### ISSUE TITLE
Make a own Hazmat Suit Mod

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#100]
Make a own Hazmat Suit Mod

**Comment by Drobac** [comment]
why? so it has durability, adds extra resistances or as an upgrade to the lava gloves?

**Comment by Dream-Master** [comment]
You have very hard jobe right ;-) looking git all time ;-)
We planing to replace the IC2 Hazmat Suit and make a own better one with many configs. (radiation, poisen etc)

**Comment by Drobac** [comment]
gotta make my pre bed surfin

**Comment by Drobac** [comment]
so a basic armor that can be upgraded tier by tier with extra resistances?

**Comment by Namikon** [comment]
Before I start with this: We should do a bit of a "brainstorming".
The only 100% proof way of negating damage would be to build this on top of the HazardousItems module, as this is the only point where I can stop damage and effects *before* they reach the player.

For everything else (IC2 uranium for example), I have to use potioneffects, or make the player invulnerable, which would render the hazmat suite kinda OP. There are some ways to stop people abusing this. For example:

- Allowing all damage from entities
- Forcing the player hold a certain item (a cobblestone..) in their hand while they handle dangerous items
- Apply something like slowness and mining fatigue 10

But this still would not prevent any *effects* being applied to the player, like the stacking IC2 radiation, which cannot be removed with milk (Can it..?). Not sure if I can remove negative effects with code.
So if you have your Hazat suite equippet, you are fine. But as soon as you switch back to your regular armor, the radiation will kill you. Not very smart

**Comment by Dream-Master** [comment]
When i be back at 7 this evening.

**Comment by Drobac** [comment]
IC radiation can be removed by milk

**Comment by Dream-Master** [comment]
Very realistic;-)

**Comment by Namikon** [comment]
Do we have the Gregtech powerarmor yet? Whats the status on that thing? I don't want to spent time on that (and it will take a few days) to make such a mod, when we won't need it afterwards

**Comment by Dream-Master** [comment]
Wait with it I think we have more important things to do.

**Comment by Dream-Master** [comment]
Ok will reopen it when we need it.
