### ISSUE TITLE
Quantum tanks/fluid storage

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1004]
Quantum tank tier1 takes EV to make. It requires a lot of resources and holds only 1,600 buckets. Fluid storage cell 4k is the same tier (ev) and requires less resources to make and holds 3x as much. Wondering why qtank tier1 is so expensive for so low storage

**Comment by Dream-Master** [comment]
Ok will look into teh recipes.
Any suggestions?

**Comment by kokochicken** [comment]
maybe taking out the niobium titanium, like moving each plate level up one. Requires EV to make and its not the greatest

**Comment by Dream-Master** [comment]
My idea is make the tanks bigger

like 2 mio, 1 mio 500.000 and 250.000

**Comment by kokochicken** [comment]
hmm?

**Comment by Dream-Master** [comment]
I will add more low Level Tanks. Some Super Tanks.
