### ISSUE TITLE
Can't craft mossy variants of GT concrete

### ISSUE THREAD

**Issue by LunarPhoenix** [GTNewHorizons/NewHorizons#1005]
There's no recipe in NEI for crafting Mossy Light Concrete Cobblestone or Mossy Light Concrete Bricks. You can craft the Dark concrete versions of these blocks with the Light versions, but the light versions are uncraftable.

**Comment by Dream-Master** [comment]
Will add a recipe if so.

**Comment by Dream-Master** [comment]
recipe for Marbel, Basalt and aoterh gt stones are missing too.
