### ISSUE TITLE
Big Engine Generator

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1006]
I think this multiblock is quite useless in EV. It give you 2k eu\t, high pollution and requare tons of machines to mantain(diesel\ndiesel, lubricant). And, near this huge monster we see... a little, small nuclear reactor with "easy 2k+ eu\t from thorium".
Ideas:
a) move engine to HV. Replace all titan with stainless, maybe add some more power(let him give HV users 2k with 4A of 512 for example)
b) make this multiblock "turbines" like - requare rotor and allow it give more than 2k with better rotor.

**Comment by kokochicken** [comment]
yeah.. it made 500k pollution in less than 20-30minutes. My idea: make it produce maybe 4k-8k eu/t instead of only 2k

**Comment by Technus** [comment]
#1007 related.

**Comment by Technus** [comment]
makes 3A EV with oxy
