### ISSUE TITLE
Air Filter multiblock

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1008]
This machine at EV reduses pollution at 160 per second. It sounds like bad joke, maybe it must reduse same amout per tick atleast?

**Comment by kokochicken** [comment]
Yeah should definitely be per tick. Almost all GT5u multiblocks on this pack (turbines/engine/filter) are not balanced well. Distill tower/oil cracker are ok but the rest are not good

**Comment by Technus** [comment]
160 per second is like 8/per tick, most multiblocks produce max 20/tick, just use a turbine and/or adsorbers to make the filter more efficient.

**Comment by Technus** [comment]
I might check how polluting are the generator/boilers blocks yes

**Comment by Cinobi** [comment]
turbines do nothing in it(use small draconium)
Absorbent filter - trolling, couse it need stacks of coal\second.

**Comment by Technus** [comment]
turbines do nothing in it(use small draconium)... - use the fckin scanner.

**Comment by Cinobi** [comment]
https://imgur.com/a/mON79
https://imgur.com/a/oebwZ
Show me fuckin difference.

**Comment by Dream-Master** [comment]
So guys come down a bit.

**Comment by Technus** [comment]
Fixed.

**Comment by killslash** [comment]
I have to comment that this exchange made me laugh a bit. 

"use the fuckin scanner"
"show the fuckin difference"
"fixed"
