### ISSUE TITLE
The Input Hatch can not accept liquid

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#1009]
![20170117183334](https://cloud.githubusercontent.com/assets/25171639/22017194/407cf77e-dce4-11e6-8fcf-75c39ab6e0e9.png)
when i update to 1.3.0.0pre4 i found that my large steel boiler input hatch cant accpet water and all of input hatch cant accpet liquid
![20170117185114](https://cloud.githubusercontent.com/assets/25171639/22017669/3f70020c-dce6-11e6-9017-90d80d97e9df.png)
i am not sure is that only me have this bug

**Comment by Dream-Master** [comment]
@technus any idea?

**Comment by Technus** [comment]
Is the input hatch a part of a multiblock? Since they wont accept stuff that the recipes dont allow.

**Comment by FallDark** [comment]
one is part of my large steel boiler but it cant accept water

**Comment by Technus** [comment]
Le derp while chaning capacity
