### ISSUE TITLE
Forestry Drawers Uncraftable

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1010]
Attempting to craft a Forestry-wood Storage Drawer or Trim block always yields an oak version.

**Comment by Dream-Master** [comment]
Which version you are using.

**Comment by Dream-Master** [comment]
1.2.1.0 or 1.3.0.0pre?

**Comment by VermillionX** [comment]
1.2.1.0

**Comment by Dream-Master** [comment]
yes try version 1.3.0.0pre i fix that already. SO dont worr wait for the next update.
