### ISSUE TITLE
High Tier Space Ores from MinerII in TF

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#1011]
i was running the GregTech MinerII in Twilight Forest to get the most out of a diamond vein we'd found near trollstone/acidrain area, i noticed several high tier/space only ores in the output, is that intended or a bug? (started yesterday night, ran for about 3 hours then + 3 hours today at MV) : 
* 9 crushed Infinity Catalyst + 3 impure dust
* 61 crushed Naquadah + 7 impure dust + 11 enriched dust
* 8 crushed Quantonium + 2 clean dust
* 11 crushed Mytryl + 3 impure + 4 crushed Mitril
* 19 crushed Meteoric Iron + 4 impure dust
* 1 impure titanium dust
* 29 crushed Iridium
* 4 crushed Osmium + 7 impure
* 18 crushed Chromite + 5 impure
* 10 impure Tungstate
* 3 clean Firestone dust
* 2 Amethyst + 8 crushed

**Comment by Cinobi** [comment]
ye, it's bag. When i plase AMiner2 in asteroid belt, it mine alot of tham shards :D

**Comment by Dream-Master** [comment]
So i need to check the TF Orgen maybe somthing went here wrong.

**Comment by Excaerious** [comment]
I think this specific problem may be due to Twilight Forest's "Trollstein" I believe its internally treated like an ore, but actually be smelted, crushed, etc. Therefore, when the MinerII mines it, it has no clue what to actually give you as a result and so gives you everything.

**Comment by Dream-Master** [comment]
Maybe maybe not will see what the cfg says first.

**Comment by ghoulsblade** [comment]
i found another diamond vein in twilight and placed the minerII again, nowhere near trollstein this time. but getting Netherrack dust, impure pile of Endstone dust, and crushed Titanium, crushed Iridium, crushed Osmium , crushed Uranium 238, crushed Uranite. No Space Ores yet, but it hasnt been running that long.

**Comment by Ugachaga** [comment]
Seems similar to https://github.com/Blood-Asp/GT5-Unofficial/pull/782

**Comment by Dream-Master** [comment]
Ok cherry pick this.

**Comment by Dream-Master** [comment]
@Technus can you please cherry pick it and look at the code changes because our version and Blood Asps different before that code too.
