### ISSUE TITLE
Mod Suggestion X.A.C.T. Crafter

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1012]
An mod which adds a crafting table with recipe memory & chest pulling 

Added on github by request 
More info on the forum 
http://gtnewhorizons.enjin.com/forum/m/36844562/viewthread/29075806-add-crafting-table-mod-xact-crafter/post/last#last

**Comment by Technus** [comment]
AE2, Project red+autocrafting table?

**Comment by Dream-Master** [comment]
So far i can see this mods not adding real new feature we dont have.

**Comment by Bryfer** [comment]
AE2 starts in an higher tier, can't say much about the projected table tho since I haven't tried if it's compatible with its sorting system. but the main reason I think this should be added is because you can save a few recipes, and you can have more than one chest next to it from which it can take items from , which is a great feature considering how many items you need in crafting 

The chest I have near my tinkers table is almost always full 

And this isn't an auto crafting table so can't compare it that way

**Comment by Dream-Master** [comment]
The Project Table can save 10 recipes too and it is not late game stuff.

**Comment by Technus** [comment]
incompatible with MT also

**Comment by Technus** [comment]
https://github.com/UniversalLP/XACT/issues/22

**Comment by Dream-Master** [comment]
Ok so we cant use this mod.

**Comment by slavatyn** [comment]
Good day,

We recently used this mod on a private NH server, and it really enhanced our experience. It duplicates the functionality of the Forestry table, but its main feature is the ability to connect to nearby chests. The internal storage in Forestry is quite limited, but with this mod, we can place four compressed chests nearby and craft almost anything. We can't view the inventory of the nearby chests through the mod, but it retrieves items flawlessly.

The recipe memory is more user-friendly in the Forestry table. Perhaps there's a way to enable the Forestry bench to connect to nearby chests like in the mod? Or maybe add the mod to the modpack?

Additionally, the mod has a nice feature that allows you to retrieve previous recipes and access NEI recipes through the mod itself. This way, you can input the final recipe, go through the components step by step, craft the initial items, and then quickly craft the final recipe through the mod, one step at a time.
