### ISSUE TITLE
Enceladus

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1014]
This planet can't be mined with adv.drill atall :D

**Comment by Dream-Master** [comment]
A bit more infos please. Screenshots?

**Comment by Cinobi** [comment]
https://imgur.com/a/h4niy
https://imgur.com/a/t6SZ0

**Comment by Dream-Master** [comment]
And GS again. @Namikon can you look into the GS code?

**Comment by Dream-Master** [comment]
Did the Mod dev do something wrong here ?

**Comment by Namikon** [comment]
No, looks fine to me. Is that Adv.Drill from IC2?

**Comment by Dream-Master** [comment]
Advanced drill from ic2 are disabled, the recipes.

**Comment by Drobac** [comment]
The drill are the ones from gravisuite mod, the ones you added 11x11 mining to

**Comment by Dream-Master** [comment]
@Namikon

**Comment by Namikon** [comment]
Well.. To be honest, no idea..
Might be Iguana Tweaks updating the MiningLevel of the Drill, but other than that, it works..?
http://imgur.com/a/cbwvB

**Comment by Dream-Master** [comment]
i remember i change mining level in 1.3.0.0 of many tools to be higher.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22569054/6bf8608c-e996-11e6-96dc-52dbc95e9ef1.png)

The Drill have Level 8+
I see you have an enchantment on it maybe thats why.
