### ISSUE TITLE
Railcraft stone recipes yield wrong material

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1016]
When making lanterns from railcraft, the lantern is meant to be the material of the slabs used in the recipe. Alas, the recipes for all the lanterns produce the wrong type of lantern. Sandy slabs makes Nether Stone Lanterns, Quarried stone slabs makes Bleached Bone Lanterns, etc...
Additionally, the slab-to-block recipes for the sandy blocks doesn't seem to exist, while nether stone slabs craft into sandy blocks, according to NEI.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/964
