### ISSUE TITLE
Wrought iron plate, extruder recipe

### ISSUE THREAD

**Issue by mannulator** [GTNewHorizons/NewHorizons#1017]
Wrought iron ingot in the bender = wrought iron plate
But wrought iron ingot(+plate mold) in extruder = "regular" iron plate

**Comment by mtesseracttech** [comment]
Yeah, I was wondering about this too, for annealed copper it makes sense that an extruder would remove the annealed part of it, but wrought iron really is an alloy that should remain the same when extruded.

To be honest, even using a wiremill would probably remove the annealing from the copper structure, which means the cable would have to be annealed after going through the wire mill.

**Comment by Dream-Master** [comment]
i read some changes blood asp did maybe i find it.

**Comment by Dream-Master** [comment]
Blood asp explained is so:
Bender is a cold recipe process and the extruder not. Thats why it turns back into iron. Same for copper.
