### ISSUE TITLE
"Fluorescent Dye" recipe not working, and not showing in NEI

### ISSUE THREAD

**Issue by Ajes1337** [GTNewHorizons/NewHorizons#1018]
http://prntscr.com/dx61qy

also "DNA dye" isnt showing up in NEI also.. but "growth medium" is showing..

http://prntscr.com/dx63w2

**Comment by Dream-Master** [comment]
Will be in the new update. Fixed allready.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/975

**Comment by Ajes1337** [comment]
The new recipes is broken, Fluorescent dye and DNA dye recipes does not show in NEI

and stuff like gregtech:gt.metaitem.02:32428 is uncraftable! according to NEI...

the new recipes was never checked in-game after changing, I gues?

**Comment by Dream-Master** [comment]
Ok need to test it and maybe change again.

**Comment by Dream-Master** [comment]
works i test it.
