### ISSUE TITLE
World Anchor fuel unavailable on private forge servers.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1019]
Apparently you can get ChunkLoader coins only through Jobs plugin, they are uncraftable.
Private forge servers have no way of chunkloading the world with offline players.

Current World Anchor fuel:
S:world.fuel=dreamcraft:item.CoinChunkloaderTierI=12, dreamcraft:item.CoinChunkloaderTierII=24, dreamcraft:item.CoinChunkloaderTierIII=48

**Comment by Namikon** [comment]
This is one of the things the Admin of private Servers needs to take care of; Among a couple other decisions about disabled/banned items. Chunk-Loading by itself is not required to beat the pack and not part of any progression.

**Comment by Dream-Master** [comment]
Change it back to default value if you like in sp or another server.
S:world.fuel= minecraft:ender_pearl=12
