### ISSUE TITLE
New Item Asbestos

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#102]
New Item Asbestos

**Comment by Dream-Master** [comment]
Maybe Asbestos String

**Comment by Drobac** [comment]
what would you use it for? its fire resistant so maybe as a part in the bronze furnace or heat proof casings for EBF

**Comment by Dream-Master** [comment]
For the advanced version of the Glows and maybe the hazemut suit.

**Comment by Dream-Master** [comment]
Not needed atm.
