### ISSUE TITLE
Rubber and Sealed Wood TiC stats are broken

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1020]
Both Rubber and Sealed wood have -0.5x durability modifier (as opposed to 0.5x) that gives any tool made with them negative durability.
Though really, both rubber and sealed wood should be considerably better than that. Sealed wood should at the very least be better than regular wood.

**Comment by Dream-Master** [comment]
I am not sure which mod add this durability modifier. Is it Tinkers Gregworks?

**Comment by Dream-Master** [comment]
This are the values from TinkersGregworks config file:
`` 
durability {
D:WoodSealed=1.0
D:Rubber=1.0

handlemodifier {
D:Rubber=1.0
 D:WoodSealed=1.0``

**Comment by VermillionX** [comment]
Yeah, I saw that. But for some reason, the stats in-game are -0.5x.

**Comment by Dream-Master** [comment]
Ok i disablled Sealed Wood and Rubber because Tools out of this MAterial are nonsens. I add a few Metals that was disabled.
