### ISSUE TITLE
Add Exo Suite recipe 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1021]
**_Please add an Exo Suite Recipe_** 

_**example For what i would use it for**_

**I wanna become a vampire **buttttt** the sun is an issue there is an armor that i can wear to allow me to go into the sun a little while longer but i need to have my Day to day armor on so i can do my normal stuff,**

**Thats why id want the Exo Suite to be added, Make it take Super conductors and Energy Flow Circuit's and The Demon Shards from Blood-magic So its hard to make but not implausible to get**

**It would be a great Quest-line to add to the pack and it would be fun to get**

**another Reason i think it needs to be added is when im doing stuff around my base some times i need to switch armor for things but armor stands Cause Mass lag and _TPS drop_ So thats out and Having them in a backpack takes a while to change out so it would be better just to have them both on at once**

j**ust Please dont make it take above IV stuff to craft ;D maby make it apart of the legendary quest line of its own of for other item's alike it that are a thing to make the game-play just that little bit more exciting :D**

**Comment by VermillionX** [comment]
Use a Locker for your armors. Right click it to instantly switch the armors in the locker with the ones you're wearing. It also recharges your armors that are in there if supplied with power. No fps loss.

**Comment by Dream-Master** [comment]
@Mylezz Did you try try this ?

**Comment by Technus** [comment]
Cause Mass lag and **FPS** drop - and only bcs of Galaxyspace also arcane crafting terminal has armor switch capabilities.

**Comment by Mylezz** [comment]
Yea but im talking about using, my magic jetpack in the pressureI space the same time

**Comment by Mylezz** [comment]
Space suit

**Comment by Drobac** [comment]
That's easily fixed, GS has a jetpack upgrade for the space suit, just needs a recipe for it

**Comment by Dream-Master** [comment]
I dont want to add this Space suit because we have enough. If this really necessary please suggest a recipe and a Tier @Drobac

**Comment by Drobac** [comment]
doesn't need anything complex, just the GS Space Suit chest with an electric jetpack in a 2k assembler. The item is already in GS, just needs a crafting recipe

**Comment by Dream-Master** [comment]
k

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22162655/da987d20-df4f-11e6-93dc-aa37123262d1.png)

![image](https://cloud.githubusercontent.com/assets/2970688/22162661/df55af72-df4f-11e6-91ec-c5cf737c980e.png)

**Comment by Drobac** [comment]
Yep,  that works

**Comment by Dream-Master** [comment]
and fixed. Drobac approved :)
