### ISSUE TITLE
Ware wolf Howl Crashes Player's that are not the wolf 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1023]
**its a potian ID Issue,**

**i went to @bigbass1997 base and when i howl and it Crashed him,
Just like when i was Crashed from the witchery id's and the Lilith Crashe's**

**Idk why the Potian ids were messed with in the first place, If u are gonna fix them the proper effect's are
Slow 1 and Week 1 for 20 secounds**

**Comment by Dream-Master** [comment]
All potion id issues i fixed. In 1.3.0.0. You can test it in the next build i release hopfully tomorrow.
