### ISSUE TITLE
Void wand Core NO Recipe 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1024]
Void wand core missing wand recipy
![f0eed5a791a458ef4b9a18ce769e40d5](https://cloud.githubusercontent.com/assets/23045776/22129739/b096de7a-de5c-11e6-933a-6d095483bcfc.png)

**Comment by Dream-Master** [comment]
Thaumic base I not nerfed yet.

**Comment by Dream-Master** [comment]
Will be in the 1.5.0.0 update.

**Comment by Dream-Master** [comment]
1.6.0.0

**Comment by Dream-Master** [comment]
allready added
