### ISSUE TITLE
Disassembling machine

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1025]
the disassembling machine does not work with disassembling machines unless crafted in vanilla bench, find this makes it hard to disassemble most things crafted another way. wondering if a way to turn machines to normal version is able to be made or something similar

**Comment by VermillionX** [comment]
Pretty sure it's intentional to prevent people from making machines via a cheap method, then disassembling them for the expensive method's items.

**Comment by Bryfer** [comment]
Just put the machine in an HV+, and you get most of it back (as dust)

**Comment by Dream-Master** [comment]
Recipe needs a Tag in GT code . GT_ModHandler.RecipeBits.REVERSIBLE

If this not there it cant be diassembled.

**Comment by Dream-Master** [comment]
Yes they get a tag when they crated so nothing i can do about it.
