### ISSUE TITLE
Tinkers' shields non-craftable with Gregworks parts

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1026]
So yeah... You can't make a Tinkers' Defense Round or Heater shield with parts from Tinker's Gregworks, even though TiGw shields are displayed in NEI. Can't switch the parts to gregworks ones after crafting either.

**Comment by Dream-Master** [comment]
Yes you cant because for this we need to update. The update have so much bugs that we need to fixe code. If @Technus or @Namikon can help with it we can update the mod.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/654

**Comment by Dream-Master** [comment]
In the newest Update Tinkers defense using smale plates for the Shields so Gregworks not compatible again.
I can add own recipes for it but how you want to repair it?
I guess without add it to the Tinkers Defense code it would be impossible to add Gregworks materials.
