### ISSUE TITLE
Blackscreen starvation

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1029]
It's likely warp-related, though not intended in this effect.
I'll on occasion i'll start blackscreening. As the name implies the screen goes completely black; not like blindness, completely black. No toolbar, no GUIs, no chat. While I can click and type normally and it'll be able to go to chat, I can't see anything. This effect is coupled with instantaneous starvation ending in death. Eating doesn't stop it, where I can't see the respawn buttons due to the black screen.
Relogging and/or closing the client doesn't solve this problem. It persists until I manage to find the respawn button and respawn.

My guess is that it's an overlap of warp's hunger effect and nightvision going all derp.

**Comment by Dream-Master** [comment]
I remember that we have a issue when Quest updates that you get a black screen but only for a few secs. What you log says after closing the game?

**Comment by VermillionX** [comment]
Nothing. It's not a crash, so doesn't leave a log.
It's also not a quest thing. Unless completing a quest causes fatal starvation...

**Comment by VermillionX** [comment]
Apparently the Black Screen of Death, along with the thaumcraft quests' black screens is due to the custom shaders in thaumcraft interacting with mods like Optifine and Betterfps and other graphics mods.
Can be disabled in the thaumcraft config.

**Comment by Dream-Master** [comment]
Better FPS and Optifine are not in the pack. So if you use it its up to you change the Thaumcraft cfg.
