### ISSUE TITLE
Charm of Keeping vs Soulbound

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1030]
If you die with a baubles item (ring, necklace or belt) that has soulbound on it equipped while carrying a Charm of Keeping III, the item is deleted instead of respawning with you.
Both the Charm of Keeping and the Soulbound enchantment should return the item to you, instead it deletes it. It's not even in the grave, and doesn't appear to affect non-bauble items.

**Comment by Dream-Master** [comment]
Did a Tooltip helps?
"Not use Charm of Keeping III, with item that have Soulbound!"

**Comment by VermillionX** [comment]
It works fine with normal armors and tools. It's just baubles that are equipped that get deleted. Probably spacesuit parts as well.

**Comment by Dream-Master** [comment]
So what can I do then?

**Comment by VermillionX** [comment]
Punch a tree?
Or the tooltip on Charm of Keeping, but specifying baubles with soulbound.

**Comment by Dream-Master** [comment]
yes a tool tip @VermillionX

**Comment by Ugachaga** [comment]
I've looked Baubles code. SoulBound support can be hardcoded to Baubles, so it will solve this issue and allow keeps soulbounded baubles in their slots on death (in the current realisation they are dropped to main inventory on death).

**Comment by Dream-Master** [comment]
@Ugachaga are you able to add this to baubles or the core mod?

**Comment by Ugachaga** [comment]
@Dream-Master  Think so. Could you fork Baubles?

**Comment by Dream-Master** [comment]
k

**Comment by Dream-Master** [comment]
Done using 1.7.10 branch as default.

**Comment by Dream-Master** [comment]
@Ugachaga https://github.com/GTNewHorizons/Baubles/invitations

**Comment by Dream-Master** [comment]
Thanks @Ugachaga
