### ISSUE TITLE
Charm of Life vs Poison

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1031]
When inflicted with poison while carrying a Charm of Life, you're instantly kicked from the server due to an "internal error" when poison lowers you to half a heart. Charm of Life is meant to keep you from dying by restoring health and giving regeneration and invincibility for a few seconds, relative to the level of the charm.
Upon logging back in, the effects of the charm of life are active and the poison status effect is gone. Though since poison can't kill you, the charm should never have activated in the first place.

**Comment by Ugachaga** [comment]
I've encountered similar strange effects when many potion effect are active and player close to die. Are you wearing any Adventure backpack that gives potion effect? Which version of Gtnh? Any logs?

**Comment by VermillionX** [comment]
Bat Backpack. Current version. Why would there be logs?

**Comment by Ugachaga** [comment]
You were kicked for some reason. Forge or server log might help.
Ok, assume that you mean 1.2.1.0.

**Comment by Dream-Master** [comment]
Hopfully fixed in 1.3.0.0.
@VermillionX can you test in 1.3.0.0 again

**Comment by VermillionX** [comment]
Kinda impossible. It's the server that kicks me, not a crash.

**Comment by Dream-Master** [comment]
The server will be updated soon. Maybe Monday.

**Comment by Dream-Master** [comment]
Ok close it now.
