### ISSUE TITLE
TConstruct:blankPattern cannot be accepted in a quest (1.3.0.0)

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1032]
This is probably because quest requires to craft it in a crafting grid, but you cannot craft it with crafting grid.

```
"questID": 536
...
      "tasks": [
        {
          "partialMatch": true,
          "ignoreNBT": false,
          "requiredItems": [
            {
              "id": "TConstruct:blankPattern",
              "Count": 1,
              "OreDict": "",
              "Damage": 1
            }
          ],
          "taskID": "bq_standard:crafting"    <-------
        },
```

**Comment by Dream-Master** [comment]
It's a crafting task. Did crafting not works ?

**Comment by EvgenijM86** [comment]
How do you craft it? The only way I know how to make is to pour down metal from Tinker's Construct smeltery. And then you just take the "blank pattern" as an item and it does not register as being crafted.

**Comment by Dream-Master** [comment]
Ah ok then it needs to be changed.

**Comment by Dream-Master** [comment]
Update 1.3.0.2
