### ISSUE TITLE
In game Bugfinder Rank??????

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1036]
**Well on the Discord Server Some of us Have the rank Bug-finder Can this be applied ingame?**

_and if so can we get this prefix  §8§kiiiiiiiiiiiii§bBug§dFinder§6]:[§5_

_it looks like this no special perms or anything just the name =) or just me because ive crashed the server so many times ;D_
![6ab1cdf78f507bb4689ed4ee7f62be0a](https://cloud.githubusercontent.com/assets/23045776/22178973/9a1749c4-dffa-11e6-8f60-24f29d2a2b17.gif)

**Comment by Dream-Master** [comment]
Sure I can try this. This thing have many letters and the last time it says Username to long.

**Comment by Mylezz** [comment]
Well its a Rank Prefix Like Elite and sutch

**Comment by Mylezz** [comment]
not a name

**Comment by Namikon** [comment]
This will break /rankup as we use Groups for the internal progression.
@Dream-Master I would be glad if you would stop "trying" things and maybe forward them to me (like it was discussed countless times).
