### ISSUE TITLE
Server stalling

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1037]
Appears in 1.2.1.0 and 1.3.0.1

Server stalls every once in a while causing timeout for all players. Happens even with no players online.
There are no logs present except for analysis from Sampler (fastcraft mod)

http://pastebin.com/M4rspZvJ

Appears to be caused by saving data of Enhanced Portals? The server thread is always first in all stall reports. We have no Enh. Portals in the server map.

Any idea what could be the cause?

EDIT:
Server log, happened at 16:32:15
http://pastebin.com/qa4kULKu

**Comment by Dream-Master** [comment]
@Namikon , @Technus any idea here?

**Comment by Namikon** [comment]
There is nothing specific in those logs; Could be heavy hardwareIO. If you run linux, install "iotop" and check the IO Load that

**Comment by Methes** [comment]
After removing fastcraft from the server we got a lot more of the following:
http://pastebin.com/3KaQPriC

Looks like something's trying to wrongly modify some data?

**Comment by Dream-Master** [comment]
Fastcraft is a client mod.

**Comment by Methes** [comment]
Actually it's both client and serverside mod, improving performance in both. You can try using it on your server, although it might have some troubles with craftbukkit.
The errors got back though so it's not solved by Java.
I'll ask elsewhere as there's nothing you can do about this probably.

**Comment by Dream-Master** [comment]
It crash the server so far i know.
