### ISSUE TITLE
Novice Thaumaturge

### ISSUE THREAD

**Issue by cristalguadian** [GTNewHorizons/NewHorizons#1038]
After gathering the Silverwood Sapling and the Greatwood Sapling, I do not seem to be able to progress in the newly unlocked "Novice Thaumaturge" Quest Line, as no new quests appear to be linked to the "Strange Things" quest, which was unlocked after completing the "What is that...?" quest in Tier 0.

**Comment by cristalguadian** [comment]
Right, on review it turns out that in order to get the next quest in the chain to appear, you need to complete the quest "Oh Shiny (Not Platinum)". 

I would request that you make the link between the two clearer, while there is some text hinting at it just having progression seemingly stop after opening the new quest line seems abrupt.

**Comment by Dream-Master** [comment]
ok remove it.
