### ISSUE TITLE
Suggestion: GT processing of HEE items

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1039]
The End is currently full of End Powder ores and Ender Goo. Both are common and pretty much useless, especially the goo.
Just asking for an HV-tier recipes to process one or both of them into something useful. Like Centrifuging 4 End Powder into 1 small pile of Endium dust, 1 tiny pile of Endereye dust and 100mb of Liquified Ender. And/or centrifuging 1000mb of Ender Goo into 1 small pile of Tungsten Dust, 1 Endereye Dust, 1 Endium Dust and 500mb of Liquified Ender.

**Comment by Dream-Master** [comment]
Will see I can add recipe without Tier breaking . Hv is stainless steel tier. So I think it must be minimum ev or iv when you get tungstensteel out.

**Comment by VermillionX** [comment]
Processing plain old end stone gives tiny piles of tungsten dust at a low chance.

**Comment by Dream-Master** [comment]
Yea true. Will add some recipes then in the next version 1.4.0.0.
