### ISSUE TITLE
Wrong item number in quest `High speed charcoal`?

### ISSUE THREAD

**Issue by hrl** [GTNewHorizons/NewHorizons#1040]
1 `Cock Oven Brick` + 1 `Infernal Brick` = 2 `Advanced Cock Oven Brick`

In step 1~3 of quest `High speed charcoal`, it needs 136 items, but 68 is enough.

**Comment by Bryfer** [comment]
Which version do you have? I wrote about this in ingame chat at 1.2.1.0 and got the answere that it's fixed "next update"

**Comment by Dream-Master** [comment]
In version 1.3.0.2 it should be fixed.
