### ISSUE TITLE
drums show info 3 times

### ISSUE THREAD

**Issue by arik4326** [GTNewHorizons/NewHorizons#1041]
![2017-01-23_22 11 12](https://cloud.githubusercontent.com/assets/23572567/22220823/f22be9b6-e1b8-11e6-8192-ce04d1b9ec18.png)
![2017-01-23_22 11 17](https://cloud.githubusercontent.com/assets/23572567/22220828/fbdbf7da-e1b8-11e6-827f-99890b271b50.png)
![2017-01-23_22 11 30](https://cloud.githubusercontent.com/assets/23572567/22220832/0173e2ca-e1b9-11e6-8b9b-77c1f26bf3b7.png)

**Comment by arik4326** [comment]
empty barrel is normal
![2017-01-23_22 13 19](https://cloud.githubusercontent.com/assets/23572567/22220894/4ad1de5e-e1b9-11e6-8309-bb757099bdc4.png)

**Comment by Dream-Master** [comment]
Wawla add here more info need to check it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22261435/3d563900-e26d-11e6-9128-ed727bbd6865.png)
