### ISSUE TITLE
Crash When using Tinkers Belt

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1042]
Here is my log
i just crashed when i tryed to use it D:
[crash-2017-01-23_12.36.45-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/724894/crash-2017-01-23_12.36.45-client.txt)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/982

You was the one who wants this belt ??????

**Comment by Mylezz** [comment]
Ik!! Idk why it crashed!!! It worked in sp!

**Comment by Dream-Master** [comment]
ask a coder about it. idk too. sorry.

**Comment by Dream-Master** [comment]
@Namikon , @bigbass1997 , @Technus any ideas?

**Comment by Mylezz** [comment]
@Dream-Master Its Crashing because the crafting was changed and its NBT data is incorrect 

[I believe this is the same problem as the bug thread named "2.1.0: Traveler's Gloves Crashes Client"](https://forum.feed-the-beast.com/threads/2-1-0-2-1-2-travellers-belt-crash-the-game.131243/)

[I posted a fix to that thread. It has to do with the expert mode Traveller's gear being crafted without Tinkers-specific NBT tags (or rather, any NBT tags at all). If the gear is crafted in normal mode, or it was crafted before the recipe change (2.1.0?), or is spawned in creatively, it works fine. If it was crafted in expert mode with the new recipe, the game will crash.](https://forum.feed-the-beast.com/threads/2-1-0-2-1-2-travellers-belt-crash-the-game.131243/)

[Since the code for the belt creates the needed tag (assuming there is already a base NBT tag compound already on the item) as the belt is swapped, you should be able to rename the belt in an anvil to get it to swap for now. (Renaming in an anvil creates a base NBT tag compound which stops the crash) If you don't want to keep the item renamed, you can rename it back by just leaving the anvil's text field blank.
 ](https://forum.feed-the-beast.com/threads/2-1-0-2-1-2-travellers-belt-crash-the-game.131243/)

**Comment by Mylezz** [comment]
@Dream-Master To fix this add a lore to the item saying to rename it in an anvil or fix the NBT data in the item crafting :D

**Comment by Ugachaga** [comment]
Maybe it could be fixed by MT script, sample for gloves: https://gist.github.com/thecybermind/4a1f3fc820abcf75f338

**Comment by Dream-Master** [comment]
Yes maybe it needs nbt data on creation . Will check it.
