### ISSUE TITLE
Cannot complete quest "A new Alloy"

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1043]
Probably because IC2 dusts are impossible to craft. And even if you find some IC2 ingots or dusts they are automatically converted to GT version.

```
"questID": 541
...
            {
              "id": "IC2:itemDust",    <------- here!
              "Count": 15,
              "OreDict": "",
              "Damage": 3
            },
```

**Comment by EvgenijM86** [comment]
I have changed it to GT copper dust and quest works now:

```
            {
              "id": "gregtech:gt.metaitem.01",
              "Count": 15,
              "OreDict": "",
              "Damage": 2035
            },
```

**Comment by Dream-Master** [comment]
Sure need to be changed to Gt dust. The problem is when I create quests and I drag and drop the item in the quest task some times I choose the wrong item. Ic2 and Gt dust looks to similar.

**Comment by Dream-Master** [comment]
@EvgenijM86 thanks
