### ISSUE TITLE
ALL TiCo items got scrambled

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1045]
All TiCo item materials seems to have been scrambled, many show the "this tool has incorrect data" error. Previously my crossbow was made of steeleaf and now it's epoxid, has a durability of -500 and a damage of 3. My bolt has gone down to 3 damage and my hammer and other tools got messed up in the same way too.

**Comment by Dream-Master** [comment]
I enable a few new metals in tinkers Gregworks but no major rework.

**Comment by Cinobi** [comment]
and this "enabling" just move all item table :D

**Comment by VermillionX** [comment]
So far it seems only TF tool materials were affected (ironwood, steeleaf and knightmetal). Turning into Epoxid (steeleaf), Polysiloxane (knightmetal) and errr... whatever ironwood turned into (no one actually uses it, so I don't know what it turned into).

**Comment by bigbass1997** [comment]
I would like to just point out that not "ALL TiCo" items are broken. I have Steel, Bronze and Titanium tools that are not broken at all. Also Mylez stated that his Unstable Ingot and Nutronium tools were also working as they should.

**Comment by mtesseracttech** [comment]
Maybe the "ALL"  was a bit too much, but pretty much all my tools seem to have material problems and everyone on the server at the time had problems with their tools. That's where that "ALL" came from.

**Comment by bigbass1997** [comment]
Duplicate issue as #1044

**Comment by Dream-Master** [comment]
Will change the cfg back. Not known that removing rubber and sealed wood and add a few more materials cause so much trouble.
