### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1046]
Ok so i started playing this game and the LV quest line would not unlock so i ran the following command

/bq_admin default [save|load]

It loaded a whole bunch of quests that i didnt see originally.  The problem however is some of them show complete but are grayed out and others are blue indicating that the reward has not been selected yet when opening the quest inside it says that its not complete.

For example: Oh Shiny (not Platinum) is blue but the items inside Diamond, Ore and Coal show Incomplete.  I tried mining those items and they dont recognize.

I tried the following command
/bq_admin reset [all|<quest_id>] [username|uuid]

to reset all my quests and then
/bq_admin complete <quest_id> [username|uuid]

to try and manually complete the ones i had already done but they end up grayed out, i dont know if this is intentional or not.

Please let me know what steps i should take to fix my questing,

Thanks!

**Comment by Dream-Master** [comment]
you did all right so far I can see. Maybe some quests bugged during update because they get new dependencies some time. Try to go in edit mode and open the quest chapter in designer mode. On the right side you have some tools to undo quests with a mouse click. Try this.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22260194/977ef020-e268-11e6-97d7-e0e4abad5267.png)
![image](https://cloud.githubusercontent.com/assets/2970688/22260203/a014c9d0-e268-11e6-97c5-d4f30ec345ce.png)

**Comment by Dream-Master** [comment]
Does it work after ?

**Comment by worsin** [comment]
This is great! This solves all my issues and i can not get my quests in order and working properly.

Thanks a ton!

**Comment by worsin** [comment]
I understand now why some were gray, if you haven't done the prerequisites and its completed you cannot open it till they prerequisites are done

**Comment by Dream-Master** [comment]
Ok god that it worked now. Can this issue be closed?
