### ISSUE TITLE
Cant Research Crimson Stained Cloth Caps..

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1047]
I cannot Research it i have all the outer Research but this 1 and when i try to make it i get
"You lack the Knowledge to understand this....."
![32b93cc6e575d4e721b34361e30268ff](https://cloud.githubusercontent.com/assets/23045776/22231686/c8bbf27a-e199-11e6-8947-f236e046e603.png)

**Comment by Dream-Master** [comment]
Yes I guess I write some aspect wrong. Will fix it later.
