### ISSUE TITLE
Chisel: Cobblestone and marble not working.

### ISSUE THREAD

**Issue by NullCascade** [GTNewHorizons/NewHorizons#1048]
You can no longer turn cobblestone into chiseled cobblestone using the Chisel mod. [NEI shows](https://cdn.discordapp.com/attachments/234936569360809996/273311688906768391/unknown.png) that you can turn chiseled cobblestone into other chiseled cobblestone, but vanilla cobblestone isn't used. 

Additionally, despite changelog statements, GregTech marble cannot be chiseled either. 

This applies to 1.3.0.4.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22259332/34430e4a-e265-11e6-99ca-66d1ba51380f.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22259441/a663fbc4-e265-11e6-818b-11521bc152c0.png)

**Comment by Dream-Master** [comment]
you nee the marble variant after smelting.
