### ISSUE TITLE
Mod Suggestion Tinker IO

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1050]
This mod original was suggested by Mylez

I think this mod is very handy automate the Smeltery from tinkers construct.

It add only 13 items in and it is easy to nerf.

https://minecraft.curseforge.com/projects/tinker-i-o

**Comment by Mylezz** [comment]
+1

**Comment by Drobac** [comment]
-1, all automation features needes in TConstruct have already been added to gregtech. Smeltery is obsolete at MV.

**Comment by Dream-Master** [comment]
@Drobac yes at MV you not use it but at Steam and Bronze age it could be usefull.
@GTNewHorizons/developers @GTNewHorizons/core what you think ?

**Comment by Namikon** [comment]
-1
I second Drobacs opinion. The smeltery really is obsolete by now with all the machines and patterns available in GT. Also tinkers caused FPS drop for me while casting items or while it's filled with material, so I personally don't like the idea to still have the smeltery in HV+ ages

**Comment by Drobac** [comment]
Also Smeltery can already be automated

**Comment by Dream-Master** [comment]
Ok will close it.
