### ISSUE TITLE
Moss & Cloud

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1051]
Ball o' Moss and Cloud Bottles from Chisel don't appear to have recipes anymore.
Basically, you throw them like splash potions. Moss balls mossify whatever blocks they hit that can be mossed (Cobblestone, temple blocks, stone bricks, etc...) and is the only way to get mossy temple blocks. I think they can also turn dirt into grass, but not sure.
The cloud bottles spawn a "cloud" of cloud blocks, which can be mined and chiselled like all Chisel blocks. Allowing transparent cloud bricks and tiles.

On the note of moss, I suggest that the recipe for mossy granite, marble, basalt bricks from GT be inverted. Currently it's 8 moss around 1 brick makes 1 mossy brick. That's kinda ridiculous for a single aesthetic block with no bonuses. It should be the other way around, or at the very least a Moistener recipe that doesn't require obscure BoP items.

**Comment by Dream-Master** [comment]
@VermillionX Are you sure we need this recipes ?
Cloud in a bottle what a nonsense.
Convince me what you want to do with it and I add some recipe for it.

**Comment by Drobac** [comment]
Uf i remember right, the recipes were removed to prevent griefing

**Comment by VermillionX** [comment]
Well then make Natura clouds chisellable into Chisel clouds.

And what I want them for is building things out of. I was mostly after the mossy blocks, especially now that you can't chisel cobblestone into mossy cobble for precantio aspects.

**Comment by Dream-Master** [comment]
Mossy cobblestone can be made with moss and cobblestone.

**Comment by VermillionX** [comment]
But temple blocks cannot.

**Comment by Dream-Master** [comment]
i add some already if you have a look in nei.
![image](https://cloud.githubusercontent.com/assets/2970688/22312383/d5c10928-e357-11e6-837b-449015af2ea5.png)

**Comment by Dream-Master** [comment]
43 recipes need to be added.

**Comment by VermillionX** [comment]
43 recipes for what?

**Comment by Dream-Master** [comment]
Sorry this comment o need to move to another issue.

**Comment by Dream-Master** [comment]
@VermillionX 
![image](https://cloud.githubusercontent.com/assets/2970688/22566693/48022d1a-e98d-11e6-9ed5-55a41f5658cd.png)
