### ISSUE TITLE
Advanced Coke Oven; Charcoal -> Coal Coke

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1052]
Charcoal gives Coal Coke inside Advanced Coke Oven

Coal Coke should ONLY be crafted using coal (not charcoal)? right?

![image](https://cloud.githubusercontent.com/assets/22825059/22291273/a805caf2-e305-11e6-9120-3c54f6fcfa88.png)

**Comment by Dream-Master** [comment]
You right will change it.

**Comment by Dream-Master** [comment]
No in my setup you can get only coal coke from coal not from Charcoal. 
The Bastfurnace can use Charcoal as Fuel but this is ok.

**Comment by Bryfer** [comment]
Can you reopen this since it's still an issue? or did you fix it in dev already? :)

**Comment by Drobac** [comment]
Guess its a MInetweaker derp? Can confirm the issue on the server, processing charcoal in the blast furnace gives you coal coke

**Comment by Dream-Master** [comment]
No it not a minetweaker derp. I add only the coal recipe.

**Comment by Dream-Master** [comment]
Its modtweaker that derps here but nothing i can do. Only will allow Coal Block.
Sorry @Bryfer no more Coal can be used.
