### ISSUE TITLE
Disable the AE2 Stuff magnet card it causes mass lag and crashes the server

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#1053]
I made the AE2 stuff magnet card and was testing it when i drooped 15k oak saplings it crashed the server because it was trying to put them in the ME system.... 

PLEASE REMOVE THIS ITEM

**Comment by Dream-Master** [comment]
So far i know the magnetic crad get a rework in the last update. Will send the serverlog to the devs.

**Comment by Mylezz** [comment]
ok thanks dream!

**Comment by Dream-Master** [comment]
Fisrt i will  update the mod.
