### ISSUE TITLE
Diamond ore is required to get battery quest.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1056]
Battery quest <- Galena quest <- Twilight Forest quest <- Diamond ore quest.

I have dug up over 100+ vertical 1x2 holes at 50 blocks intervals and still did not find it. I tried to search for it in Overworld and Twillight forest. Imo - diamond ore should be optional quest, not a requirement for batteries quest. Too much grind required for it. It would make much more sense to search for it once you have good tech to scan ores.

**Comment by Dream-Master** [comment]
I found two diamond veins not more then a hundred blocks away from my Base. With the right mining technique you will find it. Strip mining not working in this pack.

**Comment by Dream-Master** [comment]
Will look into it again later.

**Comment by kokochicken** [comment]
Dig in the middle of each chunk

**Comment by kokochicken** [comment]
Every other*

**Comment by EvgenijM86** [comment]
ok, I will try digging in the middle of a chunk

**Comment by Dream-Master** [comment]
http://gtnewhorizons.enjin.com/wiki/m/41469370/page/Mining_Guide

**Comment by EvgenijM86** [comment]
Thanks for that info. I thought that since ore veins have huge sizes (3 chunks = 48 blocks) 50 blocks between shafts are good enough to find most ores. I guess I missed diamond ore because it is smaller in size. I will try to search for it today by digging every other chunks starting at height=17.

Btw, if vein has vertical size of 7 blocks, does it mean that it will spawn at such y location that will fit all layers betweem min and max y coordinate? For example: diamond spawn between 5 and 20. In order to include 7 vertical layers it would have to spawn between 5+3=8 and 20-3=17 - is this correct?

**Comment by EvgenijM86** [comment]
Is this a right way to do it?
[https://postimg.org/image/689qw7sfz/](url)

Still no luck finding them in Overworld.

**Comment by Dream-Master** [comment]
Now you dig to often down.  Look at the mining guide.

**Comment by bigbass1997** [comment]
Actually no, that looks like a good pattern for Diamond specifically. Diamond veins are only 1x1 chunk in size (with a bit of overlap with neighboring chunks).

For more accurate mining techniques, I suggest you read the "Ores" section on this wiki http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing#Ores
(Ignore the "Default Ore Mixes" section! All those values are changed in this modpack.)

A quick summary of the Ores section is that veins will try to be generated at the center of the center-most chunk of a 3x3 chunk grid pattern as shown in this image.
![map](https://cloud.githubusercontent.com/assets/790116/22362898/ec9ad492-e42b-11e6-95e5-973f0f57cd20.png)

The image is of a top down perspective of a large region where all blocks have been removed except GregTech ores and small ores. The red lines mark the 3x3 chunk grid I mentioned. As you can see veins that were generated, generated out from the center chunk of each 3x3 section. And the veins also tend to "spill over" into neighboring sections by a few blocks at times. However you can also see that some veins are contained within only the center chunk, in which case they can be MUCH harder to find, even with my mining guide (the one that Dream linked above).

**Comment by EvgenijM86** [comment]
Actually, I don't dig often down - I create horizontal tunnels between shafts at y=17 (leg position). I can afford to this because my pickaxe Instantly break stone, so creating a horizontal tunnel is little slower than walking (need to place torches). Then I just stop and dig down from y=17 to y=5. Get back up to y=17 and continue horizontal tunnel. It would have taken ages if I dig down from the top, because ground there is at y=80+.

Ok, I gave up and just opened up MC edit to look for diamond ores. I have found:
1) one vein 100 block bellow the pattern I was making (would have never gotten there if I continue to the left)
2) one vein 300 blocks to the left of the pattern (would have eventually hit it). Those are the closes ones. So basically I would need to dig 300/16 = 19 more chunks of my pattern to the left. I have only dug 8 lines of my pattern - so that would mean I would have to tipple it's size. So yes, imagine doing this 2 times more:
https://postimg.org/image/rj2pn7irn/
3) one vein 400 blocks to the right of the pattern
4) one vein 300 blocks above

So far there is no diamonds ore in 400x400 blocks around my base. There is one ore vein in 500x500 blocks around my base. Too much digging for a single quest. Would have made much more sense if I do this quest once I have IC2 scanners (requires aluminium).

https://postimg.org/image/td2090msx/

**Comment by bigbass1997** [comment]
Seems pretty obvious you did not read a majority, if any, of what I said.

> So basically I would need to dig 300/16 = 19 more chunks of my pattern to the left.

Actually no, you would not have to mine that many chunks. If you would have read what I said, you should have seen that you would only need to mine every 3 chunks (in both directions), instead of every chunk.

> I create horizontal tunnels between shafts at y=17

Nothing wrong with that, as long as you do not leave out the vertical mining aspect of this type of strategy. Even my mining guide does not say you HAVE to start out at a specific y level, partly for the reason you are doing so.

**Comment by bigbass1997** [comment]
Oh and another thing:

> Too much digging for a single quest. Would have made much more sense if I do this quest once I have IC2 scanners (requires aluminium).

The diamond quest in the steam tier quest page, is NOT a required quest to progress in the quest book. Yes eventually would will need to find a single diamond somehow in order to get into the Twilight Forest, but you can easily go on to LV and MV tier before having to find diamond.

The IC2 scanner you mention requires a lot more than simply Aluminium, even the first once you can get, requires stainless steel which is an HV tier material.

**Comment by EvgenijM86** [comment]
Yes, you are right - my mistake. This have already been fixed, I just forgot to update DefaultQuests.json in my save directory:

https://github.com/GTNewHorizons/NewHorizons/issues/1038
