### ISSUE TITLE
GT Foil

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1059]
Make Shaped recipe to get Foils from Plates.

**Comment by Technus** [comment]
No

**Comment by Dream-Master** [comment]
Why no? Maybe my label have to changed to suggestion.

**Comment by Technus** [comment]
don't make everything craftable by hand, also making uniform foil with gt tools seems rather hard

**Comment by Dream-Master** [comment]
I want to use tools maybe a file, wirecutter and a knife or saw. Is this a good idea or should i let it like it is ?   

@Technus

**Comment by Drobac** [comment]
do you even need foil pre GT-LV era?

**Comment by Technus** [comment]
the only tool that is capable of making foil is a rolling machine, manual or electric one, we have the other tho (and dont tell me you can make 1m2^2 of foil with a hammer and anvil.)

**Comment by Dream-Master** [comment]
No but Foil are the lasest item i guess we cant make without a machine. But if it not fit i close it .

**Comment by Technus** [comment]
does not like the idea, like extrusion of small gears, is also meh.
