### ISSUE TITLE
Recipes with enchanted books

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1060]
If the recipe requires certain enchanted book, any enchanted book can be used. Apparently the reason is that books holds enchant info in NBT.

Issue covers all Fortune Lootbags and IronGolem Backpack.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22563150/b06f7230-e97f-11e6-8500-be757f932c9c.png)
![image](https://cloud.githubusercontent.com/assets/2970688/22563151/b42770e4-e97f-11e6-9694-145fdb7f8bd0.png)
![image](https://cloud.githubusercontent.com/assets/2970688/22563157/b8aa12d4-e97f-11e6-97cd-d20f15a032a2.png)
![image](https://cloud.githubusercontent.com/assets/2970688/22563162/be55af90-e97f-11e6-8fa9-df038635c700.png)

**Comment by Ugachaga** [comment]
Original issue is solved, but now NEI doesn't show which Book exaclty is needed:
![enchbooks](https://cloud.githubusercontent.com/assets/19178671/23590534/745975cc-0214-11e7-9379-2a3417752449.png)
![enchbooks1](https://cloud.githubusercontent.com/assets/19178671/23590537/76f00cc4-0214-11e7-95f0-8d91645ab50b.png)
This may confuse players.

**Comment by Dream-Master** [comment]
maybe i add a tool tip to the Enchanted loot bags "Fortune 3 Book needed"?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24208639/607fd556-0f24-11e7-83e5-a72b9c21fd56.png)
