### ISSUE TITLE
Farm logic quest #583 fails to complete.

### ISSUE THREAD

**Issue by Giovanni-NL** [GTNewHorizons/NewHorizons#1061]
Step 1 of quest Farm logic #583 completes after creating the various items.
However, after creating the Basic Circuit Board (item 4830) using a carpenter in step 2 the quest system does not detect the item, and the quest is not completed.  

Using version 1.3.0.5 of the modpack.

**Comment by Giovanni-NL** [comment]
The same thing happens for quest #584.  The first step of the quest is ok, but the soldering iron you create in step 2 is not recognized as you have it in your inventory, and the quest does not complete.

**Comment by Giovanni-NL** [comment]
Oops, did not mean to close.

**Comment by Dream-Master** [comment]
Ok I need to check it. Maybe nbt data not match.

**Comment by Giovanni-NL** [comment]
The same happened for quest #593, "Farm logic enhanced".  I did some digging, and foud the fix.  Using bq_admin I changed the required item to the item that I actually made using a Carpenter.  
The original DefaultQuests.json has this
"requiredItems": [
            {
              "id": "Forestry:chipsets",
              "Count": 1,
              "OreDict": "",
              "Damage": 1
            }
The updated config has this:
"requiredItems": [
            {
              "id": "Forestry:chipsets",
              "Count": 1,
              "OreDict": "",
              "Damage": 1,
              "tag": {
                "T:4": 1
              }
            }

For quest 583 "Farm logic" it needs to be this:
"requiredItems": [
            {
              "id": "Forestry:chipsets",
              "Count": 1,
              "OreDict": "",
              "Damage": 0,
              "tag": {
                "T:4": 0
              }
            }

For quest 584 "Change your farm circuit configuration" this:
"requiredItems": [
            {
              "id": "Forestry:solderingIron",
              "Count": 1,
              "OreDict": "",
              "Damage": 0,
              "tag": {
                "Slots:10": {
                  "1:8": ""
                },
                "UID:4": 109547956
              }
            }
Note: that is a fresh, never used, soldering iron. 

For quest 594 "Farm logic refined" this:
"requiredItems": [
            {
              "id": "Forestry:chipsets",
              "Count": 1,
              "OreDict": "",
              "Damage": 2,
              "tag": {
                "T:4": 2
              }
            }

And finally for quest 595 "Farm logic intricate" this:
"requiredItems": [
            {
              "id": "Forestry:chipsets",
              "Count": 1,
              "OreDict": "",
              "Damage": 3,
              "tag": {
                "T:4": 3
              }
            }

**Comment by Dream-Master** [comment]
Ok thanks will try it. But ignore nbt data would be more easy i guess if your circuit have another settings.

**Comment by Dream-Master** [comment]
Works for me changed it to ignore nbt tag.
