### ISSUE TITLE
Nitro fuel does not generate power with Basic Diesel Generator.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1062]
I just tried using Basic Diesel Generator and put 1 universal cell with nitro fuel in it. It show 999 fuel remaining and it does not generate any power to any machines that I tried. I also tried placing 1x and 16x tin cable between generator and machines - did not work. It connects visually to cable but does not provide any power. What do I need to do for it to generate power?

In normal GT version I just connect it to any machine that accepts power, put any fuel cell and it works.

**Comment by EvgenijM86** [comment]
I tried it with oil universal cell and it worked. For some reason nitro fuel does not work.

**Comment by Technus** [comment]
EU value of nitro diesel is too high to work in LV diesel

**Comment by Dream-Master** [comment]
I add a Tooltip
![image](https://cloud.githubusercontent.com/assets/2970688/22558634/ad71ad16-e96e-11e6-9133-8835846f2b35.png)

and a Quest note:

![image](https://cloud.githubusercontent.com/assets/2970688/22558683/d24bafe2-e96e-11e6-9250-101c3fc50421.png)
