### ISSUE TITLE
How to repair Hazmat Suit?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1063]
Tried to repair my hazmat suit (scuba helm, hazmat armor+legs, rubber boots) in the anvil using Rubber ingot/sheet/pulp, neither is working? Is there a way to repair the hazmat suit?

**Comment by Dream-Master** [comment]
I could add an recipe that work with partly damaged Armor. Not sure if this is a good idea.
@Technus, @Drobac ?

**Comment by Technus** [comment]
make a new one not like they are that expensive, ic2 never had repair recipe also.
