### ISSUE TITLE
Suggestion: Thaumcraft aspects for Galacticraft stones

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1064]
Basically everything on other planets is void of thaumcraft aspects. They don't need anything special, just aspects pertaining to their location and material:
Alienis & Vacuous for Moon turf, dirt and rock
Tenebra, Vacuous & Gelum for Asteroid Rocks
Ignis, Metallum and Terra for Mars Rocks.
Alienis & Gelum for Dense Ice.
Ira & Superbia for dungeon bricks.
And so on...

**Comment by Dream-Master** [comment]
Sure a lot more mods need Thaumcraft aspecks to materials.

**Comment by mtesseracttech** [comment]
IC2 also doesn't have aspects for most of its items/blocks

**Comment by Dream-Master** [comment]
@mtesseracttech for ic2 i will open up a new issue
