### ISSUE TITLE
Tinker's tools with Auto-smelt modifier destroy certain blocks.

### ISSUE THREAD

**Issue by mannulator** [GTNewHorizons/NewHorizons#1065]
Not sure if its intended, but I hit my Iron tank wall with the tinkers hammer that has Autosmelt on and it turned it into a bunch of iron nuggets :)

Also related; maybe you should remove the auto smelt modifier from the list of modifiers you can get via iguana tweaks when you level up - I got auto smelt on my hammer, and i really do not want it.
Mining cobblestone makes so many fiery flames pop up on my screen, i had to disable my particles in video settings.
I don't think you can remove modifiers, and making another hammer would be a huge step backwards. It feels more of a "choice" modifier that not everyone wants.

**Comment by Dream-Master** [comment]
Never test it.
@Drobac , @Tec, @Namikon, @bigbass1997  what you think ?

**Comment by Technus** [comment]
Auto-smelt and well as , repair and silktouch could be disabled from being achieved randomly.

**Comment by Dream-Master** [comment]
What the others think because this is a big thing? So no early game silk touche and repair anymore.

**Comment by Bryfer** [comment]
If you remove those random modifiers maybe add an quest so you can choose one of the three early game? Maybe 3 times tho since axe, shovel, pickaxe?  upon creating those tools for the first time maybe?

But I agree getting auto smelt is annoying when you got a good pickaxe

**Comment by EvgenijM86** [comment]
Auto Smelt and Fire Aspect are two enchants that ruin equipment. The second one makes weapons unusable against teleporting enemies. I think they should be removed from list of level-up enchants if such list exist. If somebody wants them they should use appropriate item at tool station.

**Comment by cyres** [comment]
Auto Smelt is not removed entirely, i just had an auto-upgrade with autosmelt. I don't know why these two commits are not enough but you may change the main.cfg in IguanaTinkerTweaks.

**Comment by Dream-Master** [comment]
ok will check later.
