### ISSUE TITLE
better questing bug

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1067]
I was working my way through some of the new quests with 1.3.0.5 and I got to the quest called "farm logic" and did what it asked. Got part 1 done, but when I crafted the item needed for part 2, it wouldn't let me submit it.
Also, in thaumcraft, I was doing the quest to make crystal clusters, and it wasn't working, and it seems that you need to click detect after you make each cluster, or it won't count them. 
Lastly, in thaumcraft, I made the 92 arcane stone blocks needed for "not just for decoration" and I got a similar problem, of it not detecting it when I click detect. I'm going to retry it clicking detect after I make each 8, and see if that works, then update this with what happened. 

EDIT: tried making the forestry circuit again, and it still won't detect

**Comment by Dream-Master** [comment]
Fixed. Next update.
