### ISSUE TITLE
Recipe dupe? Obsidian -> Obsidian plate

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1068]
In the (basic) cutting machine there is two recipes for obsidian, one that yields 1x plate, and the other 9x plates both for 1x obsidian
![image](https://cloud.githubusercontent.com/assets/22825059/22430894/f8c5d4ce-e70f-11e6-8c40-0fd789f8ee52.png)
![image](https://cloud.githubusercontent.com/assets/22825059/22430965/3925bdd6-e710-11e6-9bea-4aa22e26a7df.png) 
Not sure if this is the recipe problem? since I cant see the one that gives 9x in the correct machine?

-------
Picture when cutting 36 obsidian below
![image](https://cloud.githubusercontent.com/assets/22825059/22430986/4501a066-e710-11e6-9d77-a66339ef8375.png)
![image](https://cloud.githubusercontent.com/assets/22825059/22431789/0d00d724-e713-11e6-81f8-8480bd8b103a.png)

**Comment by Technus** [comment]
iirc we need to set it to 1block to 8plates
and check if TiCo or other mods don't allow making a obsidian block from obsidian ingot

**Comment by Dream-Master** [comment]
The recipe using 32 eu but i cant find the mod registered it.

**Comment by Dream-Master** [comment]
I remove the 1 Block = 9 Plates recipes

**Comment by Dream-Master** [comment]
Block Cutter from ic2 arn't able to craft.
