### ISSUE TITLE
Better automation of Ass Line

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1069]
Better automation of Ass Line.

@Technus any idea if and how we can do it ?

**Comment by Technus** [comment]
WHY, let ppl suffer. also you can automate it with OC

**Comment by Dream-Master** [comment]
@Technus You so you think we not need to do here anything?

**Comment by Drobac** [comment]
It is hard to automate, even with AE its impossible and the need for a different chip in each one doesn't help. To make it automatable it would require a rewrite of how the assembly line works so doubt its doable. Only way to automate is by combining a few mods together, personally i use dimensional transceiver with crafting export buses on them (ensuring only one stack can be in the buffee)  and ender io conduits with filters on the other end. Better automation could be done with steve's factory manager or using OC

**Comment by Technus** [comment]
i could make a Assline recipe container, that would allow the assline to see multiple recipes at once.

**Comment by Drobac** [comment]
That would help, reducing the number of assembly lines needed for automatically

**Comment by Dream-Master** [comment]
We get new Block wich can hold 9 Data sticks.
