### ISSUE TITLE
EBF LV Enery Hatches quest

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1072]
EBF really needs just 2 LV Energy hatches. There is no need to make 4.
The only reason why the GT achievement for EBF says you need 3 LV Energy Hatches is because you couldn't fix the burned out circuitry without soldering iron, which wasn't working at the time. This was fixed ages ago and noone bothered to fix the achievement.

It just bothers me to make 2 completely useless LV Energy Hatches for no reason just to get the quest.

**Comment by Dream-Master** [comment]
@Lainiel show me your setup where your EBF works with only two LV Energy Hatches in GTNH and produce let me say Alu.

**Comment by Technus** [comment]
Each energy hatch can accept 2A, but the Multiblock machine tier is counted by using the formula of 

HatchVoltge*1A+...(for each hatch)
Then round that up to the nest tier.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22555509/3869069a-e964-11e6-802e-6462739fd60f.png)

**Comment by Lainiel** [comment]
Awesome. Thanks for the quick fix.

**Comment by Dream-Master** [comment]
Please  don't close not published fixes. Thanks
