### ISSUE TITLE
Another Biogas issue - could be intentional

### ISSUE THREAD

**Issue by mannulator** [GTNewHorizons/NewHorizons#1074]
I noticed something in the biogas production, i'm not sure if its intended but:
The distillery with circuit #4 produces 1025 biogas. It seems that the max it can output into pipes is 1000 per operation - everytime it produces biogas, it instantly pumps out 1000biogas , and leaves 25biogas behind. Then a second later, the 25biogas is pumped out. Only after that, it starts producing another round.

What that basically means is that the distillery production literally takes twice as long(because it will not start making biogas until all from the last operation is pumped out). In theory, if it produced 1000biogas instead of 1025, it would work twice as quickly!

And the gas is pumped out through pipes that can do 7000L/sec, so its not them causing the bottleneck;
I haven't tested if using some other method of output would grab the entire batch of 1025 at a time(ie. translocators etc.), instead of the machine's option to do it directly into pipes

At any rate, this may have been done on purpose, to slow them down.
Or worse, It could just be a dorky way of the client showing me this info when it displays the 25 leftover biogas in the distillery's output storage...

**Comment by Dream-Master** [comment]
Yes will change it to 1000.

@mannulator Thanks for testings.

**Comment by bigbass1997** [comment]
Be sure that when you change it to 1000, that you change the input value as well, in order to keep the same ratio of biomass to biogas.

**Comment by Dream-Master** [comment]
Sure when i change the value i will keepte ratio.

**Comment by Technus** [comment]
LV machines have speed limit of 1bucket per operation, but you can use pumps to accelerate it!

#l2p

**Comment by Dream-Master** [comment]
yes but limit it to 1000l will fix it too.
