### ISSUE TITLE
Auto-Enchantment Table recipes

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1075]
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Open-Blocks.zs#L247-L251
https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/CoreMod.zs#L2123-L2138

There can be only one!

**Comment by Dream-Master** [comment]
Oh funny maybe i never removed it.
