### ISSUE TITLE
World leaks

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1076]
This is NOT shown in server console, ONLY in fml-server.log.
Problem happens upon starting up the server, eventually reaching thousands of leaks and timing out any player trying to log in, as the server fails to do anything. Restart fixes that.
Happens in 1.2.1.0 and in 1.3.0.5 too.

How to reproduce:
Setup fresh server, accept eula, start up the server.
Happens about every minute.

http://pastebin.com/V6hhD2K6

**Comment by Dream-Master** [comment]
Yes remember we had this long time ago too.
@Namikon did you remember how we fix that ?

**Comment by Namikon** [comment]
IIRC, that was before we decided to switch over to a cauldron based server. There wasn't a fix for this as it didn't cause us any of the described problems. It just appeared in the logfiles, and one day it was gone.
My suggestion would be to try to run the server with the latest Thermos build and check if the issue persists

**Comment by Methes** [comment]
Thanks for the idea, will try that later. Not your problem anymore so will close this ;).
