### ISSUE TITLE
NullPointerExceptions - possibly Mobs

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1077]
Server is spammed with this error
http://pastebin.com/P4xNVrbg

Eventually the report function says f*ck it and just says NullPointerException as seen lower in the pastebin.

Happens when dealing with a lot of mobs (spawner farm, running in the Nether - spawning/despawning).

**Comment by Dream-Master** [comment]
@Methes this is Thaumic Bases
``
    at tb.utils.TBUtils.addAspectToKnowledgePool(TBUtils.java:18) [TBUtils.class:?]
    at tb.common.enchantment.EnchantmentHandler.onMobDeath(EnchantmentHandler.java:130) [EnchantmentHandler.class:?]`
``

But i can't say much @Namikon, Technus

**Comment by Methes** [comment]
I just noticed it's probably caused by killing some enemies with Extra Utilities Diamond Spikes.

**Comment by Namikon** [comment]
Another FakePlayer issue. I'd propose a pull request but the repository (https://github.com/Modbder/ThaumicBases/tree/maste) hasn't been updated for over one year so I doubt it's of any use...

**Comment by Dream-Master** [comment]
I removed the Fork for now (to many errors)have to it fork again.

**Comment by Dream-Master** [comment]
We need to try with the newest version.
