### ISSUE TITLE
Diable IC Cables and change Recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#108]

**Comment by Dream-Master** [comment]
Done.

**Comment by Teteros** [comment]
IC2 cables can be still crafted. (The opposite way of GT wires if using the wire cutter).
Is this intended?

**Comment by Dream-Master** [comment]
I will check this later . Maybe i have to delete my recipes.

**Comment by Dream-Master** [comment]
done
