### ISSUE TITLE
Other way to get the Draconium Ingot

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1081]
The usual way:
![1](http://i66.tinypic.com/zvq80l.png)
![2](http://i66.tinypic.com/117ss3r.png)
Other way:
![3](http://i65.tinypic.com/5vn5ty.png)
![4](http://i66.tinypic.com/nw6sz.png)
![5](http://i65.tinypic.com/359xws0.png)

Also I think there are something wrong..
![qq 20170203201455](https://cloud.githubusercontent.com/assets/25528572/22591076/933235da-ea4d-11e6-8887-e98ca0148a2a.jpg)

**Comment by Dream-Master** [comment]
Not possible with 1,3,0,5
Cells cant be filled with Draconium Dust any more.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22593679/120c8578-ea20-11e6-918c-798375f439ea.png)

This is the normal view. You have the item name enabled.

**Comment by Dream-Master** [comment]
Update your client/Server to 1.3.0.5 and all would be fine.
