### ISSUE TITLE
2 Types of Honey

### ISSUE THREAD

**Issue by AntonioNoack** [GTNewHorizons/NewHorizons#1086]
There are two types of honey (fluid), both named honey, but the carpenter accepts only the forestry honey and not the Biomes O Plenty honey. Since both is named honey, both should work or at least there should be some distillery recipe for the conversion.

**Comment by Technus** [comment]
Cross compatibility distillery recipes exist.

**Comment by AntonioNoack** [comment]
oh didn't know that, thx :)

**Comment by AntonioNoack** [comment]
they are shown only when you click at the gregtech ones, cuz of that I didn't know
