### ISSUE TITLE
Cassiterite Sand, Macerator recipe missing?

### ISSUE THREAD

**Issue by Rublebuble** [GTNewHorizons/NewHorizons#1091]
Hello
The recipe, for Ground Cassiterite Sand in the macerator, is missing in NEI.
For the item "Cassiterite Sand 1959:937" but its working and you get 4 Ground Cassiterite Sand

**Comment by Dream-Master** [comment]
Not much i can do i guess.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22791073/7970a286-eee8-11e6-8c16-f1f18c23aebe.png)
![image](https://cloud.githubusercontent.com/assets/2970688/22791082/7cf47c20-eee8-11e6-952b-fd1d30ebe544.png)

works for me.

**Comment by killslash** [comment]
Hello, I just found this issue as well. It shows up in NEI the "Pulverizer" machine, but not the macerator. However every other type of Cassiterite sand shows up under macerator.

For a long time i thought it didn't macerate, and you needed a pulverizer. 

I also ran in to the issue of hoppers not feeding the 937 sand in to macerators, presumably because it doesn't see it as a valid recipe. However manually placing the sand in there works.

**Comment by killslash** [comment]
ID for Stone Ore is 1963:937. 
ID for Crushed ore is 6544:5937

**Comment by Dream-Master** [comment]
So Nei is fixed. Ore can be macerated in Steam furnace but the hopper not works. Tested with other Ores and it dont works too.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24478358/dba2c390-14da-11e7-8b54-ea800a7b945c.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24478368/e0eef846-14da-11e7-9b2d-29299ecbe218.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24478373/e524b324-14da-11e7-9df5-98da5b40fa56.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24478412/030a0cae-14db-11e7-94ae-fe1125dd6977.png)
from the side its works. So issue is fixed i guess

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24478429/12ce6702-14db-11e7-8101-9c0249d4108f.png)

**Comment by Technus** [comment]
@Dream-Master NO GT MACHINE accepts input from FRONT

**Comment by Technus** [comment]
And now check if the recipe is still giving byproducts in pulverizer...

**Comment by Dream-Master** [comment]
@Technus i added a macerator recipe need to add a pulverizer recipe.
