### ISSUE TITLE
EBF not working at all, not even a little

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1095]
So i built the ebf, it turned green for a little then red because no power or things to process etc, and when i finally had set up enough power it just wont turn on, i watch people do their in videos, i went into creative and replicated it and well nothing, just stay red, went to discord for help, used scanner on it, nothing was wrong according to it, yet when i hit the controller with the mallet it just stays red, i have built it 5 times, found out about how chunk boarders can mess with it and again nothing, tried only using tools instead of duct tape and again nothing, whole lots of nada. so i am really stuck, was a bit livid/ rageful earlier (kinda spent like 5-6 hours trying to get it to work with no results). anyway found this github page and so i am writing this. btw so far i have loved gt horizons it is very fun but I have hit a block in the road known as alluminium. everything is setup like it should be, i have hit it with mallet hundreds of times and still red, plz help. here are some images, 2 from creative try while in discord, the rest is my survival build: http://imgur.com/gallery/FpoGH              P.S. i tried switching from curse to tekkit launcher and nothing changed.

**Comment by VermillionX** [comment]
If you're trying to make Aluminium. You need 2 LV energy hatches, each with a battery buffer directly against them with 2 batteries in each. Lithium batteries are best, though if you're supplying enough power to the buffers from generator(s), it should be fine.
If you're using cables to connect to the energy hatches you won't get enough power due to the cable's energy loss.

**Comment by Ugachaga** [comment]
You forgot that recipe required configured circuit.

**Comment by Technus** [comment]
Closing this.
