### ISSUE TITLE
Fulguric/Amped Bees? (Blinding Work speed)

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1098]
Hello, I am looking in to bees at the moment and I can't seem to find a way to get the highest bee production speed (Blinding Speed). It seems like there are species that have them (fulguric and amped) but they do not seem to be able to be bred.

Is this a balance decision to have 1.7x as the highest speed multiplier (fastest) instead of 2.0(blinding)?

**Comment by Dream-Master** [comment]
not that ik.

Is there no recipe for breeding it ?

**Comment by killslash** [comment]
It seems that way. Fulguric and Amped bees do not even show up when directly searched in NEI. \

You have to search the Blinding speed gene sample in NEI, then it says they come from those two bees, However clicking on the bees do not show any way to breed them in NEI. Also, NEI seems to think they are an oblivion bee, because clicking on them shows them as the quest reward for Playing God (this gives oblivion bees). 

Curiously enough, there are a couple that I found that do not show up in NEI, but have a serum. Endearing, winsome, and carbon. http://ftb.gamepedia.com/Endearing_Bee

**Comment by Dream-Master** [comment]
Maybe this bees only enabled when other mods be in the pack.

**Comment by Dream-Master** [comment]
Enderium is a Thermal Expansions Bee i guess. We dont have that mod in the pack. I can add Bees via Gendustry cfg if we need them.

**Comment by Dream-Master** [comment]
https://github.com/MagicBees/MagicBees/blob/master/src/main/java/magicbees/bees/BeeMutation.java#L343

This is a Thermal expansion bee and only visible if this mod is present.

**Comment by killslash** [comment]
Ah okay that explains the endearing bee, though there is Tinkers Construct enderium (there is also some gregtech enderium ingots and such) that they could be used for.

I'm not sure what mod enables Fulguric or Amped bees. It looks like they are the only two species that have  Blinding Speed in the pack as far as I can tell. 

If adding or changing a species to have blinding speed is too difficult, would a quest reward in the Bees section that awards a handful of blinding gene samples from GenDustry be okay? That way players can inject it on to some bees and then breed up drones for further propagation.

**Comment by Dream-Master** [comment]
I will go over the bees and add maybe some high tier bees with blnding speed gene or add them to existing bees. Not sure which bee are best for this gene?

**Comment by killslash** [comment]
Thematically some kind of "fast/firey/electric" magical bee would work. Though not sure if any currently existing ones in the pack are high enough tier for the best speed bee

**Comment by Dream-Master** [comment]
Plutonium Bees maybe ?

**Comment by killslash** [comment]
Yeah either one of those would work. Nuclear is speed themed I suppose

**Comment by Zoko061602** [comment]
What about a thorium bee, it's nuclear and it's not that OP since you can get Thorium easily out of coal ore.

**Comment by Dream-Master** [comment]
@Zoko061602 added allready with your last uplaod.

**Comment by Dream-Master** [comment]
Will look into it later how blinding speed can be obtained.
