### ISSUE TITLE
Pam's Harvescraft water crops broken

### ISSUE THREAD

**Issue by Kate-Han** [GTNewHorizons/NewHorizons#1100]
Here's the list of problems I've found:

- Cannot place water gardens without breaking them, even in water with a dirt block directly underneath
- Cannot craft rice or cranberries into seeds; when I try, I am able to hold the seeds on my cursor for a few frames, then the seeds disappear back into the respective crop
- Cannot plant rice or cranberries in water, even with a dirt block directly underneath

**Comment by Cinobi** [comment]
Don't know about other things, but about rice... http://imgur.com/a/ccAdd

**Comment by Kate-Han** [comment]
Now that makes even less sense! Rice is supposed to require water to grow, not tilled land

**Comment by Dream-Master** [comment]
Complain on pams side. I can't remember that you can grow seeds in water ( only witchery seeds)

**Comment by VermillionX** [comment]
Water gardens can only be placed on grass/dirt, not on water. Though they will spread onto water.

**Comment by Kate-Han** [comment]
Thanks for the update, I guess I can farm these things the slow and random way at least

**Comment by Dream-Master** [comment]
Can this be closed?

**Comment by EvgenijM86** [comment]
I was able to successfully grow all of the pam's harvestcraft plants, including rice and cranberry. Cannot reproduce this.

**Comment by Dream-Master** [comment]
Ok Thanks for the Info @EvgenijM86
