### ISSUE TITLE
Magnum torch

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1101]
It's not working even to vanilla mobs :c 

https://imgur.com/a/02Gs8

**Comment by VermillionX** [comment]
I figured it just didn't work on space mobs when I used it on the moon. I'm guessing that Special Mobs overwrites its' effect.

**Comment by Cinobi** [comment]
It not work in void and overworld too :)

**Comment by Dream-Master** [comment]
Extra Utilities is not a open source mod. So nothing i can do here.
@Namikon @Technus any idea here ?

**Comment by Dream-Master** [comment]
Nothing we can do here.
