### ISSUE TITLE
Iron, Steel, Copper using Railcraft plates

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1102]
This is something that has been bugging me for quite a while now.
Iron, Steel and Copper plates looks diffrent than the rest
![](https://cdn.discordapp.com/attachments/244932288415006720/279968748541181962/unknown.png)

**Comment by damug** [comment]
I've dickered with it and it seems like you can solve this by setting a couple flags to false in the \gregtech\unification.cfg file

See screenshot below for the railcraft lines you'd change from true to false.

![unknown](https://user-images.githubusercontent.com/29874719/28399410-b36edc8a-6cc1-11e7-92a4-0f1d9cb4d8aa.png)

**Comment by Dream-Master** [comment]
@damug yes thats right but i need to check if al recipes are work after it. Most of Railcraft rcipes are nefed so maybe it works very god.
