### ISSUE TITLE
Suggestion: Replace Tungstensteel dust in Energetic Alloy recipe.

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1103]
Currently, Energetic Alloy is an MV-tier material used in many EnderIO machines. It's used in large quantities, but requires of all things, EV-tier Tungstensteel dust to be crafted. By the time you can make energetic alloy in the amount required for advanced eIO automation you're already using AE2 for automation.
So I suggest replacing the Tungstensteel in the Energetic Alloy recipe for something less... dense. There's a lot of (un)common-but-(semi)useless MV-tier metals that could take Tungstensteel's place in the recipe, along with a half dozen standard metals:
Beryllium
Vanadium
Vanadiumsteel
Neodymium(1)
Lanthanum(1)
Cerium(1)
Caesium(1)
Red Steel(2)
Black Steel(2)

(1) = Available in the overworld via full ore processing of Redstone ore or centrifuging Skystone meteors. Easier to obtain at HV+ via space ores.
(2) = If you just want people to suffer. While not overly difficult to make, they require so many different materials that people will want to kill themselves. Especially getting Bismuth.

**Comment by Dream-Master** [comment]
@VermillionX Black Steel isn't that bad read steel is much more mean.
