### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1105]
I crash when i load the world. 
Here is the crash log.
I did a clean install and created a completely new world. It still crash.

[crash-2017-02-12_23.32.26-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/769387/crash-2017-02-12_23.32.26-client.txt)

**Comment by Dream-Master** [comment]
Not try to disable hardcore darkness. This isn't possible in this pack.

**Comment by bigbass1997** [comment]
Dream is correct. Do not try to disable the Hardcore Darkness feature. You will not be able to load into either singleplayer or multiplayer.
