### ISSUE TITLE
Ore Dictionary Problem with Silver.

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1108]
Trying to auto load "Crushed Silver" into the Advanced Chemical Bath does not work.

Ive tried it with Conveyors, Pipes and even a Hopper.  Silver just sits there and wont auto load.  I can manually place it in and it works so i think its an Ore Dictionary problem perhaps,

**Comment by Cinobi** [comment]
There are alot of "crushed" problems. How it look like - http://imgur.com/a/jGxqe . This "_crushed_" ignored by gregtech machines(include sorting ones, like typefilters). I find Ir,Pt,Ag,SpPb,SpPu and desh crushed ores bugged that way. I think there is some problems with small ores drop.

**Comment by Dream-Master** [comment]
@Technus any idea here?

**Comment by Technus** [comment]
Java enum/class size limits and or wrong/broken registration of item.

**Comment by Technus** [comment]
Correction: something writes display name tag to this items, just like Vanilla anvil.

**Comment by Dream-Master** [comment]
@Technus anything we can do against it ?

**Comment by Technus** [comment]
Recompile all the mods that do it?

**Comment by Technus** [comment]
Or provide name stripping thing.

**Comment by Technus** [comment]
Need to implement some kind of name remover for that.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/15e2d0189c5d0e6d9f8ff7e8a9ec517644ee1ba5

Fixes the thing stated above

**Comment by Technus** [comment]
@Dream-Master add recipe somewhere at tier 0
