### ISSUE TITLE
Foci of dislocation duplicate Chest

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1109]
When i try to take compressed chest with this foci, it works, but chest drop as loot, so i get 2 chests. One in foci(sucsessfuly plased in the world later) and dropped one. This will not happen again when i try, so just keep in mind this.

**Comment by Cinobi** [comment]
Today it happend again - https://imgur.com/a/AzEaP , so look at it more precisely please :D

**Comment by Dream-Master** [comment]
@Cinobi Are this only possible with compressed chests or with other chets too ?
