### ISSUE TITLE
Forge microblocks

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1110]
Atleast smooth black granite don't have them - i think another greg blocks may not have them too. Fix it please :D  http://imgur.com/a/mxAMT

**Comment by VermillionX** [comment]
Galacticraft/GalaxySpace building blocks and glowstone too.

**Comment by Dream-Master** [comment]
@Cinobi 
 "Fix it please :D " XD

Ask better here:

https://github.com/Chicken-Bones/ForgeMultipart

**Comment by Cinobi** [comment]
https://github.com/Chicken-Bones/ForgeMultipart/issues/390
easy, but ur issue will be much more better than mine, @Dream-Master

**Comment by bigbass1997** [comment]
This is not something to be "fixed" and the devs won't do anything to "fix" it. ForgeMultipart already allows people to add blocks to become multiblocks.

@Dream-Master You can add these yourself to the modpack in the microblocks.cfg file. In the file it will explain the formatting for how to add blocks. I do not know why the file is not in the repo, but it definitely exists.

**Comment by Dream-Master** [comment]
Sure can add it to the config. Didnt know it.
