### ISSUE TITLE
Growth medium

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1111]
Add recipy with distilled water please - keep mixer only for this - not good.
http://imgur.com/a/W96SU

**Comment by Dream-Master** [comment]
So you mean add an additional recipe with distlled Water or delete the existing one?

**Comment by Cinobi** [comment]
As u wish, dream - but it's better to make as usial - work with both water, but with undistilled one - takes more time.

**Comment by Dream-Master** [comment]
k can add it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23033928/38022c2e-f47a-11e6-9179-c60b89ac42cd.png)
