### ISSUE TITLE
OpenPeripheral Addons mod

### ISSUE THREAD

**Issue by heatskr** [GTNewHorizons/NewHorizons#1112]
Please add OpenPeripheral Addons to give more utility to OpenComputers.

It adds few but very useful items like Terminal glasses, inventory selector, PIM...
This mod is common on FTB packs.

https://mods.curse.com/mc-mods/minecraft/228818-openperipheraladdons

**Comment by Dream-Master** [comment]
Will look into the Mod.

**Comment by Dream-Master** [comment]
Core mod is needed too
https://minecraft.curseforge.com/projects/openperipheralcore/files/2280607

**Comment by Dream-Master** [comment]
recipes needs to be nerfed.
