### ISSUE TITLE
Sever crash and backup

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1113]
My server just crashed just when I got killed in the Twilight Labyrinth. When I restarted the server my stuff wasn't there where I died. I managed to restore my inventory using /ob_inventory restore, but I have no idea how to get stuff from my Adveture backpack back.

Also is there any way to set up regular backups? I don't want this to happen again to me.

Crash log is here: http://puu.sh/u4GKv/8b76f359e2.txt

**Comment by Dream-Master** [comment]
Normaly the Adventure backpack are placed beside the grave. In the newest version of Adv Backpack the Pack inside the Grave if not spawned beside. I guess you have you own server running ?
Hope you make recently Backups of your wohle server.

**Comment by Lainiel** [comment]
Yeah I have my own server and I don't have any backup tool unfortunatly. Is there any inside the pack? I remember there being AutoSaveWorld when I was playing half a year ago, but it's missing from the pack now. What should I use for backup?

**Comment by Dream-Master** [comment]
Yes auto save world can used for backup. You can run it manually "asw backup"
ask @Namikon about it.

**Comment by Dream-Master** [comment]
@Ugachaga Thanks

**Comment by Lainiel** [comment]
I can't run asw backup because Auto Save World is not in the server pack. I'm not sure if there's even bukkit installed, because the /help command just doesn't work. I really need something that makes regular backups, because my friends and me keep loosing stuff due to server crashing.
