### ISSUE TITLE
Recipe conflict: Oak Painting Frame 1306 (Bibliocraft) and Oak Trim 2340 (Storage Drawers)

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1114]
5 slabs, 4 sticks, same shaped recipe. Same is true for every other wood variant. Painting Frame takes priority, so Trims and therefore the Framing Table from Storage Drawers is uncraftable.

**Comment by Dream-Master** [comment]
Ok have to look into it and fix it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23033587/edd2925c-f478-11e6-8a72-300d4ea8aff5.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23033602/06bb3ae4-f479-11e6-9f3d-fe60f45885e1.png)

**Comment by Dream-Master** [comment]
@Toperoco not sure what you mean ?

**Comment by Toperoco** [comment]
Fixed by updating BiblioCraft.zs to the 1.4.0.0 version

**Comment by Dream-Master** [comment]
@Toperoco Thanks for Info
