### ISSUE TITLE
A bug about the Crafter

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1117]
![ronf si 8n9df 7_ 1f1r](https://cloud.githubusercontent.com/assets/25528572/23010479/981306ca-f456-11e6-8a2d-1e973b8aade7.png)
When I use it to craft the Filled Methane Gas Canister ,I find it doesn't consume the Empty Canister.
Besides,the Liquid Methane on the Titan is difficulit to convert to the Methane Gas.

**Comment by Dream-Master** [comment]
In which machine you craft it?

**Comment by nanmumc** [comment]
Ender IO 's crafter

**Comment by Dream-Master** [comment]
Did it work with normal crafting table?

**Comment by nanmumc** [comment]
Oh,In normal crafting table ,it dosen't consume the Canister too.
With Fluid Canner,the Empty Canister can only be filled with Methane Gas. Crafting it with bucket is the only way to transform the Liquid Methane to Methane Gas.

**Comment by Dream-Master** [comment]
Maybe need to add an GT recipe for it.

**Comment by nanmumc** [comment]
Yeah ,and delete or fix the recipe as shown above to avoid duplicating the Empty Canister.

**Comment by Dream-Master** [comment]
ok i remove the shaped recipe. You can now only fill it in a fluid canner.
