### ISSUE TITLE
cache directory (1.3.0.5)

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1118]
For some reason there is a "cache" directory inside .technic/modpacks/mcnewhorizons/ with copy of all mods that are in "mods" directory. When deleting this directory and trying to reinstall - Technic Launcher redownloads this directory. It basically doubles the size of all installed mods, and doubles internet traffic for Technic website when downloading NewHorizons. This is not an issue for me, but just letting you know if you missed it.

**Comment by bigbass1997** [comment]
That is not something we can control. That is just what the Technic Launcher does.

**Comment by EvgenijM86** [comment]
I see, I will close this then.
