### ISSUE TITLE
[Suggestion] Cornmeal recipe in Sagmill/Macerator

### ISSUE THREAD

**Issue by Hastling** [GTNewHorizons/NewHorizons#1120]
A recipe to turn Corn into Cornmeal in a Macerator/Pulverizer/Sagmill would be nice so I don't have to keep crafting mortars.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23101419/5b4452f0-f693-11e6-9900-babc7e4a3f5a.png)
This recipe was there allready.

**Comment by Hastling** [comment]
![Corn Test](https://cloud.githubusercontent.com/assets/20450890/23110110/4641e3a8-f6e4-11e6-9172-501e0e2fdfbd.gif)

**Comment by Dream-Master** [comment]
Are the recipe shown in nei?

**Comment by Dream-Master** [comment]
fixed and tested

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/274679988039581697/283329823168790548/unknown.png
