### ISSUE TITLE
Recent Server Issues

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1121]
I'm not sure if you are aware of this yet but the past few reboots of the EU server have resulted in everyone timing out for several hours after reboot.

TPS freezes causing people to get kicked or something.

This might be something to look into when you get some time as its happened at least 3-4 server reboots in a row now.

Thanks!

**Comment by bigbass1997** [comment]
Would first like to note that posting this here is no faster than just messaging Namikon directly on Discord.

Drobac and I have already started looking for anything out of the ordinary in server logs and MODR records. But fact is we need to wait for Namikon to investigate the issue and hopefully devise a fix for it.
