### ISSUE TITLE
Thaumic Bases Smoking Pipe crashes nearby players

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#1124]
A player near me used a smoking pipe, and that crashed me

[crash-2017-02-20_17.24.41-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/788033/crash-2017-02-20_17.24.41-client.txt)

java.lang.NullPointerException: Ticking entity
	at tb.common.item.ItemSmokingPipe.func_77654_b(ItemSmokingPipe.java:64)

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/ThaumicBases/issues/3

**Comment by KryptonCaptain** [comment]
Do you have any additional information, such as the type of pipe being used, and the tobacco?

**Comment by KryptonCaptain** [comment]
Do you have any additional information, such as the type of pipe being used, and the tobacco?

**Comment by Dream-Master** [comment]
@ghoulsblade please give us more information about the issue.

**Comment by ghoulsblade** [comment]
i play on stonelegion server with a buddy in the same base, he was right next to me ingame when he wanted to show me the tabacco pipe from thaumic bases, but it crashed me and i had to restart the client.
i'll ask him what pipe and tobacco it was, i think greatwood + relaxing but i'm not 100% sure

**Comment by ghoulsblade** [comment]
interestingly he did not crash at the time

**Comment by KryptonCaptain** [comment]
Fixed in 1.4.1-8 release. I just grabbed the change from the 1.8 version

**Comment by Dream-Master** [comment]
Ok thanks will test it later.

**Comment by ghoulsblade** [comment]
"i was using greatwood pipe with relaxing tobacco"
