### ISSUE TITLE
1st quest of MV tier consumes the MV Machine Hull

### ISSUE THREAD

**Issue by phytopius** [GTNewHorizons/NewHorizons#1125]
https://cdn.discordapp.com/attachments/181078474394566657/283278254713077761/unknown.png
https://cdn.discordapp.com/attachments/181078474394566657/283278336107610124/unknown.png

**Comment by Dream-Master** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/2970688/23141431/11c0bb12-f7b7-11e6-8116-2f7763156815.png)
