### ISSUE TITLE
Lightning warp effect

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1126]
I think this effect is a bit stupid. Today i got some warp in eldrich dungeon, contract this warp and THOUSANDS of lightning strikes me an about 2 hours. Ligtning strikes an about each tick, just look at my armor durability in screens. Lower the ligtning rate and continuos, please. 
http://imgur.com/a/b0kzp

**Comment by Cinobi** [comment]
https://youtu.be/A9lL6yeTW_o here is the video - this idiosy continue an about an 2 hours.

**Comment by VermillionX** [comment]
Yeah, I got that as well. As long as you're inside, you should be fine though.

**Comment by Cinobi** [comment]
Verm, maybe u check the video before making a comment? :D

**Comment by Dream-Master** [comment]
@Cinobi 
 "The attack of an eldritch guardian, or of some "Warped" champions, can also give warp, mostly temporary."
The Effect Warping on your Armor which gives the player temporary warp maybe.
Thaumcraft is closed source so nothiung i can do. Why you not using the bath salt/pool to washing the warp for 20 mins away?

**Comment by Cinobi** [comment]
Dream, u write this seriosly?) I know how the warp works. Bag is - when i ONE TIME get this effect it produse idiocy like in video.

**Comment by Dream-Master** [comment]
Nothing I can do here (with my basic coding knowledge). Idk if this is Thaumcraft Code or a other mod interferes here. If you have a solution you are welcome to fix it.

**Comment by Dream-Master** [comment]
@Technus , @Namikon , @bigbass1997 any idea?

**Comment by Cinobi** [comment]
How do i fix it, maybe it can help. When i go out of town some witherbosses spawns(have 0 warp an about hour) and ligtning fury has finished. Look like there are some "quary" of effects exists, and when warp effect started but can't applied(like denying mob-spawn) previos effect stays active. As solution - remove all quarry effects by force when warp-status reach 0(if it is possible, ofc)

**Comment by Dream-Master** [comment]
So you using a litmus paper and it shows 0 warp? No normal, permanent or temporary warp?

**Comment by Cinobi** [comment]
ye

**Comment by Toperoco** [comment]
Removing all effects by force when warp is 0 defeats the idea of the anti-warp items in Warp Theory. They clearly state that the channeled energy has to go somewhere, so they reduce warp by forcing out bad effects. The Pure Tear for example instantly reduces all warp to 0 and then releases that warp as negative effects over time. Tons of warp = tons of stacked and chained warp effects. Like having 10x lightning effect, which only goes away after hitting you a certain amount of times or even killing you.
I think this is nothing but expected if you drive your warp number into the hundreds. The idea is to manage it with the various tools available before it reaches that point

**Comment by Dream-Master** [comment]
@Namikon 
any idea about this here?

**Comment by Namikon** [comment]
Nope, sorry. Pretty strange thing and definitely not intended by us.
Even with the pure tear it shouldn't go that much on rampage
