### ISSUE TITLE
Infernal mobs lag

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1127]
When i fight some of infernal mobs i noticed - somethins server reaction stops for an 1-2 seconds, all mobs frozen. somethimes i get kicked during this period. when frozen is finished, all world accelerates for some time. Today i see some interesting glitch in frozen time - look at the screen.
http://imgur.com/a/F4J4K
According to this screen i think lag happens when server try to disarm u.

**Comment by Dream-Master** [comment]
You mean the item is in your hand and on the floor the same time?

**Comment by Cinobi** [comment]
Ye. And after lag is ended, item is dropped.

**Comment by Dream-Master** [comment]
So you said that lag disarms you or did a mob have a disarm effect. I disabled all disarm effects so far ik.

**Comment by Cinobi** [comment]
I sad i _think_ "trying to disarm" couse this lag. Maybe it something else :)
About disarming, mobs disarm players often in about a week ago. After something they stop, but lags starts. Some config dismatch between server and client maybe? Ask drobac about mob-disarming, he may know more.

**Comment by Dream-Master** [comment]
Infernal mobs config was messed up. I fix it.
