### ISSUE TITLE
Ore generation is not matched with the achievement

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1129]
![default](https://cloud.githubusercontent.com/assets/25528572/23166255/e40ec866-f87a-11e6-87a2-88b62b2913ab.png)
I see the code about the ore generation and I find that the Niobium Ore doesn't generate in the Titan.But the achievement is.
![default](https://cloud.githubusercontent.com/assets/25528572/23166443/9a591e8c-f87b-11e6-8d24-3bab47e3424c.png)

       24 {
                    S:BiomeName_None=None
                    I:Density_0=3
                    B:EndAsteroid_false=false
                    B:GalacticraftCore_Moon_false=false
                    B:GalacticraftMars_Asteroids_false=false
                    B:GalacticraftMars_Mars_false=false
                    B:GalaxySpace_BarnardC_false=false
                    B:GalaxySpace_BarnardE_false=false
                    B:GalaxySpace_BarnardF_false=true
                    B:GalaxySpace_Callisto_false=false
                    B:GalaxySpace_CentauriA_false=false
                    B:GalaxySpace_Ceres_false=false
                    B:GalaxySpace_Deimos_false=false
                    B:GalaxySpace_Enceladus_false=false
                    B:GalaxySpace_Europa_false=false
                    B:GalaxySpace_Ganymede_false=false
                    B:GalaxySpace_Haumea_false=false
                    B:GalaxySpace_Io_false=false
                    B:GalaxySpace_Kuiperbelt_false=false
                    B:GalaxySpace_MakeMake_false=true
                    B:GalaxySpace_Mercury_false=false
                    B:GalaxySpace_Miranda_false=false
                    B:GalaxySpace_Oberon_false=false
                    B:GalaxySpace_Phobos_false=false
                    B:GalaxySpace_Pluto_false=false
                    B:GalaxySpace_Proteus_false=false
                    B:GalaxySpace_TcetiE_false=false
                    B:GalaxySpace_Titan_false=false
                    B:GalaxySpace_Triton_false=true
                    B:GalaxySpace_VegaB_false=true
                    B:GalaxySpace_Venus_false=false
                    I:MaxHeight_0=30
                    I:MinHeight_0=5
                    B:Nether_false=false
                    I:OrePrimaryLayer_-1=47
                    I:OreSecondaryLayer_-1=45
                    I:OreSporadiclyInbetween_-1=37
                    I:OreSporaticlyAround_-1=37
                    B:Overworld_false=false
                    I:RandomWeight_0=60
                    I:Size_0=24
                    B:TheEnd_false=false
                    B:Vanilla_EndAsteroids_false=false
}

I don't know whether it is a bug.But it has indeed bring much trouble to me to build fusion reactor.

（I guess that you mistake Titan for Triton)

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
The sheet and the config are right only the localozer Text is wrong.

**Comment by nanmumc** [comment]
OK, thanks

**Comment by Dream-Master** [comment]
Not sure why it is wrong linked.

https://github.com/GTNewHorizons/GT5-Unofficial/commit/f844ed61ecc920d078f4cb832a4dfa93cbe83be9
