### ISSUE TITLE
Stamp recipe removed but mail items still craftable

### ISSUE THREAD

**Issue by ZachNo** [GTNewHorizons/NewHorizons#1130]
All of the "Forestry for Minecraft" mail related items have new crafting recipes except for stamps.
Currently stamps are uncraftable and make all of the other mail related items unusable.

**Comment by VermillionX** [comment]
On the EU server, stamps are acquired with /kits that refresh every 24h. This will not be the case for other servers.

**Comment by Dream-Master** [comment]
Ok will add old recipes back for others.
