### ISSUE TITLE
Infinity catalyst

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1131]
Look like this small ore not present at Vega B. My enderquarry mine a 10mln blocks total, and don't find any.

**Comment by Dream-Master** [comment]
Will look at it.

**Comment by Dream-Master** [comment]
Yes i fix it now.

**Comment by Cinobi** [comment]
aww, dream, when it will be? this thing almost stop my progression :c

**Comment by Dream-Master** [comment]
Next release need to reset the Dimmensions. Go to Venus and setup a Quarrie in the mean time.

**Comment by Cinobi** [comment]
sorry, i don't get it - why u suggest venus for me?

**Comment by Dream-Master** [comment]
-                    B:GalaxySpace_VegaB_false=false
+                    B:GalaxySpace_VegaB_false=true
-                    B:GalaxySpace_Venus_false=true
+                    B:GalaxySpace_Venus_false=false

:)
