### ISSUE TITLE
Realgar tools

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1132]
has zero stats
http://imgur.com/a/poECj

**Comment by Dream-Master** [comment]
because it has no durability. Will add some but this material is very unstable and weak.

**Comment by VermillionX** [comment]
There are quite a few tool materials that could do with proper/better stats. Especially some of those exceptionally rare metals.

**Comment by Dream-Master** [comment]
Sure suggest values.

**Comment by VermillionX** [comment]
There's a variety of steel-alloy metals that have stats that are worse than regular steel. Usually in mining level. Meteoric steel for example, it pretty much unusable with its iron mining level.
**Meteoric Steel**: Just needs its mining level increased from Iron to Obsidian.
**HSLA Steel**: 775 durability, 4x handle modifier, 3 attack.
**Fiery Steel**: 410 durability, 2.5x handle modifier, 2 attack. (Pity you can't give it auto-smelt/Fire aspect trait)
**Dark Steel**: 1561 durability, 2.5x handle modifier, 5 attack. (Almost identical to its EnderIO tool stats)
**Voidmetal**: 2050 durability, 2.5x handle modifier, 4 attack.
**Stainless Steel**: 987 durability, 2x handle modifier, 2.5 attack, 12 mining speed, obsidian mining level.
**Shadowsteel**: 3 attack, redstone mining level.
**Black Steel**: 2.5 attack, 14 mining speed, redstone mining level.
**Blue Steel**: 4 attack, 1.2 weight.
**Red Steel**: 5 attack, 2.1 weight.
**Damascus Steel**: 2.5 attack. (This is literally the stuff you make blades from)
**Vanadiumsteel**: 18 mining speed, 7 attack.
**Reinforced Metal**: 450 durability, 6x handle modifier, 2 attack, obsidian mining level.
**Aluminium**: 350 durability, 2x handle modifier, 23 draw speed, 4.0 arrow speed. (an above average bow material.)
**Magnalium**: 19 draw speed, 3.3 arrow speed, 0.12 weight.
**Carbon**: 48 durability, 1.5 mining speed, 20 draw speed, 4.5 arrow speed, 0.08 weight. (Excellent bow material. Terrible durability.)
**Duralumin**: 24 draw speed, 4.8 arrow speed.
**Polyethylene**: 128 durability, 15 draw speed, 2.8 arrow speed.

**Comment by Dream-Master** [comment]
@VermillionX Thanks for you suggested values.
I have to look how to implemnt it. I can change the durability in GT code and the mining Level. I guess with Tinkers Gregworks i can change the rest but i am not sure if this will work. Will try it.

**Comment by Dream-Master** [comment]
not agree with Aluminium 350 duarbility.

**Comment by Dream-Master** [comment]
I guess your draw speed values and arrow speed values makes the bows a tone slower. Are you sure about it?

**Comment by VermillionX** [comment]
The lower the draw speed the faster it's drawn. Higher arrow speed increases range and damage. Attack value has no effect on bows.
Weight on materials affects its flight distance as an arrow/bolt/throwing knife/shuriken. Lower weight = further distance. Tungstensteel for example has like... 150 weight. It travels about 6 blocks as a bolt tip. If you make a bolt with a tungstensteel rod AND tip, it travels 1-2 blocks... or you end up shooting yourself in the foot... and you'll probably die, since tungstensteel has one of the highest attack values possible (14 attack, iirc).
