### ISSUE TITLE
Bottomless pouch

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1133]
It need some mysterios "jar of essentia", and can't be crafted with a jar filled with random essenctia. 

https://imgur.com/a/G7SRl

**Comment by Dream-Master** [comment]
Ok need a recipe change it need an void jar.

**Comment by Ugachaga** [comment]
JFYI, Bottomless Pouch allow smuggling between Overworld and Witchery dimension.

**Comment by Dream-Master** [comment]
Is there a way blacklist it on this dim ?
