### ISSUE TITLE
Assembling machine bug

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1134]
This bug has happened to all three of my assembling machines. It lets me craft 1 thing (cable/coil/etc) and then once it goes to the second it permanantly out of power. If i use a battery, still goes 90% then reset. If i connect a wire/batt buff to it does the same.

**Comment by Dream-Master** [comment]
@kokochicken Make a video for me. I am 100% sure this is not a bug you are using the machine wrong.

**Comment by Technus** [comment]
Need more info, ss with chunk alignment etc.

**Comment by Dream-Master** [comment]
@kokochicken We need more info.

**Comment by Dream-Master** [comment]
@kokochicken i close this if we not get more infos.
