### ISSUE TITLE
Recipe Request

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1135]
I would absolutely love to see Ironwood Rollingpin!

To me it makes sense because its very much like the Mallet in materials.

Wood just sucks so Ironwood would be great.

**Comment by Dream-Master** [comment]
Will see what i can add.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/ccd13bff363ebe86fb65ad83a197f108ba2e0faa

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23273033/cf8ae288-f9fd-11e6-8f6a-7618cb307ed1.png)
