### ISSUE TITLE
New Molten Polyethylene recipe idea

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1137]
As of right now you can only make Molten Polyethylene in two ways
Tiny pile of titanium dust + 16 oxygen cells + naphtha (liquid, 1296mb) = 1296mb molten polyethylene or
Compressed air cell + naphtha (liquid, 144mb) = 72 mb molten polyethylene

I'd like to see an recipe similar to the one that uses compressed air cell, but with naphtha cell instead of liquid form;

_by dividing 1000mb(cell) and base it of that recipe (144mb) (1000/144=6.94=~7)_
Here is my sugesstion for the new recipe
7 Compressed air cells + 1 cell liquid naphtha = 500mb molten polyethylene

by adding this recipe it would make it easier to automate the process of making these liquids using partly the same system, since this way these 3 molten liquids would use the same logic.
Molten Epoxid
Molten Polytetrafluoroethylene

**Comment by Dream-Master** [comment]
@Bryfer 
You mean add this recipe to the cheical ractor ?

**Comment by Dream-Master** [comment]
Need GT 5.09.27.34  for it.
