### ISSUE TITLE
Neutronium plasma

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1139]
Look like this plasma too good for current dynamo hatches - it can't be used with even small dra\neu\Adra turbunes. Add better hatch, please :)
http://imgur.com/a/Fpg83
Screen made with small neu turbine.

Before u ask - yes, we can use worser turbines, but... don't think it's resonable.

**Comment by Dream-Master** [comment]
@Technus

**Comment by Technus** [comment]
To be implemented.

**Comment by Technus** [comment]
Neutronium plasma will get disabled with the release of EM mod. I am implementing there multi ampere I/O for multiblocks and other features.

**Comment by Technus** [comment]
Plasma turbines fixed, neutronium plasma and other are way more better calculated now.
