### ISSUE TITLE
U-235 Piles voiding in to U-238 piles.

### ISSUE THREAD

**Issue by Skarvor** [GTNewHorizons/NewHorizons#1140]
I put a Drawer with 4 stacks of tiny piles of u-235 on top of a hopper full of 5 stacks of u-238 dust aimed at a compressor and the tiny piles will be accepted in to the hopper despite it being full and it will void all but one stack of the tiny piles.

**Comment by Dream-Master** [comment]
So you mean the U235 piles are converted to U238 or voided?

**Comment by Skarvor** [comment]
The u235 will be voided completely, except for one stack which the drawer will keep in it for some reason.

**Comment by Dream-Master** [comment]
we had this problems before that some materials be wrongly ordicted. Cna make Copper to aneleadcopper etc.

**Comment by Skarvor** [comment]
ah, I understand. apologies if this was a known issue then already

**Comment by Dream-Master** [comment]
not sure how prevent this. So i let the issue open until we have a solution for it.

**Comment by Dream-Master** [comment]
@Skarvor I post your Issue on Storage Drawers side.

**Comment by Dream-Master** [comment]
Still no commet on this.

**Comment by Dream-Master** [comment]
lost i guess
