### ISSUE TITLE
IntupHatch FillContainers

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1141]
Unlike the Blood-Asp version InputHatch [does not allow to fill containers](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Input.java#L64-L65). So we still can use InputHatches outside multiblocks for unpack fluid from cell (w/o energy costs), but can't pack fluid to cell. 

Is there any reason to disallow FillContainers? It was very usefull for compact setups.

**Comment by Dream-Master** [comment]
@Technus

**Comment by Technus** [comment]
Disabled ;], too cheeky.

**Comment by Technus** [comment]
also output hatches does not allow empting

**Comment by Ugachaga** [comment]
Are you aware that Output Hatches cannot be used outside multiblocks? There is no way to pump fluid into Output Hatch.

**Comment by Dream-Master** [comment]
@Technus
