### ISSUE TITLE
Basic Diesel Generator (LV) not functioning with Nitro Diesel

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1142]
So I had decided to go with a more complicated route of making nitro diesel to power my LV age stuff. However, after making several machines and then testing the setup in creative, it seems like basic generators do not work with nitro.

They make 514 eu, use up 1liter of nitro and stop working all together. They will not output the 514 eu or make any more eu. 

Normal diesel seems to work.

**Comment by Dream-Master** [comment]
I add a Tool tip that it not work so i dont see an issue here. Use a lower fuel and nitro at mv.

**Comment by killslash** [comment]
Where is the tool tip?

**Comment by Dream-Master** [comment]
wait i make a screen shot for you

**Comment by Dream-Master** [comment]
if it isnt in the last update it will be in the next one.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23332956/246b6530-fb83-11e6-81c7-1363e6e64b1c.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23332961/41ad1878-fb83-11e6-834a-b38a9ef14935.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23332995/ca5e1a14-fb83-11e6-8481-d908575a3240.png)
