### ISSUE TITLE
Ethernal singularity(infinity chest)

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1143]
I think the recipy of this item a little overpriced. It need ~30k of blocks of 47 varios metals, but the cost of metals don't check atall. What i mean - 30k of iron(for example) not so hard to get, but 30k of draconium ingots or 30r of unstable ingots - it's almost impossible. Maybe some boring top-player will make this chest, but not for use - only to have this in his collection.

I think the number of ingots needed must be back proportional to the block cost. like 30k iron - 25k copper\tin - 20k gold, - 15k platinum and so on.

**Comment by Dream-Master** [comment]
@Cinobi Ok please suggest the exact values of materials you would put into it. I can change the recipes.

**Comment by Cinobi** [comment]
well, something like this i think: http://imgur.com/a/mAciM
[Ores.xlsx](https://github.com/GTNewHorizons/NewHorizons/files/801833/Ores.xlsx)

**Comment by Dream-Master** [comment]
Ok will go over it. Thanks for the List.
@Drobac what you think?

**Comment by Drobac** [comment]
Agree with Cinobi's values, the default ones atm are waaaaay too high. Hard even with bees

**Comment by Dream-Master** [comment]
Why i every time to be forced to go the hardest way. Sadly Avaritia not supports removing Compressor recipe. Only @SpitefulFox maybe know why.
So i can try a few ways to remove recipe.
1. Try Shaped recipe remove.
2. Try to remove recipe by output in the core mod via GT Code
3. Fork another Mod and add it manually but not sure if it works for the addonds too.(hopfully last source is available)
4. Go crying and close this issue.

**Comment by Dream-Master** [comment]
Ok choosing way 3.

**Comment by Dream-Master** [comment]
@Cinobi 
If you have more ideas for singularities or values just send it to me.
Thanks

**Comment by Dream-Master** [comment]
Avaritia 1.12 and Unversal Singularity 8.1 are needed for the changes.
