### ISSUE TITLE
New Plutonium 244 Ore Mix

### ISSUE THREAD

**Issue by bigbass1997** [GTNewHorizons/NewHorizons#1144]
Need an easier way of getting Plutonium 244 at IV Tier. One specific use is the IV Naquadah Reactor which requires Plutonium 241, which can be processed in low chances through Plutonium 244, or mined in much, much higher tier planets/moons. The IV Naquadah Reactor is also a quest that appears right after the Asteroids Dimension quest.

Only current ways to get the needed Plutonium 241 is either by making and using up hundreds of Uranium Fuel Rods (or possibly thousands depending on your luck), or by centrifuging hundreds of stacks of Phobos Stone Dust.

So I propose a new ore mix be added to some/all of the Tier 3 planets/moons/asteroids that contains Plutonium 244 for sure.

Can be mixed with possibly Uranium and Thorium? Unless someone else has some other suggestions of ores that may fit with Plutonium?

**Comment by kokochicken** [comment]
found it with uraninite/uranium 238 on Ceres, maybe only certain planets have the plutonium in it?

**Comment by bigbass1997** [comment]
I am guessing that is just some old world generation on the EU server. Since Dream and I could not find Plutonium 244 in the ore mixes config file.

**Comment by Dream-Master** [comment]
Yes this Orgen is old blood asp changed it soe time ago and we pulled the code.

**Comment by DietmarKracht** [comment]
One way to get plutonium 241 is the trollplant crop. if you have done crops since lv tier you should already own one.
