### ISSUE TITLE
Some Recipies with a single item that's way out of tier compared to the rest

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#1145]
Hey guys, there's a few items i noticed that seem to have a rather out-of-teir item mixed in with the rest making them often not obtainable until well after the tier that they'd be relevant in has passed.

Super tank II requires Vibrant Alloy Plates, which itself needs Energetic Alloy, which needs Tungstensteel (an at-minimum Moon material) the Rest is Aluminum and Steel (which works for MV)

Super Tank III's LV Field Generator requires Niobium-Titanium Plate, which Niobium is from IO + and Titanium is Moon. The rest is circuits, aluminium and Stainless steel, which is fine for HV.

Super Tank IV's MV Field Generator requires 4 HSS-G Ingots worth of material, and while tungstensteel is about appropriate for the EV level tank the Naquada requirement seems out of line.

For the Field Generators, their labels are rather misleading, as they say 'LV, MV or HV'  but the materials required are -way- beyond what those tiers can make.

Advanced Electric Jetpack requires a High Energy Flow Circuit, which requires an IV Assembling machine to assemble, while the rest of the components for it, and its upgrade (the Advanced NanoChestPlate) are easily made in HV with the titanium plates and 12x platinum wires being the hardest to get materials.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by kokochicken** [comment]
for the super tanks they are meant to be like that i think, if you saw the recipes before they were WAY harder. They are really good tanks even for their current price. Super tanks kinda "start" with HV and go up (super tank 2=ev, 3=iv, 4=luv) etc, and many of these are made to gate that item until a higher tier without making the recipe harder than it should be

**Comment by Dream-Master** [comment]
@Nenluen 
Energetic Iron needs now Black steel not Tungestensteel anymore

![image](https://cloud.githubusercontent.com/assets/2970688/23343720/4a632ba4-fc70-11e6-880b-0e906d652091.png)

**Comment by Dream-Master** [comment]
I Renamed the Field generators.

**Comment by Dream-Master** [comment]
Ok i rework the Field generators completly.

Only need to look into the adv Jetpack.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23344744/d5cc1320-fc81-11e6-844a-9a6b285eb120.png)
 Fixed that allready.
