### ISSUE TITLE
"EBF-Time" Wont Complete

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1146]
Here are the steps i took that produced this problem

1. Made 1 Heat Proof Machine Casing which detected.
2. Made Electric Blast Furnace controller block which detected
3. Made Input, Output bus and Hatch which all detected
4. Made 11 more Heat Proof Machine Casings the same way as the first one (Using Worktable) None of these detect at all.

I've tried re-logging, dropping them and picking them up again.  Detect button does nothing.

I'm not sure if completing Task number 2 and 3 before completing task number 1 is what caused this or not but its suspicious that it detects 1 of them but not the other 10.

**Comment by Dream-Master** [comment]
I change the Quest and it will work in the next update.

https://github.com/GTNewHorizons/NewHorizons/commit/47dbf8d9b9ebf9e5e0c9d1121180833dfa202fac
