### ISSUE TITLE
IV Naquadah reactor quest

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1147]
Hey, the naquadah reactor quest triggered when i have an EV version, not sure if this is intended

**Comment by Dream-Master** [comment]
I think i need to rework the Naquadah reactor Quests a bit. So much is changing.

**Comment by Dream-Master** [comment]
You mean this Quest ?
![image](https://cloud.githubusercontent.com/assets/2970688/23340667/9da7eae2-fc3a-11e6-9f47-93ef299b6ff2.png)

**Comment by kokochicken** [comment]
yes @Dream-Master when i made the EV naquadah reactor it completed the quest. Also have the IV now but it completed after EV. Maybe some quest clues for what to do next (check mark quests for fusion reactor/assembly line etc) hard to tell where i'm at in the progression rn

**Comment by Dream-Master** [comment]
Yea sadly there are no Quests rn. Have to add some.
