### ISSUE TITLE
Quest Bug Multi Block EBF-Time

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1148]
When you make the Heat Proof Machine Casing for this quest it will not count if you use the Basic Assembly machine rather then using the crafting table. Since at this point you have the ability to make them in the assembly machine it should just require you to have them not craft it.

Additionally your making too many blocks in this quest. It requires you make 11 Heat proof, 1 Electric Blast Furnace, 3 Buses, maintenance, muffler, and 4 LV Energy Hatch (excluding the 16 coil blocks) . This is at minimum 2 extra blocks. Also 4 power blocks makes it a bit odd to use since one has to go in the center facing down words to be at all useful.

**Comment by Dream-Master** [comment]
Will look at it.

**Comment by Dream-Master** [comment]
In the New Update you need to do only 2 Energy Hatches.
