### ISSUE TITLE
Bug crafting single Cobalt Brass Dust 

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1149]
The recipe for using for making a single cobalt Brass dust is not working. The one that makes 9 works but if you try to use tiny piles to make a single one you will find it does not work.

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
For me it works well.
![image](https://cloud.githubusercontent.com/assets/2970688/23340561/c4ee811c-fc38-11e6-9d45-6c3aded3d240.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23340563/cd041308-fc38-11e6-9cbd-33bf77918968.png)

**Comment by Pockyninja** [comment]
I did the same process on a tinker crafting table (the type you make by using a saw on a crafting table) It does not work on that.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23343672/cf7b84a4-fc6f-11e6-8a05-66f69cea9b1f.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23343674/d44cf026-fc6f-11e6-8628-599e210a330c.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23343675/dbbb4f92-fc6f-11e6-90c5-4f5958c1b1e9.png)

**Comment by Dream-Master** [comment]
in sp it works well

**Comment by Pockyninja** [comment]
Yeah I retried it this morning and it is working. I don't know how I caused the bug the first time since no elements have changed.

**Comment by Dream-Master** [comment]
idk :)
