### ISSUE TITLE
Feedback Quest system 32 EU

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1150]
I played a earlier version of this mod a while back and I found the questing system was better. Back then when reaching 32 EU all the machines you could want to build were laid out and awaiting creation not hidden behind other machines which you might not want to make first. To sight a example the first machine I wanted to build was a Wiremill since you end up using a ton of wire early on. It wasnt till later when I made my bender (2nd machine I made) when I realized that it was hidden and my creating it earlier meant a choice between having a duplicate of the wiremill or never completing that quest.

Point being I feel the crafting system is better off not requiring you to make a certain machine first unless it is in some way a requirement of making the latter machine.

on a side note is there any quest to make Basic alloy furnace, Canning machine, Polarizer, or Fluid Extractor? I would very much not like to waste materials on duplicates.

**Comment by Dream-Master** [comment]
It is possible to make all Machines change from crafting to retrieval Quests to complete it after you craft the machine allready.

Basic alloy smelter i add yesterday, Canning machine is locked behind the  Battery Quests and Fluid Extractor is the Forestry Tab when you craft your first farm. I know it isnt optimal maybe have to push Quests to other places.

**Comment by Pockyninja** [comment]
How would you make the change from crafting to retrial quest?

Also thanks for the fast answer. Also great job on the mod thus far.

**Comment by Dream-Master** [comment]
i need to change the tasks inside the Quest file. After a recload the Quest is changed.
