### ISSUE TITLE
Several Items Conflict

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1152]
**1.**  The Manyullyn Crystal only can be crafted by the Manyullyn Plate(GT New Horizons),But by the Blast Furnace and Bending Machine ,We can only get the Manyullyn Plate(GregTech).
![default](https://cloud.githubusercontent.com/assets/25528572/23357721/f75541fe-fd19-11e6-93e7-d70e9f32ef72.png)

![default](https://cloud.githubusercontent.com/assets/25528572/23357829/6ce5e086-fd1a-11e6-9523-a13d40e71ed5.png)

![default](https://cloud.githubusercontent.com/assets/25528572/23357841/7be94f96-fd1a-11e6-89fb-5d7440501ca8.png)

**2.**  The similar problem occur when I wanted to get Amber Plate
![default](https://cloud.githubusercontent.com/assets/25528572/23358048/5772b9d0-fd1b-11e6-9951-9346d9bf0d1e.png)

There are no recipe to get the Block of Amber.
![default](https://cloud.githubusercontent.com/assets/25528572/23358089/8ab63bc8-fd1b-11e6-9d11-7b742b2b7618.png)
![default](https://cloud.githubusercontent.com/assets/25528572/23358096/8ec692e4-fd1b-11e6-8af9-64c9e30e7dd0.png)

Through compressing the Amber(thaumcraft), We can only get the Amber Block(thaumcraft).
![default](https://cloud.githubusercontent.com/assets/25528572/23358213/0963abae-fd1c-11e6-96f2-d0dde7d127dd.png)

**3.**  Also ,the Mysterious Crystal Dust(GT New Horizons) can't be obtained by this way:
![default](https://cloud.githubusercontent.com/assets/25528572/23358264/3a3f0ebc-fd1c-11e6-8878-8c81cfd35077.png)

We can only get the Mysterious Crystal Dust(GregTech)
![default](https://cloud.githubusercontent.com/assets/25528572/23358406/c9c8eada-fd1c-11e6-86f3-134590d3a580.png)

**Comment by Dream-Master** [comment]
will look into it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23401201/1d9dcbfa-fda7-11e6-802e-0f559615de35.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23401218/2b6d6c72-fda7-11e6-85c0-62aaa49b6611.png)

**Comment by Dream-Master** [comment]
Add chisel recipe

![image](https://cloud.githubusercontent.com/assets/2970688/23401526/5ba2ecf4-fda8-11e6-82e1-d512146b8f90.png)

**Comment by nanmumc** [comment]
![default](https://cloud.githubusercontent.com/assets/25528572/23401634/5f678030-fde3-11e6-9a60-5c155f29e434.png)
![default](https://cloud.githubusercontent.com/assets/25528572/23401646/665819ea-fde3-11e6-9fd3-b8ed8c4fed77.png)

Well...maybe the chisel will cause another bug..

**Comment by Dream-Master** [comment]
i remove this manually added recipes

**Comment by Dream-Master** [comment]
so you need now 9 amber.
