### ISSUE TITLE
Iron Tank Wall in Mercenary recipe different to what shown in NEI

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#1154]
Iron Tank Wall in Mercenary

**NEI**: 2 Iron Dusts
**Actually**: 2 Small Pile of Iron Dusts

**Comment by Dream-Master** [comment]
Need to check it.

**Comment by Dream-Master** [comment]
Yea that because i nerf the recipe after gt does. Will fix it.
