### ISSUE TITLE
Redstone in Carpenter

### ISSUE THREAD

**Issue by Fohlengiraffe** [GTNewHorizons/NewHorizons#1156]
It isn't possible to get redstone in the Carpenter!

So you can't make several recipes

**Comment by Dream-Master** [comment]
It is possible it must be molten Redstone. You can fill it in in Buckets or cells. Pipes should work too.

**Comment by Fohlengiraffe** [comment]
I didn' t tryed with pipes but in the Fluid Canner isn't a recipe for cells or buckets.

**Comment by Fohlengiraffe** [comment]
But I want to put the fluids in cells or buckets. And for this there isn't a recipe...

**Comment by Bryfer** [comment]
Fluid extractor -> fluid canning machine
Fluid extractor -> carpenter

There isn't a recipe since you need more than one machine to make this. You make molten redstone Inside the extractor and then you output it to where you want it.

**Comment by Dream-Master** [comment]
@Fohlengiraffe are it works for you ? Can i close this issue.

**Comment by Fohlengiraffe** [comment]
I will check today evening. And close this issue than. Or write a comment again
