### ISSUE TITLE
Backpack deletes items when upgrading size

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1157]
The Backpack from Backpack mod (id: 4341)

I recentry upgraded my backpack from backpack (4341) to Middle backpack (4341:100)
When making this upgrade it forgets everything you got stored inside the backpack.
Not sure if relevant but I had an custom name on the backpack "Bryfer's Backpack"

**Comment by Dream-Master** [comment]
Sure because it removes the nbt tag. You don't want to  say me that you honestly craft with a full backpack.

**Comment by Dream-Master** [comment]
Never crafting Backpacks with a full Backpack. I cant add Tooltips to all items :(

**Comment by Bryfer** [comment]
@dream-master
Any chance you want to re-consider adding that tooltip anyway? This problem has happened atleast 10times for differ players since I made this post.
Mostly people try to change color of their backpack thinking it's not supposed to void all items inside it..

**Comment by Dream-Master** [comment]
Not sure if I can add multi line commands. The backpacks have tool tips allready (showing size)
