### ISSUE TITLE
GT Metaitem Corruption with Everfull Urn

### ISSUE THREAD

**Issue by SwardGames** [GTNewHorizons/NewHorizons#1159]
Right clicking with a GT Metaitem on an Everfull Urn from Thaumic Exploration will corrupt it (when right-clicked with a LV Electric Pump it will become a gt.metaitem.01.0.name)

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Technus** [comment]
dont rightclick on it

**Comment by Dream-Master** [comment]
Nothing we can do here i guess.
