### ISSUE TITLE
minor exu stabilizing ritual golem bug involving utility mobs golem variant 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1160]
You can't do the exu ritual to stablize the sigil because spawning a golem the vanilla way gives a mob from utility mobs instead of the vanilla one

not sure how much more info is needed, but /summoning a golem does give you a vanilla one, but it doesn't work for the ritual

**Comment by Toperoco** [comment]
Workaround by setting UMIronGolem to false in the UtilityMobs config

**Comment by Dream-Master** [comment]
I look into it.
