### ISSUE TITLE
Question: Are any mechanics changed for Pam's Harvestcraft Gardens?

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1161]
I see that we are one letter version above that is the newest version from Official source for Pam's harvestcraft. (1.7.10Lb official vs our 1.7.10Lc)

Was anything changed regarding spreading to the gardens? Specifically, is this information taken off Pam's harvestcraft website accurate?

"Gardens can spread up to 3 blocks away from their own (a 7x7 area around the original, as well as one block above/below them), and gardens will not spread if there are 5 or more of the same type of garden in this 7x7 space. This means that when farming gardens, you should keep the same type of garden away from each other so more can grow, but pack together different types because they do not hinder each others growth (so long as the 7x7 has free space for more to spread, of course)."

**Comment by Dream-Master** [comment]
Only a texture file was renamed. That's all I changed.

**Comment by Dream-Master** [comment]
@killslash so i not change anything only the lang file. Must be a Pams thing. Can we close this?
