### ISSUE TITLE
Matter clusters

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1163]
Please, let this clasters hold more items :D 
http://imgur.com/a/2uTlC

**Comment by Dream-Master** [comment]
I touche Avaritia code yesterday maybe i can find it bt i am not sure if i can change it.
Maybe need help from @Technus

**Comment by Cinobi** [comment]
it can be changed via configs, if i remember correctly

**Comment by Dream-Master** [comment]
oh ok so easy. Sure i can change it. Values suggestions please.

**Comment by Dream-Master** [comment]
nope

**Comment by Cinobi** [comment]
can't find this in configs, look like i mistaken. Sorry :c 

About capacity: this pick can mine 2304 blocks in one hit
so it takes 2 hits to fill 4096 matter cluster
that's why i ask to update cluster's capacity :)

**Comment by Dream-Master** [comment]
Ok we can try to double it to 8192 items per cluster.

**Comment by Technus** [comment]
@Cinobi 
-matter ball- can also cause player.dat corruption (too long network packet issue) if we ramp it too high, especially when they will contain too much different item types.

**Comment by Cinobi** [comment]
[New World.zip](https://github.com/GTNewHorizons/NewHorizons/files/816273/New.World.zip)

**Comment by Dream-Master** [comment]
Using Avaritia 1.13 for it.
