### ISSUE TITLE
Game does not go much further than starting codechickencore

### ISSUE THREAD

**Issue by insanityserum** [GTNewHorizons/NewHorizons#1165]
**Edit by bigbass1997:**
  http://pastebin.com/raw/vYyeBKcn
  Please do not paste a massive wall of text into issues. When posting logs, please use pastebin or gist.

**Comment by insanityserum** [comment]
sorry

**Comment by Dream-Master** [comment]
To less info to say anything about it.
What Launcher you are using.
Java version etc.
Try another Launcher FTB or Curse or Technic.

**Comment by insanityserum** [comment]
I'm using curse, on version 1.3.0.5 of the pack, java version 1.8.0_121-b13.

**Comment by insanityserum** [comment]
Sorry about the lack of info

**Comment by insanityserum** [comment]
http://pastebin.com/w5QChYL7
Used FTB launcher. Same results.

**Comment by Dream-Master** [comment]
Specs of you machine ?
How much ram you gave the Launcher?

**Comment by Dream-Master** [comment]
Are you are using a onboard Graphic card?

**Comment by insanityserum** [comment]
I'm using a GTX 1060, Xeon E5, 16gb RAM

**Comment by insanityserum** [comment]
Technic also fails. It is using 12gb currently.

**Comment by insanityserum** [comment]
Changed it to 7gb. Testing it again.

**Comment by Dream-Master** [comment]
ok what happend the game stuck?

**Comment by bigbass1997** [comment]
What version of graphics drivers are you using?

**Comment by insanityserum** [comment]
No, doesn't even open. Seems codechicken core tries to start up and then the thing dies.

**Comment by insanityserum** [comment]
Let me check @bigbass1997

**Comment by insanityserum** [comment]
version 378.49 @bigbass1997

**Comment by bigbass1997** [comment]
That is your problem then. Version 378.49 of the NVIDIA graphics driver has major problems with many games using OpenGL including Minecraft. Install this hotfix https://nvidia.custhelp.com/app/answers/detail/a_id/4378

**Comment by Dream-Master** [comment]
@insanityserum can you close this please?

**Comment by insanityserum** [comment]
Oh sorry, didn't know that problem with my graphics drivers. Sorry mate. Yah I'll close it.

**Comment by Dream-Master** [comment]
Idk too have a AMD Card :)

**Comment by bigbass1997** [comment]
It was a major issue when the driver first came out, client will crash practically immediately without any crash logs or stacktraces. I haven't seen anyone come forward with the issue for at least a week or two, besides this one.

**Comment by insanityserum** [comment]
Yeah I'm sorry, didn't know the driver problem that was there.
