### ISSUE TITLE
Crash crafting fish with Tofu

### ISSUE THREAD

**Issue by worsin** [GTNewHorizons/NewHorizons#1166]
2 Times my game CTD trying to turn a stack of 32 Tofu into Fish.

No error produced in my log.

**Comment by Dream-Master** [comment]
So the game crash you to desktop?
fml log please.
crash log if there.
What recipe make Tofu to fish ?

**Comment by VermillionX** [comment]
Recipe is likely overlapping features of Tofu's oredictionary entry to function in pams' recipes as any kind of meat, including fish; With pams' crafting recipe for oredictionary'd fish to be crafted into vanilla raw fish to be used in other mods' fish recipes.
Thus, Tofu = Fake Fish > Real Fish.

**Comment by Dream-Master** [comment]
Can you post some screenshots please

**Comment by Dream-Master** [comment]
No answer i close this now!
