### ISSUE TITLE
Gravichest dissapearing

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1167]
I make some enderexpansion today. 2! gravichests dissapeared from me when i fight different enderexpansion mobs.
First one was an about 5 hours ago. It has a not more energy left, so i decided it just broken after outofenergy.
Second one was an 5-10 mins ago. It have 50% of energy left.

Please, fix this - i can't craft gravichest each 2-3 hours.

**Comment by Dream-Master** [comment]
@Namikon any idea ?

**Comment by Namikon** [comment]
Disappearing Items? No. Maybe Thief ability of some mobs. Gravichest has no code at all to remove armor.

**Comment by Technus** [comment]
Iirc the sticky thing is disabled, might be some other ability that applies damage to armor

**Comment by Namikon** [comment]
I think the rust-effect does this. If that's true, I don't think I can do anything to prevent it.
The armor already overwrites the "damageArmor" function and instead reduces electric charge. If a mod does direct damage without calling the standard methods, there is nothing I can do.

**Comment by Namikon** [comment]
> Iirc the sticky thing is disabled, might be some other ability that applies damage to armor

Just checked. On delta, *every* effect is enabled for InfernalMobs. So I highly assume that is the problem.
@Dream-Master is this intended?

**Comment by Dream-Master** [comment]
no. Maybe i need to recheck the cfg.

**Comment by Dream-Master** [comment]
change the file now.

**Comment by Dream-Master** [comment]
after next restart.
