### ISSUE TITLE
Legendary quests

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1168]
to unlock draconic evolution u need to get ectoplasm: letendary x, quest 386
to make ectoplasm u need to purify ghost amulet in dragon essense altar
to make dracon essense altar u need dragon essense
to get dragon essense u need to kill a dragon
to kill a dragon u need to ressurect it
to ressurect it u need unlock draconic evolution

Fix this dead end please :)

**Comment by Dream-Master** [comment]
@Drobac is this true or is there an alternative way?

**Comment by VermillionX** [comment]
You can use the temple caller quest from HEE to restart The End dimension, which respawns the dragon, but that basically crashes the server and deletes everything everyone's done in the end.
Other alternatives for respawning the dragon are the DE method, which requires about a stack of awakened draconium (zpm), locked behind the dragon.
The dragon can be respawned using the Phantasmal Bees in the main ender branch, but that requires both a Dragon Egg to be used as the bee's flower and one to be thrown on the ground so the Resurrection effect will spawn the dragon.
There are also the 4 or so Chaos Dragons that spawn iirc at +/- 10000 X & Z in the end. Of course, these dragons are the ultimate boss in the pack and are basically unkillable without full DE Dragon Armor which negates the armor/resistance-bypassing damage the dragon does (which is about 50 hearts of damage). Chances are, these are already dead anyway; and I don't know if they give dragon essence.

**Comment by Dream-Master** [comment]
Sure i can add recipe for everything but i dont want break balance.
@Drobac need your helping hand here.

**Comment by Drobac** [comment]
Best way to fix it would be adding a recipe for purified ghost talisman. Maybe a simple infusion of the normal ghost talisman with some HEE material other than the dragon essences. Could make resummoning the dragon easier, that would help with other things that need a dragon egg too. Will check when i have time today

**Comment by Technus** [comment]
and preferably smelted draconium on top of that

**Comment by Dream-Master** [comment]
you mean some ingot/plate etc @Technus  ?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23578862/790fa9ea-00e0-11e7-83b9-7c392632859e.png)
