### ISSUE TITLE
1.4.0.0 and Future

### ISSUE THREAD

**Issue by Franky9717** [GTNewHorizons/NewHorizons#1169]
when the updating goes out 1.4.0.0? 
when craftare will be possible the machineries above to the tier UV (ultra Voltage)?

**Comment by Dream-Master** [comment]
Above UV Tier will take a bit longer then 1.4.0.0

1.4.0.0 will be out very soon.

**Comment by Franky9717** [comment]
then the machineries above the tier UV will go out far in the future?

**Comment by Dream-Master** [comment]
maybe next release.

**Comment by Franky9717** [comment]
ok👍

**Comment by Franky9717** [comment]
What will be added in the update 1.4.0.0?

**Comment by Dream-Master** [comment]
http://www.gtnewhorizons.com/forum/m/36844562/viewthread/28973236-serverchangelog/post/last#last

**Comment by Franky9717** [comment]
ok

**Comment by Franky9717** [comment]
for the next update missing 1/2 months?

**Comment by Dream-Master** [comment]
@Franky9717 I not aswering the Question about an ETA of Updates.
If you look at the last updates you know how long it normaly takes.

**Comment by Dream-Master** [comment]
1.4.1.0 will be out by the weekend if all issues i wrote down are fixed.
