### ISSUE TITLE
Adjust Thaumcraft wands Vis costs

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#117]

**Comment by Drobac** [comment]
Add Thaumcraft wand upgrades

**Comment by Drobac** [comment]
Iron Capped Wooden Wand - fine as is

Golden Capped Wooden Wand - fine as is
Iron Capped Greatwood Wand - Fine as is
Gold Capped Greatwood Wand - Fine as is

Lower Primal Charm Vis cost to 50 so it can be used to craft Scepters and staffs

Iron Capped Greatwood scepter cannot have more vis cost the 50  (+discounts)
 Thaumium Capped Greatwood Scepter Cannot cost more the 75 (+discounts)

All Greatwood staffs cannot have a vis cost of more then a 100, but i suggest about 75 vis so you can get a staff with a greatwood level scepter

Capped (iron, gold,Obsidian,Icy,Quarts etc.) - FIne as is
Capped Silverwood wands - Fine as is
Silverwood Scepter - iron capped can be 100 vis ( + discount) - Scepter can still be used in crafting
                               - Thaumium capped scepter can be 150 vis
All Silverwood Staffs cannot cost more then a 150 (+discounts) - staffs cannot be used in any kind of crafting, you can only use wand focuses with them.

**Comment by Drobac** [comment]
Add Thaumic Horizons Wand caps - Mechanist's wand cap and Sojourner's Wand caps ( both are better then gold but worse then thaumium)
Add Thaumic Horizons Wand cores - Amber Core(holds 10 vis) - should have the same Vis Costs as greatwood wands, Transmutative wand core (75 vis) - should have same vis costs as the greatwood scepters
Add Thaumic Horizons Staff cores - Same as greatwood staff costs
Add Alchemical Caps - vis cost the same as thaumic capped wands
Add Blood Wand core(100 vis) should cost the same as the thaumium capped Silverwood scepters
Add Blood Staff core (50 vis) same cost as the thaumium capped silverwood scepters
Add Infernal Wand core(150 vis) - should cost the same as thaumium capped silverwood scepter

**Comment by Drobac** [comment]
Add Thaumic Horizons Wand caps - Mechanist's wand cap and Sojourner's Wand caps ( both are better then gold but worse then thaumium)
Add Thaumic Horizons Wand cores - Amber Core(holds 10 vis) - should have the same Vis Costs as greatwood wands, Transmutative wand core (75 vis) - should have same vis costs as the greatwood scepters
Add Thaumic Horizons Staff cores - Same as greatwood staff costs
Add Alchemical Caps - vis cost the same as thaumic capped wands
Add Blood Wand core(100 vis) should cost the same as the thaumium capped Silverwood scepters
Add Blood Staff core (50 vis) same cost as the thaumium capped silverwood scepters
Add Infernal Wand core(150 vis) - should cost the same as thaumium capped silverwood scepter

**Comment by Dream-Master** [comment]
Start working on

**Comment by Dream-Master** [comment]
Done so far only the Void Wand Core have to add.
