### ISSUE TITLE
Thaumcraft research bag

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1170]
Some days ago i research "Armor disguise" from gadomansy. Infusion don't work. When i ask another person with this research to start infusion - it started. 
look like this research only shows as researched, but not researched in real. Please, do something about it :c

**Comment by Dream-Master** [comment]
@Hefire PVP
Did you have any idea on this?

**Comment by HellFirePvP** [comment]
He asked me about that on the server too.. idk would need to double test this, since it _should_ work unless he uses some "weird" armor or something.

Unfortunately i guess i won't be able to directly test it there (yet) since that would require me to have the research :P

**Comment by Dream-Master** [comment]
I remember i dont touch Armor disguise in my scripts because i can set all this recipes so it shoul be vanilla. Only the research i touche. 
@Cinobi Maybe your reserch need to be rest in the Thaumcraft Player data and you research it a second time.

**Comment by Cinobi** [comment]
@Dream-Master don't have any problem - reset it

**Comment by Cinobi** [comment]
well, still not worked. btw, my friend, who get research sharing with me, can't start infusion too.

**Comment by Dream-Master** [comment]
strange then idk too. Try to find some who can do it for you then.
