### ISSUE TITLE
Hardened Clay breaking doesn't give Miner or Digger XP in the Job System.

### ISSUE THREAD

**Issue by Sentrus** [GTNewHorizons/NewHorizons#1171]
It would be nice if these blocks could be added to one or the other. There are some big biomes with mostly hardened clay and getting XP for clearing land here would be fantastic.

**Comment by Dream-Master** [comment]
@Namikon. Can you look into it?

**Comment by Dream-Master** [comment]
Hope that was added. If not reopen it or create a new issue.
