### ISSUE TITLE
Nightvision enchantment broken

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1172]
https://imgur.com/a/5mK2Z

**Comment by Dream-Master** [comment]
@Ugachaga have this anything to do with your changes you did?

**Comment by Ugachaga** [comment]
For now NightVision enchant handled by EnderIO and works similar as Dark Helm uprgade. It means you can turn it on/off using EnderIO NightVision hotkey.

**Comment by Dream-Master** [comment]
Thanks for info. @Ugachaga
