### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1174]
GTNH 1.4.0.1

Quests:
- Gardener, id 483. Reward is IC2 bronze instead of Greg one.
- Better Tank, id 16. Reward is same coins 2 times (20 + 10).
- Trade for life, id 917. Reward is 1 first-tier coin. Isn't it too little?

In Technic intaller two "AE2-Wireless-Crafting.zs". One in /scrips (it's ok) and one in /config (it's not).

There is no way to make Hot Pulsating Iron ingot, but Vacuum Freezer recipe still there.

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
AE2-Wireless-Crafting.zs are removed from cnfig folder allready.

**Comment by Dream-Master** [comment]
So far ik many Materials have hot ingots but never used because ebf temp too low. Pulsating Iron have 1800K so Tier 1 EBF is needed.
