### ISSUE TITLE
Salt crafting

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1175]
With the changeover from GT salt to Pams' salt; Small and tiny piles of salt can no longer be crafted into whole piles of salt, except by using the GT packager.

**Comment by Dream-Master** [comment]
ok so i need to add a recipe for it.

**Comment by Dream-Master** [comment]
Not so easy to fix.

**Comment by Dream-Master** [comment]
Find more inconsistencies about salt.

**Comment by Dream-Master** [comment]
Not working maybe i change it back to gt ones and change the harvestcraft recipe.

**Comment by Dream-Master** [comment]
Fixing it add Gt Salt to FoodSalt
