### ISSUE TITLE
No recipe

### ISSUE THREAD

**Issue by Segoper** [GTNewHorizons/NewHorizons#1176]
Why the stick isn't made of him?

**Comment by Segoper** [comment]
https://images.discordapp.net/.eJwFwUEOhCAMAMC_cJdCobXxMxuCBE1UCHRPZv--M6_5jsts5lDtcwPYz5nb2O3UNlIttrZWr5L6OW1uNyTVlI-7PDoBYwwkwijIK3MIDCiCxIxE3mMgkgjo_Lq4sDj-eLQolpztTzW_P43BI7U.MSPUfm3NgKkizsjZTE6Ez3jgeKo

**Comment by Segoper** [comment]
It is transmutative rod

**Comment by Dream-Master** [comment]
Did you research the Wand core because I redo the recipes.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23634702/fb180698-02cb-11e7-812f-1aa044ad9e26.png)You need Titanium screws and Fiery Blood

**Comment by Dream-Master** [comment]
``// --- Gold Banded Transmutative Wand
mods.thaumcraft.Arcane.addShaped("Rod_TransmutatitionGTNH", <Thaumcraft:WandCasting:18>.withTag({cap: "gold", rod: "TRANSMUTATION"}), "aer 70, terra 70, ignis 70, aqua 70, ordo 70, perditio 70", [
[<TwilightForest:item.fieryBlood>, <ore:screwTitanium>, <dreamcraft:item.GoldWandCap>],
[<ore:screwTitanium>, <ThaumicExploration:transmutationCore>, <ore:screwTitanium>],
[<dreamcraft:item.GoldWandCap>, <ore:screwTitanium>, <TwilightForest:item.fieryBlood>]]);``
