### ISSUE TITLE
Reserch gone but still got the warp,

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1177]
lost wa few reserches in the update, thaumic tinker was updated so i guess that is why but i still have the permanet warp from the reserches, bug or is the permanent warp not conected directly to what you have unlocked?

**Comment by Dream-Master** [comment]
Ok which researches are locked again. Need pics.
You can using Bath Soap and the Bath for cleaning your warp for 20 mins. If you research Thaumic Tinker Kami you can make the Amulet which purge the warp.

**Comment by Ghengis88** [comment]
![image](https://cloud.githubusercontent.com/assets/25811344/23630240/acd1c994-02ba-11e7-95de-e038be8eb445.png)

**Comment by Ghengis88** [comment]
the elemental fires, tome of knowlege sharing and infused seeds was lost, seemt to have the same warp as befor, 56, perm and 46 normal, dont know why the reserch was lost in the uppdate, same with soul brazier and boots of the comet, but "Thaumic Exploration(fully nerfed now)" in the chanelog is why i guess

**Comment by Dream-Master** [comment]
Yes Thaumic Exploration i nerfed so you need to research it. Thaumic Tinker i dont touche.

The Imbues Fire Potion are useless to dangerous for server so we disable fire spred.

Better try to unlock Kami to research the Amulet that cleaning Warp.

**Comment by Dream-Master** [comment]
@Ghengis88 Can i close this?

**Comment by Ghengis88** [comment]
yea sure, thx
