### ISSUE TITLE
Large turbine fix - for machine Stop if not enough fluid.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1179]
Add this to 1.4 debug patch 1.4.0.2

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/570114be0e819600276dc45640aaa0bcd0d16b73

Fix is under this commit, already merged into master.

**Comment by Dream-Master** [comment]
ok
