### ISSUE TITLE
Electrotine Battery quest

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1183]
The only way to get Electrotine is to complete related quest. But for complete this quest you need Electrotine. Should be changed to Nikolite?

**Comment by Dream-Master** [comment]
@Ugachaga I ordicted Electrotine be Nikolite allready. Can you send me a pic which explained it a bit. Thanks

**Comment by Ugachaga** [comment]
It seems BQ doesn't care about oredict. 
I mean quest requirements and rewards should be changed to material which you able to get (Nikolite).

**Comment by Ugachaga** [comment]
Jetpack quests seems affected too

**Comment by Dream-Master** [comment]
BQ not ignore Oredict but i have to set it. Will change it to ore nicolite

**Comment by Dream-Master** [comment]
I change it back to Electrotine because Nikolite cant be used as fuel.

**Comment by Dream-Master** [comment]
Ok Nikolite Ore/Dust etc are now Electrotine to be compatible with PR.
