### ISSUE TITLE
[Suggestion] Just Enough Calculation

### ISSUE THREAD

**Issue by DFliyerz** [GTNewHorizons/NewHorizons#1185]
I would like to suggest adding this mod, [Just Enough Calculation](https://minecraft.curseforge.com/projects/just-enough-calculation). While it doesn't work quite as well with NEI as it does with JEI, it's still invaluable for calculating the material costs of things if you enter the recipes manually.

**Comment by Dream-Master** [comment]
Does it support Minetweaker scripts changed recipes?

**Comment by DFliyerz** [comment]
The only recipe type that it accepts entering automatically is regular crafting recipes, but you can enter any other recipe manually. Since automatically entering recipes is handled through NEI, it does handle Minetweaker recipes.

**Comment by Dream-Master** [comment]
@Drobac , @Namikon , @Technus , @bigbass1997  what you think about this mod?

**Comment by Namikon** [comment]
While the idea is great, it is another potential fork for us. The last update for 1.7.10 was in May 2016, where the 1.10 branch had its last update 1 day ago.
A general +1 from me, but **only** if it works as a "drop in" mod. We really don't need another forked mod to maintain

**Comment by Dream-Master** [comment]
@DFliyerz How does it work. I try a bit around look a video but i dont have a clou how it works in 1.7.10.

**Comment by Dream-Master** [comment]
If no one explain me the Mod i will close the issue here.
@DFliyerz

**Comment by Dream-Master** [comment]
Ok i close this now. @DFliyerz if you want this mod in the pack just contact me and explain it to me thanks.

**Comment by PolkageistHS** [comment]
I just started using it and it's sweet.  Setting it up is manual but it supports the [?] block from NEI to add the recipes to it.
![image](https://user-images.githubusercontent.com/9247381/142965955-c9098da6-924c-4493-959c-80faa74dc4cc.png)
![image](https://user-images.githubusercontent.com/9247381/142965961-6fc8f394-0de7-4b1f-8144-3d2186123212.png)
 
It'll show both the raw materials needed and the progression path to make the final item.  It's clientside-only so no blocks or items get added.
