### ISSUE TITLE
Galena, Lead ore?

### ISSUE THREAD

**Issue by HazeTheBeater** [GTNewHorizons/NewHorizons#1186]
Ive been prospecting for a day now in the twilight forest, Yet no galena vein..  I dont know if it is server side but.. Can i get some tips or help please? I know it is 4-45 on twilight, can it be found on overworld? What can i do? My way of finding veins is either finding ravines or Digging a hole straight down with a hammer
This technique works 50% of the time to find a vein on the overworld, but it dosent on twilight.

**Comment by Dream-Master** [comment]
Will look with coffee clear blocks command tomorrow in a special world to find lead/galena

**Comment by VermillionX** [comment]
I found half a dozen lead/galena veins last night on the server. If you're on the official server, I can give you the coords.

**Comment by HazeTheBeater** [comment]
Im on prospercraft server US. I just went to prospect dozens of times but no result, we just got a reset a maybe the twilight is set up badly? Only you can find veins in ravines or world gen structures.

**Comment by HazeTheBeater** [comment]
Excuse my bad english i aint no native english speaker.

**Comment by HazeTheBeater** [comment]
It might be very common for you guys, therefore it might look like im exaggerating but yeah, im not.. I only could find diamond veins very common, 3-2 of those, 2 pyrope veins and  huge-huge-huge limonite vein, And some nickel-talc vein mixed up together.

**Comment by VermillionX** [comment]
The oregen should be the same for both servers.
Everything else you found seems to be right.

**Comment by Dream-Master** [comment]
So can this be closed?

**Comment by Dream-Master** [comment]
Ok i close this now.
