### ISSUE TITLE
Ultimate voltage turbo charger

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1188]
This item can't be crafted, becouse ultimate power transformer don't have a recipy.

**Comment by Cinobi** [comment]
Unstable ingot block don't have a recipy, too

**Comment by Dream-Master** [comment]
Since when it not have a recipe.
@Technus about the recipe should we add it?

**Comment by Cinobi** [comment]
dunno, i notised it just today. Singularity can't be crafted atall for now :D 

--and please, don't move this fix to the next update :c

**Comment by Dream-Master** [comment]
@Cinobi Why singularities cant be crafted ?

**Comment by Cinobi** [comment]
couse unstable ingot block can't be crafted :D

**Comment by DietmarKracht** [comment]
I can confirm  that. Looking into  the  script file unstable  ingot  block reciepe  is removed but never  added back

**Comment by Dream-Master** [comment]
Funny. need to check later.
