### ISSUE TITLE
Gem mismatching recipes

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1189]
Two issues involving gems and gem recipes here.

The first: The Desh Galacticraft tools use Exquisite Ruby in their recipe. However, this is actually a Fools Ruby, not a true ruby. Fools rubies are extremely hard to get, as only a small amount of Small Ruby Ores in Twilight Forest actually give Fools Ruby. Fools Ruby is basically a booby-prize for people wanting actual rubies, and doesn't actually have a use normally.

The second: Amethyst dust is the only gem dust that cannot be Implosion Compressed into a Gem. Even Fools Ruby Dust can be compressed into a new gem. This makes getting a Disenchantment Table exceedingly difficult as the only way to get the Amethyst used in the recipe (18 required) is from an irritatingly rare Small Ore in Twilight Forest or a T4 planet, long after a disenchanting table is useful.

**Comment by Dream-Master** [comment]
OK will look into it

**Comment by DietmarKracht** [comment]
The  disenchanting table is useful  in every tier

**Comment by Dream-Master** [comment]
@DietmarKracht 
``The disenchanting table is useful in every tier``
What you mean with that?

**Comment by Dream-Master** [comment]
Disenchanted Table was disabled because you can cheat stuff with it.

False Ruby recipes changed to Normal ruby ones.
Amethyst can be now made in a Implosion Compressor.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23808114/d8e7b758-05c8-11e7-9126-c4bc3c3968c5.png)
