### ISSUE TITLE
Legendary tier X(again)

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1192]
Quest for thauminite can't be completed.

https://imgur.com/a/LWU0o

(Remove this crafting quests already, please)

**Comment by Dream-Master** [comment]
@cinobi
using better words next time. This is not a children's place here.

**Comment by Cinobi** [comment]
Sorry about it, was so tired at this evening~

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23806926/e6a34970-05c3-11e7-9b45-e99786e7398c.png)

fixed
