### ISSUE TITLE
Titanium Screw Quest

### ISSUE THREAD

**Issue by DFliyerz** [GTNewHorizons/NewHorizons#1193]
The titanium screw quest in the Adept Thaumaturgy line is a crafting task, although by the point you have titanium screws you are almost undoubtedly using a lathe to craft them.

**Comment by Dream-Master** [comment]
Will change it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23806706/fef222ae-05c2-11e7-923d-4d2815a78989.png)

This isnt a crafting quest. Are you playing in sp or on a Server?
try to hit the command /bq_admin default load

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1099

**Comment by DFliyerz** [comment]
SP, I'll try that.

**Comment by Dream-Master** [comment]
Ok say me if this is fixed and close the issue then.
Thanks

**Comment by DFliyerz** [comment]
Yep, fixed it.
