### ISSUE TITLE
Quests and TiC parts

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1194]
Several quests that require tool parts and casts from Tinker's Construct are non-functional.
Thus far, both the tier 0.5 "Gardener" and the "Iron Shields" quests will not accept any of the casts or the bronze tool parts.
Similarly, the MV-tier "Diamond Shield" quest won't accept any of the specified parts.

**Comment by Dream-Master** [comment]
Will be fixed in the next release hopefully.

**Comment by Dream-Master** [comment]
Can you send me a pic that I can see in which part it change?

**Comment by Dream-Master** [comment]
This are pics from sp:

![image](https://cloud.githubusercontent.com/assets/2970688/23806555/6d421468-05c2-11e7-86e0-2a2491caa8e5.png)
![image](https://cloud.githubusercontent.com/assets/2970688/23806618/a0b69012-05c2-11e7-9f7e-8df31d1b0949.png)

![image](https://cloud.githubusercontent.com/assets/2970688/23806620/a6ba64b6-05c2-11e7-8cc8-83c68047b237.png)

With newest version Tinkers gregworks 1.0.16 which are in the next update

**Comment by VermillionX** [comment]
![2017-03-11_14 49 50](https://cloud.githubusercontent.com/assets/10645298/23819355/0bfcf378-066a-11e7-99a0-4002c6e385f6.png)
![2017-03-11_14 46 43](https://cloud.githubusercontent.com/assets/10645298/23819341/d78018aa-0669-11e7-831f-0352a17f4306.png)
![2017-03-11_14 50 46](https://cloud.githubusercontent.com/assets/10645298/23819364/29219922-066a-11e7-9961-e5dfae6073de.png)

On the EU server.

**Comment by Dream-Master** [comment]
Please try it withe the next release version.
