### ISSUE TITLE
Creosote to Lubricant

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1195]
Any chance you can change the recipe in the Distillery to process more at a time, similar to the Brewery recipe?  I get that it's cheaper material wise since you don't use up a dust but at only 1 ml per 16 ticks it took nearly an hour to make 4 buckets (and a ton of EU).

**Comment by Dream-Master** [comment]
@kris449 Why you are not using this recipe?
![image](https://cloud.githubusercontent.com/assets/2970688/23804821/cd06dcf0-05bb-11e7-82b6-c2d26e26282c.png)

**Comment by kris449** [comment]
Mainly because I don't have a brewery yet lol.  But creosote is "free" and so is power, I just don't know why it has to take such a long time.

**Comment by Dream-Master** [comment]
New Distillation Tower recipes power uses per 1mb Lubricant is now 96 eu before was 128     
   ``GT_Values.RA.addDistillationTowerRecipe(Materials.Creosote.getFluid(1000L), new FluidStack[]{Materials.Lubricant.getFluid(500L)}, null, 400, 120);
        GT_Values.RA.addDistillationTowerRecipe(Materials.SeedOil.getFluid(1400L), new FluidStack[]{Materials.Lubricant.getFluid(500L)}, null, 400, 120);
        GT_Values.RA.addDistillationTowerRecipe(Materials.FishOil.getFluid(1200L), new FluidStack[]{Materials.Lubricant.getFluid(500L)}, null, 400, 120);``

**Comment by Dream-Master** [comment]
New Distillery recipe.
Add oil to it
1mb Lubricant here use now 384 eu now 240 eu
``        GT_Values.RA.addDistilleryRecipe(ItemList.Circuit_Integrated.getWithDamage(0L, 4L, new Object[0]), Materials.Creosote.getFluid(90L), Materials.Lubricant.getFluid(30L), 240, 30, false);
        GT_Values.RA.addDistilleryRecipe(ItemList.Circuit_Integrated.getWithDamage(0L, 4L, new Object[0]), Materials.SeedOil.getFluid(40L), Materials.Lubricant.getFluid(10L), 80, 30, false);
        GT_Values.RA.addDistilleryRecipe(ItemList.Circuit_Integrated.getWithDamage(0L, 4L, new Object[0]), Materials.FishOil.getFluid(30L), Materials.Lubricant.getFluid(10L), 80, 30, false);
        GT_Values.RA.addDistilleryRecipe(ItemList.Circuit_Integrated.getWithDamage(0L, 4L, new Object[0]), Materials.Oil.getFluid(120L), Materials.Lubricant.getFluid(60L), 160, 30, false);``


I hope this will help.

**Comment by Dream-Master** [comment]
Need GT 5.09.27.33

**Comment by kris449** [comment]
So it's 90 -> 30 now instead of 3 -> 1?  Thanks!

I still don't get why the distillation tower is MV though, almost all the recipes I can find for lubricant are LV.  Don't know much about the tower.

**Comment by Dream-Master** [comment]
Ok but if lv is ok the other recipes will be too.

**Comment by kris449** [comment]
Well looks like it takes HV just to build it so I'm not gonna worry about that just yet lol.

**Comment by Dream-Master** [comment]
Let it open since it is live.

**Comment by Dream-Master** [comment]
The recipes looks different because they can be devided by 2 or so. But they much faster then before.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23810813/618ab1f0-05d3-11e7-8f1d-1292c881893a.png)
out of 12 Oil but only 16 ticks means less then 1 sec
1 Bucket of Lubricant made in 66,66667 Secs. out of Oil)

**Comment by kris449** [comment]
Well, you only get half the lubricant as the amount of oil you put in, so it would take twice that long. But still way faster than before (and oil isn't "free".. at least not yet for me).  So good deal, thanks again.
