### ISSUE TITLE
A mod suggestion

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1197]
Better Builder's Wand
This mods add a few better builder's wand with different modes. (More than what ExU builder's wand can do)
The recipe of the wand can be easily changed with minetweaker script as they are a little cheap to how many blocks they can place. 
It'll help when building where u need to place alot of blocks and the amount is more than ExU builder's wand can handle.  
Link: https://minecraft.curseforge.com/projects/better-builders-wands

**Comment by Dream-Master** [comment]
What do you think about this mod ?
@Namikon , @Technus , @Drobac , @bigbass1997

**Comment by Drobac** [comment]
It does look interesting

**Comment by Namikon** [comment]
Indeed. Wish I had this when I build my base back then. However, the super builders wand is already pretty powerful, but yes, it doesn't come with those useful modes. So, why not. If it's still maintained (Or mature and stable), I see no reason why this shouldn't be added.
*Random comment: I wish anyone would finally implement a "Build-to-me" wand.. (At least I can't find that on the list of modes this mod offers)*
