### ISSUE TITLE
LV Quest Improvements

### ISSUE THREAD

**Issue by Valdevon** [GTNewHorizons/NewHorizons#1198]
Some of the quests in LV are poorly ordered or have strange requirements, these are some suggestions to improve the LV quests from someone who just did them
 1. Make the wiremill an earlier quest, its one of the most efficient machines you can make in terms of saving material cost
 2. Make the ore washer quest alongside the macerator quest, instead of a macerator being required for it. I (and probably others) prefer to keep the steam macerators until I've used my steel on more useful machines.
 3. The quest to search for lithium ore is currently gated behind making a basic electrolyzer, even though you cannot get lithium dust from a basic electrolyzer (you need an MV one). This requirement should be removed.
 4. The Quest to make the basic canning machine is gated behind getting the materials for ALL THREE types of batteries. I think it should be changed to only require one of those quests, not all of them (the cadmium quest in particular is a bit ridiculous). This would make it work the same way as the battery buffer quest (which only requires you to make one of the five battery types)

These are merely suggestions and you can do with them as you like.

**Comment by VermillionX** [comment]
You can get Lithium from centrifuging dirty lepidolite dusts.

**Comment by Valdevon** [comment]
How is that relevant to this?

**Comment by Dream-Master** [comment]
Sure will into it.

**Comment by Dream-Master** [comment]
1. Wiremill now after LV Steam Turbine
2. Ore Washer now needs only LV Steam Turbine
3. I let it like ist is youneed the electrolyzer for more then Lithium.
4. Changed to or Logic
