### ISSUE TITLE
Concentrated darkness quest doesn't appear

### ISSUE THREAD

**Issue by Gemlord** [GTNewHorizons/NewHorizons#1200]
Pretty much as the title says, according to the quest books edit mode it should appear after completing "this is the end..." in novice Thaum quests, but it doesn't for me, but yet the tab itself of adept thaum is here.
http://imgur.com/a/gOgr4
according to the edit mode, the quest should be to the right of the snow queen blood quest, but it isn't.

**Comment by kokochicken** [comment]
have you checked if the quest has any other pre requisites

**Comment by Dream-Master** [comment]
You need to unlock it when you be in Tier 6 and above.
This is the End

![image](https://cloud.githubusercontent.com/assets/2970688/23874307/5f7beff0-0835-11e7-80a8-2b3a43f5413b.png)

Then the Thaumcraft craft can be opend

**Comment by Gemlord** [comment]
ah, there are 2 quests with very similar names so i confused the 2.
