### ISSUE TITLE
Mod Suggestion: Essential Craft

### ISSUE THREAD

**Issue by donoya** [GTNewHorizons/NewHorizons#1201]
I would like to suggest the addition of the Essential Craft mod. The unofficial version would be optimal as the original is seemingly no longer being maintained. Minetweaker support was planned at one point, but I don't know if it was ever implemented. Anyways, I'd appreciate the addition as it would add some really neat and interesting mechanics to the pack (for example a realistic radiation system). Here are the links to the [original](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2286105-dt-mods-essentialcraft-3-thaumic-bases-essential) and [unofficial](https://minecraft.curseforge.com/projects/essentialcraft-4-unofficial) versions.

**Comment by Dream-Master** [comment]
Nice mod maybe but to much tools, items, Orgen, Biomes etc. the pack is so huge and this mod add 12 mb off new content.
