### ISSUE TITLE
Apiarists Chest: not transferable by dolly

### ISSUE THREAD

**Issue by AntonioNoack** [GTNewHorizons/NewHorizons#1205]
the apiarists chest should be transferable by dollies, too

**Comment by Dream-Master** [comment]
So need Code changes in jaba. IDK if this ever will happen.
@Namikon, @bigbass1997 , @Technus @Ugachaga  any idea?

**Comment by Ugachaga** [comment]
It shouldn't be hard to add support for this chest [here](https://bitbucket.org/ProfMobius/jabba/src/ab8c25473367fc360fda1445ee908877b7cc1e62/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java?at=forge_1187&fileviewer=file-view-default). I'd suggest also add support for ExU Slightly-Larger Chest.

**Comment by Dream-Master** [comment]
OK another fork :-)

**Comment by Dream-Master** [comment]
@Ugachaga Forestry is open source so no problem but Extra Utilities not so far ik.

**Comment by Dream-Master** [comment]
Ok i just compiles jabba and will try it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24077006/b8f7580e-0c3f-11e7-884a-bc8a462e2e96.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24077008/be851856-0c3f-11e7-8119-b6db27ef43e6.png)

Apiary chests work

**Comment by Dream-Master** [comment]
Ok the other Forestry chets works too.

**Comment by Ugachaga** [comment]
> Forestry is open source so no problem but Extra Utilities not 

No need chest sources. Just class name and analysis nbt for correct orientation.
Are you planning to fork Jabba on Github?

**Comment by Dream-Master** [comment]
@Ugachaga I fork it allread ynd add the code. Works so far for the 3 Forestry chests. But how ik what is the right class in Extra Utilities and need other mods too a support?
Can put it on github sure.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Jabba

**Comment by Dream-Master** [comment]
@Ugachaga I forked Jaba can you add the code is needed for the oriantation because i want to put it in the fix update (Hopfully available in 2-3 Days.) Thanks

**Comment by Ugachaga** [comment]
@Dream-Master 
Well, simplest method to know class you need is add: 
`System.out.println(containerTE.getClass().toString());`
[here](https://github.com/GTNewHorizons/Jabba/blob/master/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java#L491). So every time you click Jabba somethere it will print tile.class (if any) to the console.

**Comment by Dream-Master** [comment]
Ah ok thanks
