### ISSUE TITLE
Tier 0 animal killing quests suggestion

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#1207]
"Well, for example right? Let's say i'm just starting off as a new player and i'm running around and get assigned a quest to kill 5 cows. So i'm running around, running around, and i pass by all these sheep and all these pigs. No cows! So I travel hundred of blocks and then finally find 5 cows to kill. But wait, now I have to kill 5 sheep? Those were all the way back at the beginning when I first started running around searching! So I have to go all the way back to the beginning and kill those sheep, even though I could have easily just killed them on the way to the cows to the first place. Why didn't it give me the sheep quest first!?."

Essentially, what this boils down to is that killing the different animals is something you can do all at the same time: it's not like if I don't kill a cow I can't kill a sheep or a pig, and so on. The ability to kill all of these animals is unlocked to me at the same time, and so should the quest. I am perfectly fine with being mandatory, but I should be able to hunt each of the animals independently so I don't end up purposely ignoring animals or killing them for no reason.

Cheers!

**Comment by kokochicken** [comment]
maybe having to kill all 3 in one time would be nice, or having 1 main quest and 2 optional

**Comment by Blinzer** [comment]
I'm pretty sure it's possible to make all 3 of them be main quests and have them be active at the same time.

**Comment by Dream-Master** [comment]
Ok Sheep and Pig Quests now in one row. Cow Quest will be not in Tier 0 because you dont need leather so early.
