### ISSUE TITLE
Bug in version 1.3.0.5 quest Glyceryl Trini... what?

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1209]
This is the version before current so it might be fixed (havent updated yet) in 32 EU quest there is a quest ot make Glyceryl Trinitrate that claims you need water coal dust and nitrogen to make Gly. The only recipy I see calls for water nitro and carbon dust.

**Comment by Bryfer** [comment]
Quest in book as of 1.4.0.1
![image](https://cloud.githubusercontent.com/assets/22825059/23935822/94ea4f50-094e-11e7-961d-1a12d63f52be.png)
Carbon in indeed used for the recipe.
![image](https://cloud.githubusercontent.com/assets/22825059/23935838/c3c24742-094e-11e7-9019-003a05cf5034.png)

Coal dust can be turned into 2 Carbon Dust with an basic electrolyzer, But I agree the text of the quest can be a bit missleading.

**Comment by Dream-Master** [comment]
OK will change it.
