### ISSUE TITLE
Electrotine/Nikolite issue for battery quest

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1214]
There is a quest in the lv section needing 6 electrotine, however you can't get that. You can get nikolite which is the same thing, and is used in the same way. However, having nikolite won't let you complete the quest. Electrotine battery in the lv section is the one I'm talking about

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1183

and fixed in the next version.
