### ISSUE TITLE
An idea about the development of tech/magic

### ISSUE THREAD

**Issue by hrl** [GTNewHorizons/NewHorizons#1216]
This idea comes from my server's players.

Steve is born with knowledge, he knows everything about any mods, which is unrealistic.

We could put some books/draftings/USB-Drives into dungeons, these items can be used in some recipes to unlock particular machine.

**Comment by Dream-Master** [comment]
@hrl You mean some progression system with some Compuer components?

**Comment by hrl** [comment]
Some progression system with some special items, which could be found in dungeons or somewhere.

**Comment by Namikon** [comment]
It was planned long ago to implement such a progression System. But that is almost the same amount of work (If you want to do that properly) than tweaking all those recipes, and the stopwatch for that is still ticking, after 2,5 years.

So as we lack people to take care of that in our team, and the ones we do have are busy with all sorts of other stuff, this will most likely not happen anytime soon.

**Comment by hrl** [comment]
I see..This pack is amazing and need huge amount of works. Thank you for your reply, I will close this issue now. :P

**Comment by kokochicken** [comment]
you also have to deal with problems of RNG and of doing this on a server. Ok its fun and all for like 2 machines but then you have to deal with "i cant find this one recipe and ive checked 30 dungeons" or where a high-level player has scoured hundreds of dungeons and there is very few open ones for other players

**Comment by Dream-Master** [comment]
Yes a progression system locks up things behind componets would be nice but this is a huge rework of the pack. So from my side idk if this will be ever happend.
