### ISSUE TITLE
Milkwart doesnt clean Radiation 3 debuff 

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1217]
When taking enriched naquadah rods without hazmat one gets infinit duration debuff icluding radiation 3. Although it cant be cleared by eating milkwarts. The buff stays even if you drink a bucket of milk afterwards.

**Comment by Dream-Master** [comment]
Milkwart is from Ic2 i guess? (crops?)
Radiation from IC2/GT
Not sure if we can change here anything.

**Comment by VermillionX** [comment]
Pretty sure Terrawart is for clearing radiation poisoning.

**Comment by Dream-Master** [comment]
@DietmarKracht can you test it with Terrawart and report it back here ?

**Comment by Dream-Master** [comment]
@DietmarKracht can you test it with Terrawart and report it back here ?

**Comment by DietmarKracht** [comment]
Terrawart doesnt clean it. Debuff stays

**Comment by Dream-Master** [comment]
Ok but how i can changed it. Ic2 is closed code so any  one have a solution for me?
@Namikon, @Technus

**Comment by Namikon** [comment]
Quantum Suite Nanobots should be able to cure any negative Potion effect

**Comment by Dream-Master** [comment]
@DietmarKracht can you test it please?

**Comment by DietmarKracht** [comment]
just dont use terra warts
use milk buckets instead to cure radiation. or infinity helmet

**Comment by Dream-Master** [comment]
ok.
