### ISSUE TITLE
Make us a way to disassemble wands/staffs/scepters

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1218]
Its really annoying imo having to craft a lot of wands just to get better wand imo, but well we have what we have.

Would be nice if you guys would implement a way to disassemble wands, even if we would loose everything except cores in the process.

**Comment by Technus** [comment]
Even adding the recipes took AGES.

**Comment by Dream-Master** [comment]
If I have to add those recipes manually I will never add it. If someone offer me a coded solution maybe.

**Comment by kokochicken** [comment]
super hyper low priority?

**Comment by Dream-Master** [comment]
less than that :P

**Comment by DietmarKracht** [comment]
@Drobac hat a suggestion long ago. He said that we could add better wand caps to existing wands by placing them in the arcane crafting table. Maybe make infusion reciepes for this so you dont reuire another wand for vis and use essentia instead.

**Comment by Dream-Master** [comment]
Yes but I need to add thousands of combination recipes.

**Comment by DietmarKracht** [comment]
i dont know much about thaumcraft code but if the wands stores its parts somewhere it can be done code wise

**Comment by Dream-Master** [comment]
Sure but i can't

**Comment by SirAzazel** [comment]
Wands store their parts within NBT, and wand name also updates based on parts, so it should be not that hard to make such mod

**Comment by Dream-Master** [comment]
@SirAzazel So we are waiting for you mod make this happend.

**Comment by Dream-Master** [comment]
@SirAzazel any news here?

**Comment by Dream-Master** [comment]
i guess not @SirAzazel
