### ISSUE TITLE
Suggestion: Renaming TiC tools

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1219]
Up until one of the more recent updates, we were able to rename our Tinker's Construct tools at will with a tool forge/station. About 2 updates ago though, we lost this ability and it's rather needed now that tool materials get broken with each update, which means that tools/weapons with default names are stuck with names like "Knightmetal Hatchet" when it is now made from Duralumin or Meteoric Steel.
Additionally, quest rewarded TiC tools also get stuck with default names. Like the Paper Cleaver from the TF quests, which is very quickly switched to a different material.

So yeah, Tinker's tool renaming re-enabled please.

**Comment by Dream-Master** [comment]
Try it in the next update it will be fixed.

**Comment by Technus** [comment]
@Namikon fixed the Gregworks issue when Materials enum change.

Nami any word on that?

**Comment by Dream-Master** [comment]
@Technus @Namikon It is fixed by Vexatos the GT Tico mod dev.
I chat with him and he fixed it.

**Comment by Dream-Master** [comment]
Renaming Items idk?
