### ISSUE TITLE
I can not submit a task within the server

### ISSUE THREAD

**Issue by Juese** [GTNewHorizons/NewHorizons#1220]
Dear author:
                     Such as title.I am using the newly updated 1.4.0.1. My friend said that this version can be submitted in the server GTNH task.If this situation can be resolved hope you can give me a reasonable solution, I would like to express my thanks here.

**Comment by Dream-Master** [comment]
@Juese What tasks? Did you mean Jobs?

**Comment by Juese** [comment]
Better questing quest book.   I can not use this mod in the server.

**Comment by bigbass1997** [comment]
What do you mean you can't use it? Also which server are you talking about exactly? Please clarify your issue, as I have no idea what your issue is.

**Comment by Juese** [comment]
I give an example.The first task is to get sixteen soils.When I dig down 16 soils, the task is not automatically submitted, and I can not manually submit the task.And the soil under the icon shows incomplete.The server is my official website to download the integrated package directly open to play with friends.

**Comment by Dream-Master** [comment]
Are you have a legal copy of Minecraft.

**Comment by Dream-Master** [comment]
@Juese

**Comment by Juese** [comment]
????

**Comment by Dream-Master** [comment]
@Juese 
Are you have a legal copy of Minecraft because BQ Mod have an issues before with UUIDs and Offline Players.

**Comment by Juese** [comment]
Thank you, I already know where the problem is.
Can you tell me what the BloodyQuests mod is doing now?
I remove it will not affect my game experience.

**Comment by Dream-Master** [comment]
Its for Blood Magic Quests but I not using rn.

**Comment by Juese** [comment]
okok Thank you again.
