### ISSUE TITLE
Can reuse old patterns to craft new ones in the Stencil Table

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1222]
It looks like reusing old stencils is configured off in the TiCon configuration, but you can still craft a pattern with an existing pattern by following these steps:

1. Put blank pattern in the stencil table
2. Select the new pattern
3. Replace the blank pattern with an old pattern
4. Click the new pattern, and it will convert the old pattern to the new one

They chose not to fix it in the upstream repo, not sure if you want to fix it in this pack since I notice you have it forked: https://github.com/SlimeKnights/TinkersConstruct/issues/2059

**Comment by Dream-Master** [comment]
@Technus any idea how to fix it ?

**Comment by Dream-Master** [comment]
@Ugachaga 
Did you have any idea here how to fix it ?

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/TinkersConstruct/pull/4

May or may not fix it, test it @Dream-Master.

https://github.com/GTNewHorizons/TinkersConstruct/pull/4

Scenarios to test:
- [ ] crafting patterns normally
- [ ] checking if the output pattern dissapears while switching the blank pattern to something else
- [ ] checking if the output pattern dissapears while switching the blank pattern to nothing
- [ ] placing blank pattern, selecting pattern to craft, switching the input item to something different, trying to craft the selected pattern?

**Comment by Dream-Master** [comment]
OK will test later

**Comment by Dream-Master** [comment]
@Technus I try to open the Stencil Table and i crash.

https://gist.github.com/Dream-Master/095b468643b0122ecacdf3f441302266

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/TinkersConstruct/commit/7a49754f3be0aefe1b1c3a73ced3a7d47d2dd28c

Fixed and tested.

**Comment by Dream-Master** [comment]
Cool thanks
