### ISSUE TITLE
AutoPackager vs fps

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1223]
A powered AutoPackager from... well, AutoPackager will constantly cause fps spikes every time it checks an adjacent inventory for items. This only occurs when warping/walking into an area where one is running. Placing one does not cause any fps spikes. So the means of getting around the problem of the one in my base has been to break and replace it every time I warp home.
Fps spikes occur regardless of whether Optifine is installed or not.

**Comment by Dream-Master** [comment]
@VermillionX sadly i cant do anything against it i gusee.

**Comment by Dream-Master** [comment]
@VermillionX If you want to fork it and fix it here is the link.
https://github.com/mcupdater/AutoPackager/tree/1.7.10

**Comment by Dream-Master** [comment]
ok mod will be removed in the next update.
