### ISSUE TITLE
gregtech mod crashes

### ISSUE THREAD

**Issue by Kayra123** [GTNewHorizons/NewHorizons#1224]
when i open the game it crashes for like 5 minutes the game cant load the gregtech mod here is my logs https://cdn.discordapp.com/attachments/96563656271093760/292641122394570752/fml-client-latest.log

![adsiz](https://cloud.githubusercontent.com/assets/26504091/24072170/c08ddec2-0bf3-11e7-87cc-54baeb6cf623.png)

Thx for help.Sorry for my english

**Comment by Bryfer** [comment]
Starting the game usually takes about 10-15 minutes, be patient :)

**Comment by Kayra123** [comment]
ik but it crashes after i wait 10 or 15 minutes

**Comment by Kayra123** [comment]
i want to wait but it crashes man :(

**Comment by Dream-Master** [comment]
@Kayra123 If it crash you gave to past the crah log too.
Looks for my if some Mod isn't completly downloaded or corrupted.

**Comment by Kayra123** [comment]
where can i find the crash log?

**Comment by Bryfer** [comment]
C:\Users\Maybys\AppData\Roaming\.technic\modpacks\mcnewhorizons\crash-reports\crash-2017-03-18_15.40.45-client.txt

**Comment by Kayra123** [comment]
[crash-2017-03-18_15.40.45-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/852441/crash-2017-03-18_15.40.45-client.txt)

**Comment by Dream-Master** [comment]
Try to redownload the pack and make a freh install.

**Comment by Kayra123** [comment]
i already did.

**Comment by Kayra123** [comment]
so there is no way to fix this problem ?

**Comment by Dream-Master** [comment]
at net.bdew.gendustry.custom.BeeSpecies$$anonfun$3.apply(BeeSpecies.scala:160)
	at net.bdew.gendustry.custom.BeeSpecies$$anonfun$3.apply(BeeSpecies.scala:160)

Send me your gendustry cfg file (the Bee file) there is something wrong here.

**Comment by Kayra123** [comment]
where is that file ? sorry

**Comment by Kayra123** [comment]
bump

**Comment by Dream-Master** [comment]
In your config folder

**Comment by Kayra123** [comment]
ok wait a sec

**Comment by Kayra123** [comment]
github dont supports .cfg files ...

**Comment by Kayra123** [comment]
i cant send you the file

**Comment by Kayra123** [comment]
what can i do ??

**Comment by Dream-Master** [comment]
Are you able to turn on and off an computer? I am at work so be a bit more patient and give me some time to answering

**Comment by Kayra123** [comment]
yes i can close my computer

**Comment by Dream-Master** [comment]
@Kayra123 So i tell you a few ways to contact me.
Discord : https://discord.gg/SnzNt6K
Email : dream-master@gmx.net
Past it to patebin or gist
load it up via Dropbox or pack it in a zip rar file and load it up somewhere.
