### ISSUE TITLE
Field generator

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#1225]
Was just wondering why field generator recipes were made very easy compared to before? if there is reason im fine with it but just wondering why because they are only used in a few high level recipes (quantum tanks high level/mass fabricator) and i was kinda ok with high tier-recipe. Let me know if im thinking the wrong way about this, thanks :)

**Comment by Dream-Master** [comment]
No maybe i make it to easy. Will over it again.

**Comment by Dream-Master** [comment]
Changed it a bit start with Red Steel
