### ISSUE TITLE
Bug Mana bean death and crash

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1226]
In the current version 1.4.0.1 I was eating a fire mana bean outdoors when the bean lit me on fire and instantly killed me. As soon as I saw the death text it kicked me from the server. When I relogged into my server I died 3 more times (did not crash from those) creating a total of 4 graves. To be clear the 3 deaths all happened in the same area as the first one not at the bed I would respawn at. In the first grave was all my items from my inventory. In my other 3 graves were a head, and my bat backpack (one of the adventurers backpacks). All 3 were identically full of my stuff and liquid.

I checked the server logs and it doesn't really make clear what killed me and the crash reason was:

 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by Dream-Master** [comment]
@Pockyninja and the crashlog i need too.

**Comment by Pockyninja** [comment]
Where can I get them (I assume that is client side)

**Comment by Pockyninja** [comment]
[crash-2017-03-18_13.55.39-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/852640/crash-2017-03-18_13.55.39-client.txt)
Here it is

**Comment by Dream-Master** [comment]
at com.arc.bloodarsenal.common.BloodArsenalEventHooks.onEntityUpdate(BloodArsenalEventHooks.java:126)
	at api.player.client.ClientPlayerBase.onUpdate(Unknown Source)
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerBaseSP.onUpdate(GCPlayerBaseSP.java:68)

**Comment by Dream-Master** [comment]
@Pockyninja The only mod is still in development for 1.7.10 is GC (Blood Arsenal and Player api stopped for 1.7.10)
Maybe try to report it there. I cant say much to this error.

@bigbass1997 @Namikon @Technus any idea?

**Comment by TimeConqueror** [comment]
Fixed in 1.2-9 BloodArsenal Release: 
https://github.com/GTNewHorizons/BloodArsenal/commit/b2616bb589a24a697b1154eacb14dbc17911ae8c
https://github.com/GTNewHorizons/BloodArsenal/commit/2f53bdbe5c59c063a13aa3cf9006caf12b600c74
