### ISSUE TITLE
Nikolite/Electrotine quest issue

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1227]
@ko5h found issue with quest 646 (Quest needs Electrotine but it doesnt spawn and nikolite cannot be used in quest)

**Comment by Dream-Master** [comment]
Fixed.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1214
https://github.com/GTNewHorizons/NewHorizons/issues/1183

**Comment by Dream-Master** [comment]
In the next update.
