### ISSUE TITLE
Battlegear diamond shield broken recipe

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1228]
@ko5h found issue with custom recipe of Battlegear diamond shield (seems that last modpack update broke it)
![](http://i.imgur.com/9BmkWtX.png)
![](http://i.imgur.com/DeNnCRb.png)
![](http://i.imgur.com/l7kiv5r.png)

**Comment by Dream-Master** [comment]
fixed

**Comment by Dream-Master** [comment]
In the next update.
