### ISSUE TITLE
Power Output of Nuclear Reactor

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1233]
![default](https://cloud.githubusercontent.com/assets/25528572/24089631/da1c79da-0d73-11e7-9f4a-6236dddf0d5b.png)

I built a Nuclear Reactor ( MK I ) output 180k EU/t , but there are not an efficient way to output the energy.The only thing can be used is the AFSU or the transformer in IC2 ,but both of them just provide 8k EU/t output.

![default](https://cloud.githubusercontent.com/assets/25528572/24089861/f56bd6a2-0d75-11e7-81bb-8a5971bf5123.png)

I have tried Cable (GT) ,Transformer (GT) ,Battery Buffer (GT) and Battery Charger (GT) .

None of them can be used with Nuclear Reactor.

**Comment by bigbass1997** [comment]
> I have tried Cable (GT) ,Transformer (GT) ,Battery Buffer (GT) and Battery Charger (GT)

All but one of those is correct. The Nuclear Reactor, from IC2 generates IC2 EU, not GT EU, they are not the same power. The only real way to convert IC2 EU to GT EU is using the GT Transformer for the respective tier of EU/t. The GT Transformer must be touching the Nuclear Reactor itself, it will not work when touching a Reactor Chamber. For Chambers, you will need to use either IC2 power storage blocks or an IC2 Transformer, and then still a GT Transformer after either of those.

> I built a Nuclear Reactor ( MK I ) output 180k EU/t , but there are not an efficient way to output the energy.The only thing can be used is the AFSU or the transformer in IC2 ,but both of them just provide 8k EU/t output.

What are you suggesting we should do about it? The GT tier system is pretty straight forward.. You simply need a higher tier of Transformer(s). Or you can make multiple smaller Nuclear Reactors that make less EU/t each, but then you can utilize the tier of Transformers you have available to you, to be able to utilize more of the EU being generated total over all the Reactors.

**Comment by VermillionX** [comment]
GT Transformers can be connected to the reactor directly, but not to a chamber. You can attach multiple MFSUs/AFSU to the chambers and share the load between them, with a transformer each unloading into a GT battery buffer.

**Comment by Technus** [comment]
Clearly doing it wrong then
![image](https://cloud.githubusercontent.com/assets/4737429/24091208/f49aca8c-0d46-11e7-87e5-5e4db4aa74bf.png)

**Comment by Technus** [comment]
REcent updates allow GT trafos to connect to chambers

**Comment by VermillionX** [comment]
Time to tear out my AFSUs then.

**Comment by Technus** [comment]
just to make it simple the big dot on trafo should face the chamber/reactor (unless you want it in steup up mode...)

**Comment by Technus** [comment]
--Redacted comments not reflecting state of the art

**Comment by bigbass1997** [comment]
I was not aware of these "Recent updates", I have tested it in the past, and many people have also reported not being able to connect Transformers to Reactor Chambers. So we have not been "Clearly doing it wrong", we simply were not aware of such changes. Either way, the GT Transformer is still required at minimum.

**Comment by Technus** [comment]
Poorly documented features, idk if even dream posted that in changelog

**Comment by nanmumc** [comment]
Oh..Thanks, it seems that update my game and all will be fine....Sorry to bother you _(:3 」∠)_

**Comment by bigbass1997** [comment]
Alright, seems nothing more to be done here. If you have any more questions feel free to talk to us on our Discord, and use Github for reporting issues or making suggestions.
