### ISSUE TITLE
Mice on Venus

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#1235]
After digging several hundred holes on venus to bedrock, aligned with ore veins, I can confirm that there's no Naquadah veins on Venus. The oregen spreadsheet is incorrect. So the only source of naquadah is in Asteroids until T6.

**Comment by kokochicken** [comment]
Have also mined quite extensively in Venus and have not been able to find any despite countless rare veins

**Comment by Dream-Master** [comment]
We changed the orgen on venus but i not reset this planet. Maybe you have to try to find new chuncks.

**Comment by kokochicken** [comment]
Ok I'll check later and let you know

**Comment by Dream-Master** [comment]
I will check the cfg file too to be sure it is enabled.

**Comment by Dream-Master** [comment]
Yes i remember this mix was very rare all 5000-10000 Blocks one.

            naquadah {
                S:BiomeName_None=None
                I:Density_5=5
                B:EndAsteroid_true=true
                B:GalacticraftCore_Moon_false=false
                B:GalacticraftMars_Asteroids_false=true
                B:GalacticraftMars_Mars_false=false
                B:GalaxySpace_BarnardC_false=false
                B:GalaxySpace_BarnardE_false=true
                B:GalaxySpace_BarnardF_false=true
                B:GalaxySpace_Callisto_false=false
                B:GalaxySpace_CentauriA_false=false
                B:GalaxySpace_Ceres_false=false
                B:GalaxySpace_Deimos_false=false
                B:GalaxySpace_Enceladus_false=false
                B:GalaxySpace_Europa_false=false
                B:GalaxySpace_Ganymede_false=false
                B:GalaxySpace_Haumea_false=true
                B:GalaxySpace_Io_false=false
                B:GalaxySpace_Kuiperbelt_false=true
                B:GalaxySpace_MakeMake_false=false
                B:GalaxySpace_Mercury_false=false
                B:GalaxySpace_Miranda_false=false
                B:GalaxySpace_Oberon_false=true
                B:GalaxySpace_Phobos_false=false
                B:GalaxySpace_Pluto_false=true
                B:GalaxySpace_Proteus_false=false
                B:GalaxySpace_TcetiE_false=false
                B:GalaxySpace_Titan_false=true
                B:GalaxySpace_Triton_false=false
                B:GalaxySpace_VegaB_false=true
                B:GalaxySpace_Venus_false=true
                I:MaxHeight_60=90
                I:MinHeight_10=10
                B:Nether_false=false
                I:OrePrimaryLayer_324=324
                I:OreSecondaryLayer_324=324
                I:OreSporadiclyInbetween_324=324
                I:OreSporaticlyAround_326=326
                B:Overworld_false=false
                I:RandomWeight_10=30
                I:Size_32=32
                B:TheEnd_true=false
                B:Vanilla_EndAsteroids_false=false

**Comment by Dream-Master** [comment]
B:GalaxySpace_Venus_false=true

**Comment by Dream-Master** [comment]
@VermillionX Should i add this mix to mercury too ?

**Comment by Dream-Master** [comment]
Or on Io?

**Comment by VermillionX** [comment]
Mercury seems more likely. It's nice and toasty there and there are no valuable ores there atm.

**Comment by Dream-Master** [comment]
OK will add then on Mercury.
