### ISSUE TITLE
Can not research rune of of superior capacity in version 1.4.0.1

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1237]
If you are researching blood magic in the thaumonomicon and create the research notes for rune of superior capacity you will notice the water research aspect on the bottom has nowhere to connect. It simply lacks any hex that link to the other starting aspects. As such it can not be researched.

![2017-03-20_18 29 43](https://cloud.githubusercontent.com/assets/24741793/24124672/4155e736-0d9b-11e7-8328-a359993e3ebd.png)

**Comment by Dream-Master** [comment]
try to get a new research scroll. The position are changed then.

**Comment by Dream-Master** [comment]
@Pockyninja did you try to get a new research ?

**Comment by Pockyninja** [comment]
Sorry for forgetting to answer. Yes I tried it and it worked. I dont know why the first one made a unable to be completed version.

**Comment by Dream-Master** [comment]
Happened from time to time.

**Comment by Technus** [comment]
Research scrolls are procedurally generated.
