### ISSUE TITLE
Thaumcraft tungstensteel screw is crafting quest

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1238]
In the "An awesome magic conductor" quest, the tungstensteel screws are a crafting quest instead of retrieval. If you can make tungstensteel you're probably using a lathe to make the screws so it doesn't register it.

**Comment by Dream-Master** [comment]
Ok need to change it.

**Comment by Dream-Master** [comment]
I fixed Chrome and Iridium screws too.
