### ISSUE TITLE
About Sword of the Cosmos

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#1240]
Use this sword to kill ChaosDragon and the Ender-Eyes can't complish the quests.
<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/sb9Ucg3.png" alt="commercial photography locations"></a>
<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/FQ7liTt.png" alt="commercial photography locations"></a>

Also items are droped everytime when I use this sword to click Ender-Eyes before it disapear.
<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/K32XKqC.jpg" alt="commercial photography locations"></a>

**Comment by Dream-Master** [comment]
Will look inside it.

**Comment by Drobac** [comment]
Quest is for the HEE dragon that spawns at the start of the end not the chaos dragon

**Comment by Dream-Master** [comment]
So guess i can close this @nanmumc ?

**Comment by nanmumc** [comment]
This is strange. I remeber that i had killed the EnderDragon in 1.3.x.x with crossbow(Tinkers' Construct).But the quest didn't complish.So that i mistake it for ChaosDragon...If this quest is alright now, the question can be closed.

**Comment by nanmumc** [comment]
Oh, the quest appeared after find the Dimensional Chest, but i kill the dragon at first. I suggest changing the order of this two quests.
<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/ZomzNra.png" alt="commercial photography locations"></a>
