### ISSUE TITLE
Copper

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1243]
This is the most valuble resorse in game. I'm not joking. I have alot of highttier ores in my storage, but almost no copper. Yes, it's a basic tier 0 metal(overworld), but we need ultralarge quantities of it. Please, add some more copper veins into distant planets(or deep dark).

**Comment by bigbass1997** [comment]
Copper already generates in nearly every tier of planets.

Copper/Iron/Chalcopyrite/Pyrite Ore generates in Tiers 1, 3, 5, 6, and 8.
Iron/Brown limonite/Yellow limonite/Banded iron Ore/Malachite Ore generates in Tiers 2, 3, 5, and 7.

From what I remember you can also generate copper (among other metals) by centrifuging lava, and Bees are also an option.

**Comment by Dream-Master** [comment]
@Cinobi 

                89 {
                    S:BiomeName_None=None
                    I:Density_0=0
                    B:EndAsteroid_false=false
                    B:GalacticraftCore_Moon_false=false
                    B:GalacticraftMars_Asteroids_false=false
                    B:GalacticraftMars_Mars_false=false
                    B:GalaxySpace_BarnardC_false=false
                    B:GalaxySpace_BarnardE_false=false
                    B:GalaxySpace_BarnardF_false=false
                    B:GalaxySpace_Callisto_false=false
                    B:GalaxySpace_Ceres_false=false
                    B:GalaxySpace_Deimos_false=false
                    B:GalaxySpace_Enceladus_false=false
                    B:GalaxySpace_Ganymede_false=false
                    B:GalaxySpace_Haumea_false=false
                    B:GalaxySpace_Io_false=false
                    B:GalaxySpace_Kuiperbelt_false=false
                    B:GalaxySpace_MakeMake_false=false
                    B:GalaxySpace_Mercury_false=false
                    B:GalaxySpace_Miranda_false=false
                    B:GalaxySpace_Oberon_false=false
                    B:GalaxySpace_Phobos_false=false
                    B:GalaxySpace_Pluto_false=false
                    B:GalaxySpace_Proteus_false=false
                    B:GalaxySpace_Titan_false=false
                    B:GalaxySpace_Triton_false=false
                    B:GalaxySpace_VegaB_false=false
                    B:GalaxySpace_Venus_false=false
                    I:MaxHeight_0=0
                    I:MinHeight_0=0
                    B:Nether_false=false
                    I:OrePrimaryLayer_-1=-1
                    I:OreSecondaryLayer_-1=-1
                    I:OreSporadiclyInbetween_-1=-1
                    I:OreSporaticlyAround_-1=-1
                    B:Overworld_false=false
                    I:RandomWeight_0=0
                    I:Size_0=0
                    B:TheEnd_false=false
                    B:Vanilla_EndAsteroids_false=false

Please fill it out and will add it probably.

**Comment by Cinobi** [comment]
89 {
                S:BiomeName_None=None
                I:Density_0=10
                B:EndAsteroid_false=false
                B:GalacticraftCore_Moon_false=false
                B:GalacticraftMars_Asteroids_false=false
                B:GalacticraftMars_Mars_false=false
                B:GalaxySpace_BarnardC_false=false
                B:GalaxySpace_BarnardE_false=false
                B:GalaxySpace_BarnardF_false=false
                B:GalaxySpace_Callisto_false=false
                B:GalaxySpace_Ceres_false=false
                B:GalaxySpace_Deimos_false=false
                B:GalaxySpace_Enceladus_false=false
                B:GalaxySpace_Ganymede_false=false
                B:GalaxySpace_Haumea_false=false
                B:GalaxySpace_Io_false=false
                B:GalaxySpace_Kuiperbelt_false=false
                B:GalaxySpace_MakeMake_false=false
                B:GalaxySpace_Mercury_false=false
                B:GalaxySpace_Miranda_false=false
                B:GalaxySpace_Oberon_false=false
                B:GalaxySpace_Phobos_false=false
                B:GalaxySpace_Pluto_false=false
                B:GalaxySpace_Proteus_false=false
                B:GalaxySpace_Titan_false=false
                B:GalaxySpace_Triton_false=false
                B:GalaxySpace_VegaB_false=false
                B:GalaxySpace_Venus_false=false
                I:MaxHeight_0=35
                I:MinHeight_0=65
                B:Nether_false=false
                I:OrePrimaryLayer_-1=35
                I:OreSecondaryLayer_-1=58
                I:OreSporadiclyInbetween_-1=-1
                I:OreSporaticlyAround_-1=-1
                B:Overworld_false=false
                I:RandomWeight_0=100
                I:Size_0=64
                B:TheEnd_false=false
                B:Vanilla_EndAsteroids_false=false

**Comment by Cinobi** [comment]
something like this?

**Comment by Dream-Master** [comment]
I:MaxHeight_0=35
I:MinHeight_0=65

I guess you mean the other way arround

Not copy the amount, Size and random wight from other mixes because it is desinged for the Deep Dark Dimension. Look at the copper mix.

This mix is on all dims set to false why?

**Comment by DietmarKracht** [comment]
i think this mix should be added to deep dark

**Comment by Dream-Master** [comment]
Sure but then we need to change the high and limit it to 10 y levels

**Comment by Dream-Master** [comment]
Ok added to the deep dark.
