### ISSUE TITLE
Question: Do ocelots/ tamable wolves spawn naturally?

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1244]
I've explored many snow and jungle-type biomes and have never come across a wild tamable wolf or ocelot

**Comment by Dream-Master** [comment]
Yes wolves are rare. Best chance is to find some in Twilight Forres. Ocelot are spawn in jungen forest.

**Comment by killslash** [comment]
So ocelots do spawn in anything classified as a "Jungle" biome? Like in the witchery book of biomes under Jungle

**Comment by Dream-Master** [comment]
In my testworlds I see some but sadly not rember the biome. Maybe you need to ask this question on my Discord help channels.

**Comment by Namikon** [comment]
The World-generator **RWG** (Realistic World Generation) that is used in the current official Pack (And thus on the generated world on Delta) is doing really weird things with Worldgen. Especially Ocean and Jungle Biomes are either broken or just do not exist. 

Either way, you should be able to change biomes with Witchery to Vanilla Jungle and hope for Ocelots to spawn

There might be an alternative for RWG in the near future as we're running tests with RTG (Realistic Terrain Generation). No ETA yet; but first results look promising.

**Comment by killslash** [comment]
Perhaps add some spawn eggs for ocelots as quest rewards somewhere in the meantime?

**Comment by Dream-Master** [comment]
Sure why not

**Comment by hhheeexxx** [comment]
You can buy egg in pams harvestcraft market.

**Comment by Dream-Master** [comment]
@hhheeexxx are the market fixed ?

**Comment by hhheeexxx** [comment]
I say wrong information: there is no ocelots egg in market.

**Comment by hhheeexxx** [comment]
Market need to fix.

**Comment by Dream-Master** [comment]
but the dupe bug was fixed by ugachaga so far i remeber or did i forget to update the pams file ?

**Comment by Dream-Master** [comment]
pams harvetcraft version "m" still have the bug ? @hhheeexxx

**Comment by hhheeexxx** [comment]
I get 1.4.1.1 server and client and test it 2 day ago, bug work In the version what I described. It seemed to me that there was one more important bug with this "m". May be you fix it, but not fix another?

**Comment by Dream-Master** [comment]
@hhheeexxx can you make a video and post it that i understand the second bug?

**Comment by Dream-Master** [comment]
I add it as reward to some Thaumcraft quests
