### ISSUE TITLE
Book of knowledge, Gadomancy

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1246]
Made myself the book of knowledge from gadomancy mod and started to auto reserch, very simple reserch notes seems to work, but if a note is in there long enough it just disapears, is it possible that the note despawns like an item on the ground?, or mob spawn limit, or just a bug, dont know but thought is should put it up here

**Comment by Dream-Master** [comment]
@HellFirePvP can you answering this Question?

**Comment by HellFirePvP** [comment]
mob spawn limit most likely since the research note is converted into a 'persistent' entity that's linked to the book. So.. well. i'd blame the spawn limit. Is there a way to blacklist/whitelist the items for that dream? Asking as this might also occur with the aura pylon's crystallized essentia.

**Comment by Dream-Master** [comment]
gregtech set despawn limit to 10 mins via config so far ik. not sure if this is for all items or if items can be whitelisted.

**Comment by Ghengis88** [comment]
hm, think it must have been more then 10 minutes, i can do a test later and come back with results

**Comment by Dream-Master** [comment]
we will get an update soon.

**Comment by HellFirePvP** [comment]
Uhm, just something here: Those items are not despawning by standart-entity-despawn means. I'm extending off of Thaumcraft's permanent item entity. It literally doesn't despawn due to age. It **must** be something else.

**Comment by Ghengis88** [comment]
agreed, dont seem to be time related, started a resertch and it finished and has been lying the finised now, tossed it in and 80 minutes later it is still there, were logged of for the last 25 minutes and kept it loaded with chunkloder so no interference with how the world is loaded from player/chunkloader that i suspected erlier.
Low activity on the server tho, betwen 5 and 8 players online.
Had a golem despawn a few weeks back, ( have not botered with them after that), might it be the same thing despawning them?

**Comment by Ghengis88** [comment]
another reserch note almost complete, 10 players online (mobbs are still spawning) might be it is despawned by the same mechanic that prevents mobs from spawning, need to try again when mobbs are blocked.

**Comment by Dream-Master** [comment]
@HellFirePvP so that mean there is no fix necessary?

**Comment by HellFirePvP** [comment]
I'm just stating that it's not Gadomancy at fault for this :|

**Comment by Ghengis88** [comment]
@Dream-Master @HellFirePvP could it be the same reason golems dont work? (Bryfer told me they dont work erlier, becous of them despawning, havent really checked it out myself) and for a simpelton like me, why is that?

**Comment by Namikon** [comment]
If it was related to any automated Clearlag purging or global entity Limit, that "issue" is gone. There is no limitation anymore, and no automatic purge.
If entities "disappear", then an operator has most likely issued a kill-entity command while trying to stabilize Server TPS.

**Comment by Ghengis88** [comment]
so then there is basicly nothing to do about it?

**Comment by Dream-Master** [comment]
Did it work in sp ? @Ghengis88

**Comment by Ghengis88** [comment]
never set it up on singelplayer, only on live server, but i cant see a pattern.. sometimes it works sometimes. i can try it on singleplayer this weekend

**Comment by HellFirePvP** [comment]
In any case you could try and automate it using the Arcane dropper in the range and only pull researched research notes out of it. If it 'survives' the time that it needs to be researched, the dropper 'pick it up' and let it be transfered through the pipe, if not, well....

Also, in case you don't do that yet, use bookshelfes around the book of knowledge...

**Comment by Ghengis88** [comment]
yea i am using bookshelfs, but using the arcane dropper was a greate idea, will deffinitly do that, thx

**Comment by Dream-Master** [comment]
@Ghengis88 @HellFirePvP i guess this issue can be closed?

**Comment by HellFirePvP** [comment]
I believe so?
