### ISSUE TITLE
Tinkers tools materials broken/changed during version change...

### ISSUE THREAD

**Issue by AntonioNoack** [GTNewHorizons/NewHorizons#1247]
I know there is such a thing already in planning, still a lot of my (Miner952x) tools on the EU-Server and some of Fifa12343 are broken, e.g. Rubracium and Awakened Draconium instead of Obsidian and Draconium. It would be nice if you could fix those tools...
and maybe prevent future changes

**Comment by Dream-Master** [comment]
Fututur change would be impossible. 1.4.1.0 have a config options that materials are locked to fix id's. Ask @Drobac how to fix existing tools.

**Comment by Namikon** [comment]
You will have to re-craft them one more time, or at least swap the parts to get your old tool back; Sorry about that. TinkersGregworks had a bug that caused this, but the bug is fixed by now, so this will never happen again.

**Comment by Dream-Master** [comment]
will close it when the patch is live.

**Comment by AntonioNoack** [comment]
ok :) good to hear that it won't happen again

**Comment by Dream-Master** [comment]
Maybe one time more in the next update because we change to the stable version but after this no more.
