### ISSUE TITLE
OpenComputers, 3DPrinter config, pls allow more maxShapes!

### ISSUE THREAD

**Issue by AntonioNoack** [GTNewHorizons/NewHorizons#1248]
We print in 2D (instead of 3D) and even there 64 shapes are a bit few. The server shouldn't suffer from it, only clients a little.

It would be nice if more shapes were allowed, e.g. like 256 (which would be enough for every 2D print).
Thx if it is fixed.

**Comment by Dream-Master** [comment]
Does this helps?

**Comment by bigbass1997** [comment]
If I remember correctly, the maxShapes has already been increased on the Official server.

**Comment by Dream-Master** [comment]
yes @bigbass1997

**Comment by AntonioNoack** [comment]
yes 256 helps :D
