### ISSUE TITLE
Crops breeding

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1249]
Is there supposed to be something here?  Was only the choice award and no coins.

![crops](https://cloud.githubusercontent.com/assets/26042867/24219615/cf58e140-0f1d-11e7-846c-5126f64db863.png)

**Comment by Dream-Master** [comment]
No i will check it.
In the new updates i add more Quests here.

**Comment by kris449** [comment]
So today right?  😄

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/fylz7zbzfknluvi/DefaultQuests.json?dl=0

@kris449 Try this file and hit /bq_admin default load.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24219953/edca94fe-0f48-11e7-8dfd-85e048f0a5e3.png)

**Comment by kris449** [comment]
Yep I got it and "First Breeding" after it.

**Comment by kris449** [comment]
Somehow a quest in "They are Coming" got completed, I'm not sure if it was before or after the file you gave me, but how do I turn off the entire tab?

**Comment by Dream-Master** [comment]
if you play in sp you can reset it in the editor /bq_admin edit
if not ask a admin to reset it.

There are a few /bq_user    commands i not know exactly

**Comment by kris449** [comment]
Okay I found it. The command is /bq_admin reset (quest ID).

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24222527/bea82ede-0f52-11e7-88cd-b2f4d1f17b69.png)

it can but it is more complicated.

**Comment by kris449** [comment]
Okay okay I didn't see that button. Thanks though!
