### ISSUE TITLE
Biomes O' Plenty not compatible with vanilla recipes

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#1250]
![recipes](https://3.downloader.disk.yandex.ru/disk/136853f443787ba80002a83efaadb7c94e42227a9373aee686d8184cc4e83fc5/58d3524f/Wx09znrsdKaiKU6SdXXNbHmTHTwAW9vREpRhRqx2KbQaStJBuXSm5uiM0CZodgkYBZypAChE4-rsxZUnQwCw1Q%3D%3D?uid=0&filename=jacaranda.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=132914&hid=40a5836f152fa0dc9b5ec3d545144779&media_type=image&tknv=v2&etag=48af84fff836a65948462296d34291f7)

**Comment by Bryfer** [comment]
You can use the architect table to craft fences (and more things) with pretty much all kinds of materials

**Comment by code32** [comment]
Thank you

**Comment by Dream-Master** [comment]
Oak fence cant be made out of some other wood. Maybe Biomes o plenty wood not have own Fences.

**Comment by Dream-Master** [comment]
The pic is gone and i cant contol anymore what recipe you show there.
