### ISSUE TITLE
Wrench not working on cables

### ISSUE THREAD

**Issue by Ormathonz** [GTNewHorizons/NewHorizons#1253]
Just started going into LV age and we miss placed some cables. 
The crafted gregtech wrench (we even spawned in and made a high quality version) does not work to remove them. Even the electric wrench from IC2 does not work. We tried copper and tin 1x wires and cables.

**Comment by bigbass1997** [comment]
You have to use the Wire Cutter tool instead. WAILA's detection of what tool to use is wrong.
