### ISSUE TITLE
Suggestion: Note the rubber making efficiency of chemical reactor in quest book

### ISSUE THREAD

**Issue by killslash** [GTNewHorizons/NewHorizons#1254]
So you can make cables about 6x as efficiently (for rubber) with the chemical reactor in to assembly machine. 

Not counting the sulphur, you can turn 9 rubber dust in to 9 ingots worth of rubber, which then go in to an assembly machine to make wires at a 1:1 ratio.

Compares to allow smelter rubber turning 3 rubber dust in to 1 ingots worth, and needing 2 ingots of rubber for a wire.

So 6 rubberdust/cable vs 1 rubberdust/cable. 

Seems like many players do not know this and could be noted in the quest book somewhere. Probably move the machine quest up further in the quest progression.

I actually think the best LV machines to make after plate bender is  the chemical reactor/assembly machine to increase efficiency of rubber. It was the biggest LV bottleneck for me.

**Comment by Dream-Master** [comment]
OK will look into it
