### ISSUE TITLE
I am translating modpack «GT New Horizons» on RUS. What happened to <<Hardcore Darkness>>? 

### ISSUE THREAD

**Issue by MajaProduction** [GTNewHorizons/NewHorizons#1255]
I am translating modpack «GT New Horizons» on RUS.(mods, quests) How do you feel about this? And what happened to «Hardcore Darkness»?  I also have some improvements for modpack textures, I hope you contact me.

**Comment by bigbass1997** [comment]
> And what happened to «Hardcore Darkness»?

What do you mean what happened? We haven't had that mod in here for a long time, if ever at all.

>  I also have some improvements for modpack textures

Textures for the entire modpack or one or more specific mods? Whatever the case feel free to contact DreamMasterXXL on our Discord. https://discord.gg/010i4hQTIv3BYCkGf

**Comment by MajaProduction** [comment]
Thank you.

**Comment by MajaProduction** [comment]
Just in the very first quest indicated that Hardcore Darkness should be, well, I will correct this.

**Comment by bigbass1997** [comment]
Hardcore Darkness the feature, not the mod. It is a feature of RandomThings, basically forcing the minimum light level visually to complete darkness.

**Comment by MajaProduction** [comment]
Okay....But nothing does not change visually....

**Comment by bigbass1997** [comment]
Uh not quite sure what you are trying to say.

**Comment by Dream-Master** [comment]
reopen it if you want @MajaProduction
