### ISSUE TITLE
Blood magic altar

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1257]
Some metals in BM altar is not magic enough, i think, Lets change them:
t3 altar - Thaumium
t4 altar - Void metal
t6 altar - Ichor blocks with recipy:
Infusion: center - Mithril block, surrounds - 2 ichor, 2 ichor ingots, 1 life shard, 1 soul shard, 1 concentrated catalyst and 1 standart binding agent.

**Comment by Dream-Master** [comment]
Ok but then Ichorium Block need a new Thaumcraft research Site iside the Book.
