### ISSUE TITLE
Nether star wire recipe [Minor discrepancy][Low priority]

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1258]
The "1x Nether Star Wire" can only be made from Nether Star Plate with Wire Cutter.
There is no ingot form of Nether Star so the Wiremill recipe does not exist.

I propose adding the following recipe: Nether Star Plate ->2 "1x Nether Star Wire" in Wiremill with standard energy (400 EU, 4EU/t, 5 sec). That requires to get 9 Nether Stars first and compress them.
OR just plain Nether Star -> 2 "1x Nether Star Wire"

**Comment by Dream-Master** [comment]
Sure i could change it but if you are able to make Netherstar wires i guess you dont care to kill mor Withers or find Netherstar ore obn some planet.

**Comment by DietmarKracht** [comment]
We have 120k netherstar. So no need  of better wiremill reciepe

**Comment by Methes** [comment]
And I have unlimited copper and there is a wiremill recipe for copper wires, that's no solid reason.
If discrepancy is not enough of a reason, consider this:
1) You like "realism" in the pack. Now you can chop off bits of the Nether Star to get a wire with a File but you can't do that in a wiremill.
2) Around MV/HV you can make relatively easy Wither farms and create the best wires in the game with no limitations. So that's kind of a balance issue.

Seriously though: saying you have 120k netherstars is like saying you make 12mil Euro a year so food being expensive is not a problem. For everything in the game there's always a point when you can't easily make tons of it and that's when balance becomes important..

**Comment by DietmarKracht** [comment]
At the time you might use netherstar wires you already reached t7 planets and can mine netherstar ores. so there is no reason to add a reciepe

**Comment by Dream-Master** [comment]
So far i know are all Gems Plate make out of Blocks. Adding recipes is not the problem but then i need to need more to add then just only this wire recipe i guess?

**Comment by Dream-Master** [comment]
I will ad a recipe wich using Netherstar Sticks in the Wiremil.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24451521/74453c1a-147f-11e7-9c08-fac0c14b8b01.png)
