### ISSUE TITLE
Neutronium processing time

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1259]
Hello. I want to discuss the neutronium processing time it this pack. As greg works(at start) - neutronium is very dense, hard to obtain(highcost infusion) and have only one real use - 16 plates for Ult battery. Now we have alot of uses for neutronium in greg itself (UV machines) and other mods in this pack (like draconic evolution). But, neutronium processing time is still insanely slow. Look at the table below:
http://imgur.com/iLLlEKh
as u can see, it's faster to smelt 2 neutronium in furnace and file them than extrude 2 rods in extruder! This is realy stupid, and must be changed, in my opinion. The best thing we can do - lower the times of processing for neutronium machine parts(rods, bolts, gears, screws, and so on). Neutronium isn't the best material in our pack, so why not?

**Comment by Dream-Master** [comment]
@Technus any idea how we can do this in code not make minetweaker recipes for each?

**Comment by EvgenijM86** [comment]
I usually solve those kind of problems by simply building more machines.

**Comment by Drobac** [comment]
I agree with Cinobi, the neutronium does take a bit too long to process in comparison of how much you need it in higher tiers. I had to have several EBFs running on UV just to keep up with crafting demands

**Comment by Dream-Master** [comment]
@Technus can you take care of it?

**Comment by Technus** [comment]
Yes either we keep it like it is, or i remove neutronium. The processing time is meant to be a joke.

**Comment by Technus** [comment]
Still the processing time is based on material mass and neutronium is defined like 10000 neutrons? so it is really massive compared to other regular matter coposed od maximum of like 300neutrons mass of value.

**Comment by Dream-Master** [comment]
If we remove neutronium we get more problesms with all this recipes. Only overriding some recipes would help i guess. @Technus

**Comment by Cinobi** [comment]
Well, there is another way to solve this problem. We have a fluidextractor-fluidsolidifer recipy for neutronium plates with normal smelt\solidifer time - 1 second MV(melt) and someseconds LV (solidife). Adding more molds(for small gear, rod, bolt and so on) will solve the problem. Well, kind of solve.

**Comment by DietmarKracht** [comment]
small gear mold exist i believe. we need a dense plate mold too :D

**Comment by Technus** [comment]
Yeah sure whatever, let me add dust molds too.

**Comment by Dream-Master** [comment]
Ok i add molds but no dust molds :P
