### ISSUE TITLE
Stupid me with stupid warp

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1260]
Forgot to aply Bathsalt befor going to Mars, and had the decay effect spawn while i were loading oxygen tanks and now the entrence room is flooded by water....

**Comment by Dream-Master** [comment]
@Ghengis88 sorry can't follow you. Can you explain a bit what the issue is here? Thanks

**Comment by Drobac** [comment]
Ye, ill fix it when I get time

**Comment by Ghengis88** [comment]
the warp effect decay replased leaves and dirt to water in the stargate room on Mars,  so now there is water everywher, and i cant repair the damage i did becous the area is townrotected, 
hmm maby this is the wrong place to post this? should i talk to Drobac instead?

**Comment by Dream-Master** [comment]
@Ghengis88 no everything is fine can just post it here that no one forgot it.

**Comment by VermillionX** [comment]
pretty sure someone's done that to the Moon's Gateroom as well.

**Comment by Drobac** [comment]
Fuxed
