### ISSUE TITLE
Suggestion: remove roguelike dungeons

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#1261]
so this a tough one and also i don't like just saying "throw this mod out", but unfortunately i will have to be devil's advocate here at least to a certain degree for a couple of reasons.

before i say why this mod is bad, i want to say that i do like the concept behind this mod and i do enjoy completing the dungeons. i think that it gives an incentive that would otherwise not be there to battle and conquer for resources that can be used early on to make progress faster.

that being said, this mod is flawed from the get go. when you're inside FPS drops TREMENDOUSLY, even for the most powerful computer(i'm talking even 1000+ dollar computers cannot handle it). the lower you go, the lower the fps you get to play with, but the more skill demand there is to fight because there's more spawners to light up and more tanky monsters to fight... but you can't fight because the fps lag doesn't let you even play the game like you want to at all. it reaches a certain point that when you're in the inferno level(bottom level), a computer like mine which is i7 and 12gb ram and runs the game smoothly reaches as low as 4 to 5 fps and stays constantly under 10 fps. i want to enjoy the thrill of conquering the dungeon but i simply cannot because the dungeon causes absurd amounts of frame drops.

do i think this mod should have a place in the pack if you ignore the technical issues? absolutely, i don't think there is anything inherently wrong with it being included in the pack, as it provides a cool mid-level incentive to conquer. but if the mod is so inefficient and requires absurd PC specs where even an i7 core with a decent graphics card(radeon 2gb dedicated) is dropping to 4-5 fps constantly when it's running the game perfectly fine anywhere else, it's not up to par with the rest of mods in the pack in making the experience of the pack fun and intriguing. even if you manage to conquer the dungeon, you had no fun while doing it because you were completely crippled by the game.

so in my humble opinion, this mod should be removed or a solution should be found to fix the insane fps problems it causes while you're inside of it.

**Comment by Dream-Master** [comment]
@Blinzer Did you play Sp or on a Server.

I won't remove a mod with so much generated stuctures. My MP map is 2,5 Years old and i not want to make some change. Have to find another way.

**Comment by Blinzer** [comment]
if you remove the mod, the already generated world is not affected. i've confirmed this by doing it myself in the past. your multiplayer world would not be affected, the only difference is that it would not generate any new dungeons in new chunks.

i've only played on multiplayer servers, which further proves my point(playing local would be even heavier than having a server shoulder the weight of running the game's world).

**Comment by Dream-Master** [comment]
@Blinzer Then the best way is you don't go to any Dungeon anymore because i guess it is only a personal suggestion from you and not from the majority to remove this mod.

**Comment by VermillionX** [comment]
I have never heard of nor experienced any fps drops in or near a RLD. There's nothing in there to cause it.
They're fairly large structures, yes. But they're made entirely of vanilla blocks with only a few tile entities.

**Comment by Saereth** [comment]
When we ran our gtnh private server we never experiences issues like this from roguelikes

**Comment by Dream-Master** [comment]
Ok Rouge Like Dungeons Stay inside the Pack.

**Comment by Blinzer** [comment]
it's not when you're around the roguelike dungeon, it's when you're inside of it and trying to actually beat it that your fps drops like mad

but it doesn't matter that much to me at the end of the day
