### ISSUE TITLE
Smeltery Autocrafting

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1262]
There is an issue with the GT NH components like the brick form where you can not autocraft using those items. Even with ore dicting enabled. So i wanted to autocraft the unfired seared bricks and that doesnt work. Crafting seared bricks from those unfired ain`t possbile too. I get an NPE every time but only client side so it shows up in the chat.
Will add the exact discription later

**Comment by Dream-Master** [comment]
@DietmarKracht Need more infos please.

**Comment by DietmarKracht** [comment]
I have my pattern setup the following: 8 grout and 1 brick form = 8 unfired seared bricks - use substitutions: yes. 
Clicking on crafting raises the following exception BUT only in chat. no client crash or kick from server
Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateExeption: java.lang.NullPointerException

**Comment by DietmarKracht** [comment]
Just realized the reciepe with 1 grout + brick form = 1 unfired seared brick does work without producing that error message

**Comment by Dream-Master** [comment]
Mabe it have somethings to do that the mntweaker script reuse the Form. I thin i have to add the recipe to java code.
