### ISSUE TITLE
Alumite and Aluminum Brass singularity

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1263]
Those are the most expensive ones. Why? Because you can only create the ingots for them in the smeltery. Aluminum Brass requires 1800 Blocks times 9 = LODS of ingots. Same goes for Alumite. Either add a mixer recipe for both or an alloy smelter or ender IO alloy smelter reciepe.

**Comment by Dream-Master** [comment]
Added mixer recipe and shapless recipe.

**Comment by DietmarKracht** [comment]
#4585 and #4586
