### ISSUE TITLE
Unable to build third tier blood altar in BloodMagic?

### ISSUE THREAD

**Issue by hrl** [GTNewHorizons/NewHorizons#1266]
Tested in SSP and SMP. The divination sigil says that this is a 2nd tier blood altar.

![2017-03-29_22 05 59](https://cloud.githubusercontent.com/assets/5822321/24459087/45734230-14cd-11e7-9eb9-3ef4ab2f4d90.png)

**Comment by Dream-Master** [comment]
You need Titanium Blocks from GT in 1.4.0.1. In 1.4.1.0 you will need a new Block Called Blood-soaked Thaumium Block which can be made in a Tier 2 Altar out of a Thaumium Block.
I will some Quests in the Future to explain it.

**Comment by Dream-Master** [comment]
@hrl does ist work? Can this be closed?

**Comment by hrl** [comment]
Sorry for the late response.. I'm playing 1.4.0.1, it works.

**Comment by Dream-Master** [comment]
np its my fault not write a propper wiki :)
