### ISSUE TITLE
Mod replacing suggestion

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1267]
I would like to suggest to replace the AutoPackager mod with Compactor mod.
Link to compactor mod: https://minecraft.curseforge.com/projects/compacter

The AutoPackager causes alot of tick lag after relogging in or reloading the chunk after leaving the chunk for some time. And they basically have the same functionality.

**Comment by Dream-Master** [comment]
Ok will look into this mod

**Comment by Dream-Master** [comment]
@noobyaran9 Is this tested?

**Comment by bigbass1997** [comment]
Why use either of the mentioned mods? GregTech has the "Packager" machine that is not just used for storage, but can auto-craft 1x1, 2x2, 3x3 recipes and all small/tiny dusts. I have used it, and does not create any noticeable lag.

**Comment by Dream-Master** [comment]
That's true so remove the packager mod.

**Comment by VermillionX** [comment]
The problem with both the GT Packager and the Compacter is that they require items to piped into them, and they have a finite internal storage. The AutoPackager at least, will check the inventory on it's left side and attempt to craft 2x2, then 3x3 and output on it's right side.

**Comment by Ugachaga** [comment]
GT Type Filter (dustTiny) -> GT Super Buffer (output by 9) -> GT Advanced Packager
Didn't try this in GTNH yet.

**Comment by bigbass1997** [comment]
So the only argument for the AutoPackager is that it is slightly easier than the GT Packager? Still seems pretty dumb to have an entire mod just so people don't have to craft a couple more machines. A chest hooked up to a couple GT Regulators, or as Ugachaga mentioned, the use of either the Chest Buffer or Super Buffer and you get around that entire argument.

Also just because 150+ dust variations exist, does not mean that a typical player will actually need to deal with them, and again, even if they did they can use the Chest Buffer or Super Buffer, or a chest combined with the Regulator.

**Comment by Dream-Master** [comment]
Are this lag spikes are client only or lagging the whole server?

**Comment by Dream-Master** [comment]
If it cause huge Server lag then we can remove it when GT make it the same way and i dont care if you need one ore two more things crafted.

**Comment by VermillionX** [comment]
The AutoPackager doesn't cause server lag. It causes fps spikes every time it checks an inventory. I reported this a few days ago.

**Comment by Dream-Master** [comment]
Ok so we need to voting about it, let this mod in or remove it.

**Comment by bigbass1997** [comment]
Why would we vote on this? It is pretty clear that the GT Packager works well. But if you really want to ignore the other posts explaining this, I vote to remove the mod and do not replace it with a new one.

**Comment by Namikon** [comment]
AutoPackagers caused tremendous tps impact while Drobac and I had these machines in our Voids. The issue with those is that each of them tries to find recipes to craft the small dusts into large ones, and cycles over those gazillions of recipes Gregtech is adding. Not a problem without, but definitely one with Gregtech loaded.

I think we both ended up using the Packagers from GT, as they are far more "stable" and the "meant to be" machines for this task.

I'd assume the suggested mod will have the same issues, as checking valid recipes is not something you can easily bypass in your mod. So the best way would be to remove both and stick with the "GregTech" way.

If those machines are too difficult or whatnot, we are now able to change this as we like. Back when we added AutoPackager, we had to rely on other people to implement our ideas.
