### ISSUE TITLE
Download of  scala-swing_2.11-1.0.1.jar Failed!

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1268]
log:
https://pastebin.com/DeRN2jYY

screen:
![error](https://cloud.githubusercontent.com/assets/7855510/24518060/308a8772-1589-11e7-8cdc-4bf9d9aecc40.png)

**Comment by Dream-Master** [comment]
@hhheeexxx minecraft librarieshost this file. So its ot us fault.

**Comment by hhheeexxx** [comment]
I think trouble is: I can't open https://files.minecraftforge.net/

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24519716/471e3928-1586-11e7-9faa-b4f3916bab8c.png)
could be. What contry you are you loading from?


Client Pack : https://www.dropbox.com/s/c4qt8fwjw9j8bpo/GT-New-Horizons-Client-Pack-1.7.10-1.4.0.1.zip?dl=0

**Comment by hhheeexxx** [comment]
I'm from Russia.

**Comment by Dream-Master** [comment]
We have many russian players here without any issuses. Try to Join my Discord we have a russian Channel.

**Comment by Dream-Master** [comment]
So i close this now.
