### ISSUE TITLE
Knowledge Notes with 0 knowledge points (1.4.1.0pre3)

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1269]
So far I have found 3 knowledge notes in chests (from HardcoreEnderExpansion) in 1.4.1.0pre3 and all of them give 0 knowledge points. In 1.4.0.1 they gave somewhere between 10-40.

**Comment by Dream-Master** [comment]
Mhm ok need to check it

**Comment by EvgenijM86** [comment]
On topic of strange loot: I have found a "Broadsword" in a chest that says "THIS TOOL HAS INCORRECT DATA. Place this tool in a crafting window to update it.". I tried placing it a crafting window and it returns Broadsword with the same error message.

**Comment by EvgenijM86** [comment]
I am sorry, this seems to be my mistake. My config folder was messed up.

**Comment by EvgenijM86** [comment]
Or not.... Now I made sure that my config is identical to upstream, then I started minecraft and my config directory changed to this:
255 files changed, 17 insertions(+), 89132 deletions(-)

I guess a lot of files are moved somewhere else for some reason.

**Comment by Dream-Master** [comment]
What files? All important files are already added by technical launcher

**Comment by EvgenijM86** [comment]
These files: https://pastebin.com/CiBQXA1B

They are added when game is first started. Probably nothing important. But at first I thought that my config directory is corrupt.

**Comment by Dream-Master** [comment]
Never seen it before. But the knowledge note have 0 points?

**Comment by EvgenijM86** [comment]
Yes: https://ibb.co/nohjFa

And all those ingots that you see in the screenshot are from chests that I found in the world by running around. It even spawned stainless steel ingot for me. Loot seems more interesting and worthwhile.

I also found "Broadsword" that says "THIS TOOL HAS INCORRECT DATA".

**Comment by Dream-Master** [comment]
Can you show a pic from the broad sword

**Comment by Dream-Master** [comment]
Ah ok I see the problem Knowledge Nots not have nbt data. Will add it

**Comment by EvgenijM86** [comment]
Here is Broadsword screenshot: http://imgur.com/a/8qBRU

**Comment by Dream-Master** [comment]
@EvgenijM86 can you test for he knowledge fragments issue. Replace the few files in the too much loot folder wit the nwer one from github.

try to type ingame /loot reload or make a new world and generate new chunks. In there the chets have nwe loo hopfully.

**Comment by EvgenijM86** [comment]
Ok. I have copied those files and waiting till it loads...

**Comment by EvgenijM86** [comment]
It worked. I found 20 pts knowledge note. But they use a little bit different formula for points (if that matters):

https://github.com/chylex/Hardcore-Ender-Expansion/blob/HEE1-1.7.10/src/main/java/chylex/hee/item/ItemKnowledgeNote.java#L45

(rand.nextInt(4) * rand.nextInt(4) + rand.nextInt(3) + 2) * multiplier

Multiplier is usually 3:
https://github.com/chylex/Hardcore-Ender-Expansion/blob/HEE1-1.7.10/src/main/java/chylex/hee/world/feature/WorldGenBlob.java#L133

This results in:
(((0+1+2+3)/4) * ((0+1+2+3)/4) + ((0+1+2)/3) + 2) * 3 == (1.25 * 1.25 + 1 + 2) * 3 == 15.75 points on average

**Comment by Dream-Master** [comment]
The problem is I can't set this with this list. @Namikon or we can add this to the mod.

**Comment by EvgenijM86** [comment]
Well, I am just letting you know. I am ok with any value that you assign if it is not zero :)

**Comment by Dream-Master** [comment]
Ok I could add new like 5, 15, 25, 35

**Comment by EvgenijM86** [comment]
I have found 2 more Broadswords with incorrect data. It seems that those Broadsword are supposed to be random TiCo tools, but for some reason they end up as a Broadsword (default?).

**Comment by Dream-Master** [comment]
i will look into the cfg file. Did you find some Tico pickaxes because i add it too?

**Comment by Dream-Master** [comment]
Found it and will rework it

``<loot item="TConstruct:broadsword" damage="0" weight="10" count_min="0" count_max="1"/>``

Sword not have nbt data.

**Comment by EvgenijM86** [comment]
I did not find any TiCo tools, except those Broadswords. Maybe unlucky.

**Comment by Dream-Master** [comment]
so its not sure if the other tools works.
