### ISSUE TITLE
UV piston can't be crafted...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1271]
... couse ZPM piston don't want to be scanned.

http://imgur.com/a/tHDyO

**Comment by Dream-Master** [comment]
Did it show up in nei?

**Comment by Drobac** [comment]
The recipe shows up fine but when you put the item in the scanner the process doesn't start at all

**Comment by Dream-Master** [comment]
I see there are no recipe for in code

**Comment by Dream-Master** [comment]
@Cinobi , @Drobac is the missing uv piston rcipe not working in 1.4.0.1 or in 1.4.1.0pre

**Comment by Technus** [comment]
for some reason it does not work, i bet the same cause as other recipes not registering properly
probably we have a loop that doesnt register last recipe or something.

**Comment by Dream-Master** [comment]
Did we need to add this recipes to the core mod or in another file that it loads a different time @Technus

**Comment by Technus** [comment]
fixed NPE on mercury fluid
