### ISSUE TITLE
Cannot craft Ingot Cast (1.4.1.0pre3)

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1272]
I build a smeltery in this version and for some reason nothing happens when I place iron ingot on casting table and right click on faucet. I also tried with other ingots - nothing seems to work. I was able to create other casts (for TiCo tools) without problems.

Edit: recipe is visible in NEI for various ingots (including iron ingot), but it does not work.

**Comment by EvgenijM86** [comment]
I was able to create Ingot Cast by using gold ingot.

**Comment by EvgenijM86** [comment]
I crafted iron ingots with smeltery and they do not stack with iron ingots that I have found in chests. I think ingots that are found in chests have some data attached to them that prevents them from being usable for Ingot Cast.

And those iron ingots that are created with smeltery are usable for Ingot Cast.

**Comment by Dream-Master** [comment]
Pics please with ids. @EvgenijM86

**Comment by EvgenijM86** [comment]
They had the same id when I opened NEI window. I already smelted those buggy iron ingots. But I still have those two emeralds with the same id of 388 - they do not stack.

**Comment by EvgenijM86** [comment]
I just created a copper ingot in smeltery and it also does not stack with other copper ingots that I found in chests.
found in chest - https://ibb.co/gPnRBF
smelted in smelter - https://ibb.co/fF74yv

**Comment by Dream-Master** [comment]
try to using on both items /mt hand and post it here.

**Comment by EvgenijM86** [comment]
Bugged ingots:
<gregtech:gt.metaitem.01:11035>.withTag({})
Is in <ore:ingotCopper>
Is in <ore:ingotAnyCopper>

Normal ingots:
<gregtech:gt.metaitem.01:11035>
Is in <ore:ingotCopper>
Is in <ore:ingotAnyCopper>

**Comment by EvgenijM86** [comment]
And those bugged items cannot be used as TiCo modifier (redstone for example).

**Comment by Technus** [comment]
Can be fixed with name remover

related #1108

**Comment by Dream-Master** [comment]
this item with nbt tag found in the chest ?

I not add nbt tags to gt ingots or other stuff.
