### ISSUE TITLE
Alumentum(Thaumcraft)

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1273]
This item designed as some kind of "magic fuel". It have 6400 ticks burning time, - x4 more than coal. In "vanila" thaumcraft u need 1 coal and 3\3\3 potentia\chaos\ignis essentia( https://ftbwiki.org/Alumentum_(Thaumcraft_4) ) - so it takes 2+3 coal to get 2 alumentum. 5x1600(coal burning) and 6400x2(alumentum burning) - that makes alumentum a good fuel. At vanila thaumcraft.

In this pack alumentum craft needs 6\3\6 potentia\chaos\ignis essentia. That means 1 alumentum need 4 coal to craft itself - and it's useless as magic-alternative to coal. That's bad, in my opinion.
http://imgur.com/a/XWjOl
Please, add some boost to burning value of alumentum(up to 8000 for example) or reduse essentia costs(to 4\3\4 for example).

**Comment by Dream-Master** [comment]
Wich increase the burnvalue.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24581171/a0dc7c18-1716-11e7-9c26-40203ac1410c.png)

**Comment by Dream-Master** [comment]
12800 is the new Burnvalue . @Cinobi ok?

**Comment by Cinobi** [comment]
Looks cool!

**Comment by SirAzazel** [comment]
i feel its overpowered, make it 72k and it will be perfect
Default efficiency of alumentum is 125% (burntime of 4 coal while uses 3 coal to craft)
you made it 200% efficient

**Comment by Dream-Master** [comment]
no i think we let it at 125% so will change it to 8000.

**Comment by SirAzazel** [comment]
me and cin talked about it, so i agree on 125% too, so 8k vote it is from me too

**Comment by Dream-Master** [comment]
Nice
