### ISSUE TITLE
Voting for something to add an OpenFM mod

### ISSUE THREAD

**Issue by MajaProduction** [GTNewHorizons/NewHorizons#1274]
Who agrees, write: +
Who is against, write: -
Voting allowed to hold @Dream-Master

**Comment by MajaProduction** [comment]
+

**Comment by MajaProduction** [comment]
+

**Comment by Technus** [comment]
Was mentioned already, yet another mod that we could add but then no one would have real use for it, Since most just listen to their music, and we have Opencomputers Tape Drives that are also not used much.

**Comment by Bryfer** [comment]
if this is a vote, could we include some information about this OpenFM mod so everyone dosnt have to google it?

**Comment by MajaProduction** [comment]
Yes

**Comment by bigbass1997** [comment]
I am closing this issue. Does anyone ever search before posting duplicate issues?

#423 
#957 
And in #607 a vote was already held. 

Unless someone is going to provide a large number of people who want to use this, have some idea what they are going to use it for, and can actually give some detailed information about the mod, then we may **consider** adding it (that does not mean we actually will).
