### ISSUE TITLE
Thaumic Bases Bracelets

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1277]
All thaumic bases bracelets infusion requires charged thaumium caps from vanilla thaumcraft. Those are unable to obtain. They are not ore dicted yet. Please add the reciepes

**Comment by DietmarKracht** [comment]
Other Bracelets aren't craftable too. They all use the vanilla thaumcraft wand caps

**Comment by Dream-Master** [comment]
I know this and it will be in 1.5.0.0. I not nerf Thaumium Base now but this is the next mod i will do.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/939

**Comment by Dream-Master** [comment]
Will nerf the complete mod.
