### ISSUE TITLE
Suggestion: Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by SwardGames** [GTNewHorizons/NewHorizons#1278]
This cosmetic mod allows for armor to be worn "cosmetically", displaying instead of the actual armor worn in its respective slot, and allows for armor to be toggled off (hidden) if desired.

The cosmetic armor has no effect when worn, only being used for its model.

https://minecraft.curseforge.com/projects/cosmetic-armor-reworked

**Comment by Bryfer** [comment]
I'd love to have this mod so I can "wear" the gear I want instead of having an nano suit that looks boring all the time 

Im in love with the idea and hope that it can be included in an not so distant update :)

**Comment by Cinobi** [comment]
But... Gadomancy... Armor disguise research...

**Comment by Dream-Master** [comment]
I am not sure if this fits. There  are more slot added not sure if this interfere wit on of u mods adding slots.

**Comment by SwardGames** [comment]
I don't quite understand what you are saying, but if you have an issue with the slots interfering, they do not have an effect on gameplay. If you are worried that they might override slots used by other mods, I think forge handles that. Furthermore, this I have used this mod before with no issues, and even seen it in some other modpacks.

**Comment by Ghengis88** [comment]
I agree with Cinobi, this already exists in the modpack
https://ftbwiki.org/Armor_Disguise
