### ISSUE TITLE
Death with Charm of Keeping

### ISSUE THREAD

**Issue by SwardGames** [GTNewHorizons/NewHorizons#1279]
Whenever I die whilst I have a Charm of Keeping in my inventory, I get disconnected from the server. This then causes me to lose all the items in my inventory, as the Charm of Keeping will void everything if you disconnect before respawning and no grave will spawn as the Charm of Keeping activates (and if a grave spawned your stuff would duplicate).

Edit: Also, its probably worth mentioning that I think I was probably using my battlegear slots, as I died from fire damage caused by a mob I had just killed.

**Comment by Drobac** [comment]
Charms of keeping and graves dont mix well

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/489

**Comment by Dream-Master** [comment]
I guess we cant do here much.
