### ISSUE TITLE
Missing LuV+ Reciepes

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1280]
There are some machines that still have no crafting reciepes. For example the Fluid Extractor.
Also uncraftable are Chemical Bath/Reactor, Brewery, Canning Machine, Mixer, Disassembler.

Some of these machines are needed in LuV or higher tier. For example tungstensteel has a very slow Mixer reciepe as well as Yttrium-Barium-Cuprate

**Comment by Dream-Master** [comment]
@DietmarKracht any other machines we need?

**Comment by DietmarKracht** [comment]
Microwave
Slicing Machine
Fermenter
Fluid Canner
Fluid Extractor
Fluid Heater

**Comment by Dream-Master** [comment]
Need to check recipes
