### ISSUE TITLE
Failed adding Recipes on startup

### ISSUE THREAD

**Issue by TheRealHypo** [GTNewHorizons/NewHorizons#1283]
Got this while starting the server today:

https://pastebin.com/bUXPE3mG

**Comment by bigbass1997** [comment]
This has been occurring in logs for at least a few versions. Does this actually cause a problem for you or prevent the server from operating?

Just as a general note (not entirely specific to this issue), there are plenty of exceptions thrown during a server startup. Usually that is completely normal unless the exception is preventing operation of the server.

**Comment by bigbass1997** [comment]
No more information was ever provided, so closing the issue.
