### ISSUE TITLE
Fusion Reactor MK3

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1285]
The fusion reactor MK3 needs americium which should be craftable with MK2 reactor. Problem is that americium need 500m starting power. A MK2 reactor can only hold 16(Energy Hatch)x20m(Capacity)=320m starting power. So it is impossible to craft the MK3 version. Either lower the starting power for americium to something between 200m (original) and the maximum of MK2 reactor or raise the power added per energy hatch. Would be something like 16m for MK1 32m for MK2 and 48m for MK3

**Comment by Technus** [comment]
Not a bug.
