### ISSUE TITLE
Infinite Iron/Steel generation with railcraft tanks

### ISSUE THREAD

**Issue by Gemlord** [GTNewHorizons/NewHorizons#1286]
Railcraft tank blocks (iron and steel) and crafted in the assembling machine from 2 of their respective plates, but may be macerated or ARC furnaced for 20 nuggets, thus creating an infinite generation loop.

**Comment by Dream-Master** [comment]
yes you get two nuggets out but you are using power. Idk how to change it without. I dnt want to disable reverse recipes.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1212
