### ISSUE TITLE
Wooden Form (Brick) dupe

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#1287]
Crafting bricks with wooden form gives you extra forms.

**Comment by Dream-Master** [comment]
Can you explain it a bit more or/and add a screenshot please. @mulisz100

**Comment by mulisz100** [comment]
![dupe](https://cloud.githubusercontent.com/assets/27481104/25061863/a8924718-21bf-11e7-929b-6973312d9bab.jpg)

I crafted some unfired clay bricks with one wood form. It's not used in crafting recipe of course but because of this glitch i got one extra wooden form per one crafted brick. Like you get in return buckets while crafting something with fluid in them.

**Comment by Dream-Master** [comment]
@Namikon 
Did the not consume code in the core mod it ? Maybe we need to change it.

**Comment by bigbass1997** [comment]
This is certainly a weird issue. Some people have this issue, and some people report not having it. (same client version).

**Comment by Dream-Master** [comment]
But i fixed it crosswise
