### ISSUE TITLE
Villagers in Epsilon

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1288]
i have come across 4-5 villages in epsilon now and have found that no villagers are spawning, asked fellow server peeps and they say the same. So no villagers have spawned.

**Comment by Dream-Master** [comment]
@Namikon

**Comment by Namikon** [comment]
In progress of repopulating (Untouched) Villages with NPCs

**Comment by Namikon** [comment]
Villages are repopulated
