### ISSUE TITLE
Drawers+SFM dupe

### ISSUE THREAD

**Issue by LameGirlyCurly** [GTNewHorizons/NewHorizons#1289]
Using steves factory manager + compacting drawer: 

1. put one compactable dust into drawer, it will show 1 dust and 9 tiny dust
2. use SFM input on blacklist and output on blacklist and you get out 1 dust and 9 tiny

The drawer "shows" that it contains both the normal and tiny dusts at the same time.

_(yes it was requested by Dream that I post this here)._

**Comment by Technus** [comment]
@Dream-Master we could disable the compacting drawer, gt does what it can also with the packager.

**Comment by Dream-Master** [comment]
ok will look into it.

**Comment by Technus** [comment]
I also asked nami what we can do

**Comment by Dream-Master** [comment]
ok.

**Comment by Namikon** [comment]
For now I'd disable the Compacting drawer, as a Quick solution.
Might be a good idea to report this to both Mods? If they happen to be still active..

**Comment by Dream-Master** [comment]
Steves factory manager stoped developping. Storage drawer dev is working on mc 1.10 and 1.11 versions and not fixing old bugs ike this.

**Comment by Dream-Master** [comment]
https://github.com/jaquadro/StorageDrawers/issues/434
