### ISSUE TITLE
[SP] Electric Air filter, instructions out of date or structure broken

### ISSUE THREAD

**Issue by Adz-Scott** [GTNewHorizons/NewHorizons#1293]
The electric air filter multiblock still says "incomplete structure", despite being assembled according to the instructions presented:

Pic of structure: 

XXX
XXX            
XXX

V M V     
M    M     
V M V

V M V
M    M
V M V

X  I   X
Y   X   O                      
X  C   E                                       
                                          
                                          
                                 
![ss](https://cloud.githubusercontent.com/assets/27580056/25066589/11a00512-2222-11e7-9db8-2be345748da4.png)

*Pic shoes no mufflers, but I tried any combination of 0-8.. same result with all.

E = energy hatch (MV)
C = Controller
Y = Maintenance hatch
O = Output bus (MV)
I = input bus (MV)
X = Air filter Turbine casing
M = muffler Hatch (MV)
V = Air filter vent casing

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Technus** [comment]
Well it needs more air around.

**Comment by Adz-Scott** [comment]
The multiblock was open at all sides.. does it need a certain number of empty blocks around it or something?

**Comment by Technus** [comment]
Why don't you try it instead of writing here, that should take less time.

Might or might not need up to 3 block radii of air where needed (**not giving exact information here**).
