### ISSUE TITLE
Steam Jetpack

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1295]
![2017-04-15_21 19 20](https://cloud.githubusercontent.com/assets/26042867/25067957/426a05a4-2221-11e7-9d29-2ab2749dff18.png)

Something wrong here.. The item is still in game but somehow I don't think it can be used to complete this quest anymore.

**Comment by Dream-Master** [comment]
Did you hit after the update /bq_admin default load?

**Comment by kris449** [comment]
Oops I forget >.> sorry

**Comment by Dream-Master** [comment]
np
