### ISSUE TITLE
Issue with [cables from Industrialcraft]/Multiplayer

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1296]
Hi everyone
~I do not know if it is an Issue but in NEI there are missing the IC2 cables, while in creative mode they are available. Without the IC2 cables it makes the IC2 machines useless?~ [Closed]
Im on the latest official modpack version 1.4.1.0

Oh and My Friend and I are having problems playing this pack. If he joins the server (private) he gets "timeouted" randomly

Here is the latest server log:

[fml-server-latest-log.zip](https://github.com/GTNewHorizons/NewHorizons/files/924231/fml-server-latest-log.zip)

His ingame name is Marvin and i think the error is:

[Netty IO #3/ERROR] [FML/]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException

but im not sure what to do about it

I hope sombody can help me
Thanks in Advance
Radst0ne

Edit: here is the log from the client (if needed)
[latest-log-client-side.zip](https://github.com/GTNewHorizons/NewHorizons/files/924351/latest-log-client-side.zip)

Edit 2: non modded Minecraft works perfectly fine.

**Comment by Adz-Scott** [comment]
Do gregtech cables not attach to IC2 machines?

**Comment by Radst0ne** [comment]
Ahh stupid me only the generator stuff from IC2 do not connect to gregtech cables 
thank you very much

**Comment by Adz-Scott** [comment]
No worries! :) Remember to close the issue if you get a moment.

**Comment by Radst0ne** [comment]
And the multiplayer error? :o

**Comment by Dream-Master** [comment]
will look into it after the update.

**Comment by Dream-Master** [comment]
@Radst0ne the fml log say nothing about a crash.

**Comment by Dream-Master** [comment]
Timeouts happend if the user have a low internet connetction or the ping is to high.

**Comment by Radst0ne** [comment]
okay... thanks!

**Comment by Dream-Master** [comment]
@Radst0ne can this be closed?

**Comment by Radst0ne** [comment]
@Dream-Master yeah can be closed we changed the vpn tunneling software, weird though it works with every other game fine, but now it works like a charm. Thanks again 👍 .
Now my Friend experience a weird Graphic glitch (premium acc.) with the Quest Book but I'll create another Issue

**Comment by Radst0ne** [comment]
@Dream-Master I think the JourneyMap was causing the disconnect/error. I updatet the version (5.1.4p2 since 5.1.1 the jar is the same for server and client) of the Server and client to the latest and now it works. Even can see nearby monsters and players

**Comment by Dream-Master** [comment]
@Radst0ne Journeymap update ? Ok will look at it.

**Comment by Dream-Master** [comment]
Oh sorry forgot it. Will add newest version in 1.5.0.8
