### ISSUE TITLE
Suggestion - GTech boilers as a multiblock goal quest

### ISSUE THREAD

**Issue by Adz-Scott** [GTNewHorizons/NewHorizons#1297]
Title is pretty self explanatory.

It just seems a little odd that the multi-block goals jump straight from the bronze blast furnace to the electric furnace, without addressing the huge amounts of power needed to power the latter.

The player has access to steel at this point, so it makes sense that the iron and steel boilers would be a logical link between the two.

Thanks!
(Great pack by the way)

**Comment by Dream-Master** [comment]
Gt Boilers are added to the Multiblocks at Quest in 1.4.1.0. It need good circuits so available in mid engame lv.

**Comment by Dream-Master** [comment]
@Adz-Scott did you see the new Quests?

**Comment by Adz-Scott** [comment]
No sign of it.. I've not unlocked HV yet, Im only mid way through MV. Will it appear later?

**Comment by Dream-Master** [comment]
After Good Circuit Quests in LV you can make the Bronze GT Boiler.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/25092914/3203042a-2390-11e7-9534-f25f7c9f7362.png)
![image](https://cloud.githubusercontent.com/assets/2970688/25092920/36b57156-2390-11e7-9b67-d67c53705f83.png)
![image](https://cloud.githubusercontent.com/assets/2970688/25092930/45ae6f46-2390-11e7-9174-eef6253cca55.png)

**Comment by Adz-Scott** [comment]
Ah! I assumed it would be unlockable prior to this. I'll close the issue, thanks!

**Comment by Dream-Master** [comment]
Yes it need before make an Arc Furnace first. I remove this dependencies. Now you need to do Good Circuits Quest then the Bronze Boiler is open.
