### ISSUE TITLE
Craft Unfired Seared Brick returns additional Wooden Form (Brick)

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#1298]
Craft "Unfired Seared Brick" on "Crafting Table" and "Crafting Station" returns additional "Wooden Form (Brick)"

**Comment by Dream-Master** [comment]
yes we know this issue. Have change some recipes.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1287
