### ISSUE TITLE
Ceres Dungeon Chest not generating loot

### ISSUE THREAD

**Issue by LunarPhoenix** [GTNewHorizons/NewHorizons#1300]
I play singleplayer. 
I updated to 1.4.10 before visiting Ceres for the first time. I found a dungeon, went through it, killed the blazeboss, and when I opened the dungeon chest with the T4 key it was completely empty. 

I also tried making a brand new world and going to Ceres (with creative), and both dungeon chests I found were completely empty.

**Comment by LunarPhoenix** [comment]
Update, Just killed a blaze boss on the creative world in survival mode with a longsword (oh so very slowly) and it generated loot in it's dungeon chest. Not entirely sure what's going on at this point.

**Comment by Namikon** [comment]
Also did open a new world and jumped to Ceres; Killed the Blaze Boss, and got loot.
So it's either a derp in your worldgen, or a bug in GalaxySpace that somehow prevents loot from spawning. 
A rough guess is that if you kill him with a bow, the killing Entity may not be detected correctly.
But as this mod is not open source, there is nothing we can do, sadly.
