### ISSUE TITLE
Chisel causes crash

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1301]
If i try to use chisel on a block while my inventory is full the game crashes, Dont know if there is anything to be done abouth it tho. just thought i should menthion it

**Comment by Ghengis88** [comment]
to specify, i were trying to chisel a block in my inventory.

**Comment by Dream-Master** [comment]
Crashlog and Block you chisel would be nice. And fml log. @Ghengis88

**Comment by Ghengis88** [comment]
[crash-2017-04-16_23.12.28-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/924591/crash-2017-04-16_23.12.28-client.txt)
[crash-2017-04-16_23.22.59-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/924592/crash-2017-04-16_23.22.59-client.txt)

**Comment by Ghengis88** [comment]
concrete 983 to tonccret 983:10

**Comment by Ghengis88** [comment]
there were also concrete laying on the ground that i were trying to pick up,

**Comment by Dream-Master** [comment]
@Ghengis88 did you try it with a empty inventory or a few slots are empty?

**Comment by Ghengis88** [comment]
if i had atleast 1 inventoryslot open i gould play on as usual

**Comment by Ghengis88** [comment]
hotbar were full tho

**Comment by Dream-Master** [comment]
Ok this happen some time ago with nei to if you try to get more items in your inventory the slots. Not sure how and if there is a fix.
@Namikon, @Technus  any idea?

**Comment by Ghengis88** [comment]
can't send fml log, says it is the wrong file type

**Comment by Dream-Master** [comment]
use gist.

**Comment by Namikon** [comment]
Seems _itemstack1_ is not null-checked in Chisel:
https://github.com/Chisel-Team/Chisel/blob/1.7/release/src/main/java/team/chisel/inventory/ContainerChisel.java#L108
And also not in CoFHLib:
https://github.com/CoFH/CoFHLib/blob/1.7.10/src/main/java/cofh/lib/util/helpers/InventoryHelper.java#L315

Not our fault, nothing we can do. Must be reported to either Chisel or CoFH Lib. Better report it to both as the Lib is reused in a ton of mods

**Comment by Dream-Master** [comment]
@Ghengis88 can you report it please. Thanks

**Comment by Dream-Master** [comment]
@Ghengis88 is this reported?. Can you post the issue links here please.

**Comment by Dream-Master** [comment]
After no on report it i did.
https://github.com/Chisel-Team/Chisel/issues/417

**Comment by Ghengis88** [comment]
Sorry, forgot to check back and then went on vacation

**Comment by Dream-Master** [comment]
@richardhendricks
