### ISSUE TITLE
Quests does not accept the not stone based ore.

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1303]
Quests does not accept the not stone based ore.
Example: copper ore from nether or with red cobble or and so on.

**Comment by Dream-Master** [comment]
sure go and find some Overworld Ores. This Quests are desingt that you cant go to the Nether at this stage.

**Comment by hhheeexxx** [comment]
I have heard many times from people "I have copper (or other ore) but it in black granite/ red granite/marble/basalt and I can't complite quest."  "Let's change granite ore to base ore / let us hold ore for complite quest/"
Today I heard that for the twentieth time and decided to write issue.
I understand that you and so have enough work, but suddenly you want to fix it.

**Comment by hhheeexxx** [comment]
I think I can suggest corrections myself.

**Comment by Dream-Master** [comment]
Its not possible to fix because you can find Owerworld Ores or Nether Ores or other Type Ores. The problem with Quests is i cant say find this or this ore. If i add ores you need to fnd them all. Adding every type of possible Ores to the Quest book will be impossible. If you like to have this feature please ask the Mod Author from Better Questing Mod to add it. @hhheeexxx

**Comment by hhheeexxx** [comment]
I see in .json
those strings:
      "logic": "AND",
      "taskLogic": "AND",
my be possible use 
"OR" and try write all 7 ores

I think I'll try to fix 1 quest

**Comment by hhheeexxx** [comment]
i see quest #28 has bug on current version

**Comment by hhheeexxx** [comment]
I try "taskLogic": "OR", and it's work.
But there'is need to do 1 quest for 1 type of ore.
Like a: "find copper ore". And 7 options with OR logic.
Not for 4 ores in one quest. Need 4 quests.
I can fix quests with ores, but i don't know how get new ID, and how goodly place it on quest map.

**Comment by Dream-Master** [comment]
Quest 28 is a with a checkbox. What can be wrong here?

**Comment by Dream-Master** [comment]
If y Quest be  an and , ore, xor etc task you need to make two and more of the same Quest. This not gone be happend. So go find some Overworld Copper or better not using the Quest Book at all. @hhheeexxx

**Comment by Dream-Master** [comment]
@hhheeexxx if you have doable suggestion or changes you can open up issues all the time or make pull requests i can merge.

**Comment by hhheeexxx** [comment]
What new ID for new quests I can use? Have you a numeric system for them? Or get first unused? I try do pull request.

**Comment by hhheeexxx** [comment]
https://github.com/GTNewHorizons/NewHorizons/pull/1307

Test case. Maybe it makes sense to add an initial info quest "find a vein" and add a final quest with a gift. Total 6 quests instead of 1.

I need feedback about what you think.

**Comment by Dream-Master** [comment]
I will change the Early Game Quests (Tin/Copper/Iron) to ingots and make the Ores optional. Thats it no more changing.

**Comment by hhheeexxx** [comment]
So there is no troble anymore.
