### ISSUE TITLE
Wood-ID Bug on latest Version 1.4.1.1

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1304]
![2017-04-17_20 47 15](https://cloud.githubusercontent.com/assets/27621272/25100210/7dbf6bfa-23af-11e7-805e-334ff36b12d9.png)
![2017-04-17_20 47 26](https://cloud.githubusercontent.com/assets/27621272/25100217/80ea05e2-23af-11e7-805f-f9b624f63092.png)
Both same Wood Type (Spruce), different directions

![2017-04-17_20 48 17](https://cloud.githubusercontent.com/assets/27621272/25100222/8451753a-23af-11e7-9691-2d4b67e4e2cb.png)
A Fence crafted with Spruce Wood -> Wood Slab Name and ID, but still a Fence (Spruce)
Pictures should be Self explanatory

Greetings from Germany
Radst0ne

**Comment by Radst0ne** [comment]
This seems to happen for all Wood Blocks and generated Trees

**Comment by Dream-Master** [comment]
@Radst0ne Eine Idee warum das so sein könnte (Change log)? Ich kann mir nicht erklären warum das erst in 1.4.1.1 aufgetaucht ist. Bis du dir sicher das dass nicht schon länger der Fall ist?

**Comment by Dream-Master** [comment]
This seems to be a Waila bug that wood that lays on the ground be renamed to oak wood. If you harvest it you got back the Block you place. Wood slabes is a localizer Bug. Binnies Mod are now open source maybe post it there @Radst0ne

**Comment by Dream-Master** [comment]
https://github.com/ForestryMC/Binnie/issues

**Comment by Radst0ne** [comment]
Nein ich bin mir da leider nicht sicher, weil ich das Pack (welches richtig gut gelungen ist, tolles quest system etc.) erst seit kurzem spiele. Auffällig ist, das es bei den meisten "künstlich" generierten Objekten/Bäumen, welche nicht Nachwachsen bzw. wozu es keine Setzlinge gibt, auftritt

**Comment by Dream-Master** [comment]
Ok ist aber nur ein Anzeige Bug. Also keine sorge. Genau wie die slabs die eigentlich Zäune sein sollten.

**Comment by Radst0ne** [comment]
Das mit dem Zaun scheint glaub ich kein Anzeige Bug zu sein da ich mit dem kein Bett craften konnte, ich hatte die ID mal in NEI nachgeschlagen und dort wurde mir zwar das richtige Rezept für eine Zaun angezeigt aber wiederum ein anderes Item

**Comment by Radst0ne** [comment]
Bug Reported

**Comment by Dream-Master** [comment]
https://github.com/ForestryMC/Binnie/issues/12

**Comment by Radst0ne** [comment]
I think I got the fence problem fixed. I'll upload the modified script file tomorrow

**Comment by Radst0ne** [comment]
okay it does not worked as planned. It's a bit complicated so I'll write it in German
Das Problem mit den aktuellen Zäunen aka Wood Slab ist, sie lassen sich nicht umbennen (mithilfe von Modtweaker) bzw. in eine Ore Dictionary Group verschieben da dann das Rezept urplötzlich einen normalen Minecraft Zaun ergibt. Eine Lösung wäre eine Mod Namens Wood Stuff hinzuzufügen, welche mit den Mods Biomes O Plenty, Natura etc zusammenarbeitet und Zäune Bücherregale Knöpfe Zauntore etc in allen möglichen Holzarten darstellt (darunter auch jungle fichte etc.). Um die ganzen Zäune vereinfacht in die bisherigen craftingrezepte hinzuzufügen müsste man einfach nur die ExtraTrees Zäune in die selbe Kategorie ore:fenceWood zuordnen und dann die jeweiligen crafting Rezepte anpassen.
Ich weiß nur nicht ob sich der Aufwand wirklich lohnt, da viele Rezepte von Wood Stuff geändert werden müssten, wie z.B. Werkbank Rezepte und es doch ein eher kleinerer Fehler ist, der einzige Vorteil wäre eine größere Vielfalt.
Eine weitere Idee wäre, man fügt ein weiteres Rezept hinzu sodass man die "Wood Slab" zu einem normalen Vanilla Minecraft Zaun umgewandeln kann, oder man fügt zu allen Rezepten, welche Zäune brauchen, die "Wood Slab" hinzu, mir würde einfallen Bett, Rucksäcke etc. (bei manchen Rezepten ist es schon enthalten bei manchen nicht.)

**Comment by Dream-Master** [comment]
Ok will see what i can do here.

**Comment by thejester10276** [comment]
I'm having the exact same issue, very annoying.

**Comment by Radst0ne** [comment]
@thejester10276 a little workaround is to remove the recipe, but then you just get only the oak fence instead of spruce etc.

**Comment by Dream-Master** [comment]
Needs to test the last Binnies Mod version if still exists.

**Comment by Dream-Master** [comment]
It is a Wila bug (with the laying wood log) so nothing I can do here.
The fences i will check.

**Comment by Dream-Master** [comment]
https://github.com/ForestryMC/Binnie/issues/78

**Comment by Dream-Master** [comment]
Not fixable or someone rewrites waila.
