### ISSUE TITLE
Spatial Distortions

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1305]
![enderpearls](https://cloud.githubusercontent.com/assets/26042867/25103394/66f3394e-238a-11e7-9b91-d08580238457.png)

Why :(

**Comment by Technus** [comment]
To induce pain.

**Comment by kris449** [comment]
It was very successful.

**Comment by Dream-Master** [comment]
Should i change it to not consume ?

**Comment by kris449** [comment]
Yes please, I worked hard for those ender pearls.

**Comment by Bryfer** [comment]
as I understand this quest you consume these ender pearls during the "research"

**Comment by Dream-Master** [comment]
yes and you get a tier 3 lootbag for it. And enderpearls are give only one h in the Chunkloader.

**Comment by kris449** [comment]
It's up to Dream, was just one of those quests that I questioned if it was actually meant to consume.  Since ender pearls aren't exactly the easiest thing to get.

**Comment by Dream-Master** [comment]
@kris449 what is easy in the pack. I could reduce it to 8 Pearls if that helps.

**Comment by kris449** [comment]
Sure that's fine.

**Comment by Namikon** [comment]
16 Pearls? I remember having setups where I produced 16 pearls each Minute, and I was far from Endgame.. But Ok..?

**Comment by Dream-Master** [comment]
I can chenge it back to 16. A Tier 3 Lootback have MV Loot.

**Comment by Jayjayx5x1** [comment]
i suggest a bump up to 32 (cause a tier 3 lootbag is mv loot) and its not exactly hard to find an enderman spawner in a roguelike dungeon and then farm it.

**Comment by Dream-Master** [comment]
Yes why not @Jayjayx5x1
