### ISSUE TITLE
Astro Miner schematics cannot be crafted.

### ISSUE THREAD

**Issue by Giovanni-NL** [GTNewHorizons/NewHorizons#1308]
According to NEI you can craft the NASA Workbench Schematic for the Astro Miner (item 5760:2) by placing a NASA Workbench Schematic for a Tier 3 Rocket (item 5760) in the second slot of a crafting bench.  That does not work.  What you do get is a NASA Workbench Schematic for an Automatic Cargo Rocket (item 5760:1)   This happens on all kinds of crafting grids, and for each of the 9 slots.  

The correct way would be to get the automatic cargo rocket schematics when you place the tier 3 rocket in the first slot of the crafting grid, or to get the astro miner schematics when you place it in the second slot of a crafting grid.

**Comment by Dream-Master** [comment]
Fixed.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/3105fea88df9f53ae374f9ce0cbbc20ba394bdbd
