### ISSUE TITLE
Smeltry multiblock quest

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1310]
https://cdn.discordapp.com/attachments/274279470117158913/304167461073453056/unknown.png
https://cdn.discordapp.com/attachments/274279470117158913/304167522217754625/unknown.png

27 seared brick req, however you can only CRAFT (in bold because important) 28 or 26 however you can make 27 if one uses the compressor, my suggestion is to make it retrieval so that nothing else has to be changed (even if the get the from a village they would still be required to craft the 162 seared bricks and the rest of the items in the quest)

**Comment by Dream-Master** [comment]
At this stage crafting Quests make sense because you can loot Villages and get reward for steeling Blocks. I chan change the Amount to28 if this help. @Jayjayx5x1

**Comment by Jayjayx5x1** [comment]
sure, but you might also want to change the amount of sand gravel and clay, and seared bricks to match it (that was the main issue for me).

**Comment by Dream-Master** [comment]
will do.
