### ISSUE TITLE
natura and the pile igniter

### ISSUE THREAD

**Issue by michaelcousins01** [GTNewHorizons/NewHorizons#1312]
it isnt accepting the natura redwood and im thinking thats a bug havnt tried any other wood thou tyvm

**Comment by Dream-Master** [comment]
yes known issue because they registered the wood logs different then other mods i guess.

**Comment by Dream-Master** [comment]
@Technus any idea how to registered Natura logs to Ordict with Gt code possibly?

**Comment by Dream-Master** [comment]
I try to ordict the logs with the core mod maybe this will work.

**Comment by Dream-Master** [comment]
ok Natura works.

**Comment by Dream-Master** [comment]
Twilight, Thaumcraft, Extra Trees not working.

**Comment by Dream-Master** [comment]
works now. @Technus thanks.
