### ISSUE TITLE
Silicon Dioxide dust reciept view in NEI crash client.

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1315]
I try see on of reciept and get crash twice.

https://pastebin.com/0LXxUxN9

**Comment by hhheeexxx** [comment]
I think one of Centrifuge reciept.

**Comment by Dream-Master** [comment]
Can you send me a pic from this recipe? @hhheeexxx

**Comment by hhheeexxx** [comment]
no i can't: this pics do crash

**Comment by hhheeexxx** [comment]
In centrifuge I get 8 recieps. I list from 1st and so on and get crash. Try it yourself @Dream-Master. I think this is reciept from europa surface dust or block centrifuge to silicone dioxede.

**Comment by bigbass1997** [comment]
I remember Sward reporting this error earlier as well. Nearly identical crash report https://pastebin.com/raw/R1DS1XmA

It appears that something from GalaxySpace does not like being rendered.

**Comment by TheRealHypo** [comment]
Got the Error too just this moment. Happened while seeing recipes for Silicon Dioxide Dust, and then go to page 3 or 4 at Pulverizer Recipes.

https://pastebin.com/H9MV94Y7

**Comment by Technus** [comment]
Yeah probably the GS devs changed the block meta id's or dream screwd the recipe

**Comment by Dream-Master** [comment]
Will fix it if I found the missmatching id

**Comment by Dream-Master** [comment]
Need 1.3.44 cormod for it.
