### ISSUE TITLE
[suggestion] Replace tinker cobalt and ardite ore.

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1317]
I think good idia remove tinkers generation of ores in nether.
And add ardite greg ore vein with something ores in nether.
Cobaltite ore already spawns in TF.

**Comment by bigbass1997** [comment]
@Dream-Master Do not listen to anything hhheeexxx says. He has been caught duplicating items. He has no point of reference for anything in the modpack, therefore everything he says or suggests should be ignored.

**Comment by bigbass1997** [comment]
Woops clicked wrong button.

Anyways, I see no issue here, there is no gregtech ore for TiC stuff.

**Comment by Dream-Master** [comment]
I added ardite to GT so this is possible but i am not sure why i have to replace it?
 @hhheeexxx

**Comment by hhheeexxx** [comment]
I about disable tinker ore generation in TiC config. And add Ardite ore in Greg worldgen. And Instead of point TiC ores will be Greg veins. Ardite in nether, Cobalt it Twilight Forest. Anyway you disable TiC Cobalt and Ardite smelt in TiC furnance. Need to use Greg to get cobalt and ardite before i can do pickaxe from it.

**Comment by hhheeexxx** [comment]
It seems to me that this will be more systematic in terms of ore generation. And more difficult to search. @Dream-Master

**Comment by Dream-Master** [comment]
Ok will look into it tomorrow.

**Comment by Dream-Master** [comment]
For make Ardite super hard (mining level) i need to set the level to 7-8 in Gregtech code. Personal i like how this Ore is generated in the Nether. What the other think about ?
@bigbass1997 @Namikon @Technus @Drobac 
@bigbass1997 Ardite Ore exist in Gt because i add it some versions before.

**Comment by Dream-Master** [comment]
No i dont change it.
