### ISSUE TITLE
Whispy Dreamcatcher research disconnect client.

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1318]
If in Thaumicon press Whispy Dreamcatcher from Thaumic Exploration for get research note, then server print exeption and client is disconnected.

https://pastebin.com/8VFP72DF

**Comment by Dream-Master** [comment]
@hhheeexxx is this a witchery mod item?

**Comment by hhheeexxx** [comment]
Thaumic Exploration mod
There is some problem with 5 another things in that mod. 
Another way to check: if you use command or cheat thaumicon to open all researches, then there is 5 things in Thaumic Esoterica tab still not opened. If you click on one of them you will be disconnected.

**Comment by Dream-Master** [comment]
@hhheeexxx have to look into it maybe my scripts derp here.
Can you list all the items thats need to be checked?

**Comment by hhheeexxx** [comment]
![img_24042017_173836_0](https://cloud.githubusercontent.com/assets/7855510/25342670/61c76702-2915-11e7-9007-c811ba2b7c3d.png)
![img_24042017_173855_0](https://cloud.githubusercontent.com/assets/7855510/25342674/61ebde2a-2915-11e7-8dfa-b6bdb06b25f8.png)
![img_24042017_173919_0](https://cloud.githubusercontent.com/assets/7855510/25342671/61c995e0-2915-11e7-889b-6c1487bbd6bf.png)
![img_24042017_173933_0](https://cloud.githubusercontent.com/assets/7855510/25342673/61cc3c78-2915-11e7-938a-4735759d5b0d.png)
![img_24042017_173957_0](https://cloud.githubusercontent.com/assets/7855510/25342672/61ca6a56-2915-11e7-8236-47cad613511f.png)

**Comment by hhheeexxx** [comment]
@Dream-Master I wrote PM direct to your e-mail, and i know to want: are you catch them?

**Comment by Dream-Master** [comment]
@hhheeexxx 
can you test this file please and report back if all erros are gone
https://www.dropbox.com/s/7kd9jby8d2sgdwb/Thaumic-Exploration-01.zs?dl=0
thanks.

**Comment by hhheeexxx** [comment]
I got test.
install on server:
there is no necro staff core now:

![mag](https://cloud.githubusercontent.com/assets/7855510/25357581/057be69e-2947-11e7-8f55-6b7c44e78549.png)

but in local game all things are opened well.

**Comment by Dream-Master** [comment]
so all things except nekro stuff works ?

**Comment by hhheeexxx** [comment]
no some problem - user disconnect and exeption on server

**Comment by Dream-Master** [comment]
thsi not helps me a bit more specific.
Did you are change the script on the server and client?
Which items work which not.
Only mp or sp too?

**Comment by hhheeexxx** [comment]
1) i change script on serv and on client
2) looks like one changes - no more nekr staff
3) i create copy of server and delete all scripts and run
4) use cheat book and get all things normal
pictures in next post

**Comment by hhheeexxx** [comment]
without scripts on server side:
![2](https://cloud.githubusercontent.com/assets/7855510/25359574/606941b2-294e-11e7-8e18-31233c4f185a.png)
![1](https://cloud.githubusercontent.com/assets/7855510/25359578/61d15594-294e-11e7-9d14-eea7fff1fec0.png)
![4](https://cloud.githubusercontent.com/assets/7855510/25359582/6521b9b4-294e-11e7-9577-616fd6a10d02.png)
![3](https://cloud.githubusercontent.com/assets/7855510/25359583/675c1a62-294e-11e7-8924-9a6021372ee5.png)

your test script on server and client:
![x2](https://cloud.githubusercontent.com/assets/7855510/25359703/d6b85308-294e-11e7-9621-f352af8fb3f1.png)
![x1](https://cloud.githubusercontent.com/assets/7855510/25359706/d9ef98ba-294e-11e7-9d30-8f0767221c33.png)
![x4](https://cloud.githubusercontent.com/assets/7855510/25359710/ddfbb2e0-294e-11e7-9511-066a675c80b7.png)
![x3](https://cloud.githubusercontent.com/assets/7855510/25359713/e03fcc58-294e-11e7-94a0-c92a7ac7472f.png)

dark items is not known yet and if pressed do disconnect

**Comment by Dream-Master** [comment]
ok so there are more bugs maybe.

**Comment by Dream-Master** [comment]
try this file please

https://www.dropbox.com/s/7kd9jby8d2sgdwb/Thaumic-Exploration-01.zs?dl=0

**Comment by hhheeexxx** [comment]
seems nothing changes:
![screenshot_1](https://cloud.githubusercontent.com/assets/7855510/25372539/844217ee-299e-11e7-8a4a-4a69e5158212.png)

**Comment by Dream-Master** [comment]
same crashes then before?

**Comment by hhheeexxx** [comment]
this crash:
https://pastebin.com/qwrESW6T

**Comment by Dream-Master** [comment]
@hhheeexxx can you test it again. Get the newest file from github 1.5.0.0 branch.
