### ISSUE TITLE
Potential Quest Requirement Mixup

### ISSUE THREAD

**Issue by Valdevon** [GTNewHorizons/NewHorizons#1319]
There are two quests with very similar names in the quest book. The final Novice Thaumcraft quest called "This is the End..." 
![image](https://cloud.githubusercontent.com/assets/9509239/25317976/7a7edaa0-2852-11e7-8bad-068876024423.png)
And the Tier 3 Rocket quest called "This is the End...?"
![image](https://cloud.githubusercontent.com/assets/9509239/25317979/959c2cd4-2852-11e7-959b-fc6e15e9bea2.png)

This Thaumcraft quest chain is gated behind the asteroids quest, but I think it might be a mistake and intended to be gated behind the Thaumcraft "This is the End..." quest.
![image](https://cloud.githubusercontent.com/assets/9509239/25317985/c1437644-2852-11e7-961d-35ea4cf915d8.png)

I've already crafted some void metal, and looking ahead in the quests it doesn't look like anything will require materials from the Asteroid Belt

**Comment by Dream-Master** [comment]
Yes i guess it is  a mistake. Will change it.
