### ISSUE TITLE
Thaumic Bees Block Requirements

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/NewHorizons#1321]
Anything from the magic bees line that requires a block under an Alveary will not breed. Extra bees works as intended though. Tried about 50 times and no mutations from two different bees on that line

**Comment by Dream-Master** [comment]
Can you give me some example?

**Comment by ko5h** [comment]
I deduced coal bee at 9% chance ... ~ 250+ cycles...try to apiary, if at all possible in your circumstances

**Comment by Dream-Master** [comment]
@Hakameda @ko5h please this with this file

**Comment by ko5h** [comment]
to apiary this (Block B:minecraft:"coal_block" and Block B:minecraft:coal_block) work... got coal gen ~25+ cycles
to alveary (Block B:minecraft:"coal_block" and Block B:minecraft:coal_block) does not work... ~50+ cycles 0 coal gen

landfill for tests http://i.imgur.com/EBi4p1P.jpg

**Comment by Dream-Master** [comment]
@ko5h 

So does it work with the new cfg file the same or different then with the old file?

**Comment by Drobac** [comment]
Did you try using a chisel to switch the blocks to another type?

**Comment by Hakameda** [comment]
Not working for me in single player

Sent from my Kata

 Drobac <notifications@github.com> wrote:



Did you try using a chisel to switch the blocks to another type?

**Comment by Hakameda** [comment]
Ive tried it with other bees on the same line of bees. None of the block requirements seem to work with alvearies

**Comment by Dream-Master** [comment]
Can you test it in the new version (after the release)?

**Comment by Hakameda** [comment]
I can, I play on a server though so it might take a bit

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



Can you test it in the new version (after the release)?

**Comment by Hakameda** [comment]
Is the fix just a config change?

**Comment by Dream-Master** [comment]
Yes

**Comment by Hakameda** [comment]
Can you link a copy, I'll see if it can be added to server


Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



Yes

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/1.5.0.0/config/gendustry/bees.cfg

**Comment by LameGirlyCurly** [comment]
I added that to our server, Hakameda can comment here in few hours how it worked if it worked.

**Comment by Hakameda** [comment]
Fix did not work for this

**Comment by Dream-Master** [comment]
@Hakameda can you list all mutations that not works. Are they all from Gendustry or added by cfg file?

**Comment by Hakameda** [comment]
Seemingly none of the custom bees added for NH work. I can't test more til I'm home. They work with apiary, just not alveary. The other mods with block requirements work like normal

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



@Hakameda<https://github.com/hakameda> can you list all mutations that not works. Are they all from Gendustry or added by cfg file?

**Comment by Dream-Master** [comment]
So in short: all Gendustry cfg added Bees can only breed in the Apiary not in the Alvery ?

**Comment by Hakameda** [comment]
Only bees that require a block under alveary. The ones that don't work fine

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



So in short: all Gendustry cfg added Bees can only breed in the Apiary not in the Alvery ?

**Comment by Dream-Master** [comment]
so bees without a block req.  works fine(gendustry bees cfg bees)

**Comment by Hakameda** [comment]
Looks like, can test more when I'm home

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



so bees without a block req. works fine(gendustry bees cfg bees)

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
@Hakameda any news?

**Comment by Dream-Master** [comment]
I set this issue to 1.6.0.0 because i will put bees into gt code.

**Comment by Hakameda** [comment]
None of them work, tried a bunch. Is there some kind of temp fix until 1.6? Since the 1.6 update will be awhile

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



I set this issue to 1.6.0.0 because i will put bees into gt code.

**Comment by Dream-Master** [comment]
I dont know what cause this problem. Is it the cfg file? Did it work in code ? I cant temp fix it if i dont know what i have to fix.

**Comment by Hakameda** [comment]
It's possible it's a gendustry problem, I believe extra bees had that issue for awhile and it was fixed. Might be able to find how they did it

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



I set this issue to 1.6.0.0 because i will put bees into gt code.

**Comment by Dream-Master** [comment]
no extra bees are closed source before now its open source but the old code i thinke we cant check.

**Comment by Hakameda** [comment]
Well, they work in apiaries. So it can't be the config

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



I dont know what cause this problem. Is it the cfg file? Did it work in code ? I cant temp fix it if i dont know what i have to fix.

**Comment by Dream-Master** [comment]
ok so i need to add it to gt code. Cost me a while to understand how it works. So sorry have to wait until 1.5.x.x or 1.6.x.x.

**Comment by Hakameda** [comment]
They mentioned how it was fixed on the reported issue, something about extending the check to under block.alveary instead of just block.apiary or something

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



ok so i need to add it to gt code. Cost me a while to understand how it works. So sorry have to wait until 1.5.x.x or 1.6.x.x.

**Comment by Hakameda** [comment]
Can mutation chance be upped until a proper fix is in? 1% on the bees for getting gendustry is insane. Soul frames are multiple, even one 1% bees it's super slow

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



ok so i need to add it to gt code. Cost me a while to understand how it works. So sorry have to wait until 1.5.x.x or 1.6.x.x.

**Comment by Hakameda** [comment]
Actually could you make it so bees require Space biomes, titanium on moon biome etc, a simple work around until a proper fix is in. That way progression isn't broken

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



ok so i need to add it to gt code. Cost me a while to understand how it works. So sorry have to wait until 1.5.x.x or 1.6.x.x.

**Comment by Dream-Master** [comment]
No. We have so many duct tape fixes. I will add it to gt code after the update 1.5.0.0

**Comment by Dream-Master** [comment]
What you could try is to remove bees cfg from gendustry and switch on gt bees. Only for testing if the gt bees works. (Try in sp) @Hakameda

**Comment by Hakameda** [comment]
I'll look tomorrow after work

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



What you could try is to remove bees cfg from gendustry and switch on gt bees. Only for testing if the gt bees works. (Try in sp) @Hakameda<https://github.com/hakameda>

**Comment by Dream-Master** [comment]
k

**Comment by Drobac** [comment]
i bred all the bees from magic bees with the blocks and had no problem at all with breeding them, think this issue can be closed

**Comment by Hakameda** [comment]
It's mis-labeled now, it's the custom gendustry bees that were added

Sent from my Kata

 Drobac <notifications@github.com> wrote:



i bred all the bees from magic bees with the blocks and had no problem at all with breeding them, think this issue can be closed

**Comment by Drobac** [comment]
What kind of species did you try? I bred all the custom bees all the way to naquadria without a problem

**Comment by Hakameda** [comment]
All of them, wasn't working in alveary for breeding, ones that require blocks.  Tried 100+ iterations in ssp for clay and most others

Sent from my Kata

 Drobac <notifications@github.com> wrote:



What kind of species did you try? I bred all the custom bees all the way to naquadria without a problem

**Comment by Drobac** [comment]
Worked for me with Industrial apiaries, but had reports are the alvearies not working proper as well, Does the same affect normal apiaries?

**Comment by Dream-Master** [comment]
My Plan is to ad all Bees to gt code soon

**Comment by Hakameda** [comment]
Yup I Know, Been waiting

Sent from my Kata

 Martin Robertz <notifications@github.com> wrote:



My Plan is to ad all Bees to gt code soon

**Comment by Dream-Master** [comment]
soon yea one year later :) But i will to do it 100%

**Comment by Hakameda** [comment]
<3

**Comment by 0lafe** [comment]
At least we still got gendustry

**Comment by Hakameda** [comment]
So is this good now?

**Comment by MineAnPlay** [comment]
I'm about to start using the alveary and breeding bees so will give info if it works or not (if I forget just DM from discord since it's on survival and might not be able to do it quickly).

**Comment by Hakameda** [comment]
Still seems to not be working, even with bee changes. Possibly because it's using an extra bees block as the bottom center

**Comment by Dream-Master** [comment]
@Hakameda which block is needed ?

**Comment by Hakameda** [comment]
I will check tonight if it works with a regular alveary block or if it's still just needs some different block id

**Comment by Hakameda** [comment]
So it works with a regular alveary block in the middle, But not an extra bees alveary block. Maybe they just need to be added to a check or something?
