### ISSUE TITLE
Advanced re-battery IC2

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1322]
craft http://i.imgur.com/s91zqfO.png
need http://i.imgur.com/CUYtrAi.png
problem http://i.imgur.com/7RgfZIN.png

https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/IC2.zs#L828
to recipes.addShaped(<IC2:itemAdvBat:26> ...

best regards

**Comment by Dream-Master** [comment]
yes will fix it.
