### ISSUE TITLE
ore magnet not functioning correctly with gregtech ores

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#1323]
when you use an ore magnet to pull gregtech ores up to the surface, gregtech ores do this thing where they take the shape of some weird generic ore and when you mine it, it yields a cobblestone(even with silk touch). this is pretty problematic imo, since the ore magnet is a well designed way to efficiently scout what kinds of ores are below you in the early-mid game, and helps you waste a lot less time randomly digging.

http://i.imgur.com/rSmtO1S.png

**Comment by Namikon** [comment]
Nothing we can do here. The OreMagnet, how it is programmed right now, will break any GregTech ores upon moving.

**Comment by Dream-Master** [comment]
Maybe i need to disable this magnet or write a tooltip :"not works on GT Ores".

**Comment by Blinzer** [comment]
don't disable it for sure since it's still a big help, but i was just throwing it out here so that maybe someone who knows how to program could fix it
