### ISSUE TITLE
[suggestion] Complicate TiC tier 2 tools craft.

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1324]
And tools like hammer and lumber mill can be craft only on tool forge.
You made the complication that the tool forge can be craft at greg tier 3 with 2 aluminium ingots.
But I think additionally need to do complication of craft of cast form of broadaxe head, excavator head, hammer head.
I think is a good idia to craft it from aluminium block with some gregs tools.

**Comment by Dream-Master** [comment]
@hhheeexxx i not realy understand what you want to change. Can you explain a bit.

**Comment by hhheeexxx** [comment]
ok. Many players on our server want to fast dig. Get some drill or ichor picaxe it's too hard. But what easy? Easy to do TiC Hammer. What need for to do hammer? Need TiC furnance, to smelt metal, need casting form for all parts of hammer, need tool forge. What trouble is? Trouble is for craft tool forge. Need 2 aluminium screw because it's need 2 aluminium ingots. How to find 2 aluminium ingit? Craft EBF. Or try to find it in chest in dange or villige or in loot bag. Or may be ask somebody for gift it. And as result any day players on our server write: somebody sell/gift me 2 aluminium ingots. And i suggest add another trouble for players like that: complicate crafting of cast form of broadaxe head, excavator head, hammer head. Now it's aesy: craft stone part from coble, place it on casting table, pour the aluminium brass. I suggest to disable craft that form on casting table, and add reciepts with more aluminium. Like 1 Aluminium block, 2 aluminium foils, some tools from GT and may be anything else what can be obtain only in tier 3 gt.

**Comment by Dream-Master** [comment]
Ok got it. But i guess if the way is a bit more complicated people will cheat too. Gated the tools via Toolforge isn't optimal.

**Comment by Dream-Master** [comment]
wont change it.
