### ISSUE TITLE
Glass

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1325]
How you make normal Glass need a rework.

**Comment by Drobac** [comment]
Fluid extractor into solidifier not good enough?

**Comment by hhheeexxx** [comment]
I get sand put it in TiC furnance, solid in block cast. Then use chisel and get normal glass. And how you want to change glass craft?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/2e76cb1057c6ce4675c7235cd73579759fcc217b

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/241133365489696768/307277946278903810/unknown.png
https://cdn.discordapp.com/attachments/241133365489696768/307278079741526018/unknown.png
