### ISSUE TITLE
Recipes are overlapping a bit.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1326]
![image](https://cloud.githubusercontent.com/assets/4737429/25400454/f1896876-29f2-11e7-93c3-3ed08a619b12.png)
![image](https://cloud.githubusercontent.com/assets/4737429/25400469/fc1a5692-29f2-11e7-9f9d-420c6455fe43.png)

**Comment by Technus** [comment]
@Dream-Master if u can change the

**Comment by Dream-Master** [comment]
:)
