### ISSUE TITLE
[bug DI] [ADVB]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1327]
Here I will create a issue about the reproduction of things.
I will send a specific description to the e-mail of the Dream-Master, so that this blog will not become an encyclopedia of vulnerabilities.
This message will be like a reminder that you need to fix this.

**Comment by hhheeexxx** [comment]
fix is ready. need update mod in modpack.

**Comment by Dream-Master** [comment]
Fixed in Dev.
