### ISSUE TITLE
[bug DI] [CABI]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1328]
@Dream-Master I send description to your e-mail.
You can fast close it by ModFixNG plugin.

**Comment by Dream-Master** [comment]
Fixed in dev not tested.

**Comment by Dream-Master** [comment]
@hhheeexxx i send you the fixed Modfile later.

**Comment by hhheeexxx** [comment]
I get file in thread. i try put it to jar and test solution.

**Comment by Dream-Master** [comment]
Did you need my file or did you make it on your own ?
@hhheeexxx

**Comment by hhheeexxx** [comment]
give your file

**Comment by Dream-Master** [comment]
Will do it tomorrow

**Comment by hhheeexxx** [comment]
I put file in jar. Test it. Fix work good.

**Comment by Dream-Master** [comment]
ok nice.
