### ISSUE TITLE
[bug DI] [TCCT]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1329]
@Dream-Master I send description to your e-mail.

**Comment by hhheeexxx** [comment]
https://github.com/GTNewHorizons/TinkersConstruct/pull/6/commits/dcad6bfecbc5bd663c0855054e5b3bd0535c8bb6

tru this for fix

**Comment by Dream-Master** [comment]
I will miss this feauture. Are you able to code a Gui/inventory check?

**Comment by hhheeexxx** [comment]
I suggest putting this fix on now and leaving a reminder to do a normal fix. I think i can to do normal fix. But right now i have not enought time to find a correct solution and code it.

**Comment by Dream-Master** [comment]
Because the next update is not so soon I wait a Bit maybe you got more time.

**Comment by hhheeexxx** [comment]
@Ugachaga, may be this is close to your knowledge. 
crafting table from tinker construct and attached chest.
if I open gui, I can see chest inv. but until gui open, chest may be changed or removed, but I steel can get loot from gui. need add some check for this. like in moment of move item with chest inv throught gui check if chest present right now and consist this item.
I open TiC source:
public class CraftingStationContainer extends Container
and get point in constractor where it's get inv info from chest, but i see, there is no modify or save code. I think there is in base class from vanila. 
@Ugachaga, can you fix this bug or tell how Container class works to understand in which place it is necessary to add a check.

**Comment by Dream-Master** [comment]
idk how to fix
