### ISSUE TITLE
[bug DI] [MICR]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1330]
@Dream-Master I send description to your e-mail.

**Comment by Dream-Master** [comment]
So guess i need to remove it. Are they have any function/use we will missing ? @hhheeexxx

**Comment by hhheeexxx** [comment]
I check your config and found only enchant table reciept what consist it. I ban saws at our server a month ago, but no bug report about "i can't craft because its banned". May be we get it later. )))

**Comment by Dream-Master** [comment]
https://github.com/MrTJP/ProjectRed/issues/1145

fixed for 1.10 hope someone can make a 1.7.10 fix.

**Comment by Dream-Master** [comment]
No 1.7.10 update.

**Comment by Dream-Master** [comment]
sadly no fix for 1.7.10
