### ISSUE TITLE
Coke oven brick making

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#1331]
Hi, tried to build more coke ovens so i made a more bricks, but its also duplicating that wooden frame at the amount of clay, so if you make 64 pcs of bricks at time you also make 64 brick frames

**Comment by Dream-Master** [comment]
@Hyperic88 we know this bug.

**Comment by bigbass1997** [comment]
This is now the third issue opened for this topic. Please in the future try searching for the problem using Github's search features. Thanks.

#1287
#1298 

Fixed: 4f1c045c79c4beeafa050af4ddb50227b8eaa10c

**Comment by Hyperic88** [comment]
oh sorry :/
