### ISSUE TITLE
[bug DI] [CURS]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1333]
@Dream-Master I send description to your e-mail.

**Comment by Dream-Master** [comment]
@hhheeexxx are they have any need feature? Otherwise remove.

**Comment by hhheeexxx** [comment]
I think you can remove it. I don' t see people who use this in normal game. Idia of thing is good but need it to be different by color or another way to be realy usefull. Chest i think more simple to use.
