### ISSUE TITLE
[bug DI] [PRBK]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1334]
@Dream-Master I send description to your e-mail.

**Comment by Dream-Master** [comment]
why ban it you can't craft it? @hhheeexxx

**Comment by hhheeexxx** [comment]
I have a question. Are you have a list of items that can be obtain by mob drop and loot chest and other way of spawn in world? If you know what that item no way to be spawned in world it will be enought only disable reciept. Owervise you need aditional add item to ban list. Some about items what can be crafted before reciept remove.

**Comment by Dream-Master** [comment]
I never see it in chest and i not add it in my loot. I need to look what items can be dropped by mobs but i guess this item is not in the game by any of them.

**Comment by hhheeexxx** [comment]
Not forget about viligers who can sell items, tc gnome who can exchange items, hologoblins etc...

**Comment by Dream-Master** [comment]
ok so if there is a cfg i will it remove then.

**Comment by Dream-Master** [comment]
This bag cant be disabled but we can set it on the ban list on the server.

**Comment by Dream-Master** [comment]
Backpacks are disabled.
