### ISSUE TITLE
[bug DI] [HCMA]

### ISSUE THREAD

**Issue by hhheeexxx** [GTNewHorizons/NewHorizons#1335]
@Dream-Master I send description to your e-mail.

**Comment by Dream-Master** [comment]
@hhheeexxx Ugachaga send me a fix to close this dupe bug. Must be in the last 1.4.1.1 update. Can you test and veryfied it please?

**Comment by hhheeexxx** [comment]
Ok I test it.

**Comment by hhheeexxx** [comment]
I test in local - not fixed.
Now try to test client-server.

**Comment by Dream-Master** [comment]
Did you replace the class in extra utilities?

**Comment by hhheeexxx** [comment]
Ups. i get op while test and get wrong result. seems all fixed.
But may be i forgot correct key for bug.
I need to search right key when it work early and test again.

**Comment by hhheeexxx** [comment]
@Dream-Master I send correct description to your e-mail.
And test it on  last 1.4.1.1 update, This still work. Need to fix any way,

**Comment by hhheeexxx** [comment]
@Dream-Master this issue not about extra utilities. it's about pam's harvestcraft.

**Comment by Dream-Master** [comment]
@hhheeexxx better using clearnames. This cryptic issues makes impossible for me to track it correct.

**Comment by hhheeexxx** [comment]
there is clear name. first 2 letters - it's a mod name, second to letters is a block name. Harvest Craft MArket.

**Comment by Dream-Master** [comment]
ok.

**Comment by Dream-Master** [comment]
I will disable it again because i add crop seed bags.
