### ISSUE TITLE
Assembler II

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1337]
Add a assemblerII with more slotes like the Circuit Assembler (4 input slots or more.)

**Comment by hhheeexxx** [comment]
I like that idia. May be add more liqud storage also. But trouble for player is in cube only 6 sides. 1 for power input 1 for result output. And only 4 left to input anything by pipes. May be create multiblock like assembler line?

**Comment by hhheeexxx** [comment]
Input inert gas, input liqud soldering alloy, input circuit plate and many many small elements. Output complite circuit. Like a real technological process.

**Comment by Dream-Master** [comment]
For this we will have the circuit assembler very soon.

**Comment by hhheeexxx** [comment]
For normal work with pipes its will be consist only 4 ingredient, not more. Because only 6 sides present on block. 1 out 1 power input. Or may be in greg present block what can get items from pipes from 4 sides as example and put it on specific slot to near machene block? Like a robot arm cover.

**Comment by Dream-Master** [comment]
Will be made in a futher update.

**Comment by Dream-Master** [comment]
Assembler haw now 6 inputs.
