### ISSUE TITLE
Talisman of Nourishment not craftable

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1338]
i cant craft the Talisman of Nourishment, and xxrughxx45 said he hat the same problem, got all i need but cant start the infusion.. a known issue?
![image](https://cloud.githubusercontent.com/assets/25811344/25440226/1097f3d4-2a9f-11e7-9b59-55083d6b6050.png)

**Comment by Dream-Master** [comment]
I thought is was fixed? Have to look into it.

**Comment by Ghengis88** [comment]
ok

**Comment by Dream-Master** [comment]
@Ghengis88 did it  not work in sp or in mp or in both?

**Comment by Ghengis88** [comment]
multiplayer

**Comment by Dream-Master** [comment]
@Ghengis88 so in other words it worked in sp?

**Comment by Ghengis88** [comment]
i only play multiplayer, so havent tested it in SP

**Comment by Dream-Master** [comment]
@Ghengis88 is using a false ruby. So i will change it to a exquisite ruby.

**Comment by Ghengis88** [comment]
great!
