### ISSUE TITLE
Suggestion: Change to OD/OV Scanner

### ISSUE THREAD

**Issue by SwardGames** [GTNewHorizons/NewHorizons#1339]
Currently, the OD/OV Scanners are not very well suited to GregTech oregen, scanning for ores in a 9/25 block large cube around you.

As there is no feasible way to find ores without mining down to bedrock, I suggest that these be changed to scan a 3x3 rectangle from the player's current position down to bedrock, with the OV scanner being the same but having an increased energy capacity.

This would greatly reduce the amount of time required to search for ores before access to Ender Quarrys (at which point you dont even need to mine anything), which is in my opinion needlessly time consuming.

Of course, the Seismic Prospector would still play a role in the game, providing knowledge unattainable through the Scanners, such as what Oil is present.

Also, if possible, I suggest changing the recipe and voltage (but not EU capacity) of the OD Scanner so that it may be crafted and charged at MV, rather than HV, to put some more distance between the OD and OV Scanner upgrade.

**Comment by bigbass1997** [comment]
This suggestion you are proposing is to essentially make finding ores extremely easy. If such a change were to happen, the voltage tier should certainly not be lowered, if anything it should be raised.

Beyond that, mining takes up such little amount of time compared to the entire modpack. It may feel like it sometimes when you spend a few days looking for ores, but that's only a few days out of months that you will be playing..

As has been coming up more and more, recently, this modpack is supposed to be difficult and take time to work through. While yes I believe that the OD/OV scanners should have more use to them, I don't believe that changing them in this way would balance them; especially not if the OD scanner is moved down to MV. OD Scanner used to be EV tier actually, but multiple staff members felt that putting it at HV is better, (and the OV Scanner at EV).

**Comment by bigbass1997** [comment]
Also might be good to look back to the already opened issue #1211 where people already tried to discuss changing the scanner in some way. Currently marked as Low Priority.

**Comment by SwardGames** [comment]
It does not make finding ores extremely easy; just read the mining guide and it explains how to find ores. This simply reduces the amount of time required to search for them.

And I feel that MV would be a good place to gain this ability; by then you should have already found a number of different ore veins to get through Steam and LV and make an EBF. It would help get you whatever ores you still need in order to progress until you have access to an Ender Quarry, without relying on the computer to roll a dice in your favor and have the ore vein you are digging towards be what you are searching for.

**Comment by Drobac** [comment]
While i do agree that it would be nice to have something like you proposed have a 3x3 scanner at MV is way to early. If it scanned your chunk at a large cost of energy id be ok with that. No. 2 ic2 isnt developed by us and don't think we can change it so would require a new tool. If someone can program a tool with that kind of function ill be glad to have it in the pack, although a 3x3 should later in tiering not at mv

**Comment by bigbass1997** [comment]
Yes it would make finding ores extremely easy. No mining or any work required after making the scanner. Just walk along the surface right clicking every chunk.

MV tier is way too low for such a tool.

And what Drobac mentioned about IC2 is also a concern whenever someone brings up the idea of changing the scanners. IC2 as far as I am aware is closed source. So yes, someone would have to program a completely new tool to implement such functionality, if this is approved at all.

**Comment by hhheeexxx** [comment]
In greg tech there is already present machine what scan all ores in 96 radius and down to bedrock. It's a seismic prospector in advanced version. It's useful thing to find all ores. in 96 radius there is 12x12 chunks,
there is 4x4 = 16 passible veins center. It's easy way to find all you need. Go 100 block forward, get data, go 100 blocks, get data. Go home print books with data. Return and dig if you need one of that ores. It's seems like a real. Run and click OV scaner, that's not seems like real.

**Comment by Dream-Master** [comment]
I dont want and can change/fix that. @Technus any idea to add a new device maybe or should i close this?

**Comment by antifluxfield** [comment]
Well, there's a guy who made a simple mod for those who don't want to dig a hole for ore-hunting: https://github.com/GWYOG/GTVeinLocator. It adds some scanners for locating or prospecing ore viens and can even automatically create a waypoint in JourneyMap.
I have no idea about its balance in this modpack; but if you do want to add a portable scanner like that, this mod could be a good choice.

**Comment by Dream-Master** [comment]
will look at this mod

**Comment by Dream-Master** [comment]
@antifluxfield i tested the mod. Tier one only show position of veins, tier 2 write down empty waypoints to jorneymap so you cant see is there a vein or not and only tier 3 shows the exact vein or shows empty.
If you have this tool you never will use the sismic prospector. This 3 vein locators are better then ov and od scanner so i will tier them behind.

**Comment by Bryfer** [comment]
Moved the GTVeinLocator to an separated Issue #1543

**Comment by Technus** [comment]
Yes very low priority seems appropriate.

**Comment by Dream-Master** [comment]
Maybe we get a scanner mod in the future @Heracles421

**Comment by Dream-Master** [comment]
We add the Scanner mod.
