### ISSUE TITLE
Nether sapling not craftable

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#1344]
The item Nether Sapling [2496:2] from Thaumic Bases mod is not craftable since it requires Cinderpearl [472:3] which only spawn in vanilla deserts which aren't enabled.

In addition, this sapling is required for the quest Useful trees [#306] (Adept Thaumaturgy) making the quest not completable.

**Comment by Dream-Master** [comment]
ok i will add a recipe for it maybe in the crucible?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26459878/3b2663de-4178-11e7-8f8c-b119eb913e45.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26459881/3f43164c-4178-11e7-8762-5d5db1508e90.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26459889/42a4dde8-4178-11e7-9525-d1e06907e7e6.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26459914/5254764a-4178-11e7-8c75-db35be49c38c.png)
