### ISSUE TITLE
Power transformer

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1356]
Power transformer not have a recipe.
@Technus did we need to add some

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/25538237/3853fe82-2c42-11e7-88eb-2ceb35505745.png)

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/f317a56c17c6ac84df12d9661bd4821e3f6e9dfa/src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java#L2762

Coremod Has them, might be some materials used  set to null.

**Comment by Technus** [comment]
so check if you have correct coremod added as dependency?

**Comment by Dream-Master** [comment]
I start it in the pack so newest version

**Comment by bigbass1997** [comment]
Power Transformers have recipes as far as I can see. v1.4.1.1

**Comment by Dream-Master** [comment]
Ok they have now until all materials tools enable
