### ISSUE TITLE
Coal Pile igniter

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1357]
Did we change the recipe?
![image](https://cloud.githubusercontent.com/assets/2970688/25538345/a1ee1e22-2c42-11e7-81e2-995ffa43d2e0.png)

**Comment by Technus** [comment]
i guess so, this is why you must compare Mine, theirs and your recipe

**Comment by Technus** [comment]
cos in some cases i merged your recipes, in some cases i merged their recipes,
You just have to pickup the most annoying one, i picked up the most "suiting one"?

**Comment by Dream-Master** [comment]
K i will check.

**Comment by Dream-Master** [comment]
all ok the recipe match
