### ISSUE TITLE
Programmable Circuits

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1364]
Basic Circuits can be made to Programmable Circuits and this to integrated.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/25547658/c40331de-2c68-11e7-9c57-ef64cb26ad98.png)
![image](https://cloud.githubusercontent.com/assets/2970688/25547664/c881f3c6-2c68-11e7-8b02-a36f5823c985.png)
![image](https://cloud.githubusercontent.com/assets/2970688/25547670/d09c5ab0-2c68-11e7-9ff5-ff3fb1fb4a7a.png)

**Comment by Technus** [comment]
this should be the same thing by ore dictionary?
