### ISSUE TITLE
Quests LV tier 2 - Tico Tools tier 2 , unable to detect

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1366]
I crafted an Tico Hammer with steel parts as stated in the "One Block mining is so Old School" quest.
The quest does not detect my fresh made Steel hammer in part 2 of the quest.

Quest IDs; 742 743 744

Tested and affected quests are Hammer, Lumber axe

The excavator quest  wants you to craft 2 Large Plates, but you only need 1 for the Excavator.

Suggestion to avoid this problem;
Remove part 2 of the quest, so you only have to make the parts to build the hammer with, to complete the quest?

**Comment by Dream-Master** [comment]
@Bryfer did you craft it out of Steel? Maybe i need to remove nbt data.

**Comment by Bryfer** [comment]
@Dream-Master All parts steel, like the quest told me to

check quest #472 "your first tool" and see how you solved it there

![image](https://cloud.githubusercontent.com/assets/22825059/25562917/aba45d1e-2d91-11e7-8477-47087abf4752.png)
![image](https://cloud.githubusercontent.com/assets/22825059/25562943/f62985f8-2d91-11e7-8c5b-b11b3f08f582.png)

**Comment by Bryfer** [comment]
@Dream-Master The Excavator quest is also wrong, it wants you to craft 2 Steel Large Plates, but you only need one.

**Comment by alphaest** [comment]
Can confirm, built them out of pure steel and it doesn't detect them. Also the fake item in the quest has the name of "[?]fSteel Hammer". Same with excavator and axe.

**Comment by Dream-Master** [comment]
Will look at it.
