### ISSUE TITLE
Typo in quest #697 "2x Steel"

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1367]
![image](https://cloud.githubusercontent.com/assets/22825059/25561231/9da880fc-2d67-11e7-96b7-df301406508e.png)

Copper is spelled coppper, also I belive it should be Bronze instead of copper?

**Comment by Dream-Master** [comment]
yes indeed i need to change it.

**Comment by Radst0ne** [comment]
Well you need much Copper for Bronze :P
