### ISSUE TITLE
Titanium pipes

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1369]
Titanium pipes can not be broken with a wrench, atleast not huge and normal pipe

**Comment by Drobac** [comment]
Could be your wrench does not have hohg enough tool level. Not sure if  pipe breaking is affected by this

**Comment by Drobac** [comment]
High enough

**Comment by Ghengis88** [comment]
ah ok thx drobac, did not know that could effect if it worked
