### ISSUE TITLE
MV extruder quest

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1371]
" Extruder quest in Tier 3 (MV) tells me to make 8 shape plates and then particular plates used in told machine in smeltery. Why this quest forces me to make 8 of them if later on i must melt them again in smeltery and then make appropriate plates. I think making 8 blank extruder plates should be removed from quest." - Mulisz 

Posting this issue made in Complaints to github quote above

**Comment by Dream-Master** [comment]
Ok will look into it.
