### ISSUE TITLE
Thaumcraft Golem, Server Issue, Both Delta and Epsilon

### ISSUE THREAD

**Issue by Jayjayx5x1** [GTNewHorizons/NewHorizons#1372]
Since the code for the Epsilon server is pretty much the same i assume it applies.

Issue: Thaumcraft Golems despawning.

If mob limit is the cause: maybe make a whitelist of mobs not affected by the mob limit? (golems, horses, villagers)

**Comment by Dream-Master** [comment]
@Namikon can you check this please.

**Comment by Namikon** [comment]
Moblimits are **disabled** on both Servers, such is purging of those. Either this is "natural" despawn by the old known "Chunk-Border" load/unload issue of Thaumcraft, or someone issued a kill-entities command.

As for the Chunk-Border issue, make sure the entire area of your golems is properly loaded by Anchors. Golems tend to get lost if they walk into an unloaded chunk

**Comment by Jayjayx5x1** [comment]
@Dream-Master Closing this issue as from my view it is solved.
