### ISSUE TITLE
Solar Pannels from gt need wafers in recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1375]
Solar Pannels from gt need wafers in recipes

**Comment by Dream-Master** [comment]
1-128 eu added recipe to gt
512-xxxx i will add via script.

**Comment by Technus** [comment]
Avaritia recipes?

**Comment by Dream-Master** [comment]
The solar panel 512 and up using 9x9 recipes I add it via minetweaker all ready some versions ago
