### ISSUE TITLE
Heat Temp EBF

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1378]
![image](https://cloud.githubusercontent.com/assets/2970688/25579970/f698a6d6-2e7c-11e7-8a3b-44e29c7ef83a.png)

how we can fix it that only the recipes we add be working? @Technus

**Comment by Technus** [comment]
check if it works now dream

**Comment by Dream-Master** [comment]
I cant see heat temp over 9000 any more.
