### ISSUE TITLE
ic2 recipe changes by GT

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1379]
need to check.

**Comment by Technus** [comment]
iirc,
IC2 recipes are removed from IC2 and added to GT_RecipeMap-s
So IC2 macerator recipes are now in GT_RecipeMap.
So it might cause issues with minetweaker.

Scanerio:
There is some OP Ic2 recipe that we want to remove via minetweak.
But BloodAsp changes move it to GT map. 
So we remove nothing and the recipe, still exists (but in GT_recipeMap).

**Comment by Dream-Master** [comment]
i will check all stuff but this need time.

**Comment by Dream-Master** [comment]
Ok I not found any issues so far. I checked all crafting recipes. The processing recipes I can't check all. @Technus any suspicious items you have in mind I need to test?

**Comment by Technus** [comment]
Check if there are any IC2 recipes (moved to GT recipes) that you remove by scripts.

**Comment by Dream-Master** [comment]
any idea how to check this or did you mentioned it as todo in code @Technus

**Comment by Technus** [comment]
looks like we dont really remove recipes for IC2 machines in scripts

**Comment by Technus** [comment]
related
#1429

**Comment by Dream-Master** [comment]
Ok checked.
