### ISSUE TITLE
Question: Is this normal? [1.4.1.1]

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1380]
![2017-05-01_19 18 00](https://cloud.githubusercontent.com/assets/27621272/25587154/13fb4a5a-2ea3-11e7-86e1-1a4b39d29ffd.png)
![2017-05-01_19 18 03](https://cloud.githubusercontent.com/assets/27621272/25587156/13fe086c-2ea3-11e7-9ad6-7edf14390475.png)
![2017-05-01_19 18 51](https://cloud.githubusercontent.com/assets/27621272/25587155/13fde814-2ea3-11e7-91c3-0c0144838fb1.png)

It was not there before the last time I logged out

**Comment by Dream-Master** [comment]
No its not. MP? which version of the pack do you using?

**Comment by Radst0ne** [comment]
Singleplayer, Latest Version (1.4.1.1) Im not sure if it's relevant but I was at the quest tier 1 (sorry dont know ID) where you have to craft a flint and steel and go to the nether.

**Comment by Bryfer** [comment]
Try executing "/bq_admin default load" in chat 
You can find more info about this command here https://github.com/Funwayguy/BetterQuesting/wiki/Commands

**Comment by Radst0ne** [comment]
Ok that worked BUT I had to delete all the Quest which I have not completed with this command /bq_admin delete. I hope I did not mess anything up. Now I can somehow enter Tier 2 but there is nothing in it (no Quests)

**Comment by Radst0ne** [comment]
Okay everything seems to work fine.
It can be closed.
Thanks!
