### ISSUE TITLE
Uranium 238 / Plutonium 244 way too common

### ISSUE THREAD

**Issue by Valdevon** [GTNewHorizons/NewHorizons#1381]
Here's a screenshot of Callisto

![image](https://cloud.githubusercontent.com/assets/9509239/25666824/a7124102-2fef-11e7-9af2-cc68fe94102c.png)

**Comment by Valdevon** [comment]
Update.....

![image](https://cloud.githubusercontent.com/assets/9509239/25667446/7cb1f16c-2ff1-11e7-83fc-4caa140fd075.png)

**Comment by Dream-Master** [comment]
Ok so I need to check it

**Comment by Drobac** [comment]
Can confirm this issue, on calisto 80% of the veins are Uranium/Plutonium ones. But the issues isn't only on callisto but on all the planets where this ore mix spawns, it is too frequent and overwrites some of the useful veins

**Comment by Dream-Master** [comment]
Ok will reduce this mix

**Comment by Dream-Master** [comment]
i removed it from Ceres. Found on IO, Ganymed and Callisto
