### ISSUE TITLE
Double Recipe

### ISSUE THREAD

**Issue by TheRealHypo** [GTNewHorizons/NewHorizons#1382]
Hey today I've got a complain of a user on my server.

He found out, that if you take a Pot + Tofu you only can get boiled Egg out of it, though it also could make Stock with it.

See Pictures:
https://gyazo.com/d53e7a693b1aa2cd10e7a147b1e16845

https://gyazo.com/2cff61f27ee026cca899e8b56ac74975

**Comment by Dream-Master** [comment]
I will look into it and change recipes if necessary.
