### ISSUE TITLE
Cooked Vension, furnance recipe missing

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1385]
Raw Vension (id:6460) cannot be cooked into Cooked Vension (id: 6461)
It can only be cooked with the disabled pam's harvest oven.

Raw Vension can be obtained using animal traps, and is the only meat product, from the trap that cannot be cooked in an furnance.

Suggested solution: make an furnance recipe to turn raw vension into cooked vension

**Comment by Bryfer** [comment]
@Dream-Master 
I've found another Pams harvest raw food that is missing

add Furnance recipe; Raw Turkey (id:6456)-> Cooked Turkey (id:6457)

**Comment by Dream-Master** [comment]
will add.
