### ISSUE TITLE
Blood Magic Blood infused diamond block

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1386]
The blood infused diamond block takes 9 bound diamonds in the compressor. Problem is those are not stackable so you can not craft the block in a compressor. Even processing array with 9 slots input dont work.
If you cant craft blood infused diamond blocks you cant craft the t6 orb and the bazooka

**Comment by Dream-Master** [comment]
ok will change the recipe.

**Comment by Dream-Master** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/2970688/26284860/03588bf2-3e45-11e7-8e37-e076de196445.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26284862/0ac32c26-3e45-11e7-88c7-569ccc07f471.png)
