### ISSUE TITLE
Blood magic high tier reciepes too expensive/time consuming

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1387]
High tier reciepes take many blood infused diamonds. These use 4 amorphic catalysts each which means a blood infused diamond block (9 blood infused diamonds to craft) takes 36 infusions.
 one cannot automate this. I suggest making the amorphic catalyst in a dire crafting table and then making the blood infused diamond in an arcane workbench so the thaumcraft aspect is still there. Another suggestion is to change the reciepes for the blood infused diamond block to thaumcraft infusion.

**Comment by Dream-Master** [comment]
Infusion can be automated so far i know. I will look into it.

**Comment by Technus** [comment]
Yes all can be automated with  AE2+Gadomancy

**Comment by DietmarKracht** [comment]
gadomancy is no real automation for infusion. just a simple device that can right click the runic matrix for you
there are several problems that come with infusion automation.
-getting the correct item in the middle pedestal and the rest around it. 
-wait until the infusion is done before another can start
-trigger to stat the infusion
...

**Comment by Dream-Master** [comment]
It is expencive and time consuming like all High Tier stuff. I not change here anything because Blood Arsenal is optional stuff.
