### ISSUE TITLE
Quest #650 Armors and Jetpacks/Copter Jetpack invalid item

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#1388]
The quest page 3 Retrieval task requires you to make a Basic diesel generator 1953:1110 but it needs to be Advanced diesel generator 1953:1111 because that is needed for the page 4 Crafting task item Two-Cylinder Diesel Engine 4347:5

**Comment by Dream-Master** [comment]
ok will check it.
