### ISSUE TITLE
2 Mod wishes

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1389]
Inventory-Tools (Back for Tools)
https://minecraft.curseforge.com/projects/inventory-tools

Crafting Tweaks
https://minecraft.curseforge.com/projects/crafting-tweaks?gameCategorySlug=mc-mods&projectID=233071

**Comment by bigbass1997** [comment]
Inventory-Tools:
We already have a bunch of backpacks, most are much larger than what this mod provides. The "Backpack" mod is a great example of what I mean. Also, we already have dollies, so not sure what this mod even adds to the modpack that we don't already have.

Crafting Tweaks:
Would anyone honestly use this feature? Most recipes in this modpack are so complicated that most of these features would be of no use. If you want it particularly for yourself, you are free to download the mod and add it to your own client, as the web page clearly states that it will work without installing on the server.

**Comment by Dream-Master** [comment]
@DragScorpion @bigbass1997 i will check the mods and let you know what i thinking.

**Comment by Dream-Master** [comment]
Crafting tweaks will be in the next update.

**Comment by bigbass1997** [comment]
> Crafting tweaks will be in the next update.

Why? You yourself said exactly:

> ok mods are dimissed

on Discord (assuming you meant "dismissed").

What is your motivation to suddenly add this mod?

**Comment by Dream-Master** [comment]
o i will ask in in Discord if we get a mojority to add the mod or not.

**Comment by Dream-Master** [comment]
@DragScorpion if you want the mods just add them to the pack i won't.

**Comment by Bryfer** [comment]
Wasn't the discussion in gtnh_staff enough discussion about this mod?
