### ISSUE TITLE
thaumcraft focus upgrade

### ISSUE THREAD

**Issue by xxrughxx45** [GTNewHorizons/NewHorizons#1390]
i tried to upgrade my blink focus but it wont let me click the upgrades i want it only let me upgrade it with frugal upgrade and i had the xp needed and the green button but it just doesnt let me click it. and i had this problem with another focus and another person had that problem too

**Comment by Dream-Master** [comment]
@xxrughxx45 i never used and dont know how to test it.

**Comment by xxrughxx45** [comment]
dream-master its when you upgrade focus using the foci manipulator i think it was from when you add special upgrades to the focus and it wont let you click it

**Comment by Dream-Master** [comment]
it can be like drobac said a Tc addon compatiblilty problem. Not sure what i can do here.
