### ISSUE TITLE
change EBF recipes to use mixed dusts instead of alloying ingots.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1393]
The our way of:

Mixed dust with crafting recipes - lossy like 10-20% of dust is lost
Mixed dust with mixer - all dust is given

Then ebf the mixed dust.

**Comment by Dream-Master** [comment]
@Technus did you add/change it allready or did you plan to add/change it?

**Comment by Technus** [comment]
If it is not marked as FixedInDev... it is not done

**Comment by Dream-Master** [comment]
K

**Comment by Technus** [comment]
It is recipe changes you could  do :P

**Comment by Dream-Master** [comment]
@Technus 
```
Mixed dust with crafting recipes - lossy like 10-20% of dust is lost
Mixed dust with mixer - all dust is given
```
This is a function i cant programming maybe its better you add it.

**Comment by Dream-Master** [comment]
adding/changing all this recipe manuylly is insane. I dont see any Alloying recipes in the EBF.

**Comment by Dream-Master** [comment]
For me this issue is done.
