### ISSUE TITLE
Missing locale in current version

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1394]
![image](https://cloud.githubusercontent.com/assets/4737429/25738959/07cabbbe-3180-11e7-8c70-eeb514d6ca9c.png)

**Comment by Dream-Master** [comment]
Yes and the new circuits need to be added too.

**Comment by Dream-Master** [comment]
Ok i will check all ores and all assembly line recipe items.

**Comment by Dream-Master** [comment]
Fixed
