### ISSUE TITLE
Transfer Node (Hyper Energy) recipe

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#1395]
![20170506221401](https://cloud.githubusercontent.com/assets/25171639/25773135/bdd9525a-32aa-11e7-923b-6b7bab9b54c7.png)
![2017050622175](https://cloud.githubusercontent.com/assets/25171639/25773138/c8bf3cc0-32aa-11e7-9e05-42f6e2d5ee1a.png)
The Hammer and Wrench will consume in the process

**Comment by Dream-Master** [comment]
You craft it where? Normal crafting table?

**Comment by FallDark** [comment]
in qed

**Comment by Dream-Master** [comment]
Ok so QED not support GT Tools.
@Technus @Namikon @Ugachaga we fork ender io allready are someone able to add gt tool support ?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/25823630/f7932a28-343c-11e7-980c-a118fbce6bfe.png)

fixed. I let gt tools out.
