### ISSUE TITLE
Chalcopyrite Dust

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1397]
![2017-05-07_00 36 46](https://cloud.githubusercontent.com/assets/27621272/25776397/631620a6-32bd-11e7-8250-d1851a0271d8.png)
Chalcopyrite Dust (Purified and Crushed Dust) give the same amount of Copper,  only 3 Nuggets.
Should not it be Chalcopyrite Dust = 1 Copper Ingot? (Like Iron Dust etc.) (1 Calcopyrite = 2 Chalcopyrite Dust = 6 Nuggets = its cheaper to actually melt the ore rather than process it further.)

And is it normal that you, if you want to make wrought iron, have to smelt Iron, get 9 Pig Iron Nuggets and then compress them to a full Ingot?

**Comment by Bryfer** [comment]
Regarding the Chalcopyrite ore
There is alot of diffrent kinds of processing ores in Gregtech. and as you have noticed its not worth getting 3(6) nuggets from Chalcopyrite ore. You can throw the Crushed dust into an centrifuge or cauldron to clean it, that way you can get an full ingot from it. Processing the ore more than this will remove some of the precious copper but enable you to extract other materials from the ore.
There is also other veins that give 10 nuggets as Crushed Dust, most ores are different. double check before putting the ore in machines which route you want it to go.
Reading and checking out the picture here might help you understanding GT ore processing a bit better
http://ftb.gamepedia.com/GregTech_5/Mining_and_Processing#Late_game_processing

It's a bit tricky to get Wrought Iron, The method I use is making 9 Iron Nuggets from an Iron Ingot, and then putting the Nuggets into an furnance which creates Wrought Iron Nuggets, and then put these nuggets into an compressor.
When you progress more you'll find new ways to create crafting components in quicker and/or cheaper ways

**Comment by Radst0ne** [comment]
Thanks for the detailed answer!
But if you macerate a Chalcopyrite Ore, you get two Crushed Chalcopyrite Ore (which give 3 nuggets each which is perfectly fine). So now comes the weird thing. Normally, as you said, you crush the crushed ore again with the hammer or a machine and get a Impure Pile of something (in this case Impure Pile of Chalcopyrite) Usually you have to clean this dust using again as you said the cauldron ore another machine which also works perfectly fine. But the non washed Impure Pile of Chalocpyrite gives a Copper Ingot and the washed Chalcopyrite Dust just only 6 nuggets

**Comment by Dream-Master** [comment]
depends on what you get when you washing the dirty one. Can be happend that the clean variant get less then the impure.

**Comment by Radst0ne** [comment]
okay thanks!
can be closed
