### ISSUE TITLE
Blood infused iron large plate reciepe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1399]
Blood infused iron large plate (Tinker's Construct not Gregworks one) is not craftable. If you smelt blood infused iron in smeltery it cannot be cast to large plate. Other casts work.

**Comment by Dream-Master** [comment]
Other Casts not works well.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/25818474/01b97c8a-342b-11e7-986b-872095ec0327.png)
That is the reason. I need to disable one in Tinkers Gregworks.

**Comment by Dream-Master** [comment]
Sorry it downt work so you need to make it the GT Way.

**Comment by Dream-Master** [comment]
Thants it only Ingots working the rest i remove and you can use GT Extruder to craft it.
![image](https://cloud.githubusercontent.com/assets/2970688/26284416/f213c028-3e3a-11e7-8b0e-b0b987a207dd.png)
