### ISSUE TITLE
Too much loot config capitalization

### ISSUE THREAD

**Issue by Diresheep** [GTNewHorizons/NewHorizons#1400]
config/TooMuchLoot/loot/chest1.xml line 67, lowercase L does not match tag on unix systems

**Comment by Dream-Master** [comment]
chest1 not have a line 67, ok a empty one. I delete it and hope it is fixed. If not let me know and send me a pic Thanks @Diresheep

**Comment by Diresheep** [comment]
its the closing </lootGroup> doesnt match the opening </LootGroup>

**Comment by Technus** [comment]
One of us is blind then, cannot see it being broken anywhere.
https://github.com/GTNewHorizons/NewHorizons/search?p=2&q=lootGroup&type=&utf8=%E2%9C%93

**Comment by Dream-Master** [comment]
@Diresheep file and line please that i can check it.

**Comment by Diresheep** [comment]
line 66 TooMuchLoot/loot/chest1.xml, was broken in the server instance I downloaded from technic website, not broken in github.

http://i.imgur.com/LGEha9M.png

**Comment by Dream-Master** [comment]
ah ok. Will be fixed in the next release.
