### ISSUE TITLE
Overestimation of 10x Coke Oven quest

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1402]
"Why one coke oven when you can have ten" QuestID: 699

The quest itself wants you to craft 10 new Coke ovens, making your total to 11 by now if not reusing your old coke oven, which is a decent number to have at the start of MV 👍 

However.

The quest wants you to craft 11x Conveyor Modules, 10 Electric Pumps, **252 Small Tin Pipes and 126 Small Wooden Pipes** and two Better Barrels to store wood and charcoal in. 
The only problem here is that you will not even need close to 4 stacks of Tin Pipes, nor 2 stacks of Wooden Pipes.

From my testing I've found that you will need about 64 Small Tin Pipes, and about 32 Small Wooden Pipes.

The picture below shows the items the quest wanted me to craft. _(252tin, 126wood)_
![image](https://cloud.githubusercontent.com/assets/22825059/25791480/ed1b608c-33c0-11e7-9724-31f7ea0600c6.png)

Picture of my Coke Oven setup, It's an decent setup in my opinion. I assume most players will place them in similar ways. If I wanted to I could have stacked them ontop of eachother aswell to save even more pipes.
![image](https://cloud.githubusercontent.com/assets/22825059/25791901/ab935b26-33c3-11e7-836d-74f20aebcd44.png)
And this is a picture of my inventory, after the automation is complete. _(187tin, 94wood)_
![image](https://cloud.githubusercontent.com/assets/22825059/25791912/b5376046-33c3-11e7-860d-728dc3262676.png)

Conclusion: Reduce the numbers of pipes needed for the the quest.

**Comment by Dream-Master** [comment]
Yes thats difficult to find the right amount of pipes. I looking in my Setup when creating the quest. Will change it

**Comment by WarlordWossman** [comment]
Maybe add a text that says "you might need more pipes depending on how you connect all of them" so we can use the low amount Bryfer recommended for the quest but people who can't figure out the optimal way of piping wouldn't get confused if it doesn't work with the number of pipes the quest wants you to craft.

**Comment by Dream-Master** [comment]
ok good idea.
