### ISSUE TITLE
Transparent Blood Orb render issue

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1404]
The transparent blood orb doesnt show the amount of stored lp. Also the item itself is called 'unnamed' after binding to a player.

**Comment by Dream-Master** [comment]
Pic please

**Comment by DietmarKracht** [comment]
![2017-05-08_10 51 35](https://cloud.githubusercontent.com/assets/11991148/25797164/66acf5e4-33dc-11e7-9381-61afa4d467ae.png)
![2017-05-08_10 51 46](https://cloud.githubusercontent.com/assets/11991148/25797165/66b4936c-33dc-11e7-9916-621522fe83a9.png)

**Comment by Dream-Master** [comment]
We fork the mod so maybe we are able to fix it.

**Comment by Dream-Master** [comment]
@Technus can you help me here?

**Comment by Dream-Master** [comment]
No one? ok i close this now nothing i can do here.

**Comment by jurrejelle** [comment]
Not to bump ghost issues, but this is still a problem in 2.6.0 
![cad05f094d74483a6b8d89fd12002a2a](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36511264/f03dfbd3-2dc5-4752-9f52-9f019651f50c)
Maybe now people are able / willing to fix it?
