### ISSUE TITLE
Vis Channel augmentation cannot be installed.

### ISSUE THREAD

**Issue by Takafate** [GTNewHorizons/NewHorizons#1406]
Vis Channels augmentation from Thaumic Machina cannot be installed. When the infusion is started, it requires essentia the same as Tainted Core, not Vis Channel. I check the materials multiple times, and try with different wands, just can't solve the problem.

**Comment by Dream-Master** [comment]
Pic please

**Comment by Takafate** [comment]
![2017-05-09_18 33 27](https://cloud.githubusercontent.com/assets/12082829/25848100/6a8e4306-34eb-11e7-9533-a488605db667.png)
![2017-05-09_18 33 57](https://cloud.githubusercontent.com/assets/12082829/25848092/607b576e-34eb-11e7-95b0-e66197ed3961.png)
Two items are left, the infusion can't finish.
![2017-05-09_18 37 03](https://cloud.githubusercontent.com/assets/12082829/25848113/76a501fc-34eb-11e7-971d-86af7701738b.png)

**Comment by Dream-Master** [comment]
@Takafate Which Rod/Wand do you are using that i can try to rebuild it in my Sp Game?

**Comment by Takafate** [comment]
@Dream-Master I was using Void Aspected Infernal Scepter with Charge Buffer installed, but that problem is with ever wand i have.

**Comment by Dream-Master** [comment]
ok will test it if i got free time.

**Comment by Dream-Master** [comment]
I dont touche the recipe only the reaserch so it must be a bug iside the mod. Can you try with Vanilla Thaumcraft Wands to be sure it isnt a Mod compatiblity problem @Takafate

**Comment by Takafate** [comment]
It seems like a problem with Thaumic Machina itself. I try a client only contains Thaumcraft and Thaumic Machina copied from GTNH, the problem is still exist.

**Comment by Dream-Master** [comment]
Nothing i can do here If thaumic machine not updates then we not get a fix.

**Comment by MainFreak** [comment]
Depending on how exactly Thaumic Machina adds the augments and ModTweaker adds Thaumcraft Support you could actually do something about it as the augmentations seem to be NBT tags. If it is possible to do advanced NBT shenanigans you could make a custom function that "if no modifier tag present" adds the NBT, "if modifier tag present" adds +X to the current NBT and "if incompatible/max level of modifier installed" makes the recipe not change any stats. I am still a sort of noob at scripting and haven't done anything advanced besides of NBT Transfer and Arrays so I can not give you an example of how it would be possible to change the modifier recipes or anything.

However, I am not sure if that 100% circumvents the bug. I think the recipe just derps up when checking the Meta of the vanilla thaumcraft ingredients so "nerfing" the buffing methods (I was able to skip elemental wand cores and jar nodes with this augments so I really suggest you to do that) and use items with different IDs may solve this issue.

Fun Fact: This bug only appears after you researched the Tainted Core. Before that it worked fine.

**Comment by Dream-Master** [comment]
@MainFreak Did you mean that have somethings todo with my scripts in minetweaker?

**Comment by MainFreak** [comment]
No I mean that as far as I can tell Thaumic Machina is not modified/nerfed besides of the base ingredient thing. If you get lucky with a village that has Energetic Alloy and apply those augments on an early wand you can skip Elemental Cores (that require Titanium afaik) and get straight into Centivis stuff with a Greatwood Wand.

To this issue, I think Thaumic Machina's original recipes derp up as the recipe for Tainted Core and Vis Channel use the same items, however *with different meta*. If the augments are applied via NBT like all other Thaumcraft Wand Stats it is probably possible to emulate/modify the recipes to use different items so the ID conflict (I assume that is the issue) fixes itself. But I have no idea how exactly Thaumic Machina applies the augments. I can try looking into it, but I can not promise that I am able to make a fully functional script to circumvent the bug

**Comment by Dream-Master** [comment]
If you can look into would be nice. Sadly Thaumic Machina is not open source so far i can see.
