### ISSUE TITLE
spice of life

### ISSUE THREAD

**Issue by cryusion** [GTNewHorizons/NewHorizons#1407]
i dunno why but on a single player world (as i like to play that way) spice of life says i need 24 different food types to keep going... not sure if intentional or not but its really overkill if it is XD. screenshot: http://prntscr.com/f5tbrj

**Comment by Technus** [comment]
It is not.

**Comment by cryusion** [comment]
Wha- HEY whyd you close my thread before i can even ask anything else >:(
was going to ask if its food type or if its amount eaten. If its amount
eaten i see why, but food type? Im not filling nearly an entire inventory
for just food. The modpack is awesome otherwise

**Comment by Technus** [comment]
Read how spice of life works, this is not a tutorial page.

But in short, it remembers last X food items (not types) eaten, and for every one above Y in history it gives you less nutrition value.

**Comment by Bryfer** [comment]
You can ask questions like this on our Discord https://discord.gg/XC6QgeE 
Find the #help there :)

**Comment by cryusion** [comment]
Knew how it worked daniel, just made me wonder because this is the first
modpack ive played where the required number is huge... others usually
ranged from 6-8 not 24 xD and thanks mattias
