### ISSUE TITLE
Assembling machine recipe to 'level up' unbreakable wand can be done with a single wand

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1409]
The recipe sais to put in two identical wands, which will then be combined to form the next, better wand. But the machine starts working even if you only put a single wand, essentially duping them.

(Version 1.4.1.1 - DirtHuts server)

**Comment by Dream-Master** [comment]
pic please.

**Comment by Toperoco** [comment]
This one: http://imgur.com/a/pi9mu

As well as all the upgrades following that one

**Comment by Drobac** [comment]
Can confirm, if you put one wand in the assembler the process automatically starts and the wand upgrades itself without any resources needed. So if you have the tier 1 wand you can upgrade to max tier at no cost
