### ISSUE TITLE
Arcane assembler recipe from thaumic energistics is not working

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1414]
I have all the required item (including the fully charged thamium bossed silverwood scepter) to start the infusion. But the infusion won't start no matter what i did.

I even tried with item from creative mode and still doesn't work.
![2017-05-14_15 27 18](https://cloud.githubusercontent.com/assets/13598309/26031996/00f45516-38ba-11e7-9492-9a91527533c3.png)

**Comment by Dream-Master** [comment]
Will look into it

**Comment by Dream-Master** [comment]
You need a Silverwood Rod and Thaumium Caps. Then you need to fill the Wand.

**Comment by Dream-Master** [comment]
maybe its fixed now.

**Comment by noobyaran9** [comment]
Yes im sure thats a filled thaumium bossed silverwood scepter. The infusion just refuse to start.

**Comment by Dream-Master** [comment]
@noobyaran9 Try my new script file reload it and test again.

**Comment by Dream-Master** [comment]
@noobyaran9 try to lay the crystals in the right oder like it shown in the recipes.

**Comment by noobyaran9** [comment]
Where can i get the script file? Thaumcraft infusion doesn't require the item to be layed according to the recipes. I think the problem is on the check on the silverwood scepter.

**Comment by Dream-Master** [comment]
loo at this commit: https://github.com/GTNewHorizons/NewHorizons/commit/2c93cea50d1b6e806ba88d7d6b606cc62e56db50
I forgot to add the nbt as byte when you crafted the wan it goes wrong allready.
Solution remove this "as byte" in you scripts and hit /mt reload and it worked.
In the next version i fixed this bug in the crafting recipe.

**Comment by noobyaran9** [comment]
Yes that fixed the recipe. I'll have to wait for the server to be updated to make it then. Thanks.

**Comment by Dream-Master** [comment]
yes but then you need to craft a new wand because i fixed the wand recipes(That was wrong ).
