### ISSUE TITLE
Update Thaumic Tinkerer

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1415]
+it's version tag

**Comment by Dream-Master** [comment]
@Technus What needs to be done here ?

**Comment by Technus** [comment]
Change version number and remember to put it in the pack

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/ThaumicTinkerer/commit/2eaec0d01038cae179a92d7f2958b4b4dc7644a7

**Comment by Dream-Master** [comment]
Ok updated and in dev pack.
