### ISSUE TITLE
Mod Suggestion: ChiselTones

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1416]
This mod (addon) adds compability between Chisel (Chisel Mod) and Ztones decorative blocks

https://mods.curse.com/mc-mods/minecraft/228004-chiseltones

With mod (addon)
![image](https://cloud.githubusercontent.com/assets/22825059/26057378/b4f13812-3979-11e7-9c75-15f7b8828a29.png)

**Comment by Technus** [comment]
A bit redundant.

**Comment by Dream-Master** [comment]
Its a 6 kb Big mod so i will add it.
