### ISSUE TITLE
Cannot craft power unit

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1419]
The Power Unit isn't craftable following the recipe in NEI... I tried both an empty and full Re-Battery.

Recipe:
![2017-05-16_21 13 50](https://cloud.githubusercontent.com/assets/720212/26134442/be11e276-3a7c-11e7-897d-0d0bf2dcc8d8.png)

Trying to craft:
![2017-05-16_21 14 07](https://cloud.githubusercontent.com/assets/720212/26134449/c7316584-3a7c-11e7-931d-65cea162fa1e.png)

**Comment by bigbass1997** [comment]
Similar to #1322

@Dream-Master Not sure if 8a76dee91e909b76920c21d890f9142c6ae54577 fixes this too, or need to change all recipes that need these batteries?

**Comment by Dream-Master** [comment]
Ok meta id need to be changed

**Comment by Drobac** [comment]
In the batpack issue it can be fixed my charging and emptying the battery, so its Metadata issue there too

**Comment by Dream-Master** [comment]
@Drobac can you link it to here. Thanks

**Comment by Dream-Master** [comment]
@Fapiko can you try eth a empty battery please because i add meta id 26 because * crash the scripts.

**Comment by Dream-Master** [comment]
Meta id 26 is a unload battery so idk why it not working. Some day i will put all in code and then i can choose Wildcard value.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26262856/8ac89dfe-3cd6-11e7-8e4b-0a845fb15480.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26262863/8f643e18-3cd6-11e7-8ed2-3edc183ca04f.png)
works for me

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26262901/bf45a090-3cd6-11e7-980e-bb2661f18598.png)

**Comment by Dream-Master** [comment]
@Fapiko can this be closed?
