### ISSUE TITLE
Rocket glitches out landing on Ceres with launch controller

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1420]
As soon as it enters Ceres it glitches out here at Y=800 eating up fuel. Launch controller has worked fine on every other planet I've tried so far (Moon, Mars, Phobos, Deimos, Asteroids). I've restarted both my client and server since I encountered this yesterday, tried again tonight and it did the same thing.

![2017-05-16_23 12 22](https://cloud.githubusercontent.com/assets/720212/26137768/3b067b06-3a92-11e7-900d-2dfe2c7d3945.png)

**Comment by Technus** [comment]
Report at origin repository

**Comment by Dream-Master** [comment]
@Fapiko 
https://github.com/BlesseNtumble/GalaxySpace/issues
