### ISSUE TITLE
HU Mode Reactors seems unbalenced

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/NewHorizons#1421]
I did a test using 1.4.1.1 and find out that the HU reactors are too powerless, which even doesn't worth its material cost.
I'm using a reactor design with 152 output and 500 points of heat:
![image](https://cloud.githubusercontent.com/assets/17354844/26159681/d49dc35e-3b51-11e7-847f-b377a2e42456.png)
In GT 5.09, this design has an output of 304EU/t in EU mode; and for HU mode, using the Large Heat Exchanger and the Large Turbines (with all Turbine Rotors having the efficiency of 100%), the machines gives out 3000EU/t per reactor in total. But in this modpack, seems that you simply rise the EU output for 10 times, and this erases the superiority of the HU mode - even the best Turbine Rotor can only buff the output for no more than 200%. That's still far too less.

**Comment by Dream-Master** [comment]
@antifluxfield yes a agree. Did you know what is changed in GT code (original repro) that the reactor is much better?

**Comment by antifluxfield** [comment]
I'm not really sure...
For EU mode, seems that GT rewrite the code of the fuel-rod items:https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/items/GT_RadioactiveCellIC_Item.java. Perhaps mainly aiming at the MOX behavior change.
For HU mode, it directly change the math of LHE: https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_HeatExchanger.java#L112
I don't know whether it has made any other changes. But maybe you can try to change the outputModifier of "Base Coolant conversion rate for FluidReactors" in IC2.ini.

**Comment by Dream-Master** [comment]
I will check that code issue but what would a good output multiplier? Did you test any value?

**Comment by antifluxfield** [comment]
Numbers between 5~10 are all acceptable, since GT has already used that balance in past versions.
For me myself, I prefer 6.

**Comment by Dream-Master** [comment]
@Technus can you look at the gt code and maybe changed it to Blood asps version ?

**Comment by Dream-Master** [comment]
@antifluxfield i hope in the future we have gt++ mod with the new rector so i can disable ic2 ones.

**Comment by Technus** [comment]
It is not the issue, the thing is that - changing EU multiplayer does not change HEAT multiplier

**Comment by Dream-Master** [comment]
So what we can do ?

**Comment by antifluxfield** [comment]
The modifier I mentioned could be a solution: https://github.com/GTNewHorizons/NewHorizons/blob/master/config/IC2.ini#L102
If you set it at 6, the Reactor will output 6 times of Hot Coolant, which means 6 times of EU.

**Comment by Dream-Master** [comment]
But it means Fluid floating 6 times quicklier through the Reactor and the risk of overheating is much higher or i am wrong?

**Comment by antifluxfield** [comment]
@Dream-Master 
Yep... I forgot it...
Or maybe we can use this value:
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/IC2.ini#L96
This one doesn't changes the amount of the fluid, and can increase the unit heat of cooling the Hot Coolant; BUT IIRC it only works for those IC things. The LHE ignores this config (which should be a glitch of GT code), so we should also change the math of the LHE in addition to let it generate more steam. But a huge magnitude of steam flow - that's already large enough - can also lead to a high risk.

Besides, we can also increase the "fuel value" of the steam; but that may influence many other balances, including the Large Boilers, the lava in LHE, and other method producing EU by steam.

**Comment by Dream-Master** [comment]
No i can set in gt code how good the heated coolant is but idk where this was in the code.
@Technus any idea here?

**Comment by antifluxfield** [comment]
@Dream-Master 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_HeatExchanger.java#L112
This one?

**Comment by Dream-Master** [comment]
@antifluxfield but gt code have the same values so why i need to change it?

**Comment by antifluxfield** [comment]
@Dream-Master 
That's where GT controls how good the Heat Coolant is in LHE.

**Comment by Dream-Master** [comment]
Ok i know but In original gt it's not changed. Make some testing for me and write down some values you tested. I not changed it until I know what happens.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/a9408b912f9a34b1807207afbdd9d7a3042b4fb3

There HU mode balanced for use with GT multiblocks.
