### ISSUE TITLE
Tier 1 Rocket Engine / Booster Recipe Change

### ISSUE THREAD

**Issue by AdrianIonut** [GTNewHorizons/NewHorizons#1422]
They can be crafted only with the fuel canister wich gets consumed (you get it back if you do it manually) if you do it using a Me System, adding a fuel cell or even bucket would be better imo.

**Comment by Dream-Master** [comment]
If you have an ME system there are other things you have to worry about. Maybe i will add a empty Canister which are consumed in both recipes.
