### ISSUE TITLE
Strange effects

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/NewHorizons#1423]
Hey! When I play, suddenly, from time to time, i got strange effets, like poison, blindness, etc. What is it and how take this off?
![2b4376d0-3b8a-11e7-9f65-0b41d9a256d8](https://cloud.githubusercontent.com/assets/28770016/26183922/858bb6c0-3b8a-11e7-8177-8e865ffc5751.png)

**Comment by Drobac** [comment]
Are you near your Blast Furnaces?

**Comment by Dream-Master** [comment]
Using a Hazamuit Suit because you ill from pollution. @JohnWarrior01

**Comment by Methes** [comment]
http://www.gtnewhorizons.com/mobile/forum/viewthread/m/36844562/id/29532416-handling-pollution

**Comment by JohnWarrior01** [comment]
okey)tnx)
