### ISSUE TITLE
Biomes'o' Plenty honey bucket gives invalid item after putting the honey bucket in fluid canner

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1424]
They can't even stack and be used anymore.

![2017-05-18_13 23 33](https://cloud.githubusercontent.com/assets/13598309/26187717/977c0798-3bcd-11e7-81ae-6e2bd24fc0cf.png)
![2017-05-18_13 23 35](https://cloud.githubusercontent.com/assets/13598309/26187718/97c091ec-3bcd-11e7-8bfd-779db91e03c9.png)
![2017-05-18_13 23 44](https://cloud.githubusercontent.com/assets/13598309/26187719/97c6b98c-3bcd-11e7-8a52-ca6ed4392c8c.png)

**Comment by Dream-Master** [comment]
Yes wired.
@Technus any idea. Your Name remover  from GT not working for this item.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26262629/c004f144-3cd5-11e7-903f-fecc5c9d9088.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26262638/c3731432-3cd5-11e7-86b8-3c0bd7dbdd82.png)
