### ISSUE TITLE
Bio Chaff Pulverizer recipe remove

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1429]
Bio Chaff Pulverizer recipe remove

**Comment by bigbass1997** [comment]
Bio Chaff is not made using the pulverizer, Plantmass is. Unless you are talking about removing the recipe from the BloodAsp version. If yes, please specify that.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26267931/f31d4bc8-3cec-11e7-8d20-b213a2a2c1a3.png)
Yes Blood Asp take all ic2 recipes to gt . I mean i will remove the Leave to Bio Chaff pulverizer recipe.
In the future Biogass will be Methane.

**Comment by Technus** [comment]
Oh yea i knew this was going to happen

**Comment by Dream-Master** [comment]
In the newest version the recipe is out.
