### ISSUE TITLE
ProgressionMod: Prevent DimensionChange

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#143]
A player shall not be allowed to enter another dimension without fulfilling predefined requirements, by either reaching a specific tier or craft a specific item by himself.
If he tries anyways, the player shall be teleported back to his current bedspawn and receive a message "YOU ARE NOT PREPARED" (copyright Blizzard Entertainment)

**Comment by Namikon** [comment]
This will be an optional feature in the upcomming tiering-framework-mod

**Comment by Dream-Master** [comment]
There is a progression Mod already but i am not sure if they have the functionality our mod have ?

http://minecraft.curseforge.com/mc-mods/229495-progression

**Comment by Namikon** [comment]
Funny is, as long as you are searching for such a thing, you don't find it. As soon as you start to build your own, things like this pop up out of nowhere. Yes, it looks indeed like something I was going to build. I will look into that and decide if it's useable for us or not

**Comment by Namikon** [comment]
Ok I reviewed the mod:
- It has an ingame editor that is pretty advanced and stable, and it stores the progression config as json files that can be edited outside, even if kinda tricky to do, since you do not know the exact syntax, and it can mess up the whole thing if you make a mistake somewhere
- It can (according to the documentation) prevent you from crafting anywhere (Even machines), but this only works if the target mod has been added to the list of compatible mods and the author has added support for that mod (of course). Quick example: I was't able to craft a furnace in the vanilla crafting table, but I could just use an assembler instead, which worked fine. However: The recipe in NEI is blocked, so you have to know the recipe you want to craft. (He needs to add gregtech support first in order to prevent crafting there)
- The ingame editor also doubles as information display for players. When an item is blocked from crafting, NEI will show you this screen so you can see which progression you need in order to craft this item, instead of showing the recipe to you
- The progression is stored in a separate file, and not inside the player nbt, which is good.

After this first review I have to say, I'm kinda sad that someone else already that idea, and created a mod which looks mature, stable and usable for our needs. Also, this NEI integration and the ASM hooks into AE, thaumcraft and such are beyond my current knowledge. I'd have to read and learn about these things first, before I could even understand what's happening in his source

I will now stop my work on the progression mod, as it makes no sense to continue. Let's just hope this guy (who also somehow worked on modtweaker) will not drop his mod anytime soon, and be available for suggestions and improvements.

**Comment by Drobac** [comment]
Rarely you hear someone complaining that he doesnt have to do a ton of work.
I do like what in  creading about it, how many of the current mods in the pack are supported by the mod?

**Comment by Namikon** [comment]
I can find ASM hooks for AE2, Forestry, Thaumcraft, ThermalExpansion, Tinkers and of course vanilla stuff.
And about the work, well, it is a lot of work, but it was something that wasn't there yet, so it would've been something unique :)

**Comment by Drobac** [comment]
Would the ASM hooks for TC work on thr addons as well?

**Comment by Namikon** [comment]
From what I've seen, it only hooks into the crafting process, in order to track what you craft, or deny recipes from being crafted if you don't have the required progression. It has to be tested in detail how far you can extend this

**Comment by Namikon** [comment]
I did ask a few questions. If anyone is interested: http://minecraft.curseforge.com/mc-mods/229495-progression?comment=16

**Comment by Dream-Master** [comment]
Not sure if Joshies mod do every thing what we need. So not clothing your Project.

**Comment by Dream-Master** [comment]
Maybe we have to make a GT Addon for this Mod.

**Comment by Namikon** [comment]
We should discuss the requirement and a potential idea / basic concept about what we want to do with this mod before I jump into writing an addon for it. I can see a lot of probelms behind the simple idea to make it compatible to gregtech.

**Comment by Namikon** [comment]
Guess we made some "Progression" on that again. Just had a disucssion with Teteros and we came up with the following idea:
- Continue my work on this mod, do our own way (Can't promise I will be able to prevent crafting or providing an ingame editor like the "other" Progression mod does)
- Evaluating "Enchiridion" (http://minecraft.curseforge.com/mc-mods/76612-enchiridion) if it's usefull as a guide-book for the progressionmod

**Comment by Dream-Master** [comment]
A Ingame Editor is nice to have but absolutely not necessary. I like the Idea make a own Progression Mod !

**Comment by Dream-Master** [comment]
The Mod Author joshijack stopping the work on his progression mod.

**Comment by Namikon** [comment]
Surprise...
I had no time to continue on that yet as I have a ton of work to do and I just want to relax in the evenings, but I haven't forgotten about it

**Comment by Dream-Master** [comment]
It is not a complain only an Info.

**Comment by Dream-Master** [comment]
I close this because we have other things to do first.
