### ISSUE TITLE
Ender fragments in the Autoclave

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1431]
Allowing players to use the autoclave to turn the ender fragments into full ender pearls
But at a better rate than the normal crafting recipe.

Idea by MTesseracT

**Comment by Drobac** [comment]
Good suggestion

**Comment by Dream-Master** [comment]
´´GT_Values.RA.addAutoclaveRecipe(GT_ModHandler.getModItem("EnderZoo", "enderFragment", 2L, 0), Materials.Water.getFluid(100), new ItemStack(Items.ender_pearl, 1, 0), 9000, 1200, 30);
        GT_Values.RA.addAutoclaveRecipe(GT_ModHandler.getModItem("EnderZoo", "enderFragment", 2L, 0), GT_ModHandler.getDistilledWater(100L), new ItemStack(Items.ender_pearl, 1, 0), 10000, 900, 30);
´´
