### ISSUE TITLE
getting Nickel

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1432]
Hi
The Quest "A new Alloy" (#541) tells you, that you can only get Zinc out of small ores or as a byproduct but you can actually get zinc out of for e.g. Sphalerite Ore.
And maybe add a Quest for getting Nickel for the EBF since you have to search it in the Twilight Forest? (because I was not sure if I should get it out of Byproducts or go out and find it.)

**Comment by bigbass1997** [comment]
While yes the quest text should be changed, we really don't need more quests for different ores. Just look at the spreadsheet for all the ore mixes to learn where they are. http://bit.ly/gtnh-oremixes

**Comment by Radst0ne** [comment]
but then it should be said something like: "in the future look up the ores that you need" and then maybe where you can find the spreadsheet

**Comment by Dream-Master** [comment]
@Radst0ne Add some text and i can copy them to the Quest.

**Comment by Radst0ne** [comment]
If you want to cut diamond blocks into plates it's time to get a new alloy 'Cobalt Brass'. First you need to make brass out of zinc and copper. Mix it with aluminum and cobalt dust (can be centrifuged from various materials) to get your new alloy.
Ps: Now that you have come so far, we think that you are able to look up the ores that you need by yourself with the help of NEI and the ore mix spreadsheet (since we are nice, we shipped the spreadsheet with your modpack (oremix.ods), or you are brave enough to join the adventure called internet and click on this link: http://bit.ly/gtnh-oremixes

my Question: are hyperlinks possible?

**Comment by Dream-Master** [comment]
No links are not possible @Radst0ne

**Comment by Dream-Master** [comment]
I copied the first part of the Text so far.
