### ISSUE TITLE
Quest: 'Routed pipes' & 'Can u eat those?' not detecting being crafted

### ISSUE THREAD

**Issue by shawnacrane** [GTNewHorizons/NewHorizons#1434]
Quest book only detected the routed junction pipe (which is made via crafting table) being made by me. They were all crafted in one session and had not left my inventory between crafts

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26282739/900e7c38-3e17-11e7-9450-6f965412d19d.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26282740/94b1a814-3e17-11e7-9684-8ef5e4edb201.png)

fixed allready in the next version.
