### ISSUE TITLE
Deep Dark Portal to cheap

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#1435]
The reciepe for the portal to the deep dark should be nerfed. Currently it requires Black Plutonium that can be found on T7 planets. You can find infinity catalyst ore and black plutonium ore in the deep dark dimension. thus you can get the infinity ingots and stuff before heading to the T8 planets. i think one should have to get to T8 planets before getting infinity ingots. Therefore i suggest changing the reciepe for the deep dark portal by adding one to four infinity ingots to the infusion reciepe.

**Comment by Dream-Master** [comment]
Will to and i take the research at a later place in the Thaumcraft Book.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26286051/09997154-3e5c-11e7-915a-bff924ae06e4.png)
