### ISSUE TITLE
Turbine rotor tooltip have a typo

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1436]
![2017-05-22_10 24 53](https://cloud.githubusercontent.com/assets/13598309/26290915/901cfa44-3edd-11e7-94c3-44d8baa2a25a.png)
![2017-05-22_10 57 45](https://cloud.githubusercontent.com/assets/13598309/26290916/901dfc64-3edd-11e7-9adf-a7133317db0c.png)

The turbine rotor plasma energy per tick tooltip should be /t not /s.

**Comment by Dream-Master** [comment]
@Technus can you verfying it?
