### ISSUE TITLE
Wrong type of Gold Cap used for greatwood wand

### ISSUE THREAD

**Issue by wingez** [GTNewHorizons/NewHorizons#1438]
When crafting gold caps for the "Novice thaumaturge: improving your wand" quest it produces **GTNewHorizons:Gold Wand Cap**. However **GTNewHorizons:Gold Wand Cap** cannot be used for crafting  the greatwood wand, instead **Thaumcraft:Gold Cap** must be used

![image](https://cloud.githubusercontent.com/assets/12143465/26327945/7485fe2a-3f41-11e7-9da0-08a97c072814.png)

![image](https://cloud.githubusercontent.com/assets/12143465/26327977/978e10e2-3f41-11e7-9f03-937628bd7709.png)

![image](https://cloud.githubusercontent.com/assets/12143465/26327989/9e48ba2c-3f41-11e7-8109-9b6a487dc6c1.png)

**Comment by Bryfer** [comment]
If I remember correctly, the recipe using the thaumcraft gold caps is supposed to be disabled but that part is not working properly. 
There is an new recipe for the greatwood wand that requires lich bones and the gtnh gold wand cap

I'm currently at work so I cannot verify this right now or provide an screenshot.

**Comment by Dream-Master** [comment]
Will post a screenshot in a sec.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26341960/58b21bd4-3f96-11e7-9da3-0f66766bb341.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26341964/5cd32924-3f96-11e7-9f66-7ae66691e6cb.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26341969/6293343a-3f96-11e7-83ae-2589df5c9686.png)

**Comment by Smeany** [comment]
How is one supposed to accumulate 35 vis to craft the golden wand when the previous wands can only store 25 vis? The Quest refers to the uncraftable wand without the lich bones.

**Comment by Bryfer** [comment]
Crafting the Iron Capped greatwood Wand in between should solve this issue
this one can hold 50ea, and costs 20ea to craft.

maybe this is the intended way to go?
@Dream-Master Is there a few quests missing here inbetween Iron Capped Wood Wand and Gold Banded Greatwood Wand?

![image](https://cloud.githubusercontent.com/assets/22825059/26389410/198afcf4-405a-11e7-92e4-543abe397f55.png)

**Comment by Dream-Master** [comment]
@Bryfer yes will do.

**Comment by Smeany** [comment]
I don't know whether it's a bug or not the thaumonicum wand research branch for exampe for the golden caps shows the caps recipy on the first page as usual, but on the next page a recipy for a wand with shadow imbued cloth caps. Same with the greatwood wand core. It shows the wand core recipy and on the next page a recipy for a wand without the previous greatwood core. That makes little sense to me. 
![2017-05-24_14 19 33](https://cloud.githubusercontent.com/assets/23564498/26403054/041a5aee-408d-11e7-8c93-1b53931f345f.png) 
![2017-05-24_14 19 34](https://cloud.githubusercontent.com/assets/23564498/26403070/0cf4e74c-408d-11e7-8348-854d5693d233.png)
![2017-05-24_14 19 46](https://cloud.githubusercontent.com/assets/23564498/26403081/1d2cd61a-408d-11e7-96f6-8e3a6ac619d7.png)
![2017-05-24_14 19 48](https://cloud.githubusercontent.com/assets/23564498/26403084/238dbfe2-408d-11e7-83eb-1af501063024.png)

**Comment by Dream-Master** [comment]
@Smeany sadly i cant choose wich wand appears because thaumcraft book pick the first wand they found with this id so far i know so nothing i can do against it only remove all pages.
