### ISSUE TITLE
Quest question

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1439]
![2017-05-23_11 59 33](https://cloud.githubusercontent.com/assets/13598309/26338025/937402be-3faf-11e7-97d8-d5c178f159f3.png)
![2017-05-23_11 59 37](https://cloud.githubusercontent.com/assets/13598309/26338026/937532c4-3faf-11e7-96c4-cf6abf5cd21c.png)

The "Tier 4" quest requires "Molten Plastic" quest  to be done so that it could be unlocked. But "Molten Plastic" quest is not marked as main quest. Some people might miss it.

**Comment by Dream-Master** [comment]
Ok will look into it. Now i changed alot because of the new Circuit Update.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26342061/cf4f6454-3f96-11e7-8e62-1b6edfac6d01.png)
