### ISSUE TITLE
Issue with pump and everful urn

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1442]
Right clicking any electric pump on GT on the everful urn returns this item.

![2017-05-27_12 54 16](https://cloud.githubusercontent.com/assets/13598309/26518120/d7621f4a-42db-11e7-82bd-231aba29cd10.png)

**Comment by Bryfer** [comment]
GT covers are meant for GT machines and GT pipes. Place the pump on an pipe with import mode instead.

Iirc this is an known issue without solution

**Comment by noobyaran9** [comment]
That was an accident. Then i tried again with a LV electric pump just to be sure that im not seeing things.

**Comment by Dream-Master** [comment]
@noobyaran9 @Bryfer try to using the reneme machine @Technus  adds for us and see if this fix the item.

**Comment by DietmarKracht** [comment]
i can confirm this bug. had it too on the delta server

**Comment by noobyaran9** [comment]
That item is no longer usable for anything at all.

**Comment by Dream-Master** [comment]
@noobyaran9 again did you test it in the machine I mention earlier or did you ignore it?

**Comment by DietmarKracht** [comment]
i guess renaming the item doesnt matter because it has no meta id

**Comment by DietmarKracht** [comment]
maybe try the disassembler

**Comment by SirAzazel** [comment]
Item appears to have no damage value (no metadata) so it is no longer item it was nor it can be just 'renamed' to fix it. I can also guess that item also looses its NBT. Most likely this item is not revertable in any way.

**Comment by SirAzazel** [comment]
Possible workaround: if only one thing bugs like that - could probs just add MT shapeless to comvert it back to proper item

**Comment by noobyaran9** [comment]
The MT shapeless is not possible, because all kind of cover turns into that item when clicked on the everful urn. 
That item can't be used in any machine or any recipe. The only uses it has is to drop into the trash can.

**Comment by SirAzazel** [comment]
use it to make scrap for UU fab ;D

**Comment by Dream-Master** [comment]
@noobyaran9 @DietmarKracht  try the renaming machine from GT Tec added.

**Comment by noobyaran9** [comment]
There is no such machine called "renaming machine"

The renaming machine will not work, because the item stacks although that item is created with different parts. If the renaming machine would work, why don't just create alot of that item with LV stuff and renaming it to UV parts and tier skip straight into UV?

**Comment by Dream-Master** [comment]
I will show you the machine later @noobyaran9

**Comment by Technus** [comment]
... I close the same issue 3rd time

**Comment by Technus** [comment]
Leaving open so probably it will reduce duplicate count...

**Comment by Dream-Master** [comment]
Everfull/burn urn is Thaumic exploration.

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/Thaumic_Exploration/issues/1
