### ISSUE TITLE
Suggestion, IC2 reactors

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1443]
I would suggest adding info in the quest for ic2 reactors that the effectivness is multiplied on the server.
I meant to skip reactor and wait for naquahada because i did not know about this. i thought the amount of materials and work was not worth it, but with the multiplier that changes alot! anyone else has a thought on this?

**Comment by Dream-Master** [comment]
Ok will add it.

**Comment by Bryfer** [comment]
\n\nHint:\nThe multiplier is set to **10** in this pack that means your Nuclear reactor is **10 times** more efficient.
Wasnt the multiplier 20?

**Comment by Dream-Master** [comment]
No 10 who set it to 20? @Bryfer

**Comment by Bryfer** [comment]
@Dream-Master I have just seen that it was on x20 on discord. Never seen anyone say that its x10
I have never tested the IC2 reactor myself.
![image](https://cloud.githubusercontent.com/assets/22825059/26530867/bb124736-43dd-11e7-93b0-081d3287202d.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530868/e2666b28-43dd-11e7-8639-9afea6f84637.png)


![image](https://cloud.githubusercontent.com/assets/22825059/26530827/cd3c0c36-43dc-11e7-8c5d-ca6643536184.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530829/d67a19be-43dc-11e7-90bf-f042c5f1c7eb.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530833/dd77ad76-43dc-11e7-8a8a-950e2ee0e498.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530835/ec4d2092-43dc-11e7-85f8-ca6fdded9cee.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530843/14996d4e-43dd-11e7-871f-476ee1cc2a25.png)
![image](https://cloud.githubusercontent.com/assets/22825059/26530859/6c5f1448-43dd-11e7-959b-7a38b6e023c2.png)

**Comment by Dream-Master** [comment]
```
wind = 1.0
nuclear = 10.0
semiFluidOil = 1.0
semiFluidFuel = 1.0
semiFluidBiomass = 1.0
semiFluidBioethanol = 1.0
semiFluidBiogas = 1.0
Stirling = 1.0
Kinetic = 1.0
radioisotope = 1.0
```

**Comment by Dream-Master** [comment]
nuclear = 10.0

**Comment by Dream-Master** [comment]
both servers

**Comment by bigbass1997** [comment]
The multiplier is definitely set to 10.0.

However, test in SP on current version of modpack yields these results:

1x Single Uranium Fuel Rod generates 100 EU/t, and 4 Heat per Durability
1x Single Thorium Fuel Rod generates 20 EU/t, and 1 Heat per Durability

1x Quad Uranium Fuel Rod generates 1200 EU/t, and 192 Heat per Durability
1x Quad Thorium Fuel Rod generates 240 EU/t, and 24 Heat per Durability

No other components are in the reactor, only whichever rod is being tested at a time.

**Comment by bigbass1997** [comment]
So the problem here is not that something is wrong with the multiplier, but actually there is a misconception for what the base EU/t really is for the fuel rods.

**Comment by Technus** [comment]
Multiplier for EU/t is 10x
But also Thorium is 2x on top of that

That is what started the misconception of 20x boost.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/IC2.ini

Updated the config to buff the fluid reactor to match the EU reactor.
