### ISSUE TITLE
Scuba helmet and hazmat suit recepie bug?

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1447]
![image](https://cloud.githubusercontent.com/assets/25811344/26527941/108126ae-439f-11e7-8b1d-a885a475be3f.png)

what am i doing wrong? Trying to make Scuba helmet

**Comment by Dream-Master** [comment]
Use tinkers glue.

**Comment by Dream-Master** [comment]
I add refined glue recipes now.

**Comment by Ghengis88** [comment]
now i managed to craft Scuba helm and hazmat suit, i did it in advanced  II assembling machine. Seems like the recepie saying 30 eu/t was the problem..

**Comment by Ghengis88** [comment]
dont know if it is possible in mv assembling machine aswell

**Comment by Dream-Master** [comment]
If it can made in lv assembler it can be made in mv assembler too.

**Comment by Ghengis88** [comment]
i made it it HV assembler

**Comment by Ghengis88** [comment]
LV did not work

**Comment by Dream-Master** [comment]
did you try with a battery. Maybe you not give the machine enough eu because of cable loss.

**Comment by Ghengis88** [comment]
yes had a battery in the machine

**Comment by Dream-Master** [comment]
wait until the update and test again.

**Comment by Ghengis88** [comment]
ok
