### ISSUE TITLE
Mismatched textures on gt items

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#1449]
![image](https://cloud.githubusercontent.com/assets/4737429/26531882/702b8cf8-43f3-11e7-93ed-cc536a254211.png)

**Comment by Technus** [comment]
probably many more

**Comment by Technus** [comment]
same on pumps (LuV,ZPM,UV) etc.

**Comment by Dream-Master** [comment]
yes i fixed some of them allready

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/26531930/d75aac96-43f4-11e7-8d85-8a0dd5ce95a1.png)
![image](https://cloud.githubusercontent.com/assets/2970688/26531932/df29af26-43f4-11e7-999d-a3e3b443d5aa.png)

**Comment by Technus** [comment]
Oh ok.
