### ISSUE TITLE
Energy Bees Biome Requirement

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/NewHorizons#1450]
Energy Bees require biome:hell where as all other nether bees require biome:nether. Does not seem to register by any of the modded biomes as hell. I've heard you can find some really small ones but I play on a server with world borders and have had no such luck

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
Ok i change Biomes from Hell to Boneyard Biome and Undergarden Biome. Should work now.
