### ISSUE TITLE
Rare Thaumcraft aspects

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1451]
auram, victus, humanus, desidia, ira, gula, nebresium, tempestas, strontio, vitium, tempus, luxuria, invidia, gellum.

For me as Info for add Aspects to mods wich not have some.

**Comment by Technus** [comment]
hmm
even if you add it here and there ppl will still use the most ez mode option

Auram - there is some flower that makes petals with it - ask Drobac for details (iirc it is called Aurelia)
Gellum - Ice blocks, so basically water+solidifier

**Comment by Dream-Master** [comment]
@Technus its only a reminder for me to look at this aspects when i ann it to new mods. I work on ic2 items/blocks atm.

**Comment by Drobac** [comment]
Only one that really needs more sources is strontio. Ill write how to get all of them and how much you need em when i have a bit extra spare time

**Comment by Technus** [comment]
Fools ruby/gold seems like a good surce, strontio is for stoopid magic right?

**Comment by Drobac** [comment]
Think you only need it for magic energy converters, only way to get them is gt schematics. Didn't know you can get em from fools gold

**Comment by Technus** [comment]
it is a suggestion

**Comment by Dream-Master** [comment]
i add it to scrap and scrapboxes.

**Comment by Drobac** [comment]
Auram is easy, either by farming wisps, nodes on planets or aurelia plant. Victus is in tons of items, very easy to get. Tempestas is in cloud blocks, plenty of those. Tempus is needed in one or two recipes, if it even is used, can get it from clocks,maybe add it to an easier to get item. Luxuria, easy from gold or other metals. Invidia is from slime balls, gellum snow. Nebresium is also easy, some gt dusts/metals give it. Vitium can be gotten with vanilla tc way by overflowing the cauldron or using Apocrypha tainted trees. Rest are the Apocrypha aspects which can be easily farmed with Apocrypha shards

**Comment by Dream-Master** [comment]
@Drobac so which aspeckt is rare?

**Comment by Drobac** [comment]
Strontio definitely, need to get online to check up on any other

**Comment by Dream-Master** [comment]
Ok

**Comment by antifluxfield** [comment]
@Drobac 
We can get Strontio from GT manyullyn ingot.
Besides, IIRC GT alumite ingot also have this aspect, but we are not using it.

**Comment by Dream-Master** [comment]
will open up when we need it again.
