### ISSUE TITLE
Enhanced Inventories

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1452]
Fügt Kisten hinzu die man nach vorne öffnen kann.
(This mod added chests which can be open on the front side not on the botton side like regular chests)

![2017-06-01_23 35 27](https://cloud.githubusercontent.com/assets/9047664/26701893/1045a354-4723-11e7-83fc-ae5d63143252.png)

Das man diese Probleme umgehen könnte

Passe auch die Rezepte dafür an.

Benötigt würde noch JABBA Unterstützung für diesen Mod damit die Kisten transportiert werden können
(Jabba support is needed to transport this chests)

**Comment by bigbass1997** [comment]
What does this actually add to the modpack that does not already exist? Just reading the [mod page](https://minecraft.curseforge.com/projects/enhanced-inventories), I don't see any unique features.

**Comment by Dream-Master** [comment]
@bigbass1997 this guy playing us modpack making over 100 youtube vids of the pack in german and using this mod in in modpack. To add jaba support is 3 lines of code or so thats why i said him open an issue here.

**Comment by bigbass1997** [comment]
@Dream-Master What? I am not talking about JABBA. I am talking about Enhanced Inventories, the mod. What does this mod add that we don't already have?

**Comment by Dream-Master** [comment]
@bigbass1997 We have the Ironchest mods (and Irochest Minecrarts) but there are people dont like Iron chests and added Enhanced Inventories Mod. We dont need that mod but if we add jaba support for this mod they can use it. We dont add this mod dont worry .

**Comment by bigbass1997** [comment]
Well as I said, Enhanced Inventories doesn't appear to have anything that our modpack does not already have. That is why I am asking. I was not insulting the user at all, just asking a question.

**Comment by Dream-Master** [comment]
no more mods atm
