### ISSUE TITLE
Crash when log in

### ISSUE THREAD

**Issue by Lardyking** [GTNewHorizons/NewHorizons#1453]
Hi

I joined epsilon and walked around for the first time. For some reason i ate a mana bean. I insta died and client crashed. Now everytime i log in i crash.

https://gist.github.com/Lardyking/696417943d9c7fbcc2b0476405aa8c78.js
https://gist.github.com/Lardyking/e6de1d0659d5814742b561241cc8d010.js

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/ec659800a0303ffb91b6a83828fdc765
https://gist.github.com/Dream-Master/a6ca52c089475177da07f0d348aac168

**Comment by Dream-Master** [comment]
maybe i will blacklist Manabeans with Block limiter that no one can eat this beans.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31316201-3ecba2bc-ac29-11e7-87d9-b5f855dd70fb.png)
