### ISSUE TITLE
Tinkers' Construct Beheading doesn't work on special Mobs

### ISSUE THREAD

**Issue by zouquan741** [GTNewHorizons/NewHorizons#1454]
I made a 40% beheading cleaver, kill lots of Wither Skeleton, and no heads dorp.
I thinks the dorp rate of heads didn't change.

After googling, found a solution on reddit:
1.Navigate to your minecraft directory (the one with the mods folder)
2.Open config/SpecialMobs.cfg
3.Change all instances of B:_allow_vanilla=false to B:_allow_vanilla=true
4.Restart your game/server.

**Comment by noobyaran9** [comment]
We also have iguana tinker tweak which also nerf beheading %. 
The new formula is 5% + (3*behading level)% = Your actual beheading %

**Comment by Dream-Master** [comment]
@noobyaran9 so you got a few heads i guess?

**Comment by noobyaran9** [comment]
Yes.

**Comment by Dream-Master** [comment]
Ok so issue can be closed I guess.
