### ISSUE TITLE
Pyrolyse oven quest consumes pieces

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1455]
The Pyrolyse oven quest consumes the parts as you complete the quest stages - I'm assuming this is unintended as none of the other multiblock quests I've done so far do this. Also, there appears to be a typo, the oven casing's are spelled with a Z (Pyrolyze vs Pyrolyse)

**Comment by Dream-Master** [comment]
ok will set this to false. Sadly all new Quests are consumequests by default. So maybe someone forget it to change.

**Comment by Dream-Master** [comment]
Quests fixed
Names fixed
