### ISSUE TITLE
Heavy duty T4 plate giving the wrong output

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1456]
![2017-06-04_13 10 16](https://cloud.githubusercontent.com/assets/13598309/26759123/d679ec00-4927-11e7-8bad-5962bd1ad6ad.png)
![2017-06-04_13 10 20](https://cloud.githubusercontent.com/assets/13598309/26759124/d67a1cde-4927-11e7-9ce9-62552dd4a93b.png)

It should be outputting tiny pile of HSS-G instead of tiny pile of HSS-E.

**Comment by Dream-Master** [comment]
Ok will fix

**Comment by MineAnPlay** [comment]
SDHC-120 also gives wrong output should be stainless steel but outputs desh

**Comment by Dream-Master** [comment]
ok will look into it too.

**Comment by Dream-Master** [comment]
change Fluid to HSSE

**Comment by Dream-Master** [comment]
change desh to stainless steel in SDHC
