### ISSUE TITLE
Witchery Arthana bug

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#1458]
Whey you cratf altar, and placed candelabra, and then you placed arthana, it happens that it dupes on that altar table so you can pick up more, i tried to relog, and still have then all in my inventory 
Edit: it happens when you place arthana with shift-right click, then do it again with an empty slot where the arthana knife was

**Comment by Dream-Master** [comment]
Sadly Witchery is close source and not longer developed.

**Comment by Hyperic88** [comment]
Ok, i just tried to help ;)

**Comment by Dream-Master** [comment]
Maybe someone can make a fix
