### ISSUE TITLE
Missing Circuit

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1460]
Version 1.5.0.0 testing

One of the 4 crystal-processor circuits is missing. The missing should be a circuitUltimate in between crystal-processor assembly and crystal-processor mainframe. 

In addition crystal-processor assembly should be a circuitMaster instated of circuitUltimate.

**Comment by Dream-Master** [comment]
Look at this sheet:
https://docs.google.com/spreadsheets/d/1Z8IcI553bSPDB-dSrE1knsHiYiekcdO8JBrmaiZklZU/edit#gid=0
There are 3 Crystal processors and a Data Orb.

**Comment by Dream-Master** [comment]
There are no missing circuits between that two circuits you mentioned.
And no crystal-processor assembly  are not a Master Circuit when i look at the sheet from Blood asp.
