### ISSUE TITLE
H2S not breaking down into aspects in the Alchemical Boiler.

### ISSUE THREAD

**Issue by Giovanni-NL** [GTNewHorizons/NewHorizons#1462]
![image](https://cloud.githubusercontent.com/assets/4085882/26804941/1451c23c-4a4a-11e7-82ac-1180aaf6d5d9.png)
This H2S cell has aspects Aqua and Ignis.  However, when I put the Hydric Sulfide into a Alchemical Boiler to get the aspects out, it tells me the liquid cannot be broken down into essentia.   That's not what I expected.  Perhaps this is because the aspects were set on the H2S cell, and not on the actual Hydric Sulfide gas. 
![image](https://cloud.githubusercontent.com/assets/4085882/26805091/be8e0580-4a4a-11e7-9792-a471677041b3.png)

**Comment by Dream-Master** [comment]
Maybe we need to test it with the new version.

**Comment by Dream-Master** [comment]
Many fluids have aspects but cant break. So not an bug i guess.
