### ISSUE TITLE
Cables burning beyond chunk borders for no reason.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1464]
I'd like to add another case to issue #802 that was closed some time ago.

On server Delta I've created the following setup:
Main energy storage of MV Buffer with 4 Batteries firing into MV transformer, making the voltage 1A 512V.
![2017-06-06_14 20 40](https://cloud.githubusercontent.com/assets/8257735/26828990/08b9c35a-4ac4-11e7-9dce-e285d37269e5.png)

This power is spread through my base by 1x Silver cable (512V). The MV transformer cannot output more than 1A so that 1x cable is just fine. Here you can see first crossroad into two different machine systems.
![2017-06-06_14 20 51](https://cloud.githubusercontent.com/assets/8257735/26829049/3cdf2f80-4ac4-11e7-9294-8351de9b6912.png)

One path leads to ore processing station, where the cable goes into another MV transformer.
![2017-06-06_14 20 19](https://cloud.githubusercontent.com/assets/8257735/26829098/66259258-4ac4-11e7-8eff-1acb0a0b0af5.png)

This cable, when under load, randomly catches fire in the two remaining blocks after chunk boundry. It has absolutely no reason to do so. (Seen from opposite side)
![2017-06-06_14 22 08](https://cloud.githubusercontent.com/assets/8257735/26829127/87f8c486-4ac4-11e7-8c08-76ef9b2513c3.png)

Now this has nothing to do with chunk loading or unloading, it happend 5 blocks away from me.
Only those two cables burn up just behind the chunk border.
I've had this power distribution system for many voltages and months on my local server without any issues, so it's probably server related.
Looks like Greg fucked up somewhere.

**Comment by MineAnPlay** [comment]
Known bug happens because of a server plugin which makes chunks that you are in work at different speeds compared to other chunks which causes overamp in the cables. Solution is to use battery buffers or transformers at chunk borders

**Comment by Technus** [comment]
^ exacly, or chunk load all chunks

**Comment by Methes** [comment]
Alright, thanks for explanation.
