### ISSUE TITLE
Diamond shield #660 and Diamond Spear #659

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1465]
![2017-06-07_12 45 03](https://user-images.githubusercontent.com/13598309/26862678-deec5d46-4b7f-11e7-82b0-13f94e17c8de.png)
![2017-06-07_12 45 06](https://user-images.githubusercontent.com/13598309/26862679-def09564-4b7f-11e7-85dc-8a7cbe6170cd.png)

This 2 quest can't be completed even when i had the items in my inventory. 
I've tried if the item damage :97 parts would complete the quests but its not working too.

Related to #1345

**Comment by Dream-Master** [comment]
Fixed in the nee update.
