### ISSUE TITLE
Viable mob protection

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1468]
as it is right now, there is no viable anti mob protection, this is a situation I have (frequently) in my claim, with a magnum torch and a monster repellator:

https://i.imgur.com/vq9RXAm.jpg

Question: will there be any viable mob protection? Since this is just risky. Slimes are not neutral mobs (especially with infernal mobs) and void creepers teleport wherever they want all the time (I have spotted them multiple times in the middle of my factory)

**Comment by bigbass1997** [comment]
Build Turrets for protection.

**Comment by mtesseracttech** [comment]
There are hobgoblins around, will they be blasted as soon as a turret goes up?

**Comment by Dream-Master** [comment]
I think neutral mobs are not shooten by turrets.

**Comment by Bryfer** [comment]
Iirc there is 3 buttons in the turrets.
Hostile, neutral and players
And also an blacklist for stuff it should not shoot

**Comment by Dream-Master** [comment]
i think this can be closed ? @mtesseracttech @bigbass1997 @Bryfer

**Comment by mtesseracttech** [comment]
I think so
