### ISSUE TITLE
Gravichest change

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1473]
This isn't an issue exactly, but more of an annoyance. The gravichest takes some LuV level items to make (NbTi wire and chrome casing), and it holds 30M EU. However, it only charges at EV tier, which means it takes about 12min to charge. I think with the high cost, it should be either IV or LuV tier to charge it.

**Comment by MineAnPlay** [comment]
Use the turbo charger.

**Comment by Technus** [comment]
Also the items are not being balanced by what eut tier they are, but on the principle of mechanics

**Comment by Dream-Master** [comment]
Any thing we can do against it or change it ? @Technus

**Comment by Drobac** [comment]
i recharge my GraviChestPlate in the AFSU and its pretty fast. Also if you have Epiclappacks the insta recharge the chestplate and they recharge basically instantly in an AFSU

**Comment by Dream-Master** [comment]
so close it ? @Drobac
