### ISSUE TITLE
Coins and Co

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1474]
Tooltip usage coins usage hearts(bq)

**Comment by Dream-Master** [comment]
You can buy Food and healing Potions with Coins.

**Comment by Dream-Master** [comment]
Make a Chapter to explain coins usage = unlock Quests Chapters and buy stuff.

**Comment by Bryfer** [comment]
Can you share this new idea you have about coins?
I noticed that you changed the number of coins you receive from quests. 

I just want more information about this "new" system before you release it, so me or someone else who is playing can help you make it better before you release it.

What kind of coins will give; food items? Healing potions?
How expensive are you planning on making them? 
What is the other kinds of coins allowing you to buy/unlock?
What is the new total amount of coins available after each tier?
Will players who has preciously completed quests be able to unlock these <new things> properly?

**Comment by noobyaran9** [comment]
Why don't just remove all the coin rewards from all the quest? Then, add a new section of quest which unlocks quest where you can trade coins with some items or some killing task after u completed some quest in other section.

**Comment by Dream-Master** [comment]
@Bryfer sure i let you know when i know what i planing. Because no one suggest something i need much longer to progress. 
@noobyaran9 No then the Coin system is complete obsolete. I balance the coins you get per quest and make a new chapter where i show people how to trade with coins.

**Comment by bigbass1997** [comment]
More suggestions for the coin system can be found in #1469 and #1202.

**Comment by Dream-Master** [comment]
I will add a Coin Chapter but not in in 1.5.0.0
