### ISSUE TITLE
betterquesting

### ISSUE THREAD

**Issue by alonehunter** [GTNewHorizons/NewHorizons#1475]
I have minecraft account but my friend hasnt. we want play new horizons, but when i set onlinemode=true he cant join so i set it false then quest book not working. cant complete any quest or it resets after i close server. is there any way to fix it or onlinemode must be true for that ?

**Comment by Dream-Master** [comment]
yes online mode must be on.

**Comment by alonehunter** [comment]
and eula ? true or false ?

**Comment by Dream-Master** [comment]
eula true but for the server.

**Comment by alonehunter** [comment]
okay thanks. he must pay for great modpacks. great job btw
