### ISSUE TITLE
Flour Problems

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1476]
Ich habe leider den Bug, wenn ich den Mortar neben Flour, Rye, Barley; Rice, Oats und Potato lege das ich zwar das Flour sehe, aber ich es nicht entnehmen kann.

Wenn der Mortar ist mittig links und das Getreide oben links ist, dann funktioniert es, bis auf Rye.

**Comment by Dream-Master** [comment]
works for me.
