### ISSUE TITLE
Carpenter recipe change

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1477]
My Idea:
You can craft carpenters with 4 wood frame boxes and 1 wood screw
Since you can get sticks very easily from bamboo its not worth using iron, steel or Aluminum screws.
Since the wood frames take a little to craft what about changing each recipe to 4 frames and "x" screw but with higher tier screws the more Carpenterblocks you get from it
E.g. 
wood screw = 4
Iron screw = 6
Steel screw = 8
Aluminum = 10
Edit: or even more since wood screws a very very easy and cheap to make

**Comment by Dream-Master** [comment]
Will look tinto it.

**Comment by Dream-Master** [comment]
@Radst0ne there are assembler recipes with more output.
![image](https://user-images.githubusercontent.com/2970688/27012069-73c6f858-4ec9-11e7-8fae-48c9847eb82f.png)
Steel
![image](https://user-images.githubusercontent.com/2970688/27012071-79263318-4ec9-11e7-9c9e-9cffc1b560ce.png)
Alu

**Comment by Radst0ne** [comment]
yeah but alu e.g. is too weak. You need 8 frames and 1 screw, with wood you need the same 8 frames but 4 screws
since wood screws are easy and nearly instant to make the other types need a buff

**Comment by Dream-Master** [comment]
so you mean extended the Carpenters Blocks?

**Comment by Radst0ne** [comment]
Yeah

**Comment by Radst0ne** [comment]
This seems well balanced:
4x Wood Frame Boxes 4x Wood Screws = 2 Carpenterblocks
4x Wood Frame Boxes 1x Iron Screw = 4 Carpenterblocks
4x Wood Frame Boxes 1x Steel Screw = 6 Carpenterblocks
4x Wood Frame Boxes 1x Aluminum Screw = 8

Aluminum is now more profitable around 64 Blocks per Ingot, but also spam crafting with wood screws is also possible (wood farm, automation etc.)

**Comment by Dream-Master** [comment]
@Radst0n you need a benefit in the assembler. The more i look at the recipes the less i want to change it.

**Comment by Radst0ne** [comment]
you mean a benefit over the normal crafting recipe?
