### ISSUE TITLE
Brick Block recipe 

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1478]
What about adding  a recipe so that you can smelt in the alloy smelter  a clay block with the block form to a full brick?

**Comment by Dream-Master** [comment]
Not so realistic. Bricks ok but Bricked Blocks not.

**Comment by Radst0ne** [comment]
well okay thought it's a bit easier when you have a lot of clay blocks that you can burn, instead of breaking them down to clay and burn them and then compress them again (since you have done the compression already or silk touch)

**Comment by Dream-Master** [comment]
@Radst0ne You mean Vanilla Clay Block ? If yes this make less sense to process it in the alloy smelter. After it you get a burned/hardened Clay Block out.

**Comment by Radst0ne** [comment]
oh yeah never thought on this! I'll take everything back :P
but maybe instead of put the 4 bricks into the compressor, using the assembling machine?
That recipe could use water (like the crafting recipe for the vanilla brick blocks does)?

**Comment by Dream-Master** [comment]
I am not sure if this makes it better. Sure adding a recipes isnt that much work. Will look into it.

**Comment by Radst0ne** [comment]
It could be a little faster but requires water

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27012028-9b972f0c-4ec8-11e7-9ab8-a1a84c297695.png)
