### ISSUE TITLE
Carpenter Bug?

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1479]
You can't place carpenter blocks ontop of a hammered half block (even if filled)

**Comment by Dream-Master** [comment]
I dont know. Why a bug? Can you send me a pic please. @Radst0ne

**Comment by Radst0ne** [comment]
![2017-06-11_15 44 24](https://user-images.githubusercontent.com/27621272/27011494-e9195c84-4ebc-11e7-97d8-8074bc19a7fb.png)
You can't place any carpenter blocks ontop of a "half carpenter block"
It only works if a block is behind where you can aim at

**Comment by Dream-Master** [comment]
Why not i dont see a bug here.

**Comment by Radst0ne** [comment]
yeah that is why I am asking :P
It's just weird because I build a huge fatory out of carpenters blocks and its a pain in the butt to build it because you can't simply place them ontop of each other

**Comment by Dream-Master** [comment]
No all is fine.

**Comment by Radst0ne** [comment]
okay this can be also closed :stuck_out_tongue_winking_eye:
