### ISSUE TITLE
Galaticraft sealable blocks Decorative lamps

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#148]

**Comment by Drobac** [comment]
This was more of a suggestion to add some more sealable blocks, its pretty low priority but would be good to have suggestion for them in one spot

**Comment by Dream-Master** [comment]
I can add them but i will add the new Red Project lights

**Comment by Dream-Master** [comment]
@Drobac Please test it if it works:

ProjRed|Illumination:projectred.illumination.lamp:*

**Comment by Dream-Master** [comment]
@Drobac  It works? We nedd more Blocks?

**Comment by Dream-Master** [comment]
@Drobac  can you test it please.
