### ISSUE TITLE
Cells destroyed by water tank sidings

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1480]
Right click with a water cell empties the cell into the tank but also destroys it

**Comment by Dream-Master** [comment]
Nothing i can do here. Use Water Buckets or pump it via pumps and Pipes in and out. (What Tanks btw Railcraft i Guess) @Radst0ne

**Comment by Radst0ne** [comment]
Yes the Railcraft Water Tank that collects water over time, I tried to empty my water cells because I needed them elsewhere.
Filling etc no problem

**Comment by Dream-Master** [comment]
If you put a pipe on the botton of the tank you dont need a pump(only the RC Valve)

**Comment by Radst0ne** [comment]
Okay I think this can be closed, since you usually dont fill this tank with water manually

**Comment by richardhendricks** [comment]
Ran into this issue myself - same problem happens if you place the cells into the internal GUI for the Railcraft Water Siding tanks.  Recommend adding a warning to the quest that it will eat cells.  Lost 128 cells that way. :(

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
Will add a note in the Questbook.
