### ISSUE TITLE
Coins are doubled on chest vision

### ISSUE THREAD

**Issue by Gyaviste** [GTNewHorizons/NewHorizons#1481]
![screenshot](http://i.imgur.com/QvmY4av.png)

**Comment by Dream-Master** [comment]
i guess because there are many. Try to put only one coin in the chest.

**Comment by Gyaviste** [comment]
I got it. Issue is already closed

**Comment by Dream-Master** [comment]
Ok

**Comment by Technus** [comment]
Added proper tag. (it is used rarely)

**Comment by Dream-Master** [comment]
Lol

**Comment by Gyaviste** [comment]
Thank you for that tag
