### ISSUE TITLE
Chiselling glass

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1483]
You can chisel TiC clear glass into Vanilla glass but not Vanilla glass into TiC clear glass. 
![2017-06-13_13 00 07](https://user-images.githubusercontent.com/13598309/27066672-50272092-5038-11e7-9f71-49f9c26453b2.png)
![2017-06-13_13 00 10](https://user-images.githubusercontent.com/13598309/27066673-502e84fe-5038-11e7-9227-f86167b8ed59.png)

**Comment by Dream-Master** [comment]
Maybe need to add it.
