### ISSUE TITLE
Animals on official servers

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1485]
On the official servers you can walk thousands of blocks as a new player trying to find animals you need to kill to advance in your quest book only to find none.
Sometimes if you find a suitable herd you'd like to breed, a mob cap can kick in, so you're screwed.
Sometimes when killing the animals you've bread THEY EXPLODE FOR NO REASON KILLING YOUR OTHER ANIMALS! (absolutely stupid mechanics I don't yet understand. seriously it's cancer)

These quests are EXTREMELY frustrating for a new player. Reducing mob cap is necessary so these early quests should be remade into gathering resources from animal trap.

**Comment by Bryfer** [comment]
#1207 is really similar, not sure if 1207 is before or after 1.4.1.1 tho.

**Comment by bigbass1997** [comment]
What mob cap are you talking about?

The mob cap was disabled months ago, and still remains disabled for both servers.

Also, just as I did the last time someone complained about how rare animals supposedly are, I just walked about 80-100m south of Epsilon spawn, and I already found 3 sheep and 2 pigs. Then I went further south and found more sheep and pigs.

Now, I am not defending the quests that require players to kill animals, only stating that they are not as rare as they seem.

**Comment by Methes** [comment]
My bad, thought the former mob cap was still in place and that's the reason I can't find any animals.
Maybe I was just very unlucky, nevertheless I deal with this problem every time I start on official servers so I thought I'd share it.

**Comment by Technus** [comment]
you can get spawn eggs from pams market too

**Comment by Dream-Master** [comment]
No in 1 5.0.0 I disable market but I think buying it with survivor coins would be nice

**Comment by Methes** [comment]
Why is everybody talking about pam's market. The problematic quests are in Tier 0, way ahead of the market.

**Comment by Dream-Master** [comment]
It is only a Info because you can dupe with the market. Ugachage try to fix it but i heared its not.

**Comment by Dream-Master** [comment]
@Methes what we can do here?

**Comment by Methes** [comment]
I'd suggest the following:
Animal trap recipe now uses slabs, which means access to a Saw.
1) Change the recipe to require planks instead of slabs.
2) Instead of killing pigs, make 5 raw pork meat retrieval quest.
3) Instead of killing sheep, make 9 wool retrieval quest (players will learn how to make one from cotton and it's enough for first bed).
4) Instead of killing cows, make 5 leather retrieval quest.

This gives players the choice of either killing animals or using animal traps and cotton, both perfectly fine.

Another step would be to give rewards of two coresponding animal Spawn Eggs (cows for leather, sheep for wool etc.) for these quests, so that players can spawn two of each animals and breed them. That doesn't seem OP to me. If you decide to use that, I'd suggest making the same quest for 6 feathers and recieving chicken Spawn Eggs quest, just to make it complete.

**Comment by Methes** [comment]
Some math behind these suggestions:
1) 9 wool means 135 cotton, so players should make reasonably large cotton farm that they'll need later anyway.
2) 5 leather and 5 porkchops means ~110 animal trap cycles to reach both. That's 27 string and 81 other crops just for the baits. That encourages players to also make food farms.

**Comment by Bryfer** [comment]
I believe this issue can be closed now that Epsilon has an animal farm available (/warp Animals) it's located close to "spawn of earth" ( /warp earth)

I have not checked if Delta also has this feature yet, if not it should be added there aswell 

@dreammaster
@drobac

**Comment by Drobac** [comment]
Core of the issue not fixed, but workaround present
