### ISSUE TITLE
Add a faster way to wash impure dust and purified dust.

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1486]
Instead of centrifuging the impure dust and purified dust at a slower speed and giving a tiny piles as byproduct, add a faster way of processing them without byproduct. Something like using the ore washer with a 1~2 tick processing time and gives no byproduct. 
Washing the impure dust and purified dust with the cauldron is almost impossible when u have a few millions of them. And centrifuging them will take ages even with processing arrays. And with these amount of impure or purified dust, the byproduct is basically meaningless.

**Comment by Dream-Master** [comment]
Not sure if i am able to code that in gt code. @Technus need help with it if we implement it.

**Comment by MineAnPlay** [comment]
Centrifuging with processing arrays doesn't take ages. If you really want speed just give it like 64 HV centrifuges. That won't be expensive if you have a few millions of dusts ;)

**Comment by noobyaran9** [comment]
I have a processing array with 64 HV centrifuge and i did a rough calculation of how long i need to clear out 1 million purified dust. 39 hours just to centrifuge them if they're 39s recipe on LV.

And i really dont need the byproduct, i just need a really fast way of cleaning them.

**Comment by Technus** [comment]
There is already one XD

Drop them into cauldron with water..

**Comment by Radst0ne** [comment]
Why not just afk near your processing array. 
A shit ton of dusts gives a shit ton of byproducts :D

**Comment by noobyaran9** [comment]
> Drop them into cauldron with water.
I will hire you as my assistant to clean all my dust. XD

> Why not just afk near your processing array.
I have way more than 1 million dust, 39 hours is just about 70% of my actual time.

> A shit ton of dusts gives a shit ton of byproducts :D
Pointless byproducts.

**Comment by draknyte1** [comment]
GT++ (As of two days ago) now has a simple dust washer, which nets 0 byproducts but is fast/cheap.
Used to replace cauldron washing, basically, but it's automatable.

**Comment by Dream-Master** [comment]
Ok cool
