### ISSUE TITLE
Olivine to perdiot

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1488]
when sticking olivine into a compressor the output is Block of perdiot, not olivine, no issue other then the name mixup i think and if you need block of olivine you just need to use the chisel, but thougt i should poste it anyway
![image](https://user-images.githubusercontent.com/25811344/27145351-c9e57746-5135-11e7-9a83-936ca7f740c5.png)

**Comment by MineAnPlay** [comment]
It's just that is oredicted before gregtech olivine block it has no issue since you really only need it for olivine plates which doesn't have issues with peridot.

**Comment by Dream-Master** [comment]
so long you can chang it back to olivibne i dont see a issue here. This Blocks are only storage Blocks i guess.

**Comment by Technus** [comment]
Olivines are Peridots with asteroid origin iirc.
