### ISSUE TITLE
1.5.0.0 Useless recipe

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1490]
Good Circuit Board has 3 recipes 1 crafting which requires 8 Fine Gold Wires and a Phenolic Circuit Board. The chemical reactor uses either 100ml Iron III Chloride or 200ml Sodium Persulfate and a Phenolic Circuit Board and 4 Gold Foil. But 4 Gold Foils and 8 Fine Gold Wires require the same amount of gold so the chemical reactor is not usefull at all.

**Comment by Dream-Master** [comment]
suggest a good new recipe @MineAnPlay

**Comment by MineAnPlay** [comment]
Make it so both the Circuit Board and the Good Circuit Board require normal wire not fine wire to craft in the crafting table and keep the chemical reactor recipe as is.
