### ISSUE TITLE
Charcoal into furnace

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1491]
pls delete this from the furnace. Version 1.4.1.1

![2017-06-14_23 33 33](https://user-images.githubusercontent.com/9047664/27155680-24a58076-515a-11e7-9e61-8d8fde467f22.png)
![2017-06-14_23 33 35](https://user-images.githubusercontent.com/9047664/27155675-249df162-515a-11e7-9f46-c02cd37544dd.png)
![2017-06-14_23 33 38](https://user-images.githubusercontent.com/9047664/27155678-24a4c9b0-515a-11e7-9481-63154255bbeb.png)
![2017-06-14_23 33 40](https://user-images.githubusercontent.com/9047664/27155676-24a2d218-515a-11e7-8267-afb1e9d200ee.png)
![2017-06-14_23 33 44](https://user-images.githubusercontent.com/9047664/27155679-24a50d58-515a-11e7-872e-d2aa0913ef49.png)
![2017-06-14_23 33 45](https://user-images.githubusercontent.com/9047664/27155677-24a2db8c-515a-11e7-9b7a-16d6fd2b7b5a.png)
![2017-06-14_23 33 48](https://user-images.githubusercontent.com/9047664/27155681-24b3b27c-515a-11e7-810f-4d57af568c3a.png)

**Comment by Dream-Master** [comment]
I dont have this problem in version pre 1.5.0.0
