### ISSUE TITLE
Recipe Change (Vacuum Freezer)

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1493]
Im Questbuch bitte die Anzahl der Frost Proof Casings von 16 auf 21 ändern. Denn man benötigt ein 3x3x3 (Hollow) (26), wenn man den Controller, einen Input Bus, einen Output Bus, einen Maintenance Hatch und ein Energy Hatch abzieht bleiben nach Adam Riese 21 Laut. PS ist auch in der GT Beschreibung falsch.

In the Quest Book the amount of Frost Proof Casings need to be changed from 16 to 21.

**Comment by MineAnPlay** [comment]
The tooltip is correct. It rights the MINIMUM amount needed not recommended (so when making something that might be expensive for you like lets say processing array it requires a minimum of 14 casings  so you can make the rest out of other things like ULV input buses or hatches to save resources).

**Comment by noobyaran9** [comment]
Suggestion:
There should be a maximum amount of hatches / buses that can be used in a multiblocks. XD

**Comment by Dream-Master** [comment]
So what i need to change here what amount of Casings would be balanced?

**Comment by noobyaran9** [comment]
> So what i need to change here what amount of Casings would be balanced?

Nothing.

**Comment by Dream-Master** [comment]
So let the quest lie it is?

**Comment by noobyaran9** [comment]
Im not sure about the quest as i can't read that language. I'm just basing off what MineAnPlay wrote.

**Comment by Dream-Master** [comment]
He wrote change the casings from 16 to 21

**Comment by noobyaran9** [comment]
Oh, then it have no issue then. There is nothing wrong with the quest. 
16 is the minimum casing required for freezer.

**Comment by Dream-Master** [comment]
@DragScorpion 16 ist das minimum so ich mach das zu jetzt vielleicht änder ich nur den text im Questbuch.

@noobyaran9 thanks for clarification.
