### ISSUE TITLE
Recipe Change: T2 and T3 OC CPUs

### ISSUE THREAD

**Issue by ianespana** [GTNewHorizons/NewHorizons#1494]
So, I've been playing on Epsilon for a time now, and I reached a point where I could craft a robot. Been playing around with it and decided to upgrade it, however I noticed that T2 and T3 CPUs use RAM in their crafting recipes.
I'm fine with it needing microchips and other metals like Titanium, but RAM sticks?

>![2017-06-14_17 11 49](https://user-images.githubusercontent.com/3208876/27156914-cd10fff0-5124-11e7-82e5-e1a823ab31df.png)
>![2017-06-14_17 11 52](https://user-images.githubusercontent.com/3208876/27156911-cd0d689a-5124-11e7-9ee2-7672395171e4.png)
>![2017-06-14_17 12 21](https://user-images.githubusercontent.com/3208876/27156913-cd11066c-5124-11e7-97b9-067504cc1015.png)
>![2017-06-14_17 12 26](https://user-images.githubusercontent.com/3208876/27156912-cd0f68f2-5124-11e7-97c7-e3c9750d570f.png)

My solution is using the same recipe as the T1 CPU, but instead of a Control Unit you'd need the previous tiered CPU. The required metals would also change, needing 2 stainless steel plates and 2 screws for T2, and Titanium for T3. Same goes for microchips, T2 would use T2 Microchips, while T3 would use T3 miocrochips
![2017-06-14_17 17 30](https://user-images.githubusercontent.com/3208876/27157069-7e4b05e0-5125-11e7-9f69-fb12e0f3f6c8.png)

**Comment by Dream-Master** [comment]
Yes i will do changes when i am nerfing this mod.
