### ISSUE TITLE
Issue with "consume=yes" in quest #781

### ISSUE THREAD

**Issue by GMous** [GTNewHorizons/NewHorizons#1495]
It's clearly mistake to consume 66 Pyrolyze oven casings, Control block and 9 Kanthal coils.

**Comment by Bryfer** [comment]
#1455 is similar, dupe (?)

**Comment by GMous** [comment]
Sorry. Could not find.

**Comment by Bryfer** [comment]
No probs, had some problems finding it myself, alot easier to find issues when people include the quest IDs like you did :) more inform to find using the Search function that way ;)
