### ISSUE TITLE
Alternative to the old >>>RED POWER 2<<< redstone pneumatic tube pipes?

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1496]
Is there an alternative?

**Comment by Technus** [comment]
don't think so, but later u can use AE2 with redstone p2p tunnels

**Comment by bigbass1997** [comment]
ProjectRed has pneumatic pipes already. Just not the redstone version. They are called Pressure Tubes.

**Comment by Dream-Master** [comment]
So we can cloe this issue ?
@Radst0ne
