### ISSUE TITLE
1.5.0.0 No way to get Arsenic in LV to advance

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1497]
There is 4 ways to get Arsenic. UU-Matter is to expensive. Arsenic ore is disabled (leave it like that). That leaves 2 recipes. Cobaltite and Realgar but Cobaltite requires MV to process and Realgar only spawns in high tier planets. So add Realgar ore to any of the starter dimensions (overworld, nether or twilight forest).

**Comment by Dream-Master** [comment]
realgar small ore spanws in the nether in 1.5.0.0.
