### ISSUE TITLE
Dragon egg

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1499]
Required for bee breeding and only one is available on the server (or none on epsilon), could use a crafting recipe which doesn't require high tier bees(which need an egg in order to get them). Perhaps by using Draconium or a Dragon heart to craft as Chaos Dragons don't drop an egg

**Comment by Technus** [comment]
some draconium enrichment process for chicken egg XD

**Comment by Drobac** [comment]
Uuu yes, i like that idea

**Comment by Drobac** [comment]
Chicken egg + nutrients (+gendustry mutation liquid). Then big egg + draconium (+liquid ender) to make it into an "Ender egg". Then ender egg with drago  hearts (not consumed) to make dragon egg

**Comment by Dream-Master** [comment]
Ok will look what i can add here. Tier suggestions @Drobac

**Comment by noobyaran9** [comment]
You can respawn the dragon using the resurrection stone and i believe the dragon will give an egg.

**Comment by Dream-Master** [comment]
I remember this process was bugged in the past and crash the server. @Drobac correct me if I am wrong.

**Comment by Drobac** [comment]
You can ressurect it, but it requires you to finish the legendary quest and have access to draconic cores, which is a bit late IMO. Latest i would put it is IV, although that is late already

**Comment by noobyaran9** [comment]
But getting a dragon heart is impossible without killing the ressurected dragon or chaos dragon. Unless dragon heart is not required in the recipe or else it will be pointless. Chaos dragon would requires at least getting a fully upgraded draconic armour or infinity armour or else it will just wreck you to death in split seconds.

**Comment by Dream-Master** [comment]
@Drobac  that's true Dragon heart is hard to get.

**Comment by Drobac** [comment]
Need to test the if it can be killed using the quantum shield if not then needs a recipe without it

**Comment by Dream-Master** [comment]
Ok i will add a Quest you can do all 7 days for get a dragon egg after killing a Chaos Dragon @Drobac
