### ISSUE TITLE
New Quest Ideas

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1501]
- [x] Quest for the slime Islands and trees
- [x] Sifter Quest
- [x] Circuit Assembler and Cleanroom Quest
- [ ] Low Gravity Quest
- [x] Tinkers Bow and Crossbow quest
- [ ] More Railcraft transportation Quests

**Comment by Ethryan** [comment]
How about a quest for the gem sifter. Sounds rather important.

**Comment by Dream-Master** [comment]
sure was suggetsed allready in a older commit but yes we need.

**Comment by Ethryan** [comment]
A quest for the circuit assembler

**Comment by Dream-Master** [comment]
ye

**Comment by Ethryan** [comment]
Transportation questline with railcraft as base?

**Comment by Dream-Master** [comment]
Yes ok

**Comment by Mofman1** [comment]
Quest for the start of Galacticraft? Tier 4 has 0 guidance on how to get to the moon, the first quest is just "go to the moon".

**Comment by Dream-Master** [comment]
1.5.0.0 have space race quests

**Comment by Dream-Master** [comment]
A new issue will be open for this
