### ISSUE TITLE
Compatibility Fix for WirelessCraftingTerminal and OpenComputers

### ISSUE THREAD

**Issue by bigbass1997** [GTNewHorizons/NewHorizons#1504]
WirelessCraftingTerminal has a bug in it that makes it partially incompatible with OpenComputers' Robots. When a robot attempts to pick up an item/block from the world (such as from breaking blocks or sucking up items), it generates a Forge EntityItemPickupEvent as it should. However in the WirelessCraftingTerminal mod, there is a block of code that listens for this event and at one point tries to get the inventory of the entity that picked up the item. Well Robots don't have a value for that, and so the mod throws a NullPointerException causing the item to drop to the ground instead of the Robot picking it up as intended.

WirelessCraftingTerminal for 1.7.10 of Minecraft no longer has any support, and so I assume the author will not make any new commits for this version. So I went ahead and added a small null-check into the mod and pushed the change to my fork https://github.com/bigbass1997/WirelessCraftingTerminal

The change works as I intended and should not disrupt any functionality of the original mod. I also fixed the build script so that anyone can build the mod using just Gradle and not have to download any libraries.

If you have any questions feel free to ask. I hope this can be put into 1.5 before release.

Dream, if you want me to just give you the jar file so you don't have to build it yourself, just let me know on Discord.

**Comment by Dream-Master** [comment]
@bigbass1997 can you add a binary to your github then i not need it  to compile it.

**Comment by bigbass1997** [comment]
Yep stand by, fixing something.

**Comment by bigbass1997** [comment]
@Dream-Master https://github.com/bigbass1997/WirelessCraftingTerminal/releases/tag/1.8.7.4-bigbass-1
