### ISSUE TITLE
Quests requirements EnderIO

### ISSUE THREAD

**Issue by Haiya-Dragon** [GTNewHorizons/NewHorizons#1506]
Several quests related to EnderIO require the player to make at least the EnderIO Combustion Generator (Quest ID 132) or the Stirling Generator for partial unlocks (Quest ID 131). These quests should be optional as it's quite redundant to have more generators just for RF when EU conversion by cabling suffices.

**Comment by bigbass1997** [comment]
Honestly quests for RF generators should not exist at all. There is no reason to make an RF generator of any kind.

**Comment by Dream-Master** [comment]
if you want to do a seperate Powersystem for Ender IO or GC not using GT power why not. Draconic Evolution is RF based too, same Extra Utilies or Buildcraft and Forestry.

**Comment by bigbass1997** [comment]
But why would anyone want to do that? Even the Stirling Generator with the Octadic Capacitor will only generate 80 RF/t, while an LV tier generator will make the equivalent of 115.2 RF/t. The most the Combustion generator can make is 160 RF/t, and that's when using Rocket Fuel. So I don't see any possible reason someone would want to use EnderIO generators, they are horrid compared to even just LV tier EU generators.

**Comment by Dream-Master** [comment]
@Haiya-Dragon as you can see this Quests all are optional
![image](https://user-images.githubusercontent.com/2970688/27254852-a91bcb2e-5391-11e7-87ee-3dc018a854b3.png)

**Comment by Dream-Master** [comment]
you dont need to do both or what you mean?

**Comment by Haiya-Dragon** [comment]
Look at the 4 quests below, the alloy smelter, sag mill etc. Also the ones on the right dealing with brewing.

**Comment by Dream-Master** [comment]
The Quests in the middel are "or" Quests and they all optional @Haiya-Dragon

**Comment by Haiya-Dragon** [comment]
Yes. but they require at least one of the RF burner quests which is silly.

**Comment by Dream-Master** [comment]
Ok but the Quests are be shown as a square are all optional. So why you not let it out. I dont understand the problem here maybe you explain it a bit and/or make pics about it @Haiya-Dragon

**Comment by Haiya-Dragon** [comment]
I need to do a quest to make a RF powergen which is a weird thing to do when you have automatic EU to RF conversion. But I still have to make one to get access to quests for other Ender IO machines because they depend on quests to make a RF powergen.

**Comment by Dream-Master** [comment]
will look into it later for the 1.6.0.0 update. Need time to read quests and understand what you mean.
