### ISSUE TITLE
Huge Pipes need a Shaped recipes to make it even like GT++

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1507]
Tiny Pipes and Huge Pipes need a Shaped recipes

**Comment by Bryfer** [comment]
Isn't the purpose of them not having shaped recipe to lock these behind MV tier? (MV Extruder)

**Comment by Dream-Master** [comment]
in 1.4.1.1 they have shaped recipes and these was overwritten by the gt update.

**Comment by Dream-Master** [comment]
if some one explain my this code i can add the recipes.

```
                if ((!aMaterial.contains(SubTag.NO_WORKING)) && ((aMaterial.contains(SubTag.WOOD)) || (!aMaterial.contains(SubTag.NO_SMASHING)))) {
                    if (!(aMaterial == Materials.Redstone || aMaterial == Materials.Glowstone)) {
                        long aAmount = aPrefix == OrePrefixes.pipeLarge ? 1L : aPrefix == OrePrefixes.pipeMedium ? 2L : 6L;
                        String aRecipeString1 = aPrefix == OrePrefixes.pipeLarge ? "PHP" : aPrefix == OrePrefixes.pipeMedium ? "PPP" : "PWP";
                        String aRecipeString2 = aPrefix == OrePrefixes.pipeLarge || aPrefix == OrePrefixes.pipeSmall ? "P P" : "W H";
                        String aRecipeString3 = aPrefix == OrePrefixes.pipeLarge ? "PWP" : aPrefix == OrePrefixes.pipeMedium ? "PPP" : "PHP";
                        GT_ModHandler.addCraftingRecipe(GT_Utility.copyAmount(aAmount, new Object[]{aStack}), GT_ModHandler.RecipeBits.MIRRORED | GT_ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | GT_ModHandler.RecipeBits.BUFFERED, new Object[]{aRecipeString1, aRecipeString2, aRecipeString3, 'P', aMaterial == Materials.Wood ? OrePrefixes.plank.get(aMaterial) : OrePrefixes.plate.get(aMaterial), 'H', aMaterial.contains(SubTag.WOOD) ? ToolDictNames.craftingToolSoftHammer : ToolDictNames.craftingToolHardHammer, 'W', aMaterial.contains(SubTag.WOOD) ? ToolDictNames.craftingToolSaw : ToolDictNames.craftingToolWrench});
                    }
                }
```

**Comment by MineAnPlay** [comment]
Bryfer is right. They are supposed to be locked behind the extruder. They never had shaped recipes.

**Comment by Dream-Master** [comment]
why gt++ hav recipes for huge pipes?
Tiny pipes dont have one.

![image](https://user-images.githubusercontent.com/2970688/27247751-f1f05770-52fb-11e7-94cd-4ac083bc9963.png)

**Comment by Dream-Master** [comment]
@Bryfer @MineAnPlay give me any reason why pipes need to be loocked by a mv machine. I add a ways to make springs and other machinestuff to make it shaped so why not pipes.

**Comment by MineAnPlay** [comment]
Because than there really isn't any reason to use extruder recipes. Also it's because tiny pipes have a smaller capacity and you get 2 per ingot and huge ones are the opposite.

**Comment by Dream-Master** [comment]
making 6 double plate is much more work then using 12 ingots in the extruder. Tiny pipes still stay in the extruder because no usefull recipes is free .

**Comment by Bryfer** [comment]
![image](https://user-images.githubusercontent.com/22825059/27247929-dbd774c6-52fd-11e7-8a20-05c8925a4f42.png)
![image](https://user-images.githubusercontent.com/22825059/27247931-e2c3a7e6-52fd-11e7-9e49-f8ff5db2c38d.png)
(1.4.1.1 recipes)
pretty sure these recipes didnt exist when I started this modpack, but I can be wrong, double steel plates is used on huge pipes
but I still think tiny and huge should be mv+

**Comment by Dream-Master** [comment]
@Bryfer but what is the reason for be MV because they bigger and smaller then normal pipes? I guess Gregtech only forget to add thos recipes.

**Comment by MineAnPlay** [comment]
lol Greg never forgets. Most likely to stop early large storage pipes or cheap pipes for when you just need to send a small amount a liquid for a long distance?

**Comment by Dream-Master** [comment]
I will ask him via pm :)

**Comment by Bryfer** [comment]
> @Bryfer but what is the reason for be MV because they bigger and smaller then normal pipes? I guess Gregtech only forget to add thos recipes.

no, because tiny pipe is smaller than small pipe, and huge pipe is larger than large pipe

**Comment by Dream-Master** [comment]
But this isn't a reason for make it extruder only. May father was goldsmith and he can make very tiny pipes with handcrafting. Ok he used most of the time gold and silver.

**Comment by Dream-Master** [comment]
GregoriusT

inactive IC² Dev but still active GT Dev

6 hours agoNew

simply not enough space in the crafting grid and no logical way to craft them with the limited amount of crafting items, thats all. In GT6 only Plastic Pipes are "Extruder only" to my knowledge.(edited)
So no deeper reason only out of recipe parts and crafting variants
