### ISSUE TITLE
Obtainable creative item renaming?

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#1508]
According to me it sounds so cheaty with items or blocks that contain the words creative and are obtainable in survival, any way we can rename them to something that sounds a bit more realistic?

for example:
Steves carts 2:  
Creative Engine => Infinity Engine
Upgrade: Creative Mode => Upgrade: Integrated Infinity Reactor
Creative Hull => Quantum Minecart Hull

**Comment by Dream-Master** [comment]
@Ethryan @Giovanni_NL Thanks
