### ISSUE TITLE
Creative Enerergy Cell has 2 recipes <- Close this

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#1509]
![1](https://user-images.githubusercontent.com/3237986/27252302-34da1fda-535b-11e7-88bc-5e8d136e45f7.png)

The creative energy cell got 2 differnt recipes this is the first one. (Too easy one)

![2](https://user-images.githubusercontent.com/3237986/27252309-528efdfc-535b-11e7-8118-7a392a638ac9.png)
This is the correct one i think. but since both show up 1 should be removed.

Fixed in my fork [link](https://github.com/Ethryan/NewHorizons/commit/73d25b8fe4ad6f0c2b0798d009ccca7e0ddec40a)

**Comment by Dream-Master** [comment]
Can you push oh?

**Comment by Ethryan** [comment]
if i try you get the quests too, can't find how to just push one file

**Comment by Dream-Master** [comment]
ok i will fix
