### ISSUE TITLE
1.5.0.0 Circuits should not use the tier before it.

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1510]
The title explains everything. It just adds up too fast. You need 207k Platinum just for the quantum processors required for a 16 block long Assembling Line. Just a small example.

**Comment by Dream-Master** [comment]
@MineAnPlay how you come to 207K Platinum? Explain it a bit with screenshots.

**Comment by Dream-Master** [comment]
@MineAnPlay write down all material costs and i can rework ciruits a bit.

**Comment by Anarack** [comment]
At minimum the Master Quantumcomputer should require 2 Quantumprocessor Assembly not 12 to follow the recipe pattern setup by other circuits in the computer class.

**Comment by Dream-Master** [comment]
Yes I fixed that it was wrongly added. Later I post a link of 1.5.0.0pre2

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/d8r217c60oamdsr/GTNH-1.5.0.0-pre2.zip?dl=0

**Comment by Dream-Master** [comment]
So circuits reworked.
