### ISSUE TITLE
[Suggestion] Endgame-recipe for Infinite Oxygen Supply

### ISSUE THREAD

**Issue by HellFirePvP** [GTNewHorizons/NewHorizons#1512]
Reminder/Suggestion to add a 9x9 recipe for the creative oxygen tank of Galacticraft.
Item in question is called "Infinite Oxygen Supply".

**Comment by Ethryan** [comment]
something like this?
![temp](https://user-images.githubusercontent.com/3237986/27255949-508b6948-53a9-11e7-893e-f08a68f9e1af.png)
a Quantum tank III in the middle with neutronium plates and tier 8 heavy duty plate, together with small 
infinity fluid pipes and extreme weteware life support circuit bords.

**Comment by Dream-Master** [comment]
yes why not give me the recipes. @Ethryan

**Comment by Ethryan** [comment]
pushing now.

**Comment by Dream-Master** [comment]
k

**Comment by Dream-Master** [comment]
@Ethryan Thanks
