### ISSUE TITLE
Crashing when loading a world?

### ISSUE THREAD

**Issue by z-ach1** [GTNewHorizons/NewHorizons#1520]
This only happened to me today, and it worked wonderfully before this. I am attaching the crash report here, maybe I could have some help?
[crash-2017-06-17_13.20.00-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1082805/crash-2017-06-17_13.20.00-server.txt)

**Comment by z-ach1** [comment]
The version is 1.4.1.1

**Comment by Dream-Master** [comment]
Maybe a dimensions id overlapping. Did you using the standard config from the download?

**Comment by z-ach1** [comment]
yeah, i haven't changed a single thing in the config.

**Comment by z-ach1** [comment]
ok, so i made a few new worlds, and they do not have this issue, only my main world.

**Comment by bigbass1997** [comment]
To me it looks like world corruption of some sort. Has happened to people before. Nothing all that specific in the crash report to really pinpoint the cause.

**Comment by Radst0ne** [comment]
To me it looks like a corruption that causes a rendering issue
@z-ach1 you can try to set you render distance to the lowest and rejoin the world or hookup a server also reduce the view distance to the lowest, grab another account and try to join
But I could be wrong

**Comment by Technus** [comment]
Ye looks like classic world corruption, cannot rebuild data array from file. Something forces negative index while loading.

java.lang.ArrayIndexOutOfBoundsException: -29
at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:26)

**Comment by EvgenijM86** [comment]
Not sure if it will help, but try to completely reinstall this modpack. I also had a crashing issue in some version of this modpack, until I deleted and redownloaded the same version that I had. This has fixed the issue for me.

**Comment by Dream-Master** [comment]
If this problem still exist i reopen it.
