### ISSUE TITLE
issue with the wooden form (Brick)

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1521]
When you use the wooden form (Brick) in recipes, for crafting unfired clay bricks for exemple, the wooden form (Brick) is duplicated.

**Comment by Dream-Master** [comment]
Yes this was posted here 100x times. Its fixed in 1.5.0.0 thanks for info.

**Comment by POPlol333** [comment]
And this is how this guy ended up admin
