### ISSUE TITLE
Change Recipe "Multiblock Tanks... Railcraft Tanks" #45

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1525]
könntest du bitte die Quest "Multiblock Tanks... Railcraft Tanks" #45
von einer Crafting Task in eine Retrieval Task umwandeln?

Da es ja die Möglichkeit gibt dies auch per Assembler herzustellen.

pls change the Quest "Multiblock Tanks... Railcraft Tanks" #45
into a Retrieval Task. 

Since there is possibility to produce this into assembler.

**Comment by Ethryan** [comment]
done a pull request with a fix for this.

**Comment by Dream-Master** [comment]
@Ethryan Thanks
