### ISSUE TITLE
Creosote Wood Block and saws

### ISSUE THREAD

**Issue by Haiya-Dragon** [GTNewHorizons/NewHorizons#1529]
The recipe to turn Creosote Wood Block into Creosote Block Slabs only works with saw. Please add a variant for buzzsaw, chainsaw (lv, mv and hv) and universal spade, like how it works with any planks.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by noobyaran9** [comment]
Please also add it to the cutting machine so it can be automated easier.
