### ISSUE TITLE
Water generation

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#153]
It should be tested, if water generation after you got the water-tank from railcraft and until you can go into RemoteIO or thaumcraft can be replaced by something new, as spamming multiblocks or farms is a "not so ideal" way

Current ways to get water:
- Spam Cactusfarm and Fluid extractor
- Spam Watertanks
- ?

**Comment by Drobac** [comment]
Everfull jar - Thaumcraft
Water sigil - Blood Magic
Currently no good way to bridge the gap between these and water tank without watertank spam or cactusfarm (didnt test viablity of that one)

**Comment by Namikon** [comment]
I build something in my base yesterday:
1x Railcraft Watertank
1x Railcraft HP Boiler (1x2)
1x BlastFurnace, 3x LV Hatch
1x Steam Turbine (LV)
3x LV BatteryBuffer 4-Slot
12x Sodium Battery

It took about 10-15 Minutes once the SteamTurbine refilled the Batteries to a level where I could process another Aluminum dust, and in total it used up 4 Stacks of Charcoal (Charcoal stacks to 64) to process 4 Aluminum Ingots.

This may seem to be useless, and it is indeed not pretty smart to build that, but once we have the new values for turbines, this setup might be a good starting point for the EBF, as it requires less water than the watertank produces.

In terms of "midgame" water production, RemoteIO and Thaumcraft are an option, however i never played with RemoteIO. Have to look into that.

But for the "start" of your early MV/EBF age, one or two RC Watertanks seem to be enough ( With the new steam turbine values )

**Comment by Drobac** [comment]
RemoteIO reservoir seems the only tech solution for water we have atm, but i think it should be adequate untill you get into Thaumcraft and everfull jars. Do you think we need the reservoirs a bit earlier? costs about half a stack of titanium + all the other materials

**Comment by Namikon** [comment]
Not sure, I shall see with the new config values for steam and once I hit MV/HV age

**Comment by Namikon** [comment]
I found a suitable water-gen for every tier, without spamming 20 water tanks on your roof, and as soon as you reach the moon, infinite water is available. Issue closed

**Comment by Dream-Master** [comment]
How?

**Comment by Namikon** [comment]
RemoteIO water source

**Comment by Dream-Master** [comment]
Yes but we need to tier it because remote io need new recipe bvecause op stuff.

**Comment by Namikon** [comment]
You want to nerf the Water source? *rage incomming*

**Comment by Dream-Master** [comment]
This recipes are nerfed by Arch long time ago. Now we have a tiering System and i want that recipes fit in this system.

**Comment by Namikon** [comment]
Well, as you wish. But maybe you should tell people earlier that you're going to redo recipes *before* they start a trial&error phase to find a suitable way of doing things. It took me a few hours to figure that stuff out, time where I could've done something else

**Comment by Drobac** [comment]
Imo i would make the recipe for the reservoir even cheaper. It is damn expensive, just the power requirements to make the titanium needed, which i think is more then half a stack are gigantic at that stage of the game. 
Also it is the only technical solution for water  we got in the pack

**Comment by Teteros** [comment]
Opening as there is still a large gap between LV and EV (RemoteIO Water reservoir).

Other that cacti farms, a [snow farm](https://www.youtube.com/watch?v=m6jyXg0tA0k) may be worth it if #265 is fixed.

**Comment by Namikon** [comment]
Snow golem farm, how did I not see that option.:p and you don't need the smeltery, just use Gt fluid extractor, should work pretty fine. We'll see how the server behaves with a few of those however. It's not the most tps friendly way

**Comment by Namikon** [comment]
Confirmed. Snow-Golem farm is a scalable, easy, early-tier solution to water-gen.
A setup with 4 fluid extractors and one snow-golem can produce about 1 Bucket of water / second.
That is more than enough to supply 2 Large Boilers from Gregtech. And if you need more, just setup 2, 3, 4,... golems.
If you happen to reach MV-age, then you can add 2 8v solar panels to the setup, and the extractors will run for free. (Add a battery buffer to cover the night if you need 24/7 water gen)

Only drawback: You have to be in a snow-biome, or the golem won't create snow patches.
I think we really need to tier witchery to LV age, as this is the second thing where you need the biome-change system (The other one is the ocean-bee thing)

**Comment by Dream-Master** [comment]
Ok fixed partial via Snow golems.

**Comment by Teteros** [comment]
Fun fact, snow patches seem to create in most biomes.
Below is a demonstration video of a swampland snow golem farm:

[![Automatic snow golem farm using a vacuum hopper](https://cloud.githubusercontent.com/assets/5067989/11798235/f13aec4c-a2c0-11e5-9fba-50b11ff6259b.png)](http://youtu.be/rzbygFkyM3M "Automatic snow golem farm using a vacuum hopper")

I wonder if [water tanks in a jungle/swamp](http://ftb.gamepedia.com/Water_Tank) could compete?

**Comment by Dream-Master** [comment]
:+1:
