### ISSUE TITLE
You smell like a Distillery quest 768 reward

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#1530]
![20170619103344](https://user-images.githubusercontent.com/25171639/27267867-12ce941e-54de-11e7-9757-7ebb035b3685.png)
wrong in 1.5.0.0pre

**Comment by Dream-Master** [comment]
ok will look inside.

**Comment by Dream-Master** [comment]
@FallDark Did you know what was original in there?

**Comment by FallDark** [comment]
Cracked Heavy Fuel Cell and Cracked Light Fuel Cell

**Comment by Dream-Master** [comment]
Thanks will replace it with new cells.
