### ISSUE TITLE
[1.5.0.0pre1]Naquadah Reactrors replaced by Circuit Assemblers

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/NewHorizons#1531]
This happens when upgrading from 1.4.1.1 to 1.5.0.0pre1, on Nq Reactor Mark IV & Mark V.
Using the "pre1" version form dropbox.

**Comment by Dream-Master** [comment]
Oh thats not god. Can you send me pics from 1.4.1.1 naq reaqctor and from 1.5.0.0 assembler with id.
thanks.
@antifluxfield

**Comment by antifluxfield** [comment]
![naq1 4a](https://user-images.githubusercontent.com/17354844/27286443-bae1c776-5532-11e7-838c-f3bc9dd83e66.png)
![naq1 4b](https://user-images.githubusercontent.com/17354844/27286444-bb0262ce-5532-11e7-9816-116dde547b1d.png)
![naq1 4c](https://user-images.githubusercontent.com/17354844/27286445-bb1147c6-5532-11e7-8848-8b5b59ed8844.png)
Items and blocks in 1.4.1.1
![naq1 5a](https://user-images.githubusercontent.com/17354844/27290021-7fb1d810-553e-11e7-8218-41b2595da435.png)
![naq1 5b](https://user-images.githubusercontent.com/17354844/27290037-890b47c0-553e-11e7-86bb-90c05938efcd.png)
![naq1 5c](https://user-images.githubusercontent.com/17354844/27290045-8dc79282-553e-11e7-8c4d-2e332e3b354b.png)
Items and blocks in 1.5.0.0
@Dream-Master

**Comment by Dream-Master** [comment]
@antifluxfield ok list me please the id's from all circuit assembler in 1.5.0.0 and all naq generators in 1.4.1.0 And 1.5.0.0. Thanks

**Comment by antifluxfield** [comment]
All the machines are the sub-block of <gregtech:gt.blockmachines>.
Circuit Assemblers in 1.5.0.0 are having the meta id from 1180 to 1187, from LV to UV, 8 tiers in total;
For Nq Reactors, they take 1190~1192 for Mk I to Mk III, in both 1.4.1.1 and 1.5.0.0; for Mk IV and Mk V, they takes 1180 & 1181 in 1.4.1.1, but 1188 & 1189 in 1.5.0.0 .

**Comment by Technus** [comment]
I set it like that to maintain compatibility with bloodasp version
suffer the idea of adding new blocks inside gt5u meta te range by dream

**Comment by Technus** [comment]
on servers we can notify staff about that, on sp you can fix it yourself

**Comment by Technus** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java#L1268
**Bloody code**
