### ISSUE TITLE
HV mixer recipe 'conflict' - Nichrome dust and Ultimet dust

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1533]
Any HV (or higher) mixer that has ever mixed nichrome dust refuses to make any ultimet dust. This probably has to do with the fact that ultimet dust also has both nickel and chrome in it's recipe. Currently the best workaround seems to be breaking and replacing the machine, making this a rather low-priority problem. Middle-clicking the mixer in creative mode seems to save data that is lost on being broken - any mixer placed from this middle-clicked mixer also cannot make ultimet dust.

**Comment by DietmarKracht** [comment]
Same With HSS-S. If you have Mixed Osmiridium first you will never be able to mix HSS-S cuz it needs both osmium and iridium too

**Comment by Dream-Master** [comment]
If there are free slots I can add a circuit but I guess I need to add more slots to the mixer

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28412090-62ec757e-6d43-11e7-9e3f-a01ca93f6f2e.png)
![image](https://user-images.githubusercontent.com/2970688/28412107-7248b4f6-6d43-11e7-8415-d68bf93bcb3e.png)
![image](https://user-images.githubusercontent.com/2970688/28412150-865ae7ca-6d43-11e7-9897-39764e02a34e.png)


Works well and tested.
