### ISSUE TITLE
[1.5.0.0pre1]Missing Duplication Recipe for Raw Crystal Chip

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/NewHorizons#1535]
All the Crystal-series and Wetware-series circuits requires Crystal Processing Unit, which should be produced from Raw Crystal Chip, at least 1 for each circuit.
But the Raw Crystal Chip only have this recipe, crystallizing Emerald or Olivine in Europium:
![crystal](https://user-images.githubusercontent.com/17354844/27290259-423e796a-553f-11e7-98a7-8d9892e0e666.png)
That's really an expensive but kind of unproductive recipe.

There is an alternitive recipe like this in the original repo:
![crystal2](https://user-images.githubusercontent.com/17354844/27290865-1c840f26-5541-11e7-9d5a-446437af87a2.png)
Which according to [this issue](https://github.com/Blood-Asp/GT5-Unofficial/issues/932), is intended.
So should those high-tier circuits just be that expensive in GTNH, or we just forget to add this recipe? Or we have some other idea for producing these items?

**Comment by Dream-Master** [comment]
I remove this recipe because you can double your circuits without produce them in space. Yes the 10% chance is a bit mean so maybe I can do there something

**Comment by antifluxfield** [comment]
@Dream-Master 
Double? Hmmm... how to double them? I just can't find any extra recipe for them, for example, the Crystalprocessor. All its recipes requires 1 Crystal Processing Unit (or Crystal SoC, can only be produced by engraving Crystal Processing Unit), and then trace back to that Raw Crystal Chip.

**Comment by Dream-Master** [comment]
@antifluxfield if you llok at Blood Asps sheet you will see some circuits need europium to process. I can set the chance to 100% but i won't remove the europium if you mean that. If you have another recipe which use europium i am fine with it.

**Comment by Dream-Master** [comment]
@antifluxfield 
```
Blood-Asp commented on 8 Mar
An invert was missing. So they did work everywhere besides space...

The 1 CrystalPU = 9 raw crystal chip recipe is intended. The europium recipe is only needed to start with crystal chips, after that they can be cheaper duplicated.

```

Blood asp speak from duplication too. I dont like this recipe so make a better one i will add it.

**Comment by antifluxfield** [comment]
@Dream-Master 
Well, that 10% recipe is not important. What I mean is we need some duplication recipe. It will be fine if you are going to add an alternative recipe.

**Comment by Dream-Master** [comment]
Ok a duplication recipe suggest a good one or make a pic with ingredients i could add. @antifluxfield

**Comment by antifluxfield** [comment]
What about adding a Crystal Chip Mold?
For example: 
Raw Crystal Chip + Manyullyn Plate => Crystal Chip Mold, in the Forming Press;
Emerald/Olivine Plate + Crystal Chip Mold(won't consume) =>Raw Crystal Chip, in the Forming Press;
And later we can use the Raw Chip to produce other items.

**Comment by Dream-Master** [comment]
Or another sulution where put the crystal cp in a forge hammer get a amount of crystal parts and using them in the autoclave to grow more raw crystals so you need only all 9 crystal chipts to make a new one.

**Comment by antifluxfield** [comment]
That sounds violent for a crystal XD
Seems that's a better plan, cause it's closer to Blood's original recipe. Using your solution is OK.

**Comment by Ethryan** [comment]
why not use the sawmill instead of the forge hammer, create 2 thinner pieces that can be used in the autoclave to slowly regrow it back to it's original form?

**Comment by Dream-Master** [comment]
@Ethryan i dont want that you can create a infinite chain of reproduction process which only one item. Ok i can add europium to the Autoclave to grow the crystal yea thats possible but i will add it to low gravity too.
