### ISSUE TITLE
Circuit Assembler progression

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1541]
1.5.0.0pre 

putting the this here just make sure you didn't miss it from the discord

This is due to HV circuit assembler and beyond requiring one tier too high of circuit at to be crafted by the previous tier of circuit assembler.

Currently HV requires Elite circuits that can only be created in a minimum of a HV circuit assembler, this pattern repeats on all circuit assemblers HV and up.

Circuit assemblers circuit requirements should be...
LV------circuitGood
MV-----circuitAdvanced
HV-----circuitData                <-------------change starts here
EV-----circuitElite
IV-----circuitMaster
LuV---circuitUltimate 
ZPM--circuitSuperconductor
UV----circuitInfinite

**Comment by Dream-Master** [comment]
ok will look nto it.
