### ISSUE TITLE
Crystal Circuit Recipe Pattern

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1542]
1.5.0.0pre

 1. Crystalprocessor Assembly Cost

The Ultimate Crystalcomputer does not require 2 Crystalprocessor Assembly's and so does not follow the recipe pattern set by most other circuits which is 2 assembly -> 1 computer.

 2. Crystalprocessor Mainframe 

Requires 8 Ultimate Crystalcomputer while the previous mainframe requires 4 computer class parts and the mainframe ahead requires 8. I would suggest making it require 6 Ultimate Crystalcomputer to act as a stepping stone between the rest of the mainframe class circuits and the final mainframe class circuit.

If you want I will split this into 2 different issues

**Comment by Dream-Master** [comment]
ok will look into it.

**Comment by MineAnPlay** [comment]
All of the mainframes require 4 when they should require 2 circuits.

**Comment by Dream-Master** [comment]
i change that allready too.

Test 1.5.0.0pre2
https://www.dropbox.com/s/d8r217c60oamdsr/GTNH-1.5.0.0-pre2.zip?dl=0

**Comment by Anarack** [comment]
Issue 2 is fixed by test 1.5.0.0pre2 but issue 1 is still present in new test version.

**Comment by Dream-Master** [comment]
yes ik need to fix first issue.

**Comment by Dream-Master** [comment]
fixed.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/1a01ab39eb52f01f422f485fe85ec60fbeb0eaac
