### ISSUE TITLE
Mod Suggestion(s) GT VeinLocator and DetravScannerMod

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1543]
**GT VeinLocator**

There's a guy who made a simple mod for those who don't want to dig a hole for ore-hunting: https://github.com/GWYOG/GTVeinLocator. It adds some scanners for locating or prospecing ore viens and can even automatically create waypoints in JourneyMap.
I have no idea about its balance in this modpack; but if you do want to add a portable scanner like that, this mod could be a good choice.

Orginally found by @antifluxfield an posted in #1339 

**DetravScannerMod**

DetravScannerMod is similar but with gui
https://github.com/Detrav/DetravScannerMod

Orginally found by @3131CuNb

@Dream-Master in #1339 
> i tested the mod. Tier one only show position of veins, tier 2 write down empty waypoints to jorneymap so you cant see is there a vein or not and only tier 3 shows the exact vein or shows empty.
If you have this tool you never will use the sismic prospector. This 3 vein locators are better then ov and od scanner so i will tier them behind.

**Comment by noobyaran9** [comment]
I think the current OD/OV scanner have no issue with them. By the time u can make those scanner, you could probably dig really fast down to bedrock anyway. And those scanner have quite abit of range actually, at least the OV one does. I could scan upto 1k~2k ores around me in the middle of the vein. Its not as small as SwardGames said in #1339
> Currently, the OD/OV Scanners are not very well suited to GregTech oregen, scanning for ores in a 9/25 block large cube around you.

**Comment by Dream-Master** [comment]
I will only add the advanced locator and tier it IV/Luv. It will use the OV scanner in the recipe.

**Comment by 3131CuNb** [comment]
DetravScannerMod is similar but with gui
https://github.com/Detrav/DetravScannerMod

**Comment by Dream-Master** [comment]
@3131CuNb is this mod for Gergetch too ?

**Comment by 3131CuNb** [comment]
![2017-06-20_16 48 10](https://user-images.githubusercontent.com/13436239/27479771-8bffc300-5815-11e7-881c-dba630fd7a7f.png)

**Comment by 3131CuNb** [comment]
you can see which ores are in the chunk

**Comment by Dream-Master** [comment]
Will look at it later

**Comment by Dream-Master** [comment]
This scanner looks like a more advanced variant maybe need to add both mods

**Comment by Bryfer** [comment]
I think we should go with the DetravScannerMod and skip the GT VeinLocator
because the Scannermod looks way more badass, and is actually working ingame without journeymap.

**Comment by Dream-Master** [comment]
Ok i will test the mod today.

**Comment by Dream-Master** [comment]
@Bryfer @noobyaran9 @3131CuNb I need someone make fixes for this mod make it compatible with the newest gt version

**Comment by Dream-Master** [comment]
Ok make this mod GTNH Compatible.

**Comment by Bryfer** [comment]
@dream-master
Why did this issue get closed?
The devscanner mod added too many other things, but what happend to GT vein locator?

**Comment by Dream-Master** [comment]
We get a new mod soon with only the scanners.  The other scanner isn't that good in my opinion.

**Comment by KaneHart** [comment]
Not sure if I can suggest anything here. But I personally like an "OPTION" To allow a low level scanner with not even need for ore info to be used right from the start in a sense. I'm thinking some sort of basic hammer and something else that you could tap on the surface just to detect if there is something underground.

I would say a big chunk of us kind of got tired of GTNH Because of the boring ore grind. I personally would be back in a flash if I could right from the near start do this without having to do any 3 chunk mine 3 chunk mine type system. 

Right now I personally just fine it's a pure boring grind there is no education to it at all it's just a pure long long grind and I think GTNH Already offers more exciting and interesting grinding without making the user have to search forever for ores.

That being said I love mining a ton and enjoy it even with GTNH Style it's relaxing for me. My issue like I said 100% the searching.

Hope we can make 2.0 amazing!

**Comment by AntidermisMC** [comment]
It it actually already possible to hit the ground with a GT Hammer to get an idea of what's behind the rock.

**Comment by KaneHart** [comment]
I thought that was super close wise. I'm thinking something more on the surface like a prospector or something idea without having to dig.

**Comment by Dream-Master** [comment]
@KaneHart in the version 1.5 or 2.0 whatever we call it there are a LV and a MV miner same as IC2 Miner. It dig out ores where you put it on the Ground like a pump. It is available in after you can make steel and steam. I guess this makes digging out ores more automate-able.

**Comment by Dream-Master** [comment]
GT Scanner are added at LuV Tier
