### ISSUE TITLE
[1.5.0.0pre]Recipe glitch

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/NewHorizons#1544]
![image](https://user-images.githubusercontent.com/17354844/27370740-7b8b1f5a-5690-11e7-80ea-67886b7154a6.png)
Glyceryl Trinitrate recipe in the Large Chemical Reactor, missing Nitration Mixture as ingredient.

**Comment by Dream-Master** [comment]
ok will look into it.

**Comment by Dream-Master** [comment]
@JohannesGaessler
Are  Nitration Mixture from yor addon or fro another mod?

**Comment by JohannesGaessler** [comment]
Nitration Mixture has already existed in GT before I changed anything.
I merely added a corresponding Material so you get a Fluid Cell in NEI.
This bug seems to exist outside of GTNH.

**Comment by Dream-Master** [comment]
Anything we can do against it? @JohannesGaessler

**Comment by JohannesGaessler** [comment]
You can commit the fix i pushed onto OilRefining.

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
done
