### ISSUE TITLE
Add Cassiterite or Tin to Deep Dark

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#1548]
I'm not sure if it was intentionally done, but it seems odd that every other ore that you need in large quantities is available in the Deep Dark while tin is excluded, unless I missed something in the ore spawn spreadsheet.

**Comment by bigbass1997** [comment]
Which spreadsheet were you looking at? (Can you provide a link to it?)

**Comment by finkledoodle** [comment]
This was after looking at the original ore spawn spreadsheet linked on the GTNHT discord and the new spreadsheet provided by MineAnPlay. I can't provide a link to the old spreadsheet as it links to the new one, but here is the new link https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1941759795 in both cases though, I did not see a form of Tin or Cassiterite spawn in that dimension.

**Comment by bigbass1997** [comment]
The link to the old one works fine http://bit.ly/gtnh-oremixes (though I would recommend not using it anymore).

But yes it does appear that you are correct. Someone may need to double-check the tin yielding ore mixes in the config just to be sure.

**Comment by Dream-Master** [comment]
@bigbass1997 The "old" one is from me. I update it from time to time so the other is from MineAnPlay.
About the issue i will look into it.

**Comment by Dream-Master** [comment]
And one thing about ore mixes. If one mix use allready (primary and secondary)use it cant be used a second time. The deep dark dim mixes have alle the same size and if i cant add cassetrite or tin a second time how i can add it. I will look into it after work.

**Comment by Dream-Master** [comment]
ok Ore 824 is Casseterite and not been used in a oremix primary or secondary so i am able to add it.

**Comment by Dream-Master** [comment]
Tin is not possible

**Comment by bigbass1997** [comment]
@Dream-Master 

> @bigbass1997 The "old" one is from me. I update it from time to time so the other is from MineAnPlay.

I'm not really sure why you are telling me this.. I very well know that you had made the old spreadsheet. MineAnPlay rewrote practically the entire thing due to how much was outdated or misspelled on the old spreadsheet. I even made an announcement about it in Discord days ago.

But okay, originally issue solved then.
