### ISSUE TITLE
Quest Choice Reward with only one option

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1549]
In mv tier the "Clay electrolysing" quest has a choice reward, but you can only choose a lootbag.

**Comment by Dream-Master** [comment]
@alphaNOVAircraft ? I dont understsnd the issue here?

**Comment by alphaNOVAircraft** [comment]
sry, first issue xD  pressed enter to early, so no description

**Comment by Dream-Master** [comment]
np will look into it @alphaNOVAircraft

**Comment by Dream-Master** [comment]
Not anymore

![image](https://user-images.githubusercontent.com/2970688/27498636-470dfc76-5860-11e7-8503-c15087746043.png)
