### ISSUE TITLE
New item: Adamantium Claws for Drobac

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#155]
:) Unbreakable! Rawr!

**Comment by Dream-Master** [comment]
;-)

**Comment by Drobac** [comment]
RAAAAAAAAWR I AM WOLVERINE!!! Well i hopefully will be

**Comment by Drobac** [comment]
Also add a regeneration effect while they are equipped for the extra Wolverine factor

**Comment by Dream-Master** [comment]
Good idea.

**Comment by Dream-Master** [comment]
Is this a thing or can we close this until we add this item ?

**Comment by Namikon** [comment]
It's on my todo list but since this requires 3D Modeling, I haven't done it yet. Can be closed, I won't forget it
