### ISSUE TITLE
Missing Item Name

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1550]
1.5.0.0 pre2

The block, gt.blockmetal8.13.name, used to make Blood-Soaked Ichorium Block does not have a regular name.

**Comment by Dream-Master** [comment]
Pics please

**Comment by Dream-Master** [comment]
I guess ichorium isn't registered right

**Comment by Anarack** [comment]
![recipe](https://user-images.githubusercontent.com/20565115/27488789-e8ab5cc6-57fd-11e7-8e88-4f3eb4f6ff9a.png)

**Comment by Dream-Master** [comment]
Ok will loonk into it.
