### ISSUE TITLE
Add bastnasite ore and salt ore to deep dark

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1552]
As this is the best source of fluorine and chlorine and u need alot of them in 1.5 update.

**Comment by Dream-Master** [comment]
Ok will check if that is possible.

**Comment by Drobac** [comment]
You get chlorine from salt, which is easy automatable (water bucket + pot). But i agree with bastanite or any other source of flourine

**Comment by Drobac** [comment]
Put a bastanite, neodymium vein. Don't think it spawns in the deep dark. And graphite if possible

**Comment by noobyaran9** [comment]
Probably graphite + salt.

**Comment by Dream-Master** [comment]
We reach now 90 ore mixes so I can add 9 more that's it.

**Comment by Dream-Master** [comment]
Bastnatite is not possible because primaray and secondary ore mix allready.

**Comment by Dream-Master** [comment]
I add Lepodolite and Neodymium as mix.

**Comment by Dream-Master** [comment]
Graphite not possible

**Comment by Dream-Master** [comment]
Ok addd Salt and Rock salt
