### ISSUE TITLE
Pure tear quest cooldown

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1554]
Pure tear quest will be repeatable every week (7 day cooldown)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27515914-dac082f0-59ae-11e7-87cb-f91b4620ffbf.png)
So every 7 days Server time or 7 Days real gameplay you can get a new Pure Tear with this Quest. Not mess up with warp.
