### ISSUE TITLE
CF spray is missing 

### ISSUE THREAD

**Issue by unggod** [GTNewHorizons/NewHorizons#1555]
Playing the pre 1.5 version at dirthuts server.
i am able to craft CF backpack but the recipe for CF spray is not showing or is disabled. Weird.

**Comment by Dream-Master** [comment]
ok will check it. Why dirthuts using a not ready made version ?

**Comment by Dream-Master** [comment]
Today i posted a stable beta version.

**Comment by Toperoco** [comment]
DirtHuts is on 1.4.1.1, not 1.5.0.0pre. CF sprayer recipe is missing for both however

**Comment by Dream-Master** [comment]
Ah ok ic2 updates and fix somethings. Will look into it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27552962-86b701b0-5aa9-11e7-8ef3-c848caf9423c.png)
![image](https://user-images.githubusercontent.com/2970688/27552968-8aed847a-5aa9-11e7-8bcd-e100967d0851.png)
but i could add a gt version

**Comment by unggod** [comment]
that is the cell and cf powder for it, but we cant make the tool to actually spray cf on the floor, we can make the backpack to store the liquid cf, but no tool to spray it. I believe the tool cf sprayer was som,ewhat disabled by acident , because the backpack is tweaked and dont work with any other type of tool.

**Comment by Dream-Master** [comment]
You need a IV Fluid Canner for it because you have to fill it once 80 Buckets of fluid.
I add more recipes.

**Comment by Dream-Master** [comment]
You can fill it in the ic2 olid fluid canner
