### ISSUE TITLE
Issues with steel tools in Tier 2

### ISSUE THREAD

**Issue by grumpymood** [GTNewHorizons/NewHorizons#1556]
GT new horizons quest book under 32 EU.  Error in the quest "One block mining is so Old School"  Second part is retrieval of steel hammer however in the book it is listed as ?fsteel Hammer causing it not to detect the steel hammer in my inventory.  The other two quests to forge steel tools have the same issue.

**Comment by Bryfer** [comment]
this problem is already reported (in ver 1.4.1.1)
Issue is fixed in version 1.5
#1366 

In the future please use Github's search features to look for similar issues to the one you want to post, before posting. But thank you anyways for bringing this to our attention.
