### ISSUE TITLE
Copper Ore

### ISSUE THREAD

**Issue by Vulca22** [GTNewHorizons/NewHorizons#1557]
Hey , don't know if its only me but i can't find any Copper ore or chalcopiryte , i even installed mekanism so i can try all over the world find some using the dictionary of both and nothing

**Comment by Bryfer** [comment]
are you looking in the correct chunks?
http://www.gtnewhorizons.com/wiki/m/41469370/page/Mining_Guide
more information about different veins can be found here
https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1941759795&range=A12

This spreadsheet link can be found on discord
https://discord.gg/XC6QgeE

Feel free to ask more questions about mining in #help in discord if you hate more questions about mining tactics :)

**Comment by Vulca22** [comment]
yes , i tryed manually in chunk by chunk and then digital miner and nothing , i tryed in more then 400 chunks , i spent all night around that 
PS: i installed digital miner after the chunks were loaded so it don't worldgen mekanism's copper ore

**Comment by MineAnPlay** [comment]
Digital Miner won't mine GT ores (They are tile entities).

**Comment by Dream-Master** [comment]
Digital Miner?

**Comment by Dream-Master** [comment]
@Vulca22 i close this because i not get a replay here.
