### ISSUE TITLE
[1.5.0.0] Game crash when creating 2nd world.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#1560]
So, I was trying to spawn a world with specific biome near player spawn location and noticed that game crashes immediately after creating 2nd world.

crash details - https://pastebin.com/xWhVc9FD

How to repeat:
1) Launch minecraft.
2) Create new world. Save and exit.
3) Create another new world.
4) Game crash.

So far I have tested it 3 times and it crashed 3 out of 3 times. I also tried complete reinstall of modpack (deleting all files and redownloading) - it did not help.

I did not encounter this bug in 1.4.1.1 - I was able to try out ~10 worlds without any crash. So this is probably not a problem with my environment.

**Comment by Dream-Master** [comment]
I did the same with my 1.5.0.0 dev world no issues at all. Save 3 worlds.

**Comment by EvgenijM86** [comment]
To use dev version I just need to copy script and config directories from github?

**Comment by EvgenijM86** [comment]
Crash occurred on 4th time. On 5th time it did not occur and I was able to save 4 worlds. The only thing that changed is that I closed a wine program. Going to test more. Maybe the problem was in my environment.

**Comment by EvgenijM86** [comment]
For some reason I can't replicate this anymore. Didn't know that opening and closing other programs can have such an effect.

**Comment by Dream-Master** [comment]
@EvgenijM86 is this fixed/gone now?

**Comment by EvgenijM86** [comment]
Yes.
