### ISSUE TITLE
Suggestion: Beef Wellington too easy

### ISSUE THREAD

**Issue by CrusherX83** [GTNewHorizons/NewHorizons#1563]
A couple of the best foods in the game require no pam's kitchenware like Beef Wellington, Epic Bacon, and Sausage in bread. All these can be made within 15 minutes of starting the pack (assuming you can find maple trees for the sausage in bread) and are all Feast meals. Maybe modify them to use pam's kitchenware to make then a little bit harder to cook.  Just a thought.

**Comment by Dream-Master** [comment]
good idea. will do.

**Comment by MineAnPlay** [comment]
Just keep it as is. Don't make food a hassle.

**Comment by noobyaran9** [comment]
Make those food requires neutronium to cook. Because neutronium is too easy.

**Comment by Bryfer** [comment]
![image](https://user-images.githubusercontent.com/22825059/27627674-ea5365b2-5bec-11e7-9121-4e811968c2f7.png)
https://www.gordonramsay.com/gr/recipes/beef-wellington/
![image](https://search.chow.com/thumbnail/1280/800/www.chowstatic.com/assets/recipe_photos/29112_beef_wellington.jpg)

Pretty sure I could make this meal with just some cooking still (cries) ..
All I would need is an bloody steak, some dough and the mushroom filling.
If anything would be done to this recipe its the reduced hunger (but it looks really good)
or replace mushroom and spinach with an item that would be more fitting to the REAL LIFE recipe. (Keep in mind we are actually playing a game..)

Im pretty sure I will not need any tools when combining dough + steak + mushroom paste

I dont think this recipe has to change.

**Comment by Dream-Master** [comment]
Why not in a UV Mixer :P

**Comment by CrusherX83** [comment]
When I made this post I didn't mean it should be gated behind any tier. My only thought was maybe to make it require a pan, pot, or something from the kitchenware as nearly all the lesser recipes call for. Having these items require pam's kitchenware (pan, pot, etc.) would encourage players to do the cooking questline to make them.

**Comment by Dream-Master** [comment]
Sure i understand what you want to change

**Comment by Proha5** [comment]
I never craft pam's food. Because best food is IC2 can. It easer to create, and no limit for eating.

**Comment by richardhendricks** [comment]
The hunger/saturation values on Beef Wellington should be cut in half, IMO. Compared with Eggplant Parmesean and other similar difficulty recipes, it is way too filling.

I think Pam said she is going to rebalance her recipes, but I think that's only for her 1.12 branch.

**Comment by Dream-Master** [comment]
Yes 1.7.10 will not developed anymore. Sadly the source code is available since 1.8.9
