### ISSUE TITLE
LuV and higher Emitters/Sensors require Neutronium

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1564]

**Comment by Dream-Master** [comment]
And? I need more expain text here. @MineAnPlay

**Comment by Drobac** [comment]
Neutronium can only be acquired on T6 planet plus, also requires ZPM power to smelt

**Comment by Dream-Master** [comment]
Ok will change the recipe use it

**Comment by Dream-Master** [comment]
fixed
