### ISSUE TITLE
Add tinker construct aluminium dust to EBF smelting

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1566]
As title.

**Comment by Bryfer** [comment]
Tico Aluminum is spelled without that 2nd I
GT Aluminium is spelled with two I


What method did you use to get Tico Aluminum? and in that case would it be better if that recipe was giving the correct aluminum instead?

You can use the Tico smeltery to transform Aluminum into Aluminium by creating Raw Aluminum and macerating it.

**Comment by noobyaran9** [comment]
Sag Mill non GT variant of aluminum ore gives TiCo aluminum dust.

**Comment by Bryfer** [comment]
![image](https://user-images.githubusercontent.com/22825059/27633409-580ece90-5bff-11e7-8b59-34310b6ce0f7.png)
possible solution(s)
craft it into small/tiny pieces and then back into dust
or smelt in smeltery and extract raw aluminum and macerate the raw aluminum

hopefully @Dream-Master will be able to modify it so it will give the correct aluminium dust in the future

**Comment by Drobac** [comment]
Aluminum dust is ore dicted, it will switch to GT alu when held in hand

**Comment by Dream-Master** [comment]
What need to changed here?

**Comment by MineAnPlay** [comment]
Also you can only use Aluminum (not Aluminium) for GT++ recipes.

**Comment by Dream-Master** [comment]
This is a bug which need to be fixed soon by Alkalus.

**Comment by Dream-Master** [comment]
Doing Exchange recipe would be enough.
