### ISSUE TITLE
Iron nuggets shapeless

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#1570]
It seems like you can make iron nuggets by hand from an iron ingot:
![iron_crafting](https://user-images.githubusercontent.com/16925725/27658780-6a03f6fa-5c51-11e7-9e7e-09b31aefca4d.PNG)

Most nuggets you make by smelting the ingots in a furnace, even iron works:
![iron_smelting](https://user-images.githubusercontent.com/16925725/27658800-8056fd44-5c51-11e7-8c98-4ed1f46b4b4b.PNG)

Imo the shapeless recipe should be removed since it leads to accidentally crafting nuggets when you shift click and a tool breaks (for example).

MineAnPlay actually found more ingots that you can craft to nuggets by hand, some are even missing the GT like furnace recipe they _should_ have.
I think a consistent way of making nuggets would be the best and the furnace recipes work just fine and are more realistic than breaking an iron ingots into nuggets by hand.

**Comment by dutsky** [comment]
+1 for this suggestion. Several times i have nuggets because of accidental shift-click :)

**Comment by Dream-Master** [comment]
Yes nuggets need to be removed. Will do later

**Comment by Dream-Master** [comment]
@WarlordWossman Are there more Nuggets then Iron?

**Comment by Dream-Master** [comment]
Thauminite Nugget 7631
Lead Nugget 4430:4
Silver Nugget 4430:3
Tin Nugget 4430:2
Copper Nugget 4430:1
Steel Nugget 5231:33 (Rezept geht nicht, wird aber angezeigt)
Lead Nugget 5450:4
Tin Nugget 5450:3
Copper Nugget 5450:2
Steel Nugget 5450:1
Iron Nugget 5450
Vibrant Alloy Nugget 5641:4
Pulsating Iron Nugget 5641:3
Awakened Draconium Nugget 6655:1
Draconium Nugget 6655

**Comment by WarlordWossman** [comment]
Yeah that's the list of nuggets you can craft by hand that I found. I don't have all the Thaumcraft research tho so you might check for metals I couldn't check yet.

**Comment by Dream-Master** [comment]
K
