### ISSUE TITLE
Bricked Blast Furnace work with Bronze Plated Bricks 

### ISSUE THREAD

**Issue by aLegoz** [GTNewHorizons/NewHorizons#1571]
![xlaa0hj](https://user-images.githubusercontent.com/10736349/27662516-c875c8d4-5c66-11e7-8f7e-6408a1081c71.png)

**Comment by Dream-Master** [comment]
@JannesGaessler

Any idea ?

**Comment by JohannesGaessler** [comment]
Of course it's not gonna work with Bronze Plated Bricks.
The description quite clearly states to use Firebrick blocks, does it not?

**Comment by Dream-Master** [comment]
The machine looks like be in active status so I guess yes.

**Comment by JohannesGaessler** [comment]
Sorry for the previous comment, I misread the issue title.
I pushed a bugfix: 6a9e0756d6709491c2f5afc98e74cdb89fbe8d21
