### ISSUE TITLE
Wrought Iron Ingot Creation Issue

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1575]
1.5.0.1

Wrought Iron nuggets can not be compressed into a wrought iron ingot using a GT compressor blocking progression. 

This can recipe can be done in the ic2 compressor but can not be performed in any GT compressor.

**Comment by MineAnPlay** [comment]
For now just use an alloy smelter with ingot mold.

**Comment by ko5h** [comment]
its not work http://i.imgur.com/ubgxeCk.png

**Comment by aLegoz** [comment]
**Can only be created in IC2 Compressor:** 
``` 
// --- Wrought Iron Ingot
Compressor.addRecipe(<ore:ingotWroughtIron>, <ore:nuggetWroughtIron> * 9);

// --- Quartzite Plate
Compressor.addRecipe(<gregtech:gt.metaitem.01:17523>, <gregtech:gt.metaitem.01:2523>);

// --- Lazurite Plate
Compressor.addRecipe(<gregtech:gt.metaitem.01:17524>, <gregtech:gt.metaitem.01:2524>);

// --- Sodalite Plate
Compressor.addRecipe(<gregtech:gt.metaitem.01:17525>, <gregtech:gt.metaitem.01:2525>); 
```

**Its work good in GT Compressor:**
```
// --- Certus Quartz Plate
Compressor.addRecipe(<dreamcraft:item.ChargedCertusQuartzPlate>, <dreamcraft:item.ChargedCertusQuartzDust>);

// --- Nether Quartz Plate
Compressor.addRecipe(<gregtech:gt.metaitem.01:17522>, <gregtech:gt.metaitem.01:2522>);
```

**Comment by Ethryan** [comment]
Using the ore dictionary as an output for a minetweaker recipe is usually not a good idea, it tends to error when it try to add that recipe.

**Comment by Dream-Master** [comment]
If you using a newer mintweaker version it works.
