### ISSUE TITLE
LV Electric Motor Multiple Recipes

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1576]
1.5.0.1 

Currently Electric motors have 2 different recipes, one requiring iron rods and the other requiring steel rods. Not sure which recipe is the intended one.

**Comment by Dream-Master** [comment]
both are crafting recipes

**Comment by Dream-Master** [comment]
So they are in Assembler.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27766211-466fb75e-5ec9-11e7-9dd8-5fe85ae2df50.png)
![image](https://user-images.githubusercontent.com/2970688/27766213-4c8f2980-5ec9-11e7-9feb-5e2e24854dc9.png)
![image](https://user-images.githubusercontent.com/2970688/27766215-511aa182-5ec9-11e7-9d36-8ef9f79de240.png)
