### ISSUE TITLE
recipe conflict in casting forms

### ISSUE THREAD

**Issue by nroe1337** [GTNewHorizons/NewHorizons#1577]
The recipe for Casting Form (Coinage Mold) 7159 is the same as the recipe for Casting Form (Gear Shape) 7004, making it impossible to get Casting Form (Gear Shape) 7004 without cheating. This is needed for the Extruder Shape (Gear)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27765836-b565754c-5ebd-11e7-996d-8a29700d1f76.png)
![image](https://user-images.githubusercontent.com/2970688/27765837-c56e3de8-5ebd-11e7-8309-7fed32828e03.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27765860-5afe00f0-5ebe-11e7-9d39-733c4a1f7ab0.png)
![image](https://user-images.githubusercontent.com/2970688/27765861-5f2c83cc-5ebe-11e7-8644-4800e1a381ab.png)
recipe changed
