### ISSUE TITLE
Wrought Iron and Aluminium Production Issue

### ISSUE THREAD

**Issue by SuperGenoXP** [GTNewHorizons/NewHorizons#1579]
I know the problem with wrought iron nuggets not being able to be compressed into ingots has been brought up, but raw aluminum also cannot be macerated into aluminium dust. So without advanced machinery like fluid solidifier, you can't progress.

**Comment by Dream-Master** [comment]
@SuperGenoXP did you mean the Tinkers raw Alu ?
![image](https://user-images.githubusercontent.com/2970688/27749484-1e5758b2-5dd4-11e7-8123-55af431a4df0.png)

**Comment by SuperGenoXP** [comment]
Yes, if you try to pour molten aluminum into an ingot cast it turns into raw aluminum. But you can't macerate that into aluminum dust that you can make into an ingot by the electric blast furnace.
![2017-06-30_12 52 50](https://user-images.githubusercontent.com/29802046/27749995-2f2ca278-5d93-11e7-90bf-e682c76d63d4.png)
Pic related is broken recipe

**Comment by Dream-Master** [comment]
i dont have this recipe but i will add it into core mod.

**Comment by Bryfer** [comment]
Avoid putting aluminium in the smeltery in the first place

**Comment by Dream-Master** [comment]
yes but there was a recipe before and now it seems to be gone.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27765714-87a2c668-5eb9-11e7-802d-db8c1932f1c1.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27765806-9a3fee2e-5ebc-11e7-8c6e-854afcf45f23.png)
