### ISSUE TITLE
Change Adv. Solar panel recipe to the new ore gen

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#158]
Advance solar panel can use Titanium since uranium is unavailable earlier, Hybrid solar Tungsteel and Ultimate Hybrid solar panel is the Chrome tier and Quantum Solar Panel Iridium.

**Comment by Dream-Master** [comment]
Yes have to change the recipes.

**Comment by Dream-Master** [comment]
Any suggestion witch Tier the Panels have to in?

**Comment by Namikon** [comment]
Drobacs suggestions regarding materials seems to be ok. Question is if solar power shall be allowed at all.

A totally different idea could be: Allow solar power only on GalacticCraft planets, as it is hard enough to build a functional base up there, and therefor making the panels cheaper to craft. Haven't spent much time up there, so I can't really tell what's a good thing to do and what is not

**Comment by Dream-Master** [comment]
Yes solar panels have to be allow but maybe forbidden on the overworld with Block Limiter.

**Comment by Drobac** [comment]
The only reason you would use those solar panels on other planets is if you make a full base on another planet, for oxygen production the galacticraft solars are better.

**Comment by Dream-Master** [comment]
done
