### ISSUE TITLE
Not possible to get advanced circuits if you arent already in hv

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1581]
You need for the Randome Access Memory Chip (wafer) a green sappphiere lens, witch you can only produce in a lathe with minimun 480 eu voltage, so you already need a hv lathe.

**Comment by Dream-Master** [comment]
i think some lenses can be moved back to mv.

**Comment by Dream-Master** [comment]
Ok lenses changed now.

**Comment by Dream-Master** [comment]
Some Flawless gem recipe are overridden.
