### ISSUE TITLE
emptying the input tank of GT machines

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1582]
I put a wrong liquid in an assembler and i can't figure out a way to empty it without voiding it.
Why the GT pumps can only retreive fluids in output tanks? It's really annoying...

**Comment by Dream-Master** [comment]
input slots can only voiding fluids with the plunger. No way for suck the fluid out.

**Comment by boubou19** [comment]
Well i guess i have to be more carefull next times. Thanks for the reply.
