### ISSUE TITLE
Sodium Persulfate isnt produceable

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1583]
NEI tells you you can use a Sodium dust and a Sulfur dust + 4000 L oxygen dust to produce Sodium persulfate in a chemical reactor with 30 eu / t, tryed it but my machin doesnt start producing, evveryting is build up correct

**Comment by Dream-Master** [comment]
Here the way you produce Sodium Persulfate

![image](https://user-images.githubusercontent.com/2970688/27765818-11f43d94-5ebd-11e7-9fcc-0e3aab1d976d.png)
![image](https://user-images.githubusercontent.com/2970688/27765819-1bf51818-5ebd-11e7-8329-344fc42cb86f.png)

**Comment by Dream-Master** [comment]
Idk why you see old recipes.
