### ISSUE TITLE
Integrated Circuit Quest ( on the way to adv circuits) (quest issue)

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1585]
In the quest Integrated circuit you need to have 64 long tin rods for the quest, but you only need 64 normal ton rods for the circuit you need to craft later
Just change long rods with noral rods

**Comment by MineAnPlay** [comment]
Yea since we made circuits cheaper XD

**Comment by alphaNOVAircraft** [comment]
Ergaenzung: Du hast in der quest angegeben das man good circuit boards braucht, allerdings bracuht man lediglich basic circuit boards zur herstellung, und nur 32 normale tin rods
