### ISSUE TITLE
For Diodes molten glass needed, but you need mv fluid extractor to get molten glass

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1586]
Um dioden herzustellen beötigt man molten glass, dieses kann man am anfang nur aus quartzite bekommen, da glass dust zu schmelzen mv ist, wuerde vorschlagen das du einfach glass dust von mir aus bei mv laesst, aber schon geschmolzenes fertiges glas nimmt

**Comment by Dream-Master** [comment]
I will add molten glass from tico so you can make it lv age.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27765175-613808e8-5eab-11e7-9f57-1f51a270472b.png)
![image](https://user-images.githubusercontent.com/2970688/27765180-6e10e3dc-5eab-11e7-8250-8d8aa33ecc18.png)
