### ISSUE TITLE
Blast furnace quest issues

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1588]
Second stage of quest asks 14 iron plate, but we need 28 iron plates to create 4 iron furnaces in third stage of quest.

Last stage of quest ask to have 36 firebricks AND Bricked Blast furnace. But to have both items we need to craft 40 firebricks in fact. So this stage should divided or stages 4-9 should be recalculated.

**Comment by Dream-Master** [comment]
Thanks for testing will change it too.

**Comment by Dream-Master** [comment]
You need 32 bricks for walks plus 4 for the furnace. Why 40?

**Comment by Dream-Master** [comment]
28 iron plates is right

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27764963-3662a4ca-5ea6-11e7-8808-c86c7d0dc4b5.png)
28 iron plates fixed.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27764967-6c36f5ba-5ea6-11e7-9d2f-09ae20700007.png)
![image](https://user-images.githubusercontent.com/2970688/27764968-6efcb988-5ea6-11e7-979b-5c2f4beebbb7.png)
change it too
