### ISSUE TITLE
Quest Flint and Steel

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1589]
First stage of the quest - crafting task. Maybe change it to retrieval? I can't use steel plates from forge hammer, because it's not crafting and i can't use flint I get before quest.

**Comment by Usernm0** [comment]
And why ask to craft only 2 steel rod, when we need 3? One for small spring and two for small gear.

**Comment by Dream-Master** [comment]
Yes this Quest I need to change too.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27764945-aebb2dc6-5ea5-11e7-9dee-7362c6962b87.png)

fixed in dev.
