### ISSUE TITLE
Quest your first bone bow

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1590]
In quest your first bone bow on stage 1 we need to craft two bowstring patterns, but in stage 3 we need to craft fearther fletching. I think on first stage one bowstring pattern should be fletching pattern.

**Comment by Dream-Master** [comment]
Yes I fix this all ready. Will be in 1.5.0.2 update.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27764918-3583b5e0-5ea5-11e7-80cf-75050ccd2da4.png)
fixed in dev.
