### ISSUE TITLE
H2S to Sulfuric Acid in chemical reactor not working

### ISSUE THREAD

**Issue by General-Bacon343** [GTNewHorizons/NewHorizons#1591]
Cannot create sulphuric acid in chemical reactor as shown by NEI. 
![2017-07-01_00 15 54](https://user-images.githubusercontent.com/27801159/27759643-98f2e99c-5df2-11e7-91b2-28052742dea7.png)
I have sufficient power to the chemical reactor. 
![2017-07-01_00 15 58](https://user-images.githubusercontent.com/27801159/27759644-aa93d198-5df2-11e7-8a33-32ffc9db67fc.png)
And I am using the correct programmed circuit.

**Comment by Dream-Master** [comment]
Will  test it later

**Comment by Proha5** [comment]
If you use 1.5, then its not bug. Version 1.5 change hemistry. Sulfuric acid recipe changed.
But why your nei show old recipe?

**Comment by Dream-Master** [comment]
This should be the only recipe be shown in Nei
![image](https://user-images.githubusercontent.com/2970688/27764909-fac634aa-5ea4-11e7-9db1-d8bc16dc7529.png)
![image](https://user-images.githubusercontent.com/2970688/27764910-fe7079c6-5ea4-11e7-844c-7e583e33b97a.png)
![image](https://user-images.githubusercontent.com/2970688/27764912-0300f15a-5ea5-11e7-91e4-d6540a7579ba.png)

If you see others something wrong with the config or the version you are using.
