### ISSUE TITLE
Disable showing old thermal centrifuge recipes in NEI.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1592]
1.5.0.1 showing detailed recipes for thermal centrifuge. IC2 window not actual. How disable old recipes?

**Comment by Dream-Master** [comment]
@Proha5 maybe @Blood-Asp can asnwering this question.

**Comment by Blood-Asp** [comment]
The GT5 main branch did that by coping all IC2 recipes into GT recipes and then removing all IC2 recipes so they no longer show up. As GTNH uses their own version of GT i do no know if that was also done or not.

**Comment by Dream-Master** [comment]
@Blood-Asp can you show me the commit that change it?

**Comment by Blood-Asp** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/7a8067868daffcc6d2fe44c557007ba839980fc3#diff-f0b042824ea4cd8d5da51fb662592938
https://github.com/Blood-Asp/GT5-Unofficial/commit/5c5aad452228255815deab8ff3bcb85e147ef63b#diff-f0b042824ea4cd8d5da51fb662592938
These are the main ones, but there are at last 5 more that are part of it and do smaller or bigger fixes.

**Comment by WarlordWossman** [comment]
Would that mean eu/t values in NEI for all the machines shared with IC2? Because it kinda sucks that you can't see if for many recipes.

**Comment by Dream-Master** [comment]
So far I see yess

**Comment by Blood-Asp** [comment]
Exactly. that was the main reason for the change

**Comment by Dream-Master** [comment]
I try to add all recipes to the new gt recipes. If i anything missing just let me know.
