### ISSUE TITLE
Quest "Wired, weird?!" appears to be outdated

### ISSUE THREAD

**Issue by Flyboi55** [GTNewHorizons/NewHorizons#1594]
For the quest, "Wired, weird?!" in the steam age, it tells you to make copper cable.  However, this can not be done without an assembly machine.  This is most likely due to the recipe for circuits changing in the 1.5 update to not require copper cable, rather it requires copper wire.  Think this is just a remnant of the old recipe.
v1.5.0.1

**Comment by Flyboi55** [comment]
![2017-07-01_21 41 55](https://user-images.githubusercontent.com/29827089/27766666-37505bd4-5ea6-11e7-935a-2d2de6541a56.png)
![2017-07-01_21 42 15](https://user-images.githubusercontent.com/29827089/27766668-39857b78-5ea6-11e7-998e-c85595034d4a.png)
![2017-07-01_21 42 16](https://user-images.githubusercontent.com/29827089/27766669-3b350ab0-5ea6-11e7-9328-a49a2b87cdf8.png)

These are the only recipes for copper cable.

**Comment by Dream-Master** [comment]
@MineAnPlay @Flyboi55 how does you made copper cable in 1.4.1.0?

**Comment by Bryfer** [comment]
2 rubber bars + copper wire (alloy smelter)
Or assembling machine. 

This quest needs to be modified to fit the new circuit recipe since the old quest was a pre-quest for lv circuit

**Comment by Dream-Master** [comment]
ok will look into it.

**Comment by Dream-Master** [comment]
@Flyboi55 try to hit the command ingame /bq_admin default load

I guess your Quests are not up to date.
