### ISSUE TITLE
GT++ metal crafting

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1595]
GT++ metals that require cobalt and aluminium dust are only craft-able with the tinkers construct variant of the dust.

**Comment by Dream-Master** [comment]
reported to @Alkalus allready.

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues/89

**Comment by draknyte1** [comment]
This is now resolved.

**Comment by Dream-Master** [comment]
So far i see yes. Will look now into it.
