### ISSUE TITLE
Basic Circuit change

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1596]
Change Alloy Cables to Alloy Wires

**Comment by MineAnPlay** [comment]
Why was this?

**Comment by Dream-Master** [comment]
Because i never see that you put cables on circuits, Wires are better here

**Comment by MineAnPlay** [comment]
Dream everything is not about realism... Just make it use cables... It will force people to do automation

**Comment by Dream-Master** [comment]
No circuit use cables exept the basic and the good one. Sure i can change it back but i guess people do cables anyways because they connect machines. We can vote about it.

@MineAnPlay @bigbass1997 @Namikon @Technus @Drobac @Bryfer @Jajax

**Comment by Drobac** [comment]
would prefer to use wires, circuit crafting already forces you to do a lot of automation. The additional step of making cables would just increase the complexity and cost of the already painful to make circuits

**Comment by MineAnPlay** [comment]
Hmm then only make the hand crafting require cables then.

**Comment by Namikon** [comment]
Suggestion to not spent time on voting for stuff like using cables or wires; Instead focussing on the real game-breaking issue of entire ore veins as requirements for one high-end circuit (as discussed for about 5 hours on discord)

**Comment by Dream-Master** [comment]
:P
