### ISSUE TITLE
Missing macerator recipes in 1.5.0 and above

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1599]
I realize most of the macerator recipes now show up in NEI under the pulverizer, but there are some that are just plain missing.  Didn't mention this before because I thought it was a known issue.  Two that I know of: 
![2017-07-02_13 40 47](https://user-images.githubusercontent.com/26042867/27772357-5a945838-5f2e-11e7-8b32-1bce4127aaad.png)
![2017-07-02_13 41 24](https://user-images.githubusercontent.com/26042867/27772359-73f957a6-5f2e-11e7-9cf3-d1a21ff5cc37.png)

Putting these items in the macerator does nothing now.

**Comment by Dream-Master** [comment]
Sunnarium is updated.

**Comment by kris449** [comment]
you will read github but not discord?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27803985-bb4f0a48-602c-11e7-84b8-36ba12a2c04b.png)

**Comment by Dream-Master** [comment]
let us hope oterh ic2 machines not have the same issues.
