### ISSUE TITLE
Suggestion for recipie change (diode / vacuum tube)

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1600]
Es würde sich anbieten, dass man die rezepte für die diode und die vacuum tube in den thermionic farbikator packt, da dieser von haus aus glass verbraucht und auch von der herstellung näher an die realistische herstellung der bauteile herankommt, und es würde forestry mehr integrieren

**Comment by Dream-Master** [comment]
I not will remove gt recipe only make forestry recipe a bit cheaper
