### ISSUE TITLE
[Rezept] Forestry Farm erst ab HV

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1601]
Forestry farmbraucht Emerald Electron Tubes welche long Emerald rods brauchen welche HV sind, da diese nur HV Presicion Laser oder LV Sifter mit 12% sind . da die farm momentan die einzigste ist welche mit den AgriCraft corps klarkommt evtl veränderung nötig.

**Comment by MineAnPlay** [comment]
Use the sifter you will need it anyway. It's more efficient.

**Comment by Dream-Master** [comment]
Emeralds are everywhere so i guess build a sifter is not so complicated. I will add some Quests for it.

**Comment by Dream-Master** [comment]
@PapaTim68 I got 7 flawless Emeralds, and two exquisite(from one stack purified ore so 32 Emerald Ores), can make 9 long emerald sticks from it and for a control block you need only 4 Tubes = 8 long sticks.
