### ISSUE TITLE
Unpacker doesnt  give back rubber

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1602]
Man braucht fuer alle kabel gummie, aber wenn ich islolierte kabel in den unpacker packe, bekomme ich keine rubber sheets mehr zurück

**Comment by noobyaran9** [comment]
What version are u on right now?

**Comment by Dream-Master** [comment]
Es ist unmöglich zu sagen wie jemand Kabel macht. Es gibt 11 Rezepte im Assembler. Reverse Rezepte gehen nur wenn sie eindeutig sind. Ich sehe hier keine Möglichkeit was zu machen .
