### ISSUE TITLE
Quest(s) AE system, EV

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1604]
Quest "Applied Crafting" #182
The first stage of this quest wants you to retrieve one crafting unit and one 1k Crafting Storage.
The problem here is that if you do them in order, then you will craft an crafting unit, then use it to craft the 1k crafting storage, and therefore you need to craft another crafting unit to complete the quest.

"Cables"  #184
Same kind of problem as described above

"Drives" #180
the 1k ME storage component you get 3 over after completing 

also worth noting is that the Molecular Assembler requires Clear Glass from tico. should this be replaced with vanilla glass instead?

Tested in Version 1.4.1.1 as far as I can see this problem seems to exist in 1.5 aswell

**Comment by MineAnPlay** [comment]
You can make Clear Glass with the EBF.
