### ISSUE TITLE
GT Buffer cores

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1605]
Crafting of the cores requires each previous core tier, making the cost exponentially higher. Needs new recipes that dont require previous tiers

**Comment by eXoShini** [comment]
Pretty sure that's how it's supposed to be. Later on it's all about automation, you won't be crafting by hand as much.

**Comment by eXoShini** [comment]
There is plenty stuff that requires previous tier component like Solars

**Comment by MineAnPlay** [comment]
Drobac is right... It gets VERY expensive. It's just a large energy buffer.

**Comment by Drobac** [comment]
It's the same issue with circuits, they require the tier before them, and the one before that. When you get to ev/iv circuits the cost gets ridiculously high for one circuit

**Comment by Dream-Master** [comment]
Will look at the buffers.

**Comment by Dream-Master** [comment]
@Drobac This are Gt++ recipes lets ask @drykenet1 if he can change it or i can add our own recipes.

**Comment by draknyte1** [comment]
I don't see what's so expensive about it usually. They're already been listed for new recipes, it just wasn't a high priority. 

Let me see what I can do.

**Comment by draknyte1** [comment]
Any suggestions for Recipes?
I'm a tad stumped and would like to get this sorted before Saturday.

**Comment by Dream-Master** [comment]
@Drobac @MineAnPlay Any suggestions here? For me the recipes are ok.

**Comment by Drobac** [comment]
Id suggest putting the battries of the appropriate tier instead of the Buffer cores. Not sure if GT++ adds batteries that are ZPM+. If it doesn't then perhaps battery buffers of that tier

**Comment by Technus** [comment]
or battery chargers instead of cores?

**Comment by Dream-Master** [comment]
Ok it use a hv casing wich make no sense to me. Gate it to hv is a different thing

**Comment by Sudoloo** [comment]
it seems these things are worth eighty of the relevant battery for that tier with the only drawback being the circuit itself and the whole exponential issue. makes no sense, that they store so much without chemical means. i say that these things are probably a bit generally too good. i propose that these items get viewed as a tier-step-down item where you use them when building machines of an earlier tier. perhaps have each core take a machine block two tiers higher, using the LV recipe as a base, replace the circuits with batteries matching that tier, make the thing take a single super conductor of the output tier and one of the second or third best cable for the same tier as its battery voltage, finish it with a coil from either the original or the middle tier,

sample recipe; LV, Hv machine block/casing, 2 hv lithium battery, kanthal/nichrome heating coil, 4x red stone alloy wire, 1x gold cable, fill holes with plates.

sample recipe; MV, EV machine block/casing, 2 sunnarium battery, nichrome/tungstensteel heating coil, 4x super conductor MV cable, either plates or LV cores as filler.

i figure the super conductor requirement keeps them from being too cheap, so the stepping up of costs in a tiered fashion might not be necesary, rather just making new cores directly could be fine. maybe requiring something tiered and molten in an assembler could increase the hassle a bit if my suggestion is still not enough.

**Comment by Dream-Master** [comment]
@Sudoloo thanks for suggestion will see what I can add.

**Comment by draknyte1** [comment]
I don't see where this is an issue?

**Comment by Dream-Master** [comment]
The capacity is no hight that i think a nerf would be nice.

**Comment by Dream-Master** [comment]
we can reopen it
