### ISSUE TITLE
Empty Sulfur Dioxide Cell [1.5.0.2]

### ISSUE THREAD

**Issue by eXoShini** [GTNewHorizons/NewHorizons#1609]
Using empty cell on bc Tank with Sulfur Dioxide doesn't consume the gas from Tank but consumes empty cell and gives Sulfur Dioxide ic2 cell which appears to be empty:
- Can't be used in electrolyzer recipe
- Extracting from fluid canner gives back just empty cell
- Can't be used on tank to fill it with it

There is GT variation of Sulfur Dioxide Cell which works fine.

**Comment by Dream-Master** [comment]
Pics please that i know the items. @ghoulsblade

**Comment by eXoShini** [comment]
![2017-07-04_23 39 46](https://user-images.githubusercontent.com/14859263/27843397-631dce9e-6113-11e7-875d-98107715b046.png)
![2017-07-04_23 47 35](https://user-images.githubusercontent.com/14859263/27843437-b37097be-6113-11e7-95e8-3eb168365431.png)
![2017-07-04_23 47 52](https://user-images.githubusercontent.com/14859263/27843455-ea45c494-6113-11e7-8ed8-77d291556aea.png)

**Comment by Dream-Master** [comment]
Buildcraft and Railcraft Tanks consume cells, cans. Better using a Super Tank or a tank from gt++ and fill cells there. Better then klick on BC/RC Tanks with cells. @eXoShini

**Comment by ghoulsblade** [comment]
i havent played gtnh in the last few weeks, but in the past i noticed desync issues with cells used on buildcraft tanks and the upgraded versions. try opening a chest or relog to see the empty cells you get back from transfer, or use unversal fluid cells for transfer. If that doesnt help you can also use fluid canner to fill and empty cells and either greg pipes or fluid transposer or endior fluid conduits.

**Comment by ghoulsblade** [comment]
Note that universal fluid cells can be rclicked and shift-rclicked on single greg pipes, but the capacity of one piece of placed pipe is as much mb as its transfer rate, so use steel or bigger pipes for at least 1 bucket capacity unless you explicitly want partial filling

**Comment by richardhendricks** [comment]
Please file new ticket if this is still an issue with the latest revision.
