### ISSUE TITLE
Ectoplasm from HEE drop rate seems way too low

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1610]
Getting ectoplasm here seems extremely difficult. Reading the in game guide for HEE, it says that breaking a log with a face on it gives a 60% chance to drop ectoplasm. However, I've broken around 200 Logs with faces on them, and only received 3 ectoplasm. Unlocking and creating the dragon amulet alone is difficult, but getting the ectoplasm itself seems to be extremely rare. Is this intentional, or could I be doing something wrong? needing 16 for a quest, this drop rate seems too small

**Comment by Dream-Master** [comment]
If there is not config file option for set it i  dont see a chance to change it. If you are a coder you can fork HEE repo. If not open up a issue ther please.

**Comment by Dream-Master** [comment]
https://github.com/chylex/Hardcore-Ender-Expansion/issues
