### ISSUE TITLE
Salis mundus not crafting [1.5.0.2]

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1612]
Thaumcraft-03-Alchemy.zs
// --- Salis Mundus
Macerator.addRecipe(<Thaumcraft:ItemResource:14>, <Thaumcraft:ItemShard:6>);

in game - http://i.imgur.com/9lGKbwp.png

best regards

**Comment by kris449** [comment]
Add that to #1599 please Dream

**Comment by ko5h** [comment]
maybe need update craftweak\gttweak for import gt machine (analog ic2)?
https://github.com/GTNewHorizons/NewHorizons/blob/9bf22ba0250bafc1a552a6d0ceee552322a867e5/scripts/Thaumcraft-03-Alchemy.zs#L407

in pack version mods CraftTweaker-1.7.10-3.0.12, GTTweaker-1.7.10-1.1.1

**Comment by Dream-Master** [comment]
Allready fixed in in version 1.5.0.3 avaibale soon.
