### ISSUE TITLE
New quests re: bricked blast furnace

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#1614]
With the introduction of the bricked blast furnace, might I suggest making the steam macerator a required quest and gating the multiblock quest for the bricked blast furnace behind it and a new quest to find a lapis vein?

Reason for this being: you need a macerator to make stone dust and you need to have located a lapis vein to have access to calcite ore/calcite dust in the bronze age.

**Comment by Dream-Master** [comment]
good idea will add.

**Comment by MineAnPlay** [comment]
Also add Gypsum (Basaltic Mineral Sand).

**Comment by Dream-Master** [comment]
K
