### ISSUE TITLE
no smelting

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1616]
![image](https://user-images.githubusercontent.com/25811344/27845475-0a2630ca-6130-11e7-82e4-a17a28d81596.png)
 
this magnetite can not be smelted, dont know where i have mined it tho....

**Comment by Ghengis88** [comment]
same item id as regular magnetite

**Comment by Ghengis88** [comment]
1451:5870

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/27846342-deac48d8-6136-11e7-8658-ebe85a00ffc9.png)

**Comment by Dream-Master** [comment]
Normaly magnetic ore are not in any mix!?

**Comment by bigbass1997** [comment]
@Dream-Master That is normal Magnetite ore.. Not sure what made you think otherwise.

The issue being reported is that the ore block is not smelting in the electric furnace, hence the description in the post

> this magnetite can not be smelted

The damage value on the ID notes that this is for sure Magnetite ore, by the number 870. The number 5 in front of 870 notes the variant of the block that the ore generated into (stone, netherrack, granite, etc), in this case it looks like marble.

**Comment by MineAnPlay** [comment]
Is it just the marble variation or also basalt too?

**Comment by Drobac** [comment]
Its the same issue we had with ores before, some of the variant (marble,endstone) werent being recognized in the recipes

**Comment by Ghengis88** [comment]
this might be an old ore, i decided to smelt all magnetite in my ME system and found that stack left in the multismelter, it shows no way of smelting in NEI either.

**Comment by Dream-Master** [comment]
Old ore? Yes I read magnetic not magnetite.

**Comment by Ghengis88** [comment]
drobac said that this was a issue before, thought that if i mined the ore befor this was fixed maby that particular stack still had the same issue.?

**Comment by Dream-Master** [comment]
New Magnetite dont have this issue @Ghengis88  ?

**Comment by Ghengis88** [comment]
dont know, i would need to find magnetite in the same type of block, but dont know what the block is...
but all my other magnetite worked fine

**Comment by Dream-Master** [comment]
It loks like Marbel and Basalt ore works different then the others.

**Comment by Dream-Master** [comment]
Works now tested.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34320812-e54c4114-e801-11e7-9e03-8b555627acdc.png)
