### ISSUE TITLE
BQM repeatable quest glitch

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#1617]
Noticed this glitch a few times, with a few quests. Any of the repeatable quests seem to not work when trying to do them more than once. Once I do it once, it works just fine, but trying to do any of them a second time breaks it. It won't detect any new mobs killed, or tasks done, and I need to relog to fix it. I have never had it work, and always had to do it like this

**Comment by Dream-Master** [comment]
@benstuwie please report it to original repo.

**Comment by Dream-Master** [comment]
https://github.com/Funwayguy/BetterQuesting/issues

**Comment by richardhendricks** [comment]
Seems to work fine now?  At least the Kill all the Things quests seem to work OK for me.
