### ISSUE TITLE
Suggestion, rotor's

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#1618]
i suggest changing the cost of making rotors in assembling machine from 16 molten tin to 18 molten tin.
This is becous there is no easy way to get 16, (bolt's are 18, wires are 72) so there will always be some leftover fluid in the assembling machine, only way around this is making 9 rotors, 9*16=144 and then you use 1 ingot, otherwise you sooner or later need to pull you plunger out and clean up.
making the cost 18 would make construktion of rotors much more simple and less time consuming, even tho making it cost "more",

**Comment by Dream-Master** [comment]
sure.

**Comment by Dream-Master** [comment]
I think you mean molten Alloy, Tin and lead. I change it to 18, 36 and 54.

**Comment by kris449** [comment]
16 is the amount you get from a tiny pile/nugget/round etc.  How is that hard to get?

**Comment by Bryfer** [comment]
@kris449
16 is 144/9. (Tiny pile, nugget) yes. Smelting tiny piles everytime you would craft an rotor would work. But it would be really annoying.
Normally the assembling machine uses 1-4 full ingots, 1/2 an ingot or 1/4 of an ingot. This suggestion is for the rotors to follow this logic and use 1/8 of an ingot instead of 1/9

(Values in my example is based on tin. Not lead or soldering alloy)

**Comment by MineAnPlay** [comment]
Change it back :P. Use tiny piles of dusts.

**Comment by Dream-Master** [comment]
@MineAnPlay Seriously ?

**Comment by MineAnPlay** [comment]
Well you could keep change it if you want.

**Comment by Dream-Master** [comment]
What is right 16 or 18 ?

**Comment by Bryfer** [comment]
I agree with ghengis on this one.

All other recipes inside the assembling machine is following the same logic. 1-4ingots, 1/2 ingot, 1/4 ingot, 1/8 ingot etc.
While the rotor is using 1/9 of an ingot(tiny pile, nugget). But it's really annoying to have that little bit of tin/lead/alloy inside the machine after using it. 
By changing​ the recipe to change 1/8 instead it will reduce alot of annoying plumbing of assembling machines.

I'm aware that some people has dedicated tin/lead/alloy assembling machines. 

Anyway. I really think that all the recipies should follow the same logic system. Which the rotor in assembling machines does not. There might be more recipies not following this logic aswell. But none of them is comming to my mind right now. If there is more recipies, then I think these should be changed aswell.

**Comment by Dream-Master** [comment]
@Bryfer thanks for feedback

**Comment by kris449** [comment]
Yes, I explained this to mineanplay also, he just likes to be difficult.

**Comment by Drobac** [comment]
Agreed with Ghengis and Bryfer, small change but saves on resources

**Comment by Dream-Master** [comment]
k
