### ISSUE TITLE
Some 1 EU/t recipe (Need improvement)

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1620]
Please make the recipe below faster and reduce the time taken to make them. 

![2017-07-06_12 01 38](https://user-images.githubusercontent.com/13598309/27895135-1ef2daee-6243-11e7-924a-cb2fa0a8cbe5.png)
Something like 16 EU/t and takes 2.5s to make.

![2017-07-06_12 02 31](https://user-images.githubusercontent.com/13598309/27895136-1ef55c7e-6243-11e7-89e4-2c424fbd9ff7.png)
Something like 8 EU/t and takes 2.5s to make.

![2017-07-06_12 02 49](https://user-images.githubusercontent.com/13598309/27895137-1efb936e-6243-11e7-845f-fa89546388ea.png)
Something like 16 EU/t and takes 2.5s to make.

**Comment by Dream-Master** [comment]
This are recipes added by Blood Asp or Gregorius him self. Better asking them why they need so long time. There are more recipes using very low voltages but need a long time to process.

**Comment by Dream-Master** [comment]
@noobyaran9 recipes with concretes need longer redstone torche i change.

**Comment by MineAnPlay** [comment]
Change the other recipes too please since it's just vanilla redstone stuff. With these speeds people won't ever use it.

**Comment by Dream-Master** [comment]
No conceret needs to harden. Maybe used at hv because 10 sec

**Comment by DietmarKracht** [comment]
Just use faster Machines
