### ISSUE TITLE
Super chest

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1621]
Super chests aren't showing the ammount of items that is in them. Quantum chests work just fine.

http://imgur.com/a/WUnyC

**Comment by noobyaran9** [comment]
If u put a storage bus on them, it only shows items on ME system. Doesn't matter how much u have in them. This happens for both super chest and quantum chest.

**Comment by Drobac** [comment]
i know in ME it only shows a stack, but in the interface of the chest itself it doesnt show how much items it contains. It just says 0 but i can pull the exact ammount of items in it out

**Comment by Dream-Master** [comment]
@Drobac Quantum chests show the amount?

**Comment by Drobac** [comment]
http://imgur.com/a/WF0rg As you can see on the left side of the interface it shows the exact ammount of items in the quantum chest. in the SS in the original post it shows zero items although there are few thousand logs in there

**Comment by Dream-Master** [comment]
@Technus 
maybe i did yome copy past errors here. Can you check code please. Thanks
