### ISSUE TITLE
ExU transfer pipe upgrade is too expensive

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1622]
![2017-07-06_20 58 10](https://user-images.githubusercontent.com/13598309/27912220-a2666ddc-628e-11e7-9159-88a882c40bad.png)
Why not just make them a QED recipe and have a cheaper recipe like 4 red alloy plate , 4 diamond and 1 stainless steel gear? 
Translocators are so much cheaper and transfer much faster with/without the glowstone dust upgrade.

**Comment by Dream-Master** [comment]
sure i can change this recipe.

**Comment by MineAnPlay** [comment]
Because ExU will be OP with to much upgrade :)

**Comment by noobyaran9** [comment]
>Because ExU will be OP with to much upgrades :)

I understand how OP is it. But that recipe is just too expensive. You can gate it behind QED and have no way to automate it.

**Comment by Dream-Master** [comment]
@MineAnPlay any new recipe suggestions? The idea put it in the QED is good.

**Comment by MineAnPlay** [comment]
Hmm just do 4 red alloy plates 4 diamond plates 1 stainless steel gear. But IMO should stay as is or may be only be QED :) .

**Comment by Drobac** [comment]
QED is a bit  late for them imo, at QED tier you can already craft enough ender io conduits that ExU become obsolete. Imo would be better to use aluminum instead of diamond plates and a steel large gear. (diamonds take forever to cut at LV/MV tier). After those tiers Ender io conduits become available and think most people prefer using those

**Comment by MineAnPlay** [comment]
The only thing is ExU can be made to be faster then any other pipe and like Ender IO you can use fluids/items in the same pipe.

**Comment by Drobac** [comment]
Yea but that requires the speed upgrades and those aren't cheap. Think its a good trade-off. Basics being cheaper, but upgrade being expensive

**Comment by Dream-Master** [comment]
Ok so no QED recipe and a cheaper recipe ?

**Comment by Drobac** [comment]
Imo yes
