### ISSUE TITLE
Tier 1 rocket engine uncraftable in 1.5.0.2

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1623]
In version 1.5 the tier 1 rocket engine requires an Partially filled fuel canister. This item is uncraftable. It seems possible to get one by filling it just partially tho. but this is just messy to do.

1.5.0.2 recipe
![image](https://user-images.githubusercontent.com/22825059/27923709-99f62e30-627f-11e7-90eb-496d358ac39f.png)
1.4.1.1 recipe
![image](https://user-images.githubusercontent.com/22825059/27923733-aa5e668e-627f-11e7-9821-62b3d250b6e2.png)

**Comment by Dream-Master** [comment]
1.5.0.3
![image](https://user-images.githubusercontent.com/2970688/27924162-a1e64372-6280-11e7-89ef-45260aab2d83.png)
