### ISSUE TITLE
[Quest] Coins

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1624]
Creativ Modifier Tinkers für Quest Coins

**Comment by DragScorpion** [comment]
All Aura Nodes for The Dark Wizard Coins

**Comment by DragScorpion** [comment]
Hives or Frames for Beekeeper Coins

**Comment by DragScorpion** [comment]
Spawn Eggs for The Survivor Coins

**Comment by Bryfer** [comment]
More coins suggestions can be found in the comments of #1469 and #1202

**Comment by Dream-Master** [comment]
@Bryfer This are not suggestions this are complaints.

**Comment by Bryfer** [comment]
@Dream-Master 
Did you actually read the comments of #1469 and #1202 

@finkledoodle
![image](https://user-images.githubusercontent.com/22825059/28351485-7cfa2626-6c50-11e7-9e08-64371b1ade18.png)
@MineAnPlay

![image](https://user-images.githubusercontent.com/22825059/28351493-8ea6d874-6c50-11e7-9750-4a698215d763.png)
@bigbass1997 
![image](https://user-images.githubusercontent.com/22825059/28351530-d195c8d4-6c50-11e7-88fc-72d7af11e135.png)
@VermillionX
@Valdevon 
![image](https://user-images.githubusercontent.com/22825059/28351574-0dc509a0-6c51-11e7-8af8-06a9079f7b26.png)

**Comment by bigbass1997** [comment]
I am confident that Bryfer has explained the following point very clearly already, but seriously.... comments made in #1469 and #1202 are NOT complaints. At least one of which even states the phrase "I would suggest"! Some of the comments say to remove coins altogether, you may view this as a complaint, however they are not complaining, they clearly explain why they feel the coins should be removed or provide requirements to make the system better. There are also many comments that SUGGEST ways/methods to add to the coin system to make it better.

A new idea for consideration is the definition of "suggestion", therefore these comments are suggestions.

**Comment by Dream-Master** [comment]
Well not all was complaints but in the phase of work in progress many things changed. I just start a Chapter where you get something for you coins. Amount of all coins allready rebalanced. 
I need 1.5.0.5 Testers on zeta then to check the changes @bigbass1997 @Bryfer @MineAnPlay

**Comment by Bryfer** [comment]
There is alot of players willing to test 1.5.0.5, contact @Namikon and give him an update and he will most likely update Zeta as soon as possible.

**Comment by richardhendricks** [comment]
I would love to be able to trade coins for uncommon foodstuffs or saplings.  Haven't been able to find corn, rice, or onions yet in any of Pam's gardens in my world.

I think it would make sense to have coins be a rare drop or else require mob grinding of some kind so that using them doesn't replace exploration.  So they would be available for those missing that one crop or sapling etc, but a homebody couldn't play the whole modpack without leaving a few hundred blocks from their base.

**Comment by Dream-Master** [comment]
I moved this forward
https://github.com/GTNewHorizons/NewHorizons/issues/2058
