### ISSUE TITLE
Diamond Block doest has a burn time

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1627]
A diamond has a burn time of 102400, but you cant burn a diamond block, i would suggest adding a burn time of 921600, or, if you want to stay with the compression bonus of 10 times instead of 9, so giviing the diamond block 1024000 burn time,
Thanks
alphaNOVA

**Comment by Dream-Master** [comment]
:) yes why not :P

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27993800-f9f89d58-64b0-11e7-88fd-51bc07d8c6e2.png)

**Comment by Namikon** [comment]
Amazing how my example config file for the custom fuels addition became an actual thing ...

**Comment by Dream-Master** [comment]
yea :P
