### ISSUE TITLE
Large bronz boiler throttles function

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1629]

**Comment by alphaNOVAircraft** [comment]
The tooltip of the large bronz boiler controller tells you you can throttel the boiler, but even if you throttle the boiler, the coal usage doesnt lowers, so i dont see the point of throtteling the boiler, my suggestion : if possible it would be create to increase the burn time of the materials in the boiler if it is throttled

**Comment by Dream-Master** [comment]
@Technus did you have here any usefull infos when looking into source code?

**Comment by richardhendricks** [comment]
@alphaNOVAircraft Are you  sure the fuel usage is not decreased?  There is definitely code to try and do that.

The effect does not occur until the boiler reaches 100% efficiency, so check with a scanner.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java#L273
