### ISSUE TITLE
Try to fix Galactic Greg

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#163]
@Namikon 
Try to fix Galactic Greg
Send your source later for a rework.

**Comment by Dream-Master** [comment]
Phobos fixed

**Comment by Dream-Master** [comment]
I see on Europa ice this func
  public Item func_149650_a(int meta, Random random, int par3)
  {

**Comment by Dream-Master** [comment]
Callisto fix

**Comment by Dream-Master** [comment]
Io not fixed

**Comment by Namikon** [comment]
That doesn't matter, as the ChunkProvider for all Moons and Planets have their own classes, for Phobos that would be "ChunkProviderPhobos". You can tell that this one is used, since it generates the correct surface/lower blocks. If the generator would have a fallback to mars, you'd have mars blocks on Phobos, which you don't.

The problem is/was GalactiGreg, as the selector for Planettypes uses an inconsistent way to decide which planettype needs to be generated. I will push the (probably) fixed selector to bitbucket in a few minutes

**Comment by Dream-Master** [comment]
When i crash land on europa snow balls spawns that means europa ice can me melt down to water and snow thats why no ores can be generated

**Comment by Dream-Master** [comment]
i fixed code all ready wait i sen you my code in a min

**Comment by Dream-Master** [comment]
Inside the Dropbox folder Galactic Greg Version 0.8 src and compiled jar

**Comment by Namikon** [comment]
Well, I don't really need the code. If you managed to fix it, all is good.

**Comment by Dream-Master** [comment]
i change a bit not much only that it works on phobos and callisto

**Comment by Dream-Master** [comment]
io not working and phobos and deimos have mars ores. Europa i dind test yet.

**Comment by Dream-Master** [comment]
Io dont spawn Oremixe i dont know how i can fix it

**Comment by Dream-Master** [comment]
[Bitbucket] Your access to Namikon/galactigreg has been revoked?

**Comment by Dream-Master** [comment]
Be back after midnight because work

**Comment by Dream-Master** [comment]
All things are fixed only Europa not let us spawn samm Ores and Ore Mixes.

**Comment by Namikon** [comment]
Oregen on Eurpoa has to be researched, the rest is working fine

**Comment by Namikon** [comment]
Trying to get in contact with Blessentumble about the europa issue

**Comment by Dream-Master** [comment]
I think we have to force making our own Planet mod because many things ;-)

**Comment by Namikon** [comment]
Maybe the Europa issue is fixed already due the massive change to GalacticGreg, I haven't tested it yet, but if the goal is to create our own mod for planets, then we need some more input on the forum. As I said, I could easily (probably even without even looking at the GalaxySpace source, as the GalactiCraft-API is easy to understand) write a mod that adds a dozen of planets and solar systems, as it is basically just a matter of copy&paste things.

But i'd like to have at least a basic concept and asset for each of the planets/moons before we start

**Comment by Namikon** [comment]
Ahm...
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-2-8-galacticraft-add-on-the

**Comment by Dream-Master** [comment]
Yes i know this Modauthor and today i looking in the forum for other Planet mods too.

**Comment by Drobac** [comment]
i like this one a lot

**Comment by Dream-Master** [comment]
So we have to change the mods?

**Comment by Dream-Master** [comment]
It is open source now
