### ISSUE TITLE
[Quest] Extrude all the things MV

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1633]
Es fehlt dir normal Pipe Shape

**Comment by Bryfer** [comment]
Small, Normal and large shape molds is not in this quest
but I dont think all molds is nessesary to be added into this quest
(checked in 1.4.1.1 currently starting 1.5 to verify in newest version)

**Comment by Dream-Master** [comment]
Maybe not necessary but its not worse to add it

**Comment by Dream-Master** [comment]
@Bryfer Mold have to be in a different quest this is a extruder quest.

**Comment by Drobac** [comment]
Bryfer meant extruder shape not molds, also wire shape won't be used as everyone will use a wiremill for wires

**Comment by Dream-Master** [comment]
ok i can remove wires. Anything else need to changed after i update @PapaTim68 @Bryfer @Drobac

**Comment by Drobac** [comment]
Better put normal/large then tiny and huge

**Comment by Dream-Master** [comment]
Only remove this two?

**Comment by Drobac** [comment]
Rest seems ok to me

**Comment by Dream-Master** [comment]
K

**Comment by Dream-Master** [comment]
Only want to know this two?
