### ISSUE TITLE
Gallium

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1636]
Sollte ich so posten :)

Gallium ist ein selten vorkommendes chemisches Element mit dem Elementsymbol Ga und der Ordnungszahl 31. Im Periodensystem steht es in der 4. Periode und ist das dritte Element der 3. Hauptgruppe, 13. IUPAC-Gruppe, oder Borgruppe. Es ist ein silberweißes, leicht zu verflüssigendes Metall. Gallium kristallisiert nicht in einer der sonst häufig bei Metallen anzutreffenden Kristallstrukturen, sondern in seiner stabilsten Modifikation in einer orthorhombischen Struktur mit Gallium-Dimeren. Daneben sind noch sechs weitere Modifikationen bekannt, die sich bei speziellen Kristallisationsbedingungen oder unter hohem Druck bilden. In seinen chemischen Eigenschaften ähnelt das Metall stark dem Aluminium.

In der Natur kommt Gallium nur in geringem Umfang und meist als Beimischung in Aluminium-, Zink- oder Germaniumerzen vor; Galliumminerale sind sehr selten. Gallium wird auch als Nebenprodukt bei der Produktion von Aluminium oder Zink gewonnen. Der größte Teil des Galliums wird zum Halbleiter Galliumarsenid weiterverarbeitet, der vor allem für Leuchtdioden verwendet wird.

Gallium wird als Nebenprodukt bei der Aluminiumherstellung aus Bauxit im Bayer-Verfahren gewonnen. Als Ausgangsprodukt dient das dabei in Natronlauge gelöste Gemisch von Natriumaluminat und Natriumgallat. Durch verschiedene Verfahren kann hieraus Gallium vom Aluminium getrennt werden. Eine Möglichkeit ist die fraktionierte Kristallisation mit Hilfe von Kohlenstoffdioxid, wobei zunächst bevorzugt Aluminiumhydroxid ausfällt, während sich das leichter lösliche Natriumgallat in der Natronlauge anreichert. Erst nach weiteren Prozessschritten wird Galliumhydroxid gefällt, vermischt mit Aluminiumhydroxid. Anschließend wird das Gemisch in Natronlauge gelöst und Gallium durch Elektrolyse gewonnen. Da dieses Verfahren energie- und arbeitsaufwändig ist, wird es nur in Ländern mit geringen Kosten dafür, etwa der Volksrepublik China, angewendet.[10]

--------------------------------------------------------------------------------------------------------------------

Gallium kann auch direkt durch Elektrolyse aus der Natronlauge gewonnen werden. Dazu werden Quecksilberkathoden eingesetzt, wobei sich bei der Elektrolyse ein Galliumamalgam bildet. Auch das Versetzen der Lösung mit Natriumamalgam ist möglich.

Mit Hilfe spezieller Hydroxychinoline als Chelatliganden ist es möglich, Gallium aus der Natronlauge mit Kerosin zu extrahieren und so vom Aluminium zu trennen. Weitere Elemente, die dabei ebenfalls extrahiert werden, können mit verdünnten Säuren abgetrennt werden. Anschließend wird die verbliebene Galliumverbindung in konzentrierter Salz- oder Schwefelsäure gelöst und elektrolytisch zum Metall reduziert.

Für viele technische Anwendungen wird sehr reines Gallium benötigt; für Halbleiter beispielsweise darf es mitunter nur ein Hundertmillionstel an Fremdstoffen enthalten. Mögliche Reinigungsverfahren sind Vakuumdestillation, fraktionierte Kristallisation oder Zonenschmelzen.[10]

Die Menge an produziertem Gallium ist gering, 2008 betrug die Weltprimärproduktion 95 Tonnen. Eine weitere wichtige Quelle ist das Wiederaufbereiten von galliumhaltigen Abfällen, daraus wurden 2008 weitere 135 Tonnen Gallium gewonnen. Hauptproduktionsländer sind die Volksrepublik China, Deutschland, Kasachstan und die Ukraine, für das Galliumrecycling auch die Vereinigten Staaten, Japan und das Vereinigte Königreich.[12]

Im Labormaßstab lässt sich Gallium durch Elektrolyse einer Lösung von Galliumhydroxid in Natronlauge an Platin- oder Wolfram-Elektroden darstellen.[13]

**Comment by Bryfer** [comment]
Thanks for the information about Gallium. What do you suggest to change with this information?
