### ISSUE TITLE
Tiny Pile of Bronze dust

### ISSUE THREAD

**Issue by Michi1232** [GTNewHorizons/NewHorizons#1637]
![grafik](https://user-images.githubusercontent.com/28935401/27977558-82c6cee4-636b-11e7-80f4-af325cf9f841.png)
![grafik](https://user-images.githubusercontent.com/28935401/27977565-889525fa-636b-11e7-933b-36b534aee97c.png)

It doesn't make sense that you can compress 9 Tiny Piles to 1 one Dust when you can craft 4 to one.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27984280-11513580-63d2-11e7-95f6-e193d432f70a.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/27984283-2f9e354c-63d2-11e7-912f-d84ef655b648.png)
with small ones works but not with tinies

**Comment by WarlordWossman** [comment]
@Michi1232 are you sure that you are using tiny piles in both pictures? Because there are small piles which are 1/4 of a full dust.
