### ISSUE TITLE
No aspect

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#1638]
Bei diesen Items fehlen Aspekte
- [x] Compressed Air Cell
- [x] Steam Cell

- [x] Aluminium Item Casing
- [x] Liveroot
- [x] Stone Slab
- [x] Red Alloy Bolt
- [x] Coated Circuit Board
- [ ] Copper Cable 1x / 8x
- [x] Phenolic Circuit Board
- [ ] Diode

**Comment by Dream-Master** [comment]
Gt components i need to check and add via code.
