### ISSUE TITLE
Can't use clay water bucket to make concrete

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#1642]
![concrete - clay water bucket - bug](https://user-images.githubusercontent.com/29874719/27990538-e0e5a132-640e-11e7-8587-069027c7823f.png)

Likely reason being that the clay water bucket doesn't appear to be ore dicted to bucketWater, so will either need to add that to the clay water bucket, or change the recipe to use listAllwater instead, which appears to be the oredict entry that the clay water bucket is assigned to (along with the regular water bucket).  

Hopefully those observations were helpful, thanks in advance.

**Comment by Dream-Master** [comment]
ok will add clay buckets to the recipe too.
