### ISSUE TITLE
[Help] Guidebook localization support.

### ISSUE THREAD

**Issue by Yesterday17** [GTNewHorizons/NewHorizons#1643]
The modpack uses `Better Questing` mod for its in-game quests. However, it's often hard for some players to read English and in fact the mod itself supports localization.
Here's a [repository](https://github.com/yesterday17/GTNH-GuideBook-i18n) created by myself and it provided a method which you can transform the old quest file to a localized one. 
By doing this, native experience would not be influenced, but more players can get the chance to read the guidebook in their own languages. Since it's a bit disturbing when editing the quests(localize-format strings, such as xx.xx.xx, must be written instead of the meaningful words and sentences), i hope that you can run the script(or things like this) before releasing new versions of this modpack, and by that way translators can do their jobs and players would get better experience.
(Language files can be loaded from resource-packs, and it can be no influence to the creation of the modpack itself.)

I hope there's could be a chance for players who has poor english ability(of course including me, TAT) to enjoy this mod pack. So i wrote this with my really really poor english. I really love the modpack!

Addition: The usage of the script
1.Enter the main page of [JSZip](https://stuk.github.io/jszip/).
2.Press `F12` to open the console.
3.Copy the content of `GTNH.js` to the console.(The url should be edited.)
4.Input`parse(true, true)` and you can get`en_US.lang` and the `DefaultQuests.json` to override the original file, or `parse(true, false)` to get `result.lang`(Used for localization).

---
Part of screenshots under 1.4.1.1(Translated into Chinese):
<br />
![default](https://user-images.githubusercontent.com/8667822/27992873-77a358d2-64d0-11e7-8000-1d55840c8e54.PNG)
![default](https://user-images.githubusercontent.com/8667822/27992874-77a3e9c8-64d0-11e7-9929-3db3047fc0d2.PNG)
![default](https://user-images.githubusercontent.com/8667822/27992876-77a5d404-64d0-11e7-975a-19f144d30932.PNG)
![default](https://user-images.githubusercontent.com/8667822/27992875-77a4ba4c-64d0-11e7-855c-c0450ea7921b.PNG)

**Comment by Dream-Master** [comment]
Yes good idea. I guess other will maybe be translate the questbook too. I here some russian guys want to and i guess some germans too.

**Comment by Dream-Master** [comment]
@yesterday17 any things i need to do from my side as the pack creator.

**Comment by yesterday17** [comment]
@Dream-Master As is mentioned above, working with localized strings is troublesome. I suggest that you can make the quests as usual, and use the script before publishing it to the platforms such as twitch. After getting the json file, just follow the steps in `README.md` is okay. The difficulty with this approach is that the translator needs to compare the previous version with this one when the version is updated. I'm working on this to simplify the process too.
Another way requires the creators to write the localize-format strings by themselves when editing quests and add them to the corresponding language files. This is more convenient for the translator because they only need to translate the edited or new entry. But for the creator, this increases the likelihood of their error.
I recommend the first method and i'm trying to update the script to support this feature. However, i'm junior 3 now and i don't have much time doing this. The current version can be used, and translators can start their work now. The problem emerges only when the pack is updated and part of the quest book is edited.

**Comment by yesterday17** [comment]
And i suggest the localization to be supported as resourcepacks. By which the publish of the modpack would not be affected.

**Comment by Dream-Master** [comment]
Ok will ask my team if anyboday can take care about this process because a lot off stuff to do here.

**Comment by richardhendricks** [comment]
I will check this out later this year.

**Comment by Dream-Master** [comment]
We need to check how ingame edit works for it also.

**Comment by Dream-Master** [comment]
@Yesterday17 need help with it. Thanks

**Comment by Yesterday17** [comment]
@Dream-Master 
Help message can be found here: https://github.com/Yesterday17/GTNH-GuideBook-i18n/blob/master/scripts/Readme.md

But recently I wrote a [script](https://github.com/CFPAOrg/Modpack-GuideBook-i18n/blob/master/Greg%20Block/modpack-upgrade.js) similiar to it, and found that due to the percise of javascript `number`, keys like `UUIDLeast:4`  and `UUIDMost:4` will be turned from `-3998212785627166950` to `-3998212785627166700`, and numbers like `0.0` will be transformed to `0`.
The latter can be ignored, but the previous one needs to be fixed. Although it seems ok to ignore it(it's widely used in china and there's no report to the mistake generated by script), I'm looking for a way to fix it.

**Comment by Dream-Master** [comment]
with console you mean the windows dos console?

**Comment by Dream-Master** [comment]
@Yesterday17

**Comment by Yesterday17** [comment]
@Dream-Master No, it uses the console of your web browser.

**Comment by Dream-Master** [comment]
@Yesterday17 ok i found the editor but i get Syntax errors .
Urls need to  be changed ?
What the Input prase means?

**Comment by Yesterday17** [comment]
@Dream-Master You should run it in the console of [this page](https://stuk.github.io/jszip/), as is said in the readme. This page sets up the running environment for the script.
In fact, every website may have different environments, which depends on what scripts it had run while loading.

**Comment by Yesterday17** [comment]
Maybe your version isn't in the tag list of this repository?

**Comment by Dream-Master** [comment]
can we chat later in discod?
Maby easy more how to explain it works.
@Yesterday17

**Comment by Yesterday17** [comment]
@Dream-Master ok

**Comment by Dream-Master** [comment]
@Yesterday17 
this one is not fixed 
numbers like 0.0 will be transformed to 0.
the uuid thing is fixed

**Comment by richardhendricks** [comment]
@Yesterday17 Does your script properly handle UTF file formatting?  It looks like it is destroying the tags needed for colorizing words and adding extra line formatting.

Issue with links to information on file formatting requirements.

https://github.com/GTNewHorizons/NewHorizons/issues/3893

**Comment by Yesterday17** [comment]
@richardhendricks It may be the problem of better questing, since wrap line isn't supported in betterquesting with localization file. I think the destruction of color tags is also caused by this.
