### ISSUE TITLE
GT++ Blocks turn into error block while reloading chunk

### ISSUE THREAD

**Issue by Anikilulala** [GTNewHorizons/NewHorizons#1646]
![gif3](https://user-images.githubusercontent.com/11403359/28003118-96ca0272-656d-11e7-86a0-48fe20aed635.gif)
Hi, I'am running the newest version GTNH 1.5.0.2 without any change.
Each time trying reloading chunk, several GT++ blocks will turn into purple mask 2037:0.
(Example in GIF above:
First time : GT muti-block tank 2037:827
Second time : GT tree farm 2037:836)
And these blocks are completely broken : no response when right clicking, drop nothing when breaking with wrench.

**Comment by Dream-Master** [comment]
@draknyte1
any idea?

**Comment by draknyte1** [comment]
No idea. Going to need more details. Pure forge? Smp or ssp? 

Not something I can fix because it'd be a gregtech issue if it's tile entities corrupting.

**Comment by Dream-Master** [comment]
@Anikilulala give me more Infos about this issue.

**Comment by Anikilulala** [comment]
It's a pure version of GTNH downloaded from TechnicLauncher without any change.
I tried to delete the old version and then install a new one, but nothing changes.
And it happens both SMP and SSP.
@draknyte1 @Dream-Master

**Comment by draknyte1** [comment]
I have no idea, you're the first user in a year to ever have a problem.
Will leave this with @Dream-Master to continue watching, see if anyone else in the pack gets the issue.

**Comment by Dream-Master** [comment]
Will update your version today and try to reproduce it. @draknyte1

**Comment by Anikilulala** [comment]
Tonight I have tested this bug on 3 different computers. These computers have different windows version, different java version and different hardware spec.And the bug happens all the same.Here is what I do on a computer never run minecraft before:
1 Download & install the newest Jre.
2 Download & run Technic Launcher
3 Download newest GTNH and start the game without any change.
4 Give myself [muti-block tank 2037:827] & place some on the ground.
5 Suicide
6 Go back and the bug occurs.
I believe if you do same things, you could reproduce it easily.

**Comment by Ethryan** [comment]
Hmm, this may be a gt++ error. 
In that case it will have to be reported to the mod author.

**Comment by Dream-Master** [comment]
@Ethryan the mod author already answered here in this thread already.
@draknyte1 is the Gt++ Author

**Comment by draknyte1** [comment]
I can't reproduce this either outside of GTNH, with which I don't have access to testing with at the moment. So, it's either due to your changes to GT or GT itself.

**Comment by Dream-Master** [comment]
@draknyte1 it was only a Info about @Ethryan because he dont know you under this name maybe.

**Comment by Dream-Master** [comment]
yes got the same problem with the gt multi tank
![image](https://user-images.githubusercontent.com/2970688/28078210-660145a4-6664-11e7-987d-fbd013d6df3c.png)

**Comment by Dream-Master** [comment]
but i got blocks back via wrench. A relog not works sadly

**Comment by Dream-Master** [comment]
@draknyte1 Tree Framer and MultiTank have this problem all other blocks just works fine

**Comment by Anikilulala** [comment]
![new](https://user-images.githubusercontent.com/11403359/28077801-57a54498-6695-11e7-82f7-760e3fe47eb4.JPG)
I have made a minimized install of GT++. [GT multitank] and many other blocks are still turning into purple mask after one or two times chunk loading (player suicide).
There are only 5 necessary mods installed, they are:
Forge 10.13.4.1558
Industrialcraft 2-2.2.828 experimental
Gregtech 5.09.31pre2
GT-PlusPlus-1.5.6-Pre-release
Nei
So I believe the problem might be some conflict between GT++ and newest IC2 or GT.

**Comment by Dream-Master** [comment]
@Anikilulala please tra with tree farmer too.

**Comment by Anikilulala** [comment]
@Dream-Master 
Tree farm block won't break during first time reloading, but will break during the second time.
It's so weird...

**Comment by Dream-Master** [comment]
it is @draknyte1 so we need help here with thi issue.

**Comment by draknyte1** [comment]
I cannot reproduce this..

**Comment by Anikilulala** [comment]
Tested stable version gt 5.09.29 and gt++.
This problem still exists.

**Comment by Dream-Master** [comment]
So it isnt a pure GTNH issue.

**Comment by Dream-Master** [comment]
still not fixed
![image](https://user-images.githubusercontent.com/2970688/31316070-bef93354-ac25-11e7-9f6c-d4760abef832.png)

**Comment by richardhendricks** [comment]
Fixed.
