### ISSUE TITLE
Recipe Imbalance? 

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1647]
centrifuging stone dust in 1.5.0.3 gives titanium, Florine, magnesium, aluminium, iron, manganese, barium, chrome.... among others, however you need ev to get the chrome and other rarer materials.

Suggestion either re-balance the materials gained or greatly reduce the chance to get material out of the stone dust to bring in line with other planetary stone dust.

**Comment by Dream-Master** [comment]
This recipe using 1920 eu/t. After you have titanium (pre moon) you can do it.

**Comment by Dream-Master** [comment]
low tech recipe need mv 120 eu high tier recipe nedd 900 eu/t = ev which need Titanium Plates for the machine. Any special suggestion how to nerf the materials @Anarack

**Comment by Anarack** [comment]
I would suggest making each stone dust give less material per dust but have the total energy cost per material gained remain similar to now because of how much dust you get from just ore washing all the ores you are already processing.

**Comment by Dream-Master** [comment]
So mean you need to put 10 or 20 stone dust in instead of one to get those materials out?

**Comment by MineAnPlay** [comment]
It's good as is. It requires EV so it's not that big of a boost.

**Comment by Dream-Master** [comment]
Will changed anyways. Johanns make a new pull request in the main repo. 
https://github.com/Blood-Asp/GT5-Unofficial/pull/1158

**Comment by draknyte1** [comment]
It only got changed because some of us had a bitch about his illogical addition.
Even then, I am not happy with the % values on outputs, as they're still too high.
