### ISSUE TITLE
[Question] Unnamed Machine

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#1648]
My Error or mod error

GTNH version 1.5.0.3

![2017-07-11_15 56 12](https://user-images.githubusercontent.com/15316448/28071844-7cd78288-6651-11e7-9287-45f7b652ca63.png)
![2017-07-11_15 56 14](https://user-images.githubusercontent.com/15316448/28071843-7cd76334-6651-11e7-8cd7-edd52f853142.png)
![2017-07-11_15 56 16](https://user-images.githubusercontent.com/15316448/28071842-7cd2a75e-6651-11e7-8344-4a65577a4bd9.png)
![2017-07-11_15 56 19](https://user-images.githubusercontent.com/15316448/28071845-7cf067b2-6651-11e7-91dc-60d0fe542744.png)
![2017-07-11_16 00 13](https://user-images.githubusercontent.com/15316448/28072056-0d694d18-6652-11e7-8383-375577ebaa0a.png)

extra trees has many unnamed blocks

**Comment by Dream-Master** [comment]
@Ldmf please post the issue here abnd link it to this issue. Thanks
https://github.com/ForestryMC/Binnie/issues

**Comment by Dream-Master** [comment]
@Ldmf I need to rechek my recipes maybe the ids are changed.

**Comment by Dream-Master** [comment]
Ok it seems machines are removed from the mod. So it is a issue in my Pack. @Ldmf

**Comment by Ldmf** [comment]
ok no problem :) im glad i can halp you
