### ISSUE TITLE
Infinity items

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#1649]
are little overnerfed. 240k infi catalyst dust and 900k black pluto just for torso, that's totaly impossible to obtain.
![2017-07-11_16 58 07](https://user-images.githubusercontent.com/25028786/28071940-229f66d8-665a-11e7-9e3e-5ae59ef9652c.png)

**Comment by Cinobi** [comment]
**new recipy**: 21 plate = 420 infi ingots, = 10080 neutron ingots + 4620 infi catalysts = 816480 tiny neutron piles + 295680 infi cat dusts = 1020600 black pluto dust + 295680 infi cat dust ~ 421735 black pluto ore + 122181 infinity cat ore.
**old recipy**: 24 infi ingots.
17.5x modifier, why so cruel? 
In delta - only 2 teams of players reach it, noone will reach with new values.

**Comment by noobyaran9** [comment]
How are u suppose to get so much black plutonium???? Even quarrying in the deep dark is impossible.

**Comment by Dream-Master** [comment]
When you are able to doing this Armor you are done with the game. And this time the recipe idea wasn't mine :)

**Comment by Dream-Master** [comment]
@Cinobi Impossible to obtain is nothing with a endless world/dim it needs only infinite time

**Comment by Cinobi** [comment]
Well, @Dream-Master , some parts of this recipy changes is good. I mean - " u need all types of hiend armor to craft it". But, this enourmous quantity of plutonium and infy catalyst... u know, for single with 100k:100k quarryes - maybe it's possible. But for multiplayer...

**Comment by Dream-Master** [comment]
@Cinobi ask @Ethryan to renerf this recipe a bit. Maybe we can have a good new recipe.

**Comment by Drobac** [comment]
Agreed with cinobi, I'd leave the normal infinity/neutronium ingots. Just to get the 24 to make a chest plate takes about 20k Infinity catalyst and 40k Black plutonium ore. I like the addition of the late game armors in the recipe, that actually makes it tier appropriate and will encourage people to actually make some of the armors like draconic, which atm are being completely evaded due to their high cost. Not to mention to get access to the Deep Dark now you need an infinity ingot anyway, so just the initial cost (especially time needed) to get to the deep dark are very high

**Comment by Ethryan** [comment]
Ok, gonna look at this tomorrow after work, will see if i can unnerf it some.

**Comment by Cinobi** [comment]
> you could get tiny infinity dust from sifting or centrifuging stone dust from some late tier planets.
it was removed near new year.

**Comment by Ethryan** [comment]
Ok, will fix this tommorow.

**Comment by DietmarKracht** [comment]
Alternative whould be an ore that can give you neutron ingots or at least tiny piles at a 1:1 ratio. the infinity catalyst dust is more common than the black plutonium dust

**Comment by Dream-Master** [comment]
Maybe i could add a recipe wich can use black plutonium in any way for Avaritia Plutonium.

**Comment by Drobac** [comment]
The avaritia is neutronium, not plutonium

**Comment by Dream-Master** [comment]
@Drobac sure my fault.

**Comment by Cinobi** [comment]
All avaritia items is pure magic items! Let's make them via thaumcraft infusion! For armor recipy: all armors in screen, + 2-3 blocks of infinity + 1-2 blocks of neutronium, + 100500 of some essense!
That's mostly a joke, but...

**Comment by Dream-Master** [comment]
Nah Avaritia Items need Avaritia Table. But add some high Tier magical recipes for make things cheaper in genaral would be nice. Any suggestions?

**Comment by noobyaran9** [comment]
Block of Pure Tears. ;D

**Comment by Dream-Master** [comment]
🤣

**Comment by Dream-Master** [comment]
@Cinobi maybe we let the recipes like it is we only add a UV way to make Infinity and Avaritia Neutronium more easy. Any suggestions?

**Comment by noobyaran9** [comment]
Add infinity small ore to T8 planet and make them require UV power to smelt.
Or add recipe for the Avaritia Neutrons Collector that generates tiny pile of neutronium every 6mins.

**Comment by Dream-Master** [comment]
Yes i could re add the Neutron detector at uv level to get avaritia neutronium quicker.  So I need to think a way get infinite dust more quickly/ easy at uv.

**Comment by Dream-Master** [comment]
@Drobac any suggestion here?

**Comment by Drobac** [comment]
Make it so infinity ingots can be made in a fusion reactor with an insanely long time and energy cost

**Comment by Dream-Master** [comment]
Infuse Neutronium plasma and xxx plasma  to infinity ?

**Comment by Drobac** [comment]
Adding easier infinity ingots on planets would make all the existing recipes pointless. Don't see what the problem is with the current recipes using infinity and neutronium ingots. I do like the addition of high tier armors in the recipe

**Comment by Dream-Master** [comment]
@Drobac any specific materials time and eu cost ?

**Comment by Drobac** [comment]
Need to check, but maybe something like awakened draconium and neutronium at UV/t and taking 6-12 hours for a nugget

**Comment by DietmarKracht** [comment]
the problem is the huge amount of needed infinity ingots for one set of armor. Either change all the plates to ingots or make an easier way of getting them to balance the reciepe

**Comment by Dream-Master** [comment]
This Armor is op and so make it expensive is ok. Let me see what i can add in the fusion recator. i will readd the Neutron collector too.

**Comment by noobyaran9** [comment]
>This Armor is op and so make it expensive is ok.

I don't see the OP-ness in this armour. The only good thing it provides with full set is invulnerability. The armour that is required in the recipe is just so much better than the infinity armour itself. I agree with what diet have said. Just use the original recipe with all the late game armour requirement. With this, nothing have to be changed   or added at all.

**Comment by Drobac** [comment]
The armor is more about bragging rights then actual use

**Comment by Dream-Master** [comment]
Then the recipe is quite ok :P

**Comment by Drobac** [comment]
The issue is still the same, there is no need or point in making the armor use Infinity plates, just the added armors needed to craft them is making them more then enough tier and difficulty wise. Just revert the recipes back to needing Infinity and Neutronium ingots. Also all of the Avaritia Tools are using the DE Draconic scepter recipe in the crafting which is pointless. Make the Avaritia tools use the appropriate DE tools for crafting, so shovel for the shovel, pick for pick etc

**Comment by Drobac** [comment]
As per discussion:
1. Remove all Infinity and Neutronium Large Plates in the recipes
2. Deep Dark recipe- reduce infinity cost to 1 ingot
3. Neutronium Compressor - remove all Infinity material from it, reduce the Neutronium cost by a bit
4. Neutron Collector - needs to have only 1 Infinity ingot in its recipe
5. Avaritia Tools recipes - need to use appropriate DE tool in its crafting, also remove all Large plates as per point 1

**Comment by Ethryan** [comment]
- [x] Remove all Infinity and Neutronium Large Plates in the recipes
- [ ] Deep Dark recipe
- [ ] Neutronium Compressor
- [ ] Neutron Collector
- [x] Avaritia Tools recipes

1. Done.
2. Is in NewHorizonsCoreMod (Dream's area).
3. Reduced infinity ingot cost to 4 infinity plates (= 8 ingots) and decreased the number of neutronium by changing 4 blocks to infinity catalysts (no shortcuts).
4. Changed the Infinity blocks to black plutonium.
5. only kept the staff for the sword since it insta kills everything it touches. The large plates are removed.

**Comment by Drobac** [comment]
Neutronium Compressor CANNOT have any infinity materials in it. It is required to make the infinity catalys out of the dusts

**Comment by Dream-Master** [comment]
Ok i will go over it again.

**Comment by noobyaran9** [comment]
Just revert it back to the orignal recipe. There is no point of changing that, as there is no uses even u have it on the ealier tier.

**Comment by Dream-Master** [comment]
No i change it but less than before.

**Comment by alphaNOVAircraft** [comment]
I agree that the amounts of ores is insane, but i dont see a need to make it really "cheaper", i would edit the recipe in a very energy exxpensive way, like the sugesstion with the fusion reactor, but also some extrem thaumcraft infusions for crafting compoonents of the infinity sruff sounds like a greate idea, or alternative it could already help adding a way to synthesise some black plutonium in the fusion reactor so you still need insane amounts, but theres no need to completly quarry out thousands of chuncks in the deep dark

**Comment by kris449** [comment]
That's what the neutron collector is for.

**Comment by kris449** [comment]
@Dream-Master are you aware that a full month and 2 updates later, the neutronium compressor recipe is still not fixed and impossible to make? =\

**Comment by Dream-Master** [comment]
@kris449 can you open up a new issue? I maybe have forgotten it.

**Comment by Dream-Master** [comment]
done

**Comment by sebastian-izquierdo** [comment]
de que vercion es el modpack? y si es que se puede pasar
