### ISSUE TITLE
Tier 2 quest screen starting point

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1650]
When clicking the Tier 2 tab, the screen has a wrong "starting point".  
Clicking in the quest window snaps the screen to a better starting point, with the top left quest in the top left corner. This snapping gets kind of annoying after a while.
This is also present to some extent in some of the other quest tabs, but it's worst in Tier 2. 
![image](https://user-images.githubusercontent.com/30087707/28085059-cd41b21a-667a-11e7-89a0-711fda303d65.png)
![image](https://user-images.githubusercontent.com/30087707/28085121-091d64f0-667b-11e7-9d8e-8ea9ce85cb0e.png)

**Comment by Dream-Master** [comment]
The large tool from tico moved to tier mv anyways in 1.5.0.4

**Comment by DualBallers** [comment]
Sorry if I didn't make it clear. It's not about a specific quest, but about the page default starting point, where half the screen is empty, and only snaps to a better view after clicking. 
Maybe the quest need to be moved on the page, or ,maybe you can move the origin of the page?

**Comment by Dream-Master** [comment]
report it to the Mod Author because i think nothing i could do here.

**Comment by Dream-Master** [comment]
https://github.com/Funwayguy/BetterQuesting

**Comment by richardhendricks** [comment]
I thought Tier 1 was broken, until I realized I had to scroll all the way over to the top right to see the quests. Is this the same issue?

**Comment by Dream-Master** [comment]
Could be. Idk never have real issues with the Questbook. Yes it jumps from time to time to another position.

**Comment by Bryfer** [comment]
Try changing your GUI scale to normal

**Comment by richardhendricks** [comment]
Will look into moving quests over in the tab builder, see if that helps.

**Comment by richardhendricks** [comment]
Nope, moving over the quests doesn't matter.  I suspect what is happening is that when the quest tab is opened, if the quests fit on the screen, great.  If not, for some reason it is justifying the quests to the bottom right. :(

**Comment by richardhendricks** [comment]
I will add a note to the first few tabs to scroll in/out to make quests appear
