### ISSUE TITLE
Crash (Multiplayer, 1.5.0.4)

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1651]
Crashreport:
https://pastebin.com/nasjyKY9

Happens when other Player (local MP) tries to look up a recipe (host not affected) (doesnt matter which recipe)
Did not happen in 1.5.0.2
1.5.0.3 not tested atm

**Comment by WarlordWossman** [comment]
I just crashed on a server in 1.5.0.4 when I tried to check a recipe. Nobody else on the server. 
Already sent the crashreport to Dream.

**Comment by Dream-Master** [comment]
Yes since  1.5.0.3 we have this mysterious crashes.

**Comment by Ugachaga** [comment]
Can you confirm or deny if crash related with Adventure Backpack and happens only if recipe view called from backpack GUI?

**Comment by Radst0ne** [comment]
Cant confirm that, happens everywhere

**Comment by Dream-Master** [comment]
@Ugachaga i update to version 15 before we stay at 12

**Comment by Dream-Master** [comment]
@Ugachaga the crash not give much infos about stactrace

**Comment by Ugachaga** [comment]
@Dream-Master  
`func_99999_d() = run()` and `func_71411_J = runGameLoop()`, something derping rly hard.

**Comment by Dream-Master** [comment]
What this function describes?

**Comment by Raccoon2709** [comment]
the functions from invetory tweaks

**Comment by Namikon** [comment]
Still not sure which mod exactly is causing it, but at least I got a more detailed Stacktrace:
https://pastebin.com/SL1sC1ak

**Comment by Lainiel** [comment]
My game crashed 4 times when I updated to 1.5.0.3 and tried to open recipe in NEI after joining my server. Then I tried starting the game and creating a new world in singleplayer to see if the game crashes too. When I opened NEI recipe in singleplayer my game didn't crash. After that I joined my server again and everything worked. I have been playing 1.5.0.3 for more than a day and haven't had any issues yet. I told my friend to do the same thing (create a singleplayer world open up a recipe in NEI and then join the server) and his game stopped crashing too.

**Comment by Dream-Master** [comment]
I will release 1.5.0.5 soon with a never gt++ version. Lets see if this fix this issue.

**Comment by Namikon** [comment]
Then close it when the issue is solved

**Comment by Dream-Master** [comment]
Not sure why it was closed maybe auto closed.

**Comment by Dream-Master** [comment]
seems to be fixed.
