### ISSUE TITLE
maple syrup

### ISSUE THREAD

**Issue by hebiohime** [GTNewHorizons/NewHorizons#1652]
the time spent in which it takes to obtain maple syrup is too damn high
![1sctiq](https://user-images.githubusercontent.com/13721540/28098808-6edd8f44-6686-11e7-9d2b-2711cd2c2fd3.jpg)

**Comment by Dream-Master** [comment]
it is maybe i have to look at an other recipe create thos trees/saplings

**Comment by Dream-Master** [comment]
I could add a food quest where you can get marple sirup for plant your trees.

**Comment by Bryfer** [comment]
I believe this would be an perfect way to spend coins.
Forestry coins(?) for saplings/seeds

This could be implemented as an optional questing tree.
or an new machine similar to the Pam's harvest market.

#1474

**Comment by Dream-Master** [comment]
Sure another option to get this sapling.
