### ISSUE TITLE
Clean up NEI by removing AE2 grindstone recipes

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#1653]
Since the AE2 grindstone is disabled in this modpack I believe NEI could really be cleaned up by removing all the recipes in it with one simple line in a modtweaker script: 

mods.appeng.Grinder.removeRecipe(<*>);

Are there any downsides I'm not seeing?

**Comment by damug** [comment]
It's also apparently doable through the AE2 configs as I look deeper.

**Comment by Ethryan** [comment]
Does this change fix it?

**Comment by damug** [comment]
So I'm trying to test the config change you posted, and it doesn't seem to be actually removing the grindstone recipes from NEI/the game.  Might have to go the modtweaker route after all.  That, or I'm just incompetent at making these changes.

**Comment by Ethryan** [comment]
Ok, i will test it more when i get home (8-9 hours from now).

**Comment by Ethryan** [comment]
Ok, i've tested it and done a pull request with a fix.

**Comment by damug** [comment]
Thanks Ethryan!

**Comment by Dream-Master** [comment]
@damug @Ethryan Added to the next release.
