### ISSUE TITLE
Excavator quest #744 requires excess items

### ISSUE THREAD

**Issue by General-Bacon343** [GTNewHorizons/NewHorizons#1654]
This quest (#744, Mining dirt block by block is so old school) requires 2 steel large plates. However a finished excavator only needs 1. 
![2017-07-12_00 51 31](https://user-images.githubusercontent.com/27801159/28105434-965841de-669c-11e7-9c84-5ac1b9acdfc3.png)
![2017-07-12_00 51 40](https://user-images.githubusercontent.com/27801159/28105436-97eb63e6-669c-11e7-8f15-dbca0cd8fddd.png)

**Comment by Dream-Master** [comment]
Ok will Change it
