### ISSUE TITLE
Annealed Copper Rods

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1656]
You can't use the extruder for making rods so you must use the lathe. Just a waste of materials and time.

**Comment by kris449** [comment]
Was posted [here](https://forum.feed-the-beast.com/threads/1-7-10-gt-new-horizons-ultra-hard-gregified-modpack-via-minetweaker-and-modtweaker-850-quests.181742/page-32#post-1895889) based on your response I thought you had fixed it.

**Comment by Bryfer** [comment]
https://www.google.se/search?q=annealed+definition

Annealed copper dosnt really work that way xP 
Extruding / lathe would most likely remove the annealed part and turn it into normal copper

**Comment by MineAnPlay** [comment]
I know how annealed works... But the stupid stuff requires tons of it :P. So making it via the lathe is just stupid. Either remove annealed copper rods or add a recipe.

**Comment by Bryfer** [comment]
Making annealed copper rods from copper rods in the ebf would make more sense than the lathe (or other furnace)

**Comment by Dream-Master** [comment]
Good idea @Bryfer .

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28292323-d214a274-6b4e-11e7-87e6-f9b2e2240d31.png)
this recipe is possible too.

**Comment by Dream-Master** [comment]
If i made annelead copper rods in the ebf i need to add other components too like plates, screws and other stuff. @MineAnPlay @Bryfer

**Comment by Bryfer** [comment]
Annealed liquid would be impossible to make in real life.
As I understand annealed copper, it's like putting bread into an toaster to get toast. 
You can not make tasted bread directly since that would make burned bread.


Yes with my precious comment suggesting ebf/furnace
If this idea would be implemented, then all annealed copper items would be make from copper items, in EBF/furnace

**Comment by Dream-Master** [comment]
ok

**Comment by MineAnPlay** [comment]
You want to make a simple item in an EBF xD. The fluid form is not realistic nor is the extruder recipe but using an EBF to make rods? It will just melt :P . I still think you should just add extruder recipes for it.

**Comment by Dream-Master** [comment]
Not sure when bronze melt but if I take temperature below it could be possible in my eyes

**Comment by jvols** [comment]
How difficult would it be to add a copper rod - > annealed copper rod recipe in the arc furnace (similar to how regular annealed copper ingot can be made with oxygen)? Most heat treatment of metals is done AFTER machining/ working.

**Comment by Dream-Master** [comment]
not really only one line of code.

**Comment by Dream-Master** [comment]
but i am not sure if the rod is not melted completly when in the arc furnace.

**Comment by Ethryan** [comment]
Since you use the arc furnace to make annealed copper ingots, it sounds more probable than using the EBF. Since annealing is the controlled heating and cooling of an  metallic object it would require a completely new kind of heat treatment machine if you want to get it more realistic. 

I actually would like it if you could only make annealed products in the arc furnace.
For example annealed copper wire, take regular copper wire and put it through an annealing process in the arc furnace to change it to anealed copper wire.

**Comment by Dream-Master** [comment]
Not sure how complicated it is take out all this recipes only for Annealead copper.

**Comment by Ethryan** [comment]
Ok, I will see if I can find something for that in the code when i get home from work.

**Comment by Dream-Master** [comment]
You must add for all processing stuff a case annealead copper. It is a bit much work but possible

**Comment by Ethryan** [comment]
Think i have found out how to disable the adding of annealed copper recipes in gt source code: [Materials](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java), [Subtags](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/SubTag.java), by adding NO_SMASHING and NO_WORKING as subtags, then you just readd the recipes you want in [Machine Recipe Loader](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java).

Gonna compile and test this when i get home.

**Comment by Dream-Master** [comment]
If this works yes it would be easy.

**Comment by Ethryan** [comment]
I found fluid solidifier recipe in [Recipe Loader](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java) line 265.

**Comment by Dream-Master** [comment]
its harder to disable i try now fluid solidifier recipes i got now but ingot and nuggest i need to find

**Comment by Dream-Master** [comment]
This only said that you can make ic copper casings out of annelead copper

**Comment by Ethryan** [comment]
ah, ok.
