### ISSUE TITLE
Fluid regulator when pipe closed

### ISSUE THREAD

**Issue by leglerm** [GTNewHorizons/NewHorizons#1657]
![2017-07-12_21 29 00](https://user-images.githubusercontent.com/13408657/28136302-81cd0c60-6749-11e7-948b-6837a6a85cb7.png)

The fluid regulator still pulls fluid from the bottom pipe even though the shutter module is disconnected. 

Not a big problem since i just attach it to the tank instead of wasting a pump module. 

Not sure if it can be fixed since it propably sees the bottom pipes inventory as a block and not as a pipe.

**Comment by Dream-Master** [comment]
@Blood-Asp @JohannesGaessler any idea here. Did the main repo have a fix i dont see for it ?

**Comment by JohannesGaessler** [comment]
I do not recall anything of the sort.

**Comment by Dream-Master** [comment]
@JohannesGaessler ok thanks for info.
@Blood-Asp any idea?

**Comment by mitchej123** [comment]
Is this still an issue, or was it fixed with the recent pipe changes?

**Comment by mitchej123** [comment]
Closing for now assuming it's not an issue, please re open if it is.
