### ISSUE TITLE
Plant Mass quest not completable

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1658]
Plant Mass quest in MV tier is not possible to complete, since advanced macerator requires industrial diamond which can be only made in HV tier.

**Comment by Dream-Master** [comment]
@Lainiel Will look at it.

**Comment by Dream-Master** [comment]
@Lainiel Why hv tier. Advanced circuits can be made in mv. Or did i oversee here something?

**Comment by Dream-Master** [comment]
I will seperate this quests from the main  Quest line anyways.

**Comment by DietmarKracht** [comment]
Its about the Industrial Diamond. This requires an Implosion Compressor and that thing is HV

**Comment by Dream-Master** [comment]
@DietmarKracht Why. I checked it and it is mv able.

**Comment by richardhendricks** [comment]
Add wording to Plant Mass questline: 

You will need an implosion compressor to make the industrial diamond. It is under multi-block goals. It requires completing the silicon quest line.
