### ISSUE TITLE
Nightmare (Mob from Thaumic Horizons) could cause problems on servers.

### ISSUE THREAD

**Issue by XxANTI-MATTERxX** [GTNewHorizons/NewHorizons#1659]
I have been doing some research in single-player, and have been focused on the nightmare for quite some time now. I fear that this mob may cause problems (whether minor or extreme, I don't know) in servers. This mob is like a horse, it accepts a saddle and horse armor, and can be ridden normally. the "jump" is replaced with a short-range teleport. all of this is fine. The REAL problem is what happens when the jump meter fills up 90% or above. The Nightmare will cause an explosion centered on itself ( this could be used for griefing purposes) and takes the rider and itself to the nether. I am afraid that this random teleporting to the nether could cause extreme lag if this multi-dimensional blink effect were to be spammed.

**Comment by Dream-Master** [comment]
@XxANTI-MATTERxX i will look at it. @Namikon @Technus @Drobac @bigbass1997  @MineAnPlay @Bryfer did we have any issue with it in the past ?

**Comment by Drobac** [comment]
I used the horse before, didn't have any problems with it
