### ISSUE TITLE
Steam suggestion?

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1660]
maybe its a bit op but what about adding a way to create SH steam with a boiler. The first one creates steam and the second creates out of the Steam SH Steam but it needs alot (by alot I mean alot like 4x more) more fuel than for its needed for normal steam. It would make the large turbine much more attractive. But maybe im overlook something.

**Comment by Bryfer** [comment]
Large heat exchanger

**Comment by Radst0ne** [comment]
But it needs lava or hot coolant

**Comment by MineAnPlay** [comment]
If you make it require 4x more fuel it will be more inefficient (SH Steam is worth 2 Steam)

**Comment by Radst0ne** [comment]
Yeah thats right

**Comment by Dream-Master** [comment]
So close this issue? @Radst0ne @Bryfer @MineAnPlay

**Comment by Radst0ne** [comment]
Well idk it would be cool to have, if its possible

**Comment by Dream-Master** [comment]
@Radst0ne Gt++ add a steam condenser or something to convert steam.

**Comment by Radst0ne** [comment]
What do you mean by "converting steam"

**Comment by Dream-Master** [comment]
Ic2 gt

**Comment by Radst0ne** [comment]
Nice okay than the issue here is solved

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28331836-f4e9d3f6-6bf2-11e7-88e1-28e57bdccb29.png)

@Radst0ne Can i close it?

**Comment by Bryfer** [comment]
I might have missed something but what does the steam condenser do?
IC2 what to steam?
IC2 power? IC2 Steam? 

And how does it make you produce more Steam? SH steam?

**Comment by Dream-Master** [comment]
Not 100% sure never used it.

**Comment by Radst0ne** [comment]
@Bryfer same questions xD

**Comment by Bryfer** [comment]
I'll look it up after work unless someone else is faster :)

**Comment by draknyte1** [comment]
Ic2Steam + water = normal steam.

**Comment by richardhendricks** [comment]
I like the idea, but I would not use extra fuel.  Instead make it not 100% efficient, so that 1 steam -> .8 SH steam. Then a steam oriented player could use the SH steam to generate power to keep relevant at higher tiers.  And would still need a normal steam setup to top off the loop.

**Comment by draknyte1** [comment]
Don't try change these kinda IC2 ratios (which you truly can't anyway), bad suggestion. 

SH steam has methods of production and isn't intended to be easily made -.^

**Comment by richardhendricks** [comment]
Superheaters are pretty common in late-tier steam machines IRL
https://en.wikipedia.org/wiki/Superheater

I didn't say it would be easy, it's just a minor way to extend the use for coal-fired steam a little longer.

Plus people like building big systems.  Boiler #1, boiler #2, SH steam turbine, Steam turbine.  Sounds like fun to me.

**Comment by Dream-Master** [comment]
I think we can let it like it is.
