### ISSUE TITLE
[Question] Smelting Ores bug?

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#1661]
I think in 1.4 or so GTNH was it so that you smelt you ors in a tc smeltery now in 1.5.0.4 you can smelt ore's in a furnac

**Comment by Dream-Master** [comment]
Ok will look at it. Is this a good or a bad feature? @Ldmf

**Comment by Ldmf** [comment]
I think the TC (tinkers construct) way was interisting
i dont think it is realistig to semlt ore in a normal furnace where you cook food

**Comment by Dream-Master** [comment]
sicher. dann erkläre das Problem nochmal @Ldmf

**Comment by Ldmf** [comment]
Klar gerne :D also ich fand es damals besser als man nur erze in der Smeltery schmelzen konnte zu mindestens so weit ich es im Kopf hatte also eisen erz zin und so weiter kann man nun in einen Ofen schmelzen oder war das schon immer so?

Weil in den 1.4.x Versionen war das glaube ich anders gewesen da musste man über Tinkers gehen um weiter zukommen

**Comment by Dream-Master** [comment]
Ne man konnte die leider immer im Ofen schmelzen auch in 1.4. Ich fände es auch besser vieles in Tinkers zu machen aber es gab einen Sturm der Entrüstung als ich das vorgeschlagen habe.

**Comment by Ldmf** [comment]
ok dann habe ich mich geirrt wäre aber besser finde ich würde auch super zum pack passen (Ofen wo man essen kocht kann man keine erze schmelzen)

wenn das immer so war dann ist die frage beantwortet (mach das also zu dann)

ps. ich schaue noch mal in einer älteren Version

**Comment by Dream-Master** [comment]
Lass mal offen

schau mal hier

https://github.com/GTNewHorizons/NewHorizons/issues/1492

**Comment by Ldmf** [comment]
Also was man bräuchte wäre ein block für die smeltery wo man Kohle/Holzkohle/Koks und co rein tun könnte oder man ändert die Rezepte so das man für eisen und co Koks braucht anstand kohle das würde auch gehen denke ich mal
nur ne Idee

**Comment by Dream-Master** [comment]
Im Prinzip gut aber man braucht einen neuen Ofen da das mit Vanilla nicht geht. Alles was ein burnvalue hat geht da rein.

**Comment by Ldmf** [comment]
Wie wäre es mit einem Multiblock aus staind clay zwei ofen und kisten oder so was fast so änlich wie die tinkers smeltery ohne lawa mit kohle (egal welche)

**Comment by Dream-Master** [comment]
Wenn ich programmieren könnte ja. :P

**Comment by Ldmf** [comment]
ich kann es auch nicht von daher es ist ja nur eine idee zum glück

**Comment by Dream-Master** [comment]
Ideen sind super vielleicht kann es ja jemand anderes.

**Comment by Ldmf** [comment]
Eine kleine idee wie man das craften könnte

Keramik Hülle
![2017-07-17_13 13 45](https://user-images.githubusercontent.com/15316448/28265918-7fd0fcda-6af2-11e7-8ff9-452d0340e52d.png)

Keramik Feuerbox
![2017-07-17_13 16 18](https://user-images.githubusercontent.com/15316448/28265919-7fd2d2b2-6af2-11e7-9b7f-e442a3beeb78.png)
Lehm Pipe
![2017-07-17_13 16 50](https://user-images.githubusercontent.com/15316448/28265922-7fde360c-6af2-11e7-83aa-9ea96b0638b0.png)

Verstärkte Keramik-box
![2017-07-17_13 18 33](https://user-images.githubusercontent.com/15316448/28265921-7fdd107e-6af2-11e7-9e05-2e90427eb049.png)

Lehm Platten
![2017-07-17_13 20 39](https://user-images.githubusercontent.com/15316448/28265970-c1bb8cc8-6af2-11e7-97a5-9a792c3b5b21.png)

**Comment by Dream-Master** [comment]
Clay pipes gibt es in GT

**Comment by Ldmf** [comment]
ja das weiß ich das Problem wäre nur die Herstellung und es ist ja nur eine Idee die mir über Nacht gekommen ist also total unausgereift und co

**Comment by Dream-Master** [comment]
Ja gut aber da zu implementieren kann ich leider nicht.
