### ISSUE TITLE
lootgames unusable item, maybe glitched?

### ISSUE THREAD

**Issue by nroe1337** [GTNewHorizons/NewHorizons#1662]
![2017-07-13_16 40 51](https://user-images.githubusercontent.com/29794591/28192436-004803b4-67eb-11e7-8267-24a7166545b0.png)

Completed my first lootgames today, was quite interesting, but the one of the rewards was this item, and it appears to have no uses and has a name that to me looks like some kind of error. Discord advised that I report the issue here, so here's a screenshot of the item. Pack Version 1.5.04

**Comment by MineAnPlay** [comment]
This is most likely a mistake since Bronze Plasma is kinda impossible :D .

**Comment by Dream-Master** [comment]
Maybe i need to check Loot Tables from chests.

**Comment by Dream-Master** [comment]
hopfully fixed
