### ISSUE TITLE
Railcraft Steam Oven Quest

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1663]
what about adding a quest about the steam oven since it can become very handy at the early stage of the game. The multi smelter quest could follow after that

**Comment by Dream-Master** [comment]
I remember i add such Quests. Will look at it.

**Comment by Dream-Master** [comment]
It wasnt the steam oven. Yes i could add some.

**Comment by MineAnPlay** [comment]
Please don't force to make the Steam oven so that you can unlock the Multi Smelter. They are different things and most people don't use steam other then early LV.

**Comment by Dream-Master** [comment]
Sure I could make quests stay parallel to each other no requirements
