### ISSUE TITLE
Novice Thaumaturge Quest uncompletable "Not Just for Decoration"

### ISSUE THREAD

**Issue by nroe1337** [GTNewHorizons/NewHorizons#1664]
I am trying to turn in the quest "Not Just for Decoration" which requires me to craft 92 Arcane Stone Blocks (476:6) and I have over 100 in my inventory (all self-crafted, I see it is a crafting task) and the quest will not accept any submission past 64/92. I am on pack version 1.5.04 
![2017-07-14_10 09 11](https://user-images.githubusercontent.com/29794591/28222558-e134af30-687c-11e7-9fce-99cd3286933e.png)
![2017-07-14_10 09 03](https://user-images.githubusercontent.com/29794591/28222560-e4d1e0ea-687c-11e7-93b7-92a316d8af63.png)

**Comment by nroe1337** [comment]
after talking to 0lafe on Discord, he suggested I do 1 craft, then open the quest submission, then 1 craft then open quest submission again and that is working for 8 items at a time. Still very glitchy though.

**Comment by Bryfer** [comment]
This happens when you shift click them while crafting

**Comment by Dream-Master** [comment]
@Bryfer no i think it counts when you shift click too. If you carft all this 92 Stones by Hand it should work. Will look at the Quest.
