### ISSUE TITLE
Manyullyn possible to make in smeltery

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1665]
Es gibt fuer manyullyn ein rezept in der schmelze, dort kann man dies auch ausgieben und in gearform im fluid extracter molten machen, und dann im fluid solidifier die barrne, eigentlich bracuht man aber in gt nen ebf und vacuum frezer damit man an manyullyn kommt

**Comment by Dream-Master** [comment]
Ok will look into it.
