### ISSUE TITLE
Thaumcraft Mirrored Glass

### ISSUE THREAD

**Issue by DasSchaaf** [GTNewHorizons/NewHorizons#1668]
Im Thaumonomicon kann man das Rezept vom Mirrored Glass nicht angucken, stürzt dann ab. Im NEI geht das, aber das Rezept funktioniert nicht.

**Comment by Dream-Master** [comment]
Sp
![image](https://user-images.githubusercontent.com/2970688/28289952-de4d54dc-6b44-11e7-9fcf-57b0329cb052.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28290060-3ada8a26-6b45-11e7-93d9-c757bb31cdee.png)
change gemQuicksilver to gemMercury would work.
