### ISSUE TITLE
Vibrant Alloy plates from molten vibrant alloy overridden by GT++

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1669]
Using a fluid solidifier to craft vibrant alloy plates from molten vibrant alloy gives a GT++ version of vibrant alloy plates which aren't compatible with GT vibrant alloy plates. The only recipe that seems to use them is some sort of dire crafting table recipe capacitor bank.

Bending machine still outputs the GT plates.

**Comment by Dream-Master** [comment]
@dryknet1 any idea here why not gives gt variant?

**Comment by draknyte1** [comment]
Last I checked, GT doesn't add it.
If yours does, don't know.

There's a reason I added plates/dusts for EIO materials a year ago, because even though listed in GT's Enum, they were Never used..

**Comment by Dream-Master** [comment]
Yes i add ender io materials to gt. What happend if i switch it off? Did recipes still use it? @draknyte1

**Comment by draknyte1** [comment]
I should probably add a config for those plates.

**Comment by Dream-Master** [comment]
would be nice because i add Materials allready after i add Ender IO in the pack. Same for Steves crats add materials too because make it more easy to change recipes and give them a greg style. (plates, screws and stuff)

**Comment by Dream-Master** [comment]
@draknyte1 Should i open an issue at GT++?

**Comment by draknyte1** [comment]
I've only just started using Sc2 and have noticed that would be a good addition.

**Comment by Dream-Master** [comment]
Yes i added Enforced metal galgadorian and enhanced galgadorian.

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues/112

**Comment by Dream-Master** [comment]
fixed
