### ISSUE TITLE
LV Pump can be crafted with paper rings

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#1670]
Paper seems seems like an odd choice of material for O-rings for a pump, was this an intended recipe?  There's a corresponding recipe using paper rings in the assembler too.

![image](https://user-images.githubusercontent.com/29874719/28280358-5cecab8e-6ad8-11e7-8cce-3e04b7ba4876.png)

**Comment by Dream-Master** [comment]
Yea maybe an old original gt repo recipe. I will remove it.

**Comment by damug** [comment]
Thanks!

**Comment by Dream-Master** [comment]
np
