### ISSUE TITLE
"2x steel" quest is auto completed

### ISSUE THREAD

**Issue by eXoShini** [GTNewHorizons/NewHorizons#1677]
Upon finishing quest "Time to get some steel" next quest for blast furnace expansion is automatically completed due to Retrieval Task which you already got enough components from first quest.
![image](https://user-images.githubusercontent.com/14859263/28433186-fcc370ca-6d8a-11e7-983d-b052487eee03.png)

Also if someone made 8 more firebricks and 1 bricked blast furnace controller he could complete further quest "4x steel" without really having even 2 full blast furnaces again due to Retrieval Task 'fault'.

**Comment by Dream-Master** [comment]
I like crafting quests but no one else. @eXoShini What you suggest to change ?

**Comment by eXoShini** [comment]
Well I guess best idea would be to add retrieval task step of about 16 steel ingots for 2x steel and about 32 steel ingots for 4x steel which is result of blast furnace running and producing steel, that way at least quest can be prevented from completing fast while preserving current quest tasks.

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
i add 64 and 128 steel ingots
