### ISSUE TITLE
Quest: NASA workbench

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1679]
The quest for the NASA workbench / Dire crafting table asks for a Mainframe, but the recipe asks for an advanced circuit.

![image](https://user-images.githubusercontent.com/30087707/28437724-048e8e28-6d9c-11e7-9a54-1eb7a650d36d.png)

![image](https://user-images.githubusercontent.com/30087707/28437816-4d2e558c-6d9c-11e7-8980-eb16591abcf2.png)

**Comment by Dream-Master** [comment]
ok need to fix that.

**Comment by MineAnPlay** [comment]
It should be a mainframe.
