### ISSUE TITLE
Quest: Rocket Engine

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1684]
The Rocket engine quest asks for a filled fuel canister (diesel) but the recipe requires an empty canister. 

![image](https://user-images.githubusercontent.com/30087707/28478663-aa85ea52-6e59-11e7-9070-0c198bd25ad6.png) ![image](https://user-images.githubusercontent.com/30087707/28478760-053b4e60-6e5a-11e7-9010-acbd2fe730a4.png)

![image](https://user-images.githubusercontent.com/30087707/28478693-bdd20140-6e59-11e7-9ef5-51f9a27eee86.png)

**Comment by Dream-Master** [comment]
sure will change it
