### ISSUE TITLE
Electric Treetap and Hoe

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1685]
IC² Electric Treetap and Hoe use 2 LV BAtterys one in recepie it self and one in the power unit

**Comment by Dream-Master** [comment]
Yes will change the recipe will use only one battery.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28489426-0a6fe7aa-6ec4-11e7-943c-e47ae0e94405.png)
![image](https://user-images.githubusercontent.com/2970688/28489434-1ed4710c-6ec4-11e7-96e9-5cf2eddbd80e.png)
