### ISSUE TITLE
[1.5.0.6] Quest: Drawers

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#1687]
The Quest with the Drawers are all Oak only.

**Comment by Dream-Master** [comment]
Sadly the quest book let me only make one kind of drawers. Quests are examples what you can do next a guideline. Drawer quests are optional so far I know.

**Comment by Raccoon2709** [comment]
okay thanks anyways (:

**Comment by Ethryan** [comment]
Dream, i think i can solve this by adding all diffent sizes of drawers to the ore dictionary, if i create 
<ore:drawerFullx1>, <ore:drawerFullx2> and <ore:drawerFullx4>. 

And then if i add them you should be able to direct the quest to accept oredicted items. (This all depends on how many different kind of wood types exist and how much work it is to add them)

**Comment by Dream-Master** [comment]
No not necessary please don't it's a optional quest so let's focus on important stuff

**Comment by Ethryan** [comment]
ok, will put this idea on the backburner until everything else is done.
