### ISSUE TITLE
Quest You Shall Proceed  #40

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1688]
This is an Tier 1 - Steam quest
The overall quest is good. however the quest rewards for this quest..

you get to choose between 6 TINY bronze fluid pipes or an lootbag (basic)

Tiny bronze pipes with their 400mb/s is too low for this tier in my opinion. I think these 6 TINY bronze fluid pipes should get replaced with 6 SMALL bronze fluid pipes
(increase from 400mb/s (20l/t) to 800mb/s (40l/t)

the tiny pipes will not send thru enough steam to power most steam machines

**Comment by Dream-Master** [comment]
Good idea will change it

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28489448-57f99e6c-6ec4-11e7-8935-ed508eaa7230.png)
