### ISSUE TITLE
[1.5.0.6]Quest: Wire Cutter v.0.2 alpha

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#1689]
Quests cant be completed, you need the Iron Plates from Railcraft and you cant craft them anymore since the new update.

**Comment by Bryfer** [comment]
so most likely every quest containing iron / copper / steel is affected by this

**Comment by Dream-Master** [comment]
Maybe I forgot this. The rewards I all ready change. Will check later.
