### ISSUE TITLE
[1.5.0.6] Short Grass BoP

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#1690]
The short Grass from Biomes o' Plenty cant replaced by other blocks. Sounds Strange sorry.

Example you can build on normal grass and it gets deleted. You place a Furnace on a Grass and the Furnace is there. But on Short Grass the Block stucks about the grass.

Its quite random, sometime it works sometimes not. Tried to reproduce it 3/10. No idea what causes it.

**Comment by Dream-Master** [comment]
Screenshots are very helpful @Raccoon2709 if this is only a graphic glitch nothing I can do. Devs from BoP all ready at version 1.11 or 1.12

**Comment by Methes** [comment]
When you place a block to a spot where regular grass is, the grass gets automatically replaced by your block. That's not the case for BoP grass.
Not the modpack's fault, BoP doesn't update for 1.7 and it's like no issue at all. You can close this.
