### ISSUE TITLE
[1.5.0.6] Gravel Dupe

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#1691]
When destroying Gravel with the Hammer you get normaly Sand, but in this version you get Gravel + Sand out of Gravel.. so dupeing as fuck.

**Comment by Bryfer** [comment]
will you get gravel & sand at an 100% chance?
(1 Gravel + 1 Sand Per block of gravel hammered?)

**Comment by Raccoon2709** [comment]
No idea 100% but 10/10 is nearly 100% :b

**Comment by joral** [comment]
Just hammered 1 stack of gravel, got 1 stack of sand + 1 stack of gravel.

**Comment by Dream-Master** [comment]
Ok will check this recipe

**Comment by Dream-Master** [comment]
@Raccoon2709 Screenshots are very helpful here.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28489611-ebd2b540-6ec6-11e7-8d85-ed0a41d16d7c.png)
![image](https://user-images.githubusercontent.com/2970688/28489613-eff535a8-6ec6-11e7-9eb5-26f344a4efea.png)

**Comment by Bryfer** [comment]
Any news on this? It still exists in 2.0

**Comment by Dream-Master** [comment]
I guess. Idk how to fix need help here.

**Comment by Methes** [comment]
If it's too complicated to fix this, just let it be.
You waste metal to get sand, why not.
A bit later you can get cobblegen and use steam/electric hammer for unlimited blocks for energy, so not a big deal imo.

**Comment by richardhendricks** [comment]
Don't see anything right off that looks wrong

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tools/GT_Tool_HardHammer.java#L104

Probably a weird interaction with vanilla, is my guess.  I will at this with low priority since it looks pretty easy to tell if it is something in GT, or in vanilla.

**Comment by ljjmrlion** [comment]
This still exists btw.

**Comment by Dream-Master** [comment]
I know but nothing we can do against it.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/IguanaTweaksTConstruct/pull/12
