### ISSUE TITLE
Cactus cannot be used to substitute for water in recipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1695]
Stone Age "Finite Water?!" quest states that cactus can be used to substitute for most recipes that require water.  However, with experimentation and NEI, it looks like it can't substitute for *any* of them. Notably, the Pam's Harvestcraft or Gregtech recipes that need water.

Running the latest version.

**Comment by Dream-Master** [comment]
You need to fill a water bucket with 8 cacti drops.

**Comment by richardhendricks** [comment]
Thanks for the clarification, when the quest said "substitute" I thought it meant directly. Maybe update the quest to say "can be used to make water".

**Comment by Dream-Master** [comment]
ok.

**Comment by zaglmayr** [comment]
![Image](https://github.com/user-attachments/assets/1a44d508-9542-4d9a-a8dc-e7563410df0a)
Put 8 Kaktus in the workbench and you will get cactus juice (Why Drops??). Put a bucket in the middle and 8 juice around it and you will get water.
