### ISSUE TITLE
Put Bees into gt code 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1698]
Put Bees into gt code from Gendustry

**Comment by draknyte1** [comment]
Did you never port the bee code when Blood did it?
Or just the extra bees you've made with Gendustry?

**Comment by Dream-Master** [comment]
I will modify it that it match with my gendustry bee cfgs

**Comment by Dream-Master** [comment]
I disabled  gt bees atm

**Comment by Dream-Master** [comment]
Planed for 2.0.5
