### ISSUE TITLE
Quest "Something to carry liquids" fails to complete

### ISSUE THREAD

**Issue by PaladinOne** [GTNewHorizons/NewHorizons#170]
Tier 0.5 Quest "Something to carry liquids"
Objective: Craft a Fired Clay Bucket

Smelting an Unfired Clay Bucket in a Furnace produces a Fired Clay Bucket, but the quest does not register the crafting and cannot be completed.

**Comment by Namikon** [comment]
My derp. Changed the task to craft an "unfired clay bucket", which was the original idea anyways (As the hint "don't forget to fire it" might have spoiled)

Will be available in the next version

**Comment by Teteros** [comment]
Issue still present in 2.7.0.4.

**Comment by Namikon** [comment]
Guess someone hasn't added the new HQM file from the Teamspeak folder to the pack? :)

**Comment by Dream-Master** [comment]
Next update i will add it

**Comment by Teteros** [comment]
Fixed in NH 1.0.0.0.
