### ISSUE TITLE
Infernal Block and Sandy Block recipe (Railcraft)

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1700]
Sandy Block requires 2x Sand and 2x Brick to get just 1x Sandy Block. I propose to increase the output to 2x or 4x Sandy Blocks.

Infernal Block requires 4x Soul Sand, 4x Nether Brick and 1x Magma Cream. Output is just 1x Infernal Block. Increase this to 8x Infernal Block.

**Comment by Methes** [comment]
![2017-07-22_12 37 51](https://user-images.githubusercontent.com/8257735/28490449-aad0cb7c-6eda-11e7-8ac2-8898a0c2163b.png)
![2017-07-22_12 37 59](https://user-images.githubusercontent.com/8257735/28490451-ac582652-6eda-11e7-9af1-3462f132d254.png)

**Comment by damug** [comment]
I get why the sandy brick recipe was the way it was at least, 4 bricks = 1 brick block, ergo 2 bricks and 2 sand = 1 sandy brick block.

I got no compelling reason as to why the infernal brick recipe the way it was though.

They're entirely cosmetic blocks though, so no real reason not to make them cheaper to craft.  Variety is always nice when making things after all.

**Comment by Methes** [comment]
Take a look at the commit by Dream just above your post. Changes have already been made ;-).

**Comment by damug** [comment]
See commit at https://github.com/GTNewHorizons/NewHorizons/pull/1725 feel free to disregard if you so desire @Dream-Master

**Comment by Dream-Master** [comment]
@Methes what you think about the changes?

**Comment by Methes** [comment]
Yes this is also fine.
