### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1701]
![2017-07-22_21 37 44](https://user-images.githubusercontent.com/13598309/28491535-19b20254-6f26-11e7-8d9c-562ff40b1a44.png)
![2017-07-22_21 37 46](https://user-images.githubusercontent.com/13598309/28491536-19b2ebce-6f26-11e7-971d-ea8cf5bcba9c.png)

**Comment by Dream-Master** [comment]
And another one. Ok fill fix it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28498387-87777410-6f9c-11e7-9d10-5f4cf51c463b.png)
![image](https://user-images.githubusercontent.com/2970688/28498389-8ad17f2a-6f9c-11e7-85d2-deb055760733.png)
