### ISSUE TITLE
[1.5.0.6] Glider wings

### ISSUE THREAD

**Issue by SPMoo66** [GTNewHorizons/NewHorizons#1703]
The Glider wings quest requires too many steel rods. The recipe for 2 wings only needs 4 rods, but the quest asks for 6 rods.
![quest](https://user-images.githubusercontent.com/17258424/28493316-a0773aaa-6ee2-11e7-83b5-76c128b1591f.PNG)
![wing](https://user-images.githubusercontent.com/17258424/28493317-a1ff8486-6ee2-11e7-9f50-05af53fcc0dd.PNG)
![glider](https://user-images.githubusercontent.com/17258424/28493318-a3d2c174-6ee2-11e7-95cb-693da19b4a3b.PNG)

**Comment by Dream-Master** [comment]
ok need to fix it.

**Comment by Bryfer** [comment]
Aren't you meant to turn two of the rods into screws?

**Comment by SPMoo66** [comment]
At that tier, two rods does not process into four screws. That doesn't line up if that was the intention either.
