### ISSUE TITLE
Steel tanks appear as silver tanks

### ISSUE THREAD

**Issue by iancoolidge89** [GTNewHorizons/NewHorizons#1704]
When you place a steel tank and look at it, it says silver tank.

**Comment by Dream-Master** [comment]
Pic please

**Comment by Dream-Master** [comment]
before they was original a silver Tank but steel match better in the pack. Will change it in the localizer.

**Comment by Dream-Master** [comment]
// --- Steel Tank
NEI.overrideName(<irontank:silverTank>, "Steel Tank");

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28498206-709a0080-6f99-11e7-8977-501735f3f9af.png)
