### ISSUE TITLE
Charcoal from naturas mod wood in furnance.

### ISSUE THREAD

**Issue by NNM42** [GTNewHorizons/NewHorizons#1705]
I can get charcoal by  burning naturas mod wood in furnace. It's a legal?

1.5.0.6 with upd from jenkins #303 {cfg, sz}

**Comment by Dream-Master** [comment]
@NNM42 pc please. A screenshot will help.

**Comment by Dream-Master** [comment]
Ok will fix it. @NNM42 Thanks for report it.
