### ISSUE TITLE
Endless powersource

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1706]
![2017-07-21_22 44 03](https://user-images.githubusercontent.com/27621272/28498381-67cc112a-6f9c-11e7-86c7-2d36b287ae9b.png)
![2017-07-21_22 43 49](https://user-images.githubusercontent.com/27621272/28498385-79bd0128-6f9c-11e7-8039-4b012517bf06.png)

Ich weiß nicht ob dir das schon gesagt wurde aber ich hatte einen weg gefunden viel strom für lau zu erzeugen.
Hydrogen hat eine burnvalue von 20k eu
Alle 2,8 sekunden produziert man ein sodium aus salz.
Dieses sodium wird dann im chemical reactor zu sodium hydroxide und 1bucket hydrogen
Man macht rund 7000eu pro sekunde plus
Man könnte jetzt noch das sodium hydroxide zu weiterem oxygen verarbeiten
P.s ich würde es nerfen aber nicht zu stark sodass es immer noch als eine art powersource bleibt

**Comment by Dream-Master** [comment]
@JohannesGaessler any idea here ?

**Comment by JohannesGaessler** [comment]
This is not intended.
Because of conservation of energy you should not be able to electrolyze salt and then gain netto energy by having the sodium react with water.
I think this way of obtaining energy should be completely removed.

**Comment by Radst0ne** [comment]
Rip my production

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/5bc961959e93aff58f87234591050507a7b9dd1f
