### ISSUE TITLE
Quest 74 is not working. Zeta server.

### ISSUE THREAD

**Issue by Giovanni-NL** [GTNewHorizons/NewHorizons#1707]
Found on Zeta server, 1.5.0.6 
Whether I spawn in the sand, gravel and clay dust, or mine it in the world, the quest book does not see the items in my inventory.  Quest 74 cannot be completed.
This is the Tinker's smeltery, on the Multiblock page.

**Comment by Dream-Master** [comment]
Will check later

**Comment by Raccoon2709** [comment]
Havent had the Problem, my one worked.

**Comment by Dream-Master** [comment]
Did it work in sp ?

**Comment by Dream-Master** [comment]
I play at the moment in sp to test some stuff. I think i open the Tico Quest allready. Will see if i can do it.

**Comment by Giovanni-NL** [comment]
I retried this on SP with 1.5.0.6 and there it did work.  So might be related to the test server, and not the modpack itself.

**Comment by Giovanni-NL** [comment]
Ok, retried on the test server once more.  Now works ok.

Closing issue
