### ISSUE TITLE
Suggestion for quest 52.

### ISSUE THREAD

**Issue by Giovanni-NL** [GTNewHorizons/NewHorizons#1708]
This quest is about making your first glass. On the tier 0.5 stone age page.

I suggest adding making a chisel to step 3 of the quest.  The quest text does mention to 'chisel' clear glass, but it is not clear how to do that, or even which chisel to use.  So to make it more clear, I suggest to also have the player craft that chisel in this quest.

**Comment by Dream-Master** [comment]
Sure why not.
