### ISSUE TITLE
Oreberry Unification Problems

### ISSUE THREAD

**Issue by UltraPeeks** [GTNewHorizons/NewHorizons#171]
Gold and tin oreberries get unificated to simple nuggets.
Iron and copper oreberries get unificated to aluminum oreberries.
Aluminum oreberries can be smelted in alloysmelter to GregTech aluminium ingot.

**Comment by Dream-Master** [comment]
I hope Blood Asp fixt it. I send him a pm

**Comment by Namikon** [comment]
Offtopic: Dream, do you still use your gmx email linked in your Github profile?

**Comment by Dream-Master** [comment]
Yes

**Comment by PaladinOne** [comment]
Okay I just had two Aluminum Oreberries unificate into Gold Oreberries. What?

**Comment by Namikon** [comment]
Every reboot it randomly changes to which oreberry it unifies. It's something that bloodasp needs to fix in gregtech, there is not much Martin can do about it

**Comment by Dream-Master** [comment]
Blood asp not have a new test version for us. I will ask him again about the ore berries.

**Comment by Dream-Master** [comment]
Blood Asp will be tomorow on a Computer an send us maybe  a fix.

**Comment by Teteros** [comment]
Fixed in [GT5 5.08.19](http://ftb.gamepedia.com/GregTech_5_Unofficial/Changelog#5.08.19).
