### ISSUE TITLE
[Recepie] Thaumcraft

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1710]
Nanosuit boots of the traveller und Nano Suit Googles of reavealing brauchen im Rezept leere nano suit teile ist dies gewollt? 2. Die Rezepte Haben einen Energy Crystall drinn ob wohl sie nicht so viel speichern können (möglicherweise nicht nötig als Fix und evlt aufgrund von Balance auch schwierig)

**Comment by Dream-Master** [comment]
Yes they be always empty in all my recipes.
2. 
![image](https://user-images.githubusercontent.com/2970688/28513983-9d60f032-7058-11e7-976f-16e3541268bc.png)
This is the original recipe they using the crystals too. I think not need for change it even if the capacity is not the same or lower then the crastyl.

**Comment by PapaTim68** [comment]
Hier die Tabelle für die Energie änderungen:
| Piece                           | Old Value     | New Value     |
|---------------------------------|---------------|---------------|
| Nanosuit Googles of Revealing   | 1 Million EU  | 2 Million EU  |
| Nanosuit Boots of the Traveller | 1 Million EU  | 2 Million EU  |
| Quantum Googles of Revealing    | 10 Million EU | 20 Million EU |
| Quantum Boots of the Traveller  | 10 Million EU | 20 Million EU |
| Solar Googles of Revealing      | 20 Million EU | 30 Million EU |

**Comment by Dream-Master** [comment]
I will ask the community first before  i make the change.

**Comment by Dream-Master** [comment]
We vote against it. Recipe stay like they are.
