### ISSUE TITLE
weirdest bug ever?

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#1712]
![image](https://user-images.githubusercontent.com/26419635/28504757-42d4a474-6fea-11e7-9fc2-796dbee08d0a.png)

server i'm playing on is 1.4.1.1 and i have the 1.4.1.1 recommended build from the technic launcher, and when i try to log on it gives me this error. we first suspected it to be inputcore, but then i removed inputcore and it told me both messages of rejection, so that can't be it. ????

**Comment by Dream-Master** [comment]
@Blinzer Which server you try to join?

**Comment by Dream-Master** [comment]
fml log i need too.

**Comment by Dream-Master** [comment]
It seems that Twitch Launcher works.

**Comment by Dream-Master** [comment]
@Blinzer if you got more problems just reopen it.
