### ISSUE TITLE
Genetics recipes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1713]
Due to poor documentation some of the recipes need a GT recipe:
- Liquid Growth medium (water + growth medium)
- Bacteria (liquid growth medium + wheat).

Can make the recipe a bit higher tier or using more complex materials, E.G. Compressed plantballs instead of wheat etc.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28576359-12736dc2-7154-11e7-9619-0ea9e8b16d8c.png)
![image](https://user-images.githubusercontent.com/2970688/28576379-1c8f2152-7154-11e7-889d-6d0c09110478.png)
