### ISSUE TITLE
Try to updatin Better Question Mod to 2.0

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1714]
Try to updatin Better Question Mod to 2.0

**Comment by Dream-Master** [comment]
@radstone
Need help if it works.

**Comment by Radst0ne** [comment]
https://minecraft.curseforge.com/projects/better-questing
https://minecraft.curseforge.com/projects/better-questing-rf-expansion
https://minecraft.curseforge.com/projects/better-questing-quest-book
https://minecraft.curseforge.com/projects/bloodyquests

Important note:
QuestProgress.json and Questingparties.json have to be moved from the save directory into the betterquesting folder in the save directory to get old progress.

**Comment by Dream-Master** [comment]
Texture update. Quest hidden
