### ISSUE TITLE
OreDictification of Quests

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/NewHorizons#1716]
Hello, @Dream-Master !
Some of quests in GTNH (especially, basic quest5s from first chapters) don't use neither OreDirct nor metadata wildcard values (when possible) for detecting materials in player's inventory. 
For example, one of these materials is sand. RWG (which is base wordgen mod in this modpack) often generates a lot of **red** sand. But quests detect only regular sand (neither ```<ore:sand>``` nor ```<minecraft:sand:*>```), while recipes use both variants.
Please, check first chapters and allow detecting materials by OreDict (or with metadata wildcard values, hwere possible). These materials are mostly from vanilla (like sand).
P. S. I'm tired from digging small beaches, while I have huge red desert...
P. P.  S. Thank you for your work! I've so much fun with GTNH!

**Comment by Dream-Master** [comment]
Ok will do.

**Comment by Dream-Master** [comment]
Ok sand i can do easy anything else ?

**Comment by OneEyeMaker** [comment]
For now I haven't GTNH Quest book at hand... Now I can't remember another materials...
But don't close this issue (mark **On Hold** or something like that). I think, there are more such quests, and I (*or someone else who follows this repo*) will contact you as soon as find something.

**Comment by Dream-Master** [comment]
sure i let it work in progress

**Comment by OneEyeMaker** [comment]
Quest "Sheep hairdnesser" (Stone age) uses hardcoded ids and meta of GT items instead of using OreDict. Quest book doesn't detect items in my inventory.

**Comment by Dream-Master** [comment]
Ok will look into it later.

**Comment by Dream-Master** [comment]
@OneEyeMaker If you mean the Damscus Steel tools they need an hardcoded mt and nbt. 
Plates are ordicted but screws and rings not necessary in my eyes. Maybe the stick.

**Comment by OneEyeMaker** [comment]
@Dream-Master I'm speaking about iron components (iron plate, screw and ring). I have **_all_** components in my inventory (including sticks) and I **_can_** craft shears. But Quest book doesn't detect these items, even I press 'Detect/Submit', even I craft all them once again (but task is retrieval, not crafting).
I think, all these items should be OreDicted in quest like ```plateAnyIron```, ```screwAnyIron```, ```ringAnyIron``` (like it is done in recipe).

**Comment by Dream-Master** [comment]
Ah ok you mean any iron ok.

**Comment by OneEyeMaker** [comment]
@Dream-Master I mean any iron and add OreDict for **_all_** items (Quest book doesn't detect them by id)

**Comment by Dream-Master** [comment]
But only in this quest ?

**Comment by OneEyeMaker** [comment]
Maybe there is the same issue in other quests. Because GT uses big metadata value (up to 32766) and rarely there are changes in materials and components (=rings/rotors/screws/...), better to use OreDict for quests, which require GT components. I recommend you to check other quests, which require GT components (as retrieval or crafting task) and add OreDict.

Which OreDict to add for items in quest - see final quest item and OreDict used in it's **_recipe_** (for current quest - it is shears, NEI shows recipe which requires ```plateAnyIron```, ```ringAnyIron```, ```screwAnyIron``` and ```stickWood```. So quest should require items with OreDict ```plateAnyIron```, ```ringAnyIron```, ```screwAnyIron``` and ```stickWood```).

**Comment by OneEyeMaker** [comment]
(As I said, if I find these quests, I let you know).

**Comment by Dream-Master** [comment]
K

**Comment by OneEyeMaker** [comment]
@Dream-Master 
The same issue in Multiblock Goals/Smeltery - sand and clay dust OreDicted.

**Comment by OneEyeMaker** [comment]
@Dream-Master 
Also, please, add OreDict tags for **_all_** GT parts. I know, that screws and rings are small - but it is only image (picture, icon of item). Don't forget to add OreDict tag for all these parts (For example, Steam Age/Wirecutter quest doesn't use OreDict).

**Comment by Dream-Master** [comment]
we can open it when we hit the problem again.
