### ISSUE TITLE
Some HarvestCraft recipes are not OreDicted.

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/NewHorizons#1717]
Bug #106 is arisen again in 1.5.0.+. 
Some HarvestCraft recipes don't use OreDict.
I can't make, for example, blueberry/blackbarry/another-berry juice just with Soft mallet and berry (Recipe is hardcoded and requires Juicer and 1 berry).
I guess this bug is arisen at some time earlier due to mod updates.

**Comment by Dream-Master** [comment]
Maybe i have to look over the recipes again.

**Comment by damug** [comment]
I think I fixed most of these berry related recipes in my local version. I will make a pull request later today if you don't get to it first @Dream-Master

**Comment by damug** [comment]
See commits at [https://github.com/GTNewHorizons/NewHorizons/pull/1723](https://github.com/GTNewHorizons/NewHorizons/pull/1723)

**Comment by Dream-Master** [comment]
@damug all issues are solver? can i mark it as fixed ?

**Comment by damug** [comment]
@dream-master 90% there.  to take it all the way would need to add the Natura nether berries to the ore dict so you can use them interchangeably with other berries for recipes like fruit punch.

I will make another commit tonight after work.

**Comment by Dream-Master** [comment]
@damug ok thanks will merge it then.

**Comment by damug** [comment]
That should take care of adding all the nether fruits to the oredict and Natura saguaro cactus, because why not.

**Comment by damug** [comment]
Reopened pull request solely for this update.  Apologies for the inconvenience.

https://github.com/GTNewHorizons/NewHorizons/pull/1738

**Comment by kris449** [comment]
Not sure if this is related, but I discovered today there's no recipe or way to use fruit juice as anything edible, it only works in the fermenter. For comparison, here's some really weird fluids that CAN be consumed in capsule form:

![capsules](https://user-images.githubusercontent.com/26042867/28890511-50e8925c-7795-11e7-8c1b-546521b9e7e8.jpg)

Can we drink fruit juice please?
