### ISSUE TITLE
Tinkers Cosmic Neutronium change to using the extruder

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#1718]
All cosmic neutronium toolparts use the tinkers part builder.

Change this to use the Gregtech Extruder Instead.

**Comment by Dream-Master** [comment]
I can add an additional recipe but not remove the recipe in Tinkers i guess
@Ethryan is this a problem?

**Comment by Ethryan** [comment]
location of the tinkers parts
https://github.com/GTNewHorizons/Avaritia/blob/1.7.10/src/main/java/fox/spiteful/avaritia/compat/ticon/Tonkers.java

**Comment by Dream-Master** [comment]
you do the code change i add the plates.
What tier and recipe i need to choose?
