### ISSUE TITLE
Space Race Quest 3

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1719]
Du sollst einen Dire crafting tabel bauen, dafuer benötigst du ein advanced circuit, die vorbereitung auf diese benötigt allerdings ein mainframe, welcher ja nicht gebracuht wird

**Comment by Dream-Master** [comment]
warum ?

**Comment by Dream-Master** [comment]
Also wieder ein Questbuch recipe konflikt?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28571812-d7bebcc2-7144-11e7-83ea-c9dca5fd6a4a.png)
![image](https://user-images.githubusercontent.com/2970688/28571823-e365b576-7144-11e7-82fa-450b6ff838fd.png)

**Comment by alphaNOVAircraft** [comment]
Dann haben wir eine andere version, da man bei und anstelle des mainframes ein adv circuit braucht

**Comment by Dream-Master** [comment]
ok ich pushe eh später 1.5.0.7
