### ISSUE TITLE
Auto-execution Quests

### ISSUE THREAD

**Issue by maksim789456** [GTNewHorizons/NewHorizons#1721]
Hi Dream-Master
After updating the build, I decided to download the quests (/bq_admin default load)
But I soon found out what kind of glitches
![screenshot_3](https://user-images.githubusercontent.com/8225008/28543781-f9fd1de2-70d1-11e7-890d-b136a5a4786e.png)
In branches Tier 3 - 128 I have not performed one quest

**Comment by Dream-Master** [comment]
What version?

**Comment by maksim789456** [comment]
The last

**Comment by Dream-Master** [comment]
1.5.0.6?

**Comment by maksim789456** [comment]
No,1.5.0.5

**Comment by maksim789456** [comment]
Sorry

**Comment by Dream-Master** [comment]
I need to check it what you need to craft before the Extruder.

**Comment by maksim789456** [comment]
The automatic execution of quests occurs not only in this thread, but also not only with this task

**Comment by maksim789456** [comment]
Here's another
![screenshot_4](https://user-images.githubusercontent.com/8225008/28550693-dfbb3ae6-70f3-11e7-9e78-2fbffd940b4e.png)

**Comment by Dream-Master** [comment]
Did you update from 1.4.1.1 to 1.5.x.x?

**Comment by maksim789456** [comment]
No, from 1.5.0.4 to 1.5.0.5

**Comment by Dream-Master** [comment]
wired maybe if i update to BG Mod 2.0 will fix this idk

**Comment by maksim789456** [comment]
Ok

**Comment by Radst0ne** [comment]
but this happens to me all the time (sometimes reloading database is enough, then corrupted quest starting to popup), I delete the progress of the quest manually

**Comment by Dream-Master** [comment]
Will update to BQ mod 2.0 maybe in the next version
