### ISSUE TITLE
Quest It's time to get more steam #784

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1722]
Please remove stage 6 in this quest.
As the quest states you need Good Circuits to make the Large Gregtech Boiler.
At this point you most will go into MV tier really shortly, so why force the players to make 10 LV turbines? just to complete an quest about an large boiler?
![image](https://user-images.githubusercontent.com/22825059/28547535-97148b40-70cf-11e7-9749-3ae6c8ad15a5.png)

Im also not sure why the Large GT boiler is under "Multiblock Goals" while the Railcraft boiler is under Tier 1 - Steam
isnt both of these multiblock structures..?
(This issue is based on 1.4.1.1, I have yet not double checked if this issue is still valid for 1.5/2.0)

**Comment by Dream-Master** [comment]
Good Questions. The Quest with the 10 Steam Turbines isnt from me but i will check it.
And yes Railcraft Boiler i can put to Multiblocks.

**Comment by Dream-Master** [comment]
remove Turbines and change Quest text.

**Comment by Dream-Master** [comment]
Only as info text for me

Bryfer - Today at 1:03 AM
I think that is pretty good, but unstead of ..and the turbine consumes 80.
It could say 800liters of steam per tick is enough to run 10 basic steam turbines

**Comment by Bryfer** [comment]
quest Steam is never enough #786 
also have the same problem, it wants you to make an additional 5 basic steam turbines.
(Large Steel Boiler)
Titanium and Tungstensteel is good :)
