### ISSUE TITLE
Rye in mortar and pestle = Master Carpentry Hammer

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#1726]
I can't find it in the scripts folder but somehow combining rye with the mortar and pestle gives you a master carpentry hammer.  Seems like it should give flour instead.  Thanks in advance.

![image](https://user-images.githubusercontent.com/29874719/28554907-2bb0eeca-70b1-11e7-8fb5-54acf8f0228f.png)

**Comment by Dream-Master** [comment]
Yes a strange recipe indeed. Not from me. Will look what I can do.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28570391-4221c87c-713e-11e7-8f00-57ddea3c3322.png)
Tested with 1.5.0.7 dev

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28570412-55e40870-713e-11e7-8c86-44d17c9bdaad.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28570426-64399d22-713e-11e7-9291-4173c343fe4f.png)

**Comment by damug** [comment]
Bizarre. Must be something whacky on my end futzing with it.  Thanks for looking.

**Comment by damug** [comment]
I think I found the problem, I also think I managed to fix it here: https://github.com/GTNewHorizons/NewHorizons/pull/1731

Thank you!

**Comment by Dream-Master** [comment]
You remove all the mortar recipes why how people can make it?@damug

**Comment by damug** [comment]
https://github.com/GTNewHorizons/NewHorizons/pull/1739

New pull request.  Removing the recipes for these grain items since the items themselves were removed from extratrees.  Flour should be able to be created as usual, and hops should be acquirable from ic2 crop breeding still.

Be;live these recipes were also the source of the NEI recipe I originally posted since the items they were creating no longer existed.
