### ISSUE TITLE
Imbued fires

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#1727]
- [x] Remove imbued fires from BlockLimiter config
- [x] Remove imbued fires from banned items list on Enjin
- [x] Add appropriate tooltip to all of them

Close this issue once all tasks have been completed

**Comment by Dream-Master** [comment]
What should i wrote?

**Comment by Dream-Master** [comment]
@Namikon like this?

**Comment by Namikon** [comment]
Looks fine. We'll check it out on Zeta then

**Comment by Dream-Master** [comment]
No online atm. Planing an update today with all the new features to test.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28570342-0fe30d30-713e-11e7-9ce2-1c6af647ba31.png)
