### ISSUE TITLE
Access to the Twilight Forest in 1.4.0.1 vs 1.4.1.1

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#1728]
So, one of the first things I noticed when going from 1.4.0.1 to 1.4.1.1 is how access the Twilight Forest has been bottle-necked to LV. This is a decision which heavily influences the overall impact of the mod as a whole in many ways, the main one being is that it chokes a lot of speedrun strategies I've been using to gather early resources and increase my character's efficiency so I don't have to waste as much time doing pointless grinding in the progression system. This is probably not something many people are aware of since I've never seen anyone outside of myself doing it, but the entire Twilight Forest can be completed in GTNH even if you start it with absolutely nothing as long as you are a skilled fighter and tactician. The resources you can acquire there are all guarded and provide a skill-reward dynamic which can only be classified as very good game design, and I am a heavy believer that this should be preserved so that there is more than one type of way to progress in the pack. Yes, GTNH is tehcnology centered, but what was created, even if by accident, is a pack which has the best of both worlds(at least in the beginning, as it lacks midgame exploration/adventure/combat content). There is no reason to purposely ruin that. I am going to list the pros and cons of having the twilight forest in the game and accessible before creating any technology, which was the case in 1.4.0.1:

Pros:

- Rewards the player for knowing how to perform well within minecraft mechanics
- Near perfect risk-reward balance in acquiring the resources available in the world
- Provides protection from early hazards which can be unfair and unnecessarily unforgiving such as darkness and hunger
- Has a very powerful independent progression system which leads naturally into technology
- Heavily reduces the luck and RNG grind in finding many different ores
- Lines up perfectly with the progression of the pack and doesn't help you skip any steps in machinery

Cons:

- Early accessibility to ample amounts of Iron, Gold, Redstone, Lapis, Diamonds, Steeleaf, Ironwood, and relatively powerful tools such as the lich staff, minotaur axe, the mazebreaker, silk touch pickaxes, and armor that is as strong as diamond
- Provides protection from early hazards which can be unfair and unnecessarily unforgiving such as darkness and hunger
- Allows players to skip combat-centered weaknesses(not having good armor or weapons to fight) that would have existed if there was no access

That's all that comes to mind to me for now.  I'm willing to discuss options to implement it beyond the item that opens the portal, such as acquiring it through other adventuring means first.

**Comment by Dream-Master** [comment]
I like the changes.
