### ISSUE TITLE
Incorrect Irradiant Reinforced Tungsten Steel Plate Recipe

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#1729]
>// --- Irradiant Reinforced Tungsten Steel Plate
recipes.addShaped(<dreamcraft:item.IrradiantReinforcedTungstenSteelPlate>, [
[<ore:screwRedAlloy>, <AdvancedSolarPanel:asp_crafting_items:1>, <ore:screwRedAlloy>],
[<ore:plateKnightmetal>, <dreamcraft:item.ReinforcedTungstenIronPlate>, <ore:plateKnightmetal>],
[<ore:screwRedAlloy>, <ore:platePlutonium>, <ore:screwRedAlloy>]]);

It should be using Reinforced Tungsten Steel Iron Plate not Reinforced Tungsten Iron Plate

**Comment by Dream-Master** [comment]
Ok will check it.
