### ISSUE TITLE
maintenance hatch can't be crafted with RC crowbar

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#1732]
It's a quality of live thing but I had to craft a GT crowbar to craft the maintenance hatch.
Would be cool to add a second recipe that's basically the same but has the RC crowbar instead of the gt meta item.

**Comment by Dream-Master** [comment]
Isn't this ore dicted? Did you try it allready?

**Comment by noobyaran9** [comment]
GT crowbar is oredicted as  craftingToolCrowbar, but RC crowbar is not.

**Comment by Dream-Master** [comment]
Maybe need to irduct that crowbar

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28617593-34d48916-7201-11e7-9eea-4abfff06c6e3.png)

**Comment by KaptenLada** [comment]
Hey this doesn't work if the crowbar is damaged
