### ISSUE TITLE
obsidian from xp and TiCo pickaxe tiers

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#1733]
I would suggest removing the recipe to get obsidian dust from xp since the block is gated behind the steel pickaxe tier and it's actually cool that you reach the point where you can break it. Also finding obsidian or lava in the world added to the exploring imo.
Obsidian dust from xp also makes players able to skip throught pickaxe tiers in Tinkers Construct since you can go from iron to obsidian or even alumite without ever getting a bronze or a steel pickaxe head.
So yeah my suggestion is to remove the obsidian dust recipe from xp buckets and in addition to that I would highly suggest changing the iron parts of the alumite alloy to steel since that makes more sense.

**Comment by Dream-Master** [comment]
Sure will do.

**Comment by Drobac** [comment]
No disabling. There are other wats to get obsidian tier picks then obby dust. The dust was specially put in the exp crafting tp help with early game tank crafting

**Comment by Dream-Master** [comment]
Maybe i need to disable obsidian dust smelting in the smeltery

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28616319-9d39fb1c-71fc-11e7-8161-f20564229239.png)
![image](https://user-images.githubusercontent.com/2970688/28616327-a0a7ac36-71fc-11e7-9c64-f499864d65db.png)

**Comment by WarlordWossman** [comment]
@Drobac I guess the biggest issue I had was the alumite but that's gone now with steel in it. Never felt like tanks were too hard to get tho if you have to harvest obsidian by hand but might just be my opinion (and I do know the nether trick with blood so it might not be the best one to judge off)
