### ISSUE TITLE
Quest We need big toys #783

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1734]
This quest is connected to the Large STEEL boiler.
however it required Titanium to be completed currently because it requires an Normal sized Turbine.
![image](https://user-images.githubusercontent.com/22825059/28613489-c928025a-71f2-11e7-84d4-40001b8521e8.png)

change the turbine size to an small turbine in the quest so people can build/complete the Large turbine quest before titanium tier
An small turbine requires Magnalium, same material used to make the turbine itself
(tested in 1.4.1.1)

**Comment by Dream-Master** [comment]
ok i could change this or remove the requirements
