### ISSUE TITLE
Wrong quest description

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/NewHorizons#1735]
The quest named "Basic Circuit Assembler" has a Typo as seen in the attached screenshot.
A MV Circuit Assembler is not needed.
Version: 1.5.0.7
Quest ID: 795

![2017-07-26_15 53 18](https://user-images.githubusercontent.com/23403241/28626548-9402f94a-721f-11e7-83c2-e25034b374e8.png)

**Comment by Dream-Master** [comment]
Ok will cahnge text. @Dacer1 Thanks.
