### ISSUE TITLE
[delta] issue with robots from opencomputers

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1736]
the robot from opencomputers seems able to bypass protection of the plugin used to avoid people to destroy blocks on warp zones in delta and maybe also town plugin (not tested). I don't know if this happen on upsilon too. I think the robot's fake player is not blacklisted in the config.

**Comment by Dream-Master** [comment]
@Namikon can you laook at it please.

**Comment by Namikon** [comment]
Forge mods cannot be blocked by bukkit plugins. To solve this, protected regions have to be recreated using admin towns

**Comment by repo-alt** [comment]
Somehow I doubt that any young griefer will have enough patience to reach HV to build a robot

**Comment by boubou19** [comment]
well in delta you can get zpm in atlantis for exemple, or a stargate on planets, spawn,etc

**Comment by Dream-Master** [comment]
i close this now its one year old

**Comment by boubou19** [comment]
it's still happening tho.

**Comment by Dream-Master** [comment]
@boubou19 what i can do ?

**Comment by boubou19** [comment]
if you can disable fake players in those area then it's fixed otherwise i guess you can do nothing

**Comment by Dream-Master** [comment]
sadly i cant. Need @Namikon or @bigbass1997
