### ISSUE TITLE
Modpack update quest reload

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1737]
To make so modpack update dont require running ```/bq_admin default load``` every time you update maybe add module to GTNH core that will create raw file in every world folder *(lets say itll be named "GTNH_ver")* and check it on load comparing to modpack version it has stored in config. If version differs it would run ```/bq_admin default load``` command automatically and change raw file contents to its own version.

**Comment by Dream-Master** [comment]
If this is possible sure why not.

**Comment by Radst0ne** [comment]
but does it require cheats on?

**Comment by richardhendricks** [comment]
Quest added for @bartimaeusnek CB for BQ block.
