### ISSUE TITLE
Quest #697 2x Steel

### ISSUE THREAD

**Issue by compwiz91** [GTNewHorizons/NewHorizons#1740]
This quest recommends creating a second  Blast furnace. However it wants the users to make the now depreciated Bronze Plated Blast furnace. I assume you'll want to update it to either create a second Bricked Blast Furnace or something else.

This was on version 1.5.0.5 of the modpack.

**Comment by Bluebine** [comment]
It's fixed on the latest version already. Update your modpack before you make any issues, because a lot of problems get patched.

**Comment by Bryfer** [comment]
#1603 is similar and fixed
