### ISSUE TITLE
[Question/suggestion] Questbook auto-update and splash screen

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1741]
Is there any way to have the questbook auto-update for each new version update?
I have a single player map and I prefer being up-to-date with the latest version, but for new each version I have to: 
- enable cheats (Open to LAN -> Allow cheats: On -> Start LAN) 
- run '/bq_admin default load' 
- then 'Save and quit' 
- reload the map (otherwise monster do not show on the minimap)

Can this be done faster or automated? :-)

Also a suggestion for the Questbook! 
Could you change it so you go to the quest section immediately and don't have to click the 'Quests' button on the GT NH splash screen **everytime** you open the quest book?

**Comment by Radst0ne** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1737

**Comment by Methes** [comment]
It's a workaround but you might be able to set up a command block with the command and just press a button each update until/if it's solved internally.

**Comment by richardhendricks** [comment]
CQ for BQ mod added.  We will add a quest to make the block.  Stick/dirt/gravel shapeless recipe will make it.
