### ISSUE TITLE
Ammonia quest can't be completed in MV

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1742]
In MV there's a quest to make ammonia, but the way the game tells you to make it (combining hydrogen and nitrogen) needs a HV chemical reactor to be done.

**Comment by kris449** [comment]
You can do it in MV, you just need a brewery, a distillery and a fermenter..y?

**Comment by Bluebine** [comment]
Yeah, sorry, I should've made that more clear.
You can actually make ammonia in LV the way you said, but the quest tells you to get and mix hydrogen and nitrogen, which needs a HV chemical reactor (it takes 384 volts)

**Comment by Dream-Master** [comment]
Will change it the right way and machine use.

**Comment by kris449** [comment]
You can't do it in LV, the brewery requires aluminium.

**Comment by Lainiel** [comment]
I just wanted to add that you can make nitrogen dioxide for ethanone just by using oxygen, nitrogen and water. No need to make ammonia and waste hydrogen. You just need to centrifuge some air and add a bit of oxygen and water.

**Comment by Dream-Master** [comment]
Demethylamine need Amonia.

**Comment by Dream-Master** [comment]
@Lainiel This was an old recipe wrongly not removed. The Larfge chemical reactor you can make in MV but i move Quests to hv.
