### ISSUE TITLE
[Quest suggestion] GT Plunger 

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1743]
Add a quest that explains the GT plunger (clear items stuck in pipes, clear fluid input slot, maybe essentia). 
I only leaned about this item by finding issue #994 , and have so far been breaking all my machines to empty the input slot...

Perhaps place the quest below the Basic Chemical Reactor in the Tier 2 tab. 
Made with 3 rubber sheets and 2 steel rods.

**Comment by Drobac** [comment]
+1 for this

**Comment by Dream-Master** [comment]
Ok will add.
