### ISSUE TITLE
Tier 2 - Incorrect info in Gallium Arsenide Quest

### ISSUE THREAD

**Issue by DonArmadillo** [GTNewHorizons/NewHorizons#1744]
In the Tier 2 - 32 (LV) in the Gallium Arsenide Quest (ID 836) a line in the quest description says that one can find full zinc ores in the nether. That isn't true.

![screeny shot 27 jul 2017 9 56 23 pm](https://user-images.githubusercontent.com/25957324/28690934-4db6d540-731b-11e7-8228-684885ac16f6.png)

 I bet whoever wrote this meant that once can find "full" sphalerite ores (around ore in Sulphur Vein height 5-20 in the nether) Which can be processed into a tiny bit of Gallium.

![screeny shot 27 jul 2017 10 37 49 pm](https://user-images.githubusercontent.com/25957324/28691205-5ffae830-731c-11e7-91a3-55e476ebac8d.png)

Awesome pack and thanks in advance for the fix!

**Comment by Anarack** [comment]
Well when this was written you couldn't get gallium out of sphalerite so you had to find small zinc ores, this should be updated to note that gallium can be obtained from sphalerite and arsenic can be gotten from cobaltite ore instead of having to find small realgar ore.

**Comment by Dream-Master** [comment]
Sure small ores I have to change that. Since 1.5.0.7 arsenic can be get out of cobalt and cobalite. I need to update this.
