### ISSUE TITLE
Blast furnace dupe for Sulfur Dioxide (7036:510) output recipies

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#1745]
There's dupe in recipies for Electric Blast Furnace which have Sulfur Dioxide (7036:510) as output liquid (as example for Cobaltite Dust (7032:2827) with 3000 mB Oxygen (7036:95) recipie http://imgur.com/Uv7dEy8)
It continues to dupe (every tick?) until there's any energy left. Results: http://imgur.com/dOgJ08y
EBF setup: Controller, Maintance, 1 Input\Output Bus, 1 Input\Output Hatch, 2 LV Energy Hatches
Output Hatch existance in EBF doesnt matters.

**Comment by Dream-Master** [comment]
Yes i take over the code from the main branch which will fix this issue.

**Comment by Dream-Master** [comment]
Its fixed now. You need a fluid output hatch on top layer in the ebf to get those liquid.

**Comment by Dream-Master** [comment]
@rekongstor can you try it if it works?

**Comment by rekongstor** [comment]
@Dream-Master sure
