### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1746]
I know that I already created a similiar issue in the past, but this time I got a more detailed log
https://pastebin.com/B35dNK2L
Maybe worth to mention is: these disconnects dont just happen randomly, it also happens every time changing to a different dimension

**Comment by Radst0ne** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1296

**Comment by Dream-Master** [comment]
Will be in 1.5.0.8 the new journeymap

**Comment by Radst0ne** [comment]
sadly journeymap didnt fix the issue

**Comment by Dream-Master** [comment]
oh ok. So any other guesses?

**Comment by Radst0ne** [comment]
Im not entirely sure but Im wondering I cant be the only one having this problem

**Comment by Radst0ne** [comment]
okay I removed all the mods and scripts so only "vanilla forge" and it works without any problems so I think it has to be a mod conflict

**Comment by Dream-Master** [comment]
Hard to say what mod it is without any stacktrace of a mod.

**Comment by Lainiel** [comment]
You're not the only one having the issue. My friend gets kicked from the server I'm hosting thanks to the NetworkDispathcer Exception all the time.

Here's the log: https://puu.sh/wYXt6/f0b3759695.log

Just serach for NetworkDispatcher exception in the log and you'll see plenty of them.
