### ISSUE TITLE
Suggestion regarding the early game Brick Form

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/NewHorizons#1747]
Issue: The Brick Form used in early game recipes such as coke oven bricks returns after 1 crafting process is done which makes it incredibly tedious to craft multiple coke ovens etc.
Suggestion: Making the Brick Form stay in the crafting grid because it is uncomsumable anyway.

(Reminder: I am not experienced in the modding of any recipes/mods so if this suggestion is not able to get realised, i am sorry for wasting someone's time.)

Thanks

**Comment by Dream-Master** [comment]
This is not possible. The recipe stay in java code and have a tag to be give back. I try to override it with minetweaker commands will duplicate the form each brick you make. In the bronze age bricks can make another way.

**Comment by damug** [comment]
There's a kind of work around for this too.  You can fill every slot in your inventory with something and that way the brick form will stay in the crafting grid.

**Comment by OneEyeMaker** [comment]
@Dream-Master Remove recipe from Java and modify item (in Java) to make it consumable in crafts (usable just once, like any other item). After this move **_all_** recipes from Java to MT. And write each recipe like this:
```
recipes.addShaped(<recipe_output>, [
    [<item>, <item>, <item>],
    [<item>, <wooden_form>.transformReplace(<wooden_form>), <item>],
    [<item>, <item>, <item>]
]);
```

@Dream-Master  If you don't change Java code for item - you will dupe it each time, like you said.

**Comment by OneEyeMaker** [comment]
I guess, it's here:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/item/WoodenBrickFormProperties.java#L22
Change this to ```false``` and recipe (above) should work.

**Comment by Dream-Master** [comment]
That's what I don't want. My end goal is remove all minetweaker script and put the recipes to code.

**Comment by Dream-Master** [comment]
If it is possible to make such a thing in code i am open for it @OneEyeMaker

**Comment by Dream-Master** [comment]
can you do a pull request for me i think this will be much better @OneEyeMaker

**Comment by OneEyeMaker** [comment]
Just add this:
```
@Override
public boolean doesContainerItemLeaveCraftingGrid(ItemStack itemStack)
{
    return !hasContainerItem(itemStack);
}
```
after this line:
https://github.com/GTNewHorizons/Yamcl/blob/master/src/main/java/eu/usrv/yamcore/items/ModSimpleBaseItem.java#L101
//I don't want to download JDK, install IDEA and so on.

**Comment by Dream-Master** [comment]
ok will try

**Comment by OneEyeMaker** [comment]
@Dream-Master @Namikon 
Excuse me, code above should be added to custom *Item* instance.

**Comment by Namikon** [comment]
Pending; Will add that to Yamcore as ExtendedItemProperties
