### ISSUE TITLE
Powering RF Machines with more than 32 EU will cause a serious explosion

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#175]
I just tried it in creative. Any RF machine from forestry will blow up in a massive explosion if provided with more than 32 EU. The amperage doesnt matter, but the voltage must **NOT** exceed 32 EU.

**Comment by PaladinOne** [comment]
I don't think this is actually a bug. When BloodAsp added support for powering RF machines with EU, he made it possible for them to explode on overvoltage.
http://forum.industrial-craft.net/index.php?page=Thread&postID=187973#post187973

**Comment by Namikon** [comment]
True, it's not a bug. I just opened an issue because I think we must (or bloodasp must ) add some tool tips or warnings about that. If the explosion would simply destroy the machine, ok. But the way it is now is just unfair. Also because the machines are nerfed in their recipes and are not trivial to craft

**Comment by Dream-Master** [comment]
Have to asking blood asp about a tool tip. I will do this later.

**Comment by Dream-Master** [comment]
So Tooltips has to be added.

**Comment by Dream-Master** [comment]
I disable the explosion i think ;-)
