### ISSUE TITLE
[Quest] Tier 1 Schematic

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1750]
The quest for the Rocket Tier 1 Schematic is wrongly opened after the Tier 1 rocket has been crafted, but is needed for crafting the rocket.
The schematic quest should be placed before the Rocket quest. 

![image](https://user-images.githubusercontent.com/30087707/28711984-b4a1352a-7389-11e7-85e9-2eeebb1525c9.png)

**Comment by Dream-Master** [comment]
Oh yes need to change the denpendencies.
