### ISSUE TITLE
[Mod Suggestion] DualHotbars (QoL)

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1751]
There is this mod called DualHotbars, it gives you a second hotbar you can scroll through. This does not mean it gives you an extra row of inventory space, it merely allows you to access the top row of your inventory the same way you normally access the bottom row.

https://media-curse.cursecdn.com/attachments/133/265/2014-12-01_14.png

It's a tiny mod, doesn't add any loading time as far as I am aware, but it's nice Quality of life, especially considering the large amount of tools and such in GTNH.

You can install it client side only, but it does not allow you to actually use the top bar, it only shows it.

**Comment by Bryfer** [comment]
There is already a feature like this ingame 
Tinkers' construct travellers belt

**Comment by Dream-Master** [comment]
@Bryfer @mtesseracttech oh yes forgot about it allready. Sure this will work too.

**Comment by Methes** [comment]
Not sure if it's still a problem in our version of TiCo, but Ethoslab had problems with the belt deleting all his items from the toolbar. Better do a research first before using that.

**Comment by Bryfer** [comment]
by deleting all items did you mean it STORED all items? did you ty pressing the same button again? or did they get voided?
I've never had any issues with the tinkers' belt

**Comment by Methes** [comment]
I've just watched back the episode and I remembered it wrong, he lost the belt and all the items it contained with it.
So if you lose the belt (upon death or by mistake), you lose the items it stores. That's it, sorry for misleading.

**Comment by Dream-Master** [comment]
ok np .

**Comment by mtesseracttech** [comment]
That seems pretty bad. As mentioned before, DualHotbars only shows(and gives direct access to) the top row of your inventory slots, it does not store items any differently. To me that seems like a different use case.

**Comment by Dream-Master** [comment]
No we dont need new mods.
