### ISSUE TITLE
Fluid Ejector Upgrade (IC2) has no recipe

### ISSUE THREAD

**Issue by AmishInvader** [GTNewHorizons/NewHorizons#1753]
1.5.0.7 GT New Horizons

'Fluid Distributor' from IC2 requires  'Fluid Ejector Upgrade' to craft, but the fluid ejectors don't have a recipe.

The ejectors can be replaced with LV pumps to fix, or given an assembler recipe of a circuit+lv pump+144 molten copper.

**Comment by Dream-Master** [comment]
Will check it.

**Comment by Dream-Master** [comment]
recipe are now moved to code due recipe conflicts.
