### ISSUE TITLE
[Quest] Novice Thaumaturge Fuuuuuu...(sion)!

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1756]
It should be considered changing the Quest objective to a detection and not a crafting Task
Not only the Fuuuuusion Quest some of the others might be also objective of change!

**Comment by Dream-Master** [comment]
Allready fixed

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28747195-8f946d18-7499-11e7-8f24-782ce6813398.png)
