### ISSUE TITLE
Macerator recipe missing - End Powder Ore

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#1757]
Tested in version 1.4.1.1

I mined a bunch of End Powder ore (itemID 865) with silk touch and expected an recipe for this item.

Right now when mining them with silk touch, you get an useless item. you can place it in the world and break it with an pickaxe without silk touch to get End Powder.

I suggest to add an pulveriser/macerator recipe for this ore. 
1 End Powder Ore(ItemID 865)  -> 2 End Powder(ItemID 4825)

**Comment by Bluebine** [comment]
Can confirm in 1.5.0.7.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28751371-e801a882-7505-11e7-9a8a-7e2d4d591c80.png)
![image](https://user-images.githubusercontent.com/2970688/28751372-edb3661c-7505-11e7-8987-e4119569658d.png)
