### ISSUE TITLE
(Quest Suggestion) Add quest about Super Tanks

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1758]
Like the title says, it'd be a nice thing to have. There's quests for the ULV tank through HV tank, but after that you can get super tanks. The first of these should be available after completing the quests Ender not-so-IO and Better Tank... HV Tank. After that, a HV quest could have a Super Tank II retrieval goal, and then mention how there's versions of the Super Tank/ Quantum Tank all the way up to UV that store more and more.

I found the Super Tanks to be really useful, once you get them a single tank can replace a decently sized iron or steel railcraft tank, at the cost of needing some circuits and aluminium plates. It'd be nice to have quests about them so new players know about them.

**Comment by Dream-Master** [comment]
Ok will add it.
