### ISSUE TITLE
Additional Quest Punji Sticks and Bamboo fence

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1760]
Make additional low level protection quests bamboo fence and punji sticks as quests.

**Comment by Bryfer** [comment]
I'd prefer this quest to be any fence with any gate

**Comment by Dream-Master** [comment]
What I mean is you can place bamboo and it growth 3 high make a fence like with berry bushes. Punji Sticks slows down player or mobs so you can make a hole around your base and put those sticks in. Normal fence are different.
