### ISSUE TITLE
[Suggestion] Add a way to craft the special Adventure Backpacks

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1762]
It would be nice if there was a way to craft the special adventure backpacks through TC, such as the bat backpack. This could perhaps be an infusion of a basic adventure backpack + sensor lenses + travellers goggles + wool of bat + salis mundis, with a large amount of Lux and Sensus.
I believe there are also other backpacks that could have recipes in the same kind of way.
Also logically it would make sense for these to at least be craftable in some way.

**Comment by Dream-Master** [comment]
Adventure backpack have any special abilities ?

**Comment by mtesseracttech** [comment]
Some do indeed, the bat backpack for example gives the player night vision

**Comment by Dream-Master** [comment]
and the Adventure Backpack ?

**Comment by mtesseracttech** [comment]
the normal one doesn't do anything except for hold some items/liquids

**Comment by Dream-Master** [comment]
Sorry i misunderstand. What Backpacks are not craftable more?

**Comment by Drobac** [comment]
All of them are craftable. Have been for a while
