### ISSUE TITLE
[Dupe] Witchery plants (Spanish and Ember Moss)

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#1763]
#### Modpack version 1.4.1.1

I've been doing Witchery stuff, mostly  Mutandis on saplings. Of course Ember Moss and Spanish Moss needs to be harvested with shears. So i used Ender IO Dark Steal Shears that are Empowered II and they dropped two plants instead of one.

![2017-07-30_21 28 36](https://user-images.githubusercontent.com/27481104/28756426-518e5ce2-756e-11e7-9e64-386829bf8fba.png)
![2017-07-30_21 28 43](https://user-images.githubusercontent.com/27481104/28756427-56a1f130-756e-11e7-9384-b355184c5694.png)
![2017-07-30_21 28 46](https://user-images.githubusercontent.com/27481104/28756429-5d908d1c-756e-11e7-9abe-796f55a2788d.png)

**Comment by Dream-Master** [comment]
Witchery is closed source so i am not sure what i can do here.

**Comment by mulisz100** [comment]
Hmm... well then, i won't be using those shears with Witchery stuff

**Comment by Drobac** [comment]
Although it is a dupe issue, fortunately both of those plants are very low tier and easy to get in any case. So could be worse

**Comment by mulisz100** [comment]
Yeah, i guess you're right Drobac

**Comment by Dream-Master** [comment]
@mulisz100 thanks for report it but i close this issue now.
