### ISSUE TITLE
Extra Utilities Drum requires meteoric steel rings

### ISSUE THREAD

**Issue by AmishInvader** [GTNewHorizons/NewHorizons#1764]
1.5.0.7 

Unsure if this is intended.  All the other components are plain steel.

**Comment by Bryfer** [comment]
intended as far as I know.
if you want an large non-movable tank you should build the Super tank (multiple tiers available)

**Comment by Ethryan** [comment]
That is intended, the drum is overpowered in early game.

**Comment by Dream-Master** [comment]
@AmishInvader yes the drum recipe is intended. I want it after visiting Moon that's why Meteoric steel.
