### ISSUE TITLE
Lootgames disconnect

### ISSUE THREAD

**Issue by Diresheep** [GTNewHorizons/NewHorizons#1765]
#### Which modpack version are you using?
1.4.11
#### If in multiplayer; On which server does this happen? 
personal server
#### What did you try to do, and what did you expect to happen?
clicked a block in lootgames to trigger a loss, disconnected from server with this error message:

30.07 19:25:53 [Server] INFO java.lang.IllegalArgumentException 30.07 19:25:53 [Server] INFO at net.minecraft.util.WeightedRandom.func_76269_a(WeightedRandom.java:82) ~[qv.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.util.WeightedRandom.func_76274_a(WeightedRandom.java:113) ~[qv.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:37) ~[qx.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.tiles.TELightGameBlock.spawnLootChest(TELightGameBlock.java:617) ~[TELightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.tiles.TELightGameBlock.processGameOver(TELightGameBlock.java:542) ~[TELightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.tiles.TELightGameBlock.handleBlockInput(TELightGameBlock.java:414) ~[TELightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.tiles.TELightGameBlock.onBlockClickedByPlayer(TELightGameBlock.java:240) ~[TELightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.tiles.TELightGameBlock.onBlockClickedByPlayer(TELightGameBlock.java:254) ~[TELightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at eu.usrv.lootgames.gol.blocks.BlockLightGameBlock.func_149727_a(BlockLightGameBlock.java:146) ~[BlockLightGameBlock.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?] 30.07 19:25:53 [Server] INFO at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?] 30.07 19:25:53 [Server] INFO at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?] 30.07 19:25:53 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Namikon** [comment]
Probably an empty loot list or the list contains an invalid Item. Need to investigate this further

**Comment by Dream-Master** [comment]
@Diresheep look in your TooMuchLoot folder in the configs if chest1, ......, chest4.xml exist.

**Comment by Diresheep** [comment]
Possibly related to https://github.com/GTNewHorizons/NewHorizons/issues/1400

downloaded fresh server files a couple weeks ago and didnt correct this issue, so again, chest1 has no closing </LootGroup>
