### ISSUE TITLE
Steve Carts chuncloader module to cheap.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1766]
Steve Carts chuncloader module to cheap. Stainless steel or Titanium would be a better material.

**Comment by MineAnPlay** [comment]
Keep it as stainless steel because I think it only does the chunk it is in (Didn't test). If it does a bigger range then yes upgrade it to titanium.

**Comment by Dream-Master** [comment]
no 3x3 chunks.

https://ftbwiki.org/Chunk_Loader_(Steve%27s_Carts_2)
