### ISSUE TITLE
[Quest] Iron Plate not "OreDictionaried"

### ISSUE THREAD

**Issue by isipare** [GTNewHorizons/NewHorizons#1767]
#### Which modpack version are you using?
1.5.0.7

#### If in multiplayer; On which server does this happen? 
Not in multiplayer.

#### What did you try to do, and what did you expect to happen?
I can only craft the IC2 iron plate but those are not accepted by the quest "Wire Cutter v.0.2alpha". This quest is expecting three iron plate from Railcraft instead.

#### What happend instead? (Attach screenshots if needed)
Nothing since I can't craft the Railcraft version. And cheated in Iron plate do not register as crafted.
So i'm stuck on this quest.

#### What do you suggest instead/what changes do you propose?
If you confirm the issue is that the iron plate form IC2/Railcraft are not Oredictionaried, then just correct it.
If it's another problem or an error on my part, just correct me.

Thank you for the help and the amazing modpack.

**Comment by OneEyeMaker** [comment]
There are some quests, which doesn't use OreDict.
If you find another one, you can report about it here: #1716

**Comment by AmishInvader** [comment]
Using '/bq_admin default load' will fix this if you're using 1.5.0.7.  I think you need to do that each update if you used the questbook on an earlier version.

**Comment by isipare** [comment]
The '/bq_admin default load' command worked perfectly, thank you.
And I will report if I find other quest with that problem.
Thank you.
