### ISSUE TITLE
Infinite DUP from EBF.

### ISSUE THREAD

**Issue by NNM42** [GTNewHorizons/NewHorizons#1769]
#### Which modpack version are you using?
1.5.0.7
#### If in multiplayer; On which server does this happen? 
yep private server
#### What did you try to do, and what did you expect to happen?
processing resources into EBF
#### What happend instead? (Attach screenshots if needed)
infinite result
#### What do you suggest instead/what changes do you propose?
hm... don't correct this. :c 

just see this: https://clips.twitch.tv/ObliqueHelpfulDoveRedCoat
*russian lang*

**Comment by Dream-Master** [comment]
Already reported and hopefully fixed in GTNH 1.5.0.8 soon.
