### ISSUE TITLE
Asteroid ore gen issue

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#177]
None of the GT ores spawn on the asteroid dimension

**Comment by Dream-Master** [comment]
I have to delete the dimension. We testing all with galacticraft 334 now we have galacticraft 339 maybe thtas the reason.

**Comment by Namikon** [comment]
I made a boo. Will fix it tomorrow

**Comment by Namikon** [comment]
Ok, this was.. crazy. I changed stuff in almost every function of galacticgreg, and i might have found the issue for weird asteroids. Newest commit of v0.8 is ready-to-be-tested in a local environment, as almost every aspect of Orespawn has been changed (I shall call it "easyfied". Is that a word?)

There are also 3 new config options; One for debug logs, one for tracelogs and one to profile OreGen ingame, so you can type "/ggregprofiler" and it will display the average oregen-time of the last 50 oregen cycles it had, (if you set that config option to true, obviously)

Be aware that "trace" will produce > 1GB logfiles easily as it's intended to "trace" the whole oreGen process in every possible way.

I shall repeat: This is a test-version, that might contain bugs. I'm sorry but we have to test every Dimension again.

**Comment by Dream-Master** [comment]
@Namikon TS?

**Comment by Dream-Master** [comment]
this versin is from yesterday?

**Comment by Dream-Master** [comment]
Testing Version 0.8.1

**Comment by Drobac** [comment]
Think that the amount of ore generating per asteroid was set too low, the biggest asteroids had about 200-300 ore in total. Need to explore some more (went a few thousand blocks in each direction) but still havent found naquadah

**Comment by Dream-Master** [comment]
Naqudah spawns now only from level 10 to 60

**Comment by Dream-Master** [comment]
I will add Tier 4 rocket recipes soon. Have Naqudah on Venus too.

**Comment by Drobac** [comment]
Asteroid only has y 60+

**Comment by Dream-Master** [comment]
Only a few Asteroids goes down to level 40 or 35. Thats because Naqudah is so rare on the asteroids.  Maybe add small naqudah to the Tier 3 planets and moons.

**Comment by Drobac** [comment]
Well untill tier IV you can only use naquadah for wires anyway.Cant make the reactors without osmium

**Comment by Namikon** [comment]
Osmium is even higher tiered than Iridium, is this tiering of Naquadah generators ok? I mean, when you reach Osmium, you are almost at fusion level right?

For the low naquadah, there would be 2 options. 1: Create a new mix just for asteroids that spawns around the average height of the asteroids or 2: Change the generator to generate asteroids everywhere from 10 to 210

**Comment by Drobac** [comment]
maybe small ores of osmium on tier III planets?

**Comment by Dream-Master** [comment]
Osmium is on Tier 5 so Tier planets have samll ores. I will add it and reload dimensions. I hope later the Tier 4 Rockets recipes are ready.

**Comment by Namikon** [comment]
We shall not break the tiering. Osmium can be centrifuged from iridium, and osmium itself as small ore shall only spawn on planets one tier before veins (SmallOresTier = VeinOreTier - 1)

**Comment by Dream-Master** [comment]
I add small Naquda ores on Ceres, Io, Venus, Enceladus, Proteus and Pluto

**Comment by Dream-Master** [comment]
Ok now ?

**Comment by Drobac** [comment]
think those should be ok. Does Venus have the veins?

**Comment by Dream-Master** [comment]
Witch veins Naquadah?

**Comment by Drobac** [comment]
yes naquadah, you said youll add it to tier IV

**Comment by Dream-Master** [comment]
Tier 3 (Asteroids) Tier 4 (Venus).
