### ISSUE TITLE
Wrong Better Builder's wand recipes

### ISSUE THREAD

**Issue by ForTheHorde01** [GTNewHorizons/NewHorizons#1772]
#### Which modpack version are you using?
1.4.1.1
#### If in multiplayer; On which server does this happen? 
Official GTNH Delta
#### What did you try to do, and what did you expect to happen?
Can't do nothing actually.. Report it was the best choice
#### What do you suggest instead/what changes do you propose?
I guess fix it if it's wrong?
So basically NEI says it needs 2x16 blocks unbreakable wand to make 1 32 blocks, 2x 32 to make 1 64 blocks, ETC ETC untill u get 16384. So i've placed one wand in assembling machine then it just start making it to another "tier" Dont know if that's known as a bug or not. But still if nei says one and machine does other thing. There must be something wrong :)

**Comment by Drobac** [comment]
Fixed in 1.5
