### ISSUE TITLE
Information about what planets need what protection

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1773]
When I went to ceres after going to the asteroid belt:
https://i.imgur.com/MtjiKgx.jpg

It would be great if there was a list of info/message before you take off about on what planets demand what protection, to avoid fun things like that in the future.

**Comment by noobyaran9** [comment]
What does it do?
Do u have thermal suit T2?

**Comment by Dream-Master** [comment]
Quests can help maybe

**Comment by Dream-Master** [comment]
Will add some.

**Comment by Dream-Master** [comment]
Quest are added already
