### ISSUE TITLE
lack of bismuth ore

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1774]
#### Which modpack version are you using?
1.4.1.1
#### If in multiplayer; On which server does this happen? 
I'm playing on delta
#### What did you try to do, and what did you expect to happen?
I tried to craft redsteel but i have a lack of bismuth and it appears that bismuth spawn only in small ore. Searching for small ores is much painful than searching for rare ore veins.
#### What do you suggest instead/what changes do you propose?
I suggest to add an ore mix of bismuth post moon or something like that because redsteel is needed in the craft of the large empty sunarium battery (LuV voltage) and the field generator (tier I)

**Comment by Dream-Master** [comment]
Sure i could add a bismuth mix. Will look at it.

**Comment by Dream-Master** [comment]
@boubou19 any suggestion in which mix i could add bismuth?

**Comment by boubou19** [comment]
On wikipedia the bismuth ore seems to be found with arsenic and antimony so maybe you could add bismuth in tetrahedrite ore veins or create a new mix with arsenic and antimony.

**Comment by Dream-Master** [comment]
ok will look at it
