### ISSUE TITLE
[Suggestion] Keep Wooden Form [Brick] in crafting grid

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1775]
#### Which modpack version are you using?
1.5.0.7

Working on my second BBF, and it is tedious with having to move the wooden form back onto the crafting grid every time I need to make bricks. Could we have it stay in the grid? Thanks.

**Comment by Dream-Master** [comment]
Yea we working on a fix.

**Comment by richardhendricks** [comment]
Thanks!

**Comment by Dream-Master** [comment]
YamCore addition @Namikon

**Comment by Dream-Master** [comment]
I need to test the stuff OneEyeMaker send me.
