### ISSUE TITLE
[Suggestion] Add Pam's Harvestcraft Maple trees as rewards

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1777]
#### Which modpack version are you using?
1.5.0.7

#### What did you try to do, and what did you expect to happen?
Able to find BoP and Natura maple trees, but no Pam's. 

#### What do you suggest instead/what changes do you propose?
Add recipe to convert between maple trees, or add Pam's variety as a quest reward, since maple syrup is used in pretty high tier foods.

**Comment by richardhendricks** [comment]
http://www.gtnewhorizons.com/forum/m/36844562/viewthread/29800621-pams-harvestcraft-maple-trees/post/128566811#p128566811

They could also be added to the loot bags, seems like I have gotten the "bunch o saplings" reward a couple of times already.

**Comment by Dream-Master** [comment]
A maple tree quest exists allready in 1.5.0.7

**Comment by richardhendricks** [comment]
Ah great, I see it in the Coins section as a trade for Forest Ranger coins.  Thanks!
