### ISSUE TITLE
Sugar piles

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1778]
**Which modpack version are you using?** 1.5.0.7

**What did you try to do, and what did you expect to happen?** Accidentally turned some sugar into tiny piles, tried to recombine them into normal sugar in a crafting table like every other tiny pile of anything ever.

**What happened instead?** Nothing, apparently it can only be done with a packager.
![sugar](https://user-images.githubusercontent.com/26042867/28900531-de7d4eb2-77bf-11e7-8327-e2771522efe2.jpg)

**What do you suggest instead/what changes do you propose?** Make tiny piles (and small piles) revert back into normal sugar in crafting table.

**Comment by Dream-Master** [comment]
Not sure why this not worked. Will fix it.
