### ISSUE TITLE
Steel Plate changed in 1.5.0.7

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1779]
I updated my server from 1.5.0.4 to 1.5.0.7 today and it appears that RailCraft steel plates got replaced with GregTech steel plates. This is causing AE2 to not recognize any recipes that used the old steel plates, which is dozens if not hundreds by the EV tier :(

**Comment by Bryfer** [comment]
This is intended. Or not the AE part please read #1102 for explanation
Sadly I believe you need to redo these recipes now 
But it's for a greater cause :)

**Comment by Dream-Master** [comment]
@Fapiko if you dont like the change revert it in the config.

**Comment by noobyaran9** [comment]
You need to pull all the recipe out and re do them with substitution mode on.

**Comment by Fapiko** [comment]
After reading that ticket it seems like this was simply to change the type of plate displayed in the GUI and not any functionality. If this is intentional I guess it's fine and can be closed, but it seems like an awful burden to put on players who have a lot of hours logged just to change the display of what the plates look like.
