### ISSUE TITLE
Make a Mod thats block ores in Dimensions

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#178]
Make a Mod thats block ores in Dimensions

**Comment by Dream-Master** [comment]
Bop we can disable ore now. Only the Ores from Tainted Magic mod cant be hidden and emeralds(on the overworld)

**Comment by Namikon** [comment]
It this still a required thing?

**Comment by Dream-Master** [comment]
No not realy any more.
