### ISSUE TITLE
[Quest Suggestion] Warn player tanks are not portable with pickaxes, add/move dolly quest to after iron tanks

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1781]
Please add a note to the "Where I can put all the liquids?" quest that these tanks are not portable. Filled one up with 16 lava and lost it all and kinda bummed about it. Was hoping to use it to store extra TiCon lava or water for my Pam's crafting. :(

**Comment by richardhendricks** [comment]
The ULV and other Gregtech tank does have a tooltip that says "Not a portable tank".  So are TiCon smeltery tanks the only portable tanks?

I did manage to route 60+ blocks of wooden pipe to the iron tank, so it is tied to my wooden tank that provides water to my base.  No more having to run across the base to make fresh water at least. :)

**Comment by Ethryan** [comment]
You can use the dolly on buildcraft tanks for portable tanks.

**Comment by richardhendricks** [comment]
Thanks for the tip, forgot about JABBA's dollies.  Maybe add a quest to create a dolly after the tanks then?

**Comment by richardhendricks** [comment]
although carrying a dolly all the way from y=6 to my base will be excruciating. :O

**Comment by Dream-Master** [comment]
There is a Dolly Quest but i am not sure in which cahpter.

**Comment by richardhendricks** [comment]
Dolly quest is in Steam tier, but gated behind Wire Wrap quest.  Recommend adjusting quest to behind tanks instead?  Is there a way to make a quest open in quest 1 OR quest 2 is completed?

**Comment by Dream-Master** [comment]
Are you sure all recipe parts can made at this point.  @richardhendricks

**Comment by richardhendricks** [comment]
Basic dolly requires rubber rounds, iron rods, 1 steel plate, and iron minecart wheels. Tanks quests are only available after getting 8 steel ingots.  Players can get rubber from the Alloy Smelter, but will need sulfur.  Sulfur is an ore in the Nether, however it is possible to get Sulfur dust via the XP drain and buckets. 2 buckets per 1 sulfur which converts into 2 rubber. (XP buckets also give obsidian dust, sticky resin, and silver dust FYI)

I think letting the quest open up when the first tank is completed is fine. I would be OK with replacing the iron tank quest with the dolly quest, if you want to keep the number of quests down down.

**Comment by Dream-Master** [comment]
Will look later into it

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28985223-cec3ab3a-7961-11e7-86a2-a20cb27b9004.png)

**Comment by Dream-Master** [comment]
Moved Quest to Tanks

**Comment by richardhendricks** [comment]
Thanks, change is perfect!
