### ISSUE TITLE
Mulch recipe

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1782]
**Which modpack version are you using?** 1.5.0.7

 Trying various recipes for Mulch, with water cells or buckets. The recipe will consume a cell but not a bucket.

![mulch](https://user-images.githubusercontent.com/26042867/28918855-0a02f1be-7819-11e7-860e-8d33479f4096.jpg)

Please give the empty cell back as it's much easier to do with a stackable item.  Or make a mixer recipe.

**Comment by Dream-Master** [comment]
Will add a mixer recipe.

**Comment by Dream-Master** [comment]
I checked now recipe and i dont like much the recipe. Mulch can me made over time in the moister. Not sure if water and bark is a good recipe.

**Comment by Dream-Master** [comment]
i remove the shaped recipe and add a mixer one.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28994655-0cf7e7fa-79d4-11e7-9e93-8cdbad17a952.png)
