### ISSUE TITLE
Rollback problem on epsilon

### ISSUE THREAD

**Issue by XxANTI-MATTERxX** [GTNewHorizons/NewHorizons#1784]
Ive been noticing recently that there have been problems with a section of chunks in my base, which seem to frequently "rollback", causing me to lose items. ive lost about a stack of nichrome ingots, 30 item chips (TI) and other items. this is the 4th time its happened, and Idk why. I HAD a TF clock tree near said chunks, but the core of said tree was removed by Drobac.

**Comment by Bryfer** [comment]
Similar to #1094

**Comment by Namikon** [comment]
Are those chunks anchor-loaded? If not, make sure they are. There seems to be an issue with chunk loading/unloading

**Comment by Dream-Master** [comment]
More than one year old. Reopen if necessary.
