### ISSUE TITLE
Advanced Coke Oven

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1786]
#### Which modpack version are you using?
1.5.0.7
#### What did you try to do, and what did you expect to happen?
Only vanilla logs are burning to charcoal
And somehow you can smelt steel in it
![2017-08-05_01 45 06](https://user-images.githubusercontent.com/27621272/28990700-323be024-7980-11e7-8a91-5bdaa2a06f93.png)

#### What do you suggest instead/what changes do you propose?
adding all wood types?

**Comment by Dream-Master** [comment]
Ok will Check it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/28994683-7ab21fa4-79d4-11e7-8041-2cf02cbb04f1.png)
Thaumcraft wood np
![image](https://user-images.githubusercontent.com/2970688/28994685-98cf795a-79d4-11e7-82d6-40c2414d8e93.png)
witchery wood np
Tf np
bop np
Forestry np
extra trees
natura....

**Comment by Dream-Master** [comment]
Magnetic iron i remove

**Comment by Radst0ne** [comment]
the rainforest oak from gt+

**Comment by Dream-Master** [comment]
ok will add that too but idk if this ever generated.

**Comment by Radst0ne** [comment]
you can craft it, found that recipe accidentally in my survival world, its a good farming tree

**Comment by draknyte1** [comment]
They don't spawn in world, no.
But they are decent size trees.
