### ISSUE TITLE
Alloy Blast Smelter produces free pulsating iron [1.5.0.7]

### ISSUE THREAD

**Issue by AmishInvader** [GTNewHorizons/NewHorizons#1787]
Put anything in the first input slot, programmed circuit (config 1) in second slot.  Alloy blast smelter will continue producing molten pulsating iron as long as it has energy.

**Comment by OneEyeMaker** [comment]
Can confirm. Also Alloy Blast Smelter doesn't use item in input slot (can't guarantee 10/10, but after attempting to melt dust of Pulsating Iron, it geives infinite amounts of molten metal and doesn't consume dust).

**Comment by Dream-Master** [comment]
@draknyte1 any idea?

**Comment by Dream-Master** [comment]
@AmishInvader @OneEyeMaker does the problem exist with GTNH 1.5.1.0?

**Comment by Dream-Master** [comment]
schould be fixed here

https://github.com/draknyte1/GTplusplus/commit/6a5dea35006704144b89d6abce2a336cb2c547d6
