### ISSUE TITLE
Mod suggestion "Advanced spawn control"

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1788]
A new Mod was suggested by the Admin Goshen from Prospercraft

https://minecraft.curseforge.com/projects/advanced-spawn-control

Did we need this in the pack?

**Comment by mtesseracttech** [comment]
Not sure if we do, I think most tweaks can be done with SpecialMobs and InfernalMobs

**Comment by bigbass1997** [comment]
Unless someone has a specific example where this would actually be used, I don't see why we should add a mod without some sort of plan or idea for what it would be used to do exactly.

**Comment by Namikon** [comment]
Would have to verify how that mod "controls" the spawn behavior. I tried something similar a long time ago, with various plugins/mods/own code, but lots of mods have their own spawn-"mechanics". Especially GalactiCraft/GalaxySpace seem to "ignore" or override the default behavior and ignore event-results.
That issue we had with the Magnum-Torch on planets not stopping entities from spawn is just one example

**Comment by Dream-Master** [comment]
No more mods for 1.7.10
