### ISSUE TITLE
[Suggestion] Cardboard books

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1789]
Can we have a book recipe that is not dependent on leather? There is (thick) cardboard in Gregtech which is almost not used right now.

**Comment by Dream-Master** [comment]
sure will add some.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29164569-2808f530-7dc0-11e7-98f9-dbfb268d1d5a.png)
