### ISSUE TITLE
Non stackable items autocrafting

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1790]
#### Which modpack version are you using?
1.5.0.7

transfer node and the auto workbench (bc factory) cant handle with non stackable items.
The auto workbench doesnt create a ghost item and the transfer node simply doesnt do anything
Maybe there is a fix for it

**Comment by Dream-Master** [comment]
Please repport it here @Radst0ne 
https://github.com/BuildCraft/BuildCraft/issues

**Comment by Radst0ne** [comment]
@dream-master okay it will be never fixed, did a quick research and due to massive code changes that was done to the crafting table it is not possible using non stackable items

**Comment by Radst0ne** [comment]
Well I think this can be closed, since this behavior is intended

**Comment by cubic-chariot** [comment]
Five years later (GTNH 2.1.2.0), BC Factory's Auto Workbench still cannot handle nonstackable items. Is there any interest in fixing this?
