### ISSUE TITLE
Server issues with energistics connector

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1791]
As discussed in discord. I spoke to the Steve's Addons dev, he recommends disabling it. He said he spent 3 weeks trying to fix it without success and decided to stop working on the mod. Since the whole mod has only 4 blocks and this one is the only one I ever heard people using, it might be a good time to remove Steve's Addons altogether.

**Comment by Dream-Master** [comment]
@Toperoco are you sure the other devices are useless when we remove the mod fully ?

**Comment by Toperoco** [comment]
There are a total of four blocks in that mod and this one is the only one people use on my server at least. I can't speak for the other servers of course, maybe others have different opinions.
