### ISSUE TITLE
1.5.1.0 Extra Cells

### ISSUE THREAD

**Issue by payalnicheg** [GTNewHorizons/NewHorizons#1792]
1.5.1.0

Single player
 After 1.5.1.0 update - not working all blocks of the mod Extra Cells
Fluid Interfaces and panels. Not open GUI, and interfaces cant receive  fluids

**Comment by Dream-Master** [comment]
Ok i hear it the first time. I dont change anything with AE2, extra cell.

**Comment by Dream-Master** [comment]
@payalnicheg any news here?

**Comment by payalnicheg** [comment]
Sorry for that. This problem happens if you go into the game under a different account. Security, will block all ME Network
