### ISSUE TITLE
Rocket Engines are too Expensive (GT++)

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1793]
Which modpack version are you using?
1.5.1.0

#### What do you suggest instead/what changes do you propose?
The Basic Rocket Engine (EV) requires IV+ circuits
and the Advanced Rocket Engine (IV) requires LuV+ circuits
Considering these are power gens and they are progressively less efficient, I think it would be fair to not have them be this unreachable.

**Comment by Dream-Master** [comment]
@mtesseracttech its a GT++ recipe so better report it to @draknyte1

**Comment by Dream-Master** [comment]
@mtesseracttech its a GT++ recipe so better ask @draknyte1

**Comment by Dream-Master** [comment]
Yes but true this is to expensive we need to change it to a lower tier circuit.

**Comment by draknyte1** [comment]
It's intended.
