### ISSUE TITLE
MV Circuit quests still use old recipes

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1794]
I noticed that in 1.5.10, the quests that guide you to the advanced circuits in MV (Integrated Circuit, Good Integrated Circuit, and Advanced Circuits) all use the old recipes for the retrieval tasks. For instance, the basic Integrated Circuit quest asks for 64 fine copper wire and 32 tin rods, while the actual circuit crafting needs 32 tin bolts and only 32 fine copper wire.
These 3 quests need updated to reflect the new circuit recipes.

**Comment by Dream-Master** [comment]
Ok yes I need to change it.
