### ISSUE TITLE
Gtnh quest - storage drawers

### ISSUE THREAD

**Issue by Alexusexcel** [GTNewHorizons/NewHorizons#1795]
Quest - storage drawers creating: 4 drawers, + 4 2x, +4 4x .
Suggestion: use ore dict ( originaly - only oak drawers assept)

**Comment by Ethryan** [comment]
Please search for similar (https://github.com/GTNewHorizons/NewHorizons/issues/1687) issues before creating a new one.

**Comment by Dream-Master** [comment]
So far I know is ordict not possible because every drawer have a different ordict. Need to create new ordict but I think not necessary. Quest is a side quest.
