### ISSUE TITLE
A lead about lead that leads to lead dust

### ISSUE THREAD

**Issue by OperativeLoop** [GTNewHorizons/NewHorizons#1796]
#### Which modpack version are you using?
1.5.1.0
#### If in multiplayer; On which server does this happen? 
Private Server
#### What did you try to do, and what did you expect to happen?
I've been working towards making my first batteries following the quests. However you need lead dust as one of the steps, but the quest "A lead about lead that leads to lead dust" only unlocks after you've been to the Twilight Forest and found a Galena vein.
#### What do you suggest instead/what changes do you propose?
Remove the requirement on finding the Galena vein, the quest text tells you that you need to go to the Twilight Forest for it, so if that prerequisite is not there, it's more informative to the player that they need to go there for it. Right now, by the time you unlock that quest and see that text, you've  already been there so its not as helpful, I had to go into the quest files to see why there were no more quests leading towards batteries to figure it out.

**Comment by Dream-Master** [comment]
Ok i can add a info

**Comment by OperativeLoop** [comment]
The info is already in the Lead dust quest, you just don't get to see it until you already found a a vein.

**Comment by Dream-Master** [comment]
@OperativeLoop any suggestion in which Quest i should mentioned it ?

**Comment by OperativeLoop** [comment]
I think you should just remove quest 610 from the preRequisites in "questID": 608 

The quest I mentioned in the title already has the mention. If you remove the prereq then that quest shows up after getting the Antimony quest done.
