### ISSUE TITLE
Output hatch in EBF still dupes fluid

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1797]
In 1.5.10, with the new EBF recipes that output fluid in the output hatch (cobaltite processing, for example), trying to manually remove the fluid by putting cells in the hatch will dupe the fluid infinitely. Placing a tank on top of the hatch to extract it manually works fine, though.

**Comment by JohannesGaessler** [comment]
Is the Fluid by chance Sulfur Dioxide?
I noticed recently that adding GT++ causes the Fluid Canning recipe for the Sulfur Dioxide Cell to break.

**Comment by Dream-Master** [comment]
@Bluebine

**Comment by Bluebine** [comment]
Yes, it is sulfur dioxide and I noticed too that the cells were impossible to empty once I filled them. I couldn't put them in chests or use a fluid canner, had to delete them and cheat in new empty cells.

**Comment by Dream-Master** [comment]
I rename the fluid and we need to test it in the new version 1.5.1.1
