### ISSUE TITLE
1.5.1.0 Problem with GT pump

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1800]
GT pump just stops pumping oil for no reason. Sometimes it just drills through the oil under it and stops working, sometimes it's just draining power and not pumping anything at all. I'm not sure what the exact cause of the problem is, but it happens pretty much every time I use it. It works great in the begining, but then it just stops outputting oil and the only soultion to get it working again is to move it and rebuild it completely. Getting the pipes back out of the oil is pretty hard. Some people say it happens when the chunk gets reloaded, but I wasn't able to confirm that.

I'm sure a lot of people experienced this issue, because it's several years old now. It would be nice to get this fixed or at least enable for example BC pump that is not that buggy.

**Comment by Dream-Master** [comment]
No I won't add bc pump. Maybe gt pumps need a fix.

**Comment by boubou19** [comment]
It's also happening to me on delta: sometimes it pumps some oil but nothing is exported during a certain amount of time and then it outputs the oil, as if the pump has an internal buffer to fill before outputing oil.

**Comment by Dream-Master** [comment]
@Lainiel can you try to pump oil and hitting from time to time with the scanner on it pump to see if a internal buffer is fill like @boubou19 said and report what happend. Thanks

**Comment by Lainiel** [comment]
It's slowling draining power, not pumping anything and the only output you get is this:

https://puu.sh/x4GGS/70bb10a044.png

And the only thing that is changing there is that it uses energy from internal buffer and that gets refilled by getting power from the cable. Nothing about pumping oil or storing it in some buffer. All it does is it just sits here and uses power without doing anything.

**Comment by Lainiel** [comment]
So a small update:
I got the pump working again by moving it 2 blocks down. It drained power for about 2 minutes and then started pumping again. I haven't replaced the mining pipe that was layed by it. When it was in the original place it just drained power for more than an hour and didn't pump anything.

**Comment by Dream-Master** [comment]
@Technus did we fix something's in the pump code?

**Comment by mitchej123** [comment]
Should be fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/54

**Comment by Dream-Master** [comment]
ok
