### ISSUE TITLE
[Worldgen] Ground and tropical gardens

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1802]
#### Which modpack version are you using?
1.5.1.0

Worldgen for Pam's Harvestcraft ground and tropical gardens needs to be updated.  Searched 7k+ blocks, only located 1 of each, both within 5 meters of each other, in a Meadow; only one of each in the whole meadow. (seed is -2966244692964020438 if it matters).

Suggest adding ground gardens to Snowy Coniferous Forest, Temperate Forest, River Icy, and Tundra biomes.

Suggest adding Tropical gardens to River Hot and any other tropical/warm biomes (For some reason I don't get very many in my seed).

**Comment by Dream-Master** [comment]
How do I add it. 1.7.10 from pams is not on git and not open source.

**Comment by richardhendricks** [comment]
Yeah, that's a real bummer. Could we change the Pam's Seeds quest in Coins Coins Coins to be more expensive, but let us select a specific garden?  Been trying for a while now to get onion or cinnamon seeds.

**Comment by Dream-Master** [comment]
Sure i can add Quests you can buy Seeds/Gardens for Coins.

**Comment by Dream-Master** [comment]
after 10 seed bags i got all 12 gardens
