### ISSUE TITLE
[Quest] Add crafting tasks for Electromagnetic Polarizer to Basic Crafting: Motors

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1803]
#### Which modpack version are you using?
1.5.1.0
"Basic crafting: Motors" quest requires magnetic iron rods, but doesn't provide tasks to build the electromagnetic polarizer. Should the quest be gated to after power generation is available?

**Comment by Dream-Master** [comment]
You can polarize iron rods just with Redstone. That why I choose this machine quest should be optional.

**Comment by richardhendricks** [comment]
Ah OK, I didn't see it when I was hunting through NEI.  Thanks.

**Comment by OperativeLoop** [comment]
There is already a quest for the Basic Polarizer, its called "Saving redstone"

**Comment by richardhendricks** [comment]
Thanks, I haven't advanced that far. In this case, request adding a step to the Basic Crafting: Motors,  Retrieval: iron rods and redstone.  This will guide a new player to using the redstone and rods to make the magnetic iron rods.

**Comment by Dream-Master** [comment]
sure.
