### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1805]
Bin mir nicht sicher ob mein pc spackt, aber irgendwie zeigt das mir einfachere rezepte an, was ich mir eingentlich nicht vorstellen kann, es sollte doch nie einfacher werden

**Comment by Dream-Master** [comment]
@alphaNOVAircraft pm auf Discord bitte was du meinst.

**Comment by Dream-Master** [comment]
Ok ich mach das jetzt zu da ich nix von dir gehört habe.
