### ISSUE TITLE
space race quest scemetivc

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1806]
In der quest wo man die schemetic fuer die rakete bauen muss benötiigt man ja eine worjkstation, was ja auch richtig ist, aber in der beschreibeung steht noch von vor dem circuit update das man ein data controll circuit benötigt, was ja nicht mehr der fall ist.

**Comment by Dream-Master** [comment]
Ok will rewrite this quest.
