### ISSUE TITLE
Material equivalency: Pig Iron

### ISSUE THREAD

**Issue by PaladinOne** [GTNewHorizons/NewHorizons#181]
Tinker's Construct and GregTech both have Pig Iron as a material, and both forms are OreDict-registered as ingotPigIron. However, the two materials are completely different. GregTech Pig Iron is a non-standard form of conventional Iron. Tinker's Construct Pig Iron is an alloy of 1 Iron Ingot (144mB molten Iron), 1 Emerald (640mB liquified Emerald), and 1 Pig (almost literally) (80mB Blood).

I'm not sure how much of an issue this is, as I don't know whether or not GregTech Pig Iron can actually be obtained through other means, but it feels entirely weird seeing GregTech Pig Iron appear when TiC Pig Iron is supposed to. (Also, it may or may not work for Tinker's Construct recipes, I don't know how OreDict-friendly that is.)

**Comment by Dream-Master** [comment]
I thought befor Gt only add Pig Iron because of tinkers but i will check it.

**Comment by PaladinOne** [comment]
Pig Iron is a perfectly ordinary material. IRL (and what GregTech works off of) Pig Iron is the term for fairly raw, impure iron, not heavily processed or purified yet. (And, in particular, *not* an alloy.)

**Comment by Dream-Master** [comment]
So what do you think i can change? Changing only recipes would not be a problem.

**Comment by Dream-Master** [comment]
You get Pig Iron only with Tinkers. I see no way to get it via Gregtech. We dont have Pig Iron Ore Veins.
