### ISSUE TITLE
Assembly line recipes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1810]
#### Which modpack version are you using?
1.5.10
All the recipe in the Assembly line uses a specific circuit and not oredicted like all the normal crafting recipe. Is it possible to oredict them?
I'd want this as it would conform to the new recipe crafting and wouldn't make some of the recipe require over 100k materials although you are at UV tier

**Comment by Dream-Master** [comment]
So far ik its not possible that why i set it to special circuit.

**Comment by Drobac** [comment]
and there is no way to have multiple recipe be made from a single scan?

**Comment by Dream-Master** [comment]
Idk well enough how the airline work. @Technus any idea here?

**Comment by Dream-Master** [comment]
Maybe we can add some dummy circuit like the programmed circuit in lv
