### ISSUE TITLE
Upgrade Higher tier batteries

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1811]
The custom LuV+ Batteries in the pack are almost useless (Sunnarium/Naquadah batteries). Just for comparison. 
**LuV** Lapotronic Energy Orb Cluster 1,000,000,000 EU - Large Sunnarium Battery 102,400,000
**ZPM** Zero point module 2,000,000,000,000 - Medium naquadah battery 409,600,00
**UV** Ultimate battery basically infinite storage - Large naquadah battery 1.634,400,00

Not to mention that the ZPM isn't even craftable, can only be acquired via quest and isn't rechargable. The custom ZPM/UV batteries have such low charge they are basically useless.
I'd recommend exponential energy storage increase in the batteries of those tiers (not enough to reach the "proper" batteries) and to have a craftable and chargeable Zero point modules

**Comment by Namikon** [comment]
Please, no chargeable ZPM.
The ZPM should remain an incredibly powerful device that will make people scream of joy if obtained.
But I do agree that the Batteries are not as good as they should be. 

My suggestion to adjust the Battery capacity:
Large Sunnarium: x10; New Value 1,024 GEU (Slightly more than the equivalent Lapotronic Cluster)
Medium Naquadah: x200; New Value 81 GEU (You'd need 25 of those to get the same capacity as one ZPM, but that is still reasonable IMO)
Large Naquadah: x1000; New Value: 1,63 TEU

Unchanged:
ZPM - 2 TEU
Lapotronic Cluster: 1 GEU

For clarification:
G = Giga = 10<sup>9</sup>
T = Tera = 10<sup>12</sup>

**Comment by Dream-Master** [comment]
Should I changes this values later or will you change it?

**Comment by Namikon** [comment]
This is a [Suggestion](https://www.merriam-webster.com/dictionary/suggestion) and as such meant to start a discussion

**Comment by Dream-Master** [comment]
I know I am always to fast.

**Comment by Ethryan** [comment]
I think the difference between the ZPM and Large Naquadah in that case is to close to each other.
If you modify the Large Naquadah to 1,63 TEU, perhaps increasing the ZPM storage a bit higher to 6 TEU so that you don't just need 3 Large Naquadah to equal 2 ZPM's. 

Just my opinion.

**Comment by compwiz91** [comment]
Rather than rechargeable why not make it craftable,  all be it extremely expensive.

**Comment by Dream-Master** [comment]
Maybe a repeatable Quest after you get your first ZPM is possible. So in exchange of some special items you can get one zpm every week or every 2 week (realtime)

**Comment by Namikon** [comment]
Making the ZPM Quest repeatable is not solving the initial issue; As it is about batteries for that Tier, not the ZPM itself. 

But rather than making the ZPM craft/chargeable (which will make every true StarGate fan feel lots of pain; At least the chargeable), my suggestion was to actually adjust the batteries to fit their tier properly and keep the ZPM as the special "omg" device that it is right now. (Remember it is one of the few legendary quest lines as well)

The initial values that are set since the introduction of those didn't take the ZPM+ machine tiers into account; Those were added later. So the first step, in my opinion, should be to adjust the values to be actually worth the materials to craft.

**Comment by Drobac** [comment]
Microverse battery sounds nice, although guess it wont charge itself :)

**Comment by Namikon** [comment]
That's the point; The Microverse Battery is infinite :P

**Comment by Dream-Master** [comment]
There are new Batteries in main gt code so need to check it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31197931-fadd2680-a952-11e7-8c68-21a29f80ba1c.png)
![image](https://user-images.githubusercontent.com/2970688/31197944-057ddb52-a953-11e7-9617-784ec840aadf.png)

**Comment by MineAnPlay** [comment]
Dream that's scanner recipes... (Pick up either those items or a Debug Scanner to see Assembling Line recipes)

**Comment by Dream-Master** [comment]
yea will show the recipes in a bit need a restart.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31200165-1d04ece6-a95a-11e7-8068-4b6fef7ce429.png)
![image](https://user-images.githubusercontent.com/2970688/31200169-223c5244-a95a-11e7-84a9-5c1ff107753b.png)
**
