### ISSUE TITLE
Infinite Enderpearls

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1813]
#### Which modpack version are you using?
1.5.1.0

Using the tinkers smeltery you can smelt ender pearls and create a block of solid ender out of 4 enderpearls or 1000mb liquid ender. Macerating the block gives 9 Dust so you gain 4 Enderpearls

#### What do you suggest instead/what changes do you propose?
Changing the amount of mb, or reduce the recipe to 4 dust

**Comment by Dream-Master** [comment]
Sure will change it.

**Comment by Dream-Master** [comment]
Ender Block changed to 2250 mb molten Ender.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29148297-c0403984-7d6c-11e7-8207-3c634dd9a279.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29148406-65615d62-7d6d-11e7-935c-2e5fe519b9cb.png)
