### ISSUE TITLE
Staff of Traveling 

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1814]
Why isn't there a recepie for the staff of Traveling from enderio?

**Comment by Drobac** [comment]
The staff is craftable, which version are you using?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29147750-4c570f96-7d69-11e7-8905-c371bfcb1869.png)

**Comment by Dream-Master** [comment]
Click on the empty staff and load it. @PapaTim68
