### ISSUE TITLE
1.5.1.0 Ore washer and thermal centrifuge in LV quests

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1815]
Theese 2 machines should not be main quests in LV and here's why:

#### Thermal Centrifuge
Thermal centrifuge has no use at all in LV age and it eats a lot of power. It is needed only when you want the thrid byproduct and you can't get that one without HV macerator anyway. You can get the first ore byproduct by washing the ore with the ore washer and the second by centrifuging the washed ore in a normal centrifuge. The third byproduct you can only get when you have Universal Macerator which is in HV age and you can pulverize the centrifuged ore from thermal centrifuge to get a 10% change to get a large dust of the third byproduct.

#### Ore Washer
Ore washer has a small use in LV, but I still think it shouldn't be a main quest. Ore washer is only needed when you want BOTH byproducts from every ore. If you want the first byproduct, you'll just hammer the macerated ore and then centrifuge it using a normal centrifuge to get it. If you want the second byproduct you can wash the macerated ore using a cauldron and then hammer it and centrifuge it in normal centrifuge to get the second byproduct. The ore washer is really only needed when you want both of them from a single ore, which almost never happens. You pretty much always want just one and you don't care about the other in LV age. You don't even have enough water to run the ore washer in LV age if you're using just the water tank to get your water. That stops being a problem once you hit everfull urn.

When I was playing I just made these machines to complete the quests and since then, they were just sitting in my chests doing nothing, because I've had no use for them.

#### What do you suggest instead/what changes do you propose?
Don't make theese quests main quests in LV age. You can make a quest in LV age that explains how to get the first or a second byproduct from ore. Then in HV age you can make a quest that shows how to get all of the byproducts from ores at the same time using 2 HV macerators, ore washer and a thermal centrifuge.

P.S. Supplying enough water for the ore washer is still a problem for me in early HV age, because the everfull urn requires 2 titanum plates and the water tank can't keep up at all.

**Comment by Radst0ne** [comment]
Water isnt a problem you can craft a reservoir from enderio in early mv

**Comment by Lainiel** [comment]
Well I didn't know that. I've never used enederio. That just means that the everfull urn is unnecessarily expensive.

**Comment by Radst0ne** [comment]
You can have a greate use out of the ore washer early, e.g. you need rare byproductsy but I agree this Quest should be optional

**Comment by Dream-Master** [comment]
In 1.5 and abov it will become more important have 2. and 3. byproduct because you need it like arsenic or gallium. So i dont want to change the Quests. Centrifuge and Ore washer are a main quest and i think they are not worse to have it.

**Comment by Lainiel** [comment]
I'm playing 1.5 from scratch. As I said you can't get third byproduct with thermal centrifuge in LV. You need to be in HV to do that. Also you can get the second byproduct without using any of theese machines. They are only needed when you want all of the at the same time.

**Comment by Dream-Master** [comment]
Ok removed it from main quest.
