### ISSUE TITLE
Steel Plate in quest detect problem

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#1816]
#### Which modpack version are you using?
1.5.1.0

#### If in multiplayer; On which server does this happen? 
Private Server

#### What did you try to do, and what did you expect to happen?
To complete the quest. Quest is not completed.

#### What happend instead? (Attach screenshots if needed)
Steel plate is not detected.

#### What do you suggest instead/what changes do you propose?
To replace the requirements of the quest
![2017-08-09_22-17-56](https://user-images.githubusercontent.com/3153076/29140132-091e610a-7d52-11e7-88e2-7e783172987a.png)

**Comment by Bryfer** [comment]
Which quest? Quest id?
Hold the cursor over the quest and hold shift to see quest id

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29147783-82b2fd8e-7d69-11e7-8763-3cd29695e202.png)

**Comment by Dream-Master** [comment]
@code32 reload your Quests please this was fixed in 1.5.1.0.

/bq_admin default load
