### ISSUE TITLE
Forestry: Circuits

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1818]
#### Which modpack version are you using?
1.5.1.0

Most Forestry Recipes doesnt allow different circuits of the same tier, you have to craft the specific one, also there is a mistake in Quest 693 "Farm Logic enhanced" the Quest tells you to get a coated circuit board but a good circuit board is needed.

#### What do you suggest instead/what changes do you propose?
I have some Suggestion regarding the Forestry Multiblock Farm:
Make the soldering Iron a little bit cheaper since it gets used up very quickly
Maybe lower the tiers of the required circuit boards for the forestry circuit board (e.g. you need for the intricate circuit boards just two good integrated circuit but a more advanced circuit board), since biogas and Bio Diesel are now a thing

**Comment by Dream-Master** [comment]
O will rebalance recipes.

**Comment by Dream-Master** [comment]
Ok change Small Power unit using Steel item casing
