### ISSUE TITLE
NEW UPDATE NOW

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#182]
Update 2.7.0.4

@Drobac, @Namikon  I have to delete all Dimension exept the overworld.

If you have stuff there i will refund it in creative

**Comment by Drobac** [comment]
Asteroid spawn with ore now but only on the surface of the asteroids, none spawn on the inside

**Comment by Dream-Master** [comment]
@Drobac  Gt ores ? On Blood Asps Asteroids or on the Galactic ones ?

**Comment by Drobac** [comment]
Gt ores in the Asteroid Dimension - http://imgur.com/M8Mf2Nd . Also naquadah doesnt seem to spawn. And i havent been able to find pitchblend/uranium veins on any of the planets stated in the excel document

**Comment by Dream-Master** [comment]
Look on Dimos and Phobos  I found some in my test world (uran and plutonium) naqudah I have to check.

**Comment by Namikon** [comment]
With the GT ores, well, this might have to do with the way the asteroids where meant to be initially. The chances for an Ore block to generate in/at asteroids are:
- Primary Ore: 6%
- Secondary Ore: 12%
- "Between" Ore: 16%
- "Sporadic" Ore: 20%

The reason why the old asteroids had so much ores was probably caused by the double oregen we had

**Comment by Dream-Master** [comment]
I make a Mix on Venus.

**Comment by Drobac** [comment]
Still no naquadah in Asteroids

**Comment by Namikon** [comment]
Look at the forum. I found another bug in the asteroid generator code. Asteroids and end might have to be reset again

**Comment by Dream-Master** [comment]
Ok i add something to core mod (not the pipes we fail with this yesterday ) so want to make a update today.

**Comment by Namikon** [comment]
I won't be there before 20:00, make sure to check the end asteroids and consider changing the rarity value before you add 0.8.1 and reset the dimensions

**Comment by Dream-Master** [comment]
I have to check for all Ores the rarity ? If Yes maybe i need more time.

**Comment by Dream-Master** [comment]
Now i test it with 10 and 5.
