### ISSUE TITLE
[Thaumcraft] Wierd Staffs not usable for anything

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1821]
Also ich hab folgendes ich wollte mir Staffs machen.....
Also hab ich los gelegt und diese Staffs gemacht die 187 Kapacität haben und so gecraftet werden:
![silver staff](https://user-images.githubusercontent.com/29522870/29171088-8e4d640a-7ddb-11e7-8a27-4646cb2dfcba.jpg)

Also imprinzip nen Scepter mit Stave core sind..... Diese funktionieren für garnichts weder im crafting table noch mit Focus, jedoch diese Staffs 
![staff staff](https://user-images.githubusercontent.com/29522870/29171144-c9eef726-7ddb-11e7-889f-c489010b49ab.JPG)
welche billiger sind jedoch nur 125 haben funktionieren wie sie sollen nur mit focis. jetzt ist die frage sind die ersten staffs dafür vorgesehen das sie mit foci funktionieren oder nicht?

**Comment by Dream-Master** [comment]
http://lmgtfy.com/?q=Thaumcraft+Wands

**Comment by PapaTim68** [comment]
...... Weil das ja auch voll und ganz mine frage beantwortet.....

**Comment by Henny022** [comment]
selber schuld, wenn du ein für dich sinnloses item craftest

**Comment by PapaTim68** [comment]
................

**Comment by alphaNOVAircraft** [comment]
warum heißt es dann nciht magic buffer staff (Zitat Holsten 2017)
