### ISSUE TITLE
Missing recipe in NEI, glow flower --> glowstone

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1822]
The extractor recipe for 2x glow flower --> 1x glowstone is not showing up in NEI (version 1.4.1.1, singleplayer as well as DirtHuts multiplayer).

Was already referenced here: https://github.com/GTNewHorizons/NewHorizons/issues/788

and here: https://github.com/GTNewHorizons/NewHorizons/issues/799

It was labeled fixed, so something new must be messing with it

**Comment by Dream-Master** [comment]
Or it is fixed in 1.5xxx. I need to  check it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29191242-603b4810-7e1d-11e7-83e7-de0cdc0ca914.png)
1.5.1.0
