### ISSUE TITLE
Iron capped Greatwood Wand (quest #798) is impossible to finish

### ISSUE THREAD

**Issue by TheMathis26** [GTNewHorizons/NewHorizons#1823]
#### What happend instead? (Attach screenshots if needed) There is only one recipe for this wand and it uses the iron caps from Thaumcraft whereas the caps we had to craft for the quest were from the mod GT: New Horizons so we're not able to craft the wand.
What the quest requires:
![2017-08-10_20 29 26](https://user-images.githubusercontent.com/12830127/29185777-a49d0fce-7e0a-11e7-9afe-148385f7f26c.png)
What the craft of the wand requires:
![2017-08-10_20 29 09](https://user-images.githubusercontent.com/12830127/29185768-9c046380-7e0a-11e7-89a9-7a28424613e0.png)

**Comment by Dream-Master** [comment]
Sadly the recipe from thaumcraft I can't remove. That s why I add own wand caps. The recipe is shown in the Thaumcraft book and nei. Using wand caps aluminium screws naga scales and a forestry stick. Look for the uses of naga scale and you will find it. The quest book guide you too.

**Comment by Dream-Master** [comment]
@Bullwulf that what i mean :)

**Comment by TheMathis26** [comment]
I've found the recipe you're talking about but that's the recipe of an iron capped wooden wand but the quest asks for a greatwood wand. Moreover, this wand has a capacity of 25 and we need the greatwood wand, which has a capacity of 50 to be able to craft the gold capped wand, which requires more than 25 vis so I'm still stuck.

**Comment by Dream-Master** [comment]
Make a Greatwood wand with iron cappes adn then one with gold caps. I rewritting the quests in the newest version

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29291145-e5fe27d8-8142-11e7-9a41-93f7fbf44e54.png)
