### ISSUE TITLE
[Quest Suggestion] Provide pointers to Forestry Worktable at key points

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1824]
#### Which modpack version are you using?
1.5.1.0

Forestry worktable is super-useful, and can reduce tedium of many common jobs because you can click-drag across a row of buckets, and it will use tools in its own inventory to continue crafting. Specifically:
Making torches with creosote - just drag-click all your buckets into the worktable
Making fresh water for Pam's - Same as above
Making fresh milk for Pam's - Same as above
Making clay bricks - wooden form is automatically reused
Making concrete - not tested, but would probably make this easier too.

Suggest adding a quest in Tier 1 to make glue buckets after Steam Extractor, using rubber bars in smeltery.

Suggest adding a quest to Cooking Farming Fishing after D'oh! to make 64 fresh water and 64 fresh milk, with a hint "This is much easier to do using a Forestry worktable. Drag-click all your buckets into the worktable, and craft them all at once."

<s>Suggest adding a hint to 2x steel: "If you are tired of making the clay bricks 8 at a time, try using a Forestry worktable from Forestry and Farms". This way the form falling out of the crafting table doesn't need to be fixed.</s> fixed allready

**Comment by Dream-Master** [comment]
"Suggest adding a quest in Tier 1 to make glue buckets after Steam Extractor, using rubber bars in smeltery."

@richardhendricks Which recipes need Glue? i see only boocks.

**Comment by richardhendricks** [comment]
Just books I think

**Comment by Dream-Master** [comment]
you mean to make a quest to make books for the bookshelf and then crafting the forestry worktable ?

**Comment by richardhendricks** [comment]
Yes.  But now that I've explored more, I don't think the glue quest is necessary.  Books can be found easily enough in villages or the roguelike dungeons surface brick house.
