### ISSUE TITLE
[Quest]

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1825]
#### Which modpack version are you using?
1.5.1.0

Quest 4x steel does not require correct number of Firebricks.

To add 2 extra blast furnaces, assuming they are attached to the other two you made:

4x3 (wall) * 2 = 24
(4x3 - 3 (center stack)- 1 (controller) )*2 = 16
4x2 (controllers) = 8

Total Firebricks needed = 24 + 16 + 8 = 48

**Comment by Dream-Master** [comment]
I see your pic on discord and you build it in a row. Why not build it like a square you need less bricks.

**Comment by richardhendricks** [comment]
Because I am stupid. :)

**Comment by richardhendricks** [comment]
I get 40 total firebricks needed if placed in a square
8 for the two controllers, 14 for the interior wall (4 + 1 + 4 + 1 + 4), and 18 for the new face (5x4-2)

**Comment by Dream-Master** [comment]
@richardhendricks and what i wrotein the book?

**Comment by richardhendricks** [comment]
Questbook has 40 . Nevermind.
