### ISSUE TITLE
[Quests]

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1828]
#### Which modpack version are you using?
1.5.1.0

Current questline has Thermal Centrifuge available right off of Tier 2 unlock, but it requires 2 Amps of power. Normal Basic Centrifuge is behind electric pistons, basic ore washer, and basic fluid extractor.  Recommend swapping the basic and thermal centrifuge quests location in the quest book so that the basic centrifuge is available right after unlocking tier 2.

Basic Fluid Extractor should be gated on LV Fluid Pump as well.

**Comment by Dream-Master** [comment]
I try to rearraged the quests not sure if this rely helps. Basic Fluid Extratctor have a piston i n recipe and gated behind it.

**Comment by richardhendricks** [comment]
Thanks!

**Comment by Dream-Master** [comment]
@richardhendricks i will close it when version 1.5.1.1 is out.
