### ISSUE TITLE
(Suggestion) Make compressed coal blocks extractable

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#1829]
The compressed coal blocks (lignite, regular coal, charcoal, and coal coke) are a neat concept, but they're not very useful- all they can be used for is smelting tons of stuff in a furnace, and you can't even get back the coal you made them with.

All the other compressed blocks (cobblestone, dirt, etc.) can be turned back into 9 of what was used to craft them in an extractor, doing the same thing for compressed coal blocks would probably be a good idea.

**Comment by WarlordWossman** [comment]
+1 can't see why that would be a bad idea

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29289098-87d99504-813b-11e7-87db-d741d685bc58.png)
![image](https://user-images.githubusercontent.com/2970688/29289135-a2ca3c7e-813b-11e7-9631-4e4ff9068c10.png)
![image](https://user-images.githubusercontent.com/2970688/29289172-bc2cfa3a-813b-11e7-87a3-57dd820be250.png)

**Comment by Dream-Master** [comment]
Did we realy need extractor recipes also ?
@Bluebine @WarlordWossman

**Comment by Dream-Master** [comment]
I add Coke coal to forge hammer too

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29289533-14c3ce3e-813d-11e7-91ab-007fc008bf64.png)

**Comment by Bluebine** [comment]
Forge hammer recipes should be fine, but if you haven't already add in ways to get from compressed coal blocks down to regular coal blocks. Extractor recipes or forge hammer recipes are both fine, as long as there's some way to do it.

**Comment by Dream-Master** [comment]
ok nice
