### ISSUE TITLE
Basic Capacitor (EnderIo)

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1830]
#### Which modpack version are you using?
1.5.10

The material cost of the basic capacitor is a little bit to high, it took a me alot of digging to get Tantalum (mv age) and even after a hour of digging I got only 10 tantalum ingots.
My suggestion: changing the tantalum rod for two tantalum bolts and two manganese foil insted of one plate but upper the amount of polyethylene to 288mb?

**Comment by MineAnPlay** [comment]
I don't think this change is needed. You don't need to get a lot of it and this is a good way to gate it a little more so you can't get it quiet early on.

**Comment by noobyaran9** [comment]
Tantalum is really easy to obtain if u have a lava centrifuge going. And u can get infinite lava with the everburn urn.

**Comment by Radst0ne** [comment]
@mineanplay Well you need for every octadic capacitor 8 normal capacitors. So it isnt that cheap. 

@noobyaran9 didnt know that about the everburn urn, thanks!
