### ISSUE TITLE
1.5.1.0 Wither skull drop

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1833]
#### Which modpack version are you using?
1.5.1.0
#### If in multiplayer; On which server does this happen? 
Multiplayer private server
#### What did you try to do, and what did you expect to happen?
I've killed around 40 wither skeletons with a cleaver from tinkers construct and I didn't get a single wither skull in the process. Cleaver should have 20% chance to drop the skull, so I should have about 8 right now.

**Comment by Dream-Master** [comment]
You mean 1.5.1.0? @Lainiel

**Comment by Lainiel** [comment]
Yes my bad sorry

**Comment by Dream-Master** [comment]
In the newest version I change the config settings and disable Inguana Tweaks skulls . Normaly they should drop now. Can you test you Ingunan tweaks main cfg if this is set :
    B:removeMobHead=true

**Comment by Lainiel** [comment]
Yes it's set to true on the server. I always replace all the config files when updating to the new version.

**Comment by Dream-Master** [comment]
It is possible that special mobs is here the problem.

**Comment by Dream-Master** [comment]
I will ask in my Community if anyone elese have this issue.

**Comment by Anarack** [comment]
I have also experienced this, and they are also not droping necrotic bones.

**Comment by Dream-Master** [comment]
The bone is possible to make after a thaumcraft research

**Comment by Lainiel** [comment]
Yes the necrotic bone can be crafted, but it should still drop from the wither skeletons. The wither skull can't be crafted so you get stuck in progression, since you can't craft the avaritia crafting table.

**Comment by Dream-Master** [comment]
Not sure if you @Lainiel only have this problem. I ask another Guy and he said that he has a sword with 90% drop chance and get alot of Skulls.

**Comment by Dream-Master** [comment]
@Lainiel Look in help chat.

**Comment by Lainiel** [comment]
Here's how it looks:
https://www.youtube.com/watch?v=x7zHvS9C41s&feature=youtu.be

Update:
MineAndPlay suggested to set B:_allow_vanilla=true for skeletons in the Special Mobs config file. I've done that and they started dropping normally.

**Comment by mitchej123** [comment]
I had the same issue on my local server.  Changing the allow_vanilla did help as vanilla skeletons were spawning but I was curious what the underlying cause was.  I did some digging and it looks like this check here is the culprit:

https://github.com/GTNewHorizons/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/tools/TinkerToolEvents.java#L319

If make the following change then wither skeletons from SpecialMobs should drop skulls.

```
 if (event.entityLiving.getClass() == EntitySkeleton.class)
```

To this:
```
if (event.entityLiving instanceof EntitySkeleton)
```

**Comment by Dream-Master** [comment]
Ok will try it. Thanks.
