### ISSUE TITLE
easy obsidian blocks in nether

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1836]
#### Which modpack version are you using?
14.1.1
#### If in multiplayer; On which server does this happen? 
i play on Delta
#### What did you try to do, and what did you expect to happen?
I used a nitric acid bucket in the nether and i expected it to be empty without the liquid's source block like a water bucket.
#### What happend instead? (Attach screenshots if needed)
The nitric acid bucket have the same behavior as the water bucket but can be placed in the nether so it easy to get obsidian.
#### What do you suggest instead/what changes do you propose?
i suggest to either give the same behavior as the water bucket so it can't be placed in the nether or disable the obsidian creation instead.

**Comment by Dream-Master** [comment]
Why not using blood in the nether much more easy :)

**Comment by Dream-Master** [comment]
I think there is nothing i can do here. I cant disable all bucket placing. I guess people find eberyone a way and what is so bad in cheap obsidian? @boubou19

**Comment by WarlordWossman** [comment]
It's not too bad in the end. At least one more thing that makes you visit the nether ;)

**Comment by Radst0ne** [comment]
and again obsidian isnt a gamebreaker, maybe adding a hint ingame that the "bug" is already known?

**Comment by boubou19** [comment]
The thing I want to tell is that you can use blood to make obsidian because there is water in blood but making obsidian with nitric acid doesn't make sense in my opinion. Also i saw squid swimming in nitric acid without taking damage x)

**Comment by Dream-Master** [comment]
But i close this now.
