### ISSUE TITLE
Large Heat Exchanger Tool Tip Improvement

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1839]
1.5.1.0

At some point the mechanics and efficiency for the large heat exchanger was buffed to have 10x steam output when using hot coolant and having its max input rate when using hot coolant by 10x, this needs to be in the tool tip as this greatly changes the behavior of the multiblock and this information is needed to correct the following things.

a. someone checks the math for the multiblock on the gregtech wiki and makes the assumption that it is not worth due to having a hard time beating out the 10x boosted normal reactors.

b. someone creates a setup using the incorrect math or follows a tutorial assuming it would work as expected in the main gregtech branch and then has a interesting time trying to figure out what is going wrong with their new expensive hole in the ground.

**Comment by Dream-Master** [comment]
Yes you right we need a tooltip here.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29327083-39258400-81ee-11e7-86f7-9c960291470f.png)
