### ISSUE TITLE
Nerfe Project Red next after IC2

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#184]

**Comment by Drobac** [comment]
Thaumcraft after that? wands recipes need fixing

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
Only Machines need to be nerfed (36) Than i beginning with Project Red.

**Comment by Dream-Master** [comment]
IC2 is ready starting tomorrow Project Red

**Comment by Dream-Master** [comment]
I am on it and i think it is very soon done.

**Comment by Dream-Master** [comment]
done
