### ISSUE TITLE
Think Tank infusion not working

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#1840]
#### Which modpack version are you using?
1.5.10

The Infusion Altar recipe for the Think Tank isn't working. I have all the proper items on the pedestals - and they were all crafted fresh today to ensure there wasn't an issue with old items from a previous version. When I right click on the altar to start the infusion nothing happens.

![2017-08-14_21 49 35](https://user-images.githubusercontent.com/720212/29299233-339ea93e-813b-11e7-8c90-a3785b5b7cac.png)

**Comment by Dream-Master** [comment]
The think tank use the original recipe i not change it but i wrongly remove it. With the changes it should work again.
