### ISSUE TITLE
Silicon Wafer Quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1842]
#### Which modpack version are you using?
1.5.1.0

This quest should only require creating the wafers and not a mv cutting machine as the recipe can be performed in the lv cutting machine that you made to unlock tier 3.

**Comment by Dream-Master** [comment]
Ok will look Ingo it.

**Comment by Dream-Master** [comment]
Sure but you need it for the irl and rams 2 Quests later. Will add the mv cutter there.
