### ISSUE TITLE
Large chemical reactor broken or tooltip incorrect? (1.5.1.0)

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#1845]
Version 1.5.1.0 ---- 05.08.2017

I'm not sure if the tool tip for the large chemical reactor is incorrect, but I've tried making one following the tooltip but it's unable to form a complete structure. Having googled a bunch, I'm unable to find a picture of a complete structure anywhere.

_Here's the steps how I build it._ 

http://www.theicecave.net/files/user/pictures/screencaps/javaw_2017-08-16_16-03-02.png
http://www.theicecave.net/files/user/pictures/screencaps/javaw_2017-08-16_16-03-56.png

**Bottom:** 
large chemical reactor
input/output bus and hatch.
hv energy hatch
maintenance hatch
cupronickel coil.

**Mid:** 
PTFE pipe machine casing, surrounded by 8 inert machine casings.

**Top:** 
9 inert  machine casings.

**Comment by Dream-Master** [comment]
@JohannesGaessler any idea?

**Comment by JohannesGaessler** [comment]
The controller has to be placed in the middle layer, not the bottom layer.

**Comment by Dream-Master** [comment]
@JohannesGaessler is this a tool tip error or a user error ?

**Comment by JohannesGaessler** [comment]
I would say the tooltip is correct.
It reads 'Controller (Front centered)'.
This is the same wording as with the Vacuum Freezer or the Implosion Compressor.
Machines whose controller is at the bottom (like the Multi Smelter) have a different tooltip.

**Comment by Dream-Master** [comment]
@JohannesGaessler ok thanks for info. @NedStarCryo hope all is clear so far !?

**Comment by NedStarCryo** [comment]
D'oh, completely overlooked the middle layer as a possibility. I suppose that's what I get when my friends made the 3x3 multi block machines.
Many thanks.
