### ISSUE TITLE
Advanced Jetpak quest

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#1846]
In der quest fuer das advanced jetpack benötigt man als vorbereiitung lauter items die man beim craften gar nicht bracuht, schein als waeren die vorbereictungs quest / die items von dieser noch von einem alten rezept

**Comment by Dream-Master** [comment]
Ok will check the Quests.

**Comment by Dream-Master** [comment]
One quest requieremets was wrong the rest seems ok.
