### ISSUE TITLE
Nuclear fuel rods and Reprocessing [1.5.10]

### ISSUE THREAD

**Issue by AmishInvader** [GTNewHorizons/NewHorizons#1847]
Depleted naquadah and depleted naquadriah fuel rods (single only) give 3 more platinum dust than they should, when processed in the centrifuge.  The double and quad rods have the correct amount.  

Also, the thorium, mox, and uranium double and quad rod reprocessing in the thermal centrifuge doesn't return all the iron/steel from the empty rods.  Dual fuel rods return 3 iron dust, but take 2 iron, 2 steel to craft.  Quad fuel rods return 6 iron dust, but take 10 iron to craft.  Unsure if this is intended.

**Comment by Dream-Master** [comment]
No. Need to check.

**Comment by Dream-Master** [comment]
I will add it to thermal centrifuge also and change the amount.

**Comment by Dream-Master** [comment]
The difference is this is a Centrifuge recipes (because of 6 outputs) the others use Thermal Centrifuges recipe. If it is possible to add 3 more slots to the thmal centrifige i could add the recipe there.

**Comment by MineAnPlay** [comment]
No don't make it output Tungstensteel Dust. Make it output Tungstensteel Plates.

**Comment by Dream-Master** [comment]
Sorry i dont get your logic behind it. Why plates? i will give the Thermal Centrifuge in a future update 3 slots more then i will pack it back.

**Comment by MineAnPlay** [comment]
Because NO ONE will use it if you return dusts since you will have to resmelt the tungstensteel . Also PLEASE don't add 3 more slots to the thermal centrifuge JUST to add a few recipes...

**Comment by combusterf** [comment]
>  Dual fuel rods return 3 iron dust, but take 2 iron, 2 steel to craft. Quad fuel rods return 6 iron dust, but take 10 iron to craft.

Was this intentionally left this way, or should the first generation duals/quads still be updated to 4/10 iron returns?

**Comment by draknyte1** [comment]
> possible to add 3 more slots to the thmal centrifige

Any single machine that has ‘recipes containing too many alots’ Can always be processed in the equivalent multiblock. Nobody EVER needs to adjust machine input slots..

On a side note, single rod fuel cells have some unique processing due to GT++.
