### ISSUE TITLE
Ethanol

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1848]
#### Which modpack version are you using?
1.5.1.0

I did some testing on creating Bio-Diesel,
Here is what I found:
The Gregtech way (all mv machines):
To create 300mb of Ethanol you need:
32 wheat that gets processed to Biochaff requires:
1: Compressor
2: Pulverizer
3: centrifuge
These three machines need 40s to create 2000mb "Biomass" (they produce biochaff but its around 2000mb Biomass)
Now I took the Pyrolyse Oven (4) way because its more efficient, it takes just 4,5s to create 2000mb Biomass
To get Ethanol out of Biomass you need a:
5: Distillery
6: Fermenter
Together they need 150s to create 300mb Ethanol out of 2000mb Biomass (32 wheat)
So you need 6 Machines and a total time of around 194,5s for 300mb Ethanol (mv)

The Forestry way:
64 Wheat (did choose wheat because it somewhat easier to campare) which gets compressed (1) to 8 Plantballs which takes up 60sec and will equal 1000mb of Biomass
For the actual Biomass you need 8 Plantballs, 666 Fruitjuice (Squeezer, or fluid extractor, took the Squeezer (2) into account), and some compost (1dirt (renewable out of Biochaff ratio 1:1), 4 wheat)
The Fruitjuice needs in a fully upgraded Squeezer (2) 8s (~4 Cactus Fruit, each 200mb)
1000mb Biomass takes 9,3s 
The Still (3) needs 25s and creates out of 1000mb Biomass 300mb Ethanol
So you need only 3 Machines, 103s of time, and not a single Multiblock.
Note: I didnt include the compost because one compost is enough for 10k biomass, soo not a big deal.

Conclusion the Forestry way is way more cheaper and faster (you can make it even faster and better with different ressources, to get more fruit juice and biofuel) in mv, you would need hv machines to compensate it

Sugesstions:
I like that, that you can "ennoble" your biomass with various fluids, maybe add that to the Pyrolyse Oven for a even better output of biomass? Or maybe add Fruitjuice in Bio-Diesel Recipe?
Greater output of ethanol, forestry has 10:3 gregtech only 10:1,5?
make the fluid extractor faster, a buff for peanuts and hazelnut etc.? (the squeezer with speed upgrades just needs 2,5s for a peanut, the fluid extractor 10s (36mb seed oil)
Generalize the Biomass? Forestry is producing its own gt the ic2

**Comment by Radst0ne** [comment]
![2017-08-16_22 37 00](https://user-images.githubusercontent.com/27621272/29384271-cc15fae8-82d3-11e7-8f44-2713f94138d4.png)

**Comment by MineAnPlay** [comment]
Dream about the fluid extractor part you need to buff it since vanilla seeds were buffed (They produce 10L from 3L and takes 16 ticks from 400 ticks. So produces 83.3333.) So I recommend to boost all outputs by 3.333 and make all recipes require 16 ticks.

**Comment by Radst0ne** [comment]
what about using bacteria :P ?
It could be used with biomass creating fermented biomass and a little bit of methane
Then more steps are required but the output is more rewarding

**Comment by Dream-Master** [comment]
@Radst0ne If this is a relistic recipe why not.

**Comment by Radst0ne** [comment]
"Im Fermenter findet unter anaeroben (Bakterien welche sich im Boden und Gewässern befinden) Bedingungen eine Sukzession von Abbauprozessen statt, bei denen die Inputstoffe Schritt für Schritt in kleinere Bestandteile zerlegt werden. Die Protagonisten dieses Gärprozesses sind bestimmte Mikroorganismen (hauptsächlich Bakterien), denen die organische Substanz der Inputmaterialien als Nahrungsgrundlage dient."

Und

"Mikroorganismen, welche die Biomasse zersetzen und vor allem das Methan produzieren"

Hier zum nachlesen :-D :

http://www.biomasse-nutzung.de/biomasse/energetische-nutzung-bioenergie/betreiben-einer-biogasanlage/der-fermenter-mikrobiologie-biochemie-und-inputstoffe/

**Comment by Dream-Master** [comment]
Ja gut mach ich mal ein Rezept :P

**Comment by Dream-Master** [comment]
@Radst0ne allready pushed with FR Biomass now(new recipes)
