### ISSUE TITLE
Tinkers construct bolts get messed up after upgrading them

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1850]
#### Which modpack version are you using?
1.5.1.0
#### If in multiplayer; On which server does this happen? 
Multiplayer private server
#### What did you try to do, and what did you expect to happen?
Me and my friend upgraded our bolts to the same material. He upgraded from manyullyn to vanadium steel and I upgraded from darksteel to vanadium steel. We ended up with bolts that have completely different stats even when they are from the same material.
#### Replicating the issue
To replicate the issue first make a crossbow bolt with some bad tip and then upgrade it to a crossbow  bolt with a better tip. Then compare the upgraded crossbow bolt to the bolt that you craft with the better tip from the start.

https://puu.sh/xcHuc/563ac32a95.mp4
#### What do you suggest instead/what changes do you propose?
Either fix the issue or disable upgrading the crossbow bolts.

**Comment by Ugachaga** [comment]
https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/216

**Comment by Lainiel** [comment]
It somehow messes up armor penetration so you can end up with bolts that almost ignore armor. I haven't figured out how that one works though.

**Comment by Ugachaga** [comment]
If i remember correctly, it is bug between Iguana Tweaks and Tinkers Construct interactions. TC does not recalculate damage for bolts and use constant value given at creation (cuz TC did not expect that bolts will be upgradeable).

Wold be great if someone patch TC. :)

**Comment by Dream-Master** [comment]
@Ugachaga we fork Tico so if you able to do it would be nice.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/TinkersConstruct

**Comment by Ugachaga** [comment]
@Dream-Master 
Nah, it's too complicated to quick fix. Have to change "base attack" NBT tag while upgrade bolts attack. If someone want to try, I'd start [there](https://github.com/GTNewHorizons/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/replacing/ReplacementLogic.java#L361) (TC logic [there](https://github.com/GTNewHorizons/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/library/entity/ProjectileBase.java#L195)).

**Comment by Dream-Master** [comment]
My knowlede of Java is to low for doing such job sorry. @Ugachaga

**Comment by Dream-Master** [comment]
@Ugachaga any news here is this fixed?

**Comment by Dream-Master** [comment]
No one fixed it till now.
