### ISSUE TITLE
Void Aspected Silverwood Wand

### ISSUE THREAD

**Issue by npo6ka** [GTNewHorizons/NewHorizons#1851]
#### Which modpack version are you using?
1.5.1.0
#### What did you try to do, and what did you expect to happen?
I wanted to craft Void Aspected Silverwood Wand. 
All recipes of 100 capacity wands should use Tungsten Steel, but recipes of wands from void metal and Ichorium are made through titanium screw, although even in the table indicated Tungsten Steel screw.

![2whbgriamxk](https://user-images.githubusercontent.com/13215491/29436388-e1ec166e-83b3-11e7-8f9a-679901c9edf2.jpg)
![pkelp1l9bug](https://user-images.githubusercontent.com/13215491/29436390-e1eda736-83b3-11e7-8bdc-80374913c167.jpg)
![ps8jgufgu_e](https://user-images.githubusercontent.com/13215491/29436389-e1ed45e8-83b3-11e7-8cb2-59c41fc5bfcc.jpg)

**Comment by Dream-Master** [comment]
Maybe my mistake. Will check it.

**Comment by npo6ka** [comment]
With Ichorium the same problem...

**Comment by Dream-Master** [comment]
@npo6ka Ichorium. Can you said which Ichorium wand ?
