### ISSUE TITLE
Add 3 more output slots to the Thermal Centrifuge if posible.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1852]
Add 3 more output slots to the Thermal Centrifuge if posible.

**Comment by Dream-Master** [comment]
@JohannesGeassler is it possible to add 3 more slots because the Thermal Centrifuge was a Ic2 machine?

**Comment by Dream-Master** [comment]
The change would be nice because the Naquada and Naquadria depleted rods need more then 3 outputs to be back processed and are now available as centrifuge recipes.

**Comment by MineAnPlay** [comment]
Don't need to add it just use the centrifuge for the depleted fuel rod recipes like how Tec did it.

**Comment by Dream-Master** [comment]
Yes but the logic to use the thermal centrifuge is brocken.

**Comment by Dream-Master** [comment]
Maybe later.
