### ISSUE TITLE
Single Block Distillery cannot process certain intermediate cracked fuels

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1853]
Using 1.5.10

Tried to use single-block distillery to process lightly steam-cracked propane. Recipe requires 2000 lightly steam-cracked propane, but distillery can only hold 1000. This makes this recipe impossible. According to NEI, distillery recipes using the following are also impossible in the single block because they require more than 1000 of the input:

Lightly Steam-Cracked Butane
Moderately Steam-Cracked Butane
Severely Steam-Cracked Butane
Moderately Steam-Cracked Butene
Severely Steam Cracked Butene
Lightly Steam-Cracked Butadiene
Moderately Steam-Cracked Butatiene
Severely Steam-Cracked Butatiene
Lightly Steam-Cracked Propane
Severely Steam-Cracked Propane
Lightly Steam-Cracked Refinery Gas
Moderately Steam-Cracked Refinery Gas
Moderately Steam-Cracked Ethane

![image](https://user-images.githubusercontent.com/30811906/29476140-95fa0c02-8430-11e7-9559-47f70506dd80.png)

Example recipe from NEI:

![image](https://user-images.githubusercontent.com/30811906/29476227-fede26ea-8430-11e7-984b-5ba92e09ef64.png)

Suggestions is either to factor the recipes down to 1000 each, or expand capacity of single block distillery to 4000mB. Not sure which would be easier.

**Comment by Dream-Master** [comment]
@JohannesGaessler any idea here?

**Comment by Dream-Master** [comment]
@AlphaApotheosis which version do you using?

**Comment by AlphaApotheosis** [comment]
Version 1.5.1.0, single player. But I think the distillery has always had a 1000mB capacity.

**Comment by Dream-Master** [comment]
yes but this fix was added.

https://github.com/Blood-Asp/GT5-Unofficial/pull/1156 
@AlphaApotheosis

**Comment by Dream-Master** [comment]
will check when i add this fix

**Comment by Dream-Master** [comment]
12.8.2017 so will be fixed in the next version 1.5.1.1 today. @AlphaApotheosis
