### ISSUE TITLE
1.5.1.0 Dire crafting quest issue

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1855]
You need to complete Time to kill (Wither) to unlock the dire crafting table quest in the Space Race quests, but there's no mention about it anywhere. Also you have to complete all the other Time to kill quests to make the Wither quest even visible.

#### What do you suggest instead/what changes do you propose?
Don't lock the Wither quest behind the other Time to kill quests and mention it somewhere that it's needed to progress further. Also I think it's a bad idea to lock it behind a quest that is from a completely different tab and isn't even labeled as a main quest.

**Comment by Dream-Master** [comment]
Ok maybe i remove it from Wither Kill Quest.
