### ISSUE TITLE
Extruder rotor shape is single-use

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#1857]
#### What happend instead? (Attach screenshots if needed)
'Extruder Shape (Rotor)' is single-use, e.i. used up when used in the Extruder. 
(The new small gear shape is correct, e.i. not single use)

#### What do you suggest instead/what changes do you propose?
Correct Rotor extruder form to not be single-use.

**Comment by ko5h** [comment]
and mold rotor too
