### ISSUE TITLE
1.5.1.1 Broken light fuel recipe

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1858]
This recipe no longer works on 1.5.1.1 for no real reason:

It's sulfuric light fuel with hydrogen cells into light fuel.

![Light fuel recipe](https://puu.sh/xefly/f48a60133f.png)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/b36b8a39719984f5826241347ca5e18d7b00402d
