### ISSUE TITLE
Lightning Effect Balancing

### ISSUE THREAD

**Issue by Orchian** [GTNewHorizons/NewHorizons#1859]
#### Which modpack version are you using?
GTNH 1.5.1.1
#### If in multiplayer; On which server does this happen? 
Zeta (Presumably others as well)
#### What did you try to do, and what did you expect to happen?
I tried to go along my merry way to a different location.
#### What happend instead? (Attach screenshots if needed)
Instead, I constantly got struck by lightning by rare mobs.
#### What do you suggest instead/what changes do you propose?
I think that either the lightning modifier should be less common, or that lightning strikes
from mobs with the lightning modifier should happen less often.

**Comment by Dream-Master** [comment]
I think you was very unlucky. If you went far enough unload the chuncks the mob are gone.

**Comment by Orchian** [comment]
Unloading chunks does not despawn mobs.
