### ISSUE TITLE
GT++ Fish Catcher Server Messeges

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#1864]
#### Which modpack version are you using?
1.5.1.1
The gt++ fish catcher is printing when and what it is generating to the server window.

**Comment by Dream-Master** [comment]
@drakynet1 any idea. I using latest source from gt++.

**Comment by draknyte1** [comment]
It's debug code.. it'll get removed when I finish working on redoing the loot.. don't release your modpack with src built versions is all I'd say to this.

**Comment by Dream-Master** [comment]
@draknyte1 i guess it is removed in newest code?

**Comment by Dream-Master** [comment]
guess this is fixed too ? @draknyte1
