### ISSUE TITLE
[Quest] Gas Turbine wording needs updated

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1865]
#### Which modpack version are you using?
1.5.1.1

Gas turbine quest in LV says "dump your unused food in a centrifuge to get methane gas" however this is not possible according to NEI. Only "LV" source for Methane gas is rubber wood. Energy output is net-positive, but not great, and requires large quantities of wood to make significant methane gas. 1 wood = 60 methane gas.  Maybe this would be a good intro quest to Forestry wood farms?

**Comment by Dream-Master** [comment]
Yes good idea will update the quest.

**Comment by Dream-Master** [comment]
I add all Logs to the recipes using oredict.

**Comment by richardhendricks** [comment]
Should the ratio change? Is 1 wood to 60 methane reasonable?

**Comment by Dream-Master** [comment]
No one log = 60. You can use fermented biomass for better methane output.
