### ISSUE TITLE
(1.5.1.1) Redstone Alloy Cable has no collision box (MP only issue)

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#1866]
(1.5.1.1)

#### If in multiplayer; On which server does this happen? 

The issue only happens on multiplayer, server doesn't matter as I tried a fresh new server to rule out server-side issues.
Single player is 100% fine and the issue does not occur here.
Blue alloy cable also does not have this issue.

Due to not having a collision box on the redstone alloy cable you're unable to place them on top of another nor are you able to remove them. By pixel seeking you can sometimes "find" the cable and remove it, but its flaky at best. 

http://www.theicecave.net/files/user/pictures/screencaps/javaw_2017-08-21_17-58-10.png

**Comment by Dream-Master** [comment]
@Technus, @JohannesGaessler any idea. Is this messed up in code somewhere?

**Comment by Technus** [comment]
no wire code was changed since long time ago anyway, i bet there is some texturing issue or smth

**Comment by Dream-Master** [comment]
@Technus This was fixed right?
