### ISSUE TITLE
Plated Reinforced Stone Tooltips

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1868]
Some tooltips that show their blast resistances would be nice, makes it easier to find them if you want to make a reactor casing that uses these (assuming that's what they are for)

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29535361-d74c91a8-86b9-11e7-9e49-81ebc95951ec.png)

**Comment by mtesseracttech** [comment]
nice
