### ISSUE TITLE
[Suggestion] Some missing things about slimeballs.

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/NewHorizons#1870]
@Dream-Master 
1) Raw rubber in GTNH can be obtained from Sticky Resin (3 items) and from slimeballs (2 items). Sticky Resin also produces in Centrifuge Raw Rubber (3 items) and Refined Glue (100 mB). I think, it is logical to add recipes for processing all types of slimeballs in Centrifuge to obtain 2 Raw Rubber (like in Extractor) + 50 mB of Refined Glue.
2) In GTNH there's fast way to obtain large amounts of rubber (raw): it is Slimy trees. From 16 trees I get (in average) 48 blocks of slime = 192 slimeballs = 6 stacks of raw rubber (after extracting these blocks twice). For comparison: with 16 Rubber tree and treetap I get 32 Sticky resin (in average) = 1.5 stacks of raw rubber.
I suggest to add optional quest for finding Slimy sapling and for producing with it large amounts of raw rubber. I advice to add quest after *Steam Age/How to make rubber* (Place new quest just above this; you can name it like 'How to get more rubber?').

**Comment by WarlordWossman** [comment]
Sounds like a good idea. I wish there was more reasons to find a slime island tho.

**Comment by Dream-Master** [comment]
Yes will do a Quest wher you need to found one.
