### ISSUE TITLE
Recipe cleanup

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1873]
I was trying some stuff with GT++ and something I noticed was that it has a large amount of items that should not really be there if one follows GT conventions. For example, the tiny/small dusts and the nuggets of items should be made invisible in NEI. (I know for a fact Alkalus doesn't really care about this, so minetweaker could be an alternative).
Also it could be nice to have the items that are just disabled be made invisible in the pack. For example the foods GT++ brings.

**Comment by mtesseracttech** [comment]
Little note: This could be nice to be done for everything that is supposed to be unobtainable, not just in GT++.

**Comment by Dream-Master** [comment]
sure if you can add it at pull request i am happy not do it myself :)

**Comment by mtesseracttech** [comment]
To be fair, I have no idea how Minetweaker works, mind creating a little example? Then I will follow and add the other items.

**Comment by Dream-Master** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:NEI_Support
