### ISSUE TITLE
(1.5.1.1) Item Filter zinc foil + carbon mesh results in gt lava filter instead. 

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#1875]
1.5.1.1

There's an overlap with the gt++ Lava Filter crafting recipe and the gregtech item filter. 
Zinc + carbon mesh results in a lava filter instead of an item filter.
It did not do this in 1.5.1.0.

http://www.theicecave.net/files/user/pictures/screencaps/ShareX_2017-08-23_00-50-41.png

NEI 
http://www.theicecave.net/files/user/pictures/screencaps/javaw_2017-08-23_00-51-46.png

**Comment by Dream-Master** [comment]
Any idea @draknyte1?

**Comment by draknyte1** [comment]
No because the lava filter doesn't require either of those items.

**Comment by NedStarCryo** [comment]
I don't know if GThorizon changes the lava filter recipe but the current recipe is 16 carbon mesh.
Not quite sure why it's 8+8 as jamming in 16 makes it anyway?
http://www.theicecave.net/files/user/pictures/screencaps/javaw_2017-08-23_13-57-37.png

There's only 2 recipes with carbon mesh in the assembling machine, I'd suggest adding in a circuit to one of em.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29635336-0e8f2308-884d-11e7-8a78-10d11d9f2f90.png)

**Comment by Dream-Master** [comment]
not needed so far i can see. slot 2 have different ingredients.

**Comment by Dream-Master** [comment]
tested both recipes works fine.

**Comment by NedStarCryo** [comment]
@Dream-Master 
I assume you used exact amounts of carbon mesh to make the item filter?

Try put in a stack of carbon mesh in slot 1, it will make lava filters. Making item filters in bulk with carbon mesh is going to need a regulator. The moment the assembling machine has made a lava filter it will refuse to make any item filters. 

Assembling machine with a stack of carbon mesh in slot 1 resulting in a lava filter, the 2nd slot does not need carbon mesh for it to make lava filters.

![javaw_2017-08-23_22-58-22](https://user-images.githubusercontent.com/2922511/29638178-b318153e-8856-11e7-89ca-0c128da150f4.png)

It's no longer willing to make item filters after you've made a lava filter.


![javaw_2017-08-23_23-06-21](https://user-images.githubusercontent.com/2922511/29638489-b1f6f660-8857-11e7-8395-84aff31f2126.png)

A freshly build assembling machine with no more than 16 carbon mesh to avoid colliding with the other recipe.

![javaw_2017-08-23_23-02-15](https://user-images.githubusercontent.com/2922511/29638320-3320c19a-8857-11e7-9676-e72ae16829ec.png)

Hopefully this clears it up.

**Comment by draknyte1** [comment]
This is a strange bug. Not sure why it happens in your fork.

**Comment by Dream-Master** [comment]
Ok ok I add a circuit.

**Comment by draknyte1** [comment]
I already fixed the recipe. Just haven't pushed today's commits yet.

**Comment by Dream-Master** [comment]
Ok cool

**Comment by Dream-Master** [comment]
@draknyte1 thanks
will add a circuit in gt too .

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29831813-972ce7ac-8ce6-11e7-870e-0c4b681f5686.png)
![image](https://user-images.githubusercontent.com/2970688/29831827-a02da526-8ce6-11e7-8188-5b58fde325ba.png)

**Comment by Dream-Master** [comment]
@NedStarCryo so far I not push a new update I let it open and close it later.

**Comment by draknyte1** [comment]
If you've updated GT++ since this was noticed it's been fixed there.

**Comment by Dream-Master** [comment]
@draknyte1 next release have both recipes with circuits 😁
