### ISSUE TITLE
[Quest] Steve's Carts Assembler needs gating behind multiple quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1876]
#### Which modpack version are you using?
1.5.1.1

Currently Steve's Carts Assembler is available right when you enter LV. However it is dependent upon several items: Robot Arms, Conveyor Modules, and Fluid Extractor (to make Simple PCBs requires liquid solder alloy).

**Comment by Dream-Master** [comment]
Yes i know but is impossible to add more dependencies because the Questbook looks like a spider net allready. (Robot arm and fluid extractor)

**Comment by Dream-Master** [comment]
@richardhendricks any better idea about it?

**Comment by Dream-Master** [comment]
![questbook](https://user-images.githubusercontent.com/2970688/29635284-e834f87c-884c-11e7-901d-48dd6fcc087c.png)

**Comment by richardhendricks** [comment]
Yeah that is pretty ugly. Robot Arms and Conveyors are necessary items for the quest. But needing a Fluid Extractor to make Liquid Soldering Alloy is not obvious, and might be missed if a player is doing it step by step.

I dunno.  I like having the Steve's Cart visible as an automation goal.  

Change the quest description so that it warns you will need a Fluid Extractor and Soldering Alloy to make the Steve's Carts circuits? 

Or add a quest before the Cart Assembler to make the Soldering Alloy & Steve's circuits?

Another option could be to split off Steve's Carts into a seperate tab, like Forestry and Farms.

**Comment by Dream-Master** [comment]
MAke a new chapter is possible and maybe better.

**Comment by Bryfer** [comment]
What about adding Steve's cart (with farm quest) to the forestry and farms chapter? 
Both of them are unlocked at pretty much the same tier. It's just personal preferences that makes people build one of the two anyway 

I haven't seen people use Steve's cart for anything other than farms anyway

**Comment by richardhendricks** [comment]
Makes sense to me. I don't know how full the chapter is with quests.

**Comment by Dream-Master** [comment]
Not really so much space.

**Comment by Dream-Master** [comment]
I will do a New Chapter because we get more steve carts quests in the future and forestry get new quests too.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29842831-508da18c-8d0a-11e7-99b6-fa803ab5e9ef.png)
![image](https://user-images.githubusercontent.com/2970688/29842853-61e4c924-8d0a-11e7-834f-9b36a53a2074.png)
![image](https://user-images.githubusercontent.com/2970688/29842862-68d7fe5e-8d0a-11e7-845a-02f2e1f823e5.png)

**Comment by richardhendricks** [comment]
I like it, looks great.
