### ISSUE TITLE
(1.5.1.1) BrainTech duct tape uncraftable.

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#1877]
1.5.1.1

The BrainTech duct tape is no longer craftable/the recipe is not showing up in NEI

Seems to be related to GT++ lava filter crafting recipe as well.

#1874 
#1875

**Comment by Dream-Master** [comment]
yes probaly. Will add circuits in recipes.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29831752-6393ec6a-8ce6-11e7-8061-a6e34d9fa11e.png)
proof
