### ISSUE TITLE
Minor quest in Transport modification

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/NewHorizons#1878]
#### What do you suggest instead/what changes do you propose?

the quest for the basic extruder (#673) is a crafting task, should be a retrieval task like other machines quests.

the Transpotting quest (#667) may be better with an explaination of how to submit the 60L creosote with the Better Quest object submit block because because we can't get a drum at this point of time.

**Comment by Dream-Master** [comment]
All Fluid submit quests are changed in 1.5.

**Comment by Dream-Master** [comment]
Extruder Quest change.
Creasote removed in 1.5
