### ISSUE TITLE
wrong recipy macerating iron tanks

### ISSUE THREAD

**Issue by Smeany** [GTNewHorizons/NewHorizons#1880]
#### Which modpack version are you using?
1.4.1.1
#### What did you try to do, and what did you expect to happen?
when macerating an iron tank wall from railcraft u get 20 iron nuggets back,
although u only need 2 iron plates to produce an iron tank wall in
the assembly machine. so you get back 2 nuggets too much.

**Comment by braeven** [comment]
This problem also happens when using arc furnace/plasma furnace

Modpack Versions: 1.4.1.1 and 1.5.1.1

Also applies to:
- Iron tank gauge
- Steel tank walls
- Steel tank gauge

Steel tank valve and iron tank valve on the other hand are only giving back around 90% of used materials

**Comment by Bryfer** [comment]
Closed issue, and dupe of #1212
