### ISSUE TITLE
[1.5.1.1] Steel Plate task on Flint and Steel quest can't be completed

### ISSUE THREAD

**Issue by Dreadchain** [GTNewHorizons/NewHorizons#1881]
#### Which modpack version are you using?
1.5.1.1
#### If in multiplayer; On which server does this happen? 
Private MP server

Problem:
The flint and steel quest in Tier 1 Steam quests can't be completed. The steel plate expected seems to be a railcraft plate and I couldn't make it work despite trying all available steel plate production methods available to me. I did attempt manual submit after each time I created a plate. 

Fix:
I changed the req to the Gregtech steel plate via /bq_admin edit and the quest seems to work OK now. Should be an easy fix, if this issue is reproducible by others.

**Comment by OneEyeMaker** [comment]
#1716

**Comment by Dream-Master** [comment]
@Dreadchain no i fix that. Please update your quest.
/bq_admin default load

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29831183-9f77f340-8ce4-11e7-80f5-008bd323de68.png)
proof its oredicted
