### ISSUE TITLE
Extruder Shape verschwindet

### ISSUE THREAD

**Issue by Larsinator78** [GTNewHorizons/NewHorizons#1882]
#### Which modpack version are you using?
GT: New Horizons
#### If in multiplayer; On which server does this happen? 
HUG Community
#### What did you try to do, and what did you expect to happen?
Rotor im Extruder gemacht 
#### What happend instead? (Attach screenshots if needed)
Danach war die Shape weg
#### What do you suggest instead/what changes do you propose?
Soll nicht verschwinden

**Comment by Dream-Master** [comment]
fixed.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1857
