### ISSUE TITLE
Quest party not working properly. GTNH

### ISSUE THREAD

**Issue by Oliverxll** [GTNewHorizons/NewHorizons#1883]
#### Which modpack version are you using?
GregTech New Horizons
#### If in multiplayer; On which server does this happen? 
Dirthuts
#### What did you try to do, and what did you expect to happen?
My friend had already played on the server and completed a lot of quests in the quest book, he just told me to join his party so we would have same progress, this did both happen and not happen completely, I got progress towards a lot of quests, like completed a few of the steps in it but not the entire quest, some I completed totally, two of which I can't complete, it says they're complete but when you enter it to see the steps taken to do it it says some is not completed nor can I claim the rewards for it. Dunno if it's a server sided thing, client or just a bug with the modpack
#### What do you suggest instead/what changes do you propose?
Just a fix I suppose?

**Comment by Dream-Master** [comment]
There is a small mod.
You need to add this to the server and write /bq_copyquests PersonToInviteUsername and than invite person to party

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/zp8fh72j0gahrqy/BQShim-1.0.jar?dl=0
