### ISSUE TITLE
Unable to infuse Shadowmetal Cap

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#1884]
#### Which modpack version are you using?

1.5.1.1

#### If in multiplayer; On which server does this happen? 

Private Server

#### What did you try to do, and what did you expect to happen?

I tried to infuse shadow metal caps and it infuses it successfully.

#### What did happen instead? (Attach screenshots if needed)

Infusion didn't start

Screenshots of infusion:
http://i.imgur.com/D2t8d4y.png

There is no NEI receipt.
Screenshot of taumonomicon entry:
http://i.imgur.com/xhk3oM0.png

Script that does that:
https://github.com/GTNewHorizons/NewHorizons/blob/4ac1a0585e067afb0208cfd255b130b29fe56326/scripts/Tainted-Magic-1.zs#L928

I have checked the items and they are 100% right.
Don't know what causes this infustion not to work.

Duplicate of #914 but not fixed it seems.

**Comment by Dream-Master** [comment]
You look on the wrong line this line need a fix
https://github.com/GTNewHorizons/NewHorizons/blob/4ac1a0585e067afb0208cfd255b130b29fe56326/scripts/Tainted-Magic-1.zs#L927
