### ISSUE TITLE
[1.5.1.1] Cobblestone in SAG Mill produces gravel with incorrect metadata

### ISSUE THREAD

**Issue by anyname2** [GTNewHorizons/NewHorizons#1886]
#### Which modpack version are you using?
1.5.1.1

#### If in multiplayer; On which server does this happen? 
Private server

#### What did you try to do, and what did you expect to happen?
Put cobblestone into SAG mill to get sand and gravel.

#### What happend instead?
Sand was correctly produced, but gravel has invalid metadata.

#### What do you suggest instead/what changes do you propose?
Fix gravel output metadata in this recipe.

**Comment by Dream-Master** [comment]
Ok will do.

**Comment by Dream-Master** [comment]
This is a vinilla aded recip bei ender io. Not sure if i can remove it. Does it work or not?

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/ThaumicBases/issues/8

**Comment by Dream-Master** [comment]
Thamic Bases not ordict Gravel anymore.
