### ISSUE TITLE
Corals missing on the server.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1887]
#### Which modpack version are you using?
1.4.1.1
#### If in multiplayer; On which server does this happen? 
Epsilon
#### What did you try to do, and what did you expect to happen?
Flew across oceans, expected to find "Coral Reef" biome.
#### What happend instead? (Attach screenshots if needed)
RWG doesn't generate additional BoP ocean biomes so there's no Corals to be found.
#### What do you suggest instead/what changes do you propose?
Add following recipes:
Algae + Glowstone = Glowing Coral
Algae + Glowstone + Pink Dye = Pink Coral
Algae + Glowstone + Blue Dye = Blue Coral
Algae + Glowstone + Orange Dye = Orange Coral

These are purely esthetic and Algaes can be found in current environment.

**Comment by Dream-Master** [comment]
Sure Why Not.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29818968-d6bb232a-8cbe-11e7-81d0-680e5112c17b.png)
![image](https://user-images.githubusercontent.com/2970688/29818970-dbb358f2-8cbe-11e7-811f-06e4db230a96.png)
