### ISSUE TITLE
Extra utilities conveyor

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1888]
Why extrautilities conveyor so expensive? 5 lv motors not a problem, but motor machine casing in center need 2 hv motor and 2 advanced circuits and it's too much. Maybe solid steel casing or steel frame box in center will be better?

We need about 3 stack of this conveyors to make efficient spawner.

**Comment by Dream-Master** [comment]
Ok will review recipe.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29818656-b0eb1890-8cbd-11e7-809c-fe47a4d41091.png)
