### ISSUE TITLE
[1.5.1.1] Alloy Blast Smelter can be used to bypass EBF heating coils

### ISSUE THREAD

**Issue by Kataiser9** [GTNewHorizons/NewHorizons#1889]
The Alloy Blast Smelter can be used to make fluid versions of EBF items without the need for heating coils. For example, to make a black plutonium ingot, you can either use an EBF with a heat capacity of 9000, or you can just use an Alloy Blast Smelter with a fluid solidifier, which is of course much cheaper.

**Comment by Dream-Master** [comment]
@draknyte1 any idea how to fix or disable recipes?

**Comment by Dream-Master** [comment]
@Technus hope you can help here?
