### ISSUE TITLE
Edit recipes that use vanilla ender chest

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#189]

**Comment by Dream-Master** [comment]
I will replace it with Enderchest Mods Enderchest.

**Comment by Dream-Master** [comment]
Need some examples. Witch recipes use enderchests?

**Comment by Drobac** [comment]
dont know all of them but some recipes from JABBA and one from Thaumic tinkerer, but that one isnt an issue right now

**Comment by Dream-Master** [comment]
The Jabba ones i fix.
