### ISSUE TITLE
EBF liquid output recipe for sulfur dioxide does not work

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1890]
#### Which modpack version are you using?

1.5.1.1

#### If in multiplayer; On which server does this happen? 

In singleplayer

#### What did you try to do, and what did you expect to happen?

Used the EBF to process chalcopyrite dust with silicon dioxide and oxygen. The EBF is running with MV and has an output hatch for liquid. NEI says recipe should produce cupric oxide, ferrosilite, and liquid sulfur dioxide.

#### What happend instead? (Attach screenshots if needed)

Recieved cupric oxide and ferrosilite, But no sulfur dioxide appears in output hatch. Tried EBF recipe with Pentlandite dust and Cobaltite dust as well, same problem, got the solid dust output, but no liquid output in output hatch.

**Comment by Bluebine** [comment]
Works fine for me in singleplayer.
Make sure the output hatch is on the UPPER layer, near the muffler hatch, not the bottom one. That confused me for a bit.

**Comment by AlphaApotheosis** [comment]
Oh, you are correct. Never used output hatch on ebf before did not know it need to be on top layer. Will close issue.
