### ISSUE TITLE
1.5.1.1 No Recipe for putting Molten Polyethylene in a fluid cell

### ISSUE THREAD

**Issue by OperativeLoop** [GTNewHorizons/NewHorizons#1891]
#### Which modpack version are you using?
1.5.1.1
#### If in multiplayer; On which server does this happen? 
Private Server
#### What did you try to do, and what did you expect to happen?
Following questlines to make Molten Polyethylene, quest #759 asks for 5 cells of Molten Polyethylene, but there is not recipe to put the fluid form into a can. I tried pressurized Fluid tank from ender IO and basic fluid canning machine and either could make cells of it. 
#### What happend instead? (Attach screenshots if needed)
Molten Poly stuck in my basic fluid canner. 
#### What do you suggest instead/what changes do you propose?
Add missing recipes. 

![moltenpoly](https://user-images.githubusercontent.com/9806550/29752250-725a17e8-8b0f-11e7-9b4b-048e150e63a0.png)
![moltenpolyquest](https://user-images.githubusercontent.com/9806550/29752251-725be0a0-8b0f-11e7-99c3-8d5e6c9cb8eb.png)

**Comment by OperativeLoop** [comment]
Actually, found it works with Universal Fluid Cells and not the regular Empty Cells like I had

**Comment by Dream-Master** [comment]
Yes sadly some fluids are using Unversal Fluid cells. Try to dump the cells to a tank.

**Comment by OperativeLoop** [comment]
The problem is not getting it out of the cells, the problem is that it uses a different type of cell and it wasn't clear to me at first

**Comment by OperativeLoop** [comment]
@bigbass1997 said in discord that universal cells suck in general. If its possible to not have to use them at all, that would be great.

**Comment by bigbass1997** [comment]
No way to make Cells contain any other fluids? Universal Fluid Cells really are bad. They don't work well when automating GT machines, they are finicky, and their recipes don't even show up in NEI. Thus few people would know how to even complete the mentioned quest..

**Comment by Dream-Master** [comment]
@bigbass1997 should we register fluids to gt cells (the missing fluid ones)?

**Comment by Radst0ne** [comment]
also iron3chloride is not working with the ic2 cell, pretty sure it worked before

**Comment by Dream-Master** [comment]
wired i add it to gt cells i am sure.

**Comment by Dream-Master** [comment]
@OperativeLoop @bigbass1997 @Radst0ne 
can you name all the important fluid thats need a gt cell. I will try to add materials for it and registere it.

**Comment by Radst0ne** [comment]
steam (there is a recipe in the canning machine but you cant fill it with right click)
iron3chloride
every fluid that the vat (enderIo) does produce (not that important)

**Comment by Technus** [comment]
Most likely the same issue as with glue some time ago the fluid id missmatches in the recipe and registry

**Comment by Dream-Master** [comment]
But glue have a material and the molten materials not producing a gt fluid cell. Need a code addition @Technus  same for the fluids not on the material list like iron3chloride.

**Comment by Dream-Master** [comment]
@Technus any news ?

**Comment by Technus** [comment]
@Dream-Master as for quests - use GT cells when applicable or just give out ingots... if no cells exist
