### ISSUE TITLE
Processing some dust in EBF with oxygen produces wrong amount of sulfur dioxide

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1892]
#### Which modpack version are you using?

1.5.1.1

#### If in multiplayer; On which server does this happen? 

Singleplayer

#### What did you try to do, and what did you expect to happen?

Used the EBF to process sphalerite with oxygen. The EBF is running with MV and has an output hatch for liquid on the top level. NEI says recipe should produce 1 zincite dust, and 1000mB liquid sulfur dioxide.

![image](https://user-images.githubusercontent.com/30811906/29753433-60fb9ac8-8b3f-11e7-80af-58f295b25d68.png)

#### What happened instead? (Attach screenshots if needed)

Recipe produced only 50mB liquid sulfur dioxide, so either the recipe or NEI is wrong:

![image](https://user-images.githubusercontent.com/30811906/29753483-7462533a-8b40-11e7-85a0-ae0af17882be.png)

Seems to be the same issue with other minerals in EBF (chalcopyrite, cobaltite, etc)

**Comment by Dream-Master** [comment]
Output hatch need to be on top in EBF.

**Comment by AlphaApotheosis** [comment]
Yeah, I have the output hatch on top but I realized the muffler limits recovery. Closing issue.

**Comment by Dream-Master** [comment]
ah ok interresting dont now too. But i remeber Johannes said somethings.
