### ISSUE TITLE
[Quest] Basic Forming Press information incorrect

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1893]
#### Which modpack version are you using?
1.5.1.1

Basic forming press quest states that you can make basic circuits more efficiently using the press, however at LV you can't make Basic or Good circuits with it. Looks like from recipes it is for logic stuff, at least at LV. Should this have a different description, and a new quest added for Basic Circuit Assembler after Good Circuits?

**Comment by Dream-Master** [comment]
Could be a old description.

**Comment by OperativeLoop** [comment]
IIRC the basic circuit assembler is needed for one of the circuit quests on the MV page. (So I think the quest already exists for that but its in a weird place).

**Comment by Dream-Master** [comment]
@Giovanni-NL 
please go over it and correct spellings. Thanks

**Comment by Giovanni-NL** [comment]
@Dream-Master Done.  See https://github.com/GTNewHorizons/NewHorizons/pull/1900

**Comment by Dream-Master** [comment]
@Giovanni-NL thanks
