### ISSUE TITLE
Neutronium compressor

### ISSUE THREAD

**Issue by kris449** [GTNewHorizons/NewHorizons#1894]
#1649 

Impossible to craft as the infinity items require the compressor to make singularities, so basically nothing with infinity items can be made at all.

**Comment by Dream-Master** [comment]
I change it to neutronium plates and neutronium heavy plates.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29795436-825f7be0-8c4c-11e7-96c2-4136f18758c6.png)
