### ISSUE TITLE
Turbine extruder shape consumed

### ISSUE THREAD

**Issue by ddejong42** [GTNewHorizons/NewHorizons#1895]
#### Which modpack version are you using?
1.5.1.1
#### What did you try to do, and what did you expect to happen?
Used the new turbine shaping form to make a turbine blade, expected only the ingots to be consumed
#### What happend instead? (Attach screenshots if needed)
The shaping form was consumed along with the ingots
#### What do you suggest instead/what changes do you propose?
Shaping form should not be consumed

**Comment by Dream-Master** [comment]
fixed.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1857

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29795182-72bb06e2-8c4b-11e7-974b-9b0594a9973a.png)
proof
