### ISSUE TITLE
Suggestion: Rocket Tier 1 quest should accept rocket with cargo space

### ISSUE THREAD

**Issue by ddejong42** [GTNewHorizons/NewHorizons#1896]
#### Which modpack version are you using?
1.5.1.1
#### What did you try to do, and what did you expect to happen?
Made a Tier 1 rocket with a gold chest, hoped it would count for the quest Rocket Tier 1
#### What happend instead? (Attach screenshots if needed)
It did not count for the quest requirement
#### What do you suggest instead/what changes do you propose?
Either the tier 1 rocket models with varying cargo sizes should all be accepted, or require the one made using a gold chest.  After all of the effort that's put into making the rocket, adding the cargo space is a trivial cost.

**Comment by Dream-Master** [comment]
The problem is  i can set only one rocket for the goal. Maybe i could add a upgrade or downgrade for rockets with cargo containers make it more easy.

**Comment by Dream-Master** [comment]
@ddejong42 i added a way you can downgrade your rocket to a normal oneto finish your quest and add a golden chest to get your rocket back (with enough slots)
