### ISSUE TITLE
Improving loading time

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1897]
If the forge splash screen is disabled the game takes 6min to start instead of 8min (tried 2 times)

What it does is removing the loading bars/screen instead it shows the good old mojang logo
To disable set the eneabled to false in splash.properties in the config folder

This can of course vary on different machines but maybe it opens some space for new mods? :P

**Comment by Dream-Master** [comment]
could be.

**Comment by Methes** [comment]
New mods mean not only increased loading time (minor) but also more instability and unwated interferences (major). Helping people startup faster is, however, awesome find. Thanks.

**Comment by Radst0ne** [comment]
speaking of performance:
using this startup in the java/launcher option boost the fps by a bit:

-XX:MaxPermSize=256m -XX:PermSize=128M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
-client -d64

MaxPermsize according to the ftb forum helps with worlds that are memory leaking (happens some time on my server)
-client somehow optimizes the game (not sure how and why)
-d64 forces minecraft to use 64bit, makes it more stable but needs at least 4gb of ram allocated
-XX:-UseAdaptiveSizePolicy affect the memory allocation (garbagecollector)
-XX:+UseConcMarkSweepGC makes minecraft less cpu intense through optimizing memory use
-XX:+CMSIncrementalMode optimizes -XX:+UseConcMarkSweepGC and again cpu usage

Im not 100% sure if all the info is correct but it helps my average fps and get a gain of about 10-20fps
and a max fps of about 170 which I had never before (tested in a same world, randomly walking)

**Comment by richardhendricks** [comment]
Concern would be players getting nervous staring at an unchanging screen for 5+ minutes. Or does it change?

**Comment by Dream-Master** [comment]
Yes I change it. Will see if people complain or not. But reduce loading time us always good.

**Comment by Radst0ne** [comment]
@richardhendricks nope its just like the vanilla launch just longer :P
@dream-master you can add a costume loading screen that says please be patience :P that would help

**Comment by MineAnPlay** [comment]
The only problem for this is that the forge splash screen has another use. It keeps minecraft active while it's loading. If the RAM usage gets near max it will start to lag and could freeze without doing anything till RAM gets lower. So I wouldn't recommend making this default but display it some where were everyone can see it so they can try it and if they don't have problems they could keep it.

**Comment by Radst0ne** [comment]
@mineanplay that isnt quite correct, the splash screen got introduced with forge 1.7.10 and just simply show whats forge doing while its loading because of concerns that @richardhendriks spoke about. Through the animation it can happen that it can stuck (most likely because of optifine (forced vsyn etc.)  till the newest 1.7.10 forge release it should be fixed but can sometimes occur) its more likely that it has more problems with the loading screen(get stuck for fw secs  etc.) than without the splash screen (its just a placeholder). Disabling it doesnt mean it changes the behavior of forge loading mods

**Comment by Dream-Master** [comment]
It works fine only show mojang logo
