### ISSUE TITLE
Reducing TConstruct and GregTech divergence

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#190]
As we know there is a clash of ideas between those two mods. Other than a viable solution for the aluminum/aluminium conflict, I suggest looking closer at the use of bronze and iron for tools in those mods.

[Historically Iron is a harder metal than bronze.](http://gaming.stackexchange.com/a/8014) This is true in GregTech where Iron tools have more durability than their bronze counterparts. In TConstruct however, bronze seems to be all-round better than Iron with better mining speed and higher mining level.

The progression of the two metals could be simply swapped for TConstruct for realism and  consistency with GT.

**Comment by Namikon** [comment]
Is it that easy to change harvest levels of tools? If so, then I second teteros suggestion

**Comment by Dream-Master** [comment]
Harvest level I can change but not the intern tico Tier.

**Comment by Dream-Master** [comment]
What i can do here?

**Comment by Dream-Master** [comment]
Cant cange here any things. If they do we have to open an new Issue for it.
