### ISSUE TITLE
[Quest] Update Antimony quest to point to Twilight Forest/fetching lead

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1902]
#### Which modpack version are you using?
1.5.1.1

Currently Antimony quest talks about building batteries, but player is gated behind fetching lead/galena/silver from twilight forest in Novice Thaumaturge tab. Add a sentence to Antimony quest to point player to Twilight Forest and prospecting for lead.

**Comment by Dream-Master** [comment]
Ok will do.

**Comment by richardhendricks** [comment]
I noticed that the lead dust quest does mention the Twilight Forest, so maybe instead of updating the Antimony quest, the "A lead about lead that leads to lead dust" quest should have requirements changes to not need the "Lead, Galena and Silver" quest.
