### ISSUE TITLE
Missing Changelogs on Curse

### ISSUE THREAD

**Issue by TechnicianLP** [GTNewHorizons/NewHorizons#1905]
Most (if not all?) versions of your modpack on curse are missing a changelog (ie [1.5.1.1](https://minecraft.curseforge.com/projects/gt-new-horizons/files/2466454))

**Comment by Dream-Master** [comment]
Oh ok will add soon.

**Comment by Dream-Master** [comment]
1.5.x.x done and 1.4.1.1
