### ISSUE TITLE
Methanol recipies missing carbon monoxide

### ISSUE THREAD

**Issue by wingez** [GTNewHorizons/NewHorizons#1907]
![image](https://user-images.githubusercontent.com/12143465/29939725-1f66a836-8e8d-11e7-97ba-11be2552fe84.png)

All recipies for making methanol out of hydrogen and CO with CO in the fluid slot in the chemical reactor seems to be missing the CO. 
This bug prevents moderatly-hydrocracking of all oil products because the configcircuit is the same
[1.5.1.1]

**Comment by Dream-Master** [comment]
@JohannesGaessler did I do here a mistake in GTNH or is this an issue?

**Comment by JohannesGaessler** [comment]
@wingez Presumably the recipe you're showing is 6 Hydrogen Cells + 1000 CO2 -> 1000 Methanol + 3 Empty Cells. 
Are you sure that the Fluid Input is indeed empty and not CO2?
Galacticraft gives CO2 a fully transparent texture, so perhaps you missed it.
Also, did you confirm that the hydro-cracking recipes are indeed not working?

**Comment by wingez** [comment]
@JohannesGaessler Yes its empty.


The recipe in the image is 3hydrogen + circuit 2 -> methanol
What i tried to do in my world was propane(fluid) + 3hydrogen + circuit 2 -> hydrocracked propane but it only produced methanol. 
I guess that the cracking recepies are still there but the methanol one takes priority since they have the same item inputs

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/29962028-de40254c-8f01-11e7-9a57-0ef890ddc98c.png)
