### ISSUE TITLE
Food inconsistency: Cantaloupe

### ISSUE THREAD

**Issue by PaladinOne** [GTNewHorizons/NewHorizons#191]
All basic food items (picked from trees or grown as crops) have a food value of 1 Fullness, 0.2 Saturation. Except Cantaloupes. Cantaloupes have twice that value, 2 Fullness 0.4 Saturation. This seems a bit odd, as there is nothing else special about cantaloupes.

**Comment by Dream-Master** [comment]
I dont know how i can change food values? So maybe cantaloupes are extra tasty ;-)

**Comment by Teteros** [comment]
This includes easy to make GT foods such as French fries or potatoes on a stick. They provide much more satiety/fullness for their effort than equivalent harvestcraft foods using same ingredients.

Also, would be nice if harvest craft chillies could be ground to chilly powder using GT mortars as crushing chilies isn't a macerator worthy task.

**Comment by Dream-Master** [comment]
Cantaloupe give one hunger bar back. So i think it isn't a big deal. Changing Food make it more realistic we need machines that have nine Input slots like the mixer with only 4. Blood asp want to make new Assembler with many input slots. maybe this one solve all us problems with food.
Adding all Food recipes back need many Day so i make this later when all other important stuff is done.
