### ISSUE TITLE
[1.5.1.2] Balance issues with re-enabled biogas recipes

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1911]
In 1.5.1.2 several old recipes were re-enabled, but I think they break the balance of the new processes for 1.5. This is particularly true for Biomass to Biogas. 

Example, Re-enabled recipe:
1000 Biomass -> 32,000 Biogas in Distillery
1,280,000 EU minus 640,000 for processing
net is 640,000 EU

1.5 New Recipe:
Fermenter -> Fermented Biomass -> Distillery
1000 Biomass -> 1,000 Fermented Biomass -> 1,800 Biogas in Distillery
72,000 EU minus 15,800 for processing
net is 56,200 EU

So re-enabled recipe is over 11 times better for biogas, and requires only one machine instead of two. It is not balanced, no one will produce ethanol for fuel or use fermented biomass if this recipe is available.

I suggest that the IC2 biogas to biogas distillery recipe (1 biomass to 32 biogas)  be disabled.

**Comment by AlphaApotheosis** [comment]
Also could reduce efficiency of IC2 biogas recipe

**Comment by SirAzazel** [comment]
Id say could do like:
1000 Biomass  (distillery)--> 16000 Biogas
32'000EU processing cost (640'000EU/608'000EU clean) 

1000 Biomass (fermenter)--> 1000 Fermented Biomass (distillery)--> 24000 Biogas
200'000EU processing cost (960'000EU/760'000EU clean)

Which returns that fermenting is 125% efficiency over straight distillery.

**Comment by Dream-Master** [comment]
@AlphaApotheosis Ic2 recipes i guess i cant change its hardcoded.

**Comment by AlphaApotheosis** [comment]
Maybe just remove the IC2 biogas distillery recipe then?

**Comment by Radst0ne** [comment]
I would also remove it since you cant get Biogas out of Biomass, since it needs to ferment to produce methan/biogas

Theoratically you cant even produce methane out of biomass you just get biogas and then you have to distill it
Biogas consist out of 50-60% methane, 35-45%Co2 and some other gases

**Comment by Dream-Master** [comment]
again @AlphaApotheosis Ic2 recipes i  cant change its hardcoded.

**Comment by Dream-Master** [comment]
Now its possible to get Biogas out of Biomass 10=16mb 320 EU
![image](https://user-images.githubusercontent.com/2970688/30034588-9a4c3670-91a2-11e7-8096-255739ee5735.png)

**Comment by Radst0ne** [comment]
![2017-09-04_19 01 51](https://user-images.githubusercontent.com/27621272/30034709-8eb941ee-91a3-11e7-96a5-2031513bfa16.png)

so you already changed something :P

**Comment by Dream-Master** [comment]
@Radst0ne but suggested is this
1000 Biomass (distillery)--> 16000 Biogas
and this
1000 Biomass (fermenter)--> 1000 Fermented Biomass (distillery)--> 24000 Biogas

**Comment by Dream-Master** [comment]
so 10=160 
and 10=240

**Comment by AlphaApotheosis** [comment]
I am confused, if you cannot change the IC2 (1 biomass to 32 biogas) recipe, then why was it missing from 1.5.1.1? It was added in 1.5.1.2. 

Also, @Radst0ne, those numbers seem way too high. The problem with the 1 biomass to 32 biogas recipe is that is produces way too much compared to other uses of biomass, in particular biomass > fermented biomass > biogas, but also compared to distillation of fermented biomass, and production of ethanol. Basically I think the IC2 (1 biomass to 32 biogas) recipe should not be in at all if it cannot be changed considerably.

**Comment by AlphaApotheosis** [comment]
I think the numbers for biogas were very well balanced with just the biomass > fermented biomass >biogas recipe.

**Comment by Dream-Master** [comment]
@AlphaApotheosis The ic2 recipe in the ic2 machine i cant change it is hardcoded.
The recipes in gt machines i can chnage but i have to look for some values. No it is imbalanced too

The multiblocks recipe need more eu in hv as the sinple distillery recipes (the fermented one)

Any suggestions, values ?

**Comment by Dream-Master** [comment]
@AlphaApotheosis rember old recipes?

**Comment by Dream-Master** [comment]
Make methan is much better now.

![image](https://user-images.githubusercontent.com/2970688/30035161-4e684fb4-91a7-11e7-869b-1275bf1cb5ad.png)
Burnvalue 104000 EU per cell Biogas 40000

**Comment by AlphaApotheosis** [comment]
True, but the methane single block distillery recipe is 1000 Biomass to 600 Methane, 
So 62,400 EU

Biomass > Fermented Biomass > Biogas is 1000 Biomass to 1800 Biogas
So 72,000 EU

Seems pretty balanced.

The new GT distillery recipe (1 Biomass to 32 Biomass) is 1000 Biogas to 32,000 Biogas
So 1,280,000 EU

![image](https://user-images.githubusercontent.com/30811906/30035234-f871a82a-9175-11e7-899b-49f6a9d82b8d.png)

This is the one that needs to be changed for balance, reduced to I think 10 biomass to 16 biogas for 8 EU/t for 1 sec.

**Comment by Dream-Master** [comment]
This was the old one "The new GT distillery recipe (1 Biomass to 32 Biomass) is 1000 Biogas to 32,000 Biogas
So 1,280,000 EU"

**Comment by Radst0ne** [comment]
@AlphaApotheosis @Dream-Master I dont think it is pretty balanced since methane should be more worth than just biogas, since biogas is something like a scrap product and it makes, for me, gameplay wise more sense to enoble my products/ get greater output using some more machines

**Comment by AlphaApotheosis** [comment]
@Dream-Master Right, it was the old recipe, but now we have the fermented biomass recipes, and I think the old recipe produced way too much anyway. Why would anyone produce ethanol for fuel or go the new fermented biomass route if this recipe is available? It is too much of an obvious choice.

**Comment by AlphaApotheosis** [comment]
@Radst0ne I mean it is balanced in the sense that neither option is much more powerful than the other, and the choice can largely be up to the player. And in fact, if you go the methane route, it only produces less if you are using the single block distillery. If you are using the distillation tower, you get several other fuels making it a much better option if you can figure out how to use all of them.

**Comment by Dream-Master** [comment]
Would be more easy disable ic2 Fermenter and let the values like it is @AlphaApotheosis @Radst0ne

**Comment by AlphaApotheosis** [comment]
Yeah, not really a fan of the ic2 fermenter anyway, particularly if we cannot change the recipes. It should be entirely replaced by the GT fermenter.
