### ISSUE TITLE
Rainbow Curry Recipe Bug

### ISSUE THREAD

**Issue by TechnicianLP** [GTNewHorizons/NewHorizons#1912]
The recipe is ~~very annoying~~ voiding any excess bowl provided - (if eg. 5 empty bowls are provded, they are counted as 1 and consumed)

**Comment by Dream-Master** [comment]
rainbow curry recipes is op anyways. Food recipes need to changed.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30034419-86c17364-91a1-11e7-85b3-53b60ab555f5.png)
worked with reuse tested one stack.
