### ISSUE TITLE
Fueled jetpack quest

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1913]
#### Which modpack version are you using?
1.5.11

First stage quest asks 30k Coolant cell, but fueled jetpack need 60k cell for craft. And I can't close first stage of the quest because it ask <IC2:reactorCoolantTriple:1>.withTag({}), and i can craft only <IC2:reactorCoolantTriple:1>. Don't take item from nei when fix this quest because tag.

**Comment by Dream-Master** [comment]
I have to options. I can add ignore nbt or remove nbt tags.

**Comment by SirAzazel** [comment]
Better remove tag since its empty anyway
