### ISSUE TITLE
Bee breeding not producing a princess

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1915]
#### What did you try to do, and what did you expect to happen?
I was breeding tropic bees in a apiary for roughly 130 generations (did not analyze the bee since didnt expect the issue). When the queen died off this time around I got no princess only drones. To my understanding this is never supposed to happen in the normal bee mod. It also happened once with a wintry bee.  I am not sure if this is a GT change or a bug.

If there is a change for GT is there a way to revert that one somewhere?

#### What do you suggest instead/what changes do you propose?

If this is intentional I don't think it helps the mod be more interesting. Bee's are a pain enough to breed without having to worry that all your work is destroyed for no discernible reason.

**Comment by Drobac** [comment]
Your princess was probably an Ignoble one and not a pristine one. Ignobles have a chance of dying every time they brees
