### ISSUE TITLE
[1.5.1.2] Magic Converters doesn't accept GregTech Void Ingots

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#1916]
#### Which modpack version are you using?
1.5.1.2

#### What did you try to do, and what did you expect to happen?
I tried feeding novice magic energy converter GregTech Void Ingot 
http://i.imgur.com/qJwTM7U.png

After feeding it the ingot it should've converted to EU

#### What happend instead? (Attach screenshots if needed)
Magic Converter doesn't accept the ingot

#### What do you suggest instead/what changes do you propose?

Right now GregTech void ingot gets converted to thaumcraft void ingot when you put it into your inventory or the world. But if you use automation and ingot is not going to world, it does not get converted.

I would like to be able to put GregTech Void Ingot to Magic Converters, or change Void Ingot receipt to Thaumcraft, not GregTech one.

**Comment by Dream-Master** [comment]
So far I know gt void ingots works too.

**Comment by DeForce** [comment]
No, they do not work, only after they get converted.

**Comment by Dream-Master** [comment]
Ok will add

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30033873-5c18c7fa-919e-11e7-8334-32f94e2577d6.png)
![image](https://user-images.githubusercontent.com/2970688/30033881-61918c94-919e-11e7-90df-fb239cebc8de.png)

**Comment by Dream-Master** [comment]
@DeForce Please try again

**Comment by Dream-Master** [comment]
Will add a recipe for gt version.

**Comment by Dream-Master** [comment]
Not been displayed if i add the recipes or not so i guess it using the Thaumcraft allready.

**Comment by DeForce** [comment]
Here is the issue I'm facing, hopefully you will understand now:
https://www.youtube.com/watch?v=TPzEQB70xTQ

**Comment by Dream-Master** [comment]
Why the not convert. I guess something wrong?

**Comment by DeForce** [comment]
Because they do not leave the inventory.

If they are in world or in player inventory it converts.
Items do not convert if they do not leave inventory

**Comment by Dream-Master** [comment]
i try to add a burnvalue but i cant its not displayed.

**Comment by Dream-Master** [comment]
i fixed the recipes how you can make void ingots to thaumcraft ingots.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30037502-a5fe951c-91bb-11e7-9b0e-d6f61f9e9c38.png)
