### ISSUE TITLE
1.5.1.2 Advanced Alchemical Furnace bugged

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1918]
#### Which modpack version are you using?
1.5.1.2
#### If in multiplayer; On which server does this happen? 
Multiplayer private server
#### What did you try to do, and what did you expect to happen?
The furnace is not outputing any essentia into the alembic that is just above it and all the essentia is stuck inside the furnace.

https://github.com/Modbder/ThaumicBases/issues/23

**Comment by DeForce** [comment]
There is a workaround. Make sure you put fuel by hand, and then insert essentia itemsby hand after.
Try that couple times. Known "bug"

**Comment by Dream-Master** [comment]
I guess no one will fix this anymore.
