### ISSUE TITLE
1.5.1.1 Typo in Quest "Pollution what....?"

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#1920]
#### What do you suggest instead/what changes do you propose?

In the below image, the quest references the bronze blast furnace, which is depreciated. It should be bricked blast furnace.
![image](https://user-images.githubusercontent.com/30208401/30044269-2d25a27a-91ca-11e7-8eec-9745deec31f6.png)

**Comment by Dream-Master** [comment]
Ok will Change.
