### ISSUE TITLE
[1.5.1.2] Industrial Sifter does not respect chances

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#1921]
#### Which modpack version are you using?
1.5.1.2
#### If in multiplayer; On which server does this happen? 
Private Server

#### What did you try to do, and what did you expect to happen?
I have put 100 Purified Ruby Ore into the Industrial Sifter and expected about 3 Exquisite Ruby (Given the 3% Chance), maybe 6, if the chance is doubled in this machine.
![image](https://user-images.githubusercontent.com/7394420/30055561-84fc241a-9238-11e7-9dca-d184e88debe7.png)

#### What happend instead? (Attach screenshots if needed)
I got 100 Exquisite Ruby
![image](https://user-images.githubusercontent.com/7394420/30055541-78bd2a96-9238-11e7-8582-ade7382b6cc1.png)

#### What do you suggest instead/what changes do you propose?
Disable Industrial Sifter or fix percentages

**Comment by DeForce** [comment]
By the way its not only Exquisite, others are also strange. Just this one is 100%

Others are
T0 - 70%
T1 - 30%
T2 - 30%
T3 - 70%
T4 - 30%

**Comment by Dream-Master** [comment]
@draknyte1 any idea?

**Comment by draknyte1** [comment]
Chances below 60% are boosted by 10-12%. Shouldn't be 100% or even close to.

**Comment by DeForce** [comment]
I have created the PR to GT++ to fix this issue:
https://github.com/draknyte1/GTplusplus/pull/129

**Comment by Dream-Master** [comment]
@DeForce did the fix working with no issues ?
