### ISSUE TITLE
[Quest] Super Tank I

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#1922]
#### Which modpack version are you using?
1.5.1.1

Super Tank 1 quest is in MV tier, but it requires PTFE pipe.  PTFE requires TetraFlouroEthylene, which requires 256 volts at chemical reactor.

**Comment by Dream-Master** [comment]
Ok so i need to change it.

**Comment by ko5h** [comment]
@richardhendricks look at recipe in assembler 
https://i.imgur.com/mYxB6tI.png 
https://i.imgur.com/2gvZzbw.png

**Comment by richardhendricks** [comment]
Well, the assembler recipe should use the same fluid pipe as the self-crafting recipe. So I guess the self-crafting recipe needs to use steel pipes?

**Comment by richardhendricks** [comment]
I mean, on some devices they do require something different in the assembler recipe, but usually it is a similar item, ie foil instead of wires or whatever.

**Comment by ko5h** [comment]
I suggest removing shaped recipe

**Comment by richardhendricks** [comment]
I am OK with that.

**Comment by Dream-Master** [comment]
No i guess i make a mistake here will check it.

**Comment by Dream-Master** [comment]
A few recipes are inconsistent so i will cgange them too.
