### ISSUE TITLE
Nitric Oxide Quest

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1923]
#### Which modpack version are you using?
1.5.1.2

Second first stage of quest ask for 12 ammonia cell and 24 Oxygen cell, but ratio 1:2.5, so we need 30 oxygen cells on first stage to make 12 nitric oxide on second stage.

**Comment by Dream-Master** [comment]
ok need to change it.

**Comment by Usernm0** [comment]
On next quest Nitric Acid, we need 24 nitrogen dioxide cell, not 12.

**Comment by Dream-Master** [comment]
yea i guess therea are more quest that not match anymore after code changes.

**Comment by Usernm0** [comment]
Yes, Next problem in Dimethylamine quest. Ammonia to methanol ratio is 1:2, but quest ask 2 cell with ammonia and 2 cell with Methanol.

**Comment by Dream-Master** [comment]
Nitric acid have two recipe variants.

But 12 water cells 12 oxy cells and 24 Nitrogen Dioxide cells make 24 Nitric acid cells. @Usernm0

**Comment by Usernm0** [comment]
Look again, Nitrogen Dioxide quest #853 ask to craft 12 nitrogen dioxide cells. And next quest Nitric Acid #851 ask 24 nitrogen dioxide cells on first stage. I finish first quest and haven't materials to do first stage of next quest.

**Comment by Dream-Master** [comment]
ah ok
