### ISSUE TITLE
Thermionic fabricator use wrong items in recipes

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#1924]
#### Which modpack version are you using?
1.5.12
#### If in multiplayer; On which server does this happen? 
Private server
#### What did you try to do, and what did you expect to happen?
I set diode recipe in thermionic fabricator with fine annealed copper wire and put regular fine copper wire in thermionic fabricator items slots. Craft shouldn't start.
#### What happend instead? (Attach screenshots if needed)
Thermionic farbricator just craft 8 diodes with regular fine copper wire. 
#### What do you suggest instead/what changes do you propose?
I think thermionic fabricator can't use nbt tags. I don't know what do with it.

**Comment by Dream-Master** [comment]
Annelead is not a nbt tag it is a different material like gold and silver

**Comment by ko5h** [comment]
confirm...and craft resistor in TF too problem

**Comment by Dream-Master** [comment]
Maybe ingredients to similar ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30133629-da9e9f0c-9354-11e7-88e4-1806f69f93eb.png)
I tested all 4 recipes it works
![image](https://user-images.githubusercontent.com/2970688/30133639-e209e09e-9354-11e7-9fdb-6acbe207e3b6.png)

**Comment by Dream-Master** [comment]
Same for resistors all recipes works
![image](https://user-images.githubusercontent.com/2970688/30133783-5ab31984-9355-11e7-9ac9-a5031fd00d55.png)

wire/fine wire are all copper or all annealead.

**Comment by aLegoz** [comment]
https://clips.twitch.tv/SneakyLivelyElkDAESuppy @Dream-Master

**Comment by Usernm0** [comment]
To reproduce set diode recipe in thermionic fabricator with fine annealed copper wire, and the put regular fine copper wire (not annealed) in thermionic fabricator items slots.

**Comment by Dream-Master** [comment]
So far I know you can make only one recipe you set before.

**Comment by DeForce** [comment]
@Dream-Master I see that copper cable and annealed copper cable share the same Ore Dictionary copperWire. Maybe something because of that?

**Comment by Dream-Master** [comment]
ok will change it you can use anycopper so it not matter what copper you are using.

**Comment by Dream-Master** [comment]
I change it anealead copper
