### ISSUE TITLE
Quest "Good integrated Circuits #793" And "Advanced Circuits #838"

### ISSUE THREAD

**Issue by aLegoz** [GTNewHorizons/NewHorizons#1925]
#### Which modpack version are you using?
1.5.1.2
![123](https://i.imgur.com/66MJShM.png)
![213](https://i.imgur.com/du7uWb3.png)

**Comment by aLegoz** [comment]
![image](https://user-images.githubusercontent.com/10736349/30132894-9fd8b500-935a-11e7-82b7-872cbee23edd.png)
![image](https://user-images.githubusercontent.com/10736349/30132915-b0bd1aa0-935a-11e7-97ab-5c564d014c39.png)

**Comment by Dream-Master** [comment]
Sadly the wrong Quest file was uploaded. Here the newest one.

https://github.com/GTNewHorizons/NewHorizons/blob/master/config/betterquesting/DefaultQuests.json

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30133927-c17a8af8-9355-11e7-9a94-e229971ead8e.png)
![image](https://user-images.githubusercontent.com/2970688/30133931-c6975d54-9355-11e7-96a2-6d6cf4f8492d.png)
