### ISSUE TITLE
EBF not output fluid

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1927]
(ver 1.5.1.1. Singleplayer.)
EBF recipe: pyrite dust + oxygen = banded iron dust + sulfur dioxide.
Sulfur dioxide not appeared in output hatch.

**Comment by Bluebine** [comment]
It works fine for me. Make sure the output hatch is on the TOP of the blast furnace and not the bottom, saw another guy with this problem.

**Comment by Proha5** [comment]
EBF description says that output hatch should put in bottom layer.
Ok. I tried place hatch on top layer. Now sulfur dioxide appear. But output amount = 880L instead 2000L. I understood. My muffler have "recovery CO2 = 44%". 880 is 44% of 2000. Max muffler recovers = 78%. No any way to get 100%?

**Comment by Dream-Master** [comment]
@Bluebine @Proha5 maybe the description is wrong here.

**Comment by Dream-Master** [comment]
As the tool tips says max 78% @Proha5

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30244361-b932c45a-95bc-11e7-826b-14ad4ce47edc.png)
