### ISSUE TITLE
[1.5.1.2] Double recipe from wooden slab

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1928]
#### Which modpack version are you using?
1.5.1.2
#### If in multiplayer; On which server does this happen? 
private serv
#### What did you try to do, and what did you expect to happen?
Put oak wooden slab in cutting and got cover...i need pressure plate
#### What happend instead? (Attach screenshots if needed)
https://i.imgur.com/caxkvcR.png
https://i.imgur.com/ZtyOZCu.png
#### What do you suggest instead/what changes do you propose?
can be share recipes into assembler and cutting?

**Comment by Dream-Master** [comment]
Yes need fix this recipe.
