### ISSUE TITLE
[1.5.1.2] GT++ Advanced Boilers seriously unbalanced

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1929]
![image](https://user-images.githubusercontent.com/30811906/30182112-abeac278-93e3-11e7-9b7d-a6a6b368af9c.png)

The GT++ advanced boilers (LV, MV, HV) generate way too much steam. The screenshot is the steam generated by the HV advanced boiler with 32 lignite. For reference, the steam generated by the tungstensteel large boiler (much more expensive) is close to 1,000,000mB. 

In addition, these boilers can take fuels GT boilers cannot (i.e. BOP ash), which makes them quite powerful.

Suggestion is they be disabled.

**Comment by Dream-Master** [comment]
Any idea here? @draknyte1

**Comment by AlphaApotheosis** [comment]
To clarify they might generate steam at the rate stated on the tooltip, but the problem is that the fuel efficiency for all three is too high, many times higher than the best GT boilers. And I think GT boilers should not be able to use diamonds and BOP ash as fuel.

**Comment by draknyte1** [comment]
They can burn anything with a fuel value and are very efficient as they don't waste fuel during run time.

**Comment by AlphaApotheosis** [comment]
Ok, they are highly efficient. I am saying that they are not balanced with the preexisting GT boilers on the basis of efficiency, even multiblocks that are much more expensive. 

GT++ is supposed to be a Gregtech pack, why would you add machines that are many times better than existing machines at an earlier tech level and cheaper price?

**Comment by AlphaApotheosis** [comment]
Ok, they are highly efficient. I am saying that they are not balanced with the preexisting GT boilers on the basis of efficiency, even multiblocks that are much more expensive. 

GT++ is supposed to be a Gregtech pack, why would you add machines that are many times better than existing machines at an earlier tech level and cheaper price?

**Comment by Dream-Master** [comment]
We can change the recipe for gtnh pack. @AlphaApotheosis Any recipe suggestions?

**Comment by OneEyeMaker** [comment]
@Dream-Master @draknyte1 
That's better to tweak output amounts of boilers (and fuel consumption).

**Comment by draknyte1** [comment]
Their efficiency stems from the fact that they don't continually use fuel.
As long as their heat is > 80%, they don't use fuel, so that fuel lasts far longer.

**Comment by AlphaApotheosis** [comment]
I don't think changing the recipe solves the problem. They just don't make sense in the pack. They will make all other steam sources redundant, no matter how expensive.

**Comment by AlphaApotheosis** [comment]
If they stay in the pack, they should be less efficient than the tungstensteel multiblock boiler at least. And they should not be able to use fuels the multiblock boilers cannot.

**Comment by draknyte1** [comment]
Not my fault gregtech boilers aren't coded to use any fuels.

**Comment by AlphaApotheosis** [comment]
@draknyte1 no one is saying anything is your fault, we are just assessing whether the capabilities of the boilers are balanced with the GT boilers that have been in for years and are already integrated and balanced with other power sources.

**Comment by Dream-Master** [comment]
@draknyte1 if you not change the rate for Gt++ or for only GTNH @AlphaApotheosis what recipe you suggest and tier?

**Comment by AlphaApotheosis** [comment]
I think they should be disabled. There is no way to balance them with recipes the way they are.

**Comment by draknyte1** [comment]
Yeah, but their steam generated per tick is horrible in comparison to large boilers.
So while you might make 750 steam/tick for a lot longer, when you want steam you want it in large quantities, so large boilers still work out better.

It doesn't upset balance, as far as I am concerned. Unless someone decides to make 20 of these, a large bronze boiler will still produce more/t. As anything within Gregtech, increase speed, lose efficiency.

**Comment by AlphaApotheosis** [comment]
Maybe I am not being clear, I will give an example. Here is the total steam production using one charcoal, starting at max heat, for all the steam boilers currently available in the pack:

Small Coal Boiler: **43,200**mB
High Pressure Coal Boiler: **48,000**mB
Railcraft multiblock boiler: **20,000** to **35,000**mB depending on size
Large Bronze Boiler: **32,000**mB
Large Tungstensteel Boiler: **48,000**mB

The GT++ boilers: more than **500,000**mB

It's just not in the scope. 

From the high pressure coal boiler to the GT++ LV boiler is at least a 10x increase in efficiency. For reference, between the large bronze and the large tungstensteel boiler, between 5 tech levels, is only a 2x increase in efficiency, and even then it only reaches the level of the high pressure coal boiler.

**Comment by Dream-Master** [comment]
@draknyte1 are you able to give us a config option for GTNH we can adjust the output rate?

**Comment by Dream-Master** [comment]
@draknyte1 any news here?

**Comment by Dream-Master** [comment]
@Technus can you add a config option for us make the Boiler a bit more balance in GTNH?

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GTplusplus/commit/d5dc97657a6776ca847c089d6da50ea649209b59
