### ISSUE TITLE
[1.5.1.2] dupe thaumic horizons

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1930]
#### Which modpack version are you using?
1.5.1.2
#### If in multiplayer; On which server does this happen? 
privat serv
#### What did you try to do, and what did you expect to happen?
use wand focus liquefaction on copper dust...and sure got copper ingot (1dust=1ingot)
#### What happend instead? (Attach screenshots if needed)
but after using focus, the smelting recipe for all players on the server has become = https://i.imgur.com/gV0u7wD.png
#### What do you suggest instead/what changes do you propose?
dont know...remove this focus

**Comment by ko5h** [comment]
tested in sp
confirm https://i.imgur.com/Gqrk9uc.png
but after uses of the focus in world on different blocks, melting a copper in the furnace gave an ingot ... if it is thrown away, it will disappear
https://i.imgur.com/inPWi5z.png
https://i.imgur.com/t1JT6Kn.png
do not take this ingot shift+lc... but if drag in inventory i can craft other item

**Comment by Dream-Master** [comment]
so ghost items ? @ko5h

**Comment by ko5h** [comment]
@Dream-Master yes, but it does not appear immediately

**Comment by Dream-Master** [comment]
Not sure what i can do.

**Comment by Dream-Master** [comment]
Not fixed. No one take care of it.
