### ISSUE TITLE
Buildcraft Robots Activation possible?

### ISSUE THREAD

**Issue by smerk84** [GTNewHorizons/NewHorizons#1932]
#### Which modpack version are you using?
1.5.1.2

Is it possible to activate the Builcraft robots in this pack? Of course with hard recipes.
For me (and maybe others) it was nice to have them in this pack.

Surely there are robots from opencomputers, but for them i need to learn programming, which i dont want to learn ;)

I hope everyone understands my english :)

Thanks

**Comment by Radst0ne** [comment]
Would like that too
but if possible disable the pump,miner,knight and maybe the builder

**Comment by Dream-Master** [comment]
Pump and quarry are disabled. Kight?

**Comment by Radst0ne** [comment]
I meant the robots
there 17types of them
http://minecraftbuildcraft.wikia.com/wiki/Robots

**Comment by Dream-Master** [comment]
sadly i can only make recipes that is shaped because robotics is not supported via minetweaker.
What tier robots have to be HV ?

**Comment by Radst0ne** [comment]
Blocks/Items that are needed:
assembly table (change to a lower tier circuit)
integration table
programming table
redstone board
docking station
laser (change to a lower tier circuit)
charging table
zone planner
the robot itself
map location
requester
buildcraft wrench

**Comment by Dream-Master** [comment]
@Radst0ne  BC Pipes are craftable

**Comment by Radst0ne** [comment]
I mean the item transport pipes, they are also needed

**Comment by Dream-Master** [comment]
are no other pipes work like Ender io or extra utilities @Radst0ne ?

**Comment by Radst0ne** [comment]
sadly no because the docking station needs to be connected to a bc pipe to put items in chests etc.

**Comment by Radst0ne** [comment]
yes only wooden pipes are needed if you set the gate right

**Comment by Radst0ne** [comment]
@Dream-Master it is possible to blacklist some robots:
In the buildcraft main.cfg::

general {
    # Blacklisted robots boards
    S:boards.blacklist <
        buildcraft:boardRobotBomber (e.g.)

**Comment by Dream-Master** [comment]
ok will do.
