### ISSUE TITLE
Powergeneration

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#1933]
Biodiesel suggestions:
Reduce the amount of seed oil from 6 to 5
Make the Recipe more time/eu expensive, around 2mins
in return buff all seed oil recipes like the vanilla ones

Reason: Once you built up a Multiblock Distillation Tower it produces a ton of Biogas, so biodiesel gets more useless/unimportant

Biogas suggestions
Nerf the multiblock biomass recipe to 250mb -> 4k Biogas
(Or even more)
Reduce the time needed in the single block distillery to 0,5s

Reason: Single Block distillery to weak, multiblock too op

**Comment by AlphaApotheosis** [comment]
I think it should be nerfed more than that, to bring it into line with the 10 fermented biomass > 18 biogas recipe in the distillery.

And we still have the pyrolyse oven recipe in 1.5.1.2, no need to add:

![image](https://user-images.githubusercontent.com/30811906/30222263-a347bc6e-9494-11e7-9d25-bee8db5c15f0.png)

**Comment by Dream-Master** [comment]
I disable ic recipe btw. So the ic2 machine is not longer craftable.

**Comment by Radst0ne** [comment]
@AlphaApotheosis oops yeah sometimes my nei doesnt show all recipes to me... I gues a reinstall will fix that

**Comment by Dream-Master** [comment]
@Radst0ne  i need to talk to you about changes.

**Comment by MineAnPlay** [comment]
I will try to find more balances for these anyways. Biogas is not supposed to be a power source (it was enabled so that you could fill the IC2 Biogas jetpack). If you want power via plants early on use Methane. Will buff methane if needed and nerf biogas so that it's no longer energy efficient to produce for power.

**Comment by Radst0ne** [comment]
@mineanplay same thoughts only methan should be efficient to use

**Comment by Radst0ne** [comment]
maybe its dumb and just a unecessary effort but what about comparing the rl burnvalue with diesel (ingame) to get a better balance?
One example:
diesel 11,8kw/kg ingame (400.000eu)
biodiesel 10,2kw/kg would be (345.000eu)

**Comment by Dream-Master** [comment]
Need to be tested.
