### ISSUE TITLE
[1.5+] OpenBlock Sleeping bag

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1935]
#### Which modpack version are you using?
1.5.x.x
private serv
mini mode to solve the problem openblock sleeping bag (y-level 128) https://minecraft.curseforge.com/projects/bag-o-sleep
This mod was made after the players rage and tested all version 1.5+ on our server

p.s. tested on [thermos](https://cyberdynecc.github.io/Thermos/) and [ultramine core](https://gitlab.ultramine.ru/ultramine/ultramine_core-docs-ru/wikis/home)

**Comment by Drobac** [comment]
If that fixes the problems with the sleeping bag, put it straight in

**Comment by Dream-Master** [comment]
Will do.
