### ISSUE TITLE
[1.5.1.2]Raw meteoric iron

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#1936]
#### Which modpack version are you using?
1.5.1.2
add raw meteoric iron in ebf
https://i.imgur.com/Irccu4e.png

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30244001-f4faa086-95b5-11e7-9818-092f525dec3b.png)

only time is changed to 60 secs.

**Comment by MineAnPlay** [comment]
Can you add a recipe to smelt Fallen Meteor Blocks? So if one uses silk touch then can either smelt it for 1 Ingot or Blast Furnace it for 2.
furnace.addRecipe(<gregtech:gt.metaitem.01:11340>, <GalacticraftCore:tile.fallenMeteor>);

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
EBF not furnace.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30457112-83dd6ce0-99a6-11e7-8015-88928fde3ba2.png)

**Comment by MineAnPlay** [comment]
I meant add a recipe for both the EBF(which gives 2) and the furnace(which gives 1).

**Comment by Dream-Master** [comment]
No this break balances. I handle it same meteoric iron

**Comment by MineAnPlay** [comment]
Why does it break balance? Someone that goes to the moon is already quiet advanced. This makes it so that if someone has time or luck at finding meteorites he can just smelt it directly but by losing 50% efficiency.
