### ISSUE TITLE
[1.4.1.1-2.0] issue with IC² reactors

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#1937]
the setup
![2017-09-09_22 23 59](https://user-images.githubusercontent.com/12850933/30243905-874b8610-95b3-11e7-9cdb-4bb02fa01781.png)

the output as it should be
![2017-09-09_22 24 12](https://user-images.githubusercontent.com/12850933/30243907-927b07ea-95b3-11e7-8779-5d66253e88aa.png)

got three amps of 2044 EU/t
![2017-09-09_22 24 21](https://user-images.githubusercontent.com/12850933/30243904-782d1bda-95b3-11e7-971f-1476cbab26da.png)

Is it intended?
This is a quick setup i made to "increase" the efficiency of this bug: i put transvector interfaces linked to the IC² reactor (not the reactor chambers) then i put 4 IV->EV transformers on each transvector interface and then i converted the current in IV then LuV
![2017-09-09_22 45 48](https://user-images.githubusercontent.com/12850933/30243909-b312f026-95b3-11e7-8ccf-9ae16eb89397.png)

with this setup i fully charged 1 LuV battery in 200 seconds
that means the battery receives 25 600 EU/t
the reactor still output 1600 EU/t
and i put 16 transformers on the transvector interfaces
16*1600=25 600 EU/t
so there is definitly a dupe

**Comment by boubou19** [comment]
this is working also on the 2.0 version

**Comment by Dream-Master** [comment]
Will ask Aroma about it.

**Comment by Dream-Master** [comment]
Aroma explain me the problem but i guess it is a Transvector problem asking to many times about how many eu the rector outputs. So thats why the output is multiple times.

Threethings we can do 
1. remove the block
2. allow them only in a special dim
3. let like it is.

@boubou19

**Comment by boubou19** [comment]
Banning the transvector interface will nerf the glitch but it will still be possible to use it since the problem seems to be related to the ic2 reactor. In the demo I only use the transvector interfaces to have more sides to link with GT transformers. So the ic2 reactor needs to be fixed or disabled i think.

**Comment by Dream-Master** [comment]
ban ic2 reactor is not possible we need it at a special tier. Give me more example for this glitch and i can ask Aroma again.

**Comment by Dream-Master** [comment]
No on will fix this maybe in 1.12
