### ISSUE TITLE
[1.5.1.2] Advanced Nanochestplate/Jetpack recepies

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/NewHorizons#1938]
At the moment the Advanced Nanochestplate and the Advanced Jetpack form Gravi Chestplate are not craftebale or more specific: The Advanced Nano ist craftable as long as it has the specific Sub ID of 26.
The Advanced Jetpack is not craftable at all due too an unoptaniable IC² Jetpack without an Sub ID. These Recpies might have to be looked at and I would suggest if wildcard Sub IDs are not possible use fully charged Items in the recepies.

**Comment by Dream-Master** [comment]
Wildcard values can used only when i put the recipes into code. With Minetweaker and IC2 you get in trouble. Will see what i can do.

**Comment by Dream-Master** [comment]
I put this two recipes in code.

**Comment by Lainiel** [comment]
Are you sure it's fixed? It doesn't work for me.
https://puu.sh/xyXiA/2ef498ac0b.png

**Comment by Bryfer** [comment]
Apperently not fixed in 2.0.0.*

**Comment by Dream-Master** [comment]
But fixed in 2.0.0.1

**Comment by MineAnPlay** [comment]
// --- Advanced Jetpack
recipes.remove(<GraviSuite:advLappack>);

The Advanced Lappack isn't craftable and that might be why. It's named Advanced Jetpack but it's removing the Advanced Lappack recipe.

**Comment by Dream-Master** [comment]
Will check
