### ISSUE TITLE
Adjust the gathering quests to measure the processed material instead

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#194]
I suggest the gathering quests such as *Copper* and *Getting Iron* should be modified to check for the smelted/processed material for the quest fulfilment condition. (The quest *Tin* already does this by just asking for 16 tin ingots)
This is to stop forcing the player needing to find a **particular** ore in order to advance to the next quest, which may be off puting.

The *Getting iron* quest needs a stack of iron ingots and 16 *Iron Ore* as requiments for completion.
There is so many forms or iron (different colours of lignite, banded iron, pyrite, iron gravel...) and hints of this are given in above quests as well.

Encouraging the player to explore and use his new tools is good, but in most cases the end result of found materials will be the same and that should be checked instead. For example, *making bronze* forces the player to make bronze the GT way, but what if the player made bronze with the smeltery until then or vice versa? Asking for ingots in that case accounts for both ways.

**Comment by Namikon** [comment]
I think I might have changed that already, but i'm not sure.. Will check it this evening

**Comment by Dream-Master** [comment]
Is this done in the last HQM File?

**Comment by Namikon** [comment]
Not yet. I have a few things I need to check with HQM anyways, so probably this evening.

**Comment by Namikon** [comment]
Removed the need for iron ore. It's just 64 iron now. About the bronze, this is a GT pack, but you are right, there are several ways. I removed the repuration award, since tinkers would not impress "the technican". Changed as wished in the next version
