### ISSUE TITLE
MyTown Plot issues

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1940]
#### Which modpack version are you using? 
~~1.5.1.3~~ 2.0

#
#### If in multiplayer; On which server does this happen? 
Epsi

#
#### What did you try to do, and what did you expect to happen?
Tried creating town plots, they shouldve shown when you walk into them.

#
#### What happend instead? (Attach screenshots if needed)
Plots create fine, cannot be overlapped like should, but if you walk into them - doesnt say hat you are in the plot neither you can delete it.
#
![#1](https://i.imgur.com/sanTrID.png)
![#2](https://i.imgur.com/pPiHTQm.png)

#
#### Earlier today I also deleted plot on delta after 2.0 update, but it was created during 1.4.1.1.

**Comment by Dream-Master** [comment]
@Namikon need help here.

**Comment by Bryfer** [comment]
If I remember correctly you can not remove your newest claim, to do so you need to claim another chunk before removing "that" one 

Not sure if this is relevant to plots tho.


More information and quote here

https://github.com/MyEssentials/MyTown2/wiki/Commands#town-creation-and-management

`/town unclaim` with perm `mytown.cmd.assistant.unclaim` Removes the claim of the chunk you are in. It will give an error if: 
* Chunk is not already claimed. 
* Chunk contains the spawn point. 
* Chunk is the last claim in a town.

**Comment by SirAzazel** [comment]
Bryf, please re-read what i am talking about. Plots have nothing to do with claimed chunks except that they need to be inside of them.

**Comment by Bryfer** [comment]
@SirAzazel I must have missunderstood what you meant with 

> doesnt say hat you are in the plot **neither you can delete it.**

and **/town plot delete**
sorry about that

**Comment by bigbass1997** [comment]
@Bryfer Besides this issue not being about claiming chunks; when the command description says it can give an error if the chunk is the last claim in a town, that is not referring to the newest claim, but instead the final/last claimed chunk (as in there is only 1 claimed chunk in the town, you can't unclaim that, as you would then have 0 claimed chunks).

@SirAzazel The command to remove a plot is `/town plot delete` and you must be standing in the plot at the time. Do you get any error messages when you attempt this? Also, I am not sure if plots are designed to notify you when you walk into them, or maybe that is a setting/perm for the plot? Again, not sure about that part.

**Comment by SirAzazel** [comment]
As you can see on screen 2 i stand in plot with chat opened and command both in chat and already ran

Plots notify you when you walk in same as towns do.

**Comment by SirAzazel** [comment]
Referenced this as example.

**Comment by noobyaran9** [comment]
Plot is accessible only by the player who created them but not everyone in the town. Is this an intended feature?

**Comment by bigbass1997** [comment]
If you don't add any members to the plot, or change the permissions for the plot, yes that is intended. https://github.com/MyEssentials/MyTown2/wiki/Commands#plot-management

**Comment by Dream-Master** [comment]
Can this be closed?

**Comment by SirAzazel** [comment]
well basing that i didnt get any response for an issue guess can it be closed or not.

**Comment by Dream-Master** [comment]
@SirAzazel sorry i dont know much ablout MyTown. Any idea who we can ask about it?

**Comment by bigbass1997** [comment]
@SirAzazel I don't understand what the issue even is...?

**Comment by SirAzazel** [comment]
So issue is:
Plots that i created on ~~1.5.1.3~~ 2.0 cannot be deleted or changed, i can see them, but other than that they dont reacto to anything.

**Comment by Dream-Master** [comment]
@SirAzazel Did ou think an Admin or Staff member can delete those plots?

**Comment by bigbass1997** [comment]
So when deleting, you stood inside of the plot and then executed `/town plot delete`? Did you get an error message or does anything happen?

**Comment by SirAzazel** [comment]
Bass, did you read first message in this issue? There is no invisible screenshots there. Dream, plots should be possible to delete by town owner and assistants themself, and it was working before 2.0 came out.

**Comment by bigbass1997** [comment]
@SirAzazel No I read your issue just fine, maybe you didn't read what I just asked you..

You said that the plot did not provide you with a message when 

> you walk into them

You also said that you could not delete the plot. However you never said anything that answered my question.. You did not say what happens when you run the delete command while standing inside of the plot. Does nothing happen? Do you get an error message?

**Comment by SirAzazel** [comment]
look at image 2 in first message or if too lazy here is link (lazy to properly link it)
https://camo.githubusercontent.com/9c32f44e7553b7d361683a69a79b37a5fa93b425/68747470733a2f2f692e696d6775722e636f6d2f7050694854516d2e706e67

**Comment by Dream-Master** [comment]
@SirAzazel you didnt read my comment too
>Did you think an Admin or Staff member can delete those plots?
If yes i will come online later nd delete it.

@SirAzazel I am sorry but i dont have all the time to go deeper into all the mods and commands. 
I have 50+ issues that need to be fixed and the pack still not get ny new content.

**Comment by SirAzazel** [comment]
Ive had enough of sensless chatter. Ive sent all info you need to know to see that its and actual issue rather than lack of plugin knowledge, and you appear to simply ignore it or read only text. Questions you ask make no sense since they have been ancwered 10 days ago. Reopen issue if needed, but i wont provide any help from my side anymore.

**And no Dream, admins cannot delete it same way town owner or assistant cant. Only can delete it using database, but then there is no proof that it wont actually just make it invisible**

**Comment by bigbass1997** [comment]
@SirAzazel I did not see the 2nd image. But I did _read_ the words in your message. So don't dare say I didn't, and insinuating that I am lazy is not a good way to get me to help. If you are not willing to work with us anymore, then I am not willing to look into the issue anymore.

You could have simply and politely noted the answer to my question anyways, even though the image did show it, or simply noted that the image contained the answer in the bottom left corner. But you didn't.

**Comment by SirAzazel** [comment]
I see cognitive dissonanse bass: 

> I did not see the 2nd image

> But I did read the words in your message

You couldnt read all of the words if you didnt look at pictures since there is words after pictures.
I have full rights to say if someone didnt read issue if they havent looked at its attachments, and i never told you are being lazy. and yes, i shouldnt be willing to help in the first place, i give you issue you fix it. i respond to questions that need to be resolved. and first of all

**I am not polite in every meaning person and im not planning to change that.**

**Comment by SirAzazel** [comment]
![image](https://user-images.githubusercontent.com/5310658/30651717-350d75a0-9e2f-11e7-98db-69316a8117cf.png)
