### ISSUE TITLE
2.0.0.0 Advanced Circuit Quest with wrong item

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#1941]
Quest for those circuits shows a copper bolt instead of annealed copper bolt.

![2017-09-10_18 57 21](https://user-images.githubusercontent.com/27481104/30251149-5c26963a-965a-11e7-80b2-28388320f5a2.png)
![2017-09-10_18 57 35](https://user-images.githubusercontent.com/27481104/30251153-65c9f2f4-965a-11e7-939a-d426a68a43ed.png)

**Comment by Dream-Master** [comment]
ok need to change.

**Comment by MineAnPlay** [comment]
Also add a recipe for making annealed copper bolts with the extruder(since now it requires bolts not rods)

**Comment by Dream-Master** [comment]
@MineAnPlay The Annelead copper and wrough iron issue need to be open up in a new issue please.
