### ISSUE TITLE
2.0.0.0 Quest "Empty Circuit Board" does not have correct ingredients

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#1943]
The quest has you make fine tin wire, while fine copper wire is needed to make the diode. (or annealed fine copper wire)

![image](https://user-images.githubusercontent.com/30208401/30252326-634e68a0-963e-11e7-80a1-5879a35d7cfa.png)

![image](https://user-images.githubusercontent.com/30208401/30252329-7a8c1f3a-963e-11e7-8d8c-a74425dfa9c8.png)

![image](https://user-images.githubusercontent.com/30208401/30252330-88165e22-963e-11e7-8ffd-abeafd1df4e6.png)

**Comment by Dream-Master** [comment]
ok need to fix.

**Comment by Dream-Master** [comment]
@KorGgenT Your quest need an update
use
/bq_admin default load.

Why you not say me the Quest Titel is wrong?

**Comment by Methes** [comment]
This quest is just completely wrong now.
All Assembler recipes need molten Polyethylen (and not molten glass as the description suggests), and even then the numbers don't match - 4 Fine Copper Wires with Gallium dust gives you 4 Diodes not 8 (that's the case for Fine Annealed Copper Wire).
Both Thermionic Fabricator recipes need Annealed Fine Copper Wire and the one with Gallium needs 16 Wires and gives 16 diodes, not 8.

**Comment by Dream-Master** [comment]
will change this and remove therionic fabricator recipes
