### ISSUE TITLE
[2.0.0.0] Quest: 2x Steel

### ISSUE THREAD

**Issue by Budda523** [GTNewHorizons/NewHorizons#1944]
Hey,
I just finished everything for the 2x Steel Quest only to see that I can't craft the Bronze Plated Blast Furnace... It says "This furnace is deprecated use bricked blast furnace"... Well I would do that, but now I can't finish the Quest, because I need the bronze blast furnace.

Is it possible to change the Quest, so you need the bricked blast furnace for it?
Also I don't know which other quests need the bronze one. When I finished the "Time to get some steel" Quest I was still able to craft the bronze one.

**Comment by Dream-Master** [comment]
Quest allready changed use /bq_admin default load 
To update your quest.

**Comment by Budda523** [comment]
Ah ok, thank you :) 👍
