### ISSUE TITLE
[2.0] Refinery Gas to Propane

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1945]
1)There is a quest
"questID": 840,
"name": "Butane and Propane",
That suggests to get Propane out of Refinery Gas.
Refinery gas burn value = 160k.
Propane gas burn value = 232k.
But from 100 Refinery you get 7(!!!) Propane.
So to get 1 bucket of Propane you should spend 204k eu and 14 buckets of Refinery Gas (which is equal to 2.2 million eu).
So for 1 Propane bucket (232k eu) you should spend 2.4 million eu.
2)My suggestion is to gradually increase outcome. For example 100 Refinery -> 100 Propane. Or even more. Because 10 times * 3k to transform Refinery into propane = 30k. So 160k + 30k to get 232k. Not that efficient to spend time on this. 

The same is applied to Butane!

By the way in 2.0 there is no recipe that would make sense to make Butane or Propane. Any ingredients burnt without transforming to Butane/Propane will give much more energy.

**Comment by AlphaApotheosis** [comment]
It might be better to change the quest description. He is correct, refinery gas is not a good source of Propane and Butane. Better return to make butane and propane from naphtha.

**Comment by Dream-Master** [comment]
Will change quest description

**Comment by Usernm0** [comment]
Crafing solid fuel binder from lpg from propane or butane make sense.
