### ISSUE TITLE
[2.0] Biomass quests

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1946]
There are quests
1)"questID": 734,
      "name": "Way One: IC 2 Fluid Canner",
2)"questID": 735,
      "name": "Way Two: Brewery",
Both of them require 1150 Biomass Cells.
Why does it require Biomass? This questline is to show people HOW to make Biomass. If he completed all previous quests it means that now he knows how do this. And requiring for example 32 Biomass cell would be more than enough.
Because to get 1150 cells you need 2300 Tin Ingots. Very huge amounts for a quest that gives little reward.

**Comment by Dream-Master** [comment]
Please update you quest file /bq_admin default load 
I am sure I reduce it to 32 or 64 cells all ready.

**Comment by nikitinalexx** [comment]
Dream-Master, I'm playing on Epsilon and when type this command it tells me to contact administrator.

**Comment by Dream-Master** [comment]
I Check later

**Comment by Dream-Master** [comment]
Ok need to change this quest. i may forgotten it.

**Comment by SirAzazel** [comment]
1150 cells is.. 18 stacks. 2 rows of invo
surely thats WAY too much
