### ISSUE TITLE
[2.0] GT++ Tanks should be better

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1947]
GT++ tanks have some downflows.
1)They require 1 tier higher ingots than usual tanks. 
2)They store the same amount of liquid as usual tanks but require 1 tier higher ingots.
3)They are not transportable.

With all these downflows there is not much reason to craft this tanks.
So my suggestions.
1)Make them require the same tier ingots as usual transportable tanks.
2)Make them store 2x liquid compared to usual tanks.

**Comment by ko5h** [comment]
gt++ tank fill cell
imho increase their tier cost

**Comment by Dream-Master** [comment]
Gt++ tanks much more better the bc tanks.

**Comment by nikitinalexx** [comment]
@ko5h, but you can right click a usual tank with a Cell and it will also be filled. Please explain why do you think that they are much better

**Comment by Anarack** [comment]
Right clicking on a tank to fill a cell is pointless for automation, they are nice for energy less cell handling that also allow covers, so they have a niche that is filled by nothing else.
