### ISSUE TITLE
[2.0] Epsilon (Maybe Delta too) has different configs

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1948]
#### Which modpack version are you using?
2.0
#### If in multiplayer; On which server does this happen? 
Epsilon maybe Delta too
#### What did you try to do, and what did you expect to happen and what happened instead?
B:MixedOreOnlyYieldsTwoThirdsOfPureOre=false is false on clients but not on servers so even though the recipe shows it will give a ingot it gives 6 nuggets for example.
#### What do you suggest instead/what changes do you propose?
Make the server also use B:MixedOreOnlyYieldsTwoThirdsOfPureOre=false
(Also make B:forceFreeFace_true=true to B:forceFreeFace_true=false please because it's just dumb and doesn't allow cool and fancy compact designs)

**Comment by Dream-Master** [comment]
It has to be true so I will check it

**Comment by MineAnPlay** [comment]
No don't make it true, it's dumb. Make it false like it is. Using the EBF makes more output so it's better. If people want more stuff/more efficiency have it there way but don't make ore processing more tedious...

**Comment by MineAnPlay** [comment]
Also PLEASE change back Rotors using 16 Soldering Alloy not 18... (You can just use tiny piles to get that amount but for 18 you need to use bolts which is way more annoying then making tiny piles)

**Comment by Methes** [comment]
Yep. Impure piles have always given ingots when smelted and suddenly I'm getting nuggets.

**Comment by MineAnPlay** [comment]
Yes it was changed for a PR but that PR is mostly repetitive work/makes the game just boring. There is an option (which the client is set to) which makes it so the EBF/PBF actually BOOST the output but also still makes it so you can get ingots via the furnace.

**Comment by OneEyeMaker** [comment]
@MineAnPlay 
GTNH is hard modpack. 
If it's too hard for you - play something another.
Don't complain on **_reasonable changes_**.

**Comment by MineAnPlay** [comment]
What's reasonable about one recipe giving more and another giving less? The one that gave more was the original and the latter was changed later on. Right now all it does is just give less materials so you just mine more materials...

**Comment by MineAnPlay** [comment]
Also about the pack being hard. I proposed that circuit should use rods and half the amount it used to. Dream wanted bolts. I know some changes were done to make the game harder but changing the mineral/material sources to give less just makes EVERYTHING more expensive overall. If one wants more minerals/materials that person shouldn't just need to mine more ores but do extra processes to get more overall materials.

**Comment by Dream-Master** [comment]
I make use it bolts to reduce the material cost but I can change it back.

**Comment by MineAnPlay** [comment]
You don't need to change it back unless you can make it require 1 circuit per tier going up and requiring a new material appropriate for that tier. So will get some of the repetitiveness out but for now bolts should stay as is.

**Comment by Dream-Master** [comment]
New recipes wich give more circuits out in one processing step are possible too. (balanced) We using two circuits instead of blood asps 3 circuits. Maybe if you are higher in tier we can such recipes. I m open for suggestions but reduce the cost to 1 circuits i dont like much.

**Comment by SirAzazel** [comment]
so imagine size of PCB in MaxV when they progress like that. lets say LV circuit is 1x1 cm size, then MaxV circuits are 512! cm size, 512! 5 freaking meters

**Comment by SirAzazel** [comment]
1 lv + difficult ingridients --> 1 mv would be a lot more logical

**Comment by MineAnPlay** [comment]
Right now the circuits require some annoying to get stuff (which are nice not arguing about that) and cheap resources. But because they require 2 circuits per tier they can get a lot more expensive (will test the amounts when I have time)

**Comment by Dream-Master** [comment]
We can add new materials which are smaller the this fine wire, sticks and bolts. Need less ressources but more processing. I dont like some circuits recipes too but for this we need to add the components first.

**Comment by MineAnPlay** [comment]
Not smaller I meant material type that is appropriate for that tier. Like how steel is LV Aluminium is MV Stainless Steel is HV etc. Though those aren't really used in circuits so we will need to find/make new materials which will be made in time, don't rush it.

**Comment by Dream-Master** [comment]
Sure will look at your suggestions.

**Comment by Methes** [comment]
What was the intention of changing this setting?
If it's "reasonable change", there must be a valid reason to do so that takes other factors into account, such as the game economy.
Please don't just stfu caring people by sending them to play another pack, that's not productive at all.

**Comment by Dream-Master** [comment]
Magnetide is not pure iron and chalcopperite not pure copper. You get 1 ingot out of the Ore but not two when you double it with the macerator. I think the change is reasonable.
I add now pure silver to the galena mix to get more silver.
Worlds that have it need to be reseted like TF or Space dims.
@Methes And no i wont people play another pack.

**Comment by Dream-Master** [comment]
We dont change this config but i am open for a third way if anyone suggest some.

**Comment by Lainiel** [comment]
I don't really mind the decreased output of impure ores that much. What bothers me is that dealing with the nuggets is a pain in steam and LV age. There's literally no way to automate making ingots out of the nuggets in steam age and in LV age you'd need a chest buffer and you'd have to know how to correctly use it to output 9 nuggets into alloy smelter. And even if you set it up it's just really slow. It takes almost 11 minutes just to process one stack of ingots from the nuggets. What I think will happen is that a lot of people will stop macerating the ores in steam and LV age, because it's a lot of work that takes a lot of time and energy just to get 3 more extra nuggets out of the ores. And yes you can use BBF to get the a whole ingot out of the dust, but every BBF that is running with impure dusts a BBF that is not making steel which is much more important.

**Comment by MineAnPlay** [comment]
Again why? xD Yes magnetite is not pure ore but there is no PURE iron ore IRL. Easiest way to explain it is that there is enough magnetite that you get an ingot out of it but the pure iron or has less ore in it that has iron inside it so that also gives an ingot. Same logic with everything else. That config makes it so dusts give 1 ingot and EBF processing with 2 dusts give 3 ingots so you are 3x your ores. IMO that is the best one because the other one is just doing the same but giving 2/3 of it. So you just need 4/3 more ores so doesn't really add more stuff just makes you mine more. With this change an EBF is an excellent way to process ores more efficiently and actually feels like it pays for the effort because other wise you use a multiblock just to get 2x from ores.

**Comment by OneEyeMaker** [comment]
@MineAnPlay Sorry, but stop spamming. DreamMaster give you answer: he won't change this config option.
//I tired to click bell icon every time I open GitHub page.

And there is iron ore (in chalcopyrite vein, in limonite vein, ...)

**Comment by Methes** [comment]
@Dream-Master That plead for explanation was mainly directed to OneEye who clearly wants this discussion to end.

Did some research for you since I'm not sure you've done it yourself guys.
What this setting means for Steam age:
The ONLY source of pure main metals is Iron Ore from Chalcopyrite veins (and from every other Magnetite vein), Tin Ore from Cassiterite veins and Copper Ore from Chalcopyrite veins.
Both Limonites, Banded Iron, Pyrite, Magnetite, Chalcopyrite, Malachite, Cassiterite - they ALL are "impure". Those are the main sources of main metals, not the pure ones.
So. If people decide to use that Macerator they have proudly crafted, they get stuck with nuggets. They can't even compress them. They need steel for Mold (and run that through slow and costly Alloy Smelter) or they can macerate/mortar the nuggets, craft a dust and resmelt that (LOL).
Nobody will use a Macerator for regular ores until they can get electrolyzer+centrifuge up and running.

This effectively doubles the amount of ores you have to mine in Steam age/most of LV (until you have the machines and power).

So no I don't think that's a good idea of doing things.

**Comment by Dream-Master** [comment]
I have another idea. Why not chage the amount of impure lets say to 7 or 8 nuggets and the impure stay at 5-6.
BBF/EBF should have the best output.

**Comment by Dream-Master** [comment]
If nuggets is a bad idea i can output dust whih is more easy to process to ingots.

**Comment by Methes** [comment]
Nuggets are a bad idea, dust is definitely easier.
If your intention is to further nerf Steam and early/mid-LV ore processing and make it even less automatable (you'd have to manually craft regular dusts out of the tiny/small ones and then put them into furnaces) -> people will have to mine even more and spend even more time babysitting the process; yes, outputting dust is the less evil way, along with 7 or 8 dusts (or maybe 3 small piles for easier crafting).

I don't see the point in further increasing the grind and time cost of early game though, it's already bad enough.

**Comment by MineAnPlay** [comment]
Dream... Do you even read? "BBF/EBF should have the best output." That config option makes dusts give ONE ingot but BBF/EBF THREE Ingots from two dusts so overall 50% more materials. "Using the EBF makes more output so it's better." "There is an option (which the client is set to) which makes it so the EBF/PBF actually BOOST the output but also still makes it so you can get ingots via the furnace." "That config makes it so dusts give 1 ingot and EBF processing with 2 dusts give 3 ingots so you are 3x your ores." "With this change an EBF is an excellent way to process ores more efficiently and actually feels like it pays for the effort because other wise you use a multiblock just to get 2x from ores." " It makes it so that the EBF is a LOT more efficient and makes the game less repetitive." Like OneEyeMaker said the amount of times I have said it is like spam...
