### ISSUE TITLE
[2.0] Quest Typos "Auto Mining"

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#1949]
![image](https://user-images.githubusercontent.com/30208401/30294114-ffa6769a-9709-11e7-9f88-d1e51d4ba1cc.png)

A suggested version:

A miner in LV age? Wow! This nifty machine will find ores for you. Place up to two stacks of mining pipes in the right slots. This machine needs 32 EU/t to work; with an 8V Solar panel it works at 25% speed. The miner searches for ores in a 16 block radius.

**Comment by Dream-Master** [comment]
@KorGgenT you can do pull request make it for me more easy to pull :)

**Comment by KorGgenT** [comment]
sure, let me find the correct thingy.
