### ISSUE TITLE
Add some GT ore substitutes to the smeltery

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#195]
Some GT ore substitutes for lets say... Iron, are not detected as iron by the Tconstruct smeltery and therefore not processed. This includes limonite (brown,yellow, etc), banded iron ore, Granitic Mineral sand, except Pyrite as that is added already.

Malanchite should smelt to copper as well.

**Comment by Dream-Master** [comment]
Adden Brown limoite, Yellow limonite; banded Iron, Granitic mineral, Tetrahydrite, Malachit etc.
