### ISSUE TITLE
[2.0] Rotor Solder Material Requirement

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1951]
#### Which modpack version are you using?
2.0
#### What did you try to do, and what did you expect to happen?
Can you change the recipe back to use 16 not 18 L of fluid? Because for 16L you can use Tiny Piles while for 18L you need stuff like bolts etc. So it makes it better to control exact amounts.
#### What do you suggest instead/what changes do you propose?
Change the fluid requirement back to 16 from 18 (For Soldering Alloy, Tin and Lead are 2x 4x that amount respectively)

**Comment by OneEyeMaker** [comment]
2 rotor per Small pile or 8 rotors per ingot - it's simple. (Matter of habit)
Please, say, how often you craft **_just one single rotor_**? I guess, it's rare cases - most of the time you precraft its by 16-32 items (for electric pumps/turbines/etc.).

**Comment by MineAnPlay** [comment]
But why change something that was already like this before hand? And what about odd numbers?

**Comment by Dream-Master** [comment]
So change back to 16 or let it at 18? @MineAnPlay @OneEyeMaker

**Comment by SirAzazel** [comment]
16

**Comment by Bryfer** [comment]
#1618 - just connecting this one to the previous post for easier tracking :)
