### ISSUE TITLE
[2.0] Searching Meteor/Meteoric in NEI causes a crash (seems like Server Side)

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1952]
Title says it all.

**Comment by Ugachaga** [comment]
> Time: 7/12/17 11:32 AM

Wrong link.

**Comment by MineAnPlay** [comment]
I have almost never used Pastebin but what exactly is wrong?

**Comment by MineAnPlay** [comment]
Oh sorry just realized... Hmm weird? There is no crash report actually (Also thanks for noticing that :P)

**Comment by SirAzazel** [comment]
looks very close to #1084

**Comment by Ugachaga** [comment]
```
[10:53:31] [Client thread/ERROR] [NotEnoughItems/]: Error loading recipe:
java.lang.ArrayIndexOutOfBoundsException: 9
    at codechicken.nei.recipe.ShapelessRecipeHandler$CachedShapelessRecipe.setIngredients(ShapelessRecipeHandler.java:53) ~[ShapelessRecipeHandler$CachedShapelessRecipe.class:?]
```
Well, thats not a reason of the crash too. This is just typical console spam from [Pam's Harvestcraft](https://github.com/GTNewHorizons/NewHorizons/issues/1084#issuecomment-280895162).

**Comment by MineAnPlay** [comment]
When I search "Meteoric" in NEIs Search Bar I crash. I have tried Meteoric Iron, Meteoric Steel, Galacticraft, GalaxySpace and Dreamcraft and none of those caused a crash. Since the crash happens before the items/blocks renders in NEI I don't know what else adds items/blocks that have "Meteoric" in there name, so I'm kinda stumped for now.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30374205-62bbbe04-9884-11e7-8262-fbbc14e6f015.png)

**Comment by Dream-Master** [comment]
seems to be a server issue.

**Comment by Dream-Master** [comment]
@MineAnPlay Any idea how o find out what it is ?

**Comment by MineAnPlay** [comment]
If we find what item/block is actually causing the crash then maybe but till then it's quiet hard to find the reason.
