### ISSUE TITLE
[2.0] GT++ Thorium Reactor (Suggestions mostly)

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#1953]
The Thorium Reactor is kinda too expensive. If I understand it right it produces either 3k 4k or 8k eu/t but the recipe is kinda insane for those tiers. It shouldn't require Naquadah or Naquadah Alloy and make it use IV Machine Hull not UV... Also the Thorium Reactor Control Circuit requires Radon which isn't that bad but it could be changed to use Field Generator (Tier II) but that's up to others. (If you are wondering if it's OP it might be but the infrastructure required to even make the fuel for it is kinda insane (which I like actually like :P) until we actually make one in SP we won't really know but IMO it should be buffed :) but like I said we first need to test it))

**Comment by Dream-Master** [comment]
Didn't know it has a recipe now.

**Comment by SirAzazel** [comment]
Referenced this as example.

**Comment by Dream-Master** [comment]
@draknyte1 Is this true that Thorium rector outputting 3k, 4K, 8K eu ?
It using a UV MAchine hull.

**Comment by draknyte1** [comment]
Produces 4x IV (so LuV). 
Cost isn't that bad, but suggestions are welcome. 

I went for the one requiring radon on purpose. The idea is that for nearly infinite power (fuel usage of reactor is slow) it's not an expensive investment.

**Comment by Dream-Master** [comment]
I suggest not go over LuV /ZPM level ingredients.
@MineAnPlay any other recipe suggetions?

**Comment by draknyte1** [comment]
UV casing isn't that expensive though.

**Comment by Dream-Master** [comment]
Sure but it implies that is some in device in my eyes.

**Comment by MineAnPlay** [comment]
For now make it LuV. Yes it outputs alot if what you say is true but we also have Naquadah Reactors which is 1 block and require almost no infrastructure unlike the Thorium Reactor. Will give more ideas as I think of them.

**Comment by Dream-Master** [comment]
@MineAnPlay any news?
