### ISSUE TITLE
Suggestion regarding Issues Template

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1954]
*Might be better to have it look like:*

```
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
```

This will add separating lines which in my oppinion make text more readable:

Text 1
# 
Text 2

**Comment by SirAzazel** [comment]
Examples of how it would look in actual report:
[Without](https://github.com/GTNewHorizons/NewHorizons/issues/1953)
[With](https://github.com/GTNewHorizons/NewHorizons/issues/1940)

**Comment by Bryfer** [comment]
Took a while before I figured it out, this line doesn't show up  on the android app I'm using, only browser version (?)

Just to let others know ;) 

---

I believe you can also make this line using 3 - - - signs together

**Comment by SirAzazel** [comment]
`#` is thin line when `---` is big line

# 
---

^ compared

**Comment by Dream-Master** [comment]
Make a pull request or a suggestion how to change

Template is located here:
https://github.com/GTNewHorizons/NewHorizons/blob/master/.github/issue_template.md

**Comment by SirAzazel** [comment]
Since i PR'd it - closing issue.
