### ISSUE TITLE
I can not seem to get the large bronze boiler to work

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1957]
#### Which modpack version are you using?
2.0.0.0

#### If in multiplayer; On which server does this happen? 
single player

#### What did you try to do, and what did you expect to happen?

I am trying to make a large bronze boiler but it is saying Incomplete structure. The structure I have is 5 high. 3x3

first level input bus, input hatch, large bronze boiler, 3 firebox, maintenance hatch, muffler (, 1 bronze plated brick

second level- forth 3 bronze plate casing in a vertical row, 1 output hatch, hollow in the center and the rest bronze plated brick

5th level all bronze plated bricks 

#### What happend instead? (Attach screenshots if needed)

It claims that this structure is incomplete and I cant seem to find anything I am doing wrong.

on a semi related note I did not use 2 of the bronze plated bricks from the quest when making this.

**Comment by Dream-Master** [comment]
@Pockyninja Please add a few pics we can look better what happend.

**Comment by Bryfer** [comment]
It's not supposed to be hollow
Check the tooltip for the boiler controller/main block and build it like NEI tells you 
Also keep in mind that different tiers use different mid layers

**Comment by Dream-Master** [comment]
https://ftb.gamepedia.com/Large_Boiler

**Comment by SirAzazel** [comment]
it is hollow @Bryfer 
![image](https://user-images.githubusercontent.com/5310658/30375803-96b07c96-9892-11e7-98bf-f25f9f7c3840.png)

**Comment by OneEyeMaker** [comment]
@SirAzazel 
Hollow just casings; whole multiblock isn't

**Comment by Bryfer** [comment]
It is not hollow @SirAzazel 
![image](https://user-images.githubusercontent.com/22825059/30377092-de2482a6-988e-11e7-96df-6b70167f1542.png)

**Comment by Dream-Master** [comment]
bad photo but yes it is 3x2x5. Wiki need to be changed :)

**Comment by OneEyeMaker** [comment]
@Dream-Master 
This photo is *half* of multiblock (it purpose - show what's inside)
Multiblock is 3x3x5

**Comment by Dream-Master** [comment]
Yes ik but if this guy make the photo change the angle abit it would be more clear.

**Comment by Pockyninja** [comment]
ok after having read what your said I figured out one of my problems (I made it hollow instead of putting the pipe casings in the middle). the bus and hatches are now changing to look like the boiler now but it still says structure incomplete and no matte how much duct tape is used the problems of the boiler don't seem to be fixed.

the 3rd firebox is in the center of the lowest level and the 3 bronze pipe casings are also in the center now.

![2017-09-13_12 37 59](https://user-images.githubusercontent.com/24741793/30389358-9907ab5c-9880-11e7-8b87-131a4f9493e6.png)
![2017-09-13_12 38 03](https://user-images.githubusercontent.com/24741793/30389356-99064168-9880-11e7-85a7-8feddb78a9dc.png)
![2017-09-13_12 38 07](https://user-images.githubusercontent.com/24741793/30389359-9909da76-9880-11e7-86aa-c44035db69ca.png)
![2017-09-13_12 38 11](https://user-images.githubusercontent.com/24741793/30389357-9906905a-9880-11e7-92b7-e84de5a73220.png)
![2017-09-13_12 38 29](https://user-images.githubusercontent.com/24741793/30389361-991bb6ec-9880-11e7-8a62-5f3ba01d3cb0.png)
![2017-09-13_12 38 37](https://user-images.githubusercontent.com/24741793/30389360-990e66b8-9880-11e7-9724-8a602766ec10.png)

**Comment by Pockyninja** [comment]
Ok I figured it out finally. When making this boiler I found out that all input hatches and such on the lowest level need the back end of it to face a firebox. It also seems to require 4 firebox or at least you can not include a bronze plated brick on the bottom level.

I think the assembly of this boiler could likely use a lot better description in the quest.

**Comment by Dream-Master** [comment]
Well i could try to add it in the Quest.

**Comment by Dream-Master** [comment]
@Pockyninja can you wrote me a better decription so i can add it to the book?

**Comment by Pockyninja** [comment]
What do you think of this description?

To make a large boiler you must make a 3x3x5 structure with pipe casings in the center of the middle 3 levels. The lowest level must contain at least 1-2 input hatch, 1-2 input bus, 3-4 fireboxes, 1 muffler, and one maintenance hatch. The lowest level can not contain any plated bricks.  All hatches, buses, and mufflers must have their back side touching a firebox. The output hatch can be placed on any of the upper 4 levels.

**Comment by Dream-Master** [comment]
Yes sure i take over it into the quest. @Pockyninja

**Comment by Pockyninja** [comment]
Thanks

**Comment by Dream-Master** [comment]
Not close this until fix. Thsnks
