### ISSUE TITLE
[2.0] GT++ Redstone Alloy Cables rebalance?

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1960]
The GT++ LV redstone alloy cables have no hitbox when they are placed in the world, as the following issue:

draknyte1/GTplusplus#121

According to the above ticket, it does not look like a fix is forthcoming.

Should probably disable the cables, or at least put a warning in the tooltip.

**Comment by AlphaApotheosis** [comment]
https://github.com/draknyte1/GTplusplus/issues/121

**Comment by kris449** [comment]
#1866 
Please please search before posting.

**Comment by Dream-Master** [comment]
@draknyte1 are Redstonealloy cables lossless and have no hitbox ?

**Comment by draknyte1** [comment]
The lack of hitbox is a gregtech issue so I can't fix it anyway. 

Lossless? Intended.

**Comment by Dream-Master** [comment]
@Technus any idea baout the hitbox?

**Comment by Technus** [comment]
disable the GT++ cables iirc normalGT redalloy insulated cable is also 0 loss

Are you sure your cables dont use your own internal https://github.com/GTNewHorizons/GTplusplus/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GregtechMetaPipeEntity_Cable.java class instead of GT_MetaPipeEntity_Cable?

**Comment by Ugachaga** [comment]
GT++ Redstone Alloy Cables LV tier, original GT - ULV. 
Seems usefull, pity it's bugged.

**Comment by Dream-Master** [comment]
I disable them

**Comment by draknyte1** [comment]
Redstone alloy is not red alloy.

**Comment by Dream-Master** [comment]
I know

**Comment by draknyte1** [comment]
I'll make the redstone alloy cable have 1eu loss for NH. Tec told me how to fix the bounding box.

**Comment by Ugachaga** [comment]
Wait, do you want to deprive them of losslessness? This makes no sense, we already have tin cables with minimal losses. If this really is necessary probably better to complicate the recipe or make it more expencive, but keep them lossless.

**Comment by Dream-Master** [comment]
@Ugachaga why you think they need to be lossless ?

**Comment by Ugachaga** [comment]
At the first place I think there is absolutely no reason to make from them expensive analog of tin cables. No one will use them in that case, obviously. So this change will not be adaptation to GTNH, but simply fiction. In this case it's better to disable and forget them.

The real question there: should loseless LV-cables be available in hardcore modpack? I see no problem here, it's an interesting option. For balance purposes they could be (very) expensive. We already have recipes to craft even creative items, so thats the problem with lossless cables?

**Comment by Dream-Master** [comment]
@Ugachaga sure we can use the high tier plastics and no rubber to insulate the cables and the wires need a mv wire mill as an example. 
@draknyte1 did you change the cable already.  If no wait a bit to finish this discussion first. Thanks

**Comment by Ugachaga** [comment]
@Dream-Master 
Sounds good to me. With such recipes players will not be able to skip regular GT powert transfer system.

**Comment by SirAzazel** [comment]
AFAIK only PVC is used for wire isolation from plastics

**Comment by Dream-Master** [comment]
i will add them via gt and disable gt++ wires. I can add a case Redstonealloy and add high tier pvc

**Comment by Technus** [comment]
Just to clarify the render issue and bounding box issue is gone.

**Comment by Dream-Master** [comment]
ok nice but i think change recipes in GT++ is more difficult then add the able in gt ? @Technus

**Comment by draknyte1** [comment]
Not really. Just tell me what you want it to be.

**Comment by Dream-Master** [comment]
@draknyte1 ok add the wires use mv voltage and for insulation some pvc or some new plastic stuff added in lastest gt (not rubber)
And it can be lossless in this case at 32 eu/t
hanks

**Comment by MineAnPlay** [comment]
Make it require synthetic rubber but not a dielectric material.

**Comment by jagoly** [comment]
What happened with this? On 2.0.4.0, these cables are still incredibly cheap. Arguably they are even cheaper than the ULV Gregtech red cables. It seems really odd for such a cheap superconductor to be available so early.

IMO they need to be waaaaay more expensive, and preferably available a bit later.

I don't like the idea of making them require an MV wiremill, that'd be inconsistent. Surely something else could change however?

**Comment by Dream-Master** [comment]
will look into it

**Comment by jagoly** [comment]
Upon further thought, I think the best action would be to just require better insulation on them, namely silicon rubber or better. That way the recipe for the alloy doesn't need to change, which is good because it seems well balanced as a replacement for molten red alloy in crafting recipes. The only thing that would be pushed later is lossless cables. They could then function as a nice boost when players reach the point of making lots of LV machines for various automated things.

**Comment by draknyte1** [comment]
Post change of rubber suggestion on the original repo. I'll do it there, as I like that idea.
