### ISSUE TITLE
[2.0] electrolyze meteoric steel?

### ISSUE THREAD

**Issue by hebiohime** [GTNewHorizons/NewHorizons#1961]
2.0 epsi
![image](https://user-images.githubusercontent.com/13721540/30406138-f190a2be-98bd-11e7-92e2-f6c4ef233aec.png)
meteoric steel equivalent to steel dust recipe?

"oh no ive made all my meteoric iron into useless steel" "welp, toss it in the me system forever"

**Comment by Dream-Master** [comment]
@hebiohime did you mean Magnetic steel not meteoric ?

If you put it in the electrolyzer yes. 
What is the isue here ????

**Comment by hebiohime** [comment]
can i get a recipe equivalent to this one steel to iron, but meteoric steel to meteoric iron

**Comment by Dream-Master** [comment]
Ok will look what I can do.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31189781-7ffd31c6-a939-11e7-8c93-dc9312f818f6.png)
