### ISSUE TITLE
[2.0] Oil Cracker Still Broken

### ISSUE THREAD

**Issue by Scionoftruth** [GTNewHorizons/NewHorizons#1962]
#### Which modpack version are you using?
2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
Bacon Gaming
#
#### What did you try to do, and what did you expect to happen?
The recipe states that you need to put in a programmed circuit, except there is no acutal place to put it except the controller slot
#
#### What happend instead? (Attach screenshots if needed)
Doesn't actually process
![2017-09-14_00 05 32](https://user-images.githubusercontent.com/11818886/30412989-2d6d1484-98e1-11e7-9674-8afc15006c59.png)
![2017-09-14_00 06 45](https://user-images.githubusercontent.com/11818886/30412991-30925746-98e1-11e7-967e-f3854bfe7bae.png)

#
#### What do you suggest instead/what changes do you propose?
Is there a certain place where the controller should go, all inputs are fluid, so there is no spot, or are you supposed to add a item bus, which isn't listed on the Oil Cracker controller. 
I've had this issue since 1.5.1.1 as far as I've noticed it.

**Comment by basdxz** [comment]
The controller slot is where you are meant to put it. I have four oil crackers running right now on Official Epsilon server.

**Comment by Scionoftruth** [comment]
Ill close this Issue, I ended up rebuilding the structure a few different ways. Turns out the issue was the oxygen you get as a reward from the quest. If you used the steam from the reward it doesn't stack with regular steam, so the process doesn't go.

**Comment by Dream-Master** [comment]
@Scionoftruth so did it work or not. If not not close the issue.

**Comment by Scionoftruth** [comment]
DM The steam I got from the reward from the quest book were the Issue. They don't stack with steam you create in general. So it doesn't match the recipe. The stacking cells from IC2 dont match up. IDK if you already fixed the Issue with the quest reward in the past, but the ones I got from the reward was in 1.5.1.1

**Comment by Dream-Master** [comment]
Will check it. The Oil cracker you get working ? @Scionoftruth

**Comment by Scionoftruth** [comment]
Yep, made sure to duplicate Hast's setup. Just was an issue with the steam

**Comment by Dream-Master** [comment]
So you said the steam cells are not regular steam cells?

**Comment by Scionoftruth** [comment]
Whatever steam cells you get from the Oilcracker Quest as a selection reward

**Comment by Scionoftruth** [comment]
They are in the regular IC2 Cells

**Comment by Dream-Master** [comment]
So change the cells and i can close the issue ?

**Comment by Dream-Master** [comment]
@Scionoftruth Ok you said in the first place Oil cracker is brocken. Is it brocken or did it work for you?
About the steam cells. What is the exact issue with it?

**Comment by Scionoftruth** [comment]
Sorry for long delay, I was out. This can be closed. The oil refinery is working fine. The issue ended up being the steam from the steam cells not being the same as the recipe. So the steam cells that are the reward from the Oil cracker quest are not compatible. I will close it.

**Comment by Dream-Master** [comment]
Yes I see there two fluids in the same canister. Maybe I will add another reward.
