### ISSUE TITLE
Rename "Cumene" To "Isopropylbenzene"

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#1963]
Title says it all, the official server has no age restriction and "Cumene" is quite an inappropriate name for a chemical due to it's significant similarities to a common term for semen. ![image](https://user-images.githubusercontent.com/5740991/30420535-bfc39a42-9931-11e7-81d6-2b879ea7c2e3.png)
For extra reference, "Nomenclature of Organic Chemistry : IUPAC Recommendations and Preferred Names 2013 (Blue Book)"  ISBN 978-0-85404-182-4 lists the term "Cumene" for (1-methylethyl)benzene as "no longer recommended".

**Comment by Technus** [comment]
O ok

**Comment by MineAnPlay** [comment]
lol then check out "Rape". If people think about something that is inappropriate that's there problem.

**Comment by Dream-Master** [comment]
Sure s rename is very easy done.

**Comment by Dream-Master** [comment]
@JohannesGaessler

**Comment by MineAnPlay** [comment]
Just keep it as is... It's not an issue... If people have problems of that being "inappropriate" that's there problem.

**Comment by Dream-Master** [comment]
I ask Johannes and both names i can use. @MineAnPlay
