### ISSUE TITLE
[2.0] The melting of cassiterite sand with carbon dust in EBF gives the wrong result.

### ISSUE THREAD

**Issue by GMous** [GTNewHorizons/NewHorizons#1964]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Smelt cassiterite sand with carbon dust in EBF must give (NEI recipe http://c2n.me/3NKaUF0) 3 tin ingots from 2 cassiterite dust. In real it give only 2 tin ingots. That equivalent of simple furnace. What looks weird.

#
#### What do you suggest instead/what changes do you propose?
Fix the recipe.

**Comment by OneEyeMaker** [comment]
@Dream-Master 
Maybe related to difference of config on clinet and server side (I'm about B:MixedOreOnlyYieldsTwoThirdsOfPureOre).
After all arguments I think that this maybe wasn't good idea to enable this config and you should disable it.

**Comment by Dream-Master** [comment]
Will check

**Comment by GMous** [comment]
In 2.0.1.1 nothing changed.
