### ISSUE TITLE
Some bugs 2.0

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1968]
ver. 2.0 Singleplayer.
1. Chemical reactor hatches changed textures. No same color. Its ugly.
2. Still consuming mold rotor. (but shape not consuming).
3. Craft table(tinkers) work as ice. Smothly moving on craft table ,

**Comment by basdxz** [comment]
3 is an intended feature

**Comment by Dream-Master** [comment]
1. @Technus any idea
2. Fixed in 2.0.0.0 so far I know

**Comment by Technus** [comment]
Not just an intended feature, a poorly documented one too.

Hatches might require offset change will take a look.

**Comment by Technus** [comment]
@Proha5 - gib screen

**Comment by Dream-Master** [comment]
@Proha5 we need a screenshot from you.

**Comment by Proha5** [comment]
![default](https://user-images.githubusercontent.com/29812448/30508569-428a70a2-9add-11e7-9801-90d5570a9e09.png)

**Comment by Dream-Master** [comment]
Oh very ugly.  @Technus Any idea how to fix?

**Comment by Technus** [comment]
The controller block is also affected, which makes me wonder.

**Comment by Dream-Master** [comment]
@Technus @draknyte1 

to point 1
Is this fixed or stilla n issue?

**Comment by draknyte1** [comment]
GT is using the wrong textures.
Index 0-63 is GT,
64-127 is GT++.

**Comment by Dream-Master** [comment]
@Technus are you able to fix tht in us gt repo?

**Comment by Technus** [comment]
It is also present in bloody repo

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/76af34564e1aefd938352556b587c0700d766472

**Comment by draknyte1** [comment]
It seems you've moved it from 114 to something still above 63?
64-127 are NOT for GT..

**Comment by Dream-Master** [comment]
@Technus
