### ISSUE TITLE
Casting Form (Coinage Mold) uncraftable, possible recipe conflict

### ISSUE THREAD

**Issue by unexpectedbukakke** [GTNewHorizons/NewHorizons#1969]
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 
BaconGaming, although the issue exists in SSP
#
#### What did you try to do, and what did you expect to happen?
The Casting Form (Coinage Mold) does not have a recipe, so it is not possible to craft things like chunkloader coins that some servers use exclusively for Railcraft anchor fuel.
#
#### What happend instead? (Attach screenshots if needed)
No recipe exists in NEI in SMP. In SSP there does look to be a recipe but it is the same recipe as the Casting Form (Shovel Head Shape) and the coinage mold isn't craftable.
#
#### What do you suggest instead/what changes do you propose?
The addition of a recipe :)

**Comment by bigbass1997** [comment]
For Servers: The server package that we distribute for the modpack, by default, does not include recipes to create the chunkloader coins. It is up to the individual server to setup how they want to manage chunkloading.

For Single Player: Personally I have not checked this recipe, so can't comment on it in this context.

**Comment by Dream-Master** [comment]
There is a zzclient.zs script which activate coins if you play in sp. Server-side see bigbass comment.

**Comment by AlphaApotheosis** [comment]
I can confirm in single player - the recipe is in NEI but there is a recipe conflict with the Casting Form (Shovel Head Shape) so it cannot be made. I think there is still a bug.

**Comment by Dream-Master** [comment]
ok will check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31186148-21b39f16-a92e-11e7-8154-677419c6429d.png)
