### ISSUE TITLE
All thaumcraft aspects cleared in v2.0 !!!

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1970]
(singleplayer)
How return my aspects? 3 months i study many things for aspects. And v 2.0 delete all aspects!
i have old save and config (from 1.5.1.2) may be i can restore my aspects?

**Comment by Proha5** [comment]
already restored.
I moved "myname.thaum and "myname.thaumback" files from 1.5.1.2 to 2.0 and my aspects restored.
but why its happened?

**Comment by Dream-Master** [comment]
I don't know. Did you change your user name or account?

**Comment by Proha5** [comment]
username not changed.

**Comment by Dream-Master** [comment]
Sometimes save data get corrupted. So make always a backup

**Comment by Dream-Master** [comment]
@Proha5 can this be closed?

**Comment by Proha5** [comment]
yes.
