### ISSUE TITLE
Air Filter [Tier2] uncraftable

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#1971]
#### Which modpack version are you using?
2.0

Air Filter [Tier2] uncraftable has no recipe and is currently uncraftable

**Comment by Dream-Master** [comment]
i see a commit in GT++ this will add the recipe. Will be in 2.0.0.1 i hope.

**Comment by Dream-Master** [comment]
Ok there is no recipe yet @Drobac 
Any idea when you add one @draknyte1

**Comment by draknyte1** [comment]
Recipe was added https://github.com/draknyte1/GTplusplus/commit/e2844ef59c5c509cdb044960626e48aa599fda63.

**Comment by Dream-Master** [comment]
Then something happend with the cells. I can't see the recipes.
