### ISSUE TITLE
[2.0] Biogas

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#1972]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon

Biogas is extremely not efficient.
1)With advanced fermenter and advanced distillery I'm able to produce 50eu/t from my Gas Turbine if it was 100% fuel efficiency.
2)With 3 advanced fermenter and 3 advanced distillery i can hardly produce even 120eu/t.(because 50eu/t * 3 minus fuel efficiency)
More than that to support 3fermenter+3distillery I need 1 advanced compressor, 2 lv compressors and still they don't produce enough Biomass to make fermenter+distillery run 100% of time (they don't have enough Biomass to produce).

More than that Steve's cart for trees and Steve's cart for crops together don't produce even the half of required apples/sapplings/crops to keep running those 3 fermenter+3 distillery.

Conclusion: to have 120eu/t I should make 2 Advanced Compressor, Centrifuge, Extractor, machine that makes Biomass, 3 Advanced Fermenter, 3 Advanced Distillery. Steve's cart for tress/crops (which can cover only half of required biomass sapplings/apples/ crops, so I should get an extra Forestry farm).

And to get 320eu/t in Large Bronze Boiler I only need Large Bronze Boiler + Advanced Coke Oven. 

So tons of machines, +tons of farms for not even constantly working 120eu/t.

And on the other side, easy 320eu/t for Large Bronze Boiler + Advanced Coke Oven (with Lumber Jack collecting wood for Oven is not a problem at all).

And remember, that both Advanced Gas Turbine / Large Bronze Boiler are MV tier. They are like 2 different solutions for MV energy problem. But In fact we have only one - Large Bronze Boiler or OIL. But not Biogas anymore.

My suggestions:
At least reduce the requirements in terms of Sapllings/Apples/Crops -> Biomass ratio. It now eats them like crazy, i need multiple farms ONLY to support 120eu/t, which is literally nothing. It consumes Biomass/Biogas extremely fast. It should be at least double Biogas for Biomass than it is now. I already have farms that cover 80% of my base. If I make even more, that will affect TPS of the server. And I need much much more.

**Comment by MineAnPlay** [comment]
It will balanced once we starting working on it but biogas(methane biogas is gonna be kinda removed (only for jetpack refilling)) is supposed to be for LV and early MV. For MV and HV use Bio Diesel/Light Fuel/LPG/Diesel (yes it's now worth making it)/Cetane-Boosted Diesel or other Oil products.

**Comment by AlphaApotheosis** [comment]
@MineAnPlay Do you have a sense of how you want the balancing to end up? I could mock up some numbers balanced with other energy sources. 

I would advise keeping biomass > biogas the same as it is now (only somewhat energy positive) and just increasing the methane output of fermented biomass distillation. Also, eliminate or reduce the output of the methane > biogas distillation (this recipe doesn't really make thematic sense anyway).

**Comment by nikitinalexx** [comment]
This is what I counted for Biomass

Counted for 100 seconds of machine working.
Biogass 40.000eu per cell
Advanced Fermenter 26.66 times * 600eu(overclocked) = 16.000eu (2.66 biomass into 2.66 fermented biomass)
Advanced Distillery 250 times * 256eu(overclocked) = 64.000eu (2.5 fermented biomass into 4.5 biogas)
4.5 biogas * 40.000 - 16.000 - 64.000 = 100.000 eu.

100 seconds is 2000 ticks.
50eu/t. Minus efficiency.
This is exactly 42.56 sappling per 100 seconds. So for ~40eu/t efficiency we should be able to support a sappling every 2 seconds. That's quite a lot.

**Comment by nikitinalexx** [comment]
One more point.
1) Basic Distillery 25 Oil + 480 eu + 1 second = 30 Sulfuric Gas
(Distillery 13.3 buckets of Oil + 255.840eu + 533 second = 16000 Sulfuric Gas)

2) Sulfuric Gas * 16000 + 2 Hydrogen + 8 seconds = 16000 Refinery Gas = 16 * 160k eu = 240eu/t

13300 oil for 240eu/t in 533 seconds

0.024 oil in second for 240eu/t.

So with only 1 Basic Distillery and 1 Basic Chemical Reactor I can make 240eu/t with only 0.024 oil per second usage.

**Comment by Dream-Master** [comment]
@JohannesGaessler 
Any balancing idea ?

**Comment by JohannesGaessler** [comment]
First off, if you overclock your machines instead of having several low-tier machines run in parallel you'll always have poor efficiency regardless of the recipe you're using.
According to my calculations a setup consisting of a LV Fermenter and a LV Distillery will produce a net of 33 EU/t.
The same setup with MV machines will produce 46 EU/t (about 30% less efficient in terms of Biomass).
My calculations neglect energy consumption for the production of Biomass.
The assumed efficiency is at 90% for a MV turbine.

Regardless, I suppose the amount of Energy that you currently get per Biomass is rather low.
I've been conservative with the energy density because I figured that an underpowered recipe is better for the game's balance than an overpowered one.

**Comment by Dream-Master** [comment]
So i guess we keep the new recipes like they are.
