### ISSUE TITLE
Minor bug Annealed copper does not etrude bolts properly

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1973]
#### Which modpack version are you using?
2.0.0

#
#### If in multiplayer; On which server does this happen? 
single player

#
#### What did you try to do, and what did you expect to happen?

When using the extruder (mv specifically) to get bolts from annealed copper from ingots you get copper bolts not annealed copper.

**Comment by mitchej123** [comment]
```
Annealing is the metallurgical term for heating a material (generally a metal) and subsequently cooling it
to change its properties (such as its hardness or durability). Annealing copper makes it softer and less
brittle, which allows you to bend it without breaking it.

Hot extrusion
Hot extrusion is a hot working process, which means it is done above the material's recrystallization 
temperature to keep the material from work hardening and to make it easier to push the material through 
the die. Most hot extrusions are done on horizontal hydraulic presses that range from 230 to 11,000 
metric tons (250 to 12,130 short tons)
```

Basically by extruding something (likely hot extruding) that's been annealed, you'll lose the annealed properties.  The same will happen with wraught iron.  Use a lathe and then a cutter instead.

**Comment by Pockyninja** [comment]
I understand that in the real world you might have some degree of a point, but in this mod it is at best inconsistent since annealed copper extrudes properly into rods and I am fairly sure some others work. Secondly it is wildly unpractical for this mod to require so much annealed copper and have no practical way to get it into forms beyond ingots.

**Comment by Dream-Master** [comment]
Only annealead copper and wrought iron have this behavior

**Comment by MineAnPlay** [comment]
Can you add a recipe for annealed bolts? (You made it for the rod but the recipe got changed and it no longer requires rods)

**Comment by plunderdog** [comment]
I'm not an expert by any means but from what I've read 'hot extrusion' basically anneals the material at the same time because both annealing and extrusion require the material to be above re-crystallisation temperature.

**Comment by Dream-Master** [comment]
Are molds a better alternative instead of extrude annealead copper? (Bolt Mold, Stick mold etc?)
@Pockyninja @mitchej123 @MineAnPlay @plunderdog

**Comment by MineAnPlay** [comment]
Just use the Extruder recipe. Extruder recipe isn't completely realistic but let's say it adjusts its self when extruding Annealed Copper. Molten Annealed Copper is impossible.

**Comment by Bryfer** [comment]
What happend to the idea to make annealed copper parts from copper parts inside an (arc) furnace?

**Comment by Pockyninja** [comment]
I guess molds could work but I think just making the extruder maintain annealed would be the better option in my opinion.

**Comment by Dream-Master** [comment]
Arc furnace is a better idea but thst mean you coukd make the small parts only there out of copper parts. Need to look at it.

**Comment by MineAnPlay** [comment]
Arc Furnace is to recycle stuff mainly. Yes it does make Annealed stuff but it's used to recycle stuff. Molten Annealed Copper is impossible so the only one left is Extruder and you could just say it processes Annealed materials "specially"

**Comment by Dream-Master** [comment]
Why you are against arc furnace. Yes Gretech use it for recycling but why have oure own fork and we can do different stuff then the main branch. I dont like the tunnel view here @MineAnPlay

**Comment by Dream-Master** [comment]
I open up a new issue for it.
https://github.com/GTNewHorizons/NewHorizons/issues/2021
