### ISSUE TITLE
[2.0] Forestry Multifarm in Managed Arboretum mode does not produce any fruits besides apples

### ISSUE THREAD

**Issue by OperativeLoop** [GTNewHorizons/NewHorizons#1975]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
Built a forestry multifarm and ran it in Managed Arboretum Mode, which should produce sapplings, wood, fruit and rubber. 

I expected to get some fruit products from the trees, but the only one that seems to work is the basic apple oak sappling. 

#
#### What happend instead? (Attach screenshots if needed)
Apple Oak Sappling -> Produces apple in farm
Rubber Sappling -> No sticky resin
Hazel and Dwarf Hazel sappling -> No Hazlenut
Cultivated Pear sappling -> No pears. 
#
#### What do you suggest instead/what changes do you propose?
I've looked in the config for Forestry, looks like we are set to Hard mode, but it doesn't mention anywhere disabling fruits. Not sure what the point of having tree breeding is if you can't get the better products from bred trees. I suggest either fixing this bug or clarifying somewhere that it won't work so that people don't waste time on it.

**Comment by mitchej123** [comment]
I think you need to be in Manual Orchard mode for fruits, not managed Arboretum: https://ftbwiki.org/MultiFarm

**Comment by OperativeLoop** [comment]
I'm not seeing any fruit planting the trees by hand either. How is it supposed to work?

**Comment by Dream-Master** [comment]
@mitchej123  Did you test it or only link it to the forum page?

**Comment by mitchej123** [comment]
@Dream-Master - I haven't tested Manual Orchard mode in this pack, but have used it in other packs for picking fruit.  I linked to the Wiki as it explains the different modes and has been useful for me in the past.

**Comment by Dream-Master** [comment]
I not change things in forestry wich mean that it worked

**Comment by mitchej123** [comment]
I just set one up in creative and it's definitely working (using sweet chestnut trees).  Make sure to use an Intrinsic Circuit Board, solder iron, set the solder iron to manual farm, and fill it with copper electron tubes.

**Comment by mitchej123** [comment]
![image](https://user-images.githubusercontent.com/1894689/30991345-94521b94-a459-11e7-8ce7-8dac445d002e.png)

**Comment by Dream-Master** [comment]
@mitchej123 thanks.
