### ISSUE TITLE
[2.0.0.0] Circuit crafting needs tweaks

### ISSUE THREAD

**Issue by Palesteak** [GTNewHorizons/NewHorizons#1976]
Hello,

I'm playing on the Epsilon-Server. Since the new Version of the modpack was installed crafting circuits became the main thing to do for me and also others. I don't think that the new system is bad, but extremely unbalanced material and timewise. This leads to eat up too much time in general when playing or even just waiting for machines to do their job and craft stuff for you.

One thing that really annoys me is the requirement of circuits of the lower tiers to craft higher ones. This does not make sense.. you wouldn't start making an i7 starting with an intel 8086, would you? ^^

What do you suggest instead/what changes do you propose?
At least in earlier tiers, make the crafting process less tedious.. its just too time consuming...

Best regards,

Palstek

**Comment by MineAnPlay** [comment]
25216s (420.27 mins or 7 hours) with out Plastic Boards 59924s (998.74mins or 16.65 hours) with Plastic Boards. Enough materials to make 64 Workstations. (Time taken for crafting the  Resistors and Diodes aren't included since Thermionic Fabricator is kinda instant)
https://cdn.discordapp.com/attachments/224191655375273985/358711959681499137/2017-09-16_23.13.53.png
15min for ONE circuit...
Oh I forgot something... The time it takes to make the circuits
6400s (106.7 mins or 1.8 hours just to craft the circuits themselves)

**Comment by Methes** [comment]
I'm in LV so I don't feel the pain yet but after looking at the Vacuum Tube and Resistor recipes it really doesn't make sense for Thermionic Fabricator to be the best choice.
Considering almost everything that had only Forestry machine recipes in the past has GT alternatives now it's kinda strange to make Fabricator the best choice.
Not only is it almost instant and takes little power, it has no tier gate as other machines do.
Making it a worse alternative is fine so why not switch the recipes?

Circuits requiring previous circuits is entirely different story.

**Comment by MineAnPlay** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1978 I've said what I think should be done for the Fabricator and the reasons why

**Comment by Palesteak** [comment]
It is interesting to see that Dream tags/replies to all other issues but seems to intentionally ignore those related to the balancing of the new circuit system ^^

**Comment by Dream-Master** [comment]
Not ignore but look for a lable i could give this issue °°^^

**Comment by Palesteak** [comment]
OK, my bad ^^

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1996
