### ISSUE TITLE
Balance of AE2 storage cells

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1979]
4x1kb = 4kb. Requere 16LV circuits
1x4kb = 4kb. Requere 16LV + 4MV circuits
Result: cheaper create more ME drives and create 1kb cells.
May be each new tier cells requere 3 previous circuits instead 4?

**Comment by Dream-Master** [comment]
@Proha5 3 circuits in the recipe looks very ugly. Maybe you have another idea how to change it.

**Comment by Proha5** [comment]
Yes, 3 circuits is ugly. Original AE2 and infitech2 recipes requere 3 previus  storage components.
Like as there: http://ae-mod.info/16k-ME-Storage-Component/
(glowstone = circuits)

**Comment by Dream-Master** [comment]
Mh will check it.
