### ISSUE TITLE
Two ammonia recipes don't make sense

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#1980]
There are two recipes for ammonia:

![image](https://user-images.githubusercontent.com/30811906/30522947-40d8947c-9ba6-11e7-83d2-ac2ae0181261.png)

And the HV:
![image](https://user-images.githubusercontent.com/30811906/30522951-50f35f0e-9ba6-11e7-9277-c7fe03fb11d2.png)

Having both these recipes makes no sense as the LV recipe is many times better than the HV recipe, and 1 Nitrogen to 1 Hydrogen -> 2 Ammonia doesn't make much sense. Do we need the LV recipe for ammonia? 

If we do I think the LV recipe should be changed to 1000 Nitrogen + 3000 Hydrogen for 1000 Ammonia, just like the HV recipe. Ammonia is NH3 after all.

**Comment by AlphaApotheosis** [comment]
Not sure we need the LV recipe for ammonia at all. If anyone needs ammonia at LV, it is possible to get from biomass.

**Comment by Dream-Master** [comment]
@JohannesGaessler Are this two recipes valid recipes or did i wrongly forget to remove one?

**Comment by JohannesGaessler** [comment]
This recipe is added by GT++.
Presumably Alkalus has balanced this independently from my implementation of Ammonia.

**Comment by Dream-Master** [comment]
@JohannesGaessler Ah ok thanks for info.
@draknyte1 can we remove this recipe in GTNH?

**Comment by draknyte1** [comment]
Sure.

**Comment by Dream-Master** [comment]
Thanks

**Comment by draknyte1** [comment]
Resolved in https://github.com/draknyte1/GTplusplus/commit/77043cacaa5a2385ffa785df8a76dd8b6b66a28c.

**Comment by Dream-Master** [comment]
@draknyte1 can you please remove the whole recipes because your recipe using 30 eu and gt 384 eu /t?
(for GTNH only)
Thanks

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30617976-cc9aef16-9d98-11e7-80fc-9edde9b43f20.png)
![image](https://user-images.githubusercontent.com/2970688/30617979-d15099de-9d98-11e7-9d5c-f6e4aac8447d.png)

**Comment by Usernm0** [comment]
Version 2.0.1.3

Now we have this:
![](https://i.imgur.com/hFmMVzp.png)
![](https://i.imgur.com/Byewcp6.png)

Please add some sense to first recipe or remove it completely.

**Comment by Dream-Master** [comment]
One is gt the other gt++

**Comment by draknyte1** [comment]
The latter is technically wrong, Johannes should fix it. Passing it over a catalyst that doesnt get consumed is more realistic than a numbered circuit.. Go look it up.
