### ISSUE TITLE
2.0.0.0 Stainless steel fluid pipes can't be broken with wrench

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1981]
#### If in multiplayer; On which server does this happen? 
Both MP and SP
#
#### What did you try to do, and what did you expect to happen?
Wanted to break a stainless steel pipe with a GT wrench to pick it up and it didn't work. I'm not the only one with this problem.

**Comment by MineAnPlay** [comment]
Not an issue. Stainless Steel (and most higher tier materials) have a higher mining level then (Steel which is most likely what you were using). Damascus Steel/Vanadium Steel or anything with a high enough mining level should be able to mine it (it should be 3 if I remember right).

**Comment by Lainiel** [comment]
I see. There's still an issue that the WAILA is showing that the pipe should be harvestable with a steel wrench.

![image](https://user-images.githubusercontent.com/18221846/30524599-4f1da5c6-9bf7-11e7-9479-39c9dae319ee.png)

**Comment by Dream-Master** [comment]
Waila have many bugs

**Comment by Dream-Master** [comment]
@Lainiel 
can this be closed or did you have an additional idea to fix this in waila or add a tooltip somewehere?

**Comment by Dream-Master** [comment]
@Lainiel any news here?

**Comment by Dream-Master** [comment]
Add a tooltip to high tier pipes via Core mod is possible.

**Comment by Lainiel** [comment]
Yeah adding a tooltip to a higher tier pipes that you need a wrench with a higher tier material is a good idea.

**Comment by Dream-Master** [comment]
I will add a Quest for high tier pipes because add tooltips for all pipes will do the list extreme long.
