### ISSUE TITLE
recipe bug biomass to ethanol

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#1982]
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 

single
#
#### What did you try to do, and what did you expect to happen?

In the recipe list if you look at biomass it claims you get 12 Ethanol for 40 Biomass when you run it through the distillery with circuit set to 1.

#
#### What happend instead? (Attach screenshots if needed)

When you run biomass through the distillery with the circuit set to 1 you get IC2 Biogas which seems fairly useless.
#
#### What do you suggest instead/what changes do you propose?

The recipe needs to be fixed in one way or the other. Either it needs to reflect what actually happens or make what happens reflect the recipe.

**Comment by MineAnPlay** [comment]
Please check carefully before posting recipe issues. The biomass used has a slightly lighter colour because it's the IC2 biomass used there. It's made using distilled water and bio chaff in the brewing machine.

**Comment by Pockyninja** [comment]
I did check it properly. I used the same cell of biomass to choose how to make it and to process it. I made it from gregtech biomass which if you type in biomass is the bottom right most. The metiod I used to make it was macerate plantball into a centrifuge into a brewery with water in it into a distillery set to 1. this is the metoid to get biomass gregtech then distilling it to 1. All machines involved were GT.

Please verify a claim if you which to speak to it. I have double checked since my current process is the same except I am fermenting it now before turning it into ethenal and the process makes GT biomass.

According to the recipe in order to get IC2 biomass you need a fluid canning machine which I do not have. As such I can not have it even if I wanted to mess up in this way.

**Comment by Pockyninja** [comment]
Having looked into it more it is in fact GT biomass the difference in color is from using distilled water instead of regular. regular makes GT item number biomass 7036:8 but you need GT biomass 7036:29

There is a issue since both are displayed as the same thing in NEI but if you look hard enough you can find the issue.

**Comment by kris449** [comment]
Can we just get rid of the second biomass (the one made with regular water), it makes searching NEI very confusing and has no unique recipes of its own.

**Comment by Dream-Master** [comment]
will check

**Comment by MineAnPlay** [comment]
There is nothing wrong here. Keep it as is.

**Comment by kris449** [comment]
What are you saying here Mine? Yes there is nothing wrong with the ethanol recipe. But having the IC2 biomass in the game when we're using the GT one is pointless.

**Comment by Dream-Master** [comment]
I will check it.

**Comment by Dream-Master** [comment]
Ok i cant remove Biomass. One is from Ic2 one is from forestry. I can try to add more recipes so you can make ethanol of both if this is possible.

**Comment by Dream-Master** [comment]
The recipes (biomass forestry to ethanol) was deprecated and removed. i forgot to disable it.

**Comment by Dream-Master** [comment]
I rename Biomass from Forestry to Forestry Biomass.

**Comment by Dream-Master** [comment]
Hope this helps.

**Comment by Pockyninja** [comment]
I am not sure is forestry biomass the one that was labeled Biomass 7036:8 or 7036:29? The ones that claim they are GT biomass? The confusion from my position was that GT has 2 different things called biomass for simplicity I will call one Biomass and the other distilled biomass since one is made with vanilla water and one is made with distilled water. That is the difference between making biogass and making ethanol.

**Comment by Dream-Master** [comment]
GT Biomass have they own name .

**Comment by Pockyninja** [comment]
Not the item number I mentioned. They show up in NEI as the same biomass just like anything that shares the same item number. The important part is the number after the : . It represents a variance of the item in question and as such shows up in NEI as the same item.

**Comment by Dream-Master** [comment]
Maybe i look how biomass is made in forestry and add this fluids.

**Comment by Pockyninja** [comment]
It has nothing to do with forestry I have not used a single nonGT machine in any process involved in any of this. This is GT biomass.

To get this biomass you use a GT brewery and for the liquid input you use either distilled water or vanilla water.

**Comment by Pockyninja** [comment]
![2017-09-22_11 56 08](https://user-images.githubusercontent.com/24741793/30753350-13838262-9f8d-11e7-85c3-349ca67d4ad9.png)
![2017-09-22_11 56 06](https://user-images.githubusercontent.com/24741793/30753352-1573fffc-9f8d-11e7-8f4e-c2b058c983d1.png)

**Comment by Dream-Master** [comment]
No they not. Upstairs there is IC2 down there is Forestry. GT look different.

**Comment by Dream-Master** [comment]
meta id not identical.

**Comment by Dream-Master** [comment]
:8 down :29

**Comment by Pockyninja** [comment]
I know the meta id is different but they are both at least in game labeled as GT as you can see from the screenshot. If that meta data makes them forestry then then that means the labels are wrong. In fact the meta number (which I now know the label for) is what I been going on and on about mentioning the difference was the 8 and 29.

Depending on how your navigating it is easy to get the 2 confused since they don't show up separate in NEI. They dont make the different appearance because only the meta is different and I think the average user know much about meta numbers. I think that it would be better off as 2 separate materials since they cant be used to make the same items.

**Comment by Dream-Master** [comment]
@Pockyninja i cant disable them they used in Forestry/IC2 for other stuff. I can change only the recipe you get Biomass from Forestry to make clear it is anoter fluid.

**Comment by Pockyninja** [comment]
So the meta data is referring to the fact they are not gregtech and are in fact different mods even with a label of gregtech on them?

if you cant relabel them or anything to make the distinction clear I guess this is something that just cant really be helped. I wasn't suggesting they be disabled at any point. I was more thinking one could be clearly labeled something different for example the (possibly forestry one) meta id 29 could be considered distilled biomass since it uses distilled water. If nothing like that can happen then I cant think of a good solution.

**Comment by Dream-Master** [comment]
Bio chaff is a ic2 item make ic2 biomass
Mulch, Compost and fertilizer are forestry items make forestry biomass
Both biomasses can be made to gt fermented biomass

**Comment by MineAnPlay** [comment]
It's kinda obvious, one is dark green and the other is light so it's easily noticeably. GT doesn't add any biomass directly. If you search Biomass you will see two fluids (the ones that look like in world fluids). Light Green is Forestry and is made via Distilled Water and can be either be used to make Fermented Biomass or to make Ethanol with Forestry's efficiency (and should stay as is because it requires distilled water). The other is IC2 Biomass which can be used to make a few things including Fermented Biomass.

**Comment by Dream-Master** [comment]
I post new recipes in a min here.

**Comment by MineAnPlay** [comment]
New recipes? Why are you adding new recipes for?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30759218-b334fed8-9fd5-11e7-9b18-23112c5fc16c.png)
![image](https://user-images.githubusercontent.com/2970688/30759225-b93753da-9fd5-11e7-9563-3cf5eea829a0.png)
![image](https://user-images.githubusercontent.com/2970688/30759231-bf844180-9fd5-11e7-814f-c59e5e5aeaad.png)
![image](https://user-images.githubusercontent.com/2970688/30759236-c60336ec-9fd5-11e7-8d6e-943ab6ec4d0e.png)
![image](https://user-images.githubusercontent.com/2970688/30759239-c9b5e12c-9fd5-11e7-8a23-0597e2a14583.png)

**Comment by Dream-Master** [comment]
Compost gt recipes is missing.

**Comment by MineAnPlay** [comment]
Why though? The old recipe was good enough because Ethanol shouldn't be hard to make.

**Comment by Dream-Master** [comment]
they not harder then the old recipes. I make it more specific. Forestry use forestry stuff. ic2 ic2 stuff.

**Comment by MineAnPlay** [comment]
It's a Foresty fluid yes but it's made via GT and the main use is to make Ethanol. If you change it to these recipes it won't really be worth it.

**Comment by Dream-Master** [comment]
if i not change it people will mixed up fluids. Are the amount is wrong or what is the issue here?
2 plantballs gives 1 chaff at lv, mv
thats why i add 16 mulch/compost/fertilizer with water, 12 with distilled water and 10 with fruit juice.

@MineAnPlay Suggest another value if imbalanced.

**Comment by MineAnPlay** [comment]
The input item isn't what is confusing people it's the fluid itself. Just keep it as is. If it works there is no problem.

**Comment by Dream-Master** [comment]
I spend now the whole evening to nerf it. And i rename cells allready
![image](https://user-images.githubusercontent.com/2970688/30762678-3e410d48-9fe3-11e7-9a3d-fa217f1d1fac.png)

**Comment by MineAnPlay** [comment]
OK that's nice. But just leave the recipe as what it was before hand. Also did you do the seeds from other mods? If not just tell me where it is and I will do it myself.

**Comment by Dream-Master** [comment]
The recipe was bugged before nos ic2 biomass can use water and destilled water. I guess this was never be finished so i finish it now. If zeta is awailable next update you can look at it and say me what need to be adjust but i like the new recipes make they way from which mod the biomass is much more clear.
Gt fermented biomass can outpull all of the stuff.

**Comment by Dream-Master** [comment]
For the mulch i using some crops from other mods if you mean that (BoP, Harvetcraft)

**Comment by MineAnPlay** [comment]
Wait what? The IC2 Biomass can only be made via normal Water. The Forestry one can ONLY be made via Distilled Water.

**Comment by Dream-Master** [comment]
No Ic2 one can now made by water and distilled water
Forestry can make now with water, distilled water and fruit juice

**Comment by MineAnPlay** [comment]
![2017-09-23_00 01 01](https://user-images.githubusercontent.com/23314473/30764207-9a88fd0e-9ff2-11e7-8b01-b80c697eb603.png)
As you can see you CAN make Forestry Biomass and ONLY use Distilled Water for it. You CAN'T use Distilled Water to make IC2 Biomass.

**Comment by Dream-Master** [comment]
now you can.

**Comment by MineAnPlay** [comment]
Dream DON'T CHANGE ANYTHING about the biomass (Other then the name of the Forestry one). The recipes are fine and balanced as is.

**Comment by Radst0ne** [comment]
@MineAnPlay Forestry Biomass has a other use than ic2 biomass. Its more worth using forestry biomass to get ethanol

**Comment by MineAnPlay** [comment]
"It's a Foresty fluid yes but it's made via GT and the main use is to make Ethanol. If you change it to these recipes it won't really be worth it." ... Please read :P I know it's alot xD. But once again KEEP THE RECIPE AS IT IS. Making Distilled Water requires a setup and it can only be used to make Ethanol more efficiently or to make Fermented Biomass but since you can use normal Water to make Fermented Biomass it's not really worth using it for anything other then Ethanol.

**Comment by Radst0ne** [comment]
thats the logic behind, forestry is more for ethanol or making fermented biomass.
ic2 is more for biogas and fermented biomass

**Comment by MineAnPlay** [comment]
Yes and the recipe should stay as is. That's what I'm trying to explain to Dream :P

**Comment by Radst0ne** [comment]
but why? the new recipe is much more nicer, @MineAnPlay lets discuss on discord

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30767167-e973295a-9ffa-11e7-97f1-774d62994f8f.png)
reminder fix this recipe (ash is missing)
