### ISSUE TITLE
[Quest Change] Building made easy 601 - remove some blocks

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1987]
This quest gives you Builder's Wand.
With the removal of LV Ender Eye recipe you can only craft Energized Voidstone at HV age. (#1986)
With potential change of Chisel's Concrete getting that one will get a lot more complicated. (#1984)

Please remove Energised Voidstone and Concrete from the quest demands so that players can get this tool early as intended in the past.

**Comment by Dream-Master** [comment]
Energised Voidstone i change the recipes and concrete not get very difficult.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30617637-3e1d3c4a-9d97-11e7-8e2e-c55f208de88d.png)

I make gt recipe more easy so you get 16 Concrete blocks in stead of 6,9
