### ISSUE TITLE
Pentlandite products smelting inconsistent with NEI

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#1988]
Crushed pentlandite ore as well as impure and pure pentlandite dusts show in NEI as smelting into a full nickel ingot, but actually smelt into 6 nuggets like most other metals.

Version 2.0, DirtHuts server

**Comment by Dream-Master** [comment]
Fixed and reverted in 2.0.0.1. Client and Server config mismatch in 2.0.0.0
