### ISSUE TITLE
craft bug: different count of microprocessors

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1989]
v2.0
![default](https://user-images.githubusercontent.com/29812448/30577437-8eefb4fe-9d51-11e7-9a77-807348222768.png)

**Comment by Proha5** [comment]
Strangle, later bug disapear. NEI bugged?

**Comment by Dream-Master** [comment]
Recipe two using an uncraft able etched wires from earlier versions. Not sure what went wrong here? @Proha5 is this a nei bug or a craft bug too?

**Comment by Proha5** [comment]
nei bugged.

**Comment by Dream-Master** [comment]
@Proha5 Wait but why there recipes shown they not there?

**Comment by Proha5** [comment]
I using "Faithful 32" texture pack. ) Some textures overrided.

**Comment by Dream-Master** [comment]
Ok then it might be an error i did. Maybe adding an recipes with the wrong output. etched wires becomes diodes after the update.

**Comment by MineAnPlay** [comment]
No it's not a bug. Just him using an outdated texture pack.

**Comment by Dream-Master** [comment]
Yes i know but the amount should be 2 not one circuit.

**Comment by MineAnPlay** [comment]
Just checked all of the recipes output 2 for me.

**Comment by Dream-Master** [comment]
Yes for me too so i gusee a nei bug or any other bug is possible.

**Comment by Dream-Master** [comment]
@Proha5 If you have more or new ifo about it i reopen it.
