### ISSUE TITLE
Unintended recipe gates after removing LV Eye of Ender recipe.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#1990]
#### Which modpack version are you using?
2.0.0.0
#
#### What's wrong?
Now that the LV Eye of Ender recipe has been removed (#1986) several items have been gated behind HV machines that were not intended that way.
Vacuum Hopper - requires an Endereye Plate
World Anchor - requires an Eye of Ender
Energised Voidstone - requires and Eye of Ender
#
#### What do you suggest instead/what changes do you propose?
Vacuum Hopper - change the Plate to Enderpearl Plate
World Anchor - change the Eye of Ender to Ender Pearl (recipe is still gated to MV thanks to dense obsidian plate)
Energised Voidstone - change the recipe to 8x Voidstone + 1x Glowstone Dust (fixes #1987)

**Comment by Dream-Master** [comment]
Yes need to change that. Thanks for info @Methes

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30613570-db143a1c-9d88-11e7-917f-1671befc33eb.png)
![image](https://user-images.githubusercontent.com/2970688/30613589-ebd643f4-9d88-11e7-85f3-1d38456906e2.png)
