### ISSUE TITLE
[Coin Quest Suggestion]OreBerry/EssenceBerry Bushes

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#1991]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Since there appears to be no other way to get these berry bushes apart from a few select quests (giving only 5/10 tops).  Could you consider adding a repeatable coin quest to get more of these bushes?  I enjoy building my farms with these bushes.

**Comment by Dream-Master** [comment]
Sure I can add some.

**Comment by tranceplanet** [comment]
nice, thanks :)
