### ISSUE TITLE
"Slime Island Journey" quest not completing with required materials

### ISSUE THREAD

**Issue by CheshireSensei** [GTNewHorizons/NewHorizons#1992]
#### Which modpack version are you using?
2.0.x
#
#### If in multiplayer; On which server does this happen? 
BaconGaming
#
#### What did you try to do, and what did you expect to happen?
Another user and myself each attempted to complete the Tier 1 quest "Slime Island Journey".  We expected the quest to clear, and for it to grant the indicated rewards.
#
#### What happend instead? (Attach screenshots if needed)
Instead, the quest remained open as if it were not complete.
#
#### What do you suggest instead/what changes do you propose?
I suggest that you make the quest completable by fulfilling the posted conditions.

**Comment by Dream-Master** [comment]
I change the quest. You not longer need the grass because you need a shovel with silk touch. 
Can you send me a pic from the Quest? @CheshireSensei

**Comment by Dream-Master** [comment]
After changing the quest it works for me. I tested it in Single player and it works.

**Comment by grumpymood** [comment]
I also am having an issue with 2.0 not completing the slime island journey.  I have all components including the grass (silk touch item).  I am on prospercraft.com server user name Grumpymood.
![2017-09-25_12 55 15](https://user-images.githubusercontent.com/29691833/30820750-dd724bf2-a1f0-11e7-906e-eb5dfd85b139.png)
![2017-09-25_12 55 08](https://user-images.githubusercontent.com/29691833/30820759-e43711b6-a1f0-11e7-8a32-292fab324ba2.png)

**Comment by grumpymood** [comment]
Thank you for the response but both detecting and dropping then recollecting did not work.  I am going to drop then log out and log back in to see if that helps.

**Comment by Dream-Master** [comment]
@CheshireSensei @grumpymood please test it with 2.0.0.1 when avaiable. Thanks
