### ISSUE TITLE
Automate processing array.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1993]
Many recipes contain integrated circuits, shapes, molds, lens.
Procesing array work only with one shape. Players should create many machines and processing arrays for each shapes/circuits.
Idea: Let processing array use material ONLY with shape/circuit, which contained in the same input bus.
Example: i create processing array with 8 input bus. Each input bus contain different shapes.
If i need plates - then i put ingot in input bus contained "plates" shape. If i need bolt, then put ingot in bus contained "bolt" shape.
Can you do it?

**Comment by Dream-Master** [comment]
@Technus  any idea here?

**Comment by Technus** [comment]
i wanted to implement advanced processing array, will do one in TecTech mod.

**Comment by Dream-Master** [comment]
@Technus are this in tec tech yet?
