### ISSUE TITLE
Mod suggestion: Better Placement

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1995]
I'd like to suggest this mod:

https://minecraft.curseforge.com/projects/better-placement

It improves the block placement system in mc, combined with the fact that we need to make huge bases for GT, I think it would be a nice thing to have.

**Comment by SirAzazel** [comment]
As far as i saw on gifs it may use same way to increase block placement as instaplace in cheat clients. Also mod is purely clientside so your suggestion only may make so you dont need to download it, but it can be used even right now.

**Comment by mtesseracttech** [comment]
I did not know about it being purely clientside. It just seemed like a nice addition to ease the creation of bases/large multiblocks

**Comment by Technus** [comment]
Some other alternative is schematica

**Comment by Methes** [comment]
Just a clarification: Schematica does completely different thing but does it very well and works with 2.0 and previous versions of the pack very well. (clientside too)

**Comment by Dream-Master** [comment]
@Technus why invalid tag ?
