### ISSUE TITLE
2.0.0.0 ME drive accepts only advanced circuits

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#1997]
#### Which modpack version are you using?
2.0.0.0
#
#### What did you try to do, and what did you expect to happen?
When crafting the ME drive the recipe accepts only one type of advanced circuits.

![picture](https://puu.sh/xEwIl/3868bda03d.png)

**Comment by Proha5** [comment]
Craft of "molecular transformer" have some problem.
