### ISSUE TITLE
Suggestion: Seed Oil Sources

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#1998]
Seed oil sources are pretty bad at the moment, the only really viable things are ExtraTrees trees. This got bad enough that on Delta everyone was just sharing a bunch of hazel saplings that an older player made, because nobody could be bothered to either breed it themselves or get it any other way (there isn't really a decent way to get the required amounts otherwise)

So my suggestion: A plant, Rapseed(Canola) for example that would serve as a decent source for Seed oil.
Or: Increase the current amounts of seed oil.

**Comment by MineAnPlay** [comment]
Vanilla Seeds already give 10L and only take 1.6s to process. There also already is Rape. From IC2 crops and outputs 50L per process. Getting a large amount of wheat isn't really that hard and you can even make a few world accelerators if you really want a large amount.

**Comment by Dream-Master** [comment]
Maybe need to make a world Acceleartor quest.

**Comment by Radst0ne** [comment]
A Sprinkler (OpenBlocks) Quest  would be more efficient it just needs water and it grows nearly instant

**Comment by Radst0ne** [comment]
@MineAnPlay yeah getting large amount of wheat isnt hard, but nevertheless reduce the seed output of wheat to 2-3? that would be an much easier fix and it makes bio diesel more worth to use

**Comment by MineAnPlay** [comment]
Wait what? Did you even look at the recipe... It NEVER gave 1(was 3L before) Did you even read what I said? *sigh* It already GIVES 10L per recipe. It's just that other modded seeds aren't using the new 1.5 recipes (outputting 10L and requiring 32 ticks). Or did you mean something else?

**Comment by Dream-Master** [comment]
Should i change the other recipes to 10L seed oil each crop?

**Comment by Radst0ne** [comment]
@mineanplay I meant the crafting recipe you can convert one wheat into one seed and I thought maybe it helps buff it to 2 or 3

**Comment by kris449** [comment]
No Dream this is fine, seed oil was already buffed. Seeds are very easy to get even on a 1 wheat: 1 seed ratio. For example I just went and harvested 10 wheat crops and got 33 wheat. Besides that there are tons of other sources of seed oil.

**Comment by Radst0ne** [comment]
what about using steam and some seed oil source in a chemical reactor (multiblock) to create seed oil, like a steam juicer does, since there is some mutliblock needed for seed oil production, since for ethanol methanol is one.

**Comment by Dream-Master** [comment]
@mtesseracttech @MineAnPlay @Radst0ne @kris449 
So did we need to add some new recipes like the setam variant that RadstOne mentioned or not? Otherwise i will close this issue.

**Comment by mtesseracttech** [comment]
Hmmm, I am not reallly sure what he is referencing and I don't really have the time to test it either at the moment. If it fits well and is achievable, I don't see why not. If it adds too much tedium... I'd avoid it.

**Comment by Dream-Master** [comment]
Ok
