### ISSUE TITLE
Battery buffer accept 1A per battery instead 2A

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#1999]
ver 2.0
GT wiki says:

> Battery Buffers emit Amps equal to the number of Batteries they contain, and accept Amps equal to twice the number of Batteries they contain. 

But i tested. Battery accept max 1A.
I tested battery charger ( 8A in / 4A out ) - works fine. Only battery buffer have bug.

My tested value:
Battery buffer:
 2 battery sources --> 1 battery destination. Charge speed: 1A (should be 2A)
Battery charger:
 2 battery sources --> 1 battery destination. Charge speed: 8A (its ok)

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Dream-Master** [comment]
@Proha5 can we close this issue ?

**Comment by Proha5** [comment]
@Technus 
understod.
I can't acept 32A to Battery buffer contained 16 batteries?
But i can accept 32A to Battery Charger contained 4 bateries?
Right?
