### ISSUE TITLE
Transformer tooltip is contradictory

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2000]
For example LV transformer, first line sais 'MV -> LV', which is the default way when placed. Next two lines say 'Voltage IN: 32 (LV) - Voltage OUT: 128 (MV), which would be LV -> MV.

https://i.imgur.com/mRYykTd.jpg

Version 2.0, DirtHuts server

Update: Using a soft mallet on a placed transformer also has a tooltip error. First click is correct, says "Step Up, In: 128V 1A, Out: 32V 4A', but second click only says 'Step Down, In:' with no further information.

https://i.imgur.com/PkKuGgA.jpg

**Comment by Technus** [comment]
it happens bcs of the trafo being inverted on placement

**Comment by Dream-Master** [comment]
@Technus can you fix it?

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/b9ae0a67546a55634144d444527a7320a2e21049
fixes the on mode change behaviour
