### ISSUE TITLE
Oregeneration config error - Apatite veins

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2001]
#### Which modpack version are you using?
2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
Private Server and Client
#
#### What did you try to do, and what did you expect to happen?
Apatite vein in config has two lines of
                I:OreSporaticlyAround_607=607
                I:OreSporaticlyAround_833=833
Only the first one triggers so there's Pyrochlore and no Phosphate in the veins.
Googledocs table says there should be Phosphate and not Pyrochlore.
The Quest 588 requires Apatite, Phosphorus and Phosphate - this quest can't be completed with current worldgen.
#
#### What do you suggest instead/what changes do you propose?
Either remove Pyrochlore from the configs (both client and server) or change Phosphate to Pyrochlore in both Questbook and Googledocs table.
Doing the former means people will need admin intervention/new oregen to be able to complete the quest if they created a new world in 2.0.0.0.

**Comment by Dream-Master** [comment]
I need to update the quest. This mix was changed but the quest not.

**Comment by jagoly** [comment]
It seems you forgot one thing - NEI still shows the vein as containing phosphate, not pyrochlore. 

It's actually kind of worrying to find that NEI ore vein plugin seems to be hardcoded.

**Comment by Dream-Master** [comment]
@jagoly which version ?

**Comment by Dream-Master** [comment]
yea fixed https://github.com/GTNewHorizons/GT5-Unofficial/commit/dcfdf6a8d70666b42c48ee9754c5d7e9347d9618
@jagoly thanks

**Comment by jagoly** [comment]
dang you're fast :D

**Comment by Dream-Master** [comment]
i am always fast :)
