### ISSUE TITLE
I can't PreGen Twilight Forest.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2002]
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 
Mine :)
#
#### What did you try to do, and what did you expect to happen?
Used Admin Commands Toolbox to Pregen every world fine but twilight.
#
#### What happend instead? (Attach screenshots if needed)
https://pastebin.com/V0QxDUnE

#
#### What do you suggest instead/what changes do you propose?
Not sure if it can be fixed just thought I share the error. Twilight forest is one the most laggy places in existence.

**Comment by Dream-Master** [comment]
@Namikon can you say how we pregen tf?

**Comment by Namikon** [comment]
I've used WorldBorder to pregen the Dimensions.
TF is a pain to pregen; But i've had quite some success with disabling server activity and switching to peaceful mode while running the pregen (IIRC, WorldGuard/WorldEdit comes with a /stoplag command). It keeps the crashes related to entities/physics/"block not found" at a minimum

**Comment by KaneHart** [comment]
Thanks mate for the suggestion. I will go ahead and change this to closed and give that a try. Clearly a nasty bug but something that be a lot of effort to track down and fix and probably out of our control anyways.
