### ISSUE TITLE
Heat proof casings Infinite Invar

### ISSUE THREAD

**Issue by Gemlord** [GTNewHorizons/NewHorizons#2003]
#### Which modpack version are you using?
latest 2.0
#
#### If in multiplayer; On which server does this happen? 
Dirthuts
#
#### What did you try to do, and what did you expect to happen?
Make heat proof casings
#
#### What happend instead? (Attach screenshots if needed)
Made them, but noticed an infinite item loop in NEI
![image](https://user-images.githubusercontent.com/18751509/30733587-721ca0f6-9f6f-11e7-8375-21a6606ac13c.png)
8 invar makes 2 casing
![image](https://user-images.githubusercontent.com/18751509/30733600-7f6766ce-9f6f-11e7-9352-8bca7df71b3d.png)
pulverising in a macerator still gives back 8, meaning 8 invar is used, then crushed, for 16 invar.
#
#### What do you suggest instead/what changes do you propose?
reduce the assembler recipe to give only one casing (every other casing works like this anyway) or make the casing recycle to 4 ingots.

**Comment by Dream-Master** [comment]
sure make sense.
