### ISSUE TITLE
Die on half slab doesn't generate grave.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2005]
#### Which modpack version are you using? (2.0)

#
#### If in multiplayer; On which server does this happen? (Private server)

#
#### What did you try to do, and what did you expect to happen? (Died on a half slab)

#
#### What happend instead? (Attach screenshots if needed) (No gravestone generated, so all item lost)

#

**Comment by Dream-Master** [comment]
Then you need somone restore your grave if you play on a server? @Gateswong

**Comment by Gateswong** [comment]
I think we find out how to restore it. But it is definitely a BUG.

Thank you.

**Comment by Dream-Master** [comment]
Nothing we can do here i guess.
