### ISSUE TITLE
BQM problem

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/NewHorizons#2006]
#### Which modpack version are you using?
# latest

#### What did you try to do, and what did you expect to happen?
# reinstall latest version of pack
#### What happend instead? (Attach screenshots if needed)
# nothing

Hey, I load my world and suddenly some of quests became like this. How can I fix it?

![image](https://user-images.githubusercontent.com/28770016/30782611-016002c4-a13e-11e7-8789-f6114b77f7d6.png)
![image](https://user-images.githubusercontent.com/28770016/30782618-2bcbff2c-a13e-11e7-8d15-93745b6e85b1.png)
![image](https://user-images.githubusercontent.com/28770016/30782620-3114da9e-a13e-11e7-8e76-820a02abd63c.png)

**Comment by Dream-Master** [comment]
try to run this commadn /bq_admin default load

**Comment by JohnWarrior01** [comment]
tnx, it helped)
