### ISSUE TITLE
[2.0] Polytetrafluoroethylene is Extremely difficult

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2008]
#
#### If in multiplayer; On which server does this happen? 
Epsilon

So I've recently got into quest in MV era called "Way one: Raw carbon mesh".
It says that we can produce Raw Carbon Fibre in MV era with using Molten Tetrafluoroethylene

I decided to check how to make it, and this is the shortest line that i found.
1)1 Tetrafluoroethylene + 7 Oxygen Gas = 1.5 Molten Polytetrafluoroethylene
2)4 Hydrofluoric Acid Cell + 2 Chloroform = 1 Tetrafluoroethylene + 6 Diluted Hydrochloric Acid Cell
3)2 Methane + 12 Chlorine = 6 Hydrochloric Acid + 2 Chloroform Cell
4)4 Fluorine + 4 Hydrogen = 4 Hydrofluoric Acid Cell

So to get ~10 Polytetrafluoroethylene Ingots/Plates you need 2 Methane + 12 Chlorine + 4 Fluorine + 4 Hydrogen.

Now imagine a production line that you need to get those 2 Methane + 12 Chlorine + 4 Fluorine + 4 Hydrogen? And those are only Basic components. After that you need to follow these 1-4 steps to get 10(!!!) Polytetrafluoroethylene Plates. Even those 2 Methane are pain the ass, I'm not even talking about 12 Chlorine, 4 Fluorine and 4 Hydrogen. And that is only for 10 plates? I can make tons of Polyethelene.
In my assumption that should be 10+ machines to make Polytetrafluoroethylene line.

I see that you've added Polytetrafluoroethylene as an MV replacement for LV Polyethelene.

But with the current situation noone will ever make Polytetrafluoroethylene , because with the same production line they are able to produce 50x amounts of Polyethelene. Noone yet has made Polytetrafluoroethylene on the server and noone will make it because there is no sense. More than 20+ recipes to get to Polytetrafluoroethylene whereas Polyethelene is extremely easy.

**Comment by bigbass1997** [comment]
Well what you describe appears to be equal to or honestly easier than PTFE was in v1.4, which can be seen in this image https://i.imgur.com/7Xy7VjG.png

Now I would have to do more research to accurately compare the new recipe chain to the old, but PTFE being a long process is not a new thing.

**Comment by Proha5** [comment]
@nikitinalexx Try create epoxid. Then you should feel, that Polytetrafluoroethylene is extra easy. :) I created 256B epoxid during 10 real days!
