### ISSUE TITLE
AE2 Stuff. Consumption bug.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2010]
ver 2.0 Singleplayer.

Total ME consumption: 220 eu/t
![default](https://user-images.githubusercontent.com/29812448/30797354-090b47fa-a219-11e7-8eb4-0d3fb82be35b.png)

I add 2 wireless connectors. Distance between = 8 blockes. Linked it. And Total comsumption = 960Eu!

![default](https://user-images.githubusercontent.com/29812448/30797370-1c7d9db0-a219-11e7-9b4f-5bc82a0fca06.png)
Wiki says, formula consumption wireless conectors = 10+distance^2.
10+8^2 = 74. And value under green marker is valid. But total consumption increased by 740 eu.
Why?
I tested. Realy consumption = 960.
Probably, bug increasing consumption x10 times. 740 = 74 x 10.

**Comment by Dream-Master** [comment]
Me system using 10 more engery then the default config. This config i change a long time ago.

**Comment by Proha5** [comment]
Then wireless connectors is bad item. Because distance 16 blockes requere 2560 eu. 32 blockes requere 10.000 eu/t. Its crazy.

**Comment by Ethryan** [comment]
Wireless AE is expensive. Change your own config if you want to have different numbers.

**Comment by Bryfer** [comment]
Just FYI, the IC2 nuclear reactor is increased by 10x  but really it's 20x due an X2 thingy, so just make one of those 
They can output alot more than 10keu/t
