### ISSUE TITLE
Chisels

### ISSUE THREAD

**Issue by Sokolov57** [GTNewHorizons/NewHorizons#2011]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Local server

There multiple chisels from different mods in this pack, but they do not interact at all, and mostly work with their native mod blocks only (the only exception is chisel from chisel, but that is the mod that just makes this item).

Do you have an intention to merge this somehow? Because chisle from chisel for example is way better than chisel form thinker's construct, but cannot be repaired on tool station and they work with different blocks. Just to make modpack more pack))

**Comment by Dream-Master** [comment]
I guess my java knowledge isn't that big to be able to do a change like that.

**Comment by Sokolov57** [comment]
The reason I'm saying this is beacuse it is one of a few (if not only) basic tools that cannot be rapired using tool station, but still it does not disappear at 0 durability (which made me think i can repair it). 
Can you fix this (somehow)?

**Comment by hebiohime** [comment]
chisel from chisel can be repaired using thaumcraft restorer

**Comment by Dream-Master** [comment]
Guess this works to. @Sokolov57 can we close this issue?

**Comment by Sokolov57** [comment]
I guess so. I tried to figure out some indirect way to fix this, but without any success. I mean, you probably know better what you can) It s no big deal tbh. Just a little messy.

**Comment by Dream-Master** [comment]
As i said earlier i am not an advanced programmer.

**Comment by OperativeLoop** [comment]
Could you  just change the name of the items? Then there wouldn't be confusion, since they are different items with different uses. "Tinker's Chisel" and "Block Chisel"

**Comment by Dream-Master** [comment]
I can add a tooltip for the block chisel. Add it for tinkers is impossible. To much combinations and items.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31181456-a6ab9398-a921-11e7-8d05-ef1bc7627ba5.png)
