### ISSUE TITLE
Recipe for raw styrene-butadiene rubber dust yields too many empty cells

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2012]
The recipes that use 1 styrene cell + 3 butadiene cells + air/oxygen have 4 cells total in their input, but 16 cells in their output, essentially duping empty cells.
Output should be X dust + 4 empty cells.

(v2.0.0.0 - DirtHuts server)

![cells](https://user-images.githubusercontent.com/11035501/30849519-e509f4ca-a2a2-11e7-9f51-e7c7b7515d05.png)

**Comment by Dream-Master** [comment]
@JohannesGaessler

**Comment by JohannesGaessler** [comment]
Thank you for notifying me.
I pushed a fix to the GT5U repository.

**Comment by Dream-Master** [comment]
@JohannesGaessler thanks will cherry pick it.
