### ISSUE TITLE
Extruder shape (wire) gets consumed

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2013]
Borosilicate Glass Bar with Extruder Shape (Wire) consumes the shape. This does not seem to happen with other materials.

(v2.0.0.0 - DirtHuts server)

![mold](https://user-images.githubusercontent.com/11035501/30849738-a810d61e-a2a3-11e7-9dd0-0531b47fa4f3.png)

**Comment by Dream-Master** [comment]
Fixed in 2.0.0.1
