### ISSUE TITLE
[2.0] Annealed Bolt recipe is Wrong

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2014]
#
#### If in multiplayer; On which server does this happen? 
Epsilon

1)There is a quest in MV called "Advanced Circuits". In 1st stage it requires 32 copper bolt but in 2nd stage it requires Advanced Circuit which is produced of 32 ANNEALED copper bolt, but not usual Copper Bolt.

2)If you put Annealed Copper in Extruder, it will give you only 8 Copper Bolt, but it should be giving you 8 Annealed Copper Bolt. (There is a workaround. Put 4 Annealed Copper in Extruder (ROD). Then put 8 Annealed Copper Rod into Cutter).

**Comment by Dream-Master** [comment]
Not a bug. We have open up some issues before with this thematic.

**Comment by Dream-Master** [comment]
Maybe the quest is set wrong.

**Comment by nikitinalexx** [comment]
Yes, then just change the quest to require Annealed Bolt

**Comment by Dream-Master** [comment]
K

**Comment by Dream-Master** [comment]
The quste was fixed allready. I will change the recipe to get Annealead copper anyways.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/30940419-55e79e7e-a3e1-11e7-904f-f93b5b292785.png)
