### ISSUE TITLE
[2.0][Epsilon] Bricked Blast Furnace Automation

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2015]
Is it possible to automate Bricked Blast Furnace with Ender IO Item Conduit?

1)From 3 output slots it outputs only from 2nd and 3rd. 1st slot where produced ingot is, is not being emptied.
2)From 3 input slots it inputs only in bottom and middle. The top slot where Dust is put, is not being filled.

![image](https://user-images.githubusercontent.com/4941736/30856072-daea5648-a2bf-11e7-8b0f-4a3ac08911aa.png)

**Comment by Dream-Master** [comment]
Bronze age machines are not good for automation

**Comment by nikitinalexx** [comment]
Dream, but how else I can transform my Chalcopyrite into Copper? Output in Furnace is always less.

**Comment by Dream-Master** [comment]
You can but no automation. Your ebf can be automated

**Comment by nikitinalexx** [comment]
But in ebf there is no such recipe Chalcopyrite into Copper

**Comment by Gemlord** [comment]
There is a recipe involving a reaction with Silicon Dioxide in the Blast furnace proper to give a product i can't remember, that can then be reacted to get the copper, similar multi-steps exist for galena, etc

**Comment by AlphaApotheosis** [comment]
Check ebf recipe for cupric oxide - you can then get copper from ebf recipe with cupric oxide and carbon, like @Gemlord says above. This is the same as several other minerals.

**Comment by Dream-Master** [comment]
@nikitinalexx did you find the recipes?
Can this issue closed?

**Comment by nikitinalexx** [comment]
Yes, such recipe exists, ty.
