### ISSUE TITLE
Unnecessary Circuit in Filter recipe

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2016]
#### Which modpack version are you using?
2.0.0.0
#
#### What's the deal? (Attach screenshots if needed)
Item Filter (Gregtech) can only be made in a Assembler using Zinc Foil and Fine Steel Wire or Raw Carbon Mesh.
Fine Steel Wire has a different recipe with Glowstone in the Assembler - no conflict.
Zinc Foil can only create the Item Filter - no conflict.
Raw Carbon Mesh has two different recipes, one potentionally conflicting already has circuit - no conflict.
#
#### What do you suggest instead/what changes do you propose?
Remove the circuit requisite from both Item Filter recipes.

**Comment by Dream-Master** [comment]
I could but if i let it in we are save for new recipes maybe added with some similar materials. @Methes Did a circuit meta change help too?

**Comment by Methes** [comment]
True, it's safe for potential new recipes so leave it.
I'm not sure what circuit meta change you're talking about.

**Comment by Dream-Master** [comment]
The two recipes you mentioned in your first post. Did they need to change to a different meta or just fine. @Methes

**Comment by Methes** [comment]
The Fine Steel Wire one works just fine, didn't have the chance to test the second one - not at that tier yet.

**Comment by Dream-Master** [comment]
I let the circuits in for more recipes in the future.
