### ISSUE TITLE
Slippery TC blocks

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2017]
#### Which modpack version are you using? 
2.0.0.0
#### What happened?
It seems that all Tinkers Construct blocks has traction like ice - they're slippery. 
I've tried walking on the Casting Table, Crafting Station, Seared Stone, Seared Bricks, Stencil Table, Pattern Chest, Part Builder, Tool Forge - and they all behave like ice blocks.

**Comment by Dream-Master** [comment]
Yes i have that too. Not sure why.

**Comment by hebiohime** [comment]
#1968 Not just an intended feature, a poorly documented one too. -technus ( slippery tc blocks )

**Comment by Dream-Master** [comment]
Not make sense for me. Ok maybe slime block can have this feature but smelter?

**Comment by Technus** [comment]
Indeed a poorly documented feature.
