### ISSUE TITLE
Bug: Chemical reactor select wrong recipe

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2022]
ver 2.0. singpleplayer.

I want create sulfur dioxide.
I put in chemical reactor Oxygen + Sulfur dust + circuit configuration[2].
But created sulfur trioxide instead dioxide!
Sometime create doxide. Random.

Sulfur trioxide have 2 recipes : with circuits[3] and without circuit.

**Comment by Technus** [comment]
needs circuit in other recipe to remove conflict @Dream-Master

**Comment by Dream-Master** [comment]
Will check it.

**Comment by Dream-Master** [comment]
I guess fixed in 2.0.0.1
