### ISSUE TITLE
Again, consuming extruder shape :( 

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2023]
v 2.0 singleplayer.
Bug:
Borosilicate glass + extruder shape(wire) consuming shape.
Other material not consuming shape.
Borosilicate no have wiremill recipes. No other way to get glass fiber, only use extruder.

**Comment by Dream-Master** [comment]
Known Bug. Already fixed.

**Comment by Dream-Master** [comment]
After update I close it.
