### ISSUE TITLE
Microprocessor crafting with SMD is not working

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2025]
#### Which modpack version are you using?
2.0 (latest public)
#
#### If in multiplayer; On which server does this happen? 
Epsilon, also tested in single player
#
#### What did you try to do, and what did you expect to happen?
Create microprocessors in a cleanroom with SMD components
#
#### What happend instead? (Attach screenshots if needed)
Recipe is not working. Clean room is clean. Machine have energy.
![image](https://user-images.githubusercontent.com/23512002/30965987-e633fcec-a45f-11e7-95b0-14329dd35443.png)

**Comment by Proha5** [comment]
Requere 2 SMD.

**Comment by repo-alt** [comment]
oops
