### ISSUE TITLE
Fence

### ISSUE THREAD

**Issue by Sokolov57** [GTNewHorizons/NewHorizons#2026]
Another thing (2.0) is that there s some weird problem with fence recipe. 
As you can see, it crafts the thing, but for some reason it calls it a slab. It was my test in single world, but on server (which is down right now) it s even worse -- it shows fence as a result, but when you try to take it, it gives you some other block. 
Anyway, you can clearly see from screenshots, that there is smth wrong.

![2017-09-28_14 18 14](https://user-images.githubusercontent.com/17034571/30985626-821b56a8-a499-11e7-8dea-edc10723c7c8.png)
![2017-09-28_14 18 17](https://user-images.githubusercontent.com/17034571/30985629-823d0f32-a499-11e7-8b5e-2904c1ad84bd.png)
![2017-09-28_14 18 19](https://user-images.githubusercontent.com/17034571/30985627-821cd3ac-a499-11e7-9137-d3f4c13b849f.png)
![2017-09-28_14 19 46](https://user-images.githubusercontent.com/17034571/30985630-82816b78-a499-11e7-911f-f2fa5467f18a.png)
![2017-09-28_14 19 48](https://user-images.githubusercontent.com/17034571/30985628-821ff564-a499-11e7-976c-d3b53dfded0b.png)

**Comment by Radst0ne** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1304

**Comment by Sokolov57** [comment]
Sry, didn't see it. I ll better show the other part, when my server is up.
