### ISSUE TITLE
Vacuum Freezer requires EV circuits

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2028]
#
#### If in multiplayer; On which server does this happen? 
Epsilon

Is this correct that it requires EV circuits?

In Space Race quest line, which actually starts in HV era, the second quest requires Glowstone doped Wafer. It's temperature is 2700K so we need Kanthal Coil Block. Kanthal Ingot requires Vacuum Freezer which requires EV circuits. So if all of these started in early-middle HV era, why does it require EV circuits, which consequently require Cleanroom.

**Comment by Dream-Master** [comment]
Cleanroom is HV.

**Comment by bigbass1997** [comment]
Vacuum Freezer requires DataCircuits, one of which can be crafted in HV. Thus Vacuum Freezer is HV.
