### ISSUE TITLE
Crucible Lag

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2029]
#### Which modpack version are you using?
2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Use a Crucible flawlessly.
#
#### What happend instead? (Attach screenshots if needed)
It lags a LOT! (see link)

https://youtu.be/kawFmTUsvN4

**Comment by Dream-Master** [comment]
Any log that could say why it lags ?

**Comment by Methes** [comment]
Sadly the server console doesn't say anything. Unless other players have this problem too, you can close this until I get more info. I suppose Alchemical Construct won't have these issues so it's not a big deal for us.

**Comment by Dream-Master** [comment]
i let it open and will see if others have the same problem.
