### ISSUE TITLE
Shutter module recipe

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#203]
Recipe uses a wrong version of the iron doors and is atm uncraftable

**Comment by Dream-Master** [comment]
Ok i see it Iron Doors -1. All Recipes with Iron Doors a screwed up. I asking Blood asp all ready and waiting for an answer. If he cant fix it I will rewrite the recipes. (Could be Malis Doors the problem ?)

**Comment by Namikon** [comment]
BeyondReality had the same problem with non-functioning shutters, but I can't remember if and how they fixed it. However, I do remember it was after they updated gregtech from .07 to .08, the same patch when some of the gem plates got messed up I think

**Comment by Namikon** [comment]
There you go:
Beyond-Reality/BeyondRealityModPack#201

**Comment by Dream-Master** [comment]
Maybe malis door issue.

**Comment by Dream-Master** [comment]
It is Malis doors same as in Beyond reality Blood asp said to me. I will minetweaker it.

**Comment by Dream-Master** [comment]
fixed
