### ISSUE TITLE
Nuclear power rework suggestion

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#2030]
I'd like to make using multiblock generators for power production more attractive. In my opinion using a very basic single block nuclear reactor that makes 2000EU/t in EU mode is just lazy and boring, not to mention that cooling nuclear reactor with air doesn't make much sense.

Here are my proposed changes:
- Scale down nuclear generator in EU mode from 10 to 2.5
- Scale up the Large Heat Exchanger from a maximum of 800 hot coolant/s to 4000 hot coolant/s. This is actually a small nerf, because you either have to use more reactors, or use a chip to lower the efficiency to get HP steam.
- Scale up optimal flow for all turbines in HP Steam and Steam Large Turbines by 4 or more

This change should make fluid nuclear reator much more attractive and also boost the popularity of other ways to make power like Large gas turbine, Large diesel engine, or tree farm with pyrolease oven and large boiler into large steam turbine.

**Comment by Dream-Master** [comment]
reducing the the single block to 2.5 is possible but i cant scale up the hot coolant right now. Nee some ic2 api additions  @Aroma1996 want add soon.

**Comment by Lainiel** [comment]
There's no need to scale up the hot coolant coming from the nuclear generator. Just to scale up how much hot coolant can the large heat exchanger use. The large heat exchanger from vanilla GT needs 4000L/s of hot coolant to make HP steam and the maximum is 8000L/s. Our large heat exchanger takes 400L/s for HP steam and 800L/s maximum. My suggestion is 2000L/s for HP steam and 4000L/s maximum. This is still pretty hard to make with a single nuclear reactor, so reducing efficiency to get HP steam with a chip is needed.

**Comment by Dream-Master** [comment]
Then I need help @technus

**Comment by Methes** [comment]
Please don't nerf energy sources but rather boost those that need it.

**Comment by Usernm0** [comment]
It be cool if somebody write little mod to ban non liquid cooling ic2 reactors at all. 

In our server we decide to change x10 ic2 reactors back to x1, because they kill every other energy sources. 
Nobody make big and complex turbine systems, when you can just make ic2 reactor with 2 chambers (little stick) and get 2000 eu/tick from it.

**Comment by Dream-Master** [comment]
just talked with Aroma about a api funktion in reactor in ic2

**Comment by DeForce** [comment]
Agree, when we have stupid energy from ic2 reactor, no need to build complex systems.

**Comment by Dream-Master** [comment]
I had a conversation with Tec today and he said fluid nukes are twice better then single block nukes

**Comment by Dream-Master** [comment]
@technus

**Comment by Technus** [comment]
the problem with IC2 nukes is that you are limited by 10000L/s of coolant heating - so the liquid production boost will remain 1x.

yes the nerf by 4x for EU mode is not as bad idea since if u make an external cooling with vac . freezer reactor it can still put out quite the punch.

![image](https://user-images.githubusercontent.com/4737429/31052517-eb82b14c-a686-11e7-9d4d-d407ab0362bd.png)

like this reactor filled with MOX would make ~20k(-cooling cost) eu/t.

regular thorium air cooled reactors would went back from 2k to 512V (aroundish)

back to fluid reactors, yes turbines are slow compared to the steam i/i

changes done:

- [ ] @Dream-Master  plz. nerf the IC2 eu rector to 2.5X from 10X (=-1 tier rating in eu production)
- [x] large exchanger got superheat theshold and max troughput doubled (now is capable of 32k eu/t of steam heat exchange...) 1600 coolant/s max 800 theshold
- [x] added loose fitting mode for large turbines - this lowers the turbine rotor eff and improves the troughput

**Comment by Technus** [comment]
![image](https://user-images.githubusercontent.com/4737429/31053659-af9fa204-a6a2-11e7-9afb-fe8616e85e5f.png)

**Comment by Technus** [comment]
![image](https://user-images.githubusercontent.com/4737429/31053904-336507ec-a6a7-11e7-8c90-afc96534dacb.png)

**Comment by Methes** [comment]
Would it be possible to mark all these changes at one place somewhere? Right now I honestly don't know which numbers are correct anymore and the GTNH google table regarding Turbines is wrong too.

**Comment by Lainiel** [comment]
@Technus Didn't you mean to nerf the EU reactor to 2.5X from 10X? 4X wouldn't be a nerf by 4

**Comment by Dream-Master** [comment]
To 4x I guess

**Comment by Technus** [comment]
to 4x

**Comment by Palesteak** [comment]
GJ nerving ANOTHER energy-source, a crucial one on top of that, wrecking the setup of a lot of bases, thank you... how about boosting something for a change? For example make large turbines generally more viable in exchange at least? Especially the large steam turbine.

**Comment by DeForce** [comment]
You have like 20 ways of generating energy. But with 10x modificator you could just throw everything away and just build nuclear. Now you will have the ability to generate energy various ways, not just building nuclear.

**Comment by SirAzazel** [comment]
i vote for boosting nuke power to 5x, fluid reactor heated coolant production 5x, making/boosting harder to make turbines HV+, adding ways to cool loads of coolant at same time for IV+

**Comment by Dream-Master** [comment]
5x nuke I can change but fluid I can't.  If I change it the fluid will quicker be pumped and nuke can be explode if lag incoming. @SirAzazel or is there a hidden config I don't see. Test it for me and show me the eu values that I know what it affect. Then I can change it.

**Comment by Lainiel** [comment]
@SirAzazel It's already almost like that after the changes Technus made. Nuclear reactor doesn't make 5x more hot coolant, but large heat exchanger makes 5x more steam from that hot coolant so the boost just got pushed from the reactor to the heat exchanger. And even if we nerf the EU reactor to 4x it's still 8x more than what the reactor planner shows. That's why I'm for 2.5x because that makes a 100EU/t single block EU reactor from the planner make 500EU/t which I think is just alright given how little stuff you need to make one and keep it fueled.

### For comparison:
![reactor](https://puu.sh/xQWr4/f42a513d47.png)
This reactor would make:

| Reactor planner | Current settings (10x mode) | 4x mode | 2.5x mode |
| --- |  ---  |  ---   | --- |
| 100 EU/t | 2000 EU/t | 800 EU/t | 500 EU/t |

Keep in mind that this is a single block reactor that doesn't need any maintanace and has no risk of exploding. All you have to do is change the fuel rods.
#
Also this change is not actually nerfing nuclear energy at all, it's actually making it more attractive. Before you couldn't make fluid reactor, because the only viable turbine that could handle enough steam coming from the heat exchanger was a Large Trinium Turbine, which required you to get to tier 5 planets.

Right now with those loose turbines it shouldn't be a problem to make a fluid reactor that makes more than 20 000 EU/t right around HV/EV age. It's just gonna take some effort, a bunch of multiblocks and isn't completely risk free if your cooling gets stuck.

**Comment by SirAzazel** [comment]
^this sounds very decent and balanced to me, ill add my vote to it

**Comment by Dream-Master** [comment]
@SirAzazel 
@Lainiel 
Sure i can change the multipler to 2.5 but i have the feeling Nuclear power is more powerfull(in real life) then it is in the game. Sure real life is not mincraft but are you sure single block nukes with 2.5 multipler and fluid rectors how Technus set is are enough for powering all stuff in this Tier?

**Comment by MineAnPlay** [comment]
I would agree on 5x (since for some reason the 10x is acting like 20x so this will be the ACTUAL value that was planned).

**Comment by Dream-Master** [comment]
But then we need to promote the fluid one more? @MineAnPlay @Technus
