### ISSUE TITLE
[Quest] Move Precision Laser Engraver quest to MV

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2031]
#### Which modpack version are you using?

2.0.0

#
#### What do you suggest instead/what changes do you propose?

Precision laser engraver isn't useful anymore at LV, and is  waste of resources/time. Move it to MV instead.  The MV version is necessary for Thaumcraft progression - must use it to make Arcane stone bricks for the essentia distiller.

**Comment by Dream-Master** [comment]
Sure will look into it.

**Comment by Dream-Master** [comment]
This Quest is optional and i change the text. There is a Mv laser engraver in MV Tier allready.
