### ISSUE TITLE
Cant craft gregtech tools (Pickaxe Axe Sword etc)

### ISSUE THREAD

**Issue by AtPMonster** [GTNewHorizons/NewHorizons#2032]
#### Which modpack version are you using?
Gregtech New Horizon
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
Cant craft gregtech tools
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Let us craft em.
![20170929_063145](https://user-images.githubusercontent.com/32396064/31024730-47414f04-a540-11e7-961d-8616b1258668.jpg)
![20170929_063151](https://user-images.githubusercontent.com/32396064/31024729-47411642-a540-11e7-9b9e-23b0e5e7e1f8.jpg)

**Comment by Dream-Master** [comment]
Will check it.

**Comment by Dream-Master** [comment]
Ok they be removed. Did we really need gt tools?

**Comment by Bryfer** [comment]
Only the GT flint tools are craftable. After that you are meant to use tinkers'construct tools which is better than gt tools anyway

**Comment by Drobac** [comment]
The Gt tools have been disabled in favour of the TConstruct tools which work better with GTNH progression system

**Comment by Dream-Master** [comment]
@Bryfer @Drobac working right now to add the tools to the assembler only at a x tier. Good or bad idea ?

**Comment by Dream-Master** [comment]
ok i will remove tool parts
