### ISSUE TITLE
[Suggestion] Add Fish oil recipes to all pam's harvestcraft fish

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#2034]
#### Which modpack version are you using?
2.0
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/30208401/31041314-00d5021a-a561-11e7-838e-8a199367d116.png)
Right now, you can get fish oil from pam's harvestcraft fish, but *only* if you craft them into raw fish first. You can get seed oil and fruit juice directly in the fluid extractor, and I suggest that you can get fish oil from all the different pam's harvestcraft fish as well.

**Comment by Dream-Master** [comment]
Yes will add it.
