### ISSUE TITLE
Indium

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2035]
May be add indium to high tier planet? Centrifuge from planet stones(low %), or add indium small ore, or add recipe for UU matter, or add recipe for fusion reactor.

**Comment by MineAnPlay** [comment]
The purpose of Indium is supposed to be hard to make and requires at least a quarry to mass produce it in large numbers. It's not too hard just requires alot of setup and resources. Maybe a Fusion recipe but even that I don't think is needed, a quarry will produce enough ores for it and produce it that way seems more fun :P.

**Comment by boubou19** [comment]
Ok then but then why keep indium ore in nei? this make non sense.
