### ISSUE TITLE
Unable to make advanced golems

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2036]
#### Which modpack version are you using?
 2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?

I am trying to turn my thaumium golems into advanced golems. According to the book you do this with arcane infusion which I have set up. When I go to right click the infuser it does nothing. It isnt like I havent done arcane infusion before so I am fairly sure I am not messing up myself.

![2017-09-30_14 32 17](https://user-images.githubusercontent.com/24741793/31048516-6c5a1580-a5ec-11e7-8450-98508997dc18.png)
![2017-09-30_14 32 24](https://user-images.githubusercontent.com/24741793/31048518-6e544d4c-a5ec-11e7-9789-29f370a5e7b2.png)
![2017-09-30_14 32 30](https://user-images.githubusercontent.com/24741793/31048519-700a5c94-a5ec-11e7-9ab9-e8eccc78d61b.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
i dont change the recipe.
