### ISSUE TITLE
deepdark ore additions and issue with the dimension as a whole 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2037]
With the 2.0 update, the deepdark portal got much, much, harder to make. You'll need at least a t6 rocket, but now you also need 4 infinity ingots, and a UV extruder. Because of the high entry cost, I think there should be a few slight ore changes to the DD. For one, I think cassiterite veins should spawn, as well as mica veins. Both of those veins are overworld only at the moment, which is a huge pain in the ass, especially with servers sometimes not allowing quarrying in the OW. I also think neodynium veins should spawn. You need the ore for EV parts, so I think it's fair to have it spawn in a UV dimension. Lastly, I think you should add either realgar, or an arsenic ore to the DD, because of how much you need that ore, and how early game it is now. 

I do have a question though. The portal needs infinity ingots, which need infinity catalysts, which come from infinity catalyst ore, which comes from the deepdark. Is it found somewhere else as a small ore? 

Last thing, this isn't a suggestion, but on servers the deepdark is awful. When you load a new area for the first time, it seems to crash the server, in a very weird way. I don't know exactly what it does, but Toperoco from dirthuts should have a better understanding of it than me, as he witnessed all 7+ crashes it caused. 

Completely unrelated, but I just ran into this. I think you should add a circuit needed for making styrene-butandiene rubber, because if you're making it all with 1 large chem reactor, having sulfur and O2 in the same reactor will make sulfur trioxide instead of making the rubber. The O2 is needed to make the styrene-butandiene dust, but gets used for sulfur trioxide instead

**Comment by Drobac** [comment]
The whole point of the DD was that it is only reachable after you have a T8 rocket. The fact it was available at T6 before was a mistake in tiering. The dimensions does need some new ore mixes though

**Comment by benstuwie** [comment]
Right, but do you need a t8 now? You need small infinity catalyst ore, but where does that come from?

**Comment by Drobac** [comment]
Centrifuging alpha centauri stone dust

**Comment by benstuwie** [comment]
ah right, forgot about that

**Comment by Dream-Master** [comment]
Will see what i can add more. My probelm is i have only 4 or 5 ore mixes left before full. 
And i can only have one ore(lets say tin) in a mix as primary or secondary product. If i add a new mix with tin it is not possible.
If i enable the tin mix from vanilla in DDDim i guess this is not balanced because the other mixes are more common but i will check it.

**Comment by benstuwie** [comment]
Tin isn't that necessary because there are other dimensions that have tin that you can quarry. If you can, I'd personally say the most important ore to add to the DD would be mica. You need it for ebfs and some other things, but can't really quarry for it on a server. What about a cassiterite/mica vein, and a neodynium/apatite vein? I think that covers most things the DD is missing

**Comment by Dream-Master** [comment]
sure will check if and how i could add it.

**Comment by Drobac** [comment]
With the new assembly line and circuit recipes there are a few mixes that aren't needed in the DD anymore. Will check to make sure when i catch some free time

**Comment by Dream-Master** [comment]
Ok casseterite/mica and neodymium/apatite added.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31182001-ff2f0e90-a922-11e7-9b2c-f10a2c552671.png)
![image](https://user-images.githubusercontent.com/2970688/31182010-0477cac2-a923-11e7-9571-0d2c083f9acb.png)

**Comment by benstuwie** [comment]
Thank you Sir Dream. If there's any left, I noticed that there also isn't any barrite or realgar. Realgar is needed now, just because of gallium-arsenic. I'd love a pure arsenic ore, but at the same time, realgar includes sulfur too, which there isn't an ore for. 
(barrite needed for superconductors, arsenic needed for gallium-arsenic circuit things, sulfur needed for sulfuric acid/rubbers (it is renewable, but it's also nice to get it as a byproduct). I think with those 2, it covers all the needed ores, at least all that I can think of. 

I'm not sure if this is something new, or I just got really lucky, but oregen in the DD in general seems to greatly increased, with blackplutonium being really frequent. I got about 150k dust in about 2-3 days of quarrying. Not sure if that's intended, but I have more avaritia neutronium than I know what to do with.

**Comment by Dream-Master** [comment]
The oregen code us rewritten please test with 2.0.1.0 when out.

**Comment by Radst0ne** [comment]
What about adding a mod that adds some miner which mine them out of the "void" like the excavator from immersive engineering or Environmental Tech

I know that IE is compatible with mintweaker so you can add and remove veins, change amount of ores etc. for without needing them to add to the world Generation
