### ISSUE TITLE
Heavy Duty plates - assembler recipes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#204]
The recipes use too much molten metal, takes additional 4 ingots for 1 plate, which is a bit much considering the metals it uses (Titanium, Tungsten, Tungsteel and Chrome atm). Just the power requirements for making those are insanely high (not mentioning the ammount of mining that woulnd need to be done) and you dont get the required power generation untill you get naquadah generators. Would be good to revert to old recipes which were half an ingot per plate ( used to be 4 bolts )

**Comment by Dream-Master** [comment]
I not remember the old recipes any more. So you want reduce the  molten  metal you need ?
Now chrome use 576 also 4 Ingots. I can set it to 144.

**Comment by Drobac** [comment]
think that to about tungsteel so tier III i think you should leave it at half an ingot, 1 ingot maximum. And scale after that. Because tungsteel is a pain to make. Later with chrome you get the chrome vein so much easier to get, i would start tiering with chrome

**Comment by Dream-Master** [comment]
Change and done.
