### ISSUE TITLE
Twilight Progression Softlock

### ISSUE THREAD

**Issue by V2LenKagamine** [GTNewHorizons/NewHorizons#2040]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion GTNH
#
#### What did you try to do, and what did you expect to happen?
Killed naga, achievement did not unlock upon picking up scales,but lich tower DID unlock.
#
#### What happend instead? (Attach screenshots if needed)
The lich tower unlocked, but because I don't have the achievement, I was unable to progress to the swamp/Minotaur after killing the lich, softlocking magic progression.
#
#### What do you suggest instead/what changes do you propose?
Twilight forests default gamerule for "Forced Progression" be turned off

**Comment by Dream-Master** [comment]
I can't this is locked in tf code. Just kill another naga and report if this helps.

**Comment by Dream-Master** [comment]
@V2LenKagamine did it work? I need an update on this.

**Comment by V2LenKagamine** [comment]
Yep, twilights just stupid. Sorry.

**Comment by Dream-Master** [comment]
Did it work after you killed a second naga ? @V2LenKagamine

**Comment by Dream-Master** [comment]
@V2LenKagamine i close this now and wait for your answer.
