### ISSUE TITLE
Jobs Shop Suggestion

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2041]
#### If in multiplayer; On which server does this happen? 
Epsilon
#

One of the common use cases for World Anchor is when we put a pump in Oil vein and then leave. It constantly consumes your World Anchor for 12/24/36 hours unless you turn it off. Or you have to wait for example 15-45 minutes for your Tank/Drum to be filled. Both of these gameplay options are not very fun.

What if we add more Coins? For example 15/30/45/60 minutes? Or add only 15 minutes Coins and make 30m Coin craftable of 2 * 15m Coins?

So whenever we need to fill a tank with Oil. We can TP to our oil vein. Put a tank, a coin for example with 15 minutes and then Continue doing your job in the main base. So no matter even if your tank got full, you won't waste a lot of World Anchor, because it will stop in 15 minutes.

**Comment by Dream-Master** [comment]
@bigbass @namikon

**Comment by repo-alt** [comment]
Anchor can be turned off by the redstone, and it keeps remaining time when picked up.

**Comment by Dream-Master** [comment]
Not an issue anymore ? @repo-alt

**Comment by repo-alt** [comment]
More like - never was. But maybe I'm missing something.
