### ISSUE TITLE
Dire crafting table doesn't need 144 diamond screws

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2043]
#### If in multiplayer; On which server does this happen? 
Epsilon
#
This quest NASA Workbench aka Dire Crafting Table in 1 step asks you to get 144 Diamond Screws. And in the nest step it asks you to craft Diamond Lattice. But this Diamond Lattice can be made without any Diamond Screws. So people who have Forming Press, don't need these 144 Diamond Screws. Please remove them from quest requirement.

**Comment by Dream-Master** [comment]
Maybe a quest mistake. Will check
