### ISSUE TITLE
Advanced Macerator (MV) recipe only allow IC2 diamond not gt

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2044]
#### Which modpack version are you using?
2.0.0.0

#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
Title basicly says it. The recipe for the MV macerator does not allow for any diamonds other then the IC2 one. This is different from basically any other diamond base recipe so I think this is a mistake.

#
#### What do you suggest instead/what changes do you propose?
That all forms of regular diamonds can be use to make mv macerator.

**Comment by AlphaApotheosis** [comment]
I think this is intended - the industrial diamond is gated by the implosion compressor, so MV+ higher level macerators require you make the implosion compressor first.

**Comment by Pockyninja** [comment]
That is pretty stupid. Why make new diamonds that have no real extra value when you already have diamonds. This just requires you to turn your normal diamond into dust, then use the implosion compressor to get back the diamond you just had. When talking about other recipes they use the different diamonds interchangeably so long as they are normal diamonds (not talking flawless or the likes).

It is not like if you didnt have this unnecessary extra step the implosion compressor would lose meaning since you at bare min need it for making your spaceship.

**Comment by Dream-Master** [comment]
Original gt recipes. make a better suggestions but a diamond i will not add.

**Comment by Pockyninja** [comment]
Since using it interchangeably like with every other recipe isnt something that you are interested in. Why not having a higher level diamond usable like a flawless one. Paying with a higher version should suffice for the difference of not having to reform the diamond you already had.

**Comment by Dream-Master** [comment]
Sure i dont like the industrial damnd too. I could add a flawless or higher tier diamnd too.

**Comment by AlphaApotheosis** [comment]
I recommend allowing an exquisite diamond instead of an industrial diamond.

**Comment by MineAnPlay** [comment]
Keep it as is. Industrial diamonds are very easy to make and when you sift ores you get dust so you aren't wasting your diamonds for it.

**Comment by AlphaApotheosis** [comment]
On second thought, yes I agree with @MineAnPlay that we should keep it as is. The higher level macerators are significantly more powerful with more outputs and gating by the implosion compressor makes sense.

**Comment by Dream-Master** [comment]
ok.
