### ISSUE TITLE
Building Made Easy needs Voidstone Requirement to be removed or recipe changed.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2045]
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
The quest Building made easy is now way too hard with the changes of Eye of Ender being a HV Chemical Reactor it makes it almost silly as making the wand itself is about 100 times easier and more early to make.

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
I suggest either make Energised Voidstone be 8 stone and 1 ender pearl (recipe is free) or remove Energized Voidstone as one the requirements.

**Comment by Methes** [comment]
See #1990
