### ISSUE TITLE
Recipe of Control Unit from OpenComputers.

### ISSUE THREAD

**Issue by Jelmazmo** [GTNewHorizons/NewHorizons#2046]
#### Which modpack version are you using?

2.0

#### What do you suggest instead/what changes do you propose?

It is very strange that almost all components for OpenComputers crafts simple with 32 EU except Control Unit, which is crafted at least with any elite circuit from GregTech that requires 2400 EU at least. As a result, we can`t make any working computers until 2048/8192 at least, lol.

What I suggest: maybe consider to lower requirements for OpenComputers to 32/128 EU or lower them to 512 but add TIS-3d as an "low-tier computer with *asm, much weaker but possible for automation too"?

Just for example for second variant - attaching my own MineTweaker script file for TIS-3d on my own local pack.

[tis-3d.txt](https://github.com/GTNewHorizons/NewHorizons/files/1349159/tis-3d.txt)

**Comment by Dream-Master** [comment]
Open computers isnt tweaked by me right now but @Henny022 working on it.

**Comment by Jelmazmo** [comment]
Well I saw recipe suitable for 512 but it is almost strange thing - all is cheap in EU Level instead of this thing. How can I contact with him? I am not often using github but there no any features like pm or other and his projects are seems stalled in comparison with this one.

**Comment by Dream-Master** [comment]
@Henny022

**Comment by Henny022** [comment]
the OC recipes currently in the pack are not tweaked at all, so they are the default gregtech recipes, which are complete crap.
I'm almost done with the new recipes, so i think, they schould be in one of the new major updates.
EU Level is one thing i have not done at all at the moment, but first computers will be available at MV tier.
If you want to contact me, you could visit me on my ts3 server (ts.henny022.de) for example

**Comment by Jelmazmo** [comment]
@Henny022 Thank you for your comment, I think this topic may be closed :)
