### ISSUE TITLE
Laptronic Crystals - Require Advanced Circuits - No options

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2047]
#### Which modpack version are you using?
Gregtech New Horizon

#
#### If in multiplayer; On which server does this happen? 
dirthuts

#
#### What did you try to do, and what did you expect to happen?
Laptronic Crystals need to be made in the Assembler with _only_ Advanced circuits.  No option to use other circuits

#
#### What happend instead? (Attach screenshots if needed)
N/A

#
#### What do you suggest instead/what changes do you propose?
Raw Laptronic Crystals should have multiple recipe options like other products

I tried to find the .zs file to provide the recipe directly but this may be hard coded, the IC2:itemBatLamaCrystal is removed in ic2.zs and pulverizer is there.  no direct recipes to creating.

**Comment by Dream-Master** [comment]
The original ic2 recipes had only ic2 advanced circuits in the recipe. I could add all circuits from this tier. @devanchya Will this helps?

**Comment by devanchya** [comment]
That would make the recipe more in line to the use.   Otherwise the Quad-Lithium Batteries from GT++ become much more affordable.

**Comment by Dream-Master** [comment]
Sure will add more circuits.

**Comment by Proha5** [comment]
Probably the player have old version of the modpack?
My version 2.0.0 I can create lapotromic crystal using "Nanoprocessor".

**Comment by Dream-Master** [comment]
@Proha5 yes it works but nei not show it.
