### ISSUE TITLE
Assembler recipe for trapdoors gives Malisis' Doors instead of standard doors

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2048]
#### Which modpack version are you using?
2.0.0
#
#### What did you try to do, and what did you expect to happen?
Trying to create trapdoors so I can put them in the arcane alembic to get motus. NEI shows a fast assembler recipe.
#
#### What happend instead? (Attach screenshots if needed)
Assembler outputs incorrect trapdoor, doesn't have motus aspect.

#
#### What do you suggest instead/what changes do you propose?
Change assembler recipe to match NEI. Add motus to Malisis trapdoors.

**Comment by richardhendricks** [comment]
![2017-10-03_02 38 03](https://user-images.githubusercontent.com/1214811/31114579-6440d31c-a7e4-11e7-9684-b62cbe21fc52.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
So far i know ou need oak to make vanilla trapdoors. The other Trapdors from Malis doors are made out of different woods the oak.

I will add Motus to all doors.

**Comment by Dream-Master** [comment]
Vanilla Tap doors using Oak now in shaped recipes too.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31174700-bff0b05a-a90c-11e7-8b38-2fdb1fb26f70.png)

**Comment by richardhendricks** [comment]
Thanks
