### ISSUE TITLE
AE2 can't put microprocessor in forming press

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2049]
This autocraft work:
![default](https://user-images.githubusercontent.com/29812448/31119484-97c4e710-a874-11e7-96b0-b6a00c5e4666.png)

But this craft work only manualy. AE2 can't put microprocessor in forming press.
![default](https://user-images.githubusercontent.com/29812448/31119597-da594562-a874-11e7-9d54-8f7829e55ae3.png)

**Comment by Dream-Master** [comment]
i guess there is something not linked or the output/input slots are not setted right.

**Comment by Dream-Master** [comment]
@Proha5

**Comment by Dream-Master** [comment]
@Proha5 any news here?

**Comment by bartimaeusnek** [comment]
old issure, new recipe, no news from the author.
