### ISSUE TITLE
Solder IO

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#205]
Make updates in Technic Launcher via http://solder.io/

**Comment by Namikon** [comment]
@Dream-Master If you have some spare time today, we can look into the solder installation i've done. It will take about 30-45 minutes to explain how it works, and then we probably could test-drive it with a few small test-modpacks. Looks pretty promising so far, a lot of work to setup and maintain, but tbh it's really worth the effort

**Comment by Dream-Master** [comment]
I be there later on 6 or 7.

**Comment by Dream-Master** [comment]
I am on it and with the next update i will use it
