### ISSUE TITLE
Empty Shape Plate in Bending Machine

### ISSUE THREAD

**Issue by braeven** [GTNewHorizons/NewHorizons#2050]
#### Which modpack version are you using?
2.0.0.0
#

#### What did you try to do, and what did you expect to happen?
Making an Empy Shape Plate with the Bending Machine needs 8x Quadruple Steel Plate, Making one with the Tinkers Smeltery takes only 4 molten steel.

#

#### What do you suggest instead/what changes do you propose?
Make the Bending-Machine only use one Quadruple Steel Plate instead of 8, it's way to overpriced currently

**Comment by Dream-Master** [comment]
will check i not known about such recipe.
