### ISSUE TITLE
DE Draconic core recipe missing

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#2052]
#### Which modpack version are you using?
Any latest, issue exists in current commit.

#
#### What did you try to do, and what did you expect to happen?
So Pro5 made legendary bag and wanted to enchant it, which require draconic cores
#
#### What happend instead? (Attach screenshots if needed)
But recipe for them is missing and seems like only way to get them is by opening legendary bags which arent renewable and have very small chance to give them.

#
#### What do you suggest instead/what changes do you propose?
Adding recipe to them in script, something hard but possible on that tier.

---
### There is 16 recipes with them, 
meaning that you will need to get them at least twice to get all those items or 3 times to get 8 enchanted legendary bags, in short that means that you will probably need more than 1 stack of legendary bags that arent enchanted, which i dont think you can get, thus draconic, wyvern, awakened, chaos cores arent possible to get either at all or more than couple of them.

**Comment by Dream-Master** [comment]
It's a quest only item. Repeatable as often you want and have enough resources.

**Comment by SirAzazel** [comment]
good enough for me, was made from work so couldnt test myself.
