### ISSUE TITLE
Quest-link

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2055]
#### Which modpack version are you using?
delta one
#
#### If in multiplayer; On which server does this happen? 
Delta, multiplayer
#
When quest #543 completes, it triggered unlocking of MV page, with no(almost) quests available.
![2017-10-06_14 51 12](https://user-images.githubusercontent.com/25028786/31276691-e25ad932-aaa5-11e7-8322-b6adceb6a35b.png)
![2017-10-06_14 51 18](https://user-images.githubusercontent.com/25028786/31276690-e21eff70-aaa5-11e7-943a-427da5ae7a59.png)

**Comment by Dream-Master** [comment]
Ok overseen some quest maybe. Will look if I can fix it.

**Comment by Dream-Master** [comment]
Seed oil seems have the same problem. Hard to fix. I dont want the Quest Book looks like a Spider net.
