### ISSUE TITLE
Bricked blast furnace automation

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2056]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta, multiplayer
#
#### What did you try to do, and what did you expect to happen?
Automate Bricked blast furnace with EI item conduits
#
#### What happend instead? (Attach screenshots if needed)
Item counduites with mode "insert" inserts things in ALL slots, even the output slots.
Item counduites with mode "extract" can't extract steel from first output slot.
![2017-10-06_16 02 44](https://user-images.githubusercontent.com/25028786/31283172-951f4eb0-aabd-11e7-8c02-fea990629e5d.png)

**Comment by Bryfer** [comment]
The old bronze blast furnace was not meant to be automated, does the bricked one have the same feature?

**Comment by Cinobi** [comment]
If it must not be automated - it must not interract with automations atall, isn't it?

**Comment by SirAzazel** [comment]
magic of 'straight' hands. Pic related, but meant only for russian speakers.
![хуяк, хуяк и в продакшн](https://user-images.githubusercontent.com/5310658/31283420-3a88bd5a-aabe-11e7-8f96-856f2ad2e99e.png)

**Comment by Dream-Master** [comment]
Not for automation. Use EBF.
