### ISSUE TITLE
New Quests for Coin usage

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2058]
Technic Coins:
- [x] motors, conveyors, pistons, pums, robot arms, emitters, sensors, circuit parts

Chemist Coins:
- [x] oxygen, nitrogen, hydrogen etc

Bee Coins:
- [x] Bees: pristine bee's
- [x] Hives or Frames for Beekeeper Coins

Food Coins:
- [ ] good food,

Forestry coins
- [x] wood saplings etc

Thaumcraft Coins:
- [ ] essentia
- [ ] All Aura Nodes for The Dark Wizard Coins

Blood Coins:
- [ ] blood magic stuff

Survivor Coins:
- [x] Spawn Eggs for The Survivor Coins

Explorer coins:
- [ ] Maybe Ores

Black Smith Coins
- [ ] Creativ Modifier Tinkers für Quest Coins (at a very high Tier)

NEW QUESTS:

Make a Chapter with Pams Harvestcraft Quest. Like a cooking course.

**Comment by joflashstudios** [comment]
I'm very excited for this.

**Comment by KaneHart** [comment]
This for me will be the sort of big special feature that comes from version to version :) More quests and finally a way to spend coins who can ever say no!

**Comment by Dream-Master** [comment]
we can reopen it or make a new issue if needed.
