### ISSUE TITLE
The Transcontinental Railroad quest! Nerf Request. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2062]
#### Which modpack version are you using?
2.0.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
The Transcontinental Railroad under Transportation.
https://i.imgur.com/F0IgPPlr.png

The last Item Black Steel Bolt requires you to have MV+ Level and I think it should just be a Steel Bolt to make it LV instead I would recommend. Pretty much Railcraft steam trains start in LV and such.

#### What do you suggest instead/what changes do you propose?
Change Black Steel Bolt to Steel Bolt

**Comment by Dream-Master** [comment]
Balck steel blot can be made in mid lv via ebf coils tier one.

![image](https://user-images.githubusercontent.com/2970688/31315832-93a4e784-ac20-11e7-8970-2fcb1892e5b3.png)

**Comment by Dream-Master** [comment]
Steel would be steam age not lv ok it open lv age.

**Comment by KaneHart** [comment]
It's quite a effort I guess for that transport rail quest. Even if it's considered LV age that is quite higher up anyways. If you want to leave it totally understandable but really iron is the true nature of rails hehe. We just found it quite gated for people who want to work on rails since pretty much you can work on them right at the door of the LV age.

**Comment by Dream-Master** [comment]
I change it to gold bolt.

We have a Railway bride in germany more then 100 Years old an there is a mythos abot a golden bolt inside this bridge. No one found this bolt until yet :)
