### ISSUE TITLE
Going up and down on a Space Station?

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2063]
#### Which modpack version are you using?
2.0.0.0

I don't seem to be able to move up and down on a space station at all. Using jump (space) and sneak (shift) as the Galacticraft wiki suggest does nothing https://wiki.micdoodle8.com/wiki/Overworld_Space_Station.

**Comment by Dream-Master** [comment]
need a graple because you are in space with no gravity

**Comment by Dream-Master** [comment]
said me if you can get down with a graple.

**Comment by Dream-Master** [comment]
@DualBallers i need an update here. If not i close this issue.

**Comment by DualBallers** [comment]
Ya sorry. The grapling hook + string works. 
It is still a weird mechanic that you can move from side to side by yourself when up in the air, but not up and down.
Anyway, just close the question :-)
