### ISSUE TITLE
Lack of indium ore

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2064]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to make HV solar panels, which require indium galium phosphide plates. So i was looking for where i can mine Indium ore. 
#
#### What happend instead? (Attach screenshots if needed)
It appears that the indium ore is not generated anywhere. (i looked in the orespawn spreadsheet and GT achievement descriptions and there is no Indium ore). The only way to get indium is by crafting Indium concentrate:
![2017-10-08_12 22 42](https://user-images.githubusercontent.com/12850933/31315949-7a99df62-ac23-11e7-9a4b-36b15c9efb5d.png)
then use it with aluminium dust:
![2017-10-08_12 25 30](https://user-images.githubusercontent.com/12850933/31315971-cd6472c0-ac23-11e7-81cf-bf04831368ab.png)

#
#### What do you suggest instead/what changes do you propose?
I suggest to add Indium ore in a existing mix or add it as byproduct of some planet dusts

**Comment by Dream-Master** [comment]
No. We have an issue for it and i wont add indium ore.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2035

**Comment by boubou19** [comment]
Ok then but then why keep indium ore in nei? this make non sense.

**Comment by Dream-Master** [comment]
because most of materials have ores. I could disable it if you feel better.

**Comment by boubou19** [comment]
Yes pls because it suggests that people can mine it but they can't

**Comment by Bryfer** [comment]
People Will not look for the ore if there is an quest telling you the proper way to make HV solar panels
Add a quest for solar panels (if there isn't already)

**Comment by Dream-Master** [comment]
Add Indium and HV Solar pannel Quest
