### ISSUE TITLE
[2.0.1.0] Basic Chisel Concrete Recipe now missing (Gravel to Concrete Smelting)

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2065]
#### Which modpack version are you using?
2.0.1.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Smelt Gravel into Concrete
#
#### What happend instead? (Attach screenshots if needed)
No Recipe (No Smelting)
#
#### What do you suggest instead/what changes do you propose?
I'm not sure if this was a on purpose change / nerf. But before you could make Concrete for great early game movement around your base and paths to other bases. It was a great building material as well for ground textures.

You can still make it but now via a very complex and expensive method vs smelting just gravel. 

To make it now you must make the GT Version of Light Concrete then chisel it.
https://i.imgur.com/3FHBSqg.png
https://i.imgur.com/BPsAxSd.png

Once again I have no clue if this is an intentional change or a accidental nerf. Please note though you can easily reverse the recipe and chisel it into GT Light Concrete then pulverize it for concrete dust and get liquid concrete again. Not sure if this might of been the issue? 
https://i.imgur.com/VCwXOpR.png

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Dream-Master** [comment]
But one thing are clear smelting gravel to get concrete was a very cheap an unrealistic recipe. Will see what recipe i can add between gt and the old one.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1984 has the original discussion on this issue.  Gravel to conrete in a smelter is just too easy.  The mixer/fluid solidifier recipe seems reasonable.

**Comment by KaneHart** [comment]
Thanks guys. Was the nerf do to the concrete use in recipes or the movement speed overall? I'm hoping was not nerfed due to it's use in recipes / materials overall it's function for early game nice pathways.

**Comment by richardhendricks** [comment]
No, the movement speed wasn't really a problem (except GT concrete is broken).  It was just felt that gravel in smelter was just too easy to obtain.  If you prefer the Chisel concrete blocks, they are still obtainable via chiseling the GT blocks. The calcite is pretty easy to obtain once you find a ball of marble.

**Comment by KaneHart** [comment]
I decided to close this. After thinking about it the recipe is not that bad.
