### ISSUE TITLE
Nei recipy mistmatch

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2066]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Multiplayer, delta
#
#### What did you try to do, and what did you expect to happen?
i try to smelt arsenic trioxide in EBF with carbone and get 3 arsenic ingots, according to nei
#
#### What happend instead? (Attach screenshots if needed)
i get 2 ingots
#
![2017-10-09_15 37 35](https://user-images.githubusercontent.com/25028786/31338473-1899cc1a-ad08-11e7-9236-e48cf488655b.png)
![2017-10-09_15 37 39](https://user-images.githubusercontent.com/25028786/31338474-189b2678-ad08-11e7-8258-f7531931a97e.png)

**Comment by Dream-Master** [comment]
Will check.

**Comment by Bryfer** [comment]
Is this related to the GT config that only gave 2/3 of ores?
- in they case it's fixed?

**Comment by Dream-Master** [comment]
Not sure thought i disable it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31569783-09d13e06-b07e-11e7-9d53-0fc04c29cfe5.png)
fixed allready
