### ISSUE TITLE
Suggestion. Change recipe

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2067]
ver 2.0 Singleplayer

Ae2 cant craft this recipe.
I tryed ALL settings. Empty, full battery, +-oredict button. Ae2 can't craft recipe contained GC battery.
May be change GC battery to "small battery hull"? GC battery free created from "small battery hull"

![default](https://user-images.githubusercontent.com/29812448/31339190-65b828e2-ad45-11e7-97df-c08c4904fa1e.png)

**Comment by Dream-Master** [comment]
Yes can do

**Comment by ko5h** [comment]
Ae2 can craft this recipe.
for autocraft in ae u need charged battery

**Comment by Dream-Master** [comment]
So does it work the way you show or did i need to change it to full ? @ko5h

**Comment by boubou19** [comment]
I successfully automated it without charging it: i use an auto workbench from BC Factory and with a bit of tinkering that does the trick ;)

**Comment by ko5h** [comment]
@Dream-Master i not changed recipe..it work your stable recipe 
shaped craft has 2 recipes empty and full battery...autocraft in AE only full battery
Proha5 say "I tryed ALL settings"...not all (so more correct)...
p.s. @boubou19 not bad... i like it ;)

**Comment by Proha5** [comment]
yes, i not tryed "charged battery" + "no ore dict substitute". Only this settings works fine.
Cancel suggestion.
