### ISSUE TITLE
WAILA recommends extremely high shovel mining level to mine moon ores

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2068]
Many ores found on the moon have unusual mining levels and suggested tools, like this galena 

![galena](https://user-images.githubusercontent.com/11035501/31340103-6ab3f550-ad05-11e7-809d-1508d223bb87.png)

Sais mining level 06 and to be mined with a shovel. Using a mining level 06 shovel does indeed work to mine this ore quickly, but a pickaxe with mining level 06 also works. I found many other examples (titanium shovel 04; perlite shovel 05; chalcopyrite pick 07), so some ores/properties are not being generated correctly. When these ores are mined and placed again, they take on the expected property, the galena from the screenshot goes to level 03 pickaxe, hardness 4.0 blast resistance 0.0

This behaviour has not been reported in any other dimension yet.

DirtHuts server, v2.0.0.0)

**Comment by ko5h** [comment]
Duplicate of #2059

**Comment by Dream-Master** [comment]
@Toperoco @ko5h its better to disable the mining level in waila ?

**Comment by Bryfer** [comment]
@Dream-Master the best thing to do would be to close dupe issues and ask questions in the first thread instead

**Comment by Toperoco** [comment]
Yes this is a dupe, sorry. Gemlord had problems making an issue here but it seems he managed after all.
