### ISSUE TITLE
Manual detect for "A mountain of copper"

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#207]
Shouldn't the *A mountain of copper* subquest in the *Time to get some steel* multiblock quest have manual detect just like the *Iron Plates* following it?

To fulfill the condition currently the player must craft (i.e hammer) all the plates. They can surely be obtained by the forge hammer/alloy smelter at this stage.

**Comment by Namikon** [comment]
True, that makes a lot more sense. Will look into that

**Comment by Namikon** [comment]
I changed the quest to "Detection" Task. Should be online with the next update martin does
