### ISSUE TITLE
EBF tooltip

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2071]
#### Which modpack version are you using?
Deltaone
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Tooltip need to be fixed - 
"Each 900k over min capacity grants 5% speedup" need to be "Each 900k over min capacity grants 5% reduced energy consumption" or something like this.
![2017-10-09_22 30 26](https://user-images.githubusercontent.com/25028786/31355526-5334a094-ad43-11e7-9357-4ef1877b8aa9.png)

**Comment by bigbass1997** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/commit/b85dad4b1ff41940fc1a589ba91734e956bdf938

**Comment by Technus** [comment]
Sorry too complicated

**Comment by Technus** [comment]
Oh, didnt noticed my commit
