### ISSUE TITLE
[2.0.1.0] Obsidian Turret causing NP with Ticking entity's.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2072]
#### Which modpack version are you using?
2.0.1.0 Mod Causing Issues: UtilityMobs
#
#### If in multiplayer; On which server does this happen? 
StoneLegion
#
#### What did you try to do, and what did you expect to happen?
One the users said they placed down an obsidian turret near a skeleton farm. Though the odd thing is the crash does not seem to be turret as much as the entity. It seems to have triggered an issue with the entity meaning the second the chunks are loaded the world crashes instantly. Right now I might have to try to MCEdit the entities out of the region but hoping to look for other solutions.

#
#### What happend instead? (Attach screenshots if needed)
Crashed:
https://pastebin.com/N4hN1vU1
#
#### What do you suggest instead/what changes do you propose?
Magic, Sadly I don't know if this one can even be fixed or repeated easily. 

We fixed it by removing UtilityMobs. The Golem was created a turret one and yeah. Done and over I see no need for the mod myself so we removed it from our server.

**Comment by SirAzazel** [comment]
Error in this fuction (fernflower):
```java 
public void func_75246_d() {
      this.golem.func_70671_ap().func_75651_a(this.target, 30.0F, 30.0F);
      if(this.golem.func_70681_au().nextInt(40) == 0) {
         if(this.golem.func_70681_au().nextInt(2) == 0) {
            --this.golem.golemAttackTime;
         } else {
            ++this.golem.golemAttackTime;
         }
      }

      if(this.golem.golemAttackTime <= 0) {
         this.golem.doRangedAttack(this.target);
         this.golem.golemAttackTime = this.golem.maxAttackTime;
      }
   }
  ```
In fern line 49 falls on }else{ part.

**Comment by Ugachaga** [comment]
My vote to get rid of the mod.

@SirAzazel [sources available](https://github.com/FatherToast/UtilityMobs/blob/master/src/main/java/toast/utilityMobs/ai/EntityAITurretAttack.java#L49).

**Comment by Dream-Master** [comment]
If no one use it i could remove the mod. 
I added the mod long time ago. Have some early game Golems that protec you and your base.

**Comment by Ethryan** [comment]
I never even knew this mod was in the pack.

**Comment by SirAzazel** [comment]
@Ugachaga my bad, went for decompiling straight away since had jar around
Also mod removal might be a good idea
