### ISSUE TITLE
[2.0.1] Nitric acid change for ore processing not consistent with electrolyzer recipes

### ISSUE THREAD

**Issue by AlphaApotheosis** [GTNewHorizons/NewHorizons#2074]
Previously processing Chalcopyrite/Pentlandite purified crushed ore with 8000mB Nitric Acid produced 9000mB Vitriol, which can be electrolyzed to the metal dust + 8000mB Sulfuric Acid. 

New recipe is 1000mB Nitric Acid (this is a good change, makes ore processing this way viable) but still produces 9000mB of liquid (Copper/Nickel Sulfate) which still is electrolyzed to 8000mB Sulfuric Acid. Does not make sense with reduced nitric acid recipe.

![image](https://user-images.githubusercontent.com/30811906/31400260-f2180218-adbc-11e7-92d0-bb087b8924a6.png)

Suggestion: This recipe should produce 1000mB Copper or Nickel Sulfate, which can be electrolyzed to 1000mB Sulfuric Acid +  the metal dust.

**Comment by Dream-Master** [comment]
It make sense Prurified Pentlatite Ni8S8 + 1 nictic assid makes 9 nickel sulphate water

**Comment by AlphaApotheosis** [comment]
Does that make sense? Real chemical recipe for pentlandite is (FeNi)9S8. Chalcopyrite is FeCuS2. I don't think it makes sense to use these formulas to make the recipes.

Old recipe was 8 acid + 1 purified ore = 9 sulfate = 8 acid + 1 metal

New recipe changed to requiring 1 acid, so should be 1 acid + 1 purified ore = (1 or 2 sulfate) = 1 acid + 1 metal

**Comment by Dream-Master** [comment]
@AlphaApotheosis better now. I change the amount to 2000.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/6f527fae66030c8401d9774954d2d09a010d74a5

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/58de5df57626d8bb5681d30ebea72760bcc02d2b
