### ISSUE TITLE
[Quest] Advanced nano chestplate

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2075]
#### Which modpack version are you using?
2.0.1.0

Refering to #1938 
The Advanced Nano Chestplate still has the incorrect set of items needed in the quest book :-)

![image](https://user-images.githubusercontent.com/30087707/31402274-ce724286-adf5-11e7-95c3-178e34842654.png)

![image](https://user-images.githubusercontent.com/30087707/31401887-8e6e0950-adf4-11e7-8746-3245b5ae154d.png)

And by the way - why does the lower tier Advanced Electric Jetpack require a Mainframe, when the higher tier Advanced Nano Chestplate only requires a Workstation chip?
Look at the crafting grid, I think the two have been mixed up.
Advanced Electric Jetpack should require Data/Extreme and Advanced Nano Chestplate should require Elite circuits.

![image](https://user-images.githubusercontent.com/30087707/31402148-6c1e4e40-adf5-11e7-8736-6609f4bf6f77.png)

**Comment by Dream-Master** [comment]
Yes need to fixit.

**Comment by Dream-Master** [comment]
did you update your questfile ?
/bq_admin default load 
@DualBallers

**Comment by DualBallers** [comment]
Yes, that's the first thing I did. 
However, the error is in the crafting grid, not in the quest book.

**Comment by Dream-Master** [comment]
I could change it to the composite suit but the circuit and the carbon plates to low for that tier.

**Comment by DualBallers** [comment]
It is just to avoid needing the same armor piece twice for two different jetpack tiers (and the quest book only asks you to make the armor once, and only points towards the higher tier jetpack).
Maybe there is another armor tier that fits the Adv. Elec better?

**Comment by Dream-Master** [comment]
Yes i will rewrite the recipe for the next update.
