### ISSUE TITLE
Thaumcraft confusing questing path

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2077]
#### Which modpack version are you using?
2.0.1.0
#
#### If in multiplayer; On which server does this happen? 
Tested in SP, Creative
#
#### What did you try to do, and what did you expect to happen?
Tried to figure stuff out, was confused af since that quest is not affected to the others at all.
See pictures below, hopefully my drawings makes more sense than me.

Since I did not make alot of sense that way..
the Quests; Lich Bone, Iron capped Greatwood Wand and A "Greater" wand
is not connected to 
the Quests Better screws and "Stores 50 vis" wand"

Quest Iron capped Greatwood Wand (id 798) requires..
ID 236 and 234 to be completed

"Stores 50 vis" wand (id 237) requires only Better screws (id 235) to be completed, 

and you have no idea of how to progress in thaumcraft after Iron capped Greatwood wand quest until you reach Stainless Steel (HV tier) since you need to complete Stainless Steel EBF processing to unlock Better screws

![image](https://user-images.githubusercontent.com/22825059/31422088-d6f29720-ae4b-11e7-9c10-07287b2bd53f.png)
#
#### My try to show you what I mean with a picture
![adasd_github](https://user-images.githubusercontent.com/22825059/31422228-903c1a4e-ae4c-11e7-9c1f-69c529bfa1f0.jpg)

#
#### What do you suggest instead/what changes do you propose?
I suggest moving the quests like this instead so its easier to understand the path of the quests.
also is the Iron capped Greatwood wand quest supposed to be connected to the Better screws quest?- or is it meant to be a dead end?
![adasdd_github](https://user-images.githubusercontent.com/22825059/31422299-04c2eed8-ae4d-11e7-85b3-cfc3f6e7f660.jpg)

If nobody understands me Ill give it another shoot at explaining this, just make an comment informing me to do so.. 🖌

**Comment by Dream-Master** [comment]
True thats a bit confusing. Will change it.
