### ISSUE TITLE
Processor machine cassing requere only 1 type circuit

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2078]
ver 2.0.1 singleplayer
I can't craft this item using same tier circuit.
You can find ALL recipes contained circuits, and fix this problem for all recipes contained circuits?
![default](https://user-images.githubusercontent.com/29812448/31426583-4c9951a2-aea7-11e7-9421-238d5fb613d9.png)

**Comment by Dream-Master** [comment]
Need to ordict the recipe.

**Comment by Dream-Master** [comment]
Look at nei and test in the crafting table if you can use other elite circuits too.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31512872-b7ee67fe-af8c-11e7-989b-aca9d79016db.png)
this is nei result

![image](https://user-images.githubusercontent.com/2970688/31512936-e83b3e6e-af8c-11e7-9eb8-ddd1417fa8a4.png)
cafting table
