### ISSUE TITLE
Galaxy Space schematics

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#208]
NASA Workbench doesnt want to accept Galaxy space rocket schematics

**Comment by Namikon** [comment]
Try shift-click them. I think I saw a post from BlesseNTumble in the GC Forum about that

**Comment by Drobac** [comment]
They go in the slot, it just doesnt do anything when i click learn schematic or what the button says

**Comment by Dream-Master** [comment]
Does the Schematics vanish inside the Nasa Workbench when you hit the button? I try it in creative and it works. I will test it later.

**Comment by Drobac** [comment]
it doesnt do anything, just sits there while i rage click the unlock schematic button

**Comment by Dream-Master** [comment]
relaxe i check it

**Comment by Dream-Master** [comment]
It dont work. I try Tier 5,6 and 7 and it works. I have to look what i can do.

**Comment by Dream-Master** [comment]
Not working now. I post it in the Forum and hope Blessnutumble will replay and fix it.

**Comment by Dream-Master** [comment]
Works in update 2.1. In the Next update.
