### ISSUE TITLE
Apiarist Database and Arborist Databases are not craftable according to the NEI recipe

### ISSUE THREAD

**Issue by Nrin** [GTNewHorizons/NewHorizons#2081]
#### Which modpack version are you using?
2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft GTNH
#
#### What did you try to do, and what did you expect to happen?
I tried to craft an apiarist database according to the recipe in the NEI and expected it to work.
#
#### What happend instead? (Attach screenshots if needed)
Neither the arborist nor the apiarist databases are craftable because the carpenter will not accept the beealyzer nor the treealyzer into its top slot. The lepidopterist database is craftable because the carpenter accepts the flutterlyzer into the top slot. 

I tested this on the Prospercraft server as well as a single player world. Neither analyzer had items inside of it.
#
#### What do you suggest instead/what changes do you propose?
Make it so the carpenter will accept the beealyzer and the treealyzer into the top slot.

EDIT: I've discovered upon crafting a new beealyzer that if you try a brand new beezlyzer in the carpenter it will accept it but if you use the beealyzer a single time then the carpenter will not accept it.

**Comment by Dream-Master** [comment]
Have to do with nbt tag i guess. Not sure if i can do there anything but i can add a crafting recipe to remove nbt tag.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31510762-b6e4c774-af85-11e7-97e9-e4221eba048a.png)
