### ISSUE TITLE
Impossible recipe (coblestone structure pipe)

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2082]
v2.0.1 singleplayer
This recipe requere only "coblestone rods". But you can create only "stone rod" (using lathe). Both rods incompatible
![default](https://user-images.githubusercontent.com/29812448/31487638-94835cd8-af7e-11e7-9425-99e189cff9c8.png)

**Comment by Dream-Master** [comment]
will fix.

**Comment by Drobac** [comment]
Try using a regular file, those yielded cobble roda for me, but recipe still needa fixing

**Comment by Dream-Master** [comment]
allready fixed.
