### ISSUE TITLE
Quest change

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2083]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Try to progress in quests :D
#
Quest #838 says to us - "u need copper bolts", but nei says - "u need annealed copper bolts".

Fix can go both ways, but my personal opinion - need to update the quest.
![2017-10-12_22 49 17](https://user-images.githubusercontent.com/25028786/31516086-f2c7ca92-af9f-11e7-99db-0542e89c5648.png)
![2017-10-12_22 49 28](https://user-images.githubusercontent.com/25028786/31516087-f2ef5436-af9f-11e7-91ef-f84418e3b1f2.png)

**Comment by Cinobi** [comment]
Update, to this issue: 

When u try to extrude annealed copper ingots into bolts u recive basic copper bolts.
![2017-10-12_23 03 57](https://user-images.githubusercontent.com/25028786/31516599-c79005d6-afa1-11e7-9fe0-f3d6c36a1139.png)
![2017-10-12_23 03 38](https://user-images.githubusercontent.com/25028786/31516600-c7b8aa36-afa1-11e7-9e03-ba24ea7368ef.png)
![2017-10-12_23 03 43](https://user-images.githubusercontent.com/25028786/31516601-c7deb028-afa1-11e7-89c8-de7f51eae77e.png)

**Comment by Dream-Master** [comment]
will check.

**Comment by Gateswong** [comment]
@Cinobi The same thing happens on "Wrought Iron" + Extruder = "Iron" things.

**Comment by Dream-Master** [comment]
No cant reproduce
![image](https://user-images.githubusercontent.com/2970688/31569642-969506b2-b07c-11e7-85b2-48c2fa477a6a.png)
Annealead copper ingots make annealead copper bolts. I change it allready in 2.0.1.0

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31569662-ccfd255e-b07c-11e7-8370-0b31e6b3a23f.png)
