### ISSUE TITLE
Mod Suggestion: CallowCraft or LunatriusCore + Stackie

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#2084]
I was searching for a xp orb mod like [Clumps](https://minecraft.curseforge.com/projects/clumps) for 1.7.10 and ran across [CallowCraft](https://github.com/hilburn/CallowCraft/releases/) witch seems to offer a similar ability with its grouping radius.

Have not tested the mod.

Otherwise [LunatriusCore](https://minecraft.curseforge.com/projects/lunatriuscore) and [Stackie](https://minecraft.curseforge.com/projects/stackie) usually works well as experience orb lag reduction.

**Comment by Dream-Master** [comment]
We have this mod llong time allready removed from this pack but i dont know the reason.

**Comment by Dream-Master** [comment]
(stakie)

**Comment by KaneHart** [comment]
I have experienced odd dupes in the past using thermos/cauldron etc in the past. I would not trust it with their rewritten stack system from spigot I think?

**Comment by Dream-Master** [comment]
We dont need more mods.

**Comment by Namikon** [comment]
As in additional information for ServerAdmins:
Do **not** use any mod that does auto-stacking of Entities (Orbs, Items,..) if you're running a Cauldron-Based Server hybrid; You will most likely experience Entity-Duping. Cauldron-Based Servers already come with ranged-item stacking build-in, it is one of the lag-prevention measurements
