### ISSUE TITLE
2.0.1.0 LV Tier "Diodes" Quest incorrect

### ISSUE THREAD

**Issue by YalinHawk** [GTNewHorizons/NewHorizons#2085]
#### Which modpack version are you using?

2.0.1.0

#
#### If in multiplayer; On which server does this happen? 

Private server running as-packaged files, no changes.
#
#### What did you try to do, and what did you expect to happen?

The LV quest "Diodes" says to make diodes using molten glass and tin wire in an assembler. Only valid recipes that are showing in NEI are using copper wire and polyethylene. So far as I can tell, I have not yet reached a quest to make polyethylene. There are no hand-crafted recipes for Diodes, only scrapbox and Assembler. Assembler provides 4 possible recipes, all using polyethylene for a fluid ingredient.

![image](https://user-images.githubusercontent.com/10606516/31572422-bbdfad9a-b073-11e7-9644-33c31374fb2e.png)

![image](https://user-images.githubusercontent.com/10606516/31572429-cc43f1dc-b073-11e7-9f5a-e0bad83c994b.png)

![image](https://user-images.githubusercontent.com/10606516/31572431-d3411096-b073-11e7-905f-9e86b88309ec.png)

![image](https://user-images.githubusercontent.com/10606516/31572436-d9d88394-b073-11e7-9b9a-490050fc79c7.png)

![image](https://user-images.githubusercontent.com/10606516/31572438-df7bb3a2-b073-11e7-9823-3e54c9fd1881.png)

#### What do you suggest instead/what changes do you propose?

Restore molten glass/tin wire recipe, or gate quest behind polyethylene production. If polyethylene production is gated for MV/later in game (haven't looked into it yet/havent had a quest for it pop up) then restoring molten glass recipe is preferred option?

**Comment by AlphaApotheosis** [comment]
I think polyethylene should not gate MV chips - after all, MV chips can be hand-crafted. I think we should have a hand crafting recipe for diodes as well. And quest to match.

**Comment by Bryfer** [comment]
From what I can understand from reading the messages in #help (on discord) I came to this conclusion:

There used to be an recipie using the Thermonic Fabricator to craft Diodes.
This recipe required glass instead of polyethylene, and this recipe needs to be added to the assembling machine again since in the current state, its hard to reach MV tier since you need to be able to craft polyethylene do reach MV tier.

For balancing purposes I propose that the polyethylene recipe will be slightly better than the glass recipe  so it will be worth changing to polyethylene once you can produce polyethylene properly.

It also seems like not everyone knows the proper way of making glass? Is there a proper quest explaining how to make glass?

**Comment by AlphaApotheosis** [comment]
So just to be clear what we are talking about here - there are several ways to make glass, and molten glass. Only some are available at LV:

1. The first method is to make glass dust with quartz sand + flint dust, then melting that to TiCo liquid glass in the smeltery, then pouring that into a basin to make a clear glass block
2. Quartzite dust in an LV fluid extractor will make molten glass
3. Sand in an MV fluid extractor will make molten glass

Glass dust also requires a MV fluid extractor to make molten glass, so the only way to get gregtech molten glass at LV is with Quartzite dust in the fluid extractor.

This is fine if a new recipe requires molten glass, as it is possible to get quartzite dust in the nether, but I just want everyone to be aware how glass currently works.

**Comment by Dream-Master** [comment]
Why not using Tico glass in gt machines as we do before too.

Question:
Did we need only add Glass as alternative recipe or add back Forestry Diode recipes?

**Comment by YalinHawk** [comment]
@Dream-Master adding the glass alternative recipe as a less efficient recipe would solve the problem.

**Comment by AlphaApotheosis** [comment]
Yes, create a low efficiency diode recipe using glass in assembler. Maybe only output of 1.

**Comment by Dream-Master** [comment]
ok
