### ISSUE TITLE
[2.0.1.0] Quest "Time to get some Steel" requires a deactivated item

### ISSUE THREAD

**Issue by StopTheBoolean** [GTNewHorizons/NewHorizons#2087]
Using Version 2.0.1.0. 
The quest requires the player to craft a bronze blast furnace which is deactivated and cant be crafted. This quest should be changed to require the player to craft the bricked blast furnace, or alternatively re-enable the bronze blast furnace.
![image](https://user-images.githubusercontent.com/31492557/31573531-2f14b62e-b101-11e7-9c22-39c37fff9c4b.png)

**Comment by Dream-Master** [comment]
I guess you not refresh your questfile.
/bq_admin default load
Then the quests are updated.

**Comment by Dream-Master** [comment]
My Questbook looks fine. Update your quest.
