### ISSUE TITLE
World accelerators suggestion

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2088]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I think world accelerators need rebalansing in some way. Currently we have - LV one - 1 rad, x2 bonus, MV one 2 rad, x4 bouns, and so on. But, sometimes, I need accelerating big radius, but with low speed. Realy, who ever need this 1-2 rad with low tier accelerators? Treefarm(and alot of other farms) need big radius, but not so big speed boost(collecting device has it's own limites, just ckeck the screen - EV accelerator working). 

My suggestion - make all world accelerators have the same radius, at cost of... something. 

![2017-10-14_22 42 33](https://user-images.githubusercontent.com/25028786/31578806-300b5a62-b131-11e7-9a80-356b9d9c44da.png)

**Comment by Dream-Master** [comment]
@Namikon
