### ISSUE TITLE
Can't craft Electric Hoe - missing Hoe head recipe

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2090]
#### Which modpack version are you using?
2.0.1.0
#
#### What did you try to do, and what did you expect to happen?
Electric Hoe requires Stainless Steel Hoe Head in its recipe but that can't be crafted anymore after GT tools have been removed.
#
#### What happend instead? (Attach screenshots if needed)
![2017-10-15_22 58 48](https://user-images.githubusercontent.com/8257735/31589132-8ca3ef98-b1fc-11e7-8f42-38afe82d6581.png)

**Comment by Dream-Master** [comment]
will check it
