### ISSUE TITLE
[Suggestion] Vacuum tube needs more Assembler recipies

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2092]
This was discussed in Discord GTNH General chat, wanted to make sure the lack of a good assembler recipe for Vacuum tubes was tracked.
#### Which modpack version are you using?
2.0.1.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Make Vacuum tubes using assembler/Thermionic Fabricator. I expected to find recipes that would be reasonably priced that would give a benefit over hand crafting vacuum tubes.  The assembly recipes for the GT Resistor is an example of where you got a benefit out of crafting with assembler over shaped crafting.

#
#### What happend instead? (Attach screenshots if needed)
There is only one Assembler recipe. It is priced at 1 Glass Tube, 1 Copper wire, 1 Steel rod and 18mb Molten Red alloy but only returns 1 Vacuum Tube. 
#
#### What do you suggest instead/what changes do you propose?
There should be more Assembler recipes with scaling up difficulty that allows one to use harder to get resources but craft more tubes in one recipe. My suggestions are as follows.

1 Glass Tube + 4 Fine Copper Wire + 1 Steel rod + 144 Molten Redstone = 2 Glass Tubes
1 Glass Tube + 4 Annealed Fine Copper Wire + 1 Steel rod + 144 Redstone  = 4 Glass Tubes
1 Glass Tube + 4 Annealed Fine Copper Wire + 1 Steel Rod + 72 Redstone Alloy = 8 Glass Tubes

Using molten glass to replace the liquid and use Red Alloy/Redstone Alloy bolts/rods to replace the glass tube could work too. Though may need an explanation that you can use Quartzite Dust to make molten dust in LV age.

**Comment by Bryfer** [comment]
do you mean the discussion in the general a few days ago, which lead to the creation of github issue #2085 ?

**Comment by Dream-Master** [comment]
I add a few more recipes
