### ISSUE TITLE
Lapotronic crystal recipe is bugged

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2093]
ver 2.0.1 singleplayer
NEI show that lap. crystal requere 2 RAW lapotron.
But realy consume 1 RAW lapotron. (1 RAW-> 1 Lap)
![default](https://user-images.githubusercontent.com/29812448/31598159-6bfadf7a-b28f-11e7-820d-4050b85aea15.png)

**Comment by Dream-Master** [comment]
Yea some nasty bug. This recipe not exist and i working on it.

**Comment by Dream-Master** [comment]
Ic2 circuits only shown but works with all advanced circuit

![image](https://user-images.githubusercontent.com/2970688/31607735-c5fdd544-b26d-11e7-82c6-5ee8825f5d2c.png)

**Comment by Proha5** [comment]
i not understand you.
I can create lapotronic crystal only from RAW. Without circuits.
![default](https://user-images.githubusercontent.com/29812448/31608965-a7011622-b2b5-11e7-8761-a61d7ce800c9.png)

**Comment by Dream-Master** [comment]
and that is wrong. The recipe need two circuits now they have some. Will be in newest version 2.0.1.1
