### ISSUE TITLE
Thaumic Bases and Crystal Wand

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2095]
#### Which modpack version are you using?
2.0.1.0 
#
#### What did you try to do, and what did you expect to happen?
I wanted to craft some Thauminite Caps and the Recipe was disabled.
And I thought that there were some other thingst ,that might be a bit to easy.
#
#### What do you suggest instead/what changes do you propose?
- Register Bloody Thaumium as a GT Material and use it to nerf the Bloodstained Thaumaturge Armor or 
 make it cost more vis (Maybe you could also use it in the Ritual to obtain the Sanguine Armor)
- Add the Thauminite Caps again and make Thauminite more Expensive at all (Knight Metal as Crucible Catalyst ?)
- Disable the Metalleat (Infinite Iron )
- Make the Thaumic Relocator require Crystal Plate instead of Shards
- Make the Crystal Wand from Thaumic Horizons Cost more, that Vortex Stuff ist'n that hard to do and the wand itself only costs a few shards. 

And just a small question:
Why do use an own GT build ?

**Comment by Dream-Master** [comment]
Yes there a very few mods that need to nerfed thats why some recipes not working
We using own gt for because i dont like all changes in the main repo and we add new feautures to the fork.
