### ISSUE TITLE
[Bug] MV Ender IO Quest: QuestID #142 (Torture Device) not unlocking

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2096]
#### Which modpack version are you using?
2.0.1.1
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Completed Quest 132(Simple RF Power: Liquid), 131(Simple RF Power: Solid). According to better questing config that should unlock quest 146(Torture Device)
#
#### What happend instead? (Attach screenshots if needed)
The quest did not unlock.
Quest book screen below.
[https://i.imgur.com/Hij35Ak.png](url)

#
#### What do you suggest instead/what changes do you propose?
Debug to determine why the quest is not unlocking, and fix it.

**Comment by Dream-Master** [comment]
@DukeGrimm Your screenshot not working.
Will check it.

**Comment by Ethryan** [comment]
Here dream I think this is the [link](https://i.imgur.com/Hij35Ak.png) DukeGrimm means.

**Comment by DukeGrimm** [comment]
Before the Roll back on the stone legion server, I noticed this quest was working in 2.0.1.2. Should be working with 2.0.1.3 I'd Imagine.

**Comment by Dream-Master** [comment]
I move this quest to hv

**Comment by Dream-Master** [comment]
Quest are rearraged and Torture Device now in HV area
![image](https://user-images.githubusercontent.com/2970688/31866163-75928e48-b77b-11e7-95b5-ac7be0d06180.png)
