### ISSUE TITLE
Reopen: The melting of cassiterite sand with carbon dust in EBF gives the wrong result.

### ISSUE THREAD

**Issue by GMous** [GTNewHorizons/NewHorizons#2097]
#### Which modpack version are you using?
2.0.1.1

#
#### If in multiplayer; On which server does this happen? 

Epsilon

#
#### What do you suggest instead/what changes do you propose?

#1964 
#1965
#1948

**Comment by Dream-Master** [comment]
@GMous Multiplayer or Singleplayer?

**Comment by GMous** [comment]
Multiplayer Epsilon server.

NEI - http://c2n.me/3OFMj2L
In real it smelt to 6 nuggets.
With BBF/EBF it smelted 1 to 1 instead of 3 ingots from 2 dust and 2 carbon/coal/etc.

**Comment by Dream-Master** [comment]
Please send me your gt cfg folder. I guess something wrong there.

**Comment by GMous** [comment]
[GregTech.zip](https://github.com/GTNewHorizons/NewHorizons/files/1394788/GregTech.zip)

**Comment by Dream-Master** [comment]
Server config was wrong. Fixed with the next server restart.
