### ISSUE TITLE
Bloody enchanted fabrics not craftable?

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2099]
#### Which modpack version are you using?
2.0.1.1

#
#### If in multiplayer; On which server does this happen? 
single player
#
#### What did you try to do, and what did you expect to happen?

I went to make Bloody enchanted fabric and when I made the enchanted fabric I could not use the crucible to make them bloody. I have unlocked the pattern under thaumic bases (it is specifically under iron spike).

I also noticed the recipe on the thaumic bases page for enchanted fabrics is not correct.

**Comment by Dream-Master** [comment]
We get a fix tomorrow.

**Comment by Pockyninja** [comment]
cool thanks

**Comment by Dream-Master** [comment]
oh wrong issue

**Comment by Dream-Master** [comment]
Yes Thaumic Base need a complete nerf. So mod is WIP

**Comment by Drobac** [comment]
if im not mistaken the bloody enchanted fabrics are made by using normal enchanted fabric on void spikes which had a mob killed on them ( makes them bloody). Which you then wipe off with the fabric to get the bloody one

**Comment by Dream-Master** [comment]
https://ftbwiki.org/Bloody_Enchanted_Fabric

**Comment by Drobac** [comment]
yep, so not an issue. You can close it
