### ISSUE TITLE
Project Red update

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#210]
New update of the core mod fixes crashes with the item filtering so plx givf new version

**Comment by Dream-Master** [comment]
Ok next update

**Comment by Dream-Master** [comment]
Version 84 version 87 not have to wait for a fix

**Comment by Teteros** [comment]
[MrTJPCore-1.0.9.22-universal.jar](http://www.curse.com/mc-mods/minecraft/229002-mrtjpcore#t1:other-downloads)

**Comment by Dream-Master** [comment]
done in the next update
