### ISSUE TITLE
Ore Drilling Plant not wokring

### ISSUE THREAD

**Issue by timothy1601** [GTNewHorizons/NewHorizons#2100]
-Which modpack version are you using?
2.0.1.1

-If in multiplayer; On which server does this happen? 
 MyFTB

-What did you try to do, and what did you expect to happen?
I set up my Ore Drilling Plant to mine some veins on Mars and Deimons.

-What happend instead? (Attach screenshots if needed)
The Ore Drilling Plant stops the Process after one cycle and doesnt get any ores. I have to manually restard the plant but the same problem happens again. The plant has enough drilling fluid and Energy, is in one chunk, has no maintenance problems and has HV energy(only needs MV).

This problem appears since the Update to 2.0.1.0 of the Server.

**Comment by Dream-Master** [comment]
@antifluxfield

You add a pull today is this fixed ?

**Comment by timothy1601** [comment]
After the last patch to 2.0.1.2 the Ore Drilling Plant is working again.

**Comment by Dream-Master** [comment]
Ok good.

**Comment by Antifluxfield** [comment]
Nope... The bug is still there... It's just that you restart the server and reset the fake player.
You still need that patch to fix it.

**Comment by Dream-Master** [comment]
Ok will do thanks
