### ISSUE TITLE
Questing book bug [2.0.1.2]

### ISSUE THREAD

**Issue by nwmqpa** [GTNewHorizons/NewHorizons#2102]
#### Which modpack version are you using?
2.0.1.2

#
#### If in multiplayer; On which server does this happen? 

Multiplayer self hosted multiplayer server

#
#### What did you try to do, and what did you expect to happen?

I tried to open the questbook and when I click on the "Detect /submit" button , nothing happen.
Then , I saw that every categories of the quest book are gone and can't click/open them
It's impossible to do a party too.

**Comment by Dream-Master** [comment]
Will fix later. In version 2.0.1.3

**Comment by MaitreCarl** [comment]
BQ book consume items without counting them (Quest about Healing Axe)
