### ISSUE TITLE
More Charcoal

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2104]
#### Which modpack version are you using?
2.0.0+
#

Quest "More Charcoal" should be "Retrieval" instead of "Crafting" quest, because at such stage of game Bronze Plates is already made in Steam Hammer. More than that we already have "Flint and Steel" item from Nether Quest.

**Comment by Dream-Master** [comment]
If you reach Lv age the quests are all retrieval before crafting quests.

**Comment by Dream-Master** [comment]
Maybe Flint and Steel can be retrieval(but you need a new one anyways)

**Comment by nikitinalexx** [comment]
But we already have Steam Forge Hammer, why should 4 Bronze Plates be Crafting Task?

Also could you confirm if this is bug or not.

When you craft something that is needed in a "Crafting" task, it will be tracked. But after that if you press a button "Detect", this Crafting task will Rollback like you didn't craft anything. So you should Craft the item again and NEVER click "Detect" button in Crafting task.

**Comment by Dream-Master** [comment]
Never test it

**Comment by Dream-Master** [comment]
Could be a bug

**Comment by Dream-Master** [comment]
4 Bronze plate is doable so no change.
