### ISSUE TITLE
Primordial Pearl gets consumed if infusing shadowmetal caps

### ISSUE THREAD

**Issue by Logicus123** [GTNewHorizons/NewHorizons#2105]
#### Which modpack version are you using?
2.0.1.3

#
#### If in multiplayer; On which server does this happen? 
gtnh-1.myftb.de

#
#### What did you try to do, and what did you expect to happen?
Infuse shadowmetal Caps; Primordial Pearl is an infusion ingredient

Thaumonomicon says that the pearl doesnt get consumed

#
#### What happend instead? (Attach screenshots if needed)
Primordial Pearl gets consumed

#
#### What do you suggest instead/what changes do you propose?
Make it so it doesnt get consumed

**Comment by Dream-Master** [comment]
A few recipes consuming the pearl

**Comment by Logicus123** [comment]
Thaumonomicon says that it doesnt consume it in this recipes... and it doesnt make sense because you need 3 prim pearls to make just 1 sceptre with those shadow caps

**Comment by Dream-Master** [comment]
Pic of the recipe please. I nerf the recipe with minetweaker so no clue if this give back mechanism works or not(like Bucket water ==> empty Bucket)

**Comment by heckenolaf** [comment]
https://www2.pic-upload.de/img/34127485/shadowmetalvoidcaps.png
thaumonomicon entry for Shadowmetal Cap 5758

**Comment by Dream-Master** [comment]
Guess this peral get consumed because not in the middle of the recipe. I can chnange it to the middle but not sure if it get back then.

**Comment by Ethryan** [comment]
Dream do you think the .reuse() command would work in the Infusion recipe?

**Comment by Dream-Master** [comment]
it don't work it gives an error.

**Comment by Logicus123** [comment]
I did a research on this and sadly it might not be possible; But its from Aug 2015:
https://github.com/jaredlll08/ModTweaker/issues/214

2 Suggestions:

Number 1: Dont use Prim Pearl as Ingredient
Number 2: Craft a "shadowmetal pearl" out of the primordial pearl in the normal crafting table (so that the pearl doesnt get consumed) and use the shadowmetal pearl as an ingedrient in the infusion recipe

**Comment by Dream-Master** [comment]
if Preimordial pear are in the center it get not consumed. Try the newest script and report if it works. Please make pics @Logicus123
