### ISSUE TITLE
Sleeping Bag disappeared

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2106]
When i was running and used Sleeping Bag it just disappeared forever

**Comment by Dream-Master** [comment]
Maybe you loose it during running (why try to sleep wehen running ???) or you hit Q to drop the item and cant found it who knows? This sounds more like you loose it not like a bug.

**Comment by Dream-Master** [comment]
Look in your Advance Badpack maybe you place it there with a controls combination.

**Comment by KaneHart** [comment]
Sometimes the sleeping bags will actually place in the world as well and stay there. They are a bit buggy but they work a lot better then the old ones lol.

**Comment by npo6ka** [comment]
In this mod, there is a check for such cases, if the sleeping bag can not be placed in the player inventory it will fall to the ground.
