### ISSUE TITLE
[2.0] Tungsten Grinding Head in SAG Mill

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#2107]
The Tungsten Grinding Head is used up with 1 use, and does not boost output as shown.
![2017-10-18_22 34 08](https://user-images.githubusercontent.com/30208401/31751672-aab92ad4-b454-11e7-8b13-4810be939f85.png)

(I should have gotten 6 Blaze Powder)

**Comment by Dream-Master** [comment]
Ok that make no sense. Need to be tested.

**Comment by Dream-Master** [comment]
Thats totaly normal. When the second stack get processed the value be on 99%.

**Comment by KorGgenT** [comment]
the grinding head comes back you're saying?

**Comment by Dream-Master** [comment]
No but you can macerating many stacks with it. The head consumed but not fully. Look at the display how many % left. same happend with Flint/and the other saw head too.

**Comment by KorGgenT** [comment]
So you didn't run into the bug then? Mine disappeared completely after the first grind, with no output bonus.

**Comment by Dream-Master** [comment]
No I get output bonus. Try to run two machines parallel
