### ISSUE TITLE
[Bug] Tinkers Arrows - Can't replace Existing arrow's arrowhead with GT arrowheads

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2108]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Tried to replace Alumite Arrowhead with Blue Steel arrowhead. Expected to see the status and material updated in output. I CAN replace TC arrowheads made with pattern, and probably iron arrowhead.
Correct Replacing behavior using flint arrowhead: https://i.imgur.com/ZXgnx1b.png
#
#### What happend instead? (Attach screenshots if needed)
The output looks the same as the input. No stats changed.
https://i.imgur.com/PWlMvBB.png
#
#### What do you suggest instead/what changes do you propose?
Check to see if the GT Material arrowheads can be modified to allow replacing on existing arrows.

**Comment by Dream-Master** [comment]
@Vexatos did you have any idea about it ?
