### ISSUE TITLE
Quest about Healing Axe

### ISSUE THREAD

**Issue by MaitreCarl** [GTNewHorizons/NewHorizons#2109]
Using latest Mod 2.0.1.2

#### Which modpack version are you using?
2.0.1.2
#
#### If in multiplayer; On which server does this happen? 
anytype of server also in solo
#
#### What did you try to do, and what did you expect to happen?
BQ book consume items without counting them
#
#### What happend instead? (Attach screenshots if needed)
no increase in QB and loosing items eaven if i gaved 8 Pam's garden of anykind
#
#### What do you suggest instead/what changes do you propose?
it used to count up and stop getting the item from us when it acheived the goal...

**Comment by alphaest** [comment]
server - client sync issue fixed in a newer betterquest version

**Comment by MaitreCarl** [comment]
nope, i still dont have the items on my side
