### ISSUE TITLE
Venus ore gen

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#211]
Please check the server ore gen config, Naquadah veins arent spawning on Venus. Checked every 3x3 chunk in a 500x500 block range and found none of it but at least 20 veins of all the other ores

**Comment by Dream-Master** [comment]
They will spawn i check it on sp. Maybe 500 x500 not enought. The vein is huge but not do common.

**Comment by Drobac** [comment]
The vein has the same chance of spawning as iridium and i found tons of iridium. It spawns in Sp for me as well, but nothing on the server

**Comment by Dream-Master** [comment]
i check it.

**Comment by Dream-Master** [comment]
Server config:

        mix {

            naquadah {
                B:Asteroid_false=true
                I:Density_5=5
                B:EndAsteroid_false=false
                B:Mars_false=false
                I:MaxHeight_60=90
                I:MinHeight_10=10
                B:Moon_false=false
                B:Nether_false=false
                I:OrePrimaryLayer_324=324
                I:OreSecondaryLayer_324=324
                I:OreSporadiclyInbetween_324=324
                I:OreSporaticlyAround_326=326
                B:Overworld_false=false
                I:RandomWeight_10=10
                I:Size_32=32
                B:TheEnd_true=false
                B:aCallisto_false=false
                B:aCeres_false=false
                B:aDeimos_false=false
                B:aEnceladus_false=false
                B:aEuropa_false=false
                B:aGanymede_false=false
                B:aIo_false=false
                B:aMercury_false=false
                B:aOberon_false=true
                B:aPhobos_false=false
                B:aPluto_false=true
                B:aProteus_false=false
                B:aTitan_false=false
                B:aTriton_false=false
                B:aVenus_false=true

**Comment by Drobac** [comment]
i will try to mine out some more then

**Comment by Teteros** [comment]
Doesn't  ***B:aVenus_false=true*** mean:
Disable naquadah gen in Venus = true?

**Comment by Namikon** [comment]
No, that's greg's way of defining "default" values. _false here means that the default value for this is false, if you'd delete this entry and reboot the server.

**Comment by Namikon** [comment]
Drobac found teh naquadah yesterday, so i guess this issue is resolved :)
