### ISSUE TITLE
Pump (EV) in assembler requere silicon rubber rings instead rubber rings

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2111]
2.0.1.3 singleplayer
Electric motor EV enough rubber ring to craft. But creating motor in assembler not accepting rubber ring. Assembler requere silicon rubber ring.

**Comment by Dream-Master** [comment]
Show me the recipe pic

**Comment by Proha5** [comment]
![default](https://user-images.githubusercontent.com/29812448/31808606-493909dc-b5b7-11e7-897c-142a07aa3add.png)
![default](https://user-images.githubusercontent.com/29812448/31808626-6274272e-b5b7-11e7-9ba5-8def50bd12cb.png)

**Comment by Dream-Master** [comment]
Not sure if I can't or if I won't add recipe. Check later.

**Comment by AlphaApotheosis** [comment]
Maybe remove regular rubber rings from allowed EV handcrafting recipe. EV cables require silicone/styrene. Every pump IV+ requires silicone rings. EV pumps should require them too.

**Comment by Dream-Master** [comment]
There is a config for

**Comment by Proha5** [comment]
@AlphaApotheosis
> EV cables require silicone/styrene. Every pump IV+ requires silicone rings. EV pumps should require them too.

Wrong info. You can create EV cable using regular rubber. Therefore EV pump allowed accept regular rubber rings.

**Comment by Dream-Master** [comment]
@Proha5 So did it work or not? can this issue be closed?

**Comment by Proha5** [comment]
you may read my first post.
if assembled recipe added GTU, then no need change
