### ISSUE TITLE
EBF-Time Quest

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2113]
This quest should not require Alumino Silicate Wool, only Cupronickel Wire should be left.

Because a player could have find already a Mica Vein, so Alumino Silicate Wool would not be needed.

**Comment by AlphaApotheosis** [comment]
Yes, this is possible. But very unlikely, as Mica is one of the rarest veins. The player would also need an LV Forming Press and Mixer.

**Comment by braeven** [comment]
we actually had 3 mica-veins before we even found redstone, we mass-produced mica-sheets, until we noticed the quest wants alumino-silicate and did it one time for the quest. Maybe change the quest to only need cupronickelcoils or make 3 quest out of it, one for making silicate wool, one for making mica sheets and one for making the ebf

**Comment by Dream-Master** [comment]
ok removed it so everyone can choose which material they want.
