### ISSUE TITLE
Quest Spell Foci #418 task 3/3 requires a blood orb with owner Namikon

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#2114]
#### Which modpack version are you using?
2.0
#
#### If in multiplayer; On which server does this happen? 
Dirthuts
#
#### What did you try to do, and what did you expect to happen?
Quest would accept my items
#
#### What happend instead? (Attach screenshots if needed)
Quest wants me to give it the blood orb with the owner Namikon
#
#### What do you suggest instead/what changes do you propose?
Change the blood orb detection to NBT independent

**Comment by alphaest** [comment]
In quest.json:
              "id": "AWWayofTime:apprenticeBloodOrb",
              "Count": 1,
              "OreDict": "",
              "Damage": 0,
              "tag": {
                "ownerName:8": "Namikon"
              }

**Comment by Dream-Master** [comment]
Will do
