### ISSUE TITLE
Questing issues

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2115]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i'm trying to complete quest #588 (forstry and farms page), it need some mysterios ore "Pyrochlore".
This ore does not exist in orespread datasheet, and can't be seen in achivenets. Apatite have another ore in it.

Suggestion: replace Pyrochlore ore with Phosphate ore.
![2017-10-21_12 08 15](https://user-images.githubusercontent.com/25028786/31850354-26335b2a-b659-11e7-8ee9-ef3da3863ef4.png)
![2017-10-21_12 09 47](https://user-images.githubusercontent.com/25028786/31850355-2655ac8e-b659-11e7-9f6e-70015703166b.png)

**Comment by Dream-Master** [comment]
New oremix was changed some version before. Old chunks has old ore mix

**Comment by Dream-Master** [comment]
Localizer I will add

**Comment by Cinobi** [comment]
Hey, almost all chanks in delta generated already, so no pyrochlore in overworld, and 40-60 height is higher than terrain level in twilight. So no ore atall =)

**Comment by Dream-Master** [comment]
I could add a quest where you can buy this ore for old worlgen servers.
