### ISSUE TITLE
some items from Random Things are disabled

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2117]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was looking for Player Interface item from the mod Random Things in NEI to see it's recipe
#
#### What happend instead? (Attach screenshots if needed)
I was unable to find it in NEI
#
#### What do you suggest instead/what changes do you propose?
It appears that half the items from Random Things are disabled in config but an item like Player Interface hasn't an equivalent in the modpack so I suggest at least to enable the Player interface and add a Thaumcraft recipe since the purpose of this block is to interact with the inventory of who placed it.

**Comment by bigbass1997** [comment]
It makes sense that it is disabled as we already have a mod that does this in place: RemoteIO.

Though I don't remember if you can access the armor slots with that, iirc you can't but still, we already have a block that can access a player's inventory. Plus the one from RemoteIO can be interacted with by OpenComputers. The regular Player Interface from Random Things cannot.

Here is some reference info: https://randomthingsminecraftmod.wikispaces.com/Player+Interface

**Comment by boubou19** [comment]
didn't know that thx i will look at it.

**Comment by bigbass1997** [comment]
You craft it using the Remote Interface and a Wireless Transmitter in a crafting square. The Transmitter needs to be bound to you (or whoever the interface should be connected to) by Shift+Rightclick with it in your hand.

**Comment by bigbass1997** [comment]
Remote IO has an item called (iirc) the PDA, which will explain generally what each thing is in the mod. (aka in-game documentation)

**Comment by bigbass1997** [comment]
If you intend to add a recipe still, which I have already said doesn't make sense, then it needs to be similar to the existing recipe for the Remote Interface from Remote IO, since it does nearly the same thing.

**Comment by Dream-Master** [comment]
Yes i will add recipes for this mod atm. Yes i have somthing in mind about Player interface.
