### ISSUE TITLE
Electro-Magic Tools Rubber Ball not craftable

### ISSUE THREAD

**Issue by timothy1601** [GTNewHorizons/NewHorizons#2118]
Which modpack version are you using?
Version 2.0.1.3

If in multiplayer; On which server does this happen? 
MyFTB

What did you try to do, and what did you expect to happen?
Tried to craft the Rubber Ball with 4 rubber ingots in the compressore but it doesnt work

https://cdn.discordapp.com/attachments/353936797530587137/371372663236460546/Unbenannt.PNG

What do you suggest instead/what changes do you propose?
Fix the recipe to be crafted in the gregtech Compressors

**Comment by Dream-Master** [comment]
will fix

**Comment by Dream-Master** [comment]
Will add a new recipe for the ball.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/31861238-0afe9e88-b72a-11e7-8d33-4e8f739158a1.png)
![image](https://user-images.githubusercontent.com/2970688/31861241-11f828a8-b72a-11e7-86e9-7bc9e3f589a3.png)
![image](https://user-images.githubusercontent.com/2970688/31861247-1b2217cc-b72a-11e7-8154-8bdb84a63f26.png)
