### ISSUE TITLE
Healing Axe from Extra Utilities

### ISSUE THREAD

**Issue by timothy1601** [GTNewHorizons/NewHorizons#2119]
In my opinion the Healing Axe from Extra Utilities is to broken. What is the point of having a mod that makes it difficult to eat when you can get early on a item that destroys that system completely?

The Axe should be disabled or be hard craft, if not the hunger overhaul mod is useless in the pack when you can get the Axe for some easy to get pams gardens.

**Comment by Dream-Master** [comment]
Not only Gardens you need to cook some special food too.

**Comment by timothy1601** [comment]
well but still isnt it a bit to op to get somethink like that so early?

**Comment by Methes** [comment]
No. Early on you feel the hunger and have to make large farms and plan your food making process.
After tons of exploring, including the nether, tons of water buckets used and LOT of crafting you can get the Healing Axe.
This is sufficient for all the regular gameplay, until you get mining tools so powerful it's actually beneficial to make the wholesome feast food. And even later you can get KAMI suite.
It's fine as it is.

**Comment by Dream-Master** [comment]
Fell free to add suggestion about additional items you need in Quest book for this quest. I close this now. Can be reopend if we need it.
