### ISSUE TITLE
[Bug] Transformer Inverting Message backwards

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2121]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Hit Transformer with hammer, I expected to see a message "Step Up, In: 32v 4A, Out: 128v 1A"
#
#### What happend instead? (Attach screenshots if needed)
Saw a message with "Step Up, In: 128v 4A, Out: 32v 1A"
https://i.imgur.com/wIQ4ibW.png
#
#### What do you suggest instead/what changes do you propose?
Fix it so the message matches the input/output of transformer.

**Comment by Dream-Master** [comment]
@Technus any idea what is here wrong?

**Comment by Dream-Master** [comment]
fixed i guess @Technus ?
https://github.com/GTNewHorizons/GT5-Unofficial/commit/4cf71516a5aa09f0388e35e2952e956f04354a2d
