### ISSUE TITLE
Industrial Sifter does not work

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2122]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
In singleplayer
#
#### What did you try to do, and what did you expect to happen?
I tried to build an industrial sifter. Once I had it set up, I expected everything to take the sieve block textures and the machine to work.
#
#### What happend instead? (Attach screenshots if needed)
The energy hatch, maintenance hatch, and input bus didn't change textures, and the controller still said "Incomplete structure." I'm not over any chunk boundaries or anything that should cause this to not work.
![2017-10-22_19 33 37](https://user-images.githubusercontent.com/29802757/31867582-6cd081ea-b760-11e7-9624-760170f57a96.png)

#
#### What do you suggest instead/what changes do you propose?
Either fix the multiblock's registration, or change the description to reflect how it's actually supposed to be built.

**Comment by Dream-Master** [comment]
@draknyte1 any idea what is here wrong?

**Comment by draknyte1** [comment]
Put your hatches on the bottom layer. Might be a registration check issue.

**Comment by Dream-Master** [comment]
@Technus can you look at this issue please?

**Comment by Bluebine** [comment]
@draknyte1 I tried putting the hatches on the bottom layer, tried moving the output hatches to the top layer, neither fixed the issue.

**Comment by RaggedCaster** [comment]
The hatches need to be MV+ tier. I think the sifter outputs all the products into 1 hatch so they don't fit inside LV one (4 slots).

**Comment by Dream-Master** [comment]
@Bluebine does it work now
Can this be closed?

**Comment by Bluebine** [comment]
@Dream-Master I've tried all the suggestions, none of them fixed it.

**Comment by LOKKO12** [comment]
Same issure on MP. Worked fine at 2.0.0.0 now its broken. 
@RaggedCaster only output hatches need to be MV+ input does not matter. 
@Bluebine you need your hatches/bus to be on the corners of your sifter. Like this (C=casing X=Hatch): 
XCCCX
CCCCC
XCCCX

**Comment by draknyte1** [comment]
The shape of the structure hasnt ever changed.
You definitely dont need such a strange corner configuration for hatches..

I personally have my four outputs along the bottom right side, input beside the controller and the energy/maint on the bottom left.. works as expected.

Fix pending either when I return from Asia or when Dream makes the change I advised.

**Comment by DonMoe3000** [comment]
Actually the problem with the large Sifter not working is still present in 2.0.7.0 
I'm running a Singleplayerworld and despite the fact that i've tried all the things above the multiblock still tells me that it's incomplete. 
Even with all the hatches changed to HV. 
Something is weird with building instructions on the Block itself too. If you hover over it in addition to the normal instructions of blocks you need, there comes a second time the list for what you need with only a muffler and a "core"-block?

**Comment by Anarack** [comment]
Yes, because 2.0.7.0 has the same gt++ as 2.0.6.8, its fixed in much latter builds of gt++.
