### ISSUE TITLE
[2.0.1.3] Titanium Ore Tooltip Needs Adjustment. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2123]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
As far as I know Titanium ore is now on Mars and not the Moon. Tooltip needs an adjustment. 
https://i.imgur.com/TmgBmdr.png
#

#### What do you suggest instead/what changes do you propose?
Fix the Tooltip :)

**Comment by Bryfer** [comment]
Read issue #1977 for more information
Titanium will be changed back to moon as soon as possible

**Comment by Dream-Master** [comment]
Fixed and would be in next build
