### ISSUE TITLE
fine wire cost being different

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2125]
#### Which modpack version are you using? 
2.0.0
#
#### If in multiplayer; On which server does this happen? 
Dirt huts, but I'd assume all of them because it's recipe issues 
#
#### What did you try to do, and what did you expect to happen?
Nothing really, it's just suggested recipe changes. 
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
For fine wire, before 2.0 all fine wire was 8 fine fire per ingot. You could make it different ways, but they all resulted in that. Either 1 ingot to 2 1x wire, then 1 1x wire to 4 fine wire. You could also make an ingot into 2 rods, and a rod turned into 4 fine wire. However, since 2.0 the ingots that don't make 1x wire, instead only make 1 fine wire per ingot, and 2 fine wire per ingot if you use rods. This means you get 4x-8x the amount of fine wire you should be getting, which doesn't seem right to me. I'd suggest changing the values back to 8 fine wire per ingot and 4 fine wire per rod. At the moment you get the most fine wire using wire cutters on foil, and there's no way that's intentional. I can add a full list later but the one I encountered first was osmiridium.

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Seems that some recipes are get overriden.
