### ISSUE TITLE
[2.0.1.3] Miner / Pump has a issue spawning the Drill Bit (tile entity) till a server reboot. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2126]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Place a pump or drill and power it and see the drill bit/pipe extend and work it's way down.
#
#### What happend instead? (Attach screenshots if needed)
The tile entity does not spawn if there is 1 single block under it will get mined / drained but no tile entity will show up after that and nothing gets performed till the server reboots and then it magically works again. If there was ones before place in the world before randomly breaks they work as well but anything new will always break till you reboot the server.

Permissions, no land claiming, etc just don't solve the issue sadly. Even with permissions, land claiming protection, etc disabled. Does not seem to be our issue but rather a bug that randomly happens. I can't find a way to repeat it just happens at random.
#
#### What do you suggest instead/what changes do you propose?
Should just work lol!

**Comment by Dream-Master** [comment]
@Technus
@Antifluxfield any idea about it?

**Comment by Dream-Master** [comment]
@richardhendricks

**Comment by richardhendricks** [comment]
Can you give a frequency on this issue?

So, standing right next to a drill/pump it sometimes does not start? 

But after a reboot the entity works fine?

And I assume you have auto-output enabled on the miners?

Mitch did some changes to the drill for the next release to make it more robust across server restarts/chunk loading/unloading. We should revisit this after the next release.


I don't have time for detailed check into this (might require a server setup), but I will modify the source code so it has a separate debug message enable variable so we can watch what is happening.

**Comment by Dream-Master** [comment]
@KaneHart

**Comment by KaneHart** [comment]
Sorry I gave up on it soon after. Lot of players also had issues tried it once and never went back to it. In fact they all go into thaumcraft for the thirsty tank instead. I can't give you an update on this sadly.

**Comment by richardhendricks** [comment]
Have players on the official servers seen this?
