### ISSUE TITLE
Catwalk recipe (Assembler vs Crafting Window)

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2127]
#### Which modpack version are you using?
GT New Horizons (latest)
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Catwalk recipe in crafting window returns 6 Catwalks
Assembler recipe returns 3 Catwalks
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Please change it 6 Catwalks in Assembler :)

Very small issue but I figured I'd mention it!

**Comment by Dream-Master** [comment]
Did it use more materials in assembler then crafting grid?
If not the recipe was devided automaticly by gt code.
If it is more expensive i can change it.

**Comment by tranceplanet** [comment]
**Original**
Recipe cost in Crafting Window = 6 Catwalks
3x Steel Grate
2x Steel Rod
2x Steel Screw

Recipe cost in Assembler = 3 Catwalks
3x Steel Grate
2x Steel Screw
144 Molten Steel Liquid

Considering the recipe is actually harder to make in Assembler due to Molten Steel requirement, it gives less Catwalks...

**Suggested**
Do you think you can change the Assembler recipe to = 6 Catwalks
3x Steel Grate
2x Steel Rod
Remove Molten Steel requirement

No need for steel screws like many other recipes.  (that's the point of the assembler right?)

**Comment by tranceplanet** [comment]
This is also the same for Caged Ladders

Original Crafting Recipe = 6 Caged Ladders
3x Steel Grate
1x Steel Rod
2x Steel Screw
1x Wooden Ladder

Assembler Recipe = 3 Caged Ladders
3x Steel Grate
1x Wooden Ladder
216 Molten Steel

Suggested Assembler Recipe = 6 Caged Ladders
3x Steel Grate
2x Steel Rod
1x Wooden Ladder
Remove Molten Steel Requirement

**Comment by tranceplanet** [comment]
Suggested to remove Molten Steel as a requirement in Assembler as this recipe is easy to craft in a window already with practically the same ingredients.  The assembler recipe shouldn't be gated by MV / Molten Steel.

**Comment by Dream-Master** [comment]
Sure will look into it.

**Comment by Dream-Master** [comment]
3 Inputs only in code possible.
