### ISSUE TITLE
circuits requierd in Gt ++ multiblocks    

### ISSUE THREAD

**Issue by HegemonRast** [GTNewHorizons/NewHorizons#2129]
latest mod pack 
put in circuits until one worked 
 
what circuits are needed for what recipes 
circuits are also needed in some of my processing arrays   
what circuits are needed for what recipes in these as well   

is this information somewhere  please  or can you add it to nei ??

**Comment by Dream-Master** [comment]
Can you make some pics? I dont undertsnad this issue.

**Comment by HegemonRast** [comment]
I don't understand what you don't understand     the GT++ multi blocks have been changed so that they require a circuit in the input bus in order to function.   NEI does not show the circuit needed  I am ask ing
