### ISSUE TITLE
Adding this Mods to the Pack as optional files

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#213]
Better FPS
http://minecraft.curseforge.com/mc-mods/229876-betterfps/files
Optifine UB7
http://minecraft.curseforge.com/mc-mods/229876-betterfps/files

**Comment by Drobac** [comment]
You put the same link for both mods

**Comment by Teteros** [comment]
http://optifine.net/downloads

**Comment by Drobac** [comment]
When i put both in the mods folder the client doesnt want to start up. Does Better FPS go into core mods? Nothing is written anywhere about where it should be

**Comment by Teteros** [comment]
You can put above mods in the *mods* directory. Optifine gives minecraft a black screen at startup, its a known issue in 1.7.10. Maybe that is why you thought it would not start up?

BetterFPS is more or less a continuation of FpsPlus+. It goes well with FastCraft and Optifine as they do different things.
Make sure to turn off "Fast Math" and "Fast Render" in Optifine's performance settings when using BetterFPS or use [these](http://imgur.com/a/D95XA) settings.

**Comment by Drobac** [comment]
Didnt  blackscreen but reverfed back to the launcher screen within 2 seconds, no error log spawned

**Comment by Drobac** [comment]
reverted*. Cant edit posts on the mobile site?

**Comment by Dream-Master** [comment]
I will add both Files in the next packupdate with  .optional. If you want to use this file have to rename it to .jar

**Comment by Namikon** [comment]
Random comment: I had both optifine and betterfps in my client yesterday, and it worked pretty well. No texture glitches so far, overall a more stable fps, and due to optifine some improvements

**Comment by Dream-Master** [comment]
Added to the pack as optional
