### ISSUE TITLE
multi block electrolizer

### ISSUE THREAD

**Issue by HegemonRast** [GTNewHorizons/NewHorizons#2130]
current update 

got the multi block electrolyser working making hydrogen from water 

its  zpm powered and runs about as fast as in iv single block now 
did you intend to make it useless ?

**Comment by Dream-Master** [comment]
I dont change there anything. @draknyte any idea?

**Comment by Toperoco** [comment]
Could this be related to the fix of #2018 ?

**Comment by Dream-Master** [comment]
Could be. 
Not sure why it was changed from IV to EV.
