### ISSUE TITLE
Suggestion for a thing that would help server performance, maybe

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2131]
#### Which modpack version are you using?
2.0.1.3
#### What do you suggest instead/what changes do you propose?
I think it would be cool if there was a processing array for multiblocks. So you could have 64 industrial electrolyzers in a single multiblock. This would be nice for things like ebfs, vacuum freezers and now the gt++ stuff. 
For the most part it's not that bad making multiple multiblocks, but when you need hundreds of multiblocks, it gets unreasonable

**Comment by Dream-Master** [comment]
Not sure if that is possible.
@Technus
