### ISSUE TITLE
Console spamming "Generated recipe with a smaller time. | 2000 | 1200 |"

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2132]
I strongly suspect this is created by GT++, since it's the only mod I know of that generates recipes with smaller times. The 2000 - 1200 numbers also fit the 40% decrease that is found in it's tooltips. The message occures exactly once per second.

(DirtHuts server, v2.0.1.3)

**Comment by OneEyeMaker** [comment]
You're right: it's GT++:
https://github.com/GTNewHorizons/GTplusplus/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GregtechMeta_MultiBlockBase.java#L125

**Comment by Dream-Master** [comment]
@draknyte1
@Technus 

any idea if and how it can be disabled?

**Comment by draknyte1** [comment]
Comment it out?

**Comment by Dream-Master** [comment]
sure will do.
