### ISSUE TITLE
Impossible craft Lapotronic Energy Orb!

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2133]
2.0.1.3 singleplayer

if craft manualy - nothing happens.
![default](https://user-images.githubusercontent.com/29812448/31931234-df99839e-b8e5-11e7-8f7f-7a523c255e7f.png)

If craft using AE2(fluid terminal), then also - nothing happens, But all components disapear(except soldering fluid).

**Comment by Dream-Master** [comment]
@Proha5 show me the nei recipe please.

**Comment by Proha5** [comment]
How fix in config? (i can't wait for update)
Assembler placed at CleanRoom.
![default](https://user-images.githubusercontent.com/29812448/31931682-503bc598-b8e7-11e7-8df1-0c12ee4b56c5.png)

**Comment by Proha5** [comment]
Sorry, i used regular assembler. But requered circuit assembler. Recipe works fine
