### ISSUE TITLE
Dark Ashes -> Centrifuge

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#2134]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Dirt Huts
#
#### What did you try to do, and what did you expect to happen?
Trying to send Dark Ashes to Basic Centrifuge using GT Conveyors and GT Item Pipes
#
#### What happend instead? (Attach screenshots if needed)
Dark Ashes clogs up the item pipe, is not received by Basic Centrifuge.
Manually inserting the Dark Ashes into the Basic Centrifuge works.
#
#### What do you suggest instead/what changes do you propose?
Fix

**Comment by Dream-Master** [comment]
You sure only one type of ash in the pipe. Maybe another typ was there and plugged the pipe.
I need to test it. Can you make a pic from your setup?
@tranceplanet

**Comment by Dream-Master** [comment]
try to wrench the output input. For me it works then.
![image](https://user-images.githubusercontent.com/2970688/32067754-7c19b9cc-baae-11e7-92b6-a4bc756c6c6d.png)
