### ISSUE TITLE
Thermal Boiler Controller Recipe Fix

### ISSUE THREAD

**Issue by eloquentJane** [GTNewHorizons/NewHorizons#2135]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Checked crafting recipe for Thermal Boiler multiblock controller. Expected it to either contain items which are all craftable, or for it to be completely disabled and have no recipe.
#
#### What happend instead? (Attach screenshots if needed)
The recipe includes four IC2 Geothermal Generators, which have their recipes disabled. Thus the Thermal Boiler is unobtainable despite having a recipe.
#
#### What do you suggest instead/what changes do you propose?
I suggest replacing the IC2 Geothermal Generators with Lava Heaters from Remote IO, as their recipe is at the same HV tier as other components of the Thermal Boiler controller and they are similarly associated with lava.

**Comment by Dream-Master** [comment]
@eloquentJane Lava Heater is tiered at EV
![image](https://user-images.githubusercontent.com/2970688/32067492-a890cf28-baad-11e7-9b4e-1196ad7db770.png)

**Comment by Dream-Master** [comment]
@eloquentJane Any other suggestions?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33472344-22b1d11e-d672-11e7-90d3-122a2a403a0b.png)
