### ISSUE TITLE
Naquadah reactor MK3 fuel value

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2137]
2.0.1.3
![default](https://user-images.githubusercontent.com/29812448/31989376-7165815e-b9b5-11e7-84f6-a425962e8313.png)

Long rod requere 2 rods. MK2 generate 500 mil from 1 ingot. MK3 generate 312 mil (250x125%efficiency)
MK2 better than MK3? is it GTU balance or gtnh?

**Comment by ko5h** [comment]
yep need change to 125kk https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/load/GT_FuelLoader.java#L32

**Comment by Proha5** [comment]
ko5h, then MK1 will better than MK2.
If current balance created by GT5U, then no need changes.

**Comment by ko5h** [comment]
@Proha5
mk1 = 25kk*8bolt(1ing)=200kk=>80%=160kk
mk2 = 125kk*2rod(1ing)=250kk=>100%=250kk
mk3 = 250kk+1Lrod(1ing)=250kk=>125%=312500k

**Comment by Dream-Master** [comment]
So wich value need to be changed ?
