### ISSUE TITLE
64ME storage component

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2139]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Craft 64ME storage component
#
#### What happend instead? (Attach screenshots if needed)
It can accept only one type of extrime circut, according to nei. Another tiers of storage components can accept any type of circut of it's tier.
![2017-10-25_21 13 48](https://user-images.githubusercontent.com/25028786/32015449-d12f5f56-b9c9-11e7-8ea2-2af0f6db1fde.png)

**Comment by Proha5** [comment]
i already posted this issue.
