### ISSUE TITLE
Custom Bees ;-)

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#214]
Look what I found:

http://bdew.net/gendustry/configuration/adding-custom-bees/

**Comment by Dream-Master** [comment]
https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/config/gendustry/bees.cfg

**Comment by Namikon** [comment]
Finally some naquadah bees for Drobac ;)

**Comment by Dream-Master** [comment]
@Namikon Maybe a alternative way to get Thaumcraft/Twilight Forest Stuff without killing a boss.

**Comment by Namikon** [comment]
True thing. But then it has to be possible without any machines (or maybe just the default bee-breeding machines, if they are not disabled). As Gendustry is late/endgame

**Comment by Dream-Master** [comment]
Yes we can add this after some standart Magic Bees from the Mod Magic Bees. So have to think about balancing.

**Comment by Drobac** [comment]
Shouldnt put bees as a requirement for anything. They can be a real pain to do them and not everyone wants or know how to do them. But givf naquadah bees, always

**Comment by Dream-Master** [comment]
It is only a alternative way to get things. Not every Body like a combat like you ;-)

**Comment by Drobac** [comment]
As an alternative its would work

**Comment by Dream-Master** [comment]
Maybe i set the chance to get byproducts very low so that the way go inside the twilight Forest and kill a Boss is much shorter.

**Comment by Dream-Master** [comment]
Blood Asp will add bees in Gt Version 5.9 so all the bees from Infini Tech he said me.

**Comment by Drobac** [comment]
What would you add, we got the important ones for shards. Only other i can think of is for ethereal essences, maybe void seeds

**Comment by Dream-Master** [comment]
Not sure now but i think the twilight ingredients i will add that you not have to fight the tf Bosses.

**Comment by Drobac** [comment]
Bee wishlist:
- Yellow Garnet
- Energized Dust
- Naquadah (has a further tier into Enriched Naquadah and Naquadria bees)
- IC coolant bees? Forestry already has a wintry brach with something similar
- Could do something weird like Deuterium and Tritium

**Comment by Dream-Master** [comment]
sure when i working on it i will add them.

**Comment by Namikon** [comment]
Didn't you plan to keep GT5.08 and continue working on the fork in order to implement your own stuff?

**Comment by Dream-Master** [comment]
Not sure. 5.09 isn't open source yet. Atm I not tested 5.09 in the pack. What do you think we have to do?
5.09 have bees that give gt ore dust.

**Comment by Namikon** [comment]
Dunno, you where the one who forked the gregtech repository and planned to add custom materials.  If you do that, you'd have to merge gt5.09 once it's committed in order to keep up with the changes. But depending on what bloodasp has added by then, this might cause conflicts.

**Comment by Drobac** [comment]
Can we add Bloodasp's bees to our version? Or would that require his update?

**Comment by Drobac** [comment]
There are some cool ones
http://www.beyondrealitypack.com/bees-flow/#1440027634934-1ac5f364-8feb

**Comment by Namikon** [comment]
Once he makes his source public, it can easily be merged. It's even possible with an obfuscated version, but I won't do it. It's a pain do translate the function names

**Comment by Dream-Master** [comment]
I think will add those bees like beyond reality makes via json files(gendustry give us the feature)

**Comment by Dream-Master** [comment]
Maybe i copy and past the Bees from Beyond reality for now and change the Values a bit.

**Comment by Dream-Master** [comment]
Working on it

**Comment by Dream-Master** [comment]
Added
