### ISSUE TITLE
Universal spade uncraftable due to GT:Showelhead no recepie

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/NewHorizons#2140]
#### Which modpack version are you using?
v2.0.0
#
#### If in multiplayer; On which server does this happen? 
NA
#
#### What did you try to do, and what did you expect to happen?
Get a recepie for Gregtech showelhead which is req for a universal spade (tried with steel)
#
#### What happend instead? (Attach screenshots if needed)
NEI refuesed to give me the recepie
#
#### What do you suggest instead/what changes do you propose?
Change the recepie :)

**Comment by Dream-Master** [comment]
Because i remove the shovel i remove the shovel head too. So i guess i need to add recipes back.

**Comment by ruSauron** [comment]
In additional check Hoe head recipe please. To craft electric hoe (from IC2) you need Stainless hoe head which is uncraftable.
