### ISSUE TITLE
Death on another planet makes you lose everything

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2141]
I think it is not okay that we craft a rocket for hours, make our oxygen gear, other machines, then accidentally die on another planet and lose everything of that.

One mistake makes you lose 10+ hours, because you have to make another oxygen gear, rocket, and all those other things.

Also it should somehow handle where to spawn you. Because for example after death on moon you are spawned on the earth. Or vise versa is possible.

Suggestion: you should not lose your rocket, launch pad and oxygen gear. More than that you should have 1 Oxygen full tank after death. Implement some new penalties for dying on moon instead of losing everything.

**Comment by Dream-Master** [comment]
so far i know you can be respawnt on the planet you died or back on earth. Graves are spwant on death point nothing i can do here. You need to find chams of keeping from TF that your inventory not loosing. In the next version you can using the white crystal from random things(can be fully loaded in a full moon night)

**Comment by Bryfer** [comment]
Charm of keeping is buggy and should not be used. It's messing with graves.

**Comment by ko5h** [comment]
use ench "last stand" or "soulbound"
https://i.imgur.com/muajG03.png
https://i.imgur.com/JPdULR8.png
p.s. maybe before flying to the moon you need to prepare?

**Comment by nikitinalexx** [comment]
ko5h, you can never be prepaired for 100%. You are not immortal. And there are a lot of dangerous things. Who can be 100% sure that he doesn't die from falling from high place, going afk for 2 minutes and being killed. Yes, it is rare case but possible.

For example i died when I got into a rocket, started countdown, but there was a mob close that makes you like you are underwater. So countdown was at 10 when i started losing health. At 0 countdown i died and rocket flew away Alone!

**Comment by ko5h** [comment]
@nikitinalexx you are wrong, you can prepare for 100%... 
Last stand = immortality (but, if you took care of the experience)
Talisman of remedium - removes all debuff
Only your precautions guarantee your safety(fly away from a safe zone)

**Comment by nikitinalexx** [comment]
Then let's better make a list of such items and put them into a description of some moon quests. For example i didn't know of these items, as most players who start i guess.

**Comment by Ugachaga** [comment]
@ko5h 
I see you lose Adventure Backpack on death. JFI, its can be soulbounded too.

**Comment by Dream-Master** [comment]
@ko5h good idea with the Quests. Can you list a few things i can add as quests to the moon Quests?

**Comment by ko5h** [comment]
last stand - searching in dungchest (can be issued as a reward)
soulbound - create in hv tier (can do after enchanter even a quest to create ender crystal for soulbound)
death poppet - first steel
talisman of remedium - the only thing to add to the quest book

Poppet and enchanter eio present in the quest book...perhaps it is worth considering how to pre required  item to fly to the moon...imho the best option is death poppet

**Comment by Dream-Master** [comment]
ok will check.

**Comment by Dream-Master** [comment]
death poppet get a recipe change because witchery i not touch now(only 1-2 recipes)

**Comment by ko5h** [comment]
mb change recipe in direcraft? to avoid autocraft (and immortality)
https://www.youtube.com/watch?v=hwmT1z0sEtE

p.s. although here it is necessary to think what we want to do ... complicate or facilitate
