### ISSUE TITLE
Good Miner recipe does not accept Annealed copper

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2142]
#### Which modpack version are you using?
2.0.,1.3
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I anneal all my copper now.  The good miner recipe in NEI shows only copper cable, however if you hold shift down on the copper cables, you can see it is oredicted to cableGT02Copper and cableGT02AnyCopper.  Putting #cableGT02AnyCopper into NEI search window does show copper cable and annealed copper cable.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Comparing with MV battery buffer, which uses 2x copper wires, maybe switch the oredict order to have the AnyCopper first before the Copper?

Picture shows recipe OK with 2x copper cable, second pic shows it not working with 2x annealed.
![2017-10-28_02 35 28](https://user-images.githubusercontent.com/1214811/32132405-b2ba6ba4-bb88-11e7-88b0-d0984609f19e.png)
![2017-10-28_02 35 33](https://user-images.githubusercontent.com/1214811/32132406-b2ce498a-bb88-11e7-8133-7767c9486bbd.png)

**Comment by Dream-Master** [comment]
I can change recipe to anycopper cable maybe this work.

**Comment by Dream-Master** [comment]
The any copper/iron thing was removed in main repo. Should i do it here too ?

**Comment by richardhendricks** [comment]
What does that mean for the recipe in the main repo?

**Comment by Dream-Master** [comment]
idk
