### ISSUE TITLE
Apiarist Clothes should be Retrieval task, not Crafting task

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2143]
#### Which modpack version are you using?
2.0.1.3

#
#### What did you try to do, and what did you expect to happen?
Tried to turn in Apiarist clothes for quest. I had received two pants from a loot bag. It did not accept the quest.  After i crafted my own pants, it still did not complete the quest.  Maybe the assembler crafting requirement for the clothes doesn't count for Better questing? 
#
#### What do you suggest instead/what changes do you propose?
Update quest to use Retrieval instead of Crafting.

**Comment by alphaest** [comment]
Crafting tasks are for things you craft using the crafting table only. So this is definitely a bug since the gear can only be made using the assembler.

**Comment by Dream-Master** [comment]
yes need to change it.
