### ISSUE TITLE
/ob_inventory restore (player) (id)     Command keeps erasing my inventory and spawning me at world spawn every time I enter the world.

### ISSUE THREAD

**Issue by LightBane** [GTNewHorizons/NewHorizons#2144]
#### Which modpack version are you using?
The latest, version 2.0.1.3-1.7.10
#
#### If in multiplayer; On which server does this happen? 
No, I play in sp only.
#
#### What did you try to do, and what did you expect to happen?
Basically, I tried clearing the chat typing /clear, but it deleted my whole inventory, so I reverted to the OpenBlocks command to restore an inventory I had on a previous death. Since I had most of my things back, I shut the game off.
#
#### What happend instead? (Attach screenshots if needed)
The problem came when I loaded the world again, as  my whole inventory was gone (I only had the 4 initial books you start with). I tried looking in every folder containing the word “inventory” under “saves” to find a quick fix, but they are all encrypted, so I’m only able to access them in game, I believe. This keeps happening, as I always reload the inventory and get sent back each time the world loads, and I fear my progress will be hindered by this.
#
#### What do you suggest instead/what changes do you propose?
I hope there’s a way to keep my stuff while also spawning at my base, and I also hope this issue gets solved for other people, as they might run into it sooner or later.

**Comment by Dream-Master** [comment]
I respawnt 100 or 1000 graves with this command and have no issues. Guess you do something wrong.

**Comment by Dream-Master** [comment]
but i never test it in sp.

**Comment by LightBane** [comment]
Thanks for the response. It must be my slow computer then, and seeing how usually I load a world and chat says “WARNING: 2347 modifications were stuck”, I guess I can be thankful I can even play the pack. I’ll stop using the command to get my stuff back and craft it myself, I hope it will fix it.

**Comment by Ugachaga** [comment]
> “WARNING: 2347 modifications were stuck”
In SP, be sure that Minecraft window is active while you load **world** (when loading the program itself it does not matter). Otherwise Minetweaker scripts could not be loaded propertly and you get such message and wrong/unmodified recipes.

The general rule: if you received such error message, you must comletely restart Maincraft.

**Comment by LightBane** [comment]
I see, thanks Ugachaga, I’ll be sure to do as instructed.
