### ISSUE TITLE
Climate Acclimator power usage seems high

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2145]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Climate acclimator for making tolerant bees seems to be very high power consumption.  Need to investigate.

From Bigbass
Just so you know, MJ and RF are not the same thing. 10 RF = 1 MJ, or at least it did originally. However this still doesn't account for what EU consumption rate you are estimating. 2.5 MJ/t comes out to approx. 6.9444 EU/t.

**Comment by Dream-Master** [comment]
I never touched Gendustry code but it is open source.

**Comment by Dream-Master** [comment]
@richardhendricks any news here?

**Comment by Dream-Master** [comment]
Binnies mods are open source now

**Comment by Dream-Master** [comment]
https://github.com/ForestryMC/Binnie/tree/master-MC1.7.10

**Comment by richardhendricks** [comment]
public static final float ENERGY_PER_TICK = 2.0f;

need to compare in game with measurements

**Comment by richardhendricks** [comment]
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/genetics/machine/acclimatiser/Acclimatiser.java

**Comment by Dream-Master** [comment]
@richardhendricks if you can fix it do it. I close this now.
