### ISSUE TITLE
Crystal chip recursive recipe

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2146]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I'm starting thinking about the most efficient recipe of IV circuts - recipe with Crystal Soc.

I found that i need raw crystal chip for it. The first exemplar can be made in low gravity only - according to google, it need to be crafted in Space station of Galacticcraft. (Hey, bloodasp, are u serios?).
After u get the first one the recipe of crystals become... recursive. Raw crystal chip brokes to pieces with hammer, and u get new one from each piece. All looks cool, but...
... but AE can't into recursive recipes. All known(for me atleast) autocrafting systems can't into recursive recipes! I can make a cicle of recrafting, but can't order the needed amount of this crystals. This is realy, realy bad.

Suggestion: Remove the recursivity in any way.

**Comment by Dream-Master** [comment]
Not only Space station asteriod belts ok too.

What you mean with recursivity. Did you mean the chance the Crystal is outputed ?

**Comment by Cinobi** [comment]
A made from B
B made from A
That's what's "recursivity" means. 
Crystal -> crystal shards -> crystal -> crystal shards and so on.
If there is 1 shard in AE and i order 2 ciruts it will just say "not enough resorses"
If there is 2 shards in AE and i order 2 circuts it will just craft 2 circuts, and i will forsed to use this shitty lowgravity recipy again.

**Comment by Dream-Master** [comment]
Then do it from hand. And shitty mean only complicated/advanced

**Comment by Cinobi** [comment]
Hey, dream, are u serios?) Maybe we should remove AE from pack? "By hand". Lol.

About "shitty" I say it's shitty way becouse:
1) 10% chanse for crafting
2) need distant base with 2 machines. This is madness.

**Comment by braeven** [comment]
Why not build a seperate Autocrafting-System, that automatically keeps 5 Stacks of Crystals avaible for the main Network? This doesn't even need to be a ME System.

**Comment by ko5h** [comment]
u need create first raw chip in low gravity...other chip u can create in overworld
You can only use liquid in pattern to avoid recursion

**Comment by Cinobi** [comment]
@braeven becouse 5 stacks is not enough, sometimes. X stacks is not enough, sometimes(before u suggest keep 10 or more stacks). All shit mast be automated, that's the final goal of all GT packs =)

**Comment by braeven** [comment]
@Cinobi Thats why you make a sub-system that keeps 64 or even 512 Stacks avaible for your main system, that automatically restocks itself. it's not that hard to build.
