### ISSUE TITLE
Pump not pumping properly

### ISSUE THREAD

**Issue by Oliverxll** [GTNewHorizons/NewHorizons#2147]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Myftb.de
#
#### What did you try to do, and what did you expect to happen?
Use the basic pump to pump oil
#
#### What happend instead? (Attach screenshots if needed)
It sends pipes lower before actually picking up all the oil at the layer it is at. Within radius, like one block away.
Now I have noticed after a few times, it happens when you teleport home, and back. So the chunks are de-loaded and then loaded again, dunno if that can have any effect on it. Might be useful info
#### What do you suggest instead/what changes do you propose?
I would suggest it should pump all the oil at the layer it is at, then continue

**Comment by Oliverxll** [comment]
![unnamed](https://user-images.githubusercontent.com/31373796/32139087-9d808a6c-bc40-11e7-8854-b26804165ab4.png)
This is what I am speaking about

**Comment by Dream-Master** [comment]
Maybe the pump code need to be checked.
@Technus 
@richardhendricks

**Comment by Dream-Master** [comment]
fixed
