### ISSUE TITLE
Lapotronic Cluster have 2 scan results.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2149]
2.0.1.3
Lapotronic Energy Orb cluster  have 2 output for scanner. Ultimate battery and Energy module.
How get scan result for both?
![default](https://user-images.githubusercontent.com/29812448/32151244-1b371648-bd67-11e7-93a0-05effa901ee0.png)
![default](https://user-images.githubusercontent.com/29812448/32151250-21e290e4-bd67-11e7-8ef6-dc1eb6d8d192.png)

**Comment by Dream-Master** [comment]
Yes need a fix
