### ISSUE TITLE
GregTech soldering iron does not repair EBF

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#215]
I used up almost 20 fine soldering iron wires, and it seems that the item count also bugs out when you click the maintenance hatch without any wires in your inv. It uses up the wires, the soldering iron does not loose durability or charge, and the circuit is still burned out. so the only way to reach 100% efficiency at the moment is to craft the duct tape

**Comment by Dream-Master** [comment]
Asking Blood Asp and waiting for answer.

**Comment by Namikon** [comment]
I derped. Soldering iron needs at least 10k charge to work
