### ISSUE TITLE
Copying Data Orbs turns them into empty Data Sticks.

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2152]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Put Data Orb with Indium Scan in the lower right field of the Scanner, empty Data Orb (5876:32707) in the left field, was expecting to copy that orb. Tried that with LV and IV Scanner.
#
#### What happend instead? (Attach screenshots if needed)
Got an empty Data Stick (5876:32708).
#
#### What do you suggest instead/what changes do you propose?
propper copy of the Data Orbs instead of turning them into Datasticks. Guess thats a bug.

**Comment by Dream-Master** [comment]
@Technus any idea here?

**Comment by Dream-Master** [comment]
@LOKKO12 Need more infos
