### ISSUE TITLE
Weird Quest behaviour (gold banded greatwood wand)

### ISSUE THREAD

**Issue by Radst0ne** [GTNewHorizons/NewHorizons#2153]
#### Which modpack version are you using?
2.0.1.3

NEI shows this recipe:
![2017-10-31_00 29 50](https://user-images.githubusercontent.com/27621272/32200585-acf88394-bdd2-11e7-95ae-3d601a2a2352.png)

This is the right recipe I guess?:
https://cdn.discordapp.com/attachments/234936569360809996/374700664284250125/unknown.png

But Quest unlocked weirdly
![2017-10-31_00 32 38](https://user-images.githubusercontent.com/27621272/32200750-7c3680d4-bdd3-11e7-9461-2b989c1453a6.png)

#
#### What do you suggest instead/what changes do you propose?
Vis costs are to high (35), fix NEI, fix Quest 237

**Comment by LOKKO12** [comment]
You must first craft the iron baneded one, and never look for TC recipes in NEI, look in Thaumonomicon.

**Comment by Bryfer** [comment]
NEI is showing the wrong recipie, check #1438 for more information

**Comment by Radst0ne** [comment]
oops didnt see that, but how you are supposed to craft this, the iron one can only provide 25 vis

**Comment by Dream-Master** [comment]
I thought thats was fixed?
@Bryfer
