### ISSUE TITLE
Suggestion: add UMV battery buffer 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2154]
#### Which modpack version are you using?
2.0.1.3
#
#### What do you suggest instead/what changes do you propose?
You can make a really ultimate battery, which is UMV voltage. However, you can't make a UMV voltage battery buffer, which seems wrong. I think you should add a crafting recipe to for the UMV battery buffers, and the supercharger thing that lets you add multiple amps. There's a battery for it, so you should be able to charge it

**Comment by Dream-Master** [comment]
@Technus

**Comment by Dream-Master** [comment]
Ok added buffers 1x, 4x 9x and 16x recipes for UEV, UIV and UMV
