### ISSUE TITLE
Styrene in large chemical reactor

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2155]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Put Benzene and Ethylene in large chemical reactor, extected Styrene and Hydrogen as in normal chemical reactor.
#
#### What happend instead? (Attach screenshots if needed)
Materials Voided.
#
#### What do you suggest instead/what changes do you propose?
Same recipe as in Chemical Reactor.

**Comment by Dream-Master** [comment]
Will check.

**Comment by Dream-Master** [comment]
i cant see such recipe
![image](https://user-images.githubusercontent.com/2970688/33449647-aa3241aa-d609-11e7-9444-be85c3d8dd4e.png)
![image](https://user-images.githubusercontent.com/2970688/33449658-ae8236d4-d609-11e7-9289-8cb957ca5092.png)
![image](https://user-images.githubusercontent.com/2970688/33449664-b39e6b10-d609-11e7-8a88-53b271493a36.png)
Thats all

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2740

**Comment by bartimaeusnek** [comment]
since the recipe got removed...
