### ISSUE TITLE
Suggestion: Desh and Meteoric Iron from UUM

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2156]
#### What do you suggest?
Add a recipe for Desh and Meteoric Iron from UUM, by scanning it and copying the recipe to a Dataorb.

**Comment by Dream-Master** [comment]
Only raw elements can be produced with uu.

**Comment by boubou19** [comment]
according to the tooltip, the symbol of Desh is De and the symbole of the meteoric iron is SpFe. They are raw in a way so add uu recipes for these two materials is not meaningless.

**Comment by Dream-Master** [comment]
Spfe seems not to be a element. Desh idk

**Comment by Dream-Master** [comment]
Only Elemnets are made from uu not chemical Compunds.

**Comment by Dream-Master** [comment]
@boubou19 if you understand how it works in gt code you can add it. I cant found it.
