### ISSUE TITLE
Advanced jetpack quest

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#2157]
The quest for the advanced jetpack requires wrong materials
![image](https://user-images.githubusercontent.com/30390927/32248457-cdd7fea4-be96-11e7-8051-9cfcdc92b725.png)
![image](https://user-images.githubusercontent.com/30390927/32248470-d4f91a56-be96-11e7-8dc7-e2575ec0445f.png)

**Comment by Dream-Master** [comment]
Did you try to reload your quests?
bq_admin default load

**Comment by RaggedCaster** [comment]
Yes, i did 
it's still broken
also looking at the config
"id": "gregtech:gt.blockmachines",
              "Count": 2,
              "OreDict": "",
              "Damage": 1642
is 4x Pt cable
But the recipe calls for 12x

**Comment by Dream-Master** [comment]
will check
