### ISSUE TITLE
Cetane-boosted diesel works in basic diesel generators

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2159]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I tried to put cetane-boosted diesel in a basic diesel generator, I expected it to either blow up or not accept it
#
#### What happend instead? (Attach screenshots if needed)
It accepted the cetane-boosted diesel and started producing power like normal.
![2017-11-01_20 08 15](https://user-images.githubusercontent.com/29802757/32303717-a5359f9c-bf40-11e7-8a86-f640ecc0c53f.png)

#
#### What do you suggest instead/what changes do you propose?
Either remove the tooltip on cetane-boosted diesel and basic diesel gens saying cetane-boosted diesel doesn't work, or make cetane-boosted diesel not work in basic diesel gens.

**Comment by LOKKO12** [comment]
Can confirm this is working in MP (Delta) too.

**Comment by Dream-Master** [comment]
Ok maybe that was a Bug in an earlier version. I will remove tooltip and  quest Book entry.
