### ISSUE TITLE
Player crash (/corruption) with Battlegear and Galacticraft using torches

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#2162]
How to reproduce:
1. Have torches in your battlegear slots
2. Go to a galacticraft planet with no atmosphere
3. Switch to the torch using R and mouse scroll

What happens:
You will crash with an internal server error.
Every time you try to login the same thing will keep happening

How to fix the situation:
Die. This will remove the torch from your slot and this error will not happen.
The easiest would be to have a moderator use /smite the second you are online.

The error itself:
in GalacticraftCore.jar micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkCurrentItem(EntityPlayerMP player)
The code checks if the held item is a torch, if yes, replace it with the galacti unlit torch.
Issue is that it tries to replace the item directly in the array:
player.field_71071_by.field_70462_a[player.field_71071_by.field_70461_c] = new ItemStack(torchItem, theCurrentItem.field_77994_a, 0);
But battlegear slots will not be there and you end up with an array out of bounds exception.

I am suggesting that galacticraft maintainer should rewrite the code so that it does not assume the index of field_70461_c will be in the array field_70462_a.

**Comment by Dream-Master** [comment]
@alphaest then please write a fix

**Comment by alphaest** [comment]
If you find someone to get the code, change 2 lines and compile it then-

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java
lines: 950 and 963 is currently this:
 if (torchItem != null)

change it to:
 if (torchItem != null && (player.inventory.currentItem >= 0 || player.inventory.currentItem < player.inventory.mainInventory.length))

this only makes the code not crash. I don't know MC code good enough to say how to fix it properly and do the unlit torch replacement in battlegear inventorys.

**Comment by Dream-Master** [comment]
mh not sure i could setup galacticraft right that i get 3 jars when make the change

**Comment by Dream-Master** [comment]
i try to get it working but to much errors
