### ISSUE TITLE
problem with the elite arc furnace

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2164]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
on delta
#
#### What did you try to do, and what did you expect to happen?
i wanted to input oxygen in an elite arc furnace
#
#### What happend instead? (Attach screenshots if needed)
i can't input oxygen in it:
![2017-11-02_18 12 48](https://user-images.githubusercontent.com/12850933/32340259-5cb85cc2-bffa-11e7-87b9-74f9e463c945.png)
pipes don't want to connect with the elite arc furnace.
in addition of that, the tricorder don't see its internal tank:
![unknown 1](https://user-images.githubusercontent.com/12850933/32340386-c2103504-bffa-11e7-8e25-f228e36263e2.png)
in comparaison this is the scan of advanced arc furnace IV:
![unknown](https://user-images.githubusercontent.com/12850933/32340441-e1e27aea-bffa-11e7-888d-4c8cb21c2013.png)

#
#### What do you suggest instead/what changes do you propose?
i suggest to fix the internal tank of the elite arc furnace

**Comment by Dream-Master** [comment]
indeed it was 0. I fixed it now in dev.
