### ISSUE TITLE
[Suggestion] More Uses for Talc/Soapstone

### ISSUE THREAD

**Issue by MainFreak** [GTNewHorizons/NewHorizons#2166]
Talc is one of the more common yet useless ores in the overworld since it can, currently, only be electrolyzed down or converted to Lubricant. My suggestion would be to make it an ingredient of Thaumcraft's Tallow Block which you use to create tallow golems and sanitizing soap. Also maybe as alternative dyeLime item?

**Comment by Dream-Master** [comment]
Yes why not. Will look for uses in  recipes.

**Comment by richardhendricks** [comment]
https://en.wikipedia.org/wiki/Talc

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33442470-82e2c26e-d5f5-11e7-9e14-00c25c9407be.png)

**Comment by richardhendricks** [comment]
I disagree that talc is "more common", but I like this change.  Don't need to mobfarm rotten flesh for my tallow golems any more. :D

**Comment by MainFreak** [comment]
Awesome!
