### ISSUE TITLE
Findint appatite quest

### ISSUE THREAD

**Issue by Meyzz** [GTNewHorizons/NewHorizons#2168]
#### Which modpack version are you using?

Last
#### If in multiplayer; On which server does this happen? 
Dirthurt
#

Finding appatite quest, i can find appatite, but i cant find pyrochlore ore and cant find any info about this ore

**Comment by Dream-Master** [comment]
because the mix was changed. I add a quest to get this ore for some coins.

**Comment by Dream-Master** [comment]
I add a Quest
![image](https://user-images.githubusercontent.com/2970688/33442121-a2719d4a-d5f4-11e7-894b-c36c6fa4b8a0.png)
