### ISSUE TITLE
Nano goggles of revealing recipe issue

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#2169]
#### Which modpack version are you using?
2.0.1.3

#### What did you try to do, and what did you expect to happen?
Tried to infusion craft nano goggles of revealing.
#
#### What happens instead? 
Crafting does not start - most likely because of bad metadata of electric goggles of revealing.
Also the damage values of energy crystal and nanosuit helmet are most likely broken too.
And the recipe is shown requiring IC2 nano circuits. Are the GT better HV ones usable there? If not, I suggest making all HV circuits usable in every TC recipe.
#
#### What do you suggest instead/what changes do you propose?
Use valid damage values for these 3 items.

**Comment by Dream-Master** [comment]
@RaggedCaster try with newest script and report to me please.
Important is the recipes need to show in Nei, Thaumcraft Book and work correctly.

https://github.com/GTNewHorizons/NewHorizons/pull/2228
