### ISSUE TITLE
Minetweaker Issue again

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#217]
It is again the Problem with the Double Point. Need help with its. I want to remove the Sawas and Inguana Tweaks and Project Red Saws not working:

https://github.com/MrTJP/ProjectRed/issues/811
https://github.com/stanhebben/MineTweaker3/issues/194
https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/149

**Comment by Namikon** [comment]
I still think that the space there is just for readability. It somehow doesn't find the items, which could be another issue with the mod-load order like we had with LogisticsPipes. As I already said, debugging a code like minetweaker is rather difficult, I'd like to wait for the replies of the original authors first before I start digging around

**Comment by Dream-Master** [comment]
@Namikon than no new Saw Recipes for now.
FTP Access not working. Sent you a Mail.

**Comment by Dream-Master** [comment]
I let the Swas out for now not known why it don't work.

**Comment by Dream-Master** [comment]
jaredlll08 reopen the issue maybe we get a solution.

**Comment by Dream-Master** [comment]
https://github.com/stanhebben/MineTweaker3/issues/194#issuecomment-137738785

**Comment by Dream-Master** [comment]
Problem is solved in Minetweaker Version 3.0.10
