### ISSUE TITLE
Quest #328 "Hold all the foci" on page "Kaaami, Haaaami, ... HA!" impossible to complete

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#2170]
Modpack: 2.0.1.3
The quest objective has ignoreNBT:false and then lists the tag:
              "tag": {
                "Inventory:8": ""
              }

But in code the thaumcraft pouch always uses:
NBTTagList var2 = new NBTTagList();
item.func_77983_a("Inventory", var2);

TagList is of type 9, not 8, which is a string. So therefor it seems to be impossible to ever get the correct match.

What to do:
Set the quest task to ignoreNBT:true

**Comment by Dream-Master** [comment]
Ok will change
