### ISSUE TITLE
Server hangs due to Lagg when activate Magic Map in Overworld

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2171]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Activated Magic Map, thought it would be like a big Map.
#
#### What happend instead? (Attach screenshots if needed)
Server froze due to lag. When i disconnected, lagging stopped. EDIT: Managed to unbug my profiele by reconnecting and dropping the map quickly after reconnect.
#
#### What do you suggest instead/what changes do you propose?
Make the Map only aviable in Twilight Forest/Fix it/Disable it completely.

**Comment by Dream-Master** [comment]
I could use disallowed in the overworld

**Comment by KaneHart** [comment]
Would this be via the core mod? I hope so it be nice to have this on all servers.

**Comment by Dream-Master** [comment]
Yes via block limiter mod cfg.

**Comment by Dream-Master** [comment]
Sadly not working with Block limiter because a new item is spawnt before the command works.

**Comment by Dream-Master** [comment]
I can add only a commnet under the item

**Comment by Dream-Master** [comment]
Ok i remove crating of the item and make a reapeatable quest every 24 h
