### ISSUE TITLE
Tinker-Time quest failing to detect 

### ISSUE THREAD

**Issue by wingedseahorse** [GTNewHorizons/NewHorizons#2172]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Crafted all the items for the Tinker-Time quest, only the tool station and pattern chest were detected
#
#### What happend instead? (Attach screenshots if needed)
two of the crafted items were not detected, the part builder and stencil table, so the quest did not complete
#
#### What do you suggest instead/what changes do you propose?
fix so the items are detected when crafted

**Comment by Dream-Master** [comment]
I guess you not craft it with the right wood type (oak)

**Comment by wingedseahorse** [comment]
Seem likely. But depending on your starting biome you might not have a lot of oak to use so its frustrating if you have to make them again just to be detected. (ofc i just used cheats to auto complete the quest rather than waste resources)

**Comment by Dream-Master** [comment]
I could add a quest exchange oak woof logs for other logs and a few coins.

**Comment by Ethryan** [comment]
How about a sapling exchange instead?
