### ISSUE TITLE
Catwalk crafting unbalanced

### ISSUE THREAD

**Issue by eloquentJane** [GTNewHorizons/NewHorizons#2173]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Checked crafting recipes for catwalks. Expected them to be cheaper if made in the assembler than if made in an ordinary crafting table.
#
#### What happend instead? (Attach screenshots if needed)
Catwalks take more steel to make in an assembler than by using the recipe in an ordinary crafting table.
#
#### What do you suggest instead/what changes do you propose?
Increase the recipe yield for making catwalks in an assembling machine so that players do not have to craft them manually to obtain the best material efficiency.

**Comment by Dream-Master** [comment]
Fixed in dev.
