### ISSUE TITLE
GT Oil Refinary not going

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2174]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 
dirthuts
#
#### What did you try to do, and what did you expect to happen?
Built a Tier 3 Oil Rig, and set it up.   Setup fully,  Scanned ground and confirmed "Heavy Oil" and "Coal and Emerald" in ground.

#
#### What happend instead? (Attach screenshots if needed)
Tier 3 Controller shows no errors gives message "hit with soft mallet"
Hit with mallet, turns on then off
No oil or Mining Pipes goes out

#
#### What do you suggest instead/what changes do you propose?
Check to see if GT Oil code has broken since the 2.1 patch

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Technus** [comment]
needs EV or IV power min?

**Comment by Dream-Master** [comment]
@devanchya can you test this and report back? Thanks

**Comment by devanchya** [comment]
gave it EV and IV power to test. No movement.

**Comment by Dream-Master** [comment]
@Technus
