### ISSUE TITLE
Fine osmiridium wire. Wrong recipes.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2175]
2.0.1.3

![default](https://user-images.githubusercontent.com/29812448/32440860-bfe5ffc2-c340-11e7-97ea-4939d5df9a90.png)
![default](https://user-images.githubusercontent.com/29812448/32440718-1b767cd2-c340-11e7-94d9-d517ed08b3bb.png)
Regular osmiridium wire not exists.

**Comment by Proha5** [comment]
Will this be fixed?

**Comment by Dream-Master** [comment]
I fixed it already in dev.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33437487-656d7790-d5e8-11e7-87fd-d0fb646cbfa9.png)
![image](https://user-images.githubusercontent.com/2970688/33437493-6901ff2a-d5e8-11e7-8535-7d4964c269cd.png)
