### ISSUE TITLE
[2.0.1.3] Suggestion: Add a Steve's Carts 2 Iron Plate Cutting Recipe to make Iron Pane's

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2177]
Right now there is a recipe in the assemblers for all of the Plates besides Iron Plate to a Steve Carts Iron Pane.

In the assembler 1 iron Plate = 2 Iron Pane this would match the hand held recipe of a saw.

**Comment by Dream-Master** [comment]
I could add ic2 item casings because iron plates allready used in this recipe in the cutting saw.

**Comment by Dream-Master** [comment]
The recipes was there but not shown because was overrriden.
