### ISSUE TITLE
[2.0.1.3] Suggestion: Add a Sign Recipe to the Assembler.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2178]
We use signs quite a bit and hoping down the road to see an assembler recipe with more output vs the crafting table method. Maybe 6 Oak Planks (covers) and 1 stick for say 4-5 output? Would this effect burn time balancing?

@electrobot request it's not a must but nice one to see.

**Comment by Dream-Master** [comment]
Sure why not.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33436843-74e833ce-d5e6-11e7-9e8d-b3a61bdc7448.png)
