### ISSUE TITLE
Quest #991 "Dark steel armor basic upgrades" and #998 "Dark steel tool and weapon basic upgrades" broken

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#2179]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Crafted the armor and tools using vibrant crystal in a anvil, charged full like on the quest third task and expected it to detect my items but it did not.
#
#### What happend instead? (Attach screenshots if needed)
I have exactly the same items as on the quest - 100% dura, 100% charged and each with a vibrant crystal "Empowered" text.
https://imgur.com/a/i9XsM

#
#### What do you suggest instead/what changes do you propose?
I checked the quest script and everything looks like it should so i got no idea why it does not work.

**Comment by Dream-Master** [comment]
Maybe some stupid nbt tag or so.

**Comment by alphaest** [comment]
Fully upgraded all items following the quest chain and they don't get accepted either.
![image](https://user-images.githubusercontent.com/18067746/32700368-a458bf0c-c7cc-11e7-9895-a2388b45a448.png)

So quests #999 and #997 are also impossible to complete.

**Comment by eloquentJane** [comment]
I was able to complete the quest for empowering the dark steel armor, but the one for getting it fully upgraded is impossible. The quest for adding all the upgrades to the dark steel armor is only broken for me because it won't register the potions in my inventory (I have no idea whether that is because potions don't stack, or for some other reason).

**Comment by Dream-Master** [comment]
Will check

**Comment by alphaest** [comment]
@eloquentJane i had a night vision potion from a TC loot bag that had the wrong meta id. Try crafting one yourself.

**Comment by Dream-Master** [comment]
i need to check Quest. I cant ignore nbt tags otherwise the quest will be completed with any armor (empty one)

**Comment by Dream-Master** [comment]
@alphaest i need the exact date from your items. Use /mt hand on them and post it here.

**Comment by Dream-Master** [comment]
My results: Sword, Pick, Axe, Shears

<EnderIO:item.darkSteel_sword>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_pickaxe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_axe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_shears>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
And second stage (quest)

<EnderIO:item.darkSteel_sword>.withTag({"enderio.darksteel.upgrade.travel": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 8 as short}, level_cost: 30, unlocalized_name: "enderio.darksteel.upgrade.travel"}, "enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
<EnderIO:item.darkSteel_pickaxe>.withTag({"enderio.darksteel.upgrade.travel": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 8 as short}, level_cost: 30, unlocalized_name: "enderio.darksteel.upgrade.travel"}, "enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}, "enderio.darksteel.upgrade.spoon": {upgradeItem: {id: 277 as short, Count: 1 as byte, Damage: 0 as short}, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.spoon"}})
<EnderIO:item.darkSteel_axe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
<EnderIO:item.darkSteel_shears>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
