### ISSUE TITLE
[2.0.1.3] Few Quest Adjustments in Forestry and Farms!

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2182]
Some quest adjustments / tweaks.

Now I'm not sure if you are trying to prevent recipe scrolling, etc. If so maybe it's time we add some sort of UI Icon Red Arrow down or something to show there is more things further down the page. Either way I'm going report these unless told otherwise.

**Missing Parts:**
Tubes - 581: Missing 2 Fine Copper Wire
Multiblock farm: Hatch - 589: is missing one Motor for a requirement.
Multiblock farm: Control Block - 591: is missing one Motor for a requirement.

**Comment by KaneHart** [comment]
I'm going reply to this instead in case it's on purpose. 

Multiblock farm: Hatch #589 is missing one Motor for a requirement. 
Multiblock farm: Control Block #591 is missing one Motor for a requirement.

**Comment by Dream-Master** [comment]
No: Tubes - 581: Missing 2 Fine Copper Wire
they have 4 fine wires for two Tubes
![image](https://user-images.githubusercontent.com/2970688/33435234-f4b0dffc-d5e1-11e7-9a9c-b05f25340e6a.png)
![image](https://user-images.githubusercontent.com/2970688/33435242-f8997b88-d5e1-11e7-89ad-967ecbbe064d.png)
