### ISSUE TITLE
Raw Lapotron Crystal use

### ISSUE THREAD

**Issue by Dr4cos** [GTNewHorizons/NewHorizons#2183]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
The Raw Lapotron crystal to a full one is only works with the Advandced Circuits from IC2
#
#### What do you suggest instead/what changes do you propose?
Maybe it should work with all the HV tier circuits?

**Comment by ko5h** [comment]
are you sure?
Lapotron crystal created through any HV circuit
https://imgur.com/cV6M6ac https://imgur.com/AnMm3jB https://imgur.com/PefXry3
p.s. 2.0.1.3

**Comment by Dr4cos** [comment]
oO ok will test again the nei only shows the reciept of the advanced circuits

**Comment by ko5h** [comment]
@Dr4cos https://drive.google.com/file/d/0B4LTCSQaEGN1d3pldHVyWk1xTVE/view
if u play in sp or you have your server...create in folder scripts zz.sc  and paste this

> // --- Circuit ---
> //-LV-
> <IC2:itemPartCircuit>.addTooltip(format.red("LV-tier"));
> <gregtech:gt.metaitem.01:32701>.addTooltip(format.gold("LV-tier"));
> <gregtech:gt.metaitem.03:32078>.addTooltip(format.yellow("LV-tier"));
> //-MV-
> <gregtech:gt.metaitem.01:32702>.addTooltip(format.red("MV-tier"));
> <gregtech:gt.metaitem.03:32079>.addTooltip(format.gold("MV-tier"));
> <gregtech:gt.metaitem.03:32080>.addTooltip(format.yellow("MV-tier"));
> //-HV-
> <IC2:itemPartCircuitAdv>.addTooltip(format.gold("HV-tier"));
> <gregtech:gt.metaitem.01:32703>.addTooltip(format.yellow("HV-tier"));
> <gregtech:gt.metaitem.03:32082>.addTooltip(format.green("HV-tier"));
> //-EV-
> <gregtech:gt.metaitem.01:32704>.addTooltip(format.yellow("EV-tier"));
> <gregtech:gt.metaitem.03:32083>.addTooltip(format.green("EV-tier"));
> <gregtech:gt.metaitem.03:32085>.addTooltip(format.aqua("EV-tier"));
> //-IV-
> <gregtech:gt.metaitem.01:32705>.addTooltip(format.yellow("IV-tier"));
> <gregtech:gt.metaitem.03:32084>.addTooltip(format.green("IV-tier"));
> <gregtech:gt.metaitem.03:32086>.addTooltip(format.aqua("IV-tier"));
> <gregtech:gt.metaitem.03:32089>.addTooltip(format.blue("IV-tier"));
> //-LuV
> <gregtech:gt.metaitem.01:32706>.addTooltip(format.green("LuV-tier"));
> <gregtech:gt.metaitem.03:32087>.addTooltip(format.aqua("LuV-tier"));
> <gregtech:gt.metaitem.03:32096>.addTooltip(format.blue("LuV-tier"));
> <gregtech:gt.metaitem.03:32092>.addTooltip(format.darkPurple("LuV-tier"));
> //-ZPM-
> <gregtech:gt.metaitem.03:32088>.addTooltip(format.aqua("ZPM-tier"));
> <gregtech:gt.metaitem.03:32090>.addTooltip(format.blue("ZPM-tier"));
> <gregtech:gt.metaitem.03:32093>.addTooltip(format.darkPurple("ZPM-tier"));
> //-UV-
> <gregtech:gt.metaitem.03:32091>.addTooltip(format.blue("UV-tier"));
> <gregtech:gt.metaitem.03:32094>.addTooltip(format.darkPurple("UV-tier"));
> //-MAX-
> <gregtech:gt.metaitem.03:32095>.addTooltip(format.darkPurple("MAX-tier"));

for easy search in nei&ae2 https://imgur.com/Ja5cB3O https://imgur.com/kDhx6hX
