### ISSUE TITLE
EBF Fluid hatches have only 1 allowed access side

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/NewHorizons#2184]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
GTNH Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Before 2.0.1.3 we was on 2.0.0.0. I had 2 MV Pumps attached to my EBF's Fluid input hatch. One set to import and the other export. When I needed to change fluids, I could just toss drums where I needed them. 
#
#### What happend instead? (Attach screenshots if needed)
Now the pumps only work if I wrench the port (The hole) toward the pump I want to use. I can still import and export but only if I change port direction.
#
#### What do you suggest instead/what changes do you propose?
If this was a change, revert back to being able to withdraw or add to the other sides of the hatch. Building an EBF per type is ok but quite resource demanding. This is better early on, to be able to exchange fluids

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Dream-Master** [comment]
Have this something to do with force one side? @Technus

**Comment by Technus** [comment]
Everything matches GT5u.
there are many ways to get around that, like rotating the hatch on corner

**Comment by Lithorn** [comment]
Was only an issue in 2.0.1.3. Worked fine in 2.0.0.0

**Comment by Dream-Master** [comment]
We wll see in 2.0.2.0 if it works.
