### ISSUE TITLE
I burn to death every time I break my grave because of non existing creosote, please help me

### ISSUE THREAD

**Issue by LightBane** [GTNewHorizons/NewHorizons#2185]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried picking up a bucket of lava, but the game thought my empty bucket was still full of creosote oil for some reason.
#
#### What happend instead? (Attach screenshots if needed)
I started taking continuous damage, even after jumping out of the area where the lava block was (the lava was still there btw). There was no burning display on my character’s vision, and the creosote was not phisically touching me, as I could walk through it without swimming or getting slowed down by it, and in addition it was not even visible. After returning to my grave, I found that where I was taking damage before, I was fine now, so I broke the grave, and suddenly I started burning again...
#
#### What do you suggest instead/what changes do you propose?
I ask for help as I can’t survive after getting back my stuff from the grave. Thanks

**Comment by Methes** [comment]
If I understand correctly you have a bucket of lava in your inventory. That's what's causing you taking damage. After picking up the items from your grave, toss the bucket out of your pockets and you should be fine.

**Comment by LightBane** [comment]
I’ll try that, thanks. Sorry if I explained the issue confusingly, my bad.

**Comment by LightBane** [comment]
The bucket was the cause. It was full of lava, so I emptied it and now it’s safe to handle, issue closed, hurray!!!

**Comment by Dream-Master** [comment]
Using gloves in Baubles slots protect you too.

**Comment by LightBane** [comment]
I had to find out the hard way. Should have followed the quest line more closely, sorry. I’ll try and look into my errors before posting again.
