### ISSUE TITLE
[2.0.1.3] Nerf Bat Request GC Parachute and Lander Tier 2 Basic Mats.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2186]
I was just surfing NEI and besides the actual Lander the Parachutes and such are made out of String, Paper, and Wood lol.

I assume this was a oversight. It just kind of ruins the entire immersion. 

![md236ru](https://user-images.githubusercontent.com/425853/32628790-fddc272c-c564-11e7-9781-fa13656f74a5.png)
![vorhwdo](https://user-images.githubusercontent.com/425853/32628799-084cbcb2-c565-11e7-8572-ca2e3cab81d7.png)
![m0kfzes](https://user-images.githubusercontent.com/425853/32628813-12e55738-c565-11e7-92ca-249387414ccb.png)

**Comment by Dream-Master** [comment]
Well I could add it to assembler?

**Comment by noobyaran9** [comment]
Change the canvas to use pams' woven cloth. Thats about it.

**Comment by KaneHart** [comment]
Well using paper seems a bit silly the woven cloth might not be a bad ideas. Are bees at all needed for real progression or can be skipped? Woven Silk might be interesting. TBH some sort of chemical applied to cloth would be more interesting. Or some sort of fiber mesh with some sort of strength to it. 

It just seem a bit funny and silly but it's all suggestions.

**Comment by noobyaran9** [comment]
> Well using paper seems a bit silly the woven cloth might not be a bad ideas. Are bees at all needed for real progression or can be skipped? Woven Silk might be interesting. TBH some sort of chemical applied to cloth would be more interesting. Or some sort of fiber mesh with some sort of strength to it.

It just seem a bit funny and silly but it's all suggestions.

No. Do not drag bees into real progression. You will drive even more people away from this modpack.
The lander tier 1 is complicated enough.
Just woven cloth from pam's is good enough to nerf this recipe.

**Comment by KaneHart** [comment]
All good I know how touchy you guys are on balance 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 

Also github really should get away with the emoji's this not suppose to be Facebook.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33434893-f3e7daa4-d5e0-11e7-9fca-8e4d3e9335c6.png)
![image](https://user-images.githubusercontent.com/2970688/33434900-fb37517c-d5e0-11e7-915c-78f2acef14df.png)
![image](https://user-images.githubusercontent.com/2970688/33434909-035a979c-d5e1-11e7-9159-72b2d5f921b3.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33434946-25bedde8-d5e1-11e7-9300-6f9369a55aad.png)
