### ISSUE TITLE
Right click on Forestry farm hatch closed server.

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2189]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Right clicked on a Forestry farm hatch, expect farm UI to open.
#
#### What happend instead? (Attach screenshots if needed)
Server closed. (10.11.17, 04:54)

**Comment by KaneHart** [comment]
Any chance this happen a 2nd time? Also any client side logs that you can see that might be useful?

**Comment by LOKKO12** [comment]
I checked client side logs, nothing. This seems to happen randomly.

**Comment by Dream-Master** [comment]
need to check serverlog.

**Comment by Dream-Master** [comment]
[crash-2017-11-10_04.53.58-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1464308/crash-2017-11-10_04.53.58-server.txt)

**Comment by Dream-Master** [comment]
This crash we have now serveral times.

**Comment by Dream-Master** [comment]
@HellFirePvP any idea/fix ?

**Comment by HellFirePvP** [comment]
His is unrelated to him opening the forestry GUI of some block. It just happened to happen at the same time. This is connected to the Break-Core of Gadomancy and it seems that there's some odd inconsistency in sorting, which shouldn't actually be the case..
However, i can't really suggest a fix except "only link the break-core to 1 position and NOT multiples" - which makes it all kinda awkward...

**Comment by Dream-Master** [comment]
@HellFirePvP any news here?
