### ISSUE TITLE
Forge Microblocks Diamond Saw

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#219]
You need the diamond saw to start of with ProjectRed transportation. Currently this needs a flawless diamond (or better) which needs to be produced in the precicion laser engraver.

Is it intended to be this late?

**Comment by Namikon** [comment]
You can get flawless or even exquisite diamonds by mining small diamond ores with a Fortune II+ pickaxe

**Comment by Teteros** [comment]
Ah, so that's how Careface found his flawless diamond.
Nice tip.

**Comment by Dream-Master** [comment]
Can this be closed?

**Comment by Namikon** [comment]
Yes
