### ISSUE TITLE
clay blocks from water+clay only have an iron bucket recipe

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2190]
#### Which modpack version are you using?
2.0.1.3

#### What did you try to do, and what did you expect to happen?
Making clay blocks with the fired clay bucket and clay, can't see why you can only do it with the iron bucket.

#### What do you suggest instead/what changes do you propose?
Add the same recipe but with fired clay bucket instead of iron bucket.

**Comment by Dream-Master** [comment]
Not even sure which mod add this recipe.

**Comment by Dream-Master** [comment]
No i wont because at the start you need to make clay dust with the mortar the hard way.

**Comment by WarlordWossman** [comment]
It doesn't add any difficulty tbh.
Just doesn't make sense since it's not consistent with other water bucket recipes for which you can always use both buckets. (At this point it just feels like bad game design).

Since I played early game 10+ times anyways I can tell you that people that take the iron bucket reward in the coke oven quest or simply craft a bucket (+hammer) before any quests suggest to do so don't run into this anyways.

So yeah it's basically just a bad design and many youtubers have run into it since the rest of the pack gives you the feel that clay bucket and iron bucket are both equally viable in terms of water use.

It's one of the wonky things leftover next to the wood slab recipe that forces you to use oak wood when crafting fences needed in other recipes.

**Comment by Dream-Master** [comment]
Mh let me think of it again
