### ISSUE TITLE
"Apiarist's Cloth" quest impossible

### ISSUE THREAD

**Issue by eloquentJane** [GTNewHorizons/NewHorizons#2191]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Attempted to complete "Apiarist's Cloth" quest. Expected it to be possible.
#
#### What happend instead? (Attach screenshots if needed)
The quest has a "crafting task" for items which can only be made in an assembling machine. Thus it cannot be completed
#
#### What do you suggest instead/what changes do you propose?
Change the crafting task to a retrieval task.

**Comment by Ethryan** [comment]
This has already been fixed.

**Comment by Bryfer** [comment]
Execute /bq_admin default load to refresh the quests after each update

**Comment by KaneHart** [comment]
would recommend close. as this was fixed in a past version and not in 2.0.2.0

**Comment by Dream-Master** [comment]
No it wasn't fixed in 2.0.1.3

**Comment by KaneHart** [comment]
Yeah version we are using so why is this here your github confuses me at times lol

**Comment by Dream-Master** [comment]
😁

**Comment by KaneHart** [comment]
Oh wait you said it's not fixed ffs I'm an idiot haha. I get it now ffs I really need sleep.

**Comment by Dream-Master** [comment]
Good night then.

**Comment by Dream-Master** [comment]
I fix it but will check later

**Comment by Dream-Master** [comment]
Will be in the next version

**Comment by KaneHart** [comment]
Oh yeah that is fine I just thought it was working fine and I was being an idiot haha. I don't mind waiting :) Easy fix :) Enjoy your holidays!
