### ISSUE TITLE
GT Pump power issue / Oil Drilling Rig low value

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2193]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
dirt huts
#
#### What did you try to do, and what did you expect to happen?
First, I tried to use the GT Basic Pump (LV) with mixed results.
#1 It worked fine above the original oil field.
#2 It worked again after moving the Pump inside the oil field (next chunk)
**#3 It wouldn't start at all when moving it for the third time.  I moved it into several positions and it just wouldn't start.  Portable Scanner says it needs more power.**

#4   I set up the GT Basic Pump again in a new oil field.  This time it worked briefly until it got a tiny bit of rain on the block next to it and blew up...  my mistake :)

**#5 I crafted the GT Advanced Pump II (HV) and tried again.  Again the needs more power message and the Pump just won't start.  (screenshot attached)**

---sidenote--- When the Pump was working, I watched it carefully; the GT Pump appears to try and pickup flowing water/oil which gives nothing a lot of the time.  Is this intended?

#
#### What happend instead? (Attach screenshots if needed)
See above 

Screenshot - [http://213.48.63.6:5003/gtpump.png](url)

#
#### What do you suggest instead/what changes do you propose?
#3 and #6 = The GT Pump's should just work

**Comment by tranceplanet** [comment]
Further to this.  It appears I found a way to tunnel through Bedrock ..

1. I placed an Advanced Miner and let it start the mining pipe process.
2. After 2 pipes, I broke the Advanced Miner and replaced it with the GT Advanced Pump II.
3. The Pump did nothing as expected but it was full of mining pipes.  After breaking the mining pipe immediately underneath the Pump.  All mining pipes were deployed straight down to and through Bedrock.  Yet the machine still said it didn't have enough power.

**Comment by Methes** [comment]
I'm having problems with the LV GT Pump stopping pumping Oil after running flawlessly for 2 months.
It just consumes power with no output or work.
The whole area is chunkloaded for months.
I've noticed the lowest pipe block is two blocks below the Oil surface with many source blocks remaining above it, like it skipped a few layers before failing.

**Comment by mitchej123** [comment]
Working through a fix.  Currently when the chunk unloads it doesn't save that it has work, and clears the work list.  When the chunk reloads it thinks it's just been placed so it immediately moves down. Current fix in progress is to have it save a state that it's currently pumping, and upon reload realize this and rebuild the pump list rather than immediately moving down. 

Working through a few other cases of weird behavior and will throw up a PR with the fix(es).

**Comment by KaneHart** [comment]
Thanks @mitchej123 was going to add to this post of other issues I had but I assume their covered! Right now a suggested Pump to use would be the thirsty tank.

**Comment by mitchej123** [comment]
I'm currently working on the single block pump and the two main issues there are 
1) dealing with unloading/loading chunks -- right now it immediately moves down
2) it's pretty easy to bug the pump and punch through bedrock
3) Stretch goal: Retract pipes when finished pumping

Anything else, feel free to add and I'll take a look as time allows

**Comment by KaneHart** [comment]
On my server a lot of times the tile entity that spawns (the pump block) will not at times and we have to reboot the entire server. Pretty much it will take the 1 block under it fluid wise then never again till a reboot. Then of course a lot of times after a reboot the whole moves down and skips anything outside of it issue as you pointed.

Love the stretch goal :)

**Comment by Dream-Master** [comment]
@mitchej123 let me know when your fix is done.

**Comment by mitchej123** [comment]
Will do.  (1) is fixed, looking into (2) punching through bedrock right now.

**Comment by Dream-Master** [comment]
Ok

**Comment by mitchej123** [comment]
Should be addressed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/54
