### ISSUE TITLE
Input Spell Cable 4619:14 uncraftable

### ISSUE THREAD

**Issue by alphaest** [GTNewHorizons/NewHorizons#2197]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Both in MP and SP
#
#### What did you try to do, and what did you expect to happen?
When you look in NEI the item recipe for input and output spell cables, they are just vertically flipped. But when you try to craft them, both of the recipes give the same item - Output Spell cable.
#
#### What happend instead? (Attach screenshots if needed)
Crafting table/ae/crafting station/bench:
![image](https://user-images.githubusercontent.com/18067746/32848199-837be466-ca34-11e7-8b27-5978f76ea972.png)
NEI:
![image](https://user-images.githubusercontent.com/18067746/32848218-927c516c-ca34-11e7-868a-20cb275a88b0.png)

#
#### What do you suggest instead/what changes do you propose?
Fix the recipe for it so that the actual recipe reflects what NEI shows.

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
works now tested.
