### ISSUE TITLE
Empty Cell Duplication Bug

### ISSUE THREAD

**Issue by eloquentJane** [GTNewHorizons/NewHorizons#2198]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Checked recipes for making raw rubber out of isoprene. Expected no dupe bug.
#
#### What happend instead? (Attach screenshots if needed)
When using isoprene cells (specifically isoprene in the cells, and oxygen/air in the fluid input), the recipe looks to result in more cells than are input. 6 extra cells from reacting an isoprene cell with air, and 20 extra cells from reacting an isoprene cell with oxygen.
#
#### What do you suggest instead/what changes do you propose?
I suggest modifying the recipe to fix the apparent duplication bug.

**Comment by Dream-Master** [comment]
will do.
