### ISSUE TITLE
Can't get the scan for the ultimate battery

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2199]
#### Which modpack version are you using?
2.0.1.3
#
The ultimate battery requires you to scan an LuV lapotron orb, however scanning the orb has 2 scanning outputs. Scanning it always gives you the data for the ZPM lapotron orb, instead of the ultimate battery. 
https://i.imgur.com/4FLWJyU.png
https://i.imgur.com/csDIwc0.png

**Comment by Dream-Master** [comment]
Known bug

**Comment by Bryfer** [comment]
How it would be done

* This issue is already reported #2149

*<Mark as dupe, close issue.>

* Add new information to old issue if needed.
