### ISSUE TITLE
Backpacks mod deleting items when upgraded

### ISSUE THREAD

**Issue by Aarkainum** [GTNewHorizons/NewHorizons#2200]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
 Stone Legion.
#
#### What did you try to do, and what did you expect to happen?
Upgrading backpacks from the Backpack mod.
#
#### What happend instead? (Attach screenshots if needed)
 The mod gives no warning that items will be deleted when you upgrade.
#
#### What do you suggest instead/what changes do you propose?
 A tooltip change to warn players about it.

**Comment by Dream-Master** [comment]
Why the hell you upgrade a full backpack? Will add a tooltip

**Comment by KaneHart** [comment]
Lmao @Dream-Master Either way dumb mod for having the issue I mean we have a different level of thinking but you have to remember most players don't think the same.

**Comment by Bryfer** [comment]
Dupe issue apperently still stupid that people still don't understand this, maybe someone else is stupid for not knowing the common knowledge level of Minecraft mods for new players
But sure keep calling people idiots for not understand this very unclear issue. You'll get alot of players this way.

@1157
I'm pretty sure you told me dream that it was impossible to add this text

Anyway as usual this is a duped issue. Why not close it?

**Comment by Dream-Master** [comment]
Will check if it is possible

**Comment by KaneHart** [comment]
![fadv6td](https://user-images.githubusercontent.com/425853/32989927-ab5c6882-cced-11e7-9456-aceed38a444e.png)

**Comment by KaneHart** [comment]
The code I used for testing this might not be correct or proper but it seem to have no effect on any other tool tips.

`<Backpack:backpack:*>.addTooltip(format.red("Idiots - Dream 2017!"));`

And you can go crazy with multiple lines too:
![jlturiu](https://user-images.githubusercontent.com/425853/32989950-0e733d2e-ccee-11e7-8d90-9d113d2c584a.png)

**Comment by Dream-Master** [comment]
Yes with minetweaker it should  work

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33427691-7988238c-d5c6-11e7-8eef-df405db7dc95.png)

**Comment by KaneHart** [comment]
I approve! Dream 2017!

**Comment by richardhendricks** [comment]
I approve this code change.
