### ISSUE TITLE
[2.0.1.3] Wither Skeletons Hardly spawn in Fortresses.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#2201]
Server: Stone Legion
Issue: Lack of Wither Skeletons
Version: 2.0.1.3
Recommendations: Remove Lava Monsters, Maybe add Wither Skeletons to Global Nether Spawns?

Our server has been having issues with Wither Skeletons spawning in Fortresses. We do have structure saving enabled but they are still quite beyond rare to spawn. We tweaked somethings and we found removing Lava Monsters mod helped quite a bit but not enough to be worth while not on a larger SMP Server.

I'm wondering if there is nothing we can think of  as improving them globally in the nether to maybe if you don't think their too unbalanced. As far as I know besides going through Ender IO Spawners you can't move a spawner till you spawn a wither boss and kill them at least once. 

I also Highly recommend removing Lava Monsters. It serves nothing but to eat up 25%+ Of the spawn mobs allocation and they are not even challenging in anyway and easily avoidable. They just sit in lava like crazy in the nether and the overworld just lagging both the client and server and using up spawn allocations. 

If anyone has suggestions on Wither Skeletons I would love to hear them. It would be nice to add them in a smaller spawn chance globally in the Nether if one the mods support it.

**Comment by Dream-Master** [comment]
Lava monsters are removed in the next update.

**Comment by KaneHart** [comment]
Thanks mate, great call!
