### ISSUE TITLE
explosion on death mechanic makes animal farms a pain

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2202]
So making normal animal farms can be a pain with the explosion on death mechanic because the small animals have less health and the big ones sometimes lose quite a lot of health due to a GT mechanic that damages entities if there is more than 3 in one block space.

I know you can build pam's animal traps but I think normal animal farms should still be something you should be able to go for, there is even a quest for animal farms.

The explosion on death mechanic is quite a gimmick imo but I had an idea that might be quite cool for this pack:
Using the Butchery Knife (which is a GT meta-tool) could lower the explosion chance to 0%.
That way the mechanic can be kept and we could have a quest for the Butchery Knife (right before the animal farms one I guess) that explains how this tool negates the explosion chance.

I don't know if it will be easy to code but I think the change sounds really good on paper and it encourages you to use another GT tool that previously had even more of a niche spot in this pack.

**Comment by KaneHart** [comment]
You know what is funny... People are now using this stupid mechanic to auto farm cows meats/leather. Like they allow their cows to die from overcrowding and then use stuff to collect it. They do lose babies but they don't care... So now they just have massive farms with over feeding via wheat lol..

So woot thanks for whoever made this dumb mechanic to give a new method of farming.

**Comment by WarlordWossman** [comment]
I know that you can use that but I think my suggestion still makes sense esp. since you have no easy access to vacuum hoppers early game.

**Comment by Dream-Master** [comment]
Sure if anyone have free time to code that why not.

**Comment by Namikon** [comment]
Angermod already has the ability to define Butcher-Items that will set the explosion probability to 0%. See angermod.cfg > Blacklist > KamikazeItemBlacklist

**Comment by WarlordWossman** [comment]
Alright think this would be a good way to make this rarely used meta tool shine!

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GTNewHorizons/angermod.cfg#L9

**Comment by richardhendricks** [comment]
Okay I have a working configuration for this.  I am going to set it up so GT knives and butchery knives work.  The DPS for knives will be reduced and butchery knives increased.  The mob immunity to damage time will also be increased for normal knife.  This way you can start with a low tier knife that takes multiple hits to kill an animal with a little bit of chasing but is really cheap and can be used for crafting, make a dedicated butchery knife that is much faster, and then upgrade to a single hit kill to prevent explosions.  Right now because the damage is based off of mining level, it takes a Stainless butchery knife to get one hit kills on cows.

I am also going to increase the % of explosion chance from 5 to 10% since there is now a way to get around it.

**Comment by richardhendricks** [comment]
Tier 0 quest, opens after Rest in Pieces:
Cows are supposed to Moo!
What the?  You noticed sometimes when you kill something, even a cow or chicken, that it explodes! What madness! To stop it, use a proper GregTech Knife or Butchery Knife. Craft a flint GregTec knife and I will give you an old iron one to use once it wears out.

Tier 0.5 quest, opens after Sheep Hairdresser
All the finest cuts of meat
This knife is not going to work for slaughtering the hundreds of animals you will need for food and materials. Make yourself a GregTech Butchery Knife. It stops the explosions, and kills the cows much faster. Later when you get stainless, you can make a new one that will kill cows in one hit.

Note: GT Tool damage is based on mining level.

**Comment by richardhendricks** [comment]
Should we add one of the powered tools to the blacklist for explosions as well? Buzzsaw/Chainsaw?
