### ISSUE TITLE
Better Questing reward claiming issue

### ISSUE THREAD

**Issue by GizliKodcu** [GTNewHorizons/NewHorizons#2204]
#### Which modpack version are you using?
2.0.1.3(with Technic Launcher)
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I've completed quest and claimed the reward.
#
#### What happend instead? (Attach screenshots if needed)
I've completed #2 quest and wasn't able to claim the reward and that happened for the rest of the Tier 0(so far) quests.
#

**Comment by Dream-Master** [comment]
Try with English localizer on ( English language ingame)

**Comment by Dream-Master** [comment]
Quest 2 : You need to submit 2 logs to get the Quest completed.

**Comment by Dream-Master** [comment]
@GizliKodcu
