### ISSUE TITLE
Quest bug teir 4 blood alter has wrong block

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2205]
#### Which modpack version are you using?
1.0.1.3
#
#### If in multiplayer; On which server does this happen? 
single player

This one is simple On the blood magic questline there is a quest for a tier 4 alter that tells you to make Blood stone bricks to cap the top of your pillars for this level. This will not make a tier 4 altar. Instead you need to use the large blood stone bricks as is tradtionally used in order to make it a tier 4. This means the issue is either a mistake in the quest or you intended to change the block but somewhere in the code there is a error.

**Comment by Dream-Master** [comment]
Make a pic for me .

**Comment by Pockyninja** [comment]
I am not entirely sure what  you need a picture of the block that goes on top is a large bloodstone brick as in my alter (this is just the top of my pillar)
![2017-11-21_21 53 24](https://user-images.githubusercontent.com/24741793/33107722-894d7766-cf06-11e7-861d-5144eb10375a.png)

what your quest says is 

![2017-11-21_21 54 51](https://user-images.githubusercontent.com/24741793/33107744-9dc47b68-cf06-11e7-8d0d-e41ff309031e.png)

**Comment by Dream-Master** [comment]
Ok will change it in the questbook
