### ISSUE TITLE
[2.0.1.3] Core animation use could not be crafted for Golem (ID 4452:8)

### ISSUE THREAD

**Issue by Derweis** [GTNewHorizons/NewHorizons#2207]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
On the server, freeminer
#
#### What did you try to do, and what did you expect to happen?
Core animation could not be crafted for Golem (ID 4452:8), tried comporator of the minecraft and of mod projectred. All attempts have not yielded results. Shears and FLINTANDSTELL was used intact, without damage, checked the craft in NEI.

#
#### What happend instead? (Attach screenshots if needed)

![image](https://user-images.githubusercontent.com/15996927/33133931-67cd3046-cfaf-11e7-898d-1855090ccdb6.png)

#

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33427111-71ef02e6-d5c4-11e7-9913-89f568aeab9b.png)
![image](https://user-images.githubusercontent.com/2970688/33427127-8133b9f4-d5c4-11e7-9fff-8aca4e35b386.png)
![image](https://user-images.githubusercontent.com/2970688/33427131-86e1e4f2-d5c4-11e7-8bd4-da2b8a04311b.png)
![image](https://user-images.githubusercontent.com/2970688/33427147-97bfcf50-d5c4-11e7-97a3-4f4f8a0c37fd.png)

**Comment by Dream-Master** [comment]
works for me

**Comment by Derweis** [comment]
rebooted the scripts works!)
