### ISSUE TITLE
Dirthuts - Server Address Change

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2208]
#### Which modpack version are you using?
latest

The current dirthuts.com New Horizon pack has moved from 138.201.134.44 to s1.digtobuild.com:25560

This is due to ownership changes at DirtHuts (Lame retired).  I am in the GTNH discord if you need to confirm.  

Please update the address in the pre-installed server list to reflect the new address **s1.digtobuild.com:25560**  thank you

**Comment by Dream-Master** [comment]
Ok will change with the next update

**Comment by devanchya** [comment]
appreciated

**Comment by Dream-Master** [comment]
Ok i update the webpages too.
