### ISSUE TITLE
Quest "Adept Thaumaturgy/Secrets" is not MP friendly

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2209]
#### Which modpack version are you using?
2.0.1.3
#
The quest "Secrets" in "Adept Thaumaturgy" tab requires to kill 2 Crimson Clerics and 2 Crimson Knights
The problem is that the Clerics do not respawn, and on multiplayers server it will be next to impossible to find an alive Cleric, after some players will fulfill this quest. The knights on the other hand are renewable, and with care, one obelisk may provide an indefinite amount of knights.

#### What do you suggest instead/what changes do you propose?
I suggest removing the cleric requirement, and increasing the knights amount requirement.

**Comment by Dream-Master** [comment]
Ok can change this. A Coin Quest where you can buy some Cleric Spawn Eggs are possible too.

**Comment by Dream-Master** [comment]
I change it to 0/4
I add Spawner Eggs one Quest before

**Comment by repo-alt** [comment]
Thank you!
