### ISSUE TITLE
Waiting game: iTNT

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#221]
Ok, so you need flint dust to craft industrial TNT, which is made by macerating flint. I didn't want to wait to I mortar'd the gravel to get flint, but then I *had* to wait like.. 45 minutes until all the flint was macerated and I could continue my iTNT.
It's ok if we'd need only a small amount of this, like for some industrial diamonds maybe. But with all the rocket-tiers where you need *stacks* of iTNT, this is going to be an annoying waiting game and should be changed. You get the pulverizer in 2048 EU age later, which is pretty fast for that, but for your beginning and probably the first rocket, this is just a big pain to do

**Comment by Dream-Master** [comment]
Diatomite have Flint dust (Centrifuge) I will add a Vein that adds Salpeter,  Diatomeen....

**Comment by Dream-Master** [comment]
Ore Mix 14/Salpeter/Diatomite/Nikolite/Alunite in the Nether  5-45

**Comment by Drobac** [comment]
Give me a warning if the nether will get a reset

**Comment by Dream-Master** [comment]
yes not before the next update

**Comment by Dream-Master** [comment]
I think tommorrow (22.6.2015 in the evening) but i have to change the ore mixes first.

**Comment by Dream-Master** [comment]
Any news here?

**Comment by Namikon** [comment]
Haven't looked at Gunpowder yet, but I will need it soon. I bookmarked one Saltpeter vein already.
Bee's are even more difficult now by the way. Forestry/RWG changed something with biome configs, and "Desert_Hot" seems to be not "Hot" anymore, which means austere bees don't make gunpowder.
A Creeper-Farm would be a nice idea, but as we had several problems tps-wise, this might become tricky. 

What about your custom recipe for gunpowder you and UltraPeeks where working on?

**Comment by Dream-Master** [comment]
Forestry/RWG changed something with biome configs

You mean on the Test Server?

We make a recipes for saltpeter.

**Comment by Namikon** [comment]
No, on the real server. We didn't notice it, because we all where fighting lag and instability back then.

**Comment by Dream-Master** [comment]
than it is forestry not rwg becuase not updated.

BTW i want to update the live server now.

**Comment by Namikon** [comment]
Anyways, biome values for humidity and temperature are weird now. I will be back this evening at probably 7pm

**Comment by Dream-Master** [comment]
ok

**Comment by Teteros** [comment]
[Creeperweed](http://ftb.gamepedia.com/Crops_(GregTech)) is a tier 7 crop. You might not want to go in to them, so I may trade you some for bees/drones once I reach tier 7.

Oh, and I can confirm the creeper farm/cursed earth farm works great for **all** the things!

**Comment by Drobac** [comment]
Doing the Gravel into flint dust directly recipe in a centrifuge will help a lot, so put that in when you can

**Comment by Dream-Master** [comment]
Recipe done i upload it when i be back home

**Comment by Drobac** [comment]
Many thumbs up for the recipe, working nicely

**Comment by Dream-Master** [comment]
So we can close this issue?
