### ISSUE TITLE
Glass tube recipe in solidifier is strange

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2211]
#### Which modpack version are you using?
2.0.1.3
#
Glass tube recipe in the fluid solidifier takes 500ml of glass,
Glass block produces 144 ml
Alloy smelter glass tube recipe takes 1 glass dust
So, for consistency, fluid solidifier recipe should take either 72 or 144 ml of molten glass.
(as most molten glass recipes do)

**Comment by AlphaApotheosis** [comment]
Just to clarify, there are two glass tube solidifier recipes. One is for 1000mb tinker's molten glass and should be fine, because 1000mb tinker's glass is one glass block. But you are correct, the 500mb GT molten glass should be 144 to match the glass dust in the alloy smelter.

**Comment by Dream-Master** [comment]
1000L is tinkers and 144L is vanilla. I fixed that now.
