### ISSUE TITLE
Fence (Tier 1) Recipe Unbalanced

### ISSUE THREAD

**Issue by eloquentJane** [GTNewHorizons/NewHorizons#2213]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Checked recipes for the Fence (Tier 1) from Open Modular Turrets. Expected it to be either the same cost or cheaper in the assembler.
#
#### What happend instead?
It costs less steel per fence to craft them manually than in the assembler.
#
#### What do you suggest instead/what changes do you propose?
Since every other tier of Open Modular Turrets fence produces two fence items in the assembler, while the Tier 1 fence only produces a single item in the assembler with a comparable recipe (i.e. the items remain the same but the material changes for tiering) I suggest changing the assembler recipe for the Fence (Tier 1) to output two items as well.

**Comment by Dream-Master** [comment]
Ok will check

**Comment by Dream-Master** [comment]
I change it to 4
