### ISSUE TITLE
suggestion change growth medium recipe

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2214]
#### Which modpack version are you using?
2.0.1.3

#
#### If in multiplayer; On which server does this happen? 
single player

#
#### What do you suggest instead/what changes do you propose?
![2017-11-25_12 46 14](https://user-images.githubusercontent.com/24741793/33233086-c43a56c0-d1de-11e7-89f7-72a0acc1110a.png)

This is the current recipe for growth medium the 2nd recipe is the same but with distilled water giving the same amount. As you can notice the suger, bone meal, and mulch are all forced to be small pile despite asking for 4 of them which enough for a regular pile. This just makes the items take up more room for no real reason. I think there should be at least a option to put in a full pile.

**Comment by Dream-Master** [comment]
I guess I add small piles because the full dust allready used in other recipes.
