### ISSUE TITLE
[Suggestion] Change Blood Magic Life Essence Cell recipe to use Regular cell rather than Universal Cell.

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2215]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
Transfer Blood Magic Life Essence fluid into Empty cell. I expected to get the cell full of the life essence.
#
#### What happend instead? (Attach screenshots if needed)
The Cells we get from the quest book don't work, However, the IC2 Universal Cells do work, but that wasn't clear and took some time to figure out.
#
#### What do you suggest instead/what changes do you propose?
Replace recipes that require Universal Cells filled with Life Essence and replace with normal cells filled with life essence. Or add a tool tip to Universal Cell items that says "This is a different type of IC2 Cell." to make it more apparent that there is a difference.

**Comment by Dream-Master** [comment]
I guess if blood is not registered to gt I can't add it.

**Comment by Dream-Master** [comment]
Same problem as the Iron3Chloride. This material isnt registered as Material in GT.

**Comment by Dream-Master** [comment]
Will try to add it to GT code.
