### ISSUE TITLE
Charcoal Pile Ingiter doesn't work with Rainforest Oak Tree Log

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2216]
Version 2.0.1.3 - Stonelegion

Charcoal Pile Ingiter doesn't work with Rainforest Oak Log.

Tested with a very XS size 3 x 3 x 1 height pile, with rainforest oak log, the igniter doesn't start.

Simply replace the logs with vanilla birch log. The igniter works.

**Comment by Dream-Master** [comment]
Maybe this log are not oredicted the right way. Which mod add It?

**Comment by ko5h** [comment]
rainforest oak log from gt++

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?

**Comment by Dream-Master** [comment]
Seems to work now

![image](https://user-images.githubusercontent.com/2970688/33424383-fd535f52-d5bb-11e7-85b4-97c09e64f992.png)

![image](https://user-images.githubusercontent.com/2970688/33424395-085a4334-d5bc-11e7-9e5a-3c0187c78117.png)

![image](https://user-images.githubusercontent.com/2970688/33424487-4da1b936-d5bc-11e7-8ff8-e68d9bdcbe93.png)
