### ISSUE TITLE
Borosilicate Glass Fibers

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2217]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?

This recipy(see below) needs wiremill brother.
![2017-11-26_18 27 40](https://user-images.githubusercontent.com/25028786/33241543-ef96faea-d2d7-11e7-861a-75301aaa2d12.png)

**Comment by Dream-Master** [comment]
I could add it to the wire mill at lower output. Not sure if tier is screwed up because extruder need 120eu/t? @Cinobi

**Comment by Cinobi** [comment]
Well, this recipy just don't needed until EV, so i don't think there is some problems with tiering. Or i understand u wrong?

**Comment by Dream-Master** [comment]
Ok will add a recipe using 480 eu/t .
