### ISSUE TITLE
[2.0.1.3] AdvLappack no craft

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#2218]
#### What happend instead? (Attach screenshots if needed)
not crafting for a Advanced Lappack

**Comment by Bryfer** [comment]
A bit more information could be useful to properly help you with your issue.

**Comment by ko5h** [comment]
@Bryfer https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_CraftingRecipeLoader.java#L817
incorrect 'advJetpack'...this is not ic2item
adv lappack need to ultimate lappack...ult lappack need to gravichestplate

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Adv Jetpack need to be tested too.
