### ISSUE TITLE
Dark Steel Tools and Weapons quest is bugged

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2219]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I crafted a fresh set of dark steel tools for the quest, and 4 vibrant crystals
The first 2 quest stages completed successfully.
Then I empowered the tools and charged them, but the quest does not accept them for the final stage.

**Comment by ko5h** [comment]
Duplicate of #2179

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33388610-b46c8f42-d530-11e7-9969-a8773ddb4311.png)
works for me

**Comment by Dream-Master** [comment]
@repo-alt 
please use on all tools andhit command /mt hand and post results here.

**Comment by Dream-Master** [comment]
My results: Sword, Pick, Axe, Shears

```
<EnderIO:item.darkSteel_sword>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_pickaxe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_axe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
<EnderIO:item.darkSteel_shears>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})
```

And second stage (quest)
```
<EnderIO:item.darkSteel_sword>.withTag({"enderio.darksteel.upgrade.travel": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 8 as short}, level_cost: 30, unlocalized_name: "enderio.darksteel.upgrade.travel"}, "enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
<EnderIO:item.darkSteel_pickaxe>.withTag({"enderio.darksteel.upgrade.travel": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 8 as short}, level_cost: 30, unlocalized_name: "enderio.darksteel.upgrade.travel"}, "enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}, "enderio.darksteel.upgrade.spoon": {upgradeItem: {id: 277 as short, Count: 1 as byte, Damage: 0 as short}, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.spoon"}})
<EnderIO:item.darkSteel_axe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
<EnderIO:item.darkSteel_shears>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5635 as short, Count: 1 as byte, Damage: 2 as short}, maxOuput: 10000, level_cost: 20, unlocalized_name: "enderio.darksteel.upgrade.empowered_four", maxInput: 10000, capacity: 1000000, energy: 1000000}})
```

**Comment by repo-alt** [comment]
Unfortunately that I have no permissions for that command.
I may try in SSP but the result will not be conclusive.

**Comment by repo-alt** [comment]
Also, in SSP I'll have to somehow open the prerequisite quests

**Comment by Dream-Master** [comment]
do /bq_admin edit and edit the quest you like. Try in ssp. I could op you tomorrow on the server that you can write the mt hand stuff to me. @repo-alt

**Comment by repo-alt** [comment]
In SSP quest is passing.
I'll paste /mt hand dump just in case, but obviously this problem is server specific.
`<EnderIO:item.darkSteel_sword>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})`
`<EnderIO:item.darkSteel_pickaxe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})`
`<EnderIO:item.darkSteel_axe>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})`
`<EnderIO:item.darkSteel_shears>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {upgradeItem: {id: 5637 as short, Count: 1 as byte, Damage: 6 as short}, maxOuput: 1000, level_cost: 10, unlocalized_name: "enderio.darksteel.upgrade.empowered_one", maxInput: 1000, capacity: 100000, energy: 100000}})`

**Comment by repo-alt** [comment]
Wow, today the quest is completed on the server too!
No idea what it was, but obviously the bug may be closed.

**Comment by repo-alt** [comment]
`
`
![image](https://user-images.githubusercontent.com/23512002/33450921-631a0086-d61e-11e7-8f2e-6ebeced021f7.png)

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/33450966-7d6f8dac-d61e-11e7-82cf-d5e7cb73e851.png)
(sword did not fit)

**Comment by Dream-Master** [comment]
not sure when i remove id it will work

**Comment by repo-alt** [comment]
In SSP it works.

**Comment by Dream-Master** [comment]
Very cool hope it work on servers too
