### ISSUE TITLE
Enable the Auto WorkBench

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#222]
ProjectRed crafting pipes/chips with the Buildcraft Auto Workbench would make a nice early to mid game alternative for AE autocrafting.

The Auto Workbench is quite slow and limited, it takes about 10 seconds for one crafting operation and does not work with GT tools. (Would be nice if it did support tools/damage values though)

To use it with ProjectRed, hook it up to a routed crafting pipe, then set the crafting template in the Auto Workbench the same way as the configured crafting chip. The crafting pipe will discover the materials through broadcast chips in other pipes and pull them on demand.

**Comment by Dream-Master** [comment]
I working on solder afet this i will finish project red and than i go to Buildcraft

**Comment by Dream-Master** [comment]
Added a Recipes in the next update.
