### ISSUE TITLE
Mars, "Space" and Astroid Dim are bugged on delta.

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2220]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### Bugs i found so far:
1. You cant go to Mars by rocket. The launch field is always Red see #2158
2. _Phobos isnt reachable with stargate anymore (27.11.17 ~02:00am). "No Permission to enter this Area."_ seems to be fixed after readding myself to the whitelist.
3. Go to Astroids by rocket will place you anywhere near ~100k ~100k, youre completly unable to go to the stargate, when you launch your rocket back to eath, the parachest will fall outside of the world border and the rocket will be lost. see #2194
4. _Void Portal will redirect into a Space Station._ fixed inDev

#
#### What do you suggest instead/what changes do you propose?
I think deleting/re-generting the problematic dims may fix these problems.

**Comment by Dream-Master** [comment]
After the ore generation is fixed I can regen the dims. Are there any buildings on this dims like spaces base etc? @LOKKO12

**Comment by Dream-Master** [comment]
Dim wipe today.
