### ISSUE TITLE
[2.0.1.3] No spawn Twilight forest mobs

### ISSUE THREAD

**Issue by Derweis** [GTNewHorizons/NewHorizons#2221]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Freeminer
#
#### 
What did you try to do, and what did you expect to happen?
will not spawn the mobs in the twilight forest, in particular the mobs. What makes a resource inaccessible. (the charm of saving inventory and the charm of life)
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Fix it))))

**Comment by Bryfer** [comment]
I'm not sure I understand exactly what you mean could you add some more information?
What mobs are you talking about? 
What about the amulet?

**Comment by Derweis** [comment]
this mobs and outher. Charm of inventory I'm talking about this subject. I wrote their admin and he sort of recovered, we have a special system spawn mobs.
![image](https://user-images.githubusercontent.com/15996927/33272677-eaef4776-d39b-11e7-986f-eb04d547b4ac.png)
![image](https://user-images.githubusercontent.com/15996927/33272703-00cb41e4-d39c-11e7-9d54-cc8508ffbc2c.png)

**Comment by Namikon** [comment]
> we have a special system spawn mobs.
Well then you should contact the Admin(s) of this Server. This is nothing we can fix on our side

**Comment by Derweis** [comment]
решено)
