### ISSUE TITLE
[2.0.1.3]deprecated Yttrium BaCu mixer recipe

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#2222]
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/27635022/33279806-faa966d2-d3b0-11e7-9cba-83320e9569c6.png) 
use circuit conf==1
_________________________________________________
![image](https://i.imgur.com/jga7RCw.png)
use circuit conf==2

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
Will check. Maybe a core mod recipe and a gt mod recipe.
