### ISSUE TITLE
[Suggestion] Allow Iron III Chloride to be added to Cells.

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2224]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
I tried to store Iron III Chloride into an Empty cell. I expect the cell to fill with 1000mb of Iron III Chloride.
#
#### What happend instead? (Attach screenshots if needed)
It did not work.
#
#### What do you suggest instead/what changes do you propose?
Make it so Iron III Chloride can be added to Empty Cells.

**Comment by Dream-Master** [comment]
I guess it not work properly because the fluid is not registered as a new material.

**Comment by Dream-Master** [comment]
`ItemList.sIron3Chloride = GT_Mod.gregtechproxy.addFluid("iron3chloride", "Iron III Chloride", null, 1, 295);`
Material is null.

I dont know of any fix so I need help.

**Comment by tranceplanet** [comment]
Can you use universal fluid cell instead?  There’s a few liquids like cracked fuels and steam that can only be shifted with universal fluid cells (and using the GT interfaces)

**Comment by Dream-Master** [comment]
As i said earlier this fluids you mentioned are all rigistered in the GT Material List. Iron3Chloride is only registered in this single line. @tranceplanet

**Comment by Dream-Master** [comment]
done
