### ISSUE TITLE
DetravScanner circuit tier mix-up

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#2227]
#### Which modpack version are you using?
2.0.1.3
All DetravScannerMod's prospecting scanners use wrong tier circuits in their crafting:
LuV scanner recipe uses ZPM circuit (Ultimate) instead of LuV circuit (Master) while it uses LuV battery.
ZPM scanner recipe uses UV circuit (Super) instead of ZPM circuit (Ultimate) while it uses ZPM battery.
UV scanner recipe uses LuV circuit (Master) instead of UV circuit (Super) while it uses UV battery.
This makes no sense ad gates the LuV scanner behind ZPM tier.
My suggestion is : require a circuit of the same tier the resulting scanner itself uses (LuV scanner is crafted from LuV circuit).
This can be achieved by changing around the circuit materials in https://github.com/GTNewHorizons/DetravScannerMod/blob/master/src/main/java/com/detrav/items/processing/ProcessingDetravToolProPick.java#L23 (lines 23,24,25).
Character.valueOf('C'), OrePrefixes.circuit.get(Materials.**materialname**)
LuV - should be Master.
ZPM - should be Ultimate.
UV - should be Super.

**Comment by Dream-Master** [comment]
2.0.2.0 is not released yet.
@RaggedCaster
