### ISSUE TITLE
Various dust mix issues

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2229]
#### Which modpack version are you using?
2.0.1.3
#### What did you try to do, and what did you expect to happen?
1. There is a missing Mixer recipe for rose gold, mixing 4 gold dust + 1 copper dust = 5 rose gold dust.
There are only recipes using tiny pile and small pile.
![image](https://user-images.githubusercontent.com/30087707/33341905-9924fc5c-d480-11e7-97bb-cf470f2e4c2f.png)

2. However the Mixer recipe for rose gold will then collide with recipe for tumbaga dust (3 gold dust + 4 gold dust + 3 copper) 

3. Some dust recipes use circuit =1 and some =2, even though I cannot find an overlap between recipes.

4. Some dust mixes are not nerfed when mixing in the crafting table. 
E.g. rose gold gives 5 for 5, blue steel 8 for 8, black steel 8 for 8, and so on. 

#### What do you suggest instead/what changes do you propose?
1. Add recipe for Rose gold dust in Mixer using dusts. 

2. All special dust mixes (ones that are made in the Combiner, 22 different mixes) should use e.g circuit = 3 when mixed in the Mixer.

3. N/A (?)

4. Nerf crafting table recipes to be dust in minus one = dust out. 
I think I got all un-nerfed dusts listed below.
Kanthal dust -> change to 2 out
Black steel dust -> 5 out
Blue steel dust -> 7 out
Red steel dust -> 7 out
Ultimet dust -> 8 out
Cobalt brass dust -> 8 out
Sterling Silver dust -> 4 out
Rose gold dust -> 4 out
Black bronze dust -> 4 out
Bismuth bronze dust -> 4 out
Vanadium steel dust -> 8 out
Angmallen dust -> 1 out
Indium gallium phosphite dust -> 2 out

**Comment by Dream-Master** [comment]
The combiner is a gt++ device so far i know

**Comment by Dream-Master** [comment]
Better to report it to GT++ so it can changed there.
@DualBallers

**Comment by Dream-Master** [comment]
`GT_Values.RA.addMixerRecipe(GT_OreDictUnificator.get(tPrefix, Materials.Copper, 1L), GT_OreDictUnificator.get(tPrefix, Materials.Gold, 4L), GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Utility.getIntegratedCircuit(1), GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.getDust(Materials.RoseGold, 5L * tPrefix.mMaterialAmount), (int) (500L * tPrefix.mMaterialAmount / 3628800L), 120);`

Code is there and i not understand why it not worked

**Comment by DualBallers** [comment]
The issue is not with the combiner or GT++.

It's just specifically that there is no recipe for rose gold dust in the mixer. 
But, by adding this, tumbaga and rose gold dust will have the same dust in the mixer. Therefore tumbaga should have circuit in the mixer recipe.
I see that most of the other dust GT++ recipes in the Mixer (not GT++ machine) does not use a circuit, so maybe add that for those recipes. 

Furthermore, I just found that a lot of crafting table recipes for dust are not nerfed, giving a 1-to-1 dust ratio. Maybe nerf those a bit :-)

Weird if the code is already there for the recipe...

**Comment by draknyte1** [comment]
I think I fixed this one too~
