### ISSUE TITLE
Circuit system is broken

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2230]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I thing Circuit system is broken right now.
Basic cirtuit for LV machines
Good circuit for MV machines
Advanced circuit for HV machines
Extrime circut for EV machines
Elite circuit for IV machines
Master circut - good for nothing(exept 5 IV machines and 4 IV components)
Ultimate circuit - LuV machines
Super circuit - ZPM machines
Infinite circuit - Uv machines

As u can see, leveling of circuits is broken, and we have one useless(almost) tier of circuit.

Suggsetion:
1. Force all LuV recipes use "Master circuit"
2. Force all ZPM recipes use "Ultimate circuit"
3. Force all  UV recipes use "Super circuit"
4. Remove "Infinite circuit" completly
5. If u love recipes of "infini circuit" use them for super circut instead
6. Rename Zpm circuit into "Super circuit"
7. Rename UV circuit into "Ultimate" or "infiny" circuit

**Comment by LOKKO12** [comment]
I dont see a problem here, since Master circuit is used in a wide range of non-GT machines...

**Comment by Cinobi** [comment]
![2017-12-26_18 40 16](https://user-images.githubusercontent.com/25028786/34359842-7141bea8-ea6c-11e7-8b82-1933188cf3a7.png)
![2017-12-26_18 40 14](https://user-images.githubusercontent.com/25028786/34359843-716523fc-ea6c-11e7-86f5-b0ad1e3c5f7f.png)
Broken, as i sayed :P

**Comment by Bluebine** [comment]
Now that the circuits have their tiers listed, this is even more of a mess. My suggestion would be to make every machine, as well as the robot arms, emitters, etc. of the tier ALL use the circuit OF the tier (both EV machines AND EV robot arms, emitters, etc. take EV circuits, and so on), remove nano circuits completely, and make wetware mainframes "special" circuits like the Nano circuits are now, only used for crafting the few UHV machines like the teleporter as well as for the Avaritia recipes that use them.
Circuit system definitely does need to be looked at.
