### ISSUE TITLE
[suggestion] Receive twilight boses 

### ISSUE THREAD

**Issue by Derweis** [GTNewHorizons/NewHorizons#2232]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Freeminer
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
I propose to make the possibility of the revival twilight bosses after the completion of the quest, they are not enough)

**Comment by Dream-Master** [comment]
I suggest to regen the Twilight Forest on your Server.

**Comment by Bryfer** [comment]
On the official server you can request spawn of Twilight bosses from staff 
If you know a way to make this process more automated, let us know

**Comment by Dream-Master** [comment]
It is possible to add after you kill a boss some spawn eggs for coins.

**Comment by Derweis** [comment]
уes, spawn eggs for coins)

**Comment by Dream-Master** [comment]
ok

**Comment by Bryfer** [comment]
Which part will only let the eggs be spawned in the proper locations?
And I believe these eggs will break alot since iirc Naga for example didn't care if the area is under protection or not

**Comment by Dream-Master** [comment]
I could forbide use the eggs in the overworld or other dims only TF ?

**Comment by LOKKO12** [comment]
@Dream-Master Can you allow use in TF and VoidDims?

**Comment by Dream-Master** [comment]
Need to add the config to the spawn eggs.

**Comment by Bryfer** [comment]
How are you planning on making the eggs usable only in the correct places of Twilight, or will exploring Twilight no longer be needed..?

**Comment by Namikon** [comment]
Our mod blocklimiter has the ability to prevent the usage of items, as long as they utilize "vanilla" behavior, that could be used to prevent it in any Dimension other than Twilight

**Comment by richardhendricks** [comment]
Don't forget, there are also bees available to generate naga scales and lich bones etc without killing the bosses first.  And if you already killed the bosses, you can duplicate scales/bones in the assembler with the reward trophy.

If you want to kill the bosses for fun, then a spawn egg is required. :D
