### ISSUE TITLE
[DELTA] Ceres Spawn destroyed

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2236]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Went to Ceres on delta, Stargate Room is destroyed, seems like someone with Decay Warp effect idled there.

![2017-12-03_01 47 49](https://user-images.githubusercontent.com/33183715/33528992-0fb54b96-d86a-11e7-81b2-cf9a277069c0.png)
![2017-12-03_01 45 33](https://user-images.githubusercontent.com/33183715/33528993-0fd570a6-d86a-11e7-8e60-a10826f8b20f.png)

**Comment by Drobac** [comment]
Fixed
