### ISSUE TITLE
[Suggestion] Change orevein heights for Y180-250 oreveins to Y80-180

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2237]
#### Which modpack version are you using?
2.0.1.3
#
#### What do you suggest instead/what changes do you propose?
Suggest changing heights for custom vein #4 Copper/Tin and #10 Dolomite to Y=80-180.  These oreveins are pretty much unable to spawn in overworld since their requirements are so high. Unless it is intentional to disable them?

Also, if we are going to use the orevein finder mod proposed in #2226 , suggest increasing #4 copper/tin weight to higher values. 160 seems reasonable, on my searches around 4-5 mountains the Lignite Y80-210 vein showed up a couple times visible from the side and it has weight 160.

**Comment by Dream-Master** [comment]
But we have Mountains that high more then 180 so i want there ores too. So far i rember i desinged the mixes for this extreme high.

**Comment by Dream-Master** [comment]
I can increase the chance ores spawns there

**Comment by Dream-Master** [comment]
And small ores

**Comment by bartimaeusnek** [comment]
if this should be changed, change it here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/6596b1f310ea82c56c27b346bd98f5985927b6e0/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L168

the config entry for Dolomite needs to be deleted then aswell.

**Comment by richardhendricks** [comment]
OK, let's just close this for now.  This fall I will be reworking the high-altitude spawns to make them better and worth exploring.
