### ISSUE TITLE
[Suggestion] Berries++ a IC2-crops-crossover mod

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2238]
Hello everyone, i programmed a small, but use- and sensefull mod, that adds various berries to IC2 crops. Until now only Natura berries are supported but im working on it. OreDirectory compatibility / integration of Pam's Harvestcraft, Twilight Forrest, Biom O' Plenty, Tinker's Construct and Witchery are planned. The mod itself is just a small mod, that does not add the berries, but makes them useable for crops. The mod itself is OpenSource, licensed under [CC-SA-BY 4.0.](https://creativecommons.org/licenses/by-sa/4.0/)Some parts, written by [mushroomhostage](https://github.com/mushroomhostage) in 2012 are under "BSD 3-clause "New" or "Revised" License".

Here are the Natura berry crops:
https://cdn.discordapp.com/attachments/333378666329276427/387903864495538176/bpp1.jpg
https://cdn.discordapp.com/attachments/333378666329276427/387903868681322516/bpp2.jpg

Here is the sourcecode:
https://github.com/LOKKO12/berries-plus-plus

**Comment by Dream-Master** [comment]
Yes looks cool

**Comment by WarlordWossman** [comment]
Really cool, I think adding more cross mod mechanics is always a good idea!

**Comment by LOKKO12** [comment]
Just a quick info that i released version 1.0:
https://github.com/LOKKO12/berries-plus-plus/releases/tag/1.0.0
![2017-12-23_03 41 09](https://user-images.githubusercontent.com/33183715/34316543-b01d2706-e798-11e7-9895-7ce955f3f335.png)

**Comment by Dream-Master** [comment]
cool.

**Comment by mitchej123** [comment]
It'd be great if you could add the cinderpearl (from thaumcraft) to the mod.  It's the one I miss the most from agricraft!

**Comment by Dream-Master** [comment]
and shimmerleaf (the plant make cinebar when extruded)too.

**Comment by LOKKO12** [comment]
Cinderpearl, MagicMetalBerry (Void and Thaumium Oreberry) and Shimmerleaf added in 1.0.2-pre. No ingame textures yet.
