### ISSUE TITLE
Creosite Wood Slabs arent craftable with Buzzsaw

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2239]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to make Creosite Wood Slabs while using a Buzzsaw.
#
#### What happend instead? (Attach screenshots if needed)
Was not craftable.
![2017-12-06_22 02 45](https://user-images.githubusercontent.com/33183715/33685403-c7b11cd4-dad1-11e7-9545-45fb08de7074.png)
![2017-12-06_22 07 25](https://user-images.githubusercontent.com/33183715/33685444-e7353766-dad1-11e7-82a8-b40a9edf6b63.png)
#
#### What do you suggest instead/what changes do you propose?
Make Creosite Wood Slabs craftable with all kinds of saws and add a Cutting Machine recipe.

**Comment by Dream-Master** [comment]
Guess this isnt oredicted or buzz saw use another one. Will fix.
