### ISSUE TITLE
Malis Doors crash

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#224]
Malis doors crashes when you try to place down the garage door.
This probably is fixed in the latest Version; http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-7-10-1-8-2-15-06-2015-see-p85-1717?comment=1717

**Comment by Dream-Master** [comment]
Yes fixed with the next update

**Comment by Teteros** [comment]
Fixed in today's hotfix.
