### ISSUE TITLE
Different Nuggets issue

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2240]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I try to process some different nuggets i get from bees - "Copper Nugget" from magic bees, more presisely, and get a problem - u can't autoinput this nuggets to gt machines in the most poplular ways(like AE or EnderIo methods). Only way u can do it is to use GT item pipe to pull off the nuggets from apiary - gt pipe convert nuggets to GT one automaticly. Some oredictionary problem i guess?

**Comment by Dream-Master** [comment]
If bees producing nuggets from other mods it can be a oredict thing. Post some pics here please.

**Comment by Cinobi** [comment]
![2017-12-08_12 03 20](https://user-images.githubusercontent.com/25028786/33758587-e35e70d2-dc0f-11e7-8366-ca2795f643c8.png)
here u go - copper nugget from mod "Magic bees".

**Comment by Dream-Master** [comment]
Did they not auto converted to gt nuggets? @Cinobi

**Comment by Cinobi** [comment]
It converts automaticly if:
a) picked in invenroty
b) place into GT machine by hands
c) take from apiary with GT pipe and cover

AE sucks them from apiary as nuggets from magic bees, and can't insert them to GT machines. Same with EIO conduits.

**Comment by Dream-Master** [comment]
I could add converter recipes for ae system if this helps

**Comment by Cinobi** [comment]
It will be better to add recipy to GT macerator, convert thousands of nuggets wia recrafting is madness :C

**Comment by Dream-Master** [comment]
This is impossible because gt nuggets are set in unification. I could change it magic bees nuggets are use but would this look better?

**Comment by Cinobi** [comment]
> I could change it magic bees nuggets are use 
Do not get the idea, can u explain it little more?

**Comment by Dream-Master** [comment]
I can unificate the nuggets to magic bees nuggets. So all nuggets let's say lead be only available as magic bees nuggets.  All gt recipes would use this type than.

**Comment by Cinobi** [comment]
Oh, i don't think this is good idea, may couse some problems with other mods(we have 5 different copper nuggets, if u interested :D)

**Comment by Dream-Master** [comment]
i dont like the idea much using a other mods nuggets. I guess if we change it we get new problems so another solution need to be found.

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/GTNewHorizons/NewHorizons/issues/1698
