### ISSUE TITLE
Oxygen mask only takes TiC glue

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2241]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I tried to craft an Oxygen Mask from Galacticraft. I expected to be able to use either the GT glue or the TiC glue.
#
#### What happend instead? (Attach screenshots if needed)
I can only use the TiC glue to make it.
#
#### What do you suggest instead/what changes do you propose?
Make the oxygen mask craftable with GT glue.

**Comment by Dream-Master** [comment]
Will add.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33798055-66e52402-dd12-11e7-93fc-29e76d953a39.png)
![image](https://user-images.githubusercontent.com/2970688/33798059-6a822dd0-dd12-11e7-9979-748ef897e49c.png)
