### ISSUE TITLE
Raw Meteoric Iron with DMG Valure unuseable

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2242]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Got 10pcs. of Raw Meteoric Iron with a DMG valure of 3, isnt useable in any machine. Name Remover did not fix this.
![2017-12-08_18 07 16](https://user-images.githubusercontent.com/33183715/33776785-c8879878-dc42-11e7-9e91-5af04163ce71.png)
#
#### What do you suggest instead/what changes do you propose?
OreDirect Raw Meteoric Iron with DMG of 3 to "dustMeteoricIron" or add a Shapeless Recipe that removes the DMG valure.

**Comment by Bryfer** [comment]
Where did you get these from?

**Comment by LOKKO12** [comment]
I dont know :/ but i know i mined them in a space dim, but dont know which one...

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33797960-13882f9e-dd11-11e7-8136-7fee8a7b6ee4.png)
![image](https://user-images.githubusercontent.com/2970688/33797962-16cdd438-dd11-11e7-84da-927ba20075d3.png)
