### ISSUE TITLE
Electronic tubes assembler recipy...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2243]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
... not working.
![2017-12-08_20 30 43](https://user-images.githubusercontent.com/25028786/33777678-da10b8b8-dc56-11e7-9c00-fe311b7c8b9c.png)
![2017-12-08_20 26 32](https://user-images.githubusercontent.com/25028786/33777679-da37028e-dc56-11e7-9514-7a74ddfafac6.png)
![2017-12-08_20 26 37](https://user-images.githubusercontent.com/25028786/33777681-da7ff9e4-dc56-11e7-8c0b-d32a32bb68eb.png)
![2017-12-08_20 28 19](https://user-images.githubusercontent.com/25028786/33777684-dabedac4-dc56-11e7-9672-a2b57f706b43.png)
![2017-12-08_20 30 27](https://user-images.githubusercontent.com/25028786/33777685-dae31768-dc56-11e7-995c-c4c58fb57fa2.png)

**Comment by Dream-Master** [comment]
A config issue. I change the recipes in gt code to be even with Forestry recipes.
