### ISSUE TITLE
Primordial pearl requirements

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2248]
#### Which modpack version are you using?
2.0.1.3
#
All, or at least most, of the avaritia infinity equipment needs an absurd amount of primordial pearls. The pickaxe/hammer alone needs 18, the leggings need 17, the sword needs 5, the shovel needs 18, and thats only a few. You need a ton of pearls to complete the set. The problem is that pearls can only be obtained in 2 ways. a .01% chance from rare lootbags, or from completing the end game dimensions. Doing either of these is a little too slow in my opinion for the amount you need. I suggest an end game duplication recipe for the pearls. Maybe 1 pearl, a dragon egg, an avaritia neutronium ingot, 4 eldritch eyes, and 128 of each primal aspect, will make 2 pearls, or something like that.

**Comment by LOKKO12** [comment]
You can open Dungeons yourself with the Node Manipulator from Gadomancy for a few Vis and 4 eldritch eyes. A Dungeon can be cleared in 5min WITHOUT Bedrock destroying gear, with it even faster. So 18*5 = 90min time in the dungeons. Do not see a problem here.

**Comment by Dream-Master** [comment]
Thanks for the Tip. Yes this seems not to hard if you are in this Tier.

**Comment by benstuwie** [comment]
@LOKKO12 how do I open them? if so, then you're right, there's no issue

**Comment by Cinobi** [comment]
@LOKKO12 this is not worhing some time. Currently at delta, for example =) When u try to open new rift it send u to same rift(cleared already), so no pearl.

**Comment by LOKKO12** [comment]
@benstuwie https://ftbwiki.org/Gate_of_the_Voidwalkers
@Cinobi thats m.b. a problem with the DIM/Cauldron i would suggest @Dream-Master to regenerate the Eldrich DIM, since there are no Buildings AFAIK.

**Comment by Dream-Master** [comment]
sure i can remove this dim

**Comment by benstuwie** [comment]
won't he need to regenerate the dimension every time a person uses the portal thing? that's like, 50 times per person

**Comment by Dream-Master** [comment]
No but I can wipe the dim now. This dim is old too.

**Comment by benstuwie** [comment]
but, if the portal you make always brings you to the same spot, won't you need to wipe it every time someone uses it?

**Comment by Dream-Master** [comment]
are they only one spot or they multiple in the same dim ?

**Comment by benstuwie** [comment]
it loos like they just keep spawning you in the same spot

**Comment by Dream-Master** [comment]
So if you open different portals you get always the same spot? Why no one complained before ?
Did Gadomancy Portal let you spawn at the same spot too?

**Comment by benstuwie** [comment]
not a different spot with different naturally generating portals, but those are limited, and really not an option on servers because of how many each person needs. The gadomancy one is the one that brings you to the same spot each time

**Comment by Dream-Master** [comment]
But Thaumcraft default portals not?

**Comment by benstuwie** [comment]
no, they work. there just aren't enough of them, and its stupidly tedious to find 50 of them

**Comment by repo-alt** [comment]
I seriously doubt that there are 50 obelisks at Epsilon for example.
I play there (with large pauses, but anyway) about half a year, almost from a start, and I have seen 5 obelisks. 2 with alive clerics. One was looted. One I looted myself. I'm pretty sure that I explored more than 10% of a land area.

**Comment by benstuwie** [comment]
exactly, there really arent enough

**Comment by Ethryan** [comment]
How about configing the server to reset the dimension once a week, that should allow for an easier time with the pearls.

**Comment by benstuwie** [comment]
really...
That's still something close to 24h of flying around to find them, and each person will probably need a reset before they finish getting all the pearls they need

**Comment by benstuwie** [comment]
I used the gadomancy dimension a little. It's buggy to say the least. For one, every new dungeon spawns inside the last one, causing there to be parts of old dungeons still there, and a generally weird layout. They dimension also breaks on server restart, and the file needs to be deleted. The dimension also breaks if you teleport out of it in any way except for using the portal, and needs the file deleted.

**Comment by Dream-Master** [comment]
Can you post some pics?

**Comment by benstuwie** [comment]
[img]https://i.imgur.com/V65xxWa.png[/img]
that's what the merged dungeons look like

**Comment by Dream-Master** [comment]
Is the Boss room only added or whole dungeon?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33984240-34728ce6-e0b7-11e7-8590-79fcf76e2454.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/33984259-423c641e-e0b7-11e7-8196-618b4845eaf0.png)
