### ISSUE TITLE
SpecialAI has enabled Thief-Mode

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#225]
SpecialAI has a submodule for stealing items from players, which just happend. This should be disabled, as it is disabled in InfernalMobs aswell

**Comment by Dream-Master** [comment]
Is is disabled.  Maybe the config change by it self.

**Comment by Namikon** [comment]
It's not:
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/SpecialAI.cfg#L147

**Comment by Dream-Master** [comment]
Set to 0 fixed in the next update
