### ISSUE TITLE
[2.0.2.0] missing recipes

### ISSUE THREAD

**Issue by donoya** [GTNewHorizons/NewHorizons#2262]
Hi, I'm using the 2.0.2.0 version of the modpack and noticed a few recipe problems.
1. Vanilla Ender Chest Uncraftable
2. Thorium Tetrafluoride Uncraftable
Both of these things are used as ingredients in other recipes, so I'm guessing they're supposed to be craftable somehow. If I find any more, I'll let you know. And in case it helps, I'm playing singleplayer.

**Comment by Dream-Master** [comment]
Vanilla Enderchest: I don't know they where craftable. Can you show me the recipe?
Thorium Teyrafluride is from gt++ so far I know. Please make a isdue on gt++ side.
Thanks

**Comment by Dream-Master** [comment]
Enderchets can be found in the End
About Tetrafluride i as gt++ de allready and he will investigate what happend @donoya
