### ISSUE TITLE
[SUGGESTION] Decocraft

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#2263]
Any chance that decocraft can be added to the pack? I actively play on the ProsperCraft server and a lot of people would LOVE to see this mod added.

**Comment by Proha5** [comment]
This modpack very fat. Adding tonn of  useless things is bad idea.

**Comment by AlexBucket** [comment]
'Useless' is in the eye of the beholder. Making a room or area look alive has value to some players.

**Comment by mtesseracttech** [comment]
I'd honestly advise against this if it's still not decided on. The mod is known to be pretty unperformant and making all the recipes for the decorations would suck majorly for @Dream-Master . I think there is a better use for his time than decoration stuff.

**Comment by WarlordWossman** [comment]
Yeah, people have been asking multiple times for this mod and the majority of players were against it (for multiple reasons that were already named). I think this could be closed.

**Comment by bartimaeusnek** [comment]
License:
All Rights Reserved

thats a nope from me.
