### ISSUE TITLE
Antimony Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2264]
Check if this quest unlocked before LV is unlocked.

**Comment by WarlordWossman** [comment]
https://youtu.be/qidtRQ5SrD8?t=3m36s

It does, in this video he doesn't have the antimony quest unlocked until he finished the Tetrahedrite quest. So yeah you unlock LV through that and only see the antimony quest if you finish the Tetrahedrite quest before you do the quests that actually unlock LV.

Maybe set it that you need all the quests intended to see LV + the Tetrahedrite quest to unlock the Antimony quest!

**Comment by Toperoco** [comment]
Same is happening in MV, it unlocks and only shows quest number 846 (O like Oxygen) without quest 89 (Tier 3) being available.

**Comment by Dream-Master** [comment]
yea have to check
