### ISSUE TITLE
 [Question] Maybe my error?

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#2265]
#### Which modpack version are you using?
2.0.2.0
#
#### If in multiplayer; On which server does this happen? 
non dont play mp
#
#### What did you try to do, and what did you expect to happen?
Re install the pack as suggest in the discord announcements chanel
#
#### What happend instead? (Attach screenshots if needed)
https://pastebin.com/aA3UmhYu
#
#### What do you suggest instead/what changes do you propose?
idk

**Comment by Dream-Master** [comment]
We waiting for a fix
