### ISSUE TITLE
Ores are not taking on proper stone type

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#2266]
Version 2.0.1.3, DirtHuts server

All overworld ores have stone background and all nether ores have netherrack background, even if they spawn in marble/granite veins:

![grafik](https://user-images.githubusercontent.com/11035501/34050300-ae4461b2-e1ba-11e7-973f-95e23ab66af3.png)

![grafik](https://user-images.githubusercontent.com/11035501/34050321-b89b8208-e1ba-11e7-90f6-62c40a6764f9.png)

Not sure what other info could be relevant here, so let me know if something needs testing

**Comment by Dream-Master** [comment]
@Toperoco In 2.0.2.0 Oregen totaly reworked so wait a bit and teset with this version. Thanks.

**Comment by richardhendricks** [comment]
Does not seem to affect all ores.  Spessartine etc do not show up right in marble, but banded ore malachite etc does.  Needs investigation.

**Comment by Dream-Master** [comment]
@richardhendricks is this fixed ?

**Comment by richardhendricks** [comment]
Discovered root cause - GT stones were being worldgenerated after GT ores.  So ores were being placed and then stones added.  If the stones intersected an already-placed orevein, the backgrounds were not updated.

Changed order of operation to do GT stones worldgen first, then GT ores.
