### ISSUE TITLE
EV microwave energy transmitter...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2267]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
...can't be crafted.
![2017-12-15_20 46 04](https://user-images.githubusercontent.com/25028786/34053744-0ad6d5cc-e1d9-11e7-8e14-1845a98c55f8.png)
![2017-12-15_19 17 47](https://user-images.githubusercontent.com/25028786/34053747-0e8f0450-e1d9-11e7-98a0-ea0cd3d1ed14.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Maybe fixed. Need to be tested
![image](https://user-images.githubusercontent.com/2970688/34060773-7fdb565c-e1e5-11e7-9a09-d913b7d9d0ea.png)
