### ISSUE TITLE
Enviromental processor from gendustry...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2271]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
...accepts only one type of Elite circuits.
![2017-12-16_01 33 20](https://user-images.githubusercontent.com/25028786/34063134-42e1cf58-e201-11e7-9996-f822740d74cf.png)

**Comment by Cinobi** [comment]
![2017-12-16_01 37 12](https://user-images.githubusercontent.com/25028786/34063216-b08cf0aa-e201-11e7-9bdb-35c89c010ba9.png)
this recipe too(geneticks processor)

**Comment by Dream-Master** [comment]
Yes will fix
