### ISSUE TITLE
Questbook progression issues (bronze age chapter)

### ISSUE THREAD

**Issue by donoya** [GTNewHorizons/NewHorizons#2272]
#### Which modpack version are you using?
2.0.1.3
#### What did you try to do, and what did you expect to happen?
Progress through the steel quest. For it to be possible.
#
#### What happend instead? (Attach screenshots if needed)
The bronze plated blast furnace was uncraftable.
#
#### What do you suggest instead/what changes do you propose?
Update the quest to use the bricked blast furnace, which has replaced the bronze plated blast furnace.

Also update the bronze age glass quest as it now seems to need steel. Or even better: re-enable the glass dust smelting recipes, because I had to cheat to complete that quest. And to go along with it, the first tank quest wants obsidian glass, which it says to use glass for, which you can't get until steel.  And there's probably a few other quests along these lines that'll need fixed.

**Comment by Cinobi** [comment]
I suggest u to use ./bq_user refresh. Do it every server update.
![2017-12-16_11 26 21](https://user-images.githubusercontent.com/25028786/34068842-08c47b4c-e254-11e7-9ef2-564ec19b2be5.png)

**Comment by Dream-Master** [comment]
Yes Quest is updated already so use new version please.
