### ISSUE TITLE
2.0.2.0 Gregtech cables fail to connect to machines

### ISSUE THREAD

**Issue by LandlessGuy** [GTNewHorizons/NewHorizons#2277]
#### Which modpack version are you using?

#2.0.2.0
#### If in multiplayer; On which server does this happen? 

#Singleplayer
#### What did you try to do, and what did you expect to happen?

#As of the previous version (2.0.1.3) my setup has run as normal, with all machines being powered and running correctly
#### What happend instead? (Attach screenshots if needed)

#On updating to latest version and login, all Gregtech cables (currently using 4x and 8x LV tin cables) no longer attach to machines and do not transmit power to them. Have tried replacing the machines and generators, as well as rotating the faces, which hasn't helped. Tried to replace the wires too, but this only makes the problem worse, as they fail to connect to both the machines and other surrounding wires then.
![2017-12-17_14 05 05](https://user-images.githubusercontent.com/1065033/34080372-7a767b24-e334-11e7-988a-e1306794706c.png)
![2017-12-17_14 05 14](https://user-images.githubusercontent.com/1065033/34080373-7f927766-e334-11e7-971b-e0aefe6626dc.png)
![2017-12-17_14 05 25](https://user-images.githubusercontent.com/1065033/34080376-84fb3436-e334-11e7-85bc-bb7f767f5726.png)

#### What do you suggest instead/what changes do you propose?
Any help with this would be massively appreciated, really enjoy playing this pack but currently can't used the newest improved version

**Comment by Radst0ne** [comment]
Use wire cutter or soldering iron to connect to machines (gt6 style cables)

**Comment by LandlessGuy** [comment]
Amazing, thanks for the advice. Didn't realise the GT mechanics had changed between versions, have tried with wire cutters and everything works normally now :)
