### ISSUE TITLE
GT Ruby block not craftable

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2278]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Make a Block of Ruby to breed Ruby bee
#
#### What happend instead? (Attach screenshots if needed)
Ruby bee require GT Ruby block, but, compressing rubies one gets a BoP Ruby block. Chiseling that produces Fools' Ruby block. 
#
#### What do you suggest instead/what changes do you propose?
Produce GT Ruby block by compressing rubies?

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by LOKKO12** [comment]
Ruby Bees should accept BoP Ruby block aswell.

**Comment by repo-alt** [comment]
> Ruby Bees should accept BoP Ruby block aswell.
So far they don't. I'll try some more cycles though.

**Comment by repo-alt** [comment]
Btw, I can confirm that BoP Ruby block works indeed. I assumed that it wouldn't because earlier I was unable to breed Uranium bee with ic2 uranium block, but with GT uranium it worked really fast, so I thought all these GT bees require GT blocks only.
