### ISSUE TITLE
Tin is needed for superconductors, should be present on high tier planets

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2279]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
When building superconductors, you need large quantities of tin.  But cassiterite sand/garnet sand vein is only on overworld, and cassiterite vein is only on 60-220.  
#
#### What do you suggest instead/what changes do you propose?
Please add tin veins to high tier worlds, and the Deep Dark.  Now that deep dark should work with veins above 128, maybe add cassiterite vein there?

**Comment by LOKKO12** [comment]
New Vein Idea (T3+)"Rich Tin":
Stannite = Cu2FeSnS4 (2%In)
Arsenopyrite = FeAsS
Galenit  = PbS
Casserite | Stannite | Galenit | Arsenopyrite | 3 | 10-30 | 4 | 32 | 10

**Comment by Dream-Master** [comment]
Will look if I can set casserite as prim or second mix.

**Comment by Dream-Master** [comment]
I will add also a Assembler recipe for this cable.

**Comment by benstuwie** [comment]
DD has tin veins, so does the bedrock dimension. You can also get it from a lot of other stuff, like lava/bees/crops. Tin isnt that hard to get

**Comment by bartimaeusnek** [comment]
TCetiE has Casserite Veins and Centauri Bb has Tin/Copper veins now:
https://github.com/GTNewHorizons/NewHorizons/pull/2867
[Actual Ore Sheet 2.0.3.1DEV](http://88.180.214.135:86/index3.html)
