### ISSUE TITLE
Long lapis rod

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#228]
No recipe for crafting it and is used in the Lapis electron tube

**Comment by Dream-Master** [comment]
Ok i will add some later.

**Comment by Dream-Master** [comment]
I added Recipes for Long Rods:
Rubber, Enderpearl, Endereye, Apatite, Sodalite, Lazurite, Lapis

**Comment by Dream-Master** [comment]
In the next update
