### ISSUE TITLE
Novice Thaumaturgy quests are on timers

### ISSUE THREAD

**Issue by Argail** [GTNewHorizons/NewHorizons#2280]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
private server updated with the above version
#
#### What did you try to do, and what did you expect to happen?
finished quests in novice thaumaturgy
#
#### What happend instead? (Attach screenshots if needed)
newly finished quests in novice thaumaturgy suddenly have a quest timer to redo them over and over again. Magic feather, Brewing Stand, etc...
#
#### What do you suggest instead/what changes do you propose?
Remove the timer tag, so it will only achieve once.

**Comment by Dream-Master** [comment]
Sure that's a bug.

**Comment by Dream-Master** [comment]
@Argail About magic map i am not sure. If you loose on you never get a new map or/and you go to a new TF area you map not drawing again the new area.

**Comment by Dream-Master** [comment]
Brewing Stand i remove the cool down.

**Comment by Argail** [comment]
Both magic map and magic map focus make sense to keep on timer.
Leaving those makes absolute sense.

Main point was on brewing point (after i generated a couple of stacks and my friend decided to deactivate it *cough cough* ) :-)

**Comment by Dream-Master** [comment]
Ah yes ok. If you found more bugs report it here. Thanks @Argail

**Comment by spinner2727** [comment]
@Dream-Master Should the Magic Map and Magic Feather quests be Consume = Yes?  Right now they aren't for me, so you keep your materials and then also get the magic map focus and map.

**Comment by Dream-Master** [comment]
Ok will check

**Comment by Dream-Master** [comment]
and fixed.
