### ISSUE TITLE
Bee Breeding Retrieval bug

### ISSUE THREAD

**Issue by Argail** [GTNewHorizons/NewHorizons#2281]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
private server updated with above version
#
#### What did you try to do, and what did you expect to happen?
Tried to go through the new bee breeding quest.
First quest is meadows + forest (retrieval works)
2nd part of the quest involves mutating to common bees. I have the common bees in my backpack. Doesn't count. 
#
#### What happend instead? (Attach screenshots if needed)
It cannot identify the common bee. I tried it with identified bees (after scanner) and i've tried them unidentified, when it still shows unknown genome. Neither worked. I also tried to breed them new from scratch. Didn't recognize it either. 
#
#### What do you suggest instead/what changes do you propose?
I think it might have something to do with the way, that forestry handles different mutations of the same bee. So it might only work with the bee, that NEI is showing with those exact properties, which is almost impossible to get to, if you breed around a bit. Is there a way to basically allow the retrieval to be any kind of this bee, as long as it's purebred?

**Comment by Dream-Master** [comment]
Did you try pristine stock not ignore?

**Comment by Argail** [comment]
Yes, i only use pristine stocks for everything. 

I sorted out all ignoble's when found and didn't breed them further.

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Maybe they not pure comon bees.

**Comment by Argail** [comment]
![new bitmap image](https://user-images.githubusercontent.com/34647016/34120582-7407f414-e426-11e7-99a8-0d607ae53c58.jpg)

**Comment by Argail** [comment]
I'd say, that's as pure as it gets in terms of purity. (that's the queen, because i keep it in automation)
Will make some quick tests in single player creative and update.

**Comment by Argail** [comment]
Ok did some creative tests. 
Quite interesting. No other bee worked. no new mutations, no bees from creative mode, 

I did try to create a new quest as a test. And while selecting the task for it, i used one of the common bees in the inventory as the task priority. It worked with that exact bee, but no other mutations of the same bee.
Since every species can have different lifespans, production, pollination, etc.. there are countless permutations. And i do believe, there is some kind of trigger, that only allows an exact match to whichever bee was used in the creation of the quest to work. 
If anyone else has any thoughts on this? Is there some kind of trigger to allow any type of subspecies? deselect NBT data or something like that?

**Comment by Dream-Master** [comment]
I remove all nbt data from bee except name (common) and pristine.  Not sure what went wrong need to test

**Comment by Dream-Master** [comment]
The quest need only drones and princess no queen.

**Comment by Argail** [comment]
Yeah, of course i used princess and drones.
Screenshot just shows, that the breed is pure. Princess and drone has exactly the same stats.

**Comment by Dream-Master** [comment]
Please use with the bee in hand /mt  hand and send the text here.

**Comment by Dream-Master** [comment]
From Drone and Princess

**Comment by Argail** [comment]
Ok we did that and we also took the princess/drone from the creative menu, so you can compare side by side:

Drone Creative
[03:31:05] [Client thread/INFO]: [CHAT] <Forestry:beeDroneGE>.withTag({MaxH: 20, Health: 20, IsAnalyzed: 1 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesCommon", UID0: "forestry.speciesCommon", Slot: 0 as byte}, {UID1: "forestry.speedSlower", UID0: "forestry.speedSlower", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})

Drone Bred
<Forestry:beeDroneGE>.withTag({MaxH: 20, Health: 20, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesCommon", UID0: "forestry.speciesCommon", Slot: 0 as byte}, {UID1: "forestry.speedFast", UID0: "forestry.speedFast", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityHigh", UID0: "forestry.fertilityHigh", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlower", UID0: "forestry.floweringSlower", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})

**Comment by Argail** [comment]
Princess Creative
<Forestry:beePrincessGE>.withTag({MaxH: 20, Health: 20, IsAnalyzed: 1 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesCommon", UID0: "forestry.speciesCommon", Slot: 0 as byte}, {UID1: "forestry.speedSlower", UID0: "forestry.speedSlower", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})

Princess Bred
<Forestry:beePrincessGE>.withTag({MaxH: 20, GEN: 207, Health: 20, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesCommon", UID0: "forestry.speciesCommon", Slot: 0 as byte}, {UID1: "forestry.speedFast", UID0: "forestry.speedFast", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityHigh", UID0: "forestry.fertilityHigh", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlower", UID0: "forestry.floweringSlower", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})

**Comment by Dream-Master** [comment]
Found the error forgot to delete some nbt data. Will fix and upload new version here for testings.

**Comment by Dream-Master** [comment]
One Common bee was not pure in the Quest

**Comment by Argail** [comment]
Makes sense :-)
Thanks

**Comment by Dream-Master** [comment]
[DefaultQuests.zip](https://github.com/GTNewHorizons/NewHorizons/files/1571229/DefaultQuests.zip)
