### ISSUE TITLE
Bee Reward Upgrades not working

### ISSUE THREAD

**Issue by Argail** [GTNewHorizons/NewHorizons#2282]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
private server with above update
#
#### What did you try to do, and what did you expect to happen?
In the Reward Area in the quests, the quest says Bee Basic > Advanced.
#
#### What happend instead? (Attach screenshots if needed)
Instead of basic bee loot bags, it requires Forest Ranger basic bags and would give as reward Forest Ranger Advanced bags. This is already covered in the Forestry basic > advanced questline.
#
#### What do you suggest instead/what changes do you propose?
Change forest ranger to bee loot bags as requirement and reward in the bee upgrade chain.

**Comment by Dream-Master** [comment]
Will look into it
