### ISSUE TITLE
Oil generation is every 8 chunks, not every 6.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2283]
Please update questbook to say search for oil every 8 chunks, not every 6.

moronwmachinegun - Today at 11:26 AM
Looks like 8 to me, not sure where 6 comes from.
        //GEN IT TO GET OBJECT...
        final XSTR tRandom = new XSTR(aWorld.getSeed() + aWorld.provider.dimensionId * 2 +
                       (chunk.getChunkCoordIntPair().chunkXPos>>3) +
                8267 * (chunk.getChunkCoordIntPair().chunkZPos>>3));
        GT_UO_Fluid uoFluid = GT_Mod.gregtechproxy.mUndergroundOil.GetDimension(aWorld.provider.dimensionId).getRandomFluid(tRandom);
And it's +-25% not 50%
                fluidInChunk.amount=(int)((float)fluidInChunk.amount*(0.75f+(XSTR_INSTANCE.nextFloat()/2f)));//Randomly change amounts by +/- 25%

**Comment by Dream-Master** [comment]
ok will do.

**Comment by richardhendricks** [comment]
Checking our code vs GT5U master, it looks like master *is* every 6 chunks, but GTNH branch is every 8.
