### ISSUE TITLE
Cables disconnecting from machines

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#2284]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
Place a GT cable connected to a machine, and then leave/reenter the world or unload and reload the chunk. I expected the cable to remain connected when I came back.
#
#### What happend instead? (Attach screenshots if needed)
It disconnected and needed to be switched back with wire cutters.
#
#### What do you suggest instead/what changes do you propose?
bugfix

**Comment by Dream-Master** [comment]
Next update we have a fix.
