### ISSUE TITLE
Player crashes due to riding into a beehive

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2285]
ElectroBot - Today at 4:25 PM
your head is partially in a Forestry forest Hive
YaNKee - Today at 4:25 PM
just crashed out again...
ElectroBot - Today at 4:25 PM
try again. I moved the hive
YaNKee - Today at 4:25 PM
my head is in a hive?!
hahaha ok one sec.. did you see me try to spawn?
ElectroBot - Today at 4:26 PM
no, I grabbed your actual crash co-ords from the crash log
YaNKee - Today at 4:26 PM
how weird is that.. I was on my horse.   ok let me see .. have to reload the damn client.. takes like 5 mins.. :frowning:  sorry.

YaNKee - Today at 4:38 PM
so that was all because I died inside a beehive on my horse?!  ahha what a whacky odd thing
ElectroBot - Today at 4:39 PM
You crashed when your head became stuck in a bee hive while riding a horse

**Comment by richardhendricks** [comment]
Client side crash, not server.

https://pastebin.com/87zUtCn4

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Stacktrace:
    at net.minecraft.client.renderer.ItemRenderer.func_78446_a(Unknown Source)
    at net.minecraft.client.renderer.ItemRenderer.func_78447_b(Unknown Source)
    at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:744)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
 
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['YaNKeeR'/20207649, l='MpServer', x=-3.38, y=84.32, z=705.09]]
    Chunk stats: MultiplayerChunkCache: 40, 40
    Level seed: 0
    Level generator: ID 04 - RWG, ver 0. Features enabled: false
    Level generator options:
    Level spawn location: World: (-236,64,815), Chunk: (at 4,4,15 in -15,50; contains blocks -240,0,800 to -225,255,815), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 148153491 game time, 176308631 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by Dream-Master** [comment]
very wired issue :P

**Comment by wumbla** [comment]
Also had the issue happen to me, was riding a horse and as soon as my head went inside the hive i crashed and would immediately crash whenever i logged in.

**Comment by bartimaeusnek** [comment]
@richardhendricks we have some custom version i've send to you in DSC
