### ISSUE TITLE
Sodium Persulfate recipe ridiculously long

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2286]
Sodium persulfate directly from sodium, sulfur, and oxygen has a 400s recipe to make 6 (or 67s per NaSO4), which just seems really long.
![2017-12-18_20 28 47](https://user-images.githubusercontent.com/1214811/34137814-48bdf392-e432-11e7-8d47-dac209e779f5.png)

Especially since the bisulfate method is almost trivial
![2017-12-18_20 32 39](https://user-images.githubusercontent.com/1214811/34137883-a58ca47e-e432-11e7-8475-c6cbdea048e8.png)
![2017-12-18_20 32 46](https://user-images.githubusercontent.com/1214811/34137891-a8172cd2-e432-11e7-9d68-c78c2ea9576d.png)
36s to make 1, with hydrochloric acid and hydrogen as very useful byproducts.

**Comment by Dream-Master** [comment]
Yes maybe 40 secs max.
