### ISSUE TITLE
Genetics mod (binnies) missing enzyme recipe for raw DNA production.

### ISSUE THREAD

**Issue by S0rn0** [GTNewHorizons/NewHorizons#2287]
#### Which modpack version are you using?
GTNH 2.0.1.3

#
#### If in multiplayer; On which server does this happen? 
Dirthuts GTNH 2

#
#### What did you try to do, and what did you expect to happen?
USe the Genetics mod to manipulate bees. I went to go and create enzyme to create the raw DNA.

#
#### What happend instead? (Attach screenshots if needed)
Could not create enzyme. No recipe.

#
#### What do you suggest instead/what changes do you propose?
Create the recipes for enzymes to allow the Genetics mod to function, or remove the Genetics mod machine recipes.

**Comment by Dream-Master** [comment]
Many recipes have no nei support. Binnies mods machines not shown in nei often. Enzyme have a recipe.

**Comment by Dream-Master** [comment]
You need a Binnies Mods Incubator, Sugar and Bacteria Fluid to make Enzyme.

https://binnie.mods.wiki/wiki/Enzyme

**Comment by S0rn0** [comment]
Ah hah. Makes sense! Sorry for the confusion.

**Comment by Dream-Master** [comment]
np

**Comment by Dream-Master** [comment]
Tested and works

![image](https://user-images.githubusercontent.com/2970688/34151778-ba69ee86-e4ac-11e7-8b67-b25a65476379.png)
