### ISSUE TITLE
Deep Dark Ores need to be stretched from Y 250 to 0

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2289]
Deep Dark Ores need to be stretched from Y 250 to 0

**Comment by Dream-Master** [comment]
Not working need a fix.

**Comment by mitchej123** [comment]
If I recall from Moron's exploration of the deep dark & oregen; the cause was deep dark being flagged as 'nosky' which is a badly named flag for isnether - caps the oregen at 128y and makes lava flow faster.  I can't recall if he implemented a workaround without needing to recompile exu.

**Comment by Dream-Master** [comment]
If this is fixable sure do what ever you need to do. @mitchej123

**Comment by richardhendricks** [comment]
We can fix it by patching the place ores function in gregtech.  I thought I removed the check, must have accidentally put it back in.
