### ISSUE TITLE
Muddy Armor no longer craftable

### ISSUE THREAD

**Issue by scutajar** [GTNewHorizons/NewHorizons#2290]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
Both MP and SP
#
#### What did you try to do, and what did you expect to happen?
Was trying to complete the Muddy Armor quest in Armor and Jetpacks section. Collected 64 Mud Balls which are not being recognised by the quest book, and cannot craft any of the Muddy Armor.
#
#### What happend instead? (Attach screenshots if needed)
Crafting recipe not recognised
#
#### What do you suggest instead/what changes do you propose?
Should be fixed, this worked in 2.0.1.3

**Comment by Dream-Master** [comment]
Not change anything in the Quest. Try to make the Wood armor Quest and get mudballs as reward. This works i test it b myself.

**Comment by scutajar** [comment]
Did some more testing, turns out the the quest is only marked as completed if you collect the items when the quest is active (so if you've collected the necessary mud balls before the quest has become active, you cannot complete the quest).

**Comment by Dream-Master** [comment]
That's true. Hit the submit button will help too.

**Comment by scutajar** [comment]
Submit button does not work if items are collected before the quest is active, but this works after the quest becomes active.

**Comment by Dream-Master** [comment]
ok. cool. Issue can be closed ?
