### ISSUE TITLE
Pure tears quest too easy 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2292]
#### Which modpack version are you using?
2.0.1.3
#
Can't tell if this is intentional, but the pure tear thaum quest doesn't need ichroim, while the tear itself does. The ichorium is by far the hardest part to get, as you need LuV to smelt the osmiridium needed. The quest option also doesn't need essentia or wait time on the infusion. This kind of makes crafting them normally a huge waste of resources and time.
I think the quest should be one time, and need the same ichorium as the recipe. That way, making them normally will still be useful/needed, while the quest can help for the very first one you need.

**Comment by Dream-Master** [comment]
Good idea. Will change it.

**Comment by LOKKO12** [comment]
I think changing the quest to use ichorium is destroying the meaning of the quest, to purge warp earlier. It might be better to change the pure tears recipe to not use Ichorium, to make it aviable in EV/IV. Maybe it should use Tungstensteel and some more essentia...

**Comment by Dream-Master** [comment]
yea i will make the quest not repeatable and maybe add some materials more. Will see.

**Comment by benstuwie** [comment]
It's available in EV if you buffer power. It's just a little annoying. You can easily not get that much warp before you hit EV, it'll just be a little annoying too

**Comment by Dream-Master** [comment]
Ok now everyone is happy.
I make the quest not repeatable. And i add all the ressources to the quest.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34243877-3b9171d8-e623-11e7-9910-e373faf01172.png)
![image](https://user-images.githubusercontent.com/2970688/34243880-3e439fbe-e623-11e7-82e9-a263d14fb454.png)
![image](https://user-images.githubusercontent.com/2970688/34243884-431e9912-e623-11e7-91d7-d194a4e45ab5.png)
![image](https://user-images.githubusercontent.com/2970688/34243889-461026f4-e623-11e7-8575-3742943c90c0.png)
![image](https://user-images.githubusercontent.com/2970688/34243895-49e58580-e623-11e7-9518-c2c9e56fe585.png)
