### ISSUE TITLE
witch's cauldron uncraftable?

### ISSUE THREAD

**Issue by Cylkin** [GTNewHorizons/NewHorizons#2293]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
Wanted to make a witches cauldron to get Mutandis to start with witchery
#
#### What happend instead? (Attach screenshots if needed)
No recipe, seems to be missing entirely.
#
#### What do you suggest instead/what changes do you propose?
Quest order seems correct, but Thaumonomicon entries skip the cauldron. It is needed to craft both the Altar and the kettle, so it should be added to the Thaumonomicon following the order presented in the quest book.

**Comment by Dream-Master** [comment]
I add it to Thaumcraft Book.

**Comment by Cinobi** [comment]
Time to read some guides about witchery? Witches caudron is creating by use some dust(don't remember actual name) to vanilla cauldron.

**Comment by Cinobi** [comment]
Tested - just use "Annointing paste" to vanilla cauldrone. Base Witchery thing, no GTNH changes here.

**Comment by Cylkin** [comment]
You are right, it just is not mentioned in the quest. As all quests up to this point regarding non-vanilla mechanics at least hinted at what to do, I would still suggest adding a short explanation.

**Comment by Dream-Master** [comment]
Yea i will write some new recipe for annotaing paste and add it to Thaumcraft book.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34244339-204d6da8-e625-11e7-882a-90b16994e78c.png)
![image](https://user-images.githubusercontent.com/2970688/34244343-2596ab6c-e625-11e7-82e3-2a1beed56351.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34244550-0f2558be-e626-11e7-8d72-75fc4769a063.png)
