### ISSUE TITLE
Alvearis quest (#1123) in how to bee not finishable due to item amount

### ISSUE THREAD

**Issue by Argail** [GTNewHorizons/NewHorizons#2294]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
Tried to finish quest Alvearies 1123
#
#### What happend instead? (Attach screenshots if needed)
![new bitmap image](https://user-images.githubusercontent.com/34647016/34214454-d02bf880-e5a2-11e7-970c-24de7b47d6cf.jpg)

the amount of items needed to finish the quest doesn't fit into the inventory, even if i unequip everything :-)
4 rows + 1 vs 4 rows
#
#### What do you suggest instead/what changes do you propose?
Either reduce the quest (craft 9 alvearis or something instead) or put in an additional step at step 1.

**Comment by Dream-Master** [comment]
Did you try with the submit station ?

**Comment by Dream-Master** [comment]
I can split this in two parts maybe

**Comment by Argail** [comment]
No, haven't tried this yet.
I assume, that this will work. Haven't thought of it.
But then again: that would be the first quest i've stumbled upon, that needs it. 
If there are any others, it's alright. If this is the only one, then i would split it.

**Comment by Dream-Master** [comment]
I will add a quest for submit station and maybe split the quest.

**Comment by Argail** [comment]
I tried it with submit station too and that didn't work either, so splitting is probably the best way.

**Comment by Dream-Master** [comment]
I split it.
