### ISSUE TITLE
Storage Drawer Upgrades

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2295]
#### Which modpack version are you using?
2.0.2.5
Jabba storage upgrades are craft-able outside of a assembler now but the ones for storage drawers are not.

**Comment by Dream-Master** [comment]
Both are craftable.

**Comment by Dream-Master** [comment]
sure not make sense will add this.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34245192-24eab8ee-e629-11e7-9899-40048b158fc1.png)
