### ISSUE TITLE
Suggestion change restone quest steam age

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#2296]
#### Which modpack version are you using?
2.0,1,3
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What do you suggest instead/what changes do you propose?

I suggest that in the steam quest line the redstone quest for the main quest be changed to just having enough redstone available. Finding the ore can be hard but while you look your bound to find tons of small ore for redstone and you can end up with more then enough to proceed with tech long before you ever find such a vien.

I would suggest the current quest be moved to a side quest opening up at the same time as the redstone quest.

**Comment by Dream-Master** [comment]
Sure i can make Redstone Ore optinonal.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34245379-f1a0aae2-e629-11e7-83ae-3d053a768396.png)
