### ISSUE TITLE
Crash on Startup and question about crash on startup with Thermos

### ISSUE THREAD

**Issue by Symsyr** [GTNewHorizons/NewHorizons#2298]
#### Which modpack version are you using?
2.0.1.4
#
#### If in multiplayer; On which server does this happen? 
Personally hosted open server
#
#### What did you try to do, and what did you expect to happen?
I deleted the mods, config and scripts folders on the server, then copied over the newly created ones.  Did my bash ServerStart.sh and expected it to start
#
#### What happend instead? (Attach screenshots if needed)
It failed on startup:  https://pastebin.com/rES6qFQT

I also have this one when trying to start with Thermos:  https://pastebin.com/WDpAmUPc

I did paste this in the Help channel on the discord but it looks like that a conversation got carried on in there

**Comment by Dream-Master** [comment]
Luminen ressource loader? I guess you are using some mod that not have to be on the server like luminen core or in-game info xxl or stackies.

**Comment by Symsyr** [comment]
I downloaded the new pack via Twitch launcher, deleted mods, config and scripts, then copied over updated mods, config and script folders

**Comment by Dream-Master** [comment]
http://www.minecraftforum.net/forums/support/server-support/2439405-modified-modpack-server-help

Custom Main Menu Mod is a client only mod.

**Comment by Dream-Master** [comment]
@Symsyr and did it work now?

**Comment by Namikon** [comment]
Why not download the official Server-Pack here?
http://downloads.gtnewhorizons.com

**Comment by Dream-Master** [comment]
Twitch not have the server pack so far i know. Thats explain why client mods in your Server folder.

**Comment by Symsyr** [comment]
Sorry, fell asleep and will test tonight when I get home from work

Do you have an idea about the Thermos crash?

**Comment by Namikon** [comment]
Remove CustomMainMenu from your Server-Mods (Or just use the ServerPack)
The crash with Thermos could be a DimensionID overlapping or a World-corruption. I suggest verifying the config files (or use the ServerPack)

**Comment by Symsyr** [comment]
Twitch does have a server pack but it only includes the overrides folder with the mods that updated, not all of the mods in it. 

@Namikon, Thank you for linking the official server download link, that is where I will download the update from

**Comment by Symsyr** [comment]
Also, for the Thermos, when I delete the level.dat file in the root world folder, it works.

**Comment by Dream-Master** [comment]
ok good. Can iclose this issue ?

**Comment by Dream-Master** [comment]
@Symsyr

**Comment by Symsyr** [comment]
Sure, if I need to, I can open a new one
