### ISSUE TITLE
[Suggestion] Improve usefulness of Thaumcraft Native Clusters

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/NewHorizons#2299]
#### Which modpack version are you using?
2.0.2.5
#
#### What do you suggest instead/what changes do you propose?
Give more use out of native clusters than being an alternative to macerating ores and getting a few more tiny dusts.

An idea to make them more useful, have some be usable in EBF for more EU/Oxygen/Time efficiency. Another thought would be to add more Native Clusters for pure ore types.

### Examples: 
- Native Iron Cluster + Oxygen + Standard Steel EBF settings = 2 Steel Ingots.
- Native Copper Cluster + Oxygen + Standard Annealed Copper EBF Settings = 2 Annealed Copper Ingots
- Could add more native clusters such as Aluminium and Titanium and have a similar EBF recipes.
-For higher tier native clusters perhaps increase alchemy cost to produce the Native clusters, since by then the player should have higher tier Alchemy Equipment.

**Comment by Dream-Master** [comment]
Add recipes for existing cluster  I can try. Add new clusters isn't possible I guess because how I can add them? Thaumcraft is closed source and wrote an add-on mod for it i think my java knowledge isn't good enough.

**Comment by Dream-Master** [comment]
Ok it not make sense to  add it because it works only on vanill/mod ores.
Gregtech Ores are not supported so far i can see.
There is a addon mod who ads more clusters but we diable most of the mods ores.

**Comment by Dream-Master** [comment]
https://minecraft.curseforge.com/projects/another-one-bites-the-dust

**Comment by bartimaeusnek** [comment]
fixed with WG
