### ISSUE TITLE
Infernal mobs

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#230]
Remove 100% Infernal for Hellhounds, Blazes and Magma cubes

**Comment by Dream-Master** [comment]
why?

**Comment by Dream-Master** [comment]
Walking in the Hell is not a easy walk.

**Comment by Namikon** [comment]
Well, If I hadn't my bubble, every so often I'd be killed due an infernal camping at my portal, and just today one warped back to my base with the fireball ability. 

The nether is crazy difficult without fly mode, I don't even dare to walk outside. But I guess I'm always complaining about such things, maybe someone else can second drobacs opinion here

**Comment by Drobac** [comment]
Hellhounds hit like crazy even in their vanilla form and make it impossible for any kind of trip into the nether and you cant hide in 1x1 holes cause they go through that. Facing a blaze even normally is hard since we have no regen so if you are set on fire you have to quit trying to kill it immediately, add infernal features to that and it becomes impossible to get any blaze rods. Magma cube are pointless to have infernal since when you kill the big infernal magma cube you get a lot of little infernal magma cube which dont even drop anything (only medium ones drop anything).

**Comment by Teteros** [comment]
Don't forget the infernal de-buffs affecting the player such (as blindness) that mobs there love to give.

**Comment by Dream-Master** [comment]
Maybe i will re-enable the Jetpack from Project Red witch has a lower Cost than a regular IC2 Jetpack (Glowstone, Project Red Batteries and maybe a Diamond Armor like the original Recipes.) With this Jetpack you can fly only 20-30 secs(full power) but for a short Jump to a safe Place it would solve this problems.

**Comment by Dream-Master** [comment]
The Projec Red Jetpack flying now a bit longer and not above Level 130.

**Comment by Namikon** [comment]
Is the jetpack available? I probably should build one then...
I went to the nether yesterday, and I spawned on y-level 100, which seems to be a kind of floating island above a lava ocean (yay...). 

About the infernals, with full enchanted armor (fire protection III on legs, protection II and III on helmet and shoes) and a decent sword (Tinkers cleaver made of manyu..whatever), it is possible to fight them (if they don't teleport and don't have regen...). 

To get the armor, I had to kill a dozen or more regular mobs, and I died a couple of times for that. But if you sum it up, it seems to be doable. In no way easy, and a long way to go, but doable. Question is, is that a thing that's meant to be like that.

I second the idea about changing *some* aspects of the infernals:
The default loot table contains things like cookies. Could we change this loot-table to only drop valueable stuff? Like, if you kill an infernal, they should always drop some undamaged armor, or a couple of diamonds, or even loot bags from thaumcraft. (Don't worry about mob-grinders, as infernals won't drop stuff if they die from a natural damage source. A player has to kill them)

I still have to try to fight against blazes, but in general, fireprotection on your armor does a wonderfull job.

Not sure about the magma cubes. With looting on your sword, they are a pretty nice source of magma cream, which is basically an alternative to get blaze powder.

Hellhounds: I want to test that too, but they do a f-ton of damage even without being infernal.

In general, removing 100% infernal is not a bad idea. It's not that the request is to never let them spawn as infernal, it's only the "you are always f*cked if you see one" thing that's a bit too much for those mobs

**Comment by Drobac** [comment]
Nether is extremely dangerous even if we had 0 infernals, just mining creates danger because it angers mobs towards you. Just imagine if you are mining and 10 infernals just rushes you, there is no defense for it.
Normal percent infernal for the mobs would be ok, this way you get killed by 5 infernal hellhounds with 200 HP minimum rushing you.

**Comment by Dream-Master** [comment]
I say it again it is the HELL. THE HELL!!!

**Comment by Namikon** [comment]
Ok, as you wish. Your decision. I will close this issue

**Comment by Namikon** [comment]
Ok. I'm not going to discuss that any further now, as you obviously think that we are just trying to make everything nice and easy.
