### ISSUE TITLE
Lapis and diamond veins are incredibly rare/nonexistant

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2302]
#### Which modpack version are you using?
2.0.2.5 TEST version
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I looked for lapis and diamonds, the two overworld veins I haven't found yet.
#
#### What happend instead? (Attach screenshots if needed)
I explored this ENTIRE area on the map, with a prospector's scanner so I wouldn't miss anything, and didn't find a SINGLE vein of diamond or lapis.
![2017-12-21_14 48 46](https://user-images.githubusercontent.com/29802757/34272392-206898a6-e65e-11e7-8137-9cc040fa8e25.png)

#
#### What do you suggest instead/what changes do you propose?
Make lapis and diamond ore more common, or make them spawn if they don't, I'm not sure which is the issue.

**Comment by Dream-Master** [comment]
No they not but if you found one you can search around and found another very close.
Try to create a new world and use the Orscanner to see how veins looks like.

**Comment by Dream-Master** [comment]
If i change one mix all other will chang too. @richardhendricks  Was the oremixes before your code change ignore configs?

**Comment by richardhendricks** [comment]
Diamond has a 2.6% base chance in a filled orevein.  Looks like you searched about 30 spots and found ore? Chance of finding diamond after 30 spots is 1-(1-.026)^30, or about 55%. Not surprising you haven't found any yet.

https://docs.google.com/spreadsheets/d/18bCPP7Ul9CMtTXsVwQvEeZCAzrR7OLzizMnwJfvRzx0/htmlview

**Comment by richardhendricks** [comment]
Sorry, you said you explored the entire area with a prospectors scanner? Can you post a screen shot?

**Comment by Dream-Master** [comment]
i can make screenshots if you want. I found 2 or 3 lapis veins in a 500x500 radius.

**Comment by richardhendricks** [comment]
@Bluebine Please provide worldseed for your SP game and I will do an orevein search.

**Comment by richardhendricks** [comment]
Screenshots aren't necessary, I'm going to do a couple of test runs with debug enabled and just make a spreadsheet

**Comment by richardhendricks** [comment]
[orevein_sampling_sorted.txt](https://github.com/GTNewHorizons/NewHorizons/files/1628041/orevein_sampling_sorted.txt)

2001 ore seeds. 
34 apatite
13 cassiterite
248 coal
184 copper
209 custom.06
169 custom.07
23 custom.08
14 custom.09
23 diamond
495 gold
227 iron
26 lapis
18 lignite
50 magnetite
12 manganese
17 oilsands
115 redstone
104 salts
20 soapstone

**Comment by richardhendricks** [comment]
Second worldseed, similar bias.

```
1417 ore seeds.  485 skipped by design, so 485/(1902) = 25.5% empty, as expected.
Found |  Percentage	| Expected 	| ore                  | notes
  13  |     0.92%   |   10.50%  | lignite              | Expected, lignite is only available at really high heights
 173  |    12.21%   |    5.20%  | coal                 | Oddly high
  33  |     2.33%   |   10.50%  | magnetite            | Expected, magnetite is only available at really high heights
 326  |    23.01%   |   10.50%  | gold                 | Oddly high
 176  |    12.42%   |    7.89%  | iron                 | Oddly high
   8  |     0.56%   |    3.20%  | cassiterite          | Expected, cassiterite is only available at really high heights
 117  |     8.26%   |    5.20%  | copper               	
  61  |     4.30%   |    5.20%  | salts	
  91  |     6.42%   |    3.90%  | redstone	
  22  |     1.55%   |    2.60%  | soapstone	
  13  |     0.92%   |    1.30%  | manganese	
  28  |     1.98%   |    2.60%  | diamond              	
  27  |     1.91%   |    3.9%   | apatite              	
  20  |     1.41%   |    2.60%  | lapis	
 133  |     9.39%   |    5.20%  | custom.06(min sands) | Oddly high
 124  |     8.75%   |    5.20%  | custom.07(garnet/tin)| Oddly high
  32  |     2.26%   |    3.90%  | custom.08(kaolinite) 	 
   7  |     0.49%   |    1.30%  | custom.09(mica)      	
  13  |     0.92%   |    2.60%  | oilsands	
```

**Comment by richardhendricks** [comment]
Ok, seems to be inherent to Gregtech, similar effect on minimal dev pack
![image](https://user-images.githubusercontent.com/1214811/34911123-d55d1ee4-f888-11e7-895f-4e9b9a66ef48.png)

**Comment by richardhendricks** [comment]
Created new ticket on my profile so I can collect info without spamming everyone.

**Comment by richardhendricks** [comment]
Problem root caused, fix under evaluation.

**Comment by richardhendricks** [comment]
Okay, ratios look good now. Tested on a stripped modpack, will do full modpack testing tomorrow.
![image](https://user-images.githubusercontent.com/1214811/34931672-84ffc862-f995-11e7-8a4b-096c835a5824.png)

**Comment by richardhendricks** [comment]
OK, tested Overworld, Nether, Twilight forest, numbers look much better now.

Still need to test The End and Deep Dark.  I think all other dimensions are handled by other code, and if new dimensions are added to GT spawning, should be good enough.

Note that iron in Nether and copper in Twilight Forest in the ore spreadsheet is incorrect, they do not spawn there.

![image](https://user-images.githubusercontent.com/1214811/35085309-bb1fe4b8-fbed-11e7-8071-dade56a6f2cf.png)

![image](https://user-images.githubusercontent.com/1214811/35085317-c4a8ecf0-fbed-11e7-9cad-2f1ab9459185.png)

Since the Twilight Forest average height is so low, many veins are skewed lower/higher than normally expected.
![image](https://user-images.githubusercontent.com/1214811/35085337-d4ecd13a-fbed-11e7-8c69-61026b726396.png)

**Comment by richardhendricks** [comment]
Tested Deep Dark and the End (essentially almost zero ores due to tiny asteroids)

Everything looks good, PR filed.

Deep dark sample ore distribution
![image](https://user-images.githubusercontent.com/1214811/35180807-f8c35fe4-fd7c-11e7-9326-fcd429081f15.png)

**Comment by chrisstuartparry** [comment]
Apologies if this is shouldn't be posted, idk who it'll ping, plus I'm posting on a very old, closed post, but I just wanna say I appreciate the effort that went into fixing an issue that could have easily been hand-waved away by "look harder". Additionally, the data collection and presentation is really cool to see.
