### ISSUE TITLE
Harvestcraft crops don't drop anything when destroyed

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#2303]
#### Which modpack version are you using?
2.0.2.5 TEST version
#
#### If in multiplayer; On which server does this happen? 
SinglePlayer
#
#### What did you try to do, and what did you expect to happen?
Planted a harvestcraft crop and hit it afterwards. Expected to get a seed back like it works with vanilla wheat-seeds.
#
#### What happend instead? (Attach screenshots if needed)
I didn't get a seed, instead the seed and the plant are lost.
#
#### What do you suggest instead/what changes do you propose?
I suggest to just drop a seed everytime a harvestcraft crop is destroyed, so nothing is lost.
Since "getDrops" can't distinguish between right-clicking and breaking the block, overriding "breakBlock" and spawning a seed-item there should work best.

**Comment by Traxis** [comment]
You may want to check the harvestcraft.cfg file in the config folder, and look for "cropsdropSeeds". Then you'll see that it's set to "false", and that's why you won't get seeds from crops. If you set it to "true", you should get them as you wanted.

**Comment by DarkShadow44** [comment]
This doesn't work when the plant is not mature, either. The plant is still lost when destroyed.
Note that, when the plant is mature, the HungerOverhault overrides kick in, so you still don't get a seed unless you configure HungerOverhault to do so. But when not-mature, the plant still doesn't drop anything.

**Comment by Dream-Master** [comment]
So what we need to do? Change the config or better not?

**Comment by Traxis** [comment]
@DarkShadow44 Oh yeah, I forgot about HungerOverhaul. In that case, check the HungerOverhaul.cfg file inside the HungerOverhaul folder in the config folder, and look for these options: modifyCropDropsBreak, seedsPerHarvestBreakMax, seedsPerHarvestBreakMin. If you change them, you'll be able to get the effect/s that you want.

@Dream-Master I'd change only the "modifyCropDropsBreak" option, and only if more people have issues with that (after all, anyone can change any options in the configs to their needs). The only way to get seeds right now is from the crops themselves which you can find in Pam's Gardens, trading with NPCs and maybe from some Quests, is that right? I wouldn't change that.

**Comment by Dream-Master** [comment]
Ok then we can close this issue ? @DarkShadow44 @Traxis  everyone make the config on sp they lie ?

**Comment by Traxis** [comment]
Maybe ask around in the Discord server and see what others think. But this is not an issue or a bug, more like a suggestion because of how the mods work.

**Comment by DarkShadow44** [comment]
@Traxis 
HungerOverhault doesn't do anything if the crop is not mature:

` boolean fullyGrown = ((!isNaturaCrop) && (event.blockMetadata >= 7)) || ((isNaturaCrop) && (event.blockMetadata == 3)) || (event.blockMetadata == 8);
    if (!fullyGrown) {
      return;
    }`

@Dream-Master 
There is no config I'd know of that would allow you to get something from breaking a not-mature plant. I'm afraid it won't be possible without code changes.

I mean, you could make it drop a vegetable instead of a seed too, but then you can plant and get a vegetable for breaking it again. Or you allow breaking it to return a seed, even if a vegetable was planted. Or you say that a non-mature plant that gets harvested is just lost. Or you somehow store what was planted (seed or vegetable) in the crop somehow. These are the only options I see, and I really don't like the plant just being lost.

**Comment by Dream-Master** [comment]
Code change i cant do by myself. Need to ask in the community.

**Comment by DarkShadow44** [comment]
Because you're not a coder, you mean? I'd submit a pull request, but I don't have the sources.

**Comment by Dream-Master** [comment]
https://github.com/MatrexsVigil/harvestcraft

but this is the source for the newest version.

**Comment by DarkShadow44** [comment]
> but this is the source for the newest version.

This only is the source for 1.11.2i and up. And didn't you say you have an already modified version?

**Comment by Dream-Master** [comment]
Yes but i am not sure which one make the code changes and what exactly be changed . I need to look into old changelogs.

**Comment by DarkShadow44** [comment]
Well, since we anyways use HungerOverhault to modify the crop drops, one could also add that feature into HungerOverhault (https://github.com/progwml6/HungerOverhaul/tree/master). You're not using a private version of that already, right?

The question is, how do you want it to work?
- Non-mature plants drop nothing
- Non-mature plants drop one seed
- Non-mature plants drop one vegetable

**Comment by Dream-Master** [comment]
Honestly i not care much about harvestcraft. It worked fine  for me.

**Comment by DarkShadow44** [comment]
So basically, you're fine with the way it currently is, i.e. plants just being destroyed when harvested non-mature?

**Comment by Dream-Master** [comment]
yea like in real life. If you grab a non mature plant you need get the seed back or not get an fruit/vegetable.

**Comment by DarkShadow44** [comment]
Yeah, I want a seed back (like with wheat), but you don't get anything.

**Comment by Dream-Master** [comment]
Ok and to get an seed back what need to be changed?

**Comment by DarkShadow44** [comment]
Basically a small change to either Harvestcraft or HungerOverhault, to make it drop that seed.

**Comment by Dream-Master** [comment]
Codewise or cfg like?

**Comment by DarkShadow44** [comment]
Codewise, there is no config option for that.

**Comment by Dream-Master** [comment]
Version L is the latest  version and I name it in GTNH M. guess I fixed only a localizer or name/texture nothing in code is changed.
That means I don't have a decompiled version for you. 
If you want to change it you need to do it by yourself otherwise I don't see a issue here.

**Comment by DarkShadow44** [comment]
Well, I made a fork from HungerOverhaul and added it there (https://github.com/DarkShadow44/HungerOverhaul/commits/master). This should do it. Would you want that in the official pack or not?

**Comment by Dream-Master** [comment]
Yes we can merge this when this is tested.

**Comment by Dream-Master** [comment]
@DarkShadow44 I see a commit from you on Hunger Overhaul. Can you upload a new working version ?

**Comment by DarkShadow44** [comment]
I uploaded a new release at https://github.com/DarkShadow44/HungerOverhaul/releases

**Comment by DarkShadow44** [comment]
While I'm at it, I found another bug with HungerOverhaul, fixed in 1.0.2 on my fork.
