### ISSUE TITLE
bee breeding quest 1116 retrieval issue

### ISSUE THREAD

**Issue by Argail** [GTNewHorizons/NewHorizons#2306]
Which modpack version are you using?

2.0.2.4
If in multiplayer; On which server does this happen?

private server updated with above version
What did you try to do, and what did you expect to happen?

Tried to go through the new bee breeding quest. part 2 this time :-D
Same problem as last time, this time with cultivated bees. quest 1116

What happend instead? (Attach screenshots if needed)

Was the same problem as with the common bees. This time, the cultivated ones in step 2 need to be fixed :-)
Thanks

**Comment by Dream-Master** [comment]
Ok will check
