### ISSUE TITLE
Cetan Boosted Diesel

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2307]
#### Which modpack version are you using?
2.0.2.4
#
#### If in multiplayer; On which server does this happen? 
MyFTB but it is a recipe issue, not server side

###Issue
Man kann cetan boosted diesel komplett in lv und ohne großen aufwand herstellen, da man es auch über glyceryl Trinitrat herstellen kann, welches wiederum in nur einem schritt herstellbar ist mit sehr geringem aufwand (lediglich carbon dust, nitrogen, water, benötig. 

#### What do you suggest instead/what changes do you propose?
Ich wuerde wie mit dir besprochen das Rezept mit dem carbon dust etc entfernen, da dies zu einfach fuer solch eine gute energieversorgung ist

**Comment by Dream-Master** [comment]
Translation:
Cetan bosted diesel can be made in lv very easy (Glyceryl Trinitrate (Coal/oxy and water))

suggestion: remove this recipe

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/29e379a788d211304d7c3d741db5f24f1ab2ca9a

**Comment by Hakameda** [comment]
yes remove this
