### ISSUE TITLE
Flint axe too fast

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#2308]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Used both iron axe and flint axe, expected the iron axe to be faster.
#
#### What happend instead? (Attach screenshots if needed)
flint axe was faster
#
#### What do you suggest instead/what changes do you propose?
I suggest making the flint axe slower, to balance it. Compared to all other flint tools, it's way to fast.

**Comment by Dream-Master** [comment]
What flint axe ? The GT one ?

**Comment by DarkShadow44** [comment]
Yes, the first axe you can make, the flint axe from gregtech. It seems way too OP.

**Comment by Dream-Master** [comment]
too op compared with tico Iron axe ?

**Comment by Dream-Master** [comment]
Flint tool speed is set to 2.5F

**Comment by Dream-Master** [comment]
GT iron have 6f

**Comment by DarkShadow44** [comment]
I have compared flint tool gregtech axe with vanilla iron axe. Also, gregtech flint axe speed is 5.0.

**Comment by Dream-Master** [comment]
Copare it against tico tools you cant build a vanilla iron pick that early.

**Comment by DarkShadow44** [comment]
Yeah, and that's why I expected the later tool to be better, but it's worse.

**Comment by Dream-Master** [comment]
yes but if you in iron tier you have a super fast tico tool already. I never use a vanilla axe so i dont understand the issue here.

**Comment by DarkShadow44** [comment]
Well I see, I didn't test that. What's the name in NEI? I just figured the flint axe was too fast for the first tool I got.

**Comment by Dream-Master** [comment]
craft a flint pick and you need to level it over time. Upgrade it to iron/bronze/steel. They get so super fast.

Did you play gtnh or just start?

**Comment by DarkShadow44** [comment]
I started recently playing gtnh, I'm still in the early stages. Currently only have flint tools

**Comment by Dream-Master** [comment]
Then play a bit more and you see that didnt need to changed.

**Comment by DarkShadow44** [comment]
Yeah I see what you mean, sorry for the misunderstanding.

**Comment by Dream-Master** [comment]
np
