### ISSUE TITLE
Mob kills Chat spawn

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#231]
Its caused by Cofh core interfering with Thaumcraft Champion system so please disable it in the config. It even logs any kind of automatic mob farm so will be very annoying for the entire server.
its disabled in the configs/cofh/core/common

    # Set to true to display death messages for any named entity.
    B:EnableGenericDeathMessage=false

**Comment by Dream-Master** [comment]
Updated in th next release

**Comment by Dream-Master** [comment]
done
