### ISSUE TITLE
QuantumSuit Body Armor construction data missing strings

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#2310]
#### Which modpack version are you using?
2.0.2.5

#
#### What did you try to do, and what did you expect to happen?
I scanned the Quantum chestpiece parts to get the construction data booklet for it. It tells me Input Bus 4: 6 4x %material Wire and Input Bus 8: 4 %material Screw for those two buses so I have no idea what I'm supposed to use to craft it.

#
#### What happend instead? (Attach screenshots if needed)
![2017-12-23_17 15 54](https://user-images.githubusercontent.com/720212/34323005-0252a962-e805-11e7-8fbc-6aed5d8b5933.png)

#

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34323081-bb64bd3a-e839-11e7-807c-d94a574d5bf0.png)

**Comment by Fapiko** [comment]
Odd, I can't reproduce it in single player but it still happens on my server.

**Comment by Dream-Master** [comment]
@Technus any ide about this issue?

**Comment by Fapiko** [comment]
Hmm, thought it was just a missing localization issue or something, but it won't let me craft it in the assembly line either so I don't know what the deal is.

**Comment by Technus** [comment]
Serverside localizer is dead i assume, there was a problem like this some time ago

**Comment by Dream-Master** [comment]
Will see if this is gone after update.
