### ISSUE TITLE
Quest Change Tool Forge

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2314]
Due to the tool forge being gated behind alumite now this quest should be gated behind the blast off quest, as that is when you can make alumite, not in MV where it is currently.

**Comment by Bryfer** [comment]
Which version are you currently looking at?

picture from #spoilers in discord
https://cdn.discordapp.com/attachments/295669878222880769/393052033495728140/unknown.png

**Comment by Anarack** [comment]
Ah never mind close this, forgot to update questbook. was on 2.0.2.5.
