### ISSUE TITLE
Cannot craft Thauminite Wand Caps (Thaumic Bases)

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2318]
Ver 2.0.1.3

In Thaumonomicon (The book), page Thaumic Bases there is a recipe for Thauminite Wand Caps.

But it is not craftable.

**Comment by Dream-Master** [comment]
Mod not nerfed yet.

**Comment by Dream-Master** [comment]
#728, #2095, #1277, #939, #733
