### ISSUE TITLE
Broken Molecular Transformer.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2319]
2.0.2.5

Molecular Transformer don't working.
Cable not connected.
I tryed connect to gt-transformer - no result.

![image](https://user-images.githubusercontent.com/29812448/34381922-54721322-eb57-11e7-9430-5eabd8d4494f.png)

![image](https://user-images.githubusercontent.com/29812448/34381937-6a3f5c00-eb57-11e7-99b7-5de62edb2cfb.png)

**Comment by Dream-Master** [comment]
try to use a wirecutter.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34382134-270e25c8-eb0d-11e7-8602-3c842aafcc41.png)

works well

**Comment by Proha5** [comment]
ok
