### ISSUE TITLE
Cannot perform Bottomless Pouch infusion

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#2323]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Happens both on my private server and in single player.
#
#### What did you try to do, and what did you expect to happen?
I tried to do the Bottomless Pouch infusion.
#
#### What happend instead? (Attach screenshots if needed)
The infusion never starts after right clicking the matrix with a wand. I have triple checked all ingredients are as they appear in NEI & the Thaumonomicon.
![2017-12-28_10 57 45](https://user-images.githubusercontent.com/720212/34415731-4ada245a-ebbe-11e7-8d40-c85cc2ea79d5.png)

![2017-12-28_10 57 40](https://user-images.githubusercontent.com/720212/34415736-4fc09a9e-ebbe-11e7-8acd-40b378457ae9.png)

**Comment by Karl-Markkus** [comment]
Does the NEI and Thaumonomicon GUI switch item-places in the setup? or the required ingredients stay put in the GUI? If they do not stay put, then I have no idea what's the problem. If they do stay put in their positions in the GUI, then place them accordingly.

**Comment by Fapiko** [comment]
Are you saying their order on the pedestals matters? I've never heard of that and it really shouldn't matter as you can have an arbitrary number of pedestals at a given altar...

**Comment by Dream-Master** [comment]
Will check it.

**Comment by benstuwie** [comment]
I had the same problem making one of those, as did someone else on the same server as me

**Comment by Dream-Master** [comment]
Maybe nbt tag

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34467611-d95dd06a-eef6-11e7-8b6e-687507e319cd.png)
![image](https://user-images.githubusercontent.com/2970688/34467618-481430e4-eef7-11e7-8bbf-a8a0586a57a8.png)
works
