### ISSUE TITLE
Cant make witches oven for a quest because ''block of steel fence'' cant be made or found in NEI

### ISSUE THREAD

**Issue by HaiderDK** [GTNewHorizons/NewHorizons#2327]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Trying to make the witches oven for the quest ''Brewers start'' you can find it under alternativ magics.
I got the recipe and the items for it, i just need ''block of steel fence'' but i cant find it under NEI.
#
#### What happend instead? (Attach screenshots if needed)
Cant find the recipe or the item ''block of steel fence'' in NEI.
#
#### What do you suggest instead/what changes do you propose?
add a recipe for ''block of steel fence''
![unknown](https://user-images.githubusercontent.com/34953835/34451295-0face362-ed22-11e7-87aa-8b18c186b93f.png)

**Comment by Technus** [comment]
isnt that just weirdly named IC2 fence? or Railcraft fence?

**Comment by mitchej123** [comment]
It's the extra utilities microblock crafting fence - Some cut up blocks of steel.

**Comment by Dream-Master** [comment]
Yes only one Fence is enabled the other are hidden because nei is allready very slow.  @HaiderDK 
I will show you the recipes.

**Comment by Dream-Master** [comment]
type in Block fence und you can found recipes @HaiderDK 
![image](https://user-images.githubusercontent.com/2970688/34453249-634e0636-ed4f-11e7-9d81-73c9c13cfbdd.png)

**Comment by Anarack** [comment]
Can't we just use the iron fence from ic2 instead of this, so the player does not have to deal with random micro blocks that can't be used for anything else?

**Comment by Dream-Master** [comment]
Yes i could change this.
