### ISSUE TITLE
Trinium Duplication

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#2328]
#### Which modpack version are you using?
2.0.2.5

Looking through NEI there is a recipe for turning one Trinium dust into one Refined Trinium dust with the mixer:
![2017-12-30_13 11 32](https://user-images.githubusercontent.com/720212/34456402-1450c10e-ed63-11e7-8845-1bf08db352db.png)

One Refined Trinium Dust can then be turned into one Trinium Dust and a Tiny Trinium Dust in the Centrifuge, netting a gain of one tiny:
![2017-12-30_13 13 19](https://user-images.githubusercontent.com/720212/34456406-3752f47e-ed63-11e7-93c5-93888821a9e3.png)

Centrifuge recipe could be changed to only give the Trinium Dust without the tiny.

**Comment by Dream-Master** [comment]
Its a GT++ item please report it on GT++ side @Fapiko

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues

**Comment by Dream-Master** [comment]
Nothing i can do here.

**Comment by draknyte1** [comment]
Why does centrifuging refined give normal trinium?
You process it to get it refined..
