### ISSUE TITLE
making bronze in a steam alloy smelter is too inefficient

### ISSUE THREAD

**Issue by Blinzer** [GTNewHorizons/NewHorizons#2329]
#### Which modpack version are you using?

2.0.1.3

#
#### If in multiplayer; On which server does this happen? 
all
#
#### What did you try to do, and what did you expect to happen?

i expected bronze to be more efficient to make using my steam technology than by grinding my tin/copper into dust and crafting it
#
#### What happend instead? (Attach screenshots if needed)

it's totally not, the one extra +1 bronze per 3 copper and 1 tin is nowhere close to worth the amount of steam and time i need to power the machine with
#
#### What do you suggest instead/what changes do you propose?

reduce the amount of steam required to make bronze using the alloy smelter

**Comment by Bluebine** [comment]
It's fine IMHO. Especially when you move onto an electric alloy smelter, you can make bronze a lot easier this way. It's basically a tradeoff-you spend some of your steam on processing bronze more efficiently.

**Comment by Blinzer** [comment]
"more efficiently" is incorrect. it's not more efficient.

**Comment by Bluebine** [comment]
Yes it is, you get 3 bronze from 3 copper and 1 tin using dust, while you get 4 bronze from 3 copper and 1 tin in the alloy smelter.

**Comment by Blinzer** [comment]
in a world where 1 ore vein is 1000 ores, it is not more efficient since you're not pressed for resources. it's just a waste of coal to produce that amount of steam, and a much higher waste of time since grinding it into dust and smelting is way faster.

**Comment by Bluebine** [comment]
the thing is, it's a tradeoff. you use more coal and water in exchange for using less copper and tin. You avoid having to mine more copper and tin, too. It's really just a matter of what you want to do- do it by hand if you want, or do it in the alloy smelter if you want.

**Comment by Blinzer** [comment]
the tradeoff is inefficient. "making bronze in a steam alloy smelter is too inefficient" is the title of the topic.

**Comment by alphaNOVAircraft** [comment]
it is normal in gt, steam machines are crude basic machines, you are a bit more efficient but before you reach LV it shouldnt be really efficient, in gregtech it forces you to higher tiers, you dont need to accept that trade, but there is not a real reason to change that recipe.

**Comment by Blinzer** [comment]
there is, because anybody would find themselves saying "i'd rather it only give me 3 bronze but be able to be powered by a single coal boiler" than what you're suggesting. anybody except you, apparently.

**Comment by benstuwie** [comment]
No, that's just how the mod works. Later on you have to make tons of parts, like rods, gears, screws. Each takes time, but you can also make them with tools instantly for a higher material cost. However, you don't see people hammering neutronium into plates, or filing osmiridium into rods, because it's a waste.

**Comment by Blinzer** [comment]
first of all, that's completely irrelevant as those machines to make those parts take much less time and resources to fuel. second, "that's just how the mod works" is false. every tier of machinery increases the efficiency of doing these operations with machinery from the last, while steam decreases the efficiency greatly of this particular operation. i've already provided the reasons above, and i can crunch all of the numbers of how long it takes to mine copper ore and tin, the amount of time each steam operation takes, the net fuel of steam vs smelting, and the time it takes to craft and smelt vs the amount of time it takes to use steam for this operation. they are all in my favor, which leads me to believe you are not well informed.

**Comment by Anarack** [comment]
Going up in tier usually improves material efficiency in gregtech, not power efficiency, they are two different measurements that it depends on the person what one maters more to there view point and resources at hand. 
Also material efficiency use to be much more important when using the alloy smelter saved you 25% on making the bronze blast furnace, now that we use the bricked one that is less important. For how little copper/tin you need in the bronze age now I sometimes don't bother using it for bronze.

**Comment by benstuwie** [comment]
For the most part, until you hit much higher tiers, power is infinite and self producing, while ores/materials are not. You aren't going to be passively generating tin/copper until you get into bees/crops, which is a ways away. However, you can easily automate power production at that time by using wood farms/coke ovens, or just doing it by hand but quickly with the charcoal pit, and wood from a wood farm. A huge part of this pack is certainly sacrificing time for more efficiency on materials. Lathes over files, benders over hammers. Steam machines arent good, that's the point. If you don't think it's worth it, then don't make it, but the way I see it, it's fair.

**Comment by alphaNOVAircraft** [comment]
well dont think you are right, greg tech isnt increasing efficiency at hier tiers, a mv machine uses twice the energy amount for an lv recipe then if you do it in lv, the only benefit is that the time needed is halfed. The most efficient tier is always the lowest voltage needed for a recipe, for each tier above the needed voltage, you will doulbe up the total energy usage, and quarduple the energy drain per tick, so you get half the time at half the efficiency.

**Comment by benstuwie** [comment]
That's not what I meant. I mean as you go up in the tiers you get more efficient options, like using machines instead of hand tools, or getting a PA for an easier way to automate tons of machines.

**Comment by Dream-Master** [comment]
Ok i close this now.
