### ISSUE TITLE
Clay dust recipes

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2330]
Es gibt mehere möglichkeiten clay dust herzustellen,
1. Clay mit mortar im craftingfeld = 1 small pile of clay dust
2. Clay zuerst mit water bucket zu clay block craften, dann mortar / macerator = 1 clay dust = 4 small piles
  => ein small pile pro clay
3. Clay mit Brick Form im Crafting feld = unfired clay bricks (Verhältiss 1 zu 1)
   1 unfired clay brick in den macerator = 2! small piles of clay dust

In Rezept 1 und 2 bekommt man pro clay 1 small pile ( auch in eigentlich allen anderen rezepten)
wohingegen man in Rezept 3 für 1 clay 2 small piles bekommt, obwohl hierfür der einzige mehraufwand ist, dass man den clay zusammen mit der holz form "brick" ins crafting grid packt, welche ja nichteinmal verbraucht wird. Auch braucht dieses rezept im macerator nicht länger.

Fix: Rezept mit 1unfired clay brick = 2 small piles of clay duust ändern, damit auch hier pro clay nur ein small pile rauskommt, also einfach nur das produkt halbieren

**Comment by Dream-Master** [comment]
Issues solved.
