### ISSUE TITLE
Field Generator have different recipes

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#2332]
#### Which modpack version are you using?
2.0.2.5
#
#### What did you try to do, and what did you expect to happen?
I noticed that Field Generator have different recipes in crafting table and component maker
in component maker it need LV circuit but in crafting table it need HV circuit

#
#### What happend instead? (Attach screenshots if needed)
![20180101140459](https://user-images.githubusercontent.com/25171639/34465899-4b0e1340-eefd-11e7-8aac-49339e9392b1.png)
![20180101140550](https://user-images.githubusercontent.com/25171639/34465905-5f557186-eefd-11e7-8155-763299444b1b.png)

#
#### What do you suggest instead/what changes do you propose?
remove or change the Field Generator recipes in Component Maker

**Comment by jiamingc0824** [comment]
What is the component assembler? or what mod its from?

**Comment by Dream-Master** [comment]
GT++

**Comment by Dream-Master** [comment]
Will disable component assembler.

**Comment by Dream-Master** [comment]
And add it to assembler
