### ISSUE TITLE
 Do not connect tin cable

### ISSUE THREAD

**Issue by scarfase** [GTNewHorizons/NewHorizons#2334]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
He turned the steam turbine from the wire to accumulate steam. Then he turned back to the wire and the turbine did not connect to the cable. I removed the cable, installed a new one, and now the cable was not connected with the machines.
![2018-01-01_06 52 22](https://user-images.githubusercontent.com/16818332/34466144-71821d4a-eef4-11e7-99e2-2a63a3a029d3.png)

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by jiamingc0824** [comment]
Right click the cable with a wire cutter to conenct them.

**Comment by Dream-Master** [comment]
cables use wirecutter/pipes wrench to connect.
