### ISSUE TITLE
EnderIO Alloy's

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2336]
2.0.2.5
Many EnderIO Alloy's, that should be EBF only, can be smelted in the railcraft blast furnace or "Advanced Coke Oven". In addition in some cases the recipe appears multiple times in this recipe list.

**Comment by Dream-Master** [comment]
I remove them from the Advanced Coke Oven. Can you show me the other issue. @Anarack

**Comment by Anarack** [comment]
![2018-01-01_11 17 58](https://user-images.githubusercontent.com/20565115/34469481-89645838-eee5-11e7-9d9a-cafae8ed8ebc.png)
Redstone Alloy, electrical steel, Soularium, is still in there. Might be gt++ adding it as there are gt++ and regular gt dusts in there.

**Comment by Dream-Master** [comment]
i disable it.

**Comment by Dream-Master** [comment]
in 2.0.2.6 i take it out.
