### ISSUE TITLE
Cells produced from nothing when placing rutile into chemical reactor

### ISSUE THREAD

**Issue by anyname2** [GTNewHorizons/NewHorizons#2339]
#### Which modpack version are you using?
2.0.2.5

#
#### If in multiplayer; On which server does this happen? 
Private Server

#
#### What did you try to do, and what did you expect to happen?
Make Titaniumtetrachloride in Chemical Reactor by placing Rutile Dust with Chlorine.

#
#### What happend instead? (Attach screenshots if needed)
In addition to Rutile, two Carbon Monoxide cells were created

#
#### What do you suggest instead/what changes do you propose?
Recipe should also require 2 empty cells

**Comment by Dream-Master** [comment]
Ok will check.

**Comment by Dream-Master** [comment]
Seems to be Carbon cells are missing. The recipe is screwed up in some way

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34471300-bbbd87d6-ef45-11e7-8b44-391bf9b9f730.png)
![image](https://user-images.githubusercontent.com/2970688/34471301-c50c06be-ef45-11e7-8b61-cdb823fba2c5.png)
