### ISSUE TITLE
Alveary quest requite wrong amount of casings

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2340]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Alveary quest require same amount of casings as the scented panelings. Should require just 27 casings instead.

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Yea you right will fix this.
