### ISSUE TITLE
Frequency Module isn't craftable anymore

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#2342]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I tried to craft the Frequency Module
#
#### What happend instead? (Attach screenshots if needed)
It is not craftable with the NEI recipe, something seems to be broken. I have tried with both charged and empty batteries.

![2018-01-01_18 21 51](https://user-images.githubusercontent.com/720212/34471830-c4e6b69a-ef20-11e7-933c-0ac36af4e523.png)
![2018-01-01_18 23 43](https://user-images.githubusercontent.com/720212/34471837-ec5d53d2-ef20-11e7-8355-3f10482a2cc5.png)
![2018-01-01_18 24 04](https://user-images.githubusercontent.com/720212/34471840-f59e0162-ef20-11e7-86a0-70213596edda.png)

**Comment by Dream-Master** [comment]
Need to check
