### ISSUE TITLE
ender pearl quest too expensive?

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2343]
there is a quest on the "to grind or not to grind page" that is required to unlock the end quest, the quest itself requires 32 ender pearls to be turned in though and has almost no real benefit other than  a single lootbag. i have completed it so it doesnt matter anymore, but now ive used up all my pearls and need to farm more before bein able to make eyes to actually reach the end. i recommend removin the need to turn them in or add a big reward for gettin 32 pearls pre-end. prefer the first solution

**Comment by Dream-Master** [comment]
You need now 16 Pearls not consum able.
