### ISSUE TITLE
Crashes when using Osmotic Enchanter from Thaumic Tinkerer.

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2345]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
Start of the enchant
#
#### What happend instead? (Attach screenshots if needed)
[crash-2018-01-02_17.33.10-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1597812/crash-2018-01-02_17.33.10-server.txt)

#

**Comment by CalterOK** [comment]
after removing the mod fastcraft error has disappeared

**Comment by Dacryphile** [comment]
I get this as well, even after disabling fastcraft.  The enchant starts going for a bit, but about halfway through it crashes.  Happened multiple times on both my regular world and a test world I created.  
[crash-2018-01-21_12.10.05-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1650088/crash-2018-01-21_12.10.05-server.txt)
[crash-2018-01-21_12.10.18-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1650089/crash-2018-01-21_12.10.18-client.txt)

**Comment by Dacryphile** [comment]
It appears I can get around it by putting the osmotic enchanter in the spectre dim without any chunkloaders running in other dims

**Comment by Dream-Master** [comment]
Nice info

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2345
