### ISSUE TITLE
Railcraft Energy Loaders way too expensive

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2347]
#### Which modpack version are you using?
2.0.2.5

So this is how Electric Locomotives are gated, MV parts needed (which is fine):
![2018-01-02_17 38 17](https://user-images.githubusercontent.com/16925725/34492696-1c01726c-efe9-11e7-8c01-3a960f2728ce.png)

Now to load these or the batbox / CESU / MFE cart you need the Energy Loaders which for some reasons are gated with Lapotron Crystals making them EV (for pretty much no reason?):
![2018-01-02_17 39 07](https://user-images.githubusercontent.com/16925725/34492766-64dbc55a-efe9-11e7-8eaf-55e6d2d41dc5.png)
![2018-01-02_17 39 23](https://user-images.githubusercontent.com/16925725/34492770-67de2478-efe9-11e7-9069-40a5f2b7ea35.png)

**I would suggest also making them MV by replacing the Lapotron Crystal with an Advanced RE-Battery:**
![2018-01-02_17 41 55](https://user-images.githubusercontent.com/16925725/34492902-c9a10720-efe9-11e7-9751-a75fff291015.png)

This would make much more sense but keep in mind that the upgrades to transfer power quicker would still need higher tier stuff than MV which means it can still get faster.
When it is gated with EV items I can't see why you would still run a batbox cart or something. (And no refilling by hand is not really an option since you would rather use a steam locomotive since automated is always better).

So yeah the idea is:
LV -> steam locomotives
MV -> electric locomotives + charging them
higher tiers -> charging gets faster + unlocking MFE cart at HV

**Comment by Dream-Master** [comment]
Will look into it.
