### ISSUE TITLE
[suggestion] force track emitter recipe

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2349]
#### Which modpack version are you using?
2.0.2.5

Currently the force track emitter is really expensive even if it's just a fancy way to make a bridge. It will save you some rails but needs power to run, so that's already a trade off and I think nobody would use it for efficiency as setting up power for it would be kind of a waste.
![force_track_emitter](https://user-images.githubusercontent.com/16925725/34500490-39fc38fc-f00b-11e7-8aa6-d648489d1706.PNG)

It does however look nice and I think it could be moved to HV so you unlock it one tier after the electrical locomotives. Here is a recipe that would be enough for this block imo:
![force_track_emitter](https://user-images.githubusercontent.com/16925725/34500383-cb8fcbc2-f00a-11e7-8729-c156305428d4.PNG)

Obviously any HV-tier circuit could be used.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34501796-ca70ec52-f010-11e7-8b4c-4f3353ccb29f.png)
