### ISSUE TITLE
Ordo/Perditio Vein

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#235]
Found 3 of them so they do spawn, the problem is that perditio doesnt seem to spawn in the vein.
http://imgur.com/Lu224nT,W1qTOOg

@Namikon Please correct me if you have found any of the veins in the new TF generation and if they spawn properly

**Comment by Namikon** [comment]
I will check my waipoints in the TF. I found a most veins, but i'm not 100% sure about perditio. Reporting back in ~1 hour

**Comment by Namikon** [comment]
Update: Sadly, my old waypoint for perditio/ordo is invalid, due world reset of the TF. So I don't have one at the moment, so for the initial question: No I have not found any perditio/ordo veins since the last reset

**Comment by Dream-Master** [comment]
I will check the config file (Witch id have perditio?)

**Comment by Dream-Master** [comment]
Found some.

Change the high in cfg file.

Nedd to be tested.

**Comment by Dream-Master** [comment]
fixed i think
