### ISSUE TITLE
thaumcraft research points loss

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2350]
so i was talkin about that on the server a while ago: i had a crapton of research points for thaumcraft (the ones you get from scanning items) but a while ago this reset and i was at 10 for the primal ones again and everything else was gone. scanned a few things to get stuff again and cheated in a lot of points again, but now i have a lot of items with ??? aspects. is there any way to completely reset this or another fix?

**Comment by Dream-Master** [comment]
Maybe your save file are corrupted. Normaly Thaumcraft points not get lost.

**Comment by Dream-Master** [comment]
? Means you don't know the researches. Guess a thaumcraft save files was reseted in you case. Was it on the server?

**Comment by Shattered2909** [comment]
i do have all research in the book, just when i hold shift on items i do know their aspects but many are ? while i can still use most stuff.

**Comment by Shattered2909** [comment]
playing singleplayer

**Comment by Dream-Master** [comment]
Make backups from your sp game every few hourse. I do the same. Nothing i can do here.

**Comment by Shattered2909** [comment]
well it happened days ago and doesnt influence me too much

**Comment by Dream-Master** [comment]
ok then we close this issue ? @Shattered2909

**Comment by Shattered2909** [comment]
i would say yes, but where can i find thaumcraft commands? maybe i can deal with it myself

**Comment by Namikon** [comment]
http://thaumcraft-4.wikia.com/wiki/Commands
