### ISSUE TITLE
QuestBook wrongly assumes steel pickaxe can mine obsidian

### ISSUE THREAD

**Issue by Andrey-Sisoyev** [GTNewHorizons/NewHorizons#2352]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
QuestBook: Tier 1: quest "Upgrade of the upgrade of the...": "...Unlock redstone and obsidian for your different tools." 
Subsequent quests also assume I can have obsidian, e.g., quest "Reinforced X? Unbreakable": "with your steel tools you are able to mine obsidian..."
Expected steel pickaxe to have mining level "5-Obsidian".
#
#### What happend instead? (Attach screenshots if needed)
Steel pickaxe has mining level "4-Redstone" - both upgraded pickaxe and brand new steel pickaxe. 
Screenshot: https://imgur.com/a/NFURB
It's not clear how to mine obsidian now.

#
#### What do you suggest instead/what changes do you propose?
Either set steel pickaxe mining level to "5-Obsidian", or change quests. 
Currently it's not clear how to mine obsidian.

**Comment by Dream-Master** [comment]
You need to level Pickaxe to obsidian level first. Start with redstone level.
Pro tip. Put a Emerald on it. If some is allready add take it on top. Works 100% :)

**Comment by Dream-Master** [comment]
I can change the text.

**Comment by Andrey-Sisoyev** [comment]
Ok, thanks! :)
Couldn't add another Emerald on top of existing Emerald upgrade.
My pickaxe mining XP is 438/1326. I guess it's not that hard to level up it again.

**Comment by Andrey-Sisoyev** [comment]
Level up mining level worked! It's now obsidian level.

**Comment by Dream-Master** [comment]
cool.
