### ISSUE TITLE
Crash-Report while exploring World

### ISSUE THREAD

**Issue by TheRealHypo** [GTNewHorizons/NewHorizons#2354]
#### Which modpack version are you using?
2.0.2.5

#
#### If in multiplayer; On which server does this happen? 
Private Server, only using the standard server package + Better Records

#
#### What did you try to do, and what did you expect to happen?
One of my players explored the world, and the game unexpectadly crashed.

Crash Log is attached. 
[crash-2018-01-04_01.52.00-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1602157/crash-2018-01-04_01.52.00-server.txt)

#
#### What happend instead? (Attach screenshots if needed)
Nothing.

**Comment by Dream-Master** [comment]
We have this crash from time to time. So far I remember chunk corruption /resets was the result. Nothing I can do here realy.
