### ISSUE TITLE
Be(e) Breeding Quests Not Submitable

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2355]
Stonelegion - GTNH 2.0.2.5

Bee quests are not submitable. When I have the cultivate princess and drone in my inventory, clicking claim doesn't not happen anything.

![](https://cdn.discordapp.com/attachments/265023943927267330/398333561377390593/unknown.png)
![](https://cdn.discordapp.com/attachments/265023943927267330/398333598064836608/unknown.png)
![](https://cdn.discordapp.com/attachments/265023943927267330/398333642390110210/unknown.png)
![](https://cdn.discordapp.com/attachments/265023943927267330/398333670701924353/unknown.png)

**Comment by Wolozo7** [comment]
Do you have a Beealyzer? Those bees are probably not purebred cultivated.

**Comment by Gateswong** [comment]
They are purebred cultivated. This one is already in automated breeding system.

**Comment by Gateswong** [comment]
The same as the drones.

![](https://cdn.discordapp.com/attachments/265023943927267330/398401442576072704/unknown.png)
![](https://cdn.discordapp.com/attachments/265023943927267330/398401536398721026/unknown.png)

**Comment by ZorbaHerbalist** [comment]
Have the same issue. After manual pushing (/bq_admin) next quest (noble etc.) detects bees. Only this one detection is broken.

**Comment by Wolozo7** [comment]
Are you playing singleplayer? I think that quest was broken when introduced in 2.5, but relatively quickly fixed.

**Comment by ZorbaHerbalist** [comment]
@Wolozo7 I'm playing on my private server.

Fixed in which version? 2.5 is last version AFAIK. Was there a re-release of 2.5?

**Comment by Wolozo7** [comment]
It's fixed in dev and on the official servers, sry.

![image](https://user-images.githubusercontent.com/34921674/34557301-1e83459a-f13a-11e7-8ea2-4ba0b3dabd9b.png)

**Comment by Dream-Master** [comment]
Yes it is fixed in 2.0.2.6 which will be out very soon.
