### ISSUE TITLE
In NEI recipe, Irradiated Comb centrifuge and produce nothing.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2356]
Ver. 2.0.2.5

**Comment by Dream-Master** [comment]
Did the comb produced by any bee or just a unobtainable comb ? @Gateswong

**Comment by Gateswong** [comment]
Vindictive, Vengeful, Avenging

**Comment by Dream-Master** [comment]
https://ftbwiki.org/Irradiated_Comb

**Comment by Dream-Master** [comment]
Will try to add a recipes for it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34562807-4b8e5046-f150-11e7-8261-c03e7153a8bd.png)
I fixing it gt side

**Comment by Dream-Master** [comment]
removed Forestry recipe in forestry centrifuge.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/36b8d68b5886337041273b5bbf277c5c97cc0cef
