### ISSUE TITLE
Printing Press Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2358]
Add a Printing Press Quest.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57187810-5b862080-6eba-11e9-971e-5b4dd3c7bbfe.png)

![image](https://user-images.githubusercontent.com/1214811/57187812-60e36b00-6eba-11e9-9a13-c593b0616994.png)
