### ISSUE TITLE
Naquadah alloy creation

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2359]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Trying to make naqadah alloy in mixer
#
#### What happend instead? (Attach screenshots if needed)
Trinium from recipe turns into GT++ shit

Suggestion: Remove GT++ from pack.

![2018-01-04_16 33 27](https://user-images.githubusercontent.com/25028786/34565802-48e57352-f16d-11e7-9e02-79cc378d59bb.png)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2328

**Comment by Dream-Master** [comment]
@Cinobi please report on GT++ side not here. I make no sense to report it here.
