### ISSUE TITLE
Lag spikes, 22.06.2015

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#236]
I'm alone on the server, and every 15-30 seconds, there is a massive lag-spike for about 5 seconds. And I had 2 timeouts already

**Comment by Dream-Master** [comment]
I restart the Server and hope the lag is gone.

**Comment by Dream-Master** [comment]
No Translocator for the moment please and i disabled the residual heat in RC.

**Comment by Namikon** [comment]
Problem is back, it is impossible to do anything

**Comment by Teteros** [comment]
Propably ran out of memory again.

**Comment by Dream-Master** [comment]
I will downgrade coro util i think this will fix the problem. Update after server restart

**Comment by Dream-Master** [comment]
I think it is fixed. Downgrade coro util

**Comment by Teteros** [comment]
Unfortunately it's back. (if it was gone to begin with).
Server is kicking/timing out players all day today.

**Comment by Drobac** [comment]
Was running smoothly when i logged in, went to mine on venus and the situation started going worse by the minute

**Comment by Dream-Master** [comment]
kill Special ai

**Comment by Namikon** [comment]
And we'll switch to Cauldron by the end of this week. I'm currently running multiple tests for stability and performance, but it looks pretty good so far. Currently scheduled: Friday 3rd July
