### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by jiamingc0824** [GTNewHorizons/NewHorizons#2360]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I clicked on the crafting status hammer in the AE UI and crashed the server.
#
#### What happend instead? (Attach screenshots if needed)
-
#
#### What do you suggest instead/what changes do you propose?
Fix it? Or announcement until it is fixed?

**Comment by Dream-Master** [comment]
What time/timzone you crash the sever? I will take a log into the log then @jiamingc0824

**Comment by benstuwie** [comment]
Were you in a void world? Because that's something that's been happening for a while

**Comment by Namikon** [comment]
https://transfer.sh/lbYNy/crash-2018-01-04_18.30.29-server.txt

**Comment by Dream-Master** [comment]
@jiamingc0824 did you have more infos? Can we close it ?

**Comment by jiamingc0824** [comment]
The only info i have is the server crashed when i click on the crafting status button in the AE terminal. 
Another info is the crash log that Namikon included. It probably have smth to do with the void dimension as i've heard from other player.

**Comment by Dream-Master** [comment]
I will ask @bartimaeausnek

**Comment by LOKKO12** [comment]
@Dream-Master I think it might be an issure with AE2. Can't recreate in SP.

**Comment by jiamingc0824** [comment]
@LOKKO12 even in void world?

**Comment by LOKKO12** [comment]
yupp @jiamingc0824

**Comment by LOKKO12** [comment]
@jiamingc0824 please report this issure here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues

**Comment by Dream-Master** [comment]
Not fully fixed but not crash anymore.
Thanks @LOKKO12
