### ISSUE TITLE
2.0.1.3 server random crash

### ISSUE THREAD

**Issue by jujuztune** [GTNewHorizons/NewHorizons#2361]
#### Which modpack version are you using?

we use 2.0.1.3

#### If in multiplayer; On which server does this happen? 

On private server.

#### What did you try to do, and what did you expect to happen?

The server crash at a random but always faster rate. i read the logs and don't find any error related to the crash.

Here's the latest-fml-server log (only last 210 lines): https://pastebin.com/kwS7LCNQ
And the latest.log : https://pastebin.com/jfyLyhZQ

The server have 10 giga of ram, so probably not the problem.

#### What do you suggest instead/what changes do you propose?

Help me to find whats going wrong, please.
(sorry about my probably bad english, not my native language)

**Comment by Namikon** [comment]
Please provide the latest crashlog file inside the /crash-logs/ folder

**Comment by jujuztune** [comment]
nothing was created in the "crash-reports" folder (latest crash log is from early december). i don't have any "crash-logs" folder.

**Comment by Namikon** [comment]
You wrote the server crashes at a random rate; If there is a crash within minecraft, caused by a mod, a logfile is written to /crash-reports/ (it's indeed crash-reports, not crash-logs). If there are no files, then the crash is caused by something else, and nothing related to our pack.

The only thing you can do is to monitor the server console to catch any JVM crashes, as they are printed to console.

**Comment by jujuztune** [comment]
So probably better to write to the server hosting company?
If the crash is caused by corrupted chunck, a crash log is created too?
Anyway, thanks you very much for your help, i try to catch that crash.

**Comment by Namikon** [comment]
Yes, even a faulty/corrupt mod will create at least a log entry or crash file.
If Java itself has a problem; Then the only place to grab this error is the console where minecraft is launched from.

**Comment by jujuztune** [comment]
I have only access to a really basic console with only minimal informations. I try to re-install the server tonight to see if it change something.

**Comment by Dream-Master** [comment]
@jujuztune any news here ?

**Comment by jujuztune** [comment]
After reinstall and update to 2.0.2.5, no more crash, do i need to close the issue myself or let someone of the gtnh team do it?
