### ISSUE TITLE
Void metal is not auto craftable if void essence is researched

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2362]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft void metal in thaumatorium
#
#### What happend instead? (Attach screenshots if needed)
Void essence is selected in GUI when I try to select void metal.
(Void metal is the first in the recipe list)

**Comment by repo-alt** [comment]
Additional info: I can select void metal if I remove mnemonic matrix, and click on void essence instead, so perhaps the issue may be renamed to, like "Thaumatorium recipe selection bug"

**Comment by benstuwie** [comment]
I've noticed that. Kinda sucks, but you can just choose the other option for void seeds and it'll give you ingots.

**Comment by Dream-Master** [comment]
A few Pics are nic to see what you mean @repo-alt @benstuwie

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/34586729-4cbbe10c-f1b6-11e7-9105-a470b35858bc.png)
![image](https://user-images.githubusercontent.com/23512002/34586737-55897c2c-f1b6-11e7-98b3-5ae79ab9c9c9.png)
Here, at the top screen if you select void metal, void essence will start crafting

**Comment by Dream-Master** [comment]
I could change the recipe Void essence is using ingots as sourceand get a higher output

**Comment by repo-alt** [comment]
That will work. Actually I had the same issue with tallow, which is resolved now with the soapstone recipe.

**Comment by Dream-Master** [comment]
@repo-alt can you test with bath salt too? Salis Mundus have two recipes also.

**Comment by repo-alt** [comment]
Probably I don't have researched the second recipe, I see only bath salt from salis mundus. What is the second recipe?

**Comment by Dream-Master** [comment]
I dont have my game open but it must be somthing from Thaumic Base or Thaumic Horizons. Will later check.

**Comment by repo-alt** [comment]
Right, it is salis mundus duplication. I have it researched, but thaumatorium does not even see the recipe.

**Comment by Dream-Master** [comment]
No it was a different recipe.

**Comment by Cinobi** [comment]
All Thaumcraft alchemical constucrion recipes that has 2 or more output has this bag. I mean this "switched output selection". Need to report it to thaumcraft creator, i guess.

**Comment by Dream-Master** [comment]
Azanor  not fixing 1.7.10 issue

**Comment by Dream-Master** [comment]
@repo-alt 
![image](https://user-images.githubusercontent.com/2970688/34611893-b04685da-f227-11e7-9f82-e09311a3d1e6.png)
this recipe

**Comment by repo-alt** [comment]
Golem animation powder is selected correctly. Also various seeds recipes are selected correctly, so this bug us not universal, it looks like recipes in the GUI don't use the same some sorting as they are stored inside, or something like that.

**Comment by Dream-Master** [comment]
ok fine then i not need to change it.
