### ISSUE TITLE
Twilight boss quest suggestions

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/NewHorizons#2363]
Currently the quests requires the player to kill the boss. In some server Twilight Forest probably have limited amount of bosses (espically high tier boss) because of restricted boundary. It's also buggy when generating/expanding Twilight Forest maps. 

So I would suggest make twilight boss quest detect their heads instead of kill, or give a recipe for boss spawner/egg. Otherwise, some late players will not finding one boss, or some guy who kill bosses without quest line have to kill one more boss.

**Comment by Dream-Master** [comment]
I add TF spawn egg quests to the game. Maybe i need to detect the heads there to open it up. You can aktivate his eggs in TF and fight the bosses.
