### ISSUE TITLE
Infinity wires madness

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2364]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Trying to craft 64 infinity wires
#
#### What happend instead? (Attach screenshots if needed)
all fine, except this mad recipe - 2 ingot\1 wire. Whyyy~
![2018-01-05_13 04 12](https://user-images.githubusercontent.com/25028786/34604511-3316d32a-f219-11e7-8dd5-f6f864733ab5.png)
![2018-01-05_13 04 07](https://user-images.githubusercontent.com/25028786/34604512-333ceab0-f219-11e7-8f26-9a108607e884.png)

**Comment by Dream-Master** [comment]
Idk good question
