### ISSUE TITLE
Jade material for GT Tools

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2365]
#### Which modpack version are you using?
Delta
#
#### If in multiplayer; On which server does this happen? 
Delta one
#
#### What did you try to do, and what did you expect to happen?
Trying to craft some GT tools from Jade
#
#### What happend instead? (Attach screenshots if needed)
They has 0 durability.

![2018-01-05_14 02 01](https://user-images.githubusercontent.com/25028786/34606611-231ed56e-f221-11e7-97df-81ea45696b3e.png)
![2018-01-05_14 02 04](https://user-images.githubusercontent.com/25028786/34606612-23407f5c-f221-11e7-9b8b-d232959d9197.png)

**Comment by Dream-Master** [comment]
Some other  materials have 0 durability too

**Comment by Dream-Master** [comment]
I add jade for moon dail only

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34621444-7b8a1196-f249-11e7-95b4-c79d75935daf.png)

**Comment by Dream-Master** [comment]
forgot the recipe to change
