### ISSUE TITLE
crash on multiplayer screen

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2366]
#### Which modpack version are you using?
2.0.2.5

#
#### What did you try to do, and what did you expect to happen?
i refreshed many times multiplayer screen and expected everything to be fine
#
#### What happend instead? (Attach screenshots if needed)
i crashed
[crash report.txt](https://github.com/GTNewHorizons/NewHorizons/files/1606969/crash.report.txt)

**Comment by Namikon** [comment]
That is entirely vanilla Minecraft. Nothing related to GTNH, and nothing that can be fixed by us
