### ISSUE TITLE
Industrial Information Panel quest

### ISSUE THREAD

**Issue by codewarrior0** [GTNewHorizons/NewHorizons#2368]
The Info Panel from Nuclear Control is the only way (aside from the HV-level Tricorder) to view the progress of a multiblock machine. A quest in "Multiblock Goals" that comes after the EBF quest would be a great introduction for new players and a gentle reminder to veterans. It should guide the player to craft the Info Panel, a Panel Extender, and a GregTech Sensor Kit, and then use the Kit on the EBF, install the resulting card in the panel, and enable the panel with a lever.

**Comment by Dream-Master** [comment]
Ok will Add.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/04e1609e77086403868b3795ff580cf93ec6f059

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/5f820885151726de5def08bf9dfd9cfe938fb2ea
