### ISSUE TITLE
Ancient Stone -> Slab

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2369]
This is a minor thing, but it would be nice to be able to cut the Thaumcraft Ancient Stone into Ancient Stone Slabs.

**Comment by Dream-Master** [comment]
Ok will add.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34652067-a60a142a-f3d9-11e7-95a7-df67c72bcd42.png)
![image](https://user-images.githubusercontent.com/2970688/34652069-aac856b6-f3d9-11e7-9f63-1e4312d62576.png)
![image](https://user-images.githubusercontent.com/2970688/34652074-af1ac258-f3d9-11e7-8731-e67001e1461f.png)
