### ISSUE TITLE
UPADTE TODAY 23.06.2015

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#237]
I planing an update today.
This Update will be only available via Technic Launcher because a easier way to updating things (Automatical Download and update)

Link : 
http://www.technicpack.net/modpack/mcnewhorizons.677387
Pack Link:
http://api.technicpack.net/modpack/mcnewhorizons

@Drobac Please pack your Bees because i will reset the nether because of new orespawns.
Are there Buildings on other Dimensions because i will check the Perditio Issue in Twilight Forest.
The Other Planets i will reset too because i will adding new Ore mixes with Nikolite ...

http://forum.gtnewhorizons.com/showthread.php?tid=22

**Comment by Drobac** [comment]
Nether cleared out

**Comment by Dream-Master** [comment]
@Drobac Ok Thanks. Why you not using the Hell biome overrider addon from Gendustry to breed Hell Bees in the overworld?

**Comment by Drobac** [comment]
Couldnt make Ind.apiaries because of the lapis rod things

**Comment by Dream-Master** [comment]
ah ok but this is fixed with the next update

**Comment by Dream-Master** [comment]
So hopfuly tomorrow i am ready for it.

**Comment by Dream-Master** [comment]
Done
