### ISSUE TITLE
Thirsty Tank too cheap

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2370]
The Automagy Thirsty Tank can function as an infinite water source and as an automatic pump (with a range of ~32 blocks?). It is craftable with very basic TC equipment and therefore way stronger than both other infinite water sources in MV and other pumps.

![image](https://user-images.githubusercontent.com/34921674/34640480-aeb3134c-f2f3-11e7-8cd9-a6cd5909b28a.png)

Possible adjustments: 
- Replace the Glass with Fused Quartz (doesn't make it that much harder, but puts it closer to the EnderIO Reservoir)
- Or replace the Water Shard with a pump (either MV or HV)
- Or replace the upper two Arcane Stone Blocks with circuits (MV or HV or EV)

**Comment by Hakameda** [comment]
EIO infinite water is HV tech, Soon as it is possible to make those people bail on thirsty tanks. GT Pumps have a way larger range

**Comment by Fapiko** [comment]
> way stronger than both other infinite water sources in MV and other pumps.
The only thing that might make them more desirable than other pumps is the fact that they don't require power. These need to be touching the fluid to be pumped and have a limited range unlike the other pumps which will go down to bedrock. Every GT pump MV and up also has a much larger radius.

**Comment by benstuwie** [comment]
Yea, but who's pumping things other than oil really. Which has a tiny radium needed. It might not be as good as other options later on. But if I'm in MV and I want power, I'd take the no power needing that block, over needing to make another machine that needs at least 1A LV

**Comment by noobyaran9** [comment]
>Which has a tiny radium needed.

Fapiko mentioned that it has limited range which i assume that it only pump up 1 or 2 layer. This means that u have to move the block down every so often to get the pump going all the time. This is already a huge downside to the block over a single pump. And GT pump doesn't takes alot of power, i've powered my MV pump with a LV generator and the internal power buffer of the pump is constantly staying full (You might be able to power a HV ones with LV gens).

**Comment by mitchej123** [comment]
Pumps sip power.  I had a generator that I used with my pumps and it was fine.  Especially now that they properly handle chunk unload and load they're very useful.  I preferred the mv pump due to the radius compared to lv or thirsty tank.  The main use I have of thirsty tank is for things demanding more water than a tank can make, but less than a reservoir.

**Comment by Fapiko** [comment]
It works for oil but it's really not good at it. You'd need to move it to get it all - and even with a jetpack it's pretty dangerous playing around in oil that early on. As people have mentioned the pumps run for white a while - a battery buffer with 1-4 batteries in will generally last the duration of the well or only need one change.

This shouldn't be balanced as a pump - that's really not what it's good at and the GT options are both easier to use and get for oil. It's a great early-game infinite water source and should be balanced as that.

Personally I'm fine with the fact that the recipe is fairly cheap because the arcane bricks are also crafted with Thaumcraft which is a bit of a pain to deal with in the early game - you have very small vis storage wands meaning you can't mass produce these things. It also requires a bit of investment to do the researches. It's a nice reward for people who have decided to get into TC earlier than required to get a good infinite water source to hold them over until HV comes around, I would strongly argue that this shouldn't be gated behind HV.

**Comment by noobyaran9** [comment]
To be honest, why not just leave the recipe as it is. Its not easy to get into thaumcraft. You need either MV or late LV to get the most basic wand in thaumcraft (unless u found an aluminium ingot somewhere else).

**Comment by benstuwie** [comment]
Is there a way to black list it for oil pumping? I think it's fine as a water source, but kind of unbalanced for getting oil.

**Comment by mitchej123** [comment]
I think it's fine as is.

**Comment by noobyaran9** [comment]
Why would people using it to pump oil when clearly the disadvantage is larger than the advantage. You need to move it everytime it finish 1 or 2 layer and risking yourself drowning in the oil and not get your stuff back. Furthermore, MV pump have larger radius than the thirsty tank itself which can be used with less of a pain and to pump up larger oil well.

**Comment by benstuwie** [comment]
1-2 layers? Isn't it like 32 blocks or something? That 3 moves max per well, and costs no power

**Comment by Dream-Master** [comment]
This mod isn't nerfed. So yes i need to go over all the recipes.

**Comment by Hakameda** [comment]
its fine as is

**Comment by Dream-Master** [comment]
Its not

**Comment by Hakameda** [comment]
Its gated behind MV, Which makes it a nice thing to get until EIO Infinite water. It is def where it should be

**Comment by Dream-Master** [comment]
Yes but the recipe not have the typical GT look. Next things i planing is to nerf all Thaumcraft mods to finih this part.

**Comment by Dream-Master** [comment]
i was to lazy in the past because a lot of work.

**Comment by Hakameda** [comment]
Provided you don't make it worthless, Then people skip it anyway

**Comment by CalterOK** [comment]
A good infinite source of water can be obtained at the beginning of the LP, by automating the source of water from the BuildCraft. Therefore as that to complicate the given variant I do not see sense.

**Comment by Dream-Master** [comment]
Water source from BC was suggested to take off? @CalterOK @WarlordWossman what we have to do?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/993fa1e9ef185422200217cb43231394cdaef213

**Comment by CalterOK** [comment]
@Dream-Master As an option, increase the number of required aspects, which will not affect the value of the reservoir, but will increase the required level of development.

**Comment by richardhendricks** [comment]
@benstuwie The Thirsty Tank can only draw on fluid sources that touch its sides.  So it becomes a real hassle to actually use to drain an oil fountain. I have a bunch, only use them as infinite water sources.  I tried using them to gather oil once, but as Mitch says, it is super-dangerous.

They only provide 1,000 L/s so IMO they are a nice compromise between the water siding tanks and the everful urn/ender IO water tank.

Maybe change the Aqua aspect to 30 so it requires a second tier wand.  Players can use water siding tanks to feed their MV boilers until they kill the lich that way.

**Comment by richardhendricks** [comment]
If you want to up the dev level, you can use the etched arcane bricks that require the MV laser engraver. And to make it more expensive, require 2 MV pumps in the bottom left and bottom right.

Doing this though will push players harder away from steam, which is good/bad depending on your point of view.  I would kinda prefer to leave it alone or minimally adjusted.

**Comment by Scottishprog** [comment]
Second leaving the tank alone.

My LV and MV tiers were heavily steam powered. The siding tanks were.... useless. Something like 12 tanks had real issues keeping up with two 3x3x3 railcraft boilers. Only when I hit early MV, and could get thirsty tanks, was steam power more than minimally practical.

Nerfing this will push post steam age steam into irrelevance.

**Comment by richardhendricks** [comment]
FYI Bart made a new water source, a Stirling engine.  It uses coal and produces water at a pretty good rate. You can even use compressed charcoal to power it for a long long time.
