### ISSUE TITLE
Everburn Urn has been nerfed. Unintentional?

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2372]
#### Which modpack version are you using?
2.0.2.5
#
I've just compared the same setup of node + Everburn Urn in modpack 1.4.1.1 and 2.0.2.5.

In 1.4.1.1 the Urn produces 1B of Lava every 2 seconds.
In 2.0.2.5 the Urn produces 1B of Lava every 10 seconds.

The Urn has been nerfed 5x with no note in changelog or the code you've changed.
Probably and oversight, please revise the code changes you've made.

(Note: used a node with 24 cV of Igni, was fully capable of powering many Urns at max speed so Node production wasn't the issue in my test.)
 
EDIT:
In 1.4.1.1 the Urn would produce 250mB every 10 ticks. Now it produces only 50mB.

public static int CONVERSION_FACTOR=250;
return (int)Math.floor(ignisVis*CONVERSION_FACTOR);

I suppose the Urn only uses 0.2 Vis instead of 1 Vis per 10 ticks due to the code below.

    public void updateEntity() {
        super.updateEntity();
        this.ticks++;
        if(this.ticks==10) {
                if(this.ignisVis<16){
                    ignisVis += VisNetHandler.drainVis(worldObj, xCoord, yCoord, zCoord, Aspect.FIRE, 1);
                    worldObj.markBlockForUpdate(xCoord,yCoord,zCoord);
                }
            ticks=0;
        }
    }

**Comment by Dream-Master** [comment]
So need that to be changed back ? Idk why Crypton Captain chang it ?

**Comment by Dream-Master** [comment]
@Methes

**Comment by Methes** [comment]
You've forked nekosune's version of Thaumic_Exploration so I suppose that's what is used the modpack.
He hasn't changed his version in 3 years.

**Comment by Dream-Master** [comment]
No we using Crypton Captains version because of bug fixes so far i remeber.

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/Thaumic_Exploration

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/Thaumic_Exploration/commit/2d9f4b635d74e22bb5f8060347ce10f476a9aca0#diff-51b469367f4f7ddd30eb98a2a2ffc6f2

**Comment by Dream-Master** [comment]
here was somethings changed

**Comment by Dream-Master** [comment]
From Changelog: Balanced everburn urn a bit better. Interacts correctly with vis relays now

**Comment by Methes** [comment]
Yes. He uses
CONVERSION_FACTOR=10
ignisVis += VisNetHandler.drainVis(this.worldObj, this.xCoord, this.yCoord, this.zCoord, Aspect.FIRE, 5)

So every 10 ticks the Urn draws 5 Vis and therefore produces 50mB.
Not only is it 5x slower, it's also 5x more expensive Vis vise.

**Comment by Dream-Master** [comment]
So what you suggest to change? And why he change it did you see the reason ? @Methes

**Comment by Methes** [comment]
Current uses:
1 Urn used to feed 20 MV Centrifuges. Now it's 4.
4 Urns was enough to power Large Heat Exchanger, now you need 20 with a lot more Vis.

I liked the numbers before thanks to the power production, I might not use it now with these numbers.
I'm biased though so it's not really my call to say how much lava it should produce (as I like to use it for power).

**Comment by Dream-Master** [comment]
So which values i need to change. I dont want to change the whole commit because maybe we lost some fixes. @Methes

**Comment by Methes** [comment]
If you want old values, values below should do it. But remember, 4 Urns with Large Heat Exchanger and Turbine can give you ~6200EU/t so please consider with the Team what is balanced.

    public static int CONVERSION_FACTOR=250;
    
@Override
    public int getCapacity() {
        // TODO Auto-generated method stub
        return 4*CONVERSION_FACTOR;
    }

                    ignisVis += VisNetHandler.drainVis(this.worldObj, this.xCoord, this.yCoord, this.zCoord, Aspect.FIRE, 1);

**Comment by Dream-Master** [comment]
So conversion factor is the time in ticks each cycle needs ?
And what about the aspects change from 5 to 1 ?

**Comment by Methes** [comment]
With my values:
CONVERSION_FACTOR=250
Every 10 ticks, Urn draws 1 Vis from network and converts it to "1*CONVERSION_FACTOR" mB Lava (250).
Max Urn capacity is "4*CONVERSION_FACTOR" (1000)

With current values:
CONVERSION_FACTOR=10
Every 10 ticks, Urn draws 5 Vis from network and converts it to  "5*CONVERSION_FACTOR" mB Lava (50).
Max Urn capacity is "10*CONVERSION_FACTOR" (1000)

**Comment by Dream-Master** [comment]
ok idk if i can rebuild it. Need to test it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Thaumic_Exploration/commit/72b8ead35ccc9d07e02fa4b9cfd85701038b22d2

**Comment by Dream-Master** [comment]
[Thaumic-Exploration-[1.7.10] 1.1.72-0.zip](https://github.com/GTNewHorizons/NewHorizons/files/1609834/Thaumic-Exploration-.1.7.10.1.1.72-0.zip)
