### ISSUE TITLE
When creating watches, electric tools are not used

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2373]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
singl
#

#
#### What happend instead? (Attach screenshots if needed)
![2018-01-07_16 59 31](https://user-images.githubusercontent.com/35035276/34650160-451406d2-f3cd-11e7-9045-c707413ffe31.png)
![2018-01-07_16 59 38](https://user-images.githubusercontent.com/35035276/34650161-455f9dc2-f3cd-11e7-86a5-402ccfe0525b.png)

#
#### What do you suggest instead/what changes do you propose?
Add their use

**Comment by Dream-Master** [comment]
Need to test it.
