### ISSUE TITLE
Quest 653 not requiring the same items as recipe in NEI.

### ISSUE THREAD

**Issue by Vanderez** [GTNewHorizons/NewHorizons#2374]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
GTNH2 - Dirt Huts
#
#### What did you try to do, and what did you expect to happen?
I tried to complete quest 653 in Armors and Jetpacks. I had the required items to make the advanced electric jetpack itself, but couldn't complete the quest, since the quest needs 4x platinum wires. The item only requires 2x platinum wire.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Change the quest to only require 2x platnum wire, or change the recipe to require 4x platinum wire. Whatever you see fit.

**Comment by Dream-Master** [comment]
Fixed in dev
