### ISSUE TITLE
Cooler fluid reactor stopped working after last server restart

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2375]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I have a heater/cooler reactor setup. General idea was suggested by BloodAsp, and described here: https://imgur.com/a/h8n8t
Before today it worked and produced 1A LuV as expected.

#
#### What happend instead? (Attach screenshots if needed)
Today I discovered that fluid reactors no longer cool down hot coolant cells.

![image](https://user-images.githubusercontent.com/23512002/34654662-fdbcf210-f40f-11e7-9134-068fb4a02908.png)

**Comment by repo-alt** [comment]
Tested in single player - it still works there, so it must be a server side config.

**Comment by Dream-Master** [comment]
Nothing is changed.

**Comment by Dream-Master** [comment]
@repo-alt Did you know if any other user have this problem?

**Comment by repo-alt** [comment]
I don't know anyone using even conventional fluid reactor, let alone a heater/cooler setup. Judging by the fact that I was the first who encountered the https://github.com/GTNewHorizons/GT5-Unofficial/issues/72 bug, nobody uses fluid reactors.

**Comment by Anarack** [comment]
You could ask proof, in the discord, I knows hes been building a fluid setup, but not CRCS style set up.

**Comment by repo-alt** [comment]
It turn out that if the fluid reactor multiblock for any reason disassembles, coolant cells in it become usable only in EU reactor (until cooled). So this bug can be closed, because it is unlikely we'll find a reason for a reactor glitch (it was probably a heater reactor bug, not coolers), and the workaround is clear.
