### ISSUE TITLE
Reactor fluid port not accepting GT fluid pipes

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2376]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I tried connecting GT fluid pipe to a reactor fluid port and it won't connect. Not sure if this is because of GT6 style pipe connection (I also tried wrenching to connect and it still didn't work) or if it was always like this. This is for both input and output (an output with a fluid ejector upgrade).
#
#### What happend instead? (Attach screenshots if needed)
The pipes just stay unconnected.
#
#### What do you suggest instead/what changes do you propose?
I akways knew EU cabling between IC2 and GT is tricky, but didn't expect fluid piping to be just as problematic. If it's possible, allow for GT fluid pipes to connect to IC2 blocks?

**Comment by mitchej123** [comment]
Can you post a screenshot of the setup?

**Comment by Prewf** [comment]
![screenshot](https://user-images.githubusercontent.com/35204071/34655584-e09aad16-f3c0-11e7-9013-e76989c4b040.png)

**Comment by mitchej123** [comment]
Is the reactor fully formed? 

 Looking at the code (very quickly) it looks like the reactor port only advertises having a fluid tank when the reactor is fully formed.

**Comment by repo-alt** [comment]
I just tested this is single player and the pipe does connect and passes liquid. (If multiblock is formed that is)

**Comment by Prewf** [comment]
Does it matter that my fluid reactor ports are on the edge of my reactor? I basically used the layout on https://wiki.industrial-craft.net/index.php?title=Fluid_reactor, but i moved the fluid ports to "layer 5", so it's on the edge.

I can see in my reactor hatch UI that the reactor is currently in "fluid mode", if that helps (it's no longer in eu-mode).

**Comment by Prewf** [comment]
![screenshot](https://user-images.githubusercontent.com/35204071/34657001-8ca58f76-f3d6-11e7-8d1e-800b4f1e1900.png)

Looks like this. The screen shot from earlier is the port on the left side (the cold coolant input)

**Comment by repo-alt** [comment]
No, the fluid port (any port actually) should be in the middle 3x3.

**Comment by Prewf** [comment]
Yup that was it! Thought I read somewhere they could be used in corners and edges, but I guess they can't. Thanks for the help.
