### ISSUE TITLE
OreDict recipes and quests using Advanced Circuits

### ISSUE THREAD

**Issue by spinner2727** [GTNewHorizons/NewHorizons#2377]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
SP and MP
#
#### What did you try to do, and what did you expect to happen?
Try to craft some recipes or do the nanosuit quests with processor assemblies
#
#### What happend instead? (Attach screenshots if needed)
Some quests & recipes only allow IC2 advanced circuit (HV tier), but you should be able to use the alternates (processor assembly, etc).  If I already have ability to make processor assemblies, making IC2 HV circuits is really annoying and inefficient.
#
#### What do you suggest instead/what changes do you propose?
There is an NEI visual bug that only shows IC2 circuit as a valid circuit in the following recipes, but the alternates actually work when placing it in the machine:
1.  Fluid Filter Cover recipe - Shutter Cover + 2 AdvCircuit in assembler
2.  Fluid Regulator LV & HV recipe - LV or HV pump + 2 AdvCircuit in assembler (other tiers are fine for some reason, but have alternate recipes instead of cycling)

Oredict the following to <ore:circuitAdvanced> instead of just <IC2:itemPartCircuitAdv>:
3.  Quest 796 Sensor Lens Retrieval Task 1 under Armors and Jetpacks tab
4.  Quest 797 Heat Exchangers Retrieval Task 1 under Armors and Jetpacks tab

**Comment by Dream-Master** [comment]
Need to check.

**Comment by Dream-Master** [comment]
Quests are fixed ass recipes using only one circuits i cant reproduce.
