### ISSUE TITLE
Hydrogen and Nitrogen quality of life alternate recipes

### ISSUE THREAD

**Issue by spinner2727** [GTNewHorizons/NewHorizons#2378]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
SP and MP
#
#### What did you try to do, and what did you expect to happen?
Make hydrogen or nitrogen in a cell instead of as a fluid output
#
#### What happend instead? (Attach screenshots if needed)
No recipes exist for that
#
#### What do you suggest instead/what changes do you propose?
Hydrogen can be made in an Electrolyzer with 3 water, 1 empty cell and (Programmed Circuit == 1), output is 1 oxygen cell and 2 hydrogen gas (liquid).  It would be nice if there was a reverse recipe, with (PC == 2), 2 empty cell, 3 water, output is 2 hydrogen cell, 1 oxygen (liquid).  There are already many other recipes like this, which can either alternate cell or liquid when two liquids are involved.

It would also be nice if you could do something like that for nitrogen and compressed air in centrifuge too, but it doesn't use a programmed circuit, so maybe nothing can be done for that.

**Comment by Dream-Master** [comment]
Compressed air cell is a auto reverse recipe will see what i can add.
