### ISSUE TITLE
Spectre key dimension dosen't work

### ISSUE THREAD

**Issue by HaiderDK** [GTNewHorizons/NewHorizons#2379]
#### Which modpack version are you using?
2.0.25
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Used the spectre key to get to the private area (dimension), but after the dimension wipe it dosent exist anymore. I then created a new key and destroyed the old one and the dimension is still bugged.
Expected a 14x10x14 private room in the dimension.
#
#### What happend instead? (Attach screenshots if needed)
Nothing i was just floating in the empty space while getting random debuffs.
#
#### What do you suggest instead/what changes do you propose?
fix the dimension bug/glitch
![spectre key](https://user-images.githubusercontent.com/34953835/34673875-128bb18a-f484-11e7-8eca-1ecb6b6cde10.png)

**Comment by HaiderDK** [comment]
my friend tried to do it and it worked for him, but when i do it i end up outside of the box

**Comment by HaiderDK** [comment]
![2018-01-09_20 39 50](https://user-images.githubusercontent.com/34953835/34739714-6fc40aec-f57d-11e7-9497-3edac0ff7365.png)

**Comment by Dream-Master** [comment]
https://www.reddit.com/r/feedthebeast/comments/59vnpt/randomthings_how_do_i_restart_spectre_room_for/
maybe this issue ? @HaiderDK

**Comment by Dream-Master** [comment]
@HaiderDK no answer ? I close this now.
