### ISSUE TITLE
Carpenter recipes - honey

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#238]
Carpenter recipes using the honey are using the wrong honey (5880:18) and should be using the 5800:22 honey which is gotten when you extract Honey drops and Honeydew

**Comment by Dream-Master** [comment]
I look inside

**Comment by Drobac** [comment]
Will check other recipe but it needed to be changed in alveary heaters and fans. Gonna check all the other recipes

**Comment by Drobac** [comment]
Ooooor a better way would be to change which hone Honey drops and Honeydew gives when extracted. Seems to be a simpler solution since youu dont have to change all the recipes

**Comment by Dream-Master** [comment]
Make Fermenter Excange Recipes.

**Comment by Drobac** [comment]
For some reason the recipes are actually using BoP honey (id 673) which i mistaken for Honey (5880:18) so just switch the ID's in the fermenter recipe

**Comment by Drobac** [comment]
The recipes just state liquid:honey and no ID's so not sure which one is the default one

**Comment by Drobac** [comment]
Apparently the honey is not the problem, the honey that you get from the fermenter works fine and most of the recipes work ok. The problem seems to be in the recipes for all the alvearyy parts, tried them in single player and none worked
