### ISSUE TITLE
%material is displayed instead of the correct material in assembly line recipe book and electric prospector on block

### ISSUE THREAD

**Issue by arnoleo** [GTNewHorizons/NewHorizons#2380]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
On DirtHuts GTNH 1 servers
#
#### What did you try to do, and what did you expect to happen?
I scanned Field Generator tier 5 onto a data stick to get the Field Generator tier 6 recipe. I printed the book and expect to get all the materials to craft my field generator tier 6 in an assembly line.
#
#### What happend instead? (Attach screenshots if needed)
each material in the book is replaced by %material
![2018-01-07_16 42 15](https://user-images.githubusercontent.com/9444402/34681856-6bf09056-f49d-11e7-9a35-186d7f5f0104.png)
#
#### What do you suggest instead/what changes do you propose?
In addition, I got the same result when I used my electric prospector on a block. Only %material is displayed in the chat. When I use the electric prospector in the air, everything is ok.

The recipe books and the electric prospector should display the correct material instead of a generic %material.

**Comment by Dream-Master** [comment]
Fixed allready in 2.0.2.6 dev
