### ISSUE TITLE
OpenPC Private Protection...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2381]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
... not working. I can access Hyperic PC, modify it, turn it on-off.
![2018-01-09_00 13 56](https://user-images.githubusercontent.com/25028786/34692738-30ce5190-f4d2-11e7-9975-4637baf8b441.png)
![2018-01-09_00 13 58](https://user-images.githubusercontent.com/25028786/34692739-30f91092-f4d2-11e7-92ad-a0fe740be69c.png)

**Comment by Dream-Master** [comment]
@Cinobi please report it to original open computers repo. Thanks
