### ISSUE TITLE
The recipe for steel in an electric blast furnace

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2382]
At the moment, the receipt of steel from the weld iron is available only from dust. I propose to replace this option with an ingot.
![2018-01-09_20 03 40](https://user-images.githubusercontent.com/35035276/34733116-4769492c-f578-11e7-90cb-d0ff86447ef9.png)

**Comment by richardhendricks** [comment]
Blast furnaces in general require dusts to operate. I don't think we should change it to use ingots.  Using wrought iron is already quite a boost in speed and power savings.

**Comment by CalterOK** [comment]
But we get the wrought iron in ingots, and I see no reason to add one more intermediate step in the form of crushing it into dust.

**Comment by noobyaran9** [comment]
But there is a choice to not use wrought iron.

**Comment by richardhendricks** [comment]
The wrought iron recipe path is trading off effort for time and energy.  The time and energy savings using wrought iron are really large, so there needs to be a corresponding increase in effort. Making a special exception to allow for ingots is thematically & realistically wrong - nothing else AFAIK is input into the blast furnace as ingots.

**Comment by CalterOK** [comment]
For the blast furnace itself, it does not matter that it is introduced into it (ingots, dust, ore), it will still melt all this (if the temperature allows). And it's not understandable for me to enter into it an exception in the form of dust.

**Comment by richardhendricks** [comment]
The "blast" part of blast furnace is the air blowing through the furnace to drive off carbon impurities. If its already a solid bar it's harder to do that.  It makes sense that ingredients would be dusted before adding to the furnace.

**Comment by Dream-Master** [comment]
Ok i close this now. In GTNH you have to use dusts not ingots! @CalterOK
