### ISSUE TITLE
Update tooltips for Large Steam Turbine and Large HP Steam Turbine

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2383]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Private server (also tested in single player)
#
#### What did you try to do, and what did you expect to happen?
I set up my Large Steam Turbine following the page on the FTB wiki. According to this, I can expect to get distilled water back from my turbine via an output hatch.
#
#### What happend instead? (Attach screenshots if needed)
FTB wiki was right.
#
#### What do you suggest instead/what changes do you propose?
In NEI, the Large Turbine Controller block doesn't list "1x Output Hatch" as one of the possible blocks that can be used to form the multiblock. FTB wiki actually says an output hatch is "required" for the multiblock to form (only for steam and HP steam turbines). I propose that the tooltip be modified to include extra text such as "1x Distilled Water Output Hatch" for the Large Steam Turbine, since it's pretty useful to know that you can get your distilled water back when using the Large Heat Exchanger with the Large Steam Turbine. I also propose that the tooltip for the Large HP Steam Turbine to include "1x Steam Output Hatch" since the Large HP Turbine takes superheated steam and outputs regular steam in its output hatch.

Here's the current tooltip for the Large Steam Turbine. The Large HP Steam Turbine is the same way.
![largeturbine](https://user-images.githubusercontent.com/35204071/34737880-4e4571d6-f52c-11e7-852b-3dced58c87a3.png)

**Comment by Dream-Master** [comment]
@Prewf write down i line of text i can add to code.
Thanks

**Comment by Prewf** [comment]
For the Large Steam Turbine,
"1x Distilled Water Output Hatch (Side centered)"

For the Large HP Steam Turbine,
"1x Steam Output Hatch (Side centered)"

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7e3ee76a5512b1d45cc4493297d44d6748a87fa8
