### ISSUE TITLE
Flint sword doesn't get detected in Quest #11 (Sharpness: Over... 5...)

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2385]
#### Which modpack version are you using?
2.0.2.6

#### If in multiplayer; On which server does this happen? 
SSP

#### What did you try to do, and what did you expect to happen?
Quest #11 detecting the flint sword I crafted.

#### What happend instead? (Attach screenshots if needed)
Doesn't get detected (very likely the same issue like the flint tool quest)

#### What do you suggest instead/what changes do you propose?
Another quest to fix!

**Comment by Dream-Master** [comment]
I guess because the flint durability is changed too.
