### ISSUE TITLE
Quest text adjustment for #481 (Creosote oil)

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2386]
#### Which modpack version are you using?
2.0.2.6

#### If in multiplayer; On which server does this happen? 
SSP

#### What do you suggest instead/what changes do you propose?
Change "diesel generator" to "combustion generator" since they got renamed.

**Comment by Dream-Master** [comment]
@WarlordWossman you mean in the quest text?

**Comment by WarlordWossman** [comment]
@Dream-Master in fact the whole oil section in LV needs to be checked when it comes to quest text. At least the first oil quest mentiones a "diesel generator" and I guess a few of the others might also name them.
I guess going over all the quests quickly and replacing it with "combustion generator" would be a good idea.

**Comment by Dream-Master** [comment]
ok.
