### ISSUE TITLE
GC and GS Rockets have to use Rocket Fuel only

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2388]
GC and GS Rockets have to use Rocket Fuel only.
(Fuel will be disabled)

**Comment by Dream-Master** [comment]
Tier 1 ok but till tier 2 you need rocket fuel. I guess it's only possible to make on fuel for all.

**Comment by richardhendricks** [comment]
Have to add Rocket Fuel as fluids for canners etc, right now it cannot be used for anything.  Also need to update quests to reflect Rocket Fuel, and correct number of canisters.

**Comment by bartimaeusnek** [comment]
@draknyte1 did this in the newest GT++

**Comment by Dream-Master** [comment]
yes i see new fluids but i am note sure if the recipes match and which rockets use which fluid @draknyte1
