### ISSUE TITLE
Can u add quests to higher levels

### ISSUE THREAD

**Issue by akimbaev** [GTNewHorizons/NewHorizons#2389]
#### Which modpack version are you using?
2.0.2.6
#### If in multiplayer; On which server does this happen? 
my server
 Can you add quests to mv and hv and higher levels ?

**Comment by Dream-Master** [comment]
@akimbaev make some suggestions. What you like to see there ?

**Comment by akimbaev** [comment]
# Thanks for such a quick response. I'm just saying that I would like to see new quests at higher levels (starting from mv to the end).
For example, you can enter a chain of quests on Ore Drill and their upgrades, and a chain of quests for processing resources (processing array), and Assembling line(Multiblock)

**Comment by benstuwie** [comment]
I'd also like to see that. Some IV+ quests would be great. I'm up for helping you write some if you want, how far have you gotten in the pack so far?

**Comment by akimbaev** [comment]
@benstuwie you said to me or to @Dream-Master

**Comment by benstuwie** [comment]
@akimbaev you

**Comment by WarlordWossman** [comment]
Would def be helpfull if players that currently are in those high tiers make specific suggestions for quests!
If you are not playing that part of the pack yourself it can be a lot harder to guess what quests would make sense to add.

**Comment by akimbaev** [comment]
@WarlordWossman I wrote some suggestuons for quest to add

**Comment by benstuwie** [comment]
Assembly line for one, PAs too I guess. Solars above HV, naq reactors above IV. A bunch of fusion ones would be cool. Circuits maybe, like wetwares. There could be a whole section about scanning/assembly line stuff, and another section for fusion

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
-[ ] Ass Line
-[ ]

**Comment by Dream-Master** [comment]
i open up a new issue if necessary.
