### ISSUE TITLE
Energy production: Oil and Fuel

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#239]
I build myself a basic distillery setup, to convert some oil (To just *get* the oil you need: A GT pump, about half a stack of mining pipes (which you cannot retract from the pump, you have to mine them up, which is a problem with oil springs as you might fall down and die) a pump cover, a battery box, multiple batteries, a couple of dollies, a bunch of BC tanks and a backpack). 

The total conversion ratio for oil to fuel is a problem, IMHO:
I had 3 BC tanks (48 Buckets) of oil. After the conversion process (Oil tanks empty, fuel tanks full)
I ended up with 13 Buckets of fuel, and one charged 400k eu Lithium Battery.

So, as we don't have early game chunkloaders, and no early game endertanks to get oil from the oil-spring to your base, and no drums yet (Because moon), you have to carry Buildcraft tanks with dollies with you (Which slows you down if you don't put them in your backpack), to get oil to your base, where you use up more than 50% of its EU value to just convert it into fuel.

Sure, that fuel can be further processed into nitro diesel, but that takes even more power, and you'd end up with maybe 2-4 buckets of nitro diesel from 48 buckets of oil.

My first thought on that was; Maybe change the conversion ratio from [8mb oil > 8mb fuel for 256 eu], to [1000 mb oil > 1000mb fuel for 1024], to increase the initial yield

**Comment by Dream-Master** [comment]
Change Fuel from 128000EU per 1000mb to 192000EU
Change Nitro Disel from 384000EU per 1000 mb to 576000EU.
So we have to test it.

**Comment by Namikon** [comment]
Still working on that, I've build a Refinery now. (Took a while..) The new values seem to be a good choice for now. I have *some* ideas to make the nitro diesel a permanent energy source. As I've got ancient bees by accident, I probably will try to breed oil-bees next (Only takes up 2 or 3 more mutation steps, should be possible within 3-4 days maybe).
Getting oil is my main concern right now, as you need it for the rockets. But if you could get a solid amount of oil from bees, (or ic2 crops) and be able to "survive" with that until you are able to move on to nuclear power (Using both nitro diesel and creosote as power source for your machines), I think that'll be fine.

**Comment by Namikon** [comment]
We might have a problem here. In order to get oily bees, you need an ocean be. And those (http://ftb.gamepedia.com/Ocean_Bee) can only mutate in an ocean biome, which we don't have due to RWG still beeing alpha. 

You can use Gendustry and the ocean biome simulator, but that is endgame and we need the oil earlier in the game. 

Maybe it is not required to get into bees, depending on the rarity of the oil reservoirs, but then people must be aware that they have to stock up a few tanks of fuel for their rockets. Does oil spawn somewhere else than in the overworld?

**Comment by Dream-Master** [comment]
Spawn only in the over world. Maybe a mining world will help.

**Comment by Namikon** [comment]
Sure, not a problem. But how do you want to get people in and out that dimension? Central portal? Teleport command for free or with a price? If portals, what about people with homes 5k blocks away from spawn? If Teleport, how do you prevent people from abusing /home from everywhere? 

I had all these problems on my server. Solution for me : centralized portals to all dimensions, and a server wide, admin owned, portal system build with Enhanced portals3 mod. Each portal at specific positions, so you either could walk to the next public portal, or build your base next to it

**Comment by Namikon** [comment]
I think, it also might be possible to create a new item, that could teleport to a specific dimension on usage... If that's what you want. But I think we already have a lot of options available

**Comment by Drobac** [comment]
There was a system on sk89's server. If you had an ender pearl in your hand when you walk into a nether portal it then Teleports you to the Mining dimension, if you want to get back to the overworld you throw that pearl at your feet

**Comment by Namikon** [comment]
@Dream-Master There is a way to allow players to set a home with /sethome, and a command to teleport them to this spot (/home). Both commands can be configured, so that the /sethome only works  in the overworld, and /home just in the mining world. Also, there is an option to enable a delay to the teleport command. If a player moves, or is attacked, the teleport is cancelled, so it can't be abused to flee from a fight. (I'd set it to 5 seconds maybe..? It's a free ride home at least)

Would that be an option? It can be enabled today, without the need for additional mods/plugins.

**Comment by Dream-Master** [comment]
Yes good idea. But than we have to disable all Portals and make only admin Portals.

**Comment by Namikon** [comment]
So, as we've discussed on teamspeak then? A central portal area, portals to every player's base, only useable by the owner of that base. And by "all portals" you also mean nether/end/twilight portals ?

**Comment by Dream-Master** [comment]
Yes exactly.

**Comment by Namikon** [comment]
Ok. I will then start working on that today

**Comment by Namikon** [comment]
An additional option (Even if not very good), I found a way to change the biome of a selected area, so if it's just for the sake of having an "ocean" biome for bees (even without water), that would be possible. I still want to test that on the testserver first, but it looks promising

**Comment by Drobac** [comment]
Witchery biome change ritual?

**Comment by Namikon** [comment]
No, it's a bukkit plugin where you can select an area with worldedit, and convert that into anything else.
I didn't know witchery has such a ritual.. Is it early or lategame witchery? And can you select any biome you want? That might be a player-progression based solution, IF witchery will become a mod for low-tiers of course.

**Comment by Drobac** [comment]
Think it should work with the ocean biome, gonna test it now

**Comment by Drobac** [comment]
Works with witchery, you can switch an area to any of the biomes available. And it isnt that expensive to do, you should be able to do it at your tech lvl

**Comment by Namikon** [comment]
Keep in mind that Witchery isn't nerfed yet. And from what i've read, you need 4 coven witches for that ritual. Something tells me this is not going to be LV/MV age after nerfing...

**Comment by Namikon** [comment]
I will close this issue now. My long-term testing is done, and i'm pretty happy how the fuel values turned out. It is perfect to MV age, and (if we'll still have those oil wells from BC) it could be even useable for early/mid HV age
