### ISSUE TITLE
2.0.2.6 no have deprecated recipes

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2390]
2.0.2.6 no have deprecated recipes. sulfuric acid, glycerol e.t.c.
Its forever? or will return?

**Comment by Dream-Master** [comment]
Are there materials with no recipes or you just complain because recipes are more expensive? @Proha5

**Comment by Proha5** [comment]
more expensive.
My automated factories use lot of depleted recipes. Now its broken. I should rebuld all base for new extra hardest recipes (

**Comment by noobyaran9** [comment]
>more expensive.
My automated factories use lot of depleted recipes. Now its broken. I should rebuld all base for new extra hardest recipes (

When the recipe already mention that its deprecated, it means that its going to be removed in the future. So that u can change how ur system works before it gets removed.

**Comment by Proha5** [comment]
5 month ago gt added new chemistry. Some players stoped playing. But this modpack added deprecated recipes. And players returned to play. But now you delete this recipes.

**Comment by Dream-Master** [comment]
This recipes are never desinged for stay in the pack it be in there by accident.

**Comment by Dream-Master** [comment]
recipes are more realistic btw.

**Comment by Dream-Master** [comment]
If you suggest more realistic recipes i am fine with it. @Proha5 Reopen it when you have some recipes you want to add and i dont mean the cheap and cheaty old ones.
