### ISSUE TITLE
Tritanium should have a uu replication recipe in my opinion 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2391]
#### Which modpack version are you using?
2.0.2.5
#
#### What do you suggest instead/what changes do you propose?
Tritanium is needed for wetwares and nano circuits, but it's a real pain to make. It's an element though, and I think it would be cool if it had a replication recipe. Replication in general isn't too useful, but this might be a good use for it. It would need a pretty high UU cost as it's normally very difficult to make, and isn't used very often. Maybe 500mB per dust or something like that

**Comment by Dream-Master** [comment]
Tritanium need to be added as Element otherwise it isnt possible.

**Comment by benstuwie** [comment]
Is it not considered an element? It has the Tt under the item in nei. If it's hard to add an item as an element you don't need to. It's kind of fine the way it is. If it's easy to add an element, I think it would be good to be able to get tritanium from uu.

**Comment by Dream-Master** [comment]
Who add Tritanium Blood asp or we ?

**Comment by benstuwie** [comment]
Almost positive its bloodasp but I've never played just gt5u without the gtnh mod. It's a material you get from t3 fusion, and the only use I've seen is in wetwares/nano circuits.

**Comment by Dream-Master** [comment]
Is it a Element or not? that is the Question.  If yes i need more infos about protrons and neutrons etc

**Comment by benstuwie** [comment]
https://i.imgur.com/JbtVpgl.png
It looks like an element

**Comment by Dream-Master** [comment]
ok any star trek fan here who can give uis more infos about protones neutrons etc stuff?

**Comment by richardhendricks** [comment]
According to the Star Fleet Medical Reference Manual (p. 19), the element tritanium, symbol Tn, atomic weight 323, atomic number 125, was discovered by the Federation on Argus X in 2161.

So 125 protons, 198 neutrons.

**Comment by Dream-Master** [comment]
ok i can add it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34841170-9be58336-f707-11e7-916d-b4d9feca6a0c.png)

**Comment by Proha5** [comment]
tritanium is not problem. Get tritanium from Fusion reactor is easy and fast for end game.
Only 1 player wanted tritanium from UU matter. (hardest and longer than from fusion)
May be do vote for adding new features in the modpack?

**Comment by Proha5** [comment]
Tritanium from fusion is not problem.
Nano circuit + 2 wetware requere 8+8 tritanium.
MK3 create 16 tritanium per 4 minutes.
15 nanocircuits per hour. But 1 nanocircuits requere 4000 eggs! You create 4000 per 4 minutes? its realy pain. Creating Eggs slowest than creating tritanium.

**Comment by Dream-Master** [comment]
Well make a suggestions what materials we can use. Human brains?

**Comment by Proha5** [comment]
May be increase percentage?
current: https://ftbwiki.org/Stemcells
my opinion:
2%, 3%, 5%, 8%, 13%, 21%, 34%, 56% (fibonacci fractal progression)
OR
5, 10, 15, 20, 25, 30, 35, 40
or add to dissassemble chicken meat and feather, and other meats.

**Comment by LOKKO12** [comment]
You can get this ammount of eggs by using IC2 Crop farms. The Eggplant (Gregtech plant) will need 1200Growth points to fully mature, thats 30720ticks (=25min) with statt 0-0-0 for 0.9 egg.  With 21-31-10 statt it will need 7424ticks(=6min) and give ~2,8eggs per plant. If you have a 11x11 field (1 crop havester) of these plants, you get rughly 340 eggs per 6min. So you can make 10 of these fields, to get 3400 eggs per 6min.

btw the hardest part here is to get the 21-31-10 crop. once you have it, its really easy to set this up.

**Comment by Dream-Master** [comment]
I like it using some other stuff lie bacterials or other living material.

**Comment by richardhendricks** [comment]
There is bacterial sludge on the moon, but it is non-renewable.

**Comment by Dream-Master** [comment]
Yes this stuff from marse but maybe we can grow it with some binnies bacrteria and growth medium?
