### ISSUE TITLE
Error in the quest to buy steel

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2392]
#### Which modpack version are you using?
2.0.2.6
![2018-01-11_15 31 54](https://user-images.githubusercontent.com/35035276/34825803-02f2d434-f6e5-11e7-85ea-e50110b6e35e.png)
Instead of the usual steel, Damascus steel is bought, although there is another quest with less quantity for it.
![2018-01-11_15 31 46](https://user-images.githubusercontent.com/35035276/34825854-315533d0-f6e5-11e7-8395-92018157ccaf.png)

**Comment by Dream-Master** [comment]
Ok will fix it.
