### ISSUE TITLE
Nano circuit naquadria cost 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2393]
#### Which modpack version are you using?
2.0.2.5
#
#### What do you suggest instead/what changes do you propose?
The nano circuit takes naqudria in the assembly line, but it takes such a weird amount. It takes 4000L, but naquadria is an ingot, so it makes molten naquadria at a rate of 144L per ingot, which doesn't go into 4000. I'd suggest changing the nano circuit recipe to take 4032L naquadria, so it's an even ingot number. Right now it takes 27.78 ingots, this would make it take an even 28.

**Comment by Dream-Master** [comment]
I guess Naquadria is not th only recipe need to balance. @benstuwie Did you know other recipes that need to be changed?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/06c204d13707923e4f46903cadacee32b3eb9ef3

**Comment by benstuwie** [comment]
None that I've found that really need a change, but I haven't looked at any of the tectech stuff.

**Comment by benstuwie** [comment]
Not needed, but I think that lowering the time to craft a neuro processing unit wouldn't hurt. It's at 1min right now, lowering it to 40s would be fine. It kind of makes using wetwares below the mainframe useless, as it's quicker to just craft the crystalprocessor equivalent

**Comment by Dream-Master** [comment]
recipe stay like it is this is the highest circuits and it is expensive at this tier.

**Comment by benstuwie** [comment]
It's no the expensive part that's an issue. I do find the egg cost a bit weird, but it's all manageable. The problem is the crafting time on the NPU's. Needing them for wetware base circuits makes using wetwares almost useless until the mainframes. Crystalprocessor are so cheap as it is, making wetwates for LuV-UV. Making a mainframe takes 2x the time of a NPU, but costs 8 NPU's. So the npu part of them takes 4x longer than making the actual circuit. 
That said. Apart from the eggs, the material cost of the NPU's is a little cheap in my opinion. If they cost maybe a crystalprocessor tier one, but took half the time in the assembly line I think it would be more fair. Right now they just cost some glass told and eggs, really really cheap.

**Comment by Dream-Master** [comment]
Yes circuits recipes nedd a compete reworte.

**Comment by benstuwie** [comment]
I agree. I'm not sure what it's like starting up now, because I was in ZPM/UV tier when the circuit change came, but the only thing I've really seen as a problem has been the wetwares/npus. There's a couple things that just seem odd, or out of place, but nothing seemed particularly broken to me besides wetwares

**Comment by noobyaran9** [comment]
There is also glass. U melt glass into 144mb and u use 500mb which is a weird number. Maybe changing the amount u get from glass to 250mb? I'll look for screenshots and post it here later.

**Comment by Proha5** [comment]
27.78 ingots is not problem. Assembling line fluids is not automated by AE2. I fill full input hatch without control.
May be do vote for adding changes to the modpack?

**Comment by repo-alt** [comment]
But the assembly line is automatable, and odd number do it no good.

**Comment by Proha5** [comment]
repo-alt, how you automate fluids in assembling line? i use Ae2+SFM for items. Fluids is fixed. All hatches contain all fluids full.

**Comment by repo-alt** [comment]
I did not yet build a working prototype, but it will be OC controlled local AE network, with fluids supplied via cells. (OC transposers can manipulate odd quantities of fluid but then I'll have to use either extra cells, which I don't like, or a set of buffer tanks which is ugly). So far I tested parts of this solution in creative and did not find any obstacles, but I did not examine many recipes.

**Comment by benstuwie** [comment]
> repo-alt, how you automate fluids in assembling line? i use Ae2+SFM for items (maximum 9). Fluids is fixed. All hatches contain all fluids full.
I don't have fluids automated, I just have drums fed by AE export buses to keep them always full. My issue is more that it's just not a full ingot for no real reason. 
>Please, change modpack only for serious issue. Because lot players already builded big factories. Any changes may will broke factory.
I don't think changing it to 28 ingots will mess up any automations, and even if it does, it's a simple fix to change it in AE and sfm. This just makes it easier if anything. 
>There is also glass. U melt glass into 144mb and u use 500mb which is a weird number. Maybe changing the amount u get from glass to 250mb? I'll look for screenshots and post it here later.
Do you mean the tubes for the NPU's? Those take 1 glass each right now, 144mB molten glass, or 1000mB of the ticon glass, so it should be fine right now

**Comment by noobyaran9** [comment]
![2018-01-12_13 35 13](https://user-images.githubusercontent.com/13598309/34861139-970c2edc-f79d-11e7-866f-385d53791268.png)
![2018-01-12_13 35 40](https://user-images.githubusercontent.com/13598309/34861140-97423b62-f79d-11e7-81bd-7d1e7dd7736f.png)
This 2 recipe currently takes 55.56 glass(8000 mb) to craft which is weird. Changing them to 8064 mb or 7920mb would be better

**Comment by benstuwie** [comment]
Oh ok, yea, that looks bad. I was mostly talking about assembly line recipes, but I agree with you, that's annoying

**Comment by Dream-Master** [comment]
What is this item?

**Comment by noobyaran9** [comment]
>What is this item?

Illuminator from IC2

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
It was Luminator but i found it.
