### ISSUE TITLE
Large Heat Exchanger gives 5x output steam, not 10x

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2394]
#### Which modpack version are you using?
2.0.2.5 (it was unchanged for 2.0.2.6 i think, or at least nothing was mentioned in changelog)
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Fed my LHE exactly 380 coolant per second, expected to get 304,000 steam per second. The controller tooltip says that steam output was increased 10x for new horizons, so this should boost LHE default of 1L coolant->80L Steam into 1L coolant->800L Steam.
#
#### What happend instead? (Attach screenshots if needed)
Only getting 152,000 steam per second. I have 6 large turbines, each expecting to get fed 48000 steam per second, but only 3 of them are getting enough input. The other 3 are either barely powered or not powered at all. This means 1L coolant->400L Steam, so only a 5x increase. Screenshot below.
#
#### What do you suggest instead/what changes do you propose?
I would suggest changing the code so that it's 10x Steam output as stated. Or, update the tooltip so that it says 5x, not 10x. Outcome of this doesn't really matter for me since I can easily just update my fluid reactor design and adapt, but it would be useful for anyone else doing the calculations for their fluid reactor design.
![notenoughsteam](https://user-images.githubusercontent.com/35204071/34842902-ca2d6d62-f6c1-11e7-97a7-ba6bf5785af1.png)

**Comment by Dream-Master** [comment]
I not change anything there so might be a bug or it was allways 5x.

**Comment by Dream-Master** [comment]
@Technus any idea?

**Comment by Dream-Master** [comment]
Ok i see in code that was changed but 3 month ago not in 2.0.2.5/2.6

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/4ec739c927cb1b338383df2f49bb08e33737eb61#diff-889ab692b1b88addc9d7307b88056613R115

**Comment by Dream-Master** [comment]
@Technus why you changed it back was there any reason ?

**Comment by Bryfer** [comment]
Wasn't this reduced from the previous 10x because it was way to powerful?

**Comment by repo-alt** [comment]
I was powerful, but nobody was using it anyway.

**Comment by Dream-Master** [comment]
Tec said tooltip is wrong

**Comment by Dream-Master** [comment]
Ok guess it is the Quest.

**Comment by Dream-Master** [comment]
yes

**Comment by Dream-Master** [comment]
We dont have a Quest for it so far i can see.
@Prewf can you show me where it says 10x?

**Comment by Dream-Master** [comment]
ok found it.
@Prewf next time i need a pic like this please:
![image](https://user-images.githubusercontent.com/2970688/34916780-c19f5862-f93d-11e7-88ce-2c0f8ab7a713.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34916812-442df874-f93e-11e7-8142-72141c5f2e1a.png)

**Comment by Prewf** [comment]
sorry about that! next time i will, thanks dream

**Comment by Dream-Master** [comment]
ok cool
