### ISSUE TITLE
Big Door frames

### ISSUE THREAD

**Issue by wllp** [GTNewHorizons/NewHorizons#2395]
#### Which modpack version are you using?

2.0.2.5

#### Issue
How do I edit the big door frames from Malisis Doors mod?

(really sorry if the format is wrong this is my first time doing anything like this)

**Comment by Dream-Master** [comment]
@wllp can you show me which Door frames you mean? i look in the mod and dont see them.

**Comment by wllp** [comment]
![image](https://user-images.githubusercontent.com/16256066/35176054-eacfc5d6-fd44-11e7-8736-20bd9c2b9835.png)

**Comment by wllp** [comment]
This was taken from the mods post on the mc forum:

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2076338-malisisdoors-1-12-2-7-2-4-1-11-2-6-1-3-12-01-2018

**Comment by wllp** [comment]
Using the original recipe one would do this:
![image](https://user-images.githubusercontent.com/16256066/35176118-35626b12-fd45-11e7-96e7-4bf186781f5d.png)

**Comment by Dream-Master** [comment]
@wllp What you want i change ? The recipe ?

**Comment by wllp** [comment]
What would be nice is having a way to craft those doors with the kind of frame I want, from what I can tell you can only make the one that looks like quartz (and only the carriage door, not the other one).

**Comment by Dream-Master** [comment]
Are the available in normal 1.7.10 Minecraft? @wllp

**Comment by Dream-Master** [comment]
I mean in 1.7.10 malis door mod or later added in nd 1.10?

**Comment by melignus** [comment]
Curious about this also. My brother is attempting to make these in our game and says that currently he's only able to produce the Oak Door versions. The Spruce Door versions don't seem to be currently craftable?

**Comment by SergeantTibbs** [comment]
Checking in and adding my hope that this issue will get some attention.

Cheers!

**Comment by Dream-Master** [comment]
Spruce doors was added in mx 1.8 so that is why the medieval door not obtainable. Nothing i can dore here because i wont add 100 and more recipes by hand. Other door works fine. I remove assembler recipe. Sadly the doors not shown in NEI.

**Comment by wllp** [comment]
So the spruce door was already added by this mod if that make a diffence

**Comment by wllp** [comment]
![doors](https://user-images.githubusercontent.com/16256066/62604704-98512180-b8c6-11e9-838a-7a21b410ed29.PNG)
This is a shot of me testing it out on a 1.7.10 build with the same version of forge and the mod as our pack.

**Comment by wllp** [comment]
Anyways I have the time now finally to mess with the code a see if I can't find a way to make this all work.

**Comment by Dream-Master** [comment]
ok cool

**Comment by wllp** [comment]
Oh, I get it now so they are craftable without a tweaked recipe just its not showing up in NEI, strange. Well sorry for reopening the issue my bad, I'll still see if I can get the assembler recipe to work that you had intended but for now I'm happy

**Comment by richardhendricks** [comment]
Do we need to add something to the Build Better Bases quest tab?

**Comment by wllp** [comment]
That might be a good idea because I myself forgot how to do this and had to look up this thread :P

**Comment by ablazingrace** [comment]
Really annoying that jei tells you nothing about these doors. Simple thing to do would've been a door and the 'any wood' etc. placeholder. Instead, you have to google for the info and end up here.

Well since I'm here, this is a thing:
![Screenshot (104)](https://user-images.githubusercontent.com/56435301/82732072-fb3a6a80-9cd8-11ea-8913-ea8b4f42f5cf.png)
same happens for basically anything from any mod that has a physical form in the world, to an extent (blocks with extra bits won't show their extra bits, for example thatch from mystical world).

**Comment by Dream-Master** [comment]
Maybe somone can do a quest ?
