### ISSUE TITLE
Some issue with dimension 29 on server

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2397]
#### Which modpack version are you using?
2.0.25
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Teleported to Mars that is marked with my charm of dislocator. Game crashes
#
#### What happend instead? (Attach screenshots if needed)
https://pastebin.com/DtsMehkn
#
#### What do you suggest instead/what changes do you propose?
IDK when this started to happen. Might need to check the server world file. There might be dimension ID mismatch. Im not sure if im able to get out of this dimension right now.

**Comment by noobyaran9** [comment]
NVM. Its because that dimension never got generated after wipe. I think its fixed now.

**Comment by noobyaran9** [comment]
>[22:11:17] [Client thread/ERROR]: Client dimension 29 has no match on server - probably a server dimension ID conflict problem.
[22:11:17] [Client thread/ERROR]: Client dimension 28 has no match on server - probably a server dimension ID conflict problem.

If you get the above log in latest.log when loading into delta, you will have a really high chance of crashing when going into moon (dim 28) and mars (dim 29).The crash is still happening.

**Comment by Dream-Master** [comment]
So you can or you cant enter this dims ? @noobyaran9

**Comment by noobyaran9** [comment]
>So you can or you cant enter this dims ? @noobyaran9

You may or may not crash.

**Comment by Dream-Master** [comment]
@noobyaran9 idk what wrong here. We can reopen it.
