### ISSUE TITLE
Can't see recipe in nei

### ISSUE THREAD

**Issue by akimbaev** [GTNewHorizons/NewHorizons#2399]
#### Which modpack version are you using?
2.0.2.6 before update i saw recipe
#
#### If in multiplayer; On which server does this happen? 
my local server
#
i can't see recipe component maker (basic , advanced etc.)

**Comment by Dream-Master** [comment]
Sorry but I need more infos and pics

**Comment by akimbaev** [comment]
i just restarted game and then all fine

**Comment by akimbaev** [comment]
you can close this isssue
