### ISSUE TITLE
Suggestion: Change Forestry back to NORMAL mode

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#240]
As suggested by BloodAsp, change the Forestry Gamemode back to NORMAL settings.
I just compared both config files, and the values don't get OP'd, most values just go up by 50%. Only farms last a lot longer (200%), so this could be changed to 750 instead of 1000.
500 seems to be a bit too hard, as apatite is might be a common source, but compared to vanilla apatite spawn (And the Fortune-Bonus you get while mining) we have *less* apaite with GT than with vanilla forestry

**Comment by Dream-Master** [comment]
I will look inside the Forestry Hard config and change some things.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/905b40e496fca967fccfe758b448dab31511af77
https://github.com/GTNewHorizons/NewHorizons/commit/111ab054d3f3f8bfdd1e723230eb9db23eb39ef2
