### ISSUE TITLE
[suggestion][simple] add hardened sand to the sand oredict

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2400]
#### Which modpack version are you using?
2.0.2.6

Hardened sand from boims o' plenty is basically orange sand that is not effected by gravity and you can do nothing with it atm. I started in a biom with a lot of those blocks, would be nice if I could use them.

#### What do you suggest instead/what changes do you propose?
Simply add hardened sand to the sand oredict.

**Comment by richardhendricks** [comment]
Should we add a further processing recipe? Red sand can be centrifuged to make sand/iron dust/tiny diamond dust. Perhaps a fast HV centrifuge recipe to give sand and clay dust?

**Comment by Dream-Master** [comment]
Oredict is not a good idea but additional recipes i could add.

**Comment by Dream-Master** [comment]
@WarlordWossman which new recipes you like to see?

**Comment by WarlordWossman** [comment]
Maybe forge hammer to convert to normal sand? 

And centrifuging into sand with a chance for clay dust like @richardhendricks suggested?

**Comment by Dream-Master** [comment]
ok.
