### ISSUE TITLE
Issue with picking up ores on Epsilon

### ISSUE THREAD

**Issue by JackieMatthews** [GTNewHorizons/NewHorizons#2402]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to mine Lazurite and the other ores in the vein. I expected it to, as normal, allow me to pick up the ores no problem just like when I was on Server Delta. Before anything: I haven't got the achievement for these ores before on the server but on Delta.
#
#### What happend instead? (Attach screenshots if needed)
Kicked out of the server, after picking up the ores; tried picking up other ores (namely Redstone,) and got the same result.
#
#### What do you suggest instead/what changes do you propose?
No suggestions or changes; just hoping this issue can be figured out and fixed. It only seems to be occurring to me, not sure for other people.

**Comment by Dream-Master** [comment]
I need you to log in and need the log from you. I will check server log.
