### ISSUE TITLE
Item and Fluid translocators do not work with GT6 style pipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2405]
#### Which modpack version are you using?
2.0.2.6

Looks like changes to update to GT6 style pipes makes item and fluid translocators no longer work to push into GT pipes.

Screenshot, item translocators trying to push into brass item pipe, cannot.

![2018-01-12_12 51 11](https://user-images.githubusercontent.com/1214811/34890461-a2aa7b28-f797-11e7-999a-8a0e9bebcd96.png)

**Comment by Dream-Master** [comment]
@mitchej123 any idea on this ?

**Comment by richardhendricks** [comment]
May be related to #2404?

**Comment by Dream-Master** [comment]
guess so but i am not sure.

**Comment by mitchej123** [comment]
Will take a look.  Did you try using a wrench to connect?

**Comment by richardhendricks** [comment]
Yes, I tried a wrench, but it failed, probably because the translocator isn't a GT machine or pipe?

**Comment by tranceplanet** [comment]
I believe this is similar to an issue where pipes can't be connected to Solar Panels, Translocators, P2P Tunnels EU and some other things.

The new GT Pipe system doesn't appear to recognise many interfaces as it should when attempting to connect it manually.

However, in some cases, there is a way around:  When placing the pipe for the first time, if you click  directly to the face of the inventory/block it will connect first time.  Problem is; Item Translocators and Solar Panels cannot exist without the pipe...

**Comment by mitchej123** [comment]
Can probably patch GT so it will connect to the translocator.  Will need to look into how translocator present themselves - fixed similar issues with p2p tunnels and solar panels.
