### ISSUE TITLE
[Balance] Adjust oilsands to make them worthwhile

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2406]
Oilsands currently has a long centrifuge recipe and only gives 500L per block.  Since it is a rare resource and there are already oilspouts, suggest making it worth collecting. 

Proposal is to decrease centrifuge time to 4s at LV, and make it output 2000L per block.  A fully mined vein would be 6-8 stacks I'm guessing, or about 784-1024 buckets, less than 1/2 of an oil spout.

**Comment by Dream-Master** [comment]
ok will change.

**Comment by Scorpy23** [comment]
Also it has a 0.63% chance to give 1 sand, IMO this should be increased to something like 50% or completely removed.

**Comment by Dream-Master** [comment]
yes will take the chance to a higher value (sand)
