### ISSUE TITLE
Compost recipe is wrong

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2407]
#### Which modpack version are you using?
2.0.2.6
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I tried to make compost, expecting it to NEED water to make.
#
#### What happend instead? (Attach screenshots if needed)
Instead, the recipe actually GIVES water, which makes no sense.
![2018-01-12_16 43 42](https://user-images.githubusercontent.com/29802757/34896410-c4fc4790-f7b7-11e7-9b98-0ca9ea8f76ff.png)

#
#### What do you suggest instead/what changes do you propose?
Make it need water to make.

**Comment by Dream-Master** [comment]
yea true
