### ISSUE TITLE
Generation maps broken

### ISSUE THREAD

**Issue by DragonHacker1** [GTNewHorizons/NewHorizons#2408]
#### Which modpack version are you using?
2.0.2.6
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I trying to explore, but have someting broked maps.. And spatial ... from ae2 spawning? lol
#
#### What happend instead? (Attach screenshots if needed)
AE2 Spatial.
![2018-01-12_23 28 20_2 - copy](https://user-images.githubusercontent.com/34381388/34897416-8e4cd3c4-f7f6-11e7-8a82-c30c11f386d0.png)
![2018-01-12_23 28 20_2](https://user-images.githubusercontent.com/34381388/34897417-8e6d97c6-f7f6-11e7-86fa-fc9fcd73467c.png)
Some building ... broken... 
![2018-01-12_23 45 43](https://user-images.githubusercontent.com/34381388/34897430-a3bbdbce-f7f6-11e7-96f0-da1e2def60d0.png)
![2018-01-12_23 36 08](https://user-images.githubusercontent.com/34381388/34897432-a3d82b12-f7f6-11e7-92a4-d903ac753db1.png)
![2018-01-12_23 45 23](https://user-images.githubusercontent.com/34381388/34897433-a3f52cda-f7f6-11e7-94e5-db7dd325efee.png)
![2018-01-12_23 45 33](https://user-images.githubusercontent.com/34381388/34897434-a4111a26-f7f6-11e7-878c-d599be56846f.png)
![2018-01-12_23 45 41](https://user-images.githubusercontent.com/34381388/34897435-a42dcf72-f7f6-11e7-99b0-8b6cc5774820.png)

#
#### What do you suggest instead/what changes do you propose?
you need to disable tinkery construct villager, because is so tricky to get some items can't crafting on dirt age

**Comment by richardhendricks** [comment]
Worldseed?

**Comment by Dream-Master** [comment]
There is some config in tinkers that let spawn random blocks in the world.

**Comment by Dream-Master** [comment]
i guess you mess with your tinkers config

**Comment by Dream-Master** [comment]
B:"All the world is Superfun"=false

**Comment by DragonHacker1** [comment]
i not have high experience of configuration, but i checked someting 
![screenshot_1](https://user-images.githubusercontent.com/34381388/34897674-fc239580-f7f7-11e7-9a45-138257d30664.png)

**Comment by Dream-Master** [comment]
I dont want to disable it. I never get a problem with it. I like to see Ticon structures there

**Comment by DragonHacker1** [comment]
yea, but another solution is make more rarely

**Comment by Dream-Master** [comment]
And you show me a Witchery Kobolt House stay close to a witchery  apothecary

**Comment by DragonHacker1** [comment]
where is kobolt house?

**Comment by WarlordWossman** [comment]
the last 3 screenshots are from a kobolt hut

**Comment by Dream-Master** [comment]
Shown in the pic 5,6,7. This one with a cauldron in it.

**Comment by DragonHacker1** [comment]
okay, 
seed - -7733764309586370464
![2018-01-13_00 34 09](https://user-images.githubusercontent.com/34381388/34898020-9ba8cd18-f7f9-11e7-9396-2d04542afc8c.png)
![2018-01-13_00 34 11](https://user-images.githubusercontent.com/34381388/34898021-9bcf1766-f7f9-11e7-80b7-98804edfebf5.png)
![Uploading 2018-01-13_00.34.13.png…]()

**Comment by DragonHacker1** [comment]
i starting to break litte bit.. 
![2018-01-13_00 35 58](https://user-images.githubusercontent.com/34381388/34898062-c4629e96-f7f9-11e7-9661-284a0f7bf930.png)

**Comment by richardhendricks** [comment]
Yeah that is a kobold house from Witchery.

**Comment by Dream-Master** [comment]
@DragonHacker1 did you are using rwg worldgen ?

**Comment by DragonHacker1** [comment]
i created world default settings, "Realistic Alpha" can't change.

**Comment by Dream-Master** [comment]
ok if you not change the configs and used the pack untouched we need the worldseed and th point where you see this things.

**Comment by DragonHacker1** [comment]
i gived seed on picks.. 
seeds

seed - -7733764309586370464

and coord... is on ss

**Comment by DragonHacker1** [comment]
i tested recreation map, is same but different c. 
![2018-01-13_00 58 27](https://user-images.githubusercontent.com/34381388/34898665-f4e3487e-f7fc-11e7-91e1-a3221244db6d.png)
![2018-01-13_00 58 29](https://user-images.githubusercontent.com/34381388/34898666-f50bd460-f7fc-11e7-8fc0-8b24de236f8c.png)
![2018-01-13_00 58 13](https://user-images.githubusercontent.com/34381388/34898668-f5314a4c-f7fc-11e7-99ae-705b169d1efa.png)
![2018-01-13_00 58 16](https://user-images.githubusercontent.com/34381388/34898669-f5562484-f7fc-11e7-9de7-d99b3dbf6085.png)
![2018-01-13_00 58 19](https://user-images.githubusercontent.com/34381388/34898670-f59bb9ea-f7fc-11e7-8f89-046c417ca431.png)
![2018-01-13_00 58 24](https://user-images.githubusercontent.com/34381388/34898671-f5c30cf2-f7fc-11e7-9438-eb742176c2bc.png)
and why make 2 structures that?
![2018-01-13_00 59 24](https://user-images.githubusercontent.com/34381388/34898719-30fff5e6-f7fd-11e7-81ec-6a1ffadea9f1.png)
i checked ae2 spatial ... is failed, my theory , maps make different placing....

**Comment by Dream-Master** [comment]
Thats true you get not two times the same map.

**Comment by DragonHacker1** [comment]
but, where coming ae2 spatials pillars?

**Comment by Dream-Master** [comment]
idk maybe some bug. Need to see the log.

**Comment by DragonHacker1** [comment]
what logs? i have many.. fml-client that time creating map?

**Comment by Dream-Master** [comment]
yes

**Comment by DragonHacker1** [comment]
i don't know what files for generating, because i don't founding spawning etc.. i giving you ZIP with some files.
[logs.zip](https://github.com/GTNewHorizons/NewHorizons/files/1627796/logs.zip)
i have fml client 2 because i crashed random from my pc, is so rarely. and 2 runs.

**Comment by richardhendricks** [comment]
Never seen the pillar before, ever. Is that the only one?

**Comment by DragonHacker1** [comment]
@richardhendricks no, is multiple guesting

**Comment by richardhendricks** [comment]
Will test worldseed today.

**Comment by richardhendricks** [comment]
Cannot find any AE2 structures at same location.  Maybe it is a corruption of a redwood?  I did see a TC obsidian totem structure.
![2018-01-13_08 12 55](https://user-images.githubusercontent.com/1214811/34906781-9b71a79e-f839-11e7-95db-1dcc52184e05.png)

**Comment by DragonHacker1** [comment]
why need test memory? i have 8gb drr4..

**Comment by Dream-Master** [comment]
No they give every time different stuctures

**Comment by Ugachaga** [comment]
Pillar definitely looks like redwood trunk.

**Comment by DragonHacker1** [comment]
yea but, i breaked and is actually spatial.. is more like a coruption placing blocks

**Comment by richardhendricks** [comment]
Yeah, that's why I think you should do a memory test on your PC.  I did 2000x2000 pass on that worldseed, did not see any strange AE2 structures like that, including a check inside all redwood forest biomes.

At this point, we will just monitor this issue and see if other run into it.

If someone else sees this issue, screenshot + report worldseed if in SP mode.
![2018-01-13_14 19 26](https://user-images.githubusercontent.com/1214811/34909761-e2694b7e-f86c-11e7-8113-d407f0879512.png)

**Comment by DragonHacker1** [comment]
how testing memory...? im noob sorry..

**Comment by richardhendricks** [comment]
Windows 7 and up
https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/windows-memory-diagnostics-tool-mdsched/c5f13d70-fb48-4ec4-b2fb-d9a5cb3f7c86?auth=1

**Comment by DragonHacker1** [comment]
![n81tvvofqvuffgsiuigqia](https://user-images.githubusercontent.com/34381388/34914530-3ff03c02-f91d-11e7-800d-83cf524df032.png)
No error.

**Comment by richardhendricks** [comment]
Are you running 100% vanilla install of GT:NH?  No additional mods?

Also, is this your first install or did you update from an older version?

Very strange.

**Comment by DragonHacker1** [comment]
is clean modpack, i use twitch , i added one mod.. betterfps, im sure is only client side that mod.

**Comment by DragonHacker1** [comment]
and is first install

**Comment by LOKKO12** [comment]
uninstall betterfps, try again with same seed.

**Comment by DragonHacker1** [comment]
i said, tested another map with same seed, they not give same structure, but villager that have bug with that seed, and AE2 spatials is random structure with problem name/id, betterfps is a CLIENT SIDE mod, i used on server no betterfps or mods. How affect server with my betterfps? nope

**Comment by richardhendricks** [comment]
Yeah it does sound really weird.  At this point, since we can't duplicate it reliably I will mark as can't reproduce until we have more reports.

**Comment by DragonHacker1** [comment]
is need more tests, but i testing me with 100 maps created same seed, but need time.
