### ISSUE TITLE
[suggestion] Wool assembler recipe

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2409]
#### Which modpack version are you using?
2.0.2.6

Making wool from 5 string is a thing:
![2018-01-12_23 38 12](https://user-images.githubusercontent.com/16925725/34898286-897e1d5c-f7f2-11e7-92eb-45ef4d55c40f.png)

However there is no GT way to automate this yet.
I would suggest adding an assembler recipe to make wool from 3 string. 
It could be like this:

**Assember:**
3 string + programmed circuit ---> wool
200 EU
4 EU/t
2,5 seconds

**Comment by Dream-Master** [comment]
Yes good idea.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34905515-6f63f4c4-f85a-11e7-926b-7cb2e81aa671.png)
