### ISSUE TITLE
Bed Rock Pickaxe needed for Extra Utilities

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#241]
@Namikon We need a Pickaxe witch can mining Bed Rock above level 1 because i want a way to get Bedrockium from Extra Utilities. This Pickaxe have to come over Manyullyn level. It have to mine the bedrock very slow. Btw now are Bedrock Tools in Tinkers available via Extra Utilities.

**Comment by Namikon** [comment]
A pickaxe would be very difficult to do, and it might even impossible to prevent bypassing the pickaxe.
Bedrock has the flag "unbreakable", so no mining tool will work, no matter how good you'd make it. It just has infinite durability, so to speak. I would have to replace the bedrock block with something different once someone starts to mine it, maybe a block with a crazy hight amount of hardness, but then you could just switch back to, for examle, Vajra, or the IC2 mining laser, and bypass the mining process. The only thing I could imagine is to create a machine which runs of EU, and removes the bedrock block in front of it after consuming X EU for Y EU/t. Basically, imitating the bedrock breaker from Rot.Craft

**Comment by Dream-Master** [comment]
Yes a machine using Eu like and brakes Bedrock Blocks like the rotary Craft bedrock Breaker would great too.

**Comment by Namikon** [comment]
Ok, but this will take some time, as I have to dig into TileEntities and GT's EU power system.
To keep it clean, I'd probably add it to a new mod. Guess I'll need a lot of classes for that..

**Comment by Dream-Master** [comment]
Is there a easier way to get Bedrock ?

**Comment by Drobac** [comment]
well you could just enable the normal bedrock ingot recipe

**Comment by Dream-Master** [comment]
Yes but bedrock I think is better. Why compressed stone are be bedrock?

**Comment by Drobac** [comment]
Well dont have to use the exact recipe, tweak it a bit. Its an easier solution then coding a new mod just to implement it

**Comment by Dream-Master** [comment]
But get Bedrock as a new material would be very interesting

**Comment by Drobac** [comment]
What would you use it as except in recipes for drums and tools?

**Comment by Dream-Master** [comment]
Drums and tools and maybe more if i can mine it.

**Comment by Namikon** [comment]
It is probably better to just use rare materials that we already have, or re-enable the vanilla bedrockium recipe. To be honest, you need 43 *million* cobblestone to get 9 ingots of bedrockium, and as there is actually no way to get unlimited-free-cobblestone without having a ton of transfer nodes with 64 speed and a world interaction upgrade (just try to get the ressources for that). The rock breaker requires power to run, and **one ingot of bedrockium** would be **2388 Million EU**.
I don't see any requirement to do new machines to break bedrock blocks

**Comment by Dream-Master** [comment]
Ok i added back some other Recipes.
