### ISSUE TITLE
Bug: Tinker's faucet not recognizing GT pipe 

### ISSUE THREAD

**Issue by mrpv13** [GTNewHorizons/NewHorizons#2410]
#### Which modpack version are you using?
2.0.2.6
#
#### What did you try to do, and what did you expect to happen?
One of the quest is early automation of the smeltery, using a faucet, GT large bronze pipe. By right clicking on the faucet, the liquid goes into the GT pipe in which then can pipe to a casting basin.
#
#### What happened instead? (Attach screenshots if needed)
The liquid does not go into the GT pipe after right clicking on the faucet. I have tried connecting the pipe using a wrench to the faucet and the casting basin (it connects to basin like it did in the previous version, but the faucet). 
#

**Comment by mitchej123** [comment]
I can think of two fixes. Either patch tinkers to fill from "unknown" side, which bypasses connection requirements, or patch GT so it will connect (and render that way) to tcon faucets.

**Comment by mrpv13** [comment]
https://gfycat.com/AgreeableVioletBoaconstrictor

**Comment by richardhendricks** [comment]
Could we have GT default to connecting to non-GT items and not connecting to GT items by default?

**Comment by richardhendricks** [comment]
I wouldn't worry too much about accessing from multiple blocks up.  The concern is that it would need to be done with any other mod that interacts with the pipes, like translocators.  I didn't know the universal cells could interact with pipes like in #2404

**Comment by richardhendricks** [comment]
https://xkcd.com/1172/

**Comment by Dream-Master** [comment]
I remember it works fine output fluids into gt pipes from faucets and back to casting table and basin. Will test first @mitchej123 @richardhendricks

**Comment by richardhendricks** [comment]
It did before the pipe change, doesn't work now, I just tested in a creative world.

**Comment by Dream-Master** [comment]
Oh ok so @mitchej123 we need a fix here.

**Comment by Dream-Master** [comment]
https://gfycat.com/AgreeableVioletBoaconstrictor

**Comment by Antifluxfield** [comment]
Well... One possible solution for these pipe issue is: ignore those "canInputFrom(direction)" and "canOutputTo(direction)" checks with GT6-style pipe(or cable) enabled.
Besides, isConnectedAtSide(int aSide) should always return true when aSide == 6(the unknown direction) for all those pipes and cables.
@mitchej123

**Comment by Dream-Master** [comment]
@Antifluxfield can you make a pull request i will test it ?

**Comment by Antifluxfield** [comment]
@Dream-Master Sorry for that I'm just busy fixing my develop environment...

**Comment by mitchej123** [comment]
TCon faucets are trying to input from ForgeDirection.UP which is triggering the canConnect() check.  I'm tempted to patch them to use ForgeDirection.UNKNOWN for gregtech entities which will bypass the connected check.  

Alternatively, their getTankInfo() returns null right now; if it returned an empty tank then I could look into fixing them similarly to transloactors.
