### ISSUE TITLE
Recipe suggestion: Salis Mundis by crushing Balanced Shards in a Mortar and Pestle 

### ISSUE THREAD

**Issue by Goatflakes** [GTNewHorizons/NewHorizons#2414]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
What it says in the title :P

**Comment by WarlordWossman** [comment]
You already are MV when you start with TC and I think balanced shards should be macerator only.

**Comment by Dream-Master** [comment]
You can macerate salis mundus in steam age. Before you definitly not need it. So macerator recipe is fine.
