### ISSUE TITLE
Component Assembler breaking tier system.

### ISSUE THREAD

**Issue by Careface1g** [GTNewHorizons/NewHorizons#2415]
Recipes that use circuits and are able to be made inside the Component Assembler (Component Maker) are some tier below the intended  GTNH recipe as shown in the example:
https://i.imgur.com/5N1sBzh.png
https://i.imgur.com/JUVAQd8.png

GTNH recipe uses ZPM tier circuits for a Tier V Generator while the Component Assembler  uses IV tier.
The machine is absolute since we already have all correct recipes inside the regular assembling machine , suggest removing it or making it uncraftable until the recipes are fixed.

**Comment by Dream-Master** [comment]
recipes disabled.

**Comment by Dream-Master** [comment]
```
// --- LV Component Assembler
recipes.remove(<gregtech:gt.blockmachines:985>);

// --- MV Component Assembler
recipes.remove(<gregtech:gt.blockmachines:986>);

// --- HV Component Assembler
recipes.remove(<gregtech:gt.blockmachines:987>);

// --- EV Component Assembler
recipes.remove(<gregtech:gt.blockmachines:988>);

// --- IV Component Assembler
recipes.remove(<gregtech:gt.blockmachines:989>);
```
