### ISSUE TITLE
Disable manyullyn shapeless recipe

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2417]
#### Which modpack version are you using?
2.0.2.6

So there is this mixer recipe for manylluyn dust:
![2018-01-13_21 50 42](https://user-images.githubusercontent.com/16925725/34909974-56614f38-f8ac-11e7-8e23-f77e11f4ef3c.png)

But I wouldn't wait 20 seconds for it if I can just use this:
![2018-01-13_21 50 54](https://user-images.githubusercontent.com/16925725/34909975-67fcf5e4-f8ac-11e7-9031-b5f365c3a89f.png)

I know that we have some assembler recipes with the same materials but I think manylluyn is not something that needs a shapeless recipe.
So as the title says I suggest to disable the dust crafting by hand.

**Comment by Bluebine** [comment]
There's several dusts like that. The mixer recipe just makes it easier to automate, while the manual recipe doesn't cost energy. It's fine as it is.

**Comment by Dream-Master** [comment]
Its a high tier material so i will take it out. At ebf tier you have a mixer allready.

**Comment by WarlordWossman** [comment]
I think it would be good if more high tier materials you need to combine were in the mixer.
Or at least make the shapeless way give a little less, like 75%.

**Comment by Dream-Master** [comment]
Ok any suggestion which recipes need to be changed? @WarlordWossman

**Comment by WarlordWossman** [comment]
My idea would be putting every dust-mix that is past-LV into the mixer. I think shapeless versions can exist but should have losses. It's a lot of work tho so I am not sure if we want it.

**Comment by Dream-Master** [comment]
Ok i reduce it to 75% in shapeless.
