### ISSUE TITLE
[Quest] Add note to EBF quest, add 2nd EBF quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2418]
Add a note to the EBF quest

Note: Additional input hatches can each store different fluids.

Add a 2nd EBF quest, after nichrome coils

Stainless too slow? Time for second EBF!

Description: 
You can make ingots faster 3 ways - better coils, higher tier energy hatches, or adding more furnaces. It's probably time to add a second EBF to your base.  EBFs can share walls and input/output blocks, but not mufflers or energy hatches.
 Remember pollution will be very high with two EBFs active at once! Watch out for high pollution effects! Use the best mufflers available and don't place the EBFs in the same chunk as any farmland or other high pollution machines like pyrolyse ovens and large boilers.

Req:
1 EBF controller
10 Nichrome coils
EBF casings
1 HV muffler
2 HV energy input hatches

**Comment by LOKKO12** [comment]
I would remove the coils as requirement, when you make a second one earlier/later, you would have to make NiCr coils aswell. For example, i made 2 EBFs at MV, and run them with CuNi coils...

**Comment by Dream-Master** [comment]
Sure i make it not using special coils. Maybe i named it only in text.

**Comment by richardhendricks** [comment]
Changed to MV hatches/muffler and added quest right after first stainless ingot is made.

reward is 2 MV sodium batteries and a 4 slot medium battery buffer and 50 technician coins.
