### ISSUE TITLE
Mining level on specific tools

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#242]
I've noticed some high tier tools such as the vajra and advanced drill from GraviSuite have only mining level up to Tin in NEI.

Shouldn't it be a bit higher for high tier tools as such? (Now I haven't tested them of course, just looked in NEI.)

**Comment by Dream-Master** [comment]
Have to look if i can set mining Level for Tools.

**Comment by Dream-Master** [comment]
https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/152

**Comment by Dream-Master** [comment]
If we not change the code i dont see any chance.
