### ISSUE TITLE
Animal farms Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2420]
Add feathers to the Chicken task.

**Comment by WarlordWossman** [comment]
What about issue #2202 btw?
Comes to mind when you mention animal farms.

**Comment by Dream-Master** [comment]
I like this mechanism back where neutrals mobs attack you when you attack them.

**Comment by WarlordWossman** [comment]
Well that's okay with me if they deal less damage than hostile mobs, was more about the explosion mechanic making neutral mob farms a pain and I would probably try to finish the quest you tweaked with pams animal traps if the explosion nonsense stays @Dream-Master
