### ISSUE TITLE
ZPM Microwave Transmitter

### ISSUE THREAD

**Issue by LOKKO12** [GTNewHorizons/NewHorizons#2421]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Opened NEI, searched for Wireless, saw ZPM Microwave Transmitter called "UV Microwave Transmitter"
![2018-01-14_17 43 41](https://user-images.githubusercontent.com/33183715/34918414-888232ce-f952-11e7-9347-5a4e72c7a6d1.png)
#
#### What do you suggest instead/what changes do you propose?
rename it to ZPM Microwave Transmitter.

**Comment by Dream-Master** [comment]
sure
