### ISSUE TITLE
Add NotEnoughResources support

### ISSUE THREAD

**Issue by TechnicianLP** [GTNewHorizons/NewHorizons#2423]
Could you add ore integration for NotEnoughResources? Would make finding a dimension the ore spawns in much easier ... (i know theres the spreadsheet but ist stupid to search it every time and sometimes even has wrong information)

**Comment by Dream-Master** [comment]
Does it support Gregtech ores? If not it make no sense to add it. @TechnicianLP

**Comment by TechnicianLP** [comment]
"add support" should state the current state - it supports addin ores via imcmessages though (so it wouldnt be that hard to implement)

**Comment by Dream-Master** [comment]
@TechnicianLP sure if you add Gregtech support and test it i could add it to the pack.

**Comment by Dream-Master** [comment]
But so far i know GT ores works different then other mods ores.

**Comment by richardhendricks** [comment]
https://github.com/hilburn/NotEnoughResources

**Comment by richardhendricks** [comment]
Bart added new mod with orevein information.
