### ISSUE TITLE
Windmeter

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2424]
#### Which modpack version are you using?
2.0.2.6
![2018-01-14_22 53 36](https://user-images.githubusercontent.com/35035276/34920116-71213144-f97e-11e7-9bcb-44a890d11a0d.png)
![2018-01-14_22 53 41](https://user-images.githubusercontent.com/35035276/34920117-76264c6a-f97e-11e7-8b58-569f03bf311c.png)
In the description of the quest is not enough 2 Small Stainless Steel Gear.
Also 1 tab was not counted (battery).

**Comment by Dream-Master** [comment]
ok the stainless steel small gears are missing i will add it.
Recipe need a empty battery now. Why batt not was counted ? @CalterOK

**Comment by CalterOK** [comment]
I do not know the reason why the battery did not want to be counted (it was just scrubbed). The fact that the matter in the battery is understood by including the absorption of materials. So he did not absorb the BC only. Quest counted by including OreDist in the battery.
