### ISSUE TITLE
Network Anchor

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#243]
Could be interesting, an [EU powered chunkloader](http://forum.industrial-craft.net/index.php?page=Thread&threadID=8513) with GT recipes.

**Comment by Dream-Master** [comment]
I look inside this mod.

**Comment by Teteros** [comment]
The 1.7.10 fork of the mod also has SeedManager which would encourage the use of underused IC2 crops.

**Comment by Dream-Master** [comment]
Maybe for now i add the Chunkloader and look inside the other mods later.

**Comment by Dream-Master** [comment]
Ok i see it is a pack with all the mods. The problem is the mod ist from September last year. I will test it.

**Comment by Dream-Master** [comment]
I think it won't work with the latest ic2 maybe we have to update the code because Network Anchors with eu would be a nice alternative.

**Comment by Dream-Master** [comment]
Not working game crash with the seed analyzer. The mod is open source.
