### ISSUE TITLE
Seismic Prospector Blocks incorrectly name for LV/MV

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2430]
#### Which modpack version are you using?
2.0.2.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Seismic Prospector blocks incorrectly name:
The LV, MV and HV version of this block have the same title as HV:
"Seismic Prospector HV"

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
I recommend renaming them :)

**Comment by Dream-Master** [comment]
Sure I will rename it.
