### ISSUE TITLE
HV Microwave Energy Transmitter

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2431]
Transmitter HV is available much later than it can come in handy. The problem in the generator for which you need a higher shooting range. I propose to change the prescription of the transmitter that it would be available on the 3rd dash of development, before flying to the moon.
![2018-01-15_18 32 57](https://user-images.githubusercontent.com/35035276/34950448-3f8d30fa-fa24-11e7-9365-37092fda99f4.png)
![2018-01-15_18 33 08](https://user-images.githubusercontent.com/35035276/34950449-40695508-fa24-11e7-8070-9a9c04995245.png)

**Comment by Dream-Master** [comment]
It's only the voltage it used. And no I won't downgrade it in tier.
