### ISSUE TITLE
Weird shapless lapis lazuli block into dust recipe

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2434]
#### Which modpack version are you using?
2.0.2.7

I just got a lapis lazuli block from a dungeon and I found this weird recipe. In fact all of the 9 pages in shapeless are this recipe so it exists 18 times it seems (guess would be because there is colored versions of extra utilities even if they don't show up there)
![2018-01-16_00 11 37](https://user-images.githubusercontent.com/16925725/34965097-e73075ec-fa51-11e7-940a-d546d95e085f.png)
Tested and it works:
![2018-01-16_00 07 19](https://user-images.githubusercontent.com/16925725/34965100-f11ee412-fa51-11e7-87cc-64a91b014274.png)

So I think this is the intended way to turn it into dust (colored versions do get displayed here btw):
![2018-01-16_00 11 54](https://user-images.githubusercontent.com/16925725/34965122-0c5e8516-fa52-11e7-9787-92ff8210a0f2.png)

We should get rid of the weird recipe. I am not sure why it happens in the first place but I will check if similar issues exist when it comes to other blocks extra utilities adds colored versions for and edit this issue if it turns out to be the case.

**Comment by Dream-Master** [comment]
Are there more recipes brocken?

**Comment by WarlordWossman** [comment]
I couldn't double check yet but afaik redstone blocks and glowstone blocks seem to be uneffected.

**Comment by Dream-Master** [comment]
still exist need to fix
