### ISSUE TITLE
2.0.2.7 changed liquid ID's in liquid filter in Steve Machine Manager

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2438]
2.0.2.7
My automated is broken after updated 2.0.2.7, because SFM liquid ID's is changed. (only in SFM)
Example: before 2.0.2.7 filter contained Helium plasma. Now changed to:  Gallium plasma.
![image](https://user-images.githubusercontent.com/29812448/34973772-229b6546-fad5-11e7-84cf-6ecd6f6c9e2d.png)
I manualy changed all wrong liquids to correct liquid.

**Comment by benstuwie** [comment]
2.0.2.6 did that too. Solder became salt water

**Comment by repo-alt** [comment]
I remember the same bug was in Extra Cells, when it was using liquid internal ids instead of names, and they changes every time new mod was added to the modpack, or some mod internal change caused internal id reassigning.

**Comment by Dream-Master** [comment]
@richardhendricks @mutchej123 any idea?

**Comment by 0lafe** [comment]
Uhhhh, bump? Idk, is there anything we can do about this?

**Comment by draknyte1** [comment]
There is no fix.
It's an issue within each mod separately.
