### ISSUE TITLE
Empty Cells destroyed when outputting fluid by hand to Drum (Extra Utilities)

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2440]
#### Which modpack version are you using?
2.0.2.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Empty Cells destroyed when outputting fluid by hand to Drum (Extra Utilities)
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Empty Cell should be returned

**Comment by Dream-Master** [comment]
I guess some Fluid Canister/Tank not working with cells. I think it was before 2.0.2.6 too.

**Comment by Prewf** [comment]
Which liquid were you trying to empty into the drum? Does it happen with every liquid? Personally, I ran into this issue before with water cells into a drum.

**Comment by LOKKO12** [comment]
All cells added by IC2 get consumed AFAIK. @Prewf

**Comment by Dream-Master** [comment]
Ok so i close this now because we cant do anything against it.
