### ISSUE TITLE
Recipe from alloy smelter

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2442]
#### Which modpack version are you using?
2.0.2.5

#### If in multiplayer; On which server does this happen? 
Delta

#### What do you suggest instead/what changes do you propose?
![2018-01-17_01 15 21](https://user-images.githubusercontent.com/13598309/35002271-1b8cb53a-fb24-11e7-84ca-32c777ad2df3.png)
![2018-01-17_01 15 24](https://user-images.githubusercontent.com/13598309/35002272-1bc2d516-fb24-11e7-989d-45334b30b9e8.png)
![2018-01-17_01 15 26](https://user-images.githubusercontent.com/13598309/35002274-1bf9402e-fb24-11e7-9d7f-6cae4f70cbd0.png)
![2018-01-17_01 15 28](https://user-images.githubusercontent.com/13598309/35002275-1c32b32c-fb24-11e7-929d-b0cd62c08340.png)
![2018-01-17_01 15 30](https://user-images.githubusercontent.com/13598309/35002277-1c6abc04-fb24-11e7-92a1-e047f6237f04.png)
Add these recipe to GT alloy smelter. Maybe smth like 30EU/t for 2.5s or 5s.

**Comment by Dream-Master** [comment]
alloy smelter not have 3 inputs.

**Comment by Dream-Master** [comment]
for fused quartz

**Comment by noobyaran9** [comment]
Its ok. Just make them take the amount they require in the original recipe like fused quartz where it takes 2 quartz dust and 1 glass dust.

**Comment by Dream-Master** [comment]
No why. Why i change recipe to take them back as they where before i change them ??

**Comment by noobyaran9** [comment]
I mean from the picture i posted. like 1 fused quartz takes 2 quartz dust and 1 glass dust.

**Comment by noobyaran9** [comment]
Just add these recipe to gt alloy smelter.
2 certuz quartz dust + 1 glass dust -> 1 fused quartz
2 nether quartz dust + 1 glass dust -> 1 fused quartz
1 fused quartz + 4 glowstone dust/1 glowstone block -> enlighthen fused quartz
1 quite clear glass + 4 glowstone dust/1glowstone block -> 1 enlighthen quite clear glass
1 fused quartz + 4 black dye of any kind -> 1 dark fused quartz
1 quite clear glass + 4 black dye of any kind -> 1 dark quite clear glass
Recipe maybe set them to take 30eu/t at 2.5s or 5s
They are the exact same recipe that takes the same amount of resources but in GT alloy smelter. If u wanna disable the alloy smelter from EiO after adding these recipe its also fine. Since apart from these recipe, its not used for anything else and its stupidly slow even with octadic capacitor.

**Comment by noobyaran9** [comment]
![2018-01-25_11 40 21](https://user-images.githubusercontent.com/13598309/35369758-903cc400-01c4-11e8-9d84-bd7f9308cfbf.png)
Alloy smelter won't craft when there is only 2 items that it needs although it has the right amount (1 glass dust + 1 quartz dust + 1 quartz dust)

![2018-01-25_11 40 26](https://user-images.githubusercontent.com/13598309/35369759-90827536-01c4-11e8-945c-b4f44a0a7a19.png)
You need to split them up like the picture above, but it takes 2 from only 1 slot which in the end will leave the other slot full of the item and stop crafting, jamming up the slot.


I recommend just adding all the recipe from alloy smelter from Ender IO into GT alloy smelter and disable the Ender IO alloy smelter.

Recipe list (uses the exact same amount from the current ender IO alloy smelter recipe):
2 certuz quartz dust + 1 glass dust -> 1 fused quartz
2 nether quartz dust + 1 glass dust -> 1 fused quartz
1 fused quartz + 4 glowstone dust/1 glowstone block -> enlighthen fused quartz
1 quite clear glass + 4 glowstone dust/1glowstone block -> 1 enlighthen quite clear glass
1 fused quartz + 4 black dye of any kind -> 1 dark fused quartz
1 quite clear glass + 4 black dye of any kind -> 1 dark quite clear glass
Recipe maybe set them to take 30eu/t at 2.5s or 5s

Only 1 recipe is missing but thats fine because that recipe is 
1 glass dust + 1 nether quartz dust + 1 certus quartz dust -> 1 fused quartz.
There is already 2 recipe for fused quartz as above, so it doesn't really matter if this recipe does not exist.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/d3d9cb7f4d5e1c3223166ec5ce97cd1d80fe3cf9
