### ISSUE TITLE
Steam rebalance discussion

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2443]
I am starting to think switching my EBF to steam was a mistake.  

I have a large steel boiler (24k/s), and it can't put out 1 HV A with small rotors (24k * .8 / 20 / 2  = 480 EU/t). It barely can with larger rotors, but those require titanium rods, but can be done in an HV assembler. Anyone else think it needs rebalanced?  

For all the infrastructure charcoal+steam requires, I'd expect it to at least provide a couple of amps of the appropriate power level. The bronze boiler can provide 640 EU/t, or 2.5 MV amps.  MV-> HV requires 4x the EU.  The bronze->steel boiler upgrade only gives you 50% more steam. Even if the normal size rotors are used (maybe blue steel or dark steel instead?), they only provide (24k * 1.05 /20/2 = 630 EU/t, or 1.23 HV Amps. Small rotors only give (24k*.80/20/2 = 480 EU/t or .94 HV Amps)

Is the only answer to build 2 large boilers and scrounge titanium until I get on the moon? That doesn't seem reasonable compared to using diesel - that only requires upgrading one line instead of multiplying every line, including tree and charcoal production. Also, power production upgrading is something you'll need early in the tier, not towards the end IMO, so it should require materials from early in the tier.

It makes better sense to me to have the upgraded boiler + the upgraded turbine rotor provide ~ the same number of amps as before.  At a minimum, if bronze + small = 2.5A MV, steel + normal = 2.5A HV, tungstensteel + large = 2.5A EV. 

Leaving the steam alone, the turbine rebalance would be 
small - 80 - 2,5 MV amps, 3 small turbines @ MV dynamo (bronze)
normal - 215 - 2.5 HV amps @ 24000L/s, 3 normal turbines @ HV dynamo (steel)
large - 640 - 2.5 EV amps @ 32000L/s (titanium)

This would still require 3 output turbines per tier to get the full 2.5A output. 

Considering the hassle it is, I actually think 4A output per tier is fairer.  That way 1 boiler + 3 turbines can power 1 EBF at the same tier. 

There is an argument that as you tier up, you need less amps since you will mostly use prior tier machines, I guess. Up to at least HV I want to have high-tier machines for speed that are also high-current consumption - electrolyzing, thermal centrifuge, and EBF. Because of the overclock mechanics, high EU recipes at a tier stay high EU recipes as you increase tier. 120 EU/t at MV becomes 480 EU/t at HV, but is only twice as fast. So I think keeping the number of amps at 4A up to HV/EV is reasonable.

So, three topics:
1. Should the output for the combined boiler + turbine blade for a tier scale together?
2. How many amps should the output be per tier? 2.5A or 4A?
3. Should the turbine rotors for a tier use resources available at the start, middle, or end of that tier?

**Comment by LOKKO12** [comment]
IMO Steam should be only a Early Game Power source, for Steam Tier, LV and maybe MV. It should scale really bad to higher tiers. No rebalance needed here.

**Comment by richardhendricks** [comment]
So you feel the progression is steam -> diesel -> cetane -> nuclear/high octane?

I prefer multiple viable options at each tier if possible.  This offers more gameplay and creative tension.  It allows players to choose to settle near oil spouts, or to develop large charcoal farms.  It also allow for replayability - maybe one time you do oil, but next time you do steam.

Reducing it to just one solution just seems arbitrary and limiting.

**Comment by richardhendricks** [comment]
On top of that, upgrading fuels for diesel gens benefits every generator, which is a big plus.

**Comment by richardhendricks** [comment]
Along with no warmup or wasted fuel if there is no demand.

**Comment by richardhendricks** [comment]
Don't forget, as it's balanced right now, 1 steel boiler can't even feed a single MV EBF.

**Comment by Bluebine** [comment]
You can always just build a double steel boiler, which lets you feed an MV EBF with steam to spare. 4 titanium boilers will feed an HV EBF, and I think that really SHOULD be the limit of standard boilers- diesel falls off at EV too, pretty much requiring you to use a more advanced power source.

**Comment by Prewf** [comment]
I don't think this is a steam issue, but rather an issue you have with the large boiler. A fluid reactor design also has steam output, but at an insanely higher rate than a boiler, which is something that makes sense to me. A completely renewable resource like charcoal and a boiler made purely out of steel (an easy to acquire, lv tier resource) should have a limit to how well it can scale up.

**Comment by richardhendricks** [comment]
It's not purely made of steel, it requires MV level for the circuit processing. 

@bluebine OK, so for an MV EBF, you can do 4 diesels pretty trivially. I did before just fine.  Or 2 forestry farms + 2 pyros or 3 advanced coke ovens  to make charcoal + 2 steam boilers + 6 steam turbines + 6 replaceable rotors.  That's not balanced.

**Comment by Bluebine** [comment]
@richardhendricks Okay, I think you're exaggerating a little bit there. First off, you only need 1 pyrolyse/advanced coke oven unless you're trying to run an EBF 24/7, which would consume an INSANE amount of diesel that way. Secondly, you didn't mention all the processing you need to do to make diesel, which requires 4-5 machines at least just to make light fuel. Third, you need 4 small turbines, not 6, which don't use rotors, unless you're trying to use large turbines, which you should only need 1 of, and you don't need to anyways.
Steam only really gets annoying to use at EV+, which is where diesel gets annoying to use, so I think it's all fair enough that diesel lasts a LITTLE longer than steam does. And with LHEs, you can probably get much more steam power, although I don't really use them myself.

**Comment by Prewf** [comment]
There's also the difference in technology behind each type of energy source. Diesel is a more compact, dense form of energy compared to burning coal. It's why we don't have a coal boiler running our cars in real life nowadays. I don't know..to me, it makes sense that diesel scales better in terms of resources/infrastructure. And as civilization streamlines making diesel, it becomes slowly more cost inefficient to try and power things the "old" way (like burning coal). That's how I see it anyway.

**Comment by Dream-Master** [comment]
I think steam need a buff mid late game

**Comment by richardhendricks** [comment]
Wait, let's stop moving the goalposts.  1 MV EBF.  Needs 4A of MV power to run. I am not talking 24x7 per se, but it should be able to do a few stacks at time, and with some ingots taking 100s, that's effectively 24x7 since other wise would require massive battery banks, which would have to recharge anyways.

The reason I said 6 large steam turbines is that I was assuming using cobalt blades.  I see now that vibrant alloy or manyullyn blades can provide an efficiency and steam throughput boost for HV.  So that does help with the infrastructure requirements and gets up to 600 EU/t off one steel boiler with small rotors using manyullyn.  So that's OK I guess, but I still think that scaling the boilers + the rotors together for each tier is necessary.  The advantages for diesel over steam are otherwise so great there really isn't much point to steam beyond LV. I haven't looked in detail at the new diesel requirements, but the fluid throughputs still seem pretty high over time - which is fine IMO for diesel but it just highlights how bad steam is.

@Prewf Sure we burn diesel in cars because of energy density per unit of fuel (including water).  But in real life diesel generators aren't use for primary electrical power production beyond small use cases.  Clearly coal scales better at the type of volumes used in real life (running a city). So it makes sense to use coal/charcoal for large scale in-game as well.

**Comment by Prewf** [comment]
@Dream-Master If you do end up buffing steam, I'd also like to (shamelessly) add: please also buff the Large Heat Exchanger output. I'm a little sad it's staying at 5x.

That being said, I'll reiterate that the issue isn't steam itself. Steam and large steam turbines are actually excellent and scales well. The "issue" is methods to generate steam. Burning coal shouldn't be viable past  HV at most. 

@richardhendricks Well, we're not really running a city in minecraft. You're talking about powering a couple of machines at every tier, so the small use case for diesel kinda fits here in my opinion. Also don't forget there's the alternative of going with nuclear power in real life. Objectively cleaner and more energy dense than coal, assuming it's responsibly handled. It fits well with how EV tier introduces you to nuclear power->steam.

**Comment by richardhendricks** [comment]
Yeah but the machines at each tier don't necessarily all use the same requirements, on average.  High-EU recipes are always high-EU at *every* tier due to overclocking.  If you need 30 EU 1A, you will always need 94% of 1A at every tier level, no matter how high you go (120EU@MV, 480EU@HV, etc). It matters most for the machines that are usually the slowest, like the EBF and thermal centrifuge. Sure other machines can be run at lower tiers in most use cases, but EBF and thermal centrifuge is where time hurts the most, at least pre-EV.

**Comment by Methes** [comment]
Right now I didn't even think twice about using GT Boilers.
Just use several max size Railcraft LP ones.
Uses only iron (not steel), each boiler produces 720mB/t with no pollution.
Can easily scale up to 2k EU/t even with HV Steam Turbines (no maintenance needed).
GT Boilers are useless compared to that.

**Comment by richardhendricks** [comment]
That's less than even the Large Bronze Boiler. So yeah, great if you have the space etc.  Also, how efficient is it? The larger boilers are more fuel efficient as well.

**Comment by Prewf** [comment]
It's true that it's less output, but the pros are that it only needs iron to make and doesn't generate pollution, running off a renewable energy source (albeit, a LOT of coal). GT boilers are technically way more efficient per coal, but the materials you need to make that boiler (titanium...tungstensteel!?!?) don't make it worth it in my opinion.

A small array of railcraft LP boilers is actually what I used to run my HV line the last time I played GT (gt5u) minecraft with my friends. I had a 2x2 chunk jungle tree farm with about 8-10 thaumcraft golems powering it all. Could've easily scaled it to EV too since my base was in the sky (all the room in the world!). I can't imagine doing that in this pack though in LV/MV since RC boilers eat so much coal per second and handling that much coal in LV/MV tier would be...too much. Not to mention the water usage without something like an ender io reservoir (HV tier) or other infinite water source makes this near impossible until you hit HV.

**Comment by Bryfer** [comment]
After seeing what people write in #help I came to this conclusion
People are lazy and believe steam should give them EV+ energy.
This is where nuclear and superheated steam comes in.

*Do not edit steam unless there is better arguments for it.*

(I haven't read the entire thread on github yet. So might add another comment later.)

**Comment by richardhendricks** [comment]
Everyone seems to feel steam is fine . Closing ticket.
