### ISSUE TITLE
Nonuple (and possibly quadruple) pipe not working

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2447]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Tried to make a long-ish pipeline with nonuple pipes, about 80 blocks long.  Input hydrogen, nitrogen, and water, expected entire pipe to be filled with all three.
#
#### What happend instead? (Attach screenshots if needed)
Nitrogen filled the pipe completely (it was inserted first).  Then, hydrogen and water show up in the pipe for about 5 blocks, then slowly get less and less filled for about 5 more blocks, and then completely disappear.  The pipe doesn't seem to be updating at all.  There is no sloshing, all of the liquid quantities on the WAILA tooltip stay static.  I can't extract anything except nitrogen from the other end.
#
#### What do you suggest instead/what changes do you propose?
Fix the pipe so that it works.

**Comment by Antifluxfield** [comment]
I think I know what's wrong...

**Comment by bartimaeusnek** [comment]
@Antifluxfield then say it lol or add a pull request if you already fixed the code 😉

**Comment by Dream-Master** [comment]
we using this code first 
https://github.com/GTNewHorizons/GT5-Unofficial/commit/d217169405d84fb3e6fd182b49f04adc1c48dbca

if this work we good otherwise we will try antiflux pr.
