### ISSUE TITLE
Update turbine rotor tooltip to reflect danger, and/or update large turbine to include fluid regulator

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2449]
Turbine rotors tooltip need to include warning to not exceed dynamo output or else it will explode.

Alternative, and my preferred solution - update large turbine controller mats to include an MV or HV  fluid regulator, and change the code so that the turbine will only consume the maximum steam for the output dynamo to generate 1A.

https://github.com/GTNewHorizons/NewHorizons/issues/2446

**Comment by richardhendricks** [comment]
As a balancing factor, excess steam beyond the EU/t needed for the output dynamo could be output from the front face, similar to the work output for steam machines, including harm to mobs.

**Comment by richardhendricks** [comment]
Update tooltip to read:

EU/t instead of L/s  for steam (include equation to calculate steam L/s: (EU/t) * 40 / Turbine Efficiency )
Add a line up top - Throttle fluid flow to the turbine using fluid regulators. Do not exceed the EU/t of the output dynamo!

**Comment by richardhendricks** [comment]
Update turbine controller output and/or tricorder readings to show average EU/t throughput.

**Comment by benstuwie** [comment]
I feel like a lot of the turbine tooltip needs an update, including this. I agree. They also don't really help with plasma injection rates. You can't just fill a hatch and get full efficiency, it needs a very specific rate of fuel that's not really listed anywhere. I think scanning the controller shows it, but that's it. It took me and a friend about 6h of testing different turbine things to get it to finally work. Things that should work don't, like sfm/fluid regulators.

**Comment by WarlordWossman** [comment]
Def +1 for this idea and I also like the idea of having the regulator in the recipe. In minecraft you assemble parts yourself and don't buy them from a company so you could easily build a regulation that makes only up to what the dynamo can handle.

Our pack is technical but explosions are unforgiving and not fun.
People will either test for hours in creative or not use the turbines, pretty much the definition of wonky game design!

**Comment by Anarack** [comment]
Steam numbers has to stay in L/s due to steam and super heated steam having different EU values, or things get more annoying as you no longer use the one to one ratio for turbines in reactor setups. 

Plasma/gas you can get the fuel optimal flow value from the tool tip, all you need is the plasma/gas value and less math than you need for the reactor anyway.

**Comment by richardhendricks** [comment]
So steam and superheated steam both use the same flow rates? I'd rather list superheated steam as a separate fluid line like plasma etc instead of tying them together.

**Comment by Anarack** [comment]
A super heated steam turbine outputs the same amount of steam that is put into it. Mainly its there to make turbine math around the large heat exchanger less of a pain, assuming it doesn't get changed again, so it does use the same flow rate.

**Comment by richardhendricks** [comment]
Sample current turbine tooltip.
https://cdn.discordapp.com/attachments/234936569360809996/403119250107006976/unknown.png

**Comment by Anarack** [comment]
Are we missing a comma or something in the lose flow option? Otherwise i'm not sure why it is almost 8 times the optimal flow value.

**Comment by Prewf** [comment]
I really like the idea of putting a fluid regulator as part of SOMETHING on the large steam turbine. It's so integral to using a large steam turbine that this should be a thing. I don't know if it should be the controller block though, since that's something that should stay static at all times. I don't want to have to make a controller block every time I decide to change my optimal flow amounts around different tier voltages. 

Perhaps a special input hatch, like a Fluid-Regulated Input Hatch? Just like other input hatches, it'd be "tiered" and the tier determines what level fluid regulator it's using.

**Comment by richardhendricks** [comment]
Ah, this is relevant.

https://ftb.gamepedia.com/Large_Turbine

I think that explains why I am not seeing the full 512 Eu/t even though I am sending the correct amount of steam.  I am losing some EU due to flow rate efficiency on my Vibrant Alloy normal size turbine.

@Anarack The flow rate is much higher, but your efficiency is much lower to compensate.

**Comment by richardhendricks** [comment]
@Prewf My mats change for the recipe would not scale with tier, the fluid regulator would just always be whatever.

I do think the idea of a fluid regulated input hatch is interesting, but changes to GT5U at that level is out of scope IMO. Suggest it for GT++ or TecTech. :smile:

**Comment by CalterOK** [comment]
At the moment in gas multi-block turbines it is possible to install several inch hatch, for supplying different fuel with different optimal flow. If you implement this plan, how do you plan to realize this moment?

**Comment by richardhendricks** [comment]
Well, we will probably just rewrite the tooltip since the community seems pretty even on whether or not it is fun to have exploding turbines.
