### ISSUE TITLE
New crossbow bolt quests cannot be completed

### ISSUE THREAD

**Issue by Paolkageist** [GTNewHorizons/NewHorizons#2451]
#### Which modpack version are you using?
2.0.2.6

#
#### If in multiplayer; On which server does this happen? 
N/A

#
#### What did you try to do, and what did you expect to happen?
I tried to create the iron bolt using the components from the Tier 1 Iron Bolts quest (wood tool rod w/ iron tip + ghostleaf fletching) and the recipe could not be completed in the tool forge.  I completed all of the previous steps successfully.  

![image](https://user-images.githubusercontent.com/9247381/35072981-1b97a6a4-fba4-11e7-9347-2273d1ad7496.png)

I also tried making the Magnalium Bolt in step 5 of the Tier 2 Magnalium Crossbow Bolts quest but there is no way to get an iron-tipped magnalium bolt. I tried putting the magnalium tool rod in a casting table and pouring molten iron on it, and tried to put a magnalium tool rod in a fluid solidifier with 144 mb of molten iron, and neither of them worked.  The recipes do not show up in NEI either.  

![image](https://user-images.githubusercontent.com/9247381/35073139-d8a47af6-fba4-11e7-8cb3-3d807e1e12a9.png)

#
#### What happend instead? (Attach screenshots if needed)
The items needed for the quest steps do not have recipes and are not created.

#
#### What do you suggest instead/what changes do you propose?
Add recipes for the tool forge that allow a crossbow bolt to be created with Natura ghostwood fletchings, and add a recipe either to the TiCo smeltery or to the fluid solidifier to create iron-tipped magnalium bolts.

**Comment by Bryfer** [comment]
Can you include quest IDs?
Hold shift while hovering over the quest to see quest IDs

**Comment by Dacryphile** [comment]
Iron Bolts quest is #1156 (step 4 can't be completed

Magnalium Crossbow Bolts quest is #1154 (step 4 can't be completed).

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
@Dacryphile 
try to use molten iron from tc

**Comment by Dacryphile** [comment]
With the TiCo smeltery? Or extract the molten iron from the smeltery into a fluid solidifier?  I tried the smeltery with iron and a casting table and it didn't work for the magnalium bolt.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35173491-e85e5d18-fd6b-11e7-9db6-be4551068770.png)

**Comment by Dacryphile** [comment]
That worked for the Magnalium bolt, but I still can't get the final bolt in quest 1156 to create.  I tried putting a wooden tool rod in a fluid solidifier with molten iron from TiCo, and with regular molten iron from GT, and neither of them worked.  I can put a wooden tool rod on a casting table and have it pour molten iron on it, but I can't combine that bolt with the ghostwood fletching to make the final bolt.  

![image](https://user-images.githubusercontent.com/9247381/35179664-cc1b5526-fd5b-11e7-8908-8f1c130a1a11.png)

![image](https://user-images.githubusercontent.com/9247381/35179668-dc90df2a-fd5b-11e7-9265-a396f96738f5.png)

![image](https://user-images.githubusercontent.com/9247381/35179672-e968b650-fd5b-11e7-8923-9daee5bfdf0b.png)

**Comment by Dream-Master** [comment]
Will check again

**Comment by BenJMcDonald** [comment]
I ran into this same issue today in version 2.0.2.7 .  The Tinker's Construct tool forge didn't recognize the Ghostwood Fletching from Natura as a valid fletching for the bolts.  I decided to just use a feather fletching to finish the bolts, and that satisfied the quest.

**Comment by EvgenijM86** [comment]
Can you at least write somewhere in quest text that you need to use iron from TiCo smeltery? Currently it does not even mention material of the bolt tip. I am talking about Magnalium Crossbow Bolts quest.

**Comment by richardhendricks** [comment]
What do you mean, iron from the smeltery?  As far as I know, you have to use the fluid solidifier to get bolt tips?

**Comment by BenJMcDonald** [comment]
Pouring iron from the smeltery directly onto a bolt shaft will put a tip on it.

**Comment by Dacryphile** [comment]
It will put a tip on it, but it doesn't work to complete the quest.  You have to pump the molten iron from the smeltery into the fluid solidifier to make the correct shaft/tip.

**Comment by EvgenijM86** [comment]
richardhendricks, I mean, that you pour iron from smeltery inside a liquid container (like a pipe), then use Universal Fluid Cell on that container to get TiCo molten iron. You then go to Fluid Solidifier and pump that TiCo molten iron inside of it. That way it works.

If you use Fluid Extractor on iron ingot - it does not work.
