### ISSUE TITLE
RFC: Massaging oreveins in "high" regions

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2454]
One side effect of the current orevein method is that it biases against oreveins being visible on the sides of mountains or hills with exposed stone.  

Proposal
- Check the four corners of a chunk, if at least two of these blocks exists between 100-110m (cobble, stone, hardened clay, dirt, sand) chunk is considered a "high altitude" chunk.

Effects of being a "high altitude" chunk
- Oreseeds generate at 100% vs 75% (default) - chunks near mountains are more filled in with ores.
- If a chunk is a high-altitude chunk, then instead of checking for nearby veins within 3 chunks, check within 6 chunks. Generate those oreveins with double the size from the RNG. Orevein density will still decrease with distance from the vein.  So a chunk at maximum distance from a seed will have a low ore spawn density.  But it will likely be visible from the exterior if the stone isn't covered by cobble/clay/sand/dirt.
- Optional: Only affect veins above a certain height, ie if the vein is above 100m.  Or not?

Pros
- More veins in high altitude areas
- high altitude veins more likely to seen in the exterior
- Mountains will be more interesting instead of just places to mine clay
- Will give options for placing veins that are useful for players, but shouldn't be more widespread, but are semi-localized, such as fluorine sources.

Cons
- Slowdown chunkgen to calculate heights doesn't seem like it will matter much, only touching a few blocks per chunk.
- slowdown chunkgen to calculate fatter oreveins will probably impact oregen in high altitude chunks, but since density will be low far from oreseed, probably not much?
- hardened clay, cobble, snow covers large percentage of tall mountains, makes it hard to see veins that far up anyways.

**Comment by richardhendricks** [comment]
This effect would only apply to Overworld and Twilight Forest for now.

**Comment by Dream-Master** [comment]
Salt veins are visible too and magnetite veins.

**Comment by WarlordWossman** [comment]
Sounds like a good idea, maybe tin might actually be a vein you find then.

**Comment by richardhendricks** [comment]
Salt and magnetite are visible because the algorithm tries to place the ores from the bottom-up.  But an orevein seed inside of a mountain is not likely to place any ore in a chunk that is just outside the seed.

This picture might help.  In this situation, chunk C has been requested. The algorithm first tries to place the high-altitude vein Tin, but since chunk C is completely air, the vein is rejected and a re-roll done on the table, getting the Gold vein further down.  So the side of the mountain is now empty when it could have had something.

```
        |        |        |  
_-_-_-_-|        |        |  
        |-_      |        |  
        |  _-_   |        |  
  Tin   |     _  |        |  
        |      _ |        |  
        |       \|        |  
        |        |\       |  
        |        | |      |  
        |        | |      |  
        |        | \      |  
        |        |  \     |  
        |        |   |    |  
        |        |   |    |  
        |        |   \    |  
        |        |    --  |  
        |        |      --|  
        |        |        |--------
  Gold  |        |        |  
        |        |        |  
   A        B         C         D
```

It is possible to get veins on the side, but only on the far side from where the generation comes.  For example, if the player is coming from the left, chunk A (or something left of it) would be requested first, and the Tin would actually place.  But because of biases, only 1/2 of the mountain could potentially have exposed veins.

The way the by-chunk generation code works, it only searches 2 chunks away by default (5x5 chunk area). What I'll do is make it so that if a chunk is determined to be 'high altitude' (1 or 2 out of 4 corner blocks is above Y=100 and is stone/cobble/sand/dirt/clay), it will search 5 chunks away for oreveins (11x11 chunk area).  The worldgen config for these veins would be set to have larger sizes so that they are wider by default (since the RNG is 0 to Size, it should be OK to make the Size much wider. The maximum a vein could be is 11x11). This way it limits potential performance impacts to a fairly small portion of the map.  The vein density will still decrease further from the center, down to 1, so there won't be a huge increase in resources, just a few sprinkled on the edges of the vein.

And changing the orevein spawn rate from 75% to 100% will help to populate mountains as well.

So there will be more veins in general in mountains, and the high altitude veins will be more visible because of their size.

While their chances of spawning is pretty high, there are still lots of low veins to compete with.  Once I have a preliminary version setup, I'll do some testing and we can decide if the effect is worth it and we like the way mountains look.

Then we can create new high-altitude oreveins for people to complain about not finding. :)

**Comment by richardhendricks** [comment]
BTW, I did some testing, and it seems like 'mountains' biome doesn't correlate at all to where mountains are located on the map, this is why I wanted to do height calculations instead.  I didn't check the MOUNTAINS tag in BoP though.

https://github.com/Glitchfiend/BiomesOPlenty/blob/8dc8f466d7b5430e9ab69cefc78c27cc20064a48/src/main/java/biomesoplenty/common/init/ModBiomes.java#L391
