### ISSUE TITLE
Ore generation mismatch between dimension and orevein

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2456]
There are two places where ore mixes can be disabled, the orevein and a separate Dimension grouping.  The iron mix is disabled for the Nether and the copper mix is disabled in the Twilight Forest.

Please verify if this is correct and update worldgeneration.cfg so both match.  

orevein for iron has it enabled in the nether, dimension has it disabled. 

MineAnPlay's spreadsheet shows copper enabled in the Twilight Forest, but it is disabled in dimension group.

**Comment by Dream-Master** [comment]
Will check
