### ISSUE TITLE
titaniumtetrachloride recipe + quest bugged (2.2.5)

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/NewHorizons#2457]
#### Which modpack version are you using?
2.2.5
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
make titaniumtetrachloride for quest #860. Expected to use carbon since it's asked in quest.
#
#### What happend instead? (Attach screenshots if needed)
recipe don't use carbon and produce carbon monoxide cell out of no cell nor carbon
#
#### What do you suggest instead/what changes do you propose?
fix recipe

**Comment by Dream-Master** [comment]
Fixed allready

**Comment by Dream-Master** [comment]
Fixed in 2.0.2.7
