### ISSUE TITLE
2.0.2.7 Client unable to load properly after two fresh installs

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/NewHorizons#2459]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft (And singleplayer)
#
#### What did you try to do, and what did you expect to happen?
Attempting to start up the pack, load to Start screen and join server or singleplayer.
#
#### What happend instead? (Attach screenshots if needed)
Fresh install works fine once, second launch of pack hangs on Nuclear Control loading in Phase 3
#
#### What do you suggest instead/what changes do you propose?
I don't know enough

**Comment by Dream-Master** [comment]
Post every log here.

**Comment by Lithorn** [comment]
Game output log 
https://pastebin.com/RQrK39wi

Launcher Log
https://pastebin.com/xhghKiRi

**Comment by Dream-Master** [comment]
@Lithorn try with NC 2.4.3a and report here if this works.

**Comment by Lithorn** [comment]
Worked for several runs without issue. Seems the issue has resolved itself or atleast has not occured again. Then again I have not unloaded the minecraft pack in a few days >.>;

**Comment by Dream-Master** [comment]
@Lithorn can we close the issue?

**Comment by Lithorn** [comment]
Go ahead, guess its just a fluke
