### ISSUE TITLE
oil drilling rig stopped working properly

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/NewHorizons#2461]
#### Which modpack version are you using?
2.2.7
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
oil rig stoppedworking properly after patch, worked for weeks with no problem before.(2 oil drilling rig II, if that matters)
#
#### What happend instead? (Attach screenshots if needed)
when enabled, rig will work for ~10 sec or so, producing heavy oil. it will use 3 mining pipe, wait a bit then take them back and stop. they are fully powered and have no maintenance problem.

screen of the prospection book: 
![oil prod issue](https://user-images.githubusercontent.com/12732004/35149440-56f14e58-fd16-11e7-91f4-e748a2e75a1b.PNG)

#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by MakinToge** [comment]
I'v put an activation cover on the controller and a redstone torch under it to force constante activation.
One rig II produced around 127 L of heavy oil in 2.25 . Same rig now produce  around 1252 L per second : 
from 2032 oil each 16 sec to 1936 each 0.75-0.85 sec (couldn't mesure the time precicely. (31 operation in 39 sec)

**Comment by Dream-Master** [comment]
@MakinToge is this still an issue or is this resolved ? Oil rigs need more power then before.

**Comment by MakinToge** [comment]
Still an issue, since my solution is just a work-around. Tested in ssp and oil rig worked with no problem. 

Strange thing is the prospector scanner tell "Found nothing of interest" but seismic prospector detected 10L oil. But that might be just me making some asumption that those two things should give the same result.

**Comment by codewarrior0** [comment]
Saw something like this right after the update that rebalanced the oil rig. Rig would extend pipe, then draw it back and stop working. But while extending the pipe it would still pump oil, even though it should only give oil after the pipe is fully extended.

It stopped doing this after I picked up the oil rig controller and put it back down again.

**Comment by Dream-Master** [comment]
We change only pump speed.

**Comment by Dream-Master** [comment]
@Technus did you change anything that can cause this issue ?

**Comment by MakinToge** [comment]
As codewarrior0 said, replacing the rig controller fixed the issue so I guess it's just a temporary bug from transisionning from 2.2.5 to 2.2.7

**Comment by richardhendricks** [comment]
Oil rig chunk detection logic has been reworked.  It was causing Concurrent Modification Exceptions when trying to remove near-empty chunks.  Please try with next release (2.0.5.0)
