### ISSUE TITLE
weird seismic prospector behavior

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/NewHorizons#2462]
#### Which modpack version are you using?
2.2.7
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
use an LV seismic prospector at y:6, couldn't insert data stick.
#
#### What happend instead? (Attach screenshots if needed)
Tryed at the top of my base, same x & z but y:160, working with no problem
#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by Dream-Master** [comment]
Y6 make no sense. You touch bedrock .

**Comment by MakinToge** [comment]
Wanted to scan for oil and my oil rig are at y 7 or 8 to use less mining pipe, so I put the prospector near them. It's not an urgent issue but it still one. I don't know the minium y for the prospector to work and can't test in creative since my game crash each time I try to play ssp...

**Comment by Dream-Master** [comment]
So your sp game is unplayable? @MakinToge

**Comment by MakinToge** [comment]
yes, Loading appear for some time then the application close and I'm back to technic launcher. Did that since 1.5 . Did not try for 2.2.7 yet. It's anoying to have to relaunch the pack.

**Comment by Dream-Master** [comment]
log and/or crashlog would be nice @MakinToge

**Comment by MakinToge** [comment]
Well I'm not crashing anymore so I guess the issue was resolved around 2.2.0 or something. I'll try the prospector y lvl

**Comment by MakinToge** [comment]
the issue don't appear in ssp, will try to reproduce on epsilon

**Comment by Dream-Master** [comment]
Epsilon is on 2.0.2.7. So guess it is fixed or gone. @MakinToge let me know asap what happend

**Comment by MakinToge** [comment]
Got the issue on epsilon after 2.2.7 . Did another try, the seismic prospector didn't work at y 6 and y 10 but worked at y 30.

**Comment by Dream-Master** [comment]
In sp the same issue ? @MakinToge

**Comment by MakinToge** [comment]
No, sp is fine.

**Comment by Dream-Master** [comment]
@technus any idea on this ?

**Comment by richardhendricks** [comment]
Seismics work in 5.1. Seismics will only detect ore blocks below their current location.
