### ISSUE TITLE
[Suggestion] IC2 Reactor recipe change

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2471]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
When I tried to craft the IC2 reactor I noticed that it required 8xPlatinum cables which is IV tier
The Reactor itself is EV tier, and using these cables makes you enter IV tier before you are able to craft these cables.
![image](https://user-images.githubusercontent.com/22825059/35182620-cfe65b56-fdd8-11e7-840c-af153d8a0d6f.png)

EV tier cables require Molten Rubber, IV+ uses other liquids/items

#
#### What do you suggest instead/what changes do you propose?

Replace the 8x Platinum Cable with an IV-EV transformer so its easier to make the IC2 Reactor in EV tier

**Comment by Bluebine** [comment]
The platinum cables aren't actually hard to craft at EV though. You just need platinum foil and some silicone rubber, which isn't actually hard to make- some HCl+methanol or chlorine+methane, some silicon, and some water is all you actually need, you just need a LOT of them to mass-produce it.

Also an IV-EV transformer needs tungsten cables... which not only require the advanced cables, but require an IV MATERIAL, of tungsten, so it'd be even worse to craft.
The recipe shouldn't be changed.

**Comment by Bryfer** [comment]
I just realized how big of a derp this suggestion is considering even that transformer needs an IV cable as mentioned 
Not sure what I was thinking there.

Revert it back or do you have any better suggestions?

**Comment by codewarrior0** [comment]
I'd leave it as is. In this pack, the reactor is on the same power level as the Large Combustion Generator, which while being made mostly of Titanium (EV tier), requires a single insulated TungstenSteel Cable (IV tier) to craft.

**Comment by Dream-Master** [comment]
Ok I close it now and leave it like it is 😀
