### ISSUE TITLE
Server crashes upon joining

### ISSUE THREAD

**Issue by Natedog85137** [GTNewHorizons/NewHorizons#2478]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
A friend's private server
#
#### What did you try to do, and what did you expect to happen?
Server was working as normal before. I saved the world before he restarted his pc due to a unrelated issue. 
#
#### What happened instead? (Attach screenshots if needed)
Upon rejoining the server it completely crashes, giving me an error message and creating a crash log in his server folder here
[crash-2018-01-20_22.34.27-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1649567/crash-2018-01-20_22.34.27-server.txt)
Everyone else can join in fine but me
#

**Comment by Namikon** [comment]
Looks like a solid chunk corruption to me. All you can do is to roll back to an older backup. If you know your location (x and z coordinates ) you can try to roll back just the affected mca file

https://dinnerbone.com/minecraft/tools/coordinates/

**Comment by Dream-Master** [comment]
@Natedog85137 any news here otherwise i close this now?

**Comment by bartimaeusnek** [comment]
please replace the berries++ version 1.1.1c with the newest, 1.1.1d. #2458 might happen to your server aswell.
