### ISSUE TITLE
Fluid Filter Cover doesn't work

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2479]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Use a fluid filter cover on a pipe.  This is especially relevant with the nonuple/quadruple pipes, but it doesn't work on normal pipes either.
#
#### What happend instead? (Attach screenshots if needed)
The fluid filter cover doesn't actually seem to filter anything.  You can set it to a fluid by right clicking on it with a cell (but only directly facing the cover, not if it's already attached between 2 pipes, and you can't use the block overlay to set it from the side, which would be nice).  But if you actually put a different liquid in the pipe, it still lets it through.
#
#### What do you suggest instead/what changes do you propose?
Fix it if possible.  Maybe the change to GT6 style pipes broke it?  I don't know if they worked before.

**Comment by Dream-Master** [comment]
I need help with it @richardhendricks @mitchej123  thanks

**Comment by Anarack** [comment]
Ok after messing with them some more, multipipes do respect filter fluids correctly... as long as there is more than one fluid in the pipe, if there is less they ignore fluid filters.

**Comment by Dream-Master** [comment]
@Anarack can we close this or did we need to add a tooltip ?

**Comment by Anarack** [comment]
No they do not filter correctly if you pipe every does not have at least 2 fluids in it. Leading to jammed setups. 

so do not close this as it is still a issue or add a tool tip warning to them till this is fixed. 
Possible fixed with this pull request but idk if we have it.

https://github.com/Blood-Asp/GT5-Unofficial/pull/1425

**Comment by Dream-Master** [comment]
will check if we can add it. @Anarack need you after it for testing.
