### ISSUE TITLE
GT centrifuge doesnt accept combs

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#248]
Since the last update GT centrifuges wont process combs at all

**Comment by Dream-Master** [comment]
I say it Blood Asp

**Comment by Dream-Master** [comment]
Fixed.

**Comment by Dream-Master** [comment]
It will accept it with my small fix.
Wil be in the next update.

**Comment by Dream-Master** [comment]
Fixed with Gt Version 21 and Forestry 3.0.6.17 stable
