### ISSUE TITLE
Some items from the mod GT New Horizons don't stack if crafted slightly diffrently.

### ISSUE THREAD

**Issue by Smetanol** [GTNewHorizons/NewHorizons#2480]
#### Which modpack version are you using?
GT New Horizons 2.0.2.7

#
#### If in multiplayer; On which server does this happen? 
Any, including single player.

#
#### What did you try to do, and what did you expect to happen?
Unfired clay bricks(id:7792) crafted using x8 recipe and x1 recipe do not stack between each other, though those items are absolutely the same. Same issue can be seen with glass dust(id 5876:2890) of Gregtech - macerated, mortared glass, crafted sand dust with flint dust. all 3 stacks of dusts don't stack between each other. Also glass dust for some reason doesn't stack if it was previously crafted. I have 5 stacks of glass dusts, that don't stack with each other, though pretty sure all of them were crafted using sand dust and flint dust recipe.

#
#### What do you suggest instead/what changes do you propose?
Look for any unnecessary data that may be embeded to items on craft. Those items are generic and shouldn't really have extra info on them.

**Comment by richardhendricks** [comment]
I think there's also a problem with tin cans, they don't seem to stack properly once filled.

**Comment by Dream-Master** [comment]
Yes thats normal they get a gt tag for the recycling recipe. Nothing i can do here.
If anyone have a idea go ahead.

**Comment by codewarrior0** [comment]
Register the crafting recipes using the vanilla crafting handler instead of the GT one. That way they don't get recycling tags.

**Comment by Dream-Master** [comment]
Yes but recycle recipes are nice and very useful

**Comment by codewarrior0** [comment]
These particular items (unfired bricks, quartz dust, glass dust, flint dust) aren't really recycle-able. They're more like the results of recycling other things. Besides, it doesn't make sense to put glass dust in a disassembler and get a block of glass back, or put bricks and get clay back, or even put quartz sand and get regular sand back.

Out of these, the only one that can really be recycled is the unfired bricks back into clay balls, and you can just add a regular crafting recipe for that (shapeless unfired brick -> clay ball).

**Comment by Dream-Master** [comment]
I will remove the reversible tag on this items not make sense.

**Comment by codewarrior0** [comment]
Might have to remove DISMANTLEABLE too - 

RECYCLEABLE adds the Macerator, Arc Furnace, and Fluid Extractor Recipes
DISMANTLEABLE adds the Disassembler Recipes

**Comment by Dream-Master** [comment]
Ok will look into it again
