### ISSUE TITLE
Input Hatch tooltip

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#2481]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
MV/HV/EV/IV/LUV/ZPM/UV/UHV Input Hatch tooltip show that capacity has wrong 
#
#### What happend instead? (Attach screenshots if needed)
I did the test it should be
MV 32000L
HV  56000L
EV 88000L
IV 128000L
LUV  176000L
ZPM 232000L
UV 296000L
UHV 368000L

**Comment by Dream-Master** [comment]
@FallDark what is wrong here?

**Comment by Dream-Master** [comment]
ah i see will look into it.

**Comment by Prewf** [comment]
the output hatch tooltips are also wrong. should be the same values as the input hatches reported by @FallDark. can easily check with a portable scanner. for example, the ev output hatch is like this
![outputhatchwrong](https://user-images.githubusercontent.com/35204071/35199044-00096902-fead-11e7-9e77-fb454b15d1d4.png)

**Comment by Dream-Master** [comment]
ok
