### ISSUE TITLE
quests not oredicting circuits

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2485]
an issue i have found with many quests: multiblock farm control, electric jetpack, electrotine jetpack and a few others: the quests require specific circuits (ic2 one) instead of any on that tier. fix pls

**Comment by Dream-Master** [comment]
@Shattered2909 Please name all quests with ids i can better found it. Thanks

**Comment by Shattered2909** [comment]
591, 651, 647, will look for more

**Comment by Shattered2909** [comment]
797, 796, 652,

**Comment by Dream-Master** [comment]
797 was change allready.

**Comment by Dream-Master** [comment]
796 too.
