### ISSUE TITLE
obsidian electron tube recipe broken

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2488]
so i was tryin to make bronze tubes for my autofarm and before i could put in bronze rods, it processed and made obsidian ones. checked NEI and found this
![2018-01-21_23 56 57](https://user-images.githubusercontent.com/35029480/35200019-056202f6-ff07-11e7-97ab-717424f95995.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Guess there are no long obsidian rods or this is a core mod item and not implemented.
