### ISSUE TITLE
An error in the required aspects of the staff

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2489]
![2018-01-22_03 17 18](https://user-images.githubusercontent.com/35035276/35205038-50122b96-ff43-11e7-9645-34a168cbbfe7.png)

**Comment by Dream-Master** [comment]
Yes will fix. What is the name of the wand to find it quicker? @CalterOK

**Comment by CalterOK** [comment]
Shadowmetal Attuned silverwood staff

**Comment by Dream-Master** [comment]
@CalterOK  thanks found out already
