### ISSUE TITLE
Can't use Bio diesel in Copter Pack

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2490]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Fill a copter pack with Biodiesel cells.
#
#### What happend instead? (Attach screenshots if needed)
It doesn't accept biodiesel cells.  It accepts Ethanol, Diesel, and Cetane, but not bio-diesel.  Looking at the adventure backpack config file, it looks like it's intended to accept a recipe for "Biofuel", and there is a biofuel cell in GT, but that can't be made.  It seems like a similar issue where internally, "Diesel" is the same as "Fuel", so "BioDiesel" should be "Biofuel" as well, but it isn't.
#
#### What do you suggest instead/what changes do you propose?
Figure out a way to use Bio diesel, if possible.

**Comment by Dream-Master** [comment]
@ugashaga any idea here?

**Comment by Dream-Master** [comment]
Bio Diesel is not Bio Fuel so far i can see if i check the code right

https://github.com/runescapejon/AdventureBackpack2/blob/master/src/main/java/com/darkona/adventurebackpack/config/ConfigHandler.java#L158

https://github.com/runescapejon/AdventureBackpack2/blob/master/src/main/java/com/darkona/adventurebackpack/reference/GeneralReference.java#L20

Bio Fuel have id 705 ingame

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35216811-36222062-ff69-11e7-8041-158ee94fb4e5.png)

**Comment by Dream-Master** [comment]
seems not in use

**Comment by Dream-Master** [comment]
https://github.com/runescapejon/AdventureBackpack2/pull/117
