### ISSUE TITLE
Empty universal fluid cell works with Combustion Generator and Gas Turbine

### ISSUE THREAD

**Issue by Takafate** [GTNewHorizons/NewHorizons#2493]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Put empty universal fluid cells in a diesel generator or gas turbine, expecting they won't generate any EU.
#
#### What happend instead? (Attach screenshots if needed)
The generator starts working without consuming anything, witch makes it an infinite power source. This works with Diesel Generator and Gas Turbine at any tier, also GT++ ones.
![2018-01-22_19 59 30](https://user-images.githubusercontent.com/12082829/35219877-4314b820-ffaf-11e7-9e81-b555cd4f9781.png)
![2018-01-22_19 59 43](https://user-images.githubusercontent.com/12082829/35219955-888c8d4c-ffaf-11e7-9b06-05a58f8ecf3e.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it if it is possible.

**Comment by Dream-Master** [comment]
I will if i can :)

**Comment by repo-alt** [comment]
Haha, this is s nice one.

**Comment by WarlordWossman** [comment]
This feature has to be a thermal expansion reference.

**Comment by richardhendricks** [comment]
UFCs are just buggy as hell, from what I've heard.  Will give this issue high priority for next debug time.

**Comment by richardhendricks** [comment]
Probably related to this issue as well, negative fuels etc. https://github.com/GTNewHorizons/NewHorizons/issues/759
