### ISSUE TITLE
Distillation Tower in wrong tier?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2494]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to craft an Distillation Tower in HV/EV tier
#
#### What happend instead? (Attach screenshots if needed)
Apperently Distillation Towers require IV circuits, I assume this is not intended?
![image](https://user-images.githubusercontent.com/22825059/35226323-3ad20484-ff8b-11e7-9d40-06eff00f6ae9.png)

#
#### What do you suggest instead/what changes do you propose?
If Distillation Towers are meant for HV tier, then replace these with HV-Tier circuits

**Comment by bartimaeusnek** [comment]
maybe replace with EV circuits since they are craftable at late HV.

**Comment by Dream-Master** [comment]
Sure will look into it

**Comment by Prewf** [comment]
Was this changed in 2.0.2.7? I made the distill tower a couple months ago and I needed workstations (ev-tier), which is doable in hv.

**Comment by Dream-Master** [comment]
Yes i will change it to ev. Not make sense because the other parts are hv age
