### ISSUE TITLE
UV machines req UHV circuits 

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2498]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Want to craft UV machine(bender), but it req UHV circuit :DD 
ZPM bender req UV circuits
LuV bender req ZPM circuits
IV bender req IV circuits

Luv circuts?...

Refered to this https://github.com/GTNewHorizons/NewHorizons/issues/2230 , please look more closely to all circuit system\progression

![2018-01-23_17 09 40](https://user-images.githubusercontent.com/25028786/35280146-558340f6-0060-11e8-97e5-423174ccce65.png)
![2018-01-23_17 09 39](https://user-images.githubusercontent.com/25028786/35280152-56bf2534-0060-11e8-81e3-2d258483bb25.png)
![2018-01-23_17 09 33](https://user-images.githubusercontent.com/25028786/35280149-561a87d6-0060-11e8-8487-90a075df4245.png)
![2018-01-23_17 09 34](https://user-images.githubusercontent.com/25028786/35280150-564a4462-0060-11e8-8006-abd4127a6f92.png)
![2018-01-23_17 09 22](https://user-images.githubusercontent.com/25028786/35280147-55adc48e-0060-11e8-921a-a8df7c26317b.png)
![2018-01-23_17 09 23](https://user-images.githubusercontent.com/25028786/35280148-55ea54f8-0060-11e8-94a1-48f27c8678b3.png)
![2018-01-23_17 03 11](https://user-images.githubusercontent.com/25028786/35280065-0b708dac-0060-11e8-8e81-303fc0f5cc42.png)
![2018-01-23_17 03 09](https://user-images.githubusercontent.com/25028786/35280066-0b978826-0060-11e8-890d-cd05328efc7e.png)

**Comment by Dream-Master** [comment]
A mistake maybe

**Comment by benstuwie** [comment]
I think wetwares should replace crystalprocessors. Make wetware circuits IV tier, assemblies LuV tier, computers ZPM tier, and mainframes UV. Just remove crystalprocessors all together, they're too easy to make for the tiers they apply to. That will keep the circuits going to the right tier. Some eu/t values might need to be changed for the wetwares, but I think it'll work

**Comment by Dream-Master** [comment]
No sorryi dont make duct tape fixes. We need to rework circuits complete or let it like it is.

**Comment by benstuwie** [comment]
I think reworking them is probably the better idea, but I'm not sure how people will feel about that. There was just a huge circuit change that made everyone change how they made circuits. If you change it again, maybe people will get even more upset

**Comment by Dream-Master** [comment]
If there is a good concept i guess not.
