### ISSUE TITLE
World Guard

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#250]
Normal users need some extra permission so we can modify the region, cant even see the region name so /rg info or /rg select are needed at least.

Also i belive for golems to work in the region it need a special permission, something like FakeThaumcraftGolem if i remember correctly

**Comment by Namikon** [comment]
We shall all take a look at http://docs.enginehub.org/manual/worldguard/latest/permissions/
and discuss some proper permissions, so people can see/alter their own region as they wish. Let's move this to the forum

**Comment by Namikon** [comment]
Also, I already had that problem on my own server:
http://forum.enginehub.org/threads/golems-wont-plant-saplings-in-regions.15913

So it should be fixed if the FakeThaumcraftGolem is added as owner to the region. We'll check that

**Comment by Namikon** [comment]
Drobac, can you please verify if the golems work now, I think I found a proper solution

**Comment by Drobac** [comment]
Golems working

**Comment by Namikon** [comment]
Awesome. I'll set your region later, and if that works too, I guess we're good with the whole permission setup. Guess we also could try the sample perms for players then, as nobody complained yet  in the thread

**Comment by Namikon** [comment]
Everything seems to be working fine. If there are still problems, please create a new issue
