### ISSUE TITLE
Quest #169 can't be completed

### ISSUE THREAD

**Issue by Shuan97** [GTNewHorizons/NewHorizons#2500]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
I've tried to complete quest "The creation of life #169". I used Soul Binder to make Broken Spawner (Skeleton) but the first part of quest hasn't been done. (Powered Spawner part works).

![image](https://user-images.githubusercontent.com/35654946/35292805-f7c16c92-0071-11e8-8c5e-2b97820c01b5.png)

![image](https://user-images.githubusercontent.com/35654946/35292857-1d8c0b62-0072-11e8-814b-201f17478502.png)

**Comment by Dream-Master** [comment]
a nbt issue 100%. Will look at it
