### ISSUE TITLE
Game crash at loader / TecTech

### ISSUE THREAD

**Issue by st3f** [GTNewHorizons/NewHorizons#2502]
#### Which modpack version are you using?
2.0.2.6 / 2.0.2.7 technic launcher
#

#### What did you try to do, and what did you expect to happen?
New installation of 2.0.2.7 or 2.0.2.6 but the gane didn't start
#
#### What happend instead? (Attach screenshots if needed)
Game crashed... 

[crash-2018-01-23_22.57.25-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1657778/crash-2018-01-23_22.57.25-client.txt)
[crash-2018-01-23_22.41.15-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1657780/crash-2018-01-23_22.41.15-client.txt)

The game starts if i remove the TecTech Mod.

#

**Comment by Dream-Master** [comment]
@Technus any idea here?

**Comment by Technus** [comment]
try pluggin in the newest build from jenkins http://jenkins.usrv.de:8081/job/Tec%20Tech/

**Comment by st3f** [comment]
Problem solved...

TecTech has a file: Java.Trojan.GenericGB.19853 which was blocked by my antivirus...

Thx

**Comment by richardhendricks** [comment]
Tec?  U been bad doggo, sticking nose in dirty things? LOL
