### ISSUE TITLE
Venus Stone Dust centrifuging recipe inconsistent

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2503]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Centrifuge Venus Stone Dust
#
#### What happend instead? (Attach screenshots if needed)
It requires empty cells and stores CO2 in them
#
#### What do you suggest instead/what changes do you propose?
Put CO2 in the output tank just like the other centrifuging recipes

**Comment by Dream-Master** [comment]
yes sure can change it.
