### ISSUE TITLE
Engraved energy chip from GTnewhorizons mod...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2507]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
... can not be crafted.
![2018-01-24_02 32 20](https://user-images.githubusercontent.com/25028786/35306511-2e6c5030-00af-11e8-903e-40f4e3083148.png)
![2018-01-24_02 32 32](https://user-images.githubusercontent.com/25028786/35306512-2e918882-00af-11e8-889d-940a9bde0b8e.png)

**Comment by Dream-Master** [comment]
A damage value issue again I guess.

**Comment by benstuwie** [comment]
Must have changed in 2.0.2.7 I could have sworn I was making them in 2.0.2.6. Those go into the tier. 3 storage chips, right?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35433638-7f0af5e2-0284-11e8-94ae-b599096ac4c3.png)
![image](https://user-images.githubusercontent.com/2970688/35433649-86cbfe48-0284-11e8-83ea-654fd650aaae.png)
works with empty one not with new crafted
