### ISSUE TITLE
Quest 997 Dark steel armor advanced upgrades

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2508]
#### Which modpack version are you using?
2.0.2.7

![2018-01-24_05 19 12](https://user-images.githubusercontent.com/35035276/35311953-42925ea4-00ca-11e8-9e51-f84e87d09955.png)
Does not count the night vision potion, an error in the ID.
Installed 8230, and crafted 8198
![2018-01-24_05 19 02](https://user-images.githubusercontent.com/35035276/35311964-4d53eac4-00ca-11e8-8931-4cc6fed5a894.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
@CalterOK you need night vision 1
