### ISSUE TITLE
Sodium Persulfate Quest

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2509]
In the most recent version of the pack, I am doing quests in MV and the Sodium Persulfate quest seems a bit off. It asks you to get some sodium and sulfur, which I think is the old recipe. At this point the only recipe to get started with sodium persulfate, you need to create sodium bisulfate, for which you need salt and sulfuric acid. So neither Sulfur nor sodium is used directly in the creation (since at that point, its likely you have sulfuric acid up already).

It should probably be changed to salt and sulfuric acid for the first step, sodium bisulfate for the second step and the persulfate for the last step.

**Comment by Dream-Master** [comment]
Will look into it.
