### ISSUE TITLE
advanced bee loot bag - Power Module

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2511]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
dirthuts
#
#### What did you try to do, and what did you expect to happen?
Got an Advanced Bee Loot bag for making a Frame -  It gave me a Gendustry Power Module

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
just reporting progress jumping loot.

**Comment by Dream-Master** [comment]
Yes i need to look into it and fix it.

**Comment by devanchya** [comment]
Loot - 961 - that's where it is
However our loot file was corrupted and the Advanced and Expert Bee bags were combined.

I also removed a Scanner item from the file,  I think our loot file was corrupted upload at some point.

I've reviewed most of the loot and none are Obviously game breaking from the original file.

This is a local config issue.

**Comment by Dream-Master** [comment]
Ah ok . So not a bug in the pack i guess?

**Comment by Hakameda** [comment]
This is loot from 256 advanced and 64 advanced with fortune - http://prntscr.com/i51t7k

**Comment by Dream-Master** [comment]
@Hakameda i not know your texture pack. Make the pic better with vanilla texture

**Comment by Hakameda** [comment]
To sum it up, Its useless junk. No power modules

**Comment by Dream-Master** [comment]
Ah ok

**Comment by Dream-Master** [comment]
@devanchya can we close this?
