### ISSUE TITLE
disassembling solar panels

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2512]
so ive been makin a few lower tier solars and realized something: there are different kinds of solars, different paths, also quests for them, now i have an MV cover one and a lower one + ic2 one. the ic2 one has become pretty useless now and the same would happen if i made a 32 eu/t one (required by quest), now i was wondering if you could add recipes to disassemble the solars again, cuz the way it is right now, if i make a specific one, the panel is just gone. would be amazing to disassemble it, then upgrade it again, much better with quests as well so i dont have to restart makin panels.

**Comment by benstuwie** [comment]
The quests for the block ones should be removed too in my opinion. There's no reason to make the block ones, unless you're getting the bee that needs them.

**Comment by Dream-Master** [comment]
disassembling it is ok i guess.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35412978-4875298c-021e-11e8-917a-18f5615729a2.png)

**Comment by Shattered2909** [comment]
there is a reason for the block ones: they do not require manual cleaning, also they generate a little bit at night
