### ISSUE TITLE
Scanned Quantum Armor book missing 2 material

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2513]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Scan the Quantum Armor "do not use" in scanner to make book
#
#### What happend instead? (Attach screenshots if needed)
Book is missing the material needed, shows up as %material instead
Page 5-  6 4x %material Wire
Page 9- 4 %material Screw

#

**Comment by Dream-Master** [comment]
Yes sadly not fixed. @Technus you need to look again in this issue.

**Comment by richardhendricks** [comment]
Needs to use getLocalizedNameForItem maybe?  Had to update scanner mod similarly for il18n language support.

Materials.getLocalizedNameForItem(GT_LanguageManager.getTranslation("gt.blockores." + meta + ".name"), meta%1000)

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/35598594-6686479c-0635-11e8-844c-cecbe2331008.png)
For the motor it starts from the first page
