### ISSUE TITLE
ExtraCell2 - cheat bug. Infinite any fluids.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2514]
2.0.2.7
Infinite fluids scheme:
Not use fluid cells. Only tanks.
SOURCE TANK -> Fluid import Bus -----> Fluid storage Bus -> DESTINATION TANK (full).
When dest tank full, if decrease fluid amount from the tank, then the destination tank fill up. But source tank not decrease fluid amount.
Total result: infinite fluid.
I try use fluid interface instead import bus. and bug not appear.

**Comment by Dream-Master** [comment]
Very old bug. Thought it was fixed a long time ago.

**Comment by Dream-Master** [comment]
@Proha5 can you report it to extra cell repo please?

**Comment by Dream-Master** [comment]
https://github.com/ExtraCells/ExtraCells2/issues

**Comment by Ngar1** [comment]
tested with 2.0.2.5 Radion as fluid and tank, supertank, drum and and between : no dupe

**Comment by boubou19** [comment]
fluids in extracells always had some issues: i don't count the times where i needed to clean my fluid storage system because i had it filled with duped fluid. for me it happened when i tried to empty a fluid cell in the fluid terminal but the cell that hold the fluid is near full
