### ISSUE TITLE
I do not know where to find pure titanium

### ISSUE THREAD

**Issue by Kostia-2001** [GTNewHorizons/NewHorizons#2515]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Kostia-2001** [comment]
In the book of quests, he writes that on Mars, and in the GretTech only on the moon

**Comment by Kostia-2001** [comment]
Achievement GretTech

**Comment by Dream-Master** [comment]
Will check

**Comment by bartimaeusnek** [comment]
It WAS on moon pre 2.0.2.7, but now, you can fint it on mars.

**Comment by Dream-Master** [comment]
Mars and moon

**Comment by Bryfer** [comment]
You can find bauxite ore on the moon which you can make rutile from
On Mars you can find titanium ore

**Comment by Dream-Master** [comment]
Moon have titanium but a bit rare.

**Comment by Prewf** [comment]
Titanium is not currently on Mars. Titanium **was** on mars for a short period. I forget which patch, but sometime after that, it was moved back on the moon (and taken off of mars). I don't think it has been changed since.

This is from 2.0.2.7 oregen config (under the "mix" section)
05 {
                    S:BiomeName_None=None
                    I:Density_0=3
                    B:EndAsteroid_false=false
                    **B:GalacticraftCore_Moon_false=true**
                    B:GalacticraftMars_Asteroids_false=true
                    **B:GalacticraftMars_Mars_false=false**

**Comment by Dream-Master** [comment]
maybe i revert ist to original. So it is on moon and asteroids now.

**Comment by Prewf** [comment]
For anyone who hasn't gone to the moon yet, I think it's also worth noting that although bauxite seems useless for titanium (which it is; honestly just remove the rutile recipe if we're keeping titanium on the moon), it is AMAZING for gallium, so don't rule it out on your list of "ores to mine" when you go to the moon.

**Comment by Bryfer** [comment]
It's not useless, but titanium ore is alot quicker and drains less energy
All you need is rutile, salt(chlorine) and magnesium
And carbon and uhm that blue thing. Sodium? :P
Oh, and two HV machines for easier setup 

Keep ore prospecting if you don't like that recipie :)

**Comment by codewarrior0** [comment]
Every Ore Asteroid I've mined in the Asteroid Belt has lots of small Titanium Ores.

**Comment by Bluebine** [comment]
In 2.0.2.7, raw titanium appears on the Moon and on Mars's moons.

Rutile is just annoying, don't bother with it.
