### ISSUE TITLE
Power substation from GT++ too cheap

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2517]
#### Which modpack version are you using?
2.0.2.7
#
#### What do you suggest instead/what changes do you propose?
The power substation can hold as much power as an ultimate/really ultimate batter, accept/distribute power at any tier, but costs almost nothing in comparison. Both ultimate batteries are long assembly line crafts, costing hundreds of lapotron orbs, and thousands of lapotron crystals. They also require mk3 fusion, and UV tier stuff. The power substation looks craftable around EV tier if not earlier. I'd suggest removing it because of how easy it is for transforming and storing power compared to every other method. If it's staying, I'd suggest replacing the quad lithium battery in the controller recipe with a really ultimate battery, and replacing the Incoloy-MA956 frame box in the middle of the casings with a 16A UMV -> 64A UIV transformer.

**Comment by Dream-Master** [comment]
@benstuwie please report it to orginal repo too. Thanks

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues
