### ISSUE TITLE
Gas Turbine missing pollution tooltip

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2519]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Single block combustion turbines list pollution numbers, so I expected single block gas turbines to do the same.
#
#### What happend instead? (Attach screenshots if needed)
Gas turbines don't list their pollution
#
#### What do you suggest instead/what changes do you propose?
I think Gas turbines are half the pollution of their Combustion turbine counterparts. Please change the tooltips to say that. For example, the MV combustion turbine generates 80 pollution per second, the MV gas turbine needs to say it generates 40 pollution per second.

Can't attach a pic right now, but just check the tooltips to see for yourself.

**Comment by Prewf** [comment]
damn that was fast!

**Comment by Dream-Master** [comment]
bääääm
