### ISSUE TITLE
2.0.2.7 very low FPS

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2521]
Before 2.0.2.7 fps was 60-80. (at factory, on idle, render distance 5)
2.0.2.7 decreased fps to 15-25. (idle, render distance 2)
If leave factory(but chunkloaded) - fps restored to 60. (max 60, but Vsync disabled - second bug?)

**Comment by WarlordWossman** [comment]
had no fps problems yet, did it happen only once or is it consistent?

**Comment by Proha5** [comment]
WarlordWossman, its happens always.

**Comment by Dream-Master** [comment]
On the server?

**Comment by shawnbyday** [comment]
@Proha5 You can try turning Mipmap Levels to off. This helped me significantly.

**Comment by Dream-Master** [comment]
No more infos ? I close this now.
