### ISSUE TITLE
Naquadah alloy dust recipe is missed.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2522]
2.0.2.7
Missed recipe for _full_ naq. alloy dust. Exists only for small/tiny pile.

cuurent:
![image](https://user-images.githubusercontent.com/29812448/35419427-990bdef8-0283-11e8-93df-f9f2f9d28583.png)
missed:
![image](https://user-images.githubusercontent.com/29812448/35419438-a7ec5dee-0283-11e8-8f5a-946c80dcdad8.png)

**Comment by Dream-Master** [comment]
Guess it's overriten. Will check

**Comment by Dream-Master** [comment]
Guess gt++ block it possible.
![image](https://user-images.githubusercontent.com/2970688/35432939-024350a6-0282-11e8-8bc4-b8d31beab099.png)

**Comment by benstuwie** [comment]
I think I speak for most people in saying naq alloy is more important than a GT++ alloy. Maybe add like a circuit 9 or something that isn't 1 or 2 to the GT++ one, and restore the full dust naq alloy recipe.

**Comment by Dream-Master** [comment]
Not even sure if i ever can add it id gt++ not ad circuits to the recipes. I will try it.

**Comment by Dream-Master** [comment]
recipe is gone but not sure how to craft trinium naquadah alloy dust/ingot etc. @draknyte1
