### ISSUE TITLE
Electric Goggles of Revealing/Boots of Travel Battery Bug

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2524]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Craft Electric Goggles of Revealing with a newly crafted Advanced RE Battery
#
#### What happend instead? (Attach screenshots if needed)
Doesn't craft.
#
#### What do you suggest instead/what changes do you propose?
The recipe asks for a :26 damage value, which is an empty battery, but it doesn't come like that when you craft it, instead it starts out with no durability bar.  The only way I could craft it was by charging it a little bit and then taking it out really fast so that it had the :26 damage.  It would be better if it could work from freshly crafted, or even full charge.

This might also be a problem with the Electric Boots of Travel infusion recipe, but I'm not sure because I just made sure to charge it a little before even trying.

**Comment by Dream-Master** [comment]
fixed today in dev
