### ISSUE TITLE
Suggestion: Skinport & Hopperducts

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2525]
#### Which modpack version are you using?
2.0.2.7
#

#### What do you suggest instead/what changes do you propose?
Just add two small mods.

The first one is Skinport, it simply lets you use 1.8 skins, so you dont have these white stripes on your playermodel.

The second one is Hopperducts:
I personaly dont like the GT pipes, so I think that Hopperducts might be a solution for this problem.
Hopperducts can be filled with a normal Hopper and transport items into their attached inventory, but they cant extract any items out of chests or other inventorys. 
There is also a grated Hopper, which allows you to only extract specific items.

I think ,that these assembler recipes might be balenced:
3 Iron Plates + 1 Mini-Chest -> 2 Hopperducts (4EU/t for 20 sec)
1 Hopper + GT Item Filter -> 1 Grated Hopper (16EU/t for 40sec)

**Comment by Prewf** [comment]
> The second one is Hopperducts:
I personaly dont like the GT pipes, so I think that Hopperducts might be a solution for this problem.
Hopperducts can be filled with a normal Hopper and transport items into their attached inventory, but they cant extract any items out of chests or other inventorys.
There is also a grated Hopper, which allows you to only extract specific items.

You can do all this with GT pipes. What don't you like about GT pipes?

**Comment by Zoko061602** [comment]
I dont know its just a personal preference.
Most times it would simply be easier to use sth like a hopper, than using a GT pipe with conveyor Module.
I think GT pipes are pretty useful when building things with GT Machines, but not with Forestry or Railcraft Machines.

**Comment by Prewf** [comment]
Well, I was just wondering because hoppers can also fill GT pipes last I checked (you might have to wrench it now because of gt6 style pipes), so you don't need a conveyor to input into it if you do it that way. Functionally, it just seems similar to something we already have.

Btw, have you tried out ender io item conduits? I've found those to be a lot more convenient for piping items than GT pipes. They're also not that expensive to make.

**Comment by Zoko061602** [comment]
Ok, you're right.
I forgot hoppers can fill GT pipes, I even used this for something.
But I think, it would make sense to mention that in a quest.

**Comment by Dream-Master** [comment]
Ok i can mentioned this in quests. Didnt know it works :)

**Comment by richardhendricks** [comment]
Yeah I use hoppers to GT item pipes in lots of places.  Just be aware that they are generally slower than an LV conveyor. 1 hopper is 1 item/s.  LV conveyer is 64 items/20s.  If you want something faster than a hopper but less annoying to make, item  translocators are a nice option. Easy to make once you have an extruder.

**Comment by Dream-Master** [comment]
The skinport mod you can use in your client but i not put it on the server.

**Comment by Zoko061602** [comment]
@Dream-Master why?

**Comment by Dream-Master** [comment]
The mod list full every mod i add makes the pack slower. Open up a poll and lets see how many people want it. If there are more than 30 i add it.

**Comment by bartimaeusnek** [comment]
Im against a new Mod adding more Stuff we already have. You can use for item transportation: conduits(enderIO), Item Nodes & Convoyer Belts (Extra Utilities), Pipes(Gregtech), Carts (Steve Carts, Railcraft), GreedyChests (Thaumcraft), Transport Pipes (Project Red, Buildcraft), Hoppers (Vanilla, Natura), a AE2 System, Translocators, and much more stuff i cant remember.

**Comment by noobyaran9** [comment]
Just nope for both mods. Its too redundant for the pack when there is already excessive amount of item transport method. Skin mod is a nope from me, its a pointless mod.

**Comment by bartimaeusnek** [comment]
another problem with hopperducts: the mod is CLOSED source, therefore its not easy to change the recipe/fix bugs without getting into license problems. @Zoko061602

**Comment by Dream-Master** [comment]
I add quest info to hoppers and then I close this issue.

**Comment by CalterOK** [comment]
I see no reason to add fashion data to the assembly, as mentioned above there are a lot of alternatives to GT pipes, as for skins, this is a purely individual problem and if it hinders you yourself, you can install this mod.
