### ISSUE TITLE
Server Crash (+ World Corruption): IC2 Crops

### ISSUE THREAD

**Issue by anyname2** [GTNewHorizons/NewHorizons#2526]
#### Which modpack version are you using?
2.0.2.7

#
#### If in multiplayer; On which server does this happen? 
Private Server

#
#### What did you try to do, and what did you expect to happen?
I tried to place crop sticks

#
#### What happend instead? (Attach screenshots if needed)
Server crashed. 
When trying to start it again server fails to start.

Crash log is here: [Crash.txt](https://github.com/GTNewHorizons/NewHorizons/files/1668985/Crash.txt)

**Comment by Dream-Master** [comment]
Will be fixed in 2.0.2.8

**Comment by bartimaeusnek** [comment]
Please remove your Version of Berries++ from your Servers Mod folder and replace it with this one:
https://github.com/bartimaeusnek/berries-plus-plus/releases/tag/1.1.1d
