### ISSUE TITLE
The Sifter - Tin to Zirconium

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#2527]
#### Which modpack version are you using?
2.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
The Sifter, when i try to sift tin or casserite or it shows a chance to get Zirconium dust from GT++.

Intended?
#
#### What happend instead? (Attach screenshots if needed)
![bug](https://user-images.githubusercontent.com/3237986/35463438-e9a3e05a-02f0-11e8-9051-eea9ee80249a.png)

#
#### What do you suggest instead/what changes do you propose?
Should this be fixed?

**Comment by Kortako** [comment]
I'm pretty sure it's the only way to get Zirconium, which is needed if you want to make some of the GT++ machines.  What do you want to get "fixed"?  Tin isn't a "jewel", so it's not like it would normally have a sifting recipe anyway.  I don't see the problem here.

**Comment by Dream-Master** [comment]
Yes it is added by gt++

**Comment by draknyte1** [comment]
It's based on GT6 Zr obtainment.
