### ISSUE TITLE
Uneven Input Numbers In Distillation Tower

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2528]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Im currently setting up an oil refinery system when I ran into this annoying issue.
I began with running Heavy, Light oil thru the oil cracking unit, and then moving it into an huge distillation tower
This was working fine since the oil cracking unit is outputting 1000l and the distillation tower wants 1000 l aswell!
and then I began phase two which was supposed to be running overflow naphtha and Refinery Gas thru the same setup, Naphtha went thru as intended.

AND THEN I GOT MAD!
Why isnt Steam-Cracked Refinery Gas using the same logic as everything else here?
Lightly 2500, moderately 1700 and severely 800 ???
This is also only affecting Steam-Cracked Refinery Gas and not Hydro-Cracked Refinery Gas. from what I can see

There could be more liquids that is messed up like this, and its really bugging me out. Is there a reason for this or could these recipies be using the same logic as everthing else?

Butene is also affected in a similar way. (lightly: 1000 Moderately: 1250 Severely: 2000)
Butadiene is also affected in a similar way. (requires 2000l / operation)
Ethane is also affected in a similar way. (requires 2000l / operation)

#
#### 
Yes. I know I could use Hydrogen Gas for Refinery Gas, since this would give me more energy. But I'm not intressted in that right now. I want more byproducts.

But if there is a reason for these strange numbers, Then I'll be forced to make multiple oil cracking units, and distillation towers just to process those aswell.
#

#### What do you suggest instead/what changes do you propose?

Re-balance values of Distillation Tower recipes (Also check Oil Cracking unit since some are strange there aswell. so they are using the same logic as every other liquid/gas inside the distillation tower /oil cracking unit

I shouldn't need this many Distillation towers just to automaticly process it all with my low production numbers..

**Comment by Prewf** [comment]
On a slightly related note, is there a way to buffer liquids (like how you can buffer items)?

**Comment by Bryfer** [comment]
@Prewf since im not really sure what you are asking
There is super tanks which can storage large numbers of liquids (GT)
There is fluid regulators which can limit the flow of liquids (IC2 and GT)
however there is nothing that works similar to the (super) chest buffer which holds liquids, and then outputs on a set number.
However the function of a (super) chest buffer could be achived by using cells in an item chest buffer
but this is limited to 1000l/1bucket sizes (or that container you are using)

**Comment by Prewf** [comment]
meant like a chest buffer

**Comment by Kortako** [comment]
I think a liquid chest buffer would be amazing for doing something like automating multiple liquids being processed through a single distillation tower.  That way, recipes with weird numbers for their liquid inputs could be managed better, which sounds like it could maybe alleviate one of the complaints you mentioned (having to build multiple oil crackers/distillation towers for different liquid processing lines).

**Comment by Bryfer** [comment]
now that I think about it, It might be possible to create the function of an liquid chest buffer using SFM (Steve's Factory Manager) But I havent played around with that so much, and that would be way to complicated to use another system just to go around the Distillation tower having strange input numbers?

**Comment by bartimaeusnek** [comment]
@Prewf @Kortako the "liquid chest buffer" are called "Drum"

**Comment by codewarrior0** [comment]
The distillation tower and oil cracker allow multiple input hatches, no?

**Comment by noobyaran9** [comment]
No for oil cracker. One for input and one for the fluid u want to use for cracking.

**Comment by codewarrior0** [comment]
Are you sure? I remember, a long time ago, sending in a patch that adjusted the oil cracker to allow two inputs and outputs for hydrocarbons, to allow the same cracker to work on Heavy and Light Fuel. Did you try to build one with two inputs and two outputs?

You'll still need multiple crackers if you want to crack some fluids with steam and others with hydrogen, of course.

**Comment by noobyaran9** [comment]
I thought u can only place input hatch in the middle of the input side?

**Comment by codewarrior0** [comment]
It can be anywhere on the input side. What you can't do is put input and output hatches on the same side.

**Comment by codewarrior0** [comment]
Anyway, If I were in your position and I really didn't want to build more oil crackers, I'd rig up a buffer system that uses supertanks and cells to measure 1000L amounts to go into the cracker and tower.

**Comment by Bryfer** [comment]
@codewarrior0 

Rig for buffer: Check
Supertanks: Check
using cells as input method of the distillation tower: Check

Multiple inputs will not solve this issue, in that case I'd need one input for EACH liquid/gas
In that case I could just make more machines instead, which is what I think is dumb.

![image](https://user-images.githubusercontent.com/22825059/35468637-8d6a06d4-0322-11e8-91e3-71faa65b8c58.png)
![image](https://user-images.githubusercontent.com/22825059/35468640-a4f90e30-0322-11e8-93d0-e73046588539.png)

Ender Fluid conduits collects the liquids and puts em into supertanks.
Empty cells in inputted into the super tanks, Full cells is sent into the input hatch

The problem is the liquid left over in there once the other kind of cells comes since there is a tiny bit of liquid already in the input hatch...

**Comment by codewarrior0** [comment]
Did you put in an item regulator set to only insert cells of Moderately Steam-Cracked Refinery Gas in multiples of 17? That would be the key to avoiding leftover liquid in hatch, I think.

**Comment by Bryfer** [comment]
No. I did not place a bunch of item regulators outside the input hatch so I could regulate the numbers needed for all the different liquids.

I belive an better solution is to change the numbers since they dosnt make sense to me.. If they make sense to you then please explain the logic.

I've tried to use item regulators before. They are just messing it up. try it yourself :)
If you set it to 17, and it starts working, then the regulator seems to try to keep the numbers INSIDE the input hatch at 17. meaning if there comes more cells, it will input them in there

It also seems like alot of unnessesary work just because these recepies are dumb?

**Comment by codewarrior0** [comment]
Ah, maybe you need to use Chest Buffers set to only *output* the cells in multiples of 17?

One man's "this is dumb" is another man's "wicked engineering problem" after all!

**Comment by Bryfer** [comment]
So what you are saying is that I should make multiple chest buffers, place them close to the input chest. then read all the recipies and for each difference in the input numbers I should just add another chest buffer, which itself would need item filters which would soon be maxed so I would need more item filters to connect them all to the chest buffer which is outputting the correct number of cells for the liquid input of the distillation tower?
Does that make sense to you?
It dosnt to me.

**Comment by Bryfer** [comment]
@codewarrior0 

If the input number was 1000 liters instead of the current 1700 (as I mentioned faar up this back, all way to OP.)
If the input was 1000liters like everything else is using then I could just add another super tank, and do what im already doing with all other liquids. Store em in the tanks and extract cells when needed.

But since its 1700 for moderately Steam-Cracked Refinery Gas currently, This is not possible and you CAN indeed to alot of strange enginnering to solve it. But I belive its completely unnessesary to make it so you are forcing players to actually make setups just to solve unnessesary problems which really shouldn't exist from the beginning.

**Comment by codewarrior0** [comment]
I think at this point it's a matter of taste.

You aren't forced to make the weird chest buffer setup any more than you are forced to build a dozen crackers and distil towers. You could just void the refinery gas, after all. ;)

**Comment by mitchej123** [comment]
@Bryfer - Have you checked the upstream PR that rebalances the cracking/distillation to be more in line with standard GT input/output volumes?  https://github.com/Blood-Asp/GT5-Unofficial/pull/1334

Disclaimer: I haven't looked into it much myself; but I am in favor of consistency of volumes in/out, and less useless cracked outputs.

**Comment by Dream-Master** [comment]
I don't like the way It was changed in the main fork but we can change liquid amount that it match better. I need detailed recipe changes because I never use the distillation tower.

**Comment by Bryfer** [comment]
@Dream-Master 

New recipie suggestions
**_Refinery Gas_**
**_Oil Cracker: OK_**

**_Distillation Tower:_**
**Light Steam-Cracked Refinery Gas** 
Current input: 2500, New input 1000 (Reduce recipies by 2.5 times, rounded to closest whole number)
Fluid, current, new
Helium Gas, 50, 20
Methane Gas, 2566, 1026
Ethylene, 213, 85
Ethane, 19, 8
Propene 113, 45
Tiny pile of Carbon Dust (cant really be reduced)
Reduce time to 6 seconds from 15

**Moderately Steam-Cracked Refinery Gas** 
Current input: 1700, New input 1000 (Reduce recipies by 1.7 times, rounded to closest whole number)
Fluid, current, new
Helium Gas, 34, 20
Methane Gas, 1732, 1018
Ethylene, 157, 92
Ethane, 77, 45
Propene 13, 8
Tiny pile of Carbon Dust (cant really be reduced)
Reduce time to 6 seconds from 10,2

**_Severely Steam-Cracked Refinery Gas_** 
Current input: 800, New input 1000 (Increase recipies by 1.25 times, rounded to closest whole number)
Fluid, current, new
Helium Gas, 16, 20
Methane Gas, 914, 1143
Ethylene, 20, 25
Ethane, 6, 8
Propene 6, 8
Tiny pile of Carbon Dust (cant really be increased)
Increase time to 6 seconds from 4,8

Distillery: Same changes as the Distillation Tower?

**Comment by Bryfer** [comment]
New recipie suggestions
**_Refinery Gas_**
**_Oil Cracker: OK_**

**_Distillation Tower:_**
**Light Steam-Cracked Refinery Gas** OK!

**Moderately Steam-Cracked Refinery Gas** 
Current input: 1250, New input 1000 (Reduce recipies by 1.25 times, rounded to closest whole number)
Fluid, current, new
Methane Gas, 500, 400
Ethylene, 1625, 1300
Propene, 250, 200
Small pile of Carbon Dust Reduce to 1 from 2
Reduce time to 9,6 seconds from 12

**_Severely Steam-Cracked Refinery Gas_** 
Current input: 2000, New input 1000 (Increase recipies by 2 times, rounded to closest whole number)
Fluid, current, new
Methane Gas, 3000, 1500
Ethylene, 625, 313
Propene, 250, 125
Small pile of Carbon Dust, Decrase from 3 Dust to 2 dust or 6 small dust
Decrase time to 6 seconds from 12

**Comment by Bryfer** [comment]
New recipie suggestions
**_Butadiene_**
Oil Cracker: OK

**Distillation Tower**
_**Lightly Steam-Cracked Butadiene**_
Current input: 2000, New input 1000 (Reduce recipies by 2 times, rounded to closest whole number)
Fluid, current, new
Methane Gas, 375, 188
Ethylene, 375, 188
Propene, 1500, 750
Small Pile of Carbon dust, reduce to 3 small dust from 6
Reduce time to 6 seconds from 12

**_Moderately Steam-Cracked Butene_**
Current input: 2000, New input 1000 (Reduce recipies by 2 times, rounded to closest whole number)
Fluid, current, new
Methane Gas, 375, 188
Ethylene, 2250, 1125
Propene, 250, 125
Small Pile of Carbon dust, reduce to 3 small dust from 6
Reduce time to 6 seconds from 12

**_Severely Steam-Cracked Butene_**
Current input: 2000, New input 1000 (Reduce recipies by 2 times, rounded to closest whole number)
Fluid, current, new
Methane Gas, 2250, 1125
Ethylene, 375, 188
Propene, 250, 125
Carbon Dust, reduce to 1 from 2 dusts
Reduce time to 6 seconds from 12

**_Lightly Hydro-Cracked Butadiene_**
Current input: 750, New input 1000 (Increase recipies by 1,33 times, rounded to closest whole number)
Ethylene, 500, 655
Butene, 500, 655
Increase time from 4,5 to 6 seconds

**_Moderately Hydro-Cracked Butadiene_**
Current input: 900, New input 1000 (Increase recipies by 1,11 times, rounded to closest whole number)
Methane Gas, 200, 220
Ethylene, 400, 440
Ethane, 400, 440
Propene, 200, 220
Butane, 200, 220
Increase time from 5,4 to 6 seconds

**_Severely Hydro-Cracked Butadiene_**
Current input: 270, New input 1000 (Increase recipies by 3,7 times, rounded to closest whole number)
Methane Gas, 720, 2664
Ethylene, 105, 389
Ethane, 250, 925
Propane, 70, 259
Increase tme from 1,5 to 5.5 seconds (or 6 seconds to keep it similar to other recipies)

**Comment by Bryfer** [comment]
New recipie suggestions
**Ethane
Oil Cracker: OK**

**Distillation Tower**
**Lightly Steam-Cracked Ethane OK!**

**_Moderately Steam-Cracked Ethane_**
Current input: 2000, New input 1000 (Reduce recipies by 2 times, rounded to closest whole number)
Methane Gas, 2750, 1375
Ethylene, 250, 125
Small pile of carbon dust, reduce from 3 small pile to 7 tiny pile?
Reduce time to 6 seconds from 12

**_Severely Steam-Cracked Ethane OK!_**

**_Lightly Hydro-Cracked Ethane OK!_**

**_Moderately Hydro-Cracked Ethane OK!_**

**_Severely Hydro-Cracked Ethane OK!_**

**Comment by Dream-Master** [comment]
@Bryfer check my pr and let me know if this is ok.
https://github.com/GTNewHorizons/GT5-Unofficial/commit/34e5d22aae04a5b662e22d560736904dcb62e7d2

**Comment by Bryfer** [comment]
Looks good :)
