### ISSUE TITLE
Energy production: Biomass/Biogas

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#253]
I'd like to go into IC2 crops since no one else seem to have any experience with them on the server. (Nobody likes weed or something I guess...)
Since the longer growing crops pretty much take over all your play time to be worth it, I was thinking of generating power with them in some way. Biogas/ethanol comes to mind.

I think nearly all machines are using forestry ethanol/biogass with the exception of the GT gas turbines and the disabled ic2 machines.
To make ic2biogass you compress your crop produce into plantballs and macerate them into bio chaff which is then canned in the (ic2) fluid/solid canning machine.
(I'd just macerate ALL the weed instead.)
The (ic2) fermenter converts the biomass into biogas using ic2 heat. You'd end up loosing EU for all the processing if you just converted EU to to heat though...

Well, GregTech does provide a way to produce biogas in the distillation tower (EV), but would anyone even bother at that tier?
GT ic2biomass (5880:0, ammount 250) to Biogas (5880:9, ammount 8000) recipe in the distillation tower:
![2015-07-12-163327_342x322_scrot](https://cloud.githubusercontent.com/assets/5067989/8638489/fb67d4ea-28b4-11e5-9d56-5fbf9a93c094.png)

Maybe scale the recipe down to LV?
So, for 1 second with 16EU/t usage; 8 ic2biomass would give 250 biogas for a total of 2400EU.
Without free fertilizer and water.

**Comment by Dream-Master** [comment]
Using IC2 Machines to do it cheaper.

**Comment by Dream-Master** [comment]
Or what you want to try exactly ?

**Comment by Teteros** [comment]
Well, I've already made a IC2 biomass setup for testing already. Some thoughts:
* IC2 machine recipes don't show up in NEI for some reason. (I didn't even know IC2 biomass is a thing without looking it up)
* IC2 fermenter are very slow compared to the IC2 Fluid/Solid Canning Machine. You can easily run more than 4 fermenters on one fluid/solid canning machine...
![2015-07-12-204203_1004x743_scrot](https://cloud.githubusercontent.com/assets/5067989/8639596/d236ec38-28d6-11e5-977e-6ee87a459d24.png)
* ...with a ton of resources that is. You might not even run the fermenters with an energy gain without a fluid heat generator or better. You need another type of heat generator to even start the fermenter because the fluid heat gens run on Biogas, which can't be produced without heat...
* The system needs a way to keep some of the biogas produced so the generators can keep working. The most compact way I could think of were redstone upgraded translocators which pulled the biogas to the GT gas turbine at calculated intervals.
* The IC2 fluid ejectors are more expensive than GT electric pumps, and you need one for each fermenter (output for EU produce) and each solid fuel gen (output to keep working) for proper fluid supply.
* In the end, those 4 fermenters seen above were just enough to keep one basic gas turbine running as long as you supply the biomass.
* The Fluid/Solid Canning Machine is fine as it is, it just needs appropriate (transformed) EU power and  water supply.

 Add the running costs of crop harvester, macerator, compressor (scanner,*cropsticks*, cron-matron...) for crops/bio chaff, so you can compare how much better your charcoal/tree farm is.

**Comment by Dream-Master** [comment]
So what we have to add ore change to using ic2 too?

**Comment by Teteros** [comment]
The new IC2 recipes need some tweaking in my opinion, some suggestions (more to follow after testing).

Please change the Fluid/Solid canning machine assembler recipe to require 32EU/t instead of 64EU/t so biogas production is possible at the same tier as fuel production.

The IC2 semifluid generator produces 32000EU for 1000mb of ic2biogas.
GT basic gas turbine produces only 26000EU for the same amount.
Maybe match the EU output of the gas turbine to the semifluid gen or make a recipe for the IC2 semifluid generator?

The [IC2 fluid distributor is just a fancier pipe](http://forum.industrial-craft.net/index.php?page=Thread&threadID=10941). It is pulls fluid from all but one side and pushes it to the remaining side, or vice versa. It doesn't take multiple fluids and doesn't sort them either.
5 ejector upgrades needed for crafting it make sense for what it does, but is way is too expensive with the current ejector upgrade recipe.
The fluid distributor recipe needs to be changed and/or the ejector upgrade.

It doesn't store liquid, so it doesn't need a tank. Something like:
III
CPC                         where I = Iron Item Casing, C=Empty Cell or Steel fluid pipe. P=Electric Pump (LV)
III

While at it, the Electric Sorting Machine, that needs 6 ejector upgrades could be adjusted too.
Though I never used it tbh.

How to make IC2 coolant cells? NEI shows vacuum freezing Coolant cells  to Coolant cells.
There is typo in "Stainless Stell Item Casing".

**Comment by Dream-Master** [comment]
Cooling cells you make with lapis dust and water in the Fluid canning machine. These recipes i cant change. All recipe in ic2 machines i cant change only the Gt ones.
Solid Fluid Canner Recipes i change to 32 EU.
GT Gasturbines have a Fuel efficency of 90% with 32 EU.(Did you using a Cable that have loss too)
Ok I change the Fluid Distributer using one or two of them.
Maybe the Sorting Machine i change to using only 2 Upgrades.

**Comment by Dream-Master** [comment]
IC2 Biogas give 32000 EU. So i don't change this. i think it is loss from the cable and 90 % Fuel Efficiency.

All Other recipes i change.

**Comment by Teteros** [comment]
I used the batbox with a spawned semifluid generator to compare the two power gen methods to avoid using a transformer.
The basic gas turbine produces 26000EU for 1000mb of ic2biogas which is only about 80% as efficient as the semifluid generator, not 90%. (26000EU of 32000EU).
It gets worse with higher tiers. I wonder if the large gas turbine accepts ic2biogas, should be.

Assuming it accepts it, I thought about GT recipes for biogas production (see 1st post) because a very high number of ic2 machines would be needed to keep up with the distilation tower or the large gas turbine.
Mostly because the IC2 machines are very slow at what they do.
It's like coke oven/creosete oil problem all over again.

Maybe MV equivalents for biogas production of the IC2 machines could be made? This means IC2 machines would be still useful for LV, and will be more efficient than the GT MV ones. On the other hand the GT MV recipes for biofuel/biogas would produce way more in that amount of time to meet the high demands of the large gas turbine/distillation tower.

**Comment by Dream-Master** [comment]
Ok witch recipes you want in the mv age.

**Comment by Dream-Master** [comment]
@Teteros 
I need to know what i have to add!

**Comment by Teteros** [comment]
To update this, the recipe from the first comment was added today. (32EU/t that is) Thanks @Dream-Master!

Looks like GT had overwritten the Sugar Canes to IC2 Bio Chaff macerator recipe with sugar ones though.
Potatoes and carrots work on the other hand...

Could you add a 8x Sugar Canes to Plantball recipe in the compressor please?

**Comment by Dream-Master** [comment]
Not working because one sugar Cane gives one sugar.

**Comment by Teteros** [comment]
8 Sugar cane to 1 Plantball should be possible though?

Oh, and uh... the distillery recipe is useless at the moment, because it consumes the integrated circuit.
The IC does not have the "Does not get consumed in the process" tag/flag?

**Comment by Dream-Master** [comment]
I will add it.

I will repair the recipes.

**Comment by Dream-Master** [comment]
Ok i repair it.
