### ISSUE TITLE
Vibrant Alloy dust with Fluid Extractor

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2530]
#### Which modpack version are you using?
2,0.2.7
# 
#### If in multiplayer; On which server does this happen? 
Local, single
# 
#### What did you try to do, and what did you expect to happen?
Vibrant Alloy dust fluid extracting. Expected getting Molten Vibrant Alloy like NEI says
# 
#### What happend instead? (Attach screenshots if needed)
I've got Molten VIbrant Alloy
# 
#### What do you suggest instead/what changes do you propose?
Disable Fluid Extractor recipe for Vibrant Alloy dust. 
Vibrant Alloy Dust has to be proceeded via  EBF on 3000 K and Vacuum Freezer then to get Vibrant Alloy  Ingots.

**Comment by Dream-Master** [comment]
Sadly a gt++ issue so far I know. In gt it is not possible but becsuse gt++ add this material too and not switch on end required. Go and report it on gt++ side. Thanks
