### ISSUE TITLE
LCR too cheap

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2531]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
The large chemical reactors are hv machines because they're gated behind PTFE. Processing arrays are an IV item, because of the tungstensteel and lapotron orbs. LCR's are better than a processing array in every way possible, for pretty much any tier past MV. This means the LCR is better when you unlock it, than a machine you wont unlock for 2 more power tiers. I think the LCR should be gated behind at the earliest, ZPM. It's an extremely useful machine, and it is really powerful. Much more powerful than a processing array of chemical reactors could ever be. Adding europium or americium plates to the controller would gate it behind a t6 rocket, requiring at least LuV power, and an assembly line to make.

**Comment by codewarrior0** [comment]
It's powerful, yes, but it's nowhere near as flexible as an Array since it only does chemical reactions. I think it's kind of essential to have once you start getting into the advanced petrochem recipes. For that reason, I wouldn't make it any higher than the Distillation Tower already is, and the Tower requires EV circuits.

**Comment by codewarrior0** [comment]
If there's something that ought to be changed about it, it's that it ignores the Clean Room requirements for recipes, including the Nanoprocessor and QBit wafer recipes.

**Comment by benstuwie** [comment]
That's fair I guess, but if so, I think it should have the no overclock loss aspect removed. That's mostly the part I think is too good

**Comment by codewarrior0** [comment]
Yeah, I could live without the free overclocking too. Maybe have it kick in only at super high voltages, if at all.

The best part about the LCR, in my opinion, is being able to use the big Aluminum fluid cells in the input hatches, which makes it easy for you to measure and carry around large amounts of fluid, so you can make big batches of things like Cetane Diesel, PTFE and Epoxid more easily.

**Comment by noobyaran9** [comment]
IMO, the LCR is just perfectly fine as it is. 
-1st, u can achieve no overclock loss aspect of the LCR using processing array fairly easily (Just add more and have fun with the no overclock loss aspect). 
-2nd, if u take away no overclock loss aspect of the LCR, the only actual benefit of this multiblock exisit is only able to accept multiple fluids to process multiple recipe which makes it worthless. (PA FTW)

>The best part about the LCR, in my opinion, is being able to use the big Aluminum fluid cells in the input hatches, which makes it easy for you to measure and carry around large amounts of fluid, so you can make big batches of things like Cetane Diesel, PTFE and Epoxid more easily.

You can also do the same exact thing with PAs.

**Comment by benstuwie** [comment]
A PA will still always be worse, and is a higher tier item. PA is IV, LCR is HV. A single PA can only do no overclock loss up to EV, then you need multiple. So, once you have IV and unlock the PA, you would need to run 4 of them, and have 256 LV chemical reactors to even compare to the LCR. Even then, it's only the same speed when you're maxing out all the chemical reactors in the PA. The LCR will be faster doing 63 or less recipes at once. Unless all your recipes are in batches of multiples of 64, LCR wins every time. 

I agree the LCR's best part is the no overclock loss, and I think it should stay in the game to an extent. However, I think it should be a 2nd one, that's unlock much, much later. Right now, there is absolutely no reason to make a processing array for chemical reactors.

**Comment by mitchej123** [comment]
You're comparing a specialized machine (LCR) to a generalist machine (PA).  The specialized machine should always be better at a specific task than the machine that does everything.

**Comment by benstuwie** [comment]
That sounds fair. However, I still think you should get the specialized machine after the general one

**Comment by mitchej123** [comment]
I dunno, fits in pretty well with the timing of the distillation tower, oil cracker, and other specialized machines.

**Comment by CalterOK** [comment]
With the current abundance of required chemical components, the complication of LCR will add many problems with tuning the chains for their production by using capsules in recipes, which will make it more difficult for some chemistry.

**Comment by Dream-Master** [comment]
I close this very soon.
