### ISSUE TITLE
Crash after crafting Talisman of Nourishment

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2532]
#### Which modpack version are you using?
Delta, 2.7

Crafted a Talisman of Nourishment via Runic Altar. When I picked up the Talisman, it was full (I don't know whether that is normal, but I assume not) and the game crashed. This might be caused by the Healing Axe (the only "food" item in my inventory, unless I overlooked something) which is located in a Battlegear slot.

I couldn't get a screenshot with the IngameInfoXML overlay, but here are at least the hotbar slots. The overlay shows the Talisman as full.

![image](https://user-images.githubusercontent.com/34921674/35484844-6f2b84d8-0456-11e8-8594-3016dc900868.png)

[crash-2018-01-28_17.50.49-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1671308/crash-2018-01-28_17.50.49-client.txt)

**Comment by CalterOK** [comment]
When using this talisman in a single game, problems did not arise. The screen shows an empty mascot, as when filling it, it has a green bar showing its fullness.
![image](https://user-images.githubusercontent.com/35035276/35551147-ee20f540-059e-11e8-9002-36b2cded5a8b.png)

**Comment by Dream-Master** [comment]
Ok so it is a no issue?
