### ISSUE TITLE
Add recipe for BoP Hardened Dirt

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2534]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Use hardened dirt for anything.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Following up on a thread I saw from Discord where recipes for hardened sand were added, it would be really nice if hardened dirt had a use as well.  There's a ton of it in the canyon biome where I made my base, so I have stacks and stacks of a useless variant of dirt.

At the very least, it should pulverize into dirt and maybe some byproducts.  Brief "internet research" tells me that dirt gets hardened because it has high quantities of either clay or lime, so maybe have clay and/or quicklime as a byproduct.  Any other suggestions appreciated.

**Comment by richardhendricks** [comment]
I vote for Gypsum, getting quantites of that for large quantities of concrete is a PITA.  I am OK with it requiring a high tier recipe, maybe in the centrifuge?

**Comment by Kortako** [comment]
@richardhendricks Gypsum isn't actually used in concrete, it's only used for the Firebricks for the BBF.  Maybe you meant Calcite?

**Comment by Dream-Master** [comment]
Gysum too

**Comment by Kortako** [comment]
Concrete is just 2 Calcite dust, 1 stone dust, 1 clay dust, and 1 quartz sand in a mixer with programmed circuit == 2.  I've made tons of concrete as well, because my entire base is concrete flooring.

**Comment by richardhendricks** [comment]
hm, maybe I'm misremembering the recipe I was interested in.  I'll look at it again tonight.

**Comment by richardhendricks** [comment]
Nevermind, I was making a batch of firebricks to expand my BBF for low-priority metals and it was a pain to get more gypsum.  Add whatever you think is worthwhile.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35828660-a9de2430-0ac0-11e8-9f69-dd58f5b3e855.png)
Clay 2x small dust 100%, Quicklime 1x small dust 75%, Gypsum and calcite 1x small dust 25%
