### ISSUE TITLE
electromagic nanosuit boots have excessive eu drain

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2535]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Walking around
#
#### What happend instead? (Attach screenshots if needed)
I'm draining EU from my nanoboots of the traveler for a fall of any height. It should only be draining when I'm actually about to take fall damage.
#
#### What do you suggest instead/what changes do you propose?
A regular ic2 nanosuit boot drains EU following this formula:

0 EU for 4 blocks or lower fall, dealing 0 damage.
(Fall Height - 4) x 800 EU for 5 blocks to 12 blocks fall, dealing 0 damage.
(Fall Height - 4) x 800 EU for 5 blocks to 12 blocks fall, dealing (Fall Height - 12) x 0.5 hearts of damage.

After I upgraded them to nanosuit boots of the traveler, my boots are draining EU for falls > 0 blocks. This is worse than what a regular ic2 nanoboots do. I believe the behaviors of nanosuit boots and boots of the traveler are conflicting with each other. Please fix it so it doesn't drain energy when we fall between 1-4 blocks. You can keep it the way it is for fall heights > 4 to keep it balanced if you want.

**Comment by Dream-Master** [comment]
Which mod?

**Comment by Prewf** [comment]
Electro-magic tools

**Comment by Dream-Master** [comment]
Ok we fork the mod. Maybe we can change something in code.

**Comment by Kortako** [comment]
The regular "Electric Boots of the Traveller" from the same mod has the exact same issue.

**Comment by CalterOK** [comment]
all boots from the mod have a similar problem: the charge is wasted even when falling from 2 blocks, the damage from falling is not applied regardless of the height of the fall.

**Comment by Dream-Master** [comment]
I now but I need help with coding here.

**Comment by Kortako** [comment]
Here's a fix, but it comes with no warranty.  https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/3

**Comment by Dream-Master** [comment]
@Technus @richardhendricks @mitchej123 can you check it please. Thanks

**Comment by Namikon** [comment]
I found multiple issues with this particular part of the mod;
- The event is processed on both server and client; It should only run Serverside
- All 3 variants of the boots seemed to use the same amount for "energyPerDamage"; 1000.  This is probably an issue with Inheritance and the SubscribeEvent attribute, not sure.
- The boots have configurable jump-boost values. Thus, the minimum distance to drain power must be also configurable, or you will drain energy by a normal jump, that is boosted by the boots.
- And; To make it worth upgrading, the boots now have a configurable amount of maximum blocks to drop before the energy drain is tripled. #balancing

See branch debBootsFix for details
