### ISSUE TITLE
Non-Gt Transformers can't boost EU.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/NewHorizons#2538]
2.0.2.7
I maked "Realy ultimate battery." Its receive 1Amp,
I have 8x512Keu solar panels. (4Meu total)
I cant charge this battery, because "non GT transformers" can't boost EU. Only lower eu.
512Keu --> 2Meu - working fine.
2Meu --> 8Meu - not working.
8Meu --> 32Meu - not working.

I tested. 16A transformers boost fine. But 4A - not working.

**Comment by Dream-Master** [comment]
what you mean with boost ? I need more infos.

**Comment by Proha5** [comment]
Transformer boost is:  4A x 2Meu --> 1A x 8Meu

**Comment by Dream-Master** [comment]
@Proha5 Can you make a few pics from the transformers they dont qork in your eyes? I want to see which one you mean.
Thanks

**Comment by Proha5** [comment]
![image](https://user-images.githubusercontent.com/29812448/35612029-f8b98ff2-06b2-11e8-9bf3-464ce2b7e8fd.png)

Label says: "Use soft mallet to invert". I do it.  But not working.
Transformer receive EU, but not output EU.

**Comment by Dream-Master** [comment]
@Technus any idea here?

**Comment by Proha5** [comment]
Same tier GT++(16A) transformers no have this problem.

**Comment by CalterOK** [comment]
Indeed, the transformer in the boost mode only fill the internal buffer without further energy transfer.
![2018-01-31_11 51 14](https://user-images.githubusercontent.com/35035276/35613532-80265ef6-067d-11e8-9257-9eb4c6ddbb83.png)
![2018-01-31_11 51 40](https://user-images.githubusercontent.com/35035276/35613533-805150e8-067d-11e8-8664-ef9de21fcfef.png)
![2018-01-31_11 52 05](https://user-images.githubusercontent.com/35035276/35613534-807d9a86-067d-11e8-8c1e-1f38ec163d67.png)
![2018-01-31_11 51 10](https://user-images.githubusercontent.com/35035276/35613539-82251260-067d-11e8-9314-d2df07727b93.png)

**Comment by mitchej123** [comment]
Is this still an issue?
