### ISSUE TITLE
Server Lag due mob-grinder setups

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#254]
I just had to disable Drobacs mob-farm (sorry for that) because the Server was down to 13 tps. The source of the lag came from there; or to be more precise, it came from those 250+ infernal blazes and ~50 infernal enderman that managed to escape the grinder room, maybe by teleportation or by other means. I'm opening this issue, because mob-grinders are part of mid/lategame, and it should be possible to do that. So we need a couple of good ideas / suggestions how to deal with that problem.

**Comment by Teteros** [comment]
What exactly triggers the teleportation of infernals? Would they teleport on any damage received, or only on player damage?

We have three mob spawners/grinders in our base and they don't seem to teleport at all. IIRC there are special mob grinders which deal damage in the same way a player would (such as robots). It looks like to me infernals make use of their effects only if a player is nearby.

**Comment by Namikon** [comment]
No idea tbh. Only thing I know is that I had to remove a ton of mobs that managed to escape the mob grinder. Maybe there's a cave above the grinder, I haven't checked. Didn't want to break any blocks there

**Comment by Drobac** [comment]
The mobs when they get hit with the Mob Grinder, and the mobs with Ninja/Ender get outside the kill zone. Blazes seem to escape more then other mobs. Think what causes is it is that Mob grinders simulate player kill so the mobs think a player hit them and teleport away

**Comment by Namikon** [comment]
I found something i'd like to test later today. There is a plugin that allows to limit the total number of any specific entity-type (mob, passive, ..) or even mob-type per chunk. If that works, I will gladly remove the spawn-lock (tbh, this infernal-mob thing is causing more problems than it does good...)

I think I will also be able to kick the test server back online today, doing final preparations atm

**Comment by Namikon** [comment]
Problem can't be resolved, as infernals will teleport away and eventually get stuck in a wall.
The entity-limit is in place and working, that'll help at least a little bit for now.
Maybe we need to define a limit for mob-farms, or a blacklist.
