### ISSUE TITLE
electro magic nanosuit loses pollution protection

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2541]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I upgraded my nanosuit boots and helmet into the electro-magic versions, Nanosuit Boots of the Traveler and Nanosuit Goggles of Revealing.
#
#### What happend instead? (Attach screenshots if needed)
IC2 nanosuit protects against pollution effects (slowness, mining fatigue, weakness), but when I upgraded my boots and helm to electro-magic nanosuit variants, I lost that protection.
#
#### What do you suggest instead/what changes do you propose?
I propose to keep that protection. Make it consistent with the IC2 nanosuit behavior.

**Comment by TechnicianLP** [comment]
The Quantum parts provided by ElectroMagicTools are not allowed for the secret Gravi-Chestplate Mode either btw.

**Comment by Dream-Master** [comment]
@TechnicianLP is it possible to add some code to make them protect against pollution?

**Comment by TechnicianLP** [comment]
Why exactly am i supposed to know if such a thing is possible? i was just pointing out a secpnd bug in that mod ...

**Comment by Dream-Master** [comment]
Everyone have more coding knowledge then myself so thats why i ask :P

**Comment by Kortako** [comment]
Here's a fix, but I'm not sure it's the best place to put it.  IC2 registers its own armors in the pollution list some time in their post-init phase, but I wasn't sure if I could figure out how to make EMT do it as well (since we don't have IC2 code forked, I couldn't tell how they do it).  But I've tested this code and it works.

**Comment by Dream-Master** [comment]
If it works all fine I guess. Ic2 code is not open source.
