### ISSUE TITLE
More efficient transition from LV to MV

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/NewHorizons#2542]
#### What do you suggest instead/what changes do you propose?

Making a quest "Tier 3" (craft MV steam turbine) optional and stress a quest about making a LV-MV transformer.

Currently you have to craft the steam turbine in order to progress into MV, which I rather not.

##### Reason:

1. I have a power generation network already in place and I don't want to build a separate one
2. Efficiency difference between LV and MV steam turbines is -10%
3. Power loss of a LV-MV transformer according to [wiki](https://ftb.gamepedia.com/GregTech_5/Electricity#Energy_conversions) is -3.1%, which I would actually prefer.

**Comment by Dream-Master** [comment]
I will split the quest in two parts and make the turbine optional.

**Comment by benstuwie** [comment]
I'd suggest making both optional. There's a lot of ways to start MV, I did neither of those and it worked out just fine.

**Comment by Bryfer** [comment]
Best to start the tier with an mv hull :)

**Comment by Namikon** [comment]
The machine hulls where the initial thing when the first ~500 quests where made, and I do agree that this is still the best thing to detect.
