### ISSUE TITLE
Information about the multi-block turbine

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2543]
The multi-block turbines lack information about the state of the rotor. This is very important information and in the original GT there is it. It would be possible to replace 1 line (Large turbine) with a display of rotor wear.
![2018-02-01_13 15 12](https://user-images.githubusercontent.com/35035276/35673310-3bc884a2-0752-11e8-8496-474262967025.png)

**Comment by Namikon** [comment]
This information is present; It's just not shown to you as the available lines are used up. You need to deselect unwanted lines in the config-GUI of the panel. 

Available information-lines are:
1 - "Large Turbine"
2 - Stored Energy
3 - Running State
4 - Current Output
5 - Optimal Flow
6 - Turbine Fitting
7 - Fuel Remaining
8 - Current Speed
9 - Turbine Damage
10 - Pollution reduced to

**Comment by CalterOK** [comment]
Only 8 lines are available, and the last 2 can not be displayed

**Comment by Bryfer** [comment]
Which GUI scale do you have?
Try an lower GUI scale, should work to see the text properly that way

**Comment by CalterOK** [comment]
changing the size of the interface does not affect. in the panel settings it's still only 8 lines, and how to add the last 2?

**Comment by Namikon** [comment]
Well, might be possible that by now there is *too much* Information to be shown to fit in that screen 🤔

**Comment by CalterOK** [comment]
is the size of the monitor?

**Comment by Namikon** [comment]
No; I think it may have happened that there are too many lines available so that the InformationPanel is unable to display all of them. This has to be investigated further

**Comment by CalterOK** [comment]
in my opinion, now some lines are occupied with completely unnecessary information, since not all are required to be monitored continuously. 1) you can specify a name in the panel itself; 2) this information was needed in general if it can be obtained with the help of a scanner if necessary; 10) it is easy to learn from the established muffler hetch.

**Comment by richardhendricks** [comment]
3 & 5 seem redundant to me.  3 because you know if it is running by the Current Output, or the blades rotating on the front. 5 because it is not information on the current turbine status, but for all turbines of that type.

A useful set of lines would be instant efficiency (last tick) and the average efficiency (20 ticks).

**Comment by CalterOK** [comment]
5 simplifies the tuning of the turbine, but it can also be obtained by the scanner. about the average efficiency is not sure whether it is required, if the turbine is set up correctly, it will work with the maximum output (excluding the instant of overclocking).

**Comment by richardhendricks** [comment]
Considering how unreliable GT pipes are about transporting fluids, average efficiency is useful IMO.

**Comment by CalterOK** [comment]
liquid regulators avoid this problem

**Comment by Prewf** [comment]
@mitchej123 re: information panels from general chat today

**Comment by mitchej123** [comment]
Rearranged the info on the display so more can show up.  Didn't add any additional information though.
