### ISSUE TITLE
Quest "Sodium Persulfate" outdated

### ISSUE THREAD

**Issue by Aradur** [GTNewHorizons/NewHorizons#2545]
#### Which modpack version are you using?

GT - New Horizons 2.0.2.7
#### If in multiplayer; On which server does this happen? 

MyFTB.de-GTNH2 Server
#### What did you try to do, and what did you expect to happen?

The Quest "Sodium Persulfate" says i need to make Sodium Persulfate out of Sulfur, Sodium and Water.
#### What happend instead? (Attach screenshots if needed)

NEI only shows a recipe for Sodium Persulfate with Sodium Bisulfate, which is Salt + Sulfuric Acid
#### What do you suggest instead/what changes do you propose?

Update the Quest to match the recipe

https://media.discordapp.net/attachments/234936569360809996/408713042415714307/unknown.png?width=1248&height=676

**Comment by Dream-Master** [comment]
I guess I allready change it but will check.

**Comment by mtesseracttech** [comment]
Duplicate of #2509
