### ISSUE TITLE
Allow IC2 shafts to be made using the GT++ extruder shape

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2546]
#### Which modpack version are you using?
Most recent
#
#### If in multiplayer; On which server does this happen? 
Not relevant
#
#### What did you try to do, and what did you expect to happen?
To use the GT++ extruder shape for shafts to craft IC2 rotor shafts.
#
#### What happend instead? (Attach screenshots if needed)
Nothing, doesn't work.
#
#### What do you suggest instead/what changes do you propose?
Adding the IC2 shafts to the shafts that can be made using the GT++ extruder shape and removing them from the rod extruder shape.

**Comment by Dream-Master** [comment]
Sure can add it

**Comment by draknyte1** [comment]
Want me to do it Dream?

**Comment by Dream-Master** [comment]
i add it now to my core mod but if you can do it will be better.

**Comment by Dream-Master** [comment]
i disabled it in gt
