### ISSUE TITLE
Obsidian Extruder Recipes

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2549]
#### Which modpack version are you using?
2.0.2.5
#
#### What did you try to do, and what did you expect to happen?
Obsidian Large Plate recipe in Extruder accepts only TiCo obsidian ingots, not GT ones.
#
#### What do you suggest instead/what changes do you propose?
OreDictionarify?

**Comment by Dream-Master** [comment]
Will fix is a minetweaker recipe error.
