### ISSUE TITLE
Rewrite Programmed Circuits recepies

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/NewHorizons#2551]
#### What do you suggest instead/what changes do you propose?
Currently if you want to reprogram Programmed Circuit you have to look recepies up. Because after first 8, there is a very not intuitional logic behind numbers.

I say it would make much more sense if the position of the screwdriver is a deciding one.

In other words we can ball park the number we're looking for with the screwdriver and find the exact number by moving the chip around. Like if I want very low number I know I should place screwdriver in the first slot, and if I want something around 11, then it should be around 2 or 3rd slot.

Crafting grids (S for Screwdriver and C for Chip)

Chip=0
`SC0`
`000`
`000`

Chip=1
`S0C`
`000`
`000`

Chip=2
`S00`
`100`
`000`
...
Chip=7
`S00`
`000`
`00C`

Chip=8
`0SC`
`000`
`000`

Chip=14
`0S0`
`000`
`00C`

Chip=15
`00S`
`C00`
`000`

Chip=21
`000`
`SC0`
`000`

Chip=24
`000`
`S00`
`0C0`

**Comment by Prewf** [comment]
As much as I would've liked something structured like this early on, I have half the current recipes hardwired into my brain at this point so changing them would be pretty jarring, at least for me. Could we at least just leave 1 through 8 alone?

**Comment by Day0Dreamer** [comment]
Well, this is a debate of games being hardcore because you have to memorize all the quirks and games being hardcore because you have to make decisions.

My point is - if you have a logical algorithm of thinking about something, you don't have to memorize anything, and in case of Prewf, the only thing he'd be struggling with is AE craft recepies and muscle memory.

Anyways, this is only a suggestion

**Comment by Kortako** [comment]
Well, I'd imagine there are a lot of long time players who already know these recipes though (GT veterans and people who've just played this pack for a long time), and changing them would be pretty annoying after being used to it for so long.  I wouldn't mind Dream changing it if there was a config option to change it back in the GT config.

**Comment by MakinToge** [comment]
No need to memorize the recipe, I crafted 4 circuit of each number up to 24 with more for 1 to 8 and I leave them in a chest at center of my base. What ever recipe I do, I know that I'v the circuit ready...

Anyway, I do think that it's a good suggestion. For the ppl used to old recipe, they can just learn the new one. Since those are really logic, it shouldn't take long.

**Comment by Day0Dreamer** [comment]
I agree, some people would be pissed. I am, after having Windows re-do each time the Control Panel. I am used to the good old Windows2000. But new users find the new one better. Such is the path of progress

**Comment by CalterOK** [comment]
in the current version, there is also its own logic and the position of the screwdriver sets the number of the circuit. would not say that this change will be so necessary, in fact, you propose to do the opposite.

**Comment by codewarrior0** [comment]
AFAIK the reason for the unusual patterns for crafting circuits beyond 8 has to do with ambiguity in the crafting grid. If the screwdriver is directly to the left of the chip, there are six ways you can lay out the grid with the screwdriver to the left of the chip, and attempting to assign a different circuit number to each of those 6 may leave you with five uncraftable circuit numbers.

**Comment by Day0Dreamer** [comment]
I agree again, there is logic, only I can't get it. It's kinda there but outside of my grasp.

Also we can fit 24 recepies in the way I suggest. It only gets a little bit messy the closer we are to 24 because we have less and less room to work with. (first sqeuence allows for 8, next for 7 and so on.)

**Comment by codewarrior0** [comment]
What I meant to say is that because of limitations in Minecraft's code, these two recipes may be identical to Minecraft and you would always get chip 0, even when trying to craft chip 8. But I'm not 100% sure on that - someone would have to try it out.

Chip=0
`SC0`
`000`
`000`

Chip=8
`0SC`
`000`
`000`

**Comment by Bryfer** [comment]
Here, I make something to show you the current logic of the programmed circuits!
Hopefully this helps you guys to remember and understand the current logic
![image](https://user-images.githubusercontent.com/22825059/35776130-fd39dd98-0996-11e8-8e2a-31cdb025234d.png)

Please dont change these, Current method is fine also If you arrange them like this and its super easy to remember.
![image](https://user-images.githubusercontent.com/22825059/35776147-54e4c65c-0997-11e8-84b3-2f0ce8672afb.png)

Leave programmed circuits as it is please :•)
