### ISSUE TITLE
ic2 Jetpack, NanoSuit and ic2 Nightvision googles have default crafting recipe

### ISSUE THREAD

**Issue by ruSauron** [GTNewHorizons/NewHorizons#2552]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I've tried to craft NanoSuit set for quest. I've expect to use carbon parts, nano crystals, reinforced lenses, BatPack, etc.

#
#### What happend instead? (Attach screenshots if needed)
NanoSuit use base ic2 crafting recipe.
![nano](https://user-images.githubusercontent.com/4716758/35766189-30994b6e-08e4-11e8-9cbc-4a277a5b1774.png)

#
#### What do you suggest instead/what changes do you propose?
They should use more complicated recipe with carbon parts, nano crystals etc.

**Comment by Dream-Master** [comment]
Fixed so far i can see.
