### ISSUE TITLE
Chlorobenzene cannot be crafted in large chemical reactor

### ISSUE THREAD

**Issue by ruSauron** [GTNewHorizons/NewHorizons#2553]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I've tried to craft chlorobenzene in large chemical reactor (multiblock structure) by using 1 bucket of benzene and 2 buckets of chlorine
#
#### What happend instead? (Attach screenshots if needed)
it can be crafted only in the small reactor. In large reactor you may also get dichlorobenzene becouse it have smillar recipe (1 bucket of benzene and 4 buckets of chlorine)
#
#### What do you suggest instead/what changes do you propose?
I want to craft both chlorobenzene and dichlorobenzene in large chemical reactor. 1 bucket of benzene and 2 buckets of chlorine with circuit configuration 1 for chlorobenzene;
1 bucket of benzene and 4 buckets of chlorine with circuit configuration 2 for dichlorobenzene (current alternative recipe) and 1 bucket of benzene and 4 buckets of chlorine with circuit configuration 24 for dichlorobenzene (possible additional recipe instead of not using circuits at all)

**Comment by Dream-Master** [comment]
So far i can see a methode not working (chemical reactor for basic machine only) hope i get  fixed that

**Comment by Dream-Master** [comment]
I hope i fix it and not mess up with other recipes.
