### ISSUE TITLE
"Enchanted Earth" research in Thaumcraft unlocks Infusion

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#2554]
The EnchantedEarth research in the Apimancy tab has an invalid description page:
![image](https://user-images.githubusercontent.com/7611392/35767010-ade798b0-08e3-11e8-961a-b11f42745412.png)

And upon reading the note, it somehow also unlocked all research that requires Infusion:
![image](https://user-images.githubusercontent.com/7611392/35767005-a07876cc-08e3-11e8-955d-50a9657cf499.png)

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35779827-a83ad0b2-09d3-11e8-8282-be5dfba9a713.png)
