### ISSUE TITLE
Can't complete apiarist cloth suit quest in weapons/armor tab

### ISSUE THREAD

**Issue by Hukabu** [GTNewHorizons/NewHorizons#2555]
#### Which modpack version are you using?
2.0.2.7

#
#### If in multiplayer; On which server does this happen? 
Personal server - no changes to any mods/configs from default. 
#
#### What did you try to do, and what did you expect to happen?
Created the pieces of the apiarist cloth suit using the assembler. Expected that to trigger the "crafting" objective of that quest.
#
#### What happend instead? (Attach screenshots if needed)
It didn't trigger the quest completion. 
#
#### What do you suggest instead/what changes do you propose?
Since using a machine to create an item doesn't satisfy crafting quests, I would propose changing that portion of the quest to a "retrieval" task.

**Comment by Dream-Master** [comment]
I have change this allready. Please update your questfile with /bq_admin default load

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35769270-b5451f40-0908-11e8-9e68-eda3e3578e70.png)

**Comment by Dream-Master** [comment]
@Hukabu if this not work after hit /bq_admin default load please reopen it.

**Comment by Hukabu** [comment]
It worked, I didn't realize you had to refresh the quest database when you updated. I forgot to close the issue after I did it. Thanks!
