### ISSUE TITLE
stainless steel and coils

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/NewHorizons#2556]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
epsilon
#

Acceleration from additional temperature of the coils does not work for stainless steel
with the 11th circuit
![2018-02-03_15 02 57](https://user-images.githubusercontent.com/35747549/35768987-e154fc14-090c-11e8-85d5-aad4af5764a3.png)
with the 1th circuit
![2018-02-03_18 06 43](https://user-images.githubusercontent.com/35747549/35769011-38ad51e6-090d-11e8-8fa0-b12e7797e9a4.png)

**Comment by Dream-Master** [comment]
Stainless steel need more 480 eu/t Can use LV hatches.

**Comment by dahgul333** [comment]
Due to the fact that I use hatches lv for liquids / objects, does not run the overclocing from the coils?

**Comment by codewarrior0** [comment]
The acceleration only applies when you are both over the coil temperature by 1800K *and* over the voltage requirement by one tier. So you need an EV energy hatch to see the bonus speed.

**Comment by dahgul333** [comment]
understood,thanks
