### ISSUE TITLE
20 rocket fuel canisters is excessive

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2559]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Trying to finish rocket quests. Quests need 20 empty/filled canisters. Is this reasonable to get to the moon and back? Do they all need to be crafted at once?
#
#### What do you suggest instead/what changes do you propose?
Lower to 8 or 10?

**Comment by richardhendricks** [comment]
![2018-02-05_00 21 07](https://user-images.githubusercontent.com/1214811/35790936-7e607fda-0a0a-11e8-9f94-f7772601b6f0.png)

**Comment by Dream-Master** [comment]
Will change to 10

**Comment by Bluebine** [comment]
@Dream-Master Even 10 is excessive, you only need like 8 to completely fill up a rocket, and only 2 or 3 to get to the Moon. I'd recommend making the quest to craft 8 empty canisters, since you'll need a few of them in quests, and fill 4 of them with fuel.

**Comment by MineAnPlay** [comment]
Even that isn't needed... Just checking for one is enough (If one can fill one they can fill 20 as well, also people might not check the quest before hand might get annoyed that they need to fill 10 more).

**Comment by Dream-Master** [comment]
I don't change it again sorry.

**Comment by richardhendricks** [comment]
I prefer 10, so that way a user reads it "I need 10 to get from the Overworld and to the moon and back, with enough to spare".  Setting it to 1 is just going to cause Discord questions.
