### ISSUE TITLE
Performance Issue: Large amounts of itemstacks

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#256]
I've been mining today, but I forgot to bring my dev/null to get rid of all excessive cobble/dirt/gravel.
So the floor endet up in a total mess, with about 300 entities around myself. Not a nice view, but bearable. However, what is *not* bearable, is that the server has dropped below 20 TPS (18,4 right now) just by me mining and all those itemstacks on the ground.
The dev/null requires a trashcan (1 ender pearl, 7 iron plates) and 1 bucket of ender (4 ender pearls).

In order to cover most "waste" while mining, you need 3 of them. And you need to be at LV age.
Normally i'd agree with the recipe, but for the sake of server performance, this item should be available as soon as players start to mine (At least on the server)

**Comment by Dream-Master** [comment]
I think there is mod for it. I not remember the name.

**Comment by Namikon** [comment]
Well, I'd like to avoid using NoLag/ClearLag, as it removes items on the ground everywhere. If you drop something by accident, and a purge is performed, your items are gone for a long time

**Comment by Dream-Master** [comment]
This mod can reduce the lag ?
https://mods.io/mods/1023-stackie

**Comment by Namikon** [comment]
Cauldron does stack items already, Also, it will probably fight with the setting of 16 items per stack,
and adding such a mod will probably cause new issues, like pam's harvestcraft did/does with food-stacking and "exploding" stacks in the inventory/chests.

However, not everyone will be mining with a tinkers hammer everyday, so it's not that much of an issue anyways.
