### ISSUE TITLE
Electric Hoe breaks when used.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2560]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Used charged Electric Hoe to till some land.
#
#### What happend instead? (Attach screenshots if needed)
When using the Hoe, for a split second its charge bar lowers too much before snapping back to the right energy amount. Probably because of that the Hoe breaks when used with ~4500/10000EU charge.

**Comment by Dream-Master** [comment]
The ic2 ones?

**Comment by Methes** [comment]
Yes, IC2 ones. Behavior can be observed in this short video.
https://www.youtube.com/watch?v=rQyfJiiLSTQ

**Comment by Dream-Master** [comment]
IC2 is not open source but if this happend we need to disable it and make a gt version of the hoe.

**Comment by Dream-Master** [comment]
Did it happend with the treetap or the windmeter too ?

**Comment by Methes** [comment]
Tried Treetap, works fine.

**Comment by Dream-Master** [comment]
Cant reproduce it in sp.

**Comment by Dream-Master** [comment]
I see the value switch back like in your vid

**Comment by bartimaeusnek** [comment]
Barimos (or now "EmptyIsGood") had the same Issure on delta, freshly crafted, charged, used some times and it broke. @Dream-Master

**Comment by Dream-Master** [comment]
i need help from the coding guys :)
@Namikon @Technus @richardhendricks @mitchej123

**Comment by Dream-Master** [comment]
@Methes i ask Aroma1997 about ic2 code also.

**Comment by Aroma1997** [comment]
Since you have InventoryTweaks installed I'd guess it's just a desync. Are the hoes gone, after you reload the world?

**Comment by Methes** [comment]
Yes they are. That's why I tried moving items around in my inventory to check seemingly empty slots.

**Comment by Aroma1997** [comment]
Can you send us a log file?

**Comment by Methes** [comment]
Checked all the files in /logs folder in both server and client and there's nothing at all.
Only this useless info in PlayerActivity:
9.2.18 20:10;RIGHT_CLICK_BLOCK;Methes;DIM:180;280;136;282;|;28;13;28

Is there some config debug I should enable?

**Comment by Aroma1997** [comment]
Can you send us a log file?

**Comment by Dream-Master** [comment]
@Methes just send it please.

**Comment by Methes** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/1712397/fml-server-latest.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/1712399/fml-client-latest.log)

Started using Hoe at 21:52:23

**Comment by Aroma1997** [comment]
Ok, I looked into this, I couldn't find anything though.
The log shows a few cases of "Detected invalid armor damage application" which is the only way I could think about that this happens,, however it's on the client and most likely not connected to the issue.
I lso couldn't think of any reason of why the hoe would disappear, but the treetap doesn't, since they use exactly the same code. You're sure this doesn't happen with the electric treetap?

**Comment by Aroma1997** [comment]
Nope, it all only uses ElectircItem.manager.use()

**Comment by Methes** [comment]
If I'm the only one affected by this just forget about it. I'm in a private world where I can cheat all I want, maybe it's some weird interference.
Maybe try on the official servers and if it's ok there, just close this.
