### ISSUE TITLE
Farming Station recipe only accepts fully discharged Electric Hoe.

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2561]
#### Which modpack version are you using?
2.0.2.7
#
The Farming Station recipe only accepts fully discharged Electric Hoe.
Freshly crafted Hoe does not work.
Fully charged Hoe does not work.
Only fully discharged Hoe works (freshly spawned from NEI).

**Comment by Dream-Master** [comment]
Will check
