### ISSUE TITLE
Reactor parts: wrong recipies

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2565]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Im currently setting up an nuclear reactor and noticed there is multiple recipies for reactor parts..
Custom GTNH recipies AND the old IC2 recipies, which is waay cheaper.
#
#### Affected Items I've found
Heat Vent 4256:1
Reactor Heat vent 4257:1
Overclocked Heat vent 4258:1
Advanced Heat vent 4260:1
Heat Exchanger 4252:1
Reactor Heat Exchanger 4253:1
Component Heat Exchanger 4254:1
Advanced Heat Exchanger 4255:1

#
#### What do you suggest instead/what changes do you propose?
Remove IC2 recipes!!

**Comment by Dream-Master** [comment]
Sure will remove it.

**Comment by Dream-Master** [comment]
This is fixed

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35826037-db0601b2-0ab7-11e8-9191-7abb76b6c31f.png)
![image](https://user-images.githubusercontent.com/2970688/35826047-e1975d14-0ab7-11e8-866f-847d3373c752.png)
