### ISSUE TITLE
GC parachute quest only asks for 4 woven/3 poly rods = enough for 1 canvas

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2566]
#### Which modpack version are you using?
2.0.2.7
#
#### What do you suggest instead/what changes do you propose?
Change first part of quest so that it requires 12 woven and 9 polyethylene rods

**Comment by CalterOK** [comment]
but is it not better to specify the required materials for crafting through the collector?

**Comment by Dream-Master** [comment]
yea i change the recipe and forgot the quest.
