### ISSUE TITLE
Thaumcraft and the osmotic enchanter issue

### ISSUE THREAD

**Issue by KirakoMM** [GTNewHorizons/NewHorizons#2567]
#### Which modpack version are you using? 

# 2.0.2.7
#### If in multiplayer; On which server does this happen?

# Single player with lan connected
#### What did you try to do, and what did you expect to happen? 

# Enchant item via osmotic enchanter (all recipes are brought) and was kinda hoping it would work
#### What happend instead? (Attach screenshots if needed)

# I crashed to desktop and reloading in will keep crashing until the item has become enchanted
#### What do you suggest instead/what changes do you propose?
To stop me crashing, also here is the crash report https://pastebin.com/F3SFktrE

**Comment by richardhendricks** [comment]
@KirakoMM please try workaround in https://github.com/GTNewHorizons/NewHorizons/issues/2345
To get to spectral dimension, you will need to gather ectoplasm from killing spirits that come out of mobs, should be pretty easy.

**Comment by KirakoMM** [comment]
I have loads of ecto, will see what i can do and will get back to you, thanks again for the info :)

**Comment by KirakoMM** [comment]
Been trying it in the spectral dimension on my single player lan, and it works like a charm, thank you so much for your help and support.
