### ISSUE TITLE
Rocket Engine Circuit Requirements

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2568]
#### Which modpack version are you using?
Lastest
#
#### What did you try to do, and what did you expect to happen?
Crafting a rocket engine, recipe is ultra expensive for what it is.
#
#### What do you suggest instead/what changes do you propose?
At the moment, the rocket engines, which are essentially just diesel generators, are ultra expensive for what they are and don't fit well into the progression.
For a simple EV rocket engine, you need to use ZPM circuits. Which is out of reach until at least IV. It also makes little sense what their circuits are at the moment considering they have a large efficiency impact compared to the previous tier.
The following chart hopefully will better explain where the disconnect is:
https://i.imgur.com/ueGKkzD.png
Edit: better screenshot
Edit 2: I vaguely remember something about them consuming fuel slower. I still find it to be a rather big step from the previous tier, since you can't feasably get them in the tier their power output is really relevant.

**Comment by Dream-Master** [comment]
Its a gt++ recipes so add this suggestion to gt++. I can wrote a recipe pull request later.

**Comment by mtesseracttech** [comment]
The reason I wrote it here is that even though maybe Alkalus feels it works well in the context of just GT + GT++, I personally feel it does not in the context of GT:NH

**Comment by Dream-Master** [comment]
Sure i will look into it and chat with alkalus.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35978160-403ea686-0ce5-11e8-8fea-c58fb1863fd6.png)
![image](https://user-images.githubusercontent.com/2970688/35978169-46f2ee10-0ce5-11e8-8f3d-fc2f55d71e3b.png)
![image](https://user-images.githubusercontent.com/2970688/35978176-4b3e6b20-0ce5-11e8-942d-f9650e3d1f50.png)

**Comment by Dream-Master** [comment]
new recipes have 136%, 120% 104%
@mtesseracttech is this more balanced ?

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/pull/213

**Comment by mtesseracttech** [comment]
@Dream-Master Looks fine to me, as long as the circuits get a tweak to not be 3 tiers above the given machine anymore.

**Comment by Dream-Master** [comment]
i make them one tier up like ev need iv circuits.

**Comment by mtesseracttech** [comment]
@Dream-Master seems fair.

**Comment by Dream-Master** [comment]
now it use ev components for ev machine
