### ISSUE TITLE
super solar panels consistency

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#2569]
so i was just reading the chat on the gregtech discord and found out theres an IV+ addon for advanced solar panels thats just adding higher tiers, now i was wondering if u wanna add that and just do recipes for the panel blocks like the advanced to quantum one... i think it would be nice to have.

**Comment by Ethryan** [comment]
is it this mod:[Link](https://minecraft.curseforge.com/projects/super-solar-panels)?

**Comment by mtesseracttech** [comment]
I'd be in favor of it

**Comment by benstuwie** [comment]
I don't really see how that would be different than using the ones we already have, but I'm in no way against it

**Comment by bartimaeusnek** [comment]
if its Closed Source, im against it, if we dont get permission to modify it, since we cant fix bugs or do other cool stuff with it... If we get permission to modify it im fine with this mod.

**Comment by richardhendricks** [comment]
I agree, prefer open source mods in case of fixes/tweaks. Pass.

**Comment by Dream-Master** [comment]
It is not open source so i guess we drop it.

**Comment by bartimaeusnek** [comment]
I contacted the owner of Super Solar Panels and asked him to change the license to an Open Source License, he agreed and set it to BSD license.

**Comment by richardhendricks** [comment]
That's totally awesome.

**Comment by richardhendricks** [comment]
Is the source code available somewhere? I didn't see it listed in the link.

**Comment by benstuwie** [comment]
WAHOOOOO, so we're getting block solars? ;D

**Comment by Dream-Master** [comment]
No source code rn.

**Comment by benstuwie** [comment]
I just looked at the actual mod, and that's not quite what I expected it to be. Seems pretty overpowered. I'd assume you wouldn't add the 1B EU/t solar, but even the 2A UV solar is pretty damn good. If the EU/t values changed to IV, LuV, ZPM, UV I'd like it. Requiring the solar cover + solder + machine hull of that tier, like the ones we have right now.

**Comment by bartimaeusnek** [comment]
@benstuwie we got the sourcecode from the auther and re-coded the valures. they are fine now and the mod is in dreams testing pack. When we does not encounter major bugs, hell add it to the next version.

**Comment by Dream-Master** [comment]
added
