### ISSUE TITLE
Forestry: Farm Blocks insanely expensive

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#257]
One single farm block costs about ~250.000 RF to craft, which is around 62.500 Eu. Considering the fact, that the farm block is a basic "craft a stack or two" block, and also considering the fact that it needs apatine electron tubes, this should not cost more than 50k RF, if not less. I was about to craft 100 of them, this would be 6.25 million Eu, or 12 Buckets Nitro-Diesel which is just insane

**Comment by Dream-Master** [comment]
As I said before I have to rebalanced the time in forestry machines.

**Comment by Namikon** [comment]
I found this today: http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Forestry_Support

The value specified as first parameter is only for the duration how long it takes to craft an item. Therefor, I suggest lowering every recipe that is not a "single-item" like the beealyzer, or any machine, down to 20-40 ticks, as It doesn't matter at all. It does not make the recipe more difficult, as the machines do not stop when they don't have enough power. At the moment, it is just annoying to wait.

And if you still want to add the aspect of required power, then you still can create new "inbetween" items and craft those things in the assembler. But I think that would be overkill. Or?

**Comment by Dream-Master** [comment]
I will change the Time of all Carpenters recipes but i need some testings.

**Comment by Dream-Master** [comment]
I will try tomorrow make all carpenters recipes 10 times cheaper of energy cost.

**Comment by Namikon** [comment]
Did you change these timings already? If not, I can do that if you want. I'm waiting for my impregnated Sticks at the moment, takes  about 5 minutes to get one  :)

**Comment by Dream-Master** [comment]
No

**Comment by Dream-Master** [comment]
You can change it if you want but update the git too that I can downloading the scripts then.

**Comment by Dream-Master** [comment]
Not sure if 10 times cheaper is a good value?

**Comment by Namikon** [comment]
No, it was still too much. I set values for every recipe now; According to their rarity and how much you need of the result. To get the total crafting time, you have to divide the number by 5, so if a recipe is 
`mods.forestry.Carpenter.addRecipe(60`
The recipe will need 60/5 = 12 seconds to finish.

I changed every recipe, and 60 is the longest time we have now. It's for all the stuff that you won't need a lot of, like machines, backpacks, farm gearboxes, hatches and such.
Stuff like farmblocks, scented paneling, impregnated sticks, so stuff that you need multiple stacks of, are fast. For example, the impregnated stick only requires 2 seconds to finish.

I pushed it to git, and reloaded the Server. Now we need to verify if these new values are ok or not. IMHO, the crafting time doesn't make the recipe harder, as the machine can be run with just any energy source, it won't loose its progress, like GT machines do. So the only thing that is changed, is the time you have to wait.

**Comment by Dream-Master** [comment]
fixed now. I will check the recipes and maybe change things if necessary.
