### ISSUE TITLE
Picking up capacitor banks with a primal crusher gave chaotic capacitor banks (Creative items)

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2570]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Pick up some basic capacitor banks
#
#### What happend instead? (Attach screenshots if needed)
I got two creative capacitor banks instead... https://i.imgur.com/YBTfg9V.png
#
#### What do you suggest instead/what changes do you propose?
Not sure, should be looked into what causes this.

**Comment by mtesseracttech** [comment]
Played around with it a little, it seems they don't hold any charge at all though and are unable to do the only thing I even use cap banks for (charging items/armor)

**Comment by Dream-Master** [comment]
The capacitors have all the same id only different meta ids and nbt tags. Guess the primal crusher mess up with meta ids. Not sure what i can do against it.

**Comment by mtesseracttech** [comment]
hmmm okay

**Comment by Dream-Master** [comment]
Not so far i can see.

**Comment by mtesseracttech** [comment]
Well, as far as I can see there are 2 things important here:
1: The given capacitor bank does not hold any charge at all, rendering it useless.
2: RF is pretty useless and not convertible to EU anyways, so who cares in the end
