### ISSUE TITLE
extra utilities filter pipe is missing circuit options

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2571]
#### Which modpack version are you using?
2.0.2.7

All the extra utilities item pipes can use any circuit version within the tier except the filter pipe:
![2018-02-08_02 35 44](https://user-images.githubusercontent.com/16925725/35951319-2f6c129a-0c7b-11e8-8f22-a30168460105.png)
![2018-02-08_02 35 23](https://user-images.githubusercontent.com/16925725/35951325-3265da62-0c7b-11e8-8c3a-529ced08db99.png)

Should probably be able to use any type of MV circuit for the recipe!

**Comment by Dream-Master** [comment]
Will change the recipe (oredict)
