### ISSUE TITLE
moss stone recipe probably not intended

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2572]
#### Which modpack version are you using?
2.0.2.7

Moss stone made by 8 moss and a _moss stone_?
![moss](https://user-images.githubusercontent.com/16925725/35952259-7b5692c6-0c7f-11e8-8497-1be51539abea.PNG)

I think it was meant to be a cobblestone in the middle.

**Comment by Dream-Master** [comment]
Oh... I guess yes
