### ISSUE TITLE
Automagy + Storage Drawer Signal Strength?

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2574]
#### Which modpack version are you using?
2.0.2.5

#### If in multiplayer; On which server does this happen? 
N/A

#### What did you try to do, and what did you expect to happen?

I am attempting to shut off a item conduit supplying logs to a pyrolyse oven when the storage drawer on it's output bus is ~XX% full using a remote comparator (Automagy.)

#### What happened instead? (Attach screenshots if needed)
Signal strength appears to be quite odd when removing just a stack of charcoal.

Drawer full (4096, or 100% full) = Signal 15 (Normal.)
Drawer missing 1 charcoal (4095) = Signal 14 (Normal I think, only 100% full gives 15.)
Drawer missing 64 charcoal (4032) = Signal 8 (I don't think that's normal.)
Also, any charcoal amount in the drawer from 64 to ~4000 also gives signal 8. Quite strange.

#### What do you suggest instead/what changes do you propose?

I have no idea, I've done the exact same setup on a different Gregtechified pack (Infitech 2) and it worked just fine.

**Comment by Dream-Master** [comment]
did infinitech using custom version of the mods ? @Axiflare

**Comment by Axiflare** [comment]
Not that I'm aware of. Seems to be a problem with the signal strength of drawers.

**Comment by Axiflare** [comment]
Sorry to double post, can't find edit button on mobile.

I'll attempt to recreate the problem in vanilla and see if it's an issue with drawers/automagy and report back!

**Comment by Axiflare** [comment]
I've returned. Sadly, it appears to be an issue with Automagy that may not be able to be fixed without rolling it back too far, and losing useful (?) items. I am okay with just working around it. A normal comparator works just fine. Here's a screenshot or two.

![comparator](https://user-images.githubusercontent.com/36259908/36011388-5d5a74ca-0d1c-11e8-982b-9961057ff972.png)

**Comment by richardhendricks** [comment]
Great job on debug.  Is automagy closed source?

**Comment by Dream-Master** [comment]
Open drawers is open source and automagy is closed so far i know.

**Comment by Dream-Master** [comment]
api is only open source
https://github.com/Tuhljin/Automagy
