### ISSUE TITLE
Forming Press doesn't accept input from top face

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2581]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Insert items using a hopper or conveyor (set to import) on the top face of a Forming Press.
#
#### What happend instead? (Attach screenshots if needed)
It doesn't work, even though the top isn't considered the "machine controls" face.
#
#### What do you suggest instead/what changes do you propose?
Fix it so that only the front face cannot accept input.

**Comment by richardhendricks** [comment]
Please provide pics and details on set.  My MV chemical bath accepts items just fine from the conveyor above it.

Are you sure the items you are trying to bath have recipes?

**Comment by Methes** [comment]
Are you sure your output side is not set on the top side?

**Comment by Kortako** [comment]
@richardhendricks Actually, I think you're right about the chem bath. Now that I think about it, I keep forgetting that it doesn't insert until you put the proper fluid in.  I'll edit this issue to remove the chem bath.

I definitely had the issue with the forming press though, specifically in an MV one, while trying to make the Diamond Lattice for the 9x9 crafting table for space.  I put a hopper on top, stuck the stainless steel bars and a stack of diamond plates inside the machine, and put the rest of the plates in the hopper, but the hopper wouldn't insert them. I had to move the hopper to the side.  And yes, I'm sure the output wasn't there.  I'll see if I can post pictures later, if necessary.

**Comment by Kortako** [comment]
Ugh, nevermind.  I had a rogue redstone signal going into that blockspace, which was disabling my hopper.  My bad.
