### ISSUE TITLE
Moon quest requirements weird

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2584]
#### Which modpack version are you using?
2.0.2.7

3rd page requirements for the moon quest are a little odd.  Why these items?

https://github.com/GTNewHorizons/NewHorizons/commit/e5d1d2ca9165634804480ddc67444f08ad6e575e#diff-405bb4deaa287e0a8c9aa8101076e990R101314

**Comment by Dacryphile** [comment]
I believe those are the components for the Thaumcraft amulet you get as a quest reward, rather than give it to you for free.

**Comment by richardhendricks** [comment]
Well, they're pretty trivial, and should probably be first if that's the idea. I didn't even know they were required until I already landed on the moon.

Suggestion:
Move them to first page, add in "kill evolved skeleton, creeper, zombie" requirements.  Maybe 4 each?

**Comment by Dream-Master** [comment]
Will change it.

**Comment by Dream-Master** [comment]
@richardhendricks Why get them to first page and after you kill the boss. You need this talisman on the Moon allready so i dont see why i need to change it. Ok the stuff is trivial but who is not fare in Thaucraft maybe can get this talisman without resarch it.
