### ISSUE TITLE
[Suggestion] Cheaper Project Red Stuff & High Tier Vacuum Tube Recipe

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2587]
#### What do you suggest instead/what changes do you propose?
1. Right now, a Project Red Plate costs a LV circuit, thats pretty expensive for basically "compact" redstone, i would suggest, to use Sulfuric Acid (125L), a Stone Pressure Plates and a Copper foil for one, instead of one LV circuit for 4 Project Red Plates

2. Make a SoC recipe for Vacuum tubes, maybe 16 - 32 Vacuum Tubes for 1 SoC, 4 fine annealed copper wires, 1 Circuit Board and some Soldering Alloy

**Comment by Kortako** [comment]
I liked Namo's idea on the Discord chat about some kind of redstone circuit you make with the laser engraver.  I really like the idea of finding a use for the LV laser engraver, because right now I don't see a use for it even though there is a quest to make it.

**Comment by Namo8010** [comment]
I suggest using the pre-circuit update concept of etched circuit wiring. (link:https://ftb.gamepedia.com/Etched_High_Voltage_Wiring)
So putting a redstone plate or redalloy plate in a LV laser engraver (with appropriate lens) will grant 8 ~ 16 Etched redstone circuit wiring. Then assembling(or forming press might be a good idea too) stone plate(or stone pressure plate) with the redstone wiring will make the red power stone circuit board.

**Comment by Namikon** [comment]
+1 for the idea with LV Engraver and remove the LV Circuit from the recipe.
But the "SoC" somehow doesn't fit for the Vacuum tube thing. Even if I do like the idea to get more for less effort. Can't really "mass-produce" them in any way I guess. Maybe add a recipe for those to the Thermionic Fabricator? It has molten glass already as component; That would fit the logic (And is used for the Forestry tubes anyways).

**Comment by noobyaran9** [comment]
The circuit plate from project red used to take only NAND chips. So an ULV circuit would make sense to replace NAND chips.

**Comment by Dream-Master** [comment]
The Forestry recipes I removed  because people don't want them but I can add them back

**Comment by WarlordWossman** [comment]
LV laser engraver would be a nice way to do it with etched red alloy wiring. The basic stone parts taking circuits really is a bit much and I could rebuild the logic gates with vanilla redstone anyways.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/36076313-bf571e18-0f5a-11e8-9d28-00200b0e996e.png)
![image](https://user-images.githubusercontent.com/2970688/36076315-c487d8c8-0f5a-11e8-94ae-4365190d2b72.png)
![image](https://user-images.githubusercontent.com/2970688/36076318-cb17c25c-0f5a-11e8-885f-c0ee4e8ac1d1.png)
![image](https://user-images.githubusercontent.com/2970688/36076320-cedfb2fa-0f5a-11e8-8a9a-32793c372d55.png)
