### ISSUE TITLE
Cetane Quest still gated behind Glyceryl Trinitrate

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2588]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Didn't realize there was a Cetane Boosted Diesel quest at all, because it was locked behind making Glyceryl Trinitrate.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Diesel can no longer be boosted with Glyceryl Trinitrate, so remove that requirement for the quest to show up.

**Comment by Dream-Master** [comment]
Will change it
