### ISSUE TITLE
Suggestion: Highspeed charcoal production

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#259]
An option would be to enable the Railcraft BlastFurnace, remove all recipes in that and add a "1 Wood to 1 Charcoal" recipe. Due the fact it needs charcoal, and you don't get creosote oil, it should only take about 20 ticks (1 second) to cook up. That way, you could run one GT Boiler 24/7 without the need to spam 20 Multiblocks; Better make the recipe for the BlastFurnace a bit more expensive instead.

And it should be craftable at mid-MV age. Also keep in mind that you need 34 of the same block, so adding circuits would be a very mean thing...

**Comment by Dream-Master** [comment]
Enable the Basltfurnace from Railcraft.
Rename it to Advanced Coke Oven
1 Charcoal burns 16 charcoals out of Any Wood.
Looks like 1 Charcoal per Sec.

**Comment by Dream-Master** [comment]
Added. Advanced Coke Oven.
