### ISSUE TITLE
[quests] Damascus steel from coins unlocks too early

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2591]
#### Which modpack version are you using?
2.0.2.7

Buying damascus steel from coins is fine but it unlocks after the "blastoff" quest in steam age, which is when you get your first steel with the BBF:
![2018-02-10_21 12 11](https://user-images.githubusercontent.com/16925725/36066312-cfa2f58e-0ea7-11e8-9e38-c6624e2b4124.png)

I would suggest gating the coin quest for damascus steel after "EBF time" to fix this.
You can loot ingots ofc but being able to buy them should require being able to make them, that's why I suggest it unlocking after "EBF time" instead!

**Comment by Bluebine** [comment]
There's no problem here. You can't actually make tools out of damascus until you've got an MV extruder, whereas alumite only needs a smeltery- and at MV, you've got vanadiumsteel which is even better.

**Comment by WarlordWossman** [comment]
Does it make sense to hand it out that early so you can use it for the gt meta tools then?
Even without the TiCo issue it would make sense to unlock it when you would be able to make the ingots yourself imo. @Bluebine

**Comment by Dream-Master** [comment]
Yes but better selling damascus in late lv or mv.

**Comment by Bluebine** [comment]
Personally I think it's fine being able to get it that early- it just makes better tools- and I'd suggest a bump up in price instead of gating it later.

**Comment by WarlordWossman** [comment]
Okay would probably gate it with "EBF-time" and only give 16 ingots, they are kinda hard to make on your own.
