### ISSUE TITLE
Breaking kinetic generator gives incorrect block back.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2593]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Move kinetic generator
#
#### What happend instead? (Attach screenshots if needed)
Got generator
#
#### What do you suggest instead/what changes do you propose?
Fix breaking kinetic generator so it gives back kinetic generator. 

Or allow some kind of exchange if we can't fix the code.

![2018-02-10_10 37 28](https://user-images.githubusercontent.com/1214811/36064307-b3463846-0e4e-11e8-81a6-541d7349a3f0.png)

![2018-02-10_10 37 36](https://user-images.githubusercontent.com/1214811/36064309-b801b43c-0e4e-11e8-9729-9029049a78bc.png)

**Comment by mitchej123** [comment]
It's IC2, break it with a wrench.

**Comment by Dacryphile** [comment]
More specifically, right-click it with a wrench

**Comment by Bluebine** [comment]
IC2 machines are annoying, you have to right-click them with a GT wrench to harvest them.

**Comment by richardhendricks** [comment]
Well I tried with a GT wrench, but I was using left click. :(  I suppose it is would be impossible to change NEI or add a popup since it is closed-source?

right-click does work.

**Comment by richardhendricks** [comment]
@draknyte1 Maybe you could add some replacement machines to GT++ for IC2 so that they have the proper usage model.

**Comment by bartimaeusnek** [comment]
@richardhendricks or you can move them with a dolly

**Comment by Bryfer** [comment]
Don't you need the IC2 wrench in lossless mode for 100% safe IC2 machines?

**Comment by bartimaeusnek** [comment]
nope

**Comment by mitchej123** [comment]
Only if you're using ic2 wrenches, I'm pretty sure the gt wrenches are lossless.

**Comment by draknyte1** [comment]
I wanted to do kinetics a while back, but there's one major thing with would be unappealing to me. 

I wouldn't/couldn't give them animations. 



Side note, you do have a bug because you shouldn't get a generator ever from a kinetic wind. You'll get either a kinetic wind or a machine casing. (Intended IC2 behaviour) this I know from breaking 100s over the last few years.

**Comment by richardhendricks** [comment]
Wait, so the IC2 machines can be picked up with a dolly? Fabulous.
