### ISSUE TITLE
Crash On Entering game

### ISSUE THREAD

**Issue by DarkRecent** [GTNewHorizons/NewHorizons#2594]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
while playing on my singleplayer world I get blue screen on pc 
#
#### What happend instead? (Attach screenshots if needed)
whenever I try to launch it I get crash https://pastebin.com/b1eZJY0h
![screenshot 66](https://user-images.githubusercontent.com/36361171/36071938-e0ce7e84-0f27-11e8-94a4-b588d4ec32f9.png) 

#

**Comment by bartimaeusnek** [comment]
dark recent did you bred ic2 crops?

**Comment by DarkRecent** [comment]
Im not sure what fml is but I think that should be right one 
[2018-02-11-2.log.gz](https://github.com/GTNewHorizons/NewHorizons/files/1714682/2018-02-11-2.log.gz)

and ı didnt started ic2 crops

**Comment by DarkRecent** [comment]
after reading that log I saw the chunk -2,32 is broken so ı tried to use world edit to delete,regen and netrulize commands but it still gives eror https://pastebin.com/dbMtGXJN there is the eror apeering on console when ı get eror of neturalize

**Comment by DarkRecent** [comment]
so ı just fixed the problem all ı did was using mcedit to delete chunk. ty for your helps 😄
