### ISSUE TITLE
Coins Coins Coins Twillight eggs?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#2595]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I wanted to kill a previous boss I've killed earlier and remembered that coins coins coins has a few quests about this
#
#### What happend instead? (Attach screenshots if needed)
I first need to "buy" an naga egg before im able to kill the lich again.
Im not really sure how these quests are meant to be used, I just assumed they are here if you want to kill bosses again?
#
#### What do you suggest instead/what changes do you propose?
Make the next one only require killing the boss itself, and not needing the previous quest to be completed aswell?

I dont really need another naga, I just wanted to kill the lich

**Comment by Dream-Master** [comment]
ok
