### ISSUE TITLE
Change Hydroxide LCR recipe

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2596]
At the moment it's not possible to do multiple recipes in a Large Chemical Reactor if they contain both Hydrogen and Oxygen, because those two make Hydroxide (which itself is useless).

![image](https://user-images.githubusercontent.com/34921674/36077964-48f5bfd8-0f71-11e8-92e5-be708bd95863.png)

Adding a circuit, preferably something rarely used (so not 1 - 8 or 24) would fix this issue.

**Comment by Dream-Master** [comment]
Its a GT++ recipe so far i can see. Maybe need to add a recipe with circuit on Gt++ side.

**Comment by Dream-Master** [comment]
Why you close it this is an issue. @Wolozo7

**Comment by bartimaeusnek** [comment]
[Link to the GT++ thread](https://github.com/draknyte1/GTplusplus/issues/215)

**Comment by Wolozo7** [comment]
I closed it and moved to GT++. But since that didn't help as well, I guess this needs to go to the main GT thing?

**Comment by Dream-Master** [comment]
```
		GT_Values.RA.addChemicalRecipeForBasicMachineOnly(
				ItemUtils.getItemStackOfAmountFromOreDict("cellOxygen", 1),
				ItemUtils.getItemStackOfAmountFromOreDict("cellHydrogen", 1),
				GT_Values.NF,
				FluidUtils.getFluidStack("hydroxide", 2000),
				ItemUtils.getItemStackOfAmountFromOreDict("cellEmpty", 2),
				GT_Values.NI,
				8*20, 30);
```

**Comment by Dream-Master** [comment]
This code changes für work us so i will do a plull request on GT++ side
