### ISSUE TITLE
More drums in extra utilities

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/NewHorizons#2597]
Maybe it's worth adding more drums for the extra utilities? Make a ranges of: 64-128-256-512-768-1024 and etc.. One drum with a capacity of 256 buckets is somehow not enough. No diversity.

**Comment by noobyaran9** [comment]
No. There is already super tank and quantum tank with provides large fluid storage. Drums and bedrokium drum is enough already.

**Comment by bartimaeusnek** [comment]
Extra Utilities is closed source.

**Comment by Dream-Master** [comment]
Yes this was a bugfix I not add myself. And no we don't need more drums

**Comment by benstuwie** [comment]
If there's one thing this pack isn't lacking, it's fluid storage. There's bc tanks, rc tanks, super tanks, GT++ tanks, GT++ multiblock tank, 2 drums, AE fluid cells, quartz tanks, fluid input busses, open blocks tanks (I think), eio fluid tank thing, cells, universal cells, large cells, and probably more. I think fluid storage is covered if you're trying to store anything from 8B to 2.1B B (I think that's the max of the GT ones)

**Comment by WarlordWossman** [comment]
Open blocks tanks are disabled because the wavey thing does lag and the are too easy to abuse as "infinitly" fast fluid pipe. Also seared tank holds 4B.

It would really only add more clutter if we added more drums.

**Comment by richardhendricks** [comment]
Also seared tanks are portable. :)
