### ISSUE TITLE
issue with gt++ overriding

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2600]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
on delta
#
#### What did you try to do, and what did you expect to happen?
wanted to craft barrel(tier 5) from open modular turrets with gt++ version of the vibrant alloy plate
![2018-02-12_20 46 19](https://user-images.githubusercontent.com/12850933/36116253-dfaef150-1035-11e8-8bb3-425b56574e2d.png)

#
#### What happend instead? (Attach screenshots if needed)
the recipe don't work
#
#### What do you suggest instead/what changes do you propose?
i got my vibrant alloy plate by putting a vibrant alloy ingot into a fluid extractor then solidify it with the mold plate and gt++ overriden the gt plate. I suggest either you somehow disable the gt++ overriding or fix recipe but it may have some recipes affected by this.

**Comment by Dream-Master** [comment]
so i need to put this recipe to code and oredict it.

**Comment by Dream-Master** [comment]
Not sure why gt++ vibrant alloy not converted to gt one.

**Comment by Dream-Master** [comment]
works in 2.0.2.8 dev not sure what is different.
![image](https://user-images.githubusercontent.com/2970688/36140851-08119b26-10a3-11e8-975e-baeba2fa02b7.png)

**Comment by Dream-Master** [comment]
seems alkalus vibrant alloy now switch to gt.
