### ISSUE TITLE
crash with butterflies

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2601]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to capture a butterfly with the golden lasso
#
#### What happend instead? (Attach screenshots if needed)
i crashed
[crash-2018-02-13_21.46.10-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1721641/crash-2018-02-13_21.46.10-client.txt)

**Comment by boubou19** [comment]
despite it says something went wrong with nbt saving it just crashes the client but this doesn't affect delta.
I was able to relog onto delta without any side effects

**Comment by Dream-Master** [comment]
So we can close this ? @boubou19

**Comment by boubou19** [comment]
yup but it happens everytime a player capture a butterfly with a golden lasso. I reported it just to let you know.

**Comment by Dream-Master** [comment]
ok.

**Comment by Dream-Master** [comment]
Butterfly amount and spawnrate are decreased in 2.0.2.8.

**Comment by bartimaeusnek** [comment]
I think this could be changed forestry side... will have a look at it sometime

**Comment by Dream-Master** [comment]
Ok

**Comment by mitchej123** [comment]
Fixed with https://github.com/GTNewHorizons/ForestryMC/commit/208de8ad3affa73b526c56b0908cc9e021906feb
