### ISSUE TITLE
[Malisis Doors] Door bugged in fence

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2602]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
put a door from Malisis Doors aside of a fence and opened it, wasnt able to close it, it was bugged in the fence 
![2018-02-14_02 16 02](https://user-images.githubusercontent.com/33183715/36183154-608cd5c4-112d-11e8-968c-b9539f67ba33.png)

**Comment by Dream-Master** [comment]
Malis Doors not longer developed in 1.7.10.
