### ISSUE TITLE
Frequency transmitters not autocraftable

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2603]
#### Which modpack version are you using?
Most recent
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Trying to autocraft some advanced info panels/extenders
#
#### What happend instead? (Attach screenshots if needed)
It got stuck on the autocrafting step of the frequency transmitter. Probably an issue with the data bound to it.
https://i.imgur.com/Y8SCVHf.png
https://i.imgur.com/MmU7lyz.png
https://i.imgur.com/AxVkTaJ.png
#
#### What do you suggest instead/what changes do you propose?
Change it to something else, maybe the AE2 transmitter or the GTNH transmitter. (https://i.imgur.com/Yn2S1co.png)

**Comment by Cinobi** [comment]
Suggestion: Remove ur stupid texturepack.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/36211835-9bcc5748-11a2-11e8-9e93-061fd35671b7.png)
no its craftable

**Comment by mtesseracttech** [comment]
Thats not what I mean, what I mean is: for some reason, when you try to autocraft it using AE2, it does not let you.

**Comment by Dream-Master** [comment]
why assembler recipes works in ae?

**Comment by codewarrior0** [comment]
Isn't it related to [using OreDict circuits in assembler recipes](https://github.com/codewarrior0/NewHorizons/commit/855bd7fe353256b8ee5ef3b237a79cce14314289#commitcomment-27469987) like you mentioned here?

**Comment by mtesseracttech** [comment]
I explained it in discord. And in the end, I think it's a result of IC2 being IC2 and not really working properly as a result.

**Comment by mtesseracttech** [comment]
@codewarrior0 I didn't see your comment, but that may very well be true.
