### ISSUE TITLE
Farming station (EIO)...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2605]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
... can't be crafted if used hoe with any id except 4275:26
#
![2018-02-14_20 22 14](https://user-images.githubusercontent.com/25028786/36218254-d173e3da-11c4-11e8-9dad-f3ec443d5789.png)
![2018-02-14_20 22 17](https://user-images.githubusercontent.com/25028786/36218255-d1983e7e-11c4-11e8-83fb-9f275511fcc5.png)

**Comment by Dream-Master** [comment]
i guess it is fixed in 2.0.2.8 but i will check.

**Comment by Dream-Master** [comment]
it using meta 1
