### ISSUE TITLE
Add RC Crowbar to ordict via Core Mod

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2606]
Add RC Crowbar to ordict via Core Mod

**Comment by bartimaeusnek** [comment]
Add Void Crowbar from TC aswell please.

**Comment by Dream-Master** [comment]
Sure

**Comment by Dream-Master** [comment]
All oredicted allread. Idk why it shows wrong?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java#L132-L135
