### ISSUE TITLE
Electromagnet Flings Items Behind Player

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2608]
#### Which modpack version are you using?

2.0.2.7

#### If in multiplayer; On which server does this happen? 

Private

#### What did you try to do, and what did you expect to happen?

Using a hammer, mining and expecting blocks to go in my inventory because I have a magnet lol.

#### What happend instead? (Attach screenshots if needed)

In the config, the magnet is capped at 20 items, and only 5 block range. Because of the hammer potentially being so fast, it quickly goes over the 20 item limit for pulling, then flings extra items behind the player, who is probably already more than 5 blocks away from the flung items. Then the items despawn if not noticed! Sadness!

#### What do you suggest instead/what changes do you propose?

I fixed the problem completely by setting these in Enderio.cfg:

magnetMaxItems=20 to -1
magnetRange=5 to 10 (can do higher, but might be annoying on SMP.)

Enjoy!

**Comment by mtesseracttech** [comment]
Ah, I have already been wondering for a while what was causing my clay digging journeys to be such a pain. Support.

**Comment by Bryfer** [comment]
The range of the magnet seems fine to me as it's currently is. But yes the item count could probably be increased slightly.
But I believe unlimited might be too much and could probably reduce TPS too much, or even crash the server.

**Comment by Wolozo7** [comment]
The item flinging the items somewhere around the player is not only caused by too many items. Happened to my on single items often enough, which then land somewhere out of magnet range.

**Comment by ForTheHorde01** [comment]
As it's "electromagnet" i bet it should work this way ;) it cant be op as draconic evolution magnet which just sucks all items to the player, I don't see any bug here

**Comment by richardhendricks** [comment]
I would like a range of 7 and maxitems of 40.   The only place where this would hurt server TPS is if someone decided to use this to carry around extra items instead of in their inventory, and I doubt it would happen that often.

**Comment by mtesseracttech** [comment]
As a frequent user of the Electromagnet, I can safely say that the scenario that @richardhendricks told at the end would not happen. It would be the ideal way to lose a lot of stuff. x)

**Comment by richardhendricks** [comment]
I believe someone has never accidentally axed an upgraded barrel full of crap. :D  But yeah, I approve this change.  It would also be nice if it wasn't solely an Amulet slot item, but meh it's a tradeoff.

**Comment by mtesseracttech** [comment]
@richardhendricks You can also keep it in your hotbar I think. It just doesn't work in the middle of your inventory, which seems fine to me.

**Comment by richardhendricks** [comment]
If the fix for tinker's crossbows in M&B slots works, that'll free up space for that.
