### ISSUE TITLE
RWG fix

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#261]
Maybe we get a rwg fix but only with new terrain.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3?page=302#c6155

**Comment by Dream-Master** [comment]
We have taint now and we can disable the emeralds in the overwold.

**Comment by Namikon** [comment]
I'd suggest to *not* add it right away. Let's wait a few days and observe the thread and repository. To see if the guy continues and is willing to actually fix stuff, or if it's just a 1-week "i'll do all the code" thing

**Comment by Dream-Master** [comment]
Sure but i have to test it and find out how i change things. Oils spans much more than before now. Taint biome appears, magical forest i dont see but i not looking much.

**Comment by Dream-Master** [comment]
Added to the Test server and wait.
