### ISSUE TITLE
Translation into spanish

### ISSUE THREAD

**Issue by LuigiBaute** [GTNewHorizons/NewHorizons#2612]
hello, I would like to collaborate with your translator project in Spanish since it is my native language, I can translate any document that has text as long as the translation is a thousand words or more

**Comment by Dream-Master** [comment]
You mean the Quest book ? @LuigiBaute

**Comment by LuigiBaute** [comment]
It can be the document readme.md and any document that has a thousand or more words

**Comment by Dream-Master** [comment]
you can do pull request to every repo you like. I will pull it.

**Comment by LuigiBaute** [comment]
ok soon I will be sending the pull requests

**Comment by Dream-Master** [comment]
ok nice

**Comment by LuigiBaute** [comment]
Thank you

**Comment by bartimaeusnek** [comment]
@LuigiBaute do you want to translate the [questbook](https://github.com/GTNewHorizons/GTNH-GuideBook-i18n/blob/master/assets/minecraft/lang/en_US.lang) aswell?

**Comment by LuigiBaute** [comment]
Sure I have no problem.

**Comment by Traxis** [comment]
@bartimaeusnek Please, no. Just, no. I don't want to have (more) nightmares about this >_<

**Comment by bartimaeusnek** [comment]
@Traxis whats the problem here? Please explain.

**Comment by Traxis** [comment]
@bartimaeusnek You can read all about it here: https://github.com/GTNewHorizons/NewHorizons/pull/2614

**Comment by bartimaeusnek** [comment]
@Traxis feel free to fix the issures, but a badly translated version is still better than no transalted version at all, in my opinion.

**Comment by Traxis** [comment]
¯\_(ツ)_/¯

**Comment by Wolozo7** [comment]
I doubt that there is a high amount of non-english speaking people that play modded minecraft due to the general lack of non-english documentation for most mods.

**Comment by Traxis** [comment]
Not really, there's plenty of spanish people who play modded minecraft and don't have any issues because they understand english well enough to read the existing documentation and wikis. The thing is, most mods don't offer a translation, and because of that it's pretty hard to translate a whole modpack (maybe the quests text if there's any, or a wiki, but that's it).

**Comment by Wolozo7** [comment]
Wtf?
> non-english speaking people

> don't have any issues because they understand english well enough

What's the connection between the people that you mentioned and mine? Should I have declared them as non-english understanding people?

Anyways, those people don't profit from a shitty translation into their native language.

**Comment by ForTheHorde01** [comment]
Most mods doesn't offer other languages than English because it's most common known language to almost every person. If some ppl can't understand English it's good time to start then. there's no person who cannot understand very basics lol

**Comment by Traxis** [comment]
@bartimaeusnek You are right, my mistake 😛 I've edited my comment.

@ForTheHorde01 I won't be the one defending those "some ppl", and I don't want to turn this into a "everyone should understand English" debate. I don't care about that, really. But if "most mods don't offer other languages than English" it's simply because sometimes there's no available translators who can help the modders, and offer a (proper) translation. There's plenty of mods with multi-language support

**Comment by bartimaeusnek** [comment]
@Traxis It's just my opinion, because i met some spanish guys on the live server who had problems to understand the quests...

**Comment by Traxis** [comment]
@bartimaeusnek I find people like that all the time whenever I play in any english server for most games, don't worry xD
But yeah, I wouldn't recommend this pack to any spanish people who can't read (and understand) English properly.

**Comment by Dream-Master** [comment]
I redo merge and wait until someone will translate it again or fix it.

**Comment by LuigiBaute** [comment]
If you guys explain me the context of the game, I can fix it.

**Comment by richardhendricks** [comment]
Luigi, have you played GT:NH, Gregtech, modded minecraft, or minecraft at all?

**Comment by LuigiBaute** [comment]
I've heard about the game but never got the time to play, what I'm thinking its to see some pictures of the game and the main options to understand the context and be able to fix it... my apologyes if the contribution wasn't pleasent to you guys.

**Comment by richardhendricks** [comment]
Luigi,
  We appreciate your enthusiasm to assist spanish gamers, but I think at this time we would prefer someone with experience in the game to do the translation.
