### ISSUE TITLE
Crop breeding crash

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2613]
#### Which modpack version are you using?
Twitch, 2.0.2.7
# 
#### If in multiplayer; On which server does this happen? 
Single
# 
#### What did you try to do, and what did you expect to happen?
Crop breeding. Two Stickreed crop breeding, wanna get some weed or new seeds.
# 
#### What happend instead? (Attach screenshots if needed)
Crash
# 
#### What do you suggest instead/what changes do you propose?
Halp. I can get more detailed info if needed.

[crash-2018-02-16_02.05.15-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1729704/crash-2018-02-16_02.05.15-server.txt)

Looks like it fixed already in dev...
Gonna try to update Berries mod. Sorry.

**Comment by bartimaeusnek** [comment]
yupp thats the fix
you can either use 1.1.1d the quickfix or update to 1.2.5 but that needs my croploadcore aswell.
