### ISSUE TITLE
Talisman of Remedium breaks top ring slot bauble instead of itself when out of charges

### ISSUE THREAD

**Issue by Dacryphile** [GTNewHorizons/NewHorizons#2615]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
I put on a Talisman of Remedium from Thaumic Tinkerer and gave myself a piece of radioactive dust so it would break down.  Normally, after the talisman cures 100 status effects, it breaks and disappears.  
#
#### What happened instead? (Attach screenshots if needed)
The talisman restored itself to full health.  I had a +1 runic ring in my top bauble slot and when the talisman took its last bit of damage, the runic ring disappeared.  I did this two more times and it happened each time.  I tried with a ring in just the bottom ring slot, and it did not disappear when the talisman took its last damage.  I also tried with a belt but the belt did not disappear either.  
#
Also, when I took the supposed-to-be-broken talisman out of the amulet slot, I could not shift-click it back into the bauble slot or to my toolbar.  When I manually move it to my toolbar then right-click it on a block or on open air, the talisman just straight disappears.  However, I can right-click it on a Thaumic Restorer and it goes inside, gets repaired to full, and then acts like a normal talisman (doesn't disappear when right-clicked, does get shifted to the bauble slot or to the toolbar when shift-clicked in inventory).  It seems like part of the game knows it's broken but the other part doesn't.  
#
#### What do you suggest instead/what changes do you propose?
Destroy the talisman

**Comment by Dream-Master** [comment]
@Namikon @Technus @richardhendricks @mitchej123 @bartimaeusnek  @codewarrior0 
any idea if we can fix this? We have thaumic tinker forked so far i know.

**Comment by codewarrior0** [comment]
Easy.

**Comment by Dream-Master** [comment]
thanks
