### ISSUE TITLE
Large Gas Turbine picky about gases?

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2616]
#### Which modpack version are you using?

2.0.2.7

#### If in multiplayer; On which server does this happen? 

Private

#### What did you try to do, and what did you expect to happen?

Added various gases to a large gas turbine expecting power output into a EV dynamo hatch.

#### What happend instead? (Attach screenshots if needed)

Naphtha Cells + Large Energetic Alloy Turbine (1800eu/t) = EV Dynamo hatch outputs power as normal.
Benzene Cells + Same Turbine = Large explosion.

#### What do you suggest instead/what changes do you propose?

This could just be me not understanding the large turbine tooltip. All hulls. cables, buffers are EV level. Any help is appreciated. Kinda tired of rolling back my base LOL. Benzene is worth less per 1000 than Nap, which is where I'm confused.

**Comment by codewarrior0** [comment]
I haven't looked at the Turbine code in a while, but this sounds like it's related to how the turbine will only burn whole numbers of L of fuel each tick, burning just enough fuel to meet the rotor's flow specification. I think it rounds up, burning just enough L of fuel that it goes *over* the flow spec rather than stopping short.

In other words, be careful when your rotor's flow spec is close to the dynamo hatch's limit - it could easily go over because it rounds up.

**Comment by Axiflare** [comment]
Not sure if I follow, the dynamo hatch can handle up to 2048, the turbine in question only has 1800/t.

Plus it works for one gas but not another.

**Comment by codewarrior0** [comment]
Well, I was wrong, it actually rounds down to get the fuel L/t. What also happens is *after* it calculates the L/t, it applies the efficiency multiplier to increase the EU/t output from that fuel.

So for Naphtha, which burns for 320EU/L, it calculates 5 L/t as the optimal flow, gets 1600 EU/t as the base output, and then multiplies by 130% to get 2080 EU/t, which *should* already be blowing up your turbine.  But you didn't mention fluid regulators, without which it would use 5L * 1.25 ~= 6L/t as the actual flow, for 1920 EU/t base output, then apply a penalty for non-regulated flow, which is `100% - (actual - optimal) / optimal`, or 80%, for a 1536 EU/t base output. Then the turbine efficiency of 130% gets applied for a final output of 1996 EU/t. Turbine doesn't blow up.

Now for the same turbine, same rotor, and no regulator, burning Benzene at 288 EU/L. Optimal flow is 1800/288 = 6 L/t, actual flow is 7L/t, base output is 2016 EU/t, after non-regulated flow penalty of 83.3% base output becomes 1679 EU/t, after 130% turbine efficiency the final output becomes 2183 EU/t. Turbine blows up.

**Comment by Axiflare** [comment]
I think I got it, but where did the 1800 come from in the 1800/288?

**Comment by codewarrior0** [comment]
Right here:

![image](https://user-images.githubusercontent.com/307683/36338331-fff99a7e-134f-11e8-8437-9965dc6a03f0.png)

**Comment by Axiflare** [comment]
Edited previous comment, my bad.

**Comment by codewarrior0** [comment]
>  but where did the 1600 base output come from?

> it calculates 1800/320 ~= 5 L/t as the optimal flow, gets 1600 EU/t as the base output
Rather, I meant

> it calculates 1800/320 ~= 5 L/t as the optimal flow, gets 320*5 = 1600 EU/t as the base output

**Comment by Axiflare** [comment]
Alright I've followed the math 10/10 so far up until fluid regulators, how on earth do they calculate a penalty, and where is this documented?

**Comment by Dream-Master** [comment]
Is this a bug or only a thing we need to mentioned in the quest book ?

**Comment by bartimaeusnek** [comment]
Gasses have different burn Valures in Turbines.

**Comment by CalterOK** [comment]
there is no mistake. but it is worth adding information on the undesirability of using multi-block turbines without regulators. then there is less likelihood that mistakes will be made in calculating the turbine

**Comment by richardhendricks** [comment]
How do you prevent the input hatch from filling before you insert a rotor? Or if you shut off a machine and turn it back on later?

**Comment by codewarrior0** [comment]
Looks like the regulator itself doesn't respond to redstone signals, so you'd have to put a shutter and machine controller on the pipe/tank adjacent to the regulator to turn it on and off.

**Comment by Dream-Master** [comment]
@Axiflare 
can this be closed?

**Comment by Axiflare** [comment]
Yes sorry forgot about this, really appreciate all the info guys!
