### ISSUE TITLE
Maceration Stack Controller too expensive / GT++ Multiblock overview

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2617]
#### Which modpack version are you using?
2,7

Originally this was only for the Maceration Stack Controller, but then became a general look at the requirements of GT++ multiblocks to make sure they are tiered properly.

The question to be asked: When should GT++ multiblocks be available? By design they appear to be between the early game singleblock machines and late game processing arrays. Therefore, I'd go with HV/EV for their availability. Adding to this (after doing part of the list), IV Machine Casings seem to be commonly used among these multiblocks. I don't agree with that and suggest changing them to EV, but that is probably something that needs to be discussed. (An argument against replacing the casings might be that some machines require at least EV energy.)

_Side note: When assessing availability, I didn't necessarily go with earliest (like getting Tungsten from moon dust or end stuff)._

Circuit tiers and alloys of the multiblocks:
---
**Industrial Centrifuge**
Circuit; IV
Alloy: Inconel-792 (Overworld), Maraging Steel-250 (Moon), Tumbaga (OW)
Other: IV Machine Casing (Mars)

**Suggestion:** Replace IV casing with EV to grant access after reaching the moon, 

---
**Industrial Coke Oven** 
Circuit: IV
Alloy: Tantalloy-61 (Mars)
Other: -

Could be changed, but probably no alternative to Pyrolyse Oven.

---
**Industrial Material Press**
Circuit: IV
Alloy: Tantalloy-60 (Mars), Tumbaga (OW)
Other: -

Probably fine since rarely needed. (Might replace the need for multiple ones for AE automation.)

---
**Industrial Electrolyzer** 
Circuit: IV
Alloy: Stellite (Moon), Potin (OW)
Other:

Fine.

---
**Industrial Maceration Stack**

Circuit: ZPM
Alloy: Tungstencarbide (Mars), Inconel-625(Moon?)
Other: Palladium Plate (Might require a T3 rocket?, IV Casing

**Suggestion:** Change Circuit to IV. Maybe discuss changing Palladium to T2 planet material.

---
**Industrial Wire Factory**

Circuit: IV
Alloy: Zeron-100 (Mars)
Other: IV Casings

Probably fine, because wires are fast anyway. Optionally change casing to EV.

---
**Matter Fabricator**

Circuit: IV
Alloy: Quantum (when is Americium available), Niobium Carbide (T3? I have Niobium, but the spreadsheet only has it at T6/7), Inconel-792 (Niobium as well)
Other:

I don't know when UU-Matter becomes relevant.

---
**Alloy Blast Smelter**

Circuit: HV
Alloy: Zirconium Carbide (OW), Tumbaga (OW), Staballoy (Mars)
Other: 

**The Staballoy gates most other Multiblocks behind a T2 rocket. Should this be changed?**

---
**Power Sub-Station** _Add later_

Circuit: 
Alloy:
Other:

---
**Gregtech Multitank** _Add later_

Circuit:
Alloy:
Other:

---
**Conpact Cyclotron** _Add later_
Circuit:
Alloy:
Other:

---
**Fission Fuel Processing Unit** _Add later_

Circuit:
Alloy:
Other:

---
**Tree Farmer**

Circuit: -
Alloy: Eglin Steel (OW), Tumbaga (OW)
Other: MV Casing

Should be fine, early MV available.

---
**Industrial Sifter**

Circuit: MV
Alloy: Eglin Steel (OW)
Other:

**Discussion:** Available early MV, could be pushed back by increasing Circut tier or adding higher tier alloy like Stellite.

---
**Industrial Thermal Centrifuge**

Circuit: EV
Alloy: Talonite (OW)
Other: Noise Hazard Signs count as casings, nice.

Seems fine.

---
**Industrial Ore Washing Plant**

Circuit: EV
Alloy: Grisium (Moon), Talonite (OW)
Other:

Looks fine.

---
**Thermal Boiler**

Circuit: IV
Alloy: -
Other:

Can't really judge without testing.

---
**Large Scale Auto-Assembler v1.01** _Add later_

Circuit:
Alloy:
Other:

---
**Industrial Cutting Factory**

**Controller doesn't have a recipe.**

Circuit:
Alloy:
Other:

---

**Comment by codewarrior0** [comment]
The Cutting Factory is made with Platinum Wires, Maraging Steel Plates, HV Circuits, and an EV Cutting Machine - so that's a Moon trip.

**Comment by Dream-Master** [comment]
I can do later some recipe change and pull it to gt++ side but not for the next update

**Comment by mtesseracttech** [comment]
This is a general trend I have noticed too with GT++. That the recipes don't seem to exactly align with their intended purpose. Indeed they all seem to be intended between single blocks and the processing arrays. But often their functionality is only a little bit better than the single block machines, at the cost of expensive materials, circuits that are many tiers above what one would expect (even above the processing arrays). Which makes them not that attractive in the end, since they of course also come with all the headaches that GT multiblock machines come with (outputs that void items when the bus/hatch is full, maintenance, just a large amount of space in general). It would be nice if there was some tuning in that aspect.

**Comment by benstuwie** [comment]
PA's of 64 are always better, and available at IV so seeing these below IV would probably be a good idea. Not the UU one, or power substation. Matter fabricator one should be UV,  because I think it's significantly better than single block ones. Substation should cost some really ultimate batteries because of how useful it is. It can store an ultimate battery worth of power, while also having a built in transformer, and works for all power tiers.

**Comment by codewarrior0** [comment]
FWIW, the GT++ multiblocks don't void items.

**Comment by mtesseracttech** [comment]
@benstuwie it might be a good idea to tell what the substation is, since there is nothing about it online. knowing what it does and why it is so good would give a good idea if it should have a more/less expensive recipe.

**Comment by draknyte1** [comment]
So, this needs a total review since GT++ 1.7.0 and later rework Multi's to be several factors better. (and they work)

**Comment by Wolozo7** [comment]
Will test them next week, the parallel processing looks nice. At first glance I still find the Blast Smelter Heat Containment Coils problematic, because they gate a lot of the alloys behind titanium, but I need to find out which multiblocks are affected by that.

**Comment by draknyte1** [comment]
A lot of the simpler alloys (<= 4 ingredients) can be mix crafted and smelted from dust form. Keep that in mind.

**Comment by richardhendricks** [comment]
GT++ tiering has been revised.
