### ISSUE TITLE
Suggestion: Nodal Mechanics

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#262]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2193499-thaumcraft-nodal-mechanics

Basically allows you to craft your own nodes with a massive amount of essentia.
Could be tiered at Tier 9+

**Comment by Namikon** [comment]
Mod is open source, we could fork it, and change/remove/alter the recipes to our liking, or even come up with fancy new ways to craft aura nodes

**Comment by Dream-Master** [comment]
i look inside it too.

**Comment by Drobac** [comment]
many +++++ for the mod

**Comment by Dream-Master** [comment]
On the Testserver allready.

**Comment by Dream-Master** [comment]
In the Testpack for testing.
