### ISSUE TITLE
Witchery quick lime not able to be made

### ISSUE THREAD

**Issue by KirakoMM** [GTNewHorizons/NewHorizons#2620]
#### Which modpack version are you using?

#2.0.2.7
#### If in multiplayer; On which server does this happen? 

# Single player
#### What did you try to do, and what did you expect to happen?

# i tried to make quicklime from witchery, and it turns it in to greg tech quick lime dust, i have looked on github for answers and it seems you should be able to put the dust back in a crafting table to be made in to witchery quick lime but instead it turns in to small piles of quick lime dust we have tried this in all four slots in our inventory and in all 9 slots in the crafting bench
#### What happend instead? (Attach screenshots if needed)

# it made greg tech quick lime
#### What do you suggest instead/what changes do you propose?
Quick lime to be obtainable

**Comment by Dream-Master** [comment]
and this is fixed allready. Next release.

**Comment by KirakoMM** [comment]
Perfect thank you so much will try figure a way round it for now, loving the mod pack, thanks for many many many hours of enjoyment
