### ISSUE TITLE
Electrolyzer Wishes

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2622]
So I am working on the polyphenyle sulphide line and in there is the step from benzene + chlorine to dichlorobenzene. I don't have any personal use for the hydrochloric acid it gives (these kinds of byproducts are more of a bother than anything in the greater picture of automation X) ) but I do want to conserve my chlorine.  I then discovered I would have to add steps in between to get the hydrochloric acid to a form I can electrolyze. Can we get a recipe for the electrolyzer to work on the cells, instead of purely on the fluid?

It would also be nice to have a fluid only version of the water > hydrogen + oxygen line, since it's a bit silly right now. Right now it is cells only, and it neccessarily includes a step in between that is "electrolyzed water" (whatever that may be...). I understand there to be a need for a cell in the last step, but that could be solved with a cell + circuit I think.

**Comment by mtesseracttech** [comment]
Adding to the base, here is the current situation with the acid:
It is a byproduct from chlorine + benzene: 
![image](https://user-images.githubusercontent.com/11915663/36353812-52d55b26-14cb-11e8-8ff9-4078ab615870.png)
And as seen the only way to do the electrolyzer step is in cells. (The second page just switches around the hydrogen and chlorine)
![image](https://user-images.githubusercontent.com/11915663/36353827-947f5c66-14cb-11e8-9295-788d1e324572.png)

For the water > H + O:
Currently it is this strange cells only line:
![image](https://user-images.githubusercontent.com/11915663/36353890-b57c0c10-14cc-11e8-8fb8-4063aa5a1ea4.png)
![image](https://user-images.githubusercontent.com/11915663/36353891-b88de13a-14cc-11e8-8bb5-446eb520e41f.png)
Which I think is unneccessarily heavy on the cells, and it require extra infrastructure to deal with the cells if you want fluids as fluids in your ME, and not as cells. (which at least is the case for me, with cells being pricey)

**Comment by mtesseracttech** [comment]
Ah another thing to mention, the electrolyzed water has some degree of functionality in IC2, but it's not used for anything in this pack. So why even have it in there, let water just be treated like other liquids and be converted in 1 step.

**Comment by Dacryphile** [comment]
You can convert water in one step -- 3 buckets of liquid water with a programmed circuit set to 1 and an empty cell in the other input slot.  Makes 2 hydrogen and 1 nitrogen in 100 seconds.

**Comment by mtesseracttech** [comment]
@Dacryphile Talked about it to Dream, the other processes will be tweaked a bit. (They are brought back to 30 seconds for 3000mb water > 1000mb oxygen + 2000mb hydrogen). There is no real justification for it to take 4x as long without the electrolysed water cell step.

**Comment by MineAnPlay** [comment]
It's supposed to take 75 seconds... Not 30. The electrolyzer recipe makes ONE per 24.5s so a total of 75s (3*24.5 + 1.5). If you make it 30s it will cause a LOT of imbalances.

**Comment by Dream-Master** [comment]
That's true will change it back like it was.

**Comment by richardhendricks** [comment]
What's the final decision on the HCl -> Cl issue?  It's faster right now to make Cl from salt than recycling it from HCl.

**Comment by Dream-Master** [comment]
Idk make a decision @richardhendricks

**Comment by mtesseracttech** [comment]
@richardhendricks Since it is a fluid you get back from so many processes, I think it's just fine that you can have this recipe. Since often the primary fluid you get back from a process should be kept as fluid (For the next step) and the HCl comes out as cells. Being able to put these cells into the electrolyzer directly, without an unnecessary tank step in between seems like a nice thing (especially since there are so many recipes that allow you to do cells directly already).

**Comment by richardhendricks** [comment]
I agree, please add a recipe to electrolyze HCl cells into H cells and Cl gas with one circuit, H gas and CL cells with a different circuit, and a  third recipe to just make Cl and throw away the H. Make it 75% of the time to electrolyze NaCl.
