### ISSUE TITLE
Kinetic generators quests should be oredict

### ISSUE THREAD

**Issue by luansantospinto** [GTNewHorizons/NewHorizons#2624]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
The quest for Kinetic Water and Wind generators uses IC2 circuit only, not oredict.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Change the quests to oredict like the recipes.

**Comment by Dream-Master** [comment]
Will check
