### ISSUE TITLE
[Suggestion] OpenFM

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2625]
#### What do you suggest instead/what changes do you propose?

I suggest that we use OpenFM, which is a mini-addon-mod for OpenComputers, allowing players to craft radios and listen to streams on the Internet. The mod is MIT-Licensed and Open Source. Its also <1Mb in size so it won't affect loading too much.
Heres the GitHub:
https://github.com/PC-Logix/OpenFM

**Comment by Dream-Master** [comment]
We have so much radio mods in the past not sure many people realy need it or is it possible to make it client side only?

**Comment by bartimaeusnek** [comment]
@Bryfer i want a server-side radio that annoys people visiting my base 😛

**Comment by mtesseracttech** [comment]
I'd be in favor of this, but the amount of people in favor might be limited because I don't think that many people use OpenComputers, with how heavily gated it is. (and lua might be a problem for some)

**Comment by Dream-Master** [comment]
MAybe later
