### ISSUE TITLE
[Suggestion] OpenComputers

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2626]
#### Which modpack version are you using?
2.0.2.7

#### What do you suggest instead/what changes do you propose?
I recently started OpenComputers and while crafting all these Items for it, it seemed like they were balanced pre 2.0. In my opinion they definitly need a rework. For example: RAM Chips need Open Computer Transistors and LV Circuits, but imo it would make more sense if we would make them requiere a cut RAM wafer from the circuit upgrade, some transistors from the circuit upgrade, some circuit board (plastic one?) and move them into the circuit assembler. The open computer transistors should also be replaced with the ones from the Gregtech update.

**Comment by Dream-Master** [comment]
Sure the whole mod need recipe changes

**Comment by Dream-Master** [comment]
Henny do a lot of recipes into the core mod. The rest need to be nerfed by one of us.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/727
