### ISSUE TITLE
EMT Solars not connecting to anything?

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2627]
#### Which modpack version are you using?

2.0.2.7

#### If in multiplayer; On which server does this happen? 

Private

#### What did you try to do, and what did you expect to happen?

Autocrafted a few compressed solars from Electro-Magic Tools and tried to get the power anywhere in my GT power grid.

#### What happened instead? (Attach screenshots if needed)

EMT Solars won't attach to any cables from GT. They will attach to a batbox, but then that won't connect to buffers or wires. (facepalm)

![emt solar](https://user-images.githubusercontent.com/36259908/36369238-22539f9e-1520-11e8-80fd-6dba362d31d9.png)

#### What do you suggest instead/what changes do you propose?

Make it so you can transfer the power from an EMT solar panel directly to a GT buffer, or at least let the batbox connect to GT cables as an intermediary please.

Edit: Also, this is by far my all time favorite pack so far! Keep up the awesome work all of you!

**Comment by Dream-Master** [comment]
@bartimausnek any idea?

**Comment by codewarrior0** [comment]
You need to use a GT transformer to convert IC2 power to GT power.

**Comment by Axiflare** [comment]
@codewarrior0 Worked like a charm! EMT Solar > Batbox > GT Transformer > Success!

Thanks!
