### ISSUE TITLE
[Suggestion] Centrifuge recipe for dissassembling fire charges

### ISSUE THREAD

**Issue by thcv** [GTNewHorizons/NewHorizons#2628]
#### Which modpack version are you using? 2.0.2.7

#
#### If in multiplayer; On which server does this happen? Prospercraft

#
#### What did you try to do, and what did you expect to happen? 

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
@thcv why you want a recipe for it ?

**Comment by thcv** [comment]
Well, without one they are pretty useless.

**Comment by Dream-Master** [comment]
Ok i will check if it is exploidable and add a recipe.
