### ISSUE TITLE
[AE2] NullPointerException at QuantumCluster.java:70

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#2629]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Crash when go The Last Millenium or Void world
https://pastebin.com/TCVGKcjR
#
#### What happend instead? (Attach screenshots if needed)
it looks like the problem is appliedenergistics although it crash but when i restart the game i still can get in Void world and Last Millenium but when you back to overworld and go these world it will still crash sometimes (maybe other world have same problem?)

**Comment by FallDark** [comment]
Test with ae quantum ring in overworld and void world and try many times go between these world it crash with same problem

**Comment by Dream-Master** [comment]
```
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

@FallDark  Can you launch Minecraft with another launcher than multi mc to be sure it crash too?

**Comment by FallDark** [comment]
use HMCL launcher still crash and i delete some mod to test it awful to start the game
https://pastebin.com/qBhTFhqL

**Comment by Dream-Master** [comment]
So a AE2 problem i guess. 
@bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
already looked at it yesterday 
```
    at appeng.me.cluster.implementations.QuantumCluster.onUnload(QuantumCluster.java:70)
```
tried to fix this with a null check, didnt worked tho, im still working on it. @Dream-Master

**Comment by bartimaeusnek** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2235
