### ISSUE TITLE
Suggestion: Thaumic Machina

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#263]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2200956-wip-1-7-10-open-beta-thaumcraft-4-2-addon-thaumic

You can upgrade your wands to carry more vis, have more discount, enable the wand to drain vis from taint (basically, with a price to pay..) or all of them (Which will make the wand unstable, spoiler..)

Could be a nice addition to the existing wand-cap exchange thing

**Comment by Dream-Master** [comment]
Will test it.

**Comment by Dream-Master** [comment]
In the Testpack for testing.
