### ISSUE TITLE
Printed Cirtuit Board recipe (Open Computers)

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2630]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
need to be moved into chem reactor in my opinion, suites much better(since all GT circuit boards made in chem reactor)
![2018-02-19_20 13 44](https://user-images.githubusercontent.com/25028786/36389799-8e3b22f4-15b1-11e8-941d-62e74935dff9.png)

**Comment by benstuwie** [comment]
What's the fluid in that recipe?

**Comment by Dream-Master** [comment]
Sure the whole mod needs to be nerfed.

**Comment by Dream-Master** [comment]
Sulfuric acid @benstuwie

**Comment by Dream-Master** [comment]
**[Suggestion] OpenComputers #2626
