### ISSUE TITLE
Remove blue steel from the high tier loot bag tables

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#2631]
#### Which modpack version are you using?
Most recent
#
#### If in multiplayer; On which server does this happen? 
Any server would have this, but it happened on delta
#
#### What did you try to do, and what did you expect to happen?
Enchanting 4 tier 6 loot bags and getting decent loot
#
#### What happend instead? (Attach screenshots if needed)
I only got a few blue steel ingots from the loot bags...
![image](https://user-images.githubusercontent.com/11915663/36396422-6b9a6950-15be-11e8-911e-9e519909b92a.png)
Low tech garbage.
#
#### What do you suggest instead/what changes do you propose?
It seems to be there as a joke (blue on the delta server is a bit of a meme), but it's a really bad reward from tier 6... especially since it's on the non garbage list. It would be fine if it's on the bad rewards list.
The resolve would be to remove it from the good rewards list and maybe reimburse the people who lost chances at loot this way.

**Comment by mtesseracttech** [comment]
The line in the xml file for lootbags are:
https://github.com/GTNewHorizons/NewHorizons/blob/2a5cc18c17169ea70fc6cccf46053ee9621f472a/config/EnhancedLootBags/LootBags.xml#L384

The one before it is for silicon ingots, which I also think is better to not be there.
https://github.com/GTNewHorizons/NewHorizons/blob/2a5cc18c17169ea70fc6cccf46053ee9621f472a/config/EnhancedLootBags/LootBags.xml#L383

Also I noticed some loot bags at the start of the tier 6 list, that are a bit obsolete now:
https://github.com/GTNewHorizons/NewHorizons/blob/2a5cc18c17169ea70fc6cccf46053ee9621f472a/config/EnhancedLootBags/LootBags.xml#L372 I think may used to have been some circuit, now it's some random circuit component (not really useful as is)

https://github.com/GTNewHorizons/NewHorizons/blob/2a5cc18c17169ea70fc6cccf46053ee9621f472a/config/EnhancedLootBags/LootBags.xml#L373 had more use in the early times of the pack, now much less so (only for fluid processors and lapotronic energy orbs)

**Comment by benstuwie** [comment]
I think it's there because t4 is EV, and EV batteries use that. Still though, you're right, it's kind of worthless.

**Comment by mtesseracttech** [comment]
@benstuwie it's for tier 6.... (IV+) which is even worse.

**Comment by Dream-Master** [comment]
I put them to tier 4(both silicon and Blue steel)I add Tungstensteel to IV Bag.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/36503074-3f6daa88-174c-11e8-8b88-6146b6dddc98.png)

**Comment by mtesseracttech** [comment]
I think silicon is even too bad for tier 4, I mean, you need it on LV already.

**Comment by Dream-Master** [comment]
ok will give it into loot bag 3 mv
