### ISSUE TITLE
Issues with questbook - Reverting to Tier 0 by itself

### ISSUE THREAD

**Issue by Kai03** [GTNewHorizons/NewHorizons#2632]
Hello, my girlfriend has problem with her questbook. She reached tier 1 and was crafting the glass and finished the game after that. With the next start up of the game, her questbook was reverted to tier 0.  Recently she reached tier 0.5 and after starting the game again her questbook reverted again to tier 0. Any suggestions on how to deal with this issue?

**Comment by richardhendricks** [comment]
That sounds like you are either playing offline or using a hacked/cracked version of Minecraft.  Better questing using the Mojang UUID to track your progress, and offline/hacked/cracked versions change UUID each time. Can you confirm you are using a legit version of MC and are online?

**Comment by Kai03** [comment]
Hmm It's definitely a legit version of minecraft, but shes playing sometimes online and sometimes offline. Could this be the cause?

**Comment by richardhendricks** [comment]
Definitely.  When MC can't get online to retrieve the UUID from the Mojang servers, BetterQuesting cannot properly save your information.

**Comment by Dream-Master** [comment]
@Kai03 Try to play always online if sp and you can auto complete quests with a code or in edit mode to recover your old quests.

**Comment by Kai03** [comment]
The commands will be useful, thank you for the help. My girlfriend doesn't have stable internet access so she might get her questbook reseted again but now at least she can recover her old quests. You can close this topic, thank you again ^^
