### ISSUE TITLE
NPE: Ticking entity at PotionEffect.onUpdate crash

### ISSUE THREAD

**Issue by KirakoMM** [GTNewHorizons/NewHorizons#2633]
#### Which modpack version are you using?

#2.0.2.7
#### If in multiplayer; On which server does this happen? 

# single player lan server
#### What did you try to do, and what did you expect to happen?

# tried to login and crashed to desktop then tried to log back in and constantly crash to desk top on log in
#### What happend instead? (Attach screenshots if needed)

# crashed
#### What do you suggest instead/what changes do you propose?
N/A

A full break down of what happened just in case it helps; me and husband are playing on a lan world and just completed the quest Bloodlust: "cain sword"
we enchanted the cane sword we received as a reward in the osmotic enchanter and husband tested damage on me (whilst wearing fulling enchanted void robes), the damage seemed to bypass my armor killing and crashing me.
Couldnt get back in, so husband broke my grave to get my items back, we then deleted my player.dat file.
This allowed me to enter the game again, i then played for a few minutes and did some witchery etc and i then got attacked by a owl, husband killed the owl and now i getting the same error, any suggestions would be welcome, here is the crash report
https://pastebin.com/Pm1uQXM9

**Comment by Ugachaga** [comment]
Seems Witchery / Osmotic Enchanter incorrectly register some PotionEffect. As a quick fix just turn off the Status Overlay in Adventure Backpack settings (graphics -> status -> enable overlay -> false). This should let you login into the game. Then use `/iih` command while holding the "cain sword" in hand and post the result here.

**Comment by bartimaeusnek** [comment]
Since Witchery is closed souce and the auther is gone, we can't do anything about it.

**Comment by KirakoMM** [comment]
Hi, thank you for your help, i am still not being able to get in game and have a new crash report for you https://pastebin.com/s0nLdmfb
Also i have added a screen shot
https://scontent-mxp1-1.xx.fbcdn.net/v/t34.0-0/p280x280/28232903_1999767573611189_1744637080_n.jpg?_nc_ad=z-m&_nc_cid=0&oh=ecb8ed7d2e14c56d7705fd9b1b2a1210&oe=5A8E31F7

**Comment by Ugachaga** [comment]
Great, now we can remove "Adventure Backpack" from the title ;)
The next step I'd try to remove all active potions effects on the player through the NBT Editor (make sure to do it on server too) and no longer use this sword.

From new crash report:
```
java.lang.NullPointerException: Ticking entity
    at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
```
`func_76455_a` = `onUpdate`. Vanilla code:
```
public boolean onUpdate(EntityLivingBase p_76455_1_)
{
    if (this.duration > 0)
    {
        if (Potion.potionTypes[this.potionID].isReady(this.duration, this.amplifier))
        {
            this.performEffect(p_76455_1_);
        }
        this.deincrementDuration();
    }
    return this.duration > 0;
}
```
Same issue: https://github.com/Mithion/ArsMagica2/issues/1442

**Comment by KirakoMM** [comment]
I removed the active potion effects as suggested above and it allowed me in to the game only for me and my husband to fight a eldritch and it to crash me, the sword cane has been removed, and we were both using the sword of the zephyr with enchants ( we have been using these sword for a week with no issues)

**Comment by KirakoMM** [comment]
Also dont know if it relevant but it suddenly says im in a tainted biome, eg the grass is purple and it shows as being a taint biome but there are no actual signs of taint, but my husbands game whom is hosting states it is still magical forest, again dunno if its coincident or not but worth mentioning, as this seemed to be when my crashes started, thanks again for all you help

**Comment by Ugachaga** [comment]
In which version of GTNH the world was created (roughly)?
Did you ever add/remove mods to the modpack (especially some with additional potions)? Did you change any potion-related configs (especially potion IDs)?

Which IDs of active potion effects you removed? Which potions correspond to these IDs?

**Comment by KirakoMM** [comment]
We created the world in 2.0.2.6, we have added the Morpheus mod so one can sleep without both needing to sleep to skip night.
The configs we have changed is thaumcraft research to normal mode, elevators being able to reach futher, and the open block tanks have been enabled.
And after crashing again and going to check the potion ids it has rolled back and no made any ids for me to check or delete

**Comment by KirakoMM** [comment]
After another crash i have some active effect id's for you, they are-
Ambient 1 Amplifier -1 Duration 221 Id 16
Ambient 0 Amplifier 1 Duration 50 Id 2
Ambient 1 Amplifier 3 Duration 1241 Id 29
Ambient 0 Amplifier 1 Duration 50 Id 127
The crashes seem to happen when i get hit by my husband by anything, no matter if its enchanted or not, even if its a aoe from the boots of the meteor

**Comment by Ugachaga** [comment]
Well this did not looks like modpack issue. However, you may dump potion IDs (via NEI) and see if there IDs overlapping or using IDs < 1 or IDs > 127.

Most likely it's mod bug. You may try to delete your husband's player data, or do more tests to determinate what exactly is going on, but all this will be time consuming. It's easiest to roll back to the previous save without this bug.

**Comment by KirakoMM** [comment]
As its lan server i deleted my version of the game including all back ups, re downloaded it from scratch this seems to have fixed not only the biome but i can now be hit without it crashing me, i guess for whatever reason my config files got rearranged and its not that they were incorrect, its that they wasnt the same as my husbands

**Comment by KirakoMM** [comment]
Thank you for all your help, if we ever find out what caused this we will be sure to let you know.

**Comment by richardhendricks** [comment]
Sure, that would be great.  Glad to hear you were able to get everything working again.  Go forth, and hunt for ores! :pick:
