### ISSUE TITLE
No large chemical reaction recipe for styrene 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2635]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
Styrene used to have a recipe in the large chemical reactor, but it seems to be gone for some reason. It's a needed fluid for making cables and some assembly line parts. It had a recipe in the LCR in version 2.0.1.3 but for some reason it seems to be gone now.

**Comment by Dream-Master** [comment]
will check
