### ISSUE TITLE
vibrant alloy ingots can be made without EBF

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2636]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to check which circuit is used in the recipe of hot vibrant alloy ingot
#
#### What happend instead? (Attach screenshots if needed)
I saw in NEI that you can bypass EBF:
![2018-02-20_21 21 10](https://user-images.githubusercontent.com/12850933/36447327-5a7c1f08-1684-11e8-875f-ffa931a362a6.png)

#
#### What do you suggest instead/what changes do you propose?
Please remove this recipe as it doesn't make any sense

**Comment by Dream-Master** [comment]
Yes this issue is old and fixed.
