### ISSUE TITLE
Missing alternate record for nitric acid in LCR

### ISSUE THREAD

**Issue by Dacryphile** [GTNewHorizons/NewHorizons#2637]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
The regular chemical reactor has two different recipes for Nitric Acid - one with 1 water, 1 oxygen, and 2 nitrogen dioxide for 2 nitric acid and 2 empty cells, and another with 1 water and 3 nitrogen dioxide for 2 nitric acid and 1 nitric oxide cell.  However, the LCR only contains the recipe for 3 nitrogen dioxide + 1 water.  Could the other recipe that only needs 2 nitric oxide and 1 oxygen and 1 water be added, preferably with a different circuit #?  There's also a duplicate recipe for 3 NO2 + 1 water that doesn't need a circuit, I'm guessing that can be removed.  

Chem reactor: 
![image](https://user-images.githubusercontent.com/9247381/36450075-0a90a26e-164a-11e8-8e85-0d01bd5f5639.png)

![image](https://user-images.githubusercontent.com/9247381/36450097-18dd11e0-164a-11e8-92e0-50556adef28b.png)

LCR: 
![image](https://user-images.githubusercontent.com/9247381/36450055-fd8388d4-1649-11e8-8312-f6486795d617.png)

**Comment by Dream-Master** [comment]
Will check if I can change it.
