### ISSUE TITLE
Can't Load my world

### ISSUE THREAD

**Issue by Alexusexcel** [GTNewHorizons/NewHorizons#2638]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
Can't Load my world! [Server thread/ERROR]: Skipping event FMLServerStoppedEvent and marking errored mod ae2wct since required dependency appliedenergistics2 has errored
#

**Comment by Dream-Master** [comment]
@Alexusexcel 
Fist of all not so long Titels. Add info into the issue please.
Second: I need a full fml log or crah log.
Thanks

**Comment by Dream-Master** [comment]
Which modpack version are you using?
If in multiplayer; On which server does this happen?
What did you try to do, and what did you expect to happen?
What happend instead? (Attach screenshots if needed)
What do you suggest instead/what changes do you propose?

**Comment by richardhendricks** [comment]
Third:  Once this issue is resolved, install a backup mod or do regular backups from your command line.  Make sure you get the Backpacks and Journeymap directories too.

**Comment by Dream-Master** [comment]
@Alexusexcel i need a n update on this otherwise i close this issue.
