### ISSUE TITLE
Dragons not dropping Dragon essence

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#2640]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Killed a few of the dragons, each is supposed to drop dragon essence but none did. Tried by killing the chaos dragon, the ressurected dragon with DE, a ressurected dragon with Bee mechanics and a command spawned dragon. None dropped it
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Crafting recipe in the assembler with Dragon heart (not consumed) and some draconium dust = Dragon essence.

**Comment by Dream-Master** [comment]
I can add it to the dragon via Mob properties so far i know. But i can add it via recipe also.
@Drobac how much they drop normaly ?

**Comment by Dream-Master** [comment]
I add 2 Quests for buy ender essense.
