### ISSUE TITLE
[2.0.2.7] Easy unlimited calcite in early game.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#2642]
You can skip searching for lapis orevein and just use the following recipes:

1) 8 stone + Lime Dye = 8 Limestone (Biome O' Plenty)
2) Chisel + Limestone (Biome O' Plenty) = Limestone (Chisel)
3) Macerator + Limestone (Chisel) = 4 Calcite Dust

Lime Dye can be made with cactus and bones. This means that you can turn Stone blocks into calcite with almost zero cost. Maybe this is not an issue and is intentional - I am reporting this just in case you didn't know about it.

**Comment by Dream-Master** [comment]
maybe make recipe assembler recipe to promote to finding a lapis vein

**Comment by Methes** [comment]
Is it really important to tinker with? Calcite is needed just for BBF, one needs to find Lapis vein anyway later on AND you can get it from XP buckets.

**Comment by Dream-Master** [comment]
@Methes so no changes are needed ?

**Comment by Drobac** [comment]
Agreed with Methes, its not that big of a problem and it allows for later automation to help with already complicated circuits

**Comment by codewarrior0** [comment]
I once joked that the BoP Limestone should be made with 8 Stone and a Lime from a Lime Tree.

**Comment by richardhendricks** [comment]
Yeah I don't think it's a big deal.  Maybe we could even mention it in the quest for players that are having difficulty finding Lapis.

**Comment by Lainiel** [comment]
In my opinion marble should macerate directly into calcium carbonate. This would remove the requirement to find the lapis vein just to make BBF. It would make more sense then to combine lime with stone to make limestone.

**Comment by mtesseracttech** [comment]
To me this one seems fine too. It's a little fun way to get around the early game grind to get that vein (which you don't really need again till much later), that you will only find if you look really well.
There could even be a short quest that would explain this path.

**Comment by Dream-Master** [comment]
Yea i think it is not a big issue. Will check what i can change.
