### ISSUE TITLE
[BetterQuesting] Quest database and progress corruption upon load

### ISSUE THREAD

**Issue by pgelinas** [GTNewHorizons/NewHorizons#2643]
It's the second time it happened to me, upon load of my single player game I get a bunch of notification about "New Quest" being completed. Opening my quest book I see a bunch of tabs now unlocked (example, 2048EU tab while I'm still on 32EU) with completed quest without description, all with "New name" and a Nether Star as icon. Unfortunately I don't have a screenshot or the QuestDatabase.json to show, as I've already fixed this part. Also, this happens randomly, and has only happened twice in the past month, since the update to 2.0.2.x

It's annoying, but I can manage to fix it manually by deleting the QuestDatabase.json in my saves folder. The quest descriptions are properly reset, but all those quests stay completed. I have to manually edit the QuestProgress.json file and reset the completion state of those quest; they all have the same "completed timestamp" so they are easily searchable.

I'm writing a small tool program to automatically fix this in case it ever happens again. However, doing so my json parser (Jackson) tells me there's an invalid UTF-8 character in the quest database: in the "questID": 742, 

"display:10": {
            "Name:8": "�fSteel Hammer"
          }

appears twice. Notice the weird '?' character, that's an invalid UTF8 sequence.

#### Which modpack version are you using?
2.0.2.7

#### What do you suggest instead/what changes do you propose?
Fix that quest (tinker's construct hammer) to avoid invalid UTF-8 characters. Might be related to the database corruption I'm seeing, who knows?

**Comment by pgelinas** [comment]
Seems like there's more: 
"questID": 743
"questID": 744
"questID": 862
"questID": 863
"questID": 864
"questID": 1105
"questID": 1150
"questID": 1151
"questID": 1154
"questID": 1156

Most of them are Tinker's construct tool, except for 1105 which is the Division Sigil and the invalid character is in the description.

**Comment by Dream-Master** [comment]
idk how to fix.

**Comment by pgelinas** [comment]
I've just manually removed the invalid character in my QuestDatabase.json and fixed my QuestProgress.json afterwards. I'll be loading up the game soon to see how the affected quests show up in the book, it should be related to their display name, with the tooltip or on the quest page itself. We'll see.

**Comment by bartimaeusnek** [comment]
QuestDatabase.json is ANSII Coded not UTF-8. Stuff like "�f" is used for styles in the text.

**Comment by pgelinas** [comment]
Hmmmm, that would make sense. I'm just not used to seeing Json files in something else than UTF-8. Alright then... but my issue of database and progress corruption still stands 😃

**Comment by richardhendricks** [comment]
Are you having connection issues to Mojang's UUID servers?  BQ relies upon your UUID to track quest progress, and if the UUID server isn't available it will autogenerate a fake one.

Otherwise it seems like it may be a reliability issue with your HD or RAM?

**Comment by pgelinas** [comment]
It's only some of the quests that are affected, not all. If it was an UUID issue I would expect all my quests to be affected. Even quests that I have not completed and are way ahead in term of progression gets suddenly "erased" (changed to New Quest) and marked as completed. I'm thinking it's more related to the quest database itself, since those "New Quest" don't have any completion requirement they automatically get marked as completed by BQ.

I doubt it's related to HD (since I have an SSD 😛) or RAM issue; I don't want to scratch that yet, but since it happened only twice in a month's time and I play almost daily, I would have expected more issues than that.

Thanks for the input though!

**Comment by Dream-Master** [comment]
@bartimaeusnek are you able to fix the issue showing up wrong sings ?

**Comment by pgelinas** [comment]
@Dream-Master The wrong signs are not an issue after all, just a text encoding mismatch. No impact on the gameplay whatsoever. 

My real issue is those "New Quest" popping up, I'll grab a screenshot the next time it happens, with the resulting QuestDatabase.json. Might an issue with BQ itself more than the modpack though...
