### ISSUE TITLE
Add backup plugin to the modpack

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#2644]
Everything can go really wrong with just a simple power outage. Your world gets corrupted chunks and your quest progress can get completely wiped out. In my opinion the pack really needs some default backup plugin that makes regular backups.

**Comment by Dream-Master** [comment]
If you need a backup mode just add one.

**Comment by Lainiel** [comment]
Yes, I can add it on my side, but I still think there should be a default backup plugin, because the pack is really unstable to unexpected crashes. As I said a single crash can wipe all your quest progress, corrupt chunks and there's no way to restore quests without any backup. The only way is to manually complete all the quests and then claim the rewards and trash them. I'd rather prefer having a default backup plugin with a config option to disable it for people that don't have enough space to keep a few backups.

**Comment by Dream-Master** [comment]
I play the pack since December with my dev version that update every day and i not run in any crash. I save my files every day one time (copy save folder) i never used a mod for it and i dont see a reason to add one and make the loading time for my pack worse.

**Comment by Lainiel** [comment]
I'm willing to bet most of the people playing do not make manual backups by copying the world folder every day like you. I know that the server rarely crashes in it's own, but what I'm talking about is computer crash or power outage or something like that. Try to pull your computer from the socket while playing and you'll see what I mean.

**Comment by bartimaeusnek** [comment]
https://minecraft.curseforge.com/projects/aromabackup
feel free to add it yourself.

**Comment by Lainiel** [comment]
Sadly aroma backup adds new items, so I can't use it serverside only. When someone connects without having it installed on the client too they get "Fatally missing blocks" error. I'd have to distribute it to all the players that want to play on the server every update.

**Comment by bartimaeusnek** [comment]
wait, if youre on a server, just add a cronjob that backups your save folder everytime you restart
