### ISSUE TITLE
Mod Suggestion: Super Tic

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2646]
#### Which modpack version are you using?
2.0.2.7
#
#### What do you suggest instead/what changes do you propose?
Originally I wanted to request adding ExtraTiC, to add some of the Metallurgy Metels, that are in GTs Material class, to make them useful again (at least for TConstruct tools). Then I saw that ExtraTiC is closed source, so I knew that nobody here would accept it. So I made a mod that does nearly the same, but it is highly configurable. It checks for all registered Toolmaterials (TConstruct) and allows to add a potion effect to the attacker or the creature getting hit. It might also solve #2583. 

The mod is called Super Tic: https://minecraft.curseforge.com/projects/supertic

Would be cool if you could add it (I think it doesn't even takes longer to load)

**Comment by Dream-Master** [comment]
@Zoko061602 can you gibe me more infos and a example config to try this mod out. Thanks

**Comment by Zoko061602** [comment]
What kind of infos do you need?

Config: https://pastebin.com/eBpbxWs6

**Comment by Dream-Master** [comment]
Effect = 2 what it mean? Duration is I understand.

**Comment by Dream-Master** [comment]
Amplifier means the level of the Effect?

**Comment by Ethryan** [comment]
Effect = PotionID i think

**Comment by Zoko061602** [comment]
@Ethryan It uses potion ids

**Comment by Dream-Master** [comment]
ah ok. So if i set potion id here animies get hit with this tool get this potion effect ?

**Comment by Zoko061602** [comment]
yes and if it's negative the potion gest applied to the attacker

**Comment by Dream-Master** [comment]
ah ok good to know
Ok so i need a list with suggestion. Not sure i can implement it for 2.0.3.0 need some help.

**Comment by bartimaeusnek** [comment]
@Zoko061602 will it remove the potion effect once the tool is not in hand anymore? havent tested it yet, but code looks promising

**Comment by Zoko061602** [comment]
@bartimaeusnek  No, the effect is added for the amount of ticks in the config

**Comment by WarlordWossman** [comment]
If it's the normal potion effects I assume milk/terrawarts are able to get rid of them?

Sounds cool and could add some unique features to materials for sure.

**Comment by Dream-Master** [comment]
sure if someoen will do the list :P

**Comment by Zoko061602** [comment]
I made a table for that: https://docs.google.com/spreadsheets/d/1I_U5pYy91FVQdsKHKugLVxQMLcLZR9NB4p7kd9X6CY4/edit?usp=sharing
I have no idea where to start :(

**Comment by mtesseracttech** [comment]
@Zoko061602 Nice work, it sounds pretty promising. It could be nice to have the later, fancy tic tools be a bit less boring (until you get Neutronium/Infinity)

**Comment by Dream-Master** [comment]
added
