### ISSUE TITLE
Teleporter rework

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2647]
Teleporter rework

**Comment by bartimaeusnek** [comment]
882b7c5d03cd5a26c87f372b080fde13fb172d04
991322d498df9e67da08ce5116a25def4bd3e14a
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/7bf69874f9e42b7110111697aeaecd3d20f832a9
