### ISSUE TITLE
Missing recipe (Soduim Persulfate via Chem reactor)

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/NewHorizons#2653]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Soduim Persulfate quest asks to be made in a chemical reactor, but the recipe is missing in NEI.

I suggest changing the quest to make people follow the alternative route (that uses Sodium Bisulfate Dust)

**Comment by Dream-Master** [comment]
I guess this is fixed allready. Will check.

**Comment by mtesseracttech** [comment]
@Dream-Master You can close this one, it's a duplicate of #2509 and #2545
