### ISSUE TITLE
Battery storage above UEV seems broken

### ISSUE THREAD

**Issue by Takafate** [GTNewHorizons/NewHorizons#2654]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
I was trying to upgrade my power network to UHV, found that UEV batteries store the same amount of EU as UHV ones do.
#
#### What happend instead? (Attach screenshots if needed)
Currently, batteries increase their storage by 4 times per tier, but there seems to be a mistake with UEV one.

Tier | Capacity
-- | --
EV | 6400000
IV | 25600000
LuV | 102400000
ZPM | 409600000
UV | 1638400000
UHV | 6553600000
UEV | 6553600000
UIV | 26214400000
UMV | 104857600000
UXV | 419430400000

#
#### What do you suggest instead/what changes do you propose?
Increase UEV ~ UXV batteries storage by 4 times.

**Comment by Dream-Master** [comment]
will look into it.

**Comment by benstuwie** [comment]
If you're around that power tier, I'd suggest looking at ultimates and really ultimates.
