### ISSUE TITLE
[suggestion] better / more professional readme 

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2657]
I read through the readme again today and I think it could be done way better.
It's basically the text people read first when they find out about the pack. I think the information could be more, the small texts could be more descriptive, questions like "how do I join" could be answered better mentioning the whitelist system and the general intention/concept of the pack could be made more clear.

Just to make it clear, I think Dreammaster wrote the previous text and he is not a native speaker, so this is in no way meant to be offensive.

The point I am trying to make is that we can probably overhaul it to improve the representation of the pack. I would be willing to help with that but everyone would be welcome to join.

Feel free to leave opinions and suggestions on the topic.

**Comment by Dream-Master** [comment]
Sure go ahead and make a better on :)

**Comment by bartimaeusnek** [comment]
Maybe update the tiering aswell and add Meta-Tiers (early game, mid game, late game) aswell... I like this idea 👍

**Comment by WarlordWossman** [comment]
#2716
