### ISSUE TITLE
[RFC] [Suggestion] Loading time and performance enhanchments

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2658]
#### What do you suggest instead/what changes do you propose?
Right now, the loadting time of the game is pretty slow. This might be enhanced if we fork every open sourced mod, and closed source mod we have permission to do so, and replacing Interger with bytes, double with float, and so on, and so on, whenever its possible. Other than that, we could delete deprecated Blocks/Items/Recipes (like TConstruct Iron Ore) from the sourcecode to save a bit of performance aswell. The Recipes that are now added by minetweaker could then be placed into the core mod, so we don't add a recipe via the mod, remove it via minetweaker and re-add a new one. Additionally we could remove stuff that spams the logs.

**Comment by richardhendricks** [comment]
Just be sure to measure performance differences.  I think the vast majority of the loadtime is caused by GT creating variant recipes for every and all ore/ingot types.  I would focus on picking and choosing which ores/ingots/etc get the full monty of plates/springs/rods etc for recipes.

**Comment by draknyte1** [comment]
I don't feel like the time saved is worth the time invested.
OreDict/RecipeGen state definitely takes the longest.

Maybe @Muramasa- can weigh in on some of his major speed overhauls he achieved on his personal fork.

**Comment by boubou19** [comment]
A good improvement in my opinion would be to transform dynamic loading into static loading (with an option to enable/disable this). That way only the first load would be long, but maybe I'm wrong.

**Comment by Muramasa-** [comment]
There can be some really nice load time improvements done to GT5U, but I'm not sure if there is a big enough want for it to happen to late in GT5Us life. If it was to happen it would be a fork on the main GT5U repo until it was stable enough to be in a main release.
