### ISSUE TITLE
%material in assembly line recipe

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2659]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Made a quantum suit boot book for the assembly line. Expected a proper recipe to show up in the book.
#
#### What happend instead? (Attach screenshots if needed)
I get a weird string like '%material' on certain pages of the book. I saw that this issue came up before https://github.com/GTNewHorizons/NewHorizons/issues/2380, but it's still happening in 2.0.2.7. Can't attach a screeny right now but I will later.
#
#### What do you suggest instead/what changes do you propose?
Needs to say what material it is.

**Comment by richardhendricks** [comment]
Dupe

https://github.com/GTNewHorizons/NewHorizons/issues/2380

Should be fixed in next release.

**Comment by Prewf** [comment]
@richardhendricks I realize it's a dupe, that's why I made the post again since #2380 was closed after it wasn't fixed. #2380 was supposedly fixed it for 2.0.2.6, but #2463 brought it up as an issue again, which is still open. 

In which issue # did Dream actually (or whichever dev fixed it) say the issue was fixed for 2.0.2.8?

**Comment by Prewf** [comment]
Nm I'm guessing it's #2513.
