### ISSUE TITLE
Iridium Neutron Reflector

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#266]
In the assembler recipes it uses 8 Thick Neutron Reflectors and 1 Iridium Plate but the Think Neutron Reflectors dont stack at all so the recipe cant be used at all

**Comment by Dream-Master** [comment]
I will find a alternative Recipes

**Comment by Drobac** [comment]
The recipe Namikon did that just switches it from the assembler to a normal crafting table recipe works just fine. No need for new recipes

**Comment by Dream-Master** [comment]
High Tier recipes need to be nerfed ;-)

**Comment by Dream-Master** [comment]
Adding Neutron reflector Parts that this recipes can still be in the Assembler ;-)
