### ISSUE TITLE
[Quest] Quest for Primal Shrooms

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2660]
Primal Shrooms quest for after getting your 2nd tier wand (lich bones). Primal shrooms allow you to refill wands easier before you can move nodes to your base.

Also add a coins quest for Vishrooms, since fresh magical forest biomes can be hard to find. Vishrooms can be used to create primal shrooms, which can restore vis in wands.  There isn't a way to increase the # or get seeds, so people hoard/use up all the Vishrooms.

5 vishrooms per 10 dark wizard token (since we get more killing mobs), with a reset time of 6 hours.  This will encourage people to at least try to find them, since ~25 are needed to recharge a tier 1 wand.

**Comment by Dream-Master** [comment]
Ok will add such quest.
