### ISSUE TITLE
Electric switch track uncraftable

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#2661]
#### Which modpack version are you using?
2.0.2.7

#### If in multiplayer; On which server does this happen? 
Delta

#### What did you try to do, and what did you expect to happen?
I've tried to make electric switch track, but that recipe wont work

#### What happend instead? (Attach screenshots if needed)
Nothing, presumably do to different item numbers
![2018-03-02_23 07 33](https://user-images.githubusercontent.com/14223368/36924264-4395c11c-1e6e-11e8-8e93-14afcaad4151.png)
![2018-03-02_23 07 38](https://user-images.githubusercontent.com/14223368/36924265-43af51c2-1e6e-11e8-969d-bb05590f122a.png)

#
#### What do you suggest instead/what changes do you propose?
Check the item meta-data and fix that recipe, or add manual version of that recipe

**Comment by Dream-Master** [comment]
Will check
