### ISSUE TITLE
[Suggestion] Underground Fluids Generation in other Dimension

### ISSUE THREAD

**Issue by Takafate** [GTNewHorizons/NewHorizons#2662]
#### What do you suggest instead/what changes do you propose?
Underground Fluids in GT5 can not only generate oil and natural gas in the Overworld but also any kinds of fluid in any dimension. This can be modified via "GregTech.cfg". By default, four kinds of oil and natural gas are generated in the Overworld and Helium-3 is generated on the moon.  This might be slightly dull, many people, including myself, tend not to build the oil drilling rig and seismic prospector, for BC oil are easy to get and He-3 is kind of useless.

I would suggest to generate more kinds of underground fluid in other dimension, such as lava and sulfur dioxide in Nether, liquid ender and ender goo in the End, methane on Titan or mercury on Mercury. We can also have other fluid generated such as liquid pure, chemical dye, IC2 coolant or anything you can imagine. 

Some planets like Europa and Barnard C do not generate any ores, we could make some valuable fluid to be generated on them. For high tier planets and the deep dark, molten metal, UUM or plasma is possible, so that players will not through their oil drilling rig into the arc furnace after they had built up a pyrolyse oven to get infinite heavy oil.

**Comment by benstuwie** [comment]
that would be really cool

**Comment by benstuwie** [comment]
Im with you on plasmas, but uu could be useful. Maybe UUA too? There's only one way to get it right now, but you need it in fairly large amounts for high tier circuits

**Comment by richardhendricks** [comment]
Liquid lead on Venus!

**Comment by Dream-Master** [comment]
No uua or uum with other materials i am fine.

**Comment by eloquentJane** [comment]
I don't think molten metals make sense. But perhaps fluids could be added that are solutions of metals. Then there could be potential for processes like the way copper is sometimes extracted in reality by leaching when the ores are too poor to be profitable for mining.

**Comment by richardhendricks** [comment]
There are many metals that are found in pure form, copper being one of them. Considering lead melts on the surface of Venus, doesn't seem too far fetched there might be pockets of it underground.  Anyways at some point playability and balance has to trump physics. :D
