### ISSUE TITLE
[Quest] Add a "Building Better Bases" quest tab

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2663]
Add quests that help build tools to make your base better

- [x] Chisel?  Maybe leave chisel quest where it is, use it to unlock this tab. Auto chisel table + upgrades
- [x]  Better builders wands, stone/iron/diamond
- [x] Extra utilities builders wands - need division sigil
- [ ] Coloring GT machines/cables/pipes with dyes
- [ ] ztones (no ofanix)
- [ ] railcraft decorative stones (infernal, sandy, ice...)
- [x] fancy extra tree block cutting thing
- [ ] extra utilities colored junk
- [ ] Paint Mixer, Paint Brush, Drawing Table, Stencils, Squeegee from open blocks
- [ ] CF foam scaffolds and reinforced stone
- [x] Botany stuff
- [ ] catwalks
- [x] Building guide
- [x] Enhanced building guide
- [x] Various lamp options
- [x] coal-powered floodlights
- [x] argon for electric floodlights
- [x] electric floodlights
- [x] arc lamps, needs Mars
- [x] elevators and enderio travel anchors - stargates?
- [ ] fillers, builders, architect table, electronic library, blueprints, template - buildcraft
- [ ] Drawbridge
- [ ] Carpenter's blocks, including using shift-scrolling to change the type, and shift-clicking with glowstone to make it emit light.
- [x] Gregtech muffler cover upgrades
- [ ] Fancy footpaths - TiCon brownstones, GT concretes, GT stones, ztones speed boosting pads, Thaumcraft traveling stones
- [x] Malisis Doors/player  detectors
- [x] Architecture craft, including how to use glowstone and cycle through options in-hand
- [ ] Lapis lamp, floodlights for mobs, dark glass/curtains for blocking light
- [ ] 3d prints
- [x] Floodgate for making pods/lakes/rivers - in LV

**Comment by WarlordWossman** [comment]
further brainstorming:
Malisis Doors, Architecture Craft, elevators leading to the ender io things you can teleport around with

**Comment by bartimaeusnek** [comment]
> Filler from Buildcraft

Really? Promote bugged stuff? I used them in the past a lot and they were often world breaking. Tbh. i would disable Filler and Builder from buildcraft completely, due to their buggyness...

**Comment by richardhendricks** [comment]
I don't know what works/what doesn't.  If it's buggy and we can't fix it, yeah let's disable it.  What other alternatives are there for clearing out large areas?

I see there is a ridiculously large/expensive *two* tier "concrete filler" that just fills in air blocks below it. Seems unlikely anyone has actually bothered to build it.

**Comment by richardhendricks** [comment]
Brownstone from Tinker's to help move around faster in your base, before you get high volume GT concrete.

**Comment by richardhendricks** [comment]
lapis lamp to allow for light and mob spawns

**Comment by richardhendricks** [comment]
Floodgate for making lakes/ponds.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4146

**Comment by richardhendricks** [comment]
Player detectors for doors/lamps/traps?

**Comment by richardhendricks** [comment]
Open Sesame
Quest for Malisis Door factory

I said ME
Quest for player detector

**Comment by draknyte1** [comment]
Auto doors

**Comment by richardhendricks** [comment]
Blackout curtains and dark glass

**Comment by richardhendricks** [comment]
HighbeamToday at 2:42 AM
@moronwmachinegun and @DoomSquirter just a note about the Filler if you didn't know already.couple of bugs with it you have to be careful with: First if you don't chunk load the Filler itself, when the chunk unloads, the Filler pops up as a dropped item. If you don't notice then it will despawn... (CONFIRMED) Second and I've only been advised this so not confirmed - but if the Filler is digging in unloaded chunks it can cause corruption? So I guess those are the 2 main bugs to be careful of. Third is a no brainer really, don't set it to 'Horizon' mode while under your base or make it fill in where machines are!!! smiley
0lafeToday at 2:47 AM
pretty sure if the filler is used on gt items it has issues, which includes ores, but that could have been changed with the change @mitchej123 made a while ago with filtering ores and DE
HighbeamToday at 2:56 AM
Pretty sure I’ve filled my area where there were gt ores and had no issues. I lost several fillers already to the chunk unloading issue. Always put a vacuum hopper next to your Filler! smiley

**Comment by richardhendricks** [comment]
First batch of base building quests done. 
![image](https://user-images.githubusercontent.com/1214811/57209386-1b986980-6f9e-11e9-94fe-d8c4e7a29ed7.png)

**Comment by richardhendricks** [comment]
Holy frack Botany is a whole another breeding system just for flowers and dyes. https://binnie.mods.wiki/wiki/Flower
Not sure if I should do it all here or put it in the Farming tab.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57270431-d97c3000-7050-11e9-8842-694689c68192.png)
![image](https://user-images.githubusercontent.com/1214811/57270438-dda84d80-7050-11e9-92dc-6e8e260a3ea2.png)
![image](https://user-images.githubusercontent.com/1214811/57270503-32e45f00-7051-11e9-99ac-c547f5ad13f5.png)
![image](https://user-images.githubusercontent.com/1214811/57270866-a89cfa80-7052-11e9-89ff-11bf0c9ef249.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57270967-18ab8080-7053-11e9-9768-cd7660e7fae0.png)
![image](https://user-images.githubusercontent.com/1214811/57271381-df741000-7054-11e9-94e0-c0614594fcad.png)
![image](https://user-images.githubusercontent.com/1214811/57271549-7b058080-7055-11e9-9604-5a75d33e020f.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57271724-33332900-7056-11e9-99c2-3304ae26165d.png)
![image](https://user-images.githubusercontent.com/1214811/57272040-69bd7380-7057-11e9-99e3-63ee42422967.png)
![image](https://user-images.githubusercontent.com/1214811/57272198-57900500-7058-11e9-8a4a-7d037fe7edb8.png)
![image](https://user-images.githubusercontent.com/1214811/57272494-94103080-7059-11e9-833c-438d729fd0f2.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57349653-94bfca00-7120-11e9-9fe7-b438f3dba022.png)
![image](https://user-images.githubusercontent.com/1214811/57349660-99847e00-7120-11e9-80df-282945b636ac.png)
![image](https://user-images.githubusercontent.com/1214811/57349664-9c7f6e80-7120-11e9-9dc8-cf74dc7b9942.png)
![image](https://user-images.githubusercontent.com/1214811/57349670-a1dcb900-7120-11e9-9bc7-38fcc64ec4c8.png)
![image](https://user-images.githubusercontent.com/1214811/57349678-a5704000-7120-11e9-9046-6edca8fb5d77.png)
![image](https://user-images.githubusercontent.com/1214811/57349683-a99c5d80-7120-11e9-9d3b-cde953e14428.png)
![image](https://user-images.githubusercontent.com/1214811/57349689-adc87b00-7120-11e9-97f2-e1c812023640.png)
![image](https://user-images.githubusercontent.com/1214811/57349696-b1f49880-7120-11e9-83ec-378e1291e087.png)
![image](https://user-images.githubusercontent.com/1214811/57349705-b751e300-7120-11e9-985e-d7c31168ab2b.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57350148-7ce94580-7122-11e9-9492-b9b3ef26dc48.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57352715-d1dd8980-712b-11e9-9756-3d549aed4d6b.png)
![image](https://user-images.githubusercontent.com/1214811/57352724-d9049780-712b-11e9-92b7-7c401d50ae93.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57353649-cb9cdc80-712e-11e9-9dc0-99f81cd2ec0d.png)

**Comment by Dream-Master** [comment]
wow a lot of new quests. Nice

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57354109-3995d380-7130-11e9-9c67-1175d9a2dc8a.png)
![image](https://user-images.githubusercontent.com/1214811/57356032-0ace2c00-7135-11e9-9803-cc875e020659.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57356053-17528480-7135-11e9-94f9-08661dff8732.png)
![image](https://user-images.githubusercontent.com/1214811/57356063-1c173880-7135-11e9-8a38-42c9a7937f9a.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57357002-70231c80-7137-11e9-900c-a78a062357de.png)
