### ISSUE TITLE
[Quest] Create new firestone ore quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2664]
Filler machine is would be very useful for base expansion. Right now it's gated by needing 5 firestone dust. Firestone is a PITA to retrieve in the nether.  There are some alternatives like the Enhanced Building Guide already available, but this also supports clearing/leveling designated areas.

Currently Enhanced Building Guide is gated by MV assembler with pretty simple items

Filler however
![image](https://user-images.githubusercontent.com/1214811/36941958-361649d4-1f2d-11e8-9f0f-2db0fe9b45e4.png)

Builder & filler both use redstone crystals (which need no redstone, lol) which requires 4 firestone plates and firestone lens (another plate), so requires finding at least 3 firestone (macerates to 2 crushed ores).

Firestone requires digging at the bottom of the lava lakes in the nether (at least 6 lava deep), so pumping the nether lava ocean or using sponges etc.

Alternatively, use fire resistance potion + seeing below lava glitch or nanosuit night vision (unlike nightvision potion, blindness from nanosuit allows seeing a few blocks, also when nightvision is disabled you get a few seconds of clear view.

I suggest changing redstone crystal recipe to using just 1 firestone plate, that way only 1 ore is needed to get Filler/builder.

Meteor boots also require 5 firestone plates, if that matters.

**Comment by noobyaran9** [comment]
>There are some alternatives like the Enhanced Building Guide already available, but this also supports clearing/leveling designated areas.

Enhanced Building Guide doesn't work on non-forge server.

**Comment by richardhendricks** [comment]
Just so nobody can complain I didn't pay the toll:
![2018-03-03_22 09 09](https://user-images.githubusercontent.com/1214811/36942049-9eea526e-1f2f-11e8-92f4-408f38badc5e.png)

**Comment by richardhendricks** [comment]
hazmat suit does let you walk under lava, but you still can't see anything.

**Comment by richardhendricks** [comment]
One thing to point out, the firestone only replaces netherrack.  So all the BoP nether blocks and GT stones will lower spawn rate.  Based on my limited sample set, quite a bit of the underlava is taken up by soulsand, marble, ash, flesh, etc, limiting spawn rate.

**Comment by richardhendricks** [comment]
Ok, there's a glitch where if you are juuust the right height, you can see underneath the lava.  Annoying but useable, just to show how much of the underlava is not netherrack.
![2018-03-03_23 50 52](https://user-images.githubusercontent.com/1214811/36942840-92663aae-1f42-11e8-87ee-86d69191208d.png)

Also, the OV scanner does show firestone ore if it is within range, so cruising right above the lava one could try and find some that way.

**Comment by Dream-Master** [comment]
If i remeber right firestone are generated by gt too not only by Railcraft. Isnt it in a Mix ? I remeber when i was in the nether some time ago a mined a few in a Ore vein. I wondering why i catch fire.

**Comment by Cinobi** [comment]
U can find firestone in venus as small ores. Even less frienfly for start than lava lakes =D

**Comment by Dream-Master** [comment]
Maybe this was changed will check the Nether ores

**Comment by benstuwie** [comment]
I think it's on IO too. I think the bc stuff is fine the way it is

**Comment by richardhendricks** [comment]
I tested the BC filler on a creative game, seemed like it worked fine once I worked out the quirks with the landmarks.

It's definitely not in the nether ores.  I want to test and see if the GT miners pick it up, if so I guess we can close this ticket.

**Comment by richardhendricks** [comment]
Also, the OV scanner apparently has a limint on how many ores it can show on the screen.  This all at the same XZ, just coming closer to the bottom.
![2018-03-04_20 47 13](https://user-images.githubusercontent.com/1214811/36955317-5be26b0a-1fed-11e8-811c-a998fdb21265.png)
![2018-03-04_20 47 16](https://user-images.githubusercontent.com/1214811/36955320-5e60fe6e-1fed-11e8-858d-3faa7765f6fc.png)
![2018-03-04_20 47 23](https://user-images.githubusercontent.com/1214811/36955325-6074328e-1fed-11e8-9b01-b59fce95b9d0.png)
![2018-03-04_20 47 32](https://user-images.githubusercontent.com/1214811/36955327-623aac9c-1fed-11e8-8095-1f21cfcada15.png)

I confirmed that the GT miners do gather firestone ores, if there is some in the area.

![2018-03-04_20 51 14](https://user-images.githubusercontent.com/1214811/36955381-c989f1e6-1fed-11e8-9cf4-b59548256926.png)

Spawn rate is still low IMO, firestones marked with cobble (4 in screen)
![2018-03-04_21 01 05](https://user-images.githubusercontent.com/1214811/36955618-2c4c9e40-1fef-11e8-9a1d-8dc9c8e2f6e9.png)

Potential firestone quest:

Looking for ore in all the wrong places?

Firestone ore is handy for some base building machines.  Unforunately, it's in the nether...at the bottom of the lava ocean! Here are some tips for finding it
- Firestone can be mined with the GT miners, if you place it within range.
- Firestone only spawns in deep lava, at least 6 deep. It will only replace netherrack, so a fjord filled with soulsand won't have any. Can you think of ways to check the lava depth, and what's down there?
- Normally you can't see through lava, but if you enable nightvision on the nanosuit, you can see a short distance at the bottom.  But how to prevent getting burned?
- Alternatively, if you keep your head at just the correct height above the lava and at the correct angle, you'll be able to see underneath it, Surely there must be a hovering jetpack?
- Firestone ore and products will cause random fires to start nearby, so get it into a backpack quickly!
