### ISSUE TITLE
[Suggestion] Some quest changes

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2666]
#### Which modpack version are you using?
Epsilon one
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
1. I think quests for 1slot-4slot battery buffers need to be removed\changed. They are just forsing ppl to make useless shit. There is totaly no reason to make 1slot - 4slot battery buffer for any tier except UV.
2. MV starter quest forse ppl to make MV steam turbine. Why? What if i make light fuel processor at LV? wasting materials for useless steam turbine is bad.
3. unlocking MV req all main quests from LV completed, so all power sourse quests need to be optional. Why i need to make gas turbine if i will not plan to use it as power sourse atall?(biogas is dead).
![2018-03-05_15 44 16_2](https://user-images.githubusercontent.com/25028786/36975913-c739e0dc-208c-11e8-808d-341e07177d47.png)
![2018-03-05_15 47 12](https://user-images.githubusercontent.com/25028786/36975914-c75cf1b2-208c-11e8-98d2-abdcb964cd16.png)
![2018-03-05_15 48 59](https://user-images.githubusercontent.com/25028786/36975915-c77e3af2-208c-11e8-86b2-f8932fc33973.png)
![2018-03-05_15 44 14](https://user-images.githubusercontent.com/25028786/36975916-c79f6d12-208c-11e8-92b7-8027eb8f2738.png)

**Comment by Cinobi** [comment]
Ok, let's start:
1. still present
2,3 - removed
4. quest "steam turbine" at MV is main quest and req MV machine casing. Just checkbox maybe?
5. quest #1212 (starter quest in fusion tab) has wrong requarements: T1 fusion req superconductor coils, not fusion coils.
![2018-03-05_18 18 15](https://user-images.githubusercontent.com/25028786/36982753-9f81eef8-20a1-11e8-86f7-8d19198f3047.png)
6. quest "Sparking nitor" from "electromagic" has some color code issue:
![2018-03-05_18 21 50](https://user-images.githubusercontent.com/25028786/36982910-19835f5c-20a2-11e8-8bc7-a3838a92a110.png)
Same in "recharging skriber tools" quest.
@bartimaeusnek hey, color errors is ur fault ;D

7. wrong quest name
![2018-03-05_18 32 17](https://user-images.githubusercontent.com/25028786/36983483-8ca7b806-20a3-11e8-806b-bf0cb3f0ba6f.png)
8. quest "portable mob spawners" from MV need realy better reward than 2 diamonds and useless bug. It's realy legendary task at mv - get 9 nether stars =D

**Comment by Dream-Master** [comment]
A machine hull was it before so i think this is fine. Check box is cheaty.
About Fusin quest will change it get this quests via upload from another user.
About bat buffer i need to check what i cahnge here.
Using color can be a problem @bartimaeusnek  ?
Will rename the "pitchblend Quest"

**Comment by bartimaeusnek** [comment]
@Cinobi will fix
@Dream-Master normally not, but if you manually edit the file it might cause these issures...

**Comment by bartimaeusnek** [comment]
![2018-03-05_17 37 42](https://user-images.githubusercontent.com/33183715/36987164-009af5aa-209c-11e8-87f1-f238862a8a70.png)
![2018-03-05_17 37 37](https://user-images.githubusercontent.com/33183715/36987165-00b9883a-209c-11e8-89e8-66291e2b94cc.png)

cant reproduce. Newest version from git:
https://raw.githubusercontent.com/GTNewHorizons/NewHorizons/c16a782d6588693c688e06b1efdff61d120e70a0/config/betterquesting/DefaultQuests.json

**Comment by richardhendricks** [comment]
I think 4 slot batteries are OK to keep, but agree 1 slot batteries should be removed from the quest.  4 slot is convenient for charging nanosuit.  In my power systems, I use 4A wires, so I use a x16 batt and then a x4 batt to regulate down to 4A.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/fd2b1b631fab517ac584ecba0702c48c30c19cae
