### ISSUE TITLE
[Suggestion]  NH "Lite" Config?

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2667]
-#### Which modpack version are you using?
NH
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
So I love this pack, despite the amount of time it takes to play.  However, getting my mates into it has been an impossible feat as they feel its too grindy and takes too long to get anywhere.

Is there a lite version of this pack already knocking around?

Just an idea to be able to 'customise' the difficulty of the pack would be some editable modifiers in the config files (examples below):
- Power Generation:  x1, x2, x4 etc (increase power generated by steam/electricity generators by factor - at least only apply to energy based machines)
- Manufacturing Processing Speed/Time: x1, x2, x4 etc (Speed up manufacturing/smelting time by factor.  Reduces time to smelt copper, process items etc)
- AE Power Reduction: x1, x2, x4 etc (Reduce power requirement for AE by factor) - The current power demand is insane

At least I anticipate the above options would potentially be easy to implement without major changes to the code and without making a whole new instance of the game.

A true lite pack would just make the whole experience quicker and more appealing to casual players who just want to playthrough a challenging pack in a month rather than several months.  This pack is amazing, however, the size, speed and complexity is too slow and overwhelming for most common players.  Some like my friends just find it too 'grindy' (*cough* circuits are grindy :p) to play the current pack which is unfortunate as I do enjoy it personally.

No negative comments please, this is a suggestion and not a criticism (except for circuits but I've mentioned it to dream several times :) ).

**Comment by Dream-Master** [comment]
There is and there will no lite Pack. Go and grab some otehr "lite" pack on the internet. There are manny.

**Comment by tranceplanet** [comment]
Ok fair enough.  Worth an ask :) thanks for the reply

**Comment by richardhendricks** [comment]
Just cheat in Electronic Prospectors for everyone. :D

**Comment by Dream-Master** [comment]
@tranceplanet I know i cant make everyone happy. This pack is grown slowly and cant be cut in pieces now or be made in one Month. If it is to long for you just play witha a few friends and sharing progress.

**Comment by richardhendricks** [comment]
With multiple people sharing progress you'll get tons of extra coins.  Use them to buy what you need from the Coins tab in the questbook to lite your game.

**Comment by bartimaeusnek** [comment]
as @richardhendricks said, best bet is to cheat in Electronic Prospectors Scanners for everyone, maybe add it as starting inventory or sth. like this.
