### ISSUE TITLE
incorrect behavior with the gt ore scanner

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#2671]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i was looking for ores on Tceti E with the ore scanner
#
#### What happend instead? (Attach screenshots if needed)
the gui for the ore map won't open. I guess it's because there is no ores on this dim because i used it in every chunk on the ground and it said "Nothing of interest"

**Comment by boubou19** [comment]
in addition of that when i use it on the ground i get two "nothing of interest" in chat

**Comment by Dream-Master** [comment]
This Planet have no GT Ores sadly.

**Comment by Dream-Master** [comment]
you need to hold the scanner on air blocks to see the ore pic.

**Comment by boubou19** [comment]
I and bartimaeusnek did so that's why i report it

**Comment by Dream-Master** [comment]
Ok maybe because there s no ore from gt. Same with Europa i guess.

**Comment by boubou19** [comment]
Yeah this happens in every dim with no gt oregen so dims like the last millenium and void dims are affected.
