### ISSUE TITLE
Missing mixer compost recipe

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2673]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Tried to make compost from ash in a mixer, but I can't.
#
#### What happend instead? (Attach screenshots if needed)
![2018-03-09_18 09 33](https://user-images.githubusercontent.com/29802757/37234316-0d861322-23c5-11e8-943c-297751dfd38c.png)

![2018-03-09_18 09 42](https://user-images.githubusercontent.com/29802757/37234391-6bc8ff58-23c5-11e8-80cb-d3eb441307d5.png)

#
#### What do you suggest instead/what changes do you propose?
Add a recipe using ash to the mixer.

**Comment by Dream-Master** [comment]
I add this recipe but it was never shown. Maybe override from another.

**Comment by Bluebine** [comment]
Tested in a mixer, the recipe is not there. It's not just hidden

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37251732-f2a3b990-2515-11e8-95e1-786157b45edb.png)
