### ISSUE TITLE
Pump recipe in assembling line

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2674]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
Pump recipe in assembling line only takes silicone rubber ring.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Add styrene-butadiene rubber ring as alternatives to the recipes.

**Comment by benstuwie** [comment]
should that also change for the ones that need a certain liquid, or does that not work? I think some of them need only styrene
