### ISSUE TITLE
Nano crystal crafting with Energy crystal

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2675]
#### Which modpack version are you using?
2.0.2.7
#### What did you try to do, and what did you expect to happen?
Can't craft the Nano Crystal with a Energy Crystal with item id 4223. 
![image](https://user-images.githubusercontent.com/30087707/37240788-6a478ace-2450-11e8-9802-ec152d236901.png)

You have to transfer some energy into the crystal, so you get fx 4226:26, before the crafting works. 
#### What do you suggest instead/what changes do you propose?
- Add precision laser crafting of using crystal id 4223 without the meta data. 
OR
- Change autoclave crafting of the Energy Crystal to output with metadata 4226:26.

**Comment by Dream-Master** [comment]
Need to test with 2.0.3.0

**Comment by DualBallers** [comment]
It's fixed in 2.0.3.0 👍
