### ISSUE TITLE
Quest idea: Crafting of Galacticraft LOX Cannister

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2676]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
Add crafting description for the LOX cannister in a Quest. 

The LOX cannister from Galacticraft is a really fast and easy way to refill your Oxygen Tanks, but NEI does not explain how to craft them. 
Maybe because Compressed Oxygen is only known as a fluid, and not as a fluid cell.

I found this page that explains the crafting steps https://gtnh.miraheze.org/wiki/Oxygen_Guide

- Fill the fluid storage of an MV (or higher) Assembling Machine with 16,000L of Oxygen.
- Use one empty Universal(!) Fluid Cell and a Circuit configured to 16.
- This gives a cell of Compressed Oxygen.
- Place this in the Vacuum Freezer to get the LOX cannister

![image](https://user-images.githubusercontent.com/30087707/37241065-7aea4652-2453-11e8-8022-793048929fb0.png)

A single LOX cannister can fill up four Heavy Oxygen Tanks, so you just need to bring a couple of LOX cannisters when going to space. 

![image](https://user-images.githubusercontent.com/30087707/37241101-0a3a0d6a-2454-11e8-8e3c-9d0a28d10670.png)

**Comment by DualBallers** [comment]
Hi https://github.com/Dream-Master, I looked through the commit, and wanted to comment on the description, as it's missing some details

To make liquid oxygen you need 16 oxygen cells and a universal fluid cell. Put them in the assember to get 1 cell compressed oxygen.\nAfter this put it in the vacuum freezer and wait a bit.\nNow you get liquid air. Fill it into a empty galacticraft cannister to get a good air backup for your tanks.\nTo refill your oxygen tanks just put both in the crafting grid to transfer oxygen.

I suggest you correct to:

The LOX canister functions as a good solution for refilling your oxygen tanks.\nTo make liquid oxygen you need 16 oxygen cells, an empty universal fluid cell and a circuit configured to 16. Process this in the assembler to get 1 cell of compressed oxygen.\nPut this in the vacuum freezer to get the Galacticraft LOX canister.\nTo refill your oxygen tanks just put the tank and the canister in the crafting grid to transfer the oxygen.

**Comment by richardhendricks** [comment]
Dream I'll take care of the changes

**Comment by richardhendricks** [comment]
"name": "LOX and Bagels",
      "description": "The LOX canister is an alternate solution to refilling your oxygen tanks.\nTo make liquid oxygen you need 16 oxygen cells, a universal fluid cell, and a circuit config 16. Transfer the oxygen gas into an MV+ assembler, and put in the universal fluid cell and circuit to get 1 cell of compressed oxygen.\nPut this in the vacuum freeezer to get 1 cell of liquid oxygen.\nTransfer this liquid oxygen into a tank, and then into a LOX canister.\nTo refill your oxygen tanks just put the tank and the LOX canister in the crafting grid to transfer oxygen.\nEach LOX canister can fill 4 Heavy Oxygen Tanks, 6 Medium Oxygen Tanks, or 12 Light Oxygen Tanks.\n\nSo much Greggy!",
