### ISSUE TITLE
Rainforrest Oak Saplings to biomass

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2678]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
I wanted to make some biomass out of Rainforrest Oak saplings
#
#### What happend instead? (Attach screenshots if needed)
I was unable to put the saplings in the fermenter
#
#### What do you suggest instead/what changes do you propose?
Add the Rainforest oak sapling to the Fermenter

**Comment by Dream-Master** [comment]
You can go the ic2 way

![image](https://user-images.githubusercontent.com/2970688/37252294-319d50b2-251f-11e8-80d0-6460dee7a207.png)

**Comment by Zoko061602** [comment]
I know, but every other sapöing can also be turned into biomass directly

**Comment by Dream-Master** [comment]
Yea its a GT++ issue. The recipes i add allready for ic2 way.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37252429-1841a8a0-2521-11e8-8b08-0031a8b0e5c9.png)
