### ISSUE TITLE
Manyulium nuggets

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#268]
Please add a recipe for changing Manyulium nuggets into ingots in a alloy furnace

**Comment by Dream-Master** [comment]
I look inside it.

**Comment by Dream-Master** [comment]
Than i have to add most off the Thaumcraft Metals because all nuggets cant be smelt in the Alloy Smelter.

**Comment by Dream-Master** [comment]
Ok added

// --- Manyullyn Ingot
AlloySmelter.addRecipe(<TConstruct:materials:5>, <TConstruct:materials:30> * 9, <gregtech:gt.metaitem.01:32306> * 0, 200, 32);

// --- Ardite Ingot
AlloySmelter.addRecipe(<TConstruct:materials:4>, <TConstruct:materials:29> * 9, <gregtech:gt.metaitem.01:32306> * 0, 200, 16);

// --- Alumit Ingot
AlloySmelter.addRecipe(<TConstruct:materials:15>, <TConstruct:materials:32> * 9, <gregtech:gt.metaitem.01:32306> * 0, 200, 8);

// --- Obsidian Ingot
AlloySmelter.addRecipe(<TConstruct:materials:18>, <TConstruct:materials:27> * 9, <gregtech:gt.metaitem.01:32306> * 0, 200, 4);

// --- Aluminium Brass
AlloySmelter.addRecipe(<TConstruct:materials:14>, <TConstruct:materials:24> * 9, <gregtech:gt.metaitem.01:32306> * 0, 200, 2);

**Comment by Dream-Master** [comment]
To the testpack first.
