### ISSUE TITLE
Unable to craft LV Robot Arm in assembler

### ISSUE THREAD

**Issue by Snaggerr** [GTNewHorizons/NewHorizons#2680]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
For the assembler recipe for an LV Robot Arm, the electronic circuit doesn't rotate through the different versions and you are unable to make it.
#
#### What happend instead? (Attach screenshots if needed)
![2018-03-09_11 40 02](https://user-images.githubusercontent.com/13313518/37244819-33242942-2443-11e8-8d3f-a2d4c9155dc2.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it yo!

**Comment by Dream-Master** [comment]
Yes i know it but not sure how to fix. Does it just not show up or not work?

**Comment by Dream-Master** [comment]
@richardhendricks its not only a visible issue. Assember using only one type of circuits.

**Comment by Dream-Master** [comment]
@Technus any idea ?

**Comment by Technus** [comment]
RecipeAdder RA is using ItemStacks not OreDict Stacks

**Comment by Dream-Master** [comment]
How it can be changed?

**Comment by Dream-Master** [comment]
Yes but i need it working for the 6 input methode.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Recipe.java

**Comment by richardhendricks** [comment]
I'm just saving pointers to where the code is located.  I think this one implements the stacks?
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_RecipeAdder.java#L353

**Comment by Dream-Master** [comment]
fixed
