### ISSUE TITLE
GT++ frames are way, way,  too cheap

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2689]
#### Which modpack version are you using?
2.0.2.7 (on the discord, people say the recipes havent changed in 2.0.3x so this should still be relevant) 

#### What do you suggest instead/what changes do you propose?
the gt++ bee frames are way too cheap compared to their bee counterparts, or just for what they do. The void frame is by far the worst. It takes a few thaumium ingots and an ender pearl. It replaces the oblivion frame, which costs a dragon egg, a few gold blocks, thaum infusion, a bunch of essentia, a couple bee products, and a lot of research to get there. This really doesn't quite seem balanced. I think if the gt++ one stays, it should be a high tier tech option instead of the lower tier, but incredibly convoluted magic path. Maybe make it cost 4 base tier wetwares (not ore dictionaried to that tier, but wetwares specifically to force an assembly line), 4 black plutonium plates to force a t7 rocket, and a dragon egg to keep some of the original difficulty.

**Comment by benstuwie** [comment]
I reposted this to the gt++ github as well, but I'll change the recipe I put on there depending on what people say here.

**Comment by Drobac** [comment]
Agreed will all you said

**Comment by Dream-Master** [comment]
And who knows it better than Drobac ? :)

**Comment by jiamingc0824** [comment]
I think instead of gating them to a dragon egg, we should gate them to around IV/ LuV materials. They have very little durability (mutagenic only 3 uses and void only 20 uses). IMO the item that makes them OP is the thaumic restorer. Oblivion frame is also found quite common in the stronghold and u can achieve the same effect as mutagenic (5x mutagen) by using alveary which itself is not a very high tier item.

**Comment by richardhendricks** [comment]
I already suggested to Alkalus to make the void frame 5x more expensive to repair.  I don't think it should be blacklisted completely from the restorer.  Maybe instead of just thaumium for the frame it can require something a little harder to get?

**Comment by draknyte1** [comment]
Refer: https://github.com/draknyte1/GTplusplus/issues/232
