### ISSUE TITLE
GT accelerator works on solar blocks

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2690]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
black list the solar blocks from the world accelerators, so you don't make 1A UMV from a single UV world accelerator. It's quite broken. Right now you can make 3A ZPM with an LuV accelerator and 4EV solars right now, and it just gets worse if there's new solars.

**Comment by Dream-Master** [comment]
@Namikon

**Comment by Namikon** [comment]
Which "Solar Blocks" are affected?  The accelerator is set to ignore everything from the gregtech namespace, so it should also cover those solar panels

**Comment by Dream-Master** [comment]
I guess advanced solar panels and super solar panels .

**Comment by bartimaeusnek** [comment]
@Namikon Check EMT Solar Panels aswell please.

**Comment by Namikon** [comment]
Should be ignored now
https://github.com/GTNewHorizons/NewHorizons/commit/3c915a8a9f583adfcd68d9032ac2c4002a81fe4e

**Comment by boubou19** [comment]
Could you also add wind and water kinetic generators in the blacklist those block aren't in the ic2 namespace
