### ISSUE TITLE
[balance] oilsands ore processing too cheap

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2691]
#### Which modpack version are you using?
2.0.2.7

Currently oilsands give 2 buckets of heavy oil per block.  The centrifuge recipe is only 5s at 10EU.  Recommend upping it to 15s at 60EU/t = 24k EU total.  Still a steal at 12K eu/bucket of oil, but not super cheap.

**Comment by bartimaeusnek** [comment]
would make it 30s at 30EU/t so it can be processed at LV aswell

**Comment by MakinToge** [comment]
I agree with @bartimaeusnek, it should have a LV recipe, oil sand is the only way to get heavy oil before the oil rig which is MV.

**Comment by Methes** [comment]
Don't see any reason why. Counting on Oilsand as energy source does not make sense and it's used for its byproducts.

**Comment by Cinobi** [comment]
Agreed with @Methes , useless change, totaly no point of it.

**Comment by MakinToge** [comment]
I used some until I got diamond tank and could efficiently move oil from remote oil geyser ... even if it's not the most rational choice, it's nice to have it. My teammate at that time choose to make 64 solar boilers instead, we passed MV before he could finish.

**Comment by richardhendricks** [comment]
@MakinToge Oilsands isn't necessary in LV since you can use light fuel.  It's intended for diesel processing at MV and above, as a stop-gap before getting a drilling rig running.

@methes @Cinobi The point is that oilsands are a really dense vein, and one vein can easily yield a few thousand buckets of heavy oil (2 buckets per ore).  Being able to process it in 5s at LV is a bit too cheap, and I say that as someone who uses it a lot. Upping the recipe to MV is a reasonable progression:

LV - get oil, distill & process to light fuel
MV - find oilsands or use drilling rig to get heavy fuel to make diesel, or make biodiesel using seeds/fish. Oilsands would need mining & centrifuging, while a drilling rig would need maintenance
HV - make TNM and mix up cetane

This would prevent a lucky player who finds oilsands near their base from using it until MV, but I think considering how common oil spouts are now, that's not a problem.

**Comment by richardhendricks** [comment]
Considering how much you can get from one vein, changing the recipe to only yield 1 bucket per ore of heavy oil might also be necessary.  I didn't realize 50 heavy oil => 125 sulfuric heavy fuel. At 2 buckets per ore, a player could completely skip the oil drilling rig.

**Comment by Dream-Master** [comment]
Ok tier it up is ok but reduce amount. Centrifuge time I will check.

**Comment by MineAnPlay** [comment]
Keep it at LV (5-10 EU/t) and around 30-60s per ore and reduce output to 1000L of heavy oil. If it gets nerfed too much it will be useless again.

**Comment by richardhendricks** [comment]
I'm OK with that, although it should be more EU/t.  28 or 30, whatever the high end is at LV.

**Comment by MineAnPlay** [comment]
I said 10-15 so if they want more they can make an extra centrifuge or two without making an extra generator.

**Comment by richardhendricks** [comment]
Making the game too easy. :D

**Comment by Dream-Master** [comment]
So yoi get 2000L oil need 30 eu/t and take 15 sec
