### ISSUE TITLE
Enchansed building guide from Open Blocks...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2693]
#### Which modpack version are you using?
Epsilon one
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
... not working.
It should place blocks u click it with at the shape, one for another. But, for unknown reason, it refuses to work. Work fine in single, so i hope it can be fixed at server too.
![2018-03-12_18 44 43](https://user-images.githubusercontent.com/25028786/37293901-ad69854c-2625-11e8-9dd4-971ce41e3d58.png)

**Comment by jiamingc0824** [comment]
Duplication of #2398
