### ISSUE TITLE
[Coins] Need Coins quest for Ocean bee

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2695]
Since there are no Ocean biomes in game, there needs to be a Coins quest for the Ocean princess.

Or maybe quests describing how to change biomes via witchery?

**Comment by K1ngMX** [comment]
approved, so less bees need to suffer :P

**Comment by WarlordWossman** [comment]
I like the concept of having to gain something yourself first before you can buy it with coins.

On the other hand I don't know if it's too far into the magic mods, a quest to change the biom would def be(e) cool tho.

**Comment by Dream-Master** [comment]
So far I know Gendustry have a ocean simulation frame.

**Comment by richardhendricks** [comment]
Yep, can you confirm it in-game? http://mesas-bee-class.wikia.com/wiki/Gendustry_Breeding

**Comment by Dream-Master** [comment]
I never play with gendustry @drobac any idea?

**Comment by Wolozo7** [comment]
The gendustry module exists but requires a T5 rocket. The Ocean Bee isn't the most useful, it breeds into oil, ink, rubber, nothing too rare. The Refined Bee seems to be the interesting successor, but oil is easy enough to come by anyway. So i don't see why this bee should be gated behind this much effort only because our worldgen doesn't like oceans.

**Comment by bartimaeusnek** [comment]
maybe add ocean bee as a free-bee (badum-tzz) to the bee breeding tab once you got imperial and/or industrious?

**Comment by Dream-Master** [comment]
I add it as Quest reward for imperials

**Comment by Gateswong** [comment]
Since your modpack has twilight forest. So you are actually able to breed ocean bees. It's no need to do this.

Twilight forest has a biome called "Twilight Lake", it's under ocean category. You can check this out in biome book in witchery. Thinking that if you need to roll this change back.

**Comment by Dream-Master** [comment]
Yea good to know
