### ISSUE TITLE
Diesel recipe suggestion

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#2696]
Could you please add a recipe for diesel that uses 5000L of light fuel from fluid input and a heavy fuel cell and outputs 6000L of diesel and an empty cell?

The only recipe right now is in the picture below and it's hard to automate without using a ton of empty cells.

![image](https://puu.sh/zGjKh/85a4982945.png)

Thanks

**Comment by Lainiel** [comment]
Here's a quick minetweaker fix I made if anyone is interested:

mods.gregtech.Mixer.addRecipe(<IC2:itemCellEmpty>, <liquid:fuel> * 6000, [<gregtech:gt.metaitem.01:30741>], <liquid:liquid_light_fuel> * 5000, 16, 120);

This is what it adds:
![image](https://puu.sh/zGl0Q/06aba43824.png)

**Comment by Dream-Master** [comment]
Sure I can lay both fluids an the cells inside. There is a LCR recipe allready for it.

**Comment by MineAnPlay** [comment]
You forgot to add the empty cells in the output.

**Comment by Dream-Master** [comment]
will do asap

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/6405767867db5cc593de1f33a50d829d7d179b84
