### ISSUE TITLE
[suggestion] Grout recipe putting buckets back to your hotbar

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2697]
#### Which modpack version are you using?
2.0.3.0

The suggestion is basically in the title. And for the smeltery quest you have to get 41 buckets of water, so it might sound like a small thing but it would help a lot.
The recipe to make clay into clay blocks with water does output the empty buckets in your hotbar while the grout recipe does not. Should be a simple fix (and make it less annoying).

edit: Now that I think about it the smeltery quest could have a hint that you can use clay blocks to get the clay dust since new players might not look for it.

edit2: Same issue for making torches with creosote and seared bricks, (probably for vanilla bricks as well)

**Comment by richardhendricks** [comment]
Can players at that stage use the hardened clay blocks? I thought they required macerating.  Also at that stage I'm not sure how far from home a player would be willing to go, but they could get a horse/boat I suppose.

**Comment by WarlordWossman** [comment]
I am talking about regular clay blocks, which save a lot of durability on your mortars.
Don't think you can use hardened clay for the reasons you mentioned.

Just made the normal clay blocks yesterday and the buckets being send back to your hotbar made it feel 10 times better, think it should be that way for all bucket recipes since you mostly do them in bulk.
