### ISSUE TITLE
Packed Ice recipe Compressor / Crafting table / Crucible

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2699]
#### Which modpack version are you using?
2.0.3.0
#

4 Packed Ice is made of 4 Ice in vanilla Crafting table
1 of 2 in Compressor
1 of 1 Ice and 1 Terra essentia in Crucible 

#

Suggest to disable vanilla crafting table recipe and add 4 Gelum aspect (Ice contains 4 Gelum) for Crucible to make recipe more like 1 Packed ice = 1 Ice + 1 Ice (to essentia) + Terra essentia

**Comment by richardhendricks** [comment]
Modify the vanilla crafting table recipes so it is 1 of 4, so at least that is available, with the compressor recipe as a better alternative.

The crucible recipe I dunno. For the amount of work required, I think it should give more packed ice.  Maybe
2 packed ice <== 1 ice + 4 gelum + terra

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37564662-ca4726be-2a9a-11e8-8b0b-12223020d6a6.png)
found a recipe allready.

**Comment by Dream-Master** [comment]
When i am on Thaumic Bases i will do recipes

**Comment by richardhendricks** [comment]
Still needs compressor recipe @Dream-Master

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/68527749-d6594980-02ea-11ea-83b1-9b8f0d4a40a5.png)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/ThaumicBases/releases/tag/1.4.20
