### ISSUE TITLE
Piko and Quantum Circuits

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#270]
Switch recipes -
Old - Quantum circuit - Quantum Circuit Board + 2 Engraved Quantum Chips  (192 Yellow Garnet)
New - Quantum circuit - Quantum Circuit Board + 2 Engraved Quantum Chips  (32 Yellow Garnet)
Now needs 32 Yellow garnet and not 192 as before

Old -  Piko Circuit - Nano Processor Board + 2 Engraved Manyullyn Crystal Chip (81 Manyullyn)
New - Piko Circuit - Nano Processor Board + 2 Engraved Manyullyn Crystal Chip (18 Manyullyn)
Now needs 18 Manyullyn instead of 81 (perhaps even lower it a bit since manyullyn isnt infinite unless you have bees)

**Comment by Dream-Master** [comment]
I look inside it and make a recipes.
Why not put Manyullyn and Ardite as a byproduct to some High Tier Metals ?

**Comment by Dream-Master** [comment]
Piko Circuits using 4 Engraved Crystals. and Quantum Circuit using 6 Engraved Crystals.
I adding Ardite to the Macerator witch mean more manyullyn and i will add some gem mixes on Planets that you can get enough Garnets,
If this is too hard we have to talk again.
