### ISSUE TITLE
[Suggestion] Pyrolyse oven casing assembler recipe

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2700]
#### Which modpack version are you using?
2.0.3.0
#

Pyrolyse oven casings require Hammer + Wrench to make (2 times per block). 
I suggest to make assembler recipe for Pyrolyse Oven Casings without tools usage. Same for Bronze Plated Bricks.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/d3d9cb7f4d5e1c3223166ec5ce97cd1d80fe3cf9
