### ISSUE TITLE
[Suggestion] Dagger of Sacrifice quest

### ISSUE THREAD

**Issue by rekongstor** [GTNewHorizons/NewHorizons#2701]
#### Which modpack version are you using?
2.0.3.0
#

Blood magic progression requires a lot of Life Essence but there's no quest for Dagger of Sacrifice. It's kinda possible to keep stabbing yourself but monster farms are more useful for this.

**Comment by benstuwie** [comment]
there's one in 2.0.2.7, guess it was removed. That's a bit of a problem

**Comment by Dream-Master** [comment]
I don't remove a quest or it was an accident.

**Comment by rekongstor** [comment]
There's still no quest for it afther updating up to 2.0.3.0

**Comment by benstuwie** [comment]
oh, you aren't talking about a recipe

**Comment by Dream-Master** [comment]
No I talk about Quests.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37564615-daa0fefa-2a99-11e8-9600-6dcc5bb85ac4.png)
![image](https://user-images.githubusercontent.com/2970688/37564616-dea20198-2a99-11e8-934f-5627bd625ba8.png)
There is a Quest.

**Comment by Dream-Master** [comment]
@rekongstor @benstuwie is this the quest you looking for ?

**Comment by rekongstor** [comment]
As I said there's Sacrificial Knife to stub yourself for blood and Dagger of Sacrifice to sacrifice mobs for blood. https://ftbwiki.org/Dagger_of_Sacrifice

**Comment by Dream-Master** [comment]
Ah ok and since when the quest is lost? @rekongstor @benstuwie

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37567290-0b4528da-2ac5-11e8-88f2-7b6501a02520.png)
2.0.2.7

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37567300-473fd48e-2ac5-11e8-9c51-fe32b2736157.png)
2.0.2.6

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37567308-67667e48-2ac5-11e8-8d6a-9d69ddca58df.png)
2.0.2.5

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37567311-82c83e2e-2ac5-11e8-9db3-c25886377a15.png)
2.0.2.0

**Comment by Dream-Master** [comment]
@rekongstor @benstuwie 
Maybe the quest was never in but still missing so i can add a Quest for it.
