### ISSUE TITLE
Stairs Are Hard (Not a bug, send help?)

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2703]
#### Which modpack version are you using?

2.0.2.7

#### If in multiplayer; On which server does this happen? 

Private

#### What did you try to do, and what did you expect to happen?

Pressed W toward cobblestone stairs.

#### What happened instead? (Attach screenshots if needed)

Stopped at bottom step. Also cannot jump past one stair at a time. I'm not kidding. LOL.

Here's a quick video of it: https://youtu.be/7LRMEODqG_U

#### What do you suggest instead/what changes do you propose?

I.. have no idea. Does anyone else experience this? If so, how to fix? The sprint issue was as easy as holding CTRL. This one, not so much.

**Comment by Bryfer** [comment]
This is because the floor you are using, not the stairs

**Comment by codewarrior0** [comment]
Before I checked the video, I thought "I bet it's because he's using GregTech Concrete, which the player sinks into slightly".

And yep, that's what was in the video. Try using Chisel Concrete instead.

**Comment by richardhendricks** [comment]
The GT concrete prevents spawns by slightly sinking the top of the concrete, which stupidly prevents you from autowalking up stairs.  If you use the chisel concrete, it doesn't prevent spawns but lets you go up stairs.  Also, chisel concretes the speed boost works better AFAIK.

**Comment by Axiflare** [comment]
Oh thank god I thought I was shrinking lol, thanks guys!

**Comment by richardhendricks** [comment]
Damn those would make awesome warp effects - shrink you so small you can climb blocks without stairs, grow you so large you can't fit in 2x1 doorways

**Comment by Axiflare** [comment]
That would be very cool actually, I'm enjoying most of the warp theory effects, although having a wither start spawning near a bunch of machines is the fastest I've ever typed /difficulty 0 LOL

**Comment by richardhendricks** [comment]
hahahaha

**Comment by draknyte1** [comment]
Did the GT6 style concrete never get backported to GTNH? It removed the soul-sand height issue and made them just nicer in general. (Which Afaik, has nothing to do with preventing mob spawns, Silly Richard :P)

**Comment by mitchej123** [comment]
> Did the GT6 style concrete never get backported to GTNH?  

It did.

**Comment by draknyte1** [comment]
> It did.
Then people shouldn't sink into the block.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/a3cf54ad0389d54651f8458d2ee3c8e55acbe58f

**Comment by mitchej123** [comment]
Perhaps he's on a version before that was merged & released?
