### ISSUE TITLE
More superconductor issue

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#2704]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Looking at all the recipes that use the old superconductor wire (UHV-tier).
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Many of the recipes weren't rebalanced after the superconductor tiering change. I'm not exactly sure what "tier" TecTech stuff is supposed to be in, but looking at the recipes..

Computer Heat Vent: it uses at most IV-tier components and EV-tier assembler, but requires UHV tier superconductors. Maybe require IV superconductors?

Active Transformer: it uses at most LuV/ZPM tier components and an LuV-tier assembler, but requires UHV tier superconductors. Maybe require ZPM superconductors?

Advanced Computer Casing: it uses ZPM tier components/assembler but requires UHV tier superconductors. Maybe require ZPM superconductors?

High Energy Flow Circuits: it uses ZPM tier components/assembler but requires 64 UHV tier superconductors. ZPM is only 131072 EU/t, but you need a 500000 EU/t assembler recipe to make this chip. Maybe require ZPM superconductors?

Superconductor/Superconductor Cover/Gravitation Engine (from the Graviation Suite mod): The gravitation engine is specifically used in the assembly line recipe for the GraviChestPlate (at best, an LuV tier recipe. Some ZPM tier chips are needed, but you can do this at LuV). You need 168 1x UHV-tier superconductor wires to make this thing. Why? An LuV-tier armor requiring a UV assembler doesn't make any sense. This could require LuV tier superconductors instead.

Besides the gravichestplate, this list doesn't include any of the assembly line recipes that have the superconductor as part of the recipe (since you can't see assembly line recipes in NEI). 

Logically speaking, it doesn't make sense to require a UHV tier (2097152 EU/t) wire for such relatively "low level" components. Please take a look at the recipes. Also look at the assembly line recipes for recipes that depend on the old super conductors.

**Comment by bartimaeusnek** [comment]
here are some screens for reference:
 
![2018-03-14_07 09 08](https://user-images.githubusercontent.com/33183715/37386057-032b0cf8-2757-11e8-90ef-4ab578a50fc6.png)
![2018-03-14_07 09 15](https://user-images.githubusercontent.com/33183715/37386059-03475f0c-2757-11e8-8a73-93fe556ae600.png)
![2018-03-14_07 09 20](https://user-images.githubusercontent.com/33183715/37386060-0361421e-2757-11e8-8e52-98956a4dc2ec.png)
![2018-03-14_07 09 22](https://user-images.githubusercontent.com/33183715/37386062-037ab67c-2757-11e8-9b87-88b4fcc5ea7a.png)
![2018-03-14_07 09 41](https://user-images.githubusercontent.com/33183715/37386063-0396bf66-2757-11e8-9d04-51437afced5a.png)

**Comment by Prewf** [comment]
![superconductor](https://user-images.githubusercontent.com/35204071/37390391-210598c4-2725-11e8-9896-e0524a0d4504.png)
Thanks for looking into this. Here's one more picture @bartimaeusnek 
It's called "Superconductor" under the same Graviation Suite mod and it requires 2 12x UHV superconductors. It's used in making the Gravitation Engine (for the GraviChestPlate, which is LuV tier).

**Comment by bartimaeusnek** [comment]
Energy Flow Circuits:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/d3d9cb7f4d5e1c3223166ec5ce97cd1d80fe3cf9

**Comment by bartimaeusnek** [comment]
TecTech is missing the buff now @Technus shall we add the recipe to the Core Mod or do you change it in your mod?

**Comment by Dream-Master** [comment]
Is this fixed @bartimaeusnek ?

**Comment by Dream-Master** [comment]
@Technus I chat with bartimaeusnek and he means that only Tec Tech recipes need a check.

**Comment by Technus** [comment]
On it

**Comment by Prewf** [comment]
@Dream-Master @bartimaeusnek Please don't forget Superconductor Cover and Superconductor from Graviation Suite mode. They are needed for the GraviChestPlate (the "advanced" quantum suit) and now it's unnecessarily gated behind UHV. The GraviChestPlate is LuV tier at most (I have assembly line recipe).

**Comment by bartimaeusnek** [comment]
@Prewf thats already fixed, see here:
https://github.com/GTNewHorizons/NewHorizons/commit/1462fdb0e219aac51859dc686e626f50a71b15c9

**Comment by Prewf** [comment]
thank u, u r the best

**Comment by Dream-Master** [comment]
Tect Tech changed recipes too. @Technus thanks
