### ISSUE TITLE
Unknown machine with messed up name

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2705]
#### Which modpack version are you using?
2.0.3.0
A machine with a messed up name that no recipe can found found inside the machine.
![2018-03-13_16 32 43](https://user-images.githubusercontent.com/20565115/37371437-657dfc5a-26dd-11e8-8af9-6c3054d9e52d.png)

**Comment by draknyte1** [comment]
Hello, this is mine.
Easiest way to tell? All Gregtech machines with an ID between 750-999 belong to GT++.

**Comment by Dream-Master** [comment]
@draknyte1 any thing we can do against it?

**Comment by Dream-Master** [comment]
@Anarack did you post the issue on GT++ side ?
https://github.com/draknyte1/GTplusplus/issues

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/134903c07dbcc33c2b267ba5011a7463b44eb2c4#diff-cf61de645e2860bc338f45937170d4ebR18.
