### ISSUE TITLE
Medium Kinetic Generator Uncraftable

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#2706]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Attempting to craft the medium kinetic generator 1632:9 and unable to do so
#
#### What happened instead? (Attach screenshots if needed)
The generator is currently uncraftable as the recipe calls for a lapotron crystal with metadate that makes it unobtainable. This is the same issue that the adventurecraft bat backpack and advanced nano chestplate had in the past.
#
#### What do you suggest instead/what changes do you propose?
Change the lapotron crystal metadata to one that is obtainable.

**Comment by Wolozo7** [comment]
Charging the Lapotron for a bit and then decharging it makes the generator craftable.

**Comment by Dream-Master** [comment]
seems to be allready fixed. It will use all meta ids.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37556885-925c8c38-29fc-11e8-82af-fe5685cb2e21.png)
![image](https://user-images.githubusercontent.com/2970688/37556887-96ba8b04-29fc-11e8-9588-ccd0bdb7f8a3.png)
