### ISSUE TITLE
Stained Clay doesn't go into Diggers Backpack.

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/NewHorizons#2714]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Mined Stained Clay, expected it to get stored into my Diggers Backpack.
#
#### What happend instead? (Attach screenshots if needed)
Diggers Backpack does not store Stained Clay or any colour.
#
#### What do you suggest instead/what changes do you propose?
Stained Clay support. :)

**Comment by Wolozo7** [comment]
As long as this isn't changed, you can use the Builders Backpack to store the clay.

**Comment by draknyte1** [comment]
That seems like an odd backpack for them.. 
I would assume all vanilla mineables would be supported by the digger/miner bags, by default from Forestry.

**Comment by Dream-Master** [comment]
I cann add it to the config file in forestry backpack config.

**Comment by draknyte1** [comment]
Cool, cheers. :D
