### ISSUE TITLE
New Superconductors feel a bit overpriced

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#2715]
So I've been looking into the new superconductors, and I feel like they're a bit too expensive for how useful they are. More specifically, in how many pumps you need to make them. I've created a list of how many pumps are needed per each superconductor and how I think it should be.
3 MV wire-2 HV pumps. This is FAR too much. I'd suggest toning it down to only needing 1 MV pump for 5 wires, and possibly making the alloy itself available earlier- locking it behind kanthal coils AND a vacuum freezer seems a bit excessive, I'd suggest just making it need 480 EU/t of 1700K heat to make the ingots. You can already just use 4x redstone alloy cables, so there's no point to using these ATM.
3 HV wire- 1 EV pump. This is a lot more reasonable, but I still think it's too much. I'd suggest making it cost 1 HV pump for 4 wires, and making it use 2 cells of nitrogen and 2 cells of helium instead of 1 of each.
9 EV wire- 2 IV pumps. I think this is OK, although maybe make it 8 wires for 2 EV pumps instead.
6 IV wire- 1 IV pump. This requires LESS pumps than EV wires do ATM. I'd suggest making it take 2 IV pump for 8 wires.
8 LuV wire- 1 LuV pump. Once again, it takes LESS pumps than the IV wires do. I'd suggest 2 LuV pumps for 8 wires.
16 ZPM wire- 1 ZPM pump. Yet again, less pumps than the previous tier. I'd suggest 3 ZPM pumps for 16 wires.
32 actual superconductors- 1 ZPM pump plus those required for the ZPM superconductors. This recipe needs changed to a lower tier, but that's an issue that's already been brought up in another ticket so I won't get into it here.

**Comment by benstuwie** [comment]
I think it's find that MV takes hv pumps. I think it should work like that for those tiers. You're right that you can just use red alloy, but that's more because that hasn't been balanced for nh, not because the superconductors should be cheaper.

**Comment by noobyaran9** [comment]
These superconductor added are meant to be expensive and not that available to every tier.

**Comment by Dream-Master** [comment]
I don't make the recipe cheaper. Tweaks are ok but if the superconductors to expensive for you use regular wires/cables.

**Comment by mtesseracttech** [comment]
@Dream-Master There is one argument I'd have against that. It's sort of the same with normal cables. You also add a relatively simple addition (until IV+, I suppose) to improve wires to be cables. Which essentially only changes their loss, by cutting it in half.

**Comment by Dream-Master** [comment]
Any suggestions what i should change ? @mtesseracttech

**Comment by mtesseracttech** [comment]
I am not entirely sure, but I think it should relatively get cheaper or stay constant the further into the tiers. For the simple reason that the relative loss on cables (compared to the voltage they can transport) lowers regardless. (2V/A/m is not bad when it's on IV+, while on LV it's a different story)

**Comment by richardhendricks** [comment]
Superconductor rework will be in 2.0.8.0 as a seperate topic. Need to decide long term on where SCs fit, are they a placeable object, etc.
