### ISSUE TITLE
[Suggestion] automating maintenance 

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2719]
#### Which modpack version are you using?
2.0.2.7
#
#### What do you suggest instead/what changes do you propose?
The auto maintenance hatches don't accept items right now, and only hold enough items for 16 repairs. I think if you could push items into them, it would be a good change. Maybe that should make them cost more, but I think it would help a lot when you start needing hundreds of multiblocks

**Comment by Dream-Master** [comment]
@Technus is this the new device you added ?

**Comment by draknyte1** [comment]
> The auto maintenance hatches don't accept items right now, and only hold enough items for 16 repairs. I think if you could push items into them, it would be a good change. Maybe that should make them cost more, but I think it would help a lot when you start needing hundreds of multiblocks.


The thing is, Auto-Maint. hatches ARE automatable, but the config option is default off, even in Standard GT. If you're on SMP, you're out of luck, but otherwise just change that setting in Gregtech.cfg.

**Comment by benstuwie** [comment]
Why not just turn the config on for the pack? Is it a choice to keep it off, or just default

**Comment by Dream-Master** [comment]
We can switch it on if this help
