### ISSUE TITLE
Macerating and centrifuging mercury

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#2720]
#### Which modpack version are you using?
2.0.3.0
#
Mercury in quicksilver form can be macerated into Mercury stone dust, and then further centrifuged into a lot of other stuff, which doesn't make much sense.

![](https://puu.sh/zJzwg/008066ebd1.png)
![](https://puu.sh/zJzwL/7f6252ff5f.png)

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
This was fixed so far i know. Can't see the recipe in my 2.0.3.1 dev inviroment.

**Comment by bartimaeusnek** [comment]
Its fixed. See this [commit](https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/11b02b8fb49e69340173c5ef80bf4b1a3c26fba9).
