### ISSUE TITLE
[suggestion] Add Fluid Regulators for IV+ pumps/Problem with HP Steam Turbine

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#2721]
Suggestion: https://github.com/GTNewHorizons/NewHorizons/issues/2721#issuecomment-373938020

#### Which modpack version are you using?
2.0.3.0
#

I've made a LHE that runs at full capacity and attached a Large HP Steam turbine to it. LHE makes 16 000 L/t of superheated steam. The turbine is equipped with a a large tungstensteel turbine with an optimal flow of 16 570 L/t in loose mode. Given that 1L of SH Steam = 1EU the turbine should be making 16 000 EU/t with 100% efficiency. With the 75% inefficiency on the turbine in loose mode it should be 12 000 EU/t. But what the turbine is actually making is around 8800 EU/t.

See the attached video of the whole setup here:
https://puu.sh/zJAxK/1dd6d64801.mp4

**Comment by codewarrior0** [comment]
Steam turbine in "Loose" mode increases the flow speed by at least 4x, and increases it even further according to the rotor's efficiency stat. It looks like the rotor tooltip is wrong and should be showing a six digit amount for the L/t in loose mode.

**Comment by codewarrior0** [comment]
Scratch that, the tooltip is correct. It looks like what is happening here is the turbine isn't being fed steam constantly by the LHE so it never gets a chance to warm up completely. I wonder why the UHV output hatch on the LHE is allowed to fill up beyond 16,000 and then drop down to 0...

**Comment by codewarrior0** [comment]
Ah, I see what's happening.

The UHV output hatch only outputs its steam into the Turbine's input hatch every eight ticks, so it ejects 128,000 at once. The Turbine then burns through the 128,000 as fast as it can, which is up to 25% faster than the stated flow rate on its rotor, also applying an EU/t penalty due to the flow being unregulated. On top of that, it spends two ticks out of every eight without any steam, so the Turbine is never able to warm up completely.

What you need to do is attach a fluid regulator cover to the Turbine's input hatch and set it to 16,000 L/t.

**Comment by Lainiel** [comment]
There's no regulator that goes up to that ammount.

**Comment by codewarrior0** [comment]
Then put two input hatches on the Turbine with regulators each set to 8,000?

**Comment by Lainiel** [comment]
You can't do that on both sides when you have a normal large steam turbine next to it. You have to put maintanance hatch somewhere.

**Comment by codewarrior0** [comment]
Why not the underside?

**Comment by Lainiel** [comment]
I'll do some testing and I'll be back. Thanks

**Comment by benstuwie** [comment]
why not put maintenance on the other side? if its like the plasma ones, you got 4 free blocks on the sides. So 2 inputs, 1 output, and 1 maintenance should work

**Comment by Lainiel** [comment]
Okay I've found out that you can put maintenance hatch on the bottom. Why you can't put it on the other side is that then you have the same problem outputing enough steam into the Large Steam Turbine. I've got it up to 11586 EU/t which is pretty close I guess.

**Comment by Lainiel** [comment]
Still I think we could use regulators that go to a higher amounts.

**Comment by Prewf** [comment]
I use all my turbines in "precise" mode but I do agree there should be higher tiers of fluid regulators, mainly because there's a lot of super high tier gregtech fluid pipes in the pack right now, and no way to actually regulate those insane rates of fluid if we wanted to do so.

**Comment by richardhendricks** [comment]
11,587 EU/t is the correct output for this setup.

Take the input amount, and divide by optimal flow to calculate penalty for less than optimal flow.

16,000L/t / 16570 L/t = .965600

Multiply by loose efficiency to get effective efficiency

.9656 * .75 = .724200

Multiply by steam input to get EU/t  (HP steam is 1:1 steam:EU, LP steam is 1:2 steam:EU)

.7242 * 16000 L/t = 11587 EU/t

**Comment by Dream-Master** [comment]
So what is the problem here? Is this a balancing issue or a missunderstanding ?

**Comment by richardhendricks** [comment]
The EU output is correct.  There is still an issue with needing larger sized fluid regulators, but in Lainiel's case it is working now.

**Comment by codewarrior0** [comment]
Neither, it's just a weird quirk. The Large Steam Turbine needs to be regulated at a higher rate than we have Fluid Regulators for, so he needed to use two regulators on two input/output hatches to get it working correctly. 

Having another tier of Fluid Regulator would mostly be a quality of life change, not really a bug fix or balance fix.

**Comment by Dream-Master** [comment]
but nothing we can fix? So the issue can be closed or written down in the quest book?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/49c1b700880983bc5fcc5003af2a115be39d8ecb
https://github.com/GTNewHorizons/GT5-Unofficial/commit/5d2eae5ab590117574632f364aa656a71b392b82
