### ISSUE TITLE
Farm Control quest requires wrong electron tubes

### ISSUE THREAD

**Issue by Kataiser9** [GTNewHorizons/NewHorizons#2722]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Not in multiplayer
#
#### What did you try to do, and what did you expect to happen?
Tried to complete the Farm Control quest with gold electron tubes (which are required in the recipe).
#
#### What happend instead? (Attach screenshots if needed)
Quest calls for emerald electron tubes instead, which aren't needed in that recipe.
#
#### What do you suggest instead/what changes do you propose?
Change the quest requirements from emerald to gold electron tubes. :p

**Comment by Dream-Master** [comment]
Sure will check
