### ISSUE TITLE
[2.0.2.7] EBF outputs less gases/fluids than in NEI recipe

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#2725]
For example: 2x basaltic mineral sand + 1x carbon dust.
NEI shows that it should output 1000L of CO2 gas. In reality it outputs 50L of CO2 gas. Either NEI recipe is wrong or EBF is producing incorrect amount of gas.

This also applies to other 3-5 recipes that I tested.

I am using Output Hatch (LV) that is placed on upper layer of EBF.

**Comment by codewarrior0** [comment]
That's normal. Install a better muffler hatch to recover more CO2 gas.

**Comment by EvgenijM86** [comment]
I see. Thanks for info. This is not an issue then and I will close this.
