### ISSUE TITLE
Chemical Formulars

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2727]
#### Which modpack version are you using?
2.0.3.0
#
#### What did you try to do, and what did you expect to happen?
I just scrolled though NEI and looked at some Chemical Formulars of some Metals
#
#### What happend instead? (Attach screenshots if needed)
The chemical formulars of Infinity (I*) and Infinity Catalyst (IC) are completely unlogical, since Infinity isn't
an awakened version of Iodine and Infinity Caltalst is not a compound of Iodine and Carbon.
#
#### What do you suggest instead/what changes do you propose?
Change the formulars to "If" for Infinity Catalyst and to "If*" for Infinity.
I also think that Cosmic Neutronium should get the formular "NtSp".

**Comment by bartimaeusnek** [comment]
if you change it, SpNt instead of NtSp, please, since everything else has already Sp first.
