### ISSUE TITLE
Alloy Blast Smelter flicking on and off?

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2728]
#### Which modpack version are you using?

2.0.2.7
#### What did you try to do, and what did you expect to happen?

Use the Alloy Blast Smelter to make Grisium for a GT++ multiblock. (Ore Washing Plant)

#### What happened instead? (Attach screenshots if needed)

Unsure if this is a duplicate issue or not, but I cannot get the ABS to do anything but click on and immediately off, consuming the items. Also tested in creative with a simpler recipe (Steel dust to molten steel), higher voltage, lower voltage, no dice.

**Comment by draknyte1** [comment]
Update to 2.0.3 or update GT++...

**Comment by bartimaeusnek** [comment]
If you have problems with GT++ please follow the information that @draknyte1 gives you hes the developer of it.

**Comment by Axiflare** [comment]
Thanks! Didn't know the abs was broken until 2.0.3, glad I put off going to Mars xD

**Comment by draknyte1** [comment]
Due to a bug in pollution handling, basically every GT++ multiblock is broken in GTNH pre v2.0.3/GT++ 1.7.0pre6.
