### ISSUE TITLE
Large heat exchanger...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2729]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
... dupes liquids. 
amount of distiller water moderately increasing, amount of ic2 coolant slowly increasing.

Here is the world save file, couse it's too complicated to explain what u need to build.
Go to x = -28 z = 14 y = 71 in overworld to find garden portal.
Go to x = 69 z = -40 y = 5 to find a schematic.
[Testing brag.zip](https://github.com/GTNewHorizons/NewHorizons/files/1825686/Testing.brag.zip)

Well, i think LHE dupes liquids couse amount of coolant increasing, but there might be a problem in any other part =D

**Comment by Dream-Master** [comment]
@Technus @Namikon @richardhendricks @mitchej123 @codewarrior0 
any idea what cause the dupe.

**Comment by codewarrior0** [comment]
Probably the ratio of distilled water to steam or the ratio of hot coolant to steam being rounded up somewhere. Fix would be to make the LHE remember partial amounts of the ratio instead of rounding.

**Comment by Cinobi** [comment]
Hyperic made this system at delta yesterday, except the AE part, and have no liquid dupe. So look like it's another one extra cells bug.

**Comment by Dream-Master** [comment]
Yea extra cells need a fix or a few. It is open source.

**Comment by CalterOK** [comment]
I checked the operation of this circuit for an hour. The amount of refrigerant remains unchanged, and the amount of distilled water decreases. The circuit itself yields about 25,000 Eu / t

**Comment by mitchej123** [comment]
Is this still an issue?
