### ISSUE TITLE
Some quest typos

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2730]
#### Which modpack version are you using?
2.0.3.0

Some typos and/or missing parts.
I will post an improved version of the text below the screenshot:

![2018-03-19_13 55 00](https://user-images.githubusercontent.com/16925725/37614114-291eb516-2baa-11e8-89eb-06535450f783.png)
-> The butchery knife from GT comes with a looting effect depending on the material. You will most likely use iron which will result in looting 2.
Can be used to finish off mobs or to simply make your animal farms more efficient.

![2018-03-19_13 55 18](https://user-images.githubusercontent.com/16925725/37614121-2f678e66-2baa-11e8-9b54-0c64c33a99f9.png)
-> While barrels offer a slot for a single item, drawers can have up to 4 slots each (holding 16 stacks per slot). Once you reach HV you can combine them with some ProjectRed pipes to set up a "ghetto ME storage system" (Tec2k17)

**Comment by Dream-Master** [comment]
@WarlordWossman make a pull request with corret text please.

**Comment by richardhendricks** [comment]
I think the drawers are easier to upgrade too, if I recall correctly.
  They do have one limitation, they can't be opened from all sides.

**Comment by WarlordWossman** [comment]
@Dream-Master alright I modified the file and senz it to @bartimaeusnek directly since I had problems with the pull request.

**Comment by benstuwie** [comment]
I'm glad I'm not the only one who has problems with them
