### ISSUE TITLE
Recipe Changing

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#2732]
#### Which modpack version are you using?
2.0.2.7

#
Need to delete non-gregified recipe from modpack

![](https://cdn.discordapp.com/attachments/224191655375273985/425391921305878530/unknown.png)
to this
![image](https://user-images.githubusercontent.com/37113583/37621240-67baaddc-2bcf-11e8-8dc9-7c701758fdd0.png)
YOU NEED TO CHANGE EM ALL

**Comment by Dream-Master** [comment]
seems to be a client/server problem.

![image](https://user-images.githubusercontent.com/2970688/37851868-c9fac568-2ee0-11e8-968a-08c1ce5f0e50.png)

@barsikus007 please check if your client scripts are wrong or not updated.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37851974-26581d1a-2ee1-11e8-9b69-1a94dc386ff4.png)
![image](https://user-images.githubusercontent.com/2970688/37852008-406daf58-2ee1-11e8-9825-629087ea4953.png)

**Comment by barsikus007** [comment]
Still works on a Delta
![image](https://user-images.githubusercontent.com/37113583/39628651-65c51b00-4fb2-11e8-8962-621360e7b1ce.png)

**Comment by barsikus007** [comment]
now that fixed on delta (I think it worked bcs delta was on 2 0 2 7)  and can be closed
