### ISSUE TITLE
Lucrum Generator

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2733]
#### Which modpack version are you using?
2.0.3.0
It is not possible to obtain a scroll with a study. Paper and writing materials are being spent but the scroll does not appear in the inventory.

**Comment by bartimaeusnek** [comment]
@CalterOK should be fixed, try this https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Emt.zs 

delete the old Emt.zs from your /scrips folder and replace it with this one.

**Comment by CalterOK** [comment]
I already registered through the console command, so I can not check
