### ISSUE TITLE
TF Portal Crystal as Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2734]
If you been in TF and lost your portal you screwed up. Maybe a free Portal Crystal Quest all 24h repeatable will help you out in sp.

**Comment by Bryfer** [comment]
Free is always a bad idea, will lead to abuse. (Atleast on servers)
I'd prefer that you atleast have to collect some items that is fairly common in TF.

**Comment by Dream-Master** [comment]
Yea this is a better idea.
