### ISSUE TITLE
Quest Steam Locomotive  ID #1184 Cannot be finished.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#2736]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Single Player.
#
#### What did you try to do, and what did you expect to happen?
After crafting Railcraft's steam locomotive can't submit it to quest in any way, quest is retrieval task.
#

#### What happend instead? (Attach screenshots if needed)
Quest couldn't be finished.
![2018-03-20_11 07 19](https://user-images.githubusercontent.com/9555787/37648809-4862984e-2c30-11e8-8a36-e190e552cfc9.png)
![2018-03-20_11 07 32](https://user-images.githubusercontent.com/9555787/37648813-4bedddd4-2c30-11e8-9d90-c557e2b7cbd5.png)
![2018-03-20_11 06 44](https://user-images.githubusercontent.com/9555787/37648818-4ed55fae-2c30-11e8-8e7b-0b6efb67e609.png)

#
#### What do you suggest instead/what changes do you propose?
If retrieval problem isn't quest bug just make it crafting task.

**Comment by Dream-Master** [comment]
ok i will check

**Comment by bedrill64** [comment]
Nevermind, typed in wrong version, was on 2.0.2.7, works fine for 2.0.3.0. Can be closed.
