### ISSUE TITLE
Quest Iron Bolts ID #1156 Can't craft Iron Bolts with Ghostwood Fletching.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#2737]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Can't craft Iron Bolts in Tool Forge even with proper ingredients. Natura's Ghostwood Fletching doesn't seem to work with Tinker's Contruct stuff.
#
#### What happend instead? (Attach screenshots if needed)
![2018-03-19_18 30 13](https://user-images.githubusercontent.com/9555787/37648900-8650af4c-2c30-11e8-9071-ebb5c816a92e.png)
![2018-03-19_18 30 15](https://user-images.githubusercontent.com/9555787/37648902-893c9dba-2c30-11e8-9fb7-90cdcf923a79.png)
![2018-03-19_18 30 24](https://user-images.githubusercontent.com/9555787/37648913-8d7b57c2-2c30-11e8-8663-837c845ce1af.png)

#
#### What do you suggest instead/what changes do you propose?
Check if there is any way to change Natura's fleching to fit it into Tinker's or change fletching in quest for one that works with TC.

**Comment by Dream-Master** [comment]
Will check

**Comment by EvgenijM86** [comment]
Maybe set "ignoreNBT" to true here?

```
          "partialMatch": true,
          "ignoreNBT": false,
          "consume": false,
          "autoConsume": false,
          "requiredItems": [
            {
              "id": "TConstruct:BoltAmmo",
```
and also for Magnalium Crossbow Bolts.

**Comment by codewarrior0** [comment]
Oh, the quests for the crossbow and bolts are looking for items with specific names, but those names can't even be typed on my keyboard. I thought I sent in a fix for that...

**Comment by EvgenijM86** [comment]
How do I print NBT data of an item?

**Comment by Dream-Master** [comment]
Ignore nbt not wor well, but I am able to remove some tags that use non static ids etc.

**Comment by codewarrior0** [comment]
I think it's these you have to remove in the JSON:

`"display:10": {
            "Name:8": "�fWooden Crossbow"
          }`

It's a custom name from renaming the tool in a tool station, so it's only counting tools that have a custom name.

**Comment by Dream-Master** [comment]
@bartimaeusnek means that comes from the format if it is Ansi or UTF maybe

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37842792-6872666a-2ec3-11e8-9a86-410004858ff3.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/37843204-8b47df20-2ec4-11e8-8ec4-c3942290f3b6.png)

**Comment by Dream-Master** [comment]
Please test in 2.0.3.1 with feather fletching

**Comment by bartimaeusnek** [comment]
the problem here is that the natura fletching isnt a tinker part, as so it cant be used for tinker tools...

**Comment by Dream-Master** [comment]
You dont need it. Why not making a normal fletching out of feathers. No one ask for a Ghostwood one.

**Comment by codewarrior0** [comment]
I think the `"�fWooden Crossbow"` bit is a bug in BQ. When you craft a new tinker tool, it has a custom name that starts with a chat formatting character `§` but that character gets mangled when it gets saved to the BQ quest file. Not 100% sure on that though.

**Comment by Dream-Master** [comment]
hope it works now after i change the name in raw nbt data in BQ
