### ISSUE TITLE
Field Generator (V) recipe mismatch

### ISSUE THREAD

**Issue by K1ngMX** [GTNewHorizons/NewHorizons#2738]
#### Which modpack version are you using?

2.0.2.7
#### If in multiplayer; On which server does this happen? 

-
#### What did you try to do, and what did you expect to happen?

Crafting Field Generators (V), found a recipe mismatch
#### What happend instead? (Attach screenshots if needed)

Recipes should require the same circuit tier i think
#### What do you suggest instead/what changes do you propose?

Unify the recipe. Im not sure if the component assembler is for cheaper recipes, but i think it is unintended to have a tier lower there.

Not sure if this is the case in the current version of the pack.

![image](https://user-images.githubusercontent.com/5102870/37688634-49270e60-2ca1-11e8-9031-e9fdcbc94b66.png)

**Comment by K1ngMX** [comment]
i have just realised that the component assembler does not have a recipe at all. ignore me :)

**Comment by Dream-Master** [comment]
In 2.0.3 I have a config file to disable component assembler.
