### ISSUE TITLE
[Reminder] Update readme on various launchers / websites

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2739]
Outdated readme / description on:

* twitch 
* curseforge [https://minecraft.curseforge.com/projects/gt-new-horizons](url)
* technic platform [https://www.technicpack.net/modpack/mcnewhorizons.677387](url)
* IC2 forum [https://forum.industrial-craft.net/thread/11403-newhorizons-ultra-hard-gregified-modpack-via-minetweaker-and-modtweaker-gt-thaum/](url)
* FTB forum [https://forum.feed-the-beast.com/threads/1-7-10-gt-new-horizons-ultra-hard-gregified-modpack-via-minetweaker-and-modtweaker-1-2k-quests.181742/](url)
* minecraft forum [https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mod-packs/2391339-gtnewhorizons-gregified-modpack-minetweaker](url)

Feel free to add to this list if I missed something.

**Comment by Dream-Master** [comment]
ic2 forum
minecraft forum
