### ISSUE TITLE
Add Lite Loader to Solder

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#274]
Add Lite Loader to Solder

**Comment by Teteros** [comment]
Mainly for [WorldEditCUI](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292886-worldeditcui).

**Comment by Dream-Master** [comment]
Will add with the next update.

**Comment by Dream-Master** [comment]
Did we realy need this any more ?

**Comment by Dream-Master** [comment]
Ok i close this now.
