### ISSUE TITLE
No styrene recipe in LCR

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2740]
#### Which modpack version are you using?
2.0.3
#### What do you suggest instead/what changes do you propose?

There isn't a recipe for combining benzene and ethylene in an LCR to make styrene. I think it would be a good thing to add. It's 1000L benzene and 1000L ethylene to make 2000L hydrogen and 1000L styrene

**Comment by bartimaeusnek** [comment]
@Dream-Master this was fixed wasn't it?

**Comment by benstuwie** [comment]
I made an issue about it before that was closed 2ish months ago, but it seemed like 2.0.3 didn't have that fix.

**Comment by Dream-Master** [comment]
Fixed in 2.0.3.1 so far I know

**Comment by FallDark** [comment]
i using the lastest build but i dont see styrene recipe in LCR

**Comment by Dream-Master** [comment]
2.0 3.1 which isn't online yet have the recipe

**Comment by FallDark** [comment]
I say i use jenkins lastest build

**Comment by Dream-Master** [comment]
Ok then the circuit not match. Will check again

**Comment by draknyte1** [comment]
The recipe for styrene is retarded. 
Ethylene and benzene combine to form ethylbenzene. Which is then Further processed into styrene. 

GT Chemistry is wrong on this one.

**Comment by Dream-Master** [comment]
Sure we can do it thus Way nur then i Need to remove the gt Chemical recipes @draknyte1

**Comment by draknyte1** [comment]
CodeWarrior suggested adding circuits to the GT recipe and calling it a shortcut. I can add extra recipes of Ethelbenzene to plastic that are 'cheaper' to encourage the proper chain of chemistry. Thoughts?

**Comment by codewarrior0** [comment]
That was more of a reference to how if you're going to split up the Styrene recipe to have an intermediate step that produces Ethylbenzene, and another step that turns that into Styrene and Hydrogen, then it follows that you'd add a circuit 24 "shortcut" recipe to the Large Chemical Reactor that just combines the two recipes into one step - giving us the recipe we already have.
