### ISSUE TITLE
Galacticraft Sealable Blocks Incorrect Config

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2743]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What happened? (Attach screenshots if needed)
Whenever someone goes to space on my server, it prints out this error log:

[config] External Sealable IDs: unrecognised block name 
'ProjRed|Illumination:projectred.illumination.lamp:0-31'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.lairBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.bittBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zechBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.agonBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.crayBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.venaBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.auroraBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.solsBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.mystBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.mintBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.vectBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zomeBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zionBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zorgBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.tankBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.ztylBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.jeltBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.korpBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.krypBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.laveBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zoneBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.fortBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.roenBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.redsBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.venaBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.iszmBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zkulBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.glaxx:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.reedBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.syncBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.azurBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zestBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zythBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zaneBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zoeaBlock:0-15'.
[config] External Sealable IDs: unrecognised block name 'Ztones:tile.zetaBlock:0-15'.

This makes me think that the GC config is incorrect and those blocks aren't being set as oxygen sealed properly.
#
#### What do you suggest instead/what changes do you propose?
The GC wiki documentation implies that an entry can either have a single metadata value, such as :0, :1, etc, or it can be :\*.  I don't think it can do :0-15, etc.  So I suggest changing the config so that all of those blocks have mod:blockname:\* instead.  I can't actually test if this works, because I haven't yet gone to space, but hopefully someone else can verify for me.

**Comment by Dream-Master** [comment]
Ok will check
