### ISSUE TITLE
HV Plate Bender quest

### ISSUE THREAD

**Issue by codewarrior0** [GTNewHorizons/NewHorizons#2744]
The HV Plate Bender quest in Tier 4 mentions that this bender can be used to make double and triple plates. However, the MV Bender is sufficient for *any* plate bender recipe.

Suggest replacing this quest with an HV Extruder Quest. The HV Extruder is needed to extrude tough metals like Tungstensteel and HSS.

**Comment by Dream-Master** [comment]
Sure will look what i can Change.
