### ISSUE TITLE
Downgrade Apple Core

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2746]
I hear Thermos had problems with newest version.

**Comment by draknyte1** [comment]
Shouldn't server owners using Thermos/kCauldron be managing this sort of stuff themselves? Issues like so shouldn't fall on the modpack to support, when they'r eusing non-standard server cores. Just my take on it.

**Comment by Dream-Master** [comment]
it is a remider for me too. I need to downgrade it in client too.
