### ISSUE TITLE
Personal relocator not craftable

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2747]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft Personal Relocator
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/23512002/37844548-3df47ad4-2ed9-11e8-991a-d5552bd61ffd.png)

#
#### What do you suggest instead/what changes do you propose?
Recipe requires  <IC2:itemBatLamaCrystal:27>
Should be either 0 (empty) or 26 (charged) or * (any)

**Comment by bartimaeusnek** [comment]
i think the recipe is changed anyway...
