### ISSUE TITLE
electro-magic tool bug

### ISSUE THREAD

**Issue by PeanutTheMiner** [GTNewHorizons/NewHorizons#2752]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
I can't charge electric scribing
#
#### What happend instead? (Attach screenshots if needed)
![2018-03-25_17 23 53](https://user-images.githubusercontent.com/37768606/37873153-4fafdf4c-3051-11e8-9a6a-10df2432454a.png)

#

**Comment by codewarrior0** [comment]
I always had to charge those in an LV gregtech machine. Thought it was weird because it's made with an HV battery...

**Comment by Dream-Master** [comment]
@bartimaeusnek can you change the code that it use hv machines and have a better charge than 400k ?
