### ISSUE TITLE
[balance] coke oven bricks in alloy smelter are not benefitial / take too long

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2754]
#### Which modpack version are you using?
2.0.2.7 (but it's the same in 2.0.3.0 anyways)

Coke ovens are kinda important if you wanna make steam, since charcoal is the only fuel you can fully automate in LV (there is some other exaples but they are quite obscure).
Coke ovens are slow so you need a few of them. Vanilla furnaces take cobblestone so you can spam them and make coke oven bricks in there. The alloy smelter recipe saves some sand, but building more than one alloy smelter is slowing your progression down and you need more boilers to run them. This is the recipe I am talking about:

![half_this](https://user-images.githubusercontent.com/16925725/37878642-8229906a-306c-11e8-8c50-4b0cdfc108b7.PNG)

I have even made a high pressure alloy smelter to speed it up but as I said, vanilla furnaces are the easier route to make coke oven bricks atm since you fuel them with creosote and they don't cost bronze/steel.
It might not sound that slow at first but keep in mind that a coke oven needs 104 bricks, and there is a quest that wants you to craft 10 of them.

My suggestion is quite simple to fix this: Just make this recipe 5 seconds instead of 10 seconds.

**Comment by richardhendricks** [comment]
An extra alloy smelter, even a steam one in LV/MV, is super useful to have.  So I think encouraging players to make a second to speed up is OK.

**Comment by Dream-Master** [comment]
You dont need it @WarlordWossman at the age when you are able to make a coke overn you hav bo no machines. Later on you can do other stuff during the machine is working. And 10 secs are not really long.
The brick form way with 10 furnaces is much faster.

**Comment by bartimaeusnek** [comment]
so since its rejected ill close this.

**Comment by WarlordWossman** [comment]
Well yeah leave the recipe how it is then, I will just never use it because saving one sand is a joke.

@richardhendricks I am currently in that stage and have no clue why I would use steel or bronze to make another alloy smelter if I can just build furnaces from cobblestone. This recipe doesn't encourage you to get an other alloy smelter by any means.

**Comment by codewarrior0** [comment]
I always thought this recipe was some kind of joke.

That being said, it might make for a more elaborate joke if it was 1 Sandstone + 1 Clay Block = 1 Coke Oven Brick Block

**Comment by richardhendricks** [comment]
I've talked to @WarlordWossman  and rethought this, it does make some sense to get players off of vanilla machines and into GT machines. Instead of making the time 5s, I would leave it at 10s but give them 2 coke oven bricks.  That would encourage saving resources by technology, and automation with hoppers to feed/collect can speed it up.  So a new player would see the Alloy Smelter recipe and be "I want thaaaaat" instead of just "LOL I'll spam 10 easy furnaces"

**Comment by Dream-Master** [comment]
Yea will take a look.

**Comment by richardhendricks** [comment]
Also, a change to the 10x coke ovens quest that says "Search NEI for a more efficient way to make coke oven bricks"

**Comment by Raccoon2709** [comment]
Also RedSand do not work. Hopefully not intended.

**Comment by Dream-Master** [comment]
yea will add

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/64b91e5ae3c5bbc31a78d9ec2d4c55a8e419c0fd
