### ISSUE TITLE
[2.0.2.7] Cropnalyzer crashes the game

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#2756]
I tried using Cropnalyzer.
1) Additional menu that is opened by C key will crash the game if you try to input seeds in it and press "Process".
2) I tried recharging cropnalyzer with lithium battery (LV) and at some point my game would crash (after reaching 50+% charge). Starting the game again and opening GUI (right click) after that will again crash my game instantly.

Here is my latest crash log:
https://pastebin.com/TXuaiPea

**Comment by EvgenijM86** [comment]
It seems crashes in 2nd case are not because I recharged Cropnalyzer, but because I was growing crops.

**Comment by Dream-Master** [comment]
Use newer berries ++ version

**Comment by EvgenijM86** [comment]
Thanks, that have fixed this issue for me. Even crop calculator is working without errors.
