### ISSUE TITLE
Remove TiCo OreBerry Bushes from Quests

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#2757]
#### Which modpack version are you using?
2.0.3.0

#### What do you suggest instead/what changes do you propose?
Fully remove TiCo OreBerry Bushes from Quests and replace them with the OreBerries, they can be placed on crops, so you don't need the bushes and can't get easy materials from bush farms with a watering can, in addition, the OreBerryBushes are 100% foolproof, they cant be trampled or infested, are very easy to set up and have a high yield, conclusion: they are way to OP, especially if you play in groups and get them multiple times...

**Comment by WarlordWossman** [comment]
+1 for this.

Currently playing and pre LV I can buy a lot of stuff using XP buckets (poor man's UU matter) because of XP berries. Also got a stack of AL dust (been playing for 3 days).

**Comment by Dream-Master** [comment]
I did a quest you can buy ore berry bushes once and berries as a repeatable quest

**Comment by WarlordWossman** [comment]
Yes but in the end you don't want players to get a single one of the bushes since they are just too fast and foolproof still. If we only ever hand out the berries we could also add a tooltip to them that refers to them being placeable on cropsticks.
