### ISSUE TITLE
[2.0.2.7] Improvements to Gallium Arsenide Quest

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/NewHorizons#2758]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Find Arsenic, which is horribly hard to obtain at LV where the quest is aimed.
#
#### What happend instead? (Attach screenshots if needed)
Spent several hours trying to find two small Realgar ores in the Nether, because there is no hints towards having a Level 7 Tool to mine Cobalt, nor can you process Cobaltite until MV.
#
#### What do you suggest instead/what changes do you propose?
Adding more information to the quest, hinting that with a leveled up Obsidian Pickaxe, you can easily mine the Cobalt in the Nether. This would save players from Strip mining for Small ores that spawn across 80 Y levels, plus hint towards a nice higher level pickaxe type. It's not very intuitive to look at every single pickaxe head in NEI to determine what's actually craftable at LV.

![2018-03-26_13 22 55](https://user-images.githubusercontent.com/3060479/37885597-73fa528a-30f9-11e8-8c0f-efbbc46d99d4.png)

**Comment by richardhendricks** [comment]
It would require significant quantities of cobalt ore to get enough cobaltite dust to get arsenic.  Better idea would be to hint at using a miner to search for you between the correct Y heights.

"You can get arsenic from realgar small ores in the nether at Y level 5-85. You can search by pickaxe, or try an automated miner to search for you."
