### ISSUE TITLE
Raspberry IC2 crop missing texture

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2759]
#### Which modpack version are you using?
2.0.3.0

Raspberry plant is missing texture.
![2018-03-25_23 53 00](https://user-images.githubusercontent.com/1214811/37887503-bf18ad92-3087-11e8-9709-7d18edb2a77f.png)

**Comment by Dream-Master** [comment]
@bartimausnek any idea or is this fixed in newer build?

**Comment by bartimaeusnek** [comment]
This isn't even an issure, it has a texture as you can see on the picture... look at the bottom of the crops...

**Comment by bartimaeusnek** [comment]
![blockcrop raspberry 1](https://user-images.githubusercontent.com/33183715/37902174-e1af49da-30f3-11e8-8bf7-4d03c6e81084.png) without texture, the whole crop block would be purple/black with dots and you wouldnt see the crops all.

**Comment by richardhendricks** [comment]
haha sorry, the purple/black just triggered me.
