### ISSUE TITLE
Shimmerleaf IC2 crop not maturing

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2760]
![2018-03-26_01 29 49](https://user-images.githubusercontent.com/1214811/37890226-6022e18c-3095-11e8-8412-fce70b94979a.png)
![Uploading 2018-03-26_01.29.55.png…]()

#### Which modpack version are you using?
2.0.3.0

IC2 crops are supposed to mature until the final stage, and stay there if there are special requirements.  Shimmerleaf doesn't mature at all, stays at zero.  Even with quicksilver block beneath it,

**Comment by Drobac** [comment]
Check if you can use a chisel to change the type of quicksilver block you are using. Currently its a thaumic bases version, check if you can change it to a TC block one. Also a TC block could have a different crafting recipe

**Comment by Dream-Master** [comment]
@bartimaeusnek are the Blocks underneath ordicted? Maybe Thaumic bases not ordict blocks right.

**Comment by bartimaeusnek** [comment]
Will Check
