### ISSUE TITLE
Higher tier crossbow quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2761]
#### Which modpack version are you using?
2.0.3.0

Add two new crossbow quests at MV
One for aluminum limb, one for carbon limb.  Setup quests so that if you complete one, you cannot complete the other (like the fading node choice quest).
Aluminium limb is higher durability and faster draw, but slightly lower arrow speed (DPS)
Carbon limb is 1/4 durability but faster arrow speed (DPS)

Check if these quests are needed
vanadiumsteel bolt quest?

HV add energetic alloy limb quest (need vac freezer?) (EA is very durable, but slightly slower draw and arrow speed)?

meteoric steel/EA bolt core quest after visiting the moon.

**Comment by benstuwie** [comment]
At this point, should there just be a whole ticon progression tab? I mean, we got a bunch of quets, and there's a bunch more that could be useful, like these. Also more hammers, some oriharukon for the speed and durability later. Maybe even a trinium hammer at some point. Could also have some pickaxe quests. That's something I wish I had when I started. I didn't really know what materials were good when I got to LV.

**Comment by richardhendricks** [comment]
A whole "Tools" tab with useful tools across mods would be a good idea I guess, including dark steel tools, thaumcraft tools, drills etc.    I do like having the tools quests mixed in the tiers tab though so you know when they appear.

**Comment by CalterOK** [comment]
Not everyone uses crossbows, some prefer bows. Maybe you should then make alternative quests to choose from for bow and crossbow?

**Comment by richardhendricks** [comment]
Are there bows that are even half as good as the TiCon crossbows?

**Comment by Dream-Master** [comment]
Ok we have magnalium in lv allready and alu /crabon is not much better. Not sure if you wast your Crossbow when using this materials. A better material for MV is needed @richardhendricks 
I look only on the values not have much experience with crossbows ingame.

**Comment by codewarrior0** [comment]
My next bow limb after Magnalium was Energetic Alloy. Slightly slower, but much better durability and much better arrow speed, so it hits harder too.
