### ISSUE TITLE
[Idea] Circuit boards crafting

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2762]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
All circuit boards except the most lowtier and plastic circuit board req chem reactor with sulpric acid.
![2018-03-27_21 06 49](https://user-images.githubusercontent.com/25028786/37986009-0b517c6c-3203-11e8-8775-89801dbb461a.png)
![2018-03-27_21 06 55](https://user-images.githubusercontent.com/25028786/37986010-0b7904bc-3203-11e8-8fc4-3edcbf6dd51d.png)
![2018-03-27_21 07 09](https://user-images.githubusercontent.com/25028786/37986011-0b9bd398-3203-11e8-9de0-a6fd01307563.png)

Plastic circuit board need chem reqctor with sulpric acid and circuit.
![2018-03-27_21 07 13](https://user-images.githubusercontent.com/25028786/37986059-30a0b794-3203-11e8-96d1-8fff71a09dd7.png)

This force ppl to have 2 chem reactors with same liquid, this is annoying and have no sence atall. Please, remove circuit from plastic circuit boards recipe, this would be very cool =D

**Comment by Dream-Master** [comment]
@Cinobi can i add a foil ? better than remove the circuits and remove the intiered recipe.

**Comment by Cinobi** [comment]
@Dream-Master one or two annealed copper foil will be naisu i think.

**Comment by benstuwie** [comment]
I'm almost positive this doesn't make you need 2 chem reactors for H2SO4. I have one for that, and one for iron3chloride, and I've never had problems.

**Comment by codewarrior0** [comment]
It makes you need two regular chem reactors because you can't remove the circuit and it only has two slots, but if you use an LCR you can do both (and the etching steps) in the same reactor.

**Comment by bartimaeusnek** [comment]
@Dream-Master maybe add it with annealed copper foils for more output (3 instead of 2 boards)?

**Comment by Dream-Master** [comment]
No 2 is a boost allready

**Comment by benstuwie** [comment]
You can already make 4 at once
