### ISSUE TITLE
[Idea] Powered plunger/siphon pump

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2763]
Would be nice to have a powered tool version of the plunger, that could also store liquids in cells.  I propose a powered siphon pump device that will transfer fluid contents to first large fluid cell in your inventory. 

Pros 
- Allows players/obsessive-compulsives to empty input tanks. 
- Conserve partial quantities of fluids that are used in very small amounts, ie Argon
- Could be tiered, with higher tiers pumping fluids quicker (LV tier should be slightly painful to use, maybe 100L/s?)

Cons
- Would require new model (Ideas? https://www.homedepot.com/p/DuraHeat-Battery-Powered-Siphon-Pump-DH-20/100125308?cm_mmc=Shopping%7cVF%7cG%7c0%7cG-VF-PLA%7c&gclid=Cj0KCQjw-uzVBRDkARIsALkZAdmfsqqdtIjEZufldBnSp0Xn2LX9mKyUp_9i47DXFe2eBNQ2cOgSWWoaAjiVEALw_wcB&dclid=CPnawOCkj9oCFRCIaQodFToJYQ 
- Need to interact with player's inventory (Soldering iron already does this)
- Need to locate partially filled cells with similar fluid before using empties

**Comment by draknyte1** [comment]
Literally the point of the small IC2 addon called IHL (I Hate Liquids), which was solely created to add a hand pump and two electric versions of it. On top of that, it adds things like Ye sap bag for rubber trees. Maybe look into why this mod wasn't originally added as mentioned by Dream, instead of reinventing the wheel?

**Comment by Dream-Master** [comment]
Thats why is was labeld with very low priority and yes we have much more important issues :)

**Comment by richardhendricks** [comment]
It adds a hell of a lot more than that (at least now) 
https://minecraft.gamepedia.com/Mods/IHL_Tools_%26_Machines

**Comment by draknyte1** [comment]
I'm aware.. but extra chemistry and microcrafting never hurt anyone. 

It all runs IC2 eu so it's rather flexible in use.

**Comment by repo-alt** [comment]
Hand pump and rubber sap sack were recently separated in a tiny mod of it's own, called Cutting Edge
http://minecraft.curseforge.com/projects/cutting-edge
For those who do not need complex IHL machinery with weird microcrafting

**Comment by repo-alt** [comment]
Oh, looks like it does not include hand pump, derp.

**Comment by bartimaeusnek** [comment]
> Need to locate partially filled cells with similar fluid before using empties

pseudocode:
```
list<itemslot> empty_cells_in_inventory;
linkedhashmap<itemslot,fluid> partitalfull_cells_in_inventory;
for (itemslot i : items_in_player_inventory)
    if ( i.item instanceof universal_fluid_cell){
        if (i.item.fluid_amount.equals(0))
           empty_cells_in_inventory.add(i);
        else if (i.item.fluid_amount < i.item.maxfluid_amount)
           partitalfull_cells_in_inventory.add(i,i.item.fluid);
```

**Comment by richardhendricks** [comment]
GT++ has added a handpump.
