### ISSUE TITLE
[LagSpikes] Permanent log spam happening.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#2766]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?

While playing and wandering around i started getting lagspikes, after checking logs noticed there is pattern that spams sometimes few times per second. Couldn't find any reason for this one, tried emptying invertory, but doesn't seem to help, it happens sometimes  without inventory opening, just wandering around, lagspike, and this shows up in log several times making log full of this. Tried some online searching, this spam was seen several times but couldn't find solution or reason for this one. Maybe someone here knows what is going on. Tried to ignore this but became really annoying making game hard to play.

Here is what i get:

> [B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@6579612c:
[B#355]  java.lang.NullPointerException
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: Index: 22 Listeners:
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 0: HIGHEST
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 1: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.StoneToolHandler@55cf0c55 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 2: HIGH
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 3: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.LevelingToolTipHandler@7e893459 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 4: NORMAL
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 5: ASM: mods.battlegear2.client.BattlegearClientEvents@4909dfba onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 6: ASM: net.bdew.lib.tooltip.TooltipHandler$@87436d2 handleTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 7: ASM: thaumcraft.common.lib.events.EventHandlerRunic@3bb4383a tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 8: ASM: buildcraft.core.list.ListTooltipHandler@1ba144d0 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 9: ASM: com.rwtema.extrautils.modintegration.TConEvents@2e2d33d unstableTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 10: ASM: com.pam.harvestcraft.PamTooltipEventHandler@1de977a3 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 11: ASM: crazypants.enderio.machine.painter.BlockPaintedGlowstone$PainterTemplate@1d17af7e onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 12: ASM: minetweaker.mc1710.ForgeEventHandler@4206999 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 13: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@4b801f16 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 14: ASM: DummyCore.Utils.DummyEventHandler@cef95ce onDescrAdded(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 15: ASM: speiger.src.crops.handler.Handler@15231d45 onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 16: ASM: mcp.mobius.betterbarrels.bspace.BBEventHandler@57b04d4a onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 17: ASM: tonius.neiintegration.mods.mcforge.MCForgeTooltipHandler@b08b278 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 18: ASM: openblocks.enchantments.flimflams.LoreFlimFlam$DisplayHandler@40ee2e82 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 19: ASM: openperipheral.addons.glasses.client.TerminalManagerClient$ForgeBusListener@5b62290f onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 20: ASM: lumien.randomthings.Handler.RTEventHandler@32536b25 toolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 21: ASM: remoteio.client.handler.TooltipEventHandler@6cb04099 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 22: ASM: com.Zoko061602.SuperTic.SuperEventHandler@459126da Tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 23: ASM: jcm2606.thaumicmachina.client.event.RenderEventHandler@1053748a onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 24: ASM: net.darkhax.wawla.addons.generic.AddonGenericTooltips@29ba0a0d onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 25: ASM: fox.spiteful.avaritia.LudicrousEvents@2fff3adb onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 26: ASM: com.rwtema.extrautils.EventHandlerClient@1416b17e generatorTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 27: ASM: buildcraft.builders.BuilderTooltipHandler@791d8a43 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 28: ASM: com.dreammaster.modctt.CustomToolTipsHandler@77616098 onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 29: ASM: fox.spiteful.forbidden.FMEventHandler@7c6c132b onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 30: ASM: INSTANCE addTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 31: ASM: com.enderio.core.client.handlers.EnchantTooltipHandler@36703a59 handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 32: ASM: com.enderio.core.client.handlers.OreDictTooltipHandler@e04d554 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 33: ASM: crazypants.enderio.conduit.item.filter.ClearFilterRecipe@4849aa94 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 34: ASM: crazypants.enderio.machine.ClearConfigRecipe@49ae873a onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 35: ASM: eu.usrv.enhancedlootbags.core.LootGroupsHandler@3d6caa65 onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 36: ASM: makeo.gadomancy.common.events.EventHandlerWorld@4a32844b on(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 37: ASM: gtPlusPlus.xmod.eio.handler.HandlerTooltip_EIO@71441bd7 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 38: ASM: invtweaks.forge.ClientProxy@6bcec394 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 39: ASM: modtweaker2.ClientEvents@5c6ee571 onDrawTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 40: ASM: taintedmagic.common.handler.TaintedMagicEventHandler@718dd6da tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 41: ASM: squeek.spiceoflife.gui.TooltipHandler@3587e93b onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 42: ASM: net.blay09.mods.tcinventoryscan.client.ClientProxy@2a0b99bd onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 43: ASM: squeek.tictooltips.TooltipHandler@e372336 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 44: ASM: tconstruct.achievements.AchievementEvents@762e679b tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 45: ASM: iguanaman.iguanatweakstconstruct.harvestlevels.VanillaToolTipHandler@75d05d85 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 46: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.MobHeadTooltipHandler@398647c0 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 47: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaToolNerfHandler@7499fcc7 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 48: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaHoeNerfHandler@17704fe2 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 49: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaSwordNerfHandler@755a3634 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 50: ASM: iguanaman.iguanatweakstconstruct.restriction.PartRestrictionHandler@6c17a4a3 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 51: LOW
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 52: ASM: iguanaman.iguanatweakstconstruct.replacing.PartToolTipHandler@745f1884 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 53: LOWEST
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 54: ASM: makeo.gadomancy.common.events.EventHandlerGolem@1fac15ce on(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[B#355]  [14:30:06] [NEI Item Filtering/ERROR] [FML]: 55: ASM: iguanaman.hungeroverhaul.util.IguanaEventHook@31f51d75 renderTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V

**Comment by CalterOK** [comment]
I also had the same. The problem is in fashion  "SuperTiC"

**Comment by Dream-Master** [comment]
@Zoko061602 any idea about it?

**Comment by Zoko061602** [comment]
I think I fixed it, there was a problem with some NBT values.
1.1.1b is currently checked by curseforge.

**Comment by Dream-Master** [comment]
Ok cool and thanks

**Comment by Zoko061602** [comment]
I guess that should also fix #2742

**Comment by Dream-Master** [comment]
What you mean @Zoko061602  it does not?

**Comment by Zoko061602** [comment]
1.1.1b doen't fix #2742

**Comment by Dream-Master** [comment]
Any additional idea how it can be fixed? And we need a standard config with a few values to make the mod give benefits to materials @Zoko061602

**Comment by Zoko061602** [comment]
I don't understand  #2747's Crash Report.

**Comment by Dream-Master** [comment]
@Zoko061602 you mean #2742  I guess

**Comment by bedrill64** [comment]
@Zoko061602 Yo, do you have any quickfix that I can download for SSP?

**Comment by Dream-Master** [comment]
Hope we hear from yu soon @Zoko061602

**Comment by Zoko061602** [comment]
Version 1.1.1b:
https://minecraft.curseforge.com/projects/supertic/files
