### ISSUE TITLE
Lag when using HV distillery

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/NewHorizons#2767]
GT NH 2.0.3.0 Singleplayer

When using HV distillery (and probably tiers above), game lags. The recipe is heavy fuel to toluene. It's 0,8sec on LV tier. So 0,2 on HV. 
It seems like such a fast recipe repeated over and over, makes the game lag.
I can't find any recipe better converting to toluene.

Maybe change recipe, so more stuff is converted slower. Same overall speed.

**Comment by Cinobi** [comment]
Well, _all_ fast GT machines creates lag, but distillery... try to make dist water in it =D

**Comment by Dream-Master** [comment]
I dont see the issue here? @Cinobi @madmacf

**Comment by madmacf** [comment]
My FPS drops maybe around 10-15 using the HV distillery with that recipe.

Got a big factory.

**Comment by Dream-Master** [comment]
In sp?

**Comment by bartimaeusnek** [comment]
@madmacf please post if you use OptiFine and which version, if you use shaders, the specs of your hardware. RAM ("Memory") and CPU ("Processor").

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2767

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3030

**Comment by madmacf** [comment]
No optifine. Yes SP. No shaders. See original post. 

The problem is the recipe is so fast and and is repeated a lot. Thats why I wrote maybe change it to process more material and slow it down.

**Comment by richardhendricks** [comment]
Yeah that's a good idea.  We can take it under consideration.
