### ISSUE TITLE
When searching in the creative menu, crash occurs

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2768]
#### Which modpack version are you using?
2.0.3
#
#### If in multiplayer; On which server does this happen? 
singl
When searching in the creative menu, crash occurs
[crash-2018-03-30_20.38.11-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1864319/crash-2018-03-30_20.38.11-client.txt)

**Comment by draknyte1** [comment]
Happens in every modded pack, caused by every second mod.
Basically, there isn't a fix except not using the Creative Search bar.
Use Creative+ and the NEI bar, you'll never have a problem.

**Comment by bartimaeusnek** [comment]
^this.
