### ISSUE TITLE
[quest]Add info on built in shutter for pipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2769]
Add note to first pipes quest about using shift-wrench on pipes to make them input-only.

**Comment by draknyte1** [comment]
Fairly sure it does tell you, because that's how I learnt ;)

**Comment by Dream-Master** [comment]
It is allready in the Text @richardhendricks

**Comment by Dream-Master** [comment]
`Shift clicking on the end of a pipe will disable the fluid input on that side. This is super handy, for example, to prevent coal boilers from feeding back steam into water pipes.`

**Comment by richardhendricks** [comment]
Just saw a comment in discord, I guess by a player who was past the quest and didn't know about the new feature.
