### ISSUE TITLE
Quantum Tank I and II and Fieled Generators recipes change

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#277]
Recipes for all the quantum tanks require osmium atm which isnt available till tier IV planets. Once you get it, you can craft quantum tanks tier 1-3 but youll craft the tier 3 because its not much more resources then the lesser ones. 
Recipes for all the quantum tanks require osmium atm which isnt available till tier IV planets. Once you get it, you can craft quantum tanks tier 1-3 but youll craft the tier 3 because its not much more resources then the lesser ones. 
Tier I - 1,602,000 MB
Tier II -  9,612,000 MB
Tier III - 57,672,000 MB
So it would be good if we could craft the tier I and II at an earlier tech level.
The only part in the recipe that would need to be modified are the field generators.

**Comment by Dream-Master** [comment]
Is osmium not in the byproduct list of iridium?

**Comment by Drobac** [comment]
yes, but it would be nice if we could tier the early quantum tanks, for example make the Tier 1 available at about moon, tier II at mars and tier III is already available at asteroid tier

**Comment by Dream-Master** [comment]
Yes i get what you mean have to change the Field generator recipes. I chnage the Quantum tanks too using gt and my chipsets.

**Comment by Drobac** [comment]
dont change the field generator cause they are used in a bunch of other recipes, just replace the field generators in the quantum tank recipes with something else tier appropriate

**Comment by Dream-Master** [comment]
If i change anything i will change both otger things dont make sense.

**Comment by Dream-Master** [comment]
A lot of work but finaly ready. I have to add all the recycle recipes because balancing.

**Comment by Drobac** [comment]
You overdid it with the Field Generator (IV) recipe, current recipe is the same as the requirement for build a 1/4 of a fusion reactor ( thats just in superconductors) so using 2 (which is in most recipes is half of a fusion reactors worth) is waaaay to expensive.

Change the 16x Superconductor Wire into 1x Superconductor Wire (which is already a pain to get), and change the nether star block with a maximum of a double nether star plate ( so 2 nether stars per generator)

**Comment by Dream-Master** [comment]
Will see what i can do.

**Comment by Dream-Master** [comment]
@Drobac The problem is when i changing the Field generator recipes i have to change all recycle recipes or i have to delete the recycle recipes.
Changing all recycle Recipes are more than 100.

Choice one let it like it is.
Choice two change the recipes but disabled the Recycle receipts
Choice tree try to find a way get osmium in small pieces before like i can add avery small chance on Mars Rock (my dust etc)

**Comment by Drobac** [comment]
small pieces of osmium might not be a bad idea, cause you dont need a ton of it to make the tank/chest so youll invest the time to try and get it. This is also the simplest solution that does not require you to change 100s of recipes

**Comment by Dream-Master** [comment]
How rare it have to be?

**Comment by Dream-Master** [comment]
I see in Endstone is 5 % chance for tiny pile of Tungsten in it.

**Comment by Dream-Master** [comment]
Netherrack have a 5% chance of gold.
So maybe Mars Stone have to have a 5% chance of Tiny Pile of Osmium Dust maybe ?

**Comment by Namikon** [comment]
It would probably mess up the ore tiering, as Osmium is Tier5 and Mars is Tier2. One Idea would be to let small iridium spawn on mars, so you can process that into osmium. Regardless of the decision, it might cause things to become available a lot earlier. Even if you set the dust to 1%, that dust is available in infinite amounts, so just by adding time, you can get all the osmium you need without reaching Tier5 planets

**Comment by Dream-Master** [comment]
Thats what i make with Drobac yesterday.
````````````````````````````
Moon
SiO2 small 50%, Manganese small 20%, Olivine small 10 %, rare earth tiny 7,5 %, Patinum tiny 5%, Tungsten tiny 3%. 

Mars 
Bandet Iron small 50%, Magnesium small 30%, Aluminium small 20%, Ruby tiny 10%, Diamond tiny 5%, Iridium tiny 3%

Asteroids 
Gold small 50%, Lead small 30%, Titan small 10%, Diamond tiny 7,5 %, Chrome tiny 5%, Osmium tiny 3%,
`````````````````````````````

Maybe have to change it and add other Planets Dust to get Ossmium a bit later.

**Comment by Dream-Master** [comment]
So small Iridium is available on Tier 3 Planets all ready. I think lower the chance to 1 or 0.5 % get Osmium from the Asteroids dust would be ok?

**Comment by Dream-Master** [comment]
Change back and ossmium now in Asteroids rocks.
