### ISSUE TITLE
Soul Brazier turns nearly everything into tainted land 

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2770]
#### Which modpack version are you using?
2.0.3.0
#
#### What did you try to do, and what did you expect to happen?
I tried to get rid of my Warp and used the Soul Brazier, which was a bit too expansive to keep it running, so I let it stand there, and exspected that nothing would happen, since it had no Warp stored.

#
#### What happend instead? (Attach screenshots if needed)
![2018-03-30_21 15 58](https://user-images.githubusercontent.com/32712367/38150648-464307fa-3460-11e8-80d0-e403246e93f7.png)
It turned nearly everything into tainted biome.
#
#### What do you suggest instead/what changes do you propose?
Make the soulbrazier only taint things when active.

**Comment by draknyte1** [comment]
Without delving into the code too far, The general consensus it that it's not even a 100% functional block.
https://www.reddit.com/r/feedthebeast/comments/34lp85/so_the_soul_brazier_with_action_shots/

When it runs out or Mortus, it will release all warp it's containing (To the best of my Non-Thaumcraft knowledge), which is probably what happened to you.

**Comment by Zoko061602** [comment]
I checked the code and it only taints the world when it's running.
I think that mose of the taint came from spreading.

**Comment by draknyte1** [comment]
All good! I only had a quick look for a solution while on mobile but I figured it may help.
At least it serves as information for anyone else looking to know why they got tainted ;)
