### ISSUE TITLE
Rainforest Oak doesn't go in the Advanced Coke Oven

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2771]
#### Which modpack version are you using?
2.0.3.0
#
#### What did you try to do, and what did you expect to happen?
I wanted to turn some Rainforest Oak into charcoal. 

#
#### What do you suggest instead/what changes do you propose?
`mods.railcraft.BlastFurnace.addRecipe(<miscutils:blockRainforestOakLog>, false, false, 20, <minecraft:coal:1>);`

**Comment by draknyte1** [comment]
It works as expected in a standard coke oven, so wherever they add logs to the RC 'Blast Furnace' is either before my logs exist or they don't iterate the oreDictionary properly.

**Comment by Dream-Master** [comment]
I can add it via modtweaker as you said to make it working @Zoko061602 . We using the blast furnace as advancee coke oven in GTNH.
