### ISSUE TITLE
Missing IC2 cell for Iron3Chloride

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/NewHorizons#2773]
GT NH 2.0.3.0 Singleplayer

Not a bug, but it would be nice to have a IC2 cell with iron3chloride.
It's very hard to filter the universal fluid cells version with ender IO.
It's used in just about every circuit board recipe.

**Comment by Dream-Master** [comment]
Yea a lot of fluids that not added  in the material list have only universal cells no gt/ic2 cells. For plastic the same

**Comment by Dream-Master** [comment]
Molten cells was added by Tec

**Comment by draknyte1** [comment]
Time to make all GT cells worthless and replace them with a cell Meta-Item, then make the former shapeless craft into the later.

Keeps compat and allows 32k cell types.
