### ISSUE TITLE
Crash when pressing search items button in creative.

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/NewHorizons#2774]
GT NH 2.0.3.0 Singleplayer

Crash when pressing search items button in creative.
Happens every time.
[2018-04-02-2.log.gz](https://github.com/GTNewHorizons/NewHorizons/files/1868118/2018-04-02-2.log.gz)

**Comment by draknyte1** [comment]
Refer to https://github.com/GTNewHorizons/NewHorizons/issues/2768.

**Comment by bartimaeusnek** [comment]
^ this
