### ISSUE TITLE
Thaumic Tinkerer mod embeds old version of AE2 API

### ISSUE THREAD

**Issue by codewarrior0** [GTNewHorizons/NewHorizons#2775]
Modpack version 2.0.3.0

The file `ThaumicTinkerer-2.5-1.7.10-554-GTNH.jar` contains an old version of the AE2 API, as the folder `appeng/api` inside the JAR. This means sometimes, Forge will load the old version from the TT jar, and sometimes it will load the correct version from the AE2 jar. If it loads the old version, we see an issue where the ME Fluid Terminal and ME Fluid Auto Filler stop working with GregTech fluid cells.

It looks like this issue was fixed by commit https://github.com/GTNewHorizons/ThaumicTinkerer/commit/96ecc27389741209c845c586752c232642994e40. I don't see ThaumicTinkerer on [Jenkins](http://jenkins.usrv.de:8081/) so the problem might be in the build environment rather than the code.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by draknyte1** [comment]
Why bundle APIs?

Only real excuse is for RF support..
When you're building addons for mod X, you shouldn't bundle it knowing it will exist. Because if not your addon is pointless and you don't load.

**Comment by codewarrior0** [comment]
Yes, the AE2 API shouldn't be present in the TT mod jar at all. It looks like it was only there because the API folder was previously misplaced in the source tree, which is fixed by the commit linked above.

**Comment by bartimaeusnek** [comment]
Ye, my fix for #2764 has most apis deleted from source. Ill create a pull request once i fixed the gradlew.build

**Comment by Dream-Master** [comment]
What is different in Captains fork? The commit codewarrior post before? Is this included?

**Comment by bartimaeusnek** [comment]
@codewarrior0 https://github.com/GTNewHorizons/ThaumicTinkerer/pull/8
