### ISSUE TITLE
Suggestion: Nerf EV/IV Tier circuits in Robot Arms, Emitter, Sensors

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2777]
#### Which modpack version are you using?
2.0.3
The microcircuits for these components are too high: Robot Arm (EV, IV); Emitter (EV, IV); Sensor (EV; IV).
For EV components used circuitData, IV components used circuitElite. Here it is clear that for EV are required circuitElite, IV circuitMaster.
![2018-04-03_07 21 08](https://user-images.githubusercontent.com/35035276/38229121-d09f9fe2-370f-11e8-94aa-d7ca112e9765.png)
![2018-04-03_07 21 15](https://user-images.githubusercontent.com/35035276/38229122-d0cd0f86-370f-11e8-904c-f6a2e892be00.png)
![2018-04-03_07 21 29](https://user-images.githubusercontent.com/35035276/38229123-d0fa3a1a-370f-11e8-9475-004ac5dd8175.png)
![2018-04-03_07 21 34](https://user-images.githubusercontent.com/35035276/38229124-d124a7dc-370f-11e8-898b-f2d2df0bf804.png)
![2018-04-03_07 21 48](https://user-images.githubusercontent.com/35035276/38229125-d1515278-370f-11e8-927d-ee86f6ec4aca.png)
![2018-04-03_07 21 53](https://user-images.githubusercontent.com/35035276/38229126-d185af3c-370f-11e8-8dcb-2dddd96a1a5c.png)
![2018-04-03_07 33 05](https://user-images.githubusercontent.com/35035276/38229404-5c54af7c-3711-11e8-8c14-097d4688cd38.png)
![2018-04-03_07 33 12](https://user-images.githubusercontent.com/35035276/38229405-5c832a8c-3711-11e8-8395-0cf9007a7eae.png)
![2018-04-03_07 33 21](https://user-images.githubusercontent.com/35035276/38229406-5cb00c6e-3711-11e8-9774-759a1773976b.png)
![2018-04-03_07 33 26](https://user-images.githubusercontent.com/35035276/38229407-5ce06dc8-3711-11e8-9237-318de4bca080.png)
![2018-04-03_07 33 37](https://user-images.githubusercontent.com/35035276/38229408-5d10fbf0-3711-11e8-80e4-c7c322f6e160.png)
![2018-04-03_07 33 41](https://user-images.githubusercontent.com/35035276/38229409-5d3e5208-3711-11e8-940d-9147cdf13a5e.png)

**Comment by bartimaeusnek** [comment]
Since IV circuits are craftable in EV i don't see a problem here.

**Comment by Dream-Master** [comment]
I don't see the problem either

**Comment by CalterOK** [comment]
Overestimated microcircuits are observed only in these types. before and after this is not observed. And right away, when you move to a new shooting gallery, it's hard to do them.

**Comment by Dream-Master** [comment]
If I change ev/iv I change all. About the number of circuits in assline we can talk but I like to make recipes more expensive each code change 😁
