### ISSUE TITLE
[QoL]Recipebalance ~ Yellow Limonite

### ISSUE THREAD

**Issue by Raccoon2709** [GTNewHorizons/NewHorizons#2778]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
DirtHuts
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/10391092/38257263-32a1d21e-3760-11e8-831a-5ff9e1d99bc9.png)
![image](https://user-images.githubusercontent.com/10391092/38257295-4083b316-3760-11e8-9738-49853d13aa1d.png)
#
#### What do you suggest instead/what changes do you propose?

I would suggest to A: Nerf the smelting recipe to 1/4 Iron or B: To Buff the Centrifuge Recipe for 4 Iron Dust otherwise the recipes are not balanced in itself or C: Nerf the Gas Outputs to 0,25 and decrease Yellow Limonite to 1. (Same as Brown Limonite)

**Comment by Dream-Master** [comment]
i did before use the lower amount and i get a shitstorm of users change it back.

**Comment by Raccoon2709** [comment]
Oh okey, if the user's dont want it you can close it. My Issue is -> If you smelt Dust to Ingots its 1:1 and if you spend a bunch of resources (energy) you loose 3 Ingots. So my suggestion change the ingot 1:1 stuff or the centrifuge.

**Comment by richardhendricks** [comment]
No, it's intentional.  It's a choice - Do I need iron, or do I want oxygen/hydrogen?  As you tier up, you'll find ways to get infinite iron, and the oxygen and hydrogen become way more important.

**Comment by Raccoon2709** [comment]
Okay. Sad.

**Comment by WarlordWossman** [comment]
@Dream-Master the lower amount would just mean that I mine more of the same ore and limonite is not exactly hard to find. I think it's fair that higher tiers allow you to choose between more options of processing which means you can get stuff out of the ores you couldn't before.
