### ISSUE TITLE
[Recipe] Concrete from mixer not used in assembler recipe for BBF bricks?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2782]
Verify that concrete output from the mixer can be used to create BBF bricks in the assembler.  Need to tweak if not.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/38373612-da3a323e-391b-11e8-831a-841a89410110.png)
allready in

**Comment by Dream-Master** [comment]
@richardhendricks is this ok?

**Comment by richardhendricks** [comment]
Player was complaining about recipe taking 1152L, but a hand bucket only providing 1000L.  Not a bug.

**Comment by Dream-Master** [comment]
Ah ok can change it to 1000 if this is a problem

**Comment by Wolozo7** [comment]
Idk, that depends on how much wet concrete other recipies require. If most of them are multiples of 144, I'd vote to leave it as it is.

**Comment by Raccoon2709** [comment]
you need fermenter to make Concrete. Wet Concrete -> Construction Foam -> Concrete (Atleast in 2.0.7)

**Comment by Dream-Master** [comment]
Ok sure.
