### ISSUE TITLE
Singular staff 375 vis

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2785]
What is the purpose of this staff? The prescription is a scepter, but it can not be put in a magic workbench, and the knobs do not dress for it.
![2018-04-05_11 05 37](https://user-images.githubusercontent.com/35035276/38354313-dc91df00-38c1-11e8-8363-753334eb04fc.png)

**Comment by CalterOK** [comment]
I thought so, but you would have known it before you scrubbed it.

**Comment by bartimaeusnek** [comment]
We should add "Staffter" to the Thaumonomicons Staff page. I didnt knew this either.

**Comment by Dream-Master** [comment]
Isn't it better to add Quest for it ?

**Comment by CalterOK** [comment]
Quest for 375 vis is not the best option, because not all will be needed.

**Comment by Dream-Master** [comment]
I make example quest how you do staffter. I don't want to add more thaumcraft wand entry's on the page. Maybe I could add it to us GTNH thaumcraft page as plain text.

**Comment by CalterOK** [comment]
We have quests (273, 274)in which you can add hint information as text.

**Comment by Dream-Master** [comment]
Sure will take a look
