### ISSUE TITLE
GTNH 2.0.3.0 Problem NEI

### ISSUE THREAD

**Issue by Alvarin5728** [GTNewHorizons/NewHorizons#2789]
#### Which modpack version are you using?
2.0.3.0
#### What did you try to do, and what did you expect to happen?
I can't searching in NEI nothing
#
#### What happend instead? (Attach screenshots if needed)
When write anything in NEI search board(for example Oak or aluminium-nothing result.In NEI 208 pages(on my screen resolution).Search in NEI not working

**Comment by Dream-Master** [comment]
Never had this problem. It takes longer the first run you searching but after a few secs it will show you the item/blocks

**Comment by Alvarin5728** [comment]
I played on earlier version of new horizons and all be ok,but last version-problem with NEI...Game doesn't freeze or lag,i can see recipes and other things,but searching not for me
![image](https://user-images.githubusercontent.com/38118253/38400253-499fec9c-3960-11e8-93c4-3cfdde34fcfd.png)

**Comment by bartimaeusnek** [comment]
Please tell us the Specs of your System (RAM, "Memory" & CPU, "Processor") and the launcher you are using and try reinstalling GT-NH.

**Comment by Dream-Master** [comment]
@Alvarin5728 any news here ?

**Comment by Alvarin5728** [comment]
AMD A-10-5800K 3.8 Ghz 8Gb Ram 64 bit win 10....

After starting the client I wait about 3-4 minitues while NEI will start searching...game's not lagging,I can crafting and other things...but in 10-20 minitues is starts to slow again.Searching takes 3-5 minitues.I don't know how to play with it. On earlier versions of GTNH everything was working beatiful,Nei searchs  2-3 seconds. But in last version it's not

**Comment by bartimaeusnek** [comment]
hmm try allocating at least 4Gb (better 6Gb) Ram to GT-NH. Might fix it.

**Comment by Alvarin5728** [comment]
I allocated minimum 4 Gb always.and on F3 screen no problems with memory.I play with my friend,he also played this pack and has 32Gb Ram,but no result

**Comment by Dream-Master** [comment]
Limit view distance to 8 or 6 chuncks and lower details.

**Comment by Alvarin5728** [comment]
I played on 6 chuncks and the minimalist details)))

**Comment by Alvarin5728** [comment]
After a lot of tests i found the problem... I'm playing with Optifine mod,and with it NEI freezes very very much.Without Optifine searching takes 5-10 seconds...I'll try earlier versions of optifine,because i can't play without him(

**Comment by bartimaeusnek** [comment]
@Alvarin5728 use Optifine D6 and Fastcraft 1.23 for maximal performance.

**Comment by Alvarin5728** [comment]
I tried this version but no result.All versions of optifine make NEI freezes

**Comment by bartimaeusnek** [comment]
Why cant you play without OptiFine tho?

**Comment by Dream-Master** [comment]
With Fastcraft 1.23?

**Comment by Alvarin5728** [comment]
Yes

**Comment by richardhendricks** [comment]
Should we add something to the questbook?  Not sure what we can do here.

**Comment by ryankhart** [comment]
@Alvarin5728 I don't know if you solved your issue or not or quit but still have an interested in the pack, but I have a suggestion for you.

If you need to use Optifine with GTNH, just update Fastcraft from 1.23 to 1.25, and you should be able to use Optifine without issues.

Patch notes for Fastcraft 1.25 are here:

> Compatibility fixes towards Optifine - at the cost of disabling some features. Performance may be better with an Optifine version that doesn't include Shadersmod or without Optifine.

https://minecraft.curseforge.com/projects/fastcraft/files/2522249

**Comment by Dream-Master** [comment]
in the past fastcraft 1.2.5 runs so slow that i not update it. Maybe i give it a second try

**Comment by ryankhart** [comment]
Maybe, I haven't noticed an issue, but I'm still in the early game. NEI search takes about 2 seconds, but from what I've read about NEI on this pack, that seems normal anyway. It's probably a safe decision to let users decide whether to update fastcraft or not, so no complaints here.
