### ISSUE TITLE
Suggested default option in Forestry/common.cfg

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#2792]
# Allow bees, butterflies, and players to pollinate vanilla tree leaves. When disabled, vanilla trees must be analyzed before they can be pollinated. [default: true]
    B:pollinate.vanilla.trees=false

This should always be false on servers to save tps.

**Comment by bartimaeusnek** [comment]
how does this save performance? is forestry turning normal leaves into TEs?

**Comment by ProsperCraft** [comment]
This doesn't turn off pollination of forestry trees, it turns it off for vanilla trees, so they don't go through the whole world changing and interacting with blocks, only where you intend them to.

**Comment by Dream-Master** [comment]
mh ok then it is is maybe a good change.

**Comment by Wolozo7** [comment]
How do you get Forestry Trees if you can't pollinate Vanilla Trees?
