### ISSUE TITLE
Maceration stack doesn't grind all blocks fast

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/NewHorizons#2794]
Which modpack version are you using?
GTNH 2.0.3.0 single

The Maceration stack doesn't grind galaxyplanet block fast. Other blocks grinded fast (like ores and cobble).
By galaxyplanet blocks I mean e.g. venus surface block, mars sub surface block and so on. 
They get grinded one at a time. It should not be like that, when those blocks can be a source of materials, like meteoric iron and so on.

**Comment by Wolozo7** [comment]
Keep in mind that those recipes have different costs. Normal ores are 2 EU/t, while Venus Stone takes 256. Supplying more power to the Maceration Stack should fix your problem.

**Comment by madmacf** [comment]
Hmm that might be it. Doing it at HV level. Maybe close this one down then.
