### ISSUE TITLE
Large Chemical Reactor

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2796]
At the moment there is a quest that requires the creation of a chemical reactor EV (1242). He starts a chain of quests to get indium. In my opinion, it is not entirely advisable to require this reactor. Is not it better to direct a player to create a multi-unit chemical reactor? After all, it is much more convenient, to the same, he does not have additional energy costs when increasing the shooting range.
I suggest removing quest 1242 and adding a new one to the multi-block section, which will already open quests for indium.
It will take:
Large Chemical Reactor - 1;
PTFE Pipe Casing - 1;
Maintenance Hatch - 1;
Cupronickel Coil Block - 1;
Chemically Inert Machine Casing - 10;
EV Energy Hatch - 1;
Input Bus - 1;
Out Bus - 1;
Input Hatch - 5;
Output Hatch - 5.
The number Input/Output hatch is specified for all recipes.

**Comment by Dream-Master** [comment]
Sure add a LCR as Quest is a good idea. Will see what i can change here.
