### ISSUE TITLE
Zirconium nuggets to ignot in Alloy Smelter consumes ignot mold

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#2797]
#### Which modpack version are you using?
2.0.2.7 (windows via TechnicLauncher)
#

#### What did you try to do, and what did you expect to happen?
Place 9 Zirconium nuggets and ingot mold in alloy smelter, ingot is produced; nuggets AND mold are consumed.

#### What happend instead? (Attach screenshots if needed)
mold should not be consumed like all the other nugget to ingot recipies.

**Comment by codewarrior0** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/pull/249
