### ISSUE TITLE
[suggestion] Getting flint with machines early game.

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2799]
#### Which modpack version are you using?
2.0.2.7 but it's the same in 2.0.3.0

Let's talk about flint. I will list the available recipes first and talk about them.
Will also do some math at the end and look at what you would realistically want to do to get flint in steam age / LV.

![flint4](https://user-images.githubusercontent.com/16925725/38455867-2bfbbd1e-3a7e-11e8-8051-568bade53e95.PNG)
This one requires the HV macerator and is only a byproduct, not really worth mentioning if we want to talk about early game.

---

![flint1](https://user-images.githubusercontent.com/16925725/38455868-2c155706-3a7e-11e8-83f0-04596eeb69f0.PNG)
That's the go to recipe which is fine for steam age imo. It does however beat pretty much all the options that will appear for a while.

---

![flint2](https://user-images.githubusercontent.com/16925725/38455869-2c2e4fb8-3a7e-11e8-9e0b-58ddc2d37794.PNG)
Somewhat okay, even if it might be slower than just hand crafting. Problem is that it needs an EBF and other materials like polyethylene which makes it not really worth going for when flint is just a few mortars away. I don't think we need a change here but just wanted to point out that you would never go for a machine like that for the flint and even then it would open up too late in LV for my taste.

---

![flint3](https://user-images.githubusercontent.com/16925725/38455870-2c46516c-3a7e-11e8-9d1e-b9d8dddcaf05.PNG)
This here is the recipe that should be an alternative in LV and normally we do really want to encourage getting away from using meta tools at this time of the game. (plate bender and wiremill would be obv examples).
However it is really easy to see why you wouldn't make your flint this way, 40 seconds for a single piece!
Sure I can save 5 stone and 2 iron (for an iron mortar) by making a stack of flint in a sifter but let's look at the numbers: 64 * 40s = 2560 second; that is 42,66 minutes for a single stack. I think everyone would much rather just sacrifice some mortars or even triple the gravel just to make flint instantly.

---

So what could we change?
The sifter clearly is a machine with a theme to it, most recipes are 40 seconds, the tin ones are 30 seconds. However gravel is the only full block you can put in there anyways so I wouldn't say it has to match either of these time values BUT also shouldn't be extremely fast.
I think 20 seconds would be a better value. 
That said 20 seconds would still have nobody ever using it to make flint, so my idea here is to give multiple flint outputs per gravel block. We are talking about around 3 to 4 pieces everage per block tho, maybe with a maximum of 6 possible pieces per block. That would also kinda fit the sifter since it outputs multiple things based on chances in its other recipes. We just have to make sure that the average number per block is high enough to give around 1 flint per 5 seconds at least, otherwise the time you have to wait will always make hand crafting the better option.

Suggestion: 
flint [100%] flint [90%] flint [75%]
flint [50%]   flint [25%] flint [15%]
On average 3,55 flint per gravel taking 20 seconds. that does sound acceptable to me and should be an alternative to just making it by hand.

(Note: While this recipe would mean a lot of flint per gravel block, keep in mind that gravel is endless and really easy to get by hammering cobblestone which you pretty much have at all time since you are mining for ores. So the ratio shouldn't be an issue at all)

**Comment by bartimaeusnek** [comment]
+1 for this, but i would suggest make it taking 25 or 30seconds.

**Comment by WarlordWossman** [comment]
@bartimaeusnek let's go with 30 seconds then, since 30 second recipes already exist in the sifter.
You might want to make the flint ratio a tiny bit higher than in my suggestion.
