### ISSUE TITLE
[recipe] oredicted recipe to make wooden pressure plates overlaps with the GT plank covers that are not oak

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2801]
#### Which modpack version are you using?
2.0.2.7 but it's the same in 2.0.3.0

#### What did you try to do, and what did you expect to happen?
I was looking at making the GT plank covers, we have spruce trees planted but knowing this recipe I assumed the same would work for spruce:
![plank3](https://user-images.githubusercontent.com/16925725/38456734-50eb4ea0-3a88-11e8-81ad-17b888b0a685.PNG)

#### What happend instead? (Attach screenshots if needed)
Turns out that for wood types other than oak wood, the cutting machine has 2 overlapping recipes for things that you can make from wooden slabs (notice the 6 pages) (oak slabs can only be made into pressure plates and not into the oak GT plank covers)
![plank2](https://user-images.githubusercontent.com/16925725/38456818-0396145e-3a89-11e8-9fb9-4da4446e27be.PNG)
![plank1](https://user-images.githubusercontent.com/16925725/38456819-03aee95c-3a89-11e8-8165-3fd6f7d98c68.PNG)
This probably happened because the recipe to make wooden pressure plates is oredicted to use any type of wooden slab.
When I put the spruce slabs in the cutting saw it gave me the GT spruce covers tho, not the pressure plates.

On a side note the shaped recipes are also somewhat inconsistent but not overlapping like the ones in the cutting saw:
![plank6](https://user-images.githubusercontent.com/16925725/38456854-52f5a8ac-3a89-11e8-8d47-b2383dbc732b.PNG)
![plank5](https://user-images.githubusercontent.com/16925725/38456855-530e8980-3a89-11e8-8549-5b454498d8df.PNG)

All GT plank covers that are NOT oak are effected by the overlapping cutting saw recipes and the inconsistent way to craft them shapeless!

#### What do you suggest instead/what changes do you propose?
Not entirely sure here, maybe you can only get non-oak type GT plank covers by making them shapeless and the cutting saw can only saw pressure plates into oak covers (?)
That way you could make oak covers from all wood types but that might not be a bad thing given that for example piston heads can only be made with the oak GT plank covers.

**Comment by bartimaeusnek** [comment]
this will be fun to code. Lets see what stuff is already oredicted...

**Comment by Dream-Master** [comment]
Why oredicting? I vote for only oak wood produce pressure plates in cutting machine.

**Comment by WarlordWossman** [comment]
That would in turn mean that you need to use oak wood if you want to make the oak GT plank covers, which are used for quite some recipes.
Maybe it would work like that if you could use every wooden GT plank cover in recipes like piston plates, signs and so on.

**Comment by Dream-Master** [comment]
not working fully.

**Comment by Dream-Master** [comment]
@Ethryan more realistic ofcurse.
