### ISSUE TITLE
Buff certain IC2 crops

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#2802]
#### Which modpack version are you using? 2.0.3.0

#
#### If in multiplayer; On which server does this happen? Sp

#
#### What did you try to do, and what did you expect to happen?
Infinite resources with ic2 crops
#
#### What happend instead? (Attach screenshots if needed)
Right now, IC2 crops for higher-tier materials require uu-matter and a long autoclave recipe to actually get resources ex nihilio. While they can dupe ores an additional 4x which is useful, when it comes to infinite resource generation they are super weak compared to bees. Bees require no uu-matter and relatively easy centrifuge recipes (except like naquadria and stuff).
#
#### What do you suggest instead/what changes do you propose?
Reduce the time and uu required, and maybe eliminate uu as a requirement for the lower tier crops like nickel and copper.

**Comment by sthegreat** [comment]
Another small issue is that the simpler "alternative" crops like cyprium and plumbiscus(?) (which just give tiny piles) and oreberries give a better yield than the "greggier" crops that need autoclave+uu just to get copper. Imo the more complex ones should be more powerful.

**Comment by codewarrior0** [comment]
Aren't bees supposed to have those same kind of centrifuge/chemical bath recipes as the crops do?

**Comment by codewarrior0** [comment]
Oh, I see, the GT bees themselves aren't even enabled, so those combs with the "hard" recipes don't exist. GT doesn't do anything special about the combs from Gendustry and ExtraBees.

**Comment by Dream-Master** [comment]
Some time I will totally rework it and disable gendustry config bees and enable gt bees. The uu matter recipes I will rework too.

**Comment by Dream-Master** [comment]
@bartimausnek not change the crops I change the bees better.

**Comment by Cinobi** [comment]
Heey, bees is fine. Don't make it as useless as crops.

**Comment by Dream-Master** [comment]
Bees goes back to gt code some day.

**Comment by 0lafe** [comment]
some bee's are fairly useless, mostly the metal ones. They don't really produce enough for them to be too viable, unless you set aside an amount of infrastructure that isn't practical compared to quarrying. The other bees are mostly fair, like the egg ones and glowstone. With 1A LuV and 4 max industrial apiaries, I can almost keep up with a single ZPM disassembler. 

I'm not sure if I've found an OP bee yet, except maybe the certus one. That can fill up drawers and drawers of the stuff way faster than I can use it. Fluix too.

**Comment by mitchej123** [comment]
I think a lot of this has been addressed, especially with crops++.  Reopen & provide details if still relevant.
