### ISSUE TITLE
Assembly machine recipe for Conveyer cant use alternative rubber sheets.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#2804]
#### Which modpack version are you using?
2.0.2.7 (Windows Technic)

#
#### What did you try to do, and what did you expect to happen?
Recipe for conveyer belts in Assembly machine require rubber sheets. If making by hand can also use alternative rubbers (e.g. silicon rubber). 

There is a recipe to make them for all rubber types in the Component Assembler machine, but this a machine you can't make.

**Comment by Dream-Master** [comment]
I guess i add it in 2.0.3.0 allready. Will check.

**Comment by drayath** [comment]
If already fixed my apologizes, thinking about it i may not have re-tried since trying to setup the production line a short while ago.
