### ISSUE TITLE
Pressure plates provide too much burn value

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#2805]
#### Which modpack version are you using?
2.0.2.7 (Windows Technic)

#
#### What did you try to do, and what did you expect to happen?

Wood->Pressure plate via cutting machines seems to provide an excessive amount of burn value.

1 Wood: 300
6 planks: 6x300 = 1800   (already as good as charcoal)
12 slabs: 12x150 = 1800

24 covers: 24x75 = 1800
OR
24 pressure plates: 24x300 = 7200

#
#### What do you suggest instead/what changes do you propose?

Reduce burn value to 75 like covers or massively up the production time (present 0.8 seconds at LV for 2 pressure plates)

**Comment by Dream-Master** [comment]
Sadly minetweaker scripts not working so we need a coding solution.

**Comment by bartimaeusnek** [comment]
Since the Burn Valure of Pressure Plates is hardcoded in net.minecraft.tileentity.TileEntityFurnace.class getItemBurnTime(ItemStack par1) we would need to use ASM to replace that method. @draknyte1 @richardhendricks @codewarrior0 @mitchej123 any idea here?

**Comment by Dream-Master** [comment]
Maybe for vanilla plate but nature are more easy I guess.

**Comment by codewarrior0** [comment]
A few lines up you see `net.minecraftforge.event.ForgeEventFactory.getFuelBurnTime(p_145952_0_)` so all you would have to do is handle the `FuelBurnTimeEvent` event to change the burn time. I'm surprised if Minetweaker doesn't already do that.

**Comment by Dream-Master** [comment]
If I set it to 0 it was removed and if I set it now to 75 it shows 75 but it need a reload. I restart the game with 75 burn value in script and it shows 300. I not tested if it is a display value only but I guess it not working.

**Comment by drayath** [comment]
If change the burn value is really awkward, if changing the recipe duration is any easier upping that so say 40 sec would stop it being an **effective** way to fuel your furnaces significant impact on anything else.

**Comment by codewarrior0** [comment]
Fixed and tested. Changed burn time via Minetweaker, display value is 75 after restarting game and item only burns in a furnace for about four seconds.

![image](https://user-images.githubusercontent.com/307683/38489458-2aa59872-3b82-11e8-9f44-7513fe2e5c5d.png)

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/26

Doesn't include any actual fuel value changes, you'll have to put those in yourself!
