### ISSUE TITLE
Missing Recipe for Neutronium Sword Blade(GT)

### ISSUE THREAD

**Issue by Takafate** [GTNewHorizons/NewHorizons#2807]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
I tried to craft Neutronium Sword Blade from Gregtech, which is required for Sword of the Cosmos.
![2018-04-08_20 58 06](https://user-images.githubusercontent.com/12082829/38479977-56619df8-3bf5-11e8-99c8-d784950e9aa9.png)

#
#### What happend instead? (Attach screenshots if needed)
The sword blade has no recipe showed in NEI. I also tried putting neutronium ingot and sword blade shape in extruder, that did not work.
#
#### What do you suggest instead/what changes do you propose?
Please add a recipe for the sword blade or replace the the sword blade with neutronium sword blade from Tic.

**Comment by Ethryan** [comment]
oops, my bad i added the sword before all gt swords were removed, my suggestion is to replace it with an infinity plate to fix it.

**Comment by bartimaeusnek** [comment]
@Dream-Master would be easier to use neutronium cleaver blade instead of putting the GT neutronium swordblade back in...

**Comment by Dream-Master** [comment]
Yea Good idea.
