### ISSUE TITLE
New ProjectRed chips

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#281]
Recipes for the crafting/extension pipe have to be removed as those pipes are deprecated, and recipes for the new crafting/extension chips to be nerfed.

Source:
[v4.7.0pre6](https://github.com/MrTJP/ProjectRed/blob/d1bb73f315e12e9f1d95e7ca94033ee8c95590a4/resources/Changelog)
- ADDED: Crafting Extension chip
- REMOVED: Routed Crafting pipe
- REMOVED: Routed Extension pipe
- CHANGE: Moved crafting logic from crafting pipe to chip
- CHANGE: Crafting chip can now be installed in any Interface pipe
- *REMOVED: Routing chip upgrade system*

You may remove the router utility/upgrade recipes as well, as they are changed/removed it seems.

[v4.7.0pre7](https://github.com/MrTJP/ProjectRed/blob/d1bb73f315e12e9f1d95e7ca94033ee8c95590a4/resources/Changelog)
- ADDED: Project Bench
- ADDED: Auto Crafting Bench

Project Bench is a nice upgrade for the crafting station while the worktable is not available.
Didn't play with the auto crafting bench, but looks like it needs power to operate.

**Comment by Dream-Master** [comment]
Wiil look inside this.

**Comment by Dream-Master** [comment]
Done
