### ISSUE TITLE
[config] entity cramming makes animal farms useless early game

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2812]
#### Which modpack version are you using?
2.0.2.7 but it's the same in 2.0.3.0

With GT entities in the world take damage if there is 3+ in the same block which is supposed to be realistic. Sadly the animal AI doesn't know that and they keep walking into each other esp. the baby animals with their small hitbox which usually makes them die really fast (less health than adults).
We had a 7 by 7 grass area for cows and after some time there were only 3 left (happened multiple times). Keeping the range of the feeder and vacuum hoppers in mind that's a bit much imo. We just ended up killing animals flying around in the world.
Even bigger spaces for animals can have them die super easily if you want to feed them which is not realistic at all, rarely seen some animals trample each other over some wheat.

My suggestion would be to change the config for mobs/animals taking damage from 3 to 6. Given the fact that you don't have many low tech options that should already help a lot.

**Comment by richardhendricks** [comment]
Seems like they glitch into fence corners and can escape on restarts too.

**Comment by WarlordWossman** [comment]
Never using fences since they can always glitch into them but even with full blocks they die like flies :D

**Comment by Dream-Master** [comment]
I close this after update.

**Comment by richardhendricks** [comment]
One other problem,MC random pathing in 1.7.10 tends to the NW anyways (causes the butterfly bug), so this helps but might still be a problem if you have many animals.  Suggestion would be to split up your animals into smaller groups =<6 or maybe add lots of corners inside your pens so that they naturally get caught there.
