### ISSUE TITLE
GT++ fluorite ore

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#2815]
#### Which modpack version are you using?
2.0.3
#
#### What do you suggest instead/what changes do you propose?
You can make gt++ fluorite ore from limestone which is made with lime dye and some stone. Normally fluorine is a difficult resource to get, and not nearly this automatable/cheap. The ore from limestone should probably be disabled, or have the limestone spawn naturally or something.

**Comment by bartimaeusnek** [comment]
Fluorite also drops from mined sandstone, which can be easily automated...

**Comment by 0lafe** [comment]
if there's a way to just remove all the gt++ fluorite ore stuff without messing anything up, that would probably be best. Or maybe just remove the recipe that turns it into fluorine in the electrolyzer

**Comment by Dream-Master** [comment]
@draknyte1

**Comment by draknyte1** [comment]
Lime dye + stone is oredicted wrong and that's not intended to drop Fluorite. So someone might want to fix that?

The drop rate reflects mining naturally spawned sandstone and limestone and people using block breakers, well I can't stop them. 

If the rate is too common, reduce it via config.

**Comment by Dream-Master** [comment]
Ok will check
