### ISSUE TITLE
Piston assembler recipe

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#282]
Good recipe, just please switch the fluid in the Piston block recipe (2594) from red alloy into redstone

**Comment by Drobac** [comment]
No other assembler recipe uses molten red alloy which in itself is a pain to make, and we already have a lot of assembler recipe which use redstone so it is much more automation friendly

**Comment by Dream-Master** [comment]
Ok.

**Comment by Dream-Master** [comment]
@Drobac 
The craftable Piston Recipes using a red alloy plate so i add this to molten or you want i add the steel as molten under the red alloy plate back?

**Comment by Dream-Master** [comment]
Make a alternative Recipes with molten iron.

**Comment by Drobac** [comment]
This still has the same issue as when i started it, i wanted the recipe to have a liquid that is already being used in other recipes (redstone is being used in bunch of them) just so you don't have to have an additional set of machines (for automation) just to make one part of a block.

**Comment by Dream-Master** [comment]
Than i have to rewrite the recipes to be Redstone Plate and molten redstone.

**Comment by Dream-Master** [comment]
````````````````````````````````````````````
// --- Piston Block
AssemblerLiq.addRecipe(<dreamcraft:tile.PistonBlock>, <minecraft:cobblestone>, <gregtech:gt.metaitem.02:20032>, <liquid:molten.redstone> * 72, 100, 32);
// -
AssemblerLiq.addRecipe(<dreamcraft:tile.PistonBlock>, <minecraft:cobblestone>, <gregtech:gt.metaitem.02:20304>, <liquid:molten.redstone> * 72, 100, 32);
``````````````````````````````````````

**Comment by Dream-Master** [comment]
Done
