### ISSUE TITLE
More Bees

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2822]
#### Which modpack version are you using?
2.0.3.0
#
#### What do you suggest instead/what changes do you propose?
I think more bees would be cool (everybody loves bees).
So I made a list with some bees that might be useful: https://goo.gl/c3PUV8

**Comment by bartimaeusnek** [comment]
Certificate Bee 🥇... srsrly? I made this damn thing purely as a joke, also ^ this.

**Comment by Dream-Master** [comment]
Merging bees into gt code mean not to add new bees available. I am open for new bees but if they produce high end stuff they need to be hard to breed and the output need to balnced too.

**Comment by 0lafe** [comment]
The crop ones look a little underpowered. Bees are mostly OP when it comes to things like eggs and certus. The higher tier gt stuff like platinum, iridium, naquadah, naquadria and the like are better gotten from mining. It's like a single quarry vs. 64 industrial apiaries with a ton of power dedicated to accelerating them. 

My 16max trait boosted alveary tin bees get about 2k dust a day, quarrying the bedrock dim I can get up to 20k a day iirc.
