### ISSUE TITLE
Kinetic Generator Recipe Rebalance

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2825]
Kinetic Generators are way too powerful in 2.0.2.7/2,0,3,0. I don't think there is much to discuss about the Why, they need to have their recipes changed to not be the by far strongest available energy source from EV to ZPM in terms of effort to set up and maintenance cost.

I chose to stick to one layout for the recipes. Debated whether switching to 7x7 for IV+ would be good, but it looked kinda meh.

Recipe suggestions:

HV Tier
![image](https://user-images.githubusercontent.com/34921674/38738791-51fe4978-3f33-11e8-8e90-783b4d2ea9b5.png)
12 Triple Stainless Steel Plates, 1 Shaft (Steel), 2 Titanium Gear, 1 Compressed Graphite, 3 1xPlatinum Cable (to force the use of the higher tier rubbers), 2 IV Circuits, 1 Motor Machine Casing, 2 HV Motors, 1 Large Lithium Battery

EV Tier
![image](https://user-images.githubusercontent.com/34921674/38737056-46d30142-3f2e-11e8-8a58-8f379938d260.png)
12 Triple Tungstensteel Plate, 1 Energetic Alloy Shaft (not in Picture), 2 Desh Gear, 1 Block of Lanthanum, 3 1x Tungsten Cable, 2 LuV CIrcuits, 1 Kinetic Generator, 2 EV Motor, 1 Small Sunnarium Battery

IV Tier
![image](https://user-images.githubusercontent.com/34921674/38737601-04887644-3f30-11e8-92a4-7ef3db1f53c1.png)
12 Triple Iridium Plate, 1 Vibrant Alloy Shaft, 2 Oriharukon Gear, 1 PTFE Pipe Casing, 3 1xGraphene Wire, 2 ZPM Circuits, 1 Low Kinetic Generator, 2 IV Motor, 1 Medium Sunnarium Battery

LuV Tier
![image](https://user-images.githubusercontent.com/34921674/38737908-084189be-3f31-11e8-929a-491f67f023de.png)
12 Triple Osmiridium Plate, 1 Tungstensteel Shaft (not in picture), 2 Draconium Gear, 1 Block of Tungsten, 3 1xVanadium-Gallium Cable, 2 UV Circuits, 1 Medium Kinetic Generator, 2 LuV Motors, 1 Large Sunnarium Battery

(I don't know enough about high tier materials...)
ZPM Tier
![image](https://user-images.githubusercontent.com/34921674/38738360-4dfd928a-3f32-11e8-9828-cf4e74f81851.png)
12 Triple Neutronium Plate, 1 Iridium Shaft, 2 Fluxed Electrum Gear, 3 1xNaquadah Cable, 2 UHV Circuit, 1 High Kinetic Generator, 2 ZPM Motors, 1 Medium Naquadah Battery

**Comment by 0lafe** [comment]
IV on can make it easily in that tier, but maybe that's kind of the point. Solars work a similar way. I like the recipes, except the shafts are a little weird. Vibrant at IV is quite cheap, and iridium at LuV+ too. Not sure if there's one past iridium though.

**Comment by bartimaeusnek** [comment]
i think we should not use tier+2 circuits here... maybe tier+1 circuits...

**Comment by Wolozo7** [comment]
Yo, this stuff completely breaks energy progression from EV all the way up to UV, why is it not in 2.4?

**Comment by Dream-Master** [comment]
because this will be in 2.0.4.1 next week

**Comment by mergendil** [comment]
I suggest gating the LuV one behind fusion with europium. Not sure about the zpm one
