### ISSUE TITLE
Iron III Chloride Coin Quest Wrong Cell Requirement

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2826]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Do the Iron 3 Chloride coin quest because I'm lazy.
#
#### What happend instead? (Attach screenshots if needed)
The coin quest requires 64 Empty Cells, and gives Iron III Chloride in Universal Fluid Cells.  Once you use it up, you've essentially transformed your empty cells into UFCells.  And they can't be converted back.
#
#### What do you suggest instead/what changes do you propose?
This particular coin quest should require 64 Universal Fluid Cells instead of Empty Cells.

**Comment by Dream-Master** [comment]
Yea ok will change it.

**Comment by Dream-Master** [comment]
Or maybe exchange recipes

**Comment by eloquentJane** [comment]
A shapeless recipe to swap between them would perhaps be the best thing to do, since they both serve essentially the same purpose (storing 1 bucket of fluid in stackable item form).
