### ISSUE TITLE
Suggestion: Remove ingot smelting to nugget mechanic

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2829]
#### Which modpack version are you using?
2.0.3.0
#
The process of smelting an ingot to get 9 nuggets makes no sense to me, as smelting something should form something together, not separate it into smaller pieces...
![image](https://user-images.githubusercontent.com/30087707/38771608-63188022-4026-11e8-991c-28d810467781.png)

The Alloy smelter, Fluid solidifier, and Casting table however makes perfect sense due to smelting the metal into a mold or cast
![image](https://user-images.githubusercontent.com/30087707/38771598-41806614-4026-11e8-8aae-b7d17b4a94e5.png)

I would suggest that the mechanic of
- getting nuggets through basic ingot smelting is removed
- crafting nuggets using a saw (or maybe hammer) with the ingot in the crafting grid is added (maybe even nerf output to 8 nuggets)
![image](https://user-images.githubusercontent.com/30087707/38771690-ca690caa-4027-11e8-9676-b6d4c8cae273.png)

This will of course affect early gameplay for steel, but it will not hinder it.
Later when you need need vibrant/pulsating/hhs-e/hhs-g nugget you would have to set up e.g. the Alloy smelter to craft these.

**Comment by WarlordWossman** [comment]
Not a big fan of this suggestion, there is crushed ores that smelt into nuggets as well.
And making wrought iron before you got steel will be painfull with the saw, we recently changed the high pressure machines to use more wrought iron and if you gate easy nuggets to the mold (4 steel) that change pretty much loses its effect.

Just don't really see any point to this, nuggets are annoying enough as of now.
(And if you wanna encourage using the nugget mold the alloy smelter recipe should be made quicker rather than changing the furnace recipe to a saw one that barely anybody would use)

**Comment by Dream-Master** [comment]
@DualBallers Ok it not make sense and for my taste the furnace shouldn't have to process any metal but the form has a steel recipe as @WarlordWossman said and this is the point.

**Comment by bartimaeusnek** [comment]
Hmm hardnened clay nugget mold that needs to be replaced after a few (10-50) uses?

**Comment by WarlordWossman** [comment]
That would be a solution, I think it would make sense if the durability would be n multiples of 9 tho :D

**Comment by DualBallers** [comment]
@WarlordWossman I think it actually does make sense that smelting crushed ores gives the (annoying) nugget output, as crushed ore is the intermediate state between ore block and dust. 

@bartimaeusnek I like the idea of using some sort of mold in the crafting table for this, but hardened clay is weaker than a formed iron ingot.
That was why I suggested using a saw or hammer, to more realistically split up the ingot into the smaller nugget pieces. 

Could you restrict iron nuggets to only come from the TC Smeltery?

**Comment by Dream-Master** [comment]
Clay form is not needed.

**Comment by DualBallers** [comment]
Hi @bartimaeusnek. I looked at the merge, and it looks like this change applies to all ingot types?
Doesn't that completely obsolete the alloy smelter and fluid solidifier nugget recipes?

Why not either 
- only have this crafting apply to wrought iron and iron, and/or
- nerf crafting output to 8 nuggets, so you want to automate it later

**Comment by bartimaeusnek** [comment]
@DualBallers You still need to craft saws which cost materials so the alloy smelter and fluid solidifier are cheaper. Anyways there are atm more important nerfs/bugfixes, ill keep this as a lowprio / reminder open.
