### ISSUE TITLE
2015/07/28 Test server notes

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#283]
Some blocks (like dirt) on the test server have a "scrambled" warp style tool tip. Whatever it is, it's from the core mod methinks.
(Noted here for reference)

The test server is not synced with the client test pack at the time of writing. (I had to downgrade a version)

I understand it's the *test* server, but please backup or otherwise save the flat_world multiverse dimension when syncing between servers. I came up with some contraption I'd like to refer to when needed.
Check out the 16bit memory IC gate for example, in the IC Worktable.

**Comment by Dream-Master** [comment]
Ok the scrambled Dirt Message is from the Core mod. i will disabled it.

I will save the world if i updating the test server.

**Comment by Teteros** [comment]
Thanks. Just to note, please don't think twice about removing the worlds/data in the test server.
That's what it is, a TEST server

Though I appreciate any efforts to save it, as I like the layout for testing/building stuff going on in the flat_world dimension.

**Comment by Dream-Master** [comment]
Ok see the folder Flat world on the Server and will backup it. But the Overworld i take from the live Server.
