### ISSUE TITLE
Just list of things that annoys me alot - tier 1

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2831]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Life epsi server
#
#### What did you try to do, and what did you expect to happen?

1. U can't use new rubber types like silicon rubber and styrene budatiene rubber with crafts that involve basic rubber(dolly, glass phials and  so on - please, check all recipes with basic rubber and add analogs)
2. When u fight witchery boss "Leonardo" it may crash the server(we killed epsi 3 times this way)
3.  Archimage orb from bloodmagic can unbound itself sometimes.
4. Electromagic tools armor and tools can't be enchanted - this make them pretty useless.
5. Bound armor(blood magic) can't be soulbound (just not cool)
6. Molds for fluid solidifer can be made at tinker smeltery only. WHYYYYYYY~
Please, add some advanced recipe.
7. Killing Chaos dracon don't count at quest #607 (slay the dragon. again)
8. Personal voids have no hostile mob-spawning. Not good. Nami knows about this, but why not to add it here ;P
10. Ultimate lappack can't be crafted - Please, recheck all recipes with IC2 energy items(crystals, lapatronic orbs, all batpacks, so on)

Somethin of this might be fixed and new version, but seriosly, no heavy testing can be made without alot of playing so update the off servers please ;D

**Comment by bartimaeusnek** [comment]
4. -> They just extend regular IC2 Items, i might be able to change that.
9. -> fixed as far as i remember, will check.

**Comment by Namikon** [comment]
Yes, I'm aware of the "No hostile mobs" problem in voids. Until someone has a really fancy way of debugging mob-spawn, this problem will remain unfixed.

**Comment by draknyte1** [comment]
Define 'really fancy way', in some detail, via a pm. Ill see what we can do.

**Comment by Dream-Master** [comment]
6. -> so far I remember if you did the form once you can duplicate it at mv but I could add a high tier recipes for the forms as well.

**Comment by WarlordWossman** [comment]
HV laser engraver? Wonder if there would be enough lenses :D

**Comment by richardhendricks** [comment]
Fluid solidifier with a casting form + 576 steel makes the most sense to me.

**Comment by Dream-Master** [comment]
Yea maybe better

**Comment by WarlordWossman** [comment]
> Fluid solidifier with a casting form + 576 steel makes the most sense to me.

Should then also add aluminum brass ingot in the MV extruder with plate shape -> blank cast; and a way to get aluminum brass. Otherwise it doesn't really need no smeltery.

**Comment by codewarrior0** [comment]
Can't the blank casts also be made from Gold or regular zinc/copper Brass?

**Comment by Dream-Master** [comment]
1. Fixed

**Comment by Dream-Master** [comment]
2. i cant fix need help

**Comment by Dream-Master** [comment]
3. 4. 5. i cant fix need help

**Comment by Dream-Master** [comment]
9. fixed

**Comment by Dream-Master** [comment]
8. i cant fix need help
7. probaly fixed now

**Comment by Dream-Master** [comment]
6. will do later
