### ISSUE TITLE
High Tier Solar Panel Recipe Swap

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2832]
Modpack version: 2.0.3.0

The "Singular Solar Panel" from Super Solar Panels generates 32768eu/t, but only requires an insane-voltage panel and machine hull to create. By contrast, the "Spectral Solar Panel" from the same mod requires ludicrous-voltage components but only generates 8192eu/t. Presumably either the power generation values or the recipes are supposed to be the other way around.

**Comment by Dream-Master** [comment]
Yea maybe I make a mistake here.

**Comment by 0lafe** [comment]
Those should probably just be solar + solder + hull and stay at the tier, right?

**Comment by Dream-Master** [comment]
yes.
