### ISSUE TITLE
printing books: seismic, asslinerec.

### ISSUE THREAD

**Issue by NNM42** [GTNewHorizons/NewHorizons#2833]
#### Which modpack version are you using?
test lab from gregtech-5.09.32.20.
#
#### If in multiplayer; On which server does this happen? 
mp only. 
#
#### What did you try to do, and what did you expect to happen?
item or material name
#
#### What happend instead? (Attach screenshots if needed)
![2018-04-15_14 07 18](https://user-images.githubusercontent.com/30381383/38775879-648f0052-40b7-11e8-9c27-66f6bf763964.png)
![2018-04-15_14 07 52](https://user-images.githubusercontent.com/30381383/38775880-64b3e8ea-40b7-11e8-8af1-663b2b73a9cd.png)
![2018-04-15_14 08 39](https://user-images.githubusercontent.com/30381383/38775881-64d4bdb8-40b7-11e8-829f-9b665239ef49.png)
![2018-04-15_14 08 43](https://user-images.githubusercontent.com/30381383/38775882-65076e5c-40b7-11e8-9b3e-0d9ce32ce74a.png)
![2018-04-15_14 08 45](https://user-images.githubusercontent.com/30381383/38775883-652c8aac-40b7-11e8-9b32-3705e38f2696.png)
![2018-04-15_14 08 47](https://user-images.githubusercontent.com/30381383/38775884-6550b26a-40b7-11e8-9e3b-f75dbca6d8e5.png)
![2018-04-15_14 08 48](https://user-images.githubusercontent.com/30381383/38775885-6572704e-40b7-11e8-8143-a71958ad787c.png)
![2018-04-15_14 08 50](https://user-images.githubusercontent.com/30381383/38775886-6594bf14-40b7-11e8-88af-63e99b7fb0a6.png)
![2018-04-15_14 08 53](https://user-images.githubusercontent.com/30381383/38775887-65d49d5a-40b7-11e8-91ce-ce5bfd21a8de.png)
![2018-04-15_14 08 55](https://user-images.githubusercontent.com/30381383/38775888-65f793aa-40b7-11e8-82c6-f01703e261c7.png)
![2018-04-15_14 08 56](https://user-images.githubusercontent.com/30381383/38775889-661b9e94-40b7-11e8-94d8-9d0e09109b24.png)
---
maybe proplems on this: https://github.com/Blood-Asp/GT5-Unofficial/pull/1251

If take this book on SinglePlayer - it's ok.

**Comment by Dream-Master** [comment]
@technus this main branch commit @NNM42  mention fix the problem?

**Comment by NNM42** [comment]
@Dream-Master 
I was hearing that this fixed. Today download last jar from jenkins and was testing.

**Comment by Dream-Master** [comment]
In sp it was fixed lo g time ago but mp not working at all.

**Comment by NNM42** [comment]
ok. thx.

**Comment by Prewf** [comment]
i think @Technus mentioned in github channel the other day that he's made a special block that will essentially act as a "datastick reader" to get around this issue
