### ISSUE TITLE
Life infuser from Blood arsenal...

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2834]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
... can be used to create almost everythin from GT.

This machine is designed to repair items, and can repair almost everything using LP. But, this repair works realy idiotical way - it just cycle from numbers after : in item ID.
10:10 -> 10:9 -> 10:8 -> ... 10:0

All GT items made by this postnumbers, so just insert any greg item into it and it will change to any item with lower postnumbers... with some time.
![2018-04-15_17 30 48](https://user-images.githubusercontent.com/25028786/38779590-3f589048-40d3-11e8-97be-ccc8aa6c75b4.png)
![2018-04-15_17 30 41](https://user-images.githubusercontent.com/25028786/38779591-3f79f288-40d3-11e8-85ef-0e8fc06e2604.png)
![2018-04-15_17 30 42](https://user-images.githubusercontent.com/25028786/38779592-3fac78b6-40d3-11e8-9b3a-867ee4168f53.png)
![2018-04-15_17 30 43](https://user-images.githubusercontent.com/25028786/38779593-3fcea2ba-40d3-11e8-8de7-53de663dbf56.png)
![2018-04-15_17 30 43_2](https://user-images.githubusercontent.com/25028786/38779594-3ff00f40-40d3-11e8-87a4-f020e5537275.png)
![2018-04-15_17 30 44](https://user-images.githubusercontent.com/25028786/38779595-4014b296-40d3-11e8-8879-34335409e48b.png)
![2018-04-15_17 47 56](https://user-images.githubusercontent.com/25028786/38779743-31ce8a5c-40d5-11e8-9409-40cb9597aa6e.png)

**Comment by draknyte1** [comment]
So.. Time to get that extra warp for BM..

**Comment by Dream-Master** [comment]
Maybe infuser to cheap. Blood magic is open source and we forked it allready.

**Comment by repo-alt** [comment]
Should be renamed to Ultimate Transmutation Machine

**Comment by Ethryan** [comment]
Should be changed to require endgame infinity materials. + the one above.

**Comment by Dream-Master** [comment]
Maybe gt items need to be take off with a blacklist. For now i change recipe.

**Comment by repo-alt** [comment]
Isn't it required to charge BM armor?

**Comment by Dream-Master** [comment]
will check
