### ISSUE TITLE
Suggestion: 10 Coke Oven Quest Require ULV

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2835]
Modpack version: 2.0.3.0

The multiblock quest for making and automating 10 coke ovens (quest ID: 699) requires LV conveyors and pumps. I propose that these LV components be replaced by their ULV equivalents, since the 1 stack per 80 seconds and 160mb/s transfer rates of the ULV components are still more than enough for ordinary coke ovens. This change would serve to somewhat cheapen the coke oven automation while also adding another reason to find lead early on (besides batteries).

**Comment by bartimaeusnek** [comment]
The quest was added before ULV parts were in the game, so LV were the cheapest ones back then. guess that needs an update.

**Comment by eloquentJane** [comment]
The only potential issue I can see with using the ULV parts instead is that it would gate that quest behind the Twilight Forest. Although that's something that I assume most people do before automating coke ovens.

**Comment by WarlordWossman** [comment]
Since circuits got touched I thought the portal generator could be something else than circuits (they are not really magic related anyways). That could help making it a bit cheaper at least even if it's still in the assembler.

Was thinking hand crafting but maybe use some gold foil so it technically is LV but really early.

**Comment by bartimaeusnek** [comment]
Hmm i just saw the ULV pump needs a potin rotor, which needs a mixer...

**Comment by Zoko061602** [comment]
Better use hoppers and faucets with a redstone clock. Thats more "Steam Age".

**Comment by EvgenijM86** [comment]
Bad idea. Before LV you can only find lead in chest and you need like 1.5 (or 2) lead ingots per 1 wire because you have no LV machines.

**Comment by Dream-Master** [comment]
Yea lead usage in steam age is a bad idea.

**Comment by Dream-Master** [comment]
Maybe I need to change lead to another material in ulv components but this changes need to be present in gt++ too.

**Comment by draknyte1** [comment]
I can change out the requirement for Potin, but I won't change Potin. (It's a real material)
Just give me a suggestion as to what 😛

**Comment by Dream-Master** [comment]
Sure will think of a material but need the community to look for some too. @septemberWaves @bartimaeusnek @WarlordWossman @Zoko061602 @EvgenijM86

**Comment by septemberWaves** [comment]
Perhaps a solution might be replacing the lead cables in the ULV recipes with zinc ones. Not sure what to do about the potin; maybe replace it with brass? The quest is gated behind the nether anyway (because of the need for sulfur to vulcanize rubber) and it'd be an early use for zinc which otherwise has very few uses for quite a while.

**Comment by bartimaeusnek** [comment]
Lets make ULV cables out of wood.
No seriously zinc and lead are bad ideas here imo, since zinc is only aviable in small ores pre mars and lead is TF. I would go for wrough iron cables, which must be implemented, since iron is the most common material in GTNH, and Iron Cable are MV.

**Comment by bartimaeusnek** [comment]
oh right got confused with arsenic

**Comment by Zoko061602** [comment]
What about Zamak (ZnAl4Cu3), it has a low melting point, is easy to obtain and it conducts electricity
https://en.wikipedia.org/wiki/Zamak

**Comment by WarlordWossman** [comment]
In my opinion that's too complicated for parts that are performing worse than the LV counterparts.
LV motors have copper cables which are MV, so why should the ULV motor not use tin wires and red alloy cables?

**Comment by septemberWaves** [comment]
@bartimaeusnek Arsenic is available from a vein-based ore source before Mars as well. Cobaltite is cobalt arsenide sulfide, and that's found in garnierite veins.

**Comment by Dream-Master** [comment]
yea why not redalloy cables. Maybe use only rupper pump to get cables or a item i can implemetnt like ruber pulp sheets.

**Comment by bartimaeusnek** [comment]
cobalt arsenide is still not an element @septemberWaves, its not pure

**Comment by septemberWaves** [comment]
Cobalt arsenide sulfide is a source of arsenic. I am aware it is not an element, the point is that it contains arsenic; I was pointing out the fact that arsenic is not just available from small ores before Mars. Realgar is the small ore in question, and that is still not an element but it is the arsenic source you were thinking of.

**Comment by Dacryphile** [comment]
So... how are you supposed to extract the arsenic from that pre-LV?

**Comment by draknyte1** [comment]
You find realiar small ores? That's intended progression 👌🏻

**Comment by Dacryphile** [comment]
That's after you get a LV centrifuge; I thought we were still talking about ULV stuff?
