### ISSUE TITLE
Suggestion: Platinum-group Sludge Quest

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2836]
I think it would be a good idea to make a quest for producing platinum-group sludge as a byproduct of chalcopyrite and pentlandite. It could probably be gated behind a quest for ammonia (since that's the most difficult prerequisite to make in bulk). The reason I suggest this is because it's a good early way to get palladium, iridium, and osmium production started early, and doing so early means that the small amounts of these rare metals will build up over time and be available in reasonable quantities by the time players start to need them; also because it's not remotely obvious that this is an option for ore processing because it only works for two ores and it's quite a complex process.

While the sludge production recipe is available from the LV tier, the only way to produce ammonia (for the nitric acid) at that point is by using a distillery, which is a slow and inefficient process. Ammonia can be made easier at the HV tier, so it may be better to gate the quest there, although producing platinum-group metals with this method at this point in the game becomes less useful (still fairly useful though).

**Comment by codewarrior0** [comment]
On the other hand, the yield from this method is miniscule: it takes two stacks of crushed ore to get, on average, one dust each of palladium, iridium, and osmium.

In stock GregTech it provides a way to get the ten or so Osmium you need to set up a replicator and make more. With GTNH's ready availability of those "rare" metals on other planets and moons, and the fact that you don't need Osmium to make field generators, there's not much point to setting up a platinum sludge line.

**Comment by Dream-Master** [comment]
Maybe I need to use it more in some recipes.

**Comment by codewarrior0** [comment]
On the gripping hand, Palladium is a very strong tool material for tinker tools, even moreso if you can get it with only HV tech. It might be worth mentioning just for that.

**Comment by Anarack** [comment]
Also if you want a maceration stack, unless you get lucky with a platinum vein in the end, that is the only source of palladium till the deep dark.

**Comment by codewarrior0** [comment]
Really? Palladium-bearing veins were present on T4+ planets, the last time I checked.

**Comment by Dacryphile** [comment]
Tier 3, actually.  I got a dozen stacks of Palladium ore from my first trip to Ceres.
