### ISSUE TITLE
Suggestion: Superconductor Quests

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2837]
The new superconductors for the MV up to ZPM voltage tiers are something which people might not notice, so perhaps it'd be a good idea to make quests for them (like how there's a quest for lossless redstone alloy cables at LV), both so that players know that lossless wires are an option, and so that they can be rewarded for making them.

Since the superconductors require materials available only at 1 tier above their power tier, it would probably make the most sense to place a quest for MV superconductors in the HV tab, HV superconductors in the EV tab, and EV superconductors (as well as possibly quests for IV, LuV, and ZPM superconductors) in the Tier 6 tab.

**Comment by Dream-Master** [comment]
Added for mv and hv

**Comment by Dream-Master** [comment]
Only Luv, ZPM and the old uhv wires are missing

**Comment by Dream-Master** [comment]
will add after assline quest
