### ISSUE TITLE
Disable Imbued Fire

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#284]
Due to the massive terrain-damage, and its uncontrollable nature, please remove the recipes for all 6 imbued fire. (Page thaumic tinkerer, top right on the page) Don't remove the Thaumonomicon researches however, as they are prerequisites to infused crops. The fire(s) shall not be available to normal players. We let one ignis fire burn for like.. a minute, and we barely could stop it.

If you want to see what happens when you place such a fire, go look at my old base (Or what is left)

**Comment by Dream-Master** [comment]
Not remove but make it much more expensive is possibble i think. On the Live or on the Test Server i have to look?

**Comment by Namikon** [comment]
Your decision. But Drobac and I tested that yesterday, and it went out of control within seconds. If we weren't 2 people, and I had no access to operator commands, this fire would still burn, eating up all chunks it can find. You can see the results on the live server. But just take one ignis fire, and place it on the testserver. Then wait ~1 Minute and see what happens, and if you can stop it

**Comment by Dream-Master** [comment]
So it chunk loading itself or it burns down the chunks in a Player range ?

**Comment by Namikon** [comment]
I don't think it will chunkload, but the fire multiplies itself. One fire spreads out to all adjacent blocks, and that continues until someone stops it, by either placing a block on the fire, or by placing a perditio fire somewhere, which will convert all magic fire to normal fire.
But the perditio only works if you place it fast enough. In our case, the ignis already spread too far. And rain doesn't stop it either

**Comment by Dream-Master** [comment]
Have it a special function or why the Mod Author probably implement it? Or there special Blocks where the fire can't spread?

**Comment by Dream-Master** [comment]
Ok i look a video and know for what it is good.

**Comment by Namikon** [comment]
It's a magic terraformer, so to speak. You can turn the overworld to a nether-like thing. Stone becomes Netherrack, Sand becomes Soulsand, Wheat becomes Netherwart, and some Water-sourceblocks even converted to lava. 
The other fires do something similar, like a snow-world in the nether. It's a very nice thing, and somehow it relates to "the spirits that I called", as you have to be very careful with it. But for a Server, this is way too risky. Maybe we can just disable it on the Server, and keep it in singleplayer

**Comment by Dream-Master** [comment]
Disabled it only in the overworld,
