### ISSUE TITLE
Fehler in 3 Quests / Error in 3 quests

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#2841]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer
yes

Quest
#1131 Ardite and Cobalt
Ist diese Quest in Tier I - Steam richtig? / Is that Quest in Tier I - Steam correct? 
Cobalt kann man doch erst mit Ardite abbauen.

#89 MV Steam Turbine
In dieser Quest muss man eine MV Machine Hull bauen und keine Steam Turbine.

#1151 Wooden Crossbow
Crossbow (3/3) kann man nicht abgeben.
Ist das gewollt, das man Obsidian am Part Builder herstellen kann? Echte harte Eiche :)

**Comment by WarlordWossman** [comment]
> #1131 Ardite and Cobalt
Ist diese Quest in Tier I - Steam richtig? / Is that Quest in Tier I - Steam correct?
Cobalt kann man doch erst mit einem EBF herstellen,

Quest wants the TiCo cobalt ore from the nether which you can't mine with leveled alumite (leveled alumite should be mining level 07-ardite)

> #89 MV Steam Turbine
In dieser Quest muss man eine MV Machine Hull bauen und keine Steam Turbine.

Duplicate of #2830

> #1151 Wooden Crossbow
Crossbow (3/3) kann man nicht abgeben.
Ist das gewollt, das man Obsidian am Part Builder herstellen kann? Echte harte Eiche :)

The crossbow part is a duplicate of #2795
Obsidian should be smeltery only, good find.

**Comment by Zoko061602** [comment]
Iguana changes the recipes for obsidian parts, since most people simply mixed it in the smeltery with lava and water

**Comment by Dream-Master** [comment]
@DragScorpion ich schau mir das noch mal im Detail an.
