### ISSUE TITLE
Shadowmetal Attuned Obsidian Scepter

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2843]
#### Which modpack version are you using?
2.0.3.0
#
#### What do you suggest instead/what changes do you propose?
Change the recipe to only require 125 and not 1255 perditio vis.

**Comment by Dream-Master** [comment]
oh sure was a mistake after nerfing 10k recipes :/

**Comment by Zoko061602** [comment]
I found another one : Ichorium Addorned Blood Wood Sceptre

**Comment by bartimaeusnek** [comment]
Ichorium Addorned Blood Wood Sceptre seems to be fixed in Devpack
