### ISSUE TITLE
Centrifuging cinnabar dust yields Mercury (the planet) stone dust

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#2847]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Centrifuge cinnabar dust in an LV centrifuge -- I expected to get 1000L of liquid mercury and 1 sulfur dust.
#
#### What happend instead? (Attach screenshots if needed)
I got 1 mercury core dust and 1 sulfur dust.
Also, apparently I can smelt that Mercury core dust into quicksilver in a regular furnace.
#
#### What do you suggest instead/what changes do you propose?
Fix the bug so that Mercury (the planet) dust isn't being substituted for mercury (the element) in places.

**Comment by bartimaeusnek** [comment]
already fixed.
