### ISSUE TITLE
[Suggestion] [Quest] "Lapotron Crystal" in Tier 5 changes

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#2848]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
1) The quest description states "... with an HV assembler ..."
2) The quest wants the player to obtain 2 HV-tier circuits and 4 raw crystals as an intermediary step
#
#### What happend instead? (Attach screenshots if needed)
1) Actually making lapotron crystals requires 1024 EU/t @ 1A, which would need an EV assembler.
2) 2 HV-tier circuits is only enough to combine with 1 raw crystal
#
#### What do you suggest instead/what changes do you propose?
1) Change the quest description to say the player needs an EV assembler
2) In part 2 of the quest, either decrease the number of raw crystals from 4 -> 1, or increase the number of circuits from 2 -> 8.

**Comment by richardhendricks** [comment]
I'll take care of updating this.

**Comment by Dream-Master** [comment]
@richardhendricks faster 📦

**Comment by richardhendricks** [comment]
Only 48,000 lines to go! :)
