### ISSUE TITLE
Block of Ichorium is craftable in the compressor

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#2849]
#### Which modpack version are you using?
2.02.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
There are 2 recipies for the block of Ichorium:
![image](https://user-images.githubusercontent.com/23512002/38952753-56435ee4-4355-11e8-8088-adeb64c4cdb4.png)
![image](https://user-images.githubusercontent.com/23512002/38952763-5c8f1cfc-4355-11e8-97a4-088bf08cfc5e.png)

I believe the first one is not intentional

**Comment by Dream-Master** [comment]
Yea thats True.

**Comment by bartimaeusnek** [comment]
@repo-alt @Dream-Master does the thaumcraft recipe requires a block of Ichorium in the middle?

**Comment by repo-alt** [comment]
`mods.thaumcraft.Infusion.addRecipe("ICHORIUMBLOCK",` <dreamcraft:tile.Mytryl>, `
