### ISSUE TITLE
Crash looking into nei when checked assline blocks

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2850]
#### Which modpack version are you using?
2.0.3.1 dev

mentioned Large Centrifuge in crash log which is from GT++ ?

[crash-2018-04-19_15.22.38-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1927251/crash-2018-04-19_15.22.38-client.txt)

Second crash after remove D-O-B Comb recipes

[crash-2018-04-19_17.18.30-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1928239/crash-2018-04-19_17.18.30-client.txt)

**Comment by Dream-Master** [comment]
@draknyte1 any idea on this?

**Comment by draknyte1** [comment]
Probably from using a bad compile of GT++?

**Comment by codewarrior0** [comment]
I bet it's the D-O-B combs again!

**Comment by Dream-Master** [comment]
will re-add it with different recipes in java code.

**Comment by Dream-Master** [comment]
Seems Tec Tech fix works. Will check about the D-O-B Combs recipes.
