### ISSUE TITLE
[2.0.2.7] Energy consumption in Pyrolyse Oven (Wood Tar)

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#2853]
Wood Tar recipe lists that it consumes 40960 EU at 64 EU/t in Pyrolyse Oven. I tried testing that and here are my results (I use Portable Scanner on battery buffer):

1) 2xLV Energy Hatch + Low Voltage Battery Buffer (3 lithium batteries) + 2xRedstone Alloy Cable (zero loss).

```
Energy Before = 32768+3*100000 = 332768 EU
Energy After = 11014+3*77560 = 243694 EU
Consumed = 89074 EU
Efficiency = 0.4598423782
```

2) 1xMV Energy Hatch + Medium Voltage Battery Buffer (2 lithium batteries).

```
Energy Before = 131072+2*400000 = 931072 EU
Energy After = 46612+2*400000 = 846612 EU
Consumed = 84460 EU
Efficiency = 0.4849632962
```

In both cases I consume more than double that is listed in the recipe. Is recipe incorrect or do I need to wire things differently?

**Comment by EvgenijM86** [comment]
And yes - I have fixed all the problems in Maintenance Hatch. It says "Running Perfectly".

**Comment by bedrill64** [comment]
Cupronickel coils work at 50% efficiency, so 2x recipe time, thus 2x energy consumption, everything is fine, can be closed.
