### ISSUE TITLE
[RFC] Add more underground liquids to planets

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2854]
#### Which modpack version are you using?
2.0.3.0

Salt
With the upcoming pam's salt nerf, suggest adding salt water as an underground liquid to certain planets. 

"V.Low" is equal to moon production rates for helium3
"Low" for purposes of discussion is ~ equal to current oil rates
"High" is 5x current oil rates

Salt water
- [x] moon - v low
- [x] Mars - Low
- [x] Europa - High

Helium3
- [x] Moon - V.Low 
- [x] Mercury - Low/High?

Chlorobenzene
- [x] Mars - V.Low

Nitrogen
- [x] Triton - high
- [x] Pluto - high

Methane
- [x] Titan - High

Ethane
- [x] Titan - Low

Ethylene
- [x] Triton - Low

Callisto
- [x] Oxygen - Low

Super Heavy Oil
- [x] Europa - low
- [x] BarnardC - high
- [x] TCetiE - low

Molten NqX
- [x] BarnardC - Low
- [x] VegaB - high

Molten Nq
- [x] Venus - V.Low
- [x] Titan - low
- [x] Haumea - high

liquid air ?
- [x] Callisto- Low
- [x] Charon - Medium
- [x]  BarnardE - High

**Comment by repo-alt** [comment]
Who needs nitrogen, tons of it are produced as a byproduct of argon/helium production

**Comment by 0lafe** [comment]
Nitrogen is more than readily available. Salt on planets is cool I guess, but there should be a different way to get it. Remote chunkloading has it's issues, as well as wireless power transfer

**Comment by richardhendricks** [comment]
How would the remote chunkloading problem be any different than now, with remote oil drills or lava pumps in the Nether?

A remote oil drill doesn't require wireless power transfer, a simple local setup in the same chunk should more than suffice.

The nitrogen idea was to keep semi-realistic (geysers on Triton, glaciers on Pluto).  If there's other more useful liquids, please propose.  

Methane/Ethane/other processed fuels on Titan?

**Comment by richardhendricks** [comment]
Also, since underground fluids do not exist at all until searched for/requested by machines, this wouldn't add any worldgen overhead.

**Comment by 0lafe** [comment]
I mostly meant it would be a problem if that's how you need to get salt. As long as there's other ways to get salt, I don't have an issue with it. It's the same as the problem now, but you never have to use oil drills or pumps in the nether so it's not a huge issue

**Comment by richardhendricks** [comment]
We can adjust the size of the liquid salt so that a lower tier single-block generator can provide enough salt for higher tier needs.  Don't forget, higher tier oil drills gather from more chunks too - I don't think (based on the code - will have to confirm) those chunks necessarily need to be loaded either, just the chunk with the drill.

Methane/Ethane on Titan is realistic and useful.
I think argon on Pluto is OK, it's a cold planet so maybe there is some liquid argon on it somewhere.

**Comment by 0lafe** [comment]
If they weren't as location specific as drilling rigs are, I'd be all for that sort of mentality

**Comment by richardhendricks** [comment]
Well, these will be an option.  I think they're more realistic than EU => magic => stuff, and probably more fun.

**Comment by bartimaeusnek** [comment]
Some more for your list @richardhendricks 

Super Heavy Oil
Europa - low
Barnada C - high
TCetiE - low

Molten NqX
Barnada C - Low
Vega B - high

Molten Nq
Venus - V.Low
Titan - low
Haumea - high

**Comment by richardhendricks** [comment]
I'll have to check tiers on these to make sure they're not accessible at or below tier.  I think putting them at least 1 tier  or maybe 2 up from where the original materials are found is good though.  What is super heavy oil?

**Comment by richardhendricks** [comment]
I think Venus would be fun for more liquid metals, like lead/silver/antimony.

Io would be good for sulfur dioxide and H2S.

But I'm sure by those tier players wouldn't need those materials.

**Comment by richardhendricks** [comment]
https://wiki.micdoodle8.com/wiki/Tiers
http://galaxy-space.wikia.com/wiki/Rockets

**Comment by richardhendricks** [comment]
Additional ideas for more liquids are in this ticket
https://github.com/GTNewHorizons/NewHorizons/issues/2662

**Comment by richardhendricks** [comment]
Argon/other noble gases on Ganymeade/Callisto and Triton

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GregTech/GregTech.cfg#L113

**Comment by richardhendricks** [comment]
2.0.4.9

Salt water -  shows up in prospector, does not pump

helium-3 - works fine on Moon/Mercury

Molten lead - Working

Oxygen - Working

liquid air - not working, does not show up in prospector, drilling rig says running perfectly but no fluids come out

Ethane - Shows up in prospector, does not pump

Methane - Shows up in prospector, does not pump

molten naquadah - Shows up in prospector, does not pump

Chlorobenzene - Shows up in prospector, does not pump

Very heavy oil - Working

**Comment by Dream-Master** [comment]
why some working an some not? @richardhendricks

**Comment by richardhendricks** [comment]
Fuck if I know.  I am trying now to get the prospector oil scanner working properly.  Once that's done I will work on the fluids.

**Comment by richardhendricks** [comment]
Salt water - works
Methane - works
Ethane - Works
Molten Naq - works
Ethylene - works
liquid air - works
