### ISSUE TITLE
Buff shadow-infused cloth caps

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2858]
#### Which modpack version are you using?
2.0.3.0

Shadow infused cloth caps in the vanilla mod provide 10% vis discount and are pretty cheap to make.  

In GT:NH, they have been severely nerfed, which is fine, but still provide just a 10% vis discount, which doesn't align with their difficulty now since they require lots and lots of mats and charged thaumium caps as part of their recipe.

Suggestion is to improve their vis discount to 15%.

Also, if possible, would be to grant all the cloth caps a bonus discount when used with wand focuses.  This would make them very nice to use for illumination wands.

Need to look at:
Cloth caps - 5% vis discount, seems reasonable since their recipe requires a gold cap which has 0% vis discount
Shadow-infused cloth caps - 10% vis discount, not balanced since they require thaumium caps and lots of resources.
crimson-stained cloth cap - 15% vis discount, didn't check recipe. Probably needs buff too.

**Comment by Dream-Master** [comment]
Mod is open source but we not use lastest version
