### ISSUE TITLE
WorldGen

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#286]
Hey guys,
if you ever want to switch from using RWG to something else, I recommend BoP with Big Trees mod.
What it does is it that it generates biome dependant large custom trees using Vanilla and BoP blocks (no blocks added). Large meaning around Thaumcraft Greatwood size. It finally makes the landscape less empty and sometimes creates lovely dense forests. I find it effectively gets rid of vanilla boredom. And it's super server-friendly.

Another tip would be World pregen mod. I'm testing it right now but it seems it works very well and fast and is a forge mod. Also seems stable even when generating large amounts of land. I'll post more if I find issues.

Links:
https://github.com/gecgooden/chunkgen
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278469-the-bigtrees-mod (use downloadable BoP config files and delete DarkOak.cfg as that one is buggy I think).

**Comment by Dream-Master** [comment]
I think we not switch because we already generating with rwg and the Terrain looks great. I check out the Big tree mod and it looks good too. Pregen we don't using atm. Dark Oak Config ?
Did you not like RWG? It is now under development and maybe finally we get Ocean Biomes.

**Comment by Methes** [comment]
Sure, it's your choice.
"Tall Dark Oak.cfg" in the big trees BoP configs is faulty and gets renaimed to *.errored_blabla each startup, eventually creating file with huge filename that can't be easily deleted. So I just delete it beforehand to fix that.
I liked RWG but it never got finished, I missed terrain cliffs and oceans and now someone else took over the mod with unpredictable results. And that's never good for persistant world that counts on stable map. Plus it's extremely resource heavy making it even less valid choice for servers.
Either way I hope it get's finally finished so you can have oceans at least :).

**Comment by Dream-Master** [comment]
Not understand mw wrong i like RWG or ATG thats why i want this mod.
