### ISSUE TITLE
Forbidden Magic Wands

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2860]
#### Which modpack version are you using?
2.0.3.0
#

#### Why you're writing this issue?
I had some time, so added Botania and ArsMagica Wands back in.
#

#### What did you change?
- Added recipes for FM Wandrods (Witchwood, Livingwood and Dreamwood), all require Tungstensteel
- Added recipes for FM Wandcaps (Manasteel, Terrasteel, Elementium, Vinteum), all require at least Titanium
- Added a Crucible Recipe for Vinteum
#

#### Do you need some Core-Mod Items?
- Vinteum, Manasteel, Elementium and Terrasteel caps would be nice :) 
 I used the original caps as placeholder
#

#### Do we need to know anything else ?
- Astral Silver, which is required for Manasteel Caps should require at least HV (It can be mixed by hand and simply smelted, but also in the alloy smelter at EV, that doens't make any sense)
- The scripts also include recipes for Thaumic Bases Wands 
#

#### Screenshots
![elementium kissed dreamwood wand](https://user-images.githubusercontent.com/32712367/39095881-22736b4a-4648-11e8-8535-ca94aef5b40d.PNG)
![forbiddenwands](https://user-images.githubusercontent.com/32712367/39095882-228fee5a-4648-11e8-8ef7-7dbccf240e51.PNG)
![vinteum](https://user-images.githubusercontent.com/32712367/39095883-22a83b36-4648-11e8-97b4-c29016868806.PNG)

# 
#### Files
[Forbidden-Magic-01-Wands.txt](https://github.com/GTNewHorizons/NewHorizons/files/1935685/Forbidden-Magic-01-Wands.txt)

[Forbidden-Magic-02-Caps.txt](https://github.com/GTNewHorizons/NewHorizons/files/1935684/Forbidden-Magic-02-Caps.txt)

**Comment by Dream-Master** [comment]
sounds cool will check when i got time.

**Comment by richardhendricks** [comment]
I'd like to add things that either add more content (areas or bosses) or fix a playability issue (like the Arcane Abacus letting you know more about your infusion altar).  What does this mod offer for actual content?  Are there more bosses or dimensions? Does it solve a problem in the modpack?

**Comment by richardhendricks** [comment]
yea sorry

**Comment by Dream-Master** [comment]
np

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/39837882-f4d9cccc-53d7-11e8-8396-05b893a519e4.png)
this cost only 6 vis

**Comment by Zoko061602** [comment]
I guess thats fine. I took a fifth of the vis cost of ichorium, since it has a vis "discount" of 180%

**Comment by Dream-Master** [comment]
at a Low tier I will start with 20 . will check it tomorrow.

**Comment by Dream-Master** [comment]
maybe we tyr with this values and will correct later.
