### ISSUE TITLE
[2.0.3.0] Galacticraft Frequency module uncraftable

### ISSUE THREAD

**Issue by Diresheep** [GTNewHorizons/NewHorizons#2862]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Bacongaming server
#
#### What did you try to do, and what did you expect to happen?
Craft a frequency module (GalacticraftCore:item.basicItem:19)
#
#### What happend instead? (Attach screenshots if needed)
Recipe does not work, items ghost in and out of forestry worktable, other tables just dont recognize recipe
#
#### What do you suggest instead/what changes do you propose?

Unsure of a fix, or what the problem might even be

EDIT: New info, even though the recipe shows empty batteries, using full ones is the only thing that works

**Comment by Dream-Master** [comment]
I remember i fixing it but have to check again.

**Comment by nikitinalexx** [comment]
I definitely built a full Tier1 Rocker will all required equipment in 2.3.0. Played in single player.

**Comment by Dream-Master** [comment]
@nikitinalexx So it worked?

**Comment by nikitinalexx** [comment]
Yes, it worked.
