### ISSUE TITLE
[Mod Suggestion] Witching Gadgets

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2863]
#### Which modpack version are you using ?
2.0.3.0 
#
#### Why are you writing this issue ? 
I think that Witching Gadgets should be added to GTNH, I've seen that this mod was suggested in 2016 and since I like Witching Gadgets, I just wanted to ask for it. 
#
#### Why do you think that mod should be added ?
Just look at the things it offers:
- Many new baubles (Kamas, Cloaks, Pauldrons, Vambraces, etc.) with special abilities.
- A Biome Manipulator
- More metal purifications
- 3 Types of backpacks
- A Pump to fill essentia from mirrors into tubes
- A spinningwheel with minetweaker support
- A Calculator for Nodes and the Infusion
- A Cobblestone Generator
- Magical gems 
- It makes invisibility useful
- A own Blastfurnace for ore tripling with minetweaker support
- A block that prevents Warp Effects in exchange of hunger
- Forge Multipart support for essentia tubes
- And it's own "endgame" armor
Also it's coremod adds a new GUI with all TConstruct and Baubles Slots, thats completly customizeable.
#
#### Is there anything else?
It's Open Source and I guess it didn't slowed the start. 
#
#### Links
https://minecraft.curseforge.com/projects/witching-gadgets
https://minecraft.curseforge.com/projects/travellers-gear
#459
#497

**Comment by bartimaeusnek** [comment]
The Cobblestone Generator killed my last IT2 server tho, laggy af 😀

**Comment by Zoko061602** [comment]
@bartimaeusnek thats what's reminded me of WG

**Comment by Dream-Master** [comment]
If you take about it I will check it out later.

**Comment by WarlordWossman** [comment]
Sounds good besides "A own Blastfurnace for ore tripling with minetweaker support" since we really got ore processing covered and don't want to add more clutter to NEI.

**Comment by Dream-Master** [comment]
We can disable it

**Comment by Dream-Master** [comment]
Are the lastest version have any known major  bugs @bartimaeusnek @WarlordWossman @Zoko061602

**Comment by Dream-Master** [comment]
Yea Krypton captain fix it all ( thaumcraft mods)

**Comment by boubou19** [comment]
If i remember correctly this mod add also a searchbar in the thaumonomicon which is, in my opinion, the best feature of this mod.

**Comment by Dream-Master** [comment]
Yes will definitely look into the mod today.
