### ISSUE TITLE
GT++ Power station rebalance tracking ticket

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2865]
#### Which modpack version are you using?
2.0.3.0

This ticket is to help people find information on the Power Sub-station rebalance in GT++

https://github.com/draknyte1/GTplusplus/pull/244

**Comment by draknyte1** [comment]
You know this won't be in a release version until mid May, at earliest, right?

**Comment by richardhendricks** [comment]
I'm well aware of that, I just wanted a link for people to place their comments and look at what has already been discussed.

**Comment by 0lafe** [comment]
Uh, so does that mean if 2.0.3.1 comes before that, we got the infinity power storage one?

**Comment by richardhendricks** [comment]
https://www.patreon.com/Alkalus/overview

Get to work, indentured servant!

![image](https://user-images.githubusercontent.com/1214811/39223935-39cde478-480a-11e8-901e-6a3ed4b1587d.png)
