### ISSUE TITLE
World-breaking crash bug; appears to be Ztones-related

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#2866]
#### Which modpack version are you using?
2.0.3.0
#
#### Outline of the problem:
Upon loading up a world, the game takes a long time (10 to 15 minutes) trying to load the world, and then crashes. The crash report appears to indicate a problem with Ztones.

This specifically happens with creative-mode worlds, when I've been using the NEI creative+ mode and the inventory-saving feature that it has. This inventory-saving feature seems to be broken currently, and replaces the saved items with randomly-chosen items in the same inventory spaces after the game is restarted (even in the same creative-mode world that the inventory configuration was saved); this appears to be what leads to the crash, as I am able to load up worlds where I do not try to load a saved inventory configuration, but the moment I do attempt to load a saved inventory configuration the game crashes (and every time I try to load that world in future, the game crashes again). This, and the crash report, leads me to assume that the crash is related to a broken Ztones block which gets placed into the inventory by the broken NEI creative+ mode inventory save/load feature.
#
#### Crash report:
https://pastebin.com/1vbaa5xg

**Comment by bartimaeusnek** [comment]
@septemberWaves try to delete "playerdata" in your /saves directory.
