### ISSUE TITLE
[RFC] Add replacement quests to the questbook.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2869]
#### Which modpack version are you using?
2.0.3.0

Rockets disappear from the launchpad and suffer from other buggy behavior that can result in loss-of-rocket - ie, getting stuck in a cloud.  Stevescarts can also disappear in frustrating ways.

Suggestion is to add a Coins quest with a long timer (1 week?) to allow for players to purchase a replacement rocket of the tier they have unlocked, or replacement stevescarts parts after they have completed the questline.

Will need to confirm that purchased rockets cannot be arcfurnaced or disassembled.

**Comment by draknyte1** [comment]
Probably can't be recycled unless they have their crafting nbt, But don't quote me on that.

**Comment by Dream-Master** [comment]
Will find a way hopfully.
