### ISSUE TITLE
Suggestion: Duodecuple or sexdecuple fluid pipes

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#2872]
Nonuple Fluid Pipes are a great way to work with fluids, both in collecting and distributing them, if players don't want to use the quite magical EIO Conduits. However, since there are multiblocks that produce more than 9 fluids, like the Distillation Tower and LFTR, I'd suggest adding either Duodecuple (crafted from 3 Quadruple) or Sexdecuple (crafted from 4 Quadruple) Fluid Pipes. Flow would be calculated as 1/3 or 1/4 of the Quadruple Pipes.
Would that be possible? Are there any concerns regarding balancing / usability?

**Comment by draknyte1** [comment]
Better suggestion for the main GT fork.

Regarding sizes, it would be 16x and not 12x.

**Comment by Wolozo7** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/1447
