### ISSUE TITLE
[cleanup] remove NEI entries in machines you can not get

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2875]
There is quite a few machines that still got recipes showing up in NEI even if you can't get them in survival. It makes it more confusing for new players and even people who know their way around need to click through more pages. They do add a lot of clutter in the end.

Here are the examples I found, don't get confused on the familiar machine names in there, these ones are the IC2 ones which are disabled:

![nei_6](https://user-images.githubusercontent.com/16925725/39293261-bbbc6f5c-4938-11e8-8865-bdf32c659988.PNG)
![nei_1](https://user-images.githubusercontent.com/16925725/39293262-bbd73350-4938-11e8-85aa-7746c3d420bc.PNG)
![nei_2](https://user-images.githubusercontent.com/16925725/39293263-bbf02112-4938-11e8-8f7a-a05cc6c82edc.PNG)
![nei_3](https://user-images.githubusercontent.com/16925725/39293264-bc081b32-4938-11e8-9209-a2b170277534.PNG)
![nei_4](https://user-images.githubusercontent.com/16925725/39293265-bc20e04a-4938-11e8-8085-f7d3ab9fc6aa.PNG)
![nei_5](https://user-images.githubusercontent.com/16925725/39293266-bc3ad202-4938-11e8-99e7-34b745b72d12.PNG)

Removing all of them would help a lot.

**Comment by Dream-Master** [comment]
component assembler us disabled in 2.0.3

**Comment by draknyte1** [comment]
Unfortunately these recipes are all registered through IC2/GC/Etc then managed by GT. So, not really much we can do there. Because removing the original entries then removes any stuff GT manages. 

Component assembler stuff doesn't exist post 2.0.3, If not earlier.

**Comment by WarlordWossman** [comment]
Oh okay, so no way to get rid of them? Why does the IC2 macerator not show up then?

**Comment by bartimaeusnek** [comment]
@draknyte1 can we just add a class that prohibits NEI from loading the IC2, GC etc. classes?
