### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#288]
Update done.

Please report Bug if yu found some.

**Comment by Dream-Master** [comment]
New Update 5.8.15

So lets test.

**Comment by Dream-Master** [comment]
New Update 11.8.15

So let's test again.

**Comment by Dream-Master** [comment]
New Update 14.8.15

So let's test again.

**Comment by Dream-Master** [comment]
TPS are very low. Yesterday between 10 and 6. No clue why.

**Comment by Drobac** [comment]
Is it stable now? guessing server restarted since yesterday

**Comment by Dream-Master** [comment]
no i restart now because tps at 3

**Comment by Dream-Master** [comment]
I make a quick update now. Only Mod Updates.

**Comment by Dream-Master** [comment]
Update TODAY 16.9.15
Version 1.0.4.9
I don't have the time to testing all things.

**Comment by Dream-Master** [comment]
I did a Script update today 17.09.2015 need to be tested also.

**Comment by Namikon** [comment]
No errors so far. I suggest to not create issues for telling people that there was an update. Is it possible to create a normal post in the forum with a changelog instead? So we could actually go directly for the changed stuff and test it, instead of trial and error stuff

**Comment by Dream-Master** [comment]
Ok good idea. So i close this here.
