### ISSUE TITLE
Electric scribing tools running out of ink?

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/NewHorizons#2880]
GT NH 2.0.3.0 SP

They seem to run out of ink and stop working even with full energy. Can't be refilled?
Maybe they use ink instead of EU? It seems to be an error. Right now there's no point in making them.
![est](https://user-images.githubusercontent.com/22689175/39398697-b24b84aa-4b11-11e8-9ba8-3ebd55f5a304.png)
![est2](https://user-images.githubusercontent.com/22689175/39398728-340b3986-4b12-11e8-8cbd-638bc2c39423.png)

**Comment by bartimaeusnek** [comment]
Place them in a LV or HV battery buffer im not sure at which state 2.0.3.0 is. one of these buffer is working for refilling.

**Comment by madmacf** [comment]
I have the wireless charger MKIII keeping it full of energy. Look at the screendumps. It's full of energy but has run out of ink. The HV bat buffer does not work.

**Comment by madmacf** [comment]
Hmm the LV bat buffer does work. I'd say it's still a bug, allthough a minor one.

**Comment by Gateswong** [comment]
You can also put it into any GregTech machine as a battery that will fix the durability.

**Comment by richardhendricks** [comment]
@draknyte1
Is this a bug with the wireless chargers?

**Comment by draknyte1** [comment]
No idea. I use the IC2 API for electrics so, probably not.

**Comment by richardhendricks** [comment]
Update quest for them to describe limitations.

**Comment by richardhendricks** [comment]
What's the consensus on this @bartimaeusnek ? Does this look right?

![image](https://user-images.githubusercontent.com/1214811/57199853-aa2ecb80-6f49-11e9-94c4-6a2f1f080d0d.png)

**Comment by Lxran** [comment]
Right, I'm somewhat confused as to whether I should just make a comment here or make a new issue but I'm encountering the same issue all this time later on version 2.7.0-RC1. Maybe a regression?

If the solution is to change the quest description, then the current quest description is somewhat deceiving. If you are in range of a GT++ HV Wireless Charger, it will charge the HV batteries in your inventory and sure enough, it will charge the Electric Scribe's Tools, but the tool will not gain durability and will still need to be charged inside a machine for it to do so. The questbook should add that ***the only way*** for this item to gain durability is to charge it inside a machine.
