### ISSUE TITLE
Shadowmetal cap infusion consumes the primordial pearl

### ISSUE THREAD

**Issue by mergendil** [GTNewHorizons/NewHorizons#2881]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
private server made for those playing on trilex's server before it's permanent shutdown
#
#### What did you try to do, and what did you expect to happen?
The shadowetal cap's thaumomicon entry specifies that the primordial pearl is not consumed.

#
#### What happend instead? (Attach screenshots if needed)
The pearl was consumed.
#
#### What do you suggest instead/what changes do you propose?
Right after the completion the pearl was there for a tick, however the pearl got overwritten by the infusion result.
I suggest swapping the place of the pearl with the charged void cap
That way the central item (wich then would be the cap) can be replaced by the infustion result while the pearl (which would be on a peripheral pedestal) can avoid being overwritten by the infustion result.

**Comment by bartimaeusnek** [comment]
Will have to test when #2863 is in the Dev pack.

**Comment by bartimaeusnek** [comment]
Should be fixed. Will test and report back.
