### ISSUE TITLE
Infinity materials can not be obtained without infinity

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2882]
#### Which modpack version are you using?
2.0.3.0

Title 

Tartarite ingots can not be obtained so this prevents the infinity catalyst from being made which prevents access to the deep dark for  infinity catalyst ore.

See for #2669 possibly some work was done on this and something was missed

**Comment by sthegreat** [comment]
Planet centrifuging for catalyst dust exists so it is fine, although it is a little silly to have an unusable dire crafting recipe as well. Imo the dire crafting should be made possible o removed.

**Comment by Anarack** [comment]
Why remove the crafting for the catalyst, its not like you have anything else to do with the mats at that point. Also with planet dust method even with 64 UV centrifuges would take 82.5 or so hours to get the amount needed for the portal and to process 800,000 planet dust with the best chance for catalyst dust.

**Comment by 0lafe** [comment]
Someone was doing it recently, and we calculated it would take him 8 days or so, it's not a quick process. It's not a terrible idea to gate it behind a lot of constant power. Infinity is meant to be past UV I think, so that makes sense. Maybe increase the amount per stone by a little, but there doesn't need to be a catalyst recipe

**Comment by Dream-Master** [comment]
but the avaritia recipes still there or i am wrong here?
@Anarack @0lafe @sthegreat

**Comment by 0lafe** [comment]
The avaritia recipe for the infinity catalyst is still there, but uncraftable. All the other recipes that need infinity ingots still work, but having the infinity catalyst recipe show up can be confusing. If there's a way to either remove it, or if you want to rework it so it is craftable, that might be a good idea

**Comment by Anarack** [comment]
The change to make it craftable is simple, as for disabling in favor just the rock method, thats boring. All it is, is quarrying 51 or so chunks down to bedrock and just waiting while making almost everything you have done up to that point in automation systems pointless except for how much power you want to throw at it.

**Comment by Dream-Master** [comment]
what part of the avaritia recipe not working or the other way just easier ?

**Comment by Anarack** [comment]
Tartarite ingots could not be gotten in any form, this prevented the catalyst from being made with the 9x9 crafting method.

As for which way is easier I'm not sure, at a minimum the 9x9 crafting rout needs more odd setups to produce at least.

**Comment by Dream-Master** [comment]
make some recipe suggestion for it.

**Comment by 0lafe** [comment]
You need 11 per ingot right? So 22 to make the portal. Idk, just the 22 16384k drives alone would be enough to get me to avoid that recipe. Singularities too, at 63k per or something like that, needing 22 is, a lot of ingots of some kind of expensive stuff.

**Comment by 0lafe** [comment]
As for suggestions, I think just removing the dire crafting method is the best way to do it.

**Comment by Anarack** [comment]
So if we want the expensive methode first we need a way to gate using the catalyst dust some how without locking out the compressor.

Possibly using straight infinity dust as a reusable chemistry catalyst to make infinity catalyst? So you are forced to make one ingot the hard way before you can use the cheesy way.

**Comment by Dream-Master** [comment]
I need to check it in-game

**Comment by 0lafe** [comment]
I don't see how that changes removing the dire recipe for the catalyst, it seems to just make it more annoying to craft before or after access to the deepdark

**Comment by Anarack** [comment]
The point is I think the planet dust method should never of been implemented as it is extremely boring and makes your stock piles of materials almost pointless, scene it was and will probably stay around, I want the dire way to stay and be a part of progression somehow, even in a limited form.

 There are better ways to do it, that was just a suggestion and making you do the dire way at least once.

**Comment by 0lafe** [comment]
What about reducing the infinity ingots needed for the DD portal to 0, have it cost like 4-5 catalysts, and an eternal singularity. That way you need to dump a LOT of resources into it, but the grind for the catalysts isn't the main focus, so the tediousness is negated by 75% in favor of adding a different requirement

**Comment by Anarack** [comment]
Kind of like that, Its mainly all the odd ball items that pull from everything you have worked, or simply the best or most difficult common ish thing a mod has, that I liked with the catalyst rather than the shear material cost of the thing.

**Comment by Dream-Master** [comment]
making the portal cheaper I against it. we will find a better way make it less grindy but take it at a high level need much effort to reach it.

**Comment by noobyaran9** [comment]
I think make them cost some UV parts like field generator, emitter and sensor in replace of infinity materials.

I thought some form of infinity catalyst spawn on T8 planet?

**Comment by bartimaeusnek** [comment]
Im in favor for infinity catalyst dust + infinity catalyst in chem reactor at UV -> 2x infinity catalyst

**Comment by 0lafe** [comment]
It does @noobyaran9 the problem is that the way it spawns is too grindy and boring I think

**Comment by noobyaran9** [comment]
>It does @noobyaran9 the problem is that the way it spawns is too grindy and boring I think

There is the solution for this issue then. Grindy and boring always comes together.

**Comment by 0lafe** [comment]
I agree completely, I have no issues the way it is right now

**Comment by noobyaran9** [comment]
By reaching T8 planet, you should already have some form of quarry again so it won't be a boring way of obtaining them (Unless you still mine manually at this stage which u shouldn't). And the compressor itself already cost UV stuff to make. Its already have plenty of gating to the singularity itself.

**Comment by 0lafe** [comment]
The grindy part is the multiple day centrifuging you gotta do I think. 64IV centrifuges can do it in 82h which is a little much, but totally reasonable. Anyway, if you're not making multiple amps of UV at that point, you're doing something really wrong.

**Comment by noobyaran9** [comment]
>The grindy part is the multiple day centrifuging you gotta do I think. 64IV centrifuges can do it in 82h which is a little much, but totally reasonable. Anyway, if you're not making multiple amps of UV at that point, you're doing something really wrong.

Centrifuging?????? I thought small infinity catalyst ore spawn on T8s?

**Comment by 0lafe** [comment]
If that's true, then this is really unnecessary. I thought it was just a ~1.5% chance from alpha centauri stone

**Comment by Dream-Master** [comment]
thats to easy

**Comment by noobyaran9** [comment]
>thats to easy

Don't forgot about the compressor u need to turn 64 dust into 1 catalyst. 
Thats already plenty of grind.

**Comment by draknyte1** [comment]
Centrifuging isn't really an issue if you use the Industrial centrifuge. /2cents

**Comment by 0lafe** [comment]
>Centrifuging isn't really an issue if you use the Industrial centrifuge. /2cents
Yeah, because an EV multiblock out preforming 64IV centrifuges taking 1A UV seems indended

**Comment by draknyte1** [comment]
I see you're making assumptions again. It's been retiered like ALL the others, which I even told and pinged you about directly on discord. 

I still think it's hilarious that you're the only person who is salty about them and also, the only person who needs infinite salt for reasons you can't truly explain to anyone. Lul

**Comment by 0lafe** [comment]
Retiered to what? I doubt it's more expensive than 64IV centrifuges, but I guess that's just an assumption. What's the new cost of it?

**Comment by noobyaran9** [comment]
Lets just re-add the small infinity catalyst ore back to Vega B and call this issue solved unless someone would like to have alternative way of obtaining the infinity catalyst dust after obtaining 1 infinity catalyst as catalyst for recipes.

This is the recipe of the neutronium compressor which u need it to convert the dust into the catalyst.
<img width="376" alt="2018-05-01_11 23 27" src="https://user-images.githubusercontent.com/13598309/39460068-fbb3fd7a-4d32-11e8-8b23-2d37f6d1dd84.png">

Which u need 64 dust to get a single catalyst.
<img width="260" alt="2018-05-01_11 23 38" src="https://user-images.githubusercontent.com/13598309/39460066-fb4d2da2-4d32-11e8-9749-e453b91a7b8f.png">

Which u need 11 of them to just get 1 infinity ingot. (Thats already 704 dust per ingot)
<img width="379" alt="2018-05-01_11 23 33" src="https://user-images.githubusercontent.com/13598309/39460065-fb1a7c68-4d32-11e8-809e-b9096f20fdc7.png">

This is the current recipe of the DD portal which u need 2 infinity plate in the recipe (Results in 1408 dust)
<img width="261" alt="2018-05-01_11 24 01" src="https://user-images.githubusercontent.com/13598309/39460067-fb7f3950-4d32-11e8-9c2f-9fe95a3267c8.png">

The neutronium compressor itself already gated the whole recipe to almost end game which u need a tons of neutronium from black plutonium. Why the heck do anyone would want to introduce more grind into the stupid DD recipe? 

If i were to change something in the recipes, I would just add an alternative way of getting the catalyst and the neutronium dust. Mining black plutonium or getting tiny piles of neutronium from planet dust would takes weeks or even month to get the DD portal itself.

**Comment by bartimaeusnek** [comment]
@Dream-Master @noobyaran9 @0lafe how about removeing the Ethernal Singularity from the 9x9 Infinity Catalyst recipe and replacing it with another / some other Singularity/ies, that does not require IC?

**Comment by noobyaran9** [comment]
>@Dream-Master @noobyaran9 @0lafe how about removeing the Ethernal Singularity from the 9x9 Infinity Catalyst recipe and replacing it with another / some other Singularity/ies, that does not require IC?

How about just remove that recipe and call it closed?

**Comment by noobyaran9** [comment]
<img width="376" alt="2018-05-01_11 23 27" src="https://user-images.githubusercontent.com/13598309/39662302-124355b0-5092-11e8-8231-e08249150f02.png">
Im going to be against any recipe using singularity if the neutronium compressor is the above recipe

**Comment by Dream-Master** [comment]
Why @noobyaran9

**Comment by noobyaran9** [comment]
Because there is already a recipe on turning 64 infinity catalyst dust into 1 infinity catalyst using the above neutronium compressor.

**Comment by Anarack** [comment]
And? It's not like you need more than one of them with how fast they are. Also its the end of the pack, what else are you going to use it for anyway?

**Comment by 0lafe** [comment]
More infinity catalyst. Anyway, ending a t8 rocket and making UV parts is not the end of the pack. There's still a decent amount of other stuff to do, more once tec tech releases more. 

I'm with @noobyaran9 on removing the recipe, but not the small ores. The idea now is to make your first 2 ingots of infinity with planet stone processing, then move onto DD infinity catalyst ore for the rest. I think that's fine the way it is.
