### ISSUE TITLE
Witches not giving thaumcraft mob aspects when killed

### ISSUE THREAD

**Issue by darkpouetman** [GTNewHorizons/NewHorizons#2885]
#### Which modpack version are you using?

#2.0.2.7
#### If in multiplayer; On which server does this happen? Tested in so and mp lan

#
#### What did you try to do, and what did you expect to happen?
When killed witches should drop aspects to charge thaumcraft wands and they do not.
#
#### What happend instead? (Attach screenshots if needed)
They do not drop any aspects while other mobs do.
#
#### What do you suggest instead/what changes do you propose?

Make witches drop aspects.

**Comment by Dream-Master** [comment]
Not sure if I can give Entities Aspects. will check.

**Comment by darkpouetman** [comment]
Thank you very much for taking a look at this. I'm really not sure where it goes wrong, maybe special mobs?

**Comment by Dream-Master** [comment]
could be.

**Comment by Dream-Master** [comment]
There are more Mobs without aspects. Need help.

**Comment by darkpouetman** [comment]
What can I do to help?

**Comment by Dream-Master** [comment]
Add more Aspects to missing ones like i did now for witches. I upload the config files to github and every mob that is empty can have new mob aspects. Add some if you like @darkpouetman
