### ISSUE TITLE
Duplicate Fermenter Recipes for Biomes O Plenty Saplings

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#2886]
#### Which modpack version are you using?
2.0.3.0

#
#### If in multiplayer; On which server does this happen? 
Using Singleplayer

#
#### What did you try to do, and what did you expect to happen?
There are duplicate recipes for the "Dying Sapling" from Biomes O Plenty in the forestry Fermenter:
Recipe One: One sapling + 50mB Water --> 50mB Biomass 
Recipe Two: One sapling + 250mB Water --> 250mB Biomass 

I tried fermenting the sapling and it used the 250mB recipe, giving me a good amount of results per sapling. After a restart of Minecaft, it used the 50mB recipe, resulting in a drastic loss in efficiency.

This doesn't only affect "Dying Sapling", but also a lot of the other saplings from Biomes O Plenty.
Affects the recipes using "Water", the recipes using "Honey" and the recipes using "Fruit Juice".

#
#### What do you suggest instead/what changes do you propose?
One of the two recipes should be removed or changed.

**Comment by Dream-Master** [comment]
maybe need to check the gt config for double entries.

**Comment by Dream-Master** [comment]
How Forestry get recipes for the fermenter for other Mods items ?

**Comment by DarkShadow44** [comment]
Okay, I found out what the problem is.
Both BiomesOPlenty and Forestry add the recipes in their compat plugins. But forestry's integration is better (it adds fair values for biomass and adds crops to its farm). However, you can't prevent BiomesOPlenty from adding the recipes.

I don't know how good your coding skills are, but the classes that add the recipes are:

`forestry_1.7.10-4.2.16.64.jar!/forestry/plugins/compat/PluginBiomesOPlenty.class`
and
`BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar!/biomesoplenty/common/integration/ForestryIntegration.class`

My solution would be to patch BiomesOPlenty to not add recipes.

**Comment by Dream-Master** [comment]
ok but maybe then some onther recipes are missing. @DarkShadow44

**Comment by Dream-Master** [comment]
only this line ?
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/integration/ForestryIntegration.java#L41
@DarkShadow44

**Comment by DarkShadow44** [comment]
No, it affects all Fermenter Recipes.
But squeezer recipes, flowers, and backpack items too are added twice - we should also prevent that.

Forestry code for comparison: https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/plugins/compat/PluginBiomesOPlenty.java

**Comment by DarkShadow44** [comment]
Sure, we could register a class transformer and change the class before it's loaded. I've already done that once, it's not too difficult.
Or, the hacky version, we could just binary edit the one offending classfile by hand and then replace it.

**Comment by draknyte1** [comment]
The latter isn't an option. 
Using ATs is also shitty. 

Just fork it, not like either mod will get any more updates ever again. 🤷🏻‍♂️🤷🏻‍♂️🤷🏻‍♂️🤷🏻‍♂️

Why make it harder on yourselves unless you have to? Like if we were on 1.10+, ATs or straight ASM via coremodding would be best, but we aren't so don't pretend we need to be.

**Comment by DarkShadow44** [comment]
> Like if we were on 1.10+, ATs or straight ASM via coremodding would be best, but we aren't so don't pretend we need to be.

Why is 1.10+ different?

**Comment by draknyte1** [comment]
Because 1.10/1.12 are active versions and 1.7.10 is not?

🤔🤔🤔🤔🤔🤔

**Comment by DarkShadow44** [comment]
Well, I guess it also depends on how much effort forking the mod is. I don't know though.

**Comment by draknyte1** [comment]
Press the fork button on their repo.
???.
Profit $$.

It's something Dream can fix himself, or delegate off to another for two minutes of work. Why do anything more unless you want to prove something? 🤔🤷🏻‍♂️

Just my 2 cents.

**Comment by Dream-Master** [comment]
ok will fork bop

**Comment by Dream-Master** [comment]
@DarkShadow44 can you post all linmes i need to comment out? Thanks

**Comment by Dream-Master** [comment]
// addFermenterRecipes();
	// addSqueezerRecipes()

I am ok with it but why comment this out ?
// addBOPFlowers();
@DarkShadow44

**Comment by DarkShadow44** [comment]
Forestry already registers BOP flowers, I don't see a reason to register them again.

**Comment by Dream-Master** [comment]
This one ?
	private static void addFlowers()
	{
		FlowerManager.plainFlowers.add(new ItemStack(BOPCBlocks.flowers, 1, OreDictionary.WILDCARD_VALUE));
		FlowerManager.plainFlowers.add(new ItemStack(BOPCBlocks.flowers2, 1, OreDictionary.WILDCARD_VALUE));
	}

**Comment by DarkShadow44** [comment]
What do you mean?

Forestry adds BopFlowers in https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/plugins/compat/PluginBiomesOPlenty.java
```
private static void addFlowers() {
		Block flowers = GameRegistry.findBlock(BoP, "flowers");
		if (flowers != null) {
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 0, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);		//Clover
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 1, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow, FlowerManager.FlowerTypeMushrooms);		//Swampflower
//			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 2, 1.0, FlowerManager.FlowerTypeNether); 		//Deathbloom
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 3, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow); 	//GlowFlower
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 4, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);		//Blue Hydrangea
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 5, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow, FlowerManager.FlowerTypeJungle);		//Orange Cosmos
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 6, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);		//Pink Daffodil
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 7, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);		//WildFlower
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 8, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);	//Violet
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 9, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);		// White Anemone
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 10, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);	// Waterlily
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 11, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);	//EnderLotus (does not actually spawn in the end)
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 12, 1.0, FlowerManager.FlowerTypeCacti);		//Bromeliad
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 13, 1.0, FlowerManager.FlowerTypeNether);		// EyeBulb
//			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 14, 1.0, FlowerManager.FlowerTypeNether);		// Unlisted top of the eyebulb
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers, 15, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow);	// Dandelion Puff
		}

		Block flowers2 = GameRegistry.findBlock(BoP, "flowers2");
		if (flowers2 != null) {
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 0, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeJungle);		//Pink Hibiscus
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 1, 1.0, FlowerManager.FlowerTypeVanilla);	//Lily of the Valley
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 2, 1.0, FlowerManager.FlowerTypeNether);		// Burning Blososm
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 3, 1.0, FlowerManager.FlowerTypeVanilla);	// Lavender
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 4, 1.0, FlowerManager.FlowerTypeVanilla);	// Goldenrod
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 5, 1.0, FlowerManager.FlowerTypeVanilla);	//Bluebells
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 6, 1.0, FlowerManager.FlowerTypeVanilla);	//Miner's delight
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 7, 1.0, FlowerManager.FlowerTypeVanilla, FlowerManager.FlowerTypeSnow); //Icy Iris
			FlowerManager.flowerRegistry.registerPlantableFlower(flowers2, 8, 1.0, FlowerManager.FlowerTypeVanilla);	// Rose
		}
		// Toadstool 0 Portobello 1 Blue Milk cap 2 Glowshroom 3 flat mushroom 4 shadow shroom 5       'plants:12' tiny cactus
		Block mushrooms = GameRegistry.findBlock(BoP, "mushrooms");
		if (mushrooms != null) {
			FlowerManager.flowerRegistry.registerPlantableFlower(mushrooms, OreDictionary.WILDCARD_VALUE, 1.0, FlowerManager.FlowerTypeMushrooms);
			FlowerManager.flowerRegistry.registerPlantableFlower(mushrooms, 3, 1.0, FlowerManager.FlowerTypeNether);
		}
		Block plants = GameRegistry.findBlock(BoP, "plants");
		if (plants != null) {
			FlowerManager.flowerRegistry.registerPlantableFlower(plants, 12, 1.0, FlowerManager.FlowerTypeCacti);
		}
	}

```
