### ISSUE TITLE
Gearboxes require different materials

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2887]
#### Which modpack version are you using?
2.0.3
#
In Iron gearbox recipes it requires Stainless Steel rings.

![image](https://user-images.githubusercontent.com/4941736/39432482-444682ca-4c9c-11e8-8528-ea21ab289526.png)

But starting from Steel Gearbox recipes and up, it requires different tier rings. For example
![image](https://user-images.githubusercontent.com/4941736/39432562-74971fca-4c9c-11e8-8cba-6419fa6c471a.png)

**Comment by Dream-Master** [comment]
will check the tiers and change recipes
