### ISSUE TITLE
Forestry leaf/butterfly lag?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2888]
#### Which modpack version are you using?
2.0.3.0

I did a test yesterday, and cut down most of the vanilla trees that have pollination leaf blocks from Forestry.  It seems like it helps with the freezelag I would get after playing for a few hours, where the Ui freezes for anywhere from a second to several seconds.  While we did lower config for butterflies, I suspect forestry leaf blocks are the real culprit, and those can be created for using forestry trees for farms or from bee pollination, or may be leftover from butterfly spreading. 

Need some more testers with bad freezelag to report on amount of forestry leaf blocks and how bad lag is before and after removing the majority of them & killing butterflies.

In my case, I had a huge swath to my north (due to forestry butterfly bug) full of butterflies and pollinated leaves.

potential relevant code from Forestry:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/arboriculture/tiles/TileLeaves.java#L176

https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/lepidopterology/ButterflySpawner.java#L23

IDK how much overhead there is to declaring new local variables on every leaf block tick, but maybe this is a cause of excess garbage collection?

Need to investigate.

**Comment by draknyte1** [comment]
Refer to #2886's solution. That will allow us to fix this issue too if we.. tweak some tick rates.

**Comment by DarkShadow44** [comment]
This one is about forestry, the one you linked is about BiomesOPlenty.

**Comment by bartimaeusnek** [comment]
how about just adding a tick counter to it, when it reaches X Ticks it will execute the procedure, should lower the load imo.something like add `byte tick = 0;` into the constructor, and a `if (tick = X){procedure; tick = 0 }else ++tick`

**Comment by draknyte1** [comment]
Oh, I thought that was forestry we were forking? 🤷🏻‍♂️ My bad.

**Comment by richardhendricks** [comment]
I think it would be better to be random, not a tick.  Because then everything's fine except when that tick occurs then BOOM all the block updates happen at once.

Or combine both, instead of setting tick=0 in the constructor, set tick=rand(X).

**Comment by K1ngMX** [comment]
I did deactivate the butterfly stuff once, but that also lead to not working forestry machines (i remember that the thermionic fabricator did not work, i enabled butterflies, restarted => it started working). That was a couple of versions ago tho.

The problem with butterflies is really the whole "i fly to unloaded chunks" thingy. Im fairly sure having a sky base makes it worse (i have one), because they spawn on my base and fly pretty far. If they spawn near normal levels they get more easily trapped in some random hole / between trees etc. My infestions were pretty bad at times, but got better when i deactivated most of my auto apiaries, i *think* the apiaries themselves are spawning butterflies themself, because otherwise i wouldnt notice a difference (all trees on land levels are mutated in my world).

Would love to simply deactivate them, but as said, some forestry machines did also stop working last time i tried.

As for the lag itself, i cant say i have lag just from the polinated trees. But when i get a bit away from my base into the butterfly wall, well.... insta freeze

**Comment by richardhendricks** [comment]
Well I don't think you'll see lag right away from the trees, but I suspect they might be a source of garbage collector lag, ie the freezes I seem to get every few minutes.  Lots of leaf blocks checking *every tick* and creating/trashing local variables -> rapid memory consumption I'm guessing.

**Comment by richardhendricks** [comment]
ie, 5000 leaf blocks, 20t/s, generously say 8 bytes per block, = 800kb/s of memory pollution.

hmmm, assuming ~2GB of memory free, that's a GC cycle every 40 minutes.  But there's other mods doing their thing too I suppose.  

And 5k leaf blocks really isn't that many tbh, only a cube 17x17x17.  And probably more than 8 bytes/block update too.

**Comment by richardhendricks** [comment]
Bee pollination doesn't create butterflies <https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/apiculture/genetics/Bee.java#L714>

**Comment by K1ngMX** [comment]
i dont know, all i can say that i had significant less butterflies spawning (i regulary do `/cofh killall butterfly`) when i deactivated like 80%+ of my apiaries on my island

**Comment by K1ngMX** [comment]
but of course not measured precisly

**Comment by richardhendricks** [comment]
To clarify, we talked in Discord, he said this was not near any treefarms etc that might be getting pollinated.  It is interesting that they bias the "pollination field" for bees so that the hive is not at the center <https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/apiculture/genetics/Bee.java#L729>
I think this means the hive tends to pollinate downwards but it needs to be tested.

**Comment by richardhendricks** [comment]
Action items:
- Confirm bee hive pollination direction and effects - do the apiaries themselves cause more butterfly spam?
- Does disabling butterflies break forestry machines?
- Does having large number of pollinated leaves cause excessive java garbage collector actions?
- Other options to keep butterflies but lessen their effects?

**Comment by richardhendricks** [comment]
Well, based on a little research, I don't think the leaves are causing garbage collector work since the variables look like local variables on the stack.

**Comment by temp1011** [comment]
Hmm. There have been quite a few performance improvements to forestry (eg - see https://github.com/ForestryMC/ForestryMC/issues/1071) and forge (eg - see https://github.com/MinecraftForge/MinecraftForge/pull/4281/files) that would help with this. Maybe they can be backported?

**Comment by draknyte1** [comment]
> Backporting Forge Fixes

Probably not. 😅
I say we just fork forestry and fix it ourselves~

**Comment by temp1011** [comment]
You could do. If you have crashes though those should be fixed. I don't think 1.7.10 will get new features. I could look into trying to backport some stuff this weekend maybe... Either way it's LGPL so it'll be fine.

**Comment by draknyte1** [comment]
Unless you're forking Forge and we're going to run custom forge, backporting the forge fixes is outside of most GTNH Dev/contributors capabilities. Lel

If you can give reason, discuss backports to forge with @Mezz and something may happen. I mean, I got backported from 1.12 to 1.10/11, no reason to exclude 1.7.10 when it's still well played. 

Easier to fork forestry and just backport the butterfly fixes or make our own. Just my two cents.

**Comment by richardhendricks** [comment]
Check out sampler to hunt down memory/tps leaks
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/

Well, if we confirm these are an issue, we can warn players at the least.  Bottling up their forestry wood/bee farms might help prevent them converting half the world to forestry leaf blocks.

One interesting tidbit - My home biome has a mix of oak and birch with vanilla leaves, so forestry can definitely cross-pollinate with the two of them.  When I tried setting up a test world, the biome was BoP trees with BoP leaves, which apparently doesn't get cross-pollinated with Forestry.  So  a suggestion might be to have players place BoP trees around them to prevent butterfly explosions.

**Comment by richardhendricks** [comment]
Look at how butterflies are spawned and controlled. Looks like it should be fairly straightforward in EntityButterfly.java, AIButterfly, and Butterfly classes in Forestry.

Basic problem is that limits on the number of entities only applies to loaded chunks - if a chunk unloads or a butterfly moves into an unloaded chunk, it doesn't count against the limits.

Ideas, listed in preferred order:
* Lower lifetime ticks -  currently 1 minecraft week (!) - This is a biggie, and probably the major source of our problems. 
* Disallow spawning on fertilized/pollinated leaf blocks - no monarch waves! (OnRAndomLeafTick)
* Lower flying speed 
* Disallow fertilizing non-forestry leaf blocks
* Add a configurable MaxButterfliesOnServer, if a new butterfly is loaded from a chunk or spawned, kill it immediately. Could cause them to be stuck around players always on. Could be done per chunk, or larger area - say limit to XX butterflies in an 8x8 chunk zone.
* Add in a "loaded" counter - once it has loaded/unloaded X times, despawn 
* Add in a "spawning block" distance control, do not wander more than X blocks away

I like the first three options. Lowering their ticks and slowing them down will prevent them from getting to a chunk boundary and unloaded. Disallowing spawning on pollinated leaf blocks means that butterflies cannot "spread" across a forest. 

Disallowing fertilizing non-forestry leaf blocks is a little more severe, but does the same thing.

Other options require more code effort to implement.

**Comment by richardhendricks** [comment]
@mitchej123 Can we consider this closed with your changes?

**Comment by mitchej123** [comment]
I think so.  Between leashing butterflies to their home, and mitigating the NW bias this should be fairly well addressed.
