### ISSUE TITLE
Ethanol production with forestry fermenter costs too much energy

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#2890]
#### Which modpack version are you using?
2.0.3.0

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
I tried to use the forestry fermenter + still to make ethanol from plants for energy production.

#
#### What happened instead? (Attach screenshots if needed)
Making ethanol costs more than the ethanol gives you when you burn it inside a combustion generator.
For Biogas production the ratios are fair - You can use centrifuge + distillery + gas turbine to produce energy from plants (e.g. potato).

I think the problem is that the forestry fermenter costs too much to operate while not producing much biomass - the fact that biomass then needs to be converted to ethanol doesn't make it any better. No matter what the input, the fermenter always usees 2640EU.

I did some math (assume LV for efficiency):

Biogas production:
1 Potato + 1440 EU -> 36L Methane
125L Methane + 160EU -> 375L Biogas
1000L Biogas -> ~29000EU

Calculating the efficiency:
1L Methane costs 40EU
3L Biogas cost ~42EU
1000L Biogas cost 14000EU (15000EU profit)

Ethanol prduction:
1 Potato + 2640EU + Fruit Juice -> 30L Biomass
40L Biomass + 384EU -> 12L Ethanol
1000L Ethanol -> ~160000EU

Calculating the efficiency:
1L Biomass costs 88EU
1L Ethanol costs 296EU
1000L Ethanol cost 296000EU (136000EU loss)

As you see, the ratios are far off. Making methane is useful, making ethanol is way too expensive. Can't we have a way to make biofuel(ethanol) for energy production? I'd appreciate that.

Also, currently there's next to no reason to use for example berries in the forestry fermenter. Gives you  1/5 of the biomass a sapling gives you, but costs the same to make. Just not worth it.

#
#### What do you suggest instead/what changes do you propose?

Maybe adjust the ratios, so it doesn't net you a loss when you're making ethanol from plants.

**Comment by Wolozo7** [comment]
1. Not directly your issue, but since you used it as an example: you lose energy by turning your Methane (104k EU per Cell) into 3x Biogas (29k per Cell). 
2, For an adequate comparison, I'd suggest looking at the GT way to make Ethanol from Fermented Biomass from Bio Chaff from Plant Mass etc. That process becomes energy-positive at the very least once a Distillation Tower is used.
The fact that the Forestry machines are so cheap is probably misleading, making people use them while there are more expensive yet more efficient alternatives in the GT machines (which the pack should probably encourage to use over Forestry ones). 
I'm not opposed to making the Forestry machines more useful, but honestly don't really see the need. Methane, Ethanol and Biodiesel have sufficient burn values to make energy from plants / trees / fish worthwhile.

**Comment by DarkShadow44** [comment]
1) Oh right, took the values from a wiki and just assumed it was more efficient this way in this pack too. (Although it only gave 89000EU per methane cell)

2) I didn't calculate it fully through yet, but if, there is only a small gain. Compared to biogas, this setup seems pretty complex and not gets you much. I can add detailed calculation tomorrow.

**Comment by Dream-Master** [comment]
@DarkShadow44 make suggestions i possibly can add or change recipes then.

**Comment by sthegreat** [comment]
Imo they're good. It's already energy positive if you use forestry saplings, and anyways the best way to use it is probably to make biodiesel before you have mv for methanol manufacturing, which needs only a little so energy needed is not a hige concern.

**Comment by Dream-Master** [comment]
i mean Forestry recipes @sthegreat

**Comment by DarkShadow44** [comment]
Just tried making ethanol with gregtech machines and biochaff - 64Potato + 88678EU -> 450L ethanol (net loss of 16678EU). That's without Distillation Tower and ony LV Macerator, since I can't make that yet...

Since you asked me for an idea for a change:
An idea would be to reblance the fermenter and the "biomass to ethanol" conversion rate.
My idea would be:
- Turn conversion rate from "40L biomass to 12L Ethanol" to "40L biomass to 20L Ethanol".
- Double the biomass output for fermenter recipes
- Increase time for fermenter recipes: 0.4 seconds per 1L biomass
- Change energy usage for fermenter recipes: 20EU per 1L Biomass

Example calculation for potato (remember, with biogas 1 Potato is worth ~2460EU)
1 Potato + Water + 800EU -> 40L Biomass
40L Biomass + 384EU -> 20L Ethanol
20L Ethanol -> 3200EU (net gain 2016EU, taking 16 seconds)

This way it's similar to biogas, and other plants (all harvestcraft crops) are also viable for usage as biofuel.
Since this only affects forestry biomass, and not gregtech biomass, it should not affect other things too much. Also, making biochaff still gets you more fermented biomass out of it.
Hope that's possible with forestry fermenter, if not, we could always use the gregtech fermenter.

It's only a suggestion though, but it seems fair to me, making biofuel viable again while (hopefully) not breaking something else.

**Comment by bartimaeusnek** [comment]
Just don't use forestry machinery imo.

**Comment by DarkShadow44** [comment]
Then why have them?

**Comment by sthegreat** [comment]
Use them (or gt) to get ethanol for ethylene, biodiesel, or I think genetics needs a little. Don't use it for power unless you have forestry trees.

**Comment by DarkShadow44** [comment]
Why can't it be usable for power too? Turning plants into fuel gains more energy than it costs - It would make sense, no? It's easier than also collecting the other resources to make biodiesel - even if it's not as efficient.

**Comment by Dream-Master** [comment]
@DarkShadow44 can you suggest which forestry recipe need to be changed with values please. Thanks

**Comment by DarkShadow44** [comment]
I've created a pull request at https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/37 with a working change.
Basically, I did what I suggested in comment https://github.com/GTNewHorizons/NewHorizons/issues/2890#issuecomment-385711128.

For more information on how exactly it works, please check out the pull request.
How does that look?
