### ISSUE TITLE
Scheelite, Tungstate Quest

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2891]
#### Which modpack version are you using?
2.0.3
#
This quest in Tier 5 won't accept Ores from Mars satellites.

**Comment by Dream-Master** [comment]
I can choose only one type of ores. the red one, the grey one etc.

**Comment by Dream-Master** [comment]
I can do an additional Quest with stone ores if this helps? @nikitinalexx

**Comment by nikitinalexx** [comment]
I think this is okay. But keep in mind that if people spend time and find veins on both planet,s they will complete both quests.

**Comment by Dream-Master** [comment]
It will be a OR quest so do Quest one or two to get far more in progression. You dont need to make both but you can. @nikitinalexx

**Comment by Bryfer** [comment]
Seems easier to make a quest for crushed ore in that case?
Different stones types does have the same item Id after they are crushed, right?

**Comment by Dream-Master** [comment]
Yea that works too.
