### ISSUE TITLE
Circuit Assembler's bug

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#2892]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I am trying to put microprocessor to EV Circuit ASSembler by AE network
#
#### What happend instead? (Attach screenshots if needed)
It cannot be putted to that machine automatically

**Comment by 0lafe** [comment]
Weird, I never had that issue. Does it let you put other stuff into it?

**Comment by Dream-Master** [comment]
A few pictures would be nice to see what you did. @barsikus007

**Comment by Dream-Master** [comment]
Yes the ore dict issue in assembler and maybe circuit assembler must be fix too.

**Comment by boubou19** [comment]
I was trying to help barsikus on delta about that and the thing is you can only put the microprocessors by hand no matter if you uses AE interfaces or item conduits taking items from a chest.
