### ISSUE TITLE
NEI wrong recipe

### ISSUE THREAD

**Issue by bashduude** [GTNewHorizons/NewHorizons#2895]
#### Which modpack version are you using?
2030
#
![image](https://user-images.githubusercontent.com/32778092/39605311-9012a320-4f38-11e8-85a3-48c9e5eab3f2.png)

Iron Capped Greatwood Wand shows wrong recipe in NEI.

It supposed to show stainless steel bolts and lich bones as well

**Comment by Dream-Master** [comment]
Sadly i can't remove it via Modtweaker so i need help to remove it via code.

**Comment by bashduude** [comment]
Well i'd didnt bother then, kinda affects nothing. Just a bit confusing when you putting this recipe in the grind and wondering why its not working :)
