### ISSUE TITLE
NEI error

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#2896]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Everytime NEI search finishes (so basically every time you open inventory +5 sec) this spams the log tons of times, probably eventually hogging up the client and creating freezes.
https://pastebin.com/VAkm8reX

Any idea what it could be? Is it on my end? (I do have Fastcraft, Optifine and Schematica added)

**Comment by draknyte1** [comment]
How about you post a full log, because the one you shared is useless? Nothing we can do about NEI issues though. 🤷🏻‍♂️

**Comment by Methes** [comment]
https://drive.google.com/file/d/1MnjoFda50vfW3jJaieOcfmwftndnuST0/view?usp=sharing

Too large for pastebin it seems.

**Comment by richardhendricks** [comment]
Looks like this issue, please try the new version of SuperTiC and see if the logspam still occurs

https://github.com/GTNewHorizons/NewHorizons/issues/2766

**Comment by Methes** [comment]
Updated to 1.2 and so far so good. Thanks. Will report if it comes back.

**Comment by bartimaeusnek** [comment]
will close when 2.0.3.1 is out
