### ISSUE TITLE
Creative Menu CTD

### ISSUE THREAD

**Issue by Drecondius** [GTNewHorizons/NewHorizons#2897]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
SP and MP, server doesn't crash, only client.
#
#### What did you try to do, and what did you expect to happen?
 I opened the Creative Menu and clicked the Search button trying to search for blocks to build a spawn.
#
#### What happend instead? (Attach screenshots if needed)
Crash to Desktop. No message, No nada, It required termination of the launcher.
#
#### What do you suggest instead/what changes do you propose?
I'm not sure, It may be related to the issue where some people are lagging out / crashing when simply opening NEI due to a bug in another mod. I have my log here
[crash-2018-05-04_18.58.46-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1976114/crash-2018-05-04_18.58.46-client.txt)

**Comment by richardhendricks** [comment]
Try using NEI cheat mode instead of Creative search button.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2768
