### ISSUE TITLE
[config][suggestion] tooltip for travel anchors and minor cooldown tweak

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#2899]
#### Which modpack version are you using?
2.0.3.0

Travel anchors have a 10 second cooldown before you can use them again (confirmed by looking up the config). The idea of a cooldown is fine imo since you could otherwise travel super fast by placing them in a row (radius 128 blocks).

1. I would suggest lowering the cooldown to 8 seconds (160 ticks) since it makes them a little more handy to travel around your base (their intended use) while not making them too fast when you place them in lines. 128 blocks / 8 seconds = 16 blocks/second.

2. This one is more important since I had to look up the config to find out:
Add a tooltip to them containing the cooldown time so players will be aware without checking the configs or asking.
I am pretty sure they have no cooldown by default but that's not the best idea. Since we changed it we should have a hint in form of a tooltip.

**Comment by Dream-Master** [comment]
I am ok with a tooltip but why 8 instead of 10 secs?

**Comment by WarlordWossman** [comment]
The 10 seconds seem like a little too long, we end up not using them when you only want to go into your cleanroom once to start some machines and have to wait until you can teleport back.
Could be even lower if you don't mind them being a travel option but currently you use them for one way and walk back the other if you don't need to stay at that place.

**Comment by noobyaran9** [comment]
I'd say 5 second is a good number, and also we can tweak the range of the block down by half maybe.
Then there is a bug with the travel anchor where u cant access it out of render distance or smth like that.

**Comment by WarlordWossman** [comment]
Yeah I guess something like 5 seconds and 96 blocks would also work.

**Comment by noobyaran9** [comment]
Or force the player to use the staff for the anchor. And increase the power usage of the staff
# Number of RF required per block traveled using the Staff of Traveling.
    D:travelStaffPowerPerBlockRF=250.0

**Comment by WarlordWossman** [comment]
I think the 96 blocks and 5 seconds is fair and the staff just removes the cooldown. no point in getting them without the staff otherwise and they already cost quite a bit if I compare it refilling my copter pack with a bit of fuel.

**Comment by Wolozo7** [comment]
I doubt that lowering the CD by 2 sec would be a necessary QoL improvement. It's not like they are, as presented here, completely worthless without a Staff of Traveling. I'm not opposed to lowering the cooldown, but I can't really understand the thought process here. 
Btw, the RF cost is pretty much irrelevant due to the current availability of the Wireless Charger.

**Comment by richardhendricks** [comment]
Another option for the cleanroom is the open blocks elevator.  Only goes up and down, but it has 0 cooldown.

**Comment by 0lafe** [comment]
I personally use them only for other things. I had them in my old base to get to the thaum area because it was a little far away. I still use them in my thaum tower to go up levels because my stairs suck. I'd love a 5s cooldown instead

**Comment by richardhendricks** [comment]
Adding 5s cooldown info to questbook
