### ISSUE TITLE
GalacticGreg Issues with Version RC2

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#290]
Add a config option where Ores and Small ores can be enabled to spawn on the surface from moons and planets in Galactic Greg.

**Comment by Dream-Master** [comment]
When i fly in the Kuiper Belt i see only Asteroids full of small tungstate ore. Normally tungsten spawns from level 20 to 40 but in the Kuiper Belt i found it in every high. (Tungstate is enabled in the config) i did not see any other Ore here.
Another thing. On the galactic Craft Asteroids i can see Asteroids generating there but they completely empty so not any ore here.
And the spawn rate is very low but this i can change maybe with the config.
Maybe i did something wrong.

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/eswfrspi5y4tzln/Screenshot%202015-08-07%2011.43.17.png?dl=0
https://www.dropbox.com/s/tn9qz8mlule7et9/Screenshot%202015-08-07%2012.01.54.png?dl=0
https://www.dropbox.com/s/m7naqlcqz4jedz6/Screenshot%202015-08-07%2012.01.42.png?dl=0

**Comment by Dream-Master** [comment]
btw Europa have now Oceans and not need Ore spawns there any more. the Europa Dungeon is on Io now.
(Version 2.4)

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/t3jm0kd5trh2zng/Screenshot%202015-08-07%2012.01.56.png?dl=0
https://www.dropbox.com/s/qdffe63gmit5m6w/Screenshot%202015-08-07%2012.09.34.png?dl=0

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/z196opz6xtt6rda/Screenshot%202015-08-07%2012.11.01.png?dl=0
https://www.dropbox.com/s/t3jm0kd5trh2zng/Screenshot%202015-08-07%2012.01.56.png?dl=0

**Comment by Drobac** [comment]
Told this to Namikon, he said that GG needs tweaking and that atm its set in the config that the asteroids are netherrack. Said hell work on it when he gets back

**Comment by Dream-Master** [comment]
It is not a rush message it is only what i find out because the last time i teted only Planets not Asteroids.

**Comment by Namikon** [comment]
Ok, so there are multiple things to keep in mind here. I'll just list them in random order
- The "only small-ores" problem is mainly caused by all ore-veins being set to =false in the config. Asteroids will always spawn, even if no valid ore configuration can be found. Small ores are totally different to normal ores, as they will always get triggered upon asteroid generation.
- The Netherrack-Asteroids origin from the default config for vanilla (see this function body https://github.com/GTNewHorizons/GalacticGregGT5/blob/master/src/main/java/bloodasp/galacticgreg/ModRegisterer.java#L88) So everything is working fine here. Empty asteroids will only occur if there aren't enough ore-veins enabled. But we've already talked about that, we'll create our own modpack specific definition in the coremod. (Soon (tm))
- If you don't want ores in Asteroid dimensions between 1-250 and only in their specified range,  make sure "obey-height-limits" is set to true. I introduced that option, as it is not guaranteed that Asteroids will spawn on every y-level, and some ores might never generate (We had that problem already with naquadah)

So the only thing that you could check right now is: Make sure the kuiper-belt has ore veins enabled. The only thing I can imagine is, there might be a typo somewhere (Either in GGreg or GalaxySpace) in the dimension name and/or provider (Kuiper, Kupier, Kurpier,..) But then, nothing should be generated at all. A rather strange situation to be honest. You can also enable trace-mode and investigate the logfile if the oregen is executed or not

**Comment by Dream-Master** [comment]
It is only a reminder not a "you have to do it now" message.
Will see what i can do.

**Comment by Dream-Master** [comment]
I change the height of Meteoric iron to 50-70. So it is not necessary to see this or on the surface it is only a nice to have feature.

**Comment by Dream-Master** [comment]
So tested Moon and Mars Tier 1 and 2 everything now ok!
Red Ores (Redgranite style) looks good on Mars.

**Comment by Dream-Master** [comment]
Ok now i turn o n some small ores and some mixes. In the Asteroids Dimension i get only Asteroids full of Titanium nothing else.
I turn on this too "obey-height-limits".
Now i try to disabled all small ores and test it only with mixes.

https://www.dropbox.com/s/fvusdbhynbcrnre/Screenshot%202015-08-08%2015.08.39.png?dl=0
https://www.dropbox.com/s/nooh8brivsxzgf8/Screenshot%202015-08-08%2015.08.59.png?dl=0

**Comment by Dream-Master** [comment]
So with Oremixes only enabled (all small ore to false ) the Asteroids are empty.
Now i try with enable debug messages.
https://www.dropbox.com/s/x5oqo8gu5zy1hpt/Screenshot%202015-08-08%2015.24.29.png?dl=0

**Comment by Dream-Master** [comment]
``````````````````````````````````
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Triggered generate: [ChunkGenerator micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids@1af40c44] [Biome asteroids]
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Selected DimDef: [GalacticraftMars_Asteroids]
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Running asteroid-gen in Dim GalacticraftMars_Asteroids
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Asteroid probability: 200
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Leaving asteroid-gen for Dim GalacticraftMars_Asteroids
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Triggered generate: [ChunkGenerator micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids@1af40c44] [Biome asteroids]
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Selected DimDef: [GalacticraftMars_Asteroids]
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Running asteroid-gen in Dim GalacticraftMars_Asteroids
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Asteroid probability: 200
[15:50:03] [Server thread/TRACE] [GALACTICGREG/]: Leaving asteroid-gen for Dim GalacticraftMars_Asteroids

````````````````````````````````````````````

**Comment by Dream-Master** [comment]
``````````````````````````````````````````````
Line 70462: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Triggered generate: [ChunkGenerator micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids@1af40c44] [Biome asteroids]
	Line 70463: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Selected DimDef: [GalacticraftMars_Asteroids]
	Line 70464: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Running asteroid-gen in Dim GalacticraftMars_Asteroids
	Line 70465: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Asteroid probability: 200
	Line 70466: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Generating asteroid NOW
	Line 70467: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: About to select oremix
	Line 70468: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Using Oremix ore.mix.gold for asteroid
	Line 70469: [15:49:18] [Server thread/DEBUG] [GALACTICGREG/]: Asteroid will be build with: Block: [minecraft:netherrack] OreType: [Netherrack]
	Line 70470: [15:49:18] [Server thread/DEBUG] [GALACTICGREG/]: Done with Asteroid-Worldgen in DimensionType Asteroids. Generation took 267 ms
	Line 70471: [15:49:18] [Server thread/TRACE] [GALACTICGREG/]: Leaving asteroid-gen for Dim GalacticraftMars_Asteroids`
``````````````````````````````

**Comment by Namikon** [comment]
Seems to be ok. All asteroids are empty?

**Comment by Dream-Master** [comment]
Without small ores empty with small ores enabled only one type of small ores. (titanium on Asteroids and chromite on the Kuiper Belt) The debug funktion i run only with small ores disabled.

**Comment by Dream-Master** [comment]
So what i can do next?

**Comment by Namikon** [comment]
Hm, ok, the log is missing the oregen entry completely. Maybe it's again one of those hidden exceptions that I had already. I will investigate this

**Comment by Dream-Master** [comment]
@Namikon I stopping testing now wait you come back.
Enjoy your holiday it is not urgent. tier 1 and 2 works well.

**Comment by Dream-Master** [comment]
@Namikon 
If you have time to coding maybe fixing Galactic greg as next thing.

**Comment by Drobac** [comment]
I can haz moonbase?

**Comment by Dream-Master** [comment]
If we want to change small ores be on the surface  not now. I am not sure if i change the high on the server. Did you find small meteoric iron on moon ? If we let it that ores be only generated in the inner rock of a planet and moon you can build your base.

**Comment by Drobac** [comment]
Found them but inside the crust, not on the surface

**Comment by Dream-Master** [comment]
Above Levl 50 or 60?
We not have it in the crust yet .

**Comment by Namikon** [comment]
Don't get too excited :) 
The commit is only (at least in my test environment) solving the issue with empty asteroids. The problem / feature with small ores within the surface block area is a totally different approach and takes quite a few changes. I do have a basic concept, but it's not done yet.

**Comment by Namikon** [comment]
Speaking of, why do we need ores to spawn in the top layer? That would be against "normal" MC behavior

**Comment by Dream-Master** [comment]
I don't say we need it. Fixing the asteroids dimension would be enough I think.

**Comment by Namikon** [comment]
It's not that it is impossible, it's just that the top layer(s) are pretty thin. The amount of small ores that would show up there would be rather small if small ores are only meant to spawn there. If it's meant to be as an additional spawn location, well, then it makes no sense to me. The layer(s) are just too small to have any noticeable change in the amount of small ores that would show up

**Comment by Dream-Master** [comment]
I agree. I think only the Asteroid dimension need to be fixed.

**Comment by Namikon** [comment]
That should be fixed with the latest commit. (It works in my dev environment) When I have some spare time today, I will try to verify it within the testpack.

**Comment by Dream-Master** [comment]
Ok will try when I come back home at 7-8..

**Comment by Dream-Master** [comment]
Not tested yet but i will hopfully today. After this i will update the Pack.

**Comment by Drobac** [comment]
Give me a heads up if youll be reseting any dimensions

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
I think this works now. If not reopen it.
