### ISSUE TITLE
Quest #36 Recommendation

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2901]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
SOLO
#
#### What did you try to do, and what did you expect to happen?
Quest: Tier 0.5 - Stone Age: Important tools: ID 36
I already had a soft mallet from tier 0. I used it to make the bed which made it take durability loss. It didn't count towards this quest.
#
#### What happend instead? (Attach screenshots if needed)
Might be nitpicking but I felt like it should have applied to this quest as well.
#
#### What do you suggest instead/what changes do you propose?
Is there any way to make it so quest ID 36 doesn't require you to make another mallet?

**Comment by bartimaeusnek** [comment]
i think we already changed that, but im not sure

**Comment by Dream-Master** [comment]
@bartimaeusnek @shawnbyday its fixed allready.
