### ISSUE TITLE
Nasa Workbench Schematic Tier 3 should accept any EV-tier circuit

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2905]
#### Which modpack version are you using?
2.0.3
#

Right now Nasa Workbench Schematic may be crafted only with Workstation in assembler. Can we add recipes with other circuits?

**Comment by Dream-Master** [comment]
@nikitinalexx any suggestions ?

**Comment by Zoko061602** [comment]
#2856 
I think it would make more sense to use Data Sticks insted of circuits.

**Comment by nikitinalexx** [comment]
@Dream-Master i mean we have some types of EV circuits, so they should be interchangeable for this recipe

**Comment by Dream-Master** [comment]
if someoen can make a mechanic to put data on data sticks (nbt data for ech tier) i am for the change @Zoko061602 @nikitinalexx
