### ISSUE TITLE
Cheaper Buildcraft Power Pipes

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2906]
#### Which modpack version are you using?
2.0.3.0
#
#### What did you try to do, and what did you expect to happen?
I wanted to build some Kinesis Pipes, hoping there is a cheaper recipe.
#
#### What do you suggest instead/what changes do you propose?
Add Assembler recipes that, require only half as much glass panes and rods. (Maybe 120EU/t for 5s )

**Comment by WarlordWossman** [comment]
Idk they are lossless as far as I know and you can power RF things with GT cables.
Guess assembler should be cheaper than hand crafting but only a bit.
