### ISSUE TITLE
Quests Won't Complete: Wooden Crossbow ID 1151 + Iron Bolts ID 1156

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2907]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Did all the parts for Quest ID 1151: Wooden Crossbow. Expected to complete quest. The text in Better Quest shows "?fWooden Crossbow" which happens in some of the other Tinkers Construct mods but doesn't prevent completion.

Did the same for Quest ID 1156: Iron Bolts. Expected quest to complete. This one also displays as "?fIron Bolts".
#
#### What happend instead? (Attach screenshots if needed)
Quests wouldn't complete. I tried to make another crossbow and didn't complete again. I used BQ admin to complete quests to move on.
#
#### What do you suggest instead/what changes do you propose?
Fix? Not sure what is causing it. Is the odd text just a language file issue or does it show up that way for everyone?

**Comment by Dream-Master** [comment]
I do the quest in sp and it worked but I remember I fix it before. it will be in the next release.

**Comment by ZorbaHerbalist** [comment]
In 2.0.4.2 still/again doesn't completes.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3089
