### ISSUE TITLE
Crash with new GT/GT++ version in DEV Pack

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2908]
New GT version crash the Game with GT++

I tested with Gt++ pre 10 and 11 is the same.

Older GT version just work 

crash log:
[crash-2018-05-07_08.07.21-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1978687/crash-2018-05-07_08.07.21-client.txt)

fml log:
[fml-client-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/1978696/fml-client-latest.log)

**Comment by bartimaeusnek** [comment]
https://github.com/draknyte1/GTplusplus/pull/271 - NEI Crash on GT++ Recipes
https://github.com/draknyte1/GTplusplus/pull/259 - GT:NH Recipe Rebalance?

**Comment by draknyte1** [comment]
First is already merged in our dev test version. Didn't want to merge to git in case it didn't work. 

The secondary PR isn't finished.

**Comment by bartimaeusnek** [comment]
So we should wait for the first one only?
