### ISSUE TITLE
Crash with Osmotic Enchanter

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#2909]
#### Which modpack version are you using?
V 2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Use the Osmotic enchanter to enchant an Edge of the Primordials sword for luls. The enchants used were maximum level of Sharpness, Wrath, Knockback, Fire Aspect, Looting, Magic Touched, Disarming, Binding and Repair. A Creative wand (crystal studded cosmic neutronium) was used to provide the aspects.
#
#### What happend instead? (Attach screenshots if needed)
The enchanter ran for a moment, before crashing the game and producing the attached crash report. Upon reloading the game, the enchantment had completed. 
[crash-2018-05-07_12.56.09-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1979794/crash-2018-05-07_12.56.09-server.txt)

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2764
