### ISSUE TITLE
Quest 470 Berry medley Recommendation

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2911]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server and SOLO
#
#### What did you try to do, and what did you expect to happen?
I had already completed the knife in the stone age by doing the coke oven quest. Making the brick mold damages the knife and it will not register as complete for this quest.
#
#### What happend instead? (Attach screenshots if needed)
I had to make a new knife even though my old one only had one use on it.
#
#### What do you suggest instead/what changes do you propose?
Remove the part where it checks for knife damage so it can register the knife made in the stone age or later in case it takes you longer to complete the early quest.

**Comment by bartimaeusnek** [comment]
2 Flint and 1 Stick extra isn't too much. You'll need the extra knife anyways.

**Comment by shawnbyday** [comment]
No worries, I wasn't submitting because the materials are killing me or anything like that.
