### ISSUE TITLE
GT ores generate in Utility Worlds Void Dimension 

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2915]
#### Which modpack version are you using?
2.0.3.0
#
#### What did you try to do, and what did you expect to happen?
I created a utility worlds void dimension in creative.
#
#### What happend instead? (Attach screenshots if needed)
I saw a small copper ore in there.
#
#### What do you suggest instead/what changes do you propose?
Remove ore generation in utility worlds.

**Comment by bartimaeusnek** [comment]
please re-try with devpack once its public
