### ISSUE TITLE
More Bees

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#2917]
#### Which modpack version are you using?
2.0.3.0
#
#### Why you're writing this issue?
I made a few additonal bees.
#
#### What kind of bees?
- A sandwich bee that produces all things required for sandwiches
- enderium and stainless steel
- high level nuclear bees (thorium, lutetium, americium, neutronium)
- magic bees (thauminite, shadowmetal, unstable ingot, netherstar)
- bees for all space metals (from meteoric iron to black plutonium)
- one bee for each planet/moon, that produces the dust 
#
#### Do we have anything to do?
Yes. Since most bees have a very high tier, you have to add them to the coremod :( 
#

#### Screenshot
![bees](https://user-images.githubusercontent.com/32712367/39897873-88a264d2-54b4-11e8-8fe9-d1b0e0880611.PNG)
#
#### Files
[bees.txt](https://github.com/GTNewHorizons/NewHorizons/files/1993469/bees.txt)
[Bees.en_US.txt](https://github.com/GTNewHorizons/NewHorizons/files/1993470/Bees.en_US.txt)

**Comment by bartimaeusnek** [comment]
My opinion on this:
` A sandwich bee that produces all things required for sandwiches` - nice!
`enderium and stainless steel `- eh same as 0lafe.. i would prefer no compound materials in bee/crop drops.
`high level nuclear bees`  - thorium? nice! other? overpowered.
`magic bees` - shaddowmetal is okay. the others? overpowered.
`bees for all space metals` - pretty nice tho, except for trinium. that one is overpowered.
`one bee for each planet/moon, that produces the dust` - pretty nice i guess? but i have a bad feeling about T7-8 bees... might be overpowered...
`infinity Branch` - overpowered.

this reflects the idea of adding these kind of bees without changing the system as it is right now. a few Industrial Apiaries and world Accelerators and you get tons of the rarest materials once you unlocked gendustry.

**Comment by richardhendricks** [comment]
Gallium would be nice

**Comment by 0lafe** [comment]
>pretty nice tho, except for trinium. that one is overpowered.

oh thats what a space metal is? Not a huge problem. Trinium is one of the dusts you usually have a lot of dust of already, and the ingots are barely used. I'd be fine if there wasn't a trinium bee, but I don't really see a reason to not add it. 

>this reflects the idea of adding these kind of bees without changing the system as it is right now. a few Industrial Apiaries and world Accelerators and you get tons of the rarest materials once you unlocked gendustry.

Let's throw in some numbers here. Gendustry is at least LuV, unless you count needing the advanced mutatron, in which case it's ZPM. If you're in zpm, you probably can't afford over an amp of zpm just to speed up bees, so accelerators are left to IV and below. If you stretch it, you could probably do 8 apiaries with 2 accelerators for all the materials you need. Even with all 8 doing one thing, at 32x speed, with production upgrades, only making a tiny dust doesn't get you too much stuff. If the comb chance is low already, you're not looking at too many resources. Then there's the cost of centrifuging the combs. Naquadria combs that are mostly enriched naquadah, take 1A LuV. Anything too useful would probably take similar power, or more. So you're looking at 3A LuV for the accelerators, then another for the centrifuging, so an amp of ZPM to make, well, maybe 5-10k dust a day.

Now let's say instead you go with quarrying. Quarries are cheaper than apiaries for the most part, and doable in EV/IV. Dimensional transceivers were HV last time I looked at them, but might be EV now. Throw down 4 quarries in a dimension with the material you want, power them on 2-3 amps of LuV, use another amp of LuV to power the processing of the ores. Now you're looking at 50k+ a day, if the material you want happens to be copper though, you're looking at over 100k a day.

This is the problem with bees. The only time they win over a quarry is when the quarry can't make that materials (eggs, thaum stuff, TF boss drops, etc...), or when you need more than 4 quarries can provide, and are willing to lose the multiple amps of UV, and huge array of apiaries to set that up. 

Bees are good before you have a quarry, which is at the latest, IV. Gendustry takes LuV+, and running it takes about an amp of zpm. This isn't mid game stuff anymore, the amount of materials you get late game is absurd compared to the way it was before. 

That said, certus bees totally need a nerf. I got like 1.2M certus in no time at all.

Final thing, if you're adding new gt bees, a phosphor bee would be totally cool, and maybe even a sulfur one (even though it's 100% doable to make infinite sulfur from bee products, a sulfur bee would be cooler)

**Comment by bartimaeusnek** [comment]
@0lafe I think this discussion leads to far here. really trinium isnt rare? then i have mixed up with something with a similar name.

**Comment by 0lafe** [comment]
The white ingot, LuV to smelt, takes 1B argon, used for fusion and has the best ticon/gt mining speed? That's the one I mean

**Comment by Dream-Master** [comment]
Mutatron get a new recipe for banacing reasons (reminder for me)
