### ISSUE TITLE
Mod removed due confirmed crash: ZombieAwareness

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#292]
The Server just crashed 2 times in a row, both times caued by ZombieAwareness.
I had to remove the mod in order to get the Server back online again. Martin, please remove ZA from Solder for now

**Comment by Dream-Master** [comment]
We losing more and more Mob Mods. Maybe coroutil cause the crash. I think we have to use the recommended Version 1.11 and not 1.13 and test it before we throwing out all mods.

**Comment by Dream-Master** [comment]
https://github.com/Corosauce/CoroUtil/issues/5

**Comment by Dream-Master** [comment]
https://github.com/Corosauce/CoroUtil/issues/5#issuecomment-126958711

**Comment by Dream-Master** [comment]
Maybe we have to update Cauldron.

**Comment by Namikon** [comment]
KCauldron for forge 1492 is available, however in the forums someone already complained about fluid problems again. Feel free to test it on the testserver, but make sure you investigate the startup logfile this time. I won't be able to work on this the next 2 weeks

**Comment by Dream-Master** [comment]
We don't need to do it now.

**Comment by Dream-Master** [comment]
We have to looking for new Mob Mods.
