### ISSUE TITLE
No way to disable toggle-sprint?

### ISSUE THREAD

**Issue by ObZidianLP** [GTNewHorizons/NewHorizons#2920]
#### Which modpack version are you using?
2.0.4.0 _EDIT: Beta_
#
####
I can't find a way to disable the sprint-toggle. I've searched everywhere but I can't find anyone talking about this or what mod enables it.
#
My issue with this "feature" is that it works the other way around too. If I toggle sprinting on by accident, when I try to sprint by holding the button down normally, it instead toggles sprinting off and I can't sprint.

**Comment by Dream-Master** [comment]
@ObZidianLP did a log out and in again. Did you check the cotrols menu and look maybe sprint have use another key ?

**Comment by ObZidianLP** [comment]
@Dream-Master I tried restarting my game multiple times, re-installing the modpack, using Version 2.0.2.7 instead, bound all other keys to 'NONE' so there wouldn't be any conflicts. I even checked the Windows keyboard and accessability settings, but all to no avail.

**Comment by ObZidianLP** [comment]
Better description of the issue:
My sprint key works both normally, and like a toggle.
If I hit the sprint key after moving, it works how you would expect it to. However if I hit the the sprint key before moving - or on accident earlier than W - it toggles sprinting on. Which means whenever I move I automatically start sprinting. This is enabled until I press the Sprint key again while standing still.
Then there's the part about it working the other way around too; If I enable the sprint toggle and try to run normally, I move at normal speed instead.

**Comment by Dream-Master** [comment]
never had thi issue need help from my comunity

**Comment by ObZidianLP** [comment]
I found a way to fix it! I installed a mod called [ToggleSneak](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2621781-togglesneak-1-7-10-v3-0-5), made by jacob5565.
All I did was put it in the mods folder, then ingame I changed the options to make it behave like vanilla through the mods options GUI. Now sprinting works like normal again!

**Comment by WarlordWossman** [comment]
@Dream-Master maybe we should add this mod and set the values to restore the normal sprinting mechanics? So far I don't know if anybody has found out what causes the toggle sprint but more players are annoyed by it than people who actually like it.

**Comment by grompe** [comment]
GT++ is the mod that changes sprint key to toggle:

https://github.com/alkcorp/GTplusplus/blob/134467bda65e12d60a329de7b940d4c6455bb0fa/src/Java/gtPlusPlus/core/handler/events/CustomMovementHandler.java#L124

In fact, it says it borrows from ToggleSneak but the options aren't available to configure from any GUI or config.

**Comment by Methes** [comment]
Good job! This has irritated me for the longest time.

**Comment by AiramProvoker** [comment]
Hoping it gets fixed.

**Comment by richardhendricks** [comment]
This bug is also causing #5142 @alkalus Any update?

**Comment by richardhendricks** [comment]
@draknyte1 Any updates?

**Comment by draknyte1** [comment]
![FE33F43A-75A3-4420-9161-7A1E21D84377](https://user-images.githubusercontent.com/3060479/70349267-46141300-185c-11ea-9123-2fef665f2af9.png)

**Comment by Dream-Master** [comment]
2.0.8.0b using Build 394 because build 400 crash on servers. 
@draknyte1 is the fix in 394?

**Comment by draknyte1** [comment]
Obviously not, ass stated above.

**Comment by richardhendricks** [comment]
Fixed in 2.0.8.3
