### ISSUE TITLE
GT++ Power Station Power Cell recipes and other issues

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#2921]
#### Which modpack version are you using?
2.0.4.0

The higher tier power cells for the gt++ power station do not have a recipe.

The gui for the substation controller block is blank/not showing any information about the multiblock.

Further testing can't be done as I can not get the multi-block to form and the no gui for feedback
Have tried controller positions, top center, bottom center, front center, front 1 off the ground center.

**Comment by bartimaeusnek** [comment]
The gt++ power station is in a unfinished WiP state at the moment.

**Comment by Dream-Master** [comment]
@Anarack should i disabled it for now until it is finish ?

**Comment by bartimaeusnek** [comment]
```
Alkalus (GT++):
Actually, once its set up, the display turns on
The GUI is blank until then
GUI works, except the cell swap feature.
PSS logic works otherwise.
```
So i would say we leave it in as it is, but add a [WiP] tooltip?

**Comment by draknyte1** [comment]
I don't see the issue?

I'll have this finalized today anyway.

**Comment by Dream-Master** [comment]
ok
