### ISSUE TITLE
Superconducting Coil only crafted with UHV

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2924]
#### Which modpack version are you using?
2.0.4.0

Great to see a new version! 
I was waiting for the superconducting wire fix (#2749) to make the Fusion Reactor, but now the superconducting coil block can only be made using UHV wires. 
Previously LuV and ZPM were also available.
![image](https://user-images.githubusercontent.com/30087707/39956690-dbe49070-55e5-11e8-8993-ea69c0851e37.png)

**Comment by DualBallers** [comment]
Hmm, OK I see it mentioned in #2686. I can think of a couple of escalating ideas, so you can add the LuV and ZPM recepies again:

1. Make (dis)assembling from coil block to wire require higher level, e.g. +UV assembly voltage (~1 mil).

2. Make (dis)assembling require an expensive UHV fluid, maybe 432 neutronium (I'm only at LuV so is that an expensive material?). 
You need 2.6 ingots neutronium in tiny fluid pipes (3.5 pipes) to make the coil the UHV recipe way, so now converting back is even more expensive, by requiring 3 ingots more.

3. Combine 1 and 2.

![image](https://user-images.githubusercontent.com/30087707/39958602-815b7aae-5605-11e8-9704-4320d917505e.png)

**Comment by Dream-Master** [comment]
Disassembling recipes are autogenerated. I guess i cant change it but i need to check @DualBallers

**Comment by bartimaeusnek** [comment]
@Dream-Master we could remove the Disassembling recipe for this block.
