### ISSUE TITLE
GT Creates "fake user" under normal user name, FEPerm bug

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#2925]
#### Which modpack version are you using?
2.3.0

#
#### If in multiplayer; On which server does this happen? 
www.digtobuild.com / www.dirthuts.com

#
#### Recreate

Go on server, create plot, add Pump or Miner,  you will get AFK spam

Permission will be created, and the machine will run under the Permsision of the Current User who placed it's Username, but a NULL Minecraft UUID.

this creates a second user in the FEPerm with the same Minecraft User Name but a Null-resolved UUID:
a8862d87-7c1d-32b2-b1c1-bb13028a5a02

When the server restarts, FEPerm will find the two Minecraft User Names with different UUID's and crash the server

resolution is to remove the bad permission from FEPermission

Issue was tracked down to Greg Tech creating the user as a NULL user.

#

**Comment by devanchya** [comment]
this is related to an issue where the AFK message is spammed to the user as well.
If we could stop the AFK message this would be best.

**Comment by bartimaeusnek** [comment]
normal GT has the same code, i think this should be fixed on ForgeEssentials side, and honestly, i dont think we can do much on our side.. (see https://github.com/ForgeEssentials/ForgeEssentials/issues/2357)

**Comment by devanchya** [comment]
Plots bug can't be fixed without the GT fake user being set to a true fake user, OR the UUID used by it being a real UUID.

For the AFK issue, we edited ForgeEssentials and removed the whole AFK option to hack around the spam.

Issue can be closed or marked as "will probably never be fixed"

**Comment by richardhendricks** [comment]
Could we not create a UUID?  Or does it need to be a Minecraft.net valid UUID?
