### ISSUE TITLE
Broken recipe | Fixed

### ISSUE THREAD

**Issue by bashduude** [GTNewHorizons/NewHorizons#2933]
#### Which modpack version are you using?
2030

![image](https://user-images.githubusercontent.com/32778092/40013285-cf4d62e8-57b5-11e8-83b4-580eea6dd2df.png)

in script file Emt.zs

i've changed middle item of the recipe.
basicly item that was declared here is non-existant in the game,
all i did is added durability.
![image](https://user-images.githubusercontent.com/32778092/40013397-18866d56-57b6-11e8-9bb3-9aaf95193dea.png)

**Comment by bartimaeusnek** [comment]
can you do " EMT:ElectricBootsTraveller:* "?
