### ISSUE TITLE
Extruder Shape (Shaft)

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#2934]
Es macht keinen sinn, das bei einem Shape das nur ein größeres Loch hat dafür mehr Material zu verwenden.

Mein vorschlag:
Extruder Shape (Rod) in die MV Lathe (120 EU) für 60 sek dann sollte das rauskommen.

Das heißt man dreht in der Drehmaschine ein größeres Loch.

**Comment by Dream-Master** [comment]
Da das Gt++ code ist muss ich Alklaus mal fragen.

**Comment by bartimaeusnek** [comment]
Translation into english:

DragScorpion:
It makes no sense, that the shaoe with a larger hole in the middle nees more material. 

My Suggestion:
Extruder Shape (Rod) into the MV Lathe (120 EU) for 60 sec, that should produce it.

This mean that the Lathe is drilling a bigger hole.

Dream-Master:
Thats GT++ code, i have to ask Alkalus.



@draknyte1

**Comment by draknyte1** [comment]
Games don't have to make sense?

**Comment by richardhendricks** [comment]
Does an MV lathe have any other uses?  I haven't need one yet at EV.

**Comment by codewarrior0** [comment]
MV Lathe is kind of useless, yeah. The LV Lathe makes lenses from exquisite gems, and the HV Lathe makes lenses from gem plates (which itself is kind of underused ever since you can upgrade gems in the laser engraver).

**Comment by richardhendricks** [comment]
You can imagine the mold is much larger than the normal mold, that's why the hole is bigger but still needs more material.
