### ISSUE TITLE
Titanium Quests (suggestion)

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2936]
#### Which modpack version are you using?
2.0.3.0

In the Titanium Finally quest in the HV Tier, it tells you that you will be able to obtain pure titanium ore on mars, but it can already be found on the moon.

####Suggestions
The Rutil quest needs a HV Thermal Centrifuge which is some kind of an overkill, you only need a lv one, so not sure if a main quest should require on of those.

Enable a second way for the main quests, so you can obtain Titanium ore and dont need to do the rutil processing (thinking of two ways to reach the Titanium Finally Quest)

**Comment by Dream-Master** [comment]
I want show people how rutile process works. After this quest they can decided how to obtain titanium. I could change  or remove the thermal centrifuge if that realy helps.

**Comment by richardhendricks** [comment]
The moon reference is already fixed on master.

**Comment by Dream-Master** [comment]
Yes the Quest text is fixed and i show people onec to het Titanium out of Bauxite. Finding Titanium Ore Quest i could add also as an additional quest.
