### ISSUE TITLE
[Quest] [Suggestion] "Indium" quest requirements

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#2938]
#### Which modpack version are you using?
Latest as of May 14th 2018
#

#### What did you try to do, and what did you expect to happen?
Quest in EV tier "Indium" requires:
9 + 27 ores and 36 sulfuric acid for step 1
4 aluminum dust for step 2
1 indium dust for step 3
#
#### What happend instead? (Attach screenshots if needed)
the quest asks for enough ores and sulfuric acid, but...
4 aluminum dust is only enough to make 1/9th the required amount of indium for the quest
#
#### What do you suggest instead/what changes do you propose?
require 36 aluminum dust in step 2

**Comment by Dream-Master** [comment]
will check
