### ISSUE TITLE
[Suggestion] Make Travel Anchor's Great Again

### ISSUE THREAD

**Issue by BlackAce21** [GTNewHorizons/NewHorizons#2939]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
Used a travel anchor, expect it to not have a cooldown.
#
#### What happend instead? (Attach screenshots if needed)
 It did xD
#
#### What do you suggest instead/what changes do you propose?
I propose removing the cooldown completely back to default. Limiting the cooldown doesn't server a purpose especially since the staff of traveling bypasses it (unless you want to force people to use the staff) which seems silly. For purposes of general quality of life I think removing the cooldown makes more sense but I honestly don't know if there may have been a viable reason this cooldown was added in the first place and if there was, my bad and I would love to know what it is xD if there isn't though, lets change it back on pack defaults ^_^

**Comment by Dream-Master** [comment]
@noobyaran9 thats true but i ask him to open up a issue to set the value to 0.

**Comment by BlackAce21** [comment]
having just read #2899 , I am still completely lost on why this was even a thing....nerfing them so you can't move super fast?? Is this real life? speed buff + sigil of speed + draconic armour = speed so fast you can time yourself out from chunk loading in a single player game....

Most people, myself included, use this as a means of navigating large and complex bases more then a form of transport over long distances (since ya know, thaumcraft gateways can travel infinite distance instantly as can stargates and 20+ other forms of transport) and putting on a cooldown does nothing but force the use of a staff of travel which just takes up an extra inventory slot in a pack with more then enough to occupy the inventory already even with backpacks etc. I still heavily support a change back to 0 second cooldown as default.

**Comment by WarlordWossman** [comment]
Not like you get the gear you talk about easily, this pack is taking balance rather serious and the staff of travel is always an option like you said, so no cooldown of 0 needed.

**Comment by richardhendricks** [comment]
It's also about progression.  Insta high speed teleporting would negate alot of the use of the items granting speed like boots, or better jetpacks.

**Comment by Dream-Master** [comment]
i lower it to 2 secs

**Comment by richardhendricks** [comment]
Will need to change quest text as well, it mentions the 5s cooldown.

**Comment by Dream-Master** [comment]
ok
