### ISSUE TITLE
Void seed (Thaumic Bases)

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/NewHorizons#2940]
#### Which modpack version are you using?
2.0.4

in a new update, the recipe for void seed(from thaumic bases) is complicated. The problem is that the recipe has no logic and explicit justification, for which the recipe now requires all the plants of mod + very many different aspects. For some aspects, 32 platinum are needed per 1 recipe. Void seed does not have such a great value to make it so complicated.

#### What do you suggest instead/what changes do you propose?
return old void seed recipe or simplify the current to an adequate level

**Comment by Dream-Master** [comment]
The old recipe was a vanilla recipes and need a change. I will check the recipe to find out it is real grindy or not.

**Comment by noobyaran9** [comment]
Same goes to farming the eldritch mob.

**Comment by Dream-Master** [comment]
ok i check it.

**Comment by Vernam** [comment]
@repo-alt, it produse onlu core for void ingot. 
there is a difference

**Comment by noobyaran9** [comment]
>Well, void plant produces a lot of void metal quite fast and essentially for free, so some complication is justified.

Is there a need for that many void metal such that this crop needed to be nerfed?

**Comment by repo-alt** [comment]
> Is there a need for that many void metal such that this crop needed to be nerfed?
That is my point - one, maybe two plants are enough for your needs.

**Comment by Vernam** [comment]
if the plant is not particularly necessary and two are enough - why does craft like this plant produce pure neutronium? Of course I'm exaggerating, but the essence does not change

**Comment by Zoko061602** [comment]
I don't think that seed is overpriced, maybe a little bit grindy. All flowers/seeds required for the infusion have simple Alchemy recipes and are duplicatable with a fortune pick, so I don't see any real reason to change the recipe. And btw. you can use Voidmetal to make pretty good GT Tools and Fluid Pipes at Stainless Steel level.

**Comment by Vernam** [comment]
it is very foolish to get a person to go through the craft of all these seeds for a void seed. Forcing people to go on a grinding road is not the best option. All these plants still need to be studied, some studies give warp. If a person tries to minimize the amount of warp it is a bad idea to require in the prescription a study for an additional warp. Yes, tools can be done. But for this and so you need to type enough warp to open voidmetal. the presence of the warp already implies that a reward can get something that would be worth it. Recipe should be logical and justified, at the moment there is no logic or justification.

**Comment by Vernam** [comment]
I'm more than sure that everyone who does not interfere with the recipe - obviously already made a seed, that's why they treat the recipe in this way. This is slightly selfish. Hardly anyone at all will want to suffer with the prescription. And for some reason no one pays attention to the demand for aspects, some are rather rare, which clearly does not make sense and justification

**Comment by noobyaran9** [comment]
The aspect cost is really unreasonable. Looking at the recipe itself, i would rather just craft the actual void seed using its intended recipe from vanilla thaumcraft or obtain them by farming those eldritch mob that surrounds the obelisk. 

>I don't think that seed is overpriced

Material-wise: Okay-ish. Just as u said, a little bit grindy.
Aspect requirement: Its just too much for a seed. There are plenty of easier method of obtaining the drop of the seed.

>And btw. you can use Voidmetal to make pretty good GT Tools and Fluid Pipes at Stainless Steel level.

But why? There are more material that offers better tool and fluid pipe when you already unlock the seed itself. I've been playing the pack for quite some time now, all i ever used void metal is only when i'm crafting the shadow fortress armour. 

I see no use in the void metel itself and thus, i think it should not be so grindy to create them.

**Comment by richardhendricks** [comment]
Shadow is way better than void metal for tools, 3x durability and 2x mining speed.
