### ISSUE TITLE
(Quest Text) Making Americum

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2941]
#### Which modpack version are you using?
2.0.3.0
#

Quest text in the Quest Making Americum has a small mistake (2 times the)

![unbenannt](https://user-images.githubusercontent.com/29660362/40084725-613e3668-5898-11e8-83a7-080a7b5e9982.PNG)

**Comment by 0lafe** [comment]
And 2 for's talking about the casing

**Comment by Dream-Master** [comment]
i guess @richardhendricks allready fix it in 2.0.4 or 2.0.4.1

**Comment by alphaNOVAircraft** [comment]
Suggestion:
Before you can upgrade your reactor, you will need to get some americium. The recipe will look pretty expensive, but once you made the next tier of reactor, you will unlock a simplier and cheaper one. You will need at least 128 plates for the reactor casings, 9 to scan for the recipe, and 4 to build one.
