### ISSUE TITLE
[Minor] Large <Material> Cells

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#2943]
#### Which modpack version are you using?
2.0.4
#
#### What did you try to do, and what did you expect to happen?
Use the 16x Large StainlessSteel Cells that were rewarded from the LCR multiblock goals quest.
#
#### What happend instead? (Attach screenshots if needed)
They work when taking from / putting into fluid tanks and hatches, but they give a message like "YOU SHALL NOT USE (this item)" on attempting to click in the world, which is annoying.
#
#### What do you suggest instead/what changes do you propose?
Disable the message / remove them from the list of items that give that message when used.

**Comment by draknyte1** [comment]
If I recall correctly, this exists due to a Tinkers Construct crash with these items and the Smeltery.

**Comment by Dream-Master** [comment]
Its not visual it is disabled via Block Limiter. Large Cells are sadly really buggy.
