### ISSUE TITLE
IC2 Wind Meter - quest

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#2945]
#### Which modpack version are you using?
2.0.0.7
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
I've tried to craft wind meter according to fulfill the quest, but even i had those materials from q, they aren't recognized
![2018-05-16_11 48 16](https://user-images.githubusercontent.com/14223368/40110374-1a126d5a-5900-11e8-96de-4464cf7cead0.png)
![2018-05-16_11 54 03](https://user-images.githubusercontent.com/14223368/40110375-1a2efcd6-5900-11e8-9148-e95d60416286.png)

#
#### What happend instead? (Attach screenshots if needed)
that "retrieval" part of quest (page 1) didnt completed
#
#### What do you suggest instead/what changes do you propose?
check the recipe

**Comment by Dream-Master** [comment]
will check
