### ISSUE TITLE
[Quest] Tier 2 Storage

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2946]
#### Which modpack version are you using?
2.0.3.0
#
In the Quest "Tier 2 Storage" (AE2 section) the quest says consume YES, all previous quests have consume NO. Dont see the need there make the quest comsume yes, you will need the produced items in further quests.
![ae1](https://user-images.githubusercontent.com/29660362/40110544-8481f5a2-5900-11e8-99d5-25deabb3d484.PNG)
![ae2](https://user-images.githubusercontent.com/29660362/40110545-849d2d5e-5900-11e8-8460-8827a9757753.PNG)

**Comment by alphaNOVAircraft** [comment]
Posted wrong screenshot (the second one), here is the right one i mentioned above
![ae3](https://user-images.githubusercontent.com/29660362/40110596-aaed471e-5900-11e8-8e53-ef3bd13350d9.PNG)

**Comment by Dream-Master** [comment]
Will fix it.
