### ISSUE TITLE
[Quest] Lapotron Crystal Quest 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#2949]
#### Which modpack version are you using?
2.0.3.0
#
The Quest "Lapotron Crystal" (EV Section) tells you to assembl a lapoton in a hv assambly machine, but you need a EV one.
![2018-05-17_13 23 33](https://user-images.githubusercontent.com/29660362/40174496-987d4694-59d5-11e8-8d3c-8a297bc20e55.png)
![2018-05-17_13 23 53](https://user-images.githubusercontent.com/29660362/40174498-9a269ee6-59d5-11e8-84fa-032f281498cd.png)

**Comment by Dream-Master** [comment]
fixed allready
![image](https://user-images.githubusercontent.com/2970688/40199366-7e94c6c8-5a19-11e8-9ebf-39563ace7ccc.png)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2848
