### ISSUE TITLE
Custom Burn Values using int 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#295]
Maybe we can using long because the Quintuple Coal Coke Block have a higher burn Value than 2147483647 (3200000000).

I see Minecraft Forge using for burn Values int so not sur how and if we can change it.

**Comment by Namikon** [comment]
No, not possible to change this. Maximum burnvalue for a single item is ~2million

**Comment by Dream-Master** [comment]
ok. 
Relax and enjoy your holiday!!!!!
