### ISSUE TITLE
Extra Bees Mutator isn't working

### ISSUE THREAD

**Issue by bashduude** [GTNewHorizons/NewHorizons#2952]
#### Which modpack version are you using?
2040

Mutator 1301 from Extra Bees need's some attention.
Doesn't working for me.

**Comment by noobyaran9** [comment]
How do u know its not working? Its only give a maximum of 300% increase in mutation chance with eye of ender.

**Comment by bashduude** [comment]
well then its fine, misunderstooding blocks, there is two different mutators (vanilla/extra bees).
and according to what we have in the pack this mutator will increase the chance of mutation by 15%(not 300%) at max. Meaning its working perfectly fine. So with 12% base bee using this mutator no matter how many you've got, once you hit 12% + 15% its done. No increase past this line. Which is weak and expensive. And my lesson has to be noted in the description of the block.
--
Maximum mutation increase is 15% in whole alveary.

**Comment by Dream-Master** [comment]
ok thanks for info. I close this now.
