### ISSUE TITLE
Vampires Blood-Draw for BM way too low.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#2953]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Cut myself to make a Weak Blood Orb, draining all my blood from 11-12 bars to 1.
Become a weak blood orb.
#
#### What happend instead? (Attach screenshots if needed)
Ran out of blood, and the thing did not craft.
#
#### What do you suggest instead/what changes do you propose?
Tweak blood drain for vampires.

I'm fairly sure this is a tweaking thing, I believe I did it right as there's nothing else I can reasonably make in terms of alter upgrades without making this orb; as a max tier vampire I expect that all my blood should be enough for, at least, the lowest tier blood orb.

**Comment by Dream-Master** [comment]
Make a suggestion which value need to be tweaked with configs. @Teirdalin

**Comment by 0lafe** [comment]
You can probably have 20 hearts, if not 30 by the time you start BM, 40 if you push it. You can make the better dagger, use gapples, heal pots, there's options. Apart from the annoying dependence on thaum, BM is really easy for nh

**Comment by noobyaran9** [comment]
If you can't even craft a weak blood orb with vampire 12 bar of health, you're obviously doing something wrong. And if you think vampire helps in blood magic, you're certainly wrong then.

**Comment by Teirdalin** [comment]
@Dream-Master Actually after looking through the config it doesn't seem that there is a vampirism blood magic config, which is rather silly of them to not add since they added the support in the first place.

Well 0lafe,  I don't use health as BM, instead it takes from my stored blood; I only get 1 bar of which per villager I feed on, which is turn is the issue as it seems to be incredibly, incredibly low how much LP it gives.

Noobyaren9 I'm not sure how much more complex making a weak blood orb can possibly be with a T1 altar,  and why should vampirism ruin blood magic for the player?   After some testing with a fluid conduit and drum it seems each bar of blood just makes 100 LP, which means it takes 50 villagers worth of feedings to fill one Weak Blood Orb.  I don't know how easy it is for humans to make these things, but it can't possibly be that ridiculous.
