### ISSUE TITLE
Orfanix server overloading

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2956]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
 
If u shift+click to cobble in recraft-orfanix recipe it will:
- if server heavy loaded - crash the server
- if server not loaded - kick everyone
![2018-05-18_14 21 22](https://user-images.githubusercontent.com/25028786/40232540-e39e4c5e-5aa7-11e8-9783-082c2cbf61cc.png)

**Comment by Dream-Master** [comment]
We can remove the orfanix if it crash the server.

**Comment by boubou19** [comment]
Orfanix is handy early game so i suggest to remove only the cobblestone recipe.

**Comment by Dream-Master** [comment]
yes

**Comment by Bryfer** [comment]
Last time this issues was brought up, o believe we ended up removing the ofanix from the boss drop?
Does it still drop?
I believe it's the lich boss?
