### ISSUE TITLE
Electric prospector scanner in bedrockium dim

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2957]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?

Electric prospector scanner don't work at bedrokium dim(ichor pickaxe dim). Some mods just don't work, some will kick u from server.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40256023-62f99eea-5ae9-11e8-96dc-080f60be10ff.png)
seems to work but need a long time to open it up. Maybe lagging
