### ISSUE TITLE
Personal cloaking device crafting

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2958]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
It uses all orbs we have in craft, yelds some result.
![2018-05-18_21 04 38](https://user-images.githubusercontent.com/25028786/40250487-1bc6793a-5adf-11e8-8268-378eb694a30f.png)
![2018-05-18_21 04 39](https://user-images.githubusercontent.com/25028786/40250489-1be8f69a-5adf-11e8-8ea5-bd320fb86339.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40254067-666e2c0a-5ae2-11e8-9ba5-8d3a04003442.png)
