### ISSUE TITLE
Stupid Thaumcraft research race

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#296]
Because of s stupid Thaumcraft research race the Wither spawns in the overworld already and i backup the World now.
I change the settings for the Overworld that the Wither kill people but not destroying blocks. Only the First explosion from the wither is real and will destroy blocks.
So be careful with Flux and Warp this could be ruin your Base.
I don't Backuping the world again so be warned.

**Comment by Dream-Master** [comment]
block-wither-block-damage	true  Whether block damage caused by Wither explosions should be disabled.
block-wither-skull-explosions	true  Whether the effects of Wither skulls should be disabled.
block-wither-skull-block-damage

**Comment by Teteros** [comment]
Hehe, I chuckled at the "stupidness" tag. (It's gonna be used a lot from now on, ain't it?)
It was the profane wands in this case, you'd really have to do a LOT of research to reach the threshold of spawning the wither, right?
Opening #297 to discuss the cause of the spawn.

**Comment by Namikon** [comment]
lol, really? I mean, you need a *ton* of warp to reach wither level.. How many wands do you have to use in order to reach that level? Honestly, I made every research possible the past 2 weeks, and put myself in exile in my old base, until I had all my warp purged. But it's not that it wasn't to be expected, was it? ;)

**Comment by Teteros** [comment]
@Namikon I have honestly no clue. From what Careface told me, he used one wand for about 10 mins to craft mundane stuff like the arcane pedestals in preparation for infusion, then BAM! ...the wither spawns right before his eyes in the storage room, ensuring fun times ahead.

I felt kind of bad, as I figured it would be safe to use the wand to save some time at the beginning. Boy was I wrong. Maybe the wand is designed to screw you up if you don't use it in combination with the respective BM ritual from the same mod which protects you from warp?

...or just warp theory acting up again.

**Comment by Dream-Master** [comment]
10 mins for him but maybe days in real life ;-)

**Comment by Namikon** [comment]
I used 2 profane wands until their contract reached zero before I noticed the fact that they give you warp, and the only things i got was a gazillion bats spawning everywhere, storm-weather, accelerated time and friendly creeper (which still scares me if it appears to be infernal in my Gregtech machine room). There is no ritual  to use them, only a tricky way to get around that "problem" of recharge-warp. Most research warp is temp or normal warp, which can be removed with sanitizing soap (The research for that should unlock very early on)
Oh, and the thaumonomicon contains a warning about those wands (Find it in the Forbidden Magic tab) "prolonged use is not recommended". 

From what I can tell right now is, that warp theory, how it is configured, works correctly (In most cases, still have to investigate  the problem with the not-stopping warp effects )

**Comment by Dream-Master** [comment]
I:minWarpWitherSpawnEffect=80

So he have Level 80 already

**Comment by Careface1g** [comment]
I can't even check my warp , i still didn't get the warp theory tab unlocked even after the wither spawning

**Comment by Namikon** [comment]
https://www.youtube.com/watch?v=0gTX2tyZUIw

**Comment by Namikon** [comment]
Well, tbh, I somehow can't believe that you haven't noticed that strange sound, and the purple warnings on the lower right screen while you used the wand / did research. One might not notice it the first and second time, but to reach wither level? But i'm not judging here, i'm always open to bugs. Maybe drobac can give you an arcane litmus paper so you can check your warp levels. Or I will try to login tomorrow and give you one.

**Comment by Careface1g** [comment]
Well tbh i did not see any change on the screen , i kinda switched from one profane to second and then it happened.

**Comment by Dream-Master** [comment]
I will make the litmus Paper much more early game acessable with the beginning researches.

**Comment by Namikon** [comment]
It is always like this. Don't forget that 100% is for 4 cores, so you have 25% of total usage

**Comment by Dream-Master** [comment]
I know we have 6 cores ;-) so it is only 16,6666% ;-))))

**Comment by Drobac** [comment]
Careface you derp

**Comment by Dream-Master** [comment]
;-)

**Comment by Dream-Master** [comment]
So close this for now. 
@Careface1g 
I hope you learnd from this in the future.
