### ISSUE TITLE
Draconic stuff mechanic

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2961]
#### Which modpack version are you using?
Epsilon
#
#### If in multiplayer; On which server does this happen? 
Epsi-one
#
#### What did you try to do, and what did you expect to happen?

Draconic Staff of power reduses tps of epsilon by 1 for each 11:11:11 click - change the mechanic of it if possible.
This is happening due to it's working mechanic: it simulates that player breaks all affected blocks one by one.

**Comment by evernife** [comment]
Does this fix remove all protection checks?
