### ISSUE TITLE
Enchanced charm of dislocation mark creation

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#2963]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
 When u trying to create new mark in Enchanced Charm of Dislocation u get kicked from server with this error: 
![2018-05-18_14 51 44](https://user-images.githubusercontent.com/25028786/40233370-56871b4e-5aab-11e8-872e-f5c0843f5db2.png)

**Comment by repo-alt** [comment]
Can't reproduce this one.

**Comment by bartimaeusnek** [comment]
might be fixed with newer versions aswell
