### ISSUE TITLE
World does not Load

### ISSUE THREAD

**Issue by Clowcadia** [GTNewHorizons/NewHorizons#2964]
#### Which modpack version are you using?
Latest Release

#### What did you try to do, and what did you expect to happen?
Tried to load world that is only in stone age.
#
#### What happend instead? (Attach screenshots if needed)
Back to main screen

https://pastebin.com/nhqDtFmf

**Comment by Clowcadia** [comment]
what do people use for text online...

**Comment by Dream-Master** [comment]
pastebin or gist

**Comment by Clowcadia** [comment]
gotcha sorry for that block

**Comment by Clowcadia** [comment]
any quick solutions? its probably something individual users have to solve, till the ae mod devs figure something out. 
i just dont know what to do, i am still in stone age. dont understand what causes this

**Comment by Dream-Master** [comment]
which version of the modpack you are using ? 2.0.4.0 ?

**Comment by Clowcadia** [comment]
the current release 2.0.4.0

**Comment by Dream-Master** [comment]
@Clowcadia you play on a server or sp ?
did anyone did stuff with ae system ?

**Comment by Clowcadia** [comment]
just sp, no ae systems going on. last thing done was increasing size of smeltery last i remeber it 5 by 5 8 or more tall, with like 90 or no coble stone inside smelting and maybe seared block being poured. that all that was going on

**Comment by Dream-Master** [comment]
This issue make no sense. All ae2 mods errored here in the log.

**Comment by Clowcadia** [comment]
I know, and i have no ae2 blocks in the world.

**Comment by richardhendricks** [comment]
Can you post the part before this snippet?  Seems like something is happening before it:

[16:30:07] [Server thread/INFO] [inpure|core]: Processing ServerAboutToStart event for submodule info.inpureprojects.core.Preloader.ModulePreloader
[16:30:07] [Server thread/INFO] [INpureLogInterceptor]: System no longer monitoring FML console messages.
[16:30:07] [Server thread/ERROR] [thaumicenergistics]: Skipping event FMLServerAboutToStartEvent and marking errored mod thaumicenergistics since required dependency appliedenergistics2 has errored

Might be something mentioned in the log earlier.

**Comment by Clowcadia** [comment]
This actually happened to me on infinity evolved mod pack, i had to restart the launcher to make it work or change the ftb_mode from expert to normal. now there is no such thing

**Comment by Clowcadia** [comment]
This actually happened to me on infinity evolved mod pack, i had to restart the launcher to make it work or change the ftb_mode from expert to normal. now there is no such thing

**Comment by Clowcadia** [comment]
@richardhendricks ok here you go, i did not know where to start so the whole thing
https://paste.ee/p/PyKIX

**Comment by Dream-Master** [comment]
``This actually happened to me on infinity evolved mod pack, `` Did you play GTNH or infinity evolved ? @Clowcadia

**Comment by richardhendricks** [comment]
OK, so you downloaded the modpack, and without changing anything, this is now the error message you get?

I don't understand what's happening.  Everything looks fine for appliedenergistics2, up until the addon mods start erroring out.

I do see an issue with Minetweaker at https://paste.ee/p/PyKIX#s=0&l=14106, maybe something is going on there causing AE2 to error out?

**Comment by Clowcadia** [comment]
exactly no changes had been done other then playing the pack.

**Comment by Clowcadia** [comment]
could updating multimc effect it? launching it through multimc, had to update it today its developer mode...

**Comment by richardhendricks** [comment]
It's possible some chunks might be corrupt, but it isn't clearly indicated in the logs.  Backup your instance somewhere safe (the whole thing), and try these steps

1.  Delete the player data file, see if that works.  https://www.akliz.net/manage/knowledgebase/48/How-to-Reset-a-Playerandsharp039s-Location-and-Inventory-on-a-Minecraft-Server.html

2.  If that doesn't work, try deleting the regional chunks.  You can compare the pictures in your journeymap folder against the chunks in your save file, and try to delete the chunks where you are located.

Once you determine if 1 or 2 works, you can try using mcedit or other tools on your savegame to fix your player data or delete specific chunks

Only other suggestion I have is to try redownloading the pack or alternate launchers like technic or curse.  Don't know what's causing that error, it seems very strange.  Make sure you backup your save game and journeymap folders, and test the save before deleting your multiMC

**Comment by richardhendricks** [comment]
Wait, you have it working now?

**Comment by Clowcadia** [comment]
Y

**Comment by Clowcadia** [comment]
Yes

**Comment by Dream-Master** [comment]
@Clowcadia explain  what it was please.

**Comment by Clowcadia** [comment]
No idea, just restarted launcher few tests and restarted laptop
