### ISSUE TITLE
Quest Error: Quest 89: MV Machine Hull Completes MV Steam Turbine Quest

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2966]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Thought I had made a MV Steam Turbine because I completed the quest.
#
#### What happend instead? (Attach screenshots if needed)
The quest for MV Steam Turbine only requires a MV Machine Hull to complete.
#
#### What do you suggest instead/what changes do you propose?
Make the quest require MV Steam Turbine to complete.

**Comment by Dream-Master** [comment]
allready fixed in dev.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40272952-9a5ee466-5bb7-11e8-87fe-aaff24401452.png)
