### ISSUE TITLE
Quest Doesn't Complete: ID 1154

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2968]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Completed the quest of crafting the bolts.
#
#### What happend instead? (Attach screenshots if needed)
Quest 1154 didn't complete.
#
#### What do you suggest instead/what changes do you propose?
Similar to the first crossbow and bolt quests in the steam age where you complete the quest but BQ doesn't detect it.

**Comment by Dream-Master** [comment]
I think this is fixed in 2.0.4 and obove.

**Comment by Dream-Master** [comment]
I think this is fixed in 2.0.4 and obove.

**Comment by Dream-Master** [comment]
I think this is fixed in 2.0.4 and obove.
