### ISSUE TITLE
Unnecessary item (Quest 887)

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#2969]
#### Which modpack version are you using?
2.0.4
Quest 887 requires a singular amulet, although it is not needed to craft it.

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
What do you mean ?
Explain what need to be changed here.

Quest 887

![image](https://user-images.githubusercontent.com/2970688/40272927-0166a834-5bb7-11e8-9ca5-cf2304961fc7.png)
![image](https://user-images.githubusercontent.com/2970688/40272930-052362aa-5bb7-11e8-8fbe-dd34bd6ce229.png)

**Comment by Dream-Master** [comment]
@CalterOK

**Comment by CalterOK** [comment]
To craft a staff for 125 vises, you do not need an amulet
![2018-05-20_02 48 45](https://user-images.githubusercontent.com/35035276/40274154-6e38761a-5bd8-11e8-94a2-7c6f41c24772.png)

**Comment by Dream-Master** [comment]
wil remove.
