### ISSUE TITLE
Profane Wands warning.

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#297]
As seen in #296, these innocent looking wands (full name is *Iron Capped Profane Wand* iirc) the villagers offer proved themselves to be deadly at last.
You may or may not know that they give the holder warp (Permament or Temporary?) in exchange for free recharge.
Apparently @Careface1g got enough warp after using the wand to craft a few times to reach the chance of spawning a wither in our base, which was quite... *destructive* to say the least.

As this behavior will not be discovered until they are used up, I'd like to suggest a tool tip to inform the user about this. If they will remain in the pack, this warning would make you think twice before trading and taking the risk associated with them.

Should the risk of using them be this high anyway, though?
All the highest level warp effects you may get are really nasty.

Scrambling of adjacent inventory warp effect affects machines for example.
I certainly wouldn't want my diamonds to end up in a recycler.

**Comment by Teteros** [comment]
Will #272 change the way these work?

**Comment by Dream-Master** [comment]
Will add a tool tip for it.
