### ISSUE TITLE
Duplicate bug

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#2970]
#### Which modpack version are you using?
2.0.4
#
Someone from dev team please pm me in discord.
kebal#2159

**Comment by nikitinalexx** [comment]
Here is a picture that Dream asked for
![image](https://user-images.githubusercontent.com/4941736/40266929-ef4d18c2-5b5c-11e8-8aaf-c4697d315b76.png)

**Comment by bartimaeusnek** [comment]
oh thats my fault i guess
