### ISSUE TITLE
[Minor] Item Conduit Recipe with Phased Iron

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#2973]
#### Which modpack version are you using?

2.0.3.0

#### What did you try to do, and what did you expect to happen?

Make an item conduit in the assembler and using the alloy blast smelter to smelt the pulsating iron dust.

#### What happened instead? (Attach screenshots if needed)

Alloy blast smelter produces Ender IO Pulsating Iron, which turns into GT++ Phased Iron plates.
(I would put this in GT++, but it's a much easier fix to just...)

#### What do you suggest instead/what changes do you propose?

Tweak item conduit recipe, oredict phased iron plate and pulsating iron plates in the assembling machine.

**Comment by Dream-Master** [comment]
No not anymore. Phased iron plates are switched to gt plates. And in the assembler it is ordited.
2.0.4.1 will fix this issue.

**Comment by draknyte1** [comment]
Regardless, all GT++ issues are to be reported to my GT++ repo. That's the policy I'm taking if folks what things investigated as issues.

**Comment by Dream-Master** [comment]
it is solved in never version no report needed @draknyte1
