### ISSUE TITLE
Field Kit... Unli paper

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2975]
#### Which modpack version are you using?
EDIT: 2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Step 1 = Make Field Kit for bees
Step 2 = Put paper in Field Kit (1 or more)
Step 3 = Use Field Kit (so paper is not full)
Step 4 = Insert Field Kit into Thaumic Restorer until repaired
Step 5 = Use Field Kit (has 64 Paper) - remove 64 paper
Go back to Step 4 and repeat...

#
#### What happend instead? (Attach screenshots if needed)
Free paper

#
#### What do you suggest instead/what changes do you propose?
Don't give free paper!!!
Maybe block Field Kit from Thaumic Restorer somehow?

/Highbeam

**Comment by Dream-Master** [comment]
not sure if i can disable it there.

**Comment by bartimaeusnek** [comment]
well you invest essentia here... and paper literally grows on trees...
