### ISSUE TITLE
Gold processing time

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#2977]
#### Which modpack version are you using?
2.0.4.0

#
#### If in multiplayer; On which server does this happen? 
Private Server

#
#### What did you try to do, and what did you expect to happen?
Gold processing in GT machines takes too much time. Gold is near the same hardness as Aluminium. For example Aluminium Plate processing time in Plate Bender is 1.3 sec. but Gold Plate is 9.8 sec. Or processing time of Aluminium Rod in Lathe is 6.5 sec, but processing of Gold Rod is 49 sec (!).

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Make Gold materials processing time near equal to Aluminium...

**Comment by Dream-Master** [comment]
processing time depends on the atomare wight so far i undertand. I wont change it and add all recipes manually is much work. Maybe you have a better idea.

**Comment by Vicus-N** [comment]
Maybe review that atomate weights based on some hardness weights? Internet full of numbers (for ex. https://www.jewelry-secrets.com/Blog/the-durability-and-hardness-of-metals/ ).

PS: I'm not insisting on this proposal, but every time I put stacks of gold to Lathe I'm crying :-D

**Comment by Bryfer** [comment]
Why not use extruder? (MV+ tiers)
It gives you 2rods from one ingot

**Comment by Vicus-N** [comment]
I know extruder benefits, but we talking about material softness and inconsistent processing time from material to material.

**Comment by bartimaeusnek** [comment]
@Vicus-N that would be a shitton of code changes. it may even break some addons like GT++ or TechTec. I would not recommend changing this.

**Comment by Vicus-N** [comment]
Then nothing to discuss here I think :)
