### ISSUE TITLE
Claybuckets unobtainable, when needed to progress

### ISSUE THREAD

**Issue by MegaGeil** [GTNewHorizons/NewHorizons#2978]
#### What version of the Modpack are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was trying to get a clay bucket.
#
#### What happened instead? (Attach screenshots if needed)
Clay dust isn't obtainable in Tier 0.5
#
#### What do you suggest instead/what changes do you propose?
Make clay dust available

**Comment by Anarack** [comment]
Make a mortar, some one close this.

**Comment by MegaGeil** [comment]
I made on but i cant get clayblocks

**Comment by Anarack** [comment]
you don't need to just use clay balls.

**Comment by MegaGeil** [comment]
That still measn the recipe shows false

**Comment by boubou19** [comment]
I'll suggest to add a precision on that because you have to chain recipes burried deep into NEI. For begginers it's not that easy to navigate into NEI.

**Comment by Dream-Master** [comment]
yea i add text

**Comment by noobyaran9** [comment]
Text : Git gud on using NEI :)

**Comment by Dream-Master** [comment]
np. Will be available next build 2.0.4.1
