### ISSUE TITLE
Testing of KCauldron 1492.150 on the Test Server

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#298]
I testing now KCauldron on the Test Server. Will see if we can use this on the live Server too.

**Comment by Dream-Master** [comment]
runs good no errors!!!

**Comment by Dream-Master** [comment]
Now Version 1492.155 is out. I will test this on the testserver too. I think with the next update we can change to kCauldron 1492 too. What do you think Guys?

**Comment by Namikon** [comment]
I don't see any reason to not update. If the testserver runs stable, which I haven't tested, why not.

**Comment by Dream-Master** [comment]
I am long time not online but if the server is still running i guess it is a stable version.

**Comment by Dream-Master** [comment]
Version 155 not works switch back to 1492.150

**Comment by Dream-Master** [comment]
Version 150 is now on the live Server.

**Comment by Namikon** [comment]
Martin, you forgot to update the client...

**Comment by Dream-Master** [comment]
Yes but i do now the update and the problem is solved.
Thanks for info.
