### ISSUE TITLE
Too many Assembler Machine Casings in Assembling Line Quest

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#2980]
#### Which modpack version are you using?
2.0.4.0

The Assembling Line quest wants you to build a 11 block long line. 

The quest step that asks for the Assembling Line Controller also requires 15 Assembler Machine Casings (the really expensive ones), but the controller is built with 4 of the 15 casings.

Either change this step to require the Assembling Line Controller and 11 Assembler Machine Casings (preferred), or move the Controller to a new quest step.

![image](https://user-images.githubusercontent.com/30087707/40379861-ad04a456-5df7-11e8-932b-33fe7b0e8280.png)

**Comment by Dream-Master** [comment]
yea will split it.

**Comment by alphaNOVAircraft** [comment]
Is that quest new in this version or am i just to stupid to find it in the 2.0.3.0 version

**Comment by Dream-Master** [comment]
new

**Comment by Dream-Master** [comment]
@alphaNOVAircraft
