### ISSUE TITLE
Vacuum Freezing Balance

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#2982]
#### Which modpack version are you using?
2.0.4
#
#### What did you try to do, and what did you expect to happen?
Recently, Vacuum Freezer recipes were updated to use voltages other than MV and be overall a lot more expensive. This has caused a lot more of the material processing costs to be shifted from the Blast Furnace to the Vacuum Freezer.
#
#### What happened instead? (Attach screenshots if needed)
For example, to make Naquadah:
First we smelt in the blast furnace: (~4 million EU over 25s)
<img width="263" alt="blast" src="https://user-images.githubusercontent.com/28197216/40397572-0970ad92-5df9-11e8-951c-bf5bd0dddccd.png">
Then, we freeze in the vacuum freezer: (~80 million EU over 500s)
<img width="262" alt="freeze" src="https://user-images.githubusercontent.com/28197216/40397619-3d855a2e-5df9-11e8-87d2-cfc1a0cba88a.png">

#
#### What do you suggest instead/what changes do you propose?
Lower the freezing costs/times of hot ingots to be more appropriate.

**Comment by NeroOneTrueKing** [comment]
By the looks of the numbers, it appears as though the voltage tiers for freezing were increased to match what the materials should need, but the time to process them was left untouched (thus, very high total cost).

**Comment by draknyte1** [comment]
Also, Advanced Cryogenic Freezer is now a thing~

**Comment by 0lafe** [comment]
As long as that works like the advanced ebf, I feel like it won't help enough for the new EU/t values and times

**Comment by NeroOneTrueKing** [comment]
Advanced Cryogenic Freezer appears to be the same EU/t with half the time, for a total of half the price (plus a small supply of another reagent). High-tier materials would still cost disproportionately much in the freezing stage vs the blasting stage.

Again using naquadah as an example, then it's ~4 million to smelt, ~40 million to freeze. I don't think it solves the problem.

**Comment by Kortako** [comment]
This has already been reverted for 2.0.4.1 afaik.
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/efe072d2ec04f0a82011ec4f8239abbb6551443e

**Comment by Dream-Master** [comment]
allready fixed in 2.0.4.1
