### ISSUE TITLE
Quest ID: 1184 Steam Locomotive Doesn't Complete

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2983]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Made the steam locomotive. Expected to get credit for quest.
#
#### What happend instead? (Attach screenshots if needed)
Didn't get credit for quest.
#
#### What do you suggest instead/what changes do you propose?
Make it register for the quest?

**Comment by Dream-Master** [comment]
I guess it us fixed 2hen I touch the other locomotive before.

**Comment by Dream-Master** [comment]
fixed allready. It ignore now nbt data.
