### ISSUE TITLE
Quest ID: 674 Wooden Rail Variants

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#2984]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Clicked on the top quest component (Wooden Junction Track) to see the recipe. Clicked on bottom quest component (Wooden Wye Track) to see recipe.
#
#### What happend instead? (Attach screenshots if needed)
Shows me how to make: Railcraft Tracks. Variants of 1395. Both of them show this. Middle one works. Might be something with the item IDs? NEI doesn't even show the correct recipe for the top and bottom ones.
#
#### What do you suggest instead/what changes do you propose?
Not sure how to fix but have it show the correct recipe?

**Comment by Dream-Master** [comment]
not possible because railcraft  add nbt data to tracks with same id.

**Comment by shawnbyday** [comment]
Maybe update the quest description to explain how they are made then? Right now I have no idea what to do.

**Comment by Dream-Master** [comment]
i add more infos but more i can't do
