### ISSUE TITLE
Is the recipe correct Superconducting coil block?

### ISSUE THREAD

**Issue by abyrvalg-s** [GTNewHorizons/NewHorizons#2988]
#### Which modpack version are you using?
2.04.0
#
#### If in multiplayer; On which server does this happen? 
singl
#
#### What did you try to do, and what did you expect to happen?
In the recipe Superconducting coil block requires tiny neutronium pipe, for smelting neutronium needs 132 keu battery and they require europium, which is produced in fusion reactor, for which we do Superconducting coil block. There are no other recipes in NEI, Is the recipe correct?
![2018-05-23_22 43 48](https://user-images.githubusercontent.com/39569968/40449409-0dbc151a-5ee1-11e8-97af-fa3070073514.png)
![2018-05-23_22 44 00](https://user-images.githubusercontent.com/39569968/40449410-0de37fa6-5ee1-11e8-8974-a64172583dc9.png)
![2018-05-23_22 44 41](https://user-images.githubusercontent.com/39569968/40449411-0e0be86a-5ee1-11e8-935f-cc7244546782.png)
![2018-05-23_22 44 44](https://user-images.githubusercontent.com/39569968/40449412-0e37b602-5ee1-11e8-94db-7c065f9f1c7a.png)

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
To give the opportunity to use a Superconductjr wire lower level.

**Comment by Dream-Master** [comment]
will be fixed in 2.0.4 1

**Comment by 0lafe** [comment]
You can totally smelt neutronium without fusion though. I think you can make solars to LuV without fusion, or any other LuV method, then buffer with 4 LuV batteries which just need sunnarium and redsteel, then smelt the neutronium that way. 

I do find it odd that you need neutronium in superconductors though

**Comment by abyrvalg-s** [comment]
To Olafe
for the production Luv solars is also needed europium) And for roasting neutronium need 4 energy buferr 32 ke with 16 sunarium battery (if there's less, the piece will just disappear.) But it is a way as all this is a very long recharge from 8Keu
Unfortunately other recipes NEI does not show) In version 2,03,0 there were recipes Superconducting coil block with  Superconductor wire lower level. and in this version of recipe only one

**Comment by 0lafe** [comment]
Mk1 fusion is some powerful stuff. It can net you over a million EU/t. Needing a partial amp of zpm to make it is totally reasonable. Make 4 LuV power generators and bam, 1A zpm

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40505924-14b0d9ea-5f96-11e8-9308-6bff50a5cec8.png)
![image](https://user-images.githubusercontent.com/2970688/40505927-178d8db6-5f96-11e8-8664-e1cb85dc8cc3.png)
you are now able to make the Superconductor Coils with ZPM or LuV Superconductore Wires

**Comment by Prewf** [comment]
hahahah 64 luv's for a coil block? my body is ready.
