### ISSUE TITLE
[suggestion] Armor with an invisible model

### ISSUE THREAD

**Issue by ruSauron** [GTNewHorizons/NewHorizons#2989]
#### Which modpack version are you using?
2.0.4.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
GT NH contain Gadomancy mod which have Armor Disguise infusion that allow to change armor visual style. it will be good to have invisible armor for reskin. 
#
#### What happend instead? (Attach screenshots if needed)
Nothing close to this.
#
#### What do you suggest instead/what changes do you propose?
I would be glad to have invisible armor to use  my character's skin. I think it can be crafted with unstable nuggets plus something (ore dictionary: nuggetUnstable, 24 of them + 4-6 other items for the whole set), something plus balanced shards (24 shards + 4-6 something for the whole set) or reinforced glass.

**Comment by draknyte1** [comment]
I guess I could add such a thing.

**Comment by bartimaeusnek** [comment]
@draknyte1 @ruSauron WG will be added in 2.0.4.0 which has a invisible armor enchantment

**Comment by Dream-Master** [comment]
2.0.4.1

**Comment by Dream-Master** [comment]
I close this now. WG will added next release.
