### ISSUE TITLE
Putting the IRC on the Test Server too.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#299]
Putting the IRC on the Test Server too for better comunications (easy Chatting)with the Live Server.

**Comment by Namikon** [comment]
I already thought about it a while ago, but I have to check if and how server to server chat can/will work, as Minecraft has a character limit for chat messages. On my todo list now

**Comment by Dream-Master** [comment]
It is only a reminder not a "you have to do it now" message.

**Comment by Dream-Master** [comment]
@Namikon 
Is this possible or mean this a lot of work and time ?

**Comment by Namikon** [comment]
Will check that today

**Comment by Namikon** [comment]
Done

**Comment by Dream-Master** [comment]
Cool thanks.
