### ISSUE TITLE
High End Rezept für Infernal Brick

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#2991]
Ist es möglich das es für die Infernal Bricks ein Rezept gibt (zusätzlich) das man diese auch im Vacuum Freezer machen kann? [10 sec 120/t]

translation:
Is it possible to add a high tier infernal brick recipe with vacuum freezer instead of the chemicl bath one. (120 eu 10 secs)

**Comment by Dream-Master** [comment]
i will check
