### ISSUE TITLE
Nether ores not generating [2.0.4.0]

### ISSUE THREAD

**Issue by ontario** [GTNewHorizons/NewHorizons#2992]
Version: 2.0.4.0 - fresh copy singleplayer (seed: 3354900193852585016 )

I`m trying to find a Nether ores (Sulfur etc).
After 3 more days I figureout with cofh those ores don`t genereted, looks like only Overworld ores does. And I see strange "noname" ore veins  looking like rock.

Config: [config.zip](https://github.com/GTNewHorizons/NewHorizons/files/2036799/config.zip)

**Comment by Dream-Master** [comment]
Yea we have issues with 2.0.4.1 too. It need a fix.

**Comment by NauticalOx** [comment]
I'm having the same problem. I've downloaded the pack multiple times from both Twitch and Technic and the problem persists even after entirely deleting the pack. 

Here's a [screenshot showing the ores](https://i.imgur.com/OGI9fny.png) on a world where sulfur appeared to not generate in the nether. Here's another [from a world where sulfur did generate](https://i.imgur.com/Pak6Moy.png) but there were still overworld ores present. Both of those screenshots are from the nether on 2.0.4.0.

**Comment by Dream-Master** [comment]
yes we have a bug and working on it. Hope it will fixed next release

**Comment by richardhendricks** [comment]
Potential fix discovered.  No idea why this wasn't happening the *whole time*.  It is a Heisenbug that wasn't there until it _**was there**_.  Fix taken from https://github.com/Blood-Asp/GT5-Unofficial/issues/726

**Comment by richardhendricks** [comment]
If you have emergency need for Nether/Twilight Forest/End ores:

1. Get a fresh version of config\gregtech\worldgeneration.cfg from https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GregTech/WorldGeneration.cfg
2. Remove gregtech mod from mods folder and replace with this version from Jenkins http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/27/

**Comment by richardhendricks** [comment]
Testing ongoing for planets.

**Comment by ontario** [comment]
Tnx, works fine for me.
