### ISSUE TITLE
Drawbridge and Advanced Drawbridge from Tinkers Mechworks not working

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#2993]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Drawbridge
#
#### What happend instead? (Attach screenshots if needed)
It does nothing when signal is applied or not...  Is it disabled?
#

**Comment by Bryfer** [comment]
What materials did you put into them?
Some materials does not work

**Comment by tranceplanet** [comment]
I tried vanilla cobblestone in both. It didn’t do anything on red stone. I’m away for weekend so can’t check until Monday now

**Comment by Namikon** [comment]
Drawbridges are disabled on both Delta and Epsilon until a solution is found on how to fix them

**Comment by tranceplanet** [comment]
Ok... What’s broken about them?
