### ISSUE TITLE
IC2/QuantumFlux

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/NewHorizons#2995]
Hey, i want to make my seeds from ic2 grow faster by imaginary time block, but it does nothing with seeds. How can i do what i want?)

**Comment by 0lafe** [comment]
Slower options would be the GT world accelerators. They work on crops, but cost a lot of power, and are slower than what you seem to want

**Comment by 0lafe** [comment]
it does work in TE mode though, and i dont think theres anything better, or at least better for ic2

**Comment by repo-alt** [comment]
How this bug relates to this repository and why it is not closed yet? @richardhendricks
