### ISSUE TITLE
[Suggestion]Adding other method to make mulch

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2999]
#### Which modpack version are you using?
2.0.2.7 (related to 2.0.4.1)
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Mulch usage is very high on 2.0.2.7 and its going to get worse with the mutagen recipe nerf using normal machines because growth medium takes mulch.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

Need to come up with a new method of making mulch that doesn’t include a percentage.

Maybe some like biochaff -> mulch in some process.

**Comment by CalterOK** [comment]
Mulch is produced 1 to 1 in a humidifier.

**Comment by Dream-Master** [comment]
humidifier? @CalterOK

**Comment by CalterOK** [comment]
https://ftb.gamepedia.com/Moistener

**Comment by noobyaran9** [comment]
Its slow and not viable when u need them in large quantity.

**Comment by 0lafe** [comment]
I'm gonna mention this here because it totally works, accelerate the moistiner
