### ISSUE TITLE
Witchery Nerfing Recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#300]
![image](https://cloud.githubusercontent.com/assets/2970688/9136393/8ac245b0-3d16-11e5-86f2-cc29b6081ee9.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/9136402/a1ed53c4-3d16-11e5-8a22-d3c3fce1d7b4.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/9136405/aac6fa68-3d16-11e5-9293-d4148efa9437.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/9136408/b50704d2-3d16-11e5-9c44-bdb66b0145cc.png)

**Comment by Drobac** [comment]
Looks ok

**Comment by Dream-Master** [comment]
More items will follow later.
