### ISSUE TITLE
Bone Meal unterschied zwischen Sagmill und Macerator

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#3000]
Warum bekommt man in der SAG-Mill, die billiger ist als Macerator viel mehr Bone-Meal heraus?
SAG --> Macerator
Large Bone Segment 24 15
Medium Bone Segment 12 10
Small Bone Segment 8 5
Bone 6 4

**Comment by Dream-Master** [comment]
Issue 3000 :p 
Will check
