### ISSUE TITLE
[RFC] Ore scanning

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3003]
This thread is to discuss potential changes to ore scanning and generation.  It's been a hot topic for a long time, and I wanted to make sure we got a good consensus on moving forwards.

First off - nobody say "I made it through so anyone can!" This is confirmation bias, and is not helpful to the discussion. Yes, you are uber elite and survived, but I'm sure there are 100x as many people who got RNG to death and/or gave up after a few hours.

The purpose is not to make ore searching trivial or easy, but fun, and scaled to get better as you reach higher tiers.

Currently there is the OD/OV scanners, and the electric prospector scanner at LuV.  The seismic prospector is also getting a planned buff where it will list ores in chunks.

Issues
1. Lots of ores are needed, especially early on.
2. Ores have different rarity, and can be hard to find.
3. It's boring to dig boreholes over and over.

Ideas
1. Add pre-steam/steam tier "diving rod" ore scanner. Requires a sample of the ore to find, so players would need to locate a small ores first to get something to put into the scanner. Under investigation.

2. Add LV-HV tier simple prospector's scanner. This scanner will not report in a GUI the ore map.  Instead it will just report the relative density of an ore in the area.  My idea is to have it not be 100% reliable. Sometimes it will report ores outside the scanning area - maybe 20% of the time it reports from a random nearby chunk - this will be tracked per chunk, so if a chunk reports incorrectly it will always report incorrectly (maybe per tier, so a higher tier scanner gets a better chance of getting the chunks accurate). Chunk width would be determined by the circuit tier used. LV - 1 chunk, MV, 3x3 chunks, HV 5x5 chunks. Since it does not report precise locations, an HV scanner might be used together with an LV scanner.  It would use the non-rechargeable batteries, for variety.

3. Add placer ores above the orevein, to the top of the replaceable blocks.  My idea for this is to use the "around" ores and place them up until it can't place any more.  Density would need to be dropped though as it rises.  This would get players a sense of reward/excitement when they find the right placer ore above the vein.  Would not help for players on current servers.

**Comment by WarlordWossman** [comment]
There is some good ideas in there.
I would like small ores of the same type as the vein being above and/or near it but that would change a lot.

**Comment by DualBallers** [comment]
These are all really good ideas and would improve the pack immensely!
I really really love the constant grind, the extremely slow progression, and the never ending requirements of more materials - but - by god the ore searching is killing the fun fast as it is just tedious on a whole other level.

One of the first hard ores to find is Mica (random weight 20) for EBF coil blocks. I had to use '/cofh clearblocks' and found the only vein ~50 chunks (!!!) away from spawn. Even with the OD/OV scanners I would have never found it without cheating!
Other really hard veins are the Thaumcraft shard veins in the TF (weight 16). Here these rare veins are easily blocked by the progression barriers, effectively blocking all magic until you are much much further in the tech tree and stronger.

What I'm trying to say is - it would be nice if the low random weight ores could be found more easily - maybe some mechanic where you need to spend a significant amount (inversely proportional to the random weight) of some more common materials.

**Comment by 0lafe** [comment]
I love the divining rod idea, as long as it needs an ore of the same type to make it

**Comment by mitchej123** [comment]
I'm in favor of the placer ores above the vein up to the surface.  Been playing a bit of 1.12.2 with the Geolosys mod and it has similar large veins to GT with some sample deposits up top.  It's a lot less tedious than digging down to check every 3 chunks.

There's additionally a tiered divining rod/prospector that searches for ores within 48 blocks in a straight line (up, down, forward, etc)

**Comment by richardhendricks** [comment]
I don't know if there are small ores for every material.  If I implemented it the way I was thinking, it would be one of the orevein ores, since it is easy to pick off right there. Maybe even randomly choose one of the 4 so that players have to have a keen eye.

The Q would be how to work with the placer ores - put them up to the dirt, but not in the dirt?  Make them visible from the surface?  Require digging down? Replace the dirt too? What about biomes with weird dirts/sands/etc? This isn't for anything "soon" but probably by the end of the year.  Another option would be researching how the "set down" items on the ground, and "set down" crushed or dust versions of the oreveins below instead of a whole ore block.

The other thing, when was the last time ppl experienced the early game? @DualBallers do you recall when your chunks were generated?  The latest release should be much nicer with ore distribution and empty veins.  Maybe the new oregen is nice enough that this isn't an issue any more. It would definitely still be a problem to new players on the servers though.

The problem with the divining rod is that you need a sample of that ore for it to work.  Makes it hard to search for Mica if you haven't found it yet.  Some ideas - 

Give a couple of the rarer ores as quest rewards after the divining rod quest, so players know to use them for that.  This would allow us to control how many they get pretty easily - maybe one quest gives you a choice between diamonds or redstone for example. Or make the ores rewards for grinding so you can choose to keep searching or do X to get an ore for the orefinder (bring me 5 witch hands and I will give you a redstone ore to use in your ore locater).

Another option would be to add them to some loot table - mob, chest, boss mob, etc.  Probably not a chest, on a server those tend to get emptied pretty fast.  So a mob or boss mob might drop a mica ore.  I don't know if we want to force players that hard into a mod, but making the Hydra drop a Mica ore could work.  Maybe the deeper mobs in the roguelikes could drop the other ores like redstone and diamond ores, I don't know if we have that kind of fine control.

**Comment by Scottishprog** [comment]
My position on ore searching... The current method of building shafts needs to die completely.  The discussion I see going on is making me optimistic on that front.
My main issue it that the current method cannot be improved until HV at least. (When the first scanner is available. - although there are prospector available.. hard to get the explosives needed at LV)
So you are stuck... and you can't innovate your way out.
Requiring some cleverness in interpreting results at lower tiers is ok.  Still have some incentive to move up the tech chain.

**Comment by Scottishprog** [comment]
Another thought... could you vary the method of discovery by rarity of ores?
So things like iron/copper/tin have placer deposits...
Mica, you need a scanner of some sort.
In short, you could always do shafts, or use a detection method that escalates in complexity/tier with ore rarity.

**Comment by DualBallers** [comment]
@richardhendricks Good point - those chunks were generated roughly a year ago, so that might not be representative of the current distribution. Maybe the shard veins in TF is also easier to find now (?).

I think the rare samples could easily be added as quest rewards for the Wither/Ender Dragon/TF bosses/GC planet bosses, so it matches the specific tiers. 
This would tie the quest progress through magic/tech/space even better together if you want some help in finding the rare ores.

Or you could start a new quest line for all the scanners where the samples can be bought for a ton of materials from the same respective material tiers.

**Comment by codewarrior0** [comment]
My vote is for the Geolosys/GT6 scheme of having surface pebbles to indicate the underlying ore. Digging boreholes is no fun, but just going out and covering a lot of ground will get you all kinds of other worldgen goodies.

**Comment by sthegreat** [comment]
In my opinion the ideal solution here would be to generate small pebbles above ground for early-tier ores like copper, iron, tin, etc., and then to use the seismic prospecter mid-game for ores such as mica in the overworld and all veins on other planets.

**Comment by mitchej123** [comment]
While I'm in favor of the Geolosys/GT6surface pebbles, one other system that seems to work well is the immersive engineering core drill sample -- except rather than a data stick, it gives you an actual sample you can read immediately (oil/water/lava, mineral, etc) and even place in the world.   

I think we have something similar from IC, but it gives a data stick you need to run back to your base with.  A "sample" you can look at right there and then is great for earlier ores.

**Comment by draknyte1** [comment]
I half wrote an item for portable data stick scanning (So you can prospect on the go).
If There was a way to print data to paper, lets say as 'Environmental observation notes' that held info on the chunk+1 in each cardinal of the player. 

Thoughts? Could probably finish all that off easily.

**Comment by richardhendricks** [comment]
Yeah I think we need to look at the prospector code.  We had pulled, AFAIK, code that allowed a higher tier prospector to show more than one chunk.  With an Hv prospector telling you what is in a 5x5 chunk area, I don't know if a handheld printer is necessary.  The current quests give you a couple of datasticks so you could easily search a pretty large area.

**Comment by Dream-Master** [comment]
https://mega.nz/#!6QYzwSqL!PcIe7Qj8G7DoSwm-UqhOSbSBJZuM-B0yRzupLAmCHTE
Source code

**Comment by 0lafe** [comment]
First id just like to say I'm totally in favor of the portable scanning idea. 

>Yeah I think we need to look at the prospector code. We had pulled, AFAIK, code that allowed a higher tier prospector to show more than one chunk. With an Hv prospector telling you what is in a 5x5 chunk area, I don't know if a handheld printer is necessary. The current quests give you a couple of datasticks so you could easily search a pretty large area.

5x5 seems like a ton for HV, I don't really think anything should be that good that early. I remember getting the OV/OD scanners in HV/EV and they felt like a huge improvement and made things a lot easier. I think something better than that, earlier, isn't a good idea. 

Maybe something that takes like ink and power, and can scan just the chunk you're in. It only has enough power to scan like 4 chunks before you gotta recharge it. That way the OV/OD scanners are still an improvement in some ways, and it's still faster than the old way of mining.

**Comment by richardhendricks** [comment]
OK, both steam tier "Ore finding wand" and LV+ basic prospector are available in game.  Please test and provide suggestions.
