### ISSUE TITLE
[suggestion] add twilight forest moss patch to the witchery ent

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3005]
#### Which modpack version are you using?
2.0.4.0

Now that random modifiers from tinkers are gone, moss patches from the twilight forest are really important as you need them to get the tinkers ball of moss (repair modifier for tools):
![moss_1](https://user-images.githubusercontent.com/16925725/40579449-a4602d7e-6127-11e8-8f73-0dd2155c2821.PNG)

The moss patches spawn in the twilight forest and are NOT renewable at the moment, which means people will have to explore to get them. This might cause problems on servers since higher tier players can raid a lot of them effectively leaving no options for newer players to get any (and besides that generating new twilight chunks can be quite laggy).

So here is my suggestion on how to make the moss patches renewable but still involve some work to do:
Add (exactly 2) of those moss patches as a drop to the Ent from Witchery (to summon him you need to chop down quite some hawthorn trees).
![moss_2](https://user-images.githubusercontent.com/16925725/40579491-71f8e528-6128-11e8-9893-f298d44b0694.PNG)

It's important that we don't overwrite his usual drops since he drops the "ent twig" which is important as well:
![moss_3](https://user-images.githubusercontent.com/16925725/40579484-3772714e-6128-11e8-9cde-00563c3dfd0a.PNG)

Adding two moss patches as confirmed loot will not only promote starting off with Witchery but also make balls of moss renewable in a not too easy way.
I recommend it for reasons listed above.

**Comment by bartimaeusnek** [comment]
@WarlordWossman A Moss Crop is planned, will implement it till 2.0.4.0

**Comment by WarlordWossman** [comment]
That is a good idea, I think we could still have this option tho for early game.
It takes quite a while (even with lumberaxe) to summon the Ent so the crops would def be better once you get them. I would honestly say: Why not have both @bartimaeusnek

**Comment by bartimaeusnek** [comment]
@WarlordWossman bc changing Witchery is a PITA and needs either Reflexion or ASM witch is both annoying af 😄

**Comment by Dream-Master** [comment]
Alkalus allready make the mod witchery extras or how it is called.

**Comment by bartimaeusnek** [comment]
@Dream-Master ye but its not for mod drops, only for recipes and stuff

**Comment by WarlordWossman** [comment]
I mean if it's impossible we can't but it would be a cool for sure.

**Comment by Dream-Master** [comment]
We can add mob drops via core mod with custom mob drops.

**Comment by richardhendricks** [comment]
Or add a recipe with the special drop from the mob?

**Comment by richardhendricks** [comment]
https://sites.google.com/site/witcherymod/ent-twig is dropped by ents, suggested moss recipe

ent twig + apatite + water in assembler (or witchery cauldron or whatever now that we can add recipes) -> 2 TF moss patches.

**Comment by richardhendricks** [comment]
200 hitpoints seems like a lot, but it looks pretty easy to kill @WarlordWossman does a Tinker's axe work on it? What other high damage axes are there?

**Comment by richardhendricks** [comment]
Actually, I think milk might be a better recipe.  That's how you make moss/lichen grow on rocks.
<http://www.mastergardening.com/blog/moss-and-lichens/>

**Comment by Dream-Master** [comment]
maybe we add it some day

**Comment by richardhendricks** [comment]
Should be easy to add to loot table for Ent or do a recipe using the twig. How many Hawthorn do you have to chop to get it?

**Comment by richardhendricks** [comment]
Also check on moss crop, see if TF moss was added to IC2 crops.

**Comment by bHXDgiuMa5yLHyC8** [comment]
@bartimaeusnek 

I think source for Witchery is now available: https://github.com/CarlGustavAlbertDwarfsteinYung/Witchery

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/68527953-61d3da00-02ed-11ea-9524-a37663577ba0.png)
Moss Crops

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/68528076-87151800-02ee-11ea-89a3-0dfe8e5070d4.png)
This 3 mosses are droped by this crop

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/68528235-43bba900-02f0-11ea-89ac-6313ee5405a7.png)
![image](https://user-images.githubusercontent.com/2970688/68528243-4f0ed480-02f0-11ea-812e-3a39423db7b6.png)
works

**Comment by Dream-Master** [comment]
@WarlordWossman  :)
