### ISSUE TITLE
Dim Wipe for Official Servers

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3009]
We need to wipe Europa, Centauri Bb, Barnard C, T Ceti E, Vega B, Io, Venus, Enceladus on official Servers to let them generate Ores for 2.0.4.1. @Dream-Master 

Also @Cinobi wanted TF to be wiped on Epsilon.

**Comment by WarlordWossman** [comment]
Twilight Forest wipe on epsilon would be nice for the new ore gen, the hard part is getting to all players and finding out if somebody has been building in there.

**Comment by Dream-Master** [comment]
I do a announcement tomorrow. If no one pm me or complain I will wipe the dims.

**Comment by repo-alt** [comment]
Is that the exact list of dimensions to be reset? I'll need to dismantle my teleposer network.

**Comment by Dream-Master** [comment]
Announcement is out:
 We need to wipe Europa, Centauri Bb, Barnard C, T Ceti E, Vega B, Io, Venus, Enceladus on official Servers (Delta nd Epsilon) to let them generate Ores for 2.0.4.x. Twilight Forest need a wipe too. If you have any Blocks or Setups there please remove them until Friday 01.06.2018 08:00 UTC. There will be no refund. (pm me if there is any problem) Thanks
