### ISSUE TITLE
Mutagen production Missing step

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3010]
#### Which modpack version are you using?
2.0.4.1

Mutagen looks like it is missing a production step.

growth medium-> bacteria ->? ->enriched bacterial sludge->fermented bacterial sludge 

Also enriched bacterial sludge and fermented bacterial sludge do not have spaces in their names.

**Comment by Dream-Master** [comment]
will ckeck

**Comment by Dream-Master** [comment]
Maybe something happend when update GTTweaker.
@Ethryan thats what i mean with unforseen consequences :(

**Comment by Dream-Master** [comment]
All Brewing Recipes need to changed (reminder for me)

**Comment by Ethryan** [comment]
I see, i only checked the solid crafting recipes, completely forgot to check the fluid ones.

**Comment by Dream-Master** [comment]
only brewery and the uu machine have changed input/outputs. Rest seems ok.
