### ISSUE TITLE
Weird recipe Onion Soup

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#3011]
#### Which modpack version are you using?
2.0.4.1
#
#### If in multiplayer; On which server does this happen? 
localhost server
#
#### What did you try to do, and what did you expect to happen?
Grilled Cheese in recipe Onion Soup looks weird.
#
#### What happend instead? (Attach screenshots if needed)
![2018-05-28_03 43 06](https://user-images.githubusercontent.com/3153076/40592804-fb0d960c-622b-11e8-918d-e5fdd6d12714.png)
![2018-05-28_03 43 09](https://user-images.githubusercontent.com/3153076/40592807-fc9f871e-622b-11e8-9750-0eda4701f959.png)

**Comment by Dream-Master** [comment]
@code32 Let me know what you put else in the soup?

**Comment by damug** [comment]
It's not quite grilled cheese, but one of the more common things served with french onion soup in my experience, generally just placed right on top before serving is a slice of cheese toast.  See: https://birdsnestbites.com/french-onion-soup-with-cheesy-ciabatta/

**Comment by code32** [comment]
Fried cheese has in the game more satiety than onion soup in which is added

**Comment by Dream-Master** [comment]
@code32 so what you suggest?

**Comment by code32** [comment]
I suggest use in the recipe ("Onion Soup")  just "Cheese" instead of "Grilled Cheese"

**Comment by damug** [comment]
Could I suggest cheese and a slice of bread instead of grilled cheese then? That way it stays in line with the cheese toast you generally serve onion soup with.

**Comment by damug** [comment]
Otherwise, drop the cheese entirely and drop the satiation value to that of seed soup, vegetable soup, and the like.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40749611-e1134f72-6464-11e8-876e-c21fb5c4d9ef.png)
