### ISSUE TITLE
[reminder][discussion] infernal blast furnace

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3012]
#### Which modpack version are you using?
2.0.4.1

With witching gadgets we now got the infernal blast furnace which is a multiblock structure that is unlocked after Lich/stainless steel.

![infernal_1](https://user-images.githubusercontent.com/16925725/40601773-b4140a30-6256-11e8-8847-e0ecb17080da.PNG)

At that level you can make steel pretty fast but you still need oxygen and energy in the EBF while the IBF just needs fire vis if I understand correctly:

![infernal_2](https://user-images.githubusercontent.com/16925725/40601821-e5e667c4-6256-11e8-85d6-0c1776e4ddc1.PNG)

So there is multiple options now depending on if you can change recipes in there.
I think it shouldn't become the goto furnace for steel in a GT pack and if it's not I wonder if anybody would use it. (We disabled stuff like the IC2 or railcraft blastefurnace too).

I think it would be cool to add specific recipes to this thing, maybe some magic alloys that you can only smelt in there etc.
But I guess it would be good to discuss first, what do people think about it?

**Comment by Cinobi** [comment]
do not see a problem in one more way to make steel at HV+. Does it realy need any change?

**Comment by WarlordWossman** [comment]
The idea would be: If you make steel in the EBF anyways, we could change this multiblock to do something else, just to make it more interesting again.

**Comment by WarlordWossman** [comment]
Idea from moron: 
Shadowsteel, thauminite, and void metals could be ingots you can only make in there.

**Comment by Dream-Master** [comment]
yea why not

**Comment by Cinobi** [comment]
Making thaumcraft even more annoying? I'm strongly against.

**Comment by WarlordWossman** [comment]
> Making thaumcraft even more annoying? I'm strongly against.

I mean you are just crying 24/7 anyways, some people actually think it's cool if there is dedicated multiblocks for magic. Def more interesting than moving every ingot into the EBF imo.

**Comment by Cinobi** [comment]
Fuckin everything my dood. Just enter the epsilon(or delta) and try by urself.

**Comment by draknyte1** [comment]
Not my fault they're using a version that's months and literally hundreds of revisions old. Wait for them to update to 2.4.2 and go find a corner to be happy in.

**Comment by Cinobi** [comment]
>Not my fault they're using a version that's months and literally hundreds of revisions old. Wait for them to update to 2.4.2 and go find a corner to be happy in. 

This is New Horizons github, not GT++. So i'm free to talk here to EVERYTHING that connects to New horizons. Official New Horizons servers have no update due to GT++ too, so go be salty somewhere else please.

**Comment by draknyte1** [comment]
> This is New Horizons github, not GT++. So i'm free to talk here to EVERYTHING that connects to New horizons. Official New Horizons servers have no update due to GT++ too, so go be salty somewhere else please.

I'm aware, but I don't appreciate your invalid slandering when you're whinging about something not relevant (As per usual). It's not relevant to this discussion either. Servers have been free to update, but I think Dream felt it beneficial to iron out bugs in the pack while I finish things off. I assume server update will happen by the weekend, considering the wipe?

As for this Blast Furnace, Move all the magic smelting here. Give people a reason to use it, just nerf the steel lul.

**Comment by Cinobi** [comment]
>>As for this Blast Furnace, Move all the magic smelting here. Give people a reason to use it, just nerf the steel lul.

Ok, let me explain little more why i'm against.(I should do it before i guess, sorry for that). EBF can be speeded up for blinding speed. This furnace - guess it can't. Why do u want someone to wait for unknown time for smelting some ingots? 
Aaand, about making thaumcraft more grindy in complex: it was funny to win the whole thaumcraft researching minigames first time. Second time. maybe third. For now it just couse me have nousea, and not only me. Aaaand u want to make it even more grindy. Awww.

**Comment by WarlordWossman** [comment]
You would probably be able to accelerate it which means it would also get faster if you have the energy, needs to be tested tho.

**Comment by draknyte1** [comment]
> This furnace - guess it can't. Why do u want someone to wait for unknown time for smelting some ingots?

Magic.

> Aaand, about making thaumcraft more grindy in complex: it was funny to win the whole thaumcraft researching minigames first time. Second time. maybe third. For now it just couse me have nousea, and not only me. Aaaand u want to make it even more grindy. Awww.

But then GT++ adds in the Auto Researcher next update and you just feed them power and raw shards and they do your research for you. Probably whenever this change would roll in if accepted in some way.

**Comment by noobyaran9** [comment]
>Idea from moron:
Shadowsteel, thauminite, and void metals could be ingots you can only make in there.

I'll agree if the ebf recipe is untouched. Else i'll give a huge no here.
As cinobi said, no point making thaumcraft grindier. You already need to use plenty of your brain to plan out research else, you're going to just fuck yourself up. 

And, moving magic ingot to smelting using magic stuff because its interesting? Nah, its stupid. 
And its a multiblock, accelerating? You sure about this?

**Comment by WarlordWossman** [comment]
Well it's more interesting than realising that every ingot is in the EBF.

And afaik you can accelerate multiblocks like the railcraft blast furnace (advanced coke oven) for example.

**Comment by bartimaeusnek** [comment]
sure you can, but why would you prefer hacky world accelerators over normal overclocking? in addition it was a PITA to make this thing accept even the "normal" BBF Recipes.

**Comment by Anarack** [comment]
Also some blast furnace only materials can be made using this such as meteoric steel, and electrical steel, so its recipe list needs a look anyway.

**Comment by damug** [comment]
I think it sounds like a great idea to move the magic ingots to the magic furnace. +1 from me.

**Comment by WarlordWossman** [comment]
@bartimaeusnek why would you add another blast furnace with the same recipe when we disabled the ones from Railcraft and IC2?
Also if world accelerators are "hacky" why do we handle them as a feature?

I am already throwing most of my ingots into the EBF, I would actually welcome some ingots that work with a different mechanic...

**Comment by bartimaeusnek** [comment]
> Also if world accelerators are "hacky" why do we handle them as a feature?

WA's actually higher the tickrate in their radius. This was never intended by Minecraft or Forge, so they are hacky, and might cause weird problems. I dont know why anyone want to call this a feature.

> I would actually welcome some ingots that work with a different mechanic...

and how is it a different mechanic? you just throw them in a different shaped BF. It's literally the same mechanic like the BBF. just with Ignis Vis instead of Coal

**Comment by WarlordWossman** [comment]
> WA's actually higher the tickrate in their radius. This was never intended by Minecraft or Forge, so they are hacky, and might cause weird problems. I dont know why anyone want to call this a feature.

We got a machine to literally do that, so somebody thought "it should be possible for players to mess with it", if this is not a feature then idk.

> and  how is it a different mechanic? you just throw them in a different  shaped BF. It's literally the same mechanic like the BBF. just with  Ignis Vis instead of Coal

You answered your own question, it uses vis instead of coal / electricity.

**Comment by bartimaeusnek** [comment]
> it uses vis instead of coal / electricity.

Thats not a mechanic thats a fuel.

**Comment by damug** [comment]
Fuel that requires an entirely different infrastructure to generate and distribute, ergo it's a different mechanic.

**Comment by bartimaeusnek** [comment]
So if i add a Blast Furnace that runs on Plantmass its a "entirely different" mechanic aswell? Imo thats just energy ressource, since you can do vis -> GTEU and vice versa.

**Comment by damug** [comment]
That already exists, you can turn plantmass into fuel, then burn it in your generator of choice to create eu.

**Comment by damug** [comment]
I think I understand your root comparison though.

Vis = fuel + something
Eu = fuel


Both take wires/pipes or batteries/jars to distribute.

I think the fundamental difference is one is "technology" the other is "magical". Functionally they may be very similar at their core but from a more broad gameplay perspective they are different systems that can emulate and compliment each other at times.

**Comment by 0lafe** [comment]
>Vis = fuel + something

eh, kinda

does it run on vis or centi vis? Whats the time frame for making steel? Is it capped on vis/t or does it just need to hit a vis cap and then its smelted? 

>I think the fundamental difference is one is "technology" the other is "magical". Functionally they may be very similar at their core but from a more broad gameplay perspective they are different systems that can emulate and compliment each other at times.

The problem is if it's centivis you're getting ebf smelting for free, if its just normal ignis vis, youre getting smelting from coal or netherrack, which is pretty much infinite. Its a much simpler conversion of item to fuel to power to end product. 

I still want to see some numbers for this, and know if its normal vis or centivis, the thaum page/nei page don't seem too useful

**Comment by bartimaeusnek** [comment]
@0lafe it runs on Centivis.

**Comment by 0lafe** [comment]
well that's more reason for me to say no. Unless the recipe/blocks it uses is totally changed and its like LuV or something

**Comment by bartimaeusnek** [comment]
actually im wrong it runs on essentia sorry

**Comment by noobyaran9** [comment]
How is generating centivis interesting? All you need to do is find a node and put it in a stablizer and tranduser and its fucking done. Such a boring and bland mechanic.
Not to mention, how are u going to change the speed of the furnace? How are u going to define the tier of material that u need to smelt?

Honestly, i find building infrastructure to generate power is far more interesting than using a node to generate centivis.
This whole suggestion is just plain stupid and boring.

**Comment by WarlordWossman** [comment]
> Honestly, i find building infrastructure to generate power is far more interesting than using a node to generate centivis.
This whole suggestion is just plain stupid and boring.

It's not like you don't have to do that if we move a few ingots over. My EBF ran for days and I didn't even touch magic ingots that go in there :D

**Comment by richardhendricks** [comment]
"all you need to do?"  Well first you need to find the node.  Then move it to your base by jarring it.  Unjarring it will likely damage it, but that doesn't matter for centivis production.  And if you want significant output you have to boost it with empowering bees, which is a nontrivial project in itself. So I don't think it is that boring and bland.

Magical ingots are hardly needed at the quantities the GT ingots are needed. I am OK with it making steel at ~LV or MV speed, considering it would only be relevant for a short while before the EBF outpaces it anyways.

If there really is need for magical ingots at quantity, using a WA seems fine to me, you still have to generate power to run that.

The power isn't any more "free" than any other farm setup like bees or oil plants or logs.

Gating high tier magical armor behind a high tier magical multiblock sounds right to me.

**Comment by richardhendricks** [comment]
Actually, it isn't centivs, it's essentia.  

https://github.com/bartimaeusnek/WitchingGadgets/blob/master/src/main/java/witchinggadgets/common/blocks/tiles/TileEntityBlastfurnace.java

https://github.com/bartimaeusnek/WitchingGadgets/blob/master/src/main/java/witchinggadgets/common/util/recipe/InfernalBlastfurnaceRecipe.java

https://github.com/bartimaeusnek/WitchingGadgets/blob/master/src/main/java/witchinggadgets/common/WGContent.java#L427

**Comment by richardhendricks** [comment]
Yeah that construction recipe is a little too easy for GT:NH. Maybe we can throw in an EBF controller so it isn't quite so cheap?

https://ftbwiki.org/Infernal_Blast_Furnace

**Comment by richardhendricks** [comment]
It covers a small amount of recipes because we haven't added recipes to it.  There are alot of other possible options too.  Maybe Thaumcraft ore clusters?

**Comment by richardhendricks** [comment]
Infernal bricks would be a great use for this.  Currently only needed for the advanced coke oven.

**Comment by bartimaeusnek** [comment]
@richardhendricks Right now it is Infernal Bricks and stairs, Thaumcraft ore clusters can be processed in there, i added Bronze Blast Furnace recipes to allow a bit more use of this thing.

**Comment by noobyaran9** [comment]
>Actually, it isn't centivs, it's essentia.

EYYYYY guess what, instead of taking centivis, now it takes essentia which is way easier to get than a node. Great, another reason to shoot down this idea.

**Comment by 0lafe** [comment]
There's just no need for it. We can smelt stuff in the ebf no problem, it's kind of the center piece for smelting. I feel like we don't need another smelter, unless it's another adv ebf, that would be cool

**Comment by Dream-Master** [comment]
ok we let it like it is.
