### ISSUE TITLE
T2 rocket schematic (Mars)

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#3013]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#

Schematics Rocket Tier 2 Chip crafting in EV circuit assembler and assembler asks to craft improved ender eye. And we need radon for it. 
![](https://i.imgur.com/g5gqTkO.png)
![](https://i.imgur.com/M4MrlLn.png)
![](https://i.imgur.com/hWCBvRb.png)
![](https://i.imgur.com/dgJZHQs.png)

It's intended? 
And if yes, where we should get radon, if all uranium ore veins located on Mars?

**Comment by draknyte1** [comment]
Even the GT++ Radon production method relies on Uranium Ore.

**Comment by Dream-Master** [comment]
Yes this need a change

**Comment by Dream-Master** [comment]
maybe all 1 tier down

**Comment by bartimaeusnek** [comment]
@Usernm0 
http://jenkins.usrv.eu:8080/job/GTNewHorizons-Core-Mod/
here you go exchange your GTNewHorizons-Core-Mod from your mod dir with the one linked above, or wait until the next version.

**Comment by CalterOK** [comment]
In fact, there is a way to get uranium ore and before flying to Mars.
![2018-02-03_12 02 39](https://user-images.githubusercontent.com/35035276/40625026-a1e398b4-62b8-11e8-85fa-42ebca719ca9.png)

**Comment by bartimaeusnek** [comment]
@CalterOK you still need uranium for that...

**Comment by CalterOK** [comment]
Then there is the recipe for obtaining the initial uranium
