### ISSUE TITLE
Not create generator upgrade

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/NewHorizons#3014]
Which modpack version are you using?
2.0.2.7

 If in multiplayer; On which server does this happen? 
Epsilon

 What did you try to do, and what did you expect to happen?

I wanted to do generator upgrade from a mods opencomputers. Could not do, since it is made from a generator from IndustrilCraft, the recipe is turned off
 
![generator upgrade](https://user-images.githubusercontent.com/39701746/40618282-b493bf26-6299-11e8-97e3-cd0ac205df1d.png)

 What happend instead? (Attach screenshots if needed)
You can not create  generator upgrade

 What do you suggest instead/what changes do you propose?
Replaced Industril Generator by Stirling generator

**Comment by bartimaeusnek** [comment]
fixed in 2.0.3.0 or 2.0.4.0
