### ISSUE TITLE
GT++ cryogenic freezer 

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3016]
#### Which modpack version are you using?
2.0.4.1

Gelid cyrotheum which is needed to run this multi block can not be obtained in the liquid form.

**Comment by bartimaeusnek** [comment]
@draknyte1

**Comment by Dream-Master** [comment]
Duct Tape
![image](https://user-images.githubusercontent.com/2970688/40887612-a45fef88-674b-11e8-83a0-4a0859611a17.png)
![image](https://user-images.githubusercontent.com/2970688/40887613-a8c11de0-674b-11e8-85d1-9a21a7a5bca4.png)

**Comment by draknyte1** [comment]
Should be fixed in latest releases of GT++.

**Comment by Dream-Master** [comment]
@draknyte1 schould i remove recipes i add via minetweaker ?

**Comment by draknyte1** [comment]
Yeah, whenever you release an update with newer gt++, probably a good idea.
Give the testers a few days to make sure everything is ready for you.
