### ISSUE TITLE
Quest 1472

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3021]
#### Which modpack version are you using?
2.0.4.1
When crafting uses conventional thread, but in the quest require Meteoric Iron String
![2018-05-29_10 22 12](https://user-images.githubusercontent.com/35035276/40644019-8cba5096-632a-11e8-9c89-7bda9b2d23b7.png)
![2018-05-29_10 22 19](https://user-images.githubusercontent.com/35035276/40644020-8ce8c674-632a-11e8-9412-1d26cd845cec.png)

**Comment by Dream-Master** [comment]
ok I must change the text
