### ISSUE TITLE
Mod suggestion : Soundfilters & Chunk Animator

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#3023]
Hi team,

First of all, i began your modpack since Sunday after finished Infitech² : lot of quests, hard survival and some funkys mobs. Very hyped by your work ! Congratulations all :)

I add some client mods and i suggest you two of those I use : 

**Soundfilters :** 
[Curse link](https://minecraft.curseforge.com/projects/sound-filters)

_"This is a little client-side mod that makes sound more interesting. Right now it adds reverb to caves and mutes sounds when you're underwater and when the sound source is behind a wall."_

I like this mod, i use everywhere ^^ Pleasant at early game for cave exploration.
I think that will be a good idea to add on GTNH.

------------------------------------------------------------- 

**Chunk animator :** 
[Curse link](https://minecraft.curseforge.com/projects/chunk-animator)

_When new chunks are loaded in vanilla minecraft they simply "appear instantly", with this mod they can be animated to either appear from below or above. This mod shouldn't impact fps considerably because all it does is render chunks "somewhere else"._

Optional mod imo but can be interesting for GTNH. "Don't impact FPS considerably"

------------------------------------------------------------- 

Theses mods are lights btw (41ko and 16ko)

Have a nice day ;)

Best regards,

DV

**Comment by boubou19** [comment]
Soundfilters might improve the exploration aspect of the pack but for Chunk animator i don't see the point of this mod apart from as you say, impact fps and the thing is when you reach the end game of this pack, your base can kill your fps and you will not want to spend a few of your spare fps in chunk animation.

**Comment by WarlordWossman** [comment]
Yeah the chunk animation I don't want, the other mod I would have to check out.

**Comment by DV666** [comment]
Yeah ofc for Chunk animator ^^ I can understand but FPS drop is petty for information.

But i prefer to see Soundfilters on your modpack, that's will be great :) Hope you will enjoy it.

**Comment by Bryfer** [comment]
Since both of these mods are client side only, I believe a better place for them would be the official forums, and let players choose for themselves wherever to include them or not :)
https://www.gtnewhorizons.com/forum/m/36844562/viewforum/7969672
