### ISSUE TITLE
Rose Gold - missing Mixer recipe

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/NewHorizons#3024]
There is a missing Mixer recipe for rose gold, mixing 4 gold dust + 1 copper dust = 5 rose gold dust.
There are only recipes using tiny pile and small pile.

#2229 see also 1.

**Comment by Dream-Master** [comment]
i guess gt++ overriding ere somethings. Will check

**Comment by draknyte1** [comment]
Tumbaga mixer recipe gets added before GT adds Rose Golds mixer recipe.
Version information helps, as this is probably fixed in 2.4.2.

**Comment by Dream-Master** [comment]
@draknyte1 why Tumbaga not use a circuit
![image](https://user-images.githubusercontent.com/2970688/40745939-30f18dd0-6459-11e8-9cd9-7165c03ef7e0.png)
