### ISSUE TITLE
Carpenter's Blocks Slopes really annoying to make now

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#3026]
#### Which modpack version are you using?
2.0.4.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Make carpenter's slopes that I use everywhere the way I have always done.
#
#### What happend instead? (Attach screenshots if needed)
Pressure plates got nerfed to require iron springs in the assembler.  That's all well and good, except for some reason, a lot of carpenter's blocks recipes treat pressure plates as slabs (I guess because there isn't a carpenter's slab item).  As a result, carpenter's slopes are significantly more annoying to make, and the ratios have been halved as well.  Where you would normally (pre 2.0.4.0) get 1 C.Block -> 2 pressure plate -> 2 slope blocks, it's now 2 C.Block + iron spring -> 2 pressure plate -> 2 slope block.
#
#### What do you suggest instead/what changes do you propose?
I personally don't think the carpenter's slope block should be based on the pressure plate.  Slopes don't even have springs in them?  Since there isn't a carpenter's slab, just make it so you can cut a carpenter's block into 2 slope blocks in the cutting machine, since the recipe to cut blocks into pressure plates no longer would conflict as it has been removed.  

I use slopes a lot, and they are purely a decorative item, so this seems like a pretty heavy nerf for what it is.

**Comment by Dream-Master** [comment]
Sure will change the recipe.
