### ISSUE TITLE
Hopefully the last Wand changes

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3028]
#### Which modpack version are you using?
2.0.4.0
#

Some wands have wrong recipes:
 - Thauminite Bossed Thaumic Sceptre consts 105 Vis (should be 125)
 - Manasteel and Vinteum Bossed Void Sceptrs have the same Recipe as the Wands
 - Elementium Kissed Thaumic Wand/Sceptre requires both 175 Vis (should be 105/130)
 - Sojourner's and Mechanist's Amber Wands/ Sceptres etc. have the wrong TF item and screws (Should be lich bones + stainless steel screws)

**Comment by noobyaran9** [comment]
>Manasteel and Vinteum Bossed Void Sceptrs have the same Recipe as the Wands
Elementium Kissed Thaumic Wand/Sceptre requires both 175 Vis (should be 105/130)

Manasteel and Elementium wand could be removed as we dont have botania in the pack.

**Comment by Dream-Master** [comment]
no why. @noobyaran9  I like the additional wands.

**Comment by noobyaran9** [comment]
The point is without botania u cant get elementium and mana steel.

**Comment by noobyaran9** [comment]
And the wand is worthless without botania in the pack

**Comment by Dream-Master** [comment]
That's wrong. look at the recipes. And if not I add some.

**Comment by Dream-Master** [comment]
why the wand is worthless?

**Comment by noobyaran9** [comment]
The wand will recharges itself with mana from botania slowly. However, without botania its just a plain normal wand.

**Comment by Dream-Master** [comment]
@Zoko061602 thanks
