### ISSUE TITLE
Spray can system requires attention

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#3031]
#### Which modpack version are you using?
V 2.0.4.2 (And probably many before it)
#

#### What did you try to do, and what did you expect to happen?
I'm currently working on a resource pack  tailored for GT:NH, but you knew that. 
Retexturing machine casings produced some odd effects.
#

#### What happened instead? (Attach screenshots if needed)
The machine frames became discoloured, as if blue and green were augmented. Poking around in the code revealed this was to do with the incomplete Spray Cans system, such that a white spray can change this blue-augmented texture into the one found in the mod's assets. This makes texture designing tricky, as I aim to have my machine casings reflect the metal used to craft them, which I do so by using the ingot's colour as defined in materials.class which is wrecked on the texture being applied to machines and recieving a change. Not to mention, the blue tint in the GUI is horribly ugly.
#
#### What do you suggest instead/what changes do you propose?
This system is incomplete, with currently no means of removing spray colour from machines. Therefore, I see no need that default textures need to be modified to accommodate this. If this renders the white spay can useless, instead have it lower saturation and up contrast, or up the lightness of the texture.

Further, a means to remove a spray colour from a machine without breaking it needs to be considered.

**Comment by richardhendricks** [comment]
Removing spray colour ticket is at https://github.com/GTNewHorizons/NewHorizons/issues/3032

This ticket will discuss the application of the  MACHINE_METAL color to GT machine textures by default.  The old GT system used grey textures and mixed in  MACHINE_METAL (210.220.255) to the textures to make them a little more "metallic" looking.  White dye removes the MACHINE_METAL dye, and restores the original texture as-presented in the texture file.

Removing the MACHINE_METAL application would change the look for everyone, really need to get good consensus here on what the group wants.

https://github.com/Blood-Asp/GT5-Unofficial/blob/f70c7d40461a97f686d89c7020d33f4a8b88c266/src/main/java/gregtech/common/blocks/GT_Block_Casings1.java#L97

https://github.com/Blood-Asp/GT5-Unofficial/blob/f70c7d40461a97f686d89c7020d33f4a8b88c266/src/main/java/gregtech/common/blocks/GT_Block_Casings2.java#L59

https://github.com/Blood-Asp/GT5-Unofficial/blob/f70c7d40461a97f686d89c7020d33f4a8b88c266/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PyrolyseOven.java#L27

https://github.com/Blood-Asp/GT5-Unofficial/blob/7cc77f5abfce652c50f7876af236dc057a0ce209/src/main/java/gregtech/api/enums/Textures.java#L625

Might be best to make this some kind of config option vs just changing the code.
