### ISSUE TITLE
Feather wings (Works like in anime!)

### ISSUE THREAD

**Issue by Kiwieee** [GTNewHorizons/NewHorizons#3033]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Attempting to craft feather duct-taped wings

#### What happend instead? (Attach screenshots if needed)
After researching the wings with thaumcraft there appears to be no recipe for Cardboard sheets.

#
#### What do you suggest instead/what changes do you propose?
Either a recipe needs to be added or, possibly it's not a bug and there is simply a locked recipe.

Perhaps a hint in the questbook or a research line needs to be changed to unlock cardboard before the wings

**Comment by Dream-Master** [comment]
will check

**Comment by Kiwieee** [comment]
Not that i can find 0lafe, doesn't work with gregtech cardboard either

**Comment by Dream-Master** [comment]
No i never add this recipe :P 
Nice to see now somone test it :P

**Comment by Dream-Master** [comment]
It was just there but had wrong meta id.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40887341-aca9ae9e-6747-11e8-88d6-b324457afc50.png)
