### ISSUE TITLE
Farm control crafting bug

### ISSUE THREAD

**Issue by Kiwieee** [GTNewHorizons/NewHorizons#3035]
#### Which modpack version are you using?
 2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?

Crafting farm control blocks
#
#### What happend instead? (Attach screenshots if needed)

In order to craft the farm control block it requires farm control blocks
#
#### What do you suggest instead/what changes do you propose?

Change the recipe to farm block like the hatch, gearbox etc.

**Comment by Dream-Master** [comment]
ok will fix.
