### ISSUE TITLE
Bee produce bug. Lore Fragments 7404 @Magic Bees

### ISSUE THREAD

**Issue by bashduude** [GTNewHorizons/NewHorizons#3036]
#### Which modpack version are you using?
2042
# 

Neither Savant or Scholarly bees produce Lore Fragments(7404)

![image](https://user-images.githubusercontent.com/32778092/40883636-d1acd334-670a-11e8-9a0c-87f99041b5ca.png)
![image](https://user-images.githubusercontent.com/32778092/40883638-f42a73da-670a-11e8-9cd0-ff2ac2bc9813.png)

**Comment by Dream-Master** [comment]
it will produce it but it required some block or some special biome to do it.

**Comment by bashduude** [comment]
This is the bee i use. (Tested with Savant in creative, wasn't working as well)
![image](https://user-images.githubusercontent.com/32778092/40886081-630104ac-673a-11e8-9332-0b2258340ded.png)
![image](https://user-images.githubusercontent.com/32778092/40886082-6b248316-673a-11e8-87ea-bda5ceceabdb.png)

Current Biome: Magical Forest

**Comment by mitchej123** [comment]
You need to be in the bee's ideal climate, normal/arid in this case,  to get special drops.  You can fake that with the aleveary upgrades or the industrial aviary with the right climate mod.

Acclimated bees will only produce the primary output in other climates.

**Comment by Dream-Master** [comment]
and     B:Thaumcraft=true so it must be enabled.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/40887139-3590d3d0-6744-11e8-98b0-9969506f3aae.png)

![image](https://user-images.githubusercontent.com/2970688/40887152-4dcfdaae-6744-11e8-8f91-6028234c9156.png)

**Comment by bashduude** [comment]
Thanks for the help guys.  Now i know...
