### ISSUE TITLE
Vortex attentuator has 0 hardness, but can only be harvested with a pickaxe

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3037]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I punched the block in a playful manner
#
#### What happend instead? (Attach screenshots if needed)
It broke instantly without dropping the item
#
#### What do you suggest instead/what changes do you propose?
Either increase the hardness or make it harvestable by hand

**Comment by Dream-Master** [comment]
Which mod add it?

**Comment by KiloJoel** [comment]
Thaumic horizons

**Comment by Dream-Master** [comment]
Will try to reset it with iguana tweaks

**Comment by Dream-Master** [comment]
There is no entry for this Block. With out change code in TH i cant do much.
