### ISSUE TITLE
New Quests/Ideas

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3042]
- [ ] Bag Packs for Coins (Exploring Coins)
- [ ] Oil in Furnaces like Creosote (64 Items)
- [ ] Cotton for coins

**Comment by WarlordWossman** [comment]
Checkbox quest that explains the dimension names and their short forms used in the NEI ore vein thing.
Pretty similar to how we did it for maintenance.

**Comment by richardhendricks** [comment]
Quest for the NEI ore vein thing completed.  Also explains how to find ores.

**Comment by Dream-Master** [comment]
Oil in Furnaces like Creosote (64 Items) is this a good idea ? @WarlordWossman @richardhendricks @bartimaeusnek

**Comment by richardhendricks** [comment]
I don't see it as a good idea.  Oil is super dangerous to walk around/mess around in - IMO lava is less dangerous.  Who would bother collecting it with a bucket to burn it in a furnace? By the time you can process it, you should have the Railcraft 2x2 steam furnace (9 items at a time) or a multi-smelter.

**Comment by WarlordWossman** [comment]
No oil furnace recipe, steam and LV furnace are not too great anyways, no need to discourage getting them further. Oil is important enough already.

**Comment by richardhendricks** [comment]
I can add a cotton quest for ic2 crops. Do we need anything else from this ticket?

**Comment by Dream-Master** [comment]
sure add cotton. Maybe backpacks missing.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57201464-c6893300-6f5e-11e9-9e3b-2f2f398f2fb3.png)

**Comment by richardhendricks** [comment]
New coins quest
![image](https://user-images.githubusercontent.com/1214811/57201507-647cfd80-6f5f-11e9-9815-ead6ccad338c.png)
