### ISSUE TITLE
MV Multiblock Goals gating

### ISSUE THREAD

**Issue by Krispion** [GTNewHorizons/NewHorizons#3043]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Many of the Multiblock Goals quests are gated by the MV Steam Turbine quest.
#
#### What do you suggest instead/what changes do you propose?
They should instead be unlocked with the MV Machine Hull quest for any players who do not wish to continue with steam power, unless there is some good reason for this.

**Comment by Dream-Master** [comment]
Yes will change it.

**Comment by Krispion** [comment]
The Coal Steam Jetpack is also gated behind the MV Steam Turbine.

**Comment by Dream-Master** [comment]
ok need to  check
