### ISSUE TITLE
[RFC] Ore finding balance

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3046]
Looking at adding IFU low-tech scanner mod <https://github.com/GTNewHorizons/IFU>

Tiering structure under proposal
(parts of this still need work)

IFU -> pre-steam for diamond/redstone/lapis/tin/copper. Limit to only work on OW (or maybe OW ores via whitelist)
 - Work needed: Change default config to depth=60
 - Work needed: Add whitelist/blacklist functionality, either by ore or dimension. Message to player "The orefinder doesn't appear to work here - you'll need a high tech method to find ores"
 - Work needed: Work with crushed ores to find main ores - so small ores can lead to main veins.

seismic prospector -> LV/MV/HV for mica/oil/moon/large quantity ores.  HV needs MV needs LV to craft.  Lv does 1x1 chunk, MV does 3x3 chunks, HV does 5x5 chunks. Uses scanner/printer/assembler.  Quests currently reward a couple of data sticks so players can search multiple spots pretty easily. (remove small ores)
 - Work needed: Implement multiple chunk functionality.
 - Work needed: Change quest to use MV prospector instead of LV
 - Work needed: Fix assembler output so that recipe doesn't overlap books (happened to delete books, not sure exact cause).

basic prospector scanner -> EV/IV for mars/large quantity veins, etc. Reports ores but not locations directly in gui. Recipe needs Forge Hammer and HV seismic prospector. EV scans 3x3 chunks, can do ~10 scans before needing recharge. IV scans 5x5 chunks, can do ~25 scans before recharge.
 - Based on Datrev/electronic prospector but without detailed map. Tradeoff with seismic prospector is that it cannot show exact locations of ores, just ores in the vicinity. Requires creating new GUI.

eletronic prospector -> LuV, adds GUI with detailed information on ores found & locations.

For new SSP/new servers, the oregen now is pretty good, but with the officials and older servers, the oregen is kinda harsh, so tools like this would make experience much better for new players.

**Comment by 0lafe** [comment]
Guess Ill throw this into the GitHub to make it official, but I think for the IFU you should have to get the ore yourself before you can use it, making it useful for finding more veins, but not for the first one. I think eliminating the digging for veins aspect is a bad idea. Anyway, finding those veins really isn't that bad with the new ore gen.

**Comment by Dream-Master** [comment]
I make a choice reward (when crafting IFU) you can choose one ore block you will start with but not more.
And btw we need a good recipe for it.

**Comment by richardhendricks** [comment]
We can set the quest after they should have at least found a couple of iron veins. Maybe
stick, knife, stick
stick, gold ingot, stick
empty, iron, empty

Gold and iron ingots means player has to find a gold/magnetite,or get gold via other means like loot or melting gold drops.  So player still has to search for veins for at least a little while.

**Comment by richardhendricks** [comment]
Small ores in the OW

Copper | 35 | 0 | 60-180
Tin | 57 | 0 | 80-220
Coal | 535 | 0 | 120-250
Iron | 32 | 0 | 40-100
Zinc | 36 | 0 | 80-210
Gold | 86 | 0 | 20-60
Silver | 54 | 0 | 20-60
Nickel | 34 | 0 | 80-150
Lapis | 526 | 0 | 10-50
Diamond | 500 | 0 | 5-15
Redstone | 810 | 0 | 5-25

**Comment by richardhendricks** [comment]
So copper/tin/nickel/coal crushed can be found looking in higher mountains.
gold/lapis/diamond/redstone can be found deeper in the ground
zinc/silver don't have direct veins in the OW

mica vein would be findable with this tool if we allow crushed tin to find cassiterite, but it might be hard since you would find every cassiterite sand vein as well.

OW veins without small ores | weight
--------------------------
Mineral sands |  80
Manganese |  20
Salts |  50
Apatite | 60
Kaolinite | 60
Dolomite | 40

**Comment by WarlordWossman** [comment]
It can use iron since that's an easy find most of the time, gold is not the best idea tho.
Also mining holes will still be a viable strat, it's just that it feels a little off if you have bad rng.

**Comment by mitchej123** [comment]
> I think eliminating the digging for veins aspect is a bad idea

I hate this mechanic.  Dig down every 3 chunks to maybe find what you want.  Waste. Of. Time. for no good reason other than "back in my day I had to do it!".  Also boo RNG.  Finding my first redstone deposit was a giant pain that had me on the verge of quitting.  It wasn't fun, it wasn't skill, it was RNG + crappy ore gen + wasted time.  I know others have had similar experiences with mica, etc.

I'm a big fan of adding a tiered approach to less RNG/mindless time sink finding the ores needed as you progress through the tiers without mindless digging.


On a related note - I've really enjoyed the sevtech mechanic with ore samples on top, and then a divining rod to find any ores within 48 blocks (straight line).  The veins were big, but smaller than GT so it was a bit challenging to find exactly where within the chunk it was.

**Comment by repo-alt** [comment]
> On a related note - I've really enjoyed the sevtech mechanic with ore samples on top, and then a divining rod to find any ores within 48 blocks (straight line). The veins were big, but smaller than GT so it was a bit challenging to find exactly where within the chunk it was.

This is essentially TFC mechanics, years old. GT6 also introduced ore samples recently. Unfortunately it is not a small change, to be easily backported.

**Comment by richardhendricks** [comment]
Adding it is probably not super difficult.  We would just put down scattered crushed ores on the surface (dirts/stones/cobbles/clays should cover all the options).  Or we could scatter small ores that match one or all of the 4 vein ores into the whole chunk. Fast vertical mining would still be needed but if you happen to hit one of the small ores you could stop and move on.

The issue would be that the servers would still be old oregen, at least on OW.
