### ISSUE TITLE
[Quest] [ID:1299] AE2 Quest Energy Cell cant be submitted

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3047]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Tryed to submit the quest that tells you to build a energy cell from ae2 (QuestID:1299)
#
#### What happend instead? (Attach screenshots if needed)
Simply did not detect the one i build

![2018-06-04_23 14 04](https://user-images.githubusercontent.com/29660362/40942075-41202d40-684d-11e8-8a03-070e3c5ff21c.png)
![2018-06-04_23 14 10](https://user-images.githubusercontent.com/29660362/40942076-41449f36-684d-11e8-87bc-3039969eedb3.png)

#
#### What do you suggest instead/what changes do you propose?
Maybe a wrong tag or something, just check it

**Comment by Dream-Master** [comment]
will check
