### ISSUE TITLE
Top Tier pumping

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3049]
#### Which modpack version are you using?
2.0.4.2
#### What do you suggest instead/what changes do you propose?

GT++ adds a pump that does essentially infinite L/s of moving fluids, but costs much, much less than even the UV pump. My suggestion is to remove the gt++ pump, and give whatever the highest tier GT pump that ability. Which is UHV now

**Comment by Dream-Master** [comment]
Yea I disable the pump so long we not balancing it for gtnh.

**Comment by draknyte1** [comment]
I never got a ticket for it, so.. I've never touched it
:shrug:
Can't add recipes for my MAX tier components on my end anyway
Because I can't add Assembly Line recipes..

**Comment by Dream-Master** [comment]
No mx tier components needed i add them as uhv components allready in my core mod. Will check the recipe.
