### ISSUE TITLE
Transparent Block texture

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#305]
@Namikon 
Can i make transparent Textures without X Raying all underneath or is this not implemented in simple blocks yet?
https://www.dropbox.com/s/edwousroc4f33sm/Screenshot%202015-08-09%2013.43.41.png?dl=0
https://www.dropbox.com/s/0vc8iwrig7yu7ay/Screenshot%202015-08-09%2014.01.27.png?dl=0

**Comment by Drobac** [comment]
There is a draconic evolution block that works as x ray, ill check the name when im home but the texture is like a blue flame

**Comment by Dream-Master** [comment]
Yes exactly with my Item. But i think we have to add a option to the ymcore that i can define this in code.
I try it with material glass, ice, iron, rock etc. For now i will fill the texture with with color so long we have another solution.

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/woliidl2rvt017z/Screenshot%202015-08-09%2015.20.34.png?dl=0

**Comment by Namikon** [comment]
I don't think transparent textures are handled correctly, you could try to use the opacity setting to make a block "transparent"

**Comment by Namikon** [comment]
Never mind, i just saw the screenshot. I don't know what's necessary to make such a partially-transparent block. If the opacity and transparent settings don't work, then there is currently no way of doing this. Stick with your texture for now; I'll check GT/IC2 source core on how to draw these scaffolds

**Comment by Dream-Master** [comment]
It have to works like minecraft Glass. There is a option to set Translucent on true or false but i not able to code this. i change the texture for now and change it later back. No rush.

**Comment by Dream-Master** [comment]
:+1:
