### ISSUE TITLE
Dirt/clay recipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3050]
Some ideas for dirt and clay

Loamy dirt/Coarse loamy dirt -> Centrifuge to dirt + small pile of clay dust 33% 30EU/t

Sandy dirt/coarse sandy dirt -> centrifuge to dirt + small pile of flint dust 33% 30 EU/t

Silty dirt/Coarse silty dirt -> centrifuge to dirt + small pile of quartz sand 33% 30 EU/t

Dried dirt (dirt in furnace) - > centrifuge to 90% small clay + 50% sand + tiny pile of ashes 25%

8 small clay piles + bucket of water (clay bucket too) -> 3 clay balls
Mixer recipe with 8 small clay piles + 1000L of water-> 4 clay balls 8 EU/t

BoP mudball in extractor -> 1  clay ball 2 EU/t

Should help with servers becoming clay poor with clay extraction holes left everywhere. Players can still opt to search for clay for their 10 coke ovens/4 BBfs, bricks, etc but with this once they have a steam macerator they can  get clay dusts from hardened clay and turn them back into clay balls.  Or they can extract clay from BoP mudballs, which a re kinda useless right now. 

Plus once they hit LV they can centrifuge dirts for additional clay dust too.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/5e2dcb771708fafa04851fd6d73d0d69571eb73a
