### ISSUE TITLE
Assembler Recipes More Expensive?

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/NewHorizons#3052]
#### Which modpack version are you using?

2.0.4.0

#### What did you try to do, and what did you expect to happen?

Use the assembler for slightly cheaper or identical recipes for components.

#### What happend instead? (Attach screenshots if needed)

Many components of various tiers have more expensive (a tier higher) circuit requirements in the assembler that don't really reward using/making the assembler. You can simply shaped craft them for much cheaper.

#### What do you suggest instead/what changes do you propose?

Adjust assembler versions of component recipes to be the same as shaped, or even require -slightly- less materials.

**Comment by Dream-Master** [comment]
can you add pics please @Axiflare ?

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/453921314701574175/454028262046433280/for_dream.png
