### ISSUE TITLE
2.0.4.2 - Lookup cinabar usage crashes game

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#3053]
#### Which modpack version are you using?
2.0.4.2

#
#### If in multiplayer; On which server does this happen? 
www,digtobuild.com

#
#### What did you try to do, and what did you expect to happen?
Lookup uses for GT cinabar crashes thet game

**Comment by Dream-Master** [comment]
crashlog?
fml log?
Cinnabar Ore?

**Comment by Dream-Master** [comment]
[crash-2018-06-06_17.13.21-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2076884/crash-2018-06-06_17.13.21-client.txt)

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by richardhendricks** [comment]
Looks like it is related to infernal blast furnace recipes

**Comment by Dream-Master** [comment]
fixed allready.

**Comment by Dream-Master** [comment]
thanks to @bartimaeusnek
