### ISSUE TITLE
Missing recipe on SMP : Casting Form (Coinage Mold)

### ISSUE THREAD

**Issue by mergendil** [GTNewHorizons/NewHorizons#3055]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
multiplayer, from the player who played on the shut down server Trilexnet

#
#### What did you try to do, and what did you expect to happen?
Trying to make the coin mold
#
#### What happend instead? (Attach screenshots if needed)
No recipe for the casting form
#
#### What do you suggest instead/what changes do you propose?
Add one

**Comment by richardhendricks** [comment]
Which coins are you trying to make?  I assume the chunkloader coins?

**Comment by Dream-Master** [comment]
This coins have a recipe i guess but i will check. Only Server not have it.

**Comment by mergendil** [comment]
both chunkloaders and the coins for the alkalus disc.
Yes it's on a server

**Comment by Dream-Master** [comment]
Server Admins have to decide to add a recipes or get the coins via jobs or quests etc.

**Comment by Dream-Master** [comment]
or use the zzclient.zs script

**Comment by Dream-Master** [comment]
from sp
