### ISSUE TITLE
Add quests on BQ and Aromabackup

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3056]
Let players know they have to use legitimate copies of minecraft, and have to be logged into Mojang servers for UUID or else they will lose quest progress.

Let SSP players know to install a backup mod

Let players know that their journeymaps/waypoints are not backed up by the mod, and even SMP will need to backup the journeymaps folder occasionally.

**Comment by Dream-Master** [comment]
About legal copy: Not need it in the questbook. Who steel software not get any support.
About aroma backup: People can easyly copy the folders and make a zip/rar file to save it. It's only save folder and journeymaps. Maybe a note can be added to the quest book.

**Comment by richardhendricks** [comment]
I know, just want to prevent dumb questions in discord.  And we aren't supporting stolen minecraft, just warning pirates they will not work.  I suppose we can tell them to get lost too.

**Comment by Dream-Master** [comment]
yes but max as quest text.

**Comment by richardhendricks** [comment]
yeah these are just information quests, no tasks or rewards. 👯‍♂️

**Comment by Dream-Master** [comment]
:package:

**Comment by CalterOK** [comment]
Perhaps it's worth adding 1 more quest with the team to update the quest book (/bq_admin default load).

**Comment by bartimaeusnek** [comment]
or using my command blocks if they are in SSP

**Comment by richardhendricks** [comment]
There's already a quest covering that
