### ISSUE TITLE
Superconductor Wire processing times are too much

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/NewHorizons#3057]
#### Which modpack version are you using?
2.0.4.0
#
#### If in multiplayer; On which server does this happen? 
Private multiplayer
#
#### What did you try to do, and what did you expect to happen?
I was looking into the recipe for a full fusion reactor and saw that you need 32 Coil Blocks, which, if you come from LuV tier (the stage you're at when you can first build a fusion reactor), require 8192 LuV superconductor wires.
That comes out to 4096 superconductor base ingots. In terms of materials, this is not that bad since mixer recipes give you quantities that are the sum of all the components so you'll make a ton at a time.

But time-wise, because of the recent vacuum freezer recipe nerfs, 4096 ingots takes:
At minimum HV, 4096*750 seconds = 35.6 days.
Overclock it to IV or LuV, and you have 8.9 and 4.5 days, respectively. I'm all for making this pack "hard" , but that's actually just insane. It takes a little over 3 times longer to vacuum freeze an ingot than it took to EBF it.

This means I'd have to have 8 or 9 IV vacuum freezers, literally running 24/7 to get this job done within a day.
#### What do you suggest instead/what changes do you propose?
Can these recipes be looked at again and re balanced? These recipe times are just ridiculous. Non-superconductor vacuum recipes take at most 60~ seconds max but these superconductor recipes are 10x more than the highest non-superconductor recipe. 

The funny thing is that the fusion reactor allows you to make insane amounts of energy once you have it, but according to these recipes, you need an ALREADY existing source of immense energy to make a fusion reactor in a reasonable amount of time.

**Comment by 0lafe** [comment]
>This means I'd have to have 8 or 9 IV vacuum freezers, literally running 24/7 to get this job done within a day.

Or 1 zpm freezer, which is totally fair for something that can do 3+A UV at mk1. 

But yes, it's dumb that the freeze recipe is so much longer than the ebf time, but wasn't that fixed? I remember seeing something about lowering the times already. 

Also, what are the coils for? The assembly line recipe for the controller?

**Comment by Anarack** [comment]
You can use zpm wires to massively cut down on the resources and time required, yes they can be produced at that tier, though a bit tricky to get the samarium. Though the vacuum freeze time are strange for super conductors however. You can also use the gt++ freezer to speed things up once you can make cryothium, but you can get that as a liquid in .4.2 so that won't help for now. 

The change for the vacuum freezer times was to adjust them for all materials that used it, though idk what the times are based on, and that got reverted anyway.

**Comment by 0lafe** [comment]
Idk about completely. That thing does 4x speed max, 2x min. That's not really enough to compensate for the kinds of times that are there. There's no reason a vac freezer recipe should be slower than the ebf part. Ebf gets tons of speed from coil upgrades, and you end up needing lots of ebfs. Why make someone have like 80vac freezers. 

I also don't like the idea of forcing the use of a gt++ machine.

**Comment by Krispion** [comment]
Is it 4x max and 2x min? I haven't tested it but according to the tooltip it says "four Vacuum Freezer Recipes at double speed" so I would assume 8x speed at 4x power consumption and some saved space. Might need clarification in the text if so.

**Comment by 0lafe** [comment]
>8x speed at 4x power consumption

yea that is 4x speed. Normally 4x power gives you 2x speed, but here it gives you 8x which is 4x normal. It basically tries to under clock the recipe once and split it among 4 machines, but cut the recipe time in half. So an IV one would function as 4 EV freezers with 2x speed. 

One problem from what I can tell is that if the recipe is the tier you power it at, you only get the 2x bonus. Because you can't have 4 EV freezers doing an IV recipe. That's my problem with the adv ebf too, ZPM smelting neutronium will be the same speed as using the normal ebf.

**Comment by Krispion** [comment]
>yea that is 4x speed. Normally 4x power gives you 2x speed, but here it gives you 8x which is 4x normal
Semantic misunderstanding then, thought you were saying it was effectively 2x normal at max or 1x at minimum.

Perhaps a mix of time reduction and the Cryogenic Freezer could work, although from what you say it would depend on how comfortable it is to use, but the possibility is out there. Couldn't judge how much from where I am.

**Comment by Prewf** [comment]
>Also, what are the coils for? The assembly line recipe for the controller?
Oh I forgot to mention in my original post hah. These coils are for physical placement in the world (in a circle) which is why it needs so many. I forgot that the controller itself also needs a coil block..

I'm all for using GT++ machines too, I love em. But to make progression practically dependent on them is something I haven't encountered before in my playthrough.

True, I can make ZPM superconductors instead (and I probably will, if nothing comes of this discussion), but that begs the question of why the LuV recipe even exists? I can make both LuV and ZPM superconds at LuV tier, one does not require significantly more resources than the other and one is clearly better to make if you want to make coil blocks.

**Comment by 0lafe** [comment]
>Oh I forgot to mention in my original post hah. These coils are for physical placement in the world (in a circle) which is why it needs so many. I forgot that the controller itself also needs a coil block..

ah ty. Couldn't remember if mk1 needed coils or if it took something else. 

>Perhaps a mix of time reduction and the Cryogenic Freezer could work, although from what you say it would depend on how comfortable it is to use, but the possibility is out there. Couldn't judge how much from where I am.

I think right now I don't like where the cryogenic freezer is enough to agree fully. If it changes I might be more on board. I don't like how in some cases it's just doing 2x speed. 

>I'm all for using GT++ machines too, I love em. But to make progression practically dependent on them is something I haven't encountered before in my playthrough.

I think what we're seeing right now is just a goof on the times of vacuum freezing, and it showing that late game vacuum freezing doesn't really work. Then Gt++ having the only thing that can possibly tackle these impossibly high recipe times. 

>True, I can make ZPM superconductors instead (and I probably will, if nothing comes of this discussion), but that begs the question of why the LuV recipe even exists? I can make both LuV and ZPM superconds at LuV tier, one does not require significantly more resources than the other and one is clearly better to make if you want to make coil blocks.

Maybe dream balanced them for use, and not for crafting superconductor coils, but maybe it should be changed? Does that mean harder zpm superconductors though?

**Comment by Prewf** [comment]
>Does that mean harder zpm superconductors though?

Yeah that's basically what I was thinking. That would be, assuming the LuV superconductors are scaled down too hah

**Comment by WarlordWossman** [comment]
>I'm all for using GT++ machines too, I love em. But to make progression practically dependent on them is something I haven't encountered before in my playthrough.

I think there is nothing wrong with that, always thought the vacuum freezer on its own was a bit boring and I like how the cyrogenic freezer needs the extra input. Would have to test it tho.

**Comment by 0lafe** [comment]
>I think there is nothing wrong with that, always thought the vacuum freezer on its own was a bit boring and I like how the cyrogenic freezer needs the extra input. Would have to test it tho.

Depending on how the freezer works, and the recipe for cryothium, I might agree with you. I'd love to see something that makes you add more input for it to work better than the normal multiblocks, and vac freezers are one of the suckier ones. Just wish it worked different with the whole mechanic of it. I'd love to see something more inline with the PSS, takes some tiered block that dictates how many times it can overclock the recipe. I think there should be a much, much higher tier multiblock, which could be the adv. freezer, or something else to replace it for higher tiers.

**Comment by WarlordWossman** [comment]
I like the idea of different coolants having different speed multipliers, but idk how possible that would be.

**Comment by Dream-Master** [comment]
@Prewf vac freezer recipes are now short as they was before the change.

**Comment by Dream-Master** [comment]
@0lafe

**Comment by Dream-Master** [comment]
2.0.4.2 is the latest version

**Comment by Kortako** [comment]
@Dream-Master The vacuum freezer [commits ](https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/efe072d2ec04f0a82011ec4f8239abbb6551443e)you did in the CoreMod only touch certain ingots, and superconductor base isn't one of them.  It must be auto-generated from GT or something?

**Comment by 0lafe** [comment]
750s at HV means 93s at LuV. That's totally reasonable. What's the ingot smelting time? Smelting an ingot of that at 93s at LuV seems fair. Needing to have a vacuum freezer for every ebf, and needing it to be at the same tier is totally reasonable.

**Comment by Prewf** [comment]
Couple things..
1. I think I was mistaken when I said this was because of the vacuum freezer nerf. This recipe seems to have been in the game a few months after superconductors received the tiering change in 2.0.3.0, it's just that either nobody noticed or cared.
2. Here https://github.com/GTNewHorizons/NewHorizons/issues/2686 you can see one of the early recipes for the coil block back in March. That's 32 2x LuV wires in the final picture. So for some reason, between then and now, that was quadrupled up to be 64 4x LuV in the current patch. What was the reasoning behind the increase in time?

Also 93s at LuV is reasonable I guess, but you also have to make 4000 of them :\

**Comment by Prewf** [comment]
Would it be somewhat reasonable to revert the LuV recipe to be 32 2x LuV wires instead of 64 4x LuV? That's what it was back in March.

**Comment by Prewf** [comment]
If you want to, you can remove the LuV wire method of making the coil block and just have zpm and uhv wire recipes. The zpm way saves alot on resources and time compared to luv, and they're both doable at luv.

**Comment by Dream-Master** [comment]
yes then i remove LuV Wires if ZPM can do at LuV because you need it for Fusion

**Comment by Prewf** [comment]
u the best ty
