### ISSUE TITLE
Galgadorian Woodcutter is a bit expensive for what it does

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#3058]
#### Which modpack version are you using?
2.0.4.0 (same in latest, I imagine)
#
#### What happend? (Attach screenshots if needed)
The Galgadorian woodcutter is a bit expensive, needing LuV tier circuits in order to be crafted, where the alternatives can be utilized in late MV/HV, only needing stainless for the most part (TC Infusion -> Golems, or Farming Station with the healing axe)
#
#### What do you suggest instead/what changes do you propose?
Probably lower the Galgadorian woodcutter circuits to be HV tier circuits, or Workstations at the most.  Honestly the effectiveness of Steve's carts tree farms peters off a bit, so I don't think having "unlimited durability" is that big of a deal and super overpriced.  At the point you can make it currently, people probably aren't even using SC tree farms anymore.

**Comment by Kiwieee** [comment]
i agree with that, swapped over to a multifarm before bothering trying to upgrade the cart
