### ISSUE TITLE
Cleanroom maintenance hatch is yellow?

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#3059]
#### Which modpack version are you using?
2.0.4.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
At some point, I want to say ever since 2.0.2.7(?), the maintenance hatch texture stopped matching the rest of the cleanroom and instead is a shade of yellow.  It also makes texture packs not find any proper texture for that particular part.
#
#### What happend instead? (Attach screenshots if needed)
![2018-06-07_00 57 15](https://user-images.githubusercontent.com/5300243/41086335-8f2dcd2e-69ee-11e8-9cb5-4af8801d6d82.png)
![2018-06-07_00 55 45](https://user-images.githubusercontent.com/5300243/41086339-951ed12e-69ee-11e8-9134-1e441853ae34.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it please, if possible. :)

**Comment by Zoko061602** [comment]
#2813
