### ISSUE TITLE
Heavy Duty Alloy Ingot T5

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#306]
Atm uses 8 compressed Quantium plates, which need 3 quantium and you need about 40 plates for the rocket so you need more then 900 quantium for 1 rocket. In all my mining on venus which has been quite a lot i got maybe 300 quantium.

I suggest changing the recipe so the Heavy Duty T5 uses 2-3 Compressed Quantium plates

**Comment by Drobac** [comment]
so just for tier 5 rocket you needd 900, and more then 1000 for higher tier rockets

**Comment by Dream-Master** [comment]
1. You have Rocket recyling.
2. Building rockets is Team Work (My Idea as i making the recipes). A few Players building a Rocket together.
3. If i change this recipes i have to change the others too.
4. With the new Oregen Quantium is much more often available as versions before. It is often like Ledox or Mytryl.
5. I look into it and look what i can change.
(Are Quantum rare on the map or more often found ?)

**Comment by Dream-Master** [comment]
Atm
Tier 1 neds 3 different Plates
Tier 2 needs 2
Tier 3 needs 4
Tier 4 needs 6
Tier 5 needs 8
Tier 6 needs 10
Tier 7 needs 12
Tier 8 needs 14

**Comment by Drobac** [comment]
I tested it with the new oregen and it is much better now, before it was extremely rare and only found on  the surface, now you can tunnel near bedrock and find a decent ammount of it, so the issue is nonexistant and ill close it

**Comment by Dream-Master** [comment]
ok
