### ISSUE TITLE
Ghast quest needs to fix ghast size for smaller windows

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3062]
Change to using a pic of the minighast maybe?
![screenshotsception](https://user-images.githubusercontent.com/1214811/41110113-39032f8e-6a3e-11e8-81ef-6d09af162ae0.JPG)

**Comment by Dream-Master** [comment]
It cant so far i know.

**Comment by richardhendricks** [comment]
Can't change the size, added some wording that you need to kill 10.
