### ISSUE TITLE
Can't get Naquadah Alloy Dust from Mixer

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3064]
Version 2.0.4.2.
Trying to mix naq alloy dust in Mixer does not work.

**Comment by DualBallers** [comment]
Mixing of small and tiny piles to naq alloy still works.

**Comment by 0lafe** [comment]
Didn't this happen a few versions ago for some GT++ related reason? I remember seeing this before

**Comment by Dream-Master** [comment]
Same thing with rose gold. I go fix it quick. Gt++ interfears here in some way.

**Comment by Dream-Master** [comment]
Works for me
![image](https://user-images.githubusercontent.com/2970688/41172412-1903b5ac-6b54-11e8-93db-9facabca71d5.png)

**Comment by DualBallers** [comment]
Hey @Dream-Master. Did you fix it for next version.
I think it happens because the Trinium Naq Alloy recipe overwrites the Naq Alloy recipe.
![image](https://user-images.githubusercontent.com/30087707/41190769-04454fc2-6be5-11e8-9e63-adb0aac1ca8f.png)

**Comment by Dream-Master** [comment]
both recipes works. i test it in SP.

**Comment by DualBallers** [comment]
Tried it yesterday on v2.0.4.4 and still could not get the recipe to work.

**Comment by Dream-Master** [comment]
@draknyte1 can you please add a circuit to your nquadah alloy recipe. Thanks

**Comment by draknyte1** [comment]
Should be fixed in latest releases of GT++.

**Comment by Dream-Master** [comment]
@draknyte1 with a circuit ?

**Comment by draknyte1** [comment]
Yep. I made all mixer recipes have circuits if < 4 ingredients.

**Comment by Dream-Master** [comment]
ok cool.
