### ISSUE TITLE
Stainless steel dust in mixer

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3065]
2.0.4.2
Stainless steel dust in the mixer requires invar dust instead 2 iron and 1 nickle dust. This makes no sense as it does not decrease the amount of different dusts needed.

proposed change 

4 iron dust + 3 Invar dust + 1 manganese dust + 1 chrome dust = 9 stainless steel dust 

to

6 iron dust + 1 nickle dust + 1 manganese dust + 1 chrome dust = 9 stainless steel dust 

Same material cost just does not require additional steps to produce.
If this is done quest number 751 will need to be updated to agree with this change.

**Comment by Vicus-N** [comment]
I think we can just add alternative mixer recipe for that...

**Comment by DualBallers** [comment]
The problem with the proposed change is that
6Fe+ 1Ni + 1Mn + 1Cr + circuit(1) = 3 Invar, plus leftover dust in the mixer.

in that case you also need to change the circuit in the Invar recipe:
3Fe + 1Ni + circuit(2) = 3 Invar

**Comment by Dream-Master** [comment]
I can add both and change circuits.
