### ISSUE TITLE
Prospector's scanner comments

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3067]
Crafting gave me back only 1 empty cell instead of 2.

I think we can limit these from LV to HV.   

How much durability does scanning a chunk take?  It looks like it was around 50?

Some durability numbers for the LV variety
bronze: 400
iron: 500
wrought iron: 800
steel: 1000
titanium: 3300
ironwood: 800
steeleaf: 1600
knightmetal: 2100
electrical steel: 1000
damascus steel: 2600
vanadium steel: 4000
energetic alloy 2100
vibrant alloy 8400

So steel could check 20 chunks, but with 21% success rate that is only success with ~4 chunks.

Is there any way we can control the metatool generation?  I really dislike having to search through 70 pages of NEI recipes to try and pick one that works.

My idea is maybe we limit the recipes to *just* the magnetic metals:
magnetic iron
magnetic steel
magnetic neodymium (gated by moon & HV polarizer)

That way the number of choices is reasonable.

Also, this way we can choose custom values for the tiers instead of trying to fit them based on a weird gregtech formula.

I would like LV success rate to be 35%, MV 50%, HV 75%
Durability at LV would be (assuming 50 durability to test)
iron: 1500 - 
steel: 4500
neodymium 9000

LV - 3x3 chunks
MV - 4x4 chunks
HV - 5x5 chunks

Larger than 5x5 tends to scroll past the chat rollback length.

# Recipe
On the recipe, I would like to see one circuit replaced with a mercury battery of that tier.  What we can also do, is instead of breaking it, have players replace the battery in the crafting grid and get back a fully repaired prospector and a dead battery of that tier.  That would allow them to take a couple of batteries with them to continue prospecting, but not have to re-create the whole machine.  

It's too bad the computer monitor cover needs aluminum it would be perfect for this. Maybe put a lime stained glass pane in the center like really old monitors? 

I want to use quadruple plates - they can be hand-made at LV, but early LV that much steel would be painful, so players would use iron first then transition to steel.

# Durability
Maybe we could setup a separate use-counter, so that after X uses the machine does break completely? Normally this would be done like the soldering iron/electric screwdriver/electric wrench, maybe we can use that code.

Thanks @bartimaeusnek for the hard work.

**Comment by bartimaeusnek** [comment]
How much durability does scanning a chunk take? - 100 on a successful scan, 25 on a failed scan. the penalty will be applied to EACH CHUNK the scanner is scanning. So a 3x3 Scanner will recive 900dmg on a successfull 3x3 scan. The chanche is also calcuated per chunk and not per scan. I like the ida of quadruple plates. also i dont have any idea how do i should do some ideas without using AT's/ASM/code changes to Gregtech to realise most of the stuff(reapairability/use-counter)

**Comment by richardhendricks** [comment]
I like the idea of the EU value of the battery determining how much durability is restored.  We can just use one battery size, whatever works there, small/medium/large.  That way players can choose to make sulfur or mercury batteries to swap out.

We could make the recipe have a % chance on returning the repaired machine, with LV at 90, MV at 95, HV at 95%.  That would sort of be like durability. It would suck though to have yours break on the first use.  Definitely needs a tooltip warning.
