### ISSUE TITLE
Test Server quite slow on download. Updload seems to be ok.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#307]
@Namikon
The Test Server is quite slow (FTP) . Solder downloading forever if there are new updates.
Can you check it when you come back home. Thanks

**Comment by Namikon** [comment]
Checked, and the updater had full speed for me just 1 Minute ago. Does the problem still persist for you? (Or anyone else..?)

**Comment by Dream-Master** [comment]
I have to test again.

**Comment by Dream-Master** [comment]
Seems to be normal now. So i close this.
