### ISSUE TITLE
Ender quarry too good 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3070]
#### Which modpack version are you using?
2.0.4.2
#### What do you suggest instead/what changes do you propose?

Enderquarries open up around IV, costing some IV field gens, and a whole load of dense obsidian plates. However, they're amazingly good from when you first craft them. Once you make one, you pretty much have all the materials you could ever want from any dimension. 4 quarries mined me around 1.5M copper in a week on enceledus. 750k iron too. In IV you're more than capable with living on multiblock miners and manual mining. 

I think they should be retired to something more suited to needing their excessive output. I'm thinking ZPM, but UV is also a reasonable place for it. The easiest way to do this is to just replace the field gens with a higher tier, but the rest of the recipe is still suited to IVish. I think some parts of it should also be aimed at higher tiers. Maybe make the exu ender blocks cost americium or something like that. I'll make an MC tweaker recipe with all the changes, but I'm interested in knowing if everyone would hate this and I'm completely alone on my complaint.

**Comment by noobyaran9** [comment]
Changing the power usage of the quarry would be a better solution. IV seems to be a nice tier to get the quarry, however, the power cost of running it at full speed seems abit low.

"ender quarry power" {
    I:baseDrain=3600
    I:hardnessDrain=400
}

Maybe we could increase the power cost by 4x or 16x which is decent considering a full speed quarry would take a little bit more power than 1 amp of IV.

**Comment by 0lafe** [comment]
As long as dimensional transievers get an equally scaled increase to what they can transfer. I don't want to have to break out the transvector interfaces just because I can't fit enough transievers on the quarry lol. 

Changing it to ZPM+ is more just because you don't need it in IV. Mining single veins is still more than enough at that tier.

**Comment by Dream-Master** [comment]
Upgrades need to be nerfed as well @0lafe

**Comment by Prewf** [comment]
Does this change mean that it takes roughly 1 LuV amp to run the quarry without any upgrades?

**Comment by Dream-Master** [comment]
it use 8x more idk what it used before ? @Prewf

**Comment by Prewf** [comment]
Oh no wait, that first commit is in RF right? I thought it was EU for some reason. So with the new changes it's a little over 1 IV amp like aran said. Probably minimum LuV if you want to run it with some speed upgrades.

**Comment by Dream-Master** [comment]
Internal Storage is now 200 mio rf thanks to @Ethryan

**Comment by bartimaeusnek** [comment]
if youre using LuV parts for the Ender Quarry, then we need to change the quests aswell @Dream-Master

**Comment by Dream-Master** [comment]
yes

**Comment by Dream-Master** [comment]
Moron did it @richardhendricks  thanks

**Comment by Dream-Master** [comment]
@0lafe open up a issue for upgrade recipe changes thanks.

**Comment by Azzyj** [comment]
Did you also the change the mining range?  I'm running 2.0.4.4 and just set up my quarry, (which is very expensive to make), and it can only mine 64 x 64.  This is insane since an HV miner does 50 x 50.    With a max area or 64x64 it not worth having, even at EV.

**Comment by MineAnPlay** [comment]
Get the latest version. Extra Utilities was downgraded for a few reasons, one of them being this.

**Comment by Azzyj** [comment]
So this isn't an issue in the latest version?  if so I'll happily update.  Thanks

**Comment by Prewf** [comment]
it functions the way it did before it broke. i don't think there's a boundary limit (or if there is, it's very large).

**Comment by 0lafe** [comment]
I was running 5k by 5ks no problem, if there was a limit it would probably be a LOT. I think I heard about someone with a 10k x 10k
