### ISSUE TITLE
Base Decoration Quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3073]
Do I look pretty?

- [x] Chisel from TiCon
- [x] Chisel cool blocks, like fans, and other animated/active blocks
- [x] Brownstone
- [x] Cement
- [x] Gregtech decorated stones
- [ ] architecturecrarft
- [ ] Varieties of lamps
- [ ] Ztones (NO OFANIX ALLOWED!)

**Comment by Anarack** [comment]
- [ ] CF foam scaffolds and reinforced stone
- [ ] fillers, builders, architect library, buildcraft
- [ ] Botany stuff
- [ ] catwalks
- [ ] mailes door mod
- [ ] fancy extra tree block cutting thing
- [ ] extra utilities colored junk
- [ ] railcraft decorative stones (infernal, sandy, ice...)

**Comment by UpstreamEDA** [comment]
OpenBlocks:
- Paint Mixer, Paint Brush, Drawing Table, Stencils, Squeegee

**Comment by richardhendricks** [comment]
[ ] floodgate

**Comment by richardhendricks** [comment]
floodlight/electric and coal powered.

**Comment by richardhendricks** [comment]
Speed blocks like Thaumcraft blocks, ztones boosters, GT concrete, asphalt, chisel concrete, etc.

**Comment by richardhendricks** [comment]
arc lamps, can pass through blocks, needs Mars.

**Comment by richardhendricks** [comment]
HighbeamToday at 2:42 AM
@moronwmachinegun and @DoomSquirter just a note about the Filler if you didn't know already.couple of bugs with it you have to be careful with:  First if you don't chunk load the Filler itself, when the chunk unloads, the Filler pops up as a dropped item.  If you don't notice then it will despawn... (CONFIRMED)  Second and I've only been advised this so not confirmed - but if the Filler is digging in unloaded chunks it can cause corruption?  So I guess those are the 2 main bugs to be careful of.  Third is a no brainer really, don't set it to 'Horizon' mode while under your base or make it fill in where machines are!!! :smiley:
0lafeToday at 2:47 AM
pretty sure if the filler is used on gt items it has issues, which includes ores, but that could have been changed with the change @mitchej123 made a while ago with filtering ores and DE
HighbeamToday at 2:56 AM
Pretty sure I’ve filled my area where there were gt ores and had no issues. I lost several fillers already to the chunk unloading issue.  Always put a vacuum hopper next to your Filler! :smiley:

**Comment by richardhendricks** [comment]
Moved everything to #2663
