### ISSUE TITLE
Ashes to Carbon dust

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3074]
#### Which modpack version are you using?
2.0.4.2

Ashes can not be converted directly to carbon.

**Comment by 0lafe** [comment]
Dark or normal? I think that's been there for a while. I remember both going to C at some point I think, then the normal ashes one got removed. I've been turning it into iron, calcite, and like 4 other things that I've never touched.

**Comment by Anarack** [comment]
normal.

**Comment by 0lafe** [comment]
I'm pretty sure that hasn't been possible for a fairly long time. Like 2.0 and above long time

**Comment by Dream-Master** [comment]
Dark Ash can
![image](https://user-images.githubusercontent.com/2970688/41195564-2ab631f8-6c30-11e8-9e7e-193990d5beea.png)
Ash cant but you get allot of nice stuff out of it.
