### ISSUE TITLE
"Machine Metal" config option testing

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#3075]
With "use_machine_metal_tint" set to "true":
-
• All machines between ULV to IV did not have tint applied.

• All machines LuV and above had the tint applied EXCEPT:
    The combiner
    The pump
    The accelerator
    The Unboxer (On an unrelated note, the boxer only goes up to IV, but the unboxer to UV. What's up with that?)
    The basic transformer (Hi-Amp and Power had tint applied)

• No battery buffers were tinted.

• All plain, placed machine casings were tinted.

• GUIs were tinted
____________________________________________________________
WITH "use_machine_metal_tint" SET TO "false":
-
• All machines, transformers, bat buffs ect are unchanged from when it was set to "true".

• Placeable casings are no longer tinted.

• GUIs are no longer tinted (This doesn't feel intended; there's a separate config option for that)

**Comment by LogicFalls** [comment]
Also: 
Machine casings of UEV and higher are tinted in all cases.

**Comment by Dream-Master** [comment]
@richardhendricks which change ?

**Comment by LogicFalls** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/126/commits/4ddcc361027a994a93859302322a24c6a303d6cf

I think it's that, but I'm not completely sure. @richardhendricks is who you want to ask.

**Comment by Dream-Master** [comment]
ok thanks.

**Comment by richardhendricks** [comment]
Yes, that would be the commit to remove.  After sleeping on it, I have a couple of other things I want to test this morning before I revert.  Will write up a report for future work in case I still am unable to fix it.

**Comment by richardhendricks** [comment]
OK, root caused to TecTech overriding dye values.  Don't know why. Used this knowledge to move the config item over to the core mod.  Requires changes in core mod, tec tech, and gregtech. Will do PR later after Logic confirms all his blocks look correct.

Please unzip and test.
[use_machine_metal_fix.zip](https://github.com/GTNewHorizons/NewHorizons/files/2216404/use_machine_metal_fix.zip)
