### ISSUE TITLE
No ore quests on coins tab

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#3079]
#### Which modpack version are you using?
2.0.4.3

Divine rod of the gods quest (1504) says: "Ore blocks can be purchased from the Coins tab".
But there is no ore quests on coins tab.

**Comment by Dream-Master** [comment]
There will be soon.

**Comment by richardhendricks** [comment]
I added a 2hr cooldown quest with cost of 25 technician/25 blacksmith coins
