### ISSUE TITLE
Ingot cooling system

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3081]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
Base freezer and adv GT++ freezer have the same coolign time.
![2018-06-10_20 30 07](https://user-images.githubusercontent.com/25028786/41204448-36ba38ce-6ced-11e8-8760-e36e3fbd5b65.png)
![2018-06-10_20 30 13](https://user-images.githubusercontent.com/25028786/41204449-375ab240-6ced-11e8-95bd-ff4ff58fa9c5.png)

**Comment by Dream-Master** [comment]
mh funny.
