### ISSUE TITLE
Orewashing plant water requarement

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3085]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
This GT++ multiblock needs input hatch and uses water, but description say nothin about input hatch.

![2018-06-11_00 07 44](https://user-images.githubusercontent.com/25028786/41206372-addb1112-6d0b-11e8-8338-5d6dda67b963.png)

**Comment by Dream-Master** [comment]
@Cinobi Please open issue on gt++ sidetoo. thanks

**Comment by Cinobi** [comment]
Can u post me a link to gt++ github please?

**Comment by 0lafe** [comment]
https://github.com/draknyte1/GTplusplus/issues

**Comment by Dream-Master** [comment]
@0lafe @Cinobi lost his keyboard and have only a mouse to click on links :keyboard:
