### ISSUE TITLE
Original styrene recipe is missing

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#3087]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Looking up the sytrene recipe shows new recipe which is GT++
#
#### What happend instead? (Attach screenshots if needed)
![2018-06-11_13 03 38](https://user-images.githubusercontent.com/13598309/41213443-139a3c96-6d78-11e8-8ef2-9904939f58ee.png)

#
#### What do you suggest instead/what changes do you propose?
Add the old styrene recipe back. #2740

**Comment by noobyaran9** [comment]
![2018-06-11_13 11 27](https://user-images.githubusercontent.com/13598309/41213650-363dfb9c-6d79-11e8-9f3e-84389ccb395d.png)

I suggesting adding fluid + 1 empty cell + 1 fluid cell recipe for ethylbenzene.

**Comment by draknyte1** [comment]
Intended change.

**Comment by Dream-Master** [comment]
yes indeed.
