### ISSUE TITLE
Crossbow quest #1151

### ISSUE THREAD

**Issue by Abenthie** [GTNewHorizons/NewHorizons#3089]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I tried to claim a quest after crafting a crossbow
#
#### What happend instead? (Attach screenshots if needed)
It doesnt count like i retrieved it
#
#### What do you suggest instead/what changes do you propose?
Well its obviously ID problem of the crossbow, the book asks for some special item that name wrote by cursive and with strange symbols before

**Comment by Abenthie** [comment]
![image](https://user-images.githubusercontent.com/40161884/41265717-cebd7772-6e1d-11e8-954e-095f9fc38736.png)

**Comment by Abenthie** [comment]
There what im talking about, i guess its personal problem or?

**Comment by Abenthie** [comment]
https://user-images.githubusercontent.com/40161884/41265717-cebd7772-6e1d-11e8-954e-095f9fc38736.png

**Comment by Abenthie** [comment]
![image](https://user-images.githubusercontent.com/40161884/41265812-481808f8-6e1e-11e8-82ff-a3840a880962.png)
Here is the one  in my inv

**Comment by richardhendricks** [comment]
I know, I see the same thing in epsilon.  But it works fine in single player, so ???.  Will change quest to just the parts and leave the final assembly off the quest.

**Comment by Abenthie** [comment]
Good option too, thanks

**Comment by Dream-Master** [comment]
@richardhendricks We better make a fix or try to fix it instead of leave it out.

**Comment by richardhendricks** [comment]
okay, need to spin up a local server so I can test it on a server.

**Comment by richardhendricks** [comment]
ok, will spin up local server and retest again.

**Comment by Dream-Master** [comment]
Maybe its a problem abot UTF8/Ansi or something like that ?

**Comment by richardhendricks** [comment]
Idk.  I made a fresh crossbow, selected it from my inventory, was no
difference in quest file.

Will look at hammer etc quests to see what's going on.
