### ISSUE TITLE
Quest #1409  (Tier 7 superconductors)

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#3091]
#### Which modpack version are you using?
2.0.4.4

Lots of spelling errors in the quest description. Not going to name them all, just pointing them out to be fixed 👍

**Comment by Dream-Master** [comment]
feel free to correct it @AlexBucket

**Comment by AlexBucket** [comment]
How about lossless 8192 EU IV wires? Vanadiumtriindinid is a superconductor wire and will transfer your energy without and loss.
Every voltage now has superconductor wires and a base wire with only a very small EU/t loss.

Mix vanadium and indium in a HV mixer. Now you have the base dust, which need an EBF with HSS-G coils, and a vacuum freezer to cool it down.

Make some IV superconductor base wires and use an assembler to combine these wires with nitrogen, helium and niobiomtitanium pipes and an IV pump to get your 8192 EU/t superconductor wires.

**Comment by richardhendricks** [comment]
How about lossless 8192 EU IV wires? Vanadiumtriindinide is a superconductor wire and will transfer your energy without any loss. Every voltage now has superconductor wires and a base wire with only a very small EU/t loss.

Mix vanadium and indium in a HV mixer. Now you have the base dust, which needs an EBF with HSS-G coils, and a vacuum freezer to cool it down.

Make some IV superconductor base wires and use an assembler to combine these wires with nitrogen, helium and niobiumtitanium pipes and an IV pump to get your 8192 EU/t superconductor wires.

**Comment by AlexBucket** [comment]
@richardhendricks #1408 is the same, I presume all the other tiered quests for superconductors will be the same.
