### ISSUE TITLE
Obsidian plate bending

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3092]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### Issue
Obsidian plate in bending machine can only be crafted from TC obsidian ingot, recipe with gt ingot  is missing

**Comment by Dream-Master** [comment]
will check if i can add it

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/41371012-6e56d7d4-6f49-11e8-8eb2-9eb35449be15.png)
