### ISSUE TITLE
wand caps

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3093]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
all quests like #230, #232, #798 now wants material WAND cap instead of material cap
#
#### What happend instead? (Attach screenshots if needed)
iron WAND cap and gold WAND cap from GT: New Horizons can' be crafted, but tasks want them in player's inventory
#
#### What do you suggest instead/what changes do you propose?
remove old caps recipes and add new wand caps  recipes or change quests

**Comment by Shyrff** [comment]
Also all wands recipes uses thaucraft version of caps, so gt: nh caps requirement is pointless

**Comment by Dream-Master** [comment]
oh yes  need to Change it.

**Comment by Zoko061602** [comment]
there are also some wand scripts, that were not removed: 
- Forbidden Magic 1 & 2
- Tainted Magic 2
- Thaumic Bases 2
- Thaumic Tinkerer 3
