### ISSUE TITLE
[Quest] Consume Yes Task in Quest 1494

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3095]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Did the quest on faster Stainless steel
#
#### What happend instead? (Attach screenshots if needed)
the quest has 3 stages of submissio, first and second are consume false, but the last oen you need to submit two mv energy hatches (consume TRUE) wich does not make any sense for me at all

![stainless](https://user-images.githubusercontent.com/29660362/41253439-a7b1fb74-6dc0-11e8-9cba-c9dd6602d993.PNG)

#
#### What do you suggest instead/what changes do you propose?
Just make it consume false

**Comment by Dream-Master** [comment]
ok need to be changed.
