### ISSUE TITLE
Add a recipe for the iron fluid pipe

### ISSUE THREAD

**Issue by mergendil** [GTNewHorizons/NewHorizons#3096]
#### Which modpack version are you using?
2.0.4.2
#

#### What do you suggest instead/what changes do you propose?

the iron fluid pipe is the only "standalone" redstone controlled fluid valve in this pack and there's no recipe for it.

Could you add one ? It's usefull for plasma setups

**Comment by WarlordWossman** [comment]
You can controll shutters on pipes with machine controller covers. Might be the same for fluid regulators even.

**Comment by mergendil** [comment]
That's a good alternative, however the pipes that can accept plasma (temperature restriction) also has big capacities (3200mB's the smallest). The bigger the pipe's buffer, the higher the loss of efficiency you get when the pipe turns on again.
The iron pipe's capacity is 500mB, which makes it the best choice

**Comment by WarlordWossman** [comment]
or just request a gt pipe with low flow rates that still deals with high tempratures?

**Comment by Dream-Master** [comment]
Yea a high temperature pipe holde plasma and have small capacity.

**Comment by richardhendricks** [comment]
Reported at GT++ for funky alloy usage. :D

**Comment by richardhendricks** [comment]
Potin pipes added
