### ISSUE TITLE
Macerate mob heads for resources

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3098]
Add maceration options to mob heads.  Make them fun/worth farming.

Skellie skulls -> 16 bones
Wither skellie -> 4 blocks of coal
Enderman -> Enderpearls
Creeper -> 8 gunpowder
Spider -> String and spider eye

Maybe use 2nd/3rd outputs on macerator too.

**Comment by boubou19** [comment]
In my opinion coal blocks doesnt fit with the wither skull, i'll rather suggest to give regular coal( let's say 9 per skull)

**Comment by Dream-Master** [comment]
Enderman -> Enderpearl Dust is better
Skellie skulls -> 16 bonmeal is better

**Comment by richardhendricks** [comment]
eh, I wanted the recipes to actually be worth chasing for the massive mobfarm fun, but just coal and bonemeal isn't worth it.

**Comment by Dream-Master** [comment]
ok but then better not use a macerator a centrifuge qould be better @richardhendricks

**Comment by boubou19** [comment]
what about putting wither skull and skeleton skull recipes into the cutting machine?

**Comment by richardhendricks** [comment]
I like chemical bath better than cutting machine. But yeah, a nice idea.
