### ISSUE TITLE
Boost coal ore output

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3099]
Change to 4/4/2/2 with 100/50/50/25 chances

**Comment by WarlordWossman** [comment]
Buff purified coal ore in sifter:

1 purified coal ---> coal (100%); coal (90%); coal (80%); coal (70%); coal (60%); coal dust (50%)
30 seconds; 16 eu/t

If this recipe is **_exaclty_** implemented as mentioned you would have to constantly run 4 LV sifters or 2 MV sifters to keep up with 1 large bronze boiler. (that would be 2 amps of LV or 1 amp of MV before loss).

This change would be an attempt to make coal a viable fuel source as it **_should_** be imo.
4 coal (on average) from one purified might sound like a lot but it really is not, and here is why:
Not only do you have to build 4 (probably 5) LV sifters to keep up with the bronze boiler (which take 2 (or 2,5) amps of the LV you are making) but you also need to constantly run macerators and set up a simple washer which needs another water source to produce the purified coal ore.
You can use enough coke ovens and/or compressing to boost the output a bit but it really shouldn't be too op, looking at how easy it is to set up charcoal.

I did the math for the sifters and I think this would be a good first tweak. If it happens (it should tbh, no reason why coal should be that much worse than charcoal) I will build it up and compare it to charcoal to see if it needs another buff.

But yeah I have been thinking about this for a few days now and we need to #makecoalgreatagain

**Comment by Dream-Master** [comment]
how the recipe now ? @WarlordWossman
