### ISSUE TITLE
Semi Fluid Generator

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#310]
I see we can add Fluids to them via minetweaker. So i will enabled it and change the fluids from the Diesel Generator to the semi fluid generator because more realistic.

**Comment by Dream-Master** [comment]
Creosote give 8000 eu  @ 8 eu/t
GC Oil give 16000 eu @ 16 eu/t
short mead give 4000 eu @ 4 eu/t
fish oil give 2000 eu @ 2 eu/t

This fluids are removed from GT Diesel Generator.

**Comment by Drobac** [comment]
But the semifluid would have to be 1/4 of the diesel gen cost then because you need 4x the machines to achieve the same voltage

**Comment by Dream-Master** [comment]
Depends on fuel you burning but you have 32 EU  Fuels too.

**Comment by Namikon** [comment]
Keep in mind that there is an energy loss too. You have to use transformers to use the IC2 semifluid generator for your GT machines. Also, creosote currently produces 8000EU at 32eu/t. Basically, you are nerfing creosote oil down to 2000 EU in terms of Gregtech energy

**Comment by Dream-Master** [comment]
I added creosote oil to make 8000 EU in the semi fluid generator not 2000. I dont think 6000 Eu will be lost via Cables and stuff.

**Comment by Namikon** [comment]
Never mind, I somehow messed up the values. Anyways, it has to be tested then if the additional steps to craft transformers, and that you need 4 generators instead of 1 to run most machines isn't a bit too much for players who just enter LV age

**Comment by Dream-Master** [comment]
We find maybe a ceaper way to make the semi fluid generator.

**Comment by Teteros** [comment]
Maybe:
![2015-09-01 13_48_57-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/5067989/9604614/9c4f67ba-50b0-11e5-8822-d9907b52cc9f.png)
```
// --- Semi Fluid Generator
recipes.addShaped(<IC2:blockGenerator:7>, [
[<IC2:itemCasing:5>, <gregtech:gt.metaitem.01:32600>, <IC2:itemCasing:5>],
[<gregtech:gt.blockmachines:2000>, <gregtech:gt.blockcasings:1>, <gregtech:gt.blockmachines:2000>],
[<IC2:itemCasing:5>, <ExtraUtilities:decorativeBlock2>, <IC2:itemCasing:5>]]);
```

Seems about right if you factor in the non-IC2 cable transformer costs for each semi fluid generator.
Also, if you take out oil and fuel the max you can get out of it is 16EU/t I believe.

**Comment by Dream-Master** [comment]
Maybe using a tank instead of only Glass ?
It is a 32 EU machine so is this a 32 machine hull ?

**Comment by Teteros** [comment]
I thought of using an Empty/Universal Cell for that slot at first, but I'd like to keep it pre-LV, which is why the "thickened glass" was there to force the smeltery as a requirement.

The tank sounds good though, just the vanilla obsidian block has two macerating steps till it gets to dust for some reason. Both *obsidian block to dust* and *obsidian block to crushed obsidian* are listed for macerator in NEI. The crushed one is preferred due to railcraft?

The hull is LV, yes. You could change the red alloy wires to tin ones if you plan on having 32EU/t recipes. Besides oil there are none at the moment?

**Comment by Dream-Master** [comment]
I added more fluids to the Semi Fluid Generator.
````````````````````````
// --- Short Mead
SemiFluidGenerator.addFluid(<liquid:short.mead> * 20, 4);

// --- Fish Oil
SemiFluidGenerator.addFluid(<liquid:fishoil> * 20, 2);

// --- GC Oil
SemiFluidGenerator.addFluid(<liquid:oilgc> * 20, 16);

// --- Creosote
SemiFluidGenerator.addFluid(<liquid:creosote> * 25, 8);
``````````````````````````

**Comment by Teteros** [comment]
>But the semifluid would have to be 1/4 of the diesel gen cost then because you need 4x the machines to achieve the same voltage

The Semi Fluid Generator is craftable now it seems, but is it supposed to be the same recipe as the basic diesel engine (upside down)?

**Comment by Dream-Master** [comment]
Yes it is. I will change the recipe soon.

**Comment by Teteros** [comment]
![semifluid2](https://cloud.githubusercontent.com/assets/5067989/9698754/061fefbc-53bc-11e5-8cad-dddc1ee1a829.png)
Red alloy cables:
```
// --- Semi Fluid Generator
recipes.addShaped(<IC2:blockGenerator:7>, [
[<IC2:itemCasing:5>, <ore:craftingTank>, <IC2:itemCasing:5>],
[<gregtech:gt.blockmachines:2006>, <gregtech:gt.blockcasings:1>, <gregtech:gt.blockmachines:2006>],
[<IC2:itemCasing:5>, <gregtech:gt.metaitem.01:32600>, <IC2:itemCasing:5>]]);
```
or tin cables?
```
// --- Semi Fluid Generator
recipes.addShaped(<IC2:blockGenerator:7>, [
[<IC2:itemCasing:5>, <ore:craftingTank>, <IC2:itemCasing:5>],
[<gregtech:gt.blockmachines:1246>, <gregtech:gt.blockcasings:1>, <gregtech:gt.blockmachines:1246>],
[<IC2:itemCasing:5>, <gregtech:gt.metaitem.01:32600>, <IC2:itemCasing:5>]]);
```

**Comment by Dream-Master** [comment]
Will work on this at the evening when i come back home from work.

**Comment by Dream-Master** [comment]
Sorry not done yet but will work on it.

**Comment by Dream-Master** [comment]
Added with the next update maybe today.
