### ISSUE TITLE
Lost in TF comsumption

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3101]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
Quest #1368 description says that you can exchange some staff for portal generator, but quest is Consume: No
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Change to Consume: Yes

**Comment by Dream-Master** [comment]
ok will change
