### ISSUE TITLE
Charged Certus Quartz Crystal 

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/NewHorizons#3103]
#### Which modpack version are you using?

2.0.4.4
#### If in multiplayer; On which server does this happen? 

Epsilon
#### What did you try to do, and what did you expect to happen?

I wanted to do Charged Certus Quartz Crystal  in  Electrolyzer
#### What happend instead? (Attach screenshots if needed)

Does not work

<a href="https://imgbb.com/"><img src="https://image.ibb.co/fX4OUd/1.jpg" alt="1" border="0"></a>

**Comment by bartimaeusnek** [comment]
The NEI recipe is wrong and should not exist. 

This is the common route (or you could use the autoclave for crystalising the dust, but thats not so efficient):

![2018-06-12_17 12 01](https://user-images.githubusercontent.com/33183715/41299495-da19e182-6e63-11e8-9e49-3c3362ae973b.png)
![2018-06-12_17 12 12](https://user-images.githubusercontent.com/33183715/41299496-da446c36-6e63-11e8-94d8-fb2314e0c7be.png)

**Comment by Dream-Master** [comment]
yes it is visaul
