### ISSUE TITLE
GC schematic consumed by scanning to data stick

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3106]
#### Which modpack version are you using?
2.0.4.4
#### What did you try to do, and what did you expect to happen?
I transferred a rocket schematic to a data stick, but as the schematic is consumed by the scanner and can not be made again, I now can't get the other tier schematic (e.g. moon buggy).

#### What do you suggest instead/what changes do you propose?

- either do not consume any type of schematic in the scanner when transferring to data stick
![image](https://user-images.githubusercontent.com/30087707/41314919-614e7166-6e8e-11e8-8398-7f9a7bab9e4a.png)

- or include printing recipe to get schematics back from data stick.
![image](https://user-images.githubusercontent.com/30087707/41314752-eeb3b3b4-6e8d-11e8-8330-68004a658db4.png)

best solution is to not consume the schematic when scanning, as the data stick can maybe too easily be wiped by placing it in the crafting window.

**Comment by Dream-Master** [comment]
The schematics was never desinged for get more than one result. Go and find another schematics and make a moon buggy. @DualBallers

**Comment by DualBallers** [comment]
Hmm alright. But are there more than one GC boss lair on a planet? 

If there are, does the quest book mention this anywhere?

**Comment by Dream-Master** [comment]
Yes there are infinite if you go far enough. Ok maybe a entry in the questbook would be nice.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/41368999-e5bf4b4a-6f43-11e8-81fd-cdbb2e4504e2.png)
allready in the quest text
