### ISSUE TITLE
Gold Wand Caps Quest

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3108]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
ssp
#
#### What did you try to do, and what did you expect to happen?
Craft Gold Caps and have them count for the quest (quest #232)
#
#### What happend instead? (Attach screenshots if needed)
It did not count because the quest wants "Gold Wand Cap" from gt new horizons mod but the ones with a recipe and uses are "Gold Cap" from thaumcraft
#
#### What do you suggest instead/what changes do you propose?
Change the quest to use the thaumcraft caps.

**Comment by sthegreat** [comment]
It seems like this is a problem on a lot of quests. Was there a switch from gt: new horizons caps back to thaumcraft caps in a new update?

**Comment by Dream-Master** [comment]
Yes i will do it asap. Next release.

**Comment by Dream-Master** [comment]
maybe i put it on the Server earlier and ssp player can download the file on github and reload it manually.
