### ISSUE TITLE
Ender Zoo

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#311]
What you think we put Ender Zoo with Ender Io in the pack because i am missing monsters ;-)
Can do this first when Enderio is nerfed.

**Comment by Dream-Master** [comment]
What is about ender Zoo?

**Comment by Namikon** [comment]
Had (have) it in my pack, and never had problems with it. So yes, why not.

**Comment by Dream-Master** [comment]
Will add with Ender IO.

**Comment by Dream-Master** [comment]
Done
