### ISSUE TITLE
Spooky laggy glitchy skeleton

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/NewHorizons#3110]
i have a skeleton farm made with skeleton spawners from a ROG like dungeon (nether stage) grind by dimonds spike but for some strange reason sometimes some "relics" of the skeletton are glitch uder the base they are not living we can't kill them they can't move or do anything but they are here and with time they can be over 900 and has you know 1000's entity make not only the game slower but make it crash...
i suppose that it comes from the nija mob that teleport i found some of them with 0 heart  but we can still hit they tehn i don't really know 
this problem doesn't appear with mob farm without spawner maybe in cause of less special mob ?

**Comment by DoomSquirter** [comment]
are the dead mobs at an angle or something along those lines, or vibrating in place?

**Comment by galyfray** [comment]
they are not vibrating they are standing as if they were in the wild without anybody around i'm gonna take some screenshot when they recame

**Comment by galyfray** [comment]
![2018-06-14_15 45 12](https://user-images.githubusercontent.com/37240229/41454730-ced199aa-707a-11e8-9063-1c2766e3d660.png)
![2018-06-14_15 45 15](https://user-images.githubusercontent.com/37240229/41454731-cf1a4a42-707a-11e8-9b52-614cd0bd3bbb.png)
![2018-06-14_15 45 28](https://user-images.githubusercontent.com/37240229/41454732-cf41e430-707a-11e8-8fe5-aad5b21d93a7.png)
![2018-06-14_15 45 50](https://user-images.githubusercontent.com/37240229/41454733-cf60f550-707a-11e8-8ad1-ca2905d50fae.png)
