### ISSUE TITLE
Crafting task bug?

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3111]
#### Which modpack version are you using?
2.0.4.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon

#
#### What did you try to do, and what did you expect to happen?
The divine rod of the gods quest and Your first wand quest
#
#### What happend instead? (Attach screenshots if needed)
The game seems to only recognize retrievel tasks not Crafting tasks
#
#### What do you suggest instead/what changes do you propose?
wave the magic quickfix wand? :D

**Comment by Dream-Master** [comment]
yea i know will fix it.

**Comment by richardhendricks** [comment]
I fixed this already.
