### ISSUE TITLE
[Quest] [Minor] Quest (#1003) for MV solar panel wrong 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3112]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Did the quest on the MV Solar panel
#
#### What happend instead? (Attach screenshots if needed)
The quest tells you in the second step you will need one ev circuit, but you need two

![2018-06-13_17 37 34](https://user-images.githubusercontent.com/29660362/41361930-833baa62-6f30-11e8-8c73-119786e38add.png)
![2018-06-13_17 37 40](https://user-images.githubusercontent.com/29660362/41361931-835f2258-6f30-11e8-9a86-58b7073052cd.png)

#
#### What do you suggest instead/what changes do you propose?
just make the quest requesting two circuits instead of one

**Comment by combusterf** [comment]
Currently the quest wants the superconductor base material, while the crafting recipe wants the fully crafted superconductors, so they're not completely in sync yet (Delta, 2.0.5.1)

**Comment by Dream-Master** [comment]
yea i need to update the solar panel quests as well @combusterf can you open up a new issue for it. this is quite old. Thanks

**Comment by combusterf** [comment]
Opened #4123 as requested.
