### ISSUE TITLE
Forestry and farms Stuck?

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3113]
#### Which modpack version are you using?
2.4.0.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon

#
#### What did you try to do, and what did you expect to happen?
Procede with questing
#
#### What happend instead? (Attach screenshots if needed)
New quests not unlocking, have entered MV but cant continue towards forestry farm,
![forestry fail](https://user-images.githubusercontent.com/25811344/41365094-cd0e4c1e-6f38-11e8-93a6-16572f374967.png)

#
#### What do you suggest instead/what changes do you propose?
Am i wrong and it unlocks later or is there a problem here?

**Comment by Wolozo7** [comment]
Iirc those quests are tied to some in LV. I think Molten Redstone was a prerequisite here, among other things.

**Comment by Ghengis88** [comment]
ok thx

**Comment by richardhendricks** [comment]
No requirement needs to stay, but maybe in Carpenter quest add

You will need molten redstone for the next quests. Look for a Fluid Extractor quest in LV.

**Comment by Dream-Master** [comment]
Yes and i want to remove this requirements to see next quest.

**Comment by Ghengis88** [comment]
Maby change them, make them erlier or state what they are, i would like a treefarm at the point where i am at but the quest for it has not arrived so i have waited with building it
