### ISSUE TITLE
[Recipe] Solar Panel (Super Solar Panel)

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3114]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Crafted some IV solar panel ( The GT ones). Wanted to upgrade them to the full-block solar panel from super solar pael, but you need an LuV assembly for that recipe. So you can craft the GT solar panel IV while being in IV, but not the super solar panel one.
#

#### What do you suggest instead/what changes do you propose?
Make the assembly Recipe for the super solar panel craftable in an IV assembly. Maybe add a medium sunnarium battery to the recipe because the super solar one has an internal buffer, that the GT one hasnt.

**Comment by Dream-Master** [comment]
Ok but if i do it i need to change all

**Comment by Dream-Master** [comment]
i change them all

**Comment by alphaNOVAircraft** [comment]
@0lafe it isnt the worst thing, but i think if you are able to craft an iv solar panel, it should have those benefits like no need to lean them, the internal buffer is gifted, thats why i suggested to add an iv sunnarium battery to the recipe

**Comment by Dream-Master** [comment]
Then we need to add to all panels batteries @alphaNOVAircraft

**Comment by alphaNOVAircraft** [comment]
@Dream-Master in my opinion that would be a good idea, you get the benefit of a energy storage (actually a prettly large one, e.g. equal of 3 iv batterys), so you should pay at least one for the recipe
When im thinking about we could also add a robot arm of the tier to it, due to the fact that this one doesnt need to get cleaned by hand, so it is maybe cleaned by an robot arm instead

**Comment by Dream-Master** [comment]
good point.

**Comment by alphaNOVAircraft** [comment]
If im not wrong those changes are still not applied ingame, thats why im asking if it is still in the interest of the players to change it or if it will stay with the old recipe

**Comment by Dream-Master** [comment]
will do asap
