### ISSUE TITLE
Light and Heavy Fuel Burn Values

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3115]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
ssp
#
#### What did you try to do, and what did you expect to happen?
Making diesel instead of light fuel for more EU
#
#### What happend instead? (Attach screenshots if needed)
It is barely worth it unless you cetane-boost or have a distillation tower, when making diesel from regular oil due to the unfavorable ratio when making heavy fuel (it is more worth it when using heavy oil as well as regular oil).

The current math is:

Light fuel - 1B oil = 1B light fuel = 320k eu per bucket oil

Diesel - 3.33B oil = 1B heavy fuel, plus 5B oil = 5B light fuel, to make 6B diesel from 8.33 buckets oil. This is only 345k EU per bucket of oil, which is a rather small improvement considering that diesel requires mv tier as well as some additional infrastructure.

Another potentially unbalanced burn value is that heavy fuel is worth only 240k, even though it is harder to make than light fuel since it generally would come from heavy oil (requiring mv) if a player ever considered burning it.

#
#### What do you suggest instead/what changes do you propose?
Adjust the burn values, maybe by switching the values of light and heavy fuel.

**Comment by Dream-Master** [comment]
I am not a specialist but i guess in real life light fuel will be burn better than heavy fuel.

**Comment by alphaNOVAircraft** [comment]
I would not increase the burn value of heavy fuel, if you get some heavy oil with the oil rig, you get insane amounts of heavy fuel (1B of heavy oil equals 2.5B Heavy fuel) so it is even more easy to get this kind of fuel as soon as you get to the oil rig

**Comment by richardhendricks** [comment]
that's not really the point though.  The oil rig is pretty late in the tier and you could just as easily get a lot of light fuel instead.  The real Q is why 1B of heavy oil equals 2.5B of heavy fuel!

**Comment by WarlordWossman** [comment]
I wouldn't switch light and heavy fuel, people got used to how it is and heavy fuel can be used for toluene.
If anything diesel cells need a slight buff, but then you would have to check if cetane is still worth going for, just a lot of numbers really.

**Comment by bartimaeusnek** [comment]
imo we should buff diesel and cetane a bit.

**Comment by sthegreat** [comment]
I don't think diesel and cetane are underpowered at all, if anything they overshadow other options...

**Comment by WarlordWossman** [comment]
>I don't think diesel and cetane are underpowered at all, if anything they overshadow other options...

It's more about the gain for actually doing more with your light fuel than just burning it.
It would probably also be okay to make light fuel 305k instead of 320k and that would probably be the more elegant fix here.
