### ISSUE TITLE
[recipe] Making Amber(Thaumic bases)

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/NewHorizons#3118]
#### Which modpack version are you using?
2.0.4.4
# 
#### What did you try to do, and what did you expect to happen?
make amber from spruce with the recipre Making Amber(Thaumic bases)
#
#### What happend instead? (Attach screenshots if needed)
not working since 2.0.4.X
#
#### What do you suggest instead/what changes do you propose?
make the recipe working again or if nerfed and disabled add a text to this recherche to say nop it won't work it's normal :)

**Comment by bartimaeusnek** [comment]
@Zoko061602 can you check your thaumic bases script for this issure please?

**Comment by Dream-Master** [comment]
Maybe a new recipe was added which use Wood in crucible ?

**Comment by bartimaeusnek** [comment]
Its also possible that Thaumic Bases didnt like the forge upgrade from 14** to 1614, will investigate.
