### ISSUE TITLE
QED Table Minetweaker Support

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#312]
The QED Table from Extra Utilities have now Minetweaker Support!

**Comment by Drobac** [comment]
I suggest using it for advanced thaumcraft recipes since it needs magical wood in the crafting recipe

**Comment by Drobac** [comment]
And if you will use magical wood i  other recipes i suvvest replacing carminite i  its crafting unless the new items is a one and done

**Comment by Dream-Master** [comment]
Why advanced Thaumcraft Recipes. I think Thaumcraft Stuff have to be only in the Book !?

**Comment by Dream-Master** [comment]
And the recipe from the QED not final.

**Comment by Drobac** [comment]
Well yes, but some of the components could be made i  the QED which would give you the ability for additional tiering of thaumcraft based on the QED

**Comment by Dream-Master** [comment]
Will look inside this later.

**Comment by Namikon** [comment]
It would make more sense to move all (advanced) items to the QED that require ender-pearls or liquid ender. Since it is somehow infusing ender-energy to the items, isn't it?

**Comment by Dream-Master** [comment]
Yes can do. So maybe all AE or Gendustry Items maybe?

**Comment by Drobac** [comment]
AE no since it requires a lot of auto crafting and QED seems tricky to automate since it clears its inv after each crafting, gendustry maybe the final items since again parts are tricky and best made with ae

**Comment by Dream-Master** [comment]
Ok maybe i add the Molecular Transformer to the QED Table?

**Comment by Dream-Master** [comment]
Added
