### ISSUE TITLE
Steel boiler multi-block explosion

### ISSUE THREAD

**Issue by Bennett020** [GTNewHorizons/NewHorizons#3120]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
GTNH Official Epsilon
#
#### What did you try to do, and what did you expect to happen?
Load into game after update to 2.0.4.4 and process ores
#
#### What happened instead? (Attach screenshots if needed)
Boiler blew up... (Reservoir was in the same chunk)
![Image of Boiler](https://cdn.discordapp.com/attachments/234936569360809996/456810232346050560/unknown.png)
#
#### What do you suggest instead/what changes do you propose?
Look into it, see why a boiler that was functioning around a week before decided to blow up after this update.... Also can my base be fixed?

**Comment by bartimaeusnek** [comment]
same issure happened to mine, Hyperics and Flockens base

**Comment by richardhendricks** [comment]
Only thing I can think of is that the update somehow reset the contents of the water input hatches but not the controllers. Maybe the reshuffling of block IDs or someting? IDK.

**Comment by Dream-Master** [comment]
I i were you i would stop my boilers and stuff before update.

**Comment by richardhendricks** [comment]
That isn't fair IMO.  If we go to monthly updates, is everyone going to stop all boilers every month? This hasn't happened in other updates AFAIK, so it seems like this one was a special case.

**Comment by Bennett020** [comment]
I had no idea this update was released when it was. I follow the announcements but I don't know how to take that and find out when I should be turning off my boiler without massively impacting my gameplay.
I mean I haven't been on since because I have no power but still.

**Comment by richardhendricks** [comment]
If you guys who had boiler explosions can detail, as much as possible, your water/boiler setup, that would be helpful.  It's not happening to everybody, maybe there is something specific we can track down. 

When did the explosion happen?  Immediately, or a while after logging in for the update?

How were you generating water?

Can you verify, if it is still there, what your water generation/connection setup looks like now?  Did it possibly disconnect from the water source?

How was the water delivered to the input hatch?

What side was the water delivered to the input hatch?

@mitchej123 I can't recall, when did the GT6 style pipes drop? I think they were in the .2.7 release on the servers already, so shouldn't have been an issue.
