### ISSUE TITLE
Problems with 'Brewing, the Industrial way' and related quests

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#3122]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I crafted a basic(!) brewery. Expected nothing.
#
#### What happend instead? (Attach screenshots if needed)
I got a message that the quest "Brewing, the Industrial way" was completed which does not seem to exist in any tab.

Looking around in bq-admin, it seems to be number 1273 (but still nowhere to be found) and a requirement for 'ferment your brew' (1274, also nowhere to be found) and thus in turn for 'the industrial way'(1280, fishing farming cooking tab) which thus stays locked forever.
 
#
#### What do you suggest instead/what changes do you propose?
It is possible they are obsolete and should just be removed as there is a quest for the advanced brewery? Though I don't know about 1280.

**Comment by richardhendricks** [comment]
Figure this shit out


bartimaeusnek - Today at 12:59 PM
the quest "Brewing, the Industrial way" needs the LV brewery quest before it
bartimaeusnek - Today at 1:00 PM
but the LV brewery quest got removed
can you remove that outdated pre-requirement
meh
i dunno how to say it
chochom - Today at 1:01 PM
not quite. Brewing, the Industrial way IS the (old) lv brewery quest but it only gives the message while not being in the questbook`
same with basic fermenter
the requirement probably is then for 'the industrial way'
the requirement problem
bartimaeusnek - Today at 1:02 PM
^ this
this is what i wanted so say
xD
