### ISSUE TITLE
Assembly Line recipes not translating from the meta to the proper name

### ISSUE THREAD

**Issue by officialGerero** [GTNewHorizons/NewHorizons#3129]
#### Which modpack version are you using?
GT New Horizons 2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Dig To Build
#
#### What did you try to do, and what did you expect to happen?
I was making luv components data sticks, to print them, and look for recipes
#
#### What happend instead? (Attach screenshots if needed)
Recipes showed like this
![image](https://user-images.githubusercontent.com/40302455/41480385-fd94a186-70d6-11e8-9633-be79272c9eaa.png)
![image](https://user-images.githubusercontent.com/40302455/41480393-056843e0-70d7-11e8-9593-1c7b3d8c6bee.png)
and so on
#
#### What do you suggest instead/what changes do you propose?
Proper name to be shown xD

**Comment by officialGerero** [comment]
Atleast every luv component shows like that

**Comment by Dream-Master** [comment]
Tec tech habe a machine to show recipes in clear names.

**Comment by richardhendricks** [comment]
@Dream-Master We need a quest for that machine before the assembly line quest.

**Comment by Dream-Master** [comment]
@richardhendricks i guess @bartimaeusnek fix it.

**Comment by bartimaeusnek** [comment]
see https://github.com/GTNewHorizons/GT5-Unofficial/commit/3e5b4f63967ed306a74f8f597a66185d76c7f335

**Comment by Prewf** [comment]
@Dream-Master @richardhendricks 
IMO, it's still worth having a quest for this machine. It takes a data stick and visually shows you the NEI recipe straight up. No having to print books anymore like a pleb. It also correctly shows you alternate options for circuits if the recipe allows it. For example, unlike a printed book, which will say recipe x needs Quantumprocessor (ev-tier chip), the data reader will show it (correctly) alternating between all 3 ev-tier chips as valid options.

Machine is called "Data Reader" and afaik it's only available for IV-tier, please add!
