### ISSUE TITLE
Advanced Boiler tooltip is wrong

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#3133]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I am using the Advanced Boiler [LV] (also called LV Gt++ Steam Boiler or LV Advanced Steam Boiler in the quest). The tooltip says it produces 250L steam/s.
#
#### What happened instead? (Attach screenshots if needed)
It produces 500L steam/s (and my base blew up because of insufficient water :P). Similarly, the MV and HV version produce 1000L/s and 1500L/s instead of the 500/750 found in the tooltip.
#
#### What do you suggest instead/what changes do you propose?
Change the tooltip. (also possibly check the corresponding config?)

Additional but related suggestion: add a remark to the quest that these boilers use waaay more water (ratio exactly 1:25, I think, compared to 1:150/160 elsewhere) than other boilers thus balancing the higher fuel efficiency.

**Comment by bartimaeusnek** [comment]
please report this at the GT++ repo aswell (https://github.com/draknyte1/GTplusplus/issues)

**Comment by chochem** [comment]
good point. have done that now [here](https://github.com/draknyte1/GTplusplus/issues/314)

**Comment by draknyte1** [comment]
Fixed above.
