### ISSUE TITLE
Mana Bean kill you and crash

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#3134]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
My friend ate a mana bean, instant death and crash.

Previous ticket already exist about this issue but was closed
[#1453](https://github.com/GTNewHorizons/NewHorizons/issues/1453)
[#1226](https://github.com/GTNewHorizons/NewHorizons/issues/1226)

#
#### What happend instead? (Attach screenshots if needed)
Nothing but can provide crash report if you want
#
#### What do you suggest instead/what changes do you propose?
Prevent/Disable to eat (maybe with Hunger Overhaul or your mod core ?)
Or add tip on description.

**Comment by Dream-Master** [comment]
I disable the beans because of the crash people complain cant use the beans. Then I enable it again and it crash again. What I should do? Thaumcraft is closed source.

**Comment by mitchej123** [comment]
Wonder if we can disable eating them, but not planting them.

**Comment by DV666** [comment]
Indeed, after somes researchs on web, the problem here is potion effects provided by mana bean => Maybe find a way to remove all theses effects, that's would be great ! (But i can't help you to create this kind of code :/ ).

Otherwise, we can just add a bold tip with MineTweaker like "Don't eat or instant death !"

**Comment by mitchej123** [comment]
Might be able to fix with some Mixins/ASM

**Comment by TimeConqueror** [comment]
Fixed in 1.2-9 BloodArsenal Release:
https://github.com/GTNewHorizons/BloodArsenal/commit/2f53bdbe5c59c063a13aa3cf9006caf12b600c74
