### ISSUE TITLE
[RFC] Move passive anchor to Steam-level, personal anchor to LV

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3135]
Once you get into steam, having machine running while you are away is pretty critical, esp. for mining trips or prospecting etc.  Right now all anchors are MV tier, but I think it makes a lot of sense to move the passive anchor to steam-level.  Since it is passive, it won't load until you visit it, ie spawn in at your base. Maybe require some double bronze plate (craftable with hammer). 

Just the same, the personal anchor makes a lot of sense at LV tier.  At LV you will want to begin oil pumping, so an anchor that loads when you are online seems fair. 

MV and above can use world anchors, since that's where you start having really long processes that you want to finish while you are offline.

Players would still need to collect pearls for them, so they can be choosy when to spend them.  Or we could add a Coins quest for a small # of pearls for coins.

**Comment by Dream-Master** [comment]
We change it to mv long time ago to not overload the server with to much active chuncks. The Anchor recipe is one thing but I am not sure if you are able at lv to collect enough ender pearls to run the stuff?

**Comment by richardhendricks** [comment]
Needs recipe change still, dense obsidian plates cannot be made at LV.

Recommend changing passive chunkloaders to use normal obsidian plates.

**Comment by Dream-Master** [comment]
I change it allready.

https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/fee968221d49e6e61f689ead545cf216865bec7a
