### ISSUE TITLE
Invissible water bucket

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3136]
#### Which modpack version are you using?
2.4.0.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Had a stack of buckets in my hand and right cklicked a full railcraft watertank. and expected to get abucket of water.
#
#### What happend instead? (Attach screenshots if needed)
I did not but a bucket disapeared from the stack in my hand. but when i placed the stack of empty buckets in the top most left corner of my inventory (the slot where new items end up) i got the waterbucket on my mousepointer like when you switch places on iitems, so the bucket is there like it should be but it is not vissible.

#
#### What do you suggest instead/what changes do you propose?
Have no idea how to fix it

**Comment by Dream-Master** [comment]
So far i know this is only visual but very annoying.

**Comment by Ghengis88** [comment]
Yes only vissual but very annoying
