### ISSUE TITLE
[questbook bug] Ore finder Wand

### ISSUE THREAD

**Issue by PolygonGenerationUnity** [GTNewHorizons/NewHorizons#3138]
Quest "Divine rod of the gods?" (stone age) does not complete after crafting Ore finder Wand. I noticed that it asks you to craft wand with id 9027:1, but using such recipe you get wand with id 9027
![image](https://user-images.githubusercontent.com/25788838/41499491-9fe814f6-7189-11e8-91bb-ba6413e8ac1f.png)
![image](https://user-images.githubusercontent.com/25788838/41499589-1defc0f0-718b-11e8-86a5-37265811a78d.png)

**Comment by Dream-Master** [comment]
I know and it is fixed allready in 2.0.4.5.

**Comment by PolygonGenerationUnity** [comment]
Oh, it really is, thanks. I've just had to reload quest database for this fix to apply. Sorry for creating unnecessary topic. Best regards!

**Comment by Dream-Master** [comment]
np
