### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#314]
Cant even log on the server, client doesnt even get past the initial connecting to IP phase. My network is not an issue, checked that already

**Comment by UltraPeeks** [comment]
I can confirm. There is no error in the logs, I just get timed out.

**Comment by Namikon** [comment]
The Server did not shut down properly this morning at 04:00, i "fixed" that...
It should be back online soon, give it ~10 minutes to boot

**Comment by Dream-Master** [comment]
Sorry wasn't often online last week. Have a lot things to do.
Hope this week i have more time.

**Comment by Dream-Master** [comment]
Is this fixed ?

**Comment by Teteros** [comment]
Looks like others and I could login just fine yesterday.
