### ISSUE TITLE
[recipe]forestry backpack upgrade 

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/NewHorizons#3142]
#### Which modpack version are you using?
2.0.4.4
# 
#### What did you try to do, and what did you expect to happen?
tried to upgrade forestry backpack to wooven's one
#
#### What happend instead? (Attach screenshots if needed)
not working with backpack that have been used only work with brand new crafted
#
#### What do you suggest instead/what changes do you propose?
make the recipe more flexible to accepte all forestry backpack maybe by creating a recipe with name in place of ID might work.

**Comment by Dream-Master** [comment]
Yes will do a recipe wher you get a clean backpack from a used one,.

**Comment by Wolozo7** [comment]
Those recipes already exist.

**Comment by Dream-Master** [comment]
oh ok.

**Comment by galyfray** [comment]
oh thx i don't see that the recipe existe
