### ISSUE TITLE
Chisel torch

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [GTNewHorizons/NewHorizons#3143]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I'm trying to use the chisel on a couple of torches to create fancier torches
#
#### What happend instead? (Attach screenshots if needed)
The chisel no longer excepts torch (Item-ID 50) as a valid torch to chisel
![screenshot_20180617_120524](https://user-images.githubusercontent.com/8460628/41506885-ba0dcdba-7226-11e8-9575-e85458ff4ad1.png)

In this screenshot you can see the torch I'm trying to make, note that the standard torch is not in the list:
![screenshot_20180617_120633](https://user-images.githubusercontent.com/8460628/41506895-e18245e2-7226-11e8-9c33-18b4d5782d05.png)

#
#### What do you suggest instead/what changes do you propose?
This used to work in v2.0.2.3 (before the delta/epsilon update), I suggest that whatever change that caused this since then to be reverted.

**Comment by tranceplanet** [comment]
I agree with this.  Now the only way to get any of these torches is to make a glowstone torch and chisel it...  Which means you need to get carbon ingots and an assembling machine just to make fancy torches.....  I'm not sure if this was intentional but I think it was a bad decision.

It would be better to remove the glowstone torch from the chisel and put the basic torch back in.

**Comment by Dream-Master** [comment]
I removed them and let the others in. Should be a error will check it.

**Comment by richardhendricks** [comment]
The problem is that the chisel torches work in space and so glowstone torches aren't used for exploring the moon etc.  That's why the chisel torches were moved to use the glowstone torches instead of regular torches.

**Comment by WarlordWossman** [comment]
Yeah this change was made because the chiseled torches work in space, also glowstone and carbon are both renewable so there is a good reason why it changed to what it is right now.

**Comment by AndrewAmmerlaan** [comment]
I see, however to me it is/was not immediately obvious that the glowstone torch was the way to get the fancier chisel torches. Could we maybe have a tooltip on the vanilla torch stating that to get the fancier torches you need to make a glowstone torch instead? 

Something like:
Torch.addTooltip("This torch cannot be used to craft chiselled torches, make a glowstone torch instead");

This way it is immediately obvious what to do to anyone trying to use the chisel on the vanilla torch.

**Comment by Dream-Master** [comment]
Yes i can add a tooltip.

**Comment by richardhendricks** [comment]
Covered in questline Build Better Bases
