### ISSUE TITLE
SMD Circuit Components

### ISSUE THREAD

**Issue by LandlessGuy** [GTNewHorizons/NewHorizons#3144]
#### Which modpack version are you using?

#2.0.4.5
#### If in multiplayer; On which server does this happen? 

#Singleplayer
#### What did you try to do, and what did you expect to happen?

# Just unlocked SMD circuit components quest in MV, and started to assemble the components required for completing the quest
#### What happened instead? (Attach screenshots if needed)

# Got to the SMD diode, which only has one recipe and requires fine platinum wire. Have trawled through NEI but as far as I'm aware there's no way to get platinum, even tiny piles, until about the Moon/EV, despite the quest being in MV. As a result I don't think there's any way to complete the quest
#### What do you suggest instead/what changes do you propose?
# I'm not sure whether the use of platinum is intended here or not? If it is, the quest can't be completed in MV...once again I don't know if this is intended or not, as it would mean the quest would be an ongoing one over time? If it is, might be worth adding that to the description just to avoid future confusion, or could remove the SMD diode from the quest and include it further up the quest line so that the quest can be completed in MV

**Comment by Wolozo7** [comment]
Nickel Ore.

**Comment by richardhendricks** [comment]
Look at centrifuge and chemical bath recipes.

**Comment by LandlessGuy** [comment]
Ah ok, didn't read the ore spawn spreadsheet well enough *facepalms* Thanks for the help guys
