### ISSUE TITLE
Pyrotheum / Cryotheum Production

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#3146]
Can we get Fluid Extractor recipes for Pyrotheum and Cryotheum Dust? Right now the way to get those fluids is making the dust, canning it into Universal Fluid Cells and emptying those cells into a tank.

**Comment by draknyte1** [comment]
Probably deserves an issue on my tracker.

**Comment by Wolozo7** [comment]
Might as well.
