### ISSUE TITLE
Tier 1 Schematic quest

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#3147]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
Quest Tier 1 Schematic require 1 Compressed Steel, while actual recipe of schematic require Heavy-Duty Plate

![default](https://user-images.githubusercontent.com/5557050/41511661-c0c17bfa-72be-11e8-8346-3e18b392be3d.png)
![default](https://user-images.githubusercontent.com/5557050/41511665-cde479ea-72be-11e8-948a-12670af90aea.png)

**Comment by Dream-Master** [comment]
Yes this need to be changed

**Comment by Vicus-N** [comment]
Maybe need to change prev. quest: "Tier 1 Heavy Duty Plates" to craft +1 Heavy Duty plate (37 total)
