### ISSUE TITLE
Small fuel canister quest

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#3148]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
Empty Canister, required by quest is not consumed in craft... so no need to require 2 Empty Canisters...

![default](https://user-images.githubusercontent.com/5557050/41511974-de4408a4-72c4-11e8-8801-6134b92cddcb.png)

**Comment by Dream-Master** [comment]
I dont change the Quest will change the recipe.
