### ISSUE TITLE
Chad quest should not be a main one

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3153]
#### Which modpack version are you using?
.4.5
#### What do you suggest instead/what changes do you propose?
The quest "Chad- A better way to make Paper" has no reason to be a main quest. It shows you how to make paper using sugarcane and chad. This is just an ALTERNATE way to make paper- you can use wood pulp too, which there's already a quest about, so you don't NEED to use chad at all. The quest also doesn't unlock anything.

With that said, there's no reason for this quest to be a main quest, it should be downgraded to a regular quest.

**Comment by Dream-Master** [comment]
ok will change it.
