### ISSUE TITLE
change all crafting quests to retrieval quests without changing anything else about the quests. as Crafting quests provide no advantage to anyone even beginners.

### ISSUE THREAD

**Issue by bucketking1** [GTNewHorizons/NewHorizons#3154]
#### Which modpack version are you using?
GT NEWHORIZON
#
#### If in multiplayer; On which server does this happen? 

#
#### 
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
i used the tinkers construct smeltery to make bronze rather than making the dusts which stopped me unlocking alot of the future quests (my fault) because i wanted to save on coal and mortars i made my bronze machines. and now have to remake them in order to complete the quests because they are crafting quests. rather than retrieval.

but crafting quests provide 0 advantage to anyone even beginners over retrieval ones. if you took the exact same quests and made them retrieval quests rather then crafting ones and left all the writing and individual steps the same. the quests would be just as useful to beginners but give more experienced players more freedom to play the game in a way they see fit.

also crafting quests stop you from using stuff found in say thaumcraft dungeons. to advance in a technology above where you currently are because you would still have to remake the same machines later in the order suggested by the questbook to complete the questbook
#

**Comment by Dream-Master** [comment]
As a beginner you craft all stuff and thats why all beginning quests are crafting tasks. This will not be changed. If you want to do a speed run in quests change it in your game if you like.
