### ISSUE TITLE
Rebalance nether veins

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3155]
Certus quartz is a key vein needed for progression.  It has a weight of 20, and a height range of 40-80.  This means not only is it rare, but the vein's height range is commonly air in the Nether.

Recommend changing the weight to 40 or 80 (like nether quartz) and/or changing the height to 5-40 or 80-120. I would prefer 80-120.  This way players can search for certus and tetrahedrite at the nether ceiling. And it would leave sulfur/beryllium/manganese/electrotine at the bottom, which is more dangerous imo.

**Comment by Dream-Master** [comment]
Yea good idea had it in my last sp game too. Will change it.

**Comment by richardhendricks** [comment]
I think we need to up the weight too.  20 is just brutal.  Even in creative with an electric prospector, it takes a long time to find certus.

**Comment by 0lafe** [comment]
I'd love to mitigate the pain that is nether ore searching, as much as possible.

**Comment by MineAnPlay** [comment]
Problem now is finding Certus on other planets. I don't know the average height of planets and moons but it might be a problem. If the average height is lower then what it is then lower it to a lower level.

**Comment by Dream-Master** [comment]
yea good point maybe we need a second vein for this reason or I make it from 60 to 120
