### ISSUE TITLE
IFU limitation/bug - was Hard to find chalcopyrite/copper veins

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3156]
Player had to search 100 oreveins to find copper

-8878552644668538540
location 753 -1303

**Comment by richardhendricks** [comment]
@bucketking1
I have confirmed an issue with the ore finder wand.

Gregtech ores are weird, they don't "exist" in the world until they have a block update done to them. This helps prevent x-ray utilities from cheating etc.  Unfortunately as a side effect, this means the orefinder wand will not find oreveins if the orevein does not touch air somewhere. I have confirmed this is true.

No response, no exposed chalcopyrite
![2018-06-20_21 08 56](https://user-images.githubusercontent.com/1214811/41694111-3858f9e8-74ce-11e8-954f-9eae168e7cb5.png)

Response increases as more chalcopyrite is exposed.
![2018-06-20_21 09 27](https://user-images.githubusercontent.com/1214811/41694113-3ad4de26-74ce-11e8-9b14-25e71a183ec6.png)

**Comment by 0lafe** [comment]
How do the scanners work then?

**Comment by repo-alt** [comment]
Scanners probably just repeat oregen code.

**Comment by richardhendricks** [comment]
They weren't using the same code, the IFU I was just doing a string compare against "gt.blockores", the scanner actually does an "instanceof GT_Block_Ores_Abstract."  Trying a fix now.

**Comment by richardhendricks** [comment]
@bartimaeusnek This one is beyond my ability.  Best I can tell, the Detrav scanner uses network packets to send the ore data to the client.  The basic orefinder doesn't support sending/receiving network data, so it only has the local data for the blocks.  Unexposed GT oreblocks don't have any ore-specific metadata yet, so you don't get any information on them.

**Comment by richardhendricks** [comment]
OK, I have a kludge tested, it seems to work much better.  Not ideal, but good enough I think.  Tested with SSP, will push branch once I test it on private server.

This explains a lot, lol.

**Comment by richardhendricks** [comment]
OK, code will now detect any background ore type with another background ore type

Bad news though, my changes don't work on dedicated servers.  Need to spend more time to investigate implementing client/server packet passing code similar to Datrev scanner.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/IFU/tree/feature/moron-kludge

**Comment by richardhendricks** [comment]
Set the damage from the server to notify to the client the level to activate

http://www.minecraftforge.net/forum/topic/40083-110-onupdate-and-onitemuse/

**Comment by richardhendricks** [comment]
Change max damage to match finding level

https://github.com/GTNewHorizons/IFU/blob/feature/moron-kludge/src/main/java/com/encraft/dz/items/ItemOreFinderTool.java#L68

**Comment by richardhendricks** [comment]
Smarter way to get the player?
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/1434556-1-6-2-forge-solved-inventory-not-working-in

**Comment by richardhendricks** [comment]
https://github.com/coolAlias/Forge_Tutorials/blob/master/EventHandlerTutorial.java#L259

**Comment by richardhendricks** [comment]
http://www.minecraftforge.net/forum/topic/16341-setting-itemstack-damage/

**Comment by richardhendricks** [comment]
PR with fix has been merged.
