### ISSUE TITLE
New OC recipes improvement

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#3157]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
New recipes for microchip T1, T3, CPU T1, T3 always use fixed lower tier circuits (Interesting that T2 microchip and CPU accept any appropriate circuit). This forces to have lowest tier circuit production even at lategame.
Also all these recipes use usual transistors. Would be nice to also have SMD transistors version.

**Comment by Dream-Master** [comment]
yea will add.

**Comment by repo-alt** [comment]
I noticed that you've added circuit downgrading shapeless recipes, so that is less of an issue than I thought.

**Comment by Dream-Master** [comment]
Yes for the circuits but for smd variants not.

**Comment by repo-alt** [comment]
I see that T3 CPU recipe still uses only workstation circuit, which can only be crafted with processor assembly (both of which are not the best circuits of the corresponding tier)

**Comment by Dream-Master** [comment]
In 2.0.6.0 the assembly line and the assembler using all circuits of a tier if you mean that @repo-alt

**Comment by Dream-Master** [comment]
will add the other transistors later

**Comment by repo-alt** [comment]
This is about OC recipes

**Comment by repo-alt** [comment]
I looked at Open-Computers.zs and the only change I see is Creative Component Bus
