### ISSUE TITLE
Long Emerald rods

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#316]
Long emerald rods dont have a recipe

**Comment by Dream-Master** [comment]
I will fix it. I thought i did all ready.

**Comment by Dream-Master** [comment]
They made out of Flawless or Exquisite Emeralds with Tools or in the Lathe

**Comment by Dream-Master** [comment]
It is the GT recipe.

**Comment by Dream-Master** [comment]
@Drobac 
Did you find the recipe?

**Comment by Drobac** [comment]
yes, works just fine
