### ISSUE TITLE
D-O-B Combs are weird in gt centrifuges

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3161]
#### Which modpack version are you using?
2.0.4.5

D-O-B combs in gt centrifuges picks a different set of materials every game reload. This is a very strange behavior and while it works correctly in a forestry centrifuge giving a very large range of items, I do not know what it is intended to do when ran through a gt centrifuge.

**Comment by Dream-Master** [comment]
because they have 20 outputs or so.

**Comment by DV666** [comment]
I tested D-O-B bee this night and yes, combs are weird... more like bugued.

With centrifuge GT ou large centrifuge, the output is limited and different each time you relaunch your game.

Here somes screenshoots about that :

Setup on my creative save :
1 drawer D-O-B comb with infinity upgrade
1 centrifuge ZPM ou large centrifuge ZPM
20 Me Storage 16384k 

Centrifuge is connected to ME interface with translocator upgraded

![2019-06-18_05 37 29](https://user-images.githubusercontent.com/17729817/59699366-c2089900-91f1-11e9-9736-7a4b345ec558.png)

After few minutes, you can see we get only a few products : 6 kinds of tiny dusts, sticky resin, pulsating nugget and only 1 shard (earth)
Sometimes, we get another products but proportion is totally unequal.

When i reboot the game and waiting again few minutes, new products comes from the centrifuge

![2019-06-18_05 55 11](https://user-images.githubusercontent.com/17729817/59699814-80c4b900-91f2-11e9-8a4f-1c8379be97a9.png)

You can see we get new items like Energetic Alloy, Water Shard, Stone dust, Lignite dust, etc...

For information, here is the result we can expect with D-O-B comb (from my previous modpack)

![2017-12-15_17 39 53](https://user-images.githubusercontent.com/17729817/59700068-f0d33f00-91f2-11e9-83cb-3e42952ad2d5.png)

**Comment by Dream-Master** [comment]
We can remove the DOB bee ?

**Comment by DV666** [comment]
Imo, this bee is too powerfull for this kind of modpack : can produce a lot of different dust like naquadah/chrome, which makes the other bees totally out of the game (no need UUM or crushed ore)

So, if this bee is deleted or not, i don't care ^^

I suggest to make a poll on discord maybe ?

**Comment by MineAnPlay** [comment]
D-O-B combs are supposed to be processed in the Forestry Centrifuge. Even though it has 9 slots it actually outputs all the products. Keeping it or removing it I will leave to others to decide but if kept it should be processable in the Forestry Centrifuge.

**Comment by xtake** [comment]
Dob bees are not powerful at all if they are not broken (as in 2.0.7.0 where you don't need the foundation blocks to breed them)
They need all different kinds of blocks normaly naquadah, plutonium, ultimate hybrid solar panel... Naquadah itself is already quite hard to get. And it only gives dust for all bees that are included in breeding it. 
If you have the ability to get the naquadah bee then I am pretty sure you can get some uu matter to make purified naquadah ore or quadruple your broken ore. So I really don't see them as too powerful they are perfect for the stage they are at. 
And I am pretty sure if we do a poll on discord it wouldn't really count I think most people that vote against it have never truly breed that bee from ground up (without broken foundations), they just see what it makes and see it as OP.

**Comment by ScriptedPiky** [comment]
In my opinion, the D-O-B bee is meant to be an accomplishment that gives you an assortment of goodies for your hard work. To obtain it, you must go through the Naquadah bee tree and Thaumic Shard bee tree. All of this is incredibly difficult and tedious as the Naquadah tree has several 10-1% bees, including the 1% breeding chance to get that particular bee. Along with the requirement of an Ultimate Hybrid Solar panel requirement underneath it. It's an incredible amount of work to get that bee, I'd be damned if it was removed and all my hard work is gone for nothing
