### ISSUE TITLE
Oil Drilling Rig does not work

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/NewHorizons#3162]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Oil should swing
#
#### What happend instead? (Attach screenshots if needed)
Drops pipes, pumps several liters of oil and lifts all pipes up

**Comment by tranceplanet** [comment]
I haven't done it yet but I believe you have to scan the chunks to see what oil is contained.  It doesn't just suck up regular oil, its a hidden layer?

**Comment by richardhendricks** [comment]
Oil drilling rig does not pump regular BC oil.  A hidden "underground oil" patch is created, and below a certain # the rig does not pump.  Please check the spot with a seismic prospector or electronic prospector.  They are in an 8x8 chunk grid.

**Comment by Bob558-51** [comment]
Seismic prospector The presence of a large vein of oil  in this place

[url=https://imgbb.com/][img]https://image.ibb.co/gtW75T/1.jpg[/img][/url]

**Comment by Dream-Master** [comment]
How many chuncks your scanner look for oil? Maybe it is in the next chunk or in the chunck after. @Bob558-51

**Comment by Bob558-51** [comment]
LV scaner 3x3

**Comment by Dream-Master** [comment]
so far i know we dont change anything @richardhendricks

**Comment by richardhendricks** [comment]
No, nothing has been changed.

**Comment by barsikus007** [comment]
I had the same problem, but I decided to break it and put the controller block
[https://cdn.discordapp.com/attachments/234936569360809996/457845084755591169/2277c7b1-8a14-43a9-acd6-cf91f930b34c.gif](gif)

**Comment by Dream-Master** [comment]
@barsikus007 url is broken

**Comment by richardhendricks** [comment]
Please try again with the upcoming release.  Some oil rig bugs were fixed.
