### ISSUE TITLE
incorrect english lol

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [GTNewHorizons/NewHorizons#3163]
"You are looking at a big progressive kitchensink pack "

It's kitchen sink not kichensink. Two words. It comes from everything but the kitchen sink an idiomatic English expression that used to mean offering everything. More modern use , however, is a bad term as in  all over the place, unfocused, jack of all trades master of none, offering too much and none of it is good, etc.

**Comment by repo-alt** [comment]
English produces new words constantly.

**Comment by WarlordWossman** [comment]
Could simply remove it from the readme I guess.

**Comment by Dream-Master** [comment]
@CarlGustavAlbertDwarfsteinYung if you so fluent in English just rewrite text and post it here. We could easily change it thanks.
