### ISSUE TITLE
Mixer recipe for Naquadah Alloy interfered with by GT++

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3164]
#### Which modpack version are you using?
2.0.5
#
#### What did you try to do, and what did you expect to happen?
Combine full-sized dusts of Naquadah, Trinium, and Carbon (with a circuit#2) to make Naquadah Alloy
#
#### What happend instead? (Attach screenshots if needed)
Nothing happened.
It did work with small or tiny dusts, however.
#
#### What do you suggest instead/what changes do you propose?
Add a programmable circuit to GT++'s "Trinium Naquadah Alloy" dust recipe so it stops interfering

**Comment by NeroOneTrueKing** [comment]
Oops, my version is 2.0.4.5, (not 2.0.5 as I wrote earlier)
I encountered the problem on a LAN world

**Comment by draknyte1** [comment]
Should be fixed in latest releasts of GT++.
