### ISSUE TITLE
ore finder wand don't store its target inside itself

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3167]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
crafted two ore finder wands to have finder for two ore veins and put one in a bag while i use the other to avoid switching ore(tooltip says i can use one wand at a time)
#
#### What happend instead? (Attach screenshots if needed)
it appears that the ore finder wand store only one ore at a time and per player so in my case this isn't affecting me a lot but we can imagine a case where 2 players, called A and B play together. A can't borrow the ore finder wand from B to search the same ore. B have to unequip the ore inside his ore finder wand before.
#
#### What do you suggest instead/what changes do you propose?
i suggest to store the ore inside the wand, but without enabling the possibility to have multiple active ore finder wands at a time

**Comment by Dream-Master** [comment]
Yes and this is inteneded. How you could hold more than on Wand in your hand? @boubou19 
At LV you can build a ore scanner.

**Comment by boubou19** [comment]
ok but for players that play together it's still a problem in bronze age because if player A wants to stop finding a specific ore with the wand and player B want to search the ore instead of player A then player A need to take back his ore and give it to player B as well as the wand. So it's just for quality of life.

**Comment by Dream-Master** [comment]
Before they wasnt any Ore finder wand. And there is a quest for buy some ores for coins.

**Comment by boubou19** [comment]
so what about adding an info on the fact that if players want to share the wand to find the same ore they have to unequip the ore first before sharing?
