### ISSUE TITLE
update seems to have broken all types of drawbridges

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3168]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
the setup:
![2018-06-21_01 30 14](https://user-images.githubusercontent.com/12850933/41689809-d661536e-74f2-11e8-9357-8025cb640584.png)
expected this:
![2018-06-21_01 30 29](https://user-images.githubusercontent.com/12850933/41689820-de955328-74f2-11e8-97ae-0b57dbe678e9.png)

#
#### What happend instead? (Attach screenshots if needed)
nothing happened when i activated the lever
#
#### What do you suggest instead/what changes do you propose?
pls fix it

**Comment by boubou19** [comment]
it happen with all the differents drawbridges

**Comment by Bryfer** [comment]
Please search before posting issues
#2993

**Comment by boubou19** [comment]
it was closed so i thought it was fixed.I'm sorry. Pls keep this one open to avoid future 
reposting of this issue

**Comment by Dream-Master** [comment]
Drawbridges are disabled on both Delta and Epsilon until a solution is found on how to fix them.
