### ISSUE TITLE
Make more quests main quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3169]
Dust to Crystals in LV - needed for nanosuit stuff

Carbon plates quest - need to OR in Organic Way (seriously, is anyone EVER going to do it that way?) quest

**Comment by Dream-Master** [comment]
Carbon plates quest and organic ones are on mv quest page @richardhendricks 
Autoclave quest are on LV Tab allready. Maybe we can add additional quests make a few dusts to crystals.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/41724436-d475de1e-756d-11e8-9747-9bd90e91bb29.png)

**Comment by richardhendricks** [comment]
The problem is that they are prerequisites for the nanosuit goggles quest, and it can be difficult to figure out they are required for that quest since it is on a different page.  Maybe we should make the nanosuit quests main quests?  IDK, players have some choices there, but it is hard to figure out what is needed since it is on a different tab.

**Comment by Dream-Master** [comment]
or I make autoclave main quest?

**Comment by 0lafe** [comment]
From playing through the current early game quests, if anything I'd rather less main quests. We're stopped from getting into the MV quests because we can't find a certis vein, but we don't need it yet. We have MV power and 3 MV machines, but can't get any credit for them because we "need certus"

**Comment by Dream-Master** [comment]
Certus is changed now and you will get it more common in the nether. Need a Nether reset.

**Comment by 0lafe** [comment]
Yea, but it's not really needed to start MV, so it seems weird as a main quest

**Comment by Dream-Master** [comment]
you need it for the detector and emitter in the scanner. I don't find a vein also and hopefully autoclave 2 crystals out of dust.
