### ISSUE TITLE
Fell out of world while using sleeping bag

### ISSUE THREAD

**Issue by UltraPeeks** [GTNewHorizons/NewHorizons#317]
The sleeping bag just sent me straight into the void.
I tried to sleep on a high mountain (x:446 z:1071 y:220). There is no Gravestone and the deathmarker from Journey Map has no y-value. So I guess all my tools and bags are gone for good?

Related issue https://github.com/OpenMods/OpenBlocks/issues/500
Seems like there is not much we can do about it, or can we prevent the usage of the sleeping bag above 128?

It seems like it's a rather rare bug, because I could not reproduce it. I tried in single player though... Maybe it's an issue in combination with cauldron or a plugin.

**Comment by Namikon** [comment]
Yep, I can confirm this issue. I had it 3 times while I was building my mage tower. Since that day, I don't use the bag anymore. And don't worry about your stuff, it can be restored. You just have to be online (and obviously have an empty inventory) while I do some console magic. I'll be idling in IRC today, so give me a poke when you are ready

**Comment by Dream-Master** [comment]
With the normal bed you get fall damage too but get back to the bed. You can't sleeping above level 128.

**Comment by Dream-Master** [comment]
It is better to not post in a closed issue. Maybe we have to open a new one. I think it is a Server or a Cauldron problem. We have to test it in sp to be sure it is a open Block thing.

**Comment by Dream-Master** [comment]
Test someone if it only happens on the Server or in sp tool ?

**Comment by Namikon** [comment]
It's an issue with the sleeping bag. I remembered I was unable to sleep in my bed in my mage tower, i just got kicked back and got a small amount of damage.

**Comment by Dream-Master** [comment]
Yes i know but i want to know if this is a only Server Side problem or this happens in single player too.

**Comment by Dream-Master** [comment]
I make a warning via Tooltips.
