### ISSUE TITLE
Potentially confusing thaumonomicon text

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3171]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
The entry for node manipulation from thaumic bases contains this text:
"you also need to constantly move Vis back and forth - some mirrors are required, and some flux formes, which is critical, so Flux scrubbers must be used too. And, for this construction to be stable some Salis Mundus is alse required."
It refers to its original recipe requiring those items to make it, but since the recipe has been changed and doesn't need any of these items, it sounds like those items would be needed to be used while running the device - which is the not the case.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Remove the paragraph

**Comment by Dream-Master** [comment]
Ok will change the text to match with it recipe.

**Comment by Dream-Master** [comment]
i change the recipe a bit to match more with the original one.
