### ISSUE TITLE
Forestry biomass is now less efficient in a distillation tower

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3172]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I tried to process Forestry biomass in a distillation tower. I expected it to be more efficient than in a singleblock distillery.
#
#### What happend instead? (Attach screenshots if needed)
In a distillery, 40 MB of forestry biomass gives 20 MB of ethanol, for an efficiency of 50%.
In a distillation tower, 600 MB of forestry biomass gives 240 MB of ethanol, for an efficiency of 40% (plus some water and a small pile of wood pulp, but ultimately those are inconsequential
#
#### What do you suggest instead/what changes do you propose?
Make the distillation tower gives 360 MB of ethanol, instead of 240. This is an efficiency of 60%, which seems like a fair number for the much larger and more expensive multiblock.

**Comment by Dream-Master** [comment]
Sure will check it.

**Comment by Bryfer** [comment]
Change the input number from 600 to 1000 aswell

Is there any more liquids that does not have even input numbers?

**Comment by Dream-Master** [comment]
ok but then i need to change output to more than 500 mb (Ethanol)

**Comment by Dream-Master** [comment]
1000 Bio Mass give now 600 mb Ethanol and 300 Water and 2 small wood dusts.
I am not sure if this is not to overpowered compared what ypu get out of fermented Bio mass?

**Comment by Bluebine** [comment]
Compared to fermented biomass, it gives a lot more ethanol but you don't get IC2 fertilizer and you don't get all the extra stuff (methanol, acetic acid, ammonia, etc.). So I think it's a fair tradeoff, you get 4x the ethanol but miss out on all the other stuff. Not to mention, forestry biomass is generally harder to make than fermented.

**Comment by Dream-Master** [comment]
@Bluebine recipe ok now?

**Comment by Dream-Master** [comment]
The test will see in 2.0.4.6 if yes.
