### ISSUE TITLE
Catwalk no longer has Assembler recipe

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#3174]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Craft catwalk in assembler
#
#### What happend instead? (Attach screenshots if needed)
There is no recipe for it.
#
#### What do you suggest instead/what changes do you propose?
Restore the assembler recipe:
2 Steel Grates + 2 Steel Rod = 3 Catwalks

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/41802691-f33171a4-7682-11e8-9307-394205b29375.png)
