### ISSUE TITLE
Impossible to valid the "Primal Charm" quest

### ISSUE THREAD

**Issue by TheMathis26** [GTNewHorizons/NewHorizons#3176]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
A private server
#
#### What did you try to do, and what did you expect to happen?
I tried to valid the quest with all the items in my inventory but it doesn't work (I have even tried with an OSS).
#
#### What happend instead? (Attach screenshots if needed)
![unknown](https://user-images.githubusercontent.com/12830127/41813891-50b80984-773f-11e8-8382-d50dd001519b.png)
![unknown2](https://user-images.githubusercontent.com/12830127/41813893-53d6abc0-773f-11e8-815d-71d3f0af4648.png)
![unknown3](https://user-images.githubusercontent.com/12830127/41813894-566c740a-773f-11e8-95d0-e2cda99a8d46.png)

#
#### What do you suggest instead/what changes do you propose?
Fix the quest

**Comment by Bryfer** [comment]
The screenshots you provided is not working properly
Can you upload them to GitHub instead?

**Comment by TheMathis26** [comment]
Done. And I add that the rings I have are rose gold, I did not make the mistake to craft gold ones.

**Comment by Dream-Master** [comment]
Will see if any other player have this issue.

**Comment by TheMathis26** [comment]
I've found the problem: I've already completed the quest in a old version of the modpack but the quest has changed since that so I had to "/bq_admin reset" it before beeing able to complete it again.
