### ISSUE TITLE
Quest #1504 - 0.5 - Divine Rod of the Gods

### ISSUE THREAD

**Issue by tranceplanet** [GTNewHorizons/NewHorizons#3177]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Second part of quest does not complete when crafting Ore Finder
Happened to myself and another I know of.

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
fixed in 2.0.4.5
