### ISSUE TITLE
IO tool

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#318]
Recipe for the item uses HSLA Steel plates which we dont have anymore

**Comment by Dream-Master** [comment]
IO tool. from wich mod? Maybe i make hsla steel available again via Blastfurnace ...

**Comment by Teteros** [comment]
It's from RemoteIO. It allows you to see and configure the chips in a remote interface or remote inventory.
I don't think it does anything else and is not required for configuring them (but handy to have still).

**Comment by Dream-Master** [comment]
Ok remote io i never touched Arch did. It need a rework.

**Comment by Dream-Master** [comment]
Make a recipes.

`````````````````
// --- HSLA Steel Dust
recipes.addShapeless(<gregtech:gt.metaitem.01:2322> * 2, [<gregtech:gt.metaitem.01:2305>, <gregtech:gt.metaitem.01:10>, <gregtech:gt.metaitem.01:1047>, <gregtech:gt.metaitem.01:1345>, <gregtech:gt.metaitem.01:1034>, <gregtech:gt.metaitem.01:1029>, <gregtech:gt.metaitem.01:1030>, <gregtech:gt.metaitem.01:1048>, <gregtech:gt.metaitem.01:1028>]);
````````````````
