### ISSUE TITLE
"Cough Cough - Something needs to be done about the smell" quest

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#3180]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Trying to commit quest items: 11 x Air Filter [Tier 1] and its not working. Detect/Submit button didn't help.

![default](https://user-images.githubusercontent.com/5557050/41813800-18077be2-7780-11e8-94a7-6b7bb7638e63.png)
![default](https://user-images.githubusercontent.com/5557050/41813806-317b0468-7780-11e8-90cd-e416065fd030.png)

**Comment by Dream-Master** [comment]
maybe a nbt data issue. Will check
