### ISSUE TITLE
Space Race Quest Fixes [Minor]

### ISSUE THREAD

**Issue by 1penguinmonk** [GTNewHorizons/NewHorizons#3181]
#### Which modpack version are you using?
2.0.4.5 (i think)
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Trying to complete Moon Patrol, Fueling Your Buggy, and Booster Quests
#
#### What happend instead? (Attach screenshots if needed)
Moon patrol quest is missing the frequency module that the buggy needs.  Fueling your buggy quest requires blocks of black steel but the recipe for the buggy fueling pads uses any of the blocks of regular steel.  Booster quest requires only 4 tier 1 heavy duty plates but you need 8 total to complete the 2 boosters required by the quest.
![2018-06-23_17 17 21](https://user-images.githubusercontent.com/36487696/41814680-bec4f724-7709-11e8-9c02-148e60dbca28.png)
![2018-06-23_17 17 44](https://user-images.githubusercontent.com/36487696/41814681-c0da7282-7709-11e8-8d95-a732926741d3.png)
![2018-06-23_17 18 09](https://user-images.githubusercontent.com/36487696/41814682-c2d3e80c-7709-11e8-84c9-212f534ba768.png)
![2018-06-23_17 18 15](https://user-images.githubusercontent.com/36487696/41814684-c52ff2f8-7709-11e8-94e1-338cb2c0435a.png)
![2018-06-23_17 18 27](https://user-images.githubusercontent.com/36487696/41814685-c6578ee8-7709-11e8-96d5-9664c0b96f9c.png)
![2018-06-23_17 18 30](https://user-images.githubusercontent.com/36487696/41814686-c77219c4-7709-11e8-9bb1-4801f3291d58.png)

#
#### What do you suggest instead/what changes do you propose?
Moon patrol quest: Add frequency module to retrieval task
Fueling your buggy: Change block of black steel to block of steel
Booster: Change required tier 1 heavy duty plates from 4 to 8

**Comment by Dream-Master** [comment]
ok will look into it.
