### ISSUE TITLE
OC recipes: Server (T3), screen (T3)

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#3183]
#### Which modpack version are you using?
2.0.4.6
#
3-rd tier server recipe shows like
![image](https://user-images.githubusercontent.com/23512002/41820231-de918338-77d6-11e8-989b-ced05d677def.png)
but actually takes 2 microchips (tier 3)
#
T3 Screen requires workstation, would be nice to have alternative Extreme circuits there
T2 Screen recipe is ok
T1 recipe requires low tier good circuit, but it can be obtained by downgrading

**Comment by Dream-Master** [comment]
ok willl look into it.
