### ISSUE TITLE
OC recipes: memory planks autocrafting "economy"

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#3185]
version: 2.0.4.4

3.5 memory plank recipe takes 2 stacks of RAM, but only one is used if crafting was called vi AE interface
I assume the same will happen when crafting T3 and T2.5

**Comment by Dream-Master** [comment]
@repo-alt What you suggest ?

**Comment by repo-alt** [comment]
idk, it's the first time I see that. Perhaps add another chips instead of second stack of RAM? like NOR & NAND chips

**Comment by Dream-Master** [comment]
ok
