### ISSUE TITLE
Suggestion - Add Just Enough Calculation mod

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#3186]
Mod add one item, which help calculate resource cost of something. Very helpful when i try to describe cost of something on stream. Or just understand how really expensive something. It's not clientside, and this is why i ask to add this mod in modpack. 

Link:
https://minecraft.curseforge.com/projects/just-enough-calculation

About gregify recipe, it's good if it be avalable on steam era, or lv. Something with glass pane and buttons should be ok.

**Comment by damug** [comment]
Seems useful.  I don't know the repercussions of adding a new mod/greggifying it up though.

**Comment by 0lafe** [comment]
There will be those who don't want more load time from more mods, but I think this sounds cool. Doesn't do anything you can't do yourself.

**Comment by Wolozo7** [comment]
Someone should test this in SP. If it is what I think it is, it can't really calculate on its own but needs to be fed with recipes before it gives out useful numbers. Especially with the GT-way of producing machine parts in non-crafting-table-setups, I doubt there is much to gain from this mod.

**Comment by Usernm0** [comment]
Yes, you should add recipes before it show numbers to you. Advantages of this - you can make just enough recipes to detail something. Or use different resource ratios on circuits depends on your processes.

**Comment by Bryfer** [comment]
This mod has been suggested before without a proper response #1185

**Comment by richardhendricks** [comment]
Why does a mod that does recipe calculation need to be on the server side?  Concerns me a little about server lag. If recipes have to be added by hand, how is that done?

I would like to see some testing on a private server showing that it doesn't cause lag issues like AE2.

**Comment by Vicus-N** [comment]
Didn't check this mod, but some mod with detail resource cost would be very useful. Tired to sit with pen, paper and calculator...

**Comment by bartimaeusnek** [comment]
seem to not work with gt machine recipes codewise. but i guess we would have to test that

**Comment by Usernm0** [comment]
Mod have server side because it add item and server should know about items in player inventory or containers.
I think it not do anything else on server.

About gt machines it works like ae2 processing patterns. You put items and it quantities as input and same as output. And it count result like ae2.

**Comment by aLegoz** [comment]
We used this mod on server, Very convenient and useful mod.
