### ISSUE TITLE
Do we need this mod ? (Thaumcraft Addon Mod)

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#319]
http://minecraft.curseforge.com/mc-mods/232192-thaumic-bases

**Comment by Dream-Master** [comment]
@Namikon 
@Drobac 
...

**Comment by Dream-Master** [comment]
Someone check this model ? Useful or useless?

**Comment by Namikon** [comment]
Sure, it looks nice. Auram is always a ressource that you are short of. You have to destroy nodes to get it, which is not the bed approach

**Comment by Drobac** [comment]
Indeed looks interesting, +1 vote

**Comment by Dream-Master** [comment]
So will see if we have a Book slot left.

**Comment by Drobac** [comment]
Should be, as i added it on the test pack and had no problems

**Comment by Dream-Master** [comment]
Added.
