### ISSUE TITLE
Stone age quest tab improvements

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3191]
#### Which modpack version are you using?
2.0.4.4; the screenshot I will use should match with 2.0.4.6 tho if you ignore the crafting station quest I crossed out.

![stone_age](https://user-images.githubusercontent.com/16925725/41869292-d37eed04-78b8-11e8-8d21-3a74bf906a22.PNG)

Let me explain the changes displayed in this picture a bit (from top left to bottom right):

* moving the quest for GT6 style pipes to be after bronze only makes sense, right now a new player who just found iron and has yet to do the copper/tin quest will be able to see it while you have to make bronze plates for this quest. The new position would be after tools still but also after you actually have bronze.
* the clipboard needs one of the wood planks you can only make in the compressor (from 8 wood pulp). It needs to either be moved to the steam age tab (after the compressor) or we make an alternative recipe for it that needs a sort of wood plank you can already get with the saw.
* the 3 informative quests for ore veins are currently totally out of place. The fact that the lunchbag quest opens up 6 quests after completing only results in people being overwhelmed. Would make a lot more sense to move those and make them appear at a point in time when you actually have to start mining.
* the quests leading to the lava gloves (or what ever you want to call them) are optional, however getting lava for your smeltery without them is really painfull (and new players might not get what is going on since they followed all the main quests and there was no explaination on how to deal with lava).
You _can_ make glass without a smeltery (block mold in the alloy smelter) but our quest line tells you to get the steam extractor prior to the making a block mold, so I think the smeltery is quite important and the gloves should be a main quest since you need to move lava around.

**Comment by Dream-Master** [comment]
yea will check
