### ISSUE TITLE
Pams harvest craft fish oil

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3192]
#### Which modpack version are you using?
2.0.4.6

Pam's fish gives only 4L of fish oil compared to the 30-40 of vanilla fish.

**Comment by Dream-Master** [comment]
yea that's to less.

**Comment by Vicus-N** [comment]
On 2.0.4.2 this was about 40L or 50L for 1 fish...

**Comment by Dream-Master** [comment]
No it wassent i dont change anything there. Maybe a autogened recipe idk need to check.

**Comment by Vicus-N** [comment]
Screens from 2.0.4.2:
![default](https://user-images.githubusercontent.com/5557050/41934961-7f540d04-79cb-11e8-9420-d44c02803c00.png)
![default](https://user-images.githubusercontent.com/5557050/41934986-939459cc-79cb-11e8-9b0e-2f39cfe3088f.png)

Raw Fish:
![default](https://user-images.githubusercontent.com/5557050/41935017-b06a7180-79cb-11e8-812e-7a6168818d37.png)

**Comment by Dream-Master** [comment]
oh ok need to check

**Comment by Dream-Master** [comment]
ok i see the recipes but in code ther recipes give 50L idk which mod it change it.

**Comment by Dream-Master** [comment]
GT_Values.RA.addFluidExtractionRecipe(GT_ModHandler.getModItem("harvestcraft", "catfishrawItem", 1, 0), GT_Values.NI, Materials.FishOil.getFluid(50L), 10000, 16, 4);

**Comment by Dream-Master** [comment]
another mod seems to change it.

**Comment by Dream-Master** [comment]
guess i fix it.

**Comment by draknyte1** [comment]
Also resolved on my side in https://github.com/draknyte1/GTplusplus/commit/00f1f7c03a173d0033d4b00a2d08cc600d6cb667.

**Comment by Dream-Master** [comment]
ok thanks
