### ISSUE TITLE
Odd behaviour with traveller's belt

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3196]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Swap hotbars with the traveller's belt
#
#### What happend instead? (Attach screenshots if needed)
![oddbehaviour](https://user-images.githubusercontent.com/17787093/41928197-49cce32c-796c-11e8-9f20-27e62c100a58.gif)
I am not sure what is causing it exactly, so I realise this isn't much info to work from.
I'll add more info if I find it.
#

**Comment by bartimaeusnek** [comment]
ive noticed the same when accessing pollution scrubbers, restarting the game has worked for me. so dunno if this is an issure

**Comment by richardhendricks** [comment]
Is it just a lag issue or are those real items?  Do they disappear if you open up another inventory and resync inventory?

**Comment by KiloJoel** [comment]
They're not real items and restarting has stopped it from happening

**Comment by Bryfer** [comment]
This has happened to me aswell, it's usually when the server is lagging/low TPS
It fixes itself after a while but it's indeed really annoying.
Logging out and back in again fixes the inventory (temporary)
