### ISSUE TITLE
cakes can be eaten

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3198]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i placed a cake on the ground and right clicked on it. I expected to eat a piece, like in vanilla.
#
#### What happend instead? (Attach screenshots if needed)
nothing. The cake remains intact
#
#### What do you suggest instead/what changes do you propose?
fix it pls

**Comment by Dream-Master** [comment]
how I can be fix vanilla behaviours?

**Comment by WarlordWossman** [comment]
Every time I interacted with cakes they worked fine, a little more information would be nice.

**Comment by boubou19** [comment]
well i don't know how to provide more informations because as i said i put the cake on the ground and i right clicked on it with an empty hand and nothing happened

**Comment by boubou19** [comment]
omg we were two to test this but too dumb to check the hunger bar i feel ashamed

**Comment by WarlordWossman** [comment]
I was originally going to ask that but thought you would tell me that you are not dumb :D
