### ISSUE TITLE
[suggestion] move ender IO farming station to early HV

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3199]
#### Which modpack version are you using?
2.0.4.6

The idea here is to promote forestry multifarms a bit more since they are fairly fleshed out and scale pretty well. The ender IO farming station is really simple as in it needs only power and a tool (keep in mind the healing axe and the unstable mattock never break) while forestry farms are a multiblock that needs water, power, fertilizer and (if you do trees) dirt blocks which results into more GT machinery to support it.

It's not going to be a massive nerf since the current recipe already requires some stainless steel but I feel like it should be a bit more of an investment for how simple it is to set it up.

Old recipe: 
![farming_station_old](https://user-images.githubusercontent.com/16925725/41957922-c5b50092-79e8-11e8-850f-59ab8c812937.PNG)

New recipe (suggestion):
![farming_station](https://user-images.githubusercontent.com/16925725/41957947-d8c70c48-79e8-11e8-841f-c4e628ad0a52.PNG)
robot arm (HV); dense pulsating iron plate; robot arm (HV)
pulsating crystal; machine chassis; pulsating crystal
electrical steel gear; Z logic controller; electrical steel gear

Also a bit more of the ender IO alloys being used in recipes other than conduits, they feel a bit underused currently.

**Comment by noobyaran9** [comment]
I suggest replacing the pulsating crystal with vibrant crystal.

**Comment by WarlordWossman** [comment]
>I suggest replacing the pulsating crystal with vibrant crystal.

I did think about this but it would force a vacuum freezer and a cleanroom.
For the double layer and octadic capacitor you would need to get energetic alloy or vibrant alloy anyways, so it might be a little weird to gate the main block after vibrant alloy.

**Comment by noobyaran9** [comment]
Why would the vibrant crystal forces a cleanroom?

I thought vac freezer should be like the 1st few machine that you get once u hit HV?

**Comment by WarlordWossman** [comment]
Vibrant alloy needs nichrome coils which can only be cooled in the vacuum freezer and the vacuum freezer needs workstations which you have to make in the cleanroom.
