### ISSUE TITLE
Assembler recipes and crafting time

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#320]
The lever recipe takes 20 seconds to craft, even in the 512 EU Assembler it still takes 5 seconds. This is way too long. 5 seconds for the 32 EU Assembler would be more than enough.

Same goes for the carpenters block recipe, and the piston recipe. Even with 512 eu machines, it takes forever to craft a stack of those (And you need multiple stacks of these things)

**Comment by Dream-Master** [comment]
Will change if i come back home.

**Comment by Teteros** [comment]
Don't forget to take power loss into account. (30EU/t for 32EU/t machines for example) if recipes are short.

**Comment by Drobac** [comment]
Same with carpenter recipes

**Comment by Dream-Master** [comment]
Ok change the recipes need to be testet.

**Comment by Dream-Master** [comment]
Carpenters blocks and pistons are changed to 100 Ticks.
Lever i have to disabled first via config and make a own recipes.

**Comment by Dream-Master** [comment]
- [ ] Make custom Lever Assembler recipes

**Comment by Dream-Master** [comment]
Done
