### ISSUE TITLE
Command Blocks for Better Questing - disable 2?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3201]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
SP
Crafting of the Default Load Block seems to be properly disabled on servers. Recipe shows but uncraftable.
#
####
Quest# 1495 : All alone in the night
I think it was a good idea to add the Default Load Block for people using SP
however I think its too easy to accidentally turn this without knowing what it does properly into a Quest Reset Block or an Hardcore Switch Block.

Its super easy to make, and all you have to do is to right click them and all your quests are gone.. Hopefully you made that backup of your questdb right?
![image](https://user-images.githubusercontent.com/22825059/41990348-74e77ece-7a42-11e8-9451-3de2f4cca499.png)
![image](https://user-images.githubusercontent.com/22825059/41990365-7ff4e8c4-7a42-11e8-87db-4ec247bf9b4d.png)
![image](https://user-images.githubusercontent.com/22825059/41990414-9bcb22ca-7a42-11e8-86e0-bc0768aebf86.png)

#
#### What do you suggest instead/what changes do you propose?
Disable recipies to make:
Quest Reset Block
Hardcore Switch Block
OR
add big fat warning labels
"Right clicking this block WILL reset ALL your quests!"
"GTNH is NOT meant for Hardcore mode!"

I'd prefer disable.
#

**Comment by richardhendricks** [comment]
Other option is to turn them into shaped recipes, with the block in a different corner.

We've had requests for a quest reset a few times, I think it should stay.

**Comment by Dream-Master** [comment]
Yes but a big warning is ok. If someone reset all quest accidently he get screwed.

**Comment by richardhendricks** [comment]
@bartimaeusnek plz update tooltip

**Comment by Bryfer** [comment]
Why would you want to reset your quest progression on SP anyway? Seems way easier to just start a new game instead if a restart is what you really want.

What reason is there to have the reset block and hardcore block in game?

On servers these blocks are, and should be disabled aswell. People will find some way to abuse it if it's available.

**Comment by Dream-Master** [comment]
use it or not depends on the player. I add a tooltip for it.
