### ISSUE TITLE
Cp Foam and Concrete Bucket

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3202]
#### Which modpack version are you using?
2.0.46
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I was making concrete buckets but did not have a bucket in the crafting table
#
#### What happend instead? (Attach screenshots if needed)
I accidentally made cp foam
#
#### What do you suggest instead/what changes do you propose?
I would suggest making cp foam a shaped recipe instead of shapeless so people do not accidentally make the wrong item like I did

**Comment by Dream-Master** [comment]
will check
