### ISSUE TITLE
Do not include server specific mods in the server pack you publish

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#3205]
Basically subject.

Currently, there is a mod called AMDIForge that has appeared in 2.0.4.5 that controls mob spawn.
This is not the mod we should have in public server pack releases. This mod messes up spawning logic of the mobs, so things like magnum torches or repelator do not work as intended.

Please stop including Delta/Epsilon/Official GTNH server mods in public modpack. Build separate pack if you need to. 
I have spent 5 hours debugging why magnum torch don't work, and all because of "delta/epsilon" is lagging.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3204

**Comment by DeForce** [comment]
This is not a duplicate of the ticket.

This is 2 different issues. 
First issue is with the mod, and there is ticket for it..
Second - with the methodology. Pushing server pack with mods that is not even mentioned in changelog is not a very good thing to do, and this is a ticket for that.

**Comment by Dream-Master** [comment]
I remember that magnum torch not working. will ask @Namikon

**Comment by Namikon** [comment]
@DeForce I highly doubt that AMDIForge is the reason for your MagnumTorch issue:

I just checked the repository again;
 AMDIForge does nothing on its own unless configured. The EventListener for EntitySpawn is set to **not** receive canceled events and does only block **additional** spawn of an specific Entity if the number that is to be configured in the respective config file is exceeded.

All these cases are not met at all. Even if @Dream-Master included the Server-Config of that mod that we use on Delta/Epsilon, there are very few limits set for certain mobs.

A few words on the Magnum Torch: If the Torch would've worked correctly, then AMDIForge would never ever receive the SpawnEvent. And even if the Torch is set to Priority=Lowest, AMDIForge still does not *force* the Entity to spawn; It limits additional spawns; If configured.

In addition to that; AMDIForge's primary functionality is to provide a clientside GUI to the /graveadmin command, which allows ServerOperators to manage OpenBlocks graves with ease. So it's not just a ServerSide mod as you mentioned.

However a ChangeLog entry would've been nice, I agree with that.

And I can't really help you with the torch, as we face the same issues from time to time. For example, The torches don't seem to work on GalactiCraft Planets. About 2months ago, all void dimensions where empty and no hostile mobs spawned (Could've been an aprils fool now that I think about it).
Couple weeks later, all was back to normal. No mod updated, no config changed. Weird, and almost impossible to debug.

**Comment by DeForce** [comment]
I specifically removed AMDIForge from a server, and magnum torch/repelors started to work.
That was tested on clean forge install, multiple times. 

2045, without AMDIForge - magnum torch works. 
2046, with AMDIForge - magnum torch doesn't work.

**Comment by Dream-Master** [comment]
maybe it worked because someone fix it in version 14. but Quarries are bugged as hell.

**Comment by Namikon** [comment]
Yeah, could be the exU version. But the test setup doesn't leave a lot of other options open. It might be indeed my hook into the event chain; some ominous side effect with setting the event state. It shouldn't happen, but it seems it does...

**Comment by DeForce** [comment]
> maybe it worked because someone fix it in version 14. but Quarries are bugged as hell.

If you check, you actually downgraded the mod from .14 to 13a

**Comment by Dream-Master** [comment]
maybe you can @DeForce check it. The problem with extra utilities is I ask mod dev for permission to change the mod but he don't answering. Version 14 we found because some one decompile it and put it on git.

**Comment by DeForce** [comment]
Yup, I did.

https://github.com/GTNewHorizons/AMDIForge/pull/1
