### ISSUE TITLE
nei shows wrong recipe for thick neutron reflector

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3207]
#### Which modpack version are you using?
2.4.0.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to autocraft thick neutron reflector with this recipe:
![image](https://user-images.githubusercontent.com/12850933/42059271-242cfbda-7b23-11e8-9949-99f7a7c46005.png)
so i encoded a pattern with this recipe:
![image](https://user-images.githubusercontent.com/12850933/42059296-37d5d828-7b23-11e8-8056-9a10ff4083df.png)
expected everything to work fine

#
#### What happend instead? (Attach screenshots if needed)
it appears that the recipe actually work with only two neutron reflectors
#

**Comment by Dream-Master** [comment]
@Techlone seems that assmbler recipe with more than 2 input have a problem (GTTweaker) A recipes can made with only 3 items instead of 5. Any idea

**Comment by Techlone** [comment]
Well idk. GTTweaker just puts all input items in GT's API https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Assembler.java#L51
Maybe something is wrong with a GT recipe optimization. When input is 4x item A plus 2x item B and output is 2x item C GT tries convert this recipe in 2xA + 1xB -> 1xC. But it's just a conjecture.
