### ISSUE TITLE
Remove rain warp

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3208]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Constant rain on servers is depressing, especially when it's being caused by other people's warp and there's nothing you can do but spam sleep every time it happens.
It's fine on singleplayer, but on servers, especially with the official ones being quite busy a lot of the time, it is raining more often than it isn't.

**Comment by Anarack** [comment]
You can also make dissipation chargers to get rid of it, probably a few magic methods as well.

**Comment by KiloJoel** [comment]
While that is the case, the people with the warp probably won't do it, and I don't think it should fall on other people to go to the effort of setting up an automatic system to deal with a problem that other people are causing.

**Comment by Dream-Master** [comment]
the effects are global and people have to take care by there own. And no I don't want to remove all the warp effects.
