### ISSUE TITLE
Crossbow quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3209]
Crossbow magnalium quest requires 42 magnalium.  Not really sure why, the quests don't require that much.  Maybe 12 total?

Need to explain how players are supposed to fluid extract iron.  LV FE is not able to FE iron. Have to use smeltery to melt the iron and then put it into fluid solidifier.

Magnalium bolts quest doesn't complete properly, has same issue as wooden crossbow quest.  Needs further research.

**Comment by Dream-Master** [comment]
fixed amount it was 9 not 42
