### ISSUE TITLE
GalactiCraft - Recipes

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#321]
Ok, so I've been working on my way into space since I started playing again a few days ago.
Before my vacation, I mined up 2 veins of Diatomite, processed it into flint dust, and produced .. a lot ... of iTNT.
For the rocket, it takes a ton of resources, and a lot of time. But I like it, it's not supposed to be easy.

However: The rest of the mod is.. spoiling the fun completely. I used up at least 30-40 Stacks of iTNT (64-ish Stacks); This depleted the entire stock of flint dust I had (2 entire veins of diatomite...)

You need a whole bunch of machines, solar panels, oxygen pipes for each space station/base you're going to build. Not to speak of the personal equipment for oxygen. For all this, you need the compressed plates. I have no idea where I should get that much iTNT from, without setting up a 24/7 flint macerating setup and let it run chunkloaded for at least a week to get enough flint dust for the iTNT.

**Comment by Dream-Master** [comment]
Any suggestion ?
Get the right balance for the recipes are very hard. 
My advice is to using only two itnt instead of four for the compressed Plates.

**Comment by Namikon** [comment]
Couldn't you just make all the machine-recipes without the compressed plates? You could use the triple ones if you want to keep the material cost high, but just the oxygen equipment / fuel loader that you need every time costs almost twice as much iTNT than the rocket

**Comment by Dream-Master** [comment]
I think we have to find a better way. I think it is much more better if Galacticraft using their materials.
I can lower the iTNT cost. May Be normal Compressed Plates using only one iNT for each plate. I can make the scripts and you can test the difference.

**Comment by Dream-Master** [comment]
Ok change all Implosion Compressor Recipes using 1 iTNT for one plate. Only Meteoric Iron and Desh using two.

**Comment by Dream-Master** [comment]
Scripts are on the Server. Need a Server restart that they working.

**Comment by Dream-Master** [comment]
Balance Ok now ?

**Comment by Namikon** [comment]
Yes, that's a lot better now

**Comment by Dream-Master** [comment]
can this be closed?

**Comment by Namikon** [comment]
Yes
