### ISSUE TITLE
witchery doesn't recognize  special mobs blazes which causes problems

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#3214]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta server
#
#### What did you try to do, and what did you expect to happen?
i am a level 5 vampire from the witchery mod attempting to level up to level 6 which requires me to kill 20 blazes
#
#### What happened instead? (Attach screenshots if needed) 
witchery does not recognize blazes from the special mobs mod  so i cannot level up my vampire level so i am stuck on vampire level 5 until i can kill 20 vanilla minecraft blazes
>i also tried buying blazes from one of the quests in coins coins coins quest tab which also spawned special mobs blazes and we also tried the obvious of using ender io spawners which also failed to spawn vanilla blazes 
>using a tablet of necromancy  the ritual specifically spawns a blaze,also doesn't work as it also summons the special mobs blaze
>tested in a singleplayer world using commands to summon a blaze /summon blaze gave the same results of spawning the special mobs one
#
####What do you suggest instead/what changes do you propose?
honestly i think its either both vanilla and special mobs  blazes spawn or we find a certain way to spawn the vanilla blaze but considering even the tablet of necromancy didn't work the first option may be the only one i also
unless somehow you could get witchery to make sense of the blazes i don't think i'll be able to level up my vampire level 
besides im still in lv and witchery is a long way to go not to mention that clearing vampirism is a endgame witchery

**Comment by boubou19** [comment]
also DE spawner only spawn infernal blazes

**Comment by Dream-Master** [comment]
So far i know are infernals no problem i guess it is a problem if the blaze is from special mobs.

**Comment by PoptartOverlord-Xabedo** [comment]
i think that the infernals  are special mobs

**Comment by Dream-Master** [comment]
some time they both

**Comment by boubou19** [comment]
well then the normal blaze spawn is very low because i spawned like 60 blaze and i got only infernal ones

**Comment by MineAnPlay** [comment]
This issue (I'm almost certain) has nothing got to do with Infernal Mobs. It's either Special mobs not being compatible with Witchery or Witchery having weird issues.

**Comment by PoptartOverlord-Xabedo** [comment]
i see, im sorry i was wrong, the issue is from special mobs

**Comment by Dream-Master** [comment]
I could lower the special mobs blaze rate.

**Comment by MineAnPlay** [comment]
Problem isn't the spawn rate, it's completely replacing it, I think, which means NO vanilla blazes are spawning. We could try some NBT tags and see if it works but it might be completely (or near completely) overwriting the vanilla Blaze entity.

**Comment by PoptartOverlord-Xabedo** [comment]
yes it is competently replacing it since as far as i know only special mobs blazes are spawning

**Comment by MineAnPlay** [comment]
```
blaze_rates {
    # If this false, vanilla blazes will be replaced with similar Special Mobs versions if not "special".
    B:_allow_vanilla=false
```
to 
```
blaze_rates {
    # If this false, vanilla blazes will be replaced with similar Special Mobs versions if not "special".
    B:_allow_vanilla=true
```

**Comment by PoptartOverlord-Xabedo** [comment]
welp thats the core problem right there

**Comment by Dream-Master** [comment]
yea i will check it later.

**Comment by PoptartOverlord-Xabedo** [comment]
so uhm, i have quite a small request, since we concluded there is no method of me leveling up my vampire level to level 6 until the update , and it doesn't look like the update is coming any soon, may i have it leveled up either by changing it in my player.dat or something else?

**Comment by mitchej123** [comment]
I checked the decompiled witchery source and it's checking for an instance of EntityBlaze, which should properly handle subclasses.  I also checked SpecialMobs and the blazes on there are subclassed from EntityBlaze; they _look_ like it should work.

Any chance the configs got mucked with?
```
      public boolean canIncreaseVampireLevel() {
          return Config.instance().allowVampireQuests && this.vampireLevel < this.vampireLevelCap;
      }  
```

**Comment by mitchej123** [comment]
Also, can you reproduce in SSP with SpecialMobs, and then does it work without SpecialMobs?

**Comment by mitchej123** [comment]
Also, have you read the book for level 6?

https://www.reddit.com/r/feedthebeast/comments/4il9c5/witchery_vampire_level_5_to_6_not_working/

**Comment by PoptartOverlord-Xabedo** [comment]
i have reproduced it in SSp with special mobs but it also didnt work i should've noted that also there is no need at all to read the book its simply a guide as you can level up without even possessing it or opening it once.
i may reproduce it again to make it sure since you have talked about witchery looking for the blaze subclass and special mobs blazes are a subclass
i will try to reproduce it in a controlled environment

**Comment by PoptartOverlord-Xabedo** [comment]
i have reproduced it and nothing has  come out of it as i killed over 64 blazes in  survival mode while i was level 5 (there is a creative tool that levels up called the creative bat/wolf token ) also when you level up an orange text comes out in the chat saying "your thirst grows stronger..."*something like that  but it did not come out and my blood reserves on the left of my screen were still 7 which means im still level 5 and level 6 has 8 blood reserves

**Comment by mitchej123** [comment]
I looked at the decompiled source code, and based on my quick reading you definitely need to read the book as increases the vampire level cap when you read it. (Look at the code bit I posted above)

As for SSP testing,  did you remove special mobs and then level up properly?

**Comment by PoptartOverlord-Xabedo** [comment]
i actually have not removed special mobs and i tested with it, also uhm, i don't know how to put it, i didn't say anything after this test because i ran another one while listening to you and reading the book which indeed worked,  am truly sorry about this...but i have yet to do it on the server, there is also something that raises my question i have the book maxed and opened it on the server, which i also killed more than the amount of blazes needed there  but still didn't level up 
thanks for informing me and i'm sorry about making this...not so beneficial issue

**Comment by PoptartOverlord-Xabedo** [comment]
update......leveled up on the server
