### ISSUE TITLE
Sifter quest too generous

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3215]
LV sifter quest currently gives 3x64 stacks of purified ore.  This wasn't intended, it should be a selection reward between the 3 stacks.

Also, stacks should probably be decreased to 32, and add a purified coal ore stack.

**Comment by Dream-Master** [comment]
ok but i will let it at 64 and make a choice quest.

**Comment by WarlordWossman** [comment]
@Dream-Master Why keep it 64? That's just too many gems you get for free, 32 would be more in line with the other rewards you get.

**Comment by MineAnPlay** [comment]
I don't think 64 is much. Gives you enough for a block to make lens and some extra for crafting. Other then Emerald you need a lot more Diamond and Ruby for that to even be much.

**Comment by WarlordWossman** [comment]
>I don't think 64 is much. Gives you enough for a block to make lens and some extra for crafting. Other then Emerald you need a lot more Diamond and Ruby for that to even be much.

You don't need that many diamonds, you get enough for some lenses and turn the rest into dust which is enough for a few cutting machines and all diamond needs early on. I just don't really see why you would try to find a diamond vein when you could just finish the sifter quest and be set for a while.

**Comment by MineAnPlay** [comment]
If you want to make Diamond Chests/Tanks you do need to find some Diamond veins because 64 Purified Ore doesn't give that much Diamond gems. I still think this is a nice extra bonus for doing a quest. Gems aren't too useful so it isn't too much of a problem IMO.

**Comment by Dream-Master** [comment]
Yes it stay at 64 it is only a single bomus so i guess it is ok.

**Comment by WarlordWossman** [comment]
You say the rewards and all make it too easy and then we hand out things for every small step, but okay.
Better than giving all 3 stacks I guess.

**Comment by Dream-Master** [comment]
yea 3 stacks was to much.
