### ISSUE TITLE
GT++ Large Electrolyzer and Centrifuge not working

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3216]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
LAN
#
#### What did you try to do, and what did you expect to happen?
Process my ores using the large centrifuge.
Use the large electrolyzer (to test if it was broken too)
#
#### What happened instead? (Attach screenshots if needed)
Nothing happened.
The machines are powered, turned on, and worked fine before updating to 2.0.4.6
#
#### What do you suggest instead/what changes do you propose?
Looking through GT++'s commits, I think Draknyte9 has already found & fixed the issue, but it has not been included into GTNH yet.
EDIT: the supposed fix is in GTNH already, but the problem persists
I hope this gets fixed and pushed soon, since my ore processing chain will bottleneck horribly without the centrifuge.

**Comment by Dream-Master** [comment]
@NeroOneTrueKing  we using lastest version of Gt++ . Can you show me where the commits was added. Maybe i will put them in a new version 2.0.4.7.

**Comment by NeroOneTrueKing** [comment]
@Dream-Master 
Looks like the supposed fix should be in GTNH, since it was before the version bump. (1.7.1.01-fresh)
The centrifuge is definitely not working, though. Guess the ball is back in draknyte's court

**Comment by Dream-Master** [comment]
ok thanks @NeroOneTrueKing

**Comment by Wolozo7** [comment]
In the last GTNH version 2.0.4.4, we had issues with the Large Centrifuge and Electrolyzer showing recipes in NEI that they couldn't/wouldn't perform. Alkalus fixed that (in the GT++ version that is currently used in GTNH 2.0.4.6), but created the current bug, where the machines won't work at all. Since then, he provided a fix for this problem, the mentioned GT++ version 1.7.0.20, where the machines work again.

**Comment by Dream-Master** [comment]
Will be in version 2.0.4.7

**Comment by Prewf** [comment]
It still doesn't work with certain recipes (on 1.7.0.20-fresh). I'll post it on the gt++ thread.

**Comment by draknyte1** [comment]
Fixed in https://github.com/draknyte1/GTplusplus/commit/0fbf214b5a95c7f4cf5dab6d4c393feb4fb80758.
