### ISSUE TITLE
[RFC] Add fortune for normal GT ores, and decrease overall ore density

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3217]
This is to discuss making veins a little less dense (by 1 grade, ie 8->7 etc in orevein config, maybe more) and add looting for normal GT ores. This will offset how easy it is to find ores now with wand and LV basic prospector with a choice between mining speed vs mining output. Obviously a density decrease will affect automated mining, so we can discuss that too. Decreasing ore density would help chunk generation time a small amount.

GT code currently exits early if the ore is standard block ore, ie
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L198

Suggested implementation is to move this check down to 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L259

and change how it reacts for standard block ores so that each fortune level gives a 10% chance (will be config option for tuning, maybe 5%) of getting 1-3 crushed ores (config option for tuning).  Standard block ores would only return crushed, small ores would still have chances at gems and impure dusts. So

fortune 1 => 10% chance of 1-3 crushed, 100 blocks => 200 crushed from macerator + ~20 additional from fortune

fortune 2 = > 2x 10% chance of 1-3 crushed, 100 blocks => 200 crushed from macerator + ~40 additional from fortune

etc

So players can choose between adding speed, durability, or bonus output to their tools.

We would also add the natural check to block ores, so that they only drop the additional stuff when mined the first time 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L202

PS
Small ores fortune only increases the chance of 0-2 crushed, it never increases how many you receive. Maybe change this too?

**Comment by 0lafe** [comment]
>the new ore finders make finding ore too easy so let's mess with mining to remedy it

This seems worse than my coin complaint

**Comment by Bluebine** [comment]
I don't really like this idea. The lower the density of a vein, the more annoying it is to mine (if you've ever played Terrafirmacraft you'll know all about this) and it just feels unnecessary, since all you're doing is putting down less ore blocks but increasing the yield per block.

> So players can choose between adding speed, durability, or bonus output to their tools

Fortune only takes up one modifier slot, it's not gonna hurt you much to have to put it on your pick, as long as you've found a lapis vein.

**Comment by Dream-Master** [comment]
yea i am against it to especial for the start when you have nothings the veins are to small.

**Comment by Prewf** [comment]
Wouldn't nerfing the ore finder wand be easier for you, codewise? Just sounds like it needs re-tweaking since it's apparently too good right now.

**Comment by Dream-Master** [comment]
nah its not to good ut maybe we need two variants of the wand a low and a high tec variant maybe.

**Comment by sthegreat** [comment]
To me this feels awkward and unintuitive on pickaxes - in mc, blocks generally either drop themselves, or they drop only something else related (like a gem, dust, crushed ore, etc.) It's kind of weird from a player's perspective to have something drop itself and then some extra, but only when naturally generated.


If it were added to (gt) hammers which drop crushed ores already, it would make more sense to me. However this presents tiering issues - if it is worse than macerator, it is obsolete come steam age, and if it is better than people will use it way longer than we probably want them to.

**Comment by DoomSquirter** [comment]
another against it:
how does that work then for ppl that choose to use silk touch cause they want to collect stone not cobble everywhere.  seems punitive if you reduce overall density but boost fortune.  stone is a building material, can make stone bricks, etc.  cobble even chisel isn't really.  I silk all the greg rock types to save myself a cooking step, etc.

same for autominer.  how does it handle that.  does it think it's manually placed or even take fortune into affect?

how does it deal with hammer?  does it account the fact that you're mining 9 blocks not 1 and fortunes all 9 or just the one you hit?

**Comment by richardhendricks** [comment]
@sthegreat This is exactly how leaves work?

**Comment by sthegreat** [comment]
It would be more like leaves still dropping apples and sapling in addition to themselves when broken with shears, but only dropping thenselves when placed and sheared a second time.

**Comment by richardhendricks** [comment]
On silk touch, yeah you're just screwed I'm afraid.

Miners don't apply fortune, I think? so they would get a penalty if we also do the density decrease.

 I would assume the hammer would fortune all blocks, it appears to when they are small ores anyways.

@Anarack The crush count would be configured in the fortune code, not using the macerator recipe.

@sthegreat Is it just as confusing that luck doesn't provide any benefit when mining GT?

**Comment by sthegreat** [comment]
@richardhendricks not really - they behave exacly like vanilla iron and gold ores. I would only expect fortune to potentially have an effect if their default drop was something other than themselves (like vanilla gem ores as well as crops, glowstone blocks, leaf sapling drops etc.)

**Comment by NeroOneTrueKing** [comment]
The only GT ores it makes sense for Fortune to affect are the Small Ores.
Small Ores don't drop their block when mined, and instead drop a variable amount of items.

I don't like the idea very much.

**Comment by richardhendricks** [comment]
OK, seems pretty clear everyone is against this idea. Tabled.

**Comment by Dream-Master** [comment]
Not be sad @richardhendricks  :/
