### ISSUE TITLE
World anchor coins

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3218]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
local server
#
World anchors require coins to run, but amount of coins avalible in ssp/local server is very limited (it is solved by plugins and without /jobs shop like on official servers, but there are a lot of players who prefer local servers instead ).  I suggest adding it to coins coins coins tab (1H coin for 2 ender pearls?) or add HV assembler recipe (ender perls + gold plates?)

**Comment by sthegreat** [comment]
In ssp they should already have recipes (gold coin + liquid ender).

**Comment by Shyrff** [comment]
I've  just rechecked it, but it seems to be unavailable to craft any of coins at least on local server

**Comment by Dream-Master** [comment]
Every server admin can choose how you got the coins. Only on ssp i enable recipe.

**Comment by Dream-Master** [comment]
@Shyrff you cqn add the zzclient.zs script to your server and it work on server too.
