### ISSUE TITLE
Add new features to BQ for more questing control

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3219]
- [ ] Add option to increase quest prices, mutliplier, max amount
- [ ] Add option to limit # of repeats
- [ ] Add buttons to move quests up/down
- [ ] Add buttons to scroll tabs up/down

**Comment by noobyaran9** [comment]
I'll add on something here.

Right click to go back one page. Like how hqm did it.

**Comment by mitchej123** [comment]
Is this still relevant?
