### ISSUE TITLE
Wrough iron quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3221]
Need to change the text.

**Comment by NeroOneTrueKing** [comment]
A couple of edits to fix typos:
`
"Wrought Iron will become more important very soon when you have a bit of steel and are able to build high pressure steam machines. The material is much harder than iron, and you can make better tools with it too.\nTo make wrought iron, you need a tinkers smelter to melt some iron ingots down and cast nuggets; put these in a furnace to get wrought iron nuggets. With the compressor, you can compress the nuggets into ingots.\n\nHint:\nCrushed or purified ore can be smelted to iron nuggets directly. Later on, you can use an arc furnace to make wrought iron ingots directly."
`

**Comment by Dream-Master** [comment]
thanks will add it @NeroOneTrueKing
