### ISSUE TITLE
[RFC] conveyors improvements

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3222]
As you may have noticed it, the GT conveyors, starting from IV, can only move 1 stack/tick, so if you need a conveyor very fast, there is no need to take one from higher tier than IV, turning LuV+ conveyor only useful in crafts. 

My idea is, since nothing can be quicker than a tick, to increase the number of stacks moved per tick for LuV+ conveyors. That way, LuV+ conveyors will be attractive for players who need a very fast transfer item method.

**Comment by Dream-Master** [comment]
good idea but I need help with it. @bartimaeusnek any idea if this can be easy implemented?

**Comment by bartimaeusnek** [comment]
i would suggest asking @richardhendricks , since he fixed the superbuffers, he has more experience in moving stack stuff from GT

**Comment by Dream-Master** [comment]
@codewarrior0 @richardhendricks @mitchej123 
Need help here please. Thanks

**Comment by mitchej123** [comment]
Seems doable.  What scaling past EV?
1, 2, 3, 4, 5 stacks?
or 1, 2, 4, 6, 8 stacks?

**Comment by mitchej123** [comment]
Addressed with: https://github.com/GTNewHorizons/GT5-Unofficial/pull/134 & https://github.com/GTNewHorizons/GT5-Unofficial/pull/135

**Comment by boubou19** [comment]
since t

**Comment by Dream-Master** [comment]
@boubou19 uhv is 16 stacks per tick. I have to add a new pipe to trasport so far. I guess now it is right tiered.

Uhv 16
uv 8
zpm 4
iv 2
ev 1
