### ISSUE TITLE
Mention crop calculator in questbook

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3225]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
sp but doesnt matter
#
#### What did you try to do, and what did you expect to happen?
Players can use the ic2 crop calculator feature to see the chance outcomes of cross breeding
#
#### What happend instead? (Attach screenshots if needed)
People might not realize that feature exists

#
#### What do you suggest instead/what changes do you propose?
Add a note to the cropnalyzer quest about it (and add a cropnalyzer quest if none already exists)

**Comment by Dream-Master** [comment]
I add text rn and will change it if you post a better one here @sthegreat

**Comment by sthegreat** [comment]
Text to add if you dont have a basic description in it yet:

The cropnalyzer is a powered tool used to analyze IC2 crop seedbags. To fully analyze a seed bag, you will need to put it through the cropnalyzer four times. If the crop is already planted, it is better to analyze it with the portable scanner instead of breaking it just to scan it.

Text to add to quest description for the calculator feature:

You may have noticed that NEI does not include every possible combination. The cropnalyzer also has a feature called the IC2 Crop Calculator, where you can find the chance outputs of breeding together any crops. To access the calculator, hit the IC2 side inventory key while holding the cropnalyzer. You can also do this while sneaking, and it will have a different gui, where you can select any crops from a row instead of needing to use them from your inventory.

In either of the GUIs, you can choose up to four crops to breed together. Then click "process" and the bottom row will show the possible crossbreeding outputs, and their weights. You can use the + and - gui buttons to scroll through the row(s) of crops. You can also use a button in the GUI to sort the rows by tier or weight. You can invert the sorting by hitting the sorting button while holding shift.

When trying to get a specific crop, you generally want to maximize it's weight. But more specifically, you want to maximize the proportion of its weight out of all the weights. This means there are usually no benefits or downsides to breeding 3 or 4 crops together instead of 2, since all weights are increased evenly.

Try a variety of combinations to get the crops you want. Often, breeding together two of the same crop is a surprisingly good option or even the best one.

**Comment by Dream-Master** [comment]
@sthegreat thanks.
