### ISSUE TITLE
BloodArsenal issue

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#323]
I've just created an issue at BloodArsenal's repository.
Drobac can't login until it is fixed, so I consider this as high priority.
I tried to fix it myself, but oh boy, dependencies...

https://github.com/Arcaratus/BloodArsenal/issues/25

**Comment by Dream-Master** [comment]
The Mod Author answers so we can hope it will be fixed.

**Comment by Dream-Master** [comment]
I think this is fixed in the new Version 1.2

**Comment by Dream-Master** [comment]
Version 1.2.2 on the Server now.

**Comment by Drobac** [comment]
fixed
