### ISSUE TITLE
GTNH Crashing on world startup. Worked before.

### ISSUE THREAD

**Issue by C9Gun** [GTNewHorizons/NewHorizons#3230]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Just made a new world because i want to return to the pack to try to finish it, but it crashes when the world loads. But Java still shows up in Task manager. 
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

Pastebin: https://pastebin.com/Sqq8428x

**Comment by bartimaeusnek** [comment]
@C9Gun restart you computer, try to load it, do that several times, nothing we can do here really, its a common bug caused by minecraft/forge.
