### ISSUE TITLE
Machine Controller cover

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#3231]
#### Which modpack version are you using?
2.0.4.6
#
Wiki about Machine Controller Cover says: "On multiblock structures the Machine Controller must be attached to the Controller block; with most multiblock structures the only free side is from below, as on others there is currently no side to apply a redstone signal"
Here the problem: I have Oil Cracking Unit, only side is visible is front side. So no Machine Controller can be attached. One Oil Cracking Unit produces 1000L fluid every 2 seconds on HV power. To refine its output amount I need either 2 HV Distillation Towers or 3 MV Distillery or 2 HV Distillery. Too much from my point of view. I want to build small buffer (Gregtech tank) and supply redstone signal to Oil Cracking Uint, so it not voiding output if I can't consume output contents fast enough.
So there is question: Is anything can be done from pack side or problem need to be raised to Gregtech devs?

**Comment by sthegreat** [comment]
Have you tried putting the cover on a side that is covered, and then powering it through a clean stainless steel block or a cupronickel coil (might need repeater or something)?

**Comment by Vicus-N** [comment]
nope, will be surprised if it will work.. Will try.

**Comment by Vicus-N** [comment]
Hmm, this works.
![default](https://user-images.githubusercontent.com/5557050/42129874-987a89c8-7d15-11e8-9b55-d90a4e06ecd0.png)
Thanks @sthegreat

**Comment by MineAnPlay** [comment]
Also it has to be the casing, the hatches and buses won't work.

**Comment by Vicus-N** [comment]
Yep, found more elegant solution: with Redcrystal and Dense Redcrystal from Automagy
![default](https://user-images.githubusercontent.com/5557050/42130350-f82e270c-7d25-11e8-9f22-717bd597f67e.png)

**Comment by Dream-Master** [comment]
maybe a good Quest ? Automagy Redstone.

**Comment by Vicus-N** [comment]
Yea, Automagy Redcrystals very cheap and super useful in some cases.
PS: Dense Redcrystal is used here, cos we need to cutoff week signal from almost full tank buffer, that have < 1000L free space.

**Comment by Dream-Master** [comment]
automagy is not nerfed the last mod.
