### ISSUE TITLE
fiery bowstring required again in ardite crossbow body quest?

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#3233]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
![image](https://user-images.githubusercontent.com/40670872/42138208-3ff08498-7d82-11e8-8c6d-54da2b96c1f3.png)

i dont think this is needed in the quest is it? as the quest before it has the same.

**Comment by Dream-Master** [comment]
so you want a noral bowstring ? @PoptartOverlord-Xabedo

**Comment by PoptartOverlord-Xabedo** [comment]
no the quest before it has the same thing to  do

![image](https://user-images.githubusercontent.com/40670872/42138221-ad365b18-7d82-11e8-8178-d69b2bb9163e.png)

**Comment by Dream-Master** [comment]
ok so you want this task remove @PoptartOverlord-Xabedo

**Comment by PoptartOverlord-Xabedo** [comment]
yes because i see no need for it since both quests have it`
![image](https://user-images.githubusercontent.com/40670872/42138240-fe802a80-7d82-11e8-8196-b84e2998176d.png)
![image](https://user-images.githubusercontent.com/40670872/42138245-0c12a880-7d83-11e8-8bc5-8613e7bdab04.png)

**Comment by Dream-Master** [comment]
will check
