### ISSUE TITLE
Witching gadgets: Infernal blast furnance

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3234]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
was trying out infernal blast furnance from witching gadgets. with native clusters it works fine but creating steel wont work. Is it disabled? 
#
#### What happend instead? (Attach screenshots if needed)
nothing, wont start
#
#### What do you suggest instead/what changes do you propose?
If steel function is disabled why not disable the whole multiblock?  or  even remove the reserch.as without steel crafting it is the same as the infernal furnance?

**Comment by Ghengis88** [comment]
Found the other thread but could not understand what was decided, maby add the recepies that are avalible in the thaumonomicon?

**Comment by bartimaeusnek** [comment]
@Ghengis88 please use NEI. It can smelt everything that is smeltable with Kanthal coils, and has the ability to smelt everything that has only one input from the Simple Blast Furnace. Steel got disabled due to a shitstorm of the community.

**Comment by Ghengis88** [comment]
@bartimaeusnek i might be a tad stupid... but how do i look at a Thaumcraft multiblock in NEI? as it has no dedicated block?
![blast furnance](https://user-images.githubusercontent.com/25811344/42153390-446d0922-7de3-11e8-8b86-a7c4fd8325c5.png)
