### ISSUE TITLE
World Anchor Uncraftable

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#3235]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Craft World Anchor. That used to happen in the Crafting Table, but now it only has an Assembler Recipe. The other two Anchors still have the old Table Recipe.
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/34921674/42144560-f0b74030-7dbb-11e8-9ff8-0192f86570b9.png)

#
#### What do you suggest instead/what changes do you propose?
Give the Anchor its old Crafting Table Recipe again or add a Circuit to the Iron Chests Upgrade Recipes.

**Comment by 0lafe** [comment]
The other recipe also needs a different circuit, diamond plate + dense obsidian + circuit
