### ISSUE TITLE
Open Modular Turrets Mod

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#324]
Did we need this mod for better defend the Base ?

http://minecraft.curseforge.com/mc-mods/224663-openmodularturrets

**Comment by Careface1g** [comment]
Seems like a fun mod to play around with , I'm up for it

**Comment by Namikon** [comment]
Actually, has anyone ever used the **existing** mod to protect his base?

**Comment by Dream-Master** [comment]
I think not (you mean Ulitiy Mobs right?)

**Comment by Namikon** [comment]
And why do you want to add another then, if noone used the old mod ever? :)

**Comment by Dream-Master** [comment]
Some mods are useful some are fun mods. Not take it to serious. So we drop this Mod!?

**Comment by Namikon** [comment]
Add it and we shall see if it's fun. I wonder how these will work against infernals.
But you'd have to make these available early game. As soon as you reach MV/HV, you don't really care about any mobs in/around your base. (At least I don't)

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
- [ ] Make Recipes

**Comment by Dream-Master** [comment]
OK Skip
