### ISSUE TITLE
ender quarry boundary 

### ISSUE THREAD

**Issue by HegemonRast** [GTNewHorizons/NewHorizons#3240]
2.0.4.4  Which modpack version are you using?  2.0.4.4

#
#### If in multiplayer; On which server does this happen?  multiplayer private server 

#
#### What did you try to do, and what did you expect to happen?  set up ender quarry boundary 

#
#### What happend instead? (Attach screenshots if needed)  it was limited to 64 by 64 blocks 

#

**Comment by HegemonRast** [comment]
I am told this is fixed in 2.0.4.6  can anyone verify this ?

**Comment by alphaNOVAircraft** [comment]
Its fixed in 2,0.4.6

but sady lthe transciver isnt better right now so you need somekind of energy production where you place the quarry

**Comment by boubou19** [comment]
just use the microwave energy transmitters

**Comment by noobyaran9** [comment]
How much is the power usage rn?

**Comment by Prewf** [comment]
8x what it was before, for base drain

https://github.com/GTNewHorizons/NewHorizons/commit/e4f6eaffe651c44e6c50dc906e32cafcd986f963
