### ISSUE TITLE
UHV piston use wrong motor tier

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3242]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
tried to craft uhv piston. I expected it to cost UHV motor since UV piston requires UV motor:
![image](https://user-images.githubusercontent.com/12850933/42195082-79de8326-7e77-11e8-935e-2bd4d478b9e5.png)

#
#### What happend instead? (Attach screenshots if needed)
UHV piston use UV motors instead.
![2018-07-03_03 59 47](https://user-images.githubusercontent.com/12850933/42195056-5664f2fe-7e77-11e8-81d0-d78549740e7a.png)

#
#### What do you suggest instead/what changes do you propose?
make it use UHV motors

**Comment by Dream-Master** [comment]
will fix
