### ISSUE TITLE
Issue with yesterdays death, and my "lost" gravestone

### ISSUE THREAD

**Issue by Karl-Markkus** [GTNewHorizons/NewHorizons#3243]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Yesterday, I was in my small 2x6 pool of water outside my "cube" house, looking in my inventory. An invisible infernal spider came and I was not fast enough to defend, and so I died. I also respawned in server world spawn afterwards (Somehow it has to do with going to Twilight Forest, dying there a few times, and it removes your Overworld bed spawnpoint)
#
#### What happend instead? (Attach screenshots if needed)
I did /home, and went straight to my latest death point, but to my horrid surprise, no grave. Boubs even helped me a little, digging down to bedrock to see, if it generated there, but nothing. I also dug a 10x9 hole 5 blocks deep around the deathpoint, but still no grave.
#
#### What do you suggest instead/what changes do you propose?
I was recommended to use the "/gravehelp request" command, I got my unique code today, but it seems that Delta self-service portal is either down, or I just can't connect to it, because it times out all the time. Also, I was recommended to contact staff who can use the "prism" command to rollback my stuff, though it seems that yesterday it was such bad timing for me, since I could not, contact any, or I was just too dumb to contact any.

Anyways, I do wish and hope I could get rollbacked soon.

**Comment by Vicus-N** [comment]
You should go to Discord for this type of support: https://discord.gg/EXshrPV

**Comment by Bryfer** [comment]
User has contacted me over pm on discord
Will look into it further once I'm home from work

**Comment by Dream-Master** [comment]
@Karl-Markkus @Bryfer is this solved? Can the issue be closed?

**Comment by Bryfer** [comment]
Can be closed, yes.
