### ISSUE TITLE
Add Ore Drilling Plant quests

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3244]
Gregtech's multiblock ore drilling plants are one of the best methods of mining until the ender quarry becomes available, but they don't have any quests in the Multiblock Goals tab.

Can we get a quest for the first tier of Ore Drilling Plant, similar to the Oil Drilling Rig?
Prerequisites: Tier 5, Seismic Prospector

**Comment by Dream-Master** [comment]
Sure
