### ISSUE TITLE
OV scaner craft bug

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3245]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
Craft didn't work
#
#### What happend instead? (Attach screenshots if needed)
![unknown](https://user-images.githubusercontent.com/37113583/42233779-2ba97560-7efb-11e8-9a86-fbf52c709312.png)

**Comment by NeroOneTrueKing** [comment]
IIRC, the problem is that the recipe only accepts a completely-drained OD scanner (which ought to be changed).
