### ISSUE TITLE
BBF quest has wrong clay number

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3248]
#### Which modpack version are you using?
2.0.4.6

![2018-07-04_00 49 10](https://user-images.githubusercontent.com/16925725/42248195-996ef7ae-7f24-11e8-907d-818629f3140e.png)
![2018-07-04_00 49 06](https://user-images.githubusercontent.com/16925725/42248190-96b706be-7f24-11e8-812e-214d7f461915.png)
![2018-07-04_00 49 02](https://user-images.githubusercontent.com/16925725/42248196-9b9e73ec-7f24-11e8-8ab5-c45f5ebde44d.png)

The first BBF you make needs 432 bricks (432 clay) + 144 clay dust (288 clay when using the macerator) which in total is 720 clay, but the quest only asks for 576 clay.
Should be a simple fix, just bump the clay in said quest from 576 -> 720.

**Comment by WarlordWossman** [comment]
>You can get clay dust from macerating stained clay, which is the easier way to get it. I vote that instead, the amount of clay is REDUCED to 432 since that's all the clay you actually need, the rest can be stained clay or hardened clay (from mesas, etc.)

While this is ofc true new players like to have an indication of how much they need to farm. Mesas are also not super common so I would indicate the right amount of clay but add the hardened clay as a hint in this quest. You will need more than 1 BBF anyways so the clay will be used at some point.

**Comment by Dream-Master** [comment]
If you be in a biome that have stained clay you are lucky but I won't force people to get it. Change the clay amount seems to be more easy.
