### ISSUE TITLE
Thermal Padding and Tier2 Rocket

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#325]
A full set of thermal padding requires a total of 108 ingots Meteoric **Steel**.
A Tier2 rocket requires 48 ingots of Meteoric **Iron**
I think that's not right, the rocket should be the one that needs a lot of it, not the padding.
On top of that, for the Armor, you have to process the iron to steel in an EBF, where for the rocket you can just use the iron itself.

Suggestions:
- Change the rocket recipe to use meteoric steel instead of iron
- Rename meteoric steel string to meteoric iron string and use iron instead of steel
- Change the recipe for Meteoric Steel String in the wiremill from the long rod to a normal rod and
- Yield 4 strings instead of one for the recipe

That way the Rocket would need 48 Ingots of Meteoric Steel
and the thermal padding (Which requires an insane amount of vis btw), would require around 14 ingots meteoric iron

This makes a lot more sense.

**Comment by Dream-Master** [comment]
I agree. Never seen this from this Material Cost view. Will see what i can change there.

**Comment by Dream-Master** [comment]
- [ ] Changed the Tier 2 Rocket

**Comment by Dream-Master** [comment]
Now a full stack of Themal Clothes ned 24 Meteoric Iron Ingots.

**Comment by Dream-Master** [comment]
In the next update.
