### ISSUE TITLE
Suggestion: add small certus quartz ores

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3250]
Since the change to the certus quartz vein height, I've seen multiple reports of people spending hours looking for the vein for the LV quest that requires it.
The number of certus quartz actually needed in LV is very small and the large time spent looking for a vein at that point seems like a large pause in progress for very little reward when it's found.

I suggest adding a quite rare small certus quartz ore, this would mean that the first few required certus quartz would not be as much of a pain to get, but the rarity meaning that it's better to look for the vein later on when more is needed.

**Comment by Dream-Master** [comment]
will check what I can do.
