### ISSUE TITLE
Recipes for TecTech Dynamo Hatches

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#3251]
Currently the IV, LuV and ZPM 16 and 64A Dynamo Hatches have no recipe. Would be nice if we could get some, since the addition of the Power Station made those hatches (more) useful.

**Comment by Dream-Master** [comment]
So far i know the hatch works only in Tec tech and not in GT.
@Technus any plans to add it to work in GT machines?

**Comment by draknyte1** [comment]
They also work in GT++ machines, so lower tiers would probably be useful for people using Sub-Stations.
