### ISSUE TITLE
Incompatible Blaze Powder types

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#3252]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
Tried to do the quest "ender eyes" 1233 as well as some recipes using blaze powder.
#
#### What happend instead? (Attach screenshots if needed)
nothing worked. The reason seems to be that I have "blaze powder 377:32767" instead of the "blaze powder 377" and the "blaze powder 377:32767" does not work in the quest or any of the recipes (it is not oredicted).

steps to reproduce: The "blaze powder 377:32767" comes from centrifuging a "fire charge 385" which I get in good amounts from my mob farm. Then use it in the blaze rod recipe (crucible) or the recipe for tiny piles or probably any other recipe.

#
#### What do you suggest instead/what changes do you propose?
Either oredict the "blaze powder 377:32767" properly or just change the centrifuge recipe and any possible other recipe that produces it to instead produce the normal blaze powder.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/42409737-053aefb2-81df-11e8-9f2a-8fbf1b461ac1.png)
recipe works check quest now

**Comment by chochem** [comment]
did some more testing:
**working**: chem reactor (magma cream, eye of ender) (I had not used these recipes so far because I already had magma cream and eye of ender without it)
**Not working**: recognition in the quest, compressor, fluid extractor, crafting table (only tested SOLS and small/tiny pile), centrifuge, alchemy (the blaze rod recipe, though I might have messed up something else here who knows)

nothing else tested.

**Comment by chochem** [comment]
example:
![2018-07-07_13 38 07](https://user-images.githubusercontent.com/40274384/42411042-9a87f666-81ec-11e8-8c86-e6be55130c37.png)

**Comment by chochem** [comment]
other example:
![2018-07-07_13 42 57](https://user-images.githubusercontent.com/40274384/42411080-a62dde4e-81ed-11e8-8ebb-c2926241d6c4.png)

**Comment by chochem** [comment]
This is the blaze powder in question btw:
![2018-07-04_10 55 58](https://user-images.githubusercontent.com/40274384/42411086-d2797e18-81ed-11e8-9f50-c1ba9fb8c01d.png)

**Comment by Dream-Master** [comment]
i can look for all 32k issues in gt code and set it to 0

**Comment by Dream-Master** [comment]
Guess i fixed it allready removed all 32k meta ids

**Comment by liveseaandsky** [comment]
I'm having this exact issue in 2.0.5.1, it does not appear to be fixed.
