### ISSUE TITLE
Passive chunkloading incorrect info

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3253]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
In the Passive Chunkloading quest (number 1528), it says "Passive only loads once the owner visits, and stays loaded until they logout."
#
#### What happend instead? (Attach screenshots if needed)
After a bit of testing, passive anchors do keep chunks loaded after the owner logs out.
I'm not sure whether they can be loaded by others or just the owner.
#
#### What do you suggest instead/what changes do you propose?
Change the quest text (and maybe consider upping the running cost).

**Comment by Dream-Master** [comment]
If this is true the passive loader are to strong because you got more time with coins in passive loaders than other chunck loaders.

**Comment by alphaNOVAircraft** [comment]
As far as i know the only difference between the passiv anchor and the world anchor is that the passive  on is not active after a server restart until the owner visits the chunck one time, afterwards it stays active like th e world anchor until the server restarts. so you shoul change the duration the coins last in that one

**Comment by KiloJoel** [comment]
Personal anchor becomes active when the owner logs in and deactivates when the owner logs out

**Comment by Dream-Master** [comment]
ok mean passive anchors better because they load chuncks wenn server log off for 12h till server restart.

**Comment by KiloJoel** [comment]
Personally though, it seems like encouraging use of personal anchors by making them the cheapest means encouraging people to afk on the server, contributing to tps problems.

**Comment by KiloJoel** [comment]
I'm not sure really, it's probably worth getting some more opinions.

**Comment by KiloJoel** [comment]
My thoughts at the moment - make personal anchor LV, Passive anchor MV, and raise passive anchor to the same running cost as personal.

**Comment by Dream-Master** [comment]
ye i change it in tier and personals have a bonus now with coins like passive before.
