### ISSUE TITLE
TiCon xbows/TiCon Swords

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3256]
#### Which modpack version are you using?
2.0.4.6

#### What do you suggest instead/what changes do you propose?

I know that everyone loves their crossbow and all, but aren't they a little OP? You really have 2 damage options, a swordlikething or a rangedlikething. Theres a best version of both, but the crossbow dominates the melee weapons so much that it seems a little unreasonable. I'm in MV right now with a 60 heart crossbow that has 1000 shots. If I look a little into thaum, I'll have infinite shots. The best sword I ever had was a tungstensteel (EV+) sword, all decked out, made from magical wood, all the stuff. It did either 49 hearts or 49 damage, I can remember which, but either proves my point. 

The crossbows are also so much safer than using a sword. You can be where you want for gravity infernals, can be 50+ blocks away from mobs that can only melee you. While swords can have lifesteal, so can the crossbow in the same way. 

I think that either crossbows should be nerfed in some way, or swords should be buffed to make up for their range flaws.

**Comment by WarlordWossman** [comment]
With the current state of things and random infernal mobs you need something that deals okay damage to play normally. Combat in MC was never great, and we are mostly a technic modpack and not a fighting modpack, so it would suck if you take a way the tools to deal with mobs.

If we get mobs to a state that makes more sense you could start thinking about this suggestion but currently it would just be annoying to nerf crossbows.

**Comment by 0lafe** [comment]
So does that mean you want swords buffed?
