### ISSUE TITLE
Quantum solar panel can't be crafted back to GT EV solar panel

### ISSUE THREAD

**Issue by Jocroy** [GTNewHorizons/NewHorizons#3257]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
DigToBuild
#
#### What did you try to do, and what did you expect to happen?
I want to craft an IC2 Quantum solar panel back to a GT EV solar panel.
#
#### What happend instead? (Attach screenshots if needed)
The result of the recipe is shown, but I can't craft it. When I try, the EV solar panel disappears instantly and the crafting grid resets. The recipe seems to be missing on the server side. The recipe works fine on all other tiers (tested in SP).
#
#### What do you suggest instead/what changes do you propose?
Add the recipe.

**Comment by Dream-Master** [comment]
fIXT
