### ISSUE TITLE
Steve's carts: duplicated train

### ISSUE THREAD

**Issue by skeblow** [GTNewHorizons/NewHorizons#3258]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I have some rails (across 2 chunks) and single steve train set for wood chopping. 
Expected one train moving around and chopping trees,
#
#### What happend instead? (Attach screenshots if needed)
Somehow after some time (like month or so) second exactly same train appeared, i have 2 same train now instead of 1.
#
#### What do you suggest instead/what changes do you propose?
Prevent duplication of train.

**Comment by Dream-Master** [comment]
I guess this is a real rare issue i guess ? Steve carts is not open source.

**Comment by Hakameda** [comment]
Wow so lucky, My trains disappear randomly instead of duping

**Comment by boubou19** [comment]
if i remember correctly this happen when cart cross chunk borders while the chunks are unloaded and it can either dupe the cart or as Hakameda said, disappear

**Comment by Dream-Master** [comment]
So russian roulett i guess.

**Comment by WarlordWossman** [comment]
>if i remember correctly this happen when cart cross chunk borders while the chunks are unloaded and it can either dupe the cart or as Hakameda said, disappear

Yeah, minecarts entering an unloaded chunk don't load said chunk and even then they would need entity processing. 
I think now that the chunkloaders are available pre MV we should add a checkbox quest that tells you to cross as few chunk borders as possible when setting up steves carts and dedicate a chunkloader to the area.

**Comment by Hakameda** [comment]
Not really a fix though, because I've had trains disappear while in the
chunk with them, so it's been loaded. Had two disappear, and one duplicated
solar cart

**Comment by richardhendricks** [comment]
I did some testing, and uncovered steve's cart will be hit by lightning and knocked off of their rails.

**Comment by richardhendricks** [comment]
We are also looking at some customizations to Forge to try and prevent entity loss.

![image](https://user-images.githubusercontent.com/1214811/71535685-2efd9980-28cd-11ea-8597-f69270c7ab37.png)
