### ISSUE TITLE
Netherstar Recipe

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#326]
How about a recipe to duplicate Nether-Stars?

As we need a rather large amount of Nether-Stars for high-tier machines and items, I thought we need some way to automate Nether-Stars at some point. Spawning the wither boss comes with a risk, he can be infernal, or he could escape. On top of that, if you need 36 Nether-Stars for 4 Blocks, you have to kill 36 Withers. That's.. meh..

So why not add a recipe, that allows you to duplicate an already existing Nether-Star from a previous kill.

[Diamond-Sword] [Any enchanted Book] [Nether-Star]
[Wither Head] [Wither Head] [Wither Head]
[Soul Sand] [Soul Sand] [Soul Sand]

Yields: 2 Nether-Stars

That way, you could autocraft it. You won't get a yellow heart, you won't get XP or the division sigil,
and it even costs you 2 diamonds, some XP for the book, and you stil have to pay the normal price of 3 WitherSkulls and some soulsand.

So? What do you think?

**Comment by Dream-Master** [comment]
It don't work, i think but if i will disable it.
Maybe adding some nether dust to some bees as by product but not this recipes.
@Namikon
I know you want all material without a fight so the bees would be a solution i can live with.

**Comment by Namikon** [comment]
Sure, bees are also good. And what do you want to disable?

**Comment by Dream-Master** [comment]
If the Diamond Sword recipes works i will disabled it.

**Comment by Namikon** [comment]
Why? It's a weapon and it's already using GregTech Diamond plates...

**Comment by Dream-Master** [comment]
Yes but it is unrealistic like the Thermal paddings using 108 Ingots of Meteoric iron Ore.

**Comment by Drobac** [comment]
maybe replace the sword with something else but i definitely agree with this. For the recipes you need so many nether stars that i sometimes spent half a day just getting 100 nether stars that i needed to get the next thing since a lot of the recipes have nether stars in them and your recipes even more so. Killing the withers isnt even a challenge, its easy to trap them and just keep hitting them but it takes forever and is zero fun, especially if you just had to do the same thing for a few hours just to get the wither skulls.

**Comment by Namikon** [comment]
Then don't forget to also disable all diamond tools in tinkers, that where added with that tinker/gregtech addon

**Comment by Dream-Master** [comment]
Why?

**Comment by Namikon** [comment]
Because it's unrealistic

**Comment by Dream-Master** [comment]
Will see if i can find a nice way to duplicate Nether stars. With Bees and maybe with a recipes.

**Comment by Dream-Master** [comment]
Maybe something with salis mundus in the assembler like the Twilight Forest recipes for Thaumcraft Wands?

**Comment by Namikon** [comment]
I liked the bee idea. But anything that can be automated is fine

**Comment by Dream-Master** [comment]
// --- Nether Star Dust
Assembler.addRecipe(<gregtech:gt.metaitem.01:2506> * 2, <Thaumcraft:ItemResource:14> * 8, <gregtech:gt.metaitem.01:2506>, 900, 256);

**Comment by Dream-Master** [comment]
Bees will follow later

**Comment by Dream-Master** [comment]
In the next update.
