### ISSUE TITLE
Red spectral component not craftable with Ruby lens

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#3261]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Make red spectral component for LuV solar
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/23512002/42333499-8db85972-8083-11e8-8266-f58fe5d46a5b.png)
(It is IV engraver, and it has energy)
#
Green component is craftable with green sapphire lens, 
Blue component is craftable with aqua lens, only red one is not working for some reason.

**Comment by repo-alt** [comment]
It turns out that the lens in the red pane recipe is made out of fool's ruby. Please fix :)

**Comment by Dream-Master** [comment]
sure will do

**Comment by AndrewAmmerlaan** [comment]
The same problem occurs when crafting Etched Low voltage wiring, it requires the ruby lens whose itemID ends with 02. however my ruby lens's itemID ends with 12. It seems there are 2 types of all ruby things (ore, gems, lenses and stuff). The ores in my chest are the 02 variant, so it seems to me that all recipes should use this one (idk how I got this wrong lens). When you fixed this did this recipe get fixed as well?

**Comment by DoomSquirter** [comment]
that's fools ruby.  dunno why it ever existed, it's so stupid.  but it's somewhat intentional.  tbh tho I didn't know you could make lenses out of it, etc.

**Comment by Dream-Master** [comment]
ok will add it to project red recipe too.

**Comment by AndrewAmmerlaan** [comment]
Found another one: Arcane stone blocks too arcane stone bricks also only accepts the ruby lens with itemID ending on 02
