### ISSUE TITLE
Nano goggles infusion refuses to start

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3262]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Multiplayer my own server
#
#### What did you try to do, and what did you expect to happen?
I tried doing the infusion for nanosuit goggles of revealing and it refused to start. When I cheated in new electric goggles of revealing and replaced them on the infusion table I got the infusion to start. I suspect there's a problem with the infusion requiring 0 durability electric googles to get it to start but when you discharge them they have 1 durability.

**Comment by Dream-Master** [comment]
ok will check.
