### ISSUE TITLE
IC2 Personal Safe lacks assembler recipe

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#3264]
Most crafting recipes with screws also contain a similar crafting recipe in the assembler that does not require screws, or provides more of the end product if produced in the assembler.  The IC2 Personal Safe lacks a screwless assembler recipe.  I'd suggest adding one with the following recipe for it: Iron Chest, LV Machine Casing, Basic Circuit.  I tried to solve this through minetweaker, but more than two items in an assembler recipe is not supported there; so if this is determined to be a good idea it will likely require a coded solution in the coremod.

Thanks!

**Comment by Ghengis88** [comment]
what version of the modpack are you playing? assembler has had 6 itemslots for a while now.

**Comment by damug** [comment]
2.0.4.6, you are correct though in that the assembler now has 6 slots, but minetweaker doesn't support more than 2. Thus, until minetweaker is compatible with the additional 4 slots, it will likely need a coded solution.

**Comment by Dream-Master** [comment]
minetweaker is now able to support more than 2 slots till we are on newest version.
