### ISSUE TITLE
Sulfuric Acid in Large chemical reactor

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3265]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
NEI shows a recepie of 3000 L Oxygen gas and 1000L Hydrogen sulfide in Large chemical reactor.
But the recepie is not in the normal chemical reactor. is this wrong or intended?  
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
if this is intended just leave it, otherwise change it

**Comment by MineAnPlay** [comment]
LCR has a few recipes using the circuit 24 that does multiple step recipes in a single recipe. This is indeed intended.

**Comment by Dream-Master** [comment]
there are three recipe types.
For singel block chem
For both
For LCR only

**Comment by Ghengis88** [comment]
ok my bad :)

**Comment by Dream-Master** [comment]
hey np good that people use git and report issues.
