### ISSUE TITLE
tiny pile sulfur + raw rubber = rubber 

### ISSUE THREAD

**Issue by Malforias2** [GTNewHorizons/NewHorizons#3267]
#### Which modpack version are you using?
2.0.4.6

#
#### What did you try to do, and what did you expect to happen?

im Chemical Reactor 1x tiny pile sulfur + 1x Raw Rubber Dust = 1x Rubber
Was leider nicht funktioniert hat. Es funktioniert nur 1x Sulfur + 9x Raw Rubber Dust = 9x Rubber

google.translate
in the Chemical Reactor 1x tiny pile sulfur + 1x Raw Rubber Dust = 1x Rubber
Which unfortunately did not work. It only works 1x Sulfur + 9x Raw Rubber Dust = 9x Rubber

#
#### What do you suggest instead/what changes do you propose?

Im Chemical Reactor 1x tiny pile sulfur + 1x Raw Rubber Dust = 1x Rubber einzufügen.

google.translate
Add 1x tiny pile sulfur + 1x Raw Ruber Dust = 1x Rubber in Chemical Reactor.

sorry für die google übersetzung mein english ist sehr schlecht.

google.translate
sorry for the google translation my english is very bad.

**Comment by Dream-Master** [comment]
ok will add some recipe

**Comment by richardhendricks** [comment]
FYI, if you need 144L quantities for recipes, you can use Tinker's Faucet - attach to a tank, then turn it on/off and it will dispense 144L.
