### ISSUE TITLE
[suggetion] 2 forming press recipes

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#3268]
#### Which modpack version are you using?
2.0.4.6

I would like to see the forming press being used a bit more so I thought about recipes that would actually make sense in there. Found 2 things that are really fitting imo:

1.) Hardened leather:

current recipe:
![hardened_leather](https://user-images.githubusercontent.com/16925725/42412890-48755426-8215-11e8-957c-8113749aea20.PNG)

suggestion:
Forming press: 2 tanned leather + 1 wax ---> 1 hardened leather; 16 eu/t; 10 seconds 

2.) Soft clay jar:

current recipe:
![soft_clay_jar](https://user-images.githubusercontent.com/16925725/42412892-6114f784-8215-11e8-9cc1-d34dbc1fce6f.PNG)

suggestion:
Forming press: 1 clay + mold (bottle) ---> 1 soft clay jar; 4 eu/t; 3,2 seconds

**Comment by WarlordWossman** [comment]
Replacing them is a good idea I would say. At the stage you need both of those items you are probably MV already.

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/42414180-f5e77ad4-822f-11e8-81ad-2478d8899808.png)
![image](https://user-images.githubusercontent.com/2970688/42414183-0a6f4f40-8230-11e8-8f23-00883ed61c8b.png)

**Comment by WarlordWossman** [comment]
Is it intended that you need 4 times the clay for one soft clay jar now? You don't get the empty ones back from the recipes.

**Comment by Dream-Master** [comment]
ah maybe overseen it.
