### ISSUE TITLE
[Suggestion] Default Load Block quest

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3270]
#### Which modpack version are you using?
2.0.4.6
#
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/37113583/42415440-073cf292-8257-11e8-8ee0-d19d85268f3c.png)
You can't complete that quest in multiplayer, I sugguest to make them like this
![image](https://user-images.githubusercontent.com/37113583/42415452-a7e69dd8-8257-11e8-9afc-08df71a83991.png)

**Comment by Dream-Master** [comment]
allready suggested. Will check tomorrow.
