### ISSUE TITLE
[Quest 803] Wrong circuit for quantum armor

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3273]
#### Which modpack version are you using?
2.0.4.6

Wrong circuit type for quantum armor set. Should be 8x Master Quantumcomputer in quest book. 
(Or change both recipe and quest book to use all LuV tier circuit).
![image](https://user-images.githubusercontent.com/30087707/42419831-b67978ec-82bc-11e8-861c-db898f03cf6a.png)
![image](https://user-images.githubusercontent.com/30087707/42419834-bd035692-82bc-11e8-8163-c3b34350899c.png)

**Comment by Dream-Master** [comment]
ok will check

**Comment by Dream-Master** [comment]
It shows not oredicted i do it in quests.
