### ISSUE TITLE
[Suggestion] Change Circuit Assembler "processing" GUI to avoid confusion with Assembler

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3274]
#### Which modpack version are you using?
2.0.4.6

Rocket chip tier 4 can't be crafted with a rocket tier 4 data stick.
![image](https://user-images.githubusercontent.com/30087707/42420070-8e00191c-82c0-11e8-8cdb-3478de575921.png)
![image](https://user-images.githubusercontent.com/30087707/42420074-9cc7ad34-82c0-11e8-9404-7b7bb6a6fe12.png)

**Comment by Bryfer** [comment]
Seems like you are using the wrong assembling machine?
try the circuit assembling instead
![image](https://user-images.githubusercontent.com/22825059/42420172-e3a3b008-82c1-11e8-9885-576cdd4ecd2d.png)

**Comment by DualBallers** [comment]
My turn to get the "Moron" label :-/

**Comment by Bryfer** [comment]
no probs - we have all been there! haha :)
@Dream-Master issue can be closed

**Comment by DualBallers** [comment]
Hi @Dream-Master, I know this is a closed issue, but I was thinking that it would be nice if the GUI of the Circuit assembly machine was unique, to avoid this kind of confusion?

Maybe the "processing" part of GUI could be the original IC2 circuit contour?
![image](https://user-images.githubusercontent.com/30087707/42447583-a8353046-837a-11e8-8d17-bbfef57c8c66.png)  changed to ![image](https://user-images.githubusercontent.com/30087707/42447405-093f64ca-837a-11e8-9bfc-9f7a2e16cf77.png)

Is this possible?

**Comment by Dream-Master** [comment]
yea will try later

**Comment by LogicFalls** [comment]
You rang?
![fragmented](https://user-images.githubusercontent.com/32601565/42657647-cd122106-861a-11e8-8cca-9fa58ca9bae7.gif)

**Comment by LogicFalls** [comment]
Or, an alternative:
![an alternative](https://user-images.githubusercontent.com/32601565/42659020-dea946b6-861e-11e8-9933-f7da511a2eea.gif)

**Comment by Dream-Master** [comment]
second one. First one look like a bug :)
