### ISSUE TITLE
Data Sticks showing up as EV-Tier Circuits in NEI

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3275]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
a player asked me why he could not find the recipie for the GT++ Data Stick.
He was trying to make a Chemical Reactor III and NEI tells you that you can use an EV-Tier circuit Or the Data Stick, Or the Data Stick from GT++

#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/22825059/42420234-e671f8a2-82c2-11e8-8722-0658d8468d54.png)
![image](https://user-images.githubusercontent.com/22825059/42420246-1a5e9b20-82c3-11e8-8d82-91ea8ab5727a.png)
![image](https://user-images.githubusercontent.com/22825059/42420249-2336fd5a-82c3-11e8-9495-251b19a99a1f.png)
![image](https://user-images.githubusercontent.com/22825059/42420259-5d68bfe0-82c3-11e8-8e59-db5fe83b5ab7.png)

#
#### What do you suggest instead/what changes do you propose?
Is the Data Sticks meant to be a alternative for EV-Circuits in crafting?

**Comment by alphaNOVAircraft** [comment]
It is the GT++ data stick, there is no recipe for it. Dont know why he coded a new data stick that has no use so far. It maybe shows up as a EV circut because the EV circuits used to be called dataCircuits back before the massive circuit change. But i dont think the data stick will or shall be a alternative circuit for ev, it is to cheap for it and there is no real sens in driving a machin with an usb stick xDD

**Comment by Dream-Master** [comment]
yea ignore gt++ circuits. @draknyte1 can we disable the circuits?

**Comment by draknyte1** [comment]
Hopefully I fixed it here https://github.com/draknyte1/GTplusplus/commit/e4e8f169c476f593917ae0f6cdde329a3e88f8ee

**Comment by Dream-Master** [comment]
i run newest source and i still see the circuits @draknyte1

**Comment by draknyte1** [comment]
I don't see how.. they shouldn't load if GTNH is detected regardless of config value. 🤷🏻‍♂️

I'll take another look I guess.

**Comment by draknyte1** [comment]
Should've been fixed ages ago afaik.
