### ISSUE TITLE
Early game storage (pre-AE)

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3277]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### Introduction
I have done a bit of research of peoples knowledge of Projectred Transportation over the weekend.
Most player does not even know it can be used as a storage in MV (almost LV tier)

I have also gone thru the quests for Projectred "Ghetto ME System" and these quest requires some rework, first of all this is the intro quest; Sounds really intressting to do these quests right?

Quest: Project red beginning # 127 (it should be
![image](https://user-images.githubusercontent.com/22825059/42423240-83b53ff0-82f7-11e8-981f-edca7d55024d.png)
This text should be in # 738 instead?
This text should be replaced by something like this

> Welcome to Projectred!
This quest will learn you the basic of Projectred and learn you how to set up a Ghetto AE system.
The Ghetto AE system will be really useful for sorting all of your first items

This quest also wants you to craft;
**16x** _Item Transport Pipes_
**16x** _Null-Logic Routing Chip_ (these can be a real pain to craft early game)

Should be changed to (Read more to know why)
12x Item Transport Pipes
2x Null-Logic Routing Chips

At this point you have no idea these quests will lead to a Storage system.

Quest: Can u eat those? # 737
This quest has a good explanation of all the different chips and what they do and are used for.
However crafting TWO of all of these is completely unnessesary!
**Change this quest to just a check box!!**

Quest: Routed Pipes # 738
Explains the different pipes and their functions
This quest wants you to craft 4 of each of the more advanced pipes (from the 16 mentioned earlier)
**change this quest to just a check box!**

Quest: Ghetto ME System # 739
Here is the first proper mention that this is actually a questline for storage, and also the last quest.
It explains how you setup a basic storage system using Projectred. And it will also give you a really handy Drawer Controller to use with it as reward 👍 
Here is a basic setup that I made that works, and uses a fraction of the items the quests wants you to craft..
![image](https://user-images.githubusercontent.com/22825059/42423362-3fd42768-82f9-11e8-8742-4fff0ab730eb.png)
![image](https://user-images.githubusercontent.com/22825059/42423377-66466a1e-82f9-11e8-86dd-0c2ef8b7ad1a.png)
![image](https://user-images.githubusercontent.com/22825059/42423379-6fc9ccde-82f9-11e8-9239-173a85cb63ac.png)

Total Projectred item cost for this setup:

5x (**3x**) _Item Transport Pipes_ (between the request and interface pipe)
**1x** _Routed Request Pipe_ (connected to the chest) (Available in LV tier)
**1x**  _Routed Interface Pipe_ (connected to the Drawer Controller) (Available in LV tier)
- The Routed Interface pipe has these items inside
**1x**  _Item Broadcaster Chip_ (Available in MV tier)
**1x** _Item Responder Chip_ (configured to Blacklist mode) (Available in LV tier)

Change this quest to craft 
Page one: is OK!
8x Item Transport pipe  (8x seems like a decent quest number, 4 seems to little.)
4x Interface pipes (recipe makes x4, 1 needed)
1x Routed Request pipe
Page two:
1x Item Responder Chip (previously 4)
Remove the Dynamic Item Responder (Not nessesary for Ghetto AE)
1x Item Broadcaster Chip (previosly 4)

(someone please calculate and see if these new numbers are correct)

Also The Ghetto AE system Could in theory be moved to LV tier IF the MV circuit for the Item Broadcaster chip was replaced for an LV one OR you can get an MV circuit for this item as a quest reward.

additional quest:
Inputting chest for Ghetto ME System
To be able to put items into the Ghetto ME system you need just a few additional pipes
The Extraction pipe should be connected to the chest you want to take items from 
Inside the Extraction pipe you need to put the Item Extraction chip, and configure it to blacklist if you want it to take all items from the chest
the Routed Junction pipe is needed so the items inside the pipes know which direction to take, without this they will just fly around inside the pipes without knowing where to go.
You might also need some additional item transport pipes depending on your setup.

items required to complete the quest:
1x Routed Interface Pipe (7955:2)
1x Item Extractor chip (7956:4)
1x Routed Junction Pipe (7955:1)

reward:
Lootbag

~There should also be an ADDIDIONAL quest which I can write tomorrow because.. work.. (and this took way longer than I expected)
This quest should show you how to make an input chest for the drawers to place near the output chest.~

#
#### Summary
Change quests to not make unused items for the Ghetto AE.
Players can make extra items if they want to use Project Red for something else, or just make more pipes if they want longer pipes

Also this quest line should be moved to the current "AE System" quest tab
the EnderIO Inventory panel (HV-Tier) should also be moved to this quest tab

Any additional storage systems I might have missed should also be moved here
This questline should be opened up after you complete Better than Barrels (questid: 727)  in Stone Age?
if so, Better than Barrels must be a main quest

"AE System" quest tab should also be renamed to "Storage Systems" (or similar)

**Comment by Vicus-N** [comment]
Only 1 annoying issue with this Ghetto AE that it shows less or equal to one stack of each item in system, even you have more...

**Comment by Bryfer** [comment]
The reason it shows 1 stack of each item is because of limitations in drawers. If you want to you can use chests instead of drawers, but if you do that you need the chips and pipes to every chest instead.
Also it's not really too babe considering its available in early tier /lv/mv
Also it does not use any power, So that little down side is something to expect from early game storages
There must be something bad with it right?

**Comment by mitchej123** [comment]
> The reason it shows 1 stack of each item is because of limitations in drawers

It's probably a limitation in the API that PR is using to get the inventory count; I don't recall AE2 having the same issue when reading storage drawers numbers.

**Comment by Dream-Master** [comment]
No i dont want to put it on ae side. Ae quests are not done yet and i will not mix it up with PR quests.

**Comment by Dream-Master** [comment]
i will change pr quests and we see if this works before we move to one tab.

**Comment by Dream-Master** [comment]
@Bryfer what is about to change recipes of pipes first from PR before change quest ?

**Comment by Dream-Master** [comment]
ok i fixt so much i can. Put all in ae tab not happend now.
