### ISSUE TITLE
Make rutile quests optional-Titan Ore balancing

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3278]
#### Which modpack version are you using?
2.0.4.6
#
#### What do you suggest instead/what changes do you propose?
There is no need to make titanium from rutile when you already found a pure titanium vein on the moon. Making titanium from bauxite and ilmenite is really inefficient and completely useless when you already found the pure titanium vein. So I'm either for making the quests optional or moving the pure titanium back to Mars.

**Comment by Dream-Master** [comment]
yea maybe put pure titanium to mars would be a good idea but i guess i see the shit storm allready.

**Comment by alphaNOVAircraft** [comment]
> put pure titanium to mars would be a good idea

agree with this point, the titanium vein is one of the best veins in the whole game, gating it behind the mars seems resonable to me. You dont only get a easy source of titan, you also obtain massive amounts of chrome and manganese, wich leads to a nearly infinit amount of stainless stell (wich seems a bit early). 

When we found one it was pretty rewarding. Think i would be a good balance change

**Comment by mitchej123** [comment]
Read through https://github.com/GTNewHorizons/NewHorizons/issues/1977 before we open this can of worms again please.

**Comment by Dream-Master** [comment]
maybe we Need to think of a light titanmix for the moon and a better for mars. Or/and small titan ores maybe.

**Comment by alphaNOVAircraft** [comment]
Then we shoul maybe buff the bauxit to titanium route, but the pure titanium vein still seems a bit to good for being found on the moon, its not only a direct source of titan, but also like i pointed out, a massive supply of chrome and manganese. 

We could e.g. just edit bauxit that you get like 6 or 8 crushed out of one ore and maybe add some titanium tiny piles in the ore washer / thermal centrifuge insead of additional bauxit dust.

**Comment by WarlordWossman** [comment]
I think going with a byproduct first and a pure ore on the next planet is a good idea, only small ores is not the best idea tho. I like the bauxit idea, obv rates have to be looked at.
With all the ore processing there is it's kinda lame to just find the pure ore instantly.

**Comment by Lainiel** [comment]
How about puting Ilmenite in the secondary layer of bauxite vein and making it grind into rutile dust directly? You should be able to produce enough titanium this way.

**Comment by alphaNOVAircraft** [comment]
Not too sure if it is worth the bauxit processing if you get illemenite directly, but e.g. as "around ore" i would definitly like the idea of adding some illemenite

**Comment by Dream-Master** [comment]
The main question is how much Titanium you need till you reach Mars?

Rutile is really gindy but a first way to get Titanium. Maybe we can boost it with small ilmenite/titanium ores or so. Or we add a poor oremix to the moon including ilmeite/titanium and move the moon mix to mars.

**Comment by Methes** [comment]
Oh ffs stop reinventing the wheel and leave pure Titanium at peace already.

**Comment by Dream-Master** [comment]
If we leave it there we can disable rutil to titan production allready because it is usless.

**Comment by MineAnPlay** [comment]
Please just leave it as is. This topic has been discussed many times over. Don't change anything, keep rutile as is.

**Comment by Dream-Master** [comment]
And now we do it again. That doesent mean that i change something now but will hear a few commts on it.

**Comment by NeroOneTrueKing** [comment]
My anecdote:
I have personally used the rutile method once, to produce 2 titanium ingots, before I reached the moon:
`Aluminum Gravel Ore -> Bauxite Dust -> Rutile Dust -> Titanium`
It let me upgrade my thaumcraft stuff a little earlier than expected, but that's all. It felt appropriately difficult to do because I was making titanium before getting to the moon. Once I made my first rocket and got to the moon, I was very glad that I had a method of obtaining titanium that would be reasonable to use to make stacks of ingots.

I think:
1 - The rutile method is okay for making SMALL amounts of titanium before you are expected to build EV machines.
2 - The rutile method should be optional.
3 - Pure Titanium ores should remain on the moon, unchanged.

**Comment by richardhendricks** [comment]
Put me down for leaving it as-is as well.  If you get some aluminium bees, you can process small quantities of rutile pre-moon.  I did some just to get better mufflers for pollution handling.  I did process about 8 stacks of titanium out of rutile once my pure ore stocks ran out (3 titanium boilers), so I'm pretty familiar with the process. But expecting players to do the full rutile cycle until they get to Mars is a bit much IMO, and really delays the benefits for going to to the moon.  Don't forget the efficiency hit too - you get a lot less titanium per oreblock when you have to process rutile.

**Comment by Dream-Master** [comment]
ok but then I will put rutile quest to hv and let it main quest.

**Comment by Methes** [comment]
Adding it to HV is okay. DO NOT make it a main quest.

**Comment by Anarack** [comment]
Couldn't hurt, possibly mention it can be used to boost plastic production as well.

**Comment by Dream-Master** [comment]
Ok so far I read here right people don't want a to take ore change. I will move rutile quest to hv and make it not main quest .

**Comment by alphaNOVAircraft** [comment]
But when we keep the titanium vein at moon, we still should maybe nerfe the by ores

**Comment by Dream-Master** [comment]
@alphaNOVAircraft suggest a new or different mix .

**Comment by Dream-Master** [comment]
what about Uvarovite?

**Comment by Dream-Master** [comment]
and Grossular Ore?

**Comment by alphaNOVAircraft** [comment]
I would move Uvarovite to sporadic = decreases the amount of chrome you will get from that vein.
Grossular is just a replacement ore for the Chromite in the case we only rebalance the titanium vein, with balancing both we would add spessaartine instead of chromite, that would make it worth to dig for the bauxit vein because you can get some manganese out of the vein.

**Comment by Dream-Master** [comment]
but thgis is your suggestion? @alphaNOVAircraft 
Titanium Vein:
Primary: Titanium Ore
Secondary: Perlite Ore
Between: Bauxit Ore
Sporadic: Uvarovite Ore

Bauxit Vein:
Primary: Bauxit Ore
Secondary: Almunium Ore
Between: Ilmenit Ore
Sporadic: Spessartine Ore

Why we spawn in pure titanium maybe replace it with Ilmenite. Titan not appears in clean form in rl.

**Comment by WarlordWossman** [comment]
I mean a lot of people in this thread want to keep the pure ore, but this change would add least make both veins worth going for.

Did saw that there is titanite ore from GT++ but it says that it only spawns in one of the GT++ dimensions so I am not sure if we could use it for an ore mix.

**Comment by richardhendricks** [comment]
In general, I am against removing pure titanium ore on the moon.

However, if you decide to do this, you *must* raise the weight of the titanium vein. Right now it is only 16, and I don't think making ilmenite the between ore gives players enough.

Also, forcing players down this route will put pressure on magnesium (maybe we need more marble now?) and even more on salt for chlorine.

**Comment by Dream-Master** [comment]
Normal GT ore mixe not have pure Titanium so far i know. I will check later how hard it is to get Titanium from Ilmenite.

**Comment by Dream-Master** [comment]
Not sure if change Ilmenite to primary would be enought and make the vein bigger and more dense maybe.

**Comment by WarlordWossman** [comment]
I think the 2 veins @alphaNOVAircraft suggested make a lot of sense as far as the ores go.
If you do anything else only change out titanium ore please, and yeah I wouldn't mess with the weight and all that jazz.

**Comment by richardhendricks** [comment]
Can we add ores?  Weird we don't have a direct Rutile ore, since Rutile/TiO2 is a normal mineral.
https://geology.com/minerals/rutile.shtml

**Comment by Dream-Master** [comment]
yes sure i can add new mixes. I dont like th idea of pure titanium. If we add more ore mixes with ilmenite /rutlile or other new added materials (in the GT material list)

**Comment by richardhendricks** [comment]
I would be ok with a Rutile orevein I guess, just don't forget the magnesium and chlorine pressure you are adding if you force everyone to Rutile processing.

**Comment by NeroOneTrueKing** [comment]
Correct me if I'm wrong, but was there not another thread, talking about doing this exact thing (removing pure titanium from the moon), which was greatly disliked and then the idea discarded? Why has this thread shifted from "Rutile quests should be optional" to "Let's make Rutile processing mandatory"?

**Comment by Dream-Master** [comment]
Make things harder/realistic or balanced are not like by all players. Sure the main issue was to remove rutile quest as main quest. I can open up a new issue if this is better.

**Comment by NeroOneTrueKing** [comment]
Yeah, once an issue falls off the first page of issues on github, it usually gets a lot less attention, and it also gets messy (like the logistics pipes discussion).
Making a second thread with a title like "Re-balancing Titanium & Rutile Mining & Processing" would make it nice and clear what I/we should be discussing :)

**Comment by Dream-Master** [comment]
ok sure

**Comment by repo-alt** [comment]
In the other modpack I played (essentially vanilla GT5 test pack) Moon was the place where you did get cheap aluminium, and Mars was the place with cheap Titan, and tbh I see nothing wrong with that, it's not like you need lots and lots of titanium to get to the Mars. Just my 5c.

**Comment by mitchej123** [comment]
Rutile is a bit too painful, titanium a bit too ez mode.  A nice middle ground would be great.  Increased yields from rutile? Titanium reduced in density/amount in a vein on the moon and bigger on mars?  Other?

**Comment by Dream-Master** [comment]
yes that's what I want. I checked Ilmenite and end up again with rutile.
