### ISSUE TITLE
RWG be now RTG

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#328]
Another Guy picked up the work from Ted and try to finished the Mod. If been on a open today already;-) I chatting with him already in the Forum to know what he is planning.

https://github.com/whichonespink44/Realistic-Terrain-Generation

**Comment by Namikon** [comment]
Good news in general. Sad thing is, it is pretty useless for us unless we're going to do a complete Map-Reset. According to his info-page, he's going to remove all custom Biomes that RWG had. This would make the map even more corrupt and messed up than the way it is already

**Comment by Dream-Master** [comment]
Maybe this Mob we add when the pack is so far ready and we start a new map. But not worry this is in the fare future.

**Comment by Dream-Master** [comment]
Ok look at this mod but we cant add them with the existing map.

**Comment by Dream-Master** [comment]
Testing RTG 0.0.6

**Comment by Dream-Master** [comment]
Maybe add this later if we have a void dimension for the player bases.
