### ISSUE TITLE
[Quest 1417] Unable to complete

### ISSUE THREAD

**Issue by BlackAce21** [GTNewHorizons/NewHorizons#3280]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft (well not anymore)
#
#### What did you try to do, and what did you expect to happen?
Complete quest ID 1417
#
#### What happend instead? (Attach screenshots if needed)
It would not complete past the air filter stage
#
#### What do you suggest instead/what changes do you propose?
I have already fixed this on our server but the quest task needs to have the ignore NBT advanced option set to true, only way it will properly detect the air filters. Tested it with a player on the server and it works just fine with this change

**Comment by DualBallers** [comment]
Fixed #3180

**Comment by Dream-Master** [comment]
@BlackAce21 will be in next release 2.0.4.7.
