### ISSUE TITLE
[Suggestion] Introduction of Steves Factory Manager quest(s) to help with Assembly Line automation

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3282]
I think everyone that has finally built a full Assembly Line (AL) has had the same realization that I've had - it is really difficult to automate the AL. 
When you have more than a handful of recipies where a certain amount of materials need to go to a specific set of input buses, then even EIO conduits will not easily help you.

I looked through discord and found that the user 'Repo' made a incredibly compact automated crafting system using ~~Steve's Factory Manager~~(edit OC).
![image](https://user-images.githubusercontent.com/30087707/42449647-c747a9bc-8381-11e8-8baa-0ec7665cf41a.png)

I have never played with SFM, the barrier of entry to making a functioning automated AL feels a bit daunting, when "coding" is involved.

I think it would be nice to have SFM quest(s) that guides you to automate e.g. the LuV Motor.
From there on you would need to figure out how to expand the SFM system yourself.

SFM is not introduces elsewhere in the quest book and this seems like a perfect fit for it?

**Comment by Dream-Master** [comment]
you need to write me some text to understand it an make quests. I never used or build it

**Comment by Dream-Master** [comment]
do it as easy as possible or wite the quests. I never ever used it before. Try to explain it a Noob.

**Comment by 0lafe** [comment]
As someone that used SFM, the basic ideas can totally be put in a quest without doing it for you. Maybe have some stuff explaining how to detect items, use AE with more than 9 items per craft, and that's essentially automated assembly line. 

There's also some nice ways to split it between 2 sfms and run an almost infinite amount of them, but it's a little more complicated to explain, but maybe just mention it's possible. 

But at the same time, I kinda see it like the botania challenges. You're meant to do it yourself, but you can always ask in the discord or something. It's a fun thing to figure out once you get it.

**Comment by repo-alt** [comment]
I suggest you do that, because with OC all I can do is publish the scripts themselves, which is a bit cheating.

**Comment by DualBallers** [comment]
Hey @repo-alt, thanks for joining the discussion. I guess I must have misread your post while going through discord looking for a "simple" solution. I agree that OC is definitely not suitable for a quest :-D

@0lafe yeah it was my initial thought that the SFM quest should just point towards the correct blocks to use, to help players like me understand the possibilities and strengths of the mod. And then maybe explain in simple terms how to setup the code-block structure to detect/send items for crafting in the assembly line.

Sure you can ask in discord, but it's nice when there is a quest that pushes you in the right direction from the beginning when playing with the more advanced mods.

**Comment by Prewf** [comment]
>And then maybe explain in simple terms how to setup the code-block structure to detect/send items for crafting in the assembly line.

I'm all for this, but you'd literally need a wall of text to explain all the aspects of SFM and I don't know how many people would go for that..

This is very similar to how the math behind Large Turbines isn't explained anywhere in the game. It's one of those things where you have to access external info yourself (either watching a youtube video or reading a wiki page) and then asking questions in discord.

**Comment by Prewf** [comment]
Perhaps a single quest informing the player that SFM **can** automate the assembly line would suffice? And the quest can be about building the main inventory manager block. The "how to flowchart a solution" after that would be up to the player to find out for themselves.

**Comment by 0lafe** [comment]
I'd like that, I think telling people that it can be automated is important

**Comment by richardhendricks** [comment]
Could there be a simpler automation to use with SFM to give players ideas? Maybe with the LCR to start with?  Or perhaps ore processing?

I don't have any experience with SFM and the AL to create quests, but if someone else writes them up I can add them to the questbook.

**Comment by DualBallers** [comment]
By the way, it is indeed possible to nearly automate the input to the AL using only EnderIO.
Each chest handles a specific item type (motor, pump,piston,...) and the output colors filters towards input to ULV bus 1, 2, 3 and so on.
It's not pretty but it does the job nicely as long as no AL recipes are crafted simultaneously...
![image](https://user-images.githubusercontent.com/30087707/46559373-737bce80-c8f0-11e8-97b5-6b65ae3c1a5a.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57416635-84622a80-71c6-11e9-9538-de6ed3e6ee56.png)
![image](https://user-images.githubusercontent.com/1214811/57416435-00a83e00-71c6-11e9-8abf-39301471253b.png)
Unlocks with IV circuit mainframe.
![image](https://user-images.githubusercontent.com/1214811/57416464-1a498580-71c6-11e9-90ae-196f374c94d0.png)
![image](https://user-images.githubusercontent.com/1214811/57416470-1ddd0c80-71c6-11e9-96f2-9ba7f3512012.png)
![image](https://user-images.githubusercontent.com/1214811/57416473-22092a00-71c6-11e9-9f91-39224aa88b65.png)

For additional quests, please submit a new ticket.
