### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by YoutubePrincess** [GTNewHorizons/NewHorizons#3283]
Is it possible that you can add the morph mod and inventory pets mod to the modpack? As well as if possible please add twinkling lights. That would be really fun.

**Comment by Bryfer** [comment]
Possible, but we need more information about the mods
Please provide links to the mods to make it easier for us to know what mods you mean :)

**Comment by YoutubePrincess** [comment]
Morph mod: http://www.minecraftmods.com/morph-mod/
Twinkling lights: https://minecraft.curseforge.com/projects/fairy-lights
Inventory pets: https://minecraft.curseforge.com/projects/inventory-pets
Is that good?

**Comment by WarlordWossman** [comment]
I don't think we need any of those 3 mods. Only strong opinion I have would be to NOT incluede morph mod by any chance, I don't like it at all and it's super gimmicky.
The other 2 mods don't look too great, I would rather not increase the loading time for the minor things they add to the game.

**Comment by YoutubePrincess** [comment]
Alright thanks

**Comment by boubou19** [comment]
I'm against Morph mod because with it, it become too easy to have access to feather falling( kill a chicken then morph into it), to fly (kill a bat/butterfly and morph into it) and climbing walls (kill a spider and morph into it)

**Comment by WarlordWossman** [comment]
Even if you disable the "special effects" of the creatures you shouldn't be able to change your hitbox size by any means since it makes cheesing mobs way easier...

**Comment by bartimaeusnek** [comment]
I'm actually for Twinkling Lights. Paul Fulham did some great coding stuff there. I would contact him and ask if we could modify the mod for our needs.

**Comment by Prewf** [comment]
@boubou19 also, witchery has this already with the infernal infusion. it doesn't have the downsides like morph does though, but it's very similar

for more info, https://sites.google.com/site/witcherymod/infernal-infusion

**Comment by Dream-Master** [comment]
I wont add morph! Creative fly as a bat no way. We tested it allready and removed it. 
The other mods idk will look inside.

**Comment by bartimaeusnek** [comment]
@Dream-Master ill close this since Twinkling lights are "closed source" aswell since the author doesnt want us to modify his code in any way. Not even bugfixes.

**Comment by draknyte1** [comment]
> @Dream-Master  ill close this since Twinkling lights are "closed source" aswell since  the author doesnt want us to modify his code in any way. Not even  bugfixes.  

Where did you find this?
There's no license attached to the 1.7.10 branch that says you can't fork it.
https://github.com/pau101/Fairy-Lights/tree/1.7.10

**Comment by MineAnPlay** [comment]
The 1.7.10 version doesn't but the newer versions do. We'd still need to at least ask for permission.

**Comment by Ugachaga** [comment]
Are there any critical bugs in the mod that need to be fixed?

**Comment by bartimaeusnek** [comment]
I asked him directly if we could fork his 1.7.10 and use it. This was his answer:

> Paul Fulham - letzten Donnerstag um 21:47 Uhr
> No, sorry, I do not want new releases of my mods promoting the continued use of severely oudated and insecure versions of minecraft.

**Comment by draknyte1** [comment]
His license and source code availability on GitHub don't reflect this. In a court of law, his statement wouldn't hold up based on these. 

Like the other mods I've forked, I go off of what GitHub offers me and it's not my responsibility to message content owners.
