### ISSUE TITLE
Typo in item "casting form (large pipe shape) 5994" doesnt have R in large

### ISSUE THREAD

**Issue by LaM0x** [GTNewHorizons/NewHorizons#3285]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Dig to Build
#
#### What did you try to do, and what did you expect to happen?
the R in the word large is missing form "casting form (large pipe shape)" and spells "casting form (lage pipe shape)" instead
#
#### What happend instead? (Attach screenshots if needed)
n/a
#
#### What do you suggest instead/what changes do you propose?
add the R

**Comment by Dream-Master** [comment]
ok sure
