### ISSUE TITLE
QED Table Recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#329]
Adding the Molecular Transformer to the QED Table.

![image](https://cloud.githubusercontent.com/assets/2970688/9833602/dc9d6070-599c-11e5-8fcb-680d88e87aab.png)

**Comment by Namikon** [comment]
Suggestions for more to add:

EnderQuarry + Updates
EnderChest/EnderTank/EnderPouch (The item, or parts required to craft them, like EnderInfused Obsidian, Computational Matrix,...)

basically everything that needs EnderPearls/Liquid Ender/.. Ender stuff.
