### ISSUE TITLE
angermobs and vampirism

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#3290]
#### Which modpack version are you using?
2.0.4.6
all mobs (even players) have a chance to explode explode on death when using melee in general unless you're using knives and butcherknives which is a bit of a problem for vampires as explosions count as fire damage and we die from it.
from my multiple talks with others they leaded me to that angermobs is the mod that makes mobs explode on death
my request is pretty simple, its to make the cane sword which is a weapon only a vampire can make not explode anymore, as vampires have a melee buff and also are stronger using it but the random chance of explosions is a huge backlash   that sometimes end horribly.

**Comment by Dream-Master** [comment]
@PoptartOverlord-Xabedo so what you suggest exactly ? cane sword?

**Comment by Ethryan** [comment]
Think he wants the Cane Sword added to the list of items that disallows angermobs explosions.

**Comment by PoptartOverlord-Xabedo** [comment]
witchery has a weapon that only vampires can make and use called cane sword,im,suggesting that the cane sword doesnt have a chance for kills to explode
![image](https://user-images.githubusercontent.com/40670872/42508031-d2aff10a-844f-11e8-843a-563f83dda2b3.png)

**Comment by PoptartOverlord-Xabedo** [comment]
yes thanks  ethryan.

**Comment by Dream-Master** [comment]
Sure if someone can code it.

**Comment by PoptartOverlord-Xabedo** [comment]
actually the angermobs mod appears to be an mod exclusive to this modpack..is it alright if you ask the one who codded it?

**Comment by PoptartOverlord-Xabedo** [comment]
first, apparently the mod is called angermod i apologize for that,
second, it appears to have a config and i've found it 
`# If the player is using one of these items, entities will not explode if they are killed [default: [flint]]
    S:KamikazeItemBlacklist <
        gt.metatool.01.34
        gt.metatool.01.36`

**Comment by Dream-Master** [comment]
@PoptartOverlord-Xabedo yes Namikon is the author but he hvent much time so far i know thats why i ask for help .

**Comment by PoptartOverlord-Xabedo** [comment]
yes there is the Creative Bat/Wolf Token @richardhendricks
