### ISSUE TITLE
Alvearies (How to be(e)) incorrect amounts (low priority)

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3291]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
in stage 4/7 you are requested to get 1728 Oak Wood and 54 Seed oil cells.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
As i assume this is in preperation for the next step when you need 27 Impregnated casings the amount is far to high. 27 casings require 216 wood and 6750mB (6,75 cells). i sugest to change the numbers in the quest to 216 wood and 7 seed oil cells.

**Comment by MineAnPlay** [comment]
It's 864 wood and 39150mB Seed Oil for one Alveary.  Don't forget that the Scented Panels require Impregnated Sticks.

**Comment by Ghengis88** [comment]
yes, but if tou do the steps in order you already have the scented panels finished when you get to that stage
