### ISSUE TITLE
Add chat switches to enable/disable GT debug settings

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3292]
Would be nice to enable/disable GT debug modes without having to restart whole game.

Look at adding some chat mode commands to enable/disable debugOrevein/debugCleanroom etc for OP use.

**Comment by Dream-Master** [comment]
yea Namikon using some commands you can reload via config to be switch on and off in his mods. @richardhendricks

**Comment by Dream-Master** [comment]
Like Lootbags etc

**Comment by richardhendricks** [comment]
I know, it's where I got the idea. :)
