### ISSUE TITLE
[Quest #1531] Quest using wrong Data Stick

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3294]
#### Which modpack version are you using?

#2.0.4.6
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Did the quest on the schemetic Tier  4, wannted to detect my Data Stick with the Rocket Schemetic Tier 4 on it.
#
#### What happend instead? (Attach screenshots if needed)
You need to detect a Schemetic Tier 3 on the Data Stick, wich isnt useful, you need the Tier 4 to craft the schemetic.

![2018-07-11_02 21 29](https://user-images.githubusercontent.com/29660362/42544359-8b03ef52-84b1-11e8-9822-570876e8829a.png)
![2018-07-11_02 24 41](https://user-images.githubusercontent.com/29660362/42544363-95b735c6-84b1-11e8-9bea-90ac7d8690ee.png)

#
#### What do you suggest instead/what changes do you propose?
Change the Quest that it uses the Data Stick with the right scemetic on it.

**Comment by Dream-Master** [comment]
duplicate. fix allready for 2.0.4.7

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/42650778-9c681f0e-860d-11e8-8058-af335f0c3760.png)
