### ISSUE TITLE
Addidional twerks (spelling errors)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#3297]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to read the super-mjolnir quest (number 1348).
I expected to not end up in a laughing fit.
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/17787093/42605786-c98bd292-8571-11e8-80ca-e0290de1a48b.png)
#
#### What do you suggest instead/what changes do you propose?
Additional tweaks
Mjolnir
Snowmen

**Comment by richardhendricks** [comment]
*twerks*

Seems legit. :dancing_men:

**Comment by Dream-Master** [comment]
@bartimaeusnek is this intended or spelling errors ?
