### ISSUE TITLE
Flew to Ceres - can't loot or break the landing balloon

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3300]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I flew to Ceres in T3 Rocket - landed in balloon but I can't break or loot the landing balloon to get my rocket back...
#
#### What happend instead? (Attach screenshots if needed)
I can see my rocket in the balloon but I can't loot it.   Edit: I was able to put spam hopper's underneath and it got pulled out thankfully!
#
#### What do you suggest instead/what changes do you propose?
Fix?

**Comment by alphaNOVAircraft** [comment]
Not sure what produces that bug, but for me it worked out just to ask another player to loot it for me, so its maybe releated clientsided, he could loot it without any problems.

**Comment by DualBallers** [comment]
Have you tried removing the blocks below the balloon?
Sometimes it seems to get stuck on a ledge and can't be accessed before it sits on a flat surface.

**Comment by Dream-Master** [comment]
@Highbeam we need more infos from you otherwise i close this issue.

**Comment by Highbeam** [comment]
Though this happened to __venom yesterday on Phobos.  I was able to put a vanilla hopper under the balloon to pull out the rocket.  Breaking the rock under the balloon didn't fix it but I'm personally happy with the workaround to place a hopper - not sure others will think of that but yea close this thanks

**Comment by Dream-Master** [comment]
Did we need to add this to the Quest Book (the info )? @Highbeam

**Comment by Highbeam** [comment]
That's a good idea - you can just put something with a tick / X advising that if the landing balloon can't be looted, to try put a vanilla hopper underneath.  It's worked twice for me now

**Comment by DoomSquirter** [comment]
can confirm, 4.6, same situation, hopper worked.
