### ISSUE TITLE
Inconel-625 no recipe

### ISSUE THREAD

**Issue by flockenobsidian** [GTNewHorizons/NewHorizons#3301]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I looked up the Maceration Stack controller from GT++, saw that i need inconel-625 frame box for it, couldnt find a recipe for it.

**Comment by alphaNOVAircraft** [comment]
Did you look up the dust?  You need to check for the fluid form of the alloy if it’s a gt++ one. It’s iirc made in the blast alloy smelter. So you will only be able to make the liquid form of it

**Comment by bartimaeusnek** [comment]
yupp, it’s made in the blast alloy smelter.
