### ISSUE TITLE
Fences are uncraftable with non vanilla wood planks

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3304]
#### Which modpack version are you using?
2.0.4.6

Biomes o plenty wood planks can not be used to craft fences.

![2018-07-13_22 08 54](https://user-images.githubusercontent.com/20565115/42720261-abafaa2c-86e9-11e8-8171-5bb2e93e9ec1.png)

**Comment by Dream-Master** [comment]
There are more then only vanilla fences. (Natura) Is there a willow wood fence ?

**Comment by Anarack** [comment]
There is a extra trees willow wood fence, but no fence for it added by biomes o plenty. No biomes o plenty wood plank has a fence variant added by the mod, but one that is close looks wise may exist with extra trees/forestry/natura that we could point that wood type at.
