### ISSUE TITLE
[Mod Suggestion] The Erebus (and Botania) Mod

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3306]
#### Why are you writing this issue ? 
I think that The Erebus should be added to GTNH.
#
#### Why do you think that mod should be added ?
It adds bit more of adventuring to GTNH and allows gating some other mods.
#
#### Is there anything else?
There are biome id conflicts and Mincraft crashes when erebus ids are higher than 127.
Sadly it's closed source, but since 1.7 is not continued we probably are allowed to modify it.
#
#### Links
Mod: https://minecraft.curseforge.com/projects/the-erebus
Required Changes : https://github.com/Zoko061602/TheErebus/commit/f7ae72e1ffb1505f5f967e7779465c7053eede95
#

**Comment by bartimaeusnek** [comment]
@Zoko061602 @draknyte1 Aren't biome IDs saved as a Byte and therefore cant be higher than 127 anyways?

**Comment by Zoko061602** [comment]
@bartimaeusnek Biomes are stored in an Array with a length of 256 and the ID is just the index of the corresponding biome.

**Comment by Dream-Master** [comment]
i remember we add that mod allready and not find a nice story for it. The Beatles and animals are nice.

**Comment by Zoko061602** [comment]
I know that this idea is a bit odd, but what about Botania?
I think it would work quite wel with the erebus, just some ideas:
- There are huge flowers in the erebus that consist out of petal blocks, I think these are just perfect for botania flowers.
- The soul cystrals that are dropped by the antlion overlord could be used to make the gaia ritual
- Living Rock and Stone could be made from Umberstone and Pertrified Wood

I think that might be a good way of gating Botania and giving the erebus an actual purpose.

**Comment by Dream-Master** [comment]
Yea but be need to rework Botania from scratch and need to gated it mabe inside Erbus in a intelliget way.

**Comment by Dream-Master** [comment]
Yea a Infernal and Special mobs variants of Erebus monsters.

**Comment by bartimaeusnek** [comment]
We could add the Erebus as a Lategame Dim (with lore, that for materials for the extreme tiny components you need to shrink yourself down and explore a new Dimension), and we could Gate Botania in a mixture of IC2 Crop-Breeding, different Dimenions, Witchery and Thaumcraft.

**Comment by Zoko061602** [comment]
I think it would make sense to split Botania and the Erebus into 5 tiers:
- HV Basic Erebus Exploration, like getting Jade and Beetle drops
- EV Botania start first Mana Stuff, like passive flowers
- IV Runes, active generating Flowers, requires Tarantual Boss
- LuV Alfheim, requires Antlion Boss
- ZPM Gaia Boss

**Comment by Anarack** [comment]
Thats nice, but remember its competing with endgame thaumcraft and blood magic toys at that point and you can complete all of that when you get a LuV blast furnace which is at IV basically... and at that point the entire mod and its mobs/bosses are trivial so it doesn't really add anything at that point.

**Comment by mitchej123** [comment]
I'm against adding any new mods that don't allow bug fixes & redistribution of modified versions (Erebus). 

There's a few things from Botania I miss, but I'm not really in favor of adding another Tech Mod (self admitted disguised as a magic mod).  I'd rather pull out the few nice things and add them to a smaller mod: horn of the wild for example.  Botania is great, but I've played it in every other kitchen sink mod and think we're fine without it here.  Plus, we'd have issue with retrogen of flowers and such, and lots of balancing with the other mods that would take a good long while and not sure that it's worth the effort.

**Comment by Dream-Master** [comment]
@mitchej123 i chat with vadis the mod dev (Erebus) rn to check the license thing.

**Comment by mitchej123** [comment]
If we can get a license to fix bugs and redistribute/support the 1.7.10 version with changes then I'm more with Erebus; it's new content I haven't played with before and (seems?) confined to a different dimension.

Still more on the pass side for Botania.

**Comment by Vernam** [comment]
I'm against adding both modes. Erebus does not fit the topic, Botania will not be needed at those stages where it should be put

**Comment by ZorbaHerbalist** [comment]
I'm on Botania. Properly nerfed and gated should be great complement of magic in GTNH.

**Comment by Dream-Master** [comment]
if i ever add it it will be nerfed first.

**Comment by ZorbaHerbalist** [comment]
@mitchej123 Retrogen is not necessary. We can and recipe for petals from i.e. sifting dirt

**Comment by Dream-Master** [comment]
Yes there will be non of the flowers in the overworld or any existing dim. If we ever add erebus or another dim for it we can add gen there if possible.

**Comment by Dream-Master** [comment]
Think we move this to GTn 3.0 and mc 1.12

**Comment by Dream-Master** [comment]
@Zoko061602 @bartimaeusnek @mitchej123 
oke when we add this eventually at 1.12 and not at 1.7 ?

**Comment by Dream-Master** [comment]
ok but we need to wait vadis pulled the code zoko send him

**Comment by Arturlang** [comment]
I think botania would be an awesome addition honestly.

**Comment by mitchej123** [comment]
Not likely to happen and discussion has gone stale.  Reopen if required.
