### ISSUE TITLE
Fluid Trashcan

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3307]
#### Which modpack version are you using?
Official Delta server Version
#
#### If in multiplayer; On which server does this happen? 
Delta Server
#
#### What did you try to do, and what did you expect to happen?
I placed a fluid trashcan and expected to input creosote into it
#
#### What happend instead? (Attach screenshots if needed)
I tried hooking up a regular steel fluidpipe to a extrautilities trashcan, to extract creosote from my ovens, and the trashcan just disappeared into thin air. Earlier today, the trashcan was working fine and still existing so I dont know what happened. I already tried to relog and place a block where it was but it is gone

#
#### What do you suggest instead/what changes do you propose?
For fluid trashcans not to consume themselves

**Comment by boubou19** [comment]
did you placed the trash after the pipes?maybe it was a partial rollback of the area?

**Comment by Dream-Master** [comment]
@WizardSleve280 ? We need more infos

**Comment by WizardSleve280** [comment]
Sorry i was busy with school work. The trashcan was on top of the pipe i was using to pump in the creosote, all in the same chunk. The trashcan was placed before the pipes and when the pipe was placed next to the trashcan, it just disappeared. No partial rollback since the trashcan was the only thing affected

**Comment by Dream-Master** [comment]
@WizardSleve280 can you put a pic here inside that i can retry your setup in sp game ?
