### ISSUE TITLE
Quest Book Progress Lost on Update

### ISSUE THREAD

**Issue by liveseaandsky** [GTNewHorizons/NewHorizons#3309]
#### Which modpack version are you using?
2.0.46
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
After updating the quest book has lost my progress. It still has the tiers but the quests themselves are not completed.
#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
I had this issue too some times. Be sure you are login in you mc account when you start your game.

**Comment by Dream-Master** [comment]
@liveseaandsky did it works when you be in online mode ?

**Comment by liveseaandsky** [comment]
I think that's probably it (Doh!), but haven't had access to my PC to check yet.

**Comment by Dream-Master** [comment]
@liveseaandsky let me know when you test it and when it works clode the issue. Thanks

**Comment by Dream-Master** [comment]
i close this now because i get not much more info @liveseaandsky .
