### ISSUE TITLE
Opencomputers OS

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#3310]
#### Which modpack version are you using?
2.0.4.6
#### If in multiplayer; On which server does this happen? 
Epsi
#### What did you try to do, and what did you expect to happen?
craft the OpenOS floppy disk

#### What happend instead? (Attach screenshots if needed)
i was unable to find recipe in NEI to craft that item

#### What do you suggest instead/what changes do you propose?
check out that recipe if it isn't missing or whatever

**Comment by Dream-Master** [comment]
will check
