### ISSUE TITLE
Basic Transport Pipe quest needs to be MV, not LV

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3311]
BTPs require 64 EU/t, needs to be moved to MV tier instead of LV.

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
lv recipes available

![image](https://user-images.githubusercontent.com/2970688/42736062-831b4a36-885f-11e8-8d24-79387490b815.png)

**Comment by Dream-Master** [comment]
assembler is mv but why you suggest pack it into mv ?
