### ISSUE TITLE
Various OpenOS items are uncraftable

### ISSUE THREAD

**Issue by flockenobsidian** [GTNewHorizons/NewHorizons#3312]
#### Which modpack version are you using?
2.0.2.6
#
#### What did you try to do, and what did you expect to happen?
EEPROM (Lua bios) and the Various Floppy disks with Programs on them are uncraftable (from Open Computers).

**Comment by Dream-Master** [comment]
various Items? I need a list to check it @flockenobsidian

**Comment by bartimaeusnek** [comment]
@Dream-Master

>  EEPROM (Lua bios) and the Various Floppy disks with Programs on them are uncraftable

I have checked that and EEPROM (Lua bios) and all Floppy disks with programs on them except for the securityOS one are uncraftable.

**Comment by Bryfer** [comment]
Are they meant to be crafted? I think you can find them in dungeons? (The programs)

**Comment by bartimaeusnek** [comment]
@Bryfer according to their wiki they need to be crafted.
