### ISSUE TITLE
Frequency module is uncraftable

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3314]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
1st part of 818th quest detected and comleted, but frequency module seems to be uncraftable
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/25793443/42738263-952e9aaa-8889-11e8-83a2-7fdc0616ed32.png)

#

**Comment by Dream-Master** [comment]
i need to check battery.

**Comment by Shyrff** [comment]
if it can affect id, galactice battery was crafted out of hull, extracted out of filled sodium lv battery

**Comment by alphaNOVAircraft** [comment]
try to use another kind of sensor, iiirc i could only craft it with a claimed sensor, not with a crafted one, maybe a wrong nbt tag?

**Comment by Highbeam** [comment]
Charge the battery to full first
