### ISSUE TITLE
Infernal Blast Furnace

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3315]
#### Which modpack version are you using?
2.0.4.6
I tried to use this oven for roasting tetrahedrite, but the oven only destroys it. Further, the remaining recipes were checked but the result is the same.
Check the operation of this multi-unit.

**Comment by CalterOK** [comment]
He checked the dust of tetrahedrite, also clusters of iron, gold, copper were tried.
Fur was installed, and the supply of viscose should only affect the melting rate?

**Comment by bartimaeusnek** [comment]
No you need a steady supply of LIQUID ESSENTIA. Place jars filled with Ignis Essentia asides of it.
