### ISSUE TITLE
Adjust durability for basic prospector?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3319]
Ok, I am finally advanced enough to make the basic prospector, and after some testing, I think the effective durability should be ~ doubled and the success rate increased.

I am targeting balancing around the vanadiumsteel prospector (easy to get once in LV with an EBF).  Some of the rare veins may require looking in over 100+ oreveins.  Based on my numbers, 10% of players might need to search over 200 oreveins to find a rare ore like Manganese if they are unlucky.

So I built and tested a Vanadiumsteel basic prospector.  It does 4x4 chunks, which means I can search essentially 4 oreveins at once (skip over 6 chunks, not 3!).  It lasted about 7 searches.  So it can give you info on ~28 oreveins.

I am thinking for rarer veins, we should expect players to make 3-4 of these at most.  So for 200 orecenters, each should search about 50.  So I am asking we double the effective durability of the scanners.  Should be easy to do by adjusting how much durability is damaged for each use.

**Comment by richardhendricks** [comment]
@bartimaeusnek What do you think?

**Comment by bartimaeusnek** [comment]
actually i think we should change them to always do 3x3 chunks, with switchable modes to 6x6 and 9x9, higher durability in lower tiers is essential if you want it to be better than the IFU Rod.

**Comment by richardhendricks** [comment]
I like the 4x4 or 5x5 myself.  That way you get info on 4 orecenters at a time.  I also like that it is "imperfect" info and that once you find something interesting you still need to dig a little.
