### ISSUE TITLE
NEW MODS

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#332]
Ich will add enhanced portals 3 and autopackager in the next update.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292751-enhancedportals-3

http://minecraft.curseforge.com/mc-mods/221457-autopackager

**Comment by Drobac** [comment]
+1

**Comment by Dream-Master** [comment]
Update today if Minetweaker woks.

**Comment by Dream-Master** [comment]
Minetweaker works

**Comment by Dream-Master** [comment]
Added in the next update.
