### ISSUE TITLE
General Quest Fixes/Typos

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3321]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
1: In the "Where can I put all these liquids" quest, the quest requires you to get clear glass in order to make obsidian glass. The problem with this is that the recipe is in fact thickened glass, not clear glass.

2: (My personal opinion) The beginning of the thaum questline should be barred (or a warning of some sort) until you get stainless steel/reach hv tier since in order to make a fusion altar and a gold capped wand, you need to have stainless steel screws as well as an hv chemical reactor, essentially making any progress until that point useless unless you want to grind out a lot of research.

3: In the LV questline, the thermal centrifuge's description states that it is an optional machine when in fact it is a required quest.

4: In the Stone Age questline, in the quests that go over how ores spawn, the first quest should have what "N" is actually equal to in order to make it easier for people to understand.

5: (My personal opinion) In the MV questline, in the extruder quest, both the small gear and rotor extruder shape should be added, since they are quintessential items for things such as pistons and pumps

6: In the MV questline, the "Transistor" quest should also have the "Molten Polyethylene" quest as a requirement, seeing as you need said molten plastic to make the transistors

7: (My personal opinion) This is more of a suggestion but instead of cramming the different ways to make power intermittently throughout lv, mv, etc. I would say to make a questing tab dedicated to generating power. This way you can be more in depth with the types and how to go about making each as well as helping with general organization of quests

**Comment by Shyrff** [comment]
5: (My personal opinion) In the MV questline, in the extruder quest, both the small gear and rotor extruder shape should be added, since they are quintessential items for things such as pistons and pumps

You should NEVER use extruder for making rotors, because it takes 5 ingots and fluid extracor+solidifier allows to craft 1 rotor out of 4.25 ingots!

**Comment by WizardSleve280** [comment]
Another issue that i found was in the mixing stainless steel quest, the quest asks for invar, when in fact it should be asking for nickel

**Comment by Dream-Master** [comment]
1 fixed

**Comment by Dream-Master** [comment]
2. try to explain a bit what i need to change @WizardSleve280

**Comment by Dream-Master** [comment]
3. fixed

**Comment by Dream-Master** [comment]
4. added

**Comment by Dream-Master** [comment]
6 fixed

**Comment by Dream-Master** [comment]
7. i will do later

**Comment by Dream-Master** [comment]
@WizardSleve280 dont see that stainless steel quest ask for invar. Maybe it was fixed before.

**Comment by WizardSleve280** [comment]
@Dream-Master i was mistaken in thinking that you could not use invar to make stainless steel, but that doesnt change the fact that there is still two quests for stainless steel. Very redundant. 
<img width="1280" alt="screen shot 2018-07-20 at 5 54 50 pm" src="https://user-images.githubusercontent.com/19292440/43026990-286625d0-8c46-11e8-9244-06eaff8e26fd.png">
<img width="1280" alt="screen shot 2018-07-20 at 5 54 56 pm" src="https://user-images.githubusercontent.com/19292440/43026992-2cf654bc-8c46-11e8-9e04-4da75b3f7b5f.png">
Also, in regards to the thaum barring, thaumcraft quests should not be unlocked until you get stainless steel, since in order to do basically anything in thaumcraft, you need stainless steel screws to make a decent wand. Otherwise you are stuck doing research.

**Comment by WizardSleve280** [comment]
Some other issues that i have found while playing @Dream-Master were that
1: In both "ways to get biomass"  quests, they mention that you need hv in order to use the pyrolace oven when in fact its lv thats needed
2: Many quests are unlocked in hv like the vacuum freezer, glowstone doped monocrystalline, and a distillation tower all require ev circuits so i would say barring at least those three quests behind the cleanroom since you need to make a cleanroom in order to make the ev circuits
3: In HV, the kinetic power quests require a dire crafting table, so I would say to lock that quest until you go complete it in the space race tab

**Comment by richardhendricks** [comment]
It is difficult enough for players to determine how to unlock a quest.  I would rather not tie quests so tightly to a bunch of prereqs, but explain in the quest (like the kinetics) that another thing must be completed.  Otherwise players don't even know they are missing something.

**Comment by richardhendricks** [comment]
1. Actually the pyro is an MV machine, even though the recipe is only LV.  It needs MV components for the controller. Updated.

2. Added notes to the respective quests "You will need to make EV circuits in a cleanroom to build this machine." and "You will need to cut these wafers in a cleanroom".

3. Note pointing to Space Race quests added already.
