### ISSUE TITLE
tumbaga and rose gold mixer

### ISSUE THREAD

**Issue by viljar290** [GTNewHorizons/NewHorizons#3323]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
official delta
#
#### What did you try to do, and what did you expect to happen?
tried to make rose gold in the mixer putting in the correct circuit gold dust and copper dust (full stack each)
#
#### What happend instead? (Attach screenshots if needed)
made tumbaga instead (recepie is gold dust and copper dust in mixer no circuit)
#
#### What do you suggest instead/what changes do you propose?
add a circuit requierment to tumbaga dust aswell to seperate the two as right now it will default to tumbaga unless too little materials to make it

**Comment by richardhendricks** [comment]
Tumbaga is a GT++ mixture, please file ticket at GT++ github 

https://github.com/draknyte1/GTplusplus/issues

**Comment by draknyte1** [comment]
![2018-07-18_03 33 42](https://user-images.githubusercontent.com/3060479/42835037-666cd3b8-8a3b-11e8-89a4-432a88bc56ca.png)
Issue has already been resolved since the update of GT++ GTNH is using.

**Comment by Dream-Master** [comment]
will check later

**Comment by Dream-Master** [comment]
Yes fixed
![image](https://user-images.githubusercontent.com/2970688/42839659-aecdf1d2-8a04-11e8-8779-715e5beb8b68.png)
