### ISSUE TITLE
Alviary mutation

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3325]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon and later in creative
#
#### What did you try to do, and what did you expect to happen?
Mutate arcane and dupernatural bees into etheral
#
#### What happend instead? (Attach screenshots if needed)
no mutation even tho using 7 mutators with eye of ender.
#
#### What do you suggest instead/what changes do you propose?
found this https://github.com/GTNewHorizons/NewHorizons/issues/2952 so i though lets try in creative with frames. but no more luck, if the alveary is locked at 15 % it totaly neglects the use of the alveary for mutation purpouses, it is then much better to use a ordinary apiary and the alviary can only be used for production. i sugest increasing the 15% to what you can achieve in a apiary cap and stating it in the NEI block desrciption.

**Comment by Dream-Master** [comment]
Seems to be a limitation of the alveary. Need ofrestry code changes.

**Comment by Ghengis88** [comment]
needs change in NEI

**Comment by Ghengis88** [comment]
GT++ Frames is not working in Alviary
