### ISSUE TITLE
[Molecular Transformer] recipes.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#333]
Any Ideas or suggestion which recipes we can add to the molecular transformer?
I can't make this machine more useful.
You need now the QED Table to craft it.

**Comment by Namikon** [comment]
Well, the MT is meant to transform less valuable materials into more rare ones. Kind of a technical way to equal-exchange stuff. 

You could remove the laser engraver recipes to make flawless and exquisite gems and add them to the MT. But I can't think of anything that's really useful besides that

**Comment by Drobac** [comment]
Could we also do some simple recipes that make life easier, like dirt into clay or even wither skulls into nether stars but needing tons of power. There are few interesting recipes on http://ftbwiki.org/Molecular_Transformer

**Comment by Drobac** [comment]
Things like redstone into rubies might actually be neccesary when you come to the IV tier since you need so many lapatron crystals for circuits and what not.. Some would be for convenience sake like nether quartz into certus quartz

**Comment by Namikon** [comment]
Most of those recipes come vanilla with the MT, but they are removed for some reason in this pack. Maybe Martin can check that again and re-enable some :)

**Comment by Dream-Master** [comment]
Yes i remove most of the recipes because i thought it is to op.

Any suggestions and how many eu it have to cost here.

**Comment by Dream-Master** [comment]
- [ ] Redstone to ruby dust (EU?)

**Comment by Dream-Master** [comment]
minecraft:glowstone_dust:1; AdvancedSolarPanel:asp_crafting_items-9:1; 10000000
minecraft:redstone:1; oredict:dustRuby:1; 5000000
oredict:dustNetherQuartz:1; oredict:dustCertusQuartz:1; 500000
oredict:dustCertusQuartz:1; oredict:dustNetherQuartz:1; 500000
oredict:dustTin:1; oredict:dustSilver:1; 5000000
oredict:dustSilver:1; oredict:dustGold:1; 10000000
oredict:dustGold:1; oredict:dustPlatinum:1; 20000000

**Comment by Drobac** [comment]
Could we get a Red Garnet Dust into Yellow Garnet dust recipe

**Comment by Dream-Master** [comment]
Sure why not. Than i will add yellow garnet to red garnet too
