### ISSUE TITLE
[RFC] Things that need to be done in GTNH 2.0 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3330]
[RFC] Things that need to be done in GTNH 2.0 to finalize the pack.

**Comment by lexx1191** [comment]
close all bugs?

**Comment by Zoko061602** [comment]
ThaumicHorizons and Automagy

**Comment by Dream-Master** [comment]
@Zoko061602 nerfs?

**Comment by Zoko061602** [comment]
yes

**Comment by Cinobi** [comment]
rework endtier recipes(noone will craft stargate or draconic evol teleporter), make assline recipes great again(take 1-year old build and look at recipes in it), greatly reduce cooling time for everything(not so nessesary, buttt...) rework bloodmagic(too complicater for it's benefits), reduse the amount of planets(a) if it's possible, b) heey, 1-2 planets for each tier except the 8 is enough - all the planets is the same rock deserts, afterall)

**Comment by Logicus123** [comment]
Please fix industrial centrifuge and industrial eletrolyzer if it isnt already fixed

**Comment by Logicus123** [comment]
ok thanks

**Comment by richardhendricks** [comment]
This is not about bugs, this is about general high level stuff that needs completion.

**Comment by Zoko061602** [comment]
Maybe adding the angel ring

**Comment by 0lafe** [comment]
Circuits for higher tiers are kind of wonky

A big thing I'd think is finish the quest book. Give quests for LuV+ stuff, thaum probably needs more, BM too, witchery for sure, other stuff too.

**Comment by NeroOneTrueKing** [comment]
The AE2 quests could be improved.

The Meteorite Compass quest says in the description that it is optional, but without it the quests for storage aren't available. The quest to make a variety of terminals includes an interface terminal, which needs an interface to craft, which you are asked to make several quests later. There are probably other things that could be changed to make that tab of the questbook more like a Beginner's Guide to AE2.

**Comment by damug** [comment]
A number of the witchery recipes look like they haven't been gregified as well.

**Comment by Dream-Master** [comment]
yea I am on it.

**Comment by Prewf** [comment]
>reduse the amount of planets(a) if it's possible, b) heey, 1-2 planets for each tier except the 8 is enough - all the planets is the same rock deserts, afterall)

I actually like that there's so many planets, mainly because some planets have a unique combination of ores/density for those ores. So for example, if I need only Galena and lots of it, I'll probably head to the moon because I find so much there. But if I want *some* Galena, but also Tungsten and Platinum, I can go to Ganymede because it has that unique combination.

Maybe it doesn't matter for end game because of the deep dark? For where I am right now though, I thought it was nice how each planet offers something the others don't in terms of ores.
