### ISSUE TITLE
Ore Dictionary Export bus does not export all items of same type

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3331]
#### Which modpack version are you using?
2.0.4.6
#### What did you try to do, and what did you expect to happen?
I am trying to export all tiny dust from my AE system (to a chest buffer -> packager) using an ore dictionary export bus using the string "dustTiny*". All items are stored on ME drives.
#### What happend instead? (Attach screenshots if needed)
Most of my different types tiny dusts a not being exported?

String used
![image](https://user-images.githubusercontent.com/30087707/42901838-fa5e0722-8acc-11e8-8e4e-6e1e73608b62.png)
Ores that are exported fine
![image](https://user-images.githubusercontent.com/30087707/42901803-e921f662-8acc-11e8-8b07-b33c3bbdd50d.png)
Ores that are not exported
![image](https://user-images.githubusercontent.com/30087707/42901894-1a6d34f2-8acd-11e8-908f-e95307d3b5cb.png)

What is happening here?
My 31K pile of tiny pyrite dust will only be exported if I use a longer string e.g. "dustTinyPy*". 
I have another dictionary bus with the string "crushedCentri*" that happily takes all centrifuged ore, so why is it different for tiny piles?

**Comment by bartimaeusnek** [comment]
fixed in 2.0.4.7

**Comment by bartimaeusnek** [comment]
for now remove every recipe in your me that generates a "dustTiny*" if you want to use it

**Comment by DualBallers** [comment]
OK great, I did wonder if it was connected to this issue :-)
https://github.com/ExtraCells/ExtraCells2/issues/398

**Comment by bartimaeusnek** [comment]
@DualBallers yes that is exactly the issure. its fixed in 2.0.4.7
