### ISSUE TITLE
Reconfigure HV Macerator quest requirements to MV macerator quest

### ISSUE THREAD

**Issue by Sudoloo** [GTNewHorizons/NewHorizons#3334]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
all
#

#
#### What do you suggest instead/what changes do you propose?

i was doing some peaking at the quest book trying to figure out why i wasnt unlocking the HV macerator quest to see that it has its requirement listed as MV Good Miner instead of MV Macerator, or as one user suggested, none at all (due to its near mandatory status in progression), i advocate for mandating the MV macerator quest instead personally.

**Comment by Dream-Master** [comment]
yea was a mistake.
