### ISSUE TITLE
double compressed ignis solar panel got a larger buffer

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3335]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
i was testing double compressed solars from electro magic tools. Expected to see the internal buffer of the double compressed ignis solar panel to be at 100k eu of capacity
#
#### What happend instead? (Attach screenshots if needed)
it's at 1000k
![image](https://user-images.githubusercontent.com/12850933/42999621-bf13a732-8c1e-11e8-8c26-329018e56644.png)

#
#### What do you suggest instead/what changes do you propose?
fix it :)

**Comment by Dream-Master** [comment]
ok
