### ISSUE TITLE
Compressed obsidian macerating mistake? 9 obsidian gives 64 dust

### ISSUE THREAD

**Issue by LaM0x** [GTNewHorizons/NewHorizons#3338]
#### Which modpack version are you using?

#2.0.4.6
#### If in multiplayer; On which server does this happen? 

#dig to build
#### What did you try to do, and what did you expect to happen?

#the recipe for compressed obsidan 9obsidian in the craft table, if you macerate the compressed obsidian it gives 64 obsidian dust, if you were to macerate normal obsidian it gives only 1 dust per block
#### What do you suggest instead/what changes do you propose?
is the recipe intended? if not reduce the dust you get

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
@LaM0x can you send me a pic please.

**Comment by ko5h** [comment]
![](https://i.imgur.com/Q6qxBIf.png) @Dream-Master

**Comment by Dream-Master** [comment]
This recipe i cant see anymore. Maybe GT++ fix it.
@draknyte1
