### ISSUE TITLE
osmium queen

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3339]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
I was looking through ways to get osmium and find out that there are 2  types of osmium queens
![image](https://user-images.githubusercontent.com/25793443/43023207-b2d885d8-8c72-11e8-9f8a-72bb1a6be207.png)
The 1st one is extremely chip and OP. It is very esay to breed and produce osmium nuggets(not 8k eu/t centifugeble combs).
![image](https://user-images.githubusercontent.com/25793443/43023202-abff2104-8c72-11e8-9934-236b7e459f3b.png)
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
1st bee should be  disabled or is it just NEI showing disabled reciepe?

**Comment by Dream-Master** [comment]
@Shyrff can you check if you enable bees in gt config ? If yes disable it.

**Comment by Dream-Master** [comment]
Yes this isnt a bee i add. IDK if this is Magic bees or some other mod add it.

**Comment by Dream-Master** [comment]
https://github.com/MagicBees/MagicBees/blob/130b7c683691135295a900c89cf702289c10437f/src/main/java/magicbees/bees/BeeProductHelper.java#L229

**Comment by Dream-Master** [comment]
another fork of a mod :/

**Comment by MineAnPlay** [comment]
For now you can blacklist it via config\forestry\apiculture.cfg

**Comment by Dream-Master** [comment]
@MineAnPlay what i need to write in ?

``
species {
    # Add species to blacklist identified by their uid, one per line. [default: ]
    S:blacklist <
     >
}``

**Comment by Dream-Master** [comment]
``<Forestry:beeQueenGE>.withTag({MaxH: 60, Mate: {Chromosomes: [{UID1: "magicbees.speciesOsmium", UID0: "magicbees.speciesOsmium", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanLonger", UID0: "forestry.lifespanLonger", Slot: 2 as byte}, {UID1: "forestry.fertilityLow", UID0: "forestry.fertilityLow", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}, Health: 60, IsAnalyzed: 1 as byte, Genome: {Chromosomes: [{UID1: "magicbees.speciesOsmium", UID0: "magicbees.speciesOsmium", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanLonger", UID0: "forestry.lifespanLonger", Slot: 2 as byte}, {UID1: "forestry.fertilityLow", UID0: "forestry.fertilityLow", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolTrue", UID0: "forestry.boolTrue", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlowest", UID0: "forestry.floweringSlowest", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})``

This isthe mt hand data of the bee

**Comment by Dream-Master** [comment]
disabled for now. Need to be tested
