### ISSUE TITLE
Metabolic frame

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3341]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsion
#
#### What did you try to do, and what did you expect to happen?
reserched the metabolic frame and started reading the text, and expectd to understand what it was saying
#
#### What happend instead? (Attach screenshots if needed)
https://cdn.discordapp.com/attachments/234936569360809996/469961342493655060/unknown.png
Aura? i hve done Taumcraft 4 up to kami and never run in to this before. is it wrong or am i still a noob?
#### What do you suggest instead/what changes do you propose?
if this is wrong then the text should be changed

**Comment by Dream-Master** [comment]
i cant find any text to it. Need to ask somone can look in code and explain it.

**Comment by MineAnPlay** [comment]
It has 130 durability, 1.8x Mutation and 1.2x Production multiplier. Nothing else that is special.

**Comment by Dream-Master** [comment]
ok i change it and remove wront text part

**Comment by Dream-Master** [comment]
ok fixed
