### ISSUE TITLE
Universal Fluid Cells Wont Empty

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3342]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
To complete the Iron III Chloride quest, the quest says to store the fluid in universal fluid cells (which is the only quest that does that btw) so naturally I filled up six cells and completed the quest
#
#### What happend instead? (Attach screenshots if needed)
When i tried to empty the cells back into the tank, all the cells would empty until there was one left in the stack. The last cell would refuse to empty into the tank. Even when there are two separate stacks, the last item in both of the stacks refuses to empty

**Comment by draknyte1** [comment]
What are you emptying them into?

**Comment by richardhendricks** [comment]
It's a known bug with IC2 universal cells.  It's closed source so hard to fix AFAIK.

**Comment by Dream-Master** [comment]
will add iron3chloride as material to fix it.

**Comment by Dream-Master** [comment]
Will add gt cells to quest
