### ISSUE TITLE
[Quest #1299] Cant detect Dense energy cell

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/NewHorizons#3344]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Want to detect the dens energy for the Quest 1299
#
#### What happend instead? (Attach screenshots if needed)
Cant submit it
#
#### What do you suggest instead/what changes do you propose?
Mabye an wrong nbt tag so you cant detect the energy cell. Check it out and fix it

![2018-07-21_14 54 32](https://user-images.githubusercontent.com/29660362/43035856-9a240c18-8cf6-11e8-8187-a654472d1b30.png)
![2018-07-21_14 54 39](https://user-images.githubusercontent.com/29660362/43035862-bf149af6-8cf6-11e8-8698-9aa12d4c6a20.png)

**Comment by Highbeam** [comment]
I've got the same problem

Item ID is also 426 and screenshots already above

**Comment by Dream-Master** [comment]
I fix it in next release. nbt get to be ignored in the future.
