### ISSUE TITLE
Jade should be added to the Twilight Forest.

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/NewHorizons#3345]
Jade is required by the Jade Moon Dial, which is a very helpful tool that will display the current moon phase. Right now Jade can only be found in Draconium Veins which requires a Tier 2 Rocket. IMO the Jade Moon Dial should be available earlier on then that. My proposal is to add Small Jade Ores to the Twilight Forest. The current Twilight Forest Small Gem Ores are found between 5-250 and the amount is set to 2.

**Comment by Dream-Master** [comment]
Yea why not.

**Comment by MineAnPlay** [comment]
ID of Jade is 537.
