### ISSUE TITLE
Regular Coke Oven Bricks

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3346]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I think that you should be able to macerate the regular coke oven blocks/bricks into dust so you can centrifuge the dust into quartz sand and clay dust since otherwise, you can only get bricks back which are basically useless unless you are making an advanced coke oven.

**Comment by Dream-Master** [comment]
Coke oven bricks and advanced now recycle able. I add dust for both.
