### ISSUE TITLE
non gendustry bees are op

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/NewHorizons#3347]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
local server
#
Yesterday I've written about op osmium bees. After I've make some more investigation and here is list of ops. In my opinion
1 Invincible's bee spec is tungsten comb from extra bees, that can be processed in LV centrifuge, need to be changed to gendustry comb variant
2 radioactive combs are about the little easier to get than uranium combs and should be moved to 2k centrifuge
and more and more. all non-gendustry ore-like or ingot-like bees are MUCH easier to breed (no block/biom requirements, so they can be breeded in LV), their combs can be processed in LV, and one can get access to mid-latemid game materials like uranium, titan, tungsten without rockets (for gendustry variant one need block of material to breed so planet should be visit at least once).
My opinion on bees: this op non-gendustry species should be nerfed(replace combs/add block to breed)/reworked to gendustry style/disabled if they are not needed for future important mutations.
On the other hand for bees to be valuable, gendustry combs should be more reach with materials (increase material drop/materials droprate?) - they are hard to get anyway.

**Comment by Dream-Master** [comment]
i can disable them until i can go deeper into code.

**Comment by Shyrff** [comment]
more research need to be done, they caould be crucial for some other non-op bees

**Comment by Anarack** [comment]
They should be disabled, but you know the invincible bees take not including processing time and before bonuses takes 3 hours per tungesten dust per bee...

**Comment by Shyrff** [comment]
tomorrow I'll check if there are more crazy bees and will add some here if i'll find

**Comment by MineAnPlay** [comment]
Those bees, other then not requiring a foundation, aren't actually OP. They produce the corresponding materials slower then the custom bees.

**Comment by MineAnPlay** [comment]
Magic Bees is Open Source and everyone is allowed to modify it, but the same can't be said to Extra Bees. We can fix the Magic Bees related stuff but not sure with Extra Bees.

**Comment by MineAnPlay** [comment]
It's open source but doesn't allow modifying the code.

**Comment by Dream-Master** [comment]
Extra Bees or Magic Bees ?

**Comment by bartimaeusnek** [comment]
@MineAnPlay its LGPL so sure it does allow modifying the code...

**Comment by MineAnPlay** [comment]
Well then, I didn't read it properly. Well that makes things easier :D.

**Comment by Ghengis88** [comment]
What bees are you disabeling? only Invincible's, osmium and radioactive or all non gendustry?, whar do you draw the line?

**Comment by MineAnPlay** [comment]
Osmium, Impregnable, Invincible and Radioactive.

**Comment by Dream-Master** [comment]
impregnable?

**Comment by MineAnPlay** [comment]
Impregnable = Titanium
Invincible = Tungsten 
Radioactive = Uranium

**Comment by Dream-Master** [comment]
ok was this the name for titanium? thanks
