### ISSUE TITLE
[suguestion] Make purification talisman able to remove pollution effects too

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3349]
If you can make this, that will be great

**Comment by Dream-Master** [comment]
We have enough things to remove pollution. GT Core mod has a airfilter and GT++ have some devices too. The talisman is only for magic.

**Comment by Methes** [comment]
Pollution EFFECTS not pollution itself.

**Comment by Dream-Master** [comment]
if somone code it maybe.

**Comment by barsikus007** [comment]
bcs nano and quantium armor works like hazmat suit

**Comment by barsikus007** [comment]
add to each good armor this ability will be more difficult than adding this trait to one item

**Comment by noobyaran9** [comment]
If you’re referring to the talisman from warp theory, then no.

The talisman of remedium from thaumic tinkerer removes all effects from player but not instantly(including radiation).

**Comment by richardhendricks** [comment]
If you are in a high pollution chunk the effects will constantly be reapplied, potentially draining amulets that remove the effect.

If we do add "negate pollution effect" we should probably do it on the GT side when pollution is applied. Wouldn't work for effects from ic2, which is probably OK. Gandalf shouldn't be traipsing around with irradiated uranium rods lol.
