### ISSUE TITLE
cleanroom not working in LV

### ISSUE THREAD

**Issue by Sudoloo** [GTNewHorizons/NewHorizons#3355]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
rastaman island 
#
#### What did you try to do, and what did you expect to happen?
i attached at one time an LV motor, and at another time a battery buffer offering 1 amp, the cleanroom didnt run despite being
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/4110158/43101973-cdb94ea6-8e97-11e8-867e-6b64f01f1cdd.png)

![image](https://user-images.githubusercontent.com/4110158/43102023-f4f512b6-8e97-11e8-9b15-474b033b454a.png)

![image](https://user-images.githubusercontent.com/4110158/43102044-0d3b5042-8e98-11e8-9de1-7b843ec44679.png)

#
#### What do you suggest instead/what changes do you propose?
i was informed that at 4 eu/t, it should be viable at ULV, but as is it refuses to run at even LV, really i dont care if it takes lv or mv, mv being something ive been told has worked for some others, i just want it listed at the bare minimum.

**Comment by Dream-Master** [comment]
yea mv is needed but not ask me why

**Comment by sthegreat** [comment]
I did some creative-mode testing using the debug scanner, and it seems the cleanroom actually is consuming 40eu/t for some reason instead of the 4eu/t it reports (i tested it by spamming the scanner, which seems to work every 4 ticks when right mouse is held)

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_Cleanroom.java#L51

Source is definitely set to 4, not sure where the extra 10x is coming from.

**Comment by richardhendricks** [comment]
Maybe related to cleanroom efficiency not starting at 100%?

**Comment by Dream-Master** [comment]
change tooltipto use 40 eu for make it clean. use 4 eu to hold is clean is fine also.

**Comment by MineAnPlay** [comment]
Wait, are you sure you aren't confusing maintenance efficiency with cleanroom efficiency? If not then it should just be set to always 4 EU/t IMO

**Comment by richardhendricks** [comment]
There's only the one efficiency as far as the code is concerned.  I say change the tooltip to 40 EU/t, 4 EU/t at max efficiency.

**Comment by Sudoloo** [comment]
i lack the know how to test it, but i wonder if it going from 4 to 3 would solve the problem. if its going x10 for no reason, may aswell see if it still goes x10 if you change the value

**Comment by richardhendricks** [comment]
That is another option, lowering the EU/t to 3 or 2 would allow an LV generator to power it.  A ULV generator/hatch would not be enough though.

Personally, I am ok with it requiring an MV hatch - it's an MV tier machine anyways.

**Comment by sthegreat** [comment]
The LV energy hatch accepts 2 amps right? So as it is now, you could still run it with an LV hatch if you wanted, you would just have to start it up using 2 LV generators, and break one after the efficiency goes up a bit.

**Comment by richardhendricks** [comment]
Trying to explain that in a quest would be kinda silly.  Also, what about the fuel in the generator?  Just easier to tell new players to use an MV hatch/gen.

**Comment by sthegreat** [comment]
That's true. And it is almost pointless anyways since the power use is the same regardless of the energy hatch used.

**Comment by Anarack** [comment]
Make sure to update the clean rooms tool tip, right now it says it can use a ulv hatch... that will solve a lot of issues right there.

**Comment by Dream-Master** [comment]
using min mv hatch in the tool tip would be enough

**Comment by MineAnPlay** [comment]
I run my cleanroom with a 4x battery buffer and it works with a LV Hatch, instead just change the tooltip and add that the power requirement is 4/(Efficiency%) EU/t.

**Comment by Highbeam** [comment]
Bit late into this conversation but I was able to run an LV cleanroom with 2 LV steam turbines -> 1 LV Energy Hatch

**Comment by Dream-Master** [comment]
@Highbeam how that? I thaought it need 40 EU/T not 2 Amp?

**Comment by Dream-Master** [comment]
@Sudoloo @sthegreat @richardhendricks @MineAnPlay @Anarack 
Did we need to add a Tooltip and what i have to written inside it?

**Comment by richardhendricks** [comment]
I like this explanation better

1x LV or 1xMV Energy Hatch, 1x Maintainance Hatch
Consumes 40 EU/t when first turned on and 4 EU/t once at 100% efficiency
An energy hatch accepts up to 2A, so you can use 2LV energy sources or 1 MV energy source
Make sure your Energy Hatch matches!

**Comment by richardhendricks** [comment]
Final tooltip

				"1x LV or 1x MV Energy Hatch, 1x Maintainance Hatch",
                "Up to 10 Machine Hull Item & Energy transfer through walls",
                "Remaining Blocks: Plascrete, 20 min",
				"Consumes 40 EU/t when first turned on and 4 EU/t once at 100% efficiency",
				"An energy hatch accepts up to 2A, so you can use 2A LV or 1A MV",
				"2 LV batteries + 1 LV generator or 1 MV generator",
				"Make sure your Energy Hatch matches!"};

**Comment by Dream-Master** [comment]
ok will add later
