### ISSUE TITLE
reduntant quest pre-requisites, smd component, central processor, advanced circuit assembler

### ISSUE THREAD

**Issue by Sudoloo** [GTNewHorizons/NewHorizons#3356]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
rastaman island bruda
#
#### What do you suggest instead/what changes do you propose?
the tier 3 quest to make smd components requires an advanced circuit assembler to be crafted for its completion, the teir 4 quest central processor requires that quest to be completed to appear. the quest directly after cpu is to acquire an advanced circuit assembler.  i suggest simply removing the advanced assembler requirement of the smd component quest as the machine doesnt facilitate the crafting of the component pieces.

![image](https://user-images.githubusercontent.com/4110158/43111421-30ed3e20-8ebf-11e8-8713-f9387fbb0a9b.png)
![image](https://user-images.githubusercontent.com/4110158/43111431-3bfb4bcc-8ebf-11e8-9d36-5f85fdba51e0.png)
![image](https://user-images.githubusercontent.com/4110158/43111440-489b179a-8ebf-11e8-865d-399314805d4a.png)

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
I remove smd components from CPU because it wont be needed.
I can make a extra Quest fro assembler mv if needed.
