### ISSUE TITLE
Turbine Maintenance

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3363]
#### Which modpack version are you using?
2.0.4.6

Turbines can not use the needs maintenance cover due to it not pushing redstone power through turbine casings. 

This prevents the ability to read turbine durability states with this cover and other maintenance issues.

Suggestion
 Make it so the needs maintenance cover powers the turbine casing/block next to it and change the needs maintenance cover output when turbine is below say 10-30% durability left, which is needed as the cover only looks if the turbine has less than 170 durability, this is not a good threshold as any turbine producing more than 850 eu/t can miss this threshold and not trigger the cover.

**Comment by ruSauron** [comment]
You can use wireless redstone cover late game

**Comment by Anarack** [comment]
No you can't, they can not be placed on turbine casings.
