### ISSUE TITLE
RC boiler seems to lose all store steam upon chunk reload

### ISSUE THREAD

**Issue by OrganicCookies** [GTNewHorizons/NewHorizons#3364]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I went /back to continue mining, and I did not touch my RC boiler
#
#### What happend instead? (Attach screenshots if needed)
When I came back, the RC boiler has no steam left(the water/fuel/temperature are still there)
#
#### What do you suggest instead/what changes do you propose?
Please fix it or suggest a way around

**Comment by Dream-Master** [comment]
did you boiler in one chunk or build over a chunk boarder

**Comment by OrganicCookies** [comment]
It is one chunk. We know to design bases according to chunks :P
Also it doesn't happen *every time* the i teleport out, but it is often enough that it causes a problem.

**Comment by Dream-Master** [comment]
in the next version personal chunkloader available at lv. maybe loaded the chunk permanent will work. Railcraft isn't open source (a few parts are missing)so I can't build custom builds.

**Comment by OrganicCookies** [comment]
Alright thx

**Comment by draknyte1** [comment]
Railcraft Multis seem to randomly deform all the time lately. (Past 6mo)

I wonder what's increased this happening? As several thousand hours using RC multis outside GTNH has never had this occur for me, it's curious.

**Comment by richardhendricks** [comment]
Does the RC boiler not store state like the tanks?  If you do not move/remove the bottom center block, you can reform a tank OK.

**Comment by OrganicCookies** [comment]
Well basically what I am seeing when i command back is that the boiler itself has disintegrated into small ones(the smallest 1x1 boiler probably don't have this problem) and takes seconds to form back.
