### ISSUE TITLE
type filters make huge cpu load

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3367]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i use some UV type filters to make differents filters in my base for diverse things. Expected nothing to go wrong
#
#### What happend instead? (Attach screenshots if needed)
Namikon said those filters are making heavy cpu load time in looking for oredictionnary entries
(16 s on a period of 107s observing time)
#
#### What do you suggest instead/what changes do you propose?
look at it pls it could save delta's tps when i'm online

**Comment by draknyte1** [comment]
You realise that their is only so much we can do because of how the thing works. It literally has to iterate the entire OreDictionary...

There's good reason no other mod has A decently working ore dictionary filter.

**Comment by boubou19** [comment]
So what about restricting the iteration to an OreDictionnary entry? like if you iterate to oreCopper it will only have to iterate on all the ores. Is it possible?

**Comment by bartimaeusnek** [comment]
Well theoretically you could run the whole iteration once and save the stuff that should pass thou in a seperate list, then you could iterate over that smaller list much quicker...

**Comment by draknyte1** [comment]
I'm sure @RichardHendricks and I can optimise the living hell out of it. 

I haven't even looked at the code. Was just stating that there is a limit to improving things that do iterations over big lists.

**Comment by draknyte1** [comment]
Got metrics for after the fix? I'm curious.

**Comment by richardhendricks** [comment]
Sure.

test setup for worst-case
![2018-08-24_01 39 00](https://user-images.githubusercontent.com/1214811/44569599-8ff8e880-a740-11e8-9977-21489b3f4cff.png)

no fix result
![2018-08-24_01 39 11](https://user-images.githubusercontent.com/1214811/44569608-97b88d00-a740-11e8-920d-ba73561375e3.png)


fix result
![2018-08-24_01 51 47](https://user-images.githubusercontent.com/1214811/44569650-b74fb580-a740-11e8-941a-127119031fbd.png)

test setup for best case
![2018-08-24_01 39 43](https://user-images.githubusercontent.com/1214811/44569618-a010c800-a740-11e8-9221-7f2709118037.png)

no fix result
![2018-08-24_01 39 49](https://user-images.githubusercontent.com/1214811/44569635-ab63f380-a740-11e8-8d7d-c5aebc615f76.png)

fix result
![2018-08-24_01 51 08](https://user-images.githubusercontent.com/1214811/44569657-bdde2d00-a740-11e8-8180-bfafb6f7996e.png)

**Comment by richardhendricks** [comment]
So ~10x speed improvement with the fix. Now this is with a full compressed chest, I imagine depending on how pathological you got, you could make it even worse, ie bring it multiple lines into the same filter, etc.

With a completely full chest and the wrong type selected, the load was really bad, 

No fix, wrong type selected against full chest
![2018-08-23_21 43 18](https://user-images.githubusercontent.com/1214811/44569853-55dc1680-a741-11e8-85af-84e02c6a7926.png)


Fix, wrong type selected
![2018-08-23_21 56 22](https://user-images.githubusercontent.com/1214811/44569874-62f90580-a741-11e8-9994-f743ea96bbc1.png)


So if a processing system had one side backed up, where the source was full of stuff the other typefilters could not accept, it could get really bad.  Fix is way better in this case, 50x.

**Comment by draknyte1** [comment]
Gotta remember you haven't filled the caches for each type. I could possibly pre-populate them during load for maximum optimisation. 

Leave it with me and I'll get to it tomorrow.

**Comment by richardhendricks** [comment]
I am not sure what you mean about "haven't filled the caches for each type"?  This is a few minutes after starting, and any cache entry would be populated with the first stack anyways.  The perf is way better than what we had before.

I don't think filling the caches with every type is really necessary right off the bat.  I think it makes more sense to do it as-needed dynamically.  Paying a small penalty (worst case having to expand the HashMap) when using a new stack is hardly expensive - after all it's not like that's going to happen with a full compressed chest anyways.

**Comment by richardhendricks** [comment]
OBJ map variant fix

worst case (last 5 matches)
![2018-08-26_00 10 16](https://user-images.githubusercontent.com/1214811/44625059-c7909d80-a8c4-11e8-8d41-cdb0999b8ee5.png)

best case(first 5 matches)
![2018-08-26_00 11 09](https://user-images.githubusercontent.com/1214811/44625060-da0ad700-a8c4-11e8-94ee-4c4ba6819833.png)


Full input (no matches)
![2018-08-26_00 08 14](https://user-images.githubusercontent.com/1214811/44625054-a92aa200-a8c4-11e8-9854-97f821e52c57.png)

**Comment by richardhendricks** [comment]
Linked hash map fix

Worst case
![2018-08-26_00 24 45](https://user-images.githubusercontent.com/1214811/44625117-e42dd500-a8c6-11e8-9ba2-a1270d8b2267.png)

Best case
![2018-08-26_00 25 46](https://user-images.githubusercontent.com/1214811/44625119-eb54e300-a8c6-11e8-8f11-0e85447c04b1.png)

full input
![2018-08-26_00 26 36](https://user-images.githubusercontent.com/1214811/44625120-f445b480-a8c6-11e8-95cb-2ff53d394b28.png)

**Comment by draknyte1** [comment]
Well, the Custom Map looks to be the best, but the LinkedMap isn't far behind.
Your call there~

But hey, Told you I could improve it! :D

**Comment by richardhendricks** [comment]
I mathed a thing!  7 samples each

Average | LinkedHM | ObjMap | HashHashmap(old fix)
---------|-------------|-----------|---------
Full Inv  |   96.7 us    |     67 us   |    62.7 us
1st 5     |     21 us     |      23 us  |       25.7 us

**Comment by richardhendricks** [comment]
Alkalus final fix merged into experimental.  Went with Objmap solution since it is best average overall.
