### ISSUE TITLE
Thaumonomicum text error reported on FTB site

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3368]
In Thaumonomicon, the description of Golem core: Butcher corresponds to Golem core: Decanting.

![image](https://user-images.githubusercontent.com/2970688/43367321-61372b50-934b-11e8-9ac9-2f82405d4776.png)

**Comment by Ethryan** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/3ca3a0f992fc252852dd1f885cb4a122944dff53/scripts/Thaumcraft-05-Golemancy.zs#L316
Should be "tc.research_page.COREBUTCHER.1"
