### ISSUE TITLE
Glowstone dust from biome's plants is unusable (has meta 32767)

### ISSUE THREAD

**Issue by NoLoginFound** [GTNewHorizons/NewHorizons#3370]
#### Which modpack version are you using?
2.0.4.6

#### What did you try to do, and what did you expect to happen?
Craft glowstone dust from glowing corals (BOP)

Expected result:
Regular glowstone dust

Actual result:
Glowstone dust with meta 32767. This glowstone dust is not usable in any recipe.

As far as google search says, 32767 is a OreDictionary.WILDCARD_VALUE, used in recipe input to indicate that any meta is accepted as input. Probably it was copied to recipe output by mistake from some other recipe input.

I guess this is a direct consequence of new lines in commit https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/7c68fd5ed1e03f133488b82ad27bc4beabaaba13 for issue #2473:

+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("BiomesOPlenty", "flowers", 2L, 3), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);
+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("BiomesOPlenty", "mushrooms", 2L, 3), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);
+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("BiomesOPlenty", "coral1", 2L, 15), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);
+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("Natura", "Glowshroom", 2L, 0), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);
+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("Natura", "Glowshroom", 2L, 1), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);
+        GT_Values.RA.addExtractorRecipe(GT_ModHandler.getModItem("Natura", "Glowshroom", 2L, 2), new ItemStack(Items.glowstone_dust, 1, 32767), 300, 2);

**Comment by Highbeam** [comment]
2 really weird discoveries with this:

If you put normal glowstone (348) in your inventory (say 1 piece) and then put the meta glowstone on your hotbar (348:32767) - shift clicking the glowstone from the hotbar to move into inventory will convert some of the glowstone to 348.  Do it multiple times to convert all.  I was only able to test with 8 pieces...

Second way to use it is to apply the meta glowstone to a translocator and right click to get it back.
