### ISSUE TITLE
High Pressure Coal Boiler vs Advanced LV Boiler

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3371]
#### Which modpack version are you using?
.4.6
Looking at both the high pressure coal boiler and the advanced lv boiler next to each other, the advanced lv boiler produces less steam than the high pressure coal boiler. Is this an intentional feature, or should the lv boiler be producing more than the high pressure coal boiler

**Comment by draknyte1** [comment]
You can't really compare them. 
Besides the fact they consume the same ratio of water to produce steam. 

My Tiered boilers don't consume fuel constantly. Once they warm up, fuel usage drops significantly. Only once they cool down to 80% heat will they consume another piece. This means your single piece of charcoal produces steam for an extended period. Efficiency vs production capability basically. 

They produce 3x less in GTNH than normal, so query DreamMaster about that. As usually they'd produce 750, not 250.

**Comment by Dream-Master** [comment]
I can't rember when it was changed? Did we using the old value and main branch was changed or the other way around.

**Comment by draknyte1** [comment]
Tec made it a config option and turned it down to 1/3 of the original amount. No idea why.

**Comment by Dream-Master** [comment]
maybe because we change the recipe using wrought iron in most of the machines and only a little but steel

**Comment by Dream-Master** [comment]
@Technus you remeber why we did the change ?

**Comment by Methes** [comment]
IIRC the change was made to balance the boilers better as the amount of steam per charcoal was VERY high. Would have to dig up the issue but there were exact numbers.

**Comment by Methes** [comment]
It's issue #1929

**Comment by Dream-Master** [comment]
@Methes thanks for digging :)

**Comment by draknyte1** [comment]
Here's why it should be unnerfed: https://github.com/draknyte1/GTplusplus/commit/470d876b83e1ccb28c135203b93ed3cb500d711d

**Comment by draknyte1** [comment]
It was producing 2x the steam intended previously, which has since been resolved.

**Comment by Dream-Master** [comment]
change to config option will make it more balanced @draknyte1 ?

**Comment by draknyte1** [comment]
Yes, read the issue above I linked this one to.
