### ISSUE TITLE
Deep Dark

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#338]
Make some Gt Ore veins extra for this dimension.

**Comment by Drobac** [comment]
suggest making it all ores and put the deep dark recipe at max tier so we can use it for automining

**Comment by Dream-Master** [comment]
Adding Black Plutomium to the Portal recipes ?

**Comment by Drobac** [comment]
That would work

**Comment by Dream-Master** [comment]
i am working on it

**Comment by Dream-Master** [comment]
-[ ] Recipes are added. 
-[ ] Add Ore mixes.

**Comment by Drobac** [comment]
Also please add an oremix with yellow garnet ore in the deep dark. Id suggest making it a gems vein so it has rubies, olivine and yellow garnet

**Comment by Dream-Master** [comment]
yes i will add all the stuff as ore not small ores and in huge size and amounts. Have to test it first.
So have to add a lot of new mixes that need a bit time.

**Comment by Drobac** [comment]
We have the garnet sand vein for the yellow garnets but those require tons of ITNT to be useful so id still like a gem vein.
No small ores is a good thing as it would just mess with automatic mining and storage. What kind of new ore mixes do you want to add?

**Comment by Dream-Master** [comment]
I not thinking about it yet but i can add a gem vein sure.

**Comment by Dream-Master** [comment]
See:
https://github.com/GTNewHorizons/NewHorizons/issues/572
