### ISSUE TITLE
Single Block Generators Being Omnidirecitonal

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3380]
#### Which modpack version are you using?
4.6
Ive been wondering this for a while, but why can't your average combustion generator or steam turbine have the ability to generate power directly upwards/downwards? Is there some coding limitation? It seems really convoluted since its only detrimental to planning out designs, and doesn't seem game breaking in the slightest.

**Comment by draknyte1** [comment]
The base generator class doesn't allow it, due to how it's textures are handled. 

I see no harm in changing such to allow it, but I assume Greg did it for a reason. /2cents
