### ISSUE TITLE
Sphalerite Suggestion

### ISSUE THREAD

**Issue by squarercribb** [GTNewHorizons/NewHorizons#3383]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
On multiplayer, irrelevant.
#
#### What did you try to do, and what did you expect to happen?
Irrelevant
#
#### What happend instead? (Attach screenshots if needed)
Irrelevant
#
#### What do you suggest instead/what changes do you propose?

What I have noticed after playing GT new horizons is that when you process Sphalerite ore, you can get 2 ingots by crushing the ore in a macerator and smelting it, but if you crush it into a dust and centrifuge 2 of it, you get only 1 zinc dust and 1 sulfur dust, which does not make sense at all. This is because since the formula for sphalerite is ZnS, which is 1 part zinc to 1 part sulfur, so that means that if you have the same amount of material in a pile of sphalerite dust and an ingot, which is what from all of this it is insisting, the ingot would be a mix of both zinc and sulfur, which is not what we see, or zinc is just appearing out of the middle of nowhere.

I would suggest maybe instead of getting 1 ingot per crushed sphalerite ore when smelted, maybe just 4 nuggets so that more processing is always rewarded.

Just an idea

**Comment by sthegreat** [comment]
You'll see these kinds of sketchy ratios everywhere in GT. Most of the time electrolyzing chemicals is bad for metal output but gives byproducts, even though this logically makes zero sense. I don't really see the point of changing it though since it gives the player a good choice between byproducts and metal, and there is also an extra metal and some byproducts choice with the EBF that I really like.

**Comment by WarlordWossman** [comment]
Not going to happen, the "problem" you named would be an issue for a massive amount of materials.
In the end you would still find ways wo use sphalerite differently so it's not a big issue.

**Comment by Bluebine** [comment]
Basically every recipe is like that. It's not for realism, it's for balance.
