### ISSUE TITLE
Circuit Tiering Problem?

### ISSUE THREAD

**Issue by TauZer0** [GTNewHorizons/NewHorizons#3384]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
![2018-08-02_16 20 55](https://user-images.githubusercontent.com/14206587/43586686-ecd9656a-9670-11e8-8dd7-afddd2f3dc2c.png)
![2018-08-02_16 21 30](https://user-images.githubusercontent.com/14206587/43586696-f1a2f818-9670-11e8-8dd4-c4e858715247.png)
#
#### What do you suggest instead/what changes do you propose?
Is it intended? Good Integrated circuit is more expensive than an older one. And seems that there is an oredict problem because  the older circuit recipe shows all lv-tier circuits but recipe of Good Integrated circuit shows only Integrated Logic circuit (lv-tier).

**Comment by Wolozo7** [comment]
The Good Integrated CIrcuit can be used to make HV circuits. The Electronic one can't do that. That's also the reason for your second question, it's intended that you can only use Integrated LV circuits for Integrated MV circuits.
