### ISSUE TITLE
Project Red only sees a stack of items

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3385]
#### Which modpack version are you using?
2.0.4.6

#
#### What did you try to do, and what did you expect to happen?
Use project red chips with the drawer controller for a simple "ae system."
#
#### What happend instead? (Attach screenshots if needed)
The pipes only see 1 stack at a time instead of the full contents of the drawer, so you can't see what items you have with the project red pipes.
#
#### What do you suggest instead/what changes do you propose?
Bug fix if it's possible

**Comment by boubou19** [comment]
known bug

**Comment by alphaNOVAircraft** [comment]
Read #3393 for answer
