### ISSUE TITLE
Gas Turbine for reduced pollution

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3388]
As is, gas turbines might be used to get of waste gas if your setup has it, like hydrogen,  methane, or benzene.

I propose giving gas turbines a purpose - low pollution power.  I am think 1/2 to 1/4th of current pollution numbers, including the large gas turbine.  This would be a nice benefit since there isn't a really good high EU gas. This is similar to real life as natural gas turbines replace coal fired.

I'm thinking we also bump pollution on combustion gens a little, maybe 25%.  So now a player concerned about pollution could use 4 gas gens around his EBF instead of 4 combustion gens.  Maybe increase EBF pollution too.

**Comment by Bluebine** [comment]
I support this idea.
Also worth mentioning is that this is also pretty realistic- gas turbines run off smaller molecule fuels than combustion gens, which naturally burn a lot cleaner IRL.

**Comment by richardhendricks** [comment]
Ironically, I looked at the code, gas turbines already are 50% of the pollution from combustion engines. Don't we look silly. I did see that the LCE multiblock pollution is pretty low, so it has been increased 50%. This makes the Large Gas Turbine a little more interesting as a choice.

**Comment by richardhendricks** [comment]
I added information on gas turbines being cleaner burning to their quest, and moved them next to combustion generators so players can see clearly the alternatives.
