### ISSUE TITLE
Wire Factory - Remove Air block requirement?

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3394]
#### Which modpack version are you using?
2.0.4.6
#

#### If in multiplayer; On which server does this happen? 
Epsilon
#

#### What did you try to do, and what did you expect to happen?
Wire Factory doesn't form if it doesn't have air blocks around it
#

#### What do you suggest instead/what changes do you propose?
I couldn't get the Wire Factory to form, but after checking the code I see there is a requirement for Air Blocks around it even though this isn't mentioned in the multiblock.

Actually I don't see the need for the air block requirement.  Can it be removed?

I wanted to make this multiblock look fancy in my base and it doesn't work.  Also, if the air block requirement stays, it will need calibrating to work with Galacticraft.airblocks and other air block types too ?

**Comment by Highbeam** [comment]
Furthermore, the requirements ask for 2 Output Bus and 2 Input Bus - I think this can be changed to 1 of each unless theres a reason for it?

**Comment by Prewf** [comment]
You should move all concerns for the gt++ multi's to https://github.com/draknyte1/GTplusplus/issues, but yea I agree with this. Some multi's have arbitrary formation rules imo, they should be as free-form as possible imo. For example, I think the industrial extruder should allow input buses on the edges.

**Comment by Highbeam** [comment]
ah pants meant to raise this on gt++!

I'll relocate

**Comment by Highbeam** [comment]
https://github.com/draknyte1/GTplusplus/issues/348
please close here

**Comment by richardhendricks** [comment]
We keep open connected tickets until GT++ finishes up.
