### ISSUE TITLE
Suggestion: Replace chain armor quest with iron armor

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3395]
#### Which modpack version are you using?
2.0.4.6
#### What do you suggest instead/what changes do you propose?
One thing I've noticed that doesn't make sense to me is the "fancy armor" quest which requires you to make chain armor. This is completely stupid for that age- steel rings take 1 steel ingot each to make at steam age, so you're sacrificing 24 steel ingots for an armor worse than iron armor and with the same durability. It requires steel, so it's also available later than iron armor is.
My suggestion: Make the first part of the quest to retrieve 24 iron plates, and the second part to craft a full suit of iron armor.

**Comment by Dream-Master** [comment]
will do the chain mail armor optional

**Comment by Bluebine** [comment]
that would work, just change the current chainmail quest to be iron armor and put a new quest for chainmail branching off that
