### ISSUE TITLE
corruption!!

### ISSUE THREAD

**Issue by bengenie** [GTNewHorizons/NewHorizons#3396]
#### Which modpack version are you using?
2.0.4.6
#### What did you try to do, and what did you expect to happen?
my world got corrution
#
#### What happened instead? (Attach screenshots if needed)
![minecraft 1 7 10 2018-08-03_16-22-14](https://user-images.githubusercontent.com/13812025/43665056-f01e7b62-973c-11e8-8396-b3916a1751a4.jpg)

#### What do you suggest instead/what changes do you propose?
having aromabackup pre installed to avoid corruption.

**Comment by bartimaeusnek** [comment]
well, first backup your world folder. then remove the level.dat and replace it with the level.dat_old that you rename to level.dat

it should load then. if not, ask in discord please, but we wont add aroma backup, the questbook even tells you to make backups or install a backupmod to avoid such situations.

**Comment by boubou19** [comment]
There is a quest that tells you to install it written by Dream on it so if he could have been able to add it in the pack, he will already have done.

**Comment by Dream-Master** [comment]
its written by @richardhendricks :)

**Comment by richardhendricks** [comment]
There is a quest vs a provided mod because users have multiple ways to backup their game. The choice is up to them, the point of the quest is to let players know to look at backup options before playing 1,000 hours and losing everything.
