### ISSUE TITLE
Cotton through the wiremill gives string

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/NewHorizons#3397]
#### What do you suggest instead/what changes do you propose?
I'd like to suggest adding a recipe for string that uses cotton in a wiremill.

**Comment by Dream-Master** [comment]
yea why not.

**Comment by WarlordWossman** [comment]
I am actually against this, the ratio seems fine and if you can turn cotten to string 3 times better it only means that string gets really cheap all of a sudden.
Also discourages making string from naphtha even more...

**Comment by Dream-Master** [comment]
who said you need only one cotton ? @WarlordWossman

**Comment by WarlordWossman** [comment]
Idk, sounds weird to introduce wiremill recipes with multiple items since the machine only has recipes with 1 item as input. Maybe the assembler would be a better option in that case.

**Comment by Dream-Master** [comment]
If string is made from cotton i am against to make it out of napta. Maybe we can add a new item ordicted to string. A sythetic string.

**Comment by WarlordWossman** [comment]
It's the plastic you make from naphtha and saltpeter (yay actual use for saltpeter for once) and the ingot gives 32 string in the MV wiremill. I like cotton but I think we should also encourage industrial ways to make string.

**Comment by Dream-Master** [comment]
i never know there is a recipe will check it.

**Comment by noobyaran9** [comment]
There is no point in introducing this recipe, the method that @WarlordWossman mentions supplies you with plenty of string with just a small amount of saltpeter.

**Comment by CalterOK** [comment]
Also, do not forget about getting threads with Plax Seeds.

**Comment by ljjmrlion** [comment]
This recipe makes it so that you don't have to manually craft cotton into string and get the crafting lag spikes once you have LV. This way you can just have a machine craft it for you. Plus if you made a massive cotton farm in early game it won't become just obsolete.

**Comment by richardhendricks** [comment]
I agree, it could be useful to have a 2 cotton -> 1 string assembler recipe. Make it not too long though, maybe 4s.

**Comment by bartimaeusnek** [comment]
we have already cotton -> string in spinning wheel recipe...

**Comment by MineAnPlay** [comment]
I agree with bartimaeusnek, it's not expensive and the speed is decent. It's also a one to one ratio.

**Comment by richardhendricks** [comment]
@draknyte1 Plz add multiblock cotton gin.

**Comment by ljjmrlion** [comment]
But can you get the spinning wheel in lv?

**Comment by Dream-Master** [comment]
I add it also to Wiremill
