### ISSUE TITLE
Mud craftable using dirt and water in a mixer

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/NewHorizons#3398]
#### What do you suggest instead/what changes do you propose?
I had decided to build some things using mudbrick and was surprised to find that actually acquiring mud was kind of annoying. I would like to propose a crafting recipe for mud using dirt and water in a mixer or another machine you feel would be suitable.

**Comment by Dream-Master** [comment]
yea sure i can add it.

**Comment by richardhendricks** [comment]
PLz post pics to discord, I want to see your mudbrick utopia. :dancer:

**Comment by richardhendricks** [comment]
Also btw you can get mudballs from clay bees, which are super easy to breed.  And also give you clay.

**Comment by richardhendricks** [comment]
Verify if this recipe made it in

**Comment by Bluebine** [comment]
I think there should be a steam-age equivalent, that's less efficient.
ATM there's 1 dirt+ 1000L water= 4 mudballs in mixer.
my suggestion:
1 dirt+ 1 bucket of water= 2 mud balls
yeah i know it's not very exciting but it'll work

**Comment by richardhendricks** [comment]
I am OK with that

**Comment by ljjmrlion** [comment]
![image](https://user-images.githubusercontent.com/9472512/59732395-0d35a280-9218-11e9-8f31-10d57f27cb28.png)
