### ISSUE TITLE
Oil Drilling Rig problems

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3399]
There are some mistakes in the oil drilling rig file. The math that designates what chunks to drill from is wrong and it doesn't actually look at how much oil is in the other chunks when drilling.

We should fix and pull this change:
https://github.com/Blood-Asp/GT5-Unofficial/commit/be7c5d7c4918282561eb9796d7d6ebb365f123d7

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/43669841-d7271812-974b-11e8-8390-77d587749ed8.png)

**Comment by richardhendricks** [comment]
Confirmed weird shit on negative chunks not needed.

4x4 driller with total of 8516 on chunks
8516 * .5 (energy hatch tier is minimum) = 4258L per operation.
4258*20/32 = 2661 L /s

80902L in 30s test  = 2692L/s

Matches.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/4c4c412769df240e4dfe949854c8750b7a91cc9f
