### ISSUE TITLE
Infernal mob new Poitions

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#340]
Have to test the new mob drops.

**Comment by Namikon** [comment]
What did you change? And what is supposed to drop now?

**Comment by Dream-Master** [comment]
Not added to the live server only to the test server.

**Comment by Dream-Master** [comment]
I added new potions.

**Comment by Dream-Master** [comment]
Health 3 and Regeneration 3.

**Comment by Dream-Master** [comment]
I never get this potions maybe have to change something.

**Comment by Dream-Master** [comment]
not working i guess.

**Comment by deeplyarnab** [comment]
i will suggest to disable the mobs with a fishing rod and "vengeance" titled mobs as you r sure to die if u go against them, the fishing rod ones pull u toward more mobs and traps you while the vengeance mob decrease your health when u attack them so leaving us unable to kill them (except 1 strike kills)
If balance is nto affected then also disable the wither witches

**Comment by Dream-Master** [comment]
If we disabled more from infernal mobs or special mobs we can remove them complete because there is nothing left.

**Comment by Dream-Master** [comment]
But this issue I open to test new drops from infernal mobs.

**Comment by Dream-Master** [comment]
I never get a poition so not working i guess.

**Comment by Dream-Master** [comment]
Not working.
