### ISSUE TITLE
Distillery missing crafting recipe

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3402]
Witches distillery is missing crafting recipe in-game.

wait, maybe it is in game but I am missing scripts.  Will check later.

**Comment by WarlordWossman** [comment]
you can def get it unless smth changed

**Comment by richardhendricks** [comment]
Restarting with updated scripts.  I am probably missing @draknyte1 's witchery recipe mod too.

**Comment by richardhendricks** [comment]
Still no recipes.  Will look at tracking down witchery++ tomorrow.

**Comment by Dream-Master** [comment]
Thaumcraft recipe
