### ISSUE TITLE
Schematics rocket chip recipe accepts blank datasticks

### ISSUE THREAD

**Issue by Jocroy** [GTNewHorizons/NewHorizons#3405]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
DigToBuild
#
#### What did you try to do, and what did you expect to happen?
Craft a rocket schematic chip (Tier 5, but this probably doesn't matter) in the circuit assembler.
#
#### What happend instead? (Attach screenshots if needed)
The recipe accepts a blank datastick, not only the one with the scanned schematic.
#
#### What do you suggest instead/what changes do you propose?
Only allow the correct datastick or replace the datastick with the schematic in the circuit assembler recipe.

**Comment by bartimaeusnek** [comment]
@richardhendricks can you check if the circuit assembler bypasses NBT data? ill look for a hotfix
