### ISSUE TITLE
Rotor and watermill quest outdated/incorrect

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3406]
#### Which modpack version are you using?
2.0.4.6
#
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/37113583/43688191-23e264a2-98ed-11e8-9cad-3c8e4a059309.png)
that is quest
![image](https://user-images.githubusercontent.com/37113583/43688192-353f507a-98ed-11e8-8020-56229429449b.png)
that in craft
and mistake with watermill quest
![image](https://user-images.githubusercontent.com/37113583/43688200-558ee1a6-98ed-11e8-867f-d8e56a82af77.png)
quest need windmill's materials to completing(motors)
![image](https://user-images.githubusercontent.com/37113583/43688209-6e97a11a-98ed-11e8-8e71-eeef8456bfc5.png)

**Comment by Dream-Master** [comment]
will check
