### ISSUE TITLE
Have Null routing chips use vacuum tubes instead of LV circuits, up output

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3407]
The null routing chip is useless on its own. It is just a crafting component for the actual chips you need.  As is, the recipe requires 1 whole LV circuit, and each followup chip also requires an LV circuit. This should be changed to 

Null routing chip recipe uses vacuum tubes instead of LV circuit, and outputs 2 null chips. 

The next tier of chips can be left alone. It is still expensive to make an automated setup, but by that point a player should be doing LV circuits in batches of 64 anyways. So GT:NH!

Maybe add a followup quest chain on automating LV circuits, lol.

**Comment by Lainiel** [comment]
I'd like to add one more option for higher tier players to make 4 null logic chips with 1 LV-tier circuit so they don't have to make vacuum tubes.
