### ISSUE TITLE
GregTech New Horizons is completely broken, and worthless

### ISSUE THREAD

**Issue by Solverbolt** [GTNewHorizons/NewHorizons#3408]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
DigToBuild
#
#### What did you try to do, and what did you expect to happen?
I completed the requirements for dozens of quests/required steps in progression.  Does not register that a player has done it. Admin has to bypass the system to get it to complete.
#
#### What happend instead? (Attach screenshots if needed)
It does nothing, just like Gregtech
#
#### What do you suggest instead/what changes do you propose?
Quit using Gregtech. Its been a broken mod created by a worthless mod creator for the last 5 years. I knew he was worthless and only a copycat when I met him at Minecon 2013. He plagiarized other peoples work as his own, but when it breaks because he tries to change it, he has no idea how to correct the issue, so he ignores it.

**Comment by Bluebine** [comment]
😎ayylmao
someone doesn't like gregtech

if you've got any actual specific issues you can post them here but no one else has reported the quest issues you're having and no one else has a problem with Gregtech as a whole

**Comment by richardhendricks** [comment]
Are you using a legitimate copy of Minecraft? Are you logged in to Mojangs authentican servers?

And if you think Gregtech is so bad, why are you here?

**Comment by Methes** [comment]
Made my day! Thanks! :-D

**Comment by Bluebine** [comment]
😎ayylmao

The most likely cause of the quest system being broken is you running pirated MC, no one else is having this problem.
And to move generators, use a wrench to break and replace them. Just like all GT machines. Wire cutters break and replace wires and cables.

**Comment by boubou19** [comment]
why keep open an issue which insult the pack and with baseless statements? from what i read you had troubles with first couple of quests in the quest book. Or a lot of people start GT:NH everyday and the only one who had trouble is you. If you want to be taken seriously first post proofs of what it happened

**Comment by bartimaeusnek** [comment]
@Solverbolt 

First of all: It's a free modpack made by volunteers. If you think you can make a better one, go ahead or help us improving it. If you can't do that sad for you. 

> the Quest system is broken

It not if you own a legitimate copy of minecraft.

>It also revolves heavily around the fact the Gregtech's setup and manipulation of items makes it impossible to work around

yes. thats what it is supposed to do.

>There is no tool to uproot the first gen power generation machines.

Wrench.

> By the way, closing the case within under 2 hours, not allowing people to respond, shows what a coward you are, as it is obvious you do want to actually have a discussion, you just want to try and prove to the rest of the world that you are a fool

If you or anyone else is just a complete idiot and cries around instead of asking questions ill close that thread. Now go play Vanilla or something.

**Comment by richardhendricks** [comment]
I suggest reading the quest texts and/or asking for help in Discord, preferably one that speaks your native language.

**Comment by richardhendricks** [comment]
Add to tools quest that Wrench is used to break machine and pipe blocks.

**Comment by Highbeam** [comment]
I see trolls exist for real now...

Unfortunately all the problems you have described are untrue for this pack. I recommend that you uninstall the pack and leave this forum as I don’t think you deserve any help with that attitude.

I don’t think anyone will be losing any sleep over the fact that you fail at life and can’t play a Minecraft mod...

Vanilla Minecraft or minesweeper might be better for you :)

If you do choose to not be a d*** for no reason and try again properly then we’ll see ;) no need for the useless hate when the problems are yours, not the pack.  Hope you learn a nicer attitude or get punched in the face of you don’t.

**Comment by richardhendricks** [comment]
![2018-08-20_22 35 57](https://user-images.githubusercontent.com/1214811/44378992-7dc14500-a4c9-11e8-9829-34186cb9fe18.png)

**Comment by richardhendricks** [comment]
Even a moron (tm MoronWMachinegun asshole) can now figure out how to use Gregtech Tools.

**Comment by FavouriteDragon** [comment]
@Solverbolt I've never seen such a self-entitled prick on github.
Don't hate on others because you're unable to recreate what they do.
