### ISSUE TITLE
Lord of Tortment issue

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3409]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to kill tortment boss
#
#### What happend instead? (Attach screenshots if needed)
At 2nd stage, in tortment dim, tortment boss didn't spawn
#
#### What do you suggest instead/what changes do you propose?
idk, this is witchery issue. People here https://mineyourmind.net/forum/threads/witchery-problem-with-lord-of-torment.20955/ have same issue

**Comment by barsikus007** [comment]
I think, we need coins coins quest 
scroll of tortment and potion of regeneration (for regenerate infusion) and coins to em loot

**Comment by Dream-Master** [comment]
is this a server issue or is it broken in sp too?

**Comment by Bryfer** [comment]
Seems to be MP because it's working in SP properly

A possible fix would be a quest that unlocks once you each the hell dimension, which gives you a spawn egg?

**Comment by Dream-Master** [comment]
I never visit this dim. will check

**Comment by repo-alt** [comment]
I had experienced the same bug, but the second time it worked. Sure, some workaround would be nice to have, because earning these scrolls takes quite some time.

**Comment by Dream-Master** [comment]
I add a Quest where a spawn egg was added when entering Tormet.
