### ISSUE TITLE
Mod Suggestion: Holo Inventory

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#341]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292641-v1-9-holoinventory-v1-9-double-chests-now-work

It is an interesting mod that lets you see the content of an inventory without having to open a chest. It shows the contents hovering above the chest.
It's a purely utility mod, makes finding your needed items much easier and works fine with modded chests, AE interfaces and other storage items.

**Comment by Dream-Master** [comment]
I see this mod before but not sure if it is compatible with iron chets or jabba.

**Comment by Drobac** [comment]
Well you dont need it with JABBA, just need to check iron chests. But it works fine with Thermal expansion strongboxes.

**Comment by Drobac** [comment]
"It was designed to work with all blocks that implement "IInventory", meaning all normal inventories"

**Comment by Dream-Master** [comment]
Ok i can add it.

**Comment by Dream-Master** [comment]
What the other thinking about this mod?

**Comment by Drobac** [comment]
Check it on the test server, but i think youll like it

**Comment by Namikon** [comment]
It's a neat feature we've seen in Material Energy. The mod is mostly clientside, but due the way chests work, it needs to be installed on the server too. Not too much overhead. I vote for it

**Comment by Dream-Master** [comment]
ok will add with the next update.

**Comment by Dream-Master** [comment]
Added to the testsever.

**Comment by Dream-Master** [comment]
Is this a client only mod ?

**Comment by Namikon** [comment]
No

**Comment by Dream-Master** [comment]
ok thanks

**Comment by Dream-Master** [comment]
Added and Done.
