### ISSUE TITLE
latest GTNH Server files cotain the same mod twice and do not work

### ISSUE THREAD

**Issue by ljjmrlion** [GTNewHorizons/NewHorizons#3412]
#### Which modpack version are you using?
GTNH Latest
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Server files zip contains two of the same mod and will not start
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/9472512/43746470-7eefc5fe-99b2-11e8-80a6-430fd2477f71.png)

#
#### What do you suggest instead/what changes do you propose?
remove the older version that was added by mistake

**Comment by Dream-Master** [comment]
fixed allready. Please redownload it.
