### ISSUE TITLE
WaterLillyCrop Texture Issures

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3413]
#### Which modpack version are you using?
2.0.4.7

#### Issure:
The Waterlilly Crop does not render propperly as seen here:
https://media.discordapp.net/attachments/224191655375273985/476188556079923210/2018-08-06_20.42.29.png

#### Quickfix, apply as texture pack:
https://cdn.discordapp.com/attachments/224191655375273985/476201075314130944/WaterlillyFix.zip

**Comment by Dream-Master** [comment]
ok uploaded to the client files on FTB Curse and to the client download
