### ISSUE TITLE
Review Multi Block goals and mark quests as main that need to be mainline

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3416]
Cleanroom and Vacuum Freezer at minimum.

**Comment by bartimaeusnek** [comment]
EBF, Coils and Implosion Compressor should be a main quest aswell.

**Comment by MineAnPlay** [comment]
Also remove the TNT requirement for the iTNT quest because you can most likely make iTNT when you make an Implosion Compressor.
