### ISSUE TITLE
More information on growing IC2 crops

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3417]
More Red, less Wheat

When breeding together crops for an output crop, try to get crops that are close in tier to the output crop, and have similar attributes to the output crop. For example, Redwheat has "Red", "Wheat" and "Redstone" attributes and is tier 6.  Hops has "Wheat" and Netherwart "Red" and both are tier 5. Use the cropnalyzer crop prediction mode to see how many points Redwheat has using this combination.

tasks
1x hops
1x netherwart

1x redwheat

rewards
4 hydration cells

in a different quest we can add

Growability depends upon factors like having enough dirt underneath (4 max), biome (swampy is best), air quality  (grow at Y>124 altitude and don't place a lot above your plants), hydration, and fertilizer.

**Comment by Methes** [comment]
public byte updateAirQuality()
  {
    int value = 0;
    int height = (this.yCoord - 64) / 15;
    if (height > 4) {
      height = 4;
    }
    if (height < 0) {
      height = 0;
    }

So growing crops at y=124 and up should have the highest air quality.

**Comment by richardhendricks** [comment]
umm...There is no return in that function. :D  Also, the blocks around it matter a little too right?

**Comment by Methes** [comment]
Of course, this is just a snip from dev version from here: http://jenkins.ic2.player.to/job/IC2_experimental/
There's also code about surrounding blocks, yes.
If I understand it right, max air quality bonus is 4 for height, 4 with no other crops around the calculated crop itself (each crop around it lowers the bonus by 0.5) and 2 for clear sky above.

 public byte updateAirQuality()
  {
    int value = 0;
    int height = (this.yCoord - 64) / 15;
    if (height > 4) {
      height = 4;
    }
    if (height < 0) {
      height = 0;
    }
    value += height;
    int fresh = 9;
    for (int x = this.xCoord - 1; (x <= this.xCoord + 1) && (fresh > 0); x++) {
      for (int z = this.zCoord - 1; (z <= this.zCoord + 1) && (fresh > 0); z++) {
        if ((this.worldObj.isBlockNormalCubeDefault(x, this.yCoord, z, false)) || 
          ((this.worldObj.getTileEntity(x, this.yCoord, z) instanceof TileEntityCrop))) {
          fresh--;
        }
      }
    }
    value += fresh / 2;
    if (this.worldObj.canBlockSeeTheSky(this.xCoord, this.yCoord + 1, this.zCoord)) {
      value += 2;
    }
    return (byte)value;
  }

**Comment by richardhendricks** [comment]
ok so clear sky only matters directly above the crop, and blocks in the 8 block area right around the crop.
