### ISSUE TITLE
Hand pump quests (2x) need to be set to consume resources

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3418]
The two handpump quests (one after plunger, one in Coins) needs to be set to consume items to make the pump.

**Comment by Dream-Master** [comment]
Hand pump need a fix also. Ask Bluebine fr the glisch.

**Comment by Dream-Master** [comment]
I add only one hand pump quest @richardhendricks

**Comment by Dream-Master** [comment]
@richardhendricks found it.

**Comment by richardhendricks** [comment]
There is two quests, I added one in Coins in case  a player lost theirs.  Make sure both quests are set to consume.

**Comment by Bluebine** [comment]
they both are, all good 👌
