### ISSUE TITLE
pichblend quest can not be completet

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3419]
#### Which modpack version are you using?

2.0.4.7
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
part of quest asks for uranium 238 but does not spawn in pichblend vein so i mined the uranium 238 ore on deimos
#
#### What happend instead? (Attach screenshots if needed)
quest does not exept the uranium 238 ore from deimos and will not complete
#
#### What do you suggest instead/what changes do you propose?
remove the uranium 238 ore from the quest

**Comment by Dream-Master** [comment]
i thought i did it allready. Did you reload your Quests with /bq_admin default load ? @botn365

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/43834546-bb338bf6-9b0e-11e8-9c6d-9365c2da5172.png)

**Comment by Dream-Master** [comment]
@botn365 reload your quest

**Comment by bartimaeusnek** [comment]
you can use the default load block aswell

**Comment by botn365** [comment]
i dit the reloade and is fixed now
