### ISSUE TITLE
Tinkers construct modifiers

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#342]
I'd like to see a lot more modifers available on Tinkers' Construct weapons that would make the viable to fight infernal mobs with tons of HP. Tinkers' weapons become completely obsolete as soon as you have the ability to get a better sword (Thaumcraft, Blood magic mostly). This would make the weapons viable for later game as well and you would get rewarded for using the same weapon and leveling it up constantly. 
If its possible to set the modifier levels just for the weapons id revert them back to original configs where you can get a free modifier every 2 levels or so. Its not really op since leveling up the weapons take a lot longer and is harder then leveling up tools.
IMO, if you have a sword that you have been using for months since you started playing i would like to see that sword be even more powerful then the Draconic Evolution weapons.
Thoughts?

**Comment by Dream-Master** [comment]
Added the Following things to the test server.
- [ ] Random Modifier all 2 Levels 2,4,6,8,10.....
- [ ] Additional Modifier all 5 Levels 5,10,15,20...
- [ ] Possible Level 99

**Comment by Dream-Master** [comment]
any news here?

**Comment by Dream-Master** [comment]
```````````````
toolleveling {
    # Adds a random bonus on these levelups if 'RandomBonuses' is enabled
    I:BonusesAtLevels <
        2
        3
        4
        5
        6
	8
	10
	13
	16
	19
	23
	27
	31
	36
	41
	47
	53
	59
	66
	74
	83
	93
	99
     >

    # Each modifier is equally likely on levelup. Disables useful bonuses. [default: false]
    B:CompletelyRandomBonuses=false

    # The amount of modifiers new tools have. [range: 0 ~ 9, default: 0]
    I:ExtraModifiers=0

    # Adds an extra modifier on these levelups if 'ExtraModifiers' is enabled
    I:ModifiersAtLevels <
        5
        10
        15
        21
        28
        36
        45
        55
        66
        78
        91
        99
     >
````````````

**Comment by Dream-Master** [comment]
Are the new System OK ?

**Comment by Namikon** [comment]
I assume it is. Noone complained yet
