### ISSUE TITLE
Potental bug with bee collector's jar.

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#3423]
#### If in multiplayer; On which server does this happen? Single

#
#### What did you try to do, and what did you expect to happen?

Earlier today I had a series of crashes. With some help I tracked down the issue to a particle effect in a empty square in my base. The only things near that area that caused a particle effect were a collector's jar with bees that had a healing effect. The area was also under the effect of 25 extremely large nodes. The crashes stopped by removing the collector's jar.

Afterwards I replaced the jar with a apiary to see if the game crashed and it has yet to do so. I suspect there is a issue with the jars.

**Comment by Dream-Master** [comment]
@Pockyninja if you have a crash log please post it here.

**Comment by Pockyninja** [comment]
[crash-2018-08-07_23.49.10-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2271171/crash-2018-08-07_23.49.10-client.txt)
[crash-2018-08-08_00.26.25-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2271173/crash-2018-08-08_00.26.25-server.txt)
[crash-2018-08-07_23.11.49-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2271174/crash-2018-08-07_23.11.49-server.txt)
[crash-2018-08-07_23.11.59-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2271175/crash-2018-08-07_23.11.59-client.txt)
[crash-2018-08-07_23.25.16-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2271176/crash-2018-08-07_23.25.16-server.txt)


I deleted several of them while working on it but these are a few of them.
