### ISSUE TITLE
Check unlock for Empty Epoxid Board, in EV

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3426]
Almost to HV, Empty Epoxid Board (EV, upper middle) unlocked.  Not sure why.

**Comment by richardhendricks** [comment]
This is with 2.0.4.6 on Epsi

**Comment by Dream-Master** [comment]
you mean quest are open before tab official unlocked?

**Comment by richardhendricks** [comment]
yeah.  I'm guessing its tied to an MV quest of some sort.

**Comment by Dream-Master** [comment]
yea we have a mv quest did the same in mv tab

**Comment by Dream-Master** [comment]
It was a or quest by accident.
