### ISSUE TITLE
Missing Plasma

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#3427]
#### Which modpack version are you using?
2.0.4.7
#
#### What did you try to do, and what did you expect to happen?
Looking for some Plasma recipe
#
#### What happend instead? (Attach screenshots if needed)
In 2.0.4.6 we actually can find more Plasma
![20180809210206](https://user-images.githubusercontent.com/25171639/43900513-bb93b300-9c17-11e8-907e-73cb0f421dde.png)
but in 2.0.4.7 we only can find
![20180809211849](https://user-images.githubusercontent.com/25171639/43901364-ddc89b64-9c19-11e8-9ccd-5f5d127de044.png)
then i check the Fusion recipes and i find it they are change to output molten material
For example the Nickel Plasma in 2.0.4.6
![20180809205946](https://user-images.githubusercontent.com/25171639/43901491-346210cc-9c1a-11e8-8a1f-a48ad627e2d0.png)
and in 2.0.4.7
![20180809212342](https://user-images.githubusercontent.com/25171639/43901636-89cef75a-9c1a-11e8-95d6-f77b736202e0.png)
It just output the molten

**Comment by Dream-Master** [comment]
Indeed must be a bug. @richardhendricks @Technus @mitchej123 @bartimaeusnek @codewarrior0 any idea

**Comment by Dream-Master** [comment]
it is deactivated by tectech. We get a new device/machine for make the plasma above iron soooooon(tm)

**Comment by Dream-Master** [comment]
``    # Set to true to enable removal of plasmas heavier than Fe and other weird ones [default: false]
    B:NerfFusion=true``

**Comment by MineAnPlay** [comment]
It's because fusion above Iron 56 is not energy positive IRL.
