### ISSUE TITLE
Forestry Farm range too big with IC2 crops?

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3429]
#### Which modpack version are you using?
2.0.4.6 (but no updates to forestry or ic2 in 2.0.4.7+ afaik so this should still be valid)

#
#### What happend instead? (Attach screenshots if needed)
The Forestry farm's intended range when harvesting/fertilizing/hydrating ic2 crops is the forestry diamond shape, going 11 blocks out from the side of the max forestry farm. However, it actually harvests/fertilizes/hydrates crops outside of this area. I did a quick test, see attached screenshot.
![Image of Test Setup](https://i.imgur.com/vClwRDu.png)
Blue: intended farm max range, Green: harvested/fertilized/hydrated anyway, Red: not affected by farm
Some observations:
-For the extra crops the farm doesn't care about stone bricks below
-The extra range seems to be square instead of diamond, and 5 blocks out
-It doesn't matter if the crops are touching others or not

#
#### What do you suggest instead/what changes do you propose?
If this seems overpowered, change it if possible, though idk if you can easily do that. If it's fine balance-wise I would recommend fully figuring out this behavior if it's not already known, and noting it in a quest or tooltip somewhere so players can use it. Personally I think it is fine balance-wise since players still need to get the extra seed bags to use this.

**Comment by Bryfer** [comment]
Server or sp?
What is the config set to?

**Comment by sthegreat** [comment]
Singleplayer 2.0.4.6 with no config changes (so it's supposed to be the regular diamond shape).

**Comment by richardhendricks** [comment]
Expected behavior with Orchard mode since leaves would be beyond edge of farm
