### ISSUE TITLE
Quest for GT item pipes

### ISSUE THREAD

**Issue by hellrage** [GTNewHorizons/NewHorizons#3432]
Suggesting to add a separate quest for GT item pipes as they are available early on for automation but aren't explicitly brought to attention.

**Comment by Dream-Master** [comment]
@hellrage you mean as an example Tin item pipes ? What i should add to the quests?

**Comment by richardhendricks** [comment]
I'll take care of it.  I think we should add tin and maybe brass item pipe quests at the appropriate times, with tips on really simple automation.  Maybe in the steam area, after hoppers.  PPL can put a hopper on top and underneath steam machine, with pipes from say macerator to hammer or something.  Automation quest for coke ovens is after 10x coke ovens, so this would be for people who don't do that.

**Comment by Dream-Master** [comment]
ok sure

**Comment by richardhendricks** [comment]
Added tin pipes after hoppers, added brass pipes after MV along with a short explanation on restrictive pipes.
