### ISSUE TITLE
[RFC] Uses for Natura nether trees

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3435]
Right now the Natura nether trees are more or less useless.  When you get them in a bag you are pretty disappointed! Here is a proposal that makes them suck slightly less.

I don't think there are any leaves/logs/apple extractor recipes, so the proposals use that.

Bloodwood - Can drop small quantities of redstone right now. Has to be grown upside down off netherrrack about 25 high above the ground.  About 20 redstone for a whole tree, which is annoying to cut down except with an Axe of the Stream (which takes a while also). Lumberaxe only does 3x3 on it. Dark steel axe can sorta work, it cuts above the area it is some of the time. Overall kinda annoying to use but might be worth it with proposal + dark steel empowered shears.

Proposal - Add Extractor recipes for saplings and logs, 1:1 for redstone dust.  For leaves, 4:1 (four leaves for 1 redstone) for redstone dust seems fair. Maybe about a stack or two from a single tree.

Fusewood - Causes minor explosions on harvesting wood. 

Proposal - Add extractor recipes for saplings and logs, 2:1 for gunpowder. For leaves, 8:1 on gunpowder.

Darkwood - Drops potash apples pretty rarely, kinda shit food. 

Proposal - Apples give IC2 fertilizer in extractor 1:4 (4 fert for 1 apple). Logs are 2:1, leaves are 8:1. (alternative, make it a chemical reactor recipe and include apatite + water.  I would change it to 1:32, 1:8, 1:4 in that case to make it better than just using left over sulfur or phosphorus)

Ghostwood - No known uses AFAIK

Proposal - Logs and saplings give bonemeal 2:1. Leaves are 4:1.  Enough you should get back more than you use.

The Empwoered dark axe works better than the ticon lumberaxe for the blood sapling.  Would make it useful for this purpose.

**Comment by richardhendricks** [comment]
If we do this, add quest after dark tools to collect some of these. The axe and shears would work nicely with these trees.

**Comment by hellrage** [comment]
Adding to this that when enchanted with Efficiency V the Dark Pick instantly mines soft blocks(stone\dit) IIRC
