### ISSUE TITLE
Completed Quest Inaccessible

### ISSUE THREAD

**Issue by natedogith1** [GTNewHorizons/NewHorizons#3436]
Modpack version 2.0.4.7

Quest 1519 "Portable tanks too small?" and quest 1510 "Biomes everywhere, but not the one you want?" aren't visible, even after completion.  If you use "/bq_admin edit" you can see them (1519 is in tier 2, directly left of 105 "The missing one"; 1510 in in tier 2, directly to the right of 96 "Avengers, assemble!")

**Comment by Dream-Master** [comment]
There where hidden.
