### ISSUE TITLE
The big fluffy crybaby quest 905

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3437]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
complete the quest
#
#### What happend instead? (Attach screenshots if needed)
The quest was qompleted by killing a mini ghast
#

**Comment by Dream-Master** [comment]
oh ok will look at it

**Comment by Dream-Master** [comment]
i set ignore nbt to false. Maybe this helps
