### ISSUE TITLE
Alternative Primitive Circuits for MV

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3438]
#### Which modpack version are you using?
2.0.4.7
#
#### What do you suggest ?
I think it would be cool to have a chip for Vacuum Tubes (circuitPrimitive), like the Nand-Chip from 1.x
Something like:
Basic Wafer + orangeLens
 -> Simple SoC Wafer (64EU/t, no Cleanroom)
Simple SocWafer
 -> 8x Simple Soc Chip (64EU/t, no Cleanroom)
Simple Soc Chip + Good Circuit Board + 2x Redstone Alloy Bolt +2x Fine Tin Wire
 -> 2x Nand Chip (120eu/t, no cleanroom)

**Comment by Dream-Master** [comment]
ok will try to add

**Comment by DualBallers** [comment]
Hey @Zoko061602 
It seems that the nand chips are significantly more expensive than the vacuum tubes, even though the new quest states that they should be cheaper.

2x Vaccum tube
glass tube, copper wire, steel rod, and a tiny amount of red alloy
![image](https://user-images.githubusercontent.com/30087707/44912649-38074680-ad2b-11e8-90d9-e1f942ab5e14.png)

2x nand
circuit board (gold, Iron III, board), simple wafer, double the red alloy amount, tin wire, and soldering material. Also x100 times the EU to proccess.
![image](https://user-images.githubusercontent.com/30087707/44912716-6f75f300-ad2b-11e8-9ce7-8f9215f674dc.png)

A better output would be 4x or 8x nand chips (haven't done the math), otherwise this new chip is just not worth producing.

**Comment by richardhendricks** [comment]
It's not just about overall costs, it's also about simplifying the production line. With the new nand chips you don't need to make steel rods or glass tubes (or red alloy/redstone alloy). I think 4x is fair.

**Comment by DualBallers** [comment]
Yes, I agree that should ideally be the case, but here the production of every single item for the nand is more complex than for the vacuum tube.

**Comment by DualBallers** [comment]
The updated cost below basic materials. 
It still seems like the nand are still wastly more expensive, complex and time consuming to craft. 
I would still recommend a better output, or to double the material cost of the vacuum tube.

Crafting 64 nand (assuming epoxid and wafers are available)
![image](https://user-images.githubusercontent.com/30087707/45351536-bb8c2780-b5b6-11e8-9d52-83ed0183e019.png)

Crafting 64 vacuum tubes
![image](https://user-images.githubusercontent.com/30087707/45351333-330d8700-b5b6-11e8-9a32-bc8a47fe8955.png)

**Comment by Dream-Master** [comment]
or make the nand chips cheaper?

**Comment by DualBallers** [comment]
@Dream-Master, any thought on making the glass tubes more expensive, or the nand chips cheaper?

They both have a 4x recipe, and the vacuum tubes still superior with regarding complexity, material, energy and time. 
There is really no point in crafting the nands at any point.

**Comment by richardhendricks** [comment]
No, the point is that the nand chips use the same resources as the normal chips, they aren't supposed to be "better", but just more convenient.

I think the x4 for the vacuum tubes should stay.  We can make the NAND chips cheaper, but they don't *have* to be better than the vacuum tubes.

**Comment by DualBallers** [comment]
Can you tell me in what way the nands are more convenient?

As I see it, the low tier tubes are superior in every way - time, energy, complexity, materials - so why would you ever change production to the nands?

**Comment by richardhendricks** [comment]
> change production


That's the point.  If you never setup automated vacuum tubes, you have no reason to do the NANDs.

If you need that tier of circuit (say for HV tanks or whatever) and you already have a cleanroom etc, then the NANDs are more "convenient" than setting up a low-tech automated line.

**Comment by DualBallers** [comment]
Still, the quest for it specifically states that this circuit is cheaper, while actually being closer to 10x more expensive and complex.

> #Quest_1714.Cheaper Simple Circuit
> gtnh.quest1714.name=Cheaper Simple Circuit
> gtnh.quest1714.desc=The NAND chip is an industrial replacement for the vacuum tubes that is much cheaper.

**Comment by Dream-Master** [comment]
@DualBallers are you want to change recipe or quest?
