### ISSUE TITLE
Knight Phantom

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3439]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
get into the dark tower
#
#### What happend instead? (Attach screenshots if needed)
i found the dungon in TF and spawned the KnightPhantom with the egg from the quest Knight Phantom and killed him, then i ran to the dark tower but that was still locked for me
#
#### What do you suggest instead/what changes do you propose?
Is the spawnebal mobs not intended to complete quest? if they are, change this

**Comment by bartimaeusnek** [comment]
@Ghengis88 you need to have the armor archivment unlocked, most likely is that youre missing an achivment
