### ISSUE TITLE
10k coolant cell uncraftable

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#344]
The cell needs "Coolant cell" but if you fill in IC2 coolant in a normal cell, it turns into "Universal fluid cell". I tried both ways, IC2 canning machine and GT fluid canner

**Comment by Namikon** [comment]
Nevermind, you can compress a cell, extract it with a fluid canner and it turns into the correct cell. Then you can use the fluid canner to fill in the IC2 coolant, and you get the correct cell for the recipe. Annoying, but it works

**Comment by Dream-Master** [comment]
Maybe i have to change the recipes be a ic2 cell?

**Comment by Namikon** [comment]
Maybe you could just add both for the recipe. I have no idea how this system works tbh. sometimes I get an universal fluid cell, sometimes I get an empty cell. It's confusing.

**Comment by Dream-Master** [comment]
Will add both recipes. Does this error occur in other recipes too ?

**Comment by Dream-Master** [comment]
Fixed 10k 30k and 60k cells recipes

**Comment by Drobac** [comment]
The recipes need a fix again
atm its for 30k: 1 bucket IC2 coolant 3x 10k cells and 6 tin plates
                 60k: 1 bucket IC2 coolant 3x 30k cells and 8 tin plates.
The recipes dont work as the 10k and 30k cells are unstackable so the recipe is invalid.

Suggestion: 30k 2 buckets IC2 coolant 1x 10k cell and 6 tin plates
                    60k 4 buckets IC2 coolant 1x 30k cell and 8 tin plates

**Comment by Dream-Master** [comment]
Ok i will add two new items in the core Mod to fix this issue

**Comment by Dream-Master** [comment]
Added in the Core Mod version 0.9.25.
Fixed with the new Update.

**Comment by Dream-Master** [comment]
Done
