### ISSUE TITLE
Superconductor dusts mixing

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3440]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
i'm working at superconductor dusts automation, and i mentioned a little mistake. Every supercond dust except LuV can be made with circuit 2, but LuV one need circuit 3.

Why is this important: It has oxygen in recipe, so all of superconductors which need oxygen(mv, hv, luv) need to be mixed in special mixer with oxygen supplied. This circuit3 differese forses us to make 2 mixers with oxygen. Not nice.

Suggestion: replace circuit3 in LuV recipe with circuit2.
![2018-08-11_21 45 14](https://user-images.githubusercontent.com/25028786/43995052-df3170ec-9daf-11e8-955f-2ecaad93c564.png)
![2018-08-11_21 45 19](https://user-images.githubusercontent.com/25028786/43995053-df53b012-9daf-11e8-9aee-60b986c91f07.png)

**Comment by Dream-Master** [comment]
i remeber there was an issue maybe i cahnge all to 3

**Comment by Dream-Master** [comment]
Ok this not working guess the superconductor overrides itself.

**Comment by Dream-Master** [comment]
@Cinobi ingredients are same so it not working
