### ISSUE TITLE
Wireless Setup Kit

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3441]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft the Wireless Setup Kit (ItemID: 4388)
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/22825059/43996924-213b486e-9dce-11e8-89c9-9b2ddeca21e2.png)
![image](https://user-images.githubusercontent.com/22825059/43996933-2ba2d7ae-9dce-11e8-9469-13d28fa250f6.png)

#
#### What do you suggest instead/what changes do you propose?
Replace the Bright Illuminated panel (4389:160) with an Illuminated panel (4387:180)

the bright version is just unnessesary.

**Comment by Bryfer** [comment]
Other recpies with same issue

Network Tool (4370)
ME Gas Storage Monitor (6720:18)
ME Storage Monitor (4387:400)

Also oversee and remove? the recipies using an dark illuminated panel
Network tool (4370)
ME Gas Storage Monitor (6720:18)
ME Storage Monitor (4387:400)

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Network too use all illuminated panels (ore dicted)
ME Storage Monitor ordicted now
Gas item i cant find.

**Comment by boubou19** [comment]
did you tried ME fluid storage monitor?

**Comment by Dream-Master** [comment]
@boubou19 this one ?
![image](https://user-images.githubusercontent.com/2970688/44085707-9e651566-9fba-11e8-8fe6-0955176c9837.png)

not used in any recipe
