### ISSUE TITLE
TNT and iTNT quests

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#3442]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
The iTNT quest is locked behind the TNT quest - this forces you to craft a stack of normal TNT before you can complete the iTNT quest, wasting your materials. (the only valid purpose of the implosion compressor before HV are industrial diamonds for MV+ lathes - easily craftable with powderbarrels => when you realistically need TNT you can already craft iTNT, making TNT obsolete) 

#### What do you suggest instead/what changes do you propose?
Putting the iTNT quest after the implosion compressor quest - removing the requirement of crafting a stack of lesser TNT.

**Comment by Dream-Master** [comment]
allready fixed in 2.0.4.7 and 2.0.4.8
