### ISSUE TITLE
Nuclear reactor quests

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#3443]
Which modpack version are you using?
2.0.4.6

What did you try to do, and what did you expect to happen?
The quest "Increasing the capacity" (retrieve 6 reactor chambers) id:195 is gated by the quest "Double the fun" id:198 which requires you to craft double MOX and uranium fuel rods - locking it behind Tier 2 planets and plutonium - but you can (and most likely will) craft a 6-chambered thorium reactor right after getting to the Moon (Tier 1).
Additionally reactor chambers are used in the reactor recipe - so most people will craft the first reactor and 6 additional chambers in the same batch.

What do you suggest instead/what changes do you propose?
I suggest placing the reactor chamber quest at the same level as the first fuel rod and reactor component quests - gate it behind the main reactor block quest.

**Comment by Dream-Master** [comment]
@RaggedCaster a bit more ifos please. What you suggest exactly?

**Comment by RaggedCaster** [comment]
updated - accidental doubleposting

**Comment by alphaNOVAircraft** [comment]
@Dream-Master he suggests changing the requirement for the quest that wants you to craft 6 additional reactor chambers (to build one full size reactor). Right now you need a few quests (gated behind mars) just to unlock the quest. But everybody builds a full size reactor anyways. So just change the requirements to only need the reactor mainblock quest

**Comment by Dream-Master** [comment]
ok
