### ISSUE TITLE
Suggestion: Make Kanthal coils a bit earlier

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3447]
#### Which modpack version are you using?
2.0.4.8
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I expected Kanthal coils (tier 2 coils, 2700K heat) to be available earlier than nichrome (tier 3 coils, 3600k).
#
#### What happend instead? (Attach screenshots if needed)
The only thing gating Nichrome coils is having kanthal coils, so the instant you can make kanthal coils you can make nichrome, so there's no point to ever using kanthal aside from to make your first nichrome coils.
#
#### What do you suggest instead/what changes do you propose?
Making Kanthal need 480 EU/t to smelt in a blast furnace, but NOT require a vacuum freezer.
This gates Kanthal behind finding mica, having a 480 EU/t blast furnace, and having an MV fluid extractor (For molten aluminium, to make the actual coils). This puts them at mid MV. Nichrome can stay the same, putting them at HV.
This establishes cupronickel coils as LV coils, kanthal as MV coils, and nichrome as HV coils.

**Comment by Dream-Master** [comment]
no i won't change this. you don't need this coil before hv and it was fine so long time. We have more important stuff to change than this.

**Comment by richardhendricks** [comment]
The other option is to push nichrome coils further up the tree.

**Comment by Dream-Master** [comment]
Sencond we did, we put nichrome further up the tree. HV vac freezer and ebf recipes take a bit longer.

**Comment by henrydukepickle** [comment]
would still love to see this, MV is too short
