### ISSUE TITLE
Suggestion: Alternate Radon Quest

### ISSUE THREAD

**Issue by RaggedCaster** [GTNewHorizons/NewHorizons#3449]
#### Which modpack version are you using?
2.0.4.8

#
#### What did you try to do, and what did you expect to happen?
There are 2 ways of getting Radon:
1. From 8 Pu239 and 1/9 U238 - a quest exists for this and it is required for progression.
2. From decayed Radium 226 (GT++) - obtained from sifting U238, pitchblende and uraninite ores in the sifter. - does not have a quest.
#### What do you suggest instead/what changes do you propose?
I suggest adding an alternate quest for Radon production using this process. (Mine some U238 ore, sift it, wait for Ra226 to decay and electrolyze it).

**Comment by Dream-Master** [comment]
sure will add.

**Comment by Dream-Master** [comment]
how decay works ? just put them in a chest and wait? @RaggedCaster

**Comment by RaggedCaster** [comment]
it works only in player inventory (no automation) and gives the player rad poisoning unless wearing the hazmat suit
currently there are 2 issues with it:
1. It happens instantly (should take 4500s)
2. The undecayed Ra226 does not stack (it should).
This is on 2.0.4.8

**Comment by Dream-Master** [comment]
make a issue at gt++ side.thanks @RaggedCaster

**Comment by Dream-Master** [comment]
i new version it takes time
![image](https://user-images.githubusercontent.com/2970688/44033054-70ecfee8-9f09-11e8-9845-50e91ab313d4.png)

**Comment by Dream-Master** [comment]
Guess it not stack because of decaying
