### ISSUE TITLE
Overclocker Upgrade not craftable

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#345]
The assembling machine doesn't start.
The problem is probably because you used the 30k coolant cell, but if you craft one of those, it automatically gets metaID 1.

**Comment by Dream-Master** [comment]
I will check it too.
btw i will open a issue for help me changing the new ic2 values in the config for the nuclear reactor.
Hope i can do the Update today or tomorrow because on the weekend my sister comes visit me and i not have any time to work on it.

**Comment by Dream-Master** [comment]
Chnage all meta ids to 1

**Comment by Dream-Master** [comment]
ok fixed
