### ISSUE TITLE
Conflicting/Unusable recipes in Large Chemical Reactor

### ISSUE THREAD

**Issue by wingez** [GTNewHorizons/NewHorizons#3450]
Tried to produce some of that sweet polydimethylsiloxane in the multiblock chemical reactor using this recipy:
![image](https://user-images.githubusercontent.com/12143465/44008173-963bf104-9ea0-11e8-9009-85b0cf8ca914.png)

I was however dissapointed when it only produced some useless hydrogen and CO2 instead. 
What I assume happens is the reactor chooses this recipe instead:

![image](https://user-images.githubusercontent.com/12143465/44008227-37b44978-9ea1-11e8-943e-77829260205d.png)

Suggestions:

- Remove the darn CO2 recipe. Who would use the multiblockreactor for hydrogen and CO2??
- Add circuits to all recipes in the LCR (GT5U issue)
- When there is a circuit in one of the input buses force the LCR to only use recipes with that circuit. (GT5U issue)

**Comment by Sudoloo** [comment]
this might be more of a gt++ issue? anyways, although it sounds like a giant pain in the ass for now, id try administering a single bucket of the dark blue one at a time, perhaps using redstone logic (if detecet output product; then input new bucket). its a pain in the ass, but thats what you can do till it either gets fixed or made more workable

**Comment by Prewf** [comment]
This has been reported before, but never fixed apparently: https://github.com/GTNewHorizons/NewHorizons/issues/3125

Simple fix would be to add a programmed circuit for the water+methane LCR recipe. Maybe programmable circuit #11? To make it consistent with the single block recipe.

@Sudoloo unless alkalus made the large chemical reactor (i don't think he did..), this isn't a gt++ issue

**Comment by Dream-Master** [comment]
All simple chemical recipes from gt/gt++ are in the LCR too.
You can make own recipes only for LCR and for single block but when you not define it it will add in both devices.

**Comment by Prewf** [comment]
Can you just change it to require a prog 11 chip and keep the LCR recipe? Methane + water making hydrogen isn't a bad recipe. I use it myself in my base because it gives good throughput compared to electrolyzing water. Just because someone doesn't see a use for it doesn't make it useless.

**Comment by Dream-Master** [comment]
sur can add a recipe especial for LCR only.
