### ISSUE TITLE
Make cracked MC warning quest available immediately

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3451]
See title

**Comment by richardhendricks** [comment]
I'll take care of it.

**Comment by Dream-Master** [comment]
ore you mean oil cracker ?

**Comment by Anarack** [comment]
Cracked as in pirated and or offline.

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
stupid me :/

**Comment by Dream-Master** [comment]
i dont want to let this be the first quest. If people so stupid to steal mc an complain here that bq not working they have to be banned :)
