### ISSUE TITLE
Process time

### ISSUE THREAD

**Issue by Zenthae** [GTNewHorizons/NewHorizons#3453]
![java_2018-08-13_22-55-41](https://user-images.githubusercontent.com/32647899/44057647-1766307c-9f4c-11e8-8a2b-f234e3f90113.png)
what's the meaning of this ? we must wait 3 days to make a craft ? there is ways to improve process time in this pack ?

**Comment by richardhendricks** [comment]
What ingot is that?  Any process can be sped up by 2x by increasing the tier.  IE, this will go 2x faster at HV.

**Comment by Anarack** [comment]
Overclocking with higher tier machines. For example a UHV extruder would do this in 512 seconds, which is doable if you have access to infinity tier material.

**Comment by Zenthae** [comment]
it's neutronium ingot

**Comment by boubou19** [comment]
neutronium pickaxe isn't worth anyways butif you want a reasonable process time make an IV extruder it will take 9 hours or make an LuV extruder and it will take 4 and half hours
