### ISSUE TITLE
Making gallium easier to get

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3455]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Right now, gallium is too hard to get from sphalerite ore. Yes, there are easier ways later on in the game, but having only a 25% chance to get gallium is ridiculous. Ive processed multiple stacks of sphalerite ore only to get four tiny gallium dust. I think that gallium should be either an outright 100% drop or 75%. Needing to rely on luck just to get a single tiny dust does not get easier with the tier you are in, it just makes it more annoying. 

I suggest locking the problematic consumers of gallium (smd diode and transistor) behind ev assemblers and moving the mv quest for smd parts to ev as well

**Comment by richardhendricks** [comment]
Just buy some with XP buckets until you can get to HV and use the HV macerator.  NEI "XP Bucket" and hit Use.

**Comment by Prewf** [comment]
What are you doing pre-HV that requires all this gallium anyways? I'm pretty sure I lasted until the moon with less than a quarter stack, considering how many diodes you can make with a single gallium dust.

**Comment by WizardSleve280** [comment]
i need the gallium for all of the mv circuits that are needed for the ev circuits

**Comment by Anarack** [comment]
Gallium sources up till moon by tier for references
 
Gallium pre HV
From sphalerite ore: 0.027 dust per ore, sucks but eh
small zinc ores: 0.11 dust per ore
xp berry: 32 berry per tiny  288 per dust

HV with pulverize
From sphalerite ore: 0.227 dust per ore, sucks much better with basically 10x yield
small zinc ores: 0.21 dust per crushed
xp berry: No improvement

HV Moon
Bauxite ore: 0.2 per ore, less than spahalerite but can be obtained in larger amounts as it is a primary ore in a vein.
From sphalerite ore:  No improvement
small zinc ores:  No improvement
xp berry: No improvement

**Comment by WizardSleve280** [comment]
and if you were to use only xp buckets to get even 8 regular gallium dust, you would need 576 buckets of xp. Or you can try your hand at pure luck based electrolyzing

**Comment by WizardSleve280** [comment]
i do agree though that once you get to the moon, bauxite fixes this problem. But there needs to be better yield from pre moon stuff because its too impractical to get said dust before then

**Comment by Bluebine** [comment]
You really don't need much gallium, though.
1 gallium dust is enough to make 2 stacks of wafers, which, if you play smart with them, is enough to make it clear through MV and get to HV (you can make 6 stacks of diodes if you do it the most efficient way, enough for 3 stacks of MV circuits, and still have 32 wafers left, which is enough to make several HV circuits and get that HV macerator+a power source for it). Once you're HV, you can get that pulverizer, which gives you a LOT more gallium, allowing you to easily mass-produce wafers for your HV-IV circuits.
I don't think anything needs changed. On average, you'll need 36 sphalerite ore to get 1 gallium dust. That's not awful. Even if you're really unlucky, a stack or two of ore is still not unreasonable to get (you're expected to get 36 of TWO sporadic ores just to make your bricked blast furnace, with just bronze tools! and you'll probably want 2 or 4 of those, so double or triple that number)

**Comment by richardhendricks** [comment]
You can also purchase wafers from the Coins tab, 16 at a time.  More than enough to get you there.

**Comment by WizardSleve280** [comment]
im not talking about using them for wafers. Im talking about using them for the smd parts

**Comment by Bluebine** [comment]
SMD diodes and transistors (the only ones that need gallium) aren't necessary until after the Moon, when you've got bauxite and can easily get lots of gallium.

**Comment by Anarack** [comment]
That is a problem I have with smd parts..., they are available much too early and there is a quest pointing you at them when using them at that point, especially the galium heavy ones are a trap basically.

**Comment by WizardSleve280** [comment]
i was under the impression that they were required, even when looking through nei

**Comment by Anarack** [comment]
No, only the high tier ones, which having a early mv quest for them does not help.

**Comment by Bluebine** [comment]
I agree on the SMD parts. I think that that quest shouldn't be available until the nanoprocessor quest in EV. 

SMD parts aren't actually NECESSARY until you start getting into nanoprocessors.

**Comment by WizardSleve280** [comment]
ill edit the post then to suggest changing the recipe/quest to require an ev assembler and to move the smd parts into the ev questline

**Comment by Anarack** [comment]
Though the smd resistors and the capacitors are nice to use, but the other no on how much gallium they use. Maybe keep those 2?

**Comment by Bluebine** [comment]
@Anarack has a good point. The SMD capacitors and resistors don't actually take any gallium, and are arguably cheaper to make even at MV.

I'd change the SMD parts quest to ONLY be those 2, and have the SMD diodes and transistors have a quest after the EV circuit assembler.

**Comment by WizardSleve280** [comment]
it would make sense to keep the two smd parts in mv since there is an actual benefit, but with the other gallium consuming smd parts, it just makes an already hard to come by resource even more used

**Comment by Anarack** [comment]
Should we bump up the diode/transistors in voltage to discourage even looking at them till they are required to fully prevent confusion in case the quest is missed or somthing?

**Comment by WizardSleve280** [comment]
@Anarack i suggested in my edit to just make the recipe ev tier

**Comment by Anarack** [comment]
I was talking about crafting voltage requirements but ya that should be done.

**Comment by WizardSleve280** [comment]
isnt that what making it ev tier is? bumping up the voltage requirement

**Comment by Prewf** [comment]
I'd cast my vote for leaving the actual recipes as is. Just move the quest in the questbook. Having SMD quests in MV was definitely too early.

**Comment by Dream-Master** [comment]
ok I make the smd stuff more expensive in eu/t and move quest

**Comment by Bryfer** [comment]
SMD parts is used to make the circuits cheaper, meaning it will require more kinds of materials, but less of everything else?
If you can't afford it, then keep using the old way

Don't change the recipes, that will just be annoying for EVERYONE who has it automated or partly automated already
If anything move part of the quest, but I think it's fine as is.

**Comment by Prewf** [comment]
>Don't change the recipes, that will just be annoying for EVERYONE who has it automated or partly automated already

Yep, I'm in this category :\ @Dream-Master The recipe doesn't need to be changed. I wish you weren't so hasty about changing stuff like this. This thread went 0-60 from "gallium is too hard to get" to "lock SMD components behind EV" wth?

**Comment by Dream-Master** [comment]
sure i can let it like it is. But if i keep the recipes i will not move the quest. Make no sense.

**Comment by richardhendricks** [comment]
We can put some text in the quest to say "Be sure to check how much gallium you have available.  It might not be worth it to use SMD diodes and resistors until you have a steady supply from bees or bauxite ore."

**Comment by Highbeam** [comment]
I don't understand why this is such a huge issue.  Having multiple options has always been the best part of this pack. Educating early with the questlines is also very nice.  Tweaking the text on the quest should be sufficient. The quest currently reads:

"Surface-mount devices are more advanced circuit parts. They will be needed for higher tier circuits and are cheaper to craft than basic capacitors, transistors, diodes and resistors. You need an Advanced Assembler and some polyethylene."

Change to: (and to keep it in MV):

"Surface-mount devices are more advanced circuit parts. They will be needed for higher tier circuits and are cheaper to craft than basic capacitors, transistors, diodes and resistors. **You need an Advanced Assembler, polyethylene and a good source of Gallium.**"

If you mention the bauxite ore or the moon in the text then I would suggest moving it to the HV quest area.

NEI gives more than enough info and plenty of sources for Gallium, shouldn't need to be drip fed on quests I believe?

**Comment by Highbeam** [comment]
Dream your commit says "It might not be worth it to use SMD diodes and resistors until you have a steady supply from bees or bauxite ore.".

It's diodes and **transistors** (**not resistors**) as I pointed out earlier :)

**Comment by Dream-Master** [comment]
oh ok will fix next release.
