### ISSUE TITLE
Oil mode scan result in Moon

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#3457]
#### Which modpack version are you using?
2.0.4.8

#### What did you try to do, and what did you expect to happen?
Scan helium-3 in moon
#
#### What happend instead? (Attach screenshots if needed)
and i got this
![20180814222144](https://user-images.githubusercontent.com/25171639/44097499-7c8a653a-a010-11e8-88f4-cfa77694f0b9.png)
it looks like only happen in Moon and work fine in overworld

**Comment by Dream-Master** [comment]
@richardhendricks @bartimaeusnek any idea?

**Comment by richardhendricks** [comment]
Will take a look at it.

**Comment by richardhendricks** [comment]
The prospector oil window uses hardcoded fluids because it selects its own colors.  Adding a fluid hashmap now with all our new fluids on it.

**Comment by richardhendricks** [comment]
Materials.x.getMolten()

**Comment by richardhendricks** [comment]
Fixed issue and added feature that fluid size is represented visually in the chunk. It tried to do this before, but pretty poorly IMO. 

OW
![2018-08-28_00 07 57](https://user-images.githubusercontent.com/1214811/44701963-aeb7f180-aa56-11e8-9868-8c65ad6cab02.png)
![2018-08-28_00 09 43](https://user-images.githubusercontent.com/1214811/44701964-aeb7f180-aa56-11e8-8f67-f26b81bf5cd1.png)

Moon
![2018-08-28_00 15 28](https://user-images.githubusercontent.com/1214811/44702129-7a910080-aa57-11e8-8815-2b786d64d05f.png)
