### ISSUE TITLE
Totally unnecessary recipes using the trophies

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3458]
These are more for fun than real use.  I would gate at minimum to MV, in an assembler.

Bat trophy + golden carrot -> extended potion of night vision

chicken trophy + feather -> extended potion of flying

Cow trophy + flint knife -> 64 leather

Sheep trophy + vanilla shears -> 64 wool

wither trophy + vanilla iron pick -> 64 blocks of coal 

Any other fun ideas?

**Comment by richardhendricks** [comment]
Yeah that's the idea.

**Comment by Dream-Master** [comment]
ok sure

**Comment by DoomSquirter** [comment]
bat trophy + stick == neutronium?  I WILL BE RICH!

bats can fly, chickens cannot.  bats should give flight potion.  but only flight potion is bm.  no?

meh I have no real ideas.  remember that a lot of these trophies you can click them and stuff is given to you at low quantities.  if you so desired, you can actually automate them.

**Comment by MineAnPlay** [comment]
Better to make the non potion ones in the Cutting Machine. Also maybe add Assembler recipes that don't consume the resources but require other items? Like you need 4-8 wheat with Cow Trophy to make 1 Leather etc.

**Comment by Dream-Master** [comment]
When you clicking Trophy from Cow you got leather for free each 5 mins or so.

**Comment by Dream-Master** [comment]
sure
