### ISSUE TITLE
Unable to make the Blank fuel tank for the Small fuel canister

### ISSUE THREAD

**Issue by XXxinsanityxX** [GTNewHorizons/NewHorizons#3459]
#### Which modpack version are you using?

# 2.0.4.8
#### If in multiplayer; On which server does this happen? 

# NA
#### What did you try to do, and what did you expect to happen?

# Tried to craft small fuel canisters, one of the components for it is missing a recipe the blank fuel tank
#### What happend instead? (Attach screenshots if needed)

# Nothing
#### What do you suggest instead/what changes do you propose?
Add recipe back

**Comment by Dream-Master** [comment]
You right the recipe is missing. Will check.
