### ISSUE TITLE
GT Fluid solidifier molds

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#346]
If possible, it would be nice to have solidifer molds for more GT parts as it can be faster then some of the other machines

**Comment by Dream-Master** [comment]
Need new Mold forms for it.

Screws, Rings, Rods and Wires.

**Comment by Dream-Master** [comment]
Maybe we can add this to GT code.

**Comment by Dream-Master** [comment]
later

**Comment by Dream-Master** [comment]
@Drobac Did we really need Screw Molds or Stick mold etc?

**Comment by Dream-Master** [comment]
Maybe add some day.

**Comment by Dream-Master** [comment]
Added
