### ISSUE TITLE
Suggestion: Useless Smog Effect

### ISSUE THREAD

**Issue by LinaMachina** [GTNewHorizons/NewHorizons#3460]
As it stands, the only real effect of pollution is status effects.  These are interesting, but they don't convey the same sense of dread that I feel smog from industrialization should provide.  I suggest a visual representation at the 'smog' level of pollution, that causes a bedrock fog effect while in the polluted chunks. 

This will also make it somewhat easier to see how far your pollution is destroying the world before scanner technology.  More 'harmless' visual effects might encourage more people to keep pollution on.

**Comment by richardhendricks** [comment]
Should be possible to add some particle effects around you , with different colors and amounts to reflect level of pollution.  At higher levels you already get nausea, blindness, hunger, acid rain etc damage.

**Comment by draknyte1** [comment]
This already exists in the mainline branch of GT5u.. just go copy it?

**Comment by Dream-Master** [comment]
@draknyte1 can you show me the commits?

**Comment by draknyte1** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/commit/911a80752930d6207fc0b850f3ccf8b3da05b0a5

I think there is another one too~

**Comment by Dream-Master** [comment]
If you found the other commit please post it here. Thanks
@draknyte1

**Comment by richardhendricks** [comment]
Looks like we have it, but commented out

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Client.java

Looks like @Technus commented it out a year ago.

I wasn't really thinking of a smog shader that would change the color of everything, I was think more along the lines of generating some colored particles in the air with different colors/density based on pollution level.  Something that would give a visual indicator before each physical effect occurs.  IE white particles before blindness, brown before nausea, black before ???.  Nothing too fancy, just like a EBF's particles but scattered in air a few blocks.

**Comment by Dream-Master** [comment]
@Technus
//TODO less bad
Well do noting realy bad :P

@richardhendricks
any idea how we can do it less bad :/?

**Comment by Highbeam** [comment]
bump :)
would love to have some consequence and see fog if we have bad pollution

**Comment by richardhendricks** [comment]
Will be covered in 5160
