### ISSUE TITLE
Seismic Prospectors changes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3462]
I am going to be implementing some changes to the seismic prospectors since we have revamped the hand-held basic prospectors.

- The LV, MV, and HV variants will be "advanced" prospectors.
- Advanced prospectors will report exact ores found in each chunk.
- oil field behavior will remain unchanged.

LV - 5x5 chunks, 
MV - 7x7 chunks
HV - 9x9 chunks
EV - 11x11 chunks

**Comment by Dream-Master** [comment]
Good idea.

**Comment by richardhendricks** [comment]
EV Advanced seismic prospector output

![2018-08-15_01 31 26](https://user-images.githubusercontent.com/1214811/44134532-ffc4252a-a02a-11e8-9bfe-f9a8d3876088.png)
![2018-08-15_01 31 29](https://user-images.githubusercontent.com/1214811/44134533-ffd2b18a-a02a-11e8-9aeb-6f8e96a0891c.png)
![2018-08-15_01 31 32](https://user-images.githubusercontent.com/1214811/44134534-ffe200fe-a02a-11e8-9ff9-fa0d406ff701.png)
![2018-08-15_01 31 43](https://user-images.githubusercontent.com/1214811/44134535-fff14488-a02a-11e8-8f23-04db06d6ff60.png)
![2018-08-15_01 31 45](https://user-images.githubusercontent.com/1214811/44134536-0000cef8-a02b-11e8-8257-66e89a07b098.png)
![2018-08-15_01 31 47](https://user-images.githubusercontent.com/1214811/44134537-000eb658-a02b-11e8-80e8-abce7564762b.png)

LV Advanced Seismic Prospector output
![2018-08-15_01 33 00](https://user-images.githubusercontent.com/1214811/44134591-30628fb4-a02b-11e8-90eb-e6aab9d3b984.png)
![2018-08-15_01 33 03](https://user-images.githubusercontent.com/1214811/44134592-30723a9a-a02b-11e8-92e2-5b1b98f7323f.png)

**Comment by richardhendricks** [comment]
Moon scan

![2018-08-15_01 40 00](https://user-images.githubusercontent.com/1214811/44134849-252d1a5a-a02c-11e8-9282-8a2ea49030c2.png)
![2018-08-15_01 40 04](https://user-images.githubusercontent.com/1214811/44134851-253cdd64-a02c-11e8-9c6e-eb26bc0c7976.png)

**Comment by richardhendricks** [comment]
Nether
![2018-08-15_01 42 48](https://user-images.githubusercontent.com/1214811/44134960-9c88d3e6-a02c-11e8-9803-ae0210bf93f3.png)
![2018-08-15_01 43 08](https://user-images.githubusercontent.com/1214811/44134961-9c97eae8-a02c-11e8-9f06-e7c611efd7dd.png)

**Comment by richardhendricks** [comment]
- [ ] Use all consumables
- [ ] Verify conversion recipes
- [ ] Verify creation recipes

**Comment by richardhendricks** [comment]
Code fixes completed.  Still needs update for questbook quest.

**Comment by richardhendricks** [comment]
Changelog - 
All seismic prospectors are now advanced seismic prospectors that return precise locations for ores.

**Comment by richardhendricks** [comment]
Quest updated.

**Comment by 0lafe** [comment]
Why increase the range? I found it was already pretty high to begin with. And does "Advanced prospectors will report exact ores found in each chunk" mean no more failed chunks?

**Comment by richardhendricks** [comment]
The way they used to work, they only reported the aggregate at each distance, so weren't very useful.  I moved that over to the basic portable prospector when I fixed it. 

Advanced prospectors are way more investment and hassle than other methods. The range is technically a downgrade from the old one, since it gives precision information.

Never had failed chunks with any of the seismic prospectors, and considering the # of steps to use it, I'm ok with it.

**Comment by Dream-Master** [comment]
@Technus 
   //TODO less bad 
Well do noting realy bad :P

@richardhendricks 
any idea how we can do it less bad :/?

**Comment by richardhendricks** [comment]
I think you meant to put that on the pollution ticket? 💃

**Comment by Dream-Master** [comment]
yea was in the wong issue

**Comment by richardhendricks** [comment]
This is what the old advanced prospector output looked like

![image](https://user-images.githubusercontent.com/1214811/44161517-311dda00-a083-11e8-814c-b626d62b955f.png)
