### ISSUE TITLE
Better Questing Revision Issue

### ISSUE THREAD

**Issue by Cockswain** [GTNewHorizons/NewHorizons#3464]
#### Which modpack version are you using?
GT new horizons 2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
LAN, as client
#
#### What did you try to do, and what did you expect to happen?
Complete quests in an orderly and sane fashion.
#
#### What happend instead? (Attach screenshots if needed)
Quests periodically becoming incomplete, even after completion and being buried under several other completed quests ahead. TL;DR I am losing quest data. I am not in a party with the host. It's important to note that the host isn't having any of these issues.
https://imgur.com/a/jHplOuq Here is an image of the issue.
#
#### What do you suggest instead/what changes do you propose?
Quests should not be able to be incomplete if quests ahead of it in the quest line are completed.

**Comment by Dream-Master** [comment]
yea known bug some times wehn update and reload.
