### ISSUE TITLE
Vacuum Freezer Bug

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3465]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
I tried to put Universal cell with oxygen in vacuum freezer
#
#### What happend instead? (Attach screenshots if needed)
I got ic2,cooliant cell in input hatch -_-
#
#### What do you suggest instead/what changes do you propose?
idk

**Comment by Dream-Master** [comment]
did the vac freezer need coolant? I heard it the first time.

**Comment by Dream-Master** [comment]
@barsikus007 i never know vac freezer need oxygen. Can you make a video about this issue please.

**Comment by draknyte1** [comment]
Universal cells are the issue I bet. 

Just use an Air Intake Hatch for your air cooling needs.

**Comment by barsikus007** [comment]
@Dream-Master Oh I just needed to make LOX cell, and I used old recipe

**Comment by barsikus007** [comment]
@Dream-Master we still have easy way to get cooliant

**Comment by barsikus007** [comment]
It's cheaty way to get cooliant

**Comment by barsikus007** [comment]
yes, so no bug?

**Comment by draknyte1** [comment]
Universal cells are all the same in every recipe. Because the fluid is stored in nbt and 99% of things ignore the nbt.
