### ISSUE TITLE
New mod request: AE2 Stuff, Enchiridion2

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#347]
**AE2 Stuff**
http://www.curse.com/mc-mods/minecraft/225194-ae2-stuff
Additional machines for AE2. Especially, the crystal growth chamber.
Reason: Even with 8k machines, an autoclave needs several seconds to craft a **single** pure crystal. Normally, you throw an entire stack of seeds in a pool of water, and it grows **simultaneously**. It needs the exact same time for 2, 3, 10 or even 20 Stacks. Especially with our recipes, the autoclave is not an option here.

Edit: Just to make one thing clear, last time I used this chamber, it drained more power than 4 vanilla AE2 accelerators together. So it's not "for free". Especially with the x4 setting on AE2 power usage

**Enchiridion2:**
http://goo.gl/sFqGaj

Would be an awesome way to create an ingame wiki for the pack, and probably some lore-books for questlines.

**Comment by Dream-Master** [comment]
Will look inside this neext week.

**Comment by Dream-Master** [comment]
Done
