### ISSUE TITLE
GT++ Power Substation does not complete

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3470]
#### What did you try to do, and what did you expect to happen?
Updated to the latest version (**Edit: Version 2.0.4.8**), and noticed the substation had an unusually high eu/t cost, so I went over to check on it. The controller was in its OFF state and upon touching it, it all stopped working, to my dismay.

I then followed the directions in the questbook to re-make the power station:
1 EV energy hatch
1 EV dynamo hatch
Control Block (bottom, side-centered)
Maintenance Hatch
18 interior energy cells (**Edit: EV-tier**)
Substation Casings for the rest
(no HV or lower hatches were involved)
#
#### What happened instead? (Attach screenshots if needed)
The multiblock did not form, and so the control block's GUI was blank.
#
#### What do you suggest instead/what changes do you propose?
First, is anyone else having problems with the power substation?
If not, I'll gladly take advice on how to get it running again.
If so, I can post this to the GT++ issues page as well (but I'd rather not make a big deal if it's a setup issue on my end) (**Edit: posted to the GT++ issues page as well**)

**Comment by Bryfer** [comment]
Modpack version?
Where did you place all the hatches, energy in/out, maintenance, controller
Which tier are the hatches
Which redox do you have?

**Comment by NeroOneTrueKing** [comment]
Modpack version: 2.0.4.8 
EV Energy Hatch: side wall (not edge)
EV Dynamo Hatch: side wall (not edge)
Controller: bottom centered side edge
Maintenance Hatch: bottom centered side edge, opposite from Controller
EV Redox cells in the center (18 of them, 3x3 in two layers)

**Comment by NeroOneTrueKing** [comment]
Two screenshots to show the location of the controller and hatches:
![2018-08-17_00 24 26](https://user-images.githubusercontent.com/28197216/44249207-7aba1200-a1b4-11e8-8ebd-3fdd4900bd64.png)
![2018-08-17_00 24 32](https://user-images.githubusercontent.com/28197216/44249208-7b52a880-a1b4-11e8-9ba3-0f68356193fc.png)

**Comment by Bryfer** [comment]
What does it say inside the controller block?
Also did you hit it with a mallet?

**Comment by NeroOneTrueKing** [comment]
The controller block has a blank GUI (no writing or colours other than black and gray boxes) -- this is a known GT++ bug, and is stated in the included book that it is known and shouldn't be reported.

Hitting with a mallet does not turn it on, since the multiblock has not formed.
Doing repairs via the maintenance hatch does nothing, since the multiblock has not formed.

Have you got one successfully running in your world?

**Comment by Bryfer** [comment]
I got one running, but epsilon is still running 2.0.4.6
It is max sized (18 height)
EV tier stuff, and buffered dynamo (4A) instead of the 1a version


Im not sure if the structure has been modified in the new version, and I haven't heard anyone else having issues with it either (in 2.0.4.8)

**Comment by Dream-Master** [comment]
@NeroOneTrueKing please open up an issue on gt++ repo please.

**Comment by Wolozo7** [comment]
Can you add a muffler hatch to the multi?

**Comment by NeroOneTrueKing** [comment]
Adding an IV muffler hatch to the top-center of the mutiblock had no visible effect -- the muffler did take on the appropriate multiblock texture like the energy/dynamo/maintenance hatches already did, but the multiblock is still not forming.

**Comment by draknyte1** [comment]
Structure formation hasn't changed in months, so you're just building it wrong.

**Comment by NeroOneTrueKing** [comment]
draknyte1:
Okay, on further inspection, I think you're right that structure formation hasn't changed, and I am in fact building the thing properly, since the hatches are changing texture to match the multiblock. That wouldn't be happening if the multiblock was being assembled incorrectly, right? However, the problem remains that the multiblock is not operational, so I'd like you to take a look yourself in-game. Thanks!

**Comment by draknyte1** [comment]
I won't be doing any testing of anything for a while, due to real life circumstances.

Have you used your handheld scanner to get more info?
Have you copied the structure the same as another player who has it working?
Have you built it across a chunk border?
Have you looked at the information Multiblocks log to fml-server/client-latest.log when they try form?

**Comment by NeroOneTrueKing** [comment]
Thanks for telling me where the log was, that helped me find the bug that was introduced in the update:

in  GTplusplus/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/storage/GregtechMetaTileEntity_PowerSubStationController.java 
on line 270:
```
if(tier < 512) {
				checkMachineProblem("Energy hatch (tier " + tier + ") is too weak for cells (tier " + tOverallCellTier + ")");
				return false;
}
```

Note that HV power is tier 3, not tier 512.
