### ISSUE TITLE
Problem with Tainted Magic Wands

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3472]
#### Which modpack version are you using?
2.0.4.7
#

#### Problem 
 All Tainted Magic Wands can not be crafted since it's research isnt using the regular TC tags.
#

#### Solution 1
Change Reseach Key to ROD_warpwood / ROD_warpwood_staff.
#

#### Solution 2
Change code so that it requires RoD_WarpwoodGTNH / RoD_Warpwood_StaffGTNH to be completed.

**Comment by Zoko061602** [comment]
https://github.com/GTNewHorizons/GTNH-TC-Wands/pull/1

**Comment by Dream-Master** [comment]
@Zoko061602 Did you change anything else ?
