### ISSUE TITLE
irradiant reinforsed neutronium plate crafting issue

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3473]
#### Which modpack version are you using?
Epsi-one
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I'm trying to make this thingy i mention in a topic. It need mysterios crystal plate from gt: new horizons, but this plate can't be craftable anyway- all crafting methods gives u mysterios crystal plate from gregtech.
![2018-08-17_22 29 05](https://user-images.githubusercontent.com/25028786/44285269-5ec67700-a26d-11e8-920c-12806853d3d1.png)
![2018-08-17_22 29 10](https://user-images.githubusercontent.com/25028786/44285270-5f5f0d80-a26d-11e8-8f36-5b1cf6d713de.png)
![2018-08-17_22 29 13](https://user-images.githubusercontent.com/25028786/44285271-5f5f0d80-a26d-11e8-89a9-738ec0c05fa5.png)

**Comment by Dream-Master** [comment]
will oredict it sure.

**Comment by Dream-Master** [comment]
this recipe is fixed in newer version and changed to assembler and oredicted.
![image](https://user-images.githubusercontent.com/2970688/44285370-5407e400-a265-11e8-8213-84135bbb59ee.png)
