### ISSUE TITLE
[Suggestion] Add a new Endgame Material: Carbyne

### ISSUE THREAD

**Issue by ScreechamusPrime** [GTNewHorizons/NewHorizons#3474]
there is a recently discovered material made from carbon called carbyne. it is much, much stronger than even graphene. it is manufactured as a single chain of carbon atoms inside two carbon nanotubes, and it is 20 times stronger than steel. It would be pretty cool to see this as an endgame material in GTNH.

**Comment by Dream-Master** [comment]
@ScreechamusPrime any use for this high tier material ? Give us some suggestion please.

**Comment by bartimaeusnek** [comment]
graphene is already a material...

**Comment by ScreechamusPrime** [comment]
I haven't gotten very far due to the fact that I don't have a very long
attention span, but if I remember from the NEI recipes, the UMV, UHV etc.
voltages were all created from components that were put into a scanner
multiple times ( I don't know if this is different now, I haven't played in
a year) maybe carbyne could be used to create some of the components. It
could also be used for late game multiblock plating and as a TCon tool
material.

**Comment by 0lafe** [comment]
Would it be made from carbon though? Idk, sounds cool. Could easily be a rod for motors

**Comment by alphaNOVAircraft** [comment]
Its a bit weird to bring it into the game. You cannot have an actual ingot of a nanosized atom layer construction. Not sure if we can find a decent recipe for it (how to obtain it)

**Comment by Zoko061602** [comment]
For me this looks more like a Circuit Material, than a regular tool/machine material. I think it should be used as ZPM-UEV circuit part, since it seems to be a good semi-conductor.

**Comment by Jayjayx5x1** [comment]
while carbyne is neat, with the way it works I see no way that it is of any use in this modpack besides a neat battery but we already have plenty of batteries. As it is a single strand of atoms (1 dimensional) it doesn't have a lot of use, while I did read about how it can be used for the storage of energy (hence the battery suggestion) I don't see any real use as most of what it would be ideally used for, graphene would still do a better job as it is a 2 Dimensional structure thus has use in circuits etc.

**Comment by ScreechamusPrime** [comment]
anyway, this is a great pack, and I look forward to playing it a when I get
my computer fixed, and I hope the glass recipe was fixed (yes, that was the
farthest I've gotten, and how long ago I played) so I can finally see what
new features were brought in the game. I think my favorite parts about the
modpack are the realistic crafting recipes (e.g. the piston) and the total
playthrough length. I am also glad to see that it isn't only me playing
this modpack.

**Comment by draknyte1** [comment]
There's generally 500+ people online on the GTNH discord server. Join us, you'll never be alone.

**Comment by ScreechamusPrime** [comment]
awesome! I can't wait to try out these new features

**Comment by draknyte1** [comment]
I bet I can find a use for Carbyne. 👉🏻😎👉🏻

**Comment by draknyte1** [comment]
I assume however that you are talking about LAC and not Carbynes in general. LAC could definitely find some uses. 😌

https://en.m.wikipedia.org/wiki/Linear_acetylenic_carbon
https://en.m.wikipedia.org/wiki/Carbyne

**Comment by ScreechamusPrime** [comment]
i am talking about LACs

**Comment by ScreechamusPrime** [comment]
here is a suggestion for an in-game sort of index for found items (like
mixveins, bees, materials) it isn't finished but you can get the basic idea
of it.
