### ISSUE TITLE
recipe conflict world anchor

### ISSUE THREAD

**Issue by skynsun** [GTNewHorizons/NewHorizons#3475]
#### Which modpack version are you using?
v2.0.4.8
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Craft world anchor from railcraft on HV assembler
#
#### What happend instead? (Attach screenshots if needed)
you get diamond to obsidian chest upgrade.
#
#### What do you suggest instead/what changes do you propose?
Get My world anchor ^^

**Comment by skynsun** [comment]
But it work in solo if you pay attention to put item in the right order

**Comment by Dream-Master** [comment]
will add a circuit to it

**Comment by Bryfer** [comment]
Did you remove old mods/scripts/configs before updating the modpack?

**Comment by Dream-Master** [comment]
in dev pack yes but technic not do it automaticly when updating. Best would be to do a clean update each update and copy save folder and journeymap back if you play sp.
