### ISSUE TITLE
Inscriber

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3477]
#### Which modpack version are you using?
2.0.4.7
#

#### What do you suggest instead/what changes do you propose?
I think the inscriber from ae2 should be readded, since every other ae2 machine is obtainable.
I think it is not super OP, since you only save some Energy and I like the feature that you can rename things with it. 

#### Scripts
`recipes.addShaped(<appliedenergistics2:tile.BlockInscriber>,[
                  [<ore:plateTitanium>, <ore:gemFluix>, <ore:plateTitanium>],
				  [<IC2:itemRecipePart>,<gregtech:gt.blockmachines:604>,<IC2:itemRecipePart>],
				  [<ore:plateTitanium>, <ore:gemFluix>, <ore:plateTitanium>]]);`
#

#### AE Config
inscribe=
    oredictionary:plateDiamond ae2:ItemMaterial.EngProcessorPress
    -> ae2:ItemMaterial.EngProcessorPrint
	
inscribe=
    oredictionary:plateGold ae2:ItemMaterial.LogicProcessorPress
    -> ae2:ItemMaterial.LogicProcessorPrint 

#

**Comment by Dream-Master** [comment]
mh ok i check it.
