### ISSUE TITLE
T2 ore drilling rig tooltip says radius 64 but I think that's diameter

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3479]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
tooltip of T2 ore drilling rig says it's got a radius of 64 but I'm 99.99999% positive that is a diameter not a radius
I placed the rig about 30ish blocks from where I knew a certain ore vein was (was visible from surface) and after it was done and got to bedrock noticed that it skipped that vein entirely.  along with the veins surrounding it.
#
#### What happend instead? (Attach screenshots if needed)
my brain exploded
#
#### What do you suggest instead/what changes do you propose?
the problem might exist for other things like single block miners, etc as well.
would be nice to see correct ranges on tooltips

**Comment by Dream-Master** [comment]
@richardhendricks

**Comment by richardhendricks** [comment]
> my brain exploded

System working as intended. :)

Will take a look.  What is the preferred setting? I like radios, so that it is able to cover a wide area.

**Comment by DoomSquirter** [comment]
ummmmm.....

I am now beginning to think this might be a non issue and was actually user error.  

w/o doing an actual test against some area that was /cofh removeblocks stone, etc it'd be hard to test but I think this might be a chunkloader issue on my part.  whooops...  

I've setup my rig on mars and got a measly set of ores back, went back and chunkloaded a much wider area and now it's mining more ores in same spot.  when it's completely done I'll goto the corners and mine down and see what I find.  if it seems like it hit that 64 radius then yeah, 100% my stupidity at fault here....

**Comment by MineAnPlay** [comment]
Also that reminds me, we really need a larger chunk loader or make the miners load the chunks because the large size one requires a large area and without chunkloading it's not really worth it and staying afk for the miner is not an effective way to spend time.

**Comment by draknyte1** [comment]
GT things should not ever chunkload stuff, because it's really up to the machines owner to chunkload individually. It's been discussed previously and as is miners suck on large servers, lets not bundle in more shitty chunk loaders.. (making one that works properly is really fucking hard, I've tried)

**Comment by draknyte1** [comment]
It's been discussed several times since it was first implemented. It always ends with all devs involved agreeing that the solution exists already, so why reinvent the wheel?

**Comment by DoomSquirter** [comment]
I am going to close this issue as resolved.  actually there was no issue to begin with.

I setup t2 miner on mars and chunkloaded a large swath of land to ensure it'd be chunkloaded enough for it to run for full distance.  it dropped it's pipes and I went back to site, went to one furthest corner of area and mined down with hammer and found a couple small ores it had missed.  backed up a couple blocks (like about 6 or 10 maybe) and did the same thing and found holes where small ores were probably.  I didn't find a large hole to signify a entire vein but I feel comfortable enough thinking that it was chunkloading issue the entire time and that, the radius of 64 is the actual radius not the diameter.

**Comment by richardhendricks** [comment]
Confirmed in code, radius for T2 is 64 blocks.

**Comment by DoomSquirter** [comment]
sorry I made you look.  lol  wasn't intentional but hey, confirmation is good, right?  right?
