### ISSUE TITLE
New decoration mod: ZTones

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#348]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x

**Comment by Namikon** [comment]
This has my vote. I was going to suggest it, but I forgot. Sadly he added tools to dungeon loot, and I think that some of those are considered OP. But since you can't craft them... Need to be verified. I will install this in my local client and check what it does

**Comment by Namikon** [comment]
Ok, all items can be deactivated, except the flat lamps and the booster pad. Flat lamps probably need a new recipe, as the default recipe yields 16 lamps for 1 glowstone (dust!). The booster recipe needs 2 blocks of redstone and yields 9 booster blocks. When placed, you get a 2 second buff with speed 4.

Regarding the other items:
**MSG Pill** - Gives you 5 seconds of hunger (Why would anyone ever need this..?)
**Mini Coal/Charcoal** - Actually, a nice idea. One coal can smelt 8 items, and just when you start your game, you probably want to waste less coal. Not OP in any way.
**Ofanix** - Enderpearl, LavaBucket, WaterBucket, crafting table and a diamond. A portable cobblegen and mobile crafting table; To be honest, a very usefull item. Uses vanilla techniques, so nothing OP detected here either
**Totem Tool** - Needs to be disabled via config. Turns (Vanilla) ores into their block variant. (Diamond ore > diamond block etc)
**Splat axe** - One-hits slimes. Probably OP too, as we have infernal slimes and that way they would be a bit too easy. However, it is a non-craftable dungeon loot so... I won't mind having one of those. It's not infinite either
**Terrain eater** - Places torches on right-click, and is able to destroy mundane blocks very quickly (Stone, grass, dirt) A very nice dungeon/chest find; But might be overwritten by Iguanas
**Diamond Zane** - Useless and probably will be overwritten by Iguana's.

For the chest drops, I examined the source code, and these are the drop-rates, drop count and chest hooks for the items: (Rarity: GoldenApple has 1, Iron Ingot has 100)

**DiamondZane**
LootTable: DungeonChest
Min/Max: 1 / 2
Rarity: 1

**Ofanix**
LootTable: pyramidDesertyChest
Min/Max: 1 / 1
Rarity: 1

**TotemTool**
LootTable: pyramidDesertyChest, pyramidJungleChest
Min/Max: 1 / 1
Rarity: 1

**Hunger-Pill**
LootTable: pyramidJungleChest
Min/Max: 1 / 2
Rarity: 1

**SplatAxe**
LootTable: mineshaftCorridor
Min/Max: 1 / 1
Rarity: 1

**TerrainEater**
LootTable: villageBlacksmith
Min/Max: 1 / 2
Rarity: 1

**MiniCharcoal/Coal**
LootTable: villageBlacksmith
Min/Max: 2 / 2
Rarity: 2

**Comment by Dream-Master** [comment]
I tested the mod a bit.
The Ofanix is very OP, It is a infinite source of Cobblestone. You never will using the gt ones
The Booster is so fast and the original recipes so cheap that you can Build road with it.
The Lamps i have to make more expensive.
The tools have a high durability and if you found some you can  use them very long (op too)

**Comment by Drobac** [comment]
Just disable all the tools and the Ofanix, adjust the recipes for the booster and lamps. That should do it

**Comment by Dream-Master** [comment]
The Ofanix is needed for some tool so i can't disabled it

**Comment by Namikon** [comment]
http://forum.gtnewhorizons.com/showthread.php?tid=46

**Comment by Dream-Master** [comment]
So we  need only a Lich Quest to get the missing Item Ofanaix
