### ISSUE TITLE
Suggestion: Mixer recipe for Red Alloy

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/NewHorizons#3491]
#### Which modpack version are you using?
2.0.4.7
#
#### What did you try to do, and what did you expect to happen?
Thought it was possible to make Red Alloy dust (the cheap one) in the Mixer.
#
#### What do you suggest instead/what changes do you propose?
Have a mixer recipe that could have increased output over using the alloy furnace;
1 Copper Dust, 4 Redstone Dust, Programmed Circuit = 5 Red Alloy Dust

**Comment by Bluebine** [comment]
1 copper+ 4 redstone to 5 red alloy sounds OP with it only giving 1 normally, maybe change it to 2 instead of 5

**Comment by DarkYuan** [comment]
Oh, my mistake, I forgot it was 5 to 1, not 5 to 4!!

**Comment by richardhendricks** [comment]
@Dream-master, did you set the mixer to output 8? That is too much IMO.  2 output sounds better to me, with redstone set to 3?

**Comment by 0lafe** [comment]
Uhhh, so mixer is an 8x increase? That does sound high, even 2 sounds kinda high

**Comment by Dream-Master** [comment]
no same as original recipe but get dust.

**Comment by Dream-Master** [comment]
1 copper for redstone dust is 1 redalloy dust.

**Comment by draknyte1** [comment]
100 ticks at 8eu/t, is what they were reading.

**Comment by Dream-Master** [comment]
maybe but the recipe is not op only an alternative way dont't using the alloy smelter.

**Comment by draknyte1** [comment]
Did not say it was, the others only think it is because they read the wrong bit of data. 😛

**Comment by MineAnPlay** [comment]
Why does it require water... Also normal recipe isn't 1 Copper with 1 Redstone it's 4 Redstone. IMO the mixer shouldn't have better efficiency then the alloy smelter (They should be equal).

**Comment by draknyte1** [comment]
> GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Redstone, 4L) 

This is four redstone. Can people not read?

**Comment by MineAnPlay** [comment]
No I can read but somehow blanked out. That's what happens when you don't get a good sleep. But my first question still stands :P

**Comment by richardhendricks** [comment]
Sorry, my bad.  I am ok with it needing water, but maybe using the mixer could allow for 3 redstone instead of 4? Don't really see the point of the new recipe otherwise. You still will need to smelt it anyways, so it is more steps than just throwing in the alloy smelter.

**Comment by Dream-Master** [comment]
sure 1:3 ok too for me

**Comment by DarkYuan** [comment]
Oops, didn't realize this also created a free Redstone output in the centrifuge (1 and 4 still)
