### ISSUE TITLE
Suggestion Portable Quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3493]
#### Which modpack version are you using?
2.0.4.8

A quest to make a portable Scanner in mv after doing advanced circuits.

EDIT: New Suggestion, change the portable scanner quest to after the ebf/ possibly the advanced circuit

**Comment by Anarack** [comment]
Yes I see that now but its nice to have it long before a clean room.

**Comment by Dream-Master** [comment]
ok will try to move quest later
