### ISSUE TITLE
Draconic Chestplate Flight Speed Modifier Not Working.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3495]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Singleplayer & Prospercraft
#
#### What did you try to do, and what did you expect to happen?
*I created a draconic chestplate, charged it fully, and tried adjusting the flight speed modifier while flying with effective while sprinting turned to off.
*Expected to move a bit faster.
#
#### What happend instead? (Attach screenshots if needed)
0% speed modifier is the same speed as 600%.
#
#### What do you suggest instead/what changes do you propose?
Fixing whatever may be conflicting with the flight.

**Comment by Teirdalin** [comment]
Feeling like Draconic Flight is the slowest flight in the game right now. lol

**Comment by Teirdalin** [comment]
Confirmed: Still not working in latest version.

**Comment by AlexBucket** [comment]
Still an issue in 2.0.7.5

**Comment by richardhendricks** [comment]
#5142
