### ISSUE TITLE
Handed pump (duplicate liquid)

### ISSUE THREAD

**Issue by skynsun** [GTNewHorizons/NewHorizons#3496]
#### Which modpack version are you using?
v2.4.0.8
#
#### If in multiplayer; On which server does this happen? 
On private server.
#
#### What did you try to do, and what did you expect to happen?
- suck out the liquid from buildcraft tank with the GT++ handed pump
- i expect liquid to vanish from the bc tank
#
#### What happend instead? (Attach screenshots if needed)
the liquid stay in the tank and you get it into the handed pump (duplicate liquid)
#
#### What do you suggest instead/what changes do you propose?
fix that xD

**Comment by draknyte1** [comment]
Fixed in dev.
