### ISSUE TITLE
Stone Duplication With Fortune / Auto-Smelt

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3497]
#### Which modpack version are you using?
2.0.4.6

#
#### If in multiplayer; On which server does this happen? 
Prospercraft

#
#### What did you try to do, and what did you expect to happen?
*Mine stone with my pick with fortune and auto-smelt.
*To get one stone back per stone mined.

#
#### What happend instead? (Attach screenshots if needed)
Gotten multiple stones back.

#
#### What do you suggest instead/what changes do you propose?
Stone to give one stone back when mined with autosmelt and fortune.

It is a pretty minor issue honestly though, at the point people would have these enchants; getting stone is basically nothing.

**Comment by boubou19** [comment]
it's a config issue: to fix this change this
> B:"Enable Auto-Smelt and Fortune interaction"=true
to false and it should work
