### ISSUE TITLE
Tinker Gregworks Material changes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#350]
In the config all material can have different values.

**Comment by Namikon** [comment]
I already prepared an entire page with that in our GoogleSheet. Please use that

**Comment by Dream-Master** [comment]
https://docs.google.com/spreadsheets/d/1sRroNCV_4JpxrgKNivrOnSi-vz_-TX-a1-ll6WhwBJs/edit#gid=773428

**Comment by Dream-Master** [comment]
If you want to edit it please contact me that i can invite you for editing.

**Comment by Drobac** [comment]
Can you link to the page, i must be blind

**Comment by Drobac** [comment]
also id suggest putting Adamantium on the same material tier with Neutronium but adjust the aspects so Adamantium would be good for Bows/Crossbows etc

**Comment by Namikon** [comment]
No link here. And probably you are using the old one, I will send you the new link via email

**Comment by Dream-Master** [comment]
@Namikon 
I send you a link to a hidden page. Did you get an email with the long(empty xls document)?

**Comment by Namikon** [comment]
Yes. I just had nothing to put there (yet).

**Comment by Dream-Master** [comment]
@Namikon  @Drobac 
I need some values here to change the materials.

**Comment by Dream-Master** [comment]
There is a Page in the Google XLS Sheet . Tinkers Gregworks properties.

**Comment by Namikon** [comment]
Available on the Testserver for investigation; Verified by me to be functional; Even fits with the new Avaritia Materials; So I'd say this can be closed
