### ISSUE TITLE
Gadomancy\fastcraft related crush

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3502]
#### Which modpack version are you using?
Epsi one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
I trying to make Gadomancy aura core bounded to ordo. When i make the needed operations i get this crush: 
[crash-2018-08-24_14.07.16-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2318138/crash-2018-08-24_14.07.16-client.txt)
After the resturt shard cluster dissapeared, and aura core stays unbounded.

Suggestion: fix it =D

![2018-08-24_14 26 42](https://user-images.githubusercontent.com/25028786/44582360-14338600-a7aa-11e8-859b-2e24b1c8dff1.png)

**Comment by CalterOK** [comment]
I have a similar problem and does not have FastCraft

**Comment by bartimaeusnek** [comment]
it is blood arsenal messing with this.

**Comment by Namikon** [comment]
Blood arsenal? There is not even one line from BA in this crashlog oO
Don't think it's a vanilla bug; From the log provided it looks like if some Entity Render isn't checking for instanceof FakePlayer.

**Comment by bartimaeusnek** [comment]
After i ASM patched the vanilla method to not render when its a fake player, this happened:
![2019-04-02_06 46 04](https://user-images.githubusercontent.com/33183715/55376943-1c5b5d00-5513-11e9-9199-23b441e1f689.png)

Note that this Fake Player is actually the Aura Core (you can pick it up). 

Same set up without BloodArsenal (with the ASM untouched):
![2019-04-02_06 55 20](https://user-images.githubusercontent.com/33183715/55377230-537e3e00-5514-11e9-8d2a-33314e995109.png)

**Comment by DietmarKracht** [comment]
I remember that I crafted the core 2 years ago an delta. Even the old setup still exists
