### ISSUE TITLE
thaum stuff for moron quest

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3503]
here's some info for moron to do thaum quests for wands/etc

so a couple of things that I've learned.
1) in the thaumic machina tab, once you have access to infusion, are some recipes to augment your wand.  I think the one that gives you a discount is broken (there's an open issue) but you can add to any wand or sceptre, a 25% increase in vis capacity.
2) robes play a major role.  what I did was I got a full set of bloodstained thaumaturges robes from a thaum loot bag.

* early on you'll end up making an iron capped whatever wand, then have to actually make the same vis amt wand but better caps, the better caps the better the discount.  you have have to rinse/repeat this process till you can make a sceptre, then AGAIN, rinse/repeat all the way starting at iron caps to make the next rod.

* skip warpwood when it comes to it.  I guess it's fixed in dev but atm in 4.6 it doesn't work whatsoever plus it uses up your pearl.

so basically I did the early 50 vis wand stf month(s) ago, so your particular place I think I just incrementally went up from iron capped wood to greatwood iron capped to copper or gold, etc.
ended up with gold capped greatwood wand, 92% cost, 50 vis
iron greatwood sceptre, 75 cap, 92% cost,
iron silverwood wand, 100 cap, 102% cost
thaumium bossed silverwood wand, 100 cap, 82 cost
thaumium bossed silverwood sceptre, 150 wand, 72% cost
I infused the thaum silverwood sceptre to get 25% more vis

by that time I was able to make ichor robes, 5% cost per piece x 4
skip warpwood, go right to ichor wand, 1000 vis, then I made ichor sceptre, 1500 vis
that was the path I took.  I never had to make any other robes or things that gave me more discount

it's a real pisser cause you're not used to making the same wand but better and better caps as you go along.
just to get another 2% to make the next one, etc

now, you can do the bart way which is to make a full fledged warpy set of robes, etc + nano boots of traveller, etc and get even more and you can probably skip some things

once I had the tech I just cheesed my way from ev to LuV ebf to make osmiridium and turned the quest in for the pure tear and did a huge studytime and got all the research all at once, and all the warp.  

turns out the arcane spa does keep all the effects from happening.  so it's good to have in your hideyhole as you take on warp and do the research.  if you have to run back to your base, be sure to wait till you can hit the spa and run back w/o effects showing up.

my approach was to have a hard cap of research.  I didn't want any of the warp theory warp events that were on the second page so once I had gotten to the edge of the first page of warps, I stopped taking on any additional warpy things.  The only exception was at the end when I wanted to turn in the quest for tear which requires void research and I wanted the transmutations to make more osmium/iridium, and thus osmiridium.  

I made a large combustion generator as well as the buffered LuV dynamo hatch which allowed me to power the ebf with an LuV energy hatch for small batches to cook the osmiridium.  You can do all of this at ev.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57422076-2ccabb80-71d4-11e9-81c0-5d0a053bfd7b.png)
![image](https://user-images.githubusercontent.com/1214811/57422080-30f6d900-71d4-11e9-940e-38f128080a4b.png)
![image](https://user-images.githubusercontent.com/1214811/57422084-33f1c980-71d4-11e9-996f-ee2002489a7f.png)
![image](https://user-images.githubusercontent.com/1214811/57422087-381de700-71d4-11e9-912d-bfc79e621c10.png)
![image](https://user-images.githubusercontent.com/1214811/57422104-41a74f00-71d4-11e9-82e7-5389c7741c74.png)
![image](https://user-images.githubusercontent.com/1214811/57422109-466c0300-71d4-11e9-8c42-0b2e471a4408.png)
![image](https://user-images.githubusercontent.com/1214811/57422117-4bc94d80-71d4-11e9-9263-77d6992405b2.png)

If you think more quests are needed, please file a new ticket. I don't know if we necessarily need quests for every type of robes etc, I think just exposing players to the idea should be enough.

**Comment by DoomSquirter** [comment]
one thing to note: do not do all the wand infusion researches
if you do you cannot do both vis discount and vis storage (it's a known unfixed issue on their git)

while those quests are dandy, it would really help if some documentation somewhere was updated/ensured correct for what it takes to make each wand step.  of all the things in thaumcraft in the pack, this was by far the most annoying bit.  most annoying.

**Comment by richardhendricks** [comment]
Do you mean both, or really all (like tainted etc)?  I only have the quests for the two.
