### ISSUE TITLE
Multilayer forestry orchard oreberry farm quest.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#3504]
Works for 2.0.4.8 SSP.

Request by moronwmachinegun for quest that would explain how to do multilayer forestry orchard farm. As orchard mode gathers everything above it, it is possible to do multilayer farm dedicated for in example oreberries in setup like this counting from bottom: Bricks -> soil -> ic2 crop -> soil -> ic2 crop etc. As crops grow to their last stage they get harvested no matter what layer. Crops are also fully saturated and fertilized.

Probably it has limitation for height but haven't tested that, works fine for 5 layers of crops.

**Comment by Dream-Master** [comment]
never did  a farm like that. Need help with it.

**Comment by richardhendricks** [comment]
I will take care of it.
