### ISSUE TITLE
HV Tier Circuit Quest Chain Ingrediants

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3505]
2.0.4.8

The Tier 4 quests chain for circuits require you to make smd diodes/transistors when they are not required and are the worst possible choice over regular diodes/transistors.

Suggestion change smd diode/transistors to normal diode/transistors

Quests that need to be looked at
Microprocessor ID: 1235
Integrated Processor ID:1016
Workstation Extreme Circuit ID:1014
IV Circuit Mainframe ID:1225

**Comment by richardhendricks** [comment]
I think SMD diodes/transistors can be pushed back to HV, after an HV macerator.  Once you get that, Gallium is way easier to get.  I can also add a Galvania IC2 crop quest, that allows players to 4x their sphalerite and get more gallium too.

Thoughts?

**Comment by Dream-Master** [comment]
Ok i can change the quest. If i need to change the recipes just post your comment here.

**Comment by richardhendricks** [comment]
ic2 galvania quest added, lots of info added to SMD circuit components quest.

![image](https://user-images.githubusercontent.com/1214811/57199784-9a62b780-6f48-11e9-9d30-d6412791f0bd.png)

I don't think the HV circuit component quests need changing.
