### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3511]
Some quests need a fix

Book quest need 12 buckets of glue

Automation power need to be and and quest

Do you heare the engine reeving (remove dependencies from previos quest)

EBF 2x/4x need a better gate that it cant be completed after make first ebf.

chainmail quest need a fix

**Comment by bartimaeusnek** [comment]
IC2 Crop quest needs the info that cropsticks can be planted on other soil but farmland. i.e. Ztongs Garden Soil
