### ISSUE TITLE
Planetary Tiers

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3513]
Tier 1
Moon -needs Oxygen Gear

Tier 2 - Need Thermal Padding for Mars
Mars    
Phobos
Deimos

Tier 3
Ceres  -Need tier 2 thermal padding
Asteroids
Europa -Need tier 2 thermal padding
Ganymeade -Need tier 2 thermal padding
Callisto -Need tier 2 thermal padding
Ross128b - Habitable Planet (need no Oxygen Gear/thermal padding)

Tier 4  -Need tier 2 thermal padding
Io
Mercury
Venus - Needs SpaceSuit 

Tier 5 -Need tier 2 thermal padding
Enceladus
Titan
Miranda
Oberon

Tier 6 -Need tier 2 thermal padding
Proteus
Triton

Tier 7 -Need tier 2 thermal padding
Pluto
Haumea
Makemake
Kuiper Belt

Tier 8 -Need tier 2 thermal padding
Alpha Centauri Bb - Requires SpaceSuit
Tau Ceti E - Habitable Planet (need no Oxygen Gear/thermal padding)
Vega B
Barnarda C - Habitable Planet (need no Oxygen Gear/thermal padding)
Barnarda E
Barnarda F

**Comment by bartimaeusnek** [comment]
added/modified list.

**Comment by MineAnPlay** [comment]
Don't tier 3 and above require Thermal Padding Tier 2? Also one of the tier 8 Planets required the Space Suit too.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57895992-21027900-7814-11e9-8481-36b7d58a8644.png)
