### ISSUE TITLE
Suggestion - Higher Chance of Tiny Americium Dust From Americium Combs, or Lower Power Requirements

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3514]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Trying to process Americium Combs through several zpm centrifuges, and getting only a tiny, reasonably useless amount of yield for a huge power consumption.
#
#### What do you suggest instead/what changes do you propose?
A lower power requirement for processing Americium Combs, as the only way it can be a viably useful bee is if you massively bulk process it, which anyone who can reasonably do probably wouldn't really need Americium.  

 Or a higher chance, maybe 50% or 75% as to actually get something for the power and effort it takes to process these 36,864,000 eu combs..

**Comment by Dream-Master** [comment]
how expensive is fusion ?

**Comment by Teirdalin** [comment]
Getting that 5% nine times in a row would be fairly impressive.

**Comment by Dream-Master** [comment]
Sure. Do a full list with suggestions and we will add this next release.

**Comment by Teirdalin** [comment]
Thanks Dream, hopefully the people here can find a way to make combs funner and more useful later game.  Personally I'm off to sleep now as it's like 3:26am here. lol

**Comment by MineAnPlay** [comment]
Also next version has a modified version of my PR (300 ticks for MV+ recipes except for the highest tier combs (I think Black Plutonium, Infinity Catalyst and Infinity). So so the math with those values as well to see how it goes.
