### ISSUE TITLE
Glass Fiber (#1675) has quantity mis-match

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3515]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
Quest steps 1-4 are the right amounts to make 32 ingots
#
#### What happend instead? (Attach screenshots if needed)
Step 5 then asks for 256 glass fiber, which would need 64 ingots to make
#
#### What do you suggest instead/what changes do you propose?
Double the quest requirements for steps 1-4

**Comment by Dream-Master** [comment]
will d for next release.
