### ISSUE TITLE
Qbit Wafer and Chip (#1679) has quantity mis-match

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3516]
#### Which modpack version are you using?
2.0.4.9

#### What did you try to do, and what did you expect to happen?
Step 1 asks for 1 wafer
Step 2 asks for 8 chips
#
#### What happened instead? (Attach screenshots if needed)
1 wafer cuts into only 4 chips
#
#### What do you suggest instead/what changes do you propose?
Double the number of wafers in step 1

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
i lower them to 4
