### ISSUE TITLE
Un-Nerf Liquid Air

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3517]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I tried to set up a liquid air line. I expected it to be competitive with compressed air, requiring a vacuum freezer but less centrifuges.
#
#### What happend instead? (Attach screenshots if needed)
Liquid air is LUDICROUSLY expensive and there's no point making it any more.
With compressed air, it can either be centrifuged for a cost of 2,560 EU per cell, or vacuum frozen for a cost of 115k EU per cell. That's a RIDICULOUSLY high number compared to centrifuging. 

It's also fairly slow compared to centrifuging the air directly.
Processing one cell of compressed air per second requires 16 LV centrifuges, consuming 128 EU/t, or TWELVE vacuum freezers consuming 5,760 EU/t (plus two centrifuges consuming 16 EU/t). Since the vacuum freezer is an expensive multiblock, VS very cheap LV machines, it should be MUCH more effective than an LV centrifuge. A single MV centrifuge is faster than a vacuum freezer!
#
#### What do you suggest instead/what changes do you propose?
The vacuum freezer recipe should require 32 EU/t, and take 5 seconds to complete. This puts it at a slightly lower efficiency level than centrifuges, but still better. With 32 EU/t, you can process .25 cells per second using 4 centrifuges, or .2 cells per second using a vacuum freezer. 
This would allow 1 vacuum freezer running off HV to process .8 cells a second, meaning processing one cell of compressed air a second would now require TWO HV vacuum freezers and ~640 EU/t, replacing 16 LV centrifuges, which I think are MUCH more reasonable numbers.

**Comment by NeroOneTrueKing** [comment]
Better for producing what, Nitrogen?
A plain old compressed-air centrifuge won't make you any Argon, while a vacuum freezer setup will.

**Comment by Bluebine** [comment]
Well yeah, I'm basing my numbers off nitrogen. That's the only real reason for using compressed air and still the main reason for using liquid air. The vacuum freezer is the higher-tech option, so it should be better or at least equal in N2 production, as well as making the argon and noble gases.

**Comment by NeroOneTrueKing** [comment]
Argon is a high-end EBF gas, needed to smelt Naquadah, Draconium, and other high-tier materials. It has very few sources, the most accessible (and I think cheapest) of which is to compress->freeze->centrifuge Air. Other Argon creating methods are UUM and centrifuging T5 planet stone.

I'd say that the main reason for using liquid air is to obtain Argon, and the nitrogen is a byproduct.

**Comment by Anarack** [comment]
Argon at 12 seconds is around 30% better than the uum rout, from the last thread. #3128
