### ISSUE TITLE
Quantum armor quest accept only mainframes

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3523]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
Ore Dict support in that quest
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/37113583/44641763-4b37b080-a9d1-11e8-9dea-18a67690cf7b.png)
#
#### What do you suggest instead/what changes do you propose?
Add Ore Dict support to that quest

**Comment by barsikus007** [comment]
When player can make assline to make quantum armor, he have acces to next circuit tier

**Comment by Dream-Master** [comment]
sure will oredict it.

**Comment by Dream-Master** [comment]
Allready fixed in 2.0.4.7/8 or 9
