### ISSUE TITLE
Memory card quest (#1331) is impossible to complete

### ISSUE THREAD

**Issue by TheMathis26** [GTNewHorizons/NewHorizons#3525]
#### Which modpack version are you using?
 2.0.4.8
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I crafted a memory card so I wanted the quest to be completed. 

![](https://cdn.discordapp.com/attachments/234936569360809996/483685989806768138/unknown.png)

#
#### What happend instead? (Attach screenshots if needed)
The memory isn't detected, even by clicking on the "Detect/Submit" button.

![](https://cdn.discordapp.com/attachments/234936569360809996/483685978524090388/unknown.png)

#
#### What do you suggest instead/what changes do you propose?
I think the bug comes from the fact the card can hold data but I don't know exactly why it does that so I don't know how to solve it.

**Comment by Dream-Master** [comment]
ignore nbt maybe. Will try.

**Comment by Highbeam** [comment]
Have you tried following the instructions on the quest (shift click a P2P ME interface)?

I think doing that completed the quest for me.

**Comment by TheMathis26** [comment]
No I didn't. I don't have P2P yet so if it's really the solution of the problem, then this quest should be unlocked after having done the P2P quest.

**Comment by 0lafe** [comment]
>then this quest should be unlocked after having done the P2P quest

It should if it's guiding you to p2p buses. It should say on the card for the quest what kind of card it is, it's different for each bus iirc, and then you can find it to yourself, I think, for security. There's a card for items, essentia, power, other power, probably fluids, and maybe others, but I think they're technically different items.

**Comment by alphaNOVAircraft** [comment]
Dont think that there are different cards aviable. Just the tunnels itself change
