### ISSUE TITLE
can't make cake in assembler - milk won't pipe in

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3527]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
smp, private
#
#### What did you try to do, and what did you expect to happen?
ingredients in assembler, milk is gt milk gotten from thirsty tank/glyph of cow
#
#### What happend instead? (Attach screenshots if needed)
milk won't pipe into assembler

#
#### What do you suggest instead/what changes do you propose?
I want my cake :(  and eat it too!  :(

recipe shows gt milk, tooltip over milk shows gt milk, I had issue a while back where I couldn't use manual milk taken by buckets in alchemical boiler.  wondering if something got mucked up along the way.

**Comment by DoomSquirter** [comment]
oh I just noticed something

milk in recipe shows milk: 7146:14
but milk in tank is milk: 7146:20

so it's like meta issue?

**Comment by DoomSquirter** [comment]
so I went out and milked 3 cows manually with buckets, put buckets in and it sucked the milk in
soooooo something is wonky

**Comment by richardhendricks** [comment]
The cake is a lie.

**Comment by draknyte1** [comment]
Milk obtained via Automagy is a different fluid 'fluidmilk' to the fluid everything else uses 'milk', there needs to be a change made to automagy if it's already forked here or otherwise a way to convert between them.

**Comment by Dream-Master** [comment]
@draknyte1 Automage only published a api not the whole mod.
https://github.com/Tuhljin/Automagy

**Comment by draknyte1** [comment]
https://github.com/Tuhljin/Automagy/issues/29

**Comment by DoomSquirter** [comment]
yeah I looked at what uses milk in recipes in machines and was bewildered to see like 30 ways to make heavy cream in mixer, all exactly the same lol.  

but yeah, that looks like only one in assembler.  probably just adding or changing the cake recipe to ignore meta would probably fix the problem.

**Comment by draknyte1** [comment]
Fluid doesn't have meta Doom, that's just a side effect of Gregtech making fake ItemStacks that display fluids. (Each one of these display stacks has meta)

We just need a way to turn 'fluidmilk' into 'milk', that's really it. Just have a 5tick, 100mb distil recipe that uses 2eu/t, done.

**Comment by Dream-Master** [comment]
yea something comes in my mind like we make honey from forestry and bop compatible.

**Comment by DoomSquirter** [comment]
keep in mind the automagy alchemical boiler which has the reverse problem.  if you were to fix the stacks, what would happen to it?  
tbh, I'll be using that alot more than making cakes.  if mucking with the milk fluid means alchemical boiler is useless for milk, then I'd rather the entire thing not have anything done to it to ensure the boiler works first and foremost.

and @draknyte1 since you like to be very specific in your wording, pls say fluid isn't SUPPOSED to have meta, because obviously it does have meta, it's just erroneous to have it in the first place.  

lastly, if the recipe you are talking about with distillation is what would fix the milk to make cakes, I can totally get along with that since I'd not have to do it to put it into boiler since it takes it as it is now.

**Comment by draknyte1** [comment]
Just make milks convertible in distil at 1:1 ratio and very minimal recipe costs. Breaks nothing then. 

Fluid does *not* have meta, the fake display stacks do, they're not representable of the actual fluid besides displaying the texture, name and temp. It's confusing, because it makes people think *every* fluid is from GT, whilst just the fake display stacks are.
