### ISSUE TITLE
Ztones Recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#353]
- [x] Add ZTone Recipes

**Comment by Namikon** [comment]
For which blocks are you planning to add recipes?

**Comment by Dream-Master** [comment]
For all we don't disabled.

**Comment by Namikon** [comment]
Ok, but please, don't change the recipes for the zTone blocks. If will mostly ruin the joy of having it if you have to make those in an assembler, or with extra materials. From what i've experienced on my Server, It took me around 4000 iron ingots and around 32k normal stone just to build the basic housing of my nuclear facility. Not to mention the special blocks that require netherquartz and such. It is just for decoration purposes anyways.

**Comment by Dream-Master** [comment]
I thought about not changing the blocks only the items.

**Comment by Namikon** [comment]
Ok, great :)

**Comment by Dream-Master** [comment]
Done
