### ISSUE TITLE
´Chunkloader coin tier II

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3531]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Use /home
#
#### What happend instead? (Attach screenshots if needed)
the test to wait appeared but noting folowed, waited about 30 s

at the time i hade chunkloader coin tier II in my hotbar, when i removed them  into a backpack i teleported, i could make this happen again so it was not some 1 thime thing
#
#### What do you suggest instead/what changes do you propose?
look into it

**Comment by Dream-Master** [comment]
realy wired.

**Comment by Ghengis88** [comment]
yes

**Comment by Ghengis88** [comment]
maby someone else could try it

**Comment by Dream-Master** [comment]
@Ghengis88 can you make a video to better reproduce it myself?

**Comment by Ghengis88** [comment]
I think it was on my end the problem was.... it works fine today..... have restarted the game. but loging out did not fix it yesterday. so dont know ...

**Comment by Dream-Master** [comment]
ok
