### ISSUE TITLE
High tier oil drilling rigs broken

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/NewHorizons#3532]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
Local LAN world
#
#### What did you try to do, and what did you expect to happen?
Extract heavy oil via an Oil Drilling Rig III, at around the center of an oilfield
![2018-08-28_14 08 16](https://user-images.githubusercontent.com/28197216/44744958-faf14900-aacb-11e8-9ee7-bbd4237093f0.png)
![oil](https://user-images.githubusercontent.com/28197216/44744994-1bb99e80-aacc-11e8-82ea-bd633d7a4110.PNG)
Seed -2983707196244287790
Co-ords: x: -1093, z:1078
#
#### What happened instead? (Attach screenshots if needed)
The rig sent down pipes, and instead of bringing up oil, it just retracted the pipes. An Oil Drilling Rig I/II in the exact same location returned heavy oil as expected
#
#### What do you suggest instead/what changes do you propose?
Fix the Tier 3 oil drilling rig

**Comment by Dream-Master** [comment]
@richardhendricks  aqny idea ?

**Comment by richardhendricks** [comment]
I talked to him in discord, need to look at it in detail.  Probably weird math in how it determines where the drill is located.

**Comment by richardhendricks** [comment]
Confirmed.
It looks like the rigs are only valid when they are in the N quadrants of the chunks.  Will investigate root cause in code.

![2018-08-29_19 54 05](https://user-images.githubusercontent.com/1214811/44823369-a03c1800-abc5-11e8-9456-27bbe7c51fce.png)

**Comment by richardhendricks** [comment]
Root cause is that java was made by idiots.  / does not behave the same on the negative side of the number line, it rounds towards 0 instead of - infinity. Math.floorDiv() must be used instead.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7e6fb0abeef22b80f16da5f63e7849525823579e
