### ISSUE TITLE
CATWALKS Mod not full integrated

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#3533]
#### Which modpack version are you using?
GTNH 2.0.4.8
#
#### If in multiplayer; On which server does this happen? 
MyFTB

scraffold from Mod CATWALKS can't be broken (do disapeare) and coulden't be macerate for recycling steel. 
May be also valid for other parts of that mod.
(Gerüst vom Mod CATWALKS kann nicht abgebaut (nur zerstört) werden und auch nicht recykled, zB gemahlen werden den Stahl zurück zu gewinnen
Eventuell gilt dies auch für andere Gegenstände des Mods.)

**Comment by Dream-Master** [comment]
@Ngar1 Die Rezepte sind nicht im Code von gt integriert und es gibt so keine Auto Recycling Rezepte. Das abbauen von anderen Mod Blöcken kann nur in der mod selber realisiert werden. Recycling Rezepte kann ich einfügen. Schlag doch hier welche vor.

Recipes from catwalks mod are not integrated in gt code and so no autogen recycling recipes available. If you wish that blocks can be harvested via tools you need to rewrite the mod itself. Recycling recipes I could add easily. Make a few suggestion here.
