### ISSUE TITLE
Sunnarium fusion recipe

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3534]
#### What did you try to do, and what did you expect to happen?
Making sunnarium is bit annoying in endtier - u need ALOT, materialthingy is a bit slow and not nice for usage(even at UV powah provided), so why not to add a fusion recipe?

Here is the code Спартак provided for me:
#
`GT_Values.RA.addFusionReactorRecipe(Materials.Glowstone.getMolten(16), Materials.Helium.getPlasma(4), Materials.Sunnarium.getMolten(16), 32, 7680, 40000000); //Mark 1 Expensive //`

I love the values, can u add this to the game?

**Comment by 0lafe** [comment]
It's not that bad, I was making it at 1 dust/tick which is a little more than 2 ingots/s which is really more than you could ever need. Fusions probably nice for it though
