### ISSUE TITLE
something new I guess

### ISSUE THREAD

**Issue by ScreechamusPrime** [GTNewHorizons/NewHorizons#3537]
I was thinking that there could be some sort of catalogue book of some sort. It should contain where to     find mix veins etc. I made a MS Paint file describing what I mean, I included it in the files (it makes more sense seeing it, even though it isn't finished.)
![untitled](https://user-images.githubusercontent.com/41102857/44770413-edf35900-aba2-11e8-9bc5-8d41860e8cef.png)

**Comment by ScreechamusPrime** [comment]
what I meant to write "here is a suggestion for an in-game sort of index for found items (like mixveins, bees, materials) it isn't finished but you can get the basic idea of it."

**Comment by bartimaeusnek** [comment]
Uhm... all of these Informations are already ingame in [NEI](https://gtnh.miraheze.org/wiki/Beginner_Tips#Learning_to_use_NEI)...

**Comment by ScreechamusPrime** [comment]
no,  I mean add something like this because it keeps things organized and
it would improve the QOL (the mix vein locations aren't in NEI)

**Comment by Ghengis88** [comment]
Yes the information is in nei but Ore location is hard to read if you don't memorize the short name for every planet and what tier they are. I still use the Google dox. Spreadsheat. 
But what you are sugesting would take a massive amount of time putting together and essentialy making nei obsolete. I Think the Google dokument fills this funktion.

**Comment by bartimaeusnek** [comment]
@Ghengis88 the Google dox. Spreadsheat is not correct anymore, if you want a speadsheet follow this tutorial: https://gtnh.miraheze.org/wiki/GT-NEI-Ore-Plugin_Spreadsheet_Export_Tutorial

**Comment by Bryfer** [comment]
wait what?
@bartimaeusnek why isnt the spreadsheet up to date?
what changes has been made since it was last updated?

In my opinion the spreadsheet should ALWAYS be up to date since its a great source of information for the modpack, it is also linked in the #help chat. so if its not valid anymore, why even have it there?

**Comment by bartimaeusnek** [comment]
@Bryfer dont ask me i dont do information stuff. Its on V 2.0.0.0 afaik

**Comment by ScreechamusPrime** [comment]
where ca I find the Google Dox?

**Comment by draknyte1** [comment]
I think his issue is remembering them. I had to write them down outside of the game for easy access *while* looking at NEI. Swapping to the quest book every ten seconds is annoying.

**Comment by richardhendricks** [comment]
Well, we can take a look at the GTNEIOre plugin and see about increasing the size of the window so we don't need to use short names. Would that work?

**Comment by DoomSquirter** [comment]
or hovertext over individual ones but yeah, probably increasing size makes more sense programmatically.  least that would be easier?

**Comment by richardhendricks** [comment]
New version of Bart's ore plugin will give actual dimension names when hovering over the list.
