### ISSUE TITLE
New NEI recipe tab for IC2 crops drops.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#3538]
Suggestion.

I think new NEI tab for crops would be useful, basically idea is like this: ie you look for source of blaze powder, then in one of tab you get blazereed as result. It's not urgent, just something I think is worth considering.

**Comment by Dream-Master** [comment]
we have the crops nei plugin from speiger. Maybe it can be improved like be better at bees.
