### ISSUE TITLE
Computer Case(Tier 3)

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#354]
The recipe uses Advanced Heat Vent (4221) and you can only craft Advanced Heat Vent (4221:1), so please adjust that in the recipe

**Comment by Dream-Master** [comment]
I fix this in the OC gregtech Recipes file directly and post it in the OC git.

**Comment by Dream-Master** [comment]
https://github.com/MightyPirates/OpenComputers/issues/1468`

All Computer Cases and the Server Rack Recipes are brocken.

**Comment by Dream-Master** [comment]
If i not get an answer i will minetweaker the 4 recipes.

**Comment by Drobac** [comment]
the other computer cases worked just fine with the new IC2 metadata, just had problems with advanced heat vents

**Comment by Dream-Master** [comment]
but they wrong too

**Comment by Namikon** [comment]
That message looks like it is triggered from our own mod; https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java#L451

However, I wonder why it prints debug messages to your console. It has nothing to do with the recipes, it's probably something with the computer case itself, while it's in your inventory. But nothing related to OpenComputers. I need to trace that; As that exception catch was just there to prevent any weird item combinations and resulting crashes, I never expected that message to show up

**Comment by Dream-Master** [comment]
Open computers have a recipes file. We using the gregtech recipe file. I think it is a open computer craft issue but i can minetweaker it anyway.

**Comment by Dream-Master** [comment]
Fixed Tier 2 and Tier 3 Casing and the Server Block via Minetweaker.

**Comment by Dream-Master** [comment]
Maybe oc fix it later in a new version.
