### ISSUE TITLE
Suggestion: add the mod "The Inbetween"

### ISSUE THREAD

**Issue by ScreechamusPrime** [GTNewHorizons/NewHorizons#3542]
The Inbetween is a very nice mod. It's a bit like the Twilight Forest Mod, but different. I think it should be added somewhere in the Thaumcraft progression, probably when reaching Dark Tower in the Twilight Forest, and the key progression items in the Inbetween should be required to progress in the TF and Thaumcraft.

**Comment by richardhendricks** [comment]
We are pretty much done with adding major mods to the current version of GTNH.  We are looking at a 3.0 release that will support modern versions of Minecraft.  Do you have a link to this mod?

**Comment by ScreechamusPrime** [comment]
what do you mean "a link"? I have never heard of this term. do you want a
link to the minecraft forge site, or the wiki?

**Comment by ScreechamusPrime** [comment]
if you want the forge link, here it is:
https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod

**Comment by richardhendricks** [comment]
Where is the mod?  I didn't find one called Inbetween.  Did you mean Betweenlands?

**Comment by ScreechamusPrime** [comment]
yes. thats the one

**Comment by ScreechamusPrime** [comment]
sorry

**Comment by Teirdalin** [comment]
The betweenlands is a fun mod,  Didn't realize it was out for 1.7.10.

Could definitely be interesting having to do that place for thaum progression.

**Comment by bartimaeusnek** [comment]
it is already in the pre-alpha-testing modpack we use for GTNH-3. i guess we wont add bigger mods to V2.x anymore so ill close this.
