### ISSUE TITLE
Processing Bio Diesel to Cetane-Boosted diesel loses 30% of the energy compared to just burning the components

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/NewHorizons#3544]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Processing bio diesel into cetane
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/42840657/44856967-69263f00-ac77-11e8-8d1d-bb22bcb2171a.png)

#
#### What do you suggest instead/what changes do you propose?
Change how much bio diesel the recipe uses

**Comment by draknyte1** [comment]
How much do you suggest instead?

**Comment by SampsaxD** [comment]
4 Bio Diesel would even it out with the normal diesel recipe, adding a little bit of extra burn value. 5 Bio Diesel would keep it a little bit in the negative, if making the energy denser in itself is worth it.

**Comment by draknyte1** [comment]
> how about we change this

How about I do, because it's my recipe.

> 4 Bio Diesel would even it out with the normal diesel recipe

It's obviously meant to be less efficient than that, but still net power.

**Comment by SampsaxD** [comment]
Bumping the gained cetane to 4 and shaving off 200k off the processing would put it just slightly in the negative.
I'm not sure why the recipe is HV, considering you have access to the Tetranitromethane recipe at that point anyways?

**Comment by draknyte1** [comment]
```
GT_Values.RA.addChemicalRecipe(
	ItemUtils.getItemStackOfAmountFromOreDict("cellFuel", 9), //Input A
	ItemUtils.getItemStackOfAmountFromOreDict("cellEthylbenzene", 2), //Input B
	null, //Input Fluid
	FluidUtils.getFluidStack("nitrofuel", 7500), //Output Fluid
	ItemUtils.getItemStackOfAmountFromOreDict("cellEmpty", 11), //Output Item 
	CORE.GTNH ? 1000 : 5000, //Eu/t
	100); //Time in Ticks
GT_Values.RA.addChemicalRecipe(
	ItemUtils.getItemStackOfAmountFromOreDict("cellBioDiesel", 9), 
	ItemUtils.getItemStackOfAmountFromOreDict("cellEthylbenzene", 2), 
	null,
	FluidUtils.getFluidStack("nitrofuel", 3000),
	ItemUtils.getItemStackOfAmountFromOreDict("cellEmpty", 11), 
	CORE.GTNH ? 1000 : 5000,
	300);
```
> I'm not sure why the recipe is HV

It's not? Even if it were, the idea is alternative uses for alternative fuels.. Sure, making Tetranitromethane might be the most viable for some, but others may find it better to make cetane this way.

**Comment by SampsaxD** [comment]
NEI says the voltage is 300EU/t so I went off that

**Comment by draknyte1** [comment]
Well, I guess the internal constructors for Gregtech are wrong and I mixed up the time and eu/t.. cool
