### ISSUE TITLE
Perfodio in essentia storage cell

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3546]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
make  pickaxe of the core
#
#### What happend instead? (Attach screenshots if needed)
infusion got stuck when i were trying to draw Perfodio.  and i have perfodio in the essentia storage drive. 
though o whell i  extract it into a jar, but can't do that either, so if looking in the terminal i have perfodio but i cant extract it.
#
#### What do you suggest instead/what changes do you propose?

maby it changes id somehoww? becous it cant be put into jars either...

**Comment by Dream-Master** [comment]
Never heard of it.

**Comment by bartimaeusnek** [comment]
^ have no problems with it aswell on delta, will test sooner or later

**Comment by Ghengis88** [comment]
hm found a clue to the problem it seems it goes into our fluid storage somhow....  when looking at conduits i see it in there....
dont know why tho
