### ISSUE TITLE
Crafting error for 'Thick Neutron Reflector' and 'Neutron Reflector Parts'

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3547]
2.0.4.9

1. Crafting of the Thick Neutron Reflector in NEI is shown with 4 Neutron Reflectors
![image](https://user-images.githubusercontent.com/30087707/44875434-6ee34b00-ac9e-11e8-84fa-e4dad29103a4.png)
but only requires 1 Neutron Reflector when doing the actual assembly crafting. This is the same issue as #3207.

2. The Neutron Reflector Parts can't be crafted as the assembly creates Thick Neutron Reflector 4262, but the crafting requires 4262:1.
![image](https://user-images.githubusercontent.com/30087707/44875924-ce8e2600-ac9f-11e8-8ebc-05fb539e5810.png)
![image](https://user-images.githubusercontent.com/30087707/44875835-92f35c00-ac9f-11e8-8904-cc90cdc06faf.png)

**Comment by Dream-Master** [comment]
will check
