### ISSUE TITLE
Could we make creosote more effective in the semifluid generator?

### ISSUE THREAD

**Issue by ljjmrlion** [GTNewHorizons/NewHorizons#3554]
As it stands creosote burns in both the diesel gen and the semifluid gen for 8kEU seeing as though creosote is a semifluid shouldn't it be more efficient in the latter?

**Comment by Dream-Master** [comment]
how efficient would you suggest @ljjmrlion

**Comment by draknyte1** [comment]
Well, you see, this is an invalid issue.
https://cdn.discordapp.com/attachments/220804408273797121/485588357875892240/image.jpg
![image](https://user-images.githubusercontent.com/3060479/44950697-1aa0bc80-ae92-11e8-947c-3cf11d3be32d.png)
![image](https://user-images.githubusercontent.com/3060479/44950698-1ffe0700-ae92-11e8-9c4f-28b97e510891.png)

https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/generators/GT_MetaTileEntity_SemiFluidGenerator.java#L66
The real fuel map doesn't actually have an NEI display.

**Comment by ljjmrlion** [comment]
Correction** The Semifluid generator produces 6392 EU per bucket of creosote @draknyte1

**Comment by draknyte1** [comment]
No, there is no flat rate, because there's three tiers of generator @ different efficiencies.

**Comment by ljjmrlion** [comment]
![image](https://user-images.githubusercontent.com/9472512/44950822-150a8e80-ae20-11e8-99b4-06911da06b64.png)
^^^^ Burned in a semifluid generator



![image](https://user-images.githubusercontent.com/9472512/44950844-d75a3580-ae20-11e8-8fac-5f19214f381f.png)
^^^^ Burned in an LV Combustion generator going straight into a battery

Both appear to be Within a few points of 6400EU.
Since the semifluid generator is made to burn semifluids and the diesel generator is not should the semifluid be more efficient?
@draknyte1

**Comment by draknyte1** [comment]
![image](https://user-images.githubusercontent.com/3060479/44950862-94d34000-ae96-11e8-81cc-e6f81a5b67c0.png)
>Burned in an IC2, useless piece of shit, non-GT semifluid generator

I see you didn't even use the correct machines, nice.

**Comment by ljjmrlion** [comment]
Will retest. sec

**Comment by draknyte1** [comment]
Fixed in next update.

**Comment by ljjmrlion** [comment]
Thank you.
