### ISSUE TITLE
ritual of binding - how do you activate it

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3558]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
I have T3 altar, magicians orb, 150k LP pool, weak activation crystal, activate binding ritual and it just says you feel a pull but are too weak to push any further, usually meaning you don't have enough LP
#
#### What happend instead? (Attach screenshots if needed)
nothing happened cept stated above

#
#### What do you suggest instead/what changes do you propose?
I just want to know what you're expected to do, to do the ritual.  I can't make anything that expands my LP pool, so I'm stuck

**Comment by DoomSquirter** [comment]
yeah I'm an idiot.  I never bound the activation crystal to me.  was eating dinner a couple hours ago and it dawned on me suddenly.  I just logged into world and tested it.  lmao.  sorry for the trouble.

**Comment by Dream-Master** [comment]
😎
