### ISSUE TITLE
Mod request: Radio mod

### ISSUE THREAD

**Issue by fewizz** [GTNewHorizons/NewHorizons#356]
http://www.curse.com/mc-mods/minecraft/dragons-radio-mod#t1:description

**Comment by Dream-Master** [comment]
Why not i vote for it.
Is this a client side only mod?

**Comment by fewizz** [comment]
![image](https://cloud.githubusercontent.com/assets/8060034/10227155/66458826-6874-11e5-9190-95e4b368861b.png)

**Comment by Dream-Master** [comment]
I try it but it not working for all streams. So i think because it is a clien mod that no others can here the music ?

**Comment by Dream-Master** [comment]
- [ ] New Recipes added

**Comment by Dream-Master** [comment]
Done
