### ISSUE TITLE
Suggestion: Remove requirements for oil in quests

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#3561]
#### Which modpack version are you using?
.4.9

#
#### What do you suggest instead/what changes do you propose?

At the moment, the quest for ethylene in MV is gated behind the "light fuel" and "naphtha" quests in LV. But this completely skips the fact that you can obtain ethylene in a second way, with ethanol and sulfuric acid in an MV chemical reactor.
My suggestion is to add a non-main quest for the MV chemical reactor, right above where the ethylene quest is, gated behind the MV machine hull (that's all you need to craft it). Then make the Ethylene quest an OR requirement, requiring you to complete the "Light fuel" quest, the "Naphtha" quest, OR the "MV Chemical Reactor" quest. (also remove the requirement for the MV electrolyzer, that's not actually needed for ethylene)

I've found two more quests that require oil. I'd suggest changes to both of them to not FORCE people to complete oil quests.
1. The "Rocket Fuel" quest in the Space Race tab requires you to fill fuel canisters. I'd recommend making the quest for EMPTY fuel canisters, not filled ones, and then mention that both diesel and EiO rocket fuel can be used as rocket fuel.
2. The "Let's get it Crackin!" quest is gated behind the oil drilling rig. It should instead be gated behind the "Workstation Extreme Circuit" quest and the "Tier 4" quest.

**Comment by Dream-Master** [comment]
to easy @Zoko061602 ?

**Comment by Vernam** [comment]
@Dream-Master no, it isn't. just look at the options for obtaining.. only one more convenient option. requiring 128 mechanism. there are options for 32, easier by mechanisms. besides the very variant with a dehydrator is quite long. I speak like a person who used this option. So the costs of the forces / time are justified and I do not think that they need an adjustment

**Comment by Dream-Master** [comment]
I added a quest for the dehydrator allready but the ethylen quest can have additional infos and some quest chains will be changed.
