### ISSUE TITLE
Change circuit for producing chloromethane from methane and chlorine

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3562]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
Tried to put Tetrafluoroethylene production (circuit 24) and Polytetrafluoroethylene (circuit 1) production in the same large chemical reactor.
#
#### What happend instead? (Attach screenshots if needed)
Because chloromethane is made from chlorine+methane with circuit 1, the lcr wastes chlorine and methane from the inputs when it is supposed to be making ptfe with the circuit 1.
#
#### What do you suggest instead/what changes do you propose?
Change chloromethane production from methane+chlorine to circuit 4 or something, would be a convenient change for making ptfe.

**Comment by DualBallers** [comment]
I would suggest that you only keep one type of circuit in each of your LCRs, or manually change the circuit depending on the crafting you need.
There are many recipes that conflict with each other across the different circuits, so if you keep adding circuits and recipes to a single LCR, you will get a lot of crafting "errors".
