### ISSUE TITLE
Distillation tower output only first product in recipe if more than one output hatch on layer.

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#3563]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I build distil tower for process oil to products and refinery gas to products in one multiblock. Height = 6 blocks. I put 2 input hatch, no output busses on level 1. 2 output hatch on level 2, 1 output hatch on level 3 and 4, 2 output hatch on level 5, and 1 output hatch on level 6. Energy hatch stay on top. Controller say, everything is ok.
#
#### What happend instead? (Attach screenshots if needed)
When i start refinery gas processing it finished and output only 70 mb butan output. Everything else voided. I think it's first output for one block distillery recipe.

#
#### What do you suggest instead/what changes do you propose?
I want all my products in distillery. :) Or controller should say incomplete structure if i put more than one output hatch on one distil layer.

**Comment by draknyte1** [comment]
Controller does say one hatch per layer though. 👉🏿🌚👉🏿

**Comment by Usernm0** [comment]
But it works with more than one hatch per layer. It shouldn't work at all.

**Comment by draknyte1** [comment]
Lots of the vanilla multiblocks aren't strict on structure checks. They'll all run equally as bad if you don't read the tooltip. 🤷🏻‍♂️

**Comment by DeForce** [comment]
Same applies to your structure checks.
Just because something is bad doesn't mean it shouldn't be changed.

**Comment by draknyte1** [comment]
>Same applies to your structure checks.

Uhh, no.
Mine enforce hatch/bus counts, vanilla ones do not.

>Just because something is bad doesn't mean it shouldn't be changed.

It's not an issue if you cannot read the tooltip, is it?..
