### ISSUE TITLE
Suggestion:  Thaumic Restore Balancing

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3566]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What changes do you propose?
Just a few items I'd suggest blacklisting on the thaumic restorer if possible-

Blood magic potions

Bee frames

Print Press Chase
(Maybe increase durability on print press chases if able to perhaps 8)

**Comment by draknyte1** [comment]
>Bee frames


All the Vanilla Forestry frames aren't really worth repairing,
The Oblivion frame is intended to be repaired for it's cost afaik,
The 10+ GT++ frames are not repairable at all, because I already fixed the issue for what I could.

**Comment by DoomSquirter** [comment]
I didn't know about the bm potions :)  but yeah  I don't think it has a blacklist anyways.  it's why nobody ever does blacklist anything in them.
