### ISSUE TITLE
Display Name on GT ingots showing up as gibberish when trying to detect with opencomputers.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3567]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Get the get.StoredItems().display_name from barrels containing GT ingots.

It to show the name of the ingot.
#
#### What happend instead? (Attach screenshots if needed)
It shown up as gt.metaitem.01.11###.name

![metals](https://user-images.githubusercontent.com/37776581/45073161-fc55df00-b092-11e8-8fa2-4f37f2f07981.PNG)

#
#### What do you suggest instead/what changes do you propose?
GT metals to properly display their name, if at all possible when trying to access their name.

Unless there's another way to go about doing so?

**Comment by boubou19** [comment]
isn't there a "label" field which contains the real name of the item?

**Comment by Teirdalin** [comment]
Not that I can tell, unless it's via a method I don't know.
Most I seem to be able to get is just-
![storeditem](https://user-images.githubusercontent.com/37776581/45074221-77b98f80-b097-11e8-966b-b8ff6ef93acd.PNG)
For non GT items it seems to show the items name properly under display_name.

**Comment by draknyte1** [comment]
Getting localized names from GT items basically won't happen..
Just due to how they work, can't really do much there & it's always been the case.

**Comment by boubou19** [comment]
you must iterate through all the fields and print them to be sure to see all the fields because the way you show them you lack some (it's the meaning of the 3 dots on the screen)

**Comment by Teirdalin** [comment]
Alright, thanks Draknyte.
