### ISSUE TITLE
add mod

### ISSUE THREAD

**Issue by Furryc** [GTNewHorizons/NewHorizons#3570]
Hi, could you add a mod "Rockhounding Mod: Chemistry", this mod about chemistry and gemology?
Sorry for my bad english, I'm from Ukraine

**Comment by Furryc** [comment]
I want more CHEMISTRY)))

**Comment by Dream-Master** [comment]
@Furryc can you link the mod page please?

**Comment by draknyte1** [comment]
Such as?

Telling us more about the mod is helpful.. because any chemistry in it we can just do ourselves in Gregtech))

**Comment by Zoko061602** [comment]
I thoght we decited to not add this mod in gtnh3

**Comment by Dream-Master** [comment]
yea i looking a vid and i have the same feeling @Zoko061602 .

**Comment by Furryc** [comment]
https://minecraft.curseforge.com/projects/rockhounding-mod-chemistry here is a link to mod))))

**Comment by Furryc** [comment]
I just realized how stupid I am, this mod on version 1.10.2

**Comment by Furryc** [comment]
Okay, at least I tried, can terrafirmacraft ??

**Comment by DoomSquirter** [comment]
HAHAHAHHAHAHAHAHHAHAHAHAHAHAHAHAHAHAHHA

ahem
sorry

**Comment by Dream-Master** [comment]
This link is for 1.10 and above. GTNH 2.0 use version 1.7.10

GTNH 3.0 Thread

**Comment by Zoko061602** [comment]
Probably to big to add it at this point

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GTNewHorizons-3.0

**Comment by Furryc** [comment]
Although in my post someone is involved, I'm not alone))))))) "sorry for my very bad English"

**Comment by Dream-Master** [comment]
@Furryc np github is for post issues, modsugestion and other stuff. Feel free to suggest stuff but for 1.7.10 we wont add new mods. The pack are full of mods allready and slowly enough (loading time).

**Comment by Furryc** [comment]
@Dream-Master Okay, whether it is possible to accelerate the loading GTNW? except for "Optifine D6"

**Comment by Dream-Master** [comment]
Optifine and Fastcraft allready accelerate the pack. Nothing you can do more.
