### ISSUE TITLE
How to optimize GTNW??

### ISSUE THREAD

**Issue by Furryc** [GTNewHorizons/NewHorizons#3571]
How to optimize GTNW? except for "Optifine D6"
I have gtx 1060 6gb, i7- 7700k and 16gb of RAM fps 60-50 even 20-10.

**Comment by Bryfer** [comment]
Feel free to ask this kind of questions on our discord server

**Comment by Furryc** [comment]
I'm Ukrainian, no one will understand me plus I do not like to sit in Discord

**Comment by draknyte1** [comment]
Nobody except all the other Russian and Serbian players. :p

Minecraft is a horribly unoptimized game. Doesn't matter how good your PC is, beyond a certain point there's nothing you can do to make it run better. Except rewrite every mod and half of the base game. 

Sorry.

**Comment by Furryc** [comment]
I wonder what is the best "Optifine" for Minecraft ??

**Comment by Dream-Master** [comment]
I using D& and Fastcraft 1.2.3. Other guys using D8 or newer and fastcraft 1.2.5. Idk what are the best version. Much more options to optimazing gtnh i dont see. Fell free to reopen it when there is another option.
