### ISSUE TITLE
BOP's blocks need more support~

### ISSUE THREAD

**Issue by jinshuguangze** [GTNewHorizons/NewHorizons#3572]
#### Which modpack version are you using?
Version 2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
The mod BOP's logs can not take part in wooden doors' formulas,neither in fence gates'.
#
#### What happend instead? (Attach screenshots if needed)
![d d7 2w68 nv j3 mu jc](https://user-images.githubusercontent.com/22865420/45091198-48ad2780-b144-11e8-8fbe-ba17d69c9432.png)
![t_ kbk3y8zwm 0jf j1dhup](https://user-images.githubusercontent.com/22865420/45091256-71352180-b144-11e8-8f40-de534889f61f.png)

#
#### What do you suggest instead/what changes do you propose?
Check all the BOP's blocks and make it more useful.

**Comment by draknyte1** [comment]
> Line 215: val Plank = <minecraft:planks:*>;
`Minecraft.zs`

This should be `ore:plankWood`.
This will resolve most of the recipes.

**Comment by jinshuguangze** [comment]
So it is a Ore Dictionary mistake,right?
...Or people design it on purpose?

**Comment by Dream-Master** [comment]
ordict issue I guess. will check

**Comment by draknyte1** [comment]
Can't say, as I don't know. 
But it may be intentional.

**Comment by Dream-Master** [comment]
@jinshuguangze the problem is there are many gates from Natura so i cant set it like ore:plankWood.

**Comment by draknyte1** [comment]
>there are many gates from Natura so i cant set it like ore:plankWood.

Add all of the Natura stuff into a new oreTag, like gateNatura, then use that in recipes.. saves you 20x the code.

**Comment by Dream-Master** [comment]
not for 1.7.10 anymore. @jinshuguangze 
and @draknyte1 yes code optimation are possible in zs script. Problem is i dont want all natura logs are oredicted because you cant choose a special door made out of a special wood.

**Comment by jinshuguangze** [comment]
Use CustomStuff or just make new special gates in GTNewHorizonsCoreMod~

**Comment by draknyte1** [comment]
> Problem is i dont want all natura logs are oredicted because you cant choose a special door made out of a special wood.

That's why I said make a new OreDict group For the Doors/Gates/Fences.. So they can be used in normal recipes, but are still grouped together only with other Natura stuff.

The alternative is to redo the Natura/bop unique recipes..
Make them cost a normal door/fence/gate surrounded in Natura/bop planks. This solution would also work for the rest of the natura/bop stuff.
