### ISSUE TITLE
Salt for your salty mouth quest not repeatable

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3574]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
Wanted to buy more salt.
#
#### What happend instead? (Attach screenshots if needed)
Couldn't buy more salt.
#
#### What do you suggest instead/what changes do you propose?
Let me buy more salt.

![](https://puu.sh/BqdM2/7e0bfaae00.png)

**Comment by Dream-Master** [comment]
will do :P

**Comment by Dream-Master** [comment]
get out your coins for salt :P
