### ISSUE TITLE
OpenComputers -  Rack   doesn't craft in the assembler.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3575]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft a Rack in an EV assembler with:
1x Relay
1x Power Distributor
1x Wireless Network Card (Tier 2)
2x Plastic Circuit Board
4x Aluminium Rotor
4x Aluminium Item Casing
16k Molten Polyethylene
Inside of it.
#
#### What happend instead? (Attach screenshots if needed)
Nothing.

![assembling machine](https://user-images.githubusercontent.com/37776581/45121599-7b402b80-b116-11e8-8f12-b351c4cdae3d.PNG)

#
#### What do you suggest instead/what changes do you propose?

The recipe to work.

![update](https://user-images.githubusercontent.com/37776581/45123657-72eaef00-b11c-11e8-821f-ca5e1339fc61.PNG)

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
guess this is fixed in a newver version

**Comment by Dream-Master** [comment]
This recipe hast 7 inputs. Maybe thats why :)

**Comment by Teirdalin** [comment]
Thanks Dream. :D
