### ISSUE TITLE
Chunkloader coins

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3576]
#### Which modpack version are you using?

2.0.4.8

#### What do you suggest instead/what changes do you propose?

The chunkloader coins are only craftable in singleplayer, and don't have recipes on servers. I tried finding out how to enable them on my server, but couldn't find a way. It would be nice to have a config option in the dreamcraft.cfg file for enabling coins on servers.

**Comment by richardhendricks** [comment]
Or add instructions to the server wiki page on enabling them.

**Comment by Dream-Master** [comment]
This is a script and not code wise. If it have a config options it need to be hard coded.
