### ISSUE TITLE
Wand Focus: AE Wrench doesn't work anymore.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3577]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### Mod It's From
Thaumic Energistics
#
#### What did you try to do, and what did you expect to happen?
Try to remove some AE parts with my old AE Wrench foci.
Made a new AE wrench focus as well to see if my old one just wasn't working.
_
The foci to laser them apart.
#
#### What happend instead? (Attach screenshots if needed)
Nothing at all.
#
#### What do you suggest instead/what changes do you propose?
Figuring out why they stopped working.

**Comment by Dream-Master** [comment]
Are this working with a older version @Teirdalin of Thaumic Energistics.

**Comment by Dream-Master** [comment]
Can you post your issue here please @Teirdalin 
https://github.com/Nividica/ThaumicEnergistics/issues
Thanks

**Comment by Teirdalin** [comment]
Not sure if it was an older version of Thaumic Energistics, but it worked before the bee update that came with infinity and other bees; however long back that was.

**Comment by Dream-Master** [comment]
@Teirdalin yes we update Thaumic energistics in the past. Can you open and issue on Thaumic Energistics side please. Thanks
