### ISSUE TITLE
Kick the Mod [Not Enouh Keys]

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#358]
After i had a lot of trouble (using some key bindings to quick) i crash many times i would to suggest to delete this mod out of our pack.

What do you think.

**Comment by Namikon** [comment]
I tend to change key bindings a lot, depending on the mod i'm currently playing. Dunno, If it still displays the conflicting keys, why not. I never saw that mod list anyways, seems to be broken since forever

**Comment by Dream-Master** [comment]
yes it shows the conflicting keys in vanilla too.

**Comment by Dream-Master** [comment]
done
