### ISSUE TITLE
Coin Mold / Coin Shape on official Servers

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3580]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta & Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft the Everglades Portal, cant make the Alkalus disk since you need the Coin Mold / Coin Shape which is uncraftable.
#
#### What do you suggest instead/what changes do you propose?
Re-Add the Coin Mold / Coin Shape.

**Comment by Dream-Master** [comment]
ok will add.
