### ISSUE TITLE
Suggestion: Filter Room (new controller using an existing room)

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3583]
#### Which modpack version are you using?
2.0.4.6

This is just an idea I had.  Late game you start to get rid of the need for the cleanroom by using multiblocks and processing arrays.  But that introduces a new challenge with pollution so I thought, what about if we repurpose the cleanroom?

Similar to the issue mentioned previously on pollution not affecting players inside the cleanroom; https://github.com/GTNewHorizons/NewHorizons/issues/3188, my suggestion would be the opposite:

**Suggestion**
A new 'Filter Room' controller that can directly replace the Cleanroom controller.  Maybe Smog Room? :)

**Construction**
The same as the cleanroom (plascrete/filter casings).  This would allow players to 'repurpose' their obsolete cleanroom late game.

**How it works**
In the Filter Room you can build multiblocks with muffler's that **cause** pollution (like the Implosion Compressor).  The pollution would be contained inside the Filter room and has the same status effects as it normally would on the player if they are outside the Filter room.

Since multiblocks need maintenance, the player would still need to enter the cleanroom and they can hang up the hazmat suit nearby.

This suggestion can obviously be expanded on.  I have a second suggestion for the cleanroom which I will make a new ticket for regarding windows.

**Comment by draknyte1** [comment]
Without recoding pollution, it's not possible. 

It's also impossible to easily support the infinite multis that do/will exist. Since the cleanroom is also horribly coded, may as well recode it while you're at it.

**Comment by 0lafe** [comment]
PAs don't make pollution. Lategame my only pollution generating structures were a few pyrolyse ovens, which wasn't too much to deal with.

**Comment by richardhendricks** [comment]
Yeah I think I'd like a mid-late tier multiblock pollution scrubber.  Input is water/distilled water, output is polluted water.  Polluted water can be distilled (EV) for distilled water, carbon dust, sulfuric acid, nitric acid. Could have it use plascrete and filter casings for the construction, so that cleanroom parts could be recycled.  It would use turbine rotors like the singleblocks, but with much higher efficiency/lifetime.  Maybe make it suck pollution out of an area of blocks set by tier? EV = 1, IV 3x3, etc?

**Comment by draknyte1** [comment]
There *is* a multiblock pollution remover already?..

**Comment by draknyte1** [comment]
Also, multi chunk is bad because we don't want it force loading chunks. Why mine don't.

**Comment by 0lafe** [comment]
Doesn't that one just kinda suck though? Also couldn't they work like miners where they have big ranges but don't chunkload?

**Comment by Dream-Master** [comment]
Tec added a block for pollution in the core mod if i rember right a air filter.

**Comment by bartimaeusnek** [comment]
Can't we (me  just add the cleanroom need for Multiblocks? @draknyte1

**Comment by 0lafe** [comment]
That's also a good idea

**Comment by draknyte1** [comment]
@bartimaesnek I won't, ever. 

They're self contained cleanroom as far as I'm concerned. I chose to exclude the requirement from day one, also to continue support for 5.08 and excessive code requirements for such support.

**Comment by 0lafe** [comment]
What about just disabling cleanroom recipes in your multis then, and make PAs require a cleanroom

**Comment by draknyte1** [comment]
Because you still need a cleanroom for circuits and the rest are in their own expensive multis, so that's illogical.
