### ISSUE TITLE
Suggestion: Cleanroom structure can allow X*height number of Reinforced Glass?

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3584]
#### Which modpack version are you using?
2.0.4.6

So I like the cleanroom but I'd like it better if we had the ability to see inside!

I'm curious if it would be possible to add a type of glass to the possible components?

Edge casings would always be Plascrete but maybe there would be X number of Reinforced Glass allowed depending on the height of the cleanroom?

Thoughts?

**Comment by Dream-Master** [comment]
Possible is everything if someone code it :)

**Comment by Teirdalin** [comment]
That'd be pretty cool.

**Comment by bartimaeusnek** [comment]
@Dream-Master you can now set a  Plascrete % in the config, that is allowed to be Reinforced Glass (5% default)
