### ISSUE TITLE
Suggestion: Make hunger a bit harder to manage early-mid game // make pams harvestcraft better somehow.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3585]
#### Which modpack version are you using?
2.0.4.6
#
#### What happens currently?
Hunger is too easy to manage without eating.
People make stacks of canned food at LV, which bypasses Spice of Life using any easy to get food they want.   Or people get a healing axe as soon as they find an enchanting table in a dungeon.
#
#### What do you suggest instead/what changes do you propose?
Make the healing axe recipe an infusion and more late game-  reasonably more powerful and way cheaper than the other hunger filling options just taking 3 diamonds and 3 iron and a couple pieces of obsidian to make.

Make (filled) tin can effected by Spice of Life or harder to make,

Currently Pams harvestcraft is really almost never used by anyone who doesn't just farm for the fun of it; and considering it adds 541 items-  it just seems a waste honestly.

**Comment by Dream-Master** [comment]
@Teirdalin Tin can not compatible with hunger overhaul/spice of life. I moved it allready to hv.

**Comment by richardhendricks** [comment]
Yeah, we already did this a while ago.  

https://github.com/GTNewHorizons/GT5-Unofficial/commit/de518f9c8b2baf5cb748a43813e2748ff59917b3
https://github.com/GTNewHorizons/NewHorizons/issues/2821

@Dream-Master Did we make an HV canner quest for tinned food? We can use this ticket to track that.

**Comment by Dream-Master** [comment]
so far i know we have a food quest but double check it.

**Comment by Teirdalin** [comment]
Ah I see.   Still fairly easy to get the healing axe,  especially since the sigil drops in dungeon chests.

**Comment by Dream-Master** [comment]
HV

**Comment by richardhendricks** [comment]
4.6 I believe is when HV canner was moved.  Do we want to keep the healing axe available so early in the game?  Should it require more steps or actual HV/EV processsing?

**Comment by Hakameda** [comment]
Or remove exu

**Comment by noobyaran9** [comment]
Disable the healing axe recipe or make it accessible in later in game.
Since you will be given an axe on completing a quest thats ask u gather bunch of food. If u lost the axe then thats it. *unless the quest is removed
