### ISSUE TITLE
Suggestion: Make Lightning Rod Less Unreasonable to Craft

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3586]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What wrong with the current items?
Lightning rods are garbage.  4 UV batteries, a UV hull, and 4 UV/UHV transformers to make an IV gen?
Hydro/Wind is easily more affordable, more stable a power source, and just in general better in every way. Infact; anyone at UV won't even be bothering with an IV outputting gen in general.
#
#### What do you suggest instead/what changes do you propose?
To make lightning gens +1 Tier instead at most, and add upto a LuV gen which takes ZPM materials.
There are just too many better alternatives for the cost to justify the machine.

**Comment by draknyte1** [comment]
The lightning rod isn't IV, if it is it's outputting 100A or some rediculous amount.

**Comment by draknyte1** [comment]
They're 512A output after a quick Squizz of the code.

**Comment by 0lafe** [comment]
Is it possible to get them almost constantly running by setting it to always storm or something?

**Comment by draknyte1** [comment]
You can use magic to make it rain more afaik..

**Comment by bartimaeusnek** [comment]
Vampirism, Wand Focus Weather... There are options

**Comment by Teirdalin** [comment]
Ahhh, didn't realize it had such a high amp.

**Comment by draknyte1** [comment]
If you can extract 512A per tick, that's 4,194,304EU/t..

**Comment by 0lafe** [comment]
yea thats why I was wondering about constantly powering it. From the gt4 wiki page it seems like it just sucks, but idk if it got changed or something. Says like 6% per lightning to generate 25M eu which is only like 6 ticks of power at that voltage and I can't really see you naturally getting that many lightning bolts per tick

**Comment by Teirdalin** [comment]
Encouraging people to spam endless lightning sounds like something I imagine any server would love.

**Comment by draknyte1** [comment]
I get some weird feeling they'll generate lightning when certain conditions are met. 


Read `onPostTick()`
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/generators/GT_MetaTileEntity_LightningRod.java

**Comment by Teirdalin** [comment]
Maybe we could have a magic alternative for lower tier lightning energy, as tech cannot really logically allow for it.

**Comment by bartimaeusnek** [comment]
@Teirdalin there is, Aqua Solar Panels from EMT, i just re-coded a few patches ago them.

**Comment by Teirdalin** [comment]
Oh, they work with lightning now too and not just rain?

**Comment by bartimaeusnek** [comment]
with thunderstrom, not quite lightning...
