### ISSUE TITLE
Recipe to craft Wormwood Seeds consumes mutating sprig

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3587]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft Wormwood Seeds with my nearly full durability mutating sprig, wheat, and 4 wispy cottons in the crafting grid.

It to craft the seeds and damage the sprig.
#
#### What happend instead? (Attach screenshots if needed)
It crafted the seeds, consuming the mutating sprig.
#
#### What do you suggest instead/what changes do you propose?
It to damage the sprig as much as a normal mutation would, and produce the seeds.

**Comment by Dream-Master** [comment]
witchery is closed source you know :)

**Comment by Zoko061602** [comment]
Why cant we use minetweaker ?

**Comment by Dream-Master** [comment]
@Zoko061602 if this is possible why not. Make a pull request :)

**Comment by Zoko061602** [comment]
We are already using minetweaker, everything works just fine

**Comment by Rika-TH** [comment]
This is still a thing, this being the way to get seeds without the quest book it should be considered if possible
