### ISSUE TITLE
[Suggestion] More realistic Nuclear fuel processing

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3588]
#### Which modpack version are you using?
2.0.4.9
Currently, enriched nuclear fuel (Normal and MOX) is manufactured in a assembling using refrigerant.
![image](https://user-images.githubusercontent.com/35035276/45258169-f7a76880-b3bb-11e8-8905-848f94543c7f.png)
 If you look at how nuclear fuel is actually made, then the recipe is very illogical.
What does the core filler look like.
![image](https://user-images.githubusercontent.com/35035276/45258183-4bb24d00-b3bc-11e8-9433-ff15a2af885e.png)
The fuel mixture is first compressed and then fired (in hydrogen), after which the rods are already filled.
Therefore, I propose that the fuel be transferred from the assembling to the blast furnace.

**Comment by bartimaeusnek** [comment]
So how about we change this to:
1. Asssembler: U238 + U235 -> Raw Uranium Fuel
2. Compressor: Raw Uranium Fuel -> Compressed Uranium Fuel
3. Blast Furnace: Compressed Uranium Fuel + Hydrogen -> Hot Uranium Fuel (will cause burns without gloves / Hazma Suit)
4. Canning Machine: Hot Uranium Fuel + Fuel Rod -> Uranium Rod

**Comment by bartimaeusnek** [comment]
But the tablets are hot arent they? The Hazma Suit also shield from heat.

So, does this looks better than?

1.    Mixer: U238 + U235 + small pile of Graphite -> Raw Uranium Fuel
2. Vacuum Freezer: Raw Uranium Fuel -> Cooled Raw Uranium Fuel
3.    Compressor: Cooled  Raw Uranium Fuel -> Compressed Uranium Fuel
4.    Blast Furnace: Compressed Uranium Fuel + Hydrogen -> Hot Uranium Fuel (will cause burns without gloves / Hazma Suit) (16min = 20h IRL at 1600K)
5.    Canning Machine: Hot Uranium Fuel + Fuel Rod -> Uranium Rod

**Comment by Vernam** [comment]
@bartimaeusnek Is it justified for so many movements?
I do not think it's worth so much as rushing into realism.

**Comment by Dream-Master** [comment]
why not realism?

**Comment by CalterOK** [comment]
@bartimaeusnek Still cooling of the processes I would have removed, many of which melts at the same temperature but does not require cooling. And since the blast furnace will require a considerable amount of time and energy, the remaining processes must be performed quickly (1-2 seconds), and the required voltage in the blast furnace is about 60 Eu / t (this is due to the cost of making rods, we have them burned in less than 3 hours, and in reality about 5 years).
