### ISSUE TITLE
Gold Capped Greatwood Wand can be crafted the regular way

### ISSUE THREAD

**Issue by EmeraldsEmerald** [GTNewHorizons/NewHorizons#3591]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
Single-player
#
#### What did you try to do, and what did you expect to happen?
I tried crafting a Gold Capped Greatwood Wand, thinking I will need the tweaked recipe with Lich bones.
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/40524065/45263141-42f56180-b424-11e8-8715-43ad3ad97db4.png)
This showed up in the GUI, indicating I can craft with the regular recipe.
I proceeded to craft it, and it worked with no issues.
#
#### What do you suggest instead/what changes do you propose?
Remove this recipe and force the Lich Bones recipe to be the only possible one.

**Comment by Dream-Master** [comment]
@Zoko061602 i thought all original recipes are removed ? Any idea ?

**Comment by EmeraldsEmerald** [comment]
@Dream-Master Just a hunch, but maybe it's because the GTNH coremod's wand caps were removed? 
That would leave default AND tweaked thaum recipes in due to the cap not being GTNH's, but Thaumcraft's.

**Comment by Dream-Master** [comment]
why the mod was removed ? @EmeraldsEmerald

**Comment by EmeraldsEmerald** [comment]
@Dream-Master The mod is still in. The mod's wand caps were removed.

**Comment by Dream-Master** [comment]
Yes and the tc wand mod should remove this recipes not in nei but the crafting ones.

**Comment by EmeraldsEmerald** [comment]
I'm lost too on why the wand mod doesn't seem to work then.

**Comment by Dream-Master** [comment]
i ask the mod dev and wait for an answer

**Comment by Teirdalin** [comment]
Were you testing this in creative or survival using the crafted recipes?

**Comment by Dream-Master** [comment]
Try this version
https://github.com/GTNewHorizons/GTNH-TC-Wands/releases/download/1.0.4/GTNH-TC-Wands-1.0.4.jar
