### ISSUE TITLE
Unnecessary Suggestion:  Melted Chocolate Liquid // Chocolate Milk Liquid

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3592]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
Was making a chocolate factory, couldn't find any liquid chocolate to make a moat with.
#
#### What happend instead? (Attach screenshots if needed)
Ended up posting on github. 
![github](https://user-images.githubusercontent.com/37776581/45264840-addc7380-b3f7-11e8-936b-12291e56d744.PNG)
#
#### What do you suggest instead/what changes do you propose?
Some sort of liquid form of chocolate for those of us who require a chocolate river. 

Maybe it could be drank (right clicked) to consume the liquid source block and fill 1 hunger and give speed II.
(Optional just to make it less completely cosmetic based)

Recipe could perhaps be from putting Pams chocolates into a fluid extractor.

Perhaps could solidify the chocolate back into a chocolate bar with an ingot mold, as well as to potential other chocolates using the different shapes with a solidifier. 

Could make an interesting process-  

Chocolate melts into liquid, sent to flood gate, fills moat,  pump pulls chocolate from river, solidifies into any sort of chocolate, flood gates refill moat.

**Comment by Bluebine** [comment]
haha yes

**Comment by richardhendricks** [comment]
Liquid chocolate?  Shouldn't quite be hot enough to burn you.

**Comment by Dream-Master** [comment]
need gloves to drink :P
outch burn you mouth :P

**Comment by richardhendricks** [comment]
Hmmmm...What would be interesting are more glowing fluids other than lava. Can molten glowstone flow? Pahoehoe?

@Dream-Master You can eat melted chocolate! https://www.amazon.com/Wilton-Chocolate-Pro-Fountain-Capacity/dp/B000OP623U/ref=asc_df_B000OP623U/?tag=hyprod-20&linkCode=df0&hvadid=167155690034&hvpos=1o2&hvnetw=g&hvrand=12449618882955587941&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9060225&hvtargid=pla-273692483006&psc=1
