### ISSUE TITLE
New Hull recipes for LuV - UHV

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3593]
#### Which modpack version are you using?
2.0.4.9
#
#### What do you suggest instead/what changes do you propose?

The prices are pretty low for the LuV-UHV machine hulls, all using materials that aren't really in the same tier. Osmium for UV, but it's smeltable/obtainable in IV with almost no problem. 

My idea for LuV is to use osmiridium. Making the dust is easy in the tier, and it takes LuV to smelt. Chrome the current material is something I just made in HV. 

For zpm, naquadah alloy seems like a better idea. Takes zpm to smelt and trinium is something that you start getting around those tiers. 

For UV, neutronium while a zpm recipe takes as long to smelt in UV, as naquadah alloy does in ZPM. Much better than osmium which is much more an IV material. 

UHV uses the new reinforced neutronium thing that I suggested to dream. It's a neutronium dust and 36L Tritanium to make the dust which smelts in 300s at UHV

![screenshot_20180909-155826 2](https://user-images.githubusercontent.com/21280852/45268600-a85d4880-b44c-11e8-8a49-f76286fcc002.png)

Uh also assembly line because, high tier

**Comment by NeroOneTrueKing** [comment]
I don't like several parts of this.
1) It uses plates instead of machine casings
2) It uses a fluid other than soldering alloy, when most assembly line recipes need a soldering alloy as their first fluid
3) ZPM+ should use PBI, not PTFE
4) Machine hull assembly cost scales with tier of hull being assembled

Revisions:
1) Use a machine casing instead of plates
2) Use 288L soldering alloy in the first fluid slot
3) Use 4 sheets of the appropriate plastic (PTFE for LuV, PBI for ZPM+)
4) Use IV power for all recipes

**Comment by 0lafe** [comment]
>ZPM+ should use PBI, not PTFE

Until PBl is redone to actually be high tier, I suggest staying away from it and not relying on it by any means. 

>It uses a fluid other than soldering alloy, when most assembly line recipes need a soldering alloy as their first fluid

Not really sure how much this impacts it, and no hull uses solder right now either. 

>It uses plates instead of machine casings

Good idea I'll change that 

>Use IV power for all recipes

Other than making it faster, I'm not sure why that matters as much. They're already tiered down one. It's fairly normal to have an assembly line at least 1 tier below you, if not the same tier, so I don't think it'll stop anything. What about 5s or 10s instead?

**Comment by NeroOneTrueKing** [comment]
Re PBI:
It's got a whole line of quests to make it in the IV tab of the book, now. It might not be as expensive as you'd like, but it certainly is a long process. It's not that important to me.

Re Soldering Alloy:
I don't have minecraft open right now to check the recipes, but as I recall, most assembly line recipes need soldering alloy in the first fluid hatch. Certainly all of the machine parts do, and machine parts didn't need any soldering alloy until LuV either. It would also be very annoying to need to keep the first fluid hatch empty so I can switch between putting in molten PTFE and molten soldering alloy.

Re IV Power:
There's no reason for hull assembly to be energy-intensive. IV is a "low" cost for assembly line recipes, and if it's expected that you'd have at least a tier-1 energy hatch anyways, there isn't any additional pressure on the player by making the recipes need more power.

**Comment by 0lafe** [comment]
>PBl

I think once the recipes are retiered then it absolutely should be the high tier plastic, or something else should if they really want PBl to follow its real life recipe. What if PTFE was for EV-LuV though? 

>Solder

Idk, I feel like it's the same with a normal assembler. A lot of recipes take solder but you can't always leave your solder in there for every recipe. Either have to automate it, or only put in how much you're gonna use. There's a bunch of other assembly line recipes that don't take solder there, it's really just the motors and stuff like that. 

>IV power

Alright. IV is fair

**Comment by richardhendricks** [comment]
Don't forget there is a 16B handpump available now.
