### ISSUE TITLE
Energy hatch cost increase 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3594]
#### Which modpack version are you using?
2.0.4.9
#
#### What do you suggest instead/what changes do you propose?
Increase the cost of energy hatches so upgrading multiblocks has a significant cost associated with it.
![screenshot_20180909-164912 2](https://user-images.githubusercontent.com/21280852/45268825-f83e0e80-b450-11e8-9c74-39cbcc1fe803.png)
![screenshot_20180909-164920 2](https://user-images.githubusercontent.com/21280852/45268826-fc6a2c00-b450-11e8-92a5-64b49b09c5f8.png)

Some recipe suggestions

**Comment by bartimaeusnek** [comment]
This would gate the pure tear from EV -> LuV.. dunno

**Comment by 0lafe** [comment]
More like IV because you can put 2 IVs together to make an LuV

**Comment by Bluebine** [comment]
no thank you please
this would just be really annoying while not actually gating anything

**Comment by 0lafe** [comment]
>while not actually gating anything

It gates having a hatches to the tier you're in, so you can only ever really overclock something 1 tier above the assembler you have. It also makes hatches have a cost, and considering they're all that you upgrade in any multiblock that isn't the PA, it also gives that a cost.

**Comment by Scottishprog** [comment]
That would hard gate hatch improvements behind that level assembler.... Not sure that's a good idea. 

Cost increase?  Perhaps.  
Need to be able to upgrade some multiblocks before the associated assembler level - too constraining otherwise. I would be really careful with this one.

**Comment by 0lafe** [comment]
>Need to be able to upgrade some multiblocks before the associated assembler level - too constraining otherwise. I would be really careful with this one

+1 yeah, but what needs 2 above assembler other than trying to get the pure tear in EV 

>That would hard gate hatch improvements behind that level assembler.... Not sure that's a good idea

Kinda. But your hatches can already do a tier up

**Comment by Scottishprog** [comment]
Put it another way, what is wrong with Pure tear in EV?

**Comment by Scottishprog** [comment]
I really not seeing the need.
Why do the energy hatches need to cost more?  What is the goal that this change will advance?
And why the circuit cost? I have enough demands on them already.

**Comment by 0lafe** [comment]
>Why do the energy hatches need to cost more

To make upgrading multiblocks cost something. Right now, you make a bunch in HV-IV and they stay with you, no changes besides maybe better fluid/item hatches, and of course better power. It makes a fairly big difference with the multiblock but costs almost nothing. A machine hull and a single cable. 

>What is the goal that this change will advance

1, make upgrading multiblocks have a larger cost. 2, gate hatches to the tier your in, and the input to your multiblocks at 1 above that. Good for stuff that takes a small amount of power for the tier. Like macerators. 

>And why the circuit cost? I have enough demands on them already.

Not really sure of a better costly single item that scales well with tiers. If there is one I don't really mind one way or the other which gets used

**Comment by Scottishprog** [comment]
Fair enough.

I can stand behind increased cost. Perhaps even have a core/block in lieu of more circuits. (A new intermediate item in other words.)

I am _not_ a fan of the tier restriction. That is a fairly fundamental change in the progression, and I am concerned about unintended effects. Think it should always be possible to "reach up" if you want to spend the resources.

**Comment by 0lafe** [comment]
>I am not a fan of the tier restriction. That is a fairly fundamental change in the progression, and I am concerned about unintended effects. Think it should always be possible to "reach up" if you want to spend the resources.

I think of it the same as single blocks. You can't reach up because ideally you can't make the resources you'd need. You can always do that by just making more of them. Let's voltages be used as a more effective gate. You can always reach up and spend the resources to make the machines to make the hatches. 

You can't make an LuV assembler in EV, but you can make an LuV assembler multiblock. I don't get how that makes sense. It doesn't stop you from going as fast as you want with any recipe, even if you have the power you can still always use it by making more multiblocks. It just stops you from doing recipes with voltages 2 tiers past you, which I like. I can't think of anything that you make 2 tiers earlier other than the pure tear, and even that you don't need at EV

**Comment by Scottishprog** [comment]
Looking at it from another angle:

I would like to preserve the choice of capturing a higher tier capability now at a high relative price, or wait until you actually have tiered up, and capture that capability at a lower relative price.


So the real question is: how important is it to preserve strict tier progression at the EV+ ranges? (At least for some multiblocks)

Unfortunately I can only speculate here, because I have not reached that level yet. My impression however, it that things are complex enough as is, without a strict tier progression to bog things down further.

**Comment by 0lafe** [comment]
>Unfortunately I can only speculate here, because I have not reached that level yet. My impression however, it that things are complex enough as is, without a strict tier progression to bog things down further.

As someone who went through them I'd say it's the other way around. The tier progression is so loose/the requirements per tier are so low that you just breeze through them. Strict tier progression is one of the biggest things that's missing in that range.

**Comment by Zoko061602** [comment]
I don't think that changing the materials required for energy hatches solves any problems in LuV+
When I look at anything above IV it feels kinda monotone, like:
 go to planet A, get ressource B, update EBF to X eu/t , etc.
Just compare this to HV, make different fuels , automate tnt for a rocket, get started with actual TC progression.
I think the main problem at LuV+ is, that you've already done most of the gameplay, like TC, EIO or AE, but I don't think that this gets solved by stretching everything else out.

**Comment by 0lafe** [comment]
>I don't think that changing the materials required for energy hatches solves any problems in LuV+
When I look at anything above IV it feels kinda monotone, like:
go to planet A, get ressource B, update EBF to X eu/t , etc.
Just compare this to HV, make different fuels , automate tnt for a rocket, get started with actual TC progression.
I think the main problem at LuV+ is, that you've already done most of the gameplay, like TC, EIO or AE, but I don't think that this gets solved by stretching everything else out.

Yea.... Those are problems with high tiers, and it gets worse when you stop upgrading the ebf or going to planets. Changing hatches isn't meant to fix the entirety of late game issues. It solves the problem of your multiblocks being too cheap in that tier, which adds stuff to do, which i can only see as a bonus in this way. 

>I would confine the changes to HV+ then.
The tier restrictions seem effective at my level. Especially on the power generation side!

So just not MV and LV? I mean, I guess but you don't really make multi blocks until MV, and then you really just make 2LV, and making some circuits for that is doable. Never really a time making the one for your tier is an issue.

**Comment by Scottishprog** [comment]
I can see your point.

However, to Zoko's point, let's have some carrot to go with the stick.
What can we add that makes jumping through the added hoops worthwhile?
As opposed "That's all the same grind, I am done." and quitting before finishing.

**Comment by sthegreat** [comment]
I'm fine with the assembler requirements, however I'd like to suggest a few changes with the recipes:

-Use a machine hull instead of 8 plates for consistency with other hatch recipes

-4 circuits is an annoying amount early on, I think 0-2 would be better for early tiers

**Comment by 0lafe** [comment]
>However, to Zoko's point, let's have some carrot to go with the stick.
What can we add that makes jumping through the added hoops worthwhile?
As opposed "That's all the same grind, I am done." and quitting before finishing.

that's much more in the realm of other stuff I've been thinking about/other stuff that's being added. New circuit tier coming, makes zpm easier to make which is nice. I've been thinking of some late game naq processing like oil processing, to make plastics, fuels and shit like that. Barts adding lategameish thaum reliant generators that bring thaum more into the late game and encourage more of that early game reliance on more than just GT. There's other stuff that's probably gonna be added too, but this energy hatch thing is semi unrelated to that. It's just making something a little harder, that has been too easy for a while. 

>I'm fine with the assembler requirements, however I'd like to suggest a few changes with the recipes:

-Use a machine hull instead of 8 plates for consistency with other hatch recipes

-4 circuits is an annoying amount early on, I think 0-2 would be better for early tiers

could easily be like solars and increase in cost with tier, super easy considering LuV+ uses the assembly line. Hulls sounds good, I'll try to make some better recipes real quick

**Comment by 0lafe** [comment]
![capture](https://user-images.githubusercontent.com/21280852/45272950-271ea980-b47e-11e8-8c4b-7fbc30d19299.PNG)

**Comment by richardhendricks** [comment]
It would make more sense to add more multi classes like the ore drill, large turbines, and oil drill instead of doing this. Like a basic EBF that can only take cupronickel and kanthal, but the advanced one that unlocks at HV can take those and nichrome and tungstensteel, and high tech one that takes HSS-G/Naq/etc.  

Similar for vacuum freezer, pyro, etc. It would require coming up with all new casings and recipes for them at the respective tiers.

**Comment by 0lafe** [comment]
>It would make more sense to add more multi classes like the ore drill, large turbines, and oil drill instead of doing this. Like a basic EBF that can only take cupronickel and kanthal, but the advanced one that unlocks at HV can take those and nichrome and tungstensteel, and high tech one that takes HSS-G/Naq/etc.

Similar for vacuum freezer, pyro, etc. It would require coming up with all new casings and recipes for them at the respective tiers.

If that's doable for all the gt and gt++ multiblocks, then yea that's better and I'd rather do that.

**Comment by ScriptedPiky** [comment]
So what you're saying is I'm going to use a total of 1088 superconductors for a single UHV energy hatch? (Wetware mainframe) The cost for that would total up to 102 ZPM motors/pumps, 592 ZPM superconductor, 64 Tritanium, 256 wetware circuit boards in total, 128 neuro processors (2048 stem cells) and other considerable resources for the total of a single UHV hatch. No way.

I get that it's supposed to be expensive, but honestly, that just enforces people to go multiple UV hatches, hell, even ZPM hatches cause it's just so ridiculously expensive.

**Comment by 0lafe** [comment]
>So what you're saying is I'm going to use a total of 1088 superconductors for a single UHV energy hatch? (Wetware mainframe) The cost for that would total up to 102 ZPM motors/pumps, 592 ZPM superconductor, 64 Tritanium, 256 wetware circuit boards in total, 128 neuro processors (2048 stem cells) and other considerable resources for the total of a single UHV hatch. No way.
I get that it's supposed to be expensive, but honestly, that just enforces people to go multiple UV hatches, hell, even ZPM hatches cause it's just so ridiculously expensive.


The motors/pump total cost is 1862 HSS-E, 612 enderium, 408 solder, 408 silicone ingots, 102 sammarium, 3,264 platinum, 816 vanadium gallium, and 153 buckets of lube. Mixing the HSS-E won't take more than 2min, the cost of it is again almost nothing, mostly just costing steel/tungsten, but barely any of that. Smelting it will take less than an hour. You're looking at about 3min for all the motors to be done, then another 3min for the pumps in the assembly line.

The price of the zpm super conductors are 46 osmium, 92 indium, 184 naquadah and 276 palladium. Not even ingots, dusts. If you're in a tier that you're worries about UHV hatches, you're pumping out at least 832 zpm super conductor base a minute, so the whole craft of the base is a minute. Ebfing the dust is gonna take you less than 5s per dust, putting you at less than an hour to smelt. Making the zpm superconductors themselves puts you at minimum 1.25s per wire which is almost half the time of smelting them, and can easily be done in under 10min for less than an amp of UHV. Making the UHV conductors will take you only 14min at zpm and 3.5 at UV, a tier below the hatch that's being made. 

Making the mainframes in the assembly line is only gonna take you about 3min which isn't much. The NPU's are gonna take around 8min, but in all that's under 2h, and almost no material cost, for essentially what is a UHV multiblock. Not to mention none of the multiblocks assumed in my time estimates used a UHV hatch, and only the assembly lines and 2 processing arrays were assumed to have a UV hatch, the rest was all ZPM or lower. Using gt++ multiblocks will also lower this time by a fair amount. You don't really at this point need tons of UHV hatches, you're right that you'll mostly rely on UV and below, but that's true regardless of this change. Not many things benefit from using a higher tier hatch, except now they can be used to gate recipes for higher tiers, without relying on single block machines. 

The higher times here mostly just show the problems with the ebf currently. Those will almost always be your highest times because of how terribly it scales. Everything else is under 15min. Compare that to crafting an LV machine in LV and it's under it I'd say.

**Comment by draknyte1** [comment]
> If that's doable for all the gt and gt++ multiblocks, then yea that's better and I'd rather do that.

It's never happening for GT++.

Energy/Dynamo hatches have zero cost besides a Machine Casing and a single cable.
The cost increase for these was suggested by myself to @0lafe and there's really no reason for anyone to disagree that they're currently cheap as chips.

I'm limited to 64 Machine casings in total, so, as I already have 50, this cannot possibly occur.
We could always add a new bus type with a single slot that holds a tiered control circuit of a sort. Effectively limiting multis to this tier. Some structures wouldn't need this bus at all, like the EBF. I would happily support this though.

**Comment by Dream-Master** [comment]
on the one hand people complain about op quest book with coins and lootbags on the other side people complain if a dirt cheap hatch recipe are change 🤔

**Comment by draknyte1** [comment]
Nerf everything ;)

The main issue is, that changing a hatch is all it takes on some multis to tier up. Since when is a little extra cost a bad thing?

**Comment by Dream-Master** [comment]
I will find a nice recipe for the energy hatches.

**Comment by Dream-Master** [comment]
Sure my english i'snt the best we can chat in the future in german if you like :P @DoomSquirter 

As i said will find some recipe.

**Comment by richardhendricks** [comment]
Why not go all the way?

Add conveyors and pumps and tiered tanks/chests to buses and hatches?

Make all multis use coils and have those coils determine tier?

Make all multis use the lowest hatch/bus/muffler tier to determine their tier?

**Comment by 0lafe** [comment]
>Add conveyors and pumps and tiered tanks/chests to buses and hatches?

I'd love item/fluid hatches to be expesnive but they need much higher storage. Items for one would need to actually increase past HV, or just remove all the others I don't get the point. Fluid storage should return to the pre 2.0 numbers, but that's also just a general complaint I have about fluid hatches. At least when you have to upgrade the energy hatch there's a tangible benefit unlike item/fluid most of the time. 

>Make all multis use coils and have those coils determine tier?

That'd be nice too, if that's doable and someone wants to add those I'm more than onboard.

**Comment by NeroOneTrueKing** [comment]
Don't tier-limit assembly of hatches. Being able to build some over-tiered stuff is nice.

Don't use circuits for making standard solid/fluid/energy buses/hatches. Circuits are expensive and don't make sense for being part of most of those blocks anyways.

Requiring a conveyor belt is okay for in/out buses IF high-tier buses have more storage space.
Add super-cheap ULV-tier in/out buses that have 1 slot of space.

Requiring a pump is okay for in/out fluid hatches IF they all have much more storage space.
If you need a tank, the corresponding hatch had better have ALL of that tank's storage space.
Add super-cheap ULV-tier in/out fluid hatches that have a small amount of space.

Want to make energy hatches more expensive? Look at some of the parts that go into transformers: Nothing, small coils, PIC chips, HPIC chips, etc.
More cables, but use tier-standard ones.
Don't make energy hatches the expensive part of up-tiering multiblocks, though, yuck.

**Comment by 0lafe** [comment]
>Don't make energy hatches the expensive part of up-tiering multiblocks, though, yuck.

Then what should be the expensive part. What else gets changed? 

>Add super-cheap ULV-tier in/out fluid hatches that have a small amount of space.

I think part of the idea of the change to buses/hatches is that you need all the same ones of a tier, so even if ULV ones exist, they'd be almost useless. If you don't need to upgrade your hatches to use higher voltages, I couldn't care less about the cost. 

>Make all multis use the lowest hatch/bus/muffler tier to determine their tier?

I support increasing cost for fluid/item stuff if this comes too, but otherwise I don't really see the point. The idea is to increase the upgrade cost of all multiblocks. You barely upgrade hatches/buses, but I'd be more than happy for you to be required to, then the cost of those hatches starts to matter more.

**Comment by NeroOneTrueKing** [comment]
Upgrading buses/hatches doesn't make sense to be the expensive part of up-tiering a multiblock. They're literally just there for input and output of items, fluid, and energy. The expensive part needs to be something new. A special hatch, like Draknyte suggested, or coil-like blocks, like richardhendricks suggested. 

The current recipes for hatches are boring and very cheap past LV/MV.
These suggestions make them a lot less boring and slightly less cheap by using appropriate parts to make the buses/hatches. The problem of "very cheap" should be addressed by something else.

I suggested ULV-tier buses/hatches thinking you would be able to mix-and-match hatch tiers. You're right that they would be quite useless if that was required.

**Comment by 0lafe** [comment]
If someone wants to go through and add coils to every single multiblock and make coils that go with tiers better than what we have right now then I'm on board with that and keeping hatches as they are. A control circuit seems fine too, but it's gotta be expensive. Not just like, put HV circuit in for HV power.

**Comment by draknyte1** [comment]
Morons idea is 100% impractical and has 0% support from me. I simply won't ever implement such changes. 🤷🏻‍♂️

Ever seen my control circuit? It's for IV and is not overly cheap at all. Food for thought.

**Comment by 0lafe** [comment]
>Ever seen my control circuit? It's for IV and is not overly cheap at all. Food for thought.

Yea, saw it when looking at the LFTR a while back. My only question about it looking at the recipe, does it oredict circuits? nei only shows nanoprocessor mainframe as an option which is a circuit made in EV. If some of the numbers are increased, I'm fully on board with like 4x field gen + 4x circuit of T+1

**Comment by DualBallers** [comment]
> We could always add a new bus type with a single slot that holds a tiered control circuit of a sort. Effectively limiting multis to this tier. Some structures wouldn't need this bus at all, like the EBF. I would happily support this though.

This is an excellent idea.
It should be expensive to upgrade the tier of the multi blocks, and it does really make sense that a multi-block needs a better "processor" every time it is overclocked to a better speed.

It would be perfect if this control circuit could be inserted into a controller slot. 
However a couple of the multi (LCR comes to mind) needs this slot for the programmed circuit. But maybe for these cases the programmed circuit should be moved a the import bus?

Many of the multis also seems to have the space for a second slot in the controller GUI.
And another option is a second slot in the maintenance hatch.

**Comment by Jocroy** [comment]
Please don't make multiblocks require higher tier input busses and hatches. ULV input busses are a very low-tech way to automate the Assembling line and for fluids lower tier hatches are usefull, if you don't like to buffer too much fluid in the hatch, in case you need another fluid in it. Also there are performance concerns with higher tier busses and chest buffers if I remember correctly.

As a more personal note: I think, that the LuV+ tiers are grindy and bland enough and don't need more resource sinks. But I seem to be in the minority here, so please make it reasonable at least. Things like the fusion reactor, that need tons of energy hatches and machine casings, which you want to make more expensive as well, are expensive enough. In my opinion this will just add more unnecessary grind to it.

**Comment by draknyte1** [comment]
I don't see how anyone can argue about the price rise when dynamos and Energy Inouts require a machine casing and a single 1x cable.. 

Requiring specific tiers of multiblock hatches for input/output is a bad move, I agree with @jocroy here. 

From a developers point of view, changing the cost of energy type hatches is the easiest way to limit tier rushing on multis without revising their code. Especially important when the GT++ multis are not going to change their behaviour at all. The only change I'll do is the controller bus that contains the tiered control circuit (new items), even then, Id prefer to fix the very low costs of the hatches.. it's why I suggested it initially..

**Comment by DualBallers** [comment]
@draknyte1, I know this is getting more difficult to implement, but if a new controller bus is added, could you consider also adding some gating mechanism for the cleanroom/low gravity functionality that is currently ignored in the multis?

**Comment by DualBallers** [comment]
Alright fair enough.

**Comment by 0lafe** [comment]
So the control circuit should take an assembler of the tier it's being made for right? Same idea as locking the hatches to tiered assemblers. Also is it possible that if it has the highest one it can use any hatch, just because there's no UEV+ parts yet to make a control circuit 

>I don't see how anyone can argue about the price rise when dynamos and Energy Inouts require a machine casing and a single 1x cable..

We can still totally increase them. What about a machine hull, + 4 2x cables of the tier, + a sensor and an emitter ( to uh, sense the voltage being put in, and emit the same voltage, realism!) 

Dynamos are something you need UEV for in gtnh, so idk exactly how to nerf that while still allowing for those tiers. Maybe like transformers, a machine hull, some cables, and some of those power things. 

The real problem I have with the hatches is that they don't take the same block as the rest of the multiblock. Idk if there's any way to actually fix that considering the only idea I have adds like 30 new blocks per multiblock.
