### ISSUE TITLE
GalaxyCraft Thermal Pads vanish after soulbounding

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3595]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
had my thermal Padding soul bound, it vanished after i died.

**Comment by Dream-Master** [comment]
both mods are open source 😎
