### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3596]
#### Which modpack version are you using 
trying to update to 2.0.5.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I updated to 2.0.4.9
![image](https://user-images.githubusercontent.com/25811344/45294341-4ad40500-b4fb-11e8-9394-ab7542b5d138.png)

downloaded the file linked in anouncement 
![image](https://user-images.githubusercontent.com/25811344/45294360-57f0f400-b4fb-11e8-9445-cbb5ba416dc8.png)
 copyed the files
![image](https://user-images.githubusercontent.com/25811344/45294379-69d29700-b4fb-11e8-94a9-39e9e028af14.png)
Pasted the files 
![image](https://user-images.githubusercontent.com/25811344/45294728-891df400-b4fc-11e8-9c0c-637c91814b05.png)

expected thunks to work

#### What happend instead? (Attach screenshots if needed)
this happened
![image](https://user-images.githubusercontent.com/25811344/45294767-aeaafd80-b4fc-11e8-9f97-62c5a681788e.png)

#

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
not copy the whole folder just mods, scripts and configs and of cource remove old versions.

**Comment by Ghengis88** [comment]
used the electromagnetics tools file but sill get crashes
[crash-2018-09-10_14.07.33-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2366509/crash-2018-09-10_14.07.33-client.txt)

**Comment by Dream-Master** [comment]
i update to 2.0.5.1 and all should be fine
