### ISSUE TITLE
Update from 2.0.4.9 to 2.0.5.0 crash on load

### ISSUE THREAD

**Issue by plaguewolf** [GTNewHorizons/NewHorizons#3597]
#### Which modpack version are you using?
Technic GTNH 2.0.5.0
#
#### If in multiplayer; On which server does this happen? 
n/a SSP
#
#### What did you try to do, and what did you expect to happen?
Launch client from technic launcher, after update from 2.0.4.9 to 2.0.5.0, expected to play SSP
#
#### What happend instead? (Attach screenshots if needed)
Errors
#
#### What do you suggest instead/what changes do you propose?
seems to be API version mismatch with a few mods (enderio, stevesaddons, AE2-rev3)

after update, pulled out custom client mods (FTBUtils, etc) retried, still crashes.
from there, backup and delete entire instance, reinstall fresh, launch, still crashes.

full log available [here](https://pastebin.com/3pH9Mrka)
???

EnderIO: Found the following problem(s) with your installation:
An unknown AE2 API is installed (rv3-beta-7 from appliedenergistics2-rv3-beta-17.jar).
Ender IO was build against API version rv2 and may or may not work with a newer version.
The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.7 from StevesAddons-1.7.10-0.10.16.jar).

/???

**Comment by bartimaeusnek** [comment]
There will be an update in short. Please stay patient.
