### ISSUE TITLE
Neutron Reflector Recipe

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/NewHorizons#3601]
The Neutron Reflector Parts require Thick Reflectors with the NBT value 1, but the Assembler recipe to produce Thick Reflectors makes them without NBT value. Those can't be used to craft further. 

![image](https://user-images.githubusercontent.com/34921674/45320049-d40e2a80-b541-11e8-8930-69083123efbd.png)

![image](https://user-images.githubusercontent.com/34921674/45320082-f4d68000-b541-11e8-8b7e-7ae3db4bfc36.png)

![image](https://user-images.githubusercontent.com/34921674/45320116-0881e680-b542-11e8-9433-9f75f4c9a3f5.png)

**Comment by DualBallers** [comment]
Duplicate #3547 :-)
