### ISSUE TITLE
Iron III Chloride ID changed or something?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#3603]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Was expecting my AE to craft me some HV circuits
#
#### What happend instead? (Attach screenshots if needed)
AE was stuck, went to investigate. All my Iron III Chloride is gone.
Even type filters and liquid conduit filters from EIO dosnt remember Iron III Chloride anymore.

Also the quest Iron (III) Chloride now gives you empty fluid cells...
#
#### What do you suggest instead/what changes do you propose?
figure out why and fix plx :)

**Comment by Dream-Master** [comment]
so far I rember fluids are shuffle around after update. Nothing we can do against it I guess.

**Comment by richardhendricks** [comment]
I think between 4.6 and 5.1 it was added as a GT fluid for cells etc?

**Comment by 0lafe** [comment]
>so far I rember fluids are shuffle around after update. Nothing we can do against it I guess.

Yea, but that shouldn't happen to quests or anything that isn't SFM, or AE

**Comment by richardhendricks** [comment]
Appeared to have lost all my iron(3) chloride stored in BC tanks.

**Comment by bartimaeusnek** [comment]
lost all 256.000L iron(3) chloride stored in my drums 👍

**Comment by Bryfer** [comment]
Has the quest for iron III chloride been fixed yet?
No information in the comments

**Comment by Dream-Master** [comment]
Yes iron3 Chloride was fixed in code.

**Comment by richardhendricks** [comment]
Need to verify Fe3Cl quest works correctly.

**Comment by Relvl** [comment]
same, ironiiichloride universal cell cannot detected

**Comment by Dream-Master** [comment]
works now.

**Comment by Bryfer** [comment]
in #3756 the quest id 1020 is fixed
however I cant find any commits for the coins coins coins quest 1144?
Is 1144 fixed aswell?

**Comment by Dream-Master** [comment]
no. Will fix that asap

**Comment by richardhendricks** [comment]
Looks OK to me? 
![image](https://user-images.githubusercontent.com/1214811/57199725-e2cda580-6f47-11e9-8141-9bc8c9137c4f.png)
