### ISSUE TITLE
Cobalt small turbine

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3605]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
there is no way to craft a cobalt small turbine
#
#### What happend instead? (Attach screenshots if needed)
nothing
#

**Comment by draknyte1** [comment]
Intended. Trash turbines have been removed if below the cut-off.

https://github.com/draknyte1/GTplusplus/issues/344#issuecomment-409801484

**Comment by richardhendricks** [comment]
@Ghengis88 Did you have a usage model for the small cobalt?  What would you use it for?

**Comment by Bryfer** [comment]
the small cobalt was just to complete a quest.

however Normal sized cobalt turbine is great together with a titanium boiler and two staem turbines.. 
This method is also recommended by the quest...
also cobalt isnt really used for anything else, so this makes this turbine even better.
Titanium boiler quest
![image](https://user-images.githubusercontent.com/22825059/45546197-e8da0f00-b81c-11e8-922e-28ac55230e86.png)

Large steam turbine quest
![image](https://user-images.githubusercontent.com/22825059/45546345-4ec69680-b81d-11e8-8a5d-d1060002aad3.png)

**Comment by richardhendricks** [comment]
Recommendation changed to Damascus Steel since cobalt durability is below cutoff. Adjusted larger steam turbine and titanium boiler quests.

**Comment by AndrewAmmerlaan** [comment]
I was using the small cobalt turbines for gregtech's advanced pollution scrubber, today I ran into the problem that I couldn't replace the turbine. The cheapest replacement I could find is manyullyn which isn't exactly as cheap as cobalt. The corresponding quest "cough cough -- something needs to be done about the smell" still suggest the use of small steel turbines, but those aren't craftable either any more. At the least the quest's text should be edited to suggest a different kind of turbine, but I would also like a slightly cheaper turbine for the pollution scrubber.
