### ISSUE TITLE
Check mark quest - Use milk to remove radiation status

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3607]
2.0.5.0

Add a "check mark" quest between 'Tier 5' and 'Hazmat suit', with the free rewards
1x uranium dust
1x bucket of milk

I only recently learned that milk removes the status of radiation - so I have died many many times due to accidental mishandling of radioactive material.
This quest will force the user to get the status, and learn how to remove it.

![image](https://user-images.githubusercontent.com/30087707/45349998-19b70b80-b5b3-11e8-8d57-8232322f4b4a.png)

**Comment by richardhendricks** [comment]
Can we define "severe cases of radiation" better?  It just leaves open questions on what is/isn't fixable with milk/terrawart.  And is there an alternative that does work on severe cases?

**Comment by Jocroy** [comment]
The Talisman of remedium comes to mind. Also, while I think the idea is hilarious, you know, that this quest will potentially kill people, right?

**Comment by Highbeam** [comment]
guess if they keep holding the uranium dust after drinking the milk they will most likely die

**Comment by DualBallers** [comment]
> Also, while I think the idea is hilarious, you know, that this quest will potentially kill people, right?

Sure you can die - if you don't read the quest, and have both low hearts and hunger, for 30 sec of radiation it gives you.

But rather that than having to drown yourself intentionally because you AGAIN picked up a stack of plutonium or depleted quads without full hazmat and got 1 hour of radiation :-/

**Comment by DualBallers** [comment]
While milk certainly is refreshing, I think it's kinda silly that it can cure radiation sickness instantly, so I have added a suggestion for a Decontamination Chamber multiblock in the GT++ github. https://github.com/draknyte1/GTplusplus/issues/377
