### ISSUE TITLE
GT Bees Wish Issue

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3610]
I try now to put bees from gendustry cfg to GT Code.
Sadly the code has limited futures and I need a few more.
Here is a wish list maybe someone can help me adding api functions from forestry and add-on  bees mood to gt that I can use it.

Features I need
- [x] choose if a species allele is dominant or recessive
- [x] Effect that the bee have like poising or other effects (mod support for extra bees and magic bees)
- [x] Biome support for other mods like magic forest from Thaumcraft or tainted lands (can choose only Biome Types, IDs maybe helpful too)
- [x] Individual traits I can choose per bee not a whole species copy(use cultivated trait but add blinding speed and teleport effect to a bee)
- [x] Adding Drops and Propolis to gt
- [x] Support for required block for breeding  not only Oredict or vanilla blocks (maybe other requirement are nice like bee need a lake of x fluid or other nice stuff)
- [x] Better support for centrifuge recipes

**Comment by redmage17** [comment]
Oh god you are going to make bees even worse

**Comment by Dream-Master** [comment]
no not worse only a bit more balance @redmage17

**Comment by redmage17** [comment]
With the current mutation rates and expense of frames they are gated as is. Took me days to get some common bees for honey and sugar

**Comment by Dream-Master** [comment]
The bees not changing much only the comb recipes. @redmage17

**Comment by redmage17** [comment]
The Allele changes is what I am looking at. Though that can be fixed with some kind of filter to brute force breeding.

**Comment by Dream-Master** [comment]
Most bees are the same only in gt code. Some allele are changed but not breaking balance allot

**Comment by boubou19** [comment]
is there a chance that you will add new biome specific emulation upgrades to industrial apiaries? because i think players at end game tier won't like the idea to modify biomes only for 1 or 2 species :/

**Comment by Dream-Master** [comment]
gendustry is open source but who can code in scala ????? @boubou19

**Comment by boubou19** [comment]
then i hope biome change will only be necessary for secondary bees :/
