### ISSUE TITLE
[SPELLING] 2.0.5.1 quests

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#3612]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
PropserCraft

#
#### What did you try to do, and what did you expect to happen?
Spelling mistakes in the quest book.

Quest ID and problem:
1696: capitalise the IV
1703: quest title needs to be Potassium Nitrade, not nitrate.
1691: put a space in the correct space between 'base' and 'materials'
1241: quest title, 'radon', not 'radeon'

**Comment by Dream-Master** [comment]
1703: quest title needs to be Potassium Nitrade, not nitrate.

**Comment by Dream-Master** [comment]
rest was fixed i guess
