### ISSUE TITLE
Cannot Claim Quest Rewards

### ISSUE THREAD

**Issue by srdr2003** [GTNewHorizons/NewHorizons#3618]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
tried to claim the reward 
#
#### What happend instead? (Attach screenshots if needed)
nothing
#
#### What do you suggest instead/what changes do you propose?
idk

**Comment by richardhendricks** [comment]
Which quest?  Are you using a legit copy of Minecraft?  Are you logged into the Mojang authentication servers?

**Comment by srdr2003** [comment]
all the quests , legit copy , auth systems working fine

**Comment by srdr2003** [comment]
all of them i am at steam age now

**Comment by srdr2003** [comment]
![2018-09-18_22 05 37](https://user-images.githubusercontent.com/43237118/45710346-0f86a580-bb8f-11e8-80ef-e10be7689b99.png)
![2018-09-18_22 05 39](https://user-images.githubusercontent.com/43237118/45710355-13b2c300-bb8f-11e8-97fc-2b1216cc55f8.png)
![2018-09-18_22 05 41](https://user-images.githubusercontent.com/43237118/45710365-18777700-bb8f-11e8-9970-a179ea520fad.png)

**Comment by boubou19** [comment]
do you have a team mate who joined your party after you made a couple of quests? or do you joined a party?

**Comment by srdr2003** [comment]
nope im playing on singleplayer

**Comment by srdr2003** [comment]
i switched back to twitch launcher and it works fine now, think its a issue with the technic launcher
