### ISSUE TITLE
Unclaimable rewards and greyed out quests

### ISSUE THREAD

**Issue by AbrasiveElk** [GTNewHorizons/NewHorizons#3619]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Updated from 2.0.4.8 to 2.0.5.1
#
#### What happend instead? (Attach screenshots if needed)
After updating, some of the quests I already finished in previous tiers are now highlighted blue with unclaimed rewards, even after trying to craft the items again, the rewards cannot be claimed and the blue highlight doesn't go away. 
![2018-09-13_14 44 47](https://user-images.githubusercontent.com/43240458/45489460-90473b00-b764-11e8-8e8a-5a98d93d0eac.png)
![2018-09-13_14 44 51](https://user-images.githubusercontent.com/43240458/45489465-93422b80-b764-11e8-9fb1-36c6abe31f9f.png)
Same things happened with the You're gonna hate this #X quests in Tier 3, except I haven't finished those quests yet and rewards are unclaimable.
![2018-09-13_14 45 06](https://user-images.githubusercontent.com/43240458/45489478-9e955700-b764-11e8-9849-cdbe20bd51ec.png)
A bunch of new quests also popped up in tabs I haven't even unlocked yet. They are greyed out but it says they are complete
![2018-09-13_14 45 38](https://user-images.githubusercontent.com/43240458/45489602-f8961c80-b764-11e8-9c66-9f38ad3a2627.png)
![2018-09-13_14 45 22](https://user-images.githubusercontent.com/43240458/45489609-fa5fe000-b764-11e8-807c-a8ad702202a7.png)
![2018-09-13_14 53 12](https://user-images.githubusercontent.com/43240458/45489610-fc29a380-b764-11e8-97db-841e8f5437db.png)
![2018-09-13_14 53 02](https://user-images.githubusercontent.com/43240458/45489614-fd5ad080-b764-11e8-8bd1-c8d3de240fd2.png)
![2018-09-13_14 52 59](https://user-images.githubusercontent.com/43240458/45489616-ff249400-b764-11e8-9f64-a5198895cb31.png)
![2018-09-13_14 52 41](https://user-images.githubusercontent.com/43240458/45489618-00ee5780-b765-11e8-8300-cdec02dd802a.png)

**Comment by richardhendricks** [comment]
Did you use the default load block to reload your quests?

**Comment by AbrasiveElk** [comment]
> Did you use the default load block to reload your quests?
I did, at first the new quests were all labeled "New quest" with no description, after using the block they updated but this happened

**Comment by richardhendricks** [comment]
Have you tried restarting the client?

Just pure single player?  (ie no local server or anything?)

**Comment by AbrasiveElk** [comment]
> Have you tried restarting the client?
> 
yes, at least 3 times
> Just pure single player? (ie no local server or anything?)
>
yes, pure singleplayer

**Comment by sthegreat** [comment]
I've also experienced this bug a few times. A way to "fix" it for now is to turn on /bq_admin EDIT, reset or force completion on all the messed up quests (based on whether or not you already had them), then claim the ones you forced complete and throw away the illegitimately gained quest rewards.
