### ISSUE TITLE
Cleanroom forming incorrect

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3621]
#### Which modpack version are you using?
2.0.4.9
Clean room is formed and works fine with only 50% of filter blocks.
![2018-09-13_19 13 19](https://user-images.githubusercontent.com/35035276/45501353-9865a180-b789-11e8-8e3a-4fadf8bdf585.png)
![2018-09-13_19 13 25](https://user-images.githubusercontent.com/35035276/45501354-9865a180-b789-11e8-9790-0e2567bf2d77.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
@richardhendricks

**Comment by alphaNOVAircraft** [comment]
The issue of the cleanroom to form even with not all Filter casings was there since the beginning. But iirc you still can’t really use it, it forms but does not do it’s job. If you process items that require the cleanroom you still don’t get the items out of it (e.g. some wafers)
