### ISSUE TITLE
Duplicating Item with Workbench Backpack

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3623]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
My private server and Single
#
#### What did you try to do, and what did you expect to happen?
Crafting of GT tool with Workbench BackPack.
#
#### What happend instead? (Attach screenshots if needed)
Item duplicate.
1.![2018-09-14_02 58 07](https://user-images.githubusercontent.com/40425798/45507205-64f83680-b7cc-11e8-95ce-9b6d0e744e34.png)
2(Crafting Hammer)![2018-09-14_02 58 14](https://user-images.githubusercontent.com/40425798/45507220-6c1f4480-b7cc-11e8-961e-e5a98b9cb04b.png)
3(ReOpen Backpack)![2018-09-14_02 58 17](https://user-images.githubusercontent.com/40425798/45507247-7a6d6080-b7cc-11e8-94d3-81cf76359408.png)

#
#### What do you suggest instead/what changes do you propose?
Please fix it.

**Comment by Dream-Master** [comment]
is this backpack still available and have a recipe?

**Comment by Dream-Master** [comment]
from which mod it is? @yukieiji

**Comment by yukieiji** [comment]
Mod is "backpack - 2.2.4 - 1.7.x" and recipe for it exists.
![2018-09-14_06 01 07](https://user-images.githubusercontent.com/40425798/45515620-9f210280-b7e3-11e8-9de5-541fe68639f2.png)
