### ISSUE TITLE
Add forestry tree quests for seedoil

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3626]
butternut and hazelnut
better stats
treealyzer
GT branch cutter

Mention butterfly protection

make sure seedoil quests point to/allow this method effectively

rewards
maybe 1 good stat sapling to help along (nut for nut butter)
proven grafter

ticon scythe or BOP scythe? - add maybe to nether tree quests?

**Comment by mitchej123** [comment]
I had no idea there was a branch cutter... might have sucked less than the grafters!

**Comment by richardhendricks** [comment]
LOL I made like 30 grafters, when they wear out I will definitely try the GT version.

**Comment by richardhendricks** [comment]
forestry spectacles for seeing pollinated leaves
(also works with apiarist hat?)

**Comment by richardhendricks** [comment]
high yield from plum trees

treealyzer

**Comment by richardhendricks** [comment]
https://ftb.gamepedia.com/Category:Tree-Attributes

**Comment by richardhendricks** [comment]
Talk about how girth works, which sapling controls the stats of the tree

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57995066-bce6eb80-7a85-11e9-8cc6-dc2923efc4f1.png)
![image](https://user-images.githubusercontent.com/1214811/57995071-c2443600-7a85-11e9-97c9-3ba7f34b92f8.png)

![image](https://user-images.githubusercontent.com/1214811/57995074-c6705380-7a85-11e9-8743-5e6242d9e3e8.png)
![image](https://user-images.githubusercontent.com/1214811/57995086-ca9c7100-7a85-11e9-989a-893699690f13.png)
![image](https://user-images.githubusercontent.com/1214811/57995091-cec88e80-7a85-11e9-96a7-420b7d516b7a.png)
![image](https://user-images.githubusercontent.com/1214811/57995098-d7b96000-7a85-11e9-8ebe-d969c83cd7db.png)
![image](https://user-images.githubusercontent.com/1214811/57995102-dbe57d80-7a85-11e9-99e1-29e3dc886620.png)
![image](https://user-images.githubusercontent.com/1214811/57995106-e142c800-7a85-11e9-956a-21968d8967c1.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57995108-e7d13f80-7a85-11e9-8d6b-ce102f3c61b0.png)
![image](https://user-images.githubusercontent.com/1214811/57995110-ebfd5d00-7a85-11e9-802f-0b6e6be73b06.png)
![image](https://user-images.githubusercontent.com/1214811/57995112-ef90e400-7a85-11e9-88dd-a828f185cbf9.png)
![image](https://user-images.githubusercontent.com/1214811/57995114-f3bd0180-7a85-11e9-94b6-cd2236eb205d.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57995122-fae40f80-7a85-11e9-8d19-04cc9e606159.png)
![image](https://user-images.githubusercontent.com/1214811/57995125-ffa8c380-7a85-11e9-8a92-26fd746785bf.png)
![image](https://user-images.githubusercontent.com/1214811/57995127-02a3b400-7a86-11e9-975f-abab4326c8a0.png)
![image](https://user-images.githubusercontent.com/1214811/57995133-059ea480-7a86-11e9-94db-dd413b8e155d.png)
![image](https://user-images.githubusercontent.com/1214811/57995134-09cac200-7a86-11e9-944d-d1e49958a1a0.png)
![image](https://user-images.githubusercontent.com/1214811/57995136-0df6df80-7a86-11e9-9ee5-4b75803811eb.png)
![image](https://user-images.githubusercontent.com/1214811/57995139-13542a00-7a86-11e9-9715-0c744ec3a041.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57995158-34b51600-7a86-11e9-91b0-ce19009585e2.png)
