### ISSUE TITLE
Promethium smelting inconsistency

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#3629]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer

![](https://i.imgur.com/NCz7m6r.png)
![](https://i.imgur.com/LDJ0wss.png)
![](https://i.imgur.com/ETCXfyM.png)

#
#### What do you suggest instead/what changes do you propose?
Make recipe properly

**Comment by bartimaeusnek** [comment]
IIRC is Promethium added either by TecTech or GT++ @Technus  @draknyte1
