### ISSUE TITLE
Add some Molecular Transformer Recipes

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#3630]
#### Which modpack version are you using?
2.0.4.6
#

#### What do you suggest instead/what changes do you propose?
Add two Molecular transformer recipes
1.) Lead => Bismuth 10MEU 
(Allows making bismuth before mars, seems to be fair at this cost)
2.) Uranium 235 => Plutonium 239 25MEU
(Faster than running a reactor, but requires energy)

**Comment by alphaNOVAircraft** [comment]
I would not add a recipe for making plutonium that way. 25meu seems a bit easy if you compare it with a nuke or centrifuging uranium dust.

**Comment by alphaNOVAircraft** [comment]
No. Imo it’s in a good spot now. The bismuth recipe seems fair to me.

**Comment by Dream-Master** [comment]
ok

**Comment by richardhendricks** [comment]
What's the need for Bismuth before Mars?  Small Bismuth ores are available in the Nether.
