### ISSUE TITLE
GT++ Control circuit accepts only 1 type of LuV circuit

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3632]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Wanted to craft GT++ control circuit. Couldn't because it didn't accept my Master quantumcomputer.
#
#### What happend instead? (Attach screenshots if needed)
Recipe didn't start.
![](https://puu.sh/BvuVU/060bd00c5e.png)
Recipe in question:
![](https://puu.sh/BvuRD/3a9a393134.png)
#
#### What do you suggest instead/what changes do you propose?
Fix the recipe to accept any type of LuV circuit.

**Comment by bartimaeusnek** [comment]
please report this to the GT++ Github

**Comment by draknyte1** [comment]
isn't the one required more expensive? -.^

**Comment by Lainiel** [comment]
No it requires Nanoprocessor mainframe, which is one tier below master quantumcomputer.

**Comment by 0lafe** [comment]
>isn't the one required more expensive? -.^

yea that's the problem, it's the dumb low tier version of it. If you want it to work better I think you use the oredictionary thing but for circuits for that tier, circuitMaster for this it looks like
