### ISSUE TITLE
Project Red Project Bench and Auto Crafting bench handle oredict wrong in crafting

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3633]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
autocraft some beef wellington in the project red auto crafting bench, or manual craft in the project bench. I expected it to only craft with the right ingredients.
#
#### What happend instead? (Attach screenshots if needed)
The benches will use any items that share an oredict with the item needed. For example the recipe for beef wellington needs the exact item spinach, and any mushroom (listAllMushroom). I encoded the pattern with the white mushroom. Because the white mushroom, spinach, and other items like carrots all share listAllVeggie, the benches will use any of them to craft the recipe which is not intended.
#
#### What do you suggest instead/what changes do you propose?
Fix if possible, or disable the items

**Comment by bartimaeusnek** [comment]
Project Red is closed and the autor doesnt seem to like PRs. guess we need to disable it.

**Comment by draknyte1** [comment]
>Project Red is closed and the autor doesnt seem to like PRs

Author has abandoned 1.7.10 and the entire mod is written in Scala, so nobody would be doing PRs anyway.

**Comment by draknyte1** [comment]
Nobody wants to know Scala, lol.
