### ISSUE TITLE
Empty TiCon crafting table gives GT coin mold

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3634]
Just started when the server restarted today. 

![2018-09-15_21 43 32](https://user-images.githubusercontent.com/1214811/45592376-6773a100-b930-11e8-8362-b0dc42a924c4.png)

**Comment by DoomSquirter** [comment]
sorry, I just have to say this... <insert nelson HA HA!>  
lol

**Comment by bartimaeusnek** [comment]
Wtf, i just moved the script from Client only -> Server script... *mumbles*

**Comment by Dream-Master** [comment]
i guess it is fixed. The script was broken so gt items not nerfed.
