### ISSUE TITLE
Circuit LV and HV

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3635]
#### Which modpack version are you using?
2.0.4.9
#
Assembler does not accept the GT of the LV and HV chips, only IC2 chips.
Variant of autocraft using microprocessor (GT) is not performed
![image](https://user-images.githubusercontent.com/35035276/45592909-b21e0900-b982-11e8-8557-e29f17b7dfe8.png)
![image](https://user-images.githubusercontent.com/35035276/45592907-a6324700-b982-11e8-8053-b594c82e279d.png)
If you replace the circuit (IC2), then all components are successfully placed in assembler.
![image](https://user-images.githubusercontent.com/35035276/45592912-bf3af800-b982-11e8-9ac3-b49dbe273b4a.png)
![image](https://user-images.githubusercontent.com/35035276/45592916-ca8e2380-b982-11e8-9f9d-448ec1948f17.png)
With xv chips a similar problem.

**Comment by CalterOK** [comment]
> #### Which modpack version are you using?
> 2.0.4.9
> 
> Assembler does not accept the GT of the LV and HV chips, only IC2 chips.
> Variant of autocraft using microprocessor (GT) is not performed
> ![image](https://user-images.githubusercontent.com/35035276/45592909-b21e0900-b982-11e8-8557-e29f17b7dfe8.png)
> ![image](https://user-images.githubusercontent.com/35035276/45592907-a6324700-b982-11e8-8053-b594c82e279d.png)
> If you replace the circuit (IC2), then all components are successfully placed in assembler.
> ![image](https://user-images.githubusercontent.com/35035276/45592912-bf3af800-b982-11e8-9ac3-b49dbe273b4a.png)
> ![image](https://user-images.githubusercontent.com/35035276/45592916-ca8e2380-b982-11e8-9f9d-448ec1948f17.png)

**Comment by CalterOK** [comment]
> #### Which modpack version are you using?
> 2.0.4.9
> 
> Assembler does not accept the GT of the LV and HV chips, only IC2 chips.
> Variant of autocraft using microprocessor (GT) is not performed
> ![image](https://user-images.githubusercontent.com/35035276/45592909-b21e0900-b982-11e8-8557-e29f17b7dfe8.png)
> ![image](https://user-images.githubusercontent.com/35035276/45592907-a6324700-b982-11e8-8053-b594c82e279d.png)
> If you replace the circuit (IC2), then all components are successfully placed in assembler.
> ![image](https://user-images.githubusercontent.com/35035276/45592912-bf3af800-b982-11e8-9ac3-b49dbe273b4a.png)
> ![image](https://user-images.githubusercontent.com/35035276/45592916-ca8e2380-b982-11e8-9f9d-448ec1948f17.png)

**Comment by Dream-Master** [comment]
@Spartak1997 link ?

**Comment by CalterOK** [comment]
@Dream-Master https://github.com/Spartak1997/GregTech5.09UnofficialBuild/pull/9/commits/ad3f302ed923c87883000588033bea0424f7f722
