### ISSUE TITLE
Redstone alloy cable

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3636]
#### Which modpack version are you using?
2.5.0.1
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
connect a 1x Redstone Alloy Cable to  1x Tin cable
#
#### What happend instead? (Attach screenshots if needed)
nothing, they wont connect
#

**Comment by mitchej123** [comment]
GT++ wires are of class `GregtechMetaPipeEntity_Cable`
GT wires are of class `GT_MetaPipeEntity_Cable`

This causes this check to fail:
```java
            IMetaTileEntity tPipe = tTileEntity instanceof IGregTechTileEntity ? ((IGregTechTileEntity) tTileEntity).getMetaTileEntity() : null;
            if (getClass().isInstance(tPipe)) 
```
Need to find a way to relax this a bit, while still only allowing cables <> cables and pipes <> pipes
