### ISSUE TITLE
Greggify stairs recipe

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#3637]
The existing stairs recipe is vanilla, and doesn't seem very Greg.

Instead, I suggest:
Assembling machine: 4 slabs and a full block gets you 4 stairs of that block

Crafting table: Current recipe plus a saw and file, returning only one stair block.

**Comment by EmeraldsEmerald** [comment]
Not greg enough. Include some Sticky Resin to glue together the planks.
Make it out of Wood Plates as well. 3 wood planks, 3 wood plates.

**Comment by bartimaeusnek** [comment]
> Not greg enough. Include some Nrutonium to keep the the bedrockium planks together.
> Make it out of Iridium Plates as well. 3 Iridium planks, 3 bedrockium plates.
>

**Comment by richardhendricks** [comment]
Needs more steps.

(HAHAHA)

**Comment by NeroOneTrueKing** [comment]
How about these recipes?

Crafting Table:
```
blank       | file       | slab
screwdriver | slab       | wood screw
slab        | wood screw | block

-> 2 stair
```

Assembler:
```
3 slabs + block + programmable circuit

-> 4 stairs
```

**Comment by boubou19** [comment]
dude seriously with this kind of recipes for decorative blocks, you'll just discourage people to build gorgeous bases.

**Comment by draknyte1** [comment]
Everyone gets dirt houses until HV. 😎

**Comment by draknyte1** [comment]
> you're probably not thinking big enough. :D

Or they've played before ;)

**Comment by boubou19** [comment]
> you're probably not thinking big enough. :D

Or you plan make extensions for your base :D

**Comment by richardhendricks** [comment]
Even playing before I want to rip out everything and redesign the base.  Or move to a more scenic spot.

Back on topic,
How about a recipe for metal stairs that doesn't use goddamn blocks? 
6 blocks of lead for 4 steps making me cry.

**Comment by Dream-Master** [comment]
Wood screw is bad for stairs better iron or assembler recipe as alternative.

**Comment by boubou19** [comment]
for metal stairs we could imagine a better recipe with an extruder shape

**Comment by LogicFalls** [comment]
@boubou19 The assembler recipe provides more stairs per block than vanilla. If you have a problem with painfully crafted stairs, "Wooden doors".
@NeroOneTrueKing I don't like the idea of screws, because this recipe is going to be generalized to all possible stair blocks, not all of which have screws. Since slabs just require tools, I think stairs should be the same as you are fundamentally ripping a chunk out of a block (Or in the case of the assembler, gluing them together).

**Comment by boubou19** [comment]
I don't mind assembler recipes, my point of view is from what i have seen in ~2 and half
years playing on delta, many players use a lot of stairs early game to make a cumfortable base, and some keep their pattern along their progression. Increasing stair recipes' difficulty will discourage them to make a beautiful base. But in an other hand, I know that some players will don't bother if the stairs recipes change because they place beauty before complex contraptions. I just want to avoid those players feeling aggrieved that's it.

**Comment by richardhendricks** [comment]
How would this affect cobble/stone stairs?

**Comment by bartimaeusnek** [comment]
> fireSTONE screws.

i'd say cast stone stairs from concrete in fluid solifier, hammer them for cobblestone screws

**Comment by richardhendricks** [comment]
If we had firestone slabs/blocks/stairs that set anything that went over them on fire...That would be epic.
