### ISSUE TITLE
the problem with recipes in a large chemical reactor for the production of polytetrafluorotylene

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/NewHorizons#3639]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
made a scheme for creating polytetrafluorotylene in a large chemical reactor, I'm wanted most of the recipes to be performed in the multiblock. I picked up the most simple and logical recipes, but I came across a conflict of two recipes.
![screenshot_17](https://user-images.githubusercontent.com/39298269/45599170-aa487e00-b9ef-11e8-98c3-b05f835b089a.png)
 When creating hydrofluoric acid, the configuration circuit 1 is required. In the chain of recipes i posted , u can notice the presence of chlorine in the imput bass. As a result, instead of hydrofluoric acid, hydrochloric acid is obtained because they have almost identical recipes.
![screenshot_16](https://user-images.githubusercontent.com/39298269/45599172-b92f3080-b9ef-11e8-8763-08d8fc532b9a.png)
![screenshot_15](https://user-images.githubusercontent.com/39298269/45599176-bc2a2100-b9ef-11e8-884d-3736fcd21a46.png)
 The chips in the recipes are the same, the difference is only in chlorine and fluorine.
This conflict of circuits prevents rather conveniently to organize the production of polytetrafluorotylene in a large chemical reactor.
A multi-block is created to execute several recipes at once, and this problem kills the meaning.
#
#### What do you suggest instead/what changes do you propose?
I hope that this is possible to change the configuration from one of the recipes to another .. For example, at 17, or another, which has no application. 
I understand that this is a minor problem, but I do not think it will take long time

**Comment by Vernam** [comment]
checked, 17 chip is used only in one recipe in single-unit mechanism. Adding it instead of the first in the recipe, which I indicated - nothing bad will happen

**Comment by septemberWaves** [comment]
Try using more than one chemical reactor. The fact that HF and HCl have similar recipes is because they are similar (but not identical) chemicals; it's not a bug. Trying to produce something as complex as PTFE with only a single large chemical reactor is frankly ridiculous. The multiblocks aren't meant to process every possible recipe you could need with just one machine - ore-processing multiblocks sometimes have that kind of versatility, but not the more specialized ones like the large reactor.
