### ISSUE TITLE
Back Pack Mod

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#364]
Did we need this mod ?

https://github.com/Vexatos/ForecastersBackpacks/blob/master/README.md

**Comment by Namikon** [comment]
I don't think so. We don't even have half of those mods

**Comment by Dream-Master** [comment]
That's why i asking ;-)

**Comment by Drobac** [comment]
Not needed, we already have adequate backpacks in the pack
