### ISSUE TITLE
Red Alloy cables do not connect to different types of cable.

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#3640]
#### Which modpack version are you using?
V 2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Placing a Tin cable, and redstone alloy cable of the same thickness adjacent and linking them with the cutters as had worked perfectly before the update.
#
#### What happend instead? (Attach screenshots if needed)
Wires refuse to connect after linking
#
#### What do you suggest instead/what changes do you propose?
This was likely a result of the recent changes to cables not being applied to GT++'s cables.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3636
