### ISSUE TITLE
Destroyed rocket

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3642]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
leave OW with my Tier 3 rocket
#
#### What happend instead? (Attach screenshots if needed)
while standing in the rocket and waiting for fuel to fill i got warpligthing effect and the ligthening destroyed my Rocket
#
#### What do you suggest instead/what changes do you propose?
refund my rocket and remove the effect of reckets blowing up from lightning

**Comment by bartimaeusnek** [comment]
DO NOT use rockets on the official servers. They kill the tps due to a strange bug.

**Comment by Ghengis88** [comment]
How am i suposed to reach the planets if not by rocket?

**Comment by Bryfer** [comment]
Only Delta has Stargates
When epsilon was launched rockets was not completely broken any more, so there was no need to use Stargates

So People om epsilon needs to use rockets. Only a few plants seem to affect TPS

**Comment by richardhendricks** [comment]
Why are you building structures while suffering from warp lighting?  Go get that shit removed first!

**Comment by bartimaeusnek** [comment]
> Only a few plants seem to affect TPS

Wrong. Even starting a rocket and going back to OW causes TPS to go lim(0).

**Comment by 0lafe** [comment]
Is this just an official problem, just a plug-in problem, or is this gonna dick my forge only server down when I come back with a rocket.

**Comment by draknyte1** [comment]
100% doesn't effect Forge, besides GC/GS being horribly coded mods in general.
I've personally flown like 20-30 times on my Forge SMP server with 0 issue.

**Comment by bartimaeusnek** [comment]
@0lafe @draknyte1 its a thermos issure, something with mobs beeing loaded in ALL Galacticraft dims

**Comment by 0lafe** [comment]
Because they're made for vanilla servers that almost require tons of dimensions that are all identical in plugins/mods?

**Comment by Highbeam** [comment]
Can killall commands be done for specific dimensions?  Would that fix it or does the problematic dim have to be visited?

**Comment by Namikon** [comment]
No, it does not solve the issue. Entities are not purged while doing a killall in those dimensions; They seem to be in some sort of hibernating state until someone enters the dim. It doesn't even matter where you teleport to. Just to be in the dimension calms the Server (At least in about 95% of all cases we had this problem)
