### ISSUE TITLE
Chunkloader Coin Tier 4 and 5

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/NewHorizons#3643]
#### Which modpack version are you using?
2.0.4.9
The recipe requires 24 and 48 buckets, but you can pour 16.
![2018-09-17_06 53 19](https://user-images.githubusercontent.com/35035276/45605604-cdeae300-ba46-11e8-95ef-998aa5b47587.png)
![2018-09-17_06 53 28](https://user-images.githubusercontent.com/35035276/45605605-cdeae300-ba46-11e8-994a-ddc7052092fc.png)

**Comment by 0lafe** [comment]
Wasn't there something with higher tier machines holding more? Anyway there's always PA's that use fluid hatches. Pretty sure IV coin is IV (lol) so it's not really the worst thing. 



Are the coins craftable on servers yet/is there a way to make them able to be?

**Comment by richardhendricks** [comment]
Yeah high tank sizes for higher tiers is something we've thought about changing.

**Comment by richardhendricks** [comment]
Just needs to change 16000 for the higher tier assemblers. 

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java#L600

**Comment by Dream-Master** [comment]
will change
