### ISSUE TITLE
zhuhai fishing port 

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3644]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon and SP
#
#### What did you try to do, and what did you expect to happen?
build the zhuhai fishing port
#
#### What happend instead? (Attach screenshots if needed)
incomplete structrure howver i do it
#
#### What do you suggest instead/what changes do you propose?
was this changed? had 1 working in sp before...

**Comment by alphaNOVAircraft** [comment]
Report this issue on the gt++ github pls
