### ISSUE TITLE
Mac OS X New installation crash

### ISSUE THREAD

**Issue by arisau** [GTNewHorizons/NewHorizons#3646]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
Expected modpack to load
#
#### What happend instead? (Attach screenshots if needed)
Modpack crashed (crashlog: https://privatebin.net/?4ad92bdbd92ccf3d#vKs0bBhl2Sdm2iaWcVsjvue/moohPihirZf4od52meY=)
#
#### What do you suggest instead/what changes do you propose?
Modpack is not loading on fully updated Mac OS X 10.13.6 after couple of reinstalls. Other modpacks work fine (for example  Sevtech Ages). During crash whole OS is freezed for a couple of seoconds

**Comment by draknyte1** [comment]
I'd suggest reinstalling latest version of Oracles Java 8 JRE.

**Comment by arisau** [comment]
Already running JDK 1.8 update 181.

**Comment by bartimaeusnek** [comment]
looks like a corrupted download to me, try reinstalling

**Comment by arisau** [comment]
Reinstalled with technic launcher - same error. I was logged out out of my OS account after game loading was complete.

**Comment by draknyte1** [comment]
> Already running JDK 1.8 update 181

And? I've asked you to reinstall Java.. your current installation may be corrupt.

**Comment by TechnicLab** [comment]
Oh, sorry. I meant that I already reinstalled JDK after discovering this weird crash.

**Comment by arisau** [comment]
With reinstalled JDK I was able to reproduce same crash on Divine Journey. Other modpacks are still working fine(1.7.10 and 1.12).

**Comment by arisau** [comment]
Issue fixed by disabling splash screen in splash.properties
