### ISSUE TITLE
Titanium ore nerf

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3647]
#### Which modpack version are you using?
2.0.5.1

#### What do you suggest instead/what changes do you propose?

Right now titanium ore is found on the moon, as well as bauxite. There's really no question that titanium ore is better for titanium, but it's a little too easy. Compared to all the tiers before it, steel you need to slave over a bbf, aluminum you need to find gravel/electrolyze tons of stuff, stainless you need to get manganese and chrome which means lots of electrolyzing. Titanium however is just found as an ore when you reach the tier that needs it. I like titanium ore, but I think it should be pushed back a bit, to maybe the T5 rocket. There's never really a time that you have issues with the amount of titanium you have. At least not the dust. 

The IV-UHV tiers are all generally the same as the lower tiers, requiring you to make semi complex materials, apart from neutronium which is a whole separate issue.

**Comment by draknyte1** [comment]
Was Ti Ore removed and re-added already in the past?
Forcing rutile is poor form, especially when people already go that route pre-moon to get Ti..

**Comment by 0lafe** [comment]
>Forcing rutile is poor form, especially when people already go that route pre-moon to get Ti..

You mean for the tiny bit you can get from aluminum gravel ore? That's more something that you can go out of your way to do, rather than anything else. The ore is first on the moon. 

>Wasn't Ti Ore removed and re-added already in the past?

it was gone for like a version or two, but that could have just been a bug or something

**Comment by draknyte1** [comment]
> You mean for the tiny bit you can get from aluminum gravel ore? That's more something that you can go out of your way to do, rather than anything else. The ore is first on the moon.

No, lol.
You can duplicate it once you've done the research in Thaumcraft, or invest it into an EV centrifuge for processing the Metal Mixture dust you get out of stone dust, which provides two different sources of Ti via Rutile processing. If you're determined, this is far easier than making a rocket, provided you think about the problem prior to late HV..

> it was gone for like a version or two, but that could have just been a bug or something

I feel like it was on purpose, but my memory isn't amazing.

**Comment by 0lafe** [comment]
>You can duplicate it once you've done the research in Thaumcraft, or invest it into an EV centrifuge for processing the Metal Mixture dust you get out of stone dust, which provides two different sources of Ti via Rutile processing. If you're determined, this is far easier than making a rocket,

The thaum thing is there because no one seemed to have looked over witching gadgets before adding it, unless you meant with something else, then I take that back. 

Still though, tungstate comes from a ton of stuff, you can process it at EV, but it's still how you get tungsten pre t6 rocket. I don't get how there being miniscule amounts of it pre moon makes the recipe un usuable for post moon. The moon will still give you tons of bauxite compared to anything else, so it's not like you're not benefiting in titanium once you get there.

**Comment by bartimaeusnek** [comment]
>The thaum thing is there because no one seemed to have looked over witching gadgets before adding it,

eh i did and its meant to be like that...

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/dd31ac9607951b185ac52aee74b9cf693961f364

Titanium Ore on the moon was changed to Ilmenite in the titanium/chrome vein
1 layer of Bauxite ore was changed to Ilmenite in the bauxite vein

Pure titanium ore is still present in neutronium veins at T6 planets.

Deep Dark giant vein ore.mix.chrometitangiant was changed, but needs to be changed back @Dream-Master

**Comment by richardhendricks** [comment]
Deep Dark giant vein ore.mix.chrometitangiant was changed, but needs to be changed back @Dream-Master

**Comment by Dream-Master** [comment]
is this deep dark only @richardhendricks if yes i will change back

**Comment by richardhendricks** [comment]
Yes the giant vein is DD only.

**Comment by combusterf** [comment]
Rutile processing is rather chlorine and magnesium heavy, so I would like to see some questbook updates about that - such as salt water pumping on the moon - to guide the player through some quality-of-life options to get there.

**Comment by botn365** [comment]
The salt water one shoud be in paralel with the helium-3 quest. 
Wont the chlorebenzene be removed from mars when the pumping fluids are rebalanced.

**Comment by richardhendricks** [comment]
The quests will be adjusted once the PR is accepted.

**Comment by richardhendricks** [comment]
Need to have fluid quests show up on Space Race tab as well, so players focusing on it will see the quest has opened up. Update wording so it mentions fluid pump in multiblock goals.

**Comment by richardhendricks** [comment]
FLuid quests are now on the multiblock page and the space race page.
![image](https://user-images.githubusercontent.com/1214811/57419944-7ca48500-71ca-11e9-83c0-8c90c79cf367.png)
