### ISSUE TITLE
Jellyfish bones?

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#3649]
Modpack version: 2.0.5.1

When pulverizing fish to mince meat, there's always a chance to produce a tiny pile of bone meal. However, this is still the case with _jellyfish_, and I'm fairly sure those don't have bones. Just for the sake of making the recipe seem more sensible, I'd suggest removing the bone meal chance from the jellyfish pulverization recipe.

**Comment by bartimaeusnek** [comment]
@septemberWaves as far as i know are jellyfish registed as "fish" and all fish recipes have this kind of recipe...

**Comment by septemberWaves** [comment]
Actually I'm fairly sure it only has the oredictionary tag for "foodJellyfish" (I can't check to confirm this _immediately_ since the game is slow to load, but I think that's the correct spelling). Other Harvestcraft fish seem to have the general tag for fish as well as for their specific fish species.
