### ISSUE TITLE
Tinkers Tools

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#365]
Tinkers Tools need to be rebalanced.
After we change the Tiering the Tools are to overpowerd.
Suggestions here or in the forum.

If i hear nothing from you i will revert the changes.

**Comment by Drobac** [comment]
What change of tiering? the modifiers?

**Comment by Dream-Master** [comment]
There is a Page in the Goold XLS Sheet . Tinkers Gregworks properties.

**Comment by arnabbiswasalsodeep** [comment]
For tiering them, we should report the default values of the tool parts and then decide the multiplier

Same process can be done for #350

**Comment by Namikon** [comment]
This issue is not about the tool parts; It's about the change that tools will level up to 99 instead of 15, and have a lot more modifiers than before. (2, 4, 6, 8, 10 before, now every 2nd level)

**Comment by Namikon** [comment]
Already approved and loved by @ProsperCraft. Shouldn't be changed and isn't too overpowered

**Comment by Dream-Master** [comment]
ok the i close it.
