### ISSUE TITLE
[2.0.5.1] How to disable biomes?

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#3650]
What is the proper way to disable certain biomes? Like "rwg_snowForest".

It seems to have config/climatecontrol.cfg inside of it, but I do not see any ClimateControl-xxx.jar files. Is this mod even installed?

**Comment by EvgenijM86** [comment]
There is also config/RTG directory, but the RTG mod is not found in mods directory. Is this mod also missing?

**Comment by Dream-Master** [comment]
original pack use rwg mod
