### ISSUE TITLE
LuV -> UV Circuit

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3651]
#### Which modpack version are you using?
2.0.5.1
![2018-09-20_01 11 45](https://user-images.githubusercontent.com/33183715/45786759-45e92100-bc72-11e8-9d26-993ba9dcafe0.png)

This recipe uses a Wetware Processor (LuV) and gives out a UV processor. This should be a bioprocessor instead.

**Comment by 0lafe** [comment]
The bio circuits are made from wetwares?...
