### ISSUE TITLE
[RFC] Draconic core quest change 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3654]
#### Which modpack version are you using
2.0.5.1
#
#### What do you suggest instead/what changes do you propose?

Draconic cores are weirdly priced right now, at 4 neutronium and 4 thauminite. So the neutronium makes sense, but the other ingot is a little weirdly tiered. I suggest changing it to 4 Nt, 2 ichorium  and an SoC chip per core. So 64 neutronium, 32 ichorium and 16 SoC chips, for the quest to make 16. Gated to ZPMish post mk1 fusion which is fair for DE I'd think. I kind of don't like neutronium being in the quest, but I'm not sure of a better item :(

**Comment by ScriptedPiky** [comment]
While I do agree that the quest is really oddly priced and could use a touchup and SoC chips would be fun, Ichorium is not the way to handle this quest. Sure Ichorium is easy enough to get once you're up there (post mk3 fusion), but it's frustrating as you need to kill enderman and pigman for their respective shards. At that point, doing the DE quest and DE, in general, doesn't become fun or difficult, but really obnoxious of having to do 64 infusion recipes for 16 cores that'll get used up easily in recipes (i.e wyvern and awakened cores and so on). Again, you most likely have world accelerators speeding up the infusion with huge amounts of materials to provide the infusion, but there are some that really don't like using world accelerators for infusion or might really dislike the thought of large infusion in general (looking at you Blood Magic).

Instead, we could use other metals, possibly qauntium, adamantium, draconium, quantum stars (1250 radon each) or just netherstars. Some thought of using other often unused materials for the core parts would be fun.

**Comment by 0lafe** [comment]
>Again, you most likely have world accelerators speeding up the infusion with huge amounts of materials to provide the infusion, but there are some that really don't like using world accelerators for infusion or might really dislike the thought of large infusion in general (looking at you Blood Magic).

That's part of the endgame though. DE is like endgame magic stuff and ichorium is about as far as magic goes. AE automation and speeding up the infusion is doable making it take longer to make the neutronium than the ichorium, but you have to have solid magic infrastructure for that tier. That's fine if you don't want to do big infusions or accelerators, but like that is an integral part of the endgame of magic so why not require it. 

>qauntium

>adamantium

Quantium is like a T4 rocket material and mostly useless, adamantium is the same except T6 or so. They aren't costly or endgame resources. 

>quantum stars (1250 radon each) or just netherstars

What about instead of neutronium use fluxed electrum, and gravi stars? So 4 fluxed electrum ingots, 2 ichorium and 1 gravi star per. 

>draconium

LuV ebf recipe that goes pretty quick, and the dust is practically free, so I disagree 

Maybe cosmic neutronium? Worth more than it's weight in neutronium I think. Could replace ichorium I guessssssssssss

**Comment by ScriptedPiky** [comment]
> That's part of the endgame though. DE is like endgame magic stuff and ichorium is about as far as magic goes. AE automation and speeding up the infusion is doable making it take longer to make the neutronium than the ichorium, but you have to have solid magic infrastructure for that tier. That's fine if you don't want to do big infusions or accelerators, but like that is an integral part of the endgame of magic so why not require it.
I get that it's an endgame magic material and powerful enough to contain DE cores (compared to the simple thauminite that somehow manages a core), but it's frustrating and not fun to make 32 ichorium for just 16 draconic cores that you'll need even more plentiful amounts of. Ichorium is nice, don't get me wrong and can be useful for certain stuff.

>What about instead of neutronium use fluxed electrum, and gravi stars? So 4 fluxed electrum ingots, 2 ichorium and 1 gravi star per.
>Maybe cosmic neutronium? Worth more than it's weight in neutronium I think. Could replace ichorium I guessssssssssss
I'm all in for gravi starts and fluxed electrum actually. Just not the ichorium (can be changed to cosmic neutronium as you said). Cosmic neutronium could fit the replacement of ichorium.

>LuV ebf recipe that goes pretty quick, and the dust is practically free, so I disagree
But isn't draconium a main component of DE? Hence the names of most draconic stuff. I guess it could be a side component and not replacing one of the main components (in this case, fluxed electrum, gravi stars, and cosmic neutronium are the main components), but draconium acts as the metal made to fit the draconic core. Although the current recipe doesn't have any draconium in it.

So if we're doing this change, the cost in total for all ingots required would be:
4 Fluxed Electrum, 2 or 4 Cosmic Neutronium, 1 Gravi Star (4 Neutronium) per core

**Comment by jiamingc0824** [comment]
>2 or 4 Cosmic Neutronium

anything other than this please. :) Getting large amount of this is quite the pain in the butt. I rather use ichorium over this.

**Comment by 0lafe** [comment]
>anything other than this please. :) Getting large amount of this is quite the pain in the butt. I rather use ichorium over this.

1.5A UV can get you an ingot every like 40s which is like >2x faster than smelting neutronium right now. That said, I'm totally in favor of not using that and keeping it as an infinity material. Ichorium all the way lol 

>So if we're doing this change, the cost in total for all ingots required would be:
4 Fluxed Electrum, 2 or 4 Cosmic Neutronium, 1 Gravi Star (4 Neutronium) per core

I'm liking that, except the cosmic neutronium I guess. What about awakened draconium? Uses draconium, sorta, and is fairly gated (T8?) while still being behind infinity stuff. Honestly finding lategame materials is such a pain. There's like billions in the early/midgame, and lategame has like 8 for all the tiers. Neutronium, naq alloy, fluxed electrum, awakened draconium, infinity stuff, duranium/Tritanium/americium. Probably some others that I'm just blanking on right now, but it's sort of an issue for making stuff :(

**Comment by noobyaran9** [comment]
After gaving it some thought on this idea, I dont really see why this change needs to happen.

1) Yes, I understand that neutronium smelting is kinda slow but its really fine. You dont really need that much of the cores anyway. Unless, u plan to make like 10 of the draconic suit set.

2) Thauminite is kinda ok in this situation because the blue core is kinda useless is most DE recipe. You would need quite abit of them in order to make something useful. Changing the other recipe rather than this quest would make more sense. Check out #3083 for some of the recipe I proposed.

3) Dont really think you need to gate the blue cores to ZPM+ as its fairly useless in its own uses other than making a spawner as the quest line is fairly end game (U need UV parts in the quest process)

**Comment by richardhendricks** [comment]
@Dream-Master What is the final quest changes for this?

**Comment by Dream-Master** [comment]
not sure yet but thauminite need to be replaced with a other material. Void or ichorium or anything else. @richardhendricks

**Comment by 0lafe** [comment]
Void isn't much better, still just a single cauldron recipe like thauminite. I'm in favor of pretty much anything that takes a thaum infusion

**Comment by Dream-Master** [comment]
in my eyes ichorium is the best choice. Only the amount need to be balanced.

**Comment by richardhendricks** [comment]
I did 1 ichorium and 1 ASoC chip per. I did ASoC since SoC seems really low?  I have no clue, let me know if this is OK @0lafe @Dream-Master 
![image](https://user-images.githubusercontent.com/1214811/57414100-73142080-71bc-11e9-8ad2-e29b07d1c40b.png)

**Comment by 0lafe** [comment]
Seems fine, we'll see if it needs more/less as people start making them probably

**Comment by BlackFlameTNT** [comment]
i would like to say if you are talking about magic why not using soul life shard after all Legendary Quests ask you to make them and i would like to see more use to them how about.
64x Neutronium + 32x Life Shard +32x Soul Shard +64x Dracouium Ingot = 16 Core.
for me i would like not to go to infusion.

**Comment by 0lafe** [comment]
Kinda the point is to enforce some lategame magic thing, but the demons can just be farmed for shards right? Ichorium takes 2 mob farms with some other stuff, but the difficulty really comes from automation and speed of the infusion

**Comment by BlackFlameTNT** [comment]
i think you mean Ender IO mob farm i think it wont work it wont give you shard.
they most be killed near the city. 
and they must spawn naturally.

**Comment by ScriptedPiky** [comment]
Yes, they have to be spawned naturally from the demon portal, and it eventually gets to a limit. So using Life and Soul Shards are not a good way to balance it since they are not renewable and tedious to obtain

**Comment by Houstonruss** [comment]
Maybe just requiring raw ichor makes more sense, than using the ingot, which is established as a thaum item. It also lowers the tedium of creating a whole ingot of ichorium. Unless there is a way to realistically automate ich ingots, or infusion crafting as a whole, it seems "too expensive" in just time.

**Comment by BlackFlameTNT** [comment]
if you going to keep it as ichor ingot can we at lest have small ichorum ore in the Deep Dark

**Comment by 0lafe** [comment]
You can automate infusions and WA them past speeds needed. Essentia gen is probably your limit really, with these taking like 500+ for some iirc. If ichorium has an ore it defeats the purpose of using it, and some other infusion only item should take it's place imo

**Comment by ScriptedPiky** [comment]
I did the math for that multiblock. It's 400 primordial pearls for the large essentia generator. 800 ichorium required or 1600 ichor. So uhhh, have fun doing that!

**Comment by BlackFlameTNT** [comment]
how about you need to use chaotic core to make the deep dark so you will need to kill the DE dragon and then go to the deep dark so you can get small ichorium ore to make it easier later.

**Comment by DietmarKracht** [comment]
Don't you need to kill the pigmen in the nether and the ender men in the end to obtain the shards? I think they don't drop in overworld or voids

**Comment by Houstonruss** [comment]
> s

Yeah, killing tons of entities is a big no-no for me. there's gotta be a better way.

**Comment by 0lafe** [comment]
>Don't you need to kill the pigmen in the nether and the ender men in the end to obtain the shards? I think they don't drop in overworld or voids

Yes, you do

>Yeah, killing tons of entities is a big no-no for me. there's gotta be a better way.

I mean we don't have much mob farm orientation overall. They're easy enough to setup and not kill tps, and slightly different than most things you do

**Comment by AlexBucket** [comment]
The deep dark really doesn’t need ichorium. 

Keep it as ingots in the quest and not the raw. Encourage people to use more of that end game stuff. The draconic pieces themselves are piss easy to craft, and for how strong the armor is, at least a part of it should be mildly difficult

**Comment by Houstonruss** [comment]
Buff ichorium in the LCR then. It's beyond ridiculous.

**Comment by draknyte1** [comment]
> finding lategame materials is such a pain

Except the 20 I add though. 🤔

**Comment by DietmarKracht** [comment]
Quantum was really hard. but then i saw hypogen

**Comment by BlackFlameTNT** [comment]
I would use GT++ material any day if I can avoid 32 thaumic infuser we can have one of this higher advanced alloy that need a mix of all elemental shards.

**Comment by draknyte1** [comment]
There’s also Rhadox? A new high tier plastic. 
Plus several other materials, like advanced Nitinol, or the upgraded Ti/W.

**Comment by 0lafe** [comment]
>Buff ichorium in the LCR then. It's beyond ridiculous.

LCR+crops are used extensively already. There's really nothing that pushes you to make a fast infusion setup, or automate essentia at a similarly fast rate.
