### ISSUE TITLE
Suggestion: add Astral Sorcery, AbyssalCraft and The Betweenlands for 3.0

### ISSUE THREAD

**Issue by ScreechamusPrime** [GTNewHorizons/NewHorizons#3657]
these three mods are nice and would fit well in the pack. Betweenlands is after the Dark Tower in TF, Astral Sorcery should require some rarely used material from T2-T5 planets, and AbyssalCraft should be after the Tier 4 Altar in BM

**Comment by bartimaeusnek** [comment]
1. GTNH3 suggestions go here: https://github.com/GTNewHorizons/GTNewHorizons-3.0/issues
2. Astral Sorcery, AbyssalCraft and The Betweenlands are already in the pre-alpha-testing-pack
