### ISSUE TITLE
chunkloader coins

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3658]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsion
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/25811344/45878509-8dba9600-bda1-11e8-88d4-0bfa80607b46.png)

#
#### What happend instead? (Attach screenshots if needed)
did relogg but still there
#

**Comment by Ghengis88** [comment]
that is the menue for buying chunkloader coins, i only get stones

**Comment by Namikon** [comment]
Tried to update the Jobs plugin; But it seems they do not support Non-Vanilla ItemIDs anymore. We'll see if the restart will solve it. If not, I'll downgrade.

**Comment by Namikon** [comment]
Aaaand; It did not. Guess we have another plugin that cannot be updated. Moved back to the old Version; Coins and jobs are functional again
