### ISSUE TITLE
Suggestion:  A way to make Stagnant Waste Water

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3664]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Get to the Toxic Everglade to get Stagnant Waste Water for use in having a nice decoration toxic waste to fill my laboratories empty channel with.
![walkway](https://user-images.githubusercontent.com/37776581/45931908-dbfaa100-bf29-11e8-8ced-630e45c21d59.png)

#
#### What happend instead? (Attach screenshots if needed)
The Containment Frame to make the portal was uncraftable.
#
#### What do you suggest instead/what changes do you propose?
Add a recipe to make the Stagnant Waste Water for enterprising mad scientists.

**Comment by sthegreat** [comment]
1. The containment frame actually is craftable. It's a nei bug, click "u" on a multi-use casing to see the recipe.

2. I believe the toxic waste water is the same as "sludge" you get from crafting the gt Chum food, though it's not craftable in very large quantites since you need the Purple Drink to make it.

**Comment by Teirdalin** [comment]
Oh weird,  wonder why the NEI didn't show on the frame itself.

Thanks sthegreat. <3

**Comment by Teirdalin** [comment]
Actually, is it possible to make the coin for the portal?  Can't seem to find a recipe for the coin mold.

**Comment by Bluebine** [comment]
eh? yes you can. coinage mold is craftable by pouring steel over a casting form in a smeltery, just like all the other molds

**Comment by Teirdalin** [comment]
Is the recipe for the Coinage mold hidden or something?

**Comment by Bluebine** [comment]
![2018-09-23_15 36 43](https://user-images.githubusercontent.com/29802757/45932174-7ec11880-bf46-11e8-9e1f-0a31125557fb.png)
![2018-09-23_15 36 46](https://user-images.githubusercontent.com/29802757/45932175-7ec11880-bf46-11e8-9e19-2ad63c5a3bd0.png)

**Comment by Bluebine** [comment]
That's on SP in .5.1. It may be disabled on servers, but I don't see why it would be.

**Comment by Teirdalin** [comment]
Will try crafting it using that recipe,  oddly the NEI isn't displaying it for me.

**Comment by Teirdalin** [comment]
Yep.  Nothing.

**Comment by draknyte1** [comment]
The NEI issue has no clear cause, I've spend days debugging it in the past. :(
