### ISSUE TITLE
Make SMD Transistors have a correct Texture

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/NewHorizons#3667]
#### Which modpack version are you using?
2.0.5.1
While i know this is propably low priority, there is one thing bothering me since the introduction of smd-parts:
The Texture for the SMD Transistor, even if it lines up with the other smd components nicely, is wrong, as a transistor should have 3 terminals.
I propose to have it look like a SOT23 package, as seen below, while maintaining the theme and colorscheme so it fits in with the other components.
Example picture:
https://storage.googleapis.com/stateless-www-faranux-com/2017/02/2TY.jpg

**Comment by DualBallers** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/30087707/46570658-cba1e780-c967-11e8-966a-c2f7ab0b1de8.png)

**Comment by Dream-Master** [comment]
yea why not looks good for me
