### ISSUE TITLE
Craft all solar panels with either filled or empty batteries

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3668]
2.0.5.1

Crafting of the solar panels changes from filled batteries to empty batteries between HV and EV type.

Change all solar panel crafting to either using filled or empty batteries. 

Bonus info - all solar panel quests, including EV and IV, says that you need the filled type.

![image](https://user-images.githubusercontent.com/30087707/45968631-d4262400-c031-11e8-9ae7-16edd9f31c15.png) ![image](https://user-images.githubusercontent.com/30087707/45968645-dc7e5f00-c031-11e8-8d16-ec7a7499a22a.png) ![image](https://user-images.githubusercontent.com/30087707/45968658-e30cd680-c031-11e8-9016-fc54d65ef2b8.png) ![image](https://user-images.githubusercontent.com/30087707/45968680-ee600200-c031-11e8-9416-2ab011544bd5.png) ![image](https://user-images.githubusercontent.com/30087707/45968689-f750d380-c031-11e8-901e-f5a09084765a.png) ![image](https://user-images.githubusercontent.com/30087707/45968708-05065900-c032-11e8-8ed4-be09ff4b655b.png) ![image](https://user-images.githubusercontent.com/30087707/45968733-15b6cf00-c032-11e8-8021-6f10ede2d12e.png) ![image](https://user-images.githubusercontent.com/30087707/45968724-0d5e9400-c032-11e8-8163-1b15035e9b27.png)

**Comment by bartimaeusnek** [comment]
should be done with filled ones
