### ISSUE TITLE
suggestion - large fluid cells that are sized in 144ml increments instead of 1000ml

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3669]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
ssp
#
#### What did you try to do, and what did you expect to happen?
doing alot of chemistry by hand with LCR and when dealing with things that end up as molten, which means it stores 144ml per cell, I am forced to do these things in small batches.

#
#### What happend instead? (Attach screenshots if needed)
like for example, 144ml ethylene, 1000ml of oxygen = polyethylene.  but no real way to measure out that 144ml of ethylene out to make the recipe.  cause it's not molten.  
on top of that, if I did have a molten to use, I'd be forced to make a single cell per, but a larger fluid cell would be better to make ratios of larger quantities and not have to babysit a bunch of small cells
#

**Comment by draknyte1** [comment]
GT++ has cells for 1L-144L, but they're disabled. Ask Dream nicely and they might be re-enabled.

**Comment by DoomSquirter** [comment]
144L or 144ml?  
intent is to grab multiples of 144ml as if I had gotten say 32 cells filled with molten polyethylene or something along those lines.  the whole idea is to make larger batches than just a single cells worth.

now, it would be awesome to get a 144ml cell that doesn't restrict to only molten IN ADDITION, but that wasn't really original intent of this issue.

**Comment by richardhendricks** [comment]
Just use 36B of ethylene at a time, get a nice integer number of polyethylene bars.

I do like the idea of N*144 cells.  Maybe we can make them from the  common materials that aren't already used for cells, like iron/copper/bronze/lead.

Alot of the need is covered though by the hand pumps - just take whatever and pull out the excess with the pump once your operation completes.

**Comment by draknyte1** [comment]
That's literally what my cells are 🤷🏻‍♂️

**Comment by DoomSquirter** [comment]
ah ok, thought yours was just basically a single cell that stores 144ml in it.

what I was thinking was copy the recipes for the large fluid cells but change the ring or something to a diff mat.  if that were made.

**Comment by draknyte1** [comment]
![image](https://user-images.githubusercontent.com/3060479/46096783-019cda00-c1b8-11e8-99df-d8e681df3e9e.png)

**Comment by DoomSquirter** [comment]
I'm very confused with the use of 144L.  assuming then 1000L = 1 bucket?

if this is the case, it's still not what I asked about from the beginning.  I was talking being able to have the equivalent of 32 of those last fuel cells as a starting point, so 32x144L=4608L, and so on and so on.

**Comment by draknyte1** [comment]
Just make 32 cells though?
Yes, a bucket holds 1000mb/l

**Comment by DoomSquirter** [comment]
lmao no.  read the damn ticket and you'll understand my point of why not.  

the whole idea is I have thousand of buckets worth of things I need to combine.  and I do them in batches that can fit into the fluid hatches of the lcr in a one off process.  I figure out the ratios and then put x of something in one hatch and y of something else in other hatch and walk away

it's when one side of equation is in buckets but other side is in 144ml increments.  if one side is 60 stacks of large fluid cells, that's a whole fucking lot of single cells more than likely.  

but yeah, hand pump will sorta work that out in that case.  just need to update when I see a version that's not got wierd issues with it.

**Comment by Dream-Master** [comment]
maybe we need to change the way it working now completly and ussing 144 value for fluids , moten  stuff.

**Comment by DoomSquirter** [comment]
most people and I'd probably guess that means everyone but me, just sets up processes to do all these chemistry things.

me?  I am not good at that and don't want a bazillion machines lying around doing nothing but one task so I just make large batches, as if it was a bakery and I'm making enough dough for the week.  

making polyethylene really is where I ran into this issue since it's 144L of ethylene, 1000L of oxygen gas which makes 216L of polyethylene.  I really don't care what the output is, whether it's an odd number or not since that's being stored someplace else and I never have to deal with it.

I can see why this isn't an issue when you're dealing with something that actually creates a molten cell and only holds 144L of fluid, like the polyethylene will.  it's why you need 144L of ethylene which, if you put ethylene in either GT or universal cell, both hold 1000L of ethyelene, that I see as the wierd issue.

tbh, I really don't care if this gets fixed or not.  as moron said, hand pump will rectify my situation cause I just put however much I want and suck out the extras

**Comment by richardhendricks** [comment]
Yes, I was referring to multiples of 144L as well.  It would be nice to have cells that did 8x144L (for a full stack recipe that only needs 18L per item) and 32x144L (72L per item). 

Hmm, maybe just add cutting machine recipes for cells that output cell that are "compact" x144 instead of x1000 versions. 

IE
fluid cell (1000L)-> 4x compact fluid cell (144)
large steel fluid cell (8000L) -> 4x compact steel fluid cell (8x144=1152L)
large aluminium fluid cell (32000L) -> 4x compact aluminium fluid cell (32x144=4608L)

with corresponding assembler recipes to take them the other way.

@DoomSquirter I always do 36B of ethylene at a time, gets me a nice round 375 bars of PE.

**Comment by draknyte1** [comment]
Still not seeing why we need to make anything new, when these items already exist but were explicitly disabled for GTNH on Dream's request years ago.

While I don't have any above 144L, making > 1 cell is a solution, plus I could just add such when re-enabling the rest. 🤷‍♂️

**Comment by richardhendricks** [comment]
We also have volumetric flasks, but I think large cells that hold multiple 144ml sizes would be convenient.

**Comment by draknyte1** [comment]
Get Dream to approve the existing cells and lemme know what multiples work. 

1440 is the only real addition i can think of. Maybe 2304, 4608 & 9216? (10/16/32/64)

**Comment by richardhendricks** [comment]
We have handpumps and volumetric flasks now. Don't really see a great advantage to this right now.
