### ISSUE TITLE
Cannot put Barnarda F Princess or Drone into Mutatron with Neutronium Drone or Princess

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3670]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
Prospercraft

#
#### What did you try to do, and what did you expect to happen?
Place Barnarda F Princess into Mutatron with Neutronium Drone. 

Mutate into Cosmic Neutronium Queen

#
#### What happend instead? (Attach screenshots if needed)
Unable to place them together.

#
#### What do you suggest instead/what changes do you propose?
Allow them to be combined in the mutatron,  if it's disabled-  there really is no reason to disable it; people who are at this point already put in a ton of work and effort, and just ruining their ability to finish their collection with the need for extremely low RNG is just unnecessary; especially when it takes so much power to process the combs into anything other than wax anyways that they're already only just a novelty for probably 99.27% of players.  Maybe increase mutagen cost and/or processing time instead.

Even when placing the neutronium block under the mutatron they don't combine.

**Comment by Dream-Master** [comment]
the infinity branch can't mutated with gendustry. Use Forestry and mods for breed this bee.

**Comment by Teirdalin** [comment]
> the infinity branch can't mutated with gendustry. Use Forestry and mods for breed this bee.

Is there a way aside from using mutagenic frames?  Because those work with the percentage chance that the bee itself has of mutating to begin with; which make them a bit useless on bees with allegedly 0% mutation chance.

**Comment by 0lafe** [comment]
What about electrical stimulators on alvearies? And a mutation hatch with stars

**Comment by Teirdalin** [comment]
We cap at eye of ender on mutators, and even with 17 mutators (16 if being realistic and using one with a mutagenic frame to sacrifice to the almighty bee so to speed up the process instead of waiting the entire cycle) all consuming ender eyes at once; that's still only 4xbase mutation chance each; so if it's 0.1% which is what I'm guessing from the fact it says 0% for the catalyst bee~

That'd be about 6.9% at the most.    Will look into electrical stimulators though.

**Comment by ScriptedPiky** [comment]
>What about electrical stimulators on alvearies? And a mutation hatch with stars

I tried this, it would not take anything else besides Soul Sand (1.5x mutation), Enderpearls (2x mutation), and Eye of Ender (4x mutation). And the Alveary might have a 15x hard-cap on mutation, but someone should check the code for that. Hey, can we even increase the hard-cap?
https://www.reddit.com/r/feedthebeast/comments/1xsk0q/hard_cap_on_bee_mutation_chance_bees_not_turning/

So it's forcing the player to use GT++ mutation frames (15x mutation total, you can't even use them in the Alvery because they have 3 durability and get destroyed instantly before having a use lol) and spend a large amount of time just hoping for a pure breed or even a hybrid of that specific bee that they want. It might even ages for a single outcome because of how low the chance is. And I've done bee work, it's not fun sitting there and hoping that RNG gives you a hybrid bee, let alone a pure one

**Comment by Teirdalin** [comment]
Personally I'm the only person on my server who even bothered getting this far in bees,  I wonder how rampant people at end-tier bees are on the other servers if we need it to be so difficult to get the last bees.

**Comment by Teirdalin** [comment]
> > What about electrical stimulators on alvearies? And a mutation hatch with stars
> 
> I tried this, it would not take anything else besides Soul Sand (1.5x mutation), Enderpearls (2x mutation), and Eye of Ender (4x mutation). And the Alveary might have a 15x hard-cap on mutation, but someone should check the code for that. Hey, can we even increase the hard-cap?
> https://www.reddit.com/r/feedthebeast/comments/1xsk0q/hard_cap_on_bee_mutation_chance_bees_not_turning/
> 
> So it's forcing the player to use GT++ mutation frames (15x mutation total, you can't even use them in the Alvery because they have 3 durability and get destroyed instantly before having a use lol) and spend a large amount of time just hoping for a pure breed or even a hybrid of that specific bee that they want. It might even ages for a single outcome because of how low the chance is. And I've done bee work, it's not fun sitting there and hoping that RNG gives you a hybrid bee, let alone a pure one

I actually made my Naquadria bee this way in a normal Apiary;  it took about 4 or 5 hours of attempts;  and I went as far as I could without using the mutatron before the low percentages made me figure it was suppose to be near impossible to the point of forcing the player to make the mutatron.
