### ISSUE TITLE
Crafting a wand without scales/screws

### ISSUE THREAD

**Issue by ljjmrlion** [GTNewHorizons/NewHorizons#3675]
Iron Capped Thaumic scepter does not require screws scales etc. (It crafted correctly so It's not just visual)
Storage is 120 of each, parts used were iron caps and a thaumium wand core from thaumic bases

![image](https://user-images.githubusercontent.com/9472512/46109879-dc0bd280-c1af-11e8-8168-2568ed3479e0.png)

**Comment by Dream-Master** [comment]
@Zoko061602 any idea if this is a bug in the TC Wand mod ?

**Comment by ljjmrlion** [comment]
@mitchej123 Wanted to let you know that I just tested and this bug no longer exists.
