### ISSUE TITLE
Suggestion: Add PVC quest between ethylene and SMD quests in MV

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#3676]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was working on the SMD quest while having all the prerequisites, and then noticed that the last item in that quest was fabricated out of PVC and aluminium foil, with PVC needing a fairly involved production line that was non-existent at that point in time, rather than being a "known resource".

#
#### What do you suggest instead/what changes do you propose?
Add a quest representing the PVC production line, for example:
1. vinyl chloride cell
2. liquid PVC cell
3. PVC sheets

Since vinyl chloride can be made with either chlorine gas or hydrochloric acid, I'd leave that out as prerequisite to avoid forcing the player into a specific route.

**Comment by Dream-Master** [comment]
Sure send me the quests file when done or make a pull request. @combusterf

**Comment by combusterf** [comment]
I had to hand-tweak a few things, probably because I don't understand BQ. Does this work?
[pvc_quest.patch.txt](https://github.com/GTNewHorizons/NewHorizons/files/2435505/pvc_quest.patch.txt)
