### ISSUE TITLE
Suggestion: Mithril Armor

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3678]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### *sigh*  What do you want this time Teirdalin?
So I was making a ton of Mithril with my Mithril bee and figured: "Hey,  It'd be pretty cool if we could make some mithril chainmail,   as light as a feather and as strong as dragon scales." 

And so I ended up posting this on the github.

Suggested Recipe:
XXX
XXX  x == Mithril rings
XOX
_____
Mithril Chainmail:  Diamond Chestplate worth of protection, and very high durability and enchantability.

XVX  V == Infinity Rings
VKV  X == Mithril Rings
XVX  K == Mithril Chainmail
_____
Glowing Mithril Chainmail:  Higher than Diamond protection, has a neat texture of infinity mixed with the mithril chainmail look.   Unbreakable.

Even if just used for appearance armor, it'd be nice to have more fun uses for Mithril.

**Comment by Dream-Master** [comment]
If somone code it why not.

**Comment by shawnbyday** [comment]
@Dream-Master do you prefer this as part of another mod? Really all that would be added is a couple assets and some crafttweaker stuff. Mithril is GT so not sure if it should go in there or if you guys have a different methodology? I know could also go in core mod too but I'd hate to create a whole separate mod just for this.

**Comment by Teirdalin** [comment]
If it was a separate mod consisting entirely of making GT equipment that could be interesting.

**Comment by shawnbyday** [comment]
Would that even be worth the time though? I don't know. I was looking at it as an addition to something but if there are a bunch of armors missing maybe @Dream-Master is right here. How many different armors are missing out of curiosity?
