### ISSUE TITLE
Recycle old Coke-Ovens

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#368]
We talked about that already. I have 444 CokeOven Bricks (The actual Block, not the single brick) in my Chests. Would be nice if they could be turned back into those single bricks, so you can actually "upgrade" your old coke ovens instead of throwing them away

**Comment by Dream-Master** [comment]
Will make a recipe for it.

**Comment by Namikon** [comment]
Also, i assume you wanted to cool down the "Hot netherrack brick" in the Vacuum freezer, and not the blast furnace.
Second: The yield is too low for the last recipe. You throw in one infernal and one Coke oven brick, so you should get 2 advanced bricks

**Comment by Dream-Master** [comment]
Will look inside this too.

**Comment by Dream-Master** [comment]
Done
