### ISSUE TITLE
Machine Cover Suggestion: Precision Conveyor

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3681]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this probably never happen? 
Prospercraft
#
#### Teirdalin you just made a suggestion ten minutes ago, what do you want?
So we really lack a very good means of turning all the different tiny dusts we have- 140 different kinds of tiny dusts, into large piles aside from either having molecular assemblers autocrafting each dust or having 140 different packagers as we always end up with 1-8 pieces of tiny dusts in the packagers.

So my suggestion is a means of pulling exact amounts from a storage;  say we want to only send packets of 9 tiny dusts to the packager from a chest.

Even better if it's an ME precision export, but I think something similar to the conveyor module is really good enough..

**Comment by richardhendricks** [comment]
The super buffer does this already?

**Comment by richardhendricks** [comment]
Try checking out the "Handle tiny dusts like a K1ng" quest.

**Comment by Teirdalin** [comment]
Oh!  Thanks Richard!

**Comment by bartimaeusnek** [comment]
also to export this from an ME use a ME Oredict Export bus and type 

> dustSmall*

or

>dustTiny*

**Comment by Teirdalin** [comment]
> also to export this from an ME use a ME Oredict Export bus and type
> 
> > dustSmall*
> 
> or
> 
> > dustTiny*

Speaking of the ore directory export, do you know if there's any tricks for preventing some results? 
Like for example-
dustTiny* -copper
The above of course doesn't work, but something similar to that.

**Comment by richardhendricks** [comment]
I think you could do it by chaining with another item that supports white/blacklists, like ProjectRed or Translocators.

**Comment by alphaNOVAircraft** [comment]
The data orb just shows that where your items are ^^ in the data orb not accessible to you. You need to click with the screwdriver on the output side to adjust how many items it should push out.

**Comment by Teirdalin** [comment]
Ah,  got it working.  Thanks.

I'm surprised nobody on here knew about this thing; it's amazingly efficient.  RIP my room of like 60 packagers and filters.

**Comment by richardhendricks** [comment]
The superbuffer can hold up to 256 items.  You'll see them if you have Holoinventory turned on, but realistically you don't care what's in there, just that it squirts them out in groups of the proper size.

FYI, I added a new mode to it (normal chest buffer as well) that will only output multiples of the requested value.  Otherwise when you are outputting to an input bus on the Amazon Warehouse multiblock packager it doesn't work correctly.

**Comment by richardhendricks** [comment]
>I'm surprised nobody on here knew about this thing;

It's literally a quest. :D

We still need to add the GT++ multiblock packager quest I think.

**Comment by Teirdalin** [comment]
> > I'm surprised nobody on here knew about this thing;
> 
> It's literally a quest. :D
> 
> We still need to add the GT++ multiblock packager quest I think.

Speaking of quests, I've been stuck on an EV quest even though I'm making like,  UV and UHV machines now.  lol

Radium 226 Dust instantly decays for me, posted it earlier and it didn't get much attention; curious if this is happening to anyone else as I haven't really seen anyone talking about it, and there's no notes or anything on the posts about it on the github.  Anyways; any ideas how I might be able to get the quest to finish in the meantime while people fix it?
