### ISSUE TITLE
[RFC]NEW GT BEES

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#3682]
All Gendustry Bees are put into gt code.

New recipes loos like this.  (see pics below)
To balance the recipes better i need your suggestions here. Thanks

Iron Combs:
![image](https://user-images.githubusercontent.com/2970688/46170851-3c2d7200-c29f-11e8-9b92-1c7b67e37013.png)

Manganese:
![image](https://user-images.githubusercontent.com/2970688/46170866-494a6100-c29f-11e8-9f61-022797279796.png)
![image](https://user-images.githubusercontent.com/2970688/46170885-549d8c80-c29f-11e8-8f99-c51a0f681780.png)
![image](https://user-images.githubusercontent.com/2970688/46170888-57987d00-c29f-11e8-8892-680e1134c4c3.png)
![image](https://user-images.githubusercontent.com/2970688/46170897-5bc49a80-c29f-11e8-8ada-72d7187f6794.png)

Platinum
![image](https://user-images.githubusercontent.com/2970688/46170932-7139c480-c29f-11e8-979c-0d1f75aa3bc0.png)
![image](https://user-images.githubusercontent.com/2970688/46170942-772fa580-c29f-11e8-80ca-e509e4b9a1f1.png)
![image](https://user-images.githubusercontent.com/2970688/46170962-80207700-c29f-11e8-87ac-bcca524543e8.png)
![image](https://user-images.githubusercontent.com/2970688/46170968-844c9480-c29f-11e8-8c49-4eaf4bbe2219.png)

**Comment by Dream-Master** [comment]
Cosmic Neutronium
![image](https://user-images.githubusercontent.com/2970688/46171039-b65df680-c29f-11e8-8249-e0353257f748.png)
![image](https://user-images.githubusercontent.com/2970688/46171044-bc53d780-c29f-11e8-9034-bc73f6db60fa.png)
Naquadria
![image](https://user-images.githubusercontent.com/2970688/46171081-d4c3f200-c29f-11e8-94c3-813cd01794d6.png)
![image](https://user-images.githubusercontent.com/2970688/46171093-dd1c2d00-c29f-11e8-8ccd-a5385c0cc57d.png)
![image](https://user-images.githubusercontent.com/2970688/46171097-e1484a80-c29f-11e8-891b-888aa941e6f0.png)
![image](https://user-images.githubusercontent.com/2970688/46171116-e9a08580-c29f-11e8-9290-db02f31725f5.png)
![image](https://user-images.githubusercontent.com/2970688/46171127-ed340c80-c29f-11e8-9f32-3a38f6922efb.png)

**Comment by Dream-Master** [comment]
[mods.zip](https://github.com/GTNewHorizons/NewHorizons/files/2425692/mods.zip)
if you want to check changes deeper download this two mods and replace in od folder. Enable gt bees in config foler/gregtech gregtech.cfg and run the game. Not foeget to backup your old files and saves.

**Comment by bartimaeusnek** [comment]
Growth Medium is way to cheap compared to UUM imo. Also i'd suggest not having any centrifuge recipes > HV Materials, kinda like vanilla GT "harder combs" recipes.

**Comment by Dream-Master** [comment]
yea 0lafe said the same. Will remove it.

**Comment by YinScape** [comment]
If my calculations are correct, at UV, centrifuging combs for cosmic neutronium will provide 0.000000926 neutronium per second [(1/9) * 0.005 chance / 600 seconds] , per centrifuge.  After a day, you would not be expected to make even a single tiny dust in a UV centrifuge.  Is there something I'm missing, or is this really the expected difficulty?

**Comment by noobyaran9** [comment]
>If my calculations are correct, at UV, centrifuging combs for cosmic neutronium will provide 0.000000926 cosmic neutronium per second [(1/9) * 0.005 chance / 600 seconds] , per centrifuge. After a day, you would not be expected to make even a single tiny dust in a UV centrifuge. Is there something I'm missing, or is this really the expected difficulty?

Its for meme purposes. Unless u plan to have like hundred amps of Max voltage.

**Comment by 0lafe** [comment]
Alsoooo imo comb autoclave with UU recipes should be buffed a bunch. Bees for ores kind of sucked even at 9 Combs to 1 dust, and nerfing it even more isn't the way to go Imo. I'd say change it to like 9 Combs + 10L UU = 4 purified ore. Kinda buffed but it should be useful now

**Comment by 0lafe** [comment]
>If the idea is to provide alternative methods of resource harvesting and production, without bypassing the intended barriers (space), then why not? Yes, active planet mining would produce more per unit time, but Minecraft is a game of self-selected goals, and I do not think GT:NH is any different. We shouldn't close off this avenue of production unless it is inherently broken or negatively affects the enjoyment of the pack.

There's really 2-3ish ways to make infinity not including bees, and while active planet mining works wonders if you aren't quarrying but mining yourself. However, we already have a fairly balanced simple power -> infinity method that's more than viable, so I don't see a use for bees in this case. I don't mind the IC bee, but I'd rather see it as THE endgame bee, because the current ways to get infinity catalyst just sucks. However, infinity/neutronium is fine imo as it is. Considering bees will either bee worse or better than what we currently have, and at that point in the game there's no reason to not use only the best option. Which either means bees, which I don't think should be the primary source of infinity, or no one will use the bees because they're underpowered.

**Comment by YinScape** [comment]
Just because something is underpowered doesn't mean someone won't use it.  However, there is a point where its just *that bad* where noone actually would and I believe the current C.Neutronium and Neutronium fits that bill.  Running a single UV centrifuge for a day on Neutronium combs has an currently expected yield between 1 and 2 TINY dusts, far, far less by several orders of magnitude than what you can achieve with a short trip on a planet.

**Comment by noobyaran9** [comment]
>Neutronium and Neutronium fits that bill. Running a single UV centrifuge for a day on Neutronium combs has an currently expected yield between 1 and 2 TINY dusts, far, far less by several orders of magnitude than what you can achieve with a short trip on a planet.

As for the recipe right now, its practically useless. To the point where the existence of the bee is just pointless.

**Comment by 0lafe** [comment]
>Just because something is underpowered doesn't mean someone won't use it. However, there is a point where its just that bad where noone actually would and I believe the current C.Neutronium and Neutronium fits that bill. Running a single UV centrifuge for a day on Neutronium combs has an currently expected yield between 1 and 2 TINY dusts, far, far less by several orders of magnitude than what you can achieve with a short trip on a planet.


I guess I forgot a part then. I disagree that bees should be allowed to get up to the level of making infinity/cosmic neutronium, and especially not at rates that compare to the current methods. Mostly for the cost, considering industrial apiaries are LuV ish and bees are free to reproduce. Making mass amounts of infinity takes UV+ recipes and a lot of them, with a decently high power draw that dwarfs gendustry hives (unless with the nerf they went up to like millions of EU/t lol)

**Comment by YinScape** [comment]
> > Just because something is underpowered doesn't mean someone won't use it. However, there is a point where its just that bad where noone actually would and I believe the current C.Neutronium and Neutronium fits that bill. Running a single UV centrifuge for a day on Neutronium combs has an currently expected yield between 1 and 2 TINY dusts, far, far less by several orders of magnitude than what you can achieve with a short trip on a planet.
> 
> I guess I forgot a part then. I disagree that bees should be allowed to get up to the level of making infinity/cosmic neutronium, and especially not at rates that compare to the current methods. Mostly for the cost, considering industrial apiaries are LuV ish and bees are free to reproduce. Making mass amounts of infinity takes UV+ recipes and a lot of them, with a decently high power draw that dwarfs gendustry hives (unless with the nerf they went up to like millions of EU/t lol)

I don't see an issue with creating high-end combs taking next to effectively EU, as the cost is in processing the combs,  currently a full C. Neutronium dust from bees takes 10.8 Trillion EU, base.

**Comment by 0lafe** [comment]
>I don't see an issue with creating high-end combs taking comparatively little EU, as the cost is in processing the combs, currently a full C. Neutronium dust from bees takes 10.8 Trillion EU, base.

Because any speed faster than useless is overpowered

**Comment by SeppDE** [comment]
Only an thought... Why not combine the comb + raw ore to raise the output?

**Comment by 0lafe** [comment]
Is that much different than the recipes with combining the Combs with crushed ore? Only ores can't be used if you use a multiblock miner.

**Comment by SeppDE** [comment]
> 
> 
> Is that much different than the recipes with combining the Combs with crushed ore? Only ores can't be used if you use a multiblock miner.

My thought was for the high end materials like cosmic neutronium and so on where the images above telling me there is an direct recipe. So to change them that they are the same as the other recipes. 
If raw ore means the oreblock itself or the crushed variant.. that's an easy choice.

**Comment by 0lafe** [comment]
Ah those bees, either way I'm still strongly on the side of they shouldn't exist in the first place
