### ISSUE TITLE
radium226 is impossible to obtain

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#3683]
#### Which modpack version are you using?
.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i was sifting purified uranium 238 to get radioactive radium 226 dust for the radon decay in EV,
#
#### What happend instead? (Attach screenshots if needed)
radium dust decays instantly right when you put it in your inventory  which makes it impossible to pass the quest, but you still get the decayed radium

**Comment by Dream-Master** [comment]
@draknate1 why radon havent a decay time on servers ?

**Comment by draknyte1** [comment]
If I knew, don’t you imagine I’d have fixed it weeks ago when it was first reported? 🤷🏻‍♂️

**Comment by PoptartOverlord-Xabedo** [comment]
well if its alright, could you remove this part of the quest for now?

![image](https://user-images.githubusercontent.com/40670872/46175308-2e361c00-c2b4-11e8-86bf-2876ab5c56d1.png)

**Comment by Teirdalin** [comment]
I'm making UHV machines, and am still EV in the quests.

Life is suffering.

**Comment by Kiwi233** [comment]
this issue still exist in 2.0.6.2

**Comment by Dream-Master** [comment]
hope it is fixed now in 2.0.6.6. Version will be out if I get a go from Alkalus gt++ dev

**Comment by draknyte1** [comment]
I think the quest should only require the decayed dust for completion anyway. Would've fixed this ages ago, but I guess we never thought of it. lol

**Comment by Dream-Master** [comment]
so is this fixed server side or not. Sure i will change the quest but if it decays immediately not good. I like it need some time.

**Comment by draknyte1** [comment]
Fixed for Christmas - https://github.com/draknyte1/GTplusplus/commit/1b1e3c0601a1cc93dcb04005fffbabf6294bf84b#diff-891178162bd6ef53db9c84a54df95a4c

If it continues to break after that, it's 100% related to using non-forge.

**Comment by Dream-Master** [comment]
ok we will see. Btw @draknyte1 can I use version 60 for new release?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57199549-055ebf00-6f46-11e9-9f14-48a8353aae8b.png)
