### ISSUE TITLE
MT Core recipe broken

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3684]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Craft MT Core, recipe does not work.
#
#### What happend instead? (Attach screenshots if needed)
![](https://puu.sh/BCpsr/e23a5678ff.png)
#
#### What do you suggest instead/what changes do you propose?
Fix the recipe

**Comment by Dream-Master** [comment]
i guess it is a issue with the neutron reflectors. Will check
