### ISSUE TITLE
Suggestion:  Make Stargates Not Complete Garbage

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3686]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you mean make Stargates better?  They're perfection incarnate and EXTREMELY OVERPOWERED!!!!

So, stargates are arguably the worst multiblock in the modpack due to their price and how they're worse in arguably every way to say a draconic portal or blood magic transposer; or even a charm of dislocation.

Currently the way stargates work,  you build the entire multiblock in each area you want to be able to teleport to, and then keep them powered and setup computers or use the dial to 'call' those locations to activate the portal while fueling it with an amount of power based on how far the destination is for however long it is activated. 

A portal takes well over 100-200 Field Generator (Tier VIII)s, an atrocious number of UV sensors and infinity, and tons of other resources, and tons of neutronium -   For each stargate you want to make in your teleportation system, and you'll probably want like 6 or so for it to not just be a bigger waste of space than it already is.

So my suggestion is to make them cheaper, maybe around the same tier that you reach T7 blood magic,  as to be a reasonable choice for a teleportation system to setup at friends bases so you can actually have a purpose for it, or have augmentStructures=true so that people exploring can find stargates and connect their stargates to ones found in the world, giving a fun use for the mod.

Otherwise;  I honestly don't see the point of having such a cool geeky multiblock teleport being arguably impossible to make, I get the idea is "Well you don't make stargates, you find them"  but having the world gen option off goes against that logic, making you have to make them.   Having a stargate doesn't give you access to every dimension or all the infinity metal you can eat;   it just lets you phone other stargates, and with nobody going through spending a month or three crafting some stargates for their towns and bases; you're not going to even have anywhere to call.

If the reason it's so painfully expensive to make is to prevent people from just making these instead of-  honestly I cannot think of any worse alternatives than a stargate-  so another option maybe is to just increase the power cost to open the portal, maybe have it take a UHV of power to open and 2a of UV to maintain?

**Comment by boubou19** [comment]
if they cost that much resources, it's because Dream doesn't want players to be able to spam it.

**Comment by Teirdalin** [comment]
> if they cost that much resources, it's because Dream doesn't want players to be able to spam it.

Why.. Would anyone spam stargates?

**Comment by Teirdalin** [comment]
If the existence of stargate mod is just so someone can make a single stargate after they complete the modpack and have literally nothing to do anymore so they can just- look at it, 3D printing Stargates far surpasses the usefulness of Stargates.

**Comment by richardhendricks** [comment]
I'd be OK with them being available to players post-Mars, if we can figure out more reasons to build bases or outposts on planets.

**Comment by Teirdalin** [comment]
> I'd be OK with them being available to players post-Mars, if we can figure out more reasons to build bases or outposts on planets.

They could be interesting on space stations.

**Comment by SeppDE** [comment]
Like on the middle station between milky way and pegasus?

They should be expansive/complex to build. There are other sources of teleport which are cheaper as mentioned above.

**Comment by Teirdalin** [comment]
> Like on the middle station between milky way and pegasus?
> 
> They should be expansive/complex to build. There are other sources of teleport which are cheaper as mentioned above.

Why exactly should they be so painfully expensive to build? What major advantages does a stargate give over the other teleportation systems that make them so vastly superior?

The fact they need an additional stargate on the other side as well doubles the price.

**Comment by richardhendricks** [comment]
Why did you close this? @Dream-Master What do you think on this one?

**Comment by Dream-Master** [comment]
sure we can change recipes but it need to be tiered right and balanced. And btw normaly stargates can only be found in the original series so a crafting recipe must be op.

**Comment by richardhendricks** [comment]
@Teirdalin Propose some details.

**Comment by 0lafe** [comment]
Can you enable them only in space, so you need to make one in your base and travel from there to spots you find on planets? You could always make 2 but it would be a lot more expensive and not help with much. Could make it an assembly line recipe that you need to scan a Stargate part for, so you need to find one to start making them. Tiering it is hard, because there's still no real consensus on when intersimensional people transport should be gated. Waystones still haven't changed, and probably need it way more than Stargates. LuV imo is a good spot for them, give waystones an LuV assembler recipe, make Stargates use the assembly line, eio is LuV already which works great. DE is LuVish, needing UV parts but that can sort of be done in LuV (overclock the assembly line/ebf and that's most of it) 

If it took like 256 LuV field gens to make and a bunch of LuV superconductors, and an amp of LuV to be stable, that seems fair imo.

**Comment by richardhendricks** [comment]
Doesn't look like there is a dimension limitation inherent to the stargate itself, but I think we can use some of our other tools to prevent placement on the Overworld, Twilight Forest, Nether, End.  What about the new garden dimension?

**Comment by richardhendricks** [comment]
It is free/open source, so maybe we can code limitations/changes into it if we really want.

**Comment by Highbeam** [comment]
you can also make the recipe give 2 of each stargate like the translocator recipe :)

**Comment by Teirdalin** [comment]
Oooh; stargates spawning very rarely in space and needing to scan each part to get assembly recipes for them would be very cool. 

Plus then can setup your own stargate to connect to ones you found prior in space.
