### ISSUE TITLE
Book of knowledge, Gadomancy

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3687]
#### Which modpack version are you using?2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
i made book of knowledge and try to auto reserch with it
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/25811344/46243713-63875a80-c3d7-11e8-97cb-9d83755b3719.png)
i get logged out and when io try to reconect it happens again. back to loogin screen.

this worked as intended in singelplayer in creative mode. 

#### What do you suggest instead/what changes do you propose?
look into the probblem and make it so i can log in again

**Comment by bartimaeusnek** [comment]
some mod is interfering with Gadomancy when you create clusters, this might be similar

**Comment by Teirdalin** [comment]
Interesting,  I also have an issue with those books but on multi.

Basically the research papers despawn.

**Comment by Ghengis88** [comment]
placing the book on a pedistal is fine, the problem occurs when you toss a reserch note at it

**Comment by Ghengis88** [comment]
is there any other way to auto reserch btw?

**Comment by Ghengis88** [comment]
@Teirdalin I had thet problem in Delta server last year

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?
