### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by marco6971** [GTNewHorizons/NewHorizons#369]
http://pastebin.com/zbJwiqzG, however i can't replicate this

**Comment by Dream-Master** [comment]
I guess this  have something to do with extra utilities hammering sound problem. Did  you loading the ressource Pack we add ? (AntiRWTemaSounds.zip)
I get a similar crash yesterdaytoo  when I unlock a archiment with the Fireworks sounds. 
Atm i think i can nothing against it sorry.

**Comment by marco6971** [comment]
oh yes, it works. it solved another problem, the random play a sound of upgrading a tool in tool forge even if i was doing other thing.
what do you think to add this mod http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2233909-mineralogy-mod for real world underground?

**Comment by marco6971** [comment]
really sorry, even this i can't replicate http://pastebin.com/1Tk5mD3Z

**Comment by Dream-Master** [comment]
Mineralogy is maybe a nice mod. I using some times ago pfaa on a Server and the chunk generation are very slow. I never played with Mineralogy but i guess it is better for a single player pack than for a Serve Pack.

The 2. Crash i never have but i will post it on malis doors side.
When the crash occur? what you did to get this crash?

3. Do me a favor and open for different things different issues. One for a crash and a nother for a suggestion.

Thanks.

**Comment by Dream-Master** [comment]
https://github.com/Ordinastie/MalisisDoors/issues/56

**Comment by marco6971** [comment]
ok sorry, i must do it now or it is a request for future?  and the only thing that i have done is to close a door of a structure that i have found and i use for house, but minecraft doesn't crash again when i try to close the door, i retried many time but nothing.
sorry for my probably bad english

**Comment by Dream-Master** [comment]
no problem. I post the crash and we will see what happend.

**Comment by Dream-Master** [comment]
So I close this. Open a new issue if necessary.
