### ISSUE TITLE
[Suggestion] Extra Bees Frames Research Path

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/NewHorizons#3691]
#### Which modpack version are you using?
2.0.5.1
#### If in multiplayer; On which server does this happen? 
Own private server
#### What did you try to do, and what did you expect to happen?
When searching down the path to find out how to finally make Chocolate Frames (or any Extra Bees frame), it wasn't as straightforward as I thought it might be, for something as simple to make as that. It's after all the Essences of XYZ and then the Dimensional Singularity. While it requires Infusion, the frames don't.
#### What do you suggest instead/what changes do you propose?
Positioning them behind a slightly earlier research, maybe just in Apimancy's start, or something such as 
```
Healing Frame - behind Essence of False Life
Proven Frame - behind Essence of Everlasting Durability
Chocolate Frame - behind Essence of Fickle Permanence
```
Maybe the idea is pointless, but it didn't make much sense as-is.

**Comment by Dream-Master** [comment]
will check the script
