### ISSUE TITLE
SAG Mill for Wrought Iron

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/NewHorizons#3692]
#### Which modpack version are you using?
2.0.5.1
#### What did you try to do, and what did you expect to happen?
Put a Wrought Iron Ingot into the SAG Mill to get Wrought Iron Dust
#### What happened instead?
Zip, nada, nothing
#### What do you suggest instead/what changes do you propose?
Adding Wrought Iron Dust as a SAG Mill output. There might be other missing ingots, but it looks like a lot of GT ingots are already supported, but at least not Wrought Iron.

**Comment by Dream-Master** [comment]
will check
