### ISSUE TITLE
Naquadah Reactor Mark V dont work

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#3695]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
![20181001112655](https://user-images.githubusercontent.com/25171639/46268429-f7d6f600-c56c-11e8-8b01-0fe4db748ab3.png)
tooltip say use Naquadria Long Rod
#
#### What happend instead? (Attach screenshots if needed)
![20181001112645](https://user-images.githubusercontent.com/25171639/46268453-0cb38980-c56d-11e8-8c13-329e91eddddb.png)
but nothing happen
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by bartimaeusnek** [comment]
@FallDark was this build before the update? if yes it might help to re-place it, else ill have to look deeper in code

**Comment by FallDark** [comment]
i create a new world and place it but it doesnt work

**Comment by bartimaeusnek** [comment]
do the other Naquadah gens work for you?

**Comment by FallDark** [comment]
> do the other Naquadah gens work for you?

yes

**Comment by Dream-Master** [comment]
will check uv machine

**Comment by FallDark** [comment]
any news on this issue?

**Comment by Dream-Master** [comment]
i remember i fix that. @FallDark  can you test this in 2.0.6.6 which are out soon?

**Comment by FallDark** [comment]
i test with jenkins latest build but still the same

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea why this not working ?

**Comment by Technus** [comment]
Should be resolved.
