### ISSUE TITLE
Bound Pickaxe

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3697]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
get money from my proffession (Miner) went whacking away with my bound pickaxe expecting to reach limit quite fast
#
#### What happend instead? (Attach screenshots if needed)
nothing, mining with the bound pickaxe rightklick wont generate income from Miner job
#
#### What do you suggest instead/what changes do you propose?
Add this? dont see how this differs from breaking blocks with any other tool?

**Comment by boubou19** [comment]
hammer mode of the world breaker doesn't generate money too
