### ISSUE TITLE
Opencomputers Transposer Recipe Not Assembling

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3698]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Assembler some transposers.

Transposers to assemble.
#
#### What happend instead? (Attach screenshots if needed)
Nothing. 🔥 

![a](https://user-images.githubusercontent.com/37776581/46389878-93f61f80-c689-11e8-8174-7a594e16c752.PNG)
![b](https://user-images.githubusercontent.com/37776581/46389883-95bfe300-c689-11e8-8e95-a75ae5a0f419.PNG)

Have in it:

Advanced Assembling Machine III
 15,892L Molten Polyethylene

 1x Low Voltage Chest buffer
 1x Inventory Controller Upgrade (No meta)
 1x Tank Controller Upgrade (No meta)
 2x Polyethylene Sheet
 2x Cable
 1x Programmed Circuit == 1
#
#### What do you suggest instead/what changes do you propose?

Fix it?  I don't think I did something wrong with the recipe.

**Comment by repo-alt** [comment]
Strange, I tested that on Epsilon server and it worked fine.

**Comment by repo-alt** [comment]
I believe the current version is 2.0.7.5
