### ISSUE TITLE
Suggestion:  Compatability between Pollution Detection Device and OpenComputers

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3699]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### Whatchu' Talkin' Bout' Teirdalin?!
So my suggestion is to fix the scanner result when scanning the Pollution Detection Device with a scanner, as right now the scanner always says "Current Pollution: 0".    This would allow OpenComputers to get the pollution level.

Or add a method in the device allowing opencomputers to call the pollution that it detects.

**Comment by draknyte1** [comment]
GT++ issue, go raise it it’s GitHub.

**Comment by Dream-Master** [comment]
@Teirdalin

**Comment by Teirdalin** [comment]
> @Teirdalin https://github.com/draknyte1/GTplusplus/issues

Thanks Dream.
