### ISSUE TITLE
Obsidian processing unbalanced

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#3707]
#### Which modpack version are you using?

2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
SP

#
#### What did you try to do, and what did you expect to happen?

Using a macerator to turn an obsidian block to dust is super inefficient.
You can use the alloy smelter to turn it to 9 ingots, then pulverize the ingots for 1 dust each. 9 times the output and much faster.

Similar with plates, one obsidian block turns into one plate, also one ingot turns into one plate.

Current recipes:
obsidian block in allow smelter -> 9 obsidian ingots
obsidian block in pulverizer -> 1 dust
obsidian ingot in pulverizer -> 1 dust
9 obsidian ingot i compressor/alloy smelter/extruder -> 1 obsidian block

#
#### What do you suggest instead/what changes do you propose?

Probably want to make 1 block into one ingot only. Can't really say one ingot should turn into tiny pile of obsidian dust, because that would be obsidian nuggets.

**Comment by Dream-Master** [comment]
Its a cross mod problem between ic2 vanilla and gt i guess. If yo found the issue and fi it i am very happy @DarkShadow44
