### ISSUE TITLE
Quest ID: 1166 Tells Player to Look in Wrong Y Level

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3709]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Was working on quest id: 1166 (Quartz and Quartzite Veins. Expected to find those ores between Y=40 and Y=80 as quest states.
#
#### What happend instead? (Attach screenshots if needed)
Accidentally found the vein at 115. Asked in Discord and apparently ore was moved up. It is also wrong on the spreadsheet.
#
#### What do you suggest instead/what changes do you propose?
Fix the quest and spreadsheet when you can.

**Comment by bartimaeusnek** [comment]
Do NOT use the speadsheet. It is outdated since 2.0.0.0! Use this to generate your own spreadsheet:
https://gtnh.miraheze.org/wiki/GT-NEI-Ore-Plugin_Spreadsheet_Export_Tutorial
