### ISSUE TITLE
Storage Drawers Addons

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#371]
Storage Drawers have mod addons for other Mods Wood variants. (like the addons for Bibliocraft) Did we have to add that ?

http://minecraft.curseforge.com/projects/storage-drawers#title-6

**Comment by Dream-Master** [comment]
we add it if no one complains.

**Comment by Drobac** [comment]
Its just decorative so i dont see why not

**Comment by Dream-Master** [comment]
Added
