### ISSUE TITLE
Suggestion:  OpenComputers Quests/Tiered Computer Lootbags

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3710]
#### Which modpack version are you using?
2.0.5.1
#
#### Sheesh you post a lot of suggestions on here Teirdalin.

So I made some OpenComputer quests over the past seven hours learning how to use better quests, if anyone would like to review it and tell me what they think.

#
-Original Post-
```
[OpenComputers Quests Fixed.zip](https://github.com/GTNewHorizons/NewHorizons/files/2452682/OpenComputers.Quests.Fixed.zip)


![opencomputer](https://user-images.githubusercontent.com/37776581/46566693-710d7a80-c8d8-11e8-823d-d2bcfbfa42ed.PNG)

Had a couple oddities I encountered with the quests like three items not making sense with the power tier a player should be making it so gave them as rewards,   also I noticed one of the parts don't seem to use ore directory-  specifically the microchip only uses Good Electronic Circuit,  but gave the quest ore directory detection for it as I figured more than likely this is just something overlooked too.

Goes into setting up your first computer, installing your OS, mounting the hard drive, and making a startup program and a default directory.     As well as a guide program explaining a way to do simple small loops and grab data from a GT machine; displaying how much power is in a 2x2 battery buffers batteries using a function call.

If floppy disks properly save to opencomputers that is, otherwise the powerdisplay program will just not work I suppose.


There is still a lot more to opencomputers, but I feel as if this is a decent start.   Still need to go over T2, T3, T3.5, servers, music, internet interactions, local and wireless computer networking, tablets, robots, upgrades, drones, and 3D printing.  But I don't feel there's much of a huge rush for that.


```

-Update: Oct 9, 2018-

![computers](https://user-images.githubusercontent.com/37776581/46705026-81786a80-cbe2-11e8-94d0-4dafbd3b63ac.PNG)
![lootbag](https://user-images.githubusercontent.com/37776581/46705027-81786a80-cbe2-11e8-9b22-8fcd29455bf6.PNG)

[OpenComputers Quest Update 2.zip](https://github.com/GTNewHorizons/NewHorizons/files/2462656/OpenComputers.Quest.Update.2.zip)

Edit- Removed duplicate item in lootbag list.

Can probably use some more balancing but I think it's fairly reasonable currently.  Gives a use for the uncraftable bitcoin and a use for bulk crafting dogecoins.

**Comment by Teirdalin** [comment]
Hang on, forgot to add the power display tutorial disk to it-

**Comment by Dream-Master** [comment]
looks good so far. Will do some minor changes and put in the next release. @Teirdalin thanks
