### ISSUE TITLE
annoying space race quest placement

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#3711]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
After getting back from the moon, smelt the meteoric iron I collected to complete the quest, and continue in the space race quests to build the t2 rocket.
#
#### What happend instead? (Attach screenshots if needed)
After the smelted meteoric iron ingots quest is the quest to go to the moon dungeon (quest "Moon Dungeon" number 1403), which requires you to hold the dungeon chest key. However the quest book requires you to go home and smelt meteoric iron before coming back and doing this, which is annoying. But making matters worse is that the player might not know this is coming up and kill the boss on their first trip, meaning they would have to find another dungeon for no reason just to complete the quest.
#
#### What do you suggest instead/what changes do you propose?
Change the quest placement to be immediately after the rocket, or change the quest to only require the schematic so people don't have to go back and redo it.

**Comment by DualBallers** [comment]
What if the ingots are changed to 32 dust and 32 crushed meteoric iron instead. 
Then you can complete the quest while on the moon, and then you go find the dungeon after.
