### ISSUE TITLE
Fun Machine Suggestion:  Lasers!

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3718]
#### Which modpack version are you using?
2.0.5.1
#
#### Lasers you say,  tell me more!

So I think we could use some laser emitter machines for each power tier, which can be adjusted with different diodes and power tiers that are also adjustable via opencomputers methods and have hand-held versions; allowing you to make your own handheld laser devices.

The lasers could melt or destroy certain materials or deal certain types of damage; there are some strong lasers in the world, and just in general there are fun things that can be done with such a thing; maybe can even connect them to detectors to make a sort of laser detection grid.

Mayhaps can even use lasers as a method of sending some power.

**Comment by Teirdalin** [comment]
> For laser machines, Gregtech's precision laser engravers exist.
> 
> For lasers which can deal damage or destroy blocks, IC2's mining laser exists.
> 
> For wireless Gregtech power transmission you can use microwave energy transmitters, which are available starting at the HV tier.

Gregtechs precision laser is boring and just engraves items.

IC2s mining laser is a handheld tool which, honestly kinda sucks and has a habit of crashing servers when using one of its modes.

Those are microwaves and not lasers.

**Comment by DualBallers** [comment]
While the idea is neat it sounds like something for a mod on its own, especially when talking about completely new mechanics.

**Comment by Teirdalin** [comment]
> While the idea is neat it sounds like something for a mod on its own, especially when talking about completely new mechanics.

Maybe,  GTLasers would be an interesting mod to exist.
