### ISSUE TITLE
GT++ hot ingots can be processed without vacuum freezer

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#3719]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
Delta (I've set up a demonstration flow)

#
#### What did you try to do, and what did you expect to happen? What happend instead? (Attach screenshots if needed)
I noticed that the fluid extractor has recipes for hot ingots - The GT++ ones can be melted straight into its fluid form, the standard gregtech ingots don't.

This discrepancy allows one to fabricate inconel-792 at the MV tier, rather than around EV/IV. The tiny inconel fluid pipe has a higher capacity than huge stainless steel pipes, breaking the original gregtech pipe tiering: there's no incentive other than a possible niobium shortage to make stainless steel pipes and this could remain this way for a few more pipe generations.

#
#### What do you suggest instead/what changes do you propose?
This appears to be an oversight; GT++ hot ingots should act like their gregtech counterparts and not be processable anywhere other than the vacuum freezer.

**Comment by Dream-Master** [comment]
@combusterf did you report this on gt++ side allready?

**Comment by combusterf** [comment]
No I haven't, where do you want it forwarded to?

**Comment by DualBallers** [comment]
https://github.com/draknyte1/GTplusplus/issues

**Comment by combusterf** [comment]
https://github.com/draknyte1/GTplusplus/issues/387

**Comment by combusterf** [comment]
Just a heads up: this is now fixed in GT++
