### ISSUE TITLE
To much loot

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#372]
Did we need this Mod? 
We have control over all vanilla Loot tables/Chests

http://minecraft.curseforge.com/projects/toomuchloot

**Comment by Drobac** [comment]
Dont really thing so? is there other then random ingots and dusts in the chests?

**Comment by Dream-Master** [comment]
There are only vanilla loot chest in the config not roguelike dungeons or Twilight Forest chests etc.
I did not checked all stuff but i not see any totally op stuff in there.
I will try the mod from father toast too.

**Comment by Dream-Master** [comment]
ok skip
