### ISSUE TITLE
Assembler recipe for basic Forestry circuit can't use NAND chips

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#3722]
#### Which modpack version are you using?
2.0.5.1
#
#### Description of issue:
NAND chips are supposed to be able to serve as a replacement for vacuum tubes in recipes that require vacuum tubes. However, the recipe for Forestry's basic circuit board in the assembler can only use vacuum tubes and these cannot be substituted for NAND chips. I suggest adding in the option to substitute NAND chips for vacuum tubes in these recipes.

**Comment by Dream-Master** [comment]
@bartimaeusnek can you add the circuit oredict fuction to circuit assembler recipes too?
