### ISSUE TITLE
When creating ritual Mystical Construct, the game crash

### ISSUE THREAD

**Issue by 648643579** [GTNewHorizons/NewHorizons#3723]
Server: Delta
Date: 07.10.2018
Every time a ritual is performed, all players who are nearby will crash the game.
(all the items that were used for the ritual are lost)
Ritual Mystical Construct: https://i.imgur.com/DKdU7Y4.png

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3502
