### ISSUE TITLE
Problem with quest "Copper capped Greatwood wand"

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#3724]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
SP

#
#### What did you try to do, and what did you expect to happen?
Tried to complete the quest "Copper capped Greatwood wand". That quest states that you need to make a copper capped greatwood wand first - before you can make a gold capped greatwood wand - since the old wand limit is 25. However, t1he cost for a copper capped greatwood wand is also greater than 25.

#
#### What happend instead? (Attach screenshots if needed)
You can't create a copper greatwood wand yet, you first need to make an iron capped greatwood wand. When you have that, you can make a gold capped greatwood wand, why would you want to make a copper capped greatwood wand just for the quest?

#
#### What do you suggest instead/what changes do you propose?
The quest should be for an iron capped greatwood wand instead, this way it would work.

**Comment by richardhendricks** [comment]
Is that true with robes etc decreasing costs?

**Comment by DarkShadow44** [comment]
I'm not aware of any vis cost decreasing items, I'm afraid.

**Comment by richardhendricks** [comment]
https://thaumcraft-4.wikia.com/wiki/Thaumaturge%27s_Robes

plus there are others

https://ftbwiki.org/Bloody_Thaumaturge%27s_Robe

I'm not sure where they fit in the wand progression though.

**Comment by DarkShadow44** [comment]
Ah I noticed that a gold capped normal wand can be used to make a copper greatwood wand... But the quest puts it like you could make a copper greatwood wand right away, which is misleading.

But why would I make a gold capped normal wand, then a copper greatwood wand and then a gold capped greatwood wand when I could just make an iron greatwood wand and then a gold capped greatwood wand? Still would be better to change the quest, I guess.

**Comment by DarkShadow44** [comment]
Robes and the likes are not enough btw, you'd need the googles of revealing too - which I can't make, since I need a better wand first..

**Comment by Dream-Master** [comment]
ok i can change the quest to iron capped wand  first.

**Comment by DarkShadow44** [comment]
Thanks for fixing this!
