### ISSUE TITLE
Ore finder bug with redstone ore

### ISSUE THREAD

**Issue by jvb50m** [GTNewHorizons/NewHorizons#3725]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
When you use any of the ores that spawn in a redstone vein the finder does not work. The bar goes up and down randomly no matter if their is redstone ore or not. Did not detect redstone when I placed it down and stood ontop
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Fix the mod

**Comment by draknyte1** [comment]
Ores contain a flag, to show if they’ve been player placed. I assume the wand ignores player placed ores.

**Comment by jvb50m** [comment]
Well that still leaves the issue if it detecting ore when it is not their

**Comment by richardhendricks** [comment]
The ore wand doesn't ignore player ores.  It only samples an area around it, +-6 XZ.

It has a 60 block range down/up. So if your redstone vein is at Y=20 and you are at Y=82, you are not going to detect it.

The length of the bar/animation depends on the number of blocks of ore it detects.  One ore block is not going to send it to 100%. 1 block = 10%.

Also, it will trip on small ores, so to detect redstone/lapis veins using redstone/lapis ore, you have to wait until the bar fills completely/the ore finder flips over/starts making noise.

If you have cinnabar or ruby ore, you can use that instead to prevent false positives from small redstone ores.

https://github.com/GTNewHorizons/IFU/blob/master/src/main/java/com/encraft/dz/items/ItemOreFinderTool.java

**Comment by jvb50m** [comment]
Alright. But the glitch still happens with ruby and cinnbar ore

**Comment by richardhendricks** [comment]
Pics plz.

**Comment by richardhendricks** [comment]
Oh one more thing, the orefinder doesn't check continuously, only every so many ms.  I think it's configured to 200 right now.

**Comment by jvb50m** [comment]
OK turns out i'm an idiot and you guys are correct that it does work. I justs didn;t know that it detected small ores and when I saw that it did not detect ruby and cinnabar ore when I tested it out I just assumed that it was broken

**Comment by richardhendricks** [comment]
No worries, it is a little confusing.  We will consider updating the tooltip to explain that.
