### ISSUE TITLE
Create book with official server commands

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3726]
Create a book that can be used on the live server to educate people about server life.

Finding a starting spot

Using the Questbook.

Jobs

towns

homes

warps

Server costs

Teleporting Commands

**Comment by richardhendricks** [comment]
http://minecraft.tools/en/book.php

**Comment by draknyte1** [comment]
GT has a built in book handling function set.. they’re just relatively unused.

**Comment by richardhendricks** [comment]
Will investigate.  I looked at the seismic prospector books a long time ago, might be able to use something based on that.  Can I create the command with the website and spawn it with GT?

**Comment by draknyte1** [comment]
Nah, ignore that book handling. 
There’s a set of functions for making books that sits somewhere near the punchcard code. Remind me later to find it~

**Comment by richardhendricks** [comment]
gregtech.api.util.GT_Utility.getWrittenBook(String, String, String, String...)

**Comment by boubou19** [comment]
don't forget to describe town glitches so people will be aware of them, like using a wand in an area of 30 blocks outside of a town is still forbidden

**Comment by richardhendricks** [comment]
Can you clarify what you mean?  Like using your own wand within 30 block of your own claim, or using a wand outside someone else's claim?

**Comment by richardhendricks** [comment]
worldspawn - lootgames dungeoons, roguelike dungeons, twilight forest bosses

**Comment by richardhendricks** [comment]
cannot /sethome on planets
