### ISSUE TITLE
An nonsense sulfuric acid recipe

### ISSUE THREAD

**Issue by Erixonich** [GTNewHorizons/NewHorizons#3728]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I expect to don't see an nonsense reaction for sulfuric acid.
#
#### What happend instead? (Attach screenshots if needed)
non-realistic recipe.
![2018-10-09_19 08 32](https://user-images.githubusercontent.com/12836717/46682903-78de5f00-cbf7-11e8-991b-34e73ab2d512.png)
![2018-10-09_19 08 39](https://user-images.githubusercontent.com/12836717/46682904-78de5f00-cbf7-11e8-950d-9ae4c5807391.png)
![2018-10-09_19 13 37](https://user-images.githubusercontent.com/12836717/46682905-78de5f00-cbf7-11e8-8b18-7c1c939a43c8.png)
#
#### What do you suggest instead/what changes do you propose?
Since, gt5u changed a lot of chemical processes to "realistic" ones including sulfuric acid (H2S => SO2 => SO3 => H2SO4), I don't understand why this is still available (H2S + H2O => H2SO4). (Since water is very weak oxidant this reaction can't be done).
My propose is disable recipes from screenshots in favor of "real-life" ones.
P.S. I know that there are many chemically nonsense recipes but we don't have alternatives yet.
P.P.S. Thank you!

Also opened issue on gt5u repo 
https://github.com/Blood-Asp/GT5-Unofficial/issues/1499

**Comment by Dream-Master** [comment]
@Erixonich @richardhendricks we have other ways to get h2so4 so i can disable it.
Did you have another alternative cheap recipe i could add @Erixonich ?

**Comment by Dream-Master** [comment]
maybe this one ?
![image](https://user-images.githubusercontent.com/2970688/46763182-72281880-ccd9-11e8-8568-25a9c5f6c546.png)

**Comment by Dream-Master** [comment]
but wait i read a bit about sulfuric acid and they said you can make diluted sulfuric acid add water. Ok i am not a chemist so @Erixonich tell me the right to do it.

**Comment by Teirdalin** [comment]
Personally I love realism when it comes to chemistry.

**Comment by Zoko061602** [comment]
Maybe we coud change the recipe to sulfurous acid, but that would just add another material, that does nearly nothing:
H2S + O2 + H2O -> H2SO3
H2SO3 + O2 -> H2SO4

**Comment by Erixonich** [comment]
> Maybe we coud change the recipe to sulfurous acid, but that would just add another material, that does nearly nothing:
> H2S + O2 + H2O -> H2SO3
> H2SO3 + O2 -> H2SO4

Technically, H2SO3 is unstable molecule in most cases you should write SO2 + H2O

**Comment by Erixonich** [comment]
> but wait i read a bit about sulfuric acid and they said you can make diluted sulfuric acid add water. Ok i am not a chemist so @Erixonich tell me the right to do it.

I just suggest remove recipe hydrogen sulphide + water = sulfuric acid (2 small reactor and 1 big reactor recipes)
Alternative aproach is quiet correct. (SO2 + O2 = SO3 just need catalyst like V2O5 but gt reactors do not support 3 component recipes)
TY for your attention!

**Comment by sthegreat** [comment]
I also vote no here. The oxygen route has twice the efficiency per H2S so it will always be preferred by higher-tier players anyways. For low tier players it presents an interesting choice between efficiency or saving their oxygen, which they need a lot of for steel and other chemistry. Realism should not be the only goal of GT, it should be a mix of realism and nonrealism for the purpose of fun gameplay.

**Comment by Hakameda** [comment]
It should be changed, oxygen isn't a hard resource to get
