### ISSUE TITLE
Ender Collectors buggy

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3729]
#### Which modpack version are you using?
latest
#
#### If in multiplayer; On which server does this happen? 
Epislon
#
#### What did you try to do, and what did you expect to happen?
I have found Ender Collector's buggy time and time again.  The latest bug is extremely frustrating.

In the past, the main bug I have found with them, is when you break them - they 'collect' themselves which typically destroys it.  (you see the magic animation when you break it, then no ender collector).

My latest tragedy has the ender collector destroying 4 crystallisers, and then itself...  Not only that, BUT it still apparently exists somehow magically trashing everything near it!  (Screenshot is hard to show an invisible ender collector)

![2018-10-10_00 07 45](https://user-images.githubusercontent.com/32101225/46701875-77c22780-cc21-11e8-9bb3-7dc9c3bd6d69.png)

#
#### What do you suggest instead/what changes do you propose?
Not sure what to suggest on this one.  I have left the problematic ender collector where it stands on Epsilon (coords X-1597, y54, z5136) standing on top of the compressed chest it used to go into.

Getting rid of them is a bit harsh as they do work when placed, just removing them can be a problem.

I have stopped using them and only use advanced item collector's now.  But annoying it destroyed some stuff

**Comment by Highbeam** [comment]
So few things on this:

1) The Ender Collector is from Extra Utilities which I understand isn't open source...  so there's not much we can do to investigate or fix any problems.
2) The ender collector actually functions when it's placed.  It's breaking it that can be problematic.
3) I wouldn't want to vote this item out as it is extremely cool to use sometimes.

So my suggestion is as follows, add a comment to the item:

"Warning: When broken, the powerful ender collector may vanish in an attempt to collect itself!"

**Comment by richardhendricks** [comment]
"...and take nearby items with it!"

**Comment by richardhendricks** [comment]
Most likely the tile entity wasn't destroyed the same time as the visual block, so it kept operating.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/46903324-964f4980-ced3-11e8-8092-6c79a6de885b.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/46903335-af57fa80-ced3-11e8-8ffd-4fa52fa8e50f.png)

**Comment by Dream-Master** [comment]
need a bigger screen :)

**Comment by boubou19** [comment]
btw if you break the ender collector when the size is set on 1, it behaves correctly
