### ISSUE TITLE
Tank Mod

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#373]
Maybe a good mod for beginning the game. Only 53 Kb big.

http://minecraft.curseforge.com/projects/iron-tanks

Will make the recipes like the Buildcraft Tank (Copper = Copper Plates and Screws etc)

**Comment by Namikon** [comment]
Indeed, that could fill the gap between bc tanks and drums. I don't see numbers on that page , but I expect the diamond /obsidian one to be decent sized

**Comment by Dream-Master** [comment]
Diamond have 64 buckets I see in the picture.

**Comment by Namikon** [comment]
Ah true. Was too small on my phone to see it. I vote for it

**Comment by Dream-Master** [comment]
![screenshot 2015-10-12 09 10 58](https://cloud.githubusercontent.com/assets/2970688/10422916/33e81c5e-70c1-11e5-9e0b-574e9a806127.png)

**Comment by Drobac** [comment]
i like it, good for tiering

**Comment by Dream-Master** [comment]
Will make recipes for it today
- [ ] Iron Tank recipes

**Comment by Dream-Master** [comment]
Done
