### ISSUE TITLE
Compressed Solar panels

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#3731]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
lan server
#
#### What did you try to do, and what did you expect to happen?
connect order infused double compressed solar panel to a battery buffer and the plant exploded 
#
#### What happend instead? (Attach screenshots if needed)
the solar panel make 200 EU at day and 75 at night and it have small buffer and we did not notice it was EV not HV.
#
#### What do you suggest instead/what changes do you propose?
make solar magical solar panel different what i find out is the following.

- all compressed give 512 EU/T HV

- all double compressed give 2048 EU/T EV

- all triple compressed give 8192 EU/T IV

there should be a tool tip that what voltage it give or make the following.

- all compressed give 128 EU/T MV or Lv

- all double compressed give 512 EU/T HV 

- all triple compressed give 2048 EU/T EV or IV

**Comment by Teirdalin** [comment]
It seems a bit dangerous for something like that to not say the power output.   Personally I think nerfing them just because they proper tooltip is a bit much though.

**Comment by bartimaeusnek** [comment]
its a problem with the GT cables auto converting the power versus the EMT solars own energy conversion

**Comment by Dream-Master** [comment]
to bad we don't have a test server.

**Comment by bartimaeusnek** [comment]
fixed in 2.0.6.0
