### ISSUE TITLE
Change quantumprocessor recipe to IV circuit assembler 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3733]
#### Which modpack version are you using?
2.0.5.1

#### What do you suggest instead/what changes do you propose?

Quantum processors should be moved to the IV circuit assembler. In MV you can't make an MV circuit in a single craft until you make the cleanroom, which is really more HV. You can't make an HV circuit in a single step until the EV circuit assembler. In EV you can make quantumprocessors in a single step, which are EV. The EV circuit assembler lets you make HV and EV circuits in a single step, but limits the best circuit you can make to the best nano, the LuV circuit. The IV circuit assembler simply lets you make the quantumprocessor mainframe which is a zpm circuit. In LuV and onwards you need to be in a tier+1 to make that tier's circuit in a single step. Crystals are IV in LuV, wetwares LuV in ZPM, and bios ZPM in UV.

**Comment by Wolozo7** [comment]
They are IV already.

![image](https://user-images.githubusercontent.com/34921674/46852625-e5c24680-cdfb-11e8-96f3-f0892b6e9da0.png)

**Comment by 0lafe** [comment]
Totally saw that and though it was EV lol
