### ISSUE TITLE
Quest complete bug

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#3734]
#### Which modpack version are you using?
2.0.5.1(latest)
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I want to complete that quests, but... ![](https://cdn.discordapp.com/attachments/289850721988509696/499063648354959361/unknown.png)
#
#### What happend instead? (Attach screenshots if needed)
...shit happend

![](https://cdn.discordapp.com/attachments/289850721988509696/499063716977967106/unknown.png)

![](https://cdn.discordapp.com/attachments/289850721988509696/499063809961623553/unknown.png)

#
#### What do you suggest instead/what changes do you propose?
U can check my quests file and know more about problem (quest ID 962)

**Comment by Dream-Master** [comment]
it works maybe your quest file is broken or need to be reset quest wise. I get quest completed in sp. @barsikus007

**Comment by barsikus007** [comment]
@Dream-Master okay, staff can help me?

**Comment by Dream-Master** [comment]
@barsikus007 sure
