### ISSUE TITLE
Add quests for traveller's gear

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3737]
traveller's belt and gloves for sure, maybe the rest.

Piston boots?

**Comment by DoomSquirter** [comment]
btw, if you use a thaumostatic harness you can pick blocks w/o any slowness if you're flying.  when you upgrade to something else you lose that but there's a witching gadgets vambrace that actually gives that back to you and some other things.  witching gadgets might need some love quest wise cause there's some neat apparel that fit into the travellers gear slots, etc...

**Comment by richardhendricks** [comment]
Well start suggesting. :D

**Comment by shawnbyday** [comment]
I'd like to see stuff like Piston Boots on there. I know it is always an option but I missed them my first world and they help SO much with hunger before you get a jet pack to save you from all of the jumping up hills and such.

Sort of related is the jetpack quests. (Might need a separate issue but I'll post here first). You don't unlock the jetpacks until you've made the electrotine stuff. I honestly find making the steam jet pack much easier but it is gated (quest wise) behind the electrotine one. If you don't do the electrotine battery as a new player you may end up missing jet packs for a long time if you don't specifically go looking for one you can make.

**Comment by richardhendricks** [comment]
Good point on the piston boots, I'll see where a good place to insert them is in the quest book.

Yeah, I've been wanting to revamp the questbook around jetpacks for a while.  I am thinking of completely removing the electrotine one completely, or make it only a sidequest instead of a main quest.

**Comment by richardhendricks** [comment]
I'll make separate tickets for those.
