### ISSUE TITLE
Suggestion (minor): Cryotheum liquid increase

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3738]
#### Which modpack version are you using?
2.0.5.1
#
Current:
Pyrotheum to liquid is 250L
Cryotheum to liquid is 144L

I suggest making Cryotheum to liquid also 250L

**Comment by Dream-Master** [comment]
will check but I guess it's a gt++ recipe.

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues/390
