### ISSUE TITLE
World expansion - Epsilon

### ISSUE THREAD

**Issue by Taudrew** [GTNewHorizons/NewHorizons#3739]
Dear all,

Me and Hyperic were thinking about moving in together somewhere else from our current spots. However, we were very frustrated with the lack of untouched space in the Epsilon world. 

There are either claimed-but-abandonded bases that block claiming 10 chunks around or half-cut large trees or in other way impaired terrain. Also, large group of new players have come to play with us and I am very glad that we can welcome new faces to the game of death and grind, but they are facing the same issue from the very start of their fresh experience (not to mention that awful RTP).

The world map is starting to get overcrowded and finding new suitable spot requires handy helper - and even they probably start to struggle with finding new areas for new players.

There goes my question - is it possible to expand the server map? As a former player on Delta, the map was incomparably larger, thus it was easier to find a new place to call home. Would it be a huge load for the server to extend for example the borders?

Thank you for reading my post and giving the answer for people in same state of mind.

Sincerely,
Taudrew

**Comment by richardhendricks** [comment]
Staff was just discussing this recently.  If we can get a handle on the low TPS we might increase the epsilon border to equal Deltas.  Meanwhile, have you tried searching the northwestern continent? It's only attached to the main continent via a couple of narrow bridges so I bet it isnt heavily populated.

**Comment by richardhendricks** [comment]
There is a large mountain area SE of me that is lightly populated.  Or you can occupy a large snow biome, those are mostly empty. :)

**Comment by richardhendricks** [comment]
Oh also there is the Utopia garden dim, use /warp utopia to get there.  It's been sectioned off for building bases.

**Comment by Taudrew** [comment]
> Oh also there is the Utopia garden dim, use /warp utopia to get there. It's been sectioned off for building bases.

I know about Utopia very well, however that is not what I am looking for - thank you for the suggestion anyway.

**Comment by richardhendricks** [comment]
Is there so.ething specific you want?

**Comment by Ghengis88** [comment]
The limited area also poses a problem to new players finding rare ores , Mica forexample

**Comment by richardhendricks** [comment]
Epsilon has bee successfully expanded in size.
