### ISSUE TITLE
Added more Materials to the EBF

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#374]
I added more Materials to the EBF.
Iridium, Osmium, Osmiridium, Desh, Platinum, Palladium, Americium.

https://github.com/GTNewHorizons/GT5-Unofficial/commit/8f4522ad6abc919b7ef96611b624243be6213667

Did we have to add other Materials to the EBF too ?

**Comment by Dream-Master** [comment]
- [ ] Ic2 Iridium disabled in furnaces

**Comment by Drobac** [comment]
Can add the 9 tiny iridium into 1 dust, easier to automate it in EBF

**Comment by Dream-Master** [comment]
Yes io can add this too.

-[ ] add tiny and small Iridium Dust to the EBF

**Comment by Drobac** [comment]
no, i meant add 9 tiny into 1 dust in a normal crafting table as that is currently disabled. Its easier to automate if you can get full dusts

**Comment by Dream-Master** [comment]
yes but this recipes i dont touch. i touch only the IC2 iridium gem not the dust.

**Comment by Dream-Master** [comment]
Done
