### ISSUE TITLE
Update orefinder wand quest on details on how it responds.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3740]
It reports number of blocks found as length on the damage bar, above a certain number it makes a noise.  If it flips out/flips over, you got a lot.  Small ores for redstone/lapis/copper can cause minor changes in length, the full vein is very obvious.

**Comment by shawnbyday** [comment]
I created a pull request for this. I'm not the best "writer" but I figured I could at least get something in there for this since I feel like I answer this question a lot. Feel free to change it with your words when you get around to it.

**Comment by Dream-Master** [comment]
@richardhendricks @shawnbyday is this fixed ? (quest text aaded )?

**Comment by shawnbyday** [comment]
@Dream-Master I just tested it and quest text has changed. I did have to do a /bq_admin default load which is normal. As long as @richardhendricks is good with the text I added it should be ready to go.
