### ISSUE TITLE
Buffer core crafting mismatch

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3741]
2.0.5.1

The buffer core changes crafting pattern throughout the tiers.
LV circuit + HV Hull -> Buffer core LV
MV circuit + Buffer core LV -> Buffer core MV
HV circuit + Buffer core MV -> Buffer core HV
EV circuit + Buffer core HV -> Buffer core EV
IV circuit + Buffer core EV -> Buffer core IV
IV circuit + Buffer core IV -> Buffer core LuV (changes here)
LuV circuit + Buffer core LuV -> Buffer core ZPM
ZPM circuit + Buffer core ZPM -> Buffer core UV

Change from using a 'higher tier circuit -> higher tier buffer' to 'lower tier circuit -> 'higher tier buffer'.

Nerf tier LuV, ZPM, UV buffers to:
LuV circuit + Buffer core IV -> Buffer core LuV
ZPM circuit + Buffer core LuV -> Buffer core ZPM
UV circuit + Buffer core ZPM -> Buffer core UV

Is this a GT++ issue, or are the recipes already nerfed for GTNH?

**Comment by Dream-Master** [comment]
Not fixed on us side.

**Comment by DualBallers** [comment]
Changed GT++ code [here](https://github.com/draknyte1/GTplusplus/commit/9321e3c11c77630b85479646bb916149306fee05) 
`return getTieredCircuitOreDictName((CORE.GTNH && tier >= 6 ? tier - 1 : tier));`
to 
`return getTieredCircuitOreDictName(tier);`
so now the recipe(s) should straighten themself out when updates are aligned. Therefore I closed the issue.

**Comment by draknyte1** [comment]
Fixed here: https://github.com/draknyte1/GTplusplus/commit/9321e3c11c77630b85479646bb916149306fee05
