### ISSUE TITLE
Pam's Harvestcraft Olives not spawning

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#3743]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
SP

#
#### What did you try to do, and what did you expect to happen?
Tried to find Olive Trees from Pam's Harvestcraft, no such luck. Also took a look at the decompiled sources, there doesn't seem to be any code for spawning olive trees,

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Verify with other players that it indeed doesn't spawn, then maybe a quest to buy them with coins would be nice. Just for completeness sake, I'd love to have all trees.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47813978-d07e6f00-dd4c-11e8-8010-f2a7ffffb651.png)

**Comment by DarkShadow44** [comment]
Awesome, thanks!
