### ISSUE TITLE
GT++ link

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3746]
#### Which modpack version are you using?
-
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
-
#
#### What happend instead? (Attach screenshots if needed)
-
#
#### What do you suggest instead/what changes do you propose?

Many posts regarding GT++ end up on the new horizons github page, is it possible to att a "Sticky" post that is always on the top of the list named something like "REGARDING ALL GT++ ISSUES" and in that post is only a link to the GT++ github page?

**Comment by Dream-Master** [comment]
not sure if it is possible. I know Github a bit but not all functions.
