### ISSUE TITLE
Suggestion: Energy Hatch recipes (New Revision)

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3747]
Following the recent post about multiblocks #3730   I believe it is important to separate this suggestion from the main post which has now become a wall of complaint with no real individual topics unfortunately.

I will keep this topic simple: it is apparent that multiblock energy hatches are far too easy to craft at the moment enabling players to easily tier skip recipes by adding a higher tier energy hatch.

The suggested change is a very small and simple change that will also help energy hatch tier/gating, particularly at higher tiers.

Side note: That adding 2 energy hatches to achieve the next tier should be allowed for some multiblocks:  EBF, Vacuum Freezer, Alloy Blast Furnace.  Should multiblock's have this function disabled by only allowing 1 energy hatch in the multiblock form - E.G: Large Chemical Reactor?
**I also believe we need to address which multiblocks are allowed more than 1 energy hatch in their structure.  This is particularly the base for most GT++ multiblocks**

**Suggested recipe updates:**
**LV Energy Hatch** _= leave recipe as is_

**MV Energy Hatch** _= leave recipe as is_

**HV Energy Hatch** _= keep recipe and_
add HV Pump (place EV Pump opposite cable in crafting recipe)

**EV Energy Hatch** _= keep recipe and_
add EV Pump (place EV Pump opposite cable in crafting recipe)

**IV Energy Hatch** _= replace 1x Tungsten Cable_
with 1x IV Superconducting Wire
- IV Superconducting Base Wire requires **HSS-G 5.2K coils in EBF and EV Energy** _(this should be achieved in IV and the equivalent multiblock quest rewards T6 IV Lootbag - all tier appropriate)_
- IV Pump is required in the Superconducting Wire (but 6 wire is made with 1 IV Pump)

**LuV Energy Hatch** _= replace 1x Vanadium-Gallium Cable_
with 1x LuV Superconducting Wire
- LuV Superconducting Base Wire requires Naquadah 7.2K coils in EBF and IV Energy (relevant to tier)
- LuV Pump required (8 wire is made from 1 LuV Pump)

**ZPM Energy Hatch** _= replace 2x Naquadah Cable_
with 1x ZPM Superconducting Wire
- ZPM Superconducting Base Wire requires Naquadah Alloy 9K coils in EBF and IV Energy, Naquadah Alloy requires 2x LuV Energy Hatch EBF with 4A of LuV to craft.  Perfectly acceptable for LuV tier.

**UV Energy Hatch** _= keep recipe and_
add UV Pump (place UV Pump opposite cable in crafting recipe)

**UHV Energy Hatch** _= keep recipe and_
add UHV Pump (place UHV Pump opposite cable in crafting recipe)

**UEV Energy Hatch** _= keep recipe and_
add UEV Pump (place UEV Pump opposite cable in crafting recipe)

**Points to consider:**
The main area of concern in multiblock gating is between IV -> ZPM which the superconducting wires really help to achieve.  This approach will help ensure that multiblock tier skipping is avoided which is too possible right now.

By UV, superconducting wires aren't important because you have already achieved Naquadah Alloy Coils in your EBF with maximum energy.  However, the Pumps help again to keep the tiers under control.

I wasn't aware of issue #3594 when I first proposed these changes and although it may seem like a repeat, please note that it's a new approach with new recipe suggestions.  I would like to avoid the criticism and negativity in the original post and address the real issue at hand here.  Before you comment, you must realise the problem with Energy Hatches right now and the way they enable players to process recipes way ahead of tier.  This needs to be plugged.  Sorry this isn't making the game harder but its necessary to fix a bigger issue.

I have tried to suggest less complicated recipes whilst ensuring tier progression is fixed as it should be.  I'd rather not suggest multiple circuits complicated recipes as its over the top.

All suggestions welcomed and keep this positive.

Please advise if there are any holes in my logic and if any of the energy hatches cannot be crafted due to the items within needing that hatch.

**Comment by 0lafe** [comment]
If this is what the end change is, I guess I'm not too mad at it, but I'd love to see them actually cost some materials in addition to being gated. Giving them an increased cost helps with the problem of multis having almost no upgrade cost. Multiple increasing amounts of SCs starting at EV, maybe some PICs, maybe some emitters or something else. Just something that you look at in the tier and go, "I'ma have to work to make this"

**Comment by draknyte1** [comment]
> which multiblocks are allowed more than 1 energy hatch in their structure

All of them. No vanilla multi has limits on hatches, they only have minimum casing counts. None of mine limit energy IO, only ever maint, and Item/Fluid IO.

**Comment by Highbeam** [comment]
> > multiple energy hatches to tier skip.
> 
> That is literally why using > 1 is allowed in the first place though.
> As such, I will not cap them.
> 
> Plus, I'm not adding a check to each multi just for GTNH. I've stated I won't do anything of the like as a solution.

Allowing > 1 is allowed in the processing multis yes.  But your assembler, extruder etc that access all recipes are allowing players to skip tiers by placing multiple energy hatches.  Even gating the energy hatches won't prevent this...  Even the Large Chemical Reactor is questionable to have this ability considering some of the recipes it can do with circuit parts.  If the hatches aren't limited then a complete review of the recipes may be needed at some point...

For example: players can currently make UV Redox too easily just by putting higher tier/multiple energy hatches on the large assembler for example.

Can you at least give a suggestion what you think we could do to fix this situation?

**Comment by Dream-Master** [comment]
done.
