### ISSUE TITLE
Suggestion: Remove thaumcraft from Opencomputers blacklist default config.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3749]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### Whatchu' talkin bout Teir!?
So by default Opencomputers blacklists Thaumcraft as an example of how to blacklist compatibility in the config for it.
"    
    modBlacklist=[
      Thaumcraft
    ]
"
Considering that gets rid of some fun possibilities such as calculating essentia jar values via adapters or connecting your computer to show the readout on your infusions; I feel as if that shouldn't be blacklisted as it's just a bit silly;  we use so much tech and magic together in this pack that they should be more compatible with computers.

**Comment by Dream-Master** [comment]
ok why not or is someone against it ?

**Comment by Teirdalin** [comment]
> ok why not or is someone against it ?

By the way Dream, did you ever change the config for https://github.com/GTNewHorizons/NewHorizons/issues/3581    also enableTankDriver=true could be a thing too that we could change;  the inventory and tank driver configs are essentially for balancing on more vanilla packs I believe since we have-  so many other mods that do what those two configs do but for cheaper.
