### ISSUE TITLE
Crashing Epsilon :(

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3750]
#### Which modpack version are you using?
latest
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Log in
#
#### What happend instead? (Attach screenshots if needed)
Crashed server, happened 2 times
#
#### What do you suggest instead/what changes do you propose?
I think my mobfarm mith be the issue, so i think when the area loads it crashes, could someone reset all enteties in the area around my player? guess that is what causes it. some loot or something not being picked up, i will OFC tear the spawner down

**Comment by Ghengis88** [comment]
also have a personal anchor there

**Comment by Ghengis88** [comment]
There is a ender Io spawner 
And i have fans pushing the mobbs into a hole where i kill them with Diamond spikes

**Comment by Highbeam** [comment]
I talked to Bryfer and went over, both spawners are off and there was 1 infernal pech in the spike pit.  I killed him and left the area but appears the server is still crashing.

**Comment by Ghengis88** [comment]
ok closing the issue then
