### ISSUE TITLE
Add Piston Boots quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3753]
For early players, Piston Boots would help with hunger since they would not need to jump up blocks.

**Comment by Dream-Master** [comment]
good idea

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47620055-fc4beb80-dae5-11e8-9787-63a8b35b799e.png)
will add the other items later.

**Comment by shawnbyday** [comment]
I'm not sure the rest of the items from Adventure Backpacks would really be worth adding on here. Just because Iron Armor is better really and a lot easier to make in my opinion. Just my 10 cents.

**Comment by Dream-Master** [comment]
will check the item first

**Comment by Dream-Master** [comment]
wont add the other pieces because dont need it.
