### ISSUE TITLE
Quest ID: 1020 Iron (III) Chloride

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3756]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Turned my empty cells into universal fluid cells. I expected quest to complete. Also expected quest to tell me how to make Iron (III) Chloride but it ended at the Universal Fluid Cell.
#
#### What happend instead? (Attach screenshots if needed)
Quest didn't complete. Didn't show how to make Iron (III) Chloride
#
#### What do you suggest instead/what changes do you propose?
Remove the Universal Fluid Cell requirement and show the recipe for Iron (III) Chloride Cell. Quest guides you to make enough for 2 cells so 2 cells should complete it?

**Comment by Dream-Master** [comment]
duplicate issue. Will change assp

**Comment by shawnbyday** [comment]
Okies, sorry. I did search but just for the quest ID.

**Comment by Dream-Master** [comment]
np
