### ISSUE TITLE
 proposal about Radon gas

### ISSUE THREAD

**Issue by boozzeeboom** [GTNewHorizons/NewHorizons#3757]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
RU GNTH server - Wabulabudaba - MelkoCraft.ru
#
#### What did you try to do, and what did you expect to happen?
Want to change Radon Gas manufacturing
#
#### What happend instead? (Attach screenshots if needed)
For now Radon manufacturing not like in real life, but we can change it.
#
#### What do you suggest instead/what changes do you propose?
New Reciept:
ingot Uran-238 x1 + Air cell x1  into Chemical Reactor = tiny pile uran-238 x8 + dirty cell radon-222 x1
or make some with fluid(gas) without cell.

Then
dirty radon-222 x1 + Air filter (tier 1 or 2 or something else like absortion filter) into Centrifuge = mixed radon-222(gas) x1 + 1 tiny pile uran-238.

Then 
x64 mixed radon-222 cell+argon cell x1(or 1000mb into fluid slot centrifuge) into centrifuge = 1 clean radon + 63 Air cell (or H, O, Gas like: x32 Hidrogen + x28 Oxigen + x3 Salt water(or dirty water\water)

**Comment by 0lafe** [comment]
The more I look at this the more I like it. Still pretty much need a T2 rocket to make it, but instead of a lot of dumb single planet stone processing its a longer gas processing recipe that uses uranium in a net neutral way. Which is interesting. The air filter though, can it be used like a circuit, so it's not a durability thing and just stays in the input? Also, what time's would this take and eu/t?

**Comment by boozzeeboom** [comment]
it can be circuite, but i take iform from Wiki about radon and it's need some filtering. I think, we can add "carbon" filter for that with cheap manufacturing. 

about eu\t:
_Info from Wiki:  1 mm3/day per gram of radium_
So only first step should take a lot of time, time for filtering and centrifuge should be quickly.

**Comment by draknyte1** [comment]
Nobody would ever do this though when you can sift uranium for neptunium which then decays to Radon..

**Comment by boozzeeboom** [comment]
radium it's time to create from WIKI. actually radon can be found from U-238
From wiki: _222Rn belongs to the radium and uranium-238 decay chain, and has a half-life of 3.8235 days_

**Comment by draknyte1** [comment]
And that’ll get fixed at some point.. but there’s why nobody would ever use the proposed recipe above now, because Rd226 instantly decays.

**Comment by 0lafe** [comment]
Considering how little it's used I would be in favor of removing that recipe, removing the base GT one, and using this new one. Then use radon much more in lategame recipes, like fusion or maybe processing stuff for naq. Could use it for circuits too. More interesting/more steps than the current ones. Probably won't be making a lot until lategame if it works like this.

**Comment by Dream-Master** [comment]
@draknyte1 is this fix in lastest source of gt++ ?

**Comment by draknyte1** [comment]
Items decay works as expected in my ssp and smp test environment. 

Maybe it’s related to using Non-Forge? No clue how to test that properly.

**Comment by Dream-Master** [comment]
i can setup a thermos server on my pc and run both instances.

**Comment by 0lafe** [comment]
Why was this closed? It's a fairly decent Rn suggestion

**Comment by mitchej123** [comment]
Issue is almost a year stale, and from what I could tell by reading, is a GT++ issue.  If it's still relevant reopen it.

**Comment by 0lafe** [comment]
The ++ side isn't much related to the issue as a whole. If Rn is changed, ++ Rn would need to change too to make it at all balanced. I'd reopen it if I could
