### ISSUE TITLE
Infinity sword from avaritia cannot be crafted

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3758]
#### Which modpack version are you using?
Live version
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Trying to craft Infi sword
#
#### What happend instead? (Attach screenshots if needed)
nothing

![2018-10-20_13 46 59](https://user-images.githubusercontent.com/25028786/47254814-98834c00-d46f-11e8-9da0-ec29dc791eff.png)
![2018-10-20_13 47 13](https://user-images.githubusercontent.com/25028786/47254815-991be280-d46f-11e8-9b9c-aeee7bc44fae.png)

**Comment by Dream-Master** [comment]
Did you use infinity plates. I just update script 10 mins before on epsilon.

**Comment by Cinobi** [comment]
Ofc
![2018-10-20_14 50 04](https://user-images.githubusercontent.com/25028786/47255297-75f53100-d477-11e8-9aad-b4267c8ebf87.png)

**Comment by Spartak1997** [comment]
@Dream-Master I found mistake in script <IC2:itemNanoSaber:1>. You should write <IC2:itemNanoSaber:*>

**Comment by Dream-Master** [comment]
I change that allready @Spartak1997

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47618550-ec77db80-dad4-11e8-8772-4cf3b7c5f4e5.png)
work now.
