### ISSUE TITLE
Wireless Transmitter/Reciever recipe changes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#376]
REther Pearl - either revert back to original recipe or change the recipe to the assembler and use molten redstone ( In automation this uses up 2 whole machines just to make 1 item)
WIreless Transciever - Change Molted Red Alloy into Molten Redstone
Reciever Dish - Remove Molten Tungsteel from the recipe, Tungsteel is already used to craft the wireless Transciever + using molten tungsteel again uses up 2 machines to make just 1 item

**Comment by Dream-Master** [comment]
Look inside this later.

**Comment by Dream-Master** [comment]
I change the molten tungsten steel to molten ender.
All recipes need molten restone not redalloy.
I don't change the REther Pearl because i dont like all recipes be in the assembler. (only change to molten redstone)
