### ISSUE TITLE
Centrifuge Fire Charge = Blaze Powder with wrong meta id

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3760]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Centrifuge Fire Charge for:
Blaze Powder 377
Gunpowder 289

#
#### What happend instead? (Attach screenshots if needed)
It gives:
Blaze Powder 377:32767
Gunpowder 289:32767

Coal dust is fine though.

They cannot be used in any recipes.

#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by Dream-Master** [comment]
this must be fixed in 2.0.5.1. Show me the recipe @Highbeam

**Comment by Dream-Master** [comment]
a found it. One wa left in the core mod.
