### ISSUE TITLE
Can no longer shape chiseled glass in the architecture table (also cannot chisel shaped glass).

### ISSUE THREAD

**Issue by melignus** [GTNewHorizons/NewHorizons#3761]
#### Which modpack version are you using?
2.0.5.1 (problem first showed up several months ago, my brother can't recall what version the error showed up in)
*_he now recalls that it stopped working around April, but I'm not sure what version we were on. I do know until summer we were updating within days of new releases_.
#
#### If in multiplayer; On which server does this happen? 
Our family server on AWS.
#
#### What did you try to do, and what did you expect to happen?
Place chiseled glass into the Architecture table and get shaped chiseled glass out.
#
#### What happend instead? (Attach screenshots if needed)
This no longer works. Vanilla glass still works and can be shaped. Chiseled glass cannot be shaped, and shaped glass cannot be chiseled. The roof of our factory didn't disappear, but we're unable to produce more of the chisel textured shaped glass to repair or expand.
#
#### What do you suggest instead/what changes do you propose?
I figure that chisel is probably fine because we still have the chiseled shaped glass roofs. They didn't disappear on us. But I think maybe a block meta value changed for the chiseled glass to where the architecture table no longer detects the chiseled blocks as valid input.

**Comment by melignus** [comment]
I was able to fix this by patching a method in ArchitectureCraft that checks for "acceptable materials." I'm going to try and pull the hard coded values out into a config file and submit the patch to the maintainer. Then I'll reply back here with an update.

**Comment by Dream-Master** [comment]
@melignus we have architecture table forked so far i know. Send me a pull request if you want.

**Comment by Dream-Master** [comment]
@melignus i need more infos and pics from the block you want to put in.
