### ISSUE TITLE
Crazy Suggestion: New Tiers, a good excuse for Toxic Everglades

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3767]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you suggest instead/what changes do you propose?
So the whole 'infinity metal is the endgame' is starting to get a bit old; and infinity catalysts, cosmic neutronium, and neutronium and honestly even infinity are all easy enough metals to get all together once you hit deep dark, sorta making them not necessarily the best metals to cram into the main mats for all the new machine tiers past UV; so my suggestion is new tiers of metal past infinity .   Maybe we can increase the recipes for every part of the toxic everglades portal to be way more endgame, and use the metals that are gathered there in making some new types of metals for even higher tiers than infinity.

Currently that place isn't too useful for,  honestly anyone who doesn't feel like just processing the stuff there into other things in mass bulk; and we can really use more variety than just sticking infinity into everything end-game.   Optionally maybe Australia can be the new endgame.

**Comment by Dream-Master** [comment]
Not sure what @draknyte1 is planig with this dim. Need to gate the portal/key behind infinity ? @Teirdalin

**Comment by Teirdalin** [comment]
> Not sure what @draknyte1 is planig with this dim. Need to gate the portal/key behind infinity ? @Teirdalin

Nah,  was just a suggestion that we could make it have its own tech tiers worth of resources.  Currently the stuff we get there isn't that useful on their own unless you process like half a stack for some oxygen, uranium, and other fairly random stuff. lol

**Comment by draknyte1** [comment]
Australia dim will be early game if I ever add a way there. 

Everglades is for EV/IV~
Since you can get Gd, Sm and other rare resources.

**Comment by 0lafe** [comment]
From looking at the like 40 long ass names for the ores there, it looks pretty good. Mostly just sammarium which isn't the worst thing
