### ISSUE TITLE
Steel pickaxe only gives redstone mining level

### ISSUE THREAD

**Issue by mtjohnson47** [GTNewHorizons/NewHorizons#3768]
#### Which modpack version are you using?
GTNH 2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Personal server, default configs
#
#### What did you try to do, and what did you expect to happen?
Made a steel pickaxe head & such as per questbook.  Should be able to mine obsidian.
#
#### What happened instead? (Attach screenshots if needed)
The shovel and axe give obsidian mining level, but the pickaxe head only gives 04-Redstone.
![image](https://user-images.githubusercontent.com/5100948/47333810-f4a1c800-d649-11e8-810f-a9a63391f789.png)
This can be bypassed by making an obsidian head from the flint & steel quest.  However, if someone unknowingly picks the ball of moss instead, they'll be unable to progress.

#
#### What do you suggest instead/what changes do you propose?
Giving steel pickaxe heads obsidian mining level, or
Changing the flint & steel quest from a choice reward to an item reward.

**Comment by Bryfer** [comment]
Level up the mining XP
Then it will be the stats it's supposed to be, tico tool's are weaker for a while when you change materials

**Comment by mtjohnson47** [comment]
Ah.  Well, I solved it by completing the flint & steel quest and making an alumite pickaxe.

**Comment by Dream-Master** [comment]
@mtjohnson47 can this be closed?

**Comment by Dream-Master** [comment]
JEI is not available for 1.7.10 must be NEI.
Steel material is from vanilla Tinkers not from gt. Not sure if we can change there anything.

**Comment by mtjohnson47** [comment]
Ok, not a bug, go ahead and close.  (I wasn't able to test before, because my pick was stuck in a grave in the nether)
