### ISSUE TITLE
Alternative Magic Energy Generator - Blood Power

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3769]
#### Which modpack version are you using?
2.0.5.1
#
#### Blood power you say?

So my suggestion is some tiers of generators that turn the liquid Life Essence into electricity.  Could be a alternative fuel for blood mage towers; although certainly should certainly be costly of a conversion rate considering how much LP you can make with the right setup.

**Comment by Anarack** [comment]
This can already be done indirectly though the lava creation ritual.

**Comment by Teirdalin** [comment]
> This can already be done indirectly though the lava creation ritual.

That is a fun idea actually; but a straight-forward conversion would be nice too; as that'd be drawing from the soul network rather than the liquid.

**Comment by Dream-Master** [comment]
we can add it as fuel to the magic erergyconverter from gt if that helps @Teirdalin @Anarack  ?

**Comment by Teirdalin** [comment]
> we can add it as fuel to the magic erergyconverter from gt if that helps @Teirdalin @Anarack ?

Oh;  that actually makes a lot of sense.  lol

**Comment by Anarack** [comment]
We could make it as a fuel but picking a fuel value would be hard... not really sure what sort of yeilds you would want per sacrifice altar.
For example a  optimized tier 6 altar for only sacrifice can make a lot of blood, and a very wide range of blood production depending on the setup..

Super altar assumptions
108 sacrifice runes
38 dislocation
19 acceleration
some sort of mob system to feed it.

max 11.72 L/t per mob or  min 0.92L/t per mob for a terrible altar using the well of suffering
NOTE: the max may be higher as I am allowing for a very high transfer speed altar.

using the Serenade of the nether to produce lava the range produced from a altar would be
500 L per lava bucket
or 23.44 L/t per mob to  1.84 L/t per mob

using the GT:NH LHE values that gives us assuming using super heated steam(not sure the gt++ versions ratios off the top of my head might be better or show up earlier) 
1,875 L/t per mob to 147.2 L/t per mob

or final eu values being assuming 1.4 and 0.75 efficiency turbines for each end
3,938-165.375 EU/t per mob.

So with the above bulky setup you can get a lot of power out of them. Keep in mind the minimum is just a naked altar and the max is a tricked out T6 which is in the EV/IV/LUV range deping on what messing around with EBF's you do.

**Comment by Teirdalin** [comment]
Well;  just need to keep in mind just what power tier someone making that much power would actually be at.  Even though they may be making a ton of blood,  it may not really be enough to really fuel their power needs adequately anyways when converted to energy.

That aside though,  there probably could be some real balance changes with energy conversion rates.  I mean a single nether star gives 100,000,000 EU and by that point you are  mining actual veins of the stuff.

**Comment by Dream-Master** [comment]
How much eu one cell of blood should give in the magical energy comverter?

**Comment by Ghengis88** [comment]
I can look into it @Dream-Master

**Comment by Ghengis88** [comment]
while thinking about this i came to the conclusion thet if we want Blood magic EU production we should have it as a singelplayer only,
say we find a decent value for how much EU 1cell of blood will give. 
thwn someone sets up a altar and wants to generate blood with well of suffering. then realises he gen feed 1 altar with 4 rituals if they overlap 1 block, then you have a 19x19 x10 area where you can generate LP, then feed potentia to all rituals and you have 19x19x20, not make floors, you can fit 8 floos that is 3 hich ioncluding floor above, so the spawnebal area is 19x19 times 8, that is equal to 53x53. now hav all this area filled with mobs constantly. that could probbably take a toll on server tps, and then say more then 1 player make this setup. to me it feels like a good way to bring the server to its knees, but in a singelplayer senario i guess it could be fine.

bur i like the idea, just dont think it is siuted for multiplayer servers

**Comment by Dream-Master** [comment]
@Ghengis88 is can be only added for both modi or we close this issue @Teirdalin

**Comment by Ghengis88** [comment]
i think it is hard to balance it, you can generate SOOOO much LP witht the right setup but if we find a balance it is a cool idea, but as i said in my previous post i think it can have a very bad effect on a server

**Comment by Ghengis88** [comment]
bur for me you can close this, cool idea but to hard to implement in a good way

**Comment by 0lafe** [comment]
I mean, people can butt fuck the server with a gigantic zombie farm that turns rotten flesh to methane. Turbines go past converters, so you'd need less stuff making the power, and it's probably easier than doing a ton of thaum infusions for BM. However, no one does that because it's useless. I'd assume the same would apply to blood magic power generation. It's doable, but why do it when you can make like 4 IV solars faster than that (inb4 solars OP)

**Comment by Dream-Master** [comment]
what about put the slates in . Spartak make a pull for it.
