### ISSUE TITLE
New recipes required: Plasma Generator Mark IV and V

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#377]
Added to the CoreMod. Please do recipes for them, so that they match with Tier I, II and III.

**Comment by Dream-Master** [comment]
Have this Blocks any funktions atm?

**Comment by Namikon** [comment]
Yes. They are full functional Plasma Generators, registered within GregTech. The original ones where supposed to be 1 Tier higher, but either Greg or BloodAsp derped here; They are one Tier lower than they are supposed to be. So in theory, I just added one additional Tier: UV. ZPM Level was always supposed to be available with MarkIII.

I just did the registration of the machines. The code/textures/sound/... is all handled by Gregtech. And this also means, that we could add even more machines and stuff, I didn't expect it to be so easy to add stuff in Gregtech without.. touching gregtech at all

**Comment by Dream-Master** [comment]
Recipes allready there.
