### ISSUE TITLE
Suggestion: Alloy smelter recipes move/clone in other machines

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3770]
#### Which modpack version are you using?
2.0.5.1
#
There's a few recipes that require alloy smelter/fluid solidifier with specific molds.  I believe some of these recipes could be allowed in other machines.  Some of the softer materials like glass/wax can be done in the forming press:

**1x Glass Tube 6546:32012**
Add recipe to Forming Press = 1x glass dust + ball mold

**1x Glass Bottle 374:**
Add recipe to Forming Press = 1x glass dust + bottle mold

**1x Wax Cast 4943**
Add recipe to Forming Press = 9x wax + block mold
Wax types:
Beeswax 4883
Refactory Wax 4884
Magic Wax 6815
Soulful Wax 6815:1
Amnesic Wax 6815:2

**1x Glass 20**  (Glass Block)
Add recipe to Forming Press =1 glass dust + block mold / 4 small glass dust + block mold / 9 tiny glass dust + block mold / 2x Glass Shard 5352 + block mold

**1x Certus Quartz Tank 2080**
Maybe ? remove this from Alloy Smelter and put into Assembler or crafting window?
Assembler:  8x Quartz Glass 239 + circuit 8
(seems weird to make a tank in alloy smelter like this?)

**1x Quartz Glass**
Add recipe to EBF: 1x Glass + 1x Certus Quartz Dust

(recipe conflict with Glass -> Clear Glass.  Update existing EBF recipe Glass -> Clear Glass to require circuit 1)

**1x Fused Quartz**
Add recipes to EBF:
2x Certus Quartz Dust + 2x Quartzite Dust
2x Nether Quartz Dust + 1x Glass Dust
2x Nether Quartz Dust + 2x Quartzite Dust
2x Certus Quartz Dust + 1x Glass Dust
1x Nether Quartz Dust + 1x Borosilicate Glass Dust
1x Certus Quartz Dust + 1x Borosilicate Glass Dust

**1x Enlightened Fused Quartz**
Move recipe to LV Assembler only:  1x Fused Quartz + 4x Glowstone
(similar to Vibrant Quartz Glass)

**1x Dark Fused Quartz**
Move all recipes to LV Assembler only: 1x Fused Quartz + 4x Black Dye
Black Dye = 
Ink 351
Shadow Ink 5177:1
Black Dye 4755:9
Tenebrous Egg 7251
Black Dye 5147:24
Black Deviating Lily seed 7961:15
Black Dye 6545:32414
(remove from chem bath also)

**5x Battery Alloy Dust**
Add recipe to Mixer:  4x Lead Dust + 1x Antimony Dust

**10x Soldering Alloy Dust**
Add recipe to Mixer: 9x Tin Dust + 1x Antimony Dust
(also good for Fluxed Electrum)

**3x Magnalium Dust**
Add recipe to Mixer: 1x Magnesium + 2x Aluminium

**3x Astral Silver**
This recipe is a big of a mess.  There is a crafting recipe and an EV Alloy Smelter recipe.  I recommend removing both the crafting recipe and the Alloy Smelter recipe and putting this in the Mixer with EV power and fixing the dust values:  2x Silver Dust + 1x Thaumium Dust = 3x Astral Silver.

Anvils = maybe no change - probably should remain in solidifier/alloy smelter as it uses dense alloys

**Comment by Highbeam** [comment]
Is the certus quartz tank supposed to be a steam level tank?  If so, then I recommend a crafting recipe instead as alloy smelter seems weird?

**Comment by Dream-Master** [comment]
1x Enlightened Fused Quartz
Move recipe to LV Assembler only: 1x Fused Quartz + 4x Glowstone
(similar to Vibrant Quartz Glass)
no it will stay in ender io alloy smelter

**Comment by Dream-Master** [comment]
1x Dark Fused Quartz
Move all recipes to LV Assembler only: 1x Fused Quartz + 4x Black Dye
Black Dye =
Ink 351
Shadow Ink 5177:1
Black Dye 4755:9
Tenebrous Egg 7251
Black Dye 5147:24
Black Deviating Lily seed 7961:15
Black Dye 6545:32414
(remove from chem bath also)

why i like the recipes

**Comment by Dream-Master** [comment]
added it to the assembler

**Comment by Dream-Master** [comment]
cant find an astral silver ev alloy recipe. Will remove the crafting one and add a mixer ev one.

**Comment by Dream-Master** [comment]
ok all done
