### ISSUE TITLE
Point players to IC2 crop sticks in farming tab when given ore berries

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3771]
Reduce rewards to 9-18 berries

point players to ic2 cropsticks missions

make sure missions unlock early on

multiblock tank #45
smeltery #74
BBF # 76
Redstone # 494
Copper ore # 825
Iron ore # 826

**Comment by Dream-Master** [comment]
i reduce 20 to 10 berries and 10 to 5.

**Comment by Dream-Master** [comment]
it cant before important tools. Long sticks need file

**Comment by Dream-Master** [comment]
will do the crop sticks quest link to stone age page.
