### ISSUE TITLE
Quest#1534 Issue

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3773]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon 
#
#### What did you try to do, and what did you expect to happen?
Complete quest 1534
#
#### What happend instead? (Attach screenshots if needed)
Cant find Ledox Ore, Has orespawn changed? befor Ledox only spawned on tier 4 planets? and the source for Ledox when crafting tier 4 plates was Europa ice, wich is still a easier way to get ledox then finding th ores.
#
#### What do you suggest instead/what changes do you propose?
change what the quest requires to ledox dust insterad of ledox ore, Players will find no joy in serching for ledox ore when they already got ledox dust from the ice they got while serching for the ore.

**Comment by Dream-Master** [comment]
will check Europa oregen

**Comment by Ghengis88** [comment]
hmm, i was just very unlucky then :(
