### ISSUE TITLE
Suggestion:  Ability to use cells instead of buckets in Liquid XP recipes, maybe even extension on the liquid xp crafting and uses.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3776]
#### Which modpack version are you using?
2.0.5.1
#
#### I like apples, sometimes.
So my suggestion is for the recipes to make random things with liquid xp to allow for cells as well as buckets;  buckets are nice for early game automations but due to the low stack size and the fact they hold the same as a cell; feel like universal cells should also be usable in the recipes.

Kinda feel like the liquid xp crafting could perhaps be expanded a bit; perhaps some assembly recipes using liquid xp and different circuit configurations and differing power costs for some other basic things; this would then allow for xp craft costs over 9000kB (outdated joke not intentional); maybe could even add in some chemical bath recipes that use liquid xp too; like say making an ender pearl into a eye of ender for 10,000kB with HV power, of liquid xp,  or turning a blaze powder into a blaze rod with 6,000kB liquid xp and some MV power, and other conversions.

Seems like some fun uses could be for the stuff with machine compatibility.

Perhaps we could even add liquid xp as a fuel for the magic energy converters; if we add life essence like in the previous blood magic suggestion to it; this would definitely fit as a fun magic fuel.

**Comment by Dream-Master** [comment]
Not sure if i can fill liquid ex into cells?

**Comment by richardhendricks** [comment]
Heavily disagree.  I think XP crafting is way too powerful already, and shouldn't be automated.

**Comment by Teirdalin** [comment]
> Not sure if i can fill liquid ex into cells?

Can confirm it definitely works with the universal cells; not with normal though.

**Comment by 0lafe** [comment]
>Heavily disagree. I think XP crafting is way too powerful already, and shouldn't be automated.

It's not already automated? I'm confused, but also agree it's already too OP. I'd much rather see the whole mechanic removed, or switched to only mob drops. Makes more sense for a mob to give multiple mob drops than create elements imo

**Comment by Teirdalin** [comment]
> > Heavily disagree. I think XP crafting is way too powerful already, and shouldn't be automated.
> 
> It's not already automated? I'm confused, but also agree it's already too OP. I'd much rather see the whole mechanic removed, or switched to only mob drops. Makes more sense for a mob to give multiple mob drops than create elements imo

I think he might mean that he disagrees with larger scale small storage of it in cells instead of buckets, but not quite sure.
Pretty sure experience would still exist even with exp from mobs disabled though.  lol

**Comment by Dream-Master** [comment]
xp crafting is poor mans uumatter crafting. But xp crafting shouldt  that powerful like uumater crafting.

**Comment by Scottishprog** [comment]
Right now, I see XP crafting as a safety valve for GaAs etc.

If you want to eliminate the mechanic, please find a replacement safety valve.

**Comment by sthegreat** [comment]
I disagree that As would need another source if xp crafting were removed. Realgar is a pain, but you can get cobaltite ore from the TF and EBF cobaltite for 3 ingots per ore, with just the 120 eu/t ebf.

Gallium is a little more painful early on. Maybe the chance of tiny gallium from sphalerite electrolysis could be increased a bit to compensate.

**Comment by Scottishprog** [comment]
I really don't have an exact opinion on the final solution... just asking for that sort of thing to be considered...

**Comment by Teirdalin** [comment]
I thought the general idea here was to allow exp cells to work the same as buckets.
Liquid xp would be fairly useless if its crafts were removed.

**Comment by 0lafe** [comment]
>Right now, I see XP crafting as a safety valve for GaAs etc.
If you want to eliminate the mechanic, please find a replacement safety valve.

I disagree that we need gallium from xp or an equivilant. I've found the gallium from sphalerite to be enough up til now (EV) and now with bauxite I'm set pretty much. 

>Liquid xp would be near-useless if its crafts were removed; without any new mechanic for it added- save from being used as, you know, liquid xp.

Other than the thing it's used for normally. Mhmm. I'd love if it had some uses that made sense, like making mob drops. If it can do a lot, with the right EU/t tiering and such, it could be a chlorine source, and replace some needs for having mob farms. Which I'm more than in favor of with how annoying farms are with infernals. 

>the final solution

Your mean eliminating the race of overpowered stuff in gtnh?

**Comment by Scottishprog** [comment]
I was referring to _how_ one compensated for the removal of XP crafting.  I am not pushing for a specific set of replacements, only that those replacements are put in place.

I too like the use of XP as a partial mob replacement.  Perhaps have a means of synthesizing from scratch (plus tons of power) as a late game option?  "Yay! I reached Tier X, I can spend Tier X- Y tier amount of energy every tick, and lose the mob farms altogether!"

To encourage eventual abandonment of mob farms. Mobs are very expensive in the terms of CPU time.

**Comment by 0lafe** [comment]
>I was referring to how one compensated for the removal of XP crafting. I am not pushing for a specific set of replacements, only that those replacements are put in place.

Right, I'm about like 95% on the side of "none of these need to be replaced because they shouldn't have existed in the first place" we already got free most things in some way, xp is a boring way to do it with crafting, but I don't think it should make stuff anyway. I like it being a mob thing, I think it's weird to make it a tech thing (iron, gold, gallium, etc...)

**Comment by Teirdalin** [comment]
> > Right now, I see XP crafting as a safety valve for GaAs etc.
> > If you want to eliminate the mechanic, please find a replacement safety valve.
> 
> I disagree that we need gallium from xp or an equivilant. I've found the gallium from sphalerite to be enough up til now (EV) and now with bauxite I'm set pretty much.
> 
> > Liquid xp would be near-useless if its crafts were removed; without any new mechanic for it added- save from being used as, you know, liquid xp.
> 
> Other than the thing it's used for normally. Mhmm. I'd love if it had some uses that made sense, like making mob drops. If it can do a lot, with the right EU/t tiering and such, it could be a chlorine source, and replace some needs for having mob farms. Which I'm more than in favor of with how annoying farms are with infernals.
> 
> > the final solution
> 
> Your mean eliminating the race of overpowered stuff in gtnh?

I feel as if liquid xp would make a bit more sense with the mob loot recipes than thaumium for the bees mob fragments; although too easy to get in contrast to thaumium.

**Comment by 0lafe** [comment]
Idk why those are all thaumium. Some make sense, but there's no reason not to use void or ichor on some

**Comment by Teirdalin** [comment]
Personally I find just killing mobs gives pretty decent loot instead of melting down my metals for it.  lol
Anywho, my above suggestions were essentially making mob drops out of liquid xp. :p  "turning blaze powder to blade rods" "turning ender pearls to ender eyes with HV power".  lol

**Comment by 0lafe** [comment]
I like all of that, I'm just also in favor of not bringing any of the current dust recipes to the fluidxp crafting party

**Comment by Teirdalin** [comment]
> I like all of that, I'm just also in favor of not bringing any of the current dust recipes to the fluidxp crafting party

The current dust recipes could fit in with an earth essence liquid mixed with something else.  It'd basically be like an experience alchemy.

**Comment by Dream-Master** [comment]
did we reopen this issue?

**Comment by richardhendricks** [comment]
I think there are enough ways to get gallium early game
Sphalerite dust - 72 Sphalerite dust ~ 1 gallium (RNGesus)
Gallium comb from Zinc drones - Not that hard to get, drop rate isn't great but if you let them run continuously easy to get enough to pass LV.
Impure zinc - available from small ores - 9 zinc impure/purified == 1 dust (guaranteed) in LV centrifuge
Crushed/Purified zinc - available from small ores - 9 zinc crushed/purified == 1 dust (guaranteed) in LV Thermal Centrifuge

If you get Galvania from IC2 crops, you can take 1 crushed zinc or sphalerite and turn it into 4 purified for the Thermal Centrifuge.

Finding ores now is super easy, and convenient. With the orewand and seismic/hand prospector players should be able to find any ore they need without spending too much time (> 2 hours IMO).

The XP buckets + the super cheap XP berries now make it trivial to skip the nether completely for any gallium, which is not what it was intended to do IMO.  I would rather the XP buckets give the Galvania leaves (1 or 9 depending on how generous you are feeling) - that would allow players to expand their current resource instead of completely bypassing it, and would require additional processing in a chemical reactor.

I dunno,  I do know some players like setting up infinite supply farms, but doing all that via one single pathway feels wrong.

**Comment by richardhendricks** [comment]
This is all off-topic, I'll open a new issue to discuss XP buckets rebalancing.

**Comment by richardhendricks** [comment]
XP bucket rebalance opened in #3783
