### ISSUE TITLE
Thaumcraft Warp Explanation in Questline

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3777]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Tried to put on my wizard cap and robe and be the master of all.
#
#### What happend instead? (Attach screenshots if needed)
Ended up with bats and scrambled chests.
#
#### What do you suggest instead/what changes do you propose?
Moronwmachinegun suggested I add this as an issue for quest updates. This was my statement in Discord:

I dunno at first I didn't like it but I do now. However, the first time I did TC in this pack I didn't understand warp...like temporary, permanent, etc. If anything maybe adjusting some of the quests to explain stuff as you go. Trading "warp" for powerful magic/tech I'm ok with. My first time playing this pack though I researched everything...got bad warp...didn't know what to do.

Mainly I didn't know that magic had the tradeoff as warp. Obviously there are "responsible" ways to research Thaumcraft to get stuff you need in a way the effects are manageable but my first time playing through that part of the pack I was like "ohh, look at all this research I can just sit around and do". Followed by me actually researching everything and then going to the Discord after to find out how very wrong I was.

**Comment by Dream-Master** [comment]
In the Thaumcraft Book is a Warp Warning Page. I could add this to the Quest book as well. @shawnbyday

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47609089-c0a71800-da38-11e8-9811-4007f6e4e66e.png)
![image](https://user-images.githubusercontent.com/2970688/47609091-c43a9f00-da38-11e8-9c0b-81f42e526ae5.png)
![image](https://user-images.githubusercontent.com/2970688/47609094-c866bc80-da38-11e8-9da3-42653467053e.png)

![image](https://user-images.githubusercontent.com/2970688/47609094-c866bc80-da38-11e8-9da3-42653467053e.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47609219-05cc4980-da3b-11e8-8194-9a9cbadf5909.png)
![image](https://user-images.githubusercontent.com/2970688/47609240-665b8680-da3b-11e8-9412-afda999c5ee6.png)

**Comment by shawnbyday** [comment]
Yea I think it is good to have it in the quest because it is easy to get carried away with going page by page researching stuff not knowing about warp. Then some people miss the second page of tabs all together. Thanks for the fix :D
