### ISSUE TITLE
Quest ID 938: Automated Sticky Resin Farmer Not Completing

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3780]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I made the electric treetap and expected the quest to complete.
#
#### What happend instead? (Attach screenshots if needed)
The quest did not complete.
#
#### What do you suggest instead/what changes do you propose?
Figure out what is causing the quest to not detect the completed item. I tried it charged and uncharged and charged with 1/27 durability and nothing.

**Comment by Dream-Master** [comment]
let it open after update
