### ISSUE TITLE
Recommendation: Move Quest ID 52

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3782]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Can make glass a lot sooner than quest guides you to.
#
#### What happend instead? (Attach screenshots if needed)
Made some glass.
#
#### What do you suggest instead/what changes do you propose?
Maybe move the glass quest somewhere off quest ID 44?

**Comment by Dream-Master** [comment]
yes you can make it earlier but the glass quest is a main quest you need it for a machine. I vote for let it like it is.
