### ISSUE TITLE
Bit silly suggestion:  Alkali metal explosions in water.  Also recipe change suggestion for sodium + water.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3785]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you suggest?
So alkali metal and water is a pretty common and fun basic reaction, for example tossing sodium into water-   https://youtu.be/NTFBXJ3Zd_4?t=50    so my suggestion is to add some reactions between alkali metals and being dropped into water or mixed with water in various machines.

Looking at a bit of the recipes, I think the sodium dust and water recipes should not make mineral water and sodium hydroxide but rather go by sodium chloride first I believe.  I may be wrong though; but I'm fairly sure if you go straight to stirring up sodium into water in a chem bath- I don't think your machines will appreciate it very much.

**Comment by richardhendricks** [comment]
Sodium is a very common output from the electrolyzer.  While adding water and getting NaOH isn't "realistic" it is sensible in-game as a sink for the massive quantities we get.

**Comment by Teirdalin** [comment]
> Sodium is a very common output from the electrolyzer. While adding water and getting NaOH isn't "realistic" it is sensible in-game as a sink for the massive quantities we get.

We could made Sodium Chloride a lot more common.   "it is found naturally in large amounts in sea water or in underground deposits. It is often obtained either by evaporating sea water or by mining underground deposits"    and then work with that primarily, and find some other uses for pure sodium.

Although I guess it does work fine as it is without disturbing everything, just feels a bit odd that we can mix the two.  lol

**Comment by Teirdalin** [comment]
I don't suppose we really need it.  lol
