### ISSUE TITLE
Suggestion: Infinity Singularity

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3788]
#### Which modpack version are you using?
2.0.5.1
#
#### Well,  why?

Just feels a little odd leaving infinity out of the singularity party, so my suggestion is for an infinity singularity to be a thing.

**Comment by 0lafe** [comment]
Seems weird we have them at all considering they're not really used, only for some poorly made late game recipes. The focus of this pack doesn't seem to be massive resource generation either so I don't really get their place. You can make all of them fairly easily, but they're like the 1 thing that really needs quarries

**Comment by Teirdalin** [comment]
> Seems weird we have them at all considering they're not really used, only for some poorly made late game recipes. The focus of this pack doesn't seem to be massive resource generation either so I don't really get their place. You can make all of them fairly easily, but they're like the 1 thing that really needs quarries

It is kinda weird.  lol

**Comment by Cinobi** [comment]
Infinity is made of singularities itself, so adding infinity singularity will collapse the universe xD
