### ISSUE TITLE
Question: Why is Scummy Bee so-  weird to breed?   Suggestion:  Make Tipsy Bee able to be bred once a month instead of once a year.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3789]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you mean weird?
So I'm trying to make the scummy bee so I can make grog for the nanomachines;  and-  I figured scummy needs to be made in the mutatron because there's no normal breeding recipe for it for some unusual reason. So I made the Agrarian Princess and an Exotic Drone but it's not mutating together; can't even place them together in the mutatron.    Are scummy bees just plain disabled or do I actually need to setup the mutatron to the requirements on the bee in order to mutatron it~
![mead](https://user-images.githubusercontent.com/37776581/47534837-aec54980-d86d-11e8-95dd-58af51fad06f.PNG)

What is this, I don't even.

The other option to make grog is to use the tipsy bee in making scummy and it has-

![tipsy](https://user-images.githubusercontent.com/37776581/47535053-930e7300-d86e-11e8-9e9a-21111e6e3653.PNG)

..  Really?..  _Really?_ 

*looks at calendar* 

Maybe we could set Tipsy to be craftable every month perhaps as it's required for scummy which is required for grog?

Ohhh I see, we can bucket mead and pour it onto the ocean and setup the mutatron and a power source atop of it.  I suppose that makes sense.    If we actually had ocean biomes.

This still seems a bit-  excessive though don't you think?     I guess it can work as a progression lock if that is the idea- quite madness though;  why not just use an advanced tech part instead of making weird hoops to jump through making the most simple part of it?  lol

Considering the bees didn't even go into the mutatron to begin with I'm not entirely sure they'd even go in if I put the mutatron in an ocean of hot mead.    Anyone know for sure if it would work?

**Comment by Teirdalin** [comment]
Actually I guess it's not that big of a deal; I suppose it's a progression related lock of some sort probably put in place for good reason.    Just feels weird for time based locks.

**Comment by 0lafe** [comment]
Can we also remove the one for the Easter egg one? It's super useful for stemcells because it gives the best % for eggs but is locked to Easter times.

**Comment by boubou19** [comment]
with gendustry and its advanced mutatron you can unlock them so no need to change anything

**Comment by Teirdalin** [comment]
> with gendustry and its advanced mutatron you can unlock them so no need to change anything

Haven't tested on Easter Bee, but definitely doesn't work on Tipsy, and also most certainly isn't working on Scummy.   https://github.com/GTNewHorizons/NewHorizons/issues/3791

**Comment by Teirdalin** [comment]
Can confirm:  Advanced Mutatron to get Tipsy is a lie.
![lies](https://user-images.githubusercontent.com/37776581/47583044-12ea1b00-d90b-11e8-8591-21e25b75750f.PNG)

**Comment by boubou19** [comment]
weird i can tell you i got mine this way on official server

**Comment by Vexatos** [comment]
The bees are more of a joke in Computronics and not meant to be the only way to craft Grog; the normal recipe for Grog has been disabled in the pack but there should definitely be an alternative way. Indeed, I made it so that the mutatron does actually require all normal conditions to be met to produce this mutation because I don't like cheating :wink:. The bees are supposed to be annoying to get, but they should definitely work. You can also produce the mutation in any normal apiary, NEI just won't show the mutations because they are technically secret.

**Comment by Teirdalin** [comment]
> The bees are more of a joke in Computronics and not meant to be the only way to craft Grog; the normal recipe for Grog has been disabled in the pack but there should definitely be an alternative way. Indeed, I made it so that the mutatron does actually require all normal conditions to be met to produce this mutation because I don't like cheating 😉. The bees are supposed to be annoying to get, but they should definitely work. You can also produce the mutation in any normal apiary, NEI just won't show the mutations because they are technically secret.

Any biome suggestion?  Was using the tropics which is-
114,Tropics,1.2,1.0,0.1,0.2,0.3,"WET, JUNGLE, LUSH, OCEAN, RIVER, BEACH",biomesoplenty.common.biome.overworld.sub.BiomeGenTropics

and it wasn't breeding.

**Comment by Vexatos** [comment]
It has to be WARM as well.

**Comment by Teirdalin** [comment]
> It has to be HOT as well.

The apiary said it's hot,  although the biome data doesn't.   I'll try the rwg_oceanOasis as that has both tags.  Didn't take tag data into consideration when I was testing initially before.

**Comment by Dream-Master** [comment]
wont be change tipsy bee. We have a recipe for grog now

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47608317-f5f93900-da2b-11e8-973b-2de86213a88c.png)

**Comment by Teirdalin** [comment]
![biome2](https://user-images.githubusercontent.com/37776581/47609098-5f0d8c00-d9ed-11e8-89ab-b41b2bc54f0f.PNG)
![biome](https://user-images.githubusercontent.com/37776581/47609100-5f0d8c00-d9ed-11e8-8074-faa138c4e0f4.PNG)
![climate](https://user-images.githubusercontent.com/37776581/47609101-5fa62280-d9ed-11e8-9481-e3ba9508e4e6.PNG)
![setup](https://user-images.githubusercontent.com/37776581/47609102-5fa62280-d9ed-11e8-9123-bf117d048c2f.PNG)
![attempt](https://user-images.githubusercontent.com/37776581/47609103-5fa62280-d9ed-11e8-94a7-2a5a76c27173.PNG)

https://www.youtube.com/watch?v=c46PtsI06jY

**Comment by Vexatos** [comment]
Who knows, the mutatron might just not like it.

**Comment by Teirdalin** [comment]
> Who knows, the mutatron might just not like it.

Maybe,  bred a strain of exotic bees which were okay with the night, and attempted 10 times with three mutagenic frames each try in an apiary under same conditions-

![night](https://user-images.githubusercontent.com/37776581/47609361-cc232080-d9f1-11e8-906d-20147fb96a3a.png)
![setup](https://user-images.githubusercontent.com/37776581/47609362-ccbbb700-d9f1-11e8-82e3-553c9ac7fa92.PNG)

And the result- 
![result](https://user-images.githubusercontent.com/37776581/47609379-1c9a7e00-d9f2-11e8-910a-c89653dbac7f.PNG)

Gotten some of the rocky bees that I bred into the exotics for the nocturnal back.  lol

**Comment by Teirdalin** [comment]
Well I suppose it doesn't matter much if scummy bee is broken,  grog recipe is changing next update anyways.
