### ISSUE TITLE
BC Builders

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#379]
Could we get recipes for some of the items:
- Filler
- Builder
- Architect Table
- Electronic Librar
- Construction Mark
- Template
- Blueprint

They are just to help out in building. Useful for creating multiple identical objects or for moving structures

**Comment by Dream-Master** [comment]
- [ ] Filler
- [ ] Builder
- [ ] Architect Table
- [ ] Electronic Librar
- [ ] Construction Mark
- [ ] Template
- [ ] Blueprint

**Comment by Drobac** [comment]
id put filler,construction mark and template in  the MV range (aluminium) and Builder, Architect table, El. Library and blue print in HV

**Comment by Drobac** [comment]
Filler - MV machine hull, 4 alu gears, 2 MV Robot arms, apropriate cirucuit and some steel plates
Constuction mark - Redstone torch + blue lumar?
Template - Paper in the assember with some circuit maybe

**Comment by Dream-Master** [comment]
Done

**Comment by Drobac** [comment]
Can you add recipes for Land Mark and Path Mark
- Land Mark - Construction mark + lapis
- Path Mark - Construction mark + Green dye

**Comment by Dream-Master** [comment]
Adding already in dev.
