### ISSUE TITLE
Texture of pipe not change when setting "Input disable".

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3790]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Single and My private server
#
#### What did you try to do, and what did you expect to happen?
Setting Pipe of GT++ alloy's to "Input disable" by Wrench Shift+Right click.
#
#### What happend instead? (Attach screenshots if needed)
Texture of the pipe not change,
![2018-10-26_13 46 55](https://user-images.githubusercontent.com/40425798/47545533-ce20ad00-d927-11e8-8c87-aaec905c525e.png)
#
#### What do you suggest instead/what changes do you propose?
fix it.

**Comment by Dream-Master** [comment]
its a gt++ issue please report on gt++ side. @yukieiji

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues

**Comment by richardhendricks** [comment]
GT++ will not change.

**Comment by draknyte1** [comment]
Can’t support this due to backwards compatibility. It’s visual, so not really a bug..
