### ISSUE TITLE
❕ Bug: Scummy Bee Mutation Broken.   Impossible to get Nanomachines.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3791]
#### Which modpack version are you using?
2.0.5.1 
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Made a rwg_oceanHot biome via rite of shifting seasons with full coven.
Made a bucket of short mead.
Placed short mead.
Placed a mutatron above it.
Connected power, and fueled it with mutagen and genetics labware.
Made it night.
Tried to place Agrarian Princess and Exotic Drone in it.

![broken bee](https://user-images.githubusercontent.com/37776581/47548808-ef918280-d8ae-11e8-9636-bbb498c5c9a4.PNG)
![mead](https://user-images.githubusercontent.com/37776581/47548809-f02a1900-d8ae-11e8-8570-5ca7268930fc.PNG)

#
#### What happend instead? (Attach screenshots if needed)
![cannot](https://user-images.githubusercontent.com/37776581/47548854-12bc3200-d8af-11e8-94ec-5b2abd1518f4.PNG)

Wasn't able to place it. 

Attempted with a normal vanilla ocean biome as well after-  still nothing.

Noticing both Hot Ocean and Normal Ocean are Normal temperature-

Attempted in tropics which is Hot temperature and an ocean.  Still nothing.

![set](https://user-images.githubusercontent.com/37776581/47550773-1eaaf280-d8b5-11e8-82f4-9d56ca48880f.PNG)

Even made an advanced mutatron to see if that'd work.

![nope](https://user-images.githubusercontent.com/37776581/47583102-4036c900-d90b-11e8-825e-5616461cdb5d.PNG)

#
#### What do you suggest instead/what changes do you propose?
Fix recipe; it's necessary to make Grog.

**Comment by Dream-Master** [comment]
Will add a second recipe for grog but bees must work too. I ask Vexatos the Mod dev. @Teirdalin

**Comment by Dream-Master** [comment]
@Teirdalin try a bit mre with bees and next update use the recipes

**Comment by Dream-Master** [comment]
i Close it after the next release

**Comment by Teirdalin** [comment]
Oh okay.
