### ISSUE TITLE
Koboldite from Witchery

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#3792]
#### Which modpack version are you using?
Live version
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
"Vanilla" forstry mechannic of getting koboldite seams broken. 
Here is how it should work:
- use lead on hobgoblin
- give him pickaxe
- wait till he mining stone, ores and so and wait till koboltide durst dropped.

Here is my setup:
![default](https://user-images.githubusercontent.com/25028786/47561282-8b5cd600-d923-11e8-8493-dbb55426aab5.png) based on https://www.reddit.com/r/feedthebeast/comments/4ydj3n/my_efficient_koboldite_dust_farm_witcheryinfinity/ this guide. Hobgoblins works more than 20 hours so far, no single koboldite dust.

Suggestion: This dust\ingot\nugget is needed for some witchery craft, same as spawning two of witchery bosses(Mog and Gulg), so we need a way to obtain it. If u can't fix the "vanilla" mechanic, some kind of thaumcraft infusion maybe? 
![default](https://user-images.githubusercontent.com/25028786/47561556-46856f00-d924-11e8-8345-e3228d4ad722.png)
somethin like this, +32 ordo, 32 perdoto 16 permutato and 16 praecantatio, giving u 10 koboldite nuggets.

**Comment by Dream-Master** [comment]
any idea why the kobolts not working ?
Dont like the idea make a Thaumcraft recipes .

**Comment by Teirdalin** [comment]
I've seen some people get koboldite over on Prospercraft;  personally I treid it once on stones and it didn't give me much although was a bit of fun having an army of kobald slaves.   I'd ask the person what they used their kobalds on but they quite a while back.    Will test on some dirt in a minute to see if they gather it fine from that.

**Comment by repo-alt** [comment]
Kobolds work fine on vanilla iron ore from TF

**Comment by repo-alt** [comment]
Can be placed.

**Comment by draknyte1** [comment]
Koboldite obtainment works 100% in a Pure Forge setup. (Explains SSP working for Dream)
I've obtained it as per usual at some point between 20.2.7 and 2.0.4.6, no issue.

I recall testing this for Cinobi ages ago.

**Comment by yukieiji** [comment]
It didn't work for a few days on my server, but it probably works fine after server reboot.
Hobgoblin is digging stones and vanilla ore placed in Golem in my server.
![2019-06-04_22 51 20](https://user-images.githubusercontent.com/40425798/58884426-5b787b00-871b-11e9-82b3-09f8aceddc77.png)
