### ISSUE TITLE
Minor Suggestion: Replace pressure plate in BiblioCraft seats with wool slab.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3793]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you suggest instead/what changes do you propose?
With the changed recipe for pressure plates to take a large spring, and screws; just feels a bit unfitting for a wooden chair seat.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/47606204-e7515880-da10-11e8-8017-ea679377d1f4.png)

**Comment by Teirdalin** [comment]
Huzzah for the power of chairs!
