### ISSUE TITLE
Ores in NEI, suggestion

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3795]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?Look up where to find in NEI where to finde a specific ore
![image](https://user-images.githubusercontent.com/25811344/47589574-d7cb0480-d969-11e8-9c56-e2574a0efd54.png)
Ilove this, but i find it hard to remember all Dimension Code names and also what tier they are in.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Instead of having 1 page for every type of spawn it has(certus quarts have 3 pages) nether,Planets and Deep dark.) i would sugest 1 page for every dimension stating the whole planet name and what tier rocket you need (if a rocket is needed), 

for as it is now i rather use the old not updated spreadsheet and risking getting outdated info rather then going back an forth between NEI and the questlog checking all Dimension codes and where i can go.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
wontfix. There is the oppertunity to [generate a up-to-date spreadsheet](https://gtnh.miraheze.org/wiki/GT-NEI-Ore-Plugin_Spreadsheet_Export_Tutorial) in the mod, but i wont recode the whole mod for this.

**Comment by DoomSquirter** [comment]
wasn't there talk about making the nei box where it prints names bigger already?  make more meaningful abbreviations?
