### ISSUE TITLE
Hologram Projector (Tier 2) Recipe Broken

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3796]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft a Tier 2 Hologram Projector in an Advanced Assembling Machine III using 
2* Advanced Circuit Boards
2* Microchip (Tier 3)
2* Polyethylene Sheets
2* Cables
4* Obsidian Plates
1* Emerald Lens
Plenty of Molten Polyethylene
#
#### What happend instead? (Attach screenshots if needed)
It would not craft.
![projector fail 2](https://user-images.githubusercontent.com/37776581/47597930-8a3e9f80-d949-11e8-9bd7-b33ebc5a3488.PNG)
![projector fail](https://user-images.githubusercontent.com/37776581/47597932-8e6abd00-d949-11e8-800d-3a425fc7c1de.PNG)
![projfail3](https://user-images.githubusercontent.com/37776581/47597938-ab06f500-d949-11e8-9d85-90079f3ebe88.PNG)

#
#### What do you suggest instead/what changes do you propose?

Fix recipe.

**Comment by Dream-Master** [comment]
added 9 input slot assembler. Should work now.
