### ISSUE TITLE
Hologram Projector (Tier 1) Recipe Broken

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3797]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft a Tier 1 Hologram Projector in an Advanced Assembling Machine III using 
2* Plastic Circuit Boards
2* Microchip (Tier 2)
2* Polyethylene Sheets
2* Cables
2* Obsidian Plates
1* Diamond Lens
Plenty of Molten Polyethylene
#
#### What happend instead? (Attach screenshots if needed)
It would not craft.
![hologram projector 1 fail](https://user-images.githubusercontent.com/37776581/47598069-8ca1f900-d94b-11e8-99ba-d41fb53da43e.PNG)
![hologram 1 fail](https://user-images.githubusercontent.com/37776581/47598070-8ca1f900-d94b-11e8-86f5-de19340ec0a3.PNG)

#
#### What do you suggest instead/what changes do you propose?

Fix recipe.

**Comment by Dream-Master** [comment]
the recipe is longer than 6 input slots

**Comment by Dream-Master** [comment]
added 9 input slot assembler. Should work now.
