### ISSUE TITLE
Thaumic Horizons Suggestion: Ink Squid

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3800]
#### Which modpack version are you using?
2.0.5.1
#
#### Ink squid you say? 
So my suggestion is to expand the thaumic horizons mutatable animals a bit with squids.    
Ink squid mutation would be made with six of a certain colored dye, 16 Precantatio, 16 Ordo, 16 Invidia, 24 Fabrico.

Ink squids could have a color overlay of the type of dye used in creating them, and produce a single dye every once in a while depending on the color; similar to how the golden egg chicken produces golden eggs except with dye.

Would make for an interesting aquarium pet while helping paint the carpets.

**Comment by DoomSquirter** [comment]
thaum bases has a dye plant. seems redundant.

p.s. do you get paid by the issue?  /s

**Comment by Teirdalin** [comment]
> thaum bases has a dye plant. seems redundant.
> 
> p.s. do you get paid by the issue? /s

Oh that's true,  and I wish.
