### ISSUE TITLE
Feature Suggestion: Trash Can (Safety)

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3801]
#### Which modpack version are you using?
2.0.5.1
#
#### We can trash if we want to, we can leave your friends behind. Cause your friends don't trash, and if they don't trash, well they're no friends of mine.

So my suggestion is a new type of trash can which which has 9 slots and a confirmation button to trash the item placed into its input slots to prevent people from accidentally shift clicking items into oblivion; especially if inventory desync happens on a server.   Recipe could be a trash can and button in an assembler.

**Comment by Bryfer** [comment]
Personally I went with the void chest from railcraft instead because of this
the void chest voids stuff alot slower, but if you throw wrong things inside it you have time to extract them to safety dance

**Comment by 0lafe** [comment]
Or make your own with a level or button and a chest that feeds into a trashcan. I used to use mine with a pressure place so it added to the realism lol

**Comment by richardhendricks** [comment]
Yeah I use a chest -> hopper w/lever -> trashcan for me.  I do like the idea of a pressure plate, but the logic is the wrong way and would need to be pulse-extended. :D

**Comment by richardhendricks** [comment]
A GT/GT++ trashcan does sound nice though.  Isn't there some tech-magic scrap or something?

**Comment by Teirdalin** [comment]
Personally I've been using a normal trashcan till one day I was up all night and accidentally destroyed all my foci, like three projects worth of items, my golem collection, and my awakened ichorium set by accidentally clicking the trash when I thought I opened a bag and shift clicking.   lol

**Comment by DoomSquirter** [comment]
sorry but that sounds a hella lot like user error and only recourse is big life lessons and lots of contemplation of what you have done.  lol

now, considering I have done similar things but not so much exactly that, if you don't feel safe throwing things into a trash can, you are far better served having a chest->conduit->trash with a lever to enable/disable it as a sort of training wheels/playing while sleeping mode.  

also, if you use ftbutils, there is a trash icon that doesn't delete the stf till you exit the screen iirc.

**Comment by DoomSquirter** [comment]
might as well then start putting training wheels on everything.  safety proofing lava pools, etc....

**Comment by 0lafe** [comment]
things like making multis turn off if their outputs are full ^

**Comment by Teirdalin** [comment]
True, it's a slippery slope.  If we add a destroy button it may kill the modpack as a whole over time.
