### ISSUE TITLE
Wrong Iron Caps is used for the Iron Capped Greatwood Wand. Quest #798

### ISSUE THREAD

**Issue by Flameis** [GTNewHorizons/NewHorizons#3802]
Which modpack version are you using?
2.0.5.1

If in multiplayer; On which server does this happen? 
N/A

What did you try to do, and what did you expect to happen?
I tried to use the New Horizons Iron Wand Cap to make the Iron Capped Greatwood Wand but it would not work even though those caps are specified in the previous half of the quest.

What happened instead? (Attach screenshots if needed)
The workbench would not accept the specified wand caps and would only accept the Thaumcraft ones.
![2018-10-28_14 27 20](https://user-images.githubusercontent.com/40249557/47622073-c0049500-dabd-11e8-810e-b216b7ec33f8.png)
![2018-10-28_14 27 31](https://user-images.githubusercontent.com/40249557/47622074-c1ce5880-dabd-11e8-91ca-011d363fb921.png)
![2018-10-28_14 27 47](https://user-images.githubusercontent.com/40249557/47622075-c266ef00-dabd-11e8-9b3a-33bf44285eee.png)

What do you suggest instead/what changes do you propose?
I suggest changing the item recipe to fit the quest.

**Comment by Dream-Master** [comment]
will check. Btw core mod item caps are disabled so far I know.

**Comment by Flameis** [comment]
The caps are not able to be made but the quest calls for them. I cheated the other ones in first because I couldn't find the recipe because they were disabled.

**Comment by shawnbyday** [comment]
This is sort of related to the issue I submitted a few days ago. https://github.com/GTNewHorizons/NewHorizons/issues/3763 I thought in my game I was able to craft the Thaumcraft ones though. I didn't cheat them in as far as I recall. I will look at that when I get home tonight.
