### ISSUE TITLE
Suggestion: Tiny essentia values for GenDustry metal combs.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3803]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you suggest?
Doesn't really need to be much, maybe like 1 aspect depending on the ore the comb is based on; as an alternative use than processing them to metal.

**Comment by Dream-Master** [comment]
Gendustry combs will be removed the next release after, We move to gt combs first and one update later we will remove them or remove the recipes

**Comment by Teirdalin** [comment]
Interesting,
