### ISSUE TITLE
Server crash when using Lumber Axe with BC robot.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3806]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
My private server and single
#
#### What did you try to do, and what did you expect to happen?
Cutting Tree with BC robot using Lumber Axe.
#
#### What happend instead? (Attach screenshots if needed)
Server crashed and Could not login to the world.
Crash report:[crash-2018-11-01_03.26.48-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2535880/crash-2018-11-01_03.26.48-server.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

It worked well when I tried with TConstruct - 1.7.10 - 1.8.8 and BC7.1.20(Not GTNH).

**Comment by Teirdalin** [comment]
Curious if other things such as a break core golem, dynamism tablet, use core golem, and OC computer robots have similar issues with the lumber axe.

**Comment by mitchej123** [comment]
Will take a look when I'm back from vacation - middle of November

**Comment by Dream-Master** [comment]
ok
