### ISSUE TITLE
Quest Text Enhancement: Quest ID 75 The Water Dilema

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3809]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private server (N/A)
#

#### What do you suggest instead/what changes do you propose?
Just add some text to the quest to explain the water tanks need exposure to the sky to work efficiently. If this is ok I can get it added and do a pull request.

**Comment by Dream-Master** [comment]
i add text for it allready.
