### ISSUE TITLE
Smeltery cannot make steel ingot

### ISSUE THREAD

**Issue by mtjohnson47** [GTNewHorizons/NewHorizons#3812]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Pour molten steel into an ingot cast.  Expected it to pour
#
#### What happend instead? (Attach screenshots if needed)
nothing
#
#### What do you suggest instead/what changes do you propose?
Add a recipe for pouring out steel ingots.

**Comment by shawnbyday** [comment]
@mtjohnson47 pretty sure this is intended so that you have to use GT processing to make steel. Whether it is the Bricked Blast Furnace or Electronic Blast Furnace. I remember asking about this before a long time ago. It does pose the issue of if you put steel in you have to either use it or destroy it which isn't clear until you try it.

**Comment by Dream-Master** [comment]
maybe i add recipe to make back iron ingots or so but ofc no steel ingots. This will break blance

**Comment by mtjohnson47** [comment]
Why would it?  You can't make steel in the smeltery, you still have to make it using the railcraft methods.  Why should it be treated differently than any other ingot?

**Comment by sthegreat** [comment]
It's because steel dust -> steel ingot is supposed to need an EBF, similar to how molten aluminium can't be cast into ingots because that needs an EBF to smelt.

**Comment by bartimaeusnek** [comment]
@sthegreat i dont see the point, since steel dust is obtained by macerating steel.... im in favor of making steel pourable

**Comment by draknyte1** [comment]
> lemme just melt down all this steel mob armour from my grinder for free steel

I don’t think so Bart.
At least, add a new ingot mold for higher tier materials. (Allow pouring Alu and Steel but require HV)

**Comment by Dream-Master** [comment]
High tier mold maybe better but not sure if we can balancing it right. 80 secs in EBf for Alu is a long time. Put oxygen to alu will not work in rl.
Ok steel will work but at a higher temperature i guess.

**Comment by bartimaeusnek** [comment]
@draknyte1 you can alloy-smelt that. also you need a macerator, which you have once you have the alloy smelter... still dont see the point

**Comment by Dream-Master** [comment]
Ok you cant smelt dust inside it so i guess it is ok to enable steel ingots. Nuggets still available.
