### ISSUE TITLE
Awesome Mod Suggestion: OpenGlasses

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3814]
#### Which modpack version are you using?
2.0.5.1
#
#### OpenGlasses, what does it do?

So I was always wondering if such a mod existed for opencomputers as it seems like something that should exist; and I saw this floating about the internet.

https://minecraft.curseforge.com/projects/openglasses

![0dae77fa683bde0a44bfe27a611c6214](https://user-images.githubusercontent.com/37776581/47937097-edc25300-de9c-11e8-96e5-d8e7ab3e55a2.png)

When wearing the glasses it allows openComputers to write data via the wireless network I believe to your glasses allowing data to be displayed on the HUB as well as other information and even objects.

**Comment by YinScape** [comment]
The pack does have Terminal Glasses though.

**Comment by Teirdalin** [comment]
> The pack does have Terminal Glasses though.

Ah I knew we had something.   Well then; openglasses could be a higher tier terminal glasses then as it has more features such as allowing computers to render things only to people wearing them instead of just being a terminal.
