### ISSUE TITLE
Non-Compatible Mod:  OpenPeripherals

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/NewHorizons#3815]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Write absolutely anything to my GUI using a T3 computer, an adapter, a terminal glasses bridge, and terminal glasses.

It to just work, a letter, a line, a square;  anything.
#
#### What happend instead? (Attach screenshots if needed)
Lots of errors.

Looked it up and it appears it requires a ComputerCraft computer to to even use.
https://github.com/OpenMods/OpenPeripheral/issues/182

> So actually it's absolutely impossible to use OpenPeripherals from OC.
#
#### What do you suggest instead/what changes do you propose?
Removal of the mod, and for all things from it to be burnt in an everlasting fire for all eternity.

Suggested an alternative over on https://github.com/GTNewHorizons/NewHorizons/issues/3814  which is built around OpenComputers and should do even more than the terminal glasses do for ComputerCraft anyways; seems they developed it as an OC alternative from its description.

**Comment by repo-alt** [comment]
OP is originally a CC addon, so not everything there works with OC, but it had some value for a while because OC missed some adapters for other mods.
Now it does have a lot of built in integration and computronics adds some missing adapters, so I'd say OP is no longer needed in it's primary capacity. (And if the glasses don't work as you say, then in any capacity at all)

**Comment by Teirdalin** [comment]
Haven't actually looked into the addons or other parts; that OpenPeripherals uses, just the glasses; but it does seem like they designed it with CC's methods in mind so they in general should not work I believe.    Someone may know more about them than me though, as I just know that the glasses only give errors when attempting to give commands to them.
