### ISSUE TITLE
IC2 Equipment is Silent

### ISSUE THREAD

**Issue by Superlagg** [GTNewHorizons/NewHorizons#3816]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft.
#
#### What did you try to do, and what did you expect to happen?
I shot my mining laser, and expected it to make a cool 'pew pew' noise.
#
#### What happend instead? (Attach screenshots if needed)
Laser came out, but without any sound.

Nothing from IC2 seems to make the sounds they should. Nukers, jetpacks, that ore scanner thing, their beeps and whirrs and whatnot are missing.
#
#### What do you suggest instead/what changes do you propose?
Make them make the sounds they should make again. Somehow.

**Comment by Dream-Master** [comment]
Ic2 is close source mod so nothing i can do from my side.

**Comment by Dream-Master** [comment]
Support for 1.7.10 was dropped. I ask Aroma allready for changes but i guess we will never get a new update for 1.7.10.

**Comment by Superlagg** [comment]
> Support for 1.7.10 was dropped. I ask Aroma allready for changes but i guess we will never get a new update for 1.7.10.

Oh okay, thanks for trying!

**Comment by draknyte1** [comment]
IC2 sounds worked fine for me last time I checked... If they didn't, GT would have no sounds either (Since GT re-uses IC2's sounds)

**Comment by Dream-Master** [comment]
@Superlagg which machines you tested? @draknyte1 which machines works fine and make sounds from ic2?

**Comment by draknyte1** [comment]
Any GT sound is an IC2 sound.
Macerator is the best example~

**Comment by Dream-Master** [comment]
ok ic2 macerator is disabled but i test in creative later. @Superlagg which machine do you test an missing a sound ?

**Comment by Superlagg** [comment]
> 
> 
> ok ic2 macerator is disabled but i test in creative later. @Superlagg which machine do you test an missing a sound ?

The nuclear reactor, the mining laser, the jetpack, and the OV scanner.
