### ISSUE TITLE
Sulfuric Acid

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/NewHorizons#3822]
In regular gt5u you take hydrogen sulfide and turn it into sulfuric acid with just water. With the changes to that recipe, doing dioxide to trioxide to sulfuric acid. The h2s + water recipe should be removed to favor the other route. H2s to sulfur dioxide then trioxide then acid

**Comment by Highbeam** [comment]
http://processflowsheet.com/sulfuric-acid-generation-from-hydrogen-sulfide/

**Comment by Hakameda** [comment]
Even that would be good, compared to just adding water to h2s

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3728
