### ISSUE TITLE
typo in quest.

### ISSUE THREAD

**Issue by Kiefy** [GTNewHorizons/NewHorizons#3823]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
I tried to read a quest title. Expected perfect english.
#
#### What happend instead? (Attach screenshots if needed)
A freakin' typo!
![](https://i.imgur.com/WO7AyL1.png)
#
#### What do you suggest instead/what changes do you propose?
Fix the typo

**Comment by boubou19** [comment]
I don't think a typo deserves you the right to insult the work of many persons who make the pack on their free time. Please be respectful to them. thank you.

**Comment by richardhendricks** [comment]
I'm sorry Kiefy, but you must be

<--- this high

to ride this ride.  Maybe next year.

**Comment by Kiefy** [comment]
I was referencing a comment from Discord where someone suggested that it would be funny if an issue be posted with this specific title for something as silly as a typo in a quest title. :)

Also. I'm higher than you think. in more ways than one.

**Comment by richardhendricks** [comment]
Just remember to !moron once and a while.  I'll be back on Discord and GTNH soonish.

**Comment by Bluebine** [comment]
Well I, for one, enjoyed the joke.
Pretty sure I'm the one you're talking about, who mentioned using that title for something silly :P

**Comment by Dream-Master** [comment]
I remeber this issue too someone  using this title but i guess it is a joke in this case so nothing i have to complain about :)
