### ISSUE TITLE
Dying while connecting doesn't generate grave

### ISSUE THREAD

**Issue by Superlagg** [GTNewHorizons/NewHorizons#3824]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft.
#
#### What did you try to do, and what did you expect to happen?
My connection cut out while I was next to a blaze spawner. By the time I reconnected, my character was dead, and I respawned. When I went back to look for my grave, it wasn't anywhere around where I died. This happened again later, with the same results.

Might be important to note that I'm fairly certain I died somewhere between I pressed the connect button and when the game actually loaded. Also, some of my soulbound equipment respawned with me, but most of it didn't, such as my GC gear.

**Comment by draknyte1** [comment]
Within SMP, there’s a period where your EntityPlayerMP exists on the server but the client is loading/syncing. Iirc, one of the mods makes you invulnerable between initial player being placed in world and when you first move. So, this shouldn’t *ever* happen.

**Comment by Dream-Master** [comment]
I set it to 30 secs so you must be online before you get hit by mobs.

**Comment by Superlagg** [comment]
This modpack takes a while to load into the world, usually way more than 30 seconds. Would it be alright to increase this time to at least a few minutes, or have it last until a definite, Id-totally-have-to-be-connected-to-do-this action is done?

**Comment by richardhendricks** [comment]
Have you checked with Prospercraft staff to see if they can find a grave file for you character?

**Comment by Superlagg** [comment]
> Have you checked with Prospercraft staff to see if they can find a grave file for you character?

I've asked in the discord help channel about that, but they're firm on the policy that they don't replace lost items. I'll ask if the mod actually generated a grave file, though!

**Comment by Dream-Master** [comment]
its very easy to restore graves with ob_ivenentory restore "user" "file"
Thats it.
