### ISSUE TITLE
GTNH Roller Derby

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/NewHorizons#3825]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 
GTNH Roller Derby
#
#### What did you try to do, and what did you expect to happen?
Use carts for GTNH
#
#### What happend instead? (Attach screenshots if needed)
Carts disappear, become unlinked,  and reverse when bumped/rubber banded like when using locking tracks
#
#### What do you suggest instead/what changes do you propose?
It won't be fixed on RC side, They did suggest it's related to an erroring entity just being removed by the server. Any suggestions on narrowing down the exact cause so we could potentially fix it?

**Comment by Hakameda** [comment]
Trains can also split in half around a corner, stay linked but be unable to move

**Comment by Dream-Master** [comment]
hard to say without a log or a picture or anything else. RC code is open source but a part isnt. I am unable to make a own build of it.

**Comment by Hakameda** [comment]
I believe I asked before if it was possible for gtnh to use it's own build
at mitch's request. I believe they said it was okay. They don't plan to
update 1.7.10 at all

**Comment by Hakameda** [comment]
![screenshot_20181109-120315_discord](https://user-images.githubusercontent.com/1900223/48282687-96c9fa00-e417-11e8-933a-d5e96c1f1829.jpg)

**Comment by Dream-Master** [comment]
sure if anyone can fix it an pull it why not.

**Comment by Hakameda** [comment]
I'm not sure how to find a more exact error though, if somebody has ideas
on that
