### ISSUE TITLE
I can not do MT Core 

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/NewHorizons#3826]
#### Which modpack version are you using?
2.0.5.1

#### If in multiplayer; On which server does this happen? 
Epsilon

#### What did you try to do, and what did you expect to happen?
I wanted to make Molecular Transformer  where  applies MT Core

#### What happend instead? (Attach screenshots if needed)
Other ID Thick Neutron Reflector does not allow to do MT Core

**Comment by Dream-Master** [comment]
yes known issue

**Comment by Dream-Master** [comment]
will check asap
