### ISSUE TITLE
Rain Noise/Particles

### ISSUE THREAD

**Issue by XavierJenon** [GTNewHorizons/NewHorizons#3830]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Privately hosted server, no changes to files.
#
#### What did you try to do, and what did you expect to happen?
Enjoy the sound of minecraft rain while playing the game. I expected the rain noise/particles 
#
#### What happened instead? (Attach screenshots if needed)
No particles for rain hitting the ground, thus no rain noise.
#
#### What do you suggest instead/what changes do you propose?
I'd just like the info to re-enable my rain. I feel that most players prefer to not hear the rain.

I have tried changing the particle effect setting, but it does not change the rain issue.

**Comment by XavierJenon** [comment]
My testing reveals it to only happen in Dead Forest biomes.

This was tested in 4 biomes: Bog, Dead Forest, Redwood Forest, Prairie.

**Comment by bartimaeusnek** [comment]
there are some biomes that do not rain, like i.e. desert aswell

**Comment by XavierJenon** [comment]
To clarify, the dead forest biome DOES rain, however the rain-hit on blocks does not happen.

**Comment by XavierJenon** [comment]
Further tested in most RWG biomes. It appears that it may be specific to Dead Forests.
