### ISSUE TITLE
Fatigue Bug

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3832]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Made a Thaumium Grafter and added Repair II on it. Expected it to repair.
#
#### What happend instead? (Attach screenshots if needed)
I die just having the Thaumium Grafter on my character (unless it is in a bag) without even moving or doing anything. Healing axe can barely keep me alive. Not sure if it is something anyone can replicate or not. *Shrugs*
#
#### What do you suggest instead/what changes do you propose?
I don't even know if it is something that can be fixed that easily?

**Comment by DoomSquirter** [comment]
it's not a bug.  I take many stacks of food in a can with me when I go out hunting saplings.  the hunger mechanism is part of the whole process.  it is sorta a interaction cause of HO or SOL but it's still just needing to be fed QUICKLY lol

**Comment by DoomSquirter** [comment]
oh wow, shots fucking fired!  lol

seriously tho, that's how it works.

easy fix.  don't put repair 2 on the grafter and let it break on you and make another and you won't have the issue.
#FatLivesMatter

**Comment by richardhendricks** [comment]
GT Branch Cutter FTW

**Comment by shawnbyday** [comment]
Yea I just tossed it out. I'll go back to making the bronze ones for now or give the branch cutter a shot.

**Comment by richardhendricks** [comment]
The BC works great for Forestry trees.  I don't think it works for Silverwoods though.

**Comment by bartimaeusnek** [comment]
ill close this.
