### ISSUE TITLE
assembling line quest can't be completet in 2.0.6.0 

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3833]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
can't comlete assembling line quest you neet the a luv energy hach to comlete the quest but you neet the assembling line to make it

**Comment by Dream-Master** [comment]
oh you fast :P will change the quest that you can work with IV ones

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/50208149-1069d780-0336-11e9-9183-0739c7eef474.png)
