### ISSUE TITLE
normal rubber allowed in luv pump

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3834]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
normel rubber shoed not be allowd in anyting in iv and up

**Comment by Dream-Master** [comment]
it was suggested to use it but i can remove it.

**Comment by botn365** [comment]
wasent the sugestion to add styreen butadien rubber to it?

**Comment by Dream-Master** [comment]
any rubber but yes i can change it.
