### ISSUE TITLE
reduce the luv motor cost

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3836]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
the 40 minuts it takes to cook the osmiridium per luv motor is too long now with the fusion nerf it takes a hole 14 days 5 hours to get to fusion

#### What do you suggest instead/what changes do you propose?
reduce the time of osmirirdium to 18.75 seconds or reduce the cost of the luv motor to 8 ingots

**Comment by 0lafe** [comment]
If you use a single LuV ebf to get to fusion then yeah. Make 4, make 8, make some ZPM. 1A UV gets you less than a day of cook time, and is more than achievable in LuV.

**Comment by Anarack** [comment]
1 Amp UV would be 25 20k reactors... at that point you would of finished smelting it all before then, and that would be 50 quad uranium cells every 4 hours.

**Comment by 0lafe** [comment]
You shouldn't be relying on something that makes 20k EU/t and is that many blocks to get to fusion. Big thing about fusion, mk1 reactor can do 1M EU/t with 2 gens and some gt++ multis. Needing 250k EU/t or 500keu/t to make something like that seems reasonable, and you don't even need that much power, it just would make it easier.

**Comment by Anarack** [comment]
I'm not saying thats unreasonable power requirements, what I was trying to say was power doesn't really scale up that well to fusion. You have to take into account was exists not just what the end goal is.

**Comment by 0lafe** [comment]
Yeah, but there's options. GT++ rocket gens, and naq both have 32768v output versions that you should be able to make in LuV. LFTR does LuV, solars become usefuler after fusion in LuV, new GT++ solar tower eventually, I think there's fluid reactors that go to like ZPM with MOX. There's fluid reactors bees too, which are, interesting. Bart's essentia gen goes to like UV or something iirc depending on the inputs and stuff. Power ain't too bad, but it's not like early game where it's all about making multiple amps of that tier with oil or whatever.

**Comment by botn365** [comment]
for the gt++ rocket gens you also neet to produce the fuel for it wich is around 0.5 buckets of High octane gasoline per second the luv naq gen requires europium for fluid reactors you also neet to make HP steam turbines wich produses 10keu/t with ori turbines if you want to make 1 A UV you wil neet 50 HP turbines also i assumed that 1 ingot produses 8 fine wire wich turnt out not to be true it is 4 so even with 1 A uv it wilstil take 1 day and 19 hours to make the motors alone for it

**Comment by draknyte1** [comment]
The rocket engines will be different after I release the next build. So, I wouldn’t advise forking out for those now, when later they’ll be using different fuels and producing tonnes of pollution.

**Comment by richardhendricks** [comment]
Is this issue still relevant?

**Comment by botn365** [comment]
got fixed in 7.5/8.0
