### ISSUE TITLE
Can't craft ZPM Dynamo Hatch

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3838]
2.0.6.0

Tried but failed to craft a ZPM Dynamo Hatch using the requested material
![image](https://user-images.githubusercontent.com/30087707/48665792-38ef7f00-eab5-11e8-8c83-07a446d0ac3e.png)
plus IC2 coolant and Soldering alloy. Ass.line power is UHV.

Wild guess, but could this be due to the coolant cells can't stack, so the ass.line only registe one item in the input bus?

**Comment by Dream-Master** [comment]
can you pump it in as fluid ?

**Comment by DualBallers** [comment]
I don't understand your question?
The assembly line won't start the crafting the dynamo.

It is really only a guess, but the recipe asks for 
![image](https://user-images.githubusercontent.com/30087707/48665861-83bdc680-eab6-11e8-998d-119098c3a21c.png)
but this item don't stack 
![image](https://user-images.githubusercontent.com/30087707/48665865-9f28d180-eab6-11e8-813a-3fdbb81edbd5.png)
so maybe the coding for the assembly line cannot handle items that don't stack??

**Comment by Dream-Master** [comment]
oh ok yes i need to try if this can stack in assline with code changes or using 2 slots

**Comment by DualBallers** [comment]
I don't know if this is what is causing the problem, just a guess :-)
But if this is the cause - then ya, easy solution is 1 cell in 2 input buses instead.

**Comment by Dream-Master** [comment]
k
