### ISSUE TITLE
UV/UHV Motor are uncraftable

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3839]
#### Which modpack version are you using?
2.0.6.0

A UV motor needs UV superconductors which need a UV pump to craft.
A UHV motor needs UHV superconductors which need a UHV pump.
![2018-11-17_15 31 46](https://user-images.githubusercontent.com/20565115/48665977-51907280-ea7e-11e8-9008-11118030e762.png)
![2018-11-17_15 34 34](https://user-images.githubusercontent.com/20565115/48665978-53f2cc80-ea7e-11e8-8a27-1d7ba19383fa.png)

**Comment by bartimaeusnek** [comment]
also in 2.0.5.1

**Comment by Dream-Master** [comment]
will check

**Comment by Bluebine** [comment]
my idiotic, probably not balanced suggestions:
I don't think motors should use superconductors at all. Doesn't really make any logical sense to me. The ZPM motors use 4 stacks of fine wire and cables, whereas the UV motors take all those PLUS superconductors. I don't see how the superconductors fit into the recipe, or what they would logically do. As such, I'd suggest taking out the stack of superconductors in favor of more fine wire. ZPM motors use 4 stacks, so UV ones should use 6 stacks, UHV ones should use 8 stacks.
UEV ones would be fine staying as they are. Makes sense to me that the highest motor would be much more expensive. (If UIV+ motors are added, then UEV should be changed to using 8 stacks of a more expensive fine wire, or 4 stacks of regular wire.)
