### ISSUE TITLE
Forestry 4 issue

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#384]
If we ever will using Forestry 4 (binnie needs to update first but than we have to drop Biblio Craft Forestry Wood Support because it crash the game)

https://github.com/ForestryMC/ForestryMC/issues/869

**Comment by arnabbiswasalsodeep** [comment]
Is it still not fixed? We should have a discussion/poll on it. I personally don't mind things being removed

**Comment by Dream-Master** [comment]
For forestry 4 this addon is not supported and will crsah the game 100% sure.

**Comment by Dream-Master** [comment]
So i think we can slowly upgrade to Forestry 4. Chocohead from IC Forum make a Binnie patcher mod allready.

**Comment by arnabbiswasalsodeep** [comment]
Should we roll and update to it then, we can report issues to him so he can also fix the issues caused and make his mod more stable.

**Comment by Drobac** [comment]
give it a week or so minimum, untill any bugs it has get fixed. Unless its proven to be stable, dont want weird crashes or corruptions like nami got

**Comment by Dream-Master** [comment]
It is a patch not modifying any of binnies Code.
Chocohead the Mod Author said on the Forum
`````````````
Just so people are aware, I've made my own patcher to use ASM to fix Binnie's code directly rather than decompile and fork it like (I presume) vSkyD1 did. It should also be noted that by doing so, there's no licence issues if you wanted to include it in a modpack. Download + more information here: http://forum.feed-the-beast.com/threads/1-7-10-binnie-patcher.143722/
``````````````

**Comment by Dream-Master** [comment]
Not have an issue with it but recipe need to be redone. Lefty take care of it. Thanks.
