### ISSUE TITLE
Neuro Processing Unit can (only) be crafted with old recipe

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3840]
2.0.6.0

The Neuro Processing Unit can still be crafted using the obsolete assembly line recipe (using normal glass tubes, gold casing and so on).
Also it seems that the new recipe does not work.

More info:
The new recipe is available through NEI.
![image](https://user-images.githubusercontent.com/30087707/48666623-d2269180-eac5-11e8-9707-9897c20bd7b7.png)

It is the old recipe that is shown in the crafting book. 
![image](https://user-images.githubusercontent.com/30087707/48666627-e79bbb80-eac5-11e8-8b0b-4b1edad73d43.png)
![image](https://user-images.githubusercontent.com/30087707/48666629-f08c8d00-eac5-11e8-8685-c5dce8695911.png)

**Comment by Dream-Master** [comment]
ok will check

**Comment by bartimaeusnek** [comment]
@DualBallers if you have an old Stick, it wont get updated.

**Comment by bartimaeusnek** [comment]
@Dream-Master the recipe is safed in the NBT of the item, i would not recommend making an update function or something like that, tons of work, little reward...

**Comment by Dream-Master** [comment]
gold item casings from ic2 not longer exists so i guess the cant be crafted anyways

**Comment by 0lafe** [comment]
When assembly line item recipes change, you gotta make the stick again. Should probably put that somewhere in a quest or something. Do we have assembly line quests?

**Comment by Dream-Master** [comment]
no we dont have a quest for making some recipe so far i know.

**Comment by DualBallers** [comment]
Ahh, very important point if the data stick needs to be crafted again!

Will it also be too much work to make the old stick obsolete? 
Right now any player could continue crafting with the old and much cheaper recipe (in running SP, so I'm mostly thinking of MP).

Concerning the gold casing - actually the old recipe functions fine with the new gold casings, so this crafting recipe is not removed. I found out about this before I knew the recipe was changed with all the other items. 
So I don't think you can close the issue just yet :-)
