### ISSUE TITLE
Can't place new IC2 crops

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#3841]
#### Which modpack version are you using?
Live delta version; A quick inventory amongst the live players showed that this was still working two days ago.

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Place IC2 cropsticks on tilled (and hydrated land)

#
#### What happend instead? (Attach screenshots if needed)
The crop shows for a few frames, then disappears. It will later respawn in your inventory.

#
#### Other things tested
- Relogging did not work
- Restarting the client did not work
- An (off-schedule) server restart since the first observation did not restore functionality
- The same behaviour persists outside mytown borders.

**Comment by bartimaeusnek** [comment]
this bug randomly occurs and is known, but there are no ways to fix it, since its random.

**Comment by 648643579** [comment]
Absolutely the same problem.
I did not detect this problem on another server use crops IndustrialCraft 2.

@Dream-Master I ask for the problem to open,
- Does this problem only occur on Delta and Epsilon servers? or others custom servers + single player mode?

**Comment by 648643579** [comment]
Edit: After the server restarts, crops normal work.

**Comment by Dream-Master** [comment]
seems to be a server issue? did you @648643579  test it in sp too?

**Comment by Dream-Master** [comment]
seems to be a server issue? did you @648643579  test it in sp too?

**Comment by 648643579** [comment]
In sp mode, I did not find this problem. (but I do not play sp so long, to make the problem happen)
maybe it would help globally ask players in Discord if there is no problem in single player mode exist crops bug.

**Comment by Dream-Master** [comment]
@648643579 if you could ask on discord?

**Comment by Klaris69** [comment]
Again can't place cropstick. does not work yesterday or today.
please fix him.

**Comment by draknyte1** [comment]
If it’s an IC2 bug, it won’t get a fix. 
If it’s a thermos bug, it won’t get a fix. 

Nobody knowing the cause, probably won’t get a fix. 🤔

**Comment by repo-alt** [comment]
I never saw this bug on Epsilon, but I saw a different crops related bug recently: Starwart crop grows up to stage 4 and immediately after reaching maturity reverts to stage 1 and starts growing again. (It has netherstar block below - otherwise it would not grow past stage 3, it has enough nutrients etc. because it is not dying, it just grows in loops forever). Not sure if it is related to the original topic..

**Comment by WizardSleve280** [comment]
This problem is still occurring in the overworld only despite trying in chunks that have little to no pollution and in different bases. As far as what causes the issue I do not know and just wanted to bring attention to the issue again (even though there isnt a lot known about it)

**Comment by boubou19** [comment]
while the bug occurs we still can place crops on overworld but with fake players (worked with oc robots and dynamism tablet)
