### ISSUE TITLE
Assembly Line NEI

### ISSUE THREAD

**Issue by Francesco9717** [GTNewHorizons/NewHorizons#3842]
How can I see the assembly line's craft?

**Comment by sthegreat** [comment]
You have to pick up the output item from the ground once. Before you do that you can only see the scanner recipe, which tells you what you have to scan to get the data stick for the item.

**Comment by Francesco9717** [comment]
can I see the crafting in the nei?

**Comment by sthegreat** [comment]
After you picked up the item from the ground once yes. Before that you need to use the book thing.

**Comment by Francesco9717** [comment]
OK thanks :)

**Comment by Dream-Master** [comment]
i add a quest for data reader
