### ISSUE TITLE
HV energy hatches too expensive

### ISSUE THREAD

**Issue by SunsfuryAlpha** [GTNewHorizons/NewHorizons#3844]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I wanted to craft an HV energy hatch for my first vacuum freezer, am currently in early HV
#
#### What happend instead? (Attach screenshots if needed)
The recipe requires 2x Helium 60k cooling cells and 2x high voltage coils, which require materials that are incredibly out of tier
#
#### What do you suggest instead/what changes do you propose?
For the HV coil:
- Vibrant alloy requires an HV vacuum freezer to make, which is difficult but possible (2x MV energy hatches supplying 512 EU/t - I haven't tried this just yet), but more importantly the hot vibrant alloy requires a temperature of 3000K, which I cannot reach without making nichrome coils which require an HV vacuum freezer to make as well.

- The neodymium is annoying but possible to make without as much hassle as the vibrant alloy is, but it's still irritating to obtain

For the coolant cell issue:
- Swap over to the "60k NaK Coolantcell" - it's a lower tier coolant cell that's a lot more reasonable to obtain before a vacuum freezer is made, considering that Helium is best obtained from a vacuum freezer

**Comment by SunsfuryAlpha** [comment]
In addition to this, the EV coils require Samarium which I don't think can be obtained anywhere near that point in time

**Comment by 0lafe** [comment]
There's a bunch of helium in ender pearls iirc, or endstone, or both. Samarium doesn't sound right though, but I can't remember what it's a byproduct of, so it could be T2 rocket things

**Comment by SunsfuryAlpha** [comment]
Samarium is a byproduct from En, Eu and Io- min. T3 rocket

**Comment by Dream-Master** [comment]
yes it is to high for hv. Will re check recipes.
