### ISSUE TITLE
AE autocrafting doesn't see equivalent circuits as equivalent

### ISSUE THREAD

**Issue by Superlagg** [GTNewHorizons/NewHorizons#3845]
#### Which modpack version are you using?

2.0.5.1
#
#### If in multiplayer; On which server does this happen? 

Prospercraft.
#
#### What did you try to do, and what did you expect to happen?

I set up my ME patterns to build EV machines. I did this back when I was making the nano line of circuits, so they're all set to use those pretty blue rectangles. Everything worked great in those times.

Recently though, I upgraded from the nano line of circuits to the quantum line. Much cheaper, despite the added cost, now I've loads of lime green EV circuits. I went to order another batch of EV machines, expecting the ME system to use these new quantum EV circuits in place of the nano EV circuits, as I'd set the patterns to accept substitutions.
#
#### What happend instead? (Attach screenshots if needed)

The ME crafter refused to build those EV machines since I didn't have any nano EV circuits. I've got a few stacks of the newer quantum EV circuits, and those work just fine for making EV machines by "hand", but AE doesn't see these circuits as a suitable substitution for nano circuits.

I assume this is also true for other circuit lines.

#
#### What do you suggest instead/what changes do you propose?

One way to solve this is to somehow convince AE that similar voltage circuits from other circuit lines are substitutable. 

Another would be to add a crafting recipe to downgrade circuits to previous lines.

**Comment by bartimaeusnek** [comment]
Sadly AE2 code is to complex that any of the devs will fix it soon.
