### ISSUE TITLE
AE System Quest Recommendation

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#3846]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Working through the AE quests and expected there to be a quest for the AE2 Energy Accepter to actually power the system.
#
#### What happend instead? (Attach screenshots if needed)
There was no quest for this.
#
#### What do you suggest instead/what changes do you propose?
Add a quest to have people craft the energy accepters somewhere in the quest line where it makes sense.

**Comment by 0lafe** [comment]
Don't you not need those if you have controllers?

**Comment by shawnbyday** [comment]
> Don't you not need those if you have controllers?

Making a controller right away as opposed to a simple network just to get started is the goal of the quests I believe and making a controller right away is quite the task. I was thinking having this in the quest line early on will help people understand how to put all the parts they make for the quests together.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58297959-558bad00-7d9f-11e9-9dd7-2263b6306daf.png)
