### ISSUE TITLE
[2.0.6.0] Gendustry Bee didn't autoconvert to GT Bee + Ruby Comb didn't produce dust

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#3847]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
MP private
#
#### What did you try to do, and what did you expect to happen?
Update to new version 2.0.6.0
#
#### What happend instead? (Attach screenshots if needed)
Gendustry Bee didn't autoconverted to GT Bee.

Bees can't produce anymore because still Gendustry, GT Bees exist on NEI but the update didn't autoconverted all my bees.

PS : Ruby Comb from GT Ruby Bee didn't produce tiny dust anymore.

#
#### What do you suggest instead/what changes do you propose?
Idk.... help :p ! I downgrade to 2.0.5.1 waiting a fix.

![2018-11-19_19 50 06](https://user-images.githubusercontent.com/17729817/48728637-c78b0a00-ec35-11e8-9fa2-065ebbc6ef86.png)
![2018-11-19_19 50 18](https://user-images.githubusercontent.com/17729817/48728639-c8bc3700-ec35-11e8-934b-9c9d613862de.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek 
Any idea why this happend?

**Comment by Dream-Master** [comment]
@DV666 its still beta so we need to make more bug fixes .Update  imidiedly when an update comes out isn't the best idea .

**Comment by ScriptedPiky** [comment]
It should be important to know that you NEED to drop the bee on the ground or wait a bit with it in your inventory. It will then update to the new bee (I tested this in single player and confirmed that it worked). That is if you did drop the bee on the ground and picked it back up and waited for the auto-convert and nothing happened still, then there's a big problem.

**Comment by bartimaeusnek** [comment]
@Dream-Master Name miss-match from GT vs Gendustry bee.

**Comment by Dream-Master** [comment]
@DV666 can you list all bees that not convert ? I will rename it in t code. Thanks

**Comment by DV666** [comment]
"its still beta so we need to make more bug fixes .Update imidiedly when an update comes out isn't the best idea ." 

Don't worry, backups ftw ^^ :)

"It should be important to know that you NEED to drop the bee on the ground or wait a bit with it in your inventory."

A subscriber tell me this tip when i reinstall previous version, i think it was automated lol sry, i will try later again ^^

However, Ruby Comb can't be process on centrifuge, maybe somes combs are missing, i will try to check that.

**Comment by Dream-Master** [comment]
ok this bees you named before allready in coded (added by blood asp) will check the name miss matches.

**Comment by Dream-Master** [comment]
Ruby bees convert to gt @DV666 
combs not produce tine piles because i change the whole system.

**Comment by Dream-Master** [comment]
ruby combs from gendustry can put in centrifuge gt not.

**Comment by Dream-Master** [comment]
ok oredicts i need to add for gt combs

**Comment by DV666** [comment]
> combs not produce tine piles because i change the whole system.

Oh.... ok. Well, some GT combs still produce tiny dust so... ^^ I will wait the next version so :p

**Comment by Dream-Master** [comment]
yes the basic ones. the more advanced not.

**Comment by DV666** [comment]
Ok thx ^^ i think it was not intended.

**Comment by Dream-Master** [comment]
@DV666 i need a list with Bees that not converts. Thanks

**Comment by DV666** [comment]
Sorry for the late @Dream-Master, after a few days playing with this version, seem there are no issue anymore on Bee conversion.

So the only issue remaining on this topic is GT Type Filter didn't recognize GT Combs.

That's all :)
