### ISSUE TITLE
OpenPeripherals removed, MineTweaker scripts remain

### ISSUE THREAD

**Issue by plaguewolf** [GTNewHorizons/NewHorizons#3849]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Any run of the game
#
#### What happend instead? (Attach screenshots if needed)
Open Peripherals scripts still included in pack, after the mods were removed. log/chat spam of errors
#
#### What do you suggest instead/what changes do you propose?
revise minetweaker recipes to remove the following, as noted in changelog
Removed Mods:

Open Peripheral Core 1.4-280
Open Peripheral Addons 0.6-249
Open Peripheral Integration 0.6-95

**Comment by Dream-Master** [comment]
you need to remove it manually. Sadly technic not remove existing scripts or confings

**Comment by plaguewolf** [comment]
ah, weird. ok then, should i close the thread?

**Comment by Dream-Master** [comment]
yes sure. Thanks
