### ISSUE TITLE
Copying GT Molds and Extruder shapes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#385]
Would be nice to have the ability to copy the molds and shapes without having to use a smeltery which works weirdly in high tech bases with a lot of lag.
Need recipes to copy the molds/shapes in the Forming press much like the AE circuit boards using either 4x steel plates or quadruple steel plates to maintain the cost.
EU cost shouldn't be too high

**Comment by Dream-Master** [comment]
done
