### ISSUE TITLE
Add Calcite Ore to the Shop

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#3850]
So I have started my second playthrough and once again I am running into this issue: I am not finding a Lapis/Lazurite Vein for Calcite. Of course all of this is just RNG, I have found lots of Mica and Diamond Veins. So maybe you could add something to the shop page... this has been holding me back for days. (Make sure it is available before getting the Primitive Blast Furnace)

Other ores (like Diamonds) can be found as small ores so people don't rely as much on gen, but Calcite... well, players need a TON and it is quite rare.

**Comment by Dream-Master** [comment]
sure will add a coins quest
