### ISSUE TITLE
/iskamiunlocked

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3851]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
use /iskamiunlocked to see what i needed to reserch
#
#### What happend instead? (Attach screenshots if needed)
it it wont show all required reserch
#
#### What do you suggest instead/what changes do you propose?
update what reserches it serches for

**Comment by Dream-Master** [comment]
as i test the command all works fine.
@Ghengis88 show me what it shows when you hit the command ingame.

**Comment by Ghengis88** [comment]
i reserched all the things listed when using /iskamiunlocked and the command said YES! but ichor did not appear in my thaumnomicon.

i continud to reserch everythin in vanilla thaumcraft 4, still nothing

reserched cursed spirits blade and then i got it unlocked

**Comment by draknyte1** [comment]
Command probably has hard coded expectations, which dream tweaks and isn’t accounted for. Mod devs don’t expect tweaks to certain things/data, so we just use hard coded values to save time/cpu cycles.

**Comment by Ghengis88** [comment]
I dont know, thaumium crowbar i am also pretty sure is needed but it is not listed either

**Comment by Dream-Master** [comment]
a quest would be nice here

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57741445-7870df80-7682-11e9-8179-68811a0741f5.png)
