### ISSUE TITLE
EBF stops working when powered from distance

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/NewHorizons#3854]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to power EBF with 2 amps of about 110 EU/t and the recipe stops immeditly after starting the EBF. After building and connecting the EBF, this exact setup worked for about 2 aluminium ingots. When I tried to make another aluminium ingot an hour later it refused to work and is still not working.

https://puu.sh/C6EKM/8140263f15.mp4

https://puu.sh/C6EOF/e42bd17306.png

**Comment by Dream-Master** [comment]
you need 120 eu.

**Comment by Lainiel** [comment]
@Dream-Master Running 120EU/t recipe in EBF on 2 amps of 110EU/t shouldn't be a problem. The problem here is probably that my cable is crossing 2 chunk borders. According to Alkalus the problem might be that Delta is running Thermos instead of vanilla forge.

**Comment by 0lafe** [comment]
I ran 8 ebfs across like 7 chunk borders on a thermos server so idk if that's what's going on here.  I'd try putting a buffer on the ebf. That way you can see the real EU/t hitting the ebf. Also always helped me when EU/t seemed like it was enough but multis would power off

**Comment by Lainiel** [comment]
@0lafe Did you have any transformers/buffers in they way when running those 8 EBFs? The problem happens only when you try to run it from a battery buffer that's in a different chunk and feeds the EBF directly.

**Comment by draknyte1** [comment]
> According to Alkalus

Well, no, I didn't say Thermos *might* be the issue, it's almost guaranteed.
My few thousand hours testing in dev alongside playing on plain forge is enough proof.

Also, issue and more info - https://pastebin.com/1q8LFqp0
Figured this may be useful~

**Comment by Lainiel** [comment]
The problem is still the same even when using transformers. For example 4 amp MV bat buffer -> MV transfromer step up to HV -> silver cable over 2 chunk borders -> transformer step down from HV to MV -> MV energy injector

https://puu.sh/C72xJ/fed4fc1efb.mp4

**Comment by 0lafe** [comment]
If you put a buffer on the ebf it should fix it
