### ISSUE TITLE
GT++ multiblocks occasionally stop accepting power

### ISSUE THREAD

**Issue by Superlagg** [GTNewHorizons/NewHorizons#3857]
#### Which modpack version are you using?

2.0.5.1

#
#### If in multiplayer; On which server does this happen? 

Prospercraft

#
#### What did you try to do, and what did you expect to happen?

I put a lot of things to be wiremilled into a multiblock Wire Factory, and a bunch of things into a multiblock Mixer.

#
#### What happend instead? (Attach screenshots if needed)

Usually, it works fine; but sometimes it'll decide that it doesn't have enough energy, shut itself off, and refuse to recharge, despite having plenty of power connected to it. This seems to happen if it has a really big load of stuff to process, or if the thing its working on has a higher than normal voltage requirement (like tungsten string for the thermal undies).

When this happens, whacking the controller with a rubber mallet will make it turn on for a frame, take some of the stuff in the input bus, and then turn off again, voiding the items. The only way to fix this is to replace the multiblock controller and re-repair the maintenance hatch, though it'll happen again later.

This happens even more often in the multiblock Mixer, as it can barely get through one processing cycle before it shuts off for good.

In all cases, the machines are getting plenty of power to the energy hatches. I have a 4-slot EV battery buffer with 4 fully-charged lapotron crystals feeding into one EV energy hatch on the multiblock. It does the same thing with two EV energy hatches, both with fully loaded battery buffers connected to them. When they stop working, the batteries are still at full capacity, and the energy hatches report having their EU buffers full.

Also the GT EU Reader reports 0 for every value. Though it also does this with every other multiblock, including the EBF, which has never failed to work in this way.

**Comment by draknyte1** [comment]
Probably missing mufflers.. cause pollution will cause this if it cannot be released. 

Otherwise, it’s related to https://github.com/GTNewHorizons/NewHorizons/issues/3854#issuecomment-441337534.

Either way, not my issue. 
All multis have had tooltips updates to include muffler requirements. Unfortunately, people can’t read that it produces more than zero pollution and figure out you need a muffler...

Thermos is not support nor will I provide any.

**Comment by Superlagg** [comment]
> Probably missing mufflers.. cause pollution will cause this if it cannot be released.
> 
> Otherwise, it’s related to [#3854 (comment)](https://github.com/GTNewHorizons/NewHorizons/issues/3854#issuecomment-441337534).
> 
> Either way, not my issue.
> All multis have had tooltips updates to include muffler requirements. Unfortunately, people can’t read that it produces more than zero pollution and figure out you need a muffler...
> 
> Thermos is not support nor will I provide any.

I did this and it fixed everything, my bad!

**Comment by draknyte1** [comment]
Good to see ^_^
