### ISSUE TITLE
Uncraftable: EnderThermic Pump

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#386]
The IC2 Miner has no recipe, which is required for the EnderThermic Pump

**Comment by Dream-Master** [comment]
Yes have to change that.

**Comment by Dream-Master** [comment]
Sorry change the ic2 scripts thats why. In the new Pack the Ender pump have a new recipe.

**Comment by Dream-Master** [comment]
change it back on the Server.
