### ISSUE TITLE
Cannot submit wire quests (#1147 and #67 at least)

### ISSUE THREAD

**Issue by TheRailfan** [GTNewHorizons/NewHorizons#3861]
#### Which modpack version are you using?

#2.0.6.0 and 2.0.5.1
#### If in multiplayer; On which server does this happen? 

#NA
#### What did you try to do, and what did you expect to happen?

#Tried to complete part 2 of GT 6 Styled Wires and Cables (#1147), and all parts of Wired, Weird?! (#67)
#### What happend instead? (Attach screenshots if needed)

#The quests cannot be completed. The ore dictionary matches between quest and inventory wires and cables, but refuses to submit and complete. Not sure what other quests this affects but #67 blocks access to Tier 2.
#### What do you suggest instead/what changes do you propose?

#Fixing the quests so that they submit correctly

**Comment by wlhlm** [comment]
> They do not appear to register as being "crafted" when done in a Forestry Workbench.

Maybe this is worth fixing. The GTNH team maintains their own fork of BetterQuesting: 
https://github.com/GTNewHorizons/BetterQuesting

**Comment by Dream-Master** [comment]
@wlhlm are you on discord or how i can contact you?

**Comment by richardhendricks** [comment]
I have a half-dozen+ forestry worktables, and have never had them break GT tools after one use. Use them all the time to make pipes etc before my extruder. On Epsilon using 2.0.5.1

**Comment by wlhlm** [comment]
@richardhendricks Does shift-clicking work for you? I just tested this in 2.0.6.

**Comment by wlhlm** [comment]
> I have a half-dozen+ forestry worktables, and have never had them break GT tools after one use.

I have to correct myself. It works indeed. I was just too dumb to pick the right item from NEI:

![2018-12-04_16 30 34](https://user-images.githubusercontent.com/1928113/49466495-8cc1ce00-f800-11e8-8fca-cba472d04008.png)
