### ISSUE TITLE
Suggestion: Locking output hatches with a cell

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#3862]
Currently i'm in the process of setting up a chem line and it's quite a hassle running a LCR for a pass and hoping the fluids go in the right place so you can then lock the output hatches with a screwdriver.

Wondering if we could add something like putting a cell inside the output hatch and locking it that way, or something similar.

**Comment by repo-alt** [comment]
That would be a serious quality of life improvement. Not sure if it possible to do though (with reasonable efforts).

**Comment by mitchej123** [comment]
No promises, but I'll take a look.  This would be quite helpful for me as well.
