### ISSUE TITLE
Disassembler does not load correctly

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3864]
2.0.6.0

I have a Elite Disassembler II set to process large eggs continually.

The disassembler does not load correctly, as seen here.
This has happened many times now, and only in the current version, as far as I remember.
![image](https://user-images.githubusercontent.com/30087707/49109328-b459e900-f28a-11e8-94af-d787d36e8e12.png)

The game breaks if I try to access the disassembler (right-click). Luckily it is still possible to use the wrench, get the machine, and place it back again.

I don't know if this affects all types of disassemblers, or why only this machine is affected, of all the machines in my base.

**Comment by DualBallers** [comment]
This is a weird issue, and my understanding of it has changed somewhat now, so I have edited a bit in the above.

The disassembler is sitting in a loaded chunk with a world anchor. However after travelling far away and coming back, the machine is again unloaded just as seen above.

The machine only reloads back correctly when an item is fed to it (using e.g. a hopper).

**Comment by Dream-Master** [comment]
i disable egg disassembling btw in 2.0.6.0

**Comment by Dream-Master** [comment]
and i guess is it a gt++ issue. Dissasembling eggs are stupid. i make an better recipe for the stemcells.

**Comment by 0lafe** [comment]
It's a GT machine not working though, sounds like GT. Disassembler now is only used for, well, disassembling. Still top tier for rotors and stuff, and sorta needed

**Comment by draknyte1** [comment]
> guess is it a gt++ issue

Nope, it's a GT issue.
Removing the recipe that's broken doesn't fix the issue at all.

**Comment by Dream-Master** [comment]
The recipe was not broken but i ecided to remove disassembling eges and add a better recipe
work with 0lafe together to get a better solution. @draknyte1 
What i mean with gt++ is that it maybe errored out now whwn somone try to disassembling your egges .

**Comment by draknyte1** [comment]
> What i mean with gt++ is that it maybe errored out now whwn somone try to disassembling your egges

Then that's related to Thermos breaking the ticking on my items or something broken within the disassembler themselves.

Disassembly of Large eggs works fine within a vanilla instance of GT++ and GT5.

**Comment by Dream-Master** [comment]
ah ok

**Comment by Dream-Master** [comment]
@DualBallers ids not changing. Idk what happend

**Comment by draknyte1** [comment]
Can you upload the Gregtech log file somewhere?

**Comment by Dream-Master** [comment]
@DualBallers please use gist or pastebin in the future. Thanks

**Comment by DualBallers** [comment]
Pastebin had a ½ MB limit, and the file was +10MB.

But didn't know about gist - https://gist.github.com/DualBallers/ea3d335a74ffd22baf1d36a510ba8124

**Comment by richardhendricks** [comment]
It does look like a recipe issue.
```
java.lang.NullPointerException
	at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_Disassembler.checkRecipe(GT_MetaTileEntity_Disassembler.java:46)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.onPostTick(GT_MetaTileEntity_BasicMachine.java:503)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:525)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by boubou19** [comment]
issue happened to me in 2.0.7.0 with HV disassembler
