### ISSUE TITLE
Input grid in 9-input assembler is not centered to items

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3865]
2.0.6.0

Is it possible to move the input grid for the 9-input assembler **one** pixel down in the GUI?
Items are not centered in the input slots, and numbers are more difficult to read and understand
![image](https://user-images.githubusercontent.com/30087707/49110559-1ec05880-f28e-11e8-8b50-3de39245c2ed.png)

Compare this to a "centered" input grid
![image](https://user-images.githubusercontent.com/30087707/49110639-4fa08d80-f28e-11e8-9ea5-a556955a12e6.png)

**Comment by DualBallers** [comment]
I found the image and moved the grid down a pixel. The image is kept in 32 bit.

Here is the new:
![assembler2](https://user-images.githubusercontent.com/30087707/49310897-ee6ff880-f4df-11e8-8816-b852c9455502.png)

[add 9 slot assembler](https://github.com/GTNewHorizons/GT5-Unofficial/commit/bc0bd6fb437a16d7d0cf130f5aabfcddd346b606#diff-baaad6c8ac041d9c7336f985327d9cda)

**Comment by Dream-Master** [comment]
@DualBallers problem is the items not moving down i guess

**Comment by richardhendricks** [comment]
We need to clean up the image overall and relocate the boxes in the code. It's not super hard.

**Comment by Dream-Master** [comment]
@DualBallers did you test it? And can you send a screen from it?

**Comment by DualBallers** [comment]
No, I haven't tested it, as I'm still too much of a newb and haven't figured out how to compile the code :-)

**Comment by draknyte1** [comment]
There’s nothing to test or recode?

He moved the grid by 1px downwards cause you made t wrong Dream. If you want to test, replace the .png asset in the Gregtech .jar using winrar/7zip/etc.. Java archives are just fancy .zil files 🤨

**Comment by Dream-Master** [comment]
@draknyte1 what i mean is to recode the places where the icons laying length and high cords not the gui itself (png)

**Comment by DualBallers** [comment]
@draknyte1 thanks for the tip for testing
![image](https://user-images.githubusercontent.com/30087707/49345386-4f383600-f684-11e8-850f-399a128ce92f.png)

**Comment by draknyte1** [comment]
No worries @DualBallers. Knowledge shared means nobody has to really do any work to test it.

Why change the code though? It works fine as it is... Unless you're looking to add stupid 12 slot input machines, at which point just make a multiblock..

**Comment by richardhendricks** [comment]
I'd prefer fixing the window so it doesn't lay over the machine title. That shouldn't cause problems for the GUI right?

**Comment by Dream-Master** [comment]
sure if this fix the issue i am with you.
