### ISSUE TITLE
MV Output Bus is not possible to craft

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3867]
2.0.6.0

The MV Output Bus recipe is not available in NEI, and cannot be crafted with what I guess is the correct recipe.

![image](https://user-images.githubusercontent.com/30087707/49114999-e1fa5e80-f299-11e8-9d23-0ca563fb08f8.png)

Other bus recipes for reference
![image](https://user-images.githubusercontent.com/30087707/49115153-41586e80-f29a-11e8-8476-00a627420c3b.png)
![image](https://user-images.githubusercontent.com/30087707/49115119-25ed6380-f29a-11e8-9ab1-aea15a001c48.png) ![image](https://user-images.githubusercontent.com/30087707/49115137-31408f00-f29a-11e8-8732-1a97c13e428e.png)

**Comment by Dream-Master** [comment]
will check
