### ISSUE TITLE
Brick dust recipe change

### ISSUE THREAD

**Issue by XXxinsanityxX** [GTNewHorizons/NewHorizons#3868]
#### Which modpack version are you using?

#2.0.6.0.
#### If in multiplayer; On which server does this happen? 

#SSP.
#### What did you try to do, and what did you expect to happen?

#Centrifuge/Electrolyse brick dust.
#### What happend instead? (Attach screenshots if needed)

#Cant do that despite the dust having a chemical formula of Al4 Si3 O12.
#### What do you suggest instead/what changes do you propose?

#Add a recipe for the dust to be able to get either centrifuged or electrolyzed.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/d7ba87fa0dd78ced2258fc75fd6225c9a3b68fad
