### ISSUE TITLE
Some Assemblyline recipes on NEI is lack

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3870]
#### Which modpack version are you using?
2.0.6.0b
#
#### If in multiplayer; On which server does this happen? 
My private server and single,
#
#### What did you try to do, and what did you expect to happen?
I tried to show at the recipe using the Assemblyline with NEI.
#
#### What happend instead? (Attach screenshots if needed)
Some Assemblyline recipes on NEI is lack.
This screenshot is part of the recipe.
Other recipes such as Ultimate Really Battery, UEV Sensor, UHV Robot Arm etc are lack.
![2018-11-29_13 47 25](https://user-images.githubusercontent.com/40425798/49200068-71a92580-f3de-11e8-8dab-ccf4afa743a1.png)
![2018-11-29_13 46 40](https://user-images.githubusercontent.com/40425798/49200175-f136f480-f3de-11e8-8d13-d69b47bb5377.png)
![2018-11-29_13 47 19](https://user-images.githubusercontent.com/40425798/49200185-f98f2f80-f3de-11e8-8094-2e890913efb3.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
@Technus any idea why the object handling not working

**Comment by bartimaeusnek** [comment]
@Dream-Master @Technus this normally happens when items are null. maybe its a problem of the load order? i.e. Assembly Line Recipes in TecTech get created before BioCircuits are registered in Dreamcraft?

**Comment by Dream-Master** [comment]
No they are all gt items and it is a problem with oredict. I caht with Tec allready @bartimaeusnek

**Comment by Dream-Master** [comment]
will close after i make a new release.
