### ISSUE TITLE
Cannot craft Foresty Copper Electron Tubes in the GT Assembling Machine.

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/NewHorizons#3871]
GTNH 2.0.5.1

 There are two recipes and the only thing different is the voltage. I have a feeling there is a conflict.

**Comment by Dream-Master** [comment]
will check but guess this is fixed in 2.0.6.0. @redmage17 can you show me the recipe please?

**Comment by Dream-Master** [comment]
fixed in 2.0.6.0 but i will check it again
