### ISSUE TITLE
issue with malachite ore (nether version)

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3872]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
none
#
#### What did you try to do, and what did you expect to happen?
looked the use of the nether version of malachite ore in a furnace. Expected to see 1 copper ingot in output in furnace tab
#
#### What happend instead? (Attach screenshots if needed)
It gives two copper ingots 
#
#### What do you suggest instead/what changes do you propose?
change it back to 1 ingot like the others

**Comment by Dream-Master** [comment]
never known this was changed. I thought output amount can't be different between ore variants nether or overworld.
