### ISSUE TITLE
ic2 item casing not craftable

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#3874]
#### Which modpack version are you using?
2060
#
#### If in multiplayer; On which server does this happen? 
private serv
#
#### What did you try to do, and what did you expect to happen?
№144 quest "Automated Crafting" ender io crafter consists of autoworkbench bc-factory...
bench not crafter because of ic2 item casing impossible to create
#
#### What do you suggest instead/what changes do you propose?
in script change ic2 casing to greg

**Comment by Dream-Master** [comment]
sure will change that quest

**Comment by ko5h** [comment]
fix in #3875

**Comment by draknyte1** [comment]
It may not be craftable, but it *is* obtainable.. Just using standard vanilla IC2 mechanics.
https://ftb.gamepedia.com/Wrench_(IndustrialCraft_2)

**Comment by Dream-Master** [comment]
yes but it will autoconvert in seconds to gt casing @draknyte1
