### ISSUE TITLE
Add recipes for disabled Harvestcraft cooking tools

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#3878]
As we all know, the ME System isn't a fan of using GT tools for recipes so it would be great to be able to make the Harvestcraft tools that are disabled right now to automate recipes at later stages of the game.

My recommendation would be to use Stainless Steel for those recipes.

**Comment by richardhendricks** [comment]
I dunno.  By HV you can make food cans that remove the need for HC at all. I think it makes more sense to encourage the HV canner instead?  Or are you a compulsive food a holic like me? :D

**Comment by Methes** [comment]
Don't you need tons of cans on you when you go mining though? I find I run through them very quickly.
A lunchbox full of wholesome feasts lasts for ages and it's similarly fast.

**Comment by DoomSquirter** [comment]
2 stacks at most will last a long ass time

the only time you bleed through tin cans is, oddly enough, using a thaumic grafter with repair 2, to try and get saplings from trees.  

also, at any point in time you can make your own healing axe, let alone do the quests for it.  I don't think anyone really cares one lick about SOL and real eating past the early game.

**Comment by Methes** [comment]
True. Axe is great especially when travelling on foot, as it can keep up with the drain.
When I instamine a vein with my hammer, hunger drains fast and that's when I find regular food useful.
Axe for travelling, cans for everyday normal life, food for mining.

**Comment by Shattered2909** [comment]
@richardhendricks Y E S. But really, if I wanted to 100% something, it would be nice to have the possibility.

**Comment by richardhendricks** [comment]
Well I guess it's fine if you use stainless for the recipes.  It's up to @Dream-Master to put them in.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50538054-624a0300-0b69-11e9-8fcf-2f25015438e7.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50540149-d34ee200-0b8c-11e9-9ea1-12a45d1b3dfa.png)
