### ISSUE TITLE
Clear glass pane EBF recipe bug

### ISSUE THREAD

**Issue by XXxinsanityxX** [GTNewHorizons/NewHorizons#3879]
#### Which modpack version are you using?

#2.0.6.0
#### If in multiplayer; On which server does this happen? 

#SSP
#### What did you try to do, and what did you expect to happen?

#I tried to make clear glass panes in the blast furnace with minecraft glass panes and a circuit with config 1
#### What happend instead? (Attach screenshots if needed)

#The recipe consumed the circuit during the process.
#### What do you suggest instead/what changes do you propose?

#Change or fix the recipe.

**Comment by Dream-Master** [comment]
oh ok will check that later
