### ISSUE TITLE
Galaxy space materials in the Vacum Freezer

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#388]
Callisto Ice ingot, Hot quantium into, Ledox ingots, Mytril ( will give complete list when i log in and see all of them) take too long in the Vacuum Freezer, think Namikon said its about 60 seconds. You need a lot of those resources and it would be a lot better to lessen the amount of time to about 5-10 seconds

**Comment by Drobac** [comment]
- Ledox Ingot into Cold Ledox Ingot (45 seconds)
- Callisto Ice Ingot into Callisto Cold Ice ingot (60 seconds)
- Hot Quantium Ingot into Quantium Ingot (120 seconds)
- Hot Mytryl Ingot into Mytryl Ingot (180 seconds)
- Mysterious Crystal ingot into Cold Mysterious Crystal ingot (240 seconds)
All values are at 120 eu/t

The rockets are a one time craft, but it takes days at 32k eu/t to process the needed materials and id suggest to change the time at 120 eu/t to 5 seconds, maximum 10

**Comment by Dream-Master** [comment]
Will lower them.

**Comment by Dream-Master** [comment]
If you look at the materials all ingots need from a few seconds to 30 secs.

I will change it like the tier is.

**Comment by Dream-Master** [comment]
- Ledox Ingot into Cold Ledox Ingot (25seconds)
- Callisto Ice Ingot into Callisto Cold Ice ingot (25seconds)
- Hot Quantium Ingot into Quantium Ingot (30seconds)
- Hot Mytryl Ingot into Mytryl Ingot (20seconds)
- Mysterious Crystal ingot into Cold Mysterious Crystal ingot (35seconds)
