### ISSUE TITLE
Enable push/pull on plasmagen controller plz

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3881]
#### Which modpack version are you using?
2.0.6
#
#### What do you suggest instead/what changes do you propose?

Enable the ability to push and pull items from the large plasmas gen multi controller, so turbine management can be automated. Fusion setups can get into the hundreds of turbines, and maintaining that is just a pain. My friend and I would have a specific day of the month we had to shut everything down, and replace the rotors by hand. Took ~15min total, and got old fast. It was super immersive but like, too much so. This wouldn't really encourage the use of worse rotors, as the most efficient are still expensive, however trinium should maybe get a rotor Nerf. It has the highest throughput, tied with infinity. You can still require space in front of them, as that has no change on being able to access them. Overall just a super nice change. Lategame it's close to, if not the one thing that just can't be automated as of now.

**Comment by draknyte1** [comment]
Turbines need air in front of them tho. 🤨

**Comment by repo-alt** [comment]
At least robots/golems will be able to replace turbines, better than nothing.

**Comment by DoomSquirter** [comment]
transvector interface might work as well

**Comment by repo-alt** [comment]
Transvector interface behaved weird with multiblock controllers, when I tried to use it.

**Comment by DoomSquirter** [comment]
ideally, you'd bind it when there's no construct made.  then form it.  it only cares the x/y/z coords.  having a formed multi might give it the wrong info.  who knows.  never tried

but tbh, unless alk made some sort of short range alternative to that code wise, I can't think of any other way to manage that the way it was described.

**Comment by 0lafe** [comment]
Pretty sure TVI work fine for this, it's just moving items.
