### ISSUE TITLE
Ores in one chunk are missing data

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#3882]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Dug down to find Redstone vein.
Found only gt.blockores.0.name
In surrounding chunks ores spawn normally.
See the scanner for more info. Note that a few server days ago the vein appeared normal on the scanner.

Could this be a faulty chunk? I'm running a Forge server.
![2018-12-04_15 56 16](https://user-images.githubusercontent.com/8257735/49450591-a3a2f900-f7dd-11e8-9c6e-e611658d960d.png)
![2018-12-04_15 56 19](https://user-images.githubusercontent.com/8257735/49450595-a56cbc80-f7dd-11e8-81c4-f0a98a0e6812.png)

**Comment by Dream-Master** [comment]
did you try to generate a few new worlds in sp and look if they have chunck errors too? Or try to run a new few test worlds with your forge server setup and fly around with a scanner. So far i know i not seen this error before.

**Comment by bartimaeusnek** [comment]
i had this issure before, restarting the server did help me, also most likely a corrupted chunk...

**Comment by Methes** [comment]
Restarting didn't fix the issue but then again I've never seen this before in the countless hours of mining so I'll just close it. It's here for search if it happens to anyone else.
