### ISSUE TITLE
EBF eats programmed circuit when processing clear glass

### ISSUE THREAD

**Issue by Auge103** [GTNewHorizons/NewHorizons#3883]
#### Which modpack version are you using?
2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
Own server
#
#### What did you try to do, and what did you expect to happen?
1. Put glass into electric blast furnace
2. Put programmed circuit with number 1 in ebf.
3. Turned on machine
4. Waited for "clear glas" as output
#
#### What happend instead? (Attach screenshots if needed)
Clear glas came out, but the circuit disappeared - the machine ate the circuit after one run.
#
#### What do you suggest instead/what changes do you propose?
Change the recipe so that the circuit doesn't get consumed in the process

**Comment by Dream-Master** [comment]
fixed

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3879
