### ISSUE TITLE
Cant complete the Crossbow-Bolt Quests #1154 and #1156

### ISSUE THREAD

**Issue by kasper993** [GTNewHorizons/NewHorizons#3884]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Puting iron with Multi Fluid Cells from the TC-Smeltery into Basic Fluid Solidfier. It works perfectly than i craft my 71 Bolts with the Leaf Fletching on the Tool forge but the quest dont complete. The same problem with the Iro Bolt Quest on Steam Age #1156.

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Technical i completed the Quest but mentaly the Quest ist dont done yet. :-)

**Comment by Dream-Master** [comment]
i can send you @kasper993 a2.0.6.x dev version to test it in a never vesion if this i fixed.
Are you on dircord ?

**Comment by kasper993** [comment]
Hey,
no im not.  But i can send you my E-Mail Adress on GMX.

**Comment by Dream-Master** [comment]
ok sure

**Comment by Dream-Master** [comment]
@kasper993 try with lastest file please

[Quests-2.0.6.4.dev.zip](https://github.com/GTNewHorizons/NewHorizons/files/2716337/Quests-2.0.6.4.dev.zip)

thanks

**Comment by kasper993** [comment]
Hallo,

 

vielen Dank für die Rückmeldung. Ich habe die Datei DefaultQuests.json im Ordner .....MCnewhorizons/config/betterquesting ersetzt (ich hoffe es war der richtige Ordner) Nur zur Info: darin befindet sich  noch eine andere Datei die heist DefaultQuest-us.json. Auf jeden Fall sind jetzt beide drin. Die alte mit der Endung ....-us.json und die die du mir netterweise geschickt hast. Aber leider besteht das Problem  weiterhin. Habe das Game neu gestartet und an der Tool Forge die 19 Iron-Bolts nochmal gecraftet aber die Quest wird dadurch nicht gelöst bzw. erkannt. 

Ich hoffe ich nerve dich jetzt nicht mit noch mehr Quests die ich nicht lösen kann :-) Aber wollte gerade im Forestry Questbaum ein wenig fortschreiten und bei der dritten Quest der Nummer #577 (Forestry Core Block) komm ich auch nicht weiter. Ich vermute mal das die Bronze Item Casings nicht erkannt werden da die, die ich herstellen kann ein wenig anders aussehen (Die Farbe ist ein wenig anders und der Name ist nicht der gleiche, die Quest erfordert "Bronze Item Casings" herstellen kann ich aber nur "Bronze Casings". Ist aber nur eine Vermutung.


 

PS. Könntest du mir bestätigen das die Datei die du mir geschickt hast in den Ordner betterquesting reingehört. Ich habe mich glaube ich versehentlich beim ersetzten der Datei richtig dusselig angestellt und bin mir nicht mehr sicher ob die datei da rein gehört. 


Von: "Martin Robertz" <notifications@github.com>
An: GTNewHorizons/NewHorizons <NewHorizons@noreply.github.com>
Cc: kasper993 <zeljko.curic@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [GTNewHorizons/NewHorizons] Cant complete the Crossbow-Bolt Quests #1154 and #1156 (#3884)



@kasper993 try with lastest file please

Quests-2.0.6.4.dev.zip

thanks

**Comment by RUMisthepower** [comment]
@Dream-Master, @kasper993 I've had the same issue with iron bolts. I replaced "DefaultQuests.json" file with lastest one from the Quests-2.0.6.4.dev.zip. Doesn't help.
   The quest didn't want to detect the last task even though i've picked up iron bolts from the ground. The only solution i have found was a changing the quest using "/qb_admin edit". I replaced iron bolts with iron bolts. It worked. 
   I suppose that it doesn't meant to be this way. Hope you find what causing this trouble.
#google_translate
