### ISSUE TITLE
Swap moon dungeon quest and meteoric iron quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3886]
#### Which modpack version are you using?
2.0.5.1

#### What do you suggest instead/what changes do you propose?
Swap meteoric iron quest and moon dungeon quest, because players might return to base to make the meteoric iron in a blast furnace, and so will have to go back to the moon for the moon dungeon stuff.

**Comment by DualBallers** [comment]
Quest for meteoric iron is changed in 2.0.6.0 to not require ingots, so the quest order is ok.

**Comment by richardhendricks** [comment]
I think it should still be swapped, since getting to the dungeon early is pretty important.  Especially if your tools/armor degrade by the time you get around to it.

**Comment by Dream-Master** [comment]
@richardhendricks where you want to have this quest exactly ?

**Comment by richardhendricks** [comment]
Just directly swap the moon dungeon and meteoric iron quests.
