### ISSUE TITLE
sfm crafter is making server timeout

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3889]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i tried sfm crafter to see if that was a good option (i needed to turn copper grains into copper dusts)
expected everything to be fine.
#
#### What happend instead? (Attach screenshots if needed)
it appears that the sfm crafter is even worse than crafting in mass through the AE crafting terminal.

#
#### What do you suggest instead/what changes do you propose?
If you could prevent sfm from spamming the server that would be great.

**Comment by boubou19** [comment]
Steve's Factory Manager.

**Comment by Dream-Master** [comment]
the mod isnt open source so far i know.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Advanced Systems Manager is open source.

https://github.com/hilburn/AdvancedSystemsManager

**Comment by Dream-Master** [comment]
ok good to know so I need help here @bartimaeusnek @Technus @richardhendricks @mitchj123

**Comment by Dream-Master** [comment]
@bHXDgiuMa5yLHyC8 and this version fix the bug ?

**Comment by Dream-Master** [comment]
this version names are changed so all addons for thesfm have to be rewritten to

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50536796-910bad80-0b58-11e9-9c3c-417abe8e3eb1.png)

**Comment by Dream-Master** [comment]
@bHXDgiuMa5yLHyC8 
@boubou19 
i have a job for you.

delete steve factory manager and the addon of you mod folder and replace with this file

[AdvancedSystemsManager-1.7.10-0.2.0.zip](https://github.com/GTNewHorizons/NewHorizons/files/2716269/AdvancedSystemsManager-1.7.10-0.2.0.zip)

i need a full test to approve this works

Thanks

**Comment by nwmqpa** [comment]
In this current state, it's unusable, as stated [here]https://github.com/hilburn/AdvancedSystemsManager/issues/71)

And the developpement is nowhere to be active since 2015, we shouldn't hope for the author to update anytime soon. it may be possible to add the autocrafting however, and make it more efficient than SFM

**Comment by bHXDgiuMa5yLHyC8** [comment]
@Dream-Master I'm not a GTNH player, it was just a suggestion.
