### ISSUE TITLE
Extreme EU cost of fine wires for LuV motors 

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3891]
2.0.6.0

When crafting the LuV, ZPM and UV motors something immediately shows in how fast they can be made.
All three motors cost 4 stacks of fine wires (64 ingots), with the following smelting cost:

LuV, osmiridium ~ 47 MEU per ingot (EBF + vacuum feezing)
ZPM, europium ~ 40 KEU per ingot (EBF, no vacuum freezing)
UV, americium ~ 0 EU (dust can just be smelted)

So here is completely upside-down tech tree, where it takes much much longer to craft the LuV motor. And this motor is now heavily required in making new wetware boards. 

I think a more suitable material for LuV fine wires would be iridium placed around ~9 MEU per ingot.

I also do not understand why europium and americium is so cheap to produce.
Why not require an EBF recipe together with Radon (radon is also used in the Am and Eu silicon boule) for something like 50 MEU and 100 MEU per ingot?

**Comment by repo-alt** [comment]
Because in vanilla they are fusion only?

**Comment by Anarack** [comment]
Well europium the first source you can get to is your t1 fusion for 14MEU per ingot, americium is t2 fusion at 42MEU a ingot. so you may still have a point for osmiridium being some what odd still.

**Comment by DualBallers** [comment]
Ya, I didn't include the fusion aspect as once you can mine the Eu ore it is basically free to craft ingots in terms of EU. And at this stage you need tons of LuV motors.

Also Am dust can be made faster using the replicator for ~60 MEU, so I still feel like smelting should incur an additional EU cost.

**Comment by DualBallers** [comment]
Fusion does not help you to make the LuV motors faster, but if the barrier to fusion really is 512 stacks of osmiridium for all, then that also speaks for using another material for this motor tier.

**Comment by 0lafe** [comment]
Osmiridium gets fairly easy over time, wetware boards are UV, so osmiridum is fairly easy to produce. Europium soon is fusion only, fairly expensive compared to osmiridium in LuV. Americium in ZPM is mk2 and kind of hard, UU time amoung other things, mid UV it gets better but still hardish fusion only. That said, I'm for reducing it to 8 fine wire per ingot, and maybe 2 stacks of osmiridium in LuV, 3 stacks of europium in ZPM, and 4 stacks of americium for UV, UHV is 6 already I think, so that kinda fits

**Comment by 0lafe** [comment]
>Fusion does not help you to make the LuV motors faster, but if the barrier to fusion really is 512 stacks of osmiridium for all, then that also speaks for using another material for this motor tier.

8 per motor puts that to 64, and at the usefulness of the reactor, in not only making power, and progressing in theirs, but reducing the cost of the reactor significantly, in a way that phased out the need for mass amounts of old materials, and just more of higher tier ones. You aren't making more than 1-2 of the reactors with osmiridium, or 2 upgrades with europium. Americium sill making most of your reactors, and with a UHV, and even a UEV way to do fusion, it never seems to be too much.

**Comment by 0lafe** [comment]
>Also Am dust can be made faster using the replicator for ~60 MEU, so I still feel like smelting should incur an additional EU cost.

Could do that, add more time. Maybe have it be like 50s at ZPM? That's ~120k EU, much more than the energy positive way with the reactor.

**Comment by 0lafe** [comment]
Fine wire cost reduced to 2 stacks for LuV motor and 3 for ZPM motor, outputs increased to 8 fine wire per ingot

**Comment by DualBallers** [comment]
> Europium soon is fusion only

Sound good 

> Fine wire cost reduced to 2 stacks for LuV motor and 3 for ZPM motor, outputs increased to 8 fine wire 

Very good changes, IMO

>50s at ZPM ~120k EU

Should this say 120MEU? No, I think replicator cost is fine.
I think that the extra EU should be put into the EBF+freezing of the replicated dust, so that the cost for a finished ingot is maybe 2x of what 144 mb cost in the fusion reactor.

>Neutronium ... reasonable fusion recipe

I agree - if the mined ores will be removed. And same concern with replicator vs. fusion here.
Replicator+EBF+freezer EU should be maybe twice the cost of fusion

And now, when a steady production of more and different materials is needed from the fusion reactor, it also makes sense that the fusion coils becomes cheaper, so it is feasible to craft more reactors.

**Comment by 0lafe** [comment]
>And now, when a steady production of more and different materials is needed from the fusion reactor, it also makes sense that the fusion coils becomes cheaper, so it is feasible to craft more reactors.

They do kinda become cheaper, you don't have to use LuV for all of them. You can use ZPM and UV, maybe even UHV and UEV later for them. Talking numbers, unless you *need* like 4+ in LuV, 16+ in ZPM or 32+ in UV, I personally feel like they're at a good difficulty

**Comment by DualBallers** [comment]
@0lafe should the UV motor also be reduced from 6 to 4 stacks Am fine wires?

**Comment by 0lafe** [comment]
Probably, doesn't sound like the worst thing. Then again UV motors got fairly easy with the removing of the SC, so 6 isn't terrible either. 6 bothers me because it doesn't fit the pattern of +1 stack/tier, but idk if that's super important to preserve. I vote 6, but am open to 4

**Comment by DualBallers** [comment]
My vote is on 4 stacks of Am for UV motors.

Also @Dream-Master, I see that the wiremill recipes for Am is missing in this commit https://github.com/GTNewHorizons/GT5-Unofficial/commit/84e4ef347f50e2b19baa1e37c370aa5bdc543809

`
       GT_Values.RA.addWiremillRecipe(GT_OreDictUnificator.get(OrePrefixes.stick, Materials.Americium, 1L), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Americium, 4L), 100, 8);
        GT_Values.RA.addWiremillRecipe(GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Americium, 1L), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Americium, 8L), 200, 16);
`

**Comment by Dream-Master** [comment]
@DualBallers i guess they not missing only the other where to expensive. Will check
And no i am against 4 stacks if zpm use 4 stacks allready.

**Comment by DualBallers** [comment]
> Fine wire cost reduced to 2 stacks for LuV motor and 3 for ZPM motor

4 stacks for UV fits the progression like 0lafe mentioned.

Currently a single UV motor costs 96 Am ingots.
If the the wire buff + 4 stacks is included, the cost is reduced to 32 Am ingots. I think this is much more fair.

**Comment by Dream-Master** [comment]
ok sure i can lower the wire cost but not the stack size @DualBallers

**Comment by Dream-Master** [comment]
@DualBallers test it with nevest reipes and let me know if we need to talke here again.
