### ISSUE TITLE
Recipes to export for web based NEI

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3892]
Starting a list of recipes to export for a web-based interface to NEI.  Need to manually choose which items to include in the list.

Vanilla
Crafting table
Torches
Doors
Fences

Gregtech
All base parts for circuits
All base parts for each tier
All machines for each tier
Casings for multiblocks
Multiblock parts like mufflers/hatches
Kinetic generator parts
Solar panel parts

Armors
Darksteel
nanosuit
quantum suit

Jetpacks
Coal jetpack
Copterpack

Gregtech fluids
ic2
oil products
coal 
charcoal byproducts

Metals (just dusts to ingots? Ores? Maybe via NEI byproducts window?)
iron
copper
nickel
tin
platinum
Steel
Damascus Steel
Vanadiumsteel
stainless steel
titanium

**Comment by mitchej123** [comment]
handled by NEP & export mod

**Comment by quenbyako** [comment]
@mitchej123 Can we reopen this one? Cause if we are talking about [this NEP mod](https://github.com/bigbass1997/NotEnoughProduction) it's in not maintained anymore, in addition it doesn't work properly in GTNH 2.4.0, if i tested it correctly
