### ISSUE TITLE
Clear glass recipe inconsistencies

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#3895]
#### Which modpack version are you using?
2.0.4.9

#
#### If in multiplayer; On which server does this happen? 
Delta 

#
#### What did you try to do, and what did you expect to happen?
I was looking for routes to produce Tinkers' clear glass panes from my (backlogged) stock and I noticed some oddities:
- There is a manual crafting recipe with a saw, but no corresponding cutting machine recipe. Both exist for vanilla glass. Automating tinkers panes from tinkers blocks currently requires two trips through the EBF.
- The chisel can craft vanilla blocks from tinkers blocks, but not in reverse (which is a regression of #1483)
- Similarly, there is no chisel conversion in either direction between Tinkers' panes and vanilla panes.
- Natura's soul glass/heat glass can be converted from vanilla but not from TiC blocks. These need effectively be crafted in two steps despite all the other decorative glasses being available directly from the Tinkers' version

#
#### What do you suggest instead/what changes do you propose?
- Add the cutting machine recipe for tinkers glass panes.
- Revisit the chisel recipes (provided the inconsistencies don't exist for balance reasons)

**Comment by Dream-Master** [comment]
will check

**Comment by richardhendricks** [comment]
FYI, you can convert back to tinker's blocks if you first chisel to the Enderio quite clear glass first.
