### ISSUE TITLE
Cant craft LuV, ZPM, UV energy hatches

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3901]
2.0.6.2

Same issue with the coolant cells for LuV, ZPM and UV energy hatches
![image](https://user-images.githubusercontent.com/30087707/49968458-2b97aa00-ff26-11e8-9bd8-06cec0c4ab71.png)
![image](https://user-images.githubusercontent.com/30087707/49968478-35211200-ff26-11e8-8eee-b5552405338d.png)
![image](https://user-images.githubusercontent.com/30087707/49968494-41a56a80-ff26-11e8-8c31-ce59d61d302f.png)

**Comment by Dream-Master** [comment]
ok will take it in 2 slots
