### ISSUE TITLE
Assembly line quest change.

### ISSUE THREAD

**Issue by XXxinsanityxX** [GTNewHorizons/NewHorizons#3902]
#### Which modpack version are you using?

#2.0.6.2
#### If in multiplayer; On which server does this happen? 

#SSP
#### What did you try to do, and what did you expect to happen?

#Quest #1412 for the assembly line asks for Luv energy hatch, but to be able to make it in newer versions it requires the assembly line, so to make it you need to run the assembly line for the first time with 2 iv energy hatches to make the luv one.
#### What happend instead? (Attach screenshots if needed)

#The assembly line needs to be build and used to be able to make the hatch that the quest asks for.
#### What do you suggest instead/what changes do you propose?

Change quest to either ask for 2 iv energy hatches instead of the luv one or add to the description that you need to run it first with 2 iv hatches.

**Comment by Dream-Master** [comment]
sure

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/50207572-77868c80-0334-11e9-8b2d-e030e65eb51b.png)
