### ISSUE TITLE
recipe mistake of Neptun(e) Comb

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#3903]
#### Which modpack version are you using?

# 2.0.6.2

The Neptun(e) Comb produce Pluto Ice Dust

**Comment by Dream-Master** [comment]
will change

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50293037-f2ee5800-0472-11e9-8989-1a916aeedb75.png)
![image](https://user-images.githubusercontent.com/2970688/50293052-f8e43900-0472-11e9-939f-a47899897db8.png)
No not for me

**Comment by Kiwi233** [comment]
> ![image](https://user-images.githubusercontent.com/2970688/50293037-f2ee5800-0472-11e9-8989-1a916aeedb75.png)
> ![image](https://user-images.githubusercontent.com/2970688/50293052-f8e43900-0472-11e9-939f-a47899897db8.png)
> No not for me

Plz search the Neptun Comb
The "Neptun Comb" added by GTNH version 2.0.6.2 produce Pluto Ice Dust

**Comment by ko5h** [comment]
cant reproduce too https://imgur.com/a/HwJntEz
pluto ice drop - pluto bee, pluto comb and pluto surface
