### ISSUE TITLE
EMT update stuff 

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#3904]
#### Which modpack version are you using?
2.0.6.2
#
#### What do you suggest instead/what changes do you propose?
Update EMT information + fix Names for unfinished casings + ru + de translation

@Cinobi @Spartak1997 can you help with RU translation?

**Comment by Spartak1997** [comment]
@bartimaeusnek why not

**Comment by bartimaeusnek** [comment]
finished with: https://github.com/GTNewHorizons/Electro-Magic-Tools/commit/980df8516a5955defbc6faa5ae3b06eac3ace91a
