### ISSUE TITLE
ElectroMagicTools server client version mismatch

### ISSUE THREAD

**Issue by Azacomu** [GTNewHorizons/NewHorizons#3905]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Personal server
#
#### What did you try to do, and what did you expect to happen?
Connect to updated server.
#
#### What happend instead? (Attach screenshots if needed)
When logging in to the server, connection was refused due to mismatch of mod versions. ElectroMagicTools in the server zip is version 1.2.7.4, while the (technic launcher) client has version 1.2.7.3
#
#### What do you suggest instead/what changes do you propose?
Update client EMT version to 1.2.7.4, after doing so manually it works fine.

**Comment by Dream-Master** [comment]
ok will check the file

**Comment by Dream-Master** [comment]
redownload it @Azacomu  it is fixed now.
