### ISSUE TITLE
[Suggestion] make creative IC chip cheaper

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#3906]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
the current price of the chip is way too expensive for what it does,
the price should be 1 ev or iv circuit with a non creative chip because it is a single use item

**Comment by bartimaeusnek** [comment]
> The IC Chip is an item added by Project Red which allows the player to construct individual redstone circuits in one gate.

The Creative one removes the limitation of parts per gate IIRC, may be worth rebalancing that, also im not quite sure if a EV or IV chip is equivalent to the ammount of redstone stuff that would be needed if the redstone circuits were build bigger... 
All in all its just redstone, so.. maybe a LuV circuit + IC + Circuitboard? 
Just my 2 cents on this..

**Comment by botn365** [comment]
al the red stone stuf is realy cheap it feel like an im am lazy too make the redstone stuff

**Comment by 0lafe** [comment]
It's Redstone and some low tier circuits for the boards for the gates. Idk what you mean it's too expensive, it gives free things lol. 64x64 space to make them is also a godsend. If anything it needs more infinity. Until then just make your gates, like is intended. They're LV crafts so it's not like you can't by EV/IV, but giving them away for *free* doesn't make sense that early.

**Comment by Dream-Master** [comment]
No we dont make it cheaper maybe more better in tier if this is wrong. @0lafe any idea

**Comment by 0lafe** [comment]
Iirc it's circles of tiers of circuits, maybe recplace outter tier with infinity? So lowest tier circuit replaced for a circle of infinity? This creative item isn't really needed, and using infinity puts it in line with other "creative" items

**Comment by Dream-Master** [comment]
creative items have their recipes
