### ISSUE TITLE
[2062]assembling machine energy-dynamo hatch mistake

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#3907]
#### Which modpack version are you using?
2062
#### If in multiplayer; On which server does this happen? 
private
#### What did you try to do, and what did you expect to happen?
![nei repice](https://user-images.githubusercontent.com/27635022/50039260-1b73ed80-0040-11e9-8543-b481f29c39cc.png)
#
#### What happend instead? (Attach screenshots if needed)
[for craft can used one cell (he or nak)](https://i.imgur.com/9VRgWNB.gifv)

**Comment by Dream-Master** [comment]
ok so I need to change the second one
