### ISSUE TITLE
Server Package 2.0.6.2 is creating the world outside the world folder

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#3908]
#### Which modpack version are you using?
2.0.6.2 server package
The world is not using the world folder and instead generating a new one and dumping the resulting files in the main folder for the server package.

Also the default server properties has the white list enabled by default.
![capture](https://user-images.githubusercontent.com/20565115/50039464-9fa28280-fff8-11e8-8d6f-4f610396082c.PNG)

**Comment by Dream-Master** [comment]
the server properties are not 100% is was only a layout for the rwg map type. I let many values open so that the server user have to configure it ready.

**Comment by Dream-Master** [comment]
I update server properties.
