### ISSUE TITLE
Any stable build?

### ISSUE THREAD

**Issue by SL-TX** [GTNewHorizons/NewHorizons#3910]
#### Which modpack version are you using?
2.0.4.2 like stable
now 2.0.6.0
#
#### If in multiplayer; On which server does this happen? 
local
#
#### What did you try to do, and what did you expect to happen?
play game
in 2.0.4.0 
Nether ores not generating [2.0.4.0] #2992
in 2.0.6.0
Cannot craft/use GTNH quartz sand #3843
#
#### What happend instead? (Attach screenshots if needed)
can't complete the quests
#
#### What do you suggest instead/what changes do you propose?
test at least possible of completing quests and world generating 
play game as usual

**Comment by Dream-Master** [comment]
2.0.5.1 is stable and 2.0.6 2 should be stable too.

**Comment by SL-TX** [comment]
ok i play 2.0.6.2
