### ISSUE TITLE
Boosted Large Combustion Engine outputs too much power

### ISSUE THREAD

**Issue by Jocroy** [GTNewHorizons/NewHorizons#3911]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
SP testing, but first hints in MP on DtB.
#
#### What did you try to do, and what did you expect to happen?
Use a LCE in O2 boosted mode, expected it to output 6144 EU/t.
#
#### What happend instead? (Attach screenshots if needed)
The IV dynamo hatch's internal buffer filled up completely, despite 1A of power being output. A test with both a High-Amp IV hatch and a LuV hatch into a battery buffer yield 18500 EU/t, if my math is correct, about 3x of the expected value. Scanning the controller gives a reading of 300% efficiency, this seems to be applied on top of the boost.
The unboosted mode seems to work fine.
#
#### What do you suggest instead/what changes do you propose?
Reduce the output to the correct value.

**Comment by Dream-Master** [comment]
@Jocroy is this a GT machine or a GT++ machine?

**Comment by 0lafe** [comment]
GT machine

**Comment by Dream-Master** [comment]
need help with this @bartimaeusnek @mitchej123 @richardhendricks @Technus
