### ISSUE TITLE
[2.0.6.2] Un craftable framing table

### ISSUE THREAD

**Issue by nwmqpa** [GTNewHorizons/NewHorizons#3912]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Happens in Self-hosted multiplayer
#
#### What did you try to do, and what did you expect to happen?
We tried to craft the Framing Table, from StorageDrawers, but it appears to be uncraftable.
![expected](https://user-images.githubusercontent.com/7863529/50092734-2b8df780-020f-11e9-9a78-1628d5c9e1ee.png)

The recipe, as shown in NEI is:
#
#### What happend instead? (Attach screenshots if needed)
When we try to craft, nothing happens.
![already](https://cdn.discordapp.com/attachments/466695842611462174/524226829473808384/PrtScr_capture_5.png)
#
#### What do you suggest instead/what changes do you propose?
Should we rework the recipe or make it function correctly ?

**Comment by nwmqpa** [comment]
![nope](https://cdn.discordapp.com/attachments/466695842611462174/524242375380434964/PrtScr_capture_4.png)
It seems not

**Comment by Dream-Master** [comment]
ok will check the recipe

**Comment by Dream-Master** [comment]
you need to use drawers on top @nwmqpa

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50292058-722e5c80-0470-11e9-8ef1-146c44783d7e.png)
 
Tims looks similar to drawers
