### ISSUE TITLE
Missing recipes in Gendustry Protein Liquifier

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#3914]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer, on which server does this happen?
Prospercraft

#
#### What did you try to do, and what did you expect to happen?
Used raw chicken in the protein liquifier to make protein

#
#### What happend instead? (Attach screenshots if needed)
The recipe did not work

#
#### What do you suggest instead/what changes do you propose?
Add recipes in the protein liquifier to accept raw chicken (as well as other missing vanilla meat such as raw beef).

**Comment by Dream-Master** [comment]
are the recipe shown in nei or not @finkledoodle  ?

**Comment by ko5h** [comment]
This recipe is not in the nei, they are taken from https://github.com/GTNewHorizons/NewHorizons/blob/master/config/gendustry/overrides/recipes.cfg#L19

**Comment by ko5h** [comment]
out of fish-catcher a lot of fish you can craft protein
#3918 if need this
