### ISSUE TITLE
Twilight Forest BiomeDecorator generation bug

### ISSUE THREAD

**Issue by proEndreeper** [GTNewHorizons/NewHorizons#3915]
#### Which modpack version are you using?
1.7.10-2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Personal Server running 2.0.6.2 with WorldBorder, ForgeEssentials, WorldEdit, Opis, Dynmap Beta installed
#
#### What did you try to do, and what did you expect to happen?
Pregenerate using WorldBorder the Twilight Forest, expected it to ocassionally crash only due to memory leaks, but not from generation.
#
#### What happend instead? (Attach screenshots if needed)
Server Crashed
https://pastebin.com/qxYXcVKN
#
#### What do you suggest instead/what changes do you propose?
Patch the BiomeDecorator as suggested in the issue report on Twilight Forest's github.
https://github.com/TeamTwilight/twilightforest/issues/564#issuecomment-409479816

**Comment by Dream-Master** [comment]
@bartimaeusnek @richardhendricks  @mitchej123 @Technus is this realy fix this issue

**Comment by richardhendricks** [comment]
@proEndreeper Please provide worldgen seed so we can duplicate issue locally.  Thanks.
