### ISSUE TITLE
Two "Quantaria" leaves

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3916]
2.0.6.2

Looks like there are Iridium and Osmium "quantaria" IC2 crop leaves.

7090:32533 and 7090:32534

**Comment by bartimaeusnek** [comment]
@richardhendricks no actually the Quantaria drops both with Iridium underneath it, the Osmium leaf is just rarer

**Comment by Dream-Master** [comment]
ok maybe a quest worth ?

**Comment by richardhendricks** [comment]
right now it is a reward seed from doing bauxia, titania, scheelinium, and platina.  I think it's ok
