### ISSUE TITLE
Biblicraft Armorstand Head issue

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#3917]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
DigToBuild
#
#### What did you try to do, and what did you expect to happen?
Shift + Rightclick redstone powered Armorstand while having multiple player heads equipped in headslot.
Heads should be stored in the armorstand.
#
#### What happend instead? (Attach screenshots if needed)
Armorstand consumed all excessive heads and only returned 1.
#
#### What do you suggest instead/what changes do you propose?
Either remove heads being equipable or remove the stackable property in head slot.

**Comment by Dream-Master** [comment]
@DietmarKracht i cant change Bibliocraft because it is closed source. Not much i can do from my side i guess.

Nice to see you come back and play the pack again.

**Comment by DietmarKracht** [comment]
I really love this pack and so much has changed since i last played it :)

**Comment by richardhendricks** [comment]
What does wearing multiple player heads do for you?

**Comment by DietmarKracht** [comment]
I can just stack them if i am not wearing any helmet armor and they dont block one inventory slot.
