### ISSUE TITLE
Forestry Core Block oredict discrepancy

### ISSUE THREAD

**Issue by AcidaliaP** [GTNewHorizons/NewHorizons#3920]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
gtnh.friedbees.net
#
#### What did you try to do, and what did you expect to happen?
I'm attempting to complete the Forestry Core Block Quest #577 and it appears that it doesn't accept the bronze casing from gregtech. 
![image](https://user-images.githubusercontent.com/44490359/50174336-96970700-02bf-11e9-8e44-496ef3166511.png)

#
#### What happened instead? (Attach screenshots if needed)
It appears to require the forestry casing, but the block is craftable using the gregtech casing:
https://media.discordapp.net/attachments/438304165387829248/524646671007744010/unknown.png?width=705&height=381

We think it might be an oredict hiccup in the quest.
#
#### What do you suggest instead/what changes do you propose?
If it could be verified/updated to accept both casings for the quest, it would be nice. Admittedly, one can wait until it's possible to use the rolling machine, but personally I'm not positive it would make the correct plating even then.
Much appreciated!
AcidaliaP

**Comment by ko5h** [comment]
#3927 
have question. What to do with dreamcraft casing?
there is only iridium alloy item casing left that is used in current recipes

**Comment by Dream-Master** [comment]
yes that is correct

**Comment by Dream-Master** [comment]
was fixed by @ko5h
