### ISSUE TITLE
Setting Ore to multiple Ore Find Wands at one time Issue.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3921]
#### Which modpack version are you using?
2.0.6.0b
#
#### If in multiplayer; On which server does this happen? 
Private Server and Single
#
#### What did you try to do, and what did you expect to happen?
When there are two Ore Finder Wands in the inventory, set Ore to one Ore Finder Wand.
#
#### What happend instead? (Attach screenshots if needed)
Ore set on two Ore Finder Wands.

Empty two Ore Find Wands
![2018-12-19_04 08 26](https://user-images.githubusercontent.com/40425798/50177254-d94ef280-0344-11e9-9126-9f84f256df0e.png)
Set Ore to Left Ore Find Wand.
![2018-12-19_04 16 47](https://user-images.githubusercontent.com/40425798/50177303-026f8300-0345-11e9-9e98-6a9473e7a700.png)
Ore set on two Ore Finder Wands.
![2018-12-19_04 18 10](https://user-images.githubusercontent.com/40425798/50177400-43679780-0345-11e9-839f-e525d0b9cc67.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.
It worked well with GTNH ver2.0.5.1

**Comment by richardhendricks** [comment]
Multiple ore finder wands have never worked together.  They are intended to be used much beyond MV anyways. We will be reviewing a blacklist for the ore finder and adding ores and other things that are incorrect. 

Please make the hand prospector or seismic prospector instead.

![image](https://user-images.githubusercontent.com/1214811/50179074-c21fee80-02cb-11e9-8176-a9edff455057.png)
