### ISSUE TITLE
Can't complete MV Quest #1020

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/NewHorizons#3925]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
NA
#
#### What did you try to do, and what did you expect to happen?
Step 3 of the quest asks for universal fluid cells, which is odd as fluid cells are normally asked for. I made them anyway and the step is still showing incomplete. I tried dropping and picking up, recrafting, using regular fluid cells.
#
#### What happend instead? (Attach screenshots if needed)
Quest just stayed incomplete.
#

**Comment by Dream-Master** [comment]
What is the name of the quest? Maybe sone fluid or stuff changed and the quest need to reworked. @NoriSilverrage

**Comment by richardhendricks** [comment]
It's the iron(II) chloride quest.  I think it's fixed already?

**Comment by richardhendricks** [comment]
I'm working on quests right now, let me know.

**Comment by Dream-Master** [comment]
it is. @NoriSilverrage reload your quests with /bq_admin default load
