### ISSUE TITLE
awakened coil, mica insulator

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#3930]
#### Which modpack version are you using?
2062
#### If in multiplayer; On which server does this happen? 
private
#### What did you try to do, and what did you expect to happen?
for craft coil block need mica insulator (tier+1)*4
cupronickel = 8, kanthal = 12 etc
#### What happend instead? (Attach screenshots if needed)
![](https://i.imgur.com/2ZH1h1v.png)
for awakened need 40 mica insulator

**Comment by Dream-Master** [comment]
@ko5h thanks for pull
