### ISSUE TITLE
Quest 1200 Plasma Generator should ask for a lower tier dynamo

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3931]
2.0.6.2

The quest for the Plasma Generator should not ask for a UV Dynamo, but instead for a LuV or ZPM dynamo.

A UV dynamo requires many UV tier machines to make, e.g. for crafting of Piko Power ICs. 
This means that it is only possible to finish the plasma generator quest much later after making the first fussion reactor. 
If you are progressing using the quests you will then basically miss out on the plasma power generation in the LuV and ZPM tiers. 

The quest text must also be updated, where it's stated that you *need* UV or above to process the plasma. Does this not depend entirely on the size and type of rotor?

**Comment by bartimaeusnek** [comment]
Same for the Assembly Line quest, it asks for a LuV Hatch, when LuV Hatches are Assembly Line only now...

**Comment by Anarack** [comment]
#3902 the assline one is fixed.

**Comment by Dream-Master** [comment]
Not oredict stuff but fixed quest
