### ISSUE TITLE
Naquadah Vein is generate at END

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3934]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What happend instead? (Attach screenshots if needed)
Naquadah Vein is generated END regardless of END generation being disabled in Config.
Naquadah Vein in END.
![2018-12-21_21 04 07](https://user-images.githubusercontent.com/40425798/50342472-8ce2fd00-0566-11e9-8b13-9b5e0cbead97.png)
Config
![2018_12_21_14_23_22_396](https://user-images.githubusercontent.com/40425798/50342447-7046c500-0566-11e9-823b-96fe1d996758.png)
#
#### What do you suggest instead/what changes do you propose?
fix it.

**Comment by bartimaeusnek** [comment]
@yukieiji see line 2 of your config, End Astroids will appear multiple times, since HEE is in the pack and adds its own "end astroids".
