### ISSUE TITLE
issue with claiming rewards in LATEST on technic?

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#3936]
#### Which modpack version are you using?
latest on technic
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
quite a few ppl who say they have legit copies of mc and are logged in have stated they have issues claiming rewards in latest version on technic.  I haven't updated and I've yet to see someone explain what the issue is...
#
#### What do you suggest instead/what changes do you propose?
are these ppl all doing pirated non auth issues or is it something wierd with technic?

I'm fairly certain there are ppl that updated on technic and are having no issues or it'd be constant.

**Comment by bartimaeusnek** [comment]
well the questbook tends to be buggy. i also got a few unclaimable quests on 2.0.5.1

**Comment by DoomSquirter** [comment]
this scenario is different tho.  each person that upgraded said it worked fine on twitch, not on technic

I'm beginning to think they're not ensuring they are logged in via launcher tho.  something they didn't have to concern themselves with on twitch

**Comment by Dream-Master** [comment]
I play 2.0.6.2 on zeta and i never have a issue with unclaimed quests. And i use technic. @DoomSquirter

**Comment by Dream-Master** [comment]
@DoomSquirter did you try multi mc or another launcher? You can prepare twitch with newest pack two. Maybe i can make a new version outside curse for the time beeing.

**Comment by DoomSquirter** [comment]
it's not me that's having the issue

problem is a bit exasperated by some language differences as well.  

willing to close this if nobody else has any input and will just assume everyone having this issue is either running crack copy or failing to notice launcher isn't authenticated

**Comment by Dream-Master** [comment]
if i not get more here i close this issue. @DoomSquirter

**Comment by DoomSquirter** [comment]
not if I do it first!  *ZOINK*
