### ISSUE TITLE
[2.0.5.1] Phatlic Acid recipe consumes second cell

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#3938]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Crafting 1 cell of Phatlic Acid, which uses 2 Oxygen cells to make. I expected 1 Phatlic Acid cell and 1 empty Oxygen cell
#
#### What happend instead? (Attach screenshots if needed)
The reaction produces 1 Phatlic Acid cell, but the second oxygen cell is destroyed in the recipe, instead of being returned as an empty cell.
#
#### What do you suggest instead/what changes do you propose?
Change the recipe to provide an empty cell alongside the Phatlic Acid cell.

**Comment by Dream-Master** [comment]
will check

**Comment by finkledoodle** [comment]
To update, apparently the reactions for Diphenyl Isophalate and Diaminobenzidine also have the same issue of using 2 cells but only outputting 1.

**Comment by ko5h** [comment]
https://imgur.com/a/AlhwHik each of these recipes has other variations
