### ISSUE TITLE
Thaumcraft's research Magic Bees's frames introduction

### ISSUE THREAD

**Issue by huajijam** [GTNewHorizons/NewHorizons#3939]
#### Which modpack version are you using?
GTNH 2062
#
#### What happend instead? (Attach screenshots if needed)
Introduction of item "Gentle Frame"
Write Resilient Frame into Gentle Frame
in "the Resilient Frame will deplete the nearby Aura by one point"
It acutlly should be "the Gentle Frame will deplete the nearby Aura by one point"
#
![image](https://user-images.githubusercontent.com/29218242/50383273-1b808700-06eb-11e9-9587-ca963d07ba2d.png)

**Comment by Dream-Master** [comment]
hope it fix it and the description is right.
