### ISSUE TITLE
Add a quest to craft GT++ fish catchers

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#3940]
This.

**Comment by septemberWaves** [comment]
Isn't there already a quest for that?

**Comment by Dream-Master** [comment]
@Shattered2909 which version of gtnh you play?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50457164-e62da080-0959-11e9-94d7-9a1b0d6f2e06.png)
![image](https://user-images.githubusercontent.com/2970688/50457170-eaf25480-0959-11e9-9f94-b5260d76e40e.png)
so its added allready.

**Comment by richardhendricks** [comment]
Does that require nether hive blacks?

**Comment by Dream-Master** [comment]
no why @richardhendricks

**Comment by Shattered2909** [comment]
sorry, didnt follow this. so there is a quest. why on earth does it require blast off and the pams harvestcraft trap tho?

**Comment by richardhendricks** [comment]
@Shattered2909 The pam's fish trap is a low tech fish trap.  The GT++ is high tech, and it needs some stuff after the Blast Off quest.
