### ISSUE TITLE
Wand cap issues

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#3941]
#### Modpack version:
2.0.5.1
#
#### Description of issues:
The most pressing issue is that the thaumonomicon research for silver wand caps does not appear to unlock the infusion recipe to make charged silver wand caps. Infusion has already been researched but neither the thaumonomicon nor NEI show a recipe for charged silver wand caps.

Additionally, sometimes the second page of a wand cap research shows a recipe unrelated to the actual wand cap in question; for example, the page for silver wand caps shows the silver cap recipe followed by the recipe for a gold banded wooden scepter (scepters have _not_ yet been researched), and the second page for gold wand caps shows the recipe for a copper capped wooden scepter. Some brief experimentation shows that these scepters are not actually craftable, as would be expected with the lack of related research.

**Comment by Dream-Master** [comment]
@septemberWaves did you try it with 2.0.6.2 ? I rember i fix it but not sure.

**Comment by Dream-Master** [comment]
http://downloads.gtnewhorizons.com/
or technic launcher
https://www.technicpack.net/modpack/mcnewhorizons.677387

**Comment by septemberWaves** [comment]
Thanks; I really had no idea where to look for this.

**Comment by septemberWaves** [comment]
That explains things; I don't use reddit so I wasn't aware of this. I'm glad the pack is still being updated.

And I can confirm that the recipe appears to be functional in 2.0.6.2, now that I've transferred my world over. I still don't actually _have_ an infusion altar (I decided to do a lot of Thaumcraft research while moving batteries from a charging setup to my blast furnace to make the redstone alloy cable that I needed to power the blast furnace consistently) but I assume now that the recipe appears in NEI it should work.

The second issue I brought up - some wand cap research pages (and apparently also some wand _core_ pages) showing recipes for unrelated scepters - still persists however. Again, the scepter research has not been completed yet and the listed scepters aren't yet craftable, so the issue is fairly minor, but still present.

**Comment by Dream-Master** [comment]
@septemberWaves so the silverwand issue is fixed so far i understand you. Thet the thaumcraft book show radom wands on a extra page i cant change. I want they show the right wand but thaumcraft choose one . Should i remove this extra page or is is a good example how stuff works?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50457133-b088b780-0959-11e9-830b-266cf504936f.png)

fixed i guess. The wand cape sites i need an ifo form you @septemberWaves
