### ISSUE TITLE
[Suggestion] Kevlar Material

### ISSUE THREAD

**Issue by Spluff5** [GTNewHorizons/NewHorizons#3942]
I imagine Kevlar plates to be used to craft the very high-tier machine hulls in the same way Polyethylene Plates are used for the low-tier ones or used in very high-tier circuits. Although not ultra-expensive, the complexity of the kevlar recipe is hat places the plastic at higher-tier as well as its immense strength compared to other plastics. I've given all the ratios of chemicals in 100's of mB to give an idea of the ratio of ingredients to products but the actual amount of each ingredient used can be changed

**Recipe (Split into stages as it's quite complex)**
Chemical Reactor (CR), Large Chemical Reactor (LCR), Distillery (D), Distillation Tower (DT), Assembly Machine (AM)

### Phenylenediamine
Phenylenediamine (PPD):
- **CR-** 100mB Cholobenzene + 100mB Nitric Acid = 100mB Nitrochlorobenzene Mixture
- **D-** 100mB Nitrochlorobenzene Mixture = 50mB 4-Nitrochlorobenzene
- **LCR-** 144mB 4-Nitrochlorobenzene + 288mB Ammonia =1 Phenylenediamine dust
PPD is a white, crystalline dust

### Terephthaloyl chloride
Terephthalic acid:
- **DT-** Xylene can be produced in the distilation tower from Steam-Cracked Heavy, Light, or Naptha or from Wood Tar. The amount produced is equal to half the amount of Toluene produced (quarter the amount of benzene)
- **Xyelene can also be made in the Distillery-** 10mB Heavy Fuel = 2 mB Xylene, 400mB Wood Tar = 15 mB Xylene, 200mB Naptha = 20 mB Xylene
- _An additional step could be added here to distill pure p-Xylene from the Xylene, increasing the base Xylene cost for production of the final Kevlar plastic_
- **AM-** 4 Long Iridium Rods + 8 Iridium Screws + 32 Fine Cobalt Wire = Cobalt Catalyst
- **AM-** 4 Long Iridium Rods + 8 Iridium Screws + 32 Fine Manganese Wire = Manganese Catalyst
- **LCR-** 100mB Xylene + 400mB Compressed Air + Cobalt Catalyst + Manganese Catalyst = 100mB Terephthalic acid
- _Cobalt and Manganese are a catalyst. Have a stacksize of 0 and so aren't consumed but must be present_
- _Might have to ask some questions about making the Catalyst more accurate to real life. Bromine is used IRL and in GTNH bromine isn't used for anything so could be made into a high-tier material to tier Kevlar properly. There are also many other additives IRL that could be used for tiering_
Terephthalic acid is a light brown fluid

DMT:
- **CR-** 100mB Terephthalic acid + 200mB Methanol = 100mB DMT
DMT/Raw DMT is a dark grey fluid

Terephthaloyl chloride (TCL):
- **CR-** 144mB Chlorine + 144mB DMT = Terephthaloyl Chloride Dust
- _This recipe could use a more realistic chlorinating agent for added complexity like PCl3, PCL5, Phosgene or Thionyl Chloride._
TCL is a light green crystalline solid dust

### Kevlar
Liquid-Crystalline Kevlar:
- **LCR Polymerization-** Terephthaloyl chloride dust + Phenylenediamine dust + 400mB Sulfuric acid = 288mB Kevlar Polymer
Kevlar Polymer is a pale yellow liquid
- _For added complexity/realism, the two dusts could be made into solutions before making Kevlar polymer by mixing them with Pharmasolve in the Mixer. Pharmasolve would have its own recipe chain_
- **Fluid Heater-** Kevlar Polymer = Liquid-Crystalline Kevlar
- _As a liquid crystal, Liquid-Crystalline Kevlar could possibly have a unique fluid texture_

Kevlar Fibers:
- **AM-** 4x Pump (UV) + Fluid Regulator (UV) + 2x Electric Piston (UV) + HSS-E Small Spring + 4x HSS-E Plates + 2x Coolant Cells = Polymer Spinneret
- _Polymer Spinneret is used in place of a mold in the Fluid Solidifier. The voltage of the components, as well as the materials the plates and spring, are made from is a good way to limit Kevlar to the appropriate tier. If raised to a higher tier, could be made in the Assembly Line instead._
- **Fluid Solidifier-** 144mB Liquid-Crystalline Kevlar + Polymer Spinneret = 4x Kevlar Fibers

Kevlar as a material:
- **Chemical Bath-** 4x Kevlar Fibers + 144 mB Molten Epoxy = Molten Woven Kevlar
- _Fibers could possibly need to be woven into a sheet before being Expoxied_
- _Could use a more advanced Epoxy like Glycidylamine Epoxy Resin with its own recipe chain_
- Molten Woven Kevlar can then be solidified into plates or shaped into other components like any plastic.

Feel free to ask any questions about any steps or any ideas about making sure this recipe is only possible at the appropriate tier as well as which steps can be easily added/removed to suit the ideal complexity level. ^_^

**Comment by 0lafe** [comment]
I like it but I have the same problem with pbl as I do here. It uses too many low tier things. It's just basic oil products, combined with some things that don't get used up. Maybe use it as a high tier plastic for EV/IVish, so PBl can go to the LuV+s and get a nice recipe change.

Kind of a problem when we try to keep oil chains for lategame stuff, when most are things you *could* make in LV, just don't have the mold/iridium rods for the catalysts. Could just use crazy eu/ts, but it still feels weird imo.

**Comment by Spluff5** [comment]
Yeah, I understand what you mean. I tried to make it complex so people wouldn't do it until they actually needed the material which kinda tiers it. In the same way you can get chrome at HV even though it's used for much higher tier machine casings. The struggle is that I can't think of a material anything like plastic that isn't just made from oil products since that's what they're made of irl.

**Comment by 0lafe** [comment]
Yeah, that's kind of the gtnh lategame issue. Realism vs tiering. Personal I don't mind if it's just straight wrong. Like this recipe, but it takes plasmas and stuff instead of oil products. Chrome for high tier machines is changing too though, because that doesn't make too much sense in gtnh. Chrome is smeltable pretty early, and comes from Redstone/Ruby also early, with almost pure chrome on the moon. Doesn't make sense for LuV hulls, but osmiridium does ;D

**Comment by Spluff5** [comment]
That is one solution. I tried tiering it with the catalysts but I guess that doesn't use any high tier consumables. Maybe if there was some kind of space-oil that could only be found on a distant planet that all the high-tier plastics were derived from (Kinda like there is on Titan IRL) or maybe plastic-like materials that aren't actually plastic like Carbyne or Graphene. Or possibly scifi materials like Plasteel or Nestene. I kinda do like the idea of the actual casing main material being the thing that his highly locked behind the correct voltage while the plastics just get more and more complex to make.

**Comment by draknyte1** [comment]
Carbyne and Graphemes already exist though? -.^
