### ISSUE TITLE
[Idea] Some High-Tier Materials

### ISSUE THREAD

**Issue by Spluff5** [GTNewHorizons/NewHorizons#3943]
When thinking about what materials would be used in the highest tier machines I had a few ideas. These aren't actual recipes but instead just a little background on some theoretical and scifi materials that could be used. I was inspired by Trinium, Duranium, Adamantium, Naquaddah, Neutronium and Tritanium all being very high-tier

### IRL Theoretical Substances
- **Strange Matter-** Found in neutron stars and made of different quark types than regular matter. Converts everything it touches into more of itself, releasing large amounts of energy in the process. Would probably be made in the Fusion Reactor from Neutronium since they're both in neutron stars
- **Quarkonium-** Found in quark stars, which are like the irl "next tier" of collapsing star after neutron. A material made of solid quarks that would be even denser than Neutronium. Probably made in the Tier IV fusion reactor since Neutronium is made in the Tier III
- **SIS Elements-** Superheavy elements on the periodic table that are found in the "Second Island of Stability. They probably exist from element 126 onwards and would be radioactive but last more than a split second unlike the superheavy elements we are familiar with. Probably made in the fusion reactor."
- **Quark-Gluon Plasma-** A step above plasma where its so hot the protons and neutrons have degenerated into just quarks and gluons, found in only the largest stars. Isn't any particular element. Probably made in high tier fusion
- **Antimatter-** Matter with the opposite charge to regular matter. Explodes when touhing regular matter, releasing massive amounts of energy so must be contained in a vacuum, levitated away from any surface by strong magnetic fields. Make in Cyclotrons IRL but costs massive amounts of energy
- **Bose-Einstein Condensates-** State of matter so cold that atoms lose their individual identity and blend into one amorphous super-atom
- **Positronium-** Electron and antimatter-electron bound in semi-stable arrangement. Can exists for a reasonable amount of time but if destabilised, will collapse and self-annhilate, releasing vast amounts of energy.
- **Cosmic Strings-** 1 Dimensional defects (essentially cracks) in the geometry of the universe. Could be used to stabilise wormholes. Made in the Big Bang so might be able to make artificial ones under similar condictions like a powerful enough Cyclotron.
- **Cosmic Domain Walls-** The 2D eqivalent of Cosmic Strings. Represent a big sheet/walla of space that cannot be passed under any circumstances (possible high tier shielding material or blade?)
- **Menger Sponge-** Theoretical shape with infinite surface area but no volume. would make god-tier catalysts, cooling systems and actual sponges
- **Exotic Matter-** Matter with negative mass. Could be used to stabilize wormholes or build a warp-drive

### SciFi Substances
- **Zybanium-** From Dr Who. Used to shield Time-engines
- **Taranium-** Only found on the planet Uranus. Used as the core of a time accelerating machine
- **Verterium cortenide-** From Star Trek like Duranium and Tritanium. The material that the warp-coils are made out of in a warp dirve. Maybe a coil tier above Naquaddah Alloy?
- **Unobtanium-** Super rare and heavy metal only on distant planets. has Platinum/Osmium/Iridium-like properties so maybe used for Field generator coils
- **Plasteel-** Material with the properties of plastic _and_ metal
- **Vibranium-** Super strong and versatile metal. can withstand any imapact. Radioactive varient called Carbonadium
- **Necrodermis-** Highly advanced self-shaping/healing, living metal from Warhammer 40k.
- **Uru-** Super-durable metal that absorbs magic like a sponge. Must be forged in the heart of a star so maybe needs to be smelted in the Fusion Reactor
- **Nth Metal-** Has the ability to negate gravity and is super strong
- **Xeelee-** Ultra, ultra advanced material that is essentiall space itself folded into a usable material. A race called the Xeelee built their ships out of it. Might require singularies/neutronium and exotic matter to make. Probably one of the most advanced materials in fiction.

Feel free to ask questions to explain any particular one further.
^_^

**Comment by Spluff5** [comment]
I had one idea for an unusual source of material. Blood Magic's _Mark of the Falling Tower_ ritual can be customized to generate meteors containing anything, including materials that can only be exclusively obtained from said meteor. The focus item used to activate the ritual is also customizable so it can be locked into a certain tier. I thought it would be a unique, kinda dangerous and interesting to automate way to get some of the more magic-type end-game space materials like Uru. You could have a high-tier material like Mysterious Crystal be needed to activate the ritual.

**Comment by draknyte1** [comment]
> There's the GT++ isotope maker which could be nice, but it looks like a recolored fusion for the most part.

That’s cause that’s what the COMET looks like IRL, so... it’s what we use in reality to create heavier elements pre-Fusion...

**Comment by bHXDgiuMa5yLHyC8** [comment]
Cosmic strings can be used to catalyze the decay of protons, effectively converting matter directly into energy.

**Comment by Spluff5** [comment]
Oh yeah! forget about that. That would make a mean end-game generator, even better than a Blackhole or Antimatter generator.
