### ISSUE TITLE
Ultimate Lappack uses old item casings

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3944]
2.0.6.2

Ultimate Lappack can only be crafted with the old item casing types
![image](https://user-images.githubusercontent.com/30087707/50458101-e67d6a00-0960-11e9-9734-48c9a06eec9b.png)

**Comment by ko5h** [comment]
[fix in new version](https://github.com/GTNewHorizons/NewHorizons/pull/3927/commits/4f315dfa9385a1246680366973b46ada23ad03d6#diff-2ff2eb830c6519653bb641fcac15fcf1R100)
