### ISSUE TITLE
Suggestion: Modify SMD Diodes

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#3945]
#### Modpack version
2.0.6.1
#
#### Description of suggestion
I'm sure most players would agree that by far the most annoying vital resource to obtain in the early-to-mid game is gallium. It has no good source from any early ore veins, only becomes a byproduct from a primary or secondary ore once you reach the moon, and is vital for most circuits you make after the LV age because of its use in diodes.

Diodes are where I have an issue, because the amount of gallium arsenide required to make the first available diodes compared to the later SMD diodes seems to be unbalanced. In every other case the SMD equivalent of a circuit component is an improved recipe. This is not the case for SMD diodes (platinum isn't expensive in such small quantities, the problem is just the gallium arsenide).

The ordinary diodes can be made as follows (with the best use of gallium arsenide):
1 AsGa dust ==> 4 small AsGa dust ==> 4 silicon boules ==> 64 wafers ==> 256 diodes

Considering this, it's obviously less than ideal that the same amount of gallium arsenide dust used to make SMD diodes only produces 32, a 12.5% yield by comparison. The SMD diode recipe is much simpler of course, but I imagine most players won't mind a bit more complexity if it means they can spend 1/8 as much time going through the nether excavating every available sulfur vein to get hold of as much sphalerite as possible. I suggest rebalancing these recipes somehow; the simplest way I can think of is to make 32 SMD diodes require a tiny pile of AsGa dust rather than a full-size pile, making the yield per AsGa become 9/8 rather than 1/8 compared to the other method; that, or have the SMD diode recipe use a small pile of AsGa dust with twice the current amount of platinum, and produce 64 diodes (meaning the recipe gets simpler but AsGa produces the same amount of diodes).

**Comment by Anarack** [comment]
You know you can skip smd diodes till they are hard required in nano tier and above circuits, by that point you most likely on the moon which at that point gallium becomes fairly cheap. see #3455 for gallium sources and previous arguments, it is much more plentiful that you think it is and if gallium is such a issue use circuit paths to minimize your gallium use.

But in total you should not need more than a few gallium dust to get to HV.

**Comment by Dream-Master** [comment]
and it can generated with 7 buckets of xp

**Comment by Dream-Master** [comment]
but maybe I have to check the balance between smd and regular ones

**Comment by richardhendricks** [comment]
HV macerator helps a lot with gallium production from zinc and sphalerite, per #3455.

Also, IC2 crop Galvania will 4X zinc or sphalerite. I have added a new info quest on how to get more gallium.

Maybe we can change the recipe to give a few more output.
