### ISSUE TITLE
Magnalium Recipe Bug

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/NewHorizons#3946]
#### Which modpack version are you using?
2.0.6.2
#
#### Description of issue:
Crafting magnalium dust in a mixer consumes the component dusts in the wrong ratio. The recipe should consume one magnesium dust and two aluminium dust to produce three magnalium dusts; instead it consumes two magnesium dust and one aluminium dust.

**Comment by Dream-Master** [comment]
ok will check
