### ISSUE TITLE
Molten redstone cant be used in filters

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3947]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 

#Epsilon
#### What did you try to do, and what did you expect to happen?
set up a fluid filter for molten redstone
#
#### What happend instead? (Attach screenshots if needed)

firstly i could not fill a IC2 cell with molten redstone in a TH tank, needed fluid canner so that recepie is missing

then i can not use  molten redstone in the filter funktion of ender fluid conduit.
tried the gregtech fluid filter cover but it does not work there either

#### What do you suggest instead/what changes do you propose?
 missing recepie? easy fix?

**Comment by Dream-Master** [comment]
good question what is so special on molten Redstone?

**Comment by Ghengis88** [comment]
can not be used in AE2 filtering either

**Comment by Ghengis88** [comment]
something must have changed becous we have molten redstone in a existing ae2 filter but i cant make a new one...

**Comment by Dream-Master** [comment]
@Ghengis88 in wich version it changed ?

**Comment by Ghengis88** [comment]
dont know, the oni in our base has been there for a very long time

**Comment by Dream-Master** [comment]
there are 2 fluids. redstone.molten and molten.redstone. One is wrong

**Comment by Dream-Master** [comment]
oh ok one is from tico the other from gt @Ghengis88

**Comment by Ghengis88** [comment]
how do i find the difference? or get the diffrent fluids?

**Comment by Dream-Master** [comment]
look at tico smelterry and molten gt redstone

**Comment by Ghengis88** [comment]
NEI says redstone in tico is named liquid redstone. but maby the file name is redstone.molten

**Comment by Dream-Master** [comment]
as i said there is moten.rdestone and redstone.molten

**Comment by boubou19** [comment]
to know the fluid name put the fluid into a drum it will gives you the name.

**Comment by Ghengis88** [comment]
this 

![image](https://user-images.githubusercontent.com/25811344/50541084-62b0c100-0b9e-11e9-9916-4e3013de8c92.png)

Gives

![image](https://user-images.githubusercontent.com/25811344/50541081-56c4ff00-0b9e-11e9-847e-e77a4c39221c.png)

and that is what i put in a tank

![image](https://user-images.githubusercontent.com/25811344/50541094-87a53400-0b9e-11e9-8264-290b64f6d78e.png)

and the cell won't fill

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/50541114-d4890a80-0b9e-11e9-8cd4-0d2793e15ead.png)
 this cell
