### ISSUE TITLE
Venus subsurface block

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#3949]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
sort with ore dictionary bus
#
#### What happend instead? (Attach screenshots if needed)
Venus subsurface block has no ore dictionary name
#
#### What do you suggest instead/what changes do you propose?
add ore dictionary name

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/50560018-999ce900-0cfc-11e9-93e2-7a82f8c9d785.png)

**Comment by Dream-Master** [comment]
will check
