### ISSUE TITLE
Ender IO Alloys energy requirements

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#395]
Need to be turned back to vanilla Ender IO requirements or do it in some other machines because basic machines have a cap of 20 RF/T.
First alloy you make is Redstone alloy which needs 500,000 RF so doing one operation would take a lot of time. And you need a lot of all of the alloys.
So id suggest either using vanilla Ender IO recipes or if you want it harder - double the vanilla energy requirement.

**Comment by Namikon** [comment]
Aren't they available in the EBF as well ? I know the higher tier ones are

**Comment by Dream-Master** [comment]
Will add it to the ebf later. Maybe only the Glass can made with the alloy smelter. Or we add a new machine in ft code with 3 or 4 inputs.

**Comment by Dream-Master** [comment]
Or Chemical Reaktor recipes would be possible too.

**Comment by Dream-Master** [comment]
@Drobac 
@Namikon 
Did all Ender IO machine have a cap at 20 RF/t?

**Comment by Drobac** [comment]
i vote dusts in the mixer. They have a cap at 20 with no capacitors, with the capacitors im guessing the cap is higher. But you cannot get higher without the basics

**Comment by Namikon** [comment]
I also vote for mixer. Keep the EBF input slot for Oxygen only please

**Comment by Drobac** [comment]
what i would suggest is that you lower the energy requirements in the alloy smelter so that yyou can still use that machines for the alloy but also add a mixer into EBF recipe as the blast furnace can be upgraded so the speed is quite fast

**Comment by Dream-Master** [comment]
No i have a new Plan. You can make the dust as Shapeles recipe or for automation in a Mixer (8 EU 100 ticks maybe)
Than you can put the Dust in the EBF to make Ingots.

**Comment by Dream-Master** [comment]
Reopen the Issue if necessary.
