### ISSUE TITLE
Olivine blocks aren't oredicted as peridot blocks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3952]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to place olivine blocks into a neutronium compressor to make the peridot singularity.
#
#### What happend instead? (Attach screenshots if needed)
it doesn't work because it only accepts peridot blocks in the recipe.
#
#### What do you suggest instead/what changes do you propose?
I suggest to oredict olivine blocks as blockPeridot because you can turn olivine into peridot and vice versa with a chisel. Also according to @Technus in #1488:
> Olivines are Peridots with asteroid origin iirc.

**Comment by bartimaeusnek** [comment]
Wikipedia says to this:
>Peridot is gem-quality olivine,

 so i approve this.  @Dream-Master are you okay with this?

**Comment by Dream-Master** [comment]
sure
