### ISSUE TITLE
Remove the BM restorer plz

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3953]
#### Which modpack version are you using?
2.0.6.3
#
#### What do you suggest instead/what changes do you propose?

Remove the BM restorer. We got the thaum one, so restoring stuff isn't a problem without it. It's only use is basically free stuff. It can also crash/corrupt your world, which doesn't seem like an item that should be in the game. It pretty much negates most GT crafting, which seems like something kind of central to the pack 

Sorry, LIFE infuser

**Comment by DoomSquirter** [comment]
wtf is a bm restorer?  I don't see it in nei.

**Comment by 0lafe** [comment]
Bloodmagic restorer

**Comment by DoomSquirter** [comment]
lmao

yes.  I understood bm meant bloodmagic.  what kind of idiot do you think I am?  I can guarantee you my idiot level exceeds that, knowing that bm=blood magic.  altho I was starting to think it meant bowel movement, but I did get lucky and just type restor in nei and I still don't see it

**Comment by DoomSquirter** [comment]
you're thinking of life infuser

**Comment by Anarack** [comment]
See #2834 for examples and amusement.

**Comment by Anarack** [comment]
we blacklisted all gt items, and we have it forked already. https://github.com/GTNewHorizons/BloodArsenal
