### ISSUE TITLE
Quest Food 2.0 can't be completed

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#3955]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private Mp
#
#### What did you try to do, and what did you expect to happen?
Complete Quest n°1178 "Food 2.0", chapter T4 HV
#
#### What happend instead? (Attach screenshots if needed)
Can't complete first task, need tin item casing from IC² but GT version only available.
#
#### What do you suggest instead/what changes do you propose?
Fix the quest :) Replace by **gregtech:gt.metaitem.02:18057**

![2019-01-06_00 03 38](https://user-images.githubusercontent.com/17729817/50730200-bb0c3380-1147-11e9-84cc-7a3aaca6a822.png)
![2019-01-06_00 03 46](https://user-images.githubusercontent.com/17729817/50730201-bc3d6080-1147-11e9-9389-dd23162f4bd1.png)

**Comment by Dream-Master** [comment]
will change yes
