### ISSUE TITLE
Hazelnut Wood not working to make heavy oil in pyrolyse oven

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3956]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I made a Hazelnut tree farm for both saplings and wood in order to get both biofuel and heavy oil. However, you cannot use the Hazelnut wood in a pyrolyse oven to get heavy oil for some reason, despite other types of wood working fine (It's called Hazel Wood ingame)

**Comment by Dream-Master** [comment]
is it oredicted? @WizardSleve280

**Comment by Dream-Master** [comment]
logWood or so?

**Comment by WizardSleve280** [comment]
it is, but there is still no option for it in the oven to make heavy oil
