### ISSUE TITLE
Endium Blocks cannot be broken back down into ingots

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3957]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Self explanatory, would like to see a recipe or two that allows you to break the blocks down back into the ingots like any other metal block (fluid extractor, alloy smelter, etc)

**Comment by Dream-Master** [comment]
Will check

**Comment by bartimaeusnek** [comment]
I guess thats a OreDictionary issure. @Dream-Master
