### ISSUE TITLE
Witching Gadgets armors not working with soulbound

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3958]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
The vambraces or other armor types from Witching Gadgets do not stay on your person, despite having soulbound on them when dying

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
they are used in the baubles slots... hacky implementation and dunno what i could do there...
