### ISSUE TITLE
Passive Fishcatchers (Gt++) should be buffed

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3959]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Currently, if you want to use fish catchers (the gt++ ones) passively in order to get biofuel, you need thousands of ingots of iron in order to get enough fish. I personally have made an 11x15x11 (x,y,z) structure of both fish catchers and water and even with 504 fish catchers (which is 4032 iron), i cannot keep up with my distillation tower in terms of processing methanol into biofuel, which is running with hv power, aka the minimum power tier to get biofuel. I think that there should be some sort of buff to the catchers so that you can both save on space and materials required to keep up with a distillation tower that makes biofuel. This buff could be either a simple double or triple increase to the rate of products produced or some sort of increase in products produced when more fish catchers are located closer together

Another solution that would work but might cause issues in other areas would be to increase the amount of oil per fish that you extract

**Comment by draknyte1** [comment]
Or just make some Multiblock Fishing Ponds instead?.. the single blocks got nerfed ages ago when the multi was introduced.

**Comment by WizardSleve280** [comment]
Multiblock is broken, so cannot use the multiblock for fish generation: https://github.com/draknyte1/GTplusplus/issues/336

Also, there is no voltage description in nei for the multiblock, aka the minimum voltage required for it to run

**Comment by draknyte1** [comment]
There isn’t a minimum voltage. It scales on input from 1-infinite.

**Comment by WizardSleve280** [comment]
Even if we do not buff the speed of the fish catchers, there still should be a buff to the amount of oil produced from each fish. Currently, in an lv chemical reactor, the recipe time and quantity to make one batch of biofuel is 6 buckets of fish oil every 20 seconds, or 6000 mb. One non-vanilla fish produces 50 mb per fish, meaning that in order to keep up with an lv chemical reactor you would need to produce 120 fish every 20 seconds, or 6 fish per second. (6000/50=120, 120/20=6) If I were to use hazelnts, which produce 150mb per nut, I would only need to produce 40 nuts every 20 seconds, or 2 nuts a second. Seeing as there is an option to make biodiesel out of both types of oil, each type should be equally as useful in comparison to the other. However, when fish are both harder to obtain and produce less oil than seed oil, there is little if not zero reason to use fish oil over seed oil

**Comment by richardhendricks** [comment]
There is no need for a buff.  Increasing fish output is trivially easy. Breeding up to decently producing hazelnuts and setting up infrastructure takes a lot of time and effort.

Plus there are lots of other useful/beneficial outputs from fish catchers such as diamonds and emeralds, and nuggets.

Also, most Pam's fish actually produce more oil than vanilla MC fish.

There is no reason to "require" the input speed to keep up with or match an LV chemical reactor.  The fish catcher is 100% free once started, so I don't think a buff is necessary.

**Comment by WizardSleve280** [comment]
I talked about the ability for a given setup to keep up with an lv chemical reactor as a baseline for any setup because otherwise, it would be harder to put both the speed and the scale of what would be needed into perspective. 

Also, the only real way to actually collect fish on a large enough scale is to use fish catchers since the multiblock does not work and is too expensive for what it does. If you want to actually keep up with a simple lv chemical reactor, you would need to either make two multiblocks using hv power or one multiblock using ev power which is a waste of materials, time and space. The other option to use fish is to set up hundreds upon thousands of the passive fish catchers which also takes quite a lot of time and space to set up. On the other hand, in order to use seed oil, all you have to do is just spend time breeding trees until you reach a butternut (which is the equivalent of breeding an industrious bee and more effective than hazelnut) or hazelnut and set up a forestry farm with five trees in it and can be powered by the byproducts from the system. 

Even though just outright increasing the output on passive fish catchers would create other problems, there should still be a buff to the amount of oil produced from fish. One reason is that you have control over how much oil can be produced from seeds by means of breeding better trees and the speed at which they mature, while with fish you are bound to the rng of what the fish catchers produce and what fish you get. 

So, if you want to use biodiesel for power, you could either spend 6k iron on passive fish catchers or 100 chrome and niobium for fish oil or just spend time breeding up to a good tree and set up a couple of forestry farms to harvest the nut. From a material, time, and sustainability standpoint, seed oil is the obvious choice. If you were to buff the amount of oil produced by the fish, then there would not be such a blatant gap in the effectiveness of seed oil vs fish oil

**Comment by draknyte1** [comment]
Kinda buffed them here - https://github.com/draknyte1/GTplusplus/commit/457c954a561f8b6e77ac911e805e5704bd5c6077...

Also made the tooltips mildly more informative. Besides the Niobium, it’s not that expensive at late MV/early HV.. which is where it’s intended for tier wise. If not slightly later~ I’ll fix it’s formation later today after I finish work on my current tidbits.

**Comment by richardhendricks** [comment]
BTW, vanilla fish are slightly worse than the Pam's fish (except for one). 

Anyways, I guess we can boost the output oil per fish.
