### ISSUE TITLE
Additional Recipe required

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#396]
Please add an additional recipe for the Dispenser, that doesn't require a bowstring from Tinkers, as it can't be automated

**Comment by Dream-Master** [comment]
Maybe i can adding the Bowstring be made in Extruder with a Tinkers Form.

**Comment by Dream-Master** [comment]
Will added the missing Cast to the Core Mod.

**Comment by Dream-Master** [comment]
Added https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/aa4d420f5671a338b71fa9d70cbf2ee84a8da217

**Comment by Namikon** [comment]
A metal cast for a bowstring? Also, you still need an entire machine just for one single recipe then. I'd be glad if we could reuse existing machines a bit, instead of adding more and more different recipes, that require slightly different setups or lenses or casts. You can't automate the cast/circuit/lens in the machines, so you need one dedicated machine for each circuit number (15), one for each lens (7). And that multiple times, as there are way more than the usual 27 recipes one machine can do at a time

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/11070913/3c83881a-87de-11e5-810b-8e99a8805a21.png)

![image](https://cloud.githubusercontent.com/assets/2970688/11070923/4ef3c78a-87de-11e5-9219-cee4d8e914bc.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/11070928/5adbddf8-87de-11e5-9844-717c2ce52a96.png)
![image](https://cloud.githubusercontent.com/assets/2970688/11070931/607498b8-87de-11e5-9517-a5f4418a5d16.png)
![image](https://cloud.githubusercontent.com/assets/2970688/11070936/66a4fafc-87de-11e5-8fa5-bef47b4bbe91.png)

**Comment by Namikon** [comment]
So it's a normal string now? Without description it's rather difficult to see what has changed

**Comment by Dream-Master** [comment]
Yes it is.
