### ISSUE TITLE
None of the Gt++ casings can be broken down into their original components

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3960]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Don't know if this is fixed in any of the newer versions of GT++ but none of the multiblock casings for things like the ore washer or electrolyzer cannot be broken down into their individual ingots (Grisium and Talonite for the ore washer, and Potin and Chrome for the electrolyzer)

**Comment by Dream-Master** [comment]
@draknyte1 any idea?

**Comment by draknyte1** [comment]
Recycling is only supported by items crafted using GT materials. Since my Materials are independent of GT, they don’t get reverse recycle recipes. Like arc smelting or laceration to correct dust types. 

This won’t ever change or be ‘fixed’, it’s intended behaviour.
