### ISSUE TITLE
No machine automated recipe for Iridium-Tngstensteel Reinforced Blocks

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3961]
#### Which modpack version are you using?
2.0.5.2
#
#### If in multiplayer; On which server does this happen? 
Delta
#
There should be an assembler recipe for making these blocks instead of needing to use a hammer, seeing as the recipe is ev+ tier
<img width="708" alt="screen shot 2019-01-05 at 10 24 07 pm" src="https://user-images.githubusercontent.com/19292440/50731672-aaa08c80-1138-11e9-8471-f2483f5496fb.png">

**Comment by Dream-Master** [comment]
yes need to add that

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51084280-4af14500-1727-11e9-9ecf-639896571cf8.png)
