### ISSUE TITLE
(item) casings not triggering quest completion

### ISSUE THREAD

**Issue by Beyond-Veil** [GTNewHorizons/NewHorizons#3963]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
quests that require item casings never seem to complete (happens on bronze / steel at least)
#
#### What happend instead? (Attach screenshots if needed)
quest never completes item casings are not detected
#
#### What do you suggest instead/what changes do you propose?
probably a dict issue? clicking on the item casing in the quest brings you to the corresponding gregtech casing, but having that casing does not trigger quest completion. had it happen a few time in the forestry branch with bronze casings and currently with  quest#717 which involves steel casings

may be related to issue #3874, but impact seems to be wider than that.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/50741012-f0705a00-11f7-11e9-8e3d-9281d4584f2e.png)
guess it is fixed allready

**Comment by Ultimoos** [comment]
This problem appear on #559 and #562 as well. Requirements ask for industrycraft2 casings instead of gregtech ones.
