### ISSUE TITLE
[suggestion] Hull change LuV-UEV

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3964]
#### Which modpack version are you using?
2.0.6.2
#
#### What do you suggest instead/what changes do you propose?
The hulls right now use materials about 2 tiers below the tier of the hull, which I find a little strange. Here's the old recipes/what I suggest. 

LuV hulls use chrome, something you get in LV/MV, and get in huge amounts in EV. It's an MV ebf recipe, and don't make sense. 

Zpm uses iridium, a little better but still seems to be 2 tiers behind zpm itself, with iridium ore coming from the T4 which is IV ish. The smelting recipe is IV, and still a little weird for a zpm hull. 

UV uses osmium. Pure ore comes from T5 I think. The smelting recipe is LuV. 

UHV uses Nt, which is probably the best here, but still a little weird considering it's more a UV material, only taking zpm to make though. 

UEV uses bedrockium which is pretty much free after you get the DD. 

I suggest changing LuV to osmiridium. An LuV smelting recipe, with materials coming from T4/5 rockets. Also use 576L PTFE instead of plastic. 

Zpm to naq alloy, a zpm smelt recipe coming from trinium which is ZPM ish. Also maybe 576L PBl for the plastic

UV to Nt because it's the most UV thing out there. Made to start UV, as well as made easier with the UV fusion reactor. 1152L PBl too, for the plastic 

UHV to cosmic neutronium. Used to make the parts for UHV, is made in UV but fairly difficulty. 2304L PBl too because plastics

UEV to infinity. It's the last tier we have parts for, so why not go all out. You only need hulls at this point for power stuff really, and with the 16 and 64A transformers, this means you can run 500M eu/t through a single power line, which seems fair imo. Also 4608L PBl because plastics. 

Also recommend removing the hulls past UEV, mostly because we don't need/use them. At least remove the recipes for now. Only thing that could is the really ultimate battery which uses the UMV bat buffer, but with the GT++ storage multi this is less important. If there's some way to find a synergy between them, it would be even better.

**Comment by DualBallers** [comment]
Currently it's possible to make battery buffers and transformer in tier(s) that are higher than your current energy hatch tier. This option helps a lot when overclocking the EBF to reach higher tier/faster smelting earlier.

Will this play-style be removed if hulls are also gated to your current max tier?

**Comment by bartimaeusnek** [comment]
In vanilla GT, Chrome was choosen because it originally came from Redstone/ruby (with no chrome ore), iridium came only from Platinum Group Sludge dust so did Osmium, which was a energy and time consuming processing.

Changing core mechanics will lead to inconsitency with our GT branch and Addons like GT++, bartworks, and basically anything thats coded for vanilla GT.

I do not support this proposal for the reasons written here. 

Instead of changing some core mechanics of GT (i.e. hull materials) i'd suggest re-tier the pure ores instead, if changes are made.

**Comment by richardhendricks** [comment]
Are these changes in the hatch "paradigm" going to be covered in quests? At least the hatches that change how they need to be made should have quests discussing what needs to be done differently.

**Comment by Dream-Master** [comment]
We can change chrome use a better coil in ebf ? Or replace the pure chrome ore with other ones.

**Comment by 0lafe** [comment]
Except chrome is used in HV too. The pure ores are nice because other than the LuV hull it's not really used anymore, so it makes HV parts easier in EV+. You'd need to push CrO2 past T5 rocket, just to accommodate one LuV recipe. Seems much easier to use an LuV material. 

>Are these changes in the hatch "paradigm" going to be covered in quests? At least the hatches that change how they need to be made should have quests discussing what needs to be done differently.

I guess, but it's LuV+, and don't quests stop at LuV? There's not a hull quest I don't think, and if anyone tries to make an LuV hull based item they'll see the new one.

**Comment by DoomSquirter** [comment]
so sorry to be an asshole here but...

can we first get a stable 6.x build, then new shit gets thrown into the mix?

it'd be nice to acclimate to the newest version and let the current hatch stuff get put into play, officials using it, etc, then have more ppl that can talk to the effects good and bad to more changes?

**Comment by Spartak1997** [comment]
@Dream-Master maybe I can change recipes
![2019-05-15_23 37 13](https://user-images.githubusercontent.com/29407630/57809195-a848e180-776d-11e9-8d71-5a90e5ce36b7.png)
![2019-05-15_23 37 15](https://user-images.githubusercontent.com/29407630/57809196-a848e180-776d-11e9-8cfc-56c8ad197038.png)
![2019-05-15_23 37 18](https://user-images.githubusercontent.com/29407630/57809197-a848e180-776d-11e9-9e89-91569b8ff9e7.png)
![2019-05-15_23 37 20](https://user-images.githubusercontent.com/29407630/57809198-a8e17800-776d-11e9-9ba6-354a0df9af2b.png)
![2019-05-15_23 36 52](https://user-images.githubusercontent.com/29407630/57809199-a8e17800-776d-11e9-84d6-b8ea68402d03.png)
![2019-05-15_23 36 54](https://user-images.githubusercontent.com/29407630/57809200-a8e17800-776d-11e9-8720-22678d2effdf.png)
![2019-05-15_23 37 01](https://user-images.githubusercontent.com/29407630/57809201-a8e17800-776d-11e9-8b19-1ad7f246634e.png)
![2019-05-15_23 37 03](https://user-images.githubusercontent.com/29407630/57809202-a97a0e80-776d-11e9-8ff0-f085f0dc0e5d.png)
![2019-05-15_23 37 08](https://user-images.githubusercontent.com/29407630/57809203-a97a0e80-776d-11e9-9099-dcdd85720b94.png)
![2019-05-15_23 37 09](https://user-images.githubusercontent.com/29407630/57809205-a97a0e80-776d-11e9-8058-02bba68f9b6b.png)

**Comment by bartimaeusnek** [comment]
@Spartak1997 


> Changing core mechanics will lead to inconsitency with our GT branch and Addons like GT++, bartworks, and basically anything thats coded for vanilla GT.
> 
> I do not support this proposal for the reasons written here.
