### ISSUE TITLE
Pam's Bowl dupe

### ISSUE THREAD

**Issue by plaguewolf** [GTNewHorizons/NewHorizons#3965]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
N/A, SSP
#
#### What did you try to do, and what did you expect to happen?
Craft 4x Pam's 'Heavy Cream' from 4x Pam's 'Fresh Milk' with a total of 4 Bowls.
#
#### What happend instead? (Attach screenshots if needed)
Craft 4x Pam's 'Heavy Cream' from 4x Pam's 'Fresh Milk' (made from 1x Bucket of Milk) with a total of 4 Bowls. Ended up with a fifth bowl..? Each time I crafted a 'Heavy Cream' it dropped a(singular, even though I put in a stack of 4) bowl, like buckets do when you craft with them, except buckets wont stack like bowls.
#
#### What do you suggest instead/what changes do you propose?
Dunno, its minor, relatively, just wanted to bring it to the attention of pack devs. Feel free to close this whenever.

**Comment by Dream-Master** [comment]
I cant reproduce it. The oly thing happend that my bowls are consumed if i put the in stacked. @plaguewolf 
show me the recipes which rrored out. Thanks

**Comment by plaguewolf** [comment]
https://www.youtube.com/watch?v=iWaZxUU-BV8

Yeah, the stacked bowls are consumed, which shouldn't happen but i think that's a Pam's bug.
The video above shows that you only ever need one bowl to craft bowled ingredients from Pam's stuff(not yet tested, because i derped and forgot, but assuming that's whats going on).
It should be consuming the bowl, since the cream is in the bowl, but instead the cream seems to produce its own bowl ex nihilo, and you get the bowl back.

Really minor, and probably not actually worth anyone's time, but its one of those things that made my brain itch. Triggered, i guess.
