### ISSUE TITLE
Crash with almost every Optifine version + fastcraft 1.2.3/1.2.5

### ISSUE THREAD

**Issue by Volarity** [GTNewHorizons/NewHorizons#3967]
#### Which modpack version are you using?
2.0.5.1

#### What did you try to do, and what did you expect to happen?
Tried to launch a game with Optifine D6 and fastcraft 1.2.5

#### What happened instead? (Attach screenshots if needed)
Crashed upon loading a world. I then tried almost every optifine version with either fastcraft 1.2.3 or 1.2.5, but I still get the same crash when loading a world.

I used to be able to run Optifine + Fastcraft a few months before on the Twitch launcher using the same modpack version, but after using the Technic Launcher, I started crashing. Don't know if that's the reason or not though.

[crash-2019-01-05_00.07.47-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2731489/crash-2019-01-05_00.07.47-client.txt)

**Comment by Volarity** [comment]
Yeah, and I've tried newer versions of Optifine w/ Fastcraft 1.2.5. Here's a crash report for that:
[crash-2019-01-07_00.05.07-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2731868/crash-2019-01-07_00.05.07-client.txt)

**Comment by Volarity** [comment]
Well, sorry to ask, I guess? I asked here since I have no idea how to fix this problem, and thought that the github was the correct place to ask questions. 

If I could get any help, that'd be wonderful, but if I'm in the wrong, I'll stop asking.

**Comment by bartimaeusnek** [comment]
A: dont use Optifine but use fastcraft 1.23
B: remove fastcraft but use Optifine (any version)
C: use fastcraft 1.25 + Optifine E7? E3? some of the E variants did work... maybe... you will need to test that...

well thats all we can say here, since fastcraft and Optifine are both closed source, we cant modify either. i guess thats all to say here...

**Comment by SpwnX** [comment]
i just had this problem and @bartimaeusnek C option worked for me, FC 1.25 and OF HD_U_E7

note that fastcraft version provided by the modpack is outdated for some reason (1.23)
