### ISSUE TITLE
Problems with crossbreeding industrious bees.

### ISSUE THREAD

**Issue by Rostisha** [GTNewHorizons/NewHorizons#3968]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Crossbreed Industrious bee and Peat\Demonic bee to get coal bee/redstone bee. I tried it with 9 Electrical Stimulators in alveary with 4x Mutation Circuits... Also tried with creative "Nova Frame" in apiary and alveary. Also raised coal bees' mutation chance to 100%.. These mutations require blocks under hive, I always put them. Strange that I easily made, for example, cuprum bees. So I have this problem only with two species.
#
#### What happend instead? (Attach screenshots if needed)
No mutations for many attempts.
#

**Comment by bartimaeusnek** [comment]
The Bee system changed drastically in 2.0.6.X, so i guess nothing we can do here...
