### ISSUE TITLE
Removed Mod: OpenPeripherals

### ISSUE THREAD

**Issue by NikitaGamer64** [GTNewHorizons/NewHorizons#3971]
#### Which modpack version are you using?

2.0.6.2
#### What is your problem?

OpenPeripherals Mod removed
#### What happened then?

All features with external programming and else are removed too 
#### What do you suggest in this case?

Maybe there is an alternative feature somewhere in the other part of the modpack? Or maybe you should add that if you don't have?

**Comment by Dream-Master** [comment]
@NikitaGamer64 we removed the mod because we had a couple of issues. If you have any idea of a new or different mod let me know.

**Comment by NikitaGamer64** [comment]
That was my question if you have any idea of a replacing mod. Or maybe in OpenComputers there's a feature that allows you to work with peripherals?

**Comment by repo-alt** [comment]
What exactly peripherals are you missing? Last time I looked all the necessary adapters were already present either in OC itself or in Computronics.

**Comment by NikitaGamer64** [comment]
I don't seem to master all peripherals in OP, so I can't tell which of them are missing in OC and Computronics.

**Comment by repo-alt** [comment]
What is your problem then?

**Comment by NikitaGamer64** [comment]
Whaddya mean what's my problem? Are you annoyed or something? :/

**Comment by Methes** [comment]
Dude. You issued a problem with mod removed, claiming you miss some of its functionality. Yet you aren't able to specify what exactly are you missing now after being offered alternatives in the pack. There's nothing more anyone can do for you until you figure out what you want.
