### ISSUE TITLE
TecTech missing assembly line crafting items

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#3972]
2.0.6.2

The assembly line recipe for the TecTech Quantum Computer misses an item.
(to see the recipe I cheated the computer in, as the data stick recipe can't be made in the scanner)
![image](https://user-images.githubusercontent.com/30087707/50857302-796cca00-138d-11e9-89ae-7bd46a6bf0bb.png)

Looking at the item in the code
`  GT_OreDictUnificator.get(OrePrefixes.wireGt02, Materials.Superconductor, 8),`
it looks like the Matter Junction, Matter Quantizer, and Matter DeQuantizer uses the same item type, and also misses this item (last item in the stack)

![image](https://user-images.githubusercontent.com/30087707/50858215-16c8fd80-1390-11e9-953e-37fb0590510d.png)
![image](https://user-images.githubusercontent.com/30087707/50858235-21839280-1390-11e9-98cb-80953ac705e0.png)
![image](https://user-images.githubusercontent.com/30087707/50858267-34966280-1390-11e9-9342-ac8a0ae8fd99.png)

**Comment by Dream-Master** [comment]
@DualBallers load up this version and test again. Thanks
http://jenkins.usrv.eu:8080/job/Tec%20Tech/56/

**Comment by 0lafe** [comment]
The really ultimate battery has a bit of an issue too, as well as some other assembly line crafts

**Comment by DualBallers** [comment]
@Dream-Master no changes to the recipes with that build, and the scanner recipe still fails.
(just to be sure - I just replaced the jar in the mods folder)

**Comment by bartimaeusnek** [comment]
i think we need to re-route Superconductor to SuperconductorUHV to provide addon compability.
Ill make a PR

**Comment by bartimaeusnek** [comment]
fixed
![2019-01-09_03 16 32](https://user-images.githubusercontent.com/33183715/50871768-fd8a7600-13bc-11e9-8c73-37e7830749c6.png)

**Comment by DualBallers** [comment]
Does this also fix the scanner issue #3859 ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51084092-d6b5a200-1724-11e9-994f-41a6d4ddf287.png)
