### ISSUE TITLE
[balance] nether star for farming golem?

### ISSUE THREAD

**Issue by Beyond-Veil** [GTNewHorizons/NewHorizons#3977]
#### Which modpack version are you using?
2.0.6.x

I understand it is quite easy to build golems and therefore push farming quite fast. However, the current "harvesting" golem command requires nether stars which effectively pushes it in EV territory. Considering forestry farms are more or less "trivial" to build in MV and Steve's carts in the same timeframe, the disparity is pretty great. This is not even considering to even get there one needs to defeat the lich at least twice, build 3 wands (requiring late MV equipment for stainless steel), build infusion altar, do all the thaumaturgy research, etc.

Is there maybe a way to get harvesting golems to late MV / early HV and not break the game?

Same pretty much goes for the fishing golem. With a bit of steel/iron and some tin pipes you can make a pretty effective fish farm early MV that outfishes over a dozen golems (except for the echanted treasure)

**Comment by richardhendricks** [comment]
The reason these golems require nether stars is that there is zero upkeep/cost for them once they are made.  All the other lower tier harvesting options require continuing upkeep or EU payments.

**Comment by richardhendricks** [comment]
Nether stars can be achieved in MV/HV at the latest. You can build reinforced obsidian to hold the wither, and a powered spawner to spawn wither skeletons in the Nether (or hunt wither skeletons in fortresses, or setup a vanilla wither skeleton farming setup in a fortress intersection)

**Comment by Dream-Master** [comment]
You can kill the wither multiple time in steam/lv age with the trick to get the wither stuck in the ceiling. I dont see any reason for lowering the core recipe for non of the Golems.

**Comment by Beyond-Veil** [comment]
Thanks for the reply. As to the obtaining it early, yes i agree, but effort <> reward for continuously spawning the wither is relatively low as a single kill is needed for each golem.

You can only dupe lich bones with a HV assembler (which would push out all other magic well into HV as well), bees could be done i guess, but without the gentech really a lot of effort :)

As to the maintenance, i guess so. On the other hand, an automated farm can run on a basic LV generator with a single biodiesel charge for a real-time week or so, and the steve carts can be made to auto-run on the harvested materials / solar (MV). Although you need to change the sawblade once in a while

Compared to these alternatives the effort to obtain a few golems seems a bit excessive, but i understand that balancing for a lot of scenario's can be an issue.

**Comment by DoomSquirter** [comment]
you need HV to do infusion anyways.  for runic stone blocks

killing withers becomes really simple after the first couple hard ones and as dream said, you can cheese it up at bedrock level real easilly as soon as you have access to nether.

tbh, I'm glad that dream has only gated it mostly behind nether stars and not something worse.  please don't give him ideas :)

I for one think it's gated just fine as it is.  I have a pretty decent crew of golems doing my treefarm atm.  the one really nice advantage of golems over say farming stations, is that the golems are pretty scalable and don't cost anything for upkeep.  as I want more trees farmed, I add more golems to same 4x tree plots that I have setup (all set for 2x2 spruce).  I don't need to increase the size of the farm.  just add more workers.  I know that will top out at some point but not within the realm of what I'll need it for.

**Comment by richardhendricks** [comment]
>As to the maintenance, i guess so. On the other hand, an automated farm can run on a basic LV generator with a single biodiesel charge for a real-time week or so, 

Sure, and that's all *infrastructure* with *costs* and time to implement.  A golem is free, forever.

>and the steve carts can be made to auto-run on the harvested materials / solar (MV). Although you need to change the sawblade once in a while

Again, infrastructure (figuring out how to use that steve's cart cargo manager seriously gives people gray hairs) and recurring costs (sawblade) is exactly why those are low tier entry level and things like the Enderio Farming Station and IC2 harvester and harvesting golems are higher tier. "Changing the sawblade" is exactly the point.  If golems needed essentia or vis to work or work fast or whatever, then lowering their tier is justifiable.

The fish catcher/fishing golem is a bit of a disconnect, and as I said maybe the fishing golem could be made easier.  But after looking at bases with hundreds/thousands of fish catchers, I am starting to think we need to rebalance those in some way.

**Comment by DoomSquirter** [comment]
just a side note, I don't think the fishing golem has the same loot pool that say the gt++ fisher has.  In fact, it's way inferior since I don't think I've gotten diamonds, etc from it at all, where for ppl that spam the gt++ fisher, that's one of their primary motivations for making it.

**Comment by richardhendricks** [comment]
yeah that definitely needs its own ticket, I'll make one.
