### ISSUE TITLE
Bamboo (Sticks replacement) have no burnvalue

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#3978]
#### Which modpack version are you using?
2.0.6.2
#

#### If in multiplayer; On which server does this happen? 
SSP
#

#### What did you try to do, and what did you expect to happen?
burn them down in a furnace
#

#### What happend instead? (Attach screenshots if needed)
![2019-01-10_21 05 08](https://user-images.githubusercontent.com/15316448/50994140-c41c4c80-151b-11e9-9d16-b9e5350f2d7b.png)
![2019-01-10_21 05 37](https://user-images.githubusercontent.com/15316448/50994150-c9799700-151b-11e9-83cf-4a6b73e7d7c8.png)
#

#### What do you suggest instead/what changes do you propose?
Add burnvalue tu the bammboo (Sticks replacement)

**Comment by Dream-Master** [comment]
yea why not.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51084066-64dd5880-1724-11e9-9eda-a333e2006eda.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51085048-2b144e00-1734-11e9-9271-9f726f8a5362.png)

**Comment by Ldmf** [comment]
nice thx
