### ISSUE TITLE
Gendustry Genetic Templates broken

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#398]
Since the last update, you can't combine genetic samples with genetic templates anymore.
That is required to build proper templates that will be added to bees later on

**Comment by Dream-Master** [comment]
Have to look inside to see if this is a minetweaker error or not.

**Comment by Namikon** [comment]
There is still something missing. You can't empty the genetic capsules in a furnace

**Comment by Dream-Master** [comment]
Ok than i will add it later.

**Comment by Namikon** [comment]
Also, if possible, please register all the new Gendustry combs as oredict "beeComb".
None of the new combs are recognized by the AE OreDict export bus

**Comment by Dream-Master** [comment]
Not sure if with Minetweaker oredicted Bee Combs are ordicted in a way like java did it. I will add it and waiting for you or anyone else to test it.

**Comment by Dream-Master** [comment]
````
// --- Gendutry Bee Combs
oreDict.beeComb.add(<gendustry:HoneyComb:*>);`

````
![image](https://cloud.githubusercontent.com/assets/2970688/11120871/e1ae953a-8952-11e5-8eac-e20bf4e3ce77.png)

**Comment by Dream-Master** [comment]
````
// --- Blank Gene Sample
furnace.addRecipe(BlankGene, <gendustry:GeneSample:*>);
`````
![image](https://cloud.githubusercontent.com/assets/2970688/11121146/8230a6e6-8954-11e5-9d30-fa8a24d68624.png)

**Comment by Dream-Master** [comment]
``````
// --- Gene Template
furnace.addRecipe(GeneTemplate, <gendustry:GeneTemplate:*>);
``````

**Comment by Dream-Master** [comment]
````
// --- Blank Gene Sample
furnace.addRecipe(<gendustry:GeneSampleBlank>, <gendustry:GeneSample>);

// --- Gene Template
furnace.addRecipe(<gendustry:GeneTemplate>, <gendustry:GeneTemplate>);

``


This works better after some wired crashes.
