### ISSUE TITLE
MV lathe requires industrial diamond?

### ISSUE THREAD

**Issue by Beyond-Veil** [GTNewHorizons/NewHorizons#3980]
#### Which modpack version are you using?
2.0.6
#

#### What did you try to do, and what did you expect to happen?
Trying to get an MV lathe to grind the lens needed for engraving silicon (green sapphire) from plate
#
#### What happend instead? (Attach screenshots if needed)
recipe for MV lathe seems to require industrial diamond
#
#### What do you suggest instead/what changes do you propose?
Allow regular diamond for MV age lathe / Explain in quest log for quest 837 that the material for the lens can only be acquired by sifting in the MV age (exquisite green sapphire)

**Comment by Dream-Master** [comment]
need to check

**Comment by Dream-Master** [comment]
I change it to Flawless Diamond. You can get two in a Quest reward for the Diamond Armor in LV.
