### ISSUE TITLE
wyvern flux capacitors uncraftables

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#3984]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
tried to craft the wyvern flux capacitor from Draconic Evolution
#
#### What happend instead? (Attach screenshots if needed)
it can't be crafted anymore

#
#### What do you suggest instead/what changes do you propose?
i looked into the mytweaker script and the recipe use the old version of the Superconductors.
Changing the <ore:wireGt02Superconductor> to <ore:wireGt02SuperconductorUHV> might solve the issue.

**Comment by Anarack** [comment]
You get them from a repeatable quest. closes #3984

**Comment by Dream-Master** [comment]
wyvern core not @Anarack

**Comment by bartimaeusnek** [comment]
@Dream-Master it does not need to be changed with the changes i did to the main branch!

**Comment by Dream-Master** [comment]
ok so fixed allready :)
