### ISSUE TITLE
Galacticraft fuel issues

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#399]
- Cannot fill canisters with fuel (Needed in the rocket booster recipes)

- Cannot fuel ANY rocket, so both Galacticraft and Galaxyspace rockets wont accept fuel

**Comment by Drobac** [comment]
- Change the recipes using Filled Fuel Canister to a Fuel cell as the GC canisters cannot be loaded in GC canners and the canisters disapear if using the recipes via AE crafting(usually just uses the fuel in the canister)

**Comment by Dream-Master** [comment]
Is this the old error we have before. Rockets cant be loaded with Fuel?

With the Canister i can change the recipes.

**Comment by Namikon** [comment]
Confirmed. Impossible to reach any planet now

**Comment by Dream-Master** [comment]
Ok  I don't have acess to the GC Fuel Loader via Minetweaker.

**Comment by Dream-Master** [comment]
B:"Use legacy fuelgc fluid registration"=true 

i set it to false and it works.

**Comment by Dream-Master** [comment]
OK ic2 cell not working and GT cell is consumed. Nothing i can do here only open up an issue.

**Comment by Dream-Master** [comment]
I am adding the recipe to the Fluid Canner. It is not shown but it working.

**Comment by Dream-Master** [comment]
GC Canner ?. In the Fuel loader the Canister works well.

**Comment by Dream-Master** [comment]
So we have to disabled the old Gc oil and fuel because this is the reason that the rockets not gt Fuel.
