### ISSUE TITLE
Add a coins quest for buying Fertilizer

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#3990]
as the name says!

**Comment by damug** [comment]
For what reason? None of it's components are particularly scarce, and it isn't necessarily a long difficult process to manufacture it either.

**Comment by richardhendricks** [comment]
Don't really see that as a reason against it tbh. Would need to make sure to use the right fertilizer, one can be converted one direction, but not the other.

**Comment by draknyte1** [comment]
> one can be converted one direction, but not the other.

I thought I made them interchangeable ages ago.. want me to do so again or fix said code? lol

**Comment by richardhendricks** [comment]
both directions I think is not a good idea since one is waaaay easier to get than the other, but whatever.

**Comment by Dream-Master** [comment]
Yes no ordict needed. A quest can be added and hurt no one.

**Comment by richardhendricks** [comment]
ic2 fert can be made into forestry fert.  Also, many of the ic2 crops quests now reward fertilizer.

I added a coins quest to get ic2 fert.
