### ISSUE TITLE
[ore balance] mid scale ore move 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#3994]
#### Which modpack version are you using?
2.0.6.2
#
#### What do you suggest instead/what changes do you propose?

Couple ores just feel wrong in where they're placed. Plutonium and tungsten come to mind first, but there's probably more that I'll add later. 

Plutonium isn't used much. You start needing a little in EV for radon (8 ingots), it's a possibility for ic2 reactors with mox, you use it to make the godtier bee frames, and in UV it's used to make americium plasma for better zpm parts. 
For the most part you can get all the Pu you need from sources other than ores for everything listed there. I think the pure versions should be moved to the DD because of this. Makes americium plasma a little more interesting pre DD, means you can't spam god frames until post infinity, but radon and Mox still work in their tiers. 

Tungsten is mostly the basis of IV, while being used in small ways before that. You have lava, then T2+ planet ores to get tungstate and schelite. Weirdly though, T3 now gives pure tungsten ore, which seems out of place imo. I suggest moving it to T5 or T6 putting the pure ore in LuV-ZPM. Used to be T5 I think which made sense, but I don't get putting the pure ore only 1 rocket tier past the ore that needs processing especially because the T3 is still kind of EV, so you start IV, the tier that needs tungsten, with pure tungsten. Every other "tier" material needs something additional when you start the tier. LVs bbfs, MVs electrolyzing for Al/gravel ore, HV making stainless and all the chrome for it, EV should be making pure Ti but right now is in the same problem as IV with tungsten, LuV doesn't give you pure Os yet I don't think and you gotta mix osmiridium plus all the fusions, ZPM needs trinium wich doesn't have an ore and all the fusions too, UV has Nt processing pre fusion and some other things. 

Pure Ti ore should be moved to at least T2 imo. Ti has 3ish ways to be made. First is a very lengthy method through stone dust or Al gravel, and servers as a pre moon option for Ti. Bauxite is the perfect EV ore. It gives Ti and a good amount of Ga. No need for pure Ti once you start needing it. Finding bauxite ore is still better than what you can get in the OW so it's still an increase of Ti on the moon, by a good amount. Every time I hit EV I just mine a single Ti vein and have enough for what feels like forever. Bauxite does however take ~20 ore to make 1 rutile. So that's not great. What if ilmenite replaced Al's spot in the vein? FeTiO3 should have a bunch more Ti, while still using rutile. Pure Ti can go to T2 or T3, but the moon seems too early to me. Maybe replace pure Ti with rutile ore? And put pure Ti in the vein rutile comes from on T4?

Now, for something a little more buff related. There's a bunch of veins in the DD that kinda suck. Spessartine/grossular for one, they're nice in MV, but not UHV. Both are manganese sources, but with a pure manganese vein in the DD, this seems weird. Almandine/pyrope falls into the same category, weird MV ores that ended up in the DD. Chromite spawns with titanium, but chrome ore spawns with vanadium. Why have both in the same dim?  Garnierite/cobaltite in the DD is also weird with pure nickel/Cobalt/arsenic. There's a bunch of others, but these seem like the weirdest. Not sure what they should change to yet, some could just be removed probably if that's possible.

**Comment by richardhendricks** [comment]
What sources other than ores for Pu are there?  Recycling U fuel rods? Should there be small ores added to the dim to replace it?  I kinda hate the DD being an ore dump for EQing.  If we get effective bedrock miners I'd like to remove most lower tier ores.

How do you get Ti from stone dust without already having EV? It's an EV recipe. Alu gravel is an obvious non-starter. Titanium is on the moon because that's one of the things it is famous for, having high Ti ores in the maria. Requiring rutile processing is going to put more pressure on chlorine, but we do have some underground salt water on the moon, so yay?

I think losing Alu ore is fine, Bauxite has plenty and there isn't as much demand IMO since you'd have a lot left over from other sources, such as clay electrolyzing or lazurite. And the chrome you get on the moon makes using HV machines for automation just as easy as MV.

**Comment by Bluebine** [comment]
We've already tried putting pure titanium on Mars, for one version. People didn't like it and it made the moon essentially pointless since you'd just rush to T2. 
I'm not really far enough in to give my comments on the rest, but titanium should really stay on the moon.

**Comment by bartimaeusnek** [comment]
>Weirdly though, T3 now gives pure tungsten ore

with a weight of 5 makeing it the rarest vein in game, burried deep in the dark ocean of europa under ~70blocks water, that makes mining it increadibly difficult since miners dont work when placed on the surface. its part of the europa core vein which is a realistic vein reflecting the actual compounds on europa.

**Comment by 0lafe** [comment]
That veins always been there, thought there was a new one added :/ that veins fine. 

>We've already tried putting pure titanium on Mars, for one version. People didn't like it and it made the moon essentially pointless since you'd just rush to T2.
I'm not really far enough in to give my comments on the rest, but titanium should really stay on the moon.

Didn't increase ilmenite spawn last time though. If it's really just used to rush T2 for more Ti then maybe put it on a T3? Moon does have nice stuff anyway, tons of chrome, gallium, titanium from other sources, chlorine, and probably some other stuff I'm forgetting. 

>What sources other than ores for Pu are there? Recycling U fuel rods? Should there be small ores added to the dim to replace it? I kinda hate the DD being an ore dump for EQing. If we get effective bedrock miners I'd like to remove most lower tier ores.

I'm confused then. The bed miners mine based on what ores spawn, so the Pu would need to be there anyway. The DD is *the* ore dump for EQing. It's just a bunch of endgame ores in a single dim. It can be an ore dump for void miners, but I don't think that's related to the ores in the dim. For Pu other than ore there's bees, crops, UU, planet stone, and rods. I think that's it. Pu ore in the DD would be like getting IC or bedrockium. The point of the ore is to let you not have to do the process to make it anymore. It doesn't have to be there, but those were my intentions for getting it moved

**Comment by richardhendricks** [comment]
> > Weirdly though, T3 now gives pure tungsten ore
> 
> with a weight of 5 makeing it the rarest vein in game, burried deep in the dark ocean of europa under ~70blocks water, that makes mining it increadibly difficult since miners dont work when placed on the surface.

@bartimaeusnek Can you clarify the miners not working on the surface?  I know of no reason they should not.
