### ISSUE TITLE
Rework of Multiblock quest requirements

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#3996]
#### Which modpack version are you using?
2.0.6.2
#

Currently, some of the quests (like the ore drilling rig) are barred behind the creation of the previous tiers of machines. I would say to add an or statement that either unlocks when you get to the tier above when you would normally make that machine or the completion of in question low tier machine to that specific quest or any others like that that are barred behind outdated machines due to progressing through tiers. (sorry for the poor wording, lowkey sick right now)

**Comment by Dream-Master** [comment]
Ok the drilling rig I will check. Any other specific quest you would move?

**Comment by richardhendricks** [comment]
The higher tier ore drilling rigs require the lower tier one as a component. Thoughts?

**Comment by richardhendricks** [comment]
Ore drill is now unlocked with Tier 5.  We don't have quests for higher tiers. Oil drilling rig is unlocked with MV machine hull.  I removed the requirement for the seismic for the oil drilling rig, and added wording to the quest itself recommending making one.

![image](https://user-images.githubusercontent.com/1214811/57414273-106f5480-71bd-11e9-80f8-8392333fda00.png)
