### ISSUE TITLE
Can't complete quest ID 800

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#3997]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private MP

#
#### What did you try to do, and what did you expect to happen?
Complete "Plated Leggings better not try yo wear it" ID 800 (chapter Armors and Jetpacks)

#
#### What happend instead? (Attach screenshots if needed)
Can't complete first task, wrong stainless item casing used (casing GTNH instead of GT).

#
#### What do you suggest instead/what changes do you propose?
Fix the quest :) Replace by **gregtech:gt.metaitem.02:18306**

**Comment by Dream-Master** [comment]
fixed in newer version but i will check it.
