### ISSUE TITLE
Mining plascrete blocks

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#3998]
#### Which modpack version are you using?
#
#### If in multiplayer; On which server does this happen? 
GTNH Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to mine plascrete blocks with a hardness of 40 which is lower than obsidian (50)
#
#### What happend instead? (Attach screenshots if needed)
Takes way too long. Even with 128 mining speed it took about 1 second
#
#### What do you suggest instead/what changes do you propose?
Either add wrench as effective tool or let pick mine it correctly.

**Comment by DietmarKracht** [comment]
Anyone interested in a workaround: Use the wand focus of equal trade

**Comment by kekzdealer** [comment]
[The issue didn't exactly get better in 7.0](https://imgur.com/Yx3e0qw)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/5a7e797883be698c59b8702c2a3cda2d41d220b4#diff-37abdb427a9f86a7dc7c2bcffa9afdbd

**Comment by Dream-Master** [comment]
allready changed now. No additional change needed.

**Comment by richardhendricks** [comment]
@Dream-Master This is not the same problem.  There is something either messing with NEI or messing with how blocks are mined.  Someone else commented that graves are taking noticeably longer to break as well.

**Comment by richardhendricks** [comment]
See kez screenshot, hardness is 400, blast resistance 1500

**Comment by richardhendricks** [comment]
Maybe something happened to change the meta? 🤷‍♂️  I dunno why there is code to set the hardness then a later function just has the hardness hardcoded anyways? 🤷‍♀️

**Comment by richardhendricks** [comment]
Problem is from https://github.com/GTNewHorizons/GT5-Unofficial/blob/93d32f3ba6a0b0235767aadee03c092db2836927/src/main/java/gregtech/common/blocks/GT_Block_Reinforced.java

The block hardness in https://github.com/GTNewHorizons/GT5-Unofficial/blob/93d32f3ba6a0b0235767aadee03c092db2836927/src/main/java/gregtech/common/blocks/GT_Block_Reinforced.java#L61

is not the same as block hardness returned in 

https://github.com/GTNewHorizons/GT5-Unofficial/blob/93d32f3ba6a0b0235767aadee03c092db2836927/src/main/java/gregtech/common/blocks/GT_Block_Reinforced.java#L127

Accident? Looks like 400 hardness for meta 1 and meta 3 makes sense, but plascrete is meta 2.

**Comment by richardhendricks** [comment]
Not sure why explosion resistance is so high, doesn't seem to come from here?

**Comment by Dream-Master** [comment]
found the error
