### ISSUE TITLE
Make aluminium oreberries a mandatory reward instead of a choice

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#3999]
players don't realize how hard it can be to find alu gravel on servers, so make a poor choice.  Make the alu berries a mandatory reward.

Also, purchasing oreberries might need to be moved to a different unlock, MV steam turbine is way too late IMO.

**Comment by richardhendricks** [comment]
At a minimum, the quests need to be updated to mention putting them on cropsticks.

**Comment by Dream-Master** [comment]
sure good idea
