### ISSUE TITLE
Game crash when trying to infuse Aura Core from Gadomancy

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4000]
#### Which modpack version are you using?
2.0.6.x
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Trying to infuse Aura Core (Gadomancy) with Ordo, so i can unlock the research and craft Book of Knowledge.
#
#### What happend instead? (Attach screenshots if needed)
After placing the Ordo cluster on the ground and dropping the core next to it, i hit it with the scepter and game instantly crashes. Have tried this twice and with someone in the server who crashes along with me regardless of who hit the core. Seems to be some sort of rendering issue. On SSP this works perfectly with no crashes. 
Pastebin of the crash https://pastebin.com/pdgd12kL
#
#### What do you suggest instead/what changes do you propose?
Honestly i don't know, this kind of issue is beyond my expertise. But this makes Book of Knowledge impossible to craft let alone unlock the research. As far as i know this is a hidden research and unlocks only upon creating the Ordo Aura Core.

**Comment by bartimaeusnek** [comment]
known see https://github.com/GTNewHorizons/NewHorizons/issues/3502

**Comment by MrWye** [comment]
Oh, i searched for it, found only old 2016 one..
