### ISSUE TITLE
Draconic Core recipe (without play quest)

### ISSUE THREAD

**Issue by 648643579** [GTNewHorizons/NewHorizons#4003]
Hi, I request that a recipe for Draconic Core be created and other parts that are from Draconic Mod and do not have a recipe.

Players who do not complete Legendary Quests can not continue Draconic Mod in the later stage of the game.

I play without quests and there is no alternative for me to create these items.
PS: Thank you DreamMasterXXL for the information I was given

**Comment by draknyte1** [comment]
>I play without quests

So you either use a cracked client and *can't* play with quests, or you're not playing the pack as intended, either of which doesn't warrant special recipes for items, just for you.

Do it yourself: http://minetweaker3.powerofbytes.com/wiki/Main_Page

**Comment by 648643579** [comment]
quests are presented as optional!
It's stupidity to find out in the end game that you need quests on draconic mods..

I'm not alone who has the same opinion on this issue!

**Comment by draknyte1** [comment]
> quests are presented as optional

Unless you want draconic items. Then they’re not optional. 🤔

**Comment by Hkal88** [comment]
Evolve draconium mod contains interesting things, but it does not make sense to make the bugs available only through tasks once for the time. There should be an alternative in the form of a Luv - tier level recipe

**Comment by 0lafe** [comment]
So, getting through the quests takes you being zpmish, so probably not LuV. The current recipe is 16Nt per core, which I've tried to change a little but people seem to hate putting ichorium in it. With Bart's quest thing you can auto turn stuff in I think, so not bad. Also, the quests are as optional as any mod in the pack is. They just happen to gate DE as well. It opens up with IV unlocked, so by the time you're making neutronium at zpm (new recipes) you can breeze through the main quests to IV pretty easily. DE takes BM, thaum, and HEE too complete. All "optional" mods as well. Unless you want that part removed too, which I'd advise against, then I don't get the complaint.

**Comment by DoomSquirter** [comment]
dream setup draconic gating behind quests.  he had reasons to do so.  agree/disagree, it's a pack decision.  Putting in a ticket like this is exactly the way one should ask for alternatives or if you disagree with the decision.

given that, I've yet to get to that point, I have been on and off doing quests but more on then off.  When/if I ever get to draconic, I'm sure the quest gating will give me pains, but I will probably just do it like everyone else.

if dream gated it that way, he had a reason.  only dream can tell you yes or no.  if you are playing ssp, or something, you're free to do anything you want, just don't expect ppl to make recipes for you if that direction isn't agreed with.

**Comment by 648643579** [comment]
@0lafe Ok, I understand and accept that idea!
But it is really such a problem to add in Extreme craft "Draconic Core" and other parts that get only from quest line. (I do not mind complex recipes, but there will be an alternative)

**Comment by 0lafe** [comment]
It's not really a problem but I don't see the point. The questline for DE is there for a reason, and builds to it pretty nicely. It also gives it a decent amount of progression pre cores, in a way that would be much less fun/enjoyable with just using recipes. It has a little story to go along with it too, it's significantly better than any other recipe I've seen, so I'd love to keep it that way.

**Comment by DoomSquirter** [comment]
way I see it, if you avoided quests altogether, you could just go in and mark all quests as completed to get to the part where the draconic stf is done.  that would be simplest solution to the issue ur talking about and can be done 100% on your end.

if bq is inaccessible, i.e. like alk said, cracked client, offline mode, there is nobody here that will offer any workarounds to that predicament.  

Otherwise, I'd just let the ticket sit and wait for dream to reply to it.

**Comment by 648643579** [comment]
I understand this explanation, but I have 9 people on Discord who agree with my opinion..
so no one can say that my opinion is unique.. ok?

**Comment by 0lafe** [comment]
I have 13 on grinder so come at me

**Comment by DoomSquirter** [comment]
I'm sure I could find 9 ppl that think I'm cool but they'd all be wrong.

as I said, the one and only person that can agree with what you're asking and either do it or say "go ahead and do it" is dream.  I'd wait for him to comment on ticket.

**Comment by emkei-cz** [comment]
quest book is for players who have no experience with GT New Horizons and need help.
being forced to change items to gain anything end-game is more than a stupid solution.

**Comment by 0lafe** [comment]
>being forced to change items to gain anything end-game is more than a stupid solution.

Isn't that a recipe?

**Comment by Dream-Master** [comment]
If i ever add a recipe this will be more hard.

**Comment by 648643579** [comment]
Absolutely i don't mind, especially when a recipe will exist as an alternative to quest line.
harcore > better

**Comment by 0lafe** [comment]
It's not even the worst of the 4+ "optional" mods associated with getting DE, after doing like 400 thaum infusions I was much less happy than making like 6 machines of tiers significantly below you.

**Comment by 648643579** [comment]
Alkalus, you have to realize that GTNH was created by the community even if you have a big share you do not have the last word!

If you think you are speaking for another persons, and you do not want such a recipe to be created, ask for a vote example Discord...

otherwise realize that you are speaking for yourself...

**Comment by draknyte1** [comment]
> Alkalus, you have to realize that GTNH was created by the community even if you have a big share you do not have the last word!

Do I ever claim I do?
I'm just vocal of my opinions and if you don't like them, tough shit.

You're one member of a community of several thousand.. why should you and your 8 friends get special entitlements for not using the modpack as intended by the authors and the rest of the community? That's the issue at hand here..

You don't get to ask for support when you're not playing the intended way for progression.. you've been given the way to add your own recipes, so why bother arguing besides the sake of being a pain in the ass?

**Comment by Mrkev986** [comment]
@draknyte1 maybe I would change the pills you take or changed your doctor because he wrote you bad pills.

**Comment by draknyte1** [comment]
> why bother arguing besides the sake of being a pain in the ass?

> maybe I would change the pills you take or changed your doctor because he wrote you bad pills.

Personal attacks are pathetic and proof I’m correct because you have no alternative replies. This hasn’t ever been a discussion and should’ve been closed long ago.

**Comment by bartimaeusnek** [comment]
there you have it, no change.
