### ISSUE TITLE
Fluid regulators have wrong colour coding

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#4004]
2.0.6.2

ZPM and UV fluid regulator haves the wrong colour coding. 
(crafting is correct ZPM to ZPM and UV to UV)
![image](https://user-images.githubusercontent.com/30087707/51432619-caf14080-1c3a-11e9-8cd7-7e1c37870dd6.png)
![image](https://user-images.githubusercontent.com/30087707/51432623-e9573c00-1c3a-11e9-8ada-ade20db45939.png)

**Comment by DualBallers** [comment]
Bump, as there's been no response to this :-)

**Comment by Dream-Master** [comment]
@DualBallers if you writing a pull request i will it merge it in seconds. I have a rl too can't monitore  all issues. sorry
