### ISSUE TITLE
Draconic quest line adjust 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4010]
#### Which modpack version are you using?
2.0.6.6
#
#### What do you suggest instead/what changes do you propose?

#4003 brought up things, so idea time. Change reqs of first legendary quest to open from the start, but make you have 16 asteroid stone, to emulate the current place. This way you can make cores while doing 0 other quests, but the "recipe" is the same, and results in the same end recipe for them

**Comment by Mrkev986** [comment]
Good solution, someone who does not complete quests and finds that he needs another 10-20 previous quests to get the draconic core is damned.

**Comment by 0lafe** [comment]
That's even better, had no idea BQ did that

**Comment by Mrkev986** [comment]
@draknyte1 can you read?
https://www.technicpack.net/modpack/mcnewhorizons.677387
https://i.postimg.cc/SQD3cpzf/obrazek.png

**Comment by bartimaeusnek** [comment]
there you have it, no change.

**Comment by Dream-Master** [comment]
change the Quest to Asteroids Blocks in Inventory

**Comment by Dream-Master** [comment]
DE stuff not realy needed if you dont like the quests play with the other stuff. Dont like the idea make this questline so easy to open.
