### ISSUE TITLE
Seared Bricks for Smeltery quest should be a retrievel task.

### ISSUE THREAD

**Issue by Fapiko** [GTNewHorizons/NewHorizons#4011]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private server

#
#### What did you try to do, and what did you expect to happen?
Tried to complete the TiCon Smeltery multiblock quest. I used a compressor since I had to make one for the Steam Age quests.

#
#### What happend instead? (Attach screenshots if needed)
It did not mark the quest complete because it is a crafting task.

#
#### What do you suggest instead/what changes do you propose?
Change the Seared Bricks task to Retrievel.

**Comment by Dream-Master** [comment]
My original intention when made the quest was to show people how to build it. Sure you can go to a village and get one for free

**Comment by Dream-Master** [comment]
that's why I made it crafting not retrieval tasks

**Comment by Fapiko** [comment]
Makes sense, but for my latest play through I already had a compressor by the time I got around to doing the quest so it wouldn't have made sense to craft it instead of using the compressor. Feel free to close this issue out but it's probably likely others will have an issue with this quest as well.

**Comment by richardhendricks** [comment]
Can always make your smeltery bigger. :D

**Comment by Dream-Master** [comment]
yes I make it bigger to later on so  no change.
