### ISSUE TITLE
DE core quest recipe change 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4013]
#### Which modpack version are you using?
2.0.6.6
 
#### What do you suggest instead/what changes do you propose?

Right now it costs 16 Nt and 16 thauminite to make a DE core. Not bad but it's really just 16Nt, the thauminite is 9:8 from thaumium in a crucible recipe, so not really a concern. The point seems to be to use endgame materials from GT and thaum, but thauminite just isn't that material. I suggest changing it to 16 ichorium instead. At least this one is an infusion and takes some higher tier stuff.

**Comment by Anarack** [comment]
On a aside note, can we look at the draconic recipes in general? With a few exceptions it is basically all neutronium and draconium and thats fairly boring. I am not asking for a nerf, just more types of stuff used. 

The machines are better but its mainly the sub components that are fairly bad about it.

**Comment by richardhendricks** [comment]
These are not quest changes.  Need someone to do recipes first.

**Comment by Dream-Master** [comment]
Dont like the idea DE Cores are have simple recipe. Make the Quest Line obsolete.

**Comment by 0lafe** [comment]
They are quest changes moron, the recipe is a quest task. The recipe is the items required for the quest. It doesn't invalidate any quest line, just saying the DE core cost is heavily weighted towards one half of the ingredients, and doesn't encourage endgame production of one of the mods it seems to rely on. Weird for endgame items.

**Comment by richardhendricks** [comment]
How is this a quest change? It sounds like a discussion on nerf/buff.

**Comment by AlexBucket** [comment]
> How is this a quest change? It sounds like a discussion on nerf/buff.

It's both a quest change and a change to the cost of cores. It's not really a nerf considering they cost sweet FA.

Ichorium is way better than thauminite

**Comment by Dream-Master** [comment]
Maybe i can add a hier tier recipes for DE Cores at uhv or so make the is maybe a cheaper way get de cores in mass production.

**Comment by 0lafe** [comment]
you *can* make it in mass with the current recipe tbh, but something with like avaritia stuff and or T4 fusion could be cool?
