### ISSUE TITLE
Draconic Core Recipe

### ISSUE THREAD

**Issue by 648643579** [GTNewHorizons/NewHorizons#4014]
Here are two draft recipes for Draconic Core

Recipe 1: https://vgy.me/90gniM.png
- Osmiridium Gear
- 4x Osmiridium Screw
- 4x Neutronium Plate
- 4x Draconium Plate
Aspects: 2048 Praecantatio, 2048 Auram, 1024 Metallum, 1024 Lucrum, 512 Instrumentum, 512 Fabrico, 256 Machina, 128 Infernus, 64 Terminus

Recipe 2: https://vgy.me/oiHmIk.png
- Osmiridium Gear
- 4x Osmiridium Screw
- 4x Neutronium Plate
- 4x Draconium Plate
- 4x Osmiridium Rod

**Comment by Hkal88** [comment]
Very nice recipes.

**Comment by Spartak1997** [comment]
Or we can use "Raw Draconium Core" (custom item) and use it in Blood Altar T5 for creating Draconium Core.

**Comment by Anarack** [comment]
Assuming one furnace can do one item per tick that can be upwards of 380 seconds of distillation time. + lets assume another 380 of infusion crafting. This is assuming you can get this much junk to feed into it via wisps or raw materials.

T6 for bm not 5, 5 is a trivial upgrade from 4.

Osmiridium is cheap once you hit Io and neutronium can be done right t1 fusion if being energy intensive or later the buffed fusion recipe.

Judging by quest line this needs to be gated at a minimum past the final rocket material wise.

**Comment by 0lafe** [comment]
So if this is meant to replace the quest recipe, shouldn't it be harder? I'd suggest switching the osmiridium to fluxed electrum, and maybe throw some more thaumey/magicey stuff in there, like ichorium or demon shards or something. I like it being an infusion, but I like it being a quest reward more.

**Comment by 648643579** [comment]
@Anarack you're right, it was based on information that:
https://vgy.me/ckkD2M.png
(64 Neutronium Ingot + 64 Thauminite Ingot > 16x Draconic Core)
1x Draconic Core = 4 Neutronium Ingot + 4 Thauminite Ingot
so I added Osmiridium as cheaper material. 

@0lafe I really like the idea of using the material fluxed electrum

**Comment by 0lafe** [comment]
If we wanna transition from a quest reward to a straight recipe, I'd like to see something from the quests needed. Like a catalyst or some item that's not used up but is in the recipe and a quest reward from finishing the DE chain. Can get the good sides of more mods that way, with the quest fun, but a recipe that isn't put 2 ingots in a block. I like it needing a T6 blood altar, could need that to activate the catalyst or something. Maybe it loses durability and you repair it with LP? 

Maybe a dire recipe of the catalyst in the middle, surrounded by alternating fluxed electrum/Nt ingots in a 3x3. Then things going out in the NE/NW/SE/SW directions of draconium 2 items long, then 4 ichorium in the up/down/left/right 5x5 around the middle. Same shape as the core upgrades. Could also throw some UV or ZPM SC in the spaces between ichor/draconium

**Comment by draknyte1** [comment]
> So UV is equal to post space progression then based on the above

If DE is at the end, why is it using anything outside of TT machines and >= UHV power.. let alone materials, boring..  As written in another ticket, all the DE recipes are use the same several items/mats and aren't very flashy. Maybe consider redoing them all with other materials such as Octiron, Celestial Tungsten, Astral Titanium, or Quantum (To list a few). Materials created or revised specifically for this tier of content for 0lafe & others.

**Comment by 648643579** [comment]
unfortunately, my knowledge in Blood Altar is limited, so someone else should design a recipe.
for comparison: https://vgy.me/N1ADrs.png
@draknyte1 If you're thinking about editing for all cores, try show recipes.

**Comment by Dream-Master** [comment]
@draknyte1 De recpipes was made a long time ago. We can change them sure. About the De Core I am not sure if we realy need to add a recipe.

**Comment by Tomas688** [comment]
How can I create DE Core without quest book? nothing.
What pre-quests do I need to make the DE Core? much.

The best solution is to create a recipe or change the quest but you said the guestbook would not change.

**Comment by 0lafe** [comment]
![screenshot_20190122-190525](https://user-images.githubusercontent.com/21280852/51573792-bd28fe80-1e78-11e9-9465-e2a35194ad1d.png)

**Comment by draknyte1** [comment]
>  De recpipes was made a long time ago

I know. I’m talking about proposed changes.

**Comment by Dream-Master** [comment]
was reopen the issue
