### ISSUE TITLE
TiC perma health canisters destroyed in rocket explosion

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4016]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Launching T1 rocket. Landing on the moon
#
#### What happend instead? (Attach screenshots if needed)
T1 rocket blew up when landing. Space bar simply refused to work to decelerate and in the explosion process TiC permanent heart canisters got destroyed and were removed from the player.
#
#### What do you suggest instead/what changes do you propose?
needs a fix

**Comment by Dream-Master** [comment]
heard it the first time. Both sources are open to change so who can fix that or is it fixable?

**Comment by draknyte1** [comment]
Possibly just another mod that's doing setHealth() directly and skipping forges death handling. You'll find this is the case anytime graves don't spawn or special handled items vanish.
