### ISSUE TITLE
Change fusion hatches 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4017]
#### Which modpack version are you using?
2.0.6.6
#

#### What do you suggest instead/what changes do you propose?

My opinions on LV-IV energy hatches asside, I think that the change was good for LuV+ as those were dumb cheap for tiers when you have dumb amounts of materials/power. Currently hatches get kinda easier gate wise with LuV, as the mk1 reactor needs LuV hatches, so you need to be able to make them right away in LuV. This means zpm recipes open up when you start LuV, instead of late LuV/early ZPM. So uh, change please

**Comment by Dream-Master** [comment]
@0lafe any new on how we can change this and not breaking tiered gt stuff?

**Comment by Anarack** [comment]
You know zpm motors are gated behind europium now right? I would argue T1 non power producing fusion is near the end of the tier.

**Comment by 0lafe** [comment]
Yeah, I wanna put LuV hatches in the same spot, but can't because the mk1 needs them. Guess we could use the rocket of the tier, but I'm not sure how to do that in a good way that doesn't require mining a certain planet specifically
