### ISSUE TITLE
Salt bees

### ISSUE THREAD

**Issue by Rostisha** [GTNewHorizons/NewHorizons#4019]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I tried to get some Salt Combs from my Salt Bees (after converting old SaltY into Salt). NEI says that they will give me Slag, Salt and Lithium Combs.
#
#### What happend instead? (Attach screenshots if needed)
Salt Bees give only Slag Combs. I also tried to put Compressed Salt (Pam's Harvest Craft)/salt ore/saltpeter ore under the alveary, but it doesn't make any changes..
#
#### What do you suggest instead/what changes do you propose?
I'm asking if I can somehow check what bees need to make Spec. Production. Or is it bug with salt bees?

**Comment by richardhendricks** [comment]
Don't you need to be in the proper biome temp/humidity for them to provide specialty products?  Specialty products ignore the temp/humidity tolerances I think.

**Comment by richardhendricks** [comment]
https://forum.feed-the-beast.com/threads/specialty-bee-products.28134/

**Comment by Rostisha** [comment]
Will try it later, thanks!

**Comment by Rostisha** [comment]
Yeah, it works now!
