### ISSUE TITLE
BQ - Skeleton: Evolved #918 doesn't detect the boss kill

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4021]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Killed evolved skeleton expecting the quest to complete
#
#### What happend instead? (Attach screenshots if needed)
The quest doesn't detect the skeleton being killed
#
#### What do you suggest instead/what changes do you propose?
Fix

**Comment by Dream-Master** [comment]
again epsilon not using lastest version. I think we fix that but I can look if this is fixed

**Comment by DietmarKracht** [comment]
Same problem on Delta

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51939435-bc134680-240f-11e9-816f-3121feaa288b.png)
