### ISSUE TITLE
BQ - Kill All The Things infernal mob kills dont appear to count

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4022]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
Killing mobs for the repeatable quests don't appear to count infernals, i am not sure if the ender zoo is also contributing to this same issue. From what i have seen only vanilla mobs seem to count toward the progress. Having to kill over 30-50 pigmen (example) and having the count to go up by just one is rather exhausting.

**Comment by Dream-Master** [comment]
Epsilon not using version 2.0.6.x . I play on zeta with the newest version and making the kill quest too. For me it worked.

**Comment by Paolkageist** [comment]
None of the nether mobs are counting for the quests.  I've killed blazes, ghasts, and pigmen, and they're all at 0/10 still.  This is weird.  I've definitely done all of these many times in the past.

**Comment by Paolkageist** [comment]
Update: I went into /bq_admin edit mode, and the kill count updated for all quests.  I'm now at 2/10 ghasts, 9/10 blazes, and 10/10 zombies.  I was able to complete the pig zombie quest.

**Comment by MrWye** [comment]
Yeah, sorry about the version mixup. I know we are not using new one, not sure why i remembered version different. Corrected.

**Comment by Dream-Master** [comment]
for me it works get a lot of hearts. Some time its not update but when you have 10 kills it will.

**Comment by Dream-Master** [comment]
@MrWye can we close this or is this still an issue ?

**Comment by MrWye** [comment]
Can be closed, it appears to work just fine in the new version.

**Comment by Dream-Master** [comment]
yea have the issue now too. After 9 counts it ont complete again.

**Comment by mitchej123** [comment]
Is this still an issue on the latest versions?  Reopen if it is.
