### ISSUE TITLE
Item Detection Cover not working

### ISSUE THREAD

**Issue by HawkridgeV** [GTNewHorizons/NewHorizons#4023]
Issue Title
Cannot craft item detection cover

Expected Behavior
weightes gold pressure plate + any of iron aluminium or wrought iron plate in an assembler with soldering alloy gives a item detector cover

Current Behavior
assembly line does not start (with soldering alloy), other fluids not tested

Possible Solution
please fix!

Steps to Reproduce (for bugs)
.
1.put ingredients into any assembler

Multi player GTNH server myftb.de

**Comment by Dream-Master** [comment]
version of GTNH?
@HawkridgeV

**Comment by Dream-Master** [comment]
Need help with it @bartimaeusnek @richardhendricks @mitchej123 @Technus

**Comment by HawkridgeV** [comment]
2.0.4.1 I beleive, but I will test it on 5.1 later today.
