### ISSUE TITLE
[rfc] drop stone dusts from small ores

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4025]
Look at dropping stone dusts out of small ores to prevent inventory spam of useless stone dusts

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_Block_Ores.java

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L262

**Comment by Anarack** [comment]
Lower the chance at a minimum.

**Comment by kekzdealer** [comment]
I vote for getting rid of them.

**Comment by Dream-Master** [comment]
nah i am ok with it. You can't get every time the ore jackpot some crapy  stone dust is ok for me.

**Comment by bartimaeusnek** [comment]
@richardhendricks
Gaussian Distribution for small ores plox, i.e. you have 12 metal/compound ores:
6 of them drop dust
3 of them drop 1 crushed ore
2 of them drop stone dust
1 of them drop 2 crushed ore

For gem ore ( for 24 ores) :
1 of them drop exquistie
2 of them drop flawless gems
3 of them drop gems
3 of them drop stone dust
4 of them drop flawed gems
5 of them drop chipped gems
6 of them drop dust

**Comment by richardhendricks** [comment]
No change
