### ISSUE TITLE
[rfc] List recipes you would like visible in an external tool

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4027]
Please list recipes you would like to see in an external tool.  Looking at http://crafting-guide.com/browse/minecraft/ , it requires manually setting up the recipes so we can't automate extracting every possible recipe.

GT machines
Circuits
Machine parts like pumps/motors/field generators
Hatches/buses for multis
Multiblock parts
Batteries
Oil refining
Polyethylene 
PVC
PTFE
New plastic
GT tools

EnderIO items
Reservoir
XP storage
capacitor banks
teleporting stones

Railcraft items
Water siding tank
iron/steel tank parts
basic rails
anchors

Any thaumcraft recipes? Witchery recipes?
Thirsty tank

Forestry
Machines and farm blocks
Bees?
Trees?

Pams
Pams tools
Pams saplings

**Comment by boubou19** [comment]
PBI could be great too.

**Comment by richardhendricks** [comment]
ores and byproducts

**Comment by richardhendricks** [comment]
GT++ machines and casings

**Comment by richardhendricks** [comment]
Superceded by Not Enough Production by @bigbass1997
