### ISSUE TITLE
Oriharukon Screwdriver

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#4028]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Make a screwdriver from Oriharukon
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/25811344/51785295-cc000180-2155-11e9-9773-b217ffb9c6cf.png)

#
#### What do you suggest instead/what changes do you propose?
add recepie

**Comment by Spartak1997** [comment]
Use another stick. For example steel rod because wood stick using not all screwdriver recipes
