### ISSUE TITLE
Bedrockium Drum uncraftable

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/NewHorizons#4029]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private MP

#
#### What did you try to do, and what did you expect to happen?
Try to craft Bedrockium Drum

#
#### What happend instead? (Attach screenshots if needed)
Can't because wrong bedrockium plate used (GTNH instead of GT)

![2019-01-26_17 32 25](https://user-images.githubusercontent.com/17729817/51790081-1e124880-2191-11e9-8ec9-c614ed281fba.png)
![2019-01-26_17 32 29](https://user-images.githubusercontent.com/17729817/51790084-1f437580-2191-11e9-98bb-c601ea42f6fe.png)

#
#### What do you suggest instead/what changes do you propose?
Replace MT script Extra-Utilities.zs (or wait futur update that will fix this issue maybe ?)

`// --- Bedrock Drum
recipes.addShaped(BedDrum, [
[<gregtech:gt.metaitem.01:17395>, <ore:ringTungstenSteel>, <gregtech:gt.metaitem.01:17395>],
[<gregtech:gt.metaitem.01:17395>, <ExtraUtilities:drum>, <gregtech:gt.metaitem.01:17395>],
[<gregtech:gt.metaitem.01:17395>, <ore:ringTungstenSteel>, <gregtech:gt.metaitem.01:17395>]]);`

**Comment by Dream-Master** [comment]
fixed allready

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51792508-0eefc280-21b2-11e9-9edf-aab997819996.png)
