### ISSUE TITLE
Ender IO Conduits

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#403]
The conduits need a lower crafting time, even in an 8k they take too long and you need large ammounts of them.
This includes the item conduits, all the fluid and energy conduits as well as the Ender IO AE cables

**Comment by Dream-Master** [comment]
The Conduits have a crafting time from 100 or 200 Ticks wich are 5 to 10 sec in different Tiers(up to HV) I can change them to be 100 Ticks each pipe but more i wont do.

**Comment by Drobac** [comment]
i would even half that amount so 50, as it is the last link in a long chain of processing just to get one pipe. For example the item pipe - 1. Alloy smelter (gold + silver) 2. extruder for pipe 3. whole processing system to get pulsating iron then bender to get plates and then the assembler with plastic to get the final product. You need a lot of the conduits, and the ME conduits should have an even shorter crafting as theirs is just a cosmetic upgrade that allows you to put them in facades

**Comment by Dream-Master** [comment]
Forgot it in 1.0.7.1. Will change it in 1.0.7.2
