### ISSUE TITLE
tainted magic messed up after 2.7

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4030]
#### Which modpack version are you using?

# this was not me, reporting for pao in help from discord
he's running 5.1

#### If in multiplayer; On which server does this happen? 
personal server
#
#### What did you try to do, and what did you expect to happen?
quite a few tainted magic researches are borked

in 2.7 there are two tainted magic scripts
in 4.6 and beyond there is one.  update happened I assume.

in doing that update, there is a messed up research pre-requisite.  
first off notice this:
// --- Shard of Creation
mods.thaumcraft.Research.orphanResearch("CREATIONSHARD");
mods.thaumcraft.Research.removeResearch("CREATIONSHARD");

then the first bork
mods.thaumcraft.Research.orphanResearch("FOCUSTIME");
mods.thaumcraft.Research.removeResearch("FOCUSTIME");
mods.thaumcraft.Research.addResearch("FocusTimeGTNH", "TM", "tempus 27, praecantatio 24, aqua 21, ignis 18, terra 15, ordo 12, perditio 9, aer 6, permutatio 3", 11, -8, 4, <TaintedMagic:ItemFocusTime>);
mods.thaumcraft.Research.addPrereq("FocusTimeGTNH", "CREATION", false);
mods.thaumcraft.Research.addPrereq("FocusTimeGTNH", "FOCUSPORTABLEHOLE", false);
mods.thaumcraft.Research.addPrereq("FocusTimeGTNH", "FOCUSFIRE", false);

notice it's called out as simply CREATION not CREATIONSHARD

notice also it's in more than one place.

pao updated his server with updates rules (creation -> creationshard) and he's able to research the stuff now.

# 
#### What happend instead? (Attach screenshots if needed)
tainted magic turned me into a newt
#
#### What do you suggest instead/what changes do you propose?

feeeexxxxxx eeeeeettt plox :)

**Comment by Dream-Master** [comment]
will check
