### ISSUE TITLE
quest 1078 and 1079 need to change

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4031]
#### Which modpack version are you using?

#2.0.6.2

quest 1078 and 1079 require some wrong item

#quest 1078(summon Ur-Ghast)
This quest require "Knightly Helm" made by Knightmetal which cannot craft
It should be "Phantom Helm" which drop by "Knight Phantoms"

#quest 1079(summon Alpha Yeti)
This quest require "Alpha Yeti Fur"
It should be "Ur-ghast Trophy" or "Fiery Tears"

**Comment by Dream-Master** [comment]
will check

**Comment by Kiwi233** [comment]
By the way, quest 1703(Potassium Nitrate) describe: "Potassium Nitrade is made out of potassium and ammonia." is not in conformity with the recipe. The recipe of Potassium Nitrate need Potassium and Nitric Acid.

**Comment by richardhendricks** [comment]
File a separate ticket plz.
