### ISSUE TITLE
wireless charger mkVIII doesn't have a recipe

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4033]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
https://github.com/draknyte1/GTplusplus/issues/418

#### What did you try to do, and what did you expect to happen?
wanted to craft the wireless charger mkVIII
#
#### What happend instead? (Attach screenshots if needed)
it's the only one who doesn't have a recipe in nei

**Comment by Dream-Master** [comment]
Have a recipe now
![image](https://user-images.githubusercontent.com/2970688/51935618-96ce0a80-2406-11e9-850b-200b74c2b5fd.png)
2.0.6.6b.dev
