### ISSUE TITLE
Mod License Request and Curse pack suggetion

### ISSUE THREAD

**Issue by monatann** [GTNewHorizons/NewHorizons#4035]
Hi, I have a request and suggestion. Sorry for my bad English:)

Firstly, I want to use GTNH modified mods for my modpack, so may I use it? Some mods doesn't be written License, so I need to ask.
I'm making a GT6 pack, and I have a plan to modify GT5u for working with GT6. (In fact I already wrote most code and it works fine.)

Secondly, if you still want to upload pack to Curse, I suggest to use DepLoader(https://github.com/Chicken-Bones/CodeChickenCore/blob/1.7.10/src/codechicken/core/launch/DepLoader.java) and download mods at first launch. If you place dependencies.info in your .jar file, it downloads mods by using URL.
Here is an example I use. 
Download URL: https://monatann.azurewebsites.net/files/minecraft/NotEnoughItemsUnofficial-1.7.10-1.0.5.120-universal.jar
dependencies.info in another .jar:
> {
> 	"repo":"https://monatann.azurewebsites.net/files/minecraft/",
> 	"file":"NotEnoughItemsUnofficial-1.7.10-1.0.5.120-universal.jar",
> 	"dev":"NotEnoughItemsUnofficial-1.7.10-1.0.5.120-universal.jar",
> 	"class": "codechicken.nei.asm.NEICorePlugin"
> }

But at first coremod must crash and need re-launch.

If you think I'm so selfish, I apologies you.
Thank you for making nice mods and pack!
<s>It's too tough to make research station lol.</s>

**Comment by Dream-Master** [comment]
please contact me on discord

**Comment by Dream-Master** [comment]
https://discord.gg/kTrF3nV

**Comment by monatann** [comment]
I joined. (discord name: monatann)
I'm sorry for your inconvenience. Thank you very much!

**Comment by Dream-Master** [comment]
GTU5 and IFU have a open license so i dont see any issues here.

**Comment by bartimaeusnek** [comment]
@monatann my gregtech 5u / IC2 addons are open source and MIT licensed, if you want you can use them aswell, just make sure to change the modname to something like monatann edition or so.

https://github.com/bartimaeusnek/bartworks - A addon for GT5u introducing some usefull multis/machines
https://github.com/bartimaeusnek/GTNEIOrePlugin - A NEI Addon for GT5u
https://github.com/bartimaeusnek/CropLoadCore - A core that do oredict stuff and ASM for IC2
https://github.com/bartimaeusnek/crops-plus-plus - Adds a shitton of IC2 crops

**Comment by monatann** [comment]
Thank you very much, Danke schön:)
