### ISSUE TITLE
Add Mince Meat to Mortar

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4039]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Make mince meat in a mortar.
#
#### What happend instead? (Attach screenshots if needed)
Can only make mince meat in macerator/pulverizer.
#
#### What do you suggest instead/what changes do you propose?
Add recipe to make mince meat with mortar.

**Comment by Dream-Master** [comment]
added.
Thanks @shawnbyday
