### ISSUE TITLE
3,3-dichlorobenzidine recipe is giving full copper dust in output?

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4045]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was setting up my 3,3-dichlorobenzidine production.
#
#### What happend instead? (Attach screenshots if needed)
the fluid in input is 2,2-nitrochlorobenzene
![image](https://user-images.githubusercontent.com/12850933/51934912-03e0a080-2405-11e9-9949-6c584e4d2802.png)
Is copper a product of the reaction IRL that would justify the full copper dust in output normal?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/51935290-de07cb80-2405-11e9-81c8-b37b180c9bb4.png)
2.0.6.6a.dev

**Comment by boubou19** [comment]
oh i guess it's fixed in dev

**Comment by Dream-Master** [comment]
np thanks for report it @boubou19

**Comment by richardhendricks** [comment]
Why is it copper at all?  If anything, it should be a zinc tiny dust.

https://en.wikipedia.org/wiki/3,3%27-Dichlorobenzidine

**Comment by Dream-Master** [comment]
o will change to zinc
