### ISSUE TITLE
Update small boiler tooltips

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4048]
small coal boiler says it does 120L/s, but it looks like it does 150.  Change it to L/tick anyways

**Comment by blanknam** [comment]
It should be producing 150L of steam every 25 ticks, which works out to 120L/s. I agree that a L/tick tool tip is preferable.

**Comment by richardhendricks** [comment]
Yeah I see the code that does that now.  Seems kinda weird.  Should I change it to 120L every 20 ticks? Not sure the logic behind doing 150 every 25.  Maybe it was done that way to make it easier to divide down?

**Comment by blanknam** [comment]
I think it's because the conversion rate for water to steam is 1:150, so that way he can add steam and remove water on the same tick.

**Comment by richardhendricks** [comment]
Makes sense!  Will update the tooltip.
