### ISSUE TITLE
Quest bug/s

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#405]
Steam-a-licious! - quest does not accept the basic steam turbine
Analyze them all - quest doesnt recognize Field Kit

**Comment by Dream-Master** [comment]
I find something too.

- The Part Builder can only make with Oak Legs (Spruce Wood not working)

- I see a Text Info in red Letters under the Bed Quest (hqm.QuestBook.childUnlock)

 -I think the Find Copper  Quest need only for of each Ores wich is a bit low. I remember a old version need a lot of Copper mabe switch it to 15,15,15 or 10,10,10

**Comment by Namikon** [comment]
HQM seems to have a few localisation problems in the current version, I also found a few "hqm.xxx" lines. Gonna check the NBT state of the Steam Engine and Field kit; I thought I set everything GT related to non-nbt. Guess it's just a derp.

And IIRC, the required OreCount was reduced because Teteros complained about it. I think it was something about that "copper ore" isn't that common, and chalcopyrite is also "copper". So for now, it's just a quest to make the player find a proper copper/iron vein by himself. But 1 is indeed a bit too low, gonna check that as well.

**Comment by Dream-Master** [comment]
The new Version 4.4.2 i will add to the Server sonn (Update 1.0.7.3) It solve a lot of Bugs.
With the Copper it is not one Copper Ore it is 4 of each Type i think but i can make a Screen Shoot of it.

**Comment by Namikon** [comment]
I think the 4 came from a time where we had the 16-ish Stacksize. (And to get 4 of each, you need to find a vein. It doesn't really matter if you have to grab 4, 10, 15,.. it's just a matter of collecting those.)
IMHO, the Quest goal is reached by finding a vein.

**Comment by Dream-Master** [comment]
agreed.

**Comment by Dream-Master** [comment]
Malachite not spawns together with copper/chalcopyrite. So you need to fined two different Veins for completing the Quest.

**Comment by Namikon** [comment]
As of v151121:

- Steam-a-licious! - quest does not accept the basic steam turbine
Wasn't set to NBT detection. 

- Analyze them all - quest doesnt recognize Field Kit
Will accept all fieldkits now; Regardless of paper-sheets added to it

- The Part Builder can only make with Oak Legs (Spruce Wood not working)
Sadly, there is no way to change this. You have to use the oak-variants. Added the missing pattern-chest as requirement

**Comment by Dream-Master** [comment]
Will add it with Update 1.0.7.3.

**Comment by Drobac** [comment]
The endermen killing quest not accepting the endermen for some reason

**Comment by Namikon** [comment]
Can we use new issues for quest problems please? With Issue recycling it's impossible to keep track of any changes. 
And the endermen are probably broken because SpecialMobs overwrites the Vanilla Enderman, I will check that

**Comment by Dream-Master** [comment]
Yes it can be Special Mobs.

**Comment by Dream-Master** [comment]
But we open a ne issue far that.

**Comment by Namikon** [comment]
Endermen are now correctly recognized. I also re-balanced the entire loot-bag system; There should be no HV drops in common bags anymore.
And, there is a bypass area now to gain reputation without doing the entire book

**Comment by Dream-Master** [comment]
:+1:
