### ISSUE TITLE
[rfc] Discussion on InGame Info XML Config

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4050]
The InGame Info mod is included in the new release.  This issue is to discuss which lines we should keep and which we should remove on the official modpack.

![image](https://user-images.githubusercontent.com/1214811/52011760-7a7dac80-249e-11e9-92a3-74239a238e30.png)

**Comment by richardhendricks** [comment]
My opinion
Name & FPS - keep
Date & time - keep
Dimension & Chunks loaded - remove
Biome & temp & humidity - keep
Warp - remove
Entities - remove
Chunk & direction - keep
Light - Maybe keep? Useful for some plants
Ore chunk info - keep
Armor info - keep

The settings on the font size etc can be configured smaller, and we can choose the location for the information.  I think bottom left may work better? IDK, you still need bottom left for the chat window.

**Comment by Dream-Master** [comment]
I don't want to add xml info to the game. Everyone can load it if they want. We have ingame info in the pack long time ago and we decided to remove it because more players feeling that the text is more anoying than helpful. Its not my opinion but the opinion of the majority at the time we make a vote.

**Comment by 0lafe** [comment]
Im with dream. Its a HUD mod that's only really useful when mining/bee biome hunting. Even then you can just f3 mostly. I say leave it as an optional mod

**Comment by richardhendricks** [comment]
I don't want to go the wiki/self-setup route because it seems like we get a quite a few questions on it.  Including this in the pack would remove those questions pretty easily along with providing player info for other useful things, like humidity for crops and the water siding tank. 

I'd say the argument is stronger to put it in the pack and if it is annoying for experts, they can remove it easily enough.

**Comment by shawnbyday** [comment]
On the note of removing it you could also include it in the pack but have it disabled by default. That way you could enable it when you're looking for ore or biomes or what have you if you so desire.

/igi enable
/igi disable

Then have a few built in versions (not sure on how many) with descriptions/examples listed somewhere and people can load the one they want.

/igi load <filename>

**Comment by richardhendricks** [comment]
Required mods:
LunatriusCore-1.7.10-1.1.2.21-universal
InGameInfoXML-1.7.10-2.8.1.82-universal

[config files.zip](https://github.com/GTNewHorizons/NewHorizons/files/2898573/config.files.zip)

Will create wiki page

**Comment by Dream-Master** [comment]
warp info line  must be disabled

**Comment by shawnbyday** [comment]
> warp info line must be disabled

I don't think there is any way from someone re-enabling this if they know how. It is a pure client side thing. This might be something to look into on the server side config of InGameInfo.

**Comment by Dream-Master** [comment]
guess thats why we take the mod out of the pack

**Comment by richardhendricks** [comment]
If we give them a prebaked script, 99% of players will use that.

**Comment by richardhendricks** [comment]
http://tinyurl.com/GTNH-IGIX

**Comment by Dream-Master** [comment]
but please not display warp otherwise the litmus paper are useless

**Comment by richardhendricks** [comment]
No, it does not.
![image](https://user-images.githubusercontent.com/1214811/58208155-cd77ab80-7ca9-11e9-9884-8b966df657ec.png)

(and in ore chunk, when in ore chunk, and armor and active item durability)
