### ISSUE TITLE
(Quest Improvement Suggestion) The water dilemma #75 needs more information

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#4053]
#### Which modpack version are you using?
2.0.5.1 (Should apply to all)

#### What do you suggest instead/what changes do you propose?
Add more information to quest "The water dilemma #75"
https://ftb.gamepedia.com/Water_Tank_(Railcraft)

Information such as the tank not working in dry climates and needing to see the sky to work at full capacity would be greatly appreciated.

**Comment by richardhendricks** [comment]
Finite water is a problem. But fear not, there are solutions! I shall guide you to a steady supply of water. The Railcraft water siding tanks provides enough water to last the early game.\n\nThe humidity of a biome is very important and will increase the base fill rate.\n\nIf it is raining, the tank will fill much quicker.\n\nAt least one block of the water siding tank must see sky for the maximum output.\n\nThe best part is that you don\u0027t need a pump to extract water.  Tanks and pipes placed next to it will be autofilled by the water siding tank.\n
