### ISSUE TITLE
AE System - Cables #184 reward is a T5 EV lootbag 

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4058]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon

 The above mentioned quest rewards  a T5 EV lootbag, i am assuming this is a mistake. 
Most if not all quests in that section (have not done all yet) award an AE 2 lootbag.

If it is a mistake should be changed to AE2 lootbag instead of T5

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
This quest was make before they where any ae system tab or lootbags.
