### ISSUE TITLE
Quest issues mark II

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#406]
You gonna hate this # 3 - quest not accepting LV robot arm
Blank Gene sample - blank gene samples have an assembler recipe which HQM isnt accepting as crafting

**Comment by Dream-Master** [comment]
@Drobac 
 This is a Quest Issue only or why you link it.

**Comment by Drobac** [comment]
im just starting the list and adding as i go through quests

**Comment by Dream-Master** [comment]
Because it is linked to issue 3?

**Comment by Drobac** [comment]
better now? linked by accident

**Comment by Dream-Master** [comment]
ah ok

**Comment by Dream-Master** [comment]
I am not sure if i update the Quest yesterday with tghe update have to check and maybe restart the Server.

**Comment by Dream-Master** [comment]
I update the Server now 1.0.7.3a

**Comment by Drobac** [comment]
Endless evolution (Draconic cores quest) - atm not set to repeatable

**Comment by Dream-Master** [comment]
With the new Update 4.4.2  it can set to repeatable before it was brocken.

**Comment by Namikon** [comment]
All mentioned issues are resolved in 151203

**Comment by Dream-Master** [comment]
Ok downloaded and will be in the next Update.
