### ISSUE TITLE
Quest ID: 1154 Magnalium Crossbow Bolts Quest Description

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4060]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Was working on the quest to do magnalium crossbow bolts. The quest states that you cannot update your current bolts. That's what I expected to happen.
#
#### What happend instead? (Attach screenshots if needed)
I was able to upgrade my current bolts. They do have to be fully repaired for that.
#
#### What do you suggest instead/what changes do you propose?
Change the quest text or tell me I'm wrong and whatever? Also making the bolts didn't complete the quest so maybe just have the quest complete on making the iron tipped magnalium bolt itself and not the completed bolt?

**Comment by Anarack** [comment]
It says to not upgrade the bolts as they don't recalculate stats correctly.

**Comment by shawnbyday** [comment]
> It says to not upgrade the bolts as they don't recalculate stats correctly.

Crafting new bolts as suggested resulted in worse stats than upgrading my current ones.

**Comment by Dream-Master** [comment]
works I tested it.

**Comment by richardhendricks** [comment]
So we can upgrade bolts now in 2.0.6.6? Do you get the better stats as well?

**Comment by Dream-Master** [comment]
I did the quest and it complete
