### ISSUE TITLE
Update Seismic Prospector oilfields output to show corners of the oilfields.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4063]
Request to add chunk corners to the output of the seismic prospector oil field grid.

**Comment by richardhendricks** [comment]
Only need to provide corners of [5], players can figure out where the rest are from that.

**Comment by richardhendricks** [comment]
Also fix output
"Oil Notes : Prospect from NW to SE 324 chunks  (9 8x8 oil fields) ...."
should be 376

**Comment by Impos913** [comment]
Umm..
376?
9x8x8=576
??

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/70871724-aa735880-1f67-11ea-811b-d3dc342dfc64.png)

This shows where the prospector is located in the 8x8 field
![image](https://user-images.githubusercontent.com/1214811/70871734-caa31780-1f67-11ea-8310-5252fcc75f1c.png)

Does it add confusion or clarify anything? LOL.
