### ISSUE TITLE
Quest ID: 784 Large Bronze Boiler

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4066]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Followed quest to craft the boiler. Expected to be able to craft the boiler.
#
#### What happend instead? (Attach screenshots if needed)
The quest doesn't take in to account that you use one of the Bronze Firebox Casing to make the Large Bronze Boiler Controller.
#
#### What do you suggest instead/what changes do you propose?
This isn't a broken quest or crafting recipe but it would be helpful to update the quest to require the player to make 5 Bronze Firebox Casings instead of 4.

**Comment by Dream-Master** [comment]
yes will change it
