### ISSUE TITLE
Can not craft the OC:CHARGER in 2.0.6.2

### ISSUE THREAD

**Issue by odixus** [GTNewHorizons/NewHorizons#4067]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
multiplayer
#
#### What did you try to do, and what did you expect to happen?
when I try to craft a OC:Charger which needs two IC2:MFE chargers, I found that the MFE charger have no recipe to craft. so, my robot run out energy and can not been recharged.
#
#### What happend instead? (Attach screenshots if needed)
I put a salor panel upgrade into robot. but it can not provide enough energy.
#
#### What do you suggest instead/what changes do you propose?
Add the recipe of MFE charger.

**Comment by Dream-Master** [comment]
error in the mfe chage pad. Willl fix it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/52526207-a9252f80-2cb5-11e9-963c-6989ed3dccc5.png)
