### ISSUE TITLE
Can not craft Wooden Boots

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/NewHorizons#4068]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
On my private server
#
#### What did you try to do, and what did you expect to happen?
Try to craft boots
#
#### What happend instead? (Attach screenshots if needed)
Boots dont crafted
#
[Video](https://cdn.discordapp.com/attachments/276780134676037642/541995330355593227/Minecraft_1.7.10_2019-02-04_17-55-26.mp4)

**Comment by shawnbyday** [comment]
Wow that is strange! Is it just an inventory bug? Your server giving any errors?

**Comment by SKProCH** [comment]
@shawnbyday No, console clear

**Comment by boubou19** [comment]
check if there is no mismatches between the minetweaker scripts of the server and your scripts client side

**Comment by SKProCH** [comment]
Apparently this is some kind of server bug or java, after rebooting the server machine everything is working correctly.
