### ISSUE TITLE
HQM Quest reset sorry

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#407]
Due the Update i wrongly enable Hardcore mode. I try to disable it but the Quest are gone and you all have to start again. Sorry for that but i see no other way atm.
I am open an Issue at hqm git allready to give us a disable function ingame.

https://github.com/lorddusk/HQM/issues/103

https://github.com/lorddusk/HQM/issues/89

**Comment by UltraPeeks** [comment]
I looked into the code and I'm pretty sure that everything is saved in the players.dat file.
So replacing that file with a backup should restore the progress?
Regarding the disable command: I will try to make a PR later this week.

Well, at least I can open the quest book again

**Comment by Dream-Master** [comment]
Ok will try to get the player.dat from a backup yesterday.

**Comment by Dream-Master** [comment]
Vote try to get the Quest Player.dat back to 23.11.15 12 o clock ?

@UltraPeeks               yes [ ] no [ ] 
@Namikon                  yes [ ] no [ ]
@Drobac                    yes [ ] no [ ]
@DooMQuiGonJinn   yes [ ] no [ ] 
@Sergio_Kaarsan      yes [ ] no [ ] 
@Methes                    yes [ ] no [ ]  
@Teteros                   yes [ ] no [ ]

**Comment by Dream-Master** [comment]
@UltraPeeks 
Ok we get a disable funktion from the Devs.

https://github.com/lorddusk/HQM/pull/105
