### ISSUE TITLE
Large Steel Fluid Cell Fill Bug

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4071]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Put Large Steel Fluid Cell into Iron Railcraft Tank. I expected each cell to get 8000L of oil.
#
#### What happend instead? (Attach screenshots if needed)
Each cell only filled up with 4000L of oil.
#
#### What do you suggest instead/what changes do you propose?
Fix if possible? Also might be worth trying with other cells. I only have steel at the moment.

**Comment by Dream-Master** [comment]
Yea but in gt devices it works fine. Not sure why it fill only 4 Buckets in RC Tanks @richardhendricks  @bartimaeusnek any idea?

**Comment by richardhendricks** [comment]
https://github.com/Railcraft/Railcraft/issues/1062

**Comment by shawnbyday** [comment]
So more or less known issue but won't be fixed since 1.7.10 essentially? I'm ok with that was just wondering.

**Comment by richardhendricks** [comment]
The Railcraft license does not allow derivative works.  We could try forking it, fixing it,and submitting a pull request.

**Comment by draknyte1** [comment]
> The Railcraft license does not allow derivative works. We could try forking it, fixing it,and submitting a pull request.

Find the offending code and I'll fix it.

**Comment by shawnbyday** [comment]
> > The Railcraft license does not allow derivative works. We could try forking it, fixing it,and submitting a pull request.
> 
> Find the offending code and I'll fix it.
> 
> While you're at it, you should find the onRightclick for the IC2 cells, so I can patch that too. (It eats cells if they're full of water and you place them 😢)

I'll take a look. I've noticed that on the cells before. Sucks.

**Comment by Ethryan** [comment]
Darknyte i think i have found the cell and can handler https://github.com/Railcraft/Railcraft/blob/d342c512ceaa71eb9675079d8e8843e7608b9c02/src/main/java/mods/railcraft/common/fluids/FluidHelper.java#L49 at least.

and i think the 4000 mb limit is line https://github.com/Railcraft/Railcraft/blob/d342c512ceaa71eb9675079d8e8843e7608b9c02/src/main/java/mods/railcraft/common/fluids/FluidHelper.java#L38 in the same document

**Comment by draknyte1** [comment]
```
[[GT++ ASM] Railcraft PROCESS_VOLUME Patch]: Transforming mods.railcraft.common.fluids.FluidHelper
[[GT++ ASM] Railcraft PROCESS_VOLUME Patch]: Attempting to patch field PROCESS_VOLUME in mods.railcraft.common.fluids.FluidHelper
[[GT++ ASM] Railcraft PROCESS_VOLUME Patch]: Removing PROCESS_VOLUME.
[[GT++ ASM] Railcraft PROCESS_VOLUME Patch]: Injecting PROCESS_VOLUME with new value.
[[GT++ ASM] Railcraft PROCESS_VOLUME Patch]: Valid? true.
```

Done, expect it next commit.

**Comment by shawnbyday** [comment]
Thanks @draknyte1 and @Ethryan ! :D

**Comment by Dream-Master** [comment]
Not fixed in Build 71.hotfix but maybe in a newer version.
