### ISSUE TITLE
Check on Coins unlocks

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4073]
Seems like there is big period with no Coins quests unlocked early game.  
- Maybe add a few more Coins quest and/or shift the unlocks around.  
- Check out when oreberries unlock - probably need to unlock alu berries when alu needed? After smeltery completed?
- Maybe allow purchasing some more ores? Copper types would be nice since those are used so much for bronze and red alloy.  
- Maybe add purchasing clay?
- Allow purchasing crop sticks for early ic2 crops before cheap ones from the assembler? Coins + logs?
- Decrease cycle time for piston quest?  Don't give more pistons, but reducing time by 2x is OK. Still encourages people to automate and do large batches.
- Purchase logs? 
- Purchase alumite?

- Currently no way to convert coins. Add very bad conversion factor quests from Technician 1 coins to other coins.  8:1 or 16:1. (need to add new banker villager at some point)

**Comment by shawnbyday** [comment]
I'd hate to become 0lafe but in my current world I've never made a single Wrought Iron Ingot. I've purchased all of them with coins. I'm currently in MV. I was thinking the entire time I was buying them "this is too easy". Arguably they aren't hard but time consuming until you can make them efficiently in the arc furnace. The cooldown time seems about right but getting half of the amount of ingots would make this purchase equivalent to being able to buy 4 circuits.

Also there was an ore I was thinking it'd be helpful to add to the ore finding wand coins quest. I THINK it was Pyro something. To help find Magnesite I think in the Twilight Forest. Sorry at work so can't look up specific ore.

Just my unsolicited 10 cents :D

**Comment by richardhendricks** [comment]
Sounds fair, I'll look into the wrought iron amount and time.

**Comment by richardhendricks** [comment]
wrought iron unlock moved to after making wrought iron.  Repeat time doubled.

Steel ingot unlock moved to after LV assembler

Clay, Chad, Glass, cropsticks coins quests added.

piston time halved.

I dunno on the magnesite, seems like there is plenty of magnesium from almandine/sapphire veins as well?
