### ISSUE TITLE
woven backpack eating items

### ISSUE THREAD

**Issue by The1andonlyDarto** [GTNewHorizons/NewHorizons#4074]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I had 2 woven miner backpacks, and expected the items I couldn't pick up due to the first one filling up to go into the 2nd one or my own inventory. I opened said filled backpack at the same time as picking up the items.
#
#### What happend instead? (Attach screenshots if needed)
The items picked up all overrode the items in the filled backpack starting from the first slot and moving through them numerically until all items were picked up, overriding what was in there before. 
It is quite easy to replicate.
#
#### What do you suggest instead/what changes do you propose?
not sure, just reporting a bug.

**Comment by Dream-Master** [comment]
@Ugachaga any idea ? 2.0.5.1 is from 11.09.2018 so i  am not sure if it use lastest version.

**Comment by Ugachaga** [comment]
@Dream-Master it's about Forestry, I've never looked into it. Sounds like pretty rare little thing, just avoid opening filled backpack same time as picking up the items.

**Comment by Dream-Master** [comment]
ah sorry yea this bag from forestry.
