### ISSUE TITLE
each GT bee didn't produce COMBS anymore

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4075]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
looked at my alverys. NEI receipt -> two (to 4) same bees, one with, one without combs - this are the "old" one. Beeding tree seems to be the same of both.
#
#### What happend instead? (Attach screenshots if needed)
Produce just drones
#

**Comment by Dream-Master** [comment]
@Ngar1 if they dont breed they Gendustry bees. Throw them on the floor and wait they convert to real GT Bees. Now they work again.

**Comment by Dream-Master** [comment]
Gendustry bee deprecated one
![image](https://user-images.githubusercontent.com/2970688/52526118-4aab8180-2cb4-11e9-989a-81a6f1b80c64.png)

Gt bee new one

![image](https://user-images.githubusercontent.com/2970688/52526123-59923400-2cb4-11e9-8b17-74c5c0e0124c.png)
