### ISSUE TITLE
warn ppl somehow that using drawers over hoppers voids stuff

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4076]
drawers over hoppers voids stuff.

can we add a tooltip to drawers signifying this or something?

**Comment by Dream-Master** [comment]
sure. I din't know it but i can add such tooltip.

**Comment by Dream-Master** [comment]
there are hundred and more drawers need a tool tip @DoomSquirter so very much text
@bartimaeusnek any idea how to add it to core mod code give a tooltip to all drawers maybe with less code than add it manually ?

**Comment by DoomSquirter** [comment]
maybe do the reverse.  add tooltip to hopper instead?
Warning: don't put a storage drawer on top of a hopper.  

something simple.

**Comment by damug** [comment]
Even simpler, just add the warning to the quest asking a player to make storage drawers.

**Comment by Dream-Master** [comment]
yea good idea :P

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57199494-1f4bd200-6f45-11e9-96db-883f488538fc.png)
