### ISSUE TITLE
Suggestion: don't make IV chem reactor mandatory for quest progression

### ISSUE THREAD

**Issue by Paolkageist** [GTNewHorizons/NewHorizons#4078]
In order to unlock the quest chain that ends up with Polybenzimidazole in IV, you need to craft an IV chemical reactor.  However, you can skip this completely if you just upgrade your LCR to IV power.  The EV chemical reactor quest, in contrast, does not block any sort of progression and is not marked as a main quest; it even suggests you can use your LCR instead.  I gots better things to do with my IV circuits than dump them into a machine I'll never use.

**Comment by Dream-Master** [comment]
sure will do it optional side quest

**Comment by 0lafe** [comment]
Maybe switch it out for an IV hatch but keep it a main quest?

**Comment by Paolkageist** [comment]
That's fair.  Then maybe a bonus quest branching off of that for people who actually do make the chem reactor?

**Comment by Dream-Master** [comment]
I am not sure what is cheaper get an iv hatch which need iv superconductors or get a chem reactor iv ? @Paolkageist @0lafe

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/52526071-c0631d80-2cb3-11e9-96e0-2ec4e72e38d9.png)
![image](https://user-images.githubusercontent.com/2970688/52526078-c9ec8580-2cb3-11e9-9a4a-895eb8d5e63d.png)

**Comment by Anarack** [comment]
Or just use two ev hatches for the lcr. I wouldn't make any hatch/chem reactor a requirement when involving the lcr.

**Comment by richardhendricks** [comment]
Removed IV chem reactor requirement and rewards,

![image](https://user-images.githubusercontent.com/1214811/57199450-a8163e00-6f44-11e9-8161-5e9ca6ddf72a.png)
