### ISSUE TITLE
Carrot Quest

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#408]
Question from Player kebal22:
````
Don't you think that 64 carrot quest is much harder than any other on that level? Even if you find a village there is no guarantee that there are 64 carrots.
````

Open for discussion.

**Comment by Namikon** [comment]
There is nothing to discuss. You get carrots as reward, and you are asked to plant and multiply them. No need for a village

**Comment by nikitinalexx** [comment]
The question is not about village or not.
If i take all the quests from the first stage, it will take 10x less time to complete than the only carrot quest.
I planted them and after 2 hours of playing i got only one carrot grown. So to grow 64 carrots it will take hours.

**Comment by Namikon** [comment]
2 hours? That is indeed a problem; And I assume something must've changed with the growth / drop rate of plants then. They *do* take longer to grow, but you should get 2-5 carrots on each harvest. And, they should require about ~10 Minutes to mature; Which will rather quickly multiply to 64.

Anyways, gonna check that.

**Comment by Dream-Master** [comment]
It is in a ice/cold  biome that why i guess.

**Comment by nikitinalexx** [comment]
It is always 2 carrots btw.

**Comment by Namikon** [comment]
As I said, I guess something has changed with either Pam's, Hunger Overhaul or any other mod that changes crop behavior. I'll reduce the amount that is required for the quest

**Comment by nikitinalexx** [comment]
Another strange quest is the one that requires 4 Malachite Ore. Malachite is Iron level whereas it is the same quest that requires just Tin/Copper Ore. Such different level of requirements in the same quest...

**Comment by Dream-Master** [comment]
The First time i am doing this Quest too i have the same feeling but at this time i building my Tinkers Furnace make me some Bronze tools and make this quest very quickly.

**Comment by Namikon** [comment]
Changed to 10 Carrots in 151203

**Comment by Dream-Master** [comment]
Will be in the next Update.
