### ISSUE TITLE
Ticking Memory Connection

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/NewHorizons#4080]
#### Which modpack version are you using?
2.0.6.7a DEV
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Wrenched my IV aassembler to move it while in my clean room, was just wanting to move it.
#
#### What happend instead? (Attach screenshots if needed)
After it popped as an item and hit the floor, the game crashed with this error.
#
#### What do you suggest instead/what changes do you propose?
Here is a Pastebin of the crash    https://pastebin.com/s7zsNSNS

**Comment by Lithorn** [comment]
Confirmed still an issue in 2.0.6.7B DEV. Wrenching IV Assembler in Cleanroom force crashes SP Server

**Comment by Lithorn** [comment]
Fixed in 2.0.6.7C by reverting GT++ Nightly .1.7.02.82 to 1.7.02.71

**Comment by Dream-Master** [comment]
@Lithorn will be fixed soon as far Alkalus fix GT++

**Comment by boubou19** [comment]
do we know the changelog of gt++ past 1.7.02.71? if there is no major issue we could use the 1.7.02.71 in the update. What do you think?

**Comment by Dream-Master** [comment]
no we can't use 71 . I will post a changelog later
