### ISSUE TITLE
Computronics API don't work

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4082]
#### Which modpack version are you using?
2.0.6.2b
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Checked AE2 SpaceialIO Port and GT Machine OC API with Computronics.
#
#### What happend instead? (Attach screenshots if needed)
True in Config but False.
![2019-02-09_22 20 11](https://user-images.githubusercontent.com/40425798/52521414-4bdfad00-2cba-11e9-91c8-5b1e1e9d49da.png)
![2018_12_21_14_23_22_396](https://user-images.githubusercontent.com/40425798/52521435-80536900-2cba-11e9-8c83-c2e3718a9807.png)
#
#### What do you suggest instead/what changes do you propose?
Please fix it.

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
@yukieiji can you explain what you mean. I ask the Computronics  Dev @Vexatos and he haven't any clue too.

**Comment by yukieiji** [comment]
Sorry, my code is wrong and it was not a bug.

**Comment by Dream-Master** [comment]
@yukieiji issue can be closed ?

**Comment by yukieiji** [comment]
Please close this issue.
I'm sorry for troubling you.
