### ISSUE TITLE
ztones addon:chiseltones, not working on the offical server

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#4083]
#### Which modpack version are you using?
2.0.5.1 delta
#### What did you try to do, and what did you expect to happen?
basically the ztones addon, chiseltones gives the option(number 0)which is on every client and anyone who downloads the modpack to chisel ztone tile to different types of ztones (example: korp,ztyl and other weird names) but the server has the other option(number 1) which instead makes the types of ztones cycle between looks using chisel 
![image](https://user-images.githubusercontent.com/40670872/52523512-cbf61a80-2c9a-11e9-8996-881e84706b58.png) this is the config on the clients

the issue is no one can use the addon because it bugs and may crash you
#### What do you suggest instead/what changes do you propose?
the server has it on 1 but clients have it on 0, could you change the server back to 0?

**Comment by PoptartOverlord-Xabedo** [comment]
i should probably note that it works in singleplayer

**Comment by Dream-Master** [comment]
will check if that is fixed in newer version allready.

**Comment by boubou19** [comment]
also it can lead to crashes. i'll upload mine later

**Comment by Dream-Master** [comment]
I remeber it was suggested to be 1 long time ago. Why not change client to 1 too ? @boubou19 @PoptartOverlord-Xabedo or is this op?

**Comment by boubou19** [comment]
from what i understand, the crash happens because i tried to get too quicky the blocks from the gui. But imo the change clientside is not OP as long as you cannot uncraft the blocks to get ez resources.

**Comment by Dream-Master** [comment]
maybe change the client because server settings are ok. Bryfer suggest it 4 month before

**Comment by PoptartOverlord-Xabedo** [comment]
i don't think changing it to 1 is a good idea, its useless since you can simply scroll to change the textures,
keeping it at 0 would only make it for people to decorate their bases easier, nothing less nothing more.

**Comment by Dream-Master** [comment]
Ask @Bryfer why he changed it @PoptartOverlord-Xabedo

**Comment by Bryfer** [comment]
When this mod was added, wrong configuration was made.
Fixed server side 2.0.5.1 
after 2.0.5.1 it's fixed both server and client side.
It was never intended be change between block types, just to add chisel options to change the looks for easier automation
