### ISSUE TITLE
Pain/Agony(I-III) enchantment bypass any type of protection

### ISSUE THREAD

**Issue by DisasterMoo** [GTNewHorizons/NewHorizons#4085]
#### Which modpack version are you using?
2.0.6.1
#
#### If in multiplayer; On which server does this happen? 
Fully Toasted
#
#### What did you try to do, and what did you expect to happen?
We have a area claim plugin which disables PVP, the enchantment in question bypasses it. Also, the damage can kill vampires(bypass any protection, i guess it can even bypass creative armor).
#
#### What happend instead? (Attach screenshots if needed)
Killed me without any death messages(grave didn't spawn, lost items)
#
#### What do you suggest instead/what changes do you propose?
Disable the enchantment

**Comment by draknyte1** [comment]
Any clue what mod they're from?
I assume the server isn't running vanilla forge if there's plugins, so that's probably 90% of the issue.

**Comment by bartimaeusnek** [comment]
@draknyte1 i think they are from a thaum mod or from witchery.

**Comment by draknyte1** [comment]
> a thaum mod or from witchery

I figure as much, was just hoping someone knew which.. to save looking through several mods I know nothing about, lol.

**Comment by bartimaeusnek** [comment]
also vampirism is completely broken, therefore i dont see an issure here, but the protection bypass, which is a plugin so i dont see anything we could do there..

**Comment by draknyte1** [comment]
> i dont see anything we could do

You're not using enough ASM. 💾🔨💥

**Comment by bartimaeusnek** [comment]
@draknyte1 im almost 100% sure we dont need asm here and i see no reason to support plugins either.

**Comment by DisasterMoo** [comment]
they both are from special mobs

**Comment by DisasterMoo** [comment]
the worst problem of all is that when a player is killed by that damage the grave is lost, so are the items.

**Comment by bartimaeusnek** [comment]
@DisasterMoo graves can be restored even if the grave hasnt been spawned, if you die it will create a inventory file, but thats annoying i get that, will look into it when i find the time

**Comment by boubou19** [comment]
it's also the only way to kill a player with infinity armor (ways to force the player to loot his armor doesnt count)

**Comment by Dream-Master** [comment]
@DisasterMoo so far i remeber die @draknyte1 Open Blocks graves harder for hungry node protection. Not sure if this works against this issue too?

**Comment by DisasterMoo** [comment]
@Dream-Master The grave don't spawn if you are killed by that damage. Also, looks like some mobs can spawn with that type of damage that bypasses any kind of protection(and when you die your grave don't spawn).

Found how to fix: Change SpecialMobs.cfg configuration file like this:
_enchants {
    I:pain_bow=-1
    I:pain_sword=-1
    I:plague_bow=162
    I:plague_sword=163
    I:poison_bow=164
    I:poison_sword=165
}

**Comment by draknyte1** [comment]
The code probably isn't killing the player properly, if this *is* the case, then we probably need to fix it. (Cause then OB isn't aware people are dying and won't generate grave data) Don't we already have a fork of this mod? Should be easy regardless. 😎

If the code is good, it's related to the plugins/server setup and isn't strictly our issue to fix.

**Comment by bartimaeusnek** [comment]
@Dream-Master @DisasterMoo **DO NOT** remove the enchantment entirely, that mind corrupt worlds/servers.

**Comment by DisasterMoo** [comment]
On src/main/java/toast/specialMobs/EventHandler.java line 136 sets entity health instead of adding more damage to the event. Is that what causes this problem?

**Comment by draknyte1** [comment]
>  Is that what causes this problem?

![image](https://user-images.githubusercontent.com/3060479/52543479-f383da80-2da1-11e9-9862-791cd2e964d4.png)
As discussed with Bart before, yes.

**Comment by Dream-Master** [comment]
pain bow and pain sword are set to -1 did it mean it is disabled or @DisasterMoo did you change that?

**Comment by DisasterMoo** [comment]
Setting it to -1 disables the enchant(as per config annotation), yet, it's better not doing it @Dream-Master. As discussed, it's possible to corrupt worlds. Since you guys have a fork of SpecialMobs source, the best approach is to change line 136 of src/main/java/toast/specialMobs/EventHandler.java to the correct way of applying damage.

**Comment by draknyte1** [comment]
https://github.com/GTNewHorizons/SpecialMobs/pull/1

**Comment by Dream-Master** [comment]
@draknyte1 thanks and merged
