### ISSUE TITLE
Space Suit cannot be charged

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4086]
#### Which modpack version are you using?
2.0.6.2

#
#### What did you try to do, and what did you expect to happen?
I upgrade my space suit but cannot charge it.
I try GT,IC,EIO,OC's energy, all of them cannot charge the space suit.
I think maybe the suit can be charged by GalactiCraft generator, but there is no recipe of GC generator.
#
#### What do you suggest instead/what changes do you propose?
Add recipe of GC generator or make the suit can be charged by GT EU.

**Comment by DoomSquirter** [comment]
make the galacticrap solar gen.  you can put the parts for space suit in the gui and charge them there

I found the upgraded version to be mostly worthless iirc.  at least the head part at least.  had to redo the head one w/o final upgrade.

**Comment by bartimaeusnek** [comment]
the GC battery should be craftable and accepts GT-EU IIRC

**Comment by Kiwi233** [comment]
Thx, i will try

**Comment by bartimaeusnek** [comment]
ill close this as "answered"
