### ISSUE TITLE
silver plasma is uncraftable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4087]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i wanted to make silver plasma as the stargate crafts need it
#
#### What happend instead? (Attach screenshots if needed)
silver plasma is unobtainable because the plasma nerf from tectech is set to true as explained in #3427 
#
#### What do you suggest instead/what changes do you propose?
either make the silver plasma obtainable via fusion or change the recipes to use molten silver, even if imo the point of using silver plasma is to have players use the fusion to get the plasma, adding a bit of difficulty in the SG recipes.

**Comment by bartimaeusnek** [comment]
@Technus the SG recipes are in your repo, can you please change the Plasma there?

**Comment by Dream-Master** [comment]
@bartimaeusnek i have acess too what i need to change ?

**Comment by draknyte1** [comment]
I'd still like all 90~ Plasma to exist, regardless of craftability.

**Comment by Dream-Master** [comment]
Fixed in new version
