### ISSUE TITLE
Weird client startup crash

### ISSUE THREAD

**Issue by majorPhysics** [GTNewHorizons/NewHorizons#4089]
### Which modpack version are you using?
2.0.5.1 Newest version I think

### What did you try to do, and what did you expect to happen?
Technically my friend, we are trying to play this. Works perfectly on my computer, but when he tries to launch the pack, it crashes immediately and throws this in the log:

https://pastebin.com/7PyXUJ5Q

Quick side note: We installed it on twitch, and he noticed there was 2 instances of the forestry mod. I don't know if he's having problems with twitch or with this modpack, but this has happened before and has really limited what modpacks we can play. Really any explanation or workaround would be greatly appreciated.

**Comment by bartimaeusnek** [comment]
@majorPhysics install it with the technic launcher. twitch isnt supported anymore.

**Comment by Dream-Master** [comment]
@majorPhysics 2.0.5.1 works with curse/twitch but newer version like 2.0.6.2 not. Maybe i will add a dependencies loader to the pack that it loads up the mods we cant host on curse from another place.
