### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#409]
http://pastebin.com/aM0SV89x - An Ender IO issue that isnt letting me log on

**Comment by Dream-Master** [comment]
Ok will look inside it.

**Comment by Dream-Master** [comment]
@Drobac 
Sorry Drobac i don't know what i can do atm. Maybe i can start the Server in Peaceful mode and hope all mobs are gone and sich later back to hard?
Wait for the Dev hopefully finding something to fix it or a solution?
Get you an older Player.dat file only for now?

@Namikon 
Any Idea here.

**Comment by Namikon** [comment]
No, that's new

**Comment by Dream-Master** [comment]
Id 30 is Lava Monsters. So maybe it could be that.

**Comment by Dream-Master** [comment]
Yes it seems to be Lava Monsters. I test it in Sp and without lava Monsters there is no Entity Id 30.
Tomorrow i try to launch the server without this mod and add it later back. Sorry i too tired today to do it.

**Comment by Drobac** [comment]
ok thanks

**Comment by Dream-Master** [comment]
Problem solved i remove Lava Monsters. To buggy i think

@Drobac try to join.

**Comment by Dream-Master** [comment]
One time i dont crash now i crash again without Lava Monsters.

**Comment by Dream-Master** [comment]
It wasnt Lava Monsters it was the Portal to the Deep Dark from Extra utilities. When spawned over the Block the Game crash. I remove this blocks and the issue is solved for now.

**Comment by Dream-Master** [comment]
Ok will re add Lava Monsters back in the next Update.

**Comment by UltraPeeks** [comment]
Now I got the same problem:
https://gist.github.com/UltraPeeks/f110d43726d3e9a3f969
It's in the Nether right at my portal

**Comment by Teteros** [comment]
Same error as UltraPeeks above, but with a different portal.

**Comment by Dream-Master** [comment]
Ok as soon i am on my Computer i will destroy the Portals that you can login again. After this i will look wich mod and Version cause the problem.
@UltraPeeks  Your Position i see allready in the Error log.
@Teteros I need your position to close your Portal.

**Comment by Dream-Master** [comment]
SO testing now on the testserver wich mod fu*** up the whole pack.

**Comment by Dream-Master** [comment]
I can't reproduce this error. I make different portals on the Test Server and not get any crash.

**Comment by Dream-Master** [comment]
Until now i cant find any explanation why this error happens.
@UltraPeeks
@Namikon
@Teteros
Could need help with this.

**Comment by Teteros** [comment]
Partially fixed with nether and end dimension resets.
