### ISSUE TITLE
Arcane assembler recipie is still not working as intended

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/NewHorizons#4090]
#### Which modpack version are you using?

#2.0.5.1
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
craft Arcane assembler
#
#### What happend instead? (Attach screenshots if needed)
nothing 
![image](https://user-images.githubusercontent.com/25811344/52652824-166fd500-2eef-11e9-9cbf-9e99684ba779.png)

#
#### What do you suggest instead/what changes do you propose?
still recipie conflict with the wand?

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/52652961-520a9f00-2eef-11e9-9c68-e75b79a0c704.png)

**Comment by Dream-Master** [comment]
What is wrong here @Ghengis88 ?

**Comment by Dream-Master** [comment]
What is wrong here @Ghengis88 ?

**Comment by Ghengis88** [comment]
recepie wont start, dont know why

**Comment by Dream-Master** [comment]
can you use /mt hand on the want that i can check why it not start ? @Ghengis88

**Comment by Ghengis88** [comment]
ok will do that. what will /mt hand do?

**Comment by draknyte1** [comment]
> ok will do that. what will /mt hand do?

It's used for dumping data about the item you are holding for Minetweaker.
But it's also the easiest way to get an item's FQRN.

**Comment by Ghengis88** [comment]
ok, server is restarting atm will do this when i get back online

**Comment by boubou19** [comment]
iirc ./mt hand doesn't work on delta/epsi because it needs OP permissions

**Comment by Dream-Master** [comment]
you can use /iih too not sure if this work.

**Comment by boubou19** [comment]
just tried it on delta and it needs OP permissions too sadly.

**Comment by Dream-Master** [comment]
ok

**Comment by Ghengis88** [comment]
Had to go and did not have time to try. But if  it did not work on delta i dont think i will be able to

**Comment by boubou19** [comment]
what you can do is dumping your inventory with the concerned items by opening your inventory, click on the "option" button on the bottom left corner, then clicking on the "tools" button, data dump, nei integration and finally click on the button to dump the player inventory.

**Comment by Ghengis88** [comment]
Will try that

**Comment by Ghengis88** [comment]
Slot,Display Name,Amount,Damage,Max Damage,Item ID,Unlocalized Name,Item Class,NBT
27,Thaumium Bossed Silverwood Scepter,1,81,0,Thaumcraft:WandCasting,item.WandCasting,thaumcraft.common.items.wands.ItemWandCasting,"{aqua:15000,terra:14388,ignis:15000,cap:""thaumium"",rod:""silverwood"",ordo:15000,sceptre:1b,perditio:15000,aer:14388}"

**Comment by Ghengis88** [comment]
now it was full but i tried first with it fresh from crafting and never charged

**Comment by Dream-Master** [comment]
can you check now the quest file ?

**Comment by Ghengis88** [comment]
i dont understand.
you have exact name of file?

**Comment by Ghengis88** [comment]
Can i ask a operator to spawn the item in in exchange for materials?

**Comment by Ghengis88** [comment]
Terra and aer are Only 14388, could this be the problem?

**Comment by boubou19** [comment]
try to charge it to max

**Comment by Dream-Master** [comment]
yes i guess this is why it not working. Fill up the wand to 100% each aspect @Ghengis88

**Comment by Ghengis88** [comment]
yep, sorry for not checking, it had lost 1 terra and aer due to i me having runic shielding on a few items
