### ISSUE TITLE
EV epichlorohydrin quest

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4091]
#### Which modpack version are you using?
2.0.6.2

#### What do you suggest instead/what changes do you propose?

The quest asks for glycerol cells to make it, but there's other ways to make it. Maybe just ask for 4 cells as the only step. Quest#1228 in EV.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57199418-405ff300-6f44-11e9-88d6-156a00d42014.png)
