### ISSUE TITLE
Server crash - SpecialMobs ConcurrentModification

### ISSUE THREAD

**Issue by DisasterMoo2** [GTNewHorizons/NewHorizons#4094]
https://pastebin.com/Y45Sn412

Looks like some parallel thread try to update SpecialMobs and makes the server crash. Also, not sure, but the 3 times that happened today swords with these enchants were involved:

![967005ab9b52caa166e5cdad60748196](https://user-images.githubusercontent.com/46634059/52766300-e9feaa80-300d-11e9-9e7c-ce387c3c1c8d.png)

**Comment by Dream-Master** [comment]
which version of the pack do you using @DisasterMoo

**Comment by DisasterMoo** [comment]
@Dream-Master Sorry, forgot to mention. 2.0.6.1 in Fully Toasted server.

**Comment by Dream-Master** [comment]
@DisasterMoo maybe its some kind of over encahnted sword. IDK need to ask my dev commuity
