### ISSUE TITLE
Coins Quest Recommendation

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4098]
#### Which modpack version are you using?
2.0.6.7c-dev
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Was thinking maybe we can add a coins quest to buy crop sticks?

**Comment by richardhendricks** [comment]
I think I already did this.  Check the latest revision.

**Comment by Dream-Master** [comment]
@shawnbyday  /bq_admin default load
