### ISSUE TITLE
Circular Dependency: Tungstensteel Ingot requires EV Energy Hatch, EV Energy Hatch requires Tungstensteel

### ISSUE THREAD

**Issue by Flincae** [GTNewHorizons/NewHorizons#4099]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private Friends and Family Server
#
#### What did you try to do, and what did you expect to happen?
I went to vacuum freeze my Hot Tungstensteel Ingot, however the recipe requires EV Voltage.  All other related Tungstensteel recipes are HV voltage.  The new energy hatch recipe for EV energy hatch requires fine tungstensteel wire to make the coils... As such i'm now tier blocked as there is a circular dependency to obtain Tungstensteel Ingots.   Unless there's a means to cool hot ingots that I'm not aware of, or are we expected to install 4 HV energy hatches into one vacuum freezer? (Not sure if that even works)

Suggested Change:
Can the coils for the EV energy hatch be changed to it's tier material Titanium or Neodymium? or Tungstensteel Vacuum Freeze recipe be downgraded to HV voltage?

**Comment by 0lafe** [comment]
Except you can put 2 HV hatches on a vac freezer and run it at EV. I just made 16 of them on 6.2 no problem

**Comment by Flincae** [comment]
It's 1920 recipe so it would take 4, not just 2, I know 2 will work, but will 4?

**Comment by 0lafe** [comment]
I wanna say multiblocks are limited to 2 energy hatches, but 4 wouldn't do much, running it at 2048 or 4096 still comes out to EV, as IV would require close to 8192. Maybe you can put 8 hatches on it and run it at IV? but either way, this totally works and that's more of a curiosity/weird tiering for some ebf stuff

**Comment by Flincae** [comment]
Oh I wait a sec, so I think I don't get how this all works.  Since the HV energy hatch can take 2 amps, I need to have 2 generators feeding each energy hatch to get to the 2048 eu/t?

**Comment by 0lafe** [comment]
I run a 4A HV cable from an EV->HV transformer to the vac freezer, and connect it to the hatches. Think of it like making your first Al with LV hatches. 2A per hatch, 4A total of HV to make 1A EV. 2 generators on each hatch totally works, or 4 feeding all 4, there really isn't a right way to do it

**Comment by Flincae** [comment]
Sweet, ya I got it working, thank you

**Comment by Flincae** [comment]
Sweet, ya I got it working, thank you!
