### ISSUE TITLE
Displayed and actual recipes are different

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#410]
Here is what NEI is showing, there are only two recipes as you see
http://imgur.com/sATR2l4
And here what the actual recipe is (i randomly found it)
http://imgur.com/ELQhPuH
And i can only guess which recipes are also broken like this.. And quest book won't help, because the actualy recipe is not shown anywhere...

**Comment by Dream-Master** [comment]
Not sure what Texture Pack do you using ? Did you try to craft the vanilla Recipes and it works?
Did you scripts Folder load without any errors? 
With Vanilla Texture i never have this error.

Can you try in Singleplayer crafting these Bricks with the Vanilla recipes ?

**Comment by nikitinalexx** [comment]
I am using ChromaHills-128x_1.7v11
If Vanilla recipes are those two on the first screenshot then
No, i can't craft them in Multiplayer and
Yes, i can craft them both in Singleplayer.
No, i didn't have any errors. I'm using techniclauncher.

I doubt there is any link between Texture Pack and NEI.

**Comment by nikitinalexx** [comment]
https://goo.gl/OLfzTl

**Comment by nikitinalexx** [comment]
https://gist.github.com/nikitinalexx/954c92f4015a0b2d1ee9

**Comment by Dream-Master** [comment]
Try this one:

https://www.dropbox.com/s/y5wz07cxvplj9u8/scripts.zip?dl=0

**Comment by nikitinalexx** [comment]
https://gist.github.com/nikitinalexx/849e5bd003e3181f2b3e

**Comment by nikitinalexx** [comment]
I found the problem. NEI in Multiplayer uses the server scripts, not the local. So you need to remove ' from server scripts and it should solve the problem.

**Comment by Dream-Master** [comment]
I fixed Forestry and Railcraft. In Buildcraft i cant find any '.

**Comment by Dream-Master** [comment]
So try it again and send me the minetweaker.log

**Comment by nikitinalexx** [comment]
This worked, all errors gone except this one
ERROR: Error loading Build-Craft.zs: stanhebben.zenscript.parser.TokenException: Invalid character at Build-Craft.zs:401 - В

**Comment by Dream-Master** [comment]
Server runs normal 30% Memeory usage 100% CPU means 1 Core from 6 is used.
Not sure why the Server is so slow. I contacted Namikon allready. 

With the Buildcraft Script i am not Sure why is schows an error. Maybe you can test this in SP delete those Line 401 and see if its gone.

**Comment by nikitinalexx** [comment]
Yes, removing this line
401:  // --- Gears ---
fixed the problem in SP.

**Comment by Dream-Master** [comment]
Maybe ther is a hidden ' inside. Will fix it.

**Comment by Dream-Master** [comment]
@nikitinalexx 

Did you have any error now?
Can this be closed?

**Comment by nikitinalexx** [comment]
No error, closing.
