### ISSUE TITLE
typo in quest 820

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4100]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was reading the quest 820
#
#### What happend instead? (Attach screenshots if needed)
there are some unknown symbols in the text: "Every rocket needs a �4�0�4launch pad.�0 Build a 3x3 launch pad to place your rocket."

**Comment by combusterf** [comment]
Allow me to add a little grammar improvement while we're on the subject:
```Every rocket needs a launch pad.

Build a 3x3 launch pad and place your rocket on top of it.```
