### ISSUE TITLE
how hard would it be to add a time to load pack counter that gets logged each startup?

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4104]
would be interesting but not seriously useful if there could somehow be a way to time how long the pack loads and log the final gtnhaflops time in log file.  could be used as a unit of measure, bragging rights, etc....

**Comment by MineAnPlay** [comment]
https://minecraft.curseforge.com/projects/loading-profiler/files/2257233. Should show loading times of mods and classes that took the most time. Doesn't show the exact loading time of the pack though, just go to your latest.log and look at the time of start up and search for one of the things that popup at the end of the loading :P.

**Comment by richardhendricks** [comment]
Yeah the logfile will include loadtimes for you. For servers, I added a progress indicator during the oredicting so players would stop killing it while waiting for the cake to bake.

**Comment by draknyte1** [comment]
I already have this in my dev builds of GT I use locally, Should probably just PR it into master.
