### ISSUE TITLE
new space bees bug

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4105]
#### Which modpack version are you using?
2.0.6.2

#### What do you suggest instead/what changes do you propose?

Dropping then picking up the space bee after the bee change kicks you from the server and gets you stuck in a kick loop. 
https://www.dropbox.com/s/wschmlvkctipkbq/fml-client-latest.log?dl=0

**Comment by DoomSquirter** [comment]
sorry not sorry


SPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACE
