### ISSUE TITLE
Head duplication with Vajra

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#4106]
Modpack version : 2.0.5.1

Happened on official Delta server

Tried to break head with Vajra right click when using Silk Touch mode.

It drops two heads instead of one
![2019-02-17_01 45 55](https://user-images.githubusercontent.com/27481104/52906894-8a471000-3256-11e9-8a56-2cce5fb5b686.png)
![2019-02-17_01 46 00](https://user-images.githubusercontent.com/27481104/52906897-903cf100-3256-11e9-9658-c1b0b6e83471.png)

**Comment by Dream-Master** [comment]
nice but at this age you dont care about a few extra heads. Not sure if this is fixable.

**Comment by mulisz100** [comment]
Well they are still very usable and with that bug you have basically free aspects. Especially Spiritus which is essential in making Ichor

**Comment by richardhendricks** [comment]
Vajra is part of GraviSuite
