### ISSUE TITLE
Everburing Urn causing client crashes.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#4108]
#### Which modpack version are you using?
2.6.2 and 2.6.4 SinglePlayer

Everburning Urn (from Thaumic Exploration) causing server crashes. With 32 urns happening every couple of hours.

[crash-2019-02-15_14.10.35-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2873077/crash-2019-02-15_14.10.35-client.txt)

**Comment by bartimaeusnek** [comment]
@drayath thats a client crash log...

**Comment by Dream-Master** [comment]
wow wondering where you get 2.6.4 or did you mean 2.0.6.8?

**Comment by drayath** [comment]
Whoops, Technic launcher shows version 2.0.6.2 (latest as of 15th Feb) and also in the update that happen today (17th Feb) that does not yet have a latest version note added in the launcher.

**Comment by Dream-Master** [comment]
yes will add that later.

**Comment by drayath** [comment]
Just going though my log folder, here is another EverburningUrn.generateVisEffect() crash that appears to be from the server (2.0.6.2) this time.

[crash-2019-02-17_14.41.26-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2873260/crash-2019-02-17_14.41.26-server.txt)
