### ISSUE TITLE
Add RT Item Filter to Voiding Drop Filter quest

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4109]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Quest ID 1863 "Throwing out the trash" has you make a voiding drop filter but it doesn't state you need to make a filter.

I suggest adding at least one quest after that one is complete that walks people through making an item drop filter and how to use it for something like voiding cobblestone. I incorrectly made a block filter instead of an item filter and only made that after quite some time troubleshooting.

**Comment by richardhendricks** [comment]
The RT item filter needs a GT filter which needs zinc and steel. I'm just going to add the RT item filter as a reward item.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57198265-6aaab400-6f36-11e9-8a7e-74543a3089c3.png)
![image](https://user-images.githubusercontent.com/1214811/57198268-7302ef00-6f36-11e9-8e40-ebfae8318187.png)
@shawnbyday Please verify my instructions.

**Comment by shawnbyday** [comment]
Looks good to me. Nice to get the item filter as a reward!
