### ISSUE TITLE
MASSIVE SERVE LAG TODAY 28.11.15

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#411]
We have a massive Server Lag and i am not sure who or what it cause.
Maybe because it is only a VPS Server.
Or someone load too many chunks?
Or because on the Weekend the Server is so busy.

@chrysator 
@Namikon 

Any plans what we can do. With a TPS of 3 no one can play.
Any solutions? Need help with this please.

**Comment by Dream-Master** [comment]
VOID 9 using 52 ms
VOID 8 using 18 ms

Mean we cant have a TPS from 20 allready with this two Dims.

![image](https://cloud.githubusercontent.com/assets/2970688/11452170/f2683b90-95de-11e5-95a2-f196c3c390e9.png)


The  Ping goes up and Down 
![image](https://cloud.githubusercontent.com/assets/2970688/11452168/e710af7a-95de-11e5-8225-8c4204bd5bcd.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/11452172/03a799e6-95df-11e5-9da9-e3f4fe0b4f58.png)

**Comment by Namikon** [comment]
I disabled my entire dim for now, as I don't have time to play anyways at the moment; That should free up enough resources to boost the TPS back to normal.

**Comment by Dream-Master** [comment]
Thanks.
