### ISSUE TITLE
Sever freeze/Crash net.minecraftforge.event.entity.living.LivingHurtEvent

### ISSUE THREAD

**Issue by alphaomega21** [GTNewHorizons/NewHorizons#4110]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
Private Server
#

Below is the error. Seems to randomly happen after playing a while. Full log is also attached as a file.
[fml-server-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/2873428/fml-server-latest.log)

EDIT: 

https://hastebin.com/olapelafot.rb
Do not post long error logs please. Use pastebin, hastebin or any other service. -bartimaeusnek

**Comment by draknyte1** [comment]
Any custom mods added?
Are your file permissions set up correctly?

**Comment by alphaomega21** [comment]
No custom mods just 2.0.6.8 on a fresh Linux VM. As far as I can tell the file permissions are all correct.

**Comment by HiDeRush** [comment]
Exactly the same problem, confirm

**Comment by Dream-Master** [comment]
Its a special mobs/GC issue.

**Comment by HiDeRush** [comment]
Enchantment "Pain" from Special mobs, any attack with weapons (mobs Or player) with this enchantment leads to freezing the server. 100% reproducibility

**Comment by draknyte1** [comment]
That means I broke it, woot!

**Comment by Dream-Master** [comment]
ok waiting for a fix @draknyte1

**Comment by Dream-Master** [comment]
@draknyte1 any news here or should i revert it so long you fixed it?

**Comment by wiloxe** [comment]
Any updates?

**Comment by Dream-Master** [comment]
@wiloxe downgrade Special mobs to 3.3.0 so long @draknyte1 push a fix for it.

**Comment by HiDeRush** [comment]
mb a good solution is to just disable this enchantment in the configuration file ...temporarily, I did it and no more problems.

**Comment by draknyte1** [comment]
`mb a good solution is to just disable this enchantment in the configuration file ...temporarily, I did it and no more problems.`

How about we don't disable it due to the several reasons already suggested.
Rolling back one version is the *proper* fix, pain simply won't generate any graves and you'll lose everything on death. 

This is what _YOU_ get for using a *BETA* version. __Deal with it.__
