### ISSUE TITLE
Issue with Quest 798's NBT Data

### ISSUE THREAD

**Issue by proEndreeper** [GTNewHorizons/NewHorizons#4113]
#### Which modpack version are you using?
Greg Tech: New Horizons 2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Personal Server for friends
#
#### What did you try to do, and what did you expect to happen?
A player on my server attempted to complete the second task of "Iron capped Greatwood Wand" quest (Quest ID: 798), and expected for the quest to be completed as they had an iron capped greatwood wand in their inventory.
#
#### What happend instead? (Attach screenshots if needed)
The quest didn't detect the iron-capped greatwood wand in their inventory.
#
#### What do you suggest instead/what changes do you propose?
Change so instead of looking for the stats of a gold capped wand, the quest looks for an iron capped wand's stats.

This is what the player's iron capped wand looks like
[https://i.imgur.com/2dUhMwC.png](https://i.imgur.com/2dUhMwC.png)

The following was changed in both the DefaultQuests.json and the DefaultQuests-us.json on my personal server to allow quest completion. (Note the line numbers are based off 2.0.6.2's files, they may differ in the latest version)

Lines 74133 - 74157 in DefaultQuests.json

Lines 74091 - 74158 in DefaultQuests-us.json
```json
        {
          "partialMatch": true,
          "ignoreNBT": false,
          "consume": false,
          "autoConsume": false,
          "requiredItems": [
            {
              "id": "Thaumcraft:WandCasting",
              "Count": 1,
              "OreDict": "",
              "Damage": 3,
              "tag": {
                "aqua:4": 1000,
                "terra:4": 800,
                "ignis:4": 600,
                "cap:8": "iron",
                "rod:8": "greatwood",
                "ordo:4": 1500,
                "perditio:4": 1600,
                "aer:4": 200
              }
            }
          ],
          "taskID": "bq_standard:retrieval"
        }
```

**Comment by richardhendricks** [comment]
I don't understand.  An iron capped greatwood wand has a Vis limit of 50, which aligns with the quest requirements.  All you changed here was make the quest require a wand charged identically to your player. I am going to set the NBT tags for the vis to 0 to see if that fixes it.  Will also do gold capped wand quest as well.
![image](https://user-images.githubusercontent.com/1214811/57199362-b57ef880-6f43-11e9-86ab-69b563f2aea7.png)
![image](https://user-images.githubusercontent.com/1214811/57199367-bd3e9d00-6f43-11e9-9f7c-14321ab2628b.png)

**Comment by proEndreeper** [comment]
I can't remember but I think the issue was that the individual tags for the attribute capacity (aqua, terra, etc.) of the wand is what caused the player to not be able to complete the quest. Their wand had the capacity as different values. 2 8 6 10 15 16 were the wand's capacity attributes, and the previous values for the quest were 50 50 50 50 50 50, which I think is what caused issues.

I am not knowledgeable in how to use thaumcraft, but I had looked at the player's inventory to determine how the NBT for that particular wand was.

Your fix might work, but I don't know enough about how better questing behaves with NBT values to know if it'll accept anything above 0 vis/capacity.

**Comment by Dream-Master** [comment]
@richardhendricks why switch it to a empty wand. I want that the quest complete if you collect vis allready ?

**Comment by richardhendricks** [comment]
When you make the wand in the table, it has 0 vis.

**Comment by Dream-Master** [comment]
that's true. So you add a new step to quest?

**Comment by richardhendricks** [comment]
I just changed it to 0 vis wands like the other quests.

**Comment by Dream-Master** [comment]
ok
