### ISSUE TITLE
Naquadah Reactor Mark II

### ISSUE THREAD

**Issue by Dr4cos** [GTNewHorizons/NewHorizons#4115]
#### Which modpack version are you using?
2.0.6.8 
#
#### If in multiplayer; On which server does this happen? 
myFTB and single player
#
#### What did you try to do, and what did you expect to happen?
Using Naqaudah enriched rods as a fuel in the Naquadah IV Single Block, as seen in the questbook 
#
#### What happend instead? (Attach screenshots if needed)
The reactor isn't using any of the enriched naquadah fuels(bolt, rod, longrod, ingot)
#
#### What do you suggest instead/what changes do you propose?
fixing it

**Comment by draknyte1** [comment]
It was changed recently during beta. 

Point yourself to the changelog or search Naquadah in the GT5 repo by the GTNH team.

**Comment by Dr4cos** [comment]
Thanks for the fast answer.
https://www.technicpack.net/modpack/mcnewhorizons.677387/changelog
https://www.gtnewhorizons.com/forum/m/36844562/viewthread/28973236-serverchangelog/post/137055268#p137055268
In both changlogs I only find "-fix naquadah reactor wiredness" under 2.0.5.1

where do I "find GT5 repo by the GTNH team"?

**Comment by boubou19** [comment]
here is the GT5 repo of the GTNH team: https://github.com/GTNewHorizons/GT5-Unofficial

**Comment by Dr4cos** [comment]
the only changlog that I can find up to version 5.09.31. Only the "Naq Gen MK3" is described.

I'm trying right through all Enriched Naquadah items, both liquid and solid, but I can not get the fluids into the block and it does not take the solids

**Comment by Dream-Master** [comment]
@Dr4cos @boubou19 is the description wrong or the fuel rod/bolt etc ?

**Comment by boubou19** [comment]
i can only speak for 2.0.5.1 and it was used to need enriched naquadah rods

**Comment by 0lafe** [comment]
There were some new naq fuels added in hopes of a large naq gen for UHV+, but there aren't done nor does the generator exist. Idk if doing that stuff messed with normal naq gens though?

**Comment by Dr4cos** [comment]
2.0.6.8 
![naq](https://user-images.githubusercontent.com/33230359/52971617-6e5b7f80-33b8-11e9-9766-4403b71b7529.png)

**Comment by HawkridgeV** [comment]
Same story here, Mark III and IV stopped working with the correct fuel..
