### ISSUE TITLE
[quest suggestion] distillation tower quest second page

### ISSUE THREAD

**Issue by Beyond-Veil** [GTNewHorizons/NewHorizons#4117]
#### Which modpack version are you using?
2.0.6.x

#### What do you suggest instead/what changes do you propose?

The distillation tower quest's (#768) second page suggests using all HV hatches for the tower. Given the changes to hatches, the cost and the changes to recipes, this seems out of touch with how nearly anyone would build it.

2x MV power can run any recipe, except pollution and acetone separation (which i would consider "niche" settings). All the "popular" recipes run on a single MV energy hatch, with the exception of heavy oil.

HV hatches/bus are much larger than anyone would need. For most recipes, no "Solid" output is required and you would put in an ULV bus.

Most HV tier multi's already allow you to pick and chose the hatches and power solution. Maybe allow this for the tower as well

**Comment by 0lafe** [comment]
You *could* add an ore dictionary tag to diff hatches so the quest could ask for fluidHatch and it would let you turn in any tier. I think that would work

**Comment by Dream-Master** [comment]
no not a good idea. Nat that it can be inter change able after.

**Comment by draknyte1** [comment]
> You _could_ add an ore dictionary tag to diff hatches so the quest could ask for fluidHatch and it would let you turn in any tier. I think that would work

BURN.
Stop fucking suggesting how *NOT* to use the Ore Dictionary.
It's intended _ONLY_ for items worth 1:1. If they're not 100% equal, they should *NOT* have a tag.

**Comment by Dream-Master** [comment]
i guess we find another way

**Comment by richardhendricks** [comment]
I removed the hatches except for the maintenance hatch from the requirements, and added text.
![image](https://user-images.githubusercontent.com/1214811/57199026-d80f1280-6f3f-11e9-998b-959e0ded85e8.png)
