### ISSUE TITLE
[Delta] server plugin with gratituous permissions

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#4118]
#### Which modpack version are you using?
N/A; The server runs a flavour of Essentials 

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
the commands /workbench and /enderchest are available for all users, workbench allowing tier-0 quest skipping and enderchest providing significant convenience well before actual enderchests (or backpacks for that matter) are available.

#
#### What do you suggest instead/what changes do you propose?
Disable or limit the use of these commands to some higher ranks

**Comment by richardhendricks** [comment]
These are features enabled/disabled based on the server donations being met.
