### ISSUE TITLE
GT++ Cutting Factory & Industrial Material Press

### ISSUE THREAD

**Issue by Dr4cos** [GTNewHorizons/NewHorizons#4121]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
MyFTB
#
#### What did you try to do, and what did you expect to happen?
Placed the Control Core Modul
The GT++ Cutting Factory will not complette with the Control core Modul
![cutting](https://user-images.githubusercontent.com/33230359/53049384-40993800-3497-11e9-8cd8-d53228a08827.png)

Industrial Material Press is forming correct but the blocks don't change color

![material press](https://user-images.githubusercontent.com/33230359/53049700-eea4e200-3497-11e9-9460-f2ed577da598.png)

#
#### What happend instead? (Attach screenshots if needed)
The Cutting factory is not forming correct.
Material Press ist working correct, but ist not coloring the blocks right
#
#### What do you suggest instead/what changes do you propose?
Getting the cutting factory working und that the Material Press ist working

**Comment by Dream-Master** [comment]
2.0.6.8 is a beta version. Would be nice to post this issue on gt++ too. thanks @Dr4cos

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus

**Comment by Glammi** [comment]
Material Press is working only the color won't change

**Comment by Dream-Master** [comment]
I guess we get a new version from Alkalus the Gt++ dev soon if you post it on his github site too @Glammi
