### ISSUE TITLE
MV Solar quest ingredients - wrong wire flavour.

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#4123]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I had completed the quest-listed ingredients for the MV solar panel and expected to be able to use them to craft the actual panel.

#
#### What happened instead? (Attach screenshots if needed)
The MV panel did not appear in the crafting output. On very close inspection it turned out that the wrong wires were being used - the recipe and the quest one are different, but are visually indistinguishable and textually almost indistinguishable.

#
#### What do you suggest instead/what changes do you propose?
Update the quest to contain the superconductors rather than the raw wire material

**Comment by Dream-Master** [comment]
sure Solar panels get a quest fix soon
