### ISSUE TITLE
ReRequirement for fusion quest line

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4124]
#### Which modpack version are you using?
2.0.6.8
#

#### What do you suggest instead/what changes do you propose?

Fusion quest line is locked behind "this is the end?..." which is early IV. Fusion takes the assembly line and LuV to make, so I'd suggest locking it past the first LuV quest, which itself needs the assembly line quest.

**Comment by Dream-Master** [comment]
sure. before there are no luv quests

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57198956-d55fed80-6f3e-11e9-995a-37161fe29b2c.png)
