### ISSUE TITLE
small neutronium batteries (UHV tier) last ridiculously short

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4127]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was thinking about powering one assembly line in UHV so i started looking into a battery setup.
#
#### What happend instead? (Attach screenshots if needed)
i made some maths:a fully charged small neutronium battery (UHV tier) is holding 6,553,600,000 EU. 
UHV tier is consuming 2,097,152 EU/t. So 6,553,600,000/2,097,152 = 3125 ticks = 156 sec

the regular batteries such as sunnarium/naquadah/neutronium have all this 3125 ticks. But tiers below UHV have also energy orbs/clusters that last way much longer: Let's take the UV tier for exemple:
the large naquadah battery lasts 3125 ticks, but the energy cluster lasts 190735 ticks that's around 2 hours and 39 minutes. There is also ultimate batteries. But generally there are two batteries for each tier, starting to IV but starting to UHV there is only one kind of battery. 
#
#### What do you suggest instead/what changes do you propose?
Well, considering recipes such as Stargate-radiation-containment-plates that needs 1h at UHV, we need bigger batteries for very long crafts because using Ultimate batteries and transformers makes the small neutronium battery useless.

**Comment by richardhendricks** [comment]
156s is the normal time for smallest batteries of the tier?  At least LV-HV they are all 156s.  

I agree a larger battery could be added, but it isn't going to be cheap. Why use batteries at that tier vs cables to power supplies anyways?

**Comment by boubou19** [comment]
because i need a buffer in case of extreme lag or if i have a power failure because crafting stargate components are a bit expensive.

**Comment by richardhendricks** [comment]
2 minutes of "buffer" is not enough?  It's a pretty big jump to go to needing hours of discharge time. It would need hours of charging time as well!

**Comment by boubou19** [comment]
well both stargate frame part and stargate-radiation-containment-plates need UHV power for 1hour in the assembly line. It's reasonable to afk while it's crafting but if a power failure happen while you are afk two minutes isn't enough to save the craft and losing that much resources... i prefer not to think about it. Also i don't see why taking hours to charge should be an issue? If the batteries are used as back up power source, they shouldn't need to be used too often so you can charge them meanwhile the main power source is on.

**Comment by richardhendricks** [comment]
I don't have enough experience (IE, zero) at high tiers to comment further on this issue.  I'd think though that if a player at UHV that under powers their infrastructure system deserves to be fiercely slapped in the face. Just my opinion.

**Comment by 0lafe** [comment]
But there's already the GT++ power storage multi which holds up to whatever tier Dynamo/energy hatches we have right? There's also ultimate batteries which hold and infinite amount at UV, so stack 4 of those if you really want, but I think there's also a supercharger or some way to get more than 1A from them. There's also the really ultimate battery which holds an infinite amount and outputs 64A UHV. There's also ways to make UHV and buffer the fuel for that, or use solars and have constant power input.

**Comment by boubou19** [comment]
i understand that there are other ways of doing buffers but my point was that i think that each tier need its own little battery and big battery for consistency because soon UHV will have a real utility.

**Comment by draknyte1** [comment]
Just use Energy Buffers if you're pissy with battery sizes. 🤷‍♀️ 
That's literally why they exist..

**Comment by Dream-Master** [comment]
I will not change the battery size so use other stuff like the Energy Buffers or i need to add a battery/cluster/orb for uhv. Not sure if the realy make sense.
