### ISSUE TITLE
weird interaction between diamond saw and AE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4129]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I crafted some covers with the diamond saw then i placed the saw in ae, closed the gui and reopened the gui to take back the diamond saw
#
#### What happend instead? (Attach screenshots if needed)
this is the diamond saw i used
![2019-02-20_19 29 05](https://user-images.githubusercontent.com/12850933/53115523-b7413e80-3546-11e9-9b57-8747c1beb553.png)

this is another diamond saw i have in my AE
![2019-02-20_19 29 00](https://user-images.githubusercontent.com/12850933/53115528-b9a39880-3546-11e9-8009-e8b97a333e67.png)

this is what i get after putting the saw i used in AE, closed the gui and reopened it.
![2019-02-20_19 29 19](https://user-images.githubusercontent.com/12850933/53115538-bd371f80-3546-11e9-8f08-412a6cbb3859.png)

**Comment by Dream-Master** [comment]
@boubou19 
You can store items in saw like in the chisel? If so idk how to change that. Maybe a bug we need to live with.
