### ISSUE TITLE
As a tic/gt material to use the Ichorium

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/NewHorizons#4130]
#### Which modpack version are you using?
2.0.6.8
#### What do you suggest instead/what changes do you propose?
Ichorium as a top material in a magic system,Not much use in other places.Why  not use Ichorium to make tic tools and gt tools?

**Comment by Dream-Master** [comment]
Then it need to be added to gt material list

**Comment by Ethryan** [comment]
It is already, check line 817.
https://github.com/GTNewHorizons/GT5-Unofficial/blob/6f02b700fa1aaec71ab62477e9d2e1168fa0f210/src/main/java/gregtech/api/enums/Materials.java#L817

**Comment by Dream-Master** [comment]
ah sure ok so we need to find values for the material @SKYCATV587 @Ethryan

**Comment by SKYCATV587** [comment]
I think the gt tool made by Ichorium should be in the T7, and the durability should be between the neutronium and the awaken draconium,as for wire,i thingk uhv,1m/a,
As a tic tool, I hope that it can bring some good enchanting attributes, such as Fortune,Sharpness,Unbreaking or Looting, and each part has a reinforcement slot. If there is a suit effect,such as unbreakable, then it would be better.
(translate by Google )

**Comment by richardhendricks** [comment]
@Dream-Master Need to add some SuperTIC buffs for it too.

**Comment by Dream-Master** [comment]
yea why not
