### ISSUE TITLE
dissassembler showed just as black/violett block, touching kills client

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4132]
#### Which modpack version are you using?

2.0.6.8  Problem is since the last two updates
#### If in multiplayer; On which server does this happen?

myFTB
#### What did you try to do, and what did you expect to happen?

I build new EV and HV dissassemblers. On "old" ones, there is the same problem. First time they are shown in correct shape, sometimes later they are change to black/violett with waila-name ".name". Clicking on them kills the client. If you put a hopper on top and put machinery for disassembling in it, it works correctly and the right machine picture apear and also clicking on dissassembler works well.
Little later it falls back in black/violett view.

#### What happend instead? (Attach screenshots if needed)

#

**Comment by boubou19** [comment]
can you post the crashlog please?

**Comment by Ngar1** [comment]
picture and log:
-----------------
![2019-02-21_19 33 54](https://user-images.githubusercontent.com/7759876/53192945-f4253800-360f-11e9-9105-5e1e0159a0e9.png)
https://paste.myftb.de/asuxedoxih

**Comment by Dream-Master** [comment]
@Ngar1 i need a log. (crash log, fml log)

**Comment by Ngar1** [comment]
https://pastebin.com/WDpQCCx4

last infos from fml client log

**Comment by Ngar1** [comment]
Crash log:
https://pastebin.com/nHiKftZy

**Comment by Dream-Master** [comment]
very hard to say what it crash no mod was named. Need help

**Comment by Dream-Master** [comment]
any idea @Namikon @richardhendricks @mitchej123 @bartimaeusnek @Technus ?
