### ISSUE TITLE
Ferru plant doesn't grow to 4th stage with GT Iron Ore Block.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4133]
As in title, works fine with Vanilla MC one, I think they should be somehow oredicted or some change in code is required to allow them treat GT Iron Ore block as proper one to fully grow.

**Comment by bartimaeusnek** [comment]
yupp cant be fixed easily since its an IC2 crop and not an GT crop. No fix for now.

**Comment by Dream-Master** [comment]
Quest ?

**Comment by boubou19** [comment]
why not simply add a ferru through crops++ and somehow disable the ferru from ic2?

**Comment by richardhendricks** [comment]
I can agree with this.  The Ferru crop right now does not behave the same as the other metal crops, ie silver/copper/zinc/etc. When harvested, it drops way back on growth levels, the other crops only drop 1 growth level.  Enough that I find it really annoying to use.

**Comment by Dream-Master** [comment]
Blastoff the Steel Quest in steam age gives you 5 Iron Ore Blocks

**Comment by richardhendricks** [comment]
yeah I dunno just giving 5 doesn't seem right.  You can get more from the Twilight Forest but that's a ways away.  I just used blocks of Iron.  I'd be more interested in replacing ferru with a different GT crop that we have more control over. There are plenty of crops that produce from both so it wouldn't be a big deal IMO. Also, we should do something to make the crop textures (at least fully mature) a little more unique, pretty boring right now.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57741653-6f344280-7683-11e9-85b1-63424c306274.png)

**Comment by bedrill64** [comment]
As you are on the topic, same goes for Aurelia, it uses vanilla gold only iirc.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57743599-5af44380-768b-11e9-90da-70fd48f82a55.png)
