### ISSUE TITLE
Nano Sabber cant be crafted

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4134]
#### Which modpack version are you using?
2.0.5.1
#
#### What do you suggest instead/what changes do you propose?
Recipe requires a Platinum Sword Blade from Gregtech that is uncraftable. need to change this.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53702077-8e9d2c80-3e03-11e9-8e87-151eb904cc8c.png)
![image](https://user-images.githubusercontent.com/2970688/53702083-9230b380-3e03-11e9-8772-9ce0c22c4b67.png)
![image](https://user-images.githubusercontent.com/2970688/53702091-95c43a80-3e03-11e9-99f9-4230d4fde889.png)
