### ISSUE TITLE
Question about binnies bee tree

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4136]
#### Which modpack version are you using?
since 2.0.6.2

#### If in multiplayer; On which server does this happen?
myftb

#### What did you try to do, and what did you expect to happen?
Until now the breeding tree of "none GT" material production bees (valuable, impreg.,..) is´nt visuable

Q: how is the future of binnies bees (I mainly use) planned?
- will they reactivate? Ore disapeare (bad scenario)?
- breeding tree disabled or only not showen in NEI?

#### What do you suggest instead/what changes do you propose?

I prefere a parallel way for GT bees AND binnies bees!

The GT bees are less interesting, because I need for breeding that material before (!) and then they are useless. The combs can only used as ore multiplicator in CR -> placing some more miners are much easier then breeding and operating bee production lines.

I think, that the multiplicator way with crops are enough. Multiplication with bee is redundant and on my opinion needless.

**Comment by draknyte1** [comment]
It was changed to be consistent with crops afaik.
Dream has planned to do this for a year or two, lol.

**Comment by Dream-Master** [comment]
@Ngar1 you mean Gendustry bees?

**Comment by Ngar1** [comment]
I mean eg Impregnable bee (ID 4929 / ID4928) produce Titanium combs from extra bee (binnies bee).

**Comment by Dream-Master** [comment]
Yea there some bees duplication i know it. I can remove the GT variants but that make more advenced bees not more interresting. Did you have any idea what i could change to make bees more interresting? @Ngar1 
Guess you german so we can chat on Discord in German too. Just send me a pm

**Comment by Dream-Master** [comment]
@Ngar1 i waiting for new ideas
