### ISSUE TITLE
server crash Description: Ticking entity(from SpecialMobs)

### ISSUE THREAD

**Issue by Lanyangzhi** [GTNewHorizons/NewHorizons#4137]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
Below is the error. Seems to randomly happen after playing a while. Full log is also attached as a file.
full log is too large,can not upload.
Crash-report
https://pastebin.com/4gTsfQkG

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4110

**Comment by Lanyangzhi** [comment]
> [＃4110](https://github.com/GTNewHorizons/NewHorizons/issues/4110)

I didm't see any error enity and attack it.I just walked in the village and crashed.
there is not enchantment weapon

**Comment by draknyte1** [comment]
You don't have to do anything. Something else with an enchanted weapon can cause this, like any zombie or skeleton that spawns.

**Comment by Lanyangzhi** [comment]
> You don't have to do anything. Something else with an enchanted weapon can cause this, like any zombie or skeleton that spawns.

okay
i'm back to 2.0.5.1

**Comment by Dream-Master** [comment]
@Lanyangzhi why you not only downgrade Special mobs?

**Comment by Lanyangzhi** [comment]
> @Lanyangzhi why you not only downgrade Special mobs?

It takes 30 minutes for my server to start minecraft. It's too long.
I hope the stable version will help me reduce the problem.
And players can only download 2.0.5.1 from the public launcher.

**Comment by Dream-Master** [comment]
will push an update today
