### ISSUE TITLE
Change tungstensteel unlock quest

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4138]
#### Which modpack version are you using?
2.0.6.2

#### What do you suggest instead/what changes do you propose?

To get to the tungstensteel quest in EV you have to complete one of the tungstate quests, however both of these look for the tungstate/schelite/lithium vein. There's another more common, tungstate/schelite vein on Mars, that's mostly desh. I suggest changing the quests to one for schelite one for tungstate, both asking for 64 of the ore, but no other ores. Completing either unlocks tungstensteel. This way no matter how you find tungsten you unlock the quest.

**Comment by richardhendricks** [comment]
Does not cover centrifuging tungsten from lava.

**Comment by 0lafe** [comment]
What about adding a quest to make EV electrolyzer and just lock it behind that

**Comment by Dream-Master** [comment]
i add the Desh mix to the quests so one of the 3 mixes need to be found to open up tungstensteel quest
