### ISSUE TITLE
Achievement Misspelled

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4139]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Got GT Batteries Achievement
#
#### What happend instead? (Attach screenshots if needed)
It is spelled "Batterys".
#
#### What do you suggest instead/what changes do you propose?
Is it even possible to change the spelling in an achievement or is that hardcoded? It should say "Batteries".

*Pulls out a can of polish*

**Comment by Dream-Master** [comment]
sure it can be renamed in code.
