### ISSUE TITLE
Quest 587 "Magnetize Your Rods" Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4140]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Seems sort of pointless for the player to make magnetic steel rods in LV. Maybe just have this be magnetic iron rods only? Double amount if it seems to easy?

**Comment by Dream-Master** [comment]
no not useless if you hit mv but stay in lv and make your first mv motor

**Comment by shawnbyday** [comment]
Good point for some reason I was thinking MV used iron too. Probably just close this.

**Comment by Dream-Master** [comment]
ok
