### ISSUE TITLE
Salt is salt right ?

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/NewHorizons#4143]
#### Which modpack version are you using?
2.0.6.8
#
#### What did you try to do, and what did you expect to happen?
making salt water with edible salt
#
#### What happend instead? (Attach screenshots if needed)
edible salt is not register as salt for GT recipe 
#
#### What do you suggest instead/what changes do you propose?
replace in the craft of edible salt by the pam's salt in the previous version we were able to make salt by distilling water wich were really usefull for making biodiesel without the need of an ore so salt is salt i don't see why the edible salt exist .

**Comment by boubou19** [comment]
it's intended because otherwise you can spam chlorine too easily

**Comment by Bluebine** [comment]
this is intentional. chlorine was too easy, people just set up salt autocrafters.
get your chlorine from ghast tears, or from salt water deposits that spawn on other planets

**Comment by Dream-Master** [comment]
yes as @boubou19 @Bluebine said. Salt is not salt in GTNH and was before too op.
