### ISSUE TITLE
Right click on magical energy absorber causes crash.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#4145]
#### Which modpack version are you using?
2.0.6.8 (Single Player)

#
#### What did you try to do, and what did you expect to happen?
Right clicking on magical energy absorber change radius of absorption effect, get reasonably consistent crashes when cycling radius though 64 range.

[crash-2019-02-23_20.28.57-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2898125/crash-2019-02-23_20.28.57-server.txt)

**Comment by Dream-Master** [comment]
I remember code was changed by leagris if I rember right

**Comment by drayath** [comment]
I seem to recall the same error when i was playing around Christmas time so this might not be related to any very recent changes.

**Comment by Dream-Master** [comment]
thanks to @leagris
