### ISSUE TITLE
DEV Suggestion for Building Better Bases Section

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4146]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Add carpenter's blocks to this section. Including how to SHIFT scroll to change them (once they are cut). Also that you can SHIFT right click them with glowstone dust to have them emit light.

**Comment by Dream-Master** [comment]
Good idea

**Comment by richardhendricks** [comment]
Include info on the various builder's wand options.

**Comment by shawnbyday** [comment]
- Malisis Doors and Player Detectors as well. 
- Maybe mention that some of the blocks can't spawn mobs (for example Quarried Stone chiseled into Marble Tiles I think is what it is)?

**Comment by shawnbyday** [comment]
Add in a quest for GregTech Muffler Upgrades. Quiet bases are sexy bases.

**Comment by richardhendricks** [comment]
Rolled into 2663
