### ISSUE TITLE
A morons guide for server setup

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4148]
Version: any

Our glorious staff member moron has decreed that the server setup instructions are terrible and should be adjusted to be easier to use and understand.
![moron says](https://user-images.githubusercontent.com/20565115/53314844-1aeca400-3886-11e9-9c54-e6d3fae6560f.PNG)

**Comment by richardhendricks** [comment]
https://www.gtnewhorizons.com/wiki/m/41469370/page/Server_Setup
