### ISSUE TITLE
Quest book recipe crashes when opened before inventory

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#415]
Test case:
Join a game.
Don't open inventory.
Open any quest in your Quest book.
Try to open any recipe in your book with R button (this should trigger NEI opening).
Your game will crush.

Workaround:
Open inventory at least once. Only after that use your quest book.

**Comment by Dream-Master** [comment]
I never test to using Nei out of the Quest Book.
If you send me a crash log i can open an Issue on HQM Gitpage or you can do it by your self.

**Comment by nikitinalexx** [comment]
Thank you, here is a stacktrace
https://gist.github.com/nikitinalexx/6885e20977adf7cebac0

**Comment by Dream-Master** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/issues/306

**Comment by Dream-Master** [comment]
Does this happend with the new Nei file ?

**Comment by Teteros** [comment]
> Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

If it was BM in the end, there's little we can do on our side.
