### ISSUE TITLE
Coins Quest 1044 - Iron (III) Chloride

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/NewHorizons#4151]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Tried to buy Iron (III) Chloride with coins
#
#### What happend instead? (Attach screenshots if needed)
Gives 64 empty universal cells
#
#### What do you suggest instead/what changes do you propose?
Update the quest reward to give tin cells of Iron (III) Chloride since the liquid is fixed.

**Comment by Dream-Master** [comment]
reload you quest files this is fixed ages ago. @dragagon  /ba_admin default load

**Comment by dragagon** [comment]
I did a default load the moment I updated. Please note this is the coins quest reward, not the mv quest.

**Comment by Dream-Master** [comment]
yes seen this after I wrote it.

**Comment by Dream-Master** [comment]
will check
