### ISSUE TITLE
Quality of Life Mod Suggestion DEV

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4154]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Should add mod Controlling to the pack: https://minecraft.curseforge.com/projects/controlling it allows you to search the keybinds instead of having to scroll.

**Comment by Dream-Master** [comment]
Vote is startet
