### ISSUE TITLE
Impossible quest in Witchry

### ISSUE THREAD

**Issue by Kostia-2001** [GTNewHorizons/NewHorizons#4155]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
Yes, in multiplayer. We have our own private server.
#
#### What did you try to do, and what did you expect to happen?
Quest #1584 requests spanish moss. This requires shears, but they are not.
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/35667197/53432426-890aa580-3a03-11e9-86c6-b6b1a2c71e87.png)
#
#### What do you suggest instead/what changes do you propose?
Give Shears.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53701273-817c3f80-3dfb-11e9-8228-5b07af278df4.png)
![image](https://user-images.githubusercontent.com/2970688/53701276-85a85d00-3dfb-11e9-8b67-19f7ca33d435.png)
