### ISSUE TITLE
IC2 Crops Magnifying Glass Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4157]
#### Which modpack version are you using?
1.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Make a crude magnifying glass that will identify growing crops. It wouldn't tell you any of their stats just the name of the crop. This let's you start working on crops before you're into LV without guessing so much. Can have it crafted like:

```
[[Iron Rod, Glass Pane, Iron Rod],
 [Iron Rod, Iron Ring, Iron Rod],
 [null, Iron Rod, null]]
```

Or something similar. It doesn't have to be crazy powerful just be nice to know what is growing.

**Comment by bartimaeusnek** [comment]
done. with the newest crops++ (1.3.2)

**Comment by shawnbyday** [comment]
You're my newest favorite person! Thanks! :)

**Comment by shawnbyday** [comment]
@richardhendricks once that gets in the game we will of course need a fancy quest for it!

**Comment by richardhendricks** [comment]
Absolutely.  Will there be any other uses for it @bartimaeusnek ? Anything to do once a player makes a cropnalyzer?  I don't suppose there is for for the bee field kit, so there doesn't have to be.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57197418-b5bfc980-6f2c-11e9-9ef9-ba97e8838b49.png)
