### ISSUE TITLE
LV Energy Hatch Recipe Suggestion DEV

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4159]
#### Which modpack version are you using?
2.0.6.7c

#### If in multiplayer; On which server does this happen? 
Private

#### What do you suggest instead/what changes do you propose?
Currently the LV energy hatches are a bit expensive to make. They take:

- 2x Electronic Circuit
- 2x Low Voltage Coil
- 1x LV Machine Hull
- 1x Tin Cable
- 1x LV Pump
- 2x Lubricant Cell

I'd suggest one of the 2 possible recipe changes:

- Replace 2x Electronic Circuits with 2x Resistors OR
- Replace 2x Electronic Circuits with 2x Tin Wire and the 1x Tin Wire with 1x Electronic Circuit

If you have any questions or I missed something let me know.

**Comment by damug** [comment]
I find your second suggestion much more reasonable to me. Two circuits is overkill, but one seems fair enough.

**Comment by Ngar1** [comment]
just a question for understanding: why is a pump and lubrication needed, for electrical power input? If for cooling a more realistic idea: for fluid cooling in electrical inverters, lasers, magnetrons a water/glycol (50:50) mixture is used.

**Comment by richardhendricks** [comment]
materials have to be obtainable at LV.
