### ISSUE TITLE
Got a crash after pressing ''J'' bottom 

### ISSUE THREAD

**Issue by Ptahil** [GTNewHorizons/NewHorizons#416]
Here is a technic log-file:

[techniclauncher_2015-12-09.txt](https://github.com/GTNewHorizons/NewHorizons/files/57095/techniclauncher_2015-12-09.txt)

It says: **EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x0000000007902558, pid=5008, tid=2400**

**Comment by Dream-Master** [comment]
This looks like a Java Error. Will try tomorrow to reproduce it.
By the way you can now play on the Server. I set you as a Builder today.

**Comment by Namikon** [comment]
Please upload the mentioned file
*H:\Games\Technic Platform\modpacks\mcnewhorizons\hs_err_pid5008.log*

**Comment by Dream-Master** [comment]
@Ptahil 
Can this closed?
