### ISSUE TITLE
DEV ProjectRed Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4166]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Making circuit plates requires Pressure Plates. They "look" the part but having a spring in a circuit is weird. Can we add a custom item that is like "Blank Plate" or something and it's made by cutting a stone slab or something? Anything without a spring...seems weird.

**Comment by damug** [comment]
could just use the gregtech stone plate instead of pressure plates?

**Comment by shawnbyday** [comment]
> could just use the gregtech stone plate instead of pressure plates?

That'd make more sense.
