### ISSUE TITLE
Multi oil pump slowdown/general changes

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4167]
#### Which modpack version are you using?
2.0.6.8
#
#### What do you suggest instead/what changes do you propose?

The oil pump multis that start at MV and go to EV are kind of a little fast. Throwing out some numbers, a decent oil field is 500+L/cycle, a cycle is 2s at HV, or 1s at EV. This means an EV powered EV drill, will pull from 64 chunks, if it's a field of 650L, that means 2080L/t oil. Simply burning that will give you an amp of LuV, almost 50k EU/t in LCEs. However, if you invest a little extra infrastructure and distill that oil to sulfuric light fuel, and burn that, you get 83k EU/t, or about an amp of zpm in LCEs. If you go a step further and manage to turn it all to light fuel and burn that, you can get over an amp of UV before the LCE boost. The only problem becomes turning all that fuel to power, but it's fairly doable with each LCE giving out 3A EV. Distilling the fuel to sulfuric will take a lot of distilleries, and turning it to fuel will take a crazy amount of H2, but this highlights my point. There's no reason you need that much oil/t. An EV pump will supply 208 EV distillation towers. 

Reducing the cycle time from 8s at LV, to 16s is a good start. It means an MV pump running on MV, will give you about 4L/t oil, which is enough to supply 2 LV distilleries to make diesel. Also probably want to reduce the size of the HV and EV drills. 3x3 for HV and 4x4 for EV should be enough. Means EV pumping EV will give about 1/10 what it does now, which is only 260L/t which translate to only 5k EU/t if you burn it straight, and a lot more if you distill it in a manner that's reasonable in those tiers. 

Yes, oil deplets. Looking at the EV pump burning oil, it will take 7.5 days to deplete, and it does so linearly. So it's more like 25k EU/t for a week, which is still kinda OP considering all it costs is a drill, an EV power source, and that's it. That's more than most nukes, which are significantly harder to get/maintain. You'd need to get/fuel like 12 EV naq gens to reach that output. 

Slowing down the pump speed has almost no effect on power/products from oil distillation, mostly just means it's not a viable for simple power production, and benefits more from processing.

**Comment by richardhendricks** [comment]
A singleblock pump pulling up BC oil does it quickly and can be made faster by stacking more pumps. So having a fast output from the oil drills isn't out of balance compared to those.

Faster outputs encourages automation for shutoff or automating bringing back the oil, since it means otherwise you have to travel to the oil drill more often to retrieve oil out of the tanks.

Oil is used for more than EU generation. At MV+ where the oil drill is available you will begin using oil for plastics and explosives.

Also, with the big nerf to energy hatches, the barrier to upgrade to higher power tiers is larger than before. 

I say no.

**Comment by 0lafe** [comment]
>Faster outputs encourages automation for shutoff or automating bringing back the oil, since it means otherwise you have to travel to the oil drill more often to retrieve oil out of the tank.

Only small positive really, but it's more annoying. It's just needed because the multi is way too fast. 

>Oil is used for more than EU generation. At MV+ where the oil drill is available you will begin using oil for plastics and explosives.

yea and you'd still get enough for that, You'd just have to choose between drilling faster, or more drills, or splitting oil between some power and some products, which seems fine. 

>A singleblock pump pulling up BC oil does it quickly and can be made faster by stacking more pumps. So having a fast output from the oil drills isn't out of balance compared to those.

Yes, but if you pump them at speeds anywhere close to what I'm talking about, they'd be gone in probably a few minutes, if not maybe an hour. The GT wells will last you days upon days. EV takes 7.5 days of constant running to deplete a spot. With the change to 16s/cycle it would take over 2 weeks. BC oil wells simply don't have enough for them to compare here. 

>Also, with the big nerf to energy hatches, the barrier to upgrade to higher power tiers is larger than before.

I'm not sure what this has to do with it. Not only does it not really make the entirety of a tier harder, it just gates what you can do, but even if that's the case these setups aren't ones in which the energy hatches can be considered the primary cost. An IV hatch doesn't really compare to making 64 MV machines.

**Comment by bartimaeusnek** [comment]
@0lafe @richardhendricks BEFORE YOU CANGE ANYTHING, please do the maths on this, since pumps require EU/t and not EU/L and adjust the pump EU/t.

**Comment by 0lafe** [comment]
^ so that's more of an issue when looking at producing power, but using less than an amp of MV, or HV in HV to EV isn't going to change much power wise. It would add an almost unnoticeable amount of EU to the chain when looking at something like cetane, HOG, or even diesel. It would more become a problem when burning SLF or the oil alone, which is sort of meant to not be done, and in no way the dominant power option, past LV or so. You're still looking at the same depletion time on the wells. They'll go slower for the same EU/t, but depletion time/L of oil will stay the same. The point is more to make pumps required to run more often when refining oils, as right now they need to be throttled fairly hard to accommodate for their crazy speeds. The more important change is to make them less crazy good for simple power setups relying on that insane L/t speed they give. It doesn't apply as much to larger setups, as your constraints limit the oil use, but not so when you're simply burning the oil, or the SLF/LF from it. 

Also, from what Bart and I talked about, chunkloaded is kind of a thing around these pumps. So assuming they run when you're not there is kind of fair. At least with e pearls and CL where they currently are. 

Another option is to slow down the speed less, but impact range of higher tiers more, or give it a worse overclocking multiplier? So MV->HV is like 1.5x better or something. The MV rig isn't terribly fast, but you're still slowing it down as it's the fastest part of your oil processing by a fairly wide margin. Especially upkeep cost to speed wise.

**Comment by richardhendricks** [comment]
One comment, the oil pump is now used to pump other fluids, most notably salt water on the moon/mars/europa for high tier chlorine use. Have you considered the effect of this on that?  How much salt water is needed at high tiers?

**Comment by 0lafe** [comment]
As long as you can find 200+ fields, a 3x3 chunk pump at a 16s LV cycle powered with EV gives 1b/s, which is probably more than you need. Chlorine is mostly used in plastics and rubbers, but the usage isn't terribly high given what amounts of them are asked from the player. As long as the moon spawns salt water fields past 100L then it should be fine.

**Comment by alphaNOVAircraft** [comment]
The oil rig is definitly on the strong side of oil collecting right now, but i need to question the impact of that nerf, as you mentioned above it wont be the bottleneck in your processing system anyways. Nerfing it wouldnt make it a useless multiblock for sure, but i dont thnik it will change anything too (maybe except the amount of chunkloading time it needs)

**Comment by 0lafe** [comment]
It also changes the weirdly high EU/ts you can get from burning oil/slf/LF for power in HV-IV

**Comment by alphaNOVAircraft** [comment]
Thats probably right, but i need to admitt that i never heard of anyone buring oil/slf/lf in ev - iv. So your nerf seems somehow reasonable for hv. Due to only increasing the process time and not the eu cost i dont think the nerf would be so hard. Like it :)

**Comment by 0lafe** [comment]
Ranges kinda OP too, at least with current speeds and stuff. T2 pump is 16x better than T1, and T3 is 4x better than the T2. Ranges are nice because they mean you get more total fluid per placed pump, but changing how good they are by that much seems excessive. Maybe lowering the T2 speed by 4x, and the T3 by 8x would be better. Means T2 is still pumping 4x the quantity for the same power input, and T3 will do 2x the T2. T3 currently is 64x better than the T1, this change makes it only 8x better. Considering you loose 2x eff going to T2, and 4x total going to T3, the ranges with new speeds mean up tiering a T1 will give you 16x the life time of placement, 2x power efficiency, at 8x overall speed, for 4x the power. Going to a T3 will do 4x on the life time, and another 2x on the power efficiency, Doing 8x overall speed for 4x the power.
