### ISSUE TITLE
Fertilia quest needs rework.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4169]
Quest ID: 1808

Fertilia quest has improper description, it doesn't drop IC2 fertilizer but components for this, tiny dusts of apatite/calcite and phosphate dust, also part about growth stat is incorrect, venomilia is the crop that behaves like weed not fertilia.

**Comment by Dream-Master** [comment]
@richardhendricks can you rewriting the quest because you dont get fertilizer out of this seeds. (only Phospate, calcite and apatite so far ik)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57188786-e6bae280-6ec9-11e9-9673-6d5f45377af4.png)
