### ISSUE TITLE
Distillery recipe

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#417]
I suggest to change Distillery recipe. Because even 32eu machine requires one Blaze Rod. And on such early tier killing Blaze in Nether can be extremely hard.

**Comment by Dream-Master** [comment]
Ok the Distillery i can change but the Brewery i dont want to change. (You need the Brewing Stand which is only available via Thaumcraft)

**Comment by Teteros** [comment]
Implemented in [1.0.7.4](http://forum.gtnewhorizons.com/showthread.php?tid=47&pid=223#pid223).
