### ISSUE TITLE
[rfc] Fortune boost for singleblock and multiblock miners for small ores

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4171]
With the 6.8 oregen changes the amount of normal ores in an orevein is decreased slightly and are replaced with small ores.  

This RFC is to discuss giving miners and the multiblock miner fortune boosts to recover additional products from small ores. 

Currently they all mine blocks with the equivalent of 1 fortune boost. (the multiblock miner later does the equivalent of the HV macerator to drops, but that doesn't affect small ores).

I am proposing the following changes

Single-block miners get a fortune boost of +2 per tier.  So equal to 3/5/7. Based on my testing, it's about 4% more per fortune level, or about 8% more small ores per miner tier.

Multiblock miners get a fortune boost of +5 per tier.  So equal to 6/11/16/21.

This will only affect small ores and vanilla ores (ie, from TF).

GT Ores placed by hand will not get any fortune boosts (ie, through ore duping via thaumcraft)

**Comment by shawnbyday** [comment]
Good idea. I do like the new 9 layer veins since they work so well with the hammer but did notice the density is a little less. I don't math or anything so it was just an observation.
