### ISSUE TITLE
Add forestry tree breeding quest line

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4173]
2x2 trees
taller/tallest trees
yield
speed
number of saplings

hazel nuts
butter nuts

**Comment by richardhendricks** [comment]
Moron, Plum for high yield, Coast/Giant sequoia for max size

**Comment by richardhendricks** [comment]
grafters
thaumium grafters
etc

**Comment by shawnbyday** [comment]
Don't forget to explain how Thaumium Grafters require food to run, not magic LOL.
