### ISSUE TITLE
Convert low tier hand prospector to using disposable batteries

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4174]
Currently the hand prospector breaks once it is used up.  Want to change that so it can be refilled with the disposable batteries.  Need to figure out proper way to hand this. Maybe add a shapeless recipe to take 1 of the three battery types and recharge it, and return an empty battery.

**Comment by richardhendricks** [comment]
Another option is to make it a rechargeable tool like the soldering iron. I'm OK with that too.

**Comment by damug** [comment]
Would an assembler recipe work ? 1 empty prospector plus 1 full single use battery resulting in 1 full prospector plus 1 empty battery.

Obvious shortcoming being that you couldn't pop new batteries in while in the field though .

**Comment by shawnbyday** [comment]
I think there are a couple options:

1. Scanner is unbreakable and rechargeable but has a higher crafting cost.
2. Scanner is breakable but repairable and rechargeable and crafting cost stays the same.

My personal reaction to a scanner that breaks with no repair option is to not use it unless I'm forced to.

I would prefer option 2.

**Comment by shawnbyday** [comment]
Outside of straight up changing it like I mentioned above I think @damug has a good idea but I'm not sure the assembler can return the repaired scanner and the empty battery? It might need to be a crafting table recipe until it can be re-coded?

Letting you change batteries in the field might be a little bit too much power for what this thing is though.

**Comment by Anarack** [comment]
what about handling them like the gt drills and toss them into the disassembler?

**Comment by shawnbyday** [comment]
@Anarack you mean that machine has a use!? LOL Good idea though.

**Comment by richardhendricks** [comment]
yeah having a way to recharge in the field would be preferable. I think making it similar to the soldering iron/electric wrench etc, where it has both a durability and a charge bar is probably best.  Will have to think about it some more.

**Comment by 0lafe** [comment]
Don't these things have crazy large ranges? Maybe we want to lower them if they're easier to repair/refill?

**Comment by richardhendricks** [comment]
Not really?  The range increases with tier, but realistically players would switch to the electronic prospector at LuV.

**Comment by richardhendricks** [comment]
at IV the max is 7x7 chunks

**Comment by Dream-Master** [comment]
The Prospector was never made for this. Use the scanner. @richardhendricks
