### ISSUE TITLE
GalacticGreg server's config issue

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#4176]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private Server Debian
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
The server generates a new config file named GalacticGreg. The old one is galacticgreg. The new one
contains different config with the old one.
#
#### What do you suggest instead/what changes do you propose?
change filename to GalacticGreg

**Comment by Dream-Master** [comment]
oh ok good to know.

**Comment by Dream-Master** [comment]
cant see it was changed

**Comment by Dream-Master** [comment]
GalacticGreg is the name since 2015/16

**Comment by bjin2000** [comment]
After run the server, new file GalacticGreg generated, old one is galacticgreg
![0 x 5880 yd4q m63vr4h](https://user-images.githubusercontent.com/48137054/53698390-03dc1380-3daa-11e9-9084-b4e97512e143.png)
This is part of old one
![5rcm m_v 0 9 u27oie7](https://user-images.githubusercontent.com/48137054/53698409-3ab22980-3daa-11e9-94b4-fd1119a80bf1.png)
This is part of new one
![0ebgzgm9g2s hctc 4z p6](https://user-images.githubusercontent.com/48137054/53698424-72b96c80-3daa-11e9-9923-ab0f7c4ce0f1.png)

The new one lack the buildinmods part and main part

**Comment by Dream-Master** [comment]
will ask namikon about it.

**Comment by Dream-Master** [comment]
@Namikon

**Comment by richardhendricks** [comment]
Might need to check on a Linux/Mac system, Windows the files are treated as one file.
