### ISSUE TITLE
Quest #1754 cannot retrival

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/NewHorizons#4178]
#### Which modpack version are you using?
GTNH 2.0.6.2
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Try to retrival quest#1754. Required 2 Aluminium Item Casing(dreamcraft:item.AluminiumItemCasing), but all recipes craft GT Aluminium Casing(gregtech:gt.metaitem.02:18019), except quest#671 rewards just 1 Aluminium Item Casing.
#
#### What happend instead? (Attach screenshots if needed)
Cannot retrival.
#
#### What do you suggest instead/what changes do you propose?
Add recipes or fix quest

**Comment by Dream-Master** [comment]
allready fixed in 2.0.6.8/9
