### ISSUE TITLE
Coins Quests

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4179]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
You can buy Hydrogen Cells with coins why not be able to buy Nitrogen and Oxygen Cells too?

**Comment by Dream-Master** [comment]
you can
![image](https://user-images.githubusercontent.com/2970688/53698055-0f463380-3dd8-11e9-84fa-9ee5cd268ab7.png)
![image](https://user-images.githubusercontent.com/2970688/53698058-153c1480-3dd8-11e9-97be-410680822a7e.png)

**Comment by shawnbyday** [comment]
Oh my bad. I probably just haven't done the Nitrogen quest yet. Sorry! You can close this.
