### ISSUE TITLE
New quests

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#418]
Suggestion to add new quests for the most popular mods

**Comment by Dream-Master** [comment]
?

**Comment by nikitinalexx** [comment]
Okay, let's leave a Quest book the way it is. Half empty and covering mostly only gregtech.

**Comment by Dream-Master** [comment]
I know what you want but your suggestion was only "make more quests"
The ? means what Quests you suggest and which Mode we have to pick first.

If you have more detailed ideas it would be nice :)

**Comment by Namikon** [comment]
The questbook was initially supposed to get you started with the way our tiering works; GregTech.
Everything is based on that; Even Thaumcraft. (This is also mentioned in the quest-texts btw; But who reads those anyways..)
It's not as easy as "suggestion to add new quests for the most popular mods", as 
the basic concept behind the book is quite different; It's not a "use this to reach endgame"-book.

But I'm open to ideas how to continue that concept, and integrate more mods into new quests

**Comment by Drobac** [comment]
Might be good ti make tier specific quests for free farms, as it isnt widely known when they become available. So Steves at LV, forestry at MV, TC Golem farms in the tc quest line

**Comment by Dream-Master** [comment]
I close this we can reopen it or make a new Issue,
