### ISSUE TITLE
Add startup message for complaints/company

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4182]
#### Which modpack version are you using?
2.0.6.8
#

Add a message when starting a world that this GitHub/discord exist, and point people here for complaint related things/changes they want. Nice idea with bee/hatch/LuV+/soon bio/GT++/tectech/other changes coming with 2.0.6+

**Comment by richardhendricks** [comment]
"Please direct all nerf complaints to @0lafe on Github" Sounds right? :D

**Comment by 0lafe** [comment]
I guess but I'll never really see them on here, should add discord too. I wanna see all the messages from people who don't like needing to actually tier up their infrastructure >:)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/54014298-cd9fea80-4141-11e9-82d9-3c2a87340d39.png)
