### ISSUE TITLE
Needs maintenance cover needs strong redstone signal

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4183]
https://github.com/GTNewHorizons/GT5-Unofficial/issues/166

**Comment by Dream-Master** [comment]
can this be closed?
@richardhendricks

**Comment by richardhendricks** [comment]
Ok so soldering iron + fine solder wire lets you change redstone signal strength from weak to strong. Will need to create/update quest for this.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57188937-38b13780-6ecd-11e9-9e2b-95f4f3d21c74.png)

**Comment by richardhendricks** [comment]
Also added Howler Alarm quest.

![image](https://user-images.githubusercontent.com/1214811/57189284-6482ec00-6ed2-11e9-9ba1-f55be9a32000.png)
