### ISSUE TITLE
EXU Spikes cannot be moved by pistons when enchanted

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4184]
The title says it all, really. Diamond spikes can be moved when unenchanted, and not when enchanted. I'm not sure if this is in your control, but a fix would be appreciated.

**Comment by Dream-Master** [comment]
EXU mod is closed source so cant be fixed easyly.

**Comment by LogicFalls** [comment]
Yeah, I thought it was closed. Oh well.

**Comment by Dream-Master** [comment]
Ask ASM God Alkalus :P

**Comment by draknyte1** [comment]
I assume it's probably intentional to be honest, but let me look.

**Comment by LogicFalls** [comment]
Is hardly a game-breaking thing, I just thought it was unusual that the behaviour was inconsistent. Thanks for taking a look!

**Comment by draknyte1** [comment]
> Thanks for taking a look!

I had honestly never looked into what allows a block to be 'pushable', so I was curious myself.
