### ISSUE TITLE
[suggestion] additional gt decorative plates

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4185]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I was building with GT marble and i realized that that pack has only gt cover for smooth red/black granite.
It could be cool to have all the red/black granite variants and also marble variants to build and it will fit perfectly with the AE2 covers and BC covers that already add all GT marble and red/black granite variants as covers.

**Comment by Dream-Master** [comment]
more complex than i thought

**Comment by damug** [comment]
If this does end up possible, I'd also like to see some other stone/cobble/brick/wood variants as possible plate covers

**Comment by Dream-Master** [comment]
if somone helps me yes why not
