### ISSUE TITLE
duplication for disabled metal 

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/NewHorizons#4186]
#### Which modpack version are you using?
2.0.6.8
#
there is a lot of dupplication that as been disabled in metallurgic perfection becose it were to op, don't know why gallium is in if you can enlighten me , but can you had a way for duplicating those metal with the infusion altar by infusion a nugget to an ingot for example.

**Comment by Dream-Master** [comment]
It was a random suggestion to disable a few. Well we can remove Gallium.

**Comment by Dream-Master** [comment]
@bartimaeusnek why duplication label ?

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4059

**Comment by Dream-Master** [comment]
Ah ok didnt see. Thanks
