### ISSUE TITLE
Wooden pipe recipe

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4187]
#### Which modpack version are you using?
2.0.6.8 

There should be a recipe for wooden pipes in extruder or assembler or something else. Its annoying to use tools to craft it.

**Comment by Dream-Master** [comment]
No not really. Wooden pipes are the very early pipes for water and cold fluids. And btw try to explaim me how you want to extrude a pipe out od wood logs in rl :)

**Comment by bartimaeusnek** [comment]
@Dream-Master how about 6 wooden plates + glue in assembler?

**Comment by Impos913** [comment]
I am at EV and still using wooden pipes :P
There so many things that is impossible to do in real. You can fly with copter pack at moon :/

**Comment by Impos913** [comment]
I just want a recipe in a machine anything would be nice :D

**Comment by Dream-Master** [comment]
yea maybe the glue recipes is the best on :)
