### ISSUE TITLE
Add chisel support to gregtech stones

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/NewHorizons#4188]
Would be nice to add chisel support to red granite, black granite, basalt, concrete, dark concrete, light concrete, etc.

Marble was given chisel support a few years back under a different ticket: https://github.com/GTNewHorizons/NewHorizons/issues/892

**Comment by Dream-Master** [comment]
sure but to which group I should add it? @damug

**Comment by Dream-Master** [comment]
or I add a extra group better

**Comment by Dream-Master** [comment]
@damug I see the prblem that this blocks are not interchange able without break balance.

**Comment by damug** [comment]
@Dream-Master I don't quite understand the question.

So you can't create new chisel groups for blocks?  If so, some of these aren't the best fit, but:
1) red and black granite could go under the chisel granite archetype.
2) light/regular/dark concrete could be added to the chisel concrete archetype.
3) basalt could be added to the chisel abyssal stone archetype.

Ideally, though we could create new chisel archetypes for these.

RE: balance, the only sub item that takes anything more than a furnace, file or hammer to create is the mossy cobblestone and mossy bricks, and I'm not sure about 0lafe, but I'm alright with purely decorative items being easier to craft.

**Comment by bartimaeusnek** [comment]
@damug red and black have different ingridients... IF you really need it as chisel, id suggest moving marble in an own group, red granite, black granite, basalt and concretes aswell.

**Comment by Dream-Master** [comment]
@damug @bartimaeusnek so make a new group with all that blocks including marble ?

**Comment by damug** [comment]
Correct, create new chisel groups for all the gregtech stones, including marble.

I took at peak and @bartimaeusnek is correct that you can centrifuge the two granites into separate component dusts, which might cause issues later.

Also, remove marble from the chisel marble/quarried stone group.

Thanks!

**Comment by bartimaeusnek** [comment]
no. not all in one group. one group per type @Dream-Master

**Comment by Ngar1** [comment]
please let marble GT be at the marble/quarried group

**Comment by richardhendricks** [comment]
Please keep GT marble in the quarried stone group. Makes it really easy to get calcite.  Also, otherwise quarried stone is pretty useless.

I think putting abyssal stone and black granite in the same group is fine.

red granites in a group and basalts in a group is OK too.

I'd really like to see more GT concrete types/asphalts too.

**Comment by damug** [comment]
I'd equate abyssal stone closer to basalt than black granite personally. This all looks easily minetwealer, so long as I can decipher the meta ids for the various stones. If I can I'll make a pull request with a minetweaker script update tonight.

**Comment by richardhendricks** [comment]
I was going with black granite because Bg has more usable byproducts than basalt. ;)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53980459-af6dc680-4110-11e9-91b1-1cefcf6cbab6.png)
![image](https://user-images.githubusercontent.com/2970688/53980480-b72d6b00-4110-11e9-8c28-118e171c616d.png)
