### ISSUE TITLE
Stargate chevron recipe is broken

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4189]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I tried to craft a SG chevron with an assembly line so i followed what was written inside the book.
#
#### What happend instead? (Attach screenshots if needed)
Nothing happened
here is the recipe:
![image](https://user-images.githubusercontent.com/12850933/53695586-a05be100-3dbd-11e9-90f2-344a4e7b1003.png)

#
#### What do you suggest instead/what changes do you propose?
According to @bartimaeusnek it's because of the stack size of the exquisite jasper and ruby: they have a maximum stack size of 16 but the recipe needs a stack size of 64 (4 stacks of 16 doesn't worked)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53980407-8ea57100-4110-11e9-8f07-69e8bebdd923.png)
