### ISSUE TITLE
Missing world file, yet world still loads then crashes after 20 minutes.

### ISSUE THREAD

**Issue by austin1346** [GTNewHorizons/NewHorizons#4191]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
My server (Dedicated)? Not sure what you mean.
#
#### What did you try to do, and what did you expect to happen?
Loaded up my server for the first time, freshly downloaded server files. Server worked fine for 20 minutes then crashed. There's no world file at all in the server files which is strange. I added aromabackup/core and the backup fails each time, because there's no world file I presume. Not sure where it's saving to.
#
#### What happend instead? (Attach screenshots if needed)
-
#
#### What do you suggest instead/what changes do you propose?
-

**Comment by austin1346** [comment]
Just found out that it's saving all the contents of the normal world file to the main server directory instead of it's own directory (world file). Not sure why that is.
![capture](https://user-images.githubusercontent.com/3124834/53705072-79b2a000-3de7-11e9-9716-97cc4efb36fd.PNG) Example.

**Comment by Anarack** [comment]
https://www.gtnewhorizons.com/wiki/m/41469370/page/Server_Setup

Please check your server properties file. This is a user error. Then grab the latest build of special mobs from our discord. Also posting that your server crashes without also posting a crash log prevents your issue from ever being resolved.

https://discord.gg/EXshrPV

**Comment by austin1346** [comment]
I'm guessing the level-name=____ is what I need to set right? why isn't it set to "world" by default like 2.0.5.1?

**Comment by Anarack** [comment]
It has a broken fix in it that can crash the server I'm not sure if the fix for that made it into the 2.0.6.8 server package yet, and no I don't know why the that option was changed from the default.
