### ISSUE TITLE
Crop Harvester and GT Wrench

### ISSUE THREAD

**Issue by xhek** [GTNewHorizons/NewHorizons#4195]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
German Public MyFTB
#
#### What did you try to do, and what did you expect to happen?
Tried to destroy the Crop Harvester (IC2) with the GT Wrench to replace the machine like every other machine
#
#### What happend instead? (Attach screenshots if needed)
Basic Machine Casing dropped instead of machine
#
#### What do you suggest instead/what changes do you propose?
Make the GT Wrench disassemble IC2 machines, almost all items used in the recipe for the Crop Harvester are GT Items

**Comment by Dream-Master** [comment]
IC2 is closed source so not sure if that gonna happen.

**Comment by draknyte1** [comment]
I may have missed one or two things by mistake, but otherwise EVERYTHING uses a wrench after this - https://github.com/draknyte1/GTplusplus/commit/caa09ffe94f23c1383f2f8259876de6c88a637de

Which is live in 6.8. Please go open an issue on the GT++ issue tracker for me.

**Comment by Dream-Master** [comment]
@xhek can you open up the issue on gt++ side please. Thanks

**Comment by Impos913** [comment]
Alkalus said its fixed in .6.8 in the discord chat.

**Comment by Dream-Master** [comment]
that's why I said open up am issue please @xhek @Impos913

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/issues/435

**Comment by Dream-Master** [comment]
ok cool. Will you hand me out a dev version later i can test it ? @draknyte1
