### ISSUE TITLE
Chunkloaders in jobs shop will be changing with 6.8+

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4196]
@Namikon it looks like chunkloader coins in the jobs shop will not use the same IDs.

Just FYI for when the official update happens.

![image](https://user-images.githubusercontent.com/1214811/53776010-3ffe9980-3eba-11e9-8e30-f10f4845f558.png)

**Comment by Dream-Master** [comment]
chunckloader coins can be made via recipes on zeta
but i can change it

**Comment by richardhendricks** [comment]
I'm not saying we need to change that, I'm just wanting to make sure we don't mess up chunkloader coins when we upgrade the officials.
