### ISSUE TITLE
SpecialMobs spawn chances & Teleportation

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#420]
SpecialMobs.cfg changes for I:hungry zombie which steals items and I:doom creeper which spawn silverfish, and take a considerable amount of time to clear up. Either to disable for now, or make monster types rare as their difficulty rises.

Infernal mob teleportation to be disabled to make mob traps viable.
(To be discussed in IRC for alternatives)

**Comment by Dream-Master** [comment]
Yes i will change a bit the Special Mobs config.

@Namikon 
can we change teleportation in the code that the monsters not stuck inside the wall or make teleportation range smaller that they not leaving a Monster Trap Room.

**Comment by Namikon** [comment]
A smaller range wouldn't help, as even with a setting of 2 blocks they could escape. One could check the destination for air-blocks, but that has to depend on the mobtype if the free area is 1x1, 1x2, 2x2, 1x3 etc. Then, at least in our pack, Gregtech harms entities that are too close together, so they will get additional damage if more than one teleports to the same location; Which might trigger further teleportation.

It's just a much cleaner way to disable that effect, as the safety-checks to make it fail-proof would be rather difficult

**Comment by Careface1g** [comment]
I would ask for disabling a couple of mobs in SpecialMobs considering what they do.
They are originally supposed to check your inventory for food items and steal those , but for some reason they are also taking non-food items and are almost impossible to defend against.
The ones I know and the ones described on the site are :
-Hungry Zombie
![alternative text] (http://minecraft-forum.net/wp-content/uploads/2012/12/2ee05__0Gfrr.jpg)
-Hungry Zombie Pigman
![alternative text] (http://minecraft-forum.net/wp-content/uploads/2012/12/2ee05__I9Jex.jpg)
I also saw a hungry zombie villager but I couldn't find a picture or take one.
Taken from : http://minecraft-forum.net/default/special-mobs-screenshots/

**Comment by Namikon** [comment]
The config-change has been made, and hungry/thief mobs should now be gone for good.
Please report issues here

**Comment by Teteros** [comment]
Now that that's been addressed, will mob teleportation get the same treatment?
Always infernal mobs such as Blazes still can't be reliably liquidated in a controlled environment.

**Comment by Dream-Master** [comment]
We disabled already so much that I have to look for a other mob mod.

**Comment by Namikon** [comment]
It's not true that you can't do reliable blaze / mob farms. There is at least one way to kill mobs without causing the teleport effect to happen; In fact, my very own farm works like a charm; And I have a ton of infernal witches and enderman there from time to time. Not a single one escaped, ever.
Of course they don't drop the rare loot then; But that's supposed to happen only if you as a player does the kill anyways.

However: I support the idea of having normal mobfarms by using stuff like the DraconicEvolution grinder.
@Dream-Master: The ninja/tp effect is from Infernalmobs, not specialmobs. 

I could probably do some tweaks to infernalmobs, as it ships with the sourcecode. But I'm not sure if we really should start yet another fork ..? I'll make that a community decision. Check the forum for a poll

**Comment by Dream-Master** [comment]
Please vote

http://forum.gtnewhorizons.com/showthread.php?tid=78

**Comment by Teteros** [comment]
Ender/'TP' effect removed from mobs since https://github.com/GTNewHorizons/NewHorizons/commit/6d6f82f7212e2e3d052d4a27f9760aacaa41d3be.

If there's more problem causing mob effects, please reopen.
