### ISSUE TITLE
Titanium change (and a little teeny bit of tungstensteel)

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4200]
#### Which modpack version are you using?
2.0.6.8
#

#### What do you suggest instead/what changes do you propose?

Right now titanium spawns on the moon as a pure ore. It's the main EV material, used in most EV crafts in some way. However, with this pure ore coming as soon as you start to need it, it becomes one of the easier tier materials to obtain. When compared to stainless in HV needing things like chrome, and tungsten needing hydrogen. Idea is to change a few things to make titanium a more appropriate tier material. 

First, change how pure titanium ore spawns. Remove it on T1/2 planets, and leave it as a small ore on asteroids. The T3 rocket is a fairly easy EV rocket, giving you better Ti options while still in EV, just not at the start. Switch pure Ti in the vein with ilmenite. A rutile containing mix, which yields around 1 ingot Ti per ore, more if you use a multi miner. The main problem with relying on simply bauxite processing, is that bauxite gives so little titanium. You get 2 rutile every 39 crushed, which is 1/10 ores, or a little less with a multi miner. At 700+ ores in a vein, that's only 70+ ingots Ti, super low. However switching places of ilmenite and 2ndary bauxite in the bauxite vein gives you more like 800+ titanium in a bauxite vein. You'll also get a sizable amount from the chromite veins which would have ilmenite too as a primary ore. 

2nd part is to change rutile processing a little. Right now it eats 1/3 magnesium dust per Ti and 1B Cl. My idea is to change it to give back 100% of the magnesium, but still take the 1B chlorine. You have salt water pumping starting with the moon, and increasing with the T2/T3 rocket. 

Other small change, titanium and rutile ebf recipes should probably be EV. It's sort of weird that the idea of overclocking your ebf to the next tier to progress stops with EV/IV, then comes back in LuV. Titanium uses an HV ebf/vac freezer, and tungstensteel uses HV ebf/EV vac. Seems kind of low for these 2 tier materials. EV ebf/HV vac for titanium, IV/EV vac for tungsten steel seems like a better fit for them. Could lower their times to compensate. It's weird you can make IV stuff with only an HV ebf though.

**Comment by Impos913** [comment]
You said T3 is easy at EV??? You have to get into IV for tier3 rocket.

**Comment by 0lafe** [comment]
No no no... It unlocks IV, in the same way the T1 rocket is HV and unlocks EV. But I'd say the T3 isn't quite the end of EV. It takes an EV assembler, EV CA, electrolyzer for tungsten, and wiremill for the thermal suit, then an EV vac freezer which can use HV hatches. It's kind of a low amount of stuff to get to IV lol. But anyway that's mad EV. Also yes it takes other stuff. But rest is HV, and yea this EV

**Comment by Impos913** [comment]
Tungstensteel unlocks IV and T3/4 rockets are in IV, I didnt check the recipes but tier3 rocket quest unlocked after IV hull

**Comment by Beyond-Veil** [comment]
Weirdly enough, i don't mind the proposed titanium changes that much, if we indeed get the entire package. However you must think through the EBF changes. Overclocking is massively expensive power wise. Requiring your EBF to be EV wouldn't it just make it EV for titanium, but effectively for all materials (unless you start forcing people to have a second EBF dedicated for lower tier materials). 

1) For example making aluminium in an EV EBF costs a quarter bucket of cetane (bucket of benzene) per ingot. or 16 buckets (64 benzene) for a stack. 
2) you already need to use a convoluted process to get titanium, why not make the EV requirement for "pure" titanium ore and not the low yield early recipe you are discussing here? (which is actually a chemical process mostly) they are not related, so no need for them to be exactly the same (or even close)

You make the early EV start sound easy, but you just have slightly easier access to machine casings. These are hardly a gate in any level. Circuits and power have proven to be a much better gate than steel, stainless or titanium have ever been. they are just time consumers, no more, no less.

**Comment by Anarack** [comment]
With nichrome coils for lower tier stuff you have 1-2 boosted overclocks, so its not as bad as you make it out to be cost wise. tbh, you really should look at having more than one ebf at that point anyway, or thats what the processing time for nichrome should of told you.

**Comment by 0lafe** [comment]
Yeah but I'm not sure what you mean by that. It's useful to have more than one, but are you saying that means we shouldn't make you OC one of them to EV? I'd disagree but I'm also not sure if you're against it. 

>Tungstensteel unlocks IV and T3/4 rockets are in IV, I didnt check the recipes but tier3 rocket quest unlocked after IV hull

The T3 rocket quest is unlocked when you finish the T2 I think? Idk I did it while still in EV. Crafting it is also EV, no way it's IV. 

>Tungstensteel unlocks IV and T3/4 rockets are in IV, I didnt check the recipes but tier3 rocket quest unlocked after IV hull

If that's all the tier material was used for then sure, but it's not. It's in motors, pistons, lotta component parts and some multis as casings. The T2 drills/LCE aren't that bad to craft with current Ti, making a bunch is almost trivial. Both of these multis are fantastic, but can be made fast with mostly HV/MV machinery, besides the electrolyzer for the like 1 cable in the LCE controller. There's some other things I'd suggest for moving these a little farther, like increasing silicone/styrene production to at least EV eu/t, maybe IV considering it's not really used until IV, and IV EU/t on a CR is still an EV thing. 

>Overclocking is massively expensive power wise. 

Yes that's kind of the point. You're EV now, you should have to dump this much power into your ebfs. 

>Circuits and power have proven to be a much better gate than steel, stainless or titanium have ever been. they are just time consumers, no more, no less.

Isn't this using power as a gate though? Also the speeds of 4 HV ebfs on Ti have made it not close to a time gate at least from my usage of it. I've gone through 4k Ti or so, but never had to wait for it to smelt. If we increase the EU/t and lower the time of the recipes by 1/2, running 4 EV ebfs would give you even more Ti, more than simply overclocking them to EV.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/dd31ac9607951b185ac52aee74b9cf693961f364
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/ab918526c29f516867e767ae88e04f206ec5511c
