### ISSUE TITLE
Really Ultimate Battery recipes is lack

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4204]
#### Which modpack version are you using
2.0.6.8b
#
#### If in multiplayer; On which server does this happen? 
Private Server and Single
#
#### What did you try to do, and what did you expect to happen?
I looked at Really Ultimate Battery recipe.
#
#### What happend instead? (Attach screenshots if needed)
Really Ultimate Battery recipes is lack.
![2019-03-06_09 40 52](https://user-images.githubusercontent.com/40425798/53850223-d25b8600-3ffd-11e9-86d2-ddf2aaccf3e8.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53980373-76355680-4110-11e9-8201-9e936d342a54.png)
