### ISSUE TITLE
New Multiblock Hatch/Bus recipes are too expensive

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/NewHorizons#4205]
They do not mechanically make sense. Granted the old blocks were cheap. However these new recipes are far more expensive and time consuming to craft. They use several components that do not make sense(Such as coolant cells, coils, and circuit parts) that are not used much elsewhere. Seeing as the contributor who came up with recipes can be quoted " Once you have an AE system it's not too bad" I am going to say he has zero idea on how to properly balance. Quit have players that are used to being at high tier nerf crap because they are bored without someone reviewing the idea.

**Comment by Bluebine** [comment]
As I said in the discord: The energy hatches serve a purpose- they gate upgrading your multiblocks, which is a good change.
The other hatches don't serve any purpose, they just make multiblocks more annoying to make, I don't think they're necessary.

**Comment by redmage17** [comment]
There is a level of finesse to everything and it's been taken from one extreme to another. You could just include a coil, and appropriate wires/conveyor/pump

**Comment by alphaNOVAircraft** [comment]
coolant cells seem legit for me, they arent used in a ton of recipes, but they arent hard to make either. I personally play GTNH because it finds recipes to include nearly all items that are aviable in the pack, dont think that is something bad. We could even consider adding coolant cells for more recipes. (e.g. in in the superconductor wires of the early tiers, transformers (instead or addintionally to lubricant cells))

**Comment by Cinobi** [comment]
There was a one big problem of hatches\basses - literally no point of making any bus more than HV and any hatch more than ULV. Aaand, this nerf only makes the things worse xD

**Comment by Anarack** [comment]
Fusion requires tiered hatches, gt++ multis/processing arrays may need them on large loads, LHE may need them as I'm not sure its exact rules on fluid pushing. High volume turbines when using gt pipe and regulation as well.

**Comment by richardhendricks** [comment]
Simple fixes, make the hatch output speed vary with their tier.  Maybe 1/2 or 1/4 of their tier-specific component, so 320L/s or 160L/s for LV fluid hatches would encourage players to use higher tier versions.  We could make fluid input hatches rate-limit as well, so if you want to input large volumes of fluids you have to tier up (would need to think about turbines for this).

Similar kneecapping of input and output buses would encourage players to update their multiblocks or else their high speed multi will not be able to accept or output low tier material recipes at full speed.

**Comment by bartimaeusnek** [comment]
@richardhendricks no. that wont work. ever. there are enough ways to bypass such a limit.

**Comment by richardhendricks** [comment]
Such as?  You can kneecap the amount of fluid the hatch presents to outside fluid extractors, preventing them from pulling more than the hatch is rated to allow.

**Comment by bartimaeusnek** [comment]
the blood altair does the same, with different fluid pipes, there are serious duplication/deletion issures. while this isnt a real problem for the altair, it definitely will be for hatches.

**Comment by Anarack** [comment]
Also this will make the large heat exchanger even more difficult to handle. I really don't want to try merging high volume fluid outputs consistently with the gt pipe system.

**Comment by 0lafe** [comment]
If we could have them use a base scaling mechanism but different throughputs per multi it would probably work better, but that sounds like too much work. 

If we could make scalable hatches we could lock energy tier to lowest hatch tier. If like MV hatch meant anything from 1-9 slots, and HV was 1-16. Fluids I'm not sure if there's really a reason you'd use higher or lower tier hatches besides cost. So forcing higher ones wouldn't be detrimental I don't think.

**Comment by richardhendricks** [comment]
The speed throttling doesn't necessarily have to happen at the hatch-rest of the world interface, it could happen at the hatch-multiblock interface.  Not sure if we can do that with just changes at the hatch or if it would require multiblock code changes.
