### ISSUE TITLE
Muffler Hatch (MV) Recipe Incorrect

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4207]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Went to craft Muffler Hatch (MV) expecting to use MV Machine Hull.
#
#### What happend instead? (Attach screenshots if needed)
MV Muffler uses LV Machine Hull.
#
#### What do you suggest instead/what changes do you propose?
Change recipe to use MV Machine Hull.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53980353-66b60d80-4110-11e9-8020-b540d75d29f2.png)
