### ISSUE TITLE
Phosphorus production through bones 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4208]
#### Which modpack version are you using?
2.0.6.8
#

#### What do you suggest instead/what changes do you propose?

Phosphorus is one of the less easily obtainable elements, mostly only showing up in apatite veins, and as a very low byproduct of things like Ash or bee phosphorus. It's used in EV+ for epoxy, but as a byproduct of phenol production, it creates acetone. One of the key features of HOG. 

Idea is to give bones a more realistic output, as well as increase the phosphorus options we have to involve more than just bees/crops or mining ores. 
>Typical bone ash consists of about 55.82% calcium oxide, 42.39% phosphorus pentoxide

>Lastly, the newly sterilized bone is ground with water into fine particles

Using these 2 fun facts, I propose changing bones -> bonemeal to use an autoclave to make a "sterilized bone" which is then macerated for bonemeal. Then you electrolyze bone meal for 55% CaO, and 45% phosphorus pentoxide. 

Maybe make the autoclave recipe MV 30s? It could give "pure bone meal" as an output which could be electrolyzed. While using a mortar or simply macerating bones only gives bone meal, which wouldn't have a recipe in the electrolyzer. This way you need to use the autoclave step to get phosphor, but not if you're just using bonemeal to grow stuff or whatever. Maybe make the electrolyzer recipe HV 30s? It's kind of a good output, and you don't really need tons of it, but it would be nice to give it a solid renewable recipe for EV+ plastics

**Comment by 0lafe** [comment]
Apparently it sucks adding new items, so maybe just adjust current bonemeal recipe to 75s HV and new outputs?

**Comment by Beyond-Veil** [comment]
Currently electrolysing bonemeal gives calcium, which is an input in other streams (like for cetane energy via biomass). I'm onboard with a different recipe stream using the "purified" route, but not if it changes the only simple calcium recipe to a monstrous expensive HV bloat.

Especially pertinent as this calcium is used in the biomass route to obtain acetone. Don't get me wrong here, but this feels you want to nerf the biomass route because the benzene route needs phosphor: let's remove the easy calcium from bones from the biomass guys and change it into a harder recipe to benefit the benzene energy route.

**Comment by 0lafe** [comment]
Maybe make it a 5s recipe at HV?

**Comment by draknyte1** [comment]
The confusing thing is, The names changed at one point. - https://github.com/GTNewHorizons/GT5-Unofficial/commit/480408a7bfb63c176242172bab61a804105b440d

**Comment by Beyond-Veil** [comment]
Sure Cetane is HV so that is fair. As long as the production allows for both main routes to produce acetone at a reasonable rate. Biomass already has the downside that phenol needs to be specially made for epoxy and needs more complex set-ups and investment to produce enough cetane to be competitive with benzene for energy.

IMHO We really don't need stealth nerfs to biofuel/biomass and buffs to benzene at this point.

**Comment by bedrill64** [comment]
You all forgot about fertilia crop, it's actually renewable source of calcium and phosphate, its only tier 3 crop, kinda tricky to breed but really easy to manage, at point when you need phosphorus you can just plug WA and breed shit out of it and then never worry about calcium/phosphorus.

**Comment by richardhendricks** [comment]
Is't calcium one of the Lapis byproducts as well?  I seem to recall having plenty of it and not much use for it.

**Comment by 0lafe** [comment]
There's also a bee that gives a bunch of phosphor and calcium, but I'm tryna give options that aren't bees/crops

**Comment by Beyond-Veil** [comment]
> 
> 
> Is't calcium one of the Lapis byproducts as well? I seem to recall having plenty of it and not much use for it.

That is part of my point: biodiesel set-ups have no use for phosphor, benzene set-ups have no use for calcium. I'm ok with bringing them together to both have an alternate route via bones, as long as it doesn't flip to the point where it affects the viability of the existing route to favour the other

**Comment by 0lafe** [comment]
Yea but with calcium from lapis, which has a plant, you can probably get it fast enough for cetane/HV stuff, or HOG/EV stuff. So nerfing calcium from bones doesn't remove fast enough calcium for that route

**Comment by Beyond-Veil** [comment]
It is about parity:

current
```
- phosphor from plants: Y
- phosphor from bees: Y
- Phosphor from mining: Y
- Phosphor from bones: N

- Calcium from plants: Y
- Calcium from bees: Y
- Calcium from mining: Y
- Calcium from bones: Y
```

If you change that to:
```
- phosphor from plants: Y
- phosphor from bees: Y
- Phosphor from mining: Y
- Phosphor from bones: Y

- Calcium from plants: Y
- Calcium from bees: Y
- Calcium from mining: Y
- Calcium from bones: N (not feasible)
```
 all you have gained is boosting benzene and nerfing biomass. Saying "there is other ways to get calcium" isn't the point. your argument was "i want another source for phosphor". fine. I don't see why that has to lead to nerfing that EXACT SAME path for the competing solution.

**Comment by Bluebine** [comment]
making bonemeal electrolyzation a 5s HV recipe, and giving 50% phosphorus and 50% calcium (don't do 55% and 45%, that'd just be annoying to deal with) would be cool and make sense. But don't make it incredibly annoying with that "purified bone" solution. Having tons of calcium or phosphorus really isn't going to break the game.

**Comment by bedrill64** [comment]
Well, making bone to drop both resources at once gives infinite easy way for fertilizer production, even if its HV still seems OP for me, no infrastructure whatsoever required, just power.

**Comment by Bluebine** [comment]
There's lots of easy ways to produce fertilizer. Most people get it as a byproduct of biomass processing they'd do anyways, you can ALREADY make it from calcium and either sulfur or ash, which are also easy renewable, or get it from darkwood easily. Not really a big concern IMHO.

**Comment by draknyte1** [comment]
![cc85fd0a-24aa-42dd-9a54-f37f0ce6af11](https://user-images.githubusercontent.com/3060479/53996951-44cd8280-4132-11e9-9472-b9cba7db77f0.png)
![517bc55c-7bdc-46fb-898d-9c1a85796586](https://user-images.githubusercontent.com/3060479/53996952-44cd8280-4132-11e9-9ca8-0cbf9c69449e.png)


I’ve got a whole AgroChem chain added for P production and other materials

**Comment by draknyte1** [comment]
https://cdn.discordapp.com/attachments/401118216228831252/553373337888489472/unknown.png

Manure by-products can be used to obtain P.
Different levels of processing exists for these materials, with higher tier recipes giving better % on outputs and better efficiency in terms of processing.
