### ISSUE TITLE
Marble cobble should not be part of Nickel quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4209]
Looks like a leftover from a cut&paste

**Comment by richardhendricks** [comment]
Same with Magnalium source quest

**Comment by Dream-Master** [comment]
Please add quest id otherwise i cant fix it @richardhendricks

**Comment by Dream-Master** [comment]
And mabel is a souce of magnesium so no wrong copy paste issue
![image](https://user-images.githubusercontent.com/2970688/53954770-706f4f00-40d7-11e9-89d3-46bea9ed7e08.png)

**Comment by Dream-Master** [comment]
other quest is fixed
