### ISSUE TITLE
Upgrade path for Steam machines to High Pressure equivalents

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#421]
To make high pressure machines more viable and practical it would be nice to be able to upgrade from LP steam machines to HP steam machines at a little discount.

For example a steam compressor could be upgraded as follows:

![test2](https://cloud.githubusercontent.com/assets/5067989/11845333/4c926d40-a40b-11e5-8e63-74a98e4a1a88.png)

**Comment by Namikon** [comment]
I kind of dislike that idea. You have ways to dismantle / recycle almost every GT item. By adding such a change, you'd change a fundamental thing in the existing GregTech tiering, as you'd have to make most machines upgradeable then. Also, it would cause problems with dismantle recipes; As all machines carry their initial crafting recipe as NBT Data; thus martin has to add those special tags as well, to be compatible.

By the way, the tag "accepted" should not be placed by the one that makes a suggestion... Or did I miss something here?

**Comment by Dream-Master** [comment]
Yes but if i add this recipes to GT code and delete the old one or better replace them the recycler recipes and Disassembler recipes will work.

**Comment by Dream-Master** [comment]
You need only High Pressure machines after Bronze and with LV you dont need it any more.

**Comment by Dream-Master** [comment]
Ok we have to vote for it.

I open a threat up in the Forum.

**Comment by Namikon** [comment]
You don't *need* those machines. You can go directly from bronze > LV. The High Pressure machines are a pure optional thing. And that's how the quests are build by the way

**Comment by Dream-Master** [comment]
Sure i only think about it not wasting the Bronze machines because and find a better way for recycle it at this time because you dont have any assembler, disassembler only a macerator. Otherwise you keep this machines in some chest so long yo have the machines to recycle them for a proper output.


So you can vote for it and we will see.

http://forum.gtnewhorizons.com/showthread.php?tid=68

**Comment by Teteros** [comment]
It does raise an inconsistency and alters the players expectations at the beginning (if I can upgrade X this way, why not Y) indeed.

The idea is that the player doesn't have machines at this point and surely the bronze machines are nowhere near as complex as carefully assembled electric machines, so reinforcing them with plates to upgrade may be plausible by hand.

While yes, they are optional in practice they are skipped by most as there is no incentive to make them from scratch. You might as well conserve precious steel for LV machines. The recipe above saves about 4 steel and a piston or two. It's more about the steps needed than resources.

I added the 'accepted' tag as the idea was bounced on IRC and players seemed to vote for it. I'll use it correctly next time after the decision is unanimous I suppose.

**Comment by Dream-Master** [comment]
https://strawpoll.me/6283814

**Comment by Dream-Master** [comment]
I think it is better we like the recipes like they are.
