### ISSUE TITLE
Faster saplings -> wood pulp

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4210]
Current recipe is 20s, and gives 2 small piles.  A whole log also takes 20s and give 6 piles.  It would be useful to make the saplings go faster, like 5s.  So logs are still 3x the wood pulp in the same amount of time, but wood pulp would make a viable sink for excess.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53980319-56059780-4110-11e9-9e2b-b98e0a1c7f7f.png)
