### ISSUE TITLE
[suggest] warp and pollution

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4211]
When very serious pollution occurs, warp will increase slowly.
![image](https://user-images.githubusercontent.com/42833050/53877383-f80b7e00-4043-11e9-88ee-0087d9e8ecb4.png)

**Comment by Beyond-Veil** [comment]
1) 1.4Mgib isn't really very high, so it would need to be much more serious
2) heavy pollution already caries its own dangers and downsides
3) it is way to easy to build up warp this way before normally warp would be an issue or you can measure pollution or even counter pollution

Not mixing high pollution areas with magic is maybe an interesting idea. Eg high pollution increases the chances for warp effects slightly or more flux gets created when doing alchemy etc in high pollution area. but straight up increasing warp, especially when it impacts players in steam, LV and MV era's seems very unfair

**Comment by richardhendricks** [comment]
It would be interesting if it affected infusion stability or if flux turned into pollution, but it would be a lot of effort for a little benefit.
