### ISSUE TITLE
"Plunger 2.0 The Hand Pump Replacement" is not repeatable.

### ISSUE THREAD

**Issue by Kanisof** [GTNewHorizons/NewHorizons#4212]
If you buy the Hand Pump from the coins tab and lose it there is no way of getting another one. 

#### Which modpack version are you using?
v2.0.5.1

#### What do you suggest instead/what changes do you propose?
Make it repeatable / Give it a cooldown

**Comment by Dream-Master** [comment]
fixed in newer version with a recipe so far ik
