### ISSUE TITLE
Various Liquid recipes are driving people mad

### ISSUE THREAD

**Issue by BlackAce21** [GTNewHorizons/NewHorizons#4214]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Tried crafting various recipes requiring liquids of some kind
#
#### What happend instead? (Attach screenshots if needed)
Some of the recipes requiring liquids have been typo'ed, I am assuming at the code level because I couldn't find a single config file in scripts or otherwise to fix it. Example: To craft a Large Naquadria Battery (Empty) requires 567 L of Molten Polybenzimidazole when it should require 576 L. 576 L is equal to 4 ingots. 567 L is equal to 3.9375 ingots which is annoying when you have to constantly unclog machines with left over materials during automation. Please note that this isn't the only example and I have multiple reports from other users encountering the same problem.
#
#### What do you suggest instead/what changes do you propose?
I propose fixing the problem at whatever source is causing it. I did look through the issues posts here on this github and on the GT unofficial versions change log to see if any mention was made of a fix. Either I found none because it was worded in a way I didn't catch. Or it has yet to be addressed. Either way, hoping to see this one sniped out of existence in the next update because man is it annoying. Thanks for your time.

**Comment by boubou19** [comment]
can you list all the wrong recipe you found please?

**Comment by DualBallers** [comment]
Large Naq Battery should have been fixed here #3656 

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/52/commits/d943564e61f020e4c4d79e41c5611dbd48abe788

**Comment by Dream-Master** [comment]
@BlackAce21 yes would be very nice if you can post the recipe here and i can take care much easier.
Thanks

**Comment by BlackAce21** [comment]
The original request was made to me by members of the ProsperCraft server. With the exception of ones already mentioned, no one has written down any of the other recipes. I asked for more details but all I got was "I just remember seeing a bunch of them". If you have the coded values, would probably be easiest to grep them within the code base. Having said that I will get after the guys to check for other recipes they might know of.
