### ISSUE TITLE
Phosphorus Singularity recipe is missing.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4215]
#### Which modpack version are you using?
2.0.6.8b
#
#### If in multiplayer; On which server does this happen? 
Private Server and Single
#
#### What did you try to do, and what did you expect to happen?
I tried to checked recipes of Phosphorus Singularity.
#
#### What happend instead? (Attach screenshots if needed)
This recipe is missing.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
This is a material of Pneumatic Singularity, an intermediate material of Eternal Singularity.

**Comment by boubou19** [comment]
the recipe on 2.0.5.1 is:
![image](https://user-images.githubusercontent.com/12850933/53988767-91aa5c80-4124-11e9-8df8-8c5930dc8336.png)

**Comment by Dream-Master** [comment]
need to check

**Comment by draknyte1** [comment]
Probably related to the Phosphorous changes x]

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Universal-Singularities/releases/tag/8.5

**Comment by Dream-Master** [comment]
need new version for it.

**Comment by BlackFlameTNT** [comment]
at 2.0.7.0 still not showing.

**Comment by Dream-Master** [comment]
7.1 fix it.

**Comment by yukieiji** [comment]
This issue don't fix(ver2.0.7.5) and name missing.
Please reopen.
![2019-08-04_04 44 58](https://user-images.githubusercontent.com/40425798/62416313-3c428f00-b673-11e9-8ec5-cf4221889436.png)

**Comment by Dream-Master** [comment]
The name not fixed or the whole singularity is missing?

**Comment by Dream-Master** [comment]
@yukieiji

**Comment by yukieiji** [comment]
Both.
The name not fixed and Phosphorus Singularity recipe is sitll missing.

**Comment by Dream-Master** [comment]
now fixed

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Universal-Singularities/releases/tag/8.5a

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/62427926-b9fdad80-b6fa-11e9-931f-38af8854b38d.png)
![image](https://user-images.githubusercontent.com/2970688/62427928-c5e96f80-b6fa-11e9-8784-e651a0155506.png)
