### ISSUE TITLE
Wormwood

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#422]
Because of the right click function of Pam's Harvestcraft, it is impossible to get this item by regular means, so could you please add a custom recipe for Wormwood seeds - using 4 buckets of water, 4 wispy cotton and 1 wheat

**Comment by Dream-Master** [comment]
There is a new version from pams harvestcraft out already. I will update soon.  If the recipe not there I will add it.

**Comment by Teteros** [comment]
Implemented in [1.0.7.4](http://forum.gtnewhorizons.com/showthread.php?tid=47&pid=223#pid223), commit 669b0f7fa5391e5ae08c6f19a86c0ef60a88ba81.
