### ISSUE TITLE
Trinium can't be obtained in the Tier below the T4 rocket

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4221]
#### Which modpack version are you using?
2.0.7.0
#
#### What did you try to do, and what did you expect to happen?
Heavy Duty Alloy ingot T5 requires Naquadah Alloy, but Trinium can't be obtained at that Tier.
Also, I can't make ZPM assembler because I can't obtain Trinium.
#
#### What do you suggest instead/what changes do you propose?
I suggest that Trinium should be obtained more easily.
In the case of GTNH 2.0.6.2, it was possible to obtain a small amount using an Electromagnetic Separator.But it can't be obtain since GTNH 2.0.6.8.

**Comment by Dream-Master** [comment]
@0lafe can you check ?

**Comment by draknyte1** [comment]
It wasn't intentionally meant to obtained in GTNH that way.

**Comment by Dream-Master** [comment]
wait you disable trinium in GTNH complete or change only the way you can get it? @draknyte1

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java#L2098

I didn't used to be in the GTNH block.
It wasn't really intended to be enabled here, but I guess I forgot to change it for 5.x.

**Comment by 0lafe** [comment]
So uh there still is the GT++ chem bath stuff? Wulfenite and naq give it, which are in the TF/T3 rocket. Or is that now disabled

**Comment by draknyte1** [comment]
Chem Bath recipes only exist if the Ore stuff does, which for Trinium doesn't within GTNH.
So, they'd be long removed.

**Comment by 0lafe** [comment]
It's enabled in 2.0.6, but if it's gone after what do we wanna do for trinium? We could do planet stone product again, or maybe try to focus more on UU for it somehow? It's not used much early ZPM, only naq alloy.

**Comment by 0lafe** [comment]
Deep iron small ores on Mercury should fix this

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54641693-0f5e5880-4a93-11e9-9d46-e44465ef1c0d.png)
