### ISSUE TITLE
Nuclear reactor

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/NewHorizons#4223]
![GBN}~BGW}%WAG(4 {XH{046](https://user-images.githubusercontent.com/41377439/54072120-36f23b80-42b1-11e9-99a3-1cbd22e130f9.png)

**Comment by Dream-Master** [comment]
@SKYCATV587 I need more infos please.

**Comment by SKYCATV587** [comment]
like this
![2019-03-09 23-06-45_x264_2](https://user-images.githubusercontent.com/41377439/54073580-0bc51780-42c4-11e9-82ed-75e94bda2024.gif)

**Comment by alphaNOVAircraft** [comment]
Seems like its possible to click a whole stack of rods into the reactor, did you try this out in survial mode too?

**Comment by SKYCATV587** [comment]
> 似乎可以点击一整堆棒进入反应堆，你是否也在幸存模式中尝试了这个？

yeah,of course
