### ISSUE TITLE
Superconductor UV Wire wrong recipe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4224]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Superconductor UV Wires output 36 and require 63 Superconductor Base UV wires.
#
#### What happend instead? (Attach screenshots if needed)
![Screenshot 2019-03-09 17 04 19](https://user-images.githubusercontent.com/11991148/54073968-6727e300-428d-11e9-8d10-82da57cab8e5.png)

#
#### What do you suggest instead/what changes do you propose?
Fix

**Comment by Dream-Master** [comment]
ok
