### ISSUE TITLE
Fluorine to coins tab. 

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4225]
#### Which modpack version are you using?
2.0.6.8 

Add fluorine to coins quest tab as there is other basic fluids like oxygen, hydrogen, chlorine...

**Comment by alphaNOVAircraft** [comment]
But pls make it more expensive then the other gases in that tab, its not that easy to obtain in larger quantities in the beginning, and you dont need to much of it.

**Comment by richardhendricks** [comment]
100 chemist coins for 16 fluorine cells, unlocks after Teflon don.
