### ISSUE TITLE
Too difficult to obtain Plutonium 241 for ZPM Sensor/Emitter with T5 Rocket

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4226]
#### Which modpack version are you using?
2.0.7.0
#
#### What did you try to do, and what did you expect to happen?
Plutonium 241 is required for ZPM Sensor/Emitter, but I can only get that Tiny Dust at 10% by centrifuging Plutonium 239 when T5 Rocket Tier(ZPM Tier).

#
#### What do you suggest instead/what changes do you propose?
I suggest that Plutonium 241 should be obtained more easily or change metal used for ZPM Sensor/Emitter.

**Comment by Impos913** [comment]
Wiki says you can get plutonium 241 from trollplant.

**Comment by alphaNOVAircraft** [comment]
Iirc you can get thr plutonium 239 pretty easily, so the centrifuging only takes quite a lot of time, but zpm sensors / emmiters dont need to be super easily to produce, if you set it up once and let it run in the background the whole time i did not encounter any issues with plutonium 241 shortages till now

**Comment by draknyte1** [comment]
![3DD8BC7A-252A-4DD5-9B4F-50DEC404165F](https://user-images.githubusercontent.com/3060479/54082955-34293200-4315-11e9-9969-15273a89fe1f.jpeg)
You can also process MOX fuel rods for it in future.

**Comment by Dream-Master** [comment]
i think you can get Plutonium at io so tier 4. I dont see an issue here.

**Comment by Dream-Master** [comment]
and centrifuge it down to 241 need some time
