### ISSUE TITLE
Bauxia crop doesn't recognize TiCo Aluminum Block.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4227]
As in title, Bauxia does not recognize Tinker's Construct alu block as growth block, you have to chisel it into Galactic Craft Alu block which is not intuitive for most of players, change it or oredict it somehow if possible.

**Comment by Dream-Master** [comment]
its a gt crop right @bartimaeusnek  ?

**Comment by draknyte1** [comment]
Because Tinkers calls it Aluminum and GT and everything else uses Aluminium.. just use a GT block

**Comment by bartimaeusnek** [comment]
@Dream-Master yes, but it would require a lot of changes.

**Comment by draknyte1** [comment]
GT intentionally does not support TiCon aluminium stuff. There’s actually a massive ticket about it on the master repo, where things like this were discussed. We agreed to leave it as is~ I’ll try find the link later when I’m not stuck on mobile.

**Comment by bedrill64** [comment]
Just fyi, GT block of aluminium is not craftable ingame actually.

**Comment by Dream-Master** [comment]
will add it to chisel
![image](https://user-images.githubusercontent.com/2970688/54086439-c51a0080-4349-11e9-854c-a611be6b5246.png)

**Comment by boubou19** [comment]
be sure that this chisel recipe will not be able to bypass aluminium making via an ebf

**Comment by Dream-Master** [comment]
if the tico block not bypass it how the gt block would be ?

**Comment by boubou19** [comment]
oh sorry i wasn't aware of the TiCo aluminum not being possible to obtain with the smeltery.

**Comment by bedrill64** [comment]
Well if GT block is actually recognized I think simplest solution would be to change compressor recipe to give GT alu block instead of TiCO alu block.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54639973-f05dc780-4a8e-11e9-87a0-f4ef9582b136.png)
