### ISSUE TITLE
Changing loot table for God of Thunder crop.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4229]
Is there possibility that we change loot table for God of Thunder crop? 
Atm it drops small coal dust + coal + Thunder leaves occasionally we already have crop for coal which is withereed. Leaf drop is pretty shit atm, comparing with all other stuff in chest, its after 1 harvest of 24/25 crops, 2 leaves is really not sufficient number for any production. And those are more or less max gain crops. Another thing its one of those specific crops that drop to stage 2/4 after harvesting which makes it even less productive leafwise.

![2019-03-10_14 15 23](https://user-images.githubusercontent.com/9555787/54085609-36ed4c80-4340-11e9-9aba-22652d9ad2bf.png)

**Comment by bartimaeusnek** [comment]
this is possible and rather easy to change.

**Comment by bedrill64** [comment]
Bump.
I'd love to have this change in next release.
