### ISSUE TITLE
Internet Radio mods

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#423]
Dragon's Radio Mod is in the pack but disabled it seems, and so is the openblocks radio block.
Openblocks radio needs a codec lib which is included, though it seems the radio block was disabled by the devs?

Are there any alternatives? Would be a cool client-side feature.

**Comment by Dream-Master** [comment]
This Mod maybe ?
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2155190-better-records-download-songs-from-the-internet

**Comment by Namikon** [comment]
Since when is the dragon's radio mod disabled? And if it is, why is it still in the pack?
Also: If you want to listen to music just use spotify/napster/iTunes/winamp/... ?

**Comment by Teteros** [comment]
Supposedly Dragon's radio mod crashes the server for some reason?

The in-game radio mod would give positional sound (which works very well with [MumbleLink](https://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272675-1-8-mumblelink-forge-smp-lan-mumble-realism) which is what our group is using) offering a more immersive experience. If playing solo it's probably not very useful indeed, but still makes your base a bit more personal and may be a nice surprise for visitors coming in.

**Comment by Dream-Master** [comment]
The mod is not longer on the Client. I remove him already.

**Comment by Dream-Master** [comment]
Ok teteroscan you  open a new issue for a new Radio Mod.

**Comment by Teteros** [comment]
Reopening, because Dragon's Radio Mod doesn't crash the client anymore.
Also, if you wish to get the script back, https://github.com/GTNewHorizons/NewHorizons/commit/ff73272ec9ba44e7026eac6211cf42792863a31e github to the rescue!

**Comment by Teteros** [comment]
Alternatively, I found a nice fork:
https://github.com/PC-Logix/OpenFM
Seems to support OC as well.

**Comment by Dream-Master** [comment]
If we add a radio mod again i want ut be a server side mod otherwise minetweaker script not make sense here.

**Comment by Teteros** [comment]
The minetweaker script would be for the actual radio & speaker block.
![<speaker image here>](https://cloud.githubusercontent.com/assets/5067989/13376205/686243ac-ddad-11e5-8a63-b0efe5ffd533.png)
Unless you want to distribute it via quests, or donation only.

**Comment by Dream-Master** [comment]
@Teteros 
Any news here?

**Comment by Dream-Master** [comment]
2 Monsth later.....


@Teteros 
Any news here?

**Comment by Teteros** [comment]
[OpenFM](http://minecraft.curseforge.com/projects/openfm) is still an updated fork of Dragon's Radio mod.

It's still a decision whether OpenFM has a place in the pack or not.

I'd say go for it as its OGG and OpenComputer support was fixed since my last post.  That was holding my vote for it until now.

**Comment by Dream-Master** [comment]
Ok i open a new issue for it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/607
