### ISSUE TITLE
Duplicate Alumite tools

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4231]
As of V2.0.7.0, Alumite was added as a GT metamaterial, meaning it can be used to create GT tools.
In doing this, however, it has been detected by Tinker's Gregworks and has created duplicate alumite toolsets, and parts. It also conflicts with vanilla TiC thus creating duplicate molten metals, ingots and dusts.
![image](https://user-images.githubusercontent.com/32601565/54087161-3e185880-4348-11e9-9d77-0c4842fd8fc3.png)

**Comment by richardhendricks** [comment]
Alumite from a furnace doesn't match in quest #1126, need to change to ingotAlumite oredict

**Comment by Dream-Master** [comment]
wait let me fix thus stuff first and remove tools. What we really need from alumite? @richardhendricks wich parts I mean.

**Comment by richardhendricks** [comment]
Parts to do GT tools.  ingots, Rods, plates, screws, drills etc.  Let me check the quest changes I have and you can change back if you need to.
