### ISSUE TITLE
[Quest #1476] ("All the finest cuts of meat") - OreDict error

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/NewHorizons#4232]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Crafted an Iron Butchery Knife to fullfill the Quest (Quest is located in Tier 0.5 - Stone Age)
#
#### What happend instead? (Attach screenshots if needed)
Quest is still not completed; isn't a visual bug; it accepts only Butchery Kinves of material NULL
#
#### What do you suggest instead/what changes do you propose?
Change quest-requirement to OreDictionary (craftingToolBlade won't work because it would also include GT-Swords, -Universal Spades, -Knives and -Senses -> register the Butchery Knife also in something else and use that for the quest, e.g. craftingToolKnifeButcher)

**Comment by richardhendricks** [comment]
Will check.  I don't think we need a new ordedict, probably just properly ignore nbt.

**Comment by richardhendricks** [comment]
yeah needs an ignore nbt in retrieval task. Will fix

**Comment by richardhendricks** [comment]
Ignore nbt, delete enchantment id
