### ISSUE TITLE
Butchery knife duplication

### ISSUE THREAD

**Issue by TechnicFreak** [GTNewHorizons/NewHorizons#4234]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
MyFTB
#
#### What did you try to do, and what did you expect to happen?
Followed the shown recipe in NEI
#
#### What happend instead? (Attach screenshots if needed)
Didnt worked as it should
#
#### What do you suggest instead/what changes do you propose?
Please look into that and maybe change it

https://i.imgur.com/i1UrQW7.png
https://i.imgur.com/ko3H4zK.png
https://i.imgur.com/kU2x9AM.jpg
https://i.imgur.com/pfI1Etz.jpg
--> 
additional informations on this : 
it´s possible to craft the butchery knife to a cutting board from Pams Harvestcraft. And from this cutting board its possible to craft endless butchery knifes bcause the cutting board doesnt get consumed in the process and doesnt lose any durability

**Comment by richardhendricks** [comment]
Confirmed. Also, the knife-> cutting board accepts any butchery knife, when it should only be stainless steel.

**Comment by richardhendricks** [comment]
@Dream-Master The recipe needs to consume the knife, and not go the other direction.  Up to you on if it requires a fresh knife.
