### ISSUE TITLE
Cherry pick and test fix for multiamp dynamos

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4237]
https://github.com/Blood-Asp/GT5-Unofficial/pull/1518/commits/23d8fb6b6743b25bf24d320a647fccdc016a9930

**Comment by richardhendricks** [comment]
Also update buffer dynamo tooltip if necessary.

**Comment by Dream-Master** [comment]
@richardhendricks you will doing the pull ?

**Comment by richardhendricks** [comment]
I want to test it first then I will do the pull.

**Comment by Dream-Master** [comment]
oh i pulled it allready :/

**Comment by richardhendricks** [comment]
Just now, or a long time ago?

**Comment by draknyte1** [comment]
> Also update buffer dynamo tooltip if necessary.
 
they should already reflect the fact they’re multi Amp by the name?

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/181

**Comment by richardhendricks** [comment]
Need to update quests to reflect new multiamp dynamos.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57188629-6c895e80-6ec7-11e9-893e-ba0005b91060.png)
![image](https://user-images.githubusercontent.com/1214811/57188633-7743f380-6ec7-11e9-9292-06bf4848427f.png)
