### ISSUE TITLE
Assembling Machine doesn't accept certain circuits from automation

### ISSUE THREAD

**Issue by mulisz100** [GTNewHorizons/NewHorizons#4239]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to put Nanoprocessors and Microprocessor in assembling machine by any automatic means (Me System autocrafting, Ender IO conduits, Steves Factory Manager etc.). Everything works when i put those circuits in machine by hand. This includes also input hatches (tested with GT++ Multiblock Assembler). Recipies we're all correct
#
#### What happend instead? (Attach screenshots if needed)
Machine refuses to accept said circuits by any automatic means. Putting them by hand works and machine starts running
Screenchots provided we're made when trying to make Field Generator I
![2019-03-11_10 23 10](https://user-images.githubusercontent.com/27481104/54113619-fbf32380-43e8-11e9-8b46-191d0400e8bb.png)
![2019-03-11_10 23 27](https://user-images.githubusercontent.com/27481104/54113626-01506e00-43e9-11e9-8401-ec8214ea06ad.png)
![2019-03-11_10 23 29](https://user-images.githubusercontent.com/27481104/54113633-04e3f500-43e9-11e9-9b71-9a4fe3408b01.png)

It seems someone made issue about it 9 months ago but it's still not fixed
#

**Comment by Dream-Master** [comment]
oh noo again?
@bartimaeusnek any idea why? i have the same issue with the assline as well. not sure if it is a nei visual bug or a real bug

**Comment by bartimaeusnek** [comment]
no idea.

**Comment by boubou19** [comment]
maybe related to #2892

**Comment by soncemvo** [comment]
have same bug
