### ISSUE TITLE
Server Connection Issues

### ISSUE THREAD

**Issue by Rollermad** [GTNewHorizons/NewHorizons#424]
I keep having issues at around 9am BST with connecting. Its fine later in the day but in the morning I can't connect and it says I have an invalid game session.

![1a](https://cloud.githubusercontent.com/assets/16381149/11927057/87a22524-a7c1-11e5-880d-1b2cc77d905e.png)
![1b](https://cloud.githubusercontent.com/assets/16381149/11927061/8a915bd8-a7c1-11e5-985d-91450ce49040.png)
![1c](https://cloud.githubusercontent.com/assets/16381149/11927062/8c7bf2be-a7c1-11e5-8611-9231f07d5e14.png)

Any ideas?

**Comment by Rollermad** [comment]
http://prntscr.com/9gpnbq

I restarted and it seems even worse, i am going to reinstall I think

**Comment by Rollermad** [comment]
I redownloading and that error is still happening ^

Time to play Cities Skylines I guess :D

**Comment by Dream-Master** [comment]
log in and off. If this not help close the launcher and reopen it. I have this issue today too try to log in maybe 7 or 8 times.
