### ISSUE TITLE
Suggestion: Buff Platinum Group Sludge

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#4241]
So the consensus seems to be that, while platinum group sludge is a cool concept, it's pretty much useless. 
At the moment, it takes 9 ores to get 1 platinum group sludge, and 1 platinum group sludge only has chances to get tiny piles of dust- meaning you need 81 ore to get 1 gold and 1 platinum, and less of the other dusts.
As such, my suggestion:
Make gold and platinum a WHOLE pile, instead of a tiny pile. That way it's now 1 per 9 ore, on par with what you'd get from processing the crushed ore twice INSTEAD of doing platinum group sludge. 

After that, bump the other 3 tiny piles up to 100%, from 80% and 60%. Just a minor statistical buff, and makes it more consistent. Still requires over a stack of ore, 81 each, to get each dust, so it's not going to be a major source of palladium, osmium, and iridium before it's available.

Make platinum group sludge centrifuging HV, with a time of 15s instead of LV for 45s. Just for the centrifuging, not for producing it. I originally considered EV, but HV uses plenty of platinum and gold, so I figured it'd be better there.

**Comment by richardhendricks** [comment]
Gold is easy to get.  Platinum is available from nickel ores in the chemical bath.  Otherwise, I am OK with this.

**Comment by finkledoodle** [comment]
Giving players more options for things seems like a good idea, especially if it's a viable alternative before they are able to get actual platinum ore.
