### ISSUE TITLE
Suggested edits for Coins quests

### ISSUE THREAD

**Issue by Kanisof** [GTNewHorizons/NewHorizons#4243]
Here are a few suggestions/fixes for the coins, coins, coins tab

#### Which modpack version are you using?
2.0.7.0

#### What do you suggest instead/what changes do you propose?
Iron (III) Chloride cells require Biodiesel quest to unlock. Change this to needing Iron (III) Chloride quest.
Light Fuel/ Heavy Fuel / Naphtha cells all require Methane quest. Change to their respective quests.
Ethanol and Sulfuric Acid require Tier 4. Change to their respective quests

**Comment by Dream-Master** [comment]
i change a few but i dont make this quest much  more easy.
