### ISSUE TITLE
Change block needed for Pyrolusium crop.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4244]
At this moment blocks required under pyrolusium crop are Manganese Ore block or manganese block, as Manganese block is obtainable at any poin of the game due to loot from chests or Overworld ore vein, the Manganese Ore block is obtainable at Europa earliest.

Manganese is HV material required for stainless, thus I'd love to see change from Manganese Ore block to Pyrolusite ore block as growth indicator block. Even names match, easier to obtain, less material wasted.

Just Europa gate is ridiculous for me.

**Comment by Dream-Master** [comment]
i add a quest you can buy after you reach mv
