### ISSUE TITLE
Text additions for Fertilia quest, #1808

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4245]
@richardhendricks 

So, after some number testing I've come to conlusion that fertilia actually can be viable source of fertilizer.
It's main drop is still mostly useless tiny calcite dust, but rare drops of tiny apatite dust and IC2 fertilizer are more of less the same in numbers which makes it perfect crop for recipe below.

![2019-03-11_08 14 13](https://user-images.githubusercontent.com/9555787/54167806-d9561e80-446b-11e9-82a4-9ef738fc9981.png)

Rate is more or less 1:1, so 9 tiny apatite piles + 8 IC2 fertilizer -> boom 30 forestry fertilizer, which is a good number. I can power fullsized crop farm, multilayer oreberry and 2 fullsized tree farms with this amount of fertilizer using 25 max stat fertilias. And its nothing compared to max size farm.

So I think its worth to mention this one in quest.

PS. Also worth mentioning, best way I found to breed fertilia is using 2 zomplant crops, highest chance of mutatnion with these.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57188580-adcd3e80-6ec6-11e9-81a7-eeab3eb35b8a.png)
