### ISSUE TITLE
New crop related quest branch.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4247]
Basically breeding through reed line to get diareed.

Stickereed -> blazereed -> withereed -> oilberries -> diareed

Withereed can branch to God of thunder which can branch into reactoria, for reactoria better breed would be prob t12 crops but viable doing with god of thunder.

@richardhendricks I'll leave quest texts and rewards for you.

**Comment by bedrill64** [comment]
Some notes worth mentioning in quests.
Thorium for god of thunder can be found in nether, which when processed with thunder leaves gives Uranium that can be used for blocks for reactoria crop.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57200823-0566bb00-6f56-11e9-87f8-9f4172923782.png)

![image](https://user-images.githubusercontent.com/1214811/57200821-fd0e8000-6f55-11e9-9d7a-8d9838f2b51e.png)

![image](https://user-images.githubusercontent.com/1214811/57200827-0c8dc900-6f56-11e9-9abc-9a6d9a2205f1.png)

![image](https://user-images.githubusercontent.com/1214811/57200828-1283aa00-6f56-11e9-8da1-38ea20ad8f5a.png)

Al;so added liveroots quest before steeleafranks quest.

![image](https://user-images.githubusercontent.com/1214811/57200927-33003400-6f57-11e9-9bbb-a2b0669b7f6a.png)

**Comment by richardhendricks** [comment]
Added a Corium quest after Flax.
![image](https://user-images.githubusercontent.com/1214811/57201016-9e96d100-6f58-11e9-88ed-9c6f631ba6ac.png)

**Comment by bedrill64** [comment]
Flax has easy breed for cotton in IC2 crop form, if you use both of them you can simply autocraft woven cloth + corium -> easy tanned leather.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57201074-59bf6a00-6f59-11e9-91ef-842de1ca2288.png)

**Comment by richardhendricks** [comment]
Is creeperweed the best source for liveroots?
Also is liveroots best for steeleafranks?

**Comment by richardhendricks** [comment]
also what's a good source for eggplant?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57201176-f6363c00-6f5a-11e9-9d6f-d5c427de9370.png)

![image](https://user-images.githubusercontent.com/1214811/57201179-ff270d80-6f5a-11e9-85c8-c2119c15cbb6.png)

**Comment by richardhendricks** [comment]
I went with milkwart as an eggplant source, seems decent.

**Comment by richardhendricks** [comment]
Tearstalks, I don't recall what I used to breed those?

**Comment by bedrill64** [comment]
Loading world, gonna check everything in a sec, for tearstalks alone iirc stickereed was best, but gonna check.

**Comment by richardhendricks** [comment]
Quantaria too.

**Comment by bedrill64** [comment]
Easiest obtainable for tearstalks: Argentia/nether wart/blazereed.
Withereed suprisingly is harder than I initially tought, I'd go with plumbilia as its easy metal crop also.
Once you have withereed its easy route for rest of unknowns like oilberries, creeperweed, god of thunder.
Liveroots definetely creeperweed, for steelafranks liveroot, liveroot is also best source trollplant(pu-241 for mutagenic frames)
Steela franks -> bobsyeruncle -> enderbloom.

If you can't get milkwarts, blazereed is good for eggplants.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57264861-18eb5200-703a-11e9-952e-60f16a2c61d1.png)
![image](https://user-images.githubusercontent.com/1214811/57264863-1d176f80-703a-11e9-90a3-37495599f58b.png)
![image](https://user-images.githubusercontent.com/1214811/57264864-20126000-703a-11e9-9bed-c0656ee3d6c3.png)
![image](https://user-images.githubusercontent.com/1214811/57264870-23a5e700-703a-11e9-8144-ceeb2be58b9c.png)
![image](https://user-images.githubusercontent.com/1214811/57264872-26084100-703a-11e9-8c02-aee37fb3cdad.png)

**Comment by bedrill64** [comment]
Block of knightmetal is kinda too op reward for this crop, you can get seeds without block, but you can't harvest it without knightmetal block, I'd give 8 ingots instead so ppl have to get 1 remaining ingot from twilight forest.

**Comment by richardhendricks** [comment]
Yeah, liveroots and steeleafranks don't require a block underneath, AFAIK. I wasn't actually thinking of the block as a gift so that players could make knightmetal, but I guess I am OK with it too.  I was just getting bored of giving players dusts.
