### ISSUE TITLE
Add a new mod

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/NewHorizons#4249]
#### What do you suggest instead/what changes do you propose?
There is a mod ,After add this mod ,it can Keep historical information about the NEI search,And can display favorite items.It is very usefull.
![`2@QPQ7@HGRK~U5D{1AZD}J](https://user-images.githubusercontent.com/41377439/54186581-ac931d00-44e6-11e9-8ac6-f0741d0edea7.png)

Here is his link:http://www.mcbbs.net/thread-614246-1-1.html

**Comment by LogicFalls** [comment]
This is client-side, right? If people want to use it then they can download it for themselves.

**Comment by bartimaeusnek** [comment]
@LogicFalls they cant since its a chinese only forum with requires a baidu account to actually download the mod...

**Comment by Dream-Master** [comment]
so i guess not

**Comment by Dream-Master** [comment]
@SKYCATV587 sorry but the mod need to be aviable on curse or on a download page you dont need a account.
