### ISSUE TITLE
Make a new Grog Recipe or move to Forestry 4

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#425]
My client crashes with the latest update:
http://pastebin.com/Ts4kCGjN

Probably the changed/removed Computronics species

**Comment by Namikon** [comment]
Update: The bee species "Scummy" is completely gone now; And grog doesn't have a recipe anymore

**Comment by Dream-Master** [comment]
we cant use Forestry 4 atm because of Binnie. So what we can do in the meantime?

**Comment by Dream-Master** [comment]
can you login or crash it everytime you join the game ?

**Comment by Namikon** [comment]
I can't open my species chest, which contains my entire collection of gene samples.
Not a problem at all, I can just spawn the expensive species I had again. Problem is that the Scummy bee is missing, and thus you can't work with OpenComputer's NanoMachines

**Comment by Dream-Master** [comment]
so make a nother recipes how to get grog ?

**Comment by Namikon** [comment]
So computronics 1.6 requires forestry 4.1+. We need a new way to get grog

**Comment by Namikon** [comment]
Please add a new way to get grog, or just use the default OC recipe. The whole Nanobot system in OC is locked due to this Bee issue

**Comment by Dream-Master** [comment]
Ok you can make Grog now because we update to Forestry 4.
