### ISSUE TITLE
BM quest

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4250]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Following the quest 'Powerful Shards' in the 'They Are Coming...' tab
QuestID #703

Step 1 asks for 16 life and soul shards

![image](https://user-images.githubusercontent.com/34566584/54197701-c0f00d80-4518-11e9-923b-d0449d18471f.png)

Step 2 asks for 4 Crystal Clusters, each infusion requiring 5 of each shard.

![image](https://user-images.githubusercontent.com/34566584/54197738-d6653780-4518-11e9-99fb-f3e44e621b87.png)

![image](https://user-images.githubusercontent.com/34566584/54197775-eda42500-4518-11e9-8969-79f8bbd4c9ac.png)

Can we get step 1 to be more inline with whats require, changing the amount of shards needed to 20 of each to complete step 1?

**Comment by Dream-Master** [comment]
will change
