### ISSUE TITLE
Chest loot

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4251]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Open loot chest, and I expect to get loot. Instead I got many of these from different chests
![image](https://user-images.githubusercontent.com/34566584/54197927-4f648f00-4519-11e9-9ac9-273ca4463286.png)

I purpose they be removed from the loot table, since they are completely useless.
Also remove the one ring for chest drops, it's stupidly OP. If it can be crafted, leave it in that way.

**Comment by Dream-Master** [comment]
@draknyte1

**Comment by draknyte1** [comment]
They're there intentionally, not a bug/issue.
To remind the great folks of GTNH that they got the Void Frame nerfed out of existence.

**Comment by Dream-Master** [comment]
ok but the frame is from gt++ and quit useless in a chest. Can it be removed from loot table or have I to do this with my core mod?

**Comment by draknyte1** [comment]
I know it’s useless, like half the other loot from chests. It’s a novelty loot item and it’s not going anywhere. I intentionally left it there after everyone wanted it removed. :shrug:

**Comment by Dream-Master** [comment]
i take time to change the loot tables with the loot mod .

**Comment by draknyte1** [comment]
Cool? Do whatever you want.. just Don’t remove my dungeon loot I put there, as a rare item. I don’t care if you find it useless, other players do not.

**Comment by Dream-Master** [comment]
I spoke about the useless frame nothing more and this is a useless item for gtnh at all and need to be removed from the loot table in gtnh.

**Comment by Dream-Master** [comment]
i add coins recipe for useless frame

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54635437-6d377400-4a84-11e9-815c-50439867ad31.png)
