### ISSUE TITLE
Additional Be(e) Breeding quests

### ISSUE THREAD

**Issue by kekzdealer** [GTNewHorizons/NewHorizons#4252]
pack version: 2.0.7.0

- [x] unweary
- [x] diligent
- [x] sweetened/valiant
- [x] fruity
- [x] Blooming - bonemeals nearby saplings
- [x] Imperial - Regeneration buff as radiation accident prevention?
- [x] clay
- [x] aqua - removes effects, like using milk
- [x] coal/oil
- [x] Spidery bee gives largish territory pretty easily.
- [x] Cave Dwelling - Rocky
- [x] Nocturnal - Rocky
- [x] Rain tolerant - Water bee
- [x] 4 fertility - wintry bee
- [x] skeleton - crap, doesn't spawn very fast, and no wither skeletons from what I could see.
- [x] other spawning bees, brainy/wispy/ghastly/ablaze/etc
- [x] spectral/phantasmal
- [x] Heroic - Damages hostile mobs - do they give player drops?
- [x] Collecting bee - picks up nearly items - is this in our pack? (probably not, from career bees)
- [x] Hermetic - repels hostiles
- [x] copper - opens up metals lines
- [x] Lapis/redstone/certus/diamond?
- [x] fluix?
- [x] Nuclear/radioactive - which is preferred? Dangerous bees
- [x] XP bees
- [x] shard bees, aqua for poison curing? maybe this fixes radiation?
- [x] salis mundus bees
- [x] rejuvenating, other node boosting bees
- [x] Pure bee
- [x] excited/energetic/ecstatic bees as sources of energy from lightning bolts?
- [x] Solum bees? Faster mining?
- [x] celebratory bee - spawns fireworks

Need to add quest talking about specific breeding strategies. "pristine" line of queens, breed in drones, etc.

**Comment by richardhendricks** [comment]
skeleton, zinc, magic bees to boost nodes, twilight forest bees, meat bees, sugar bees, XP bees, coal, oil,

**Comment by richardhendricks** [comment]
verify skelly bees will spawn wither skellies in the nether, and the distance, and if player required to be nearby

**Comment by kekzdealer** [comment]
...and whether cursed earth works as a substitute or not.

**Comment by richardhendricks** [comment]
Fruity bees for accelerating forestry tree maturity.  Great for making seedoil.

**Comment by richardhendricks** [comment]
Quest Reward ideas
robust bee, steadfast/valiant as quest reward

Lootbag additions
clay bee as lootbag reward


More reward ideas please, both for quests and lootbags.

**Comment by kekzdealer** [comment]
More quests for Alveary upgrades would be cool. Not sure which ones are actually required, but I wouldn't mind making some for a quest. 
- Frame Housing
- Alveary Fan
- Alveary Heater
- Alveary Hygroregulator
- Rain Shield
- Electrical Stimulator
- Alveary Lighting
Could all be in one quest and maybe reward a stack of Scented Paneling. Those are the more annoying component for Alveary Blocks and would last for eight blocks. A full Alveary takes 27.

**Comment by Jocroy** [comment]
Lootbag additions: Lavacapsules and snowballs for use in the acclimatizer. Maybe even other Genetics items: Fluorescent/DNA dye or Enzymes. Gene sequences for good traits would probably be too OP, as are Genetics Integrated Circuit boards.

**Comment by richardhendricks** [comment]
Lootbag additions
Hives, frames, drops
Would be the ideal things
Honey drops*
Scoops
Small chance at alveary chest maybe

**Comment by richardhendricks** [comment]
Alveary quests added

**Comment by richardhendricks** [comment]
Bee quests completed.
