### ISSUE TITLE
Problems with bee comb ore quadrupling recipes

### ISSUE THREAD

**Issue by Extremity4** [GTNewHorizons/NewHorizons#4253]
#### Which modpack version are you using?
2.0.7.0
#

Some of the bee combs are a little weird right now and there's missing recipes for quadrupling of a number of ores. I haven't gone through it all in any depth, but here's what I noticed on a quick lookthrough:
Astral silver uu and chemical reactor recipes lead to silver, not astral silver.
Sparkeling comb can't quadruple netherstar ore. Also maybe change name to Sparkling 
Nickel comb quadruples powellite and wulfenite but that doesn't seem right?
Lead comb only quadruples lead ore? Galena makes more sense to use lead combs than silver IMO
Cassiterite sand should maybe also be quad-able with tin combs?
Gallium comb quadruples niobium for some reason
Titanium comb doesn't quadruple titanium ore. Maybe it should also quadruple ilmenite?
Chromium comb quadruples niobium and bastnesite for some reason
Tungsten comb doesn't quadruple tungsten or tungstate
Iridium comb doesn't quadruple iridium ore
Osmium comb doesn't quadruple osmium ore
Uranium comb doesn't quadruple uranium ore
Plutonium comb doesn't quadruple plutonium ore
Naquadah comb doesn't quadruple naquadah ore
Naquadria comb quadruples enriched naquadah ore, but maybe it should be naquadah comb instead? not sure about this one
Thorium comb doesn't quadruple thorium ore
Desh comb doesn't quadruple desh
Ledox comb doesn't quadruple ledox
Callisto ice comb doesn't quadruple callisto ice
Black plutonium comb quadruples plutonium 239?
Mysteriouscrystal quadruples emerald and gets uu'd into emerald
Quantium comb doesn't quadruple quantium
Infinitycatalyst doesn't quadruple infinitycatalyst ore

Some of these are more important to fix than other in my opinion, in particular the ones for which a leaf quadrupling recipe exists but no comb quadrupling exists (such as titanium, ilmenite, tungsten, naquadah, iridium, etc). I'm only at EV, so I don't know how the balancing should work for the very high tier materials like black plutonium and infinity catalyst

**Comment by Dream-Master** [comment]
Astral silver have no ore thats why goes to silver

**Comment by richardhendricks** [comment]
This is for IC2 crops, but I think it has similar situation for bees:
No moly leaves, hence why powellite and wulfenite use nickel leaves
galena uses silver leaves because the molten byproduct is silver

cassiterite sand is already 8x with macerator, not sure if another 4x is needed, but maybe add? Are there really any big tin sinks?

**Comment by Dream-Master** [comment]
@Extremity4 most of the recipes autogenerated and cant be changed so easy. Sure i can add own recipes but this is a mess.

**Comment by Dream-Master** [comment]
high tier combs have only uu matter recipe. I dont add the other ones. If you want i add it i need a fluid is using quadrupple it.

**Comment by Dream-Master** [comment]
there is no wulfenite or powwelite comb so why not?

**Comment by Dream-Master** [comment]
there is no niobium bee so why not

**Comment by Dream-Master** [comment]
i forgot two line of code lol
