### ISSUE TITLE
IC2 SGPU crashes client when attempting to leave its interface

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4254]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon, Eta
#

Issue is pretty much in the title. I do realize placing stargate blocks are disabled unless in creative and the use of the block is very much limited, but still decided to post the issue. Let it be known :D

**Comment by Dream-Master** [comment]
IC2 SGPU ?

**Comment by Dream-Master** [comment]
@MrWye

**Comment by MrWye** [comment]
its the IC2 Stargate Power Unit, its placed under the stargate to power it.

**Comment by Dream-Master** [comment]
ah ok

**Comment by Dream-Master** [comment]
@MrWye i need a crashlog please.

**Comment by MrWye** [comment]
Crash log https://pastebin.com/hZWcNh6W

**Comment by Dream-Master** [comment]
can you try with a rf power unit. Can be crafted out of the ic2 one

**Comment by MrWye** [comment]
Sorry for delay on update. We were setting up admin gate on Eta with Namikon using OC dial script and it turned out that some gates do not get enough power from IC2 SGPU. So we replaced them with RF SGPU and it appear to work just fine, no crashes with that block. Only downside being you have to setup 2 or in many cases 3 of them below the gates to power it. 
I suppose IC2 variant can be left alone, since RF variant works just fine and doesn't crash the client.

**Comment by Dream-Master** [comment]
maybe i disable it ?

**Comment by MrWye** [comment]
You can disable it, yes, unless it is used in some other crafting recipe, i have not checked.
