### ISSUE TITLE
Errors in Datasheet Ore Spawn page

### ISSUE THREAD

**Issue by AsciiBunny** [GTNewHorizons/NewHorizons#4255]
#### Which modpack version are you using?
2.0.7.0
#
#### What did you try to do, and what did you expect to happen?
In the datasheet, specifically the [Ore Spawn sheet](https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1941759795), I came across data that does not match with what I find in my world.
For Apatite, the current data is as follows:
**21** | Apatite | Apatite | Apatite | Phosphorus | Pyrochlore | 530, 534, 833

In all Apatite veins I generated they consist of Apatite, Tricalcium Phosphate and Pyrochlore. In addition the current id's do not match with the stated ores.

For Draconium the current data is as follows:
**51** | Draconium | Draconium | Nikolite | Jade | Vinteum | 975, 812, 537, 529

It mentions Nikolite while this ore is called Electrotine in every other ore vein and ingame
#
#### What do you suggest instead/what changes do you propose?
I propose the datasheet be changed to:
**21** | Apatite | Apatite | Apatite | Tricalcium Phosphate | Pyrochlore | 530, 534, 607

**51** | Draconium | Draconium | Electrotine | Jade | Vinteum | 975, 812, 537, 529

As I understand, the sheet is generated by an NEI plugin, as I do not have MultiMC setup I wasn't able to run it so I do not know if its results are correct.

**Comment by Dream-Master** [comment]
Yes the sheet is quit old and not updated

**Comment by richardhendricks** [comment]
Need to update spreadsheet with new 2.0.7.0 section

https://gtnh.miraheze.org/wiki/GT-NEI-Ore-Plugin_Spreadsheet_Export_Tutorial

**Comment by AsciiBunny** [comment]
I've generated a new csv file for 2.0.7.0.
[GTNH-Oresheet.zip](https://github.com/GTNewHorizons/NewHorizons/files/2959120/GTNH-Oresheet.zip)

**Comment by dragagon** [comment]
I went ahead and made a copy of the official sheet, added a new sheet for 7.0 and put the csv into it. If you want to copy it into the official sheet, you can steal it from here: https://docs.google.com/spreadsheets/d/1e2-bYblJBSLlMDAHAETA1VD2s8oTK5IvVtG4E3wkrqo/edit?usp=sharing

**Comment by richardhendricks** [comment]
Spreadsheet updated.
