### ISSUE TITLE
Infernal Blast furnace

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4256]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

Apparently a lot of the EnderIO ingots such as blue steel, electrical steel etc and regular steel can be processed through the Thaumcraft Infernal Blast Furnace.

They should be forcing the use of the GT EBF, unless this is intended.

**Comment by Dream-Master** [comment]
i guess this was intended @bartimaeusnek ?

**Comment by Beyond-Veil** [comment]
Not sure why you'd force EBF? It requires late MV / HV to build and none of these ingots require a freezer to make (before you can get the materials). the machine is slow and relatively hard to maintain and hard to automate. It does have some unique benefits for those that are willing to invest in dark magic to get the native cluster research, but AFAIK has no material benefit compared to the EBF and for most items is slower

**Comment by richardhendricks** [comment]
If I recall correctly the last time this discussion came up, MV recipe items (steel, aluminium etc) are allowed since the ABF is not upgradeable and cannot be speed boosted.
