### ISSUE TITLE
Reward bag suggestions

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4257]
Some additional reward bag suggestions

Pre-stone/stone age bags
- Short duration water breathing and night vision potions. 1/2/4 each? Nice reward that helps for finding clay
- enchanted imp leather armor set

Stone/steam age bags
- long duration water breathing and night vision potions
- Scuba mask and 8 compressed cells for working underwater
- short duration flying potions
- iron GT tools

LV age bags
- long duration flying potions
- steel GT tools
- VS GT tools

Stuff to add to trash collection loot
random mob head, skele, zombie, enderman, wither
peanut butter sandwichs
pies
wood screws
64 salt dust

**Comment by Beyond-Veil** [comment]
Assuming VS stands for vanadium-steel, sounds like a hefty upgrade compared to steel in LV. Maybe damascus steel? it is also L3 but twice as good as steel rather than 3x?

otherwise i think it is rather well thought out
