### ISSUE TITLE
Extra Utilities Tools

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4258]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Used both the erosion shovel and the destruction pickaxe.
Expected them to work like whats listed on their wiki page

https://ftbwiki.org/Erosion_Shovel
>  It quickly works its way through soft dirt substances and will eliminate sand or gravel that is above it. Like the Destruction Pickaxe, it will not drop any blocks. It will dig slower than a fist used for any other block

https://ftbwiki.org/Destruction_Pickaxe

>  It is five times as efficient as a Diamond Pickaxe, but only on stone. On all other blocks it is worse than bare hands. Blocks mined with it will not drop any items. This makes the pickaxe very useful for mining large amounts of stone without filling up the Player's inventory. 

#
#### What happend instead? (Attach screenshots if needed)
The pickaxe mines all GT ores, stone etc up to manullyn and drops them normally instead of dropping them. There is no speed reduction for mining ores vs stone.

The shovel just works like a shovel and doesn't destroy items either. No speed reduction outside of dirt.

#
#### What do you suggest instead/what changes do you propose?
Make them work as intended. It might be a conflict with IguanaTweaks/TiCon

**Comment by Dream-Master** [comment]
Extra utilities is closed source mod.

**Comment by AlexBucket** [comment]
It could be a conflict with iguana tweaks that makes them work unintentionally.

**Comment by Dream-Master** [comment]
maybe iguana is open source
