### ISSUE TITLE
Thorium Reactor Quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4259]
Due to the time gates required for lutetium we should make a quest to encourage the creation of thorium reactors early to avoid people getting stuck at a 14 hour per cycle time gate in late zpm.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54618468-5f252b80-4a63-11e9-8737-d57b8f11468e.png)
the quest is there.

**Comment by richardhendricks** [comment]
Make the quest a main quest, add info 

"Note: You will need the byproducts from Thorium fuel processing later, better start on a reactor now!"
