### ISSUE TITLE
Block placers do not place blocks

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#426]
The two redstone powered block placers (Project Red and Openblocks) both cannot place blocks in the world.

Tested it outside the region to make sure it isn't region related.

**Comment by Dream-Master** [comment]
Maybe be have to repprted on Project Red side. Work it in Singelplayer ?

**Comment by Teteros** [comment]
Server related only. Possibly permissions/fakeplayers.

**Comment by Namikon** [comment]
After a reboot... Changed the permission set. Both placers work now as expected

**Comment by Dream-Master** [comment]
@Namikon 
Die ganzen KCauldron configs die du wo und wie eingestellt hast musst du mir bitte bei Gelegenheit mal erklären. Immer wenn jemand was fragt steh ich da hab keinen Plan.
