### ISSUE TITLE
Redstone-Trigger chat messages

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4262]
I'm suggesting either finding or making a mod that adds a block to the game.
This block, when powered with redstone, will send a chat message to the player that placed it, with the option to play a sound as well. This would work cross-dimensionally, and at any distance as long as the block is chunkloaded.

GTNH is big, and occasionally little things like maintenance or the depletion of a resource requires immediate attention. Adding cross-dimensional support will also give this block more use than say a redstone powered lamp or howler alarms. This is the same sort of idea as Factorio's alarms, wherein the player is able to set a sound and a message to appear when their attention is required.

**Comment by richardhendricks** [comment]
Suggested tier - HV
Can make it a GT machine that needs power + controlled by redstone?
ender pearls part of recipe?
Should be doable with a user-custom chat message, and selecting from a few different alarm options.

**Comment by LogicFalls** [comment]
EXP ding, Anvil clang, Ghast cry and bat squeak are go-to alert SFX from Vanilla. If you can nick some actual alarms from IC2 that would be cool too.

**Comment by richardhendricks** [comment]
Wilhelm scream, door squeak that is in *every* damn movie, and Discord ding. ;)

**Comment by Anarack** [comment]
What about flashing the taskbar icon or equivalent?

**Comment by richardhendricks** [comment]
That would probably not be possible lol.  But we could give the player blindness! :D

**Comment by dragagon** [comment]
Could you do a quest complete popup? xD

**Comment by AlexBucket** [comment]
> Wilhelm scream, door squeak that is in _every_ damn movie, and Discord ding. ;)

Needs more goldfish screams, endless until the redstone is toggled off.
