### ISSUE TITLE
GT gasses stored in BC tanks realistically

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4263]
I'm not sure how, but when gases like steam are stored in Thermal Expansion tanks, the volume of fluid is indicated by alpha of the texture, instead of filling from the bottom like a normal fluid - as if you can see the gas becoming more dense inside the tank.

Would it be possible to create this behavior with BC and RC tanks and GT gasses?

**Comment by Dream-Master** [comment]
Idk if BC is open source. RC is open but I can't compile it (license)
