### ISSUE TITLE
AE2 Cutting Knifes

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4264]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
GTNH Delta
#
#### What did you try to do, and what did you expect to happen?
The Nether Quartz Cutting Knife and Certus Quartz Cutting Knife of AE2 don't have a recipe.
I want to craft them for a name press but they cannot be obtained.
#
#### What do you suggest instead/what changes do you propose?
Add a recipe for either one or both versions

**Comment by AlexBucket** [comment]
Would be much nicer than doing them in an anvil for sure.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54615384-4fefaf00-4a5e-11e9-85c2-5058b6abd443.png)
![image](https://user-images.githubusercontent.com/2970688/54615419-5e3dcb00-4a5e-11e9-95d0-de884052af09.png)
