### ISSUE TITLE
Steeleaf issues.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4265]
Steeleaf dust has only 1 recipe in alloy smelter - small dust -> steeleaf, its missing regular dust and tiny dust ones.

Another thing, steeleaf soft mallet can't be crafted with regular stick, it requires natura ones and only those work for crafting.

**Comment by Dream-Master** [comment]
wired. will check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54613700-72cc9400-4a5b-11e9-835e-dc9641b1e8e2.png)
works with normal stick

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54614072-1453e580-4a5c-11e9-8686-adede81f0f5e.png)
added
