### ISSUE TITLE
Crossbow bolts tips fluid fix.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4266]
If you want to create crossbow bolt in fluid solidifer with steel/iron, it wants to use Tinker's construct ones which require input of 1000mb via bucket, you can't use fluid extractor to input 144mb of metal because they are not oredicted. Fix that if possible.

Also all you can do with 8 ingots leftover is use plunger on it because it can't be turned into ingots.

Another thing, quest doesn't say that you have to use fluid canner and tinker's construct metal, make adnotation for that because I just spent 2h looking for solutions till I realised I'm using wrong iron/steel.

**Comment by Dream-Master** [comment]
Are a quest text change will fix it /inform you ?

**Comment by bedrill64** [comment]
Well, it will guide ppl how to actually do that but won't fix material waste issue, i'd still opt to add GT versions to recipes.

**Comment by richardhendricks** [comment]
So in the quests as-written now, I tell players that iron/steel/alumite works on wooden bolts in the casting table, and anything higher they need to use the fluid solidifier.

I think the magnalium crossbow quest tells people to use the fluid solidifier, so there isn't an issue there.

Is the problem trying to use a better shaft but with still iron/steel/alumite? I suppose we could add GT fluid recipes for those to the solidifer, but idk.

**Comment by bedrill64** [comment]
Quest doesn't say that you have to use smeltery metal and then use fluid canner to input it into machine, Intuitively I input metal via fluid extractor and it doesn't work because its not supported in recipe, I had to go through each of 150 of bolt recipes, find iron that was looking totally not like the one I input via extractor, then after pressing it appeared that I have to use smeltery one.

Make it clear in quest or/and add fluid extractor versions for bolts, cause as above knowing that you have to do that do not solve issue of 8 ingots being wasted in process.

**Comment by richardhendricks** [comment]
yeah OK, I think it makes more sense to fix the recipes since not everyone does quests. :P

**Comment by Dream-Master** [comment]
@richardhendricks you cant fix the recipes because autogenerated. Guess you have to do it in Tgregswork or so.
