### ISSUE TITLE
Tier 8 Rocket is Impossible to Obtain

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4267]
#### Which modpack version are you using?
2.0.7.0

Due to an overlook and recent adjustments to the rocket tiers, it has been noticed that the Tier 8 Rocket requires UEV voltage in an Assembler and molten Flerovium that does require the use of a Tier 4 Fusion Reactor. These two machines require a UEV circuit in their recipes, however, the UEV circuit requires the Tier 8 Planet Tceti E and the seaweed; there's no other way to obtain seaweed early without going to the planet. See where this problem occurs? Yes, you can use a GT++ Autocrafter (or otherwise known as the Assembler Multiblock) to bypass the UEV requirement; however, that still doesn't bypass the Tier 4 Fusion Reactor. Pictures for examples: 
![GT7](https://user-images.githubusercontent.com/41557212/54408960-7a79ea80-46a1-11e9-9cf1-d8e666a3b974.PNG)
![GT11](https://user-images.githubusercontent.com/41557212/54408961-7b128100-46a1-11e9-8742-5c9f4cb7c5a7.PNG)
![GT10](https://user-images.githubusercontent.com/41557212/54408962-7b128100-46a1-11e9-91ce-841494879572.PNG)
![GT9](https://user-images.githubusercontent.com/41557212/54408963-7b128100-46a1-11e9-96cb-15a50a9fcb4a.PNG)
![GT8](https://user-images.githubusercontent.com/41557212/54408964-7b128100-46a1-11e9-9bf2-d337eb73ed8e.PNG)

**Comment by Dream-Master** [comment]
yes we need to redoing t8 and the trinium one.

**Comment by BlackFlameTNT** [comment]
i was looking at it Heavy duty alloy ingot T6 need UV.
i think this is overkill.

**Comment by Dream-Master** [comment]
I sitting in an airplane will look at it after I arrived Bangkok

**Comment by 0lafe** [comment]
>i was looking at it Heavy duty alloy ingot T6 need UV.
i think this is overkill.

idea was to give each tier a rocket, HV+ instead of 2 tiers having 2 rockets. Changing the current bio recipe will fix this issue, as long as it doesn't rely on t ceti seaweed anymore. Could maybe use the seeweed stuff in the nano line instead?

**Comment by BlackFlameTNT** [comment]
So I was testing a bit the yesterday if I can make the plate with GT++ autocrafter it dose not work am not sure it it is the muilt block or the plate it self.

**Comment by Dream-Master** [comment]
Ok for now i set t8 rockets use 4x molten neutronium than t7. If you have a better just write here.

**Comment by BlackFlameTNT** [comment]
At what voltage I would say at UHV not UEV.
Maybe molten Flux.... Or molten cosmic neutroium.

**Comment by 0lafe** [comment]
Once a proper bioline comes we should rechange some of this

**Comment by BlackFlameTNT** [comment]
You need to have T8 rocket to be able to make UEV stuff
