### ISSUE TITLE
Reward bags are absolute trash: EV suggestions

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4268]
I just opened a few EV tier reward bags, got saplings, seeds, a book and other shit. They feel absolutely worthless, got some recommendations for loot:
-Meteoric Iron
-Workstations
-Superconductors (MV and HV)
-Vibrant Alloy
-Early Galacticraft parts (Compressed Steel/Alu/Tin/Bronze)
-Liquid Oxygen Cells
-Industrial TNT

**Comment by boubou19** [comment]
were the bags enchanted? because you have also a chance to get rewards from other tiers if not enchanted

**Comment by Dream-Master** [comment]
No you have a chance get trash loot from bags. Idk how high is the chance.

**Comment by Impos913** [comment]
I see EV lootbags giving you more trash than HV-MV ones. Add more good loot or decrease the chance of trash loot or both.

**Comment by richardhendricks** [comment]
From what I understand, the way the reward list is generated the trash list is just added to the "good" items list.  So if the "good" item list is short, you're going to get a higher chance of "trash".

Propose more loot for tiers that don't have many items to get less trash!

**Comment by Dream-Master** [comment]
so far ik 108 items are allowed per lootbag.

**Comment by Namikon** [comment]
> From what I understand, the way the reward list is generated the trash list is just added to the "good" items list. So if the "good" item list is short, you're going to get a higher chance of "trash".

Not exactly true; LootBags use the weighted random algorithm to select loot. You can have 100 trash items and 10 good ones; If the final item weight is high enough on the good ones / low enough on the bad ones, you'll never get trash. It's more a matter of balancing out the weight values.

But yes; Fortune III will get rid of trash completely. 
From what I remember; at EV it should be already trivial to get Fortune III books

**Comment by richardhendricks** [comment]
True.  There is the expensive part that has to be included with the bag to get the fortune boost.  Maybe we need to update the tooltip so it is clear that Fortune gets rid of trash 100%?

**Comment by Namikon** [comment]
There are already 2 Tooltips and *both* point you towards the Fortune Enchantment in addition to the Quest which explains that you should do that. I don't think it is required to do so; But that's just my humble opinion

**Comment by Dream-Master** [comment]
Ok we dont add a additional tooltip but a few more items i can add to the bags.

**Comment by Namikon** [comment]
Again: The amount of items does not affect the chance of "good rewards" you are expecting!
The drop weights need to be rebalanced in order to have any serious effect.

As an alternative; You can also add recipes to enchant the bags with Fortune I and II.
If you shift-right click any bag in creative mode, you'll see a tooltip with drop chances, calculated in percentage for each Fortune Level. (Section == Trash/Fortune Behavior ==, line _Drop % F 0/1/2/3_)

**Comment by Dream-Master** [comment]
yes ik but some bags have less items than other. Add more stuff from the tier is always good to make the bag gabling more interresting.

**Comment by richardhendricks** [comment]
F1 wouldnt be much different to get from F3 IMO. Maybe instead of Fortune use XP buckets instead? I hate the idea of everyone farming XP berries, but at least earlier players would be able to upgrade bags.

**Comment by richardhendricks** [comment]
Could also make upgrading scale with tier. No buckets at pre stone, 1 at stone, etc.

**Comment by richardhendricks** [comment]
Just to be clear, keep the "additional item" needed to upgrade as well.

**Comment by Dream-Master** [comment]
it is a lap crystal rn

**Comment by richardhendricks** [comment]
That is fair for EV IMO.
