### ISSUE TITLE
UHV Components have crafting grid recipes

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4269]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
GTNH Delta
#
#### What did you try to do, and what did you expect to happen?
All UHV Components have a regular 3x3 crafting grid recipes along with the assembly line one.

UHV Motor
UHV Electric Piston
UHV Robot Arm
UHV Convoyer Belt
UHV Sensor
UHV Emitter
UHV Field Gen
UHV Pump
#
#### What do you suggest instead/what changes do you propose?
 Remove the crafting grid recipes

**Comment by Dream-Master** [comment]
Who the hell add that. It wasn't me

**Comment by Anarack** [comment]
Check with alk, it got pointed out to him a while back but idk if he found what added them, though being honest the hand crafting recipes may be way worse than the assline versions.

**Comment by Dream-Master** [comment]
will check.

**Comment by 0lafe** [comment]
It's at least partially ++ related. They're the same recipes the MAX components have when NH installed. Maybe change those recipes to be NH conditional and disable if NH loaded? Max components got switched to UHV parts, and it seems like they kept the recipes.

**Comment by 0lafe** [comment]
@alkalus

**Comment by 0lafe** [comment]
@draknyte1

**Comment by Dream-Master** [comment]
i remove them via minetweaker. Not the best way.
