### ISSUE TITLE
7 high veins

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4271]
#### Which modpack version are you using?
2.0.7.0

I found 9 high veins on TF but on ceres all veins are 7 high and there is no small ores in the veins on ceres.

**Comment by bartimaeusnek** [comment]
all galactic dims should still use the old oregen at this point. @richardhendricks need to apply some changes to galactic greg to make this work propperly.

**Comment by Dream-Master** [comment]
are you sure that was one vein or maybe two veins ? @Impos913

**Comment by Impos913** [comment]
All veins are 7 height

**Comment by richardhendricks** [comment]
Yes I know, I asked him to open this ticket to remind me this work needs to be done.

**Comment by Impos913** [comment]
Alkalus said the chunks might have generated before I went to that dimension. Actually somebody should test this in a new world.

**Comment by Impos913** [comment]
Why I am keep closing this issue accidantly, damn

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4417
