### ISSUE TITLE
Impossible to craft Fusion Reactor MK1

### ISSUE THREAD

**Issue by Guren1993** [GTNewHorizons/NewHorizons#4276]
In first: sorry about grammar, i am from Russia =)
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
my personal home server
#
#### What did you try to do, and what did you expect to happen?
Trying to craft Fusion control computer MK1 on LuV tier.
#
#### What happend instead? (Attach screenshots if needed)
Impossible to craft Dense Naquadria Plate on current tier. Smelting Nq* in EBF needs 9000K coils, but they needs ZPM assembler to craft. ZPM assembler needs ZPM motors, but they needs Europium to craft... also i need Europium on LuV tier to craft Fusion Reactor to craft Europium...
#
#### What do you suggest instead/what changes do you propose?
May be change Dense Naquadria Plate in Fusion control computer MK1 to Dense Naquadah Alloy Plate or nerf Naquadah Alloy Coil  Blocks crafting tier. Or help me find source of europium without fusion, but with Tier4 rocket

**Comment by ScriptedPiky** [comment]
Confirmed that it's impossible to craft. However, if you were to make the GT++ Assembler multiblock, then you'd be able to technically bypass making a single block ZPM assembler in this case.
![GT13](https://user-images.githubusercontent.com/41557212/54488388-71824800-485e-11e9-80bb-7f2c68e24e7d.PNG)
![GT14](https://user-images.githubusercontent.com/41557212/54488387-71824800-485e-11e9-9f2b-c9cc42a83a47.PNG)

**Comment by Guren1993** [comment]
I`m sorry, but using Large ZPM Assembler is impossible too. ZPM Control Core to Large Assembler need ZPM single block Assembler to craft it first
![Новый точечный рисунок (5)](https://user-images.githubusercontent.com/48643499/54489337-31ea4900-48bc-11e9-895f-6d45c8d768fd.png)

**Comment by 0lafe** [comment]
Control cores don't lock EU/t, you'd need to be able to make a ZPM energy hatch, which shouldn't be doable in LuV. Probably wanna change the naquadria to something else. Naq alloy sounds like a good idea.

**Comment by draknyte1** [comment]
Only an issue in 7.0.
Control core issue isn’t relevant for 7.1.

**Comment by Guren1993** [comment]
Imho recipe must be correct in any version. Anyway ZPM assembler is too early for craft before start first fusion reactor

**Comment by Dream-Master** [comment]
@Guren1993 what you suggest ?

**Comment by Guren1993** [comment]
I suggest replace Dense Naquadria Plate to Dense Naquadah Alloy Plate in Fusion Reactor MK1 recipe for balance technical availability

**Comment by Dream-Master** [comment]
@Guren1993 
thats what i doing
GT_OreDictUnificator.get(OrePrefixes.plateDense, Materials.NaquadahAlloy, 4L),

**Comment by Guren1993** [comment]
all right, thanks for yor work
