### ISSUE TITLE
Obsidian dusts don't smelt in the smeltery

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4277]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
wanted to smelt obsidian dusts and obsidian ingots in a Tinker smeltery
#
#### What happend instead? (Attach screenshots if needed)
only the ingot were processed:
![2019-03-17_15 04 01](https://user-images.githubusercontent.com/12850933/54492354-1dab4980-48c6-11e9-8106-01ddc1361e66.png)

#
#### What do you suggest instead/what changes do you propose?
would be cool if we could have the ability to smelt them too

**Comment by Dream-Master** [comment]
I can add it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54590633-d25d7c00-4a28-11e9-9ed0-0a1d0cd44b55.png)
