### ISSUE TITLE
Add metabolic disease from diet

### ISSUE THREAD

**Issue by willis936** [GTNewHorizons/NewHorizons#4278]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
A private server.
#
#### What did you try to do, and what did you expect to happen?
Steve getting diabetes from carb heavy diets or heart disease from fat heavy diets.
#
#### What happend instead? (Attach screenshots if needed)
Steve does not feel any consequences of his over indulgent diet.
#
#### What do you suggest instead/what changes do you propose?
Adding metabolic diseases to spice of life driven by diet.  The diseases would add debuffs like slowness until death.  In extreme cases they may cause lowering of health or death.

**Comment by Bluebine** [comment]
👌

**Comment by Dream-Master** [comment]
If we want to add this we need help.

**Comment by willis936** [comment]
Is there a list of forked repos for this project?

**Comment by Methes** [comment]
There could be a lot done to the whole health system, not only based on nutrition, but also being bitten by zombies, falling and other stuff.
Problem is you're very limited in how to present these effects to the player. You can basically only lower your health or add one of already present debuffs that end up being only annoying without any enticing gameplay.
This isn't an RPG game so you'd first have to implement that to positively and negatively affect the player in a fun way.
