### ISSUE TITLE
Robot Arm crafting is only using Mainframe type circuits

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/NewHorizons#4279]
#### Which modpack version are you using?
2.0.7.0

Robot Arm crafting in the assembly line can only be made using mainframe type circuits.

![image](https://user-images.githubusercontent.com/30087707/54497473-5addfe80-48fb-11e9-97ed-1d72fe858c6f.png)
![image](https://user-images.githubusercontent.com/30087707/54497481-66c9c080-48fb-11e9-8cdd-88b84334f054.png)
![image](https://user-images.githubusercontent.com/30087707/54497490-79dc9080-48fb-11e9-9124-ffbd3ce8b3b2.png)

**Comment by 0lafe** [comment]
Not the only things, seems like oredic broke in the assline, or at least in NEI. All circuit or rubber using parts seem affected

**Comment by 0lafe** [comment]
@Technus

**Comment by Dream-Master** [comment]
@0lafe is this a nei issue or a recipe issue.

**Comment by Dream-Master** [comment]
We need here an fix that better worked as the fixes before.

**Comment by DietmarKracht** [comment]
Are the assembling line recipes implemented code wise or script wise?

**Comment by Dream-Master** [comment]
code wise

**Comment by DietmarKracht** [comment]
So i investigated this issue a bit. It seems like this issue is related to NEI only. i just crafted a luv robot arm on delta with other type of circuits than mainframes. if you scan the datastick in the data reader you can see that the recipes also accepts other circuit types.
