### ISSUE TITLE
TecTech Questline

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4281]
Here I wrote an entire quest that you people may use for future quests that inform the player of the Research Station recipes and whatnot.

These questlines should be opened and properly inform the player of the massive task they have ahead of themselves; telling them to prepare for a huge learning curve. This questline, in particular, begins right after the **Crystalprocessor Mainframe** quest in **Tier 7 - 32768 EU (LuV)** with a quest labeled as "TecTec Adventures", the questline shall allow for a new tab labeled as TecTec and list this very guide & quest with the following resource requirement:

Main: **The Beginning of the End Game** Quest
"Welcome to TecTec! The pinnacle of absolute high-tier machinery for all your end-tier needs. However, learning TecTec is incredibly confusing, so listen very carefully. First, you'll need to gather various casings for your machines that you'll need. High Power Casings, Computer Casings, and Computer Vents will do, though you'll require a large amount of them before proceeding onward."

The quest then requires the player to gather these resources:
64 High Power Casings, 96 Computer Casings, 96 Advanced Computer Casings, 64 Computer Heat Vents, 64 Optical Fiber Cable, and 1 Multiblock Machine Blueprint.

Main: **Quantum Computer** Quest
One of the more incredibly complicated machinery, this will serve as the main structure for your "Computation" generation for the giant Research Station. First, you'll need a few things, the Quantum Computer itself, a huge energy hatch several amps of UV or above, this is because as Computer Racks, that'll be explained later on down here, will continuously increase the demand of energy input for every new Computer Rack that you add on. The Multiblock also consumes a large amount of energy by itself. Another important factor is ONLY turn on the Quantum Computer once you have the desired recipes for the Research Station ready to avoid excess energy loss. In order for you to build this absolute monster, you'll need to place down the Quantum Computer at least 1 block above the surface/ground and use the Multiblock Machine Blueprint, this will give you a hefty amount of information and various ghost-like blocks that'll show where casings and or hatches should go.

_Computation_:
Computation is generated every second and is based on the tier of your circuit. There are, however, differences in between how much computation is generated, even with the same exact tier. For instance, you could use a Master Quantum Computer (Quantum Circuit Series / LuV) or a Wetwareprocessor (Wetware Circuit Series / LuV) which will give you more Computation even though they are of the same tier. If you wish to find out exactly how much Computation a circuit gives; place down a Computer Rack, put a circuit inside and scan it. It will include the following information
Base computation: <numbers based on circuits>
After overclocking: <numbers, same as above unless you specially overclock it>
Heat Accumulated: <numbers, based on circuits and heat vents, keep a watchful eye on this part as it's extremely important>

_Computer Racks_:
The main component within the multiblock to generate Computation. In order to achieve this, you will need to input some circuits and heat vents; Advanced Heat Vents work best. It is critical that you use Heat Vents to prevent the heat from reaching a catastrophic point, 55 percent or above should be avoided for safety reasons. Technically, you could achieve "55 percent" in your Computer Racks, but in reality, they could around 4000-4999 heat. In order to precisely find out how much heat, you'll need a **Parametrizer**, which will be explained later. Now that you've understood one of the more basic concepts and safety of handling within the Computer Racks (scan the Racks before you run the Quantum Computer!), what are the more optimal setups for your Quantum Computer? Do keep in mind that even a 128 min Computation / Sec setup can complete practically 3/4th's of the recipes within the Research Station. In this case, a 4 Computer Rack setup with **1 Advanced Heat Vent** and **3 Wetwareprocessors** (LuV) will generate 72 Computation every second; leading up to a maximum of 288 Computation every second at just 5 amps of UV (524,288 EU/t) with only 4 Computer Racks required. This is a rather minimal setup compared to some of the more complicated setups.
And most importantly: DO NOT WRENCH THE COMPUTERRACKS IF THEY HAVE HEAT IN THEM. Scan them before anything else! Otherwise, you're going to get an explosion.

_Uncertainty Resolver_
Much like a puzzle-solving simulation, it is rather complicated to explain how to solve it, but it's often best just to retrace or undo certain actions and hope for the best. Sometimes, the Schrödinger Status will require some puzzle solving again after a period of time. This is random and incredibly frustration especially during operations being done between the Research Station and Quantum Computer(s), so it is important to constantly check the Uncertainty Resolver before you start operations on your Computer.

Now that you understand some of this, it is time to build the Computer! You'll need to gather quite a lot of resources at first.

The quest then requires the player to gather these resources:
1 Quantum Computer, 1 Uncertainty Resolver, 1 Optical Master Connector, 32 Optical Fiber Cables, 2 UV 4A Energy Hatch's, 12 Computer Heat Vents, 20 Advanced Computer Casings, and 22 Computer Casings.

Main: **Research Station** Quest
Now that you've started building up your precious Quantum Computer, how about the giant Research Station? Once again, using the Multiblock Machine Blueprint will tell you how to build this Multiblock. Once it is nearly assembled, place down an Energy Hatch, an Optical Slave Connector, and a Maintenance Hatch all on the back side. Once fully assembled, you can now begin operating recipes at any given time, so long as the Quantum Computer is also active. This Research Station requires you to put the desired item within the Object Holder, then a data stick in the Multiblock interface itself. Once the Computation is fully completed, the data stick that houses all the data of the completed item will be inside the Multiblock Interface. Still confused? Good, that's the spirit of learning! Always make sure to test these things in Single Player if you wish to find exact measurements and such. Don't forget to ALWAYS COLOR THE OPTICAL HATCHES AND FIBERS!

The quest then requires the player to gather these resources:
1 Research Station, 1 UV 4A Energy Hatch, 1 Optical Slave Connector, 1 Object Holder, 58 Computer Casings, 23 Advanced Computer Casings, and 14 Computer Heat Vents.

I hope this helps explain things and is added to the questline. If there's information that is wrong or otherwise not easy to understand, please make suggestions!

**Comment by richardhendricks** [comment]
Give credit to Piky/Scripted for the quests or quest tab

**Comment by richardhendricks** [comment]
- Piky shed blood over these quests for you.  Now you will shed blood for us!

**Comment by richardhendricks** [comment]
The quest can begin right after the Crystal Processor quest with a following quest named "An Age of Tech" that features a TecTec item of sorts. This quest then describes "Hello there. I've been keeping a watchful eye on your technological advance, it's time to see the dreams of a technological future! You shall be introduced to a whole new complicated series of machinery and I shall guide you through. Be wary though, as these machines will test your energy limits to the extreme."

![image](https://user-images.githubusercontent.com/1214811/54505459-e3fa3300-4905-11e9-85df-49adca39635a.png)

**Comment by DietmarKracht** [comment]
Now as many things are gated behind TecTec how do we generate that much power needed. Currently i see two options: solars and fusion. Both are limited to several UV amps but some TecTec research uses UHV+ voltage and also multiple amps

**Comment by richardhendricks** [comment]
@draknyte1 How much power does your solar tower produce? Could it hit UHV+?

**Comment by draknyte1** [comment]
0 eu/t.
No.

**Comment by 0lafe** [comment]
>Now as many things are gated behind TecTec how do we generate that much power needed. Currently i see two options: solars and fusion. Both are limited to several UV amps but some TecTec research uses UHV+ voltage and also multiple amps

I made solid UIV power with fusion before mk4s and infinity rotors, it's more than doable. 4 mk4 reactors, some ++ multis for fuel production (10 maybe? not a lot), and like ~30 infinity turbines. Using niobium plasma also gives a boost over He so you can probably get like maybe even close to 1A UMV with a similar sized setup. Also you don't have to run these recipes close to all the time, so buffering power for them is an option. Solars can compete, they got a little nerf but if you're T+1 from the solar it should still be kinda easyish to make them. Considering they're creative gens, I feel like there should be more infinity stuff associated with them, but that's for another time I guess. There's also naq gens, which in singleblock form exist until UV, and while they do use a bit of naquadria, if you're just needing a few A, it should be doable. ++ multiblock naq gen is maybe a thing soon, and hopefully covers some of the higher tiers while using more interesting versions of Nq for fuel. 

>@draknyte1 How much power does your solar tower produce? Could it hit UHV+?

considering if it's the penis tower it runs on steam, that would be a PITA to deal with. The mega steam turbine helps, but only counts as 16 turbines iirc which is still below what this is asking for.

**Comment by richardhendricks** [comment]
I need some rewards appropriate for this tier. @ScriptedPiky ?

**Comment by richardhendricks** [comment]
Also, will there be more quests? What do players actually do once they make the machines?

**Comment by richardhendricks** [comment]
@Technus

**Comment by DietmarKracht** [comment]
For the Quantum Computer the quest is missing a parametrizer. it wont run without one alothough neither me nor tec really know how it works :D

**Comment by ScriptedPiky** [comment]
Parametrizer isn't required technically, but it is nice and I know somewhat about that particular machine

**Comment by richardhendricks** [comment]
OK for know ticket is done, any future change requests/new quests create a new ticket.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57498799-f0b25c00-72a2-11e9-912e-4907f03283fb.png)
![image](https://user-images.githubusercontent.com/1214811/57498801-f445e300-72a2-11e9-9b3c-fa798d051156.png)
![image](https://user-images.githubusercontent.com/1214811/57498809-f8720080-72a2-11e9-90cf-2c00585db585.png)
