### ISSUE TITLE
Containment Casing and Field Generator(Tier VI) scan recipe conflict

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4282]
#### Which modpack version are you using?
2.0.6.8 and 2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Single and Private Server
#
#### What did you try to do, and what did you expect to happen?
I tried to get scan data of Field Generator(Tier VI).
#
#### What happend instead? (Attach screenshots if needed)
I got scan data of Containment Casing instead of Field Generator(Tier VI).
On NEI, Containment Casing and Field Generator (Tier VI) are required to scan Field Generator (Tier V).
![2019-03-18_16 30 15](https://user-images.githubusercontent.com/40425798/54513940-21a99b00-499c-11e9-8033-af89d9de0324.png)
![2019-03-18_16 30 17](https://user-images.githubusercontent.com/40425798/54513941-21a99b00-499c-11e9-9ec6-7bf3d96f43c9.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by draknyte1** [comment]
6.8/7.0 use same version of GT++.
7.1 - fixed.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54589270-81985400-4a25-11e9-87a3-7b1cc0e3fc96.png)
![image](https://user-images.githubusercontent.com/2970688/54589278-865d0800-4a25-11e9-896e-aa81eae6169a.png)
