### ISSUE TITLE
Magic metal berry crash.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4283]
ver. 0.6.8

When forestry farm tries to harvest magic metal berry it crashes client.

Crashlogs below, all similiar.

[crash-2019-03-18_13.40.56-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2978608/crash-2019-03-18_13.40.56-server.txt)
[crash-2019-03-18_14.28.28-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2978609/crash-2019-03-18_14.28.28-server.txt)
[crash-2019-03-18_15.14.21-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2978610/crash-2019-03-18_15.14.21-server.txt)

**Comment by Dream-Master** [comment]
@bedrill64 magic metal berries are from which mod?

**Comment by bedrill64** [comment]
Its bart's crop afaik.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bedrill64** [comment]
Can I get a link to version with fix? Can't get into the world atm and really do not wanna MCEdit this world.

**Comment by bedrill64** [comment]
So, after testing, metal oreberry was crashing because it actually can grow without block below it, due to no block, no drop was recognized and it crashed instance. 

Also another thing, as its crops++ crop it recognizes block only when its 2 blocks below crop, not like most of crops that check for required block 4 blocks down.
