### ISSUE TITLE
Future semiconductor/circuit materials

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4284]
If we are looking for futuristic materials for circuits etc, Silicon Carbide is a good option.  It allows for very high temperature operations at 800*C+ 

https://ieeexplore.ieee.org/document/7956136

We could make up some fancy top tier recipes for it etc.

Also, another material could be Magnetic Random Access Memory.  This can work at high temperatures >250C and has very good speed and durability.

Just need to greg them up!

**Comment by draknyte1** [comment]
Silicon Carbide Already exists?
