### ISSUE TITLE
Held items are invisible in third person

### ISSUE THREAD

**Issue by Vixor999** [GTNewHorizons/NewHorizons#4287]
#### Which modpack version are you using?
2.0.7.0 (Updated from 2.0.6.2)
#

#### If in multiplayer; On which server does this happen? 
Private server.
#

#### What did you try to do, and what did you expect to happen?
View my held items in third person, or view another players held items.
#

#### What happend instead? (Attach screenshots if needed)
None of the players on my server are able to see their own held items in third person. This is also true for attempting to view items held by other players, even if looking at a player in first person. Personal held items are visible in first person or when thrown on the ground, but otherwise appear invisible. This appears to be a purely visual bug.

![2019-03-18_21 25 19](https://user-images.githubusercontent.com/32398957/54576003-706b2b00-49c4-11e9-8b0a-ccca5b8bb8c4.png)

In this screenshot I am holding a sapling, but it appears invisible while in third person. It also appears invisible if I get another player to hold it.
#

#### What do you suggest instead/what changes do you propose?
Uncertain of what's wrong here, other than it started when we updated the pack version to 2.0.7.0 

Never seen the issue before that.

**Comment by boubou19** [comment]
can confirm that this happens on ru live servers as well

**Comment by Dream-Master** [comment]
Are you adding or deleting optifine @Vixor999 @boubou19 ?
are you using newer optifine than d6 with fastcraft 1.25 ?

**Comment by Vixor999** [comment]
No, I haven't added optifine, or any other graphical mods. The issue apparently happens in single player, too, if that helps. 

We've also tried reinstalling, and that didn't seem to fix the issue, so I feel like it must be a bug with the new update, especially if there are people experiencing it on the official servers as well. The issue didn't exist when we were on 2.0.6.2.

**Comment by boubou19** [comment]
from my side i don't have optifine and i use fastcraft 1.23

**Comment by Dream-Master** [comment]
yes i have the same issue. Not sure which mod change this.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54587323-14ce8b00-4a20-11e9-9f3d-c93ae595ef84.png)

**Comment by Impos913** [comment]
Also the copter pack is not rendered.

**Comment by barsikus007** [comment]
This bug exist from 2.0.6.8
Here is proof:
https://youtu.be/DPUkIr64Tb4?t=1308

**Comment by barsikus007** [comment]
This is mods, which can cause bug (tested be deleting mods and checking in single)
![image](https://user-images.githubusercontent.com/37113583/56461586-0cba9000-63be-11e9-9def-c358422cf61a.png)

**Comment by bartimaeusnek** [comment]
@barsikus007 its unlikely that its bartworks, since it wasnt in 2.0.6.8 when this bug appeared, also i dont do render stuff with the player..

**Comment by Dream-Master** [comment]
@barsikus007 
Core mod not add new rendere so far ik. Cant speak for Tec Tech @Technus or Gt++ @draknyte1

**Comment by SanyokJons** [comment]
@Dream-Master 
This problem is created by the GT ++ mode. Checked by removing all mods gradually.

**Comment by Dream-Master** [comment]
@draknyte1 any idea on this?

**Comment by SanyokJons** [comment]
@Dream-Master 
I tried to install the latest version of GT ++ from github, I do not observe this problem.

**Comment by Dream-Master** [comment]
so 337 works ?
@SanyokJons

**Comment by SanyokJons** [comment]
Sorry, did not pay attention to the year in their assemblies git. apparently found the wrong resource and rolled back to the older version of rm ++

**Comment by Dream-Master** [comment]
Try the lastest one https://circleci.com/gh/alkcorp/GTplusplus @SanyokJons

**Comment by Dream-Master** [comment]
Not working with lastest GT++

**Comment by barsikus007** [comment]
So we need to wait for update of modpack for fix?

**Comment by Dream-Master** [comment]
@barsikus007 ask him if you want not sure how to fix it.

**Comment by draknyte1** [comment]
AFAIK, not my issue because I don’t fuck with rendering. 
Doesn’t occur in any dev situations. 

Unless someone can prove it’s my mod, there’s nothing I can do to fix it.

**Comment by SanyokJons** [comment]
Seriously, even when you put another version of GT ++, this problem is not observed.

**Comment by draknyte1** [comment]
> Seriously, even when you put another version of GT ++, this problem is not observed.

I assume this means new versions aren’t a problem. Otherwise again, unless you can prove its GT++, I stand by the fact I don’t touch rendering in any way to cause this issue.

**Comment by repo-alt** [comment]
Is that not proof enough that when GT++ is removed then the bug disappears? What other proof can there be w/o actually debugging?

**Comment by bartimaeusnek** [comment]
moved to -> https://github.com/alkcorp/GTplusplus/issues/489

**Comment by bartimaeusnek** [comment]
as Workaround:
Disable Capes in GT++ config.
