### ISSUE TITLE
ZPM+ lootbag need items

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4288]
#### Which modpack version are you using?
2.0.5.1-2.0.7.x
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
i open ZPM-UV lootbag
#
#### What happend instead? (Attach screenshots if needed)
i got a diamond.
#
#### What do you suggest instead/what changes do you propose?
ZPM+ loot bag should have a good reward like UV circuit or UHV superconductor ....etc we should open a discussion and make it balance.

**Comment by Namikon** [comment]
Duplicate of #4268

**Comment by Dream-Master** [comment]
not a real duplicate. zpm and uv bags need items

**Comment by Namikon** [comment]
But it's the same topic; That LootBags are merged with Trash and appear to be unfair. That affects every Lootbag tier; Except Legendary

**Comment by BlackFlameTNT** [comment]
Zpm+ loot bag give only 1 diamond there is nothing else

**Comment by Dream-Master** [comment]
no zpm lootbags are add to quests but have no items or only the diamond

**Comment by BlackFlameTNT** [comment]
Fusion quest line give you zpm+ lootbag and the only item they give is a single diamond even if it is fortunate III.

**Comment by Namikon** [comment]
Ok, seems I have to rename the Diamond to "The Dev forgot to add Items to me"
