### ISSUE TITLE
Increase small titanium ores, change spawn range

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4289]
Since we are removing all pure titanium ore on the moon, it be a good idea to at least give some back on the T2+ planets. Recommend changing spawn range to 10-180, and increasing number spawned from 8->32.  Because the spawn range is so wide and the small ores do not retry if unable to place, the number of ores isn't going to be really that high.

**Comment by 0lafe** [comment]
Adding small ores to the T2 rocket kinda ruins the point of moving Ti ore off the moon. T3 planets make more sense for this

**Comment by Jocroy** [comment]
How does small amounts of small ores for T2 ruin removing real ores in veins from T1?

**Comment by 0lafe** [comment]
The T2 is still an EV rocket, and kind of early in the tier (only need EV electrolyzer and assembler right?). You don't really need to process much rutile at all to be able to use pure Ti. If the point of moving pure Ti is to force rutile for EV, then put pure Ti in IV. The rocket is early IV as much as T2 is early EV. Such a small time using rutile isn't really worth doing an auto setup for it or really trying to get much done with it.

**Comment by Bluebine** [comment]
I'd say leave the small ores as they are, and add pure titanium ore to T3 rocket. That's IV, so you can't get pure titanium in EV. Problem solved.

**Comment by Dream-Master** [comment]
No small ores are enough

**Comment by richardhendricks** [comment]
Small ores are definitely enough with the fortune bonuses and massive area larger tier ore drills can do. A T2 drill can fill a compressed chest in ~2 hours, with about 20 Y height.

**Comment by richardhendricks** [comment]
@0lafe Please stop assuming everyone is trying to speedrun the tiers. Plenty of players spread horizontal through the tiers and do things at that tier. Like, for example, building the large combustion engine or gas turbines or nukes. There is plenty to do at EV and making a rocket to rush is not going to be the first thing on everyone's mind.
