### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by leftyde** [GTNewHorizons/NewHorizons#429]
Mod 1:
http://minecraft.curseforge.com/projects/openmodularturrets
Rezepte könnte ich anpassen falls die Mod erwünscht ist.
Zweck: Base defense mit Technologie, vieles anpassbar von den Werten her.

Mod 2:
http://minecraft.curseforge.com/projects/neat
Eigentlich ganz cool, besser als diese Waila kacke XD

Mod 3:
http://minecraft.curseforge.com/projects/survival-tweaks
Player Collision, Bed Tweaks, Effect Tweaks? :D

Ansonsten ist die Modliste echt Top! :P 
Für andere Sachen muss ich erstmal mehr spielen.^^

**Comment by Dream-Master** [comment]
Mod 1: we discussed already this but the majority don't wnet this mod.
Maybe we can mak a vote again because i think this mod is real need for protect the Base from Infernal Mobs.

Mod 2: I see this mod too. Have this all the features Waila have? If this is better than Waila why not.

Mod 3: I dont know this mod so make a voting here too.

**Comment by Dream-Master** [comment]
http://forum.gtnewhorizons.com/showthread.php?tid=69

**Comment by Drobac** [comment]
Mod 1 Gets a vote + from me
Mod 2:Dont know much about it,  but might be useful. Especially with hardcore darkness
Mod 3: Has some cool aspects, can the effects be turned on/off via configs. Does it have dependencies?

**Comment by leftyde** [comment]
I mean Net is client side, so atm I just drop it into my mods folder with an batchfile and delete invtweaks and xcopy an changed config file for holoinventory :D

Survival Tweaks is fully configurable and openmodularturrets are awesome :I

**Comment by leftyde** [comment]
What about http://minecraft.curseforge.com/projects/stacksonstacks?gameCategorySlug=mc-mods&projectID=235753 ? :D Cool mod too :PPPP I know we have a lot of mods, but those mods have unique functions so :>

**Comment by Dream-Master** [comment]
So far i can see we can Open Modular Turrets to the next Update. Neat not replace full Wila so we have to test it and survival Tweaks too.

**Comment by leftyde** [comment]
as replacement I mean the Health from Mobs, not the whole waila :D

**Comment by Dream-Master** [comment]
Ok we add OMT in Update 1.0.7.5.
If someone want heat you can install it by your self it is a only client side mod.
