### ISSUE TITLE
Void jar infusion doesn't work.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4291]
0.6.8

As in title, I can't launch this infusion, everything placed properly, should work. Screens below.

![2019-03-20_17 55 49](https://user-images.githubusercontent.com/9555787/54704510-28224900-4b3b-11e9-9984-8a794a92d995.png)
![2019-03-20_17 56 19](https://user-images.githubusercontent.com/9555787/54704511-28224900-4b3b-11e9-9a1b-985f54d18d7d.png)

**Comment by Dream-Master** [comment]
will check

**Comment by bedrill64** [comment]
False alarm, I used wrong plate. Sorry for bothering. Its endereye plate not enderpearl plate.
