### ISSUE TITLE
Field Generator Tier 2,3,4 are bugged in assembler

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4292]
#### Which modpack version are you using?
2.0.7.0

The assembler recipes takes in 1 instead of 4 circuits

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea why?

**Comment by Dream-Master** [comment]
not working

**Comment by bartimaeusnek** [comment]
should be fixed with the circuit ductape update from 2.0.7.5
