### ISSUE TITLE
HI Amp Transformer wrong recipes

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4296]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
GTNH Delta
#
![Screenshot 2019-03-21 18 57 17](https://user-images.githubusercontent.com/11991148/54774263-9c2c2200-4c0b-11e9-873f-dcfff548fe60.png)
#
#### What do you suggest instead/what changes do you propose?
HI Amp Tranformer have wrong recipe for all transformers from LUV HI Amp and higher tiers. Before 2.0.7.0 they all used different coils. Now they use mainframes one tier below. 
Either oredict the mainframes or change back to the coils

**Comment by Dream-Master** [comment]
Or maybe alk add some recipes via gt++

**Comment by draknyte1** [comment]
I haven’t touched them.

**Comment by Dream-Master** [comment]
ok I will check the recipes
