### ISSUE TITLE
Alterration of the quest The quest: Upgrade of the upgrade of the...

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/NewHorizons#4297]
#### Which modpack version are you using?
Version 2.0.7.0 08.03.2019
#

#### What did you try to do, and what did you expect to happen?

The quest: Upgrade of the upgrade of the...
You are told in the quest that it will unlock redstone and obsidian
When getting this steel tool parts people run off to mine obsidian but are unable to, as steel upgrade only gives redstone level.
But I fell for this when i upgraded my tools and i see others in chat that have had or are having the same issue.
The issue here is if you forget as i did or dont know that you have to use your brand new steel pickaxe to level it up.

#
#### What do you suggest instead/what changes do you propose?

There are two ways to inform the player about this
1-  The simple solution, add text in the quest that explains that you have to use your tool to level it up.

2 - or in the spirit of the mod-pack, add a quest after the steel tools quest and before alumite quest. where you tell a player to go clear a vein or something, bring back 64 blocks of copper/iron/tin ore or something. this will force them to level their tools.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57200529-e0247d80-6f52-11e9-9218-34f9f6e52742.png)
