### ISSUE TITLE
"New Quest" glitch

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4298]
This seems similar to #909 .
V2.0.7.0
Occasionally, on SSP login, random amounts of quests are replaced by "New Quest" - empty quests -  and automatically completed. The fix is to run /bq_admin load default, and enter Edit Mode to manually reset completed quests (or re-accept reward from already completed quests to void). This is a terrific inconvenience, as it's hard to find which quests were prematurely (re)completed amidst legitimately completed and available ones.

**Comment by richardhendricks** [comment]
That really sounds like file corruption.  Also, with your complaints earlier about chunk rollbacks, maybe you need to run a SMART test on your drive? IDK.  Otherwise, try and copy the BQ JSON files before each start, see if they are corrupted from the last quit.

**Comment by BlackFlameTNT** [comment]
That happens to me and my brother like ... 4 time in our run so far and for us we have the tape unlocked and it’s really difficult to know what have we done.

**Comment by richardhendricks** [comment]
Sorry, ignore commit above.

**Comment by richardhendricks** [comment]
Okay, just had the issue appear for me too while working on new quests.  I'm starting to think we may be at the limit of what Better Questing can do reliably.  Will need to look at upgrading to a newer version I think for better packet handling.

**Comment by Dream-Master** [comment]
I chat with Funwayguy the dev of the mod and we can use backported version 3. The only thing we have to add is Nei support. When this is done i will change to BQ3 @richardhendricks

**Comment by richardhendricks** [comment]
I found a couple of extra New Quests turds in the BQ file.  I removed them, should be resolved in the next release.  Will create separate ticket for BQ3.
