### ISSUE TITLE
Energy core [ULV] cannot be autocrafted

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#4301]
#### Which modpack version are you using?
2.0.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Set up autocrafting of control cores
#
#### What happend instead? (Attach screenshots if needed)
ULV energy core core (used to craft LV core, used to craft control core) cannot be autocrafted with microprocessors. Manual crafting works fine.
Illustrated setup uses chest and conveyor to exclude AE bugs:
![image](https://user-images.githubusercontent.com/23512002/54795842-be02c480-4c5e-11e9-8e50-f92834a2c760.png)
![image](https://user-images.githubusercontent.com/23512002/54795857-ca871d00-4c5e-11e9-87d5-4d4db7eefdf2.png)

If I manually place the microprocessors in the assembler it will craft the core.
#

**Comment by Dream-Master** [comment]
circuit oredict sucks. Idk what to do. We need to fix that circuit oredict mess.

**Comment by Dream-Master** [comment]
And cores are changed in upcoming versions

**Comment by Dr4cos** [comment]
If you place 1 microprocessors in the machine it will work till there is a fix for it

**Comment by DietmarKracht** [comment]
That has nothing to do with the recipes itself. it is an issue about using circuits in buffers rather than putting them directly in a machine
