### ISSUE TITLE
small oilsand is useless

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4303]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
smal oilsand ore from oilsand veins cant be turnt in to oil

**Comment by Dream-Master** [comment]
ok what they drop?

**Comment by ScriptedPiky** [comment]
It drops this when fully processing the crushed ore. However, Oilsands Dust, the item that is the problem, doesn't have a recipe to be processed into more oil
![2019-03-23_00 49 13](https://user-images.githubusercontent.com/41557212/54863409-8864e680-4d05-11e9-8ef8-08f479fe8fe6.png)

**Comment by DietmarKracht** [comment]
Maybe add a Mixer Recipe to produce oil from the dust.

**Comment by Dream-Master** [comment]
what you get out of the dust atm.

**Comment by botn365** [comment]
noting

**Comment by Dream-Master** [comment]
ok will add additional recipe

**Comment by bartimaeusnek** [comment]
how about a centrifuge recipe, 1 dust -> 500L Heavy Oil + 33% chance of Sand, to be in line with 1 Ore -> 2000L Heavy Oil?

**Comment by Dream-Master** [comment]
isn't it not much oil? Maybe get normal oil 1000L.

**Comment by richardhendricks** [comment]
Oil sands should give heavy oil, just like the ore.  1000L is OK, since the ore itself gives 2000L, this way you don't get extra oil.  OS is already pretty good heavy oil source.
