### ISSUE TITLE
qeust does not detect gt alumimte

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4304]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
complete alumite quest using the cheaper recipy
#
#### What happend instead? (Attach screenshots if needed)
the quest does only detect tinker alumite but not the gt alumunite
#

**Comment by Dream-Master** [comment]
because the designed for tico alumite

**Comment by botn365** [comment]
the only difrents between the two is that one comes from smelting dust and the other one from a smeltery so if you make the gt one you have to smelth them in the smeltery then make them in ingots again to comlete the quest and if you then want to do somting with it you have to smelt it again 
the first time is only there for comleting the quest

**Comment by Dream-Master** [comment]
Alumite the gt tools need to be disabled I only allow ingot and dust support.

**Comment by botn365** [comment]
but you cant complete the the 16 alumite ingot quest with gt alumite ingots only ticon ingots when they are the basically the same ting

**Comment by Dream-Master** [comment]
moron add alumite to gt but it was never planed add two different type of materials only compat
