### ISSUE TITLE
Impossible to smelt quantium for T5 rocket/Rebalance heavy duty plates

### ISSUE THREAD

**Issue by DisasterMoo** [GTNewHorizons/NewHorizons#4305]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Fully toasted
#
#### What did you try to do, and what did you expect to happen?
To smelt quantium the required temp is 12000K needing electrum flux coils(or awk. draconium in newer versions i suppose). To get to that, first we need to get trinium for naquadah coils which can't be obtained without a T5 rocket(deep iron). Also ZPM voltage seems unfair. Comparing to T6 heavy duty plates, oriharukon is too easy and mysterious crystals still not that hard.
#
#### What happend instead? (Attach screenshots if needed)
![print](https://user-images.githubusercontent.com/46634059/54873714-78a7d980-4dbb-11e9-9237-988114dc0c5a.png)

#
#### What do you suggest instead/what changes do you propose?
Change T5, T6 and T7 heavy duty plates materials to be consistent.
T5(Quantium) should smelt at 5400K(HSS-G coils) at IV voltage
T6(Oriharukon) should smelt at 7200K(Naquadah coils) at LuV voltage(keep in mind it is needed for crafting IV kinetic generators)
T7(Mysterious Crystals) should smelt at 9000K(Naq. Alloy coils) at ZPM voltage
T8(Black Plutonium) should smelt at 12000K(Flux/Awk. Draconium in 2.0.7.0?) at UV voltage

For me, this way it looks more reasonable. Also time is a factor here. For example, 720sec at 120eu/t with 7200K to smelt mysterious crystal(in 2.0.6.2) is 22,5 sec in ZPM with same coil. Far too easy compared to the 375sec at ZPM with 12000K for quantium ;)

**Comment by 0lafe** [comment]
Quantium got changed, plate parts in rockets could maybe do with a look, they're not really the best tier stuff, but idk, I'd rather change them then change the times of stuff with how these other materials are used. Upping MC to ZPM sounds good though, don't think you get it til zpm anyway, with the T5. I think there's a new cap for coils, awakened/flux got lowered from 12/15 to maxing at 12 I think with 1500k increments. 

If we wanna work in the space metals more we probably wanna look at their smelting times too. Personally I'm for just removing them and changing the ore mixes to something else, unless we can find something creative to do with them besides another simple ebf -> vac -> ingot

**Comment by Dream-Master** [comment]
12k is wrong maximum should be 10800k.

**Comment by 0lafe** [comment]
So I take that back, looks like quantium never got changed? Should be IV or LuV though, with the rocket being LuV. There are multi amp IV+ hatches now though, so like, technically ZPM multi recipes are IV
