### ISSUE TITLE
Quest "GT 6 styled Pipes" should not be mandatory

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#4309]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to progress through stone age to steam age.
I expected to progress straight from the bronze quest to the steam boiler quest.
#
#### What happend instead? (Attach screenshots if needed)
The "GT 6 styled Pipes" quest is not only a main quest, but MANDATORY to reach the steam boiler quest, for some reason.
![2019-03-24_18 23 24](https://user-images.githubusercontent.com/29802757/54886760-f0c8da80-4e61-11e9-94eb-47720438a8ee.png)

#
#### What do you suggest instead/what changes do you propose?
Make the quest a non-main quest, and make it not required for the steam boiler quest.

**Comment by richardhendricks** [comment]
Requirement removed.  I left it as a main quest because noobs need to read it.
