### ISSUE TITLE
RemoteIO: Remote Inventory

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#431]
Remote Inventory from the Remote IO mod has no crafting recipe. Is this intented?

**Comment by Dream-Master** [comment]
Please read the Tooltip and you know this Block not need a new recipes (Block link)

**Comment by Dream-Master** [comment]
![screenshot 2015-12-27 13 38 11](https://cloud.githubusercontent.com/assets/2970688/12010238/36ce30ce-ac9f-11e5-87bc-1b6a6c1aea8c.png)
![screenshot 2015-12-27 13 38 13](https://cloud.githubusercontent.com/assets/2970688/12010239/36d25294-ac9f-11e5-86dd-4f28e10fedd0.png)

**Comment by Dream-Master** [comment]
shift click the wireless transiver to bound it to you.

**Comment by Teteros** [comment]
Thanks for clarifying that. I was assuming you need the (Remote Inventory) block first, and then you bind it to yourself. You only need a remote interface and a transceiver then.

**Comment by Dream-Master** [comment]
yes
