### ISSUE TITLE
For My Town claims listing, list dimension of claim, also split claims by far group if possible

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4310]
@Namikon Since we have the code working for mytown, is this possible?

**Comment by bartimaeusnek** [comment]
also absolute X/Y values would be nice, chunk coords are fine, but its easier to see the normal ones (just multiply by 16)

**Comment by Namikon** [comment]
Absolute Coords and Dimension is possible; The far-claim group I'll have to check

**Comment by Namikon** [comment]
X/Z coords added in latest dev branch; Dimension ID is meant to be printed; but the .lang file is missing a placeholder.
However the claim list can be quite large; I'll have to rewrite that part to include a tooltip overlay containing x/z coordinates. WiP

**Comment by richardhendricks** [comment]
I don't think the tooltip overlay is required, the full list can be retrieved from the output log file.  Maybe add a line after the claim list is printed 

"For long claim lists, look at blahblah.log"

**Comment by Namikon** [comment]
Hm.. That's a very "functional" solution. But yeah; I might do exactly that; For now.
I was thinking about a "Click to Teleport" OnClick handler in case the command sender is in creative mode.

**Comment by richardhendricks** [comment]
Official servers have database access to claims now.
