### ISSUE TITLE
Andisite Cutting into nothing.

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4311]
2.0.7.0

Andisite has a cutting machine recipe that outputs nothing.

![2019-03-25_19 57 50](https://user-images.githubusercontent.com/20565115/54963899-761ebe80-4f38-11e9-9807-a10d43cc1339.png)

**Comment by Dream-Master** [comment]
maybe because no plates available.

**Comment by boubou19** [comment]
same for the 3 recipes involving the pam's salt block in a cutting machine:
![image](https://user-images.githubusercontent.com/12850933/55277617-a1bbf300-5302-11e9-9244-1ba3025eee31.png)
