### ISSUE TITLE
Avaritia Achievements

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4312]
#### Which modpack version are you using?
2.0.5.1

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
I tried to flex on the n00bs on our server, but turns out you can't complete the first achievement making the crystal matrix ingots as GT makes them in the forming press.

#
#### What happend instead? (Attach screenshots if needed)
I couldn't flex on n00bs.

#
#### What do you suggest instead/what changes do you propose?
Give me achieves, let me throw items on the ground and get achieves.

**Comment by Dream-Master** [comment]
Maybe it is possible to change the archivement in code. But i need help with this.

**Comment by DietmarKracht** [comment]
There are many achievements that can't be reached due to the minetweaker recipes. The gregtech coils need to be handcrafted to be recognized for the achievments but they can only be crafted in assembler.
