### ISSUE TITLE
Quest for dealing with new assline recipes

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4314]
#### Which modpack version are you using?
2.0.7

#### What do you suggest instead/what changes do you propose?

This be for @richardhendricks 

When recipes in the assembly line change weird things happen to your data sticks, and this is a quest placed in the beginning of LuV (first quest? idk) that explains how to deal with this.

>When the pack updates, and changes an assembly line recipe, your old data sticks become useless. However it's more than that, you can't simply rescan an old UV motor for the new UHV data, you need a new UV motor. It's best to start with component parts in the lowest changed tier, then work your way up until you've rescanned up to your current tier. Yes, this sucks, we also wish there was another way. You can tell if your data stick is out of date by seeing if the nei recipe matches the one in the data viewer. Nei will always be right.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57504031-683eb600-72b8-11e9-87a9-d3bd6416194a.png)
