### ISSUE TITLE
ZPM core are uncraftable.

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4315]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Make HG-1223 to make ZPM core.
#
#### What happend instead? (Attach screenshots if needed)
The alloy furnace need ZPM core to make HG-1223
#
#### What do you suggest instead/what changes do you propose?
Make HG-1223 as LuV or remove the core systems.
You need HG-1223 to make ZPM core but you need ZPM core to make HG-1223

**Comment by DietmarKracht** [comment]
You don't need cores in the abs to run it. Use multiple energy hatches

**Comment by BlackFlameTNT** [comment]
Will it work as zpm?

**Comment by BlackFlameTNT** [comment]
And abs in 2.0.7.0 core is a must to be able to run it iirc.

**Comment by DietmarKracht** [comment]
Well I use abs on uv power without any core inserted into the module. Everything works fine

**Comment by Bluebine** [comment]
after .7.0 control cores are gonna be optional, not mandatory. once the next update drops, this won't be a problem.
