### ISSUE TITLE
Add quest for anchor sentinels

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4318]
For when you need to load a straight line of chunks, up to 25.

**Comment by DietmarKracht** [comment]
On the official Servers world anchors are disabled. so this would be related to SSP only

**Comment by richardhendricks** [comment]
Anchor sentinels work for passive and personal anchors as well.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57494738-50ebd280-7290-11e9-9a6a-3b9786f84666.png)
