### ISSUE TITLE
Add quest for saddle after tanned leather

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4319]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by richardhendricks** [comment]
uh nevermind, horses are buggy as f

**Comment by draknyte1** [comment]
They desynchronise like boats in SMP. Work fine in local SMP and SSP.

**Comment by richardhendricks** [comment]
okay, well we can have a quest but warn players on servers.

**Comment by draknyte1** [comment]
There’s some ASM fixes out there which fix both. Maybe be worth making a forum post or something with links to all of these QoL things. Totally optional but some folks may want them.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57200479-4230b300-6f52-11e9-94e1-961b3dee6557.png)
