### ISSUE TITLE
New Quest Potential in Tier 1 - Steam (Clay Quest)

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4320]
Right after the player completes the 'Extracting stuff' quest in **Tier 1 - Steam**, this new quest will show up as an optional quest stating the following:

**Mud is not useless!**

"You may have found plenty of mud piles around the wetlands and thought of them as mere annoyances when jumping in the water or for that armor. Waste not! With your new extractor, you can pull out the clay hidden in the mud!"

For reference:
![image](https://user-images.githubusercontent.com/41557212/55054563-95434c00-501d-11e9-88f6-ed02ff68b3a5.png)

This would be a good way to inform the player that, if they aren't already aware, will tell them that mud can be processed into clay via extracting

**Comment by septemberWaves** [comment]
This could be very helpful for players who struggle finding a stained clay biome (though there are several of these, they _can be_ difficult to locate if you are unlucky with world generation). I have played the modpack for several years and did not know of this mud ==> clay conversion until now; it seems that it may be easily missed.

**Comment by richardhendricks** [comment]
It's < yr old, it was added in .5.1 I think?  I asked Dream to add a bunch of the BoP crap blocks as recipes. Hardened sand gives double quartz dust etc.  Loamy dirt also gives a small amount of clay. Red sand gives a little iron, but needs MV.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57188239-f681f900-6ec0-11e9-8283-10d96e458513.png)
