### ISSUE TITLE
World Accelerator Power Usage

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4322]
Add to the tool tip for the world accelerator its power usage by mode, there is no real way to tell except putting it against a battery buffer and adding batteries till it works.

**Comment by Namikon** [comment]
Can't login at the moment; But the Tooltip of the Accelerator should tell you the Energy required already...
And it also should tell you if you use a scanner on it while placed. So I don't really get what exactly you are asking?

**Comment by Anarack** [comment]
It does not tell the amperage used. just the max accepted.
