### ISSUE TITLE
New MV tool quest

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4323]
We could use new quest for hammer/other tools, placed after MV Extruder, Vsteel parts + damascus steel rod as damascus has 5x durability multipler.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57186831-87e67080-6eab-11e9-9062-ac854b03e612.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57187289-c121df00-6eb1-11e9-9a81-f63525e06f16.png)
