### ISSUE TITLE
Change gates for Magic Energy Converters.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/NewHorizons#4324]
After hatch/voltage nerf Magic energy converters have unfair gates in my opinion. 

LV magic energy converter is obtainable with MV energy hatches (stainless required), MV one requires iridium plate -> EV energy hatches and IV EBF, HV one requires double osmium plate which makes it LuV voltage nad IV energy hatches.

I'd say change required plates for: iridium -> titanium(moon gate) and osmium ->tungsten, eventually iridium, but I'd say tungsten is fine, since HV solar doesn't require anything above IV voltage.

I'm aware noone uses them because they are off meta. But I want to try them and power my base of magic. At this moment I just can't, I'm not going to w8 for IV energy hatches to generate HV energy. For HV solars all I need is tungsten and sunnarium, lets change HV/IV/LuV gate to HV/EV/IV, I think it's better solution. 

All balance suggestions are welcome, I just want to tier it down where it should be.

**Comment by richardhendricks** [comment]
The problem is the lack of side effects when in use.  There is no pollution or flux from these right?

**Comment by damug** [comment]
Yeah, they appear to be magical green energy.

From the looks of it, if you get a boosted energized node they basically become fire and forget solars that work day and night.

**Comment by richardhendricks** [comment]
Yeah, then they definitely need similar tiering.

**Comment by bedrill64** [comment]
Any plans on this one?
