### ISSUE TITLE
gravichestplate

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4325]
#### Which modpack version are you using?
2.0.7.0
#

#### What did you try to do, and what did you expect to happen?
i was about to make gravitchestplate.
#
#### What happend instead? (Attach screenshots if needed)
for the update the gravotchestplate now move to UHV tire instead of ZPM.
#
#### What do you suggest instead/what changes do you propose?
the superconductor need to change recipes.

![image](https://user-images.githubusercontent.com/43831847/55277910-73481300-5316-11e9-96e2-07378a301a65.png)
![image](https://user-images.githubusercontent.com/43831847/55277934-aab6bf80-5316-11e9-9cfa-05a629b0530b.png)

UHV superconductor ask for awakened draconium and cosmic neutronium and infinity catalyst and americium for the dust base.

you can change gravichest plate recipe.

**Comment by Dream-Master** [comment]
To be honest Gravi chestplaye was never designed to be zpm maybe uv.

**Comment by BlackFlameTNT** [comment]
I will find it ok as UV but not as UHV you need rocket T8 to be able to make it .... and can you have fun in your vacation don’t worry that much about the pack ok =D

**Comment by 0lafe** [comment]
If we wanna do UV then UV SC in the thing seems ok. If zpm then zpm ones. Personally I feel like zpm is fine as it's arguably worse than DE which is UV.

**Comment by botn365** [comment]
wil anything be done about this or is this isue forgotten?

**Comment by Dream-Master** [comment]
it is an old issue but if it is open its not forgotten. Will check asap

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/69757060-43c70000-115c-11ea-8508-bcb2f148d94e.png)

LUV Superconductors

![image](https://user-images.githubusercontent.com/2970688/69757077-4d506800-115c-11ea-9667-87b9b51c99a6.png)

IV Superconductors
