### ISSUE TITLE
Terminus Jar Label

### ISSUE THREAD

**Issue by Rostisha** [GTNewHorizons/NewHorizons#4326]
#### Which modpack version are you using?
2.0.6.2
#
#### What did you try to do, and what did you expect to happen?
Craft Jar Label for Terminus aspect
#
#### What happend instead? (Attach screenshots if needed)
It didn't happend.. 
![image](https://user-images.githubusercontent.com/46450977/55290462-4100e900-53dc-11e9-86de-cd3f22af5301.png)

**Comment by Dream-Master** [comment]
Terminus is not a Thaumcraft aspect?
@Rostisha

**Comment by bartimaeusnek** [comment]
@Dream-Master its from avarita, also @Rostisha it should work with the witching gadgets labeling library

**Comment by bedrill64** [comment]
Works fine with WG apect library, confirmed.
![2019-03-31_18 21 17](https://user-images.githubusercontent.com/9555787/55291709-039f5a00-53e2-11e9-8359-be6d0c1b2399.png)

**Comment by Rostisha** [comment]
Ok, thanks a lot!
