### ISSUE TITLE
eeprom (lua bios) from quest is bugged

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4327]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
i placed correctly my computer, powered it. Expected it to boot properly
#
#### What happend instead? (Attach screenshots if needed)
it doesn't want to boot because the eeprom (lua bios) from the quest turned itself into a raw eeprom in the computer. I crafted the eeprom(lua bios) myself and that worked
#
#### What do you suggest instead/what changes do you propose?
maybe the item given in quest have wrong NBT

**Comment by richardhendricks** [comment]
I clicked a new version from NEI, I think we may have updated OC so it needs a new BIOS?  Please retest the quest with next release.
