### ISSUE TITLE
doge coins are uncraftable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4328]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Single player, Eta
#
#### What did you try to do, and what did you expect to happen?
wanted to make doge coin (to complete the quest 1777, opencomputer tab) so i was looking to make a Castin Form (Coinage Mold) to make the mold to make the coin.
#
#### What happend instead? (Attach screenshots if needed)
It's uncraftable, even with the recipe described in #1969.
#
#### What do you suggest instead/what changes do you propose?
please make it craftable or change the recipe of the doge coins

**Comment by Dream-Master** [comment]
I was sure doge coins can only be found ?

**Comment by boubou19** [comment]
well if that's the case then you should mention it in the quests i guess

**Comment by Bluebine** [comment]
They're craftable in singleplayer. I'm assuming that coins are meant to be uncraftable on servers, so people can't make chunkloader coins, but someone accidentally disabled doge coins too?
either way, they should probably be re-enabled

**Comment by boubou19** [comment]
that's weird because even in single player i wasn't able to see the castin form (coinage mold) recipe in NEI

**Comment by Dream-Master** [comment]
if it is only available on sp game then it must be a added recipe via script or some wired gt code works only in sp. Idk

**Comment by kekzdealer** [comment]
![image](https://user-images.githubusercontent.com/31353359/55361734-64a95980-54d8-11e9-8cc0-7e892c64abe8.png)
Works in 7.0 and I'm pretty sure the coin mold also existed in 5.1

**Comment by Bluebine** [comment]
![2019-04-01_17 48 13](https://user-images.githubusercontent.com/29802757/55361843-580c0d80-54a6-11e9-8b41-40c2405f7ab1.png)
Found the problem: THIS recipe, to make the casting form for the coinage mold, doesn't exist.
So thus, you've got no way to make the coin mould, and without it, you can't make dogecoins.
So that needs a recipe, at least for singleplayer.

**Comment by Dream-Master** [comment]
ok

**Comment by bartimaeusnek** [comment]
@Dream-Master we had the coinage mold enabled on delta and epsilon, maybe wrong files?

**Comment by Dream-Master** [comment]
will check
