### ISSUE TITLE
Withereed and Diareed have a max size that is shortest?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4329]
Not sure if this is intended, but the size 4 (mature) sizes of the diareed and withereed are both smallest of the 4 sizes.  Diareed it does turn blue so maybe this is intentional?

See diareed at 4/4, but smallest size.
![2019-04-01_22 30 55](https://user-images.githubusercontent.com/1214811/55374425-04adb580-54ce-11e9-9491-177bc173a6e5.png)

**Comment by bartimaeusnek** [comment]
it is intented.

**Comment by Dream-Master** [comment]
so can this be  closed ? @richardhendricks
