### ISSUE TITLE
recipe conflict in mixer

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4330]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
wanted to make purple illumar in a mixer which is filled with water
#
#### What happend instead? (Attach screenshots if needed)
got water mixed purple dye. 
![image](https://user-images.githubusercontent.com/12850933/55431439-d7760b80-5590-11e9-9d38-8fbe35ee1098.png)
![image](https://user-images.githubusercontent.com/12850933/55431490-f8d6f780-5590-11e9-9c68-4e08e6b0b0d0.png)

**Comment by BlackFlameTNT** [comment]
you need to remove the water to make the glowing stuff.

**Comment by boubou19** [comment]
i know but that's weird, generally the recipes use a circuit to avoid this kind of situation

**Comment by Dream-Master** [comment]
The recipe was made at this time minetweaker not support more slots. Now it's possible to change it via Minetweaker or change the gt recipes in code.

**Comment by DietmarKracht** [comment]
Almost all recipes using steel in the mixer have a conflict.if using AE automation you get a mess in your machines

**Comment by Dream-Master** [comment]
@DietmarKracht why it isnt reported on git ?

**Comment by DietmarKracht** [comment]
[https://github.com/alkcorp/GTplusplus/issues/452](url) is what i meant
