### ISSUE TITLE
Remove Regen from Jolt Blazes or Reduce Cooldown of Jolt Blazes's Teleport

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4331]
#### Which modpack version are you using?
2.0.7.1 (Test Build)

#### If in multiplayer; On which server does this happen? 
Zeta.

Blacklist Jolt Blazes from receiving the Regen or ensure that the Jolt Blaze has a CD when after teleporting. Why? Because having a Jolt Blaze teleport every single time that you hit it and regenerating its health back to full and always teleporting to your location if you move too far or hitting it, is not fun in the slightest. Jolt Blazes without the regen or massive health pool are generally fine, as, after a while, it will die. But having regen on that thing otherwise is a massive pain in the ass to remove and not fun at all

**Comment by FlandreS** [comment]
Additionally this causes mass numbers of high-tier regen Jolt's from gathering around mob farms, as they teleport out before killed.

Getting a Regen + Darkness + Vengance jolt with 300HP aggro'd is a near-guaranteed death.

**Comment by DoomSquirter** [comment]
I'd say leave them as is.

seriously.  If you have a problem with farming blazes and don't want to wall off your spawner area, then.... easy fix.

don't .... spawn.... and ..... farm... blazes.....

I resist farming blazes and witches for this exact reason.  Like thaum gating, this forces ppl to make a choice.  deal with the mobs peculiar attributes or ignore them entirely.  

also, the last time trimming more bad behavior from specialmobs/infernals basically made dream go all ragey and state he'd just remove the whole mod altogether, which I'm totally against as a completely different debate.

pls close this.
