### ISSUE TITLE
Stuck in Last Millenium

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4332]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Made Last Millenium Portal (needs 50+ warp), tried to get back, no permission for /home, can't get back tough the portal due to "You have too much warp to enter here". (it will normally send you to the spawn)

**Comment by Namikon** [comment]
Not a bug. Configure your town to allow a higher warp. The default setting is 30
