### ISSUE TITLE
Time Reduction in Superconductor Cooling

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4338]
2.0.7.1 (Dev/Zeta Build)

For reference: https://github.com/GTNewHorizons/NewHorizons/issues/4333 and https://github.com/GTNewHorizons/NewHorizons/issues/4335

We all know and look at the Superconductors and see the freezer recipe being hundreds of seconds long and wonder why. Especially since they get used up heavily later on in the higher tier recipes. I propose all the current Superconductor recipes and time reductions to be fairly balanced and not a heavy time-sink. However, they should not be easier to obtain as a result for them having near lossless at Superconductor Base and lossless at Superconductor form, yet, they shouldn't take extremely long either, especially for some of the more bigger recipes that require them later on in LuV+ (Fusion coils). Suggestions are very much welcomed. **If new proposed recipes are suggested, I can adjust the time values to reflect the new changes.**

The current Superconductor recipes for instance:
![image](https://user-images.githubusercontent.com/41557212/55609138-d54cb200-5734-11e9-8bd1-83bd98db35cc.png)
Proposed change for MV Superconductor: Reduce the time from 225 seconds, down to 65 seconds. 

![image](https://user-images.githubusercontent.com/41557212/55609982-ded71980-5736-11e9-97d2-c86c0670b223.png)
Proposed change for HV Superconductor: Reduce time from 225 seconds, down to 85 seconds.

![image](https://user-images.githubusercontent.com/41557212/55610249-658bf680-5737-11e9-8c11-3160a3be626f.png)
Proposed change for EV Superconductor: Reduce time from 300 seconds, down to 100 seconds.

![image](https://user-images.githubusercontent.com/41557212/55610393-ab48bf00-5737-11e9-9e9f-79bb0d05414d.png)
Proposed change for IV Superconductor: Reduce time from 300 seconds, down to 125 seconds.

![image](https://user-images.githubusercontent.com/41557212/55610951-e992ae00-5738-11e9-9c53-706c4dd1615a.png)
Proposed change for LuV Superconductor: Reduce time from 450 seconds, down to 160 seconds.

![image](https://user-images.githubusercontent.com/41557212/55611070-4726fa80-5739-11e9-8f40-431fe1c3ee73.png)
Proposed change for ZPM Superconductor: Reduce time from 450 seconds, down to 200 seconds.

![image](https://user-images.githubusercontent.com/41557212/55611732-3e372880-573b-11e9-96b2-a497b642a687.png)
Proposed change for UV Superconductor: Reduce time from 450 seconds, down to 250 seconds.

![image](https://user-images.githubusercontent.com/41557212/55611779-632b9b80-573b-11e9-9624-e2e7c7175a26.png)
Proposed change for UHV Superconductor: Reduce time from 450 seconds, down to 325 seconds.

**Comment by Anarack** [comment]
Fusion in terms of LuV Blast furnaces and IV Vac freezers
 the vac freezers are faster than ebf's at this point so making them LuV would be pointless

1xLuV BLAST/IV FREEZER 629 hours  1.25 AMP LUV
 2xLuV BLAST/IV FREEZER 314.5 hours  2.5 AMP LUV
 3xLuV BLAST/IV FREEZER 209 hours    3.75 AMP LUV
 4xLuV BLAST/IV FREEZER 157 hours    5 AMPS LUV
 8xLuV BLAST?UV FREEZER 78.625 hours 10 AMP LUV

Heres my napkin math for fusion costs https://pastebin.com/DCamtmjN

**Comment by 0lafe** [comment]
Times and stuff are calculated with mega vac/ebf. They're not really tiered, their stuff is all craftable, and most of it is fairly cheap. The glass is kinda painful but it's not unreasonable. Using the same power as the ebf would use, the craft time is around 4h, 

You sorta gotta look at the wait times of this overall process to see that changing SC cool time doesn't change much. Using a zpm vac freezer and ebf, you're mostly running the ebf, as all the ebf tiimes added up are longer than the vac times. The ebf is your main time gate, as it's what's running the whole time. Lowering the cooling time doesn't have an impact on your overall crafting time, it just means you need to use less power on freezing. 

To change coil craft times lower SC count in coils, and change the craft to 15x SC per pump. Both of these have significant changes to the SC time, both in evening out the times of the SC wires themselves and the pump cost in the SC wires, and reducing the time needed for crafting the the coils. 

![image](https://user-images.githubusercontent.com/21280852/55708428-ebb47100-59b3-11e9-9fe8-51af517698a3.png)
here's some math

Also here's a version with this suggestion for SC cooling
![image](https://user-images.githubusercontent.com/21280852/55708494-143c6b00-59b4-11e9-9983-5a0ea64ca84f.png)
LuV vac keeps up with zpm ebf here, which is uh, why....
