### ISSUE TITLE
chamelium uncraftable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4339]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
wanted to make chamelium:
![image](https://user-images.githubusercontent.com/12850933/55656121-486a2d00-57f6-11e9-85e1-0b0c7322b47e.png)

![image](https://user-images.githubusercontent.com/12850933/55656180-6041b100-57f6-11e9-9e55-2cddb96bcd27.png)

#
#### What happend instead? (Attach screenshots if needed)
it doesn't start:
![image](https://user-images.githubusercontent.com/12850933/55656055-207ac980-57f6-11e9-86ee-66e82d93bf4b.png)

but if i add one more coal dust i get this:
![image](https://user-images.githubusercontent.com/12850933/55656095-37b9b700-57f6-11e9-880d-8bba7304cbc1.png)

So it seems that the coal ball recipe is taking priority on the chamelium recipe

**Comment by repo-alt** [comment]
Weird, I just yesterday made a stack of chamelium on Epsilon...

**Comment by boubou19** [comment]
i'll try to make some again to see if a reboot fixed it

**Comment by boubou19** [comment]
nope still doesn't work

**Comment by boubou19** [comment]
it works well on delta: 
![image](https://user-images.githubusercontent.com/12850933/55666767-9a8d6b80-5853-11e9-883a-72a34e939b58.png)
i'm gonna try to make some chamelium in a hv mixer to see if it's the issue.

**Comment by boubou19** [comment]
it works well with a hv mixer too on delta. I'm out of ideas.

**Comment by boubou19** [comment]
My team mates said we now have chamelium so a couple of reboot must have fixed it. weird.
