### ISSUE TITLE
Recipe fix  - Nano rubber boots

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#434]
Assembler recipes uses 2 rubber boots which aren't stackable, change the recipe so it uses just 1 rubber boots

**Comment by Drobac** [comment]
Recipe fix Laser Emitter
Replace the coolant cells from 60kCoolant cells with 4209 to 60kCoolant cells 4209:1

**Comment by Drobac** [comment]
Item id 7259 still uncraftable

**Comment by Namikon** [comment]
Something weird is happening here. This exact issue was solved already: #343 
I wonder how many recipes are also "reset" to some old state...

**Comment by Dream-Master** [comment]
they fixed now i load the wrong recipe file on the server :)
