### ISSUE TITLE
Ore finder rod not working with some GT stone types

### ISSUE THREAD

**Issue by hausfath** [GTNewHorizons/NewHorizons#4340]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen? 
Ore finder wand does not appear to work with black granite.
#
#### What happend instead? (Attach screenshots if needed)
The ore finder does work with vanilla minecraft stone types (I tested it with regular stone) but does not appear to work with black granite. I tested using both black granite cobble and regular black granite (obtained by smelting the cobble). Standing right next to a vein shows no response.

#
#### What do you suggest instead/what changes do you propose?
Fix the ore finder wand to work with gregtech stone types.

**Comment by richardhendricks** [comment]
Check here, maybe removing background stone type is messing up detecting non-ore GT stones
https://github.com/GTNewHorizons/IFU/commit/3afd7d586525bdb77bbc755e76dfe4db36a413b6#diff-858c857c32bc67a004839ec88297deb2R161

**Comment by richardhendricks** [comment]
@moronwmachinegun 
https://github.com/GTNewHorizons/IFU/blob/3afd7d586525bdb77bbc755e76dfe4db36a413b6/src/main/java/com/encraft/dz/items/ItemOreFinderTool.java#L161
change this to: (you need to add nullchecks)
Materials material = GT_OreDictUnificator.getAssociation(searchItem).mMaterial.mMaterial;


then later in the code change this:
https://github.com/GTNewHorizons/IFU/blob/3afd7d586525bdb77bbc755e76dfe4db36a413b6/src/main/java/com/encraft/dz/items/ItemOreFinderTool.java#L186
 for (Materials m :Materials.values()){
            if (m == material ) {
                boolean blacklisted = false;
                for (String s : dupe) {
                    //System.out.println("Blacklisted ore " + s + " compared to " + name );
                    if (s != null && s.equals(m.mName)) {
                        //System.out.println("Ignore, ore is blacklisted");
                        // ore is blacklisted, do not report
                        blacklisted = true;
                    }
                }
                if (!blacklisted ) {
                    found++;
                    //System.out.println("Exact match found");
                    if (found >= MAX_DAMAGE) {
                        keepLooking = false;
                    }
                    break;
                }
                }
                break;
            }
            if (keepLooking)
                continue;
GitHub
GTNewHorizons/IFU
Low Tec Ore Scanner by EnnekPL. Contribute to GTNewHorizons/IFU development by creating an account on GitHub.

GitHub
GTNewHorizons/IFU
Low Tec Ore Scanner by EnnekPL. Contribute to GTNewHorizons/IFU development by creating an account on GitHub.

**Comment by richardhendricks** [comment]
Bart did a fix for this, need to validate.

**Comment by richardhendricks** [comment]
Works for black and red granite and marble, but not basalt (?)
@bartimaeusnek
