### ISSUE TITLE
Iron capped Greatwood Wand quest complete issue

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/NewHorizons#4341]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
Quest : Iron capped Greatwood Wand
When crafting this wand ( using the recipe found with NEI 'U') the quest dose not complete.
First few thoughts are a either a wrong recipe or a bug.
I did figured i would try to charge it to full strength to see if it completed and it did.
#
#### What do you suggest instead/what changes do you propose?
Add text to the quest (or and extra step), that tells a the player to build the wand and then charge it to complete the quest.

**Comment by Devtron3D** [comment]
The quest "Gold Banded Greatword Wand" has the same issue.
Needs to be fully charged to work. but it is not said in the quest text.

**Comment by richardhendricks** [comment]
Removed vis requirements from wands.
