### ISSUE TITLE
Add quest for Soul Brazier to hold player permanent warp

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4342]
From dgamer1993

ok this is how it works once u put all the perm warp it holds only  u need vis  and essence of mortuus that and a etherealbloom for the taint spread to get rid of  it does take somethat a bit of essence but once it runs out the perm warp goes back to u and if u break it same thing so hopes this helps

![image](https://user-images.githubusercontent.com/1214811/55664374-2d95b980-57f2-11e9-8b0b-2ebd7459dae4.png)

![image](https://user-images.githubusercontent.com/1214811/55664391-6e8dce00-57f2-11e9-90a5-b60fd015c496.png)

![image](https://user-images.githubusercontent.com/1214811/55664412-bf9dc200-57f2-11e9-8566-96ec042b3fa1.png)

**Comment by septemberWaves** [comment]
Does this work across dimensions? For example, if I want to keep it in the Twilight Forest to avoid any risk of tainting anything important, would I be able to do that and still have the warp stored when I return to the Overworld (presumably as long as it is chunkloaded)? It is probably worthwhile to note the answer to this question (whatever it may be) in the quest, if you do end up making one for the soul brazier.

**Comment by richardhendricks** [comment]
There are quite a few open questions, for sure.  What happens if the brazier is in a chunk that gets unloaded, for example?   A lot more research needs to be done on this.

**Comment by richardhendricks** [comment]
OK, so the Soul Brazier will only hold your warp within a range of 3 chunks.  So it's useful if you want to prevent warp effects in your base without having to hit the spa all the time. Not quite as good as I'd hope. 

Here he implies it does work while in other dimensions?
https://www.reddit.com/r/feedthebeast/comments/34lp85/so_the_soul_brazier_with_action_shots/

wiki is slim pickings
https://ftbwiki.org/Soul_Brazier

We have our own branch of TE, so maybe we could change this up? Longer range? Lower the drain? Etc.

**Comment by richardhendricks** [comment]
I will add a new quest, but try to go over the usefulness a bit.

**Comment by richardhendricks** [comment]
Looking at the code we have, it will chunkload itself when activated. So it will stay loaded if the player is across another dimension.  It only pulls the permanent warp off the player, not the temp or normal warp.

Also, I don't see any sort of range on it, so this a pretty decent solution.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57187024-a732cd00-6eae-11e9-9063-f2a7e10f9796.png)
