### ISSUE TITLE
Basic Laser Precision Engraver Quest Invisible

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#4345]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
I complete the quest  for the "Basic precision laser engraver" (quest id 99) and it gave me a notification that I finished the quest, but the quest is nowhere in my questbook to be found.

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
The quest should probably be moved into the LV Tier questbook-page.

**Comment by richardhendricks** [comment]
Need to look into if the Basic PLE quest was removed for some reason, probably because it isn't that useful?  Is it needed for anything in LV?

**Comment by DarkShadow44** [comment]
>  Is it needed for anything in LV?

Not that I know of, I'm in HV without ever needing a LV laser engraver.

**Comment by richardhendricks** [comment]
OK, I think we just unlink quests that are no longer needed, that way quest #'s don't change for localization. Did you craft the Basic PLE or just see a notification about completing a partial quest step?

**Comment by DarkShadow44** [comment]
I did craft it, for completeness sake - but it didn't seem to unlock anything.

**Comment by richardhendricks** [comment]
I'm confused.  You said you couldn't find the quest, but then you crafted it for completeness sake?  How did you know the quest existed if you couldn't find it?

**Comment by DarkShadow44** [comment]
I mean, I wanted to have the LV basic laser engraver since I made most other machines, too.

**Comment by richardhendricks** [comment]
Changed to consume quest so it should not auto complete.  Not in any quest tab so not visible to end users.

![image](https://user-images.githubusercontent.com/1214811/57498113-2dc91f00-72a0-11e9-9016-7359a78f2ed6.png)
