### ISSUE TITLE
Mega Blast Furnace Tries to smelt too many things and fails

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4346]
2.0.7.0

Tested with HV Tier Glass
Various energy Hatches with stainless steel dust with the lower tier coils.

1 ZPM Energy hatch smelts 256 dust at hv for each dust and works as expected.
It also will overclock when able if less than 256 dust are inputed and not cause itself to fail by drawing to much voltage.

1 HV energy hatch, backed by a 16A buffer, can only smelt 1 stainless steel dust at a time.
any more up to 4 total will cause smelting to fail and the items to be destroyed.
furnace should not smelt in number it has no hope to smelt
adding more energy hatches does not solve this issue until energy hatch total surpasses minimum power needed to smelt

**Comment by bartimaeusnek** [comment]
*should be fixed* if not re-comment please i send you the inDev version of bartworks

**Comment by draknyte1** [comment]
Setup CircleCI and ill give you my build files.

**Comment by bartimaeusnek** [comment]
@draknyte1 i got travis :p

**Comment by Anarack** [comment]
Updating this as I forgot, last beta you gave me, some what fixes behavior for one energy hatch, but not multiple.
1 energy hatch both amps must be supplied to it for the mega blast to work correctly.
more than one hatch runs into issues of not attempting the correct number of recipes.

**Comment by bartimaeusnek** [comment]
also fixed
