### ISSUE TITLE
cannot craft abs control block

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/NewHorizons#4347]
Single player on 2.0.7.0
![image](https://user-images.githubusercontent.com/15355637/55685191-3b962800-5921-11e9-915c-8c47a8d7ea93.png)

**Comment by yukieiji** [comment]
One circuit uses that of the EV tier.
![2019-04-08_05 53 25](https://user-images.githubusercontent.com/40425798/55689690-afd4d800-59c2-11e9-92f8-8f738a34c06c.png)
