### ISSUE TITLE
Add a quest for the Lead Lined Box to avoid further confusion

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4349]
It took me FOREVER to figure this out.

The box is used to let Radium decay without being in the players inventory. (Needed for Radon in EV)

**Comment by Shattered2909** [comment]
Oh right, also: the Radon Decay quest requires 64 Crushed Uranium 238 Ore which makes no sense because it requires Phobos or Deimos. Pitchblende works for Radium too and is found on Mars, no further travelling needed.

**Comment by septemberWaves** [comment]
Deimos and Phobos require the same rocket tier as Mars. Unless you enjoy enormously long excursions in each dimension to gather every resource you will ever require to eschew any need to return, I see no reason why visiting the Martian moons would be any more trouble than visiting Mars itself.

As for the main purpose of this thread, I agree that a quest for the lead lined box should be added.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57199644-10feb580-6f47-11e9-9ba4-d82565b51a64.png)
