### ISSUE TITLE
CF Sprayer

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#435]
I was looking for uses for stone dust and I stumbled upon CF powder, then I remembered IC2 has an interesting building material called Construction Foam.

Would be a good use for stone dust (maybe it will be voided less). CFoam can be made, though the actual thing that "sprays" or puts it down on the ground,  the "CF Sprayer" is missing a recipe.
Which is strange as the CF backpack has one.

To refill it, make "CF Powder", then mix it in the mixer with water again to get the fluid.
Another way is right clicking placed water with CF powder, and then using the sprayer on it.
Testing it in SP reveals that even the GT Fluid canner can fill up the CF Sprayer, but not the CF Backpack. Unfortunately you'd need the IC2 Fluid/Solid Canner for that.
The CF Backpack holds 80000mb of Construction foam, maybe a recipe for the fluid canner to refill it with GT CFoam? Thoughts?

A "scaffold" from IC2 is needed to control the CFoam vertically, for those unfamiliar with it.
Nice thing about the foam is that it can be colored with most painters. (I tested IC2 and openblocks) Though, it takes a while for the foam to "harden" and become a block.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/12079322/c06cbf68-b234-11e5-817f-b430f0603053.png)

The recipe is there but not shown only when you try the uses for Cf Foam

**Comment by Dream-Master** [comment]
Will add some cf sprayer recipes for gt machines too.

**Comment by Teteros** [comment]
Yep, it was NEI. The GT canning machine works,  just needs the full 80000mB buckets fill to fill the backpack all at once.

**Comment by Dream-Master** [comment]
:+1:

**Comment by Teteros** [comment]
Still using the IC2 canner though because only the IV Fluid canner holds 80000mb.

**Comment by Dream-Master** [comment]
ah ok
