### ISSUE TITLE
UHV Motor is uncraftable

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4350]
#### Which modpack version are you using?
2.0.7.0

The UHV motor need Cosmic Neutronium Ring which is uncraftable.
No NEI, cannot craft by solidifying or hammer.

**Comment by Dream-Master** [comment]
will check

**Comment by Kiwi233** [comment]
By the way, the Cosmic Neutronium Rod only can be crafted by file.

**Comment by DietmarKracht** [comment]
There are some recipes missing for extruding cosmic neutronium. 

1. Small Cosmic Neutronium Gear
2. Large Cosmic Neutronium Gear
3. Cosmic Neutronium Rod

Maybe it would be nice to have cosmic neutronium as a fluid, but not necessary.

**Comment by Dream-Master** [comment]
it has a tag no smelting.
