### ISSUE TITLE
Missing recipe?

### ISSUE THREAD

**Issue by Novarek** [GTNewHorizons/NewHorizons#4352]
#### Which modpack version are you using?
2062/2070
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Cant find recipe for: maraging steel 250, 300, 350 dust. Same with inconel 250. However there is recipe for inconel 690 and 792.
#
#### What happend instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Add mixer recipe for above dusts

**Comment by draknyte1** [comment]
They’re made purely in the ABS (Alloy Blast Smelter).

Consider looking at recipes for the molten metal in future. As most alloys from GT++ are obtained this way.

**Comment by Novarek** [comment]
Oh ok, thanks for that. Probably I never could figure out it myself. As most ingots comes from dust, I didnt look for molten version of above metals.

**Comment by Novarek** [comment]
Oh ok, thanks for that. Probably I never could figure out it myself. As most ingots comes from dust, I didnt look for molten version of above metals.
