### ISSUE TITLE
Filling Cabinet Bug

### ISSUE THREAD

**Issue by JokoJose** [GTNewHorizons/NewHorizons#4353]
![Screenshot (20)](https://user-images.githubusercontent.com/35201825/56033709-1de70b00-5cf3-11e9-8090-2ea512c9ac47.png)
#### Which modpack version are you using?

# GT NewHorizons v2.0.7.0

#### If in multiplayer; On which server does this happen? 

# Delta

#### What did you try to do, and what did you expect to happen?

# I created a Filling Cabinet for enchanted books. I expected that only Books would go inside that Filling Cabinet.

#### What happend instead? (Attach screenshots if needed)

# What happen instead is that the Filling Cabinet got filled with a lot of random items allowing enchanted books to pass beyond the Filling Cabinet in to the drawers.

#### What do you suggest instead/what changes do you propose?

# I would like for that issue to be look on to and if possible get it fix on a future patch if its possible.

![Screenshot (20)](https://user-images.githubusercontent.com/35201825/56033733-28a1a000-5cf3-11e9-86c3-d3de44ffa77c.png)

**Comment by Dream-Master** [comment]
@JokoJose Its from extra utilities? If yes the mod is closed source and cant be changed.

**Comment by damug** [comment]
You could probably set up a filter of some sort to allow only books and ignore nbt data? That should capture and enchanted varieties too.
