### ISSUE TITLE
obsidian glass to use clear glass

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4358]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
to make obsidian glass you neet tickend glass 
tickend glass is made by putting clear glass in a workbench
tis step of putting it in a workbench is noting but an annoyance

**Comment by Dream-Master** [comment]
later on you can do it in a machine.

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/56086367-f3619300-5e55-11e9-9575-b67185ea3da3.png)

this is the recipy for making tikend glass it is literly clear glass no machines needit

**Comment by Dream-Master** [comment]
I mean obsidian glass or I am wrong? Chisel it is another option.

**Comment by botn365** [comment]
obsidian glass is tickend glass + 4 obsidian dust ^ is the recipy for tickend glass
