### ISSUE TITLE
Weird GT cable behavior

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4359]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
i wanted to charge the two buffers with the hv hi amp power transformer:
![2019-04-14_11 44 38](https://user-images.githubusercontent.com/12850933/56091110-c7bcc800-5eaa-11e9-880e-222bf7722f5a.png)
The hv hi-amp power transformer is linked to a transvector which is linked to an ic2 reactor producing 5.6k EU/t
#
#### What happend instead? (Attach screenshots if needed)
only one battery buffer is charging:
![2019-04-14_11 33 53](https://user-images.githubusercontent.com/12850933/56091117-defbb580-5eaa-11e9-8959-58e6aed44db6.png)
the other doesn't want (and i tried to take/replace a battery to update the buffer but nothing happened):
![2019-04-14_11 33 12](https://user-images.githubusercontent.com/12850933/56091123-f470df80-5eaa-11e9-8cff-ed2dce90002e.png)

the thing is according to the tooltip the hi-amp transformer should provide 16 A of HV, even if due to the 5.6k eu/t in input instead of 8.1k eu/t the transformer may not deliver 16 real amps so it should be enough to slowly charge both the buffers silmutaneously.

**Comment by boubou19** [comment]
Ok so i changed the cable for a 16A one because i thought maybe the cable was somehow limiting the current instead of burning (it should have burnt) and i put only one battery on the top bat buffer and 8 in the bottom bat buffer and it works as intended:
![2019-04-14_13 15 17](https://user-images.githubusercontent.com/12850933/56092058-6818e980-5eb7-11e9-9d51-556c6914b9a4.png)
![2019-04-14_13 15 17_2](https://user-images.githubusercontent.com/12850933/56092059-6818e980-5eb7-11e9-992c-cc60159e5d70.png)
but if it put back the 7 other batteries in the top bat buffer the botom one stop charging.
Also i get only 4A of HV but i have 5.6k eu/t so i understand i can't get full 16A but still: 4A HV is only 1A EV
![2019-04-14_13 17 38](https://user-images.githubusercontent.com/12850933/56092083-b0d0a280-5eb7-11e9-9524-caa9779f0d57.png)

**Comment by richardhendricks** [comment]
Battery buffers pull 2x the number of batteries in amps.  The 8 batteries in the top buffer will make it draw 16A.

Also, the batteries will only start charging once the internal EU buffer inside the batbuff has fully charged. Monitor both batbuffs with a tricorder or display to see the internal buffer charge status.

**Comment by boubou19** [comment]
ok thx for the info but if there are only 4A available in the cables, the two bat buffers will pull a total of 32 A max but then why only one is receiving all the amps? Because the Top one start filling the batteries like 10s but the other one doesn't seems to fill its internal buffer.

**Comment by boubou19** [comment]
yeah one buffer is stuck and doesn't want to charge because the other one is pulling too much i guess
but it doesn't make sense as the one not being charged is closer than the one being charged
![2019-04-14_18 25 25](https://user-images.githubusercontent.com/12850933/56095992-aed00900-5ee2-11e9-841e-4e152ed844f6.png)

**Comment by richardhendricks** [comment]
The code is kinda complex, but I don't think an energy source pushes EU from nearest to furthest destination.  It pushes based on whatever destination is first in the (complex) search tree, based on Forge directions.  See code here, how it cycles through directions 0-6 with the for loop at 

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java#L210

and then at line 221 it does transferElectricity for the next tile entities. So nothing to sort by distance etc.

**Comment by boubou19** [comment]
ok then i'll close this
