### ISSUE TITLE
Feature request: Add dimensions for small ores in NEI

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#4362]
As small ores have grown in importance since the last patch (2.7.0), would it be possible to add the dimension descriptions in NEI for small ores similar to the ore veins?

E.g., it is impossible to know that there are small ores of titanium on Mars from NEI even though that is quite important as it is the first pure titanium.

**Comment by richardhendricks** [comment]
I think @bartimaeusnek already implemented an update to handle this.  Will check.

**Comment by bartimaeusnek** [comment]
http://jenkins.usrv.eu:8080/job/GTNEIOrePlugin/lastSuccessfulBuild/artifact/build/libs/gtneioreplugin-1.7.10-1.0.7.jar
