### ISSUE TITLE
Wrong voltage requirements for multiblocks like the vacuum freezer in NEI

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#4363]
Playing 2.7.0.

There are many voltage requirements listed in NEI for recipes in multiblocks like the vacuum freezer that are just not true. These machines do not have any minimum voltage.
Example: Making Tungstensteel in a vacuum freezer requires EV-voltage according to NEI which is impossible to obtain at that point (see issue #4099, this is a common problem). However, the NEI recipe is wrong, as the machine only cares about EU/t and not the voltage. Thankfully, discord pointed this out to me or I would have been stuck.

Suggestion:  In NEI, change 'voltage' and 'amperage' for all recipes in the vacuum freezer (and possibly other multiblocks) to 'unspecified' as it is in the EBF recipes as the behavior is indeed the same for the vacuum freezer and EBF (except for the details regarding overclocking).

**Comment by Anarack** [comment]
Amperage should be changed, not voltage, or you would never know what voltage total you need to reach.

**Comment by chochem** [comment]
Anarack, sorry that is not true. There are 3 entries. Usage, voltage, amperage. The first one is all that matters and all you need for the vacuum freezer. Just look at the EBF recipes for comparison. You do not need a voltage (that is the whole point) but only a usage (=energy/time=amp*voltage).

**Comment by richardhendricks** [comment]
The confusing part is that multis sum up their potential input energy hatches to come up with a tier. So 2 HV hatches at 2A each is 2*2*512=2048, or EV.  I think the better path is to explain this more often in the quests.

**Comment by Anarack** [comment]
It kind of is, at least with the ebf, doesn't help with the ebf questions that pop up however.

**Comment by richardhendricks** [comment]
I don't think we get much EBF questions any more about multiple hatches and overclocking/next tier?  But this is a special case since it is for the vacuum freezer, and we don't really talk about using two hatches there.

**Comment by chochem** [comment]
the confusing part (for me) is that the vacuum freezer has a minimum voltage which according to any gt5 wiki means that you can absolutely not run it on a lower voltage. The EBF is completely fine.

**Comment by chochem** [comment]
The problem is apparently fixed in 2.0.8 by using my suggestion.
