### ISSUE TITLE
Some recipes using item casings are broken

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4364]
Now that there are GT item casings, players don't get the GTNH casings anymore. Some recipes still need them, so should be changed to accept GT ones, recipes are for these items:
-Machine Chassis (Ender IO)
-Kinetic Water and Wind Generator (IC2)
-Low Kinetic
-Medium Kinetic
-High Kinetic is fine as it takes Iridium Alloy
-Extreme Kinetic
-Laser Emitter (for the Laser Gun)
-OV Scanner (IC2)
-Ultimate Lappack
-Coal, Thermal Engine (Steve's carts)
-Blank Upgrade
-Electrotine Generator
-Block Breaker
-Item Importer
-Block Placer
-Fire Starter
-Multimeter
-Router Utility
-Floodgate
-Combustion Gen (Ender IO)
-Zombie Generator
-Sag Mill
-Painting Machine
-Crafter
-The Vat
-Fluid Tank
-Electric Heat Generator (IC2)
-Stirling Generator (IC2)
-CF Backpack
-Small Power Unit
-Crop-Matron
-Steam Generator
-Fluid Regulator
-Liquid Heat Exchanger
-Magnetizer
-Copper Boiler
-All Forestry Farm Blocks
-Beealyzer
-Sturdy Casing (Manual Crafting)
-Flutterlyzer
-Habitat Locator
-OD Scanner
-Thaumometer
-Lepidopterist Database
-Apiarist Database
-Botanist Database
-Arborist Database
-Tiny Coal Engine
-Torch Placer
-XP Shower
-Slimalyzer
-Auto Workbench
-Stirling Generator (Ender IO)
-Obscurator
-Item Buffer (IC2)
-Electric Sorting Machine
-Fluid Distributor
-Solar Distiller
-Batbox Chargepad
-CESU Chargepad
-Engine Booster
-Filtered Importer
-PDA
-Killer Joe
-Item + Liquid Translocator
-MFE Chargepad
-Lapotron Loader Upgrade
-Motor Machine Casing
-Pump Machine Casing
-Processor Machine Casing
-Electronic Library
-Power Unit
-MFSU Chargepad
-Electric Kinetic Generator
-Kinetic Steam Generator
-Remote (WR-CBE)
-Wireless Sniffer
-Private Sniffer
-Remote Accessor
-AFSU
-Ultimate Lappack

That should be it. You can say thanks later, yours truly.

**Comment by Dream-Master** [comment]
I remeber i ordict the stuff when it was implemented. Maybe old script files ?

**Comment by Dream-Master** [comment]
Will check recipes.

**Comment by richardhendricks** [comment]
Are you sure?  I don't see an issue with the recipes. 
![2019-04-18_21 41 51](https://user-images.githubusercontent.com/1214811/56402452-ee6c5d00-6222-11e9-86d2-eabe6d6e222a.png)
![2019-04-18_21 41 52](https://user-images.githubusercontent.com/1214811/56402453-ef04f380-6222-11e9-80b9-4e14f95da6fd.png)
![2019-04-18_21 42 48](https://user-images.githubusercontent.com/1214811/56402454-ef04f380-6222-11e9-989d-6d2f0df93c27.png)
![2019-04-18_21 42 49](https://user-images.githubusercontent.com/1214811/56402455-ef04f380-6222-11e9-86f0-74739ddee428.png)
