### ISSUE TITLE
Weird EBF recipes

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4366]
Smelting HSS-G with Nitrogen takes 1920 EU/t
Without Nitrogen it takes 2920 EU/t

Looks like a typo to me

When smelting Titanium, the 1 full dust + Nitrogen recipe has the same time as without Nitrogen. The small and tiny dust recipes are fine.

**Comment by Dream-Master** [comment]
misstype in code i guess.
