### ISSUE TITLE
Update Seismic Prospector Ore Output

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4368]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What do you suggest instead/what changes do you propose?
the data from the seismic pros is alomost unreadeble 
it print the data from evry vein scanned wich couses the same vein be printet muilteple times on difrent pages 
only chunks that follow the 3n+1 rule should be printet 
remove the close,medium,far it ads more confusion then it helps

the cordinants are written at evry ore wich couses confusion 
insteat of writing it like tis 
> ore1 at cordinate 1
ore 2 at cordinate 1
ore 3 at cordinate 1
ore1 at cordinate 2
ore 2 at cordinate 2
ore 3 at cordinate 2

write it like tis
> (cordinate 1)
ore1
ore2
ore3
(cordinate 2)
ore1
ore2
ore3

**Comment by 0lafe** [comment]
Changing this to simply listing the primary ore, or even all of them sequentially, but using the number system from the fluids would help. If that's possible

**Comment by richardhendricks** [comment]
The scanner knows nothing of the ore "type". Why would a player care about the number system?

**Comment by richardhendricks** [comment]
Will change it so that the prospector only scans orevein centers to cut down on cruft.

**Comment by richardhendricks** [comment]
This is the best I can do, there isn't an easy way to separate chunks on different pages, but they are now sorted and separated at least.
![image](https://user-images.githubusercontent.com/1214811/70882541-baa22c80-1f95-11ea-937a-a2a55b147562.png)
