### ISSUE TITLE
Platinum ingots problem

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#437]
ATM to get a platinum ingot you need a Vacuum freezer. And you cannot craft a Vacuum freezer without platinum.
So either remove the platinum from the EBF all together or make it go from dust to ingot directly in the EBF with no need for the freezer

**Comment by Dream-Master** [comment]
Ok will look inside it.

**Comment by Dream-Master** [comment]
Fixed https://github.com/GTNewHorizons/GT5-Unofficial/commit/1f4f33837deab2f85c92cef7d8f7b66b3b2d3a93
