### ISSUE TITLE
Circuits seem unbalanced

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#4371]
#### Which modpack version are you using?
2.0.7.0

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
I'm at the quest where I need to make Good Integrated Circuits.

I've made a cost comparison between Good Electronic Circuit and Good Integrated Circuit

Good Electronic Circuit:
- Good Circuit Board x1
- Integrated Logic Circuit x2
- Diode x2
- 1x-Copper Wire x2
- Molten Tin 144L

Good Integrated Circuit:
- Good Circuit Board x1
- Integrated Logic Circuit x2
- Resistor x4
- Diode x4
- Fine Gold Wire x4
- Silver Bolt x4
- Molten Tin 144L

Why does the integrated circuit seem to be more expensive? I mean, I most recipes all MV chips (good circuits) are accepted.
What's the difference in usage between the three MV chips (electronic circuit, integrated circuit, integrated processor)?

**Comment by Bluebine** [comment]
The more expensive circuits are needed to make higher-tier circuits than MV.
The cheapest MV circuits are the cheapest because they need to be craftable for reasonable prices in LV, while the others aren't needed until you're ready to enter HV.

**Comment by DarkShadow44** [comment]
Ah, so they're not Ore-Dict unified? That would make more sense then.

Still, for it feels kinda off that the better chips are more expensive. They can be used in the same recipes, and that seems like waste.

**Comment by Bluebine** [comment]
For most purposes, you're right, and you should use the lower tier circuits.
The higher-tier ones are meant for making HV+ circuits.

**Comment by Prometheus0000** [comment]
This should probably be closed.
