### ISSUE TITLE
AE2 quest issues

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4373]
Meteorite quest needs to be main quest

Also the quests suck?

Nori SilverrageToday at 5:08 PM
Yes, but I'm not seeing a controller quest
kekzdealer🐝Today at 5:08 PM
AE tab has super weird quests

kekzdealer🐝Today at 5:08 PM
They ask for P2P tunnels and never ask for drives or controllers

Nori SilverrageToday at 5:08 PM
it also never details how to use the p2p tunnels
as I said, I'm a AE newb and I was hoping the quests would help

![image](https://user-images.githubusercontent.com/1214811/56446116-5fb11c00-62c6-11e9-8b5b-080a2f60193e.png)

**Comment by NoriSilverrage** [comment]
Since the lovely Richard here went above and beyond posting this issue for me... I'll add some color.

I am a complete AE newb. Never used it and had barely heard of it before I started playing GTNH. I just got to a point where I can build the stuff and was hoping the quests would provide lots of help. But alas, while they tell you how to build the items, there is little help in creating a decent network.

For instance, in my reading online, the p2p tunnels are going to be crucial for a ore processing center. Yet the p2p quest here just says to build p2p tunnels.

If I was a expert at this I would offer to help with the quests, but it'll likely be weeks/months before I'm decent enough at it to say anything.

**Comment by richardhendricks** [comment]
@kekzdealer @NoriSilverrage Can we get some more details here?

**Comment by richardhendricks** [comment]
Meteorite quest is a main quest, dunno what exactly and where we need next.

**Comment by NoriSilverrage** [comment]
So I realize 21 days have passed, but I've still only started building AE components. Haven't actually used the system. However I have watched a lot of videos and actually completed many of the quests.

**A few things I noticed** 

- The Find Them All quest isn't actually optional. It really should be option. Maybe one of those checkmark quests?

- The quest that asks you to build P2P tunnels tells you literally nothing about them. Not how to use them or why you "need lots of them". There is no follow up quest and there is no explanation on how to use the basic one and switch it to all the other versions of the tunnel.

- The quests that talk about making the crystals and dusts and fluix crystals give no idea on what amounts you are going to need for a basic setup.

- The cable quest should be split into 3 quests. One quest should be on how to get quartz fiber cables and explain that they do not carry networks, but do carry power and thus are used keep networks separate but power centralized.

- A second quest for smart cables and encouraging using those over the glass or covered cables (they ae the best after all) and a final quest for the dense cables.

- The reason to split those two up is they server vastly different purposes. The dense are your backbone cables, and take up a whole tile. The smart cables are for branching off and such. Both will be used heavily probably.

- The right side with crafting the storage and crafting stuff is ok. It feels like just collecting pieces but never really cumulates into anything. Doesn't explain how to setup a good storage room.

- The arrangement for the crafting processors is odd as don't you need the molecular assembler for those to be of use?

- There is no quest for a controller or a energy acceptor. Both things even a early network will need.

**Some other thoughts:**
I'm a AE noob, so take this in with that thinking.
The PR tab walked you through a real game example of how to use the system to easily automate something that you will need. It'd be great if the AE tab had something similar. This would probably be a separate branch of quests.

For instance, lets say you finished a quest to make some terminals and a few other essential items. A new branch opens up (make it visible but locked from the beginning). The first quest has a list of material on building a system to automate crafting some needed AE parts. Storage cells maybe.

Oh and that brings me to another thought. Many people will use a drawer controller and connect a storage bus to a bank of drawers for bulk storage of dusts or ores etc. This is never mentioned as a option and neither is using compressed chests. Both of which are extremely viable, and bipass the power requirements that might be tough in a early system.

**Comment by richardhendricks** [comment]
ME Controller and Energy Acceptor
![image](https://user-images.githubusercontent.com/1214811/57995421-8f02a680-7a87-11e9-9e7d-f235a9cd6111.png)
![image](https://user-images.githubusercontent.com/1214811/57995425-932ec400-7a87-11e9-80d1-ff2036e2ee1c.png)
![image](https://user-images.githubusercontent.com/1214811/57995428-96c24b00-7a87-11e9-87db-24a14505ddc0.png)

**Comment by richardhendricks** [comment]
Splitting out sample questline for building a small userful AE system into a separate ticket.

![image](https://user-images.githubusercontent.com/1214811/57995494-fae50f00-7a87-11e9-8890-c81e03619141.png)

**Comment by richardhendricks** [comment]
>  The arrangement for the crafting processors is odd as don't you need the molecular assembler for those to be of use?
Please clarify.  The MA isn't blocking anything?
![image](https://user-images.githubusercontent.com/1214811/57995658-f3723580-7a88-11e9-974d-d298a50a1647.png)

**Comment by NoriSilverrage** [comment]
Looking good.

On the MA, my thinking was that the MA is useless without the crafting processor (AFAIK) and I'm pretty sure you would want the MAs if you have processors. Given that, it's position just seems weird.

**Comment by richardhendricks** [comment]
Propose a quest with location, requirements, and rewards.

**Comment by NoriSilverrage** [comment]
I'm really not sure. Staring at it hasn't given me any ideas. It does need the annihilation and formation parts, so it does need to be gated behind that. I suppose you could make the first crafting processor a requirement? Could just mention in the quest text that it needs the processing to be useful.

Not really sure what is best.
