### ISSUE TITLE
Missing Rockbreaker LUV+

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4374]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
There are no Rockbreaker versions for LUV and higher tiers.

#### What do you suggest instead/what changes do you propose?
Add the rockbreakers for higher tiers

**Comment by Dream-Master** [comment]
sure not so difficult I guess
