### ISSUE TITLE
recipy change voltage coil HV,IV

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4375]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
the HV and IV voltage coil neet 4 ingots of material while evry other voltage coil neets 2 ingots per coil 
#
#### What do you suggest instead/what changes do you propose?
half the amount of fine wire fot HV and IV or make energetic alloy and iridium produce 8 fine wire per ingot so that the voltage coils are consistent

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
the difference is that wires of the materials exists.
