### ISSUE TITLE
Shutter Module

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#438]
I'd like to suggest for the recipe of Shutter Modules to be changed to require Steel (Maybe also aluminium as a choice?) bars instead of the door in the assembler.

Due to the nature of GT fluid inputs in machines, calculating molten steel usage for every shutter (door needs only '16' while an ingot gives '144') is very tedious, especially considering how many shutters may be [needed](http://forum.industrial-craft.net/index.php?page=Thread&postID=161937#post161937) in a typical system. One could call them "valves" in their usage.

Time reduced from 50 seconds to 30 seconds would also be welcome, but the current recipe outputs 2 so 50s is justified.

**Comment by Dream-Master** [comment]
Fixed https://github.com/GTNewHorizons/GT5-Unofficial/commit/abc6cfc291929603cf963990982d58bf6f66b349
