### ISSUE TITLE
iv-mainframe has wrong circuit cost

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4384]
#### Which modpack version are you using?
2.0.7.0
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
build iv_mainframe
#
#### What happend instead? (Attach screenshots if needed)
it only consumed 1 ev-circuit also you can use any ev-circuit not only the workstation
![afbeelding](https://user-images.githubusercontent.com/42187820/56661572-4d5a2800-66a2-11e9-94f6-09bd04528bd3.png)
#

**Comment by Dream-Master** [comment]
what you suggest to change ? @botn365

**Comment by botn365** [comment]
make it use 2 workstations so it folows the same recipy as al the mainframes

**Comment by Dream-Master** [comment]
sure
