### ISSUE TITLE
Unintended Fertilizer Loop

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#4389]
Playing GT:NH in version 2.0.7.0.

There is a way to make Fertilizer (Forestry or IC2) very cheaply which seems unintended:

    Mixer: 8 IC2 Fert. + 1 Apatite dust + 1Bucket Water = 30 Forestry Fert.
    Fluid Extractor: 1 Forestry Fert. = 144L Fluid Fert.
    Centrifuge: 144L Fluid Fert. = 1 IC2 Fert.

Overall 1Bucket Water + 1 Apatite dust makes 22 Fertilizer (of either type) which makes every other recipe obsolete in comparison.

I am pretty sure 1. is intended thus making IC2 Fertilizer 'more valuable' than Forestry Fert. So probably 2. and 3. should have matching solid fertilizer.

I was first directed to GT++, https://github.com/alkcorp/GTplusplus/issues/451, but Alk says it is not GT++.

**Comment by Dream-Master** [comment]
fluid fertilizer isn't from gt or my core mod so idk. Need to check

**Comment by chochem** [comment]
only just saw https://github.com/GTNewHorizons/NewHorizons/issues/4351
