### ISSUE TITLE
GT++ Lead Lined Box CTD

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#4391]
#### Which modpack version are you using?
2.0.7.0

#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I noticed the lead lined box had a hardness of 0 according to waila, so I tried breaking it barehanded to see if I could move it elsewhere. It broke instantly followed by a crash to desktop.

Upon relogging, the contents was spilled, but the box was gone.
#
#### What happend instead? (Attach screenshots if needed)
```[B#402]  [18:37:59] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#402]  // Don't be sad, have a hug! <3
[B#402]  
[B#402]  Time: 4/27/19 6:37 PM
[B#402]  Description: Unexpected error
[B#402]  
[B#402]  java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
[B#402]  	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[B#402]  	at java.util.ArrayList.get(ArrayList.java:433)
[B#402]  	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
[B#402]  	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
[B#402]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(Unknown Source)
[B#402]  	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
[B#402]  	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
[B#402]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[B#402]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
[B#402]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
[B#402]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[B#402]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[B#402]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#402]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#402]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[B#402]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#402]  	at java.lang.reflect.Method.invoke(Method.java:498)
[B#402]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#402]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
[leadbox-crash.txt](https://github.com/GTNewHorizons/NewHorizons/files/3124119/leadbox-crash.txt)

Delta itself crashed four minutes later; this might or might not be related.

#
#### What do you suggest instead/what changes do you propose?
The box should have a hardness/resistance to avoid accidental breakage, and it should drop as an item again when broken. 

There should be no crashes.

**Comment by boubou19** [comment]
i broke one eta and there was no crash but it was not bare hand

**Comment by draknyte1** [comment]
Wrong place to post GT++ issues. 
> https://GitHub.com/AlkCorp/Gtplusplus/issues

Wrong log file. 
> fml-client-latest

**Comment by draknyte1** [comment]
Both resolved in https://github.com/alkcorp/GTplusplus/commit/9944302dd6a557dfc5c191193c873d7a8b00fdff

**Comment by combusterf** [comment]
> Wrong log file.
Such sentiments are only appreciated if the file was not half a gigabyte in size.
