### ISSUE TITLE
Quest ID 1504 (Ore Finder Wand) Won't Complete

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4392]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Crafted the ore finder wand. Expected Quest to complete.
#
#### What happend instead? (Attach screenshots if needed)
Didn't complete.
#
#### What do you suggest instead/what changes do you propose?
Fix the detection.

**Comment by dragagon** [comment]
I found that you can get it to complete by shift-right click to set it back to "default" and it'll complete. Happened in 2.0.7.0

**Comment by richardhendricks** [comment]
Redid requirement with crafted ore finder wand, might fix.
