### ISSUE TITLE
[BetterQuesting] Sulfur Ore Quest Text Addition

### ISSUE THREAD

**Issue by voidlogic** [GTNewHorizons/NewHorizons#4396]
#### Which modpack version are you using?
2.0.5.1
#

How to make rubber #496
32 Sulfur Ore 32 Pyrite Ore 32 Sphalerite Ore

**Quest text should mention that sphalerite soon electrolyzes into zinc and gallium for use in circuits.** 

Had a player wandering the nether for a long time, at a complete loss for how to obtain these two elements.

**Comment by richardhendricks** [comment]
Which quest had them looking for zinc or gallium?  I added a note for sphalerite to the cobalt brass quest.  The gallium arsenide quest already talks about using sphalerite.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57414697-cd15e580-71be-11e9-9e88-4d8f99f5e8a4.png)

**Comment by richardhendricks** [comment]
2.0.5.1 is too old. Quest was added in 2.0.7.0.
