### ISSUE TITLE
TecTech Research Station Bug

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4398]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
GTNH Delta
#
#### What did you try to do, and what did you expect to happen?
I scanned an UV fluid pump in a regular scanner and the research station. Both result the same data stick

It seems like some if not all researches do not have to be done in the research station and can also be done inside a regular scanner

**Comment by Dream-Master** [comment]
fixed in 7.1 7.2

**Comment by draknyte1** [comment]
Last I checked, TT lets you do every scanner recipe in the research station. 
I even added compatibility for such.
