### ISSUE TITLE
Epichlorohydrin int 23/24 swap

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4399]
#### Which modpack version are you using?
2.0.7

#### What do you suggest instead/what changes do you propose?

The int 24 recipe for epichlorohydrin is not the simplest one, and the simple one in int 23. I'd suggest switching these 2 if possible. It doesn't look like any of the inputs have a recipe that uses less than all of them, so it looks like it should work. 

Int 23
![2019-04-29_17 47 23](https://user-images.githubusercontent.com/21280852/56929152-e7591080-6aa6-11e9-9fa6-caea7bb69a0f.png)

int 24
![2019-04-29_17 47 25](https://user-images.githubusercontent.com/21280852/56929153-e7591080-6aa6-11e9-846f-840dae44d680.png)

There's another int 24 that uses the mercury based HClO, which probably shouldn't be 24 as it's sort of a worse version of the Mercury including 24, but could stay as the HClO based int 24 as it works with the current 23 changing to a 24. The 24 I showed above doesn't, at least not as well. Technically it would work, but you'd need to limit your Cl below 4b when using it in the worst case option.

**Comment by kekzdealer** [comment]
The 24 one could be seen as easier as it makes the outputs match up perfectly with the 24 epoxy recipe (needs 1000L HCl & 1000L Epichlorohydrin).
