### ISSUE TITLE
Thaumcraft Wand Recharging Pedestal duplicates vis

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/NewHorizons#4401]
#### Which modpack version are you using?
2.0.7.0

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
Tried charging a wand inside a Wand Charging Pedestal.  Expected the wand to get only the vis that is inside the nodes, but it fills the wands a lot faster sometimes..

For reproducing follow the following steps:
- Create a new world with creative mode enabled
- give yourself an empty wand
- place a random aura node, note the amount of vis inside it
- place Wand Recharging Pedestal
- place wand onto pedestal, take it off again, and place it again.
- wand should now charge two vis for every one vis drained. you can add up the vis from wand and node, or just notice the wand charging twice as fast.

#
#### What do you suggest instead/what changes do you propose?
The pedestal probably shouldn't duplicate vis. Looks like a Thaumcraft bug though, does happen with only Thaumcraft installed, too. Not sure how easy it would be to fix.

Can someone confirm the issue affects them too?

**Comment by DarkShadow44** [comment]
I think I have a solution for this, although i would need permission from Azanor for a fix. The problem here seems to be a desynchronization between client and server, leading to the wand being updated on the server, and on the client - adding up the vis.

**Comment by bartimaeusnek** [comment]
Azanor has quit MC modding, so either make an ASM patch, or contact me on discord and we can work that out, if you want this to be fixed.
