### ISSUE TITLE
Ore finder wand quest issue.

### ISSUE THREAD

**Issue by ItzzGamma** [GTNewHorizons/NewHorizons#4403]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Tried to complete the Ore finder quest (Divine rod of the gods) and i expected the quest to accept my item.
#
#### What happend instead? (Attach screenshots if needed)
The final quest for the Ore Finder Wand did not accept my crafted item.
#
#### What do you suggest instead/what changes do you propose?

Stone age (Divine rod of the gods) Orefinder Quest requires 9259:1 while the orefinder which is given by crafting is 9259:10. I suggest changing the required quest item to 9259:10 or the given item from crafting to 9259:1.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4392
