### ISSUE TITLE
Item "*any material* Drill Tip" isn't showed by NEI

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4404]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
My own private server.
#
#### What did you try to do, and what did you expect to happen?
I tried to look at all possible Drill Tips in NEI, so I expected it to appear.
#
#### What happend instead? (Attach screenshots if needed)
There is no drill tips in NEI at all.
![image](https://user-images.githubusercontent.com/25156941/57159244-15fc2180-6dee-11e9-86eb-d37d98e03473.png)

**Comment by richardhendricks** [comment]
This is a limitation of how GT makes its parts. It doesn't show every wrench, wire cutter, screwdriver etc combination either.  

Some tips:
Look at the "generic" NEI version of the tools. 
Look at a part used in the tool, like plates, and hit U to find uses.  That will show the tool recipes.

Should this be included in a quest?
