### ISSUE TITLE
Quest Recommendations from Shattered

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4407]
- [x] you could  go and also add quests for IV macerator, IV washing plant and IV thermal centrifuge cuz those are required for the multiblocks. - Quests not added, already have quests for the multis.
- [x]  EV, you should add quests for the circuits for nanocomputers. those are wafers that take carbon fiber and glowstone. pref in an LCR.
- [x] EV cutting machine 
- [x] EV hatches before that
- [x] the ore quests for T2 planets are a complete mess. 4 of 5 veins are tungsten ones
- [x] there should be quests for higher kinetics
- [x] why on earth does the IV machine hull quest require stone from all T2 planets?
- [x] Update stone requirements for asteroid quest?
- [x] HSS-G should not be behind a T3 rocket. thats kind of a rush in IV. it helps a bit with smelting iridium which is needed for T3. So move HSS-G to before the T3, just after the IV hull
- [x] IV extruder
- [x] IV circuit assembling/the entire cleanroom package after quantum star - Already exists?
- [x] IV cutting machine/laser engraver
- [x] after the IV circuit assembler, quests for quantum circuits - Already exists?
- [x] the assline should not unlock before the IV circuit assembler + quantum circuits
- [x] assembler machine casing takes quantum mainframes
- [x] AFSU - like IV MFSU? recharging equipment? 1  billion Eu storage?
- [x] the entire chemistry thing, blablabla you get the idea - Polybenz line exists? Not sure what you mean
- [x] ender tanks and chests should also have a quest (in the T2 thaumcraft tree imo) - gated by Fiery Tears
- [x] Oxygen sealer on Galaticraft page, after Oxygen Bubble Distributor - already there? Requires airlock and OBD - Re-arranged quests, Sealer is gated by T2 Rocket, unlocks airlock. OBD is gated by T1 rocket.

**Comment by Shattered2909** [comment]
Approved

**Comment by richardhendricks** [comment]
Shat
- IV prep items for multis not added, we already have the multi quests
- what did you mean EV hatches quest? EV energy hatches? Dynamo hatches? Not sure. PLayers at this tier should be able to figure this part out, no?
- TUngstensteel quest in EV is an OR quest, player only needs to do 1 of the prereqs to unlock it.

![image](https://user-images.githubusercontent.com/1214811/57502493-8ce35f80-72b1-11e9-8484-f2ec618b93c3.png)
![image](https://user-images.githubusercontent.com/1214811/57502495-9076e680-72b1-11e9-81f3-2ee66d6ca71c.png)
![image](https://user-images.githubusercontent.com/1214811/57502497-94a30400-72b1-11e9-9761-8449ed84c9ac.png)
![image](https://user-images.githubusercontent.com/1214811/57502502-a1bff300-72b1-11e9-948c-ce48a0250846.png)

**Comment by richardhendricks** [comment]
Removed redundant tungsten quest, changed Deimos ore quest to be pure uranium ores instead

![image](https://user-images.githubusercontent.com/1214811/58297288-d7c6a200-7d9c-11e9-886b-b40fabad5d05.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58301767-7e1aa380-7dad-11e9-87b3-946ed5703214.png)
![image](https://user-images.githubusercontent.com/1214811/58301772-81ae2a80-7dad-11e9-91ca-7d55ee517dd6.png)

Don't really like the AFSU myself, to be honest.  Loses percentage of EU when you right-click to break it, loses all EU when you left click to break it.  Seems like it will make a lot of sad players.
![image](https://user-images.githubusercontent.com/1214811/58302475-e4ed8c00-7db0-11e9-896c-6e5c0b75a131.png)
