### ISSUE TITLE
[RFC] New Rocket Recipes

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4409]
#### What do you suggest instead/what changes do you propose?

Right now, Rockets take T+1 Materials, which may, or may not, "nerf" the rocket. In my personal opinion, it just makes the construction of the early rockets (T2, T3) tedious. This is why i suggest changing the Material to a T+0 Material (i.e. T2 rocket now has Tungstensteel -> Meteoric Iron / Titanium). That would give the player more freedom to play in a way he prefers, without needing to build extra machinery he wont use soon after. (This applies especially to the T3 rocket)

This change also dis-ordered the Quests ( see https://github.com/GTNewHorizons/NewHorizons/issues/4407 ) Tungstensteel is behind the T2 rocket, Iridium doesnt even have a Quest, and HSS-G, which is needed for smelting Ir, is behind the T3 rocket.

**Comment by Shattered2909** [comment]
disagree. it does not make early rockets tedious, you can get tungsten from lava/the end and iridium is a byproduct of meteoric iron.

**Comment by kekzdealer** [comment]
I think it is okay to ask for some scraps of the next tier material. Though it needs thorough checking that current tier coils allow for it and the material is actually obtainable in small amounts. 
It also should be an amount that can be gotten by processing some dust from somewhere or similar. Asking for a dedicated setup is too much.

As it is right now, you can obtain the Tungsten for the T2 rocket easily by processing some lava or any of the other sources. Olafe however already stated that he wanted to make the T2 plates cost several ingots  per plate, which is way too much in my opinion. At that point you're more or less forced into the Everburn/Centrifuge route.

**Comment by 0lafe** [comment]
Not really, even at 2 ingots per plate and less return it's still doable with manual lava and centrifuging. I also tried to buff endstone production of it, and moon stone could be buffed too? Tungsten production from lava is significantly faster than the current rocket needs. The current rocket is also a tungsten gen, meaning you only need 1 tungsten dust to make it. 1... 
2 per plate, 3 tiny back, means you need like 7 pure tungsten. Lava currently is more than fine for that, and endstone would be if numbers were adjusted to reflect total tungsten gained from before the change to tungstate. Also puts it more inline with lava, giving you options. 

Tungstensteel is an EV material, in almost every way possible. It's not unlocked in the previous tier, but that doesn't mean it's not ev. 

Iridium is IV, and goes in the IV rocket. However, with the ease of getting Ir dust from meteoric, using ~20 in the rocket seems fine. No specific setup needed either, because apparently that's a bad thing.

**Comment by ScriptedPiky** [comment]
> moon stone could be buffed too


Going to repost a comment about this as well https://github.com/GTNewHorizons/NewHorizons/issues/4379

> I'd also recommend changing the Moonstone centrifuging recipe to be buffed (I'll go more in-depth about changing/buffing the planet stones in the future), such as: changing the tiny pile of tungstate to pure tiny pile of tungsten. Change the current chance of 1.50% to 3.75% as well.

For instance: If you decided to run your LV centrifuge to process Moonstone for exactly 1-hour for every 20 seconds on the current game patch (in-game time, so this can take longer with TPS issues), you'd get exactly .5 whole dusts worth of tungstate. Or rather, 4.5 tiny piles of tungstate over 1-hour in-game time roughly. This is without overclocking to HV or EV. Overclocking to HV would simply put it at 5 seconds and 2.5 seconds at EV.

Math by the way from my friend that explained this to me: (0.025) * (3600/20) / 9 = 0.5
In order: % of the tungstate (2.5%), 1-hour in seconds, recipe time in seconds, into a whole pile of tungstate


Now if the % of obtaining pure tiny tungsten from moon dust is 3.75% for my proposed recipe change, we get this answer: (0.0375) * (3600/20) / 9 = 0.75
So every hour at LV voltage in a SINGLE centrifuge, we get roughly 0.75 whole tungsten/hourly. Is it too much at LV? Eh, possibly. Remember, the Moon is meant to be the next step towards your next rocket, so it better be damn good to obtain pure tungsten from moonstone centrifuging, although, this can be adjusted as pure tungsten can be strong and if that's the case, it can be lowered to 3.50% or 3% for a tiny dust. That's also with absolute PERFECT 20.00 TPS conditions on a server with no lag and requirement of staying next to the centrifuge or having chunkloaders. It'll obviously take longer with lower TPS

**Comment by Dream-Master** [comment]
get tungsten from moonestone? tungstate woul be better need ev Voltage to process.

**Comment by 0lafe** [comment]
Yeah. If you look at the math, on a 1/3 recycle, using pure tungsten output nothing less than 4ingots/plate seems fair. 40/rocket, before returned dust. Pure tungsten 2% is close to lava output, or 15% for tungstate (preferably the 2nd one). These make ingots of tungsteen steel take about 4min at EV, which imo means 20+ tungstensteel per rocket seems ok. 

No tungsten pre tungstate needs buffing if the rocket plate recipes aren't changed to use more tungstensteel and or give less back. That said, current production rates far exceed the rocket usage rates, and plate recipes should change. Moonstone should be viable, but can still output tungstate and do that.

**Comment by Dream-Master** [comment]
ok but what we need to change here @0lafe

**Comment by 0lafe** [comment]
Increase tungstensteel usage in T2 heavy duty plates from 36L to 432L, reduce tungstensteel dust output from implosion compressor to 2-3 tiny dusts instead of 5, change tungstate output % to 15 from 2.5 for centrifuging moon stone.

**Comment by kekzdealer** [comment]
Trading a more expensive rocket recipes for easier access to tungsten pre T2 sounds nice :o

**Comment by 0lafe** [comment]
Kinda, lava already exists and it's just putting the rocket recipe inline with the production from lava. Then makes moonstone and endstone comparable with lava

**Comment by Hyperic88** [comment]
Tbh nerfing those recipes in a way you suggested 0lafe is insane ;) Obtaining materials for the rocket even T1 from scratch is expensive but still doable, this addition will make more people annoyed... including me

**Comment by richardhendricks** [comment]
Endstone is easy enough to obtain on most servers, since the End is usually already opened and cleared out. For SP, players can gather lots of moonstones. Should we make an explicit quest or recommendation to come home with lots instead of just throwing it out?

**Comment by ScriptedPiky** [comment]
> Increase tungstensteel usage in T2 heavy duty plates from 36L to 432L, reduce tungstensteel dust output from implosion compressor to 2-3 tiny dusts instead of 5

Cool. I'm using 3 ingots worth of tungstensteel and only getting 2-3 tiny dusts back. Great idea! Love me getting 15 tungsten just for my damn T2 rocket with barely any source and still abysmal tungsten resource from Moonstone. Now let's put this into perspective: If we need 10 T2 plates for the T2 rocket, that would mean we need 30 tungstensteel total without using the tiny dusts back. Now if we were to salvage as must of the tiny dust as possible, we get 3 tiny dust per T2 heavy-duty ingot. So with this in mind, we literally save only 2.3 whole dusts worth back from the heavy-duty ingots

**Comment by Hakameda** [comment]
I'm with ya, revert the tungstate change from endstone

**Comment by 0lafe** [comment]
>Tbh nerfing those recipes in a way you suggested 0lafe is insane ;) Obtaining materials for the rocket even T1 from scratch is expensive but still doable, this addition will make more people annoyed... including me

Currently it costs 1 tungsten, then gens you like 2 by the end. Idk what you think expensive means, but it's not that. If you really think 15-20 pure W dust pre T2 is unreasonable it would be nice to know why, as the rates produced from lava are more than enough to accomplish that. Moonstone/endstone should be competitive soon too, but that just means more options.

**Comment by Bluebine** [comment]
my thoughts: keep them as they are, but remove the dust that you get back from making the plates.
expecting someone to get 20 tungsten from moonstone or lava is kinda stupid. Getting back more tungstensteel than you put in is also kinda stupid. 
But requiring you to find a way to get 3-4 ingots of the material BEFORE you reach the planet is a cool concept. Just make it a small amount, so it's a test of your ability to process weird stuff, rather than an annoying grind to get a bunch of materials.

**Comment by sthegreat** [comment]
I don't think any tungstensteel is necessary for the T2 rocket. While it is obtainable in late EV, it is still primarily an IV material, the same way we consider titanium an EV material despite it being obtained in late HV or earlier. I think use of the EV assembler is enough of an EV gate for the rocket.

Iridium for T3, in its current amount, seems fine to me as iridium is definitely an IV material and is used in many IV machines.

**Comment by richardhendricks** [comment]
What work is left to do here?

**Comment by Dream-Master** [comment]
nothing so far if everything need to be changed we make a new issue
