### ISSUE TITLE
Oregen broken on Moon

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#441]
Drobac told me that the Oregen seems to be broken; At least on the moon. I could verify that in Singleplayer. Probably more Dimensions do not generate Ores

**Comment by Dream-Master** [comment]
Did Galacticraft change some major things ?

**Comment by Dream-Master** [comment]
Mars works well.

**Comment by Namikon** [comment]
I assume it's because the moonblocks are defined wrong in the SpaceDimRegisterer:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/galacticgreg/SpaceDimRegisterer.java#L112
IIRC, this should be ***tile****.moonBlock* but I can't verify that atm
