### ISSUE TITLE
Buff solar boilers or look at requirements?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4412]
Request from Piky.  I also tried them on Zetatest, and I agreed they are super annoying.

Cause the requirement to constantly wrench them to get full steam and to sleep is incredibly annoying.
12 silver with no steam hammer, 9 silver with a steam hammer, 6 with a LV bender. So imagine my stress getting 16 solar boilers pre-LV :breakdown: Can we buff them?

1. Less resources.  I buffed small silver ores already, but on the servers finding silver bars and small ores will be difficult. Double plates is pretty excessive IMO, I think just normal plates is fine.
2. Better performance. It starts out matching a small coal boiler at 120L/s. . A HP coal boiler can output 300 L/s. I think placing this in the middle at 200L/s base is a good compromise.
3. Calcification effects.  Now calcification takes it to 1/3 of output or 40L/s. It happens pretty fast in terms of gameplay, but I think it's OK to leave this if we up the base output.  Need to time how long it takes, 7 in-game days to calcify would be nice.

**Comment by richardhendricks** [comment]
oh, also faster ramp up time would be good too.  As it is, it isn't even making steam if it waits a full day from cold.

**Comment by Dream-Master** [comment]
switch off calcification or reduce it i am ok with. I nerf the recipe before to double plates of silver to avoid user have 10 or 20 of them in a base at sarting bronze age.
Better preformance is ok too or mae a tier bronze and one tier steel maybe ?

**Comment by richardhendricks** [comment]
I will take a look at slowing down calcification, speeding up heating, and boosting performance a little:
1. Make sure calcification only happens when making steam.
2. Change steam output to be in between bronze and steel boiler.
3. Increase time to fully calcify.  Look at time a stack of coal takes to run in normal boiler, maybe make it equal to ~ 1/2x that time?
4. Fully calcified boiler will be about 50% of bronze boiler.

**Comment by Ngar1** [comment]
disable calcification when using distilled is fine!

**Comment by Dream-Master** [comment]
@Ngar1 this is a good idea.

**Comment by richardhendricks** [comment]
See above comments
