### ISSUE TITLE
GT++ A2 spam

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#4413]
As mentioned in #4111 there's endless "A2" spam from GT++ in the console when opening player inventory. Opening other inventories, such as chests or crafting tables is fine.
Considering it has been over 2 months since this bug has been posted and Alkalus said "Don’t use beta builds.", it would be nice if this could be fixed.

**Comment by sleepylucy** [comment]
🙃

**Comment by sleepylucy** [comment]
Use build 340.
A2 Spam happens cuz it’s a dev Build not intended for public use.

**Comment by Methes** [comment]
Well, I use modpack 2.0.7.0 which has the dev version in it. While I could use different version and switch it on my server too, I don't find it feasible for general public.

**Comment by sleepylucy** [comment]
Dream has been on holiday for probably a month now so that’s why no new GTNH versions came out. You’ll have to wait until he comes back (I forgot when exactly, middle of May I think).
Everyone is aware of A2 and it’s been discussed to death.

**Comment by DietmarKracht** [comment]
Dream will be home in about 24 h

**Comment by Methes** [comment]
Thanks for the info, wasn't aware of that.

**Comment by Dream-Master** [comment]
a2 is fixed in 7.2
