### ISSUE TITLE
Binnies machines uses way too much RF

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#4414]
#### Which modpack version are you using?
2.0.7.2a.dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I've tried to power Binnies genetics machines with HV combustion running on ethanol ... 
#### What happend instead? (Attach screenshots if needed)
That HV gen is barely able to feed that 20RF/t , even one cell of ethanol is 192k EU... some generator efficiency off  so its 163k per cell... it drinks like grumpy russian guy :smile:
and power is enough for that sequencer, batteries empty,so according to that machine tooltip (+pics from SP) it uses 20RF/t which is obviously wrong number otherwise that gen would be moooore than enough... if the ratio is roughly about 1:4 it should be able to produce more than 1024RF/t
![2019-05-05_15 04 31](https://user-images.githubusercontent.com/14223368/57194769-09411000-6f4b-11e9-985f-b2a718528e9c.png)
![2019-05-05_15 28 37](https://user-images.githubusercontent.com/14223368/57194770-09411000-6f4b-11e9-9674-d26aa13d3c0c.png)
#
#
#### What do you suggest instead/what changes do you propose?
Check that, correct ratio or at least give that info somewhere into the quest line :)

**Comment by richardhendricks** [comment]
Ideas:
Does GT gen wait until destination can accept a full EU packet? GT only sends full EU packets, so if it is sending 512 EU but there is only space for 20, maybe the rest is thrown away?

Could you try putting down a batbuff instead, and measure how much it is outputting with a scanner?
And try a couple of different batbuff tiers, like MV/HV/EV?

**Comment by Hyperic88** [comment]
Ive made somewhat workaround, take power from EIO capacitor bank... so GT gen->GT bat buffer->Eio Capacitor bank->machines :) now it works fine

**Comment by Dream-Master** [comment]
Binnies mods are open source so feel free to make code changes

**Comment by richardhendricks** [comment]
OK, mention made in the Enderio Capacitor quest and new Genetics quest tab to use enderio capacitors to power RF machines in Genetics.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57976050-014a8c80-799d-11e9-95ee-526b2dab59de.png)
![image](https://user-images.githubusercontent.com/1214811/57976051-0ad3f480-799d-11e9-85a7-80d3cda5ad28.png)

**Comment by Dream-Master** [comment]
@richardhendricks I think a quest not fix the consume rate of binnies machines? Or I am wrong?

**Comment by richardhendricks** [comment]
It does not fix it, but telling players to use the Enderio Capacitor bank or other RF energy source does.

**Comment by Dream-Master** [comment]
ok
