### ISSUE TITLE
Binnies mod's  - General recipe changes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4418]
The Botany soil meter recipe right now needs 1 steel rod, 4 gold plate, and molten redstone at 64 EU/t for 60s in an assembler (MV Tier)

Recommend lowering it to 1 gold plate, and 16 EU/t for 10s (LV Tier).

The meter doesn't tell you much other than the stats on the soil, so I don't think it needs to be at MV level.
![2019-05-06_21 56 27](https://user-images.githubusercontent.com/1214811/57268546-d0d42b80-7049-11e9-8250-b5f1d73bfed5.png)

**Comment by Dream-Master** [comment]
sure go ahead

**Comment by richardhendricks** [comment]
I don't do recipe changes.

**Comment by Dream-Master** [comment]
ok will do

**Comment by richardhendricks** [comment]
Glass fittings - change from using long iron rods to normal iron rods, increase output from 5 to 10.
