### ISSUE TITLE
Compressed cobblestone

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#442]
The process to make even a single bedrock ingot takes a really really long time. As most of the time is take up by making the first step - single compressed cobble, i suggest to transfer that process to normal compressor machines. This way the process can be sped up as you go along the tiers, and you are rewarded by crafting better machines

**Comment by Dream-Master** [comment]
Bedrockium you not need early game. I can maybe make the first and the second copressed Cobble Stone TNT free but the other not. Or i make the Bedrockium more expencive (need more Stone)

**Comment by Dream-Master** [comment]
Maybe we can add a high Tier Bedrockium producktion line?

**Comment by Dream-Master** [comment]
Bees or UU Matter can be a way to get it.

**Comment by Drobac** [comment]
Minimum ZPM level replicator with UU matter

**Comment by Dream-Master** [comment]
any recipes suggestion?

**Comment by Drobac** [comment]
Well there are a couple of ways to do it. You could do it the standard replicator way, so that you need to scan a bedrock ingot and the make more of them in the replicator at the cost of liquid UU matter. Or an ZPM assembler recipe with diamond blocks and something extra, 1 neutronium ingot or something like that (for "realism" - as neutronium is supposedly extremely dense and can simulate compressed cobble) with some liquid UU.
Open for comments

**Comment by Namikon** [comment]
I like the idea with Neutronium; As it enables people who have reached a certain level to do the "not-so-endgame-stuff" easier. But if you want to use UU-Matter as a reagent to turn Neutronium into bedrockium, then limit it to something like... 50-60 mb. That stuff is not the easiest to get, and you would just exchange "time-required-for-iTNT-explosions" with "time-required-to-get-UU-Matter"

**Comment by Dream-Master** [comment]
So 50 mb UUm an one neutronium ingot make one Bedrockium Ingot ?

**Comment by arnabbiswasalsodeep** [comment]
Hasn't this been implemented now? so we can probably close it right?
And my suggestion is to make most of the double compressed stuff be done without implosion compressor or compressor and just via crafting grid, eg. sand and gravel can be compressed once in crafting grid but not stone and coal/charcoal.

**Comment by Dream-Master** [comment]
Not yet implemented. Can you let it open please.

**Comment by Dream-Master** [comment]
So my solution. The first one is in the compressor but the next level will be in the Implusion Compressor. i lower the amount of Itnt using allready.
Bedrockium  is now made out of neutronium with uumater at zpm Level.
