### ISSUE TITLE
Binnies Sequencer - traits unobtainable

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#4421]
#### Which modpack version are you using?
2.0.7.2a.dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Ive tried to enhance forestry trees via Binnies genetics ->Isolator->analyzer->Sequencer , it's fertility rate for more saplings, height for more wood and girth for the same reason
#
#### What happend instead? (Attach screenshots if needed)
Even i enhanced genetic traits before placing them inside that sequencing machine, whole process will take ->consume that item, but it doesnt write that for further usage into gene database. Only ones that were written were species  of trees and their fruit produced, so you can change saplings from oak to lime for example, but not "upgrade" their mature rate,height etc.

![2019-05-06_22 22 33](https://user-images.githubusercontent.com/14223368/57312900-bdc76700-70ee-11e9-826d-17c06ae915a3.png)
![2019-05-06_22 23 34](https://user-images.githubusercontent.com/14223368/57312901-bdc76700-70ee-11e9-948b-b2a91f1095d2.png)
![2019-05-07_17 34 04](https://user-images.githubusercontent.com/14223368/57312902-bdc76700-70ee-11e9-83f7-bbd6071777f4.png)

#
#### What do you suggest instead/what changes do you propose?
Check if its 100% success rate upon consuming that item with genetic trait except species , those are 100% or at least they were written into that database on the first run all the time so..., its not that easy to get particular gene trait. Back then i was playin at Delta/Epsi it was 100% rate of success for all of those traits.

EDIT: Suppose its same issue thats responsible for https://github.com/GTNewHorizons/NewHorizons/issues/3913

**Comment by repo-alt** [comment]
I have built binnies mod from sources and tested that in dev, - The first gene I obtained was 'Effect'. Interesting that the latest version in 1.7.10 branch in the official repo (https://github.com/ForestryMC/Binnie) is 2.0.22. We use 2.0.23 and I have no idea who built it and from what sources.

**Comment by repo-alt** [comment]
For the record: the bug cannot be reproduced with just Forestry+Binnie, so it must be some mod interaction (likely Gregtech)

**Comment by bartimaeusnek** [comment]
@repo-alt https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/bees/GT_Bee_Mutation.java <- this class i made seems to be issuering
