### ISSUE TITLE
Non-energy hatch nerfs

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#4423]
#### Which modpack version are you using?
.7.0

#### What do you suggest instead/what changes do you propose?

Right now, there are nerfs in place on all the hatches. Outside of energy hatches, this really isn't needed. They unnecessarily add to the cost of early game multis such as the ebf, which were fine previously. They also make tiered input/output buses even more useless. People weren't making IV output hatches very often before, but now they absolutely never will because it needs an IV pump and large tungstensteel fluid cell.

Dynamo hatches are slightly different, but they still do not need to be gated nearly as hard as they are right now. They should be still be tier-appropriate in cost, but if a person has every other part to make a certain powergen setup, I don't think dynamos should prevent them from using it. However these will probably be fine after the addition of multi-amp dynamos for all multis.

I suggest we undo the nerfs on input/output buses and hatches.

**Comment by Dream-Master** [comment]
we can chage the recipe a bit make things easier but the old Gt recipes will never be enabled again.

**Comment by NoriSilverrage** [comment]
I agree, the only time I make the higher up hatches is if I think a single tick will exceed the hatch capacity. They are quite expensive though when you consider all that you need.

Additionally the hatch capacity should make the fluid cell put in. The HV hatch has 54,000 for some reason where as the MV has 32,000 and LV 16,000.

I agree completely on the dynamo hatches. They should be a lot easier to access and be tiered at one lower than their rating, similar to how transformers work.

Currently I'm limited to EV hatches despite easily being able to produce IV power and even having access to a transformer that goes from LuV to IV.

**Comment by bartimaeusnek** [comment]
moved thread to:
https://github.com/GTNewHorizons/NewHorizons/issues/4446
