### ISSUE TITLE
SFM Quests

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/NewHorizons#4427]
As many people know, SFM is quite powerful. However, it is extremely daunting for those who have never used it before. Couple this with a complete lack of any info about it online (outside of old videos) and it is tough to get into.

Additionally, there are many many items and blocks in GTNH, it would be simple to never even know of SFM because it is never mentioned in the quests. That combined with no info about it in game means many people wouldn't even know it exists.

A new SFM quest tab that opens after you build some IV circuits would be great.
Have a simple intro quest to build the inventory manager with some info on why SFM is useful. Then a quest for the inventory cables (since those two are the basis for everything else).

A followup quest for the redstone blocks. Those are pretty self explanatory.

Another for the inventory relays and what they do (it isn't explained in game otherwise).

A quest for the cable clusters and the camo. Explain how you have to insert the other blocks into it and that the basic cable cluster does not extend inventory functions.

Some additional thoughts that I posted in discord:
**Variables** - Declaration vs Standard
Global vs Local
When attempting to use a for each it is not clear that you need a blank variable

**Input/Ouput**
It is not at all clear that by input, they mean taking from that object and putting it into SFM. 
Vice versa for output.
I also found it strange that it is a two step process. I thought I was doing it wrong at first. It makes more sense now.
With regards to items - Precise detection vs NBT independant and all the other options

**Blocks**
What is the inventory relay, the Adv inventory relay?
What are the cable clusters for? How do you use them? What's the diff with the Adv one? How do you use camo?
Cable clusters were quite confusing at first. It is not clear that you have to "craft" what you want in one. 
**Camo** is also quite unclear. I assumed you could just apply it to a regular inventory cable or such, but nope, I assumed you could apply camo from a block by right clicking it. Nope... Given this, it is a extremely expensive block for any reasonable amount because you have to build a cable cluster or adv cable cluster in nearly every situation

Group node is also hard to figure out. It would require you to randomly create a group and then put it in and even then you may not realize what it is for.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3282

**Comment by richardhendricks** [comment]
Nori, check the linked tickets, I started some quests already.

**Comment by richardhendricks** [comment]
What are cable clusters and camo? I dont know what those are

**Comment by NoriSilverrage** [comment]
See, my point exactly.  Can't find any info on them. :)
Ok there are two types of clusters. Regular old cable cluster and adv. cable clusters.
They are the same except for one thing I'll mention later.
The basics of it is that it allows you to combine as many of the other cables together into one block. You could have a redstone receiver and emitter and a inventory relay all in one block.

The regular one has a downside, it doesn't also act as a inventory cable. The Adv. add this functionality.

Camo cable does what it sounds like. It allows you to camo the block as any other block. However, it is more powerful than simply hiding the cables. See you can put it in the same workflow as any other cable, updating the camouflage on the fly. You can even make each side different. There are other more adv camo blocks such as being able to set the inside face of the block as well (if you imitate glass for instance).

**Comment by richardhendricks** [comment]
Great info, thanks. Will add new quests.

**Comment by richardhendricks** [comment]
- [ ] inventory cable - allows access to inventory or cable attached
- [ ] inventory relay - wiki says 'interact with adjacent non-player entities' - wtf does that mean? animals?
- [ ] adv inventory relay - ? 
- [ ] item valve - ? 
- [ ] rapid item valve - ?
- [ ] block detector - ? 
- [ ] block gate - ? 
- [ ] cable cluster - The basics of it is that it allows you to combine as many of the other cables together into one block. You could have a redstone receiver and emitter and a inventory relay all in one block.

The regular one has a downside, it doesn't also act as a inventory cable. The Adv. add this functionality.
- [ ] advanced cable cluster - acts as inventory cable too
- [ ] sign updater

**Comment by 0lafe** [comment]
Valves are used to interact with the world. Can pull from them to pull items around then, or push to them for them to drop items in the direction they point. 3x3 around the block. Block detector iirc just works like a bud switch but kind of more customizable. Block gate places stuff in the world like formation plates. 

Inventory shits are to like interact with your invetory. I used one of them to input pearls to my inv while I spam clicked on the DE charm fuel add button. I think they do some other stuff, but idk haven't really used them. 

Sign updater does what it says. Updates signs. Basically turns signs into displays for shit. I used them to display when my assline was in manual or automatic mode.

**Comment by richardhendricks** [comment]
Thanks 0lafe.  Any ideas for quest rewards? Just more inventory cables?

**Comment by 0lafe** [comment]
Inventory cables are always nice, not much else helpful in sfm really. Could just do generic lootbags/tier rewards I guess.

**Comment by NoriSilverrage** [comment]
- The inventory cable extends the reach the main SFM block (Machine Inventory Manager) allowing it to access the inventory of any inventory capable block it touches. It also serves as a connection cable of sorts for all of the other cables. You will need a lot of these.
- The cable cluster allows you to combine as many of the other cables together into one block. You could have a redstone receiver and emitter and a inventory relay all in one block.
- The adv cable cluster also acts as a inventory cable
- The redstone emitter can emit redstone signals on each of it's 6 faces. The redstone can be set to any value, add, subtract and more.
- The redstone receiver reads redstone signals on each of it's 6 faces
- The block gate can break pickup, or place blocks
- The block detector detects block updates
- The item valve picks up items in the world
- The rapid item valve picks up items in the world but has no delay
- The inventory relay can access the inventory of non-stationary entities. For instance minecarts
- The advanced inventory relay can also access player inventories
- The sign updater allows dynamic sign updating
- The camouflage blocks allow the faces of blocks to be made to imitate any other block. This works in the full workflow and thus can be updated on the fly. Please note that this block is placed the same as all of SFM cables. It does not act as a inventory cable and thus will need to be in a adv cable cluster in many situations.

As for rewards, I would reward some of whatever the quest told them to build. Everything will be needed in quantity. 
For the inventory cable quest, I would award 16 of them (8 crafts). They are used to make all other cables and thus I would say it makes sense to award a decent amount.
Awarding a machine inventory manager for the quest that asks for one would be nice and would encourage more SFM usage.

**Comment by NoriSilverrage** [comment]
Variables - Declaration vs Standard
Declaration is simply creating a variable with eligible blocks in it. This allows easy updating of workflows. For instance you could have a variable that contains 2 chests. You use it in a nifty for each loop and later add another chest. Simply update the variable and the for each loop will start using it.

Standard variables are able to be inserted into the middle of a workflow (it has input/output) and thus can be modified on the run.

Please note that for each loops will require a empty variable to work with. This is listed as "Element" in the loop.
 
Global vs Local
Global will keep changes to a variable that are done in the workflow, whereas local keeps anything done local to that part of the workflow.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57499782-87cce300-72a6-11e9-910e-e8fb531e6808.png)
![image](https://user-images.githubusercontent.com/1214811/57499784-8ac7d380-72a6-11e9-9466-d1ab72fceec1.png)
![image](https://user-images.githubusercontent.com/1214811/57499789-8e5b5a80-72a6-11e9-9834-3a5b0f5b4b76.png)
![image](https://user-images.githubusercontent.com/1214811/57499798-93200e80-72a6-11e9-9f2f-1c974664c460.png)
![image](https://user-images.githubusercontent.com/1214811/57499800-974c2c00-72a6-11e9-8c32-fe250aa038be.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57499812-9fa46700-72a6-11e9-8449-6f9eb245f5a2.png)
![image](https://user-images.githubusercontent.com/1214811/57499819-a29f5780-72a6-11e9-80fa-bb0914f4afc6.png)
![image](https://user-images.githubusercontent.com/1214811/57499824-a6cb7500-72a6-11e9-9c39-7c5b5e93af30.png)
![image](https://user-images.githubusercontent.com/1214811/57499833-ac28bf80-72a6-11e9-9f65-11039f072343.png)
![image](https://user-images.githubusercontent.com/1214811/57499837-afbc4680-72a6-11e9-95aa-b2f88b3ed481.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57499848-b945ae80-72a6-11e9-9880-757056d07456.png)
![image](https://user-images.githubusercontent.com/1214811/57499853-bcd93580-72a6-11e9-9e7e-412d199b3f42.png)
![image](https://user-images.githubusercontent.com/1214811/57499854-bfd42600-72a6-11e9-9b88-12bc8e80b6ab.png)
![image](https://user-images.githubusercontent.com/1214811/57499856-c4004380-72a6-11e9-8cad-34f4c84f5041.png)
![image](https://user-images.githubusercontent.com/1214811/57499862-c82c6100-72a6-11e9-81a9-14d73a2b9587.png)
![image](https://user-images.githubusercontent.com/1214811/57499866-cbbfe800-72a6-11e9-9346-609cd951d8f1.png)
![image](https://user-images.githubusercontent.com/1214811/57499873-d37f8c80-72a6-11e9-92d5-100744992549.png)
![image](https://user-images.githubusercontent.com/1214811/57499877-d7abaa00-72a6-11e9-8338-19656aef4cf2.png)
![image](https://user-images.githubusercontent.com/1214811/57499881-dda18b00-72a6-11e9-94a4-9e4471422ff7.png)
