### ISSUE TITLE
Add way to obtain random Forestry Pollen from Villagers or other sources

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4428]
Currently, within Foresty, there is no way to obtain random pollen from Villagers as they don't even generate it at all. https://github.com/GTNewHorizons/ForestryMC/blob/GTNH-Fixes/src/main/java/forestry/arboriculture/VillageHandlerArboriculture.java

This makes obtaining Giant Sequoia saplings near impossible. As it is technically possible to obtain them from Forestry Village houses, the probability of obtaining one and finding a village with a forestry house is immeasurably tedious. Spoiler, you need 16 pollen to get the full capability of the Giant Sequoia

**Comment by mitchej123** [comment]
It looks like the pollen is only a 1.12 thing.  In 1.7.10 you need to find the actual sapling from a villager trade.

Still incredibly rare, and you need 16 saplings since it's 4x4.

**Comment by bartimaeusnek** [comment]
I suggest just adding a breeding recipe.

**Comment by richardhendricks** [comment]
Can we do that? Or would a coins recipe that takes a bunch of different saplings be better?

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/ForestryMC/pull/1

**Comment by 0lafe** [comment]
I'd say breeding is better as it builds on the mechanic for the tree system as a whole. It'll be just as difficult to get the sequoia with the top tier breeds or without if the only drop is rng villagers. If it needs top tier trees you can only make it once you've finished the whole point of tree breeding

**Comment by Hakameda** [comment]
You can buy all saplings from a villager, And it doesn't take that long. Its also not necessary but a reward for people who invest the time

**Comment by bartimaeusnek** [comment]
@Hakameda its a 0.75% chance per foresty tree villager to get the desired sapling...

**Comment by mitchej123** [comment]
Investing the time with a villager spawner, or tree breeding.  I like options.

**Comment by ScriptedPiky** [comment]
@Hakameda Also, a forestry villager is locked to THREE trades maximum. You can't just buy from one villager as the moment you see it has a different sapling, it's back to the grind that villager goes. See, a forestry villager cycles through three random trades in no particular order: A sapling (random gene), thirty-two planks (random gene), and a grafter (always the same type). The amount of saplings there are is 132, including the Giant Sequoia one. If a villager indefinitely traded until all possible genes of saplings and planks ran out and forced a Giant Sequoia version in the final version (if the RNG is that bad), then I'd be happy

**Comment by mitchej123** [comment]
We could backport some of the 1.12 mechanics.  

It goes something like:
1) wood, sapling
2) wood, proven grafter, pollen
3) wood, wood
3) pollen, sapling

You get two saplings, two pollens, and several wood to play with.

Thoughts?

**Comment by Hakameda** [comment]
I have on multiple occasions gotten all tree saplings, Including Giant Sequoia for a mega tree from villagers and generally takes less time then breeding them. There is nothing wrong with how it currently works and no need to make it easier. Once done its insanely good, That's how you progress should work time for rewards

**Comment by draknyte1** [comment]
Adding pollen for all trees doesn't make it any easier, but gives options.
Bart's breeding 'recipe' I don't think is required, which I stated during the original discussion on Discord.

Tree isn't meant to be breedable, nor does it need to be.
Not everything needs alternative ways to obtain it.. Because some folks enjoy showing their big dick energy from obtaining such things.

**Comment by 0lafe** [comment]
>Not everything needs alternative ways to obtain it..

But the current way is a forced alternate way. It's a tree, all trees are breedable and it's the best one. Why is it in no way related to the actual point of the tree system it ends?

**Comment by draknyte1** [comment]
Because that’s how the mod was designed?
Why do you feel the need to change mods and how their authors want them? 🤦‍♂

**Comment by 0lafe** [comment]
Because mod authors don't always get it 100% right. At least not for NH. There's a reason so many things have custom recipes

**Comment by Hakameda** [comment]
Its not breedable because it's a bonus not a requirment

**Comment by draknyte1** [comment]
> Because mod authors don't always get it 100% right

It's THEIR mod, they can't get it wrong.
If we add breeding recipes for this, lets add breeding recipes for all the special bees too then.

**Comment by bartimaeusnek** [comment]
But they can decide if they allow changes or not, they did a clear statement with their license, we decided to change it. Ill lock this thread now, its getting too hot-headed.
