### ISSUE TITLE
Fill in SFM and Open Computers wiki pages

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4431]
https://gtnh.miraheze.org/wiki/Steve%27s_Factory_Manager

https://gtnh.miraheze.org/wiki/Open_Computers

**Comment by repo-alt** [comment]
I may add some tutorial/example for OC but only after the update because OC/AE integration is broke on the server. I can probably illustrate robot farming now (in a few days, just got back from vacation, lots of work)
