### ISSUE TITLE
Check out low perf PC suggestions and OpenJava JRE JVM change, add to wiki if they work

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4434]
https://www.reddit.com/r/feedthebeast/comments/beyi1t/the_ultimate_guide_to_improving_performance_in/

- Look at suggested mods for 1.7.10 options? Born in a Barn?

https://www.reddit.com/r/feedthebeast/comments/as6p87/java_vms_and_you_how_to_reduce_your_ram_and_cpu/

Replace standard JVM with new JVM that provides better performance

**Comment by DoomSquirter** [comment]
be sure to read the entire post
down further they talk about primitive mobs and twilight forest issues, so possibly TF might have some issues but they were talking about 1.12 versions of the mods cause they were bringing up foamfix.

so basically, I guess what I'm saying is there's not going to be a "it loads, it's better, it's all good" kind of experience till time tells if there are wierd crashes/problems and they have to be separated as normal pack crashes vs what jre you're using.

**Comment by richardhendricks** [comment]
Batby says it "feels better" using the new JVM. Crashes less for him, for whatever reasons.

**Comment by bartimaeusnek** [comment]
significally less memory spikes and usage for me, way smoother gameplay with J9
