### ISSUE TITLE
Give the Vis Stone a purpose

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4435]
The Vis Stone is a common drop from Thaumcraft bags, but is pretty much useless since the wand recharge pedestal and vis relays are gated so far into the modpack. https://ftb.gamepedia.com/Vis_Stone_(Thaumcraft_4)

So, I was thinking we can add a GT assembler recipe to "recharge" the Vis Stone.  Idea is that the input side will ignore the NBT with vis levels, so it recharges any level of charge, and always requires all the primals as slivers. 
To keep players from cheesing it too much, make the recipe 
120s @ MV
5 of each primal sliver (Aer Aqua  Ignis Ordo Perditio Terra)

And anything else we want to add to balance, it, amber or quicksilver maybe.

**Comment by richardhendricks** [comment]
Would need to test with partiall charged stone to confirm recipe ignores input vis.

**Comment by Hakameda** [comment]
It would just add another non-useful thing to the stone nobody uses. Alot of eu and shards for 25 vis that can be obtained other ways

**Comment by bedrill64** [comment]
I'm good with MV recipe, if you want to be annoying add balanced shard to recipe, but I think its fine, requires sliver crafting, bunch of EU, I'd give it a shot.

**Comment by richardhendricks** [comment]
General consensus is that it would be better to throw it into lava and just make more iron or whatever wands.
