### ISSUE TITLE
Quest ID 241 Thaumcraft Cauldron Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4437]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Change quest to retrieval for cauldron.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57494372-842d6200-728e-11e9-817c-4213a0efb8dc.png)
