### ISSUE TITLE
Sensor (Tier 5)

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#444]
Recipe needs fixing, it requires the sensor(Tier 5) to craft itself

**Comment by Namikon** [comment]
I assume the recipes changed again? All patterns are invalid this morning

**Comment by Dream-Master** [comment]
Will look inside it. Yes and i change now the recipes again only for Tier 1 and 2.

**Comment by Teteros** [comment]
8b8ff25
