### ISSUE TITLE
MV-Quest "Silicon" (#746) weirdness

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4441]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
My private server.

#### Suggestions?
So, this quest suggests me to make Silicon Ingots right from Silicon Dust.
![image](https://user-images.githubusercontent.com/25156941/57552075-61c14480-7373-11e9-98db-753adb68e8da.png)
![image](https://user-images.githubusercontent.com/25156941/57552078-65ed6200-7373-11e9-95f9-52ca4aaf0b37.png)
And this process eats too much energy while it has alternative which is fully accessible at this stage.
What quest suggests me:
![image](https://user-images.githubusercontent.com/25156941/57552088-71408d80-7373-11e9-856a-4db7f6fd46ea.png)
Alternative (that is already in modpack), which was found by me:
![image](https://user-images.githubusercontent.com/25156941/57552190-ca102600-7373-11e9-9d49-9816a6cb42ce.png)
Here silicon is made from silicon dioxide and 2 carbon dust and costs much smaller amounts of energy. Carbon is easily obtained from electrolyzing (char)coal dust, and silicon dioxide is made from electrolyzing Flint Dust (It is just flint or sand).
So, why does quest suggest more difficult solution for making silicon ingots, when there is alternative, which is easier? :) Maybe it is worth correcting the method of obtaining silicon in the quest?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57579624-63b70080-7464-11e9-818c-399e5ff8c2c9.png)
