### ISSUE TITLE
Cable loss balance change

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4442]
With superconductors getting an easier recipe, this ticket is to discuss changing the default cable losses so they scale with tier. Currently cable losses are only range from 1-4 EU/m. With access to superconductors in easier recipes, we can discuss making that scale with tier.  A couple of proposals

Mine is to do 2^(tier-1), 0lafe is thinking 3^(tier-1). 
![image](https://user-images.githubusercontent.com/1214811/57557739-c8793a80-7340-11e9-9fcc-eae62fff48bc.png)

Potential issues
- Players long range infrastructure will be hindered. This will encourage players to shrink bases.
- Players factory infrastructure may begin undervolting if they are using long lines. As shown above, long lines at EV+ would be severely impacted. Potentially a player's base may be crippled and require temporary measures to get enough power to start production of superconductors.
- Players using kinetics as primary power sources will be severely impacted since those power sources have to travel the longest distances.

Mitigating factors
- Players can upvolt power using transformers.
- At EV microwave transmitters can be used for long distance point to point power.

Requirements before implementation
- [ ] Updated superconductor recipes
- [ ] Updated superconductor current capacities (4A minimum for 1x)
- [ ] Notification sent out to userbase
- [ ] Notification added to coremod motd
- [ ] At least 3 months between notification and release for players to prepare their bases

Vote Thumbs Down for no change, Laugh for moron version, Hooray for 0lafe version.

**Comment by DoomSquirter** [comment]
I'm ok if we get some balance out of this, that the intended reason for the nerf is to incentivize making SC's and that those are going to be affordable to do.  

With that said, I just hope that it's phased in, that you get new SC recipes and a few weeks later the cable nerfs hit to give ppl time to prepare.

Now, if the SC's are going to also have to have fluid to run them in addition to just making/placing them and having them attached to said fluid otherwise thing stops working, I am not a big fan at all.

**Comment by kekzdealer** [comment]
Those Olafe-lengths sure are something to behold. Not that the others are much better.
Microwaves to alleviate cable loss is insane.

**Comment by DoomSquirter** [comment]
ok I want to add:

I absolutely hate this statement; This will encourage players to shrink bases.
fuck that.  the whole idea is to spread out your base enough that FPS lag is avoided.  You are now trying to make it impossible to do that?  That shouldn't be a thing.  choose a different mission statement.

**Comment by kekzdealer** [comment]
Just use Mirowaves or lay down an AE cable :))))

**Comment by sleepylucy** [comment]
I want to have a nice spread out and beautiful base, not something wedged into a few chunks.
Adding changes that cut player freedom in planning their base is plain stupid

**Comment by NoriSilverrage** [comment]
Olafe's is a complete no go. That is far far too much losses. Moron's is better but still to much. If it was increased 2-4x it'd probably be pretty decent TBH. I ought to be able to go 128 tiles in IV before I can't power the tier recipe. LuV could stay at 128, or just be a 50% increase to 192. That would be quite resonable.

**Comment by mehdi2344** [comment]
God leave the cables as it is 1-8 eu/t per block is fine

**Comment by Anarack** [comment]
I would be ok with trying morons, but olaf's is not usable.

**Comment by Shattered2909** [comment]
Moron version is okay.

**Comment by chochem** [comment]
sorry, but this is a really bad proposal. Small bases are ugly, laggy, and polluted. Not something players should be pushed towards even more. The chunkloaders are bad enough already.

The only possible reason for such changes that I can see is that you want people to use fuels and produce energy in place whenever possible, but why do you want that?

**Comment by Hakameda** [comment]
no

**Comment by draknyte1** [comment]
What’s hilarious is standard GT has hardcore cable loss enabled by default for 5.07/5.08/some 5.09. Apparently 1/32nd loss/m/amp is too hard for GTNH. They don’t even get SCs. There’s a single tier of SC that transfers UHV/MAX and that’s it. 

Y’all soft. 


So far as SCs go, the current ones all suck in world and I’ll probably force them to be crafting only at some point so that the GT++ SC system can replace them.

**Comment by damug** [comment]
Personally, I think moron's is fun and 0lafe's more *fun*, if you want to run power a long distance, there are ways to do it while avoiding cable loss.

**Comment by mitchej123** [comment]
> Personally, I think moron's is fun and 0lafe's more _fun_, if you want to run power a long distance, there are ways to do it while avoiding cable loss.

s/fun/tedious/

**Comment by mitchej123** [comment]
One thing I could potentially get behind:

* IV and lower -- Leave as is
* Starting the tail end of LuV/start of ZPM - start increasing the cable loss per block. Change SuperConductors to be more of a challenge to use to send voltage long distances, but lossless.  Make them use increasingly more complex (note I said complex, not tedious) mechanics.  Liquid cooled perhaps, with increasing amounts of usage (start out small, 1 or 2 L per amp every few ticks, and scale up with tiers) for voltages, and more exotic liquids
** If we get really ambitious make cable loss a function of how far it's traveled... the farther it goes the more the loss -- thus short runs are almost lossless, but longer runs are more lossy.

**Comment by draknyte1** [comment]
> IV and lower -- Leave as is

> So far as SCs go, the current ones all suck in world and I’ll probably force them to be crafting only at some point so that the GT++ SC system can replace them.

Changing mechanics isn't really required, although I do like your first point.
My SC's are superior because the cables don't do anything. Conduction nodes (The Tile you pump power into to push it into your SC network) do all the handling, since all nodes on a 'network' are linked, you only ever need to manage the fluid in one. Bonus of this is with some refinement, It makes it possible to have power move around without loaded chunks cause the cables do nothing.

**Comment by FlandreS** [comment]
I don't see how any of this improves gameplay, bases, or even realism if that's even a consideration anymore. Wiring and machines already heavily incentivize moving fuels instead of moving power. If the SC's are considered too cheap now, that's the problem, not the current wire losses.

**Comment by chochem** [comment]
> I don't see how any of this improves gameplay, bases, or even realism

agreed. If I remember my physics correctly, power loss is only dependent on amperage (and resistance) but is independent of voltage, so precisely like the system we have. Scaling it with some strange power law regarding voltage makes no sense whatsoever.

As there really seems to be a desire among devs to nerf cables, how about the following:

Make sure the option in each tier with only 1eu/(A*m*t) loss is a bit more expensive. In particular, silver and aluminum are really cheap for being the best option in HV/EV.

**Comment by combusterf** [comment]
If anything, transformers should be a readily available option, should be worth it, i.e higher tiers should be craftable one or two tiers before, and any increase in resistance should be uneven. In addition, there should be a choice between cheap and quality cables.

As a counterproposal: resistance=tier for the affordable cable, and from there x0.5 for expensive&quality, x2 for cheap and >= x3 for EBF coil material. 2A versions or better can then be used as extra tweaking on relative rarity factors.

**Comment by Hakameda** [comment]
Or change nothing as it's fine as is
