### ISSUE TITLE
QoL Wire Crafting

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/NewHorizons#4443]
At present (V2.0.7.0), it is possible to craft 
2x wires from two 1x wires
4x wires from two 2x wires OR four 1x wires
8x wires from two 4x wires OR eight 1x wires
12x wires from a 8x wire  and a 4x wire
16x wires from two 8x wires OR a 12x wire and a 4x wire

I'm suggesting, for convenience sake, add more recipes to allow more combinations of bundled wires to be made in less steps, for example, 8x wires made from four 2x. The specific example that comes to mind is 16x from four 4x wires.

**Comment by bartimaeusnek** [comment]
This would increase loads times, since every cable would get a lot of new recipes. Im against this.

**Comment by Zoko061602** [comment]
What about adding a custom recipe that checks if wires are compatible and counts their thickness.
That would reduce the number of recipes for just one for all of them.

**Comment by Impos913** [comment]
Also i think there should be 9x cables/wires because of 9 slot battery buffers.

**Comment by DietmarKracht** [comment]
Why would we need changes to wires? If you have setup autocrafting for wires it takes 2 steps to make a 16x wire (16 1x into 2 8x then into 1 16x) also 2 steps for 12x which is definitely OK. If you are not fine with handcraft ING wires we also have the assembly line recipes
