### ISSUE TITLE
GT++ He prime fusion skip

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4444]
#### Which modpack version are you using?
2.0.7

#### What do you suggest instead/what changes do you propose?

After a ++ update to rare Earth sifting, small block fusion is now pre normal fusion. It's fairly cheap in cost comparatively, with the only LuV cost being 32 field gens. It's meant as an alternative or something, being 16x slower but doing the same outputs. Specifically this means you can make europium fairly early in LuV, and doesn't need a reactor. Makes zpm a fair amount easier with this, as well as other europium gated stuff. 

I'm posting this here instead of on ++ because alk said this is working as intended and doesn't wish to change it. So I'm proposing we either change the recipe to the prime to need europium, or somehow try to change the rare Earth outputs to remove Gd. Other options too I guess, but these seem like the easiest.

**Comment by draknyte1** [comment]
You forget to mention it also takes Tier+2 power, so it’s effectively unusable due to hatch nerfs. You can’t use it effectively at all until post-fusion.

**Comment by 0lafe** [comment]
They don't use hatches though for power input, and the power it needs for europium crafting is less than you really need to make fusion. It's not power viable, which the multi has over it. For europium production in LuV it's sort of easier than the multi for small amounts, which is all you really need to tier skip the reactor.

**Comment by DietmarKracht** [comment]
It takes lafium compound which is zpm iirc

**Comment by 0lafe** [comment]
![2019-05-12_02 02 49](https://user-images.githubusercontent.com/21280852/57578430-539a2380-745a-11e9-9215-912f6c252845.png)
:(
