### ISSUE TITLE
TiC "Broken" item won't self repair when "Ball of Moss" is applied.

### ISSUE THREAD

**Issue by mcwnuq** [GTNewHorizons/NewHorizons#4447]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
#
#### What happend instead? (Attach screenshots if needed)
The durability of the tool goes up but tool remain "Broken".
#

**Comment by Dream-Master** [comment]
If you broke a tool ball of moss cant repair it. Let at least 1 durabilty point on the tool.

**Comment by mcwnuq** [comment]
it will slowly increasing durability points but... i've tested it

**Comment by mcwnuq** [comment]
![image](https://user-images.githubusercontent.com/11915730/57575371-6a844a00-7449-11e9-92c0-1c55ef1b70fb.png)
and after some time...
![image](https://user-images.githubusercontent.com/11915730/57575373-75d77580-7449-11e9-81fa-2c55aae315c7.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57579635-a082f780-7464-11e9-9c64-e1b7810cbcf8.png)
