### ISSUE TITLE
ProjectRed ore generation

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#445]
ProjectRed configs now use new design ("World Gen" instead of "world generation").
These configs got regenerated and now ProjectRed ores spawn in the world, along with Volcanos.

**Comment by Dream-Master** [comment]
ok i have to check

**Comment by Dream-Master** [comment]
Thanks for let me know.

**Comment by Teteros** [comment]
Fresh config regenerated in https://github.com/GTNewHorizons/NewHorizons/commit/242be105e3587a4ff5e038dae3e75c4bfce70936
