### ISSUE TITLE
Uranium Rod vs MOX Rod uranium consumption

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#4452]
#### Which modpack version are you using?
.7.0
#
#### What do you suggest instead/what changes do you propose?

So right now, uranium rods take 6 u238 to make, as well as 3 nuggets of u235 (you can make 7 235 nuggets from 1 u238 via thaumcraft, so going that route it's 6.42 u238 per rod). They then return 4 uranium after running for 20k seconds. Mox rods, on the other hand, also take 6 uranium to make, but they return no uranium and only run for 10k seconds. The result of this is that running mox consumes 5-6 times as much uranium as uranium rods, but only provides 2.2x power (default ic2 is 4.4x power, but not here). This incentivizes players to use more reactors with uranium rods compared to using mox rods, which to me makes no sense because mox rods are supposed to be more technologically advanced and using mox rods requires you to either run a reactor for a very long time or advance to t3 planets in order to get the requisite plutonium. The reprocessing cycle with mox is also a more efficient way to use uranium in real life.

To remedy this, I suggest we add 3 or 4 ic2 uranium 238s to the output of mox rod recycling. This would allow use of mox fuel to be more uranium efficient, about on par with or a bit more than uranium rods, which is both more realistic and good for gameplay as it incentivizes switching to mox.

One issue with that change is that we are already using all of the thermal centrifuge's output slots for the current recycling recipe. While it would be possible to add more slots to the thermal centrifuge for this, I would suggest we just add the uranium as an item and make the iron it currently outputs a fluid instead. So the recipes would be:

1 depleted mox rod -> 1 tiny pile plutonium (ic2), 3 big plutonium (ic2), 4 uranium (ic2), 144L molten iron
1 depleted dual mox rod -> 2 tiny piles plutonium (ic2), 6 big plutonium (ic2), 8 uranium (ic2), 432L molten iron
1 depleted quad mox rod -> 4 tiny piles plutonium (ic2), 12 big plutonium (ic2), 16 uranium (ic2), 864L molten iron

**Comment by draknyte1** [comment]
If there’s ever an issue with slots, the recipes a still doable in a multi.. since they don’t have slot limits.
