### ISSUE TITLE
Forestry Fermenter recipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4453]
Forestry Fermenter has a bunch of dual recipes with different output amounts.  We need to fix this.

Example: 
Plant balls 90 L or 125 L
![image](https://user-images.githubusercontent.com/1214811/57587258-f0df7100-74c7-11e9-963b-9f167c7b9ffc.png)
![image](https://user-images.githubusercontent.com/1214811/57587259-f50b8e80-74c7-11e9-8575-54573e0ee0d4.png)

Dark Oak 50L or 75L 
![image](https://user-images.githubusercontent.com/1214811/57587275-3e5bde00-74c8-11e9-8374-fbf34c752d35.png)
![image](https://user-images.githubusercontent.com/1214811/57587277-41ef6500-74c8-11e9-8f95-446ed2a202bb.png)

**Comment by sthegreat** [comment]
This is intended. You get extra biomass when you input fruit juice or honey into the fermenter instead of just water.

**Comment by richardhendricks** [comment]
TIL  :D
