### ISSUE TITLE
Kill all the things: More 'Time to kill' quests

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4457]
New repeated mob quests that **do not** apply to the 'Time to kill (Nether)' quest. These are even more optional but can be worthwhile for the player if they choose to fight these types of mobs.

**Time to kill (Dire Wolf)**
These kinds of wolves do not take kindly to you marching close to them or offering them bones! Neutral at first, but extremely hostile upon approaching close to them and dangerous. They'll rip the bones right off ya! Found within snowy forest biomes.

Mobs to kill: 10
Offerings: Quarter Heart, 25 Coin "The Dark Wizard 1", 8 Coin "The Survivor 10", 8 Coin "The Explorer 10", 25 Coin "The Technician 1"
Unlocked: After the 'SO... TIRED...MUST...SLEEP...' quest in Tier 0.5 - Stone Age

**Time to kill (Hell Hound)**
Aggressive and can apply fire, although not a fast enemy either. Recommendation, avoid melee combat and offerings of bones.

Mobs to kill: 15
Offerings: Quarter Heart, 35 Coin "The Dark Wizard 1", 35 Coin "The Survivor 1", 35 Coin "The Explorer, 25 Coin "The Technician 1"
Unlocked: After the 'THE NETHER' quest in Tier 1 - Steam

**Time to kill (Slime)** (Also applies to all sizes)
Sticky and bouncy! Now in many variations.

Mobs to kill: 40
Offerings: Quarter Heart, 5 Coin "Blacksmith 10", 5 Coin "The Chemist 10", 3 Coin "The Dark Wizard 10"
Unlocked: After the 'SO... TIRED...MUST...SLEEP...' quest in Tier 0.5 - Stone Age

**Time to kill (Magma Cube)** (Also applies to all sizes)
Now a Hell version of your slime! Always applies with Infernal status.

Mobs to kill: 20
Offerings: Quarter Heart, 7 Coin "Blacksmith 10", 7 Coin "The Chemist 10", 5 Coin "The Dark Wizard 10"
Unlocked: After the 'THE NETHER' quest in Tier 1 - Steam

**Time to kill (Silverfish)**
Be wary, they like to disguise and clone themselves in stone-related blocks! (Applies to Vanilla blocks only) Can be found within dungeons. Can also be found in Drowning Creeper spawned cobblestone blocks.

Mobs to kill: 15
Offerings: Quarter Heart, 5 Coin "Blacksmith 10", 5 Coin "The Chemist 10", 5 Coin "The Dark Wizard 10", 25 Coin "The Technician 1"
Unlocked: After the 'SO... TIRED...MUST...SLEEP...' quest in Tier 0.5 - Stone Age

**Time to kill (Bat)**
...Did you expect a raid boss of some kind? If you count the number of bats you'll encounter and kill, then probably yes.

Mobs to kill: 250
Offers: 16 Compressed Salt Blocks, 64 Pufferfish, 1 Coin "The Dark Wizard 100"
Unlocked: After the 'SO... TIRED...MUST...SLEEP...' quest in Tier 0.5 - Stone Age

**Comment by Hakameda** [comment]
You should probably change ticket to I need more coins and salt

**Comment by richardhendricks** [comment]
Kill 250 bats & 1 TC firebat
![image](https://user-images.githubusercontent.com/1214811/57897005-172f4480-7819-11e9-9490-0326709042dd.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57898801-24036680-7820-11e9-9874-b5ca1074f51c.png)
![image](https://user-images.githubusercontent.com/1214811/57898808-2796ed80-7820-11e9-8031-fc27ad9cb147.png)
![image](https://user-images.githubusercontent.com/1214811/57898812-2b2a7480-7820-11e9-8d17-8ec6715cb0ce.png)
![image](https://user-images.githubusercontent.com/1214811/57898822-34b3dc80-7820-11e9-9830-157c11489e55.png)
![image](https://user-images.githubusercontent.com/1214811/57898824-38dffa00-7820-11e9-8bc1-8c3db0aae55e.png)
![image](https://user-images.githubusercontent.com/1214811/57898828-3da4ae00-7820-11e9-9b79-be123301ebd0.png)

**Comment by Impos913** [comment]
There are lots of twilight forest mobs and I think some of them should have 'Time to kill' quests.
Like Kobold, Redcap, Death Tome, Minotaur, Fire Bettle, Slime Bettle, Pinch Bettle (Maybe all bettles can be in the same quest), Goblin Knight, Helmet Crab and those little ghasts at ur-ghast tower.
Maybe put the mobs that are found in same place to one multi-task quest.
