### ISSUE TITLE
Add more Thaumcraft quests

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4459]
for moron

https://ftbwiki.org/Rosa_Mysteria_Sprout

they will need to research the thaum bases rosa mysteria as well as the blocks they get placed on... (crystal blocks).

**Comment by richardhendricks** [comment]
Node manipulator questline looks interesting too.

**Comment by richardhendricks** [comment]
Rosa Mysteria added to Useful Plants quest
![image](https://user-images.githubusercontent.com/1214811/57742230-f08cd480-7685-11e9-9205-5231d9223ccd.png)
![image](https://user-images.githubusercontent.com/1214811/57744297-44032080-768e-11e9-9a5a-974a0cb1b317.png)
![image](https://user-images.githubusercontent.com/1214811/57744313-57ae8700-768e-11e9-8968-8ced0b688dd7.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57744983-f2a86080-7690-11e9-839a-bb01a0ed7cc9.png)
