### ISSUE TITLE
Dehydrated food

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#446]
Can you switch the recipe (Can of Food) so each needs 2 items to fill a can. As that is how much hunger it provides

**Comment by Teteros** [comment]
Were you eating the Melon can of food? That one seems to replenish 2, for reference:
Dehydrated apples 4
Dehydrated carrots 4
Dehydrated melons 2
Dehydrated potatoes 1
...and so from that the recipes are more or less right, considering how much is replenished from the original food.

**Comment by Drobac** [comment]
its a Drobac derp then, thanks for the extra info
