### ISSUE TITLE
Stone Pressure Plate -> GT/NH Stone Plate

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4463]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Change the following recipes to use GT/NH Stone Plate instead of Stone Pressure Plate:

- [ ] Redstone Comparator 404
- [ ] Redstone Repeater 356
- [ ] Armor Stand 1743

Add recipe (maybe):

- [ ] Pulverize/Macerate - 1x GT/NH Stone Plate -> 1x Stone Dust

**Comment by Dream-Master** [comment]
I add core mod stone plate before they where in gt. Arent they ordicted ?

**Comment by shawnbyday** [comment]
> I add core mod stone plate before they where in gt. Arent they ordicted ?

Yes they are in the oredict. I was suggesting changing the recipes from using pressure plates to using stone plates instead.
