### ISSUE TITLE
MBGA (Make Bees Great Again)

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4464]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Feel free to assign this to me for now. Just want a place to start figuring out how to make bees worth doing again.

**Comment by 0lafe** [comment]
oil bees should be better maybe

**Comment by Hakameda** [comment]
Bees are fine

**Comment by draknyte1** [comment]
They were changed to be online with Crops and Dream had wanted to make this adjustment for years. It won’t change, it will only ever be refined.

**Comment by shawnbyday** [comment]
Bees and crops when it comes to ore production are basically useless.

**Comment by 0lafe** [comment]
In fabrication not really, but theyre great for boosting outputs

**Comment by shawnbyday** [comment]
Faster to just go mine.

**Comment by Hakameda** [comment]
Then go mine, Bees are fine

**Comment by shawnbyday** [comment]
Ok, thanks.

**Comment by Dream-Master** [comment]
If bees need a buff/nerf make a new ticket with explicit wishes and we can discuss about it.
@shawnbyday 
thanks

**Comment by shawnbyday** [comment]
@Dream-Master yea that's what this ticket was going to BEE about but I didn't even get a chance to post any edits to it before I was torn limb from limb lol. @Hakameda all in good fun. I'm getting ready to start working on bees within a week on this version and I'll come back after I get into them a ways with specific feedback.

**Comment by Hakameda** [comment]
Un-nerfing gt++ frames would make bees better

**Comment by richardhendricks** [comment]
No.

**Comment by Hakameda** [comment]
They are useless ATM, hasn't that been your thing this week?

**Comment by richardhendricks** [comment]
The frames are way OP where they were before, and ridiculously OP with the Thaumic Restorer. If bees need fixing, propose something else.

**Comment by richardhendricks** [comment]
?
![image](https://user-images.githubusercontent.com/1214811/57725705-5e6bd880-7653-11e9-87c1-a94f979502de.png)

**Comment by Hakameda** [comment]
They should remain at 3 uses and not repairable. But they should use uranium not plutonium. By the time you get plutonium, you already have better options

**Comment by Hakameda** [comment]
The old recipe was uranium

**Comment by richardhendricks** [comment]
Insta-breeding the bees is OP even with uranium. U is achievable at LV with crops in LV.

**Comment by sthegreat** [comment]
Maybe switching them from Pu 241 to Pu 239 could be a decent idea, making them cheaper but same gating. But honestly they seem fine as-is. What better options are available at that tier, anyway?

**Comment by Hakameda** [comment]
Alvearies

**Comment by Hakameda** [comment]
And before that

**Comment by DietmarKracht** [comment]
I think the uum autoclave processing times should be lowered. currently it is faster to use bee combs for existing crushed ore multiplication than using them to create ore from uum. Maybe increase the amount of uum but lower the processing time.

**Comment by Hakameda** [comment]
That's actually a fair point too, the eu cost would be better on the uu itself then the clave. Then you pick what you want from.your uu supply
