### ISSUE TITLE
Remove 1 copy of fortune 3 from quests, other related things

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4473]
Remove 1 copy of the fortune 3 book, look at adding information to mobfarming on diamond spikes.

Add info on options to deal with removing unwanted enchants on books using division sigil, can use unactivated ones from chests and wither kill

Add info or quest on disenchantment table, add pointers (pretty high tier, but doable through twilight forest amethyst)

leave 1 copy of fortune 3 at end of printing press quests

**Comment by richardhendricks** [comment]
thing is, if you have an enchanting table, you really only need to explore thaum just a teeny bit and get to the enchanted cloth research which opens the wiping one

**Comment by shawnbyday** [comment]
Sort of related but do we have quests that explain enchantment duplication with the press from bibliocraft?

**Comment by richardhendricks** [comment]
Added them a few days ago

**Comment by richardhendricks** [comment]
Fortune 3 book changed to fortune 1 for the printing press quest.
Fortune 3 book for skystone changed to fortune 2
Found a couple of enchanted books (no fortune) in a roguelike
Fortune I dropped by Brutish Zombie from a Thaumcraft Barrow (probably Alk's code)

**Comment by richardhendricks** [comment]
Sigil doesn't work correctly with books.
Spellbinding cloth doesn't work on books, and removes *all* enchantments anyways
Disenchanting table requires 75 vis wand.
![image](https://user-images.githubusercontent.com/1214811/57749050-1922c780-76a2-11e9-8949-a9e35e0ec911.png)
