### ISSUE TITLE
Element 24 Cr

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4475]
#### Which modpack version are you using?
2.0.7.w/e
#

#### What do you suggest instead/what changes do you propose?

Chrome is the name of the pink Cr element, but it's actually chromium. We changed phosphorus, should chromium be next? Probably fucks ore dict, unless we just keep the chrome ore tag

**Comment by Anarack** [comment]
You can change the localized name without having the change the ore dict, but I don't really see the point of the name change as its been like this the entire lifespan of gregtech.

**Comment by 0lafe** [comment]
It's also been wrong the whole lifespan of GT 🤔

**Comment by draknyte1** [comment]
Lots of other games get it wrong too, so there's consistency in that sense.
