### ISSUE TITLE
The cobblestone boulders that generates on the Overworld.

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#4483]
Ticket about disabling the surface cobblestone rocks.
https://github.com/GTNewHorizons/NewHorizons/blob/635179d931590d26b9f76d16d901ad24c9bf18f0/config/RWG.cfg#L37

Thumbs down to keep setting.
Thumbs up to change it to false.

Edit: I am speaking about the Cobblestone boulders that dots the overworld, pictures down below.

**Comment by kekzdealer** [comment]
Weren't the opinions in the other thread clear enough? ^^

**Comment by richardhendricks** [comment]
No, the other thread options were about if it should block release. This thread is if it should be changed.

**Comment by richardhendricks** [comment]
Another option I can implement is allowing GT stones and/or ores to replace cobblestone. This would allow small ores to take their place if RNGesus allows it.

**Comment by kekzdealer** [comment]
![image](https://user-images.githubusercontent.com/31353359/57785927-e4ab1c00-7732-11e9-8468-a35e449b2b37.png)
Wouldn't that look far far messier?

**Comment by richardhendricks** [comment]
I don't understand your point?  There's only 4 small ores there. And the current worldgen allows GT stones to replace hardened clays. I don't think it would add all that much, really.

**Comment by kekzdealer** [comment]
Doesn't GT stone include the coloured granite versions too? I figured that would result in oddly coloured sprinkles all over mountains.

**Comment by richardhendricks** [comment]
Yes, it already does this now. Try finding a new worldgen mountain.  I personally like the look. The grey clays hid ores too much IMO, with the GT stones overriding clay it lets you see what's in the mountain better.

Summary:
- GT stones (basalt, marble, red/black granties) currently replace hardened clay (found in mesa and mountainsides and hot deserts). This is done before oregen so ores can spawn in them.

Proposal:
- Remove cobble boulder generation
- Allow GT stones and ores to replace cobblestone. This would make cobble on the sides of mountains potentially turn into GT stones and ore, along with cobble boulders (if their generation happens after GT, would need to test) and potentially villager structures.

**Comment by kekzdealer** [comment]
We reset our OW after 7.0 and are living inside one of those mountains :D
If the result looks like this I'm fine with it:
![image](https://user-images.githubusercontent.com/31353359/57786845-8717cf00-7734-11e9-91d8-92550eec069c.png)
I just had that mislead thought that it would *only* replace the cobble...which would look odd. Those larger patches I do like a lot. 
I'm still not sure why above ground cobble should disappear. If you want a clean area, just landscape it. Like you do with everything else. We had to clear this whole valley from those one-log scrubs when building our farming valley. Even though it was annoying and took forever, I wouldn't like to see them disappear completely. 
![image](https://user-images.githubusercontent.com/31353359/57787180-30f75b80-7735-11e9-99cd-f92f987b4b78.png)

**Comment by kekzdealer** [comment]
Moron corrected me that this is not about cobble on mountains, but the boulders on open fields instead. Those are obviously something different, but I still stand by the point I'm making in the second half of my previous post.

**Comment by draknyte1** [comment]
They’re ugly and tend to fill magic forests, never knew it was a config option.

**Comment by kekzdealer** [comment]
You dislike RWG to the point where you asked us to make a second overworld with BoP gen just for your base. 
![image](https://user-images.githubusercontent.com/31353359/57790854-dca3aa00-773b-11e9-81a5-4fd58fe5f0fa.png)

**Comment by richardhendricks** [comment]
@Ethryan Please take some pics of areas with the boulders and the same area with a fresh world after disabling the option.

**Comment by bHXDgiuMa5yLHyC8** [comment]
I'm curious about why you use RWG and not RTG?

**Comment by Ethryan** [comment]
![image](https://user-images.githubusercontent.com/3237986/57808503-c6114900-7763-11e9-9b03-1cd458dcb50a.png)
With the config enabled
![image](https://user-images.githubusercontent.com/3237986/57809563-f954d780-7765-11e9-89ad-af91d7b56b97.png)
Same spot with the config disabled, notice the missing eyesore of a boulder?
That is what this config option does, nothing else.

**Comment by Dream-Master** [comment]
I like the boulders make terrain more interesting. If somone code better boulders i am ok with it too.

**Comment by Dream-Master** [comment]
RWG terrain is much better coded that RTG terrain. Sad to see the dev is gone but if he finsih the development of rwg add oceans and other nice biomes (+ more mod support) rwg would 1000 times better than rtg.

**Comment by richardhendricks** [comment]
Is the terraingen open source? Also, what do you think about GT replacing cobblestone with marble/granite/etc if the seed say to place it? At least they would be more interesting that just cobble garbage.

**Comment by Dream-Master** [comment]
Yes the source is n git so far ik not sure if open lincense or not.

**Comment by Ethryan** [comment]
https://github.com/Ted80-Minecraft-Mods/Realistic-World-Gen/issues/14
<-- License

**Comment by richardhendricks** [comment]
And notice that he quit developing right after that was pointed out. Real shame.

**Comment by Hakameda** [comment]
I like big rock

**Comment by richardhendricks** [comment]
![2019-05-15_19 27 22](https://user-images.githubusercontent.com/1214811/57817953-8a688600-7747-11e9-9ba1-ea6eb122fef6.png)
This is probably a better example since there is no snow to cover them up

**Comment by Dream-Master** [comment]
i like them so i not disabled it. People dont like it may use rtg mod.

**Comment by richardhendricks** [comment]
GT stones will replace cobble.  And it is possible for GT ores to generate in the replaced areas.
![2019-05-18_12 26 19](https://user-images.githubusercontent.com/1214811/57973051-3dafc580-7968-11e9-89f6-58087128ccbe.png)
![2019-05-18_12 26 25](https://user-images.githubusercontent.com/1214811/57973052-3dafc580-7968-11e9-8f08-a74606028c59.png)

**Comment by Dream-Master** [comment]
@richardhendricks are you add this ?

**Comment by richardhendricks** [comment]
yes it was added already.

**Comment by Dream-Master** [comment]
ok
