### ISSUE TITLE
Ridiculously high cost for Real Ultimate Battery

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4484]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
The cost for the real ultimate battery is way to high imho. Lets take a look at it:

1 Real Ultimate Battery takes 8 Ultimate Batteries (UV Voltage).
1 Ultimate Battery takes 8 Energy Cluster (UV Voltage).
1 Energy Cluster takes 8 Energy Modules (ZPM Voltage).
1 Energy Module takes 8 Lapotronic Energy Cluster (LuV Voltage).

So that makes 1 Real Ultimate Battery cost 8x8x8x8=4096=64 Stacks of LuV Clusters.
That means one has to make 4096 Stacks of High Power IC which is more than 1k Stacks of Indium dust. This is just to meantion one part of the battery. 

One can exchange the LuV Cluster recipe from assembly line to circuit assembler (IV Cluster) which mean another 8 IV Cluster for 1 LuV Cluster so that is 32k IV Clusters.

**Comment by draknyte1** [comment]
Fairly sure the cost is there simply for epeen. 
Making this gives you big dick energy. 

Sometimes cost isn’t meant to be worth it; beyond bragging rights.

**Comment by 0lafe** [comment]
Cost is totally worth it tho. It's infinite storage at UMV, meaning each really ultimate can input 256x the rate of a normal ultimate. Considering storage doesn't matter as both are infinite, input rate is what causes you to make more. With the really ultimate equating to 256 normals, only asking for 8 to craft it is a steal.
