### ISSUE TITLE
Hold off on removal of bees script till maybe 8.x

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/NewHorizons#4485]
with the upcoming update close to dropping, realized that some ppl might be on 5.2 (prospercraft?) and waiting on stable update to proceed.  they wouldn't have had 7.0 to fix all the bees, etc.  

releasing 7.3 with the script gone to convert bees will basically cause everyone's bees to disappear.

suggestion then to hold off till 8.x or something to actually implement that removal script instead to give ppl time to update and convert bees.

**Comment by Dream-Master** [comment]
yea will put back gendustry bees and combs to gendustry config with no breading options back.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/ede30cbcd17a2a52ce9962d63f059c4e59a0f477#diff-82eef4018466612ba7931bf101f11380
