### ISSUE TITLE
Tinker's Construct Materials rebalance

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4486]
#### Which modpack version are you using?
2.0.7.0
#
####
materials like VS is way too good for when you unlock it but tungsten is pretty bad compared to materials from the same tier

proposed change:
vanadium steel 720  mining level 4 speed 12
tungsten 1920   5    16
tungstencarbide 1440    5    20
tungsten steel 2880    5    14

**Comment by richardhendricks** [comment]
Current stats for common stuff

Alumite | 413 | 5 | 7.9
Ardite | 455 | 6 | 8
Damascus Steel | 1500 | 4 | 8
Manyullyn | 900 | 8 | 9
Cobalt | 600 | 7 | 11
Stainless Steel | 987 | 5 | 12
Energetic Alloy | 1805 | 4 | 12
Knightmetal | 1021 | 4 | 13
Black Steel | 576 | 4 | 14
Tungstencarbide | 960 | 5 | 14
Meteoric Steel | 1480 | 5 | 16.2
Vibrant Alloy | 3036 | 5 | 18
Vanadiumsteel | 1440 | 4 | 18
Perditio | 48 | 5 | 32
Shadow | 6144 | 5 | 32
Oriharukon | 7680 | 6 | 32

**Comment by Hakameda** [comment]
Isn't tungsten super brittle?

**Comment by richardhendricks** [comment]
The free element is remarkable for its robustness, especially the fact that it has the highest melting point of all the elements discovered, melting at 3422 °C (6192 °F, 3695 K). It also has the highest boiling point, at 5930 °C (10706 °F, 6203 K).[11] Its density is 19.3 times that of water, comparable to that of uranium and gold, and much higher (about 1.7 times) than that of lead.[12] Polycrystalline tungsten is an intrinsically brittle[13][14] and hard material (under standard conditions, when uncombined), making it difficult to work. However, pure single-crystalline tungsten is more ductile and can be cut with a hard-steel hacksaw.[15]

Tungsten's many alloys have numerous applications, including incandescent light bulb filaments, X-ray tubes (as both the filament and target), electrodes in gas tungsten arc welding, superalloys, and radiation shielding. Tungsten's hardness and high density give it military applications in penetrating projectiles. Tungsten compounds are also often used as industrial catalysts.

**Comment by Scottishprog** [comment]
Not particularly interested in having V. steel nerfed for non-tinkers' uses. Used in both my bolts, and my electric screwdriver/wrench tips.  IF this change only effects tinkers tools, then carry on.

**Comment by NoriSilverrage** [comment]
I'd leave VS durability and just reduce mining speed. 18 is really high for it's tier, however I will say that because of it's low mining level, I never used it for my mining stuff, only for weapons and tools.

My hammer and pickaxe stayed on cobalt until I was able to upgrade to Oriharukon.

One thing that should be buffed is Manyullyn. Alloys are usually better than the base, but if you were using cobalt, Manyullyn is a downgrade. You lose mining speed and reinforced II and all you gain is 1 mining level (which is useless anyway) and 300 durability.
