### ISSUE TITLE
Worldgeneration.cfg changes not respected in game

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4489]
Modpack version 2.0.5.1

#### If in multiplayer; On which server does this happen? 
This is SSP/SMP related
#
#### What did you try to do, and what did you expect to happen?
I've made some changes to the config/gregtech/worldgeneration.cfg in order to make some ores more plentiful and spawn in bigger veins and in different dimensions. None of the changes made in the config are respected in game. For example, let's take titanium, it generates in a vein together with chrome and some other ores. The vein is named "titaniumchrome", and here it is in the worldgeneration.cfg

```
            titaniumchrome {
                I:Density_3=3
                B:EndAsteroid_false=false
                B:GalacticraftCore_Moon_false=true
                B:GalacticraftMars_Asteroids_false=true
                B:GalacticraftMars_Mars_false=false
                B:GalaxySpace_BarnardC_false=false
                B:GalaxySpace_BarnardE_false=false
                B:GalaxySpace_BarnardF_false=false
                B:GalaxySpace_Callisto_false=true
                B:GalaxySpace_CentauriA_false=false
                B:GalaxySpace_Ceres_false=false
                B:GalaxySpace_Deimos_false=false
                B:GalaxySpace_Enceladus_false=false
                B:GalaxySpace_Europa_false=false
                B:GalaxySpace_Ganymede_false=true
                B:GalaxySpace_Haumea_false=false
                B:GalaxySpace_Io_false=false
                B:GalaxySpace_Kuiperbelt_false=false
                B:GalaxySpace_MakeMake_false=false
                B:GalaxySpace_Mercury_false=true
                B:GalaxySpace_Miranda_false=true
                B:GalaxySpace_Oberon_false=false
                B:GalaxySpace_Phobos_false=false
                B:GalaxySpace_Pluto_false=true
                B:GalaxySpace_Proteus_false=true
                B:GalaxySpace_TcetiE_false=true
                B:GalaxySpace_Titan_false=true
                B:GalaxySpace_Triton_false=false
                B:GalaxySpace_VegaB_false=false
                B:GalaxySpace_Venus_false=false
                I:MaxHeight_70=70
                I:MinHeight_10=10
                B:Nether_false=false
                I:OrePrimaryLayer_28=28
                I:OreSecondaryLayer_825=825
                I:OreSporadiclyInbetween_842=842
                I:OreSporaticlyAround_925=925
                B:Overworld_false=false
                I:RandomWeight_16=16
                S:RestrictToBiomeName_None=None
                I:Size_16=16
                B:TheEnd_false=false
                B:"Twilight Forest_false"=false
                B:Underdark_false=false
                B:Vanilla_EndAsteroids_false=false
            }
```
This particular vein contains Titanium, Chromite, Uvarovite and Perlite. I've made some example changes to it to show that none of the settings are respected once the game loads up. Here are the example worldgeneration.cfg changes made to the mentioned vein.

            titaniumchrome {
                I:Density_10=10
                B:EndAsteroid_false=true
                B:GalacticraftCore_Moon_false=true
                B:GalacticraftMars_Asteroids_false=true
                B:GalacticraftMars_Mars_false=true
                B:GalaxySpace_BarnardC_false=true
                B:GalaxySpace_BarnardE_false=true
                B:GalaxySpace_BarnardF_false=true
                B:GalaxySpace_Callisto_false=true
                B:GalaxySpace_CentauriA_false=true
                B:GalaxySpace_Ceres_false=true
                B:GalaxySpace_Deimos_false=true
                B:GalaxySpace_Enceladus_false=true
                B:GalaxySpace_Europa_false=true
                B:GalaxySpace_Ganymede_false=true
                B:GalaxySpace_Haumea_false=true
                B:GalaxySpace_Io_false=true
                B:GalaxySpace_Kuiperbelt_false=true
                B:GalaxySpace_MakeMake_false=true
                B:GalaxySpace_Mercury_false=true
                B:GalaxySpace_Miranda_false=true
                B:GalaxySpace_Oberon_false=true
                B:GalaxySpace_Phobos_false=true
                B:GalaxySpace_Pluto_false=true
                B:GalaxySpace_Proteus_false=true
                B:GalaxySpace_TcetiE_false=true
                B:GalaxySpace_Titan_false=true
                B:GalaxySpace_Triton_false=true
                B:GalaxySpace_VegaB_false=true
                B:GalaxySpace_Venus_false=true
                I:MaxHeight_70=70
                I:MinHeight_10=10
                B:Nether_false=true
                I:OrePrimaryLayer_28=28
                I:OreSecondaryLayer_28=28
                I:OreSporadiclyInbetween_28=28
                I:OreSporaticlyAround_28=28
                B:Overworld_false=true
                I:RandomWeight_100=100
                S:RestrictToBiomeName_None=None
                I:Size_96=96
                B:TheEnd_false=true
                B:"Twilight Forest_false"=true
                B:Underdark_false=true
                B:Vanilla_EndAsteroids_false=true
            }

I drastically increased the size, changed it to spawn in any dimension, adjusted the density and the random weight, and removed any other ore from spawning in the same vein. Pretty drastic and noticeable changes, right?  Now I go create a new map, find some Titanium, and it's still generated as per the old original settings. The info on titanium in NEI shows that the changes to dimensions have registered, but nothing else. The vein is still the original size, contains Chromite, Uvarovite and Perlite, and has the old random weight. 

So, how do I properly adjust these settings for existing veins, and can I add custom veins to the mix? I'm a little confused, because it seems like all the necessary settings for it exist in a beautifully customizable config, only to not register in game. I've found next to no information online about the particular format used in the config, or how to make changes to it. 

Also, something I found curious: whenever I leave the Worldgeneration.cfg writable, something writes back the original settings so it looks like:

                I:OrePrimaryLayer_28=28
                I:OreSecondaryLayer_28=28
                I:OreSecondaryLayer_825=825
                I:OreSporadiclyInbetween_28=28
                I:OreSporadiclyInbetween_842=842
                I:OreSporaticlyAround_28=28
                I:OreSporaticlyAround_925=925
                B:Overworld_false=true
                B:Overworld_true=true
                I:RandomWeight_100=100
                I:RandomWeight_16=16

Which makes me think that the settings for it are kept in another file somewhere, or are cached because where else would it be coming from? Am I not meant to modify this file, is it there simply for informational purposes? I'm not even sure this is the right place to ask, but because I'm at my wits end I might as well try. I would like to make some more subtle changes so that ore generation suits my liking, but if something this ridiculous doesn't show up then I don't know what else to do here.

Here's a screenshot of the vein generated as per my changes to it:

![2019-05-15_17 35 36](https://user-images.githubusercontent.com/43228249/57818253-f8a54c80-7737-11e9-9555-ed24d919b1c3.png)

Notice the size and composition of it, it should not be like this
And here's a screenshot of the NEI info for titanium

![2019-05-15_17 35 50](https://user-images.githubusercontent.com/43228249/57818285-14105780-7738-11e9-9f42-d111c905c2bd.png)

You can see that the changes to the dimension have registered, but nothing else.

**Comment by richardhendricks** [comment]
Worldgen doesn't use the config files any more @bartimaeusnek

**Comment by bartimaeusnek** [comment]
@richardhendricks https://github.com/GTNewHorizons/GT5-Unofficial/blob/aa3d8338721db23b74466bab9f7565ea37e39bf9/src/main/java/gregtech/common/GT_Worldgen_GT_Ore_Layer.java#L126

also, as you can see, its wrongly changed:

`     titaniumchrome {
                I:Density_3=10
                B:EndAsteroid_false=true
                B:GalacticraftCore_Moon_false=true
                B:GalacticraftMars_Asteroids_false=true
                B:GalacticraftMars_Mars_false=true
                B:GalaxySpace_BarnardC_false=true
                B:GalaxySpace_BarnardE_false=true
                B:GalaxySpace_BarnardF_false=true
                B:GalaxySpace_Callisto_false=true
                B:GalaxySpace_CentauriA_false=true
                B:GalaxySpace_Ceres_false=true
                B:GalaxySpace_Deimos_false=true
                B:GalaxySpace_Enceladus_false=true
                B:GalaxySpace_Europa_false=true
                B:GalaxySpace_Ganymede_false=true
                B:GalaxySpace_Haumea_false=true
                B:GalaxySpace_Io_false=true
                B:GalaxySpace_Kuiperbelt_false=true
                B:GalaxySpace_MakeMake_false=true
                B:GalaxySpace_Mercury_false=true
                B:GalaxySpace_Miranda_false=true
                B:GalaxySpace_Oberon_false=true
                B:GalaxySpace_Phobos_false=true
                B:GalaxySpace_Pluto_false=true
                B:GalaxySpace_Proteus_false=true
                B:GalaxySpace_TcetiE_false=true
                B:GalaxySpace_Titan_false=true
                B:GalaxySpace_Triton_false=true
                B:GalaxySpace_VegaB_false=true
                B:GalaxySpace_Venus_false=true
                I:MaxHeight_70=70
                I:MinHeight_10=10
                B:Nether_false=true
                I:OrePrimaryLayer_28=28
                I:OreSecondaryLayer_825=825
                I:OreSporadiclyInbetween_842=842
                I:OreSporaticlyAround_925=925
                B:Overworld_false=true
                I:RandomWeight_16=100
                S:RestrictToBiomeName_None=None
                I:Size_16=96
                B:TheEnd_false=true
                B:"Twilight Forest_false"=true
                B:Underdark_false=true
                B:Vanilla_EndAsteroids_false=true
            }`
would be the right config entry.

**Comment by richardhendricks** [comment]
Also, the GT worldgen ignores size>64 because it will cause cascading worldgen. Galacticgreg does not, and setting a size that large will crash your server.

**Comment by observeroftime02** [comment]
Knowing that the config is not used for worldgen was very helpful. It pointed me in the right direction. I've found the responsible bytecode in the GT_Worldgenloader.class file and patched it around to suit my liking. Configuration is not as easy as I previously assumed when seeing the config file. Thanks again, and sorry for the bother.
