### ISSUE TITLE
Spice of Life settings

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#449]
This is an idea, not a bug.

**Lunch Box**
In vanilla you regularly have up to 256 hunger bars of food in one slot (64 steaks). With SoL you have to carry around 4 or 5 types of food.
The Lunch Box was made to overcome this inventory problem, but right now its max slot item count is capped at 2 via configs. It has 6 slots so that's 12 pieces of food. That's just 48 hunger bars of mediocre food for one inventory slot.
I suggest increasing the cap to 32 (That's 3 times vanilla) to gain a bonus for the box.
You still have to prepare all the food types but the inventory mess is much better that way.

**Nutritional Value**
I don't like when the value of food drops right after first consuming the food.
I got it set to *food.modifier.formula=IF(count>=8,0,1)*.
That means 8 pieces give you full value but 9th piece gives you zero, so you have to switch.
Alternative:
*=IF(count>=5,(1 - (count-5)/8),1)*
That would mean 4 pieces are at 100% and then it decreases by 12,5%.
(There might be more efficient way of coding that)

Just ideas :).

**Comment by Teteros** [comment]
Maybe the lunch box could be tiered like a bit higher to justify the capacity increase?
At the moment there is barely any reason to use the lunch bag, since you can craft the lunch box relatively early. If both the lunch bag, and the lunch box were buffed, (perhaps lunch box more so) I think they would be more viable indeed.

Inventory space was usually the reason for better food in my mind. Though, do feasts food types even stack up to that much? Last time I made some was during 16 stack size days so things might have changed since then.

**Comment by Dream-Master** [comment]
Will look what we can change here.

**Comment by ProsperCraft** [comment]
Honestly the hunger is over the top, I love the complexities of gregtech, but this hunger is just too much.  The lunchbox is supposed to be there to make the spice of life mod not as obnoxious, but only holding two items is not enough.  I feel like I am constantly eating and not able to focus on enjoying the modpack.

**Comment by Namikon** [comment]
There are some ways to bypass the "food-struggle", but they are not early game and I do agree that the only way to survive in the early tiers is to build massive fields of various types of food (And yes, I f... **hated** it). The changes suggested by Methes seem to be fair; I'd vote for the second formula (100 and descending), and stacksize to 64 for the lunchbox; As all food items do stack to 64 in your inventory already.

**Comment by arnabbiswasalsodeep** [comment]
I have modified the formula in another branch, it still needs to be tested.
https://github.com/GTNewHorizons/NewHorizons/commits/Delicious/config/SpiceOfLife.cfg

**Comment by deeplyarnab** [comment]
Its been implemented here:- https://github.com/GTNewHorizons/NewHorizons/commits/Patches-Arnab
Done testing, works fine. If it isn't good enough then we can reopen this, closing it for now.
