### ISSUE TITLE
Add proper shader setup information to the wiki

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4490]
Optifine HD E7 Ultra
dynamic lighting at Fast
torch in right hand in mount and blade slots
screenshots for other settings later

Sildurs Vibrant Shaders v1.20 Extreme
change torchlight setting
change moon brightness
issues with moon phase

SEUS 11.0
edited composite1.vsh to change torchlight to pure white, final.fsh to change water fog to 0.05, 
issues with nightvision

**Comment by draknyte1** [comment]
Consider testing the ShadersMod vs Optifine. 
It has no issues with FastCraft.

**Comment by richardhendricks** [comment]
optifine integrates shadersmod doesn't it?

**Comment by draknyte1** [comment]
> optifine integrates shadersmod doesn't it?

Doesn't mean EVERYONE wants Optifine, it's fucking trash.
