### ISSUE TITLE
Thaumcraft Quests

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/NewHorizons#4494]
Moron said to make a tic.. so here is a tic.

Many, many many things in Thaumcraft are not explained well and the mods can be far worse.

One mod that is awesome, but also has some odd things is Automagy. See, the mod dev thought it'd be cool to make research unlock upon scanning certain items in the mod. Well issue is, some of those items may never be made by someone and thus it is quite unintuitive...

So please make a quest for making and scanning the crystalline brains in automagy. Oh and note that they need the thaumcraft zombie brains, vs normal ones.

Next up is the avarice pearl, which is a item many will make, but few will probably spam right click... You need to throw items on the ground and spam right click it until it turns into a shattered pearl. Thus opening up a few more items.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58296793-d09e9480-7d9a-11e9-94b2-7611d7c2461d.png)
![image](https://user-images.githubusercontent.com/1214811/58296798-d5634880-7d9a-11e9-9a80-34b13ef49c0b.png)
