### ISSUE TITLE
Electrical Stimulator and Mutator from Extra Bees are extremely OP and need nerfing

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4496]
ES is only gated by stainless steel really.

Mutator is only gated by soul frames.

Needs to a discussion on appropriate tiers for these items.

Mutator especially is very OP since with nether stars it grants 1000% mutation chance, and unlike the extra bees wiki, there is not a limit on that.

**Comment by richardhendricks** [comment]
https://binnie.mods.wiki/wiki/Electrical_Stimulator

https://binnie.mods.wiki/wiki/Mutator

**Comment by richardhendricks** [comment]
Each circuit can hold 4 tubes, never decay etc. Now leaning towards high end of EV

**Comment by Ethryan** [comment]
There is no way to implement an GT ampere limiter to those blocks?

For example 1 of them require 1 ampere electricity, 2 require 2 ampere, 3 require 4 and so on. 
Thus limiting the number of Electrical Stimulators that can be feasibly used in a Alveary multiblock.

**Comment by richardhendricks** [comment]
Mutator to EV. Electrical Stimulator to IV

**Comment by Hakameda** [comment]
Nah
