### ISSUE TITLE
Quest ID 798 Iron Capped Greatwood Wand

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4498]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Put in the quest text that for the quest to detect the wand must be fully filled with aspects.

**Comment by Dream-Master** [comment]
fixed by @richardhendricks
