### ISSUE TITLE
Move IC2 seeds from HV lootbags to new "IC2 Crops" lootbag

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4499]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by 0lafe** [comment]
silicon bees shouldnt be in legendary bags

**Comment by Dream-Master** [comment]
there is a xml file in the lootbags folder. Just remove it is no problem

**Comment by richardhendricks** [comment]
I'm going to leave the IC2 seeds there, makes it interesting.

I've created a new separate IC2 crops quest bag, and added to all quests.

Feel free to tweak the settings as needed.

I do need a recipe to convert the normal to Fortuned bags please. @Dream-Master

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58385432-f0f66b00-7fb5-11e9-9fc6-16e030891f01.png)

Not all are same chances, several have limited drop number.

**Comment by richardhendricks** [comment]
Suggested recipe to up normal lootbags to fortuned lootbags

SprayCan of WeedEx
Fortune 3
normal lootbag

**Comment by richardhendricks** [comment]
@Dream-Master Need fortuned lootbags recipe.

![image](https://user-images.githubusercontent.com/1214811/58687140-6bbcde80-8346-11e9-8251-d2cdb91b1957.png)
