### ISSUE TITLE
Turn off suspicious hunger loss

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#450]
With the /afk feature on the server, the "suspicious hunger loss" measure to prevent chunk loading by players is redundant, as /afk will prevent the player death anyway.

**Comment by Namikon** [comment]
True, but keep in mind that only we have the afk feature, SP and any forge server do not

**Comment by arnabbiswasalsodeep** [comment]
I'd +1 the suggestion, when i un-afk, i had zero hunger bar, all the effects kick in and had food just a bit away, luckily i was able to reach my food chest taking tick damage and reducing to 4 hearts and ate stuff. Time was wasted cuz i had to look for the food i had already eaten.

**Comment by Namikon** [comment]
So either Martin agrees to disable AFK Hunger, or I will remove the afk-godmode so that this isn't a problem anymore

**Comment by Dream-Master** [comment]
If no one wants afk hunger the disabled it.

**Comment by Dream-Master** [comment]
So what need done here? Did someone change the config file ?

**Comment by Namikon** [comment]
I'll go through the configs and check what needs to be done. Several mods add afk-hunger behaviour, so there are multiple things that need a change

**Comment by Dream-Master** [comment]
@arnabbiswasalsodeep @Teteros 

Can you take care of it please and update the files. Thanks

**Comment by Teteros** [comment]
@Dream-Master
Gregtech is responsible for it (it used to be called *B:unsuspiciousHungerConfig* in GT 3.x hence the name of the issue, but since GT 4.x is seems to be renamed to *B:AFK_Hunger*)

Either way, it looks to be disabled:
https://github.com/GTNewHorizons/NewHorizons/blob/54a9da236f0d801aebe15ac1adeb5ed12706ca7a/config/GregTech/GregTech.cfg#L13

Please check if the server version of this file is the same.

**Comment by Methes** [comment]
It's very probably config of Hunger Overhaul.
Even here on Github you have
constantHungerLoss=true
That's what I disabled for my SSP and constant loss is gone.

**Comment by Teteros** [comment]
Good point, changed. If there's something else with the same behaviour, please report.
