### ISSUE TITLE
Need separate Genetics tab

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4500]
Binnie's Genetics is used for bees, trees, and flowers.  Need to setup quest tab covering it.

**Comment by Hyperic88** [comment]
And Butterflies too, although i never used them in large numbers , but they are excellent pollinators afaik :)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57984831-47e3c980-7a25-11e9-8f82-6e5923c839f1.png)
![image](https://user-images.githubusercontent.com/1214811/57984835-4adeba00-7a25-11e9-8b28-f34e8acdd051.png)
![image](https://user-images.githubusercontent.com/1214811/57984836-4f0ad780-7a25-11e9-8e01-b8513fac4d5f.png)
![image](https://user-images.githubusercontent.com/1214811/57984838-5336f500-7a25-11e9-9e11-62ed3721f0ff.png)
![image](https://user-images.githubusercontent.com/1214811/57984840-57fba900-7a25-11e9-91c8-3acc7575f01c.png)
![image](https://user-images.githubusercontent.com/1214811/57984842-5cc05d00-7a25-11e9-82d1-0670162f2d94.png)
![image](https://user-images.githubusercontent.com/1214811/57984844-61851100-7a25-11e9-9382-4cecc78a5fce.png)
![image](https://user-images.githubusercontent.com/1214811/57984846-6649c500-7a25-11e9-8083-5ce91ed5365b.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57984864-97c29080-7a25-11e9-82c8-291f70f40cd9.png)
![image](https://user-images.githubusercontent.com/1214811/57984866-9b561780-7a25-11e9-8e1d-d88a09dbc6d9.png)
![image](https://user-images.githubusercontent.com/1214811/57984870-a1e48f00-7a25-11e9-867f-dfcfabec3a55.png)
![image](https://user-images.githubusercontent.com/1214811/57984873-a7da7000-7a25-11e9-8046-0d1b5f9ef8b2.png)
![image](https://user-images.githubusercontent.com/1214811/57984876-ac9f2400-7a25-11e9-96b4-74d4ca696c79.png)
![image](https://user-images.githubusercontent.com/1214811/57984878-b163d800-7a25-11e9-83f7-992a2ad27165.png)
![image](https://user-images.githubusercontent.com/1214811/57984880-b6c12280-7a25-11e9-9b0e-3ddd606abfc8.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57984885-c04a8a80-7a25-11e9-83fa-7e4533c9cb02.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57985448-cd6b7780-7a2d-11e9-8648-88cd27488333.png)

**Comment by Hyperic88** [comment]
Nice! but Isolator sometimes "consume" item thats put into to isolate that genes from occasionaly IIRC ;)

**Comment by richardhendricks** [comment]
That will be something for players to discover on their own I guess.
