### ISSUE TITLE
More alveary quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4501]
Upgrades and better frames.

Automation etc
Temp etc
Humidity etc

Mutator and electrical stimulator need proper tiers

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57976457-8c7c5000-79a6-11e9-9e58-4ffda1dd1606.png)
![image](https://user-images.githubusercontent.com/1214811/57976459-93a35e00-79a6-11e9-9881-bd5b6b46ae73.png)
![image](https://user-images.githubusercontent.com/1214811/57976460-98681200-79a6-11e9-9498-a47df192143f.png)
![image](https://user-images.githubusercontent.com/1214811/57976461-9c942f80-79a6-11e9-96f0-5dabdaf5e5ac.png)
@Hakameda

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57976469-b5044a00-79a6-11e9-88e8-71a452540cad.png)

**Comment by richardhendricks** [comment]
Split Mutator into its own quest
![image](https://user-images.githubusercontent.com/1214811/57976505-aec29d80-79a7-11e9-94ad-1e7bb4aac82d.png)

**Comment by Hakameda** [comment]
The alveary blocks quest should be separate
