### ISSUE TITLE
Ultimate Solar Helmet uncraftable

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4509]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I Tried to craft the Ultimate Solar Helmet
#
#### What happend instead? (Attach screenshots if needed)
![2019-05-17_22 16 29](https://user-images.githubusercontent.com/11991148/57953843-8d9f7580-78f1-11e9-9aa7-ee3be84fe0f5.png)

Does not work for some reason.
Here is the nei recipe
![2019-05-17_22 08 10](https://user-images.githubusercontent.com/11991148/57953727-38636400-78f1-11e9-9da2-0a419cf97c21.png)
I tried 3 different types of zpm circuits (mainframe, crystalcomputer, wetware assembly)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/57955671-c1c96500-78f6-11e9-991a-cc90b385b157.png)
![image](https://user-images.githubusercontent.com/2970688/57955682-c8f07300-78f6-11e9-9a27-0430799a56e8.png)
![image](https://user-images.githubusercontent.com/2970688/57955695-ce4dbd80-78f6-11e9-9d3c-c6f5d62a8cc9.png)
![image](https://user-images.githubusercontent.com/2970688/57955701-d4dc3500-78f6-11e9-9474-de29f3ef9e45.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/57955831-300e2780-78f7-11e9-94d2-c54dfe5ecf92.png)
if helmet is empty it not works. If it is full it works
