### ISSUE TITLE
Quest "Another brick in the wall" fails to complete

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#451]
"Quest "Another brick in the wall" fails to complete because it requires 8 Arcane stone bricks to be *crafted*. This is not possible anymore as they need to be assembled into bricks instead.

Changing it to detection would solve it.

**Comment by Namikon** [comment]
That was changed in the latest HQM file available on the Testserver, has to be verified yet

**Comment by Dream-Master** [comment]
works.
