### ISSUE TITLE
HV Steam Turbine Quest Error?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4513]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Shouldn't this quest in the HV quests tab give an HV reward bag and not a MV one?

**Comment by Dream-Master** [comment]
will check

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58146455-d0c45600-7c1b-11e9-9dde-d0cf08e3d036.png)
