### ISSUE TITLE
Moon Buggy Schematics unable to obtain

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4514]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to create a moonbuggy schematic from the moonbuggy datastick.
#
#### What happend instead? (Attach screenshots if needed)
It creates a t2 rocket schematic just like the t2 rocket data stick
#

**Comment by bartimaeusnek** [comment]
should be fixed with 7.3 but im not quite sure
