### ISSUE TITLE
Finite Water can be tricked+bugged

### ISSUE THREAD

**Issue by stk2008** [GTNewHorizons/NewHorizons#4515]
#### Which mod pack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Ok bit of a long one this sorry so I have set up a pump like so
https://i.imgur.com/RlTezV4.jpg

and it sucks up the water like so 
https://i.imgur.com/dduaymh.jpg

now all is good as you can see FINITE works great the water is disappearing as it should.The issue now comes when you reintroduce the water back in like this
https://i.imgur.com/b1ghMnU.jpg

leave it a moment to fill up and start pumping again then block it off again like this
https://i.imgur.com/fFLHXnx.jpg
as you can see its now pumping again and the water is disappearing as is should but here is the killer issue.
Once all the water is visually gone it still pumps water for ever even though there is no water left to pump.
The pump shows 0 then goes to 1000 then back to 0 then 1000 forever. and the large tank also fills up with this magic water.

https://i.imgur.com/6JcofWy.png
https://i.imgur.com/s7pnmjL.png

this issue happens on EVERY pump in this pack that I have tested so far.
this is a big issue I think as it can be hacked on servers to make the FINITE plug in pointless.

thank you so much in advance

#
#### What do you suggest instead/what changes do you propose?

I would expect the water to drain as expected then once I reintroduce the water and then block it off again I would expect that water to then be consumed and not be infinite.

EDIT

ok I see whats going on here as some one did say it does not take the water directly from the pump it takes it from a random source in the lake which is here
https://i.imgur.com/e9ydLY0.jpg

so even though now there is no water in the pump area it just draws it from the lake

so fast forward some more note the water has been taken from this spot
https://i.imgur.com/WvamBOi.jpg

is this fixable if so it would be amazing possibly place a check on the pump to make sure its touching water?

So theoretically if i do not place the pump in the lake etc and place it on the ground and place water in the hole using a bucket it should not take it from the lake

ok that worked I broke the pump and placed a new one down to reset the water node location so no water new pump and mining pipes
https://i.imgur.com/ngsZOfz.jpg

fill with water from the bucket
https://i.imgur.com/Zhf8RUL.jpg

all is good so far and water from bucket has gone
https://i.imgur.com/PsoP4o3.jpg

fill with more water from bucket
https://i.imgur.com/z6AHnyl.jpg

and once that is used up all is good
no more pumping water.

so how can this be fixed I have an idea how about once the pump has finished and there is no more water we drop the pump and the mining pipes on the floor FORCING players to replace them there for reseting the water source pick up location.?

Thanks

**Comment by richardhendricks** [comment]
Building the tree of pumpable water takes extensive amounts of time. Doing so after every puimp operation would needlessly increase server load.  You are free to take a look at the code here if you like and suggest improvements, but it works "good enough" as is.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Pump.java#L351

**Comment by stk2008** [comment]
Hi thanks for replying.
I truly wish i could assist with code but I have zero idea what I am looking at.

The link you sent me for example all I see is ?????????????? Lol.

Thanks for replying though I suppose I will have to wait and pray that one day some one might pick it up and have a dabble.

All the best.

**Comment by draknyte1** [comment]
Every mod expects water to be infinite. 
Without recoding every mod, it’s not fixable.

**Comment by stk2008** [comment]
Hi
yeah its just kind of beats the FINITE plugin from code chicken chunks is all.
It does work under some circumstances EG filling up a hole using a bucket.
But as soon as you use a water source from a lake etc its infinte as it does not take it from the pump it chooses a source out side of the pump area.

I have looked at the code and really want to understand it as I would love to fix this but it realy is way way over my head.

I have ALWAYS said people that can programme are wizards LOL :)

**Comment by richardhendricks** [comment]
That's just where it prints it.

I looked at the code some more, and here is the explanation for what you are seeing.

The code is pretty complex. Basically what it is doing is, starting from the pumphead, make two lists.  One is a list of fluid blocks found. One is a list of blocks to check. As a block is checked its neighbors are added to the the end of the list of blocks to check, but only if they are fluids and not in the list of found blocks.  When the check is completed, the block is added to the list of fluid blocks found, but at the beginning, pushing earlier blocks down the list. 

When looking for neighbors it checks the 4 cardinal directions and also up. This way it can follow back flowing liquids to their source block.

At the end of the process the fluid blocks found has the "last found" blocks at the front of the list - these are the blocks furthest away from the pump head. Then the pump starts removing these blocks.  What is happening in your case is that the pump is removing the source block for a "stream" that flowed to the pump head.  So it looks like the pump head is pumping without a direct connection, but during the list creation there was a link.  

So all's well.

**Comment by richardhendricks** [comment]
I think this might be your situation, or something similar anyways.

![image](https://user-images.githubusercontent.com/1214811/58038019-75e40f00-7af4-11e9-93f3-2811426288ca.png)

PH = pump head.
W = Water source blocks
F = Flowing water blocks
num = Distance from pump head.  

W8 to F3 is downhill, so the water height is resetting on block drop.
Wa and Wb have flowing water connecting to F3, but are level with F3. if W8 wasn't there, they would not be able to make it all the way to PH.

So when creating the list, the pump head sees all the fluid blocks.  As it extracts, it does the furthest blocks first.
And so W8 gets pulled before Wa6 or Wb6, and so the water looks "disconnected" now because they can't quite flow to the pump head.
