### ISSUE TITLE
Small Fuel Canister dont stack

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4517]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Small Fuel canisters dont stack. Every other type (medium, large, extra large) do stack.
#

#### What do you suggest instead/what changes do you propose?
Make the small fuel canister stack too

**Comment by Dream-Master** [comment]
@DietmarKracht is this a Galaxy space item ? If yes we can do it via asm ? @bartimaeusnek

**Comment by DietmarKracht** [comment]
yep is galaxy space item

**Comment by Prometheus0000** [comment]
Is this worth reopening?

**Comment by Prometheus0000** [comment]
Looks like this is fixed now anyway.
