### ISSUE TITLE
Crash with using bowl in pams

### ISSUE THREAD

**Issue by deeplyarnab** [GTNewHorizons/NewHorizons#452]
Crash Report:-

http://pastebin.com/xhAvtAfZ

Description:-

Pams recipe that uses the vanilla bowl gets consumed in recipe. (in this pack)
So when i tried to craft a friut bowl using the recipe 3_berries+1_bowl=1_fruit_bowl, but instead used 6_berries+1_bowl as it would yield 2_fruit_bowl, the game crashed instead.

**Comment by Namikon** [comment]
That is caused by the experimental AntiRecipeTamper module, which shouldn't be active oO Weird things happen these days. Anyways, duct-taped in 65u

**Comment by Dream-Master** [comment]
Will be added in the next update.
