### ISSUE TITLE
New Diamond Tool Quest

### ISSUE THREAD

**Issue by IAmBatby** [GTNewHorizons/NewHorizons#4522]
#### What do you suggest instead/what changes do you propose?

I suggest after the diamond quest (Steam Age : "Oh, Shiny (Not Platinum") there be a quest to make diamond gregtech tools, as they are very decent upgrades from iron/bronze players would be using and at this point diamonds do not have too much use for how much they just collected.

**Comment by IAmBatby** [comment]
Atleast a diamond hammer, I know it gets outclassed by the autohammer but for 6 diamonds your not really using its a lot faster

**Comment by richardhendricks** [comment]
Pick and Shovel cannot be used.

GT hammer is ok I guess. 128k durability.  There's better places to spend your diamonds IMO but I will add a quest for it.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58143395-56420900-7c10-11e9-8206-4c73976f5191.png)
