### ISSUE TITLE
Dehydrator recipes

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4524]
https://github.com/alkcorp/GTplusplus/issues/487 
Posted on alk's github, posting here too.
Suggesting to add drying rack recipes to dehydrator 
Example: bound leather --> tanned leather

**Comment by Dream-Master** [comment]
yes good idea why not

**Comment by Dream-Master** [comment]
@Impos913 why not suggest the other recipes too that can be only made with the rack?

**Comment by Impos913** [comment]
I cant open the game now so...
