### ISSUE TITLE
Quest Addition Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4526]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Add a quest to explain how benzene works? I feel like getting people over the initial power production hump will keep them around longer. Steam turbines are obvious because you come from steam but maybe something that just does a quick and dirty benzene setup to show there are "alternate" paths? Maybe a Light Fuel line too? (Add past the combustion generator - or maybe power production needs it's own little branch in LV screen?)

**Comment by shawnbyday** [comment]
Just realized that benzene is MV because of distillery but still.

**Comment by richardhendricks** [comment]
There's already quests for all the fuels in LV after the oil pump?  Not sure what you want here really.

![image](https://user-images.githubusercontent.com/1214811/58144145-dff2d600-7c12-11e9-9ad0-cf6ba73e3403.png)

Benzene quest added
![image](https://user-images.githubusercontent.com/1214811/58144485-3ad8fd00-7c14-11e9-9de1-e3199ee3c81d.png)

**Comment by shawnbyday** [comment]
Yea I was thinking just an "Fuels other than steam 101" sort of thing. I've ran steam all the way into EV several times because 1. I'm dumb and 2. I didn't know any better.

**Comment by Bluebine** [comment]
At this point pretty much every viable fuel has a quest. Oil for both light fuel and refinery gas, diesel, cetane, biodiesel, benzene, there's even a quest for solars. I think that's about all anyone uses- I tried CO for power, but that was a terrible idea and I definitely wouldn't recommend it to a noob.

**Comment by richardhendricks** [comment]
oaky I'll make a checkbox quest with fuel options.

**Comment by shawnbyday** [comment]
Sorry I'm dumb lol.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58146044-13852e80-7c1a-11e9-94a6-2dbfcd41be9a.png)
