### ISSUE TITLE
Glass Fiber quest wrong location

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4528]
#### Which modpack version are you using?
2.0.7.0
Quest number 1675 is in the wrong location, it should be in the IV tab as nothing in ev uses glass fibers.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58143541-c94b7f80-7c10-11e9-8a2e-9471d5f55fc6.png)
