### ISSUE TITLE
Open Modular turret Damage is to low

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4529]
Turret damage caps out far to low to be anything other than a novelty, buff them a lot so they can at least deal with most non regen mobs.

**Comment by Dream-Master** [comment]
@Anarack there is a very detailed and nice config. https://github.com/GTNewHorizons/NewHorizons/blob/master/config/openmodularturrets.cfg
Please make some suggestions or better a pull request. 
You can send me the modified file as well. Thanks
