### ISSUE TITLE
Toxic Everglades acess at official servers

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4532]
#### Which modpack version are you using?
Eta Live
#
#### If in multiplayer; On which server does this happen? 
Multiplayer
#
#### What did you try to do, and what did you expect to happen?
Trying to make a portal to Toxic Everglades and well, expect it to be possible xD
#
#### What happend instead? (Attach screenshots if needed)
Casting mold(coin) have no recipe, so not possible to make alkalus disc
![2019-05-21_19 05 33](https://user-images.githubusercontent.com/25028786/58112128-8206c400-7bfb-11e9-9d50-66a12df36b4b.png)

#
#### What do you suggest instead/what changes do you propose?
Well, we have two ways here:

1. Add casting mold(coin) recipe
2. Make a quest for obtaining the osmium coin itself.

here was an issue https://github.com/GTNewHorizons/NewHorizons/issues/3580 , but well, look like not made it.

**Comment by DietmarKracht** [comment]
there is also an extruder mold iirc. i made the disc on delta

**Comment by DietmarKracht** [comment]
nvm it is the same mold

**Comment by Dream-Master** [comment]
fixed in 7.2/7.3

**Comment by richardhendricks** [comment]
Not fixed, still cannot do mold

**Comment by Dream-Master** [comment]
tested with lastest 7.3 Version ?

**Comment by richardhendricks** [comment]
Yes, still no recipe for the coins mold.

**Comment by Dream-Master** [comment]
ok will check it later

**Comment by Cinobi** [comment]
2.7.0.5 still present x_x

**Comment by Dream-Master** [comment]
you mean the bug or the recipe @Cinobi ?

**Comment by boubou19** [comment]
Casting form (coinage mold) still has no recipe in 2.7.0.5

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71314114-0f84ed80-2443-11ea-8c5b-39294d73b0a0.png)
![image](https://user-images.githubusercontent.com/2970688/71314118-1449a180-2443-11ea-968b-1c936fc4679b.png)
