### ISSUE TITLE
Gating Steam Age behind Redstone quest.

### ISSUE THREAD

**Issue by IAmBatby** [GTNewHorizons/NewHorizons#4538]
#### What do you suggest instead/what changes do you propose?

Edit / Reorder Stone age so you need to finish the Redstone quest to view Steam Age, when I played I didn't realize Redstone was a main quest, and when I got to Steam Age it was asking for Redstone which I didn't have, so I kind of lost track, if you don't have Redstone there's only 1 quest in steam age you can do (the powered smelter) so I think players shouldn't be able to see it.

**Comment by richardhendricks** [comment]
I don't want to gate steam with Redstone, as you said you can make the boilers and alloy smelter without the red alloy.  What I did was move the redstone quest so it is a little more clear it is a mandatory quest.  Mandatory quests are marked with thick lines and have the crenelations on them.
![image](https://user-images.githubusercontent.com/1214811/58143779-9bb30600-7c11-11e9-8b21-4d40e59da082.png)

**Comment by IAmBatby** [comment]
I disagree but lack the experience to hold my ground, thanks for the compromise
