### ISSUE TITLE
The more prefixes an enemy has the less health it should have.

### ISSUE THREAD

**Issue by IAmBatby** [GTNewHorizons/NewHorizons#4539]
#### What do you suggest instead/what changes do you propose?
Infernal mobs makes enemies do crazy things, wither effects, fire balls, speed, increased size, rapid fire etc, but on top of this they have insane health, i think they have way to much health for the things they can do, its just not fun to try killing an enemy that takes 30 hits but also every hit takes a quarter of your health.

**Comment by Impos913** [comment]
lol

**Comment by DoomSquirter** [comment]
early on, the mobs are difficult.  later you can mostly ignore them.  At some point, with the right enchants, you can ignore pretty much every mob in the game and I'm not talking about late game for this.  

there are counters to everything the mobs can toss at you.  I wouldn't touch anything, especially if it makes things like the op crossbows completely irrelevant.
