### ISSUE TITLE
x2 Steel (Quest #657)

### ISSUE THREAD

**Issue by IAmBatby** [GTNewHorizons/NewHorizons#4542]
#### What do you suggest instead/what changes do you propose?
Due to it being just before the Bricked Blast Furnace quest, the player already has the items in their inventory to mark #657's part 2 and 3 of the quest off, but the quest implies a new set of those items (firebricks and the main controller block)

not sure how you would remedy this, but it is a seeming issue

**Comment by Impos913** [comment]
I think you should start with 4x bbf then build more if you need, I dont build more 4x is enough for me.

**Comment by IAmBatby** [comment]
This reply might have been made off the assumption of the title, but the title is just the name of the quest, not a suggestion

**Comment by Impos913** [comment]
I mean the quest should say you to build 4x not start with 1 then 2 then 4

**Comment by Dream-Master** [comment]
yea will change the quest

**Comment by richardhendricks** [comment]
I would be very careful deleteing a quest that has already been used for so long. Better to either leave it alone, or unlink it but leave it in the database.

Otherwise if you create a new quest it might use the same quest ID # and players will have it already complete or unlocked.

**Comment by richardhendricks** [comment]
Change to 4x steel and 10x steel. :D

**Comment by IAmBatby** [comment]
no one wants to delete this quest

**Comment by Ethryan** [comment]
How about locking the x2 steel behind the gather 8 steel on the steam page, that way you will have to set up the first blast furnace before the quest even appears.

**Comment by IAmBatby** [comment]
Yes this would be a good solution.
