### ISSUE TITLE
U dont see Items on other Players (in there hands)[Multiplayer][1.7.10]

### ISSUE THREAD

**Issue by TimoWolle** [GTNewHorizons/NewHorizons#4543]
#### Which modpack version are you using?
1.7.10
#
#### If in multiplayer; On which server does this happen? 
myFTB Server(Multiplayer)
#
#### What did you try to do, and what did you expect to happen?
U dont see selected Items on other characters (If he hold a sword u dont see it)
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Maybe that i see what he is holding?

**Comment by sleepylucy** [comment]
That issue is already known, but dunno if it’s going to be fixed in the next version

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4287
