### ISSUE TITLE
Remove Gendustry bees & conversion script

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4544]
Players have had plenty of warnings now, time to remove them.

**Comment by Jocroy** [comment]
Aren't there servers that are still on 2.0.5.1? What is the harm in keeping this around still?

**Comment by Hakameda** [comment]
Some people are still running old versions. Does the bees/script being in there really cause many problems?

**Comment by DoomSquirter** [comment]
wait hold up moron.  we already decided (dream gave input) that we'd hold off and wait till after 7.3 to remove the scripts.  do not remove them prematurely!

**Comment by Dream-Master** [comment]
in 8.0 there are gone 100%.

**Comment by richardhendricks** [comment]
This is *not* for 2.0.7.3, releasing soon, this is for whatever is next. I just called it 2.0.7.4.  If it is 8.0, whatever.

**Comment by richardhendricks** [comment]
The scripts cause confusion because of cluttering up NEI.

**Comment by repo-alt** [comment]
Would be nice to fix that https://github.com/GTNewHorizons/NewHorizons/issues/4527 before removing. Also I'm not sure if I found all the bees with mismatching names.

**Comment by Ngar1** [comment]
how can i see ( looking in Apiarychest) which bee is gt or gendustry, foresty? All showing with waila just „forestry...“

Also not every bee change by trowing on ground suddenly to gt, sometimes i get in alvary hybrids of gt and gd because gt isnt recognizeable - not so nice.

**Comment by repo-alt** [comment]
Looking in the apiary chest you can see that gendustry bees has no available mutations in the left pane. As for the hybrids where gendustry bee species trait is secondary, - I have no idea what can be done to fix them.
