### ISSUE TITLE
Gadomancy crush

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4548]
#### Which modpack version are you using?
Eta one
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
https://github.com/GTNewHorizons/NewHorizons/issues/3502
Not fixed, still the same

**Comment by bartimaeusnek** [comment]
iirc eta doest have the updated blood arsenal version
