### ISSUE TITLE
Red Alloy Rod takes forever in the Basic Lathe

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#4549]
#### Which modpack version are you using?
2.0.7.2 Twitch Version
#
#### If in multiplayer; On which server does this happen? 
--
#
#### What did you try to do, and what did you expect to happen?
Checked the crafting time for Red Alloy Rods.
![image](https://user-images.githubusercontent.com/3237986/58209087-a1c6e680-7ce6-11e9-942b-ee1c3b805e3d.png)

#
#### What happend instead? (Attach screenshots if needed)
Takes literally forever to make.
#
#### What do you suggest instead/what changes do you propose?
Reduce the crafting time to something reasonable, 10,75 sec <-- or about 15 sec i think.

**Comment by DietmarKracht** [comment]
We've all been through this and nobody has complained.

**Comment by bartimaeusnek** [comment]
2.0.7.2 Twitch Version is not an official release. it is an unsupported beta test.

**Comment by Impos913** [comment]
Processing red alloy is same in all versions its not about 2.0.7.2

**Comment by Impos913** [comment]
I think it takes too long to make anything from red alloy. Like extruding and making plates in bender etc. (cant check now, its what I remember)

**Comment by draknyte1** [comment]
Gold also has a silly processing time. Processing times are based on atomic mass not real density.

**Comment by Hakameda** [comment]
It's fine, it gets faster when you melt the ingots and cast them
