### ISSUE TITLE
Tinkers' Construct wool slabs consume the shears

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#455]
Self-explanatory, the shears are consumed in the Tconstruct wool slab recipe.
I'd imagine this is not intentional.

**Comment by Dream-Master** [comment]
ok i try this 
`````
Shears.transformDamage()
````
and hope it works.

**Comment by Dream-Master** [comment]
If this not work i will change it to a saw (not make sense)

**Comment by Dream-Master** [comment]
ok works now
