### ISSUE TITLE
Glowstone Doped Monocrystalline Silicon Boule Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4550]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Been to this part of the game a few times and always struggle to figure out how this works. Can we add some more information to the quest to guide people how to upgrade their EBF to make these? I can't remember specifically what it takes but I think it has to be HV energy hatches? Do you have to upgrade coils to get to 2400k? Anyway...just more info in the quest maybe?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58306343-d4dda880-7dc0-11e9-86d6-ec8332de6e76.png)

**Comment by shawnbyday** [comment]
@richardhendricks awesome!
