### ISSUE TITLE
Add Quest Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4551]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Quest to collect tantalite around the enderio area in MV?

**Comment by shawnbyday** [comment]
There is already a quest for this actually BUT it is after you make the machine chassis which you need tantalum to make. Maybe just move the quest to before the chassis?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58303992-187fe480-7db8-11e9-9ea3-9557cf2d8318.png)
