### ISSUE TITLE
Tinkers' modifier quests.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4555]
2.0.7.0
You can only add 2 redstone/lapis or others at once in tool station. Add info to quest that tells you you can use crafting station to add modifiers and you can use blocks to add modifiers (lapis, redstone, quartz blocks..)

**Comment by Impos913** [comment]
Its told in crafting station quest but you domt need to put it next to a tool station to do that.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58304140-b4115500-7db8-11e9-9877-0cfdae37e1c4.png)
![image](https://user-images.githubusercontent.com/1214811/58304158-cd1a0600-7db8-11e9-8d87-441b73bd0303.png)
![image](https://user-images.githubusercontent.com/1214811/58304184-e9b63e00-7db8-11e9-9d6e-ea47d6202c47.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58304419-c344d280-7db9-11e9-88fe-3f4db5ee2e39.png)
![image](https://user-images.githubusercontent.com/1214811/58304434-d8b9fc80-7db9-11e9-97c0-54fa9da761bb.png)
![image](https://user-images.githubusercontent.com/1214811/58304439-de174700-7db9-11e9-9e8e-6a518a8aa1f7.png)
