### ISSUE TITLE
tumbaga dust in cratfing table gives too much

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4556]
#### Which modpack version are you using?
2.07.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
make tumbaga dust
#
#### What happend instead? (Attach screenshots if needed)
![afbeelding](https://user-images.githubusercontent.com/42187820/58279559-ff1e6e80-7d9e-11e9-8081-fa5fdf8bbb15.png)

#
#### What do you suggest instead/what changes do you propose?
it should only give 6 dust

**Comment by richardhendricks** [comment]
top left is *not* gold

**Comment by botn365** [comment]
it is rose gold but you stil get too much dust

**Comment by yukieiji** [comment]
It has been fixed in the latest version of GT++
https://github.com/alkcorp/GTplusplus/issues/433
