### ISSUE TITLE
Adjust lathe times/extruder should be mediocre at all tasks

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4560]
Right now the Extruder is a jack-of-all trades, but in most cases there is a better alternative, ie wiremill, or fluid extractor/solidifier, or plate bender.  The one place that isn't true is the lathe.  I think we should adjust the lathe rod recipes to make them slightly faster than the extruder at the same tier. This would add a lot more utility to the lathe.

IE, I need 128 rods, I can throw 2 stacks in the lathe to get them out faster, or throw 1 stack in the extruder to get them out much slower.

**Comment by draknyte1** [comment]
Extruder is also more efficient in the sense that it gives two rods vs a rod and dust.

**Comment by richardhendricks** [comment]
hence my 1 stack vs 2 stacks, but sometimes you want rods *now*. 👍

**Comment by Bluebine** [comment]
I think the lathe should be A LOT faster than the extruder, because it gives dust which makes it more annoying. It's already insanely fast with screws, so making it take, like, half a second per rod would be reasonable and make it worth using compared to the extruder even if it does give dusts.

**Comment by Houstonruss** [comment]
Any reason to not have the lathe just give 2 rods (or 1 long rod to cut?)and get rid of the waste dust? I understand that a real lathe would have waste, but you wouldn't make rods ON a lathe anyway, you'd extrude , cast, or roll them out... Just a balance and QoL thing anyway.
