### ISSUE TITLE
Ender Collector Crash

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4566]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Crash on Delta due to a ticking ender collector. Wasnt newly placed. Did work for several weeks now.
[Crashlog](https://pastebin.com/rPny72Fy)

**Comment by DietmarKracht** [comment]
Never overlap ender collectors!

**Comment by boubou19** [comment]
also if you drop massive amount in the range of an endercollector you'll get an internal server error disconection
