### ISSUE TITLE
New mod suggestion

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4570]
https://minecraft.curseforge.com/projects/just-enough-calculation

**Comment by 0lafe** [comment]
Idk how useful that'll be. Maybe for like rockets, but if it can't do fluids, not much past rockets is really that helpful. Nei kinda shows you enough

**Comment by Impos913** [comment]
Nei doesnt work good, takes a long time to search something and causes fps to drop.

**Comment by vectorman1** [comment]
I cannot reproduce the issues by @Impos913. NEI works fine, searching as well. The mod itself appears to be in stable shape - can we get another look at this? @mitchej123 @Dream-Master

**Comment by Impos913** [comment]
NEI was slow and laggy in an old version of the pack. But they made it work well.

**Comment by vectorman1** [comment]
Unfortunately, I discovered you crash pretty consistently when trying to insert machine processing recipes into it.

https://hastebin.com/rehasupiwu.less

**Comment by Impos913** [comment]
Oh, I havent tried it in this minecraft version but it was working fine on 1.12. Thats sad it crashes.
