### ISSUE TITLE
Ztones Garden Soil Turns to Dirt While Sprinting Across

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4571]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I was sprinting across a crop field that uses ztones garden soil. I expected everything to be ok.

The image below shows the environment around the block in question. I've never had this problem pre-2.0.7.2. Some other maybe helpful information is I'm wearing piston boots so I have a little bit of a speed boost when I'm sprinting but again even in the past wearing these this has never happened.

![image](https://user-images.githubusercontent.com/33701188/58384255-51c97780-7fa5-11e9-92dd-9d2e61afecd1.png)

#
#### What happend instead? (Attach screenshots if needed)
One of the garden soils turned into dirt and the crop was killed and the sticks popped off.
#
#### What do you suggest instead/what changes do you propose?
Not sure if anything can be done but it would be nice to have this fixed. Not really a big rush but if we can't fix it we might have to update the quest about ztones garden soil to not state that you can jump/land/sprint on them.

**Comment by Dream-Master** [comment]
Mod is not open source not sure what we can do here?

**Comment by richardhendricks** [comment]
I'll update the quest tonight.

**Comment by shawnbyday** [comment]
Yea I didn't think there was much we can do. Though it is funny because in 2.0.6.7c I think this never happened and I ran across them all the time...they were my sidewalks lol.
