### ISSUE TITLE
Hope we get a download for TickProfiler

### ISSUE THREAD

**Issue by Jocroy** [GTNewHorizons/NewHorizons#4575]
Since this is the best tool to identify lag sources on 1.7, I made a ticket to hopefully get another download link, since the old page is down: https://github.com/MinimallyCorrect/TickProfiler/issues/110

**Comment by Dream-Master** [comment]
build code from github isnt that hard. I can make a file if you want @Jocroy

**Comment by richardhendricks** [comment]
Git to work on that release! :fire_engine:

**Comment by stk2008** [comment]
Just to show interest.

getting a working version of this would be great.
Thanks

**Comment by Jocroy** [comment]
I tried to build it myself, but couldn't get it to work. This is may be due to me being a total Java scrub, but it looked like there are some dependencies needed from the dead server to compile it. This is also not really about myself, but to get a link where we can point people with new small private servers.

**Comment by Dream-Master** [comment]
yes the whole server is down. Not sure if this dependencies is realy needed or can be stored elseweher. I am not a gradle specialist so i need help with it.

**Comment by Jocroy** [comment]
No need for you to do anything Dream, moron just wanted to have the issue tracked on our side. I probably should have made that clear from the start.

**Comment by mitchej123** [comment]
[TickProfiler.zip](https://github.com/GTNewHorizons/NewHorizons/files/3561482/TickProfiler.zip)
