### ISSUE TITLE
HV Quest Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4577]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Add a quest in HV to upgrade your energy hatches on your EBF. Insert right before Vibrant Alloy?

**Comment by richardhendricks** [comment]
I added a bunch of pointers to the coil upgrades.

I assume thats what you mean?

**Comment by shawnbyday** [comment]
> I added a bunch of pointers to the coil upgrades.
> 
> I assume thats what you mean?

I know you added those. I mean upgrading the energy hatches. There is a MV quest that has you do EBF energy hatch upgrade but not a HV one.

**Comment by richardhendricks** [comment]
Already is one?

![image](https://user-images.githubusercontent.com/1214811/58686339-31ead880-8344-11e9-8206-a7d37bb828b7.png)

**Comment by shawnbyday** [comment]
I must have straight up missed it. I will check my book later and see what I did wrong.
