### ISSUE TITLE
Quest Error Witchery Foul Flame

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4578]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Quest text mentions you can burn: food item, logs or jungle saplings in the witches oven to get Foul Flame, however, you cannot use logs (which makes sense) but should remove it from the quest text.

**Comment by Dream-Master** [comment]
sure.

**Comment by richardhendricks** [comment]
I also removed the log requirement from the quest. Players can choose food items or saplings on their own.

Also changed wording to "cooking food items or jungle saplings" - you can only use food items that are normally cooked in a furnace.

**Comment by richardhendricks** [comment]
Actually, it looks pretty particular about which food items will work here as well.  Cookies and bread definitely work, including toast. Meats do as well. Baugettes or buns do not.  So will clarify vanilla cooking foods only.
