### ISSUE TITLE
Witchery Coins Quest Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4579]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Add quests to use witchery coins on? I might not be able to see them if they exist. Some for:

- Foul Fume
- Breath of the Goddess
- Exhale of the Horned One
- Mandrake Root/Mutandis

**Comment by Dream-Master** [comment]
@shawnbyday what you mean? can you describe the issue a bit. Thanks

**Comment by shawnbyday** [comment]
Sure. You give witchery coins as you complete witchery quests, however, I can't buy anything with them. I was suggesting adding things to buy with them on the: Coins, coins, coins tab. Hope that helps.

**Comment by Dream-Master** [comment]
If you open up the next withcrey quests you will spend them very quick. And you need to keep them in the dream dim to buy stuff you cant makew there like the witchery cauldron or other stuff.

**Comment by shawnbyday** [comment]
@Dream-Master you can probably close this. Thanks for the clarification!

**Comment by richardhendricks** [comment]
I think the quests already mention using the coins for this purpose.
