### ISSUE TITLE
Tweak the Essentia buffer recipe a little

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#458]
![2016-01-24_16 45 52](https://cloud.githubusercontent.com/assets/5067989/12537569/1aeac936-c2ba-11e5-897c-e05ca5b686e6.png)
Essentia buffers are the only way in an essentia tube system to hold & transport more than one type of essentia at a time. This makes them essential in almost every setup, an example of one being in the screenshot above as regular essentia tubes can only hold one type at a time.

As a result, I'd like to suggest tweaking the recipe a little, because the vis cost is really to much, with all the  *advanced* types of tubes it needs, and just how frequently you'll use these. Imo due to the mechanics of tubes, the buffers are effectively a replacement for essentia tubes at this point, not a specialty pipe in setups like above.

The troublemaker in the recipe is certainly the Restricted Essentia Tube, requiring 16 Terra and 5 Aqua per piece. If either this pipe is lowered to 5 vis cost each, or replaced for something else in the recipe, the buffers would be certainly more viable. Perhaps tiny/small GT pipes or screws used as filler for the adv pipes.

Whether or not the essentia tubes just suck and golems are superior is beyond this issue, but this just might make them used more often.

**Comment by Dream-Master** [comment]
Will see what i can do but as the name say they are advanced pipes. Golems are to cheap atm.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/12847503/fd1b9c24-cc13-11e5-806a-f075cc44402c.png)

**Comment by Teteros** [comment]
That should work nicely indeed.
