### ISSUE TITLE
Space Race Parachute Quest

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4580]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Change the parachute quest to have player craft the correct amount of materials. It needs:
- 12x Woven Cotton
- 12x Polyethylene Rod
- 5x Fine Steel Wire
- 3x Canvas

**Comment by Impos913** [comment]
There is a crafting recipe and assembler recipe, which one you looking?

**Comment by shawnbyday** [comment]
> There is a crafting recipe and assembler recipe, which one you looking?

Probably the wrong one!

**Comment by shawnbyday** [comment]
Closing this because I'm just dumb...no shocker there.
