### ISSUE TITLE
7.3 crash twice

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4587]
#### Which modpack version are you using?
2.0.7.3
single player crash twice at ross128
[crash-2019-05-28_09.14.50-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3225955/crash-2019-05-28_09.14.50-client.txt)

**Comment by bartimaeusnek** [comment]
already fixed, we must update gt++ https://github.com/alkcorp/GTplusplus/issues/479

**Comment by Dream-Master** [comment]
using newer version than 354. We using 369 in lastest dev.
