### ISSUE TITLE
Add Corporeal Attractor quest for dealing with warp bats

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4589]
Add a new Corporeal Attractor and whatever quest for dealing with bat problems.

**Comment by richardhendricks** [comment]
Might already be a quest

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58687699-feaa4880-8347-11e9-9481-f2687ac3b27c.png)

@doomsquirter

**Comment by DoomSquirter** [comment]
looks good
