### ISSUE TITLE
[Mod suggestion] Witching gadgets for TC

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#459]
With more TC pages mod, we can look into other expansions to TC if they offer new features not found elsewhere.

[Witching Gadgets](http://www.curse.com/mc-mods/minecraft/228268-witching-gadgets) is a small TC add-on adding adding mechanical tweaks and additions, such as support for forge multiparts in essentia tubes, or a way to make a cobblegen via TC, as well as other neat things like a thaumometer similar to a tome of sharing for research, allowing someone to share what they scanned to another player.

**Comment by Dream-Master** [comment]
Maybe we vote in the forum for like i make a vote for this mod:

http://forum.gtnewhorizons.com/showthread.php?tid=81

**Comment by Methes** [comment]
This mod has one slight problem and that's its coremod
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221178-travellers-gear

Adds yet another inventory button. Just a slight problem though.

**Comment by Dream-Master** [comment]
http://forum.gtnewhorizons.com/showthread.php?tid=82

**Comment by Dream-Master** [comment]
So need to be tested before we add this mod maybe.

**Comment by Dream-Master** [comment]
@Teteros 
Can you add this mod to your pack and test it in sp if this mod works well with the pack?

**Comment by Teteros** [comment]
Sure, will edit this post when it loads and I can give feedback.

**Comment by Teteros** [comment]
As for Witching Gadgets, the mod seems to be [abandonware](https://github.com/BluSunrize/WitchingGadgets/issues/92) and that alone may rule it out, [changes](https://github.com/BluSunrize/WitchingGadgets/issues/87) to implement it would be necessary as expected.

**Comment by Teteros** [comment]
Would there be interest in a thaumcraft way to get certain byproducts from ores?
Thaumic bases already some ways to process shard ores into equivalent shards, we could build upon this.

Perhaps the infernal blast furnace could be the EBF of TC, for advanced recipes... like, cooking thaumium ingots to thauminite?

Any thoughts?

**Comment by Dream-Master** [comment]
I can add all recipe i want and with the core mod all Items Blocks and Fluids we eventual need.
BUT SOMEDAY WE NEED TO FINISH THE PACK!!!

When i done with Thaumcraft scripts i will look into it.

**Comment by Teteros** [comment]
It was decided that Witching gadgets and Gadomancy will be included next update.

**Comment by deeplyarnab** [comment]
Traveller's gear? What about it?

**Comment by Teteros** [comment]
It's a dependency of Witching gadgets, so it must be it with it.

**Comment by Teteros** [comment]
WG is added to test pack.
Discuss in https://github.com/GTNewHorizons/NewHorizons/issues/497.
