### ISSUE TITLE
Waterlily Texture Broken 2.0.7.3dev

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4595]
#### Which modpack version are you using?
2.0.7.3dev
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Waterlily Texture is broken. Tried to spade and replant and same thing.
![image](https://user-images.githubusercontent.com/33701188/58522327-66646600-8185-11e9-9f1c-fc26e0da2726.png)

**Comment by Dream-Master** [comment]
@shawnbyday there was a resource file long time ago ( load it before enter the game) Nor sure why the texture is not in the mod itself @bartimaeusnek ?

**Comment by bartimaeusnek** [comment]
already fixed:
https://github.com/GTNewHorizons/NewHorizons/issues/4582
