### ISSUE TITLE
Be(e) Breeding Quest Displaying Incorrectly

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4596]
#### Which modpack version are you using?
2.0.7.3dev
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
This might be intended but the arsenic bee quest is showing as grayed out but that I've completed it already.
![image](https://user-images.githubusercontent.com/33701188/58522404-d672ec00-8185-11e9-8fc6-b5d0a8adb1b5.png)

**Comment by richardhendricks** [comment]
Arsenic Bee quest was previous quest 1115, possibly you had it unlocked before and now it is showing as unlocked still.

**Comment by shawnbyday** [comment]
I can reset it manually but I haven’t touched bees yet. I was waiting for this Dev release to start. Has it always been 1115?

**Comment by richardhendricks** [comment]
Obviously not, 1115 was an old broken quest that I deleted (the "New Quest" bug) so BQ recycled the number. If you had it unlocked already it stats unlocked. BQ should really never reuse numbers exactly because of this IMO.

**Comment by richardhendricks** [comment]
I had to add a minor quest, so I used 1115 for that and created a new quest for the arsenic bee.
