### ISSUE TITLE
Realy Ultimate Battery Recipe issue

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4604]
#### Which modpack version are you using?
2.0.7.3 dev
#
The Realy ultimate battery uses 64 of double neutronium plates. Double plates only stack up to 32. Havent tested the crafting yet but its highly related to #4189

**Comment by DietmarKracht** [comment]
![2019-05-29_14 16 43](https://user-images.githubusercontent.com/11991148/58562875-6bc7bc00-822a-11e9-8585-5e7589d33bd8.png)

**Comment by 0lafe** [comment]
Can you still make it with an LV+ hatch?

**Comment by bartimaeusnek** [comment]
@0lafe the assline doesnt accept multiple smaller stacks as input.
