### ISSUE TITLE
AE2 Stuff block crashes server

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#461]
Wireless connector crashes server when placed

**Comment by Dream-Master** [comment]
This is the Server log to the crash.

https://gist.github.com/Dream-Master/cf2f3df9128c15b4181e#file-ae2-stuff-crash

**Comment by Dream-Master** [comment]
https://github.com/bdew/ae2stuff/issues/97

**Comment by Dream-Master** [comment]
http://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

**Comment by Dream-Master** [comment]
So we add the different verion to the pack and i think this will work.

**Comment by Teteros** [comment]
Confirmed rv3 version in test server works, all that's left is update to live.
