### ISSUE TITLE
Small Ti ore 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4619]
#### Which modpack version are you using?
2.0.7.3
#

#### What do you suggest instead/what changes do you propose?

Remove small Ti on Mars. T2 is sort of early EV, gives pure Ti way too early. Maybe T3 instead, could be on Europa or something. Imo, just add the small Ti's back to asteroids, and replace tungstate. That much tungstate in IV is also kind of a lot. With changes to fortune, minering an asteroid should be like over a hundred stacks of crushed.

**Comment by botn365** [comment]
there is already small Ti ore on T3 planets just remove it from mars

**Comment by 0lafe** [comment]
That works too

**Comment by richardhendricks** [comment]
How is after the T2 rocket "early EV"?

**Comment by 0lafe** [comment]
It takes a very small amount of stuff you won't have  at the end of HV.

**Comment by Bluebine** [comment]
...why?
it's still worse than an actual vein. you get less titanium than you would from mining actual titanium veins. it's a convenience factor for people that make a T2 rocket, so you don't have to do rutile for too long.

**Comment by Anarack** [comment]
That and pure titanium is significantly more expensive energy wise to smelt.

**Comment by draknyte1** [comment]
Pure Ti was on the moon for ages. Why push small ores further back? 🤷🏻‍♀️

**Comment by ScriptedPiky** [comment]
The point of advancing to the next planet/tier is to obtain the materials in a previous age, but way better. And as others said, smelting pure Titanium requires an EV EBF and (at the current moment on 7.3) 90 - 120 seconds in the EBF (gas and no gas recipes). How does pushing these ores back even further help at all?
Someone had recently done a trip on Mars and placed a T1 multiblock miner and got around 200-300 titanium over 24 hours. Mind you that you most likely will not have a T2 or higher Ore Driller multiblock before Mars (unless you want to rush it). Pushing these things constantly back further and further doesn't make the game more difficult, you just make it more tedious and frustrating to play the game

**Comment by 0lafe** [comment]
>so you don't have to do rutile for too long.

Not too long is right, it's a fraction of a tier. Im suggesting at least pushing it to the beginning of the next tier. Down to stop the usage of it, but I think you gotta use it a good amount first. You don't need much by the T2. 

>That and pure titanium is significantly more expensive energy wise to smelt.

If that makes it not super useful post T2 EV, then it seems fine pushing to farther. If it's still better to use than rutile, then pushing it farther also makes more sense. 

>Pure Ti was on the moon for ages. Why push small ores further back? 🤷🏻‍♀️

Because putting small ores on T2 sorta misses the point of moving pure Ti out of EV. Tier metal processing being a single ebf step seems fine, but I'm not sure why it should be in the tier of the metal. Kind of simplifies it a lot. 

>Long complaint I don't wanna paste in 

Kinda, but next tier. T2 rocket is super early. Advancing tiers decreasing cost is good, but you're not really advancing in tiers, you just made a rocket. 200-300 is a fair amount, for EV at least. Imo rutile should be the EV method for material gen, and only really changed once you start focusing on another tier material. It's not really more frustrating, you get a ton of Ti equivalent through rutile. I'm not sure what's frustrating about rutile?

**Comment by NoriSilverrage** [comment]
Leave small ores alone. Small Ti on mars is not a issue. It provides nice to have amounts, but hardly enough for substantial use, thus you will likely still need moon visits to get rutile.

**Comment by richardhendricks** [comment]
Talked with Dream, he said it's not going to change.

**Comment by 0lafe** [comment]
can I get a why? All i get from this is it's useless but removing it would be the worst thing

**Comment by DoomSquirter** [comment]
dream spoketh, obeyeth the dream, stfuppeth

**Comment by Dream-Master** [comment]
let's release 2 0.7.4 first before we talk about this here.

**Comment by 0lafe** [comment]
I mean we don't need to change it for 2.0.4 I guess, but can't we talk about it for whenever it could change?

**Comment by richardhendricks** [comment]
I voted against it because 

1. We already removed Ti ore from the moon.
2. Not everyone is going to "speedtier." And if that is such a concern then maybe we should make the T2 rocket need more titanium, not remove it from Mars too.
3. A novice player is more likely to go to the Moon again before trying for a T2 rocket just to get Ti.
4. Even so, getting a few hundred Ti ore is kinda a joke considering how much you need to setup real EV infrastructure.
5. Small ores are just that, small.
6. Player building industrial infrastructure to get around a limitation is kinda the point of the modpack.

**Comment by bartimaeusnek** [comment]
addition to moron:

1. It litterally makes no sense to higher tier Ti Ore with the current Energy/Time compared to the TiCl4 route. This is a significant factor regarding larger setups.

2. In smaller Set-Ups, getting enough small Ti Ore is virtually impossible. Kind of like, you *can* make your whole base out of Nether Star Blocks in LV. But you won't do that, because it is a hughe timesink to do so.

**Comment by 0lafe** [comment]
To moron 
>1

Yes but the reasoning for it applies to removing from Mars too. Ti shouldn't be easy/simple in EV, it can be easier once it matters less

>2

Still makes Ti much simplier while still being in EV. If it was more end of EV that would be better I guess. Depends where rocket tiers fit in I guess. RN they're kinda early tier, which I think fits better with T+1 giving you easier tier mat gen. So IV gives easier EV, etc. With current tier reqs, I strongly disagree with lowering the time you spend with the processing version of your tier mat. That said, to change it to an end of tier rocket which makes the past tier easier is something I guess I'm on board for. 

>3

That's fine, that's sorta unrelated. Even post rocket they're still EV, and needing more Ti will also happen. Giving pure Ti at that point is what I disagree with. 

>4

Not much. Ti isn't used too extensively beyond some crazy AE setups, LCEs, and T2 miners which are technically IV? 200-300 titanium is more than you'll spend on most EV machinery. 

>5

Uh huh? Small ores give a TON more output than normal ores. A normal ore is 2x-5x(5?) at most, while a small ore is upwards of a stack. They'll spawn more rarely I guess? But they're still super useful, and depending on the amount spawning, are arguably better than normal ores. 

>6

Yes but there's no infrastructure and it reduces infrastructure? It takes a single craft of a rocket, which needs very little itself, to reduce the necessity of rutile infrastructure. 

-now for bartyboo-

>1 

Yeah it's the trade off of power for simplier method. I just disagree that the option for that should be avaliable this early in the tier. 

>2

Smaller setups? I mean unless we mean multiple drills, they'll be about the same output. Kinda different than stars though, unless this is just as useless/tedious, in which case I'm even more for removing the ores. 



So uh, conclusions I guess. Intratiering of rockets in tiers is weird, and maybe should be standardized/looked at? They're early tier for T2+ but late tier for HV. They gate the creation of the next tier material, and the easier method of earlier tier materials. It can be done no matter where in the tier the rocket is, but moving it to the end sort of makes sense. I guess this means the T2+ should get new recipes to push them further into the tiers. Imo, forcing LuV circuits/epoxy/tungstensteel/maybe some ++ multis or general high speed machinery, seems like a good way to go. Not sure what else is really EV atm, unless we want some type of AE gate, but that would probably just come out to a TON of crafting steps, which is ok I guess, but will need a lot of additions to make it work. Once done, this would probably apply to other rockets as well, but we should probably get one done first. Being at the end of the tier, pure Ti fits better in it, as well as tungstate/uranium.

**Comment by richardhendricks** [comment]
Weren't you the one who said players need to have multiple amps of on-tier power?  And now a player is going to speed-tier to titanium, which needs EV power in the EBF, and 10x of it at that vs Rutile? I don't buy it. 10x power consumption is a huge step up and doing that without proper infrastructure (read:nukes) is just going to murder the average player's stored power. 

Just add some higher tier circuits to the rocket, won't that will force players to build out their EV infrastructure before they can launch?

**Comment by botn365** [comment]
a higher tier circuit wont work becous you neet an ev circuit assembler to make it wich requires radon wich can only be gotten at T2 rocket

**Comment by 0lafe** [comment]
Just circuits not really, as nanos alone are a very small hurdle unless used in assline amounts. I'm not saying you need multiple amps, I'm saying you should, but that's mostly unrelated. Rutile is EV, titanium is energy to skip rutile. Imo that's not something that you should get early EV. Maybe later if the rocket moves, but simply using circuits doesn't really do that.

**Comment by sthegreat** [comment]
So the small Ti is only useful if a player builds strong powergen for their tier anyways due to the 1920 eu/t smelting anyways, right? In that case, there's really no need to change small ore spawning. A player can choose where to build their infrastructure, either weak power and rutile only or strong power and then can use some small ores.

Also, I feel like we kind of overstate the complexity of the rutile process sometimes. It's just a few machines, not like skipping it is the same as skipping the need for epoxy or something. The main difference imo is the lower titanium per ore from bauxite/ilmenite.
