### ISSUE TITLE
Obsidian blocks from TC/RC don't work in the smeltery

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#462]
The smeltery can't smelt the following Thaumcraft blocks which should be equivalent to obsidian (for normal recipes the blocks are oredicted with vanilla obsidian):
1. Obsidian Totem (ip is 920)
2. Obsidian Tile (ip is 920:1)

It would also make sense to add this Railcraft block since it is macerated Obsidian:
Crushed Obsidian (ip is 1362:4)

I think it would make sense to add those 3 things to the smeltery and they should all give the same amount as normal obsidian.

**Comment by Dream-Master** [comment]
Will add those Blocks to the smeltery tomorrow.

**Comment by Namikon** [comment]
You might want to save the thaumcraft totem blocks for later, as you'll need them for some higher tc stuff. And iirc, they only spawn and can't be crafted.

**Comment by Dream-Master** [comment]
I can add some Infusion recipe for make them. Maybe after the Sinister Loadstone Research.

**Comment by Namikon** [comment]
IMHO that takes away the search for the sinister node towers (where the node stone is used) , which is an additional challenge I'd like to keep

**Comment by Dream-Master** [comment]
@Namikon 
Maybe i make it so expensive that you better search. Only let the option open if all Obelisks are mined.
What do you think?

@WarlordWossman 
But the Smeltery recipe i wont add then because people mine the totems and not go farming obsidian somewhere.

**Comment by Namikon** [comment]
Hm, that could work. It needs to be way above the level of the osmotic enchanter then, as this is what it's used for

**Comment by Dream-Master** [comment]
Ok fine i will add it if i am nerfing Thaumic Tinkerer.

**Comment by Teteros** [comment]
Obsidian ingots to obsidian plates could also be considered, as you'd think an ingot to plate is only natural.

**Comment by Dream-Master** [comment]
sure why not

**Comment by WarlordWossman** [comment]
Well 1 obsidian block gives 2 ingots in the smeltery tho so that means you can get 2 plates from 1 block that way.

**Comment by Dream-Master** [comment]
Ok add Tile and Totem to the smeltery = 288 mb
