### ISSUE TITLE
Unweary Princess Quest Doesn't Detect

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4622]
#### Which modpack version are you using?
2.0.7.3dev
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Unweary Princess Quest Doesn't Detect purebred. (Be(e) Breeding Quest ID 2157)

**Comment by richardhendricks** [comment]
Works fine for me.  Did you use a scanned bee? I scanned a Prisitine pricess and it worked fine. Trying now for an Ignoble
