### ISSUE TITLE
Crash in controls menu

### ISSUE THREAD

**Issue by Nanimonai3** [GTNewHorizons/NewHorizons#4623]
#### Which modpack version are you using?

2.0.7.0

#### What did you try to do, and what did you expect to happen?

I tried entering controls to change hotkeys.
[crash-2019-06-01_09.46.39-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3243557/crash-2019-06-01_09.46.39-client.txt)

#### What happened instead? (Attach screenshots if needed)

After scrolling down the game freezes and crashes.

#### What do you suggest instead/what changes do you propose?

I don't know enough about the pack to propose any changes, but I do know that I did not experience this problem with Twitch launcher's current GT NH version.

**Comment by richardhendricks** [comment]
First time we've heard of this.  Can you try with the beta 2.0.7.2 available on Twitch?
