### ISSUE TITLE
[Suggestion] BSpace Upgrade

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/NewHorizons#4624]
BSpace upgrades from Jabba for the Barrels are interesting. Allowing a inventory to be shared anywhere is pretty nifty. However, the upgrades are pretty expensive severely limiting their use.

Their main component is a Adv. Ender chest. I don't have a issue with the cost of that chest as it is a powerful and versatile tool, however the BSpace upgrade isn't the same. You can only store one item in it at a time vs 27 different stacks with the Adv Ender Chest. Additionally you have access to the ender pouch further increasing the ender chests power.
Because of this reduced versatility I propose a cost reduction.

I have two ideas for how this could be achieved. 
First would be to remove the Adv Ender Chest as component of it's production and change it to use 1 or more dense enderium plates. This tiers it similar to the magic mirror.

The other idea would be simpler. Keep the inputs the same, but increase the quantity output. Currently it is 2, changing that to 4, or 8 would make it far more interesting.

**Comment by 0lafe** [comment]
Just enderium is a really small cost compared to the ender chest or most of the other wireless item movements. 2/4 outputs seems ok I guess, does make it better than the ender chest itself
