### ISSUE TITLE
Some more minor quest changes

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#4626]
it's that time again cuz i've got some more minor problems I have with the quests
- [x] The Integrated Processor quest in HV should not require the SMD Circuit Components quest in MV. These circuits don't require SMD parts. REMOVED SMD DEVICES, PUT IN TEXT TO USE WHICHEVER YOU PREFER, THERE IS NO OREDICT FOR THESE COMPONENTS BECAUSE THEY ARE NOT IDENTICAL ACROSS THE BOARD.
- [x] The Integrated Processor, Processor Assembly, Workstation Extreme Circuit, Microprocessor LV, and IV Circuit Mainframe quest should accept either SMD or non-SMD parts- SMD parts aren't required for any of these. DONE
- [x] The IV Circuit Mainframe quest should have a note added saying that it consumes less resources if SMD components are used- to encourage people to make them, instead of forcing them to. DONE, SEE BELOW
- [x] The Silicone Rubber quest shouldn't require chlorine and methane- chloromethane can be made from HCl and methanol, too. Instead, make the quest only require chloromethane, and mention both of the ways it can be made in the quest itself.
- [x] Ruby Electrolyzation should NOT be gated behind the LV oil quest- that's such an odd thing for it to be gated behind, and makes no sense. Just gate it behind MV electrolyzer. DONE
- [x] The Super Tank quest in MV shouldn't be gated behind the Better Tank... HV Tank quest. There's little point in making most of the GT++ tanks except ULV, and the super tanks are EXTREMELY useful to mention. Instead, just gate them behind the MV pump. DONE
- [x] The Glowstone Doped Monocrystalline Silicon quest in HV should be gated behind the kanthal coil upgrade quest. Kanthal coils are required to make these. I KNOW, BUT INSTEAD I PLACED A POINTER TO THE KANTHAL QUEST, OTHERWISE YOU WOULDN'T KNOW IT IS NEEDED. SEE BELOW.
- [x] Gate the MV and HV Battery Buffers quest behind the MV and HV Batteries quest, instead of the other way around. Gating batteries behind their buffers is a very weird approach.  CHANGED THE ORDER, AND MODIFIED THE TEXT AND REQUIREMENTS, SEE BELOW.
- [x] The Dragon Egg quest in HV should be moved to the EV tab, and gated behind reaching Mars. The egg can't actually be completed until you reach Mars, so it'd be odd to start it any sooner. DONE, ALSO CHANGED UNIVERSAL CELL TO VOLUMETRIC FLASK FOR FUTURE UNIVERSAL CELL REMOVAL.
- [x] Add a quest for tin cans to HV, after the "You gonna hate this 1-4" quest. It would require the player to make an HV bending machine, then create a stack of tin cans, then fill the cans with food. (The HV canner isn't required for this BTW- the HV bender is needed to make the tin cans, but an LV canner can be used to fill the cans)
- [x] The HV Extruder quest image is actually a bending machine. Should be changed to an extruder. 
- [x] Mark the "Oak trees are not apple trees" quest as a main quest. It gates a whole bunch of stuff in the Coins Coins Coins tab, so players need to know that it's important to do. BUT IT DOESN'T BLOCK PROGRESSION MOTHERFUCKER THE QUEST ALREADY SAYS IT UNLOCKS THE COINS TABS. :)
- [x] The diamond armor quest should be gated behind iron armor, not gold armor. Not many people are gonna make gold armor, so diamond armor should be gated behind something that people are more likely to make. ALREADY DONE, DIAMOND NOW GATED BEHIND LV CUTTER.
- [x] In the Electro Magic quest, add quests for the Electric Boots of the Traveller, Nanosuit Boots of the Traveller, and Quantum Boots of the Traveller. They're ENORMOUSLY useful. ADDED AND GATED BEHIND BOOTS OF THE TRAVELLER QUEST IN NOVICE THAUMATURGE
These are all problems I've noticed on .7.0. Sorry if any of these are already fixed.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58750746-a9f7f200-845b-11e9-97a0-18870dd6122c.png)
![image](https://user-images.githubusercontent.com/1214811/58750795-2d194800-845c-11e9-8610-b96ee5327535.png)
![image](https://user-images.githubusercontent.com/1214811/58750928-c006b200-845d-11e9-849d-1b51c2320ba1.png)
![image](https://user-images.githubusercontent.com/1214811/58750955-0cea8880-845e-11e9-80ed-169491b460c5.png)
![image](https://user-images.githubusercontent.com/1214811/58750984-6357c700-845e-11e9-8f2e-a405d744635f.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58751182-f0038480-8460-11e9-93b0-6ec87928fe41.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58752391-c56ef700-8473-11e9-9515-a9f85724a3e5.png)
![image](https://user-images.githubusercontent.com/1214811/58752392-c99b1480-8473-11e9-9976-e7d18c77bf6c.png)
![image](https://user-images.githubusercontent.com/1214811/58752393-cd2e9b80-8473-11e9-9ca2-872347eafa5a.png)
