### ISSUE TITLE
LV recycler quest text: stone suggested but blacklisted

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#4627]
#### Which modpack version are you using?
2.0.7.0  
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Quest 1875 reads: `If you have too much wood, saplings, dirt or stone, just recycle it and get scrap` so I hooked up a transfer node with world interaction and ended up getting no scrap from cobblestone, nor with a furnace in between to turn it into normal stone as per the quest text.
#
#### What happend instead? (Attach screenshots if needed)
At least cobble, stone, and cobble stairs refused to go into the recycler via automation. Manual insertion ate several stacks each of these without producing scrap.
#
#### What do you suggest instead/what changes do you propose?
Running the UU tree off unprocessed cobble could be considered cheesy and is probably rightfully blacklisted as such. I would update the text accordingly:
> If you have too much wood or saplings, just recycle it in a recycler and get scrap. In the future you can use it to make UU-amplifier, which is used to make UU-matter cheaper.
> 
> Note though that the recycler won't produce anything from particularly cheap materials, such as stone and cobblestone.

**Comment by richardhendricks** [comment]
Already done for 7.3

![Uploading image.png…]()
