### ISSUE TITLE
Steel dust processing

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#463]
To make an ingot, one steel dust in Blast furnace takes
50 seconds and 120k EU.

While iron ingot takes just
25 seconds and 60k EU.

Intended?

**Comment by Dream-Master** [comment]
It is Gt Code i not change it. So i guess it is intended.

**Comment by WarlordWossman** [comment]
It is supposed to be harder since dust is something that you get in processes like macerating random mob loot or safing materials by making steel rods in a lathe for example.

**Comment by Dream-Master** [comment]
So i close it. If someone have a better idea we can reopen it.
