### ISSUE TITLE
Alternate pollution handling schemes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4630]
In addition to advanced mufflers and scrubbers, how about

1. a recapture muffler, one that outputs the pollution to a pipe, to be handled in a separate machine?

2. A big ass fan to redistribute pollution among chunks faster, or a longer distance.  Like at MV it does 1 chunk radius at 350k vs 400k. At HV it does 2 chunk radius, at EV it does 3 chunk radius. Spreads out the pollution to more chunks, faster.

**Comment by Methes** [comment]
Pollution spreader that releases pollution from the pipe back into the air would be awesome too.
With recapture mufflers cheap enough you could finally place them at each machine and create a proper ventilation system and either be eco about it and process the pollution or spew it all out in your neighbour's area.

**Comment by 0lafe** [comment]
If we're gonna make pollution differentnly manageable can we also make it matter? Most of the negative effects aren't impactful, and you can spend most of your time without remembering pollution is a thing. 

It's gotta hurt more than your player for it to really be impactful

**Comment by richardhendricks** [comment]
Can make it affect airbreathing generators and maybe cleanroom efficiency.  Other option would be to have hazmat suit not completely negate effects, but only lessen them.  IE suit is like pollution is 1/4 or 1/8 the level. That way at high enough levels you still want to mitigate it.

**Comment by shawnbyday** [comment]
I think moving slowly is one of the biggest impact effects you can have short of death. Nothing is more frustrating than moving slowly.

**Comment by Methes** [comment]
Pollution should affect not only players and sometimes vegetation, but also crops and bees. Having a smog effect (lowering visibility) would be great too. Maybe even _slowly_ change biome type all the way to Wasteland.
On a side note: radiation could be greater threat too. Dealing with radioactive materials outside of a sealed room could raise radioactivity in a chunk with consequences.

**Comment by combusterf** [comment]
Having a ghetto biome changer could actually prove useful for bees ;)
