### ISSUE TITLE
Crash after shift-clicking the thaumometer recipe in arcane worktable

### ISSUE THREAD

**Issue by faqza** [GTNewHorizons/NewHorizons#4633]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
I shift-clicked the thaumometer recipe in the arcane worktable game immediately crashed
#
#### What happend instead? (Attach screenshots if needed)
Game immediately crashed
[crash-2019-06-02_11.33.39-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3244491/crash-2019-06-02_11.33.39-server.txt)

**Comment by DoomSquirter** [comment]
you closed this cause you probably realized this does happen from time to time.

**Comment by Dream-Master** [comment]
I guess so. Its a random error maybe the mod load so heavy at some time.

**Comment by DoomSquirter** [comment]
yeah it's a can't fix really
and when you get thaum ae the problem goes away completely
