### ISSUE TITLE
[Recipes] Assembly line need few changes.

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#4636]
#### Which modpack version are you using?
2.0.7.0

ok here a list of some finding when assembly line.

- [x] SMD pattern is not consensent in make circuits.
- [x] Bioware Supercomputer ask for SMD Diode twice.
- [x] Object Holder ask for 1000/mB Molten Iridium it should be 1152/mB
- [x] Hollow Casing ask for 576/mB of argon gas it should be 500 or 1000
- [x] Deep Earth Heating Pump ask for 32 HSS-E Gear in one slot
- [x] FusionTech MK IV ask for 10 dense neutronium Plate it should be 8.
- [x] Really Ultimate Battery need 64 double neutronium plate in one slot

here is the link for all the item for 2.0.7.0 the page will be updated after the 2.0.7.x is in public.

https://gtnh.miraheze.org/wiki/Assembly_Line_Recipes

**Comment by bartimaeusnek** [comment]
Deep Earth Heating Pump fixed in https://github.com/bartimaeusnek/bartworks/commit/d29b986b46133e0815f053972f9e5fa5a7b8e8d4

**Comment by bartimaeusnek** [comment]
Really Ultimate Battery need 64 double neutronium plate in one slot https://github.com/GTNewHorizons/NewHorizons/issues/4604

**Comment by bartimaeusnek** [comment]
FusionTech MK IV ask for 10 dense neutronium Plate it should be 8. Is this GT++ or did we changed the recipe?

SMD pattern is not consensent in make circuits.
Bioware Supercomputer ask for SMD Diode twice.
Object Holder ask for 1000/mB Molten Iridium it should be 1152/mB
Hollow Casing ask for 576/mB of argon gas it should be 500 or 1000
are in TecTech

can you change these Recipes please @Dream-Master ?

**Comment by Dream-Master** [comment]
i think i fix it to 32 so far ik or 16 need to check

**Comment by Dream-Master** [comment]
will fix more

**Comment by Dream-Master** [comment]
FusionTech MK IV is a GT++ issue

**Comment by Dream-Master** [comment]
all other issues fixed

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/pull/493

**Comment by Dream-Master** [comment]
https://circleci.com/gh/alkcorp/GTplusplus/370#artifacts/containers/0

**Comment by Dream-Master** [comment]
waiting for gt++ but can use the version on ci i guess
