### ISSUE TITLE
Radon Quest Order Issues

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4641]
The lead lined box quest should be before the radium decay quest in EV due to it helping bulk production vs just clogging inventory for a while.

**Comment by Anarack** [comment]
Changed this to all radon quests as the current order makes you use both? sources for some reason.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58910187-7e366f80-86da-11e9-8986-05862d46d95e.png)
