### ISSUE TITLE
Awakened Draconium Coil

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4647]
#### Which modpack version are you using?
2.0.7.3 dev
#
Its impossible to obtain awakened draconium coils anylonger as the draconium needs to be smelted at 10800 K but the highest possible heat value is 9900 K with electrum flux coils.
![2019-06-04_13 51 55](https://user-images.githubusercontent.com/11991148/58877006-f51a3b00-86cf-11e9-96e0-70d7dd15553b.png)

**Comment by Dream-Master** [comment]
ok will  lower it.

**Comment by bi9lamer** [comment]
DietmarKracht, u can up heat value increasing the voltage in ur EBF to UV/UHV.

**Comment by bartimaeusnek** [comment]
@bi9lamer no you cant make the heat higher than the coils. Voltage and Coil heatage are two different things.

**Comment by bi9lamer** [comment]
@bartimaeusnek try it with GT++ EBF

**Comment by bartimaeusnek** [comment]
GT++ Heating Coil bug does no longer work with 2.0.7.3DEV

**Comment by Dream-Master** [comment]
ok set it back to 9K or so would fix the issue i guess.
