### ISSUE TITLE
Wrong backpack recipe when using Forestry Worktable

### ISSUE THREAD

**Issue by Wegifan** [GTNewHorizons/NewHorizons#4648]
#### Which modpack version are you using?
2.0.7.0

When I want to craft a middle backpack before reaching moon, I accidentally find this wrong recipe.
It use no Ti and simplify the procedure so it need to be corrected.
![1](https://user-images.githubusercontent.com/49618165/58879190-a4263900-8707-11e9-9107-bd6d66becb31.png)
![2](https://user-images.githubusercontent.com/49618165/58879191-a4becf80-8707-11e9-9bcc-e053c46584e3.png)

**Comment by richardhendricks** [comment]
Recipe does not exist in 8.0?
![image](https://user-images.githubusercontent.com/1214811/71522317-c80ac100-2889-11ea-98f4-ca7b34f591ce.png)
