### ISSUE TITLE
Preview: Additional Tinkers Construct tiering

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#465]
I've been adjusting a few TGregworks materials so you can continue using the sword/pickaxe you have been using since the start all the way to and past the neutronium tier.
Still tinkering with the values but this is the gist of it:
http://imgur.com/a/ZFPmT
https://docs.google.com/spreadsheets/d/186YJBZIjh8TyhhdQdxaBkSnAalCOyIcmJMlv762zak8/edit?usp=sharing

**Comment by Namikon** [comment]
Really looks nice; I approve

**Comment by Dream-Master** [comment]
:+1:

**Comment by Drobac** [comment]
Got the values all set as they should be, but i cant change the mining level of the materials. It was generally meant to empower weapons but id still like the tools to get a boost as well. And yes ive tried adjusting the materials in the IguanaTweaks config but that doesnt seem to affect TGregworks materials

**Comment by arnabbiswasalsodeep** [comment]
I suggest starting maybe from the lower tiers making the high tier swords have a base damage of 20 hearts and the crossbows of that tier have 90+ attack damage. This will give us 40 attack values for sword with different materials (with increment of 0.5)

**Comment by Drobac** [comment]
that is what i wanted to do as well but sword damage and arrow damage correlate with one another. Had adamantium swords do 20 damage but that caused crossbows with adamantium to deal 200 hearts damage which is a bit too much (http://imgur.com/a/ntVfz). Ill probably add higher attack damage on damage on neutronium so we have a high attack damage Sword material which is useless with arrows.

**Comment by Drobac** [comment]
I didnt do more then 3 materials per tier as you will always try to go for the best possible material available at your tier and are the type of materials that require some processing or have little other use which makes it good for tool materials. Also the materials i picked fit in the tiering system already set up

**Comment by Dream-Master** [comment]
@Drobac 
so is this finish now or we need more materials to change?
