### ISSUE TITLE
Questbook broke

### ISSUE THREAD

**Issue by shitstainlord** [GTNewHorizons/NewHorizons#4650]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
Load up my game expecting it to work as per usual
#
#### What happened instead? (Attach screenshots if needed)
Questbook broke, spamming endless quest complete messages, unlocked pages up to Tier 5, even though I'm at Tier 2, the quests completed were bunch of empty quests with no description.

![2019-06-05_00 22 16](https://user-images.githubusercontent.com/50236595/58914984-96cd7680-8728-11e9-8ed5-faa6284c95ad.png)
![2019-06-05_00 22 24](https://user-images.githubusercontent.com/50236595/58914985-96cd7680-8728-11e9-9c9f-9136cba1ee94.png)
![2019-06-05_00 22 27](https://user-images.githubusercontent.com/50236595/58914986-96cd7680-8728-11e9-8da2-181286a6e10f.png)

#
#### What do you suggest instead/what changes do you propose?
Possible fix?

**Comment by Methes** [comment]
You're using old version of modpack so the first step should be updating to the most recent one.

**Comment by richardhendricks** [comment]
You could try doing a 

/bq_admin default load

It shouldn't lose your progress, but you should probably back up your quest .JSON files in your save directory anyways.
