### ISSUE TITLE
The Following Bees Don't Detect

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4651]
#### Which modpack version are you using?
2.0.7.3dev-Experimental GT
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?

I noticed on the old bee line it shows as "Unknown Genome" instead of an identified species. Maybe we try changing that?

So far the following bees don't detect:

- [ ] Clay Bee
- [ ] Sweetened Bee
- [ ] Tin Bee
- [ ] Copper Bee

Here is a list of bees that did detect just fine:

- Iron Bee
- Zinc Bee
- Nickel Bee
- Aluminium Bee

**Comment by Dream-Master** [comment]
Old bees means Gendustry ? @shawnbyday if yes I don't fix there anything because bees get removed soon.

**Comment by shawnbyday** [comment]
These are the new bee quests moron made.

**Comment by Dream-Master** [comment]
A Quests ok

**Comment by richardhendricks** [comment]
Are these the latest version from Github, or the old 2.0.7.3?

**Comment by shawnbyday** [comment]
From the experimental GT you sent me in Discord. GTNH 2.0.7.3dev but with the fixed GT.

**Comment by richardhendricks** [comment]
Thats weird since I confirmed the quest worked with bees I bred.  Did you try analyzed and not analyzed? I think I removed the pristine/Ignoble requirement too, but maybe try that too.

**Comment by shawnbyday** [comment]
**Sweetened Clay Bee**
Didn't detect the bee either scanned or not scanned. Tried throwing on ground too for both scanned and not scanned. Here are the scanner results for what seem like relevant pages.
![image](https://user-images.githubusercontent.com/33701188/59164932-72331f00-8ad9-11e9-89b1-55ebdee1aabf.png)
![image](https://user-images.githubusercontent.com/33701188/59164934-75c6a600-8ad9-11e9-93bc-ba2627bce8ad.png)
![image](https://user-images.githubusercontent.com/33701188/59164938-7a8b5a00-8ad9-11e9-8992-d3ed4cb8a5ce.png)

**Comment by shawnbyday** [comment]
**Copper Bee**
Didn't detect the bee either scanned or not scanned. Tried throwing on ground too for both scanned and not scanned. Here are the scanner results for what seem like relevant pages.
![image](https://user-images.githubusercontent.com/33701188/59164969-0b623580-8ada-11e9-9267-94d78bc14225.png)
![image](https://user-images.githubusercontent.com/33701188/59164971-0f8e5300-8ada-11e9-8769-501324a79c21.png)
![image](https://user-images.githubusercontent.com/33701188/59164973-13ba7080-8ada-11e9-827b-9e99b55f3cfd.png)

**Comment by shawnbyday** [comment]
**Clay Bee**
Didn't detect the bee either scanned or not scanned. Tried throwing on ground too for both scanned and not scanned. Here are the scanner results for what seem like relevant pages.
![image](https://user-images.githubusercontent.com/33701188/59164984-35b3f300-8ada-11e9-9d72-75f5fbcfc0ec.png)
![image](https://user-images.githubusercontent.com/33701188/59164987-39e01080-8ada-11e9-92f3-36e98d09b915.png)
![image](https://user-images.githubusercontent.com/33701188/59164988-3c426a80-8ada-11e9-918b-22f5d87249aa.png)

**Comment by shawnbyday** [comment]
**Tin Bee**
Didn't detect the bee either scanned or not scanned. Tried throwing on ground too for both scanned and not scanned. Here are the scanner results for what seem like relevant pages.
![image](https://user-images.githubusercontent.com/33701188/59165011-9a6f4d80-8ada-11e9-94ba-7ad249b796f1.png)
![image](https://user-images.githubusercontent.com/33701188/59165012-9d6a3e00-8ada-11e9-8976-bd3954dd4256.png)
![image](https://user-images.githubusercontent.com/33701188/59165013-a0652e80-8ada-11e9-9d2d-8b6891f78e9e.png)

**Comment by shawnbyday** [comment]
Sweetened Bee is Binnie...rest are GTNH. When you click the bee in the questbook it takes you to a breeding tree where the bees are Forestry. So maybe the questbook is looking for the forestry version of the bees?

**Comment by Dream-Master** [comment]
NBT errors i guess. Make Bee quests are very difficult remove the right nbt tag and not the wrong one.

**Comment by richardhendricks** [comment]
Shawn was using outdated questbook.  With latest in-dev questbook, the bees are detected OK.
