### ISSUE TITLE
[Question] My Error or bug?

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#4656]
#### Which modpack version are you using?
2.7.0
#

#### If in multiplayer; On which server does this happen? 
Private sever
#

#### What did you try to do, and what did you expect to happen?
#

#### What happend instead? (Attach screenshots if needed)

chrash the client

https://pastebin.com/WV5M9wpK

#

#### What do you suggest instead/what changes do you propose?

**Comment by Dream-Master** [comment]
remove invtweaks or use a different version. cant say for sure what happend here.

**Comment by boubou19** [comment]
is this a random crash or regular crash? what were you doing before the crash?

**Comment by Ldmf** [comment]
Rnd error
Puting items in a jabba Barrel (gt items like pumps dust)

**Comment by boubou19** [comment]
then i guess nothing ca be done sadly

**Comment by richardhendricks** [comment]
Is bug still occurring?

**Comment by Ldmf** [comment]
I think it Was rnd error if it coms agan i will Post a uptade and reopen the Problem
