### ISSUE TITLE
new rf

### ISSUE THREAD

**Issue by wissanu020430** [GTNewHorizons/NewHorizons#4657]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#

**Comment by DoomSquirter** [comment]
best ticket ever, 8/10, would read again.

**Comment by stk2008** [comment]
That was a long read phew I'm tired now reading that huge in depth write up.

Really goes into detail its amazeing

**Comment by Dream-Master** [comment]
????????

**Comment by DietmarKracht** [comment]
TL. DR.

**Comment by wissanu020430** [comment]
Remove Non-present Devices using DevCon
=======================================

removedevices.js is a script to automatically remove all non-present (i.e.
disconnected) devices from a Windows computer system.  This can often be
useful to prevent misbehaving and/or unnecessary drivers from being loaded.

WARNING
-------
This script will remove/uninstall devices from your computer system.
Although several important types of devices have been excluded from the
default removal process, the possibility of removing devices critical to
the operation of your computer system still exists.  PLEASE double-check
the list of devices which will be removed before pressing "Y" and PLEASE
create a system backup if you are remotely concerned about making your
system unbootable.

Examples
--------
 - To remove all non-present devices (except legacy and software devices)
   either double-click the script or invoke it from the command prompt
   without options.

 - To delete devices without confirmation, run

        removedevices.js /noconfirm

 - To see the output of DevCon as the script executes, run

        removedevices.js /verbose

 - To create a list of devices which would be removed, run

        removedevices.js /outfile:devicelist.txt

 - To delete all devices (device IDs) listed in a file, run

        removedevices.js /infile:devicelist.txt


More Information
----------------
Installation instructions are available in INSTALL.txt.
Major changes are listed in ChangeLog.txt.
Complete license text is available in COPYING.txt.

The latest version of this software and the bug tracking system are
available on GitHub <https://github.com/kevinoid/remove-nonpresent-devices>.

**Comment by wissanu020430** [comment]
**SETUP**

Update credentials / port numbers in `deploy/build.properties`, then:

    ml local bootstrap
    ml local deploy modules
    mlcp.sh -options_file mlcp.patent.properties
    mlcp.sh -options_file mlcp.ipc-class.properties

Then, unfortunately, in QC, select `patent-demo-content` and run:

    import module namespace process = "http://marklogic.com/roxy/lib/classification-process"
      at "/application/custom/ext/classification-process-lib.xqy";
    process:process()

Note the commented-out transformation in `mlcp.ipc-class.properties`
(see known issues for details)

**FUNCTIONALITY**

**Landing Page**

Typical assessment builder search app. The only enhancements to this page are the tooltips
for the classification facet/chiclet, but they only display on page load (see known issues).

**Patent Document View**

This is a customized interface. The patent document is transformed into HTML on the server,
and then enhanced with a variety of related JSON data retrieved via the REST API.
Referenced classifications are retrieved, and can be further explored in a pop-up window.
Patents related to those classifications are also linked. Users can request a licence
for the patent, or suggest prior art that may invalidate the patent.
Cited patents are linked (although most won't exist, see known issues).

**KNOWN ISSUES**

**Classification Facet Tooltips**

The classification description tooltips only display on page load. I spent several hours
experiment with MutationObservers and overriding jQuery functions to emit custom events,
but was unable to reliably display the tooltips as a user interacts with them.

**MLCP Transformation Errors (Classifications)**

I implemented an XQuery module for transforming the classification XML when uploaded with MLCP,
but, for reasons I can't determine, that transformation errors out: 'missing socket'.
I read through the MLCP source, but the actual error is from com.marklogic.mapreduce.ContentWriter,
which is in a separate project. The configuration works fine without the transformation., 
so something else is causing the socket to disappear. I created a simple test case to
split documents via MLCP, and that worked just fine.

**MLCP Transformation Errors (Patents)**

There's a date-parse error when loading the patent XML files. I've tried running the parser
from QC, and been unable to reproduce the error. I can't seem to find any logging options
for MLCP. The error doesn't appear to have impacted the application in any way.

**Patent Citations Dead Links**

The majority of patent citation links with simply display "no results found".
This is because I've only included a small quantity of patent documents.
Years worth of patents would obviously be many GB of XML ...

**Patent Images Missing**

Patent images are not included in the source data from http://patents.reedtech.com/pgrbft.php

**NOTES**

The patent XML is published as a ZIP archive of a single "XML" file, which is actually
a concatenation of thousand's of XML files. I split that into files using `awk`:

    awk '/^<\?xml/{close(x);x="ipg140107."++i".xml";next}{print > x;}' ../ipg140107.xml

**RESOURCE LINKS**

Classifications info:
http://www.uspto.gov/patents/resources/classification/

IPC Classifications:
http://www.wipo.int/classifications/ipc/en/ITsupport/Version20140101/index.html
http://www.wipo.int/ipc/itos4ipc/ITSupport_and_download_area/20140101/definitions_viewer/en/en_20140101_definitions_viewer.htm

IPC XML schema:
http://www.wipo.int/ipc/itos4ipc/ITSupport_and_download_area/20140101/MasterFiles/
IPC Schema docs:
http://www.wipo.int/export/sites/www/classifications/ipc/en/guide/guide_ipc.pdf
http://www.wipo.int/classifications/ipc/en/faq/#G17

Patent XML:
http://patents.reedtech.com/pgrbft.php

Patent XML Schema Docs:
http://www.uspto.gov/products/PatentGrantXMLv42-Documentation.pdf

Miscellaneous Resources

CPC:
http://www.cooperativepatentclassification.org/cpcSchemeAndDefinitions/Bulk.html
http://intellogist.wordpress.com/2012/07/12/ready-or-not-the-cooperative-patent-classification-has-arrived/

US:
http://patents.reedtech.com/classdata.php

**Comment by Bluebine** [comment]
now this is true art. beautiful. just beautiful.
thank you for your amazing contribution to GTNH.

**Comment by Dream-Master** [comment]
??????????????????????????????????????????????????????????????????

**Comment by DietmarKracht** [comment]
report that guy pls

**Comment by ItzzGamma** [comment]
no u

**Comment by sleepylucy** [comment]
What the fuck is happening

**Comment by ItzzGamma** [comment]
idk lol this is a meme post i think
