### ISSUE TITLE
Machines higher than IV have a recipe conflict

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#466]
UV Alloy smelter and UV Furnace have the same recipe

**Comment by Teteros** [comment]
Try the Remote IO intelligent workbench, it resolves recipe conflicts.
Until it's fixed in master.

**Comment by Dream-Master** [comment]
The ZPM Level Furnace and Alloy Smelter have the same Problem

**Comment by Namikon** [comment]
Oops.. 
Will fix that when I add the remaining machines

**Comment by Drobac** [comment]
yep used the intelligent workbench to make it. Probably affects the LuV as well

**Comment by Dream-Master** [comment]
Will change that in the Core Mod code.

**Comment by Dream-Master** [comment]
fixed

https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/b5186fdece2b1c30838f3754367e984bb0174b7f

https://github.com/GTNewHorizons/GT5-Unofficial/commit/334b01dac00de7d6068b2e64acfd208cd8ed02be
