### ISSUE TITLE
Camera bug at 4K

### ISSUE THREAD

**Issue by snoudin** [GTNewHorizons/NewHorizons#4663]
#### Which modpack version are you using? 2.0.7.0

#
#### If in multiplayer; On which server does this happen? The same problem at singleplayer and local server

#
#### What did you try to do, and what did you expect to happen? If use Fhd everything is ok

#
#### What happend instead? (Attach screenshots if needed)
If move camera left or right it “falls” down
Sorry for my English. Hope, you will understand me
#

**Comment by Bluebine** [comment]
Can you include a video? We're going to need to see exactly what's going on, this isn't a glitch that's ever been reported before, as far as I know.

**Comment by 0lafe** [comment]
There's a weird thing in MC where it'll slowly move your view in a direction if you have some weird resolutions. Idk if that's the same, but it sounds similar
