### ISSUE TITLE
LCR change (nerf/small buff?)

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4666]
#### Which modpack version are you using?
2.0.7.we

#### What do you suggest instead/what changes do you propose?

LCR's are kind of really really good atm for a few reasons. They're unlocked in HV, have perfect overclocking, and simply require a new hatch to uptier. Imo having all 3 of those makes them way too good, and I have some ideas to make them a little better. 

First remove the perfect overclock. Make it a normal one, or something like 3x/4x. Most of the time the LCR won't be your speed bottleneck, so this isn't terribly noticable, but would have a greater impact after the tiers of the mk2 option. Even overclocking like a normal CR, the advantages of it are still strong. No more cells, and they're easier to use for fluid automation. Still a multi you'd want to get when you can, if you want to setup chem automation. 

Next, limit the eu/t that can be input to coil tier. This way the coil is something that's adjusted to the tier of the CR, and gives it a slightly better overclocking cost. With it being not a great overclock, the cost is fairly low at 1 coil, but it makes it a little better. Cupronickel being LV, kanthal MV, nichrome HV, tungstensteel EV, etc. 

Lastly, add an LCR mk2 or something of the sort. Same idea, but would be IV ish, use things like PBI/epoxy instead of PTFE, and generally be a higher tier version of the original LCR. It could be a 4x5x4 or something, to give it a little more utility. More space for hatches means it's a little more forgiving for poor fluid handling. It could also have more coils inside, which would increase the overclock cost by some factor depending on how many coils. Imo 8 seems nice, 1/2 an ebf cost so it's still fairly low. Most CR recipes aren't done at tiers past IV, so it would really just be about speed increases. The overclocking mechanics of this CR would be the current perfect overclock of the LCR, as that feature is very useful post IV. If we really want to make this a lot better by eliminating some of the more difficult issues of the current LCR, there could be some sort of way to change out the integrated circuits easier than the current LCR. Not really needed, but just another way to make it worth it.

**Comment by sthegreat** [comment]
I disagree with this change because I really don't see the need... this honestly feels like a nerf just to nerf. It's not like there's some big issue with HV people being able to process their chemicals quickly, and there's no issue with the current LCR times for circuit boards (main user of chem reactor time) either. In fact circuit boards remain annoyingly slow even with the LCR.

**Comment by Scottishprog** [comment]
Not really seeing the need.  Why bring this up now?  For example the Forestry farm multilayered stuff is recent, so dealing with it now makes sense.   The LCRs have been as such for a while, what is the actual issue?  _NOT_ "too good"  What is the _actual issue?_  

I don't like the trend of pushing everything to late game - the rewards for pushing up tiers should be distributed along those tiers.  Not to mention the encouragement of rushing.

**Comment by 0lafe** [comment]
>I don't like the trend of pushing everything to late game - the rewards for pushing up tiers should be distributed along those tiers. Not to mention the encouragement of rushing.

Except IV is midgame, and the HV option is still a large bonus to singleblocks even with a 2/4 or 3/4 OC 

>what is the actual issue? NOT "too good" What is the actual issue?

That's the issue though, with all that the LCR has it really is too good. This separates some of the better qualities to the areas of the game that need them more (lossless OC) and gives it a more substantial upgrade cost (coils).

**Comment by sthegreat** [comment]
Wasn't the whole purpose of the energy hatch nerfing thing to give a more substantial cost to upgrading multis?

**Comment by 0lafe** [comment]
In a way yes, but the costs of them are nothing compared to your ability to make things at these points. A single hatch is a very low cost for upteiring a whole multi, especially early on compared to the cost of the multi itself. Most are around the difficulty of a singleblock, but mostly easier. No circuits until LuV+ and uses minimal tier components. If we want to make hatches much much more expensive across the board I guess that's always an option, but personally im much more in favor of multi specific upgrade costs that are more easily changeable for the specific multi.

**Comment by Folanlron** [comment]
> First remove the perfect overclock. Make it a normal one, or something like 3x/4x. Most of the time the LCR won't be your speed bottleneck, so this isn't terribly noticable, but would have a greater impact after the tiers of the mk2 option. Even overclocking like a normal CR, the advantages of it are still strong. No more cells, and they're easier to use for fluid automation. Still a multi you'd want to get when you can, if you want to setup chem automation.

This doesn't matter, you can sit there and make Boards at overclocked speeds all day, your still limited by the Circuit Assembler and Cleanroom machines, and just starting out at HV it's slow as hell, even lower tiered circuits.
  
> Lastly, add an LCR mk2 or something of the sort. Same idea, but would be IV ish, use things like PBI/epoxy instead of PTFE, and generally be a higher tier version of the original LCR. It could be a 4x5x4 or something, to give it a little more utility. More space for hatches means it's a little more forgiving for poor fluid handling. It could also have more coils inside, which would increase the overclock cost by some factor depending on how many coils. Imo 8 seems nice, 1/2 an ebf cost so it's still fairly low. Most CR recipes aren't done at tiers past IV, so it would really just be about speed increases. The overclocking mechanics of this CR would be the current perfect overclock of the LCR, as that feature is very useful post IV. If we really want to make this a lot better by eliminating some of the more difficult issues of the current LCR, there could be some sort of way to change out the integrated circuits easier than the current LCR. Not really needed, but just another way to make it worth it.

Better solution, give us a 2 tank IN/2 tank OUT Single block HV CR(And you'll never see the LCR used again), that is the massive benefit of the LCR, your don't have too deal with the shitty cell system anymore, the whole "perfect" overclock doesn't matter as you are still limited by the machines after it, so WHY?

**Comment by Scottishprog** [comment]
Then look at the multis overall. I repeat, why are we looking at the LCR now?  (I think it's ok that some classes of problems are solved by a given tier. It's shouldn't be necessary to keep adjusting _all_ production when tiering up all the time.)

**Comment by 0lafe** [comment]
>This doesn't matter, you can sit there and make Boards at overclocked speeds all day, your still limited by the Circuit Assembler and Cleanroom machines, and just starting out at HV it's slow as hell, even lower tiered circuits.

Uh yeah, kinda I guess. I think you're less limited there and the boards take the majority of the time, but idk if that's true. Even if the boards are the worst, you're still limited by the other materials that go into circuit usage. 

>Better solution, give us a 2 tank IN/2 tank OUT Single block HV CR(And you'll never see the LCR used again), that is the massive benefit of the LCR, not having too deal with the shitty cell system anymore, the whole "perfect" overclock doesn't matter as you are still limited by the machines after it, so WHY?

Uh, what? I mean I get the 2 slot singleblock sorta, but even that would still not be as useful as the LCR, as there are LCR specific recipes. What do you mean by limited by the machines? Like the other parts of the steps that will use the things made in the CR? You're mostly slowed down by other things, but in some ways that's the point. The CR is really good comparatively, and the lossless overclock puts it above almost anything else. 

>Then look at the multis overall. I repeat, why are we looking at the LCR now? (I think it's ok that some classes of problems are solved by a given tier. It's shouldn't be necessary to keep adjusting all production when tiering up all the time.)

Maybe not all, but giving most the same tiny cost isn't great. You get more functionality out of them when tiering up, quite a lot more with lossless overclocking. Apart from ++ which we have no control over this aspect of, the LCR is the multi that benefits the most from an uptiering and really has no downsides. Other multis/singles require either more resources or the same as the LCR, and most will get a lossey overclock in return, baring the ebf which can get a few losslesses, but also has the coil cost. Uptiering costs is part of the game, and without them you'd be spending much less resources on progression. You really don't spend resources upgrading the LCR, but you totally should. It gains utility when uptiered, that should cost something at least. Removing a running cost for an upfront cost is already super good, but having almost no cost is way too good. 

I'm not sure what you mean by now. It's not really about talking about it in a time frame that fits it, it's bringing it up because no one else has and it's stupid OP. I tried to get it nerfed over a year ago, but I didn't really go about it too well, and removed the cell utility too early while not totally addressing the OP issues of it.

**Comment by richardhendricks** [comment]
I'm OK with having coils set the max limit, but I think those correlations are too low. I'd start with CN at HV, and go up from there, so it's a little more natural with when you'll start yanking coils out of your EBF and upgrading them, and what tier you want to do combined recipes.  Along with the new requirements, I think a small speed boost based on coil tier is appropriate as well, similar to how pyros work.

**Comment by Scottishprog** [comment]
One final comment:  

Keep in mind, multiple LCR will be used.  When balancing, consider the fact that there might be 10+ in a base...

I would rather this not get touched at all, but if it is, price it with a large number of LCRs in mind.
Note this is with the recommendation of massive parallelization in order to keep processing time under control...

**Comment by 0lafe** [comment]
I tiered them according to crafting tier, to make them somewhat costly. In the single coil LCR even this is barely anything, just needing 8 ingots. 8 cupronickel ingots in HV is nothing, and even 8 nichrome isn't too much. However one gives a goodish upgrade cost, while the other is practically free at that point. These are also in conjunction with an energy hatch, comparatively T-2 coils aren't really adding a cost on top of the hatch

>so it's a little more natural with when you'll start yanking coils out of your EBF and upgrading them

Seems like that means you'll never really make a coil for the LCR, which sorta defeats the purpose of increasing cost through coils. If it's not only a low resource cost, but one you're likely to already have lying around. 

>Along with the new requirements, I think a small speed boost based on coil tier is appropriate as well, similar to how pyros work.

Could use this as the overclock instead. Remove perfects and work with 2/4 that's boosted by coils. 50% faster per tier or whatever kinda works well for overclocking, but not for at tier running. It just becomes somewhat of a partial to multiple lossless overclock, with the exception of the tier recipes running at extensively faster speeds. Imo, having either a parallel count, overclock loss reduction, or speed bonus to overclocked recipes would be better for the LCR. The issues are never running recipes at tier, and the perf overclocks are certainly fast enough, if not too fast. 

Also, pyro uses 9x the LCR, and has worse overclocks just the speed. Having both on the LCR with less upgrade cost is just a big ol no imo. 

>I would rather this not get touched at all, but if it is, price it with a large number of LCRs in mind.
Note this is with the recommendation of massive parallelization in order to keep processing time under control...

First, not really true on the needing them to keep time under control. You really just need 1 per circuit integration, and even that's more than you need if you do it right. That said, you'd need to make 16 before it equated to 1ebf, and at this point you probably have 2+. Depending on the LCR and how you set it up, you won't always need to use a tier coil on it anyway even if it voltage locks to the coil tier. Many recipes are low tier and don't always need to be overclocked to your tier. Especially when diversifying into multiple LCRs.

**Comment by Scottishprog** [comment]
There seems to be a few "ifs" involved.... If this is going to be the expected path of play - can we record the "optimal" ratios/setups somewhere? There seems to be an expectation that the player will play a certain way....

As I see it, you want to nerf the LCR in _two_ ways:

 - Straight up cost - make it cost more.
 - Lesser speed/tier locked speeds.

I don't know what to say on the additional costs - I hate to say it but one coil isn't so bad.
As for the overclock - leave it as is, but lock max Eu/T input to tier. (Although I don't like you proposed coil/tier pairs, we _start_ building these things in HV...   I have two EBFs, but no LCRs, due to the difficulty in getting enough Florine.)

If you _must_ put in a TII version, I say have an option of the original 3x3 OR a larger version. This allows the player to "drop in" the improved version into an existing setup.
