### ISSUE TITLE
Quest #84 Where can i put all the liquids won't update if you make the screws in lathe

### ISSUE THREAD

**Issue by Pallinaama** [GTNewHorizons/NewHorizons#4669]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
official epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to complete quest, made 4 iron screws in lathe to progress the quest.
#
#### What happend instead? (Attach screenshots if needed)
Quest did not recognize 4 iron screws.
#
#### What do you suggest instead/what changes do you propose?
Make the quest accept iron screws made in machines as well as by hand. This may affect other quests too.

**Comment by boubou19** [comment]
was the task a crafting task? if it was a crafting task it's normal.

**Comment by Pallinaama** [comment]
> 
> 
> was the task a crafting task? if it was a crafting task it's normal.

It was. I didn't realize that was working as intended when you have other options to you. I'm dumb.
