### ISSUE TITLE
quicksand

### ISSUE THREAD

**Issue by abitaredomdepo** [GTNewHorizons/NewHorizons#4671]
![11111111111111111111111111111](https://user-images.githubusercontent.com/51705777/59271185-f7ded800-8c5b-11e9-8fae-bcb5b08a0ad7.png)

**Comment by boubou19** [comment]
what's the issue?

**Comment by abitaredomdepo** [comment]
> В чем проблема?

no problem. but I would like more realism. quicksand can be made but when digging quicksand sand should be obtained. I hope you understand) Google translator helped me Kappa

**Comment by repo-alt** [comment]
You can imagine that you are digging with a bucket :)

**Comment by abitaredomdepo** [comment]
> Вы можете себе представить, что вы копаете с ведром :)

did not understand you

**Comment by repo-alt** [comment]
Ну, если серьёзно, зыбучий песок актуален только в самом начале игры, когда его можно использовать как ловушку. Когда доступен миксер, есть уже куча других способов. Т.е. реализация этого предложения (если я его правильно понял), сделает песок ещё более бесполезным.

**Comment by abitaredomdepo** [comment]
![sad_frog](https://user-images.githubusercontent.com/51705777/59298147-8a9a6980-8c92-11e9-985d-b454fd29668e.jpg)

**Comment by richardhendricks** [comment]
I think we can add a shapeless recipe to make quicksand from sand, water bucket (clay or iron), and dirt. Quicksand would be useful to protect your initial base from unwanted monsters.

**Comment by abitaredomdepo** [comment]
my recipe is better ^_____^

**Comment by Dream-Master** [comment]
sand stone dust and air maybe cool

**Comment by Methes** [comment]
There's usefulness and coolness. Can't really have both here.
