### ISSUE TITLE
Forestry Boggy branch not breeding

### ISSUE THREAD

**Issue by xtake** [GTNewHorizons/NewHorizons#4673]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta, my own private world, wherever Mineanplay plays
#
#### What did you try to do, and what did you expect to happen?
Breeding Miry bees on server. Breeding Miry and Boggy in creative test world. I expected them to breed after a bunch of tries or in test world with creative 100% mutation at least.
#
#### What happend instead? (Attach screenshots if needed)
They didn't breed.
#
#### What do you suggest instead/what changes do you propose?
Well I don't know if you can add custom breeding stuff if yes then add a new bee which replaces that or somehow change the old one to actually work.

**Comment by richardhendricks** [comment]
I assume your end goal is to get peat?  Try breeding a Peat bee, crossing Clay with Rural.

**Comment by richardhendricks** [comment]
Uh, you might need a newer version of GT5u, the clay bee in that is currently ungettable. Cheat yourself in one if you want to test.

**Comment by richardhendricks** [comment]
I am able to start breeding the Boggy branch just fine.  Are you sure you are in an appropriate biome?  Make sure you make a habitat locator to confirm the temp and humidity.

![image](https://user-images.githubusercontent.com/1214811/59324484-b6bee600-8ca4-11e9-99b8-bcacd904e775.png)

I found Rainforest to work.

![image](https://user-images.githubusercontent.com/1214811/59324492-bcb4c700-8ca4-11e9-98ff-7727e81a230e.png)

**Comment by xtake** [comment]
Peat does not have anything to do with miry/boggy bees? I am trying to get elastic bees.
Clay I already have which wasn't a problem at all I even got it by accident.
Yes I was in appropriate Biome I was in a Jungle which is Warm, Damp. 
I even used an alveary to create my own warm damp biome which didn't work either. 
Are you using the same version of GTNH? And where are you testing it?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/59372385-020cdf00-8d0d-11e9-88eb-086b404afe5e.png)

**Comment by richardhendricks** [comment]
User was able to fix the issue with the correct biome and mutagenic frames.
