### ISSUE TITLE
Flask and Soldering iron texture is wrong

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4674]
#### Which modpack version are you using?
2.0.7.3dev
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What happend instead? (Attach screenshots if needed)
Flask and Soldering iron texture is wrong.
Also fluid texture in some flasks was broken
![2019-06-12_13 08 12Iron](https://user-images.githubusercontent.com/40425798/59322888-400d0180-8d13-11e9-9b1d-bb61ae79112f.png)
![2019-06-12_13 10 57flask](https://user-images.githubusercontent.com/40425798/59322976-ab56d380-8d13-11e9-85e9-a100ad4e99fc.png)
#
#### What do you suggest instead/what changes do you propose?
fix it.

**Comment by Ethryan** [comment]
This has already been fixed in GT5-Unofficial, what i did to fix it for myself was downloading the textures from https://github.com/GTNewHorizons/GT5-Unofficial and replacing them into the GT5 installed in the mods folder.

**Comment by Dream-Master** [comment]
@Ethryan can you do a pull request for Gtnh ? Thanks @Ethryan

**Comment by Ethryan** [comment]
@Dream-Master This is already fixed on https://github.com/GTNewHorizons/GT5-Unofficial
There is no pull to make, I only described how i fixed this ony my own 2.0.7.3dev instance.

**Comment by Dream-Master** [comment]
if textures are missing why not pull them to gtnh branch ? @Ethryan

**Comment by Ethryan** [comment]
There is no missing textures, 
bartimaeusnek fixed this with the revert of https://github.com/GTNewHorizons/GT5-Unofficial/commit/e9a1ffaf34d83c38f0ee8364eebf6f42ad4a40a3.
Please close and mark as already fixed this issue.

**Comment by Dream-Master** [comment]
ok thanks for clarification
