### ISSUE TITLE
Existing magic solar panels crash the server

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/NewHorizons#4678]
#### Which modpack version are you using?
2.0.7.4
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Loading a world with compressed/Magic solar panels crashes server right after loading them.
The server has single compressed order and entropy panels.

https://pastebin.com/ptRdKbQq Crashlog

**Comment by SampsaxD** [comment]
Some more fudging around: Even spawning in panels and placing them on any connected cable crashes the server with the same error.

**Comment by richardhendricks** [comment]
Tested Barts fix, I don't get crashes with the solar panels.
