### ISSUE TITLE
Suggestion: Gravestone mechanics.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#468]
Yesterday i had a face to face contact with hungry node.
Ofc it nommed the grave stone, so there is a suggestion. Change gravestone mechanic:
-Bedrock type resistances
-No hitbox (can be walked trough, also by mobs)
-Picked up only by right click, would be great if that was even possible in blocked WG regions

According to the code it should be possible to set minimal and maximal spawn heigth.

I forked the openBlocks mod with the supposed solution for "bedrock graves". There is allso issue posted by me on the openBlocks repo linking to proposed solution.

**Comment by Technus** [comment]
Added two lines of text to OP

**Comment by Technus** [comment]
Added Fork of Open blocks with suggested fix, needs to be checked

**Comment by Dream-Master** [comment]
Please suggest this on Open Blocks side because i think we not have the resources for change every Mod. Or if you have Java Knowledge you can add it/change it by your self.

**Comment by arnabbiswasalsodeep** [comment]
By "Bedrock type resistances" do you mean not breakable by nodes? or what? Cuz otherwise the player itself might not be able to break it.

**Comment by Teteros** [comment]
You only need a block with hardness 5 or above for it to not be sucked in by the hungry node [(source)](https://www.reddit.com/r/feedthebeast/comments/35euyi/til_hungry_nodes_can_be_contained_with_any_block/).

Blast resistance/block hardness does not concern the player, but explosions (you can break fused quartz and hardened stone, but not something more special like warded blocks, right?)

What's the status on https://github.com/GTNewHorizons/OpenBlocks/commit/72feb6a5d2c1529b111ac662ddd5a9b29c405255 and can this be closed?

**Comment by deeplyarnab** [comment]
I think we can prevent void deaths by using this skript plugin's script https://www.spigotmc.org/resources/void-teleport.15409/

**Comment by Namikon** [comment]
I considered adding that when I had died several times back in the days where I played myself. But the problem with that is, that you cannot control how and when this is triggered.
For example: You are in the End, and fall into the void. > Free tp back to your base.
Second example: You are far away and want to go home; Sleep above 128 > Free tp.

**Comment by deeplyarnab** [comment]
I considered the end scenario but the free tp to base to escape from ender dragon or just cuz is a player dependent thing. Still those r a few problems of real concern, using the gravestone mechanic seems the best way to get the stuff done effectively.

**Comment by Dream-Master** [comment]
Any news here?

**Comment by Dream-Master** [comment]
So no one help me here. i close this now.
