### ISSUE TITLE
AdancedNanoChestPlate recipe adjustment

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#469]
Replace iridium plates in the recipe with titanium plate so it is tiered properly

**Comment by Dream-Master** [comment]
Why Titanium? Between Iridium and titanium Tier there are Tungsten Steel and Chrome Tier.

**Comment by Drobac** [comment]
Because the AdancedNanoChestPlate is supposed to be tiered to Moon, and all its other parts indeed are except for those 2 plates

**Comment by Dream-Master** [comment]
will see what i can do here.

**Comment by Dream-Master** [comment]
Moon is on IV Level (because of the High Energy Circuits)?
I will change it to chrome plates (1700 k EBF)
