### ISSUE TITLE
Two small bugs with the HP Solar Boiler

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4690]
#### Which modpack version are you using?
2.0.7.4-Dev

#### If in multiplayer; On which server does this happen? 
Zeta

There are currently two issues with the HP solar boiler at the moment. For one, it has incorrect GUI textures (see below), and that the output of the HP Solar Boiler does not meet what the tooltip states: "Produces 360L of Steam per second", or rather, 450L of Steam per 25 ticks in an operation. Simplified to 360L/sec of course. However, in reality, it will only produce 300L of Steam every operation/25 ticks; or 240L of Steam per second for the simplified way. In this case, it's only doubling the Steam of a regular solar boiler (150L Steam per operation, 120L every second), and not tripled as the tooltip states. This is when it is not calcified by the way.

The bugged GUI texture screen:
![2019-06-15_03 20 03](https://user-images.githubusercontent.com/41557212/59550361-a9149500-8f1e-11e9-83a1-bf59dabc31eb.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by bartimaeusnek** [comment]
will change tooltip & re-add texture, i guess i must have deleted it by accident
