### ISSUE TITLE
GT Drilling Rig does not mine GT++ ores in the Everglades

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4692]
#### Which modpack version are you using?
2.0.7.0

#
#### If in multiplayer; On which server does this happen? 
Both MP and SP

#
#### What did you try to do, and what did you expect to happen?
I set up a Drilling Rig in the Everglades, expecting it to mine GT++ ores such as Lautarite and Perroudite, to get Iodine which is needed to make Abyssal Alloy (for UHV energy buffers)

#
#### What happened instead? (Attach screenshots if needed)
The drilling rig mined all ores except for the GT++ ores. 

![2019-06-15_17 48 15](https://user-images.githubusercontent.com/43228249/59557721-ee27de00-8f95-11e9-8b55-0a370c5a192f.png)

#
#### What do you suggest instead/what changes do you propose?
I expect the Drilling Rig to mine GT++ ores, so I propose that all of the GT++ ores get added as mineable ores by the drilling rig.

**Comment by BlackFlameTNT** [comment]
i was talking with alk with this and it is not a bug you need to use Experimental Deep Earth Drilling Platform - MK I for that and as far i know it is WIP

**Comment by observeroftime02** [comment]
Huh, interesting. I'll go try that, although it should just work, because there's no mention of this anywhere.

**Comment by BlackFlameTNT** [comment]
i heard at 7.0 its a cube or you need to update GT++ not sure

**Comment by observeroftime02** [comment]
So, the expeimental deep earth drilling platform does not validate it's structure, no matter what I try.

![2019-06-15_18 51 37](https://user-images.githubusercontent.com/43228249/59558078-ab1e3880-8f9e-11e9-942b-e3e02cca66e4.png)

What am I missing here?

**Comment by BlackFlameTNT** [comment]
its WIP as far as i know
