### ISSUE TITLE
[2.0.7.5] Direct link to item recipe in questbook stopped working.

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4696]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
#### What did you try to do, and what did you expect to happen?
In previous versions of modpack, you were able to see item recipe by clicking on the item in questbook.
#
#### What happened instead? (Attach screenshots if needed)
In 2.0.7.5 nothing happened.
(R key or Left-Mouse button also doesn't provide recipe)

**Comment by boubou19** [comment]
maybe related to nei changes?

**Comment by Dream-Master** [comment]
try to search for a recipe in nei first. After this recipe works in questbook too. @TimeConqueror

**Comment by TimeConqueror** [comment]
After some minutes it begins working again.
