### ISSUE TITLE
Vanilla wolves spawn issue

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#470]
According to what i seen on SSP correct biome for their spawn should be taiga based, yet no biome like that is seen on the map.

Would recommend setting up some spawn mechnics.

(Requirements for witchery mod, no possible means of spawning them exist)

**Comment by Dream-Master** [comment]
@Teteros @Careface1g

is this a problem ?

**Comment by Drobac** [comment]
Check TF snow biomes for wolves

**Comment by Drobac** [comment]
Check TF snow biomes for wolves

**Comment by Technus** [comment]
Just did, found direwolves and TF direwolves.

**Comment by ProsperCraft** [comment]
I found two groups of vanilla wolves in Twilight

**Comment by arnabbiswasalsodeep** [comment]
Twilight spawns are there, but overworld spawn has been reduced majorly

**Comment by Namikon** [comment]
I don't see a problem with that :P Consider it "gregified" :)

**Comment by Dream-Master** [comment]
So then we close it :+1:
