### ISSUE TITLE
Some wrong Twitch files of ver2.0.7.5

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4700]
#### Which modpack version are you using?
2.0.7.5 Twitch
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I started GTNH ver2.0.7.5 with Twitch
#
#### What happened instead? (Attach screenshots if needed)
Forestry is installed with two different versions.
New very cool GTNH BG pic was not installed.
When I tried to log in to the server of ver 2.0.7.5, some mods were missing.

・Forestry is two different versions.
![2019-06-17_21 28 01](https://user-images.githubusercontent.com/40425798/59604327-d3e13200-9146-11e9-8900-a0e16848064e.png)
![キャプチャ_22](https://user-images.githubusercontent.com/40425798/59604376-f8d5a500-9146-11e9-88fa-c6579b221690.PNG)

・New very cool GTNH BG is missing
![キャプチャ_2](https://user-images.githubusercontent.com/40425798/59606042-215f9e00-914b-11e9-9d6a-a725671f765f.PNG)

・Some Mods is missing
![2019-06-17_21 50 14](https://user-images.githubusercontent.com/40425798/59606145-608def00-914b-11e9-95ab-31ad78d8c213.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by richardhendricks** [comment]
#4711
