### ISSUE TITLE
Opening the inventory causes the game to lockup for a few seconds when using Twitch launcher

### ISSUE THREAD

**Issue by Denwey** [GTNewHorizons/NewHorizons#4704]
When using the _Twitch_ launcher, opening the inventory causes the game to lockup for a few seconds. Note that this _may_ take several minutes of gameplay to happen, but it always ends up happening anyway.
When using the _Technic or MultiMC_ launchers instead, opening the inventory is always instant.

I've had this same issue when playing through Project Ozone 2, in which case I switched over to MultiMC and never had it again.

Note that in both cases NEI takes some time to complete searches, and this doesn't lockup the game, just make the search take some time to show results, so search time may not be related here, unless NEI tries to make the search every time the inventory gets opened.

For reference, I'm on version 2.0.7.5, and here's my simplified PC specs:
CPU: i7-7700K
RAM: 16 GB
GPU: GTX 1070 Ti
OS: Windows 10 x64

**Comment by Dream-Master** [comment]
I add twitch support for that people don't use or like another launcher. Never make benchmark

**Comment by richardhendricks** [comment]
Need to do comparison, probably related to Java version I think. Maybe memory allocations too.

**Comment by boubou19** [comment]
does it happen everytime or just one time?

**Comment by DoomSquirter** [comment]
whatever the case may be, I'd appreciate it that it stays up on twitch.  I can download pack w/o ever touching launcher, something you can't do on technic.  

also twitch defaults to it's own java.  you have to change it config wise to use the java installed by you.
