### ISSUE TITLE
GT shovel not craftable

### ISSUE THREAD

**Issue by makoto47** [GTNewHorizons/NewHorizons#4705]
#### Which modpack version are you using?
Version 2.0.7.5 (the current version)
#
#### If in multiplayer; On which server does this happen? 
---
#
#### What did you try to do, and what did you expect to happen?
craft GT shovel with flint for quest
#
#### What happened instead? (Attach screenshots if needed)
unable to craft GT shovel, no recipe found in NEI
despite previous versions of the pack being able to do so
#
#### What do you suggest instead/what changes do you propose?
suggest a fix or a solution to the problem

**Comment by Dream-Master** [comment]
craft tico shovel is much better. Gt shovels disabled

**Comment by Dream-Master** [comment]
show me a version where it working @makoto47

**Comment by richardhendricks** [comment]
The GT flint tools quest (flint axe/shovel/pick) is a required part of the questbook. Are you sure it was disabled??

**Comment by Anarack** [comment]
I can craft GT flint shovels. Yes the gt flint tool quest still exists in 2.0.7.5. Local server and client combo.

**Comment by Impos913** [comment]
Flint shovel is still craftable in 2.0.7.5

**Comment by makoto47** [comment]
![shovel](https://user-images.githubusercontent.com/51930874/59643099-61c91700-915f-11e9-978d-3e7da15a74db.png)

flint GTshovel is needed to complete quest, not crafting, cannot complete quest

**Comment by bigbass1997** [comment]
It can still be crafted, in 2.0.7.5.
![image](https://user-images.githubusercontent.com/790116/59643872-14818100-9130-11e9-9be7-589dd3b8b4a1.png)

@makoto47 Did you update from a previous version of the pack?
Also, which client/source did you use to download and install the modpack?

**Comment by makoto47** [comment]
downloaded from twitch, did not update

**Comment by richardhendricks** [comment]
Does the MOTD say 2.0.7.5 when you start up?

**Comment by makoto47** [comment]
![GT version](https://user-images.githubusercontent.com/51930874/59645816-d43ff400-916b-11e9-9219-7864fd6102dc.png)
only just downloaded it today
should i just try from a different source?

**Comment by richardhendricks** [comment]
Yeah, download it from a different source.  Apparently our method of getting around the Twitch restrictions isn't working right. 
#4711
