### ISSUE TITLE
Rebalance Adventure Backpacks?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4709]
Right now Adventure Backpacks require 1 aluminium plate, which makes them MV tier.  I was thinking it would be nice to have access to them at LV. To make it a little gated, perhaps we replace the aluminium with steel and require an LV assembler to put it together. Looks like it should fit in a 6 slot assembler. It will still require doing some bees to get combs, and a centrifuge to get beeswax+ compressor to make Pam's wax, and a forming press to turn the bound leather into hardened leather.

MV right now is the coal jetpack and the copterpack.  As much as it pains me, I think we should retier the copterpack a little higher - perhaps require it to need higher tier circuits, like Workstation (EV-tier)?

i think replacing the tiny steel fluid pipe on the right center with an EV tier circuit would be reasonable.

![image](https://user-images.githubusercontent.com/1214811/59654957-224dfb00-915e-11e9-9911-4158e75ee1ba.png)

**Comment by Scottishprog** [comment]
So, you are saying Mid-HV tier?

Not really a fan, as I found the mobility makes things much less tedious.  

Let me make a counter-proposal: IF you make this change - make the coal jet pack slightly more useful.  I consider the current form minimally useful, if that. 
Perhaps only burning fuel when operating?  Something to make it less clunky. 

Two peeves:
The bubbling while hot. (So one doesn't want to keep it lit off.)
The hang-time until hot. (So it really isn't transportation as much as a glider booster, a clumsy one.)
Heck, making the hot noise more tolerable might do it.

Then waiting an extra tier will be more tolerable.

**Comment by DoomSquirter** [comment]
someone will have to verify for me.  the thaumostatic harness, while it uses a chest inventory slot, is far superior to the copterpack but is gated about the same time I think as copterpack.

**Comment by richardhendricks** [comment]
Isn't the TH limited in range though?  Or drians charge pretty quick without the recharge/refuel convenience?

The noise we might be able to tone down buy adjusting it in a resource pack right?
Does the coalpack accept blocks/compressed coal?
So if we reduce the noise, you can just leave it on all the time without issue?

**Comment by DoomSquirter** [comment]
not really limited in range and you can just bring more jars of essentia with you
it's somewhat slow unless you make the harness + belt and add speed enchants to them

you can change all the jetpack's noises in the config.  I always turn off the coal jetpack noises cause the gurgling is ultra annoying and sometimes gets stuck when u login to server etc

**Comment by Dream-Master** [comment]
@richardhendricks we have enough low tier backpacks so please let the Adventure Backpacks in MV otherwise the low tier bags are obsolet.

**Comment by Dream-Master** [comment]
maybe coal jetpack in mv and copter in hv is much better. I can replace the tiny pipes with stainless steel pipes and maybe a circuit hv

**Comment by richardhendricks** [comment]
I guess that works.  I still think putting adventure backpacks in LV is a better idea, but I guess players can swap between backpack and coal jetpack once they make it. 

👍 on copterpack using stainless steel pipes and HV circuit.

**Comment by Methes** [comment]
Not to give you bad ideas, but why move copter pack to HV? Flight is quite a big QoL and copter pack is decent at that. What's more, the Electrical Jetpack is at HV right now and I believe is in a perfect place. Wouldn't that make the Copterpack obsolete?

**Comment by richardhendricks** [comment]
No, I don't think so. The copterpack is great for long distance travel and for perfect hover.  The electric jetpack is only a few minutes of travel, and the hover is not stable.

**Comment by richardhendricks** [comment]
Also, the EJ is harder to recharge on the go IMO vs the copterpack.  Maybe we should move the EJ to MV as a sidegrade to the coal jetpack?

**Comment by richardhendricks** [comment]
Methes, Right now the Coal Jetpack and Copterpack are available once you get into MV.  The copterpack needs a few more machines to make, but not alot of separation really.

**Comment by Methes** [comment]
I agree with your points, although I have to point out the EJ has stable hover mode for quite some time now as discussed in #2942, creating an issue with Advanced Nano having worse flight abilities.
