### ISSUE TITLE
Create Jenkins autobuilds for our newer forks.

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#471]
Add these to our jenkins to be build automatically whenever we rebase upstream/master.
https://github.com/GTNewHorizons/ProjectRed maintaned by @Teteros
https://github.com/GTNewHorizons/OpenBlocks maintained by @Technus

**Comment by Namikon** [comment]
Scheduled for 13.02.2016

**Comment by Namikon** [comment]
ProjectRed has been added. OpenBlocks pending, as the fix is considered to cause trouble in certain conditions. As discussed in GTNH#2016-2, further investigations regarding disabled item-usage over y120 is done by me, "once I have time (tm)"
