### ISSUE TITLE
Master ticket for Twitch launcher issues in 2.0.7.5

### ISSUE THREAD

**Issue by Serglittle** [GTNewHorizons/NewHorizons#4711]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Own server
#
#### What did you try to do, and what did you expect to happen?
Tried to connect to server after update from Twitch launcher
#
#### What happened instead? (Attach screenshots if needed)
Error: Mod rejections [FML:detravscannermod{1.5.4}, FMLMod:thaumicbases{1.4.18}]

Manual file installation does not help. Twitch launcher just removes both of them
![image](https://user-images.githubusercontent.com/25683853/59658994-da56c480-91ad-11e9-956e-16160761783c.png)

**Comment by Dream-Master** [comment]
Yes ik Twitch version have a few issues and i cant find out why. Need to upload a new version when fixed.

**Comment by bigbass1997** [comment]
I have created a list of all the differences I noticed between the v2.0.7.5 installs of the Twitch and Technic launchers.

The Twitch install is missing the following mods:
- GT Scanner Mod
- InGameInfoXML
- LunatriusCore
- Thaumic-Based

There are a lot of mods whose filenames are different (different version numbers or formatting differences) between the two installs, but are the same file size. These shouldn't cause any problems, but still should be noted:
- BiblioWoods (BiomesOPlenty, Forestry, and Natura versions)
- GTNewHorizonsCoreMod
- IC2 Nei Plugin
- ModTweaker2
- OpenBlocks
- ProjectRed (all versions)
- StorageDrawers
- Thaumic-Machina

These mods have different file sizes, despite having the same filenames:
- Carpenter's Blocks
- ironchest
- WitchingGadgets

Five of the script files contain differences:
- Avaritia.zs
- Biome-o-Plenty.zs
- Emt.zs
- Minecraft.zs
- Project_Red.zs

The questing files are also radically different between the two installs.

**Comment by Dream-Master** [comment]
I am working on it

**Comment by Dream-Master** [comment]
Ok i fixed that all mods now present.
Having different file size can be happend if the mbps patcher patching the files and give it a different size.
The differnt names mean nothing if the file is the same (mod name in the jar)
Script maybe newer than the technic scrits (avaritia use oredicted items instead of gt  items)

**Comment by Dream-Master** [comment]
lastest update let me join so i guess issue is solved on my side.
