### ISSUE TITLE
Gendustry machines need unavailable combs

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4716]
Gendustry machines require specific combs that are no longer obtainable since we removed gendustry bees.

- [ ] Bee receptacle
- [ ] Power Module
- [ ] Climate Control Module
- [ ] Mutatron
- [ ] Advanced Mutatron

maybe others?

**Comment by xtake** [comment]
- [ ] Mutatron

- [ ] Advanced Mutatron

**Comment by richardhendricks** [comment]
already fixed
