### ISSUE TITLE
Crash while opening Wiremill

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4719]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
#### What did you try to do, and what did you expect to happen?
Tried to open GT LV Wiremill.
#
#### What happened instead? (Attach screenshots if needed)
Crash.
https://pastebin.com/fmuhXW8k

**Comment by Bluebine** [comment]
random crashes just kinda happen sometimes. I wouldn't report them unless it happens again after a relog
