### ISSUE TITLE
Crash when clicking the search tab in creative

### ISSUE THREAD

**Issue by warrenher** [GTNewHorizons/NewHorizons#4722]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
/
#
#### What did you try to do, and what did you expect to happen?
In creative, I tried to click on the search tab in order to look for an item. I expected it to pop up and let me search the item.
#
#### What happened instead? (Attach screenshots if needed)
The game suddenly, right after clicking on the tab, froze and crashed afterward. Crash report: https://pastebin.com/wpYNZGVn
All I added to the modpack was Chunk Pregenerator 1.7.10-2.1 and therefore Optifine (1.7.10_HD_U_D6)
#
#### What do you suggest instead/what changes do you propose?
/

**Comment by DoomSquirter** [comment]
that is a bug that shows up in many packs with lots of items, etc.  very very doubtful it'll ever be fixed.

**Comment by warrenher** [comment]
Oh, I see. I guess solely using NEI for searching stuff would "fix" it, then.
