### ISSUE TITLE
Gravel and Dirt generation

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4723]
#### Which modpack version are you using?
2.0.7.5 

Too many gravel and dirt are generating underground and must be decreased. 
Slowing you when mining veins. 
Destroying veins.

**Comment by richardhendricks** [comment]
Nothing was done to change this for any of our releases.  Also, the gravel/dirt generated is part of the world generation and biome-dependant. We can take a look but it isn't going to be a priority.

**Comment by Dream-Master** [comment]
Nah its not a bug and i think the dirt and gravel packs underground ok.
