### ISSUE TITLE
Quest for Witchery: Lycanthropy level 5 (Wolf Man Form)

### ISSUE THREAD

**Issue by Goatflakes** [GTNewHorizons/NewHorizons#4725]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Official EU server Epsilon
#
#### What did you try to do, and what did you expect to happen?
I summoned the Horned Huntsman with the Horn of the Hunt (7328), that was good, horn disappears as it apparently should, but before I could kill the Horned Huntsman he wandered onto my plot and vanished!

<https://sites.google.com/site/witcherymod/lycanthropy>

#
#### What happened instead? (Attach screenshots if needed)
I thought maybe ask the Wolf Altar for another horn but he just bitches 'The voice echoes, "THE HUNTSMAN LIES UNDEFEATED! SUMMON HIM WITH THE HORN AND LAND THE KILLING BLOW!"'

#
#### What do you suggest instead/what changes do you propose?
Ability to buy a Horn of the Hunt (item id 7328) with coins, probably Dark Wizard coins, but I don't know what would be appropriate level of coin, because I was gifted lycanthropy and the Wolf Altar.

**Comment by Jocroy** [comment]
I'm not against your suggestion, but this is mostly an issue with plots and the offical servers. Afaik, you are supposed to kill him on the first try or deal with the consequences, namely, summoning the Huntsman the hard way.

**Comment by richardhendricks** [comment]
What's the hard way?

**Comment by richardhendricks** [comment]
ah nvm, https://ftb.gamepedia.com/Horned_Huntsman

**Comment by richardhendricks** [comment]
Proposed coins quest. Unlocks after quest 333 Offerings in witchery tab, 
![image](https://user-images.githubusercontent.com/1214811/71537105-e51caf80-28dc-11ea-8085-2a4590f4cf21.png)
