### ISSUE TITLE
Witchery: Lycanthropy 5 quest (Wolfman form): Need a Horn of the Hunt! (7328)

### ISSUE THREAD

**Issue by Goatflakes** [GTNewHorizons/NewHorizons#4726]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
EU live server Epsilon
#
#### What did you try to do, and what did you expect to happen?
I was doing the Lycanthropy level 5 quest, which involves talking to the Wolf Altar, he gives you the Horn of the Hunt (7328) and tells you to blow it to summon the Horned Huntsman, who you must then defeat. I did and the horn vanished, as it should, and summoned the Horned Huntsman as it should.
#
#### What happened instead? (Attach screenshots if needed)
But before I could kill him he wandered onto my plot and vanished! Asking the Wolf Altar it just moans that you haven't defeated him, you must blow the horn and defeat him. Only you can't get another horn!
#
#### What do you suggest instead/what changes do you propose?
Can you please give me a new Horn of the Huntsman, item ID 7328, and put it in the double chest surrounded by crafting stations in my town "Pepperridge_Farms" location (x:950, z:-3884, y:66).

Thanks.

**Comment by richardhendricks** [comment]
Done
