### ISSUE TITLE
Woven backpacks

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4733]
You get free woven backpacks in official servers (at least in eta) by using /kit command and in singleplayer you have to progress in bees to make woven backpacks. I want free woven backpacks in singleplayer :P

**Comment by 0lafe** [comment]
Nerf official servers

**Comment by boubou19** [comment]
the kits are unlocked once the player reached level 10 in the corresponding job

**Comment by Impos913** [comment]
Level 10 is nothing actually

**Comment by boubou19** [comment]
maybe increasing to the level 20-30 idk then

**Comment by Impos913** [comment]
Add a way to get free woven backpacks in singleplayer. Level 20-30 might be better tho.

**Comment by boubou19** [comment]
We shouldn't add free woven backpacks in singleplayer because /kits are server bonuses.

**Comment by Dream-Master** [comment]
No i am against it. A quest where you can get it as reward is ok at a certain point

**Comment by richardhendricks** [comment]
I agree, there are enough backpacks that space shouldn't be a problem, and it is a nice server perk.  I don't recall if there specifically is a quest to upgrade the backpack, but if not I can add it.
