### ISSUE TITLE
Spec Combs don't produced

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4736]
#### Which modpack version are you using?
2.0.6.8 and 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Single and private server
#
#### What did you try to do, and what did you expect to happen?
Run SaltQueen in Alveary
#
#### What happened instead? (Attach screenshots if needed)
Although SlagComb is being produced in 241 stacks, SaltComb isn't being produced
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by richardhendricks** [comment]
which salt queen is it? It may require Jubilant status to make the salt comb.

**Comment by sthegreat** [comment]
it needs to be in it's preferred temperature and humidity to produce specials (tolerance doesn't work). Use the alveary heater/fan/etc upgrades to change the temp and humidity.

**Comment by yukieiji** [comment]
Bees are bred in the following environments.
![2019-06-21_00 47 09](https://user-images.githubusercontent.com/40425798/59862702-398b2380-93be-11e9-82b4-77c638859cf6.png)

**Comment by sthegreat** [comment]
use the beealyzer to see what it's preferred temp and humidity is, and use alveary upgrades to get that.

**Comment by yukieiji** [comment]
It is result of beealyzer
![2019-06-21_00 55 59](https://user-images.githubusercontent.com/40425798/59863322-6ee44100-93bf-11e9-8d45-835ca1038ade.png)
![2019-06-21_00 56 05](https://user-images.githubusercontent.com/40425798/59863324-6ee44100-93bf-11e9-9f5e-022c162ab129.png)

**Comment by sthegreat** [comment]
Yeah you have to make the climate be considered Warm. Add an alveary heater.

**Comment by yukieiji** [comment]
Ok, I make climate a Warm and test again.

**Comment by richardhendricks** [comment]
There really needs to be a notification that a bee requires Jubilant status or not, it is not something obvious or necessary for every bee.

**Comment by richardhendricks** [comment]
LOL https://www.reddit.com/r/feedthebeast/comments/4fv52w/certain_bees_not_producing_their_special_drops/

Will add info to quests that special drops require Jubilant status.

**Comment by yukieiji** [comment]
After several tests with a Warm climate, Spec Combs were produced.
Thanks @richardhendricks  and @sthegreat

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/71536859-c9fc7080-28d9-11ea-88d2-82b2f8136102.png)
