### ISSUE TITLE
motd version

### ISSUE THREAD

**Issue by willis936** [GTNewHorizons/NewHorizons#4737]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Server default motd set to the current release version (2.0.7.5)
#
#### What happened instead? (Attach screenshots if needed)
Server default motd set to the previous release version (2.0.7.0)
#
#### What do you suggest instead/what changes do you propose?
Integrate updating motd with other release specific configs

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GTNewHorizons/dreamcraft.cfg#L169

I cant see an error the file was updated. When you update the pack delete the config and scripts folder frist. Override is possible too.

**Comment by willis936** [comment]
I just downloaded the server release to double check.  I forgot to mention that it is specifically the server.properties motd I'm referring to.

http://downloads.gtnewhorizons.com/?prefix=ServerPacks/
GTNewHorizonsServer-1.7.10-2.0.7.5.zip

**Comment by Dream-Master** [comment]
Ah ok the server properties is a file that have Server Owner to set on there own. I will remove a version so that people can type in that version they needed.
