### ISSUE TITLE
menu music

### ISSUE THREAD

**Issue by willis936** [GTNewHorizons/NewHorizons#4738]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Listen to main menu music.
#
#### What happened instead? (Attach screenshots if needed)
The main menu music only plays sometimes.
#
#### What do you suggest instead/what changes do you propose?
It looks like 3 of the 4 .ogg files in resources\minecraft\sounds\music\menu were made into empty files.  I think those empty files can still be chosen to be played back by minecraft.  If an empty file is chosen to be played back the main menu is silent.  If the .ogg file chosen to be played back is not located (because it's deleted or renamed) it plays the default menu music.  I think the previous solution of having 4 copies of the same music file is an acceptable solution.

**Comment by Dream-Master** [comment]
Main menu choose one file randomly thats why i copy past empty files and one (the Main one with music)
Not sure if there is an easier way to force the game just choose an specific file.
