### ISSUE TITLE
Quests on Hardcore Ender Expansion

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#4739]
https://hee.chylex.com/

**Comment by DV666** [comment]
That will be an awesome idea to create chapter for HEE (or add quests on TC chapter).

- Contain some fun items (like Ender Pouch or Temple Caller to reset the End)
- Bosses (but i don't know them very well)
- Some cool stuff like Altar or Energy infuser
- Best disc music ever (lol)

**Comment by richardhendricks** [comment]
HEE quests added to 8.0
