### ISSUE TITLE
Game enchantments

### ISSUE THREAD

**Issue by deeplyarnab** [GTNewHorizons/NewHorizons#474]
[**Void Teleport**]( https://www.spigotmc.org/resources/void-teleport.15409/)

It does what it says, if a player falls into the void then he'll be Tp'd to the set location (spawn). This can be a good replacement for the vanilla issue with using beds above y=128.

[**Blood n bones mods**](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2529963-blood-n-bones-gamings-mods)

My favourite of the mods is the Dimensional Control, which allows us to customise a dimension. I personally want this feature because i think every ppl like me DON'T WANT A BLACK VOID DIMN SKY. I kinda want a twilight night sky with mushroom biome and always night. People can then choose their dimension properties that they want like day/night, etc.

Other mods r just good for some tweaks, like block physics can allow us so that clay and compressed cobblestone (+6 compression) fall due to gravity. Triumph can be used just to modify the vanilla and twilight achievement order with some gregtech achievements too. Advanced mob control can be used to solve the vanilla wolf spawn issue (i didn't find normal wolfs in twilight too D: ).

[**Dynamic slots**](https://www.spigotmc.org/resources/dynamicslot.18247/)
Currently not needed as the server wont hit 20+ players, just listing it as it might be useful in the future (maybe?).

And about agricraft, i can manage it but after feb or after half month of march has passed, same with these mods i suggested

**Comment by Namikon** [comment]
Ahm, please utilize the forum for these suggestions. I already copied it over, but next time please do it there directly.
http://forum.gtnewhorizons.com/showthread.php?tid=120
