### ISSUE TITLE
Superconductor Wires quest

### ISSUE THREAD

**Issue by Viktor-KN** [GTNewHorizons/NewHorizons#4758]
#### Which modpack version are you using?
7.0.5.0
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
Looking at quest for HV Superconductor Wires. Quest expect from you 1EV pumps, but recipe in Assembler accepts HV pumps.
https://cdn.discordapp.com/attachments/401118216228831252/592276563488276480/unknown.png
#
#### What happened instead? (Attach screenshots if needed)
https://cdn.discordapp.com/attachments/401118216228831252/592276681436430337/unknown.png
#
#### What do you suggest instead/what changes do you propose?
Fix recipe or quest, depending what pumps were mean.

PS: MV Superconductor wires quest same issue: quest require HV pumps, but recipe accept MV pumps... Maybe other tiers have same problem

**Comment by richardhendricks** [comment]
Already fixed in 8.0?
