### ISSUE TITLE
Open computer can't access ae network

### ISSUE THREAD

**Issue by Anikilulala** [GTNewHorizons/NewHorizons#4759]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
My private server
#
#### What did you try to do, and what did you expect to happen?
Access ae network using opencomputers
#
#### What happened instead? (Attach screenshots if needed)
getItemsInNetwork() always returns {n=0}
Although the power usage returns correctly.
![image](https://user-images.githubusercontent.com/11403359/59974251-89dfcc80-95dc-11e9-8756-fb8cb98e38ee.png)
Oc adapter is connected to the me controller directly
![image](https://user-images.githubusercontent.com/11403359/59974279-ef33bd80-95dc-11e9-897d-70f512992e0b.png)

#
#### What do you suggest instead/what changes do you propose?

I have no idea if i missed some necessary components or it just a bug or version incompatible.

**Comment by repo-alt** [comment]
@Dream-Master Can you verify that OC mod in the pack was actually built from our repository? (or, even better, from the original OC repository, because it now includes all the fixes, as I mentioned in https://github.com/GTNewHorizons/NewHorizons/issues/4679), I'm sorry I forgot to test the issue when the test pack was released...

**Comment by Dream-Master** [comment]
@repo-alt guess i used old one. Is there an update with the changes your made or can we use gtnh fork ?

**Comment by repo-alt** [comment]
As I said, our fork is now missing some fixes from the original repository, so while the original is being supported again, it is better to use it: https://github.com/MightyPirates/OpenComputers "master-MC1.7.10" branch

**Comment by repo-alt** [comment]
There was no official release, so the jar has to be built from git

**Comment by Dream-Master** [comment]
merged
