### ISSUE TITLE
Combustion Generator Multiblock is killed by Oxygen

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/NewHorizons#4760]
#### Which modpack version are you using?
gtnh 2.0.7.5

#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried using the Combustion Generator Multiblock with Cetane-Boosted Diesel, Lubricant and Oxygen. I expected the gen to produce max 6144 eu/t (or 2048 eu/t at 3 amps)
#
#### What happened instead? (Attach screenshots if needed)
Using oxygen killed the gen immediately. Breaking and replacing the entire Structure was the only way to fix it. 
I tried to run it with only Lubricant and cetane boosted diesel, that worked. 
Then i tried to put in Oxygen, killed it again.
I also tried using several Dynamo hatches: EV, EV buffered, and IV, none of these helped.
using a machine controller cover and a lever cause the gen to flicker very fast, using up fuel but not producing energy.
My guess is that the recipe "lubricant+fuel+oxygen = energy" is bugged.
This problem did not occur in 2.0.7.0
#
#### What do you suggest instead/what changes do you propose?
I suggest that the Generator should produce 6144 eu/t or 2048 eu/t at 3 amps, when its used with oxygen. Just like written in the tooltip of the Controller block

**Comment by boubou19** [comment]
why close this @Aggadahr ?

**Comment by observeroftime02** [comment]
I'm not sure what's up with that, but I'm using a boosted combustion engine and it functions correctly with oxygen.
