### ISSUE TITLE
GT Sense crop harvester claiming everything in 5x5x5

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4761]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server.
#

Gregtech tool, which is named "Sense" is able to harvest logs, dirt, gravel, stone by 5x5x5 cube. Very cheaty item because it is accessible even in early stages.
![image](https://user-images.githubusercontent.com/25156941/59976854-b262c900-95d2-11e9-8a10-976fd3effe26.png)
![image](https://user-images.githubusercontent.com/25156941/59976857-bd1d5e00-95d2-11e9-87b9-b6433533c7c4.png)

**Comment by Dream-Master** [comment]
A sense have to harvested bio material but not stone dirt or rocks

**Comment by DietmarKracht** [comment]
Well that doesn't make sense

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/38e2e1512bb91c3535729250f828d8078c88a91d
