### ISSUE TITLE
Sense is broken

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#4763]
#### Which modpack version are you using?
2.0.7.5

#
#### What did you try to do, and what did you expect to happen?
Sense can only harvest stuff from cropsticks or harvests

#
#### What happened instead? (Attach screenshots if needed)
It is doing crazy things like breaking bedrock. 
Clip Proof: https://clips.twitch.tv/DependableAuspiciousHorseStrawBeary

#
#### What do you suggest instead/what changes do you propose?
Fix?

**Comment by DeForce** [comment]
Is duplicate of #4761 (just better worded)

**Comment by richardhendricks** [comment]
Thanks for the info. Will look into it.
