### ISSUE TITLE
RWG Breaks down at ~ negative 100000

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4764]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Both

#
#### What did you try to do, and what did you expect to happen?
At block positions involving -100000 blocks, RWG produces buggy terrain. 

#
#### What happened instead? (Attach screenshots if needed)
Level Seed: 3964270390937389807

100000 120 -100000

![2019-06-23_15 17 08](https://user-images.githubusercontent.com/43228249/59982617-07e6a800-95ca-11e9-8a6b-9129f4d8362c.png)

-129000 120 -129000

![2019-06-23_15 18 32](https://user-images.githubusercontent.com/43228249/59982623-2fd60b80-95ca-11e9-8ea2-96b7e105125a.png)

1 120 -100000

![2019-06-23_15 19 37](https://user-images.githubusercontent.com/43228249/59982634-55fbab80-95ca-11e9-95ce-7bc8c86cb225.png)

etc.

Positive Numbers, no problem:

100000  120 100000

![2019-06-23_15 21 52](https://user-images.githubusercontent.com/43228249/59982658-a246eb80-95ca-11e9-9606-bc44153061f0.png)

#
#### What do you suggest instead/what changes do you propose?
Improve the handling for negative coordinates so it no longer produces buggy terrain at large negative coordinates.

**Comment by Dream-Master** [comment]
rwg is open source but with no open license. use rtg and climate control instead.

**Comment by observeroftime02** [comment]
Is there a reason RTG is not used by default? Can I just switch them out and have everything generate normally?
