### ISSUE TITLE
Witching Gadgets Cloak research order

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#4765]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I found cloaks in the thaumonomicon, but one of the ingredients, `cloth of spacious folds`, was not researched and the item and all sub-research which use the cloak as an ingredient could therefore not be crafted

#
#### What happened instead? (Attach screenshots if needed)
![2019-06-24_08 45 41](https://user-images.githubusercontent.com/8459776/59997611-c99ac880-965d-11e9-811a-13b66741c9f8.png)
![2019-06-24_08 56 47](https://user-images.githubusercontent.com/8459776/59997781-24ccbb00-965e-11e9-9b0b-bfc99f848358.png)

#
#### What do you suggest instead/what changes do you propose?
Make the cloak research dependent on whatever provides the cloth of spacious folds. Alternatively the recipe can be altered to use e.g. an extra bewitched fleece instead of the cloth, or the cloth recipe can be included in the research itself.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/WitchingGadgets/releases/tag/1.2.9l

**Comment by combusterf** [comment]
I updated 2.0.7.4 with 1.2.9l and got the expected result, thanks!

**Comment by Dream-Master** [comment]
ok good. Thanks for testing @combusterf
