### ISSUE TITLE
Fusion crafting fix

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4766]
#### Which modpack version are you using?
Eta live
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
not fixed
https://github.com/GTNewHorizons/NewHorizons/issues/4276

![2019-06-24_15 02 31](https://user-images.githubusercontent.com/25028786/60017336-311e3b80-9691-11e9-8e7c-789b3d8c92c6.png)

**Comment by Dream-Master** [comment]
did you @Cinobi using a old book?

**Comment by Cinobi** [comment]
Ah, i'm stupid and forget to rescan... but hopefully i have another issue to send xD

**Comment by Cinobi** [comment]
Oh yep, i'm stupid and forget to rescan, thx =)
