### ISSUE TITLE
Change the quest 1988

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4767]
#### Which modpack version are you using?
2.0.7.5 
Drawer upgrades quest. 
Quest wants you to make iron, gold and obsidian drawer upgrades and obsidian one require aluminium plate. Quest is in steam tab. 
Remove the obsidian upgrade from quest.

**Comment by Dream-Master** [comment]
maybe split the quest

**Comment by richardhendricks** [comment]
I'll delete the obsidian upgrade requirement and just put a note in the quest text that those upgrades are pretty cheap once you get to MV.
