### ISSUE TITLE
Add Gregtech Cheese to Cheese Curd recipe in Molecular Transformer

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/NewHorizons#4778]
Cheese Curd can be used to make Cheese Ore using witchery, and Cheese Ore is one of the blocks that allows you to grow Space Plants.

Because Molecular Transformer requires Titanium, it wouldn't be tier-skipping. This would mostly allow attaining space flowers without a rocket for challenge runs.

**Comment by Dream-Master** [comment]
@SampsaxD how you get this cheese curd? i disable the ore

**Comment by 0lafe** [comment]
I mean, it's kind of tier skipping with the intention of not using rockets. Considering the usages of the space flower, simply gating it to the moon seems too early, it should probably be T3+. Maybe even T6 ish for some of the things it can do.

**Comment by SampsaxD** [comment]
The only thing space flowers allow you to tier skip is Desh and Oriharukon, Deep Iron requires ZPM energy hatches.

**Comment by 0lafe** [comment]
You can make that in IV with multi amps, which is before Ke is found by at least 1 tier of rocket, let alone if you haven't made the rockets up to IV.

**Comment by 0lafe** [comment]
Not to mention getting both desh and oriharukon pre moon is tier skipping more rockets

**Comment by repo-alt** [comment]
As if getting enough titanium for MT is easier than building a rocket...

**Comment by Dream-Master** [comment]
suggestions how to make it more hard ?

**Comment by repo-alt** [comment]
that was sarcasm, sorry

**Comment by Dream-Master** [comment]
:)

**Comment by ScriptedPiky** [comment]
I'd say that if the player wishes to go through this route, they fully intend on knowing the difficulties ahead of them. Acquiring these high tiered flowers requires an immense amount of effort, power, resources, planning, and much more. Compared to simply building a rocket, I doubt this truly counts "tier skipping" as it is impractical to do on a normal run.

This kind of thing does not harm NH at all. It doesn't ruin the gameplay, it doesn't cause bugs, it doesn't break the balance of NH for the majority of NH. There are no issues concerning this change that Sampsa requested at all. Barely anyone can achieve this level of meme-run shenanigans in their playthroughs.

**Comment by 0lafe** [comment]
Could tier space flowers better to not give you all space products after the moon, or somehow tier the recipes that use the flowers
