### ISSUE TITLE
Assembling line tooltip is annoying

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#4784]
#### Which modpack version are you using?
2.0.7.5

#
#### What did you try to do, and what did you expect to happen?
I'm trying to figure out how to build assembling line, and block tooltip is giving me headaches.

![image](https://user-images.githubusercontent.com/7394420/60291494-a3a64a00-9923-11e9-9ea8-7c784c22d751.png)

First - There is no block that is named "Assembly Line", there is "Assembling line casing"
Second - There is no block that is named "Steel Machine Casing", there is "Solid Steel Machine Casing"

And "UpMiddle" is also giving me headaches.
#
#### What do you suggest instead/what changes do you propose?
I suggest changing the tooltip to something like that:
(Remove First "Assembling Line" line)
```
Size: 3x(5-16)x4, variable length
From down-upwards:
1 - [ Solid Steel Machine Casing, Input Bus (Last is Output Bus), Solid Steel Machine Casing ] (Steel casings can be replaced by Maintenance or Input Hatch)
2 - [ Reinforced Glass, Assembling Line Casing, Reinforced Glass ] 
3 - [ Grate Machine Casing, Assembler Machine Casing, Grate Machine Casing ]
4 - [ Empty, Solid Steel Machine Casing, Empty ] (Steel Casing can be replaced by Energy Hatch)
```

**Comment by richardhendricks** [comment]
public String[] getDescription() {
        return new String[]{"Assembling Line",
                "Size: 3x(5-16)x4, variable length",
                "From Bottom to Top, Left to Right",
                "Layer 1 - Solid Steel Machine Casing, Input Bus (last is Output Bus), Solid Steel Machine Casing",
                "        - Casings can be replaced by Maint or Input Hatch",
                "Layer 2 - Reinforced Glass, Assembling Line Casing, Reinforced Glass",
                "Layer 3 - Grate Machine Casing, Assembler Machine Casing, Grate Machine Casing",
                "Layer 4 - Empty, Solid Steel Machine Casing, Empty - Casing can be replaced by Energy Hatch",
                "Up to 16 repeating slices, First replaces 1 Grate with Assembly Line,",
                "Last has Output Bus instead of Input Bus",
                "Optional - Replace 1x Grate with Data Access Hatch next to the Controller"};
    }
