### ISSUE TITLE
Extra Cells fluid interface ignores channel logic

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/NewHorizons#4785]
#### Which modpack version are you using?
2.0.7.5

#
#### What did you try to do, and what did you expect to happen?
I put 9 machines in row with 9 interfaces, I expected that last fluid interface would be "disabled".

#
#### What happened instead? (Attach screenshots if needed)
I have a pattern inside the interface: 
![image](https://user-images.githubusercontent.com/7394420/60299764-2b954f80-9936-11e9-92b8-9dc6e62bf1bb.png)

Fluid interface shows that it's disabled:
![image](https://user-images.githubusercontent.com/7394420/60299836-5089c280-9936-11e9-8f6e-3d496bd15e6a.png)

but the problem is that I can still craft thing from this interfrace:
![image](https://user-images.githubusercontent.com/7394420/60299874-65feec80-9936-11e9-8bef-4071ed87dac5.png)

![image](https://user-images.githubusercontent.com/7394420/60299952-934b9a80-9936-11e9-93d2-a97ab3e383bd.png)

#
#### What do you suggest instead/what changes do you propose?
Fix?

**Comment by DeForce** [comment]
I have created PR for this fix. Who can review it? :)

**Comment by Dream-Master** [comment]
yes will merge after my dev tea review it. @DeForce thanks btw
