### ISSUE TITLE
Simple Washer recipes

### ISSUE THREAD

**Issue by Viktor-KN** [GTNewHorizons/NewHorizons#4787]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
I tried to wash Purified Pile of Rock Salt in Simple Washer. Expecting it wash it, like cauldron do it.
#
#### What happened instead? (Attach screenshots if needed)
Simple Washer does not have recipes to wash Purifed Pile of *
#
#### What do you suggest instead/what changes do you propose?
Add recipe to wash Purified Pile of *

**Comment by Dream-Master** [comment]
Simple washer is a Gt++ device so far ik. Can you report it on gt++ GitHub please @Viktor-KN  Thanks

**Comment by Viktor-KN** [comment]
shure, will do it

**Comment by Viktor-KN** [comment]
#https://github.com/alkcorp/GTplusplus/issues/501
