### ISSUE TITLE
Change remaining LV Crafting Task Quests to Retrieval

### ISSUE THREAD

**Issue by bigbass1997** [GTNewHorizons/NewHorizons#4788]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon, though presumably all servers and SP that do not change the quests
#
#### What changes do you propose?
Out of the numerous quests throughout LV tier, the _only_ quests that appear to contain Crafting Tasks, are the "You're gonna hate this" quests. All of the other quests, including all of the machine quests, and the circuit quests, use retrieval tasks. Even quests that have items that can only be made in a crafting table, are still retrieval.

I see no reason why that particular handful of quests need to be crafting tasks. Especially when crafting task detection is not always reliable (Worktable for example), and has no functional purpose. The quests are still required for progress through the rest of the book, and some of them even have alternative Assembler recipes that can be done at LV (another chance that the crafting detection will be missed).

**Comment by richardhendricks** [comment]
Changed just the Gonna Hate This quests in LV to retrieval.
