### ISSUE TITLE
Remove "Magnetize your rods" quest in LV tier

### ISSUE THREAD

**Issue by bigbass1997** [GTNewHorizons/NewHorizons#4789]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon, but should be on all servers or SP
#
#### What changes do you propose?
This quest seems pretty pointless, besides possibly wasting materials. To unlock the quest, you must complete the "Saving redstone" quest which requires you to make an LV Polarizer. "Saving redstone" could easily include all of the quest text that "Magnetize..." has.

The position of the quest also means that it is certainly possible that the player will end up crafting polarized iron rods, far before they ever even know this quest exists.

If you want the quest to stay, then at least make it an optional quest. Optional means that anyone who comes across this quest after making a bunch of machines or finished the rest of the quests in this tier, can choose to make all of the rods if they want. There is certainly no reason that this should be part of the main questline (not optional).

**Comment by richardhendricks** [comment]
Quest made optional and scaled down.
