### ISSUE TITLE
GT Cobalt can used for Tinkers Tools

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#479]
You can use Cobalt from GT for Tinkers tools and jump over many Tiers.

**Comment by deeplyarnab** [comment]
From which mining level to which? And is this issue or info?

**Comment by Drobac** [comment]
Aware of it, but dont think it can be countered, and the main step you skip with it is alumite. What is the mining level for cobaltite?

**Comment by Dream-Master** [comment]
Will add Cobalt to the Blast Furnace and then it is available pre Steel.

**Comment by Technus** [comment]
Will add Cobalt to the Blast Furnace and then it is not available pre Steel.

Tec-just fixing comments

**Comment by Teteros** [comment]
The question's if it's supposed to be. If mining level of the GT version of cobalt could be changed, to what it would be? Same as TiC I assume.

**Comment by Dream-Master** [comment]
Not sure if GT have own Cobalt Tools?

**Comment by Dream-Master** [comment]
fixed
