### ISSUE TITLE
Forestry worktables cause lots of lag on the server when crafting large amounts of gregtech items

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4792]
Per discord request and title.

**Comment by Cinobi** [comment]
Applied energetics have some issue actually, well, all crafting tables with inventory has.

**Comment by Anarack** [comment]
#4782 possibly related

**Comment by richardhendricks** [comment]
Fixed with https://github.com/GTNewHorizons/NewHorizons/issues/5163
