### ISSUE TITLE
Analyst / Registry Quests

### ISSUE THREAD

**Issue by xtake** [GTNewHorizons/NewHorizons#4793]
#### Which modpack version are you using?
2.0.7.5
#

There are 2 Analyst Quests. One in "Slice and Splice" right next to first quest and the other one is in "How to Bee" after beealyzer.
- Just remove one of them.

And Registry Quest is in "Slice and Splice" After 4 machines and a gene database that needs ev circuits. 
- I never liked genetics mod much so I wouldn't put the Registry quest after all of those. Maybe just put it after the first initial quest in "Slice and Splice" maybe in place of the 2. Analyst Quest.

**Comment by xtake** [comment]
On a sidenote. In the Hang glider quest there are 2 quest pages that need 2 glider wings. Minor thing just saying.

**Comment by richardhendricks** [comment]
Removed analyst quest in Slice and Splice.  Moved Registry quest. Removed extra step for glider wings.
