### ISSUE TITLE
Quest/Random Tweaks

### ISSUE THREAD

**Issue by xtake** [GTNewHorizons/NewHorizons#4796]
#### Which modpack version are you using?
2.0.7.5
#
Travellers Boots Quest don't register once you add the 2 lilypads
Travellers Gloves have 5 modifiers Questbook says 4
Travellers Gloves Quest not completed when adding the 55 redstone blocks and 5 redstone (500 redstone on glove).
Travellers Wings also dsnt register completed once you added feather fall. And the recipe to turn travellers wings into travellers wings with feather fall is not in NEI just in the Materials and you volume 1. 
Travellers Vest with perfect dodge dsnt register either.
Travellers googles with nightvision don't register either.

Other Tweaks:
Wood Boots have Soft mallet on top in recipe every other boots have hammer on bottom. Minor thing but yeah.
Stone age: Making better tools (Bronze tinkers stuff). Make it so it accepts all kinds of parts not just bronze because most people use iron instead of bronze.
Flint throwing knives. Take out pattern part of quest most people don't take the pattern out of stencil table into inv but straight into pattern chest. Same with Tinkers bow. You never pick up those wood patterns. 
Maybe change the Alumite Ingot quest in some way because normally you leave the 16 molten ingots in the smeltery and instantly make the large plates for the tool forge so no Inogts.
You can get "Charged Thaumium Caps" From GT: New Horizon in a Loot bag but they are not craftable or used in any way. The normal Thaumcraft charged thaumium caps work. Maybe replace in Loot Bags.

**Comment by richardhendricks** [comment]
Traveller's quests fixed - completed item removed.
wood boots - file separate ticket.
Bronze is better than iron.
flint knife - patterns removed
bow - patterns removed
Ardite quest - changed to 1 ingot and added "Leave the rest of your Ardite as liquid in your smeltery, you'll want it to make the Tool Forge. You need 16 ingots in the smeltery to make 2 Large Plates."
File separate ticket on Charged Thaumium Caps.
