### ISSUE TITLE
Copper bee don't work after throwing on ground

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4797]
#### Which modpack version are you using?
7.5
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
throw bees on ground, like ordered
#
#### What happened instead? (Attach screenshots if needed)
new bee produce no combs
![Copper_Drone_4929](https://user-images.githubusercontent.com/7759876/60382342-0867be80-9a62-11e9-952f-531011eee99d.JPG)

#
#### What do you suggest instead/what changes do you propose?
Combs, if they are centrifuged to get copper dust or (not prefered) Combs to multiply crushed copper ore in CR 

Antworten gern auch in D

**Comment by richardhendricks** [comment]
Copper comb in 8.0 looks like it has proper recipes?
