### ISSUE TITLE
additional info for extra biome dependences for bee products 

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4800]
#### Which modpack version are you using?
7.5
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Smoulding bee (temperature/humidity 5/5) in apiary,... 
#
#### What happened instead? (Attach screenshots if needed)
do not produce blaze rods, only combs
#
#### What do you suggest instead/what changes do you propose?
someone wrote,  a specific biome (extra to T/H biome specific situation) would be needed.

If so, please add this info to bee info (WAILA and/or bee analyser)

**Comment by 0lafe** [comment]
Could make a quest or something, it's just that spec outputs need the default biome reqs the bee asks for, even if it has up/down stuff.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/71503139-91a55580-2839-11ea-9086-cef4ea5a7721.png)

**Comment by richardhendricks** [comment]
I really hate the damn Jubilant effect. Really needs to be declared somewhere.

**Comment by sthegreat** [comment]
I'd note in the quest that you can also get the specialty products by using the appropriate alveary upgrades to make the humidity and temperature the same as their preferred/default ones. In that case, no specific biome is required.

**Comment by richardhendricks** [comment]
Yeah I already did that in a few places.
