### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by HoleFish** [GTNewHorizons/NewHorizons#4801]
#### Which modpack version are you using?
GTNH2.0.7.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
1.Ban the recipes of electrolyzer : organic matter (such as ECH)and oxides (such as ZnO, CO2, ESPECIALLY SiO2) as well as  most of the salts (such as FeCr2O4 and silicate, but leave chloride)
2. Change nitrogen used for superconductor to liquid nitrogen
3. More scientific ore processing( especially scheelite), add more oxides and salts to be the by-product; ban the element ore ( reactive metals )
4.Add Cat. for chem recipes (such as ammonia and nitric oxide)
5.Add more input and output solt for EBF

**Comment by boubou19** [comment]
can you explain why do you think those changes need to be applied?

**Comment by 0lafe** [comment]
5 seems kinda useless as I think we do technically have huge inputs for it. 

4 like catalysts? I'm certainly not opposed, but it would probably be a little weird in practice with non consumable inputs. My only hesitation would be to make sure you can pull from fluid inputs in a way to make this viable. 

3 seems like a great idea, especially removing elemental ores. Gets rid of almost all the material complexity, and seems to exist for many many top tier ores. I'd suggest more post dust stage processing, but in ways that's just the only option with non pure outputs. That said, I'm all for making things like tungstate/scheelite dust being processed to tungsten in a more interesting way. 

2 seems ok, but is it craftable? 

Not sure of the purpose/reason of 1 tbh.

**Comment by observeroftime02** [comment]
Regarding #5 We have the super bus, which at max capacity holds 160 item stacks, which is a lot.

**Comment by HoleFish** [comment]
5 I mean that there can be 2 or more kinds of fluid input, 3 or more kinds of item input,2 or more kinds of fluid output( a place to 100% give fluid production, instead of trash ) and one recipe

**Comment by Methes** [comment]
If we could also, for realism sake, modify all recipes with Saw to require moving your mouse in a straight line repeatedly else your materials are wasted and the crafting fails, that would be great.
Also crafting with a Hammer should only be possible after smashing spacebar 3 times really hard. You can then remove the sound effect as it's redundant.
Soft mallet is of course the same as hammer except you use your head instead of your fist.
Rest of the tools I don't know. Maybe twist your nipples for Screwdriver recipes?

**Comment by HoleFish** [comment]
> If we could also, for realism sake, modify all recipes with Saw to require moving your mouse in a straight line repeatedly else your materials are wasted and the crafting fails, that would be great.
> Also crafting with a Hammer should only be possible after smashing spacebar 3 times really hard. You can then remove the sound effect as it's redundant.
> Soft mallet is of course the same as hammer except you use your head instead of your fist.
> Rest of the tools I don't know. Maybe twist your nipples for Screwdriver recipes?

That's what TFC have done I say:(

**Comment by 0lafe** [comment]
More ebf fluids would be fun, I think it's doable too. Semi limited just because of space and stuff, but it should work. More ore proc tho, that's totally the move

**Comment by observeroftime02** [comment]
I'm not sure why the EBF would need more than one fluid input. Producing steel for example, needs just Oxygen IRL. Perhaps one could add nitrogen as a protected atmosphere environment of sorts which provides faster processing, but most recipes already do that when you have a choice of using fluid / no fluid.

As far as liquid production goes, we have the blast smelter, which creates all kinds of alloys from complex dust inputs.

**Comment by 0lafe** [comment]
I think it would be less about adding them to things it doesn't fit with, and more about finding stuff that uses multiple fluids. Could also be for the more fantasy shit we add.

**Comment by jiamingc0824** [comment]
>1.Ban the recipes of electrolyzer : organic matter (such as ECH)and oxides (such as ZnO, CO2, ESPECIALLY SiO2) as well as most of the salts (such as FeCr2O4 and silicate, but leave chloride)

why?

>3. More scientific ore processing( especially scheelite), add more oxides and salts to be the by-product; ban the element ore ( reactive metals )

why?

>4.Add Cat. for chem recipes (such as ammonia and nitric oxide)

This sounds interesting. Need to see how to implement it properly.

>5.Add more input and output solt for EBF

Doesn't seems to be useful.

**Comment by 0lafe** [comment]
>3

Current ore proc for a lot of EV+ ores is fairly boring and ends with pure products right away. Rutile is kind of the most complex it gets, and shits like not even EV really. Tungstate falls off a lot, and most others are at most just centrifuge products.

**Comment by HoleFish** [comment]
> > 1.Ban the recipes of electrolyzer : organic matter (such as ECH)and oxides (such as ZnO, CO2, ESPECIALLY SiO2) as well as most of the salts (such as FeCr2O4 and silicate, but leave chloride)
> why?
 That's not enough scientific and difficult, everyone knows that SiO2 make it too easy to get oxygen.
> > 3. More scientific ore processing( especially scheelite), add more oxides and salts to be the by-product; ban the element ore ( reactive metals )
> why?
The reason is the same. It's too easy to get Aluminium.

**Comment by jiamingc0824** [comment]
> 
> 
> > > 1.Ban the recipes of electrolyzer : organic matter (such as ECH)and oxides (such as ZnO, CO2, ESPECIALLY SiO2) as well as most of the salts (such as FeCr2O4 and silicate, but leave chloride)
> > > why?
> 
> That's not enough scientific and difficult, everyone knows that SiO2 make it too easy to get oxygen.
> 
> > > 1. More scientific ore processing( especially scheelite), add more oxides and salts to be the by-product; ban the element ore ( reactive metals )
> > >    why?
> 
> The reason is the same. It's too easy to get Aluminium.

Why are you bothering with realism? It's just a game. The method of obtaining oxygen is not limited to only SiO2 and there are plenty of method to getting oxygen which are easily automatable. Aluminium is also very easily obtainable and removing the pure ore doesn't affect anything at all. 

It is a stupid idea to nerf things just for the sake of nerfing them and due to "realistic".

**Comment by richardhendricks** [comment]
We have plenty of complex processing already, and the new platinum processing is complex enough. Declined.
