### ISSUE TITLE
All Travellers gear upgrade quests don't accept upgraded items

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4805]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
So I crafted upgraded wings, but the quest doesn't want to accept it.
Tab: Armors and Jetpacks

![image](https://user-images.githubusercontent.com/25156941/60388678-ba80a400-9abd-11e9-95ce-ee1d9de17383.png)
![image](https://user-images.githubusercontent.com/25156941/60388683-ccfadd80-9abd-11e9-829c-8306aa9e74cf.png)
![image](https://user-images.githubusercontent.com/25156941/60388685-d3895500-9abd-11e9-9e07-a37c200fd230.png)

Upd:
Also it will be nice if you add the information about how to craft it, because recipe cannot be viewed via NEI.

Upd: This bug is also with gloves.

Upd: This bug is with all quest about upgrading traveller's gear.

**Comment by DietmarKracht** [comment]
Also applies to 2.0.7.0

**Comment by richardhendricks** [comment]
Removed the crafted items from the requirements.

Added info to put the traveller's gear in the center of the Crafting Station to make items.
