### ISSUE TITLE
Wearing the Charge Pack in your baubles slot and picking up redstone corrupts the player

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4806]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Both MP and SP

#
#### What did you try to do, and what did you expect to happen?
1. Wear the gt++ charge pack (UV in my case) in your baubles belt slot
2. Pick up a stack of redstone, either from AE2, the ground, a chest or cheat it in from NEI
3. Get kicked from the server and loose the ability to connect until you delete player data.

This happens every time, removing the charge pack from baubles slot fixes it and stops it from happening. [Here's a log](https://pastebin.com/1Rptx4iv) of the incident.

**Comment by draknyte1** [comment]
Could you please submit your error here? https://github.com/alkcorp/GTplusplus/issues/new

Thanks.

**Comment by observeroftime02** [comment]
[Done](https://github.com/alkcorp/GTplusplus/issues/505)
