### ISSUE TITLE
Mega EBF voids items: Concrete example

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4807]
2.0.7.5

After a conversation with bart, where I was unable to describe the specific issue with the mega ebf, I've decided to record a clip showing this in action [1](https://gfycat.com/totalinbornafricanwildcat) and [2](https://gfycat.com/meekuniformgossamerwingedbutterfly), because I hate to throw around accusations without having anything to show for. 

Recipes in this example: 
Clip 1: Superconductor UHV dust, Circuit setting 11, with Radon: 62 ingots worth of Gas consumed, item voided, EBF disabled .
Clip 1: Superconductor LuV dust, Circuit setting 1 without gas: item voided EBF disabled.
Clip 2: Awakened Draconium, Cirtcuit setting 11 with Argon:  64 ingots worth of Gas consumed, item voided, EBF disabled.

Mega EBF configuration: UV Borosilicate Glass, Awakened Draconium Coils, 16 (!) UHV energy hatches, receiving a total of 48 A UHV

I hope this demonstrates the issue, and assists in troubleshooting this monster. 

And before someone blames the configuration, [here's it smelting Tungstensteel without issues](https://gfycat.com/favoritesmoggycanadagoose).

**Comment by DietmarKracht** [comment]
You didnt do enough testing. You should test with 1 Dust and with a stack respective so the tungstensteel doesn't really say anything about this issue as you only smelted a single dust but tried smelting a stack of highest tier materials

**Comment by observeroftime02** [comment]
Single dust, same result. Please don't tell me that I didn't do enough testing, when in fact, I did. And what should tier have to do with it when the regular EBF smelts these down just fine, regardless whether i put a stack or a single dust into the input. 

But, just for you: [Here's a clip](https://gfycat.com/illiteratequalifiedgossamerwingedbutterfly) with the same behavior, for single dusts. Can we perhaps acknowledge that there is a problem with this somewhere?

**Comment by Ergonoodle** [comment]
After upgrading to 2.0.7.5, I have the same problem. I thought the problem was advanced muffler ZPM. But I replaced them with Muffler LuV... But still void dust.

**Comment by boubou19** [comment]
@observeroftime02 what are the cables on your clips?

**Comment by observeroftime02** [comment]
I'm pretty sure this was fixed in more recent releases but I'll check when I get back home.
