### ISSUE TITLE
1,1-dimethylhydrazine craft

### ISSUE THREAD

**Issue by Rostisha** [GTNewHorizons/NewHorizons#4808]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
As quest #856 (HV chemistry) says, i can make 1,1-dimethylhydrazine usint dimethylamine and chloramine. But the recipe of 1,1 is hydrazine+formaldehyde+hydrogen
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/46450977/60395658-70400700-9b3f-11e9-9269-1441bae0efa7.png)
![image](https://user-images.githubusercontent.com/46450977/60395663-81891380-9b3f-11e9-86fa-ce28440f9a7e.png)
#
#### What do you suggest instead/what changes do you propose?
Maybe fix quest
#

**Comment by draknyte1** [comment]
GT Rocket fuel recipes were all removed in favour of GT++ rocket chemistry.
Just a simple oversight, cause I don't touch quests, so it relies on someone else to find and tweak the relevant quests out of the several thousand that exist.
