### ISSUE TITLE
GT NEI Update

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#4810]
#### What do you suggest instead/what changes do you propose?
Add a small Info to the Voltage Requirements of a Recipe adding its Tier (i.e. add "LV" for 24EU/t recipes)

**Comment by observeroftime02** [comment]
That's a great idea! 

I've got another QOL improvement. How about adding an easy way of looking up all the particular recipes used by a machine, without having to find something that the machine processes first? Like if I want to see all the recipes used by the laser engraver, I have to find something that goes into it or comes out of it first, and then go through that to look up the recipes. Perhaps when using the "use" key on the machine itself, it could show all the recipes for that particular machine.

**Comment by Anarack** [comment]
Considering some machines are used to craft other machines and or recycling recipes, another key would need to be used. This makes the key issues with this pack even worse however.

**Comment by observeroftime02** [comment]
There could be another page when using the use key, showing the recipes, so it wouldn't conflict in the case that the machine is used to craft something else as well, you know what I mean?

**Comment by DoomSquirter** [comment]
you realize tho that this already exists?  hover over the middle of the screen where it shows something being made in the gui and you'll get a tooltip called recipes, which shows exactly that info

**Comment by observeroftime02** [comment]
Right, but for that you first need to find a recipe used by that machine. For example, if I have no idea what goes into a pyrolize oven, I wouldn't be able to find it's recipes.

**Comment by DoomSquirter** [comment]
well ofc you would since that doesn't have a gui
yeah, I think in the big scheme of things, what you are writing about is literally the very tip of the iceberg of what is so hard in a pack like this, in dealing with NEI.

for example, when I want to see recipes for a machine and I see 500+ pages of recipes but I'm only really interested in what screws I can make and I really don't care about foils or plates, yet it's definately going to show me all of that.  adding something like favorites like you can with JEI would go a long way to alleviate that issue since then you can immediately go back to already found recipes, etc.  even if it's something that you'd end up persuing further down the rabbit hole but it'd remove that first 20 steps you have to do each and every time you need to go back and find it.

**Comment by observeroftime02** [comment]
It's just a suggestion to perhaps make it a bit more user friendly. Favorites are a great idea also. 

One issue I came across early on was making alloys in the alloy smelter. Take for example, Bronze. Hitting the recipe key on a Bronze ingot, and then scrolling to the alloy smelter page, you see 42 things that aren't really relevant (like smelting Bronze springs into Bronze ingots), and it even shows things that aren't ingots, like nuggets. If I click the little arrow to see all of the alloy smelter recipes, and I'm only interested in what alloys it can create from 2 different dusts or ingots, I have to scroll through 11000 recipes, 99.99% which aren't of interest to me at all. So perhaps some type of filtering would be ideal, although I'm unsure about the specifics. Then having a favorite button to save what you found would make life a little better as well, I agree. 

This is needlessly confusing to new players who are just looking for a way to create the actual Bronze ingot from copper and tin. Do we really need to show the recipes that create 4 bronze ingots from 1 quadruple bronze ingot, or one bronze ingot from one bronze plate? Who needs that information?

**Comment by DoomSquirter** [comment]
as I said, anything with a gui, you already have this in the gui, as a click away.  it's the multi's that won't show that info cause of no gui.

but yeah, beyond that semantic I totally agree with you but nei isn't a mind reader.  with a pack like this the divide between normal and what would be nice to have becomes huge.

**Comment by 0lafe** [comment]
Can we talk about the idea of people not knowing how to divide by 4 though?...

**Comment by noobyaran9** [comment]
>Can we talk about the idea of people not knowing how to divide by 4 though?...
 
No. Not everyone need to know how to divide by 4.


Back to the topic, i really liked the idea of bookmarking recipes.
