### ISSUE TITLE
2 Different super chests?

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4812]
2.0.7.5
There are two different super chest types with different capacities and recipes but with the same names.

**Comment by draknyte1** [comment]
Fairly sure one set are mine.
https://github.com/alkcorp/GTplusplus/issues/new

**Comment by Dream-Master** [comment]
@Anarack please file a Gt++ issue. Thanks

**Comment by Anarack** [comment]
https://github.com/alkcorp/GTplusplus/issues/511 done
