### ISSUE TITLE
XP crafting

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#4817]
#### Which modpack version are you using?
2.0.7.newest

#### What do you suggest instead/what changes do you propose?

Right now xp crafting sort of exists as a poormans uu duping for more than elements. Depending how you do it, it will either cost a very low amount of power, or none at all. Some of the crafting options are ok, but others are a little too good. 

~Copper could probably be 3b instead of 2. It's a little more useful/harder to get than iron/sulfur which are 2. 
~Gypsum/calcite could probably be 2 instead of 3, as they're more early game crafts when you have less xp. 
~Silver could probably be changed to a small/tiny pile or removed. Al is the same amount as silver right now, but Al is really easy to get a ton of even in MV. While silver is mainly for the tier after Al, and is harder to get. Silver doesn't have a lot of ways to produce it, making this xp method quite good comparatively.

**Comment by sthegreat** [comment]
Honestly I think xp crafting should be removed for copper, silver, gallium, and possibly others. It just doesn't really make sense to me that a mob farm which already produces tons of iron, gold, steel, diamonds, pistons, etc. should give even more stuff. Xp crafting is fine when you're a new player using the tinkers drain thing to get a few copper or sticky resin, but it really shouldn't be possible to use industrially with a giant xp berry farm or a mob farm.

**Comment by Methes** [comment]
Agreed on copper, agreed on calcite+gypsum.
Leave silver as is or nerf to small pile at most. Remember it's a nice way to get more solars pre LV.

**Comment by Scottishprog** [comment]
I say don't mess with it at all.
No balancing.


Why?  These were put in as a defense against early game brick walls.
If you want to remove alter these ... have a _lot_ more discussion on how the brick walls will be mitigated.
(And no, "build more" is _not_ responsive to the situation. Everything is expensive and slow, leaving the sole option of grinding, if the needed materials cannot be found.)

Personal example:  Gallium.  Without that recipe I would have been dead in the water. I did not get adequate sources of gallium until I was mid-late MV.

**Comment by DoomSquirter** [comment]
agree with scottishprog.  if ppl decide to build up a infrastructure to milk this or use this as mainline to make mats, fine, let them.  it doesn't hurt anyone.  this isn't a competition.

if you don't like something in a pack, don't utilize it.  grow a backbone and take an internal stand not to use a thing.  don't try to make everyone play the pack your way.  allow ppl find their own avenues to explore if they want.

me?  I never made anything with xp buckets.  not once.

**Comment by Viktor-KN** [comment]
Liquid XP don't have so much uses anyway... Let it be useful at least that way.
