### ISSUE TITLE
Typos in Thaumcraft Aspects

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#482]
_Side note: The Testserver is running with research setting -1 to make it easier to check recipes and tiering._
A lot of basic Thaumcraft researches are impossible to research due to (probably) misspellings in Thaumcraft aspects. For example; It should be ["gelum" instead of "gellum"](https://github.com/GTNewHorizons/NewHorizons/blob/master/scripts/Thaumcraft-Thaumaturgy-3.zs#L104)

I'd suggest to check all aspects in every Thaumcraft file to avoid possible problems with researching

**Comment by Dream-Master** [comment]
Yes i planing to research all stuff to be sure it will works and correct speeling.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/18ca279ad3855c990a56be50052f6f54659ea2f3

**Comment by Teteros** [comment]
Hehe, that's why next time making a branch and verifying typos and whatnot first, (before pushing to master) is advised.

**Comment by Teteros** [comment]
@Dream-Master Should I move all TC scripts to a new branch ([Everything **after** 1.0.7.6 tag](https://github.com/GTNewHorizons/NewHorizons/releases/tag/1.0.7.6)) and revoke commits on main branch till we go through them once more?

**Comment by Namikon** [comment]
Unrelated to this Issue; But could we go with tags for the Testserver? (As 1.0.7.6-test, or similar) To keep things more synchronized? This is a whole mess to figure out what needs to go where.. I'll think about a solution to autodeploy updates from GIT to the servers, and only use the direct server-transfer for troubleshooting

**Comment by Teteros** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/485

**Comment by Dream-Master** [comment]
fixed
