### ISSUE TITLE
Incorrect ingridients for "Superconuctors 2048 eu/t" quest

### ISSUE THREAD

**Issue by npo6ka** [GTNewHorizons/NewHorizons#4820]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What happened? (Attach screenshots if needed)
The quest must have an EV pump instead of IV.

![img](https://pp.userapi.com/c850332/v850332730/18c1b2/5rez8l0z5_E.jpg)

![img](https://pp.userapi.com/c850332/v850332730/18c1c1/7HiMFPyyHdc.jpg)
#

**Comment by npo6ka** [comment]
And the nitrogen in this recipe is not used. The problem with nitrogen is in the quests for superconductors 2048/8192/32768.

**Comment by Dream-Master** [comment]
All Superconductor recipes are wrong now. Need to change all Quests and the order maybe too.
