### ISSUE TITLE
Krypton from fuel rods missing from double and quad rods

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#4826]
2.0.7.5

This recipe exists for singe fuel rods:
![image](https://user-images.githubusercontent.com/43228249/60761088-8c87ec00-9ff6-11e9-8530-ec2915577db9.png)
![image](https://user-images.githubusercontent.com/43228249/60761094-9d386200-9ff6-11e9-9ca8-86f63373c4e2.png)
![image](https://user-images.githubusercontent.com/43228249/60761096-a88b8d80-9ff6-11e9-8357-83386925c1cd.png)

The same recipe is completely absent from the dual and quad version of the same fuel rods.

For example, quad uranium rod depleted:
![image](https://user-images.githubusercontent.com/43228249/60761117-e983a200-9ff6-11e9-8687-ee32ea94d0b7.png)

Quad MOX depleted:
![image](https://user-images.githubusercontent.com/43228249/60761128-08823400-9ff7-11e9-836f-2bfb86eb85ee.png)

This currently punishes people who run more than single rods in their reactors, as Krypton is a much needed resource for the creation of the Power Sub-Station. Can the recipes for the spent fuel rods be unified please?

**Comment by botn365** [comment]
from what i have heard it is intensional

**Comment by draknyte1** [comment]
Intended.
Single Rod Reactors are for breeding, not producing power.
This is the cost of producing these rarer elements.
