### ISSUE TITLE
Iron capped Greatwood Wand quest (798) does not detect its second step

### ISSUE THREAD

**Issue by NIKENIT** [GTNewHorizons/NewHorizons#4827]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What happened? (Attach screenshots if needed)
Iron capped Greatwood Wand quest (798) does not detect its second step.  The quest is critical to progression in Thraumcraft quest line. Does not matter if the wand is empty or if it is maxed out on vis.

**Comment by GamerTriStuS** [comment]
I also have this problem. I'm not a programmer, but I noticed the absence of the line **"aer: 4": 0** " in the file **DefaultQtests-us.json** Maybe the problem is connected with this?
![bandicam 2019-07-11 20-40-54-212](https://user-images.githubusercontent.com/52796465/61073725-bc802680-a41e-11e9-9187-fca00d44233f.jpg)

**Comment by mrTeroblaze** [comment]
small addition: second step just requires wand with 0 0 0 0 0 charges. New created wand does not have charges at all (he is not just empty he does not displays charges). I checked it by creating new wand (quest didnt accept) than fully charged it from nodes (charges appeared but quest not coun it) and then droped charges to 0 (by crafting stuff in arcane workbench) and voila! quest done :D

**Comment by repo-alt** [comment]
How did you manage to pick crafts to drain vis  exactly to zero? are there some small enough items for all the elements?

**Comment by mrTeroblaze** [comment]
> 
> 
> How did you manage to pick crafts to drain vis exactly to zero? are there some small enough items for all the elements?

To test this i did following:becouse basic wand have 110% vis usage, i cheated vis discount armor and crafted primal charm which costs 50 of each aspect and recieved 0 0 0 0 0 charged wand. Dont know if there are a way on MP to do so.

**Comment by richardhendricks** [comment]
Probably better to make the quest detection a 100% filled wand since that is easier to do.

**Comment by Dream-Master** [comment]
thats what the quest before @richardhendricks

**Comment by GamerTriStuS** [comment]
Above the described way, I managed to pass the quest 798. Then follows the quest 237 "Stores 50 vis" wand in which there is the same problem. A crafted stick with gold tips has no aspects. It had to be charged and discharged to 0 0 0 0 in order to pass this quest 237.
