### ISSUE TITLE
Nodal Mechanics recipe reset to default

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#483]
The Nodal-Mechanics recipe is reset to the default cheap one

**Comment by Dream-Master** [comment]
Yes i forgot to update my Version.
Will do this later.

**Comment by Dream-Master** [comment]
Fixed.
Put the new File to Solder and update the client Pack.

Nodal Mechanics 1.0.11

**Comment by Dream-Master** [comment]
Nodal Mechanics 1.0.12 we add to the Live Server in 1.0.7.7
