### ISSUE TITLE
Industrial Diamond cannot be lathed into rods despite NEI saying so

### ISSUE THREAD

**Issue by kekzdealer** [GTNewHorizons/NewHorizons#4830]
7.5, multiplayer

Issue described in title.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/61177035-b7aca580-a5cb-11e9-9ca5-ea6b65b11328.png)

not true

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/61177037-c2ffd100-a5cb-11e9-91b1-548f2b834e64.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/61177040-cf842980-a5cb-11e9-99fd-54a5c38231b9.png)

**Comment by Dream-Master** [comment]
nei shows the recipe but it cant be used
