### ISSUE TITLE
Typesetting table bug

### ISSUE THREAD

**Issue by Viktor-KN** [GTNewHorizons/NewHorizons#4833]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
Trying to make Enchanted Plate in Typesetting Table (for enchanted book duplication) without Print Press Chase in table. Expect it will not create Enchanted Plate.
#
#### What happened instead? (Attach screenshots if needed)
Enchanted Plate created without Print Press Chase
#
#### What do you suggest instead/what changes do you propose?
I suggest, that Print Press Chase is required to successfully create Enchanted Plate, cos it will consume it if u put it in Typesetting Table.

**Comment by Dream-Master** [comment]
Biblio craft is closed source
@Viktor-KN
