### ISSUE TITLE
allow the EBF to have all buses/hatches in the top layer

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4834]
as the name says. make it a thing.

**Comment by 0lafe** [comment]
Why? Even 2x of 4xing your ebf walls you have all the space you need

**Comment by Viktor-KN** [comment]
why not? If this change not breaking anything then its good to have more options of hatches/buses placement.

**Comment by bartimaeusnek** [comment]
Im against this, it makes wallsharing too easy, therefore decreases the costs for multi EBF setups.

**Comment by 0lafe** [comment]
kind of true, but im more against it because if more fluids are used in the ebf, youll need to handle your fluids in a way that isnt just keeping hatches filled/filtering hatches based on fluids. When you have more fluids than hatches it makes for much more interesting automation
