### ISSUE TITLE
sheelium should autoclave int to pure tungsten

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4836]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SP
#

#### What do you suggest instead/what changes do you propose?
pyrolsium gets turend int to mangenees and bauxia gets turen in to aluminium
wich is both the pure ore form
but sheelium gets turend into sheelite and not tungsten wich still neets to be prossesd and neet 7x more to get the same amout of resourse
so sheelium should autoclave in to tungsten not sheelite

**Comment by Dream-Master** [comment]
@botn365 can you post an recipe. I cant find it. I found Scheelite but not Sheelium.

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/61177043-f5113300-a5cb-11e9-9c04-8ba2e5c74bfc.png)
im talking about tis recipy
i meant scheelinium
