### ISSUE TITLE
Quest #33

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4838]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
On step 4/5, allow 'Stick' to be Stick (anyType)

**Comment by Dream-Master** [comment]
Quest 33 havent 5 tasks maybe another Quest @AlexBucket
