### ISSUE TITLE
Re-add Titanium Ore to T4 or T5 planets

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/NewHorizons#4839]
#### Which modpack version are you using?
2.0.7.5
#

Pure titanium veins now seem to spawn only on T7 planets and the Deep Dark now. While I understand that Ti was very easy to get in the past, and the desire for some people to force players to use ilmenite and rutile as an inferior substitute early on, this change just goes too far in the opposite direction. As it is now, you are forced to use that chlorine-intensive method to obtain small amounts all the way until tier 7, at which point the only pure titanium is "sporadically" spawned in Neutronium veins. It is only when you get to the Deep Dark that you can get Ti in abundant quantities with ease.

I would recommend moving Pure Ti ore back to Tier 4 or 5 planets as a primary or secondary ore in a vein. There is zero reason why an EV-tier material should be so difficult to obtain in bulk until so late in the game.
![2019-07-11_11 14 50](https://user-images.githubusercontent.com/12854704/61075530-0b9e6b00-a3cf-11e9-943b-bea20841e8ff.png)
![2019-07-11_11 14 58](https://user-images.githubusercontent.com/12854704/61075534-0c370180-a3cf-11e9-8058-12a691154e56.png)

**Comment by Xauronx** [comment]
I can see that it is intended to force maybe the Ore Drilling Multiblock to obtain pure Tungsten now. But it is a little weird, that every major Tier-Metal gets a pure Vein source in higher Tiers, but not Titanium. 

Would agree with finkle here, to make a pure vein source open at least at T5 Rocket

**Comment by Viktor-KN** [comment]
T5 rocket? Why not T3-T4? As bauxite/ilmenite u first get it on Moon T1...

**Comment by combusterf** [comment]
Last time I checked, pure titanium could be recovered from T3 planetary stone (Callisto) as an alternative.

**Comment by observeroftime02** [comment]
Titanium spawns as small ores just about anywhere. A max tier drilling rig with a radius of 9 would dig up about 10k of Titanium. Perhaps this is the intended route for obtaining large amounts of it? 

Still, as a primary material, I'd also like to see at least one pure Titanium vein somewhere on a Planet of it's respective tier, not everyone fells like wreaking havoc on TPS with drilling rigs.

**Comment by mitchej123** [comment]
I thought we were moving it from the moon to mars?

**Comment by 0lafe** [comment]
>I thought we were moving it from the moon to mars?

Nah that's still EV. Something T3 at least, but I'm not mad at it being T4. You really do get enough from rutile, and keeping the process into IV is kind of nice with current tungsten. Maybe when tungstate is more involved Ti could come to T3?

**Comment by botn365** [comment]
its T5 not T4 so its availble at ZPM

**Comment by 0lafe** [comment]
T4 is LuV though? Isn't this T4 too?

**Comment by botn365** [comment]
the planet titan is T5

**Comment by Dream-Master** [comment]
ok added to venus also
