### ISSUE TITLE
Custom recipe pages really hard to read

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#484]
Some GregTech recipe pictures in the Thaumonomicon are really hard to read. Suggestion to add a descriptive text to explain at least which circuit configuration needs to be used and what the input items are. Or, if possible, a tooltip on mouse-over

**Comment by Dream-Master** [comment]
Can make some Screenshots to see which recipe you mean ?

**Comment by Teteros** [comment]
He means recipes like this:
![Assembler](https://i.imgur.com/wZqbrSh.png "What is the circuit config?")

>explain at least which circuit configuration needs to be used and what the input items are. Or, if possible, a tooltip on mouse-over

**Comment by Dream-Master** [comment]
Yes will add some Text and delete those Pictures. (Salis Mundus Maceratpr recipe too)

**Comment by Dream-Master** [comment]
removed
