### ISSUE TITLE
[2.0.7.5] Game crashing on load

### ISSUE THREAD

**Issue by Mogball** [GTNewHorizons/NewHorizons#4840]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Hosted on a local machine. Crash also occurs when launching game in single player.

#
#### What did you try to do, and what did you expect to happen?
Log in to the server/load the game in SP. No one else was on the server. Server was re-launched.

#
#### What happened instead? (Attach screenshots if needed)
Game briefly loads in and appears to crash on the first tick update (client crash). I've attached a crash report. I can't remember if the server was properly shut-down... so the game world might be corrupt?

[crash-2019-07-11_17.11.44-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3384011/crash-2019-07-11_17.11.44-client.txt)

**Comment by boubou19** [comment]
Please try to reinstall your instance it can help sometimes

**Comment by Mogball** [comment]
I tried that but I am still getting the same crash

**Comment by bartimaeusnek** [comment]
if you have installed the game via twitch, please either download it [here, direct Link to 2.0.7.5,] or install it via technic launcher, the twitch instance is quite buggy atm (http://downloads.gtnewhorizons.com.s3-eu-west-1.amazonaws.com/ClientPacks/GTNewHorizonsClient-1.7.10-2.0.7.5.zip)

**Comment by Mogball** [comment]
I installed via Technic launcher. Based on some googling, I think there might be multiple tile entities in the same block

**Comment by shawnbyday** [comment]
@Mogball I'm not at home so I can't confirm if this is normal but you have two of the same mod here...I know the error is related to GT++ but maybe someone else can confirm if this is normal. Different names...same jar name.

	UCHIJAAAA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHIJAAAA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar)

**Comment by boubou19** [comment]
that just means the two mods are stored into the same jar no?

**Comment by shawnbyday** [comment]
*Shrugs* I honestly don't know. Normally duplicate mods give a different error. It looks like it is something to do with GT++ as Mog stated but I thought I'd read the rest of the log too and found that odd.

**Comment by bigbass1997** [comment]
It is normal. It is a single file with the main mod and a legacy mod inside. If the problem was duplicate mods, the error would be very different.

**Comment by bartimaeusnek** [comment]
@shawnbyday boubou is right, this most likely means what @Mogball already wrote, 2 tile entities on the same spot, which should never happen. The crashlook also looks suspiciously similar to the one in this issue: https://github.com/GTNewHorizons/NewHorizons/issues/4777 which also supports this thesis. @Mogball please contact me on discord, we might be able to edit your world with a tool.

**Comment by Mogball** [comment]
@bartimaeusnek helped me look into this and increasing stack size (-Xss1G) allowed me to load in. It doesn't seem like there are duplicate TEs but rather that there are too many pipes in our base and `onNeighborChange` was blowing out the stack

**Comment by draknyte1** [comment]
> Different names...same jar name.

You can have 32k mods per .jar as far as Forge cares.
