### ISSUE TITLE
better foil for zpm transmitter and sensor

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4844]
#### What do you suggest instead/what changes do you propose?
zpm transmitter and sensor neet 3 stacks of Pu241 foil
![afbeelding](https://user-images.githubusercontent.com/42187820/61157743-4ac7db80-a4f7-11e9-98d7-8a7f8ac17da8.png)
![afbeelding](https://user-images.githubusercontent.com/42187820/61157759-5b785180-a4f7-11e9-9e34-ada43f8c5d3b.png)
Pu241 is prety much impossible to get in tose quanties the only source of getting such quanteties is a Pu241 that is on T6 planets but that is UV while UV
is naquadaria 
![afbeelding](https://user-images.githubusercontent.com/42187820/61157862-9d08fc80-a4f7-11e9-82b0-9b45628b19d1.png)
![afbeelding](https://user-images.githubusercontent.com/42187820/61157887-a8f4be80-a4f7-11e9-8d5a-5b7c63541ee8.png)
naquadaria is easy to get in tose quanteties by LuV wich makes 
so swich the foils of zpm and UV or get a better foil for ZPM
maby trinium

**Comment by observeroftime02** [comment]
That's 48 Pu241 ingots per item, considering that at LuV tier Pu241 is really hard to obtain (primarily Nuclear Reactors or centrifuging Pu239), I'd be okay with changing it to something tier appropriate, like maybe HSS-G foil or Niobium-Titanium foil or something along those lines, or at least replace a part of the Pu241 foil for something not quite as challenging to obtain. 

To get 48 Pu241 ingots from centrifuging Pu239 you'd need to process about 2000 Pu239 dusts or do an insane number of cycles in the nuclear reactor.

Considering the difficulty of this recipe when comparing it to the other recipes for the different tiers of the same item, it's really out of proportion.
