### ISSUE TITLE
Quest 1714 (Cheaper Simple Circuit) requires wrong amounts

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4846]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
This amount of ingredients produces 64 circuits, not 32.
![image](https://user-images.githubusercontent.com/25156941/61170485-70de9180-a572-11e9-9adc-389487388c36.png)
![image](https://user-images.githubusercontent.com/25156941/61170487-74721880-a572-11e9-9ce3-f632b1fd0e42.png)
![image](https://user-images.githubusercontent.com/25156941/61170489-7fc54400-a572-11e9-8046-68a3eb2d3db6.png)

**Comment by DietmarKracht** [comment]
Also Nand chips should be a replacement for vacuum tubes as well. But in some recipes one can only use vac tubes

**Comment by Dream-Master** [comment]
@DietmarKracht whiche one ?
