### ISSUE TITLE
Add a Filtered Output Bus

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/NewHorizons#4847]
#### Which modpack version are you using?
2.0.7.5
#
Currently, to process ores, you need to make a lot of item filters which is both time and resource consuming. It would be a lot easier to add a function to multiblocks that would only allow, for instance, tiny dust to come out of one bus in a thermal centrifuge and only full dusts to come out of another bus.

**Comment by observeroftime02** [comment]
Idk about needing _a lot_ of filters, before switching to AE my ore processing from 8 thermal centrifuges was handled by basically three type filters. 

But sure, maybe hitting the output bus with a screwdriver could change the functionality to output a only certain oredict type like the type filter would do, would be nice to have for sure. But then you would have the problem that unless you set all your buses up perfectly, items wouldn't have anywhere to go. I could see this causing all sorts of issues.

**Comment by 0lafe** [comment]
Idk about causing any issues, but it seems kinda pointless. You mostly just need a filter or two for ore proc, and by the time you make multis they're quite cheap. Also consume no power, so not really costly
