### ISSUE TITLE
buff salt sifting

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4849]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What do you suggest instead/what changes do you propose?
![afbeelding](https://user-images.githubusercontent.com/42187820/61178342-74622f00-a5eb-11e9-836b-42d99c9baae8.png)
after running it trough a gt++ sifter basicl shows that you get no bonus from sifting salt when a normal sifting recipy should give a deasent % more tis barely gives a 1% boost

**Comment by bartimaeusnek** [comment]
buff salt crystals to 25% instead of 15% would be a propper buff here i guess?

**Comment by richardhendricks** [comment]
Huh?  Those numbers show a 10% boost over "Advertised". What's the problem?

**Comment by botn365** [comment]
i sugest 
exquisit 2%
flawles 10%
crystal 25%
flawd 20%
chipped 40%
dust 50%
tis will give a boost of ~130% if you sift it instead of normal prossesing
