### ISSUE TITLE
Synchronize new configs

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#485]
1.0.7.7 is becoming way too big for it's own good.
@GTNewHorizons/core 
I suggest we split unfinished or unchecked features from master (TC scripts mainly), revoke them (undo) on master and update the pack.
In an attempt to _keep master clean at all times_.
There's many fixes not in [1.0.7.6](https://github.com/GTNewHorizons/NewHorizons/releases/tag/1.0.7.6) that are in master, and it's very hard for an outsider to know how to apply them at the moment.

[They are not limited to, but include:](https://github.com/GTNewHorizons/NewHorizons/compare/1.0.7.6...master)
- RemoteIO.zs (has the IOTool dupe still in live pack)
- HungerOverhaul.cfg (butcher trade, constant hunger)
- EnderIO.zs (bank upgrade fixes & glass)
- Tinkers-Construct.zs (shears consume)
- Railcraft.zs (creosote as fuel)
- InfernalMobs.cfg (witchery bosses and steal/TP effects)
- IC2.zs (basalt dust)
- WarpTheory.zs (0aba38f674efc37f39efac738ee618cde2d6efdc only!)
- GraviSuite.zs (chrome plates)
- config/GregTech/Recipes.cfg (obsidian plates and more)
- Extra-Utilities.zs (bedrockium ingots)
- CoreMod.zs (.giveBack to .transformReplace)
- ProjectRed.cfg (regenerate, disable worldgen)
- config/enchiridion/library_books.json (no free books in enchirion library)
- Translocator.cfg (crafting grid disable)
- Chisel.zs (glass & marble)
- Morpheus.cfg (sleep percentage)

Alternatively, we can cherry pick those fixes, and release a 1.0.7.6-hotfix branch of some kind.
for the other server, and more...

**Comment by Teteros** [comment]
Till we sort it out, @ProsperCraft these commits are what you need.
Sorry about that.

**Comment by Dream-Master** [comment]
I think if i checked Thaumcraft scripts today we can make a update exclude Gadomancy and Witching Gadgets from the Update.
Lootbags and Quests are finish so lets get the Updatet not bigger.
In 1.0.7.8 we can add those new Mods when tests are done.

**Comment by Namikon** [comment]
I'd like to put my veto to stop the update. You haven't been on the Testserver; There are a _lot_ of issues. Random crashes, slow NEI, Rendering issues, stuff that hasn't been verified like proper tiering of lootbags, proper integration with Headcrumbs, Agricraft is completely unbalanced, and more. Sorry to play the bad guy, but this isn't ready to go public yet

**Comment by deeplyarnab** [comment]
Dont make the pack public yet, you can roll out some of the changes though. I am wiling to balance agricraft after feb gets over so you can remove it till then. Slow nei might be due to all the extra entries (like all the heads from headcrumbs maybe?)

**Comment by Teteros** [comment]
https://github.com/GTNewHorizons/NewHorizons/pull/502
