### ISSUE TITLE
add rutile quadrupeling

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4850]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SP
#### What do you suggest instead/what changes do you propose?
with the new titanium vein rutile ore is a big part of so quadrupeling using plants and bees should be availeble

**Comment by Dream-Master** [comment]
@botn365 show me the recipe you mean ?

**Comment by botn365** [comment]
9 titania leaf/titanium comb + 1 crushed rutile ore + 1000L water = 4 purified rutile ore
chemical reactor 24eu/t 4.8 seconds
