### ISSUE TITLE
Suggestion/Challenge for someone techy: Crafting Guide

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#4853]
I believe something like this has been brought up before.

There's a website/program http://crafting-guide.com/ that does a good job of resource planning for minecraft mods.

RedNicStone has already been working on making it work for GT here:
https://github.com/andrewminer/crafting-guide/issues/320#issuecomment-511791748

I'm curious if anyone is tech savvy enough to get this working on GTNH?  At least for most of the shaped/shapeless crafting.  It would be extremely handy for most players upto at least EV.

Any suggestions/volunteers would be great :)

**Comment by 0lafe** [comment]
Kind of already have AE for that once it gets to be a lot of stuff

**Comment by Highbeam** [comment]
Hence why I said this would be viable upto around EV which some people spend months to get to :)

**Comment by richardhendricks** [comment]
I had a note to look into it, but the requirement to manually gather recipes is a real downer. If RedNicStone has a way of autogenerating the recipes, that would be fantastic. We don't need *every* recipe in there - I think we know where iron dust comes from! But the more complex recipes would be a great start - maybe filter on anything needing more than 2 inputs or something.

The big advantage is not in game 0lafe, it's for offline use.

Been playing Planet Explorers for breezy break the last week, one nice "feature" it has is tracking a recipe - that puts the recipe in you HUD with the components needed and how many you have. It would be really nice to have similar for NEI to help you track the recipe you are working on when you have to go 3 crafts deep to get something!

**Comment by observeroftime02** [comment]
I think having a version specific for GTNH would be a cool idea, even if it's just to highlight the insanity of material cost for some of the high-tier items.

**Comment by 0lafe** [comment]
>The big advantage is not in game 0lafe, it's for offline use.

Honestly didnt think of that, that parts amazing. Idky i thought it was like an ingame thing

**Comment by Highbeam** [comment]
I've had a look into this with my limited technical understanding and reached out to the creator to see if this is hosted on AWS and whether it can be copied.

I'm pretty much starting from nothing here but going to try and do what I can to get anything working.

The main thing I don't know much about is Node.JS and Jade and setting up a webserver that can run the code on the website.  I believe I can setup a free webserver on AWS if someone can help with the setup.  It appears to use S3 storage for the code.

Next I will upload the website code from the repository and try and figure out how to extract the recipes (maybe RedStoneNic's code can help there)  

I anticipate some web gui updates to make the website more appropriate visually for GTNH and potentially more robust so it can use more of the screen when showing the steps/items (multiple columns).

If anyone can help get this up please give me a shout.

**Comment by richardhendricks** [comment]
@bigbass1997 has now created Not Enough Production. Check out the channel on Discord for more details.
