### ISSUE TITLE
Autoclave receipt Salis into Magic Essence doesnt work

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4854]
#### Which modpack version are you using?
7.5
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
uum and salis in Autoclave (HV) -> nothing was produced
#
#### What happened instead? (Attach screenshots if needed)
progress was showed, but nothing come in output slot (no auto output)
#
#### What do you suggest instead/what changes do you propose?
as NEI showes: Magic Essence
(or I want my uum back =( )

**Comment by observeroftime02** [comment]
I'm pretty sure there's a % chance for the output like with many other autoclave recipes. Can't check at the moment, but check the recipe to see if there's a % chance foe the output in NEI.
