### ISSUE TITLE
witchery wormwood is hard to obtain

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#4855]
put simply, you cant make wormwood crop in order to progress in witchery because of the rightclick to harvest wheat
more info: https://sites.google.com/site/witcherymod/wormwood
i play on delta , i tried going through config and disable rightclick harvest but it didnt work 

i suggest maybe either add a quest to obtain the wormwood as rightclick to harvest is useful for everyone

**Comment by richardhendricks** [comment]
New coins quest added - consumes 10 Spirit coins and 16 wheat. Sprig and wispy cotton is not consumed, not sure if it is supposed to.
![image](https://user-images.githubusercontent.com/1214811/71502306-15a90e80-2835-11ea-8d30-60aa8af4bc79.png)

**Comment by PoptartOverlord-Xabedo** [comment]
wispy cotton should be consumed, the only thing that shouldn't be is the mutating sprig .

**Comment by richardhendricks** [comment]
Ok, will do

**Comment by Prometheus0000** [comment]
Doesn't the sprig have durability to it too? You may want to account for that if you can, though it's not like it's hard to make another one.
