### ISSUE TITLE
 can't select gt purified/crushed/centrifuged ores in sfm

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4859]
#### Which modpack version are you using?
2.7.0.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i wanted to route gt purified/crushed/centrifuged ores via steve factory manager
#
#### What happened instead? (Attach screenshots if needed)
 The only purified/crushed/centrifuged ores you can find are either ic², bartworks or gt++ ones.
steve factory manager can't find gt ones, but you can find any other gt stuff registered with the same common id.

**Comment by observeroftime02** [comment]
For some odd reason all of the GT ore products are hidden in NEI, and I haven't found an option to re-enable it. When I asked about it, I was told "Why would you want to do that", well, this is part of the reason why I wanted to do that.

**Comment by Dream-Master** [comment]
Nei loads very slow if we add more items it loads longer

**Comment by boubou19** [comment]
i wanted to use sfm to set a filter which will send some purified ore into the sifter and the others into the thermal centrifuge. SFM filters and moves items very fast so if you have a replacement for it...

**Comment by observeroftime02** [comment]
GT Item Filters perhaps

**Comment by boubou19** [comment]
it's slower + you can only filter via oredictionnary: i need to send some crushed purified ore into the sifter and some into the thermal centrifuge

**Comment by observeroftime02** [comment]
There's the type filter, and then there's the regular item filter which lets you set individual items. Could be a working solution for the time being. It's what I ended up using before AE anyways.

**Comment by boubou19** [comment]
i doubt it will be fast enough because i need to route the items very fast: i noticed too much items in a pipe start causing lags

**Comment by draknyte1** [comment]
Change the GT config. It’s a clientside option.

**Comment by observeroftime02** [comment]
Where in the config is it? I've been looking for this for ages.

**Comment by boubou19** [comment]
maybe     B:show_all_metaitems_in_creative_and_NEI=false, line 86 in GregTech.cfg?

**Comment by observeroftime02** [comment]
That one did it. Thanks. Don't notice much of a performance difference.

**Comment by boubou19** [comment]
maybe you should put that somewhere in the quest book so that way ppl can enable it if they need it.

**Comment by richardhendricks** [comment]
Where should it be? Under AE? SFM? PR?

**Comment by boubou19** [comment]
you don't need it in AE because you need to set filters manually with the items, SFM clearly needs it as stated above, and i don't know about project red almost never used it.
