### ISSUE TITLE
Skins glitched out

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#486]
A weird issue either caused by one of the new mods, updated mods or Thermos; The skins of the players randomly "glitch out", as they where thrown into a blender. Yesterday I went from Twilight back to Earth, and my skin was reset to Vanilla MC.
Confirmed by Drobac; Needs to be investigated

**Comment by Teteros** [comment]
I recall this happening even on the live server, check @ProsperCraft streams.
The skin switching to Steve's (Vanilla MC).

**Comment by deeplyarnab** [comment]
I think the steve skin switch is normal with teleportation to different dimensions. I face that a lot in normal servers too and generally a /suicide does the trick, but even sometimes dying in the same dimension or /suicide does it to me, got pretty used to it, lol.

Namikon, i think the tails mod can be causing it, i remember seeing some warn msg from the mod about the skin being a dynamic ____. Try removing it and see.

**Comment by ProsperCraft** [comment]
I am having this issue as well, I have to reconnect a couple times to record with my own skin sometimes :)

**Comment by Namikon** [comment]
@deeplyarnab k, going to check that

**Comment by Namikon** [comment]
Semi-Confirmed. It is caused by Tails. After removing it, no weird skin bugs occurred after logins.
And even better; The slow NEI problem is gone too. Will update the testserver/pack today and keep an eye on that for a couple more days

**Comment by deeplyarnab** [comment]
I can confirm the blending too, removing tails didn't change much for me (nei is still a slower)

**Comment by Dream-Master** [comment]
ok i close this now.
