### ISSUE TITLE
[Suggestion]Add AutoMagy's IEssentiaLocusReadable interface to Gadomany

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4862]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
AutoMagy's EssentiaLocus can't manage Gaddancy's EssentiaCondenser.

#
#### What do you suggest instead/what changes do you propose?
I suggest that adding AutoMagy IEssentiaLocusReadable interface interface to Gadomany.

According to the original issue(https://github.com/Tuhljin/Automagy/issues/67), if IEssentiaLocusReadable is added to Gadomany, it will be solved.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/Gadomancy/pull/2

code done, needs to be tested WITHOUT AutoMagy for crashes.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Gadomancy/releases/tag/1.0.7.5
@yukieiji can you test it please with this version i linked before. Thanks

**Comment by yukieiji** [comment]
I tested that EssentiaCondenser works without AutoMagy, and tried EssentiaLocus manage EssentiaCondenser with GTNH v2.0.7.5 and Gadomancy v1.0.7.5
They worked well!!.
![2019-07-22_17 45 13](https://user-images.githubusercontent.com/40425798/61619561-14821d00-acaa-11e9-9e5c-0c42cae95de6.png)

Thanks you @Dream-Master and @bartimaeusnek.

**Comment by Awfullyfishy** [comment]
Not sure if this is worked on still but there's an issue with this integration. Using Gadomancy 1.0.7.5 and Automagy 0.28.2. 

Linking a Condenser to a Essentia Locus and hovering over the Locus will always show three times the amount of essentia that is stored in the Condenser. Meaning if it stores 1 Lux, the Locus will show 3 Lux, 28 Lux will show 84 Lux. 
Most likely a weird interaction with the Locus counting all three tiles of it as separate containers? It's a minor issue as pulling essentia out from the Locus won't pull out 3 times the amount, but it breaks Vis Readers and doesn't work quite correctly.

Would love any help as I'm nowhere near knowledgeable enough to duct tape one together myself.

**Comment by yukieiji** [comment]
After testing again, @Awfullyfishy said it was showing 3 times the amount of Essentia.
![2019-10-10_10 36 49](https://user-images.githubusercontent.com/40425798/66532520-9ca9ed00-eb4a-11e9-93eb-efb93f2ddc37.png)
![2019-10-10_10 36 53](https://user-images.githubusercontent.com/40425798/66532521-9ca9ed00-eb4a-11e9-9ccd-32f611de1531.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea if this can be fixed?

**Comment by Shibva** [comment]
This issue is becasue of how the locus is programed, it looks for adjacent jars  and reads their value; because the thing consist of three blocks itself its reading the values from all three of the blocks. a solution would be to make only one part of the 3 blocks actually read  it and prevent the other 2 from being read

**Comment by Shibva** [comment]
this woudnt be much of an issue if automagey was coded to only read one thing no matter what if a crystal eye was focues

that way the thing will only focus on one porton of the block and not spread to adjacent things
