### ISSUE TITLE
Quest Correction?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#4865]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Made an iron hammer, excavator and lumbering axe. Expected quests to not complete since they say "Steel".
#
#### What happened instead? (Attach screenshots if needed)
Quests completed as if I had made steel tools.
#
#### What do you suggest instead/what changes do you propose?
Change the quest book to say iron or change the quest to require steel.

**Comment by Dream-Master** [comment]
It was changed to ignore nbt data but i guess this dont work propertly

**Comment by Dream-Master** [comment]
I think make this tool in Iron isnt realy good since you have steel at this tier to mak more durable tools.

**Comment by Dream-Master** [comment]
In sp it works
![image](https://user-images.githubusercontent.com/2970688/61993703-cedd9f80-b06f-11e9-894c-045c28446adc.png)
![image](https://user-images.githubusercontent.com/2970688/61993706-d4d38080-b06f-11e9-94ef-b2aee646351e.png)
Maybe i change the quest text
