### ISSUE TITLE
mobessence recipe issue

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#4867]
#### Which modpack version are you using?
2.0.7.5
#### If in multiplayer; On which server does this happen? 
delta
#### What did you try to do, and what did you expect to happen?
make mobessence
#### What happened instead? (Attach screenshots if needed)
recipe requires 1332 xp but the brewery can only hold 750 
![image](https://user-images.githubusercontent.com/40670872/61647460-0d610c00-acb6-11e9-9943-deb9f8c823db.png)
![image](https://user-images.githubusercontent.com/40670872/61647487-1a7dfb00-acb6-11e9-97c8-58730bf449cf.png)

**Comment by Dream-Master** [comment]
did the hv version holds more @PoptartOverlord-Xabedo ?

**Comment by boubou19** [comment]
it seems to be hardcoded at 750 mb, here is my IV one:
![image](https://user-images.githubusercontent.com/12850933/61656327-d2180a80-acc0-11e9-98a1-7ea71d189bdd.png)

**Comment by Dream-Master** [comment]
is this a gt or gt++ recipe ?

**Comment by boubou19** [comment]
It's a GT++ recipe. Back in the past we were used to convert the liquid experience into mob essence with this gt++ block:
![image](https://user-images.githubusercontent.com/12850933/61658343-713f0100-acc5-11e9-912b-8c6117289d4b.png)

**Comment by Dream-Master** [comment]
@draknyte1 any idea? is this a multiblock recipe ? Is there a multiblock for brewing ?

**Comment by draknyte1** [comment]
Make your breweries not shit and expand their internal tanks. The actual fix for this and doable by you. Unless there’s a brewery In the multimachine, then it’s doable that way in the meantime.

**Comment by observeroftime02** [comment]
The 9-1 does not have a brewery, but perhaps you could get around this by using the brewery in a processing array? It allows you to input more fluid if I recall correctly.

**Comment by draknyte1** [comment]
That’s also a valid workaround. I think brewery mode was removed in favour of another, iirc.

**Comment by PoptartOverlord-Xabedo** [comment]
ah i see, will do the processing array

**Comment by Dream-Master** [comment]
expande brewery tank or not ? @PoptartOverlord-Xabedo @boubou19 @observeroftime02 ?

**Comment by boubou19** [comment]
well i think it should have its internal tank size based on the voltage tier if we look how GT machines evolve in general. But you can also let the recipe stay like that because if i remember correctly, the mob essence is only used to make the big chicken eggs, which give access to the stemcells. If you need to use stemcells, in my opinion, the processing arrays are easily accessible.

**Comment by richardhendricks** [comment]
Do we need to update a quest?

**Comment by Dream-Master** [comment]
brewery works different. Not sure what happend if we change it. Brewery has it's own class with tank size 750 for all tiers.

**Comment by richardhendricks** [comment]
I am OK with changing it to 1500. It doesn't need to scale with tiers like the other tanks.

**Comment by Dream-Master** [comment]
@draknyte1 ok i see the device but what we do in the mean time. Should i add a 2. recipe with half of the liquid amount ?

**Comment by Dream-Master** [comment]
@bartimaeusnek or a nice vat recipe (Bart Works) fits maybe too ?

**Comment by draknyte1** [comment]
Don’t do anything in the meantime. The new recipe you added is wrong, it breaks the ratio of XP values. (From memory, it is why the recipes have odd amounts.)

This is currently craftable with a PA and anyone wanting to craft it can do it that way. Otherwise expand tank sizes as suggested already by myself and moron.

**Comment by Dream-Master** [comment]
PA ? @draknyte1

**Comment by draknyte1** [comment]
Processing Array?
Y’know.. the multiblock..

**Comment by Dream-Master** [comment]
ah yea ok. i revert commit and close issue.
