### ISSUE TITLE
pyrolyse oven doesn't form with electrum flux and awakened draconium coils

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4868]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
wanted to upgrade my pyrolyse oven with the new coils
#
#### What happened instead? (Attach screenshots if needed)
It doesn't form but when i replace the new coils with naquadah alloy coils it forms again.
#
#### What do you suggest instead/what changes do you propose?
make the pyrolyse oven form with the linear boost described in the pyrolyse oven controller tooltip

**Comment by botn365** [comment]
there is already a ticket #4848

**Comment by boubou19** [comment]
whoops sorry
