### ISSUE TITLE
weird rendering when looking at stabilized node

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4872]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
after the last update, when i look at stabilized node (mine or other players' ones) i have strange
animations making flickering the render of all the tile entities:
that's for my personal node:

![lightning](https://user-images.githubusercontent.com/12850933/61756559-d6295280-adbc-11e9-8cd4-1bc8181624fa.png)
![2019-06-30_21 24 33](https://user-images.githubusercontent.com/12850933/61756568-dd506080-adbc-11e9-86a7-3e862be853e4.png)

that's from xabedo's node:
so this is normal view:
![not flickering](https://user-images.githubusercontent.com/12850933/61756609-fc4ef280-adbc-11e9-91a9-33357ba32c2c.png)

regularly i get that for a frame:
![flickering](https://user-images.githubusercontent.com/12850933/61756608-fc4ef280-adbc-11e9-9a9d-1938f0cf4cfc.png)

i have this issue on both my laptop and my desktop computer, and i did not touched the graphic driver settings, and it happens on both fast and fancy settings, playing without optifine.

Never saw the animation before, so where does it come from? And can i turn it off or something?

**Comment by Dream-Master** [comment]
Are the devices only Thaumcraft stuff or mixed magic mods ? @boubou19

**Comment by boubou19** [comment]
only thaumcraft stuff

**Comment by Dream-Master** [comment]
@boubou19 let me know if it was Java version.

**Comment by boubou19** [comment]
I was using open J9 for playing Minecraft: the issue comes from here. I reinstalled vanilla java and all went back to normal. So if you decide to make a wiki page or something for #4434, you'll need to warn the player that he can have some weird issues with rendering (i also experienced issues with compressed chests with open J9)

**Comment by draknyte1** [comment]
Java > 8 isn't really supported *At All* for MC 1.7.10. Nothing we can do there.
As developers, we're supposed to be using J6/J7 subsets according to Lex and the Forge developers. 🤷‍♀
