### ISSUE TITLE
easy recipe for low kinetic wind generator is still enabled

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4873]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
a player reported to me that the easy recipe for the low kinetic wind generator is still enabled:
so here is the intended recipe:
![image](https://user-images.githubusercontent.com/12850933/61831265-9d958180-ae6d-11e9-8bc1-5f47043f7339.png)
here is the easy recipe:
![image](https://user-images.githubusercontent.com/12850933/61831286-b30aab80-ae6d-11e9-84db-ac262074238c.png)

This is the only one remaining recipe, i checked all the others.

**Comment by PoptartOverlord-Xabedo** [comment]
funny thing is that i've noticed it since 2.0.6 versions
