### ISSUE TITLE
Power Station With (MAX) Cells Does not accept Hatches above UHV

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/NewHorizons#4874]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
myftb.de
#
#### What did you try to do, and what did you expect to happen?
The PSS forms completely if i'm using Hatches/DynamoHatches at UHV or below. If i use UEV hatches at the same spot, die PSS does not form.

#### What do you suggest instead/what changes do you propose?
Add above UHV Hatches to the functionality.

**Comment by observeroftime02** [comment]
They don't work because the tier of the PSS is limited by the cells on the inside. To accept UEV hatches you would need UEV cells that don't exist.

**Comment by Dream-Master** [comment]
@draknyte1

**Comment by ChrisLua** [comment]
@observeroftime02 UHV cells dont exist eigther.
Its ..., ZPM, UV, MAX. Unless MAX isnt a typo,

There are Vanadium Redox Power Cells **(MAX)**
Which does stand at the exact position, where all other Voltages stand before. I assume thats The MAX voltage. Guiding me that any hatch should work.

**Comment by observeroftime02** [comment]
MAX voltage is UHV actually, not the maximum possible. See MAX voltage energy buffer (It's UHV). GT++ has a funny way of naming things, it doesn't help that there's another MAX voltage in the game. So there's your problem.

**Comment by ChrisLua** [comment]
Which guides us to the question if this is rather an Issue than a tool tip advice.

I now assume that UHV will be the maximum for hatches in combination with GT++, and this is not changing soon right?

**Comment by draknyte1** [comment]
Standard GT goes UV -> MAX. 
GTNH defines several extra tiers in between. (UHV/etc)
MAX for both is Integer.MAX_VALUE.

I do nothing to attempt support for GTNHs intermediary tiers, never explicitly have. 
Feel free to open a ticket on my GitHub and I’ll look into it.
