### ISSUE TITLE
gycerol electrolyser receipt also for large electrolyser

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4875]
#### Which modpack version are you using?
2.5
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
search for large electrolyser receipt for glycerol 
#
#### What happened instead? (Attach screenshots if needed)
only small electrolyser has receipt with cells
#
#### What do you suggest instead/what changes do you propose?
receipt in large electrolyser

**Comment by Dream-Master** [comment]
@Ngar1 did you mean electrolising out of the fluid glycerol ?

**Comment by Ngar1** [comment]
yes
