### ISSUE TITLE
4 GT++ Multiblocks alternately have incomplete structure

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#4877]
#### Which modpack version are you using?
2.0.7.5

4 GT++ Multiblocks alternately have incomplete structure.
**Ore Washer
Thermal Centrifuge
Amazon Prime
Energy Station**

Once fix one Multiblock of them by rearranging, the others will have incomplete structure.

**Comment by boubou19** [comment]
Strange,never had that with the ore washer, the amazon prime, and the thermal centrifuge,
and i had them running 24/7 since 4 days.

**Comment by Kiwi233** [comment]
@boubou19 
If you haven't changed their instucture since update, they will run perfectly. But when you changed one of them, this situation will happen...

**Comment by boubou19** [comment]
it's a fresh build because i re did my ore treatment system, but old crafted blocks if it helps

**Comment by Kiwi233** [comment]
@boubou19 
Thx, i will test again

**Comment by Kiwi233** [comment]
I test again.
I build those 4 Multiblocks in 2.0.7.0, they can run perfectly.
Then, i update to 2.0.7.5. Those Multiblocks can still run.
But when i break one casing, replace this casing again, the multiblock still show "incomplete structure"

**Comment by boubou19** [comment]
is the muffler hatch not obstructed? i had some issue when they were obstructed

**Comment by Kiwi233** [comment]
No, i change nothing but relpace one casing
