### ISSUE TITLE
Disable the usage of the "Endest Pearl" from Avaritia

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#488]
Caused some sort of destruction that was impossible to repair even with Prism rollback.
If possible, the pearl should be added to MyTown2 protection list to avoid usage close to (Player)Claims ( To be investigated by me ). If that's not possible, the pearls usage should be disabled/prevented

**Comment by Dream-Master** [comment]
it is a crafting item. We can add a new item via core mod not have any function and remove the avaritia item via minetweaker.

**Comment by Dream-Master** [comment]
This recipe is quite expensive. Maybe if we extend the Block limiter mod someday we can forbid to use this item in Dim 0.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/608

**Comment by Dream-Master** [comment]
Fixed and available in Version 1.0.8.5.
