### ISSUE TITLE
Ae2 System lagging the game

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/NewHorizons#4882]
#### Which modpack version are you using?
gtnh 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I tried using my ae2 system multiple times over the course of the day. Fine at first, but the game started to lag and slow down, this got worse over time.
After roughly 2-3 hours of active playtime, its lagging so hard that i can barely play, warp commands and travel anchors are slowed down, it takes ~60 seconds to open a vanilla chest, breaking and placing blocks is laggy.
Relogging fixed this issue for only about 10 minutes and once, it was so bad that i could not reconnect to the server and only reinstalling the modpack could fix it (happened precisely at the 28.07.2019 afternoon, i could connect to epsilon and singleplayer just fine)
after some troubleshooting i could rule out server tps, connection problems, not enough ram, etc, these were not the issue.
i highly suspect the ae2 storage system being responsible, because the lags stopped after i relogged and touched anything but the ae (ofc its a central component of my base, so not using it is no option)
The problem also only occured after i started using the ore drilling rig and thus expanding my item storage by a lot over the course of a few days.
but after all, my ae2 system is not so big, that i could call this a reasonable source of lag.
1 ME controller, 106 interfaces, roughly 500k items stored, only the most central stuff up to late IV age is automated
#

#### What do you suggest instead/what changes do you propose?
Since i made sure that all other possibilities are not the issue, i believe that some kind of memory cache or similar workspace fills up and the heavy information load when opening the ae2 system contributes mainly to it, until the game is unplayable. 
im not sure what exactly could be done, but maybe some kind of option to manually flush cached information could help

![javaw_2019-07-29_20-53-29](https://user-images.githubusercontent.com/46688121/62074563-59c2c380-b243-11e9-8766-a0bd3daefa8b.png)

![2019-07-29_20-53-10](https://user-images.githubusercontent.com/46688121/62074546-529bb580-b243-11e9-9028-ed4f1205f3b3.png)

**Comment by boubou19** [comment]
I have this issue too on delta(even if it's not recent: first happened back in 1.4.x) and over the time i rebuilt my ae system a couple of time, sometimes bigger, sometimes smaller, etc. What i was used to believe was the fact that each time i opened AE (except when i open ae for the first time after loaded the game which is super long and normal) i had some delays with everything in the game including chat lags, only a relog or waiting a long time could fix it. And when i checked my internet, the download speed was crappy, so i though i had found the cause of it, explaining why i did not reported it before. 

But recently, i still had those issues but my download speed was more than correct (1 mega byte per sec) and it does not happen every time: sometimes it lags, sometimes not. Also when it happens; even if i have huge delays including chat, when i type something in the chat, the discord bot and the other players get my messages. 

The issues start to happen when i open either a ME terminal, ME crafting terminal, ME wireless terminal or a ME wireless crafting terminal (with and without infinity card). Other things of the AE system doesn't seem to trigger the lag.

**Comment by Dream-Master** [comment]
@DeForce I know you looking into extra cell code maybe you able to look into ae code also ?

**Comment by DietmarKracht** [comment]
You can workaround this by using arcane crafting terminals as these have different behaviour

**Comment by boubou19** [comment]
Yeah for an odd reason this seems to work: i opened the arcane terminal and everything was instant,then i opened the regular crafting terminal and i got the delay. Is it possible to somehow replace the code of the terminals with the one from the arcane terminal?

**Comment by DeForce** [comment]
That is the kind of issue that you call "I blow air and something is lagging".
I would say that is could be something server specific, or I need exact replication steps of the issue.

Just because arcane terminal fixes the "issue" doesn't mean that AE2 is the cuplrit, as acrane terminal is using the code from AE2 terminal.
Without reproduction steps doing anything is a "guess in the wild".

**Comment by boubou19** [comment]
i have the feeling that regular terminals send packets and not receiving one of them make us desync from the server.

**Comment by boubou19** [comment]
in fact i was lucky earlier: the same issue happens also with the arcane terminal.

**Comment by DoomSquirter** [comment]
so while we played on a regular forge server, nobody had a single issue with ae terminal lagging ppl.  we did not have the amt of players delta/epsi have but we also did not have any of the lag issues they have as well.

I have to suspect that this is just another example of straying from vanilla forge server more than anything else.  if you think about it, it makes sense.  if you have your AE spread about in multiple chunks and yet the server is distributing different tick rates for each of those chunks, ae is probably confused as hell trying to figure out what's going on.  my guess at least.

**Comment by gordominossi** [comment]
I have the same issue on Epsilon. Makes the game unplayable :(
Arcane terminal sometimes causes a little less lag, but still is not nice and it doesn't have the same features as the other terminals

I'll start from scratch on Eta

**Comment by repo-alt** [comment]
Do I understand it correctly that it is a client side lag? I wonder why some people have it and some do not

**Comment by boubou19** [comment]
Must be some random desync, i can play weeks without having it, then it eventually comes back, no matter how good is my connection.

**Comment by Prometheus0000** [comment]
Does removing and re-placing the ME controller blocks (or turning power off and on) fix it?

**Comment by boubou19** [comment]
a relog fixes it most of the time, but the game is extremely long to do any action when it happens.
