### ISSUE TITLE
Make ore drilling rig mining distance configurable

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4887]
As a suggestion, if possible, it would be great if we could hit an ore drilling rig with something like a screwdriver to adjust its mining distance. 

I love that the T5 ore drilling rig has fortune 20 but dropping it in the deep dark on specific veins it has to search way out further than I realistically would like and picks up ores I don't care for. If I can scale it back and not have it search a radius of 144 it would be great.

**Comment by observeroftime02** [comment]
You can, in theory, scale it back by using chunk loaders, because once gone, it will only mine in the loaded area. Just some ideas.

**Comment by richardhendricks** [comment]
It's already on the schedule of things to add, basically add support for using a circuit to set drilling range.

**Comment by richardhendricks** [comment]
#4493
