### ISSUE TITLE
Make GT++ Selenium the main material for LuV Hulls

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#4889]
This removes any issues involving chrome not being a "Tiered" material for LuV.
Adds a processes to produces this material that brings it into line with titanium and tungstens
makes everyone happy for once in this community.

Poke @draknyte1 for more details

**Comment by Shattered2909** [comment]
Alkalus bad!

But really, its a good idea, 100% supporting!

**Comment by basdxz** [comment]
Pull this material from G++ and integrate it into GT5u-GTNH Branch

**Comment by richardhendricks** [comment]
https://en.wikipedia.org/wiki/Selenium#Chemical_compounds

**Comment by draknyte1** [comment]
> Pull this material from G++ and integrate it into GT5u-GTNH Branch

Processing chain for Selenium cannot be moved from GT++.
EBF processing for materials for every tier is boring, why not change it up?
Migrating Selenium out of GT++ serves 0 purpose at all, as people already have this material. GT++ produces/owns several other elemental materials and this hasn't ever been an issue prior.

**Comment by Anarack** [comment]
Solved by latest zeta and used a different material.
