### ISSUE TITLE
Charm of Keeping <-> Gravestones interaction

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#489]
Deadlocks Server when a player has a charm of keeping in inventory on death.. Request to be Disabled as it is a game breaking bug.

**Comment by Dream-Master** [comment]
So what exactly happened here ? How the charm of keeping working different on servers then on clients (MP SP Game)

**Comment by Goofyschooler** [comment]
@Dream-Master ask Goshen on discord. He might have a better explanation

**Comment by deeplyarnab** [comment]
We explained it to him

**Comment by Goofyschooler** [comment]
Okay thank you @deeplyarnab

**Comment by Teteros** [comment]
@Namikon died both in twilight and overworld a few times in our test server, having the T1-3 charm equipped and did not crash his client nor the server itself. The gravestone kept the items as expected.

@Goofyschooler 
@ProsperCraft
Can you outline the steps to reproduce this issue?

**Comment by Dream-Master** [comment]
The testserver using a newer version of open blocks mod. Can this be the reason?

**Comment by Goofyschooler** [comment]
The bug occured when Goshen Died in the End when fighting the dragon with the Charm of keeping and as soon as he died it deadlocked the server. Dingo-"Openblocks and Twilight were having a fight on who were trying to keep the items"

**Comment by Namikon** [comment]
I just jumped to the end, got killed multiple times by various mobs including the dragon and the server is still fine. Every time the Gravestone spawned, charm is gone, and inventory saved. Everything as it should be. So if we happen to have a newer Version of Openblocks here, it seems that problem is gone. At least I can't reproduce it

**Comment by ProsperCraft** [comment]
We are using KCauldron, we need to switch to Thermos and see if it resolves...been waiting for a stable version of Thermos, it changes every day.

**Comment by Teteros** [comment]
Please do report if works on your end, I'm curious to see if it's just thermos working better.
Could also be something magical with the OB update.
