### ISSUE TITLE
Dark Helm + Anvil Issues

### ISSUE THREAD

**Issue by Bubunator** [GTNewHorizons/NewHorizons#4892]
Which modpack version are you using?
gtnh 2.0.7.5

If in multiplayer; On which server does this happen?
delta

What did you try to do, and what did you expect to happen?
I tried to upgrade my Dark Helm (Item ID 7997) with a Potion of Night vision ( Item ID 373:8198 and 373:8262) i had an anvil and enough lvl but the recipe seems to be invalid. Upgradeing with a vibtrant crystal (7950:6) worked just fine. 
Also crafting an Anvil (Item ID: 145) with any recipe or matierial gives one always a very damaged one (145:2) not sure if this is intended.

**Comment by DoomSquirter** [comment]
verify which night vision potion you added.  iirc there's more than one with different use times

same goes for speed on the boots

**Comment by Bubunator** [comment]
i mentioned the item IDs, i tried the 3minute and 8 minute night vision potion

**Comment by draknyte1** [comment]
Item IDs are unique for everyone. Forge assigns them and retains a mapping. So providing them gives no real insight to anyone else. 

There’s several types of each potion and while they may look identical, they’re not.

**Comment by richardhendricks** [comment]
I think what I discovered is that somehow, the number of potions created at a time is a part of the NBT or something?  Try making 3 potions in a potion stand and using that. Or maybe 1?

**Comment by Bubunator** [comment]
but the NEI Item ID´s should be the same right?

**Comment by Folanlron** [comment]
Try making 3  8 minute night potions at once, then try using it too add onto the dark helm, NBT values which you can't see unless you activate a certain NEI feature matter. 

Witchery has the same problems when doing kettle brew's that require potions(known issue for a long time)

**Comment by Bubunator** [comment]
that didn't work but with the 3minute version it worked fine! Ty

**Comment by richardhendricks** [comment]
Anvil works fine for me.

Upgrade quest mentions using 3:00 potions made 3 at a time.
