### ISSUE TITLE
Crafting paper with chad and stone halfblocks

### ISSUE THREAD

**Issue by ShadowMiner** [GTNewHorizons/NewHorizons#4896]
#### Which modpack version are you using?
2.0.7.5-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Eta server
#
#### What did you try to do, and what did you expect to happen?
Craft paper and get back stone halfblocks
#
#### What happened instead? (Attach screenshots if needed)
Stone halfblocks disappear and you need to craft alot of it to make paper with chad
#
#### What do you suggest instead/what changes do you propose?
Use stone halfblocks in craft but dont take it.

**Comment by Dream-Master** [comment]
Nothing is for free in GTNH. Stone halfblocks haven't durability bars so I don't see a point for not using it up.

**Comment by Dream-Master** [comment]
later on you can make the recipe in machines.

**Comment by ShadowMiner** [comment]
some time before it was stone halfblock free. this is why i asking

**Comment by ShadowMiner** [comment]
> Nothing is for free in GTNH

then i have no questions.

**Comment by Dream-Master** [comment]
it was never free

**Comment by repo-alt** [comment]
I think I remember it returning slabs in some version (or perhaps it was vanilla GT recipe?)
