### ISSUE TITLE
Cassiterite Dust/Sand electrolyzing to Tin + Oxygen bug?

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/NewHorizons#4898]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
Seeing in chemistry, Cassiterite Sand/Dust (SnO2) can be electrolyzed to Tin and 2x Oxygen. But the recipe should need 3x Cassiterite Sand/Dust, not only one dust, you can see it in Formula. For example, magnetite accepts this law. 
![image](https://user-images.githubusercontent.com/25156941/62370607-48c3cc00-b53b-11e9-82a0-7cd879f7dece.png)
![image](https://user-images.githubusercontent.com/25156941/62370613-4c575300-b53b-11e9-8cda-82ee485ae664.png)
![image](https://user-images.githubusercontent.com/25156941/62370640-62651380-b53b-11e9-973a-91e2b0822eca.png)
![image](https://user-images.githubusercontent.com/25156941/62370650-65f89a80-b53b-11e9-95b5-9069f17b801b.png)

**Comment by draknyte1** [comment]
All recipes should be ‘mass conservative’ like magnetite. Some people who’ve contributed to GT over the years either haven’t noticed or felt their minority of recipes needed it and breaking consistency didn’t matter. 

If any other recipes like such exist, they’re wrong. (Just in case anyone reads this in future)

**Comment by richardhendricks** [comment]
This recipe is intentional as a cheap source of oxygen for players starting the game, that does not kill their tin output (much, there is still a small loss vs blast furnacing).
