### ISSUE TITLE
[Request]Thaumcraft Imbued fire

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#490]
When the imbued fire is used (any) loads chunks and causes severe damage to Land surrounding the start point. Request the recipe be removed but allowed to be researched and the items removed from the game not allowed to be cheated in. In return this allows players to get to the infused crops afterwards. (Thaumic Tinkering)

**Comment by Namikon** [comment]
Related: #284

**Comment by Goofyschooler** [comment]
@Namikon Should be disabled in All Worlds and their should be added procautions to completely prevent them from being crafted or even spawned in

**Comment by Namikon** [comment]
I just linked that from the past, where I was a mortal on the server struggling with survival :) But IMHO this is a thing server admins have to take care of. I totally agree that these fires should never be available on a MP Server; For single player however, they add a rather unique aspect of magic.

Gonna discuss that in our next meeting. I could imagine to create 2 sets of configurations; one for SP and one for MP

**Comment by Goofyschooler** [comment]
But For Sp they still destroy worlds? Why allow it to be crafted? It can not be controlled no matter what you do.

**Comment by Namikon** [comment]
There are a lot of items that can cause serious damage to your world. In fact, overheating an ic2 nuke basically ends your gameplay if it goes off in your base. It's not something you stumble upon / place by accident. But that's just my own opinion. 

As I said, gonna take this as a open topic into our next meeting.

**Comment by Dream-Master** [comment]
I don't like the idea to disabled all the things even there items are dangerous. (the same with the Warp and Wither in the Over world damaging Blocks) The best thing would be to disable the right click function on some items in some dimension like Block limiter does with placing Blocks. I will change this recipe too when I continued Thaumcraft addon mods.

**Comment by Drobac** [comment]
You can disable imbued fire crafting in Thaumic tinkerer configs

**Comment by Goofyschooler** [comment]
@Drobac yeah fixes the problem of not crafting it. But their is infused seeds afterwards which is gated by the imbued fires. Moving the infused seeds would be the best bet then you can disable the imbued fires without any problems.

**Comment by Drobac** [comment]
I need to check ingame, but doesnt it just prevent you from crafting the imbued fire? So you could still research it and the seeds afterwards

**Comment by Goofyschooler** [comment]
No it disables it completely, removes it from the thauminomicon

**Comment by Drobac** [comment]
ok, will check for a way around it

**Comment by Goofyschooler** [comment]
Alright, easiest way if it works is just to remove the crafting of it. Or add a configuration option to remove the crafting so servers have the option.

**Comment by Drobac** [comment]
yep, we discussed the crafting config option, will probably end up that.

**Comment by Goofyschooler** [comment]
Yeah seems like the most viable option. And when you add a public download for servers add a note file explaining all the added configurations so people can be more informed.

**Comment by ProsperCraft** [comment]
We disable inbued fire in the config on all of our servers, it took our DW20 server to 4TPS for days before we deleted the nether.  Someone released it in the nether and it was crawling through the entire world changing lava to obsidian, even when players were not in the nether.
All of the players that are doing thaum research have to disable it in their client to continue their research when they reach that point.

**Comment by Teteros** [comment]
Will be nerfed during Thaumic Tinkerer mod phase, hopefully for 1.0.7.8.

**Comment by Dream-Master** [comment]
I change this recipe and it is really unstable and really forbidden knowledge. If we ever expand the Block Limiter Mods to items we maybe can forbid right click on Dim 0.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/608
