### ISSUE TITLE
Alternative Tanned Leather recipe for Mv/hv

### ISSUE THREAD

**Issue by speckbrot87** [GTNewHorizons/NewHorizons#4900]
#### Which modpack version are you using?

#2.0.7.5
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#Add recipe for dyhidrator or chemical bath plus Tannin to get Tanned leather out of leather bound (dyhidrator) or leather with phenol (chemical bath)
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

Add recipe for dehydrator or chemical bath plus Tannin to get Tanned leather out of  bound leather (dyhidrator) or leather with phenol (chemical bath)

**Comment by draknyte1** [comment]
https://github.com/alkcorp/GTplusplus/issues/487

https://github.com/alkcorp/GTplusplus/commit/393abfa8d3ac9c6bdd82fa09905f18fc8b583021

**Comment by richardhendricks** [comment]
Dehydrate your grapes to raisins. Or make some Styrene, Benzene or Ethylene at MV. Either way, this device is a nice to have.

It also does the Drying Rack recipes as well.
