### ISSUE TITLE
The behavior of Mega Vacuum Freezer is strange

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4901]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I tried to cool hot osmium with ZPM 2A.
#
#### What happened instead? (Attach screenshots if needed)
Operation time becomes 14 seconds, 7 seconds, 3 seconds.
In addition, work doesn't complete even if it works.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Kiwi233** [comment]
The consume of the Mega Vacuum Freezer depends on how many items in its input bus.
Up to 256 items.

**Comment by yukieiji** [comment]
Does that mean that Voltage Tier varies with the number of items on the input bus?

**Comment by boubou19** [comment]
nope it only allows the max number of being processed in parallel. The recipe time stays the same. Anyways i tried it in sp with 2A ZPM with the latest dev version and i cooled that amount of hot osmium ingots successfully:
![image](https://user-images.githubusercontent.com/12850933/62424719-0208da00-b6d3-11e9-8fb1-7a1c94835855.png)

So if there is a bug in live version it's fixed in dev.

**Comment by yukieiji** [comment]
@boubou19 Are the sizes of Input Bus and Output bus the same?
And my Mega Vacuum Freezer was crossing chunks, what about your Mega Vacuum Freezer?

**Comment by boubou19** [comment]
my mega vacuum freezer doesn't cross border and tested with both UHV buses, but iirc past EV the size of the buses doesn't increase so...

**Comment by bartimaeusnek** [comment]
i assume its either connected to the crossing chunks, the position of the energy hatches (in 2.0.7.5 the bottom check does not work flawlessly) or a power failue. if you want to fix it:
first move all energy hatches to any layer but the bottom layer, second but battery buffers with 2Batterys or Cable Diodes that are limiting to 2A directly in front of the hatches and if that doesnt help, rebuild the structure in ONE chunk.

**Comment by yukieiji** [comment]
@bartimaeusnek My Mega Vacuum Freezer installed an energy hatch in the top layer or the layer one layer below the top layer and put two batteries in the battery buffer for direct energy input.....
Does the new version of bartworks work with Mega Vacuum Freezer even when it crosses chunking?

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/62425762-1fdb3c80-b6dd-11e9-83ee-9e81a42cb481.png)

**Comment by yukieiji** [comment]
@boubou19 What version of BartWorks are you using?

**Comment by boubou19** [comment]
latest dev

**Comment by yukieiji** [comment]
I'm glad to hear that it has been fixed in the latest version.
Thank you.

**Comment by boubou19** [comment]
maybe related on your server type: tested on forge-only environment. Do you have thermos or regular forge server?

**Comment by yukieiji** [comment]
My server uses Contigo which forks Thermos.

**Comment by boubou19** [comment]
if you can try on vanilla forge

**Comment by CalterOK** [comment]
I also encountered a malfunction with small amounts of material for processing (1-10 ingots), the installation of additional hatch energy helped. I tried to increase the hatch range (set 1) but the refrigerator also did not work.

**Comment by boubou19** [comment]
Yeah in fact if you bloat the input bus you don't need more hatches but for low amounts there was more overclocking leading to a failure

**Comment by CalterOK** [comment]
boubou19 Is it possible to do so that the acceleration does not exceed the maximum available voltage?

**Comment by boubou19** [comment]
well bart already fixed this in dev so you'll have to either bloat the bus or wait for new version
