### ISSUE TITLE
Mod Suggestion - Ewy's Workshop

### ISSUE THREAD

**Issue by AmberSherbet** [GTNewHorizons/NewHorizons#4903]
Ewy's Workshop adds a Workshop Table similar in nature to the Forestry Workbench, but offering its own unique strengths. It can allow you to place furnaces or crafting tables into 4 slots in the workbench, allowing you to access all 4 of them from 1 interface. This has a lot of potential use in GregTech's tendency towards multi-step crafting, allows you to, say, begin laying out the crafting patterns for 3 different parts and the machine you are trying to build at the same time.

But thats not all, theres also several craftable upgrades to the table you can install. I'll give a basic overview of them each

-Storage : Adds a 6-slot storage slot under the crafting table interface. Can be added to every crafting table, for a total of 24 slots maximum. Allows the crafting table it was installed on to access the storage for its crafting operations.

-AutoCrafting : Relatively slow auto-crafting, pulling from the crafting table's storage. Can be sped up with up to 8 Speed Upgrades. Uses power which can come from Solid fuels, or with some new modules, Solar, RF, and Liquid Fuels. Modules are available for better automatic transfer into the table

-Various Other Upgrades : Speed, Fuel efficency, Transfer filters, the rest is about what you might expect.

A big Pro towards this mod I can see is the ease of gating. For example, if you dont want played autocrafting early game, change the recipe of that module. If you want to let players autocraft but make it slow, gate the  Speed upgrades recipe.

Overall, a simple yet potentially very helpful and very easily gateable mod, seems like it would be a perfect for GTNH

**Comment by Ethryan** [comment]
Link to mod:
https://www.curseforge.com/minecraft/mc-mods/ewys-workshop
