### ISSUE TITLE
Printed Circuit Board (PCB) not craftable

### ISSUE THREAD

**Issue by golress** [GTNewHorizons/NewHorizons#4908]
#### Which modpack version are you using?
2.7.5
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Looked for Printed Circuit Board (PCB) from OpenComputers in NEI because it's required to craft a ME Upgrade from Extra Cells 2
#
#### What happened instead? (Attach screenshots if needed)
The Printed Circuit Board (PCB) doesn't show up in NEI
#
#### What do you suggest instead/what changes do you propose?
Make ME Upgrade craftable again by either changing the recipe or adding Printed Circuit Board (PCB) recipe again.

**Comment by repo-alt** [comment]
PCB is also used in some computronics recipes.

**Comment by repo-alt** [comment]
For Computronics I suggest to just add shapeless conversion from, say, Fiber-Reinforced Circuit Board to OC PCB, because Computronics devices are mostly just for fun. ME upgrades recipes should be probably moved to the core mod, and unified with other OC recipes.

**Comment by repo-alt** [comment]
See also https://github.com/GTNewHorizons/NewHorizons/pull/5027
