### ISSUE TITLE
Add switch to enable/disable dimensional exclusions for orefinder wand

### ISSUE THREAD

**Issue by MotDT** [GTNewHorizons/NewHorizons#4909]
#
2.0.75
#
Adding the possibility of detailed settings or by the method of exclusion dim. :)
#
`# If this is set to false, the OreFinder will only work in the Owerworld, Nether and Twilight Forest [default: false]
    B:"Enable Everywhere"=true`

**Comment by Dream-Master** [comment]
@richardhendrics

**Comment by richardhendricks** [comment]
I made the Seismic Prospector ore output much nicer. I don't think we want players to use a stick on the moon to search for ores.
