### ISSUE TITLE
Supreme pizza gloves

### ISSUE THREAD

**Issue by Zafaranec** [GTNewHorizons/NewHorizons#4910]
hello, I have problem with supreme pizza gloves, I get quest but don't see recipe, worst when i give them, moment when i put in baubles inventory, client log off from server with ticking entity error, I must open backup without this item in inventory, because can't login

#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
my own
#
#### What did you try to do, and what did you expect to happen?
equip him in Baubles inventory
#
#### What happened instead? (Attach screenshots if needed)
[logout of player](https://pastebin.com/TvHBcqZf)
#

**Comment by draknyte1** [comment]
Please report this to the GT++ issue tracker. 
https://github.com/alkcorp/GTplusplus/wiki/Github-Issue-Format

**Comment by draknyte1** [comment]
Do not post it at the bottom of a closed existing ticket that IS NOT related. Please try again.

**Comment by Zafaranec** [comment]
sorry and thanks for support, and have another question, I can't see recipe, quest but not recipe, is there some unlock or...?

**Comment by draknyte1** [comment]
A recipe has never been added, only suggested.

**Comment by Zafaranec** [comment]
but why is quest for them, that suggest way to craft, is there actually way to get him(without cheat)?

**Comment by richardhendricks** [comment]
I'm pretty sure I wouldn't have added the quest if they weren't craftable?

**Comment by Zafaranec** [comment]
maybe unlock via thaumcraft research, this recipe don't show before that, if not you are opposing :)

**Comment by draknyte1** [comment]
> I'm pretty sure I wouldn't have added the quest if they weren't craftable?

But you did though :p
https://github.com/alkcorp/GTplusplus/issues/484

**Comment by richardhendricks** [comment]
Quest will be hidden until the recipe is available
