### ISSUE TITLE
Quality of Life Improvements to Tungsten Smelting (Not an overhaul)

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4911]
After hearing constant complaints on the GTNH Discord and players from Zeta test server, I devised a QoL improvement to tackle this constant complaint on nearly everyone's minds that heavily dislike the time gate involved.

Currently, the process goes as follows:
Tungsten (No Gas): 600 seconds at 1920 EU/t at a Heat Capacity of 3000K, or Nichrome Coils
Tungsten (1000L Nitrogen Gas): 500 seconds at 1920 EU/t. Same requirements

Hot Tungsten: 27.45 seconds at 1920 EU/t

How do you normally overclock, though? How can I reduce the time constraint required? Well, if you increase the voltage to IV along with Nichrome Coils, you will receive 300 to 250 seconds at that tier. However, in order to losslessly overclock, you must obtain Tungsten Steel Coils and IV voltage in order to get a coil reduction that results in the new following results:
Tungsten (No Gas): 150 seconds at 6931 EU/t. Tungsten Steel Coils
Tungsten (1000: Nitrogen Gas): 125 seconds at 6931 EU/t. Tungsten Steel Coils

This results in an EXTREMELY long waiting game when trying to progress further. Not to mention that one of the Tungstate resources are abysmal. In this case, Moonstone has the worst Tungstate resource by far with 2.50% to obtain a tiny pile of Tungstate dust at 20 seconds at LV and is extremely laughable at best. Why it was changed from Tiny Tungsten to Tiny Tungstate with NO compensating buffs whatsoever is beyond me. Tungsten is also used quite heavily when progressing into the later tiers and trying to progress from EV to IV with bare minimum amounts of tungstate is aggravating and extremely frustrating

Now, onto the actual QoL buffs.
-Adjust the Moonstone recipe: Increase the chance from 2.50% to 10% ` Previously was 6.50%`. Math:
`0.10 chance of Tungstate x 3600 sec in an hour / 5 the processing time at an HV centrifuge for Moonstone / 9 packaging 9 tiny's into 1 whole dust = 8 Tungstate an hour`

-Reduce the overall voltage requirement of Tungsten Smelting from EV voltage input to HV voltage input.
**OR**
-Reduce the overall time requirement of Tungsten Smelting from 600-500 seconds (No Gas & Gas recipes) to 300-250 seconds at EV voltage input.
**OR**
-Reduce the overall time and increase the voltage requirement of Tungsten Smelting from 600-500 seconds (No Gas & Gas recipes) to 150-125 seconds at **IV** voltage input.

-Remove the Nitrogen gas input and replace it with 2000L of Argon. Reduce the time from 500 seconds down to 350 seconds.

What does this overall QoL improvement do in terms of late-game and overclocking? Lossless overclocks are not touched and are the same. If you overclock with the new buffs, you will get 300 seconds at EV with no gas and 175 with gas. This vastly improves the overall heavy use of "tedium" involved with the current recipes that no one generally enjoys.

Counter Arguments:
-**This removes the stress test and difficulty of how much you can generate EU in your tier**
While this is something that I considered and went over multiple times in my thoughts, barely anyone really desired this concept being shoved down their throats multiple times during the EV age. Talk to the Zeta people or even the people on the GTNH Discord and you will know what's up.
-**Tungsten in real life takes a lot longer, why is it being reduced here? Are you saying that we remove the realistic process of Tungsten smelting?**
Again, this is something I went over multiple times in my thoughts. However, due to the varying usage and requirements that are in GTNH, Tungsten smelting is the **least** enjoyable process to most. This proposal tackles that issue by allowing users to overclock 1 extra time if they wish to go up to EV AND even keeps the time difference. Remember, it doesn't always need to be "tiered" to fit the "difficulty." In fact, this even enforces the notion of difficulty by constantly upgrading to reduce the overall time consumption in a fair manner. As well as the Argon process. While 2000L of Argon might not be much in terms of quantity, it will begin to progressively add up. The faster you want it, the more you are going to consume. If you are relying on an old Argon setup, then this kind of process enforces better production for smooth smelting. In turn, this enforces the notion of difficulty to a fun degree.

Overall, this process will help benefit the enjoyability and still enforce difficulty in a creative way.

**Comment by boubou19** [comment]
wasn't tungstate here to blocks tierskip pre 2.0?

**Comment by ScriptedPiky** [comment]
Ohhh that's a good point seeing as Moonstone technically doesn't require EV.
I came up with some math and determined that, if you were to centrifuge Moonstone at HV voltage input (time is overclocked down to 5 seconds per recipe)and never go beyond to EV to try and tier skip, you will get roughly 26 pure whole Tungsten dust per hour. Soooo maybe I'll go back and change it to Tungstate dust if that's the case.

-Updated the post: Replaced pure Tungsten from Moonstone and replaced it with Tungstate, buffed the chance significantly; chance from 6.50% to 18%, Tungsten to Tungstate.
-New output potential: 72 whole piles of Tungstate per hour (assuming PERFECT 20.00 TPS)

**Comment by CalterOK** [comment]
I do not see any difficulties in getting tungsten. With 1 core, when using a multi-block miner, approximately 3k-4k tungsten is obtained. As for melting using blast furnaces from gt ++ or a mega stove, this does not cause problems. If now you are having such problems melting tungsten, what will happen to you in the future?

**Comment by boubou19** [comment]
@CalterOK are you sure you have everything you described at hv?

**Comment by CalterOK** [comment]
we are talking about ev, and 4 conventional furnaces up to luv were enough for me.

**Comment by 0lafe** [comment]
Except it's an IV material, why would it use HV? It makes you have some level of power gen, but I've found it to be perfectly ok with the usage of tungsten. Reducing the time/power isn't a great idea, when the overall EV/early IV power usage is already fairly low compared to your gen options. 

If you're gonna buff moonstone, don't do pure W. Looking at a tungstate change in proc, this would skip that. 5% tungstate sure, but not tungsten. 

>trying to progress from EV to IV with bare minimum amounts of tungstate is aggravating and extremely frustrating

Except there's tungsten ores on T2 so it's not. You really just need enough tungsten from moonstone to get the rocket, which uses like 1 fucking ingot lmao. 

Argon is fine, but why 2B? Also why does it need to change the time? Argon is a late HV/early EV thing in terms of crafting. Throwing it in a mid EV unlock recipe, with most usage being in IV, seems like it fits. 

>While this is something that I considered and went over multiple times in my thoughts, barely anyone really desired this concept being shoved down their throats multiple times during the EV age. Talk to the Zeta people or even the people on the GTNH Discord and you will know what's up.

"Conceptually I can't be mad at it, but I won't make more power"? You have a ton of options in EV for making lots and lots of power. If you choose none of them and don't progress, I'm very unsure why you should still be able to progress easily. Increasing infrastructure and things required of you is part of the pack progression. Current tungsten is inline with that progression for EV, while this makes tungsten mostly HV again. If you can't produce the power for this, that's not really a fault of the tungsten recipe.
