### ISSUE TITLE
Pneumatic singularity recipe broken

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4912]
#### Which modpack version are you using?
Eta-live version
#
#### If in multiplayer; On which server does this happen? 
Eta-live
#
#### What did you try to do, and what did you expect to happen?
Looking at pneumatic singularity recipe =D
#
#### What happened instead? (Attach screenshots if needed)
There is broken singularity item in recipe, named as screen sayed and had no recipe.
![2019-08-08_16 52 06](https://user-images.githubusercontent.com/25028786/62708861-e5cfaa80-b9fc-11e9-842c-c05db7acdc21.png)

#
#### What do you suggest instead/what changes do you propose?
Replace it with working singularity =D

If i remember correctly, there was phosphor singularity with something like ~10k items in recipe. Better to check in older versions if they are available

**Comment by boubou19** [comment]
maybe related to #4215
