### ISSUE TITLE
Ichorium Block can be made without Infusion

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4913]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What happened instead? (Attach screenshots if needed)
Ichorium Block can be made without Infusion by using Fluid Extractor(or ABS) and Fluid Solidifier.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
I think the Fluid Solidifier's Ichorium Block recipe should be removed.

**Comment by CalterOK** [comment]
If you compare the receipt of the ichor block via infusion or hardener, then the recipes are for the most part equivalent in materials, and give a choice of how to make them. Since the hardener requires 9 ingots instead of 2.

**Comment by yukieiji** [comment]
When making Ichorium Blocks by Infusion, research is necessary to check recipe, Essentia is required for making, and it's also instability, so the difficulty seems to be higher.
And since it's no compressor recipe, Ichorium Block should not be created by machines.

**Comment by 0lafe** [comment]
Also keeps it gated to BM if you need to do the infusion
