### ISSUE TITLE
Tungsten Processing Overhaul

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/NewHorizons#4914]
(basically #4911 but cooler)

Currently, tungsten smelting is excessively long while tungstate and scheelite processing is extremely simple compared to reality. This suggestion is to reduce tungsten smelting significantly (perhaps to 150s EV/120s with nitrogen) but to add a fully realistic refining process to get tungsten dust from ores.

First, change the name and formula of the tungsten ore compounds to be more correct.
-Change the formula of Scheelite to CaWO4
-Change the name of "tungstate" to Wolframite, and change its formula to (Fe,Mn)WO4

Now, for the process itself:

1. For Scheelite: 7 Scheelite Dust + 4000l Na2CO3 solution => 4000l or 4 dusts Sodium Tungstate (Na2WO4) + 1 Calcium dust as byproduct
For Wolframite: 7 Wolframite Dust + 4000l NaOH solution => 4000l or 4 dusts Sodium Tungstate (Na2WO4) + 1 small Iron and 1 small Manganese dust as byproducts

Both these recipes in the autoclave. If possible, the Sodium Tungstate should be a solution but a dust is ok if the autoclave can't output fluid. If a dust is needed, add 1000l Water to the input of the next recipe

2. 1000l Sodium Tungstate + 1x Ion-exchange Resin Beads (Cl) => 1x Ion-exchange Resin Beads (WO4) +2x Salt Dust

This recipe goes in the chemical reactor. The 2 salt dusts contain 1 sodium and 1000l Chlorine, so sodium is not lost by the process.

3. 1x Ion-exchange Resin Beads (WO4) + 2000l NH4Cl => 1000l Ammonium Isopolytungstate solution (formula (NH4)2WO4) + 1x Ion-exchange Resin Beads (Cl) (90% chance)

This recipe also in the chemical reactor. The Ion-exchange Resin Beads should be reusable by this process but slowly be lost over time. The 90% chance leads to a loss of 400l chlorine and 102.4l polystyrene per tungsten dust. The 2000l NH4Cl should contain 1000l chlorine.

4. 1000l Ammonium Isopolytungstate Solution => Ammonium Paratungstate Dust (formula ((NH4)10(H2W12O42)·4H2O))

This is a drying recipe and should go in the GT++ dehydrator.

5. Ammonium Paratungstate Dust => Tungsten Trioxide Dust (WO3)

This is a heating recipe, and should probably go in a vanilla furnace. It could go in the EBF, but using the blast furnace twice to get your tungsten seems kind of silly, and most people will not want to build a processing chain with a dedicated EBF so it might add a manual element. It could also go in the pyrolyse oven, but that is even more annoying than the ebf.

6. 4x Tungsten Trioxide Dust + 3000l H2 => 1x Tungsten Dust + 3000l Water

This can go in the electrolyzer.

Other needed chemical processes:

16x Polystyrene Rounds + 1000l H2SO4 + 1x NaOH dust => 1x Ion-Exchange Resin Beads (empty)
This recipe goes in the chem reactor. This recipe is for the production of Sodium Polystyrene Sulfonate, one type of ion-exchange resin. If this recipe is used, the "Ion-Exchange Resin Beads" should probably be instead called "SPS Beads." However, these may not be the proper resin to use, as Wikipedia says that SPS is acidic, while for anion exchange (what we are doing), weakly or strongly basic resins are used instead. So some other fluids instead of H2SO4 might need to be used (such as a carboxylic acid? I am not an expert on resins). These beads should be the "chipped gem" texture, with a yellowish tint.

Ion-Exchange Resin Beads (empty) +1000l Cl2 => Ion-Exchange Resin Beads (Cl)
Short chem reactor recipe to add the initial chlorine to the beads.

NaOH + H2O  => 1000l NaOH Solution
Na2CO3 + H2O =>1000l Na2CO3 Solution

Short mixer recipes (also add to LCR) to produce solution versions of sodium hydroxide and sodium carbonate. We also need a way to obtain ammonium chloride if GT++ does not already have it.

All of these recipes (autoclave, chem reactor, mixer) should be at HV and not too long, perhaps 10-15s for most of them. The intent is not to make tungsten a time sink but rather an interesting chemical process.

Please comment with feedback, especially if there are messed-up ratios causing a dupe somewhere.

Credit to EmeraldsEmerald for much of the work figuring out what the proper chemical processes are.

**Comment by draknyte1** [comment]
Changing materials that exist is bad.

**Comment by Methes** [comment]
Please summarize inputs needed and outputs produced to get 1 tungsten dust.

**Comment by sthegreat** [comment]
On average, you input: 
-7 scheelite/wolframite
-400l chlorine
-104.6L polystyrene (ethylene+benzene+O2), 400l H2SO4 and .4 NaOH (if the SPS resin is used), -3000l hydrogen for electrolysis
-4 of the processes needed to produce a NaOH or Na2CO3 dust from a Na dust. For NaOH this is just adding water, but as it turns out we have no recipe for sodium carbonate. A simple recipe should be added such as 1 sodium hydroxide + 1000 CO2 => 1 sodium carbonate. None of the sodium itself should be lost in this part of the process if I made it correctly; it should all be returned as salt.
-Ingredients to produce 8000l NH4Cl from 4000Cl. GT++ adds a recipe for a pure ammonium fluid (lol) which is 1000l ammonia + 1000 hydrogen = 2000 ammonium. It seems no ammonium chloride exists right now either, so we could add another recipe: 1000l ammonium + 1000l chlorine => 2000L ammonium chloride; that would make this part of the cost 2000l ammonia and 2000l hydrogen. We could also add a more realistic recipe, which would be 1000l NH3 + 1000l HCl => 2000l ammonium chloride; with this recipe the cost for a tungstate is 4000 ammonia and 4000l hydrogen.

Thinking about it, that's probably an excessive amount of ammonia. If the ammonium isopolytungstate dehydration recipe gave back 500 or 750 ammonia it would reduce the ammonia consumption by 2x or 4x which may be more reasonable. This is fairly realistic also as I believe some ammonia is evaporated in that step.

The chlorine, polystyrene, sulfuric acid, and sodium hydroxide use could be reduced if we increase the chance to get back the resin catalyst, increasing to 95% from 90% would cut the consumption of those chemicals in half.

As outputs we get:
-1 tungsten dust
-1 calcium if scheelite is used
-.25 manganese and .25 iron if wolframite is used
-Some random water

**Comment by CalterOK** [comment]
@sthegreat Where did these reaction equations come from?
The decomposition of wolframite concentrate is carried out by sintering it with soda at a temperature of 800-900 ºС in rotary kilns.
And the equations there are as follows:
2FeWO4 + 2Na2CO3 + 0,5O2 = 2Na2WO4 + Fe2O3 + 2CO2
3MnWO4 + 3Na2CO3 + 0,5O2 = 3Na2WO4 + Mn3O4 + 3CO2. 

Scheelit agrees that it is processed in an autoclave, but the equation there is as follows:
2CaWO4(d) + 2Na2CO3(f) = 2Na2WO4(f) + 2CаO(d) + 2CO2
(d) - dust
(f) - fluid
How is it better for me to implement this particular reaction:
Rich tungsten concentrates (65-70 WO3) are also decomposed with sodium hydroxide solution.
MeWO4 + 2NaOH ⇄ Na2WO4 + Me(OH)2, 
Ме – Fe, Mn
Precipitation of CaWO4 (“artificial scheelite”) is the most common method for the initial separation of tungsten from sodium tungstate solutions. The low solubility of CaWO4, decreasing with increasing temperature, subject to certain conditions, provides a fairly complete transition of tungsten to the precipitate.
Precipitation is usually carried out with calcium chloride, an aqueous solution of which is poured into a solution of sodium tungstate:
Na2WO4 + CaCl2 = CaWO4↓ + 2NаСl.
Subsequent decomposition of CaWO4 with hot hydrochloric acid makes it possible to obtain yellow tungsten acid:
CaWO4 + 2НСl = H2WO4↓ + CaCl2
Tungsten trioxide is obtained by thermal decomposition of tungsten acid.
H2WO4=WO3+H2O
The restoration of tungsten with hydrogen occurs in several stages (can be combined in one):
WO3+0,1 H2= W2,9+0,1Н2O
WО2,9+0,18H2 = WО2,72+0,18Н2О
WO2,72 + 0,72Н2= WO2 + 0,72H2
WO2+2H2=W+2H2O

**Comment by CalterOK** [comment]
Corresponding if you make the chain for producing tungsten more approximate to the reality of the methods (in automated conditions) then it will look like this:

1. In a chemical reactor we get sodium tungstate
FeWO4 + 2NaOH ⇄ Na2WO4 + Fe(OH)2
2. In a chemical reactor from sodium tungstate we get scheelite
Na2WO4 + CaCl2 = CaWO4 ↓ + 2NаСl. 
3. In a chemical reactor we get tungsten acid from scheelite
CaWO4 + 2НСl = H2WO4 ↓ + CaCl2 
4. Restoring tungsten from tungsten acid with hydrogen
WO3 + 3H2 = W + 3Н2O

**Comment by sthegreat** [comment]
@CalterOK The chemical processes come from the book Tungsten: Properties, Chemistry, Technology of the Element, Alloys, and Chemical Compounds by Erik Lassner, Wolf-Dieter Schubert ([pdf](http://93.174.95.29/main/124000/63e8c05b3b593425133d0591d19a0414/Erik%20Lassner%2C%20Wolf-Dieter%20Schubert%20-%20Tungsten_%20Properties%2C%20Chemistry%2C%20Technology%20of%20the%20Element%2C%20Alloys%2C%20and%20Chemical%20Compounds-Springer%20%281999%29.pdf))

In the book, your process is described as the classical process while the process suggested is the modern process, chosen for its better energy efficiency, labor efficiency, and output purity. Discussion of the classical vs modern process is on section 5.2.1 pp. 184, and discussion of the resin-based ion exchange process (people on discord felt it was more interesting than the alternative solvent-based extraction process) is on pp. 200-202.

The resins actually used in the book are the Chinese anion exchange resins numbered 930, 931, 934, and 937, however, I was unable to find out what those resins were.

**Comment by draknyte1** [comment]
Realism != fun. 
GT takes shortcuts for the sake of gameplay enjoyability all over the board.
Keep that in mind, because people won’t take the alternative just for the sake of boring, tedious realism.

**Comment by CalterOK** [comment]
@sthegreat My first question was asked because of the formulas, since they are very different from the original, respectively, and were interested on the basis of what they were made in this form?
From what I was able to find out about the resins at the base, it was a polystyrene-divinylbenzene sulfonated macroporous copolymer, but I could not find the exact formula.

**Comment by CalterOK** [comment]
@draknyte1 the classic way is much simpler than using resins and ion exchange

**Comment by 0lafe** [comment]
I'd agree that realism shouldn't be forced for realism. Things solely being done for the sake of realism could be detrimental to the gameplay. However, when the gameplay idea is to add a more lengthy W proc chain, and the real life one is super interesting and better than what we have, why not use it? 

If single use chems are that bad, there's other ways to do this, but if you can follow the real chem chain for less "bloat" than orichalcum alone provides, then why not do it? 

As someone in early IV right now, I feel pressured to make some level of Ti proc setup, as rutile does take a little work, and I need tons of it. However, tungsten is really boring atm, and we have much more of it than titanium. Changing proc chains isn't just about realism, it's about the fun of more in depth GT setups.

**Comment by EmeraldsEmerald** [comment]
@CalterOK I'll answer in lieu of st, as I helped out with the formulas themselves.

>My first question was asked because of the formulas, since they are very different from the original, respectively, and were interested on the basis of what they were made in this form?

Two PDFs, one of which was attached by st and one of which can be found [here](https://www.bgs.ac.uk/downloads/start.cfm?id=1981). That second one has all of the reactions on pages 9-10.
As st already said, your way is the "classical" option. As for where OUR formulas came from?

- The Autoclave Recipes: You are correct in saying that the Scheelite requires an autoclave, while soda kilns are used for Wolframite. Why autoclave for both? Because of that other PDF I linked saying wolframite is treated with NaOH. Another autoclave works as well as another machine replacing a rotary kiln would for in-game purposes. Furthermore, the Solutions were used because the autoclave only has ONE item input.

- Recipes with Ion-Exchange Resin Bead included: Taken practically straight from the Tungsten PDF st posted. The only unrealistic part is not including NH4OH in the second step.

- Dehydration into Paratungstate: Yeah, literally taken from st's PDF as well. The same can go for the Tungsten Trioxide and Pure Tungsten Recipes.

> From what I was able to find out about the resins at the base, it was a polystyrene-divinylbenzene sulfonated macroporous copolymer, but I could not find the exact formula.

Yeah, this resin point. A sulfonated Polystyrene copolymer. No divinylbenzene was added, correct. Sulfonation occurs... technically through SO3 irl, but it can also occur through H2SO4, leaving the Sulfonated Polystyrene and Water. Afterwards, NaOH is added to turn it into Sodium Polystyrene Sulfonate.  
Furthermore, the beads carry Chlorine! This is outlined in the Tungsten Book, where _R_ stands for _Resin_. This goes for both reactions.

If I wrote not answering your questions or not clear enough or whatever pong me, thanks

**Comment by draknyte1** [comment]
> Two PDFs

Really, the depth that wikipedia has for most topics is the level of depth you want for playability reasons. Technical papers and implementations of things are usually too complex to implement properly, actually suck to do, or generaly just don't fit without adding 15 new machines.

**Comment by EmeraldsEmerald** [comment]
> Really, the depth that wikipedia has for most topics is the level of depth you want for playability reasons. 

Wikipedia's depth on tungsten's entry:
> Tungsten is extracted from its ores in several stages. The ore is eventually converted to tungsten(VI) oxide (WO3), which is heated with hydrogen or carbon to produce powdered tungsten.

There also exists a page on Ammonium Paratungstate, which states:
> Ammonium paratungstate is produced by separating tungsten from its ore. Once the ammonium paratungstate is prepared, it is heated to its decomposition temperature, 600 °C. Left over is WO3, tungsten(VI) oxide. From there, the oxide is heated in an atmosphere of hydrogen, reducing the tungsten to elemental powder, leaving behind water vapor. 

We've got a justification for APT to tungsten itself now.
As for APT's production?
>When concentrating an ammoniacal solution of tungstic acid (i.e. hydrous WO3), the product obtained is ammonium paratungstate.

Ammoniacal solution of Tungstic Acid. That's also got a wikipedia page! 
> Tungstic acid is obtained by the action of strong acids on solutions of alkali metallic tungstates. It may also be prepared from the reaction between hydrogen carbonate and sodium tungstate.

So there's the catch, huh. The Resin Bead step technically just replaces using up MORE Hydrogen Carbonate. 

And sodium tungstate?
> The predominant route to this salt is the extraction of tungsten ores, almost all of which are tungstates. Thus, the ores are treated with a base to give sodium tungstate, as illustrated in the case of wolframite:

>Fe/MnWO4 + 2 NaOH + 2 H2O → Na2WO4•2H2O + Fe/Mn(OH)2
>Scheelite is treated similarly using sodium carbonate.

This is also a point for @CalterOK - we're perfectly fine in terms of recipes, barring a hydroxide's production.

So now we've approached the point where literally the only change between our and wikipedia's route is the Resin Extraction - literally shown to be more efficient compared to the classical method, alongside adding a use to Polystyrene.

~~But this route is clearly suboptimal, so what do I know.~~

**Comment by CalterOK** [comment]
@EmeraldsEmerald I was confused by such moments:
> 1. Для шеелита: 7 шеелитовой пыли + 4000 л раствора Na2CO3 => 4000 л или 4 пыли вольфрамата натрия (Na2WO4) + 1 кальциевая пыль в качестве побочного продукта 
>    для вольфрама: 7 вольфрамитовой пыли + 4000 л раствора NaOH => 4000 л или 4 пыли вольфрамата натрия (Na2WO4) + 1 маленькая железная и 1 маленькая марганцевая пыль в качестве побочных продуктов

After all, correctly these reactions would look like this:
CaWO4+Na2CO3=Na2WO4+CaCO3
(1 Scheelite + 1 Sodium Carbonate = 1 Sodium Tungsten +1 Calcium Carbonate)

FeWO4+2NaOH= Na2WO4+Fe(OH)2
(1 Iron tungstate + 2 Sodium hydroxide = 1 Sodium tungstate + 1 Iron hydroxide)
MnWO4+2NaOH= Na2WO4+Mn(OH)2
(1 Manganese tungstate + 2 Sodium hydroxide = 1 Sodium tungstate + 1 Manganese hydroxide)

**Comment by sthegreat** [comment]
I did not suggest the proportions of that recipe to be fully realistic, but rather to retain the original ratios of 7 ore dust to 1 tungsten dust. It is true that the calcium should realistically be CaCO3 and the iron and manganese should be hydroxides.

**Comment by CalterOK** [comment]
@sthegreat I see no reason to leave the current coefficient, since we significantly extend the production of tungsten, which in turn will bring more of it. The current chemistry in Greg tries to keep the ratios indicated by me (of course, there are exceptions, but these are more likely errors).

**Comment by sthegreat** [comment]
Which ratios do you think should be used? Maybe 4:1 by removing the 7:4 ratio at the beginning but leaving the 4:1 at the end? I don't think scheelite/wolframite to tungsten dust should be 1:1 unless the ores lose their macerator bonus (currently they are 1 ore -> 8 crushed ore).

**Comment by CalterOK** [comment]
@sthegreat In my opinion it is better to change the bonus when crushing ore, since there are many ways where wolframite (lava, endstone) is obtained

**Comment by botn365** [comment]
i find @CalterOK process is the best its more comlex then thu rutile process but the one with Ion-Exchange Resin Beads is a bit to comlex to get tungsten 

> In my opinion it is better to change the bonus when crushing ore 1:2, since there are many ways where wolframite (lava, endstone) is obtained

mining should always be the best source of obtaing material and should not be nerfed becous there are alternatifs 

if tis is going to be changed the pure tungsten ore on europe should be moved to a T4 ot T5 planet becous it wil make tis process prety much usless (the tungsten veins on europe are equaly or even more commen then sheelite/tungstate veins)

**Comment by CalterOK** [comment]
If I take the processing chain that I proposed, it is clear that we make scheelite from tungsten. Accordingly, the processing of scheelite requires several stages less to obtain wolfram. Therefore, I propose to completely remove pure tungsten, and leave sheelite instead.

**Comment by 0lafe** [comment]
Considering the generation of ore and non ore tungstate/schelitite seems ok enough, it seems better to keep the limiter in the reaction here. However, we can also keep realism and keep the 1:1 but change how the veins/outputs work. Lower it from lava and stuff by 7x, then reduce the ores to only spawn as 3/4 type ores to limit the amount in a vein. By tungsten tier you're still gonna get more from properly processing those ores than from infinite gens, but youll also get overall much less.
