### ISSUE TITLE
Free machines on the surface of Ross128B

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4916]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Searched around Ross128B to explore

#
#### What happened instead? (Attach screenshots if needed)
Found machines in huts ranging from steam to IV in huts, more commonly EV and IV machines.

#
#### What do you suggest instead/what changes do you propose?
Remove machines in huts.

**Comment by AlexBucket** [comment]
@Dream-Master

**Comment by boubou19** [comment]
then you are lucky because on eta i found more steam and lv than ev and iv huts

**Comment by 0lafe** [comment]
I'd also agree that free IV machines in IV is too much. Reducing it to EV, or even HV is still something useful, but much less OP. A big part is the free tungsten cables that are in the huts too.

**Comment by AlexBucket** [comment]
> I'd also agree that free IV machines in IV is too much. Reducing it to EV, or even HV is still something useful, but much less OP. A big part is the free tungsten cables that are in the huts too.

EV or preferable HV would be ok, but free machines of the tier you reach the planet is just a bit over powered.

**Comment by AlexBucket** [comment]
> > I'd also agree that free IV machines in IV is too much. Reducing it to EV, or even HV is still something useful, but much less OP. A big part is the free tungsten cables that are in the huts too.
> 
> EV or preferable HV would be ok, but free machines of the tier you reach the planet is just a bit over powered.

Maybe even replace the machines in huts with small farms of mid - low tier IC2 crops outside with varying stats, or seedbags.

**Comment by EmeraldsEmerald** [comment]
Maybe replace the machines Hulls/Casings and (maybe) some Circuits? just as a sign of something going wrong with electricity or the overall setup?

**Comment by DoomSquirter** [comment]
So, obviously, I have zero issues with free stuff.  That's not what I wanted to comment to here tho.

If this was gt++ and alk made naked villagers that poop enriched naq every 5 minutes, and you all went nuts over the thing, you'd have to take this up with alk.  If alk said that it's their mod and it's the way they deemed it to be, that in alks vision of the mod, villagers poop enriched naq every 5 minutes and that they were not going to change anything, you'd have to take it up with them.  

Essentially, it becomes less of a pack issue and more of a mod issue.  if bart has his own github for issues, I'd take it up with him there.  If he's already said no tho, I think the point has been made that it's not going to change.

**Comment by AlexBucket** [comment]
Theres absolutely no need for free machines that are of the tier of the planet, or at all. Not in GTNH.

If he's not willing to change it then maybe the planet needs to be disabled.

**Comment by DoomSquirter** [comment]
I think the point tho is what does bart think.  If bart says it's fine, then by all accounts, it's fine.  

you posted your complaint, he replied.  that's literally the end of the discussion.  he did close the ticket.  I think he made his point pretty clear.  This is literally beating a dead horse at this point.

**Comment by AlexBucket** [comment]
> I think the point tho is what does bart think. If bart says it's fine, then by all accounts, it's fine.
> 
> you posted your complaint, he replied. that's literally the end of the discussion. he did close the ticket. I think he made his point pretty clear. This is literally beating a dead horse at this point.

Just because he created the mod, doesn't mean he is thinking in the best interest of the pack. It's poor form that he just closed the thread and won't take on any more infomation. It's broken, it needs to be fixed or the mod removed.

**Comment by DoomSquirter** [comment]
let's try to imagine that bart is staff and also that he is part of the core group that makes gtnh.  Let's also imagine that he is of german heritage, speaks german.  Now, imagine, dream speaks german, is german.  They could talk, if they wanted, in german, for hours on end and discuss whatever matters they wish, without translation.  

One might say he is in a position of some authority to make these kinds of decisions, no?

Now, commenting that something isn't to your liking.  there is absolutely nothing wrong about that.

Crying about how your comment was received, however.  That's really my point here.  Just cause you want a thing to happen does not mean it will happen.

welcome to the world all of us have been living in, when nerfs were thrown into the pack with hardly any overview or rfc.  See how we have felt in the past.  Is fun, no?

**Comment by richardhendricks** [comment]
I don't see it as an issue.  Getting to an IV planet already requires a lot of IV machines, no? And IV single-block machines are hardly game-breaking - by that point you're transitioning to multiblocks anyways right? 

I'd much rather have *interesting* planets than yet another Galaticraft bore-fest anyways.

His system for adding these machines is still a WIP, and I hope to have time to dig in and add my own additions, so it becomes more like a "gregtech rogue-like" with rooms/chambers/etc.

**Comment by 0lafe** [comment]
>I don't see it as an issue. Getting to an IV planet already requires a lot of IV machines, no? And IV single-block machines are hardly game-breaking - by that point you're transitioning to multiblocks anyways right?

Not really, only a handful of singles. You can get more than you've made for free extremely easily. Not to mention the cables are also kind of OP as you get your tier material for free in fairly large amounts. 

>I'd much rather have interesting planets than yet another Galaticraft bore-fest anyways.

Interesting sure, but that doesn't mean they have to give out free tier resources lol

>you posted your complaint, he replied. that's literally the end of the discussion. he did close the ticket. I think he made his point pretty clear. This is literally beating a dead horse at this point.

>If this was gt++ and alk made naked villagers that poop enriched naq every 5 minutes, and you all went nuts over the thing, you'd have to take this up with alk. If alk said that it's their mod and it's the way they deemed it to be, that in alks vision of the mod, villagers poop enriched naq every 5 minutes and that they were not going to change anything, you'd have to take it up with them.

Kind of different though. Only reason we abide by alk is because his mod isn't changeable. We can just fork barts mod for NH if we want. In no way is this a "we need to deal with it" situation. Judging by the responses, not many people really have a reason to keep it besides it's already there. If it's a poorly implemented feature, people have issues with it, and it's changeable, why would we want to keep it?

**Comment by richardhendricks** [comment]
> for free

I'd rather attack this aspect.  Like put in traps or dangerous boss monsters. @bartimaeusnek ?

**Comment by mitchej123** [comment]
Another cool mechanic would be if they're abandoned machines and a bit broken.. need one or two parts to make them operational again.

**Comment by richardhendricks** [comment]
That shouldn't be too hard to implement, just make a simple block that has to be combined with a GT part to return the working machine.  I like it.
