### ISSUE TITLE
Remove NotEnoughCodecs and MobiusCore

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#492]
It's just a decoding library, so we don't need it.

Openblocks, the only mod in our pack ever using it, stopped doing so after they got rid of the radio block:
https://github.com/OpenMods/NotEnoughCodecs/issues/3

Mobius core is redundant as well.

**Comment by deeplyarnab** [comment]
I would like to quote the author here
> NEC was never required for radio, it was just for MP3 streams
Sooo, we may need it for the issue #423

**Comment by Teteros** [comment]
That's unrelated, none of those mods in that issue use that lib.
OpenFM pulls
`mp3spi-1.9.5-1`
and `mp3spi-1.9.5-1` as dependencies.
