### ISSUE TITLE
Proposal: IC2 Drilling Fluid Cells

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/NewHorizons#4922]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server?
delta
#
#### What do you suggest instead/what changes do you propose?
Allow Drilling Fluid to be canned into IC2 Cells. Enables more Options for (cross-dimensional) transport and adds consistency to the IC2 fluid cell system.

**Comment by EmeraldsEmerald** [comment]
Also, the Ore Drilling multiblock quest requires the currently unobtainable cells. This would fix that issue.

**Comment by Anarack** [comment]
You know large fluid cells exist yes? Dim transicers exist and can handle liquids. This issue solves a already solved problem.

**Comment by boubou19** [comment]
moving fluid is not the issue: the implementation of the drilling fluid isn't finished. I guess that is what Aggadahr means.

**Comment by Aggadahr** [comment]
The Issue is 1) the lack of options when it comes to transportation (dim. transceiver can transport it but requires energy) 
and 2) the Inconsistency, every other fluid (as far as i know) can be transported in cells too

just because a solution exists in the form of a workaround, doesnt mean it shouldnt be solved

**Comment by observeroftime02** [comment]
![image](https://user-images.githubusercontent.com/43228249/62826931-a084b780-bb79-11e9-8897-9f47f2d2650a.png)

I don't get the problem? Drilling fluid can be transported in cells just fine.

**Comment by EmeraldsEmerald** [comment]
@observeroftime02 @Anarack Friendly reminder:

![image](https://user-images.githubusercontent.com/40524065/62826939-3691ff80-bbc5-11e9-9417-e327ee9c95d6.png)

No cells means no quest. No cells also means it ain't standardized, oh no

**Comment by observeroftime02** [comment]
The original proposal was: "Implement Cells containing Drilling Fluid"
As far as I can see, drilling fluid works just fine in every cell except for the IC2 Empty Cell. Converting those to Universal Fluid Cells makes it work as well.

**Comment by boubou19** [comment]
all the fluid containers that can hold the drilling fluid can't use the canning method to move fluids in item form and that's not consistant with other fluids.

**Comment by observeroftime02** [comment]
Yeah, it's not consistent in the way that the IC2 Cells don't accept it.

All I'm saying is that IC2 cells don't work at the moment, but any other option to transport the fluid does. So until this is made to work, there are plenty of options available that don't require power or any special procedures, which addresses the concern of the original post (cross-dimensional transport, transport in general)

Large fluid cells and canner? No problem. 
Universal fluid cells and canner? No problem. 
Large fluid cells and tanks? No problem. 
Universal fluid cells and tanks? No problem. 
IC2 fluid cells? That doesn't work right.

**Comment by Aggadahr** [comment]
I agree, will edit the proposal accordingly

**Comment by sthegreat** [comment]
Just want to mention that it looks like the cells used in the quest are universal fluid cells, which should be fillable fine.

**Comment by richardhendricks** [comment]
Will add a notice to the quest that these are universal fluid cells, not normal fluid cells.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/71500279-f062d300-2829-11ea-9475-2b68a9dcbac5.png)
