### ISSUE TITLE
Suggestion: Make MV superconductors craftable Late MV / Early HV

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/NewHorizons#4927]
#### Which modpack version are you using?
GT New Horizons
#

#### Suggested Changes
I am at late MV, ready to start thinking about changing my crafting wall to MV machines, and I see that MV superconductors are mostly doable with the resources I have. Except for one thing: It requires a Vacuum Freezer in order to craft the ingot. This gates MV superconductor wire to Late HV / Early EV at the earliest, and by this time you have moved on entirely from MV and will never craft this particular item. Additionally, lossless cable is the most important at MV and below, since each loss of 1 EU per amp is 3% of the total carried EU at LV and 0.8% at MV (higher becomes negligible). My suggestion is to allow MV superconductor base to simply be turned into the regular ingot in the blast furnace, reducing the 2500K requirement (needing kanthal, which also needs a vacuum freezer) to 1800K (or whatever random number for cupronickel coils) and 480 EU/t (double MV hatches minimum)
This will allow slightly heavier usage of MV power if desired, given that superconductor wire is already very resource-intensive.

**Comment by Shattered2909** [comment]
agree. needing a late HV machine for MV cables is silly

**Comment by KorGgenT** [comment]
I just noticed that the earliest way to get helium is from the end, so that might need to be changed as well to keep in in tier. nitrogen is another possible option for a relatively inert gas used for cooling.

**Comment by EmeraldsEmerald** [comment]
Helium is avalible from any kind of Refinery Gas. it's not a HIGH amount of output, but perfectly doable.

**Comment by Bluebine** [comment]
Seems fair to me. MV superconductors are already fairly expensive since you can only make THREE superconductors per pump. Since LV superconductors are available once you've got your EBF, I think it's fair for MV ones to unlock with the HV EBF. 
Helium is a HV material, so it would also need be changed. Nitrogen would make logical sense- maybe a larger amount of it, to compensate for how much cheaper it is than helium?

**Comment by observeroftime02** [comment]
Yeah, I'm for making it more available at the respective tier, but I got to ask, who uses such expensive cabling at MV tier? I much preferred to move fuel around instead, and have generators closer to the consumer than laying a significant amount of cables, especially early on. 

I do agree though, make it craftable at MV tier so people have a choice.
