### ISSUE TITLE
[Idea] LiteLoader Mods

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/NewHorizons#4929]
[LiteLoader](http://www.liteloader.com/) is a Modloader that supports .litemod [mods](http://www.liteloader.com/mods#version=1.7.10). The coremod can be used as an Forgemod in the mods-folder.

**Which Litemods are there?**

- [_Big Chat History_](https://hypixel.net/threads/modification-1-7-10-1-8-big-chat-history-100x-scrollback.314429/) - extends the ingame-chat form 100 to 10,000 lines
- [_Link Info_](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1294637-link-info-0-6-see-basic-info-about-webpages-and) - If you click on a link in the chat the mod will provide basic information about the website you are trying to open (the same screen where you are asked, if you really want to open this website)
![grafik](https://user-images.githubusercontent.com/35727266/62839652-02821180-bc8d-11e9-91a5-2786b1fb2c7a.png)
- [_Chat Bubbles_](https://www.planetminecraft.com/mod/chat-bubbles/) - adds speech-bubbles over the heads of the players when they write something in the chat
- [_Voxel Map_](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2261180-voxelmap-1-14-4-to-1-7-10-a-minimap-and-worldmap) - a better Journeymap
- [_MAtmos_](https://github.com/Sollace/MAtmos/wiki) - An atmospheric sound generator that will generate natural sounds depending on your surroundings (needs a [soundpack](https://github.com/Sollace/MAtmos/wiki/SoundPack:-MSI))

**Why should we use these mods?**

The first three mods are purely cosmetic, but in my opinion do enhance the playing experience.
VoxelMap does everything that journeyMap does while having some extras that realy come to shine when having a huge amount of active waypoints like being able to highlight a waypoint (it doesn't even have to be a waypoint, you can highlight every point on the map) and set different waypoint-icons. The information about maps/waypoints is stored in a folder in the mods-folder (-> easy to backup). In my opinion the ingame-config of VoxelMap is also way more simple and intuitive than the JourneyMap ingame-config.
The only huge drawback is that players who explored a lot most likely won't change their minimap and lose all their amp-information. I did this at an early point in the game and it was already a lot of work. There are different approaches to solve this, each with a different level of "enforcement":
1. Keep JourneyMap and don't include Voxelmap - This would change nothing.
2. Keep JourneyMap and don't include Voxelmap but inform people over the existence of this mod (for example via the questbook) - No problem for players who already advanced in their world but new people won't likely install a new mod without even knowing anything anout GTNH.
3. Keep JourneyMap, include VoxelMap but disable it by default and inform people over the existence of VoxelMap - same as above but new people don't have to install VoxelMap by themselves -> new peple/people who start over again are to at least give it a try.
4. Keep JourneyMap, include VoxelMap but disable JourneyMap by default and inform people about this - old people can easyly switch back - their old JourneyMap-files won't be deleted. New people are highly encouraged to use VoxelMap
5. Don't keep JourneyMap, include VoxelMap and inform people about this - old people can install JourneyMap again and their old JourneyMap-files won't be deleted. New people are highly encouraged to use VoxelMap (I won't recommend this)
6. Don't keep JourneyMap, include VoxelMap and don't inform people about this - don't do this

LiteLoader and its mods are compatible with the current version of GTNH (2.0.7.5) and are completly client-sided.

**Comment by CalterOK** [comment]
I myself have been using Voxelmap for a long time, its addition can be carried out individually and there are no problems. therefore, adding these mods to the assembly itself does not see the point

**Comment by glowredman** [comment]
I see your point and I definitley don't want to force anyone to switch the minimap. So if I would make decisions I would not include VoxelMap in the modpack but provide information (the same way a backup-mod is recommended in the questbook). I've got the feeling that most peolpe don't even know that VoxelMap exists but maybe they would prefer it so this solution would raise attention. 
The other mods tho I see no point in not adding them because the point of a modpack is that the users don't have to assemble the mods themselves.

**Comment by richardhendricks** [comment]
Write a quest and we can include it.

**Comment by glowredman** [comment]
Only about VoxelMap or also about MAtmos (I added this LiteMod in the last edit because I forgot it)?

**Comment by Methes** [comment]
Chat options are meh.
Journeymap works perfectly fine and adding whole new modloader and changing already existing map for a different one with very minor tweaks makes no sense really.
There's Dynamic Sorroundings for those wanting more sounds which is Forge compatible and works the same as MAtmos.

Changes you suggested make no sense community wise and are purely cosmetic with little benefit for general public.

Having a quest with optional clientside modifications could be a thing, or just make a page on the wiki regarding these options together with resource packs.

**Comment by glowredman** [comment]
So, I finished writing the wiki-entry (as suggested by @Methes ). I'll later ask a wiki-editor to look over it to make sure everything is correct and up to GTNH standarts. I've also edited the Backup-quest (1501) to redirect to the wiki page and the wiki in general. I did it like this because the page I created also contains a paragraph about backup-mods and it's sort-of the same topic.

wiki-page: https://gtnh.miraheze.org/wiki/Mods

quest:
```
{
      "questID": 1501,
      "name": "Backup your stuff...",
      "description": "Single player? Please install your preferred backup mod, or use the command line to backup your game. Not sure which to use? AromaBackup for 1.7.10 works pretty well.\n\nWhile you\u0027re at it, check out our wiki for a list of mods you could add aswell to further increase your playing experience. The wiki contains some really usefull information and beginners guides you shouldn\u0027t miss if you\u0027re new to the modpack.\n\nRemember though Journeymap and Thaumcraft Node Tracker information isn\u0027t included with AromaBackup, so you should backup your journeymap and tcnodetracker directories after exploration.",
      "isMain": false,
      "isSilent": false,
      "lockedProgress": false,
      "simultaneous": false,
      "globalParticipation": 0.0,
      "globalQuest": false,
      "globalShare": true,
      "autoClaim": false,
      "repeatTime": -1,
      "sounds": {
        "complete": "random.levelup",
        "update": "random.levelup"
      },
      "logic": "AND",
      "taskLogic": "AND",
      "icon": {
        "id": "adventurebackpack:blockCampFire",
        "Count": 1,
        "OreDict": "",
        "Damage": 0
      },
      "visibility": "UNLOCKED",
      "tasks": [
        {
          "taskID": "bq_standard:checkbox"
        }
      ],
      "rewards": [
        {
          "rewards": [
            {
              "id": "dreamcraft:item.CoinTechnician",
              "Count": 1,
              "OreDict": "",
              "Damage": 0
            }
          ],
          "rewardID": "bq_standard:item"
        },
        {
          "command": "/tellraw @p [\"\",{\"text\":\"Here you can find the wiki: [\"},{\"text\":\"mods page\",\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://gtnh.miraheze.org/wiki/Mods\"}},{\"text\":\"|\"},{\"text\":\"main page\",\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://gtnh.miraheze.org/wiki/Main_Page\"}},{\"text\":\"]\"}]",
          "hideCommand": true,
          "viaPlayer": false,
          "rewardID": "bq_standard:command"
        }
      ],
      "preRequisites": [
        1500
      ]
    },
```

**Comment by richardhendricks** [comment]
Added the description above to quest 1501.

![image](https://user-images.githubusercontent.com/1214811/71499713-6a458d00-2827-11ea-85a4-a70536da7e5d.png)
