### ISSUE TITLE
Pulsating Iron recipe cannot consume oxygen

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#493]
NEI displays there's two ways to manufacture EiO Pulsating Iron:
1) With oxygen -- output is a regular pulsating iron ingot.
2) Without oxygen  -- output is a hot pulsating iron ingot.

The EBF does not do 1), instead it skips directly to 2) regardless if oxygen is present.

Other EiO ingots seem to play nice with an EBF (w/ oxygen).

**Comment by Dream-Master** [comment]
Ok will change this in GT Code then.

**Comment by ProsperCraft** [comment]
Please close, this is tested working

**Comment by ProsperCraft** [comment]
Just kidding, this still isn't working, please re-open

**Comment by Dream-Master** [comment]
Will change the recipe.

**Comment by Dream-Master** [comment]
Fixed
