### ISSUE TITLE
Ztones Dungeon loot only items should be disabled in config

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/NewHorizons#4931]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
In the ztones config file
**tweaks {
    # Enables dungeon chest loot [default: true]
    B:enableChestGen=false
}**
    B:"Splat Axe"=**true**
    B:"Terrain Eater"=**true**
    B:"Diamond Zane"=**true**
dungeon loot only items are set not to spawn at all yet are still enabled as items

#### What do you suggest instead/what changes do you propose?
I propose changing the values from true to false to prevent registering a couple of items that serve no purpose.

**Comment by richardhendricks** [comment]
They could also be added as quest reward items or given recipes. 

However, looking at their details, I don't really see any compelling reason to add them .

**Comment by ljjmrlion** [comment]
They were disabled from spawning in #348

**Comment by observeroftime02** [comment]
They are generic tools that don't really perform any special task. If these were given as a reward, perhaps a rare enchant or something could make up for that. But I tend to agree, best to just disable them, less work for everyone involved.
