### ISSUE TITLE
nitrogen cells no longer needed for SCs; remove from LuV SC quest

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#4932]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Do quest #1711

#
#### What happened instead? (Attach screenshots if needed)

Quest asks for:

![image](https://user-images.githubusercontent.com/34566584/62912978-9f4bc880-bdcd-11e9-86eb-5c576e330c1f.png)

LuV SC requires the following for crafting:

![image](https://user-images.githubusercontent.com/34566584/62913024-d326ee00-bdcd-11e9-982a-d9aec750fe3b.png)

#
#### What do you suggest instead/what changes do you propose?
Remove the need for the nitrogen cells

**Comment by richardhendricks** [comment]
Was already done? Don't see it in the current 8.0 quests.
