### ISSUE TITLE
Only the first galacticraft schematic shows the scanner recipe

### ISSUE THREAD

**Issue by DbpGaming** [GTNewHorizons/NewHorizons#4933]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Find the use for a schematic in nei
#
#### What happened instead? (Attach screenshots if needed)
https://cdn.discordapp.com/attachments/568210714121207823/610962764755763220/2019-08-13_17-25-57.mp4

Only works for the first schematic (moon buggy)
#
#### What do you suggest instead/what changes do you propose?
Probably should work for any schematic, it only working on the first is a really easy point of confusion since the moon buggy isn't need for progression, so the player may just straight up ignore it

**Comment by bartimaeusnek** [comment]
fixed with: https://github.com/GTNewHorizons/GT5-Unofficial/commit/38e2e1512bb91c3535729250f828d8078c88a91d
