### ISSUE TITLE
Insalling Server

### ISSUE THREAD

**Issue by HansenJonas** [GTNewHorizons/NewHorizons#4935]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
On my own Server
#
#### What did you try to do, and what did you expect to happen?
I tried to install my own Server and to play with a few friends.
#
#### What happened instead? (Attach screenshots if needed)
On start, after a few minutes the windows just closes. (I got no Error message to make a screenshot)
#
#### What do you suggest instead/what changes do you propose?
I would like to know, what I am doing wrong.

**Comment by observeroftime02** [comment]
Have you got a log?

**Comment by bigbass1997** [comment]
Log file please, and did you try following these instructions? https://www.gtnewhorizons.com/wiki/m/41469370/page/Server_Setup

**Comment by bartimaeusnek** [comment]
@HansenJonas that means you have not set the EULA=true in the eula data.

**Comment by HansenJonas** [comment]
@bartimaeusnek thanks, the server started successfully.

But now I get another error Message, when I try to join the Server.

![Error](https://user-images.githubusercontent.com/47722640/63008176-615cac00-be82-11e9-95ac-fc9a4946824b.png)

**Comment by bigbass1997** [comment]
Are you sure the server and client are running the same version? If so, where did you download the server and client from?

**Comment by HansenJonas** [comment]
I used the newest Version for the Server, but i just saw, that there is a new Version of the modpack, im going to install that.
