### ISSUE TITLE
[Mod Suggestion] MagicalDecorations

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#4939]
#### Which modpack version are you using?
2.0.7.5

#
#### Links
Mod: https://www.curseforge.com/minecraft/mc-mods/magicaldecorations

#
#### What do you suggest instead/what changes do you propose?
There are many wonderful building materials in GTNH today. However, there are not so many building materials for magic.So I suggest adding this mod.

Although there are few additional elements, it will be possible to use a RunicMatrix that can change the size and rotation speed as a building material. In addition, magical light is added, expanding the choice of light sources.

**Comment by bartimaeusnek** [comment]
its ARR im against it.

**Comment by observeroftime02** [comment]
ARR meaning All Rights Reserved? 
That means modification and integration of it would be next to impossible, and as a matter of principle that's not alright.

**Comment by bigbass1997** [comment]
> However, there are not so many building materials for magic.So I suggest adding this mod.

According to the mod's description, this only adds 3 things:

> - a lantern block that comes in two varieties: Greatwood and Silverwood
> - a decorative version of the Runic Matrix

So I'm confused how this accomplishes what you want. This mod doesn't provide "building materials".

**Comment by yukieiji** [comment]
I'm sorry, I'm confused because I sometimes use the same "building materials" and "decoration materials".
