### ISSUE TITLE
EBF Titaniumtetrachloride to EV Discussion

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#4941]
Would you be comfortable with Titaniumtetrachloride's voltage tier going to EV BUUUUT the time is reduced by half to simulate the original voltage-time with an overclock?

Let's put the times together to find out the total time on the current live version (not including ore processing).
Electrolyzer, 39 Bauxite dust: 35.10 seconds at MV, 90 EU/t, 17.55 at HV, 380 EU/t; 2 Rutile dust. Chemical: 1 Rutile dust: 25 seconds at HV, 480 EU/t; 1000L Titaniumtetrachloride. EBF: 40 seconds HV, 480 EU/t; 1 hot Titanium ingot. Freezer: 7.20 seconds at HV, 480 EU/t; 1 Titanium ingot.
Simplified: 107.3 seconds, 89.75 with overclocked Electrolyzer. 87.3 with EV EBF change, 69.75 with EV EBF (1920 EU/t) change and overclocked Electrolyzer
Note: Because of the 2 extra Rutile dust from the Electrolyzer, this would mean that half of the time, your total processing will be technically reduced to 72.2 and 54.65. With EV EBF change, 52.2 and 34.65.

This would mean the running cost of all machines running on both the live version and the proposed change would be:
MV and HV Electro, live version: 1530 EU/t and 1800 EU/t
MV and HV Electro, proposed version: 2970 EU/t and 3240 EU/t. But the time is still practically the same at the tier due to it being reduced to 20 seconds from 40 seconds from the new change.

Thoughts? Yes, this does make it more annoying and increases running costs, but would it be practical and enjoyable? Considering 20 seconds at EV and 69.75 overall times with all the machines (not including ore processing), would it serve its purpose as a difficult and rather enjoyable process?

Summary: These changes will overall make the game a little more difficult as the energy required to progress to EV requires the tiered voltage. It will also give you a sense of what kind of power you will need in that tier; allowing the player to make adjustments and more infrastructure to their base before going forth into the **Extreme Voltage** age. Their first Titanium will also be more enjoyable and rewarding as the sense of progression & difficulty they have to overcome will be present.

**Comment by observeroftime02** [comment]
The processing cost would pretty much stay constant and there is not a significant change in the time to process. This means players in the later tiers would see one less overclock in practical terms. I'm just wondering what brought this on, as the TiCl4 process that is in the game is a tremendously enjoyable one at the moment. It's a great example of how ore processing can be done in a sensible matter, this would just push things back a tier. What is the necessity of this change? That's what I'm trying to understand. 

I'm not for it, I'm also not against it, I'm just trying to understand the thinking behind this. What problem does this change solve? Is the current TiCl4 process not appropriate for it's tier?

**Comment by ScriptedPiky** [comment]
That is a valid point and I can understand it. The original intention was from a "What if..." scenario where 0lafe claimed that the process isn't as difficult and I had thought of bringing that suggestion to meet the "difficulty" standard.

Although, now that you bring that up, I do see that it pushes things back a tier and that it offers no other real benefit other than being an artificial difficulty increase that would be incredibly frustrating as it also affects the later game as you said, with 1 less overclock overall. I realized this proposal  wouldn't serve the ideal game state other than more "difficulty."
Though I **do not** plan on this wanting to change to go in after realizing its lack of purpose, I do want to see your thoughts on **if** something like this would've been implemented. Would it be detrimental to the game and more of an annoyance than a difficulty curve?
