### ISSUE TITLE
Ross 128b relic items are OP and chunk generation duplication

### ISSUE THREAD

**Issue by Wegifan** [GTNewHorizons/NewHorizons#4944]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
private server

One can arrive at T3 planet Ross 128b in early IV. On Ross 128b you can find relics that generate Naquadah Reactor Mk II, but it can only be made after finishing a ZPM circuit production line with a huge amount of material and machine, meaning that IV tier electricity supply is much easier than before. There are mountains of IV tier machine that could be acquired through finding relics' treasure making it too OP in early IV. Only generate EV machines and IV components would be better.

Chunk generation seems duplicate, weird.
![1](https://user-images.githubusercontent.com/49618165/63216763-24880200-c16d-11e9-8a9d-5acbc9240102.png)

**Comment by Kiwi233** [comment]
You can find indium veins on Ross 128, which can only be made by fusion MK III or by a series of complex processes. I think this is too OP.

**Comment by AlexBucket** [comment]
Agreed.

**Comment by observeroftime02** [comment]
You do not find pure indium veins on Ross 128. There exists a very rare vein that spawns Roquesite as a sporadic ore which can be processed into Copper, Sulfur and Indium at a ratio of 4:1. The vein is so tiny that mining out a whole vein yields about 30 indium in total. It is also the rarest ore vein that spawns on this planet, with a weight of 3, about 26 times less common than the most frequently spawned veins. I do not consider this an issue due to the rarity, size and density of this vein. At the time when you have access to the planet and the tools you have available for locating such a vein, this seems perfectly reasonable. Have you actually tried to locate one, mine it and process it, or is this simply based on your gut feeling? IMHO it makes perfect sense to have a small and rare alternate source for indium by the time EV rolls around. 

I do agree that finding random Mk2 Nq gens is an issue though.

**Comment by Kiwi233** [comment]
@observeroftime02 Not 4:1, just 36:1

**Comment by observeroftime02** [comment]
![image](https://user-images.githubusercontent.com/43228249/63219036-3b533800-c11e-11e9-8abe-cdbd716029b9.png)

Huh? Where do you get 36:1 from?

**Comment by Kiwi233** [comment]
@observeroftime02  my fault, i mean use sphalerite and galena to make indium, 36:1.

**Comment by bartimaeusnek** [comment]
As i have stated mayn times:

1. the odds of getting an IV hut are **1:3072** chunks (best case without rivers/ocean biomes)
2. the odds of getting a nq generator are **1:12288** chunks (best case without rivers/ocean biomes)
3. the roquesite vein is rarer than any vein (weight of **3/300**) in the game and gives out ~20-40 Indium per vein.

Please, before you cry any rng based event/generation is op, at least do some serious, long term testing.

**Comment by 0lafe** [comment]
You do realise by putting IV machines on an IV planet, in an achievable manner with IV tech, you just encourage people flying around finding free stuff. Really fast ways to fly, and getting some naq gens, or even just a bunch of tungsten is kind of really worth it. You're really incentivising a really noninteresting mechanic, that will probably cause some tps issues with all the terrain gen, to get things that are normally meant to be difficult for your tier. The numbers are achievable for the machines, and really brings the question, why would you think it's a good idea to give free IV machines on an IV planet

**Comment by Anarack** [comment]
You are aware you can trivially change the planet tier and hut spawn chance by config correct? Go out and play with numbers before throwing away something as broken. That and tbh, any server population is going to be unhappy if someone is searching at this scale.

**Comment by 0lafe** [comment]
If it's that easy, I'll do it I guess. I think the point of these is more that the default shouldn't be IV, rather than the inclusion of being able to lower it is enough.

**Comment by observeroftime02** [comment]
I'm curious, is there a config option for the tiers of machines being found? Haven't looked yet.

**Comment by Wegifan** [comment]
> 2. the odds of getting a nq generator are **1:12288** chunks (best case without rivers/ocean biomes)

In terms of probability, it is true indeed, but you need to consider the time cost.
People can easily fly for 5*15 chunks in 20s and thus 1 hour for a nq generator and 3 IV machine. However, 8 ZPM circuits are hard to make, not to mention the production itself, just take a closer look at the raw material for nq gens and other IV tier machine will also make you crazy. The tungsten ingot, tungsten steel, etc. all need the energy to produce, mostly from a mox nuclear reactor, it takes time, a lot of.


> You are aware you can trivially change the planet tier and hut spawn chance by config correct? Go out and play with numbers before throwing away something as broken. That and tbh, any server population is going to be unhappy if someone is searching at this scale.

You can also cancel hardcore darkness by config. I think that talking about the default settings is much better, and I really don't know if there is this in the config, nobody will know in the beginning.
A large-scale searching does annoy to the server and other people who try to enjoy the game and low tps, but those achievers want to because it's the most convenient way to advance in IV for now. 

NH is a modpack based on GT tier progression. Any game mechanic that break this principle is worth discussing.

> Edit: The last issue about this got closed for the same reason, what makes you think another will change a thing?

My fault. I ignored it by mistake.

**Comment by mitchej123** [comment]
I'd be in favor of making them require some maintenance before they work; but it's an interesting story and a nice reason to explore beyond the usual grind.

**Comment by ljjmrlion** [comment]
@mitchej123 Maybe you find them as a block called "unidentified machinery" and bring them back and use a scanner to figure out what they are. like the RF tools dimlets. then they could have a table of possible machines and chances easily configurable

**Comment by 0lafe** [comment]
Maybe if the scanning/assembling eu is more than the proc power of the machine's parts normally, but otherwise I don't see this doing much with the whole free machine thing.

**Comment by ljjmrlion** [comment]
@olafe Yeah, that's true. Maybe a machine could be used to identify the machine then another to repair it? like if you find a broken HV assembler you could repair it in an assembly machine with something? I feel like this may be getting too convoluted.
