### ISSUE TITLE
some mob related problems

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#4946]
#### If in multiplayer; On which server does this happen? 
eta

there are a couple of bugs and issues that should be addressed about mobs

first is the easiest to deal with, the smolder blaze,when the player is killed by it the grave does not spawn and death message does  not appear, requires grave files to get stuff back

second is an uncommon bug, i do not know if it happens in SP but it happens on the servers, a completely invincible invisible mob spawns and cant be dealt with, relogging **sometimes** helps though, but its bad enough it should be addressed as its becoming increasingly common

lastly is the worst one, the tps killer, too many mobs spawn, especially if you're close to a rougelike dungeon, this causes too much lag, the spawnrate of mobs is too damn high it makes both players and server machine ragequit sometimes

**Comment by richardhendricks** [comment]
Any details on the invisible mob? What message do you get if it kills you?

**Comment by PoptartOverlord-Xabedo** [comment]
funny enough i only recently came back to the pack after a break, so as far as i remember... the mob is the usual infernal, perhaps a bug from the mod itself.

**Comment by PoptartOverlord-Xabedo** [comment]
though i would recommend to take quick action for the smoulder blaze, the black blaze, as  deleting the grave is....not that pleasant.

**Comment by richardhendricks** [comment]
I assume you mean Ember?  Smolder doesn't have any special effects.  It will be covered by the fix #5215.

**Comment by PoptartOverlord-Xabedo** [comment]
is it the black blaze? pretty sure they're smoulder 
let me try going on a suicide mission and i'll see what happens

**Comment by richardhendricks** [comment]
The invisible mob we'll look at under the Infernals ticket #3229

**Comment by richardhendricks** [comment]
Smolder just blinds you when it hits you.
![2020-01-26_10 31 16](https://user-images.githubusercontent.com/1214811/73138328-ff09f900-4026-11ea-92b8-6078d1ce7af1.png)

Ember is the one that used to prevent graves, but I have it fixed in my branch.

**Comment by richardhendricks** [comment]
Not sure what's a good way to prevent massive mob spawns next to a Roguelike, that's kind of the point.

**Comment by richardhendricks** [comment]
You can claim the chunks around the roguelike in the official servers to prevent spawns, or you can use a monster repellator or magnum torch. Another option is a Thaumcraft lantern, since it lights up a huge area, including underground.

**Comment by wlhlm** [comment]
> second is an uncommon bug, i do not know if it happens in SP but it happens on the servers, a completely invincible invisible mob spawns and cant be dealt with, relogging sometimes helps though, but its bad enough it should be addressed as its becoming increasingly common

This is a pretty vague description, If we assume that this means an Infernal mob with cloaking modifier, than this should be fixed with the changes in  GTNewHorizons/atomicstrykers-minecraft-mods#1 which make the cloaking modifier no longer permanent, but have a 2s cooldown.

**Comment by richardhendricks** [comment]
@wlhlm I am going to review your PR as soon as I get my head above water. :)  Thanks for your work.

**Comment by Dream-Master** [comment]
@richardhendricks oh ok I merged it. Let me know if I have to revert it. Thought it was a old pr and see the new changes after merge

**Comment by PoptartOverlord-Xabedo** [comment]
i apologise for its vagueness, as its a rare occurrence which i myself have only encountered twice and saw others complain about it, i hope it will be fixed by new cloaking  change.

**Comment by richardhendricks** [comment]
nah that's fine, we can just test it in Zetatest and see how it works out.
