### ISSUE TITLE
plutonium-imperial bee takes "internal server" crash

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#4947]
#### Which modpack version are you using?
2075
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
breed older plutonium bee with imperial. Resuling bee cant be hold in inv -> internal server crash
I dropped the bees before and the mixed I dropped too, that they could changed (Gendustry -> GT++ Bee)
#
#### What happened instead? (Attach screenshots if needed)
https://paste.myftb.de/ekifekoqam
#
#### What do you suggest instead/what changes do you propose?
no crash and right working bees

**Comment by bartimaeusnek** [comment]
the paste you attached is empty.

**Comment by bigbass1997** [comment]
The paste works fine for me, but being hastebin, I'm not surprised you're having problems loading it; plus it is really large. @Ngar1, please repost the log using https://gist.github.com/ instead.
