### ISSUE TITLE
crash in control menu like: #4623

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/NewHorizons#4950]
Which modpack version are you using?
2.0.7.5

What did you try to do, and what did you expect to happen?
I tried entering controls to change hotkeys.

What happened instead? (Attach screenshots if needed)
After scrolling down the game freezes and crashes.

What do you suggest instead/what changes do you propose?
I don't know enough about the pack to propose any changes, but I do know that I did not experience this problem with Twitch launcher's current GT NH version.

**Comment by mitchej123** [comment]
Please provide a crash log

**Comment by sethdark** [comment]
[crash-2019-08-22_19.25.29-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3531242/crash-2019-08-22_19.25.29-client.txt)

**Comment by mitchej123** [comment]
What language/keyboard layout are you using?

**Comment by sethdark** [comment]
AZERTY (Belgian Period)

**Comment by mitchej123** [comment]
It looks like an invalid keybind.  Check your options.txt for any custom keybinds (not set to 0 I think); or just remove the keybinds and let it go to default.

**Comment by sethdark** [comment]
worked! thank you!

**Comment by Dream-Master** [comment]
@sethdark if it worked please close the issue. Thanks
