### ISSUE TITLE
Infinity catalyst cooling

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#4952]
#### Which modpack version are you using?
Eta-live
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Trying to smelt some Infinity catalyst in my ebf and get some ingots =D
#
#### What happened instead? (Attach screenshots if needed)
U can smelt ICatalyst at UV with the best coils - it's ok. But... U can cool it at UEV only!
I guess it's just one excess zero symbol in recipe - cooling it at UV make sence.
![2019-08-23_14 13 31](https://user-images.githubusercontent.com/25028786/63588883-41c73100-c5b0-11e9-9b6e-3183bb761571.png)
![2019-08-23_14 13 40](https://user-images.githubusercontent.com/25028786/63588885-41c73100-c5b0-11e9-91ff-a23e972d672d.png)

Suggestion: remove this excess zero symbol.

**Comment by observeroftime02** [comment]
I've noticed something similar in the recipe for infinity ingots as well, and brought it up, I'm not sure if those are intentional. Seems overkill if so.
