### ISSUE TITLE
BQ: Novice Thaumaturge #798 and #237 new crafted wands are not being detected

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/NewHorizons#4955]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
epsi
#
#### What did you try to do, and what did you expect to happen?
One of the quests require Iron Capped Greatwood Wand, another
Gold Banded Greatwood Wand, when those are newly crafted the item contains no vis and simply shows the wands total vis capacity, disregard the wand type in the picture:
![wand](https://user-images.githubusercontent.com/23141859/63639067-30595400-c698-11e9-9652-58bf15e0e64d.png)
The actual wands that are being accepted by the book look like this:
![wand2](https://user-images.githubusercontent.com/23141859/63639093-6eef0e80-c698-11e9-9f70-05b4a1895c84.png)
Issue is that the newly crafted wand would have to be filled to contain all types of vis and then drained all to zero in order for the quest to actually accept it.
#
#### What do you suggest instead/what changes do you propose?
Change the wand damage value so the book will accept fresh wand, maybe both, not sure if that is possible. in case the player makes a mistake and fill it before actually completing the quest, provided the quest book did not auto-detect when it was first crafted.

EDIT: eg. Adept Thaumaturge # 877 works correctly and accepts fresh crafted scepter
![wand3](https://user-images.githubusercontent.com/23141859/63639348-b4144000-c69a-11e9-948e-b2d08f556d82.png)
 EDIT: just found this https://github.com/GTNewHorizons/NewHorizons/issues/4827 so one seems to be fixed and needs testing
Also # 237 is mentioned at the very end of it, but i don't know if that was looked at.

**Comment by richardhendricks** [comment]
Should be fixed now.

**Comment by Dream-Master** [comment]
we close this after release

**Comment by richardhendricks** [comment]
It's a duplicate issue, and is already fixed for the gold wand in the last release
