### ISSUE TITLE
Request to add this mod- Decocraft

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#496]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292016-decocraft-2-2-decorations-for-minecraft-halloween

This mod does not affect balance in any way, and provides a lot of flavor to minecraft.

**Comment by deeplyarnab** [comment]
I wanted to suggest this mod with "et futurum" mod, the only thing that'll be affected is the startup time of the game since it adds a tonne of new stuff.

**Comment by Dream-Master** [comment]
We vote against it.
