### ISSUE TITLE
Big Egg quest#1655 issue

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#4964]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Tried to complete that quest
![image](https://user-images.githubusercontent.com/37113583/63861263-3b232a00-c9b3-11e9-825e-eca1797763ce.png)

#
#### What happened instead? (Attach screenshots if needed)
But nothing happend
![image](https://user-images.githubusercontent.com/37113583/63861280-48401900-c9b3-11e9-9367-8b612dd9445c.png)
![image](https://user-images.githubusercontent.com/37113583/63861298-51c98100-c9b3-11e9-918f-1774b448ea46.png)
#
#### What do you suggest instead/what changes do you propose?
I quess it is volumetric flask

**Comment by richardhendricks** [comment]
Issue is the spawn egg, there is no way to make a generic one.  I have removed it from the requirements, and put in the text that the player can choose any spawn egg. They're purchaseable with coins, so it's not a big deal which one they use.
