### ISSUE TITLE
Quest is outdated by GT++

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#4966]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
That quest is outdated by GT++
![image](https://user-images.githubusercontent.com/37113583/63909942-6ea29a80-ca2d-11e9-9c42-3f80c46f3091.png)

#
#### What happened instead? (Attach screenshots if needed)
1,1-Dimethylhydrazin have new craft in that version of modpack
#

**Comment by Dream-Master** [comment]
fixed in dev
