### ISSUE TITLE
More planets addition

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/NewHorizons#4969]
#### What do you suggest instead/what changes do you propose?

Maybe you can add the More Planets mod (Galacticraft Addon) into GTNH? It's also have cool planets too offer. *+1 habitable planet). Just ignore the rockets since NASA Workbench is uncraftable. Some planets may have unique ores. (Anyway it's just an idea. Feel free to try if it fits the pack.)

**Comment by observeroftime02** [comment]
What exactly do those planets offer? Because ATM the GC planets are bland as can be, with no real difference except for the color of the rock blocks. Making any kind of base in space is also out of the question unless the planet has a breathable atmosphere, due to the way that GC handles space.

**Comment by Dream-Master** [comment]
Adding a new mod and remove gc isnt possible. We invest so much time to nerf and balancing all together but for 1.12 /13 /14 when we make GTNH 3.0 we can look at this mod.
