### ISSUE TITLE
Test Witching Gadgets and Gadomancy

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#497]
Gadomancy and witching gadgets made it into the test/unstable pack.
Witching gadgets requires Traveller's gear.  See https://github.com/GTNewHorizons/NewHorizons/issues/459.

Now to review and identify if any  incompatibility issues arise for next major update...

**Comment by Dream-Master** [comment]
Gadomancy added if anyone wants Witching Gadget we have to open a new Thread for it.
