### ISSUE TITLE
[RFC] Change LuV Machine Casing material

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4971]
With barts recent plans to change platinum group sludge processing to something else (giving Osmium, Palladium, Iridium, Rhodium) I think we should change the material for LUV machine casings to an alloy made from 3 Palladium and 1 Rhodium. That way we get rid of the stupid Chrome part and make Palladium a useful material in a lot of things, including the Fusion Reactor!

God bless Palladium!!

**Comment by observeroftime02** [comment]
Last I heard changing casing materials was not possible

**Comment by bartimaeusnek** [comment]
Possible, yes, mainting such a hughe change in this pack, abosulte nightmare, therefore practially impossible if not tested over a long term and with many patches.

**Comment by Dream-Master** [comment]
@bartimaeusnek @Shattered2909 we we not change chrome processing as well to make it tier appropriate ?

**Comment by Dream-Master** [comment]
It is fixed so far i see.
