### ISSUE TITLE
[RFC] Change Fine Wire Material for LUV Motors

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/NewHorizons#4973]
Yes yes, we have talked about it a lot. Now with Barts changes to Platinum Sludge processing, we have the idea of changing the Fine Wires in the LUV Motor from Osmiridium to something else. Osmium is one of the most rare materials at this stage and needing a large amount of it for the most basic part of machines (motors) is ridiculous. My idea is to change it to either Platinum or Iridium Fine Wires, dunno which yet, feel free to tell me! With Osmium being removed from simple LUV machine parts, I would recommend making it a material needed for LUV tier circuits aka Crystalprocessors. Maybe Osmium, maybe Osmiridium, dunno.

**Comment by 0lafe** [comment]
Rare yes, but you can get more than enough in the tier. Current chalco rates give you ~400 Os from a non boosted vein, 4x that if you bee/crop it up. Uu can also give you quite a bunch. Our IV power at the moment will uu us around an ingot every 40s or so. Asteroid stone is also fairly viable. 

It's certainty not something I'd say needs to be made easier. Giving LuV motors a reasonable cost is nice.

**Comment by Shattered2909** [comment]
With barts changes, getting Osmium from Chalco will be a lot harder. Osmium from Asteroid stone will probably be removed. Rememer: these changes are AFTER the plat sludge change.

**Comment by 0lafe** [comment]
Harder sure, but the production chain of it right now isn't the limiter. It come's down to the ratio of ore to osmium really, which from what I can tell hasn't been set yet. Lowering it from what it is now seems slightly weird compared to other options, as even if that's the case, UU would give you more than enough for even fusion.

**Comment by Dream-Master** [comment]
changed so far i see.

**Comment by Dream-Master** [comment]
@bartimaeusnek can this be set to fixed in dev ?
