### ISSUE TITLE
quantinium veins on venus are too dens

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#4978]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SSP
#
a quantiniumvein lookls like tis
![afbeelding](https://user-images.githubusercontent.com/42187820/64081672-718add00-cd04-11e9-9646-d5b70f070d27.png)
![afbeelding](https://user-images.githubusercontent.com/42187820/64081675-7b144500-cd04-11e9-96a8-51086ae41630.png)
tis is way too dens for what it should be

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/64376184-f7ba6280-d027-11e9-82d7-34d2522dbd07.png)
indeed this is to huge

**Comment by Dream-Master** [comment]
maybe misstype 33 instead of 3
