### ISSUE TITLE
Tungstensteel Ingot need 2k energy hatch, 2k energy hatch need Tungstensteel

### ISSUE THREAD

**Issue by goblintb** [GTNewHorizons/NewHorizons#4979]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
nope, local
#
#### What did you try to do, and what did you expect to happen?
going to 2k energy tier and stack, when going to Tungstensteel
#
#### What happened instead? (Attach screenshots if needed)
to create Tungstensteel Ingot i need 2k freezer. To make 2k freezer i need 2k energy hatch. 2k energy hatch made from Tungstensteel. How i will continue?
![1](https://user-images.githubusercontent.com/17138367/64190100-49bf8480-ce7e-11e9-9644-30827e9280b9.png)
![2](https://user-images.githubusercontent.com/17138367/64190101-49bf8480-ce7e-11e9-826a-918067139cf8.png)

#
#### What do you suggest instead/what changes do you propose?
any comments how to solve it?

**Comment by bigbass1997** [comment]
Use 2 HV Hatches

**Comment by goblintb** [comment]
sorry, i don'y know that freezer support unspecified amperate, thx
