### ISSUE TITLE
Remove MobiusCore

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#498]
remove moebius core

**Comment by Teteros** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/492

**Comment by ProsperCraft** [comment]
Re-Open- Mobeous Core still not deleted from the client.

**Comment by Teteros** [comment]
Yep, still in there as of 1.0.7.7g

**Comment by Dream-Master** [comment]
fixed in 1.0.7.7h.
