### ISSUE TITLE
[RFC] Rebalancing the EV Assembling Machine

### ISSUE THREAD

**Issue by thegooddoctor79** [GTNewHorizons/NewHorizons#4982]
Alright so I've been playing this pack for many many moons now. When thinking back, I recall times where fences and pistons were made in a way that at least made some sense, BBF had an actual purpose and didn't become obsolete in a hot minute and withers didn't spawn in your base after getting a little warp.

From the start the EV assembler was gated by titanium and needing EV voltage. It was great, happy days. Playable, you progressed much quicker.

Then the changes started coming. Not at once, slowly, drip by drip, little by little. Things began to add up.
The worst thing to happen to this pack was the so called Titanium ore "overhaul". Suddenly EVERYTHING became slow as molasses, needed a lot more crafting and resources. The EV assembler was pushed away out of reach for the common man.

For some reason even lower tier things get nerfed over and over, beaten like a dead horse, probably because once you nerf one thing too much, you get nervous and everything else suddenly seem too easy as well 

Or because some yahoo "helper" thinks of a cool new mechanic how to make something more "more interesting" and "fun", but fails to realize that it will impact just about every step you take, even at the lower tiers, or perhaps is willfully blind and has malicious intent at heart to begin with.

Take your first  assembler as an example. For many minecraft years, you had to save up rubber, make a few motors, circuits, cable and a whole ton of tin cables. Done. Now you have additional extra steps.

Your first time travelling to space and therefore first EV assembler is ALWAYS ripped away from you therefore immensely increasing the time before you get there.

I say move the EV assembler to HV tier as time wise it righteously fits the progression that has been here for the longest time.

**Comment by EmeraldsEmerald** [comment]
Seems very "sensible" and "well argued". +1 eyes emoji

**Comment by Dream-Master** [comment]
This not follow the GT logic.

**Comment by Methes** [comment]
"He was born in 1985"
"1985 is the year in which he was born"

Your input has zero value. Congratulations.

**Comment by Takafate** [comment]
The balancing of this pack has crushed, because those who made the changes to this pack do not actually play this pack. That's why they never understand things has been over nerfed. I still remember the days when GTNH self claimed to make "every recipe gregified", but today I don't say this pack follows the GT logic.

**Comment by AlexBucket** [comment]
> This not follow the GT logic.

What is the GT logic, @Dream-Master ?
