### ISSUE TITLE
Crashes when i try to change controls mp.v.2075 ,single,tried to change controls,it crashes

### ISSUE THREAD

**Issue by andkramorov** [GTNewHorizons/NewHorizons#4985]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by andkramorov** [comment]
version 2.0.7.5 ,newest asingle player or even in menu,i tried to change controls ,it crashed.(even if i haven't change something yet).I propose to fix it or just tell what sholud i do.there was a similar crash 17 days ago,but it dind't help me(because i can't understand what i did wrong)

**Comment by andkramorov** [comment]
[crash-2019-09-08_11.11.00-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3587286/crash-2019-09-08_11.11.00-client.txt)
[crash-2019-09-08_11.53.13-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3587287/crash-2019-09-08_11.53.13-client.txt)

**Comment by sthegreat** [comment]
This looks like it's caused by an invalid keybind. One of the keys something is bound to does not work well with minecraft. You can delete your options.txt file to regenerate all settings to their defaults, or you can edit the options.txt file, find where it is, and change it to something else.

**Comment by andkramorov** [comment]
i've understood,maybe.... one of the keys i've binded was 348.... as i remember thre is no number greater 255 in ascii... so i'l try to bin using options.txt and ascii table... thanks for answer

**Comment by draknyte1** [comment]
https://github.com/alkcorp/GTplusplus/issues/544
