### ISSUE TITLE
Removing mods from modpack for singleplayer

### ISSUE THREAD

**Issue by andkramorov** [GTNewHorizons/NewHorizons#4986]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by andkramorov** [comment]
Can i remove mod fro pack without crashing?
1) items from mod aren't used in other recipes
2)some items are used in crafting recipes
In which case i can remove mod from pack without possibiliti=y of facing crash or other issues?

**Comment by andkramorov** [comment]
I want to remove some mods that ,in my opinion,are cheating or are trash,or useless,for example,ender.io,bc for there pipes,openblocks,backpack, gt++ and other.If it's impossible,how i can easily prohibit crafting recipe as it's done in pack?

**Comment by Dream-Master** [comment]
goog luck. This will be very difficult.

**Comment by observeroftime02** [comment]
Use minetweaker to remove recipes. If that doesn't work, you're out of luck. Removing mods might actually break things in spectacular ways. Best of luck to you.
