### ISSUE TITLE
NEI acting strangely

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#4989]
#### Which modpack version are you using?
2.0.7.6-dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#

At first ive tried to access recipe in NEI by hovering over an item and pressing R key, that lead to force kick with "Internal server Error", but after couple kicks its working as it should, only you can't find anything by its name

![2019-09-08_21 36 44](https://user-images.githubusercontent.com/14223368/64493508-4a428b80-d281-11e9-9f08-760a02c045cb.png)
![2019-09-08_21 37 26](https://user-images.githubusercontent.com/14223368/64493509-4a428b80-d281-11e9-818d-a0e2e8fc3bd9.png)

**Comment by ScriptedPiky** [comment]
Happens as well if you put a single item in your crafting inventory. Also, the errors that it spams can go up to 64k lines where the same 60+ errors are spammed every millisecond https://pastebin.com/jdYAt1EW

**Comment by Dream-Master** [comment]
fixed in newer version
