### ISSUE TITLE
Can't change mode on multiblock

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#4991]
#### Which modpack version are you using?
2.0.7.6adev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Change the multiblock machine mode with screwdriver from ore wash to chem wash
#
#### What happened instead? (Attach screenshots if needed)
Internal server error and kicked out

**Comment by observeroftime02** [comment]
Remove all hatches from the multi before changing the mode. This is a known bug.

**Comment by mitchej123** [comment]
is there a gt++ issue for this?

Have a crash log?

**Comment by Hyperic88** [comment]
> Remove all hatches from the multi before changing the mode. This is a known bug.

well on .7.5 version it worked fine, no removing hatches needed...



> is there a gt++ issue for this?
> 
> Have a crash log?


[GregTech.log](https://github.com/GTNewHorizons/NewHorizons/files/3592789/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/3592790/latest.log
[fml-client-latest2.zip](https://github.com/GTNewHorizons/NewHorizons/files/3592793/fml-client-latest2.zip)

)

**Comment by mitchej123** [comment]
Zeta's running a new version of GT++ which means the possibility of new issues; make sure to report a detailed issue on the GT++ github.

**Comment by Hyperic88** [comment]
> Zeta's running a new version of GT++ which means the possibility of new issues; make sure to report a detailed issue on the GT++ github.

Currently onto it ;)

**Comment by draknyte1** [comment]
Just append it here: https://github.com/alkcorp/GTplusplus/issues/495

**Comment by Hyperic88** [comment]
> Just append it here: [alkcorp/GTplusplus#495](https://github.com/alkcorp/GTplusplus/issues/495)
> 
> > > Remove all hatches from the multi before changing the mode. This is a known bug.
> 
> > well on .7.5 version it worked fine, no removing hatches needed...
> 
> Been like this since 6.8 iirc.

Ive been switching modes on .7.5 without problem

**Comment by draknyte1** [comment]
> without problem
It's related to the Fluid Hatches, so you may very well have gotten away with it without issue. Doesn't change the fact it's a known issue we can work around. If the issue persists with the latest build of GT++ (Build 389), then I'll take another look.

**Comment by Hyperic88** [comment]
... If the issue persists with the latest build of GT++ (Build 389), then I'll take another look. 

it does, filled a ticket

**Comment by Dream-Master** [comment]
@draknyte1 yes I put 389 in the last zeta build.

**Comment by Dream-Master** [comment]
@Hyperic88 @draknyte1 
is this fixed ?
