### ISSUE TITLE
Oredict Rubberwood

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4992]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private Multiplayer
#
#### What did you try to do, and what did you expect to happen?
Rubberwood cant be used to create chests or be used for the charcoal pile igniter

#### What do you suggest instead/what changes do you propose?
I suggest to oredict the wood to fix this issue

**Comment by ljjmrlion** [comment]
This is just one line in minetweaker to fix. Is there any reason for not doing this? Or was it just an oversight.

**Comment by Dream-Master** [comment]
@DietmarKracht @ljjmrlion why not make a pr ?

**Comment by ljjmrlion** [comment]
@dream-master pr?

**Comment by Dream-Master** [comment]
Pull request
