### ISSUE TITLE
Add Maple Syrup Extractor Recipe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#4993]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private Multiplayer
#
Maple Wood has no usage. So once you start chopping it you can only store it somewhere. Maybe add an extractor recipe that gives maple syrup.

**Comment by ljjmrlion** [comment]
I agree with this. Centrifuge or extractor should turn Maple logs into syrup/wood pulp

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/64722481-d990ae80-d4ce-11e9-93c0-9a4458734e3c.png)

**Comment by DietmarKracht** [comment]
Also, Add cinnamon wood extractor recipe as well as paperbark.
