### ISSUE TITLE
Assembly Line won't check voltage

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/NewHorizons#5003]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
I tried to craft UHV dynamo hatch in UV AssLine when it needs UHV
#
#### What happened instead? (Attach screenshots if needed)
It voided items
#
#### What do you suggest instead/what changes do you propose?
Idk is that bug or feature so I reported that

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/14ea6a3ba9de16dd6fbd731b7b0f80ed109d4541
