### ISSUE TITLE
Storage Drawer Assembler Recipe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#5006]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
The Assembler Recipe for Storage Drawers should be a little bit cheaper. Currently it just takes the same amount of resources to handcraft or to assemble. 
#
#### What happened instead? (Attach screenshots if needed)
With better barrels the assembler is a lot cheaper than the handcraft.
#
#### What do you suggest instead/what changes do you propose?
Either make the storage drawer recipe cheaper in assembler or make the better barrel recipe use the same resources in assembler as in handcraft.

**Comment by Dream-Master** [comment]
We are packing the scripts to code sonn.
Bart is working on it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4983
