### ISSUE TITLE
Salt ores not going into Miners backpack

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/NewHorizons#5009]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
private server

#
#### What did you try to do, and what did you expect to happen?
I was expecting salt ores to going into the Miners’s backpack

#
#### What happened instead? (Attach screenshots if needed)
https://youtu.be/UaunYVx2L2w

#
#### What do you suggest instead/what changes do you propose?
Salt ores must going into the miner's backpack

**Comment by Dream-Master** [comment]
works now with new config

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/66839093-2bad6f80-ef66-11e9-8920-604e20082d33.png)
