### ISSUE TITLE
Custom main menu

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#501]
- [ ] [Custom main menu](https://mods.curse.com/mc-mods/minecraft/226406-custom-main-menu) and [ResourceLoader](http://minecraft.curseforge.com/mc-mods/226447-resource-loader) mods. (On hold, waiting for APNG support)
- [ ] Gather screenshots/GFX (Help welcome with this one, show off your builds!)
- [ ] Write the menu.json script.
- [ ] Push to the repository, closing this issue.

**Comment by Dream-Master** [comment]
:+1:

**Comment by Teteros** [comment]
On hold till Custom Main Mod 2.0 is released for MC1.7.10 and https://github.com/lumien231/Custom-Main-Menu/issues/96 is resolved.

**Comment by Technus** [comment]
APNG not going to happen:

https://github.com/lumien231/Custom-Main-Menu/issues/96

**Comment by deeplyarnab** [comment]
Booo, people are abandoning 1.7.10 :(

**Comment by Dream-Master** [comment]
@Teteros 
Any news here Teteros? If we can't get a animated Background take a Screenshot or some other Graphic. Thinks take too long and we never release the pack if wait so long.

**Comment by Dream-Master** [comment]
@Teteros 
Will do a custom main menu today by my selfe because i want to release the pack soon.

**Comment by Teteros** [comment]
Alright, sorry couldn't implement my ideas without the animations when I started this.

**Comment by Dream-Master** [comment]
I am not done yet. Have to understand first how the mod works.

**Comment by Dream-Master** [comment]
My custum Main Menu is done from my side. If anyone want to add or changes stuff you can do this after Update 1.0.8.7.
