### ISSUE TITLE
Recipies to can fluids in a cell are gone

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5010]
#### Which modpack version are you using?
2.0.7.6a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Tried to can helium and other fluids
![afbeelding](https://user-images.githubusercontent.com/42187820/64901625-12ca4980-d69c-11e9-8508-3ff6c752d82a.png)
It won't let me can fluids into GT cells, but it will let me uncan fluids.

**Comment by observeroftime02** [comment]
I can confirm that even water will no longer go into regular empty cells (it should). Universal fluid cells still work in the fluid caner though.

**Comment by bartimaeusnek** [comment]
Rollbacked GT++ to 2.0.7.5 version, works fine for me.

**Comment by observeroftime02** [comment]
I guess using an ULV fluid tank works in the meantime.

**Comment by Dream-Master** [comment]
@draknyte1 can you check if this is a gt++ issue or we have to looks elsewehere. Thanks

**Comment by ScriptedPiky** [comment]
> @draknyte1 can you check if this is a gt++ issue or we have to looks elsewehere. Thanks

Me and Alk / @draknyte1 found out what was causing it and are currently suggesting using this build https://circleci.com/gh/alkcorp/GTplusplus/380#artifacts/containers/0 to avoid the canner issue until now. It was discovered that build 382 was the cause of this issue

**Comment by Dream-Master** [comment]
Build 380 crash when searching nei recipe so i cant use it. Also the RAre Earth fix isnt included.
Any other idea or fix ? Or i need to fall back to very old 2.0.7.5 version which are no option too.
@draknyte1 @ScriptedPiky

**Comment by Dream-Master** [comment]
fixed. I tested
