### ISSUE TITLE
Giant input hatch needed for new air processing 

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5014]
#### Which modpack version are you using?
2.0.7.6b-dev
title.

**Comment by observeroftime02** [comment]
There is a liquid air input hatch.

**Comment by Anarack** [comment]
Did not see that, but it should be renamed so it comes up when looking for input hatches.

**Comment by observeroftime02** [comment]
This is a Bartworks thing, so Bart could fix it.
