### ISSUE TITLE
[Bartworks] NEI plugin all recipes shows garbage

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#5017]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was looking for mining options on Ross128b - or rather noticed some oddities and then started picking apart the NEI plugin in detail

#
#### What happened instead? (Attach screenshots if needed)
The all recipes feature is broken; it shows the base GT ores appropriately, but garbage where BartWorks ores would have been.

![image](https://user-images.githubusercontent.com/8459776/65070355-c37e6480-d98c-11e9-850d-37f1cccc0c6a.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek
