### ISSUE TITLE
Quest #623 impossible

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#5020]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Rare Earth now requires HV Sifter. The quest is in LV tab though.
#

#### What do you suggest instead/what changes do you propose?
Move it to HV. Do another quest for cadmium at lv with mining some sphalerite, washing and centrifuging it...

**Comment by bartimaeusnek** [comment]
*should be fixed on gt++ side by now*

**Comment by draknyte1** [comment]
It was a month ago.

Cadmium being REQUIRED availability wise in LV is fucking stupid though. Lithium is MV, same purposes. Cadmium is more advanced, so why is it easier to obtain?

/2cents of afterthough.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/66164027-ff265900-e631-11e9-9cc5-93d19dfbbe96.png)
readd recipe so far the other recipe works better
