### ISSUE TITLE
Ore dict Resonant Ender Bucket and Liquified Ender Bucket for Mirrored Glass recipe

### ISSUE THREAD

**Issue by speckbrot** [GTNewHorizons/NewHorizons#5025]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
Try to build Thaumcraft Mirrored Glass, but only accepts Liquified Ender Bucket which you can only get from Tinkers smeltery, but filling the bucket with Liquid Ender using GT or Extra Cells machines, results in Resonant Ender Buckets which is will not be accepted in the mirrored Glass recipe
#
#### What happened instead? (Attach screenshots if needed)
https://ibb.co/1fRDm34
https://ibb.co/qpsydTq
#
#### What do you suggest instead/what changes do you propose?
Either change Mirrored Glass Recipe for Resonant Ender Bucket or add Ore dict to the recipe or allow both Buckets for the recipe

**Comment by yukieiji** [comment]
Already fixed
https://github.com/GTNewHorizons/NewHorizons/commit/6d1ebaf9413f2f94023c97de24984481d21d378c

**Comment by speckbrot** [comment]
ok i guess for 2.0.7.6 update
