### ISSUE TITLE
TCP singularities missing items

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/NewHorizons#5029]
7.0.7.6b

Tricalcium Phosphate singularities are uncraftable, they are lacking a recipe.

![image](https://user-images.githubusercontent.com/43228249/65657669-3749ee00-dfd9-11e9-8486-6d3da479e50a.png)

Could this be fixed? This prevents all items that use singularities from being crafted.

**Comment by Dream-Master** [comment]
i rember i fix this. Not sure what happend here.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Universal-Singularities/commit/2b845c836efd56ad176fde69624807c965b62030

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/65865091-2c91af00-e373-11e9-9c64-e33296f7ac56.png)
fixed in version b allready. Maybe you using wrong file.

@observeroftime02 Here is the 2.0.7.6c link
https://www.dropbox.com/s/0m9i884in1185bi/GT-New-Horizons-2.0.7.6c-dev.zip?dl=0
