### ISSUE TITLE
Electric Implosion Compressor doesn't work properly

### ISSUE THREAD

**Issue by Glammi** [GTNewHorizons/NewHorizons#5030]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
myftb.de
#
#### What did you try to do, and what did you expect to happen?
Use the Electric Implosion Compressor
#
#### What happened instead? (Attach screenshots if needed)
The compressor goes on and off, destroys the item and stays off.
#
#### What do you suggest instead/what changes do you propose?
fix
![2019-09-26_13 32 42](https://user-images.githubusercontent.com/42199976/65685630-b46d7580-e062-11e9-8c7a-bb66c239bb17.png)
![2019-09-26_13 33 03](https://user-images.githubusercontent.com/42199976/65685631-b5060c00-e062-11e9-964e-8ec244393f53.png)
![2019-09-26_13 33 11](https://user-images.githubusercontent.com/42199976/65685633-b5060c00-e062-11e9-95d6-d568be737f7a.png)

**Comment by observeroftime02** [comment]
Update Bartworks to the latest beta available, the implosion compressor works correctly now.
