### ISSUE TITLE
Repeated Crashes while loading a specific save

### ISSUE THREAD

**Issue by LowQualityCode** [GTNewHorizons/NewHorizons#5032]
#### Which modpack version are you using?
2.075
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
I tried to load into my world and I expected it to run.
#
#### What happened instead? (Attach screenshots if needed)
While loading the blocks the world crashes the console
#
[crash-2019-09-27_16.37.01-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3664929/crash-2019-09-27_16.37.01-server.txt)

**Comment by draknyte1** [comment]
Corrupted chunk, afaik.

**Comment by LowQualityCode** [comment]
> Corrupted chunk, afaik.

I would I fix this

**Comment by draknyte1** [comment]
Post you fml-client-latest.log please.

**Comment by LowQualityCode** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/3664935/fml-client-latest.log)

**Comment by draknyte1** [comment]
Could you also post `crash-reports\crash-2019-09-27_16.37.01-server.txt`?

So far both indicate a corrupt chunk or Tile Entity within the chunk.
I'd just roll back ona backup and accept this happens on rare occassion,

**Comment by LowQualityCode** [comment]
[crash-2019-09-27_16.37.01-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3664940/crash-2019-09-27_16.37.01-server.txt)
 Is it possible that backups are automatic? Cause the only one I have is from a few days ago

**Comment by draknyte1** [comment]
> backups are automatic
Backups are handled by you, the user to set-up, configure and ensure it works.
If you've ignored that quest in T0 and progressed without, you're shit outta luck beside your few day old one. you kinda get fancy, look which chunk it is, (Says at bottom of fml-client-latest) and then only replace that from a backup. Depends on your effort level.

**Comment by LowQualityCode** [comment]
Well thank you I will definitely be taking this to heart and get a backup running.

**Comment by draknyte1** [comment]
It's one of the first five quests you do, hehe.
Hopefully it wasn't a chunk within your main base. :)

**Comment by LowQualityCode** [comment]
It probably was, but if I wanted to go about replacing a specific chunk how should I go about that.

**Comment by Anarack** [comment]
Look into multi mc.

**Comment by draknyte1** [comment]
>Player Count: 1 / 8; [EntityPlayerMP['ApollosHammer'/304, l='Oh Geez', x=-861.94, y=83.00, z=-470.61]]

If that's you, a quick google can tell you how Chunks are stored and you can do some simple math to figure it out.

**Comment by LowQualityCode** [comment]
No luck so far from trying to change the chunk. I'm just going to go back to my previous file and install a proper backup system. Thank you for the help. My problem has been solved.
