### ISSUE TITLE
Amber staff and foci.

### ISSUE THREAD

**Issue by AiramProvoker** [GTNewHorizons/NewHorizons#5034]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Epsilon, official servers.
#
#### What did you try to do, and what did you expect to happen?
Attaching foci to an iron capped amber staff.
#
#### What happened instead? (Attach screenshots if needed)
Can't attach them.

#
#### What do you suggest instead/what changes do you propose?
Since all staves excel at handling foci, amber staff should be no different.

**Comment by psuemno** [comment]
I'm pretty sure that a real Amber Staff isn't actually craftable. If the recipe you used had 3 wand caps and a Primal Charm, then what you actually have is an Amber Staff Scepter. 

I did the same thing expecting to end up with a staff for casual foci use. While it's no good for that, it's still great as a vis battery for any Repair enchants and Runic Shielding, and did help me go on longer adventures without needing to come home to recharge.

**Comment by AiramProvoker** [comment]
Huh. So I made that weird "staffter" hybrid. Wands and Staves of Amber are uncraftable then. That solves the problem then. Thanks a lot for the answer, @psuemno.

**Comment by Dream-Master** [comment]
@AiramProvoker fixed?
If yes close the issue or i will do  it soon.
Thanks

**Comment by AiramProvoker** [comment]
@Dream-Master, well, turns out there was no bug to begin with. It doesn't seem to be possible to craft Amber Staves, only Amber "Staffters" and Scepters. 
Yeah, I'll close it.
