### ISSUE TITLE
Game crashes when I open the "controls" tab in options.

### ISSUE THREAD

**Issue by Proposed12** [GTNewHorizons/NewHorizons#5036]
#### Which modpack version are you using?
2.0.75
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
Tried to open my controls, expected it to work fine.
#
#### What happened instead? (Attach screenshots if needed)
2 days ago, I tried opening controls to configure keybinds. Crashed while scrolling down, so I reset my controls and configure them again. Jump to present, and I try to configure keybinds once again and I crash immediately after clicking it. Happens on servers, SP, and on the main menu. 
[crash-2019-09-28_19.22.31-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3666111/crash-2019-09-28_19.22.31-client.txt)

#
#### What do you suggest instead/what changes do you propose?
N/A

**Comment by sthegreat** [comment]
looks like an invalid keybind key, same issue as #4985. Try deleting your options.txt to regenerate it or looking for the messed up bind and changing it to something else there.

**Comment by draknyte1** [comment]
Also, fixed in next GT++ release.
https://github.com/alkcorp/GTplusplus/pull/525/commits/ebdb06055ebe8426e6546bae3321cf0282f2d98e

**Comment by Proposed12** [comment]
Deleting the options file worked for me. Thank you!
