### ISSUE TITLE
LCR recipes  - Ammonia NH3 and Nitrous Oxide issue

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5038]
#### Which modpack version are you using?
2.0.7.6b-dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Ive tried to establish LCR to produce ammonia (two inputs - Nitrogen,Hydrogen) then with another input of Oxygen it should make Nitric Acid, but then ive found that recipe for NH3 and NO are the same eg. no circuit to make a difference in LCR process so Nitric acid chain cant be done in LCR (but i am pretty sure it was doable bcs i have had running that for a little while!)

If thats done on purpose then its crazy to make LCRs bcs you cant use their full potential and making multiblock just for one fluid isnt very "economic" :))
#
![2019-09-29_20 46 44](https://user-images.githubusercontent.com/14223368/65837719-06c8c380-e2fb-11e9-832a-db786167c6c9.png)
![2019-09-29_20 46 48](https://user-images.githubusercontent.com/14223368/65837720-07615a00-e2fb-11e9-83cd-d26c94d0c9a2.png)

So for example set a circuit for Nitrous oxide, so that Nitric acid can be made in one LCR

**Comment by sthegreat** [comment]
There are a lot of instances where you can't do something at the same time in one lcr like this. But here it shouldn't matter because you can use the circuit 24 recipe to make nitric acid more easily anyways, don't need to make nitrous oxide at all.

**Comment by Hyperic88** [comment]
...anyways, don't need to make nitrous oxide at all.

yup thats what i did, but if you put N,H and O in one LCR it will make nitrous oxide and not ammonia ;) which you need for circ 24 (NH3+O2)
