### ISSUE TITLE
Volcanus issue on login

### ISSUE THREAD

**Issue by GoldBlockIngot** [GTNewHorizons/NewHorizons#5039]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta, I've seen problems with this happening on SP as well though. I'm certain it would happen on all servers.
#
#### What did you try to do, and what did you expect to happen?
Built a GT++ Volcanus to smelt in bulk, seemed simple enough, but difficulties ensued involving coming back to see the furnace deactivated with a maintenance problem. After some testing, I chalked it up to, on login, the problem occurs.
The issue puzzled me, but I did some testing and I think I know what's going on. This event is supposed to be because it's not getting sufficient pyrotheum. However this wasn't the case, as the vent was full and power was plentiful. I suspect that on login, the machine activates before it checks for pyrotheum or something, and it think it's not getting any and fires this event.
#
#### What do you suggest instead/what changes do you propose?
A fix is necessary but for the meantime I would recommend deactivating your volcanus before leaving the game or server. For those who randomly crash while smelting that important endgame material though...well you're SOL for now. Also, this issue may be present in other GT++ machines.

**Comment by Anarack** [comment]
Try the beta pack in announcements, gt++ may of fixed this. https://github.com/alkcorp/GTplusplus/issues/507
If so post here and in the gt++ issue
