### ISSUE TITLE
Chamelium uncraftable

### ISSUE THREAD

**Issue by sleepylucy** [GTNewHorizons/NewHorizons#5046]
Trying to make Chamelium in the Mixer makes coal balls.
![coaldust](https://user-images.githubusercontent.com/49254436/66345159-bdf2b980-e94f-11e9-93a8-f44249a25a3a.png)

**Comment by kekzdealer** [comment]
Seems like crafting always prefers options with no Integrated Circuit over options that have them.
Got the same issue with some of my recipes. The priority should be the other way around.
