### ISSUE TITLE
Some Better Questing Bugs & GT Machine NBT Issues

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/NewHorizons#5047]
Version 2.0.7.6b-Zeta Dev. Happens on the official Zeta server.

The current issue that I am particularly having with BQ is two or more infuriating bugs; one involving "ghost" like completed quests where you still have to turn in an item, but the quest is already completed. Pictures down below as such:
![2019-10-07_19 47 08](https://user-images.githubusercontent.com/41557212/66363596-9abe0f00-e93b-11e9-948c-b96f83144613.png)
![2019-10-07_19 47 14](https://user-images.githubusercontent.com/41557212/66363597-9abe0f00-e93b-11e9-800a-7ff433581684.png)
You can see that I need to complete this quest by turning in the HV hull, however, you can also see that I have already completed this quest.

This bug appears to happen every new update or since the latest new BQ instance. **However**, this particular bug had appeared since around 5.0~ updates, so it's been an incredibly long while.

Second, I cannot turn in **any** GT machine at all, despite having the machine in my inventory. This is possibly caused by the bug above or related to something else. In any case, this is entirely game-breaking as I legitimately cannot progress through the questlines at all.
![2019-10-07_19 54 31](https://user-images.githubusercontent.com/41557212/66363808-57b06b80-e93c-11e9-996c-f77ae2b0087c.png)
![2019-10-07_19 54 49](https://user-images.githubusercontent.com/41557212/66363809-58490200-e93c-11e9-81be-1b4eb27713c0.png)
You can even see that the machine is there, but not accepting. This happens to many other quests, not just this particular one.

**Comment by Anarack** [comment]
I'm fairly sure its a nbt matching issue, as turning on ignore nbt fixes it most of the time. Most gt related quests get blocked by this.

**Comment by ScriptedPiky** [comment]
Ohhh that makes a lot more sense. The GT machines that are required are ones from the **creative** tab/NEI page. Just checked in-game and compared two different machines; a handcrafted one and a creative one, the handcrafted was of course not the correct one. Some further investigation showed that `ignoreNBT` is false.
![2019-10-07_20 13 25](https://user-images.githubusercontent.com/41557212/66364550-efaf5480-e93e-11e9-8e3e-c0d315998e0f.png)

**Comment by Dream-Master** [comment]
Not sure if this works in all cases. Some times we need a specific item with nbt tags.

**Comment by ScriptedPiky** [comment]
> Not sure if this works in all cases. Some times we need a specific item with nbt tags.

Just the GT machine quests would need to have `ignoreNBT 1 - true` in-order for this to work. Otherwise, the quests are searching for a **creative** or NEI machine and only one type, not all types are searched. It picks the first result, which is the creative/NEI pulled machine.

**Comment by Dream-Master** [comment]
@ScriptedPiky can you do a quest id list for me so i can working quicker on it. Thanks

**Comment by ScriptedPiky** [comment]
All GT machine quest ID's (including GT++; excluding wires) are as follows:
44#, 63#, 62#, 61#, 60#, 46#, 50#, 58#, 51#, 57#, 54#, 53#, 56#, 497#, 73#, 70#, 88#, 90#, 116#, 554#, 96#, 1126#, 1887#, 100#, 869#, 94#, 101#, 545#, 1273#, 1274#, 1499#, 673#, 579#, 1155#, 543#, 538#, 898#, 771#, 891#, 892#, 1135#, 533#, 532#, 97#, 531#, 1792#, 795#, 930#, 542#, 599#, 1821#, 624#, 617#, 619#, 664#, 662#, 547#, 539#, 105#, 98#, 102#, 1134#, 791#, 935#, 792#, 89#, 1869#, 1267#, 1268#, 1269#, 1082#, 1148#, 740#, 1547#, 931#, 1907#, 894#, 944#, 1870#, 1081#, 754#, 751#, 1614#, 1320#, 1321#, 2253#, 126#, 1598#, 1494#, 1417#, 1744#, 2047#, 1322#, 850#, 951#, 735#, 1324#, 1924#, 1142#, 1145#, 1923#, 1922#, 1403#, 808#, 1921#, 160#, 1811#, 769#, 1877#, 1876#, 1906#, 770#, 1164#, 1420#, 1521#, 1289#, 1903#, 772#, 1237#, 1221#, 932#, 1271#, 943#, 1909#, 1815#, 1012#, 1879#, 1252#, 1223#, 1407#, 1406#, 1242#, 176#, 2018#, 2023#, 1416#, 1418#, 1262#, 1410#, 213#, 1890#, 1539#, 1669#, 216#, 1493#, 1689#, 1722#, 1683#, 1212#, 1200#, 1197#, 1198#, 1202#, 1419#, 767#, 784#, 76#, 786#, 783#, 77#, 85#, 765#, 1545#, 876#, 787#, 1740#, 80#, 786#, 788#, 1894#, 781#, 1652#, 766#, 1822#, 81#, 940#, 2144#, 1818#, 1820#, 1905#, 2027#, 1412#, 1787#, 1637#, 1419#, 1417#, 1418#, 1416#, 2033#, 1420#, 2028#, 2032#, 2053#, 2049#, 1421#, 1422#, 1423#, 2034#, 2029#, 2030#, 2031#, 2038#, 2037#, 2054#, 2036#, 2035#, 2040#, 2039#.

This should be every single quest out there. I might've missed a few, but these should cover almost everything.

**Comment by observeroftime02** [comment]
Went ahead and changed all the quests that Piky listed out to ignore NBT data, if there's any more that need to be ignored let me know.
