### ISSUE TITLE
Gadomancy's Golem logic issues

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5048]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What happened instead? (Attach screenshots if needed)
Server Crash.(This issue may also crash continuously)
[crash-2019-10-08_07.35.56-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3706166/crash-2019-10-08_07.35.56-server.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it.
I think this issue is caused by Java sorting algorithm that has changed due to version upgrade...

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea if this is fixed in 2.0.7.6 or can be fixed ?
