### ISSUE TITLE
Nice Nether Trees #1741

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#5050]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private
#
The Quest is in Tier 1 Steam. Though it gives back an MV reward bag which is tier 3 MV.

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/66829146-08c59000-ef53-11e9-9bb5-a8e152d8bf10.png)
