### ISSUE TITLE
LuV Energy Hatch need LuV power for Assembly Line

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#5052]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
no error - just a useless nerf
it is possible to use for ONE TIME 4 (2) IV Energy Hatches to get with the needed 32k EU a LuV Energy Hatch, but for what?
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
please reduce needed EU to IV level, may be four times longer...
![LUV_Energy_Hatxh](https://user-images.githubusercontent.com/7759876/66704080-3cb57100-ed19-11e9-91c4-580c95f2c049.JPG)

**Comment by botn365** [comment]
any energy hatch above MV needs a assembler of that voltage Hv need HV assembler EV need EV assembler so i dont see why LuV needs to be difrent when you can perfectly use 2 IV energy hatches to make the first LuV energy hatches

**Comment by Ngar1** [comment]
But you dont need a Energy Hatch for lower tier assember - thats the point.

**Comment by botn365** [comment]
you do need a energy hatch of the lower tier for first aluminium first stainles first tungsten + cooling
and other metals so why should the assline not be allow to need the lower tier hatch first

**Comment by Ngar1** [comment]
because an assembler doesend need a energy hatch, until LuV you need em, because only assembly line (multiblock) needs an energa hatch.

And you need this just one time, because than you could switch to LuV at the assembly line.

**Comment by botn365** [comment]
you need them at LuV bacous your using single block assemblesr but at LuV you need the assembling line to make the energy hatch but that is not a reason to stop the need of tier voltage to make tier energy hatch
and when your at the point you can make LuV energy hatches a second IV energy hatch should not be a problem

**Comment by Ngar1** [comment]
it is not a problem, but useless, because you need two IV EH only for 20s just for one block and never again. Assembly line is complicated enought (special how to automate them).

But as I say, it is not a failture, its in my point of view a useless nerf (I dislike useless nerfs).

**Comment by BlackFlameTNT** [comment]
Assembly line need more then one energy hatch for every new tier I don't see it a bug or any thing I see it something you need to deal with it.

**Comment by Dream-Master** [comment]
GTNH was never desinged to be easy :)
