### ISSUE TITLE
Question Repeat for stainless steel dust

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5053]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Question #749 and #751 are both required you to produce a stack of stainless steel dust
in tier 3 MV age.
#

**Comment by Dream-Master** [comment]
What need to be changed here @bjin2000 ?

**Comment by bjin2000** [comment]
Question #751 requires us to produce an 'Advanced Mixer' and 63 'stainless steel dust'
Question #749 requires us to produce 64 'stainless steel dust'

Are these two requirements duplicate?

I think the better way is question #751 only requires us to craft advanced mixer, then followed by a question that requires us to craft stainless steel dust.

**Comment by Dream-Master** [comment]
ok will change it.
