### ISSUE TITLE
Part Builder must be made of oak wood to progress with questline in quest book

### ISSUE THREAD

**Issue by freshwawa** [GTNewHorizons/NewHorizons#5055]
#### Which modpack version are you using?
2.0.7.5-1.7.10
#
#### If in multiplayer; On which server does this happen? 
ProsperCraft
#
#### What did you try to do, and what did you expect to happen?
Questbook related, did quest requiring you to craft the 4 basic Tinker's Construct tables, however I crafted part builder out of pine wood instead of oak and it did not register. 
#
#### What happened instead? (Attach screenshots if needed)
I expected the quest to complete but it required an oak part builder before it worked.
#
#### What do you suggest instead/what changes do you propose?
Make it so that for the Tinker's Construct quest, any type of part builder will work instead of an oak tool table. Resources are already hard enough to craft in this game, being punished for something like that seems a bit uneccesary.

**Comment by Dream-Master** [comment]
With bq1 it wasent possible not sure it will work in bq3.

**Comment by Dream-Master** [comment]
The problem is Tool Stations having different meta ids and no oredict.
If i reset meta it fall bac to 0 which is the tool station

**Comment by Dream-Master** [comment]
All part builder can be changed to oak
![image](https://user-images.githubusercontent.com/2970688/67749729-0a508700-fa2e-11e9-9935-fc90ad0fbd0a.png)
![image](https://user-images.githubusercontent.com/2970688/67749739-0e7ca480-fa2e-11e9-8b07-5734ca8336f9.png)
![image](https://user-images.githubusercontent.com/2970688/67749747-12a8c200-fa2e-11e9-96b8-866049e63fdb.png)

**Comment by Dream-Master** [comment]
just change it to oak and it works

**Comment by richardhendricks** [comment]
Quest needs update to tell players they can change to oak.

**Comment by Dream-Master** [comment]
yea

**Comment by Dream-Master** [comment]
@richardhendricks come back you the quest master :-)
