### ISSUE TITLE
Plunger 2.0 #1549

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#5058]
#### Which modpack version are you using?
Live Version
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I tried to put all the components into an assembler.
#
#### What happened instead? (Attach screenshots if needed)
The result was an lv fluid regulator as it conflicts with the assembler recipe for the handpump token.
#
#### What do you suggest instead/what changes do you propose?
Make the recipe unique

**Comment by draknyte1** [comment]
Fixed in dev.
