### ISSUE TITLE
Replace .giveBack coke oven brick recipes to .reuse or .transformReplace

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#506]
Please make the form stay in the crafting grid when you use it to make a coke oven brick, or craft the whole stack, putting it back in hundreds of times kills peoples wrists.

**Comment by ProsperCraft** [comment]
Also, if your inventory is full, it destroys the form.

**Comment by Dream-Master** [comment]
I add two recipe in the code one for one ingot and one for 8 ingots. We had before some trouble with Forestry Table (ghost items) that why we changing the recipe back.
https://github.com/GTNewHorizons/NewHorizons/issues/472
If the Form stays in the Table you can doublicate it with Forestry Working table.

Now we using this methode 
``````````````
<dreamcraft:item.WoodenBrickForm>.giveBack(<dreamcraft:item.WoodenBrickForm>
``````````````````
maybe we can try this

````````````````````````````
<dreamcraft:item.WoodenBrickForm>.reuse()
``````````````````

**Comment by Dream-Master** [comment]
I planning to add all recipes to the core mod in a long term so maybe this will fix it.

**Comment by deeplyarnab** [comment]
Someone knows the stress.....I had to make 12 coke ovens that way and my hands got rekt.

**Comment by Dream-Master** [comment]
Building a Bronze Alloy smelter and the problem is solved.

**Comment by Teteros** [comment]
>Please make the form stay in the crafting grid when you use it to make a coke oven brick, or craft the whole stack, putting it back in hundreds of times kills peoples wrists.

This WAS fixed as part of my duplication bug solution for https://github.com/GTNewHorizons/NewHorizons/issues/472.

Wooden Brick form stored as .transformReplace in a variable:
https://github.com/GTNewHorizons/NewHorizons/commit/0493545782189799ca4d7fa741525d04eb5a7128#diff-40a82948545fd6cab0c61ed65b61954fR53
Used in rewritten brick form recipes which were also shapeless:
https://github.com/GTNewHorizons/NewHorizons/commit/0493545782189799ca4d7fa741525d04eb5a7128#diff-40a82948545fd6cab0c61ed65b61954fR774

However it seems @Dream-Master undid my entire commit here:
https://github.com/GTNewHorizons/NewHorizons/commit/f7e6c8b31ff818656e6793e779cf339e94ad482f#diff-40a82948545fd6cab0c61ed65b61954fR770
