### ISSUE TITLE
bufferd dynamo hach not working like it should

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5061]
#### Which modpack version are you using?
7.6d
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
i build a large plasma turbine with a large draconium turbine and a bufferd zpm dunamo hatch 
this should produce ~204K eu/t 

#
#### What happened instead? (Attach screenshots if needed)
but when checking the bat bufer it was only recyving ~130K eu/t not 204Keu/t

when i replaced the zpm bufferd dynamo hatch with a normal UV dynamo hatch then i dit get the expeted 204Keu/t 
#
#### What do you suggest instead/what changes do you propose?
make it so the turbine can actualy dump more then 1 amp in a bufferd dynamo hatch

**Comment by Anarack** [comment]
This should of been fixed on steam turbines at least.

**Comment by draknyte1** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L517

Read through it here, see if you can find any issues. (It's commented)

The EU/t is passed in as a single value and should be split. If > hatch tier go boom.

**Comment by Dream-Master** [comment]
@botn365 @Anarack so what is with this issue ?

**Comment by botn365** [comment]
this should be fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/207

**Comment by Dream-Master** [comment]
ah ok thanks
