### ISSUE TITLE
Ticon clear glass panes can't make the iron tank guage

### ISSUE THREAD

**Issue by MaxsimalPD** [GTNewHorizons/NewHorizons#5063]
#### Which modpack version are you using?
2.0.7.5
#

#### What did you try to do, and what did you expect to happen?
I tried to use the TiCon glass to make iron tank guage from the multiblock quest for railcraft iron tanks.  It *seems* like that should be doable at an early tech level, considering when that quest opens up. 

#
#### What happened instead? (Attach screenshots if needed)
The clear glass panes you can get from TiCon can't make them.
#

#### What do you suggest instead/what changes do you propose?
I'd suggest either oredictionarying the panes - though that may not be intended because the normal panes are listed as 'HV' level (maybe that's not correct though?) or allowing another recipe for the iron tank guages that allows the clear glass ones.

Also possibly an early glass quest should be added, since the glass making process wasn't the most obvious (tbf I haven't explored the entire quest tree so maybe one exists)

**Comment by richardhendricks** [comment]
The "HV" level is for a later multiblock, it's not the level you can make the glass.

There are a couple of glass quests, for sure.  Do you have the chisel yet? You can use that to convert TiCon glass to various glass types.

**Comment by MaxsimalPD** [comment]
Ah so you can.  But only the blocks, not the clear glass panes.  Well, glad to know it's possible :)  I'd... still consider this valid feedback though.
