### ISSUE TITLE
Sever Crash when deconstructing HV Semi-Fluid Generator

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/NewHorizons#5064]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Have a HV semi-fluid generator, deconstructing it with a wrench causes a server crash (repeatable)

#
#### What happened instead? (Attach screenshots if needed)
[crash-2019-10-26_18.29.07-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3775111/crash-2019-10-26_18.29.07-server.txt)

#
#### What do you suggest instead/what changes do you propose?
Don't crash.

**Comment by Anarack** [comment]
Possibly fixed by https://github.com/alkcorp/GTplusplus/issues/553

**Comment by drayath** [comment]
Crash logs look identical. I forget to check the gt++ issue list before raising this one.

**Comment by Dream-Master** [comment]
@Anarack @drayath 
Please test with Dev pack and report it here. Thanks
http://downloads.gtnewhorizons.com/ClientPacks/GTNH-1.7.10-2.0.7.6e-dev.zip

**Comment by drayath** [comment]
GTNH-1.7.10-2.0.7.6e-dev.zip appears to resolve the issue.

**Comment by Dream-Master** [comment]
ok thats good. Thanks for info @drayath
