### ISSUE TITLE
buffers will output wrong amount then set

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5065]
#### Which modpack version are you using?
7.6e
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What do you suggest instead/what changes do you propose?
when i looked at my packager i saw that the super buffer outpuet a wrong stack size wich was set on 9 blocking the entire process
after some playing around with it becous it was consistently happpeng 
![afbeelding](https://user-images.githubusercontent.com/42187820/67627393-db82b700-f85b-11e9-9574-3e845c73b53b.png)
i saw this in the input hatch after removing 1 tiny pile from it gor replaced the momend i took it
i think this is why it happens

after i replace the HV input bus with a ULV input bus i had no problems with the buffer outputing the wrong stack size

**Comment by richardhendricks** [comment]
Try changing the buffer mode. one way it will try to keep the stacksize of the destination inventories at 9, the other way it will only output 9 items at a time. The first way will cause this problem because the inventory slots merge. The second way should work with this.

**Comment by botn365** [comment]
dint know this mode exist tank you
