### ISSUE TITLE
Steel Item Casing Recipes Broken

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/NewHorizons#5068]
GTNH 2.0.7.5

Now that Steel Item Casings Oredict into the GT Version any Recipe requiring the IC2 Steel Item Casings are uncraftable. IE Fluid Regulator. 

Revert it back to the old ore dict, or make some kind of shim.

**Comment by Dream-Master** [comment]
@redmage17 guess something broke with configs on your server. Here it works just fine.

**Comment by redmage17** [comment]
It's SP, I haven't changed the configs. Let me copy some fresh configs

**Comment by redmage17** [comment]
Does not working in vanilla crafting table or AE crafting terminal

**Comment by redmage17** [comment]
GTNH Core mod was few versions behind. Fixed
