### ISSUE TITLE
After last update storage drawers are not working properly with project red pipes

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#507]
New items are not getting placed into storage drawers, only existing items.
This started right after the update, did Storage drawers update?

**Comment by Dream-Master** [comment]
Yes Storage Drawers (1.9.4) get an update and Project Red too.(4.0.7.12.95)

**Comment by Teteros** [comment]
This might sound silly... Maybe you just had the drawers locked at the time?
Projred interface pipes with request chips will not send items into inventories they are forbidden to input into.
Try it on a GT type filter to see what I mean. Set on 'ore' only will only accept ores, obviously.

**Comment by ProsperCraft** [comment]
We added two stacks of 2x2 drawers and it won't fill them with items until we go in and tap the drawer with one block, then it will pull all bending blocks.  It basically can't make new entries.

**Comment by Dream-Master** [comment]
We update from Version 1.7.5 to 1.9.4.
``````
1.7.6

Added ability to change drawer style in-place by shift+right-clicking with trim block of desired style.
Added ability to hide upgrade borders by shift+right-clicking with trim block of same style.
Added capacity string to WAILA tooltip.
Changed default WAILA item counts to 'JABBA' style (affects new mod installations only).
Fixed thermal expansion integration returning wrong planks/objects for some drawers in the sawmill.
Fixed drawers spilling billions of objects if broken with creative vending upgrade (thanks Nentify).
Added German translation (thanks wlhlm).`
`````
``````
1.7.7

Fix crash if Thermal Expansion integration fails.
````
`````
1.7.8

Controller allows ore dictionary-compatible items to coexist in a bank of drawers. Items will prefer drawers with an exact match over drawers that would cause a conversion. AE2 integration supports this, but other integrations like Logistics Pipes and Automagy will need to update.
WAILA stack limit reads infinity when creative upgrades are in place.
Possible fix for unusual NEI render crash.
updated zh_TW translation (thanks NatsuArash).
´´´´´´
´´´´´
1.7.9

Fix crash when right-clicking controller with empty hand.
`````
`````
1.8.0

Added 'Personal Key' for owner-private access control.
Added CoFH variant of Personal Key using CoFH's friend trust list. Depends on Thermal Foundation.
`````
````
1.9.0

Added Framed Drawers
Added Framing Table
Added ja_JP translation (thanks vorfee)
`````
````
1.9.1

Fixed custom drawers dropping as regular drawers.
Fixed various rendering problems with custom drawers.
````
````
1.9.2

Fix permanent render crash when framing drawers with blocks that don't return valid icons.
`````
````
1.9.3

Fixed crash when removing a drawer from a controller network while other systems are using it.
Fixed framing table allowing players to dupe raw drawers.
Fixed framing table refusing to craft in some cases.
Fixed status upgrade crashing client when placed on framed drawers.
Performance improvement in controller interactions with some mods.
Minor rendering adjustments.
````
```
1.9.4

Fixed voiding regression for AE2, LP
Updated zh_CN translation (thanks XieEDeHeiShou)
````

**Comment by Dream-Master** [comment]
@ProsperCraft 
Is this still an issue or can this be closed?

**Comment by ProsperCraft** [comment]
So what we have found with more testing is that if a drawer is full it will keep the items in the input chest instead of using an empty drawer if you already have a drawer for that item.

I think it is just a change in logic somewhere.

**Comment by Dream-Master** [comment]
ok so no fix or anything possible to do here right ?
