### ISSUE TITLE
Low tier wand retrieval item missing

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5072]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
complete building questions
#
#### What happened instead? (Attach screenshots if needed)
retrieval item missing
![2019-11-01_01 42 54](https://user-images.githubusercontent.com/48137054/68004726-064c8100-fc49-11e9-9a2f-77d44b487cf5.png)
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by bjin2000** [comment]
The question is #1946

**Comment by Dream-Master** [comment]
will check
