### ISSUE TITLE
GT heat damage effects are broken

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5073]
2.0.7.7
Hot items and pipes do not damage me.
![2019-11-01_12 27 35](https://user-images.githubusercontent.com/20565115/68043327-04171080-fca3-11e9-9a08-06b25a2ee0ef.png)
.

**Comment by Dream-Master** [comment]
@Anarack did it hurt you before ? Since wich version this is changed/bugged?

**Comment by Anarack** [comment]
Started working again, not sure why it didn't work for a while.
