### ISSUE TITLE
Better quest not making a sound when you complete a quest.

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/NewHorizons#5078]
#### Which modpack version are you using?
2.0.7.7 eDev
#
#### If in multiplayer; On which server does this happen? 
On single player
#
#### What did you try to do, and what did you expect to happen?
when i complete a bq quest it doesn't make a completion sound nor does it show an image of the completed quest 
![2019-11-01_20 05 18](https://user-images.githubusercontent.com/57275066/68062272-110a2300-fce8-11e9-8c5e-1813b99bc890.png)

#
#### What do you suggest instead/what changes do you propose?
Put a sound when you complete a quest, and also an image of the completed quest

**Comment by Dream-Master** [comment]
I send a pm to @Funwayguy.

**Comment by richardhendricks** [comment]
@Funwayguy 

One of our players figured out the issue:

Fixed my sound thing -- this was in a new world and it looks like the default quests were wrong. They override the default sound for each individual quest, all are minecraft:entity.player.levelup, which doesn't seem to exist in 1.7. Find/replaced all with random.levelup, reloaded defaults in world, my ding noises are back

**Comment by Funwayguy** [comment]
Guess I missed that minor change in the legacy conversion code.
