### ISSUE TITLE
SSP login minetweaker errors

### ISSUE THREAD

**Issue by leftyde** [GTNewHorizons/NewHorizons#508]
Spiel bisschen im SSP und mir sind seit dem letzten Updates viele minetweaker fehler aufgefallen beim SSP login. Ich schick später mal den Log bin nur noch auf der Arbeit.

**Comment by Dream-Master** [comment]
Lösche mal deine Instanz oder zumindest den config und script Ordner. Da sind viel Dateien doppelt oder haben andere Namen.

**Comment by leftyde** [comment]
Jo hätte ich auch drauf kommen können.... :D

**Comment by Dream-Master** [comment]
:+1:
