### ISSUE TITLE
remove small osmium ore from genymede 

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5080]
#### Which modpack version are you using?
2.0.6.7e
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What do you suggest instead/what changes do you propose?
remove small osmium ore from  genymede 
you can easly get 1K osmium ore from the planet wich is way to op
to get from a T3 planet

**Comment by Dream-Master** [comment]
i like to replace it. @botn365  which ore ate good ?

**Comment by ScriptedPiky** [comment]
Iridium (if that already isn't in Ganymede) could be a nice substitute in replacing pure Osmium

**Comment by Dream-Master** [comment]
small iridium is on Ganymede allready @ScriptedPiky

**Comment by botn365** [comment]
could be replaced with small quantinium ore

**Comment by Dream-Master** [comment]
but not on y tier 3 Planet. Quantinium is Level 4 @botn365

**Comment by botn365** [comment]
ceres a T3 planet also has small quantinium ore

**Comment by Dream-Master** [comment]
realy will check
