### ISSUE TITLE
Bricked Blast furnace wrong bricks in description

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5082]
2.0.7.7, but probly been here forever

Description does not say it needs firebricks.

**Comment by Dream-Master** [comment]
will check it.

**Comment by Dream-Master** [comment]
return new String[]{
                "Controller Block for the Bricked Blast Furnace",
                "Controller has to be placed in the (front) center of the second layer",
                "Useable for Steel and general Pyrometallurgy",
                "Size(WxHxD): 3x4x3 (Hollow, with opening on top)",
                "Built from 32 Fired Brick Blocks",
                "Causes 200 Pollution per second"};

@Anarack what you want to change ?

**Comment by Anarack** [comment]
Fired Brick Block should be firebricks instead.

**Comment by richardhendricks** [comment]
Also, update the Cleanroom tooltip, it should be "filter machine casing" so players can search for it in NEI properly.
