### ISSUE TITLE
Underwhelming rewards for the Ore Mining Rig (T1).

### ISSUE THREAD

**Issue by AiramProvoker** [GTNewHorizons/NewHorizons#5083]
Currently the rewards for the Ore Mining Rig are rather underwhelming. The multiblock machine is EV tech and requires multiple EV motors, among 2 EV circuits. The (optional) rewards, however, are next:
- MV bag
- 2 MV motors
- 2 Data Sticks
- 16 Al plates

![orerig](https://user-images.githubusercontent.com/9785108/68088830-1d66bb00-fe63-11e9-85fb-282f578d3952.png)

It could be changed to something along these lines:
- EV bag
- 2 EV circuits
- 16 Titanium ingots

**Comment by Dream-Master** [comment]
yes that is wrong. Will check the rewards
