### ISSUE TITLE
Better quest not recognizing crafting tasks

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/NewHorizons#5085]
#### Which modpack version are you using?
2.0.7.7
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
It's the third quest that i couldn't complete without /bq_admin because itsn't recognizing, (i've crafted on worktable, tinkers and vanilla crafting table)  
![2019-11-05_18 11 55](https://user-images.githubusercontent.com/57275066/68248543-d3fda380-fffb-11e9-8dcf-10b86baf9e83.png)
(quest not completed, even though i've just made the electric piston on a vanilla table)

**Comment by Dream-Master** [comment]
Did you reload the quest?
/bq_admin default load

**Comment by maniifestantes** [comment]
yes, multiple times, it only worked for the steam turbine quest(the last steam tier quest)

**Comment by richardhendricks** [comment]
How did you get the components to make the piston?

**Comment by maniifestantes** [comment]
i crafted some with my hands, others on the tinkers table

**Comment by Dream-Master** [comment]
maybe another nbt issue

**Comment by maniifestantes** [comment]
i should just comment that i "fixed" the problem by reseting my quest and redo all of them(with bq_admin complete one by one ), it seemed like all the old quests i already completed were incomplete, and i couldn't complete them again.
