### ISSUE TITLE
Crash on Launching

### ISSUE THREAD

**Issue by JFMillerUSA** [GTNewHorizons/NewHorizons#5087]
v 2.0.7.5 on Twitch Client

https://pastebin.com/raw/cLjv4SeU

**Comment by mitchej123** [comment]
are you running optifine and fastcraft?

**Comment by bigbass1997** [comment]
The Twitch release for that version is generally regarded as broken, and the launcher itself has had a history of problems. I'd highly suggest using a different launcher instead: either [Technic](https://www.technicpack.net/modpack/mcnewhorizons.677387), or [downloading the pack directly](http://downloads.gtnewhorizons.com/ClientPacks/) and using [MultiMC](https://multimc.org/#Download).

**Comment by Dream-Master** [comment]
@JFMillerUSA did it work with another launcher ?

**Comment by JFMillerUSA** [comment]
Yeah running both with resourcepacks. Decided to remove both resourcepacks
and Optifine. Launches just fine on twitch with some Java line commands.

**Comment by bigbass1997** [comment]
You are probably running a version of fastcraft/Optifine which is incompatible with the other mod.

**Comment by Dream-Master** [comment]
@JFMillerUSA optifine D6 works with Fastcraft 1.23. Newer version need Fastcraft 1.25 (not in the Pack)

**Comment by basdxz** [comment]
Well documented issue with older fastcraft/newer optifine.
