### ISSUE TITLE
[RFC]Fortune Mod in Ore Drilling Rigs

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/NewHorizons#5089]
#### Which modpack version are you using?
2.0.7.7Dev
#
#### What do you suggest instead/what changes do you propose?

The fortune mod od the Ore Drilling Rigs is ridicously high. 2 T3 Ore Drilling rigs gave out ~20k Neutronium on Mercury (just small ores). Drilling Veins is less efficient currently than using OreDrills for small ores, therefore i suggest to set the Fortune Modifier to 0/0/0 for single and 1/2/3 for the Multis, with 3 beeing the same you can archive with a quarry.

**Comment by botn365** [comment]
i got 21.5K neutronium from 2 T3 drills mining the full 12x12 chunks on T5 planets(oberon,ancleados(ice planet))
not mercery

**Comment by richardhendricks** [comment]
Might be better just to disable fortune on Small ores. At high tier, aren't you needed tens of thousands of ore? The fortune bonus is to make the Ender Quarry less attractive as well, since that just leaves vast swaths of useless chunks on servers.

**Comment by botn365** [comment]
i think the fortune of the ore drill should be 2/4/6/8
and no bonus on the single blocks

**Comment by Anarack** [comment]
The single block ones don't boost the main ore yield so I wouldn't gut their fortune completely, just not higher than the large drills.

**Comment by bartimaeusnek** [comment]
@richardhendricks but the fortune only applies to small ores... regular ones dont get fortune boosted at all with the ore drilling rig, also wdym with ender quarly leaves useless chunks? it just replaces all blocks it mines with dirt...

**Comment by richardhendricks** [comment]
That's what I meant, the point at the time was to make it a step towards a void miner, ie leave it in an area, and come back with a bunch of stuff without destroying half the landscape.

Are you sure the fortune only applies to small ores?  I swear I tested it with normal ores and saw boosting there, I don't think I tested with small ores.

2 T3 oredrills cover a really large area - 500+ chunks right? 40 small ores per chunk doesn't sound like alot to me. A alternate solution is to reduce the density of small ores. How high is the Neutronium ore density?

**Comment by botn365** [comment]
a T3 is 12x12 so 144 chuncs or 288 for 2
neutronium is 8 ore/chunck that is 2304 small ore

**Comment by richardhendricks** [comment]
Thanks for the numbers, that helps a lot.

I like the idea of leaving the singleblock miners with a fortune bonus of 1/2/3.  The multis could go 4/5/6/7 - I think that's still a pretty good bonus and worthwhile.

**Comment by richardhendricks** [comment]
FYI, the current bonuses are 3/5/7 on the singleblocks and 6/11/16/21 on the multiblocks.

**Comment by botn365** [comment]
fortune 16 is 21.5K/2K = ~9x the amount
asuming fortune is linear
that is 8/16 = 0.5 extra ore per fortune
the new numbers would be
3x/3.5x/4x/4.5x for large drills

**Comment by sthegreat** [comment]
> Are you sure the fortune only applies to small ores? I swear I tested it with normal ores and saw boosting there, I don't think I tested with small ores.

There is boosting for normal ores but it's independent of fortune.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OreDrillingPlantBase.java#L113

this code macerates normal ores and increases the drops (by what I though was 3x but actually looks more like 2.5x) with no regard to drill tier or fortune level; no such mechanic exists for the singleblock drills as they just give ore blocks.

**Comment by richardhendricks** [comment]
If I recall correctly, there was a 1 level add to small ores because of them being critical in the early stages of the game for things like silver and other small ores that players needed at that early stage.  Probably could cut back on the fortune from the rigs to compensate.

I don't think we want the mining rigs to be "balanced against" the EQ, but "used instead" right?

**Comment by botn365** [comment]
if you want players to use the rig instead of ender quarys they need auto chunck loading and a big range 
becous thats the bigest reasen to use the EQ

**Comment by richardhendricks** [comment]
Ah I remember what it was, when we did the "placer ores" add, the density on average was a little less since the small ores replaced ore blocks. The +1 fortune was to balance out the overall result so that the total if someone mined them was closer to what you would get before without the orevein spread into tracer ores.

@botn365 Yes, that's the long term plan.

**Comment by sthegreat** [comment]
The eq is gated to post fusion instead of removed so I imagine it's supposed to be an option at some point. iirc it uses a lot of power so it's more of an endgame thing to continuously quarry a certain dimension with it instead of using gt miners and having to move them

**Comment by basdxz** [comment]
Fully agree with Bart, really dislike the miners having such an absurd boost to ore output when compared to manual mining as is. 0/0/0 1/2/3 rates or similar seem more than adequate. I believe they were meant as a sidegrade to the ender quarry or is there some real benefit to promote using them instead?
