### ISSUE TITLE
Additional Mod

### ISSUE THREAD

**Issue by JFMillerUSA** [GTNewHorizons/NewHorizons#5097]
Modpack v2.0.7.7-dev

To make it more creepier at night can you add the mod [Flashlight Mod](https://minecraftside.com/flashlight-mod/)

TIA

**Comment by observeroftime02** [comment]
I can't find out what license this mod is published under. Got any idea?

**Comment by bigbass1997** [comment]
There's no indication of a license, which typically means it defaults to all rights reserved. The mod hasn't been updated for 4 years, and the developer doesn't appear to have the source anywhere nor is active anymore. Unfortunately it also adds an item, which means it can't be client-side only.

I don't see how this would be beneficial for the modpack? I don't even see how it would make night any "creepier"; rather it would make night less scary and less dangerous. It would pretty much defeat the purpose of hardcore darkness.

Unless someone can give a good reason why this is a good addition, there's no chance this will be added to the pack. If an individual playing on a private server they own, or in Single Player, wishes to add the mod, then that's up to them; but the actual modpack doesn't appear to benefit from this addition.

**Comment by sleepylucy** [comment]
Or you could just install optifine, that’s client side only and adds that functionality to vanilla torches

**Comment by richardhendricks** [comment]
I agree, with the difficult mobs we have a flashlight that only points in one direction isn't that useful. 

What I'd like to see is a torch/other light auto-placer that can be configured to place light sources in a grid. That would be really nice for setting up large rooms.
