### ISSUE TITLE
Quest Important Tools not detecting

### ISSUE THREAD

**Issue by JFMillerUSA** [GTNewHorizons/NewHorizons#5099]
#### Which modpack version are you using?

# 2.0.7.7-dev
#### If in multiplayer; On which server does this happen? 

# NA
#### What did you try to do, and what did you expect to happen?

# Used /bq-admin edit True, tried to change some settings.
#### What happened instead? (Attach screenshots if needed)

# Couldn't figure out what settings to change.
#### What do you suggest instead/what changes do you propose?

# Change settings in Better Questing to allow better detection of tools on Important Tools Quest.

TIA

**Comment by draknyte1** [comment]
Known issue in the dev versions. 
Don’t use the dev versions. 🤷🏻‍♀️
