### ISSUE TITLE
Gregtech modual armor should be disabled or fixed due to possible player data corruption issue

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5101]
all versions probably, see alk for more details.
![image](https://user-images.githubusercontent.com/20565115/68714925-7cfd4e80-0566-11ea-8b36-35d173bc3df7.png)

**Comment by draknyte1** [comment]
This hinges on it being the same untouched code from master branch. But seeing as how nobody uses it, I’d swing towards that being more likely than not. 

I’d like to be wrong.

**Comment by Anarack** [comment]
Looking at its history, we haven't really touched it. Last major changes where from bloody back in 2017.

**Comment by draknyte1** [comment]
What’dya know? I’m right 😒
Then yeah, all the above stuff is true. I’d thought about redoing them once in the past, but opted to make a modular bauble instead with similar properties. It’s in a fairly working state, just can’t comment on its balance. Why it’s never had a recipe.

**Comment by Dream-Master** [comment]
disabled for now
