### ISSUE TITLE
Change LCR recipe to create Deep Iron from UV to ZPM

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/NewHorizons#5109]
2.0.7.5

Right now there's a recipe to convert space flowers and meteoric iron into deep iron, which can be used to get Trinium. It is however not possible to get before fusion (Which requires Trinium), as the LCR does not work with 8 LuV energy hatches.

I propose changing the required voltage to ZPM, so it can be done with 2 LuV energy hatches. This would allow getting Trinium without a rocket possible, for challenge runs.
![image](https://user-images.githubusercontent.com/42840657/69501947-9614e080-0f12-11ea-8a08-f576ebdd8051.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek it's your recipe.

**Comment by SampsaxD** [comment]
Yeah bart told me to add an issue for him
