### ISSUE TITLE
Server crash with 2.0.8.0a

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/NewHorizons#5114]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
personal server
#
#### What did you try to do, and what did you expect to happen?
loaded files to a server box and launched.
#
#### What happened instead? (Attach screenshots if needed)
server startup crashed on what looks to be GT++
#
#### What do you suggest instead/what changes do you propose?

[crash-2019-11-25_21.27.45-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3889924/crash-2019-11-25_21.27.45-server.txt)

Fresh install server side of 2.0.8.0a. Error looks to be from GT++ mod. Issue does not happen client side.

**Comment by Zodiack256b** [comment]
Reversion to gt++ 394 from 2.0.8.0 issue resolves. Issue seems to be with version 400 of GT++ in 2.0.8.0a.

**Comment by Dream-Master** [comment]
@Zodiack256b please open up a ticket on gt++ side. Thanks

**Comment by ScriptedPiky** [comment]
https://github.com/alkcorp/GTplusplus/issues/577
