### ISSUE TITLE
Armor crafting is broken

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5115]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
craft an armor
expected normal recipes
#
#### What happened instead? (Attach screenshots if needed)
recipes have reverted back to vanilla ones
![2019-11-25_22 55 58](https://user-images.githubusercontent.com/29802757/69598263-c32ac700-0fd6-11ea-9c64-3fce005e05d9.png)
![2019-11-25_22 56 02](https://user-images.githubusercontent.com/29802757/69598265-c45bf400-0fd6-11ea-8ada-f1db74e15840.png)
Seems to only be a problem with metal armors (iron, gold, bronze, steel, thaumium, thauminite) as far as I can tell
#
#### What do you suggest instead/what changes do you propose?
fix recipes to require plates and hammer again

**Comment by Dream-Master** [comment]
Will check.
@bartimaeusnek can this happend because of your fast loading procedure patch ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/69755841-702d4d00-1159-11ea-9ae2-97c8a934d577.png)
![image](https://user-images.githubusercontent.com/2970688/69755850-76232e00-1159-11ea-8008-6b3f665fbe2f.png)
