### ISSUE TITLE
Volumetric flask doesn't work with drums

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#5117]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
R-Click a volumetric flask on a drum with refined glue.
It does not drain the glue, drum reports contents instead, as if clicked with a non-container.

**Comment by Dream-Master** [comment]
The volumetric flask are devices for using fluids more less than 144mb/1000mb. Why you want to fill a drum with it use cells.

**Comment by repo-alt** [comment]
I do not want to fill a drum, I want to fill a flask _from_ the drum.
Also, speaking about filling - what's wrong in the dumping the fluid back if it was not needed.

**Comment by draknyte1** [comment]
We can’t really change ExU behaviour. It does that to most fluid containers if memory serves me right. 

Fluid handling and items that hold fluids is a headache for all parties.

**Comment by repo-alt** [comment]
Can't this be handled from the flask side?

**Comment by draknyte1** [comment]
It could be, but it shouldn’t. Fluid API exists to work as is, working around that ends up with dupes galore. The drum expects to handle the behaviour, so..

**Comment by richardhendricks** [comment]
https://xkcd.com/927/
