### ISSUE TITLE
UV 4A energy hatch needs wierd amount of silver

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5118]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What do you suggest instead/what changes do you propose?
![afbeelding](https://user-images.githubusercontent.com/42187820/69759928-7f18fd00-1163-11ea-9b61-a5e4b1c86fe8.png)
you need 1000L silver for the hatch 
wich is a wierd amount to use for molten metals wich coma at amounts of 144L
change it so a normal amount like all the other items that need molten metal

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/69764008-3d8e4f00-116f-11ea-82ff-d07c4e400577.png)
same thing for the object holder

**Comment by Dream-Master** [comment]
@botn365 are this tec tech items ?

**Comment by botn365** [comment]
they are tectech items

**Comment by Spartak1997** [comment]
https://github.com/Technus/TecTech/commit/b6e12a2c46fba15f5205a1d0c2f85408d8e8b9be
