### ISSUE TITLE
Expand Warp Warnings TC Page

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#512]
Show a few examples of thaumaturge malpractice and hint a way to clean it.

**Comment by Dream-Master** [comment]
Make screenshots from the messed Areas and integrate it into the TCBook ?

**Comment by Teteros** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/512

**Comment by Dream-Master** [comment]
Why you close this ?

I open up an issue for a other thing.

**Comment by Teteros** [comment]
Ment to say https://github.com/GTNewHorizons/NewHorizons/issues/529 above, it's both are warp warnings related so better keep it in one place.

**Comment by Dream-Master** [comment]
ah ok so no facelift needed?
