### ISSUE TITLE
BQ3 Quest ID can not be seen in game

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5121]
2.0.8.0a

Title, having access to this is important because otherwise the complete command can not be used in a practical manor and it makes submitting bug reports and the fixing of quest bugs easier.

**Comment by Dream-Master** [comment]
They're there. You just need to turn on advanced tooltips with F3 + H

**Comment by richardhendricks** [comment]
Need to add this to the splash screen or initial window on the questbook.  It's too useful to not have.

**Comment by shawnbyday** [comment]
If you do F3 + H and they still don't show up try restarting your client. This is what I had to do to get them to turn on.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/71456252-36526500-275e-11ea-8b30-2b8c468fa34d.png)
