### ISSUE TITLE
Texture missing for IC crop Water lilly

### ISSUE THREAD

**Issue by grumpymood** [GTNewHorizons/NewHorizons#5122]
#### Which modpack version are you using?
GTNH 
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I was cross breeding crops and water lilly appeared.
#
#### What happened instead? (Attach screenshots if needed)
![2019-11-29_01 05 56](https://user-images.githubusercontent.com/29691833/69847358-df33a000-1244-11ea-8002-5dce45f5feca.png)

#

**Comment by Dream-Master** [comment]
@grumpymood which version you are using ?

**Comment by bartimaeusnek** [comment]
2.0.7.5 is on prospercraft

**Comment by grumpymood** [comment]
Correct.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/69888463-43f60580-12ec-11ea-838e-c1e6cdbab304.png)
![image](https://user-images.githubusercontent.com/2970688/69888615-1b224000-12ed-11ea-9700-da52345a93d6.png)
![image](https://user-images.githubusercontent.com/2970688/69888760-de0a7d80-12ed-11ea-98e5-9b6ec1eaf6b8.png)

**Comment by grumpymood** [comment]
Thank you for the response.  Does that mean it works for you or that it is
fixed?

Regards
Grumpymood

**Comment by Dream-Master** [comment]
That it is fixed in newer version. 2.0.7.5 is 6 month old. Will release 8.0 soon.

**Comment by grumpymood** [comment]
Great, thank you so much!

**Comment by shawnbyday** [comment]
This is fixed for sure in 2.0.8.0.
