### ISSUE TITLE
Constant crashes after changing hotkeys

### ISSUE THREAD

**Issue by shitstainlord** [GTNewHorizons/NewHorizons#5132]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
Tried changing the conflicting the hotkeys and the game crashed. Now it crashes everytime I load up the game or go to key bindings options (without loading the world)

Crash log:
[crash-2019-12-03_22.24.04-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3918325/crash-2019-12-03_22.24.04-client.txt)

**Comment by toadjaune** [comment]
Me and my friends are also having it on our server. We can provide extra crash logs if useful :)

**Comment by shitstainlord** [comment]
I actually found the solution with some help. Go to options.txt file and find if any of the values there are above 255. If so, change it to something less than 255 and launch the game. It should work

**Comment by richardhendricks** [comment]
fixed
![image](https://user-images.githubusercontent.com/1214811/71455657-a14e6c80-275b-11ea-8b04-65ae9bf07581.png)

**Comment by draknyte1** [comment]
It IS a bug in LWJGL and it IS fixed in 2.8, but not by you guys. 

Quest is redundant/useless because unless it occurs shortly after it, it’s a tad hard to query once it breaks and you have no idea why. Just don’t bother, won’t ever happen again. 

https://github.com/alkcorp/GTplusplus/issues/544

**Comment by toadjaune** [comment]
Even with a fix (which is great, thanks @draknyte1 !), this quest is still useful to indicate that you need to deconflict keys. The extra sentence about fixing options.txt might be removed though.

**Comment by toadjaune** [comment]
Did you mean that it is fixed in `2.0.8.0` by the way ?

**Comment by richardhendricks** [comment]
The quest change will be in the next release. The fix probably is not in 80 since we had to rollback gt++, should be in the next release though.
