### ISSUE TITLE
Why I can't make a coin mould?

### ISSUE THREAD

**Issue by Sakura-sama** [GTNewHorizons/NewHorizons#5135]
2.0.7.5
I want to make some coin to load my driller,but I can't make a coin mould.Can a coin mould be made by player?

**Comment by draknyte1** [comment]
Coin mold recipe was re-added long ago, then removed again.
Should exist as it's required for access to one of my Dimensions.

**Comment by Sakura-sama** [comment]
thanks,more thing I want to know is how to update my 2.0.7.5 to 2.0.7.7?

**Comment by Dream-Master** [comment]
update to 2.0.8.0 @Sakura-sama 
just replace the 3 folder mods, configs and scripts.

**Comment by draknyte1** [comment]
Issue still exists in dev afaik.

**Comment by richardhendricks** [comment]
This is fixed in 2.0.8.0
