### ISSUE TITLE
Ichor & Thaumic Thinkerer

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#514]
Ichorium (KAMI) from Thaumic Tinkerer is currently **disabled** till TT gets its first minetweaker scripts pushed into the pack. Just like other mods' wand caps and rods, unfortunately you will have to wait for the recipes to be made till you can use them.

Thaumic thinkerer scripts are planned for the **1.0.7.8** release, after we sort out Galacticraft/GalaxySpace problems first.

As always, don't hesitate to post small tweaks here on the issue tracker, or more elaborate suggestions on our [forum](http://forum.gtnewhorizons.com/forumdisplay.php?fid=11).

**Comment by Dream-Master** [comment]
All recipe done and approved by Drobac.
