### ISSUE TITLE
Quest ID 2263 Industrial Grafter

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#5141]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
This quest has no objectives and auto completes upon completing Quest ID 2121 Better Grafter through Technology. (I'm playing in a fresh world)

**Comment by Dream-Master** [comment]
will check

**Comment by richardhendricks** [comment]
Fixed, however the Industrial Grafter is pretty ridiculous, requiring osmium and palladium parts.

**Comment by Dream-Master** [comment]
will check
