### ISSUE TITLE
Silky Combs quest requires forestry centrifuge and GT centrifuge

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5145]
Change to only requiring GT centrifuge, and point to forestry centrifuge in quest as a potential upgrade that is slower but gets 9 items.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/70373819-2cbaa780-18ec-11ea-93d9-5935089d0206.png)
![image](https://user-images.githubusercontent.com/2970688/70373822-30e6c500-18ec-11ea-895b-5cd1614b363e.png)
i dont see the difference

Or there are circuits which make output better @richardhendricks  ?

**Comment by richardhendricks** [comment]
No, they both work fine, my point is that the quest is gated by both.  I think the quests need to be reorganized a little.  Move the Forestry centrifuge quest to after the Go find some tropical bees as a side quest, and unlock the combs quest immediately, without gating on the centrifuges.  The silky combs quest says "use a GT centrifuge or Forestry centrigue" but a player right now won't even see that because the quest doesn't unlock until *after* you make *both* types.

**Comment by Dream-Master** [comment]
yes thats what i removed.
