### ISSUE TITLE
White bee quest should be winter+diligent

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5146]
quest currently shows forest+diligent

**Comment by Dream-Master** [comment]
No
![image](https://user-images.githubusercontent.com/2970688/70373664-48bd4980-18ea-11ea-8086-948fd96610d3.png)

**Comment by richardhendricks** [comment]
OK, I guess it is fixed in 2.0.8.0

*excitement intensifies*
