### ISSUE TITLE
TiCo Lumberaxe crashed game when cutting down Ghostwood Tree in the Nether

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#5148]
#### Which modpack version are you using?
2.0.8.0b
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Tried to cut down a Ghostwood Tree in the Nether,
#
#### What happened instead? (Attach screenshots if needed)
Crashed with following report:
https://pastebin.com/w0vcDpzJ

**Comment by Dream-Master** [comment]
@mitchej123 can you check this. I rember you fix some other axe issues before. Thanks

**Comment by mitchej123** [comment]
This is the same error I've seen periodically, but I haven't been able to reproduce locally.  If someone can give me a method to reliably reproduce I'm happy to fix.

```
java.lang.LinkageError: loader (instance of  cpw/mods/fml/common/eventhandler/ASMEventHandler$ASMClassLoader): attempted  duplicate class definition for name: "cpw/mods/fml/common/eventhandler/ASMEventHandler_2115_TreeChopTask_onWorldTick_WorldTickEvent"
```

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/TinkersConstruct/pull/15

Can't reproduce locally so I can't test if it fixes it.

**Comment by Dream-Master** [comment]
we put this on zeta and will see.
@mitchej123 thanks for try to fix it.
