### ISSUE TITLE
Perditio Requires Redstone Mining Level?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#5155]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Mining Thaumcraft ores. All of the other aspect ores only require Tin level. Perditio requires Redstone level. Is that intended?
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Either change Perditio to Tin or all  the other 5 aspects to Redstone so it is consistent?

**Comment by Dream-Master** [comment]
sure

**Comment by draknyte1** [comment]
IIRC Perditio tools are a higher mining level.

**Comment by Dream-Master** [comment]
yes but i can put all other aspect to this level. When you can enter twilight mining level is no problem anymore.

**Comment by draknyte1** [comment]
No, like, it’s tiered higher because it gives you tools a tier higher. It’s correctly tiered as is compared to the other five shard types.

**Comment by Dream-Master** [comment]
So why it is higher tiered. @draknyte1 ?

**Comment by draknyte1** [comment]
If all crystals produce mining level 2 tools, perditio produces level 3.. its balanced as is, being my point. 

Iirc Perditio tools have horrible durability to balance their slightly better mining level.

**Comment by Dream-Master** [comment]
So you suggest let the mining level like it is @draknyte1  ?

**Comment by draknyte1** [comment]
Well that’s the ‘bonus’ to that aspect. Like terra stuff has the most durability. Etc. 

It’s handy early game as it can mine obsidian (iirc) but doesn’t have many uses.

**Comment by Dream-Master** [comment]
@shawnbyday ok we let the mining level like it is. Greg had an idea why tiering it like that.

**Comment by richardhendricks** [comment]
Perditio tools are also crazy fast, so it makes sense for them to be a little tougher to obtain.
