### ISSUE TITLE
tin item pipe not harvestable

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5156]
#### Which modpack version are you using?

2.0.8.0a

#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I tried wrenching a small tin item pipe with a steel and with an iron wrench. It even says that it is harvestable.

#
#### What happened instead? (Attach screenshots if needed)

nothing. I does not break.

Furthermore: bot☢ on discord was able to reproduce it. He then tried it with a neutronium wrench which did work.

![2019-12-08_14 18 42](https://user-images.githubusercontent.com/40274384/70390989-036f4980-19c8-11ea-91ff-f85989032ad0.png)

#
#### What do you suggest instead/what changes do you propose?

fix the bug. I don't know if other pipes have the same problem (but wood and bronze work fine)

**Comment by botn365** [comment]
neutronium wrench dit break item pipe

**Comment by chochem** [comment]
Further testing results in the follwing:

- the problem is still there on 2.0.8.0b
- tin item pipes of other sizes have the same problem
- brass item pipes work fine
- higher tier wrenches like energetic alloy or ardite work fine

**Comment by Dream-Master** [comment]
guess tin have a higher item level. But steel must work
