### ISSUE TITLE
Unable to use the Basic mixer to make redstone alloy dust

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#516]
It worked fine last night, but now it only makes Red Silicon Compound and ignores the coal dust.

**Comment by ProsperCraft** [comment]
Shapeless works.

**Comment by Dream-Master** [comment]
If it not work i have to fix it somehow. Not sure if this is a recipe i put directly in gt code or if it is a minetweaker script.

**Comment by Dream-Master** [comment]
Its code wise.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L101

**Comment by Dream-Master** [comment]
Both recipe works for me. need to be tested on the Server.

**Comment by Dream-Master** [comment]
Yes understand now. First you can make redalloy but when you make Silicon Compound one time it is impossible to make Redalloy again. The machine need to be replaced.
I will change those recipe.
