### ISSUE TITLE
Ultimate battery( and really ultimate) recipes aren't consistent with previous batterys recipes.

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/NewHorizons#5162]
#### Which modpack version are you using?
DEV 2.0.8.0.b   singleplayer
#

#### What do you suggest instead/what changes do you propose?
The recipe for the ultimate battery contains 4 circuits in the same slot, whereas the energy module (ZPM) and the energy cluster (UV) have 4 circuits across 4 slots.
I think the recipe should be changed to require the 4 circuits across 4 slots for consistancy.
There is the same issue with the really ultimate battery (UMV-tier)
![image](https://user-images.githubusercontent.com/57050655/70400037-ba9bad00-1a28-11ea-9974-aa6cd16190f4.png)

![image](https://user-images.githubusercontent.com/57050655/70400026-a9eb3700-1a28-11ea-80ce-24ce8e4c9b33.png)

**Comment by septemberWaves** [comment]
So the issue is that it requires a smaller assembly line than previous battery tiers?

**Comment by Alexdoru** [comment]
exactly

**Comment by 0lafe** [comment]
Unless you're wasting asslines, the length would still need to be larger to do other recipes. The cost of an assline is also essentially free by the point you're making ultimates

**Comment by Dream-Master** [comment]
`` GT_Values.RA.addAssemblylineRecipe(ItemList.Energy_LapotronicOrb2.get(1), 288000, new Object[]{
                GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Europium, 16L),
                new Object[]{OrePrefixes.circuit.get(Materials.Ultimate), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Ultimate), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Ultimate), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Ultimate), 1},
                ItemList.Energy_LapotronicOrb2.get(8L),
                ItemList.Field_Generator_LuV.get(2),
                ItemList.Circuit_Wafer_SoC2.get(64),
                ItemList.Circuit_Wafer_SoC2.get(64),
                ItemList.Circuit_Parts_DiodeSMD.get(8),
                GT_OreDictUnificator.get(OrePrefixes.cableGt01, Materials.Naquadah, 32)},
                new FluidStack[]{
                Materials.SolderingAlloy.getMolten(2880), new FluidStack(FluidRegistry.getFluid("ic2coolant"), 16000)},
                ItemList.Energy_Module.get(1), 2000, 100000);

        GT_Values.RA.addAssemblylineRecipe(ItemList.Energy_Module.get(1), 288000, new Object[]{
                GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Americium, 32L),
                new Object[]{OrePrefixes.circuit.get(Materials.Superconductor), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Superconductor), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Superconductor), 1},
                new Object[]{OrePrefixes.circuit.get(Materials.Superconductor), 1},
                ItemList.Energy_Module.get(8L),
                ItemList.Field_Generator_ZPM.get(2),
                ItemList.Circuit_Wafer_HPIC.get(64),
                ItemList.Circuit_Wafer_HPIC.get(64),
                ItemList.Circuit_Parts_DiodeSMD.get(16),
                GT_OreDictUnificator.get(OrePrefixes.cableGt01, Materials.NaquadahAlloy, 32),},
                new FluidStack[]{
                Materials.SolderingAlloy.getMolten(2880),
                new FluidStack(FluidRegistry.getFluid("ic2coolant"), 16000)},
                ItemList.Energy_Cluster.get(1), 2000, 200000);``

**Comment by Dream-Master** [comment]
The code is the same just a visual thing with nei
