### ISSUE TITLE
plunger 2.0 The Hand Pump -  quest wrong

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5170]
#### Which modpack version are you using?
2.0.8.0b
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
do the quest
#
#### What happened instead? (Attach screenshots if needed)
the items in the quest are outdated. They do not give the token for the hand pump in the assembler.
Circuits are no longer needed but instead aluminium bolts I think.
#
#### What do you suggest instead/what changes do you propose?
Change the quest.

**Comment by chochem** [comment]
the recipe was changed to be unique and have no overlap with the fluid regulator. So the recipe is good now but the quest wasnt updated

**Comment by daddy77gaming** [comment]
playing in version 2.0.8.3 guess thats post this issue and supposed fix?

Quest does not ask for a fluid regulator

![image](https://user-images.githubusercontent.com/31905330/74028295-450d7800-49aa-11ea-92fd-4f5ecc9648a3.png)
![image](https://user-images.githubusercontent.com/31905330/74028354-60788300-49aa-11ea-8e2a-389d77e4f11c.png)
