### ISSUE TITLE
Fluid regulator texture wrong

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/NewHorizons#5171]
#### Which modpack version are you using?
2.0.7.5
#### If in multiplayer; On which server does this happen? 
Eta

For some reason the ZPM and UV fluid regulators have their textures the wrong way round, ZPM should be light blue and UV green so it is in line with the normal pump textures as shown below.

<img width="406" alt="Screenshot 2019-12-11 at 12 43 37" src="https://user-images.githubusercontent.com/54497873/70622464-e29b3400-1c13-11ea-8783-0a9cde50527c.png">
<img width="710" alt="Screenshot 2019-12-11 at 12 43 20" src="https://user-images.githubusercontent.com/54497873/70622465-e29b3400-1c13-11ea-8c26-64b41b40468b.png">

**Comment by DualBallers** [comment]
Duplicate here https://github.com/GTNewHorizons/NewHorizons/issues/4004 and here https://github.com/GTNewHorizons/GT5-Unofficial/pull/204
