### ISSUE TITLE
maybe add on test server zeta for test? WarpDrive mod

### ISSUE THREAD

**Issue by DarkGaterau** [GTNewHorizons/NewHorizons#5173]
https://www.curseforge.com/minecraft/mc-mods/warpdrive
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2510855-warpdrive-custom-ships-laser-cannons-and-modular

This mod brings Warp Drive and similar Science fiction technologies to minecraft included but not limited to resource collection (mining asteroids in space), transportation (move your team or your whole base across dimensions), and combat (fight against other ships and bases with laser cannons or other mods) or mine resurces whith mining lasers

**Comment by Anarack** [comment]
Pvp isn't really a thing in this pack.
Have asteroid mining.
Can move stuff across dims via ae2 spacial stuff.

**Comment by DarkGaterau** [comment]
> Pvp isn't really a thing in this pack.
> Have asteroid mining.
> Can move stuff across dims via ae2 spacial stuff.

you can move base across dims

**Comment by Anarack** [comment]
Entire bases is included in "stuff".

**Comment by DarkGaterau** [comment]
whell this mod also god for pve game/ for example you boring stay in one place you can move all base in other place. mining whith setup offset level and can also mine whith silktouch

**Comment by bartimaeusnek** [comment]
I vote no, since we got all the featues already and this would just add clutter and loading times.
In addition to that, it is ARR licensed, which is a big NO for me.

**Comment by Dream-Master** [comment]
if the mod isn't open source I vote for no also.

**Comment by DarkGaterau** [comment]
https://github.com/Cr0s/WarpDrive

**Comment by richardhendricks** [comment]
The point is not that the source code isn't available, the point is that the original authors have marked it as ARR.

![image](https://user-images.githubusercontent.com/1214811/70643188-2f780e00-1c06-11ea-90b1-5a86e50f8a6e.png)

**Comment by bartimaeusnek** [comment]
@richardhendricks is that a no from you aswell? then ill close this issue, feel free to reopen if you feel otherwise.
