### ISSUE TITLE
Sulfuric Acid quest in LV gives incorrect instuctions

### ISSUE THREAD

**Issue by MaxsimalPD** [GTNewHorizons/NewHorizons#5174]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
The quest says that sulfur and water in a chemical reactor will produced sulfuric acid.  This isn't the case.   

#
#### What happened instead? (Attach screenshots if needed)
Nothing got made.

#
#### What do you suggest instead/what changes do you propose?
Either make sulfur+water produced sulfuric acid, or change the quest text.  If going for the latter, then we probably need a quest to make oxygen first, since you need to use oxygen gas + sulfur -> Sulfur Dioxide + More Oxygen -> Sulfur Trioxide.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71313722-e7928b80-243c-11ea-8f27-579ddc03c1b0.png)
Dev version allready updated

**Comment by Dream-Master** [comment]
After you oil production you have so much sulfuric acid you have some spare to do the recipes. Maybe i add additional info.
