### ISSUE TITLE
Solar Boiler WAILA option now available

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5187]
@mitchej123 I have added a getCalcificationOutput to the solar boiler base class that can be used for WAILA reporting.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/19acdbddcc7c560890dde3eb8053cf66adc91b05/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Solar.java#L118

**Comment by KaneHart** [comment]
Thanks for all these little tweaks :) I always love them

**Comment by Dream-Master** [comment]
@richardhendricks so this is fixed/new future ?

**Comment by richardhendricks** [comment]
Mitch's new commit should take care of it.
