### ISSUE TITLE
Add info on Nether/End fluids to Fluids drilling rig quest

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5188]
Moon/Mars fluids are already talked about but we don't have fluids info for Nether and End. Add to fluid drilling rig quest.

**Comment by botn365** [comment]
there should also be info on barts planet fluids
ross128b is
max 625 very heavy oil
max 32767 lava
max 625 refinery gas

ross128ba is
max 1250 helium-3
max 1250 salt water

**Comment by richardhendricks** [comment]
Actually, looking at the current config file, the End and Nether are blacklisted for fluids. So no underground fluids in the Nether or End.
