### ISSUE TITLE
Callisto Ice is not consistent

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/NewHorizons#5195]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Found in SP, should be the same in MP
#
#### What happened?
Various Callisto Ice blocks/items from the GTNH-coremod (GregTech is fine) are not consistent. Generally the name would be "Callisto Ice *" with the oreDict-entry `*CallistoIce`. There are however some blocks/items, that are named "Callisto Cold Ice *" and/or have the oreDict-entry `*ColdCallistoIce`:
- "Callisto Cold Ice Ingot" with `ingotColdCallistoIce`, which has no uses.
- "Callisto Cold Ice Block" with `blockCallistoIce`, which is made out of normal `ingotCallistoIce` and is the only way to obtain
- "Callisto Cold Ice Plate" with `plateColdCallistoIce`, which can be only used for the Gravitation Suit's "Cooling Core".
- "Dense Callisto Cold Ice Plate" with `plateDenseCallistoIce`.

#
#### What do you suggest instead/what changes do you propose?
Changing all those names to the standard "Callisto Ice *" and changing all those oreDict-entries to `*CallistoIce`. The "Cooling Core"-recipe has to be changed to accept `plateCallistoIce`. Finally, the recipe of "Callisto Cold Ice Plate", which uses IC2 Coolant instead of Lubricant or (Distilled-)Water, has to be removed, as it is then redundant.

**Comment by Dream-Master** [comment]
Most of them are removed in Dev version. This are artefacts from older versions with no gt material callisto ice.

**Comment by Dream-Master** [comment]
Only callisto cold ice plate will stay the rest is removed/unused/obsolete.
