### ISSUE TITLE
D-O-B Invalid output

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5199]
2.0.8.0
Produces a invalid.name item from gendustry. Not sure how long it has been like this, may be relate to moving from gendustry bees.
![2019-12-20_13 54 43](https://user-images.githubusercontent.com/20565115/71288308-5209d580-2330-11ea-8f45-9635fe530dae.png)

**Comment by Dream-Master** [comment]
seems to be a old drop. Will check.
