### ISSUE TITLE
[Suggestion] Warm Blood as coin reward

### ISSUE THREAD

**Issue by Saika-Takehiko** [GTNewHorizons/NewHorizons#5205]
I'd like to suggest adding "Warm Blood 7286:163" As a "coin, coin, coin" reward. It's currently an un-craftable item from the witchery series. Whereas it gives vampires; 2 free blood drops (food in vampiric terms). It would help out vampires in the public servers as the only other way to get blood is from villagers. (Villagers have 4 blood drops and you can only drink to half or they'll take damage) The only way for the villagers to replenish their blood drops is through sleeping an entire night (does not replenish if they do not sleep the entire night cycle from what I've been testing)  which can be difficult when other players are online and want day times for various reasons.

**Comment by Dream-Master** [comment]
it has a crafting recipe in 2.0.8.0

**Comment by Saika-Takehiko** [comment]
> it has a crafting recipe in 2.0.8.0

Well then, I'll be expecting it soon then.

**Comment by richardhendricks** [comment]
Also a cookie arrow allows you to double the # of villagers quite easily.
