### ISSUE TITLE
Quests Not Working in 2.0.8.0 2.0

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/NewHorizons#5206]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
**The following quests aren't detecting (will add quest ID's when I get my tooltips working):**
_Quest ID, Quest Name, Quest Item, Quest Tab_
- [x] Quest ID 809 - NASA Workbench aka Dire Crafting Table (Electric Piston (HV), Robot Arm (HV)) [Space Race]
- [x] Quest ID 819 - Small Fuel Canister (Blank Fuel Tank, Small Fuel Canister) [Space Race]
- [x] Quest ID 1371 - LOX and Bagels (Filled Canister of Liquid Oxygen) [Space Race]
- [x] Quest ID 821 - Rocket Fuel (Electric Pump (HV), Large Steel Fluid Cell) [Space Race]
- [x] Quest ID 810 - Rocket Tier 1 (Small Fuel Canister) [Space Race]
- [x] Quest ID 918 - Skeleton: Evolved (Dimension: Moon, Kill Evolved Skeleton Boss) [Kill all the things] - Also quest gives T2 coins...should it maybe give T3?
- [x] Quest ID 1739 - Farming a little easier (Robot Arm (HV)) [Tier 4 - 512 EU (HV)]
- [x] Quest ID 1012 - Rutile (Advanced Thermal Centrifuge II) [Tier 4 - 512 EU (HV)]
- [x] Quest ID 781 - Still not enough charcoal? (Pyrolyse Oven) [Multiblock Goals]
- [x] Quest ID 768 - You smell like a distillery! (Distillation Tower) [Multiblock Goals]
- [x] Quest ID 1781 - Traveller's Gear (Electric Piston (HV)) [Armors and Jetpacks]
- [x] Quest ID 1012 - Rutile (Advanced Thermal Centrifuge II) [Tier 4 - 512 EU (HV)]
- [x] Quest ID 784 - It's time to get more steam (Maintenance Hatch, Muffler Hatch (LV)) [Multiblock Goals]
- [x] Quest ID 766 - Let's get crackin! (Maintenance Hatch) [Multiblock Goals]

**Comment by skeblow** [comment]
Also

- Quest ID 1412 - Ass line (Maintenance hatch, Data access hatch) [Multiblock goals]
- Quest ID 1880 - Field generator (Field generator Tier II) [Tier 5 - 2048 EU (EV)]

**Comment by richardhendricks** [comment]
I am doing quest changes right now, please hold off on any mods to the quest file until my PR

**Comment by richardhendricks** [comment]
ok changed all the quests to ignore nbt
