### ISSUE TITLE
Some Circuit Recipes are wrong.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5209]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private server and single
#
#### What did you try to do, and what did you expect to happen?
I confirmed the circuit recipe.
#
#### What happened instead? (Attach screenshots if needed)
Some Circuit Recipes are wrong.
The following circuit recipe was wrong as far as I confirmed.
・Nanoprocessor(Cheap recipe only)
・Quantumprocessor(Cheap recipe only)
・Crystalprocessor
・Crystalprocessor Assembly
・Ultimate Crystalcomputer
・Crystalprocessor Mainframe
・Wetwareprocessor
・Wetwareprocessor Assembly
・Wetware Supercomputer
・Bioprocessor
・Bioprocessor Assembly

![2019-12-23_17 46 44](https://user-images.githubusercontent.com/40425798/71347673-1d0ab680-25ae-11ea-9b8a-259badd593b8.png)
![2019-12-23_17 46 47](https://user-images.githubusercontent.com/40425798/71347674-1d0ab680-25ae-11ea-826b-287890e8e5ae.png)
![2019-12-23_17 47 06](https://user-images.githubusercontent.com/40425798/71347675-1da34d00-25ae-11ea-9ea7-3628802aea50.png)
![2019-12-23_17 47 14](https://user-images.githubusercontent.com/40425798/71347676-1da34d00-25ae-11ea-905b-340170432743.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
The recipes look ok in the code so something went wrong here. 
@bartimaeusnek @richardhendricks @Technus @basdxz @mitchej123 
Need help with this.

**Comment by bartimaeusnek** [comment]
@yukieiji make the circuit one time, make an imprint from it, then use the Circuit Assembly Line instead. As you can see, these circuits are LuV+, so is the Circuit Assembly Line.

**Comment by ScriptedPiky** [comment]
So to explain this. From what I recall, this was intentional to force the use of the Circuit Assembly Line for newer circuits. So that the player crafts a circuit, puts it through a slicer, and then uses it alongside or inside the Circuit Assembly.

And any circuit above the voltage of IV will have its resources increased to 64 in all slots, except when used in the Circuit Assembly, hence the requirement of using the multiblock for higher tier circuits. However, there are currently some issues or certain skips that can be done with this multiblock and from what I'm assuming is SoC wafer skips and other certain circuits (Quantum and Wetwares mostly).

**Comment by yukieiji** [comment]
It is necessary to make a large number of circuits to make a QuantumComputer or a ResearchStation, and automation of the circuit assembler is essential.but CircuitAssemblyLine has only one Circuit Imprint and is difficult to automate.
So I think that it is necessary to be able to exchange or putting multiple Circuit Imprints by some means.

**Comment by 0lafe** [comment]
From what I can tell, there's ways to have CA's run multiple recipes through swapping controllers

**Comment by yukieiji** [comment]
If it is assumed that multiple CircuitAssemblyLines are build, this recipe is a little difficult.

**Comment by bartimaeusnek** [comment]
@yukieiji ZPM is the second last official tier, making multiple rather cheap multis shouldnt be a big deal in that age.

**Comment by 0lafe** [comment]
If you change the stupid 16x multiplier, people will need to make multiples anyway for the speed aspect

**Comment by koiNoCirculation** [comment]
[https://github.com/GTNewHorizons/NewHorizons/issues/5217](Circuit Assembly Line Does Not Work)
Yes, this shit doesn't work, we need  recipes in 2075.

**Comment by yukieiji** [comment]
In GTNH ver2.0.8.1, using CircuitAssemblyLine didn't reduce the cost of these circuits.
![2020-01-17_22 23 35](https://user-images.githubusercontent.com/40425798/72615896-0ff8a180-3979-11ea-9fd1-8922bb9754f9.png)
![2020-01-17_22 28 58](https://user-images.githubusercontent.com/40425798/72615900-1424bf00-3979-11ea-9ff8-e83614f45b76.png)
.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by Dream-Master** [comment]
fixed i guess. If not reopen pleaase.
