### ISSUE TITLE
Galacticraft Biome in the Nether

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#521]
Player Shiitake (Minecraft froum) report this.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2391339-gtnewhorizons-gregified-modpack-minetweaker-gt?page=8#c142

"Oh, huh, why is the mars biome showing up in the nether? Is that on purpose? It kindof makes sense..."

**Comment by Dream-Master** [comment]
Ok i change the Biome ID to 141(moon) 142(mars) 143 (asteroids)

**Comment by Teteros** [comment]
This is in master (1.0.7.7m) since 8f0053c8c134ace3235a2e536c003c3f638b1fff, can it be closed?

**Comment by Dream-Master** [comment]
yep sure.

**Comment by PaladinOne** [comment]
I also just found Venus in the Overworld. Looks to be another ID conflict with BOP.

**Comment by Dream-Master** [comment]
No with Galaxy Space Mod. Id cant be configured atm. Waiting for new Version.
