### ISSUE TITLE
Ember Mobs destroy Soulbound items

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#5215]
#### Which modpack version are you using?
1.7.xxx
exists in latest release as well
#
#### If in multiplayer; On which server does this happen? 
eta

#
#### What did you try to do, and what did you expect to happen?
When fighting a Ember mob, if you die to it, the Adventure Backpacks and other soulbound items will be destroyed and not placed in a grave or left on the body

#
#### What do you suggest instead/what changes do you propose?
Recommend Ember Mob (Blaze type) be removed

**Comment by richardhendricks** [comment]
Another player on the officials fought Ember and no grave spawned. Issue needs to be addressed ASAP

**Comment by draknyte1** [comment]
Someone’s calling entity.setHealth() 😒

Think it’s worth me writing up a debug option that dumps all bad usage cases of said function? Nothing outside of forge, really, should be doing it.

**Comment by richardhendricks** [comment]
Comments from 
![Screenshot_20191223-151133_Discord](https://user-images.githubusercontent.com/1214811/71382781-a6ae8a00-2596-11ea-87b2-240d156a673b.jpg)

**Comment by bartimaeusnek** [comment]
moved -> 2.0.8.1, its not a critical / game breaking bug, but this requires more effort.

**Comment by richardhendricks** [comment]
@draknyte1 is doing an ASM fix that should redirect all sethealth calls to appropriate functions

**Comment by richardhendricks** [comment]
OK, the setHealth call in the emberentity is not what's causing the graves not to spawn. Or at least not the *only* thing.

Tested with 
```java
    /// Overridden to modify attack effects.
    @Override
	protected void onTypeAttack(Entity target) {
    	if (target instanceof EntityLivingBase) {
    		//((EntityLivingBase) target).setHealth(((EntityLivingBase) target).getHealth() - 2.0F);

    		DamageSource g = new DamageSourceEmber();
            target.attackEntityFrom(g, 30.0F);   
    	}
    }

    public static class DamageSourceEmber extends DamageSource {
        public DamageSourceEmber() {
            super("cooked");
            setDamageAllowedInCreativeMode();
            setDamageBypassesArmor();
            setDamageIsAbsolute();
        }

        @Override
        public IChatComponent func_151519_b(EntityLivingBase aTarget) {
            return new ChatComponentText(EnumChatFormatting.RED + aTarget.getCommandSenderName() + EnumChatFormatting.WHITE + " cooked from the inside out");
        }
    }
```

**Comment by richardhendricks** [comment]
ugh, stupid openblocks won't place a grave if the inventory is empty. Redoing some tests

**Comment by richardhendricks** [comment]
ok think I got it figured out. Working.

**Comment by richardhendricks** [comment]
OK, so my change is

```java
    /// Ember's specialty is that it has no fireball attacks, only melee
    /// And those melee attacks bypass armor to directly set you on fire inside-out
    @Override
    public boolean attackEntityAsMob(Entity target) {
        this.onTypeAttack(target);
        return true;
    }
    
    /// Overridden to modify attack effects.
    @Override
	protected void onTypeAttack(Entity target) {
    	if (target instanceof EntityLivingBase) {
    		DamageSource g = new DamageSourceEmber();
            target.attackEntityFrom(g, 4.0F);
    	}
    }

    public static class DamageSourceEmber extends DamageSource {
        public DamageSourceEmber() {
            super("cooked");
            setDamageAllowedInCreativeMode();
            setDamageBypassesArmor();
            setDamageIsAbsolute();
        }

        @Override
        public IChatComponent func_151519_b(EntityLivingBase aTarget) {
            return new ChatComponentText(EnumChatFormatting.RED + aTarget.getCommandSenderName() + EnumChatFormatting.WHITE + " cooked from the inside out");
        }
    }
```

This is slightly different than the original implementation. Ember will bypass potions and armor to do direct damage to the player, 2 hearts worth. This will no longer prevent grave spawning either.
