### ISSUE TITLE
CircuitAssemblyLine don't work

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5217]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private test server
#
#### What did you try to do, and what did you expect to happen?
I tried to make Crystalprocessor and Wetwareprocessor with CircuitAssemblyLine.
#
#### What happened instead? (Attach screenshots if needed)
I couldn't make circuit.

The following is the SS when trying to make a Crystalprocessor.
・ Imprinted Circuit
![2019-12-24_20 19 30](https://user-images.githubusercontent.com/40425798/71412655-fe7deb80-2691-11ea-82e4-9b8b095646af.png)
・Use CircuitAssemblyLine
![2019-12-24_20 20 32](https://user-images.githubusercontent.com/40425798/71412582-b6f75f80-2691-11ea-9641-53302d112403.png)
![2019-12-24_20 19 09](https://user-images.githubusercontent.com/40425798/71412570-aa730700-2691-11ea-9b4c-9640b04a90d0.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by bartimaeusnek** [comment]
as you can see, the imprint was not consumed, therefore the line is not imprinted. im not quite sure whats causing this issue at your side, will take a look at it.

**Comment by yukieiji** [comment]
This Imprinted Circuit isn't made in Creative Mode, but is made by slicing the processor taken out by Creative Mode.
Imprinted Circuit consumed but didn't run properly when tested outside of the clean room....

**Comment by richardhendricks** [comment]
CAL does not need to be inside clean room.

**Comment by yukieiji** [comment]
I tested CAL outside Cleanroom but it didn't work....
![2019-12-26_16 18 27](https://user-images.githubusercontent.com/40425798/71464126-ede98480-27fb-11ea-84a5-d443c8d18fef.png)

**Comment by bartimaeusnek** [comment]
im pretty sure you did something wrong then, multis cant even detect wether they are in a cleanroom or not

**Comment by yukieiji** [comment]
The materials and the server used are as follows. Is there anything wrong?
Also, the following materials consumed the Imprinted Circuit only once when enable, but did not execute...

8 4xNiobium-Titanium Wires are in the ULV input bus.
・Server:Contigo-1.7.10-1614.UNOFFICIAL-server
![2019-12-26_23 55 37](https://user-images.githubusercontent.com/40425798/71480428-4d678480-283c-11ea-84cc-574e7388ef27.png)
![素材](https://user-images.githubusercontent.com/40425798/71480435-535d6580-283c-11ea-9307-3317ad1b6b29.png)
![2019-12-26_23 59 17](https://user-images.githubusercontent.com/40425798/71480418-4771a380-283c-11ea-8ac8-ecf5274aaa0e.png)

**Comment by botn365** [comment]
it wont work becous the imprint is "epic bacon" not the circuit you want to make

**Comment by yukieiji** [comment]
No matter how many times I make it, it will be Epic Bacon's Imprintcircuit....
![2019-12-27_00 31 51](https://user-images.githubusercontent.com/40425798/71481309-b0f3b100-2840-11ea-9269-e95666878161.png)
![2019-12-27_00 32 40](https://user-images.githubusercontent.com/40425798/71481310-b0f3b100-2840-11ea-8a8e-3c346984a487.png)

**Comment by 5lx** [comment]
The NBT of the generated Imprinted Circuit is wrong.
6918:32089 is not the GT circuit.
I tried to modify the NBT data to the 6856:32089,
then everything works great.

**Comment by bartimaeusnek** [comment]
The NBT data seems to change with world load, or more precise, the ItemIDs shift. I need to investigate whats causing this issue.

**Comment by yukieiji** [comment]
This issue didn't occur with ver2.0.8.0Pre2(bartworks.1.7.10-0.5.3_f1) single.
But, the recipe display of NEI didn't match between CircuitImprint and SliceCircuit.

・ the recipe display of NEI
![2019-12-31_14 25 30](https://user-images.githubusercontent.com/40425798/71611047-6d4ecd80-2bd9-11ea-9135-0f2df07742e3.png)
![2019-12-31_14 25 33](https://user-images.githubusercontent.com/40425798/71611048-6de76400-2bd9-11ea-9697-c7dab776d990.png)

**Comment by yukieiji** [comment]
SliceCircuit couldn't be made successfully when tested on an existing world(playing with ver2.0.7.5) with ver2.0.8.0Pre2 (bartworks.1.7.10-0.5.3_f1)....
But when I created a new world it worked fine.

・NEI recipe of the existing world that was playing with ver2.0.7.5
![2020-01-06_00 49 06](https://user-images.githubusercontent.com/40425798/71782725-b7441300-3020-11ea-9cf5-5b94c063c38d.png)
・NEI recipe of new world created with ver2.0.8.0
![2020-01-06_01 08 03](https://user-images.githubusercontent.com/40425798/71782755-09853400-3021-11ea-8cc1-7d7d8f0cc672.png)

**Comment by yukieiji** [comment]
When tested with bartworks.1.7.10-0.5.6, it was fine on NEI, but could not make SlicedCircuit with existing world(the world created before ver2.0.8.0).

![2020-01-10_00 54 44](https://user-images.githubusercontent.com/40425798/72083417-241f1c00-3345-11ea-9eb5-cc6899690adc.png)

**Comment by yukieiji** [comment]
This happened in the Creative Circuit, not in Circuit what already created.

**Comment by bartimaeusnek** [comment]
yukieiji can you make a video of what you did? i can not recreate this.

**Comment by yukieiji** [comment]
@bartimaeusnek [SlicedCircuit Missing](https://www.youtube.com/watch?v=N2NYN815dho&feature=youtu.be)
In addition, after conducting some tests, I found that SlicedCircuit wasn't made successfully only when entering the world that created before ver2.0.8.0 for the first time after updating.
After creating this video, if I re-enter the world, I was able to make it well...
