### ISSUE TITLE
Thaumcraft wand inconsistencies

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5218]
#### Which modpack version are you using?
2.0.7.5
#
While looking through the wands I noticed some things;
1) Unlike other staffs and staffters of it's tier, the Amber staffer uses Stainless Steel+Lich Bones, when it should be Titanium+Fiery Blood.
2) Similarly, the Warpwood staffter uses Tungstensteel+Fiery Tears, but should be Chrome+Carminite to match others of similar tiers.
3) The Blood (not blood infused wooden) and Witchwood staffs and staffters appear to have the wrong capacity set, being both 50 (staff) and 75 (staffter). Others of the same capacity (100) all have 100/150/250/375 (wand/scepter/staff/staffter) capacity, so this is likely a typo on these two.
4) Eldritch, Profane, and Tainted wand cores can't be used to make a wand. Tainted can be crafted, and I think you trade for profane? I think Eldritch is a crossmod Ars Magica 2 wand core, but doesn't have a recipe.
#
#### What do you suggest instead/what changes do you propose?
Change the recipes of the first two to be consistent with the rest of the wand recipes. Change the capacity of the Blood and Witchwood to be consistent. I don't really care about the three unused ones, and they can be pushed off till 2.0.8.1 or later anyway.

**Comment by Dream-Master** [comment]
Change a recipe I can do easy but change capacity need code changes and I am not sure if I can change it.

**Comment by Prometheus0000** [comment]
I figured it would just be a matter of adding a 2 and 3 for the code change, but if it's more complicated, well, I don't think anyone really cares that much about staffs of these wands anyways.

**Comment by Prometheus0000** [comment]
BTW they're both from Forbidden Magic if someone else wants to look, but personally I couldn't even tell where it sets the capacities when I looked at the code.

**Comment by Dream-Master** [comment]
well at the end it's calculated in thaumcraft I guess but the add-on mod set the values

**Comment by Methes** [comment]
Not sure about other wands but the Amber Staff has fairly low capacity - 37 Vis. So I guess it's consistent in that regard that it uses stainless (same as greatwood).

**Comment by Prometheus0000** [comment]
Staffs/"Staffters" below Tungstensteel (aside from amber) require Tier+1 materials, while Staffs/"Staffters" at Tungstensteel and above (aside from warpwood)  require Chrome Screws/Carminite. So they're not consistent with the rest. 
Amber wands also recharge to full fairly fast, so they're good for repair/runic shielding batteries, which is what a staffter is basically.

**Comment by Prometheus0000** [comment]
I just noticed that in pre2.0.8.0 the chrome screws (for staffs/"staffters") have all changed to be iridium screws, so warpwood should be iridium instead.

**Comment by richardhendricks** [comment]
@Zoko061602 Is this ticket closed? Has these changes been addressed in 2.0.8.3?

**Comment by Zoko061602** [comment]
@richardhendricks  I was unable to test the changes I made to the wand mod, so I didn't do a pull-request,

**Comment by Dream-Master** [comment]
@Zoko061602 should i merge your changes and put a test build on zeta?
BTW why you not on Discord anymore ?

**Comment by Dream-Master** [comment]
[GTNH-TC-Wands-1.1.0.zip](https://github.com/GTNewHorizons/NewHorizons/files/4147123/GTNH-TC-Wands-1.1.0.zip)
@Prometheus0000 us this file and test please 
Thanks

**Comment by Prometheus0000** [comment]
Crash on startup 
[crash-2020-02-03_07.46.01-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4147919/crash-2020-02-03_07.46.01-client.txt)

**Comment by Zoko061602** [comment]
I think that should fix it
GTNewHorizons/GTNH-TC-Wands/pull/4

**Comment by Dream-Master** [comment]
@Zoko061602 i add your pull and get a crash too
[crash-2020-02-03_23.08.53-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4150450/crash-2020-02-03_23.08.53-client.txt)

**Comment by Dream-Master** [comment]
@Zoko061602 i need your help here what went wrong why it crash ?
