### ISSUE TITLE
[Recipes missing] Extract fluid from cryotheum / pyrotheum dust in 2.0.8.0

### ISSUE THREAD

**Issue by 5lx** [GTNewHorizons/NewHorizons#5219]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Recipes to extract fluid from cryotheum / pyrotheum dust is missing in 2.0.8.0
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
If this is a bug, please fix it.

**Comment by botn365** [comment]
this is fixid in a later version of gt++

**Comment by 5lx** [comment]
Do you mean the GT++ version > 394?

**Comment by botn365** [comment]
yep but the problem with the later versions 405+ is that no gt++ multies work
\

**Comment by 5lx** [comment]
OK I got. Thank you for the explanation.
I'll try to add back the recipes as a work around for now.
