### ISSUE TITLE
GT Steam efficiency can't be changed via cfg

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#522]
Player Shiitake (Minecraft Forum ) report this.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2391339-gtnewhorizons-gregified-modpack-minetweaker-gt?comment=138

I copy all text here.

"What's with the steam efficiency on the basic turbine? It says 120%, and by my understanding the base ratio is 2mb steam to 1 EU, so it should actually require 1.67mb steam per EU. However, the red alloy plate recipe in the basic bending machine consumes slightly more than 24000 steam(just enough to stop short if you try to make a plate with a full turbine and no reserve steam or active boiler), despite claiming to use 10512 EU. This looks more like it's 2.5mb steam per EU, which would be due to having a base ratio of 3mb steam per EU. It's also possible it's 2 to 1, but the efficiency rating is backwards so it takes 20% MORE steam, resulting in 2.4mb per EU?

Edit: Okay, I ran an experiment. I disconnected the turbine from my steam pipes, then measured how much steam it took to make a steel plate. 4284. The recipe says it requires 1344 EU. That means the conversion rate on a basic steam turbine is 3.1875mb steam per EU. I uh... don't know why. That is an odd fraction.
Copper plate recipe uses 4896 steam. The ratio there is about 3.238. I'm guessing that it's 3mb per EU, but there's additional waste that depends on the number of ticks the recipe lasts, or something? Or maybe it's really supposed to be 1.67mb per EU but something is screwing everything up and wasting half of it."
______________________________

"No matter how I change the config, it always uses the same amount of steam.

This suggests the config does nothing... which supports the numbers. At 66% efficiency, that's 3 steam per EU, which gives 4072 steam required for a steel plate. It ACTUALLY uses more than that, which I assume is due to some rounding errors somewhere in the gregtech code... or maybe the recipe listed in NEI is giving an incorrect EU requirement."

**Comment by Technus** [comment]
Nami is that:
>https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/generators/GT_MetaTileEntity_SteamTurbine.java#L50

And/or That:
>https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/generators/GT_MetaTileEntity_SteamTurbine.java#L58

Correctly passed there?:
>https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/generators/GT_MetaTileEntity_SteamTurbine.java#L58

Or something like that.

**Comment by Namikon** [comment]
I remember that Bloodasp changed the entire efficiency system a while back in 5.09 Not sure if that got merged to our 5.08 repo. He mentioned that it "did not work at all the whole time". IIRC the new system used weird numbers in the config instead of percentage values. But I haven't touched the GT repo yet, so I can't tell for sure what's going on

**Comment by Dream-Master** [comment]
On a long term i will update to Gt 5.09 and add all stuff we added. This will be not now and it needs a lot of testings.

**Comment by Dream-Master** [comment]
Please test 5.09. MAybe we have change configs here after testings.
