### ISSUE TITLE
OC Adapter recipe don't work

### ISSUE THREAD

**Issue by ZorbaHerbalist** [GTNewHorizons/NewHorizons#5220]
#### Which modpack version are you using?
2.0.8.0

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Recipe for OC's Adapter doesn't work

![image](https://user-images.githubusercontent.com/22648885/71474417-963b2100-27db-11ea-9af0-eee57796ed31.png)

#
#### What happened instead? (Attach screenshots if needed)
Nothing happened

#

**Comment by repo-alt** [comment]
did it work in 7.5?

**Comment by ZorbaHerbalist** [comment]
I have no idea, starting OC in GTNH right now.

**Comment by ZorbaHerbalist** [comment]
Same problem with OC Redstone Card. Both recipes requires OC Cable, maybe problem with NBT or sth.

**Comment by repo-alt** [comment]
Removing bartworks fixes this issue
@bartimaeusnek this is rather game breaking, because w/o adapters OC is kinda useless

**Comment by Dream-Master** [comment]
recipe is located in the core mod.

**Comment by Dream-Master** [comment]
//adapter block
            ``GT_Values.RA.addAssemblerRecipe(new ItemStack[]{ItemList.Casing_LV.get(1L), ItemList.Circuit_Board_Plastic_Advanced.get(1L), GT_ModHandler.getModItem("OpenComputers", "cable", 2L, 0), GT_ModHandler.getModItem("OpenComputers", "item", 1L, 24), GT_Utility.getIntegratedCircuit(1)}, Materials.Plastic.getMolten(72L), GT_ModHandler.getModItem("OpenComputers", "adapter", 1L, 0), 200, 120);
            ``

**Comment by Dream-Master** [comment]
It's a recipe conflict with bart works

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71924612-9b12b400-318f-11ea-9d8c-8befb4350548.png)
![image](https://user-images.githubusercontent.com/2970688/71924624-a06ffe80-318f-11ea-8236-4404cb60bc64.png)

**Comment by Dream-Master** [comment]
fix worked
![image](https://user-images.githubusercontent.com/2970688/71926197-132ea900-3193-11ea-8467-1e221f52f5f6.png)

**Comment by repo-alt** [comment]
Gah, another selector circuit = another assembler for automation.
Thanks for the fix anyway.

**Comment by repo-alt** [comment]
What about redstone card?

**Comment by Dream-Master** [comment]
@repo-alt what is wrong with redstone card ?

**Comment by repo-alt** [comment]
> Same problem with OC Redstone Card. Both recipes requires OC Cable, maybe problem with NBT or sth.

**Comment by repo-alt** [comment]
3-rd comment from the top

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71929510-0ceffb00-319a-11ea-9835-3716556be865.png)

**Comment by repo-alt** [comment]
Ok, good, must be user error then.

**Comment by Bubunator** [comment]
aww this is a pitty iam playing on delta and the fix isnt live yet any chance to do so ? not able to proceed in OC quest progression this way

**Comment by bigbass1997** [comment]
The official servers will be updated when the next modpack version is stable enough, and more importantly when Dream has time to do so.

**Comment by repo-alt** [comment]
Adapter recipe is not broken in 7.5 in the first place. @Bubunator

**Comment by miozune** [comment]
I also cannot craft Redstone Card in 2.1.2.2QF2 MP, but unable to reproduce in SP.
Another person reported this in Discord: https://discordapp.com/channels/181078474394566657/401118216228831252/756562882283438271
