### ISSUE TITLE
Rhodium ore crash

### ISSUE THREAD

**Issue by TheThingG** [GTNewHorizons/NewHorizons#5222]
#### Which modpack version are you using?
2.0.8.0pre
#
#### If in multiplayer; On which server does this happen? 
Local server, single
#
#### What did you try to do, and what did you expect to happen?
When player tried to pickup result of Small Crude Rhodium Metal Ore mining or pickup any of it byproducts from creative game crash.
#
#### What happened instead? (Attach screenshots if needed)
Game crashes/Server disconnect
https://pastebin.com/tSyCs56b
#
#### What do you suggest instead/what changes do you propose?
This is some of Bartworks bugs

**Comment by bartimaeusnek** [comment]
should be fixed with the F1 version, need to investigate, maybe related to https://github.com/GTNewHorizons/NewHorizons/issues/5231

**Comment by bartimaeusnek** [comment]
seems to work fine with F1.

**Comment by skeblow** [comment]
This crash also happens with `rhodium sulfate cell` and `zirconium carbide dust`.
