### ISSUE TITLE
Ore Drilling Plant resets marked range.

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/NewHorizons#5223]
#### Which modpack version are you using?
 pre8.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
# 
#### What did you try to do, and what did you expect to happen?
was about to set up an ore drill, with sucess. It runs fine, however it seems that it will not mine (every) ore block within set range (96 at my case). but every ore within 16 meters
#
#### What happened instead? (Attach screenshots if needed)

![2019-12-26_22 39 26](https://user-images.githubusercontent.com/58643870/71491826-64ee3f80-2833-11ea-9dfe-a36c7b8b1f0b.png)
As you can see it drilled all ores within 16 meters range. but kinda randomly some ores with a greater distance 
#
#### What do you suggest instead/what changes do you propose?
/

**Comment by koiNoCirculation** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blame/177a2633777f055d4bd183c357abd22447b80f46/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OreDrillingPlantBase.java#L195
I got it.
The chunk radius is mistakenly set as mining block radius;
Oh fuckyou.
Watch what you did.
int radius = Math.min(Math.max(chunkRadiusConfig << 4, 1), getRadiusInChunks());

**Comment by bartimaeusnek** [comment]
oops, set the radius to blocks instead of chunks lel

**Comment by GeicowithaBango** [comment]
so we gucci now?

**Comment by koiNoCirculation** [comment]
int radius = Math.min(Math.max(chunkRadiusConfig, 1), getRadiusInChunks()) << 4;

**Comment by bartimaeusnek** [comment]
@koiNoCirculation next time, you can also make a pr if you already solve it :)))) 

https://github.com/GTNewHorizons/GT5-Unofficial/pull/225
