### ISSUE TITLE
2.0.8.0 server and client mod conflict

### ISSUE THREAD

**Issue by j2ghz** [GTNewHorizons/NewHorizons#5231]
#### Which modpack version are you using?
Happens on both:
* TechnicLauncher version 2.0.8.0pre
*  a multiMC instance with `http://downloads.gtnewhorizons.com/ClientPacks/GTNewHorizonsClient-1.7.10-2.0.8.0.zip`
#
#### If in multiplayer; On which server does this happen? 
I set up a server with `http://downloads.gtnewhorizons.com/ServerPacks/GTNewHorizonsServer-1.7.10-2.0.8.0.zip`
#
#### What did you try to do, and what did you expect to happen?
Connect to server
#
#### What happened instead? (Attach screenshots if needed)
I got this error: `Rejecting connection CLIENT: [FMLMod:bartworkscrossmod{0.5.3}, FMLMod:bartworks{0.5.3}`
And on client: `Rejecting connection SERVER: [FMLMod:bartworks{0.5.3_f1}, FMLMod:bartworkscrossmod{0.5.3_f1}]`
#
#### What do you suggest instead/what changes do you propose?
I noticed the server has bartworks 0.5.3 but the client has 0.5.3_f1.

**Comment by j2ghz** [comment]
I removed `mods/bartworks1.7.10-0.5.3.jar` from the client and added `bartworks1.7.10-0.5.3.jar` from the server zip to client's mods, and it worked.
I'm not sure if I should rather use the 0.5.3, or 0.5.3_f1

**Comment by bartimaeusnek** [comment]
f1 is the fixed version. use that FIX1 😉
