### ISSUE TITLE
Witchery coins insufficient

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5238]
#### Which modpack version are you using?
2.0.7.5

#
#### What did you try to do, and what did you expect to happen?
Complete the Witchery Spirit World Quests
#
#### What happened instead? (Attach screenshots if needed)
The Witchery spirit world quests require you to trade 8000 coins to move witchery tools (oven, cauldron, etc) into the spirit world, which is useful, but they require a ridiculous amount of time to grind for. First off, the quest Nightmares (1588), is impossible to do, since the Nightmare enemy is invulnerable until you get the Brew of Flowing Spirits, which is the point of the whole quest chain (as noted in Potion of flowing spirit (1584)), so you can't get any coins that way. Secondly, quest Wispy Cotton (1589) requires far too much Wispy Cotton compared to how many coins you get, and the time spent finding it. After completing all (possible) available quests (including the ones that require you to kill bosses), you would have only collected a total of around 3500 coins, leaving you to get the rest by collecting Wispy Cotton, which means you would need to collect about 2250 of them. The 2.0.8.0b version that I checked adds quests that give about 1600 coins (assuming you do all of them), meaning you would have ~5100, and still have to collect 1450 Cotton Wisps for 29 blue coins, something that would likely takes entire days of time, and be even worse on a server.
#
#### What do you suggest instead/what changes do you propose?
Lower the number of required Wispy Cotton for (1589) to 5-10, remove (1588), add other things you can trade for coins such as Disturbed Cotton, Diamond Vapor, Demon Blood, etc. Possibly add spirit coins to the Witchery boss kill quests on the Legendary Infinity page (though that might be too easy, if they're also 1k coins). Maybe add a non-repeatable version of each to the Witchery page explaining how to fight/summon the bosses? Like the Lord of Tourment(typo?)(2348) quest. 
In addition Better Nightmare Protection (1579) should probably be linked from Fanciful Thread (1595) (since you need it in your inventory to have an effect, so you have to make it in the spirit world for it to be useful), and Mellifluous Hunger 1583 should be linked from 1584, since you can't kill it until then.
I'm not sure why no one else complained about these quests, maybe I missed something? Or no one does witchery?

**Comment by richardhendricks** [comment]
Not many have progressed that far in Witchery tbh. Most using it are there for lycanthropy or vampirism.  I'd rather reduce the coins cost to move items instead of generating more quests to get more coins. Which quests need cost reductions?

**Comment by Prometheus0000** [comment]
Do they not follow quests? And it's not like it's far in really? Anyways it's the following:
We need another oven (1585) 500
another cauldron (1587) 1000
kettle for the spirit world (1593) 1500
offerings in your dreams (1592) 2000
spinning your dreams (1594) 3000

Spirit coin transfer (338) and more coins (1586) also take coins, but give them back as the reward so you can transfer them to the spirit world. But this is pointless since you can "pay" in the overworld too. It does get you used to the idea of transferring I guess though? But if you're reducing the amount of the others, you should reduce these too.

**Comment by richardhendricks** [comment]
Reduced costs for quests by 5x.

**Comment by Prometheus0000** [comment]
In pre4 the quest text is still the same, thus being inaccurate with the amounts needed changed. Also, 338 and 1586 still haven't had the amounts changed, making it (still) gated to the HV assembler.

**Comment by richardhendricks** [comment]
I wasn't sure if wanted to keep the questline gated to the HV assembler? @Dream-Master 

@Prometheus0000 Which quest text needs changing?

**Comment by Prometheus0000** [comment]
The gating is compressing the coins to the 1000 version in the quest with an orange icon that still doesn't have the amount changed (1586). The text should be ALL the of the ones that had the amount changed (mentioned above). 
Also, should I give up on changes relating to the nightmare enemy mentioned originally?

**Comment by richardhendricks** [comment]
File that in a separate ticket, it's too difficult to track multiple things in a big ticket like this.

**Comment by Prometheus0000** [comment]
Ok

**Comment by richardhendricks** [comment]
Witchery Distillery and other things around the same level require Stainless, so I think leaving the requirement for an HV assembler is intended.

**Comment by richardhendricks** [comment]
Quest text updated
