### ISSUE TITLE
Singleblock miner bugs

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5239]
#### Which modpack version are you using?
2.0.8.0pre w/updated GT++
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Crafted (in 2.0.8.0pre) and placed down a HV singleblock miner. Expected it to default to the maximum radius.
#
#### What happened instead? (Attach screenshots if needed)
Defaults to minimum radius (3x3) instead of maximum (49x49), so I had to mash it with a screwdriver a bunch.
#
#### What do you suggest instead/what changes do you propose?
Set the default radius to the maximum, and make the WAILA tooltip for the miner display the current operating radius.

**Comment by richardhendricks** [comment]
I think I know the issue.  A freshly crafted item doesnt have the radius set,  and even though we set it now in the constructor, that gets overwitten by the loadNBT that doesnt find any value. Should be an easy fix to see if the radius is 0 during NBTload and set it to default.

**Comment by repo-alt** [comment]
yea, I noticed/fixed similar issue in multiblocks, didn't look at single blocks

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/229/files

**Comment by richardhendricks** [comment]
singleblock miner was missing the fix, it has it now.
