### ISSUE TITLE
Quantum boots of the traveller can't be researched

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#524]
Reported by @DingoX3.
Not sure if it's a one time thing, but the attempted research looks like this:
![quantum boots of the traveler research img](https://cloud.githubusercontent.com/assets/5067989/13727761/dcf8eeaa-e8f7-11e5-8502-e4fce1f472ce.png)

**Comment by deeplyarnab** [comment]
Its thaumcraft, randomises the the research notes.
<blockquote class="imgur-embed-pub" lang="en" data-id="kqNCve6"><a href="//imgur.com/kqNCve6">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Dream-Master** [comment]
Electro Magic Tools reipe i not touch atm.
