### ISSUE TITLE
Teleposers telepose blocks with -1 hardness, including Bedrock and Transport Beacons

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5245]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
Telepose Transport Beacon, fail.
#
#### What happened instead? (Attach screenshots if needed)
Succeded in teleposing.
#
#### What do you suggest instead/what changes do you propose?
Add to blacklist before someone steals all the easy to use teleporters in the end.
They use energy from energy clusters, but you can move those normally within the mod (though they lose power or something), so you could steal them and set up a network elsewhere. Using the teleposer on the clusters causes them to explode at least.

**Comment by Dream-Master** [comment]
How you mine it @Prometheus0000 ?

**Comment by Prometheus0000** [comment]
? I teleposed them, as in used the blood magic teleposer to teleport them.

**Comment by Dream-Master** [comment]
so it is possible to move blocks like bedrock etc ? dind't know it

**Comment by Prometheus0000** [comment]
Yes, you can move stuff like nodes as well (in other modpacks, I didn't check in this one), entities like players or mobs, and can expand the range up to a 7x7x7 area if you use the max level teleposition focus. There's a blacklist with nothing on it in the config folder, so it should be a simple matter of adding items and testing it.

**Comment by Dream-Master** [comment]
good idea. @Prometheus0000 can you make a list for me with items we have to put in there. Thanks

**Comment by Prometheus0000** [comment]
I feel that this is the kind of thing you shouldn't rely on just me to come up with, but here's what I thought up.
The config file is AWWayofTime.cfg, and the part where the blacklist is is at line 970:

"teleposer blacklist" {
    # Stops specified blocks from being teleposed. Put entries on new lines. Valid syntax is: 
    # modid:blockname:meta
    S:Blacklist <
        minecraft:bedrock
        minecraft:end_portal
        minecraft:end_portal_frame
        HardcoreEnderExpansion:transport_beacon
        Thaumcraft:blockPortalEldritch
        Thaumcraft:blockEldritchNothing
        ThaumicHorizons:vortexTH
     >
}

I tested only bedrock, but it does prevent teleposing.

The entries I've thought of are:
Bedrock
End Portal (stronghold end portal/end exit portal)
End Portal Frame (stronghold end portal frame)
Transport Beacon (teleporters in the end)
eldritch portal (portal to eldritch dimension and back)
portal to nothing (walls of eldritch dimension)
planar vortex (like a hungry node but faster, if not stabilized)

pure tree node(couldn't find entry) (node that forms in silverwood trees)
node (couldn't find entry) (there's harder ways to do it in thaumcraft and it's addons anyway)
rubber tree knot (couldn't find entry) (probably unnecessary anyway)
other portals? I saw some in the dump file, but I'm not sure what they are, or if they can be moved/destroyed normally.
possibly the end crystal entity? I don't know who would bother though.
spawners if you want to be mean. After all, we already have diamond dollies.

There may or may not be a bunch or others depending on various factors. For example, you can move half a piston, but the original block is dropped, and nothing from the half you teleposed when mined. Doors kind of act wonky too. It's probably the same for lots of similar blocks. I imagine many multiblocks would not like parts missing in the middle of operation, but I think common sense and the lack of a reason to do so would prevail there. And it's not like I know everything about every mod either. I don't know about world gen for the galacticraft planets for example, so someone else will have to help with that.

**Comment by Dream-Master** [comment]
will add.

**Comment by Prometheus0000** [comment]
It seems you can move graves as well. orz. Please add OpenBlocks:grave to the list.
