### ISSUE TITLE
Minor Thaumcraft quest error

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5246]
#### Which modpack version are you using?
2.0.8.0pre

The "iron capped greatwood wand" quest (ID 798) in the Novice Thaumaturge tab has a retrieval for an iron capped wooden wand, when it should request an iron capped greatwood wand.

**Comment by chochem** [comment]
this quests was in the list, here https://github.com/GTNewHorizons/NewHorizons/issues/5112,
but is still broken, even doubly so.

It asks for the wrong item but does not recognize even that (or do only empty wands count? my old iron capped wooden wand obviously wasnt empty).
