### ISSUE TITLE
Fluix Bees not showing recipe. 

### ISSUE THREAD

**Issue by Kaffeine2005** [GTNewHorizons/NewHorizons#5247]
#### Which modpack version are you using?
Magic Bees1.0 in Dire Wolf 2.5.0
#
#### If in multiplayer; On which server does this happen? 
Personal server
#
#### What did you try to do, and what did you expect to happen?
When clicking on the fluix bee it should show a recipe (breeding pair) for the bee and what it outputs.
#
#### What happened instead? (Attach screenshots if needed)
There is no recipe for the fluix bee and it also says the only output is regular honey combs
#
#### What do you suggest instead/what changes do you propose?
Are fluix bees included in magic bees 1.0? Can a newer version be added to dire wolf?

**Comment by richardhendricks** [comment]
This is for the modpack Gregtech:New Horizons, not Dire Wolf.
