### ISSUE TITLE
SOC recipe conflict 

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/NewHorizons#5255]
#### Which modpack version are you using?
2080
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Try crafting soc, but gets 4 LPIC wafer instead
#
#### What happened instead? (Attach screenshots if needed)
Wafer recipe conflict on SOC and LPIC 
#

**Comment by Dream-Master** [comment]
Soc use Naq Wafers and above
Lpic use lower wafers. i dont see a recipe conflict here.
@koiNoCirculation

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71746857-5d9be700-2e6e-11ea-9bfa-6123388dee8b.png)
![image](https://user-images.githubusercontent.com/2970688/71746865-5ffe4100-2e6e-11ea-846d-863fa5295478.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71746886-6ee4f380-2e6e-11ea-86e8-c3cddd3af0b6.png)
![image](https://user-images.githubusercontent.com/2970688/71746892-71dfe400-2e6e-11ea-98f1-f7fdc6d7ca5f.png)
