### ISSUE TITLE
CircuitAssemblyLine can't build up with high-amp Energy Hatch.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5259]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
single and private server
#
#### What happened instead? (Attach screenshots if needed)
CircuitAssemblyLine can't build up with high-amp Energy Hatch(Adding by TecTech) such as UV 4A Energy Hatch.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by draknyte1** [comment]
TT Energy/Dynamo hatches don't actually extend the standard types. So far as GT itself can tell, they're not Energy or Dynamo hatches.

It's not really on GT to implement this support, then have a build dependency on TT as a result. Tech chose this design choice for a reason, just gotta live with that. IIRC Nothing beyond TT multis and the PSS support his stuff.

**Comment by bartimaeusnek** [comment]
^ TecTech Hatches/Dynamos are not working for most multis for a reason, that is that they can accept way to many amps, for early/midgame. I might implement them on the MegaMachines sooner or later, but for now, its not planned for any BW Multi.
