### ISSUE TITLE
Purification Talisman recipe may be too difficult

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#526]
Considering how important this Talisman is to having to actually playing, my players feel that the new recipe is too difficult.  Something between the old one and the new one might be better.

**Comment by Dream-Master** [comment]
Will see what i can do here.

**Comment by Dream-Master** [comment]
@ProsperCraft 
What exactly is too expensive.
Too much ingredients, the instability to high, to much vis cost?

**Comment by ProsperCraft** [comment]
The Exquisite diamonds are the most difficult to obtain I think, it locks the talisman to EV tier.

**Comment by Dream-Master** [comment]
Ok i can change this to flawless Diamonds so HV need for it or a Sifter.
