### ISSUE TITLE
Quicklime dust recipe issue

### ISSUE THREAD

**Issue by flockenobsidian** [GTNewHorizons/NewHorizons#5261]
#### Which modpack version are you using?
2.0.8.0

#
#### What did you try to do, and what did you expect to happen?
Small & Tiny Piles uncraftable, only Modid changes, GT -> Witchery, when placed in crafting grid

**Comment by bartimaeusnek** [comment]
We should change the Quicklime recipe to the following:

```
"  d" aka. null, null, dust 
```
to allow for propper recipe handleing with the recipe lookup speed boost patch

**Comment by richardhendricks** [comment]
Think you can fix it in the next few days? It would be nice to get 8.0 official out this weekend. :)

**Comment by bartimaeusnek** [comment]
Dunno where dream added it, i might have the time to look it up, but i cant promise it.

**Comment by Dream-Master** [comment]
I guess its a issue in the script. Will check
