### ISSUE TITLE
Netherfarms kill TPS when crossing chunk lines - Cursed Earth

### ISSUE THREAD

**Issue by devanchya** [GTNewHorizons/NewHorizons#5262]
#### Which modpack version are you using?
Latest ETA

When a Cursed Earth Farm is in the nether, it can cause huge TPS issues (Nether shows 3-4tps).
Issue appears when cursed earth is connected to anything in the nether.   

Discussion over the last few months has lead us to find it works better if the Cursed Earth is not attached to anything from the Nether.   IE:  can be on Marble but the marble cannot touch anything in nether (nethercrack, nether brick)  floating in the air.

Cursed Earth should be 1 Chunk max, with 1 block smaller than the chunk size.  This would include the walls .

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72584697-b9c02b80-38b0-11ea-89ea-925167a90740.png)
