### ISSUE TITLE
Getting your first Platinum Quest impossible in MV

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5266]
#### Which modpack version are you using?
2.0.8.0pre
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
The Quest *Getting your first Platinum* tells me to smelt the Metallic Powder for Nuggets. 
#
#### What happened instead? (Attach screenshots if needed)
its impossible in MV. The heat req. needs Kanthal coils which are HV-tech. On top of that, this is a main quest leading to SMDs, etc.
#
#### What do you suggest instead/what changes do you propose?
Either change the heat requirement for the Platinum Nugget recipe or push the quest +SMD quest to HV

**Comment by Bluebine** [comment]
IMHO the quests should definitely be pushed to HV, or even EV. You don't need platinum or SMD parts until EV, and they're not terribly useful until at least HV.

**Comment by richardhendricks** [comment]
OK will try moving them the HV somewhere.  Will also note that the best sources is Nickel Ores or Endstone dusts at this tier. 

Will the Platinum Group Sludge recipes still be valid?

**Comment by richardhendricks** [comment]
Since the integrated processer/workstation/etc quests have the SMD quest as a prereq, I put the platinum/SMD quests before 1018 Central Processing Unit in line with the Advanced Circuit Assembler.
