### ISSUE TITLE
No CD on some quest that should have CD (to grind or not to grind section)

### ISSUE THREAD

**Issue by Shan0211** [GTNewHorizons/NewHorizons#5267]
#### Which modpack version are you using?
latest on the server
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Just NO CD in grind all the things quest the bottom 2-3
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Maybe add the CD so it will be fixed :) (its repeatable atm)

**Comment by richardhendricks** [comment]
Talked with Shan on discord, need to retest this with Zetatest or 8.0pre.

**Comment by richardhendricks** [comment]
coins quests properly have repeat cooldowns, need to test the Grind quests.
