### ISSUE TITLE
Workstation Recipe/Quest issues

### ISSUE THREAD

**Issue by LandlessGuy** [GTNewHorizons/NewHorizons#5269]
#### Which modpack version are you using?
2.0.8.0pre
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Attempted to make a workstation using the recipe shown on NEI
#
#### What happened instead? (Attach screenshots if needed)
Recipe has been changed from platinum bolts to blue alloy bolts. However, the workstation quest still lists the required bolts as being platinum.
#
#### What do you suggest instead/what changes do you propose?
Quest change to reflect the new bolts being added

**Comment by Anarack** [comment]
Blue alloy is made from silver and electrotine in the alloy smelter. recipe is shown and exists, just needs quest change.

**Comment by LandlessGuy** [comment]
Apologies, have just found this, will update ticket accordingly

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/71711556-2de5d400-2dc7-11ea-8064-f3d21c783cc3.png)
