### ISSUE TITLE
Biome/Potion ID Conflict

### ISSUE THREAD

**Issue by Ixodid** [GTNewHorizons/NewHorizons#527]
Galaxy Space's mercury biome is overwriting RWG's ice river, id = 200. I also can't find any Galaxy Space config file if there is supposed to be any.

**Comment by deeplyarnab** [comment]
Eh, another biome conflict issue related to galacticraft, are you using the latest recommended version? We fixed some biome id conflicts in the latest one

**Comment by Dream-Master** [comment]
There are no config for it and i think it is hard coded. So i think i can't do any thing against it. If you load a new World maybe change RWG Biome id to another ID.

**Comment by Dream-Master** [comment]
@deeplyarnab 
No arnab GS 2.6 not have any config for it and 1.0.8 ignore it if i change the biomes so useless too.

**Comment by Ixodid** [comment]
If Galaxy Space is all hardcoded I guess I'll move the RWG and BoP IDs around.
Just for the record, as you might want to change it for a future release. As of 1.0.7.7m:
RWG and GS both use id 200 (rwg_riverIce & mercury)
BoP and GS both use id 120 (Wetland & venus)

**Comment by Dream-Master** [comment]
Thanks for info so we need to change it too. You find any other id conflicts?

**Comment by deeplyarnab** [comment]
@Dream-Master Use [this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2387300-say-no-to-id-conflicts-install-anti-id-conflict) Super highly recommended for all id conflicts.

**Comment by Dream-Master** [comment]
Yes will check this later. maybe we get more surprising id conflicts.

**Comment by deeplyarnab** [comment]
It did though, crashes the game if it finds conflicts

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 14/3/16 4:32 PM
Description: Conflicting potions forced game to crash: 

code.elix_x.coremods.antiidconflict.managers.PotionsManager$PotionsIDConflictException: Conflict between potions with same id caused game to crash.
Affected ids:
71 is asked by: potion.dragonwrack (fox.spiteful.forbidden.potions.PotionDragonwrack), witchery:potion.gasmask (com.emoniph.witchery.brewing.potions.PotionGasMask)
114 is asked by: Feather Fall (WayofTime.alchemicalWizardry.common.potion.PotionFeatherFall), Demon Cloaking (WayofTime.alchemicalWizardry.common.potion.PotionDemonCloak)`

**Comment by Dream-Master** [comment]
Ok found it in the config
``````
ID 71 are used by Witchery
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/ForbiddenMagic.cfg#L27
 and Forbidden magic
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/witchery.cfg#L176
``````
````
ID 114 are use by Blood magic 
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/AWWayofTime.cfg#L324
and Blood magic
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/AWWayofTime.cfg#L326
``````
Ok will fix it.

**Comment by Dream-Master** [comment]
Poition ids are fixed

https://github.com/GTNewHorizons/NewHorizons/compare/PoitionIDFix

**Comment by deeplyarnab** [comment]
BTW, for your ease, i uploaded the conflict related files generated by that mod
[Get it here](https://www.mediafire.com/folder/bfq4ap1zg3d2b/AntiIDConflict)

**Comment by Dream-Master** [comment]
Can't download things.

**Comment by deeplyarnab** [comment]
Updated link, made the folder in a zip.
https://drive.google.com/file/d/0B3BKP8ryhGQAOWFrZW9vclZsaE0/view?usp=sharing

**Comment by Dream-Master** [comment]
But with this changes i made we not have any conflict atm.

**Comment by Dream-Master** [comment]
Can i have a full list with Biomes that overlaps ?

**Comment by deeplyarnab** [comment]
Check all the conflicts from [here](https://drive.google.com/open?id=0B3BKP8ryhGQATlAydU9qRTBobGM)
Just ignore the biome id conflicts from BOP or RTG

**Comment by Dream-Master** [comment]
@deeplyarnab 

This not helped because i can't see GS Biome ids.
and btw i sen you a pm in the forum.

**Comment by Dream-Master** [comment]
If we change some day to RTG we dont have this problen anymore.

**Comment by Dream-Master** [comment]
Will stick with RWG because looks better. So maybe need to change BIOME ids or update to GS 1.10

**Comment by Dream-Master** [comment]
So we updating Galaxy Space now and the Dimension Id conflict is gone then.
