### ISSUE TITLE
Electrotine (Oredict?) Issue

### ISSUE THREAD

**Issue by LandlessGuy** [GTNewHorizons/NewHorizons#5270]
#### Which modpack version are you using?
2.0.8.0pre
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Attempted to convert PR electrotine to GT electrotine via tiny and small pile recipes
#
#### What happened instead? (Attach screenshots if needed)
Converted the electrotine to tiny GT piles, but they cannot be combined into a normal sized dust. The same issue occurred on testing with small piles
#
#### What do you suggest instead/what changes do you propose?
Potential Oredict required for conversion of electrotine for use in new recipes - not essential as blue alloy can be made with PR electrotine but thought it might be useful anyways

**Comment by richardhendricks** [comment]
bart I am trying the latest gt5u and this is still a problem

**Comment by Chapsteck4yurlipis** [comment]
Issue still exists on GTNH 2.6.1:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29219333/e197f621-0d35-4843-95d9-22be03bcba9c)
