### ISSUE TITLE
Can't breed firestone bees

### ISSUE THREAD

**Issue by raellol** [GTNewHorizons/NewHorizons#5271]
#### Which modpack version are you using?

#2.0.7.5 also checked in 2.0.8.0
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Firestone bees can't be bred because there's no firestone block. Didn't try because there's no such thing as "blockFirestone" .
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/35425473/71683279-6ae3a380-2d92-11ea-8c03-4333495d3946.png)

#
#### What do you suggest instead/what changes do you propose?
The addition of a firestone block, ore a change in the requirement of it...

**Comment by Dream-Master** [comment]
will add a firestone block
