### ISSUE TITLE
Request to add Modded Minecraft Club to official server list

### ISSUE THREAD

**Issue by john01dav** [GTNewHorizons/NewHorizons#5274]
#### Which modpack version are you using?
2.0.8.0

#### If in multiplayer; On which server does this happen? 
Modded Minecraft Club, https://www.moddedminecraft.club/

#### What do you suggest instead/what changes do you propose?
I would like to request that my server, Modded Minecraft Club, be added to the server list that is provided with the GTNH pack on download. I was told in the GTNH Discord that making an issue here is the correct place to request this. The IP is gtnh.moddedminecraft.club. All other information is available at https://www.moddedminecraft.club/, including Discord, forums, and wiki. The wiki contains server rules, moderator guidelines, and all other server policy (excluding what is internal to the staff team, of course).

**Comment by john01dav** [comment]
Some people on Discord have vouched for my server and community's quality. The conversation for this starts around https://discordapp.com/channels/181078474394566657/181078474394566657/662530251964022784 .

**Comment by Dream-Master** [comment]
will add in the next release

**Comment by Dream-Master** [comment]
Lord Capy, Destroyer of LambdasToday at 7:39 PM
@DreamMasterXXL server is in Montreal, Canada in a professional datacenter. It is public without a whitelist, but has very strong anti-grief controls in place so this isn't an issue.
