### ISSUE TITLE
Bio magneto resonatic circuit uncraftable

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/NewHorizons#5276]
#### Which modpack version are you using?
2.0.8.0
#

#### What do you suggest instead/what changes do you propose?

The bio magneto resonatic circuit from bartworks requires UIV circuit assembler to be crafted, but the UIV ca itself has no recipe. Maybe add some recipe for the UIV circuit assembler.

**Comment by Spartak1997** [comment]
GTNH doesn't have a good concept for UHV-UEV tiers. I think we should't talk about a new tier :D

**Comment by Spartak1997** [comment]
GTNH doesn't have a good concept for UHV-UEV tiers. I think we should't talk about a new tier :D

**Comment by Josh5minus1** [comment]
The late game tiers are incomplete, so maybe in future those tiers will be implemented

**Comment by Dream-Master** [comment]
yes
