### ISSUE TITLE
Quests Getting your first Platinum and SMD Circuit components still impossible where placed

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5279]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What is the problem?

both quest were supposed to be moved to HV but they still appear in MV even though they are impossible there. (see https://github.com/GTNewHorizons/NewHorizons/issues/5266)

While they do now also appear in HV, they are positioned too early, blocking the entire questline.

These quests need kanthal coils and thus have to be behind EV circuits.

#
#### What do you suggest instead/what changes do you propose?
remove these quests from MV. In HV remove them from the EV circuit progression. Instead put them parallel to the Glowstone doped wafer which also need Kanthal coils.
Furthermore, the requirements for the quests need to be changed.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71765028-a1830080-2eef-11ea-90c8-64866db412fd.png)
they in hv

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71765108-ca57c580-2ef0-11ea-9efa-57de40fb19de.png)

**Comment by chochem** [comment]
hmm, I am obviously not able to test this InDev and the red lines don't have directions, but the picture still looks like you need platinum (or platinum based SMD components) to get to EV circuits (via cpu, circuit assembler, ...), which would break the progression.

**Comment by Dream-Master** [comment]
@chochem please check in game an report here. Thanks

**Comment by chochem** [comment]
Sure, I will test it once I have game files for it like in pre5.

**Comment by richardhendricks** [comment]
New placement 
![image](https://user-images.githubusercontent.com/1214811/71955075-e8e9e500-31ac-11ea-9b37-167ab6080d4a.png)
