### ISSUE TITLE
Flint Tools Quest

### ISSUE THREAD

**Issue by ddteam90** [GTNewHorizons/NewHorizons#5280]
Hello! 

I started playing GTNH again and noticed that after update with quests, **Flint Pickaxe** crafting doesn't count in quest **Tools**

Similarly with Flint Sword in quest **Sharpness: Over 5**

Pack - 2.0.8.0

Have a good day!
DigimasterHiro

**Comment by richardhendricks** [comment]
Are you using 2.0.8.0pre from Technic, or 2.0.8.0pre4 from downloads.gtnewhorizons.com?

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297
