### ISSUE TITLE
cleanroom quest 940 does not recognize MV energy hatch

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5282]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
cleanroom quest 940
#
#### What happened instead? (Attach screenshots if needed)
it does not recognize the MV energy hatch EDIT: or the filter machine casings EDIT2: or the cleanroom controller
#
#### What do you suggest instead/what changes do you propose?
supposedly this was fixed in https://github.com/GTNewHorizons/NewHorizons/issues/5112, but this specific quest still has the problem

**Comment by chochem** [comment]
added the filter machine casing and the cleanroom controller to the MV energy hatch. Everything else works though.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297
