### ISSUE TITLE
Djurleite ore isnt recognized as ore for "small" miners

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5287]
#### Which modpack version are you using?
2.0.8.0.pre-4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Mine Djurleite ore by Advanced miner
#
#### What happened instead? (Attach screenshots if needed)
it mines every other ore in range, no djurleite
![2020-01-06_00 47 11](https://user-images.githubusercontent.com/14223368/71787963-29672880-301e-11ea-9be1-b0d0dd276c15.png)

#
#### What do you suggest instead/what changes do you propose?
Add that ore in "whitelist" or whatev that machine uses

**Comment by richardhendricks** [comment]
Well, never suspected someone would place a bunch of miners next to each other. Educational.
