### ISSUE TITLE
Quest still not recognizing item: ID 1232 - You gonna hate this 5 and 6 in HV, (Emitter (HV), Sensor (HV))

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5289]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
crafted emitter and sensor
#
#### What happened instead? (Attach screenshots if needed)
quest does not recognize either item. This was supposedly fixed in https://github.com/GTNewHorizons/NewHorizons/issues/5112.
#

**Comment by Hyperic88** [comment]
have you tried to run it through that name tag remover machine?:)

**Comment by chochem** [comment]
never heard of that.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297
