### ISSUE TITLE
Pump block doesnt mine properly

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5290]
#### Which modpack version are you using?
2.0.8.0.pre-4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I've placed pump in nether, to take out lava :)
#
#### What happened instead? (Attach screenshots if needed)
Pump mined straight down to bottom, outputting only 1 bucket per layer (for the pipe)
#
#### What do you suggest instead/what changes do you propose?
check the function please

**Comment by chochem** [comment]
I dont know if this is intended or not (hopefully not). The range defaults to 1.
 But you can adjust it with iirc a screwdriver.

**Comment by Hyperic88** [comment]
Ok, that was it... sorry :)

**Comment by richardhendricks** [comment]
Pump block should have been fixed to start at maximum width.  If it did not, we need to recheck with the latest version.

Was this a pump you crafted, or one you cheated in? The configured radius is saved in the item NBT so it should preserve if you break the pump and replace it somewhere else.

**Comment by chochem** [comment]
for me this happened with a newly crafted advanced pump (on 8.0pre or pre4 not sure). Have not tested anything beyond that.

**Comment by repo-alt** [comment]
It was fixed fairly recently, but should have gotten into pre4

**Comment by bartimaeusnek** [comment]
> Piky / Scripted Support:
> So this is an interesting interaction with the miners. Look at where the positioning of the miner, and where they mined at
> 
> https://media.discordapp.net/attachments/551955778840428550/663723700255719449/2020-01-06_04.40.06.png

**Comment by repo-alt** [comment]
Central chunk is mined first. The picture is not very illustrative as it is tbh.

**Comment by chochem** [comment]
@repo-alt @bartimaeusnek this is not about chunks or multiblockminers, so I dont know how relevant all that is. And @Hyperic88 clearly reported for pre4. Anyway, *needs to tested*.

**Comment by richardhendricks** [comment]
Let's keep this with the pump issue please.  Yes, pre did not have the fix, pre4 should have the fix that if there is no stored pump radius NBT, it will default to the maximum. I'll have to recheck.

**Comment by chochem** [comment]
test result:
new pump just crafted on pre4: works correctly.
