### ISSUE TITLE
Quest still not recognizing items: ID 237 - "Stores 50 vis" wand

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5291]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
crafted the gold banded greatwood wand
#
#### What happened instead? (Attach screenshots if needed)
quest does not recognize it
#
#### Additional Comments:
Was part of this https://github.com/GTNewHorizons/NewHorizons/issues/5112. Also see https://github.com/GTNewHorizons/NewHorizons/issues/5246 for the other wand quest that is not working.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297

**Comment by tuckermand** [comment]
I'm now experiencing this problem on prospercrafts SMP server, ver 2.0.9.0.

**Comment by Prometheus0000** [comment]
Update to 2.1
