### ISSUE TITLE
Divine rod of the gods not recognizing Ore Finder Wand being crafted

### ISSUE THREAD

**Issue by bvierra** [GTNewHorizons/NewHorizons#5292]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Crafted an Ore Finder Wand for the Divine rod of the gods quest in Tier 0.5. I expected it to recognize the wand was crafted, it however did not.
#
#### What happened instead? (Attach screenshots if needed)
Still shows that I need to retrieve the Ore Finder Wand
#

**Comment by richardhendricks** [comment]
Probably NBT data related again.

**Comment by richardhendricks** [comment]
Did you try clicking on the detect/submit button? It's a retrieval task, so it won't trigger on crafting.

**Comment by richardhendricks** [comment]
Maybe https://github.com/GTNewHorizons/NewHorizons/issues/5297

**Comment by richardhendricks** [comment]
tested with latest dev, looks like it works.
