### ISSUE TITLE
Nightmares (1588) on Look to the Edges tab is not possible when you get it

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5294]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
As mentioned in #5238, this quest is impossible to do (when you get it), since the Nightmare enemy is invulnerable until you get the Brew of Flowing Spirits, which is the point of the whole quest chain (and thus the point of grinding coins) (as noted in Potion of flowing spirit (1584)), so you can't get any coins that way for doing the spirit world quest line. Not to mention, you would have to kill it without decent weapons or armors (flint tools, wood armor?) 10 times for a single blue coin. Technically you can complete it after getting Brew of Flowing Spirits, but why would you need more coins then? If you want to leave a way for people to grind coins if you add more to the Coins tab (I thing wormwood was added?), place it after getting the brew, and reduce the number.
#
#### What do you suggest instead/what changes do you propose?
Remove the quest, or move it+reduce number of kills(maybe).

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72128666-43b04780-3339-11ea-8598-ff704d0c7181.png)
![image](https://user-images.githubusercontent.com/1214811/72128674-49a62880-3339-11ea-9d8b-4062bfe8326f.png)
