### ISSUE TITLE
Quest 1739: *Farming a little easier* does not recognize robot arms

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5298]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?/ What happened instead? 
As the title says. Quest 1739: *Farming a little easier* (EIO Farming station, HV tab) does not recognize the 2 robot arms. All other items in the quest work fine.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297
