### ISSUE TITLE
Quest not recognizing item: Quest ID 1236 - Cutting Machine HV

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5299]
#### Which modpack version are you using?
2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
made an HV cutting machine.
#
#### What happened instead? (Attach screenshots if needed)
It is not recognized by the quest.

(was part of https://github.com/GTNewHorizons/NewHorizons/issues/5112)

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5297
