### ISSUE TITLE
NEI Crash opening TinkersConstruct ToolStation

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NewHorizons#5300]
#### Which modpack version are you using?

2.0.8.0pre4

#### What did you try to do, and what did you expect to happen?

Opening TinkersConstruct ToolStation

#### What happened instead? (Attach screenshots if needed)

Crash [`crash-2020-01-07_19.21.27-client.txt`](https://gist.github.com/leagris/8eeadc8b30055354955f3babe861c174)

**Comment by Dream-Master** [comment]
[NotEnoughItems-1.7.10-2.0.0-pre-11-GTNH-universal.zip](https://github.com/GTNewHorizons/NewHorizons/files/4031951/NotEnoughItems-1.7.10-2.0.0-pre-11-GTNH-universal.zip)

@leagris try with this version please. Thanks

**Comment by mitchej123** [comment]
I'll push a fix.  I removed the state buttons and didn't realize any other mods were calling that.

**Comment by mitchej123** [comment]
For the time being, if you want to use the toolstation, grab NEI off of curseforge -- I'll push a fix tonight.

**Comment by mitchej123** [comment]
[NotEnoughItems-1.7.10-2.0.0-pre-12-GTNH-universal.jar.zip](https://github.com/GTNewHorizons/NewHorizons/files/4032074/NotEnoughItems-1.7.10-2.0.0-pre-12-GTNH-universal.jar.zip)

Untested, but this should fix the issue.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/71926591-f3e44b80-3193-11ea-921e-feae7a7fc687.png)
fixed i guess
