### ISSUE TITLE
Piston recipe doesn't oredict GT planks

### ISSUE THREAD

**Issue by Denwey** [GTNewHorizons/NewHorizons#5306]
The current piston recipe only accepts the oak GT plank variant, while still oredicting the fence used alongside it, forcing you to use oak instead of whatever choice of wood you may have.
Observed it in 2.0.7.5, not sure as to other versions.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3762

We've tried several times over the years to fix this and been unsuccessful. It sucks but it's where it's at.
