### ISSUE TITLE
NEI crash while viewing infusion recipes

### ISSUE THREAD

**Issue by BloCamLimb** [GTNewHorizons/NewHorizons#5308]
#### Which modpack version are you using?
2.0.8.0-pre4
#
#### What did you try to do, and what did you expect to happen?
Fix it
#
#### What happened instead? (Attach screenshots if needed)
NotEnoughItems-1.7.10-2.0.0-pre-12-GTNH-universal
[crash-report](https://paste.ubuntu.com/p/NZRYYm47p9/)
searching gunpowder usage in infusion page

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by mitchej123** [comment]
<3 internal usage by arr mods.  Need to decompile it and see which field it
took a dependency on

**Comment by Dream-Master** [comment]
@mitchej123 we have the unofficial version auf Thaumic horizons forked

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons

**Comment by mitchej123** [comment]
At first glance this doesn't seem NEI related, it looks like it got a null stack passed to it somehow.  Will investigate when I get home and can run it through a debugger.

Can you reliably reproduce the bug?  What about with the 1.x series of NEI?

**Comment by BloCamLimb** [comment]
Still with 1.0.6, I've also got two other crashes recently
[crash1](https://paste.ubuntu.com/p/2YzcqNxk7V/)
[crash2](https://paste.ubuntu.com/p/jRB2wNPBC4/)

**Comment by mitchej123** [comment]
@bartimaeusnek take a look at crash2.

**Comment by mitchej123** [comment]
Can you give me the steps to reproduce this?

**Comment by BloCamLimb** [comment]
the first crash, unlock all tc researches, lookup gunpowder usage, goto infusion page and wheel up to the last recipe

**Comment by mitchej123** [comment]
And the other two?

**Comment by BloCamLimb** [comment]
I can't remember but both just happened sometimes when lookingup NEI
