### ISSUE TITLE
Please Replace RT Hardcore Darkness with Hardcore Darkness Mod (Compatible)

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#5312]
It be nice if this could make it in for 2.0.8.0, but sadly I might be too late.
**Testing using Hardcore Darkness:**
https://www.curseforge.com/minecraft/mc-mods/hardcore-darkness/files/2262352 
**(Default Settings)**
Default HardcoreDarkness.cfg (So you don't have to launch it the first time)
https://pastebin.com/NqaxVp0H

Changing these 2 Lines in RandomThings.cfg
B:"Hardcore Darkness"=false
B:LockedGamma=false

You can also do moon phases, change some other dims like nether/twilight forest. Keep in mind by default Nether is Hardcore Darkness so you might want to change that if that is not something you want.

So the biggest complaint I have seen is Gamma Lock in RT Hardcore Darkness. The issue with enabling it and using the slider is it buggers the entire Hardcore Darkness and makes it a lot brighter.

The reason people do this is for Vision problems, Youtubers, and well not wanting their base to look ugly...

The thing is I like the Hardcore Darkness concept and I want both Hardcore Darkness and Full Gamma without ruining the Ambient lighting. 

Thanks to Hardcore Darkness the Separate Mod it fixes just this and even offers you more darkness options including moon phases, etc. 

Here is a Test Video Showing Hardcore Darkness (The Mod) with No Gamma to Max Gamma and then RT Hardcore Darkness with No Gamma and Max Gamma.
https://www.youtube.com/watch?v=_L9nqjrNCP0

RT Hardcore Darkness Low Gamma: 
https://i.imgur.com/Sivbf1l.png

RT Hardcore Darkness High Gamma: 
https://i.imgur.com/Ed9nxwm.png

Hardcore Darkness (Mod) Low Gamma:
https://i.imgur.com/vXuZALs.png

Hardcore Darkness (Mod) High Gamma:
https://i.imgur.com/HM0iEMD.png

Bonus it works 100% fine with Bloodmoon and here is High Gamma Examples:

Bloodmoon RT Hardcore Darkness High Gamma:
https://i.imgur.com/wstG6yH.png

Bloodmoon Hardcore Darkness (Mod) High Gamma:
https://i.imgur.com/aa1ptDV.png

If your not convinced due to a lower quality monitor, low back light, etc. Check these 2 screenshots by another player saying they could not see the difference. 

I Doctored Both images with 150 Gamma and -50 Contrast and you can see by the mini map, etc they are even. But this really shows off how bad RT Hardcore Darkness is with Gamma.

No Gamma:
https://cdn.discordapp.com/attachments/181078474394566657/664878037799796739/unknown.png

Gamma:
https://cdn.discordapp.com/attachments/181078474394566657/664878061178847262/unknown.png

**Comment by chochem** [comment]
'another player' here. I approve! In particular this change would make GTNH much better for streaming/youtube which would be awesome.

**Comment by KaneHart** [comment]
Please keep in mind nether is enable by default so you might want to disable that unless you want to hear 1000's of souls scream lol

**Comment by Dream-Master** [comment]
Why? dark nether is nice :P

**Comment by Dream-Master** [comment]
works for me too

**Comment by Dream-Master** [comment]
found a bug. If nether have enabled HD it will be black in unlighted areas. If you leave the game and re join the effect is gone. If you go through the portal and come back it is enabled again.

**Comment by KaneHart** [comment]
Honestly might be best to disable the Nether one as I think people will hate you forever if you enable that LOL. I love the effect but people hate the nether already too much. The idea of this is to get people to enjoy HD in the Overworld with the option to have full Gamma and the awesome mood effect of HD

**Comment by KaneHart** [comment]
@Dream-Master Dude to some requests on Discord. Do you think you can not include the mod on the server side but just the client?

People still want the option to disable it... I mean that is up to you but then people just find ways to hack it and be annoying with it. I think instead if you don't include it those servers who want to force it can and the ones who don't want to don't need to add it to the server side.

I tested it and works just fine on the client side if the server does not have the Jar.

Also works great in optifine someone had asked.

**Comment by Dream-Master** [comment]
No I add it to the server as well or i  change it back to the old configs and remove the mod.

**Comment by KaneHart** [comment]
I rather you keep it for sure. It's just people will cry and whine about it as they can't cheat and turn it off!

But I'm fine leaving it alone :)

**Comment by Dream-Master** [comment]
it's part of the pack.

**Comment by KaneHart** [comment]
I totally agree! I just wanted to put out what others said on Discord. Now they have full gamma I don't see an issue. Before it screwed up the look of bases now they look awesome and we get the Darkness.

**Comment by Dream-Master** [comment]
and nether and tf stay unchanged

**Comment by chochem** [comment]
@Dream-Master well, about that: https://github.com/GTNewHorizons/NewHorizons/issues/5354
