### ISSUE TITLE
More quests that need oredicted

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5316]
#### Which modpack version are you using?
2.0.8.0pre4
#### What do you suggest instead/what changes do you propose?
-[ ]The following quests are still not properly oredicted and thus aren't completable: 
-[ ]The carpenter (578)
-[ ]Railcraft steam power (560)
-[ ]Swipe swipe (1607)
-[ ]Sharpness: Over... 5... (11)

Will add more if I find more.

**Comment by richardhendricks** [comment]
Don't bother on pre4, wait until the next release.  or download the latest questfile from github.  The questfile was improperly released on pre4, breaking a lot of stuff.  I went through and fixed it.

**Comment by Dream-Master** [comment]
@richardhendricks oredict and nbt are different so it wont changed in pre5 or 2.0.8.1

**Comment by Dream-Master** [comment]
@Bluebine ore you mean nbt ?

**Comment by Bluebine** [comment]
er yeah, I meant NBT. Same problem a bunch of other quests had

**Comment by Dream-Master** [comment]
ok that is fixed
