### ISSUE TITLE
Suggestion: separate out or remove the crowbar from the basic gt tools quest

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5320]
Reason, blue dye is a bit tricky to get a hold of at that stage.
Alternative allow any dye to be used in the gt crowbar.

**Comment by richardhendricks** [comment]
I'd also accept moving some of the flowers that make light blue dye to blue dye.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72228061-ebf82300-3568-11ea-9169-54dfeea63a00.png)
![image](https://user-images.githubusercontent.com/1214811/72228065-ef8baa00-3568-11ea-81e2-af774b91257e.png)
