### ISSUE TITLE
Infinite iron/steel through re-smelting/pulverizing boiler tanks.

### ISSUE THREAD

**Issue by HyloxalusFallax** [GTNewHorizons/NewHorizons#5321]
#### Which modpack version are you using?
 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SP

Low and high pressure boiler tanks from railcraft return 29 tiny piles of iron/steel after pulverization or the same amount of nuggets after arc furnace. But making them in the assembler only requires 3 ingots if you are using most effective recipes (extractor or cutting machine for machine parts). Re-smelting or pulverizing them should probably return only 27 of nuggets/tiny dusts.

**Comment by Dream-Master** [comment]
so far ik fixed in 2.0.8x but i will check

**Comment by Bluebine** [comment]
Can confirm, is still a problem in .8.1.

**Comment by Dream-Master** [comment]
ok
