### ISSUE TITLE
Quests needing ignore NBT enabled

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5323]
FIXED - First things first  (bees)

**Comment by ben0sharples** [comment]
Go find some bees (How to be(e) second quest)

**Comment by Bluebine** [comment]
Advanced circuit assembler II (1222)

**Comment by Ethryan** [comment]
The hp solar boiler got the wrong quest icon. It has the icon for normal solar boiler instead of hp one.

**Comment by richardhendricks** [comment]
all bee quests, all tree quests

**Comment by richardhendricks** [comment]
@ben0sharples Cannot reproduce your issue, please reset with 2.0.8.1 after executing
/bq_admin default load
on the command line while in cheat mode or on the server command line as
bq_admin default load

**Comment by ben0sharples** [comment]
I used the command block thing to run that command. Is there any difference with it explicitly through the command line?

**Comment by ScriptedPiky** [comment]
Multiple Thaumcraft quests involving wands, particularly the iron-capped and gold-capped wands and maybe the scepters need to have their NBT data set to ignore, as they've been a pain for MANY players for a long time already.

**Comment by Anarack** [comment]
A lot of the blood magic quest should probly get looked at as well, as a lot of the items get bound to a player.

**Comment by richardhendricks** [comment]
@ben0sharples there shouldnt be, but maybe it didnt take. Do you see the "Note:" in the quest? The current version is missing half the note, but should validate.

@ScriptedPiky The wand quests should all be good now. Please test and report separately, aince its a different issue.

@Anarack Can you test them? I dont have any experience with blood magic.
