### ISSUE TITLE
ars magica 2

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/NewHorizons#5325]
so today i was looking at ars magica 2 as a new mod for magic for the new update i think it would be fun add the mod for GTNH.

1st thing we need to talk about the occulus it is the item needed for upgrading your magic tree without it you cant learn any thing and you cant make any kind of spill so it will be the most needed item in the mod after the crafting alter, so i would suggest make it need some void plate and elder eye and some quantum eye in the infuser alter.

2nd is about the crafting alter ,it is where you make all your spell about this thing we need few things to know about ,at default it is really easy to make a high lvl crafting alter but we can change that by changing the 5 caps blocks for more expensive items we can use some of the same block used in BM alter, and the crafting alter block need to be locked in infusion and even at end IV or start or LuV.

3rd the lesser Focus (the basic) can be crafted in the arcan table from thaumcraft and need infusion to make the useful one.

4th we need to remove arcane deconstructor or make it only only disassemble spells.

5th about the essence refiner we can keep it or move all the items to BM Alchemic Chemistry for making all the essence.

6th we will have 5 new ores 
blue topaz = Al2SiO4(F,OH)2 <----already in GTNH {gem}
Sunstone = (Na,Ca)Al2Si2O8 {quartz}
Moonstone = KAlSi3O8 {quartz}
vinteum is dust?
chimerite is a magical crystal?
and about moonstone it fall from the sky we should disable that and make it as an ore in the moon.

7th there will be new kind of tree+ plant i think they should be craftable or can be sold in the shop.

8th there will be a teleportation like stargate using the keystone or receptacle .... idk what to do about it maybe lock it behind DE?

9th there will be liquid Etherium maybe make it craftable or sold in the shop as well and disable the normal spawning of it.

10th the blank rune will be blank slate in arcane crafting table and for adding color you need 4 dye with in the arcane table.

**Comment by mitchej123** [comment]
From what I recall, Ars Magica 2 is way too buggy... I don't want to support it.

**Comment by quedral** [comment]
I agree with mitchel123.
Back in the day it had so many bugs and spell crafting mutliblock crashed my server on several occasions.

**Comment by KaneHart** [comment]
Way too many issues. Neat mod some neat concepts but way too many issues and honestly I personally feel GTNH has too many magic mods already. They have yet to have time to Greg Witchery itself we don't need to be looking at another mod let alone having to fight to fix all the bugs and issues.
