### ISSUE TITLE
quest: Minor issue

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5326]
Better than iron - Can't smelt iron ingots into nuggets any more, have to use saw.

More advanced alloys - sideby

**Comment by Anarack** [comment]
Or the nugget mold for the alloy smelter.

**Comment by richardhendricks** [comment]
alumite - says leave rest of ardite, should be rest of alumite

**Comment by richardhendricks** [comment]
Tools - #5, missing text?
