### ISSUE TITLE
Quest "Getting Europium #1213" randomly.

### ISSUE THREAD

**Issue by RPG28** [GTNewHorizons/NewHorizons#5327]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 

#
#### What happened instead? (Attach screenshots if needed)
I noticed the quest was completed, and colored blue, and I could claim the reward despite being Tier .5. The pre-requisite quests had not been completed.
#
#### What do you suggest instead/what changes do you propose?
moronwmachinegun#5849 on the Discord told me to file an issue.

**Comment by Dream-Master** [comment]
The quest are open after fusion. Its not repeatable and looks like it ok. Not sure what i need to change here? @RPG28

**Comment by richardhendricks** [comment]
yeah the quest looks fine to me. Something must be bugged out in your quest file.  Try resetting the quest with
<open to lan, enable cheats>
<enter creative mode>
/bq_admin reset 1213 (your name)
<leave creative mode>
<leave to main menu, start world again>
