### ISSUE TITLE
Galacticraft 452

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#533]
@Teteros 

There is a new Version wich fix some thing in GC 451.

Can you update us GS compatible Version please.

Thanks

**Comment by Dream-Master** [comment]
If i am messed up here please fix ;)

https://github.com/GTNewHorizons/Galacticraft/releases

**Comment by Teteros** [comment]
You need to merge the [upstream/micdoodle8](https://github.com/micdoodle8/Galacticraft) GC repo with the changes from build you desire ([see their jenkins](http://ci.micdoodle8.com/job/Galacticraft-1.7/changes)). Only afterwards push the tag to trigger the build.

I suggest adding the upstream repo to your client as a remote to make this easier.

To do that go to your repo's settings in your git client and add a remote.
Alternatively, append this to _<Galacticraft local git repo>\.git\config_ file:
```
[remote "upstreamGC"]
	url = https://github.com/micdoodle8/Galacticraft
	fetch = +refs/heads/master:refs/remotes/upstreamGC/master
```
