### ISSUE TITLE
Remove Duplicate background from resources\mainmenu\textures and save 5mb!

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#5331]
bg.png and bg5.png are duplicates in resources\mainmenu\textures.

If you remove one or the other you save over 5mb of space and who can argue with that ;)

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
allready remove maybe only inside the mod itself. Will check

**Comment by Dream-Master** [comment]
fixed in 2.0.8.3
