### ISSUE TITLE
Charcoal pile igniter doesn't work

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5334]
Needs an end to end looksee.  Doesn't seem to work properly. Doesn't report properly via WAILA or hand scanner.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5323

**Comment by richardhendricks** [comment]
![Screenshot_20200113-072836_Discord](https://user-images.githubusercontent.com/1214811/72259574-6f9c2900-35d6-11ea-82d5-50808ee3d1b0.jpg)

**Comment by chochem** [comment]
details were posted here: https://github.com/alkcorp/GTplusplus/issues/606 (even though its not gt++)
But alk is already on it anyway.

**Comment by richardhendricks** [comment]
The GT5u code is still pretty bad and worth a looksee.  I might boost the output from the charcoal blocks as well.

**Comment by draknyte1** [comment]
GT++ Patched function.
```
	public static boolean isWoodLog(Block log) {
		boolean isLog1 = OrePrefixes.log.contains(new ItemStack(log, 1));
		if (isLog1) {
			return true;
		}
		ArrayList<ItemStack> oredict = OreDictionary.getOres("logWood");
		if (oredict.contains(ItemUtils.getSimpleStack(log))) {
			return true;
		}
		return false;
	}
```

GTNH Function
 ```
   private boolean isWoodLog(Block log, int meta){
        for (int id : OreDictionary.getOreIDs(new ItemStack(log, 1, meta))) {
            if(OreDictionary.getOreName(id).equals("logWood"))
                return true;
        }
        String tTool = log.getHarvestTool(meta);
        return OrePrefixes.log.contains(new ItemStack(log, 1,meta)) && ((tTool != null) && (tTool.equals("axe"))) && (log.getMaterial() == Material.wood);
    }
```
Vanilla GT5u Function.
```
    public boolean isWoodLog(Block log){
        String tTool = log.getHarvestTool(0);
        return  OrePrefixes.log.contains(new ItemStack(log, 1))&& ((tTool != null) && (tTool.equals("axe"))) && (log.getMaterial() == Material.wood);
    }
```

GTNH Can just disable the patch in ASM.cfg, the existing method for NH is probably sufficient.. Although it doesn't work for Rainforest Oak Logs, so it's still buggy. (Tool check is redundant)

**Comment by draknyte1** [comment]
Fixed in https://github.com/alkcorp/GTplusplus/commit/0ec85b9bb29ce98904d627c45af628013d1da969.

**Comment by richardhendricks** [comment]
Looked at brittle charcoal block, they already can drop more than 1 charcoal, so it is slightly more log efficient to use this machine than the coke oven.  Think we can leave it as-is.

**Comment by richardhendricks** [comment]
Looks like CPI works with all expected logs now.
