### ISSUE TITLE
Make Marshmellows craftable

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#534]
Any recipe suggestions.
Dragon Egg and Draconic Powder maybe at IV?
or Bees eventually?

**Comment by Technus** [comment]
Assets:
https://www.dropbox.com/sh/ob2kob7zz4j7ynh/AACYcE3FX-n18AVk1wjVbHPia?dl=0

**Comment by Teteros** [comment]
If you refer to _Dezil's Marshmallow_ from DE, please don't make them obtainable via usual means. It's a creative only item [solely meant for player called _dezil_nz_](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-2-snapshot-10?comment=667) by the DE devs.

I feel allowing feats like punching the ender dragon to death with zero gear shouldn't be so accessible. Special HQM/quest only reward sure, easily craftable at a certain tier, no.

Note this is just my feedback feel free to add it if you feel the recipeis balanced enough.

As a side note:
I think it's funny this issue popped up, as I was writing a listener for the coremod to block this particular item from being consumed for #536, but I wasn't sure whether to make a pull request or not :)
![marshmallow](https://cloud.githubusercontent.com/assets/5067989/13799159/f17780b6-eb14-11e5-960f-78c08bd7593d.png)

Apparently the

**Comment by Dream-Master** [comment]
Why you won't let people consumed this item ?
My recipe is hard (IV Tier) and time intensive but i can put it to infusion to.
Any recipe suggestion?

**Comment by Teteros** [comment]
Looking at the assets, a TC infusion is what I was imagining. Since to make it glow (phase 3) you could require infusion indeed.

At the moment even [quantum bread](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/6acc9582a0ef86a2025318f09c0d13bd2d2351fa/src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java#L1164) has a higher tier requirement.

**Comment by Namikon** [comment]
I agree with Teteros on that. The Quantum bread was introduced because of the marshmallow being way to overpowered for having a crafting recipe

**Comment by Dream-Master** [comment]
But if the villager trade disabled you can't get this item. I will change the recipe to a higher tier to be sure this is balance.

**Comment by Dream-Master** [comment]
Lets test the new recipe and we will see.
