### ISSUE TITLE
Quest suggestion: Biome changing questline

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5341]
I wrote some quests for how to change biomes so people know how to do so. You'd probably mostly want it if you want to do crops/bees, so it starts there. It's my first time suggesting/making quests, so I'm sure I messed up somewhere.
 I don't think it's really worth it to have separate quests for the first two (BM Ritual and WG device), since in comparison they're not nearly as good. Feel free to make quests for them if you want? 
For the range of the SS Rite, https://www.reddit.com/r/feedthebeast/comments/3a5a6m/witchery_range_of_rite_of_shifting_seasons/ says it's "8 * (size of coven - 3)", however what I got when I tested was 

<4 Fail to activate
4=16
5=32
6=48
6 is max in coven

so it should be 16 * (size of coven - 3), keeping in mind this is the radius of a semi-circular area, so you won't get the corners.
Some of the names are a little boring, feel free to come up with new names. Similarly, I'm not really good at coming up with rewards, Witchery doesn't really have a lot of interesting stuff for that.

#

Biome Changing (should be linked from 721 - 'Unknown seeds no more' on the fishing farming cooking tab, copy linked from 992 - 'Go find some tropical bees' on the how to be(e) tab, unlock from either) (Maybe use a more fun name?) (maybe too much info on reqs?)

So maybe you can't find a swamp or tropical forest for your crops or bees, or maybe they're too far away so they're inconvenient to get to, or maybe your base is in a colder climate and you have to deal with the howls of direwolves constantly. Instead of packing up all your stuff and moving somewhere else, why not try changing the biome? There are a couple different ways to do so in this modpack:

Use the Arcane Terrestrial Reformer from Witching Gadgets
-Requires EV Circuits, Tungstensteel, Rocket Tier III
-Also requires Infusion, Void Metal (sufficient warp), Energized Node for CV, lots of Essentia
-16 block radius
-Can only change to a few specific Vanilla or Thaumcraft biomes
-Kind of slow

Use Ritual of Gaia's Transformation from Blood Magic
-Requires Void Metal, Infusion, Tungstensteel
-Requires getting deep into BM (and the warp that come with it)
-Requires 1,000,000 LP, Master Blood Orb, Tier 4 Altar and Awakened Activation Crystal
-10 block radius, can be exactly specified with bloodstone bricks (either type)
-Cannot specify which biome you get, you can only change the temperature/humidity within the 0.0 - 2.0 range and hope
-Some biomes may be impossible due to limited range and overlap
-Adjust temperature/humidity with items on 8 plinths around Master Ritual Stone
-Need to relog to see changes
-Very little documentation or explanation
-Fast

Use the Brew of Shifting Seasons from Witchery
-Small range, depends on the level of the brew (power, not dispersal extent)
-Biome can be exactly specified
-Crafted using the complicated custom brew system
-Can add different ingredients to change range of the brew
-At min changes a single block
-At max has about a 3 block (circular) radius
-Instant (once you use it)

Use the Rite of Shifting Seasons from Witchery
-Requires Stainless Steel, Greatwood Scepter or better for the Distillery
-You have to do a bunch of witchery stuff
-Not hard once you're done it once
-Extremely large range, 16/32/48 block radius
-Biome can be exactly specified
-Sometimes fails in specific chunks
-Very Fast

If you want to know how to use the Witchery methods, please go to the Look to the edges tab to continue.

PSA: The IC2&Galacticraft Terraformers only change the surface, not the biome itself.

(no reqs to complete, no reward)

#

Changing Biomes With Witchery (linked from Distillery, should require above to show up, Look to the edges tab) (name is kinda boring)
There are two ways to change biomes with Witchery, the easy way or the hard way, choose which one you want to do (or do them both).

(no reqs to complete, no reward)

#

The Easy Way to Change Biomes (linked from Changing Biomes With Witchery, Look to the edges tab)(It seems your brewing expertise needs to be over level 30 to have a chance at a second brew, what a gyp!)
So you want the easy way? Ok, go get this stuff:
Mandrake Root, Nether Wart, Tear of the Goddess, Diamond Vapor, and a Diamond.

Then toss it in the Witch's Cauldron IN ORDER, before also tossing in a page from the Book of Biomes (Extended) (craft it with a piece of paper while on the page of the biome you want), followed by a bit of Gunpowder.
Then just use a bottle to get the brew. If wearing your Robes or Hat, you may even get more than one! (If you have a ton of brewing expertise, which is unlikely)

If it failed, you may not have enough Altar Power, you need 5450 at least. Try placing down a Dragon Egg or Demon Heart if you're close. Check a wiki for more details on altar power.

If you want to have more than a single changed block, then add Glowstone Dust, Blaze Rod and Attuned Stone (Charged) in order to increase the effect (and Altar Power cost slightly) by +1 for each. Do this before adding in the page.

For more detailed info, check out the Witches' Brews book. Click on Brewing, then go to the Brews: Step-by-step page. This should tell you what you need to know. For what each of the brews actually does, see the Effects page.

(Reqs: 1 of Mandrake Root, Nether Wart, Tear of the Goddess, Diamond Vapor, Diamond, and Gunpowder. Reward should be Attuned Stone (Charged)/A brew that's Level IV for a good biome (rainforest/swamp?)/something else?

#

The Hard Way to Change Biomes (linked from Changing Biomes With Witchery, Look to the edges tab) (part one? the start/beginning? name is boring)
Ok, to have a ritual with a size greater than zero, you need to get Coven Witches to acknowledge you and then agree to help you out. To get them to deign to speak with you, you can either infuse yourself or bind a familiar. In this quest line we'll be covering binding a familiar, but for the people who want to do infusion, you just need to make the appropriate item: Ghost of the Light, Soul of the World, Spirit of Otherwhere, or Infernal Animus, and do the appropriate Rite of Infusion. Be sure to have a Death Protection Poppet to protect you, because the ritual kills you. If playing hardcore, definitely test in a separate world first.

To bind a familiar, first, summon a Demon and tear out it's heart. No, seriously, go do it. Use an Arthana with Looting III for the best chances. If you don't know how to summon one, refer to page 49/50 of the Circle Magic book for the correct Rite of Summoning. 

You'll need a Mutating Sprig for the next part.

(Reqs: Demon Heart, reward:another heart?)

#

More Hearts for Valentines (linked from The Hard Way to Change Biomes, Look to the edges tab)
If you want to get more hearts, you can try trading with the Demon, but they're more likely to shoot fireballs at you than trade. Unless you have this item that is! First, make the Polynesia Charm that allows you to trade with animals (probably not worth it in this pack), then use the demon heart to make the Devil's Tongue Charm. With this, not only are they a lot less likely to attack, they will even sell their brethren's hearts for a little less.

Just remember that it can only be used a limited number of times, ok? It might also be worthwhile to use the Rite of Protection at the same time as summoning a demon. To do so just put down both circles, and meet the item (and Altar Power) requirements of both. If you're not planning on killing the demon, you should probably send it back when you're done with the Rite of Banishing on page 47/48 of the Circle Magic book.

(Reqs: Devil's Tongue Charm, reward:another one?, something else?)

#

Are You Grassping What I'm Telling You? (linked from The Hard Way to Change Biomes, also linked from Mutating Sprig, Look to the edges tab) (intentional misspelling in the title)(Should it say Tall Grass? That isn't the name even if that's what everyone calls it)
To make Grasspers, first you need to arrange Grass in the cardinal directions around a Chest above a block of water. Then right-click the Chest with your Mutating Sprig.

(Reqs: 4xGrassper, reward:not more grasspers for sure)

#

PETA Approved* (linked from The Hard Way to Change Biomes, also linked from Mutating Sprig, Look to the edges tab)
To make Critter Snares, first you need to arrange Alder Saplings in the cardinal directions around a Cobweb above a block of water. Then get a zombie to walk onto it and right-click the Cobweb with your Mutating Sprig.
This will change the Saplings into the needed Critter Snares. Do this twice. (*May not be PETA approved)

(Reqs: 8xCritter Snare, reward:also not more snares)

#

Mad Science is the Best Science (linked from PETA Approved*, also linked from Are You Grassping What I'm Telling You?, Look to the edges tab)
Next we need to fill our snares up with some critters, specifically Bats and Slimes. For the Bats, just place them beneath you and AFK if your warp is high enough to spawn bats, otherwise...uh, go caving?
For the Slimes, if you can't find any just use the Maze Slimes from the Minoshroom maze in the Twilight Forest for this. After you get them, also go collect a Wolf and an Ocelot (Lassos or Soul Vials are great for this). 

Now we'll be creating new life, specifically Toads and Owls. Arrange a Cobweb above a water block with grasspers at the diagonals and one of the two sets of snares in the cardinal directions. Place Attuned Stone (Charged) in all 4 Grasspers. Then place one of the two animals in the center and right-click with your Mutating Sprig like when making the snares. Use the Wolf with the Bats, and the Ocelot with the Slimes. The tamed versions also work.

Congratulations, you've defied the natural order and created new life! Hopefully they didn't run away because you created them outside :(
 Make sure to breed them for the next part. Use Raw Porkchop or Raw Beef for Owls, and Rotten Flesh for Toads to both tame and breed them.

(Reqs: 4xCritter Snare (Bat), 4xCritter Snare(Slime), reward:attuned stones maybe?) The Metadata is 1 and 3

#

Finally Binding a Familiar (linked from Mad Science is the Best Science, Look to the edges tab)(the familiar death thing didn't kill me, so like wth? Does chunk loading affect it? Can you toss it in a lasso to be safe? etc. Name is also boring)
Now that you have Toads and Owls, you can choose between them and Cats to bind. Why didn't we just bind a Cat earlier? Well, you'll need them both soon anyways, and who doesn't love choices? To carry out the Rite of Binding (P6, Circle Magic), you'll need to distill some Demonic Blood. Do that now, and collect the rest of the items needed.

After collecting the items, bind your familiar using them. Make sure you have enough Altar Power. Remember that each has different benefits. See the official wiki for details. You may receive a tiny portion of damage your familiar receives (and vice-versa), so park it somewhere safe. Also note that if it dies, so will you.

Now go murder a few of your new friends and tear of their Owlet's Wings, and cut off their Toe of Frog. Remember to use an Arthana. The next step needs a Seer's Stone.

(Reqs: P1: Tear of the Goddess, Odour of Purity, Whiff of Magic, Diamond, Demonic Blood. P2: Owlet's Wing, Toe of Frog. reward:more wings and toes?) (There's some you get (the demonic blood) from a quest reward, Nimbus 1999 - 342, a little unbalanced maybe? You probably wouldn't have used it until now, so you can skip killing a Demon if you use the reward. Well, if you don't do the quests anyways)

#

Greenhouses on Mountains, Hell on Earth (linked from Finally Binding a Familiar, seer stone or summon the witches, Look to the edges tab)
You're almost there! To actually use the ritual, you need to recruit a coven first. Find some Coven Witches and complete their quests:
The means to control the dead -> Necromantic Stone 
The beating means to master the infernal dimension -> Demon Heart
I must perform many curses, bring me the necessary brew -> Brew of the Grotesquex5
I desire to predict the future	-> Crystal Ball
Or just fight something.

Once completed, they'll disappear until you need them. They will sometimes appear near your spawn point if you walk by it, so don't position it over lava or something, since they CAN die and reduce the number of your coven. You can have 6, with one extra appearing for Cauldron work. Consider keeping some extras around in a dungeon just in case.

After you recruit your coven, you just need a few things for the ritual itself: Spider Eye, Toe of Frog, Wool of Bat, Tongue of Dog, Owlet's Wing, Attuned Stone, and Attuned Stone (Charged).

To specify the biome, look in the Book of Biomes, and find 1) the type (Forest, Plains, etc), and 2) the number. Type determines the foci used, and number determines the amount of glowstone used to get that specific biome. Make sure to pack up a ritual circle into a circle talisman so you don't have to redraw it, and bring some cobblestone to make a flat area (15x15, any height). Try not to do it at night unless you like dealing with infernals.

To actually do the ritual, have the ritual circle on the ground, the items (including the foci and glowstone) in the circle, and right-click the center with the Seer's Stone.

Unfortunately, sometimes after logging out and back in again you may find that it didn't work correctly in specific chunks, this is (possibly) due to lack of chunk updates and it not saving the changed biome ID correctly. Just redoing the ritual doesn't really help, you'll just get patches in the same places, however placing water after the ritual and before logging out may help with this. Or use chickens. Lots of Chickens.

PSA: To pack your circle back up, you need to bring your altar with you.

Reqs: Spider Eye, Toe of Frog, Wool of Bat, Tongue of Dog, Owlet's Wing, Attuned Stone, and Attuned Stone (Charged), reward: 5xingredients+stack of glowstone?, something else?)

**Comment by combusterf** [comment]
The most ghetto biome changer is missing from this list - the good old Silverwood tree that turns every biome into a starter bee friendly one.

So it might be nice to open up an additional silverwood quest in the "how to bee" section together with the biome finder, and then branch out the above quests as "long term" goals roughly when the appropriate tabs unlock. Kindof like how the dimensional goal quests work on the tier tabs despite the number of intermediate steps left to take.
- EV hull + gold/greatwood wand -> terrestrial reformer quest
- Witches oven -> witchery brew quest
- Ritual chalk -> witchery coven quest
- Blood altar -> BM ritual quest

----

Flavour text:

Standing under the glow of the majestic Silverwood, you notice the bees happily buzzing around. Maybe if I plant one at home, it will make my own bees happy as well?

I notice this method does not always work the first time, and only gets me a Magical Forest biome. If I pay more attention, I might learn why. I might even learn other magical ways to bring any biome to me, rather than having to bring myself to that biome.

**Comment by Prometheus0000** [comment]
While I don't hate the idea of unlocking quests as you progress, the problem is that the non-witchery methods (except nodes) completely suck. There's no point having quests for them that unlock later but are less effective and much more expensive, that's just mean to the players. 

For the witchery stuff, it's all unlocked once you get the Distillery (yes you need it for the brew as well), which just requires Stainless. You might be able to get a head start on some of the stuff, like killing demons or making the toad/owls, but the quests require basically nothing for the first quest (so you can see the ways you can progress), and you can't do anything useful until you get Stainless for the Distillery anyway (which also allows the wand to make it).

For the nodes, I did some research:
Sinister node - > Eerie biome - radius 11 (produces Furious Zombies from the node)
Sinister (totem) node - > Eerie biome - radius 11 (produces Furious Zombies from the node)
Pure (tree) node - > Magical Forest biome - radius 11
Pure node - > does nothing by itself unless it has victus supposedly
Tainted node - > Tainted Land biome - radius 11 (produces fibrous taint, very unsafe)
All biomes count as Normal/Normal for bees.

Maybe a quest should mention all of these, not just the silverwood node? You can also change nodes to different types using the Thaumic Bases Node Manipulator, but that's EV-tier.

Bare pure nodes are supposed to be able to act like Ethereal Blooms, and purify eerie/tainted/magical forest biomes back to the way they were. In practice, it only worked on Tainted Land. Radius of 7?

Ethereal Blooms should be able to revert biomes, but only work at a decent speed for eerie it seems. Radius of 7. They don't revert witchery changed blocks, but if you W.Ritual ->Sinister node -> E.Bloom, it'll go back to the original biome.

I initially suggested linking from the tropical bee quest because I didn't think many people would make the habitat locator, I know I didn't. But since you can now see 1 quest past the next one, it probably would make more sense to link it from it. Is there a quest for the Nature's Compass item? Maybe add that in on the bee page as well.

**Comment by richardhendricks** [comment]
There already is a quest for the Nature's Compass. I think it is in Steam or LV?  It requires a Compass first, which has certain requirements. We can add a mention to it from the bee pages.

**Comment by richardhendricks** [comment]
- [ ] Add mention of Nature's Compass to Tropical bee quest.  It's the only bee that is kinda hard to find because its biomes are so infrequent.  Test and list the relevant biomes for them to appear in game.

**Comment by Prometheus0000** [comment]
It seems it's linked off the LV assembler. I couldn't find it before, though I didn't look that hard.

**Comment by Prometheus0000** [comment]
As noted by dgamer1993 (and me, I just forgot before) if you use the SS ritual where there are already crops, they disappear (looks like empty crop) until a block update or relog. This probably should be mentioned in the last quest.
