### ISSUE TITLE
Fix for questbook losing sound

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5342]
Fixed my sound thing -- this was in a new world and it looks like the default quests were wrong. They override the default sound for each individual quest, all are minecraft:entity.player.levelup, which doesn't seem to exist in 1.7. Find/replaced all with random.levelup, reloaded defaults in world, my ding noises are back

**Comment by richardhendricks** [comment]
Check on newly created quests too

**Comment by richardhendricks** [comment]
File ticket on BQ3 if necessary

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/NewHorizons/issues/5078 for the question

**Comment by richardhendricks** [comment]
ok thanks chochem
