### ISSUE TITLE
[quest] How to open your Wooden Doors?

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NewHorizons#5345]
#### Which modpack version are you using?

2.0.8.1

#### What did you try to do, and what did you expect to happen?

Following the `How to open your Wooden Doors?` quest, first stage asks for `5 × slabWood`.

The wooden slab part of the quest will validate with any kind of wood slab; 
but the next step requires `10 × oak wood plank covers` that can only be crafted from Oak wood slabs.

#### What happened instead? (Attach screenshots if needed)

I was stuck with Sacred Oak wood slabs that validated the first stage of the quest but was unusable for the last step.

#### What do you suggest instead/what changes do you propose?

I suggest changing the first part of the quest with `5 × Oak Wooden Slab` rather than the ore-dictionary `slabWood`, or directly asking for `10 × oak wood plate`.

Incidently, Gregtech wood plank covers could be registered as `plateWood` and the ore dictionary `plateWood` used in recipes rather than item references. It would at least allow use of all vanilla wood types and the first forestry wood types.

Another possible enhancement would be adding recipes for wooden slabs to wood plate covers of unknown wood type (Natura, BOP, Binnie, TwilightForest) to produce oak wood plate covers as a fallback.

**Comment by richardhendricks** [comment]
There is a coins quest to purchase all the vanilla tree types, including the oak.  I'll change the quest to require oak wood and put a note there to purchase some oak saplings.
