### ISSUE TITLE
Allow Hardcore Questing mode

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/NewHorizons#5349]
#### Which modpack version are you using?
2.0.8.2
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
playing with bq_admin hardcore enabled, trying to use the extra life item, it should give +1 life
#
#### What happened instead? (Attach screenshots if needed)
you can't use it, you just get a purple text (same one as trying to use fe a slime bucket)
![image](https://user-images.githubusercontent.com/7458440/72514581-01ae6680-384f-11ea-9045-8454cda63424.png)

#
#### What do you suggest instead/what changes do you propose?
enable the extra life item to give an extra life

**Comment by Dream-Master** [comment]
@sethdark i disabled it because normaly we dont play Hardcore and the heart consume crash the game if you not in HC mode.
If you need this enabled change the config:

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GTNewHorizons/blocklimiter.cfg#L22

**Comment by sethdark** [comment]
Super Thank you!

**Comment by richardhendricks** [comment]
I'll add a comment tonight to the Better Questing quest telling players this.

Actually @Dream-Master  have we tried this with BQ3? Maybe it doesnt crash any more.

**Comment by richardhendricks** [comment]
OK I tested it, they no longer crash the client.  I will remove them from Block Limiter.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72581609-93e15980-38a5-11ea-92bf-e24372af225f.png)
