### ISSUE TITLE
Object Holder recipe

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/NewHorizons#5351]
#### Which modpack version are you using?
2.0.7.5
#

Recipe requires 1000L of molten iridium when each ingot gives 144L... It should really be a multiple of 144, change it to 1008L since 1008/144 = 7 exactly even if it technically costs more.

**Comment by draknyte1** [comment]
Cells hold 1000L though. 🤷‍♀

**Comment by GTNH-Colen** [comment]
> Cells hold 1000L though. 🤷‍♀

Obviously but it's bad practice to make recipes use non-multiples of 144 if they're gonna use a molten metal, it makes automating said recipe a pain in the ass. Most recipes follow this rule, only a few exceptions like this exist. It's hardly game breaking but just makes life awkward for no real reason.

**Comment by draknyte1** [comment]
> Most recipes follow this rule

I literally avoid it wherever possible. Round numbers don’t trigger my OCD. The only real exception is auto generated material recipes.

**Comment by repo-alt** [comment]
Doesn't leftover molten metal trigger your OCD ffs

**Comment by draknyte1** [comment]
No, because it’s always In cells or tanks. Weird amounts get plungered or hand pumped. (Sole reason it exists because wasting is bad)

**Comment by repo-alt** [comment]
So, you disagree that an original state of a molten metal is a metal ingot? because otherwise where do you get those cells from?

**Comment by yukieiji** [comment]
It seems to be fixed in the current GTNH ver2.0.8.2.
https://github.com/Technus/TecTech/blob/b6e12a2c46fba15f5205a1d0c2f85408d8e8b9be/src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java#L425

**Comment by GTNH-Colen** [comment]
> > Most recipes follow this rule
> 
> I literally avoid it wherever possible. Round numbers don’t trigger my OCD. The only real exception is auto generated material recipes.

GT++ has actually been super consistent in this regard, unless we've changed the recipes molten metal amounts for GTNH. All the multiblocks/items that i've got on autocraft from your mod have worked perfectly fine as they're multiples of 144, it's mostly tectech that has been doing this.

**Comment by GTNH-Colen** [comment]
> It seems to be fixed in the current GTNH ver2.0.8.2.
> https://github.com/Technus/TecTech/blob/b6e12a2c46fba15f5205a1d0c2f85408d8e8b9be/src/main/java/com/github/technus/tectech/compatibility/dreamcraft/DreamCraftRecipeLoader.java#L425

Thank you, I wasn't aware of this. In any case this should be common practice as to make the users life more bearable. ;)

**Comment by draknyte1** [comment]
> GT++ has actually been super consistent in this regard,  

Because...  
>The only real exception is auto generated material recipes.


> should be common practice as to make the users life more bearable

Most of us don't mod for the users sake, but our own. If I cared about the users, it would be far more apparent. :')
