### ISSUE TITLE
CircuitAssemblyLine recipe is different from NEI

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5352]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
My Server
#
#### What did you try to do, and what did you expect to happen?
I tried to check CircuitAssemblyLine recipe.
#
#### What happened instead? (Attach screenshots if needed)
The plate put in the seventh input bus is different.
・NEI
![2020-01-17_00 50 10](https://user-images.githubusercontent.com/40425798/72545399-504e1600-38cc-11ea-83f0-76e9966e8439.png)
・Data Reader
![2020-01-17_00 51 03](https://user-images.githubusercontent.com/40425798/72545400-504e1600-38cc-11ea-8a18-8ca2081bb061.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by bartimaeusnek** [comment]
https://github.com/bartimaeusnek/bartworks/commit/583bb0a71c698d59150450336d9493f8016b260f

**Comment by yukieiji** [comment]
@bartimaeusnek Which recipe is the correct CircuitAssemblyLine recipe?

**Comment by bartimaeusnek** [comment]
@yukieiji in your case, the chrome is written onto the stick, as you can see in the reader, next version will have the Rh/Pd, but if you want that recipe, you need to re-scan the stick
