### ISSUE TITLE
Legendary Tier X Questline

### ISSUE THREAD

**Issue by TechnicianLP** [GTNewHorizons/NewHorizons#5353]
While the idea of the Questline telling a Story is quite nice, there should be a way to determine (without edit mode) which items are required for the next hidden quest.
I suggest adding some better hints and to make the Triggers more logical
An Idea:  the first two hidden Triggers talk about a Casing melting and a better Material being required; Change that Trigger to either the Ingots or the Casing/Hull instead of requiring the unprocessed Ore, as most should have all Ores automated at that Point and never handle the Ore manually anymore.

**Comment by richardhendricks** [comment]
I added this info to the quest previous
