### ISSUE TITLE
Backpack: A loophole in the big backpack recipe！

### ISSUE THREAD

**Issue by ENNISHIBUYA** [GTNewHorizons/NewHorizons#5356]
#### Which modpack version are you using?
2.0.7.5 & 2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Non-server, But the server may be the same...
#
#### What did you try to do, and what did you expect to happen?
I try to process the small backpack and eight Tanned Leather in the Crafting Table
#
#### What happened instead? (Attach screenshots if needed)
The script of the Big Backpack can be obtained through a small backpack and eight Tanned Leather. (Circled)
![2020-01-15_15 20 28](https://user-images.githubusercontent.com/34373971/72581668-1a844e00-391b-11ea-9ac0-a26937e85f83.png)
#
#### What do you suggest instead/what changes do you propose?
Modify Backpack config：
I changed it to [True] to solve the problem
![000](https://user-images.githubusercontent.com/34373971/72581828-a5fddf00-391b-11ea-9d9e-c3f5a7b6122f.png)

**Comment by richardhendricks** [comment]
Confirmed config change blocks easy recipe, and that gregified recipe still works fine.  Thanks for the info.
