### ISSUE TITLE
Villagers still offer DE Marshmallows for trade

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#536]
iRage2Win from @ProsperCraft reports he still has access to the villager who is selling a stack of DE marshmallows for an emerald.

This probably means either of these (or both):

1. Disabling the ["butcher trades"](https://github.com/GTNewHorizons/NewHorizons/blob/master/config/HungerOverhaul/HungerOverhaul.cfg#L197) affects only harvestcraft items. (something else adds it?)
2. Villagers already present in the world with those trades keep them as is.

To make sure, one would need to make sure the config is set properly and find some new villagers to test it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/2c06e96042519747eb6e8d0a94fe3e17ccd168f2

**Comment by Teteros** [comment]
Isn't that file... default.cfg? As in, not used because HungerOverhaul.cfg is the main one.

**Comment by Namikon** [comment]
I'm about 99 % sure that this is / was fixed on the testserver that I had set up; as I searched a butcher and unlocked all of his trades. You may check those config files. Only if they are still unchanged of course. And yes, it's not default, it's HungerOverhaul. 

The butcher that was found should also sell the high tier pam's foods. If not, then something else is adding the mallow now

**Comment by Technus** [comment]
Isn't the amount of trades added that way > the amount of trades that one villager can offer?

**Comment by Namikon** [comment]
It is. But since the butcher I had didn't sell any pam's food right after the restart and the way in terms of code that was used to add the high tier foods as trade, gives only this one  option. That full stack trade for 1 emerald is definitely HungerOverhaul

**Comment by Dream-Master** [comment]
I not seen the butcher trade the Marshmallows any more afte the cfg changes. Will see in the future.
