### ISSUE TITLE
CircuitAssemblyLine consumes Imprinted Circuit on first time.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5361]
#### Which modpack version are you using?
2.0.8.0Pre～2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
Single and Multi
#
#### What did you try to do, and what did you expect to happen?
Used for the first time after build up CircuitAssemblyLine.
#
#### What happened instead? (Attach screenshots if needed)
Imprinted Circuit that shouldn't be consumed, but it consumed and never returned...
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
intended
