### ISSUE TITLE
Fluxed electrum no mixer recipe, only shapeless 

### ISSUE THREAD

**Issue by firendlyGhost** [GTNewHorizons/NewHorizons#5366]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
no
#
#### What did you try to do, and what did you expect to happen?
check NEI, see a mixer recipe for fluxed electrum
#
#### What happened instead? (Attach screenshots if needed)
there is no mixer recipe, only a very inefficient shapeless one ( 8dust input-> 4 output)

#
#### What do you suggest instead/what changes do you propose?
that a recipe in a mixer be added, its a pretty easy fix

**Comment by Dream-Master** [comment]
will add.

**Comment by quedral** [comment]
doesn't mixer has 6 slots?

**Comment by firendlyGhost** [comment]
Oh right, oversight on my part, all the 8 dusts are different, maybe a recipe change or a 1:1 shapeless output would be best

**Comment by Dream-Master** [comment]
or a mixer with 9 slots ?

**Comment by firendlyGhost** [comment]
i mean if you can make that happen go for it seems like the perfect solution, won't that brek other stuff tho, like GUI and texture packs?

**Comment by Dream-Master** [comment]
Yes Gui i can rework like for the assembler but not the texture packs

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/72648643-db3a1980-397b-11ea-9e57-f784e0201e25.png)

**Comment by firendlyGhost** [comment]
Awesome!

**Comment by Dream-Master** [comment]
Only recipe need to be added
