### ISSUE TITLE
One CircuitAssemblyLine can only create one type circuit

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5367]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
multi and single
#
#### What happened instead? (Attach screenshots if needed)
One CircuitAssemblyLine can only create one type circuit In GTNH ver2.0.8.1.
#
#### What do you suggest instead/what changes do you propose?
I suggest that be able to create multiple types of circuits with one CircuitAssemblyLine or lower the cost of creating CircuitAssemblyLine.
At present, CircuitAssemblyLine requires nearly 4units of LuVTier, but I think it is difficult to make that 4units with that Tier....

**Comment by bartimaeusnek** [comment]
Nope.

**Comment by yukieiji** [comment]
why?
One CircuitAssemblyLine requires ZPMCircuit×6, LuVCircuit×34, IVCircuit×30, and it seems that it is a little expensive assuming that multiple units are created with LuVTier...
