### ISSUE TITLE
request to change the new witchery  quartz crystal recipe 

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#5369]
#### Which modpack version are you using?
.8.3
#
well the recipe is okay, its not hard, its pretty cheap once you're late MV/HV , but quartz crystals are pretty much not very useful, only two rituals require them, the ones that make 1. seer stone: a witch tool to see what curses you got, how many coven witches, and your witch levels and 2.crystal ball: can "predict the future", if used extensively can summon a weak boss.

it also has a 3rd use, a vampire requires it to level up to level 5 which gains temporary protection from the sun, enough for the vampire to escape the sun.
the problem lies is that vampire needs 10 of them to make it, and the current recipe is HV since you will need a greatwood wand to make it.

![ohgodpleaseno](https://user-images.githubusercontent.com/40670872/72646376-ac717280-397e-11ea-894c-717bf7eb8dde.png)

#### What do you suggest instead/what changes do you propose?
i suggest the recipe to atleast be changed so we can make it at steam/lv
maybe same recipe but in normal crafting table?

**Comment by Dream-Master** [comment]
I can make it cheaper but it fits into thaumcraft. So make it use 25 vis much and maybe another crystal in the middle to make it mid lv able.

**Comment by PoptartOverlord-Xabedo** [comment]
mid Lv sounds good

**Comment by BlackFlameTNT** [comment]
... But thaumcraft is already at start of MV

**Comment by PoptartOverlord-Xabedo** [comment]
i just saw something bad, it needs this, which makes it EV.
![image](https://user-images.githubusercontent.com/40670872/72649571-bac38c80-3986-11ea-88e9-cb6e6b7277a1.png) 

well you can also use 
![image](https://user-images.githubusercontent.com/40670872/72649651-eba3c180-3986-11ea-972a-42cda06a33ea.png)
which makes it behind HV, since implosion compressor needs HV circuits

**Comment by PoptartOverlord-Xabedo** [comment]
maybe change it to glass lens instead?

**Comment by Dream-Master** [comment]
i said i will change that leans and the vis usage

**Comment by PoptartOverlord-Xabedo** [comment]
lmao im blind, sorry
