### ISSUE TITLE
Create InGameInfo.xml

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#537]
Default InGameInfoXML configuration conflicts with other interfaces such as WAILA's:
![ArmourWailaGUIConflict.jpg](https://cloud.githubusercontent.com/assets/5067989/13802668/f1d6ccc6-eb35-11e5-8e50-bef6780918bf.jpg "IGIXML Armour conflicting with WAILA block info")

[InGameInfoXML mod is pretty modular and flexible.](http://mc.lunatri.us/wiki/mods:ingameinfoxml#commands)
Eventually we could make/improve the user interface with it.

First and foremost, conflicts with other GUI mods need to be fixed though:

- [ ] Armour/WAILA conflict (Right-bottom corner)
- [ ] TC/GC conflict (Left-upper corner)
- [ ] DE w/ tools (not sure if global)(Left-bottom)

**Comment by Technus** [comment]
InGameInfo.xml can be edited in game via mod options.

**Comment by mrgreenacid** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/306cad6849cc7a8e9f7697ad9309fba04d19931a

Closed?

**Comment by Technus** [comment]
More like yes.
