### ISSUE TITLE
I can't build Chemical Plant

### ISSUE THREAD

**Issue by Mr233sir** [GTNewHorizons/NewHorizons#5374]
#### Which modpack version are you using?

#2.0.8.1 
#### If in multiplayer; On which server does this happen? 

#in singleplayer
#### What did you try to do, and what did you expect to happen?

#I followed the guide to build the Chemical Plant.
#### What happened instead? (Attach screenshots if needed)

#It didn't work.

**Comment by draknyte1** [comment]
You built it wrong.
https://cdn.discordapp.com/attachments/234936569360809996/666023330339487757/image0.jpg

**Comment by Mr233sir** [comment]
Thanks,I filled the surface……

**Comment by daddy77gaming** [comment]
Just a FYI for ANYONE using this picture as a guide.. the structure it shows is FINE.

JUST DO NOT USED MACHINE HULLS as stated in it!

**Comment by Prometheus0000** [comment]
Did you read the quest? It says to use machine casings. Was it not clear?

**Comment by daddy77gaming** [comment]
You can imagine someone using that picture circulating (bc its a new thing) on a second monitor to build and gather recourses.. in which case they MAY end up with 57 hulls.

**Comment by Prometheus0000** [comment]
I already mentioned it to alk before, they didn't change the image. And that was before it was in GTNH. Maybe make your own picture for others to use? Or edit it?
