### ISSUE TITLE
New language files didn't update

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5375]
#### Which modpack version are you using?
2.0.8.3 reupload version of Technic Launcher
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
I checked the language file of betterquesting under resources\minecraft\lang.
#
#### What happened instead? (Attach screenshots if needed)
The language file of us and cn was different from the version that posts on GitHub.
#
#### What do you suggest instead/what changes do you propose?
Please upload the correct version of the translated language.

**Comment by Dream-Master** [comment]
ah ok will do that asap
