### ISSUE TITLE
Crafting or inventory 2x2 crafting grid broken

### ISSUE THREAD

**Issue by urso90** [GTNewHorizons/NewHorizons#5377]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
crafting flint in 2x2 inventory crafting grid.
#
#### What happened instead? (Attach screenshots if needed)
Internal error - disconnect
#
#### What do you suggest instead/what changes do you propose?
Fixing bug - it blocks new users from progressing (they can still use /craft or /workbench when its available becouse normal 9x9 crafting grid works)

**Comment by braeven** [comment]
Can confirm the problem

Tested it on Delta, same error
Tested it on Epsilon, same error

Tested it in Singleplayer, no problem

**Comment by draknyte1** [comment]
Uploading your FML-client-latest.log would actually be useful.

**Comment by draknyte1** [comment]
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/5350. 

Thermos bug, which FunwayGuy WILL NOT fix in BQ3.
