### ISSUE TITLE
PSS MAX redox cell energy value changed

### ISSUE THREAD

**Issue by firendlyGhost** [GTNewHorizons/NewHorizons#5378]
#### Which modpack version are you using?
2.0.8.2
#
#### If in multiplayer; On which server does this happen? 
no
#
#### What did you try to do, and what did you expect to happen?
value should be the same as in 2.0.8.1
#
#### What happened instead? (Attach screenshots if needed)
Old value was 1,677,721,600,000,000 EU, New value is 102,400,000,000 EU
#
#### What do you suggest instead/what changes do you propose?

Wanted to know if this is intentional, it wasn't in the changelog

**Comment by botn365** [comment]
old value is defnetly a broken value new value is the intendet amount

**Comment by firendlyGhost** [comment]
Indeed, just wanted to make sure
