### ISSUE TITLE
Crafting Recipe (Sandstone)

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#538]
No Recipe for Sandstone in NEI. Any way of crafting it? Currently their is no way.
Edit: Sandstone With an Integrated Circuit with Config of "1" Does not make Smooth Sandstone.

**Comment by Teteros** [comment]
Wild guess, but have you tried chiseling sand/sandstone to get smooth sandstone?
I recall I could make really fancy sandstone blocks that way back in the past.

If you mean an recipe for the actual sandstone block (to chisel from) there could be some recipe for it, yes. Any suggestions?

**Comment by deeplyarnab** [comment]
I suggested a shapeless recipe for it using chisel and 4 sand in crafting table to get the recipe

**Comment by Dream-Master** [comment]
Before Sandstone have a compressor recipe. 
@deeplyarnab 
Please show me in real life how to chisel Sand ;)

**Comment by deeplyarnab** [comment]
well, we really cant but compressor is already used for compressed sand and assembler for sandstone is kinda off

**Comment by Technus** [comment]
autoclave it then.

**Comment by Dream-Master** [comment]
ok will readd it to the compressor dont know why recipe are off.

**Comment by deeplyarnab** [comment]
what about compressed sand then?

**Comment by Dream-Master** [comment]
no normal compressor.

**Comment by Goofyschooler** [comment]
So @Dream-Master Are you going to make us do this Sand > Compressed Sand > Double Compressed > Sandstone? Because currently Double Compressed is in Implosion. Or is it just going to be Sand > Compressed Sand > Sandstone with this one all being down in the compressor?

**Comment by Dream-Master** [comment]
Ok i know why recipe is gone. The Compressed sand from Extra Utilities occupying the old recipes.

**Comment by Dream-Master** [comment]
1.0.7.7n fixed
