### ISSUE TITLE
"Sharpness: Over... 5..." quest issue.

### ISSUE THREAD

**Issue by Sarodinian** [GTNewHorizons/NewHorizons#5384]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta

#
#### What did you try to do, and what did you expect to happen?
So, I was trying to complete a quest, name "Sharpness: Over... 5..." (Stone age), where you have to craft a flint sword. Figured this'd be straightforward, create a flint sword, finish the quest.

#
#### What happened instead? (Attach screenshots if needed)
After building two such swords, the quest log is not registering that I've crafted them, and will not allow me to complete the quest.

#

**Comment by richardhendricks** [comment]
Make your sword by placing flint/sticks in the left slots of the crafting table. The version using the center slots is broken and should not be there.

@bartimaeusnek @Dream-Master 
Can you look into why there are two sword crafting recipes?

**Comment by Dream-Master** [comment]
will check

**Comment by Dream-Master** [comment]
Another Question why all other tools have 128 duarbility and shovels only 64?

**Comment by Dream-Master** [comment]
I try both recipes with the swords but get only one sword with 128 durability
try nature sticks and normal ones.
