### ISSUE TITLE
Missing recipes of maraging steel 250,300

### ISSUE THREAD

**Issue by 1qft** [GTNewHorizons/NewHorizons#5387]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
No.
#
#### What did you try to do, and what did you expect to happen?
I tried to craft maraging 250 ingot for an industrial centrifuge but couldn't find the recipe.
There was a recipe of maraging 250,300 in 2.0.8.0pre.
#

#### What do you suggest instead/what changes do you propose?
Add a recipe of maraging steel 250 or change the recipe for the industrial centrifuge.

**Comment by Dream-Master** [comment]
@1qft this a GT++ materaial ? If yes please report to https://github.com/alkcorp/GTplusplus/issues
Thanks

**Comment by 1qft** [comment]
Yes it is. I will report there. Thanks
