### ISSUE TITLE
Firestone plate uncraftable

### ISSUE THREAD

**Issue by mrTeroblaze** [GTNewHorizons/NewHorizons#5391]
GTNH 2.0.8.3
MP Private server (also checked in SP)

I tryed to craft firestone lens (for nine hells focus for quest) which needs firestone plate. Plate have craft from Firestone block which can`t be made becouse it`s made from stacked raw firestone (they dont stack obw) or GR firestones wich cant be achieved.

Also i checked it in 2.0.7.5 - plate can be crafted from firestone dust. So we just have missing recipe.
![kekus](https://user-images.githubusercontent.com/26322390/72677563-c7430480-3aae-11ea-8a00-4056543c9884.png)

**Comment by Dream-Master** [comment]
will check and change the recipe

**Comment by chochem** [comment]
I hope this gets fixed soon as several things are just uncraftable at the moment due to the missing firestone plate.

But here is a workaround for now: One can still craft the firestone block in the gt++ multiblock compressor. I have tested it myself. Of course that multiblock is in IV-tier.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77120858-220ac500-6a3a-11ea-823c-5e7c33e10123.png)
make  it that firestone is stackable up to 9
