### ISSUE TITLE
(Suggestion) Remove Invincibility From The One Ring

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GTNewHorizons/NewHorizons#5395]
#### Which modpack version are you using?
2.0.8.3
#
#### What did you try to do, and what did you expect to happen?
Found The One Ring. Became invincible. I expected that items obtainable in the early game would be balanced for the early game.
#
#### What do you suggest instead/what changes do you propose?
Invisibility is fine. But being invincible and not having hunger completely remove any reason to progress in very large aspects of the modpack. Why worry about a food source? Why focus on getting better gear for fights? You can a ring that makes you unkillable. And no amount of negative effects will counterbalance this. In my opinion, invincibility needs to be removed from the ring or the ring needs to be removed altogether.

**Comment by sthegreat** [comment]
#5168 relevant reading

**Comment by richardhendricks** [comment]
5168 will cover this issue
