### ISSUE TITLE
Remove BPS patching of GT++ through Curse

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/NewHorizons#5398]
My license does not allow it.

![image](https://user-images.githubusercontent.com/3060479/72690248-5d5c4680-3b12-11ea-814a-5e8080ed098f.png)

Is GTNH a public pack? Yes
Are people using a modified version through Curse? Yes

**Comment by Dream-Master** [comment]
@draknyte1 upload a new version of your mod on curse and we are fine.

**Comment by draknyte1** [comment]
Could just ask, lol. I'll speak with Bot and see what we wanna do in terms of a proper release.
It's been, rather low priority.
