### ISSUE TITLE
Energistics arcane terminal fix

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#540]
https://github.com/Nividica/ThaumicEnergistics/issues/279

https://github.com/Nividica/ThaumicEnergistics/issues/274

https://github.com/Nividica/ThaumicEnergistics/pull/284/commits/223a5313c87935b62e28ae3c1a74b64363579efc

Can we try that?

**Comment by Dream-Master** [comment]
I think we can. Have to make a for later.

**Comment by Dream-Master** [comment]
fixed hopefuly

https://github.com/GTNewHorizons/ThaumicEnergistics/releases/tag/1.0.0.2
