### ISSUE TITLE
Make boats recipe possible in tier 0

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5402]
I think we should unlock basic boats earlier for player exploration during the "nomadic" phase.

Recommend changing boats to using a knife instead of a saw.  That makes them craftable in tier 0 instead of needing post-bronze.

Thoughts?

With the potential boat fix, this makes boats a really nice pre-glider/horse exploration tool.

**Comment by KaneHart** [comment]
But require Aluminium Screws :)

**Comment by quedral** [comment]
although boats in 1.7.10 are vert buggy and fragile it does not hurt to make the more accessible in early game. carving a boat wit  aknife would take lots of time in rl. i know vikings used axes to carve them so maybe axes make more sense dunno.

**Comment by Methes** [comment]
Heh. Deja vu
https://github.com/GTNewHorizons/NewHorizons/issues/64

**Comment by richardhendricks** [comment]
Wait, what happened then?

**Comment by richardhendricks** [comment]
// --- Boat
recipes.addShaped(<minecraft:boat>, [
[<ore:plankWood>, null, <ore:plankWood>],
[<ore:plankWood>, <ore:craftingToolKnife>, <ore:plankWood>],
[WoodSlab, WoodSlab, WoodSlab]]);

Maybe it was changed, and we just need to update the quest then?  Saw does count as "craftingToolKnife" in the oredict, so it might be showing up in the picture.

Need to test.

**Comment by richardhendricks** [comment]
So, boat recipe does use knife now, but the *slabs* needed for the recipe require a saw.

Idea for a recipe change

string, string, string
plank, knife, plank
log, log, log

So now it is a log boat, craftable at tier 0, but not super easy.

**Comment by richardhendricks** [comment]
Dream has decided that the recipe stays as-is. You will have to make a hammer/file/saw to make slabs to get a boat.

**Comment by Dream-Master** [comment]
Make a knive and a saw isnt that difficult. Maby need to add a flint saw :P
