### ISSUE TITLE
A very very cheap way to remove all permanent warp 2

### ISSUE THREAD

**Issue by mrTeroblaze** [GTNewHorizons/NewHorizons#5404]
GTNH 2.0.8.3
Warped Tumor is a Self-Infusion added by the Thaumic Horizons mod. It removes 50 of the player's Warp untill the player's death.  (c) FTB wiki.
So this handy infusion removes all warp from the player and death wont returning it back.
Tested both in MP and SP.

**Comment by Dream-Master** [comment]
Ok nerf incomming :)

**Comment by mrTeroblaze** [comment]
That is a bug, Nerfing this is unreasonable becouse there is not so many ways to get rid of warp untill IV. So tumor (and Soul Brazier that have same glitch) are really helpfull.

**Comment by Dream-Master** [comment]
change the recipe will make it harder. Forbidden is forbidden for good reasons

**Comment by ScriptedPiky** [comment]
The warp technically doesn't get removed upon death, however, if you close your MC client and load up a new one, all the warp will magically return back to you upon the next loading session. I had this occur on Zeta. No idea why returning on death doesn't properly return it but restarting & making a new client does.

**Comment by mrTeroblaze** [comment]
> 
> 
> The warp technically doesn't get returned upon death, however, if you close your MC client and load up a new one, all the warp will magically return back to you upon the next loading session. I had this occur on Zeta. No idea why returning on death doesn't properly return it but restarting & making a new client does.

Tested it on my server - warp didnt come back even after client restart

**Comment by ScriptedPiky** [comment]
> Tested it on my server - warp didnt come back even after client restart

Really? Well, that's incredibly strange. Does it return on server restart as well? Adjusting TC warp is a wacky as hell process then. So many bugs.

**Comment by mrTeroblaze** [comment]
> 
> 
> > Tested it on my server - warp didnt come back even after client restart
> 
> Really? Well, that's incredibly strange. Does it return on server restart as well? Adjusting TC warp is a wacky as hell process then. So many bugs.

Yep, tryed all variants. 
So, as i mentioned above, it`s now useless to do any kind of magic research deeper than novice quests untill IV, becouse 2 methods of dealing with warp bugged and constantly using salts/spa is not the option.
Yes, yes, you can say: do only usefull researches, manage your way etc, But already at 30 warp you gain fancy lighting effect which is pain in the ass/

**Comment by bombcar** [comment]
Ok this is *mostly* fixed but the "tumor removes ALL permanent warp" part still exists.

But it does return 50 upon death at least now.

**Comment by bombcar** [comment]
Ok I watched it - what it does is weird.

First it takes 50 perm warp. Then it takes the remaining perm warp, and if there is any left over, it takes normal warp, too..

I suspect  this cascading if/else statement.
