### ISSUE TITLE
need to craft crowbar twice for stone age quests

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/NewHorizons#5407]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
You need to craft the crowbar for the quest "Important tools" (36) and that unlocks quest "got a flat tire" (2402) where you need to craft it again right after.
#
#### What happened instead? (Attach screenshots if needed)
no need to craft it twice in a row i'd think?

quest images:
![image](https://user-images.githubusercontent.com/7458440/72782149-5709bf80-3c23-11ea-8a15-0febf2d2130c.png)

![image](https://user-images.githubusercontent.com/7458440/72782132-4bb69400-3c23-11ea-9c6a-de5e9b51b35b.png)

the quest follows the first one:
![image](https://user-images.githubusercontent.com/7458440/72782194-76085180-3c23-11ea-8e89-c2deebceeb83.png)

#
#### What do you suggest instead/what changes do you propose?
remove the flat tire quest or remove it from important tools

**Comment by richardhendricks** [comment]
Already fixed
