### ISSUE TITLE
Don't use ++ RF converter 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/NewHorizons#5411]
#### Which modpack version are you using?
2.0.8.3
#

The ++ RF converter shouldn't be a thing 🙏

**Comment by Anarack** [comment]
It should be disable for us from what alk has said.

**Comment by 0lafe** [comment]
It has a recipe with parts that seem craftable, but idk I coulda missed a part

**Comment by noobyaran9** [comment]
Do we even have anything that can benefit from having that?

**Comment by Dream-Master** [comment]
is there a config? if yes we can disable it. if not I remove recipe via minetweaker

**Comment by 0lafe** [comment]
# Converts RF to GTEU. Requires COFH-Core to be installed. [default: true]
    B:enableMachineRFConvetor=true

Think so

**Comment by Dream-Master** [comment]
ok

**Comment by repo-alt** [comment]
It may be left enabled but given some UV recipe to make Draconic Reactor less useless

**Comment by Dream-Master** [comment]
sure a uv recipe is possible too.

**Comment by 0lafe** [comment]
DE reactor is kinda useless even if you can convert. No reason to make a large multi of DE tiered items for an output less than an mk1 fusion reactor. It also kinda sucks as a power gen, you just input nuggets and it makes power.

**Comment by repo-alt** [comment]
This is kinda weird objection, if it sux then people just wont use it, right?

**Comment by 0lafe** [comment]
It's the eio capacitor that makes it something you shouldn't add

**Comment by Dream-Master** [comment]
we have source of De we can change it. Make output more energy because the recioes are very pricy

**Comment by mitchej123** [comment]
Make it out put EU :dancer:

**Comment by Dream-Master** [comment]
if you code that ok @mitchej123

**Comment by bartimaeusnek** [comment]
Well I don’t get why it exists the the first place, GT has a confit for RF...

**Comment by repo-alt** [comment]
It exists exactly for these special cases, when general EU <-> RF conversion is not wanted, or e.g. should be gated.

**Comment by mitchej123** [comment]
> Well I don’t get why it exists the the first place, GT has a confit for RF...

yah... https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Transformer.java#L143-L177

**Comment by draknyte1** [comment]
It’s better coded than the transformers. They’re shit and don’t work very well. 

It was made solely for one of my Patrons, could not give a fuck about it in any other regard.
