### ISSUE TITLE
ULV machine casing and pyrolyse oven casing use shared texture

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#5419]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Any

ULV machine casing and pyrolyse oven casing use shared texture.

assets\gregtech\textures\blocks\iconsets\
MACHINE_8V_BOTTOM.png
MACHINE_8V_SIDE.png
MACHINE_8V_TOP.png

Please, split up.

**Comment by richardhendricks** [comment]
GT++ adds ULV casing and re-uses pyro PNG.

**Comment by Spartak1997** [comment]
@richardhendricks No. Problem in Pyrolyse Oven. I know how fix it problem. You should use ID from GTNHCore, not from vanilla casing.

**Comment by richardhendricks** [comment]
Great, file a PR. :)

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/236
