### ISSUE TITLE
Serious GT++ Issues

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/NewHorizons#5423]
#### Which modpack version are you using?
2.0.8.3
#

The current version of GT++ used in 2.0.8.3 has left it in a complete state, from what I can currently see these are the most pressing problems:

Missing material recipes for:

Maraging Steel 250
Maraging Steel 300
Hastelloy-N

Additionally Lafium Compound can no longer be made as it uses Hastelloy-N in its recipe.

This has the knock on effect of making the following multiblocks/machines either uncraftable or unable to complete their structure due to missing blocks:

Volcanus - Maraging Steel 250 for the pyrotheum heating vent.
Industrial Centrifuge - Maraging Steel 250.
Cutting Factory - Maraging Steel 300.
Cryogenic Freezer - Maraging Steel 250 for the cryotheum cooling hatch.
Wireless Charger VI - Lafium Compound.
High Current Industrial Arc Furnace - Lafium Compound.

In addition to this list the multiblock mixer currently does not function properly at all. There are many more recipes impacted by these materials being unavailable but from what I can currently see these are the most important ones. 

I recognise this is a GT++ issue and the issue has been reported there but upon fixing of these issues I think we should seriously consider updating the pack version as to include them as large parts of this mod that are widely used by most of the player base are currently completely broken or uncraftable. Tangentially there are also other serious bugs with the latest version, such as players not being able to craft the T8 rocket plates and thus can't actually even "finish" the pack...

**Comment by draknyte1** [comment]
mAyBe PeOpLe ShOuLd TeSt ShIt On ZeTa, Or StFu. 

Not my fault nobody does any testing of the Pre-releases.. considering taking action in the future instead of having a whinge. 🙃

**Comment by GTNH-Colen** [comment]
> mAyBe PeOpLe ShOuLd TeSt ShIt On ZeTa, Or StFu.
> 
> Not my fault nobody does any testing of the Pre-releases.. considering taking action in the future instead of having a whinge. 🙃

I'm taking action by making this ticket, which is more than most. It took me quite a while to compile all this data, talk to people and write it up in a neat format. Sorry that I can't immediately learn java overnight and submit a PR myself, but i'm trying to help how I can. That said if you've got nothing productive to add other than the fact I actually am reporting an issue then please, don't bother commenting. 

<img width="381" alt="Screenshot 2020-01-24 at 03 46 27" src="https://user-images.githubusercontent.com/54497873/73043227-29f42180-3e5c-11ea-8590-5326f9974385.png">

Ticket on your github...  https://github.com/alkcorp/GTplusplus/issues/619

**Comment by richardhendricks** [comment]
Need testers to provide good version to use.

**Comment by KaneHart** [comment]
Great Report. Thanks for testing. Live or Not it's still been tested and reported.

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/commit/19f9cd0d0616a25e0d405593a1503e654d2eb452

**Comment by Dream-Master** [comment]
When it is merged we can test it.

**Comment by Dream-Master** [comment]
https://circleci.com/gh/alkcorp/GTplusplus/478

**Comment by Josh5minus1** [comment]
Fixed in 478, but 479 got this bug again

**Comment by draknyte1** [comment]
@Josh5minus1 if you took the time to look, you’d notice ones a PR build while the other is master branch. 😪

The PR isn’t yet merged, lol.

**Comment by Dream-Master** [comment]
@draknyte1 ok merge it and we can make a new test build 2.0.8.4

**Comment by draknyte1** [comment]
Was merged in https://circleci.com/gh/alkcorp/GTplusplus/483.
