### ISSUE TITLE
Flower Power quest change suggestion

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5424]
#### Which modpack version are you using?
2.0.8.3
#
The quest Flower Power on the Fishing Farming Cooking tab requires 8 of rose and dandelion seeds each, unlike every other crop seed quest, not to mention the questionable utility of the flowers.
#
#### What do you suggest instead/what changes do you propose?
Reduce to 1 bag each.

**Comment by Dream-Master** [comment]
i make it 2. Not so hard to get.
