### ISSUE TITLE
LuV tier Mega EBF borosilicate glass material/name change suggestion

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5425]
#### Which modpack version are you using?
2.0.8.3
#
Since Chrome is no longer used for the LuV Machine Casings, maybe the Chrome Reinforced Borosilicate Glass Block should be made with the same material, Rhodium-Plated Palladium?
#
#### What do you suggest instead/what changes do you propose?
Change the name and required material for Chrome Reinforced Borosilicate Glass Block. Or not, if you disagree.

**Comment by richardhendricks** [comment]
@bartimaeusnek Thoughts?

**Comment by bartimaeusnek** [comment]
Chrome was chosen bcs. of recycling recipes...
