### ISSUE TITLE
Add a use for HEE Sphalerite

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5426]
#### Which modpack version are you using?
2.0.8.3
#
HEE Sphalerite currently has no use, I suggest adding a macerate to crushed sphalerite (GT ore) recipe. This would add another limited and somewhat hard to get source of gallium (and zinc of course).

#
#### What do you suggest instead/what changes do you propose?
See above.

**Comment by richardhendricks** [comment]
I think 4x just like Nether ores would be OK.
