### ISSUE TITLE
HEE quests require you to collect large amounts of useless stuff

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5428]
#### Which modpack version are you using?
2.0.8.3
#
The "Visit X island" quests (of which there are 4) require you to large amounts of useless stuff that you'll just throw on the ground, or into the void when you complete them. This is tiresome, makes it harder for other players to complete, and completely pointless.

"Find all the ores in the end" requires 64 endium ore, but this seems like kind of a lot considering how rare it is, though I'm not completely sure. If it was the ore or dust, that would be fine though since you can centrifuge ender goo for it.

"Hot puzzle" requires 128 Igneous Rock, is this amount really necessary to complete the puzzle?

"Curse master" seems to require you to make all the curse items, but will anyone really use these? Is one not enough?

"Visit the infested island" additionally requires you to collect 64 stardust, is there an easy way to collect it there I don't know about? I thought it only comes from 'Sphalerite with Stardust', though that can be fortuned, it's kind of rare, isn't it? Like, only on the Sphalerite meteors?

#
#### What do you suggest instead/what changes do you propose?
Reduce the number of items like 'Enchanted End Stone', Ravaged Dungeon Brick, etc. required to 1, you can't get them anywhere else anyway. Honestly, I'd say it should be just 1 of the biome specific endstone, and one other thing only found there.

Reduce the number of required endium ore in "Find all the ores in the end", or change to dust/ingot.

Confirm how many igneous rock is actually needed for the puzzle in "hot puzzle". I couldn't even find one to test. I'd say set it to 8, and leave the rest up to the player unless you actually need that many.

Consider removing most of the items in "curse master", unless you can think of a use? Would people use these against infernals? I wouldn't bother personally.

Reduce the amount of stardust needed for "visit the infested island", since you don't get any there (unless I'm wrong).

**Comment by Dream-Master** [comment]
Ich change most of the amounts of items.  Curse master Quest will be untouched. If you want craft only one curse use the Quest before.
