### ISSUE TITLE
Move away from using TiCon chisel, has bugs when crafting

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5429]
Lea has provided a PR to remove most of the TiCon chisel crafting recipes and put them into the normal chisel

https://github.com/GTNewHorizons/NewHorizons/pull/5427

This is good because the TiCon chisel is buggy and can have issues with lagging out the server, probably because of damage calculations.

Still need an alternative for going from the the single ingot to  Ticon block recipes. Maybe via forgehammer or some other fast machine. Using a single ingot is a bit weird, but since these are deco blocks, I'm OK with leaving that along.  Perhaps we can make the forgehammer recipes use a block of material -> 9 ticon blocks.

If we add recycling recipes via arcfurnace etc, must make sure they only provide 1 ingot/dust in return.

Also need to update Build Better Bases tab with whatever we decide to do.

**Comment by Dream-Master** [comment]
i pulled it.

**Comment by Dream-Master** [comment]
@richardhendricks make a new issue if you want to add Quests
