### ISSUE TITLE
EnderChest Getting Wiped

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#543]
After Dying my enderchest got wiped. Twice. Any way to fix?

**Comment by deeplyarnab** [comment]
Did you mean you dyed it after putting stuff in it? Enderchests and pouch connect to their counterparts with the same dyed channel, so basically your stuff is still there just on other channel.

**Comment by Goofyschooler** [comment]
No it was a vanilla ender chest

**Comment by Goofyschooler** [comment]
After I died my vanilla ender chest was completely wiped. Second time this has happened. And has happened to 3 people on the server.

**Comment by deeplyarnab** [comment]
Wait, you mean your player death caused your vanilla enderchest to get wiped out? Hopefully it is not a bug of minecraft itself or one of its mods.

**Comment by Goofyschooler** [comment]
Exactly what I mean when I died I lost all my items in my enderchest. Has happened every time I've died with stuff in it. Tested in vanilla not a vanilla issue. Has to do with a mod. Maybe hqm is doing it?

**Comment by Dream-Master** [comment]
@Goofyschooler 
Vanilla Enderchest is disabled because we using The Enderchest Mod from Chicken Bones.
You explain it a bit more detailed that i can look what happend there.

**Comment by Goofyschooler** [comment]
@Dream-Master I don't know how to explain it more. I died then my enderchest is gone.

**Comment by Dream-Master** [comment]
How you get a vanilla Enderchest?

**Comment by Goofyschooler** [comment]
We have a command for it on our server.

**Comment by Dream-Master** [comment]
We not using it so i don't know. Ender Chest are disabled and replaced with Ender chest mod.
If you not using this chest it is you own risk. I am not sure how vanilla chest works. HEE have a Ender Chest to which items go into it after Death.

**Comment by Goofyschooler** [comment]
Alright so @prospercraft disable /enderchest

**Comment by Dream-Master** [comment]
Yes this would be better because the Ender Chest mod you can better personalize your chest.

**Comment by ProsperCraft** [comment]
I am not going to disable it, I used it extensively with no problems even through death.  Use at your own risk.

**Comment by Dream-Master** [comment]
@ProsperCraft 
Is this a extra mod or what it is ?

**Comment by ProsperCraft** [comment]
essentials /echest plugin.  Its never had a problem before on all of our servers over 1.5.2-1.7.10

**Comment by Dream-Master** [comment]
ah ok never used it.

**Comment by Teteros** [comment]
[Already is](https://github.com/GTNewHorizons/NewHorizons/issues/543#event-595808761).

As much as we'd like to know the actual cause of this, the vanilla enderchest has no SMP recipe indeed. That said finding out why this strange behaviour occurs in the first place doesn't seem too trivial.
Do report any findings for curiosity's sake, if anything.
