### ISSUE TITLE
Free platinum from nickel ore

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#5433]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
priv serv
#
#### What did you try to do, and what did you expect to happen?
![image](https://i.imgur.com/Lmc4U0i.png)

#### What do you suggest instead/what changes do you propose?
at the output to have crushed nickel ore

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73142350-c5b8a400-408d-11ea-82c6-06408eaab5a4.png)
