### ISSUE TITLE
Can't cook awakened draconium

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/NewHorizons#5435]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Tried to cook awakened draconium in the GT++ EBF
I have fluxed electrum coils (9900k).
UV power
Argon gas in bus
Circuit 11 in hatch
Multi structure complete
Machine processing enabled.

#
#### What happened instead? (Attach screenshots if needed)
Didn't cook.

#
#### What do you suggest instead/what changes do you propose?
I spawned in some awakened coils and it started cooking straight away.

I feel that because it requires 9900k and it's being supplied 9900k, it's reading it as not enough.

To make fluxed electrum, you need 9000K. Naq alloy coils (highest tier you can have pre-fluxed elec) at 9001K.

Maybe the fluxed electrum coils need to be changed to 9901K.

**Comment by ScriptedPiky** [comment]
Does this occur in a regular EBF as well? Currently, in the public release (without the fixed version of GT++), the Volcanus EBF breaks and does not function properly. Although, Fluxed Electrum coils *should* have exactly 9900K, especially if you scan the EBF and find their exact cooking (hopefully they're not off by 100 or something).

If it doesn't work in a regular EBF, then perhaps something is amiss with the awakened draconium recipe.

**Comment by AlexBucket** [comment]
> Does this occur in a regular EBF as well? Currently, in the public release (without the fixed version of GT++), the Volcanus EBF breaks and does not function properly. Although, Fluxed Electrum coils _should_ have exactly 9900K, especially if you scan the EBF and find their exact cooking (hopefully they're not off by 100 or something).
> 
> If it doesn't work in a regular EBF, then perhaps something is amiss with the awakened draconium recipe or a bug/oversight with the coils.

Scanned the GT++ EBF and it didn't have the heating capacity line with the fluxed electrum coils.

Put the coils on my regular EBF and whala:
![image](https://user-images.githubusercontent.com/34566584/73115761-8e0f0680-3f7e-11ea-9285-0a08d6f780a6.png)

**Comment by richardhendricks** [comment]
Is the a GT5u issue or a GT++ issue?

**Comment by botn365** [comment]
this is a gt++ issue its already fixed in dev

**Comment by Dream-Master** [comment]
@botn365 which version fix it ?

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/commit/19f9cd0d0616a25e0d405593a1503e654d2eb452

**Comment by Dream-Master** [comment]
@draknyte1 can you merge this pull. Thanks
https://github.com/alkcorp/GTplusplus/pull/615

**Comment by Dream-Master** [comment]
https://circleci.com/gh/alkcorp/GTplusplus/478
