### ISSUE TITLE
some witchery books recipes are a little expensive 

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#5436]
#### Which modpack version are you using?
8.3
now i know those books aren't actually "Expensive" but they serve as a main source which people learn witchery from but some recipes demand things you can only know from the books (ingame, i mean the mod is plenty documented on the internet so anyone can just google, but still)
here are the recipes i have a problem with
![image](https://user-images.githubusercontent.com/40670872/73120756-a54bf500-3f7a-11ea-9ce8-9c551faa71f0.png)
first is this, could you change wormwood to something cheaper? maybe a vanilla flower
![image](https://user-images.githubusercontent.com/40670872/73120786-f8be4300-3f7a-11ea-8d23-b470757d36d8.png)
the brewing stand here is a little too much, maybe cauldron is better?

![image](https://user-images.githubusercontent.com/40670872/73120827-6d917d00-3f7b-11ea-9537-92ebbe9672b1.png)
while a toe of the frog isnt that hard to get, but for someone learning witchery this might be a chore
well idk what we could replace it with but preferably something cheaper 

personally those recipes dont effect me at all, because i know witchery and the mod itself is fully documented here https://sites.google.com/site/witcherymod/, i could also just raid a couple villages and the recipes then become completely obsolete, but for newbies maybe it could prove too much.

**Comment by Dream-Master** [comment]
@richardhendricks ask me first. I change this recipes in the last update.
Witchery is a mod you dont start at LV Level.

**Comment by Dream-Master** [comment]
Maybe we can exchange ingredients.

**Comment by PoptartOverlord-Xabedo** [comment]
they dont have to be lv/mv at all, but 1st and 3rd recipes have advanced witchery items needed to make books that tell you how to do stuff in witchery, which beats the point, e.g wormwood

**Comment by Dream-Master** [comment]
@PoptartOverlord-Xabedo feel free to make suggestions or do a pull request.

**Comment by PoptartOverlord-Xabedo** [comment]
already suggested some <3 maybe they were hard to see since they are under the pictures
also for 3rd book instead of toe of frog how about wolf/hound head because its easier to find
