### ISSUE TITLE
Quest #1243 - Pitchblende only accepts "Mars" Pitchblende

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/NewHorizons#5439]
#### Which modpack version are you using?
2.0.8.3

#
#### What did you try to do, and what did you expect to happen?
Mined the Pitchblende from Phobos and expected the quest to be oredict.

#
#### What happened instead? (Attach screenshots if needed)
Quest did not complete, had to go to Mars to get ore

#
#### What do you suggest instead/what changes do you propose?
Confirm that it should only be Mars version, since it extends from the Mars quest, but blocks the alloy blast smelter quest until you complete it.

**Comment by Dream-Master** [comment]
Problem is Ores cant be oredicted. Will do a 2. Quest and make it "or" logic.

**Comment by Dream-Master** [comment]
There is a Quest for Deimos/Phobos
![image](https://user-images.githubusercontent.com/2970688/73138724-4e234e80-4066-11ea-9e1c-6a37522f9dbb.png)
![image](https://user-images.githubusercontent.com/2970688/73138725-52e80280-4066-11ea-8ba0-858858357325.png)

**Comment by dragagon** [comment]
The circled quest is blocked unless you get the Mars version of pitchblende
![oresquest](https://user-images.githubusercontent.com/777920/73138901-ffa19000-4024-11ea-8ed8-fd2c774fe16a.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73139033-bf183580-4069-11ea-8c96-48edf959d330.png)
![image](https://user-images.githubusercontent.com/2970688/73139034-c2132600-4069-11ea-8add-58e81dcb79b7.png)
