### ISSUE TITLE
Basic crafting: Casings not detecting

### ISSUE THREAD

**Issue by madthedemon** [GTNewHorizons/NewHorizons#5443]
#### 2.0.8.3

#
#### Eta

#
#### i crafted both the LV machine casing and the machine hull as per reQuested

#
#### they weren't detected making me very sad D: (being a main quest this is expecially bad)

#

**Comment by Dream-Master** [comment]
@madthedemon in the Quests? And which quests?

**Comment by madthedemon** [comment]
Basic crafting: Casings

**Comment by Dream-Master** [comment]
impossible it ignore nbt it must be detectde. Use a vailla crafting table. @madthedemon

**Comment by madthedemon** [comment]
i'll try

**Comment by madthedemon** [comment]
vanilla workbench worked, thank for the help
