### ISSUE TITLE
SP world fails to load at random

### ISSUE THREAD

**Issue by Arvannies** [GTNewHorizons/NewHorizons#5444]
#### Which modpack version are you using?
Both 2.0.8.2 & 2.0.8.3

#

#### What did you try to do, and what did you expect to happen?
Trying to load a single player world.

#
#### What happened instead? (Attach screenshots if needed)
Seems to be a random chance of either successfully loading the world or stating "shutting down internal server" and quitting out of the game entirely. 

[crash-2020-01-26_15.35.03-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4114586/crash-2020-01-26_15.35.03-client.txt)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/1256381fe5f69eb445a71142745a4bd2eeebd5a6
