### ISSUE TITLE
Armor stand Needs Recipe change

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#545]
Currently it is 2 iron ingots with 3 stone slabs. needs to be Gregified.

**Comment by Dream-Master** [comment]
Its Bibliocraft right ?
I not touch this mod.

@leftyde 
Wolltest du nicht den Mod nerfen ?

**Comment by Goofyschooler** [comment]
Yes it is, could be changed to add a Hammer and Screw driver with Steel Screws and Change the stone slabs to pressure plates. Just an idea.

**Comment by Dream-Master** [comment]
Yes sure the whole mod need a rework.

**Comment by leftyde** [comment]
Ich hatte Storage Drawers angepasst, ich kann natürlich auch so generell mal nachgucken was noch so angepasst werden müsste, wenn ich eh mit dem SkyBlock Pack anfange (Hab nur auf den 1.0.7.8 release gewartet)

**Comment by Dream-Master** [comment]
@leftyde 
Der ist heute raus. Bin noch am bugs fixen.

**Comment by leftyde** [comment]
Lust hab ich sehr viel, Zeit ist bei mir das Problem. Hab in einer Woche Urlaub, da werde ich dann paar Tage Hardcore scripten für den SkyBlock Modus und damit dann auch so generelle Sachen ändern die mir auffallen.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/659

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22310563/e6110f60-e34f-11e6-8b89-26486ab772fd.png)

**Comment by Dream-Master** [comment]
43 recipes need to be added.
