### ISSUE TITLE
Storage Drawers conflicting assembler recipes fo halfdrawers

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/NewHorizons#5450]
#### Which modpack version are you using?
git

https://github.com/GTNewHorizons/NewHorizons/commit/286ba64766c349b181befb439d3466ab805f6138

https://github.com/GTNewHorizons/NewHorizons/blob/2bcec0ca622ab78b4d4fc24b77486a02a145fd45/scripts/Storage-Drawers.zs#L886-L894

**Comment by Dream-Master** [comment]
yea will fix that.

**Comment by leagris** [comment]
Already fixed
