### ISSUE TITLE
quest #618 not detecting

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/NewHorizons#5452]
#### If in multiplayer; On which server does this happen? 
epsilon
![image](https://user-images.githubusercontent.com/40670872/73225277-c7a96280-4174-11ea-99ef-353759916780.png)

**Comment by richardhendricks** [comment]
More nbt issues

dam, don't have a GitHub account, but it was posted, Quest #1653 task 2 was not posted if someone with a GitHub Account wants to post that one

**Comment by Prometheus0000** [comment]
SA works for me when I tested it? Is it in the right kind of cell?

**Comment by PoptartOverlord-Xabedo** [comment]
i have tried it again, it works, my mistake.
