### ISSUE TITLE
Drawer Controller Quest Suggestion

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5456]
#### Which modpack version are you using?
2.0.8.3
#
Somehow, there doesn't seem to be a quest for the Drawer Controller, even given how important and useful it is. This should be rectified. It uses MV circuits, but also uses stainless, so it could be MV or HV.

There's a quest on the Project Red page that rewards one, and also expects you to have one, but never mentions making one in any quest I looked at, but there's a lot of quests, and I might have missed it.
#
#### What do you suggest instead/what changes do you propose?
Add a quest for the Drawer Controller.

**Comment by richardhendricks** [comment]
The DC is a reward for the end of the Project Red quests. We can add a standalone quest for building one to HV.

**Comment by Prometheus0000** [comment]
I wrote some text. I don't use Project Red, so it probably needs text on how to interact with that.

Now that you have MV Circuits and Stainless Steel, you can make the incredibly handy Drawer Controller. This block will make any drawers it connects to in a 12-block radius (including the y-axis) part of a multiblock that allows storage (and retrieval with the right setup) to any of the blocks that make it up. This will allow you to dump the contents of your mining trip into a storage system much easier. Just hold right click on the Controller front for a second, and any items that match what's already in the multiblock will be deposited, while your tools and such won't. Just make sure to place your Controller last so it registers all the drawers.

You can feed into the Controller (and thus the rest of the drawers) with any kind of piping or hopper equivalent. If using it as part of a Multifarm or Mob Farm, make sure to set the contents of the drawers, and lock them with a key so that it properly stores everything in an organized manner. If the drawers' contents aren't set, it will start filling starting from the ones closest. If you wish to have more than one drawer full of an item, put a void upgrade on the drawer further from the Controller, and it will fill the first one, then the second. 

If you want to go around corners, use the Trim Drawers to extend the multiblock. If you want to have a second point to dump items into, use the Slave Controller (one per multiblock). Note that you can use a key on the Controller to affect all drawers at once.

Once you have an ME Network, place a storage bus on the controller, and the entire inventory will be accessible from the network, with both storage and retrieval. Just remember to set the priority higher than your ME Drives.
