### ISSUE TITLE
Optifine does not work in 1.0.7.8(a)

### ISSUE THREAD

**Issue by Ixodid** [GTNewHorizons/NewHorizons#546]
Optifine has stopped working since the move to version D3. The forge loading screen stays black and even though the main menu says optifine is active it doesn't seem to function at all, only the vanilla video settings are available. Going back to version D1 fixes this.

**Comment by Dream-Master** [comment]
In my Pack it works well but i heard from other players to they have problems.

Version 1.0.7.8b backdate Optifine to HDU1
