### ISSUE TITLE
Quest #10 fix

### ISSUE THREAD

**Issue by chadandersen1** [GTNewHorizons/NewHorizons#5463]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Complete quest #10
#
#### What happened instead? (Attach screenshots if needed)
Didn't complete quest #10
#
#### What do you suggest instead/what changes do you propose?
The flint swords durability was changed to 6400. Change the durability of the sword required for the quest to 6400 from 12800.

**Comment by richardhendricks** [comment]
The released modpack for 2.0.8.3 has two different flint sword recipes. Use the recipe with the ingredients on the left side.

**Comment by Dream-Master** [comment]
will remove the wrong sword
