### ISSUE TITLE
New GT Mixer texture need to be corrected

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#5467]
New GT Mixer texture need to be corrected.

![image](https://user-images.githubusercontent.com/2970688/73354246-8492e080-4295-11ea-9157-3127292dcd8d.png)

**Comment by Ethryan** [comment]
What is wrong with it?

**Comment by Dream-Master** [comment]
@Ethryan look at the green dust. The backround has to be moved one pixel
