### ISSUE TITLE
WorldGuard/Edit Wand has higer priority than ingame actions.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#547]
Can't put Leather in a barrel on claimed region (i am the Owner)

![image](https://cloud.githubusercontent.com/assets/2970688/13925715/ae98c4b6-ef89-11e5-801d-1c813990c242.png)

![image](https://cloud.githubusercontent.com/assets/2970688/13925728/bb33126c-ef89-11e5-82ba-a7649b58f9eb.png)

**Comment by Teteros** [comment]
Have you tried adding the relevant flag to the region? In this case it would be `use` I think.
I've noticed some regions have them.
Try:
`/rg flag home_dreammasterxxl2 use true`

**Comment by Technus** [comment]
> Region wand
You can use leather and right click a block to see a list of regions that encompass this. You can change the wand item by modifying WorldGuard's configuration.

Change WG config of wands to unobtainable items.

**Comment by Teteros** [comment]
>You can use **leather**...

Well spotted, however the second instruction:
>remove that perm: `worldguard.region.wand`

Isn't ideal since moderators wouldn't have (or normal users would be enabled to) use the region wand to set up protection/regions for players.

Simply changing the leather (and other WG special items if any) to something else is enough.

**Comment by Technus** [comment]
Region Wand=/=World edit wand

Region wand (leather) is for region check only which is == to /rg info
(unless you need block wise precision)

World edit wand(wooden axe), is for setting up regions (for both WE and WG)

**Comment by Namikon** [comment]
Changed to bedrock. Reopen if issue persists

**Comment by Dream-Master** [comment]
:+1:
