### ISSUE TITLE
[Suggestion]: A change to the etylene dehydration recipe

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/NewHorizons#5475]
In the dehydrator right now you input 2000L liquid Etanol and 2 empty cells to receive 1 etylene cell and 1 water cell.

My suggestion is to change it so that the water gets outputed as a fluid instead of put into a cell. 

This is to ease early game automation so that the fluids can be split into different directions easier.

**Comment by richardhendricks** [comment]
Isn't this a GT++ recipe?

**Comment by draknyte1** [comment]
Dehydrator is mine. 
Please report on my repo.

**Comment by Ethryan** [comment]
Reported an copied.

**Comment by draknyte1** [comment]
Not being changed, please close.
