### ISSUE TITLE
Quest Suggestion: Bedrock Dimension

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5476]
#### Which modpack version are you using?
2.0.8.3
#
The Awakened Ichorium Pickaxe allows you to create a portal to the Bedrock dim when used on bedrock in the OW, but there's no mention of this.

Incidentally, I'm not sure the ores in the dim are set properly, as you get IC2 ores, galacticraft ores, etc that you normally don't.
#
#### What do you suggest instead/what changes do you propose?
Add a quest for getting to the Bedrock dim. This quest can also be used to mention what ores are there, since the electric prospector doesn't work there.

**Comment by repo-alt** [comment]
I remember the ores in the bedrock dimension were discussed and left as is, e.g. as an alternative source of TC shards, or EIO silicon.

**Comment by Prometheus0000** [comment]
I wasn't sure about that. Good to know, but probably annoying to process extra types of stuff. Guess I can post another issue about miners not picking up Aluminum ore now that I know it's supposed to be there.

**Comment by richardhendricks** [comment]
I don't know if they were left, or if we couldn't intercept their worldgen to properly insert ores. Might be L:ast Millenium I'm thinking about.

**Comment by Prometheus0000** [comment]
Last millennium is a void world, and I'm writing a quest suggestion for it now.

**Comment by repo-alt** [comment]
isn't Last Millenium just void?

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/issues/44

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/35

Doesn't seem like it ever worked/was tested

**Comment by Prometheus0000** [comment]
I wrote some quest text. The quest would presumably be after getting the pickaxe. Cleared by entering the dim I guess? I don't think there's a need for a reward either. If you fix the ores, you would need to change the text a little. If anyone can figure out the stupid /fill command and wants to look at the ores for a while feel free to submit a list of them. I don't think a partial list would be a good idea though.
#
After acquiring your new pickaxe and clearing away a mountain or two, you wonder if maybe you should go..._deeper_. After trying it out on some Bedrock, you see a way down into the very depths of the planet. After exploring this new realm you make a note that it is:

A) Seemingly empty of life
B) Full of Bedrock you need to clear away with your new pickaxe
C) Full of ore veins going up and down
D) These ores are strange and _different_ from the ones you are used to
E) Since Miners cannot break Bedrock, if you wish to use one, you'll have to do it for it first.
F) After leaving you wake up on the surface somewhere nearby, your lack of memories of such is probably due to Oxygen deprivation. _Probably_.

**Comment by Prometheus0000** [comment]
So, the ores are listed in a file, which I forgot. But now that there's a link to it, I can tell what's there. So, should I list the ores in the quest or not?

**Comment by Dream-Master** [comment]
No there ores are here
https://github.com/GTNewHorizons/ThaumicTinkerer/commit/17a06b2c2d6debdb0de005ebe8836683448d2964#diff-eb4d458a902536bead2ded5a62136168
@Prometheus0000

**Comment by Prometheus0000** [comment]
Yeah, I meant that after I saw the link above, I could look at it. Anyways should I tell people in the quest what's there? Or should it be a mystery? Unless they check github.

**Comment by Dream-Master** [comment]
Secret is better. You can mentioned vanilla and vanilla mod ores. @Prometheus0000
