### ISSUE TITLE
Quest Suggestion: Last Millennium

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5478]
#### Which modpack version are you using?
2.0.8.3
#
There's no quest for the Portal to The Last Millennium, used to get to the Last Millennium dim.

In addition, the research condition to unlock the research is hard to find (IE: do random research until it unlocks), so this should also be mentioned (from the looking at the code, it's Oculus, which should be the 'unlock the eldritch dim' research).

Having a void world to build stuff is clearly useful, so people should probably be informed about it. Quest placement is likely to be trickier, but should be HV at least. Putting it after 'They See Me, They Watch Me' (Adept tab) would make sense, but it might be nice to hint at it earlier than that to convince people to collect the necessary warp to get the Eldritch Revelation research, which is necessary. And I doubt everyone goes into edit mode to look ahead at the quests. Perhaps after 'Concentrated Darkness' (also Adept tab), with some kind of "whispers from the darkness tell me about the end of time" flavor text or something. Though even that would require Eldritch Epiphany to complete, and for people avoiding warp as much as possible until they get pure tears, not possible to complete until then. Whatever you feel is best.
#
#### What do you suggest instead/what changes do you propose?
Add a quest for the Portal to The Last Millennium.

**Comment by richardhendricks** [comment]
The questbook already has a reward option between a Garden dim or a void dim. What use would this dimension be?

**Comment by Prometheus0000** [comment]
You can get it way earlier, and it's not my fault that it makes the void portal kinda useless. Hasn't it been mentioned on discord multiple times to choose Garden because you can get LM? 
This also wouldn't be a reward, it's just telling you it exists/to craft it.

**Comment by draknyte1** [comment]
LM likes to drop you at world spawn when you leave though. Which deters myself and Probably others from using it until alternative teleport methods exist.

**Comment by Prometheus0000** [comment]
Well that's annoying. That would definitely need to be mentioned in the quest if it gets approved. It's probably more useful in single player if you cheat in some kind of teleporter or something to deal with it until you can make them for real, like you say.

**Comment by boubou19** [comment]
We must not forget that there is the weather in the Last Millenium.

**Comment by bartimaeusnek** [comment]
@boubou19 i have removed weather from there.

**Comment by Dream-Master** [comment]
what the weather does @bartimaeusnek What nenefit else the last millennium Dim give us

**Comment by bartimaeusnek** [comment]
@Dream-Master the weather in there is just annoying and lowers TPS with no reason, so i removed it via ASM, there is a config option for it.

**Comment by Prometheus0000** [comment]
It's a void world to build in to reduce lag in your main base/overworld? Lots of space without having to tear stuff down?

**Comment by Dream-Master** [comment]
Yes i understand but we have garden dim and void dim. So last millennium have no real use now or we found a special use

**Comment by Prometheus0000** [comment]
Are you suggesting to remove it? There's even a custom research to unlock it so I would have figured this kind of decision would have been made a long time ago? As mentioned above, it's available earlier too. If you remove it, please change the deep dark portal recipe, since it's a component, and a research requirement. Though I think people that have built stuff there might be upset.

**Comment by Dream-Master** [comment]
no one said to remove it.

**Comment by Prometheus0000** [comment]
Then I'm not sure what you want? Yes, it overlaps in purpose with the void dim (although this one seems to have problems, and by problems, I mean the drop at spawn thing, and #3415). No, it doesn't have a special use. Yes it has a real use, the same use as the void dim. I just thought it would be nice to have a quest to actually tell people about it if they don't already know.

**Comment by Prometheus0000** [comment]
I wrote some quest text. Separated into two to hint at LM (and thus DD research req) for people who hate warp to encourage getting it if they want a void world. Though it says riches in the quest instead I guess.
#
Linked from Primal Charm on the Adept tab to hint at the LM and DD research requirements. No reqs, no reward.

After holding a Primal Charm for a while, you suddenly understand some of it's whispers! It tells of a land filled with untold riches, just waiting for someone to claim them. You scoff at the claim, but apparently if you "Open the Eye" and create a very fancy carved stone, you can create a portal there. But this eye it speaks of...just what is it? Maybe by delving into the darker realm of magic...bah! Only fools would believe such nonsense.

#

Linked from 'They see me, they watch me' on the adept page. Req is entering LM. Should the Mini-ghasts be mentioned or are they getting fixed soon? Confirms entry to LM and hints at DD req, though that's probably not necessary. The dimension is the reward.

Yes! Yes! The eyes! You understand now, it is all too clear! The land of riches, it is yours! But what is this? It's empty? Why, where have your Riches gone? The sole inhabitant tells you that all such things have faded away long ago, with the End of Time at hand...But that simply means you're in the right place after all! You're simply in the wrong _time_. If you simply _adjust_ the portal a little, you can arrive at the right _place_ and _time_ to get your well-deserved Riches. You suspect that such an adjustment would require something strong...INFINITELY strong.

In the meantime you now have a very very big closet to store your things in once the old owner...moves out. Unfortunately the shifting of time causes you to end up in what is likely wilderness when you leave. (Exiting sends you back to the world spawn)

**Comment by Dream-Master** [comment]
@Prometheus0000 are you on Discord? If you make Quest suggestions why you not work on quest directly and make pull requests I can merge later?

**Comment by Dream-Master** [comment]
Contact me on Discord if you like. Can't find you under the name @Prometheus0000
