### ISSUE TITLE
Internal Exception: Java.lang.runtimexception: No openGL context found in the current thread

### ISSUE THREAD

**Issue by Tejasminer** [GTNewHorizons/NewHorizons#548]
Unable to login to the prospercraft server after update to 1.0.7.8c

I can login to a single player world.
A few of us had this issue. Most resolved it by removing better fps, fastcraft and optifine.
I tried removing them and could not resolve the issue.

I deleted the modpack and reloaded. Rebooted all the basic stuff.

**Comment by Technus** [comment]
I had this once, even rejoining game can sometimes help. Usually removing optifine 
(or adjusting settings) can help. The real cause remains unknown.

**Comment by Goofyschooler** [comment]
Their a few steps you can take to fixing this. (Needs to be tested)
1st : Update Optifine to a stable Version

If this doesn't work Continue.

2nd : Remove Schimatica , Optifine, Fastcraft, Better FPS

3rd : If neither of these work, Change Launcher to Multi MC or Curse Launcher.

Hopefully This Helps!

**Comment by Teteros** [comment]
Ever since optifine updated, there's been issues like this. Need to be tested if it's optifine or not.

**Comment by Dream-Master** [comment]
@Goofyschooler
@Tejasminer 

can log in on the EU Server.

**Comment by Teteros** [comment]
Tested on a fresh thermos (Thermos-1.7.10-1614-50-server.jar) instance with **Tejas**, issue is gone.:tada:
It's an issue with @ProsperCraft's server instance I'm afraid.

Try updating your thermos and report back maybe?

**Comment by Dream-Master** [comment]
Yes spoke with Goshen and he said the Enderchest Bug is gone too with Thermos Build 50

**Comment by ProsperCraft** [comment]
I did not test it, but the changelog for Thermos says it fixes something similar so I am going to guess its fixed.

**Comment by Dream-Master** [comment]
@Ghoshen
Maybe its not Thermos it is bungeecord.

**Comment by Dream-Master** [comment]
I think the Server is not online any more.

**Comment by Teteros** [comment]
Their server simply wasn't running, and may be back in the future once they migrate it.
Locking as this isn't a modpack issue.
