### ISSUE TITLE
Update railcraft settings from Gt++

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5481]
Alk has added new settings for us

https://github.com/alkcorp/GTplusplus/issues/635

Add settings and configure for GTNH

**Comment by Dream-Master** [comment]
Let me know what we need to change in the config. @richardhendricks

**Comment by richardhendricks** [comment]
It's not urgent, but we want to increase the speed fluid loaders/unloaders operate. Ideally we want to increase the size of tank carts too.

**Comment by Dream-Master** [comment]
Let me know what values are good @richardhendricks
