### ISSUE TITLE
Item pipes placed after updating world cannot be broken with wrench

### ISSUE THREAD

**Issue by kinjav03** [GTNewHorizons/NewHorizons#5482]
#### Which modpack version are you using? 
2.0.8.3 

After updating a world started in 2.0.7.5 to 2.0.8.3, I became unable to break newly placed item pipes (tin pipes in this case) with a wrench, no break progress is made. I have tested out pipes of different materials (clay, bronze, wood) and this only happens with the tin pipes. Any tin pipes placed before I updated my world can be broken just fine, and I can adjust the pipes with a wrench just fine, just not break them.

**Comment by Dream-Master** [comment]
tin is harder then the other materials follow the Tico logic. Use a steel wrench. I Remember I change hardness level but changed it back so far ik

**Comment by chochem** [comment]
You adjusted the steel wrench, so that it can still harvest the now harder tin pipes. See https://github.com/GTNewHorizons/NewHorizons/issues/5156

**Comment by Dream-Master** [comment]
@kinjav03 craft a new steel wrench and you can harvest the pipe.

**Comment by Mac15001900** [comment]
Tin pipes are available way before the player can make steel. Can you at least update the description of the quest that tells you to craft them to warn the player that they won't be able to break those pipes until they get steel?

**Comment by Dream-Master** [comment]
Use STeel wrench that worked

**Comment by chochem** [comment]
he is aware that steel wrench works, you should read @Mac15001900's comment again. The remaining problem is only that tin pipes are available before you get your first steel and there is no warning of any kind.

**Comment by Dream-Master** [comment]
@chochem in which quest i have to write a warning text ?

**Comment by richardhendricks** [comment]
I forget, why are we not lowering the tin pipes level instead?

**Comment by chochem** [comment]
I would propose: Quest 1738 When all you have is a hammer...
This is the info quest about tools. Could say something at the end like 'Only a tool with a high enough level can be used for materials of a given level. For example, you will need a steel wrench to break tin pipes, an iron wrench is insufficient.'

although I must say @richardhendricks solution is more appealing to me.

**Comment by Dream-Master** [comment]
No Tin Level is set by Tinkers.
I add text to this two quests.
