### ISSUE TITLE
Earmuffs have no recipe

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5484]
#### Which modpack version are you using?
2.0.8.3
#
#### What did you try to do, and what did you expect to happen?
Check if they have one with NEI.
#
#### What happened instead? (Attach screenshots if needed)
No recipe appears (creative Thaumonomicon used, and all research completed)
#
#### What do you suggest instead/what changes do you propose?
There's a recipe in the quest on the witchery tab that should be used.
BTW it might be useful to mention that the ic2 crop version doesn't spawn mandrakes in the quest.

**Comment by Dream-Master** [comment]
I rember I add some

**Comment by Prometheus0000** [comment]
I checked in game, no recipe.

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
recipe has a typo

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73599476-36573900-4544-11ea-8acd-9c9a437992fd.png)
