### ISSUE TITLE
Twilight Forest swords do not destroy webs

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#5488]

**Comment by jss2a98aj** [comment]
All Twilight Forest swords are cutting spiderwebs just as fast as other swords. They also work as expected in adventure mode. Were you in creative mode? Swords do not break blocks in creative mode.

**Comment by Dream-Master** [comment]
@jss2a98aj are you test in survival  because no one play in adventure mode I guess.

**Comment by jss2a98aj** [comment]
I tested the twilight forest swords in Survival, Adventure, and Creative.
Survival: They break blocks as fast as other swords(much faster than by hand/with wrong tool).
Adventure: Same as survival.
Creative: Cannot break blocks, including webs(the same as vanilla swords)

**Comment by Dream-Master** [comment]
@richardhendricks what is the issue here ?
@jss2a98aj thanks for testing

**Comment by richardhendricks** [comment]
TIL I guess.
