### ISSUE TITLE
I cant launch GT New Horizons

### ISSUE THREAD

**Issue by ardaoks** [GTNewHorizons/NewHorizons#5492]
#### Which modpack version are you using?
The latest version on Twitch (2.0.8.3-1.7.10)
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I just tried to launch the game
#
#### What happened instead? (Attach screenshots if needed)
The game crashes instantly
#

**Comment by boubou19** [comment]
try with technic launcher, twich version is glitched for many users

**Comment by draknyte1** [comment]
Or use the MultiMC pack - http://downloads.gtnewhorizons.com/Multi_mc_downloads/
