### ISSUE TITLE
Allow locking output hatch with a fluid container

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/NewHorizons#5493]
#### Which modpack version are you using?
2.0.8.3

#
#### What did you try to do, and what did you expect to happen?
Tried to use the hand pump, ender IO fluid tank, and cells to put a fluid into an output hatch so I could lock the output type.

#
#### What happened instead? (Attach screenshots if needed)
Nothing, its an output hatch.

#
#### What do you suggest instead/what changes do you propose?
Would be nice if i could put a liquid into an output hatch so i can lock it to that liquid rather than hoping to get lucky when the recipe finishes and doesn't duplicate a liquid already locked to an output.

Alternatively, it would also be acceptable to make the multiblock check for locked outputs before picking a hatch to output a liquid to.

**Comment by draknyte1** [comment]
No.

**Comment by dragagon** [comment]
Why is this a bad thing? I can already jump through hoops to get outputs where i want if i break and rebuild the multi, why not make it easier to get the result? If its a coding limitation at least state that, but otherwise its just going to take someone longer to accomplish the same thing.

**Comment by repo-alt** [comment]
This is indeed a bad idea. but there is an alternative https://github.com/GTNewHorizons/NewHorizons/issues/3862
If @mitchej123 has no time/interest I may have a look at the issue.

**Comment by GTNH-Colen** [comment]
Being able to lock the output hatch without running the machine would be incredibly useful and has been stated as so by many users for a long time. Not sure why the hand pump is a bad idea either, might be missing something obvious but just any way to lock it without mucking about with the machine would be very nice.

**Comment by repo-alt** [comment]
I mean, being able to put anything in an output hatch is an obvious hack, and pump or not.

**Comment by dragagon** [comment]
lest we forget that the hand pump is a hack designed to remove liquid from an input that was never designed to be removed ;)

In any case, even just having the multiblock recognize that an output hatch with the liquid already exists would be nice, but i'll take any solution that lets me lock an output without being force to play whack-a-mole with the screwdriver and hoping the right one comes out in the right spot will suffice.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7b5239cf80e4ac7d0a98644f23fdd573db188e5d
