### ISSUE TITLE
Master Energy Absorber needs a recipe change

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#550]
Starting from the _master_ (512EU/t) energy absorber (and grandmaster) you need materials not available at that tier (Europium?! Go back to LuV!)

Those infusion recipes should be rebalanced/redone to be available at the tiers they're ment for.
_Magic Energy Absorber_ provides an alternative TC power generation way via energized nodes amongst other things.

**Comment by Dream-Master** [comment]
Maybe we ask Blood Asp first why he tiered it lik that.

**Comment by Dream-Master** [comment]
Blood Asp wont change anything. Magic Energy ara a very special Energy Source. I think we let the recipe like they are.

**Comment by Dream-Master** [comment]
No one make a suggestion so i close this for now.
