### ISSUE TITLE
[FEATURE REQUEST] patches

### ISSUE THREAD

**Issue by lexasub** [GTNewHorizons/NewHorizons#5503]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
i want patch for gtnh without magic 
also i want patch for gtnh without mobs from mods

**Comment by 0lafe** [comment]
Can we get one without ++ too?

**Comment by Dream-Master** [comment]
@lexasub go play vanilla Minecraft thats is without magic and without hard mobs.
