### ISSUE TITLE
Change the charm of dislocation recipe until DE is started

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#551]
The non-enhanced draconic evolution charm is craftable too early with just enderpearls and an eye of ender. Since it's a way to teleport cross dimensionally it should be tiered a bit higher, comparable to some other solutions via thaumcraft.

The non-enhanced version in question has finite uses though, and has to be remade every now and then. Could be a TC research and infusion, as usual. Perhaps even a DE tab for later.

**Comment by Dream-Master** [comment]
The whole mod need to redone.

**Comment by Teteros** [comment]
Hence the

>until DE is started

in the title. Either it gets the KAMI treatment before its recipes are done (disabled completely) or some temporary recipe needs to be thought of so players can't freely TP once they reach LV, making rockets redundant after first travel.

**Comment by Dream-Master** [comment]
Will do when i start with DE.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/14597233/c2a3a976-054b-11e6-99c3-80db1d3359de.png)
