### ISSUE TITLE
NEI beta5 left/right click bug

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5515]
#### Which modpack version are you using?
GTNH 2.0.8.3 but with NEI-beta5
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
left/right-click on an item in a chest next to a tinkers crafting station while the table is open. Expect to pick up the item.
#
#### What happened instead? (Attach screenshots if needed)
NEI search for uses/recipe. This only happens on the left edge of the chest (where the iron is in the picture).
Very likely related to the new left/right click fix in beta5.

![2020-02-04_12 01 39](https://user-images.githubusercontent.com/40274384/73743471-8d2c6080-4746-11ea-88e1-ef072aba2ea9.png)

**Comment by mitchej123** [comment]
Will have a fix out shortly -- keep an eye out for beta6

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/releases/download/2.0.0-beta-6/NotEnoughItems-1.7.10-2.0.0-beta-6-GTNH-universal.jar
