### ISSUE TITLE
WetwareSupercomputer CAS recipe is missing

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5516]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What happened instead? (Attach screenshots if needed)
WetwareSupercomputer CAS recipe is missing.
![2020-02-05_00 03 02](https://user-images.githubusercontent.com/40425798/73756570-22614080-47ab-11ea-8f8e-d502303d914a.png)

The correct recipe should use only one "Wrap of Extreme Wetware Lifesupport Circuit Board"
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by botn365** [comment]
nope 2 boards per circuit is the intendet recipy for the UV wetware board
