### ISSUE TITLE
Suggestion for Distilled Water uses

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/NewHorizons#5520]
#### Which modpack version are you using?
2.0.8.3
#

Moronwmachinegun asked me to file a ticket about what I said in #general so in FTB:Interactions, you have the option of using Distilled Water in the ore washer (its using GT:CE) instead of normal water to slightly wash crushed ores faster for quicker processing.

At base level:
LV, normal water: 25 seconds.
LV, distilled water: 20 seconds.

The only problem with this is that distilled water is made at a disgustingly low rate per operation, aka 4mb per cycle. But I'm not a dev, and this is just a suggestion, so you can do what you want. :D

**Comment by richardhendricks** [comment]
You get distilled water for free from a large boiler + turbine setup. This would make setting up steam power actually useful.  I think it's a great idea, but would go with 15s at LV to make it more enticing.

**Comment by xTwi** [comment]
Agreed, but the times I listed for what they were in the other modpack. Distilled water could be used in other recipes too such as mixer recipes in the place of normal water to speed up production or what-have-you. It needs more uses other than ic2 coolant and autoclaving for a higher %. But thats a lot of potential recipe changes, so I don't think anyone would care if you didn't.

**Comment by Dream-Master** [comment]
Make it 15 sec with 500mb distilled water at lv make it cost 16k more eu than water recipe.
Make it 15 sec with 100mb distilled water at  lv make it cost even same eu than water recipe.
I suggest 200mb to make it more profitable when using free steam from boiler or use oxygen and hydrogen.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/73924086-36509380-48cc-11ea-82fd-ed88fe6d9dc0.png)

**Comment by richardhendricks** [comment]
Thanks, looks good 

*breaks out old steam equipment*
