### ISSUE TITLE
Sword Quest (ID 11) not working

### ISSUE THREAD

**Issue by DazzleFizzle** [GTNewHorizons/NewHorizons#5523]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I crafted the sword in the quest and expected the quest to complete
#
#### What happened instead? (Attach screenshots if needed)
nothing happened
#
#### What do you suggest instead/what changes do you propose?
The quest should work

**Comment by richardhendricks** [comment]
Craft the sword in the left 3 slots of your crafting table. This is fixed for the next release.
