### ISSUE TITLE
Bartworks ASM fix for crafting speedup causing server launch issues

### ISSUE THREAD

**Issue by winsomniak** [GTNewHorizons/NewHorizons#5524]
I am in early-mid LV. Using a mix of steam machines and LV electric machines.

#### Which modpack version are you using?
2.0.8.3-1.7.10

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
I tried to load the world 3 times. Expected it to load :)

#
#### What happened instead? (Attach screenshots if needed)
 Each time, I see "loading terrain.... shutting down internal server"

#
#### What do you suggest instead/what changes do you propose?
Please take a look at the crash report, let me know if there's anything I can do to resolve myself.
```
--- Crash Report ---
removed and saved to gist

```
https://gist.github.com/Dream-Master/1701b4986f528ffa0366bb83d2240bf6

**Comment by Dream-Master** [comment]
@winsomniak please don't post logs here like this. Use Gist or pastebin and add a link instead. Thanks
@bartimaeusnek any idea ?

**Comment by richardhendricks** [comment]
@winsomniak In the bartworks config, disable the crafting ASM fix.

**Comment by winsomniak** [comment]
> @winsomniak In the bartworks config, disable the crafting ASM fix.

Hey that fixed it. Thanks!

**Comment by richardhendricks** [comment]
We'll keep this open as the source issue for this problem.

Can you provide some details?

Single player or standalone server?

Server age?
I am in early-mid LV. Using a mix of steam machines and LV electric machines.

Was the server/game setup with 7.5 and migrated? New with 8.3?

Thanks

**Comment by winsomniak** [comment]
Singe player. 
I did not migrate anything.
Only played for a week or so.
I don't have any additional logs to provide.

Sorry I can't be of more help. Appreciate the fix.

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/1256381fe5f69eb445a71142745a4bd2eeebd5a6
