### ISSUE TITLE
Adding new Fuels to the TC smeltery

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#553]
Adding Hot coolant and pahoehoe Lava to the smeltery (2X Lava).

**Comment by Teteros** [comment]
Hot coolant should be about 2x worse than regular lava (like in large heat exchanger)
and pahoehoe lava should be 2x more efficient than regular lava (like when centrifuging it)

**Comment by Dream-Master** [comment]
So Hot Coolant 50% Lava 100% and pahoehoe Lava 200% right?

**Comment by Teteros** [comment]
Correct. Should have formatted it better :)

If our @GTNewHorizons/developers can think of some other hot fluids that make sense, go ahead!
