### ISSUE TITLE
Quest #810 doesn't accept rocket with storage

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5533]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Crafted tier 1 rocket with 56 storage space and expected to complete the quest (#810)
#
#### What happened instead? (Attach screenshots if needed)
Quest doesnt see my rocket. 
#
#### What do you suggest instead/what changes do you propose?
Make the quest #810 accept rockets with storage space too. Also I need a staff member to complete the quest for me. Ign: Impossible_VT

**Comment by Dream-Master** [comment]
@Impos913 easiest way is to craft a clean rocket and add a chest later.
You can craft rocket back to rocket without a chest
![image](https://user-images.githubusercontent.com/2970688/74106822-22c25880-4b6a-11ea-8823-fee2bf65191e.png)
add chest later back
![image](https://user-images.githubusercontent.com/2970688/74106828-2eae1a80-4b6a-11ea-93f8-147dbd7bf04d.png)

**Comment by Dream-Master** [comment]
rockets have different meta ids not a simple nbt tag i could ignore.

**Comment by richardhendricks** [comment]
We need to mention in the quest to build the rocket without a chest and add the chest after you complete the quest.

**Comment by Ethryan** [comment]
Why not remove the crafting recipes where you craft the whole rocket with storage.

Maybe add the rockets and chests to the assembler where you combine them into a cargo rocket.

That way it’s impossible to craft the cargo rockets before the ordinary rocket.

**Comment by DarkGaterau** [comment]
try block "name remover"

**Comment by Impos913** [comment]
> try block "name remover"

It doesn't work.
