### ISSUE TITLE
FTB Launcher not updated since 2.0.5.1

### ISSUE THREAD

**Issue by heatskr** [GTNewHorizons/NewHorizons#5534]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Run latest versions with FTB Launcher on Linux/Fedora/Ubuntu.
#
#### What happened instead? (Attach screenshots if needed)
It is not updated since 2.0.5.1
#
#### What do you suggest instead/what changes do you propose?
Support FTB Launcher on updates for those not using Technic.

**Comment by Dream-Master** [comment]
FTB Launcher not longer supported. They said they wont update anymore so nothing i can do here.
Use technic, Multi mc or curse.

**Comment by heatskr** [comment]
Thank you, dear developer. I am closing the issue with two facts:

1. FTB Team is slowing poking us.
[Back to Minecraft and taking part in the HCMC challenge on 1.15.1](https://www.twitch.tv/videos/538985940)

2. Technic people is getting crazy
Ever living on social control and internet monitoring stone age, they think that genocide policy subject will give power to them. I am talking with my heart because we need a VIDEO GAME ONLY launcher.

![PropagandaPoster_dl](https://user-images.githubusercontent.com/348713/74066754-83b92780-49d6-11ea-9000-743f689ef1d2.jpg)
