### ISSUE TITLE
Epsilon - Request for BQM book complete reset after 3year break

### ISSUE THREAD

**Issue by Quadrai** [GTNewHorizons/NewHorizons#5536]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Used to play on Epsilon about 3 years ago all the way to early MV but then moved to a SPP world.
Ready now to play on the server again but after logging in I noticed my base has been scavenged (all LV/MV stuff is gone) and my questbook has random gaps in it. Probably due to the mytown claim expiring which is understandable after 3 years. I don't mind starting progression from zero again as I already have a building to work with but would like my questbook to be reset to scratch.
I tried crafting the Questbook Reset block but it is disabled on the server.
#
#### What happened instead? (Attach screenshots if needed)
BQM Questbook Reset block is uncraftable on Epsilon.
#
#### What do you suggest instead/what changes do you propose?
Could you manually reset my BQM quest progression to zero on Epsilon please?
Ingame name: Quadrai

**Comment by Dream-Master** [comment]
@Quadrai if you online later I can reset your quest book.

**Comment by Quadrai** [comment]
@Dream-Master I'm online on Epsilon now and should be around for a couple hours.

**Comment by Dream-Master** [comment]
fixed
