### ISSUE TITLE
Suggestion: Nerf Ross128b

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5538]
#### Which modpack version are you using?
2.0.8.3

Planet: Ross128b
Rocket: Tier 3

This planet is way to powerful for a T3 rocket at the moment. It is powerful enough that you get your first decent source of indium, no mobs, many chests. No, on top of that you get free IV machines! Among other things, this includes T2 Naquadah Generators which are very powerful and difficult to obtain at this point in the game and just game breaking.

Suggestion: limit machinces to max tier EV (this would still be great!)

Alternative: Previously there were plans to add dungeons or boss mobs or something to at least add a bit of challenge before the prize or have the machines be in a broken state ( https://github.com/GTNewHorizons/NewHorizons/issues/4958) but nothing ever came of it. The issue was closed and everything was just left as is.

**Comment by quedral** [comment]
On previous ticket Bart said that he won't change it so i see no point reopening this.

**Comment by boubou19** [comment]
already disccussed in #4958 and #4944

**Comment by chochem** [comment]
hmm, looks like you are right, Bart was quite clear on this. I cant claim that I understand it on any level but I will have to respect that decision and close the issue.

Well, I can always impose a rule on myself to ignore those items.
