### ISSUE TITLE
Bartworks ore crashes the client

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5539]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Used seismic prospector on moon and it found Bornite vein. I went there to check what is it. 
#
#### What happened instead? (Attach screenshots if needed)
Instead of Bornite I found Temagamite ore. I wanted to check recipes of Temagamite. When you press R on temagamite or left click on it on NEI crashes the client. Tried twice.

I think that ore isn't even supposed to be exist on moon. Aren't they Ross128b ores?

**Comment by Impos913** [comment]
https://pastebin.com/DZP98yXf here is the crash report

**Comment by Impos913** [comment]
Looking through pages of BartWorks Ores in NEI also crashes when it comes to temagamite vein. It cant show that page for some reason.

**Comment by chochem** [comment]
See https://github.com/GTNewHorizons/NewHorizons/issues/5392

**Comment by Impos913** [comment]
Well there is another issue. Seismic prospector said there is bornite vein, but there is temagamite vein instead.
