### ISSUE TITLE
Quest #1404 Electric Pump(MV) cannot be recognized.

### ISSUE THREAD

**Issue by quedral** [GTNewHorizons/NewHorizons#5541]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
local mp
#
#### What did you try to do, and what did you expect to happen?
Superconductors 128eu/t id:1404 Quest doesn't recognize MV electric pump unless you put them through Name Remover.
#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by DarkGaterau** [comment]
try after processing in block "Name Remover"

**Comment by quedral** [comment]
people need to learn to read the whole ticket.
