### ISSUE TITLE
[Suggestion] Additional EnderIO content

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/NewHorizons#5542]
#### Which modpack version are you using?
2.0.8.3
#
#### What do you suggest instead/what changes do you propose?
EnderIO added in 1.12 much new content so I thought it would be nice to have that too.
This includes: 

- Grinding Balls for boosting SAGMill output
- New Fluids used as Fuel and Coolant
- Upgraded Zombie Generators
- A new set of armor that is stronger that Darksteel 
- A new Solar Panel
- A new Capacitor for increased Machine speed and range

**Comment by Dream-Master** [comment]
@Zoko061602 feel free to add it like the last time :)
