### ISSUE TITLE
Tantalum quest #1835 not oredicted

### ISSUE THREAD

**Issue by daddy77gaming** [GTNewHorizons/NewHorizons#5544]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
toasted
#
#### What did you try to do, and what did you expect to happen?
tantalum quest #1835 mined up a vein in the nether expected to complete the quest, as i already came across a vein there and not in the OW figured i'd just mine that 
#
#### What happened instead? (Attach screenshots if needed)
quest wants OW ore, is this intended expected it to be oredicted
#
#### What do you suggest instead/what changes do you propose?
oredict the quest to accept any type

**Comment by Dream-Master** [comment]
there is no oredict for all types
![image](https://user-images.githubusercontent.com/2970688/74093554-98c7b080-4ad3-11ea-8d0c-aaeee0f4bc8e.png)
![image](https://user-images.githubusercontent.com/2970688/74093556-a0875500-4ad3-11ea-9163-c3a10f255bc8.png)
![image](https://user-images.githubusercontent.com/2970688/74093559-a8df9000-4ad3-11ea-89b8-4db40615bce9.png)
![image](https://user-images.githubusercontent.com/2970688/74093562-aed57100-4ad3-11ea-8d0a-a0117676c0c0.png)

**Comment by Dream-Master** [comment]
there is no oredict for any kind  of Tantalum ore
![image](https://user-images.githubusercontent.com/2970688/74093568-c876b880-4ad3-11ea-94b9-28dd14ac6025.png)
![image](https://user-images.githubusercontent.com/2970688/74093569-ce6c9980-4ad3-11ea-96f1-7830dbb53273.png)

**Comment by sthegreat** [comment]
why not have the quest take crushed tantalum ore instead? You need to crush it anyway to get the tantalum, and there's only one type.
