### ISSUE TITLE
Ore Drilling Plant Quest Issue

### ISSUE THREAD

**Issue by Greg4581** [GTNewHorizons/NewHorizons#5545]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to complete the "Time to ore drill!" quest (#1545)
#
#### What happened instead? (Attach screenshots if needed)
Did not recognize the Maintenance Hatch and MV Energy Hatch in my inventory.
#
#### What do you suggest instead/what changes do you propose?
Fix the quest.
![questissue1](https://user-images.githubusercontent.com/22825820/74094263-34d9c380-4aa4-11ea-817f-6562e339e5c5.PNG)

**Comment by Dream-Master** [comment]
must be fixed. NBT is ignored allready.
