### ISSUE TITLE
RIP GT plus plus, closed source, update GTNewHorizons/GTplusplus plz.

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/NewHorizons#5546]
I noticed alkcorp has closed the source code of gt++ few days ago.
Will you update your gtplusplus fork?
GT++ will be obfucscated from now.
last tag is : cb20041176ebfe636f9c0e73dd060fc42e45bc28

**Comment by mitchej123** [comment]
even if we did, we couldn't distribute it.

**Comment by koiNoCirculation** [comment]
@mitchej123 sure? obfuscation will fuck many things up.like asm and zs tweaker.

**Comment by mitchej123** [comment]
Read the license, it's ARR.  Plus a few of us have access to the private repo.
