### ISSUE TITLE
Paving Stairs of Warding and slabs not craftable 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#555]
Paving Stairs of Warding and slabs not craftable .

![image](https://cloud.githubusercontent.com/assets/2970688/13992486/934ba27a-f11c-11e5-81fd-bc1adb6b4660.png)

![image](https://cloud.githubusercontent.com/assets/2970688/13992387/36ecc5cc-f11c-11e5-80f4-0b6e09158e39.png)

![image](https://cloud.githubusercontent.com/assets/2970688/13992413/4a327a5a-f11c-11e5-8bc4-7b8afe9f1d4e.png)

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/845

**Comment by Dream-Master** [comment]
I fix it via java code

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/pull/846

**Comment by nekosune** [comment]
These were deliberatly not craftable as still in development

**Comment by Dream-Master** [comment]
so make it craftable but it won't have the effect yet.

**Comment by nekosune** [comment]
They do not have the full effect, and instead seem to just partially stop mobs, hence why not craftable, as I do not want to remove code that is in progress, and try and keep seperate, just to let it be craftable early.

**Comment by Dream-Master** [comment]
@nekosune 
So they will be new 1.7.10 updates in the future?

**Comment by nekosune** [comment]
There is one underway, will be the final one however, baring any world breaking bugs
