### ISSUE TITLE
Iron Electron Tube recipe

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/NewHorizons#5554]
GTNH v 2.0.8.3

The recipe for the Iron Electron Tube doesn't seem normal : 

https://i.imgur.com/0m1Nqhb.png
https://i.imgur.com/UoXk7e7.png

As you can see, the recipe for LV require specifically wrought iron. The second issue is there is also an MV recipe for the tube (the only electron tube to have one for some reason) and that one specifically require iron. Is this normal ?

Also, any update on this issue ?
https://github.com/GTNewHorizons/NewHorizons/issues/4502

**Comment by Dream-Master** [comment]
will check
