### ISSUE TITLE
EBF - Conflicting recipies for aluminium ingot

### ISSUE THREAD

**Issue by vorvac** [GTNewHorizons/NewHorizons#5555]
#### Which modpack version are you using?
GTNewHorizonsClient-1.7.10-2.0.8.3-MMC-fixed-2.zip
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
EBF recipe for aluminium ingot: Regular dust + config 1 Circuit, 157,800 EU in 65.75 seconds. This recipe happens if dust is placed before circuit. The 85s (assuming intended) recipe happens if circuit is placed before dust. I cannot view the 85s recipe.  
#
#### What happened instead? (Attach screenshots if needed)
See above.
#
#### What do you suggest instead/what changes do you propose?
Was told on discord it could be a bartworks recipe conflict.

**Comment by vorvac** [comment]
![Screenshot from 2020-02-09 14-11-31](https://user-images.githubusercontent.com/17916889/74109092-6623c380-4b78-11ea-8d41-254553c4766c.png)

**Comment by vorvac** [comment]
Dust in before Circuit: 
![Screenshot from 2020-02-09 14-13-47](https://user-images.githubusercontent.com/17916889/74109133-c31f7980-4b78-11ea-9e37-090bf1c492c7.png)

Circuit in before Dust:
![Screenshot from 2020-02-09 14-14-09](https://user-images.githubusercontent.com/17916889/74109147-cadf1e00-4b78-11ea-8d1b-b4c5a500fe13.png)

**Comment by Dream-Master** [comment]
@vorvac only aluminium ingot or other recipes too ?

**Comment by vorvac** [comment]
@Dream-Master I have only experienced this with aluminium so far, just got to MV this play through.

**Comment by botn365** [comment]
#5592 mostlikly the same same problem with titanium

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/1256381fe5f69eb445a71142745a4bd2eeebd5a6

**Comment by vorvac** [comment]
Thanks @bartimaeusnek !

**Comment by Dream-Master** [comment]
i close this later when i make a release. @vorvac
