### ISSUE TITLE
Multiblock Mixer doesnt work

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5558]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Build that thing, fixed all the issues, connect power, smacked it, put circuit and dusts in...
#
#### What happened instead? (Attach screenshots if needed)
Nothing :))
#
#### What do you suggest instead/what changes do you propose?
Check this out why please, i suspect circuits... Also apologies if its been mentioned earlier, but couldnt find that ticket...

**Comment by ScriptedPiky** [comment]
https://github.com/alkcorp/GTplusplus/pull/615#issuecomment-578597988 Fixed in latest GT++ Dev instance and was confirmed by testing it.
For the fixed version: https://circleci.com/gh/alkcorp/GTplusplus/483#artifacts/containers/0 🎉
