### ISSUE TITLE
Compressed Duralumin crash

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5559]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon 
#
#### What did you try to do, and what did you expect to happen?
Tried to check how to make Compressed Duralumin (GalaxySpace)
#
#### What happened instead? (Attach screenshots if needed)
Game crashed

https://pastebin.com/LRVv46HM

**Comment by Dream-Master** [comment]
@mitchej123 is this a crash related to the lastest Nei changes or a GC issue?

**Comment by mitchej123** [comment]
It looks recipe related.  Can probably be bypassed in nei, but unclear what the root issue is

**Comment by mitchej123** [comment]
```
        public PositionedStack getOtherStack()
        {
            return IngotCompressorRecipeHandler.afuels.get(IngotCompressorRecipeHandler.ticksPassed / 48 % IngotCompressorRecipeHandler.afuels.size()).stack;
        }

```

Seems... something... fuels related?  Is the GT++ fuel ASM enabled? Maybe that's causing it?
