### ISSUE TITLE
Add MumbleLink for positional audio support

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/NewHorizons#556]
Since we have an [official mumble server](http://forum.gtnewhorizons.com/showthread.php?tid=145&pid=502#pid502) now, I think it would make sense to add the [MumbleLink](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272675-1-8-mumblelink-forge-smp-lan-mumble-realism) forge mod to the pack, to spare time adding it.

It doesn't add items or blocks, it's merely to link mumble to the game of Minecraft.
It's a clientside mod which only works when mumble is on, and only if others have it, so it must be included in the pack to even work well enough to justify it.

**Comment by Dream-Master** [comment]
added to the Update 1.0.7.9
