### ISSUE TITLE
Windmill Grindstone Halves Crafting

### ISSUE THREAD

**Issue by Sator334** [GTNewHorizons/NewHorizons#5562]
#### Which modpack version are you using?
GTNH 2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
In single player
#
#### What did you try to do, and what did you expect to happen?
Tried crafting BartWorks Windmill Grindstone Halves, expected the recipe to output intended items
#
#### What happened instead? (Attach screenshots if needed)
Recipe did not work, output item slot was empty as though recipe was invalid
#
#### What do you suggest instead/what changes do you propose?
Fixing the recipe if possible, thanks :)

**Comment by Dream-Master** [comment]
i can craft it no problem

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/74279638-93f53d80-4d1b-11ea-8fa7-28142f1b7626.png)
![image](https://user-images.githubusercontent.com/2970688/74279674-a66f7700-4d1b-11ea-9a0e-cf277bd2851f.png)
![image](https://user-images.githubusercontent.com/2970688/74279710-b71fed00-4d1b-11ea-84cb-8e06fb0f34d2.png)

**Comment by Sator334** [comment]
I'll try again tonight, maybe it was a one time thing? Thanks for the help, I'll come back if it happens again and I'll bring screenies

**Comment by Dream-Master** [comment]
i using smoth stone and redgranite

**Comment by Sator334** [comment]
Thanks for the help! Didn't happen again, must have been an error on my side :) thanks
