### ISSUE TITLE
I found an easter egg

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/NewHorizons#5565]
#### Which modpack version are you using?
Delta version
#
#### If in multiplayer; On which server does this happen? 
Delta version
#
#### What did you try to do, and what did you expect to happen?
Details in the video
#
#### What happened instead? (Attach screenshots if needed)
Details in the video
#
#### What do you suggest instead/what changes do you propose?
I suggest not changing it because it might be an Easter egg

[Video ](https://drive.google.com/file/d/1dUw613XA91wnwJwxQSVuVDY_uZbYn3Ol/view?usp=sharing)

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5172

**Comment by Dream-Master** [comment]
fixed i guess
