### ISSUE TITLE
[BartWorks] Electric Implosion Compressor recipe missing: Pile of Neutrons

### ISSUE THREAD

**Issue by 5lx** [GTNewHorizons/NewHorizons#5566]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
My private server
#
#### What did you try to do, and what did you expect to happen?
Trying to compress some pile of neutrons from Electric Implosion Compressor. This should work because the normal Implosion Compressor has the recipe to process this.
#
#### What happened instead? (Attach screenshots if needed)
It doesn't work.
![image](https://user-images.githubusercontent.com/6583339/74414538-7b0d8a80-4df6-11ea-9694-e44715a38a4b.png)
![image](https://user-images.githubusercontent.com/6583339/74414576-89f43d00-4df6-11ea-9182-02fc67d51b35.png)

#
#### What do you suggest instead/what changes do you propose?
Please fix it.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by Ethryan** [comment]
Correct me if i'm wrong but doesn't the electric Implosion Compressor require a ridiculous amount of energy.

That NEI recipe is for the original implosion compressor.

**Comment by 5lx** [comment]
There is no issue on my electric implosion compressor setup, and it works for other recipes like industrial diamond. The issue I'm trying to show up here is that we have the Pile of Neutrons recipe for the normal gt implosion compressor, whereas there is not for the electric implosion compressor.

**Comment by bartimaeusnek** [comment]
It wont work with MT recipes. Not going to change the logic for a single recipe, its easier to pull that recipe in code.

**Comment by Kiwi233** [comment]
@bartimaeusnek 
The EIC is machine above uhv
Most commonly used to produce Neutrons
So this recipe is very important.
Can you tell us how to add it?
