### ISSUE TITLE
Pyrolyse oven texture change causes crash once formed

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5577]
#### Which modpack version are you using?
2.0.8.4
#
#### What did you try to do, and what did you expect to happen?
Load world, look around, not crash.
#
#### What happened instead? (Attach screenshots if needed)
Load world, look around, crash.
#
#### What do you suggest instead/what changes do you propose?
[crash-2020-02-14_21.42.17-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4207670/crash-2020-02-14_21.42.17-client.txt)
It happened after loading the world, when I tried to look at my wall of multiblock parts (hatches, buses, casings, controllers, etc.) It worked fine in 2.0.8.3. It seems to have to do with the texture of a GT hatch?

**Comment by Prometheus0000** [comment]
Same thing happens as soon as when loading my main world finishes (probably because I'm looking at one or something).
[crash-2020-02-14_22.12.20-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4207693/crash-2020-02-14_22.12.20-client.txt)

**Comment by nom457** [comment]
I have a similar error

**Comment by mitchej123** [comment]
Did you recently build/place something from GT, GT++, BartWorks, or KekWorks?  Curious what the erroring block is.  

Seems a hatch of some sort? Multiblock you recently built?

**Comment by Kataiser9** [comment]
I have this same error, and have not constructed any new multiblocks in many days. I also have no BW/KW multiblocks, and only one GT++ multiblock. Was all normal until 2.0.8.4.

**Comment by Prometheus0000** [comment]
I have a pyrolyse, 4xdistillery, ebf, vac freezer, and sifter, all at HV or less. I'm not sure when I last adjusted them, I haven't played in my main world for a while. 

I tried placing input/output busses and hatches and energy hatches up to HV in a clean world, but no crash. 

In my test world though, it could be anything, since I have tons placed.

**Comment by mitchej123** [comment]
It's crashing when it tries to form a multiblock is my bet.  Make the multis you have in your main world and see which one crashes?

**Comment by mitchej123** [comment]
Seems suspicious: https://github.com/GTNewHorizons/GT5-Unofficial/commit/44596d4e3500f8abd7953dddd0af2d7b51925ed5

**Comment by Prometheus0000** [comment]
Crash forming the pyrolyse 
[crash-2020-02-14_23.11.53-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4207736/crash-2020-02-14_23.11.53-client.txt)

**Comment by mitchej123** [comment]
@Dream-Master was the pyrolyse "fix" tested before being merged?  Seems it might be... buggy?

**Comment by Spartak1997** [comment]
@mitchej123 holy... Yep, it's my mistake. Can you change ID? It should be 1090, because (8x128)+66

**Comment by Dream-Master** [comment]
@Spartak1997 Please make a pull I fix later

**Comment by Dream-Master** [comment]
@Prometheus0000 try with this version
http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/396/
thanks

**Comment by Hyperic88** [comment]
I have the same issue upon loading world, it CTD after few sec
[crash-2020-02-15_01.26.03-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4208516/crash-2020-02-15_01.26.03-client.txt)

**Comment by Prometheus0000** [comment]
Hangs on loading world with new version
[crash-2020-02-15_10.15.51-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4208630/crash-2020-02-15_10.15.51-client.txt)

**Comment by Prometheus0000** [comment]
It seems that the fix works for some people. It worked in my clean test world, but not my main one, so I dunno what's up with that. When I entered my clean test world that had previously crashed, the pyro wasn't formed because I had put the input bus on the side (but it crashed before anyway). After moving the bus it formed correctly without crashing. I'm wondering if already formed pyros don't work because of pointing to a texture that no longer exists? I'm going to go back a version break it and reimport it to check.

**Comment by Prometheus0000** [comment]
After doing the above and forming it again it doesn't crash. So informing people to break them before updating might be necessary.

**Comment by chochem** [comment]
had the same crash. Was able to load my 8.3 save into the 8.4+fix instance without any need to break the pyro. Everything works.

Your persistent problem probably stems from loading the pyro in 8.4 without fix and then applying the fix on that save and not going back to a backup.

**Comment by Prometheus0000** [comment]
It seems you're right, I went back to my 8.3 save, formed the pyro, replaced the 8.4 one with it, and loaded the world to find it not crashing. So only the people who grabbed the pack early will be affected I guess.

**Comment by Hyperic88** [comment]
[crash-2020-02-16_23.49.28-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4211190/crash-2020-02-16_23.49.28-client.txt)
thats my latest crashfile for Mitchej123

**Comment by mitchej123** [comment]
Added https://github.com/GTNewHorizons/GT5-Unofficial/pull/241 to avoid crashing -- will allow anyone impacted by this to break and reform.
