### ISSUE TITLE
[BUG] Circuit can still be produced with old recipe

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/NewHorizons#5579]
#### Which modpack version are you using?
2.0.8.3

For example, 
![image](https://user-images.githubusercontent.com/42833050/74582543-6a2c6700-4ff8-11ea-9faa-55ed4b13e2c8.png)
iv circuit can be produced like this

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/1256381fe5f69eb445a71142745a4bd2eeebd5a6
