### ISSUE TITLE
Fix for minetweaker issues?

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#558]
Should resolve file sorting issues on server and client resulting in broken recipes.

https://github.com/stanhebben/MineTweaker3/pull/274

**Comment by Dream-Master** [comment]
Ok i make a fork if i had time and will add the code.
But allways remember "1Bug is fixed yea......oh 99 new bugs :("

**Comment by Dream-Master** [comment]
I hope soon we get Craft Tweaker (after NBT support) which solved the problem also.

**Comment by Dream-Master** [comment]
We using craft tweaker which have this code allready added. So no problems anymore.
