### ISSUE TITLE
Industrial Wiremill broken struktur

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#5580]
#### Which modpack version are you using?
283
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
existing wiremill say broken strukture
Picture of strukture (GUI in controller) changed but comment in NEI of controllerblock doesent changed. 
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
actualized Block Info

**Comment by Ngar1** [comment]
GUI Wiremill:
![Wiremill_broken_GUI_View](https://user-images.githubusercontent.com/7759876/74600552-977a2300-5093-11ea-9b6c-d9f3af797fa5.JPG)
Enthält neue Blockdefinitionen (top-center, middle-side), die in den NEI Kommentaren nicht enthalten sind:
![grafik](https://user-images.githubusercontent.com/7759876/74600604-1cfdd300-5094-11ea-8af2-e1d6aeadcec2.png)

**Comment by Ngar1** [comment]
Id would be also nice to hear, what to do - befor correction :-)

**Comment by Dream-Master** [comment]
@Ngar1 this is a GT++ device. Please report here also.
https://github.com/alkcorp/GTplusplus/issues

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?

**Comment by Ngar1** [comment]
now the 32 casings are checked
