### ISSUE TITLE
Unable to access Toxic Everglades

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/NewHorizons#5581]
#### Which modpack version are you using?
2083
#

#### If in multiplayer; On which server does this happen? 
private server
#

#### What did you try to do, and what did you expect to happen?
The Portal Frame needs Pikyonium64B, and Pikyonium64B needs Yb. But the Yb can only be found in Toxic Everglades.

**Comment by boubou19** [comment]
Yb can be obtained out of rare earth with gt++ route (xenotime out of rare earth I)

**Comment by nanmumc** [comment]
> Yb can be obtained out of rare earth with gt++ route (xenotime out of rare earth I)

Oh, sorry to forget the new production way. Thanks, let's close this issue.

(By the way, cauldron can still purified the impureDust to regular dust, likes Pt,Ir,Os...
And, rare earth can still be processed by Centrifuge)
