### ISSUE TITLE
quest #1888 "Repairing your Hazmat Suit" can't be completed

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#5583]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
tried to complete the quest 1888 "Repairing your Hazmat Suit" can't be completed
#
#### What happened instead? (Attach screenshots if needed)
can't make the questbook recognize the soft hammer (crafted rubber one and woodden one but it did not recognize them)
#
#### What do you suggest instead/what changes do you propose?
maybe some nbt related issue

**Comment by NickDuijndam** [comment]
Ran into the same issue, using version 2.0.8.4

**Comment by Dream-Master** [comment]
Soft mallet removed
