### ISSUE TITLE
Enchantment table

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/NewHorizons#5586]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/74596905-7e23a780-5090-11ea-9723-05829c83fb62.png)
According to the quest book, it should able me to craft an Enchantment table
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/74596922-de1a4e00-5090-11ea-9a22-09e6ded40594.png)
But I can’t study it in my magic research book

#
#### What do you suggest instead/what changes do you propose?
I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it I need it

**Comment by Prometheus0000** [comment]
The research reqs are in the CoreMod.zs file. For this it should be nitor and alumentum.

**Comment by richardhendricks** [comment]
Need to re-arrange quests so Nitor and Alumentum are required before enchanting table
