### ISSUE TITLE
Berry Medly crashing game (SMP)

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#559]
I crafted with strawberry (pams), blackberry (pams), and blueberry (natura), had crash occur in tcon crafting table and vanilla.

crash log : http://pastebin.com/raw/WgMB5aad

**Comment by Dream-Master** [comment]
http://i.imgur.com/n2t5iZ4.png

**Comment by mrgreenacid** [comment]
Here is a previous crash log in a vanilla crafting table.

http://pastebin.com/raw/H7nVDa4G

**Comment by mrgreenacid** [comment]
@Dream-Master 
Login issue may be unrelated, I tried to connect a few minutes after I got that screen and it went through.

**Comment by deeplyarnab** [comment]
I believe it's the same as https://github.com/GTNewHorizons/NewHorizons/issues/452

**Comment by Namikon** [comment]
Almost the same, yes. This time it's the achievement subsystem of gravisuite. Working on a patch already

**Comment by Dream-Master** [comment]
This Build will fix it

http://jenkins.usrv.eu:8081/job/GravitationSuite/34/

I make a update soon.

**Comment by Dream-Master** [comment]
@Namikon 

please read the pm i sen you.

https://gist.github.com/Dream-Master/b1b71ef6687d1dbf9c3a758dc47a9263#file-fml

**Comment by Dream-Master** [comment]
Bug gone for no reason.

**Comment by Dream-Master** [comment]
Maybe 1. April fool :-1:
