### ISSUE TITLE
Missing recipe for drawers, storage upgrades, and keys

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5590]
#### Which modpack version are you using?
2.0.8.4QF
#
#### If in multiplayer; On which server does this happen? 
SP
#
there is no recipe for drawers. I checked Oak, Dark Oak, Acacia, Jungle, Birch, Spruce.

**Comment by chochem** [comment]
wait, the storage upgrades also dont work. Are all recipes from the storage drawers mod broken?

**Comment by Dream-Master** [comment]
@leagris any idea ?

**Comment by leagris** [comment]
@Dream-Master Fixed in dev
