### ISSUE TITLE
EBF not working properly

### ISSUE THREAD

**Issue by MadeofGold** [GTNewHorizons/NewHorizons#5592]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Official Delta
#
#### What did you try to do, and what did you expect to happen?
Smelt titanium using circuit 1 a recipe needing 98 s
![titanium](https://user-images.githubusercontent.com/38396468/74605680-edba8680-50d2-11ea-814e-628ae0af1747.PNG)

#
#### What happened instead? (Attach screenshots if needed)
EBF processes it at 120 s 
![ebf](https://user-images.githubusercontent.com/38396468/74605707-25293300-50d3-11ea-89c8-89758c9fba0d.PNG)

**Comment by boubou19** [comment]
checked the input bus: only circuit configuration 1 and titanium dusts. EBF just fixed with duct tape to ensure it running at 100% efficiency, input hatch filled with oxygen and EBF running at EV with 2 hv energy hatches.

**Comment by mitchej123** [comment]
Is it getting enough energy?

**Comment by boubou19** [comment]
yeah ev bat. buffers with 2 batteries directly next to the hatch, for each energy hatch

**Comment by mitchej123** [comment]
If you have two energy hatches you're explicitly telling it to overclock to IV; is that your intention?

**Comment by boubou19** [comment]
no he has two hv energy hatches making it unlock the recipe which is available at ev. 
Also if it gets an overclock then it consumes more power making it fails the recipe no? this is weird

**Comment by mitchej123** [comment]
Ah that makes more sense.   Both bat buffs are pointing directly to the energy hatches? No cables for loss?

**Comment by mitchej123** [comment]
And everything's in one chunk?

**Comment by boubou19** [comment]
no cable loss but did not checked the chunk boundaries

**Comment by botn365** [comment]
this is most likly the same problem as #5555 sinse the 98.65 seconds is clearly autogenrated while 120 seconds is a manual recipe

**Comment by Dream-Master** [comment]
@MadeofGold @boubou19 @mitchej123 @botn365 
So is it Bartworks recipe or a GT one?

**Comment by botn365** [comment]
120 is gt 96 is bartworks

**Comment by Dream-Master** [comment]
@botn365 why bartworks use own recipes? With a custom fluid or override stuff ?

**Comment by boubou19** [comment]
it overrides the default titanium recipe with no fluid

**Comment by botn365** [comment]
becous he autogenrated a bunch of recipes so using higher tier gas would mean faster smelting times but why the no gas recipes dont know ask @bartimaeusnek

**Comment by MadeofGold** [comment]
The EBF is in the same chunk.
A werid thing happens , if i break any block (even controller ,but after that i need to repair) the recipe goes back to 98s after some time it goes to the 120 s

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/1256381fe5f69eb445a71142745a4bd2eeebd5a6
