### ISSUE TITLE
Exxon mobile could use more info

### ISSUE THREAD

**Issue by daddy77gaming** [GTNewHorizons/NewHorizons#5594]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
toasted

![image](https://user-images.githubusercontent.com/31905330/74606260-46882000-50cf-11ea-9106-cc27c0fc64db.png)

I know there is tons of info on this currently as it is, tho it feels to be short some info.

Some thoughts a NOOB to this multi may have:
For example (like most multis do) 
How many input / output hatches do you need
How many input / output busses do you need
How about power? does it need any? 
Does it need a muffler? does it even produce pollution? ( why wouldnt it.. it's a chemical plant after all)

Checking discord there are not too many peepz toying around with it, that may also be bc it's a bit scary big and unknown.

If you search well enough you can find this, which shows main structure: 

![image](https://user-images.githubusercontent.com/31905330/74606388-56543400-50d0-11ea-8fb3-a898b820829d.png)

**Comment by Prometheus0000** [comment]
See #5483 and the quest in HV. Go to the gt++ github if you want to post suggestions to add to the tooltip.

**Comment by daddy77gaming** [comment]
Just a FYI for ANYONE using this picture as a guide.. the structure it shows is FINE.
JUST DO NOT USED MACHINE HULLS as stated in it!
