### ISSUE TITLE
Questbook singularity triger dont work

### ISSUE THREAD

**Issue by DarkGaterau** [GTNewHorizons/NewHorizons#5595]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
Name Remover
#
#### What happened instead? (Attach screenshots if needed)
nothing https://i.imgur.com/NIInZGx.png
#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by boubou19** [comment]
iirc name remover only works for gt based items

**Comment by DarkGaterau** [comment]
> iirc name remover only works for gt based items

What did you try to do, and what did you expect to happen?
Name Remover
What happened instead? (Attach screenshots if needed)
nothing

**Comment by Dream-Master** [comment]
i set ignore NBT to true
