### ISSUE TITLE
My Beter Questing progress and contents files are corrupted.

### ISSUE THREAD

**Issue by Comrade-Corbyn** [GTNewHorizons/NewHorizons#5597]
#### Which modpack version are you using?

#I'm using version Version: 2.0.7.5-1.7.10
#### If in multiplayer; On which server does this happen? 

#A personal server me and my friend play on
#### What did you try to do, and what did you expect to happen?

#It seems to have corrupted in either server shut down last night or startup this morning.
#### What happened instead? (Attach screenshots if needed)

#The quest book has no contents.
#### What do you suggest instead/what changes do you propose?
Is there any way to recover this, or will we have to purge these files and finish quests through admin commands?

**Comment by quedral** [comment]
Firstly you can try "/bq_admin default load"

If this doesn't help you can try to download original 2.0.7.5 server files and replace everything except the world folder and try again the "/bq_admin default load"

Again if this doesn't work there is not much you can do except revert back to an old backup save.

This is not a pack issue. This is:  _"You should have backed up son"_ kinda situation so good luck.

**Comment by mitchej123** [comment]
We replaced BQ1 with BQ3 to help address these issues.  Upgrade to 2.0.8.x; the version you're on is unsupported.
