### ISSUE TITLE
java.lang.RuntimeException: No OpenGL context found in the current thread.

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#560]
When Connecting to Prospercraft's GTNH server, i receive this error: 

![opengl crash](https://cloud.githubusercontent.com/assets/10765948/14163601/a4f4bcbe-f6bc-11e5-91e1-fbc7fcb85f3a.png)

I don't receive this error in any single player game, and i've tried this on 3 different windows 10 machines, trying to run pack versions 1.0.7.8c, d and e.

This log is from a 1.0.7.8d version.

[log.txt](https://github.com/GTNewHorizons/NewHorizons/files/196886/log.txt)

**Comment by Teteros** [comment]
>I don't receive this error in any single player game.

It does not occur on our _official_ EU server nor a fresh Thermos/kCauldron server install of the modpack.
See https://github.com/GTNewHorizons/NewHorizons/issues/548.

This really narrows it down to @ProsperCraft's particular server instance. Some report it's bungeecord, and connecting to the hub (play.prospercraft.com) works, some not.

You'd think that OpenGL message is typical for clients. (not servers!) We are at a loss at what it could be and cannot replicate it.
