### ISSUE TITLE
Little Helpers quest issue

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/NewHorizons#5600]
#### Which modpack version are you using?
2.0.8.4QF
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Crafted Straw Golem and expected quest to pick it up.
#
#### What happened instead? (Attach screenshots if needed)
Quest log did not detect the newly crafted straw golem.
#
#### What do you suggest instead/what changes do you propose?
Need to fix the detection of the straw golem.

**Comment by Zodiack256b** [comment]
Removing gadomancy tag from the raw nbt in better questing made it detect for me.

**Comment by Dream-Master** [comment]
@Zodiack256b why not make a pull request?

**Comment by Zodiack256b** [comment]
Still pretty new to github so not quite sure how to use the pull request.

I retested this in a test world and actually just setting ignoreNBTdata to true on the golem was enough to fix it instead of trying to remove the gadomancy nbt tag.

**Comment by Dream-Master** [comment]
ok will do a fix
