### ISSUE TITLE
OreDict "good" circuits for Microchips (Level 1)

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/NewHorizons#5607]
#### Which modpack version are you using?
2.0.8.3

#
#### What did you try to do, and what did you expect to happen?
Tried to use integrated processors rather than Good Circuits
#
#### What happened instead? (Attach screenshots if needed)
Refuses to craft with anything other than good circuits
#
#### What do you suggest instead/what changes do you propose?
OreDict the circuits like the rest of open computer recipes.

**Comment by repo-alt** [comment]
Why no one looks at already open issues?
https://github.com/GTNewHorizons/NewHorizons/issues/5154

**Comment by Dream-Master** [comment]
@dragagon Yes this is an issue not easy to fix.
