### ISSUE TITLE
Gendustry, DNA liquification.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#561]
DNA Extractor has no recipes that allow for liquid dna production.
This rends the setup for DNA Extractor, Genetic replicator and Protein Liquifier useless. (The machines are still craftable.)

**Comment by Technus** [comment]
Overlooked, labware needs to be supplied.

But still some issue after binnie patcher update - bees cannot be liquified.

**Comment by Dream-Master** [comment]
I come to the conclusion with Bdew that the recipe never worked because the file was every time in the override folder. I put it back to the main folder and will test it.

**Comment by Drobac** [comment]
The gendustry machines work just fine, no problem

**Comment by Dream-Master** [comment]
Yep but we never have all the ingredients. After my change all works fine.
