### ISSUE TITLE
Add server please

### ISSUE THREAD

**Issue by Relvl** [GTNewHorizons/NewHorizons#5611]
Just reminder for @Dream-Master from discord. Dont panic or shouting please ;)

```
website: https://hgames.enjin.com/
mc server: 51.75.61.80:25565
name: Hard Games [RU]
whitelist/graylist: no
```
![2020-02-18_11-35-57](https://user-images.githubusercontent.com/4003026/74710189-dac6c400-5242-11ea-925c-e9b9e7ce6f4e.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/74872514-9bd96100-535d-11ea-8374-45dafb3b3c2b.png)
