### ISSUE TITLE
Set default holoinventory keymode to 1

### ISSUE THREAD

**Issue by sleepylucy** [GTNewHorizons/NewHorizons#5613]
Change the holo inventory config file to use keymode 1 (The key toggles the rendering) instead of 0 (Always display hologram). Mode 0 makes no sense, and if you don't like it to be always on you won't have to restart the client anymore to change the config file if you forgot to change it beforehand.

**Comment by code32** [comment]
> Change the holo inventory config file to use keymode 1 (The key toggles the rendering) instead of 0 (Always display hologram). Mode 0 makes no sense, and if you don't like it to be always on you won't have to restart the client anymore to change the config file if you forgot to change it beforehand.

You forgot a little about those who needed him. Now they have to restart the client.

**Comment by Dream-Master** [comment]
@code32 in next version we have a Glasses for it
https://twitter.com/DreamMasterXXL/status/1238135272166088704

**Comment by sleepylucy** [comment]
> Now they have to restart the client.

No, you don’t have to restart the client you just have to press the “toggle holoinventory” keybind, then it’s on again. That’s what “toggles hologram” means
