### ISSUE TITLE
Passive Chunklaoding quest not work

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/NewHorizons#5616]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/74786834-a1489400-52e8-11ea-9ff7-92c24139164c.png)

#Passive Chunklaoding quest now work
#### What do you suggest instead/what changes do you propose?
Passive Chunklaoding quest not work

**Comment by Dream-Master** [comment]
@Eason134HK why you open an issue if it works ?

**Comment by richardhendricks** [comment]
I think they meant "not" working?

**Comment by Dream-Master** [comment]
NBT ?

**Comment by richardhendricks** [comment]
I am not sure if this is an nbt issue or not.  Which task is failing to complete? Did you test it?

**Comment by Dream-Master** [comment]
no. we need to ask the reporter @Eason134HK
