### ISSUE TITLE
Algae pond multiblock - wrong tooltip

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5618]
#### Which modpack version are you using?
.8.5
#
#### If in multiplayer; On which server does this happen? 
Zeta

I tried to build Algae pond multiblock, according to NEI there should be bottom level made of machine hulls (81-4 for hatches) of same level that determines the speed and I/O hatches + maintenance hatch. If you follow that tooltip machine wont form. 

Algae Pond doesnt need maintenance hatch (but its mentioned it needs one) but its optional, since it doesnt need maintenance (that is mentioned)
and the bottom layer is not made of hull but merely machine casings - tested in singleplayer.
![2020-02-19_02 45 02](https://user-images.githubusercontent.com/14223368/74793833-d8577f00-52c1-11ea-99ff-fbc32120de61.png)

**Comment by Prometheus0000** [comment]
If this is a GT++ multi, you should report it there.

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/issues/644

**Comment by botn365** [comment]
the tooltip is fixed in dev

**Comment by Dream-Master** [comment]
@botn365 ok i see
