### ISSUE TITLE
Enderpearl Block has two shapeless recipes

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#562]
http://i.imgur.com/6MAtMqi.png

Need to use Remote IO's Intelligent Workbench to distinguish?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/bde72ae36870cec32c1d7483bafbda708eeb71a2

**Comment by mrgreenacid** [comment]
Actually almost all blocks from GemBlocksForGreg

**Comment by Dream-Master** [comment]
yes i am on it.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/23487f45b57a607139d40dcfcb203bb80c699c95
