### ISSUE TITLE
Storage Drawers Upgrade Template missing recipe

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/NewHorizons#5622]
#### Which modpack version are you using?

2.0.8.4

#### If in multiplayer; On which server does this happen? 

Singleplayer

#### What did you try to do, and what did you expect to happen?

Craft Storage Drawer Upgrade Templates in order to complete quest "Upgrading Drawers" (steam age).

#### What happened instead? (Attach screenshots if needed)

Upgrade Templates don't show a recipe in NEI, making me unable to craft them.

#### What do you suggest instead/what changes do you propose?

Add the recipe back. I guess it went missing with the Storage Drawer upgrade in 2.0.8.4.

**Comment by Dream-Master** [comment]
@wlhlm use version 1.11.2 from Storage Drawers
https://github.com/GTNewHorizons/StorageDrawers/releases/tag/1.11.2-gtnh
 or 2.0.8.5 Dev version on http://downloads.gtnewhorizons.com/ClientPacks/

**Comment by Dream-Master** [comment]
@wlhlm na wieder dem GTNH Fieber verfallen :) Nice and welcome

**Comment by wlhlm** [comment]
:-)

**Comment by Dream-Master** [comment]
@wlhlm https://discord.gg/EXshrPV

**Comment by wlhlm** [comment]
Ok, I just checked, the template (only) has an assembler recipe in 2.0.8.5 -- do you build an assembler in steam age? Otherwise the quest line I mentioned above doesn't really make sense in steam age.

**Comment by Dream-Master** [comment]
@leagris is this a steam age recipe or a LV one ?

**Comment by Prometheus0000** [comment]
In 2.0.7.5 at least, there's 2 recipes, one that needs steel screws, and one that uses the assembler.

**Comment by chochem** [comment]
the one with steel screws has been removed for no apparent reason. Should really be restored.
