### ISSUE TITLE
T button won't register in ME terminal search

### ISSUE THREAD

**Issue by Jaalte** [GTNewHorizons/NewHorizons#5626]
( This is my first issue post ever and i'm not sure if it belongs here or on the AE2 page so bear with me please )

#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Locally-hosted server
#
#### What did you try to do, and what did you expect to happen?
Type any word into an AE terminal that includes the letter T
#
#### What happened instead? (Attach screenshots if needed)
All letters type fine except for T.
- IE if I was typing "tin" it would only register "in," or if I was typing "interface" it would register "inerface."
- No other letters are affected.
- If I press the T button multiple times it'll eventually register and work fine until I close the GUI, but every time it is reopened the problem comes back. The number of presses this takes varies significantly, usually 1-5.
- Clicking the search bar also fixes it
- Removing all keybinds on the T key (including chat) doesn't fix the issue.
#
#### What do you suggest instead/what changes do you propose?
This is more of a bug report so I don't know what to put here

**Comment by chochem** [comment]
have you checked the NEI keybinds? They are only in the NEI options. Most likely you have T bound to search in world, so that in tries to find the item you are hovering over. T then only works in your ME system if you dont hover over anything. Best just change the keybind.

**Comment by boubou19** [comment]
T keybind in NEI is useful to check in nearby inventories the item you where hovering while pressing T: if the gui closes itself then it has detected something so look around you and you'll find white particles

**Comment by Jaalte** [comment]
Changing that keybind fixed the bug. I haven't been able to get the search functionality to work even in GUIs besides the ME terminal, but that's likely me missing something and a whole different issue. Thanks for the help!
