### ISSUE TITLE
Arcane crafting terminal drawers tape dupe (2.0.8.3)

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/NewHorizons#5627]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Multiplayer private server
#
#### What did you try to do, and what did you expect to happen?
Put items in drawer.
Pack drawer with packing tape.
Take some more empty drawers same type.
Put packed and empty drawer in arcane crafting terminal
Shift click on packed drawer first
Shift click on empty drawer

2 different drawers in inventory expected.

#
#### What happened instead? (Attach screenshots if needed)
2 packed drawers with items in inventory.

#
#### What do you suggest instead/what changes do you propose?
Fix it :)

[Twitch clip to illustrate dupe](https://clips.twitch.tv/HonestAverageSpaghettiTooSpicy)

**Comment by repo-alt** [comment]
The same bug as duplicating random fluid with the terminal.
https://github.com/GTNewHorizons/NewHorizons/issues/5371

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/ThaumicEnergistics/commit/c01030e49b79fe17afda223ef8cee9f7919a84a9
