### ISSUE TITLE
Large Sifter not doing the correct number of process with certain recipes

### ISSUE THREAD

**Issue by zacharyandrews** [GTNewHorizons/NewHorizons#5629]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Yes, Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Put purified cinnabar ore into the large sifter at MV tier which should process 8 at a time
#
#### What happened instead? (Attach screenshots if needed)
It processed it 5 at a time
#
#### observations after testing
it appears at LV it will process 1 instead of 4 but at HV it will process the intended 12 (not tested at EV or greater) also Palladium Salt Dust, Platinum Salt Dust, and Rhodium Nitrate Dust behave the same way

it should be noted that these recipes are the only recipes to have 9 possible outputs instead of the typical 6 outputs, have yet to see a 6 output recipe behave this way

**Comment by botn365** [comment]
iirc the recipe is 30 eu/t so if you feed LV it only has the enrgy to do 1 recipe
and in HV 30 * 12 = 360 eu/t o now it has al the eu/t to process at max parrallel

**Comment by zacharyandrews** [comment]
ok yeah you're right forgot to check the power for the recipe so yeah the actual output is correct for these recipes will close this issue
