### ISSUE TITLE
Cyprium doesn't accept copper ore as soil.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5633]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Placed a copper ore below cyprium crop and expected it to grow as mentioned in crop description.
#
#### What happened instead? (Attach screenshots if needed)
![2020-02-21_16 11 22](https://user-images.githubusercontent.com/36479271/75042230-c2ff7200-54c6-11ea-8eec-3814331f227f.png)
![2020-02-21_16 18 37](https://user-images.githubusercontent.com/36479271/75042236-c561cc00-54c6-11ea-851a-dca6cd911d9e.png)
it says 'Can grow:  No'
#

**Comment by boubou19** [comment]
gt ore or ic2 ore?

**Comment by Impos913** [comment]
GT ore, can you even get ic2 ore?

**Comment by boubou19** [comment]
yeah bedrock dim or bloodmagic ritual to get a sphere of ores but if it needs ic2 one then i have a workaround : simply make a copper block and put it underneath

**Comment by Impos913** [comment]
You cant just say that. If it says 'Requires copper ore as a soil block to grow' it should accept GT ore. I suggest to change that. Also I dont have a compressor to make block right now.

**Comment by leagris** [comment]
Long awaited wish:

- Enable Gregtech to generate other mods/vanilla ore blocks in veins.

Alternatively:

- Add ore blocks into Chisel groups, to allow switching ore. 
  (*I am aware it sounds like Chisel is my sole hammer-like tool, and every pack issue is chisellable*).
- Example: put Gregtech copper stone-bound ore block into chisel, and replace it by an IC2 or Forestry ore block.  
  Limiting the interchangeable ore blocks to Overworld stone-bound types would maintain balance and prevent glitching ores with different yield.

**Comment by sthegreat** [comment]
all the ic2 metal crops have (ferru cyprium etc.) this issue because they just check oredict instead of using the necessary gt method to deal with gt's te ores. Metal blocks work but it would be useful if someone asmed or otherwise patched ic2 for this.

**Comment by Prometheus0000** [comment]
I went though the wiki previously to show the exact blocks you can use. If it doesn't specify the mod on the page, it's the GT ore/block or the block gotten by the compressor.

**Comment by Dream-Master** [comment]
chisel gt to vanilla ore I am ok with

**Comment by Dream-Master** [comment]
I will add Quests for interchange Ores from Vanilla, IC2 etc.
