### ISSUE TITLE
Quest Forming Press v0.1

### ISSUE THREAD

**Issue by flvranckx** [GTNewHorizons/NewHorizons#5634]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
Trying to solve quest "Forming Press v0.1" but impossible to find the solution without asking the discord
#
#### What happened instead? (Attach screenshots if needed)
The quest ask for a knife, but does not specify how to make one. The answer was hidden in page 51/77 of NEI, which is not very noob friendly and player could get stuck. 
#
#### What do you suggest instead/what changes do you propose?
The quest should specify how to make a flint knife. Or the recipe for the flint knife should be in first or last place like in previous versions.

**Comment by chochem** [comment]
to clarify a bit: there is flint knife quest in tier 0. It says the recipe is on the 'last NEI page'. this is no longer the case. It would be better to say: 'craft with a flint above a stick' or something like that
