### ISSUE TITLE
Wrong tip on tanks

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5638]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
wrong tip on buildcraft and iron tanks' tank
 
![2020-02-23_02 24 24](https://user-images.githubusercontent.com/48137054/75105628-adcc3580-55e3-11ea-9b74-e7049350de52.png)

#

**Comment by Dream-Master** [comment]
@bjin2000 its some visual bug from Bartworks so far ik. @bartimaeusnek  ?

**Comment by bartimaeusnek** [comment]
It's not a bug, its a visual indicator for the glass level it is. You can build the MegaEBF or the VAT with these blocks for HV level.
