### ISSUE TITLE
Two same recipes of electrotine

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5639]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
crafting electrotine in mixer
#
#### What happened instead? (Attach screenshots if needed)
two same recipes with different energy required
![2020-02-23_02 31 21](https://user-images.githubusercontent.com/48137054/75105702-9fcae480-55e4-11ea-8e91-e155767a8601.png)
![2020-02-23_02 31 35](https://user-images.githubusercontent.com/48137054/75105704-a22d3e80-55e4-11ea-8bbf-5d27085e1fcb.png)

#
#### What do you suggest instead/what changes do you propose?
which is correct one

**Comment by Dream-Master** [comment]
will check. I guess this one with the circuit

**Comment by boubou19** [comment]
confirmed in 2.0.8.3 on delta: the circuit version is with a circuit configuration on 1

**Comment by Eason134HK** [comment]
Of course the cheaper one is correct
