### ISSUE TITLE
Suggest: keep galacticraft's schematic

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/NewHorizons#5640]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
scan galacticraft's schematic on scanner
#
#### What happened instead? (Attach screenshots if needed)
schematic was consumed
#
#### What do you suggest instead/what changes do you propose?
keep schematic since it can only be found on dungeon

**Comment by Dream-Master** [comment]
You can pruduce the rocket control circuit <ou dont need a schematic. Schematics are interchangeable in Tier.
