### ISSUE TITLE
remove europium from LuV lapotronic orbs

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5645]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What do you suggest instead/what changes do you propose?
ev lapos can be mad ein the start of EV
IV laops can be made at the start of IV
but LuV lapos need fusion to be made wich at that point your prety much in ZPM
that also means you have to go trough LuV still using the IV ones and being very limitid in amps
if somone is not using the pss

**Comment by draknyte1** [comment]
There’s always energy buffers. 😂

**Comment by botn365** [comment]
you mean the LuV energy buffer that needs ZPM to make

**Comment by repo-alt** [comment]
isn't there sunnarium LuV battery?

**Comment by botn365** [comment]
sure but those are prety bad storage wise

**Comment by 0lafe** [comment]
Batteries for storage post HV are a dumb idea

**Comment by botn365** [comment]
pss bad 
batterys bad 
then how am i suposed to mange energy

**Comment by GTNH-Colen** [comment]
Just generate UIV constantly and then you won't need batteries. /s

In all seriousness maybe this isn't a bad idea, the cost of some of the high tier batteries kinda force you towards the PSS so if anything **certain people** should want something like this as it makes other energy storage options more attractive...

**Comment by 0lafe** [comment]
Low storage still allows them to function as good throughput averagers, but not enough for running things with generation off, or running things that consume more power than you gen for an extended period of time. 

You can still do those things, but the cost/issues with setting it up usually outweighs the benefits.

**Comment by GeicowithaBango** [comment]
I would appreciate if luv lapos wouldnt need europium but still have the assline recipe which makes them cheaper past-fusion. the price is decent (just replace eu with sth else) for their use. sunnarium doesn’t require the infrastructure that lapos do, so its really no argument about short storage.
