### ISSUE TITLE
A couple of notes after completing steam age

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/NewHorizons#5649]
#### Which modpack version are you using?

2.0.8.5

#### If in multiplayer; On which server does this happen? 

Singleplayer

### Bugs

**Quest "Repairing your Hazmat Suit"** I was unable to complete this quest, since it wouldn't detect a soft mallet in my inventory. I've tried it with freshly crafted wood and rubber soft mallets.

*Already reported in #5583.*

### Suggestions

**Quest "Factory Iron Door"** This quest has some weird phrasing: "For your new Factory you need iron doors. Well the recipe is really hard and need steel." I suggest: "For your new Factory you need iron doors. Unfortunately, the recipe is really hard, needing steel."

**Quest "Making a list, checking it twice"** Maybe add a note to the quest that you can put the clipboard on a wall using Shift-Rightclick. I stumbled upon this by accident and it made the Clipboard a lot more useful.

**Quest "What can I put all these items in ?"** The quest notes to check the key bind to access the backpack: "Check out the 'Backpacks' control configuration 'Open Backpacks' and remap it to a new key." Maybe it should also say that the key binding only works *after* the backpack is added to the back slot, which can be done using Shift+&lt;Open Backpacks Key>.

### Questions

~~**How do you dismantle small tin item pipes?** A wrench didn't work on them like it would on fluid pipes, meaning it took a long time to break the item pipe and it didn't drop the item. (WAILA also says "Effective Tool: Wrench", but alas...)~~

*Needs a higher level wrench (level 3 and up). Related issue #5482*

**Comment by boubou19** [comment]
for the quest "Repairing your Hazmat Suit" see #5583.
For the tin item pipes, try using a wrench with a better material because wrenches also have levels like mining levels for pickaxes.

**Comment by wlhlm** [comment]
Thanks for taking a look at my issue!

> For the tin item pipes, try using a wrench with a better material because wrenches also have levels like mining levels for pickaxes.

Yeah, it works now after crafting a Steel Wrench (level 3), I was trying to use a Wrought Iron Wrench before.

**Comment by DietmarKracht** [comment]
Why would you need a better wrench to dismantle tin pipes but can use an iron wrench on bronze pipes?

**Comment by wlhlm** [comment]
@DietmarKracht See #5482
