### ISSUE TITLE
Motor wire material changes

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#565]
16x copper wire for IV is just silly

LV/MV - Copper 1x/4x
HV/EV - Silver 2x/4x
IV/LuV - Electrum or Gold - 2x/4x
ZPM - Nq 2x
UV - Osmium 2x

Maybe a bit expensive, 1x/2x would be reasonable per tier instead of 2x/4x

Edit: This gives a lot more use for secondary materials which is a good thing.

**Comment by Technus** [comment]
Assigning Dream since he knows how to change greg code for that (experience with large cells)

**Comment by Technus** [comment]
Would require checking if dissasembler recipes for machines using them will auto adjust.
Afaik, it should be possible to add new recipes that would not make you get different/more metals from reverse processing motors. (the motor already does not stack when you use different materials to make it)

**Comment by Technus** [comment]
Still there might be issue when making a machine block out of the engine - it seems to forget what was used since the machines stack. ( need to be tested)

**Comment by Dream-Master** [comment]
Recipe changed:

https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/86507b6da1afe25e7bb8b2ba27ae09fd91d0a855

https://github.com/GTNewHorizons/GT5-Unofficial/commit/0a5ea5afae4e47d8ac9cd413b9a039c8971149e9

**Comment by mrgreenacid** [comment]
Thanks for helping with the idea @Technus :).

No more crazy copper requirements later.
