### ISSUE TITLE
New fresh Russian server: Zvezdolet

### ISSUE THREAD

**Issue by Askara** [GTNewHorizons/NewHorizons#5650]
Hi, 

The issue about adding another Russian server to list: 
1) IP: gtnh.114-7.com
2) Whitelisted
3) Online-mode=true
4) Version 2.0.8.3
My specs are: Hetzner hosting in Finland, i9-9900K, 1 Tb SSD in Raid, 64 Gb Ram
Server is fresh opened and have only 2 players right now. I want to give players a new good server to fresh game.

Thanks

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/75588960-f8353280-5a79-11ea-8ca0-bcd85d266d06.png)

**Comment by Askara** [comment]
Awesome, Thanks
