### ISSUE TITLE
Please rebalance Bartworks ore centrifuging

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5651]
#### Which modpack version are you using?
2.0.8.5dev

the current state of processing bartworks ore is very strange. Just compare the following two:

Centrifuging Impure Pile of Platinum Metallic Powder Dust: 0.05s, 5EU
Centrifuging Impure Pile of Djurleite Dust: 986s, 98600EU

Djurleite is just copper and sulfur, so really low tier stuff, while platinum is important high tier stuff. Still Djurleite takes 20000x as long?? One would think this is a bug or something got mixed up when these numbers were put in the code, but similar comparisons also apply for the rest of the ores.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea or is this intended ?

**Comment by bartimaeusnek** [comment]
fixed
