### ISSUE TITLE
Battlegear merge request

### ISSUE THREAD

**Issue by seitenca** [GTNewHorizons/NewHorizons#5653]
I made it specially thinking in this modpack
https://www.curseforge.com/minecraft/mc-mods/battlegear2-unofficial

I can do whatever you want, just say me what to do.

**Comment by Dream-Master** [comment]
Sounds interresting but we need to check if it works in GTNH.
@seitenca We made allready changes on top on the official version so it need to be merged together if possible.

**Comment by seitenca** [comment]
Ok so how we are going to merged together, you will upload mi changes to the GTNH Battlegear page?
here is the code: https://github.com/seitenca/Battlegear2-Unofficial

**Comment by Dream-Master** [comment]
@seitenca you are on Discord?
https://discord.gg/EXshrPV

**Comment by richardhendricks** [comment]
I'll do a comparison tonight and see if we can merge.  Thanks for your work!

What I would like is a ice-based arrow of some kind. We need to make it pretty expensive (vanilla arrow + bunch of packed ice or something), so the Twilight Forest Ice bow is still worthwhile. A custom DamageSource called "frost" would work. Once it's in, I can add it as an effective damage source against Blazes in Special Mobs. 

You can see an example of how to create a custom DamageSource here https://github.com/GTNewHorizons/SpecialMobs/blob/master/src/main/java/toast/specialMobs/EventHandler.java#L182 Just call super with the name, and set func_151519_b to return the death message.

**Comment by seitenca** [comment]
> @seitenca you are on Discord?
> https://discord.gg/EXshrPV

Yes AIex#3425

**Comment by seitenca** [comment]
> I'll do a comparison tonight and see if we can merge. Thanks for your work!
> 
> What I would like is a ice-based arrow of some kind. We need to make it pretty expensive (vanilla arrow + bunch of packed ice or something), so the Twilight Forest Ice bow is still worthwhile. A custom DamageSource called "frost" would work. Once it's in, I can add it as an effective damage source against Blazes in Special Mobs.
> 
> You can see an example of how to create a custom DamageSource here https://github.com/GTNewHorizons/SpecialMobs/blob/master/src/main/java/toast/specialMobs/EventHandler.java#L182 Just call super with the name, and set func_151519_b to return the death message.

Sounds good I will try it

**Comment by mitchej123** [comment]
Not a fan of the entire commit history being squashed. Can take a diff and apply it to our fork as a separate commit.

**Comment by seitenca** [comment]
How do I have to do it?
git clone https://github.com/GTNewHorizons/Battlegear2.git
git add .
git commit ""
git pull origin master:1.7.10
or
git clone https://github.com/GTNewHorizons/Battlegear2.git
git remote remove origin
git remote add origin https://github.com/seitenca/Battlegear2-Unofficial
git add .
git commit ""
git push origin master:1.7.10

**Comment by mitchej123** [comment]
Will take a look

**Comment by seitenca** [comment]
@Dream-Master If I make more changes, I need to do another pull request?

**Comment by Dream-Master** [comment]
@seitenca yes please
