### ISSUE TITLE
IC2 seedbags dupe

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/NewHorizons#5657]
#### Which modpack version are you using?
2.0.8.3
#

#### What did you try to do, and what did you expect to happen?
Using robot to plant seedbags on cropsticks, with seedbag equipped as handitem and writing use()
#
#### What happened instead? (Attach screenshots if needed)
Insted, plants appear on the cropsticks and remain in the robot inventory
![2020-02-27_19 21 17](https://user-images.githubusercontent.com/29033773/75463239-94860900-5996-11ea-9615-c45dea85546b.png)
![2020-02-27_19 21 36](https://user-images.githubusercontent.com/29033773/75463259-99e35380-5996-11ea-8c00-067e2df92c5b.png)

**Comment by repo-alt** [comment]
For future reference: it turns out that robot.place() correctly handles the seeds, so legit user may use that instead of robot.use().

**Comment by mitchej123** [comment]
Fixed with https://github.com/mitchej123/Hodgepodge/pull/1 - v1.2.0
