### ISSUE TITLE
The papermaking became too easy because of the paperbark wood in Pam's mod

### ISSUE THREAD

**Issue by a-k-ol** [GTNewHorizons/NewHorizons#5658]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I expected to use more difficult recipes to make paper, but then I noticed the recipe of Paperbark Sapling was available. It means we can use bone meal to grow paper simply, while the bone meal is everywhere.
#
#### What happened instead? (Attach screenshots if needed)
![2020-02-28_17 34 05](https://user-images.githubusercontent.com/61580870/75536842-e4290b00-5a50-11ea-95c7-a69966434b6a.png)
The paperbark wood. If you use bone meal to right-click on it, it will drop paper.
![20200228173443](https://user-images.githubusercontent.com/61580870/75536996-294d3d00-5a51-11ea-957c-e1b4b19105a2.png)
The recipe of the sapling.
#
#### What do you suggest instead/what changes do you propose?
Use more complicated recipe instead, or just ban it.

**Comment by richardhendricks** [comment]
I am OK with leaving it in myself.  What I want to do though is make them show up in the wild instead of only via this recipe.

**Comment by Prometheus0000** [comment]
There's also the IC2 papyrus crop that drops paper. That's easy to farm (but takes more effort to get), is this? if you have to right click to get paper, it'd be a pain to get a lot of it. Maybe change the recipe to use a paper stack? Or push it back a tier or two?

**Comment by Dream-Master** [comment]
Will look what i can change here. But harvestcraft get a overhaul later.

**Comment by Ngar1** [comment]
1. you need first a paper to make it
2. It takes time to collect 
3. from lv this trees are inefficent, because of easier and faster ways
  
If this is "cheeting", than also loots in chests and loot bags should be banned.

**Comment by mitchej123** [comment]
Early game doesn't need much nerfing, and this is really only viable early game.  If it had an large impact later game I would be down with adjusting it

**Comment by Dream-Master** [comment]
All other trees are created the same way.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/75588326-b48df900-5a78-11ea-8d0f-43e6bf955cef.png)
![image](https://user-images.githubusercontent.com/2970688/75588340-b952ad00-5a78-11ea-80c2-b86f382d8a9c.png)
![image](https://user-images.githubusercontent.com/2970688/75588349-beaff780-5a78-11ea-9969-da549e56bbd1.png)
