### ISSUE TITLE
Would like to join the server

### ISSUE THREAD

**Issue by Drehverschluss** [GTNewHorizons/NewHorizons#566]
Hello there.

I know its maby the wrong place but you sai we shall just write a msg here if we want to join.

So here i am :)

MFG

**Comment by Dream-Master** [comment]
np can add you

**Comment by Dream-Master** [comment]
MC Name please

**Comment by Drehverschluss** [comment]
same name as here

**Comment by Drehverschluss** [comment]
and where to download the pack?

**Comment by Dream-Master** [comment]
On Technic Launcher

Google it  "MCNewHorizons - Technic Platform"

Using Technic Launcher add the pack and launch.

You whiteledted. I am off for today but the Player Tec_SG can add you as a builder

code is "manuadd Drehverschluss Builder" without the qotes. He has admin right on the server.

**Comment by Drehverschluss** [comment]
on my way :)

**Comment by Dream-Master** [comment]
will see you tomorrow.
