### ISSUE TITLE
Ore Drilling Plant work just in one chunk

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#5660]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
DeepDark-World: 
place a ore driling plant and also reactivate a drilling plant from 2.0.7.5. Placed chunkloader (personal anchor) to get 27 aktiv chunks.
#
#### What happened instead? (Attach screenshots if needed)
Drilling just in the chunk of ore drilling plant
#
#### What do you suggest instead/what changes do you propose?
Drilling in all aktive chunks

**Comment by Ngar1** [comment]
https://github.com/alkcorp/GTplusplus/issues/646#issue-572763211

**Comment by botn365** [comment]
how the ore drilling plant work has been chanced
it now chunckloads it self (can be turned off) and it fist does the chunk it is on and then gose to one of the corners chuncks and start driling there chunck for chunck

**Comment by repo-alt** [comment]
_Quote from discord pinned messages:_
Ore Drilling plant (multiblock miner) now by default works chunk by chunk.
Central chunk is dug as usual.
After the drill reaches bedrock/void it starts digging other chunks one by one.
(It does not retract pipes until all the chunks are processed.)
Ores within those chunks are picked bottom-up
The chunks to drill after the first are selected starting from the lowest X/Z corner accessible
The purpose of this change is to enable chunkloading a single chunk with a miner itself
Then the miner loads working chunks as needed one by one
Radius change (with a scredriver) is taken into account.
Chunkloading behaviour is turned off/on with soldering iron
That info will be in a quest some day

**Comment by Ngar1** [comment]
but this doesen´t work: 
As power was empty and refilled, ore drill doesn´t start again with soft hammer

**Comment by repo-alt** [comment]
Need exact steps to reproduce.

**Comment by Ngar1** [comment]
After build up it works and after some hours the
Energy source (Naquadra Reaktor (ZPM)) was empty - seen by: no more ores were drilled.
Than I refilled Naquadria bolds and the plant doesnt start them selfe. Than I slam the mashine with soft hammer, but only a short time on (ca 1s), than again off. With ore scanner I see, that just one chunk was drilled.

**Comment by Ngar1** [comment]
Sorry - after a waiting time the dill starts themselfe - sorry!

**Comment by repo-alt** [comment]
It must have been rescanning the mining column after restart.
