### ISSUE TITLE
EV tier lootbag can't be enchanted with fortune III

### ISSUE THREAD

**Issue by gordominossi** [GTNewHorizons/NewHorizons#5661]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to enchant an EV lootbag with a lapotron crystal. Expected to get an enchanted lootbag
#
#### What happened instead? (Attach screenshots if needed)
It didn't craft
#

**Comment by Dream-Master** [comment]
@gordominossi did it need a charged or empty one ?
