### ISSUE TITLE
quest id:1405 Superconductors 512 eu/t HV Fluid pump issue

### ISSUE THREAD

**Issue by quedral** [GTNewHorizons/NewHorizons#5662]
#### Which modpack version are you using?
20.8.3
#
#### If in multiplayer; On which server does this happen? 
private mp
#
#### What did you try to do, and what did you expect to happen?
Electric pump (HV) cannot be detected by the quest. probably nbt issue.

**Comment by quedral** [comment]
putting fluid pumps through Name Remover solves the issue.

**Comment by Prometheus0000** [comment]
IgnoreNBT is already on, are you really sure that's the problem? Dunno what else I can do?

**Comment by Dream-Master** [comment]
2.0.8.3 is very old allready @Prometheus0000 
i would say this is fixed allready.
