### ISSUE TITLE
Raw Walleye cannot be processed into mince meat

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/NewHorizons#5667]
#### Which modpack version are you using?
2.0.8.3
#
Not totally sure what went wrong here but it's probably rather simple to fix, for some reason all the raw fish have recipes to grind them into mince meat except from the raw walleye.

**Comment by wlhlm** [comment]
Appears to be fixed in 2.0.8.5:
![2020-03-03_12 50 49](https://user-images.githubusercontent.com/1928113/75773204-b6dca580-5d4d-11ea-9172-5119af0067eb.png)

This [change](https://github.com/GTNewHorizons/NewHorizons/commit/2a78661b98144938eb83cb726c3a76f61249011a) was merged more than a year ago. Not sure why it's not working for you.

**Comment by GTNH-Colen** [comment]
There isn't a macerator recipe though, at least in 2.0.8.3 unlike the rest of the fish. Noticed it because I was creating mince meat with the zhuhai fishing port but this fish was clogging up my system as it wouldn't input into the macerator.

**Comment by Dream-Master** [comment]
Maybe this fish have no oredict tag ?

**Comment by richardhendricks** [comment]
So would you say it's walling you off?

ok ok, ouch ouch stop throwing things, I'll see myself out.

:)

**Comment by Connor-Colenso** [comment]
I did think of that but it appears to have the same ore dict tag so not sure what’s going wrong here

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/76170560-51d8e380-6183-11ea-8507-d8021da4bd26.png)
fixed

**Comment by wlhlm** [comment]
You show the crafting recipe, but that was already working as my [screenshot](https://github.com/GTNewHorizons/NewHorizons/issues/5667#issuecomment-593913404) above shows. Did you check the macerator?

**Comment by Dream-Master** [comment]
not yet will do

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/76170786-86e63580-6185-11ea-9164-01dd6f45e57c.png)
