### ISSUE TITLE
Desh GT vein

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#567]
Primary Layer - Desh
Secondary Layer - Desh
Sporadically in between - Scheelite
Sprodically Around - Tungstate
```

                I:OrePrimaryLayer_=884
                I:OreSecondaryLayer_=884
                I:OreSporadiclyInbetween_=910
                I:OreSporaticlyAround_=841

```

Contains trace amounts of Tungsten but mostly desh.

**Comment by Dream-Master** [comment]
Yea ok will add it.
