### ISSUE TITLE
Question: Phobos bee flower type

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/NewHorizons#5674]
#### Which modpack version are you using?
8.3.
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Analyse Phobos bee -> unexpected flower type of unknown kind
#
#### Questions
- intentional or incomplet type definition? (Absicht oder unfertig?)
- what type is this? -> normal Minecraft flowers, I expect
![Bee_Phobos_Flowertype](https://user-images.githubusercontent.com/7759876/75702977-daa0dc80-5cb6-11ea-941d-0fdf35cc1d61.JPG)

**Comment by Ngar1** [comment]
![Bee_Phobos_Flowertype2](https://user-images.githubusercontent.com/7759876/75703440-c7dad780-5cb7-11ea-85f9-8fdf7a87503e.JPG)

**Comment by Dream-Master** [comment]
will check

**Comment by Ngar1** [comment]
Pollination seems to be wrong, or?

**Comment by Dream-Master** [comment]
tMutation.requireResource(GameRegistry.findBlock("GalaxySpace", "phobosblocks"), 2);

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/76164074-30103a00-614c-11ea-957b-e6fcccdb4209.png)

**Comment by Dream-Master** [comment]
PLANET("Planetaris") {
        @Override
        protected void setBranchProperties(IAllele[] alleles) {
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.TEMPERATURE_TOLERANCE, EnumAllele.Tolerance.BOTH_1);
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.TOLERANT_FLYER, true);
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.FLOWER_PROVIDER, getFlowers(EXTRABEES, "rock"));
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.FLOWERING, GT_Bees.superFlowering);
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.LIFESPAN, EnumAllele.Lifespan.NORMAL);
            AlleleHelper.instance.set(alleles, EnumBeeChromosome.SPEED, EnumAllele.Speed.FASTEST);

**Comment by Dream-Master** [comment]
They need rocks as flowers
``AlleleHelper.instance.set(alleles, EnumBeeChromosome.FLOWER_PROVIDER, getFlowers(EXTRABEES, "rock"));``
