### ISSUE TITLE
Get rid of the Life Infuser

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5675]
#### Which modpack version are you using?
2.0.8.5dev
#
Apparently the recipe for infinity armor does not require a _charged_ life imbued armor, so there's no need to keep this buggy POS around.
https://media.discordapp.net/attachments/181078474394566657/683499540891828227/Screenshot_2020-03-01_at_02.23.02.png
And it's still broken:
https://media.discordapp.net/attachments/181078474394566657/683506550463135747/Screenshot_2020-03-01_at_02.50.49.png?width=1123&height=702

Just adding infinity to the recipe does not change the brokenness of it. If someone fixes it that's fine, but _right_ _now_ it is not. And changing the recipe for that would be easier than fixing the LI too.
See also #3953
#
#### What do you suggest instead/what changes do you propose?
Remove the Life Imbuer, until someone fixes it. Maybe make it only work on the armor set?

**Comment by Dream-Master** [comment]
Or we make it super expensive so long it isnt fixed.

**Comment by Ethryan** [comment]
My vote is axe it, if you really need a repairer, thaumic restorer works.

Unlimited ZPM's is NOT intended.

**Comment by Dream-Master** [comment]
better fix it. Repair items not dupe it.

**Comment by Ethryan** [comment]
https://github.com/GTNewHorizons/BloodArsenal/blob/2f53bdbe5c59c063a13aa3cf9006caf12b600c74/src/main/java/com/arc/bloodarsenal/common/tileentity/TileLifeInfuser.java#L257

seems to be the line that heals items...

No clue on how to fix though.

**Comment by Prometheus0000** [comment]
Supposedly in the previous issue GT stuff was blacklisted...but I can't find any sign of that. There's no blacklist config, nor any commit to changing the code that seems to relate either? If no one can figure out how to fix it, making it whitelisted or only work on the LI Armor would be good too. Just making it expensive is a bandaid solution that doesn't fix anything, just makes it take longer until you can abuse it. If you _have_ to keep it around, how about the Stargate Base instead of the Infinity Large Plate?

**Comment by mitchej123** [comment]
If it's open source let's just add a whitelist to known items that work.

**Comment by Anarack** [comment]
Yes to that considering how easy it is to brick you character with the thing.

**Comment by GTNH-Colen** [comment]
Glad someone is putting the testing I did the other day to good use ;). I recall someone saying there was already a blacklist for all GT items but if that is the case it clearly isn't working properly as you can see from the screenshots.

This item has caused so many headaches and issues, it's an extremely niche thing so I don't think we'd be losing much by getting rid of it entirely. It honestly looks so poorly thought through, it even breaks vanilla minecraft logic (Can transmute potions into other types).

**Comment by Prometheus0000** [comment]
@Anarack, you're the one that said GT items were blacklisted, where were you getting that from? Also, we have it forked already (where I looked through the commits), so anyone who has the desire to (and capability to) can add a whitelist. Does it brick worlds if you only use it on appropriate stuff though? If it's bricking things when you use it normally, that would be an even better reason to get rid of it.

**Comment by Anarack** [comment]
I think its ok on the things its supposed to be used on, or at a min I've never tried screwing around with it and the life armor thing. A black list/whitelist was discussed at some point iirr, but that was a while ago, or I just missread it then. and I guess I assumed someone did it but that was apparently a no.

**Comment by Dream-Master** [comment]
fixed with http://jenkins.usrv.eu:8080/job/BloodArsenal/8/
