### ISSUE TITLE
BW Circuit Programmer doesn't work with Programmed Bio Circuits (GT++)

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5676]
#### Which modpack version are you using?
2.0.8.5dev
#
#### What did you try to do, and what did you expect to happen?
Put circuit in programmer, click a button, changed circuit.
#
#### What happened instead? (Attach screenshots if needed)
Won't even go in the device.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by bartimaeusnek** [comment]
No. Im fed up with breaking changes in GT++.
