### ISSUE TITLE
Hydrogen sulfide in the LCR has a conflicting recipe

### ISSUE THREAD

**Issue by NG-ChE** [GTNewHorizons/NewHorizons#5677]
#### Which modpack version are you using?
2.0.8.4
#
#### What did you try to do, and what did you expect to happen?
Create sulfuric acid and ammonia in the same LCR.
#
#### What happened instead? (Attach screenshots if needed)
Produced hydrogen sulfide instead of ammonia.
![2020-03-02_18 19 02](https://user-images.githubusercontent.com/52723686/75727349-c22ec300-5cb2-11ea-9b00-b5c065985d50.png)
![2020-03-02_18 19 12](https://user-images.githubusercontent.com/52723686/75727385-d2df3900-5cb2-11ea-99a9-12fee263a13f.png)
#
#### What do you suggest instead/what changes do you propose?
Hydrogen sulfide has two recipes of the same amount with hydrogen and sulfur. The one with the circuit used to be the only way to produce it with those components, if I remember correctly.

**Comment by 0lafe** [comment]
You can limit your S input based on H2S fill level, or not input all the recipes you're using the LCR for at once. It can't do parallels of different recipes so having all inputs doesn't help anything

**Comment by Dream-Master** [comment]
i remove this recipe withot a circuit from LCR.
