### ISSUE TITLE
Oil well apocalypse 

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#568]
http://i.imgur.com/bzDWE6k.jpg
http://i.imgur.com/hTEapHq.png

Not sure if this is only happening with vanilla generation, need to test more. Maybe something to do with https://github.com/GTNewHorizons/NewHorizons/issues/557

Steps to reproduce
Create SSP world
Go to desert

**Comment by Dream-Master** [comment]
sure when you not set the level typ to rwg you get too much oil but if i generating new chuncks i not get any oil well. With this config i get al 200-400 Block one oil well. Go and check it with some rwg world.

**Comment by Dream-Master** [comment]
I set it to 20 wich is a good amount for the server. it is only for RWG when you play with BoP you have to lower it to 1-4.

**Comment by mrgreenacid** [comment]
Poor person who tries vanilla generation with this pack, maybe make release config be 1-4, not 20.

**Comment by Dream-Master** [comment]
sure
