### ISSUE TITLE
Microblocks

### ISSUE THREAD

**Issue by Tedtricks** [GTNewHorizons/NewHorizons#5682]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Singleplayer, but can be applied to every server
#
#### What did you try to do, and what did you expect to happen?
I added "minecraft:double_stone_slab":0-8 in the microblocks.cfg file, but apparently it doesn't read it 
#
#### What happened instead? (Attach screenshots if needed)
Nothing
#
#### What do you suggest instead/what changes do you propose?
Add it to the pack :P

**Comment by mitchej123** [comment]
Not really sure what the ask here is?

**Comment by Tedtricks** [comment]
I want to be able to craft double_stone_slab microblocks, that’s all
