### ISSUE TITLE
Basalt GT covers

### ISSUE THREAD

**Issue by Tedtricks** [GTNewHorizons/NewHorizons#5683]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Singleplayer, but applies to every server
#
#### What did you try to do, and what did you expect to happen?
Crafting a Smooth Basalt cover for GT wires, but it hasn't a recipe, while Granite does.
#
#### What happened instead? (Attach screenshots if needed)
Nothing
#
#### What do you suggest instead/what changes do you propose?
Add a config file where you could add new materials to make plates of / Adding the cover I request :P

**Comment by boubou19** [comment]
see #4185

**Comment by Tedtricks** [comment]
Why is it closed as bug minor though?

**Comment by boubou19** [comment]
because at the time, no one knew how to implement it and it was closed because it was considered as an old issue

**Comment by boubou19** [comment]
@Dream-Master can you also add the marble plate pls?

**Comment by leagris** [comment]
Also missing weathered concrete, red granite and black granite.
Also missing variants of all GT stones...
Also missing wood plank covers of upper forestry wood IDs.

I have mentioned a possible enhancement by implementing a printable GT cover.
How it could work:
1. Craft a polyethylene plastic foil as a blank cover
2. Insert arbitrary block into the GT Scanner to record the model into a memory stick
3. Insert memory stick, ink, blank cover into the GT Printer
4. Get a plastic cover printed with the texture of the scanned block.
5. Use this printed plastic cover to make any side of a GT machine block look like the scanned block.

Alternative to steps 2 to 4:
Use the IC2 Obscurator device over a placed blank plastic cover and get the texture printed onto it in-world as it works with IC2 Construction Foam blocks.
