### ISSUE TITLE
The quest 'Some high tier metals' in HV wants the wrong items

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5684]
#### Which modpack version are you using?
2.0.8.5dev
#
With the platinum changes, the items on the last page are wrong, it should be:
Silicon Dioxide Dust
Gold Dust
Platinum Metallic Powder Dustx2
Tiny Pile of Palladium Metallic Powder Dustx6
Tiny Pile of Iridium Metal Residue Dustx3
Tiny Pile of Rarest Metal Residue Dustx3
With the above multiplied 14x, since you get that much from each of the 14 Platinum Group Sludge Dust you made. Also, it would be nice if the quest mentioned where in the platinum processing line you use each of the dusts.
#
#### What do you suggest instead/what changes do you propose?
See above

**Comment by chochem** [comment]
Duplicate of #5360

**Comment by Prometheus0000** [comment]
Didn't see it when I looked.
