### ISSUE TITLE
BM Weak Activation Crystal can't be made at the tier it should be

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5685]
#### Which modpack version are you using?
2.0.8.5dev
#
The Weak Activation Crystal needed to activate BM rituals can't be made at the tier it should be. It is a BM T3 item, but the Lapotron Crystal needed to make it is an EV Assember recipe, while the orb for BM T3 is HV, indicating that it shouldn't use EV items at this tier.
#
#### What do you suggest instead/what changes do you propose?
Change the recipe for the Unbound Crystal (used to make the WAC) to use a Raw Lapotron Crystal or an Energy Crystal.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/76152459-3e187900-60c0-11ea-84f7-0862cc1fdb4c.png)
