### ISSUE TITLE
RND Chrash NEI

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#5687]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Privet sever
#
#### What did you try to do, and what did you expect to happen?
stand still and checked crops
#
#### What happened instead? (Attach screenshots if needed)
https://pastebin.com/nmkuwmbk
#

**Comment by mitchej123** [comment]
Upgrade your NEI to the latest version, this has already been fixed.
