### ISSUE TITLE
BQ quest "Automated evolution" (#391) not consume item

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#5688]
#### Which modpack version are you using?
2084
#
#### If in multiplayer; On which server does this happen? 
priv serv
#
#### What did you try to do, and what did you expect to happen?
For complete quest u need 2 thaumium golem...
In quest the golem has a tag "tag:10": {"gadomancy:10": {}},
```
"2:10": {
              "id:8": "Thaumcraft:ItemGolemPlacer",
              "Count:3": 2,
              "tag:10": {
                "gadomancy:10": {}
              },
              "Damage:2": 7,
              "OreDict:8": ""
            },    
```  
#### What do you suggest instead/what changes do you propose?
 remove tag in quest

P.S. ![image](https://i.imgur.com/uR11B3U.png)
1)crafting golem does not have tag
2)if you take the golem from the creative, u have this tag

**Comment by Prometheus0000** [comment]
The golem I made in a thaumatorium worked just fine? And when I tried to replace the existing one in the quest it said there were no changes when I compared files? Did you use them for something first? They may have gotten additional NBT data from that.

**Comment by Prometheus0000** [comment]
It seems that making a copy of a golem in creative changes the tags of both the new and old one. You can see in #5600 how they had tags added probably because of this. I'll turn ignoreNBT on.
