### ISSUE TITLE
Extra Trees fences are buggy

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/NewHorizons#5694]
#### Which modpack version are you using?

2.0.8.5

#### If in multiplayer; On which server does this happen? 

Singleplayer

#### What did you try to do, and what did you expect to happen?

1. Craft spruce wooden fences
2. Connect spruce fence gate to spruce fence

#### What happened instead? (Attach screenshots if needed)

1. The game at some point forgets about the spruce fence recipe and instead gives oak fences when crafting. (It works after restarting the game, but gets lost after some point, don't know what's causing it)
![2020-03-05_10 47 33](https://user-images.githubusercontent.com/1928113/75969924-ee735b00-5ecf-11ea-98fb-33f604f7bf2a.png)

2. ~~Spruce fence only connects to vanilla oak fence gate.~~ *Fixed*
![2020-03-04_01 03 09](https://user-images.githubusercontent.com/1928113/75969939-f3d0a580-5ecf-11ea-9ad6-bfb3838feb58.png)

3. Extra Trees fences show up in WAILA as "Oak Fence" (pretty minor issue, really)

**Comment by leagris** [comment]
Affect also regular fences:

![](https://i.imgur.com/crEU7Hh.png)

**Comment by mitchej123** [comment]
Addressed with https://github.com/GTNewHorizons/Hodgepodge/releases/tag/v1.3.0

**Comment by wlhlm** [comment]
Point 2 is fixed now!
![2020-03-08_22 38 04](https://user-images.githubusercontent.com/1928113/76171666-024be500-618e-11ea-8406-f52fe6d7ce11.png)

Thanks @leagris and @mitchej123! 🎉 

Points 1 and 3 remain though. The game still forgets about the crafting recipe after some point. I don't know how to exactly reproduce it, but after playing some time, the crafting recipe for the spruce fence just returns the vanilla fence. Also, all Extra Trees fences still show up as "Oak Fence" in WAILA.

**Comment by wlhlm** [comment]
I'm reopening this since only part of the problems reported in this issue have been fixed. I'm currently looking into the WAILA bug.

**Comment by Dream-Master** [comment]
ok

**Comment by mitchej123** [comment]
#1 -- need a way to reproduce this or track it down.  It's a big too vague right now
#3 -- Minor visual bug, if someone wants to tackle it go for it, but I won't have cycles for a while to look at it

**Comment by wlhlm** [comment]
I already, said, I'm working on #3. This is not urgent, thus I've removed it from the milestones.
