### ISSUE TITLE
Quest 1412: Assembly Line NBT issues

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5696]
#### Which modpack version are you using?
2.0.8.5dev
#

Quest 1412 (Assembly Line) does not recognize the assembly line (controller). It only works after running it through the name remover.

**Comment by Prometheus0000** [comment]
See #5451, also #5693

**Comment by chochem** [comment]
thanks. I did search, but only say an old, closed issue  :P

**Comment by Dream-Master** [comment]
I close this after release @chochem

**Comment by chochem** [comment]
I only closed it because it was a duplicate.
