### ISSUE TITLE
Tanned Leather not craftable in the Chemical Dehydrator

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/NewHorizons#5697]
#### Which modpack version are you using?
2.8.0.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
The questbook said that drying rack recipes were able to be done in the dehydrator, so I assumed that tanned leather was craftable.
#
#### What happened instead? (Attach screenshots if needed)
No such recipe was found
#
#### What do you suggest instead/what changes do you propose?
Add a reasonable recipe for making tanned leather with the dehydrator. Waiting 6 minutes seems kind of unecessary post-steam age and it seems that the intention of the packmaker was to make the dehydrator work as a replacement, but I'm open to being wrong about that.

**Comment by Dream-Master** [comment]
Dehydrator is a GT++ device.

I add it to Chemical Bath for now.
