### ISSUE TITLE
Creative stuff recipes

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#570]
> OPENCOMPUTERS:
- Creative stuff have the advantage of:
  More stuff inside
  Infinite power
- Server (Creative)
  
  ```
  High Energy Flow Circuit, Data Control Circuit, High Energy Flow Circuit
  Data Control Circuit, Computer Case (Tier 3), Data Control Circuit
  Screwdriver, Quantum Processor Board, Wrench
  ```
- Accelerated Processing Unit (APU) (Creative)
  
  ```
  Quantum Processor Board, High Energy Flow Circuit,Quantum Processor Board
  Accelerated Processing Unit (APU) (Tier 2), Data Control Circuit, Graphics Card (tier 3)
  Quantum Processor Board, High Energy Flow Circuit,Quantum Processor Board
  ```
- Tablet Case (Creative)
  
  ```
  Data Control Circuit, Dense Chrome Plate , Pellets of RTG Fuel
  High Energy Flow Circuit, Screen (Tier 3), Radioisotope Thermoelectric Generator
  Data Control Circuit, Quantum Processor Board, Pellets of RTG Fuel
  ```
- Microcontroller Case (Creative)
  
  ```
  16x Electrum Wire, Data Control Circuit, 16x Electrum Wire
  Quantum Processor Board, Obsidian Chest, Quantum Processor Board
  Pellets of RTG Fuel, Radioisotope Thermoelectric Generator, Pellets of RTG Fuel
  ```
- Drone Case (Creative)
  
  ```
  Chrome Turbine Blade, Biome Compass, Chrome Turbine Blade
  Data Control Circuit, Microcontroller Case (Creative), Data Control Circuit
  Chrome Turbine Blade, Quantum Processor Board, Chrome Turbine Blade
  ```

> Steve's Carts 2
- Creative Hull (More SPACE)
  
  ```
  Assembler LuV 30kEU/t 20s: Galgadorian Hull, Quantum Chest V
  ```
- Upgrade: Creative Mode (Instant and non energy using cart assembler upgrade)
  
  ```
  Enhanced Galgadorian Plate, Dense Naquadria Plate, Enhanced Galgadorian Plate
  Enhanced Galgadorian Plate, Naquadah reactor Mark III, Enhanced Galgadorian Plate
  Enhanced Galgadorian Plate, Upgrade: New Era, Enhanced Galgadorian Plate
  ```

> ProjectRed Fabrication
- Creative Mode IC Chip 
  (Free Redstone circuitry, they can only be used for redstone purposes or recycler ;] )
  
  ```
  Nano Circuit, Nano Circuit, Nano Circuit
  Quantum Circuit, High Energy Flow Circuit, Quantum Circuit
  Piko Circuit, Piko Circuit, Piko Circuit
  ```

> Applied Energistics  2
- Creative Energy Cell (Free AE power)
  
  ```
  Fusion Casing MK II, Naquadah reactor Mark III, Fusion Casing MK II
  Fusion Casing MK II, Fusion Control Computer Mark III, Fusion Casing MK II
  Fusion Casing MK II, Iron Plasma Cell, Fusion Casing MK II
  ```

**Comment by Dream-Master** [comment]
Creative Energy Cell (AE2)exists allready via Avaritia.
If we add those recipe it will be avaritia recipe only.

**Comment by Dream-Master** [comment]
Maybe adding the Admin Dislocator from Daconic Evolution to the Avaritia Table too

**Comment by Technus** [comment]
Changing stuff.

Open computers - Creative Case cannot be opened by Non creative player.

**Comment by SanMan911** [comment]
Maybe we could make it so that questing system, late in the game would drop certain sleek-looking nifty item, which would have to be used to make a particular creative item...
This would ensure that some players do not become too ridiculously op, and even despite having economy system, no one would like o sell their hard earned quest item to anyone else.
It'd really incentivize doing quests, and should the demand arise at a further date, the quest for dropping the particular items could even be made repeatable, even if with a huge cool down...
What say?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22384076/ff7f1914-e4cc-11e6-8f1b-8559b7411e13.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22384513/0381d798-e4cf-11e6-9193-218af9863a49.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22385175/ee000018-e4d1-11e6-969c-c0d0fc6b44db.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22386965/b0d312ea-e4d9-11e6-92c6-2eba44d885bc.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22387266/0e6f8a22-e4db-11e6-99c1-8c91d11c1fb7.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22387371/8b66ca86-e4db-11e6-926b-eaba2220366f.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/22387950/572fed26-e4de-11e6-9891-44f9b74d6e7b.png)
