### ISSUE TITLE
Mushroom Block With Chisel Support

### ISSUE THREAD

**Issue by itsmekasta** [GTNewHorizons/NewHorizons#5701]
Hey, I would like to craft the Ztones Myst blocks.

is there any way to get the vanilla mushrooms **99** other than bees?

It looks like even when I break the same block ID with silk touch on brown mushrooms roof, I get IDs of **99:1** - **99:9** if I do the same with the stem, I get **99:10**.

Maybe we could add the mushroom blocks to Chisel to get ID 99, because I'm not sure, if this is intended. :)

[Album](https://imgur.com/a/1WCn7CV) with the ID's and current situation

**Comment by Dream-Master** [comment]
@leagris is this possible ?

**Comment by leagris** [comment]
Sound like it is. Ill have to test
