### ISSUE TITLE
Flint sword dosnt been detected by quest #11

### ISSUE THREAD

**Issue by yuval380** [GTNewHorizons/NewHorizons#5702]
Modpack Version: 2.0.8.3

Started a new Singleplayer world.
Quest 11 don't detect the flint sword I made...

I tried making a new sword, close the world and reopen, restart Minecraft.

Same as #2385

**Comment by chochem** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5384

**Comment by yuval380** [comment]
👍
