### ISSUE TITLE
RFC: Bigger AE interfaces

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/NewHorizons#5707]
There are 2 approaches to the 18+ pattern slot AE interfaces. One is to give all the interfaces 18 slots (already done by @4gname (https://github.com/4gname/Applied-Energistics-2-Unofficial/tree/new-Interface) needs just a bit cleanup). 
Another is to add an upgrade, kind of like "Capacity Card", that would add another 9 pattern slots. The obvious advantage of the first variant is that it may be added today. Second variant requires some time/efforts, and I'm not sure if they are justified.

**Comment by quedral** [comment]
i would pick the easier way since you all do this on your own leissure and nobody gets paid.  nobody will look down on you for this.

**Comment by GeicowithaBango** [comment]
Is there a way to make the ME interface coast more energy-wise when used for crafting, in respect of the „new“ capacity cards?

**Comment by repo-alt** [comment]
> Is there a way to make the ME interface coast more energy-wise when used for crafting, in respect of the „new“ capacity cards?

Of course with the upgrade there would be a way to use different amount of energy

**Comment by Dream-Master** [comment]
Please add an upgrade @repo-alt

**Comment by mitchej123** [comment]
Upgrade or a separate item

**Comment by Dream-Master** [comment]
i mean a seperate item or maybe more items for different tiers.

**Comment by repo-alt** [comment]
Ok, accepted.

**Comment by mitchej123** [comment]
Honestly an upgrade would also be fine... easier than swapping them out -- do whichever is easier

**Comment by mitchej123** [comment]
Or... do like mekanism does... and have an upgrade you can smack on the in world item to upgrade it

**Comment by repo-alt** [comment]
> Or... do like mekanism does... and have an upgrade you can smack on the in world item to upgrade it

Huh, well, this is a interesting idea by itself, but all the other upgrades work like cards, so I'd probably go this way

**Comment by GTNH-Colen** [comment]
Repo at it again with his game changing AE modifications, it is appreciated bud ;).

**Comment by 0lafe** [comment]
What are you using for the power multiplier on it? And does this also effect the power draw when crafting, or just idle

**Comment by repo-alt** [comment]
When crafting. Interface does not use power when idle.

**Comment by 0lafe** [comment]
What's the use on it when crafting?

**Comment by repo-alt** [comment]
Interface energy usage scales proportionally to the number  of items used in the recipe.
We set power multiplier to 10 and EU/AE conversion to 2 in config, so EU used is by default 5 times the number of items used in the recipe, per craft.
Each upgrade increases energy usage 4 times.

**Comment by 0lafe** [comment]
Nice
