### ISSUE TITLE
Sacrificial dagger triggers anger mod explosions.

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/NewHorizons#5714]
2.0.8.3

This shouldn't happen as it makes blood magic even more annoying.

**Comment by Dream-Master** [comment]
# If the player is using one of these items, entities will not explode if they are killed [default: [flint]]
    S:KamikazeItemBlacklist <
        gt.metatool.01.34
        gt.metatool.01.36
        witchery:canesword
     >

**Comment by Dream-Master** [comment]
# If the player is using one of these items, entities will not explode if they are killed [default: [flint]]
    S:KamikazeItemBlacklist <
        gt.metatool.01.34
        gt.metatool.01.36
        witchery:canesword
		AWWayofTime:daggerOfSacrifice
		BloodArsenal:glass_sacrificial_dagger
		BloodArsenal:glass_dagger_of_sacrifice
     >
