### ISSUE TITLE
Crash when shift-clicking (+ button in NEI) recipe into arcane crafting table 

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NewHorizons#5716]
#### Which modpack version are you using?
2.0.8.5dev
#
#### What did you try to do, and what did you expect to happen?
Shift-click the recipe (angel block, but I think it's happened before with another recipe) into the arcane crafting table (with the + button), puts items into table (this does work most of the time)
#
#### What happened instead? (Attach screenshots if needed)
Shift-click the recipe into the arcane crafting table (with the + button), crash
[crash-2020-03-08_14.10.18-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4303648/crash-2020-03-08_14.10.18-client.txt)

It mentions thaumcraftneiplugin, so that's probably the cause.
This appears to be a different crash from #4633.
#
#### What do you suggest instead/what changes do you propose?
Fix the crash. BTW, I know you sped up other crafting tables, but this one is still super slow when crafting multiple items, if you can do anything about that.

**Comment by TimeConqueror** [comment]
Fixed in TCNEIAdditions1.0.2.2: https://github.com/GTNewHorizons/TCNEIAdditions/releases/tag/1.0.2.2

**Comment by Dream-Master** [comment]
will close after release.
