### ISSUE TITLE
Sprinklers don't work in latest version

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/NewHorizons#5722]
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 
In singleplayer
#
#### What did you try to do, and what did you expect to happen?
I updated to 2.0.8.6 and expected everything to work fine.
#
#### What happened instead? (Attach screenshots if needed)
My sprinklers stopped working in my tree farm. They still spray water particles, but my saplings aren't actually growing any faster than they normally do. 
![2020-03-09_13 07 52](https://user-images.githubusercontent.com/29802757/76238947-0cf69080-6207-11ea-85c9-3fbd6917e9e9.png)
The setup worked fine before I updated to .8.6, and trees still grow, but only at their normal speed.
#
#### What do you suggest instead/what changes do you propose?
I checked the config, this isn't just a config issue; no idea what the actual problem is though.

**Comment by Dream-Master** [comment]
@Bluebine is this a open blocks item ?

**Comment by Bluebine** [comment]
Yeah, the sprinklers are Openblocks

**Comment by Bluebine** [comment]
so this seems to have been a corrupted install or something, it worked fine after I reinstalled the pack
