### ISSUE TITLE
Mudball Bucket Duplication Glitch

### ISSUE THREAD

**Issue by ImVaskel** [GTNewHorizons/NewHorizons#5727]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Modded Minecraft Club
#
#### What did you try to do, and what did you expect to happen?
I was making mud balls for the quest for the armor. I just expected to make some mud balls
#
#### What happened instead? (Attach screenshots if needed)
Instead I made the mud balls and then I had the amount of buckets in my inventory as dirt I used (eg 40 buckets for 40 dirt)
#

**Comment by Dream-Master** [comment]
fixed. Try with 2.0.8.5 or 2.0.8.6
