### ISSUE TITLE
Cannot feed Charcoal, Blocks of Charcoal, or Blocks of Coal Coke RE: Bricked Blast Furnace

### ISSUE THREAD

**Issue by metnavman** [GTNewHorizons/NewHorizons#5728]
Using the most recent version of GT:NH off Technic. Only thing that works is 2 pieces of Coal Coke to cook one Steel Ingot. If intended, NEI recipes are dirty liars.

**Comment by Dream-Master** [comment]
So which item work and which not?

**Comment by Dream-Master** [comment]
make screenshot

**Comment by wlhlm** [comment]
Works for me in 2.0.8.6. Remember that you need enough iron ingots when using blocks of coal, i.e. five iron ingots per block of coal coke IIRC.

**Comment by metnavman** [comment]
I appear to be on 2.0.8.3, from Technic's recommended download. Perhaps that's the issue?

https://imgur.com/a/arSs90G

Screenshots anyways. If I need to be playing the latest version to solve this issue, than there we go.
