### ISSUE TITLE
Blinding speed Bees

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#573]
Change GenDustry bee species: Magenta

```
Speed: Fastest -> Speed: Blinding
(170%)->(200%)
```

Light Gray is also tier 3 color but the beez used to make light grey bee dont have Fastest trait.

**Comment by Dream-Master** [comment]
Not sure if i can touch Gendustry own Bees.

**Comment by Dream-Master** [comment]
lets add those traits to bees i add. We can add for each bee i add own traits.

https://github.com/GTNewHorizons/NewHorizons/blob/master/config/gendustry/bees.cfg

**Comment by Dream-Master** [comment]
@Technus 
I look into foresty Souce code and find this:

	```
public enum Speed implements IAlleleValue<Float> {
		SLOWEST(0.3f, true),
		SLOWER(0.6f, true),
		SLOW(0.8f, true),
		NORMAL(1.0f),
		FAST(1.2f, true),
		FASTER(1.4f),
		FASTEST(1.7f);
```
no blinding speed found. Maybe i can add some but sure if this works.

`		BLINDING(2.0f);`

**Comment by Technus** [comment]
I mutated that bees on SP, tested AF

**Comment by Dream-Master** [comment]
Its maybe added by Gendustry.

**Comment by Technus** [comment]
Still i can test it once more later.

**Comment by Dream-Master** [comment]
No i look into Gendustry code to be sure.

**Comment by Technus** [comment]
If it is in gendustry code there will be no problem

**Comment by Dream-Master** [comment]
I look for keywords cant find any.
Gendustry Bees i can change only via Code or i need to add a new bee species via cfg.
This was your origial suggestion right?

**Comment by Technus** [comment]
Yeah to add that trait to some high tier bee

**Comment by Dream-Master** [comment]
Sure i want to add own individual traits to all bees but this need a lot of time. I am thinking about add this via GT Code because bees are allready implemented. Coding needs more time.

**Comment by Dream-Master** [comment]
removing traits from low tier bees would be more difficault.

**Comment by Dream-Master** [comment]
@Technus If you have an idea how to code it then i reopen it.
