### ISSUE TITLE
bug circuit secondary recipes

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/NewHorizons#5731]
#### Which modpack version are you using?
2086qf
#### If in multiplayer; On which server does this happen? 
privet server :)
#
#### What did you try to do, and what did you expect to happen?
craft circuit in 2083
![image](https://i.imgur.com/MLVwuFP.png)

and craft in 2086
![image](https://i.imgur.com/WXD8PJb.png)

its not fake nei
https://giant.gfycat.com/FragrantSnappyDinosaur.webm
also dont works for [hv](https://i.imgur.com/jZxHyWL.png), [ev](https://i.imgur.com/fYeTUGE.png), [iv](https://i.imgur.com/WXD8PJb.png)

**Comment by 0lafe** [comment]
Isn't that the intended recipe?

**Comment by Bluebine** [comment]
This is intended, to encourage use of the circuit assembly line. Which is intended for all circuit recipes LuV+ IIRC

**Comment by botn365** [comment]
this recipe is intented any circuit that needs LuV+ voltage needs the circuit assembling line to make the circuit at normal price
