### ISSUE TITLE
End steel armor set upgrades + Apiarist suit

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/NewHorizons#5734]
#### Which modpack version are you using?
.8.5dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Tried to combine Apiarist suit with End steel armor which should be possible in same way as in Dark steel armor set
#
#### What happened instead? (Attach screenshots if needed)
Put both into anvil, with proper levels, but nothing happened except of consuming apiarist armor part

![2020-03-11_20 45 31](https://user-images.githubusercontent.com/14223368/76457738-a37aab80-63d9-11ea-87b1-2d1e30c68c40.png)
![Uploading 2020-03-11_20.45.33.png…]()

#
#### What do you suggest instead/what changes do you propose?
Check that recipe/combination

**Comment by Impos913** [comment]
It looks like end steel helmet doesnt have revealing upgrade too.

**Comment by Hyperic88** [comment]
> It looks like end steel helmet doesnt have revealing upgrade too.

yup that too, forgot to mention that , thx

**Comment by Hyperic88** [comment]
Also triple jump and step assist doesn't work

**Comment by Dream-Master** [comment]
@zoko061602 can you check if this can be added too?

**Comment by Dream-Master** [comment]
@Hyperic88 test with this version please https://github.com/GTNewHorizons/EnderIO/releases/tag/2.3.1.0
Whole dev pack is here
http://downloads.gtnewhorizons.com/Dev-Pack/

**Comment by Hyperic88** [comment]
So i did a little testing in SP with updated EIO file and...
Apiarist set is working but there is a mess with tooltip both end steel and dark steel set
Shoes - step assist doesnt work, jump enhancement does, but it doesnt negate fall damage anymore - End steel set
Leggings - not mentioned Speed upgrade (with swiftness potion) but tooltip for already upgraded version says Speed III - both sets Dark and End steel

**Comment by Dream-Master** [comment]
@Zoko061602

**Comment by Hyperic88** [comment]
@Dream-Master Tested in 2.0.8.7QF2 on Zeta and now that End Steel armor works as should, if some new issues come it will be reported again

**Comment by Dream-Master** [comment]
ok cool and thanks for testing @Hyperic88
