### ISSUE TITLE
nerf everburn urn

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5739]
![Screenshot from 2020-03-12 15-06-49](https://user-images.githubusercontent.com/42187820/76531081-f5bcda80-6474-11ea-8e30-c062371af4f6.png)
proposed nerf fot the everburn urn

**Comment by GTNH-Colen** [comment]
Lava is getting nerfed way too hard guys.

- Increasing cost of urn.
- Put useful products behind LHE (Increased complexity and setup cost).
- Increased energy consumption.
- Diluted useful material with stuff like SiO2. 

No one will bother with it if you nerf it too hard, what's the point when you can slap a miner down in the nether and get 10s of thousands of copper?

**Comment by 0lafe** [comment]
>Diluted useful material with stuff like SiO2

That's the HV version, which is still useful in HV, and beyond. Infinite silver with no upkeep is always a nice thing to have, especially if it's also giving you Mn and Ta. It's also easy enough to get a bunch of useful HV mats from something you can pump a lot of early on. 

>No one will bother with it if you nerf it too hard, what's the point when you can slap a miner down in the nether and get 10s of thousands of copper?

Don't veins cap sub 8k post nerf? You can get a bunch but miners are semi slow in HV/EV, and youll need to keep moving them. Not to mention you get P, Sn, W, Ag(should be Au maybe?), Al, and some Ti. All from one process, and all infinite. Using ++ centrifuges, you can still crank out a lot of these products in an infinite process, giving an easy enough route for useful materials in EV-LuV. Not really sure how these changes make it useless, still seems like a viable production for a handful of items

**Comment by Bluebine** [comment]
I've got no problem with it being a fairly difficult infusion recipe, since it's a fairly powerful item, but requiring tungstensteel coils gates it later than it is right now, and later than what it should be IMHO. How about adding a few reactor casings to the recipe? Those are EV, but reasonably expensive, and kinda fit thematically.

**Comment by Dream-Master** [comment]
Reactor casings ?
