### ISSUE TITLE
Transmute schematics within tier

### ISSUE THREAD

**Issue by mrgreenacid** [GTNewHorizons/NewHorizons#574]
Getting the wrong schematic after wasting 30-60 minutes finding/killing a terribly designed boss feels absolutely terrible. An interesting fix for this would be to have some kind of infusion crafting that changes less desirable schematics (moon buggy, cargo rocket, astro miner) into the respective tiers rocket schematic.

For recipes maybe some random vis that seems thematically close (vacous, etc), that tier's processed ore and dust byproduct.

Moon titanium and maybe an ingot or two of tungsten (grinding moon dust). 
Mars desh, tungsten-steel, iridium. I think you get the point.

This only would need to be done for the first 3 tiers since galaxyspace has no such shenanigans.

**Comment by Dream-Master** [comment]
@mrgreenacid 
A second idea is you can exchange schematics means you get a Cargo Rocket that you already have and exchange it to a Moon Buggy (Which you need) Ok you can only exchange Moon Schematics.
