### ISSUE TITLE
Add recipe: Bio Organic Mesh to Raw Carbon Mesh

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5741]
#### Which modpack version are you using?
2.0.8.6

#
#### What do you suggest instead/what changes do you propose?
Add an EBF recipe to turn bio organic mesh into raw carbon mesh.
Total: 72000 EU
Usage: 120 EU/t
Time: 30 secs
Heat Capacity: 1000 K
Same as turning bio carbon plate into carbon plate.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/76544665-b7311b00-6488-11ea-9910-8b048b316653.png)
