### ISSUE TITLE
Need help!!(Holo Glasses)

### ISSUE THREAD

**Issue by seitenca** [GTNewHorizons/NewHorizons#5743]
@GTNewHorizons/developers @GTNewHorizons/core 
We want to change the [Holo Glasses](https://github.com/GTNewHorizons/HoloInventory/blob/1.7.10/src/main/java/net/dries007/holoInventory/items/HoloGlasses.java) from baubles slot to the tinkers mask slot (is the slot 0)
I have managed to put it in the slot, the problem is that I do not know how to detect if it is equipped or not, to place the holo inventory event.

    public class HoloGlasses  extends Item implements IAccessory {

    public HoloGlasses()
    {
        super();
        this.setMaxStackSize(1);
        this.setHasSubtypes(true);
        this.setMaxDamage(0);
        setCreativeTab(CreativeTabs.tabTools);
    }

    public IIcon icon;
    @SideOnly(Side.CLIENT)
    @Override
    public void registerIcons(IIconRegister ir) {
        icon = ir.registerIcon("holoinventory:hologlasses");
    }
    @SideOnly(Side.CLIENT)
    @Override
    public IIcon getIconFromDamage(int meta) {
        return icon;
    }

    @SideOnly(Side.CLIENT)
    @Override
    public void getSubItems(Item par1, CreativeTabs par2CreativeTabs,List par3List) {
        par3List.add(new ItemStack(this,1,0));
    }

    @Override
    public boolean canEquipAccessory(ItemStack itemStack, int slot) {
        return slot == 0;
    }

    @Override
    public String getUnlocalizedName(ItemStack par1ItemStack)
    {
        return super.getUnlocalizedName() + "." + par1ItemStack.getItemDamage();
    }
    }

**Comment by Dream-Master** [comment]
@mitchej123 you my Tinkers-Expert maybe you know how it can easily implemented :)

**Comment by seitenca** [comment]
private ArmorExtended slot = new ArmorExtended();

    @SubscribeEvent
    public void renderEvent(RenderWorldLastEvent event)
    {
        if(slot.isStackInSlot(0)){

**Comment by Zoko061602** [comment]
GTNewHorizons/HoloInventory/pull/2
