### ISSUE TITLE
Hodgepoge and Mixin won't work with Gambiarra Fix on Servers

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#5745]
Hodgepoge and Mixin won't work with Gambiarra Fix on Servers.

@mitchej123 any idea how and if this can be fixed?

**Comment by mitchej123** [comment]
Will fix

**Comment by Dream-Master** [comment]
[fml-server-3.log](https://github.com/GTNewHorizons/NewHorizons/files/4332429/fml-server-3.log)
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/4332430/latest.log)

**Comment by Dream-Master** [comment]
@mitchej123 it nit working
tested with 
[BQ3-Thermos-Patch-1.0.jar.zip](https://github.com/GTNewHorizons/NewHorizons/files/4332433/BQ3-Thermos-Patch-1.0.jar.zip)
