### ISSUE TITLE
Chisel Variation Skystone crash on Thermos Servers

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#5747]
Chisel Variation Skystone crash on Thermos Servers

Ae rv3-23
Chisel 2.9.7.0

https://gist.github.com/Dream-Master/cea6c25e6e706a18c7c5fcf4fe7de4e1

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers

**Comment by Pilad** [comment]
May be error in script ?

**Comment by Dream-Master** [comment]
No scripts loaded last and cause not this crash.

**Comment by leagris** [comment]
@Pilad another issue is causing ae2 to not load correctly, not registering its blocks and then chisel encounter nullpointer exceptions while trying to reference the unexpectedly non-existent ae2 blocks.

**Comment by Dream-Master** [comment]
New AE Version 23 crash on Thermos Servers #5748

**Comment by Dream-Master** [comment]
Some day we need to run thermos on Java 8

**Comment by KaneHart** [comment]
I'm crashing with this as well it's happening on Vanilla Forge.... 
https://gist.github.com/KaneHart/485f0ab8ca73715d3cc192bb0fd7b2b4

**Comment by mitchej123** [comment]
Vanilla forge? Don't forget forge essentials!?

**Comment by mitchej123** [comment]
Or did you not include that in this run? (/client instance?)

**Comment by KaneHart** [comment]
So it worked once I used the new AE2. Strange bug I don't think was a thermos issue just AE2 and the way it was compiled I guess.
