### ISSUE TITLE
New AE Version 23 crash on Thermos Servers

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#5748]
New AE Version 23 crash on Thermos Servers

https://gist.github.com/Dream-Master/6126f12c6749397c23f7f49daa4af8fa

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers

**Comment by Dream-Master** [comment]
@Zoko061602 thanks for help

**Comment by repo-alt** [comment]
Thermos uses Java 6 ?
And we have no other mods using Java 8, really?

**Comment by Dream-Master** [comment]
yea fuck. Cost the whole day to find that out.

**Comment by Dream-Master** [comment]
Some day we need to run thermos on Java 8

**Comment by repo-alt** [comment]
Java 6. Gross.

**Comment by repo-alt** [comment]
But congratulations anyway, would never thought it was Java version to blame.

**Comment by Dream-Master** [comment]
Thanks to @Zoko061602

**Comment by repo-alt** [comment]
Btw, Thaumic Energistics targets Java 8

**Comment by repo-alt** [comment]
Even Gregtech targets Java 8

**Comment by draknyte1** [comment]
Literally any 1.7.10 mod updated in the last 3-4yr is using or at least compiling against J8.. 

At worst, J7. 

Nothing should be using J6 or be compiled against it. (Big No)

**Comment by Dream-Master** [comment]
@draknyte1 feel free to update the mod.

**Comment by bartimaeusnek** [comment]
If this ever happens again, add '-noverify' as a JVM argument.
