### ISSUE TITLE
Molten Bisphenol A, output anomaly

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/NewHorizons#5749]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Was looking at making Molten Bisphenol A and found a bug/error with the recipi
The Large Chemical reactor and Chemical reactor

The chemical reactor gives water as output and Bisphenol A , but not the LCR recipi,.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/3405825/76638552-eb6e0f80-654c-11ea-8c5d-f72bd8666d9e.png)
![image](https://user-images.githubusercontent.com/3405825/76638573-f3c64a80-654c-11ea-836e-8ef14067ad9f.png)

#
#### What do you suggest instead/what changes do you propose?
either remove water as output for the small chem reactor, or add it to the LCR version

**Comment by noobnoobnub** [comment]
it is intended
many recipes in LCR allows you to void water without producing it
check the same recipe and you will find they have different programming circuit

**Comment by Devtron3D** [comment]
According to NEI,  the LCR only has the recipi shown, with no extra output,
All chem reactor recipi (3 if them) come with water
As far as i have seen it is more or less always the LCR that comes with extra outputs, where the small one voids them.
