### ISSUE TITLE
Need a HQM replacement mod or a fix

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#575]
After so much Quests resets (because of Updates and no KCauldron support) no one really want to start the Quests again. We need a new Mod here.

**Comment by Dream-Master** [comment]
Maybe this mod:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2577119-better-questing-a-new-and-improved-questing-mod

**Comment by Technus** [comment]
Just try imporing HQM to that and see. There will be nothing better afaik.

**Comment by Dream-Master** [comment]
Sure will try today.

**Comment by Drehverschluss** [comment]
This mod seems very promissing in my mind. 

Also they have a full HQM and lootbags converter. Hope everything will work.

**Comment by Technus** [comment]
We dont use lootbags but a mod from Namikon instead.

**Comment by Dream-Master** [comment]
We can change or take new items in an XML file which makes loot bags full configurable.

https://github.com/GTNewHorizons/NewHorizons/blob/master/config/EnhancedLootBags/LootBags.xml

**Comment by Dream-Master** [comment]
Most of the Quests are easy imported but the Legendary Quest Series can be saved as json file an so I can't import it to the new mod. The Last update we change the hqm file to (4.4.4 to 4.4.4a) maybe that's the reason for the reset. I will do some Quests on the server in creative change and fixed some stuff in the hqm file and try to update the server again. Maybe now with the new version the problem is solved. Need more testing's. (The new Mod looks very Good but i think HQM have more options and things you can make with)

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/6y36el7yxl03sfz/Screenshot%202016-04-29%2023.15.15.png?dl=0

https://www.dropbox.com/s/mb2romekrxg565c/Screenshot%202016-04-29%2023.15.58.png?dl=0

https://www.dropbox.com/s/enoybf1zorva91l/Screenshot%202016-04-29%2023.16.22.png?dl=0

**Comment by Dream-Master** [comment]
REMINDER : Add some Leather and Cotton Quests before the Gloves.

**Comment by Dream-Master** [comment]
Done.

**Comment by Dream-Master** [comment]
We replacing HQM with Better Questing Mod soon. Need to wait for an update 1-2 weeks because of some wired crash.

https://github.com/Drethic/QuestBook/issues/8#issuecomment-216205749
