### ISSUE TITLE
Alloy Blast Smelter not respecting circuit in current input bus

### ISSUE THREAD

**Issue by kilianloftis** [GTNewHorizons/NewHorizons#5750]
#### Which modpack version are you using?
2.0.8.6

#
#### What did you try to do, and what did you expect to happen?
Make Molten Eglin Steel in an alloy blast smelter, using Eglin Base recipe. Ingredients are put into an input bus with a #3 circuit in it.

#
#### What happened instead? (Attach screenshots if needed)
The furnace produces silicon carbide, because another input bus has a #2 circuit in it.

#
#### What do you suggest instead/what changes do you propose?
Respect the circuit in the current input bus. I believe it used it.

**Comment by Dream-Master** [comment]
@kilianloftis  ABS is a GT++ device. Please report i here. Thanks
https://github.com/alkcorp/GTplusplus/issues

**Comment by draknyte1** [comment]
Not a bug.
