### ISSUE TITLE
InGameInfoXML slider not saving

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/NewHorizons#5754]
InGameInfoXML-1.7.10-2.8.1.84-universal.jar  

The config change does not take effect after hitting done and exiting the settings.  Upon reopening the settings it's back where it was (5).  All other settings seem to be updating, taking effect, and persisting except the scale slider.

**Comment by Dream-Master** [comment]
@mitchej123 remove your cfg and generate a new one. or copy over this from github. It works after. I test it allready

**Comment by mitchej123** [comment]
I tend to copy some of my old configs so I don't need to redo them every time -- should add a fix to work with the old config.

**Comment by 0lafe** [comment]
Idk if this is related, but disabling the hud doesn't persist upon relaunch

**Comment by Dream-Master** [comment]
@mitchej123 ask seitenca it's only this one line you need to change

**Comment by Dream-Master** [comment]
make sure the sale is I:scale and not S:scale

**Comment by seitenca** [comment]
@mitchej123 make sure your config is the lastest (2.0.8.6 or 2.0.8.7)

**Comment by draknyte1** [comment]
> add a fix to work with the old config

Due your fucking due diligence and make sure old config files load and update correctly. Should be transparent to the user,

**Comment by seitenca** [comment]
@draknyte1 I think it is common sense to update the config files

**Comment by draknyte1** [comment]
And if someone just updated the mod? They’d never know.. if you’re going to make changes to the config, do a proper job of handling it or don’t do it at all.

**Comment by seitenca** [comment]
a you mean the mod, I never think about it

**Comment by seitenca** [comment]
https://github.com/GTNewHorizons/InGame-Info-XML/releases/tag/2.8.1.84

**Comment by seitenca** [comment]
done

**Comment by draknyte1** [comment]
@mitchej123 owes you cookies now. 😉

**Comment by mitchej123** [comment]
Seriously, is it really that hard to code properly and add backwards compat?  It is a bug, and it is your fault.

**Comment by mitchej123** [comment]
A warning on the release is NOT how you handle this, you transparently load the old config values and fix them.

**Comment by mitchej123** [comment]
> @mitchej123 owes you cookies now. 😉

For a warning on a release? No.  It's not a proper fix.

**Comment by seitenca** [comment]
https://github.com/seitenca/InGame-Info-XML/commit/c1f4603774cf4ea2480facc1dddf68958b615191

**Comment by mitchej123** [comment]
Another option is to try loading it as an int... and if that fails, load it as a float and cast it to an int.  That way it's backwards compatible.
