### ISSUE TITLE
Quest 'Time to ore drill!' needs changes.

### ISSUE THREAD

**Issue by Relvl** [GTNewHorizons/NewHorizons#5755]
#### Which modpack version are you using?
2.0.8.7
#
#### What do you suggest instead/what changes do you propose?
Quest 'Time to ore drill!' in 'Multiblock goals' requires Input Bus (MV), but structure 'Ore Drilling Plant' does not need any Input Hatch. Mining pipes should be placed into controller block. 
Also need only 7 Solid Steel Machine Casing.
https://ftbwiki.org/Ore_Drilling_Plant

![image](https://user-images.githubusercontent.com/4003026/76774595-eff12d00-67c5-11ea-8874-cf232eebed9a.png)

**Comment by repo-alt** [comment]
Actually you do need input bus if you are at height >64

**Comment by Relvl** [comment]
It is optional, don't required thing.
