### ISSUE TITLE
Natura Crops dont break when farmland trampeled

### ISSUE THREAD

**Issue by meneken17** [GTNewHorizons/NewHorizons#5757]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
When you jump onto farmland int turns into dirt and breaks the vanilla crops.
#
#### What happened instead? (Attach screenshots if needed)
The Natura crops (e.g. cotton) do not break but stay an keep growing.
#
#### What do you suggest instead/what changes do you propose?
Crops break.

**Comment by ToastedEggplant** [comment]
I can confirm this issue.

**Comment by Dream-Master** [comment]
@jss2a98aj need help here
Thanks

**Comment by jss2a98aj** [comment]
This was fixed on the 16th. The bug was there so Natura crops spawned by world gen wouldn't randomly break. I was able to come up with a workaround and fix it without making crops from world gen break.
