### ISSUE TITLE
No recipe for electrotine

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#5760]
#### Which modpack version are you using?
2.0.8.6 also on 2.0.8.7QF2

I cant find a mixer recipe for electrotine. When  I check the usages of redstone found  a recipe that should be giving electrotine but gives nothing.

![2020-03-17_01 59 12](https://user-images.githubusercontent.com/36479271/76809566-ea124080-67f3-11ea-92ae-ecab6f63dd79.png)

I think @Dream-Master broke something when fixing #5639

**Comment by Dream-Master** [comment]
will check
