### ISSUE TITLE
Holoinventory Glasses Tier Fix

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/NewHorizons#5761]
#### Which modpack version are you using?
Latest
#

Can we move perditio lens to lv lathe so that Holoinventory Glasses are available in LV?

![image](https://user-images.githubusercontent.com/9472512/76809842-83c0fa00-67c2-11ea-9f8e-245b20fd414a.png)
![image](https://user-images.githubusercontent.com/9472512/76809850-891e4480-67c2-11ea-8ffa-9669487dbf60.png)

**Comment by Zoko061602** [comment]
Better change the recipe to use Glass Lenses, this would move the recipe to late steam age.

**Comment by Dream-Master** [comment]
I thought this lens is a bit magical look into chests. I make it a give away (quest reward) when you create the bronze boiler at beginning steam. And you can choose 2 more perdition lenses. If you lost it you can make one more after your first steel.

**Comment by ToastedEggplant** [comment]
I'm in LV at the time that the change happened so I never got it as a reward.

**Comment by Dream-Master** [comment]
that is true. will add a coins coins quest.

**Comment by Houstonruss** [comment]
Earlier glasses the better. The glasses lose their effectiveness the later the game progresses anyway, as people shy away from chest walls.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77103411-a51c2300-6a1a-11ea-8704-4b431f828096.png)
![image](https://user-images.githubusercontent.com/2970688/77103421-a9e0d700-6a1a-11ea-99bd-3afc02d579dc.png)
![image](https://user-images.githubusercontent.com/2970688/77103436-afd6b800-6a1a-11ea-85a5-fff07925c4ec.png)

Not to bad. Locked after first steel
