### ISSUE TITLE
Task ID: 798 The second project ID is incorrect

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/NewHorizons#5769]
#### 2.0.8.7.dev.QF2

#
#### single-player

#
#### Complete the second item of the task ID: 798

#
#### No matter what I do is the item ID: # 4365/20, not # 4365/3 thaumcraft: wandcasting
![1](https://user-images.githubusercontent.com/22012110/77027854-459a2500-69d2-11ea-8518-494edfae3c38.png)
![2](https://user-images.githubusercontent.com/22012110/77027859-4763e880-69d2-11ea-97cd-0d91284daadc.png)

#
#### 
If possible, please tell how to make the right item
or hope to be resolved in the next version

**Comment by Dream-Master** [comment]
Not sure what you exactly mean.
I change things a little bit not sure this was the error.
@AdminXiaoMai
