### ISSUE TITLE
Add sounds to OpenSecurity Alarm

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#577]
https://github.com/GTNewHorizons/NewHorizons/commit/eb2bb68e52e76c2b8124896234090d6b457fcf0b

**Comment by Dream-Master** [comment]
added. Not sure if the sounds have to be in the config or the mods folder.
@Technus can you check it please?

**Comment by Technus** [comment]
Build 77 changes how alarms are loaded, alarms are now loaded from 

- /mods/OpenSecurity/sounds/alarms/

 
and must be .ogg files, there is no need to modify the sounds.json, or the config file anymore, but sounds must be on all clients to be played.  Also alarms should be small, as the client has to load the entire file into memory to play it which with large files will cause the client to hang.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/15420448/05a2b6e2-1e6d-11e6-9ee9-92de37ffa886.png)

**Comment by Dream-Master** [comment]
klaxon1.ogg
klaxon2.ogg

**Comment by Dream-Master** [comment]
Added
