### ISSUE TITLE
Gardener quest stone age

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/NewHorizons#5771]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I made a mattock with iron and a stick instead of bronze so the quest should not be completed
#
#### What happened instead? (Attach screenshots if needed)
The quest was   ##completed
#
#### What do you suggest instead/what changes do you propose?
I suggest 2 possibles things : 
- Possibility of making a mattock with any material
- The quest check only if a bronze mattock is made

**Comment by boubou19** [comment]
it's quest number 483
