### ISSUE TITLE
Diamond nuggets not craftable

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/NewHorizons#5773]
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### 

Diamond nuggets from the translocator mod are not craftable at the moment. Of course this might just be intentional but I could not find anything on the topic on discord or here on github. The diamond nugget is currently oredicted together with the diamond shard which is craftable, but diamond shards don't work on translocators.

Diamond nuggets are super useful, so please add a recipe. :)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77105967-b23b1100-6a1e-11ea-9b3b-457be06d1b01.png)
