### ISSUE TITLE
GT-ERR-01: @ ic2.itemRubber   Rubber

### ISSUE THREAD

**Issue by PaladinOne** [GTNewHorizons/NewHorizons#578]
So I was digging through my client startup log and stumbled upon this. Unfortunately I have no idea what mod could actually be causing it, and a quick NEI recipe search doesn't turn up any GT-ERR-01s either.

**Comment by Dream-Master** [comment]
Most of the recipe i change with minetweaker. Maybe there some original recipe that have an error.

**Comment by Technus** [comment]
Here.
https://github.com/Blood-Asp/GT5-Unofficial/blob/6e0f90964ec2b6d7b436fb5b9bc0c1e0b09be0bf/src/main/java/gregtech/GT_Mod.java#L813

Greg describes stuff.

**Comment by PaladinOne** [comment]
^I'm aware that is the source of the message; the problem is tracking down the source of the bad recipe.

**Comment by Dream-Master** [comment]
@PaladinOne , @Technus Any Ideas here?

**Comment by Dream-Master** [comment]
Nothing i can do here. maybe I ask Blood Asp.

**Comment by Dream-Master** [comment]
@PaladinOne Find the bad recipe in Thinks Construct.

![image](https://cloud.githubusercontent.com/assets/2970688/19020273/a4d688be-88a4-11e6-8dae-896f2f9bf764.png)

**Comment by Dream-Master** [comment]
It is Glue.

**Comment by Haudi1986** [comment]
I have the same Problem, but how can i remove the recipe with minetweaker? Has anyone the Scriptcode for me? I used this //IC2 rubber
furnace.remove(<IC2:itemRubber>);
furnace.remove(<TConstruct:materials:36>);
But it doesnt work :( Pls Help

**Comment by Dream-Master** [comment]
Tinkers construct cause this issue. Its only a warning message nothing serious. So ignore it.
