### ISSUE TITLE
Tinkers smeltery not accepting GT aluminium ingots

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/NewHorizons#5784]
#### Which modpack version are you using?
2.0.8

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I tried making aluminium brass using ingots as input

#
#### What happened instead? (Attach screenshots if needed)
"normal" GT aluminium ingots did not smelt, despite NEI showing recipes for other aluminum ingot versions

#
#### What do you suggest instead/what changes do you propose?
Add the option to smelt GT aluminium ingots

**Comment by Dream-Master** [comment]
No i wont because this will break gt tiering.

**Comment by combusterf** [comment]
To make sure we don't misunderstand each other, I don't expect to cast *into* aluminium ingots (that would indeed tierskip past the EBF), but rather turn exiting ingots into smeltery contents.

**Comment by Dream-Master** [comment]
Ok . You need more Tinkers aluminium in MV ? Alu Gravel not enough?

**Comment by boubou19** [comment]
thing is, for exemple, if you do not have one type of mold, you need to make aluminium brass into the smeltery. The point of Combuster is that you cannot put GT aluminium ingot into the smeltery. Only the dust.

**Comment by Dream-Master** [comment]
ok i can add alu ingots to smelter but all you get is Tinkers alu.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77260948-45787e80-6c8b-11ea-876b-14723e7b758b.png)
