### ISSUE TITLE
Quest: 'Auto Mining HV' description small tweak

### ISSUE THREAD

**Issue by Shuan97** [GTNewHorizons/NewHorizons#5785]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
Quest should have "Fortune 3" instead of "Fortune 6" in the descripton, Advanced Miner HV says it has fortune 3.
#
#### What happened instead? (Attach screenshots if needed)
-
#
#### What do you suggest instead/what changes do you propose?
Change just one number in the description.

![image](https://user-images.githubusercontent.com/35654946/77229635-504de900-6b8f-11ea-814a-842e5cdd5ce5.png)

**Comment by Dream-Master** [comment]
Allready fixed in anewer version

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77261004-98523600-6c8b-11ea-8ffa-346f8a6fc36c.png)

**Comment by Shuan97** [comment]
Great, didn't find related issue before, issue closed

**Comment by Dream-Master** [comment]
i close it after release @Shuan97
