### ISSUE TITLE
Power Station weird structure check

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/NewHorizons#5786]
#### Which modpack version are you using?
2.0.8.7QF2 SinglePlayer

forgive my bad english 
#### What did you try to do, and what did you expect to happen?
Power Station not form third layer and above
#
#### What happened instead? (Attach screenshots if needed)
![2020-03-21_22 52 36](https://user-images.githubusercontent.com/25171639/77229571-c96a3200-6bc9-11ea-8f05-45cbfcc07908.png)
but if i quit to title and enter the world again the structure is form
![2020-03-21_23 22 55](https://user-images.githubusercontent.com/25171639/77229810-ea7f5280-6bca-11ea-9bb0-1f7edfa9d534.png)
however if you place or break the wire that connect the hatch it will cause the incomplete structure error
![2020-03-21_23 26 03](https://user-images.githubusercontent.com/25171639/77229916-8dd06780-6bcb-11ea-8df4-ad0abb2e89f3.png)
![2020-03-21_23 26 22](https://user-images.githubusercontent.com/25171639/77229921-96c13900-6bcb-11ea-9aa2-b397068c664c.png)

**Comment by GTNH-Colen** [comment]
This seems like a GT++ issue, please report it there:

https://github.com/alkcorp/GTplusplus/issues

**Comment by botn365** [comment]
tire removing the core module hatch

**Comment by FallDark** [comment]
> trie removing the core module hatch

Thanks it works fine after remove core module hatch
