### ISSUE TITLE
Paper has incorrect aspects, Blaze Powder has too much

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#579]
Paper is 4 aqua 4 metallum 1 cognito.  This is annoying when trying to produce Cognito essentia, and doesn't really make sense either.

It should probably just be 1 cognito.

Blaze Powder on the other hand has 24 ignis, 12 praecantatio, and 1 instrumentatum.  It should have 2 ignis 1 praecantatio.

**Comment by Dream-Master** [comment]
Will look inside it tomorrow.

**Comment by Dream-Master** [comment]
So change .
````````````````````
// --- Thaumcraft Aspects Set ---


// --- Blaze
mods.thaumcraft.Aspects.set(<minecraft:blaze_powder>, "ignis 6, praecantatio 4, instrumentum 2");

// --- Blaze Rod
mods.thaumcraft.Aspects.set(<minecraft:blaze_rod>, "ignis 10, praecantatio 4");

// --- Paper
mods.thaumcraft.Aspects.set(<minecraft:paper>, "cognitio 4, aqua 2, arbor 1");`
````````````````````````
