### ISSUE TITLE
Ticking Fire Zombie crashing the game (an arrow seems to be involved, too)

### ISSUE THREAD

**Issue by Oheta11** [GTNewHorizons/NewHorizons#5793]
#### Which modpack version are you using?
I am using the latest version atm, GT:NH v2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
It's a SP world. One thing to note, I added Botania to my game but I didn't seem to have a part in the crash. 
#
#### What did you try to do, and what did you expect to happen?
Merely strutting about. The crash comes from a ticking entity (fire zombie if I read the crash report correctly) that has been shot by an arrow ? That I didn't fire. I am pretty early game, so I don't have any turrets of some kind. No villages around too (so no guards). The crash I linked happened shortly after loading the world that had crashed moments ago.
#
#### What happened instead? (Attach screenshots if needed)
Well, the game crashed.
[crash-2020-03-20_14.59.46-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/4364964/crash-2020-03-20_14.59.46-server.txt)
For the time being I relocated InfernalMobs-1.7.0-GTNH.jar to a safe place (jail) and it works like a charm.
#
#### What do you suggest instead/what changes do you propose?
Absolutely no idea. I have to admit, I kinda have a PTSD problem with Java. Good luck ! I hope this report helps. Don't hesitate to contact me if you need anything.

**Comment by Dream-Master** [comment]
fixed in 1.7.1  I guess. Will pull version 2.0.8.8 today

**Comment by wlhlm** [comment]
Yes, this is a known crash in Infernal Mobs. You can grab the fixed jar [here](https://github.com/GTNewHorizons/Infernal-Mobs/releases/tag/1.7.1) if you need an immediate fix, or wait for the 2.0.8.8 release which should be imminent.
