### ISSUE TITLE
Clay bucket turns to iron bucket when picking up oil

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#580]
This means you can transmute clay into iron.

**Comment by Dream-Master** [comment]
yes test it and it change. very strange. Not sure if we can do there anything. Mod are now at 1.8 or 1.9 i guess mod authors wont change stuff.

**Comment by Dream-Master** [comment]
Maybe we have to add a oil bucket to prevent it from changing. Then i will add a creosote clay bucket too.

**Comment by Technus** [comment]
Fixed - RC and BC fluids are now impossible to carry around in them now.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/IguanaTweaksTConstruct/commit/f34900edeb77a56d2fc0ae00efc18dfa26f396f7
fixes #580
