### ISSUE TITLE
2.0.8.8 server download has missing LunatriusCore

### ISSUE THREAD

**Issue by Khalkion** [GTNewHorizons/NewHorizons#5800]
#### Which modpack version are you using?
2.0.8.8 server download
#
#### If in multiplayer; On which server does this happen? 
Local server
#
#### What did you try to do, and what did you expect to happen?
Tried to launch and got crash as mod is missing.

#
#### What do you suggest instead/what changes do you propose?
Add required dependency to download file.

Client has the mentioned file, only server needs attention.

**Comment by Dream-Master** [comment]
Just redownload the pack.
