### ISSUE TITLE
Updating causes Magical Forest becomes Tainted

### ISSUE THREAD

**Issue by Ling4321** [GTNewHorizons/NewHorizons#5811]
#### Which modpack version are you using?
I updated from 2.0.8.3 to 2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I updated the modpack and used the old map, and expects that everything will work fine.
#
#### What happened instead? (Attach screenshots if needed)
I found that the Magical Forest biome I found before becomes Tainted.
#
#### What do you suggest instead/what changes do you propose?
I hope that you can fix this if it is a bug. It might be my fault because I added mods that doesn't belongs to the modpack, or because I haven't changed the save.
(Sorry for my poor English, since I don't use English. I hope you can understand.)

**Comment by Ling4321** [comment]
If it is a bug, I hope that this won't happen again if I update it to new versions.

**Comment by boubou19** [comment]
do you have a backup of the save? if yes try to remove all the mods you added, then load the the save with 2.0.8.4, then if everything is fine with 2.0.8.5, etc until you find the 1st version where it goes wrong

**Comment by wlhlm** [comment]
I suspect there is something wonky with your installation. I recommend doing a fresh install and using the old save to see if the same problem occurs. Of course keep a backup of your old installation.

There was a similar sounding problem for an update to 2.0.8.6, see #5724. It could be because of one of the mods you've added. Can you post a list of the stuff you added?

**Comment by Ling4321** [comment]
Well, I actually add lots of things.
They are THKaguya mod, projectE with Thaumic Equivalence, Slashblade with the Last Smith, Bamboo, Ex Nihilo for lava, Academy Craft for superabilities and Torcherino.
Also I deleted hardcore darkness and inferno mobs, which actually decrease the difficulty a lot. I add them just for better fuel or for fun.
I delete all of them and I'm trying to reinstall the modpack, hope it can fix the problem.

**Comment by Dream-Master** [comment]
@Ling4321 we not support modified packs. Play it vanilla or not complain.
