### ISSUE TITLE
About gt item pipes

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/NewHorizons#5813]
I'm trying to make a setup for benzene production with advanced coke ovens. I have a drawer with woods and normal nickel pipe with mv conveyor. It should give up to 64 item with conveyor but finds first adv coke oven and fills it even if it needs 1 wood and doesn't goes on to other coke ovens. It has 1 stack second limit but acts as 1 connection per second. I tried to split pipes before reaching first coke oven but it only fills nearest one.

**Comment by richardhendricks** [comment]
This how the GT machines etc are setup.  The X stacks per second is *destinations*. So if you have a fast machine, it will take the 1 item and the pipe will not try the next machine.  

If you want to send outputs to multiple machines, you must either get a faster conveyor for the extraction side, or else split up your pipe network into multiple pipes (or do both). What I do is route my logs to 1 barrel, and then have conveyors extract from each side of the barrel and limit the max destinations per pipe.
