### ISSUE TITLE
crashed with SpongeMixins-1.2.0.jar and privat launcher 

### ISSUE THREAD

**Issue by boozzeeboom** [GTNewHorizons/NewHorizons#5815]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
private melkocraft.ru
#
#### What did you try to do, and what did you expect to happen?
Client can't start with SpongeMixins-1.2.0.jar, but work correctly with SpongeMixins-1.1.0.jar
#
#### What happened instead? (Attach screenshots if needed)
crash here: https://pastebin.com/jG1KH7ac

**Comment by mitchej123** [comment]
Validating: Client side or Server side?  Any other addons added or removed?

**Comment by boozzeeboom** [comment]
it's only on client side. server works correctly with both 1.2 and 1.1.
mods full from official gtnh

**Comment by mitchej123** [comment]
What's your username on GitHub.  Can make a build for you to test

**Comment by mitchej123** [comment]
I mean discord...

**Comment by boozzeeboom** [comment]
Indeed#9146

**Comment by mitchej123** [comment]
It looks like your private launcher is pulling in an incompatible gson version; you'll need to get it to pull in a compatible version.

This works fine in the base version of the pack.
