### ISSUE TITLE
Lead Nuggets not smeltable in the smeltery

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#582]
Lead Nuggets not smeltable in the smeltery.

**Comment by drroller** [comment]
Lead ingots have the same issue.

**Comment by ProsperCraft** [comment]
Lead ingots have the same problem.

**Comment by Dream-Master** [comment]
Ok will look into it too.

**Comment by SanMan911** [comment]
Wasn't able to smelt silver nuggets in the smeltry, either.
Also tried using mortar to crush it, but in vain.
Maybe make a recipe with mortal, or make nuggets smeltable in the smeltry.

**Comment by Dream-Master** [comment]
So far i can see Lead isnt good for nothing but i will add those missing recipes.
