### ISSUE TITLE
Overflow Values should loop backwards from lowest value to highest value

### ISSUE THREAD

**Issue by patrick-hill** [GTNewHorizons/NewHorizons#5820]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
MP, my server

#
#### What did you try to do, and what did you expect to happen?
Used screwdriver to increase value. Once max value is reached, it rolls over to the lowest value allowed.
Decreasing the value stops at its lowest value instead of rolling over to the highest value.

#
#### What happened instead? (Attach screenshots if needed)
Decreasing value stops at lowest value instead of rolling over to highest.

#
#### What do you suggest instead/what changes do you propose?
Decreasing the value beyond the lowest should roll it over to highest value.
Basic use case for these is to use a small tank as overflow for a larger one... meaning the highest value is generally wanted (at least for my poor ass MV pump age where extraction speed is an issue)

**Comment by botn365** [comment]
fixed in newest version of gt++

**Comment by patrick-hill** [comment]
Perfect, thanks!

**Comment by patrick-hill** [comment]
Well, I'm still noob'ing at all these mods. Are you saying GT++ that is in NH?
