### ISSUE TITLE
weird distillation tower recipe

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#5823]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was looking in nei the use of liquid air
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/12850933/77676975-5973f700-6f8f-11ea-9c0f-9496d37b1c3b.png)

Is it even possible to push that amount of liquid in a distillation tower?

**Comment by draknyte1** [comment]
Bart added large hatches just for these afaik.

**Comment by Shuan97** [comment]
Check on Liquid Air Fluid Hatch, it has enough capacity to hold such amount of liquid

**Comment by boubou19** [comment]
the more you know
