### ISSUE TITLE
Netherstar dublication recipe

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#583]
Change to a more pricy recipe.

**Comment by Goofyschooler** [comment]
Idea could be to cut the nether star and for each one use sails mundus in a blast compressor to create a full star. So netherstar>cutting machine>nether star fragment(2)>blast compressor (8 salis mundus 1 nether star fragment)>1 nether star.

**Comment by Dream-Master** [comment]
Implusion Compressor can take only one item and iTNT.

**Comment by Goofyschooler** [comment]
Ohokay didn't know that. Maybe instead do salis mundus in the blast compressor with itnt to make a referbished nether star fragment and the. Use the two fragments in an assemblr with enderpearl fluid to Fuze the two prices together

**Comment by Dream-Master** [comment]
I will think about a recipe but it need some part of the Nether Start to crystallize a new one.

**Comment by Goofyschooler** [comment]
I agree 100% do you want to include magic in this recipe? Could use witcher or bm since it hasn't been messed with yet

**Comment by Dream-Master** [comment]
I think gt recipe would be fine if i have an good idea.

**Comment by Goofyschooler** [comment]
Alright, I think one of the multi block machines should be included but it's upto you.

**Comment by Dream-Master** [comment]
You will using Null Catalyst and Salis Mundus to make Nether Stars in the future.

**Comment by Dream-Master** [comment]
fixed.
