### ISSUE TITLE
Infernal Mobs ClassCastException

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/NewHorizons#5851]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
walking around
#
#### What happened instead? (Attach screenshots if needed)
[crash](https://pastebin.com/uQExeryt)
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by wlhlm** [comment]
This has been fixed in 2.0.8.8.
