### ISSUE TITLE
ConcurrentModificationException during the world launch

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#5868]
So I'm using the latest modpack version 2.0.8.3 with the latest java 8.
Everything was going smoothly till last night I correctly exited a game, and today during the launch it throws me out with the following errors
https://pastebin.com/z4NkSdCK
Three launches - and it's all the same.

**Comment by Dream-Master** [comment]
@nikitinalexx use a newer version or update bartworks to 0.5.12

**Comment by nikitinalexx** [comment]
Thank you, updating the mod solved the issue.
