### ISSUE TITLE
Suggestion, show fluid amount in NEI.

### ISSUE THREAD

**Issue by moller21** [GTNewHorizons/NewHorizons#5869]
Hey again,

It was annoying me that i had to mouseover the fluids in a recipe to see the amounts, would be nice to show them instantly. 

I've been toying around in an IDE and i made this so far, but to be honest i don't really know what I'm doing. Would be great if someone competent could add it:) 

Some issues now is that the font looks blurry at some gui scales, and the item count number for the fluid is shown if there's more than 1999 liters worth of fluid.

![2020-04-04_17 39 41](https://user-images.githubusercontent.com/42100910/78454957-c37d5200-769b-11ea-81a5-b27a3eb1b845.png)

```
    private void drawFluidAmount(PositionedStack posStack) {
        for (ItemStack item : posStack.items) {
            if ( item.hasTagCompound()) {
                long fluidAmount = item.getTagCompound().getLong("mFluidDisplayAmount");
                if (fluidAmount > 0L) {
                    String amountString;

                    if (fluidAmount < 10000) {
                        amountString = "" + fluidAmount + "L";
                    } else {
                        int exp = (int) (Math.log(fluidAmount) / Math.log(1000));
                        amountString = String.format("%.1f %cL", fluidAmount / Math.pow(1000, exp), "kMGT".charAt(exp - 1));
                    }
                    Minecraft.getMinecraft().fontRenderer.drawString( amountString, posStack.relx*2, posStack.rely*2+24, 0xFFFFFF, true);
                }
            }
        }
    }

    public void drawExtras(int aRecipeIndex) {
	int tEUt = ((CachedDefaultRecipe) this.arecipes.get(aRecipeIndex)).mRecipe.mEUt;
	int tDuration = ((CachedDefaultRecipe) this.arecipes.get(aRecipeIndex)).mRecipe.mDuration;
	String[] recipeDesc = ((CachedDefaultRecipe) this.arecipes.get(aRecipeIndex)).mRecipe.getNeiDesc();

        GL11.glPushMatrix();
        GL11.glScalef(0.5F, 0.5F, 0.5F);
        for (PositionedStack output : this.arecipes.get(aRecipeIndex).getOtherStacks()) {
            drawFluidAmount(output);
        }
        for (PositionedStack ingredient : this.arecipes.get(aRecipeIndex).getIngredients()) {
            drawFluidAmount(ingredient);
        }
        GL11.glPopMatrix();
```

**Comment by draknyte1** [comment]
> the item count number for the fluid is shown if there's more than 1999 liters worth of fluid

That's cause 2000L is an ItemStack with a stacksize of 2..

**Comment by moller21** [comment]
Yes, exactly. Don't know how to hide it.

**Comment by draknyte1** [comment]
You either patch MC or NEI, lol.

**Comment by GTNH-Colen** [comment]
Don't listen to drak, they're just grumpy. This is a really great idea, thanks for putting the work in and writing some stuff up. Hopefully someone with a little more experience in these matters can help you out.

**Comment by draknyte1** [comment]
> Hopefully someone with a little more experience in these matters

Oh wait, that's me. 🤦
I mean, I'm stating the facts though @GTNH-Colen. I think it's a nice idea, but like many nice ideas, are bound to the limits of MC or other mods. The rendering code for stack size either resides in NEI or vanilla MC and you can't really do much about that with patching them. The 'Fluid-Item' is just a normal item, it doesn't get special behaviour. 🤷‍♀️

**Comment by moller21** [comment]
Thanks. Well you don't sound positive drak:p

Can't gregtech just always send fluids with a stacksize of 1 int the recipes?

**Comment by draknyte1** [comment]
> you don't sound positive

Do I ever? 🤔 

> Can't gregtech just always send fluids with a stacksize of 1 to the NEI recipes?

NEI just iterates the actual recipes.
You probably could if you poke around the NEI handler I guess.. good thonking.

**Comment by moller21** [comment]
Yes, positivity:) I'll dig around there some time. Been staring at walls of text to long today.

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by Glease** [comment]
Replace the `GT_Utility.getFluidDisplayStack()` calls inside `GT_NEI_Default_handler.java` and `GT_NEI_AssLineHandler.java` with something that always set the stack size to 1 would fix the problem in NEI. This however does not affect the fluid display inside machine GUI. A much better fix would be implementing an `IItemRenderer` for `GT_FluidDisplayItem` and only pass around `GT_FluidDisplayItem` at a stack size of 1. It's a fake item so the actual stack size doesn't really matter.

**Comment by moller21** [comment]
That's a good idea, I'll have a go at it.

**Comment by Dream-Master** [comment]
@moller21 @Glease we have forked Nei so it can be added.

**Comment by Glease** [comment]
@Dream-Master We don't actually need to change NEI for this fix though, but good to know.

@moller21 I'm somewhat familar with GT's code base. Feel free to tag me if you find something confusing.

**Comment by Dream-Master** [comment]
@moller21 are you joined GTNH Discord ? What is your username ?

**Comment by moller21** [comment]
Yeah im on there, sticklord is the username:)
