### ISSUE TITLE
Grass Won't Spread In To Dirt Blocks.

### ISSUE THREAD

**Issue by JokoJose** [GTNewHorizons/NewHorizons#5871]
#### Which modpack version are you using?
GTNH 2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
On every MMCC server dedicated to GTNH (possible on officials too, haven't tested it tho)

#### What did you try to do, and what did you expect to happen?
Grass won't spread from a grass block to a dirt block, regardless of proximity or light level. Even if next block has grass, it won't spread towards the dirt block to make it grass block.

#### What happened instead? (Attach screenshots if needed)
Dirt stays dirt forever instead of turning in to grass.

#### What do you suggest instead/what changes do you propose?

Check if its a code error, or make a low tier tool (chisel for example) that can turn dirt into grass.

**Comment by boubou19** [comment]
did you tried the reinforced watering can? I'm used to spread grass with that on delta.

**Comment by chochem** [comment]
grass spreading works fine in my 2.0.8.8 SP world. just tested.

**Comment by JokoJose** [comment]
No boub because im not that advanced on this server im playing now. 

Chochem u playing in official or private? because i play on MMCC multiplayer servers and both of their server has the issue, not only for me, but for everyone on the server.

**Comment by chochem** [comment]
as I said, singleplayer. I am not denying you have an issue. I am just trying to help narrow down the cause. :)

**Comment by JokoJose** [comment]
It didnt said single player on your previous reply, thats why i asked. I am trying to narrow it down too. So far got words that its happening on Toasted servers too. So it has to be related to the 2.0.8.8 update. Possible the crops slow growth rate affected grass spread rate and stop it from spread.

**Comment by JokoJose** [comment]
ah SP = private server?

**Comment by Nick5131** [comment]
My thoughts are it might be thermos causing this issue, I'm running into it aswell here on Fully Toasted's GTNH

**Comment by draknyte1** [comment]
And thermos isn’t supported. ☺️

It’s very much use at your own risk, lol.

**Comment by mitchej123** [comment]
HodgePodge fixes grass trying to spread in unloaded chunks. Are you using Thermos?  

This was tested on SP and my locally hosted MP world.  If Thermos is messing with the grass block's update tick or workd.blockExists, it could be interfering with the fix.

https://github.com/GTNewHorizons/Hodgepodge/blob/master/src/main/java/com/mitchej123/hodgepodge/mixins/fixgrasschunkloads/block/MixinBlockGrass.java

There's an option in the config to disable the fix if you'd like, look under `config/hodgepodge.cfg`

**Comment by mitchej123** [comment]
Yah, Thermos is rewriting the grass block update function and causing hodgepodge to not work.  Disable the fix in the hodgepodge config.

**Comment by mitchej123** [comment]
Automatically detected and disabled in https://github.com/GTNewHorizons/Hodgepodge/commit/f1c3492608aae80aaf94e5b649aafdedffae6349
