### ISSUE TITLE
Quest #1590 in Witchery Chapter dimension task not work

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/NewHorizons#5872]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Self-host
#
#### What did you try to do, and what did you expect to happen?
Complete quest 1590.
#
#### What happened instead? (Attach screenshots if needed)
Cannot complete 1590.
#
#### What do you suggest instead/what changes do you propose?
Quest is check dim_id=0 and range=55, should be change into dim_id=55 and range=-1.

**Comment by Prometheus0000** [comment]
Are you sure? It says dim 55 and range -1 in my 2.0.8.5 instance, and I don't think anyone's touched that quest in between. And the 2.0.8.8 file says the same thing. Are you sure it isn't working and that it's that quest? One of them was broken like that before, did you update your quests?

**Comment by albus12138** [comment]
@Prometheus0000 It seems that something wrong when I upgrade from 2083 to 2088. Sorry.
