### ISSUE TITLE
plantmass maceration eu cost

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/NewHorizons#5884]
Plantmass has 30 eu/t cost that makes using hv macerator for bonus output useless.

**Comment by Dream-Master** [comment]
explain why @ahmetsad ?

**Comment by ahmetsad** [comment]
why should i use 16x more energy for something free to get 2x output when i can place 4x lv macerator for same recipe.

**Comment by Bluebine** [comment]
I don't see how this is a problem? It's a tradeoff between power consumption on the macerator, or using twice the amount of plants to make plantballs.
And no, plantmass isn't just a "low tier" recipe, it's great for chemicals even in lategame.
Fine as it is, don't see why this needs to change.

**Comment by AiramProvoker** [comment]
Above MV, you should have no trouble with the amount of plantmass, so people will just spam LV macerators at any tier, making the fact there are byproducts in the recipe useless.
It is a weird recipe that is hard to justify.

**Comment by Bluebine** [comment]
I use it. It's easier to put down 1 HV macerator, than to put down twice the amount of every other machine, and 1A HV is really not that much power cost, especially considering that you'd need more of the other machines anyways.

**Comment by ahmetsad** [comment]
Recipe just looked odd . Still odd without multi tough. I think i should hear for more people before opening a ticket.
