### ISSUE TITLE
GT Machines are not detected in quests

### ISSUE THREAD

**Issue by toadjaune** [GTNewHorizons/NewHorizons#5892]
#### Which modpack version are you using?
2.8.0.3

#
#### If in multiplayer; On which server does this happen? 
A private server, but I can give access if you want to reproduce.
I tried on a local world, the problem is present too.

#
#### What did you try to do, and what did you expect to happen?
I crafted a Basic Electric Furnace and held it in my hotbar, with quest 88 "Welcome to tier 2" complete.
I then opened quest 1887 "Electric Furnace" and clicked "Detect/Submit" to force the quest detection.
I expected the Retrieval task (and consequently, the quest) to be validated.

#
#### What happened instead? (Attach screenshots if needed)
Nothing, the Retrieval task is still not validated.

#
#### Extra details

It would seem the issue appeared when we upgraded the server from the previous stable version (2.0.7.5), which, if I'm not mistaken, implies a major Better Questing upgrade.

The issue seems to affect all retrieval tasks of GT machines or tools (like electric handheld tools), but nothing else. I'll make sure to add any found counter-examples here.

The issue seems to affect all players on the server equally, regardless of if they are in a party or not.

I did a few more tests based on https://github.com/GTNewHorizons/NewHorizons/issues/5047 (both on the server and on my local world), and interestingly enough, a crafted furnace does not validate the quest, but one taken from NEI does !

Looks like it may be some NBT tag related issue, but I couldn't see any difference between the two furnaces (they both show `(#1480/261) 1480:261`), and I honestly don't understand what I'm talking about enough to research this lead any further.

Next test, I tried to generate a new world with this version on the modpack. Not only does it work just fine with the crafted furnace, but the questbook is visually quite different (different sizes for quests, thumbnails on tabs, see ![before](https://user-images.githubusercontent.com/12686813/78838922-cef7b280-79e6-11ea-80e6-94d077286bf4.png) and ![now](https://user-images.githubusercontent.com/12686813/78838920-cdc68580-79e6-11ea-906d-078ebf4c276b.png)
)

At this point my hypothesis is that the upgrade of the modpack (specifically, of Better Questing), required some kind of manual action to upgrade the questbook, but we failed to do it.

Are there some release notes instructions that we missed ?

Thanks in advance to anyone who would help us !

**Comment by chochem** [comment]
this has all been fixed already. Either update or, as a workaround, use the Name Remover to get rid of nbt data.

**Comment by Redlinkk** [comment]
We updated the server from 2.0.8.3 to 2.0.8.8, it didn't fix the problem. 
To fix it, I removed the QuestDatabase.json in the save folder, which seemed outdated. It regenerated on server restart and it fixed the problem.

**Comment by Dream-Master** [comment]
@Redlinkk did you use /bq_admin default load ?

**Comment by Redlinkk** [comment]
No, I didn't know the command. That would probably fix the issue

**Comment by Dream-Master** [comment]
yes file need to update all the time (every update)

**Comment by Redlinkk** [comment]
okay thanks, I will do that from now on

**Comment by Dream-Master** [comment]
@Redlinkk close the issue if this fix it. Thanks

**Comment by Dream-Master** [comment]
@toadjaune

**Comment by toadjaune** [comment]
@Redlinkk fixed it manually on our server, but I can confirm this command did fix it on my local world too.

Thanks a lot !
