### ISSUE TITLE
HV Motor recipe problems.

### ISSUE THREAD

**Issue by Yeti-one** [GTNewHorizons/NewHorizons#590]
Hi. Cannot make HV Motor due to needing Nichrome wire.
Nichrome needs the Vacuum Freezer. 
Vacuum Freezer needs HV Piston which needs HV motor. As you can see, it's a problem. 
Unless I'm missing something?

**Comment by Dream-Master** [comment]
Yes I know this. I can post here a updated Gregtech Version to prevent this problem. Will be fixed in the next upgrade.

**Comment by Yeti-one** [comment]
No problem. 
Was just making sure you were aware of it. 
Thanks.

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/4cb19i4d2p9fgdn/gregtech-5.08.33.17.jar?dl=0

Gregtech 5.08.33.17custom

**Comment by Yeti-one** [comment]
Can report that has fixed the problem. Appreciated.
