### ISSUE TITLE
Two Advanced coke oven brick recipes, blast furnace won't use the oxygen recipe

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#591]
There are two advanced coke oven brick recipes in the blast furnace.  One uses half as much EU in exchange for requiring 2000 oxygen.  However, if you provide oxygen, the blast furnace does not use it, defaulting to the recipe that uses more EU.

**Comment by Dream-Master** [comment]
Maybe EBF handle only 1000 mb. Will try this or remove one recipe.

**Comment by McFrugal** [comment]
Another possibility is that the order of the recipes matters.  The Soularium ingot recipe will accept oxygen, and the oxygen-using recipe shows up first in NEI.  The Pulsating Iron ingot has the same problem the advanced coke oven bricks have... both of those have a non-oxygen recipe first in NEI.

**Comment by Dream-Master** [comment]
Advenced Cokeoven Bricks works in Single player both recipes.

**Comment by Dream-Master** [comment]
Ok i get the same problem with Soularium. Try to fix it now.

**Comment by Dream-Master** [comment]
I think i fix it. Need Gt 5.08.33.18 for it.
