### ISSUE TITLE
Unnatural Hunger results in black screen

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#594]
With the current optifine settings on my computer, Unnatural Hunger gives me a black screen. I fixed this by turning off "Fast Render".  This also fixed the issue I had with glowing bees, where the background behind the bees glowed too, and when they were offscreen in a file cabinet the entire screen glowed.  (also file cabinets are laggy with lots of bees in them, even if I ban file cabinets from holoinventory)

Apparently it has something to do with shaders?  Unnatural Hunger uses a shader for its red screen effect.

**Comment by Dream-Master** [comment]
In the public pack i will add Optifine only as optional mod. A new Version HD4 is available maybe this version fix it ?

**Comment by Dream-Master** [comment]
Please test with OptifineD4 now in the Update 1.0.8.3

**Comment by Dream-Master** [comment]
no one complains so done i guess.
