### ISSUE TITLE
World Accelerator reipe

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#596]
What a recipe the World Accelerator need?

**Comment by Namikon** [comment]
A good question indeed. Most mods with such a ability have rather expensive/endgame recipes.
However: As Gregtech has all the variants from early to late-game voltage, and thus the WA is also available in various power-stages, there should be appropriate recipes for all of them

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/15449794/4244518e-1f88-11e6-8386-45bd8ed76e87.png)

**Comment by Dream-Master** [comment]
Need Core Mod 1.1.40 for it.
