### ISSUE TITLE
Soy/Tofu tweak.

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#601]
Add new item recipes.

Soy beans -> compressor -> Wet Tofu (add this item to Coremod)

Wet Tofu -> centrifuge -> Firm tofu, soy milk

**Comment by Dream-Master** [comment]
@Technus sure i can add it. Can you make same nice texture for it ?

**Comment by Technus** [comment]
Should be done, tommorow when i have time.

**Comment by Dream-Master** [comment]
np will add it tomorrow.

**Comment by Technus** [comment]
![image](https://cloud.githubusercontent.com/assets/4737429/15408131/e3a125aa-1e0e-11e6-9a12-d77496e012b6.png)

**Comment by Technus** [comment]
check if it is correct if not remove background

**Comment by Technus** [comment]
![tofu](https://cloud.githubusercontent.com/assets/4737429/15408304/de86422a-1e0f-11e6-9508-917195400303.png)

**Comment by Dream-Master** [comment]
ok will do a recipe for it in the next update.

**Comment by Dream-Master** [comment]
compressor won't work because thre is a plant ball recipe in it alllready. I using a nother machine.

**Comment by Dream-Master** [comment]
I read in the Wiki soya beans are taken in water overnight and later they get pressed to Tofu. MAybe a assembler reipe with water and soya beans ore ok.

**Comment by Goofyschooler** [comment]
@dream-Master an idea for it could be to have them drop the soybeans in water and after a certain amount of ticks it changes to wet tofu then in a presser (believe pams has one) turns into tofu. Applied energistics does this with fluix crystals.

**Comment by Dream-Master** [comment]
Sure if i am an advanced Java Programmer why not. Sorry i not have the knowledge to do it by my self.

**Comment by Goofyschooler** [comment]
Haha it was just an idea. If it's not plausible then it's not plausible

**Comment by Nenluen** [comment]
Wouldn't a mixer be a bit more of an appropriate machine than an assembling machine?

Being normally filled with water (at least in my base) i can see the beans sitting in the water until it spins up to press them.

It also seems to be more in line with 'machine that helps make food' given it's status with Dough.

**Comment by Dream-Master** [comment]
sure can change that

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/23297472/ea95e8b2-fa79-11e6-8f59-de56893c93cc.png)
