### ISSUE TITLE
Server crash - Special mobs

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/NewHorizons#603]
http://pastebin.com/hguzcUiz

I attached a special mob witch of domination with a tinkers cutlass and the server went down.

**Comment by Dream-Master** [comment]
A nother user reported this bug too so nt sure if we can do much about it. Special Mobs isnt open source and Father Toast not post anything in the Forum since Jan. 2016.

**Comment by Dream-Master** [comment]
Nothing i can do here. If happend again please reopen.
