### ISSUE TITLE
Blood Magic Tweaks

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#604]
Blood magic has been a neglected mod because of the extremely low cost:benefit ratio. Complex spell systems are also not enough to kill even the big slimes (unless an extremely powerful and potent spell is made, which consumes ludicrous amounts of blood and items); and with the difficulty at GT level, maybe its effects could be twerked a bit to favour the players a little?
It'd be worth it to explore the field as well...
Well, if I were feeling diabolical, I would link further progress in the mod to Blood Magic spell system as well!

**Comment by Dream-Master** [comment]
Blood magic is open source so we can change things there. I not played much with this mod so not sure what we need to change here. Make some suggestions.

https://github.com/WayofTime/BloodMagic

**Comment by SanMan911** [comment]
Okay, cool. No worries.
I'll have a look at it in SP ofc and let you know by the end of this weekend.

**Comment by Goofyschooler** [comment]
I've been writing scripts for blood magic but been taken over by life that I haven't been able to finish a decent amount. On my test pack of it I keep I've teired each of the levels of altar. So tier 1 through 3 is hv. 4 though 5 are ev (I think that's next) and 6 is the next one. Can't remember what I made the blood orbs. And I upped alot of the stats for spells because they are pointless compared to other abilities in damage.

**Comment by Dream-Master** [comment]
The Blood Altar needs to be a Thaumcraft Infused item but with a different recipe not that what i copy from a nother mod.

**Comment by SanMan911** [comment]
@Dream-Master Yeah, blood altar could do with an infusion recipe. The other blocks of blood magic need not be needed. However, could the block toppings required, such as glowstone, bloodstone, etc be replaced by some 'technical' blocks that can only be crafted in a particular tier?

@Goofyschooler I was wondering if Level 1-2 could be made LV+, so as soon as you can do Thaumcraft, you can 'start' with blood magic (after completing the infusion research and having the stabilizers, of course), 3 onwards make it equal with the GT tier... like, level 3 in MV, 4 in HV and so on and so forth?
That'd make sure people can't just continue with a single favourite mod.... Like I said to Dream above, you could make it so the 4 block toppings are only in their respective GT stages...

What say?

**Comment by Dream-Master** [comment]
After i am done with De recipe i will take care of Blood Magic and the Addon Mod Blood Arsenal.

**Comment by Dream-Master** [comment]
@SanMan911 , @Goofyschooler 
Ok from today on i am on the Blood Magic scripts. If we need to change Code or Values i need more Infos from you.

**Comment by Dream-Master** [comment]
Ok close this because no one suggest anything.
@SanMan911 Blood Altar structure changes allready via config
@Goofyschooler I am nearly done with the scripts so nothing to do here any more.
If BM is finsih i need you to testing the new recipes.

**Comment by SanMan911** [comment]
@DreamMasterXXL I was only concerned about increasing the damage done by both the simple and complex spells, and maybe add some buffs to the BM armour, just to make the mod worthy of doing it, because normally also, it isn't worth taking all the pain for, and with needed recipes, it'd be even more pointless/futile if some 'encouragement' isn't given to do the mod. Tbh, the only reason I used to even do BM hitherto, was just to get till tier 4 for the teleposers. I never went for the spell system once I realized in sp how pathetic the damage of the spell system was....

P.S.: Sorry for the late reply.

**Comment by Dream-Master** [comment]
Ok this is to general for me. I have to know which spell you mean exacltly and i am not sure with my limited java knowledege i can change there stuff without braking things and make it worth more.

**Comment by SanMan911** [comment]
Okay, so the spell system of Blood Magic is 'customizeable', just like its potions. I will make one of each system in the test server today in around 6 hrs. from now, and message you the coordinates, so check it out then. It will be easier to explain when you see it.

**Comment by Dream-Master** [comment]
Ok.

**Comment by Dream-Master** [comment]
@SanMan911 Any news here ?

**Comment by Dream-Master** [comment]
A lot of Text but no reults.
