### ISSUE TITLE
Thaumcraft Inventory Scanning

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#609]
How about we add the TC Inventory Scanning mod in our next update?
It has MIT License, and can be redistributed in modpacks, so essentially, no permissions required.
Kinda makes TC a bit less messy, particularly with the tonnes of different ores and machines and parts/spares that GT adds.
Maybe we could have a poll if there is no unanimous consensus? :)
Just a suggestion.... 

If this helps:
A mod which we only would have to throw in. It is optional on the client side, so only those people need install it who want the functionality.

Edit:
Retrieved the [link](http://minecraft.curseforge.com/projects/thaumcraft-inventory-scanning) which 'shows' it beautifully.

@GTNewHorizons/core @GTNewHorizons/developers

**Comment by Goofyschooler** [comment]
Is it server side? Like could I install it and join a server and shove every item in my base in my inventory and scan everything?

**Comment by SanMan911** [comment]
No, I don't think you can do that because I tried it myself first, but it doesn't do anything.
So basically, it is optional on the client side, but compulsory on the server side, I reckon.

**Comment by Goofyschooler** [comment]
So how does it "scan" do you have to have goggles of revealing or a thaumometer in your inventory?

**Comment by SanMan911** [comment]
Nopes, you just open your inventory, your chest, whatever.
You click on the thaumometer and start hovering over the items one by one and it scans them.
So basically, you don't need to puke the items out to scan them... which makes it kinda nifty & 'clean'....

**Comment by Goofyschooler** [comment]
Ohokay as long as it doesn't scan your whole inventory or chest in one go I approve. Not like me approving does much lol

**Comment by SanMan911** [comment]
No way! That'd be too op, like, super op! O.o
And well, still, it's good to discuss, right? ;)

**Comment by Dream-Master** [comment]
Please Vote : http://forum.gtnewhorizons.com/showthread.php?tid=199

**Comment by Dream-Master** [comment]
So far 23.5.16:

Yes = 4
No = 0

**Comment by Dream-Master** [comment]
Already in Version 1.0.8.5
