### ISSUE TITLE
Recipe Required

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#613]

**Comment by Dream-Master** [comment]
?

**Comment by SanMan911** [comment]
Sorry. I had opened the issue about recipe fixes earlier. I don't know whether it got your notice or not, but you fixed those in the next research. I thought I'd be able to wipe it off from here completely, but it still kept that empty issue there, so I closed it.
Just for the records, the recipes were about Avaratia mod and the Pam's tofu.

**Comment by Dream-Master** [comment]
ah ok.
