### ISSUE TITLE
Bugged TC Research?

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#614]
The research called "Wand Stability" in the Thaumic Machina tab of the Thaumonomicon consumes paper and ink, but does not give any research notes for it.
Bug, eh?

**Comment by Dream-Master** [comment]
Yes i know. I will fix it when i am on Minetweaker scripts.

**Comment by SanMan911** [comment]
Has the recipe been fixed yet?

**Comment by Dream-Master** [comment]
not now.

**Comment by Dream-Master** [comment]
let me do BM ready first.

**Comment by Dream-Master** [comment]
Ok this item is null thats why.

` item = new TMResearchItem("WAND_STABILITY", null, -10, -3, 0, new ResourceLocation("ThaumicMachina:textures/research/r_wand_stability.png"), false);`

**Comment by Dream-Master** [comment]
Quick fix so long i redone the recipes.

```
// --- Wand of Stability
mods.thaumcraft.Research.clearPages("WAND_STABILITY");
mods.thaumcraft.Research.addPage("WAND_STABILITY", "tm.research_page.WAND_STABILITY.1");
mods.thaumcraft.Research.addPage("WAND_STABILITY", "tm.research_page.WAND_STABILITY.2");
mods.thaumcraft.Research.addPage("WAND_STABILITY", "tm.research_page.WAND_STABILITY.3");
// -
mods.thaumcraft.Research.setAspects("WAND_STABILITY", "instrumentum 3, ordo 12, instrumentum 6, praecantatio 9");
mods.thaumcraft.Research.setComplexity("WAND_STABILITY", 3);
```
