### ISSUE TITLE
Gregtech tools have inaccurate durability bars

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/NewHorizons#615]
At half durability, a tool will display a much smaller durability bar.  Like 25% of the bar, or something.

**Comment by Dream-Master** [comment]
@McFrugal 
Can you post a screenshoot fom it please.

**Comment by McFrugal** [comment]
Ok, sure.
http://i.imgur.com/yoUERIb.png
Also this new HUD mod is even more obtrusive than the last... and almost all my quests just reset with the update... and the questbook spammed me with a bunch of completion notifications, some of which blacked out my screen, I assume because they occurred at the same time as I got a flux flu warp effect.

I'm kinda sick of wrestling with Better Questing, honestly.

**Comment by Dream-Master** [comment]
Ok the Textures looks like not are from GT. Did you using a texture pack ? Gt textures looks different and the  durability bar looks ok too. 

About the Quests:
You need to put the new Better Questing file json in your folder and hit the command /bq_admin default load. Now the new file is loaded and the old progressein still there. Works on my Server so.

**Comment by McFrugal** [comment]
I'm using the Unity and ZT GT5U resource packs, as recommended.

What is the name of the new json file, and where do I put it exactly?
When you say new json file do you mean the DefaultQuests.json in the betterquesting config directory?
Do I need to rename it when I move it?

**Comment by Dream-Master** [comment]
Normally you have one Default Quest json in the better Questing Folder with clean data and one file Questdata json in the save Folder with User data and Questfiles. Normally replace the file in there Better Questing Config Folder and try to hit /bq_admin default load.

But I hear from Prospercraft they have issues too. Maybe the Mod Dev are not ready with his version and we still need to wait for an new Update.

**Comment by McFrugal** [comment]
Okay, so... I take the QuestData.json file and put it in the config folder?  Then rename it to DefaultQuests?  Then use the command?

**Comment by Dream-Master** [comment]
No wait. You have to load the update file 1.0.8.4 and the new Questing file will be replace in the Better Questing Folder. try to hit ingame /bq_admin default laod. Thats it. New Quests old Progression date.

If not please repost here then i open up an new Issue an Better Questing Mods side.

**Comment by McFrugal** [comment]
Yeah, that didn't work.  In fact, it removed all progress I had retained.

**Comment by Dream-Master** [comment]
Ok the I guess the Version 101 not worked properly yet. Maybe we have to wait for an update.
Nothing i can do so far. You can eabled your progress Quest by Quest with a admin code but this isn't fun.

**Comment by Dream-Master** [comment]
But your Original Issue was GT Textures :)

**Comment by McFrugal** [comment]
Yeah, so I guess I'll close this.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/617
