### ISSUE TITLE
WAY too many Hud mods

### ISSUE THREAD

**Issue by Goofyschooler** [GTNewHorizons/NewHorizons#616]
<img src="https://cloud.githubusercontent.com/assets/17286580/15564164/f17de69a-22c3-11e6-85c2-bb3b23140660.png"> Also When you get hit or injured Red blobs pop up on the screen. any way to disable all of this nonsense? Oh and it lowered my fps 10-15 from my normal. and when looking at a sign another hud pops up taking up more space.  Oh and the added WAILA hud in the bottom right. Why do we need so many huds?

**Comment by Dream-Master** [comment]
You can disabled most of the things from this mod. There is a configure key in the video menu of your game. Maybe the key are used fro a nother mod already. If i am on a Computer i can  Say which key it is.

**Comment by Dream-Master** [comment]
And it is a client mod feel free to disabled it. We had a vote in the Forum and most of the people want this mod.

**Comment by Dream-Master** [comment]
@Goofyschooler 
Any news here? Can this be closed?

**Comment by Goofyschooler** [comment]
I just disabled the whole mod. Closing
