### ISSUE TITLE
Better Questing Book forgot the quests I had done

### ISSUE THREAD

**Issue by PatSimmons** [GTNewHorizons/NewHorizons#617]
![2016-05-26_11 56 14](https://cloud.githubusercontent.com/assets/19594311/15581190/5834f0ca-2339-11e6-98a2-49ffcd06cd32.png)

**Comment by Dream-Master** [comment]
Did you play on the Server or in Singleplayer mode.
Which version of Bettre Questing Mod do you using?
With the newest Version 101 it not happend if you or the server admin hit the commad /bg_admin default load.

**Comment by PatSimmons** [comment]
Both
101 I believe
I can't utilize commands, ask Goshen
You already know most of this, just putting this info here for documentation purposes

**Comment by Dream-Master** [comment]
Ok will an update will be there soon. Now Player data a separate saved and makes as reset impossible.

**Comment by McFrugal** [comment]
Running 1.0.8.5 I still have no progress in my quest book when I load my save.  The save is from before the change, so it's still not converting completed quests properly.  Is there a new way to convert progress or is it still just broken?

**Comment by Dream-Master** [comment]
Ok we get today an update which hopfully fix that issue. Will be solved in the next update.

**Comment by Dream-Master** [comment]
Fixed in the newest version. Be in the next update.

**Comment by McFrugal** [comment]
It still doesn't work!

**Comment by Dream-Master** [comment]
Did you using 1.0.8.6? Can you explain a bit what you did (load or save etc.)

**Comment by McFrugal** [comment]
I'm using 1.0.8.6.  I took my backup copy of QuestDatabase.json and put it in my save directory after deleting the faulty QuestProgress and QuestDatabase json files from the last time I tried to update.

I then updated, loaded my save, and no quests at all are marked as completed.  I get no quest completion spam, unlike the first attempt BQ made.  If I use "/bq_admin default load" then it gets even worse, where I can't even see quests beyond those immediately available to me.  Instead of being able to see that there's a quest after the wheat quest, there's nothing there.

**Comment by Dream-Master** [comment]
The progression data is save in the Questprogress.json. If you delete this file the progress is gone too.
In the QuestsDatabase.json are only the Quests.

**Comment by McFrugal** [comment]
The QuestDatabase.json I'm putting into my save folder is from before the split.  It has quest progress in it.

**Comment by Dream-Master** [comment]
not any more. The file is split in more files now. One progress, one Quests, one party etc.

**Comment by McFrugal** [comment]
I know that!  I'm telling you that I backed up the json that had my quest progress in it.

**Comment by Dream-Master** [comment]
Ok let me knoe if it works.

**Comment by McFrugal** [comment]
It does not.

**Comment by Dream-Master** [comment]
yes please do that because we dont have this issue.

**Comment by Dream-Master** [comment]
Ok after reading the issue i understand what you mean. The only way you can do open up the Quests naually or copy all progress Quest by Quest to this file.

**Comment by volume75** [comment]
What I have noticed is every time you load your save, your user gets a random ID number.dat file. Since the progress uses the ID number not the user name, the Mad doesn't detect the progress completed

**Comment by Dream-Master** [comment]
Will see if it is the same with Better Questing 2

**Comment by Namikon** [comment]
> What I have noticed is every time you load your save, your user gets a random ID number.dat file. Since the progress uses the ID number not the user name, the Mod doesn't detect the progress completed data with in the file

If you get a new UUID each time you login, then you are most likely playing with a cracked Version of Minecraft. That's the only reason that would explain a "dynamic" userID

**Comment by volume75** [comment]
OK thank-you will look into that concern
