### ISSUE TITLE
Remote Accessor (id:7048) vs. ingame IRC and /say Command

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#618]
(Ingame) IRC chat msg's and /say msg's show up additional times equal to the number of times that item was used.

Relogging resets the "use count" to 0.

Bug does not affect normal ingame player msg's or the automated broadcast. So chatting with other players ingame is flawless.

Needs to be tested of other types of msg's are broken.

**Comment by Technus** [comment]
https://github.com/Slikrick/RemoteIO - we could try this build instead

**Comment by Namikon** [comment]
Isn't the remote Accessor some sort of transvector interface on steroids?
Apparently I'm missing some vital Information to understand the problem. What exactly happened and why is it considered a bigMinor?

**Comment by Dream-Master** [comment]
Any news here ?
