### ISSUE TITLE
Put any Repeatable 'Turn-in' quests in a separate, unlocked tab. [Suggestion]

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#620]
Hello guys,

A Suggestion I thought of after discussions on the Prospercraft GTNH server, is that any quests that allow for a turn in of some materials, for others (for example, loot bag upgrades, or draconium ingots) should be presented in a new tab, and available for turn-in from the very start of the game.

Sometimes players prefer to explore their own path to progression, and don't follow the book, or unexpected events happen that reset the quest book, but the players still get to the level where they can turn in these quests easily enough, but are arbitrarily restricted.

This way, players can both easily access the turn-ins for the advance materials they need and also can check what is needed from the beginning to get some of those sweet end-game items, and can plot their path.

Thanks,
-Nenluen

**Comment by Namikon** [comment]
As mentioned in #619, this will most likely not happen. We don't want this pack to have a "rush through" mode. What we can do, to enable Server admins to choose the easy-mode and don't care about questbook progression, is to add a special minetweaker file which adds recipes for all those "quest-only" items we have, so you don't have to bother about the questbook at all.
