### ISSUE TITLE
Forestry Backpacks are unable to hold anything [Bug]

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#621]
Hello guys,

As tested with the Miner's Backpack (4674) and the Digger's Backpack (4676) neither are able to hold any of the common items one would expect to go into them, such as dirt, stone and gravel into the Digger's Backpack, crushed ore, powders and regular ore into the Miner's Backpack, neither with pickup upon walking over the items, nor with trying to put items directly into the bags.

Thanks,
-Nenluen

**Comment by Technus** [comment]
Afaik that requires adding the block ID into forestry config.

**Comment by Dream-Master** [comment]
before it was preconfigured why that now ?

**Comment by Technus** [comment]
Needs to be configured.
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/forestry/backpacks.cfg
