### ISSUE TITLE
Stop the 'Explode on Death' Mechanic

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#622]
Hey Guys,

This one is one of those Quality of Life suggestions, in that when all mobs die, or despawn, they have a chance of exploding.  Normally this is a surprise and slight annoyance when killing livestock, however there are times when it can get downright hazardous, or detrimental to the landscape.

I'm mostly talking about Creepers, more specifically Water and Dirt ones.  For when these mobs explode by the 'explode on death' mechanic, they leave behind their effects as if they exploded trying to kill the player. (the Silverfish laden sphere of watery doom, and clump of dirt, respectively).  Regular creepers also explode, but just leave their typical crater, which can still suck, if you kill one before it explodes, but it blows up anyway.

This mostly just leaves a nasty hazard for players around their base, but could come into mechanical conflict, when players are not using chunk protections (such as towny) and try to make use of mob grinders, with one of these spheres, clogging, or completely destroying a person's grinder.

Picture attached shows 3 'water creeper' spheres around Flint City on Prospercraft. (one west, one Northeast, one south-southwest), to date i have cleared over half a dozen of the water creeper spheres from just outside the city, all having detonated without a player nearby. And an uncounted number of dirt creeper, because they're much less annoying due to having no silverfish.

![2016-06-03_15 22 26](https://cloud.githubusercontent.com/assets/10765948/15791809/23436952-299f-11e6-8c40-194683fe04c3.png)

Thanks,
-Nenluen

(p.s. another effect, is when they blow up any 'ronin' subtype mobs damaged by the explosion teleport out of any grinder area, and often end up wandering around a base, but that is also just a minor annoyance)

**Comment by Namikon** [comment]
Heh, another SpecialMobs issue. Funny. We're probably never get rid of issues with this mod will we?
Anyways, you can easily disable the kamikaze revenge mode.
Change this to false on your server (Or have someone do it) And your problems will be gone: https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GTNewHorizons/angermod.cfg#L79
If this really relates to Angermod it will solve the issue. The explosion is set to don't cause terrain damage, but maybe it's some issue with SpecialMobs not verifying the correct "explosion state".

**Comment by Nenluen** [comment]
After much testing, I believe i found the answer... And it has nothing to do with either Special Mobs nor Angry Mobs... 

Enderminies (EnderIO) are hostile toward creepers.

Both readily spawn in the overworld, and should the creeper be strong enough to withstand a few 

hits from the endermini, it will explode, will all related effects.

![2016-06-04_15 46 44](https://cloud.githubusercontent.com/assets/10765948/15801990/948a949c-2a6b-11e6-9a79-3f3b9e5ad11c.png)
![2016-06-04_15 46 47](https://cloud.githubusercontent.com/assets/10765948/15801997/d8fa624c-2a6b-11e6-9fa4-6e1f438167dc.png)
![2016-06-04_15 50 52](https://cloud.githubusercontent.com/assets/10765948/15802010/213dd8e0-2a6c-11e6-91c6-dcd7cef60051.png)

**Comment by Nenluen** [comment]
Repeated testing showed that the Angrymobs on-death explosion, caused no block damage.

**Comment by Namikon** [comment]
That's good to know, thanks for the detailed analysis.
So the solution would be to disable Enderminies; We'll discuss that issue on IRC

**Comment by Dream-Master** [comment]
Maybe i have to check if there is any config for it.

**Comment by Dream-Master** [comment]
Ok maybe i need to disable Ender Minis.
