### ISSUE TITLE
Stainless Steel issue

### ISSUE THREAD

**Issue by AdrianIonut** [GTNewHorizons/NewHorizons#623]
The stainless steel recipe is bugged the oxygen does not get consumed, @Technus sugested to change the circuit board priority on the oxygen recipe to 1 and the normal one to 2.

**Comment by Technus** [comment]
I suggested to add integrated circuits to recipes - that way you can control which recipe is used.

program 1 - no oxy
program 2 - oxy

**Comment by Dream-Master** [comment]
Ok this is a good idea. Not sure if I can set a recipe inside the ebf which not consumed the Circuit.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/a874d9dd8875ebd421348866e88006fc0ed0c598

**Comment by Dream-Master** [comment]
Need  version GT 5.08.33.27

**Comment by Technus** [comment]
does this work as intended?

**Comment by Dream-Master** [comment]
yes

**Comment by Dream-Master** [comment]
only oxy using a circuit no oxy works normal without circuit.
