### ISSUE TITLE
Natura cotton seed recipe overwritten by Natura->Pam conversion recipe.

### ISSUE THREAD

**Issue by Booyadude** [GTNewHorizons/NewHorizons#624]
![2016-06-21 06_20_43-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/8705282/16227779/6d0a348a-3778-11e6-8ee5-e18ea0b34bda.jpg)

**Comment by Dream-Master** [comment]
Will look into it later.

**Comment by SanMan911** [comment]
I think it is just the gregifying nature, because I remember making seeds out of 2 or maybe 3 of those Pam's cotton in a crafting grid or something... I think it is totally fine...
