### ISSUE TITLE
Cobblestone Structure Pipe Disabled?

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#626]
As you know that this is just a structural pipe, no items can pass through it. it is a support pipe, which is used to 'connect' structures to redstone signals, make facades and all, so I was thinking if that item only may maybe be made craftable, it would really help.
Waiting for views.

P.S.: It is from the BuildCraft mod "BC Transport". Any item which completely replaces it, but also does **all** the exact same work is also welcome.

**Comment by Dream-Master** [comment]
Sure this pipe I can reactivate later.

**Comment by SanMan911** [comment]
Thanks a lot! :))
