### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/NewHorizons#627]
![2016-06-30_10 48 44](https://cloud.githubusercontent.com/assets/15316448/16482525/5cd6b7f2-3eb0-11e6-8f53-741e61bb663f.png)

what heppend

did the ud in the luncher to version 1.0.8.7 

sc shows 1.0.8.6

**Comment by Dream-Master** [comment]
1.0.8.7 is a testversion i check that later. An yes i have to update the id to 1.0.8.7.

**Comment by Dream-Master** [comment]
Thanks for testing my testversion.

Try Version 1.0.8.7a

**Comment by Dream-Master** [comment]
I test it it is fixed now.

**Comment by Ldmf** [comment]
np :) and good work at all i like the mod pack :)

**Comment by Dream-Master** [comment]
Thanks.

**Comment by Ldmf** [comment]
np if i funde more bug i will post them :D (mein englisch ist nicht so gut alternatif kann ich sie auch in deutsch schreiben ^^)

**Comment by Dream-Master** [comment]
besser. :) Ich verstehe sie ja.
