### ISSUE TITLE
Suggestion for the pams harvest craft machines be turned on

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#628]
So I noticed you guys had a lot of the machines from pams harvest crafted turned off unable to make etc, and I asked my friend whos on the server he told me its cause you have another way of making the ending product well aint that just lovely

its like ik you guys wanted to make your own recipes etc but when its early game satisfying food is hard to come by due to the making cost. its like yea you being able to use the item in the machines that take electricity is good and all but no one gonna get electricity in the first 2 weeks if they know nothing about the game.

the ones made by machines should be the end game pretty much cause later id be faster to make etc 
but early game players need that item that cost no electricity so they can survive early game like come on the game is difficult as it it trying  to stay alive with the after a  certain time period you cant eat said item even if your player is starving about to die and he wont eat that bake patoto.

so please consider it 
Death :)

**Comment by Dream-Master** [comment]
Which machines you mean i have to turn on ?

**Comment by Dream-Master** [comment]
I will redo the recipes a bit to be not need higher tier materials or machines.
Maybe i will add Quests.
