### ISSUE TITLE
Disenchanter [EarlyISH-Mid way]

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#629]
I was thinking if we could have a disenchanter a bit early in the game, because enchants like, say, Looting, or Sharpness, or say, Protection, etc don't have much role to play once we hit the current Draconic Evolution tier and its disenchanter... Maybe any block which takes, say, xp and durability damage to extract an enchantment out of an item could do for the beginning game, because the enchanter of even Thaumcraft is wayyy too inside the game, and not to forget that there are certain enchants which you can not get even with the osmotic enchanter.
Inviting suggestions/views...

**Comment by SanMan911** [comment]
Any updates/thoughts about it?

**Comment by Dream-Master** [comment]
I don't know another mod have a early game disenchanted.

**Comment by SanMan911** [comment]
Well, I know of an "Auto-Disenchanter" from MFR [MineFactory Reloaded] mod...

**Comment by Dream-Master** [comment]
Sure but I won't add this Mod. It change too much and add so much stuff we don't need. Any other mod you know?

**Comment by SanMan911** [comment]
No, but maybe you could then change the recipe of the disenchanter maybe to make it more accessible?
Like, using draconium ingots in some LV or MV machine to make it, because once a player reaches planet Pluto already and has neutronium, why would he want the Draconium to make the Draconic disenchanter of all the items?
I personally think this is really broken.

**Comment by Dream-Master** [comment]
Ok will look at it again. The problem is Draconium now need a high tier blast furnace to process. So a solution would be put no Draconium in the recipe. I can't say how pocketful the enchanter is. I mean fore Game balancing reasons.

**Comment by SanMan911** [comment]
True, but as the name suggests, it us only a disenchanter. What is kinda "OP" in this Draconic evolution thingy, is that it can pull out all the enchants of any item _without damaging_ the item, which is basically the difference between the Draconic disenchanter and the one that I had suggested as an alternative.
I believe that disenchanter actually has work only in the earlyish-mid way because once people get Quantum or Kami, they don't need fire protection or feather falling or Aqua affinity or even 'protection', so yes, if you can make it possible to damage, say, 1/3 of the item when an enchant is plugged out, awesome; yet if you can't, not much harm done, I guess...
I'll post a few snaps in a couple of hours when am back on my system.

**Comment by Dream-Master** [comment]
I can only change recipe. The Game mechanics i cant really touche or i need to ask OneEyeMaker.

**Comment by SanMan911** [comment]
Okay, so just for the records, seems like the draconic disenchanter gives a 40% damage to the item being disenchanted, so only a recipe fix should suffice :))
See [this](http://prntscr.com/bz8ohn).

**Comment by Dream-Master** [comment]
Maybe a Thaumcaft recipe after the Enchanting Table would be nice.

**Comment by SanMan911** [comment]
Looks pretty good!
Thanks for considering it :))

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/17440956/2daad788-5b2f-11e6-86f9-41d861e679e8.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/17440966/37856e62-5b2f-11e6-979a-9fcaf58bbad5.png)

**Comment by SanMan911** [comment]
lol yeah, I saw the commit, that's why I said it looks good ;D
Thanks again!
