### ISSUE TITLE
Broken Quest

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#630]
The quest to find all types of gardens, make 128*2 tofu and some healthy food to get the HEALING AXE is kinda broken.
Part 3/3 of retrieval task requires some amount of rainbow curry and sausage in a bread. Now, where maple trees are kinda rare to find, even in BiomesO'Plenty, the tree from Pam's Harvest Craft is even more rare... which makes making the sausage not easy to make... also, the rainbow curry shows no recipe in the NEI. I'll however test in SP if the rainbow curry is a Thaumcraft item or not, and if it IS, then it would be veryy late in, because I've completed all the non-warp-giving researches, and have not found it still.
Expect an update in a couple of hours when I get back.

Update: Updated with the Questing reward to make it easy to identify.

**Comment by Dream-Master** [comment]
Will look into it later.
