### ISSUE TITLE
Gloves for fire resistance are buggy as hell

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#631]
I have started another single player world to test the new quests ect. and now I am at the point where I need to get lava for my smeltery.
I have the gloves on and it says I got fire resistance (but most of the time 0:00 if you look in the inventory) but I keep getting damage. Don't ask me if I got them the wrong way around or anything, I know how they "work".

I would suggest to fix them or remove the lava damage feature tbh, the other ways to transport lava (tanks with dollies or putting the buckes in a backpack) are fully bypassing the mechanic anyways and make it feel like an inconsistent feature that is just to fuck with you.

And no I don't think it is too hard or anything, I crafted the gloves and they don't work at all and that is pretty bad news imo.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/16670989/4c1aba4c-449d-11e6-92f2-d959bb537945.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/16671049/9d32981e-449d-11e6-8c26-7263e6d158bb.png)

**Comment by WarlordWossman** [comment]
I tried it multiple times with the gloves in the same slots and it does give me fire resistance but I still get damage, I haven't tried restarting the game, maybe that will fix it.

**Comment by WarlordWossman** [comment]
Okay it works after I restarted the game, did exactly nothing different.
Really weird.

**Comment by Dream-Master** [comment]
Nice.
