### ISSUE TITLE
Broken Thaum Quest

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#633]
After progressing a bit in Thaumcraft researches, there are quests which require us to build golden caps, greatwood wand, get lich bones & make stainless steel screws (only crafting table works, it doesn't register screws taken out from machines), it unlocks another quest to make a <<"50 vis storage" wand>>. Now, this also requires you to make yet another iron capped wooden wand (25 vis storage, 10% penalty), when it should require to make a gold capped greatwood wand logically.

**Comment by Dream-Master** [comment]
Hopfully fixed in the next Version.

**Comment by SanMan911** [comment]
I'll test it and let you (all) know.
