### ISSUE TITLE
Thaumcraft, oh! Thaumcraft...

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#634]
Well, now the questing is fixed, but after the gold capped wand quest, the next quest is once again broken..
So the next quest requires one to make the pillars and the runic matrix for the infusion, which requires 40 vis of each type. Shouldn't be a problem with the gold banded Greatwood wand which can hold 50 vis and has zero penalty, right? Wrong! lol
Now, the gold capped greatwood wand has an even more vis penalty than even an iron capped wooden wand :/
                           Then:                                        Now
Iron cap:        10% Penalty                           10% Penalty
Gold cap          0    Penalty                           30% Penalty (wtf?! lol)
So even though greatwood wand can store 50 vis, making the runic matrix is now impossible since now the recipe requires 52 Vis [40 Original + 30% penalty]. Since any wand better than the Greatwood wand requires infusion, and infusion requires the runic matrix, well.....

Edit: Even if we think of crafting scepters, it is still impossible because a single scepter requires 50 base of every vis.. With the penalty costs, it goes up to 65, which no wand without infusion can hold... :/

**Comment by Dream-Master** [comment]
Relax and come down I will see what I can do or change:)

**Comment by Dream-Master** [comment]
@SanMan911 
Did it work now?

**Comment by SanMan911** [comment]
@Dream Yeah, it works now, albeit it gives me a 100% vis cost, that is, no penalty, but no discount while it should give me a 5% vis discount. Anyways, since it worked and is not something that's a huge big loss, I guess I'm okay with it, thanks :))
