### ISSUE TITLE
Quest book suggestion

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#635]
Every time when you open a book, it opens not on the last page you were on, but the front page. Because sometimes you open a book 10-20 times per quest, this thing becomes very annoying.

Also right now you are unable to view the recipe of an item that quest requires. Right clicking on it doesn't open NEI and this was very convenient.

**Comment by Dream-Master** [comment]
@nikitinalexx 
If i am in a Quest and when i reopen the bock the page not changing so i can't reproduce this.
The Nei thing you have to report to Better Questing Mod directly.
https://github.com/Funwayguy/BetterQuesting/issues

**Comment by SanMan911** [comment]
@Dream-Master Hang on, I'd be posting the detailed analysis in here in a couple of hours when am back home.
Rarely the page remains there, but mostly, it goes back to the first page as @Nikitinalexx correctly mentioned.

**Comment by Dream-Master** [comment]
I think i know what you mean. I am not sure if i can change there anything it is in the BQ Code. Maybe open up a issue there.
https://github.com/Funwayguy/BetterQuesting/issues

**Comment by Dream-Master** [comment]
Ok linked it to BQ Mod Issues.

**Comment by Dream-Master** [comment]
OK Nei support is added Thanks to @FunWayGuy

**Comment by Dream-Master** [comment]
So what we need to test if the Books works same on the server and the client forgetting the last page.

**Comment by Dream-Master** [comment]
The mod get a total rewrite so lets wait for a new version.
