### ISSUE TITLE
5 bronze plate quest

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#639]
It doesn't accept plates made in Bending Machine, only made with Hammer.
The same for Iron plates.
For quests that require a lot of plates this bug makes you lose tons of resources.

The same for other quest required things if they were made with machines. For example Iron rod made in Basic Lathe

**Comment by Dream-Master** [comment]
@nikitinalexx 
Look here:

https://github.com/GTNewHorizons/NewHorizons/issues/619

**Comment by SanMan911** [comment]
@Dream-Master I believe what @Nikitinalexx is trying to say, is NOT about retrieval or crafting (which is talked about in the referenced thread), but making the crafting accept items out of machines as well, not just manual crafting.
I remember experiencing the same problem as well...

**Comment by nikitinalexx** [comment]
@SanMan911, yes, exactly. The linked thread says "You can't complete quests with items that you found somewhere else or if somebody gave you them"
And what i'm saying is
"I crafted the items myself using a machine and the quest did not accept them".

**Comment by SanMan911** [comment]
Yes, sir. I got your point; "Been there, done that", you know ;D

Anyways, do you also play on ProsperCraft, or you got your own server?

**Comment by Dream-Master** [comment]
The problem is you did the Quest in a Age where you past BBF. The Quest are designs for new players starting from 0.
I guess all Quests till Steam age are crafting Quest that you not cheat trough. At Lv Quest the Quests are retrieval Quests. I sadly not can build a trigger for players be far in the game and restart all Quests. Namikon is the Main Quest maker and he won't change all the Quests be retrieval instead of crafting Quests.

**Comment by nikitinalexx** [comment]
I thought making Bronze Plates in a Rolling Machine is considered "crafting" and not "retrieval".

**Comment by Dream-Master** [comment]
Sure I can set this Quest to retrieval but I am sure other Quests will follow. Will ask Namikon about it and maybe change these quest.

**Comment by Dream-Master** [comment]
Ok because of 196 Bronze Plates i will do this Quest a retrieval Quest.

**Comment by Dream-Master** [comment]
It was allready a retrieval Quest. Maybe i have to reload Quests on the Server.
