### ISSUE TITLE
Tier 1 Steam - "Wire-wrap quest"

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/NewHorizons#640]
This quest requires Mold(Plate), but in fact Mold(Plate) is not required to make Rubber Sheet anymore.

**Comment by nikitinalexx** [comment]
My bad, it still requires. Just the whole line to get Rubber Sheet got much longer.

**Comment by Dream-Master** [comment]
Yes i  will rewrite the quest a bit later to show people need sulfur. Maybe add as quest reward a bit extra  sulfur or rubber.
