### ISSUE TITLE
Worldgen / Loot rebalance?

### ISSUE THREAD

**Issue by NorthernWard** [GTNewHorizons/NewHorizons#641]
So I was thinking about the early game, and I can see a lot of effort was put into slowing down the early game through both resource requirements and creative additions like the modified seared ingot recipe, but a lot of this is invalidated by the availability of bountiful worldgen. A quick trip to the closest village almost guarantees a free set of Tinkers' Crafting blocks, and a fairly large Smeltery. Something that would take much more time and effort to obtain using the customized recipes. It pains me to see the work that went into crafting this experience undercut so quickly. Obviously this is just one person's suggestion, but I'd personally like to see Tinkers' worldgen chance turned way down, or ideally disabled entirely to maintain a "all done by hand" feel to the pack.

Secondly, and this is a more controversial suggestion, but I've always felt the huge number of valuable metals made available by Gregtech's chest loot additions were out of place in... well, Gregtech packs. Probably sounds silly, I know, but often times when entering the Steel age, you can have anywhere between half a stack to a few stacks of free Steel, depending on how much looting you did. So instead of building your Bronze Blast Furnace and excitedly grabbing out your first Steel ingot, it becomes just another one on the pile. To me this once again, cuts into the "all done by hand" feel, where you feel accomplished in the fact that you got to where you are purely through your own work and wit.

That's always felt like what Gregtech's gameplay changes were meant to achieve to me. Not just random nerfing for no reason, but to give a sense of accomplishment by overcoming them.  That's just my own point of view though, maybe I'm just projecting too much onto the pack.

*If* the metal loot were to change though, it would obviously require some things to take their place in the loot table. I can't think of too much right off the top of the head, but the best fit for dungeon loot to me tends to be useful things, with a limited number of uses. So something like a short Regen III potion. Good enough to be useful in a few situations, but doesn't really mess up progression. I'm sure there are a ton of more creative options from mods that fit the bill.

Sorry for the wall of text, I'm just pretty invested in the pack since it is the most thoroughly crafted and cared for GT pack I've yet to have the pleasure of playing. Naturally this is all just the ramblings of some random player, so don't hesitate to disregard it, and I hope I haven't overstepped any boundaries or stepped on anyone's toes by trying to push for a potentially unwanted playstyle. After all, if allowing players to boost through parts of the early game is intended, that's absolutely fine, I just thought I'd come check and throw my thoughts in. :)

**Comment by Dream-Master** [comment]
I totally agree with you but I made the pack for many different people and if there is not loot like steel or other Stuff to progress faster I guess more people will quit earlier and never come back. If you play with RWG the Villages appear not so often then with Bop or vanilla and I can live with it people looting some villages and get some early game steel. You have to do 1000 of Steel Ingots in the game so let's have people a bit the "Wow I find some good stuff  Effect" when they found some stuff. 
Yes you can loot a Tico smeltery but you not get the Quest done and any reward. If I made the pack only for me I am disabled many loot already. 
Maybe I have to think about the loot table mod to change maybe the amount a bit.

**Comment by NorthernWard** [comment]
I'm happy just to hear you agree, and I totally understand that you have to keep it that way to appeal to more players. I had the same problems when playing just with friends, haha. No worries, it was nice to get it off my chest anyway. You're right, I'll try to think bigger than the early game scraps of steel, after all it's gonna take a lot more to really get anywhere good.
