### ISSUE TITLE
questID: 28

### ISSUE THREAD

**Issue by leftyde** [GTNewHorizons/NewHorizons#642]
"description": "With your new acquired fuel source, you are now ready to process more advanced materials than stone or clay; Iron or copper, for example. Just in care you don\u0027t know, they spawn in rather large veins. Use the following quests to search and locate the most important veins you\u0027ll need"

Sollte doch eher "Just in case" anstatt "Just in care"

**Comment by Dream-Master** [comment]
Ja da müssen wir alle noch mal drüber lesen. Sind noch mehr Fehler hier.
