### ISSUE TITLE
Tin Cable Recipe

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#643]
The current tin cable recipe, unlike the other cable recipes, cannot be made in the assembling machine using molten rubber. Please fix it because as of now, it can be made only from rubber sheet in a crafting grid or in a packager. Please add the recipe to make it craftable using assembling machine.

**Comment by Dream-Master** [comment]
Will cahnge that.

**Comment by Dream-Master** [comment]
Fix: https://github.com/GTNewHorizons/GT5-Unofficial/commit/eeab702de4c84effbe22fd0a78b96deae1a31def

**Comment by SanMan911** [comment]
Thanks. Much appreciated :)).

**Comment by Dream-Master** [comment]
Please let it open till fix. Thanks.
