### ISSUE TITLE
Thaumcraft issues/suggestions.

### ISSUE THREAD

**Issue by EinSchurke** [GTNewHorizons/NewHorizons#644]
Hello there, DummeMaske here.
There were some problems with thaumcraft i encountered, aswell as ideas id like to suggest.

First the problems. These are for the version 1,8,8c, while playing on the US server, so you might have adressed those already.
1. The research "advanced golems" shows the recipe of golemic shielding.
2. Killing enemies with the "Thaumic Revolver" makes certain enemies (e.g. the lich, zombies) not drop
special loot. (in the lich's case his bones, which occured to 4 lichs i killed, no bones.)
Zombies do not drop brains when shot.
3. In the GT-New Horizons google table there are rods named which actually can be crafted, but not turned into wands/scepters. (e.g. thaumic wand rod, transmutative wand rod, void wand rod)
4. Sometimes entities in the "Curative Vat" despawn. (skeleton horse for example)
5. "Ore Destruction" from Thaumic Bases does not work with the infused stones from Gregtech.
6. Electro-magnetic tools need many items/machines from IC2 which are disabled.

Suggestions:
The magic energy converter recipees are strange. Each machine needs parts from higher tiers, while the machine hull itself is from the respective tier. (a 32(LV) machine needs a (LV)hull but (MV) sensors)
Doesnt really make sense. Id suggest lowering the requesites (An (LV) energy converter needs a (LV) machine hull and (LV) sensors).
Same with higher converters.

I also find it strange that many advanced cores need nether stars, especially the alchemy core, since he got one in the decanting infusion already. Though i can see the need for a harder recipe on those cores, id suggest to take items given by thaumcraft itself, such as "Cured Zombie Brains" for more complex cores.

The Inventarium. A good thaumcraft player can create an inventarium very soon, while making it nearly as effective as a ME system. It seriously needs more complex recipees.

And thats about it. I hope i could help with this and wish you a good time.

**Comment by Dream-Master** [comment]
A few Thaumcraft Mods are left so i will nerf this too soon.
Game Play mechanic i cant change or fix bugs.
To 1. This i can. fix.

**Comment by Dream-Master** [comment]
The research "advanced golems" shows the recipe of golemic shielding because i change the recipe an the book shows only the first possible recipe. Runic Shielding using NBT data too so thats why it shows the recipe. i am not sure what i can do here.
