### ISSUE TITLE
High pressure steel boiler

### ISSUE THREAD

**Issue by EinSchurke** [GTNewHorizons/NewHorizons#645]
Macerating the high pressure boiler tank gives 6 steel dust, while the recipe only needs 3,5 steel per boiler.

**Comment by EinSchurke** [comment]
same with low pressure.

**Comment by Dream-Master** [comment]
This are Railcraft Blocks and i change the recipe via Minetweaker not via GT code. Will change it in the GT Cod then to give the right Materials back.

**Comment by Dream-Master** [comment]
Fixed need GT 5.09.22.29 for it.

**Comment by Dream-Master** [comment]
Need newest Core Mod too 1.1.67
