### ISSUE TITLE
Broken OreSpawn in the TF

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#646]
Limonite (Both brown & yellow), Malachite & Banded iron veins were found in the Twilight Forest when they are not supposed to spawn there, at least according to the excel document.

**Comment by Dream-Master** [comment]
Will look into it later.

**Comment by SanMan911** [comment]
Thanks.

**Comment by Dream-Master** [comment]
You not need to close this if o merged this to master it will auto close it.
