### ISSUE TITLE
Aura Core (Gadomancy) Request

### ISSUE THREAD

**Issue by EinSchurke** [GTNewHorizons/NewHorizons#648]
-From a mod not nerfed yet-
The Aura Core recipe is broken.  Upon using any Crystal cluster in the recipe the client crashes (twice, once right after and a second time when reconnecting, tried this with a pause of several hours in between, no change). After that you will be able to reconnect, only to find that the core you get is an earth core all the time. (Earth cores are unused by any recipe, other than making it blank again)

My request is to change the recipe from a "multiblock" ( you have to place the cluster into the world and throw the core next to it, and click it with a wand after that) to a arcane table recipe once you start nerfing Gadomancy. This should prevent both the crashes aswell as getting the wrong core.

**Comment by Dream-Master** [comment]
New version is available. Look at the text if this is fixed .

http://minecraft.curseforge.com/projects/gadomancy/files/2314158

**Comment by EinSchurke** [comment]
might fix getting the wrong core, yes. but i wonder if this fixes the crashing issue. 
I tried it in SP but it only occured after i tried about 3 times, while it happened on the MP server all the time.

**Comment by Dream-Master** [comment]
Ok then better post the issue on the Gadomancy issue page.

**Comment by Dream-Master** [comment]
https://github.com/makeoo/Gadomancy/issues/70

**Comment by Dream-Master** [comment]
OK you need to make the different core in different regions. Water Cores on the Water, Lava core near to water etc. Earth Core not have any use yet. I not test it on the Server but i will as soon as possible.(After the next update with new Version).

@EinSchurke 
Read this:
http://ftbwiki.org/Aura_Core

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/23dfb56c0ebdbc3071c74c87203e7165
