### ISSUE TITLE
Needs Attention

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#651]
1. Bibliocraft mod [used to make copies of enchanted books] recipes have NOT been nerfed yet. Could do with only a bit of nerfing, not too much. Consider replacing Iron with Thaumium.

2. Mine n' Blade battlegear icons are able to safely keep/hold lava buckets without doing any damage. Maybe a bug. However, it might also have been designed that way so people can still keep their regular amulets on them, and can choose to keep lava or their weapons in the slot.

**Comment by Dream-Master** [comment]
Ok Thanks will have a look.

**Comment by SanMan911** [comment]
Thanks!
Closing this as it was resolved.

**Comment by Dream-Master** [comment]
@SanMan911 
Please not close it before it is resolved via Technic Launcher means in the next version. If i cant see it i cant test it when i am published and test the next version.

**Comment by SanMan911** [comment]
Ah! Okay, sorry. I just thought a small script reload would do for the recipes so closed it.

**Comment by Dream-Master** [comment]
No i will do more recipe like :
https://github.com/GTNewHorizons/NewHorizons/issues/545

**Comment by SanMan911** [comment]
lol I'll translate the German when I get back on my system, but sure thing. It could be updated alongwith the disenchanter recipe.
