### ISSUE TITLE
MumbleLink CPU leak?

### ISSUE THREAD

**Issue by NorthernWard** [GTNewHorizons/NewHorizons#653]
MumbleLink seems to be using excessive CPU resources, even when idle. Simply opening the pack and leaving it on the main menu sees it chewing through a full CPU thread trying to do... something. Disabling the mod and opening the pack again returns the pack to using ~0% CPU on the main menu.

I suspect it's looking for a mic or something (and freaking out because I don't have one.), but there is the possibility that it is having some kind of conflict with drivers on my side. Maybe some others can test with/without mics.

Personally I have no problem disabling it manually, but if it is an issue for people other than myself, and potentially anyone without a mic, I think it would be wise to include it with the pack, but disabled by default.

I realize that disabling it would be annoying for those who do use it, but I also worry that new users users will open the pack and be confused when they get poor performance due to MumbleLink eating CPU cycles.

**Comment by Dream-Master** [comment]
Maybe i remove this mod and all this people using the mod can add it manually.

**Comment by Dream-Master** [comment]
Ok removed.
