### ISSUE TITLE
Tinkers defence we cant update.

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#654]
I wait for a fix.

https://github.com/Lance5057/Tinkers-Defense/issues/29

**Comment by Technus** [comment]
Seem resolved
https://github.com/Lance5057/Tinkers-Defense/issues/29

**Comment by Dream-Master** [comment]
Lance5057
"I gotta do some testing to make sure its solid but atm windows keeps forcing a broken update so I can't use my computer very much. Hope to have it up before Friday."

**Comment by Dream-Master** [comment]
1.3.7 is out and can be tested next update.
Need to rework some items and stuff.

**Comment by Dream-Master** [comment]
Still more crashes.

**Comment by Dream-Master** [comment]
Sadly there is no fix. I hope @Technus you can fix some thing in this mod to using never version.

**Comment by Dream-Master** [comment]
The mod is so unfinisehd and so buggy. I think we stay at 1.2.1 and i will add more recipe for the missing Shields.
