### ISSUE TITLE
issue after update

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#655]
im experiencing a issue that is very annoying 

so the issue i having is a gui interface issue when you look into your inventory its glitching out all items even wore and the upper tabs for armor and what not.   and not enough items is disapearing to and idk what is causing it and it only happen after the update

**Comment by deathxfighter** [comment]
![image](https://cloud.githubusercontent.com/assets/20245730/17460779/c0deb520-5c41-11e6-89f7-55a3a238a3ed.png)

**Comment by deathxfighter** [comment]
![image](https://cloud.githubusercontent.com/assets/20245730/17460781/d2ad34d4-5c41-11e6-946e-7406066c2886.png)

**Comment by Dream-Master** [comment]
Fit you hit o? There is a key to hide nei but hide your items is new for me.

**Comment by deathxfighter** [comment]
its not o
its literally glitching

**Comment by Dream-Master** [comment]
Did you using other mods that are not in the pack? Like optifine etc...

**Comment by Dream-Master** [comment]
Need fml log from you. And Computer specs.

**Comment by deathxfighter** [comment]
im not using any other mods only the mod pack

**Comment by deathxfighter** [comment]
tec told me to do a clean install of the pack and I did and get on same issue

**Comment by Dream-Master** [comment]
How often it glitch away? Give me some log please (fml lastest)

**Comment by Wildmage0** [comment]
I am playing on a private server and have had this issue when wearing an adventure backpack. It fixes if you take off the backpack. Removing and putting it back on can sometimes keep it from happening. This would also spawn artifacts on screen for myself and players around me. 
![2016-07-29_17 56 16](https://cloud.githubusercontent.com/assets/20892021/17464821/0018222c-5ca5-11e6-9886-ed03db21455d.png)

**Comment by Dream-Master** [comment]
@Wildmage0 
Thanks for the Info. Maby I have to ask the Author from this mod.

**Comment by deathxfighter** [comment]
well the issue finally stopped after the i had to update when i open minecraft and now its running pretty smooth idk if it was that last update or something?

**Comment by Dream-Master** [comment]
so then i close this.
