### ISSUE TITLE
GalaxySpace update to 1.10+

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#656]
- [x] Compare all Ores on Planets
- [x] Check if all Stuff works (Galacticgreg Code)
- [x] Compare all Plates (missing or additional Ores/Stuff) (Vega, Humea, Makemake and Barnards need Ores)
- [x] Compare all Rocket Tiers
- [x] remove NASA workbench and replace with Avaritia Table to be more free with Components
- [x] Check all missed or added items (minetweaker)
- [x] Added back Ores and Materials via GT Code
- [x] Rocket reverse recipe
- [x] Planet Dust ByProducts
- [x] Check all Quests (Materials and Monster Bosses)

**Comment by Technus** [comment]
Dream you can remove all the galaxyspace dimensions that we already have, (everything above actual tier 3), and replace them with new ones, unless the process is more complicated.

**Comment by Dream-Master** [comment]
yes will do because new ore mixes.

**Comment by Dream-Master** [comment]
Ok so Deimos, Ceres and Phobos need a cleanup. Maybe i cut off onle the Base on the planets because most of the Rock and Stone material ids changed too.

**Comment by Technus** [comment]
Anything but spacestations and moon could be cleaned
