### ISSUE TITLE
Wired! #67

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#657]
The named quest wants you to craft 6 copper cable which is not possible anymore as you can only use the assembler and the alloy smelter.

**Comment by Dream-Master** [comment]
I fix it. Try the command /bq_admin default load

**Comment by Dream-Master** [comment]
@WarlordWossman 
And it works for you now ?
Can i close this?

**Comment by WarlordWossman** [comment]
No it doesn't work it's still a crafting task and you can't craft copper cables ...

**Comment by Dream-Master** [comment]
I guess you play sp. The new Version 1.0.9.1 have a new questing file. I think you are using a old one because this issue was fixed. I look later in it again.

**Comment by Dream-Master** [comment]
As you can see Quest was fixed.

![image](https://cloud.githubusercontent.com/assets/2970688/17490481/4909b6d6-5da3-11e6-8d9e-f080fd74e7ba.png)

**Comment by WarlordWossman** [comment]
Strange, is there a way for me to fix it in my current singleplayer world?

**Comment by Dream-Master** [comment]
There are many ways. Try with  load or save again. You can remove the file from you save game folder and reset all. Now you can finished the Quests you did already manually in the edit mod with a tool there.

**Comment by Dream-Master** [comment]
/bq_admin default load or /bq_admin default save

or after delete the file

/bq_admin reset all

edit Mod:

/bg_admin edit

**Comment by Dream-Master** [comment]
@WarlordWossman did it work ? Can i close this?
