### ISSUE TITLE
BUFFS & NERFS : Suggestion

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#659]
Okay, let me proffer some suggestions as to what all could be buffed, and what all, nerfed:
**NERF:**
1. BiblioCrat
I believe I've already suggested that earlier, but just a quick reminder if you haven't already
2. Nuclear Reactor
100x is too op and pushes people to invariably stick with it, without looking for other power avenues
3. Hell Hounds
Always infernal needs to go. [Quick reminder again, if you haven't done already]
4. Gendustry
Mark the caps, it's TOOO OP! The components are maybe not buffed much in the beginning, but it also again takes the fun out of building apiaries & alvearies; and pushes everyone to go gendustry... Increase the usage cost and nerf some more, if you deem fit.

**BUFF:**
1. Other modes of energy generation, even if by only 10x...
2. Loot in the dungeons as suggested earlier already by @deathxfighter in another thread #658 

Inviting suggestions & comments from everyone.

**Comment by Technus** [comment]
NERF:
2. Nuclear, from what i can tell even 20x buff of nuke was op around 10x is enough
4. Gendustry, make the energy acceptor for gendustry require Osmium or even better an osmium comb.

**Additionally:**

BUFF:
3. Reverse recipes for GT Coil blocks and TiCo Metal Blocks.

**Comment by Dream-Master** [comment]
Biblio Craft has a low priority. I nerfed the Book Copy Blocks but feel free to add some recipe by yourself.
Nuclear Control is 10X so i guess its not to OP. If i can change that the MultiBlock Reactor get more power and the easy reactor less i do this allready.
Hellhounds get not always infernal in the next Update.
Gendustry is OP mod sure. I will add some Bees to the recipe that can only breed with high Tier Bees.
Maybe put the Machine recipe to Avaritia 9x9 Table.

Are coil blocks not have a reverse recipe. If not i will add some.

**Comment by Dream-Master** [comment]
Engineer Tec - Today at 9:24 PM
nuclear reactor core should require titanium

**Comment by Technus** [comment]
Coil reverse - only applies to Superconductor Coil block - just regular shapeless crafting back to wire should do.

**Comment by Dream-Master** [comment]
- [ ]

**Comment by SanMan911** [comment]
Make nuclear require Titanium [/b] AND/OR [/b] a tier 2 Item.
Buff up wind/solar generation 10x to maintain parity with nuclear.... for people who prefer to go fuelless... The down side would be they won't be able to generate at night, but it would give players more options and flexibility to choose from.
Make the gendustry require some speciality of a high tier bees.... to balance the mod and to make people go the usual way using Apiaries & Escritore :D

**Comment by Technus** [comment]
Added to do on top.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/545

**Comment by Dream-Master** [comment]
I close this. We can open new issues for it.
