### ISSUE TITLE
recipe change please [Extra Utilities Item Filter]

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#662]
Item filter   from extra utilites.

i think it should be changed cause the cost is to much for something that only can filter a number of items etc    the only thing that i should be changed on it is the diamond gear cause that takes 8 diamonds to make and there is no cheaper thing to help sort stuff in a base when you need to make at least 10 item filters

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Technus** [comment]
(Use EnderIO item conduits with item filters. way cheaper...)

**Comment by deathxfighter** [comment]
tec ik i want the enderI0 for getting stuff outta chest but i wanna sort items by mod then by what they are so we cna have all ingots,ores, parts, dust in one area and rest in a different

**Comment by deathxfighter** [comment]
bump

**Comment by deathxfighter** [comment]
@Dream-Master can it be changed to like a steel or a iron gear? cause i honestly need alot of these

**Comment by Dream-Master** [comment]
Yes will change the Gear but better to (Alu) or Stainless Steel.

**Comment by deathxfighter** [comment]
Alu would be nice

**Comment by Dream-Master** [comment]
Adding Stainless Steel Alu is to soft :)

**Comment by deathxfighter** [comment]
when will the change be made?

**Comment by Dream-Master** [comment]
I fixed this in my dev pack and it will be available in the next update. If I not get any problems with other stuff I am done this weekend.
