### ISSUE TITLE
TubeStuff Mod suggestion

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#664]
Just for the sake of one block called - player detector.

Infinite range (even interdimensional), since it uses a method based on - "is player logged in to server". (It basically locks to the player  that placed that block.)
Great for disabling any machine setup while offline.

**Comment by Dream-Master** [comment]
The idea is good but for one Block we need a new Mod with Items we dont use. I am not sure if we need the Core Mod too (Immibis). Maybe its possible to make a Block with Open Computers?

**Comment by Technus** [comment]
There seems to be online detector.
