### ISSUE TITLE
Issues with the adventure backpack mod

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#665]
The issue is tht every now and then it would glitch my inventory, armor, inventory items. And tabs. For other players like bou bou and sanman991 it glitches their screen where they can see for a period of time.

When i take the backpack off they said it stopped 

And ik its a problem but i dont want to get rid of such a handy backpack :/

**Comment by Dream-Master** [comment]
I asking the Mod Dev and waiting for an answer.

**Comment by Dream-Master** [comment]
@runescapejohn need pics from this issue.

**Comment by Dream-Master** [comment]
So i guess a other item or block cause this. We cant do anything here i guess.
