### ISSUE TITLE
GT Teleporter not Interdimentional

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#666]
As the title says, the GT teleporter inter-dimensional teleportation is disabled to apparently prevent you from skipping tiers or something like that. Dimensional transport is a very useful feature that I was hoping to use to allow easy transport between planets/moons for more efficient ore gathering to avoid having to take a rocket or use the Stargate system to get to space.

**Comment by deathxfighter** [comment]
hmmm i like this idea

**Comment by Dream-Master** [comment]
Did you have to visit the Place before (Planet/Moon) or can you jump to any place you like?

**Comment by Dream-Master** [comment]
If the discribtion is right you can skip tier with it. Maybe i have to change the Block "Dragon Egg" to some more high tier Block. Using a inter Dim Teleporter is ok but you have to reach a certain Tier first.

**Comment by Technus** [comment]
#549

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Teleporter.java#L212

**Comment by Technus** [comment]
3179:2 Block of neutronium

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/14

https://github.com/GTNewHorizons/NewHorizons/issues/674

**Comment by Technus** [comment]
@Dream-Master the change u pushed works. The required block is now neutronium block (otherwise u need nitrogen plasma - default thing)

**Comment by Dream-Master** [comment]
Ok nice should we change the Plasma too? Or the Block?

**Comment by Technus** [comment]
Plasma too.

**Comment by Dream-Master** [comment]
@Technus Iron Plasma? You changed many values like amount and some math stuff i not understand thats why i not merged it. Can you do a new pull request only with the plasma values and a small explain that i understand it too. Thanks

**Comment by Dream-Master** [comment]
Ok changed it to Iron Plasma Tier 3 Fusion.

**Comment by Dream-Master** [comment]
Gt Teleporter is now very Expencive. Using Telepad or Ic2 Teleporter so long you reach the Tier.
