### ISSUE TITLE
turn on refinery 

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#667]
literally so annoyed with how fuel is made -_-  
there is a reason why its made in a refinery cause that is logical like god ,please turn it on
like the NEI got me so turned around getting so confused and want to rip my hair out
oil being filtered makes fuel 
you guys are making it more hassle than its worth

**Comment by Technus** [comment]
Single block gregtech distillery - sulfuric fuels - burn that
