### ISSUE TITLE
Thaumic Bases Issue

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#668]
Smoking tobacco from this mod causes the nearby players to crash hard to their desktop. I've tried it using both greatwood and silverwood fume pipes, same effect. Could be used to troll people.
Requires a fix.

**Comment by Dream-Master** [comment]
This Mod is available for MC 1.8.9 so we not get any fix here.

**Comment by Dream-Master** [comment]
If some one will write a fix:

https://github.com/Modbder/ThaumicBases/tree/master

**Comment by Technus** [comment]
https://github.com/Modbder/ThaumicBases/commit/2e7c69b521d949cec74e2c6ce86564b88342e278
That it?

**Comment by Technus** [comment]
I bet no the commit is old...

**Comment by Dream-Master** [comment]
But this seems to be it only we have to move it to 1.7.10 branch

**Comment by Dream-Master** [comment]
Without a crash log i cant fix it.
