### ISSUE TITLE
Electro Magic Tools

### ISSUE THREAD

**Issue by SanMan911** [GTNewHorizons/NewHorizons#669]
Order Infused Triple Compressed solar panels should technically output 3,072 EU/tick as promised, but when tested on an AFSU OR the MFSU with an EU reader, it says to be outputting only 2,048 EU/tick.
However, this is not the upper limit or cap because when another solar panel is put on another side, the output increases to 4,096 EU/tick.
See [http://prntscr.com/c6ok8t](here) for the proof from the 1 Triple Compressed solar.
Needs to be fixed.

**Comment by deathxfighter** [comment]
definitely need this fixed

**Comment by Dream-Master** [comment]
This Mod is un-nerfed and need to be redone.

**Comment by Dream-Master** [comment]
If someone has nice configs then we reopen it.

**Comment by Technus** [comment]
I fixed the issues with >2048 eu/t
