### ISSUE TITLE
Ends of IC2 mining pipe becoming useless fix.

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#670]
We need a crafting recipe to turn 208 back into 207 if possible please :3

**Comment by Dream-Master** [comment]
Need Core Mod 1.1.85 for it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/17792002/c85f7be8-659e-11e6-8994-eea189a02fd8.png)
