### ISSUE TITLE
Galaxy Space Moon/Planet Dust [NEED YOUR HELP]

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#676]
I will add for every single Planet and Moon a Dust like i did for the Moon, Mars or Asteroids.
This dust when macerated give byproducts.

I want you suggestions here.

**Comment by Dream-Master** [comment]
No one ?

**Comment by Technus** [comment]
Would be nice to have a GalactiCraft/GalaxySpace Rocket Tier/Gregtech Tier/Planet triplets (a table showing what planet is what GT and GS tier)

**Comment by Dream-Master** [comment]
https://docs.google.com/spreadsheets/d/1sRroNCV_4JpxrgKNivrOnSi-vz_-TX-a1-ll6WhwBJs/edit#gid=1348574161

**Comment by Muramasa-** [comment]
Maybe centrifuging the rock dusts for a rare chance to get a tiny pile of a rare resource or maybe some sort of gas.

**Comment by Technus** [comment]
Yeah like helium (more than u can get from endstone) from mercury stone dust. Also dream could you make a list of added dusts?

**Comment by Dream-Master** [comment]
Yes i will and Tier 1-5 allready done but i guess you can help me a bit and some ByProducts i will change again
