### ISSUE TITLE
suggestion for solar panels Gregtech

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#677]
one solar panel takes the predecessor solar panel to be created can we change this so it doesnt use the old one or make a 2nd recipe so a solar panel can be made without its predecessor cause it would help and might let people choose other power options

**Comment by Technus** [comment]
Imho solars from greg are still op getting a greg UV panel is way easier than whole fusion reactor that makes 2/3 of UV packet. (still reactor is usefull for other things but the amount of shit required is insane)

**Comment by deathxfighter** [comment]
you still cant make the EV above unless you hit mars

**Comment by Dream-Master** [comment]
Ok what i need to change here?

**Comment by deathxfighter** [comment]
the part where you need the previous solar panel to make the item can we just change it to where its a different item?
@Dream-Master

**Comment by Dream-Master** [comment]
Why?

**Comment by deathxfighter** [comment]
cause the cost after a while will be too much

**Comment by Dream-Master** [comment]
As Tec says getting a greg UV panel is way easier than whole fusion reactor.

Solar is Free Power and this have his price.

**Comment by deathxfighter** [comment]
ok then how about i go nucular and make 100 mox 1s and get 200k power easier?

**Comment by deathxfighter** [comment]
ok how about you get on MC and make solar panels it cost alot already dont want to be making many damn predacessors to make 1 item like really

**Comment by Technus** [comment]
@Dream-Master i would approve for avaritia recipes for solars above EV

**Comment by Dream-Master** [comment]
So let me understand first what is bad here. The recipe? the balance? any thing else? 
And how i can balance it i think there is no config for it. Codewise ?

**Comment by Technus** [comment]
will look into power gens when i get time

**Comment by Dream-Master** [comment]
recipes added.

https://github.com/GTNewHorizons/NewHorizons/issues/710
