### ISSUE TITLE
Add better description for gloves and/or lava buckets.

### ISSUE THREAD

**Issue by sehesak** [GTNewHorizons/NewHorizons#679]
the issues is that , when grab lava with bucket (clay or iron )  bucket start hurting even if I have glove on myself
glove doesn't give the protection and even if sometimes give the fire protection bucket hurting anyway

**Comment by Technus** [comment]
u need both gloves

**Comment by sehesak** [comment]
Yes, this I know and I have both in baubles. left and right gloves, but still when I put lava bucket to inventory, then constantly get damage and kill me 
and most of the time, fire resistance is not appear.
and sometimes appear and still hurting me

**Comment by Dream-Master** [comment]
You need it in your Hand not only in the Inventory.

**Comment by sehesak** [comment]
Oh, I am very very sorry. I start test world and testing whole problem in differents way and working like You say. When I grab lava with bucket and stay hand hold the bucket, I get little hurt and then is activate fire resistance buff and stay to  9 second until I change slot or put lava things from inventory out.
Sorry for this mess and thanks for explanation

**Comment by Technus** [comment]
Reopened since that type of question was aksed like 3rd time.

Dream if u can add more desciption to gloves and/or lava buckets/cells

**Comment by Dream-Master** [comment]
How? With some tooltip?

**Comment by Technus** [comment]
Yes tooltip
