### ISSUE TITLE
Everburn Urn fix

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#681]
https://github.com/nekosune/Thaumic_Exploration/issues/40

Dream would be nice  if u could branch and compile with the changes.

afaik you still have to import some TC API file.

**Comment by Dream-Master** [comment]
Ok will do.

**Comment by Dream-Master** [comment]
@Technus 
Please Test it.

https://github.com/GTNewHorizons/Thaumic_Exploration/releases/tag/1.1.56

**Comment by tvanderka** [comment]
You made a typo with "ticks=0" being in the wrong place, it disabled the urn completely. Move it up 1 line and it works fine.

I also suggest replacing "extends TileVisRelay" with "extends TileThaumcraft" so it does not act like a vis relay, works better this way.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/Thaumic_Exploration/pull/1

**Comment by Dream-Master** [comment]
Merged will compile anew version.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Thaumic_Exploration/releases/tag/1.1.57

**Comment by Technus** [comment]
Seems fixed,  (i have that issue in my base on line server i could test on that when the updates comes)

**Comment by Walkman100** [comment]
It's fixed as in the client no longer crashes, but on my setup with Thaumic Exploration v1.1.57 it still acts as a vis relay. It draws CV in blobs like any other machine (Infernal Furnace, Focal Manipulator e.t.c.), but it still connects to vis relays.

I can provide version info/logs/screenshots if that'd help, but I doubt it's anything funny on my end, probably a simple line of code or two to remove (sorry not a java coder or I'd make a PR).

**Comment by Dream-Master** [comment]
Try with version 1.1.71

**Comment by Dream-Master** [comment]
[Thaumic-Exploration-.1.7.10.1.1.71-0.zip](https://github.com/GTNewHorizons/NewHorizons/files/1596037/Thaumic-Exploration-.1.7.10.1.1.71-0.zip)

**Comment by Walkman100** [comment]
using `Thaumic-Exploration-.1.7.10.1.1.71-0.jar` from the zip above I get this loading a world:

![image](https://user-images.githubusercontent.com/5454764/34570848-a5af58fc-f175-11e7-8e35-8fd316593ed5.png)
(was previously using [`ThaumicExploration-1.7.10-1.1-57.jar`](https://github.com/GTNewHorizons/Thaumic_Exploration/releases/tag/1.1.57)

I click yes and the world loads fine, however after staring at an everburn urn seemingly working normally (and not acting as a vis relay) after a few seconds my game crashed (looks like a generic error to me). (OpenEye report: http://openeye.openmods.info/crashes/1714de7b6bc68c9687f4c01bc2e2131a)

Upon reloading the world and removing an replacing the urns, all seems well. The urns now only store 2 buckets of lava and sputter annoying particles even when it's doing nothing though... they also seem to produce half the amount of lava...

Not sure if I'll use it on my server, but thanks for the option. You should upload these builds (57 and 71) to curse, I'm sure others will appreciate not having to dig through GitHub to find them :D

**Comment by Dream-Master** [comment]
Ok thanks for testings but i am not the Mod Author of the original Mod not the Mod Author make the fix. I can link the version.

**Comment by Dream-Master** [comment]
https://github.com/KryptonCaptain/Thaumic_Exploration/releases
@Walkman100
