### ISSUE TITLE
Biome mismatch/overlap unable to change world type

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#683]
When creating a new world in SSP river biome is shown as mercury, might be not the only one broken.
Also it is impossible to change the world generator to super flat or anything else than RWG Alpha.

**Comment by Dream-Master** [comment]
This will be fixed with Galaxy space  1.10

**Comment by Dream-Master** [comment]
This I locked via a Mod(default worldgen) to prevent that players loading other world. Oil ,villages and other Things are only well balanced when rwg is on.

**Comment by Technus** [comment]
What mod is that?

**Comment by Dream-Master** [comment]
Default worldgen. You can Chance the configs.
