### ISSUE TITLE
Infernal mobs... again

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#684]
Posible things to get disabled.

Rust: Causes high amounts of wear on weapons and armour when fought.
- makes electric armor loose durability nearly instantly (since electric armor does not use durability but EU nbt), things like nano wings, electric boots of traveler are being destroyed.

Sticky: Can snatch the items the player attacks it with. 
- moderate evil just use ranged weapon

Lifesteal: Heals from attacking.
Vengeance: Reflects a portion of all damage done back at the player.
- pick one combo of that is impossible to kill

**Comment by Dream-Master** [comment]
Yes ik then we have to change the source code.

**Comment by Technus** [comment]
B:"MM_1UP enabled"=false             - enable
    B:"MM_Alchemist enabled"=true
    B:"MM_Berserk enabled"=true
    B:"MM_Blastoff enabled"=true
    B:"MM_Bulwark enabled"=true
    B:"MM_Choke enabled"=true
    B:"MM_Cloaking enabled"=true
    B:"MM_Darkness enabled"=true
    B:"MM_Ender enabled"=false
    B:"MM_Exhaust enabled"=true
    B:"MM_Fiery enabled"=true
    B:"MM_Ghastly enabled"=true
    B:"MM_Gravity enabled"=true
    B:"MM_Lifesteal enabled"=true      - disable
    B:"MM_Ninja enabled"=true
    B:"MM_Poisonous enabled"=true
    B:"MM_Quicksand enabled"=true
    B:"MM_Regen enabled"=false        - re enable
    B:"MM_Rust enabled"=true            - disable
    B:"MM_Sapper enabled"=true
    B:"MM_Sprint enabled"=true
    B:"MM_Sticky enabled"=false           - nice was already done
    B:"MM_Storm enabled"=true
    B:"MM_Vengeance enabled"=true
    B:"MM_Weakness enabled"=true
    B:"MM_Webber enabled"=true
    B:"MM_Wither enabled"=true

**Comment by Technus** [comment]
proposed change to infernalmobs.cfg

**Comment by Dream-Master** [comment]
If regen is disabled some Mobs are unkillable.
1Up i not sure why we disabled it but i guess because someone complain about it.
Rust i have to look into it.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/pull/689

**Comment by Technus** [comment]
Regen allows the mobs to passively gain hp, you just need better weapon to kill em.

**Comment by Technus** [comment]
Field test to check if the death issues are gone.
