### ISSUE TITLE
Adding materials to planets

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#685]
Adding Material to Planets .

**Comment by Dream-Master** [comment]
Adding Infinity on  Alpha Centauri adding Draconium Awakened on  Barnards  and Unstable and Bedrockium on Vega.

**Comment by Technus** [comment]
https://docs.google.com/spreadsheets/d/1sRroNCV_4JpxrgKNivrOnSi-vz_-TX-a1-ll6WhwBJs/edit#gid=1821686091

**Comment by Technus** [comment]
@Dream-Master 
moved:
Infinity now Infinity Catalyst.

![image](https://cloud.githubusercontent.com/assets/2970688/18120668/fc128c70-6f60-11e6-88ab-d0401a948bdc.png)
