### ISSUE TITLE
Gendustry "rebalance"

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#686]
Powermodule should require this to be crafted:
- Naquadah Comb - mixed with neutronium ->bee catalyst

Industrial Apiary 
- instead od power module make it require IV energy hatch - this is not an op block in gendustry - somewhat equal to alveary from forestry

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/659

**Comment by Dream-Master** [comment]
I am on it.

**Comment by Technus** [comment]
The changes are not bad - since there is harder version of bee genetics available - genetics mod.

Still i would not hit the industial apiary that hard, it is like ~80% of forestry alveary production wise and uses energy ~32EU/t (forestry alveary is a multiblock (bigger)and requires frames (items that break over time) )

**Comment by Dream-Master** [comment]
So what recipe do you suggest. Did the industial apiary works without the other items and stuff?

**Comment by Dream-Master** [comment]
Infinity now Infinity Catalyst.

![image](https://cloud.githubusercontent.com/assets/2970688/18120668/fc128c70-6f60-11e6-88ab-d0401a948bdc.png)

**Comment by Dream-Master** [comment]
Ok i lower the Apiar To Tier 2 Planets (Titanium and Tungstensteel)

![image](https://cloud.githubusercontent.com/assets/2970688/18121269/12a28bea-6f64-11e6-8d2c-0c3613900bdf.png)

**Comment by Dream-Master** [comment]
@Technus 
Is it possible to breed in the Industrial Apiary?

**Comment by Technus** [comment]
Yes it is but the beez need to meet the criteria. 
 - logic like any other forestry bee thing (besides bee house).

It can also take upgrades to emulate certain biomes.
 - like alveary.

**Comment by Dream-Master** [comment]
@Technus 
So balancing is now ok ?

**Comment by Technus** [comment]
it is better
