### ISSUE TITLE
Basaltic Mineral Sand

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#688]
Basaltic Mineral Sand is only processable in SAG mill.

**Comment by Dream-Master** [comment]
Ok will look into it and add recipe if necessary.

**Comment by Dream-Master** [comment]
Yes only Stone Ores not have any recipe.

**Comment by Technus** [comment]
Related #726

**Comment by Ugachaga** [comment]
Achievement is not given for lifting Basaltic Mineral Sand block, if it helps to catch the issue.

**Comment by Ugachaga** [comment]
Not sure if related (from GT6 changelog):
```
6.00.47
[FIXED] "oreBasalticMineralSand" being parsed into "oreBasalt" with the Material "icMineralsand", what resulted into a Situation similar to the one I had with "oreNetherQuartz"
```
