### ISSUE TITLE
Do we want this?

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#693]
https://github.com/CannibalVox/McDiscord/releases

**Comment by Dream-Master** [comment]
So we can link it to the Server commands via Bot like Prospercradt did ?
I like the Idea.
@Namikon 
Any security things that you against it?

**Comment by Namikon** [comment]
Not really, this is just another chat-mod that links discord to the server; And it seems to have support from Technic itself.
Another question would be, is the IRC integration still wanted/needed?

**Comment by Dream-Master** [comment]
I see this on Prospercraft and its handy. Ok we have irc but not all joined here so maybe we have to vote if we add it. For me it isnt a high priority thing only a nice to have function.

**Comment by Dream-Master** [comment]
Ok maybe with the Server change we can setup it.
@Namikon

**Comment by Dream-Master** [comment]
@Namikon 
I need Infos here if we add this Mod to the Server to link it to Dicord.
