### ISSUE TITLE
Transformers broken recipe

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#695]
Why don't transformers use any coils? Also why no wet transformers? Immersion triggered.

**Comment by Dream-Master** [comment]
Good Questions. The Coils i can add. For other stuff maybe @Technus know better.

**Comment by Technus** [comment]
The actual transformers - will be tre dry transformers and work as usual

I will later add another tile entity - wet transformer - 16 A at Tier+1  /64 A at Tier

**Comment by Technus** [comment]
My part done will rollout with new-tiers update

**Comment by Dream-Master** [comment]
@Technus Need your recipes suggestions.

**Comment by Technus** [comment]
they are in the source code... (i already told you posting a comment so i can feel better about myself)

**Comment by Dream-Master** [comment]
Ok will add soon.
