### ISSUE TITLE
IC2 Nano helmet / leggings Crafting Issus 

### ISSUE THREAD

**Issue by Elyspio** [GTNewHorizons/NewHorizons#696]
hi Staff, the recipe for the nano platted legging and the nano scuba helmet accept only the metadata 27 and we can only have metadata 26 (full empty) .. any fix for that ? (its maybe the same probs with Nano's Other Parts)

**Comment by Dream-Master** [comment]
Ok will test it.

**Comment by Dream-Master** [comment]
Nano Helm i can crafting and assemble no problem.

**Comment by Dream-Master** [comment]
Ok set Meta id to 26 aof all recipe hope that works.
