### ISSUE TITLE
Mars Boss not spawn

### ISSUE THREAD

**Issue by AdrianIonut** [GTNewHorizons/NewHorizons#697]
The Mars boss does not spawn, and some dungeons are broken they do not have a boss room.

**Comment by Drobac** [comment]
This is an issue with Galacticraft world generation, you come across a dungeon from time to time without a boss room. Are you sure the dungeon you went through wasnt cleared before?

**Comment by Dream-Master** [comment]
Yes no one was before there. And we test 2 or 3 Dungeons. I spawn some Creeper in that the Player can get a Tier 3 Key for the Chest.

**Comment by Dream-Master** [comment]
We need to generate some new Chuncks to test it.

**Comment by Dream-Master** [comment]
@Namikon Is this a Server only issue?

**Comment by Namikon** [comment]
No. As Drobac described, sometimes the Dungeons don't have a boss spawner.
On top of that, the old issue with stopped Server activity is still not solved. Working on that, but it will take more time to have a (potential) solution for that. This is not something that is easy to fix

**Comment by Dream-Master** [comment]
Ok thanks for info.

**Comment by Dream-Master** [comment]
@Drobac @AdrianIonut please test with newer version of GC in Fix Update 1.4.1.0 when available.

**Comment by Namikon** [comment]
As LavaMonsters is gone for the time being, and Entity numbers have stabilized, I removed the Mob-Limit on Delta. It won't fix the Dungeon problem, but definitely should fix the "no monsters spawn" issue.

**Comment by Dream-Master** [comment]
So no chance for Lava Monsters atm ?

**Comment by Namikon** [comment]
No

**Comment by Dream-Master** [comment]
Maybe its fixed in the newest version. So we need to test it with new generated chunks on Mars.

**Comment by Dream-Master** [comment]
It was fixed someone reported it to me.
