### ISSUE TITLE
Cannot craft WoodenBrickForm.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#699]
Cannot craft WoodenBrickForm (knife + blank pattern).

Have done two test cases:
Technic Launcher (1.0.9.2g) - cannot craft it and recipe is not shown in NEI.
Technic Laucnher (1.0.9.1b) - can craft it and recipe is shown in NEI.

Note: I did not try to do a full clean reinstall. I simply let Technic Launcher do it's update procedure when switching version - I am assuming it works without any issues.

**Comment by EvgenijM86** [comment]
There is also a lot of errors in CoreMod.zs when starting world (in 1.0.9.2b), like:

```
[11:23:13] [Client thread/INFO]: [CHAT] ERROR: CoreMod.zs:1927: Could not resolve <GalaxySpace : plutoblackplutonium>
[11:23:13] [Client thread/INFO]: [CHAT] ERROR: CoreMod.zs:2027: Could not resolve <GalaxySpace : item . QuantiumIgnot>
Error executing CoreMod.zs: Bad type on operand stack
```

More details - http://pastebin.com/p1jgh7GE

**Comment by Technus** [comment]
When switching versions it is recommended to remove config and scripts folder, otherwise shit happens.

//Solder is bad

**Comment by EvgenijM86** [comment]
Thanks for info, did not know that. I will try it out on 1.0.9.2g with deleting config and scripts now. I just tried 1.0.9.2c (without deleting config and scripts) and recipe worked.

**Comment by EvgenijM86** [comment]
I have removed:
~/.technic/modpacks/mcnewhorizons/config
~/.technic/modpacks/mcnewhorizons/scripts

Scripts directory have been recreated but was empty even after client start - is that normal? I tried "reinstall" button and it is still empty.
There is also a lot of .zs files in ~/.technic/modpacks/mcnewhorizons/. I do not understand why they are not placed inside scripts directory. I have deleted them just in case.

I still cannot craft it or see its recipe in NEI.

**Comment by Technus** [comment]
Assigning Dream he is more familiar with that thing.

**Comment by EvgenijM86** [comment]
Test summary (will update this, until I find the version which introduced that error):

1.0.9.1b - works
1.0.9.2c - works
1.0.9.2e - testing...
1.0.9.2g - fail

**Comment by EvgenijM86** [comment]
I have managed to fix this problem by moving all .zs files inside script folder. Now recipe shows in NEI. It seems when I switched version to newer one there were two sets of .zs files - one inside scripts directory (from older version) and one outside it (from newer). So it means that I used older scripts with newer version. That is why CoreMod.zs failed to load, probably.

**Comment by Technus** [comment]
Yes you are absolutely right, I reported to him that the scripts are improperly placed.

**Comment by Dream-Master** [comment]
Yea maybe some copy past error. Will fix that later.

**Comment by Dream-Master** [comment]
Version 1.0.9.2h fixt it.
