### ISSUE TITLE
Connection issues with a private server (1.0.9.2h)

### ISSUE THREAD

**Issue by Kataiser9** [GTNewHorizons/NewHorizons#700]
Trying to set up a small private server on 1.0.9.2h. (Couldn't find an actual server download for the latest version, so I manually updated the mods/scripts/configs.) Server and client launch fine, but when I attempt to join the server, I am immediately disconnected and the server spits out "java.io.IOException: String too big (was 105035 bytes encoded, max 32767)". Full pastebin of the join attempt [here.](http://pastebin.com/jLnn2e2z) It's not terribly useful, though, because the stacktrace stops before identifying where the issue could be.

I did a lot of googling around to try to fix this without much luck; I saw some stuff suggesting that it could be Lava Monsters, but disabling that mod didn't fix it.

(Sorry if this is the wrong place to ask. Let me know if you could use any more information.)

**Comment by Dream-Master** [comment]
@Kataiser9 
If you using additional Mods I can't give any guarantee that the modpack runs fine (Aroma Backup and Ex Nihilio)
I have a GTNH 1.0.9.2h running  Test Server without any issues. (1.0.9.2 is in the testing phase to goes live)
And by the way how can Ex Nihilio fit good to the pack so with un nerfed recipes. We have a lot of Gregtech veins and Ex Nihilio is a Mod if the resources are limited (Sky Blocks etc)

**Comment by Kataiser9** [comment]
Whoa, sorry, I should clarify. Ex Nihilo is NOT in there. (I double checked.) The only reason that phrase shows up in the logs is because NEI Addons has compat for it.

As for AromaBackup, I thought of that too, and I tried taking that and AromaCore out. No dice, I'm afraid.

Good to know that it's working for you though. I'll make sure I didn't put the wrong mod somewhere or something.

**Comment by Dream-Master** [comment]
Ok did you run a Server by yourself or did you try to join a server? Did you try a clean reinstall? Did you using Technic Launcher ? 
Fml logs from Client and Server would be nice too.

**Comment by Kataiser9** [comment]
I'm running both server and client on my own computer. Client is through Technic Launcher.

I did try a complete reinstall of both client and server. (In the case of the latter, I took the most recent available server download and manually updated scripts/configs/mods.) I've also tried running the server with and without Thermos - it doesn't seem to make a difference, although the error message I get is less specific when using Thermos.

Here's the most recent FML logs for server (with Thermos) and client, as requested. Couldn't use Pastebin because they were too large, so I had to change the file extension and attach them here.

[fml-server-latest.txt](https://github.com/GTNewHorizons/NewHorizons/files/478063/fml-server-latest.txt)
[fml-client-latest.txt](https://github.com/GTNewHorizons/NewHorizons/files/478065/fml-client-latest.txt)

Thanks for the help, I hope I haven't made some kind of stupid obvious mistake. (...and I apologize if that's the case.)

**Comment by Kataiser9** [comment]
On second thought - having exhausted most available options, it looks like I probably made some bizarre stupid mistake somewhere along the line, and it's probably not the pack's fault. I'm closing the issue, so don't worry about it further.

I'll post in this thread again if I ever find the cause.

**Comment by Dream-Master** [comment]
Ok let me know what is was.
