### ISSUE TITLE
Semi-stable ingot

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#703]
Alloy smelting unstable nuggets should give semi-stable ingot instead of unstable ingot.

**Comment by Dream-Master** [comment]
No better to remove this recipe because for semi stable Ingots you need the Advanced Sigil which is hard to make.

**Comment by Technus** [comment]
ehh, you needs the activated sigil to make unstable ingots and semi-stable nuggets.

The thing is: now i can craft semi-stable Ingots in crafting table from the nuggets, but alloy smelting gives unstable ingots.

**Comment by Dream-Master** [comment]
All works fine here so far i can say.
