### ISSUE TITLE
Trading system

### ISSUE THREAD

**Issue by AdrianIonut** [GTNewHorizons/NewHorizons#704]
Implement a new reward system that let's you trade 5 or more coins for basic resources like iron,tin,copper,redstone etc. Or useing the trade-o-mat.

**Comment by AdrianIonut** [comment]
This will help new players to actually try the modpack,finding ores with a flint pickaxe is a pain..

**Comment by EvgenijM86** [comment]
The amount of ingots that is needed for bronze blast furnace is 392. If you include other bronze machines it may go up to 500-600 ingots. I doubt that trading for 20-40 ingots will let you avoid searching for copper and tin ore veins.

**Comment by Technus** [comment]
And exploration is another feature in the modpack, still there are GT hammers to prospect.
