### ISSUE TITLE
Hungry Node Destroy graves

### ISSUE THREAD

**Issue by Elyspio** [GTNewHorizons/NewHorizons#705]
all is said, Thaumcraft Hungry node destroy the graves and annihilate stuff.. 

its in Twilight Forest : 
![screenshot_177](https://cloud.githubusercontent.com/assets/22132082/18638462/8c132cce-7e90-11e6-8258-c1c2007a7061.png)

**Comment by Technus** [comment]
Yeah it is a feature. @Dream-Master grave restore or we dont do it anymore?

**Comment by Dream-Master** [comment]
@Elyspio 
You need to be online for it.

**Comment by Dream-Master** [comment]
@Technus 
@Drobac 
using this command when he is on.
/ob_inventory restore Elyspio  inventory-Elyspio-2016-09-19_17.32.13-death-0.dat

**Comment by Technus** [comment]
@Dream-Master - permission denied, console only.

**Comment by Dream-Master** [comment]
@Technus 
Will ask Nami to change it to ingame for Admins.

**Comment by Technus** [comment]
But we still need SSH to get the filename

**Comment by Dream-Master** [comment]
k then we let it like it is.

**Comment by Dream-Master** [comment]
@Elyspio 
Contact me if you are online

**Comment by Elyspio** [comment]
@Dream-Master  I'm Online :)

**Comment by Dream-Master** [comment]
@Elyspio Why you leaving?

**Comment by Dream-Master** [comment]
ok fixed
