### ISSUE TITLE
Update Chisel 2

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#706]
Hi, would it be possible to update Chisel2 to the most recent and updated version for 1.7.10 please.

https://mods.curse.com/mc-mods/minecraft/235279-chisel

I am still using the recommended 1.0.9.1b version of the pack, so if this has been addressed already i apologize.

**Comment by Dream-Master** [comment]
I think we are using a different Version of Chisel (Chisel 2 by the Cricket)

**Comment by lilmoefow** [comment]
This updated version is compatible.

**Comment by Dream-Master** [comment]
Ok will try tomorrow.

**Comment by Dream-Master** [comment]
Ok in the new Update 1.0.9.2i.
