### ISSUE TITLE
Tier 2 Chandelier Quest

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#707]
Theres an issue with the Basic Monster Protection Quest in Tier 2 where one has to create a chandelier by putting a diamond and 5 torches along with 4 ingots of molten gold in the assembler. The molten gold can not be achieved in LV tier because the fluid extractor cant use LV (32) to work. it needs at least 51 as the reciepe tells.
Pleaase fix this or migrate the quest to tier 3

**Comment by Dream-Master** [comment]
Ok change it to molten tin 1440 mb
