### ISSUE TITLE
High Tier Solar Panels be in the Avaritia Table HV and up

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#710]
High Tier Solar Panels be in the Assmbly Line or Avaritia Table

**Comment by Drobac** [comment]
-1 :P.

**Comment by Dream-Master** [comment]
@Drobac 
Avaritia table?
Any idea?

**Comment by Drobac** [comment]
the reason i dont like either idea is they aren't automatable, but i might figure something out

**Comment by basdxz** [comment]
Avaritia sounds good to me since solar is 100% free power with 0% maintenance. Drobac is quite biased on the issue imo.

**Comment by Dream-Master** [comment]
Ok nice will think about some nice recipe aka Avarita Table :)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/2b473c959d6474e64749726d02f1a468ce27564d
