### ISSUE TITLE
Simple Solar Boiler Uncraftable (steam)

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#712]
The standard recipe for steam Solar Boiler is shown in NEI but doesn't work in crafting table.

![2016-09-21_13 30 19](https://cloud.githubusercontent.com/assets/8257735/18709306/d164d1ea-7fff-11e6-83cd-b0517953d9bf.png)
![2016-09-21_13 30 16](https://cloud.githubusercontent.com/assets/8257735/18709311/d55d8508-7fff-11e6-814e-20640730a2c1.png)

**Comment by Dream-Master** [comment]
Normaly they using glass on top. Not sure why nei not show it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/18709510/ccc9ae34-8000-11e6-8aea-4ea2403a375d.png)

**Comment by Dream-Master** [comment]
I guess you are using a Texture Pack maybe Glass not shown right ?

**Comment by Methes** [comment]
Aha! You're right!
I'm using Faithful and glass is almost invisible. Thanks :).
