### ISSUE TITLE
Quest updates needed

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#713]
Under kill all the things - switch Blaze Evolved ( TIer 3 Planet - Ceres) with Ghast Evolved Quests (Tier 4 planet -IO)

¸
Legendary Tier X - after "A hull" - neutronium ore doesnt trigger the next step

**Comment by Drobac** [comment]
Under Adept Thaumaturgy - "Armor" switch from crafting to retrieval task

**Comment by Drobac** [comment]
Under Tier 6 and beyond - "Clean" energy - change EnrichedNaquadahBolts with EnrichedNaquadahRods

**Comment by Dream-Master** [comment]
k

**Comment by Dream-Master** [comment]
@Drobac 
Any ting more to fix ?

**Comment by Drobac** [comment]
under Novice Thaumaturge "Infinite water!" quest is set to a crafting quests, need to switch to detection
under the KAMI quest line "Hold all the foci" - quests doesnt detect the bottomless pouch
