### ISSUE TITLE
Simple solar boiler does not consume water.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#714]
After filling it up with water and using it for a couple of hours I noticed that water level did not change - water gauge remained full despite producing all that steam.

**Comment by Dream-Master** [comment]
@Technus any idea.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/c3c85319c07b1561907ce835cff0f403b80266f2
