### ISSUE TITLE
Recipe changes

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#716]
Relocator - uses Teleporter in recipe (which needs an Infinity block to craft), also i suggest lowering the crafting to LuV tier so the player gets a reward for crafting and using the Assembly line

OD Scanner - Replace the meteoric steel plate with Stainless steel plate( Maybe even aluminium) so its available pre-moon. Its a bit pointless now because as soon as you get it you upgrade it to the OV one and would serve to reward the player for reaching stainless steel.
OV Scanner - Put meteoric steel in the recipe so it needs the moon.

**Comment by Dream-Master** [comment]
Relocator are trasportable Teleporter and you can skipp Rocket tiers. Thtas why it is so expencive.  Now you can find Inity Catalyst on Planets wich make crafting much easier. Maybe i can add raw infinity to some Tier 8 planets too but i am against to set it to Luv. (Maybe the Ininity Block in the Teleporter i can change but it stay UV Tier which using Ass line too)

OD and OV Scanner i will rewiew.

**Comment by Drobac** [comment]
They arent transportable Teleporters, as you need to visit a place and set the point before going there again (unlike teleporters which can do any dimension and can skip tiers)
