### ISSUE TITLE
Harvestcraft Rice is not plantable

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#719]
There is a conflict between Harvestcraft and Hunger Overhaul.   See issue here  MatrexsVigil/harvestcraft#14 .   

Setting this config option in Harvestcraft.cfg to False apparently fixes it.

B:enablecropspecialplanting=true

**Comment by Dream-Master** [comment]
So a false will enable it very crazy. Ok will test it. Next release.

**Comment by Technus** [comment]
Config Option: You can now disable special farmland needs of water crops
 - enablecropspecialplanting - 
Default: true (If true, seed planting doesn't work on farmland. If false, crop planting doesn't work on water. No matter how it's set, previously planted crops on water *only* will stay)

Plant on water...

**Comment by Technus** [comment]
Ading stupidness label, check what config does before changing it.

**Comment by Dream-Master** [comment]
??
