### ISSUE TITLE
Questbook MV Quest Ender not-so-IO

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#724]
You need Conductive Iron Ingots to finish this quest but for that you will need titanium. Titanium can only be grinded by being able to go to the moon which is in tier 4 (HV age)

**Comment by DietmarKracht** [comment]
Also the quest requires pulsating iron. An ebf with oxygen and cupronickel coils doesnt run. the reciepe says 1 pulsating iron dust need 1800K heat.

**Comment by Dream-Master** [comment]
I change Conductive Iron to using silver instead of Titranium.
You need a Circuit and oxygen to run it. If his recipe not using a circuit i need to fix it.

**Comment by Dream-Master** [comment]
Ok small pile of dust works but this is crazy why the other recipes not works.

**Comment by Dream-Master** [comment]
Ok If you run a LV EBF the max heat is 1700k and you cant make it so update to MV or higher.
Recipes works fine you need o put the dust and the circuit on the right palce. Fist dust then cuircuit. In my Test dev it works just fine.

**Comment by Technus** [comment]
heat cap = coil+(tier-1)*100

**Comment by DietmarKracht** [comment]
Still makes it an HV quest because you need at least kanthal coils => vacuum freezer => stainless steel

**Comment by Dream-Master** [comment]
Now you can make it with Tier 1 Coils again so i guess fixed now.
