### ISSUE TITLE
Suggestion for EBF

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#725]
Maybe add a reciepe for aluminum which uses oxygen and is therfore cheaper. That makes sense because to get oxygen you need the advanced electrolyzer which is made out of aluminum.
Correct me if i am wwrong

**Comment by Dream-Master** [comment]
I think oxygen and aluminium not works well together in the real world. If you can look in wiki and say me if there is another which match better i can add the recipe.

**Comment by Technus** [comment]
Yes we could speed up the process but that is how it is done irl:
![image](https://cloud.githubusercontent.com/assets/4737429/19416367/441ce3ec-938f-11e6-85d2-d65ee829fb6a.png)

**Comment by Dream-Master** [comment]
New recipe system available in newest GT version.
