### ISSUE TITLE
Nether star ore ( 1451:506 ) cannot be processed

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#726]
Only the vanilla stone variant of the nether star ore is completely unable to be processed in any way, all the other variants (red and black granite, netherrack etc) work fine.
Also the only version that can actually be found is the stone variant as it spawns on planets

**Comment by Dream-Master** [comment]
Yea Basaltic Mineral Sand have the same problem. So we have to look what the problem here is.

**Comment by Technus** [comment]
Related #688

**Comment by Technus** [comment]
@Dream-Master Fix that and #688 With scripts, anddont close this issue until we figure out why this "no work".
