### ISSUE TITLE
Thaumic Bases Wand Cores

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#728]
The wand cores added by Thaumic bases do not seem to be able to be used in any wand crafting recipe.  Just wondering if it is intentional.   I didn't have a very long time to test this, just reporting an issue a player on my server is having.

**Comment by Dream-Master** [comment]
Yes I not nerf this mod and so wands are not craft able. I hope I have time for it soon.

**Comment by lilmoefow** [comment]
alright cool, will let the players on my server know to avoid making them for now till the recipes are ready 

thanks for the quick response :)

**Comment by Dream-Master** [comment]
Mod partly nerfed will go into this deeper later.
