### ISSUE TITLE
Crash to desktop when opening a backpack with IC2BIOGas inside a tank 

### ISSUE THREAD

**Issue by ProfGameatron** [GTNewHorizons/NewHorizons#729]
This happens with the adventure backpack. I shift clicked the cells into the back-pack not thinking they would go into the tank and now when I try and open the backpack it causes a crash to desktop.

**Comment by Dream-Master** [comment]
@ProfGameatron So any log for me?
Then i can report it to the mod Author.

**Comment by Dream-Master** [comment]
https://cdn.discordapp.com/attachments/233979175931871232/233979494174556160/crash-2016-10-07_10.58.46-server.txt
https://cdn.discordapp.com/attachments/233979175931871232/233979496070381578/crash-2016-10-07_11.14.10-server.txt
https://cdn.discordapp.com/attachments/233979175931871232/233979498108944384/crash-2016-10-07_11.47.52-server.txt
https://cdn.discordapp.com/attachments/233979175931871232/233979757891551232/crash-2016-10-07_10.41.12-client.txt
https://cdn.discordapp.com/attachments/233979175931871232/233979759942434816/crash-2016-10-07_10.26.26-client.txt
https://cdn.discordapp.com/attachments/233979175931871232/233979761867620353/crash-2016-10-07_10.05.34-client.txt

**Comment by Dream-Master** [comment]
Ok will forbid to place the backpack in Dims.

**Comment by Drobac** [comment]
forbid to place them how? on the ground? cause thats how they get saved when a player dies wearing them. They get place on the ground next to the grave

**Comment by bigbass1997** [comment]
It doesn't sound like the problem is that the backpack is on the ground, but that the mod doesn't know how to handle that fluid when opening the GUI.

**Comment by Dream-Master** [comment]
If it interact with pipes then i crash the whole map.

**Comment by bigbass1997** [comment]
Testing would need to be done to determine that.

That's not even the issue at hand.

The crash occurs client side when the client attempts to open the GUI of the backpack, which can be done whether the backpack is placed on the ground or not.

As of yet, there is no indication that pumping fluids in or out of the backpack would cause any server problems, if doing such action is even possible in the first place.

**Comment by Dream-Master** [comment]
I chat with the Mod Dev allready and he can maybe make a fix,

**Comment by Drobac** [comment]
pumping fluids in andout of the backpack doesnt cause problems, already tested it, works fine with the hose usages into tanks and drums, but didnt go for pipes specifically as i didnt see a need. Its possible that the backpack is not compatible with some of the liquids we have

**Comment by Dream-Master** [comment]
@Drobac Try with Extra Utilities Nodes thats crash the Server.

**Comment by bigbass1997** [comment]
@Dream-Master I attempted to use Ender IO, Gregtech, and Extra Utilities, and I was unsuccessful in both trying to extract or input fluids out-of/into a standard Adventure Backpack that was placed on the ground.

**Comment by ProfGameatron** [comment]
The server side crash is in connection with the client side crash I am uploading explanation videos ATM

**Comment by ProfGameatron** [comment]
https://www.youtube.com/watch?v=QMmQtrAaVs8&feature=youtu.be The crash with Extra utilities transfer node item

**Comment by ProfGameatron** [comment]
Also its not the fluid node being used its a item transfer node

**Comment by ProfGameatron** [comment]
https://youtu.be/llEZacTqWk8 @Dream-Master @Drobac @bigbass1997

**Comment by bigbass1997** [comment]
Would like to note that this problem also happened when using WATER cells. So it appears to be more a problem with cells than it does the liquid inside them.
