### ISSUE TITLE
Me covered cable recipe noncompliant

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/NewHorizons#730]
Me covered cable is made using a cfg 1 IC instead of a cfg 24 IC like every rubber insulating recipe in assembler.

**Comment by Dream-Master** [comment]
@basdxz Sorry not undertstand what you mean here.

**Comment by Drobac** [comment]
the configuration circuit needed to make the covered cable is using the setting of 1 (as it was made before the GT update with cable crafting in the assembler with liquid rubber), can you switch the configuration setting of the circuit in the crafting recipe to 24 so it complies with all the other GT cables
