### ISSUE TITLE
Suggestion Botania mod

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#731]
In many modpacks there is the mod called [Botania](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294116-botania-an-innovative-natural-magic-themed-tech)
That mod has lovely animations and textures. I suggest to place it at thaumcraft level (MV) and use some of its items eg. the terra ingots for witchery and bloodmagic. The Feed-the-beast Infinity Evolved Pack has some hardcore reciepes with this mod.

**Comment by Drobac** [comment]
If its minetweakable, this mod gets +1 for me. It is a really great one and has cool features

**Comment by DietmarKracht** [comment]
I believe it is! [Mod Tweaker](http://minetweaker3.powerofbytes.com/wiki/ModTweaker)

**Comment by bigbass1997** [comment]
I was actually surprised that this modpack didn't have Botania when I first started playing it. As @DietmarKracht said before me, yes it is Minetweakable. Here's the [Botania Support](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Botania_Support) page on the wiki.

**Comment by Dream-Master** [comment]
Ok if i find time i will look at it.

**Comment by Technus** [comment]
-1 doesnt really fit the modpack theme
-1 we already have magical duplication available in thaumcraft
-1 we already have flowers in botany mod

**Comment by bigbass1997** [comment]
The mod adds many useful tools/items. While the mod is technically a "magic" mod, there are many things you can automate with it, as if it were a "tech" mod, such as even an automated treefarm.

It does add some redstone and glowstone duplication, but I'm pretty possitive that can be changed.

Even default recipes and such make it a relatively long mod in terms of how long it takes to progress through it, and with recipe changes, I'm sure it can be made even longer.

There is one minor concern though. The mod requires 16 varieties of special flowers that the mod would normally generate. Fortunately though, if the recipe were changed, there is an item known as "Floral Fertilizer" that is similar to bonemeal except that it spawns random of these special flowers on the ground in a small area.

Other description of the mod can be [found here](http://botaniamod.net/index.php), scroll down a bit to the section titled "Magic, Tech. Naturally".

**Comment by bigbass1997** [comment]
@Technus 
> -1 we already have magical duplication available in thaumcraft

The duplication recipes in Botania are very few as far as I remember. I believe there was redstone, glowstone, and nether quarts. Besides that, I can't remember anything else that involved duplication.

> -1 we already have flowers in botany mod

The flowers in this mod are primarily only used as crafting items; or in other words, the point/purpose of this mod is not the flowers, so you can't really compare it with the botany mod.

**Comment by Drobac** [comment]
Dont see why it wouldnt fit in the pack,  it does need a bit more diversity. Also its minetweakable so it can be gregified. 
Magical duplication is such a small part of the mod,  wouldnt break anything, can probably disabled,  and the pack needs a ton of redstone so it aint that bad of an odea,   it adds innumerable tools and mechanics that are fun to play with.
Botany flowers and Botania's have very little in common. Botanias are used as essential in the crafting system,  botany are just for colour

**Comment by WarlordWossman** [comment]
I wouldn't like the fact that the (currently really cool looking) overworld would be spammed with the flowers. Would there be an option to only have them spawn dimension or biom specific?

**Comment by bigbass1997** [comment]
@WarlordWossman The overworld would NOT be spammed with Botania flowers, it would actually NOT have any Botania flowers, unless the overworld was regenerated. I already mentioned this above:

> There is one minor concern though. The mod requires 16 varieties of special flowers that the mod would normally generate. Fortunately though, if the recipe were changed, there is an item known as "Floral Fertilizer" that is similar to bonemeal except that it spawns random of these special flowers on the ground in a small area.

**Comment by Dream-Master** [comment]
MAkeing Flower recipes are not the problem :P

**Comment by DietmarKracht** [comment]
We could think about resetting the Twillight Forest and let the flowers generate only in tf. 
With that you wouldn't have to start too early with the mod and the overworld doesnt need to be regenerated.

**Comment by bigbass1997** [comment]
@DietmarKracht There's other ways that we could restrict access to Botania, without resetting anything. Such as the way I described, or various other ways.

**Comment by Dream-Master** [comment]
Yes but a special dim have only the Flowers would be nice.

**Comment by bigbass1997** [comment]
True but that consumes a lot more server resources then just adding a crafting recipe.

**Comment by Dream-Master** [comment]
you have to go to Twilight Anyways to start with Thaumcraft so its ok.

**Comment by Drobac** [comment]
There really is no need for a special dimension, if we have to use the Twilight forest thats fine, its meant to be a "mining world" so adding flowers to it and resetting the TF isnt a big issue. Also after you have the first few flowers, it has a mechanic to make more flowers so there isnt going to be an issue with a lack of them

**Comment by Dream-Master** [comment]
I lok at Botania config and i cant find any cfg for lets spawn Flowers in a special Dimension.

**Comment by Drobac** [comment]
Ill check it out later, still its not a big deal even if they spawn in the overworld as well as you can start anything without a petal apothecary for which the recipe can be adjusted to fit the tier

**Comment by Namikon** [comment]
As a side note, there is a Forum for such polls. Anyways; Even if I do like Botania, we're struggling with Server "OutOfMemory" Problems already with 12GB of Ram, and Clients need a crapton of Memory/Beefy CPU to run smooth. Botania adds even more load onto that. Just to keep that in mind. Another Dim for the flowers is a really bad idea. How many Dimensions do you want to add? Our Server resources are not unlimited.

Also I somehow second Tec's opinion about the mod for *this* pack; Being a "GregTech" pack, and not another "FTB Monster" derivate

**Comment by bigbass1997** [comment]
Want to make a couple of comments responding to what @Namikon said above.

I agree completely with Nami on not making a new dimension. As I have already tried to explain, making a whole dimension JUST for flowers that can easily be created using the item I mentioned earlier that acts similar to bonemeal called "Floral Fertilizer", is a really horrible idea. Adding an entirely new dimension will add so much more load onto the server resources, no matter what the specs of the server is.

In terms of does Botania fit the so called "theme" of this modpack, I don't know. Of the 3 or 4 people I asked, none of them seem to know what the theme really is, beyond just making recipes more complex, increasing the longevity of the modpack. Not only that, but if you do say that the theme is "GregTech", then why is Witchery, Twilight Forest, Thaumcraft, and every other magic mod in the pack?

If you want Botania to be "gregified" as some people call it, then please do. Change the recipes to be harder, etc. Botania is more than just a magic mod, it has "tech" in it, and complexity.

Personally I recommend clients have around 3GB minimum; which is pretty good compared to other 1.7.10 modpacks that I've played, requiring at least 4-5GB. Measuring CPU/GPU is a bit harder though.

Also, just because this modpack may have a lot of various mods, doesn't make it an FTB X derivative. In all my time of playing with mods/modpacks (since Industrial Craft 1 first came out), this is the first modpack that I did not either beat or otherwise got bored with, within the first couple weeks. Adding more, especially already complex mods such as Botania, just adds even more complexity, longevity, and fun to the pack.

**Comment by Mylezz** [comment]
i want botania!!!!! i love this mod 2 death and its needed for this pack! 
Maby not a new Dim but maby crafting for it~!

i love thaumcraft+botania! its so much fun!

**Comment by Dream-Master** [comment]
@Mylezz 
Other things have a higher prio atm. So if i nerfed all Thaumcraft addon mods and witchery 100% i have time for this. This mod is not easy and huge. Will see when i am done with nerfs.

**Comment by Mylezz** [comment]
Ok thanks @dream-master!!

**Comment by KaneHart** [comment]
+ one from me and my community. We love it a lot.

**SUGGESTION:** Don't enable flower generation. It's messy and ugly and we got enough crap on the ground. Rather let people bone meal for it or use other methods.

**Comment by Dream-Master** [comment]
I have much ideas but less time :)

**Comment by Dream-Master** [comment]
Will close it now because we have enough mods i guess and the pack becomes slower and slower.
