### ISSUE TITLE
Can not Craft Tier 1 Rocket

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#732]
"to make first rocket to the moon you need a tier 1 rocket engine, which needs a certain alloy(compressed alloy "SDHC-120"), which is made in an implosion compressed from the raw alloy and explosives, however making the raw alloy uses desh screws, ergo you need desh (from mars) to reach the moon.."

That is an issue that a player on my server is having,  I looked it up in NEI and can confirm the recipe issue.  Is there a secondary way of getting desh that we are not seeing???

Is that Intended or did the Galaxy space update break somethings???

**Comment by bigbass1997** [comment]
According to my NEI (on the EU server), the Raw "SDHC-120" Alloy requires Stainless Steel Screws.

![2016-10-08_12 38 08](https://cloud.githubusercontent.com/assets/790116/19214900/b921d864-8d54-11e6-9b5c-737443661c57.png)

**Comment by lilmoefow** [comment]
Not sure if its just an issue with the scripts i have for out sevrer download, but this is the recipe we have.

// --- Compressed Raw Alloy SDHC-120
recipes.addShaped(<dreamcraft:item.RawSDHCAlloy>, [
[<ore:screwDesh>, <ore:craftingToolScrewdriver>, <ore:screwDesh>],
[<GalaxySpace:item.CompressedDualBronze>, <GalaxySpace:item.CompressedCoal>, <GalaxySpace:item.CompressedDualAluminium>],
[<ore:screwDesh>, <ore:craftingToolHardHammer>, <ore:screwDesh>]]);

**Comment by lilmoefow** [comment]
dont know why i clicked close

**Comment by Dream-Master** [comment]
I fix that in the last version.

**Comment by lilmoefow** [comment]
ok cool, i planned on updating our server later on today so thanks :)

**Comment by lilmoefow** [comment]
the server download is still showing GT-New-Horizons-Server-Pack-1.7.10-1.0.9.2i.zip ?? is that correct?

**Comment by Dream-Master** [comment]
yes it is j it shows i. I am lazy no change the link.

**Comment by lilmoefow** [comment]
but the mod pack is on version k on the launcher??

**Comment by Dream-Master** [comment]
k have only exclude Special mobs because we testing stuff.

**Comment by lilmoefow** [comment]
ok im confused then.... You said "I fix that in the last version."  which version would that be?? cause i have my server on version J already, and that fix is not present there. and if version k is just a removal of Special mods, which version has the fix for the desh screws?

**Comment by Dream-Master** [comment]
it is possible is it fixed only in dev. So better do it manually or using my 1.0.9.3 branch srcipt.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/6e03a58afc0fec5177d288b335dc7984f14c8976

**Comment by lilmoefow** [comment]
ight ill just download the scripts from here and replace on server. if you are only "testing" the removal of speacial mobs for now with version k, I am not going to update cause we are not having any issues with it.

Thanks for the Help :)

**Comment by Dream-Master** [comment]
k np.
