### ISSUE TITLE
Missing Nerfed Mods

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#733]
**High priority**

- [ ] Thaumic Horizons
- [ ] Automagy
- [ ] Thaumic Bases
- [ ] Witchery

**Medium priority**
- [ ] Enhanced Portals
- [ ] Project Blue
- [ ] Random Things
- [x] SG Craft - https://github.com/GTNewHorizons/NewHorizons/issues/2647
- [ ] Twilight Forest

**Low priority**
- [x] Open Computers - https://github.com/GTNewHorizons/NewHorizons/issues/2626
- [x] Open PeriperalAddons
- [x] Open Printers
- [x] Open Security
- [ ] Computronic

**Comment by Technus** [comment]
Witchery would totally require more tc research - if u get to it.

**Comment by Technus** [comment]
Questbook - can be disabled crafting, iirc every one uses the button to open it "~" or "`"

we better keep that quest book item just to let players know we have quests

**Comment by Technus** [comment]
SGCraft - would be nice if there was a quest line for it inste

**Comment by Dream-Master** [comment]
Sure i list only every Mod i could find.  And Witchery need a complete redone without changing the Gameplay too much.

**Comment by deathxfighter** [comment]
how about you make witchery able to be used at teir TC is cause honestly TC and witchery needs to be separate in my opinion cause they are totally different and plus the witchery tab in TC doesnt say what line you need to research for it its like if i want one friend to learn witchery while the other learns TC and blood magic how is anyone able to do anything plus dream i think you should reset your character and start playing cause you aint seeing the hastle alot of players gotta deal with like you are changing so much stuff and not playing the pack for yourself to experience what others are experiencing

**Comment by Dream-Master** [comment]
Witchery i will totaly redo. It have using basic Thaumcraft stuff to start with. More things will be taken in the Thaumcraft Book. It will be different then Thaumcraft but it will stay in the Book.

**Comment by Drobac** [comment]
Witchery cant even be set to thaumcraft except for the starting items. Its current status is ok.  Its circle magic cannot and shouldn't be changed. The mod does has interesting and helpful mechanics which are all ok as they are

**Comment by Excaerious** [comment]
I agree on this above notion. Thaumcraft is already quite frontloaded with things it gates. It already gates Witchery to a degree and furthering it would honestly kill the spirit of the mod, as you are meant to do things with its own set of mechanics. Please don't change it.

**Comment by Dream-Master** [comment]
I will add the Key items to Thaumcraft and change maybe some recipe but the machanics i cant and will not change.

**Comment by Dream-Master** [comment]
Will open it up as new issue.
