### ISSUE TITLE
Hardcore Nerf

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#736]
I wonder if this is intented, but galacticraft now requires the avaritia crafting table. That means you have to gather 18 nether stars to get the matrix. Very hardcore i think

**Comment by DietmarKracht** [comment]
Galacticraft is used be a a HV mod by the way.

**Comment by Dream-Master** [comment]
And you can exchange Nasa Workbench to get a Avaritia table and no you nor need to kill 18 wither. Look at the duplication recipe with null catalyst.

**Comment by Drobac** [comment]
Still 18 nether stars for the table seems a bit too much too early

**Comment by Dream-Master** [comment]
Yea but with Null Catalyst no problem.
