### ISSUE TITLE
Iron tank multiblock quest.

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#737]
It seems that Iron Tank quest will not work if you build it by using Assembler Machine.

**Comment by Dream-Master** [comment]
Yea could be a crafting Quest. I can change that but I guess Multi Block thanks be early available before Assembler in the Bronze Age so.
@Namikon 
What you think about change it to retrieval instead of crafting ?

**Comment by DietmarKracht** [comment]
I think you should leave the Iron tank multiblock quest as a crafting quest and change the steel tank multiblock quest to a retrieval because if you get steel you will likely have the assembler soon.

**Comment by Dream-Master** [comment]
Ok good idea.

**Comment by EvgenijM86** [comment]
Personally, I have decided to wait until LV tier to save up iron. I stored all my creo oil inside glass bottles which are a lot cheaper way (they cost just sand) to store liquids than building iron tank without electric machines.

**Comment by Dream-Master** [comment]
Iron Tanks are crafting tasks Steel Tanks are retrieval tasks.

**Comment by codewarrior0** [comment]
I also waited until LV tier before building an iron tank to save iron. It costs two or three times as much iron to craft the tank blocks by hand than it does using the assembling machine.
