### ISSUE TITLE
No Ocean Biomes

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#739]
Using the ATG world gen that is provided by the pack means there are no ocean biomes spanwing, in turn means you can not get Abyssal Stone from Railcraft.

https://github.com/CovertJaguar/Railcraft/blob/mc-1.7.10/src/main/java/mods/railcraft/common/worldgen/QuarryPopulator.java#L66

**Comment by Technus** [comment]
Actually here:
https://github.com/CovertJaguar/Railcraft/blob/mc-1.7.10/src/main/java/mods/railcraft/common/worldgen/GeodePopulator.java#L72

Quick fix is on the way.

**Comment by Technus** [comment]
Added custom populators to coremod.
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/bdab66c922b531c246718cc8fc81c29bd84dfe9d
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/724e20c6bde09a396603d6a447f6f08fde3254c4

**Comment by Technus** [comment]
https://cdn.discordapp.com/attachments/175668782327398401/237877628260843520/unknown.png
