### ISSUE TITLE
Flint and Steel quest

### ISSUE THREAD

**Issue by chehob** [GTNewHorizons/NewHorizons#743]
In the Flint and Steel quest two parts of the first crafting task are not detected:
- Steel Plate
- Flint

**Comment by Dream-Master** [comment]
@chehob Send me a pic please. Did you are using the lastest Quest file from Version 1.0.9.2k?
Did you refresh after each update the Quests ?

**Comment by chehob** [comment]
http://i.imgur.com/virWLtE.png
http://i.imgur.com/jW3WFPJ.png
just reinstalled the pack, still got the problem

**Comment by Dream-Master** [comment]
Did you click submit button a few times ?

**Comment by chehob** [comment]
yes of course, tried dropping items and picking them up and clicking submit again, tried restarting client

**Comment by Dream-Master** [comment]
What version you are using?

**Comment by chehob** [comment]
1.0.9.2k

**Comment by Dream-Master** [comment]
Ok will asking a bit around if others have this problem  too.
Are you play sp or mp ?

**Comment by chehob** [comment]
I'm playing mp on eu server.

**Comment by Dream-Master** [comment]
Which eu Server ?

**Comment by chehob** [comment]
GTNH Official EU

**Comment by WarlordWossman** [comment]
As far as I remember it's a crafting task, have you tried crafting flint from 3 gravel and making the steel plate in the crafting table (2 ingots and hammer)?

**Comment by chehob** [comment]
Will try crafting things. I took the flint from the chest and the steel plate was made in steam forge hammer

**Comment by bigbass1997** [comment]
It is a crafting quest according to the picture you linked. So yeah try crafting them by hand.

**Comment by Technus** [comment]
Crafting always require using the crafting grid in any form, so yes this is most probably the case.

**Comment by Dream-Master** [comment]
@chehob 
Any news. Can i close this issue?

**Comment by Dream-Master** [comment]
:+1:
