### ISSUE TITLE
[Suggestion] Disable initializing spam

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#746]
As long there is no need to update separate mods manually by players, i suggest to disable that spam.
- \Galacticraft\core.conf
B:"Disable Update Check"=true

- \GalaxySpace\core.conf
B:enableCheckVersion=false

- \CodeChickenCore.cfg
checkUpdates=false

- \DraconicEvolution.cfg
B:"Enable version checker"=false

- \WirelessRedstone.cfg
checkUpdates=false

- \FloodLights.cfg
B:IGWNotifierEnabled=false

- \openmodularturrets.cfg
B:"Enable IGW Mod notification"=false

**Comment by Dream-Master** [comment]
Sure will do in the next update.
