### ISSUE TITLE
Cannot remove lava from adventure backpack

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#747]
More specifically: I can put lava into both slots for liquid, but I cannot remove lava from right slot. Liquid from left slot is removable. I was using standard minecraft bucket to do this.

This bug started to affect me when I switched to latest 1.0.9.3 version (from 1.0.9.2). I have removed/redownloaded scripts and config directories just to make sure that it is clean install - still happens.

**Comment by Dream-Master** [comment]
Ok will ask the Mod Dev.
