### ISSUE TITLE
Thaumaturge's Revolver from Thaumic Bases destroys blocks

### ISSUE THREAD

**Issue by Excaerious** [GTNewHorizons/NewHorizons#748]
As title explains the Thaumaturge's Revolver from Thaumic Bases will destroy blocks in such a way as to they will not drop their block if shot. Additionally, the revolver avoids all grief prevention measures, as it can break a block anywhere. Finally, players can be harmed regardless of pvp based settings by the gun.

**Comment by Ugachaga** [comment]
There is [fork](https://github.com/KryptonCaptain/ThaumicBases/releases) which added config for many modules of the mod. Revolver can be just disabled.

**Comment by Dream-Master** [comment]
Will change it if i nerf this mod.

**Comment by Dream-Master** [comment]
try with newest forked version.
