### ISSUE TITLE
mod suggestion 

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#751]
since the special mobs have been removed can we get a mod that does these to the mobs

I dont know what mod my friend had but it made mobs smarter and sometimes spawn more

1. attracted to light( from torches)
2. if player get hits from mob he spills blood( attaracts mobs)
3. idk how the mob count is gonna be but  hordes of zombies ^^^^ great idea ;) for them zombie killers
4. mob AI smarter

**Comment by Drobac** [comment]
Its zombie awareness,  we had it before and it breaks the server harder then special mobs do
