### ISSUE TITLE
Wood Pulp to Paper recipe

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#752]
GTNH 1.0.9.3e
8x Wood Pulp + Water Clay Bucket = 2x Paper + Fired Clay Bucket + **2x Stone Slab**
8x Wood Pulp + Water Bucket = 2x Paper + Bucket + **2x Stone Slab**

On 1.0.9.2k additional Stone Slabs are not provided.

**Comment by Dream-Master** [comment]
my recipe I add is the one with the wood pulp and the Water Bucket. Blood asp add the Chad recipe.
Stone plates are not able to make before you get iron and a saw. Maybe I need to change the Chad recipe using Chad and Water like the wood pulp recipe. Chad can be made then out of sugar and a mortar.

**Comment by Technus** [comment]
Might be realted to bloods asp returning stoneslabs on crafting code

**Comment by Technus** [comment]
I could disable it

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/a70e237cf82bac7ef7bb9cdbe5d5509d7a1bcc4a
