### ISSUE TITLE
Ender tank crafting bug

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#753]
NEI wont show me the crafting recipe 

here is what i get from [it](https://gyazo.com/39e18d1c765951f3182c5eb238049df7)

**Comment by bigbass1997** [comment]
The Ender Tank recipe is unlocked through Thaumcraft research. It requires at least IV tier materials.

I can confirm that when looking for its recipes, whether you have it unlocked or not, it does show how to get water in the smeltery. I suspect this is a problem with the Ender Storage mod itself though I could be wrong. No errors show up in console when looking up how to craft the Ender Tank.

If you ask for what recipes the tank is used in, you will find recipes where either the tank itself is used, or where water is used to craft something.

Ender Tank ID: 2666:4096
Ore Dictionary Name: enderChest

**Comment by Dream-Master** [comment]
Ender Tank have a Thaumcraft recipe like bigbass1997 said. You need to research it first. That nei not show the right thing (nothing) I can't do anything against it sorry.
