### ISSUE TITLE
Quest typos & strange food

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#754]
questID 143 - name erased by description
questID 484 - double description

Cannot eat Toastet Sesame Seeds. Seems not registred as food.
Can drink Chai Tea, but it recovers 0 hunger.

**Comment by Dream-Master** [comment]
- [] questID 143 - name erased by description
questID 484 - double description

**Comment by Dream-Master** [comment]
About the food idk what i can do.
