### ISSUE TITLE
Electric Blast Furnace Quest has Crafting tasks, should be Retrieval

### ISSUE THREAD

**Issue by codewarrior0** [GTNewHorizons/NewHorizons#755]
Heat Proof Casings can be crafted in the Assembler, which does not fulfill a Crafting task.

I noticed this, and went to build the casings using a crafting table instead. But the crafting table I used was a Forestry Worktable. I found out crafting many items by shift-clicking in the Worktable _also does not fulfill a Crafting task_.

<sub>Being in Single-player, I looked around for an equivalent to `/hqm edit`, but all I managed to do was delete the Heat Proof Casings task.</sub>

**Comment by Technus** [comment]
crafting tasks are meant to be crafted normally yes, still if u want to skip that:
https://github.com/Funwayguy/BetterQuesting/wiki/Commands

**Comment by Dream-Master** [comment]
Crafting the Coils manually or with an assembler is a minimal difference. I let it like it is a crafting Task.

**Comment by codewarrior0** [comment]
To reiterate: I crafted the casings in a workbench and *still did not receive quest credit*.

**Comment by Dream-Master** [comment]
Ok will check it.

**Comment by Dream-Master** [comment]
Ok recipes are changed now will be a retreival Quest.
