### ISSUE TITLE
Greg Oil Fields empty since 1.1.0.0 update

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#757]
Hi! i spent the whole day prospecting oil, both with seismic as well as with test drills using oilrig near bedrock, of 25+ tested areas (each 6x6 chunks), only a single one had nonzero but really crappy 14mb/cycle. Giving up and placing the oil rig back on my old spot where i had 350+ mB/cycle remaining before the update it didnt produce a single drop of oil. So something got messed up there. I'm in dirthubs server + discord chat if feedback/testing is needed :)

**Comment by ghoulsblade** [comment]
Usually 50% of greg oil wells should have nonzero. All except one i tested today had literal 0, not a single mb/cycle.

**Comment by Technus** [comment]
I am investingating that problem already

**Comment by ghoulsblade** [comment]
now i'm getting 5000mb/cycle, which is totally insanely much. really good yield would be 500mb/cycle and they're rare. most nonempty should be around 100-350.
The 5000mb/cycle was insanely good for a very short time, but ran dry after 71850mb = less than 72 buckets. Something still totally bonkers there.
Afaik dirthuts is running 1.1.0.2, but best ask the admins in discord chat for details on which version of the fix they installed. Lilmoe maybe?

**Comment by lilmoefow** [comment]
Yeah, Server is on 1.1.0.2

**Comment by Technus** [comment]
yes next update should be ok, the values are more like the blood asp ones and the oil system has some extra fallbacks to prevent stuff

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/eac4226c168b6498531468b727c8b8e87c69a143

You wanted it and you have it

**Comment by Technus** [comment]
For testing purposes GT portable scanner (used in creative mode) can be used to measure oil in chunk (localization on server is broken...)

Oil field values change drasticly every 6/6 chunk field just so u know

**Comment by Technus** [comment]
Also the next commit makes all chunk non zero (you know trace amounts if you really feel like getting em...)
