### ISSUE TITLE
Field kit server kick

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#758]
When trying to scan bees with the field kit the server kicks you with a Fatal error message and nothing in the client log

**Comment by Dream-Master** [comment]
ok will see what the Server log said.

**Comment by Dream-Master** [comment]
I need a log or a bee name. Maybe using /mt hand to see what bee it was. I ask Chocohead but with this spare infos he can't do anything.

**Comment by Dream-Master** [comment]
> Chocohead - Yesterday at 8:02 PM
> Hmmm, it's hard to fix anything with any idea of what's gone wrong. Not especially sure what it would be either, as you'd expect a hard crash from an invalid interface or something like that.

**Comment by Technus** [comment]
@Drobac  Need log of that from the client side.

**Comment by Drobac** [comment]
Didnt get any log when getting kicked from the server. When i tried in SP, i didn't crash

**Comment by Dream-Master** [comment]
@Drobac 
Are you able to relog or crash the client when you join on the server?
Did you crash every time or only some time?

**Comment by Methes** [comment]
So I tried to scan a bee twice today, both time I got kicked out with fatal error.
Server log - http://pastebin.com/uL0Kad4J
It was Common drone, perhaps a hybrid. Other bees work alright so far (scanned like 5 of them).

**Comment by Methes** [comment]
Update:
It has to do with available paper in the Field Kit.
Apparently shift-clicking the paper inside the GUI moves the paper visually but doesn't get applied.

How to reproduce:
Open GUI, shift-click paper, close GUI, see it didn't raise durability and you still have paper in your inventory.

How to get kicked out of the server:
Open GUI (no paper in the tool), shift-click paper inside the tool, try to scan a bee, when the tool tries to remove 1 paper it fails and kicks you out.

Binnie FTW!

**Comment by Dream-Master** [comment]
Chatting with @Chocohead yesterday and hope we get a fix here.

**Comment by Dream-Master** [comment]
Binnies Mod now updates and be open source.

**Comment by Dream-Master** [comment]
Need to be tested with newest version.

**Comment by Dream-Master** [comment]
Test with new version 2.0.16. please
