### ISSUE TITLE
Diesel Generator Nitro Bug

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#759]
I recently noticed the amount of nitro in a diesel generator going up despite no fuel source being connected, i've figured out how to produce this behavior now.

Place diesel generator and put a few buckets nitro in it, attach some energy consumer, e.g. pump or transformer in my case. Stop or Remove consumer after a while so the diesel gen still has some partial amount of diesel left.
Get a stack of empty universal fluid cells, rclick diesel gen and put them in top slot. They will fill with full buckets worth of nitro and stack in the bottom slot, and few hundred mb in the diesel.
So far so good, but now: remove the full universals from bottom slot, while there is still an empty one in top slot.
For some reason the empty one will end up in the bottom slot, still empty. Now the amount of nitro in the diesels fuel tank will start going up.
I think there's an overflow / sign change of the amount of diesel inside for some reason in that case.
Managed to reproduce it 2 times for 2 different diesel generators now, confident that i can reproduce it again with the steps above if needed.
I'm on dirthut discord chat usually if you need assistance/testing.

**Comment by Technus** [comment]
uhh

**Comment by Technus** [comment]
will poke bloodasp

**Comment by ghoulsblade** [comment]
single block: yes, reproduced with mv and hv at least.

**Comment by Technus** [comment]
@ghoulsblade if u can provide some video/gif

**Comment by Technus** [comment]
seems like it is a thing

**Comment by ghoulsblade** [comment]
regression, this bug is back on dirthuts server, 1.2.1.0 afaik

**Comment by Dream-Master** [comment]
@technus any idea?

**Comment by ghoulsblade** [comment]
seen it again just today, issue is still closed, can you reopen? i cant

**Comment by Dream-Master** [comment]
It's not fixed?

**Comment by Technus** [comment]
Fixed by ez mode solutions.
