### ISSUE TITLE
Pam's Harvestcraft Rice Seed

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#760]
There is an issue with crafting the rice seed from a single rice. If i put rice into the crafting grid it will blink the rice seed icon for a short time as the output. Might be caused by a script but you can't finish the rainbow curry that way. Rice seeds are uncraftable.

**Comment by Dream-Master** [comment]
@DietmarKracht In singleplayer all works fine. Can you test it in sp too?

**Comment by DietmarKracht** [comment]
For me it works in sp too

**Comment by Dream-Master** [comment]
Are rice seeds the only seeds cant be crafted ?

**Comment by lilmoefow** [comment]
What server are you on? If they are on the 1.1.0.0 version of the of the pack still, they may not have the updated scripts and or configs on the server.  Same issue i ran into when originally updating to 1.1.0.0 on DirtHuts

**Comment by Dream-Master** [comment]
This could be happend. @DietmarKracht you have before the very old enchiridio scripts in your pack which are rmoved 6 month ago.
If you update please remove the script and config folder and then update again.
Did you run the pack at version 1.1.0.2?

**Comment by DietmarKracht** [comment]
Tested by other Players on the Server. Still doesn't work. Only in SP.
May be an issue at Client-Server-Sync

**Comment by lilmoefow** [comment]
What version of the pack is the server on?

**Comment by Dream-Master** [comment]
@DietmarKracht Any news here?

**Comment by DietmarKracht** [comment]
Afaik @Drobac  has had the same problem when i gave him 1 rice. He thinks its a problem with synching client and server scripts.

**Comment by lilmoefow** [comment]
It is a problem with server and client configs.  The Server he is playing on does not have the updated configs for Pams Harvest Craft.   I ran into the same issue on DirtHuts, when updating to 1.1.0.0  

Check the Configs again on the server, or get the server owner/admin to double check. Cause i guarantee you that the ones in the client do not match the ones on the server.

**Comment by Dream-Master** [comment]
will do.
