### ISSUE TITLE
New Thaumcraft Tab issue??

### ISSUE THREAD

**Issue by lilmoefow** [GTNewHorizons/NewHorizons#761]
Wasn't sure how to title this issue to be honest, but i just finished updating to 1.1.0.2 and the "localization" for the BloodMagic, GTNewHorizions, and Witchery tabs in the Thaumonomicon seem to be broken.

http://imgur.com/a/DfKcz

**Comment by Dream-Master** [comment]
Yea will look into it. Maybe a load order thing again.

**Comment by Dream-Master** [comment]
how the scripts loading alphabetical?

Issue on the Server or Client?

**Comment by Dream-Master** [comment]
DreamMasterXXL - Today at 2:17 PM
@everyone can someone check if the Name from the Thaumcraft Book Tabs are Written right (GTNH page, Witchery Page and Blood Magic Page)?  thanks.
https://github.com/GTNewHorizons/NewHorizons/issues/761
GitHub
New Thaumcraft Tab issue?? · Issue #761 · GTNewHorizons/NewHoriz...
Wasn't sure how to title this issue to be honest, but i just finished updating to 1.1.0.2 and the "localization" for the BloodMagic, GTNewHorizions, and Witchery tabs in the Thaumonomicon seem to b...

EUBotBOT - Today at 2:18 PM
[Nomad]deathxfighter: one sec
[Admin]~tec_SG: works for me dream
[Admin]Drobac: same here
[Admin]~tec_SG: might be that he uses different locale?
[Admin]~tec_SG: but i doubt
[Nomad]deathxfighter: they look fine to me
[Nomad]deathxfighter: name says blood magic and whichery
DreamMasterXXL - Today at 2:19 PM
so not same as on the picture ?
EUBotBOT - Today at 2:19 PM
[Admin]~tec_SG: nope

**Comment by Dream-Master** [comment]
So looks fine on the EU Server 1.1.0.2

**Comment by lilmoefow** [comment]
I'm at work.  Will double check again when I get home. Aparebtly they were not working in the 1.1.0.0 version either.    The scripts I have on the server are the ones that were provided in the 1.1.0.2 client download from technic.

**Comment by lilmoefow** [comment]
Seems to be fine now on DirtHuts, must have been a one off.
