### ISSUE TITLE
issue with greg tech machine and a pump  and pipe

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#762]
sooo i have a EV pump( the pump that drains lakes etc) and a IV pump(for pipe)

the problem is EV pump wont pump out the if you have ither just a pipe or a pipe with pump connected to it and any face of EV pump

and forgot the titanium pipe will not pick up with electric wrench?? i was using normal pipe of titanium

**Comment by Dream-Master** [comment]
A pump will output output not need a pipe pump.

**Comment by deathxfighter** [comment]
i even tried it without the pipe pump

**Comment by Dream-Master** [comment]
@deathxfighter Can you make some pics for me i dont understand what you mean?

**Comment by Technus** [comment]
![image](https://cloud.githubusercontent.com/assets/4737429/19928055/177d6110-a0fd-11e6-8d79-b114e8e34524.png)
Works for me

**Comment by Technus** [comment]
If you put the pump on the machine it should export, if on pipe it should import

**Comment by Technus** [comment]
Also covers on machines that can store power, drain power...

**Comment by deathxfighter** [comment]
gotta wait till after first formation so i can go ingame ill get pics

**Comment by Technus** [comment]
all here is a feature...

**Comment by Dream-Master** [comment]
:P
