### ISSUE TITLE
Broken backpack?

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#763]
![image](https://cloud.githubusercontent.com/assets/4737429/19931184/ddfd6444-a10b-11e6-995d-ea9ef612571a.png)
They broke it...
dream if u can report it

**Comment by Dream-Master** [comment]
DreamMasterXXL - Today at 1:13 PM
are hollidays today ?

any news about the fluid issue and backpacks ?
runescapejon - Today at 1:15 PM
yea it's an holiday i forgot one, i haven't work on the backpack cause i was busy with servers
DreamMasterXXL - Today at 1:20 PM
ok

**Comment by Dream-Master** [comment]
we get a new version.
