### ISSUE TITLE
Solar GT suggestion

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#764]
I think it would be in best intrest if you changed the EV and HV solar panals back to there previous crafting i can understand the LuV and up(even though i dont like the resource requirments) to be used in extreme crafting

**Comment by Technus** [comment]
well imo any solar above 1Eu/t shouldnt exist sine it is the max amount of power you can get per block.

**Comment by Technus** [comment]
Use another power source solars are meant to be endgame'ish

**Comment by deathxfighter** [comment]
They aint suppose to be engame ish MR. iwannausereactors 

Sorry i dont feel like accidently blowing up my base sending me back to the stone age

**Comment by deathxfighter** [comment]
Endgame*
