### ISSUE TITLE
nerf naqudau reactor

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#765]
once made pretty much free power only put in a fuel cell like really :P like made solars extreme crafting and its a way of power might as well do it to the rest of high tier power sources

**Comment by Dream-Master** [comment]
@deathxfighter It need Enriched Naquadah so it's not free like solar panels if this is your question. Or you try to troll me here?

**Comment by deathxfighter** [comment]
i really do think all LuV power stuff should be extreme crafting its like why not make it harder for the higher tiers am i right

**Comment by deathxfighter** [comment]
its like to me now Solar panels are nerfed so bad they aint worth the time or effort to make 

Reason 1,     the cost is way to great then any other power source since it has to have its predecessors etc you made it so bad that when you look at it its not even worth the time or effort to do all that mining when you need more then 1 solars you making it look liek 1 solar is soooo op it aint and that much resources for 1 is just to great

**Comment by Dream-Master** [comment]
Normally Solar Panels are disabled

**Comment by deathxfighter** [comment]
Well i ask of you at least to do this before you start saying its just free power etc 

Set up a full base in SP with just solar panels as power and see what all you can actually run with 1-10 solar panels etc then get back to me on that

**Comment by Dream-Master** [comment]
@deathxfighter if you have real constructive-minded ideas we can open up a new Issue for it.
