### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#766]
I suggest the mod [Thaumcraft Nodetracker](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2340854-thaumcraft-node-tracker-updated-5-25-2015) to be in this Pack. It is a Client-side mod and useful for any Thaumaturge who likes to grab some nodes he found as he can't remember where they were.

**Comment by Dream-Master** [comment]
Ok I can re add it.
