### ISSUE TITLE
Ore listings inconsistent with ore generation

### ISSUE THREAD

**Issue by thePalindrome** [GTNewHorizons/NewHorizons#767]
In the "Achievements" menu, under "GregTech" each ore is listed with every dimension it will spawn under, however there are a few oddities among them.

Malachite: Does not mention the Twilight Forest, but I've only managed to find it there.
Sulfur: The only non-planet listed is the Nether, which is unavailable until mid game, despite requiring sulfur for tier 1.

It's rather hard to find ores when you're told to look in places you can't reach :P

**Comment by Dream-Master** [comment]
Yea maybe the Archivments Text  have to get a  rewrite.
I make a Nether Quest in the Bronze Age so you are able to get Sulfur before be in LV Tier.

**Comment by bigbass1997** [comment]
You can read this spreadsheet as well to find out where all the ore veins spawn based on dimension and y-level range. [https://goo.gl/aR3HHX](https://goo.gl/aR3HHX)

Also, if you are having trouble finding ores in general, go read this [https://goo.gl/JU7Fy9](https://goo.gl/JU7Fy9)

**Comment by Dream-Master** [comment]
@thePalindrome 
Can this closed?

**Comment by thePalindrome** [comment]
I believe at this point what's been established is more "update the achievements text" and "indicate in the quest that sulfur is required"

**Comment by Dream-Master** [comment]
Ok i go over the archivements again. Will do a Sulfur Quest asap.

**Comment by Dream-Master** [comment]
Ok fixed existing Archivements.

**Comment by Dream-Master** [comment]
Sulfur Quest added,

**Comment by thePalindrome** [comment]
Alrighty, see you next bug :P

**Comment by Dream-Master** [comment]
Let it open so long i not push the release.

**Comment by thePalindrome** [comment]
I may be misunderstanding, you are leaving this bug open to ensure it becomes part of the next release? I would suggest the "Milestone" feature to make this bug block the next release. I'm not entirely sure what you're going for.

**Comment by Dream-Master** [comment]
ok ?

**Comment by thePalindrome** [comment]
Sure, that works :P

**Comment by Dream-Master** [comment]
:P
