### ISSUE TITLE
Gregtech Unification and Thaumcraft issues

### ISSUE THREAD

**Issue by Excaerious** [GTNewHorizons/NewHorizons#768]
In the interim, until Dream configures every single recipe which I understand will take along time, it would be great to have a GT Thaumium -> Vanilla Thaumium (and GT Thaumium Block -> Vanilla Thaumium Block), GT Void Seed -> Vanilla Void Seed, and  GT Void Metal ingot -> Vanilla Void metal ingot set of recipes. Many items from Thaumcraft addons are broken due to specifying ONLY vanilla versions (since they aren't changed). 

A small example is the Thaumostatic Spire multiblock which specifies ONLY vanilla Thaumium block. Doesn't work at all with anything else. Example images below of the book page and the completed multiblock not functioning.

![image](https://cloud.githubusercontent.com/assets/6412128/20028093/8876ce76-a2fe-11e6-8023-720be24af206.png)

![image](https://cloud.githubusercontent.com/assets/6412128/20028094/9619c1e6-a2fe-11e6-89e1-53689625ae84.png)

Similarly, you actually cannot currently finish Thaumcraft related quests for the same reason, as one quest specifically wants Vanilla Void Seeds and Vanilla Void Ingots.

![image](https://cloud.githubusercontent.com/assets/6412128/20028124/489400de-a2ff-11e6-9ce0-e46b6bb69319.png)

**Comment by Dream-Master** [comment]
Yea will check this. If i remember right Thaumcraft Ingots are the vanilla version and void are the gt version. Most of teh Thaumcraft recipes are ordicted so not get any prolem.
@Excaerious 
Can you plase list all recipes with incostinces here with pic that i rember what i need to fix. Thanks

**Comment by Dream-Master** [comment]
For Thaumium blocks I can add Chisel variants to fix this issue.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/20029252/99eb0552-a347-11e6-811a-d88ff8f65d48.png)
Block is fixed add a Chisel variant.

**Comment by Dream-Master** [comment]
Ok GT 5.0.26.02 fix this issue.
