### ISSUE TITLE
Questing Tier 0.5 - Tanned Leather too early or too hard?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#773]
Hello! I do belive this quest should be changed slightly since step two is to make an Drying Rack.
To craft an Drying Rack you need access to an Screwdriver. But to make the Screwdriver you need access to an File and an Hammer.
And you need two Wooden Screws, to make that you also need an Saw to cut an Stick into "Short Wood Stick". then File it

So basicly you need an Hammer, File, Screwdriver and an Saw to complete this quest.
And the tools we have access to at this point is the Soft Hammer (Planks) and the Knife (Flint).

And at this point the metals we can access is limited to loot findings. (only Flint Pickaxe)

I belive this quest should be moved to later into the questing since it is (almost) impossible to complete at this tier.

> **As bigbass pointed out below wooden slabs require saw.** 
> So this recipe wont work with slabs, but could work if replaced by planks?

> Another way to solve this could be to remove the Screws from the recipe and replace them with strings instead? The Drying Rack is basicly just a piece of wood anyway?
> 
> I'd Like it to be changed into this recipe instead since it (almost) is realistic
> Wood Slab | Wood Slab | Wood Slab 
> String | Knife | String
> Nothing | Nothing | Nothing
> 
> for the realistics without imagination: You use the knife to cut small holes in the slabs then put the string thru and make the pieces stick together

**Comment by Dream-Master** [comment]
Yea maybe change the recipe will help.

**Comment by bigbass1997** [comment]
Just note that wooden slabs also require a saw anyways.. So even if we changed the recipe to your suggestion, you will still need the saw tool.

And note that this quest is optional, therefore not required to progress in any way.

If you REALLY want the quest to be moved, then just move it to after the "Important tools" quest in Tier 0.5, which is where you craft all of those tools anyways.

**Comment by Dream-Master** [comment]
Yea will move the Quests a bit in Tier 0.5.
