### ISSUE TITLE
minor: Pollution/Muffler particles one tile off south

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#777]
Muffler particles are generated one tile too far SOUTH
![2016-11-12_17 09 39](https://cloud.githubusercontent.com/assets/378125/20239208/99d43552-a8fb-11e6-93b6-108ad8e3f749.png)

**Comment by Technus** [comment]
Already fixed in dev

**Comment by Technus** [comment]
Just to be sure what version of GT u have?

**Comment by ghoulsblade** [comment]
1.1.0.2 on server, 1.1.0.0 on client (didnt wanna upgrade client since that messes up bookmarks on technic)

**Comment by Technus** [comment]
Outdated version, reopen if u find that bug after update. 

Also the waypoints are stored in the journey map folder. So u can retrieve em after update, or u can just backup them before.
