### ISSUE TITLE
thaumcraft recipe question

### ISSUE THREAD

**Issue by deathxfighter** [GTNewHorizons/NewHorizons#778]
dream why did you change the quantam gear recipe you made it double the material basically   (1 suit of nano +  1 quantaum suit(another suit of nano)  = 1 quantaum with upgrades)    could you have just changed the items where u would have been able to just infuse extra stuff then make a completely 2nd set to make the suit?

**Comment by Mylezz** [comment]
I agree with that because its Stupid to have it cost 2x what i would cost before D:

**Comment by ghoulsblade** [comment]
only expensive part is the damn helmet due to nightvision. platin from nickel ore in chemical bath > autoclave + carbon.

**Comment by Dream-Master** [comment]
@deathxfighter Did you mean the Electro Magic Tools Armor ?

**Comment by deathxfighter** [comment]
yea

**Comment by deathxfighter** [comment]
like for example the quantaum infused armor and wings shoudl be different cause if a quantaum armor + wings dont get same abilities so the quantaum armor should be a lil different if u know what i mean?

**Comment by Dream-Master** [comment]
We change the values a bit. Now the wings have much more armor like Nano and quantum plus the fly abilities.

**Comment by Dream-Master** [comment]
@deathxfighter 
The original recipe looks like this:
https://ftbwiki.org/Infused_Quantum_Chestplate
