### ISSUE TITLE
bloodmagic altar tier3+ changes should be mentioned ingame

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#779]
Bloodmagic tier3 altar needs 8 titanium blocks, it was mentioned in the changelog, but should also be mentioned ingame in thaumonomicon bloodmagic descriptions as well as quest texts.

**Comment by Dream-Master** [comment]
Yes i will add it to the Quest Book or/and Thaumcraft Book.

**Comment by Technus** [comment]
Closing duplicate.
