### ISSUE TITLE
Marble ores not accepted in quest.

### ISSUE THREAD

**Issue by veryhasted** [GTNewHorizons/NewHorizons#782]
The Marble ores that have the exact same name as the normal ores doesn't register in any quest that requires ores. Some of these are Malachite Ore ( -oreMarbleMalachite ) and Yellow Limonite Ore ( -oreYellowLimonite )

**Comment by Dream-Master** [comment]
Yes i know the same for Nether, End and Granitic ones. I think i cant do anything against it. 
@Technus any idea on this? Not breaking Ordict and make it detectable.

**Comment by Technus** [comment]
i could add a common unused for crafting oreregistration

**Comment by Dream-Master** [comment]
I wont change anything here. @veryhasted Try to find some Stone variant of the Ore.
