### ISSUE TITLE
T4 Quest

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/NewHorizons#784]
In the T4 Age where you get to HV there is a quest with crafting the soulbinder from Ender IO. That Block needs a Ender Head that is produced in the Slice'n Dice out of 2 vibrant alloy plates. These require tungstensteel which is definitely not a T4 material. Either change the reciepe or move quest to T5

**Comment by Dream-Master** [comment]
Ok will look into it.

**Comment by Dream-Master** [comment]
Yes high Tier Quests needs a rework sure.

**Comment by Dream-Master** [comment]
Using Chrome allready.
