### ISSUE TITLE
Battlegear 2 shapeless recipes broken

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#787]
The following recipes in Battlegear 2 don't function:
the crafting recipes to add arrows to the quiver
the crafting recipes to remove arrows from a shield with arrows in it

Possibly due to MineTweaking? They should work by default with the base mod, as they're an integral part of the mod, so I can't imagine they would be simply bugged.

**Comment by Dream-Master** [comment]
Yes it is fixed in dev. Will be in the next update.
