### ISSUE TITLE
Some recipes being culled improperly from NEI - INPure Core?

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#788]
The following recipes don't show up in NEI, but still function:
glow flowers into glowstone dust via compressor
disc rack from bibliocraft

I believe INPure is responsible for this due to [this comment](https://www.reddit.com/r/feedthebeast/comments/2qkbi2/dw20_1710_bibliocraft_disc_rack_replacement/cn87y3o/).

**Comment by Dream-Master** [comment]
Maybe i need to remove inpure mod.
