### ISSUE TITLE
Forestry Mail System Implementation

### ISSUE THREAD

**Issue by Technus** [GTNewHorizons/NewHorizons#789]
'Mailbox'
- At Bronze+Iron+blue dye tier

'Trade Station'
- At Steel Tier (BBF) +blue dye

A way of making letters would be also nice. (preferably compress 9 wood pulp)

**Comment by Technus** [comment]
![image](https://cloud.githubusercontent.com/assets/4737429/20340443/cc481786-abe1-11e6-911e-f5b2435512fc.png)
Remove that recipe

**Comment by Namikon** [comment]
+1
TP commands will be disabled soon (Moved to donation Goal). The Mailbox System would enable item-trading early on. ServerSide only; EU Server
