### ISSUE TITLE
Empty Seared Tanks trigger pizza glove effect when in hand

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#790]
Title. It works with any form of Seared Tank, regardless of what fluid is within. Is this because there is no different item for a Seared Tank filled with lava?

**Comment by Dream-Master** [comment]
Yes because it detect the fluid tank and not make a difference if there is lava in or not. @Namikon anything we can do here?

**Comment by Technus** [comment]
It requires effort... will see.

**Comment by Technus** [comment]
So the tank name is
TConstruct:LavaTank
and the Lava in name triggers the gloves, @Dream-Master  needs to adjust configs.

**Comment by Dream-Master** [comment]
I am not sure if this works. I rember only this works otherwise the tank are not detected.

**Comment by Technus** [comment]
I and nami know why it no work. Most probably.

**Comment by Technus** [comment]
The tank has 0mB of lava inside instead of 0mB of null inside when empty.

**Comment by Dream-Master** [comment]
@Namikon @Technus 
Any Idea if we can fix this or we let it like it is, Gloves can be repaired.

**Comment by Dream-Master** [comment]
i dont see a real problem here.
