### ISSUE TITLE
Problem with putting BoP Blood with a bucket into fluid canner

### ISSUE THREAD

**Issue by Smeany** [GTNewHorizons/NewHorizons#795]
It doesn't return a normal bucket. It returns a bucket called minecraft.bucket.name from  BiomeOPlenty. Those buckets aren't stackable and they crash the server if right clicked on a coke oven with them.. BoP blood is poop anyways. It cant be tanked :-(

**Comment by Dream-Master** [comment]
I test it yesterday in my dev Pack and it works fine. Can you send me a pic?

**Comment by Smeany** [comment]
![2016-11-19_15 07 28](https://cloud.githubusercontent.com/assets/23564498/20455991/20f6d940-ae6a-11e6-86e8-35edde44a725.png)
![2016-11-19_15 46 23](https://cloud.githubusercontent.com/assets/23564498/20456170/886054f8-ae6f-11e6-92cf-966c7bc2b20e.png)

It's the fluid canner and not the canning machine, sorry.. was goin to make the advanced coke oven bricks.

**Comment by Drobac** [comment]
is it only doing that in the fluid canner? what happens when you put the liquid in a normal BC tank?

**Comment by Smeany** [comment]
That's what i meant with "BoP blood is poop anyways. It cant be tanked"  Seems like it is not a real fluid like the other blood types.. There is no blood cell either. Atleast not with the BoP blood D:
I don't want to waste so many buckets aye.

**Comment by Dream-Master** [comment]
Maybe using a different fluid then.

**Comment by Dream-Master** [comment]
Will using IC2 coolant.
