### ISSUE TITLE
crush when seeing recepis involving alcemical caps

### ISSUE THREAD

**Issue by arik4326** [GTNewHorizons/NewHorizons#796]
[crash-2016-11-19_11.27.58-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/601344/crash-2016-11-19_11.27.58-client.txt)

**Comment by Technus** [comment]
`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/19/16 4:30 PM
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 3
	at com.arc.bloodarsenal.common.thaumcraft.ItemWandCores.func_77617_a(ItemWandCores.java:51)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(Unknown Source)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.arc.bloodarsenal.common.thaumcraft.ItemWandCores.func_77617_a(ItemWandCores.java:51)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(Unknown Source)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: com.arc.bloodarsenal.common.thaumcraft.ItemWandCores@a7bcc50
	Item Aux: 3
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe
	Mouse location: Scaled: (577, 343). Absolute: (1155, 403)
	Screen size: Scaled: (1024, 545). Absolute: (2048, 1089). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['tec_SG'/14275308, l='MpServer', x=-2585.35, y=112.62, z=-1208.02]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 04 - RWG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-2584,96,-1168), Chunk: (at 8,6,0 in -162,-73; contains blocks -2592,0,-1168 to -2577,255,-1153), Region: (-6,-3; contains chunks -192,-96 to -161,-65, blocks -3072,0,-1536 to -2561,255,-1025)
	Level time: 1012452396 game time, 6818351 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityCow['Cow'/5429331, l='MpServer', x=-2539.72, y=72.00, z=-1193.50], EntityTFBunny['Forest Bunny'/5914713, l='MpServer', x=-2530.56, y=70.00, z=-1185.28], EntityPig['Pig'/14275933, l='MpServer', x=-2556.94, y=75.00, z=-1265.13], EntitySheep['Sheep'/5729874, l='MpServer', x=-2537.69, y=70.00, z=-1181.50], EntityPig['Pig'/14275932, l='MpServer', x=-2524.97, y=74.00, z=-1248.22], EntitySheep['Sheep'/14275934, l='MpServer', x=-2534.56, y=76.00, z=-1268.53], EntityPig['Pig'/14275921, l='MpServer', x=-2553.13, y=74.00, z=-1259.97], EntitySheep['Sheep'/14275920, l='MpServer', x=-2552.38, y=74.00, z=-1256.22], EntityWolf['Wolf'/11, l='MpServer', x=-2580.94, y=91.88, z=-1172.59], EntityWolf['Wolf'/139, l='MpServer', x=-2526.22, y=91.00, z=-1156.31], EntityCow['Cow'/14275922, l='MpServer', x=-2548.78, y=75.00, z=-1264.81], EntityPig['Pig'/140, l='MpServer', x=-2538.47, y=71.00, z=-1159.34], EntityTFDeer['Wild Deer'/12, l='MpServer', x=-2533.59, y=69.00, z=-1168.41], EntityTFDeer['Wild Deer'/13, l='MpServer', x=-2540.38, y=69.00, z=-1172.63], EntityCow['Cow'/141, l='MpServer', x=-2532.69, y=71.00, z=-1160.53], EntityPig['Pig'/14275924, l='MpServer', x=-2527.63, y=74.00, z=-1232.19], EntityWolf['Wolf'/142, l='MpServer', x=-2572.66, y=84.00, z=-1173.75], EntityCow['Cow'/14, l='MpServer', x=-2538.47, y=69.00, z=-1168.75], EntitySheep['Sheep'/14275927, l='MpServer', x=-2587.66, y=81.00, z=-1265.50], EntityWolf['Wolf'/143, l='MpServer', x=-2573.78, y=96.00, z=-1169.69], EntityTFBunny['Forest Bunny'/15, l='MpServer', x=-2535.28, y=70.00, z=-1182.88], EntityPig['Pig'/14275926, l='MpServer', x=-2580.06, y=79.00, z=-1261.88], EntityWolf['Wolf'/144, l='MpServer', x=-2575.25, y=96.00, z=-1170.41], EntityGoblin['Hobgoblin'/9390367, l='MpServer', x=-2543.13, y=71.00, z=-1183.56], EntityCow['Cow'/14275913, l='MpServer', x=-2553.06, y=76.00, z=-1238.84], EntityWolf['Wolf'/145, l='MpServer', x=-2572.31, y=96.00, z=-1170.31], EntityPig['Pig'/14275912, l='MpServer', x=-2544.41, y=75.00, z=-1223.22], EntityWolf['Wolf'/146, l='MpServer', x=-2575.06, y=96.00, z=-1171.53], EntityCow['Cow'/14275915, l='MpServer', x=-2541.81, y=74.00, z=-1241.25], EntityHorse['Horse'/19, l='MpServer', x=-2577.94, y=73.00, z=-1160.06], EntityCow['Cow'/147, l='MpServer', x=-2578.52, y=87.00, z=-1202.32], EntitySheep['Sheep'/14275914, l='MpServer', x=-2527.22, y=74.00, z=-1217.50], EntityWolf['Wolf'/148, l='MpServer', x=-2603.06, y=96.00, z=-1169.69], EntityPig['Pig'/14275917, l='MpServer', x=-2537.75, y=74.00, z=-1233.38], EntityPig['Pig'/14275916, l='MpServer', x=-2532.09, y=74.00, z=-1239.81], EntityCow['Cow'/14275919, l='MpServer', x=-2576.47, y=77.00, z=-1262.47], EntityPig['Pig'/151, l='MpServer', x=-2584.03, y=78.00, z=-1188.16], EntitySheep['Sheep'/14275918, l='MpServer', x=-2582.81, y=79.00, z=-1263.50], EntityCovenWitch['Coven Witch'/152, l='MpServer', x=-2535.50, y=72.00, z=-1193.09], EntityPig['Pig'/14275905, l='MpServer', x=-2561.69, y=82.00, z=-1236.47], EntityCow['Cow'/153, l='MpServer', x=-2540.53, y=71.00, z=-1185.16], EntitySheep['Sheep'/3034935, l='MpServer', x=-2538.47, y=70.00, z=-1183.47], EntityCow['Cow'/14275904, l='MpServer', x=-2647.88, y=74.00, z=-1183.13], EntityGoblin['Hobgoblin'/154, l='MpServer', x=-2536.22, y=70.00, z=-1185.50], EntityPig['Pig'/14275907, l='MpServer', x=-2527.06, y=74.00, z=-1235.16], EntityHorse['Horse'/155, l='MpServer', x=-2524.84, y=71.00, z=-1192.03], EntityClientPlayerMP['tec_SG'/14275308, l='MpServer', x=-2585.35, y=112.62, z=-1208.02], EntityGoblin['Hobgoblin'/14275909, l='MpServer', x=-2576.47, y=91.00, z=-1238.09], EntityHorse['Horse'/14275908, l='MpServer', x=-2535.97, y=74.00, z=-1229.97], EntitySheep['Sheep'/2376378, l='MpServer', x=-2536.91, y=70.00, z=-1184.47], EntityCow['Cow'/14275910, l='MpServer', x=-2561.13, y=77.00, z=-1245.97], EntityCow['Cow'/14266879, l='MpServer', x=-2615.34, y=78.00, z=-1154.53], EntityPig['Pig'/14266878, l='MpServer', x=-2619.94, y=75.00, z=-1162.06], EntityChicken['Chicken'/9412775, l='MpServer', x=-2538.50, y=70.00, z=-1184.50], EntitySpider['Spider'/28977, l='MpServer', x=3.43, y=-42.78, z=30.42], EntityGoblin['Hobgoblin'/14267234, l='MpServer', x=-2582.13, y=77.00, z=-1146.56], EntityGoblin['Hobgoblin'/3863174, l='MpServer', x=-2535.50, y=70.00, z=-1183.56], EntityBlaze['Blaze'/41414, l='MpServer', x=-12.52, y=-26.99, z=56.06], EntityGoblin['Hobgoblin'/5584925, l='MpServer', x=-2535.44, y=70.00, z=-1184.50], EntityTFMiniGhast['Carminite Ghastling'/14679, l='MpServer', x=-9.57, y=-43.72, z=42.13], EntitySheep['Sheep'/14266881, l='MpServer', x=-2622.50, y=78.00, z=-1155.56], EntityCow['Cow'/14266880, l='MpServer', x=-2609.25, y=75.00, z=-1159.50], EntityTFMobileFirefly['Firefly'/14478726, l='MpServer', x=-2574.44, y=12.17, z=-1149.94], EntityTFDeer['Wild Deer'/14266882, l='MpServer', x=-2619.78, y=81.00, z=-1165.03], EntitySkeleton['Skeleton'/41309, l='MpServer', x=0.48, y=-26.99, z=56.06], EntityHorse['Horse'/14275897, l='MpServer', x=-2637.53, y=82.00, z=-1192.47], EntityCow['Cow'/14275896, l='MpServer', x=-2563.47, y=83.00, z=-1210.31], EntitySheep['Sheep'/14275899, l='MpServer', x=-2635.75, y=84.00, z=-1185.38], EntityCow['Cow'/14275898, l='MpServer', x=-2632.47, y=85.00, z=-1196.31], EntityWolf['Wolf'/14275900, l='MpServer', x=-2588.00, y=90.00, z=-1216.69], EntityCow['Cow'/5683760, l='MpServer', x=-2538.53, y=70.00, z=-1185.53], EntityCow['Cow'/14275903, l='MpServer', x=-2611.75, y=96.00, z=-1218.44], EntityCow['Cow'/14275902, l='MpServer', x=-2572.44, y=88.00, z=-1236.66], EntityPig['Pig'/5866035, l='MpServer', x=-2537.19, y=70.00, z=-1185.53], EntityPig['Pig'/14275893, l='MpServer', x=-2630.84, y=81.00, z=-1168.63], EntityCow['Cow'/14275892, l='MpServer', x=-2637.69, y=75.00, z=-1166.47], EntityCow['Cow'/5643192, l='MpServer', x=-2539.53, y=70.00, z=-1182.56], EntityPig['Pig'/14275895, l='MpServer', x=-2633.81, y=81.00, z=-1178.50], EntityItem['item.item.egg'/14431666, l='MpServer', x=-2538.88, y=70.13, z=-1184.22], EntityPig['Pig'/14275894, l='MpServer', x=-2625.13, y=81.00, z=-1169.34], EntitySheep['Sheep'/3105503, l='MpServer', x=-2529.69, y=70.00, z=-1186.16], EntityZombie['Zombie'/36082, l='MpServer', x=3.43, y=-43.72, z=42.13], EntityTFSquirrel['Forest Squirrel'/5629351, l='MpServer', x=-2534.41, y=69.00, z=-1181.47], EntitySheep['Sheep'/14268461, l='MpServer', x=-2539.75, y=75.00, z=-1212.50], EntityTFBoar['Wild Boar'/6043044, l='MpServer', x=-2536.22, y=70.00, z=-1181.50], Entity_SpecialSlime['Slime'/14487585, l='MpServer', x=-2580.69, y=32.62, z=-1245.29]]
	Retry entities: 0 total; []
	Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by Technus** [comment]
Looks like that item no longer exists in BloodArsenal.

**Comment by Technus** [comment]
Check this up, it is some wand core/rod with meta ==4.
Probably would need recipe change/deletion.

**Comment by Technus** [comment]
There are now only two items of that class:
"blood_wood", "blood_wood_staff"

**Comment by Dream-Master** [comment]
@Technus Did anyone other have this issue maybe on us Server?

**Comment by Dream-Master** [comment]
I think i fix it.
Will be in the next release.
