### ISSUE TITLE
Crafting Fence with Spruce Planks

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#797]
Local Forge server 1.1.0.4
When craftin Fence with Spruce Planks the recipe shows up correctly but the block changes into " Wooden Slab" instantly upon clicking the product.
Works fine with Oak Planks.
![2016-11-19_19 21 05](https://cloud.githubusercontent.com/assets/8257735/20457517/a499bb82-ae8d-11e6-9692-d00dfe775be0.png)
![2016-11-19_19 21 09](https://cloud.githubusercontent.com/assets/8257735/20457519/a6e6e414-ae8d-11e6-9a1d-bcab37f764e5.png)

**Comment by Dream-Master** [comment]
Maybe some wrong ordict. Have to test maybe i can reproduce it.

**Comment by Dream-Master** [comment]
@Methes Its only a visual thing. I can renme it with minetweaker maybe.

**Comment by Methes** [comment]
It's not just visual. The "fence" works only in three recipes (Tinker's tables) and as fuel. It doesn't work in anything else.
Bed for example:
![2016-11-20_23 35 47](https://cloud.githubusercontent.com/assets/8257735/20466798/3df5d3f0-af7a-11e6-9705-e9cc86d3596f.png)

**Comment by Dream-Master** [comment]
The bed need oak ones. Maybe I need to add fuel values via Minetweaker too.

**Comment by Dream-Master** [comment]
Ah ok didn't read with the fuel. The problem with the bed is fence not have any ordict so far I know.
