### ISSUE TITLE
Glow flower

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/NewHorizons#799]
![2016-11-21_02 05 39](https://cloud.githubusercontent.com/assets/16925725/20467861/9b068aa2-af8f-11e6-96a6-e9ad55011588.png)

The glow flower still got one of those weird recipes to get the seeds. My suggestion would be one glow flower -> one seed. 

Also the screenshot shows "all" the uses (U key used on it) of the flow flower.
Now you can put 2 of them in the extractor and get 1 glowstone dust however NEI is not showing that which sucks. Fixing that would be great and on top of that I felt like it would be more balanced and also better fitting if the extractor ratio would be 1 glow flower -> 1 small pile of glowstone dust.

**Comment by Dream-Master** [comment]
2 Flowers give a glowstone dust so 4 small piles i think this recipe is ok.
Will add a seed recipe one flower for one seed.
