### ISSUE TITLE
EnderIO: soulbinder recipe for Sentinel Ender not working

### ISSUE THREAD

**Issue by LameGirlyCurly** [GTNewHorizons/NewHorizons#801]
When trying to craft EnderIO dimensional tranciever, the Sentient Ender (aka EnderIO:itemFrankenSkull:4) doesn't seem to have a valid recipe in the soul-binder. Shows up in NEI, but the soul vial with a witch captured in it cannot be inserted at the same time with the other component into the soulbinder.

**Comment by Technus** [comment]
Was that soul of Witchery witch or vanilla one?

**Comment by Technus** [comment]
But yes i can confirm it does not work.

**Comment by Technus** [comment]
Is there Enderio update planned, or did u changed the recipe? @Dream-Master

**Comment by LameGirlyCurly** [comment]
it was just a vanilla witch. A player told me that "wither witch" worked

**Comment by Dream-Master** [comment]
Special mobs override the mobs. Tec is working on a fix.

**Comment by Technus** [comment]
Done

**Comment by Technus** [comment]
Even if that was EnderIO fault.
