### ISSUE TITLE
Chunk-crossing cables with transformers, apparent amperage increasing - is this fixable?

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#802]
Drobac and Bigbass have seen a demonstration of this bug already, but I'll try to explain it succinctly here.

The generator setup is as such: 2 LV generators feed into a 1A LV buffer, which feeds into a ULV transformer. The stepped-down 4A ULV power then travels through 25 blocks of 4x Red Alloy Cable to another ULV transformer on the other side, where it is stepped back up into 1A LV.

The 25 blocks of RA cable happen to cross chunk borders twice. Here is where the bug occurs: all of the 4x RA cable within the middle chunk, the one lacking a transformer, disappears/burns up within moments of powering the system on.

https://gyazo.com/415f828de4942de608b7523befe31a9d
https://gyazo.com/a95a7e7bef4d461df4cc0cead8628272

Adding 8x cable to the edges, we can see that the 8x cable is unaffected; something is increasing the amperage for no apparent reason. What's more, the amperage problem mysteriously vanishes upon contact with the outer chunks with transformers present. This problem is also not caused by unloaded chunks; it occurs instantly, without having to leave and return to the area.

Even just knowing what the hell is going on would be nice. I've wasted 44 4x RA cables on this dumbass bug already, and I'm going to have to waste another 12 just to work around the bug until it can be fixed.

Update: 

https://gyazo.com/73a629632cc16f4244222bc850f91d3f

Using a continuous line of 8x cables through the middle chunk didn't work. This time, it consumed all of them within the chunk, including the border ones that survived before when the middle ones were only 4x. This means the amperage must be more than simply doubling, possibly increasing without bound due to some unknown factor.

I'm out 112 copper and 7 stacks of redstone because of this thing, not to mention the rubber, power, and time.

**Comment by Technus** [comment]
Learn how to not derp.
Wont fix ic2 power system.

**Comment by Technus** [comment]
More detail provided on discord

**Comment by Technus** [comment]
Still for power distribution one does not simply stepdown....
