### ISSUE TITLE
A few Uncraftable Items in Thaumcraft Addons

### ISSUE THREAD

**Issue by Chicken9000** [GTNewHorizons/NewHorizons#803]
I found a few uncraftable items, assuming they are not disabled as i can see them in NEI.

Planar Conduit from Thaumic Horizons. (Void Ingots is the issue, looks like there are a few recipes that need the vanilla TC void ingot then the GT one.)
Thaumium Anvil from Thaumic Bases. (Thaumuim Blocks are the issue.)

**Comment by Dream-Master** [comment]
Yes we know that and it is fixed in the next update.

Thaumic Horizons and Thaumic Bases are mods i not touche yet but i will soon.(nerfing)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/768

**Comment by Drobac** [comment]
If you need the "vanilla"  thaumium block you can use the chisel to switch it. The rest of the recipes using vanilla thaumium and void ingots need to be switched, but im guessing there will be a work around for it

**Comment by Dream-Master** [comment]
yes Thaumcraft Blooks are made via Chisel.
