### ISSUE TITLE
Thaumium Tinker tool parts can be made in the basic part builder (no extruder required)

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#805]
Not sure if this is a bug, but reporting it anyway since it seems distinctly un-greggy.

**Comment by Drobac** [comment]
This is a vanilla tinkers/TC interaction. Thaumium made in the extruder gives the wrong kind of thaumium parts which dont give the extra modifier

**Comment by Dream-Master** [comment]
yes and thats why i disable thaumium for Tincers Gregworks.
