### ISSUE TITLE
Certain combinations and types of non-vanilla woods do not work for many construction recipes

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#811]
Examples of recipes that don't work with modded woods, but do work with vanilla woods:

Sacred Oak planks and Twilight Oak wood to make a chest in an LV Assembler
Twilight Oak wood with flint to make a crafting table, also in the Assembler
ANY type of wooden slabs other than Oak to make trapdoors by hand

**Comment by Dream-Master** [comment]
Yes some wood logs/planks need a ordict tag maybe.

**Comment by Dream-Master** [comment]
seems to conflickting with Barresl in the Assembler.
