### ISSUE TITLE
Specific Infernal Mobs effects interact bizarrely or are broken

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#812]
The 1UP effect, when present on a Special Mobs "Unholy Ghast" or other such mob with resistance to all weapons but the vanilla wooden sword, will cause the mob to become nearly impervious to ALL weapons after the 1UP triggers. Vampire Pigmen will likely experience the same buff. 

The Ninja effect causes an extreme amount of damage to the player when the mob is struck (whether at melee or at range) and usually then places the mob in a wall somewhere nearby, where it suffocates. Surely this can't be intended behavior?

Blastoff, Ghastly, Storm, and Alchemist all affect the player regardless of whether the mob is aggroed, e.g. on a Zombie Pigman or Enderman.

**Comment by Dream-Master** [comment]
Not sure what i can do here. We disable so many effects i not want to disable more.

**Comment by Drobac** [comment]
1UP is waaaay too strong. It is one mob effect that has to be disabled, When you are dealing with a 400 HP mob with a lot of effects, the last thing you want is that mob to revive with full HP

**Comment by Dream-Master** [comment]
ok so which effect we can add back to remove 1up?

**Comment by Wavepon** [comment]
I think Bulwark is about the same as 1UP. Basically the same: 1UP increases the mob's effective HP by 100%, and Bulwark also does that, but by reducing the damage they take by 50%. Literally the same but Bulwark is less buggy.

**Comment by Drobac** [comment]
Which ones are currently disabled?

**Comment by Wavepon** [comment]
Rust, Sticky, and Lifesteal are all disabled.

Rust is another broken effect.

Lifesteal presumably makes some mobs, such as particularly fast ones, or mobs with vengeance, impossible to kill.

And Sticky is simply overpowered. It pulls items out of the player's hand on hit, and if the mob has Ghastly or Storm, or even if the fight is occurring in the wrong place... bad news.

**Comment by Dream-Master** [comment]
We fork Special mobs so its possible to fix brocken stuff.

**Comment by Nenluen** [comment]
Ninja Mobs are currently the bane of any of my spawner-farm designs.

I have the mobs funneled down to a quick kill area (diamond spikes, in my current case) where they neatly pack in and fall over dead, but fairly frequently, when the Angry Mobs 'kamikazi' explosion on death triggers, any ninjas nearby are popped out and start doing nasty things like potions or storm at any nearby player, or, sometimes derpy things like when they teleport into a nearby wall and just start suffocating... forever if they have 'First Aid' or 'Regen' and then have to be dug out of the wall to be killed.

Ninja mobs will also teleport if they explode when they die sending their drops scattering across the area.

**Comment by Dream-Master** [comment]
We need someone who want to change the code. I close it now until we find someone are able and willing to do it.
