### ISSUE TITLE
Add a quest for Transformer blocks with information about cables going over chunk borders?

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#813]
Having experienced this bug firsthand, I think it would be helpful for new players to understand that cables need to be protected by transformers anytime they cross chunk borders. A transformer block quest in LV would be the perfect way to teach people about this.

**Comment by bigbass1997** [comment]
Though this is slightly off-topic, it would be good to teach players basics of GregTech power in general. It's very different from normal power systems (such as practically all systems that use RF).

As well as telling them about issues currently in the mod such as the chunk border issue.

**Comment by Dream-Master** [comment]
I dont know what i can explain here. Need help with it and close it now. If someone can explain it btter i reopen it.
