### ISSUE TITLE
Add alternate, more efficient Blast Furnace recipes to almost every major material, requiring a secondary ingredient?

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#814]
1000 Molten Uranium-238 to enhance the smelting speed of Quantium, for example. Some kind of appropriate material for the tier (like Cobalt with Oxygen, maybe something for Aluminium and Silicon as well).

**Comment by Dream-Master** [comment]
Tec change a lot in EBF recipes with different fluids. This will be available in the next update.

**Comment by Drobac** [comment]
As dreammaster said, a lot of new liquids will be added in the next update to help with all the material processing. All the liquids will be tier equivalent to the ingot being smelted
