### ISSUE TITLE
Add recipes for Chisel variants of natural stone that don't generate (Marble, Limestone, etc.)

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#818]

**Comment by Dream-Master** [comment]
@Wavepon 1 pic says more tehn 1000 words. Can you send me some example pic thanks.

**Comment by Wavepon** [comment]
As it turns out, Railcraft Quarried Stone can actually be chiseled into Chisel-mod Marble. However, Limestone is still unobtainable. 

https://gyazo.com/82bc06091e2190719dada1c31463307f

**Comment by Dream-Master** [comment]
@Wavepon so you want a limestone recipes or what you exactly want. Sorry for not understand what i need to change :)

**Comment by Wavepon** [comment]
A limestone recipe would be great! And perhaps an abyssal stone recipe, if there is no way to obtain that material.

**Comment by Dream-Master** [comment]
Abyssal stone be available in the next version. Limestone recipe I can add.

**Comment by Wavepon** [comment]
Thanks!

**Comment by Technus** [comment]
Abyssal - yes but only on new generated chunks so GL.
