### ISSUE TITLE
Add Twilight Forest woods and leaves, BoP leaves, Forestry leaves, Extra Trees leaves to Woodcutter job

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#819]

**Comment by Dream-Master** [comment]
@Namikon can you add those items/blocks?

**Comment by Namikon** [comment]
Any type of "log" (Not oredict, by ID) was added to those jobs. I need the exact type of wood that is not working. And there will be no reward for breaking leaves...

**Comment by Dream-Master** [comment]
I will check twilight logs if oredicted.

**Comment by Dream-Master** [comment]
All logs are ordicted.

**Comment by Dream-Master** [comment]
``<TwilightForest:tile.TFLog>
<TwilightForest:tile.TFLog:1>
<TwilightForest:tile.TFLog:2>
<TwilightForest:tile.TFLog:3>
<TwilightForest:tile.TFMagicLog>
<TwilightForest:tile.TFMagicLog:1>
<TwilightForest:tile.TFMagicLog:2>
<TwilightForest:tile.TFMagicLog:3>``

@Namikon Thats all Logs i found. Are planks need to be added too?

**Comment by Namikon** [comment]
As I wrote, this works by ID not by oredict. The following BlockIDs are monitored in the Woodcutter job:
17:0
17:1
17:2
17:3
18:0
18:1
18:2
18:3
161:0
161:1
162:0
162:1
626
627
628
629
815
3127
3128
1913

I don't have an up to date block-list around, so maybe IDs got shifted, it needs specific Meta-Values or something is missing. Someone on the EU Server should verify those IDs if possible, just in case

**Comment by Dream-Master** [comment]
Will post it later here. @Namikon

**Comment by Dream-Master** [comment]
If still happend we can reopen it.
