### ISSUE TITLE
People's chat names should be the same color as their rank

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#821]
I think it would be cool to have it that way so People are more inclined to rankup and look more distinguished :DDD

**Comment by bigbass1997** [comment]
Well the rank tag itself is already colored, and if I remember correctly, member ranks (besides Newbie) are all bold text to make them stand out more.

Then Staff and donators are also able to use colors and /nick (and colors in the nickname). In fact, as far as I know, all staff members have a colored name.

To change the color of every single person based on rank would make staff and donators stick out far less than now.

**Comment by Mylezz** [comment]
for like Citizen+

**Comment by bigbass1997** [comment]
Ok yeah for just Elite and MAYBE Citizen I think would be okay. I say just Elite because its the end of the rank tree as of right now and even with grinding out money, it still takes a lot of time to achieve which would properly show that that player is at least somewhat dedicated to the server. Thus he/she should get some recognition.

And I don't know about Citizen, maybe, probably wait for @Namikon's opinion before setting my mind to any of this.

**Comment by Mylezz** [comment]
yea

**Comment by Technus** [comment]
Colored nickname is donor perk.
And even then the ~ shows if the user has OP staus.
@Namikon  already negated the feature when i sugested it.

**Comment by bigbass1997** [comment]
We aren't suggesting allowing member ranks access to /nick. But that the player's name is automatically colored by the rank itself. Again I would only support this for Elite as its the final rank at the moment and it costs a lot of money (and it currently doesn't give anything special anyways).

**Comment by Namikon** [comment]
I'll think about something for Citizen+. Don't want to make stuff *too* colorful; Maybe a bold+dark_green would be ok for citizen, and bold+gold for elite

**Comment by Mylezz** [comment]
I was actually going to suggest those colors! Lol green is the best!!!

**Comment by Dream-Master** [comment]
@Mylezz , @Namikon , Ise this solved?

**Comment by Dream-Master** [comment]
@Mylezz , @Namikon , Ise this solved?

**Comment by Technus** [comment]
The real question is why there is no blue chat for staff. @Namikon

**Comment by Namikon** [comment]
Because it's hard to see ingame. But I can give you light blue if you want...

**Comment by Technus** [comment]
Exacly what i want 💯 :1st_place_medal:

**Comment by Namikon** [comment]
Done

**Comment by Namikon** [comment]
....aaaaaaand removed due to the expected "readability" issue.
