### ISSUE TITLE
Modify Rope Ladder recipe output or input

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#823]
Currently the recipe requires 64 string and 16 long wooden sticks for a single rope ladder. This isn't really very valuable. Maybe 4 or 8 ladders would be a better output? Possibly halve the string cost as well?

**Comment by Dream-Master** [comment]
It's o rope ladder so you are able climbing up to 256 Blocks. Under this circumstances this recipe is to cheap.

**Comment by bigbass1997** [comment]
@Dream-Master I haven't personally tested it, but from what I have heard from others, a single rope ladder does not spawn a super long ladder beneath where it was placed. So assuming that is fact, actually 64 string for a single meter of ladder is pretty expensive.

**Comment by Drobac** [comment]
Recipe was made a long time ago,  mechanics must have changed

**Comment by Wavepon** [comment]
It consumes more rope ladders to place itself, therefore needing even more rope ladders to make a ladder of any reasonable size, at a 1:1 ratio.

**Comment by Dream-Master** [comment]
@Wavepon Ok suggestions please.
