### ISSUE TITLE
Issues about Plasma Generator

### ISSUE THREAD

**Issue by Anikilulala** [GTNewHorizons/NewHorizons#824]
HI, I'm playing newest version of Gregtech new horizon mod pack and meeting with some unexpected plasma generator explosions.  I spent some time looking into the code ,and found some problems. It seems   these bugs are from the original version of Gregtech5Unofficial. So I have posted  these to the original Gregtech5Unofficial issue page. Here are the details:
https://github.com/Blood-Asp/GT5-Unofficial/issues/721
Howerver those bugs will not occur frequently in a original Gregtech5Unofficial game, unless using a few extremely high energy plasma. But when playing Gregtech new horizon things become more dangerous, because of adding so many high energy plasma.FLOAT to INT conversion will increase the actual output and finally trigger unexpected explosions. That's why I decide post it here.

**Comment by Dream-Master** [comment]
@Technus any idea if it is a bug and how we can fix it?

**Comment by Anikilulala** [comment]
I think I should give an example to confirm this bug:
1 A large plasma generator
2 Small turbine made from MgAl2 : Plasma flow 6000/t  / Efficency 70%
3 ZPM Dynamo hatch : 131072 eu/t allowed
4 Silver plasma (tier 2 fusion)
According to the wiki http://ftb.gamepedia.com/Large_Turbine
This generator should only generate 6000* 0.7=4200 eu/t, far less than 131072.
However, An unexpected explosion will occur after about 1 minute running. 
My code in https://github.com/Blood-Asp/GT5-Unofficial/issues/721 might solve this bug, though it break the 125% fuel consuming rule (no one can handle an exact 0.012mb/tick input, isn't it? ), and still need test.
Or I suggest temporarily disable the large turbine explosion until original mod fix this bug.

**Comment by Technus** [comment]
Fixed by new turbine code.
