### ISSUE TITLE
Cant build The Blood Altar tier 3 and above.

### ISSUE THREAD

**Issue by Anikilulala** [GTNewHorizons/NewHorizons#825]
Cant build The Blood Altar tier 3 and above according to the original mod structure.
Are there any structure differences or special material requirement besides the runes?

**Comment by Drobac** [comment]
T3 need titanium blocks as pillars,  T4 should have tungstensteel and T6 i believe id neutronium

**Comment by Dream-Master** [comment]
No the last use Iridium Blocks. Sorry documentation is missing but I will add this info to the Questbook.

**Comment by Anikilulala** [comment]
Thanks you very much.
I think it maybe be a good idea that write it on the altar tooltip.

**Comment by Drobac** [comment]
Thought it was written somewhere, ateast in the questbook. @Dream-Master is it written somewhere and i missed it?

**Comment by Dream-Master** [comment]
Its not written thats the problem. We need a WIKI Guy :)

**Comment by Drobac** [comment]
Can write it on the enjin wiki no problem, but it needs some in-game way to see it

**Comment by Dream-Master** [comment]
in the config you can see it but it is cryptic

**Comment by Drobac** [comment]
So its not even written il the questbook?

**Comment by Dream-Master** [comment]
no

**Comment by Dream-Master** [comment]
I make Quests for Tier 1-6 of the altar to explain how it works and which blocks you need.
