### ISSUE TITLE
Lightning Warp from Warp Theory

### ISSUE THREAD

**Issue by Chicken9000** [GTNewHorizons/NewHorizons#826]
This specific warp is making it hard to even play. I can deal with the other effects, even the guardians.

I don't get the message all the time that I get this effect. (Your hair stands on end...) Also it can last for hours and though extended log out sessions. Its making it very unplayable when I can't go topside of my base. As I write this message I have had this effect for 18 hours straight.

**Comment by Dream-Master** [comment]
Make soma amulet to reducing the warp or using the Thaumcraft bath to wash the warp temporary away. Didn't you read on the researches Dangerous or Taboo ?

**Comment by Chicken9000** [comment]
Yes, I lowered my warp but it didn't fix it, I just had to wait a few more hours till it stopped on its own.

**Comment by Dream-Master** [comment]
@Chicken9000 But now its gone ?
Be carefull with warp.

Can I close the issue?
