### ISSUE TITLE
Inventory tweaks out of date and also missing from the server.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#827]
2 issues I have version InventoryTweaks-1.59-dev-156 and curse offers at least Inventory Tweaks 1.59-dev-152.

The most latest version I can be gotten from here:
http://stonelegion.com/kane/InventoryTweaks-1.59-dev-156.jar
(This version I took from Infitech 2 and people use to talk about it but I don't know why I can't find the actual direct link to the build and their build sites down right now making this post)

**Comment by Dream-Master** [comment]
Yes a have this version too not be sure if this version have more or less bugs?

**Comment by KaneHart** [comment]
Not sure. I will use what you provided for a while and let you know if I run into issues. I don't think I can note any bugs with the version I posted as I been using it for a while but there is always bugs somewhere :)
