### ISSUE TITLE
List Of Mods with Update Checks Still.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#828]
This not a full list I'm sure I missed one or 2 but here we go:

**AppliedEnergistics2/VersionChecker.cfg**
B:changelog=false
B:notify=false
B:enabled=false

**EnhancedPortals/config.cfg**
B:NotifyOfUpdates=false

**INpureProjects/INpureCore/INpureCore.cfg**
B:check=false

**NEI/client.cfg**
checkUpdates=false

**BiblioCraft.cfg**
B:CheckForUpdates=false

**BloodArsenal.cfg**
B:"Is auto-magic version checking allowed?"=false

**HardcoreEnderExpansion.cfg**
B:enableBuildCheck=false

**MrTJPCore.cfg**
B:"Include Unstable"=false
B:"Version Checking"=false

**opensecurity.cfg**
B:enableMUD=false

**WirelessRedstone.cfg**
checkUpdates=false

**Comment by Dream-Master** [comment]
@KaneHart And this configs are true atm?

**Comment by KaneHart** [comment]
They were at least on the server configs. I could of missed something but I ended up going through all the server configs and comparing them to my configs and these are the ones that were still lit up outside of my book spawn disabled ones.
