### ISSUE TITLE
Forced Hardcore Darkness is not for everyone | Custom Servers! (Could we get a config option server side)

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#829]
So don't get me wrong I think it's cool to have hardcore darkness for some. Hell I like the idea and the appeal but overall it's boring and grim. For a server you have many choices at night. Logoff, afk, or skip night... Your interior looks like crap because the forced gamma lock is not fun. Places like the nether and twilight are overall darker looking and blind as a bat people like me can't see shit all.

The only big thing that actually makes it harder is mining underground. But then again who mines the old style when we all dig straight down now and have the sky light inside and use minimal torches...

So my point is it's not for everyone. I understand why you wanted to force it via a core mod for your own servers but I feel having and allowing a server side option to disable it should be brought back...

Not only that but you ruined my Let's Play Series since it was started without the darkness ;)

So would it be possible to have a config option please?

**Comment by KaneHart** [comment]
@Technus could I have a reason for closing the ticket? Thanks.

**Comment by Technus** [comment]
Didnt noticed, serverside based check would indeed not be that bad option. Harder to implement tho.

**Comment by Dream-Master** [comment]
@Technus I close this now. When changed we can reopen it.
