### ISSUE TITLE
Quest reward issue

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#830]
When someone invited me to join a party with them, before I accepted it, I started getting unclaimed rewards on the quests they were completing.
![capture](https://cloud.githubusercontent.com/assets/17787093/20652116/49e638c8-b4eb-11e6-856a-69db76c2c52c.PNG)

**Comment by Dream-Master** [comment]
You are a lucky guy maybe :)

**Comment by Technus** [comment]
Shared rewards, every one gets the reward for quest.
