### ISSUE TITLE
Natura Sticks have two incorrect NEI recipes, and no correct recipe

### ISSUE THREAD

**Issue by LunarPhoenix** [GTNewHorizons/NewHorizons#832]
I chanced upon how to craft natura sticks the other day, after previously haven given up crafting them. NEI shows 2 possible recipes, one of which actually makes vanilla sticks, the other actually makes a pressure plate. 

It's necessary to craft Natura sticks to make the Natura versions of fences, fence gates, and trapdoors. Sidenote, the Fences are all named "Fence" instead of 'Sakura Fence', or 'Ghostwood Fence'

The Actual Recipe:
![screenshot 2016-11-27 17 35 48](https://cloud.githubusercontent.com/assets/24213264/20652471/f967c722-b4c7-11e6-84c4-663dfa8d5b9f.png)

NEI recipes:
![screenshot 2016-11-27 17 37 05](https://cloud.githubusercontent.com/assets/24213264/20652489/6233d732-b4c8-11e6-8787-f1bd017f2c98.png)
![screenshot 2016-11-27 17 37 09](https://cloud.githubusercontent.com/assets/24213264/20652490/62377c34-b4c8-11e6-9579-0917c9c3d61f.png)

What the NEI recipes actually craft:
![screenshot 2016-11-27 17 37 45](https://cloud.githubusercontent.com/assets/24213264/20652492/6b579268-b4c8-11e6-9165-0c77569499aa.png)
![screenshot 2016-11-27 17 37 35](https://cloud.githubusercontent.com/assets/24213264/20652493/6b598b72-b4c8-11e6-9b89-10bdb945fac9.png)

Sidenote:
![screenshot 2016-11-27 17 48 56](https://cloud.githubusercontent.com/assets/24213264/20652579/d0501784-b4c9-11e6-9fa2-2ecc1feda4d3.png)

**Comment by Dream-Master** [comment]
Yes tested it now recipes act a bit wired.

**Comment by Dream-Master** [comment]
There are hidden bowl recipe idk very funny.

![image](https://cloud.githubusercontent.com/assets/2970688/20652712/9a3edede-b4fe-11e6-8df0-ad83d32528dd.png)

**Comment by thePalindrome** [comment]
FWIW Natura sticks and planks don't ore dictionary with wood in most modpacks I've played. This might be a big reason why it doesn't work correctly in NEI

**Comment by Dream-Master** [comment]
Will add it to oredict via core mod.

**Comment by Dream-Master** [comment]
MAterial are ordicted but not works normal.

I add new reciepes

![image](https://cloud.githubusercontent.com/assets/2970688/21743992/88386d48-d50d-11e6-81e9-a650e9e520b5.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21743994/90fe4ab0-d50d-11e6-9d12-b8521168a607.png)
