### ISSUE TITLE
Adv Backpacks Disconnect (Consistent)

### ISSUE THREAD

**Issue by Bizzmark** [GTNewHorizons/NewHorizons#833]
I've discovered a solid bug in the new 1.2.0.0 update. With Adventure Backpacks, specifically my Bat pack (I don't have any other packs but assume functionality is identical), I had always used the lower-left green tool slots to shift+mousewheel which scrolls between them. Until the 1.2.0.0 update today (DirtHuts) this worked flawlessly, save for a visual bug with GT tools; now, it disconnects me from the server every time I try to scroll, instantly. The error displayed is attached below (Connection lost; a fatal error has occurred, this connection is terminated). I am only using TiC and other fairly normal tools (Healing Axe etc.), no GT tools because of the visual bug.

![screenshot_7](https://cloud.githubusercontent.com/assets/5779097/20653003/5a9007e8-b4d3-11e6-914c-8c78d01f30d0.jpg)

**Comment by Dream-Master** [comment]
There is a quick fix out. Will look into it tomorrow.

**Comment by KaneHart** [comment]
Thanks. I was about to report this also. When switching tools now it dc's.

**Comment by Dream-Master** [comment]
Update planing for Today 29.11.16.

**Comment by Dream-Master** [comment]
Hopfully fixed with new update.

**Comment by KaneHart** [comment]
Thanks ;)
