### ISSUE TITLE
Pure Stibnite dust cannot be smelted into Antimony (nuggets nor ingot)

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#834]
Magnetite, Malachite, and other impure ores have this functionality, so I assume Stibnite and other basic smeltable ores should be the same.

**Comment by bigbass1997** [comment]
Actually Stibnite Dust can be centrifuged into Antimony Dust and Sulfer Dust.
Impure Piles and Purified Piles of Stibnite Dust can however be smelted into ingots.

Galena Dust is a similar example: Both the Impure Pile and regular Galena Dust have no smelting recipes, instead Galena Dust can be Electrolyzed into Lead, Silver, and Sulfer Dust.

**Comment by Dream-Master** [comment]
Did other pure dusts can be made to ingots directly? I think it is not a bug.

**Comment by Wavepon** [comment]
Other pure dusts can, yeah. Copper, Malachite (makes nuggets), Chalcopyrite, Tetrahedrite. Basically every accessible ore in Tier 1-2 is smeltable normally, except for Stibnite now.

Stibnite was previously able to be smelted normally. Also, every variation of Stibnite can be smelted normally (impure dust, crushed, purified, etc) except for pure dust.

**Comment by Dream-Master** [comment]
@Technus any idea here.

**Comment by WarlordWossman** [comment]
Well not every "pure" dust can be smelted into something, it always was that way.
