### ISSUE TITLE
Crashing When using Witchery Cauldron

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#836]
Crashing when making anything in the Bigger cauldron, When i reload i cant move and my FOV is like slowness 30.... Unless i die/am killed. also any players around me get the same issue D:

here are my crash reports
[crash-2016-11-27_19.06.02-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/615297/crash-2016-11-27_19.06.02-client.txt)
[crash-2016-11-27_18.45.11-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/615296/crash-2016-11-27_18.45.11-client.txt)

**Comment by Dream-Master** [comment]
````micdoodle8.mods.galacticraft.core.entities.player.GCPlayerBaseSP.onUpdate(GCPlayerBaseSP.java:68)`````

@Mylezz Did it crash only with 1.2.0.0 or with 1.1.x.x too?
I have to look at the potion ids maybe something using same id.

Please report the bug to GS too maybe they have an idea.

https://github.com/BlesseNtumble/GalaxySpace/issues

Will do a potion dump later to see if ids multiple times used.

**Comment by Mylezz** [comment]
Only 1.2.0.0

**Comment by Mylezz** [comment]
Will do in the morning its 1:30 am here

**Comment by Dream-Master** [comment]
k

**Comment by Dream-Master** [comment]
Galaxy Space seems to cause this issue. Works with GS 1.1.0 after this i dont work.

**Comment by ghoulsblade** [comment]
i got the same crash apparently, was doing witchery with robe+hat for bonus output, making otherwhere chalk. worked fine 2 times, 3rd one crashed me. by the crashlog it looks like a potion effect is the cause.
[crash-2016-12-28_19.21.35-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/676060/crash-2016-12-28_19.21.35-client.txt)

**Comment by Ugachaga** [comment]
GalactiCraft code [seems fine](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerBaseSP.java#L65-L69). 
GalaxySpace not even in stacktrace.

Potions  dump [looks good](https://github.com/GTNewHorizons/NewHorizons/files/676451/potion.txt) too.

All 3 crashes are about `java.lang.ArrayIndexOutOfBoundsException: -71`. So something is trying to make potion with id "**-71**". As I see Witchery potion IDs was changed in GTNH 1.2.x, perhaps it is related somehow.

**Comment by ghoulsblade** [comment]
when brewing something with witchery there's a chance to get random potion effects on the player while doing so, maybe it selects a broken effect sometimes.

**Comment by ghoulsblade** [comment]
in the meantime for the witches out there who dont want to risk crashing when making potions i found a partial workaround: the book "witches' brews" (7285, blue) shows how you can draw circle runes around the cauldron to eliminate those sideeffects, in the chapter Rituals: Risk & Power, see screenshot below:
![2016-12-30_20 52 25](https://cloud.githubusercontent.com/assets/378125/21571693/fa610aca-ced1-11e6-8b66-195a2f4dfaf6.png)

**Comment by Dream-Master** [comment]
Nice but this not fix the original issue.

**Comment by Ugachaga** [comment]
1.3.0.0pre1 log:
```
[22:07:59] [Client thread/WARN]: witchery: Using potion slot 185 (for potion witchery:potion.paralysed), can lead to problems, since there is a client/server syncing restriction of max 128 potion IDs. Use the PotionStartID configuration setting to lower the range witchery uses.
[22:07:59] [Client thread/WARN]: witchery: Using potion slot 203 (for potion witchery:potion.wrappedinvine), can lead to problems, since there is a client/server syncing restriction of max 128 potion IDs. Use the PotionStartID configuration setting to lower the range witchery uses.
[22:07:59] [Client thread/WARN]: witchery: Using potion slot 195 (for potion witchery:potion.spiked), can lead to problems, since there is a client/server syncing restriction of max 128 potion IDs. Use the PotionStartID configuration setting to lower the range witchery uses.
...
```

**Comment by Dream-Master** [comment]
@Ugachaga ah ok that is a very helpfull info you gave me. Will fix it.
And that explain the crashes. 
@Ugachaga Thanks

**Comment by Ugachaga** [comment]
[Detailed explanation](http://gaming.stackexchange.com/questions/265484/why-does-potion-level-128-give-some-potions-weird-effects/265521#265521) how potion IDs work. So potion ID "-71" caused that crashes = 127 + (128 - 71) = 184 = witchery:potion.overheating. That makes sense.

This problem is not completely fixed yet. Safe ID range is "0 - 127", so need to change: [Taint Withdrawl](https://github.com/GTNewHorizons/NewHorizons/blob/6ec54e6def2ab329d1be55dbe4dbc017fc2627d5/config/ThaumicExploration.cfg#L35) and [FeatherFall](https://github.com/GTNewHorizons/NewHorizons/blob/6ec54e6def2ab329d1be55dbe4dbc017fc2627d5/config/AWWayofTime.cfg#L363).

**Comment by Dream-Master** [comment]
K will try if there is more free space

**Comment by Dream-Master** [comment]
Fether fall get 98 allready so only Tainted Withdrawl needs to be fixed.
