### ISSUE TITLE
Part 4/6 in Quest 'Wire-Wrap' in 'Tier 1 - Steam' does not trigger

### ISSUE THREAD

**Issue by Toperoco** [GTNewHorizons/NewHorizons#838]
Hi!

So this is a retrieval task for 60 raw rubber and 10 sulfur dust (on a side node - this seems a bit off, since the next step requires 60 raw rubber and 20 sulfur dust), but gathering these materials does not seem to complete this quest step. The ones before complete just fine. I also made double the materials to start step 5/6 (crafting 20 rubber bars), which again triggered immediately.

I noticed this issue after the server updated to 1.2.0.0, where a main quest for crafting a wire cutter was added, which opened this quest for crafting 10 plastic sheets. Some additional info in the screenshots below. I'm available to provide any info I might be missing or do some testing that might help in resolving the issue!

![gt-nh-book](https://cloud.githubusercontent.com/assets/11035501/20660709/3f1246ac-b54b-11e6-9013-6b4db5f8761a.jpg)
![gt-nh-inv](https://cloud.githubusercontent.com/assets/11035501/20660711/3f1ea690-b54b-11e6-8f36-e017000da484.jpg)
![gt-nh-quest](https://cloud.githubusercontent.com/assets/11035501/20660710/3f177f78-b54b-11e6-970a-0a5ef55da193.jpg)

**Comment by Dream-Master** [comment]
did you try to hit the detect and submit bottom a few times?
Throw the stuff on the ground and collect it.

**Comment by Toperoco** [comment]
Tried dropping several times and spammed that button like a madman ;)

**Comment by Dream-Master** [comment]
Ok will check it later.

**Comment by Toperoco** [comment]
Related and apparently solved by https://github.com/GTNewHorizons/NewHorizons/issues/844

When I was given 10 IC2 sulfur dust the quest completed instantly and the dust got converted to the GT version without me doing anything with it.
