### ISSUE TITLE
Unable to get glue into assembly machine. 

### ISSUE THREAD

**Issue by Canhos** [GTNewHorizons/NewHorizons#839]
Tried pumps, pipes from other mods and centrifuge directly into it. Only a problem since 1.2 patch.

**Comment by Technus** [comment]
something doesnt allow unification of TicoBlue with GT glue and that makes 2 glue fluids to try and register, i still cannot reproduce that in DEV env.

**Comment by Dream-Master** [comment]
It seems to be a Server issue.

**Comment by LameGirlyCurly** [comment]
so does that belong to Thermos github?

**Comment by Dream-Master** [comment]
We are not 100% sure. Needs some more tesing. We guess it have somethings to to with script load order.
Hope we can fix it soon.

**Comment by LameGirlyCurly** [comment]
well definitely doing /mt reload spills out an error on console, which it usually doesn't do: 

http://pastebin.com/0zbs4eR6

**Comment by Dream-Master** [comment]
@LameGirlyCurly Did you remove all script files from the Server when make an update or override them?
Some scripts change thier names and so it could be possible that one recipe loading twice in two different recipe files.

**Comment by LameGirlyCurly** [comment]
you're partially right about the scripts - old ones were moved away, but the ones that were installed were partially corrupt (or atleast did have different sizes for some parts then the ones I pulled today from the dropbox that was linked to from techniclauncher).

Error is away but no glue goes in regardless :)

**Comment by lilmoefow** [comment]
There is nothing wrong with the scripts on the sevrer. the ones i put on the server for the 1.2.0.0 update i pulled from the client download you have on technic.

**Comment by lilmoefow** [comment]
How are you going about "unifying" the glue types?  Are you doing it with scripts or are you just letting GT's Oredict handle it all?

**Comment by lilmoefow** [comment]
Tcons "fluid" glue is not in the ore dictionary, and i can not seem to actually find a way to get liquid tinkers glue.   So im not sure where the issue for this is??

**Comment by Dream-Master** [comment]
Ticon is ignored so not sure why the game choose in sp Tico glue and on Server GT Glue which doesent work.

**Comment by Dream-Master** [comment]
Need new GT version 5.09.26.21 and Core Mod 1.3.01
