### ISSUE TITLE
Quest: Wire-Warp should be a Requirement for Basic crafting: Casings.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#841]
Wire-Wrap should also be a required unlock for Basic crafting: Casings not just Blastoff! As it requires rubber and people might of not completed the other chain yet.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Dream-Master** [comment]
But in the End get the Last Quest of Tier 1 you need it both.
![image](https://cloud.githubusercontent.com/assets/2970688/20773518/7d3fd2c4-b752-11e6-9793-aefb3eb09f80.png)

The wirering looks ugly then and i guess peple will complete it to go to Tier 2.
