### ISSUE TITLE
Quest: Wire-Wrap Wrong Sulfur Dust (IC instead of GT)

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/NewHorizons#844]
I was having issues completing (detecting/submitting) GT Version of the dust. I went ahead and spawned IC version in creative and worked just perfectly though it auto converted into GT overtime or something crazy.

Either way the detection seems a bit buggy I feel if it was switched to GT Version of the dust then less people will have issues with it.

**Comment by Technus** [comment]
should use oredict tag instead tho

**Comment by Dream-Master** [comment]
will change that.
