### ISSUE TITLE
Thaumcraft Armor on BiblioCraft Armor-Stands Causes Major FPS Lag

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#845]
Thaumcraft Armor on BiblioCraft Armor-Stands Causes Major Fps lag when u are within 20 or so blocks of them. 
When i was moving the armor stands around my base i saw my Fps was back to its average of 280-300 fps, So i removed all the Armor-Stands and i found that was what was causing My lag.
When Thaumcraft armor is on Armor-Stands it Drops my Fps From An Average of 280-300 down to 20-30 Fps, Here are some Screengrabs to show u Top Right Above the Map is the FPS Counter
![basefps](https://cloud.githubusercontent.com/assets/23045776/20727533/b93bbed4-b62e-11e6-81d3-e1f12c40364b.png)
![lag](https://cloud.githubusercontent.com/assets/23045776/20727539/bbd2dde4-b62e-11e6-98eb-c6eb7ceced80.png)
![nolag](https://cloud.githubusercontent.com/assets/23045776/20727541/bd7d0a48-b62e-11e6-9ca8-c0cf1fce1a58.png)

Normal Armor dose not lag as bad but its still more lag than before 
I tried this on a Custom Pack with just thaumcraft and Bibliocraft and it Dident lag So the issue is native to this pack.

Just wanted to let u know!

~Mylez_

**Comment by Dream-Master** [comment]
@Mylezz But what you think i can do against it. Biblio Craft ar no longer developed for 1.7.10.

**Comment by Mylezz** [comment]
Get an older version? Before the update it was not a problem

**Comment by Dream-Master** [comment]
I not updated this mod for ages.

**Comment by Mylezz** [comment]
Was thaumcraft updated?

**Comment by Dream-Master** [comment]
No Thaumcraft not get any update.

**Comment by Mylezz** [comment]
What mods were updated

**Comment by Dream-Master** [comment]
http://gtnewhorizons.enjin.com/forum/m/36844562/viewthread/28973236-serverchangelog/post/125693975#p125693975

**Comment by Mylezz** [comment]
Galaxy space could be causing it and also I didn't close this issue apparently that's another issue with mobile on github D:

**Comment by Mylezz** [comment]
Because of the witchery issues maby the build is unstable?

**Comment by Dream-Master** [comment]
Maybe potion ids. I change some because gs overitten a potion id

**Comment by Mylezz** [comment]
Ok, well maby the next update iy will be fixed

**Comment by Mylezz** [comment]
It~

**Comment by KaneHart** [comment]
I experienced this issue too but with 0 thaumcraft just vanilla minecraft head on it tanked the fps in half.

**Comment by KaneHart** [comment]
Looks like this is the issue:

https://github.com/GTNewHorizons/NewHorizons/issues/837
