### ISSUE TITLE
Invalid quest reward?; Tier 2 - Don't play with food!

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#847]
Tier 2 - Don't play with food!

Choice reward between LootBag (Tier 2) or "Item Placeholder Original ID: Forestry:canOil"

I assume that the second one should be an can of oil, not an "?" icon

Issue Solved. Thanks @Dream-Master

**Comment by Dream-Master** [comment]
Quests need to be reloaded. Are you playing on a Server or sp? command is /bq_admin default load

**Comment by Bryfer** [comment]
aha, that explains it, thanks! private server with friends,

**Comment by Dream-Master** [comment]
So it can be cloded ?

**Comment by Bryfer** [comment]
@Dream-Master Yes, unless you want it here for others to see the solution if they got the same problem :)
