### ISSUE TITLE
Some ores are mineable with gt flint pickaxe

### ISSUE THREAD

**Issue by miguel1118** [GTNewHorizons/NewHorizons#848]
I've able to mine the gt black iron ores (dont remember the name), gt tin ores and also small gold and iron ores with gt flint pickaxe, but when I got tinkers flint pickaxe I wasnt able to mine them.

Im almost sure this is a bug since quest book said that I shouldn't be able to mine those ores until I got the tinkers iron pickaxe

**Comment by Dream-Master** [comment]
Small Ores can be always mined so far i know. Maybe i have to set the values in the override cfg again.
@miguel1118 Is there any Game/Tier breaking stuff?

**Comment by miguel1118** [comment]
Well I coulnd't mine those small ores with tinkers flint pickaxe, 
Im still in tier 0.5 so Im not sure if I would be able to mine them with tinkers iron pickaxe
I will replay again when I try it with tinkers iron pickaxe

**Comment by Dream-Master** [comment]
Tinkers flint pickaxe levels up once.

**Comment by miguel1118** [comment]
Ok i've cheked it up already, gt flint pickaxe can mine tier 1 ores (copper) which let you mine basaltic sand, cassiterite, aluminum and other ones, but tinkers flint pickaxe can't unless it lvl up mining level.

And since you get gt flint pickaxe before tinkers I think it shouldn't be able to mine tier 1 ores, according to questbook, I shouldn't be able to mine those tier 1 ores until quest book gave me Iron pickaxe head on tier 0.5 questbook "upgrade 2.0" quest:

"Find Iron, copper and tin ore, very funny. how you can mine it which just a flint pickaxe? I have an idea, bring me all your stone and I will give you a better tool head in exchange"

**Comment by Dream-Master** [comment]
So is this an issue or not. I mean break it Tiers?

**Comment by Dream-Master** [comment]
Ok Gt Flint Pickaxe is one level up the Tinkers Flint Pickaxe. Try to update you Pickaxe and you can mine the same as with gt one. It mine level 1 Ore wich are not much so i think not game breaking.
