### ISSUE TITLE
Wrought Iron Dust (for steel EBFing) can only be made by manually grinding ingots with a mortar.

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#849]
It should be doable with the usual machines, right? Pulverizer and Macerator, specifically?

**Comment by Drobac** [comment]
You can also use a Wrought iron ingot. Can get WI nuggets by smelting regular ingots in a furnace

**Comment by Dream-Master** [comment]
@Drobac Are here anything change from update 1.1.x.x to 12.x.x?

**Comment by Technus** [comment]
Changed macerate into to wrought iron.

**Comment by Dream-Master** [comment]
So it is the way it works.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/20773036/44d77a60-b750-11e6-9e6e-45d7a8059ab5.png)

**Comment by Wavepon** [comment]
It wasn't working that way on the server for me previously; in order to get the dust, I had to use a mortar. But as long as it works correctly I'm happy.
