### ISSUE TITLE
ServerCrash with EnderQuarry and BloodArsenal

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#850]
A problem regarding FakePlayers was found today, and a patch was proposed:
https://github.com/Arcaratus/BloodArsenal/compare/master...Namikon:patch-2

This issue is to keep track about that

**Comment by Dream-Master** [comment]
@Namikon Should we fork Blood Arsenal and make a own repro? 1.7.10 is not longer supported.

**Comment by Dream-Master** [comment]
@Namikon any news here?

**Comment by Namikon** [comment]
@Dream-Master it is merged since 11 September 2016, so I assume the latest release contains that fix

**Comment by Dream-Master** [comment]
cant build it need help.

**Comment by Namikon** [comment]
Stay tuned; Working on it
