### ISSUE TITLE
Order LV quests to help newbies

### ISSUE THREAD

**Issue by Tyecon** [GTNewHorizons/NewHorizons#851]
It would be nice if in LV there was order to the machine quests in the order of Bending Machine, Wiremill, Chemical Reactor+Fluid Solidifier as to save materials for other machines. What machines should I make first is a common question.

**Comment by KaneHart** [comment]
Not a bad idea. They kind of throw you to the wolves once you hit LV in a way. Should have a better ordering system to it.

**Comment by Dream-Master** [comment]
Yes will rearrange it.

**Comment by Dream-Master** [comment]
working on it.
![image](https://cloud.githubusercontent.com/assets/2970688/21594174/b1cd86ee-d11f-11e6-910b-50dfc39327d9.png)
