### ISSUE TITLE
Lilith Crash

### ISSUE THREAD

**Issue by Chicken9000** [GTNewHorizons/NewHorizons#856]
Lilith from Witchery crashes anyone who is near her to the launcher. 

She didn't do it in a previous version of the pack, not sure what changed to do it.

**Comment by Dream-Master** [comment]
@Chicken9000 Crash log please.

**Comment by Dream-Master** [comment]
Maybe same problem with the potion ids.

**Comment by Mylezz** [comment]
yea same problem me and Lazorpie had its a Potion ID issue

**Comment by Dream-Master** [comment]
Yes I will change potion Ids from witchery back.
