### ISSUE TITLE
HV Requirement for MV Quest

### ISSUE THREAD

**Issue by Zaromas** [GTNewHorizons/NewHorizons#857]
Hi all,

I don't know if this was a recent gregification, but since ender io item conduits require 256 to craft in assembly table, it's not possible to complete the "MV" quest if you're not at HV yet. Are you just supposed to return to it later? 

Thanks!
Z

**Comment by Dream-Master** [comment]
Needs to be change.

**Comment by Dream-Master** [comment]
Ok will change that recipe to 120 EU/t
