### ISSUE TITLE
Unable to craft cut Firestone in precision engraver

### ISSUE THREAD

**Issue by Canhos** [GTNewHorizons/NewHorizons#858]
The Raw Firestone gems will not stack, to get them to the 4 units required in the recipe. Need recipe change or something.

**Comment by Dream-Master** [comment]
Screenshot please from the recipe needs to be changed.

**Comment by Drobac** [comment]
Which version of the pack are you on? i was certain we fixed that one

**Comment by Wavepon** [comment]
Can confirm on the EU live server, Raw Firestones don't stack.

**Comment by Wavepon** [comment]
Maybe a Firestone Block could be used instead?

**Comment by Dream-Master** [comment]
But then it can't be compressed if it not stacks.

**Comment by Wavepon** [comment]
Perhaps the block can be made with 8 firestone dust and one raw firestone in an assembler or engraver.

**Comment by Canhos** [comment]
I'm on the most current version. 4 dust and one raw combined in an HV assembler would be similar cost i think.

**Comment by Dream-Master** [comment]
Will add a new recipe.
