### ISSUE TITLE
[Suggestion] add Garden Stuff mod

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#859]
The proposed mod: https://minecraft.curseforge.com/projects/garden-stuff

I have played with Garden Stuff before, and it has compatibility modules for Forestry and Natura (and possibly Extra Trees as well). It contains very nice aesthetics in the form of wooden and "Wrought Iron" blocks to make natural-looking constructions. The mod's "Wrought Iron" can probably be replaced with GregTech Wrought Iron to bring the mod into balance with GregTech.

The important blocks for Garden Stuff are:

The compost bin, which turns seeds and other plant items (like wooden logs and harvested crops) into compost, which can then be made into garden soil.

The bloomery furnace, which turns iron, charcoal, and sand into wrought iron. This block should be disabled, to prevent it from overtaking the Arc Furnace's functionality.

And the garden soil, which is made from dirt and compost and boosts plant growth. It is essentially better farmland. The recipe for garden soil could be altered to require LV processing (perhaps a Mixer recipe?), thus ensuring that the player can access Wrought Iron and garden soil easily all at once, without making farming too easy early on.

It also adds flower pots and miniature gardens, thus replacing the functionality of Botany.

---

Botany fails, for me, as an aesthetics mod for one major reason:

https://gyazo.com/ecf901c09d2eba67696d01be05e51b1b

It looks like this! Awful, awful! This mod fails in the most basic way, by failing to provide quality aesthetics when aesthetics is almost its only function. Even trying to determine the soil quality, a basic necessity of the mod, is made significantly more difficult, as the indicators of soil quality are visual in nature. Additionally, major items like the Florists' Encyclopedia simply do nothing and only serve to waste the player's time. Binnie has also disappeared from modding, and the mod itself is not open source, so these issues cannot be fixed. On the other hand, Garden Stuff's source code is available publicly, so these kinds of issues can be managed and resolved.

**Comment by Wavepon** [comment]
Update based on something I found from Binnie's issue repository: 
https://bitbucket.org/binnie567/binnie-mods/issues/374/botany-black-textured-soil

Apparently, the black textured soil can be fixed by turning on smooth lighting. Our variant of the black-textured soil occurs because our light level 0 is pitch black; without hardcore darkness, it would look more like the screenshot in the link.

However, I don't like smooth lighting... and this doesn't address the many other issues with the mod.

**Comment by Technus** [comment]
Botany adds ceramic and glass tiles tho.

**Comment by Wavepon** [comment]
It looks like Botany is baked into the Binnie's Mod jar. And I'm sure people have made Botany stuff already. So maybe a better solution would be to leave it in, but make the useless crap uncraftable. Like the florists' guides.

**Comment by Technus** [comment]
Ye it has deprecated shit included

**Comment by Dream-Master** [comment]
No I don't want to disable a part of a mod. Add Gardencraft have to suggested to us Forum on Enjin.

**Comment by Dream-Master** [comment]
I think we have enough mods rn.
