### ISSUE TITLE
need Mutatron to make Mutatron? vindictive bee mutation missing in NEI

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#860]
Mutatron (2131) needs Bee Receptacle (6828) which needs Plutonium Comb (6825:701) which needs Vengeful & Vindictive & Avenging bee, which show as nei only in Mutatron , not with normal breeding.

So either NEI shows it wrongly for just those 3 bees, or you Mutatron needs Mutatron = circular dependency

**Comment by bigbass1997** [comment]
Look up the recipe for the Avenging bee, that should show you the rest of the tree. And it's possible that NEI just missed it. If breeding something using the Mutatron is possible, then it should also be possible to do that breed by hand, whether NEI shows it or not.

**Comment by ghoulsblade** [comment]
I got Vindictive by manual breeding, so that at least works. Will try the rest when i have them pure and prereqs :)

**Comment by Dream-Master** [comment]
Is this a visual bug or a real one?

**Comment by ghoulsblade** [comment]
i got avenging just today, took a while but worked, so can confirm its just a visual glitch in NEI

**Comment by Drobac** [comment]
Yep it is a visual glitch, shows the entire tree when checking Avenging bees, doenst show the tree for vengeful.
