### ISSUE TITLE
Questing bug making quest rewards unclaimable

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#861]
After joining a party with someone, certain quests that they have completed become completed on my quest progress. But the retrieval tasks in those quests are still listed as uncompleted, and the reward is not claimable. The tasks listed as not completed will not change even if I fulfill the requirements for them.

![2016-12-03_10 35 16](https://cloud.githubusercontent.com/assets/17787093/20858758/5deea28a-b944-11e6-8c87-8eb58bcdf1ae.png)
![2016-12-03_10 36 00](https://cloud.githubusercontent.com/assets/17787093/20858759/60072b82-b944-11e6-884b-0e2e26339bea.png)
![2016-12-03_10 36 05](https://cloud.githubusercontent.com/assets/17787093/20858760/6228d10e-b944-11e6-961e-cd3b362babaf.png)

Gardener listed as completed with claimable rewards.
![2016-12-03_10 37 12](https://cloud.githubusercontent.com/assets/17787093/20858809/7b3e7576-b945-11e6-92f9-1868247eaa86.png)

Rewards unclaimable and tasks listed as uncompleted.
![2016-12-03_10 38 11](https://cloud.githubusercontent.com/assets/17787093/20858812/8c0a5b54-b945-11e6-8b67-f6476a74a51f.png)

I did all the quest requirements, and nothing changed in the quest.
![2016-12-03_10 37 51](https://cloud.githubusercontent.com/assets/17787093/20858827/9d7fc496-b945-11e6-92ed-a1f999c51c34.png)

**Comment by Dream-Master** [comment]
@KiloJoel Are you play on a Server?

**Comment by KiloJoel** [comment]
I play on the official EU server

**Comment by KiloJoel** [comment]
This is the task that is not complete.
![questnotworking](https://cloud.githubusercontent.com/assets/17787093/21591871/10ab1c3c-d100-11e6-9d88-fea421622f9d.PNG)

I have the required items in my inventory.
![capture](https://cloud.githubusercontent.com/assets/17787093/21591903/48435dc6-d100-11e6-9e90-2affaa0a1350.PNG)

When I press submit, it doesn't change the state of that task.

**Comment by Dream-Master** [comment]
Maybe the Quest is bugged i can can rest it if you want.

**Comment by KiloJoel** [comment]
That would be good. Could you also reset "animal farms" in tier 0.5?

**Comment by Drobac** [comment]
Poke me when you see me online, ill reset it for you

**Comment by Dream-Master** [comment]
Thanks Drobac
