### ISSUE TITLE
Occasional crash to launcher when mousing over GregTech items in the Forestry Worktable

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#862]
http://pastebin.com/30WDsP0A

I've crashed twice now, and both crashes throw the same error. It seems to be only when working with GregTech crafting items (pumps, cables, etc).

**Comment by Dream-Master** [comment]
It has Forestry in the Stack trace too. @technus any idea.

**Comment by Ugachaga** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/720

**Comment by Dream-Master** [comment]
Ok thanks for linking it how we can fix it ? @Ugachaga

**Comment by Dream-Master** [comment]
Maybe fixed.
Using GT 5.09.27.01 for it.
