### ISSUE TITLE
Hatchery needs undefined block to craft

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#864]
Hatchery (1418:5) is a part for bee alveary multiblock, it needs tile.for.apiculture.1.name (754:1) to craft according to nei, theres no recipe for that either

**Comment by Wavepon** [comment]
Looks like it's supposed to be either an Apiary (damage value 0) or a Bee House (2).

**Comment by Dream-Master** [comment]
Maybe some Ids are changed. Will look into it later.
