### ISSUE TITLE
wire-wrap quest requires 1c2 rubber

### ISSUE THREAD

**Issue by bcg17** [GTNewHorizons/NewHorizons#865]
the wire-wrap quest in the steam category asks for ic2 rubber not gt rubber

as you can see in this image it doesn't have a chemical value
![image](https://cloud.githubusercontent.com/assets/5795530/20864223/9cdbc9a2-b9b5-11e6-82b6-e9620c958205.png)

and if i click on it to see hows its made and hover over it displays it as ic2 rubber

![image](https://cloud.githubusercontent.com/assets/5795530/20864227/d2b7c6de-b9b5-11e6-9304-6c8821a66528.png)

**Comment by Dream-Master** [comment]
I fix it already. Try to use /bq_admin default load

**Comment by Technus** [comment]
ppl in the main server and prospercraft report it also.
