### ISSUE TITLE
"EBF-Time" Quest missing certain blocks

### ISSUE THREAD

**Issue by thePalindrome** [GTNewHorizons/NewHorizons#866]
Given that many other quests give you a step-by-step guide to building the entire project, and EBF-Time attempts to do the same, I'm presuming this is a bug.

In order to satisfy the Multiblock Structure, a Maintenance Hatch is required. This is missing from the quest.

In order to power it, you have to have 2 LV Energy Hatches. The Quest requires a single one.

If you like I can make the pull request.

EDIT: In addition, a simple guide to maintenance would be appreciated. Being new to GregTech I did not realize you only needed to solve one issue.

**Comment by Dream-Master** [comment]
So far I know ebf need 4 energy hatches in the quest line. Try to using version 1.2.1.0 and use command /bq_admin default load     To using lastest quest Update.

**Comment by thePalindrome** [comment]
Ah, my bad, it was fixed recently.

**Comment by Technus** [comment]
the ebf needs 3-4A from adjecnt battery buffers and should work even with 2 energy hatches.
