### ISSUE TITLE
DreamMaster is on Holiday and is obviously working very hard still. 

### ISSUE THREAD

**Issue by Canhos** [GTNewHorizons/NewHorizons#867]
How to make him unplug for at least the majority of each day for the next 2 weeks? I have tried to Kick him, but the button doesnt' work.

**Comment by KaneHart** [comment]
I'm new here but he is probably like me in a lot of ways. He enjoys this with a passion. Him being unplugged would probably make him actually sad inside. He enjoys what he enjoys and you can' take that away from him :P

**Comment by Dream-Master** [comment]
All is fine if I have spare time I will look into it if not I don't care so long I am in Holidays.

**Comment by Canhos** [comment]
Thanks for playing. I'll close this now.
