### ISSUE TITLE
Tungsten Bee not breedable

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#868]
Tungsten Bee (id=4690 Forestry) shows no breeding info in NEI ("Bee Breeding" tab, "Mutatron Tab" and "Bee Breeding Tree" all come up empty). It is needed for Iridium Bee (requires block of iridium to breed)

**Comment by Technus** [comment]
Bee breeding plugin has issues.

**Comment by Dream-Master** [comment]
If this is a Bee I add via Gendustry we can look into it and check if the configs are written wrong if not then it is more difficult.

**Comment by ghoulsblade** [comment]
gendustry\bees.cfg Line 2160: mutation: 3% "forestry.speciesHeroic" + "gendustry.bee.Manganese" => "gendustry.bee.Tungsten" Req Block B:gregtech:"gt.blockmetal"@11

i guess thats the one, will try in a few days if it works even without nei showign it, but need to breed heroic first

**Comment by Dream-Master** [comment]
So possible a nei bug.

**Comment by ghoulsblade** [comment]
Fix:
`B:gregtech:"gt.blockmetal"@11`
should be
`B:gregtech:"gt.blockmetal7"@11`
gendustry\bees.cfg Line 2160

Reasoning:
All the other gt.blockmetal entries had a number after them, and 7 is what opencomputers robo inventory upgrade scanned tungsten block (1191:11) as "gt.blockmetal7.11.name"
For comparison, platin block (1189:12) shows as "gt.blockmetal5.12.name" in robo and the Platinum bee mutation worked fine with B:gregtech:"gt.blockmetal5"@12.
The block gt.blockmetal base id seems to be 1184, which gives 7 for platin:1191-1184 and 5 for tungsten:1189-1184.

**Comment by Dream-Master** [comment]
Did you change the config and test it.

**Comment by ghoulsblade** [comment]
Dirthuts admin LameGirlyCurly just applied it on the server config and is restarting at the moment, i'll try to breed it again right after than and report if it works :)

**Comment by Technus** [comment]
But it is the cause for sure.

**Comment by ghoulsblade** [comment]
And its not just a nei bug, i've been trying to breed the wicked thing without success for a few days.

**Comment by Dream-Master** [comment]
Does it work now?

**Comment by ghoulsblade** [comment]
will take a while longer, i noticed i was using steadfast instead of heroic as parent, trying to mutate heroic now but that needs forest biome and apparantly my rwg_temperateForest doesnt count, or i'm just having bad luck

**Comment by ghoulsblade** [comment]
worked, got tungsten :)

**Comment by Dream-Master** [comment]
Nice can you make a pull request please in the 1.3.0.0 branch. Thanks.

**Comment by ghoulsblade** [comment]
urr, never done that but here goes, see above
