### ISSUE TITLE
Pumpkin seed (/w Soft mallet) recipe gives two seeds

### ISSUE THREAD

**Issue by Kuzym** [GTNewHorizons/NewHorizons#869]
There are two pumpkin seed recipes, one that uses a hammer and another that uses the soft mallet. Both convert pumpkin to seeds at a 1:1 ratio. The same recipe for watermelons gives only one, with the hammer being superior.

**Comment by Dream-Master** [comment]
Ok need to check the recipes.

**Comment by bigbass1997** [comment]
Here are the recipes, top is hammer, bottom is soft mallet.

@Kuzym Not sure what you see problematic about either of these recipes. You get more seeds per melon/pumpkin when you use the Hammer, than when you use the Soft Mallet.

![pumpkin](https://cloud.githubusercontent.com/assets/790116/20996830/1913082e-bcc6-11e6-84b5-b2ef3f76c93d.png)
![melon](https://cloud.githubusercontent.com/assets/790116/20996834/1f7beb0e-bcc6-11e6-8fb6-b05a32b69847.png)

**Comment by Dream-Master** [comment]
Can this be closed?

**Comment by bigbass1997** [comment]
I see no issue here. So unless you see an issue, yes it can be closed.
