### ISSUE TITLE
Thaumcraft.cfg is missing in 1.2.1.0

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/NewHorizons#871]
When doing clean install (deleting pack and installing it again in technic launcher) thaumcraft.cfg is not downloaded for some reason. This results in default thaumcraft.cfg with it's ore generation enabled.

**Comment by Dream-Master** [comment]
Ok need to check it.

**Comment by EvgenijM86** [comment]
Update: 1.2.0.0 is also affected by this. 1.1.0.4 is not affected.

**Comment by Dream-Master** [comment]
Ok will re add the cfg file.

**Comment by Dream-Master** [comment]
Is fixed in the next update
