### ISSUE TITLE
Manyullyn Plates recipe issue

### ISSUE THREAD

**Issue by Azzyj** [GTNewHorizons/NewHorizons#872]
I'm trying to make a Manyullyn Crystal 7732.   To do so requires a plate 7468.  If you take a standard Manyullyn Ingot (6026:11386) & plate bed it, or extrude it, you get Manyullyn Plate 6026:17386 which will not make a Manyullyn Crystal.    I'm still experimenting to see if I can make Plate 7468 but it seems that recipe should include the use of either plate.

**Comment by Drobac** [comment]
I will double check ingame, but unless something changed in the last update, they worked fine for me

**Comment by Azzyj** [comment]
I was able to make the correct plate but only by making a block of Manyullyn & placing it in a cutting saw.

**Comment by Dream-Master** [comment]
Have to check the recipe. Maybe this is the way it had to work or a recipe is overridden by a script.

**Comment by Drobac** [comment]
The issue is that the crystal recipe uses 7670 Manyullyn plates (from the core mod) and the only ones you can get is the 5876:17386 (from GT). So just switch the crystal recipe to use the GT plates

**Comment by Dream-Master** [comment]
Ok will do.
