### ISSUE TITLE
Coil Quests are crafting tasks

### ISSUE THREAD

**Issue by Shuezo** [GTNewHorizons/NewHorizons#873]
In the questbook under multiblock goals, the coil Quests are crafting tasks, however, coils are now only made through assembling machines. They should be set to retrieval non consume, instead.

**Comment by Dream-Master** [comment]
So far I know this is fixed in 1.2.1.0 because of new ingredients for coils. Try to refresh the Quests /bq_admin default load

**Comment by bigbass1997** [comment]
The main EBF quest that needs Cupronickel coils is a retrieval task, however the Kanthal and Nichrome coil quests are crafting quests. I just checked myself too.

**Comment by Dream-Master** [comment]
Ok need a change then.
