### ISSUE TITLE
Alternate Capacitor Bank recipe wrong

### ISSUE THREAD

**Issue by Naolas** [GTNewHorizons/NewHorizons#874]
The "upgrade" recipe for EnderIO 5M capacitors asks for 2x5M capacitors, instead of 2x1M capacitors.

![5mcap](https://cloud.githubusercontent.com/assets/4760479/21016283/5492b378-bd65-11e6-9a37-949af25cdb1d.png)

**Comment by Dream-Master** [comment]
Need to check it.

**Comment by Dream-Master** [comment]
I remove the recipes because of Balancing.
