### ISSUE TITLE
Problems with better questing

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#876]
Since very early on (Tier 0) I have worked together with a friend on the official server. he at some point did some quests and to my surprise, while they are marked as complete, I can't "cash" them, since all the subcomponents are marked as "incomplete" while they clearly are in my inventory (even when I press manually submit).

Some screenshots:

https://i.imgur.com/WqjVykf.png
https://i.imgur.com/lfoZTlP.png
https://i.imgur.com/2UpBymC.jpg (look in lower bar, I have the items)
https://i.imgur.com/VaSk22k.png (these 2 quests seem to have the same problem, even though I am sure my partner hasn't finished the top one yet)

**Comment by KaneHart** [comment]
tbh, people should not be getting double rewards from this period.. Not sure if it does but if 2 people work on a quest only one reward should be given.

**Comment by Dream-Master** [comment]
Will see if it is the same with better questing 2 mod.

**Comment by mtesseracttech** [comment]
KaneHart, what would be the point of doing the quests together then?

**Comment by TheRealHypo** [comment]
Sometimes we've seen, that If there is written a 0/x unter the required Item, we have to craft them again.

if there is just "16x Copper Ore" for example, no 0/16. Then you just need it in Inventory.

**Comment by Dream-Master** [comment]
@mtesseracttech So does it work now?

**Comment by Dream-Master** [comment]
ok but i can close this now?
@KaneHart 
@TheRealHypo
