### ISSUE TITLE
Ur-Ghast Bee Mutation not working

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#878]
Tried for dozens of cycles with thaumium block (thaumcraft) and thaumium block (gregtech) below alveary in nether (both undergarden and actual hell biome) with electric stimulator 4x mutation upgrade that should raise the chance to about 25% per cycle. Also tried mutator block in alveary  a few times with endereyes, that also failed. Temperature in Both biomes is hellish and humidity is arid, so should be ideal for the bee, also both parents have 5/5 both tolerances. The base chance is 5% so it shouldnt be that hard.

config\gendustry\bees.cfg Line 2175: mutation: 5% "gendustry.bee.Hydra" + "gendustry.bee.ThaumiumDust" => "gendustry.bee.UrGhast" Req Block B:Thaumcraft:blockCosmeticSolid@4 Req Temperature Hellish

On Dirthuts server.

**Comment by ghoulsblade** [comment]
it did work with single block apiary in a few tries. odd, i did use alveary sucessfully for a mutation already, not sure where the block has to be with it tho, i had it directly below the center of the bottom 3x3

**Comment by Dream-Master** [comment]
@ghoulsblade only this mutation not work or others too ?

**Comment by ghoulsblade** [comment]
Bees can live in a single-block apiary or in a multi-block alveary.
The Alveary Multiblock is expensive and allows upgrades for higher mutation chance.
I tried the mutation in the Alveary Multiblock with this Bonus many times, and had the required thaumium block below the center of it, and the mutation didnt work.

Then i tried with the single-block apiary and the mutation worked.

So i'm guessing a single metal block below the center of the multiblock alveary does not work, maybe 3x3 are needed in that case, but i dont know for sure and i finally got my bee so i'm happy :)

**Comment by Dream-Master** [comment]
Can you test that in creative in a separate world and report the result here?

**Comment by ghoulsblade** [comment]
Maybe this weekend, too busy in the next few days.

**Comment by Dream-Master** [comment]
@ghoulsblade 
Any news here can this be closed?

**Comment by ghoulsblade** [comment]
Yeah, can close it, works decent enough as long as  you dont use a multiblock alveary. I'm guessign the multiblocks wants 3x3 blocks below it but, its very timeconsuming to test due to the low mutation chance and singleblock apiary worked for me so no urgent need.

**Comment by Dream-Master** [comment]
ok
