### ISSUE TITLE
File Cabinet Bug

### ISSUE THREAD

**Issue by TheRealHypo** [GTNewHorizons/NewHorizons#879]
Two problems with the File Cabinet.

1. If there are too many different items in it, there are missing textures and while scrolling, some of the first columns move elsewhere.

2. At some point ( can't reproduce it at all time ), with many different items in it, it gets impossible to Shift+Click Items into it. Also if i do it manually, it works, but taking out any other item let's me pickup the item I wanted to put in with Shift+Click.

**Comment by Dream-Master** [comment]
I guess this is a Extra Utilities Bug so not much i con do here. Extra Utilities isnt open Source.
