### ISSUE TITLE
Feature Request: Questline for Power Generation beyond Steam

### ISSUE THREAD

**Issue by TheRealHypo** [GTNewHorizons/NewHorizons#880]
As explained to bigbass1997 in Dischord:

There is need for a quest line that introduces Power generation beyond Steam.
Could be done in a way that there is "Basic Power Generation" with a little quest text to explain it.
Then multiple optional Questlines, for the different types of Generation at that point (Biogas, Creosote, etc.)

**Comment by Dream-Master** [comment]
Sure will add more QUests when i am back.

**Comment by Dream-Master** [comment]
Added a Quest for Diesel Engine and Gas Turbine. More will follow.

**Comment by Dream-Master** [comment]
Oil and Diesel Quest are done.
Will add some Biogas and Ethanol Quests.

**Comment by Dream-Master** [comment]
Ok i add a Bio Gas Questline. Maybe Ethanol i can add more.

**Comment by Dream-Master** [comment]
Bio Gas and Ethanol are added.
