### ISSUE TITLE
Kill All Things Quest Error

### ISSUE THREAD

**Issue by Azzyj** [GTNewHorizons/NewHorizons#881]
Ghast Evolved Quest Error:  The quest indicates that you must kill an Evolved Ghast on Ceres to obtain the tier 4 key.  It's actually an Evolved Blaze that gives the key, and I have completed the task but the quest does not update.

**Comment by Drobac** [comment]
I was sure we fixed that one as soon as GS updated. Ill look at it when i get some spare time

**Comment by Azzyj** [comment]
It's possible I killed it before the last update.  I just noticed the quest this morning.  I'll pop back to Ceres and kill him again.

**Comment by Dream-Master** [comment]
@Azzyj try with newest Quest file 1.2.1.0 and do /bq_admin default load
