### ISSUE TITLE
Hardcore darkness crash

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#882]
When I set in RandomThings.cfg
Hardcore Darkness=false
LockedGamma=false

The game crashes upon entering any world.
Wasn't the case before the update.

Crash log says just
java.lang.Error

**Comment by Dream-Master** [comment]
Then better change it back. This pack is made for Hardcore Darkness.

**Comment by Methes** [comment]
Sure, that's an option.
Although all Hardcore Darkness realistically does is create ugly shadows in the world.
You always skip the night for solars anyway.
You never go caving because there is no point.
If you have optifine, you can just hold a torch and walk around with that.
If you have shaders, you can skip the darkness altogether.

If at any point you get stuck outside at night and can't rest/nobody else rests, you just dig in the ground and wait 10 minutes.
