### ISSUE TITLE
Private Server Crash

### ISSUE THREAD

**Issue by frbitato** [GTNewHorizons/NewHorizons#883]
Running a private server for me and a couple of friends.  Things have been running fine for about two weeks, but yesterday I was getting some lag on my end (hosting server on same machine as game), so I closed the server out and relaunched.  Today, we're in the Twilight Forest, clearing out one of the hills, and every couple of minutes the server will just crash.  It always relaunches fine, but the crashes are occurring closer and closer together.  We're running GT NH server 1.2.0.

[crash-2016-12-11_15.03.00-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/644790/crash-2016-12-11_15.03.00-server.txt)

**Comment by bigbass1997** [comment]
Looks like something related to a potion problem in SpecialMobs.

Stack trace points to https://github.com/FatherToast/SpecialMobs/blob/master/src/main/java/toast/specialMobs/entity/witch/EntityDominationWitch.java#L96

**Comment by frbitato** [comment]
Yeah, I had looked at the crash logs and saw that, figured it was some sort
of potion-related issue in one of the mods.  Do you know if this was fixed
in the server update, or do you know how i can correct this?  Thank you for
getting back to me so quickly, by the way!

**Comment by frbitato** [comment]
Relaunched everything, and the witch that I thought was crashing things was gone.  Everything is back to working fine for now, but I'm concerned about facing another witch.

**Comment by Dream-Master** [comment]
It seems to be a potion Id conflict. I am not sure but we have a guess Galaxy space. Have some error two when brewing potion in witchery cauldron. On your End I think it is a mob throwing potions(special mobs). You chantry downgrading gs but I am not sure if you got more trouble. I add some code in the core mod for compatibility with ga 1.1.1. at the moment I am at Holidays and can't do much.

**Comment by Dream-Master** [comment]
Yes Witchery Potion have to be not higher then 128.

**Comment by Namikon** [comment]
No. That crash is caused by SpecialMobs using a field in his code that is client-side only. A different PotionID will not help here. A patched Version is currently on my todo list

**Comment by Dream-Master** [comment]
ok
