### ISSUE TITLE
 Add Thaumic upholstry to the pack? (Thaumcraft cosmetic)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#884]
This mod adds armor coloring and armor customizing to thaumcraft it looks cool and also might be a nice extra quest for end game to get one set of each color armor?????

Id like it in the pack so i can make my armor look cooler and better,

https://mods.curse.com/mc-mods/minecraft/228019-thaumic-upholstry#t1:description

Thanks, Mylez_

**Comment by Dream-Master** [comment]
Will look into the mod when I am back on a computer. :)

**Comment by Mylezz** [comment]
Ok!

**Comment by Methes** [comment]
That mod was buggy and I've never made it work. Looks like the mod author has made a new version called Thaumic Dyes though.
https://mods.curse.com/mc-mods/minecraft/251561-thaumic-dyes#t1:description

**Comment by Mylezz** [comment]
Thankyou! for finding this!

**Comment by Dream-Master** [comment]
so close this now.
