### ISSUE TITLE
Recipe change; Reinforced Ingot? + Blank Upgrade?

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#885]
I just tried to make an Upgrade modifier for Steve's Carts 2, and for the Blank Upgrade (7066:59) you need an Reinforced Plate. To make it, Yeah...

First you craft yourself some Stabilized Metal
Then you put the Stabilized Metal in you EBF to get an Reinforced Ingot (Steve's carts 2 version)
Macerate it to get Reinforced Dust (Gregtech)
Then put it in your EBF again to get Reinforced Ingot (Gregtech)
And then you can make your plate

But screw that, nobody here uses Steve's carts for anything more useful than tree farms I guess? so.. Cant we make the Blank Upgrade use Steel plates or aluminumumum plates instead? 💃

Being able to modify your carts should (almost) be unlocked in the same tier as you craft carts, right?

Right you you need an implosion compressor, diamonds and molten obsidian, and a few more MV machines quite alot just to modify a cart :P

**Comment by Dream-Master** [comment]
Will look inside it when I am back from Holidays

**Comment by Dream-Master** [comment]
Thinking about making forestry farms cheaper or increase the amount of blocks  you get out of the carpenter.

**Comment by Dream-Master** [comment]
Original recipe use reinforced metal ingots. So i will fix that you need to make reinforced metal two times.

**Comment by Dream-Master** [comment]
Need Core Mod 1.3.04 for it.
