### ISSUE TITLE
Broke progression/quests in tier 0.5 (?)

### ISSUE THREAD

**Issue by Kuzym** [GTNewHorizons/NewHorizons#886]
![stars](https://cloud.githubusercontent.com/assets/24378982/21123970/55cd2046-c0dc-11e6-965b-81d7bd1daa5f.png)

I'm in tier 0.5, and have just set up my smeltery. I haven't finished the ore quests yet. Then I found the Thaumcraft saplings and turned in that quest. It opened up the first Thaumcraft chapter (and nothing else, yet). Then I went to the chapter Novice Thaumaturge. It had the quest "Strange Things" which I turned in.

This opened up tier 4 and 5, It also unlocked tier 1. It didn't unlock tier 2 or 3. It also unlocked the chapter 'they are coming...', and a quest to build a vacuum freezer in multiblock structures. All of them seem to have empty quests called "New Quest" with a nether star icon (as seen in the screenshot) that then branch out into the actual quests. In some cases they are dead ends (again, as seen in the screenshot), in others they unlock content that is far above my current tier.

It might be worth mentioning I do not use the book itself, I just press the GRAVE key to access the quests.

**Comment by Kuzym** [comment]
By the way, I would really appreciate some instructions on how to fix my book if possible. If that's not easily done I'll have to reset it and do all the quests again, but I'd rather not. Thanks. :)

**Comment by Dream-Master** [comment]
Try to reload your quest first.    /bq_admin default load

**Comment by Kuzym** [comment]
That fixed the "new quest" icons and empty quests, and turned them into the appropriate quests. Unfortunately that still left me with a lot of locked quests so I reset the entire book and will work my way back up.

**Comment by Kuzym** [comment]
Okay, I replicated the entire path that I took through my quest book. After completing Strange Things (from Novice Thaumaturge) nothing unusual happened. Let me know if you'll need more information.

**Comment by Dream-Master** [comment]
So is it fixed on your side?

**Comment by Dream-Master** [comment]
you need to reload your Quests.
/bq_admin default load

**Comment by Kuzym** [comment]
Sorry, forgot to respond to this. The first time I simply restarted my whole quest book, but yesterday I encountered the bug again and used that command to fix it. Unfortunately it un-completed some tier 0.5 quests and left some higher tier chapters unlocked, but it hasn't broken progression I think. I'll update if that changes, but for now this can be considered resolved.

**Comment by Dream-Master** [comment]
Try to remove the Quest file reload it and add it back. Or go to edit mode if you play sp and reset those Unfinished Quests.
