### ISSUE TITLE
Arcane Assembler Crafting is bugged

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#887]
For the infusion Recipe for the Arcane Assembler from Thaumic energistics it wants the Wrong Wand, it wants the one u cant craft from default Thaumcraft.
ive tryed making the one it says to and i cant, So plz fix

D::::

**Comment by Dream-Master** [comment]
Need a pic not sure what you exactly mean.

**Comment by Mylezz** [comment]
kk 1 sec

**Comment by Mylezz** [comment]
https://gyazo.com/ca8ddbbc46b070e867d58762c237c24e

**Comment by Mylezz** [comment]
it wants the wand i cant make

**Comment by Mylezz** [comment]
This is the one i can make https://gyazo.com/14b02af5a1a0aa2a23076628809ef6c5

**Comment by Dream-Master** [comment]
Funny recipe I can't remember I did it. Will change it asap

**Comment by Mylezz** [comment]
Thx
