### ISSUE TITLE
Spice of life containers and eating speed

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#888]
Spice of Life containers have trouble syncing food eating speed. When you hold right click, food you eat on your client usually doesn't sync with server, so your hunger gets reset after a while and you have to eat again. Or the eating stutters and you visually eat one meal multiple times to catch up.
It's because of Hunger Overhaul'[ modifyFoodEatingSpeed=true.
Setting it to false fixes this problem (or not using spice of life lunchbags at all).

**Comment by Dream-Master** [comment]
I thought we fix that already? Did you using the last Version 1.2.1.0 of the pack?

**Comment by Methes** [comment]
Yes. I am using forge server though, not thermos. Did you fix that with some plugin or something?

**Comment by Dream-Master** [comment]
I thought it was fix in the config. @Namikon did we some Thermos config or plugin fixed this error/bug?

**Comment by Namikon** [comment]
Not that I remember. There was a major issue with the StackSize of food (Aka "exploding stacks") that got changed long ago, but nothing related to the consume-speed
