### ISSUE TITLE
Flawless emerald recipe

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#889]
Crafting Flawless Emeralds in the precison laser give no output, but uses up the input emeralds.

**Comment by Technus** [comment]
FFS DONT REPORT THINGS THAT I ALREADY TOLD U I FIXED

**Comment by Drobac** [comment]
that was for the lenses, and that is fixed. I havent seen this issue before

**Comment by Technus** [comment]
hmm

**Comment by Technus** [comment]
Turns out it was the same thing error XD
+1 retardness point

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/8b2096ea78d135b400a73b94712b8c4af2f4b4f5
