### ISSUE TITLE
Minor rubber quest discrepancy

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/NewHorizons#890]
**Quest #69 Wire-Wrap in Tier 1**
Makes you create 20 rubber bars and transform them into 10 rubber plates.

Following **Quest #67 Wired, weird?! in Tier 1**
Makes you create 4x tin cables (uses 4 rubber plates) and 6x copper cables (**requires 12 rubber bars**)

So basically in quest 69 you've "wasted" 12 rubber bars that you'll have to make again for quest 67.
It's no big deal since you'll use those extra rubber plates eventually, but it breaks the otherwise nice quest flow you've got going.

Also also, might be nice to not force people to make flint and steel and just detect the Nether - I've just let some planks catch fire near a portal frame and skipped the 6 steel ingots requirement for flint and steel only to be forced to complete it later on. VERY minor thing though.

EDIT:
Following **Quest #66 Time for some logic in Tier 1**
Makes you craft 4 Red Alloy Wires and 2 Tin Wires even though you've crafted them in Quest #67 already.

**Comment by Dream-Master** [comment]
Will look into it and change some amounts and stuff.
