### ISSUE TITLE
Cant Chisel Gregtech Marble D:

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#892]
I cant chisel it plz fix

![cant](https://cloud.githubusercontent.com/assets/23045776/21298669/d6123a5a-c548-11e6-8ef0-aed7cf0b40ff.png)

**Comment by Dream-Master** [comment]
Maybe have to add it to the marble group via minetweaker.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21587168/8157fc38-d0d9-11e6-8dbd-19c8fdb83653.png)
