### ISSUE TITLE
Compressed Gravel Is Missing a Recipe!!!

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#893]
Dose not have a recipe in NEI anc i cant Compress it D:
![geav 1](https://cloud.githubusercontent.com/assets/23045776/21299598/1b551a5c-c552-11e6-9c40-38ffa0db6890.png)
![grav1](https://cloud.githubusercontent.com/assets/23045776/21299599/1c1c7a8e-c552-11e6-8d77-97a520801d9b.png)

**Comment by Dream-Master** [comment]
Maybe it's overwritten by another recipe. Will look into it.

**Comment by VermillionX** [comment]
I believe it's overwritten by the Gravel Bricks recipe; which is the same, except it uses 1 gravel instead of 9 with integrated circuit 1 in the assembler.

**Comment by Dream-Master** [comment]
It can be only overridden by another compressor recipes with the same input item.

**Comment by VermillionX** [comment]
None of the compressed cobble, sand, dirt or gravel recipes are compressor recipes. They're all assembler recipes.

**Comment by Dream-Master** [comment]
Let me come back and I will check it.
