### ISSUE TITLE
Missing texture.

### ISSUE THREAD

**Issue by Mkez45634** [GTNewHorizons/NewHorizons#896]
Hi all, just making a note that the food Chocolate roll from Pam's Harvestcraft is missing a texture.
http://imgur.com/gallery/xh0wL

**Comment by Dream-Master** [comment]
Maybe a wrong named Texture.

**Comment by Dream-Master** [comment]
renaming localizer inside the file.
chocolaterollitem to chocolaterollItem

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21586989/4d36a96a-d0d7-11e6-900b-e6d4fccee940.png)

**Comment by Duxtorm** [comment]
;w; how do I do that?
