### ISSUE TITLE
Technic GTNH files have out of date/incorrect configs.

### ISSUE THREAD

**Issue by Saereth** [GTNewHorizons/NewHorizons#897]
Comparing to the curse download, latest version there are several major difference in the config including biome ids and aspect max caps. Curse seems accurate with server side files so this appears to just be an issue with the technic files. Additionally mob radar doesn't seem to work with the technic files but does with curse by default.

**Comment by Dream-Master** [comment]
Yes I forgot the Thaumcraft config in the client version.
Mob radar works because after 3 month curse team can't fix this issues because they too busy they said. I decided using the ultimate version of journey maps so that it works on curse clients.

**Comment by Dream-Master** [comment]
FairPlay version still not works when use Curse launcher.
