### ISSUE TITLE
Default worldguard configs causing issues on servers

### ISSUE THREAD

**Issue by Saereth** [GTNewHorizons/NewHorizons#899]
the default worldguard configs prevent anything from burning including GT pipes that are meant to when you use hot liquid in them, this allows basic wooden pipes to be used for steam etc. Additionally it prevents pam's rice from growing. Turning off WG fixed these issues for us.

**Comment by Dream-Master** [comment]
I will remove Thermos and all plugins out of the Serverpack and replace it with Forge. To many people can't configure Servers and the one this one who is able to do it can download it manually and add own plugins.

**Comment by Saereth** [comment]
It's not much of an issue to configure a server but its hard to know your intent as the pack creator. Firespread prevention means no lighting nether portals with vanilla burning wood for instance, which increased the early game difficulty for us. We had no way to know if this was intended behavior or not but when we ran into the progression breaking pam's issue we assumed not at that point. 

Either packaging with forge instead, modifying the default worldguard configs to what you recommend or just a wiki article would all be good solutions.

**Comment by Dream-Master** [comment]
As I said before we(all Server devs) decided to remove Thermos and plugins in the next update. I am right now on holiday can't do much. If you need some config please contact some admin on our Discord.

**Comment by Dream-Master** [comment]
Ok Forge is added and Thermos and Plugins removed.
