### ISSUE TITLE
'Time for some logic' quest displaying wrong item

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/NewHorizons#900]
In the 'time for some logic' quest in tier 1 of the quest book, one of the tasks is to craft 2 refined iron item casings.
Refined iron item casings don't exist in the pack, however crafting steel item casings completes the task.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Dream-Master** [comment]
The problem here is that i rename it via Minetweaker. Maybe i have to change the localizer inside ic2 file.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21586826/8f0814de-d0d5-11e6-8374-582b293fb025.png)
