### ISSUE TITLE
Naga Stone Connected Textures are bugged D: (Low Priority)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#901]
![f33e7a0a703e5858ecf151993d69f192](https://cloud.githubusercontent.com/assets/23045776/21374283/801bd4f6-c6da-11e6-8d0d-b3df5c6e9e8b.png)
![baee86f3dd2f343b60d456f8047146e7](https://cloud.githubusercontent.com/assets/23045776/21374285/81d8245c-c6da-11e6-942b-42aa0f80050d.png)

**Comment by Dream-Master** [comment]
@Technus 
Any idea how to fix.

**Comment by Technus** [comment]
I would fix it like this: (look at labels)

**Comment by Technus** [comment]
Probably can be solved with correct block placement but imma not sure

**Comment by Mylezz** [comment]
Tryed that alredy

**Comment by Dream-Master** [comment]
Can we fix that inside TF mod ?

**Comment by Dream-Master** [comment]
@Mylezz 
If you can fix it good if not i close this.

**Comment by Drobac** [comment]
Don't think this is something that can be fixed by use but needs to be adressed by the TF dev

**Comment by Dream-Master** [comment]
TF is no longer updated so i guess the dev is gone away.
