### ISSUE TITLE
Multiblock Goals - EBF Coils

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#903]
Need to switch all the Coil quests from crafting to detections as they cant be crafted by hand anymore but require the use of an assembler.

**Comment by Dream-Master** [comment]
Yes I will change all coil quests when I am back.

**Comment by Drobac** [comment]
Also the quest High Speed Charcoal - reduce coke oven and infernal brick to 68 each as the recipe gives 2x adv coke oven brick

**Comment by Dream-Master** [comment]
So the amount is wrong?

**Comment by Drobac** [comment]
When finished with the quest you have enough bricks to make 2x adv. coke ovens. Think 1 is enough as the bricks are expensive at that tier. Also the adv. coke oven cant actually make coal coke so thatll need to be added

**Comment by Dream-Master** [comment]
K

**Comment by siriulx** [comment]
@Dream-Master 
The GT achievement for EBF Coils also need to be fixed.
And I also found another issue: the assembling recipe EBF Coils + Chip No.8 ---> 16x cables doesn't cost any coil.

**Comment by Dream-Master** [comment]
@siriulx 
All Coils need 2x wire 8 times so you get 16x wire. What is wrong here ? Send me some pic about wrong recipes please.

**Comment by Dream-Master** [comment]
What is wrong with the archivents can you send me a pic here too ?

**Comment by siriulx** [comment]
@Dream-Master 
![image](https://cloud.githubusercontent.com/assets/6583339/21784058/fa04cbb2-d687-11e6-864f-e461b0f81dfc.png)
![image](https://cloud.githubusercontent.com/assets/6583339/21784077/16b37a74-d688-11e6-9570-f36e824a9972.png)

All type coils don't get consumed in this process.

The GT EBF coils achievements triggered by normal crafting, And using assembling machine won't trigger those achievements.

**Comment by Technus** [comment]
Coil reverse recipes are fixed in dev.

**Comment by Dream-Master** [comment]
@Technus how we can change the archivements detecting the coils only ?

**Comment by Technus** [comment]
Moved to onItemPickup
