### ISSUE TITLE
Inventory Tweaks missing from Server files

### ISSUE THREAD

**Issue by Saereth** [GTNewHorizons/NewHorizons#904]
Inventory tweaks is missing from the server files, this was causing us some pretty serious desync issues with inventories. Adding the inventory tweaks jar to the server files cleared the issue up. It may be a good idea to include it with the server files by default.

**Comment by Dream-Master** [comment]
Never know it is necessary to be on the Server. @Namikon need we add inventory Tweaks to the Server?

**Comment by Namikon** [comment]
It's not on the EU Server and we didn't have any Issues for ages (In fact we had, when it was present Serverside), so imho we don't need to add that

**Comment by Dream-Master** [comment]
I add it client side @Namikon

**Comment by Namikon** [comment]
After some investigation of the code from bigbass, it appears that the mod doesn't do anything spectacular if added server side. However: The function to auto-refill should be disabled by default; As it acts weird with GregTech items. We had InvTweaks long ago, and we had the same issues. Disabling Auto-Refill will solve most desync-issues

**Comment by Dream-Master** [comment]
@Namikon , @bigbass1997 
Did we need to add the mod to the server or not the next update ?

**Comment by bigbass1997** [comment]
@Dream-Master No. Do not add it. There's no reason to.

But do remember to set the default config for the auto-refill option to false for clients.

**Comment by Dream-Master** [comment]
ok will do. Thanks.
