### ISSUE TITLE
Microblock saw and railtech steelblock

### ISSUE THREAD

**Issue by Pockyninja** [GTNewHorizons/NewHorizons#905]
When making a witches furnace I was required to make a saw for micro blocks. I made a rather basic mistake of not realizing the rods used are not gregtech steel rods, as used in every other tool which uses a rod, but instead requires a Tinkers construct rod. I find this odd as the gregtech changes to the micro block saw has already been altered to account for the gregtech saw blade. I think it would make more sense for it to also use steel rods from gregtech.

On a sort of side note it also requires you to cut a railtech steel block. The only way I have managed to make one of those is compress steel and then use a chisel to change the block type to the railtech one to then cut and make into the iron block fence. If this is truly the intended path then maybe a quest would help make this more clear.

**Comment by Dream-Master** [comment]
Will look into it.

**Comment by Dream-Master** [comment]
This is are the vanilla recipe i not touch them because of some reason it dint work. I will try to ordict the things.
