### ISSUE TITLE
Awakened ichor pick wont infuse

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#908]
all the item's are correct and i have the vis but it wont start the infusion

![asas](https://cloud.githubusercontent.com/assets/23045776/21473334/852abf2c-cabb-11e6-952d-047eab747eae.jpg)

**Comment by Dream-Master** [comment]
I need to check the recipe when I am back.

**Comment by Dream-Master** [comment]
ok i remove nbt data from the Galgadorian drill heads and it works for me.
