### ISSUE TITLE
hv laser engraver: 3 diamonds to flawless diamond recipe broken

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#910]
hv laser engraver: put 3 diamonds and a glass lens in and you should get a flawless diamond.
instead it consumes the diamonds and even the lens and provides no output, tried 3 times,
also with industrial diamonds and a diamond lens.

**Comment by ghoulsblade** [comment]
possibly related: https://github.com/GTNewHorizons/NewHorizons/issues/889

**Comment by Dream-Master** [comment]
Why you open it up again?

**Comment by ghoulsblade** [comment]
i just clicked the wrong button when posting the link, if you can confirm its the same bug you can close it

**Comment by bigbass1997** [comment]
Yes #889 is the same bug as yours. Also this issue has already been fixed in https://github.com/GTNewHorizons/GT5-Unofficial/commit/8b2096ea78d135b400a73b94712b8c4af2f4b4f5

The fix will be active whenever the modpack updates next.
