### ISSUE TITLE
Electric/Nano Wings not chargeable

### ISSUE THREAD

**Issue by meonester** [GTNewHorizons/NewHorizons#913]
Crafting electric and nano wings (and quantum? - needs checking) in infusion matrix produces one with no meta(damage) value, therefore it cannot be charged anywhere.

**Comment by Dream-Master** [comment]
Try to damage the item or wear it or try to discharge it. Minetweaker scripts can't output Infusion recipes with meta data. I am too lazy add all the recipes to java code. When I am back on a computer 1.1.17 I will look at it.

**Comment by meonester** [comment]
Tried all i could think off, failed to find any workaround.

**Comment by Dream-Master** [comment]
Ok will look into it. Maybe make a shapeless recipe with meta Id.
