### ISSUE TITLE
universal fluid cell into smeltery drain

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#915]
Using a Universal Fluid Cell to insert liquids into a Tinkers Construct Smeltery Drain block (not faucet) caused a timeout for everyone on the server and some people mentioned a small rollback, not sure if it was a crash or just temporary hangup.

I had several small amounts of different metals and a large amount of rubber in the smeltery.
Wanted to take out a few buckets worth of rubber but didnt have it selected so i accidentally took out a few partially filled universal cells of different metals. When i tried to put them back by shift rclick everyone including me got timeout.
If that itself isnt enough to reproduce the behavior i may have tried to insert some liquid rubber from greg chem reactor (1 sulfur + 9 raw plastic) that i still had in my inventory as well.

**Comment by Dream-Master** [comment]
Never tried using fluid cells in Tico smeltery. I know there where some issues with partly filled cells but I guess Buckets works. The problem is I can't really do much here because Tico had no 1.7.10 support anymore. Any idea @Technus .

**Comment by Technus** [comment]
universal fluid cells are the most evil thing to ever exist in MC. Usefull but broken AF.

**Comment by Dream-Master** [comment]
@Technus You mean the cels with more then 1000mb?
are you able to fix it ?
