### ISSUE TITLE
Charcoal Dust into Alumentum (adv. crucible)

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#916]
Tried using advanced crucible attached to me system via essentia provider, everything works for other recipes but not this one. Checked everything, essentia just won't load in.

**Comment by Dream-Master** [comment]
``// --- Alumentum
mods.thaumcraft.Crucible.addRecipe("ALUMENTUM", <Thaumcraft:ItemResource>, <ore:dustCoal>, "ignis 6, perditio 3, potentia 6");
// -
mods.thaumcraft.Crucible.addRecipe("ALUMENTUM", <Thaumcraft:ItemResource>, <ore:dustCharcoal>, "ignis 6, perditio 3, potentia 6");
// -
mods.thaumcraft.Crucible.addRecipe("ALUMENTUM", <Thaumcraft:ItemResource>, <ore:dustLignite>, "ignis 6, perditio 3, potentia 6");``

Maybe the recipes are ordicted. Are the problem exists with other ordicted recipes added by modtweaker script too?

**Comment by Dream-Master** [comment]
@Fifa12343 Does it work with the Crucible ?

**Comment by Fifa12343** [comment]
Yes it does, only the advanced crucible doesn't work with Lignite Coal Dust and Charcoal Dust, http://oi63.tinypic.com/2mcymc9.jpg
