### ISSUE TITLE
BuildCraft Gates and Tables

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#917]
1) Is there any way to craft BC Gates? BC Assembly Table has no recipe so just wonder if Gates banned intentionally. Even without BC pipes they are still usefull for control BC/Iron Tanks, RC Turbines and so on. May be make few recipes for simple Gates for GT Assembler/Forming Press/etc.

2) On the other hand, BC Advanced Crafting Table has vanilla recipe but it cannot be powered because Lasers has not recipe. Missed recipes.remove?

**Comment by Dream-Master** [comment]
Ok will add some recipes for it and look into it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21580699/0a1ef144-d00c-11e6-849f-935db8708eba.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21580740/a9ec63e4-d00e-11e6-8dd9-a41c8a84ae7f.png)

I remove all recipes make in Gt machines and let only the Gates inside.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21580775/765fdaea-d010-11e6-9b56-20955277ca9d.png)
Charging Table
