### ISSUE TITLE
Nethermind Diagram is Wrong

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#918]
it says to do this
![66efb871c8cb3af0c932e8a1a5bccc41](https://cloud.githubusercontent.com/assets/23045776/21580426/2bd43c6c-cfa9-11e6-9236-28e1f73b4a7b.png)

but it actuly needs this
![90a441d86ae3eb38f70a6c843bba7cfa](https://cloud.githubusercontent.com/assets/23045776/21580425/24582598-cfa9-11e6-88c6-70acacf7c469.png)

**Comment by Dream-Master** [comment]
@Mylezz Which mod?
Mystical construct recipes i cant change with Modtweaker.

**Comment by Mylezz** [comment]
Automagy and its a multyblock

**Comment by Dream-Master** [comment]
I guess we can add a Info in the Thaumcraft book but the Graphic i cant change.

**Comment by Drobac** [comment]
That is an issue for the mod author so post it there. What is wrong with the schematic?

**Comment by Dream-Master** [comment]
Automagy are no longer developed for 1.7.10 but we can open up an issue.

**Comment by Dream-Master** [comment]
@Mylezz look at the issue and please test it.

**Comment by Mylezz** [comment]
It was a glitched block in my setup all is fine

**Comment by Dream-Master** [comment]
Ok thanks for info
