### ISSUE TITLE
Skybox in VoidDim wont change with Botania  but over-world will change

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#919]
This is what the over-world looks like
![ad724ec0eff4c575466f8fc0b082d4f7](https://cloud.githubusercontent.com/assets/23045776/21580504/91f6738c-cfb0-11e6-8112-599ddd07b4ed.png)

This is the Void dim
![ec24aed66742f497b77d2a449c25d094](https://cloud.githubusercontent.com/assets/23045776/21580506/9a73816c-cfb0-11e6-90c9-281c3f1aef8a.png)

also can u enable Time Cycle in the void dim?

**Comment by Dream-Master** [comment]
This is all i can do

````
# Configuration file

general {
    # Determines if Garden World portals can be crafted.
    B:AllowGardenWorld=true

    # Determines if Portals can be crafted.
    B:AllowPortalCrafting=false

    # If true, Applied Energistics 2 meteors will not be generated in the created dimensions.
    B:PreventAe2Meteors=true

    # Sets how bright the stars are, from 0.0 (totally black) to 1.0.
    D:StarfieldBrightness=0.5
}
````
ulityworlds.cfg

**Comment by Mylezz** [comment]
Can u not Specify what Dim uses the Skybox?
'

**Comment by Mylezz** [comment]
# Set this to false to disable rendering of baubles in the player.
    B:baubleRender.enabled=true

    # Set this to false to remove the block breaking particles from the flowers and other items in the mod.
    B:blockBreakingParticles.enabled=true

    # Set this to false to remove the block breaking particles from the Mana Shatterer, as there can be a good amount in higher levels.
    B:blockBreakingParticlesTool.enabled=true

    # Set this to false to disable the wireframe when looking a block bound to something (spreaders, flowers, etc).
    B:boundBlock.wireframe.enabled=true

    # Set this to false to disable the animation when an item is charging on top of a mana pool.
    B:chargeAnimation.enabled=true

    # Set this to false to disable the Smokey Quartz blocks. This config option is here for those using Thaumic Tinkerer
    B:darkQuartz.enabled=true

    # Set this to false to disable the particles in the elven portal.
    B:elfPortal.particles.enabled=true

    # Set to false to disable the ability for the Hand of Ender to pickpocket other players' ender chests.
    B:enderPickpocket.enabled=true

    # Set this to false to disable the Fallen Kanade flower (gives Regeneration). This config option is here for those using Blood Magic. Note: Turning this off will not remove ones already in the world, it'll simply prevent the crafting.
    B:fallenKanade.enabled=true

    # Set this to false to disable the fancy skybox in Garden of Glass.
    B:fancySkybox.enable=true

    # Set this to true to enable the fancy skybox in non Garden of Glass worlds. (Does not require Garden of Glass loaded to use, needs 'fancySkybox.enable' to be true as well)
    B:fancySkybox.normalWorlds=true

**Comment by Dream-Master** [comment]
Wat mod add this config @Mylezz

**Comment by Mylezz** [comment]
Botania
