### ISSUE TITLE
Old GTNH plates recipe - new plates

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#921]
Recipes that require updating to the new plates:

Mysterious Crystal crafting ( switch to new Mysterious crystal plates)

Reactor Stabilizer, Reactor Stabilizer Frame and Chaotic Core ( switch to new Black plutonium plates)

**Comment by Dream-Master** [comment]
fixed hopfully.

**Comment by Drobac** [comment]
Irradiant Reinforced Naquadria Plate recipe uses Quantinum Plate (7280), need to switch to Quantium plate (5876:17391)

**Comment by Dream-Master** [comment]
sure
