### ISSUE TITLE
Electric Boots of the Traveler doesn't give bonus speed

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#923]
That defeats whole purpose, doesn't it?

**Comment by Dream-Master** [comment]
@Technus 
any idea?

**Comment by Fifa12343** [comment]
Same thing goes to nano version of the boots,

**Comment by Technus** [comment]
use boost key

**Comment by NullCascade** [comment]
The boost key, locally configured Numpad9, does not enable speed boost. The boots provide fall damage immunity, and a higher jump, but do not give speed as the original boots do. The boots are charged, and lose charge as fall damage would be taken.

**Comment by Technus** [comment]
```
		if (Keys.instance.isBoostKeyDown(player) && Keys.instance.isModeSwitchKeyDown(player))
		{
			speedBoostActive = !speedBoostActive;
		}
```

**Comment by Technus** [comment]
Leaving the code snippet for referene

**Comment by Technus** [comment]
this is how "well it is implemented"

**Comment by NullCascade** [comment]
Bah. Yup. If I press down both keys it enables. Thanks!
