### ISSUE TITLE
obsidian plates NEI recipy is wrong

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#928]
![f2c0cfa2489bb5c7de97bb61eb67615c](https://cloud.githubusercontent.com/assets/23045776/21597370/d9a4222a-d0fe-11e6-8fb5-a9bb9510358a.png)
![67cdb0cc12f9792527532d2d0dc84c6a](https://cloud.githubusercontent.com/assets/23045776/21597371/daf34f98-d0fe-11e6-8a4a-21347404e042.png)

**Comment by Dream-Master** [comment]
Maybe a script conflict. Will see if I am able to fix it.

**Comment by VermillionX** [comment]
there are multiple recipes in NEI for obsidian>plate that overlap. The normal output of cutting a block into plates is usually 9, but for some reason the first recipes in NEI say they only yield 1.

**Comment by Dream-Master** [comment]
Yes very funny need to check my scripts.

**Comment by Dream-Master** [comment]
I look into the code and cant find anything. Maybe its inside the recipes cfg file idk.

**Comment by VermillionX** [comment]
The recipe applies to both obsidian tiles from Thaumcraft and vanilla obsidian. Maybe the oredictionary is derping by confusing the two?
