### ISSUE TITLE
Chisel Limestone is unobtainable

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#931]
The Limestone from Chisel, like all chisel stone types, doesn't generate and there are no recipes for it.

**Comment by Dream-Master** [comment]
I made some recipe wih lime coloar but maybe in dev. Will be in the next update.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21600336/e2a75668-d17a-11e6-8cd6-1885a0923b9e.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21600382/b101c354-d17b-11e6-83bc-e9da04a490f8.png)
