### ISSUE TITLE
AE2 Power Multiplier

### ISSUE THREAD

**Issue by Excaerious** [GTNewHorizons/NewHorizons#932]
Upon talking to other people who play the pack I noticed a big issue with the PowerMultiplier config for AE2. On Curse individuals are getting PowerMutliplier = 10.0 and on Technic people are getting PowerMultiplier = 100.0 . Which one is the correct one? I was almost certain 100.0 was the correct number but there are quite a few config issues as of late.

**Comment by bigbass1997** [comment]
Also would like to note some additional information about this issue:

The server package for version 1.2.1.0 ships with the value 10.0.

Github shows in this commit by Tec https://github.com/GTNewHorizons/NewHorizons/commit/c3b6c52dea6902cf48121877d8ab03c2199149df that he changed it from 10.0 to 100.0 between version 1.0.9.2 and 1.0.9.3.

Then on the [official changelog posted by Dream](http://gtnewhorizons.enjin.com/forum/m/36844562/viewthread/28973236-serverchangelog/post/125529342#p125529342), he notes in version 1.1.0.0 that

> Config changes:
Applied Energystics(System needs now 10x power then before)

**Comment by Dream-Master** [comment]
Maybe i forgot it will change it ro 100.

**Comment by Dream-Master** [comment]
D:UsageMultiplier=100.0 
no its set here

**Comment by bigbass1997** [comment]
Yes as I noted, here on this Github it was set to 100.0 on this commit https://github.com/GTNewHorizons/NewHorizons/commit/c3b6c52dea6902cf48121877d8ab03c2199149df however, the issue is that the curse client has it set to 10.0, and the server package download also has it set to 10.0.

**Comment by Dream-Master** [comment]
yes the serv pack are a have the value 10 idk whats went wrong.

**Comment by Namikon** [comment]
Ok why was it set to x100 at all? That's insane, even for us. One controller with 2 drives and 2 terminals eat 1,2k EU/t now

**Comment by Vicus-N** [comment]
Agree with Nami. I'm just now unlocked all to build first ME network... And with my power sources that is impossible now.

**Comment by Drobac** [comment]
100x is way too much, 10x is just enough and it lets you start using AE at EV tiers and have automation at IV tier. It is a constant power drain and is unneccesary to have it at a 100

**Comment by Mylezz** [comment]
its way to much 
After the update my power system was DEAD and Drained 3 FULL AFSU's
and it cant keep up!!!!

**Comment by bigbass1997** [comment]
Now Dream set the EU server to 20x, and people are still having problems keeping up with the increase. Change it back to 10x. "Don't fix what isn't broken."

There is lag being created by AE systems across the server switching on and off due to the unannounced/discussed change.

**Comment by Mylezz** [comment]
_"Don't fix what isn't broken."_ ~BigBass 2017

**Comment by Mylezz** [comment]
and also it Drained my Naquada Reactor in 10 mins... it a Mark II Fresh entrenched Rod D:

**Comment by Dream-Master** [comment]
@bigbass1997 @Drobac @Technus 

So what values we set now 10, 20, 15 idk.

Votes please.

**Comment by bigbass1997** [comment]
10x

**Comment by Dream-Master** [comment]
ok i changed it now.
