### ISSUE TITLE
Distillation tower in HV

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#935]
Hey, I think distillation tower should be added to HV, all the pieces of multiblock (stainless steel etc) are HV, and oil is good HV method (solar, me system, nuclear) are all EV and i believe distillation tower should be moved down to HV, or atleast add alternate more expensive recipe for HV. Most everyone using biogas as oil cant compete very well until distillation tower. I think atleast an HV recipe for oil distilling should be added to tower. Sorry if this is a bit jumbled, woke up 30mins ago.

**Comment by Dream-Master** [comment]
Ok what you exactly mean. I thought Destillation Tower is hv.

**Comment by kokochicken** [comment]
Distillation tower block needs 16 titanium etc, the tower though uses stainless steel casing (HV).
I think distillation tower should be added to HV to add more powergen options than biogas

**Comment by Dream-Master** [comment]
Biogas is now mv or hv?

**Comment by Drobac** [comment]
Can start with biogas on LV, on MV it becomes more efficient. It might be a good idea to make it available on HV, would make using oil as power gen a lot more prevalent

**Comment by Dream-Master** [comment]
ok will change that.

**Comment by Dream-Master** [comment]
Need GT 5.09.27.02 for it.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21620051/be994c18-d1f2-11e6-83ee-995bfae3e72c.png)
