### ISSUE TITLE
Coal Coke in Adv. Coke oven

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#936]
Add a recipe to make Coal Coke ( from coal ) in the Adv, Coke oven. Atm its only accepting the charcoal recipe

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21743310/dbe56710-d4ff-11e6-8cd6-3a2b9ee54f73.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21743312/e2191708-d4ff-11e6-9ae6-f0dcaeec8589.png)
