### ISSUE TITLE
Quest adjustments #193 (Tier 1 fuel:Thorium) and #258 (Infinite... Lava?)

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#937]
Change #193 From Fuel Rod (Depleted Thorium) 6557 to Fuel Rod (Thorium) 6560 so it fits all the other quests.

Change #258 from a crafting to a detection task. Can't be detected with a crafting task

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21618145/c1d46920-d1e9-11e6-8182-978f53144740.png)

![image](https://cloud.githubusercontent.com/assets/2970688/21618253/516af996-d1ea-11e6-9d12-ec06456afad3.png)
