### ISSUE TITLE
Moon dirt/rock in diggers bag

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#938]
I think it would fit if moon dirt/rock etc went into the forestry diggers bags.

**Comment by Dream-Master** [comment]
sure licke the other Planet dirt/rocks too.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21743600/c82f4d34-d505-11e6-9022-6d83aa5d1d99.png)
