### ISSUE TITLE
Infusion not working: Void Bracelets

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#939]
Checked every item, everything fine but still can't start the infusion.

**Comment by Dream-Master** [comment]
Which mod. Did is using Wand capes ? If yes it cant work because i change the Wand caps to GTNH version. Will do a new recipe when i touche this mod.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21633559/8d9c3ca2-d250-11e6-8ea3-3bfa6cc36470.png)
This saps are from Thaumcraft. I disabled it. So i need to make a new recipes first.

**Comment by Dream-Master** [comment]
fixed
