### ISSUE TITLE
TC Augment: Vis Channels

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#940]
The essentia value in thaumonomicon differens from the one during infusion, + the infusion is probably broken (didn't end for me). Was ussing wan with Augment: Charge Buffer on it.

**Comment by Dream-Master** [comment]
You mean this recipes ?
![image](https://cloud.githubusercontent.com/assets/2970688/21633523/425e932a-d250-11e6-8ee2-995dd72a334b.png)

**Comment by Fifa12343** [comment]
Yes

**Comment by Dream-Master** [comment]
This recipe i dont touche. I only change the Arcane recipe.

**Comment by DietmarKracht** [comment]
If you have not enough stabilizers it can cause the infusion to drain additional vis

**Comment by Dream-Master** [comment]
So it isnt a bug ?

**Comment by Dream-Master** [comment]
@DietmarKracht is it a bug or a feature?

**Comment by DietmarKracht** [comment]
feature ofc. he'd known that if he'd read the mod wiki

**Comment by Dream-Master** [comment]
ok
