### ISSUE TITLE
Dynamism Tablet server crashes

### ISSUE THREAD

**Issue by Saereth** [GTNewHorizons/NewHorizons#941]
looks like the Dyna tablet from Thaumic tinkerer causes some crash with blood arsenal. BA doesn't seem to be properly checking fake player and is casting the tablet to EntityPlayer, not sure if this was ever updated or not. Special mobs, Infernal mob triggers and thaumcraft mobs can all trigger a crash from this.

Here is a copy of the server logfile
https://hastebin.com/ipubaxewug.pl

Basically when an ability would trigger against the tablet like fiery from infernal mobs, or in this case thorns from thaumcraft the code in blood arsenal will crash the server.

steps to reproduce: Dynamism tablet+tinkers cleaver attacking Mobs with damage reflect or on hit effects

**Comment by Namikon** [comment]
BloodArsenal was just forked today. So we'll continue the 1.7.10 branch for this mod I assume. Weird is, this should've been fixed already since 2015.. But I'll check

**Comment by Saereth** [comment]
Yeah I tried to look into the code to do a PR but all I could find on his github was the 1.10 code :/

**Comment by Namikon** [comment]
Hopefully this https://github.com/GTNewHorizons/BloodArsenal/commit/20958ba74ba5971c84219c27751dc2675c249260 should help with all issues related to GameCrashes of this kind

**Comment by flashsugar** [comment]
this issue still has nmot been fixed

**Comment by Saereth** [comment]
this no longer crashes for blood arsenal but it does crash for forge essentials. 
Relevant logfile: https://www.dropbox.com/s/wcqrw27slj1c7bn/crash-2017-06-06_20.51.04-server.txt?dl=0

This is version 1.4.1.1 of the GTNH pack.

This wouldnt be an issue but there seems to be no other way to automate wither skull collection. Currently diamond spikes, robots using tinker cleavers and liquid death dont drop wither skeleton skulls. The Dynanism tablet+cleaver seems to be the other option but it crashes.

**Comment by Namikon** [comment]
That's a problem in ForgeWorldEdit, not BloodArsenal

**Comment by Saereth** [comment]
it was a similar issue with blood arsenal due to the dynamism tablet's implementation of fake player. I referenced the original issue with blood arsenal because it all stems from the same issue. I don't expect a fix for forge essentials as its no longer supported, documenting regardless.
