### ISSUE TITLE
TC: Rosa Mysterias Knowledge Fragments cause dc

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#942]
After using one of the fragments gathered from rosa mysteria i get instantly dc'ed, 

![rosa mysteria](https://cloud.githubusercontent.com/assets/24848942/21649102/c9eaaf86-d2a0-11e6-8f59-3bde3982e3e9.png)

+ they cant be crafted into normal fragments tho there's a recipe for it in thaumonomicon.

![for issue](https://cloud.githubusercontent.com/assets/24848942/21649335/9acf06f6-d2a1-11e6-97c8-849a13d770ab.png)

**Comment by Dream-Master** [comment]
dc=disconect???

Without any log i cant say much.

**Comment by Fifa12343** [comment]
yep disconnect

**Comment by Dream-Master** [comment]
fml log in you folder logs.

You need to report it to Thaumic Bases repro too.

**Comment by Dream-Master** [comment]
https://github.com/Modbder/ThaumicBases

**Comment by Dream-Master** [comment]
can see here much not seen you disconected.
Did your client crash?

**Comment by Fifa12343** [comment]
No, I just get disconnected from the server...

**Comment by Fifa12343** [comment]
Happens to others too.
![](https://i.gyazo.com/147fbfca834f90436deba6a091b738e4.gif)

**Comment by Dream-Master** [comment]
Did you try in sp ?

**Comment by Fifa12343** [comment]
On singleplayer everything works great.

**Comment by Dream-Master** [comment]
Did you open up an issue on Thaumic base side ?

**Comment by Fifa12343** [comment]
Did it right now.

**Comment by Dream-Master** [comment]
@HelfirePvP Did you have any idea about this issue? I know its not your mod.

**Comment by Ugachaga** [comment]
> Possibly fixed server d/c on eating last rosa fragment in a stack

[Here](https://github.com/KryptonCaptain/ThaumicBases/releases).

**Comment by Dream-Master** [comment]
@Ugachaga Thanks will compile the lastest fix and we need to test it in the next release.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/ThaumicBases
