### ISSUE TITLE
Powergen suggestions

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#943]
Hey, looking to come up with some new ideas for powergen fot GT5u (our custom version) not sure where to put this so i'll put it here. I think we need some more powergen options for mv-hv (maybe move biogas for a really early method and hv-ev with multiblock turbine) I think some cool new powergen options would be hydroelectric dam multiblock or something similar, like a multiblock watermill. I believe this would be pretty cool (would need turbine maintenence etc) and would add some more depth to powergen.

**Comment by Dream-Master** [comment]
I moving Distillation Tower to Hv. Now oil becomes a more useful role in hv. For Mv using Biogas.

**Comment by kokochicken** [comment]
Alright,

**Comment by Mylezz** [comment]
I like the dam idea

**Comment by Dream-Master** [comment]
Ask Tec for implementing such thing. Yea the idea is nice.

**Comment by Drobac** [comment]
We do have compact wind/water mills for water power, although the recipes do start with titanium. Maybe could switch the lower tier recipes to need aluminum/stainless for their tier

**Comment by Dream-Master** [comment]
The ic2 i will then let Stainless but Advanced stay at titan.
