### ISSUE TITLE
Botany's Stained Striped Vertical Ceramic Bricks recipe (what a mouthful) craft wrong item

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#944]
These recipes don't actually show up in NEI, but all the botany stained ceramic blocks, bricks and tiles use the same recipes.
The recipe is the shapeless crafting of the striped bricks, and should yield the vertical version. Instead it gives the horizontally-angled pattern, made through a different recipe. Though i'm not sure how you could fix this, unless you can make an alternative recipe for any and all striped brick color combinations (12880 combinations).

**Comment by Dream-Master** [comment]
Pic please. 
With minetweaker I can't change it I guess. This can only changed code wise. Not sure if this can be probably done inside binnies patcher mod from Chocohead. Maybe you have to ask him to add/change it.

**Comment by VermillionX** [comment]
Angled bricks, when shapeless crafted give their vertically-oriented version. Striped bricks, when shapeless crafted give the angle bricks instead of their vertically-oriented version.

![2017-01-05_20 15 50](https://cloud.githubusercontent.com/assets/10645298/21672003/3028e55e-d384-11e6-8499-6a8ef09b0003.png)
![2017-01-05_20 16 00](https://cloud.githubusercontent.com/assets/10645298/21672009/365e1f48-d384-11e6-8ecc-9df7bab1a686.png)
![2017-01-05_20 17 53](https://cloud.githubusercontent.com/assets/10645298/21672014/410aa038-d384-11e6-8c69-933de0e54bcc.png)

**Comment by Technus** [comment]
botany fault
