### ISSUE TITLE
Add GraveStone (dungon mod)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#945]
This is an awesome mod that adds a huge dungon that spawns randomly in the world.

It spawns a hard to kill wither at the end and is full of early -mid game items,

https://mods.curse.com/mc-mods/minecraft/gravestone_mod#t1:description

**Comment by Mylezz** [comment]
True but this would be nice to have

**Comment by Dream-Master** [comment]
This mod a ton of new stuff. We have gravestones and we have dungeons. 
If the other admins thinking different will open up again.
