### ISSUE TITLE
Add Chat Bubbles,

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#947]
Nothing more to say outher than it its awesome and it would be amazing to see on the server

https://mods.curse.com/mc-mods/minecraft/235520-chat-bubbles

**Comment by Dream-Master** [comment]
I cant say about the mod. 
What you mean?
@Namikon , @bigbass1997 , @Drobac , @Technus

**Comment by Namikon** [comment]
That's a client side mod and requires liteloader
