### ISSUE TITLE
Suggestion: Armourer's Workshop

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#948]
MCF: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins

Curse: https://minecraft.curseforge.com/projects/armourers-workshop

![2015-09-24_01 04 13](https://cloud.githubusercontent.com/assets/10645298/21671726/40d2a0c2-d382-11e6-9acb-b8ac6ebddda0.png)

AW is an amazing aesthetics mod, that adds 8 or so blocks and about as many items.
What you can do with them is place and paint armor blocks on a large-scale hologram and then compress it into a skin that can be attached to an item, armor, block or tool that will replace its appearance with a 3D model of your own creation.
Additionally, AW adds the Mannequin; A basic steve-skinned posable model that can wear armor/tool skins and is fully posable. By applying a player-named nametag to the mannequin it'll also take on the appearance of that player. Allowing players to fill their houses, towns and libraries with immobile occupants.

No longer do you need the unicorn vomit that is Tinker's Construct pickaxes; Never again must you look at those retarded coke bottles that make up a jetpack; And never again will you be alone in your one-man town.

Unfortunately, it's not currently ready for suvival usage as-is. For survival usage, the Armourer would need to be disabled to prevent duping of equipment cubes. When the Mini-Armourer is completed (won't be for a long time, probably) it will be survival-usable without the duping that comes from loading a skin in the armourer.
With the Armourer out, players would need to make their skins in creative mode in Singleplayer and copy them onto the server via the Equipment library. Though the upload process may strain the server; in that case i'd suggest disabling loading skins from player's computers (there's a config option for that), and giving everyone a pre-loaded set of skins to choose from; or alternatively disabling all the loading/saving machines and make skins purchasable with either money, job points or coins.
Could also be possible to hold skin-building events, where the winner gets their skin(s) added to the server list. Just an idea...

With the exception of AW-built blocks (which are just decorative blocks), the skins are aesthetic items and do not affect gameplay in any way.
The equipment cubes used to make skins also work as flat-colored, paintable building blocks. Available as Solid, Transparent, Solid Glowing and Transparent Glowing; and can be painted a different color on each side. Much like the OpenBlocks canvas blocks, minus the textures and paint patterns.

(btw, that's my old avatar skin on the mannequinnes in the image at the top. Those equipments they've got are also all mine.)

**Comment by Mylezz** [comment]
Love it!!!

**Comment by Mylezz** [comment]
Please add it id love to have this

**Comment by Mylezz** [comment]
+1

**Comment by Dream-Master** [comment]
The pack is huge enough.
