### ISSUE TITLE
[Suggestion] Add Wawla-Mod

### ISSUE THREAD

**Issue by cyres** [GTNewHorizons/NewHorizons#951]
How about adding the [Wawla](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at)-Mod? It [adds some useful informations](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/images) to the UI.

Cheers
Cyres

**Comment by Dream-Master** [comment]
I think we have enough infos in the screen. I can see what i looking for like you can see in thie pic.
![image](https://cloud.githubusercontent.com/assets/2970688/21708013/d14f4630-d3d4-11e6-9c2c-0ec309846b77.png)

**Comment by Dream-Master** [comment]
@bigbass1997 , @Namikon, @Technus , @Drobac

**Comment by Namikon** [comment]
WAWLA is a spinoff/alternative to WAILA, that is also continued to be developed for 1.8+, where WAILA is not. It's either WAILA or WAWLA. So if it is added, WAILA must be removed.

**Comment by cyres** [comment]
It can be [used alongside with WAILA](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at?comment=51):

> It started out for an addon to Waila, and it will always be that. Although I have been moving it to a much more neutral direction. It can work without Waila, and soon it will even work with other mods like The One Probe.

**Comment by Dream-Master** [comment]
So vote for it or against it.

**Comment by Ugachaga** [comment]
WAWLA uses WAILA window and add some more infos (block hardness, blast resis, animal stats etc.)
![wawla1](https://cloud.githubusercontent.com/assets/19178671/21934348/a8086dee-d9db-11e6-982f-a58e3596ca97.png)
![wawla2](https://cloud.githubusercontent.com/assets/19178671/21934352/a9c1acd6-d9db-11e6-8571-0658797fc64e.png)

**Comment by Dream-Master** [comment]
try it now
