### ISSUE TITLE
Storage Drawers balance

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#955]
Storage Drawers seems heavily undernerfed.

1. Compares to Jabba they have too easy basic drawers recipes:
- no need any instruments, like saw for slabs, for craft drawers;
- no need any machines for craft upgrades;
- cheap upgrades overall, so for 4*5 obsidian plates (~2 obsidian blocks in LV Cutting Machine) you get drawer for 800 stacks. It just solved storage problems here and now, makes Jabba obsolete and overpriced;
- void upgrade just for 2 obsidian;
- etc. 

2. Drawer Controller. For 1 Diamond Plate (LV Cutting Machine again) your drawers, in a radius of 12 blocks, are transformed into a autosorting cluster. It can be even used as sort of pipe when Trim is basic pipe and Drawer/Controller with hopper is node.

**Comment by bigbass1997** [comment]
Remember that Drawers have half the base storage space as a barrel, thus their recipe requires less to make.

As for the drawer controller, it has been used by multiple people as a very primitive storage/sorting system, especially when combined with ProjectRed. If you are going to "nerf" this, then at least keep it LV tier.

**Comment by Ugachaga** [comment]
> Remember that Drawers have half the base storage space as a barrel, thus their recipe requires less to make.

Thats true, but I'm talking about the complexity of the recipes. It may cost just 1 wood plank and 2 wooden screws, so less wood than now but needs of instruments. Also drawers much easier upgrades, there is no need to craft upgrade for each additional stack.

> As for the drawer controller, it has been used by multiple people as a very primitive storage/sorting system, especially when combined with ProjectRed. If you are going to "nerf" this, then at least keep it LV tier.

I'd say these multiple people abuse balance. It is not primitive storage/sorting system. It is great, easily expandable and extremaly cheap system. It can be uses even with ME and still be great.

**Comment by Dream-Master** [comment]
And another mod we need to change via java. Templates cant be removed via minetweaker or gt code. So i guess i have to change them inside the mod.

**Comment by Ugachaga** [comment]
Jabbas Structural Upgrades also crafted by hand, but Storages Upgrades have Assembler recipe. So why not use Jabba as balance base and do something like this:

|Tier|  SD | SD*5 | Jabba|    SD upgrade cost   |
|----|-----|------|------|----------------------|
|  1 |  32 |      |   64 |                      |
|  2 |  64 |  320 |  128 |  1/2 J StorageUpgrade |
|  3 |  96 |  640 |  256 |    J StorageUpgrade    |
|  4 | 160 |  800 |  512 | 2x J StorageUpgrade    |
|  5 | 256 | 1280 | 1024 |    J StorageUpgradex3  |
|  6 | 416 | 2080 | 2048 | 2x J StorageUpgradex3  |

SD - capacity for Drawer with Tier upgrade, 
SD*5 - maximum capacity for Drawer with 5 Tier upgrades, 
Jabba - fully upgraded Tier Jabba. 
For each additional 64 stacks Jabba requered Storage Upgrade, so 
SD upgrade cost - approximate price for Drawer Tier Storage Upgrade based on Jabba Storage Upgrade.

**Comment by Dream-Master** [comment]
@Ugachaga are you on GTNH Discord ?

**Comment by Ugachaga** [comment]
@Dream-Master same nick

**Comment by VermillionX** [comment]
The upgrade templates for storage drawers must be made in the assembler. The manual crafting recipes don't work.

**Comment by Dream-Master** [comment]
They are now and the shaped recipe is removed.

**Comment by Dream-Master** [comment]
Need Storage Drawers 1.10.8a for it.
