### ISSUE TITLE
[Suggestion] Add OpenFM mod

### ISSUE THREAD

**Issue by Vicus-N** [GTNewHorizons/NewHorizons#957]
Subj. https://minecraft.curseforge.com/projects/openfm
Would be nice.

**Comment by Dream-Master** [comment]
I remember we had another audio mod on the pack long time ago.
WHat the other think @bigbass1997 , @Namikon , @Technus , @Drobac

**Comment by Drobac** [comment]
we had this - https://minecraft.curseforge.com/projects/dragons-radio-mod . If i remember right it was throwing console errors or some other problem similar to that

**Comment by Vicus-N** [comment]
On project page author tells: "Highly modified version of Dragon's Radio Mod"

**Comment by Namikon** [comment]
A no from me. We had like 3 Radio mods by now, and all 3 had either serious issues, or were never used except by the one person who suggested it.

**Comment by Dream-Master** [comment]
Ok i close this now If you like a Radio mod @Vicus-N install some in you client.
