### ISSUE TITLE
doing /jobs top miner crashes you

### ISSUE THREAD

**Issue by rijodan** [GTNewHorizons/NewHorizons#958]
mylez also did the same right after me, no technic crash file that i found tho

**Comment by Dream-Master** [comment]
@Namikon any idea?

**Comment by rijodan** [comment]
seems to happen if you do anything regaeding any tops, get error code "Internal Exception: io.netty.handler.codec.DecoderException: java.IOexception: the received string length is longer than maximum allowed (21>16)

**Comment by Namikon** [comment]
Will try to disable that command

**Comment by Dream-Master** [comment]
@Namikon is this fixed ?

**Comment by Namikon** [comment]
Can't block the command because it would block the entire /jobs command.
But the plugin is still being developed, and I'll update it today, so then the issue may have been solved
