### ISSUE TITLE
ic2 mfsu bug

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#961]
it said wrench is incorrect tool to pickup mfsu, i used the tool it says is the right tool (pickaxe) and it gives me basic machine casing?????

**Comment by Dream-Master** [comment]
Never using pickaxe on machines. Yes maybe the tool tip wrong but would you remove a bt machine with a pickaxe ???

**Comment by kokochicken** [comment]
tried with wrench... no clue why i shouldnt be able to do it like GT when near all ic2 stuff morphed into GT...

**Comment by VermillionX** [comment]
MFSU is an IC2 machine. Removing it should require a shift-right click with the wrench to remove it, if it still functions like IC2 normally does.
