### ISSUE TITLE
Thaumcraft Research Bug

### ISSUE THREAD

**Issue by robpo4** [GTNewHorizons/NewHorizons#962]
Bug that occured on the Prospercraft server while conducting research in thaumcraft, specifically with interactions within the Research Table.
Whenever placing/removing thaumcraft research notes, placing aspects within the minigame, trying to create new aspects it immediately kicks you from the server every single time. And I mean kick, it does not crash the client so there is no crash report.

**Comment by Dream-Master** [comment]
Without any log I can't say much. Ask Goshen @Prospercraft to post a server log here. You need to talk with him first to know the time you try it. Thanks

**Comment by Dream-Master** [comment]
@robpo4 send me a log and we reopen the issue.

**Comment by ProsperCraft** [comment]
Blackace found the problem, it was similar to a problem experienced in the past he could explain it to you.

Something with how the thaumcraft mobs were getting killed by spikes, which causes thaumcraft to stop working.  He had the same problem with Witchery and patched it with a plugin he wrote.

**Comment by Dream-Master** [comment]
@Ghoshen if this addon/fix is good for the pack maybe he is willing to share it.

**Comment by Methes** [comment]
As said before, the server kicks happen when doing any research after Extra Utilities spikes kill mobs.
Server log: http://pastebin.com/6QHcGuuT
Possibly related to #1077

Restarting the server allows research to be done again, will try turning on mob farm later.
