### ISSUE TITLE
Railcraft lantern recipes are messed up in various ways.

### ISSUE THREAD

**Issue by Wavepon** [GTNewHorizons/NewHorizons#964]
https://gyazo.com/9dbe93ae70c983df7534fb95bd2526c1
https://gyazo.com/c556f44d39e7a598dfabc97f44b2d64e

Old, ungregged recipes still work for sandstone and stone.

https://gyazo.com/96f0f14e8dda0ff364577df2b2209152

The Railcraft exclusive stone lanterns' recipes are all mismatched.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/831

**Comment by Dream-Master** [comment]
and fixed allready in dev.
Thanks for info.
