### ISSUE TITLE
Small Gear Extrusion Mold

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/NewHorizons#967]
I know this is more of a GT thing than anything, but with the way GTNH is made, it's probably relatively easy to add.

Realistically seen there is no reason why the extruder can't produce small gears. It can produce the big ones and it can produce things like bolts (all three would have a similar way of being extruded).

**Comment by Drobac** [comment]
Works with a fluid extractor/solidifier if you really need it

**Comment by Technus** [comment]
iirc was suggested once already

**Comment by Technus** [comment]
small gears are too precise to be extruded

**Comment by mtesseracttech** [comment]
It's a bit of a strange reason, if extrusion is too imprecise, casting (fluid solidifier) surely is too imprecise too.

**Comment by Dream-Master** [comment]
added
