### ISSUE TITLE
Open Blocks Grave Loose's Item When u Die To Blood-magic Self Sacrifice 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#968]
I Died to server lag, and when i claimed my grave my Dislocation Charm Was not in it and it was Soul-bound.
I had San help me and i have Had this issue Before with outher item's.
I think its a Glitch With the Death mechanic of the Mod.

**Comment by Drobac** [comment]
If it was soulbound it never appears in your grave, always appears on your person. I never had issues with with, every time the item was in my inventory on revive as it's supposed to be
