### ISSUE TITLE
Missing SAG Mill recipes for GT stone ores

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#970]
The EnderIO SAG Mill can grind any GT ore, including Netherrack ores, Red Granite Ores, Black Granite Ores and even GalaxySpace ores. Yet for some reason, there are no recipes for ores in Marble or Basalt.

**Comment by Dream-Master** [comment]
Because this ore are added later by GT. I need to add it in the Ender io config

**Comment by Dream-Master** [comment]
Example for Lithium:

``  <recipe name="CrushoreLithium" energyCost="3600">
    <input>
      <itemStack oreDictionary="oreLithium" />
    </input>
    <output>
      <itemStack oreDictionary="crushedLithium" number="1" />
      <itemStack oreDictionary="crushedLithium" chance="0.5" />
      <itemStack oreDictionary="dustStone" chance="0.5" />
    </output>
  </recipe>``

Marbel and Granite are ordicted too but not detected idk why.

**Comment by Technus** [comment]
probably the same problem as was with achievements or netherrackNetherStarOre

**Comment by Dream-Master** [comment]
@Technus Any idea how to fix. Ask muramasa already and wait for an answer.

**Comment by Dream-Master** [comment]
@muramasa any idea about this issue ?

**Comment by mramasa** [comment]
I am not a member of this GIT repo, plz validate your email receipt.

**Comment by Dream-Master** [comment]
renamed i allready.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21902105/f09aa158-d8fa-11e6-8965-49c432c7f019.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21902108/f41f7470-d8fa-11e6-80bf-5146cceaadb2.png)
