### ISSUE TITLE
OpenBlocks Rope ladder recipe gives only 1 ladder

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/NewHorizons#971]
The recipe for the OpenBlocks Rope Ladder costs 16 long wood stick and 16 string and gives only a single ladder. In order to actually use the ladder properly you need at least 16 of them. Recipe should give at least 4.

**Comment by Dream-Master** [comment]
The ropeladder open up automaticly from the block you put it down too the floor.

**Comment by bigbass1997** [comment]
@Dream-Master This issue has been opened before. I can test it again if you want but https://github.com/GTNewHorizons/NewHorizons/issues/823 clearly shows that it doesn't open up automatically using just a single ladder but requires a ladder in inventory for each meter in height.

**Comment by VermillionX** [comment]
What bass said. It consumes 1 ladder from your inventory for every block it lowers.

**Comment by bigbass1997** [comment]
Just tested it. That is correct. I placed a ladder, with 4 total in my inventory, 5 blocks above the ground, and the placed ladder went down only 4 blocks, consuming what was in my inventory. It did not go all the way down to the ground.

**Comment by VermillionX** [comment]
I believe it's because the config has infinite mode set to false.
ladder {
    # If true, ladders will behave in old way: single item will place ladder all the way down, but it will not drop when broken
    B:infiniteMode=false
}
Currently, the ladders feed from the player's inventory and drop when broken.

**Comment by Dream-Master** [comment]
Ok will aktivate it then.

**Comment by Dream-Master** [comment]
ok will change the recipe or the output
