### ISSUE TITLE
After I launch, the Minecraft process loads but Minecraft itself won't

### ISSUE THREAD

**Issue by Saiburr** [GTNewHorizons/NewHorizons#973]
I think it's Thaumcraft energistics causing it. http://pastebin.com/H4g0cD7B

**Comment by Dream-Master** [comment]
try to redownload the pack/mod again.

**Comment by Dream-Master** [comment]
@Saiburr any new can this be closed ?

**Comment by Dream-Master** [comment]
Pastbin log is deleted.
