### ISSUE TITLE
Little poor clerics

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/NewHorizons#974]
Please, remove quest "secrets" from adept thaumaturge. Cultists almost impossible to find in server. And, according to quest, you have to find 2! obeliscs with cultists!(5kills requared)

**Comment by Dream-Master** [comment]
Will loonk into it. On which server do you playing? EU?

**Comment by Drobac** [comment]
Lower the need to kill the cultists to 1 or 2
