### ISSUE TITLE
Genetics DNA/Fluorescent Dye?

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#975]
Anyone know how to get "DNA Dye" (6315:1) and "Fluorescent Dye" (6315:2) from Genetics mod other than quest rewards? NEI doesnt show anything. Just starting but afaik its needed for using the machines as well so a somehow renewable supply would be needed.

**Comment by ghoulsblade** [comment]
hmm, found some with github search, i wonder why nei doesnt show it, i'll try and check if they're actually craftable or broken. If it works maybe add a recipe text to bee quest to work around nei failure ?

scripts/Genetics.zs
```
// --- DNA Dey
Mixer.addRecipe(<Genetics:misc:1>, null, [<minecraft:glowstone_dust>, <minecraft:redstone>, <minecraft:dye:4>, <minecraft:dye:5>], <liquid:molten.blaze> * 144, 100, 30);
// --- Fluorescent Dey
Mixer.addRecipe(<Genetics:misc:2>, null, [<minecraft:glowstone_dust>, <minecraft:redstone>, <minecraft:dye:14>, <minecraft:dye:11>], <liquid:molten.blaze> * 144, 100, 30);
```
which should translate to mixer recipes if i read it right:
DNA Dye = glowstone + redstone + lapis?(351:4) + purple dye (351:5)     + 144mb "molten blaze" 
Fluorescent Dye = glowstone + redstone + orange dye (351:14) + dandelion yellow (351:11) + 144mb "molten blaze" 
The molten blaze can supposedly be made with http://binnie.mods.wiki/wiki/Incubator i think, will try.

NOTE: In original genetics recipe DNA Dye was purple(351:5)+magenta(351:13)+pink(351:9), so if lapis fails maybe one of those.

**Comment by Dream-Master** [comment]
Maybe some recipe are get overriden by another.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21862593/2ed1c076-d83a-11e6-8682-51003f97694f.png)

![image](https://cloud.githubusercontent.com/assets/2970688/21862603/39589272-d83a-11e6-9b31-3c7c24ed35bf.png)
@ghoulsblade
I see the recipes in sp.

**Comment by ghoulsblade** [comment]
odd, i have the standard install in technic launcher, no optifine or any other tweaks, only thing i did was put a texture pack in the ressource pack folders. 1.2.1.0, same as on server. 
I do see recipes for other items from genetics in nei, and the recipe using dandelion yellow does NOT show up if i rclick dandelion yellow and scroll through mixer recipes.
So either its a change in the new version you're using or its something on the server. 2 others on the server also dont see it but a 3rd one does, also technic launcher. Maybe new installs work but existing ones updated get messed up or dont get nei cache reset ?
My installation was updated several times from an older version.
Any way to manually clear nei cache ?
I'll soon have the materials ready to try crafting it, so prolly later today or tomorrow evening.

**Comment by Dream-Master** [comment]
The script and config folder needs to be removed manually every update. We had recipe and config issues in the past.

**Comment by ghoulsblade** [comment]
OK, tried it with HV mixer, the DNA dye recipe worked (at least when i did the exact same positions as your screenshot), but the Fluorescent  dye didnt work. tried with vanilla dyes as well as gregtech dye items =\

Script + Config folder: do you mean on technic launcher client or on server ?

**Comment by Dream-Master** [comment]
On the client first. On the server should be the 1.2.1.0 fueled hopefully.

**Comment by ghoulsblade** [comment]
![2017-01-11_21 17 00-fail](https://cloud.githubusercontent.com/assets/378125/21864894/089b409e-d844-11e6-938f-a2718f10a8eb.png)
Well the machine should do it once i place the items in even if my client would be messed up.
Admin lame checked and found the exact lines as above in scripts/Genetics.zs on the server without changing anything.
Machine has plenty of power, even a hv battery in, tried wooden hammer to pause and unpause it, still nothing.

**Comment by ghoulsblade** [comment]
Hmmm, i was trying if higher amounts than 1 per item would work, and i got illumar instead even with the redstone in! Seems its trying to run those recipes instead while ingoring other things in the input slots.
I rearranged a bit and suddenly it made one fluorescent dye when i replaced yellow vanilla dye by yellow greg dye item.

**Comment by Dream-Master** [comment]
Mh maybe it interfear wih some other recipes.

**Comment by ghoulsblade** [comment]
yes, Yellow Illumar (7425:23) and Orange Illumar (7425:20) use 2 glowstone + 2 yellow/orange dye and seem to ignore other things in the input slots. so it prolly triest to run them.
I havent found a reliable way to get the fluorescent but i did get it twice while trying for half an hour....

**Comment by Dream-Master** [comment]
So change it to gt dye will help maybe?

**Comment by ghoulsblade** [comment]
also Blue Illumar (7425:30) and Purple Illumar (7425:29) for DNA Dye.   
Suggestion, needs testing: make the illumar recipes require glass dust in addition
Suggestion, needs testing: make the DNA Dye and Fluorescent Dye require small glowstone dust instead of full dust.

**Comment by ghoulsblade** [comment]
aha! i think i found a reliable workaround for anyone wanting to play with gendetics until this is fixed properly:
put the recipe in with vanilla dyes, 1 item each, not a higher amount.  then take 1 corresponding greg dye and click/swap it with the corresponding vanilla dye several times. then the machine will start.

**Comment by ghoulsblade** [comment]
if it doesnt work try the other color, only worked with the blue on dna dye for me just now

**Comment by Dream-Master** [comment]
will change to color deys not used in other recipes.
