### ISSUE TITLE
Pizza Gloves Dont work with lava drums

### ISSUE THREAD

**Issue by rijodan** [GTNewHorizons/NewHorizons#976]
Tried picking up a drum full of lava with oizza gloves in correct slots, in correct order, in an inv slot that i was selected and the fire resistance buff never kicked in from the gloves

**Comment by Dream-Master** [comment]
Yes test it and you get burned when have a lava drum on you.

**Comment by Dream-Master** [comment]
@Namikon any idea?

**Comment by Namikon** [comment]
That should get rid of these issues

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21899943/6288954e-d8f2-11e6-92da-d0ef059741f1.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21899952/662b2810-d8f2-11e6-97b5-cd8a9527ba04.png)
works
