### ISSUE TITLE
Emiter IV wont craft

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#978]
I have all the Right Item's for the crafting of it and it wont craft it show's as craftable for a secound then it removes its self

![73f7008a3ed03756cec5704e2593532c](https://cloud.githubusercontent.com/assets/23045776/21867825/cf7ef5e2-d804-11e6-9530-599f85bd0517.gif)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21867897/8d4745fc-d850-11e6-85a8-f52fe415f5f1.png)
I guess you not delete all update your script and config folder. Your recipe is deprecated and missmatch with the server recipe.

**Comment by Mylezz** [comment]
ok il restart and redownload the pack

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21867939/bf09eb76-d850-11e6-8c7e-8f3baff15e6c.png)

**Comment by Mylezz** [comment]
Delete the Script and cfg?

**Comment by Dream-Master** [comment]
yes the two folders and redownload the pack. not forget to save your Journeymaps folder and stuff you needed.

**Comment by Dream-Master** [comment]
Maybe gt versions not match. Hope in the new update this will be fixed.

**Comment by Drobac** [comment]
Tec updated the recipe but wasn't pushed to the server

**Comment by Dream-Master** [comment]
?

**Comment by Dream-Master** [comment]
I know Gt version differ between server and client but was the recipe change in this change included @technus

**Comment by Technus** [comment]
Might be a thing. (IV shouldnt use Osmium)

**Comment by Technus** [comment]
Recipe in code uses iridium.

**Comment by Dream-Master** [comment]
sure so fixed with the next update 1.3.0.0 good.
