### ISSUE TITLE
Quest #234: A "greater" wand glitch

### ISSUE THREAD

**Issue by rijodan** [GTNewHorizons/NewHorizons#979]
the quest is a crafting quest for the great wood rod, made two seperate rods in the arcane work bench and neither triggered the quest

**Comment by Dream-Master** [comment]
I am not on a computer right now but I guess this Wand have to be charged with Vis first.

**Comment by rijodan** [comment]
the quest isnt for the wand, just the rod for the wand

**Comment by Dream-Master** [comment]
will look inside it.

**Comment by rijodan** [comment]
could it be the arcane crafting table doesnt count as "crafting" in the current code?

**Comment by Dream-Master** [comment]
Yes thats maybe the reason. Will make it retrieval.
