### ISSUE TITLE
Blacklist lava-tanks/buckets/whatever from backpacks

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/NewHorizons#98]

**Comment by Namikon** [comment]
Easy to fix, see backpack.cfg / S:disallowItems for Details.
Not a code issue, I'll leave it to @Dream-Master :grin:

**Comment by Dream-Master** [comment]
Forestry Backpacks not have a configure file. Have to check which Items can be placed in the Backpack and make this packs (liquid backpack)uncraftable. Or I disable all Forestry backpacks?

**Comment by Namikon** [comment]
Disabling only the liquid backpack seems a good way to accomplish this. Forestry packs are quite nice for their special purpose to carry only ores, only cobble/sand/.. and such and it would be sad to have them removed. Haven't seen the recipes yet, but they should be craftable once you hit steam/32 eu range. (Not speaking of "easy" craftable, but .. craftable.)

**Comment by Drobac** [comment]
Forestry backpacks do have a config file, but only additional whitelisting, no blacklisting

**Comment by arnabbiswasalsodeep** [comment]
Should we black list it though? If the player can make a backpack then he already is able to make gloves.

**Comment by Namikon** [comment]
Yay for not closed issues.. I'm ok with the current settings. You can do gloves, but you don't have to. And you can still go the dolly/chest/bc-tank way, so trying to "fix" backpacks and lava tanks is just over complicating things imho. Martin; Please consider closing this

**Comment by Dream-Master** [comment]
In Backpack i can dissallow items and  i will do it. Forestry have a Liquid Backpack and maybe now a reason for craft it.
