### ISSUE TITLE
Skullfire Sword isn't working.

### ISSUE THREAD

**Issue by Fifa12343** [GTNewHorizons/NewHorizons#980]
It's supposed to give 1 wither skull every skeleton kill but i dont get any of them and skele drops me normal skulls, its pretty bad despite its low dmg and 200 diamonds + 21 nether star cost. I'd have to kill withers then anyway.

**Comment by Dream-Master** [comment]
Special mobs variants of the skeletons maybe not dropping the skull maybe. I could add it via Custom drops mod but not sure about the balancing.

**Comment by Namikon** [comment]
No, please don't...
The linked commit should fix that issue, but needs to be verified if functional before release. That was a (very) quick addition today

**Comment by Dream-Master** [comment]
Crash
https://gist.github.com/Dream-Master/160834176e6603e10fc6c8bf49a62c8a

**Comment by Namikon** [comment]
Try again

**Comment by Dream-Master** [comment]
Not working for me. Try to kill 64 Skeletons no Wither Head.

**Comment by Dream-Master** [comment]
Ok try it now with new config

**Comment by Namikon** [comment]
It is **not** solved; Why is this closed?
The issue is that iguana tinkers tweaks is removed all heads upon drop, no matter what you do.
I have a possible solution for this, needs to be discussed. However: This affects a general combination between Iguana and Avaritia; Not only in our Modpack

**Comment by Dream-Master** [comment]
Auto close after push to master @Namikon
Will test it later.
