### ISSUE TITLE
Add Air Texture 

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#981]
Please add an air Animation so when we look in recipes we see it

Here is an idea
![air](https://cloud.githubusercontent.com/assets/23045776/21912130/e7d58e92-d8d8-11e6-9826-c02b9725c724.png)

**Comment by Cinobi** [comment]
Good idea, love it

**Comment by Mylezz** [comment]
thanks

**Comment by Dream-Master** [comment]
need GT 5.09.27.08 for it
