### ISSUE TITLE
Add Travelers Belt Crafting and Traveler's Gloves crafting

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#982]
Please add crafting for these thay are Really Useful :DD
 Traveler's Belt that can be used to change hotbars back and forth. so i can have my normal tool's then have like Wrench and crowbar screwdriver etc

 Traveler's Gloves which can have redstone added onto it through the Tool Forge to increase mining speed.
mine faster for Nubie's :D
https://ftbwiki.org/Armor_Tab

**Comment by Dream-Master** [comment]
There was some reason why I disabled those items long ago. Will look into it.

**Comment by Mylezz** [comment]
Ok it would be really usefull to have

Thanks

**Comment by Technus** [comment]
Swapping hotbars can occasionally dupe.

**Comment by Dream-Master** [comment]
so better not add it ?

**Comment by Mylezz** [comment]
it wont cause that it was fixed in a newer verison
