### ISSUE TITLE
AvaritiaAddon (infinity chest)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#984]
This adds an infinity chest like a DSU for late late game
https://minecraft.curseforge.com/projects/avaritiaddons

**Comment by Dream-Master** [comment]
Gregtech Quantum chest ?

**Comment by Drobac** [comment]
+1 from me for this addon, has some interesting features although the recipes need to be a lot more expensive.  The chest works differently from the GT quantum chest as the GT one can hold only 1 item this can hold 2,147,483,647 ( Tț Quantum cheat worth of items)  of 243 different types of items. Basically a quantum chest on some space age steroids, but a suitable recipe could be found for it.  The really interesting part of this mod to me is  the Automatic Dire Crafting Table as it allows automating those recipes

**Comment by Technus** [comment]
I knew you would mention the autocrafting table...
