### ISSUE TITLE
Possible balance for biogas

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#987]
So biogas is used the most of many powergens and can even be scaled up to be a good hv-ev powersource as seen on the server. My suggestion for a nerf to biogas and maybe make oil competitive with it is making biogas farms a bit harder to make. Possibly nerfing vanilla cactus farm/saplings->biogas recipe/other easy autofarms that make energy a breeze and not take much to setup a 2k+ eu/t powerplant from just some cactus+sand+water

**Comment by Dream-Master** [comment]
We can reopen it if it not working in the update.
