### ISSUE TITLE
Nitro Fuel bug

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#989]
We gat a ton od Nitro fuel cell in Nei

![image](https://cloud.githubusercontent.com/assets/2970688/21948186/c4be53e6-d9e9-11e6-82ab-0ba783f79c55.png)
 recipes are displayed wrong or be wrong

![image](https://cloud.githubusercontent.com/assets/2970688/21948207/e84f860e-d9e9-11e6-8802-8963fa67fe0a.png)

**Comment by Dream-Master** [comment]
@Technus 
any idea did you change something?

**Comment by Dream-Master** [comment]
I seems that all universal fluid cells schown only as NitroFuel cell in nei.

**Comment by kokochicken** [comment]
this is an nei glitch with universal cells. Shows recipes for all universal fluid cell stuff once you clikc it on one.

**Comment by Dream-Master** [comment]
@kokochicken how can fix it. I remeber i not have it before.

**Comment by Dream-Master** [comment]
Energy Addition mod cause this issue. i had it for testing reasons in the pack.

**Comment by Technus** [comment]
Unable to reproduce 1.3pre1, more info

**Comment by Technus** [comment]
Unable to reproduce in 1.3pr1

**Comment by Dream-Master** [comment]
ok so lets see when its on the server. Will close it now.
