### ISSUE TITLE
Unable to craft the 45slotted backpacks from Forestry

### ISSUE THREAD

**Issue by Bryfer** [GTNewHorizons/NewHorizons#991]
![forestry backpack](https://cloud.githubusercontent.com/assets/22825059/21954452/55398cc6-da51-11e6-8814-10a033474674.PNG)
_(NOTE: The brown backpack on the picture was supposed to have an mouse-arrow besides it, well, snipping tools removed it :P)_

The problem is that the backpacks are unplaceable inside the Carpenter :/

Backpacks I've tried Hunter's Builder's Miner's neither of them work in there. Correct item Id on the backpack (default Mode)
9x Woven Silk (4496:3)
Seed Oil (5000mb) (made from hazelnuts in squeezer)

**Comment by Dream-Master** [comment]
Ok will check recipes

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21954928/d608c796-da5f-11e6-8537-be4bdcf09224.png)

using /mt hand on your bag maybe the id or nbt differs

**Comment by Bryfer** [comment]
dont have permissions for those commands :/
ItemID is correct so it must be nbt in that case

**Comment by Bryfer** [comment]
Update: it works with an backpack that has never been used

**Comment by Dream-Master** [comment]
ok so i need to change the nbt thing

**Comment by Dream-Master** [comment]
``<Forestry:minerBag>`` before 
``<Forestry:minerBag>.withTag({UID: -1118044985, Slots: {}})`` after

**Comment by Dream-Master** [comment]
Ok nbt not works in the minetweaker script. i will add a shapless recipe where nbt is removed after it.
