### ISSUE TITLE
Quest suggestions Ass Line

### ISSUE THREAD

**Issue by Drobac** [GTNewHorizons/NewHorizons#992]
Quest for the assembly line crafting in the Tier 6 and above tab.
Crafting the parts for the assembly line and maybe the basic LuV GT parts for people who don't know how to use the assembly line

**Comment by Dream-Master** [comment]
Yes good idea @Drobac .

**Comment by DietmarKracht** [comment]
Maybe add another legendary quest for fusion reactor + plasma turbine but optional

**Comment by Dream-Master** [comment]
yes can do.

**Comment by Drobac** [comment]
And a legendary quest for T8 planets- Infinity ingots, avaritia tools
