### ISSUE TITLE
Twilight forest bugs

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#993]
Ok so, the hydra wont take any damage. I killed over 30-40 heads and it just keeps sitting there spasming. Random items from my inventory are being eaten by something while i am fighting. Random mobs spawning 1hitting me then despawning. Tons of random bugs. Hopefully add a way to progress without having to deal with these bugs or fix them.

**Comment by Dream-Master** [comment]
Twilight Forest not longer supported i guess. The Mod dev not seen for a long time. I dont know if others have the same issue.

**Comment by Drobac** [comment]
Koko is a derp
