### ISSUE TITLE
Feature Request:  Ability to remove fluids from the Input of Gregtech Machines

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/NewHorizons#994]
Hey guys,

If possible, I'd like to be able to somehow take fluids out of the input side of a machine, such as the Sulfuric Naphtha shown here, after I put it in, as many of the recipes require very specific amounts of fluids and getting the exact amount is difficult, if not impossible, forcing a player to break the machine to be able to get use out of it again.

![2017-01-14_12 56 51](https://cloud.githubusercontent.com/assets/10765948/21957289/ef335e54-da58-11e6-9a58-de49bae435c7.png)

I originally tried scooping the fluids out of the drum I had it in with a bucket, but Sulfuric Naphtha isn't one that can be bucket'd and when i used a universal fluid cell, the cell got consumed when i used it on a smeltry tank, but it placed the naphtha inside the tank.

Using Stacked Filled Universal Fluid Cells in general seems to be very buggy with the inventory.

**Comment by kokochicken** [comment]
possibly adding a 1-use cell that can take out of input slot? make it where it is only woth using if you have valuable stuff inside

**Comment by Dream-Master** [comment]
Yea its the same thing in Assembers. @Technus any idea here.

**Comment by Technus** [comment]
Non gt canon.

**Comment by Technus** [comment]
You can remove the fluid with plunger

**Comment by Nenluen** [comment]
Alternatively, an option or a tool that just moves the fluid from the input tank to the output tank, where it can then be removed through normal means.

Plunger does remove the fluid, but it voids it at 1,000 (L/mB) per plunger use.

**Comment by Dream-Master** [comment]
@Technus any idea? Or can this be closed ?

**Comment by Technus** [comment]
Not all machines with input tank have output tank, we can close this.
