### ISSUE TITLE
Harvest Golem doesnt replant wheat (with ordo upgrade)

### ISSUE THREAD

**Issue by ghoulsblade** [GTNewHorizons/NewHorizons#996]
Thaumcraft Golems with Harvest Core and Ordo upgrade cannot replant wheat from vanilla minecraft. they harvest it, leaving the farmed tile empty. Replant works ok for other plants like netherwarts, sugarcane and cotton(natura). We tried both Tallow Golems from basic thaumcraft as well as silverwood golems from gadomancy.

**Comment by Dream-Master** [comment]
@HelfirePVP any idea about Gadomancy?
@Drobac any idea about Thaumcraft Golems?

**Comment by HellFirePvP** [comment]
idk, we faced the same issue. It's nothing Gadomancy changes since we don't change/modify anything about their behavior. so.. *shrugs*

**Comment by ghoulsblade** [comment]
one suspicion: it seems vanilla wheat growth speed was reduced/modified by some mod, maybe thats related ?

**Comment by Dream-Master** [comment]
Pams harvestcraft interacts here.

**Comment by Dream-Master** [comment]
@HellFirePvP fixable or not ?

**Comment by Dream-Master** [comment]
guess not :(
