### ISSUE TITLE
TF deleting items

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/NewHorizons#997]
Ok so my night vision goggles and other items (circuit parts, hammer , etc) get deleted while in TF... wondering how to fix this dont want to remake stuff from bugs deleting it

**Comment by Dream-Master** [comment]
A bit more specific please. Fml logs please.
Can you reproduce it?

**Comment by Drobac** [comment]
Did you have a charm of keeping in your inventory?

**Comment by kokochicken** [comment]
No I did not. I was running around in tf look I g for goblin ruins and my items started deleting

**Comment by VermillionX** [comment]
Might also want to mention that TF progression is broken for you, koko.
