### ISSUE TITLE
Cant Wear backpack (Backpack's mod not Adventure backpack)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#998]
it say's u can wear it  here
Maby it can be made to have a bauble slot?
[](url)
>[it Simple hold a backpack in your hand and right click to open 
You can put any backpack in a separate slot. You access the slot by sneaking and pressing the key to open a backpack (default 'B'). When wearing a backpack in this slot the backpack can be opened by pressing the 'B' key. You can change the key in your controls.
When you wear a backpack it will show a 3D Model on the back of the player.](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286124-1-10-2-backpacks-v-3-0-1)

and when i try it wont let me 
![f44782031aa3e75328a58d65bf9a19fe](https://cloud.githubusercontent.com/assets/23045776/21959185/517c4bc8-da74-11e6-8ac9-b3eafe742c37.gif)

and it shows on the page this 
![04bdd1f52a3124553c5292f50569b1e0](https://cloud.githubusercontent.com/assets/23045776/21959194/a3ba99bc-da74-11e6-8cd2-2241ee1f87bd.gif)
![c94bdf992ff8ac4ba67833db29048396](https://cloud.githubusercontent.com/assets/23045776/21959198/ae78905c-da74-11e6-9f08-262d5dee3468.png)

**Comment by Ugachaga** [comment]
shift+'B' by default
