### ISSUE TITLE
Looking at players causes massive FPS drop.

### ISSUE THREAD

**Issue by trueangryyeti** [GTNewHorizons/NewHorizons#999]
As soon as a player comes into your view you receive a massive FPS drop. Happens for everyone I've asked. I personally go from 300 to 100 fps with one person in my view and then down to 50fps with two people in my view.

**Comment by Technus** [comment]
Use search function...
#837

**Comment by Dream-Master** [comment]
@Tec better People report here bugs then in the Forum or in the chat. 
@trueangryyeti yes but tec is right look first if thi issue allready reported.

**Comment by trueangryyeti** [comment]
@Dream-Master That was my bad,  was on mobile and didn't see it when I searched.
